= Roll Playing System

[quote]
____
*We like dice and arithmetic!*
____


Roll-Playing refers to a game system that depends heavily on dice rolls.
Rolling dice does not preclude telling stories or playing personas with character and passion.
The Roll-Playing System depends on the dice to determine outcomes rather than relying on players to determine effects.
For example, the Roll-Playing System determines a failed grenade attack with tables and dice rolls. 
When using the Role-Playing System, the players would determine what happens with a failed grenade attack. 
The storytelling is still up to the players in both rulesets.
The Roll-Playing System allows the dice to have a greater on the storytelling.

NOTE: *Combat in the Roll-Playing System works best with miniatures on hex paper.*

The Roll-Playing System uses the tactical combat rules and the xref:roll_playing_system:kilo_die_mechanic.adoc[Kilodie Mechanic, window=_blank].
This ruleset works best with hex paper and miniatures on a huge table.
The Roll-Playing System has been waiting on the virtual tabletops of today for decades. 
The Roll-Playing System employs all kinds of dice in all sorts of unique combinations.
A lot of arithmetic and reading is required. 
Onboarding of new players requires patience and supportive teaching. 

.*Roll-Playing System is for you if...*
* You play different RPGs
** If you don't know what an RPG is, Roll Rules are not for you
* You like to roll dice
* You are not afraid of arithmetic
* You like details

:art: nuts_for_dice.png
:width: 350px
:snark: Nuts for dice.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Several polyhedral dice, chewed pencil and mouse wearing headphones.

include::ROOT:partial$articulate.adoc[]

== Kilodie Mechanic
The kilodie is a die roll unique to EXP.
This die roll exists in the tactical combat rules.
The tactical combat rules are the bespoke combat rules for the Roll-Playing System.
The kilodie generates a number between 1 and 1000.
To learn how to use it see xref:roll_playing_system:kilo_die_mechanic.adoc[Kilodie Mechanic, window=_blank].
The tactical combat rules depends on the kilodie roll.
All combat adjustments from Defence Rating to attack rolls use the kilodie mechanic.

It is conceivable to extend the kilodie mechanic to replace all rolls in EXP.
However, kilodie rolls do not create a nice curve.
On a kilodie, 001, 042 and 1000 are equally likely.
Rolling 3d6 does create a nice curve.
On 3d6, 3 and 18 are rare, and 9 is very common.
The 3d6 makes for more organic results with common and uncommon numbers.

== Embrace The High Roll
The higher a player rolls on the dice, the better it is for her persona.
When the player is rolling dice to see what happens to her persona, rolling high is almost always her advantage.
When the referee is rolling dice to see what happens to her referee persona, rolling high is better for the referee persona.
There are exceptions to embracing the high roll, but the higher number the better it is for the persona.
The gory details of all the possible rolls are discussed in xref:uncombat:all_those_rolls.adoc[All Those Rolls, window=_blank].
A quick overview of significant rolls is covered below.

== Adjusting Rolls
In the Roll-Playing System, dice rolls can are subject to many adjustments.
In keeping with embracing the high roll, positive adjustments help the persona, and negative adjustments hinder the persona.
For example, a bonus of plus three would add three points to the player's die roll.
Bonuses make success more likely, but success is not guaranteed.
Physically strong personas increase their damage when using striking weapons.
A Force Bonus is a bonus that increases a damage roll.

Adjustments:: 
Any number that alters a dice roll is an adjustment.
An adjustment could be beneficial or detrimental.

Bonus:: 
A bonus is any adjustment that benefits the player's dice roll by increasing its value.
Usually, a number is added to the die roll to improve (not guarantee) the chance of success.
For example, the player increases her attack roll by adding her proficiency bonus to the attack roll. 

Penalty:: 
A penalty is any adjustment that impairs the player's dice roll by changing its value.
Usually, a negative number is added to the die roll to decrease the chance of success.
In heavy fog, the player adds a negative number to her attack roll. 
Sometimes a penalty will increase the target number that the player needs to beat. 
For example, a task difficulty may double and therefore decrease the chance of success.

=== Attributes
The persona's attributes, like strength and intelligence, will influence the player's dice 
rolls.
The attribute can both directly and indirectly affect actions.
A persona that is attempting to lift a barrel may get a direct benefit from her strength attribute.
A persona shooting a gun may get a mix of benefit from her dexterity, intelligence and awareness.

=== Family
The family types can affect player rolls through special abilities assigned to them.
A maintenance robot may get a bonus doing repairs.
An equine anthro may enjoy an increase in their movement rate. 
An alien may be able to climb really well due to specialized limbs. 

=== Vocation
The player rolls for completing tasks and skills are influenced by persona vocations.
A mechanic will have interests and expertise that improve task rolls. 

=== Proficiency
Proficiency is a legacy term for weapon skills, and hails from the last millennium.
By strict definition, a skill is a proficiency and vice versa.
So a player with skill in a weapon can add more bonuses to her attack roll in combat. 

=== Role-Playing 
Role playing can improve player rolls with ad hoc, or prescribed, roll bonuses.
A small bonus may be added to an attack roll or a task roll when the player inspires the table. 

== All Those Rolls
The Roll-Playing System is overflowing with rolls for all kinds of things. 
The most common types of rolls are covered here.
The gory details of all the possible rolls are discussed in xref:uncombat:all_those_rolls.adoc[All Those Rolls, window=_blank].

NOTE: All your rolls are belong to us.

=== Attack Rolls
Attack rolls are the most common rolls made by players. 
An attack roll is made every time the persona tries to harm another persona.
The player will roll the kilodie and compare that value to the target's Defence Rating.
If the attack roll plus adjustments are greater than the target's Defence Rating, the player usually inflicts damage on the target.
A damage roll follows a successful attack roll.
The higher the number the player rolls, the more likely her persona will be victorious in combat.
There are more than fifteen sections under the heading of xref:combat:a_introduction.adoc[Tactical Combat, window=_blank] that cover the finer details. 

=== Attribute Rolls
Attribute rolls are a collection of rolls that pit the persona's attributes against specific challenges.
The player usually rolls a twenty-sided die for an attribute roll.
Two players could make attribute rolls to see who's persona wins an arm wrestle.
A player could make an attribute roll to see if a poison harms her persona.
The higher the player rolls, the more likely things will go well for the persona.

.*Example Attribute Rolls*
* Poison roll pits the persona's physical hardiness against a poison
* Psionic roll pits the persona's consciousness against a mental invasion
* Radiation roll tests the persona's physical resilience against radiation
* Jelly roll tests the player's ability to snack without making a mess on the hex mat

=== Task Rolls
These rolls are made by the player when her persona is attempting a skill-based maneuver.
The player most often rolls percentile dice to determine task rolls. 
The higher the player rolls, the more likely the persona will be successful in her task.
Simple tasks have a low difficulty, and more complex tasks have a higher difficulty.
The player is competing with this difficulty to determine success.

=== Generative Rolls
Players make these rolls to generate a purely random outcome.
They are not competitive, and rolling high or low does not indicate a win or a loss.
The player uses percentile dice to make generative rolls.
They either determine if a random event happens or pull random data from a table.

==== Table Rolls
The player is usually rolling a percentile die to 'generate' data. 
Generative rolls determine what kind of artifact a persona finds. 
A high roll does not make a difference when generating an artifact.
Data tables are in alphabetical order, and a higher roll only indicates the starting letter of the artifact.
An excellent artifact roll for the persona could be six on one table but fifty-six on another table.

==== Chance Rolls
Chance rolls determine if a specific event occurs.
The lower the roll, the more likely the event will occur.
Sometimes the event is beneficial to the persona, and sometimes it is not.
For example, there may be a 15% chance of a fire starting. 
The persona may, or may not, want the fire to start.


// todo .Success vs Random
// todo . Success roll 
// todo .. affects the persona in that moment
// todo .. have a success, tie fail outcome
// todo . Random rolls 
// todo .. deterministic 
// todo .. randomly decide a skill, Toy or description
// todo .. may be good, bad or indifferent, but not success fail
//
// todo .Success Rolls
// todo . Static Rolls (one roll vs fixed number)
// todo .. attack roll
// todo .. Saving Throws
// todo .. Attribute Checks - within one persona (same as a save?)
// todo . Dynamic Rolls (one roll vs one roll)
// todo .. Attribute Challenge - between 2 personas
// todo .. Sphincter Roll