= Roll Playing System

[quote]
____
*We like dice and arithmetic!*
____

Roll playing refers to a game system that depends heavily on dice rolls.
Rolling dice does not preclude telling stories or playing personas with character and passion.
The Roll Playing System depend on the dice to determine outcomes rather than relying on players to determine effects.
For example, the Roll Playing System determines a failed grenade attack with tables and dice rolls. 
When using the Role Playing Rules, the players would determine what happens with a failed grenade attack. 
The storytelling is still up to the players in both rulesets.
The Roll Playing System allow the dice to have a greater on the storytelling.

NOTE: *Combat in the Roll Playing System works best with miniatures on hex paper.*

The Roll Playing System use the tactical combat system and the xref:roll_playing_system:CH00_kilo_die_mechanic.adoc[Kilodie Mechanic, window=_blank].
This ruleset works best with hex paper and miniatures on a huge table.
The Roll Playing System have been waiting on the virtual tabletops of today for decades. 
The Roll Playing System employ all kinds of dice in all sorts of unique combinations.
A lot of arithmetic and reading is required. 
Onboarding of new players requires patience and supportive teaching. 

.*Roll Playing System are for you if...*
* You play different RPGs
** If you don't know what an RPG is, Roll Rules are not for you
* You like to roll dice
* You are not afraid of arithmetic
* You like details

:art: nuts_for_dice.png
:width: 350px
:snark: Nuts for dice.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Several polyhedral dice, chewed pencil and mouse wearing headphones.

include::ROOT:partial$articulate.adoc[]

== Kilodie Mechanic
The kilodie is a die roll unique to EXP.
This die roll exists in the tactical combat system.
The tactical combat system is the bespoke combat system for the Roll Playing System.
The kilodie generates a number between 1 and 1000.
To learn how to use it see xref:roll_playing_system:CH00_kilo_die_mechanic.adoc[Kilodie Mechanic, window=_blank].
The tactical combat system depends on the kilodie roll.
All combat adjustments from Defence Rating to attack rolls use the kilodie mechanic.

It is conceivable to extend the kilodie mechanic to replace all rolls in EXP.
However, kilodie rolls do not create a nice curve.
On a kilodie, 001, 042 and 1000 are equally likely.
Rolling 3d6 does create a nice curve.
On 3d6, 3 and 18 are rare, and 9 is very common.
The 3d6 makes for more organic results with common and uncommon numbers.

== Embrace The High Roll
The higher a player rolls on the dice, the better it is for her persona.
When the player is rolling dice to see what happens to her persona, rolling high is almost always her advantage.
When the referee is rolling dice to see what happens to her referee persona, rolling high is better for the referee persona.
There are exceptions to embracing the high roll, but the higher number the better it is for the persona.
The gory details of all the possible rolls are discussed in xref:roll_playing_system:CH16_Special_Rolls.adoc[All Those Rolls, window=_blank].
A quick overview of significant rolls is covered below.

== Adjusting Rolls
In the Roll Playing System, dice rolls can are subject to many adjustments.
In keeping with embracing the high roll, positive adjustments help the persona, and negative adjustments hinder the persona.
For example, a bonus of plus three would add three points to the player's die roll.
Bonuses make success more likely, but success is not guaranteed.
Physically strong personas increase their damage when using striking weapons.
A Force Bonus is a bonus that increases a damage roll.

Adjustments:: 
Any number that alters a dice roll is an adjustment.
An adjustment could be beneficial or detrimental.

Bonus:: 
A bonus is any adjustment that benefits the player's dice roll by increasing its value.
Usually, a number is added to the die roll to improve (not guarantee) the chance of success.
For example, the player increases her attack roll by adding her proficiency bonus to the attack roll. 

Penalty:: 
A penalty is any adjustment that impairs the player's dice roll by decreasing its value.
Usually, a negative number is added to the die roll to decrease the chance of success.
In heavy fog, the player adds a negative number to her attack roll. 

== Abilities and Skills
The most common way players adjust their dice rolls is through their persona's attributes, knowledge, and experience.
Personas have attributes that determine their intelligence and dexterity.
Personas have family types that determine species-specific abilities.
Personas can have mutations that grant unique abilities.
Personas have vocations that determine particular aptitudes and areas of expertise.

=== Ability
Abilities are innate abilities that only the persona can possess.
An ability is not learnable and comes baked in with the persona.
A rodent persona can see in the dark. 
This ability does not change over time, and another persona cannot learn this ability. 
A mutation may allow a mutant to vomit poison gas.
The mutation is an ability unique to that mutant, and another persona cannot learn this ability. 
Abilities may improve slightly as the persona gains more experience, but abilities don't have scores like skills or proficiencies.

==== Gift
A gift is the kind of ability that cannot be explained by biology, chemistry or physics in Physical Space.
A gift is not learnable, teachable or understandable by the persona.
The mystical warriors called knites have inexplicable powers that are more gifts than abilities.
A mutant with extrasensory perception may not understand the gift of this extraordinary power. 

=== Skill
Skills are learnable aptitudes that the persona possesses.
The mutant's vocation usually determines her skills.
A persona can learn and intentionally improve a skill.
Skills usually have scores like climbing two or juggling one.
A mechanic persona could improve her engines skill from two to three.
The higher skill score improves her chance of success at engine related rolls and makes her better than a colleague with engines one.

Skills are usually limited to the scope of the persona's vocation.
A mechanic will not be good at psychotherapy, and a mercenary will not be able to find shelter.
The skills make it more likely for a player to make a successful roll when attempting maneuvers. 

==== Proficiency
Proficiency is a particular kind of skill that refers to weapons in the tactical combat system.
By strict definition, a skill is a proficiency and vice versa.
The tactical combat system uses a byzantine and archaic system of proficiencies regarding weapons.
A persona proficient with a sword enjoys more bonuses on her attack roll than if she were to use a mace.
Attack roll bonuses can become tremendous for the persona who becomes highly proficient with her chosen weapon(s).

Proficiency is a legacy of the last millennium.
However, the proficiency system in tactical combat is balanced and heavily playtested. 

== All Those Rolls
The Roll Playing System are overflowing with rolls for all kinds of things. 
The most common types of rolls are covered here.
The gory details of all the possible rolls are discussed in xref:roll_playing_system:CH16_Special_Rolls.adoc[All Those Rolls, window=_blank].

NOTE: All your rolls are belong to us.

=== Attack Rolls
Attack rolls are the most common rolls made by players. 
An attack roll is made every time the persona tries to harm another persona.
The player will roll the kilodie and compare that value to the target's Defence Rating.
If the attack roll plus adjustments are greater than the target's Defence Rating, the player usually inflicts damage on the target.
A damage roll follows a successful attack roll.
The higher the number the player rolls, the more likely her persona will be victorious in combat.
There are more than fifteen sections under the heading of xref:roll_playing_system:CH27_Tactical_Combat.adoc[Tactical Combat, window=_blank] that cover the finer details. 

=== Attribute Rolls
Attribute rolls are a collection of rolls that pit the persona's attributes against specific challenges.
The player usually rolls a twenty-sided die for an attribute roll.
Two players could make attribute rolls to see who's persona wins an arm wrestle.
A player could make an attribute roll to see if a poison harms her persona.
The higher the player rolls, the more likely things will go well for the persona.

.*Example Attribute Rolls*
* Poison roll pits the persona's physical hardiness against a poison
* Psionic roll pits the persona's consciousness against a mental invasion
* Radiation roll tests the persona's physical resilience against radiation
* Jelly roll tests the player's ability to snack without making a mess on the hex mat

=== Task Rolls
These rolls are made by the player when her persona is attempting a skill-based maneuver.
The player most often rolls percentile dice to determine task rolls. 
The higher the player rolls, the more likely the persona will be successful in her task.
Simple tasks have a low degree of difficulty, and more complex tasks have a higher degree of difficulty.
The player is competing with this degree of difficulty to determine success.

=== Generative Rolls
Players make these rolls to generate a purely random outcome.
They are not competitive, and rolling high or low does not indicate a win or a loss.
The player uses percentile dice to make generative rolls.
They either determine if a random event happens or pull random data from a table.

==== Table Rolls
The player is usually rolling a percentile die to 'generate' data. 
Generative rolls determine what kind of artifact a persona finds. 
A high roll does not make a difference when generating an artifact.
Data tables are in alphabetical order, and a higher roll only indicates the starting letter of the artifact.
An excellent artifact roll for the persona could be six on one table but fifty-six on another table.

==== Chance Rolls
Chance rolls determine if a specific event occurs.
The lower the roll, the more likely the event will occur.
Sometimes the event is beneficial to the persona, and sometimes it is not.
For example, there may be a 15% chance of a fire starting. 
The persona may, or may not, want the fire to start.


//.Success vs Random
//. Success roll 
//.. affects the persona in that moment
//.. have a success, tie fail outcome
//. Random rolls 
//.. deterministic 
//.. randomly decide a skill, Toy or description
//.. may be good, bad or indifferent, but not success fail
//
//.Success Rolls
//. Static Rolls (one roll vs fixed number)
//.. attack roll
//.. Saving Throws
//.. Attribute Checks - within one persona (same as a save?)
//.. PT Rolls
//. Dynamic Rolls (one roll vs one roll)
//.. Attribute Challenge - between 2 personas
//.. Sphincter Dice