= Avarian

:art: avarian.png
:width: 250px
:snark: Birds of a feather.
:artist: Peggy Lynn McIsaac
:date: 1990
:license: CC BY-SA 4.0
:description: Drawing of a humanoid bird holding a stethoscope.

include::ROOT:partial$articulate.adoc[]

// Table 4.6 Avarian Data
.*Avarian Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|Particulars for hatching an avarian player persona.

s|Attribute Minimums
2+<|AWE 12; CON 10; DEX 10

s|Attribute Adjustments
2+<|AWE +3; CON -1; DEX +2; STR -2

s|Age
2+<|13-16 (1d4+12) years

s|Abilities
2+<|<<_flying,Flying>>, <<_ambush_detection,Ambush Detection>>

s|Size
s|Hite (cm)
s|Wate (kg)


|Stout
|175+(3d10)-20
|65

|Lean
|175+(2d20)-40
|71

3+<|xref:anthros:anthro_sizezeze.adoc[Calculate Hite and Wate]

|===


Avarian is the short name for Hominidae Homo Avis.
Avarians are humanoid bird people.
An avarian persona can choose from many avian life forms.
For example, hawk, parrot, albatross, ostrich, penguin, vulture, swallow, puffin, robin, etc.
Avarians are not humans with wings.
An avarian has two legs, two arms, a torso and a face.
Feathers or down cover their skin, they sport beaks, and they have clawed hands and feet.

Some avarians from popular culture are https://en.wikipedia.org/wiki/Ekek[ekek,window=_blank], https://en.wikipedia.org/wiki/Karura[kakura,window=_blank], https://en.wikipedia.org/wiki/Garuda[garuda,window=_blank], and https://en.wikipedia.org/wiki/Thoth[Thoth,window=_blank].

Avarian wings are cosmetic and do *not* automatically allow the persona to fly.
Flying personas increase the complexity of the game exponentially.
Flying avarian personas are possible if they fit into the referee's campaign milieu. 
The player can choose for her persona to have no wings, decorative wings, or a full set of wings.

.*Decorative*
Decorative wings stick out of her back and are *never* functional.
Decorative wings do not inhibit the function of the persona at all.
A set of decorative wings would comfortably fold under her armour.
The persona can flutter and manipulate her decorative wings, but they will never hinder her.

.*Full Wings*
Full wings stick out of her back and are *not* automatically functional.
If the referee permits, there is a chance for full wings to be functional.
Full wings require modified clothing and armour.
Full wings can never retract or hide, and they can become a hindrance to the persona.
There is a chance that full wings can be functional wings allowing the persona to fly.
Full wings are majestic and offer a Charisma bonus of plus two.

== Flying
A flying persona is a significant challenge for the referee. 
If the story works better by having avarians flying around, always choose story and fun over rules.

For an avarian to be able to fly, she must have functional wings.
Only full wings can be functional. 
There is a 1/2 percent change per point of Dexterity that the persona will have fully functional flying wings.
An avarian persona with a Dexterity of twelve has a six percent chance of flight.

Flying allows the persona to have three-dimensional movement and to hover in the air.
The persona can fly at up to double her movement rate.
A persona with a move of 6 h/u can fly at 12 h/u.
That is 12 h/u in any direction.
 
Flying offers no benefit underwater.
Full wings make swimming nearly impossible and limit the persona to a rudimentary swimming rate of 1 h/u.
Flying offers no extra benefit in low gravity and does not work at all beyond 1.5 gravities.
Flying does not work in low or heavy atmospheres. 

Functional wings impair land movement, and the persona's halves her movement rate on the ground.

== Ambush Detection
Avarians are flighty, nervous and aware of their surroundings.
These attributes make them hard to ambush.
An avarian triples her Awareness when detecting an ambush.
Successfully ambushing an avarian is a difficult task indeed.

