= Ursidae

:art: ursidae.png
:width: 250px
:snark: Baring arms.
:artist: Peggy Lynn McIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of ursidae pirate wielding sword while doing yoga tree pose.

include::ROOT:partial$articulate.adoc[]

// Table 4.16 Ursidae Data
.*Ursidae Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|The bare facts to create an ursidae player persona.

s|Attribute Minimums
2+<|DEX 4; INT 4; STR 12

s|Attribute Adjustments
2+<|CON +1; INT -2; STR +2

s|Age
2+<|9-12 (1d4+8) years
s|Abilities
2+<|<<_hibernation,Hibernation>>, <<_frenzy,Frenzy>>


s|Size
s|Hite (cm)
s|Wate (kg)

|Big
|176+(2d20)-20
|78

|Bigger
|208+(2d20)-20
|139


3+<|xref:anthros:anthro_size.adoc[Calculate Hite and Wate]

|===

Ursidae is short for Hominidae Homo Ursus.
Ursidae are big, furry humanoid bears.
Typical appearances of ursidae: grizzly, panda, black bear, etc.
They have rotund bodies, bear-like heads and claw-tipped stubby hands.
Regardless of the bear type chosen, the persona remains a bipedal humanoid that naturally possesses no more abilities than those described here.

== Hibernation
Ursidae can hibernate. 
The hibernation is so deep that they appear dead.
Their metabolism is so slow only vets, and other ursidae can tell whether an ursidae is dead or just resting.
Ursidae will only hibernate when they decide to do so.
Hibernation does not automatically activate.
Ursidae cannot hibernate if they have negative hit points.
An ursidae with negative HPS is dying like all other anthro personas.

Once bedded down to hibernation, the ursidae will sleep for 1-6 (1d6) days.
The referee determines the hibernation duration and may keep that info secret from the players.
While hibernating, the ursidae will heal one hit point for every two points of Constitution each day.
So an ursidae hibernating for four days with a 14 Constitution would heal a total of 28 hit points each day.
Metabolic poisons do not affect an ursidae while she's in hibernation.

====
In past versions of EXP, there was a chance that an ursidae could die during hibernation. 
Fellow expedition members would only notice once the ursidae started to smell bad. 
However, this is a kindler, gentler version of EXP.
====

It is both difficult and dangerous to wake up a hibernating ursidae.
An ursidae's fellow personas may attempt to wake her once per day, and if successful, she may <<_frenzy,frenzy>>.
The chance of successfully waking a sleeping ursidae is equal to the persona's Charisma.
So a colleague with a ten Charisma has a 10% chance of waking the ursidae.
Regardless of the nature of the attempt, the chance of waking is the same.
For instance, whispering softly into her ear will be as useful as a bucket of cold water.


== Frenzy
In complete juxtaposition to hibernation is frenzy.
Frenzy is a mindless mauling attack where the persona drops everything and unleashes furry fury.
The persona rends and tears at the primary cause of the dilemma with her claws.
When in a frenzy, the persona cannot hear anything and does not respond to commands, demands or screams.

The persona can enter a frenzy by choice.
An ursidae can also be forced into a frenzy if she is awoken from hibernation or intellectually stumped.
When intellectually stumped, the persona has a 1% (a roll of 42 on a 1d100) chance of a spontaneous frenzy.
When woken from hibernation, the persona has a 42% chance of forced frenzy.

An ursidae frenzy will last for 2-16 (2d8) units. 
The referee determines the frenzy duration and usually keeps this info secret from the players.
The feral combat state continues for its entire duration.

Initially, the frenzy is good as the persona starts by attacking enemies or inanimate objects.
However, the frenzy quickly becomes dangerous as the raging fur tank moves on fellow personas when she runs out of things to attack.
Arresting an ursidae frenzy requires a skilled vet, a skilled biologist or a powerful stun weapon.

Frenzy turns the persona into a flailing claw machine of destruction.
The ursidae will receive 1 and 1/2 attacks per experience level per unit.
A frenzied ursidae a minimum of two and a maximum of six attacks per unit.
For example, a 4th level ursidae would get six attacks per unit.

Each attack is either a punch, claw, bite or body slam.
No weapons are allowed.
Each attack is a non-powered thrusting and striking attack (Strike). 
A successful hit inflicts 1-6 (1d6) hit points of damage.
A 6th level ursidae with an eighteen Strength would get six attacks per unit, capable of inflicting 10 to 15 hit points of damage

Frenzied ursidae completely ignore their environment and their physiology.
No damage system shock (DSS) rolls apply during the frenzy.
The frenzied persona will also continue to fight with a negative HPS total.
A frenzied ursidae will literally attack until dead.

