= Insectoid

:art: anthro_insectoid.PNG
:width: 250px
:snark: Medical mantis
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a humanoid praying mantis with medical kit.

include::ROOT:partial$articulate.adoc[]

// Table 4.12 Insectoid Data
.*Insectoid Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|Data required to hatch an insectoid player persona.

s|Attribute Minimums
2+<|MND 12

s|Attribute Adjustments
2+<|Nil

s|Age
2+<|21-32 (1d12+20) years

s|Abilities
2+<|<<_neural_stability,Neural Stability>>

s|Size
s|Hite (cm)
s|Wate (kg)
// One size fits all not present

|Stout
|125+(8d20)-40
|60

|Lean
|150+(6d20)-50
|55

3+<|xref:CH04_Anthros_Size.adoc[Calculate Hite and Wate]

|===

Insectoid is short for Hominidae Homo Insectum.
Insectoids are humanoid bugs.
An insectoid persona could resemble a bee, spider, worm, slug, flea, mosquito, beetle, tick, louse, moth, grasshopper, dragonfly, etc.
Every insectoid has two arms, two legs, a torso and a face.
The insectoid may sport the head of a fly and have a soft exoskeleton for the skin.
The persona may also have additional decorative limbs or wings.
The anthro type is entirely decorative.
For example, an insectoid spider would not be poisonous or build a web.
An insectoid may have a stinger for a tail, but it would not be sharp or poisonous.

== Neural Stability
Insectoids have very resilient brain structures.
Insectoids are resistant to psionic attacks, torture, advertising and general beguiling.
An insectoid receives a bonus of +1 for every 4 points of Mind against such attacks.
For example, an insectoid with 15 Mind would get a +4 in psionic roll against a psionic mutation attack.