= Equine

:art: equine.png
:width: 250px
:snark: Getting started with equines.
:artist: Peggy Lynn McIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid horse sprinter leaving starting blocks.

include::ROOT:partial$articulate.adoc[]

// Table 4.8 Equine Data
.*Equine Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|What every player needs to know to make an equine persona.

s|Attribute Minimums
2+<|DEX 8; STR 10

s|Attribute Adjustments
2+<|DEX +1; INT -1; MND -2; STR +2

s|Age
2+<|10-29 (1d20+9) years

s|Abilities
2+<|<<_gallop,Gallop>>, <<_jumping,Jump>>

s|Size
s|Hite (cm)
s|Wate (kg)

|Quaint
|179+(2d20)-20
|71

|Robust
|186+(2d20)-20
|81

3+<|xref:CH04_Anthros_Size.adoc[Calculate Hite and Wate]

|===

Equine is the short form for Hominidae Homo Equus.
Homo Equus are humanoid horse people. 
Equines can choose to resemble any hoofed animal: Clydesdale, gazelle, elephant, cow, goat, moose, giraffe, etc.
Equine are bipedal humanoids, and they are not quadrupeds.
Equines have horse-like heads, hooves for feet, and fly-swatting tails. 
Possibly their cured skin makes good leather.
A Homo Equus unicorn can have a horn on her head but possesses no other magical qualities.

The equines are fast.
All equines are fast. 
Cows, deer, horses, and goats all enjoy the gallop ability.
All equine get a bonus of +3 h/u on their movement rate.
So an equine with a move of five h/u would move at eight h/u.
This movement rate is not an equine gallop and represents its natural movement rate.

== Gallop
Equines have can also gallop.
A gallop is a full-out clippity cloppity sprint. 
A galloping equine moves at two and ½ times her movement rate.
If the equine's movement rate was eight h/u, she could gallop at the fantastic speed of twenty h/u.
An equine cannot do anything other than Gallop while galloping.
For example, the equine cannot attack while galloping but could use a psionic mutation. 

== Jumping
Equines are also excellent jumpers.
Equine can jump horizontally (a leap) two hexes per 8 points of STR.
Equine can jump vertically (a jump) 1.5 times their Hite.
Jumping and leaping are part of an equine's natural movement rate.
An equine can jump up or down without any movement penalty.
An equine can add a leap into her movement rate but cannot use it to extend her movement.
Jumping does not work with galloping at any time for any reason.



