= Anthro Type Selection

At this point, the player's anthro is merely a list of numbers.
Her persona may be strong or smart but has no form.
Choosing a persona type is the first step in giving the persona a literal shape.
The player gets to make choices, but as usual, the dice guide her options.
The persona's attributes determine from which anthro types the player may choose.
Using the Anthro Type Table represents a bit of a legacy in the ruleset.
Some anthro types are less common due to their unique abilities and attribute adjustments. 
A player whose persona has a Strength less than ten cannot have an equine anthro type. 
A persona with a Dexterity of twelve or less cannot be a feline.

In the past, these kinds of creative limitations were commonplace. 
As role-playing games have matured in the last 40 years, choice restriction seems miserly.
However, balance in the roll playing system is based on these kinds of limitations.
One can find a <<_alternate_anthro_type_selection,compromise>> below. 
Don't let rules get in the way of the story or fun.

The player and referee compare the persona's list of attributes to the attribute minimums one the Anthro Type Table. 
This comparison results in a list of anthro types from which the player can choose.

include::ROOT:partial$table/anthro_genus_selection.adoc[]

== Attribute Minimums
Anthro attribute minimums serve two purposes. 
1) organize anthro types based on physical abilities.
2) ensure a minimum attribute score for the anthro type.

The restrictions ensure that hardy anthro types have a high Constitution, that smart anthro types have high Intelligence, and that strong anthro types have high Strength.

Persona attribute minimums are part of a selection process and do represent a protected attribute score.
In gameplay, ageing, mutation or injury can drop an attribute score below the anthro type's minimum.
A persona's Charisma score can drop below her anthro type minimum due to burns.
A persona's Strength can drop below her anthro type minimum due to ageing or injury.

== Example Anthro Type Selection
A player has generated a persona with the following attributes:  AWE 6, CHA 15, CON 17, DEX 9, INT 14, MND 12, STR 6 AND HPS 42.
The player can choose from the following anthro types avarian, florian, humanoid, insectoid, purestrain and rodentia.

include::ROOT:partial$table/anthro_genus_selection_example.adoc[]

== Alternate Anthro Type Selection
Players can skip the arduous procedure of comparing attribute types and choose their anthro type directly.
The referee and players must give care to game balance if the straight selection model. 
Expeditions will quickly become overpowered and full of ursidae spies and reptilian knites without some balance.
If the player chooses an anthro type purely for cosmetic and story reasons, they should forfeit the abilities and attribute adjustments of the anthro type.
So if a player always wanted to look like a panda bear but lacks the attributes, she can look like a panda bear but does not get hibernation, frenzy or plus two on her Strength. 
Choosing appearance over abilities and attributes is called the "I wanna look like" loophole. 

== Explaining Anthro Delivery Data
Once the player has chosen her persona's anthro type, she records it on her persona record sheet.
Each anthro type has a Delivery Data Table.
Each table is unique to the anthro type and contains essential information about the type.
Below we use the  Ursidae Delivery Data table to explain the info.

.*Ursidae Delivery Data*
[width="75%",cols="<,<,<",frame="all"]
|===
3+<|The bare facts to bear an ursidae player persona.

s|Attribute Minimums
2+<|DEX 4; INT 4; STR 12

s|Attribute Adjustments
2+<|CON +1; INT -2; STR +2

s|Age
2+<|9-12 (1d4+8) years
s|Abilities
2+<|Hibernation, Frenzy

s|Size
s|Hite (cm)
s|Wate (kg)

|Big
|176+(2d20)-20
|78

|Bigger
|208+(2d20)-20
|139

3+<| xref:anthros:anthro_size.adoc[Calculate Hite and Wate]

|===

=== Attribute Minimums
The required attributes for an ursidae are DEX 4, INT 4, and STR 12.  
See above for details ad nauseam.

=== Attribute Adjustments
These are the adjustments made to the persona's attributes.
Strong personas get even stronger, and weak personas may get even weaker.
The ursidae persona would take an Intelligence penalty of -2.
She would also enjoy a Constitution bonus of +1 and a Strength bonus of +2.
These attribute adjustments make the ursidae strong, hardy, but not too smart
An anthro type attribute penalty cannot drop an attribute below the type attribute minimum.
These attribute adjustments are important because attributes influence a persona's choice of vocation.
The player records the adjusted attributes on the persona record sheet. 

=== Age
The starting age range of the persona in years.
Ages vary wildly from anthro type to anthro type. 
Most of the anthro ages fall into the young adult category.
In the case of an ursidae, the player would roll 1d4 and add 8.
The die roll generates an age between 9 and 12 in years.
The player records her persona's age on the persona record sheet. 

=== Abilities
Abilities are cool things that the anthro type can do. 
Abilities are part of the anthro type, and they are not mutations.
All ursidae have frenzy and hibernation
The player can read the details of frenzy and hibernation in the 
 
=== Hite and Wate
Hite is in centimetres (cm), and wate is in kilograms (kg).
A centimetre is shy of half an inch.
A kilogram is slightly more than 2 pounds. 
The delivery data lists two different sets of hite and wate.
The player chooses between the sizes big and bigger.
Their titles are self-explanatory for the ursidae.
In general, ursidae are big.

Not all anthro types have a choice between larger and smaller sizes. 
These are the "one size fits all" anthro size.
Gender does not determine the anthro size in EXP.
Anthro size a player's choice.

The hite and wate listed here are average hite and wate.
To calculate the persona's exact hite and wate, jump to xref:anthros:anthro_size.adoc[Calculate Hite and Wate].



