= Feline

:art: feline.png
:width: 250px
:snark: A catsi tab.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid cat leaning on taxi cab.

include::ROOT:partial$articulate.adoc[]

// Table 4.9 Feline Data
.*Feline Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|Feline data for creating this anthro type is below.

s|Attribute Minimums
2+<|AWE 8; CHA 8; DEX 13

s|Attribute Adjustments
2+<|DEX +2; CON -2; STR -1

s|Age
2+<|5-10 (1d6+4) years

s|Abilities
2+<|<<_ambush,Ambush>>, <<_night_vision,Night Vision>>

s|Size
s|Hite (cm)
s|Wate (kg)


|Skinny
|150+(1d20)-9
|45

|Chubby
|150+(1d20)-6
|48

3+<|xref:anthros:anthro_sizeze.adoc[Calculate Hite and Wate]

|===

Feline is short for Hominidae Homo Felis.
Felines are humanoid cat people.
Some of the cat types that felines may resemble are siamese, lion, tiger, puma, jaguar, leopard, ocelot, etc.
Felines have furry bodies, long slender tails and mouths full of sharp little teeth.
All felines have the same abilities. 
For example, a leopard feline persona could *not* accelerate up to 100 km/h.

Some felines from popular culture include https://en.wikipedia.org/wiki/Bakeneko[banenenko, window=_blank] and https://en.wikipedia.org/wiki/Kzin[kzin,window=_blank].

Felines have excellent balance and agility.
All felines have a +30% movement bonus.
A feline with a move of 5 h/u increase to 7 h/u.

== Ambush
Civilized felines have evolved beyond sneaking up on dinner in the darkness.
They now prefer to buy dinner at the local grocer.
The skill of night stalking remains.

An ambushing feline can subtract her Dexterity score from the target's Awareness score when ambushing prey.
A target with a 16 Awareness would typically get an ambush detection bonus of 16.
If the feline ambushing the target has a 14 Dexterity, its ambush detection bonus drops from 16 to 2.

To fully realize this ability, the feline must be ambushing alone or with other felines.
The referee can reduce the ambush bonus depending on the makeup of the expedition.

== Night Vision
Homo Felis has equal nite/day vision.
Night vision allows them to operate in darkness without any penalty.
