= Pure Strain Human

:art: pure_strain.png
:width: 250px
:snark: Pure strain teaching biology.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of earnest woman teaching xenobiology.

include::ROOT:partial$articulate.adoc[]

// Table 4.13 PSH Data
.*Pure Strain Human Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|Pure Strain Human info.

s|Attribute Minimums
2+<|Nil

s|Attribute Adjustments
2+<|CHA +3
 
s|Age
2+<|13-18 (1d6+12) years 

s|Abilities
2+<|Nil 

s|Size
s|Hite (cm)
s|Wate (kg)

|Tall
|169+(2d20)-20
|62

|Taller
|176+(2d20)-20
|71

3+<|xref:anthros:anthro_sizezeze.adoc[Calculate Hite and Wate]

|===

Pure strain humans (PSH) is the name given to Hominidae Homo Sapiens.
Pure strain humans are the collection of mammals control mundane terra. 
You are a pure strain human. 
The term pure strain refers to their lack of fun sciency fiction mutations or diseases of any sort.
Pure Strains can choose from any skin colour: black, blue, white, green, yellow, red, gold, etc.
Pure Strains possess none of the mythical strengths or weaknesses from unpopular culture.

There is a small chance a pure strain may catch a psionic mutation.
If the player does not want her persona to mutate, a pure strain human persona will not mutate.
If the persona does mutate, she cannot have a defect or a mutation that alters her appearance.