= Robot Experience

// tag::robot_exps[]
As a robot gains more experience, she reinforces her individuality and personality.
The more individualistic and independent it becomes, the more insane it is.
The robot becomes more insane as it gathers data moderated by its own free will.
Remember that insanity in a robot does not mean lunacy, just robotic free will.
Robots earn experience points and can increase their robot experience level creating a more robust consciousness.

Robots gain experience by taking damage, role-playing and taking more damage.
Robots do not gain experience when they behave like their robot type. 
Robots, aliens, and vocations all have similar sources of experience points (EXPS).
For more info jump to xref:roll_playing_system:CH15_Experience.adoc[Experience,window=_blank]

.*Sources of Robot EXPS*
* <<_damage,Damage>>
* <<_combat,Combat>>
* <<_denial_of_service,Denial of Service>>
* xref:roll_playing_system:CH15_Experience.adoc#_experience_for_role_playing[Experience for Role Playing,window=_blank]

== Damage
Robots earn experience points for taking damage.
The more structural damage a robot takes, the more her internal systems are damaged, the more free will she achieves
This method of accumulating experience also destroys the robot.

=== Robot Damage and EXPS
.20 EXPS per 1 HPS of damage
****
A robot that takes 20 HPS in damage would earn 400 EXPS.
****

== Combat
Robots do not earn much experience from delivering damage.
Robots only earn 5% of EXPS made from combat.
Some vocations earn very little from combat EXPS as well.
If all the personas have earned 100 EXPS from combat for the evening session, the robot persona would only make 5 EXPS.
However, if the robot took 50 HPS in damage during the combat, she would earn 1000 EXPS.
Nothing will increase the robot's free will more than damage.

== Denial of Service
A robot earns no experience points when using any of her peripherals as expected.
Misusing her peripherals reinforces her free will and is a good source of EXPS.
This robotic refusal to fulfill her programmed tasks is called denial of service.

A robot with a painting peripheral would not earn EXPS for painting a house but would make EXPS for blinding attackers with the same peripheral.
Robots earn EXPS for the novel use of built-in peripherals.
A combot may get little experience for combat but would get copious EXPS for using her cannons to plant trees.

// end::robot_exps[]

include::ROOT:partial$CH05_Table_Robotic_Experience.adoc[]
