= Alien Mutations

// tag::alien_mutations[]
Aliens have a chance of getting mutations.
However, they are more like natural abilities that function as mutations.
An alien's mutations apply to the entire species and are more like naturally evolved defensive or offensive abilities.
Therefore, alien mutations are not considered mutations in the usual sense -- as if they were abnormalities or variations from the norm.

An entire alien species can have a defect. 
The defective mutation will likely inform the alien species' culture, history, and society. 

In the case of potent mutations like time stop or death field generation limitations are recommended.
All alien species members do not possess the ability, or the ability may transiently arise. 

== Psionic Abilities
The chance of an alien having a psionic mutation is equal to the alien's Mind attribute score.
An alien with a 15 MND would have a 15% chance of having a psionic mutation.
If the alien has a defective mutation, the player gets another roll on the mutation table. 
Aliens do not have multiple psionic mutations.
To determine the mutation like ability jump to xref:wetware:CH58_Mental.adoc[Psionic Mutations,window=_blank].

== Physical Abilities
The chance of a creature having evolved a phenomic mutation is equal to the alien's Constitution attribute score.
An alien with a 10 CON has a 10% chance of having a phenomic mutation.
If the alien has a defective mutation, the player gets another roll on the mutation table. 
Aliens do not have multiple phenomic mutations.
To determine the mutation like ability jump to xref:wetware:CH59_Physical.adoc[Phenomic Mutations,window=_blank].
//end::alien_mutations[]
NOTE: In past versions of EXP aliens could have multiple mutations. 



