= Alien Attack Frequency

:art: alien_attacks.png
:width: 250px
:snark: Many hands many attacks
:artist: Edward Cartier scan M. Moscow
:date: 1951
:license: CC BY-SA 4.0
:description: Drawing of large multi-legged multi-armed alien aggressively approach humanoid in space suit. 

include::ROOT:partial$articulate.adoc[]

Each alien has a unique frequency of attacks per combat turn.
In EXP, combat turns are called units and represent a 2-second interval.
Attack frequency is how many attack rolls the player can make each unit.
The more attack rolls per unit, the more dangerous the alien.
These attack rolls can be bites, punches, pokes, slaps, stings.
Usually, the player will determine how her alien attacks once her description is complete.

The attack frequency only refers to the alien's natural attacks.
Alien attack frequency does *NOT* refer to weapon or mutation attack frequency.
An alien with three attacks per unit can only bite three times per combat turn.
If the alien were using a lazer pistol to attack a target, the player would not get three attacks per unit.
The attack frequency would be one attack roll per unit set out for the lazer pistol.

Aliens with high Dexterity scores are more likely to get multiple attack rolls for each unit.
Players add the alien's Dexterity score divided by three to the die roll.
For example, a persona with a 15 DEX would add 5 to her die roll.

include::ROOT:partial$CH06_Table_Number_of_Alien_Attacks.adoc[]

The player can attack up the number of attacks per unit.
She is not required to use all attack rolls in every combat unit.
The persona with three attacks can attack three different targets.
