= Mercenary

:art: mercenaries.png
:width: 450px
:snark: High tech merc vs lo tech merc.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid rodent picking a fight with a flying rocket-laden gun toting cop in powered armour.

include::ROOT:partial$articulate.adoc[]

They are the fighters, the tough gals, and the expedition's paramilitary types.
Mercenaries are hardy, ready-to-fight sorts.
Mercs are valuable for the clutter of combat skills that they possess.
They represent the dog-meat essential for the survival of any expedition in combat. 
Mercs do not personally regard themselves as dog-meat.

== Mercenary Abilities
Mercenary abilities are mostly concerned with inflicting damage on organic and inorganic objects.
Their abilities are divided in to actions (gifts), interests and skills.
Mercenary actions are gifts that help define the persona as a mercenary. 
Interests are broad areas the mercenary is good at like combat or tactics. 
Mercenary skills are item or task specific abilities like pistols or grenades. 
Interests and skills assist the persona with her tasks.

=== Mercenary Actions
The mercenary actions (gifts) are abilities that only a mercenary persona has.
New actions are added when the persona gains a certain level of experience.
The player cannot choose her personas actions. 

include::ROOT:partial$CH08_Table_Mercenry_Actions.adoc[]

=== Mercenary Interests
These are broad areas of interest that the mercenary has. 
Combat interests will assist the persona in any combat related tasks she is undertaking.
For example, shooting a lazer gun or throwing a grenade would benefit from combat interests.
Tactical interests are the officer side of executing tasks related to the bigger picture of a battle.
If the mercenary wanted to avoid an ambush, or organize a room entry she calls on her tactical interests.

At startup the player gets one roll per 3 points of INT. 
Each interest includes a skill roll as well.
After startup the player can roll or choose one additional interest per new EXPS level.

include::ROOT:partial$CH08_Table_Mercenary_Interests.adoc[]

==== Combat Interest
This interest is about weapons. 
Combat interests lead to combat skills that are usually weapon specific.
Combat interest can assist the persona when making task rolls related to combat tasks.
For example, if the persona is making a task roll for ambidextrous combat the combat interest will help.

==== Tactical Interest
Tactical interests assist the mercenary regarding decisions that do not affect direct combat.
For example, artillery use or planning an ambush is a tactical  interest.

==== Special Interest
These are special interests that do not involve combat or tactical interests.
For example, knocking open a door, or combat in zero gravity can benefit from special interests.
These are not special ops interests per se, but many of the special skills fall into those categories.

=== Mercenary Skills
Skills are much more specific than interests and can refer to a specific weapon type or a specific task. 
The skills will assist the persona in completing task rolls related to the skill.
A mercenary gets one skill per corresponding interest. 
So combat interest will earn the persona a combat skill as well.

==== Combat Skills
Combat skills assist the persona on any attack rolls she makes with the described weapon.
The skill would also help the persona when working with a non-combat task with the weapon.
The combat skill Pistols, Full Auto would give an attack roll bonus for flotto pistol.
The Pistols, Full Auto would also give a task bonus when cleaning or unjamming a flotto pistol

The player makes one roll per interest at startup and gets an additional roll for each new EXPS level.

include::ROOT:partial$CH08_Table_Mercenary_Combat_Skills.adoc[]

Combat weapon skills are cumulative and separable. 
So a persona with Rifles, Full Auto, and Rifles Bolt action would have Rifles +2 and Full auto +1
This would allow for +3 with flotto rifles, +3 with bolt action rifles and +2 with any other rifle.

When using the tactical combat system and kilodie attack rolls the player adds +20 per combat skill.
The player adds  +60 with flotto and bolt action rifles attack rolls and +40 with any other rifle attack roll.
These bonuses can exceed the persona's Max Roll. 

==== Tactical Skills
Tactical skills give the persona a bonus when making task rolls for the specific skill.
Some of the tactical skills also give weapon bonuses, like artillery or bombs.
Such skills are not considered weapon attacks because they are not considered personal weapons. 
Other tactical skills are esoteric and represent "officer type" skills.

include::ROOT:partial$CH08_Table_Mercenary_Tactical_Skills.adoc[]

==== Special Skills 
Special skills give the persona a bonus on tasks that are neither tactical nor combat.
However, these skills can definitely be used in combat situations.
For example, the submersive skill will assist the persona in underwater combat.
There are not special ops skills per se, but represent specializations that would require specialization beyond a weapon skill.

include::ROOT:partial$CH08_Table_Mercenary_Special_Skills.adoc[]

== Explanations of Abilities
Due to the importance of combat abilities the following paragraphs shed some light on the more common abilities.

=== Bolstering Defence Rating
The mercenary can increase her Defence Rating, making her more difficult to damage in combat.
The mercenary increases her defence by decreasing her attack.
The player can transfer points from her Skilled Bonus to her Defence Rating.
So her chance to hit decreases but her chance to be hit decreases as well.
This trade-off can change every unit, and the player doe not need to win a task roll.
Bolster AR is an automatic combat ability for mercenaries.

Let's consider a 3rd level merc with a Skilled of 158 and an AR of 620.
She could drop her Skilled to 98 and increase her AR to 680.

The Skilled Bonus use must match the attack type.
The player can use her persona's Strike Skilled against Strike attack.
A mercenary can transfer 20 Skilled points to AR per EXPS level. 
The amount transferred cannot exceed the mercenary's Skilled Bonus.
The player can use only the pure attack table Skilled Bonus.
Other bonuses, like scope bonuses, do not apply.
The mercenary can use her bolstered AR against one attack per EXPS level.

=== Divided Attacks
Mercenaries can make extra attack rolls with non-powered weapons.
Non-powered weapons are thrusting and striking (Strike) and non-powered missiles (Fling).
Powered weapons (Shoot) have a mechanical rate of fire limitation, and the divided attack ability does not apply.
Divided attacks are automatic, and the player does not make a task roll.

The player divides her Skilled Bonus between the attack rolls. 
Hence the name divided attacks.
The persona gets one additional attack every two levels of experience to a maximum of 4 divided attacks per unit.
A 4th level mercenary is attacking with an axe and has a Skilled of 210.
She could chop once with a Skilled of 210 or 3 times with a Skilled of +70;

To maintain game efficiency, players should make their calculations in advance.

=== Ambidextrous Combat
Mercenaries can use weapons with both hands without penalty.
The player must win a task roll or usual penalties for ambidextrous combat.
Ambidextrous combat allows the mercenary to combine any weapon types they can carry.

.Example Ambidextrous Combos
* two rifles
* pistol and sword
* two swords
* aerosol and dagger
* two grenades

Under normal circumstances, a persona suffers a severe penalty for ambidextrous combat.
The typical penalty is -200 for the dominant hand and -300 for the non-dominant hand.
If the player wins a task roll, the mercenary does not suffer these penalties.
If they miss their task roll, the merc will suffer -200 and -300 on the two attacks.

The DD of the task roll is 12. 
If the player wants to combine ambidextrous combat and divided attacks, DD is 24.

==== Poly-dextrous Combat
Aliens can come with multiple attacks pre-evolved.
An alien mercenary gets the same abilities as any other mercenary.
However, mercenary abilities only apply to weapons that the alien mercenary uses, not her native attacks.
For example, an alien with two natural attacks per unit cannot use divided attacks or ambidexterity on her biological attacks. 
A mercenary alien could use her natural attacks and her weapon attacks simultaneously. 
Each alien is different, and whether her natural and weapon attacks work simultaneously must be negotiated between the referee and players.

=== Absolute Proficiency
Mercenaries are proficient in any weapon that they use.
So a mercenary using a lazer pistol she just purchased up would use her Skilled Bonus.
Absolute proficiency only works with fully identified personal weapons.
This ability does not work on unidentified artifact weapons, but the mercenary is most likely to identify a gun.
This ability does not work on weapon systems of mass destruction.

=== Snap Reload
The mercenary can reload her weapon and attack in the same unit.
Most personas would have to miss at least a combat unit to reload a weapon.
The snap reload can also be used as a snap weapon exchange.
The player must win a 6 DD task roll to snap reload or snap change weapons.
If the mercenary is trying to snap reload during ambidextrous combat, the DD increases to 12. 
A mercenary cannot combine snap reload, ambidextrous combat and divided attacks. 
If the player loses the task roll, the mercenary reloads like all other personas.

.*Example Three Rolls*
* Hand-to-hand, striking
* Pistol, revolver, XLP (extra-low powered)
* Pistol, revolver, MP (medium-powered)
* Extra Roll!
* Grenades, Buildings


// for use in task tables
// tag::mercenary_maneuvers[]

== Mercenary Tasks
Mercenary tasks are devoted to combat and harming organic and inorganic targets.
These tasks are all about destroy, destroy, and destroy.

A mercenary must have a weapon to work with.
This must be an actual weapon that is not improvised from the persona's body (a fist is not a mace).
The referee may make a target roll more difficult if the mercenary does not have a weapon.

include::ROOT:partial$CH14_Table_DD_Merc.adoc[]

// end::mercenary_maneuvers[]

== Experience
The benefits of increasing experience levels are more weapon skills and improved success with task rolls.
Mercenaries earn experience points for completing maneuvers and role-playing within their vocation.
Mercenaries gain 110% of combat EXPS earned.

include::ROOT:partial$CH08_Table_Mercenary_Experience.adoc[]