= Nomad

:art: nomad_urban.png
:width: 250px
:snark: Urban nomad in city biome.
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid antelope pushing a shopping cart full of tech junk.

include::ROOT:partial$articulate.adoc[]

Nomads are survivalists.
They are experts at finding their way, constructing a shelter, and doing well with nothing more than their bare hands.
Other vocations cannot grasp the subtleties necessary to adapt to and live off an environment.
It is doubtful that there are accredited schools of nomadic adventure.
The persona most likely was born with these inherent survival abilities.
A nomad's survival abilities may have appeared out of necessity due to some scarcity situation.
Nomads can aid the expedition by providing a source of intuitive survival skills.

NOTE: Nomads can be sociable and have no political baggage.  

Nomads will generally shun technology if it is unnecessary for survival.
They prefer to sleep in a hollow log or a dumpster rather than a hotel room or tent.
There is no penalty for a nomad who uses technology.

== Nomadic Abilities
Nomads have abilities, that are divided between adaptions (gifts), interests and skills.
Adaptions are nomad specific abilities that the persona acquires at specific experience levels.
An adaption is a built in task that the nomad can practice without making a task roll.
The interests are broad areas that the nomad excels in.
An interest can be applied to many different skills.
Skills are more specific and can assist very specific task rolls. 

=== Nomad Adaptions
Adaptions are gifts that the nomad carries with themselves and help define them "being a nomad."
Adaptions cannot be chosen and are assigned as the persona increases in experience levels. 
Nomads get new adaptions at 1st, 4th and 7th levels of EXPS.

include::ROOT:partial$CH08_Table_Nomad_Adaptions.adoc[]

=== Nomad Interests
Interests are broad abilities that can represent experience that can assist skills and tasks. 
Nomad interests are intentionally wide ranging and can be very loosely applied to most any nomad task.

At startup the persona gets one interest per 4 points of Awareness, and one additional interest per new experience level. 

include::ROOT:partial$CH08_Table_Nomad_Interests.adoc[]

==== Biome Interests
Biomes are the bread and butter of a nomad. 
A biome is a geographically, ecologically or socially unique biological location.
When the nomad is in a familiar biome she enjoys task roll bonuses on nearly everything she does in that space.
Each biome interest earns the player an additional biome skill. 
Nomads quickly become very competent in their preferred biomes.

==== Survival Interests
All nomads, and all personas for that matter, are interested in surviving.
A survival interest will assist the player in any task rolls that represents survival tasks.
For example, a safe passage task roll would benefit from the survival interest. 
Whereas trying to domesticate an alien pack mammal would not.

==== Domestication Interests
Nomads can have an interest in domestication aliens for their personal use. 
The domestication interest will assist the persona in tasks that are part of domesticating aliens.
The process of domestication is elaborate and covered below. 

=== Nomad Skills
Skills are specific abilities that assist with more specific task rolls. 
A skill could represent knowledge, experience or training. 
The player rolls one skill per interest, and if the person earns another interest they gain another skill. 

==== Biome Skills
The nomad is assisted for any task attempted in a familiar biome.
There is no penalty for acting outside one's biome. 
The player makes one roll on the biome table per biome interest. 
The Alien Biome Table is included here for efficiency of the now, and the future. 
Each biome skill includes a biome and characteristic.

include::aliens:partial$biome_list.adoc[]

include::aliens:partial$biome_characteristic.adoc[]

:art: nomad.png
:width: 250px
:snark: Nomads desert biome.
:artist: Louis Glanzman
:date: 1952
:license: CC BY-SA 4.0
:description: Drawing of two humans finding shelter from sun in an alien desert.

include::ROOT:partial$articulate.adoc[]

==== Survival Skills
These are skills that specifically assist the persona in performing survival tasks. 
They include tasks like finding water, food and shelter.
Remember to add in biome skills and interests to improve the chance of success of the task.

include::ROOT:partial$CH08_Table_Nomad_Survival_Skills.adoc[]

==== Domestication Skills
These are skills that help the nomad when working with aliens. 
The aliens that domestication skills work on are typically flora and fauna. 
There are details about the complicated process of domesticating an alien below.
The table is a mix of Biologist taxonomy skills and specific nomadic domestication skills. 

include::ROOT:partial$CH08_Table_Nomad_Domestication_Skills.adoc[]


== Nomad Skills and Task Explanations
Some example explanations to help guide nomad abilities and tasks.

=== Water
This ability allows to nomad to read the environment, do a bit of dowsing, and sniff out some water.
Each win on the task roll will find enough water for one anthro for one day.
The player can keep making task rolls until she fails.
If she were to fail on the first task roll, she found no water that day.

.*Water Abilities*
* Find 1-4 (1d4) DD
* Purify 5-8 (1d4+4) DD
* Find source 9-12 (1d4+8 (1 DD);

=== Shelter 
Find shelter allows the nomad to either find or build shelter employing nothing other than the biome's materials.
The shelter can protect from the elements, local pests, or toxins.
The nomad must win a task roll for every persona that she is sheltering, camping or clothing.

.*Shelter Abilities*
* Fire 1 DD
* Find 1-6 (1d6) DD
* Safe campsite 5-10 (1d6+4) DD
* Craft clothing 9-14 (1d6+8) DD

The nomad can produce fire from local materials.
Creating fire is more difficult with challenging elements and austere conditions.

The safe campsite ability is an improvement on find shelter.
A safe campsite is free from natural disasters and less likely to be approached by hungry flora and fauna.

Craft clothing involves the fabrication of protective clothing from local materials.
The clothing could offer warmth, ventilation, or protection from inhospitable environments.
Often players wish to have camouflaged clothing.
Crafting camouflage doubles the DD of the task roll.

=== Food 
This ability allows the nomad to find sustenance from the local environment. 
The player must make a  task roll for every hungry mouth.

.*Food Abilities*
* Find 1-8 (1d8) DD
* Safe preparation 3-10 (1d8+2) DD
* Yummy preparation 5-12 (1d8+4) DD
* Cure poison 1-25 (intensity) DD

The Nomad can cure an organic poison that comes from the biome.
The nomad could cure a poisonous alien bite but not a military neurotoxin.
If the poison has an intensity of 12, the DD would be 12.

=== Domestication
Nomadic domestication involves the befriending and training of alien flora and fauna.
Aliens with language, culture, education, vocations or tool users are not flora or fauna.
Domestication is limited to flora and fauna aliens.
Domestication does not work during combat or with violently defeated aliens.
Domestication does not work with hungry aliens where the nomad is dinner.
Robots cannot be domesticated.

.*Domestication Stages*
. Befriending 1-25 (INT) DD
. Taming 2-50 (2*INT) DD
. Training 2-50 (Assigned) DD

Befriending is the first stage of domestication. 
Befriending indicates an alien that trusts and won't run from the nomad.
The degree of difficulty (DD) for befriending is equal to the alien's INT.

Taming is the second stage of domestication. 
The nomad must befriend an alien before being taming.
Taming indicates the alien has attained a pet status.
The degree of difficulty (DD) for taming is equal to twice the alien's INT.

Train for tricks is the third stage of domestication.
The nomad must tame an alien before teaching tricks.
The referee and players assign the DD of the trick.
The more valuable the trick, the higher the DD.
The player must win a task roll at double the trick's DD to train the alien.
The player must win a task roll to carry out the trick successfully.
Failing to carry out a trick should be humorous, not deadly.

The nomad has decided to domesticate a Festinated Wumpus. 
The Festinated Wumpus has a 4 INT. 
The Wumpus is a herbivore that the expedition has never hunted or killed.
The Wumpus does not use tools and has no language. 

To befriend the Wumpus, the nomad must make a 4DD task roll.
To tame the Wumpus, the nomad must make an 8DD task roll.
Training the Wumpus to retrieve an ammo pack is a 12DD trick.
To train the trick is a 24DD task roll.
The nomad must win a 12DD task roll every time the Wumpus retrieves an ammo pack.

=== Safe Passage
The nomad can determine a safe passage through seemingly impassable terrain: a mountain range, a toxic area, or a red light district.
Safe passage may require multiple task rolls: one roll to get through the city and another to avoid police.
The DD for safe passage has a range of 1-12 (1d12).
Safe passage cannot avoid plot points or story elements.

=== Tracking
Nomads can track anything that they want.
Tracking is not limited to flora and fauna. 
The nomad can track robots and vehicles as well.
There are two aspects of tracking, following and finding.

..*Tracking Abilities*
* Following 1-10 (1d10) DD
** Avoiding add INT
* Finding 1-10 (1d10) DD
** Hiding add INT
* Reverse tracking 2-50 (2*INT) DD

.Following
Following is used to keep up with a moving target. 
Following uses clues and intuition to track an unseen target.
The ability can follow an alien in the forest or a taxi in a megalopolis.
The nomad follows her target until the target stops moving.
If a target is trying to avoid following the target's Intelligence is added to the DD.
A successful following of a target does not guarantee successfully finding a target.

.Finding
Finding places the nomad face to face with her target.
If the target was initially moving, the player must win a task roll for following first.
After following an alien for a few hours in the forest, the player must win a finding maneuver to get that photograph.
If a target is not moving, the player needs only win a finding maneuver.
Finding a deserted warehouse in a city or a persona hiding in the bushes are two examples.
If a target is hiding, the player must add the target's Intelligence to the DD of the finding maneuver.
Finding hidden intelligent personas can be very hard indeed.

.Reverse Tracking
This ability allows the nomad to determine if she is being tracked. 
Reverse tracking lets the nomad know that she is being tracked.
To determine what is tracking her, the player must win a following and finding task rolls.
The nomad will have to follow and find what is tracking her using the 


== Rationalizing Nomad Skills

.Example Nomad SKills 
* Farm, Toxic
* Forest, Toxic
* Farm, Underground
* Coniferous, Normal

.Reorganized Skills
* Farm - 2
* Toxic - 2
* Forest - 1
* Coniferous - 1
* Underground - 1

Skills are cumulative and separable. 
A nomad trying to follow a rogue tractor on a toxic (2) farm (2) would get +4 on her task roll.
Finding a safe campsite in an underground (1) cave have a bonus of +1.

:art: biome_modern_space.png
:width: 450px
:snark: Biomes are not just trees and dirt.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Landscape of futuristic wall in front of planet and stars.

include::ROOT:partial$articulate.adoc[]

// for use in task tables
// tag::nomad_maneuvers[]

== Nomad Tasks
Nomad tasks are about surviving and manipulating the environment surrounding the persona.
These terrains are called biomes and can be natural, industrial or residential.
These tasks  are about personal survival.
Nomadic tasks  are mostly Gut tasks  and the player may enjoy an AWE bonus the Task Roll.

A nomad has no essential equipment.
Unlike any other vocation a nomad may be inhibited by survival tools like tents, or fire starters.
The referee may make a target roll more difficult if the nomad is glamping (glamorous camping).

include::ROOT:partial$CH14_Table_DD_Nomad.adoc[]

// end::nomad_maneuvers[]

== Nomadic Experience
Nomads get half experience for combat and EXPS for successful maneuvers.
Faithful role-playing of the nomad vocation will earn EXPS for the persona.
Increasing levels allows the nomad a greater chance of survival in the wild or combat.

include::ROOT:partial$CH08_Table_Nomadic_Experience.adoc[]

