= Knites

The Knite vocation is a mix of mystical, military and morality.
Knites are mythical and make a clear stand supporting order or chaos. 
They are the only vocation with a code of conduct.

The knite vocation combats her foes in the Physical Space and the Think Space at the same time.
They can use their Strength and Mind simultaneously.

Every persona in the knite vocation is psionically active.
They have no adverse disposition towards using technology, but the knite vocation feels most comfortable wielding the traditional energy sword.

The mental powers of the knite vocation use Kirlian energy. 
EXP includes sciency fiction details about how all this works in its generic mythos.
The referee should understand xref:appendices:Appy_C_Mythos_Generic.adoc#_the_spaces[The Spaces,window=_blank] and xref:appendices:Appy_C_Mythos_Generic.adoc#_kirlian_energy[Kirlian Energy,window=_blank] and how these impact the knite vocation.

The knite vocation has two mutually opposing groups.
Both sides manipulate Kirlian energy to fulfill their goals.
Order and chaos are the competing sides of this binary paradigm.
On the side of order is the Knite.
They prefer a steady-state and respect life.
On the side of chaos is the Anti-Knite.
They prefer entropy and do not respect life.
Where one finds Knites, there will be Anti-knites and vice versa.

== Knites
Knites are the supporters of compassion, goodwill, honesty, and life.
Knites do battle against injustice, intolerance, and enslavement.
They will err on the side good at every opportunity.
Knites are not pacifists and will deliver fatal justice without a second thought.

:art: anthro_purestrain_knite.png
:width: 250px
:snark: Two swords for justice
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a human woman in an onesie holding a sabre and light sword.

include::ROOT:partial$articulate.adoc[]

Knites tend to go off on "damn fool quests."
Knites do not ignore injustices perpetrated by their fellow expedition members.
A knite is a powerful ally in combat but may hinder an expedition's nefarious objectives.

Kirlian energy arises from the interface between the Think Space and the Physical Space. 
The Knite's strong sense of order makes them potent conductors of the Think Space.
This amplification of the Think Space allows them to sense and manipulate the Kirlian energy around them.

== Anti-Knites
Anti-Knites are the enemies of goodwill, humanity, and organized civilization.
Anti-knites are anti-everything.
An anti-knite is devoted to spreading chaos and entropy, but this does not make them random nihilists.
They can be systematic, calculating and patient.
A complicated plan that leads to more chaos is good.

:art: anthro_purestrain_anti_knite.png
:width: 250px
:snark: Bad in black
:artist: Eric Hotz
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of woman in black armour wielding a pistol and energy sword. 

include::ROOT:partial$articulate.adoc[]

Ant-Knites tend to organize "complicated deceptions."  
Anti-knites have no regard for personas less powerful than them.
The moment fellow expedition members are no longer valuable to the Anti-Knite, they can expect a savage betrayal.

WARNING: Anti-Knite personas in player expeditions will result in tragedy and strain player relationships. 

Kirlian energy arises from the interface between the Think Space and the Physical Space. 
The Anti-Knite's strong propensity for chaos makes them potent disruptors of the Physical Space.
This disordering of the Physical Space allows them to sense and manipulate the Kirlian energy around them.

== Knite Vocation Requirements
The knite vocation is powerful and complex.
One does not 'just become' a knite.

.*Requirement Checklist*
. Ref's <<_milieu,Milieu>>
. <<_attribute_requirements,Attribute Requirements>>
** 15 Dexterity score
** 18 Mind score
** 25 Hit Points
. <<_trial_period,Trial Period>>
. <<_kirlian_ascension,Kirlian Ascension>>

=== Milieu
The Knite Anti-Knite paradigm requires extra attention from the referee and must fit into her milieu.
The referee will have to create a mythos if the EXP generic mythos does not fit her milieu.
In short, the referee will decide if the background-laden vocation of knite is appropriate for her campaign.

=== Attribute Requirements
The Mind attribute requirement for the knite vocation is sacrosanct.
The persona loses her knite vocation abilities if her Mind score drops below 18.

=== Trial Period
The knite is a vocation.
It may or may not involve training. 
It may or may not involve religion.
There is always a trial period where the player must run a none knite persona until she activates the Kirlian energy around her.

The potential knite must start the campaign in a vocation other than knite.
There is no set time for the trial period. 
A persona may gain several levels of experience as a nothing, nomad, mercenary or whatever.
When the knite ascends, she switches to the knite vocation with zero EXPS.

During this trial period, the player's actions determine which side her knite persona will follow.
The righteous will likely become Knites and the ruthless Anti-Knites.

=== Kirlian Ascension
The test event is when the persona realizes she has ascended to the moral slavery of the Kirlian energy.
The referee may devise a life-threatening event where the player has to make an obvious choice between order and chaos.
It is more likely that the persona's behaviour during the trial period decides whether she ascends to order or chaos.

== Vocation Maintenance
In short, Knites must behave, and anti-knites must misbehave.
There is no rigid code of conduct, but there will always be minor errors.
Severe or persistent transgressions may get the persona into trouble.
The consequences for not following their side of order or chaos depend on the transgression. 

The persona may temporarily lose her ability to use Kirlian energy and lose her knite abilities. 
A powerful knite of the same side may appear to remind her of her duties.
A powerful knite of the opposing side may appear to turn her to the other side.

=== Turning Sides
Turning a knite has different implications depending on whether the knite is with order or chaos.

A Knite devoted to order can be turned to the side of chaos.
If a Knite is having a vulnerable time, the forces of chaos may conspire to create a complicated plan to turn her.
Anti-Knites seem always to be prowling around in the dark, waiting for knites to falter.
Once a Knite becomes an Anti-Knite, there is no turning back.

An Anti-Knite devoted to chaos cannot be turned.
If an Anti-Knite shows weakness, the forces of chaos may conspire to create a complicated plan to destroy her.
If an Anti-Knite carries out a fatal heroic act for the side order, this act can posthumously turn her.
Only in death can an Anti-Knite be turned.

=== Death
Death is quite final in EXP. 
There are very few ways to restore a dead persona.
In the case of a knite,  nothing can revive them.
When a knite dies, her Kirlian connection breaks, and she is permanently dead.
Death of a knite has different implications depending on whether the knite is with order or chaos.

A Knite's strong sense of order is a powerful conductor of the Think Space. 
This ordered connection to the Think Space allows them a translucent presence after death.
Dead Knites may occasionally re-appear as translucent immaterial entities to living Knites.

Anti-knites strong sense of chaos is a potent disruptor of the Physical Space.
This chaos  powers their Kirlian energy in the Physical Space, but leads to their complete dissolution at death. 
Dead Anti-Knites swirl in chaotic entropy and makes no smarmy translucent appearances.

== Knite Abilities
Knite abilites are divided into gifts, interests and skills. 
Unlike the abilities of other vocations only a knite can use these interests and skills.
In most cases Knite and Anti-Knite abilities are the same, but their goals are different.
There are a few abilities that are limited to choas or order. 

NOTE: Knites cannot manipulate Kirlian auras through inorganic media like monitors, cameras or phones.

=== Knite Gifts
Knites are the only vocation that calls their gift, gifts. 
These gifts are powered by manipulating pervasive Kirlian energy with their mind.
Gifts are abilities that a knite can call on without having to make a task roll.
A gift is like a task that persona can simply use. 
Knite gifts are conveniences and are not meant to destroy plot.

include::ROOT:partial$CH08_Table_Knite_Gifts.adoc[]

A player does not get to choose her knite's gifts.
They are assigned automatically based on the experience level of the persona. 

=== Knite Interests
Knites have broad scopes of interest that improve their chance of succeeding at task rolls.
One knite may have keen interest in manipulating the physical space.
While another knite may be interested studying society.
An interest in the Think Space would assist with any task that involves the think space.

At startup, the persona gets one interest per three points of Intelligence score.
A persona with a 12 INT would get three rolls on the Knite Interest Table. 
After startup the persona earns another interest with each new experience level.
The player can choose to roll on the Knite Interest Table, or choose a specific interest.

include::ROOT:partial$CH08_Table_Knite_Interests.adoc[]

Each interest has an associated group of skills.
At startup the player gets one skill per interest.
After startup the player may roll a new skill on the appropriate table or choose a specific skill.

==== Physical Space
An interest in the physical space will assist the persona in any task that involves the physical space.
For example, telekinesis involves manipulating the physical space.

==== Think Space
An interest in the think space will assist the persona in any task that involves the think space.
For example, intimidation involves manipulating the think space.

==== Cultural Space
An interest in the cultural space will assist the persona in any task that involves interacting with populations.
For example, interacting with a military institution would be assisted by an interest in the cultural space.

=== Knite Skills
Knites skills are tasks that the persona is particularly good at.
Not having a skill does not preclude a knite from attempting a task, but the skill makes it more likely to succeed.
Skills are grouped by interest, and the pesona gets one skill per interest.

At startup the player gets one skill per interest. 
So a knite with physical space 2 and cultural space 1 would get 2 rolls on the physical skills table and 1 roll on the culture skills table.
After start up the persona gets one new interest per new experience level. 
As described above the player can roll or choose the new interest.
Each new interest includes a new skill.
The player can choose, or roll, the new skill. 


==== Physical Space Skills
These skills align with tasks that impact the physical space.

include::ROOT:partial$CH08_Table_Knite_Phys_Skills.adoc[]

==== Think Space Skills
These skills align with tasks that impact the think space.

include::ROOT:partial$CH08_Table_Knite_Think_Skills.adoc[]


==== Cultural Space SKills
These skills align with tasks that allow the knite to interact with cultures.

include::ROOT:partial$CH08_Table_Biologist_Cultural_Stream.adoc[]

== Skill Explanations
For some reason there is a lot of detail available regarding knite abilities. 
This is probably due to game play edge cases encountered running previous knite personas. 

=== Kirlian Sight
The glowing, flickering Kirlian auras allow the knite to maneuver easily in darkness.
The Kirlian sight has a range of 1 hex per point of adjusted Mind (MND plus level).
Kirlian sight allows the knite to see much more than what is in the darkness.

Below are some specific uses of Kirlian sight. 
These only work on organic personas.
They do not work on plot points or story-making secrets. 
Usually, the target persona doe *not* get a saving roll.

Seeing Hidden:: 
The gift of sight allows the knite to find hidden objects. 
The player must win a task roll vs a DD of 1-6 (1d6).

Seeing Danger:: 
Seeing danger allows the knite to detect impending danger's direction and intensity.
This gift does not reveal the nature of the danger.
The player must win a task roll vs a DD of 5-10 (1d6+4).

Seeing Life::
Seeing life allows the knite to detect if a persona is alive.
Some referees will alter this Kirlian sight such that Knites see life and Anti-Knites see death.
This gift does not reveal what happened to the persona.
The range of this Kirlian sight is one km per adjusted MND.
The player must win a task roll vs a DD of 5-12 (1d6+6).

Seeing Intent:: 
Seeing intent allows the knite to detect a persona's general intentions.
This gift does not reveal the specific detail of any plans.
The player must win a task roll vs a DD of  9-14 (1d6+8).

Seeing Truth::
Seeing truth allows the knite to detect if a persona is being truthful.
Some referees will alter this Kirlian sight such that Knites see truth and Anti-Knites see lies.
This gift does not reveal the specific detail of the persona's thoughts.
The player must win a task roll vs a DD of  11-14(1d6+12).

Seeing Fate::
Seeing fate allows the knite to determine what may happen to a specific persona.
This gift does not reveal the specific details of their fate.
Seeing fate does not work well on player personas or significant plot points. 
The range of this Kirlian sight is one month per adjusted MND.
The player must win a task roll vs a DD of 17-23 (1d6+16).

=== Mimic
A knite can reproduce a brief sound so well that it will emotionally affect the listener.
The player must win a task roll to mimic a noise successfully.
The listener does not get a saving roll for the deception.
A task roll fail produces a random ineffective noise.
Mimic cannot reproduce sonic attacks.
This gift's typical DD range is 1-4 (1d4).

=== Induce Silence
A knite can cover themselves in silence, preventing normal sounds from travelling. 
This gift cannot overcome loud, violent noises.
A successful task roll will suffuse the knite in silence.
The player must win a task roll every five units (10 seconds) to continue in silence.
The louder the noise, the harder it should be to hide it.
This gift's typical DD range is 1-4 (1d4).

=== False Rest
False rest is an extension of the gift Kirlian sight.
This gift allows the knite to use her Kirlian sight through closed eyes or none metallic blindfolds.
This gift's typical DD range is 1-4 (1d4).

=== Deflection 
Deflection is an ability that allows the knite to deflect or absorb projectile attacks. 
The knite can deflect arrows, bullets and lazer blasts by merely raising her hands.
The knite cannot deflect area of effect attacks or energy attacks like electron or fusion weapons. 
Deflection is only effective against frontal attacks. 
This ability cannot deflect flank or rear attacks.
Restraining a knite's limbs will prevent her from using deflection.

In the tactical combat rules, deflection improves the knites Defence Rating and decreases damage.
If the player wins a task roll, her persona's AR increases by 30 per level.
If the attack roll fails, the knite deflects the projectile.
If the attack roll wins, the knite can absorb five hit points of damage per experience level. 
A 3rd level knite could absorb 15 HPS of damage from those attacks that penetrated her increased AR (+90).
The knite can deflect one attack per experience level.

The attack roll determines the degree of difficulty.
The DD increases by one per 42 points of the attack roll.
So an attack roll of 840 would require the player to win a 20 DD task roll. 

=== Suggestion
Suggestion allows the knite to put words into the mouths of susceptible personas.
The gift of suggestion is a transient mind control where the target will repeat and believe what they are told.
For example, the knite may tell a bodybuilder, "these aren't the roids you're looking for," and the bodybuilder will agree and look for other roids. 
The effect is not permanent and only works as a temporary distraction. 

The player must win a task roll, and then the target must lose a saving roll before a suggestion takes.
This gift's DD increases as the difficulty increases. 

.*Suggested Suggestion DDs*
* Spoken, native language 4DD
* Spoken, foreign language 8DD
* Silent, native language 12DD
* Silent, no language 16DD

=== Telekinesis
This ability allows the knite to move objects without touching them.
The knite can move a large object slowly or a small object quickly. 
The knite can only inanimate objects.
The object must both be within the range of her telekinesis and be visible to the knite.
An object held by an unwilling persona gets a saving roll to avoid telekinesis.

The range of telekinesis is one hex per point of adjusted Mind.
The player must determine her knite's Mind wate allowance using her MND on the xref:anthros:wate_allowance.adoc[Wate Allowance Table,window=_blank].
A persona with a 20 MND would have a 20 hex range and a 34 kg MND wate allowance.

The knite's experience level determines the number of telekinetic objects the knite can move at once.
A knite can telekinese one object for every two experience levels. 
A 6th level knite can telekinese three objects at once. 

.*Heavy and Slow*
To slowly move a large object requires the knite's full attention.
She can lift twice her MND wate allowance times her 'amount' in kilograms.
A 6th level knite with a 20 MND could slowly lift  204 kgs off the ground.
This ability's typical DD ranges from 2-12 (2d6)

NOTE: Lifting a 5500 kg space fighter from a bog requires a level 30 knite with a 33 MND.

.*Small and Fast*
To quickly move small objects requires no special attention from the knite.
She can snatch weapons from hands or hurl objects at targets while engaging in combat.
The number of objects the knite can fling around at once is equal to one per two experience levels. 
The total wate of the objects the knite can fling at once is equal to her wate allowance.
A 6th level knite with a 20 MND could telekinese one object at 34 kgs, two objects at 17 kgs or three objects at 11 kgs.

When hurling objects as weapons, they are an Attack Fling (non-powered ranged attack).
The player must make a attack table for this attack where her MND replaces her STR.
There is no Force Bonus for telekinetically hurled objects.
If the player wins an attack roll, the attack inflicts 1-6 (1d6) hit points of damage per object. 
This ability's typical DD ranges from 1-6 (1d6).

A 6th level knite with a 20 MND could telekinese one object for 3d6, two objects at 2d6 or three objects at 1d6.

.*Lifted from above*
* Range: 1 hex per MND + Levels
* WA: MND on WA chart
* Amount: 1 per 3 Levels
* Slow: 2* WA * Amount
* Fast: Total WA or 1d6 per Amount

=== Pressure 
Pressure fills the target with overwhelming emotion.
The knite must be within reach of the target.
The target is incapacitated if she fails her saving roll.
The knite must reapply the pressure every five units (10 seconds).
A Knite using pressure will flood the target with incapacitating guilt.
An Anti-Knites using pressure will flood the target with asphyxiating fear.
Both versions of pressure are equally immobilizing.
This gift's typical DD range is 1-8 (1d8).

=== Kirlian Defense
Kirlian defence allows the knite to harden her consciousness with Kirlian energy.
The trance-like state blocks mental incursions by other knites or psionic mutations.
While in her psionic fortress, the knite cannot use any gifts or psionic mutations.
If the player wins a task roll against DD 4, her Kirlian defence is active.
The persona can then block attacks by winning a saving roll.

== Energy Sword Abilities
The knite's unique weapon is her energy sword.
The energy sword can be a force field sword, laser sword, or lite sabre.
The knite can do certain things with her energy sword that no other persona can.

These abilities only work with her bespoke energy sword.
The knite cannot pick up any glowing weapon and become a food processor.

=== Multiple Attacks
A knite can attack more than once per unit with her energy sword.
She can make one extra attack per unit per two levels of experience.
The ability of multiple attacks does not require a task roll.
The maximum number of attacks per unit is four.

=== Deflection
A knite can use her energy sword to deflect damaging attacks.
If an attack roll on the knite is successful, she can opt to deflect the attack.
The knite can deflect arrows, bullets and lazer blasts by combining parries and Kirlian energy.
The knite cannot deflect area of effect attacks or energy attacks like electron or fusion weapons. 
She can deflect attacks from any direction, except when ambushed.

To successfully deflect an attack, the player must win a task roll.
The DD for this ability is 1/42 of the attack roll made on her.
So an attack roll of 840 would require the player to win a 20 DD task roll. 

The knite can deflect one attack per two experience levels.
Thus a 4th level knite could deflect two attacks per unit.
Remember that she need only deflect those attacks that will hit her.

=== Amputation
The most devastating energy sword ability is that of amputation.
The energy sword is capable of excising any limb that it hits.
Amputation does not remove heads, and there is no decapitation ability.
The target must have limbs and be small, medium or large sized.
Tiny and gigantic personas are amputation resistant.

The player must declare she is making an amputation attempt.
The more damage the energy sword attack inflicts, the more likely the amputation chance.
There is a 1% chance per hit point of damage.
If there is a chance of amputation, the player must win a task roll to remove the limb.

Inflicting 15 HPS in damage has a 15% chance of an amputation check.
The knite must make a task roll against a DD equal to 1/100 of the target's Defence Rating.
A target with a 500 AR would be a 5 DD task roll.

// for use in task tables
// tag::knite_maneuvers[]

== Knite Tasks
Knite maneuvers are mystical in nature and involve manipulation of the thinkspace.
Knite maneuvers are considered spiritual gifts or psionic abilities. 
When in combat the knite may be able to get a MND Task Roll bonus.

A knite must have a MND of 18 to perform any of these maneuvers. 
The knite's MND is an essential piece of equipment.

include::ROOT:partial$CH14_Table_DD_Knite.adoc[]

// end::knite_maneuvers[]

== Knite Experience
The benefits of increasing experience levels are more refined interpretations and manipulations of Kirlian energy and improved combat skills.
Knites earn experience points for completing maneuvers and role-playing within their vocation.
Knites earn 100% of combat experience.

include::ROOT:partial$CH08_Table_Knite_Experience.adoc[]


