= Attack Table

[quote]
____
*A list of numbers that follow the persona into combat.*
____

The attack table is the centrepiece of the tactical combat rules.
The tactical combat rules allow for players to carry out detailed combat shenanigans using miniatures on a tabletop.
The Attack Table combines all of the persona's bonuses in one place.
The matrix lists all the bonuses that the player adds to her attack and damage rolls.
The attack table combines attributes, vocation, levels, weapon familiarity and tactics to pretend that these elements matter.

Each persona has its own attack table. 
The amount of time spent calculating the data depends on the importance of the persona.
Player personas have the most detailed attack tables.
Cannon fodder have the least detailed attack tables.

The tactical combat rules are not simple, and the attack table requires an understanding of each element of the table.
You need to read this section if the following acronyms do not make sense: Skilled, Raw, Max, Force, DEF, Strike, Fling, Shoot etc.
If you know what you are looking for, jump to the attack table you need.
Below is a list is of player persona attack tables. 
Referee persona attack tables are detailed in their referee persona sections

include::ROOT:partial$CH09_Table_Tiny_CT.adoc[]

.*Jump to the Attack Tables*
* xref:anthros:attack_table[Anthro Attack Table,window=_blank]
* xref:robots:attack_table.adoc[Robot Attack Table,window=_blank]
* xref:roll_playing_system:CH06_Aliens_6_CT.adoc[Alien Attack Table,window=_blank]

include::anthros:partial$attack_table_blank.adoc[]

== Deconstruction of an Attack Table
The following sections will demonstrate how to fill in the empty table immediately above.

include::ROOT:partial$CH09_Table_Description_of_a_Combat_Table.adoc[]


// attack types tag
include::CH27_Tactical_Combat.adoc[tag=Attack_Types]

== Skilled Bonus
This number is added to the attack rolls when the persona is using familiar weapons.
Being familiar and skilled with a weapon indicates that the persona is proficient with that weapon.
Using a proficient weapon allows the persona to bring all her aptitude and skills to bear.
The higher the Skilled Bonus (Skilled), the more likely the player will win her attack roll and damage the target. 
When the player throws her kilodie attack roll, she adds the Skilled to the die roll. 

If the persona is using an unfamiliar weapon, she uses her Raw Bonus (Raw).

The Skilled Bonus has two main components: attribute bonuses and level bonuses.

=== Attribute Component
Most of the calculations done on the attack table involve the persona's attributes.
Each attack type has its own attribute calculation. 
Strong personas have better attack bonuses with thrusting and striking attacks.
Dextrous personas excel with powered missile attacks.

:art: combat_feline_pstr_win.png
:width: 250px
:snark: STR helps Strike attacks.
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid feline walking away from destroyed carnival game.

include::ROOT:partial$articulate.adoc[]

=== Level Component
The level component refers to the bonuses the persona gets from her vocation and experience level. 
The higher the experience level, the better the persona is at combat. 
In general, the persona with the higher level will be better in combat.
Sometimes exceptional attributes can overshadow experience levels.
However, if two personas have the same attributes more experienced persona will have an advantage.

== Raw Bonus
The Raw Bonus is added to an attack roll when the persona is using unfamiliar weapons.
The Raw Bonus (Raw) is a fraction of the persona's Skilled. 
The Raw still benefits the player's attack roll but less so than her Skilled.
Personas will prefer to use familiar weapons in which they are proficient.

The persona's vocation determines the persona's  Raw. 
All anthros have vocations and therefore use the Vocation Raw Table to determine their Raw.
The more combat-oriented the vocation is, the better their Raw Bonus.
The less combat-oriented the vocation is, the lower their Raw is relative to their Skilled.
A nothing only can use 10% of her Skilled Bonus with Shoot attacks.
A mercenary can use 100% of her Skilled for all attacks. 

:art: critical_fail_equine_grenade.png
:width: 250px
:snark: You must know your tool.
:artist: Peggy Lynn McIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a humanoid horse throwing away a pin and holding a grenade.

include::ROOT:partial$articulate.adoc[]

== Max Roll
The Max Roll is the best attack roll that the player can make for her persona.
If a player's total attack roll is 1042 and her Max Roll (Max) is 884, her attack roll becomes 884.
As the persona increases in experience levels, her Max Roll increases as well.
Combat vocations increase their Skilled andMax faster than non-combat vocations.
Without the Max, low-level personas are as dangerous as high-level personas.

NOTE: *Critical Checks allow any persona to damage any other persona with pure chance.*

Occasionally a player will be unable to win an attack roll on a target with a high Defence Rating.
This limitation of the Max Roll will leave some players feeling helpless and frustrated.
These emotions indicate that it's a good time for their persona to run away.

:art: maximum_roll.png
:width: 250px
:snark: Just can't get better.
:artist: Andrew Brechin
:date: 1991 
:license: CC BY-SA 4.0
:description: Drawing of dart in center of dartboard.

include::ROOT:partial$articulate.adoc[]

== Force Bonus
The player adds the Force Bonus when she wins an attack roll.
The Force Bonus (Force) represents the impact of Strength on persona-powered attacks.
Strength increases the amount of damage that the persona delivers with a striking weapon.
Powered attacks (Shoot) do not have a Force Bonus.








