= Incidentals

[quote]
____
To avoid incidents, don't miss the incidentals.
____

:art: backpack.png
:width: 250px
:snark: Stuff in your stuff.
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of very angular boxy high tech backpack.

include::ROOT:partial$articulate.adoc[]

This section contains the junk that personas need to survive in the referee's milieu.
Whether these items exist or not is entirely dependent on the world created by the referee and the players.
If there is are no tools, skip Mundane Equipment.
If there is no money, skip Start Money.
If there is no high-tech, then skip Start Toys.
This section is here for convenience, and it is not an attempt to wreak havoc with a referee's milieu.
Take from the incidentals what the personas need. 

Anthro personas usually need all the mundane stuff included here.
Anthros are soft and defenceless against the universe.
Robot personas usually have no interest in anything in this section.
Alien persona's need for this mundane stuff depends on their culture and society.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Start Money
Start money is the persona's pocket money on day zero of the campaign.
The start money is usually their total worth.
The personas may keep their life savings in a satchel or credit on their plastic money card.

The default currency in EXP is the eps (electrum piece).
The nature of money depends on the back story created by the ref and players.
Money nomenclature is discussed more thoroughly in the xref:roll_playing_system:CH23_Money.adoc[Money,window=_blank] section.

include::ROOT:partial$CH10_Table_Persona_Start_Money.adoc[]

== Start Equipment
To expedite the expedition exploring, the referee can extend start equipment to the personas.
Start equipment is only appropriate if it fits into the milieu of the ref and players.

This equipment will be of the mundane variety.
Here mundane means lo-fi, lo-tech tool level equipment.
Slightly higher-tech equipment is available.
Higher tech equipment is lighter and costs more.
There are no artifacts available for purchase in the incidentals. 
Personas get artifacts from the Technological Object Yield System (TOYS).

NOTE: * High-tech equipment are called artifacts or toys.*

Players can take their start money over to xref:roll_playing_system:CH24_Mundane_Equipment.adoc[Mundane Equipment,window=_blank]
 to purchase their start equipment.
For players not interested in pouring over lists, here is a mundane survival pack.

=== Survival Pack
The survival pack costs 70 eps and has a wate of 13.5 kg.
The survival pack is supposed to speed up the equipment buying procedure.
The referee can configure her survival packs as she sees fit.

include::ROOT:partial$CH24_Table_Survival_Pack.adoc[]

== Start Toys
Toys are special equipment generated on the Technological Object Yield System (TOYs). 
The TOY system generates random technological goodies that help the personas with their goals.
The player makes countless deci-dice rolls to generate a nondescript black box.
Artifacts and toys do not have obvious uses. 
Mundane equipment has obvious uses.

These technomagical high-tech devices are toys or artifacts.
Calling something an artifact sounds more serious.
Players use the terms toys, artifacts and equipment interchangeably.
Referees can pedantically intercede, and school player's with the following nomenclature.

Artifact::
An unidentified technological device. 
An artifact may turn out to be useful, useless, benign or lethal.

Toy::
An identified technological device that the players like.
While the device's use remains unknown, it is usually called an artifact.

Mundane:: 
Mundane equipment is the useful and boring stuff that is essential to detail-oriented campaigns.
This equipment has obvious uses, no trickery or hidden lethality.

Equipment::
All the stuff that the expedition has at their disposal.
Equipment includes artifacts, toys, and mundane equipment.


The referee and players will decide if personas start the campaign with artifacts or not.
The intended use of TOYs is to generate high-tech artifacts that are utterly opaque to the players.
Figuring out what an artifact does is a cornerstone of the technological chaos of EXP.

If the milieu permits personas to have start toys head over to xref:iii-hardware:An_index_hardware.adoc[Hardware,window=_blank] to get some toys.
It is also possible for personas in a high-tech world to purchase artifacts from shops.
If the milieu permits, players can use the xref:iii-hardware:An_index_hardware.adoc[hardware section,window=_blank] like a shopping catalogue.

NOTE: In the previous millennium, retail stores snail-mailed glossy books full of https://en.wikipedia.org/wiki/Mail_order[equipment,window=_blank] directly to personas.