= Referee Personas

A Referee Persona (RP) is any persona that is *not* run by a player.
Personas brought to life by the referee are called referee personas. 
The referee persona could be from any family: anthro, robot, alien or AI.
Referee personas can be friends, foes, flora, or fauna.

NOTE: *A referee persona is also called a non-player character. RP=NPC*

== Referee Persona Checklist
Referee-run personas require more details than player-run personae.
The Referee Persona Creation Checklist indicates the extra info needed for a referee persona. 

.*Referee Persona Creation Checklist*
* *ROLL PLAYING INFO (Data)*
. <<_determine_family,Determine Family>>
.. Anthro
.. Alien
.. Robot
.. AI
. Determine Relevance
.. Cannon Fodder
.. Canon Fodder
.. Canon Persona
. Persona Record Sheet
.. Record creation Date
.. Record unique RP ID
. Determine Type
. Attributes
. Defence Rating
. Movement Rate
. Wate Allowance
. Mutation
. EXPS Level
. Vocation
. Equipment
.. Mundane
.. Artifact
. Attack Table
. Combat Ratio
* *ROLE PLAYING INFO (Fun)*
. Story
.. Origin
.. Presence
.. Goal
.. Personality
. Appearance
.. Clothing
.. Hygiene
.. Gender
. Beliefs
.. Religious
.. Political
.. Philosophical
. Modifications
.. attributes
.. size
.. age
. Name
. Have Fun!

== Determine Family
The referee starts the process of RP generation by picking a family for the RP.
Often the referee will need a certain kind of RP and can jump right to that section.
If inspiration is needed, then roll on the Referee Persona Family Determination Table. 

include::ROOT:partial$CH11_Table_RP_Family_Type.adoc[]

== Referee Role-Playing
It is the responsibility of the referee to role-play referee personas to the best of her ability.
Intelligent aliens must seem and act intelligently.
Nomads will prefer their biome over luxury.
Anti-knites must not stray from the righteous path of entropy.
Robots lack facial expressions and body language.
In short, the referee must be able to make even the temporary personas as authentic as possible.

=== Spread the Fun
Collaborative role-playing groups will often have players represent referee personas.
Player-run referee personas work well for personas that are friendly or neutral to the expedition.
A player could run a cranky shopkeeper that likes to haggle.
A player could run an adorable alien that begs for scraps of plastic.
A player should *not* play a Heavy Combot RP that is attacking the expedition.
A player should *not* play a spie feline RP that knows crucial campaign secrets. 

== Referee Persona Generation
Referee personas are so essential to the core of role-playing games that the referee will be generating many of them.
The expedition need's an ursidae mercenary for protection in the wilds.
Those wilds are full of ferocious alien flora and fauna.
The radioactive ruin in the center of the wilds is the home of an explorations robot collecting specimen with lethal prejudice.

A referee could generate completely random referee personas.
However, it is unlikely that a completely random persona will fit the milieu.
The referee should massage the RP creation to fit into her milieu.
The RP toolset is for helping creativity, not replacing it.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

Each family has its section for RP creation.
Each section has most of the essential data in one place.
Moving from top to bottom will create a persona most efficiently.
Filling in a persona record sheet as you create the persona will save precious time.
Creating referee personas can be as much fun as playing them. 
