= Robot RP

Robots are inorganic lifeforms.
In the faux taxonomy, robots are of the family machinidae
Machinidae are life forms that are inorganic and fabricated.
Anthros, Aliens or other Robots can fabricate robots.
The robots here are referee persona robots fabricated by the referee.

.*Robot RP Fabrication Checklist*
* *RP ROLL PLAYING (Data)*
. <<_robot_rp_relevance,Relevance>>
. <<_robot_rp_type,Select Type>>
. <<_fabricator_type,Fabricator Type>>
. <<_robot_rp_attributes,Attributes>>
. <<_robot_rp_size,Size>>
. <<_robot_rp_defence_rating,Defence Rating>>
. <<_robot_rp_movement_rate,Movement Rate>>
. <<_robot_rp_wate_allowance,Wate Allowance>>
. <<_robot_rp_exps_level,EXPS Level>>
. <<_robot_rp_systems,Systems>>
.. Offensive
.. Defensive
.. Peripheral
. <<_robot_rp_control_factor,Control Factor>>
. <<_robot_rp_adaptability,Adaptability>>
. <<_robot_rp_value,Value>>
. <<_robot_rp_tech_level,Tech Level>>
. <<_robot_rp_age,Age>>
. <<_robot_rp_combat_table,Attack Table>>
. <<_robot_rp_combat_ratio,Combat Ratio>>
. <<_robot_rp_technology,Technology>>
.. Power Source
.. Sensors
.. Locomotion
. <<_robot_rp_story,Story>>
.. Origin, Presence, Goal
.. Personality
. <<_robot_rp_appearance,Appearance>>
.. Shape
.. Colour
.. Adornments
. <<_robot_rp_beliefs,Beliefs>>
. <<_robot_rp_name,Name>>
. Have Fun!

// fix . _robot_rp_modifications,Modifications

== Robot RP Relevance
Not all RPs are created equal.
Some personas are less important than others.
The referee usually knows the importance of the persona before she starts generation.
An RP's relevance increases the more entangled they are with the expedition.

include::ROOT:partial$CH11_Table_RP_Relevance.adoc[]

=== Cannon Fodder
Cannon fodder are like movie extras that fill in the background.
Robot cannon fodder are inorganic machines operating in the background.
These robots are delivery drones, cashiers, or elevators.

.*Cannon Fodder* 
. offer no opposition
. have no useful information
. have no nutritional value, monetary value or useful parts.

Any combat contact will utterly destroy robotic cannon fodder.
Destroying robotic cannon fodder is not without consequence.
Cannon fodder is always property, and destroying it may anger a corporation or a powerful entity. 

=== Canon Fodder
Canon fodder may have bit parts in the story but does not make the story. 
Robot canon fodder can be security sentries, attack drones, or angry shopping carts.

.*Canon Fodder* 
. could act in opposition to the expedition's goals
. could injure or kill a player persona
. could accidentally alter the story of a campaign
. could have information or treasure

The referee usually predetermines the goal of canon fodder.
The referee creates as much information as needed.
For example, security sentries protecting a plantation may only have a lazer and Skilled Bonus on her attack table.
The security sentries may all look the same, but with different id numbers.

Canon fodder can be extremely dangerous to the expedition.
They are there to get in the way of the player's goals. 
The referee should complete a persona record sheet for robot canon fodder. 
There are too many moving parts with robot RPs to make them on the fly.

=== Canonical Persona
Canonical personas are like supporting actors that make the story possible.
These referee personas are integral participants in the campaign story.
They can be powerful recurring enemies or comrades in arms.
Canonical referee personas are the real deal.
These referee personas utilize every step of persona creation.
They have all the dressings of a player persona.
Only the player personas are more important to the story.

== Robot RP Type
For player personas determining their robot type is a laborious process.
The referee can use the Single Roll Robot Type Table below.
One roll using a 1d1000 chooses the robot RP type.
The referee should massage the robot type to suit her campaign's milieu.

include::ROOT:partial$CH05_Table_Robot_Single_Roll.adoc[]

=== Fabricator Type
Where fabricator type does play a role is in delivering orders to the robot. If a fabricator type tells a robot what to do, it is more likely to comply. In short, the robot's fabricator type is more successful at bossing the robot around. If a fabricator type makes a reasonable, on mission command to a robot, it would almost certainly result in a control factor roll.
For more information about the implications of the fabricator type jump to xref:robots:fabricator.adoc[Robot Fabricator,window=_blank].

include::robots:partial$fabricator_type.adoc[]

== Robot RP Attributes
Inverse to player personas, the RP robot's type determines her attributes.
While the table looks imposing, it is much faster than the player personas process.
The attribute lookup table gives the direct attribute scores.
The referee determines the robot's prime attributes after her regular attributes. 

include::ROOT:partial$CH11_Table_Robot_RP_Attributes.adoc[]

=== Robot RP Prime Attributes
Some robot abilities depend on the robot's prime attribute. 
For robot RPs the robot type determines the attribute ranges. 
Consult the lookup table below to record the attribute ranges.

include::ROOT:partial$CH11_Table_Robot_RP_Prime_Reversal.adoc[]

== Robot RP Size
The robot size consists of the robot's wate and the robot's hite.
The wate of the robot plays a role in ramming damage. 
Heavier robots inflict more damage.
The hite of the robot determines its rough volume. 
Bigger robots don't fit as well into anthro-sized spaces.

include::ROOT:partial$CH11_Table_Robot_RP_Wate.adoc[]

=== Extremely Tiny Robots
Any robot that has a wate of 4.2 kg or less has a chance of becoming an extremely small nanorobot.
The chance of the robot becoming a nanorobot is 1 in 6 (1d6)
Nanorobots have a wate of  0 to 999 grams (1d1000-1).
A nanorobot cannot have a wate greater than a kilogram.
Nano robots have no change to their attributes, abilities or combat values.

==== Extremely Gigantic Robots
Any robot with a wate of 4200 kg or more has a chance of becoming a mighty machine.
The chance of the robot becoming a mighty machine is 1 in 6 (1d6).
Mighty machines have a wate of 6 to 600 tons (1d100 times 6).
MIghty machines have no change to their attributes, abilities or combat values.
However, in regards to ramming, mighty machines can increase their ramming ratio to 12 (versus 4).

=== Hite
Hite gives an estimation of the volume occupied by the robot.
The referee rolls dimensions once for each of hite, width and length.
A hexagon is 200 cm across. 

include::ROOT:partial$CH05_Table_Robot_Dimensions.adoc[]

== Robot RP Defence Rating
Robot RPs have an AR of 700.
A robot AR is the same as any other persona AR.
A successful attack roll damages the robot as it would any other persona.
Robots are different from organic personas and damage differently.
Robot RPs are easy to hit but hard to destroy.

== Robot RP Movement Rate
The robot's Dexterity score determines her movement rate.
Robots are twice as fast as those other personas with the same DEX.
Those robots which move faster than eight h/u must accelerate the same as vehicles.
Robotic acceleration is one hex per unit per STR prime score.

include::robots:partial$movement_rate_and_dexterity.adoc[]

== Robot RP Wate Allowance
Bots are affected by encumbrance, though not as much as other referee personas.
Strength determines the weight allowance of the robot.
A robot with a STR level of 3 and a 17 STR would have a wate allowance of 75 kgs.
Robot size does not affect a robot's wate allowance.
For more information about carry stuff, jump to xref:roll_playing_system:CH18_Encumbrance.adoc[Encumbrance,window=_blank].

include::robots:partial$wate_allowance_and_prime_strength.adoc[]

== Robot RP EXPS Level
EXPS Levels improve the RP's Control Factor, assist in saves and robot attributes.

include::robots:partial$experience_to_levels.adoc[]

== Robot RP Systems
Robotic RPs may have offensive, defensive and peripheral systems.
Generating systems for player persona robots is convoluted and fun.
The referee can find the number of rolls for each system on the single lookup table below.
The lookup table seems scary, but it is scientifically proven to be faster than the player robot persona method.

include::ROOT:partial$CH11_Table_Robot_RP_Systems.adoc[]

== Offensive Systems
These are the systems that harm others.
On the lower level tables, the robot is misusing and weaponizing malfunctioning peripherals.
On the higher level tables, the robot is using weapons baked-in during fabrication.
The referee will dance back and forth between the attack tables, creating a murderous melange of machinery.

=== Ramming 
All robots can ram, but not without challenges.
Only robots with ramming freedom can fling themselves around with self-destructive abandon.
For more info about robot ramming, ram your way over to xref:roll_playing_system:CH05_Robots_Z_Offensive.adoc#_ramming[Robot Ramming,window=_blank].

include::ROOT:partial$CH05_Table_Robotic_Ramming.adoc[]

=== Attack Table One
These attacks include ramming, and the robot is misusing and weaponizing malfunctioning peripherals. 
It is possible to get a roll on Attack Table Two to get more dangerous weapon systems.
For details about these attacks jump to  xref:roll_playing_system:CH05_Robots_Z_Offensive.adoc#_attack_table_one[Attack Table One,window=_blank].

include::ROOT:partial$CH05_Table_Robotic_Attack_Table_One.adoc[]

include::ROOT:partial$CH05_Table_Type_A_Weapon_Type.adoc[]

=== Attack Table Two
Slightly more dangerous attacks, but mainly consist of misused devices.
It is possible to get several rolls on Attack Table One or move up to Attack Table Three.
For details about these attacks jump to  xref:roll_playing_system:CH05_Robots_Z_Offensive.adoc#_attack_table_two[Attack Table Two,window=_blank].

include::ROOT:partial$CH05_Table_Robotic_Attack_Table_Two.adoc[]

include::ROOT:partial$CH05_Table_Type_B_Weapon_Type.adoc[]

=== Attack Table Three
Even more dangerous attacks.
These attacks are a mix of baked-in weapons and misused devices.
It is possible to get several rolls on Attack Table Two or move up to Attack Table Four.
For details about these attacks jump to  xref:roll_playing_system:CH05_Robots_Z_Offensive.adoc#_attack_table_three[Attack Table Three,window=_blank].

include::ROOT:partial$CH05_Table_Robotic_Attack_Table_Three.adoc[]

=== Attack Table Four
Even more dangerous attacks.
These attacks are a mix of baked-in weapons and misused devices.
It is possible to get several rolls on Attack Table Three.
For details about these attacks jump to  xref:roll_playing_system:CH05_Robots_Z_Offensive.adoc#_attack_table_four[Attack Table Four,window=_blank].

include::ROOT:partial$CH05_Table_Robotic_Attack_Table_Four.adoc[]

== Defences
Robot defences can arise from misused peripherals or intentionally baked-in defensive systems.
For more detailed explanations jump to xref:roll_playing_system:CH05_Robots_Z_Defensive.adoc[Defensive Systems,window=_blank].

include::ROOT:partial$CH05_Table_Robotic_Defences.adoc[]

== Peripherals
Peripherals are attachments that give the robot some additional flexibility in performing its tasks.
Peripherals are not weapons. 
For more detailed explanations jump to xref:roll_playing_system:CH05_Robots_Z_Peripherals.adoc[Peripheral Systems,window=_blank].

include::ROOT:partial$CH05_Table_Primary_Robotic_Peripherals.adoc[]

include::ROOT:partial$CH05_Table_Robotic_Secondary_Peripherals.adoc[]

== Robot RP Control Factor
Calculate the persona's control factor here.
For more details jump to xref:robots:control_factor.adoc[Control Factor,window=_blank].

include::roll_playing_system:page$CH05_Robots_Z_CF.adoc[tag=control_factor]

== Robot RP Adaptability
If there is a need to know the referee persona's adaptability check the fabrication info for the robot type.

== Robot RP Value
Most referee persona robots do not like to talk about their value. 
If there is a need to know the referee persona's value check the fabrication info for the robot type.

== Robot RP Tech Level
Tech level alters the wate and size of artifacts.
There is no mechanism in EXP for altering robots based on their tech level. 
Is a high tech level robot less able to ram because it is now lighter? 
Tech level could increase the value of a robot, improve its power plant, and overall alter its appearance.
Would steam power a low tech level robot? 
For more info and the effects of altering tech levels, jump to xref:software:CH56_Tech_Level.adoc[Tech Level,window=_blank].

include::ROOT:partial$CH49_Table_TOY_Tech_Level.adoc[]

== Robot RP Age
Robots do not age.
Unlike organic life forms, robots only decay from damage and not time. 
The longer it has been since fabrication allows for an estimate of how much damage the robot has experienced.
The robot age table was previously called the decrepitude table.

include::ROOT:partial$CH11_Table_Robot_RP_Age.adoc[]

== Robot RP Attack Table
The attack table keeps track of the persona's combat skills and increases with EXPS level.
The referee may need two attack tables for her tool using aliens.
For general info about attack tables, jump to xref:roll_playing_system:CH09_Combat_Tables.adoc[Attack Tables,window=_blank] in tactical combat.
For a detailed explanation of the outline below jump to xref:robots:attack_table.adoc[Robot Attack Table,window=_blank].

This attack table is for baked-in offensive systems and ramming freedom.
Robot RPs only have a Skilled Bonus (Skilled) for their baked-in attacks. 
If a robot RP manages to use a gun, her Skilled is zero.
If the robot type is Android (A), then the referee must make an anthro-like vocation-based attack table as well.
For the vocation based attack table, jump to xref:anthros:attack_table[Anthro attack table,window=_blank].

:art: bots_bots_bots.png
:width: 350px
:snark: Combat ratio can alter numbers.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Many flying robots.

include::ROOT:partial$articulate.adoc[]

== Robot RP Combat Ratio
// boilerplate is from anthro RP
include::CH11_Referee_Personas_Anthro.adoc[tag=Combat_Ratio]

=== Robot Specific

include::ROOT:partial$CH11_Table_RP_CR_Robot.adoc[]

// general CR adjustments list of tables.
// heading is === for each table
include::ROOT:partial$CH11_Table_RP_CR_General.adoc[]

== Robot RP Technology
Qualitative details about how the robot moves, sees, and powers itself.

=== Robot RP Power Source
Robot power sources are sciency fiction supercells that allow the robot to operate.
Recharging may be necessary.
For more detailed information, jump to xref:robots:power_source.adoc[Power Source,window=_blank].

include::robots:partial$power_cell_types.adoc[]

=== Robot RP Sensors
Robot sensors allow the robot RP to hear and see like any other persona.
The higher the RPs Awareness, the more sensors they have. 
For more detailed information, jump to xref:robots:sensors.adoc[Sensors,window=_blank].

include::robots:partial$sensor_types.adoc[]

=== Robot RP Locomotion
Robot locomotion allows the RP to get anywhere she can fit.
For more detailed information, jump to xref:roll_playing_system:CH05_Robots_Z_Locomotion.adoc[Locomotion,window=_blank].

include::ROOT:partial$CH05_Table_Robotic_Primary_Locomotion.adoc[]

include::ROOT:partial$CH05_Table_Robotic_Secondary_Locomotion_Type.adoc[]

== Robot RP Story
The referee persona's story is a skeleton to help the referee create a backstory.
The past, present, future and personality of the persona give the referee a skeleton to hang the story meat.
Cannon, and canon, fodder do not have detailed stories at all. 
Canonical personas may need a lot more.

=== Past
L33t Un1t is an expendable combot left on the planet from a past war.
She has no command and control and wanders around the desert near the expedition's home base.

include::ROOT:partial$CH11_Table_Referee_Persona_Origin.adoc[]

=== Present
L33t Un1t still misses the organizational elements of an organized military force.
She would be happy to take direction from anyone with military training.
L33t Un1t will work with the expedition if they offer this kind of direction to her.

include::ROOT:partial$CH11_Table_Referee_Persona_Presence.adoc[]

=== Future
L33t Un1t desires nothing more than to find meaningful leadership.
She will leave the expedition to follow any combot or military brass from her previous campaign.

include::ROOT:partial$CH11_Table_Referee_Persona_Goal.adoc[]

=== Personality
Robot personalities are accidental and arise from malfunctions and damage to their processes.
If the robot RP was to be appropriately 'repaired,' she would lose her personality.

include::ROOT:partial$CH11_Table_Introverted_Personality_Trait.adoc[]

== Robot RP Appearance
Shape, colours, locomotion type, and peripherals contribute to the robot RP appearance.
These tables are for inspiration and fun and should not replace referee creativity.

=== Basic Shape
The basic shape is fit into the dimensions of the robot. 

include::ROOT:partial$CH05_Table_Robotic_Basic_Shape.adoc[]

=== Contortion of Basic Shape
The referee can contort the shape above for fun and randomness.

include::ROOT:partial$CH05_Table_Robotic_Basic_Shape_Adjustment.adoc[]

=== Attachments
Useless attachments.

include::ROOT:partial$CH11_Table_Fancy_Attachments.adoc[]

=== Colour Your Robot
Colour makes the world go round.

include::ROOT:partial$add_colour_to_your_world.adoc[]

== Robot RP Beliefs
The robot RP can have beliefs similar to an anthro persona.
The robot may be randomly expressing these beliefs due to the damage that gave her consciousness.
The robot may intentionally express these beliefs because they were programmed in by the fabricator type or corporation.

include::ROOT:partial$CH11_Table_RP_Beliefs.adoc[]

include::ROOT:partial$CH11_Table_Referee_Persona_Religious_Belief.adoc[]

include::ROOT:partial$CH11_Table_Referee_Persona_Political_Belief.adoc[]

include::ROOT:partial$CH11_Table_Referee_Persona_Philosophical_Belief.adoc[]

== Robot RP Name
The robot should have a name like any other persona.
Robot names can become complicated because they may need a persona name, model name and fabricator name.
For more details on naming shenanigans, jump to xref:robots:moniker.adoc[Robot Name,window=_blank].
