= Artifact Identification

Technology in EXP is diverse and prolific.
Not knowing an artifact's intended use is a core experience of the game.
Some TOYs will defy the understanding of players and their personas.
Consider the potpourri of technological devices drawn from a universe of cultures, each at a different technological growth.

Ideally, personas figure out what equipment does by role-playing.
Often this is too laborious a process, so a fun mini-game exists to replace this process.
This mini-game is the artifact identification flowchart. 

NOTE: *A tragic epidemic on mundane terra lead to the renaming of the AID Flowchart for version 6.0.*

The AID flowchart should be judiciously applied.
The referee should decline using this mini-game for devices that are too important or too mundane.
The referee should not use the AID Flowchart to keep personas from using a spatula.
The players should not use the AID Flowchart to roll themselves through a scenario.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Using the Flowchart
The flowchart should be fun to use. 
Consider it a descriptive mini-game used to replace a process that is too complex to role play.
Role-playing has an impact on the flowchart.
The more role-playing the players invest, the less likely they will blow themselves up.
Experience level, persona Intelligence, tech level, and luck also influence the AID flowchart. 

The player navigates the flowchart with a series of *1d10 rolls*. 

// duration per roll

:art: aid_table.png
:width: 650px
:snark: Playing with fire for science.
:artist: HM
:date: 2010
:license: CC BY-SA 4.0
:description: Flowchart show process for identifying, activating and damaging artifacts.

include::ROOT:partial$articulate.adoc[]

== Duration of Artifact ID
Each roll on the AID Flowchart takes a variable amount of game time. 
A complicated low-tech cloning machine should not be sorted out in a few minutes by a persona.
An obvious gun-looking gun should not take a mercenary ten days to figure out.

To make the AID Flowchart more faux realistic, the referee can change the duration of each roll.
For example, can the fusion rifle be identified in time for the mercenary to use it?
Or can the rejuvenation chamber be activated before the dead persona starts to smell?

Each roll on the flowchart can represent minutes, hours, days or even weeks.
The referee may alter the flowchart such that each 1d10 roll represents a year of research and several adventures.
In the end, the flowchart should be fun to use.

== Start
The player starts on this location once they have committed to identifying the artifact.

=== Restarting 
If a persona stops the identification process, she may be able to pick up where she left off.
A persona can restart where she left off as long she continues in less than 24 hours.
A player may elect to stop rolling if they feel things are going badly.
For example, if the artifact is making scary accidental activation noises, it may be best to stop.

== Colour Positions A to F
The colourful circles are for adding colour commentary to the flowchart process. 
The referee may associate each circle with a particular sound or mechanism position.
These embellishments can be for fun, or be they can be used as clues.

For example, position A could fill the persona with a sense of 'nearly there' or an equivalent sound effect.
Or landing on position E could make a scary activation noise or activate a countdown timer.

A player can exit the process at any colour position. 
The player cannot exit the flowchart if they land on a decision point. 
She can return the next day to start at the same colour position, wait longer to start fresh at Start.

== Identified!
The Identified! flowchart endpoint indicates the person has figured out what the artifact is.

:art: bot_tv_hand_win.png
:width: 300px
:snark: I knew it all along.
:artist: StudioStoks, mod HM
:date: 2018
:license: Copyright by StudioStoks
:description: Robot hand with green win sign on palm.

include::ROOT:partial$articulate.adoc[]

The artifact can no longer accidentally harm the persona.
Identification does not indicate that she knows everything about the artifact.
If the artifact is simple, a successful artifact identification can include information about operation and maintenance.
Identification should protect the persona from immediate harm.
For example, a nuclear device is no longer trying to be used as a portable oven.
Successful identification does not mean the persona is skilled at using the artifact, knows its value, or knows its tech level.



Identification of an artifact can mean many things.
The referee must remember that Identification is a __positive__ result.
Usually, identification only indicates the general use of the artifact.
For example, this is a medical device for healing (not a bomb), this is a drug (not perfume), this is a napalm aerosol (not hair spray).

Complete identification of an artifact depends on the persona's vocation.
Some artifacts have specific vocation designations.
For example, mercenaries can identify bombs, aerosols, and weapons.
A nomad best identifies climbing equipment.

== Activated!
The Activated! flowchart endpoint indicates that the persona has unwittingly turned on the artifact.

:art: bot_tv_hand_activated.png
:width: 300px
:snark: I meant to do that.
:artist: StudioStoks, mod HM
:date: 2018
:license: Copyright by StudioStoks
:description: Robot hand with yellow accidental activation sign on palm.

include::ROOT:partial$articulate.adoc[]

For weapons, bombs and grenades, accidental activation can be deadly.
However, accidental activation is not all bad.
An accidental activation reveals a lot of information about the artifact.
The players may be able to identify the artifact just by what happens when it activates.

Personas learn a lot from an accidentally activated TOY.
Accidental activation for a vocation-specific TOY also counts as an identification.
A mercenary persona that accidentally fires a weapon automatically identifies it.  

After an accidental activation, the persona returns to Start with additional information.
The new information gives a +2 bonus on all successive AID rolls.
The bonuses for accidental activation are cumulative.
Another accidental activation increased the bonus to +4.
Damage! and Activation! bonuses are cumulative.

== Damaged!
The Damaged! flowchart endpoint indicates that the persona has injured the artifact.

:art: bot_tv_hand_damaged.png
:width: 300px
:snark: It was on fire when I got here.
:artist: StudioStoks, mod HM
:date: 2018
:license: Copyright by StudioStoks
:description: Robot hand with red accidental damage sign on palm.

include::ROOT:partial$articulate.adoc[]

The referee can announce arrival at this endpoint with horrible crunching noises or tragic beeping.
The artifact suffers an artifact damage roll, and the persona returns to Start.

include::ROOT:partial$CH21_Table_Artifact_Extent_of_Damage.adoc[]

Artifact damage requires the subtle intervention of the referee.
Some artifacts just can't be broken.
Other artifacts are obviously delicate.
For more detailed information, jump to xref:roll_playing_system:combat:breaking_things.adoc[Artifact Damage,window=_blank].

Personas learn a bit from artifact damage.
The persona returns to the Start with information about what not to do this time.
The new information gives a +1 bonus on all successive AID rolls.
The bonuses for damaging an artifact are cumulative.
Another artifact damage improves the bonus to +2.
Damage! and Activation! bonuses are cumulative.

== AID Flowchart Adjustments
Many factors affect the persona's navigation through artifact identification.

=== Vocation Adjustments
Mechanics enjoy a particular advantage over all other vocations.
A player with a mechanic persona uses 1d12 instead of the 1d10 roll when making AID rolls.
Mechanics can also lead a research team, and their ideas (rolls) are not subject to Charisma competitions.

The referee may offer bonuses to vocation-specific artifacts.
For example, a mercenary would get a bonus when trying to identify weapons or armour.

The players should keep in mind that accidental activation of a vocation-specific artifact counts as Identified!

A persona-centred version of the AID Flowchart allows the player to add her EXPS Level to each die roll when working with vocation-specific equipment.

include::ROOT:partial$CH20_Table_Class_Specific_Artifacts.adoc[]

== Tech Level Adjustments 
Tech level is a term that loosely represents the artifact's level of technological development.
A persona from the middle ages would be at a loss in a modern kitchen.
A persona from the modern world would be lost in a middle ages kitchen.
The further the tech level is from the personas native tech level, the harder it is to identify the artifact.

include::ROOT:partial$CH20_Table_Tech_Level_and_AID.adoc[]

Some high-tech artifacts are combined devices called multi-toys. 
Multi equipment is common with very high-tech TOYS.
The persona may identify one part of a multi-toy and not another part. 

There is also the possibility that high-tech devices will come with baked-in instructions.
Whether these are linguistically helpful or confusing is determined by the referee's milieu.

== Role-Playing Adjustments 
Adjustments are added depending on how the persona conducts her study of the artifact.
If the player says that her persona is being very careful, she will add 3 to roll in circle E.
If the player says that her persona is in a reckless rush, she will subtract two from her roll in circle  E.

include::ROOT:partial$CH20_Table_AID_Style_Adjustment.adoc[]

== Research Teams
Personas can get together to improve their chances of successful identification.
Two heads are better than one, or many hands make confusing work. 
The referee can allow as many personas to join in as makes sense.
An artifact may not dispose itself to being surrounded by curious personas.

Every participant on the AID Research Team gets to roll a 1d10.
The referee can average this roll. 
Averaging is arithmetically challenging and can trap the team in a loop.
Getting stuck in a loop is a common problem with teams on mundane terra.

A more exciting approach is to have all the players roll at once. 
The highest roll pairs with the lowest roll, and those two personas argue over who is correct.
A Charisma attribute competition decides which 'idea' moves the team forward.
While this seems completely insane, it is how teams commonly proceed on Mundane Terra.
