= Artifacts

[quote]
____
*A bad manual makes the simplest technology appear as magic* 
____

:art: babooshkas_PSH.png
:width: 550px
:snark: Complicated old lady doll
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of researcher inspecting set of Russian dolls.

include::ROOT:partial$articulate.adoc[]

// basis of EXP
// technology terminology
// artifacts, TOYS, tech
// ID is a mini-game.
// Destroying things
// NOT Mundane equipment

EXP's headline is "The Game of Technological Chaos."
This title reflects a rule system where one can expect any device to exist alongside any other device.
Is the laser pen mightier than the vibro sword?
Can a low-tech culture devote all its resources to make a time machine?
Can a high-tech culture devote all its resources to make itself feel sad and pathetic?
Add a bit of humour, and these explorations are what EXP is all about.

NOTE: *Technology represents a mix of unknown devices.*

In our mundane terra's olden daze, there was a game show dedicated to https://en.wikipedia.org/wiki/What_in_the_World[identifying things,window=_blank].
This game show broadcast on a one-way colourless video device called a television.
The artifact system in EXP is like a simulated version of that game show. 

More than 70 years later, neither this game show nor the TV device exists.
A handheld piece of glass with high-resolution full colour moving pictures has replaced the television. 
This evolution of the television took four generations on mundane terra.

:art: converting_nature.png
:width: 550px
:snark: Converting healthy air into money
:artist: Leon Bennet 
:date: 1887
:license: CC BY-SA 4.0
:description: Drawing of humanoid overlooking enormous smokestack covered factory.

include::ROOT:partial$articulate.adoc[]

How the technological chaos arises is up to the milieu of the referee.
Did countless societies rise and fall, leaving their technology to be found later?
Did alien civilizations leave their garbage behind under https://en.wikipedia.org/wiki/Stargate[pyramids,window=_blank]?
Or is it both?
EXP's artifact ruleset is play tested to deliver a fake and fun take on this kind of milieu.
If this sounds like fun, you are in the right place.

== Nomenclature
Calling technological devices artifacts is a twist on the archeological nature of their discovery.
These discovered artifacts represent the detritus of a technologically advanced civilization.
Everything old is new again.
EXP artifacts are usually found by personas while on an expedition.
There is no reason that the expedition could not purchase them from a local junk store, print catalogue or computer store.

The players generate technomagical equipment using the Technological Object Yield System.
This Technological Object Yield System is called TOYs for short, and anything it generates is a toy.
An unidentified toy is called an artifact.
An identified toy is called a toy or equipment.
Each group of players will develop their language for equipment.

.*Artifact Checklist*
* xref:hardware:An_index_hardware.adoc[Generating Artifacts,window=_blank]
* xref:software:CH56_Tech_Level.adoc[Tech Level,window=_blank]
* xref:CH20_Artifact_ID.adoc[Artifact Identification,window=_blank]
