= Equipment Damage

Personas aren't the only things that get destroyed in EXP.
Besides the ceaseless battering of personas, inorganic equipment is also subject to the effects of entropy.
In EXP, nothing is indestructible, everything wears out, and what can go wrong will.
Equipment damage is reserved for unique circumstances and is not part of regular gameplay.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

Equipment does not have hit points like personas.
It would be a total bore to keep track of equipment HPS.
Equipment HPS comes into play for unfortunate circumstances where the referee needs to quantify a mishap.
Non-artifact equipment, aka mundane, equipment is usually just destroyed by incidents.

A crucial artifact that is the centrepiece of a campaign may have an HPS total.
For example, the referee may use the artifact damage if a persona uses her prized plasma rifle as a crowbar.

:art: smashing_brick.png
:width: 250px
:snark: Humanoids in glass houses...
:artist: James Shields
:date: 2014
:license: Copyright JEShields Stock Art
:description: Drawing of brick smashing through pane of glass.

include::ROOT:partial$articulate.adoc[]

== Determining Artifact Hit Points
The artifact's EXPS is the basis for an artifact's hit points. 
The higher the tech level, the tougher the artifact

=== Artifact Hit Points
.Artifact HPS = Fraction EXPS + Tech Level
****
200 EXPS, TL 10 vet equipment: 16 HPS = 3% x 200 + 10  +
540 EXPS, TL 20 aerosol: 128 HPS = 20% x 540 + 20
****

include::ROOT:partial$CH21_Table_Artifact_Hit_Points.adoc[]

A tech level 10 age determiner is worth 200 EXPS.
Vet equipment earns 3% of EXPS for HPS.
The age determiner can withstand 16 HPS of damage (3% x 200 + 10) before being damaged.

A tech level 20 napalm grenade is worth 540 EXPS.
Grenades earn 20% of their EXPS value as HPS.
So this grenade would have 128 HPS (20% x 540 + 20).

== Damaging Equipment
Artifacts are technomagical and are composed of alloys, and polymers.
Equipment is most often damaged by AOE attacks, direct hits, kinetic tragedy and malice.
Anything that damages a persona will damage equipment.

:art: falling_gun.png
:width: 250px
:snark: Oops, kinetic tragedy!
:artist: HM
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of high tech pistol falling towards the ground.

include::ROOT:partial$articulate.adoc[]


== Extent of Damage
Nothing happens to the equipment until it reaches zero HPS.
When this happens, the toy does not go unconscious or die, but it suffers damage.
The extent of damage roll shows what percentage of previous function the toy presently has.
The extent of damage can vary from trivial (cosmetic only) to the destruction of the artifact.

include::ROOT:partial$CH21_Table_Artifact_Extent_of_Damage.adoc[]

Massive amounts of damage can generate multiple rolls on the extent of the damage table.
For example, an artifact with 5 HPS taking 15 HPS damage at once would make three rolls on the extent of damage table.
The damage would be cumulative likely destroying the artifact.
Ouch.

=== Trivial Damage
The least detrimental is trivial damage.
Trivial damage does not affect the performance of the artifact.
The damage could be cosmetic or a mere annoyance, such as a stuck button or scratched finish.

=== Minor, Major and Critical Damage
These three damage categories decrease the function of the artifact.
Unlike the trivial and destroyed damage categories, these categories require some arithmetic.

Each time an artifact takes damage, its effectiveness drops.
The results of reduced performance affect all aspects of the device's performance.
Range, battery duration, duration of effect, area of effect, hit bonuses, and armour ratings are examples of what reduces when an artifact is damaged.
Cumulative damage rolls can totally disable a toy without destroying it.

An artifact that sustains minor damage will function at 90% of previous performance.
A generic artifact that has a range of 100 hexes takes minor damage.
Minor damage reduces its range to 90% of previous performance or 90 hexes.
The same artifact now sustains critical damage and will function at 30% of previous performance.
The generic artifact now has a range of 27 hexes (30% of 90 hex range).

Damaged artifacts are repairable.
The more damaged the artifact, the more difficult the repair.
Destroyed artifacts are not repairable.

=== Destroyed
Destroyed is the worst possible damage that an artifact can sustain.
Destroyed artifacts no longer function.
Destroyed artifacts are unrepairable.
A destroyed artifact becomes a dead wate which may only be valuable for a few spare parts.

Destroying an artifact in one blow may lead to additional consequences.
Often players will expect a destroyed bomb or grenade to activate accidentally.
If a discussion arises about accidental activation the players may need to consult a xref:roll_playing_system:CH16_Special_Rolls_Asshole.adoc[Sphincter Roll,window=_blank]

:art: equip_damage_chicken.png
:width: 250px
:snark: Rubber chick organ maintenance is crucial
:artist: Andrew Brechin
:date: 1991 
:license: CC BY-SA 4.0
:description: Drawing of tuxedo clad humanoid pulling chicken out of futuristic music organ.

include::ROOT:partial$articulate.adoc[]

=== Maintenance
Maintenance of equipment is for those referees and players working through https://en.wikipedia.org/wiki/Obsessive%E2%80%93compulsive_disorder[OCD].

The more moving parts the artifact has, the more maintenance is needed.
For example, a vehicle needs regular maintenance, but a grenade does not.
A pharmaceutical tablet may be able to sit around for decades.
An ointment may require refrigeration and air conditioning.

Un-maintained artifacts will deteriorate.
Equipment subject to any semblance of routine maintenance is not be affected by wear and tear.
To avoid deterioration, players merely need to say they are maintaining their artifacts. 
Complicated vehicles may require a mechanic for maintenance.
A mercenary can maintain weapons. 
A veterinarian can maintain vet equipment.

The referee can make an extent of damage roll once a year for unmaintained equipment.

:art: glass_half_broken.png
:width: 350px
:snark: It was broken when I got here.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: A few shards of broken glass on the ground.

include::ROOT:partial$articulate.adoc[]

== Mundane Equipment Damage
Personas will often insist on damaging mundane items that surround them.
They may wish to destroy a door, crash through a wall, blow a hole in the road, or destroy a bridge.
The referee can't have the HPS of architectural items such as walls, doors, windows and the like prepared for each particular scenario.

Mundane Doors and-walls are destroyed when they lose all their HPS.
For instance, a mundane door has 30 HPS.
If a door takes 30 HPS, it ceases to be a door and now is an opening with sharp edges.

include::ROOT:partial$CH21_Table_Mundane_Artifacts_Hit_Points.adoc[]
