= Money

Money is beneath most heroic adventurers. 
They are interested in artifacts and altering the universe.
However, money does make the planet go around.

:art: money.png
:width: 350px
:snark: Current currencies.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of different kinds of currency piled up and scattered about.

include::ROOT:partial$articulate.adoc[]

This section gives a money baseline for the players and referee.
Referees may create a monetary system for their milieu.
A twelve toed alien society may evolve a base 12 currency.
What is the value of a dollar bill in a post-apocalyptic wasteland?
The post-apocalyptic currency may be mouthfuls of clean water.

.*Sources of Cash*
* xref:roll_playing_system:CH10_Incidentals.adoc[Incidentals,window=_blank].
* xref:hardware:CH53_Treasure.adoc[Treasure,window=_blank].
* Earn it in the wilds.

== EXP Standard Currency
EXP values use the electrum piece standard.
The electrum piece (eps) is a coin-based standard.
The eps standard uses a decimal system where the base unit is one.
 The remaining coins are tens, hundreds, tenths and hundredths.
The wate and rough diameter of each coin are the same.   
The diameter is 25 mm or about an inch.
The wate is 25 gm.
A 25 gm coin is a very heavy coin.
42 of these heavy coins have a wate of 1 kg.
The EXP coinage most resembles the mundane terran
https://en.wikipedia.org/wiki/Loonie[Canadian Loonie,window=_blank].

While each coin type has the same wate and rough diameter, each coin type is visually, tactilely and acoustically unique.
Each of the denominations has its colour, markings, edging, and sound.
A persona can differentiate between the coins by their colour, touch and sound.
If a coin is tapped or rung, it will create a sound unique to that coin.

include::ROOT:partial$CH23_Table_Currency_Units.adoc[]

== Kinds of Currency
The referee can modify her currency based on the relative values of the EXP standard currency.
Currencies can come in any form: cards, chemicals, wate, credit vouchers, or paper.
Currencies can come in any nomenclature: bucks, domars, cubits, credits, crillos, units, bytes, sense, and doll hairs.

== Barter
If a milieu has currency, a certain level of a cohesive society is implicit.
The most likely form of exchange for a technologically collapsed, or resource austere, society is barter.
A bartering system does conjure up an infinite supply of role-playing situations.
The players may prefer to have dice rolling from xref:roll_playing_system:CH22_Negotiations.adoc#_social_interaction_tables[Social Interactions,window=_blank] replace role playing barter.

The referee can use the values assigned to artifacts to guide the barter.
A 1000k eps artifact is worth five times more than a 200k eps artifact.
The personas may never discuss the artifacts' actual values, but their relative values become the barter's driving force.
Using values to guide barter is only a guideline.
If the expedition needs a specific artifact to complete a mission, then that artifact may become priceless.


