= Area of Effect Attacks

[quote]
____
*Close counts in hand grenades and aerosols.*
____

An area of effect attack wreaks its havoc on a bunch of hexes instead of a specific target.
Area of effect weapons target a  hex instead of a target persona.
Every target (friend or foe) in that area of effect is automatically affected by the attack.
Following are the detailed rules for Area (area of effect) attacks. 

:art: lion_grenade.png
:width: 250px
:snark: Simba deals with Scar.
:artist: Andrew Brechin
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of angry humanoid lion throwing a grenade with an atomic cloud in the background.

include::ROOT:partial$articulate.adoc[]

The most common area of effect attacks arise from grenades and aerosols.
Aliens and robots can have an area of effect attack as natural abilities or offensive systems.
Most alien and robot area of effect attacks function like a grenade or an aerosol, and the rules work the same.

== Grenades 
Grenades are area of effect attacks that personas aim at a target hex.
Combat with Molotov's, acid misters, pipe bombs, explosives and artifact grenades is covered here.
Alien and robot area of effects attacks use the grenade rules as described.

Grenades are effective and dangerous.
They do not come with warning labels. 
Personas cannot safely throw some artifact grenades.
Armour does not absorb grenade damage.
The grenade area of effect is three-dimensional.

WARNING: *Area of effect attacks damage friend and foe equally.*

.*Steps of a grenade attack*
. <<_range,Range>>
. <<_attack_roll,Attack Roll>>
. <<_area_of_effect,Area of Effect>>
. <<_grenade_effect,Wreak Havoc>>

== Range
The range of a grenade attack indicates how far away the target hex can be from the persona.
The range is different from the area of effect.
The area of effect depends on the power of the grenade attack.
So the persona determines the range, and the grenade defines the area of effect.

The player chooses the target hex that her persona is targeting.
Grenades are most commonly thrown (Fling). 
Grenades can also be launched (Shoot).
The persona can throw a grenade one hex per point of Strength.

=== Grenade Range (thrown)
.Range = 1 hex per point of STR
****
A persona with a 12 STR can pick a target hex up to 12 hexes away.
****

The grenade launcher determines the range of a launched grenade (Shoot attack). 
Usually, a grenade launcher can fire a grenade much further than a persona can throw one.

The player can count the number of hexes between herself and the target hex.
The player is not allowed to count the number of hexes of the area of effect.
If the persona has grenade proficiency, her player can count the number of hexes of the area of effect.

:art: Figure_range_vs_aoe.png
:width: 450px
:snark: Black line is range. Red is area of effect.
:artist: HM
:date: 2010
:license: CC BY-SA 4.0
:description: Diagram demonstrating range as a line and area of effect covering hexes.

include::ROOT:partial$articulate.adoc[]

== Grenade Activation
Once the grenade is activated (pin, twist cap, or launcher), the persona is committed to the attack.
The pin is a safety device to keep the grenade from exploding in transport.
Once the persona 'pulls the pin,' there is no turning back.
For artifact grenades, a persona may not know how to activate the device. 

== Attack Roll 
The grenade attack roll is a kilo-die roll made by the player.
The role includes skills, bonuses, and lots of chance.
Throwing a grenade in combat is fraught with risk.

The Defence Rating of the target hex is 542.
How can a lump of dirt have such a high Defence Rating?
While it is easy to activate and throw the grenade, success is shrouded in the fog of combat.
Between the kilo die attack roll and the chaos of combat, the lump of dirt has an AR of 542.
A failed attack roll with a grenade can still damage targets upon detonation.
The persona only needs to get close with a grenade.

=== Target Hex Defence Rating
.Target Hex AR = 542
****
The player must roll 542 or higher to hit the target hex. Anything less is a miss.
****

An attack roll is for ranged grenade attacks. 
Attack rolls and grenade misses are for targeted attacks during the chaos of combat.
An attack roll does not apply if the persona drops a grenade down a hole or at her own feet.

=== Attack Roll Bonuses
Players use the persona's attack table to increase their attack roll.
Unless the persona has grenade proficiency, the player will use the Raw Bonus (Raw) for her attack roll.
The grenade delivery determines which attack type the player uses for her attack roll.

If the persona throws the grenade, the player makes a Fling Attack.
If the persona shoots the grenade out of a grenade launcher, the player makes a Shoot Attack.
A Grenade attack that acts as a Strike Attack would be a suicide vest or a land mine. 


If the area of effect attack is an alien natural ability, the player uses her Skilled Bonus.
If the area of effect attack is a robotic baked-in offensive system, the player uses her Skilled Bonus. 

If the player fails her attack roll, this becomes a grenade miss.
While the grenade could land anywhere depending on the kilodie roll, it can still damage the initial target.

== Miss Result 
A miss with a grenade can still be a hit.
A miss will indicate that the grenade lands somewhere other than the target hex.
There is a chance the grenade will still even land in the target hex.
As the adage goes, close only counts in horseshoes and hand grenades.

:art: Figure_grenade_miss_direction_d12.png
:width: 250px
:snark: Roll to see where it rolls (1d12).
:artist: HM
:date: 2010
:license: CC BY-SA 4.0
:description: Diagram with hexagons demonstrating direction of a miss throw.

include::ROOT:partial$articulate.adoc[]

include::ROOT:partial$CH30_Table_Distance_of_Grenade_Miss.adoc[]

:art: Figure_grenade_oops.png
:width: 450px
:snark: Direction 5, 3 hexes or making friends with grenades.
:artist: HM
:date: 2010
:license: CC BY-SA 4.0
:description: Diagram with hexagons demonstrating area of effect with a miss throw.

include::ROOT:partial$articulate.adoc[]

== Area of Effect
The area of effect of the grenade is, not surprisingly, the area in hexes affected by the attack.
The area of effect for grenades is most often a radius of hexagons.
Some powerful grenades have many radii of effects with different injury types.

The area of effect is not the range of a grenade attack. 
While the player can count out the hexes of the range of her attack, she cannot count out the radius of the area of effect.
Not being allowed to count grenade hexes reflects the unpredictability
of area of effect weapons.
Players whose personas have grenade proficiency or skill are allowed to count out the hexes of the radius of effect.

:art: Figure_grenade_area_of_effect.png
:width: 250px
:snark: Area of effect.
:artist: HM 
:date: 2010
:license: CC BY-SA 4.0
:description: Diagram with hexagons demonstrating area of effect.

include::ROOT:partial$articulate.adoc[]

== Grenade Effect
Most grenades deliver a deadly shockwave along with shrapnel or other special effects.
Artifact grenades can deliver additional effects like fire, gas, or even stranger things.
The grenade affects every persona in the area of effect.
Those persons who are located one hex beyond the area of effect are faux realistic lucky.
If the grenade effect is 30 hit points, every persona loses 30 hit points.
If the grenade effect is poison gas, every persona must win a saving roll or take damage.

=== Avoiding Grenades
Players like to have their personas dive for cover if a grenade attack is incoming.
Grenade dodging is movie-style combat fun.
It is unlikely that a persona will notice a baseball flying across the smoky chaotic battlefield.
The persona must both notice the grenade and be able to react before it detonates. 

.*Consideration for Grenade dodging*
. must be able to move, still has movement left in the combat unit.
. must be able to sacrifice her attack in the combat unit.
. must know what a grenade is and not think it is a stick to fetch.
. the referee may require an Awareness roll.

Sturdy protection such as bunkers, rocks, or vehicles can protect a persona from an explosive grenade effect.
This kind of cover would not protect a persona from a gas grenade attack.

Taking cover from an explosive grenade attack can mitigate the damage inflicted.
If a target has 90% cover, then reduce the damage by 90%. 
If the target has 33% cover, then reduce the damage to 33%.
Concealment offers no protection against explosive grenades.

include::ROOT:partial$CH35_Table_Cover_and_Concealment_Penalty.adoc[]

=== Grenade Malfunction
Do it yourself mundane grenade weapons can malfunction in all sorts of ways.
Artifact grenade weapons only come under scrutiny if the player rolls a 42 on the kilo-die.
There is a 1 in 1000 chance that something different will happen when the player makes a grenade attack roll.
Malfunction can occur to alien and robotic grenade-like attacks.
What happens is up to the referee and players.

=== Artifact Grenade Malfunction
.Attack roll = 042
****
If the player rolls 42 on the attack roll, something interesting may happen.
****

== Aerosols
Aerosols are canisters of death that spray their attack with the push of a button.
The gameplay of aerosols is much more straightforward than grenades, but they are no less dangerous.
Almost all aerosols have their business end clearly marked.
The weapon is generally foolproof, and even the nothing vocation can use them without difficulty.
Weaponized aerosols are always artifacts, and there are no mundane aerosols.

For classification, an aerosol is a Shoot Area attack type.
Aliens and robots can have attacks that function the same as aerosols. 

:art: aerosol_face.png
:width: 250px
:snark: Ding dong. Facial calling.
:artist: Michael Jackson
:date: 1990
:license: CC BY-SA 4.0
:description: Drawing showing blast from aerosol dissolving a humanoid face.

include::ROOT:partial$articulate.adoc[]

=== Attack Roll
Aerosols do not require an attack roll and do not malfunction.
The point and shoot nature of the aerosol leads to limited flexibility.
When activated, the aerosol instantly ejects either a stream or blob attack.

=== Stream Aerosol
The stream aerosol attack is the most common.
The aerosol blasts its weaponized contents straight out the front.
An aerosol with a 2 hex by 9 hex stream area of effect cuts a swath 2 hexes wide and 9 hexes long.
Every target in the jet stream is affected by the aerosol.

=== Blob Aerosols
Blob aerosols instantly launch a blob a fixed range and expand out to a radius area of effect.
Blob aerosols function very similarly to a powered grenade launcher.
An aerosol with a 10 hex range, and a 5 hex area of effect, would shoot a blob 10 hexes and then engulf a 10 hex diameter ball of targets (or teammates).
Every persona in the area of effect will be affected by the aerosol.

:art: Figure_Aerosols.png
:width: 450px
:snark: Don't just hurt the ozone.
:artist: HM
:date: 2010
:license: CC BY-SA 4.0
:description: Diagram with hexagons demonstrating aerosol area of effect.

include::ROOT:partial$articulate.adoc[]

=== Confined Spaces
Aerosols do not exhibit great forces like exploding grenades. 
These weapons transform the atmosphere to exert their damage.
Aerosols do not expand beyond the area of effect in a confined space.
A stream aerosol aimed into a tiny room will only affect that tiny room.
This safety feature keeps aerosols from harming their users. 
