
= Attack Roll Adjustments= Hit Location

[quote]
____
*That's gonna leave a mark. Right there.*
____

The tactical combat rules do not automatically use hit locations.
However, players can easily incorporate hit locations. 
Hit locations do not alter the damage delivered to the target.
So a blow to the head that delivers very little damage is a grazing shot.
However, a hit to the foot that delivers many HPS damage represents a severe injury to the foot.

Hit locations are good for storytelling details.
Hit locations can determine if a partial suit of armour is effective.
Hit locations can determine what part of an expensive jumpsuit gets ripped.

The hit locations are tremendously inaccurate. 
A less faux realistic hit location system would require a different chart for every angle of attack.
No one here is going to be making those tables.

== Snap Hit Location 
The snap hit location table quickly indicates where a successful attack roll landed on the target.
The table can also determine what body part a miss nearly damaged.
The referee should not use the snap table for critical damage location rolls.
The snap hit location is best as a descriptive aid.

include::ROOT:partial$CH36_Table_Snap_Hit_Location.adoc[]

== Anthro Hit Locations
Use this table when the referee or players need to know where a successful attack roll lands.

include::ROOT:partial$CH36_Table_Anthro_Hit_Location.adoc[]

== Alien Hit Locations
Alien hit location is challenging. 
What looks like an eye or a mouth may not be an eye or a mouth. 
Alien hit location represents function and tries to avoid anthropization.
Sometimes the indicated hit location does not even exist on the alien.
Improvisation or post factualization will help sort out alien hit location.
Aliens are called diversidae for a reason.

include::ROOT:partial$CH36_Table_Alien_Hit_Location.adoc[]

== Robot Hit Locations
Robot hit location is different from robot damage location.
This chart simply describes where a hit landed. 
The system damaged can be entirely different.
Players cannot expect that shooting cameras on a robot will damage the robot's sensors.
Robots are easy to hit and hard to destroy.

include::ROOT:partial$CH36_Table_Robot_Hit_Location.adoc[]

== Hit Location and Attack Rolls
The tactical combat rules do not take hit locations into account. 
Damage is damage, and the hit locations here are for colour and commentary.
Players often want to target a specific body part and reap the benefits of a head shot or disabling foot shot.
The tactical aspect of combat in EXP focuses on movement, cover and the expedition working together.
If a player wants her persona to shoot a hand about to push a button, the referee will have to cobble something together from existing rules. 

== Hit Location and Damage
Hit location does not alter the damage that the target suffers.
The random damage roll takes into account angles, dodging, anatomy, etc.
The number of hit points delivered determines the injury severity, not the hit location. 

== Hit Location Shifting
Even though hit location does not offer attack roll bonuses or damage bonuses, there may be times where hit location is still important.
For example, a target may be wearing resistant armour a persona may wish to target an unarmoured spot.

Instead of targeting a specific hit location, the player can shift the location hit if her attack roll is successful. 
Only combat vocations like mercenary, knite, and spie can shift hit locations.
The persona must have proficiency with her weapon to shift a hit location.
The player can move the hit location up or down the table, depending on her Bbnus proficient.

The player must first win her attack roll. 
She then rolls the damage and hit location following her success.
The player can move the hit location up or down the hit location chart depending on her Skilled Bonus (Skilled).
In this case, the mercenary persona has a Skilled of +150 for her weapon.
A hit location roll of 800 (Forearm) can shift from the Pectorals (650) to the Shoulder (950).
The hit location does not alter damage. 
However, the new hit location may allow the persona to disarm a target dramatically.

Hit location shifting has limitations on robots and aliens.
What the persona thinks is an alien's eye may be the alien's appendix.
That camera on the robot's hull may be a thermometer.
The persona can choose her hit location, but the effect may be unexpected.
The persona's Skilled Bonus is divided by 10 when shifting on the alien and robot hit location tables.