= Incidentals

[quote]
____
To avoid incidents, don't miss the incidentals.
____

:art: back_pack.jpg
:width: 400px
:snark: Stuff in your stuff.
:artist: aimage. prompt HM.
:date: 2023
:license: CC BY-SA 4.0
:description: Overfilled backpack.
include::ROOT:partial$articulate.adoc[]

Incidentals are game elements that are not part of the biology, personality or knowledge of the persona.
If an incidental is added or removed from the persona, the persona remains the same. 
A persona may behave differently if they lose all their money, but they remain the same persona.
Incidental items are just that, incidental. 

== Families
Anthro personas usually need all the mundane stuff included here.
Anthros are soft and defenceless against the universe.
Robot personas have no interest in anything in this section.
Alien persona's need for this mundane stuff depends on their culture and society.

== Mythos
Incidentals must align with the referee's milieu and campaign.
An austere post apocalyptic milieu will not have start money or startifacts.
A cyberpunk metropolis milieu will have start money and startifacts.

If there is are no tools, skip Start Equipment.
If there is no money, skip Start Money.
If there is no high-tech, then skip Startifacts.
This section is here for convenience, and it is not an attempt to wreak havoc with a referee's milieu.


// tag::austerity_levels[]
=== Post Apocalyptic
* No Start Money
* No Start Equipment
* No Startifacts
* One prized piece of xref:hardware:junque.adoc[Junque]

=== Austere
* No Start Money
* Limited survival pack
* Solitary Startifact

=== Typical 
* Start Money
* Start Equipment
* Startifacts

=== Abundant
* Start Money
* Start Equipment
* Purchase from xref:hardware:a_introduction.adoc[Hardware,window=_blank] 

=== Opulent
* Start Money not needed
* Start Equipment is all bespoke
* Pick from xref:hardware:a_introduction.adoc[Hardware,window=_blank] 
// end::austerity_levels[]

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Start Money
Start money is the persona's pocket money on day zero of the campaign.
This money usually represents the persona's total worth.
Personas may keep their start money in a jingling satchel or a plastic money card.
What money is depends on the milieu set out by the referee and players.
The default currency in EXP is the eps (electrum piece).

For more details about money xref:uncombat:money.adoc[Jump here.,window=_blank].

include::roll_playing_system:partial$vocation_start_up_money.adoc[]

== Start Equipment
This equipment will be of the mundane variety.
Here mundane means lo-fi, lo-tech tool level equipment.
Slightly higher-tech equipment is available.
Higher tech equipment is lighter and costs more.
There are no artifacts available for purchase in the incidentals. 
Personas get artifacts from the Technological Object Yield System (TOYS).
For players not interested in pouring over lists, below is a mundane survival pack.

To engage in the vagaries of purchasing mundane equipment  xref:hardware:mundane_equipment.adoc[jump here.,window=_blank]

=== Survival Pack
The survival pack costs 70 eps and has a wate of 13.5 kg.
The survival pack is supposed to speed up the equipment buying procedure.
The referee can configure her survival packs as she sees fit.

include::hardware:partial$mundane_survival_pack.adoc[]

== Startifacts
Startifacts are a mash up of Start and Artifacts.
Artifacts are technological devices that are not mundane, but are not necessarily useful.
A typical EXP milieu will have each persona start with an artifact or three.
This is in the spirit of technological chaos. 
There is *NO* guarantee that the persona will know how to use the artifact.
It is possible they will have no idea what the artifact is.

Startifacts are generated on the Technological Object Yield System and are also called TOYs.
Artifacts sound more serious than toys, but both are meant to be fun. 
To get some startifacts xref:hardware:startifacts.adoc[jump here,window=_blank]


