= Kilodie Mechanic

[quote]
____
*50 times better than a 20 sided*
____

Reading the following is recommended, but an online support tool exists at https://kilodie.expgame.com[kilodie.expgame.com]

The kilo-die is a thousand sided die, or 1d1000.
The 1d1000 generates a random number between 1 and 1000.
1d1000 rolls are the die rolls made in combat attack rolls.
Hence the nickname kill-o-die.

The kilodie allows the referee to assign tiny adjustments for minutiae.
For example, a player wants an attack roll bonus for making a ferocious face during combat.
The referee rewards the role-playing aspect of this by giving the player +10 on her attack roll.
If the player scores a hit because of the +10, there will be much rejoicing and merriment.
The kilodie allows for more detail and fun in the tactical combat rules.

== The Dice 
:art: 664_GYR.png
:width: 250px
:snark: Not a golf ball with microscopic writing.
:artist: HM
:date: 2020
:license: CC BY-SA 4.0
:description: Three dice. Green ten sider, yellow ten sider, and red ten sider.
include::ROOT:partial$articulate.adoc[]

== How to Roll
Three ten-sided dice simulate the 1d1000 die roll.
Usually three separate coloured ten sided dice are rolled at once. 
For example, roll a green, a yellow and a red ten sided dice all at once.

* The green die is assigned the hundreds place.
** 900, 800, 700, 600, 500, 400, 300, 200, 100 and 0 
* The yellow die is assigned to the tens place.
** 90, 80, 70, 60, 50, 40, 30, 20, 10 and 0 
* The red die is assigned to the digits place.
** 9, 8, 7, 6, 5, 4, 3, 2, 1 and 0 
* 0 0 0 is 1000 because that is more fun than 0

Rolling six on the green ten sider, six on the yellow ten sider, and four on the red ten sider results in a kilodie roll of 664.
One can also roll a 1d10 three times to get the same result. 
However, users of the Roll Playing System usually prefer to roll lots of dice.

include::roll_playing_system:partial$kilo_die_roll_examples.adoc[]

A player could also roll a single ten sided die three times in a row and build the kilodie result one roll at a time. 


== Alternate Dice Choices
If your table prefers to use a simpler die, 1d1000 is easily divisible to accommodate simpler dice shapes.

include::roll_playing_system:partial$kilo_die_divider.adoc[]
