= Mutating

[quote]
____
*to change state or condition, undergo change, from Latin mutatus, past participle of mutare to change*
____

In EXP, the term mutation is not limited to the biological transformation of DNA.
Mutations represent randomly acquired permanent changes to the persona. 
The mutation story is deeply rooted in Sciency Fiction.
On mundane terra, biological mutations are mostly fatal.

In the Sciency Fiction world of EXP, mutations are just plain fun.
A referee can't explain this process scientifically.
Mutations are part of the game and fall under the 'black box' explanation. 
However, pseudo-scientific justifications add to the milieu of the campaign.

Mutations have two broad categories: psionic and phenomic.
Mutations.

NOTE: Historically mutations were divided between physical (phenomic) and mental (psionic)

This section is a tasty overview of mutations in EXP.
Mutating is a mere place holder to help with persona generation.
The meat, metal and metamorphosis of mutations is in the section xref:wetware:a_introduction.adoc[Mutations]

== Anthros (Mutations)

Anthro mutations represent changes in persona DNA that create unique persona changes.
Mutations can be innocuous, powerful or deleterious.
Anthro mutations are the stuff of Sciency Fiction legend from comics to movies.
Players have full awareness of their persona's mutations.
However, a fun campaign twist is to have a mutation that is activated by a story trigger.
It is fair game, and fun, to have personas acquire their mutations through gameplay.
Going skinny dipping in the glowing creek may activate an unknown mutation.
Anthro mutations are aptly called *mutations*.
To get the deets on anthro mutations, jump to xref:anthros:mutation_check.adoc[Anthro Mutations]. 


== Aliens (Evolutations)
Evolving an alien creates not just a persona but an entire species.
Alien mutations are natural abilities that the alien species has evolved.
However, it does not mean that every member of the species will have that mutation.
For example, if an alien person has the mutation time stop, it is unlikely every alien in the species does.
EXP does not broach the possibility that an alien persona may acquire a mutation unique from her species.
An alien mutation is called an *evolutation*. 
To get the deets on alien evolutations, jump to xref:aliens:evolutations.adoc[Evolutations].

== Robots (Malfunctations)
Robots do not have DNA to mutate, but robots can still have mutation effects.
Robot mutations represent unique malfunctions of existing systems.
The mutation effect is novel to the collection of peripherals and malfunction.
On occasion, a robot will generate a weapon or device that mimics a mutation.
There is no specific check for robot mutations, but they can randomly acquire mutation like functions during their fabrication. 
A robot mutation is called a *malfunctation*.
