= Persona Creation

[quote]
____
the aspect of someone's character that is presented to or perceived by others.
____

The persona is a fictional representation that the player uses to participate in the EXP world. 
In other games, a persona is called a character, an avatar, or an actor.
The persona is the player's tool, and the player gives the persona life.
The player manipulates the fictional world through her persona.
Every player in the game has a persona.
The referee will have many personas; they are called referee personas.
Some referee personas will be important; others will be insignificant.

EXP is a tabletop roleplaying game, and the players gather together in the flesh. 
A group of personas is called an expedition.
The referee, who is just another player, gives puzzles that the expedition must solve. 
The persona allows us to experience anything through the power of our imagination.

== Assumptions
It is assumed that one has at least a basic understanding of the following elements to create a persona.
If any of the assumptions don't ring a bell hit the included link.
To make a persona you do not need to know about combat or uncombat rules at all. 

.*Assumptions: I know ...*
. https://en.wikipedia.org/wiki/Dice[How to roll dice,window=_blank]
. xref:referee_personas:a_introduction.adoc[Player vs Referee Persona,window=_blank]
. xref:attributes:a_introduction.adoc[Attributes,window=_blank]
. xref:roll_playing_system:families.adoc[Families,window=_blank]
. xref:roll_playing_system:mutating.adoc[Mutations,window=_blank]
. xref:vocations:a_introduction.adoc[Vocations,window=_blank]
. xref:hardware:a_introduction.adoc[Toys,window=_blank]

NOTE: *If this seems too much you may prefer the xref:role_playing_system:a_introduction.adoc[Role Playing System,window=_blank]*

== Steps 
Below is a checklist of the basic elements for creating a persona in EXP. 
The more complex persona types like alien and robot have many steps not listed below.
It is recommended that players familiarize themselves with the system before jumping into alien and robots personas.

.*Steps for Persona Creation*
* [ ] xref:appendices:printables.adoc#_persona_record_sheets[Persona Record Sheet,window=_blank]
* [ ] Pick a family
** xref:anthros:a_introduction.adoc[Anthro,window=_blank] - most familiar, easiest to play
** [ ] Attributes
** [ ] Genus
** [ ] Mutations
** [ ] Vocation
** xref:aliens:a_introduction.adoc[Alien,window=_blank] - less familiar, harder to play
** [ ] Attributes
** [ ] Shape
** [ ] Mutations
** [ ] Biology
** [ ] Society
** xref:robots:a_introduction.adoc[Robots,window=_blank] - totally unfamiliar, hardest to play
** [ ] Attributes
** [ ] Series
** [ ] Systems
* [ ] xref:hardware:startifacts.adoc[Startifacts,window=_blank]
* [ ] xref:referee_personas:rp_story_cues.adoc[Story Cues,window=_blank]
* *Have fun!*







