= Weapon Skills

[quote]
____
*To develop the skill to kill takes will.*
____

Weapon skills play an important part in keeping personas alive.
The weapon skills discussed her are anthrocentric and refer to weapons like swords, bows and guns.
A weapon skill is an informal skill in EXP. 
The persona does not need to go to weapon night school to gain a skill. 
A persona will be able to recognize a gun or a sword, but using them proficiently is a different matter.
Having a weapon skill allows the persona to 'use' a weapon properly, but not expertly. 
The main advantage of a weapon skill is that it allows a persona the player can add the Skilled Bonus to Attack Rolls.
If the persona lacks a specific weapon skill they can be just as deadly, but the player can only add the Raw Bonus to Attack Rolls. 

Players should choose their persona's weapon skills carefully. 
For example, being skilled with a lazer pistol will be fun until the batteries run out.
In a leather and dust milieu, a crossbow skill may have been a better choice.
Players can hold back their weapon skills choices until the right weapon comes along.

NOTE: In the past weapon skills were referred to as proficiencies.

== Initial Weapon Skills
The initial weapon skills are determined by the persona's vocation.
Each vocation, except Nothings, gets to choose one weapon skill from each Attack Type. 
It is common for players to hold back choosing their weapon skills until they come across a weapon they like.
For example, a mechanic persona may have no Strike Attack skills until she finds a compucrafted hammer.
So the player uses the Raw Bonus for Strike Attacks until adding the hammer skill. 
Once the persona has hammer skill the player will add the Skilled Bonus to her Attack Roll when using a hammer.
In austere campaigns players will use their Raw Bonus in combat until they find a weapon that they want to skill in.

== Weapon Skill Limitations
The weapon skill is specific, and limited to the Attack Type.
Skill in dagger does not cross over to skill in a sword, or skill in a throwing dagger.
The choice of weapon skills should be limited by the milieu. 
If the campaign has a low tech austere environment, choosing a flotto lazer pistol skill would go against the plot.
If the persona's culture has not developed crossbows, then choosing crossbow skill would not go against the milieu.
With freedom to choose comes responsibility. 

Weapon skills refer to personal weapons and not weapons like artillery, or missiles.

== Weapon Skill Advancement
As the personas progress in experience levels they can earn additional weapon skills.
Players may choose to add new weapons, or increase their skill level in a particular weapon. 
A Nomad gets an additional Strike Attack weapon skill at level 3. 
The player could add dagger skill in addition to her sword skill. 
This would allow her persona to use her Skilled Bonus for both daggers and swords. 
However she could also choose to increase her sword skill to sword 2. 
Combat vocations with high experience levels can have skill sets that resemble: pistol-2, sword-3, and bow

Increasing weapon skill levels increases the persona's proficiency with that specific weapon.
Weapon skill level 1 (ie, hammer-1) allows the player to use the Skilled Bonus when making an Attack Roll.
Higher weapon skill levels like pistol-3 or sword-2 help the persona as well.
When doing a task with a weapon, like making a trick shot or attempting a quick reload the increased level will assist the task roll like any other skill.
There is also a bonus of +42 on the Attack Roll per level above 1.
So a persona with pistol-3 would get +84 added to her Attack Roll based on pure skill. 
At some tables this skill bonus can increase the persona's Max Roll. 
This allows a master archer the ability to hit above their Max Roll. 

include::ROOT:partial$CH09_Table_Attack_Proficiencies.adoc[]

At 1st level a player with a Nomad persona can choose 1 Strike, 1 Fling, and 1 Shoot weapon skill. 
The player chooses dagger-1, bow-1 and pistol-1 skills.

At 3rd level the player can add 1 Shoot Attack skill.
The player could increase to pistol-2 or broaden her weapon skills by adding rifle-1.
The expedition lives near a rifle range with lax security, so the player chooses rifle-1.
Her weapon skills are now dagger-1, bow-1, pistol-1 and rifle-1.

At 4th level the player can add 1 Strike Attack skill.
The player could increase to dagger-2 or broaden her weapon skills by adding sword-1.
The local government has placed a tax on stabbing devices longer than 30 cms, so the player chooses dagger-2
Her weapon skills are now dagger-2, bow-1, pistol-1 and rifle-1.

At 5th level the player can add 1 Fling Attack skill.
The player could increase to bow-2 or broaden her weapon skills by adding thrown dagger-1.
The player has found some compucrafted daggers that are great for stabbin' and throwin', so the player chooses thrown dagger-1
Her weapon skills are now dagger-2, bow-1, throw dagger-1, pistol-1 and rifle-1.

=== Aliens
Aliens are automatically skilled with their natural attacks and use Skilled Bonus for the Attack Type.
Aliens that are not tool users (flora or fauna) cannot comprehend weapons and do not use them.
Aliens cannot advance the skill level of their natural attacks. 
There is a built in Force Bonus improvement as the alien increases in experience levels. 

Tool using aliens will require a vocation to use tech weapons.
Tech weapons would include mundane terran weapons like swords and bows.
Weapon using aliens must generate an attribute based Attack Table to use weapons. 

=== Robots
A robot is only Skilled with attacks baked-in during fabrication.
Robots use their Raw Bonus for attacks that are malfunctioning peripherals. 
Most robot attacks are malfunctioning peripherals. 
On a robot Attack Table the Raw Bonus is zero.
There is a to be decided edge case of whether a robot that has a vocation can use an attribute Attack Table.

=== Vocation Quirks 
The following edge cases are discusse in the appropriate vocations, but are listed here for convenience.

Knites:: 
Knites are alway skilled with their energy sword.
They are not skilled with any energy sword, but only the bespoke one related to their calling.
The personal energy sword of a Knite does not count as a weapon skill.
So a first level knite with a bespoke energy sword would still have access to 3 first level weapon skills.
The player can choose to increase her bespoke energy sword skill with advancements. 

Mercenaries:: 
Mercenaries are efficient with anything that is a personal weapon.
This is a built into their starting gift called weapon proficiency. 
If the weapon is a high tech artifact that does not look like a weapon the persona must identify it as a weapon first.
Mercenaries still get weapon skills and increase skill levels to help with tasks and improve Attack Rolls.  

Nothings:: 
Nothings are only skilled with one weapon and one weapon only.
Choose wisely.

// fix this needs to be in combat rules when created