= Wetware


Arrrrgh there be mutations. 

But should there be mutations.
Maybe there should be skills 

* iii-hardware
* v-software
* vi-bioware
** anthros mutations unique
** aliens abilities reproducible
** robots malfunctions unique

* bioware
** physical - physical space
** mental - think space

//explanation of defects
//not superpowers
//have balance

Surviving mutations in our early biology is a very rare occurrence indeed.
In the mundane world, most mutations are lethal changes in cells which can produce cancers or arrest the development of the organism altogether.
However, in the radioactive, poisoned science fantasy world of EXP, mutations are 100000 times more frequent and infinitely stranger.

The mutations that invade the alleles of personas are for more exotic than any which exist today.
Commonly, mutations are caused by the flip or omission of a section in an organism's DNA -- usually rendering the organism unnoticeably different or dead.
None of the EXP's mutations are so realistic (read boring).
Seemingly cancerous lumps and bumps can develop into complex organ systems that will fulfill some unimaginable purpose.
Such mutations are described in http://expgame.com/?page_id=364[Chapter 58: Mental Mutations] and http://expgame.com/?page_id=366[Chapter 59: Physical Mutations].
Even though the mutations represent biological systems as complex as a complete organism, they are quite easy to play in the game.

For historical purposes, the mutations have arisen from the effects of radiation, poisons, or ultra rare gene combinations.
The acquisition of the mutations can generally be accredited to the parents (or the closing tank) of the mutated offspring.
Since we are dealing with the world of science fantasy, it is not impossible for mutations to have arisen from post-gamete cells.

It is impossible for a referee to scientifically explain a mental mutation like ESP (#14) to a geneticist but the pseudo-scientific justification should be reasonably plausible.
The referee must be prepared to black box the biological aspects of her campaign as well as the technological ones.
Lastly, not all mutations are beneficial to the persona.
Many mutations are simply defects and the player is going to have to deal with the burden on her persona continually.

== Robots and Aliens

The Mental and Physical Mutation tables are not used solely to determine the genetic anomalies of mutant players.
Aliens, robots, and computers can be referred to these tables to determine extra special abilities that may not actually be considered mutations.
Rolls on the mutation lists can be made for randomly generated aliens to determine the natural abilities of an entire alien family.
These alien mutations may not be mutations at all but evolved parts of their physiology.
Robot personas can use the mutation chapters to determine effects of special peripherals.
Such robot peripherals are actually mechanical devices that imitate the mutation rolled or are regular peripherals running amok but they are not necessarily biological anomalies.
Only anthropomorph personas use the mutation chapters strictly for mutations.

== Acquiring Mutations

The susceptibility of personas to mutation is affected partly by family and partly by choice.
The families have varying frequencies of mutation that are based both on elements of popular fiction and the ability of the species to adapt to mutation.
The chance of mutation can be determined on the Mutation Frequency table.
The players also have some input as to whether they mutate or not.
If the player desires to mutate, she can double her persona's chance of mutation.
It is assumed that the parents of this persona were exposed to high levels of mutagens or the persona herself was exposed to situations that increased the chance of mutations (e.g.
she went skinny dipping in the glowing creek).

== Generating Mutations

All players rolling up a persona must check against the Mutation Frequency table to see if they have mutated or not.
The player checks against the frequency of both mental and physical mutations as listed by her persona family.

A Humanoid persona would have an 18% chance of mental mutations and a 23% chance of physical mutations.
If she were to roll less than 23 on deci-dice when checking for physical mutations, she would be due for 1-4 physical mutations.
The physical mutations are determined in Chapter 59: Physical Mutations.
In that chapter, the exact mutation is determined and all important information about it is recorded.
The same procedure is repeated for mental mutations.

Defects do not count as mutations.
So if a persona is supposed to get three physical mutations and the first one is No Resistance to Disease (physical mutation #3`), she would have three more mutations to be rolled.
Mutations that are considered defects are listed as such in their respective chapters.




== Mutation Parameters

Each mutation, whether mental or physical, has certain properties that describe what it is and how it affects play.
The parameters of each mutation are explained in the following paragraphs.
Not only should the basic feature of a mutation be recorded but the mutation number and the page number where the mutation can be found.

*Name*: The name of a mutation can give an inkling to what the mutation does or simply describe it outright.
The title can be deceptive so the mutation should be read in detail and the mutation number recorded on the persona record sheet.

*Range*: The range of a mutation indicates how far away the effects of the mutation can be delivered to a target.
Any exception to this meaning of mutation range will be specified in the mutation.
Many mutations can affect targets hexes away;
others require contact;
and some have a radius of effect.
Ranges are not devoted solely to offensive mutations and even defensive mutations may be critically affected by range limits.

The intensity of a mutation cannot be regulated and neither can its area of effect.
Only a single target mutation can be adjusted for different ranges from the persona.
Mutations that have areas of effect will indiscriminately affect all targets in this area of effect.

Nothing can stop a mutation which travels directly from one mind to another.
E.S.P., gyrokinesis, and telekinesis can pass through any barrier if the mutant has positive proof that the target exists.
Those mutations which manipulate the environment to attack a target such as mind blast or launch-able quills are subject to all terrain effects.

*Distance*: The most common is the ranged mutation.
Ranged mutations can be directed at any target within range of the mutant.
The range is determined by the MSTR and EXPS level of the attacker.
For example, a mutation may have a range of one hex @ MSTR.
This means one hex per point of mental strength and, with a 12 MSTR, a mutant could use the mutation 12 hexes away.
There are variations to this common range format.
Two hexes per MSTR would yield a 24 hex range with a 12 MSTR.
One hex per four MSTR would yield a three hex range with a 12 MSTR.
If the range includes MSTR and experience level then the two are added.
A fourth level persona with a 12 MSTR would have a 16 hex range with a mutation that was listed as one hex per (MSTR + level).

*Area of Effect*: Radius ranges are spherical and use the location hex of the persona for the centre.
Thus a mutation with a ten hex radius of effect would contain all targets within ten hexes including above and below the mutant.
The area of effect would include everything in the 20 hex diameter sphere.

*Touch*: Touch mutations are self explanatory.
The mutant must touch the target to inflict the effects of the mutation whether benevolent or not.
The touch must be hand, paw or claw to skin, fur or scales.
Some touch mutations can be conducted through material that would be considered conductive, like metal.
Some touch mutations may still be effective if derma to derma contact cannot be made.
They may be mutations with very short ranges, several millimetres, and a successful to hit roll may be all that is needed to get within range.

*Duration*: The duration of a mutation almost always refers to the length of time that the mutation effects last.
If the mutant has telekinetic flight, she can stay aloft for the duration of the mutation.
Mutations usually require complete concentration on the part of the mutant.
If a mutation obviously does not require complete concentration on the part of the mutant then the concentration need not be maintained.
Mutations that are always in constant use do not require a significant portion of the mutant's mental or physical resources.

Mutations usually last so many units per point of MSTR and they may also be affected by the persona's experience level.
If a mutation has a duration of one until per MSTR, then the mutant can make the mutation last 12 units if she has a 12 MSTR.
Other variations of duration exist and they all function identically to the range variations discussed earlier, except that units replace hexes.
Mutations with random durations are determined each time the mutation is employed.
Such mutations indicate that the mutant has set in motion physical effects which she has no control over.

Until Saves: If the duration is "`until saves`", the mutant may continue the attack until the victim saves or is dead.

Permanent: When the duration says "`permanent`", it indicates that the effects won't dissipate on their own accord.
For instance, permanent healing of HPS means that they will not disappear after a certain number of units but it does not mean that the mutant has a cache of indestructible HPS.

Constant: Most mutations can be stopped whenever the mutant sees fit, except those mutations that have a "`constant`" duration or an "`until dead`" duration.
These mutations will function until the mutant is dead or has the mutation excised.

*Frequency*: The frequency of the mutation indicates how often it can be used during a daily cycle of the mutant.
The frequency assumes a 24 hour day (see Chapter 12: Time and Movement) where the mutant sleeps around eight hours each day.
If the mutant is in a situation where there is no planetary rotation or one where there is no 24 hour cycle, a complete rest (eight hours`' sleep) will be equivalent to the completion of a daily cycle.

Most mutations can be used several times a day depending on the MSTR and level of the mutant.
The more powerful the mutation, the less frequently it can be used each day.
If the frequency of a mutation is one per four MSTR, a persona with a 12 MSTR could employ it three times each day and would have to rest eight hours before using it again.
For this type of mutation, rest for the brain is essential.
Unless otherwise stated, a mutation can be used at least once a day.
This includes mutations which have very low frequencies (e.g.
one per 13 MSTR).
This mutation could be used once a day even by a persona with a MSTR of six.

Mutations which can be used more frequently are labelled "`as needed`" and just as the title states, the mutant can use such a mutation as it is needed.
"`Constant`" mutations are usually defects and they constantly project their effects regardless of what the mutant is doing.
Constant mutations always function whether the mutant is asleep or awake.

Mutations cannot be stored.
A mutant cannot use a mutation more often one day than the next because she saved some uses from the previous day.
The mutant may use the mutation no more than the frequency states and each use is cumulative until she rests.
Mutations cannot be compounded to double an effect.
The mutant can only use one mutation at a time unless one of the mutations has a "`constant`" or "`as needed`" frequency.

The mutant has used a mutation whenever the effects start.
Even if the target saves and the mutation has no effect, the mutation has been used.
If the mutant voluntarily stops the mutation then it has been used.
If the mutant switches from one target to another, this will usually indicate another use.

*General Bonus*: The general bonus listing of the mutation could contain several arcane bits of information that are related to the use of the mutation in unexpected circumstances.
If the mutation is particularly dangerous, then there may be a combat ration (CR) adjustment listed (see Chapter 11: Referee Personas).
The mutation may indicate a bonus for particular PT rolls, attribute rolls or negotiation rolls.
Any simple affect that the mutation has on the dice rolling of the persona should be included beside the general bonus listing.

== Saves

Whenever a persona is subject to a psionic attack, she may save versus a psionic attack.
If a persona's body is threatened by poisons, she may save versus poison.
Saves represent the struggle of the body against intrusions of any sort.
Saves are detailed in Chapter 16: Special Rolls.
A successful save will almost always negate an attack.
If the mutation still has effects when the target saves, it will be stated in the description of the mutation.

Often inorganic objects will be subject to mutation attacks.
When artifacts are about to be controlled by some mutation, they will have an effective MSTR of zero.
If inorganic artifacts are allowed some form of defence, this will be because of weaknesses in the mutation and not strengths in the artifact.
Inorganic objects that are given mental defence will get an effective MSTR of 0 to 9 rolled on a d10.
Objects being held by a persona will have a MSTR equal to the persona when saving.

== General Queries

In general, there are many questions which will arise when mutations are introduced into play.
Some of the more obvious problems are included here but many others are certain to arise during the heat of play.
When this occurs, the referee is expected to ad-lib and the complications covered here should give her a decent framework with which to improvise.

Using Mutations: A persona must be conscious for a mutation to be used.
Unless a contradiction to this is stated in the description of the mutation, this rule will stand.
Like all rules in EXP, there are exceptions.
A mutation with a constant frequency will be functioning whether mutant wants it to or not.
Any degree of consciousness is sufficient for the mutant to use her mutation.
Mutations may still be activated even if she is stunned, dying, nauseous, falling or worse.

Restraint: Just because the mutant can use her mutation, doesn't mean that it will work.
Physical restraint can render physical mutations useless;
whereas complex interference patterns can deter mental mutations.

Detecting Mutations: The detection of a mutation attack is virtually impossible unless the attack has some obvious physical characteristics.
Even if the target saves, the attack may not be detected.
Saves versus psionic attack involve little or no mental thought and the brain acts subconsciously to defend against the intrusion.

== New Mutations

New mutations can be acquired by the personas under the rarest of circumstances during the process of a campaign.
Most mutants will never have any more than those generated through pharmaceuticals, exposure to mutagenic compounds or by even more devious methods thought up by the referee.

*Radiation and Mutations*: Each time a persona takes damage from a radiation attack there is a chance that she will acquire a new mutation.
Radiation damage is discussed in detail in Chapter 16: Special Rolls.
A persona that fails to save versus radiation poisoning will take a d4 in damage per level of radiation intensity.
The referee can check against total radiation damage with either a deci-dice or a kilodice roll to determine if the exposure has mutagenic potential.
If it does then the player can roll against her persona family's chance of mutation and, if the mutation is indicated, then she will refer to the appropriate chapters.

If a canine persona were exposed to 38 HPS of radiation damage, the referee may roll percentile dice to determine if the exposure was mutagenic or not.
A roll of 38 or less will indicate that the radiation will have a chance to mutate the personal whether she wants to or not.
The persona is a canine so the player has to refer to Table 7.1 to determine if her persona mutates or not.
There is an 18 percent chance of acquiring a new mental mutation and a 22 percent chance of acquiring a new physical mutation.
If a new mutation is indicated then the mutant will only acquire one additional mutation of either type, regardless of whether it is a defect or not.
