= Artificial Intelligence

Artificially intelligent (AI) computers can talk, carry out complex calculations and intake data all at the same time.
The artificial intelligence computers are the thinkers of the inorganic world.
The machines may run on positronic brains, nanocircuitry, or organic computation systems.


== EXP Mythos

What ever the referee chooses, the computers all have one thing in common: they operate on a Multi-tasking Open Memory system.
The computer system has earned the nickname MOM.
This acronym reflects the maternal nature of the computer which is very protective of all anthropomorphs.
The title of MOM does not indicate how the referee should run her AI computers.
Maternal doesn't indicate that the computer has to masculine or feminine, but it does indicate that the computer is programmed to protect and assist its anthropomorph charges.
Evil and manipulative MOM computers do exist.
They been altered by a program system called Safeguard Terminology Evasive Programming (STEP).
Evil AI computers are commonly called STEP MOM computers.

== Distribution

include::ROOT:partial$CH48_Table_AI_Type.adoc[]

== Power Level
There are 6 levels of AI computers, and they all incorporate the MOM series title.
The lowest level is a MOM computer, the MOM is a basketball sized sphere that has a wate of 8 kg.
All MOM series computers must have a power source to function.
The next computer levels are the Grand MOM (GMOM) and then Great Grand MOM (G2MOM), and so on.
The highest known AI computer level is a Great Great Great Great Grand MOM (Matriarch).
Each progressive level of MOM computer is more powerful than the preceding one, is smarter, and can handle additional AI peripherals.

The INT level of a MOM computer will be 20 plus 1-2 (1d2) per G in it's title.
So a G3MOM could have an INT from 23 to 26.
A Matriarch (G5MOM) could have an INT between 25 and 30.
Woah!
Smart.

include::ROOT:partial$CH48_Table_Artificial_Intelligence_Level_of_the_Multitasking_Open_Memory_System.adoc[]


== Programming
To begin programming a MOM series computer is 1DD per point of INT maneuver.
So a Great Grand MOM AI computer with an INT of 22 would be a 22DD Performance Table maneuver.
To program a Matriarch AI computer (G5MOM) would require a research team.
// aka ask a question

== Personality
MOM series AI computers are incredibly complex, and personalities are likely to appear through all the programming.
MOM AI computers quickly become referee personas as they are capable of chatting, chastising and maybe even being crazy or evil.

include::ROOT:partial$CH11_Table_Introverted_Personality_Trait.adoc[]


== Vocations
Yup.
Intellectual side.

include::ROOT:partial$CH48_Table_Vocation_Computers.adoc[]

== Peripherals
Peripherals are sub AIs that are controlled by the MOM computer and offer extremely good advice in their area of expertise.
These peripherals allow the computer to become a pedantic expert in some finer point of the humanoid world.
The AI computer will have one roll on Table 48.11: AI Peripherals per G that the MOM AI computer has.
So a MOM gets no peripherals, a GMOM gets 1 peripheral, a G4MOM gets 4.
Each peripheral has a wate of 2 to 16 kg, and a value of 750000.
A well equipped MOM computer could have a wate of several hundred kilograms, and spout exacting information about any number of topics.

include::ROOT:partial$CH48_Table_AI_Computer_Peripherals.adoc[]

