= Attributes

A persona's attributes are its natural given abilities.
The attributes reflect things like strength and Intelligence.
Dice determine the value of each attribute.
Attribute values are the framework that guides the rest of the persona generation.
Until now, the persona has been nothing more than a flicker of the player's imagination.
The attributes are the first steps toward the creation of a persona.

include::attributes:partial$attributes_of_attributes.adoc[]

== Attribute Scores
Each attribute is generated by rolling dice.
The type and amount of dice the player uses depend on the persona's family.
The higher the value of the attribute, the better the attribute.
A persona with a fifteen Strength is much stronger than a persona with an eight Strength.

The values of the attributes are equivalent between the families. 
Anthro, alien and robot attributes are roughly the same. 
A 9 Charisma is a 9 Charisma for a robot, alien or anthro. 
There are differences in how each family's attributes interact with the world. 
A ten Dexterity generates different movement rates for robots, aliens and anthros. 

A persona's attribute values determine both her species and her vocation.
Ursidae are strong and require Strength.
Mechanics are smart and require high Intelligence. 
A combot will be strong and hardy. 

NOTE: The anthro is the most common player persona type.

== Anthros 
A player generating an anthro persona creates most of her attributes by rolling three six-sided dice (3d6) and adding them up.
Using 3d6 makes for a nice organic curve.
An average attribute score is nine.
The extremely high and low (18 and 3) attribute scores are rare.
Anthros tend to have attributes between 3 and 18.

== Aliens
A player generating an alien persona creates most of her attributes using 5d6 and subtracting four from the roll. 
Rolling 6d6 makes for a nice organic curve.
The average attribute roll is twelve. 
In general, aliens will be stronger and smarter than their organic relatives, the anthros. 
However, aliens can have attribute values as low as one.

== Robots
A player generating a robot persona uses a mix of dice rolls.
Robots have four prime attributes where the player rolls 1d4. 
These prime attributes determine the robot type and, eventually, the persona's attribute scores.
Robots are complicated to play and complex to fabricate.
Robot attribute scores can range between 1 and 29. 
