= Hit Points (HPS)

:art: hitpoints.png
:width: 
:snark: How much damage can one take?
:artist: Warren Oddson
:date: 1990
:license: CC BY-SA 4.0
:description: Drawing of chest with bullet scars.

include::ROOT:partial$articulate.adoc[]

Hit points reflect the persona's ability to withstand physical damage.
Hit points are a composition of structural integrity, force distribution, resilience and luck.
The more hit points a persona has, the more physical injury the persona can endure.
When a persona runs out of hit points, they go unconscious and quickly die.

NOTE: Hit Points are the currency of combat.

Anthro hit points are a combination of connective tissue strength, organ padding, bone strength, coagulation and luck.
Alien hit points include all the elements of anthro hit points plus stronger special hides, unique fluid, and luck.
Robot hit points have inorganic equivalents like tensile strength, alloy casings, redundancies, power distribution, and luck.

Hit points are a unique attribute.
Unlike all other attributes, hit points are very dynamic.
A persona's hit points can vary wildly everyday.
A persona could lose hit points by getting injured.
She could immediately regain those lost hit points with a healing pharma.
She can gradually regain lost hit points as her body repairs itself.
No other attribute dances around like this.

To keep track of this attribute, it has two parts. 
These two parts are the constant hit points maximum (HPM), and the dynamic hit points (HPS). 
They are often referred to collectively as hit points.

A hit point is not like an erg, or some other unit of energy.
However, a hit point has a constant value.
One hit point of damage reduces the hit point total of the persona.
A hit point is a hit point is a hit point.
Anthros, aliens, robots, and inanimate objects all lose hit points when damaged.

== Hit Points Maximum (HPM)
A persona's hit points maximum is determined once.
The player calculates her persona's hit point maximum during persona generation.
Each family calculates its hit points maximum differently.

The hit points max (HPM) is a fixed element. 
A persona with 42 HPM will always have a hit points max of 42. 
A persona cannot heal beyond her hit points max.
For example, a healing pharma can restore a persona to 42 HPS but not beyond. 
Hit points max is not completely permanent. 
Age, robot decay, or other nastiness can reduce the Hit Points Maximum.
There are science fiction interventions that can increase a persona's HPM

== Hit Points (HPS)
HPS is the number of hit points the persona has at this instant.
When uninjured, the hit points (HPS) equals the hit points max (HPM).
The persona's HPS Total decreases every time she is injured. 
The HPS attribute is like a fuel gauge for damage.
The lower the fuel gauge, the less damage the persona can withstand. 
If this damage gauge gets to zero, dramatic things happen to the persona.
These dramatic things include unconsciousness and death.

== Hit Points and Families
Robots, aliens and anthros all deduct hit points in the same fashion.
However, the impact of a hit point varies between the families.
Following are some brief examples. 

.*Points About Hit Points*
* Anthros can be stunned if they lose too many hit points at once. 
** Aliens and robots cannot be stunned or knocked out by a bolus of damage.
* Anthros go unconscious and start dying at zero hit points. 
** Aliens are dead at zero hit points. 
** Robots break something and decay a bit at zero hit points. 
* Spontaneous HPS recovery
** Organics (aliens and anthros) heal hit points through rest. 
** Robots do not heal hit points, and the risk of repairs usually exceed benefits. 


include::attributes:partial$hit_point_ranges.adoc[]

