= Mind (MND)

:art: mental_strength.png
:width:
:snark: Where minds meet.
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0
:description: Two stern sets of eyes staring at each other.

include::ROOT:partial$articulate.adoc[]

Mind represents the persona's will power, psionic ability, and luck.
This attribute is a Sciency Fiction one with no physiologic connection to our mundane terra just yet.
A persona with high Mind Attribute has excellent will power and resistance to influence.
Mind is the attribute powering psionic mutations and psionic events.
Strength (from muscles and levers) represents the amount of force a persona can generate in the physical space.
Mind represents the amount of force one can generate in the think space.
For more information about these faux spaces jump to xref:appendices:generic_mythos.adoc[Generic Mythos,window=_blank].

The Mind Attribute has family-based peculiarities that other attributes do not have.
Inorganic personas (robots) have a Mind of zero and are unharmed by this.
Robots do not connect to the think space, will power is not a concept, and cyber space has no use for luck.
Organic personas die if their Mind drops to zero. 
The life force of alien and anthro personas evaporates if they lose their Mind.
In rare instances, an alien may evolve with zero Mind.
These alien species are an edge case and have no connection to the think space.

// brand new table for version 6.0
.*Mind by Family*
[width="75%",cols="<,^,^,^"]

|===

|
s|Anthro
s|Alien
s|Robot


s|Range
|4-16
|1-26
|0

s|Die Roll
|4d4
|5d6-4
|---

|
s|Anthro
s|Alien
s|Robot

4+<|Creating a new persona with a 0 MND is not fatal.
|===



