= Social Standing (SOC)

:art: time_crime.png
:width: 250px
:snark: Honey attracts more flies.
:artist: Kelly Freas
:date: 1955
:license: CC BY-SA 4.0
:description: Creepy man at desk with phone and cigarette.

include::ROOT:partial$articulate.adoc[]

Social Standing indicates where the persona fits into her social structure.
Social Standing is an odd attribute because it is more a cultural measure than a physiologic measure.
Social Standing indicates how high up the persona is within her societal structure.
A persona with a high social standing would know where to go and what to do within her culture. 
If a persona with a high social standing asked for help in a store, she would be more likely to get proper help.
If a persona with a low social standing were to ask the same question, she might not get useful information. 
Social Standing is a tool to assist decisions involving power, but it is mostly invisible and unconscious. 

NOTE: Social standing takes fourth place to roleplay, the referee's story and the campaign milieu.

How social standings work varies wildly between the families.
Anthro's social standing represents an invisible privilege within the persona's culture.
A high social standing may come with the trappings of wealth and power within the campaign's milieu.
On mundane terra, that would be fame and fortune. 
On post-apocalyptic terra, that would be food rations and clean water.
The persona's social standing does not make her a jerk or pathetic.
When two anthro personas of equal everything compete over some insignificant thing, the higher social standing will usually be triumphant.

Alien social standing could represent access to food, breeding or territory.
Alien social standing in an advanced tool-using culture may represent something more like the anthro social standing.

Robot social standing is a reach as their self-awareness lives in a computer malfunction.
Social standing for robots could reflect how their owners treat them, their security clearance, space in the recharging queue, or maintenance schedules.



// brand new table for version 6.0
.*Social Standing by Family*
[width="75%",cols="<,^,^,^"]

|===

|
s|Anthro
s|Alien
s|Robot

s|Range
|1-1000
|1-1000
|1-1000

s|Die Roll
|1d1000
|1d1000
|1d1000

|
s|Anthro
s|Alien
s|Robot
|===