= Strength (STR)

:art: physical_strength.png
:width: 250px
:snark: Chemistry and levers.
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a muscular arm giving a thumbs up.

include::ROOT:partial$articulate.adoc[]

Strength represents the force the persona can generate to get work done.
Strength is a combination of leverage, power and physique.
Strength determines how much the persona can lift or break using brute force.
Strength helps when kicking open doors, breaking bonds, or crushing beer bottles.

Strength is equivalent amongst all the families. 
Anthro and alien Strength arise from contracting fibres and boney levers.
Robot Strength employs hydraulics, servos, wires etc.
Organic and robotic Strength is equal on a point by point basis. 
So a robot, alien or anthro with nine Strength are equally strong.

// brand new table for version 6.0
.*Strength by Family*
[width="75%",cols="<,^,^,^"]
|===


|
s|Anthro
s|Alien
s|Robot


s|Range
|3-18
|1-31
|Prime 1-4

s|Die Roll
|3d6
|6d6-5
|1d4

|
s|Anthro
s|Alien
s|Robot
|===


