= Hardware

[quote]
____
*Technology is indistinguishable from magic as soon as the manual goes missing.*
____

. <<_introduction,Introduction>>
. <<_toy_type,Toy Type>>
. <<_support_equipment,Support Equipment>>
. <<_tech_level,Tech Level>>
. <<_toy_record,TOY Record>>
. <<_startifacts,Startifacts>>
. *Have fun!*

****
*Need some tech right now? Jump to * <<_toy_type,Toy Type>>.
****

== Introduction
EXP, The game of technologic chaos, is a sciency fiction role-playing game.
This section focuses on the technological part of the game.
The chaos of technology arises from the core canon that anything from anywhere can appear at any time.
Long lost civilizations, alien detritus, corporate misadventure, and electroevolution combine to create a potpourri of technological chaos.

:art: temple_trouble.png
:width: 350px
:snark: 
:artist: Rogers
:date: 1951
:license: CC BY-SA 4.0
:description: Drawing montage of oil derricks, atom symbol, gun and bow.

include::ROOT:partial$articulate.adoc[]

The chaos arises from the randomness of the system that generates technological objects in EXP.
The hardware section has sixteen equipment categories, and they are ready for random equipment generation. 
The hardware section also makes a decent reference catalogue for technomagical devices. 

The Technological Object Yield System (TOYS) is where the technological chaos begins.
The TOY System generates random artifacts.
These artifacts can vary from worthless junque to sun hopping starships.
The randomness is the root premise of The Game of Technological Chaos.

.*Technology Nomenclature*
TOYS or TOYs:: 
Technological Object Yield System. 
The TOY system is the ruleset for generating random tech.
The TOYS ruleset is the entire Hardware Section.

Toy::
Anything that the TOYS generates is a toy. 
A toy can be powerful or useless.
Most toys are somewhere in between.
An unidentified toy can be called an artifact.
An identified toy is often still called a toy.

Artifact:: 
An unidentified potentially technological device.
An artifact can be powerful or useless.
Most artifacts are somewhere in between.
Useless artifacts can be called mundane equipment.

Mundane Equipment:: 
Mundane equipment is the boring practical stuff of life.
Personas can usually purchase mundane equipment in a local shop.
Sometimes what was once an artifact is demoted to mundane equipment.

== Toy Type
Let the chaos begin.

The referee can make the plethora of 1d100 (decidie) rolls needed to generate an artifact.
The referee will often involve the players to make the decidie rolls. 
Hence the constant reference to the 'player' is rolling.
The referee usually secretly records the toy information to preserve the element of the unknown.

The player rolls on the Toy Category Table to determine the artifact category.
From this table, the referee jumps to the appropriate category and generates the specific toy type.
The player rolls 64 on the 1d100 indicating the Pharmaceutical category.
The referee jumps to pharmaceuticals and generates the specific pharma type.

include::ROOT:partial$CH41_Table_TOY_Category.adoc[]

== Support Equipment 
Support Equipment is stuff that is needed to run the equipment.
Support Equipment ranges from manuals to ammunition and from batteries to software.
Support Equipment is ineffective on its own but essential to another device.
Jump to xref:iv-software:CH55_Support.adoc[Support Equipment,window=_blank] for more details.

== Tech Level
Tech Level is a numerical measure of how well crafted an artifact is.
The higher the Tech Level (TL), the better the artifact. 
An advanced artifact does not automatically arise from an advanced civilization.
A culture may focus a disproportionate amount of energy on a particular device.

Higher tech level artifacts are more durable, lighter, more efficient, etc.
Tech level can also change the shape and appearance of an artifact.
A flotto laser rifle may look like a stick.
A psionic headband may look like a necklace.
Very high-tech items can appear to function like magical items. 

Low tech level items can be equally confusing to personas. 
A large building may represent a society's best calculator.
Compare a water pump of today from the waterwheel of yesteryear.

Jump to xref:iv-software:CH56_Tech_Level.adoc[Tech Levels,window=_blank] for more details.

include::ROOT:partial$CH56_Table_Assign_Tech_Level.adoc[]

== TOY Records
Artifacts in EXP are like snowflakes.
Each one appears different and functions differently.
If the device was worth generating, it is worth writing down.
Keeping artifact records results in quicker gameplay and fewer 'oops' moments.

.*Example Toy Record*
* *Owner*: Gilberne Freyte (canine) *Date*: 19/Oct/64 *Serial*: yrul2
* *Toy*: Gun, 16 full-auto lazer rifle (flotto) 
* *Wate*: 4.0kg *EXPS*: 760 *Value:*
* *Tech Level*: 19 (see below Adjustments)
* *Wate*: 0.8kg *EXPS*: 1120 *Value*: 85000 (adjusted to tech level)
* *Support Eq.*.: 3 x Liquid batteries.
* *Info*: Shoot, F; 120h 60; 3-30 MP; +50; Malfunction <30.
* *Desc*: dark blue pipe with button and dial setting

If the spirit of the unknown artifact is part of the milieu, the players will only know the description and wate of the equipment. 

=== Toy Story
The referee can use post factualization to explain the how and why of an artifact.
An artifact can also be a tool for explaining the culture from which it hails. 
Most artifacts will simply be equipment, but some artifacts will become part of the campaign itself.
Some artifacts have Intelligence and attitude.

== Startifacts
There is a legacy rule in EXP of newly minted personas starting the game with a few artifacts.
Starting artifacts are called startifacts.
Startifacts must match the referee's story and milieu.

Startifacts are usually secret.
Players get to roll their persona's startifacts, but the referee records the info with an alloy-clad poker face.

=== Startifact Number 
Players get *three* startifacts, maybe. 
Personas can end up with more or less than three items.

Random Junque and minimal Treasure do not count as startifacts.
In this case, the persona may get more than three items, although some are useless.
Spaceships, vehicles, robots and other powerful items stop startifact generation.
In this case, the persona may get less than three items because of the item's power.

=== Vocation Limits
Personas are not allowed to amass artifacts related to their vocation.
Vocation toy limits is a legacy rule within a legacy rule.
This rule prevents personas from being overpowered with startifacts.
It also encourages the expedition to work together from startup.
The player should stop generating startifacts according to the below table.
For example, a player rolling startifacts for her mercenary persona would stop once she generates a weapon.

include::ROOT:partial$CH41_Table_Vocation_TOYS.adoc[]