= Hardware

[quote]
____
*Technology is indistinguishable from magic as soon as the manual goes missing.*
____

EXP The game of technologic chaos is a sciency fiction role-playing game.
The technological chaos is a mix of technologies, and a mix of tech levels.
Long forgotten civilization, alien detritus, economic collapse, and apocalyptic devastation all have left layers of mysterious devices.
Amongst the rubble all imaginable technological coexists in potpourri of chaos.

*Jump directly to ->* <<_toy_system,Artifact Generation>>

EXP exercises the liberties of faux science and magical thinking to have fun.
This is the root of the sciency fiction milieu of EXP.
Referees and players must lever the magical power of the opaque black box.
An aptitude for rational fabrication and post factualization are essential tools.

Random technology can drastically alter the course of a campaign.
A life ray could lead to reckless personas.
A control baton may be useless until the overseers in powered armour show up for tithes.
Use the randomness as a tool to creatively explore the milieu and story.
The players have to roll with this randomness.
The referee should as well.
It is the Game of Technological Chaos after all.

A referee is free to tailor the hardware section to what best reflects her story.
This can easily be done by creating a few devices in advance and ignoring all the randomization harboured here.
Or you could just play https://en.wikipedia.org/wiki/Traveller_(role-playing_game)[Traveller] instead.

== What is TOYS?
The Technologic Object Yield System (TOYS) generates completely random artifacts.
These artifacts can vary from worthless junque to sun hopping starships.
Starting out with the TOYS leads to a completely random artifact.
The devices are generated from the Hardware section. 
EXP's rule system expects that artifacts are randomly generated.
It is the root premise of The Game of Technological Chaos.

NOTE: *TOYS creates toys = artifacts = tech = devices = equipment = fun stuff*

== Getting Artifacts
Personas can start with artifacts, find artifacts, or be rewarded with artifacts.
Newly created personas starting out with a few artifacts is a legacy rule of EXP.
The habit of starting equipment might even be a house rule from a homebrew. 

NOTE: *Artifacts generated during persona creation are called startifacts*

Once the campaign is underway personas will acquire technology in any way possible.
They may find devices in an ancient destroyed laboratory.
They may earn devices from combat or cunning stunts. 
They may be paid in artifacts for a job well done.

It is assumed that all artifacts are unidentified curious devices of unknown purpose.
The heavy ceramic piglet chained to a carabiner could be random junque, the key to a spaceship or stun weapon.

== Anthros
Anthros are tool users by definition and enjoy the full breadth of the TOYS.
The amount of startifacts (artifacts generated at start) are limited by vocation. 

== Aliens
Aliens are not tool users automatically. 
Non-tool user aliens have no startifacts and ignore tools of any format.
Aliens that have a vocation follow the full breadth of the TOYS.
The amount of startifacts (artifacts generated at start) are limited by vocation. 

== Robots
Robots do not have startifacts unless they have a vocation.
Robots that have a vocation follow the full breadth of the TOYS.
The amount of startifacts (artifacts generated at start) are limited by vocation. 
Robots that do not have a vocation generate peripherals that function as startifacts. 

== Toy Story
Players can get attached to their persona's toys.
Some artifacts can become essential parts of the campaign.
Some artifacts can be embedded with intelligence and attitude.
Not unlike referee personas artifacts can be cannon fodder or full referee personas.
The more important the artifact is, the more back story is needed.

== TOY System
The Technological Object Yield System (TOYS) is where the technological chaos begins.
The referee may choose specific artifacts from the vast array listed in Hardware.
Most technology will be randomly generated using 1d100 rolls.

:art: temple_trouble.jpg
:width: 250px
:snark: 
:artist: Rogers
:date: 1951
:license: CC BY-SA 4.0
:description: Drawing montage of oil derricks, atom symbol, gun and bow.

include::ROOT:partial$articulate.adoc[]

The player makes all the die rolls, and the referee tells her which dice to use.
Obviously, this does not apply to toys being rolled by the ref for a scenario.
The ref records all pertinent information in secret, not revealing or hinting anything about the toy (an alloy-clad poker face must be maintained at all times).

.*TOY System Checklist*
. <<_toy_type,Toy Type>>
. <<_specific_toy,Specific Toy>>
. <<_support_equipment,Support Equipment>>
. <<_tech_level,Tech Level>>
. <<_roll_again,Roll Again>>
. <<_toy_record,TOY Record>>
. *Have fun!*

Players get a maximum of three rolls on the TOY Type Table.
Personas can end up with a single item or more than three items.
Artifacts are limited by vocation. 
Random Junque and minimal treasure do not count as rolls.

== Toy Type
Let the chaos begin.
The player rolls on the Toy Type Table to determine the general artifact category.
From this table the referee jumps to the appropriate section and generates a the specific artifact.

A player that rolls 68 on the 1d100 will be getting a Pharmaceutical.
The referee jumps to that section and generates the drug.
Some players will have memorized the table to get a head start on Artifact Identification.
Not much can be done about this habit.

include::ROOT:partial$CH41_Table_TOY_Type.adoc[]

Recording the data on the artifact should start immediately.
The referee should secretly record the persona name, toy type and an ID.

== Specific Toy
This is were the rubber hits the road. 
Each hardware section has it's own introduction and quirks. 
While visiting the specific hardware section the referee secretly records the data.
How much data she records depends on the campaign milieu and rule system being used.
A jump list is included below.

.*TOY Sections*
* xref:CH43_Aerosols.adoc[Aerosols,window=_blank]
* xref:CH42_Armour.adoc[Armour,window=_blank]
** xref:CH42_Powered_Armour.adoc[Powered Armour,window=_blank]
* xref:CH45_Grenades.adoc[Area of Effect,window=_blank]
** xref:CH44_Bombs.adoc[Bombs,window=_blank]
* xref:CH46_Guns.adoc[Guns,window=_blank]
** xref:CH43_Artillery.adoc[Artillery,window=_blank]
* xref:CH48_Misc_Equip.adoc[Miscellaneous Equipment,window=_blank]
** xref:i-roll_playing_rules:CH11_Referee_Personas_Robot.adoc[Robot, window=_blank]
* xref:CH49_Misc_Weapons.adoc[Miscellaneous Weapon,window=_blank]
* xref:CH50_Pharmaceuticals.adoc[Pharmaceuticals,window=_blank]
* xref:CH51_Random_Junque.adoc[Random Junque,window=_blank]
* xref:CH53_Treasure.adoc[Treasure,window=_blank]
* xref:CH54_Vehicles.adoc[Vehicles,window=_blank]
** xref:CH52_Space_Vehicle.adoc[Space Vehicles,window=_blank]
* xref:CH47_Medical.adoc[Veterinary Equipment,window=_blank]

== Support Equipment 
Support Equipment is the stuff that is needed to run the equipment.
Support Equipment ranges from manuals, to ammunition, to batteries, to software.
Support Equipment is ineffective on its own, but essential to another device.

Support equipment is one of the more technical aspects of hardware.
Counting ammunition and units of battery use can quickly become tiresome.
Support Equipment is one of the first artifact elements to be dispensed with.

Jump to xref:iv-software:CH55_Support.adoc[Support Equipment,window=_blank] for more details.

== Tech Level
Tech Level is a numerical measure of how well crafted an artifact is.
The higher the Tech Level (TL) the better the artifact is. 
An advanced artifact does not automatically arise from an advanced civilization.
A culture may have focused disproportionate amount of energy on a particular device.
A higher tech level artifact will be more durable, lighter, more efficient, etc.
This can change the shape and appearance of an artifact.

Tech level is checked for each device that the persona has.
The campaign, milieu and story trump tech level randomness.

Jump to xref:iv-software:CH56_Tech_Level.adoc[Tech Levels,window=_blank] for more details.

include::ROOT:partial$CH56_Table_Assign_Tech_Level.adoc[]

A flotto laser rifle may look like a stick.
A psionic headband could be styled like a necklace.
Very high tech items appear magical in nature. 
The practise of faux science we keep them in the realm of sciency fiction.

Low tech level items can be equally confusing to personas. 
A large building may represent a society's best calculator.
Compare a water pump today from the windmill of yester year.

include::ROOT:partial$CH56_Table_Effect_of_Tech_Level_(TL)_on_Artifact.adoc[]

== Roll Again 
How many artifacts (Startifacts) is an appropriate number?
This question only applies to players generating artifacts for their new personas.
It was concluded, by consensus conference, at the last Ref's Cabal that 3 rolls is the magic number.
However, 3 rolls is very different from 3 toys.
The maximum number of useful artifacts is three.
A persona may get additional rolls if she has acquired useless artifacts. 

.*Yes to Roll Again*
. less than 3 startifacts.
. No vocation limitation.
. Random Junque does not count.
. Treasure does not count.

=== Vocation Limitation
Personas are not allowed to amass startifacts related to their vocation.
This rule prevents personas being overpowered with startifacts.
It also encourages the expedition to work together from start up.
Related vocation equipment is described below. 
For example, a mercenary persona would stop rolling once she gets a weapon.
If the weapon is generated on her first TOYS roll she stops with one startifact.
If the weapon is generated on her third TOYS roll she will have three startifacts.

include::ROOT:partial$CH41_Table_Vocation_TOYS.adoc[]

=== Random Junque
Random Junque does not count as a startifact roll.
It is not usually necessary to record random junque. 
Unless the players have been mislead think that the junque is something useful.
Random Junque is meant to be fun and useless.
This does not mean players won't find important uses for Random Junque.

=== Treasure
Treasure does not count as a startifact roll.
Small amounts of treasure need only record the eps value. 
Large amounts of treasure may require recording by the referee.
For example, valuable information, jewelry or real estate treasure may need recording.

== TOY Record
If the players and/or ref decide to ignore TOY recording procedures disaster is sure to follow.
First, much gaming time will be wasted leafing through the technology section--fun, but not gaming.
Second, players, yes and even refs, may play equipment incorrectly.
E.g., they may incorrectly assume they know what happens when an antimat pistol malfunctions.
But when they turn to the book, and the truth is revealed, they wail, "I would have", "If I had known", "that was my best persona", or "You didn't tell me that"".

For players that are too lazy to record their toy info, a penalty should be meted out each time the game must be interrupted with reference work.
An ExPs penalty may do the trick, increasing the artifact's chance of malfunction, or rendering the device functionally inoperative (broken) until its functional parameters are recorded.
Referee's Toy Records:The referee's book of toys should be as important, and as secret, as her campaign book of scenarios.
For every relevant piece of equipment the toy type, and toy name should be recorded as well as the wate, experience points, and value.
These details should also include an identifying description or serial number, functional information, and rulings that the ref has made about the device's previous function.

This record keeping is not as overwhelming a task as it might seem.
Remember that only relevant equipment need be recorded.
Relevant equipment includes: powerful devices;
devices unknown to the players;
devices not completely understood by the players;
and those devices which are complex to run.

.*Example Toy Record*
* *Owner*: Gilberne Freyte (canine) *Date*: 19/Oct/64 *Serial*: yrul2
* *Toy*: Gun, 16 full-auto lazer rifle (flotto) 
* *Wate*: 4.0kg *EXPS*: 760 *Value:*
* *Tech Level*: 19 (see below Adjustments)
* *Wate*: 0.8kg *EXPS*: 1120 *Value*: 85000 (adjusted to tech level)
* *Support Eq.*.: 3 x Liquid batteries.
* *Info*: Type C, F; 120h 60; 3-30 MP; +50; Malfunction <30.
* *Desc*: dark blue pipe with button and dial setting

== Player's Toy Records
The player's responsibilities are similar to the refs, except that only information relevant to role-playing is stored.
The item's wate must be deducted from the persona's weight allowance, the item's experience point value added to the player's ExPs total, and the value estimated at the time of sale.
The player is expected to remember they are carrying equipment, and players designated to carry toys are expected to remember how frail the equipment is.

The referee should keep track of the toys that the personas have.
She must have some sort of a permanent book (ed.
note this portion was written in 1990) in which she records the essential information about each toy that is generated in her campaign.
The reason that this is the referee's responsibility is because the referee is the constant in her campaign.
Personas will come and go, but their equipment will remain long after them.
Cryptically recorded persona record sheets will not relinquish useful information about artifacts all that often.
It is important that the referee record, in her own cryptic records, at least the essential information about each persona's toys.
Without book keeping, fission rifles turn into fusion rifles, grenades have variable area of effects, vehicles change accelerations, etc., etc.
In no way is this malicious on the part of anyone involved.
It is just simple fact that as data is transcribed from one page to another it always suffers a little bit of accidental alteration .

== Book Keeping and Game Play
If keeping track of mutations, weapons, computers, robots, and other stuff is starting to bog down the game simply decrease the amount of information that is important in the game.
Do you really need to know the battery type of a particular device?
Is the range of a detector so important that it should be included for every detector?
You will find that the amount of information kept track of will be the amount of information that is needed in the game.
Some players will be able to handle more information than others, and they will gravitate towards highly equipped personas.
Other players will keep their personas as simple and as uncluttered as possible.
Each player will rise to their level of .

A toy is any item which originates from the Technological Object Yield System--TOYS for short.
These items are predominantly equipment such as: sensors, grenades, batteries, computers, robots, bandages, pharmaceuticals, vehicles, and spare parts.
The toys range from the completely useless (items that do no more than go whiz and click), to the seemingly all powerful (warbots and androids).
The equipment is usually inanimate, and subject to the persona's whims, however it can also be slightly more sentient, giving its owner the odd disciplinary problem.
The words toy, artifact, equipment, item and tech are used interchangeably and mean the same thing: a technological device. 