= Armour

Armour protects the wearer from damage in combat and other harsh environments. 
Artifact armour can have technomagical qualities that vary from thermal protection to computerized, servo-aided joints.
Unless otherwise stated, the armour will include torso, limb, hand, foot, and head protection.
Armour does not include shields.

.*Armour Checklist*
. <<_armour_type,Armour Type>>
. <<_armour_parameters,Armour Parameters>>

== Armour Type

include::ROOT:partial$CH42_Table_Armour_Type.adoc[]

== Armour Types

=== Ablative Armour

[horizontal]
Armour Rating:: 625
Restrictiveness:: 3
Wate:: 2.5 (1.5kg)
EXPS:: 200
Value:: 590/kg (900)

Ablative armour negates lazer attacks.
When hit by a lazer, the ablative material vaporizes, producing an anti-lazer gas that dissipates the lazer bolt, keeping the attack from damaging the wearer.
When hit by a lazer, the wearer will take no damage because of the ablative armour.
This armour only works against lazers and does not affect energy attacks such as fission, fusion, or plasma.
The armour rating represents how well the armour is at deflecting all other attacks.
Since the armour vaporizes to disrupt lazers, it has a limited lifespan.
The armour will lose its ablative effect after disrupting 300-1000 (1d8+2 x 100) hit points of lazer damage.
If a lazer attack scores a hit, the damage score harms the armour, not the wearer.
Depleted ablative armour retains its AR of 625 but loses all special defences against lazers.

=== Ballistic Amour

[horizontal]
Armour Rating:: 625
Restrictiveness:: 3
Wate:: 2.9 (2kg)
EXPS:: 200
Value:: 590/kg (1200)

Ballistic armour negates ballistic attacks.
A crisscrossing mat of super-dense polymers absorbs high-velocity projectile damage (bullets, fragments, etc.).
Ballistic armour can absorb 100-600 (1d6 times 100) hit points of high velocity (Shoot attacks) damage.
Once the armour has sustained this maximum damage, it will be unable to negate projectile damage but maintains its AR of 625.
Ballistic cloth does not absorb damage from low-velocity attacks such as punches, maces, pipes, flails, etc.

=== Combat Armour 

[horizontal]
Armour Rating:: 725
Restrictiveness:: 2
Wate:: 3.0 (2kg)
EXPS:: 100
Value:: 1000/kg (2000)

Combat armour is typical futuristic, militaristic body protection designed for infantry dogmeat.
It is usually composed of such mundane materials as Kevlar weaves and ceramic plates.

=== Compucrafted Armour

[horizontal]
Armour Rating:: Plus 30-120 (3d4 times 10)
Restrictiveness:: 0-3 (1d4-1)
Wate:: Halved
EXPS:: 300 
Value:: See below

Compucrafted armour is computer-designed versions of mundane armour types.
They are designed to handle stress better, deflect blows better, be less restrictive, and have less wate.
Compucrafted armour uses special alloys, plastics, and ceramics, unlike the mundane equivalents.

include::ROOT:partial$CH42_Table_Compucrafted_Armour_Types.adoc[]

The armour rating (AR) increases by 30-120 (3d4 x 10) from the base armour rating.
Lighter and less cumbersome materials allow for more unrestricted body movement.
The lighter design decreases the armour's restrictiveness to between 0-3 (1d4-1).
The new restrictiveness cannot be higher than armour's previous restrictiveness.
Compucrafted armour reduces its wate by half and increases its value four times.
EXPS value is a flat 300 points for all types of compucrafted armour.

=== Concussion Armour

[horizontal]
Armour Rating:: 625
Restrictiveness:: 3
Wate:: 2.9 (2kg)
EXPS:: 200
Value:: 590/kg (1200)

Concussion armour absorbs concussive forces.
The protection looks like a bulky, pillowy onesie.
Each of the fluffy lumps is full of tiny resilient beads that increase the surface area that concussion force is absorbed over.
This design reduces crushing damage from explosions, falls, crashes, blunt weapons, squeezing attacks, etc.
Any of these damages types are reduced by 1/2 when wearing concussion armour.

=== Flexion Covering

[horizontal]
Armour Rating:: None
Restrictiveness:: Table
Wate:: Table
EXPS:: 333
Value:: Table

Flexion coverings increase protection against specific attacks.
They offer no protection against other attacks.
The various flexion coverings appear as beltless, pocket-less ponchos, parkas or trench coats.
The persona can wear Flexion over armour and equipment.
The flexion coverings can essentially withstand limitless damage.
Flexion should only do so after the persona has sustained 1000 hit points in damage.

include::ROOT:partial$CH42_Table_Flexion_Covering_Type.adoc[]

Concussion::
Concuflex reduces the chance of being injured by concussion attacks.
Shockwaves, crushing and gravity attacks are concussive attacks.
Concuflex increases the persona's armour rating (AR) by +150 against such attacks.
This covering appears as a bulky down parka.

Electro:: 
Electroflex reduces the chance of being injured by electrical attacks.
Electrical attacks include stun, lightning arcs and electrocution.
Electroflex increases the persona's armour rating (AR) by +150 against such attacks.
This covering appears like a black slicker with tendrils reaching the ground.

Energy:: 
Enerflex reduces the chance of being injured by energy attacks.
Energy weapons include fusion, fission and plasma attacks
Enerflex improves the persona's AR by +150 against energy attacks
This covering appears like a translucent shimmering raincoat.

Inertia::  
Inerflex reduces the chance of being injured by energy inertia attacks.
Classic inertia attacks are focused concussive damage like swords, punches, or inertia weapons.
Inerflex improves the persona's AR by +150 against inertia attacks.
This covering appears like a wet, flattened-down parka.

Lazer::  
Reflex reduces the chance of being injured by energy lazer attacks.
Lazer attacks include anything generated by a lazer, including lazer sights and lazer detectors.
Reflex improves the persona's AR by +150 against lazer attacks.
This covering appears like a matte trench coat with reflective flecks.

NOTE: *Previous EXP versions flexion coverings terminated in the letter  'c' instead of 'x'. The 'c' as a suffix was too similar to a derogatory term in the language of the main buyers.*

Projectile::  
Proflex reduces the chance of being injured by high-velocity projectile attacks.
Projectile attacks include bullets, crossbow bolts and launched quills.
Proflex improves the persona's AR by +150 against projectile attacks.
This covering appears like a poncho woven from tiny ballistic tiles.

Vibro:: 
Vibroflex reduces the chance of being damaged by vibro weapon attacks.
Vibro attacks include any vibro enhanced attack, sonic attacks other high-frequency damage.
Vibroflex improves the persona's AR by +150 against vibration attacks.
This covering appears like a rough weave of loose fibres.


=== Force Field 

[horizontal]
Armour Rating:: 0
Restrictiveness:: 0
Wate:: Table
EXPS:: 500
Value:: Table

Force field belts generate a nearly invisible defensive shield contoured to the wearer's body.
The electromagically generated field dissipates kinetic energy protecting the wearer.
The belt will absorb any attack that uses energy (kinetic, lazer, clubs).
The field raises instantly when an incoming attack is detected.
The force field belt absorbs any damage that the wearer would have taken.
This force field does not stop poison gas, radiation, kisses or psionic attacks.

Force field belts vary in the number of hit points they absorb.
Once the belt absorbs this damage, it shuts off.
The persona cannot use the force field belt before replacing the batteries.

include::ROOT:partial$CH42_Table_Force_Field_Belt_Strength.adoc[]

=== Helmet 

[horizontal]
Armour Rating:: +40
Restrictiveness:: 0
Wate:: Special
EXPS:: 50 + TOY  
Value:: 100 + TOY 

These are specialized helmets that offer head protection and a special accessory.
The accessory is usually an artifact baked right into the helmet.
The artifact could be a gun, vet equipment, or a scope.
The persona controls the artifact using voice command, tongue wrangling, or facial contortions.
The milieu of the campaign determines the base helmet type.

Regardless of the helmet type, the AR bonus is the same. 
Helmets do not affect restrictiveness. 
The baked-in artifact determines the wate and value of the helmet.

The type of equipment installed is limited by wate and reason.
Heavy artifacts would not only be impractical but would cause severe neck injury.
The table is an abbreviated list of equipment that may be useful in a combat helmet.


include::ROOT:partial$CH42_Table_Helmet_Accessory.adoc[]

Communication:: 
The communication device is generated at xref:iii-hardware:CH48_Misc_Equip.adoc#_communicators[communicators,window=_blank].
The comms cannot have a wate greater than 6 kg.
Helmet communications are common, and this does not count as a roll, and the player may roll again.

Gun:: 
The gun can only be a pistol, and its wate cannot exceed 6kg.
The gun is part of the helmet, and the wearer's head actions trigger it.
Jump to xref:iii-hardware:CH46_Guns.adoc#_gun_type[Gun,window=_blank] to generate the pistol.

Veterinarian Equipment:: 
The vet equipment must be reusable, and its wate cannot exceed 6kg.
The artifact cannot be a disposable one, like a vedi-kit or special bandage dispenser.
Jump to xref:iii-hardware:CH47_Medical.adoc#_veterinary_equipment_type[Vet Equipment,window=_blank].

Miscellaneous Equipment:: 
The miscellaneous artifact must be reusable, fair and its wate cannot exceed 6kg.
For instance, a plastix helmet with a built-in fire log may be humorous but cruel.
Jump to xref:iii-hardware:CH48_Misc_Equip.adoc#_miscellaneous_equipment_type[Miscellaneous Equipment,window=_blank].

Scope:: 
There is no limit to the type of scope in a helmet.
Roll from the list of scope artifacts found in xref:iii-hardware:CH48_Misc_Equip.adoc#_scopes[Scopes,window=_blank].

Visual Aid:: 
The persona will be able to flip the vizaud up and down using a stylish visor.
Roll from the list of visual aid artifacts found in xref:iii-hardware:CH48_Misc_Equip.adoc#_visual_aids[Visual Aids,window=_blank]

=== Plastix Armour

[horizontal]
Armour Rating:: 800
Restrictiveness:: 1
Wate:: 1.0 (0.7kg)
EXPS:: 75
Value:: 1000/kg (1000)

Plastix armour is unusually clean looking, white, ceramic composite plate armour.
The armour tends to remain clean and white.
This ceramic plating is the staple uniform of disposable spacefaring infantry.
This armour's helmet includes a closed faceplate with a nearly opaque sun visor.
Any persona wearing the helmet suffers a -114 penalty on her attack rolls.
The armour rating is not compromised if the persona removes this helmet.

NOTE: *In previous EXP versions, plastix armour had no AR when not wearing the vision-obscuring visor.*

=== Powered Armour

[horizontal]
Armour Rating:: 750
Restrictiveness:: 15
Wate:: 300 (210kg)
EXPS:: 1000
Value:: 10000000 + accessories

Powered armour is servo-aided and computer-enhanced body armour.
Typically powered armour is sealed, carries its power plant and fully integrates with its accessories.
Powered armour enhances the wearer's attributes by electronically amplifying the persona's natural abilities.
Powered armour becomes an anatomical extension of the persona, fully integrating her with the armour and its artifacts.
Jump to xref:iii-hardware:CH42_Powered_Armour.adoc[Powered Armour,window=_blank].

=== Protex

[horizontal]
Armour Rating:: 600
Restrictiveness:: +2
Wate:: None (2kg)
EXPS:: 900
Value:: 20000

Protex is industrial under armour that protects personas from specific workplace hazards.
Each suit consists of a bodysuit, integrated gloves, hood, and socks.
The armour clothing offers complete protection from the hazard described.
The protection is total, no damage taken, no saves necessary.

This armour is not for the rigours of combat.
Combat will destroy Protex reasonably quickly.
Protex armour can withstand 400 HPS of damage.
Any hit points of damage that the persona suffers are considered Protex damage.

include::ROOT:partial$CH42_Table_Protex_Armour.adoc[]

=== Shield 

[horizontal]
Armour Rating:: Table
Restrictiveness:: Table
Wate:: Table
EXPS:: 100
Value:: Table

A shield is a handheld sheet of armour used to deflect and block attacks. 
The shields here are like bucklers or tower shields, not force fields.
A shield can only protect one flank and does not cover the entire persona.
They are crafted from specific armour types and offer bonuses in AR and defences.

include::ROOT:partial$CH42_Table_Shield_Type.adoc[]

Ablative Shield::
This shield functions like the armour type <<_ablative_armour,Ablative>>. 
The shield gives an armour rating bonus of +75 and defends against lazer attacks.
The shield negates 10-100 (1d10 x 10) hit points of lazer damage.

Ballistic Shield::
This shield functions like the armour type <<_ballistic_armour,Ballistic>>.
The shield gives an armour rating bonus of +75 and defends against ballistic attacks.
The shield negates 10-100 (1d10 x 10) hit points of ballistic damage.
 
Combat Armour Shield::
The shield functions like the armour type <<_combat_armour,Combat>>.
The shield gives an armour rating bonus of +125.

Compucrafted Shield::
This shield is base on a <<_compucrafted_armour,Compucrafted>> version of mundane armour.
The shield improves armour rating by +3-300 (3d10 * 10).

Concussion Shield::
This shield functions like the armour type <<_concussion_armour,Concussion>>.
The shield gives an armour rating bonus of +75 and defends against concussion attacks.
The shield negates 10-100 (1d10 x 10) hit points of concussion damage.

Flexion Shield::
A flexion shied like an umbrella made of <<_flexion_covering,Flexion>> armour.
The shield gives an armour rating bonus of +125.

Force Shield::
A force field shield a defensive wall projected from a wrist band. 
It does not encompass the persona's body like a regular <<_force_field,Force Field>>.
The force shield absorbs 10-100 (1d10 x 10) hit points per battery.

Plastix Blocker::
This large white shield functions like the armour type <<_plastix_armour,Plastix>>.
The shield gives an armour rating bonus of +75 and impairs the user's accuracy.
Using a plastix shield will inflict an attack roll penalty of -100.

Powered Shield::
A powered shield is an attachment for an upper limb of xref:iii-hardware:CH42_Powered_Armour.adoc[Powered Armour,window=_blank].
The shield only works with the peripheral point of a powered armour limb.
The shield gives an armour rating bonus of +100 and 0-2 (1d3-1) accessories.
The accessories for a powered shield are generated at xref:iii-hardware:CH42_Powered_Armour.adoc#_upper_limbs[Upper Limbs,window=_blank].

Protex Shield::
A protex shield functions like the armour type <<_protex,Protex>>.
There is no adjustment of the persona's armour rating. 
The shield absorbs 100-400 (1d4x100) hit points of the protex type. 

:art: vac_suit_MiltonLuros_1953.png
:width: 450px
:snark: Have your vac suit ready
:artist: Milton Luros
:date: 1953
:license: CC BY-SA 4.0
:description: Drawing of a humanoid wearing a space suit and floating far above the planet.

include::ROOT:partial$articulate.adoc[]

=== Vac Suit
The vacuum resistance suit protects organic personas from the harm of space.
The cumbersome vac suit beats being simultaneously asphyxiated, boiled and frozen.
The vac suit can also be called a spacesuit.

NOTE: *Exatmo = EXterior to ATMOsphere. Inatmo = INside ATMOsphere.*

There are three different types of vac suits: civilian, industrial, and military.
Each of which has its peculiarities.
Vac suits will rip only if subject to direct damaging forces.
For example, shooting or intentionally cutting a vac suit may cause it to rupture.
None of these vac suits can survive entering into an atmosphere. 

include::ROOT:partial$CH42_Table_Vac_Suit.adoc[]

==== Civilian

[horizontal]
Armour Rating:: 500
Restrictiveness:: 4
Wate:: 10 (8kg)
EXPS:: 350
Value:: 100000

The civilian vac suit is the life preserver of outer space.
The suit keeps civilians alive in case of an exatmo emergency.
Adorning the vac suit is simple to understand and can be done quickly.
No one can don a civilian vac suit faster than an explosive decompression.

The civilian vac suit has no motion controls. 
Personas must clumsily drag themselves around by grappling in zero gravity.
Civilian vac suits have an all-frequency homing device, emitting a locator-distress call.

The persona will be able to function for four days in a vacuum.
After the fourth day, the civilian vac suit turns into a personalized cryogenic suspension unit.
Vac suit cryo will keep a persona alive as long as it suits the story.
A persona can also wear the vac suit to protect against toxins inside an atmosphere.
The suit will maintain a safe environment for four days and then act as a stasis bag for four months. 
Being resurrected from a vac suit is a veterinarian maneuver.

A civilian vac suit is relatively delicate, and intentional destruction can lead to rupture.
If warranted, there is a 1% chance of rupture per hit point of damage.
For example, 30 hit points of damage has a 30% chance of vac suit rupture.
Vac suit rupture will quickly kill the persona.:art: alien_vac_suit.png

:art: alien_vac_suit.png
:width: 350px
:snark: Industrial vac suit for an alien.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Aquarium with goldfish has robot legs and pincer arm. 

include::ROOT:partial$articulate.adoc[]

==== Industrial

[horizontal]
Armour Rating:: 600
Restrictiveness:: 8
Wate:: 30 (21kg)
EXPS:: 350
Value:: 250000

The industrial vac suit is for repair work in outer space.
It is cumbersome to put on and is not helpful in an emergency decompression.

The wearer can fly an industrial vac suit at six h/u.
The industrial vac suit has a built-in radio and storage for tools and parts.
The industrial vac suit also has a mini airlock.
The airlock allows for delicate inatmo hands-on work.

A worker can inhabit the industrial vac suit for one day.
Beyond one day of use, the wearer will die from the perils of exatmo. 
There are no safety features like those found in civilian vac suits.
An industrial vac suit cannot function inatmo.

==== Military

[horizontal]
Armour Rating:: 700
Restrictiveness:: 6
Wate:: 20 (15kg)
EXPS:: 350
Value:: 300000

A military vac suit is the least hospitable of the vac suits.
It is stealthy, combat-ready and expendable. 
There are no similarities between powered armour and military vac suits.
The military vac suit has no role in emergency procedures.

The military vac suit is designed not to be found. 
It is dark, light-absorbing and hard to detect.
There are no homing beacons. 
Communications are only through a lazer communicator with a direct line of a site.

The suit has a jet system built into the shoulders and feet of the vac suit.
This jet system is nimble and can turn on an electrum piece.
The system allows the wearer to travel at 12 h/u.

The gloves are highly articulated, allowing the wearer to employ any weapon.
The entire suit is ready for explosive removal in the atmosphere.
This feature allows the wearer to be combat-ready when boarding a space vehicle.
A military vac suit cannot function inatmo and cannot cross into an atmosphere.

A military vac suit will function for six days in exatmo.
There is no cryogenic suspension. 
Upon incapacitation of the wearer, a military vac destroys itself and its wearer.
The suit melts into harmless space debris, leaving no helpful evidence behind.

== Armour Parameters

=== Armour Rating 
The higher the armour rating, the better the protection offered to the wearer.
Not all the armour in this chapter has a high armour rating, but each offers some unique form of special protection.

The base armour rating of an unarmoured target is 500.
The armour ratings are related to this base value.
For instance, a suit of armour with an armour rating of 725 would give the wearer a base armour rating of 725 instead of 500.

=== Restrictiveness 
The more restrictive a suit of armour is, the more cumbersome and unyielding it is to normal body movement.
The more cumbersome the armour, the higher its restrictiveness.
The less restrictive armour is, the more that the persona can use her Dexterity to avoid taking damage.

=== Wate
The wate of armour is unnecessarily complicated.
The wate includes a number followed by another number in brackets.
The first number is a percentage.
The second number is the total wate of this armour for a 70 kgs anthro persona.

The percentage value helps the referee when fabricating armour for aliens or robots. 
The total wate of the armour will be the percentage of the wearer's wate.
If the percentage wate is 2.5% and the wearer has a wate of 100 kgs, the armour's wate is 2.5 kgs.
The value in brackets is the armour's wate for a 70 kgs anthro, or 1.5 kgs).

=== EXPS 
This value is the number of Experience points the persona earns for identifying the armour's unique function.

=== Value 
The value of armour is unnecessarily complicated.
The value includes a number followed by another number in brackets.
The first number is a value per kilogram.
The second number is the value of this armour for a 70 kgs anthro persona.

The value per kilogram helps the referee when fabricating armour for aliens and robots.
The value of a suit of ablative armour is 590 eps per kilogram of armour wate.
So a three-kilogram suit of ablative armour is worth 1770 eps.
The standard value for a 70 kgs anthro persona is 900 eps.
 