= Aerosols
An aerosol is a cylindrical canister that violently ejects a pressurized, gaseous solution through a push button valve.
When activated, an aerosol will discharge all of its contents, and cannot be used again.
Unlike grenades, aerosols lack a history of military use.
Aerosols  unforeseen methods of conflict, or could merely be maliciously employed industrial devices.

:art: aerosol_face.png
:width: 250px
:snark: Ding dong. Facial calling.
:artist: Michael Jackson
:date: 1990
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

.*Aerosol Checklist*
. <<_aerosol_type, Aerosol Type>>
. <<_trigger,Trigger>>
. <<_labeling,Labeling>>
. <<_description, Description>>
. <<_amount,Amount>>
. <<_aerosol_attribute_explanations,Aerosol Attribute Explanations>>

== Aerosol Type 

include::ROOT:partial$CH45_Table_Aerosol_Type.adoc[]

== Aerosol Types 

=== Anti Lazer Aerosol 
[horizontal]
Range:: 4h
Area of Effect:: 7h
Damage:: None
Wate:: 2kg
EXPS:: 275
Value:: 1000

The antilazer aerosol will dissipate any lazer that passes through its gaseous field. 
The antilazer cloud dissipates attacks, blinds lazer vision and blocks lazer comms. 
There is no limit to the amount of damage that an antilazer aerosol can dissipate
Energy attacks like ​fission, fusion, plasma ​are not affected by this aerosol. 
The shimmering cloud will evaporate 1-10 (1d10) minutes after discharge.

=== Attraction Aerosol 
[horizontal]
Range:: None
Area of Effect:: 1 km
Damage:: None
Wate:: 2.0kg
EXPS:: 350
Value:: 100

The attraction aerosol is a potent anti-repellant.
The attraction aerosol generates pheromones, vibrations, chemicals, or sounds that appeal to a particular persona.
The attracted persona will swarm towards the epicenter of the discharge.
The creatures will show up hungry, desperately in love, or plain curious.
How many referee personas approach the expedition depends on the mood of the referee.

This aerosol is also known as a love bomb.

include::ROOT:partial$CH45_Table_Attracted_Personas.adoc[]

=== Blinding Aerosol
[horizontal]
Range:: 12h
Area of Effect:: 3h
Damage:: None
Wate:: 2 kg
EXPS:: 300
Value:: 50

The blinding aerosol renders organic optical sensors inoperative
Any target with organic optical sensors must win a poison roll or be blinded.
Every 3 units spent within the cloud will require another poison roll or be blinded.
The blinding poison has an intensity of 2-20 (2d10).
If blinded, the target will remain blind for 0-9 (1d10-1) minutes.
If the duration is less than 1 minute, the target will be blinded for 1 to 20 units.
The cloud of the aerosol is invisible, and will dissipate in 1 to 12 units.
Any target entering the cloud must make a poison roll.

The blinding aerosol is alternatively called tear gas.

=== Catabolic Dismodulator Aerosol

[horizontal]
Range:: 12h
Area of Effect:: 3h, special
Damage:: 5-60 (5d12), special
Wate:: 2 kg
EXPS:: 300
Value:: 25000

The catabolic dismodulator turns inorganic matter into an opaque, multi-hued, cloud of gas.
The effects are devastating to equipment, and robots.
Only solid inorganic matter within the target hex is dismodulated.

Inorganic personas and equipment must win a poison roll or be destroyed by this attack.
The poison intensity is 13 to 28 (10+3d6) poison.
Most equipment has little or no constitution to combat this attack. 
Organic personas hit directly with a catabolic dismodulator have a 5% chance of  dismodulating along with their equipment.
If an organic persona can be dismodulated they must win a poison roll or be killed.

The area of effect of the catabolic dismodulator is only the the target hex.
The 3 hex area of effect is from cold damage to  targets caught in the cloud.

=== Demagnetizer Aerosol 

[horizontal]
Range:: 12h
Area of Effect:: 5h
Damage:: None
Wate:: 2kg
EXPS:: 300
Value:: 25

This aerosol is an industrial strength tape head cleaner.
Temporarily dissolving the weak forces of magnetism creates chaos for devices.
The obvious problems that could arise from this are broad.
Fridge magnets fall of the fridge. 
Monitors will go blank.
Magnetic attachments will detach.
Magnetic levitating legs on vehicles and robots will collapse.
Electronic memories get erased.
This attack has no specific damage, but the result of it's attack can lead to damage.

Military devices must win a mental attack roll to avoid being demagnetized.
The mental strength of the attack is 3-18 (3d6).

Magnetized remains neutralized for 3-18 units.
There is a 1% chance for each unit of duration that the device  is damaged.

=== Disintegrator Aerosol 

[horizontal]
Range:: 15h
Area of Effect:: 1h
Damage:: Special
Wate:: 2kg
EXPS:: 300
Value:: 12000

The disintegrator aerosol turns inorganic substances into dust.
More refined, and discerning, than its cousin the catabolic dismodulator aerosol, the disintegrator aerosol will only affect a certain material.
Any amount of this material, within the area of effect,  is turned into dust.

What happens to partially impacted devices and targets.
For example a piece of equipment may be partially disintegrated by the aerosol.
To randomly determine this jump to xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Rolls].
A loss in a sphincter roll will indicated that the device is partially disintegrated.
Jump to xref:i-roll_playing_rules:CH21_Artifact_Damage.adoc#_extent_of_damage[Equipment Damage] to determine the extent of damage.


A malfunction of this weapon disintegrates the aerosol into dust.

include::ROOT:partial$CH45_Table_Disintegration_Type.adoc[]

=== Exploding Aerosol 

[horizontal]
Range:: None
Area of Effect:: 1h
Damage:: 5-60 (5d12)
Wate:: 2kg
EXPS:: 4200
Value:: 42

This sadistic device explodes like a fragmentation grenade when it is triggered.
All targets in the 1 hex area of effect take the damage listed.
The referee should note that it is very impolite to laugh when an exploding aerosol is discharged.
This toy would be considered a trap and should not count as a toy roll at start up.

=== Foam Aerosol 

[horizontal]
Range:: None
Area of Effect:: 8h by 2h
Damage:: None
Wate:: 2kg
EXPS:: 100
Value:: 250

The foam aerosol creates a pad of creamy foam 16 hexes across, and 2 hexes deep.
For the first minute, the foam can be easily travelled through.
By the end of the second minute the foam is starting to thicken, and movement is halved.
Three minutes after being discharged the foam will be so viscous that movement will be reduced to one quarter.
The pad will be completely solidified 4 minutes after its discharge, and anything caught within it will be completely trapped.
At no time, even during the solid phase, is breathing hampered  by the foam.
Anything entombed by the foam pad will starve to death before anything else.
The foam is not much stronger than Styrofoam, but only those persons trapped in the outer edges, and those who are particularly industrious will be able to free themselves.
The colour of the foam will be the same as on the outside of the aerosol canister.
Once solid, the foam is structurally sound, and well insulated.
This aerosol has been given synonyms such as the insulator, and the homemaker.

=== Freezing Aerosol 

[horizontal]
Range:: 9h
Area of Effect:: 8h
Damage:: 5-60 (5d1)
Wate:: 2kg
EXPS:: 300
Value:: 1000

The freezing aerosol subjects all targets in its area of effect (8 hexes) to an enthalpy attack.
The super cooled temperatures coats everything with ice and snow.
The freezing aerosol has a % chance, equal to the damage inflicted, of entrapping large, or smaller, sized targets in ice.
This attack also freezes switches in place, triggers in the firing position, pins in grenades, pant zippers closed, etc.

=== Gas Aerosol 

[horizontal]
Range:: 7h
Area of Effect:: 6h
Damage:: Special
Wate:: 2kg
EXPS:: 250
Value:: 900

The gas aerosol fills the area of effect with a pall of transparent, but noticeable gas.
The cloud of gas will affect all organic creatures within it.
Personas must win a poison or be affected by the toxin.
The poison roll must be repeated for every 3 units within the area of effect.
The intensity of the poison is 2-16 (2d8).
The cloud will dissipate in 4 to 16 units.
Roll on the below table to determine the effect of the gas.

include::ROOT:partial$CH44_Table_Gas_Type.adoc[]

=== Invisibility Aerosol

[horizontal]
Range:: None
Area of Effect:: 0h
Damage:: None
Wate:: 2kg
EXPS:: 300
Value:: 250000

The invisibility aerosol prevents matter from deflecting or reflecting visible light.
This aerosol has a limited area of effect and only works on it's target hex.
Everything in that are will become undetectable to sensors that use reflected light.
Sonar, infravision, ultravision, and other such sensors are not affected.

The aerosol does an effective job of making the targets invisible.
The disguise is only on the visible spectrum.
Personas still occupy space, exude odors and make noise. 

There are many challenges to being invisible. 
Eye hand coordination becomes none existent. 
Equipment dropped remains invisible.

The effects of this aerosol last 1-4  (1d4) days.

=== Matter Detector Aerosol 

[horizontal]
Range:: 12h
Area of Effect:: 12h
Damage:: None
Wate:: 2kg
EXPS:: 100
Value:: 400

The matter detector aerosol brings the material world into clear focus.
Solid matter within the area of effect is coated with detection chemicals.
The detection coating emits subtle amounts of heat, light, radiation, and vibration.
This chemical exposes matter to most common sensors (eyes, infravision, sonar).
Invisible objects suddenly appear, secret doors are highlighted.
If something is solid it gets lit up.
If something is not solid it also stands out.
The matter detector aerosol is a good hologram detector too.

Attack rolls on lit targets receive a bonus of +65.
Ambushes are 10 times easier to detect.
Hiding while lit is 10 DDs more difficult.
The duration of detection continues for 1 to 4 minutes.

This aerosol is also called a marker aerosol, or a targeting aerosol.

=== Mistor Aerosol 

[horizontal]
Range:: None
Area of Effect:: 25h
Damage:: None
Wate:: 2kg
EXPS:: 100
Value:: 400

The mistor aerosol disables all sensory modalities ineffective.
Sensors include: eyes, sonar, infravision, touch, smell, etc.
Personas within the cloud are not blinded, but there is a barrier between all 5 senses.
Inside the cloud vision is greyed out, yelling is quiet, and touch is numbed.
Virtually all sensors are dulled through lack of stimuli.
Personas have no sense of direction, and combatants may bump into each other 
Regardless of collisions attack rolls are made in a random direction.
Movement is random, unless the persona has some form of heightened directional sense.
The suspension will remain cohesive for 16 days.

=== Molecular Diffusion Aerosol 

[horizontal]
Range:: 10h
Area of Effect:: 7h
Damage:: 12-96 (12d8)
Wate:: 2kg
EXPS:: 300
Value:: 2500

This delivers microscopic tears to anything in the area of effect. 
These little micro rends cause the prescribed damage. 
The massive amount of damage is delivered to everything in the area of effect.
Damaged personas and equipment do not appear to have any obvious damage or injury.
Only detailed inspection will reveal the microscopic diffusion of the molecules. 

=== Napalm Aerosol 

[horizontal]
Range:: 8h
Area of Effect:: 8h x 2h
Damage:: 6-60 (6d10)
Wate:: 2kg
EXPS:: 300
Value:: 1900

The napalm aerosol blasts a swath of flaming gas and gel when triggered.
This is definitely not a artifact you'd want to mistakenly point backwards.
The blazing area of effect sears everything for 6 to 60 (6d10) hit points of damage.
Everything that takes the initial heat damage immolates and continues to be damaged.
Targets that have immolated will burn for an additional 2 to 8 units.
Burning targets will take an additional 4-24 (4d6) hit points of damage per unit.
The specially adherent flammable chemicals cannot be extinguished with normal measures.
Most targets will continued to burn for the full immolation period.

Other than the flaming targets, the napalm aerosol will extinguish itself immediately.

=== Paint Aerosol 

[horizontal]
Range:: 4h
Area of Effect:: 4h
Damage:: None
Wate:: 2kg
EXPS:: 50
Value:: 42

The paint aerosol can be used to paint an entire room with one explosive button push.
This time saving feature violently paints everything in its way.
This indiscriminate nature of the paint aerosol allows it to be weaponized.
If caught in the area of effect personas must win a poison roll or be blinded.
The blinding affects all visual sensor and lasts 1-20 (1d20) units.
The intensity of the poison 1-12 (1d12).
The player may use her persona's DEX or CON for this poison roll.

The paint colour match the aerosol canister colour.
To get a simple or zany colour jump to xref:v-software:CH55_Appearances.adoc#_colour_your_whirled[Colour].

This aerosol is also called an RBG or Color Your Whirled.

=== Pharmaceutical Aerosol 

[horizontal]
Range:: 12h
Area of Effect:: 1h
Damage:: None
Wate:: 2kg
EXPS:: Double pharma
Value:: Triple pharma

This aerosol can be used to apply long range prescriptions to groups of patients.
What sort of plague, military infestation, or Woodstock celebration prompted the invention of such a dispenser is unknown.

Take a little trip over to xref:iii-hardware:CH50_Pharmaceuticals.adoc#_pharmaceutical_type[pharmaceuticals] 

All targets in the area of effect must *lose* a poison roll to be affected.
For beneficial pharmaceuticals to help the persona she must lose the poison roll.
The intensity of the poison (pharmaceutical) is 2 to 20.

This intensity is reduced by one for every target in the area of effect.
The more potential users, the milder the dose.
It is possible to make this aerosol completely ineffective by having too many targets in the area of effect.
The cloud dissipates immediately after it has been ejected.

=== Poison Aerosol 

[horizontal]
Range:: 12h
Area of Effect:: 3h x 12h
Damage:: Death
Wate:: 2kg
EXPS:: 300
Value:: 700

The poison aerosol is a selective lethal, combination contact an inhalation poisons. 
The ejected cloud is a mix between nerve gas and pulmonary desiccant.
Any persona affected by this attack must win a poison roll or die.
The intensity of the poison is 2-24 (2d12).
The lethal attack does not linger and only affects those personas indicated.

While the lethal toxin's affect has no duration there is a lingering residue.
This residue violently repulses susceptible personas. 
Affected personas cannot approach the swath area unless they win another poison roll.
The repellent effect last for 1-4 (1d4) days.

The lethal poison aerosol are also called Raid, or nerve gas.

include::ROOT:partial$CH45_Table_Poisoned_Personas.adoc[]

=== Repellent Aerosol 

[horizontal]
Range:: None
Area of Effect:: 3h
Damage:: None
Wate:: 2kg
EXPS:: 300
Value:: 50

The repellent aerosol employs irritating pheromones, smells, vibrations and emotions.
These irritations drive the affected personas out the area of effect.
There is no roll vs poison. 
The 3 hex area of effect or anything coated by the repellent is unapproachable.
Unintelligent aliens will bolt far beyond the area of effect.

To approach within 10 hexes of the repellent epicenter a personas must win a poison roll.
The poison intensity is 13-28 (3d6+10).
Intelligent creatures may make an attempt to approach once per day.
The repellent effect lasts 1-6 (1d6) days

This aerosol is also called Oph, Repecks, or Protector.

include::ROOT:partial$CH45_Table_Repelled_Personas.adoc[]

=== Siren Aerosol 

[horizontal]
Range:: None
Area of Effect:: 500h
Damage:: 2-12 (2d6)
Wate:: 2kg
EXPS:: 100
Value:: 75

This ear splitting siren will wail for 2-8 minutes.
The initial blast of sound inflicts 2-12 (2d6) hit points of damage.
There is also a 10% chance per hit point of damage of going deaf.
The screeching will launch a damaging harmonic each minute of duration.
This indicates another 2-12 (2d6) hit points of damage. 
Follow up attacks also indicates another chance to be deafened.
If a persona becomes deaf or unconscious the follow up sonic blasts do no damage.
Hearing will be restored after 1-10 hours.

The siren aerosol damages organic and inorganic acoustic sensors.
Devices or personas that use sonar take double damage from the first blast.

This aerosol has severe environmental effects.
When used outdoors delicate flora and fauna can die from shock. 
The epicenter may attract dear, confused and angry local fauna.

This aerosol can also be called a whistler or screecher.

=== Smoke Aerosol 

[horizontal]
Range:: None
Area of Effect:: 12h
Damage:: None
Wate:: 2kg
EXPS:: 42
Value:: 100

This smoke aerosol will instantly discharge a 24 hex diameter sphere of dense smoke.
The smoke will obscure the vision of any visual sensors caught within its field.
This means that there is a -230 per hex to hit penalty for ranged attacks, unless the persona has some sort of smoke cutting device.
The smoke is so dense that it can only be moved by a gale force wind, or a bulldozer.
The cloud will disperse in 1 to 8 weeks.
The colour of the smoke will match the colour of the aerosol canister.
To generate the colour jump to xref:v-software:CH55_Appearances.adoc#_colour_your_whirled[Colour].


=== Web Aerosol 

[horizontal]
Range:: 8h
Area of Effect:: 8h
Damage:: None
Wate:: 2kg
EXPS:: 300
Value:: 1000

The web aerosol splatters the area of effect with a super adhesive goo.
Anything caught in the area of effect will be trapped until the webby mess dissipates.
The web maintains it's grip for  2-16 minutes.
Any persona that saunters into the goo will instantly become stuck.

A trapped persona can attempt to make subtle movements without risk.
Small actions like pulling a trigger, firing an aerosol, or taking a pharmaceutical
Struggling to break free is a different situation.
There is a chance that the web will block the persona's face and risk suffocation
There is a 1% chance of suffocation whenever a trapped persona struggles.

Any attempt to free a persona is a chance to entrap the rescuer.
Procedures such as burning, dissolving or disintegrating will have varying success.
Consult the xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice] to determine if a particular attempt to destroy the web works. 

The colour of the web will be the same as the colour of the aerosol canister.
Jump to xref:v-software:CH55_Appearances.adoc#_colour_your_whirled[Colour] to generate a colour of string. 

The web aerosol is also called Killy String or Super Goo. 

== Aerosol Attribute Explanations

=== Range 
Aerosols:The range of an aerosol depends entirely on the pressure of its contents.
This internal pressure usually ejects the contents of the aerosol a safe distance before exploding with an area of effect blast.
Some aerosols have an swath area of effect, and the range represents the longest dimension of this area of effect.
For more info see chapter 30, Grenade and Aerosol Combat.

=== Area of Effect 
Aerosols:An aerosol is an area of effect weapon.
First the contents of the aerosol are sprayed a certain distance, and once reaching that range (or hitting a solid object) the contents explode about their area of effect.
For example, a freezing aerosol has a 9 hex range, and an 8 hex area of effect.
This aerosol fires out 9 hexes, and then freezes everything in an 8 hex spherical area of effect.

=== Damage 
This is the hit point range that is inflicted upon any target caught within the area of effect of either an aerosol or grenade.
Wherever the damage has been omitted, the aerosol has some other special effect.
Remember that damage is rolled once, and applied to all targets within the area of effect.
Unless specified there is no save versus area of effect attacks.

=== Wate 
This is the wate of an unspent grenade, or aerosol.
An empty aerosol canister has a wate 10% of its original wate.
E.g., 2 kg aerosol is reduced to an empty 200 gm canister.

=== EXPS 
Experience points for identifying a grenade, or aerosol, are earned the same as for any other artifact.
An equivalent experience point value can be earned after either weapon has been discharged, but these EXPS can only be earned by the firer.

=== Value 
The value of a grenade, or aerosol, is the value of one charge.
In some cases aerosols can generate more than one charge, but even with these modifications such aerosols still have the same value.

=== Trigger 
Aerosols are even simpler to use than grenades.
Push the release valve on top of the canister, and all its contents instantly spray out for all their described effects.

=== Amount 
The ref rolls a 1d8 to determine the number of aerosol canisters found in a package.
For powerful campaign altering aerosols one will suffice.

=== Labelling
Since many of the aerosols described in this chapter are non-military in.
nature, many may still have their industrial labelling intact.
To determine the literacy of an aerosol's labelling roll a 1d10.
A roll of 1 indicates unintelligible labelling.
This is labelling that is either in an alien language, has incorrect instructions, or is somehow damaged.
A roll of 10 will yield an aerosol with proper markings, and instructions.
Proper labelling may greatly reduce the ExPs value of an aerosol, but increase its monetary value.
All other rolls (2-9) indicate that no markings of any sort are listed on the aerosol canister.

=== Description 
The aerosol can appears to be an oversized version of today's typical Freon container.
The aerosol may have a distinctive colour--either the canister, or the jet--that can be rolled on the Giant Colour table.
The Giant Colour Table can offer up a simple colour by rolling a 1d10.
Fancy colours, affect and patterns can be rolled to create zany colour patterns. 

include::ROOT:partial$add_colour_to_your_world.adoc[]


