= Veterinary Equipment

Veterinary equipment is for repairing organic machines.
Each piece of vet equipment performs its private miracle, but nothing does everything, and some things do nothing.
Even though the equipment is highly advanced, the equipment still requires some input from so-called professionals.
Veterinarians are the primary users of vet artifacts.
Most artifacts merely require a single vet to point the device correctly.
While other artifacts require an entire xref:i-roll_playing_rules:CH14_Performance_Tables.adoc#_research_teams[Research Teams,window=_blank].

:art: medical_equipment_combat.png
:width: 350px
:snark: Zero responders
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of human soldier being tended to by white coated veterinarian.

include::ROOT:partial$articulate.adoc[]

.*Vet Equipment Checklist*
. <<_veterinary_equipment_type,Veterinary Equipment Type>>
. <<_vet_equipment_parameters,Vet Equipment Parameters>>

== Veterinary Equipment Type 

include::ROOT:partial$CH47_Table_Medical_Equipment.adoc[]

== Veterinary Equipment Types

=== Age Determiner 

[horizontal]
Duration:: 5 years
Bonuses:: +20 age related rolls, +10 time related rolls
Wate:: 1kg
EXPS:: 200
Value:: 5000

The age determiner estimates the age and life stage of organic personas.
The little black box automatically displays the info when pointing at the target.
The age determiner has off-label uses that come in handy. 
The device can help detect a disguise, notice a time-space aberration, or detect an ambush.

=== Anesthetics Mask 

[horizontal]
Duration:: 5 hours
Bonuses:: +30 surgery; +40 on comfort
Wate:: 1.2kg
EXPS:: 10
Value:: 6000

The mask renders any organic patient safely unconscious.
The mask breathes for the patient and puts them into a state ready for surgical interventions.
An anesthetics mask looks like a gas mask with dials and indicators.
It is virtually impossible to subject an unwilling patient to the anesthetics mask.
The mask does not protect the wearer from submersion or in the vacuum of space.

=== Anti Aging Beam 

[horizontal]
Duration:: Power Source
Bonuses:: +40 age related rolls
Wate:: 150kg
EXPS:: 200
Value:: 50000

This machine bastes the organic persona with information encoded energy.
This data can technomagically reprogram cells reversing ageing.
A complete treatment takes place over 1-4 (1d4) days and lasts an hour each day.
Any treatment interruptions require the treatment to start over.
Getting injured in combat would be considered a treatment interruption.

The beam is not a fountain of youth.
The anti-ageing beam only removes chronologic years from the persona's lifespan. 
The beam does not repair any decayed attributes.
The beam does not change the appearance of the patient.
So a patient would not change their attributes nor move from one life stage to another.

The anti-ageing beam heals 3-30 (3d10) years of chronologic damage.
Accidentally reducing a persona's chronological age to less than one year old is lethal.

=== Anti Mutation Beam 

[horizontal]
Duration:: Power Source
Bonuses:: +30 mutation related rolls
Wate:: 150kg
EXPS:: 2000
Value:: 200000

This machine bastes the organic persona with information encoded energy.
This data can technomagically reprogram cells that have mutated.
The beam rapidly restructures the patient into its original organic form.
The beam removes all mutations, not just defective mutations.
The anti-mutation beam does not affect the mutation-like abilities of robots or aliens.
If the robot or alien caught the mutation after fabrication or evolution, this beam would work.
If there is a dispute whether a mutation is a freak of nature or an evolutionary trait, consult the xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice,window=_blank].

The anti-mutation beam is a large device, and it surrounds the patient.
The beam's effect is instantaneous and irreversible.
While under the beam, physical mutations shrivel up and fall off the mutant.
Mental mutations stop working.

Veterinarians can manipulate the beam for more exact effects.
For example, removing one mutation while preserving another is a veterinarian manoeuver.
Working around a physical mutation is a 3DD maneuver, and a
mental mutation is a 10DD maneuver.
If a vet wanted to eliminate a mutant's pus-producing organ while retaining her symbiotic attachment, the player must win a 13DD performance roll.

=== Anti Virus Beam 

[horizontal]
Duration:: 200 unit per Battery
Bonuses:: +20 on infection rolls
Wate:: 5kg + Battery
EXPS:: 1000
Value:: 100000

The anti-virus beam will damage foreign micro-organisms infiltrating an organic substance.
The beam eliminates viral, bacterial, fungal, or prion infections.
More exotic infections like nanomachines or exoplanetary organisms will require a veterinarian's intervention.
The beam will not kill symbiotic organisms that are healthy for the persona.
This super-sterilizer has a range of 75 cm.

Whether the beam works on a robot with computer virus requires xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice,window=_blank].

=== Auto Tourniquet 

[horizontal]
Duration:: Unlimited
Bonuses:: +20 limb or bleeding rolls
Wate:: 1.5kg
EXPS:: 250
Value:: 750

The automatic tourniquet will locate any severe bleeding and control the hemorrhage.
The persona activates the device and places it on the organic persona.
The automated tourniquet rolls across the body and gets to work on any bleeding it locates.
The tourniquet is more than just an automated constricting bandage.
This artifact employs electrical impulses to constrict the appropriate vessels and prevent injury from constriction.
The tourniquet can assist on a severely damaged limb, internal bleed, or head wound.

The tourniquet has safety mechanisms to prevent malicious placement.
The auto tourniquet does not heal damage but does prevent further damage.
The electric tourniquet will always function (no batteries necessary) if attached to a warm organic creature.
Veterinarians earn +20 on any performance rolls that involve blood loss (surgery to severe trauma).

:art: medical_bot_suturing.png
:width: 350px
:snark: Automated suturing device
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of human receiving sutures from a tiny robot.

include::ROOT:partial$articulate.adoc[]

=== Bandage Box 

[horizontal]
Duration:: 100 minutes per Battery
Bonuses:: +20 quick fixes, +10 surgery rolls
Wate:: 5kg
EXPS:: 500
Value:: 1500

The bandage box is not just a collection of bandages and plasters.
A bandage box will crawl all over the patient's body, sewing, gluing, and bandaging wounds it finds.
This artifact will clean and change old dressings.
The treatment takes about 1-6 minutes for a medium-sized patient.

=== Biorganic Attachment 

[horizontal]
Duration:: Permanent
Bonuses:: Nil
Wate:: 10kg
EXPS:: 500
Value:: Special

A biorganic attachment is a self-attaching limb in a bag.
The limb comes in a vacuum-sealed bag along with the necessary power, technology and invasive tools.
A biorganic practically attaches itself in a gory, noisy automated surgical procedure.
The limb may be from a donor bank, a bio vat, or an unlucky clone.

Once attached be biorganic attachment becomes seamless with the persona.
If the persona is strong, the attachment will grow in strength.
If the persona is weak the attachment will atrophy.
Biorganic attachments are relatively easy for a veterinarian or a biologist to attach.
Not all attachments are created equal.

include::ROOT:partial$CH47_Table_Biorganic_Attachment_Type.adoc[]

Basic Unit::
The basic unit requires a veterinarian for attachment.
Attaching a basic unit is a DD4 maneuver.
Reasons for failure could be sizing, anthro type or technique.
If there is any questions about limb sizing or matching consult the xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice,window=_blank].
This attachment only works for anthro arms or legs.
The biorganic attachment will adjust to the size and anthro type over time.
The vet or biologist can preserve the limb for later use if the attempt fails.
The basic unit is worth 2000 EXPS and 75000 eps.

Special Edition::
This unit is primarily self-attaching.
The biorganic attachment has an 80% chance of successfully self-attaching.
If guided by a vet, there is a 100% chance of attachment success. 
This attachment only works for anthro arms or legs.
The biorganic attachment will adjust to the size and anthro type over time.
The special edition unit is worth 1000 EXPS and 1500000 eps.

Luxury Edition::
The luxury edition biorganic looks like a sausage-in-a-bag.
This lack of definition gives it the flexibility to more exotic limb types.
A luxury edition biorganic attachment can replace fins, wings, noses, trunks, ears, eyelids, or damaged physical mutations.
A vet is not required, and there is a 99% chance of attachment success.
The luxury edition is worth 500 EXPS and 2750000 eps.

Luxury Plus::
The luxury plus biorganic attachment looks like a sausage-in-a-bag.
This lack of definition gives it the flexibility to more exotic limb types.
A luxury edition biorganic attachment can replace fins, wings, noses, trunks, ears, eyelids, or damaged physical mutations.
The luxury plus attachment includes a non-defective physical mutation.
This mutation can be a xref:v-wetware:CH59_Physical.adoc#_combat_mutations[Physical Combat Mutation,window=_blank], or a xref:v-wetware:CH59_Physical.adoc#_non_combat_mutations[Physical Non-Combat Mutation,window=_blank].
If the persona is not missing a limb, they will still acquire the mutation.
A vet is not required, and there is a 99% chance of attachment success.
The luxury plus edition is worth 500 EXPS and 5500000 eps.


=== Biorganic Replacement 

[horizontal]
Duration:: Permanent
Bonuses:: Nil
Wate:: 1kg
EXPS:: 960
Value:: Special

A biorganic replacement is a self-inserting organ in a bag. 
The organs can come from tissue culture vats, harvested from clones or criminals, or alien life forms.
The biorganic replacement can enhance an existing system or replace an ailing one.
The new organs possess new and bizarre features, almost always strengthening the persona.

75% of the time, the biorganic replacement will be a basic unit requiring surgical insertion by a veterinarian.
Correctly inserting this attachment is an 8DD maneuver and requires a surgical theatre and anesthesia.
The remaining 25% of the time, the biorganic replacement will be a luxury unit that is self-inserting.
The self-inserting unit still requires a veterinarian, but success is guaranteed and requires no special operating theatre.
The value of a luxury self-inserting is ten times that of the basic unit.

Stacking biorganic replacements is dangerous and leads to bad outcomes.
Stacking a biorganic replacement always requires a veterinarian and likely an entire research team.
The degree of difficulty for stacking is 12 per level. 
So 12DD the first time and 24DD the second time.
Failure results in an attribute penalty equal to the attribute bonus.  

include::ROOT:partial$CH47_Table_Biorganic_Replacement_Type.adoc[]

Blood Filters::
The blood filter is a super spleen combined with fortified bone marrow, strengthening the quality of the personas lifeblood.
A blood filter could replace a failing blood system or improve a healthy one.
The blood filter gives a permanent constitution increase of +10%.
The bonus must be at least one point but no more than two points.
The persona is hardened against poison and gets a bonus of +2 to win poison rolls.
The blood filter biorganic attachment is worth 150000 eps.

Bone Hardening:: 
Bone hardening coats the persona's skeleton with a strengthening laminate.
The bone hardening will only take in adult personas.
The microbial slurry is drunk by the persona and does not require a vet intervention.
There is no luxury edition of bone hardening.
There is a 20% HPS max bonus granted due to the tougher bone structure.
The bone hardening biorganic attachment is worth 100000 eps.

Brain Tissue::
The brain tissue biorganic attachment improves mental capacity and memory.
A vet must successfully insert the proto tissue into the persona's braincase. 
The persona receives a permanent intelligence increase of +10%.
The bonus must be at least one point but no more than two points.
This increased intelligence has no impact on mental strength. 
The brain tissue biorganic replacement is worth 1000000 eps.

Conductive Tissue::
Conductive tissue biorganic replacement improves the user's nervous system.
Parallel neural tissue grows alongside existing neurons, improving electrochemical flow.
The persona receives a permanent dexterity increase of +10%.
The bonus must be at least one point but no more than two points.
The conductive tissue biorganic replacement is worth 500000 eps.

:art: primed_pumper.png
:width: 250px
:snark: A primed pump.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Mammal four chamber heart with mechanical attachments. 

include::ROOT:partial$articulate.adoc[]

Contractile Tissue:: 
Contractile tissue biorganic replacement adds muscle tissue and innervation, improving the persona's brawn. 
The persona receives a permanent physical strength increase of +10%.
The bonus must be at least one point but no more than two points.
The contractile tissue biorganic replacement is worth 100000 eps.

Exoskeleton:: 
The exoskeleton biorganic replacement seals the persona's body from the outside world by replacing her skin.
The persona's skin becomes impermeable, and her orifices become unseemly fleshy airlocks.
Nothing enters or exits her body without first passing through the semi-volitional airlocks.
The persona's skin functions the same as a xref:CH42_Armour.adoc#_civilian[Civilian Vac Suit,window=_blank]. 
The persona's charisma drops by 5 points, and her dexterity decreases by two points.
The persona smears a smelly bouillabaisse of biochemistry onto her skin, and no veterinarian is required.
There is no luxury edition for this biorganic replacement.
The biorganic replacement exoskeleton is worth 2000000 eps.

Hardening:: 
The hardening biorganic replacement strengthens the persona's integument.
Fat pads get reinforcements, bones get lamination, and skin gets textile weaves.
The persona's base armour rating increases to 600. 
There is a 10% HPS max bonus and a -2 charisma penalty.
The persona smears a smelly bouillabaisse of biochemistry onto her skin, and no veterinarian is required.
There is no luxury edition for this biorganic replacement.
The biorganic replacement of hardening is worth 100000 eps.

Digestion::
The digestion biorganic replacement upgrades the entire digestive tract.
The improvements include teeth, stomach, intestine, and support organs.
This hardening allows the persona to chew on peculiar items and consume them without gastric despair.
The persona only needs to eat the smelly biomass to get the biorganic replacement.
No vet is required to activate this biorganic attachment, and there is no luxury edition.
This patient gets a bonus of +5 on all toxin poison rolls and cannot suffer nausea.
The digestion biorganic replacement is worth 550000 eps.

Pump:: 
The pump biorganic replacement improves an anthro's vital fluid pump.
The pump itself is improved, as are the essential vessels of the vascular system.
The improved heart and blood vessels improve the persona's constitution.
The persona receives a permanent CON increase of +20%.
The bonus must be at least one and no more than three points.
The pump biorganic replacement is worth 200000 eps.

Lung::
The lung biorganic replacement improves the persona's respiratory status.
The improved respiratory tissue can be more lung, better gills, or hyperphotosynthetic leaves.
The replacement will improve the persona's constitution.
The persona receives a permanent CON increase of +10%.
The bonus must be at least one and no more than two points.
The persona gets a +5 on inhaled and gas poison rolls.
Breath-holding, or the anthro equivalent, is increased by three times. 
The lung biorganic replacement is worth 200000 eps.

Mental Mutation Insertion:: 
This biorganic replacement gives the user a permanent mental mutation.
There is no way to determine what the mental mutation will be in advance.
Jump to xref:v-wetware:CH58_Mental.adoc#_mutation_type[Mental Mutations]  
The mental mutation should not be a defect. 
A vet is required to get this replacement into the braincase of the persona.
The mental mutation insertion is worth 10000000 eps.

Physical Mutation Insertion::
This biorganic replacement gives the user a permanent physical mutation.
There is no way to determine what the physical mutation will be in advance.
Jump to xref:v-wetware:CH59_Physical.adoc#_mutation_type[Physical Mutations]  
The physical mutation should not be a defect. 
The physical mutation insertion is worth 5000000 eps.

Sensory:: 
Sensory biorganic replacements enhance the persona's connection to the outside world.
There is an improvement in vision, hearing, touch, taste and smell. 
The improved sensory system improves the persona's awareness.
The persona receives a permanent awareness increase of +20%.
The bonus must be at least one and no more than three points.
Eye-hand coordination maneuvers are improved, and ambush detection doubles.
The sensory biorganic replacement is worth 2000000 eps.

Softening::
The softening biorganic replacement improves how the persona outwardly appears.
Softening is the most complex of all the biorganic replacements.
While the goal is to improve the persona's charisma, how the body is modded varies.
This replacement accentuates vocal cords, pupil reaction, skin tone, hair colour.
The improved appearance of the persona improves her charisma.
The persona receives a permanent charisma increase of +20%.
The bonus must be at least one and no more than three points.
The softening biorganic replacement is worth 1000000 eps.

=== Vision Goggles

[horizontal]
Duration:: 12 months per Battery
Bonuses:: Nil
Wate:: 500 gm (includes Battery)
EXPS:: 960
Value:: 200000 + Battery

Vision goggles will restore sight to an anthro persona struck by visual impairment.
The goggles restore sight up to a range of 1 hex per point of awareness.
The vision goggles
A persona with an awareness of 12 could see 12 hexes in daylight and complete darkness.
If the persona has no visual impairment, they still enjoy the night vision effects.


=== Blood Clot Disruptor 

[horizontal]
Duration:: 150 unit per Battery
Bonuses:: +20 for blood related procedures
Wate:: 2kg + Battery
EXPS:: 1300
Value:: 35000 + Battery

The blood clot disruptor is for dismantling unwanted clots from the outside of the body.
The device does not treat any particular medical illness but assists the vet when working with blood.
A complete treatment uses ten units of battery power.

Weaponizing this device yields unpredictable results.
The blood clot disruptor is a Type A attack, and it behaves like a dagger.
A successful attack roll inflicts 2-12 (2d6) hit points of damage.
There is a 1% chance per hit point of damage of inflicting a major bleed.
A major bleed will inflict an additional 2-20 (2d10) hit points of damage.
Each attack drains 30 units of battery power.
Five attacks would drain a full battery.

=== Blood Congealer 

[horizontal]
Duration:: 1800 units per Battery
Bonuses:: +10 for blood related procedures
Wate:: 1.7kg
EXPS:: 800
Value:: 25000 + Battery

The blood congealer helps the body create needed clots from outside of the body. 
Any persona can use the device can be used to create scabs on superficial bleeding.
Only a vet can use a blood congealer to control internal bleeding.
The device does not cure any particular medical condition but assists the vet when working with bleeding or surgery.

Weaponizing this device yields unpredictable results.
A successful attack roll inflicts 2-12 (2d6) hit points of damage.
There is a 1% chance per hit point of damage of inflicting a major clot.
A major clot will inflict an additional 2-20 (2d10) hit points of damage.
Each attack drains 300 units of battery power.
Six attacks would drain a full battery.

=== Bone Setter 

[horizontal]
Duration:: 90 minutes per Battery
Bonuses:: +20 for bone related rolls
Wate:: 8kg + Battery
EXPS:: 1500
Value:: 3000

The Bone Setter accelerates the repair of any anthro's structural elements.
Structural elements include bones, cellulose, exoskeletons or mutated limbs. 
Fractures, cavities, cancers, deformities, and ligaments repair technomagically.
A treatment uses 1-10 minutes of battery power.
Any persona can use the bonesetter to heal 1-6 (1d6) damage to obvious trauma.
A vet can extend this healing into daily rehab.

=== Breath Ball 

[horizontal]
Duration:: Single use
Bonuses:: +25 for resuscitation-related procedures.
Wate:: 500gm
EXPS:: 1500
Value:: 3000

The breath ball is a temporary self-contained ventilation gas exchanger.
A conscious persona can stuff the ball into her ventilation orifice to breathe safely.
A vet can jam the breath ball into an unconscious persona's digestion orifice.
The ball will take over ventilation and oxygen exchange for many minutes. 
The ball will offer oxygen or carbon dioxide (florians) to the breathing persona.
The ball allows personas to breath underwater.
The breath ball also filters out respiratory poisons from the air. 
The ball basically will work for a few minutes to get the persona through a tight pinch.
This device does not act as long-term life support or protect against exatmo.

=== Cardio Vest 

[horizontal]
Duration:: Single use
Bonuses:: +25 for resuscitation-related procedures.
Wate:: 2.9kg 
EXPS:: 300
Value:: 1200

Any persona can put this vest on to regulate and monitor cardiac pump function.
The cardio vest can rhythmically contract to pump the heart and lungs and keep vital fluids moving, whether blood or sap.
The cardio vest will maintain the persona for a few hours to get to long-term life support.
In most circumstances, a cardio vest will synchronize and work in unison with an anesthetics mask.


=== Cerebro Converter 

[horizontal]
Duration:: Power Source
Bonuses:: +30 on consciousness rolls
Wate:: 1000kg
EXPS:: 10000
Value:: 11300000000

A cerebral converter can analyze and copy any organic storage device.
In most cases, this will be an anthro brain.
The information is converted to electrical storage and becomes transferrable.
The Cerebro converter can transfer consciousness from one brain to another.
Some of its uses include brainwashing, ultimate disguise, and immortality.

Consciousness transfer moves the emotions, memories, skills, and mental strength between organic brains.
The brain receiving the consciousness has its previous consciousness obliterated.
The body which the consciousness left becomes a vegetative husk.
The converted consciousness now lives in a new body.
The physical attributes of the new body do not change. 
AWE, CHA, CON, DEX, PSTR and HPS remain the same.
There is a new INT, MSTR, personality, memories, vocation and EXPS in the new brain. 

IMPORTANT: *These actions are both ethically dubious and medically dangerous.*

Cerebro conversion is a dangerous maneuver for the personas, players and the referee.
For the personas, there is a high chance of death, insanity, and mental loss.
The users must be aware that the cerebro converter is indiscriminate, and all knowledge (family life, loves, hates, gossip) transfers into the receiving brain.

Any procedure failure, like a power failure, interruption by combat, or a failed performance roll, will adversely affect the transfer.
The adverse effects of Cerebro conversion are drastic.
If properly exploited by the referee can translate into an endless source of fun.

.*Success Checklist*
. Donation Roll
. Performance Roll
. Malfunction Roll
 
==== Donation Roll
The donor consciousness is transferring into the receiver's brain. 
The receiver brain consciousness is fighting for its existence.
The more powerful the receiver's consciousness, the more difficult it is to wipe.
If there is a donation failure, the veterinarian must still make her performance roll.

==== Chance of Donation Success
.(INT + MSTR of donor) / (INT + MSTR + LVL receiver)
****
Chance = (9 INT + 6 MSTR) / (9 INT + 9 MSTR + LVL 3) +
Chance = (9 + 6) / (9 + 9 + 3) = 15 / 21 = 71%
****

==== Performance Roll
For the cerebral conversion to be a success,  a vet must also win a performance roll.
If the donation is successful, the vet can still mess up the procedure.
It is strongly recommended to build a xref:i-roll_playing_rules:CH14_Performance_Tables.adoc#_research_teams[Research Team,window=_blank] when using a cerebro converter.

The difficulty of the performance roll depends on the tech level of the cerebro converter and the type of donation the vet is doing.
A typical cerebro converter will be tech level ten.
Transferring a donor to another anthro is 25DD, and transferring a donor into storage (organic or inorganic) is 30DD.
Higher tech level cerebro converters decrease the degree of difficulty and allow for more elaborate conversions. 

==== Malfunction Roll
The cerebro converter has a chance of breaking down under the duress of a conversion.
The chance of machine failure and damage is 1/2% per DD of maneuver.
So if the degree of difficulty is 20, there is a 10% chance of machine malfunction.
If there is a mechanic on the research team, she can prevent malfunction by winning a performance roll set to the conversion's DD.
Jump to xref:i-roll_playing_rules:CH21_Artifact_Damage.adoc#_extent_of_damage[Equipment Damage,window=_blank]. 
If the machine suffers critical damage or is destroyed, the conversion is a failure.

==== Failures 
A cerebro conversion failure can lead to side effects like insanity and death.
A failure at any step (donation, performance or malfunction) prevents conversion.
A conversion failure may result in a side effect. 

If the donation fails, the veterinarian must win her performance roll to prevent a side effect.
If the machine malfunctions, the mechanic must win her performance roll to prevent a side effect.

If the donation was successful, but the vet lost her performance roll, there is no side effect.
If the donation was successful, but there was a machine malfunction, there is a side effect.

include::ROOT:partial$CH47_Table_Cerebro_Converter_Side_Effects.adoc[]

Confluence::
Confluence is the mixing of two consciousnesses in the same physical space. 
The donor consciousness does not thoroughly wipe the receiver consciousness, and a confusing confluence of the two occurs. 
Whichever consciousness has the higher mental strength tends to dominate the vessel.
However, the less powerful consciousness (lower mental strength) can regain control during experiences in tune with that persona.
If the consciousness were a mercenary, a combat experience would be a time to rise to the surface.
Confluence is an excellent story propelling tool. 

Death::
Death by cerebro converter is the result of wiping too much from the receiver brain or storage medium.
The consciousness converts into a  dead body and is lost. 
Death is the most dangerous possible side effect of the cerebro converter.
The player of the donor consciousness gets a saving roll versus a mental attack or dies.
The intensity of the mental attack is equal to the DD of the maneuver.
If the player fails her saving roll, the cerebro converter creates one vegetative husk and one lifeless husk.

Insanity::
The conversion is a failure, and both consciousnesses now have insanity.
Insanities in EXP are persona performance irritations and not mundane terran mental illnesses.
Jump to xref:i-roll_playing_rules:CH11_Referee_Personas_Anthro.adoc#_introverted[mild insanity,window=_blank] for some inspiration.

Mind Blank::
The conversion is a failure, and both consciousnesses are at risk of mind blanking.
Mind blanking removes all memories, skills and EXPS.
The blanking most often afflicts brains, but robots, AIs and storage mediums can suffer blanking.
Each consciousness must win a mental attack roll against the DD of the conversion or lose all EXPS and skills.
If a player persona suffers mind blanking, the referee will usually have the fugue last for a specific amount of time.
Memories slowly returning is an excellent opportunity for some storytelling.

Mental Mutation:: 
The cerebro conversion fails, and both personas suffer a defective mental mutation.
The persona must win a mental attack roll or suffer a xref:v-wetware:CH58_Mental.adoc#_defective_mutations[Defective Mental Mutation,window=_blank].
The intensity of the mental attack is the same as the DD of the maneuver.

==== Less Failure Through Science
The higher the tech level of the cerebro converter, the more dependable the artifact's function.
The lower the converter's wate, the higher its tech level.
The impacts of tech level on artifacts is cover in xref:iv-software:CH56_Tech_Level.adoc[Tech Level,window=_blank].

A typical cerebro converter will be tech level ten.
Transferring a donor to another anthro is 25DD, and transferring a donor into storage (organic or inorganic) is 30DD.

include::ROOT:partial$CH47_Table_Cerebro_Converter_and_Tech_Level_(TL).adoc[]

=== Cloning Equipment 

[horizontal]
Duration:: Power Source
Bonuses:: +20 on cloning related rolls
Wate:: 2500kg
EXPS:: 25000
Value:: 5000000000

Cloning Equipment functions like a biologic printer building an exact organic replica.
The clone is a verbatim cellular construct, an autonomous statue with matching meats and ligaments.
However, cloning does not transfer the consciousness of the source. 
The new clone body lacks the personality, mental strength and training of the source brain.
The clone copies the cellular maturity, but not the vocation or experience.
The sample has no control over the clone.
The clone cannot speak and usually becomes a referee persona.

WARNING: *Successful cloning does not copy consciousness.*

To copy a consciousness into a clone requires a <<_cerebro_converter,cerebro converter>>.

.*Success Checklist*
. Sample Size
. Performance Roll
. Malfunction Roll

==== Sample Size
The more advanced the cloning equipment, the less of a sample is needed.
A low-tech cloning machine needs to have a living body present for the entire process.
Low tech cloning is very time-consuming and dangerous for the living sample.
A high-tech cloning machine only needs a small chunk of the sample present.
The typical cloning machine is tech level ten and needs a living copy for a sample.
Cloning cannot proceed unless the necessary sample size is available.

==== Performance Roll
For cloning to be a success,  a vet must win a performance roll.
The difficulty of the performance roll depends on the tech level of the cloning equipment.
Typically cloning equipment is tech level ten, and cloning is a 20DD maneuver.
Higher tech level cloning equipment decreases the degree of difficulty of cloning. 
It is strongly recommended to build a xref:i-roll_playing_rules:CH14_Performance_Tables.adoc#_research_teams[Research Team,window=_blank] when using cloning equipment.

==== Cloning Duration
The cloning process takes one day per degree of difficulty.
For example, a 20 DD clone takes 20 days to brew.
Brewing a clone has a biblical minimum of seven days.
Speeding up the cloning process increases the chance of failure.
Each day that the clone brewing is sped up increases the DD by one.
Speeding up a 20 day clone brew to a ten-day clone brew creates a 30DD maneuver.

==== Malfunction Roll
The cloning equipment has a chance of breaking down under the complex process of cloning.
The chance of machine failure is 1% per DD of maneuver.
So if the degree of difficulty is 20, there is a 20% chance of machine malfunction.
If there is a mechanic on the research team, she can prevent malfunction by winning a performance roll set to the conversion's DD.
Jump to xref:i-roll_playing_rules:CH21_Artifact_Damage.adoc#_extent_of_damage[Equipment Damage,window=_blank]. 
If the machine suffers major damage or worse, the cloning is a failure.

==== Results of Failure
Most often, a clone brew will fail catastrophically.
The tank will contain a jumbling blob of bones, tubes, organs and rumpled skin.

include::ROOT:partial$CH47_Table_Cloning_Machine_and_Tech_Level.adoc[]

=== Coma Control Box 

[horizontal]
Duration:: 25 Days per Battery
Bonuses:: +20 for consciousness rolls
Wate:: 5kg + Battery
EXPS:: 500
Value:: 7000

A coma control box will stabilize an unconscious persona and prevent their death.
Only anthro personas suffer the comatose dying state that this device prevents.
A coma control unit does not heal the persona but freezes their hit points at a negative number.
The coma control unit only halts hit point decline below zero.
The device has no impact on the effects of poisons or pharmaceuticals.
The coma control unit does not prevent further damage from additional attacks.
The device is self-attaching, but detachment requires a biologist, mechanic, or veterinarian.
A veterinarian must resuscitate the person when the device is removed.

=== Comfy Couch 

[horizontal]
Duration:: 15 Days per Battery
Bonuses:: +10 for stablization rolls
Wate:: 70kg + attachments + Battery
EXPS:: 700 + attachments
Value:: 15000 + attachments

A comfy couch is a mobile medical bed stocked with medical attachments.
The comfy couch uses antigrav instead of a mattress, safely supporting the patient.
The bed can carry up to 300kg, but only one patient at a time. 
The couch easily moves around at a maximum speed of 3 h/u.

A comfy couch uses antigrav to support the patient but is not automatically an antigrav stretcher.
The comfy couch may still have wheels. 
The comfy couch does not carry inorganic artifacts and does not like being used as a sled. 

A comfy couch may have built-in veterinary equipment to complement vet care.
The attachments automatically start working on the patient it is supporting.
Every couch gets 0-3 (d4-1) on the Attachments Table.
These additional artifacts add to the wate, EXP and value to the comfy couch.

The comfy couch has the nickname porter plus.

include::ROOT:partial$CH47_Table_Comfy_Couch_Attachments.adoc[]

=== Consciousness Headband 

[horizontal]
Duration:: 20 uses 
Bonuses:: +20 on consciousness rolls
Wate:: 200gm no battery
EXPS:: 200
Value:: 50000

This headband keeps organic lifeforms conscious in the face of overwhelming odds.
The headband can counter anything that would render a persona unconscious.
The headband jump-starts the limbic system before it can fail.
The persona must wear the headband constantly to prevent loss of consciousness.
The device cannot jump-start an already unconscious brain.
Each use will inflict 0-5 (1d6-1) hit points of electrical damage to the persona.

The unit is self-contained and disposable.

=== Cauterizing Ray 

[horizontal]
Duration:: 20 units per Battery
Bonuses:: +20 for bleeding related rolls
Wate:: 3kg
EXPS:: 1002
Value:: 220000

The cauterizing ray expertly seals openings that leak vital fluids.
The vital fluids can be blood, sap or whatever goo the anthro circulates.
The device assists a vet on both external and internal uses.
Each use burns through 1 unit of battery storage.

Weaponizing this device yields unpredictable results.
A successful attack roll inflicts 2-12 (2d6) hit points of damage.
There is a 1% chance per hit point of damage of inflicting enduring damage.
Enduring damage is immune to rapid healing by regeneration, quick fixes, and pharma heals.
Enduring damage from a cauterizing ray must wait until after combat for the attention of a veterinarian.
Each attack drains five units of battery power.
Four attacks would drain a full battery.

=== Hearing Headphones 

[horizontal]
Duration:: Unlimited
Bonuses:: Special
Wate:: 1.2kg
EXPS:: 275
Value:: 90000

These headphones allow any hearing-impaired persona to hear normally.
The device is weather resilient but does not work underwater or exatmo.
The headphones are acoustically powered and do not require batteries.
This device does not work for inorganic personas or machines.
The persona enjoys +2 AWE for hearing-based maneuvers while wearing the headphones.
Such maneuvers include safe cracking, detecting ambush, machine repairs. 
When being worn for enhancement, sonic attacks inflict double damage to the persona.

=== Drug Analyzer 

[horizontal]
Duration:: 20 analyses per Battery
Bonuses:: +25 on pharmacologic maneuvers
Wate:: 10kg + Battery
EXPS:: 250
Value:: 50000

The drug analyzer is a somewhat portable pharmacological analyzer.
The analyzer assists a vet in analyzing a sample to identify it.
The machine determines the type, effects, duration, side effects, and value of pharmaceuticals.
It can also identify poisons and toxins.

The analyzer prefers a full dose of the pharmaceutical to use for study.
The analysis is destructive and consumes the entire dose.
The data can be printed out or screened out depending on the milieu.
A drug analyzer will store a molecular copy of the sample, allowing for future reproduction of the analyzed drug.
A drug analyzer does not fabricate pharma.

The degree of difficulty for the performance roll depends on the tech level of the drug analyzer.
Successful interpretation requires a vet performance roll win.
It is strongly recommended to build a xref:i-roll_playing_rules:CH14_Performance_Tables.adoc#_research_teams[Research Team,window=_blank] when using analyzing drugs.

=== Drug analysis Degree of Difficulty
.DD = 42 - Analyzer Tech Level
****
DD = 42 - Tech level 10 = 42 - 10 = 32
****

The time taken to analyze a sample is story-related. 
Ideally, the duration of the analysis will be the most exciting duration possible.

:art: pharma_box.png
:width: 350px
:snark: A box of vet stuff.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Open container full of medical type stuff. 

include::ROOT:partial$articulate.adoc[]

=== Drug Box 

[horizontal]
Duration:: 5 doses per Battery
Bonuses:: +42 on pharmacologic rolls
Wate:: 35kg + Battery
EXPS:: 900
Value:: 900000

A drug box fabricates pharmaceuticals like a pharmacy in a drum.
The box comes with a random and limited list of supplies.
There is no limit to the number of pharmaceuticals the drug box can learn.
The drug box does *not* analyze and copy meds.
The drug box is not a pharmaceutical photocopier. 
To add a new prescription requires a drug analyzer or a veterinarian. 

Successful fabrication of a pharmaceutical does not require a veterinarian.
However, a veterinarian's input decreases the chance of adverse effects.

xref:i-roll_playing_rules:CH14_Performance_Tables.adoc#_research_teams[Research Teams] may be required for fancy rare medications.
The difficulty of the maneuver depends on the chance of adverse effects.

==== Existing Prescriptions
A drug box may come with some existing prescriptions that it is ready to fabricate.
The drug box has 0-3 (1d4-1) rolls on the Starting Pharma Table.
There will be 1-10 (1d10) doses of each pharma type.

include::ROOT:partial$CH47_Table_Drug_Box_Start.adoc[]

==== A Nice Pairing
There is a slight chance that a drug box will have a <<_drug_analyzer,Drug Analyzer>> built-in.
The chance of this nice pairing is 1% per tech level of drug box
A tech level 12 drug box has a 12% of being combined with a drug analyzer.
The drug analyzer increases the wate and value of the drug box.
The multi-tool will come with *no* existing prescriptions if the drug box and drug analyzer are combined.

==== Duration
Fabricating a pharmaceutical takes 1-8 (1d8) hours per dose.
Ideally, the duration of the fabrication will be the most exciting duration possible.

=== Eye Cleanser

[horizontal]
Duration:: Single Use
Bonuses:: +10 on eye related rolls
Wate:: 150gms
EXPS:: 250
Value:: 3000

The eye cleanser looks like a set of oversized opaque swimming goggles.
When strapped over the eyes, they foam up and bathe the eyes in healing chemicals.
They will negate and heal all forms of physical damage to anthro optical sensors.
The goggles also heal and hit points of damage inflicted via eye damage.
The treatment is fast, and the persona is back to normal in 1-4 (1d4) units.

=== Fever Control Blanket 

[horizontal]
Duration:: Single Use
Bonuses:: +10 on metabolism rolls
Wate:: 50gms
EXPS:: 50
Value:: 150

The fever control blanket maintains the proper body temperature of anthro personas.
The artifact looks like a fragile, highly reflective, translucent sheet.
The blanket can counter any conditions (poison, sickness, mental attack) causing fever.
The blanket can maintain normothermia within air temperatures of -10C and +50C.
The fever control blanket is well-loved by nomads as well as vets.

The blanket will function until it is damaged.
The blanket is delicate, and a mere three hit points of damage destroys it.
A fever control blanket is disposable and is disposable.

=== Incubator 

[horizontal]
Duration:: Power Source
Bonuses:: +20 on any growth related rolls
Wate:: 100kg + vat size
EXPS:: 300
Value:: 250000

The incubator creates the environment and conditions necessary for gestation.
Anything embryonic will flourish inside this tank. 
Embryonic includes nascent clones, embryos, seeds, hyphae, etc.
All organics are grown to survive outside of the womb, seed or spore sack.
The incubator requires a vet or biologist to operate. 
A nomad can also use an incubator to grow plants quickly.

include::ROOT:partial$CH47_Table_Incubation_Times.adoc[]

When combined with a cloning tank, the incubator can safely speed up clone growth.

=== Injury Detector 

[horizontal]
Duration:: 100 uses per Battery
Bonuses:: +50 on injury related rolls
Wate:: 2.5kg
EXPS:: 2500
Value:: 100000

This handy little box analyzes organic personas for injury.
The injury detector buzzes for any trauma from ligament strains to rigour mortis.
The detector does not make an exact diagnosis but guides the vet to better treatment.

:art: danger_in_deep_big_screen.png
:width: 450px
:snark: Big screen diagnostic computer
:artist: Louis Glanzman
:date: 1953
:license: CC BY-SA 4.0
:description: Drawing of scientist people standing in front of gigantic computer screen.

include::ROOT:partial$articulate.adoc[]

=== Internal Viewer 

[horizontal]
Duration:: Power Source
Bonuses:: +30 on all vet maneuvers
Wate:: 55kg
EXPS:: 3000
Value:: 950000

This device gives a three-dimensional, technicolour, moving picture of the innards of organic personas.
The paddles of the internal viewer must make contact with the patient.
The internal views can be recorded and subjected to a host of special effects.

=== Life Ray 

[horizontal]
Duration:: Power Source
Bonuses:: Nil
Wate:: 1250kg
EXPS:: 10000
Value:: 22100010042

A life ray will resurrect dead organic tissue into a living state.
Enormous energy surges (like lightning) are used to rehydrate desiccated cells, restore chemical equilibriums, and rebalance biological polarities.
The Life Ray is a machine, and the deceased must be within it.

The Life Ray only works within 42 hours of death.
The life ray will faithfully revitalize the sample placed within it.
The ray does not heal or repair the body.
The team must complete life-saving surgery before activating the life ray.
For instance, a vet must reattach an amputated limb before restoration.

To properly operate the life ray requires a successful performance roll.
The difficulty is 1 DD per hour since the death. 
For example, a patient that has been dead for 6 hours would be a DD6 maneuver.

The life ray is not a healing device. 
The persona will be restored to zero HPS and regain consciousness.
Missing limbs do not grow back. 
Attributes do not recover, pain continues, and limbs do not grow back.

The life ray cannot restore a persona with a zeroed attribute.
So a persona who has zero physical strength is permanently dead.
Charisma is the only attribute that can drop below zero.

Death leads to decrepitude. 
The death experience damages every attribute.
A rebooted persona suffers the following attribute penalties.
AWE, CHA, CON, DEX, INT, PSTR and HPS maximum will lose 0 to 3 points (d4-1).
If the persona zeroes one of her attributes during a life ray treatment, she is permanently dead.
The life ray is far from perfect, and personas who keep dying will eventually die.

There is a chance that the death experience will improve a persona's mental strength.
The first time the life ray resurrects a persona, her mental strength may increase by 0-3 (1d4-1).
Further life ray treatments may decrease or increase the persona's mental strength by adding -1 to +1 (1d-2) points.

=== Limb Capper 

[horizontal]
Duration:: Single Use
Bonuses:: +5 on tissue preservation rolls
Wate:: 150gms
EXPS:: 50  
Value:: 200

A limb capper consists of a flexible bowl-shaped bio-bandage stored in a convenient bag.
Due to legacy and convention, the storage bag is 'crinkly.'
The capper moulds itself onto any sized stump. 
The amputated part fits into the limb capper's crinkly bag.
The capper preserves nerve endings, tendons, and muscles of amputations for reinsertion.
The crinkly bag keeps the amputation ready for reimplantation for several days.

The limb capper is a common artifact in milieus frequented by knites.
As an aside, the crinkly bag will store a sandwich indefinitely.

=== Vedi Kit 

[horizontal]
Duration:: Single Use
Bonuses:: +20 on healing rolls
Wate:: 200gms
EXPS:: 100
Value:: 215

The vedi kit (veterinarian medical kit) is a disposable single-use tool kit for making quick fixes.
The quick fix is a temporary healing maneuver best done by veterinarians.
The kit contains bioelectric painkillers, tissue adhesives, cutting acids, spray-on bandages, and fur remover.
For sanity reasons, vedi kits melt into useless blobs after use.
Vedi kits are also called medi kits, med packs, veti kits and first aid kits.
When found in the field, there will usually be 1-6 vedi kits. 

=== Vedi Wrap

[horizontal]
Duration:: Single Use
Bonuses:: +20 on healing rolls
Wate:: 100gms
EXPS:: 100
Value:: 3000

A vedi wrap is a patch of self-adhering synthetic skin that melts onto injured skin.
The wrap can be easily applied to obvious wounds by personas of any vocation. 
Once applied, the wrap's effect is immediate, and the wrap prevents any further damage.
The wrap will heal up to 30 hit points of specific skin damage.

include::ROOT:partial$CH47_Table_Medi_Wrap_Type.adoc[]

Veterinarians can extend the use of a vedi wrap by winning performance rolls.
A veterinarian can extend a vedi wrap to cover multiple wounds allowing one vedi wrap multiple uses.
Extending a vedi wrap is 3DD per extension (3DD then 6DD then 9DD).

Veterinarians can extend a vedi wrap to heal different injury types.
A thermal burn vedi wrap could heal a chemical burn.
This a 3DD maneuver.

NOTE: *A vedi wrap is not a veggie wrap and is not edible.*

Vedi wraps are also called medi wraps, med packs, plasters, veti wraps and first aid wraps.


=== Vedical Kit 

[horizontal]
Duration:: 42 uses.
Bonuses:: +42 emergency rolls
Wate:: 10kg
EXPS:: 2000
Value:: 500000

The vedical kit (veterinarian medical kit)combines a simple diagnostic computer and a pile of medical supplies.
The vedical kit is not an autonomous device but assists any persona in making quick fixes.
The quick fix is a temporary healing maneuver best done by veterinarians.
Other persona vocations can use a vedical kit, but they can only do quick fixes and get no bonuses.
Vets enjoy a +42 bonus on any acute care maneuvers (quick fixes, poison cures, etc.).
The diagnostic computer runs out of power, and the stores run out of materials after 42 uses.
Recharging a medical kit is left to the improvisational talents of the referee.

A vedical kit is also called a medical kit, trauma box or fist aid machine.

=== Metab Counter 

[horizontal]
Duration:: Unlimited 
Bonuses:: +10 all vet and biologist rolls
Wate:: 1kg
EXPS:: 300
Value:: 25000

A metab counter graphically monitors respiration, blood flow, brain activity, and other useless metabolic indicators.
The metab counter is the classic futuristic physician's stethoscope.
This device has a ten hex point and snoop range.
Vets and biologists can use the metab counter to locate life forms and determine their health.


=== Mood Ball 

[horizontal]
Duration:: Unlimited
Bonuses:: +20 in emotion related rolls
Wate:: 2.1kg
EXPS:: 300
Value:: 25000

The mood ball will balance and maintain the disposition of the persona holding it.
If they are depressed, it will make them happy. 
If they get angry, it will calm them down.
The mood ball is a psychiatric device that employs electrical signals and inaudible sounds to maintain socially acceptable behaviours from the user.
The mood ball is not a mind-control device.
The user is aware that she is employing the ball for her benefit since they will be genuinely happier when the ball is activated.

A persona that frequently uses the emotional adjustments of the mood ball may become dependant on the device.
The mood ball cannot be used to negate reasonable emotions but may make them more tolerable.

=== Mutation Detector 

[horizontal]
Duration:: Unlimited
Bonuses:: +25 on mutation related rolls
Wate:: 1kg
EXPS:: 300
Value:: 25000

This handy little box analyzes personas to detect mutations.
There is one light for physical mutations and one light for mental mutations.
This device does not detect the evolved powers of aliens or the mutation-like effects of robots.
If the alien has a mutation, then the detector will sound off.

If a target has physical and mental mutations, both lights sound off.
The detector does not reveal anything about the nature of the mutation.
A mutation detector has a next hex range and does not work through obstructions.

=== Neuro Cap 

[horizontal]
Duration:: Unlimited
Bonuses:: Nil
Wate:: 80gm
EXPS:: 200
Value:: 90000

The cap generates a think space interference that prevents psionic intrusion.
The device looks like an oversized beanie with a blinking light on top.
The neuro cap will not defend against mental attacks that manipulate the environment.
For example, cryokinesis and life leech don't pass through the think space to work.
However, ESP and mental control pass through the thinkspace, and the neuro cap works on them.
A  neuro cap is just a machine and offers no other benefits to the persona wearing it. 

Mental attacks must win a roll against the persona's doubled mental strength.
The mental defence of the neuro cap has a minimum MSTR of 20.
A persona with a 15 MSTR would have a psionic barrier of 30.
If the mental attack passes the neuro cap's psionic barrier, the persona still gets a save versus a mental attack.
The neuro cap will also block any mental mutation that the persona attempts to emit.

=== Poison Detector 

[horizontal]
Duration:: Unlimited
Bonuses:: +15 on poison related rolls
Wate:: 1kg
EXPS:: 300
Value:: 25000

This handy little box detects poisonous compounds. 
The poison detector has a two hex range.
There are a few lights and a scale.
The scale indicates how dangerous the poison is.
The danger is related to the intensity, but the player does not learn the exact intensity of the poison.
The detector can also differentiate between radiation, chemical or biological poisons.

Nomads and biologists can use the device to assess a poison risk.
A vet can use the device to assist with treating toxic patients.

=== Poison Box 

[horizontal]
Duration:: 15 treatments per Battery
Bonuses:: +42 for poison related rolls
Wate:: 20kg
EXPS:: 1984 
Value:: 62036049

A poison box can synthesize an antidote from a sample of a poison. 
If there is no antidote to the poison, the box acts as a resource for veterinarians. 
The poison box has no range, and it requires a toxin sample.
Treatment can be either an antidote or a performance roll bonus for the vet.

Synthesis of antidote requires 1 to 8 hours of battery use.
This duration of synthesis often means that an initial poisoning will not have an antidote in time.
An antidote doubles the persona's constitution for poison saving rolls.
An antidote or treatment has no effect if the persona is already dead.

Reconfiguring a poison box to make poison is very hard and quite likely will destroy the machine.
Creating a poison box would require a research team and is at least a 42DD maneuver. 
A failed attempt at reconfiguring a poison box for nefarious purposes would permanently damage the device.

=== Psionic Box 

[horizontal]
Duration:: 200 units per Battery
Bonuses:: +42 for psionic related rolls
Wate:: 20kg
EXPS:: 1984
Value:: 129036049

The psionic box is like a stethoscope for the think space.
The device contains materials, generators and detectors that measure interactions between consciousness and the thinkspace.
The box is an elaborate detector that will betray the presence of any mental mutations (but not physical mutations) or manipulations of a psionic nature.
The veterinarian can use the psionic box to probe the local area for a psionic anomaly.

For instance, a veterinarian could use the psionic box to eavesdrop on telepathic conversations or generate simplistic psionic signals.

Attaching the psionic box to a mutant's scalp can deduce a mental mutation's effects.
The psionic box would reveal the ability to manipulate time and not a diagnosis called Time Stop.
The mutant can defend against the intrusion by winning a mental attack of intensity 4-24 (4d6).
The level of the veterinarian making the assessment is added to the intensity, increasing her chances of success.
The probing takes 1 to 100 units of melodramatic agony.
If the mutant fails their saving roll, the veterinarian must win a 12DD to detect the mutation type (16DD for biologists).
The psionic box can combine with a Cerebro converter to search the target's mind like a https://en.wikipedia.org/wiki/Rolodex[roll-a-dex].

=== Phenotype Detector

[horizontal]
Duration:: Unlimited
Bonuses:: +15 for type related rolls
Wate:: 2.1kg
EXPS:: 300
Value:: 25000

This handy little box helps detect the taxonomy of organic personas. 
The detector works on deceased specimens as well.

EXP has a sciency fiction taxonomy to separate the three families.
Jump to xref:i-roll_playing_rules:CH04__Families.adoc[Families,window=_blank] for more info.
The family level reading will be Hominidae (anthros), diversidae (aliens), or inorganic.
The genus-level reading for anthros is homo.
The species-level reading for anthros is the anthro type.
Anthro types are Avis (avarian), Canis (canine), Felis (feline), etcetera.
An aquarian would register as Hominidae Homo Pisces.
The subspecies would be its appearance shark, goldfish, or octopus.

The genus-level reading for alien depends on what the referee named it.
Brand new aliens can be registered and cross-referenced to other registered aliens. 
This detector allows a biologist to build a menagerie of sciency fiction names.
The famous sandworm from https://en.wikipedia.org/wiki/Sandworms_of_Dune[Arrakis] would register as Diversidae Lumbricalis Arrakis Humongous.
Later the sandworm may be renamed Diversidae Lumbricalis Arrakis Melange.
A phenotype detector can add a tremendous amount of work for the referee.

=== Rejuv Chamber 

[horizontal]
Duration:: Power Source
Bonuses:: +42 on healing rolls
Wate:: 333kg
EXPS:: 2000
Value:: 210000042

The rejuv chamber is a technomagical device that repairs damaged organic personas.
A rejuv chamber is the classic sciency fiction fluid-filled tank where the injured are submerged to heal. 
This artifact does *not* restore life to the dead and does *not* grow back missing limbs.
A deceased persona will only clog up a rejuv chamber. 
The rejuv will remove bullets, replace burned skin, set bones, excise tumours, drain swellings, trephine a skull, fix blood chemistry, filter toxins, and groom the patient's hair, nails and skin.
After a stint in a rejuv chamber, the patient will feel refreshed, clean, and alive.
Some personas use the device as a personal groomer.

The chamber does *not* resurrect deceased personas.
Nor does the chamber restore missing limbs.
The chamber does restore hit points and attribute values.
The rejuv chamber can repair AWE, CHA CON, DEX, PSTR and HPS Total.
The rejuv chamber cannot repair INT, MSTR or HPS Max. 
If an attribute drops below one (except CHA and HPS Total), the persona is irrevocably dead.

To have a safe rejuv chamber experience, the vet must win a performance roll.
The degree of difficulty of the maneuver is 1 DD per point of rejuvenation.
So repairing 10 HPS would be a 10 DD maneuver, and fixing 1 PSTR point is a 1DD maneuver. 
xref:i-roll_playing_rules:CH14_Performance_Tables.adoc#_research_teams[Research Teams,window=_blank] are recommended when running a rejuv chamber.

Vet failure will result in the removal of one point from one attribute to repair another. 
The rejuv chamber robs Peter to pay Paul. 
Instead of growing fresh tissue, the chamber moves tissue around instead.
A failure by the research team leads to the persona loses an attribute to undertake the rejuvenation.

If the vet loses her 20 DD performance roll, the patient loses 1 point off a random attribute and returns to full health. 
Regardless of what requires rejuvenation, the patient only loses on attribute point.
The attribute reduced is randomly determined.

include::ROOT:partial$CH47_Table_Rejuv_Damage.adoc[]

Only treatments that need point restoration can harm the patient.
Treating parasites, diseases, poisons, tumours, and pharma side effects will not damage the persona.
At full health, a persona can get a fabulous manicure and hair doo without risk.

Treatment duration depends on what requires rejuvenation. 
A patient healing 20 HPS would require 20 hours in the machine.
A patient undergoing an 8DD maneuver would require 8 hours in the machine.
Vets can speed up the process by increasing the degree of difficulty of the maneuver.
The rejuv chamber does not work like a stasis bag and ejects personas when the treatment finishes. 

:art: omnilingual.png
:width: 450px
:snark: BIPAP for biohazard
:artist: Kelly Freas
:date: 1957
:license: CC BY-SA 4.0
:description: Drawing of woman wearing oxygen mask standing in front of skyscraper ruins.

include::ROOT:partial$articulate.adoc[]

=== Respirator 

[horizontal]
Duration:: 5 hours per Battery
Bonuses:: +15 on breathing rolls
Wate:: 2.5kg
EXPS:: 500
Value:: 50000

A Respirator will monitor, regulate and maintain respiration in organic personas.
For example, the respirator moves carbon dioxide for florians and oxygen for canines.
The device snuggles over the mouth and nose.
It appears like a half-face, rounded scuba mask.

If any breathing irregularities arise, the respirator will take over. 
The device will filter out toxic substances in the air but does not have an air supply.
It protects the persona from toxic air but is not usable underwater.

:art: laser_scalpel.png
:width: 350px
:snark: Smoking edge of the blade
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of pen shaped device cutting skin with lazer beam.

include::ROOT:partial$articulate.adoc[]

=== Scalpel 

[horizontal]
Duration:: 300 units per Battery
Bonuses:: +15 on fleshy rolls
Wate:: 100gm
EXPS:: 200
Value:: 1500

This scalpel is a blade-less finely adjustable surgical flesh cutting device.
A scalpel will easily cut through any organic covering.
Most often, the device is lazer based, but the scalpel could also be sonic-based.
Choose which style is best for the milieu.

Weaponizing this device yields unpredictable results.
Each attack drains 30 units of battery power.
Ten attacks would drain a full battery.
It attacks as a type A weapon but has no PSTR bonus.
A successful attack roll will inflict 2-12 (2d6) hit points of cutting damage.

A treatment with this device used 1-20 units of battery.
Often this artifact is referred to as a lazer scalpel.

=== Stasis Bag 

[horizontal]
Duration:: Single use.
Bonuses:: Nil
Wate:: 300gm
EXPS:: 200
Value:: 1500

The stasis bag is the body bag of the future.
The stasis bag suspends all organic processes, especially one like decomposition.
Stasis means that there is no decomposition, no need for respiration, and no need for food.
The stasis bag will suspend any organic material in a steady state: lunches, bodies, limbs, eyes for the eye bank, and even whole unconscious organisms.
The auto-embalmer cannot hold an unwilling occupant, and anyone could thrash their way out of the thin opaque bag.
Stasis bags can be any colour, but they are always opaque. 

One bag can hold 150 kg.
Only one type of organic material per bag is allowed. 
Two canines would be acceptable.
A canine and turnips would not.
A stasis bag requires an atmosphere and a temperature between -80C and +80C.
The bag does not work exatmo.

A vet, biologist or mechanic must properly open a stasis bag.
The player must win a 5 DD performance roll of the contents rapidly spoil. 
Spoiled contents are dead and suffer accelerated aromatic decomposition.
Failure when opening a stasis bag from long-term storage can lead to explosive spoiling.
Explosive spoiling does not inflict damage but results in a grenade of grossness.
A stasis bag has a 1% chance per year of storage of explosive spoiling.

Larger bags increase in value (+1000 ) and wate (+200 gm) for every additional 150 kg of capacity.

=== Touch Gloves 

[horizontal]
Duration:: Single use.
Bonuses:: +20 for touch-related rolls
Wate:: 2gm
EXPS:: 360
Value:: 25000

Touch gloves are medical safety gloves that also enhance the sense of touch.
They appear as surgical gloves with visible circuitry and maybe a blinking light.
When worn, they melt into the skin, accentuating the persona's digital sense of touch.
This hypersensitive touch is so clear that the user can almost feel air molecules careening off her fingertips.

Typically a vet will remove the gloves after completing a  delicate maneuver.
If the persona does not remove the gloves, they wear off in 1-4(1d4) days.

Touch gloves improve the persona's awareness. 
There is a general bonus of +1 AWE. 
There is an additional bonus of +2 AWE when making touch-related rolls.
Mechanics can use the bonus for delicate repairs.
Spies can use the bonus for picking pockets or opening locks.
Pilots and drivers can use the bonus for driving rolls.

=== Translinker 

[horizontal]
Duration:: Self powered
Bonuses:: +42 with connected device
Wate:: 200gms
EXPS:: 750
Value:: 1000000

The translinker is a bidirectional neuro machine interface.
The translinker will allow a persona to directly interface with a piece of equipment, controlling it as an extension of her mind.
The equipment must be more complex than a simple machine and contain electronics and computers for a translinker to connect.
The translinker could not attach to a vedi-kit or a pistol.
But it may connect to a medical kit or a fancy scope.

The translinker allows her to visualize the device's data as part of her memory structure and control the device's controls as part of her motor system.
The persona becomes one with the device.
The translinker would allow a vet to integrate herself with a rejuv chamber.
A translinker allows a mercenary to fire a piece of artillery.
A spie may gain insight into an electronic lock.
A mechanic to drive a space vehicle.
A translinker would allow virtual access to a computer's memory system.

If the persona translinks with consciousness containing machines like robots or AI, there is a risk of the inorganic controlling the organic.
The competition for control is up to the referee and depends on the machine's intelligence versus the persona's mental strength (not intelligence).

The persona may also become dependent on the translink device.
Frequent use, or abuse, may prevent the persona from disconnecting from the device.
If the persona fails a mental attack, she may prefer to view the world through the machine she translinks with rather than her senses.

The translinker's appearance depends on the referee's milieu and story.
There may be a socket in the skull, a tinfoil hat, a keyboard deck, a coily cord, or a nail that punches into the machine.

== Vet Equipment Parameters

=== Duration 
The duration parameter indicates how much use the persona can get from the artifact.
Single-use and disposable vet equipment improve patient hygiene and corporate profits.

Other devices have a time for their duration parameter, like 500 units, 25 hours or 10 kgs of flesh.
Each treatment depletes the duration by a set amount, and when the duration is all gone, the device needs new batteries.

=== Wate 
The wate of medical equipment is the functional wate of the artifact, excluding batteries.
Wate is also a proxy for tech level, where low tech level machines are bigger and heavier.

=== EXPS 
The experience point value is for the persona, or personas, who correctly identifies the device.
Identification can occur before or after the device is used.

=== Value 
The value parameter is how many electrum pieces the device is worth.
The value of a device may be priceless in certain situations of milieus.