= Pharmaceuticals

The pharmaceuticals described in this chapter are fantastic miracle substances capable of diagnosing, preparing, and administering the proper remedy.
They can do wonders, but they can also have deadly side effects.
Pharmaceuticals are found in groups of doses called a prescription.
A prescription may consist of pills, injections or liquids.
A prescription will normally have a negligible mass.
Overuse of a prescription may result in dependence to that specific pharmaceutical type.
Addiction to pharmaceuticals is very rare considering the vicious side effects that will ultimately accompany their use.


:art: drugs.png
:width: 250px
:snark: Say no to pharma
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of pills, tablets, inhaler, and liquid dropper.

include::ROOT:partial$articulate.adoc[]


.*Pharmaceutical Checklist*
. <<_pharmaceutical_type,Pharmaceutical Type>>
. <<_prescription,Prescription>>
.. <<_labelling,Labelling>>
.. <<_delivery_method,Delivery Method>>
.. <<_metabolism,Metabolism>>
.. <<_adverse_effects,Adverse Effects>>
.. <<_doses,Doses>>
. <<_pharmaceutical_attribute_explanations,Pharmaceutical Attribute Explanations>>

== Pharmaceutical Type

include::ROOT:partial$CH50_Table_Pharmaceutical_Type.adoc[]

== Pharmaceutical Types

=== Cures 

[horizontal]
Duration:: Until next time.
Safety:: 4
EXPS:: 100
Value:: Special

A cure is not an inoculation, and therefore does not reduce the chance of future contraction of an illness.
A cure will simply arrest the process of a disease, or poison, but it will not heal damage that has already happened.
Cures restore no damaged attributes, or reduced hit point totals.
Cures stop the affliction in its tracks and remove it from the persona.

include::ROOT:partial$CH50_Table_Cure_Type.adoc[]

Aging::
Reduces abnormal aging by 1-10 (1d10) years. 
If no abnormal aging present life span is increased by 10%.
Each time an aging cure is used to extend life span the safety level is halved.
Value is 250000 per dose.

Trauma::
Repairs any deficit to the persona's Hit Points Max.
This cure does not restore lost hit points. 
The trauma cure repairs a persona's hit points max that had been reduced by injury or aging 
If no hit points max deficit is present the persona's HPS Max is increased by 10%.
Each time a trauma cure is used to extend HPS Max the pharmaceutical's safety level is halved.
Value is 250000 per dose.

Infection::
Infection cure super charges the persona's immune system to remove any infectious invader.
This includes bacterial, viral, parasitic, prion or other sciency fiction infection.
This cure will remove multiple infections at once. 
Infection cure does not harm symbiotic infections like gut flora. 
Value is 50000 per dose.

Attribute::
The attribute cure can restore attributes decreased due to aging. 
A veterinarian can dial in which attribute is repaired with a 10 DD maneuver.
If there is no veterinarian delivering the pharma the cure will repair the last attribute decreased by 1 point.
This cure has no effect if there are no degraded attributes.
Value is 500000 per dose.

Psionics::
The psionics cure briefly disconnects the persona's consciousness from the think space.
This reset breaks off any undesired psionic controls being exercised on the persona.
For example if the persona was being mind controlled she would be freed from mind control for a few hours.
How long the cure keeps the mind control out is determined by the story. 
Value is 1000000 per dose.

Mutation::
This cure will remove the patient's most recent mutation. 
The cure does not discriminate and removes beneficial or defective mutations.
A veterinarian can dial in the cure to remove a particular mutation.
This requires a 20 DD manuever for success.
Value is 1000000 per dose.

Toxins::
Toxin cure arrests any poison or toxin from having ongoing effect on the persona.
This includes organic envenomization, poison gases, chemical exposures etc.
The cure does not reverse damage or repair a persona's hit points. 
If used against a killing poison the cure will leave the persona at -1 HPS total instead of being dead.
It is possible that this pharma's adverse effect may be the same as the poison it cures. 
That is just bad luck.
A veterinarian can use this cure to prevent poison damage with a successful 15DD maneuver per dose.
Value is 50000 per dose.

Radiation::
A rad cure removes any ongoing effects of radiation from the persona.
If taken early enough the cure can avoid damage from radiation as well.
How early is early enough? 
The persona would have to know that radiation damage is imminent. 
A veterinarian can use this cure to prevent radiation damage with a successful 15DD maneuver per dose.
Value is 50000 per dose.

Thermal::
A thermal cure returns organic flesh to it's original state after cold or heat damage.
The thermal cure does not heal hit points back but restores any permanent damage due to thermal injury.
The cure will also arrest any ongoing thermal damage from an active attack.  
Value is 50000 per dose.

Ubiquitous::
The ubiquitous cure must be dosed by a vet. 
The vet and persona can choose whatever they would like cured with this generic cure.
The vet must win a 10 DD manuever roll regardless of the cure attempted.
More difficult cures like curing a defective mutation or a mental illness would increase the DD.
Cures are not heals or inoculations and the ubiquitous cure is no different.
If an intense discussion were to arise regarding this pharma consult the xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice].
Value is 4200042 per dose.

Decomposition::
This cure will place a persona in a state of lethal stasis.
While the persona will not decompose they are also dead. 
There is no counter cure for this treatment. 
The persona must be revived by other veterinarian equipment. 
This cure has been previously called  "cured ham" or "poison apple."
Value is 250000 per dose.

=== DNA 

[horizontal]
Duration:: Until next time.
Safety:: 1
EXPS:: 1000
Value:: 2000000

DNA is a pharmaceutical capable of replacing lost limbs or organs, and reactivating non-functioning ones.
A dose of DNA activates the growth centers of remaining cells at the site of missing, or inactive, body parts.
The repair is accelerated, and will be complete in 10-100 (10d10) hours.
The DNA will replace any missing, damaged, or malfunctioning organ or limb, but it will be especially effective at replacing the part rolled on the table.
The repaired, or replaced, limb will resemble that of the metabolism type rolled for the drug.
For example an avarian may have an ursidae arm, but a perfectly good functioning one though.
The organ, or limb will function absolutely normally regardless of persona type, but there will be an obvious cosmetic effect.
A DNA dosage may also activate any previously nonfunctional body part--like a mutated extra ear, or limb.

Repairing amputated limbs is not all that common. 
Unless the campaign is full of limb chopping knites and anti-knites.
More commonly DNA will be misused to get interesting and occasionally useful body parts.

When using DNA on a persona containing all their body parts an immediate adverse effect is delivered.
There is a percent chance equal to the persona's CON that they will grow a random new body part.
The body part will be very random. 
It will most likely be cosmetic or vestigial.
There is a percent chance equal to the persona's DEX that she will be able to control the body part. 
So a persona with an  11 CON and and a 14 DEX has an 11% of growing something new and a 14% chance of controlling it.
A vet can dial in the misuse of this pharma to get desired parts.
This would be a 42DD maneuver and a xref:i-roll_playing_rules:CH14_Performance_Tables.adoc#_research_teams[Research Teams] is recommended.

.*Your DNA Checklist*
. DNA Type
. Metabolism
. Location

include::ROOT:partial$CH50_Table_DNA_Type.adoc[]

include::ROOT:partial$CH50_Table_Pharmaceutical_Intended__Metabolism.adoc[]

include::ROOT:partial$CH36_Table_Snap_Hit_Location.adoc[]

If the dice should guide the story to a robotic DNA body part it is easiest to have the persona grow a random peripheral. 
Robotic DNA attachments are a pathway to cybernetics.
The referee may feel that a vestigial robotic wheel sticking out of the persona's head is amusing she must be reminded of game balance and player enjoyment. 
Referees work for story and play balance and do not work directly against players. 

=== Narcotic 

[horizontal]
Duration:: Special
Safety:: 5
EXPS:: -42 (yes minus)
Value:: 42

Narcotics represent pharma that are intended for recreational use.
They may represent regular pharma that has gone sour.
The narcotics are not grouped by any name or class or mechanism of effect. 
In EXP narcotics do not offer insightful experiences that enhance mental strength.
There are other pharma that have such effects.

A narcotic has a 42 point EXPS penalty which permanently decreases the persona's EXPS total by a minute amount.
Narcotics also impair the persona's attributes.
While impaired AWE, DEX, and INT all suffer a 1-6 (1d6) penalty for the duration of the narcotic effect.
Since a persona is dead if any attribute is reduced to 0 the referee may limit the minimum attribute decrease to 1.
It is up to the referee whether or not a narcotic attribute reduction will kill the persona.
However narcotic misadventures regularly kill humans on terra.

Narcotics wreak havoc on the persona's mental strength.
A persona's MSTR is halved while under the effect of a narcotic.
Knites avoid any such excursions into the chaos of the mind.

include::ROOT:partial$CH50_Table_Narcotic_Effect_Duration.adoc[]

include::ROOT:partial$CH50_Table_Narcotic_Effect.adoc[]

=== Heal 

[horizontal]
Duration:: Until the next injury
Safety:: 7
EXPS:: 100
Value:: Special

Heals are pharmaceuticals that repair physically damaged tissues.
The majority of healing is for whole body hit point damage.
There are also heals that repair damaged attributes.

include::ROOT:partial$CH50_Table_Heal_Type.adoc[]

Hit Points Total::
The results of the healing process are reflected by a change in the persona's hit point total.
Heals do not alter the persona's hit point maximum, but will improve the present total.
So a persona with 40 out of 42 hit points will only heal to 42 hit points, and does not exceed their HPS Max.

include::ROOT:partial$CH50_Table_Hit_Points_HPS_Healed.adoc[]

.*Percent Heal* 
Heals that indicate a % hit point total work in the following fashion: they return the persona the given % of their hit point max.
So a persona with a HPS max of 50 using a 40% heal would immediately be raised to 20 hit points.
If the persona has more than 20 hit points when the dose is taken, the heal has no effect.

.*HPS Heal*
The other type of heal repairs a preset number of hit points.
A 20 hit point heal would return 20 hit points to a persona regardless of her hit point total.
However, the persona's hit point total can never exceed her hit point max by taking heals.

Attribute Heals:: 
Those heals that can repair attributes will repair 1-6 (1d6) points of attribute per dosage.
Attributes cannot exceed their original values by the use of heals.
A persona who lost 3 points of CHA (15 down to 12) from a recent burn could never exceed at 15 CHA. 

=== Inoculation 

[horizontal]
Duration:: Permanent
Safety:: 8
EXPS:: 1001
Value:: 1000000

Inoculations are not cures. 
Inoculations are not heals.
They neither repair or fix the persona.
An inoculation will increase the persona's resistance to future effects.

If a persona is inoculated against paralysis she will double her CON when trying to win a saving throw versus a paralyzing or stunning attack.
So if her CON were 15 she would save as if her CON were 30.

include::ROOT:partial$CH50_Table_Inoculation_Type.adoc[]


=== Mutation

[horizontal]
Duration:: Permanent
Safety:: 1/2 (TL / 2)
EXPS:: 100
Value:: 6000000

This pharmaceutical gives the persona a mental or physical mutation.
The mutation will not be a defect.
The mutation may be accompanied by a radical change in skin or coat colour.
The player will not know which mutation the persona has taken on.
Part of the fun, and danger, involve figuring the mutation out.

include::ROOT:partial$CH50_Table_Mutation_Type.adoc[]

Colour::
Colour deviations are a permanent side effect specific to this pharmaceutical.
They appear after the mutant's first sleep after dosing.
Make a jump over to xref:iv-software:CH55_Appearances.adoc#_colour_your_whirled[Colour] where the persona can have as simple or complex a colour change as needed.

Mental::
This indicates that the persona has acquired a mental mutation.
The mental mutation takes hold immediately, but the power is not immediately understood.
Mental mutations are hard to figure out and may only reveal themselves under duress.
Jump to xref:v-wetware:CH58_Mental.adoc#_mutation_type[Mental Mutations] to generate a fresh new mutation. 
This mutation cannot be a defect.

Physical::
This indicates that the persona has acquired a physical mutation.
The physical mutation will take a few sleeps to grow in.
The mutation's growth can be itchy, painful and unseemly.
Jump to xref:v-wetware:CH59_Physical.adoc[Physical Mutations] to generate the mutation.
If the player rolls a defect it will be combined with another non-defective physical mutation.

=== Mutation Effect 

[horizontal]
Duration:: 2-200 (2d100) hours
Safety:: 1/4 (TL / 4)
EXPS:: 100
Value:: 2000000

The mutation effect pharmaceutical aggressively and radically alters the persona.
They will transiently acquire either a physical or mental mutation.
The mutation effect comes on with a vengeance and quickly reveals it's power.

include::ROOT:partial$CH50_Table_Mutation_Type.adoc[]

Colour::
Colour deviations are a *permanent* side effect of this pharmaceutical.
The colour change immediately appears with a mutation effect.
This colour change can be as simple or as fancy as the referee desires.
Make a jump over to xref:iv-software:CH55_Appearances.adoc#_colour_your_whirled[Colour] to get a colour change.

Mental::
This indicates that the persona has acquired a mental mutation effect.
The mental mutation comes on with a ferocious headache and quickly reveals itself.
Jump to xref:v-wetware:CH58_Mental.adoc#_mutation_type[Mental Mutations] to generate a mutation effect. 
The mutation effect cannot be a defect.
When the duration ends the mental mutation fades away.

Physical::
This indicates that the persona has acquired a physical mutation effect.
The physical mutation violently explodes out of the persona's body.
The process is painful and unseemly.
Jump to xref:v-wetware:CH59_Physical.adoc[Physical Mutations] to generate the mutation.
The mutation effect cannot be a defect.
When the duration ends the physical mutation decomposes and falls off. f

=== Transient Intumescence 

[horizontal]
Duration:: 1-6 (1d6) minutes
Safety:: 1
EXPS:: 100
Value:: 2000000

Transient intumescence rapidly swells an attribute beyond normal bounds.
This boost is unnatural and temporary.
A transient intumescence doubles the attribute that it effects.
An awareness of 15 would become an awareness of 30. 
The intumescence is not impeded by anthro attribute restrictions.
Biological maximums remain. 

The intumescence is accompanied by a radical physical transformation.
A PSTR intumescence transforms the persona into a muscle layered hulk.
An AWE intumescence dilates the eyes ears and nose of the persona. 

Extreme attributes scores allow for abnormal performance.
Super awareness may let the persona smell chemical formulas or see microscopic cracks. 
Super mental strength may let the persona see kirlian auras.
Spectacular charisma may let the persona woo a large crowd with a glorious oration.

include::ROOT:partial$CH50_Table_Periodic_Intumescent_Type.adoc[]

This pharma is highly addictive and misuse is very attractive to players.
The referee can keep this pharmaceutical rare or have specific side effects.
Long recovery times with debilitated attributes is a good method for game balance.
For example, having a several day recovery period where the boosted attribute is halved. 


=== Permanent Intumescence 

[horizontal]
Duration:: Permanent
Safety:: 2
EXPS:: 100
Value:: 10000000

This complicated pharmaceutical permanently enhances a specific persona attribute.
Pharma that permanently improves attributes are the most sought after meds of all.

Once the pharmaceutical is taken the persona must work hard to increase the attribute.
The new attributes do not instantly appear.
The persona must earn the improved attribute over time.
This can be through training, pharmaceuticals, or extraordinary events. 
For example, a physical strength increase would require a regimen of strength training.
Or a new hit points max would require healing by a veterinarian.

Permanent intumescence should be rare enough that super attributes remain uncommon.
Players that choose to over use this pharmaceutical risk permanent attribute decay as a side effect.

include::ROOT:partial$CH50_Table_Permanent_Intumescent_Type.adoc[]

=== Poison 

[horizontal]
Duration:: Special
Safety:: 0
EXPS:: 1001
Value:: 42

Poisons are pharmaceuticals that do nothing but harm the patient.
They may be intentional poisons or pharma that has gone sour. 
Poison effects are very, very bad.
Personas can very easily be killed by poisons.
Poisons act as a deterrent for personas indiscriminately imbibing pharma.

Because poisons are directly administered into the persona's system there is no save roll.
If a save roll is granted the intensity of the poison is 6-36 (6d6).
Players are reminded that reducing an attribute to zero can lead to death.
None of the poisons are lethal, but their effects can be.
In addition to being a poison these pharmaceuticals automatically have an adverse effect.

include::ROOT:partial$CH50_Table_Poison_Type.adoc[]

== Pharmaceutical Attribute Explanations

In the immediately following paragraphs the pharmaceutical attributes are described.
After these paragraphs are the steps to creating a prescription.

=== Duration 
This note describes the length of time that the pharmaceuticals effect will last.
The onset is instantaneous, and the body will return to normal at the end of the duration.
Remember that side effects may have a longer duration than the pharmaceutical's effect.
A Permanent
duration indicates a permanent change in the taker's body.
All other durations are given in normal time ranges.
Those drugs that have a range of times listed for a duration must be rolled each time a dose is applied.

=== Safety 
Safety is simply the chance that the substance has no side effects.
Safety can be checked for each dose taken, or one roll can reflect the entire prescription.
Safety is usually equal to the tech level of the pharmaceutical.
A tech level 10 pharmaceutical has a 10% chance of no side effects.
If tech level is not part of your rule set the default is TL10.

=== EXPS 
EXPS are the experience points granted for identifying the prescription.
The pharmaceutical's effect can be determined by winning a vet performance roll.
Imbibing the pharma and correctly deducing the effect can also earn the EXPS.

=== Value 
The value is an indicator of the pharmaceutical's worth in eps.
The value is for a single dose.
If a prescription has 3 doses then it is worth 3 times the given value.
The value of pharmaceuticals can change according to the market's needs.

== Prescription 

.*Prescription Checklist*
. <<_labelling,Labelling>>
. <<_delivery_method,Delivery Method>>
. <<_metabolism,Metabolism>>
. <<_adverse_effects,Adverse Effects>>
. <<_doses,Doses>>

=== Labelling 
Prescriptions for us on terra are essentially over labelled.
Labelling of pharma in EXP is not like this at all.
The druggists that filled this prescription may have been deceased for a thousand, or the language used no longer exists.
In short prescription markings are essentially random. 
A living vet is the best bet for identifying an artifact pharmaceutical.

include::ROOT:partial$CH50_Table_Prescription_Markings.adoc[]

Labelling includes a completely uninformative colour for the pharmaceutical.
Jump to xref:iv-software:CH55_Appearances.adoc#_colour_your_whirled[Colour] to spice things up.

:art: drug_needleless.png
:width: 250px
:snark: You may not feel a little prick
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a syringe with no needle injecting into skin. 

include::ROOT:partial$articulate.adoc[]

=== Delivery Method 
The delivery method indicates the manner in how a dose is delivered to the persona.
A completely unhelpful colour can be applied to the pharmaceutical as well.
Pills would sport the colour rolled, and aerosols would be have that colour of case.

include::ROOT:partial$CH50_Table_Method_of_Administration.adoc[]

=== Metabolism
There are many different persona types in EXP.
Metabolism indicates what persona type the pharmaceutical was developed for.
This is an anthro centered rule set and anthros are the most common pharmaceutical metabolism.
This is an optional rule that has been given too much attention.

include::ROOT:partial$CH50_Table_Pharmaceutical_Intended__Metabolism.adoc[]

==== Anthro 
This pharma is designed, researched and made for anthros.
Often the players will stop there and not worry about specific anthro types.

Taking pharmaceuticals designed for other species increases the likelihood of adverse effects.
If a canine uses pharma created for avarians the chance of adverse effect is doubled.
This is calculated by halving the safety attribute of the pharmaceutical.
So a safety level 4 medicine would be reduced to a safety level 2 medicine. 
This doubles the chance of adverse effect.
The safety level is multiplied by the pharmaceutical's tech level to determine the chance of safe usage.

Alien and robotic pharmaceuticals do *not* work on anthros.
If an anthro uses an alien pharmaceutical it it becomes a <<_poison,poison>>. 
If an anthro figures how out to use a robotic pharmaceutical it becomes a <<_poison,poison>>.

==== Alien 
This pharma is designed, researched and made for an alien species.
The pharmacology of the medicine will not match any other alien or anthro physiology.
Alien pharma is designed for a specific alien species and does not work between aliens.
The method of delivery will match the size of the alien.
Gigantic aliens would have larger pills and syringes.

Taking pharmaceuticals designed for other species increases the likelihood of adverse effects.
If alien species uses pharma created for another species the chance of adverse effect is tripled.
This is calculated by dividing the safety attribute by three.
So a safety level 6 medicine would be reduced to a safety level 2 medicine. 

Anthro and robotic pharmaceuticals do *not* work on aliens.
If an alien uses an anthro pharmaceutical it it becomes a <<_poison,poison>>. 
If an alien figures out how to use a robotic pharmaceutical it becomes a <<_poison,poison>>.

==== Robot 
This pharma is designed for, researched on and fabricated for robots.
Robot pharmaceuticals are better described as spectacular motor oils, or bizarre fuels.
Liquid programming is another label for robotic materials that cause pharmaceutical effects.
For example, a robotic injection would appear more like a pneumatic dagger than a hypodermic needle.
Organic pharmaceuticals have no effect on a robot.

=== Adverse Effects 
Pharmaceuticals in EXP are complicated technological compounds that both diagnose and remodel the persona's body.
This make adverse effects very common with pharmaceuticals.
An adverse effect is an undesirable change in the body's chemistry that arises from taking a pharmaceutical.
Adverse effects and side effects are interchangeable terms

==== Adverse Effect Chance
The chance of an adverse effect is decreased as it's safety level increases.
The safety level of a pharmaceutical is multiplied by it's the tech level.
The most common tech level is 10.
If the players are not using tech levels then TL 10 is used.

=== Chance of No Adverse Effect
.No adverse = Safety * Tech Level
****
Pharma with a safety of 4 and tech level 10 has a 40% chance no adverse effect.
****

Vets can administer pharma to avoid adverse effects. 
A win versus intensity 5-30 (5d6) poison may deflect an adverse effect.

==== Adverse Effect
A roll on the Side Effect table will determine what side effect the persona will sustain if they have a failure of purity or take a prescription not tuned to their metabolism.
The side effects themselves are not lethal, but their consequences can be.
The ref can roll a new side effect each time one occurs, or have a specific one prepared for that pharmaceutical.

include::ROOT:partial$CH50_Table_Pharmaceutical_Side_Effect.adoc[]

=== Doses 
The more expensive the pharmaceutical the less doses per prescription.
One dose is one effect of the pharmaceutical.
The number of doses could represent the number of pills in a bottle, or puffs in an inhaler.

Vets can extend the number of doses in a prescription.
The more valuable the dose the harder it is to split a dose. 

include::ROOT:partial$CH50_Table_Pharma_Dosing.adoc[]