= Random Junque

The title of this chapter is self explanatory.
The tables contained in here are filled with lists of completely useless equipment.
It is almost certain that these artifacts have existed in every society in one form or another.
Random junque is useless equipment when compared to the artifacts created by TOYs.
However players regularly find use for random junque during their sessions. 

Random junque should not count as a roll for players generating start up Toys.

Wate::
If a random junque needs a wate the players decide whether it is large or small.
Small items are 100 grams and large items are 10kg. 

EXPS::
Players should earn decent EXPS if they manage to use random junque in their game session.
The EXPS earned usually ends in 42, and ranges from 42 to 1042 experience points.

Value::
Random junque has a random resale value of 1-10 (1d10) eps.
There is also a 10% chance that sacrificing a piece of random junque will generate a spare part.
A spare part can be used to fix a more objectively useful artifact.

.*Random Junque Checklist*
. <<_purely_random_junque,Purely Random Junque>>
. Random Junque by category
.. <<_appliances,Appliances>>
.. <<_armour,Armour>>
.. <<_books,Books>>
.. <<_clothing,Clothing>>
.. <<_fiddle_junque,Fiddle Junk>>
.. <<_foodstuff,Foodstuff>>
.. <<_furniture,Furniture>>
.. <<_livestock,Livestock>>
.. <<_materials,Materials>>
.. <<_musical_instruments,Musical Instruments>>
.. <<_personal,Personal>>
.. <<_sports_equipment,Sports Equipment>>
.. <<_stationery,Stationery>>
.. <<_weapons,Weapons>>
.. <<_miscellaneous,Miscellaneous>>

:art: random_Junque_Bin.png
:width: 250px
:snark: One persona's garbage...
:artist: Peggy-Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of an overflowing garbage can.

include::ROOT:partial$articulate.adoc[]



== Random Junque Category
Draw from the catalogue of random junque. 

include::ROOT:partial$CH51_Table_Random_Junque_Type.adoc[]



=== Appliances 
Every civilization has its kitchenware of convenience.

include::ROOT:partial$CH51_Table_Appliances.adoc[]

=== Armour 
Things you would never expect as armour.

include::ROOT:partial$CH51_Table_Armour.adoc[]

:art: random_junque_helmet_books.png
:width: 250px
:snark: One generations junque...
:artist: Warren Oddson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of space helmet, books and shaving brush on table.

include::ROOT:partial$articulate.adoc[]

=== Books 
Rare medium not well done.

include::ROOT:partial$CH51_Table_Books.adoc[]

=== Clothing 
Well worn stuff to wear.

include::ROOT:partial$CH51_Table_Clothing.adoc[]

=== Fiddle Junk 
Even more purposeless than the usual random junque.

include::ROOT:partial$CH51_Table_Fiddle_Junk.adoc[]

=== Foodstuff
Never enough to sate hunger, but always enough to make one hungry. 
First roll container type and then the foodstuff in it.
A frozen gaseous cookie is possible.

==== Foodstuff Container

include::ROOT:partial$CH51_Table_Foodstuff_Container.adoc[]

==== Foodstuff 

include::ROOT:partial$CH51_Table_Foodstuff_Type.adoc[]

=== Furniture 
Often the most useless part of a piece of furniture.

include::ROOT:partial$CH51_Table_Furniture.adoc[]

:art: random_junque_pig_toaster.png
:width: 250px
:snark: Pet pig, toaster and blender
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a blender a toaster and a piggy.

include::ROOT:partial$articulate.adoc[]

=== Livestock 
A unique alien species is evolved for this useless junk item. 
Only the xref:i-roll_playing_rules:CH06_Aliens_8_Shape.adoc[description] and biology elements are generated.
The alien must always be small, weak, dumb, and slow.
Livestock is not a pet, not a friend, and is not trainable. 
The livestock will constantly make a specific irritating noise

include::ROOT:partial$CH51_Table_Livestock.adoc[]

=== Material 
Incomplete building material components.

include::ROOT:partial$CH51_Table_Material.adoc[]

=== Musical Instrument 
Various out of tune noise makers.

include::ROOT:partial$CH51_Table_Musical_Instrument.adoc[]

=== Personal Items
You are so king in it.

include::ROOT:partial$CH51_Table_Personal_Item.adoc[]

=== Sports 
Go ball sport team. 

include::ROOT:partial$CH51_Table_Sporting_Equipment.adoc[]

=== Stationary 
Non-moving stationery. 

include::ROOT:partial$CH51_Table_Stationery.adoc[]

=== Weapons
Unusual replacement non-powered weapons. 

include::ROOT:partial$CH51_Table_Weapons.adoc[]

:art: radio_or_not.png
:width: 250px
:snark: Old timey radio or trans-hyperspace monitor?
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Old rasio with turn dial and wooden frame.

include::ROOT:partial$articulate.adoc[]



=== Miscellaneous
No missiles here at all. 

include::ROOT:partial$CH51_Table_Miscellaneous.adoc[]

=== Ref's Own Table 
The ref's own table for random junque should consist of useless things from the milieu.
Regardless of the milieu there will always be waste, incompetence and corruption.