= Exatmo Vehicles

[quote]
____
Ships sail from A to B across the C. Spaceships sail from A to B with __nothing__ in between'.
____

Although many times more sexy, and useful, than vehicles, spacecraft are nothing more than a means of getting from one place to another.
Spacecraft have the ability to exit planetary atmospheres, and sail off into the wild black yonder.
The spaceships are able to do this because of specially sealed hulls, super powerful engines, and highly specialized drives that cover enormous distances in one action.

The space vehicles created in EXP can vary wildly.
The space vehicle may be a piece of garbage discarded by a 1000 planet armada.
Or the priceless result of some life form trying to escape its gravity well.
Ships can be found, stolen, rented, lent or inherited by the expedition.
The ships can be used to achieve a specific campaign goal, or just to expand campaign horizons.
Either way access to a spaceship increases the level of fantasy to galactic proportions.

:art: hitcher_space.png
:width: 250px
:snark: Going my Milky way?
:artist: StudioStoks. Mods HM. 
:date: 2017
:license: Copyright Studiostoks 2015

include::ROOT:partial$articulate.adoc[]

The introduction of a spaceship will occur whenever the ref sees fit.
The campaign could start with a launch countdown, or could end with the escape from one's own hideous planet.

== Nomenclature 
Exatmo is a contraction for exterior to atmosphere. 
Exatmo is deadly to all life forms unless they are specifically protected.
ECM is an acronym for electronic counter measures. 
A vehicle must have exatmo or special drives to be a space vehicle.
An air ship only has an inatmo drive.
An air ship could be a plane, or a dirigible, but not a space vehicle.

include::ROOT:partial$CH38_Table_Nomenclature_of_Space_Vehicles.adoc[]

== The Build 
Space vehicles are neither accurate in detail, nor in aerospace specifications.
The space vehicle is a tool for role-playing. 
It is not an end itself.
The build creates random space vehicles that supply the basic necessities of space travel.
The only guarantees are a hull, drives, computers, and life support.
The layout and appearance is left to the referee and players.

.*Space Vehicle Build Checklist*
. <<_hull,Hull>>
. <<_drives,Drives>>
. <<_fuel,Fuel>>
. <<_computer,Computer>> 
. <<_computer_software,Software>>
. <<_defences,Defences>>
. <<_attacks,Attacks>>
. <<_crew,Crew>>
.. Navigator
.. Pilot
.. Engineer
. <<_cargo,Cargo>>
. <<_space_chattels,Chattels>>
. <<_exps,EXPS>>
. <<_value,Value>>
. <<_operational_costs,Costs>>

== Hull 
This is the first assumption about space vehicles is that they have hulls.
The shape of the hull is determined entirely for dramatic effect.
Space vehicles shaped like pirate ships are fine if this fits the referee's milieu.
The space vehicles in created here are designed must be operational exatmo.
Regardless of the shape chosen the hull will surround the delicate contents of the space vehicle.

The ship's hull is intimately integrated with the ship's life support and gravity systems. 

.*Hull Basic Elements*
. size
. composition
. strength


=== Hull Size 
Hull size determines the space vehicle size.
It is described in metric tonnes.
Hull size represents the amount of volume displaced by the space vehicle.
Hull size does not correlate with reality in any way.

:art: danger_in_deep_space_ships.png
:width: 250px
:snark: Different sized space vehicles
:artist: Louis Glanzman
:date: 1953
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Hull size determines how much stuff can be crammed on the space vehicle. 
It also determines the wate of drives, computers and fuel storage. 

include::ROOT:partial$CH52_Table_Hull_Size.adoc[]

=== Hull Composition 
Hull Composition is more of a descriptor.
All hulls function the same except regarding maintenance.
Most space vehicles will be composed of metal, plastix, and ceramic alloys.
Smart hulls are self maintaining and can slowly repair themselves.
Smart hulls offer no combat benefit at all. 
They allow the expedition to avoid the expenses of hull refitting.

include::ROOT:partial$CH52_Table_Hull_Composition.adoc[]

=== Hull Strength 
Hull strength is represents the hull's ability to prevent damage to the ship's interior components.
It is a mix of composition strength, shape and redundancy.
The hull strength is also the Hull AR. 
The hull cannot be damaged until the Hull AR is depleted. 
This depletion can happen fast in space vehicle combat.

include::ROOT:partial$CH52_Table_Hull_Strength.adoc[]

== Drives 
Like any vehicle a space vehicle needs engines to travel from one point to another.
However space vehicles are not so provincial as to call their power sources engines.
Space vehicles call their engines drives.
The term drive all the components needed to propel the space vehicle.

The space vehicles have three different types of drives. 
No space vehicle is guaranteed to have all three drives.

.*Adding Space Vehicle Drives*
. Drive configuration
.. Exatmo
.. Inatmo
.. Special
. Drive Size 
. Drive Level

include::ROOT:partial$CH52_Table_Drive_Types.adoc[]

=== Exatmo Drive
Exatmo drives are the defining feature of the space vehicle.
This is the drive that maneuvers the ship through the vacuum of space.
The exatmo drives are sciency fiction fast.
Their power is measured in fractions of the speed of light.
They can maneuver a ship well beyond survivable physics in combat. 

Exatmo drives will be one of two types: fusion or gravetics.
The player creating the space vehicle may choose between the two.
Both are equally efficient at moving the ship around exatmo.
Neither type of exatmo drive can function within the atmosphere.
Fusion and gravetics drives require an absence of gravity and atmosphere to function.

Weaponizing either exatmo drive is a campaign level, nearly insurmountable task.
At some point every expedition will attempt to weaponize the exatmo fusion drive inatmo.
The referee should make such a refit and multi-run campaign story.
Using a fusion drive or gravetics drive as a weapon will certainly destroy it as an exatmo drive.

=== Inatmo Drive
These are the in-atmospheric drives of the ship.
The inatmo drive is for in atmospheric maneuvering.
A space vehicle that does not have an inatmo drive cannot enter an atmosphere.

All of the inatmo drives function equally well.
For inatmo drives to function both atmosphere and gravity are required.
Inatmo drives do not work in space. 
A space vehicle with both inatmo and exatmo drives can enter and exit a planet's atmosphere.
The ship's computers negotiate the transfer of drives from inatmo to exatmo.

include::ROOT:partial$CH52_Table_Inatmo_Drive_Type.adoc[]

==== Antigrav Inatmo Drive
Nothing more than anti-gravity units which suspend, and maneuver, the ship above the planet's surface.

==== Balloons Inatmo Drive
Once in the atmosphere, balloons will automatically billow out, and fill themselves with a computerized mixture of gases.
The ship is maneuvered about by altering the buoyancy of the various balloons.

==== Chutes Inatmo Drive
This spaceship ejects an enormous collection of kites, and parachutes, which computers control to maneuver the ship while fuel supplies last.
The spaceship can employ prevailing winds to lift off.

==== Jets Inatmo Drive
A multitude of fuel burning jets maneuver the ship in atmosphere.
They act like retro rockets that can maneuver a ship within the atmosphere.

==== Props Inatmo Drive
Large airscrews, located about the ship operate at various power levels to attain maneuverability.

=== Special Drives
Special drives technomagically fling the starship instantly across space.
Special drives avoid generational space vehicles  and unhealthy cryosuspension.
Special drives are cornerstone of sciency fiction space operas.
The speed of light is just not good enough.
The logistics of 2000 year space flights are the root cause of special drives.
Special drives make space travel more efficient and more fun.

include::ROOT:partial$CH52_Table_Special_Drive_Type.adoc[]

The special drives turn insurmountable distances into science fiction pulp.

==== Bloater Special Drive
A bloater drive expands the ship, and its contents by increasing the space between its molecules.
The expansion continues until entire planets, and stars, can pass between the molecules without danger.
This bloating continues until the destination point is near the ship's hull.
The ship then begins to deflate around its new destination point, arriving there without moving.

==== FTL Special Drive
Faster than light travel plays havoc with many paradoxes.
All such paradoxes aside, FTL travel is a convenient way to get from point A to point B.

==== Hyper Special Drive
Also known as jump drives.
Anything that is hyper does more than anything else in the same amount of time.
So the hyperdrive covers light years faster than a non-hyper drive would.

==== Psi-Flip Special Drive
The most fantastical of all the special drives.
The psi-flip transports the ship to the location thought of by the navigator.
Only the most precise mental image can be translated into motion.
To navigate this special drive requires 18 MSTR or a specially mutated persona.
Robots cannot operate a psi-flip special drive.
Once the psionic navigator has convinced her mind that she is somewhere else, the psi-flip drive correct the reality.
Psi-flip is known as a mind flip drive, or a flip drive.

==== Time-Slip Special Drive
Another one of the mystically bizarre space travel devices is the time slip.
This drive system drops its payload into time limbo (wherever that is).
Once in this reference it scans through past/future time frames until it finds one where the stars and planets of the universe are better aligned for for its travel purposes.
The drive then re-enters the original space time, but at its desired location.

==== Transmat Special Drive
A transmat is also known as a probability drive.
It depends on the probability that at least one of the electrons of one of the drive's molecules will be on an extreme orbital somewhere near the desired location.
Once this occurs it is just a __matter__ of reorienting the ship's molecular parts with the vagrant orbital electron particle.

==== Warp Special Drive
Warp drives operate under the premise that the space between two points can be folded up.
Once space time is folded the space vehicle passes through the base of the fold.
This distance travelled is short but distance covered is enormous.
This can also be called an origami drive.

=== Drive Level and Wate
The drive level represents how powerful the drive is.
Drive level is determined by a 1d10 die roll.
Each drive type will have it's own performance level.
A space vehicle configured with exatmo and inatmo drives would roll for each drive type.
The higher the die roll the more powerful the drive.
The more powerful the drive is the more hull space it occupies.

The wate of a ship's drives are determined their level and the space vehicle size.
The drive wates are cumulative. 
A space vehicle with a 10 tonnes exatmo drive and a 5 tonne special drive uses 15 tonnes of hull.

A level 5 exatmo drive can move at 0.5 C (speed of light) and orbit around 5 G (gravity) planets. 
On a 100 tonne vessel the drive would have a wate of 5 tonnes, and occupy 5 tonnes of hull space. 
On a 10 tonne vessel the drive would have a wate of 500 kgs and occupy 500 kgs of hull space. 

include::ROOT:partial$CH52_Table_Drive_Level_and_Size.adoc[]

==== Inatmo Drive Level
The inatmo drive level is determined by a 1d10 roll. 
The player rolls an individual drive level for each drive.
For each level of inatmo drive the space vehicle can travel 1 Mach in atmosphere.
For each level of inatmo drive the space vehicle can manage 1 Gravity of planet pull.
Mach is equal to the speed of sound. 
In EXP we ignore the effects of temperature and atmospheric density on the speed of sound.
It is a given that a level 4 inatmo drive is twice as fast as a level 2 inatmo drive.
A level 6 inatmo drive can travel at Mach 6, or 6 times the speed of sound
A level 6 inatmo drive could overcome 6 gravities of planetary pull. 

==== Exatmo Drive Level
The exatmo drive level is determined by a 1d10 roll. 
The player rolls an individual drive level for each drive.
A exatmo drive can travel at 1/10 the speed of light per drive level.
The space vehicle can maintain an orbit around a planet with 1 gravity per drive level.
A level 6 exatmo drive can travel at 0.6 the speed of light. 
A level 6 exatmo drive can close orbit up to 6 gravities of planetary pull.

==== Special Drive Level
The special drive level is determined by a 1d10 roll. 
The player rolls an individual drive level for each drive.
The special drive can travel 20 light years (LY) per level.
A level 6 special drive can travel 120 light years in one moment.

During a special drive jump the ship cannot be communicated with.
A special drive jump cannot be aborted safely.
The consequences of aborting a special drive run are up the referee.

The special drives must fit into the milieu of the referee's campaign.
The duration of a jump could be changed from a moment, a day or a week.
The distance covered can be changed to parsecs, or astronomical units.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Fuel 
Fuel seems like a trivial issue for a gallant expedition out to save the universe.
Energy is the limiter of all, including the space vehicle.
Fuel is a tool to make game play more challenging and the story telling more interesting.

=== Fuel Type
A space vehicle's fuel type is mostly a fun descriptor.
It is entirely up the referee if gas from one ship is compatible with gas from another.
A space vehicle will only have one fuel type.
Each drive type will use the same fuel type.
The drive types may use the same fuel, but each drive has different needs and rates of consumption.

include::ROOT:partial$CH52_Table_Fuel_Type.adoc[]

=== Fuel Amount 
The amount of fuel is determine by individual die rolls for each drive type.
The player only rolls for the drive types the space vehicle is configured for.
The fuel amount occupies hull space on the vessel.
The fuel amount also determines the range of the space vehicle.
The higher the fuel level the more space it occupies and the further the space vehicle's range.
 
include::ROOT:partial$CH52_Table_Fuel_Storage.adoc[]

For example a spacecruiser has the following fuel levels: inatmo 8, exatmo 9 and special 3.
Regardless of the fuel type, fuel storage occupies 20% of the spacecruiser's hull.
The spacecruiser would have a range of 20 months. 
If this were a 100 tonne spacecruiser 20 months of fuel would occupy 20 tonnes of hull space.

=== Fuel Range 
Calculating light years, kilometers, or parsecs, was overwhelming, and boring.
The 30 day month was chosen as a measure of fuel use.
The month of range refers to that specific space vehicle, it's storage, it's drive and it's size.
One month of fuel usage equates to one special drive jump.
Choosing a time of fuel burn proved to be the easiest way to keep track of fuel consumption.
A 10 tonne and 100 tonne spacer would use 1 month of fuel to do a special jump.
The 100 tonne vessel would use 10 times more fuel in wate, but the month is used to keep track.

include::ROOT:partial$CH52_Table_Fuel_Consumption.adoc[]

So a space vehicle with a fuel storage of 5% Inatmo and 10% exatmo would have 15 months of fuel.
This fuel could be used up in 15 special drive jumps, or 60 turns of space combat.
A space vehicle cannot jump if there is less than 1 month of fuel on board.
A space vehicle drops out of combat if there is less than 1 week of fuel on board.
During space combat the drives cannot sip from the collective fuel storage. 
Fuel storage is compartmentalized for safety and this can effect fuel access of specific drives.

Refuelling is left to the design of the referee.
Some fuel types maybe innocuous materials which are easily obtained from the local gas giant.
Other fuel types may require days of retooling by highly skilled space mechanics.
Don't forget the power of the sphincter dice when trying to decide complicated and boring issues.

== Computer 
The computer is the ship and the ship is the computer.
The computer is deeply integrated with every system on the ship.
The computer manages special jumps, evasive actions, life support, gravity and more.
A space vehicle requires a computer and crew to function.
Pilots, navigators and engineers work on the space vehicle through the ship's computer.
The persona crew can be be replaced by software. 
There are no manual space vehicles.

Life support protects the vessel's cargo, but is there for the ship's computer.
A dead computer is as dead space vehicle.
Cargo and crew come and go.

.*Installing the ship's computer*
. Computer Level
. Computer Wate
. Computer Software
.. Crew
.. Defensive
.. Miscellaneous

The ship's computer is mostly distributed throughout the entire ship.
Often there will be a central location for interaction. 
This could be called the ship's bridge.
Personas acting as ship's crew can be located on the bridge or distributed about the vessel.

A personality for the ship's computer is recommended.
It is assumed that there is tremendous artificial intelligence potential in a ship's computer.
The referee may consider the ship's computer a referee persona.
The ship's computer is intended to be user friendly.
The expedition may interact with the computer via devices, or voice interaction.
It would not be unreasonable to roll a fabricator type for a space vehicle. 

=== Computer Level and Wate
The higher the computer level the more powerful it is.
A higher the computer level improve everything from the food made to combat maneuvers. 
Computer level is rolled on one 1d10.

The bigger the ship, the larger the computer.
The higher the level of the computer the more complicated the software it can manage.
The die roll also represents the percentage of hull capacity that is occupied by the computer.
So a 200 tonne starship with a level 4 computer would have 8 tonnes of computer equipment on board.
The 8 tonnes of computer includes all the wiring, transducers, terminals, and interfaces, as well as memory and processor.

== Computer Software 
Ship's computer software accentuates a computer's skill set in specific areas.
All space vehicles automagically maintain life support, gravity, and keep things from exploding.
A space vehicle needs direction from personas to get up and go.
The effectiveness of software is determined by the computer level of the space vehicle.
There is no limit to the amount of software on board. 
A space vehicle is limited to using 1 software title per level of computer.


How software appears in the game is dependent on the milieu of the referee.
Software may be hardware that is attached to the ship's computer.
Or it may be auto downloaded from GitHub.
Mechanics making their own software would require a research team and a start DD of 20


// doubled up in software section
// remember to cut and paste

The table for software is a bit different.
Each software title has a __Chance__ listing. 
A level 3 computer would have a 60% chance of an astrogation program.
A roll of 60 or less on 1d100 indicates the software is installed.
The player rolls for every software title.
There is no limit to the amount of software that the computer can have on board. 
A space vehicle is limited to using 1 software title per level of computer at once.
Players may have to make choices about what it the most important software to run.

=== Crew Replacement
Crew replacement software indicates programs, and mechanical devices that can replace essential crew.
In some circumstances the crew software replaces the required crew member completely.
In other circumstances the crew software allows even the vocation nothing to operate the system.
A space vehicle is limited to using 1 software title per level of computer at once.
Players may have to make choices about what it the most important software to run.
A low level ship's computer may always require a persona crew member to function.

.*Essential Services*
. Pilot
. Astrogator
. Engineer

Each software title has a __Chance__ listing. 
A level 3 computer would have a 60% chance of an astrogation program.
A roll of 60 or less on 1d100 indicates the software is installed.
The player rolls for each crew replacement software title.

include::ROOT:partial$CH52_Table_Software_Crew.adoc[]

==== Astrogation
This software title allows any persona to pilot the special drives.
The persona works directly with the ship's computer to plot special drive jumps. 

When an astrogator uses this software she enjoys some special drive bonuses.
The special drives are enhanced by 2 LY distance per level of ship's computer. 
Special drive fuel consumption is reduced to 2 weeks per jump instead of one month.

==== Engineering
This software title allows any persona to carry out ship maintenance and repairs. 
The ship's computer directs personas what needs to be done, where it needs to be done and how to do it.

A mechanic working with this software gets bonuses on her performance rolls for ship related maneuvers.
Ship repair and maintenance performance rolls get a bonus of +5 per level of ship's computer.

==== Navigation
This software title allows any persona to pilot the inatmo and exatmo drives.
The persona works directly with the ship's computer via specialized control devices (steering wheel). 

A pilot or navigator working with navigation software can save fuel during normal travel.
Combat fuel usage is unaffected by this teamwork.

==== Piloting
This software title allows any persona to completely hand over all maneuvers to the ship's computer.
This includes navigation, astrogation and combat piloting. 
Piloting software is so advanced that endowing it with an additional personality would be reasonable.

=== Miscellaneous 
This software can be virtually anything that can be imagined for a ship's computer.
If the software is relevant to a personas PT roll she can earn a DD bonus of +1 per computer level.
For instance a nothing making a general performance table roll to successfully cater a fancy dinner would earn a DD bonus if etiquette, diplomacy, or entertainment programs were on board.
Many of the software devices list a class in which they will assist.
If this is the case any persona of that class will earn a DD bonus equal to the space vehicle's computer level when working within its environment.

The player makes one roll per level of ship's computer. 
What to do with repeat results is determined by the referee and players.

include::ROOT:partial$CH55_Table_Space_Vehicle_Software.adoc[]


== Defences 
A ship's defences are composed of both the ship's computer, and machinery within the hull of the ship.
Life support, gravity and hull are considered defensive systems. 
Life support works together to defend against the harshness of exatmo.
Intentional defences, like ECM and shields, are designed to protect the ship in combat.

Defences are list on a check table.
The player checks for each defence listed on the table.
A space vehicle with a level 5 computer would have a 50% chance of electronic counter measures, 40% chance of shields, and so on.

include::ROOT:partial$CH52_Table_Defences.adoc[]

=== Life Support
Life support maintains a comfortable environment for the organic, and delicate inorganic, contents of the ship.
Life support is entirely self contained, and is virtually impossible to tamper with.
The life support system will function completely unknown to the players, until something goes wrong.

Life support, gravity, hull AR and hull are all part of the Life Support Onion.
Before life support is vulnerable each outer layer of the onion must be destroyed.

include::ROOT:partial$CH38_Table_Order_of_Life_Support_Destruction.adoc[]

=== Gravity System
The gravity system is a crucial component of the life support system.
The gravity system is intimately integrated with the hull and life support system of the vessel.
Life support is distributed, self contained, and is impossible to disable.
Gravity is usually maintained at a constant attraction of 1g.
This includes walkways, workspaces, cargo holds, cabins, and exterior hull etc.
This is controlled by the ship's computer, and is uniform throughout the whole ship.
The gravity can be adjusted between 0.5  and 1.5 gravities.

=== Armour
The hull supplies the space vehicle's armour rating used in combat.
When space vehicles are created they are assigned an armour rating as part of their hull.
The hull and armour rating have an intimate relationship.
In combat Armour Rating can be reduced by absorbing or being damaged.
The space vehicle's armour rating must be reduced to 400 before the hull is damaged.

The hull is a crucial component of the life support system.
The hull is intimately integrated with the gravity and life support systems of the vessel.
Life support is distributed, self contained, and is impossible to disable.

=== ECM
Electronic countermeasures (ECM) deceptively manipulate the electromagnetic spectrum to defend the ship.
The more powerful the ship's computer level the more effective the electronic counter measures.
If any personas have skill in ECM they can add that skill level to the computer level used for the ECM.
So if a mechanic has ECM level 2 and the computer level is 3 then the ECM will function as a level 5.

ECM is an accessory unit of the ship's computer. 
It can be utilized as attack ECM or defense ECM.
One ECM unit cannot do both in the same combat turn.
If the space vehicle has only 1 ECM unit the players must decide how to use it each combat turn.

=== Shields
The shields protect the hull AR and hull from energy and kinetic attacks.
A defensive shield may be a force field or a structural mechanism. 
Both mechanisms work by distributing the damaging force across the entire hull.
This faux scientific diffusion effectively dampers the damage.
The shields have an active mode that the players turn on to thwart intentional damage.
Shields also have a passive mode, and when present they are part of the life support system.

=== Guns
A gun is a purely defensive element in space vehicle combat.
A gun does not sound like a defensive tool, but occasionally the best defence is a good offence.
Guns on space vehicles are anti-personnel air lock defense weapons.
In ship to ship combat a gun is an ineffectual weapon.
However to prevent boarding or air lock intrusion a mounted gun can be very effective.

The airlock gun is created in the  xref::CH46_Guns.adoc[Guns section]. 

.*Airlock Defensive Guns*
* operate inside and outside of airlock
** but not not simultaneously
* operate inatmo or exatmo
* can be automated like a turret
** gunnery software or ship's computer
* can be controlled by personas
** mercenaries do this best
* has unlimited ammo to defend against boarding
** ammo can be limited if weapon being abused
* has an AR equal to the ship's hull
** including ECM and shields
* damaged by Hull AR damage or airlock damage location

=== Active
Active defences are used against incoming weapons.
Active defences are sometimes called actives.
They can eject missiles, shrapnel, energy blasts, lazer matrices, or crystalline discharges. 
The goal is to dissipate, prematurely detonate, or destroy incoming attacks.
All active defences function equally.
Active defences can be used against grenades, bombs, or artillery.
Actives have no effect against boarding, ramming, ECM, or naval artillery.

.*Notes about active defences*
* Active defences are not part of the Life Support Onion
* Active defences are automated
** Gunnery skilled personas can help
* Active defences work inatmo and exatmo
* Actives cannot be weaponized

== Attacks 
Space vehicle combat is highly discouraged due to the high chance of persona mortality.
A space vehicle may be fitted with attacks because the crew are pirate scum.
A space vehicle may be fitted with attacks to fight pirate scum.

A military space vehicle is defined by the rolls in this section.
A vessel that has naval artillery, mines, or missiles is a combat vessel.


All space vehicles can be used to forcibly board another space vehicle.
The referee goes down the list rolling once for each attack type.
So a space vehicle with exatmo drive level 4 would have a 20% chance of ramming, a 16% chance of ECM, and a 2 percent chance of Naval Artillery.

include::ROOT:partial$CH52_Table_Attacks.adoc[]

=== Boarding
All space vehicles can attempt to forcibly dock with another vessel.
Boarding is congenial ramming.
Boarding lines up airlocks to prepare for a breech and boarding of the target vessel.
Boarding can only be used to force airlocks together while exatmo (exterior to atmosphere).
Once connected the attacking crew will breech the airlock of the target ship and then board.
This method of attack is used because it preserves the target space vehicle, hostages, cargo, and is a lot more fun.

=== Ramming
Ramming is a method of boarding a target space vehicle where all caution has been thrown to the solar wind.
A space cruiser capable of ramming will have a specialized airlock which can attach to any part of the target ship's hull.
Once attached the invading party may breech the hull, airlock, or whatever to gain entry into the ship.
In procedure, ramming is similar to boarding except that ramming is accompanied with lots of crunching and scraping noises.
Ramming, requires skill and brute force.

Not all space vehicles can ram.
There is an element of self preservation that a space vehicle has.
Many safety layers have to be removed for a ship's computer to consider ramming as an option.

=== ECM
ECM is the acronym for electronic counter measures.
This is the battle for control over the electromagnetic spectrum.
In space vehicle combat, ECM is the battle for control over the electronics of the target ship.
Attack ECM can be used to confuse the target ship's defences with false data, to control an essential component of the target ship, or be used as defensive instead of attack.
The pilot must choose between Attack Assist, Control Attack or Defense for her ECM each turn.
An ECM attack unit is still an ECM unit and can be used to defend instead.
One unit cannot do both.

=== Grenades
In space vehicle combat grenades explosives delivered by either mini-missile or mini-mine.
The intent of the grenade is to explode against the hull in an attempt to damage the internal mechanisms of the ship.
A successful attack roll must be made against the space vehicle's armour rating to inflict damage.
This is in direct contrast to area of effect weapons in tactical inatmo combat.
If the attack roll is unsuccessful the grenade detonates ineffectively and silently in space.

Grenade delivery systems have diminutive titles because they only deliver grenades. 
Naval missiles and mines deliver bombs.

include::ROOT:partial$CH52_Table_Spacer_Grenade_Type.adoc[]

=== Bombs
Bombs are lethal attack weapons.
Bombs need only explode near the ship's hull to inflict damage to the contents within.
The number and type of bomb is determined when the space vehicle is created.
Bombs are delivered by either missiles or mines.

A bomb is guaranteed to damage a target with a successful attack roll.
Every bomb gets a second chance to damage a vessel just by getting close enough. 
If the raw roll of a missile or mine is better than 500 the target is still damaged.
Dangerous destructive devices.

include::ROOT:partial$CH52_Table_Spacer_Bomb_Type.adoc[]

=== Artillery
The purpose of ship artillery is to damage the target ship so that it ceases to function.
This goal is achieved by penetrating the hull, and delivering the artillery's destructive force to the internal components of the ship.

Although artillery cannot be fired exatmo into the atmosphere it can be used freely when the vessel is within an atmosphere.
Ship artillery has the same ranges, damages, and effects as the artillery it is modelled after.
The difference is in the amount of ammunition the fixed gun has access to.
Energy based weapons can fire as long as the ship has fuel, and artillery requiring ammo will have 100 times the regular supply.

include::ROOT:partial$CH52_Table_Spacer_Artillery_Type.adoc[]

=== Naval Artillery
Naval artillery has only one purpose in mind, to destroy the target ship.
Naval artillery is not used to soften or assist in the taking over of the target vessel.
The destruction is accomplished by the sheer force of the weapon.
One use of naval artillery exhausts a whole day's worth of fuel.
The naval artillery cannot be idly used, it requires a gunnery program, and two gunners.
Without this complement, the ship cannot fire its naval artillery.

NOTE: *Artillery are big guns. Naval artillery are big big big guns.*

Naval artillery is more deadly than the regular deadly artillery.
Naval artillery inflicts 3 times the damage, and has 100 times the range.
Naval artillery can only be fired exatmo.

The player rolls on the artillery table above and then does arithmetic as directed below.

include::ROOT:partial$CH52_Table_Naval_Artillery.adoc[]

include::ROOT:partial$CH52_Table_Example_Naval_Artillery.adoc[]

== Crew 
Space vehicles vary in size from personal craft to city sized leviathans.
They can have fantastical drives that flit them across the stars, and computers that weigh tonnes.
The most important element is still the crew.
They are manufactured to move life forms, and cargo from place to place. 
Space vehicles can have personalities and attitude, but they are *not* autonomous lifeforms. 

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

The crew of a space vehicle can be composed of aliens, anthros, or robots.
Every space vehicle has essential crew.
Without the essential crew a space vehicle will not move.
A space vehicle will have the essential crew on board, or the software titles to replace them.

.*Essential Services*
. Pilot
. Astrogator (for special drive)
. Engineer

Some space vehicles will require even more crew. 
Some space vehicles will require multiple engineers. 
These three are the essentials needed.

=== Pilot 
The pilot is an essential crew member and a space vehicle cannot function without one.
The pilot is the overseer of all the ship's functions.
She is responsible for the execution of planetary maneuvers, star system maneuvers, combat maneuvers, ship procedures, and general ship authority.
All of these tasks require the intimate cooperation of the ship's computer, and the pilot.
Without a pilot the ship is essentially grounded, orbiting space junk, or stuck in deep space.
No ship can, unless having a mind of its own, be activated without a pilot.

An additional pilot (co pilot) will be required for every 10 000 tonnes of displacement.

.*Qualified Pilots*
. Mechanic vocation with pilot skill
. Nothing vocation with pilot skill
. Exatmo transport bot

=== Astrogator 
The astrogator is an essential crew member and a special drive cannot function without one.
The astrogator operates the ship's special drive.

The complexities of the special drives are a case of their own.
The astrogator is responsible for safe programming of the ship's special drive.
She co-ordinates with the ship's computer to arrange for a safe special drive jump.
A special drive will not properly activate without an astrogator.

An additional astrogator is required for space vehicles exceed 4200 tonnes.

.*Qualified Astrogator*
. Nomad vocation
. Knite vocation
. Mechanic vocation with astrogation skill
. Nothing vocation with astrogation skill 
. Exatmo transport bot

=== Engineer
The engineer is an essential crew member and a space vehicle will  malfunction without one.
The engineer does essential repairs and maintenance on the space vehicle.
A space vehicle may jump once, or engage in combat once, without an engineer.
Afterwards it will not function.
If essential routine maintenance is not carried out the space vehicle will not operate.

The engineer maintains tonnes of drives, complicated airlocks there is a lot that will go wrong.
It is the responsibility of the ship's mechanic to monitor the computer's maintenance programs, to program repairs, and to occasionally pick up the wrench herself

An additional mechanic is required for every 9 000 tonnes of hull displacement

.*Qualified Engineer*
. Mechanic vocation
. Maintenance robot

=== Gunner 
Gunners are required to operate the combat equipment: artillery, naval artillery, mines, active defences, missiles, and shields.
None of the listed equipment will function without a gunner, or a software replacement.
Combat robots can replace a gunner without the need of a gunnery program.
Combat robots can operate one active combat device for every 4 points of intelligence.

.*Qualified Gunner*
. Mercenary vocation
. Spie vocation
. Combot

=== Doctor 
Any space vehicle that has organic passengers requires a ship's doc.
Guests, soldiers, cattle without proper vet attention will get sick in deep space.

.*Qualified Ship's Doc*
. Veterinarian vocation
. Diagnostics veterinarian robot

=== Steward 
Guest laden starships require a ship's steward.
The steward changes linen, washes clothes, and generally makes space travel bearable for guests.
Without a steward, guests will certainly be in bad temper, and may even rebel during the trip.

One steward is required for every 50 passengers.

.*Qualified Steward*
. Nothing vocation with SS <400
. Social robot
. Domestic janitorial robot

=== Administrator 
One optional crew member which may be actively shunned by the personas, is the ship's administrator.
The ship's administrator will arrange docking papers, interpret cartage laws, balance accounts, designate cargo allotments, and will fill in as the ship's legal advisor.

.*Qualified Administrator*
. Nothing vocation with INT <12
. Transport robot
. Datalyzer robot

=== Diplomat 
The diplomat is trained at being excruciatingly polite, even to the most horrific of alien species.
A diplomat will attempt to keep the crew, the guests, (and especially the personas) from offending rarely encountered cultures.

.*Qualified Diplomat*
. Nothing vocation with CHA >12
. Social robot

== Cargo
Cargo is any tonnage that is not occupied by drives, fuel, or computers.
The cargo allotment cannot be immediately counted as cargo space, there are several other space vehicle features which occupy hull space.
These are: cold storage, work spaces, cabins, and corridors.
The remaining space is cargo space, it indicates how much goods can be transported, and what type of hull access is allowed.

The player allots all cargo space remaining after drives, fuel and computer. 
This may necessitate a design for the space vehicle.
Design can be laid out on a graph paper sheet, hex mat, or napkin.
It need not be fancy.

=== Access Port (mandatory)
Allows access to the space vehicle when inatmo. 
If one is present the personas may use the airlock instead. 

=== Work Spaces (mandatory)
Work spaces are even more mandatory than the essential crew.
One half tonne of hull space must be allotted to every member of the working crew.

=== Airlock
An airlock allows passengers, and stuff, to get in and out without decompressing the space vehicle.
Airlocks work perfectly well inatmo.
Airlocks are simple, secure and safe.
Any tool using life form can use an airlock.
They usually employ pictograms and may even have language assist.
Airlocks are secure. 
The ship will only allow identified crew to enter the space vehicle.
Airlocks are safe.
It would be nearly impossible to eject a lifeform from a functioning airlock.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

An airlock takes up no space __inside__ the space vehicle.
However an airlock requires 5 tonnes of vacant cargo space.
It is possible a smaller space vehicle does not have enough hull for an airlock.
If the space vehicle has inatmo drives the vessel is intended to be boarded inatmo.
If the space vehicle only has exatmo or special drives it is meant to be boarded inside a larger ship or space port. 

A ship can have 1 airlock for every 5 tonnes of vacant cargo space.
Airlocks are free to be located anywhere on the space vehicle.
So a ship with a 15 tonnes vacant cargo hold could support 3 airlocks anywhere on its hull.
A ship with 2 tonnes vacant cargo space would have an inatmo access port.

=== Cargo Lock
A larger ship may prefer a cargo lock.
A cargo lock is not pressurized and can only be used inatmo. 
A cargo lock requires a minimum 50 tonnes of vacant cargo space.
However a cargo lock does not occupy any cargo space.

A cargo lock is more than just a door, it is a system.
A typical cargolock has a capacity of 10 tonnes.
A 10 tonne cargo lock can load/unload 10 tonnes of cargo per hour or day or whatever.

=== Cargo Airlock
Cargo airlocks are enormous airlocks that are found on gigantic space vehicles.
The cargo airlock can move cargo or without depressurizing the space vehicle.
A cargo airlock requires at least 500 tonnes of vacant cargo space.
The cargo airlock occupies cargo space.
A space vehicle loses 1 tonne of cargo space per 2 tonnes of cargo airlock size.

There are no open hull force field protected cargo airlocks in EXP.
Development is ongoing and this milestone may be reached with expected technological advances.

=== Cold Storage 
Cold storage is for cryogenic suspension of organic material less than 250 kg in wate.
The freezers will maintain life, with no drain on life support, and will continue to function after life support has failed.
Cold storage will work until the cold storage box itself is destroyed.
Each cold storage space occupies one half tonne of hull space.

=== Cabins 
Cabins are somewhat of a luxury, but it is impossible to have guests (other than in cold storage) without cabin space.
Each cabin requires one tonne of hull space, and can comfortably house two passengers.

=== Corridors 
Corridors only apply to any passageways that connect luxury cabins, workspaces or ship systems.
Cabin corridors require 200 kg of hull space per map hex (2 meters) of passage.
If personas want to quickly run from the artillery bay to the exatmo drives corridors are recommended.

The entire ship is accessible by utility corridors.
Utility corridors occupy no significant amount of hull space.
However they are cramped, claustrophobic and slow to navigate.

=== Example Calculation 
All remaining cargo space is honest to goodness cargo space.
A ship may have one airlock per 5 tonnes of cargo space, a cargo lock (in atmosphere only) requires 50 to 500 tonnes of cargo space, a cargo airlock requires 500 to 5000 tonnes of cargo space.

Let's walk through an example 100 tonne space cruiser.
Exatmo drive level 10.
Fuel storage level 5.
Computer level 4.
Carries 20 passengers 16 in cold storage 4 in Cabins.
A pilot, mechanic, doctor,  and steward.
No robots.
This leaves about 63 tonnes cargo space in the vessel.
This would allow for a cargolock and multiple airlocks.
60 tonnes is about two 21st century urban dump trucks full of stuff.

include::ROOT:partial$CH52_Table_Calculate_Cargo_Space.adoc[]

== Space Chattels 
Specialized equipment and architecture common to ancient, and future, space travel.

=== External Drives 
The nature of external drives are self explanatory.
Either the exatmo, or inatmo, drives are located outside of the hull.
This innovation allows cargo space they occupied to be converted into cargo space.
The drawback of this system is that the drive units are subject to attack during combat.
External drives can either be accessed directly through the hull, or via an airlock.

Special drives can never be external.

=== Datalocks 
Datalocks are also called hardpoints.
Datalocks are electronic accesses to the exterior of the hull.
A datalock is required for every single external contraption that requires exatmo access (guns, missiles, viewers etc).
A ship will have 10 datalocks per level of computer.

=== Vac Suits 
Vac suits allow delicate organic life forms to survive exatmo.
A spacecraft will have one civilian vac suit per crew member and luxury cabin.
So a pleasure cruiser with 5 crew and 6 cabins would have 11 civilian vac suits.

There is a 10% chance per civilian vac suit that there will be an industrial vac suit.

Vac suits are described in the xref::CH42_Armour.adoc[Armour section].

=== Gravity Couches 
Gravity couches are chairs specially designed to save the body from damage during high-g maneuvers.
They are composed of force absorbing materials, and restraining belts.
Grav couches are only needed when the starship's gravity system has failed.
Passengers and crew not in gray couches during high-g maneuvers will almost certainly be killed.

Only combat vessel have grav couches by default. 
A naval vessel is defined as a space vehicle that is fitted with naval artillery, bombs or grenades.

=== Emergency Response 
Emergency response is part of the ship's life support system.
Space vehicles will have automated emergency equipment and processes.
Minor air leaks will be repaired by the ship.
Small fires are suppressed by the ship.
The ship will close of bulkheads to contain raging fire, depressurization or radiation leaks.

The ship can only look after itself in a limited way.
Major events must be dealt with by crew.
Major hull repair, radiation clean up and passenger rescue need actual personas on board.

=== Life Bloat  
A life bloat will maintain 4 passengers (up to 250 kg in wate each) in cryogenic suspension for an indefinite length of time.
The cryogenic suspension will begin when the balloon-like life bloat is subject to exatmo.
There will be one life bloat for every four luxury passengers.

=== Sick Bay 
The sick bay is a vet's place of operation, and personal respite.
A sick bay can hold four patients and takes up two cabins worth of space.
A ship with an assigned ship's doc will have a sick bay.
Otherwise there is a 1% chance per organic persona that there will a vacant sick bay.

=== Machine Shop
The machine shop is a mechanic's place of operation and personal respite.
A machine shop requires two cabins worth of space.
There is a 5% chance per robot on board of having a machine shop.

=== Food Machine 
The food machine will generate nutritionally balanced meals for anything that eats.
The palatability of said foodstuffs is determined by the referee.
Most food machines employ algae, or fungal, cultures to create the basic heterotrophic food groups.
One tonne of machine is required for every 10 eaters supported.
Because of their potential for comic relief all ships will have a food machine.
Food machines are also known as compu-cooks, and auto chefs.
If the food machine is used enough it would be reasonable to give it a personality.

=== Robots 
Robots are a common occurrence on starships.
This is only the case if robots are suitable to the referee's milieu.
The robots can be on board to replace crew, to aid crew, or as paying guests.

The chance of a ship sporting a particular robotic replacement depends on the level of the space vehicle's computer, what sort of software the computer supports, plus what ever adjustments are appropriate for that type of robot.


A ship may have a whole host of robots, and the relevant ones should be prepared to the last detail as a referee persona hots.
Insane robots on a space ship could add to the mysteries of a campaign, or scenario.

include::ROOT:partial$CH52_Table_Spacer_Robots.adoc[]

== EXPS 
The EXPS value of a spacecraft is impossible to assess.
The expedition is considered to have earned a space vehicle once they have flown it somewhere.
The accepted EXPS award for an earned spaceship is one complete EXPS level.
This award is offered to all vocations.
Nothings are automatically propelled to zero level of their desired class.

== Value 
A space vehicle's value depends on several basic components: hull, drives, computer, etc.
Wear and tear may have reduced a ship to worthlessness in one culture, while another will pay dearly for anything that can get them into orbit.
Space vehicles are very valuable.
Space vehicles with powerful computers and special drives are worth enormous amounts.

include::ROOT:partial$CH52_Table_Space_Vehicle_Value.adoc[]

=== Example jump ship value
.200M eps = computer (10 * 10 * 1M) + special drive (100 * 10 * 10 * 10 * 100k)
****
A 100 tonner with level 10 computer and special drive. Only driven on Sundays by a little old alien.
****

== Operational Costs 
Space vehicle maintenance and operational cost are boring.
The main operational costs of a spaceship are wages, and fuel.
Maintenance carried out by the ship's engineer cost nothing, and are completed properly.
Replacing destroyed parts costs the same as the calculated value of the part.
Upgrading parts costs the same as the calculated value of the part.
The cost of parts will includes parts and labour.

:art: busy_bow_prop_repair.jpg
:width: 250px
:snark: Inatmo drive repair.
:artist: Ladrimal
:date: 1887 (yes 1887)
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

General refitting is necessary for alloy hulls.
Refitting will be required after extended travels, or after any combat.
Not refitting the space vehicle will lead to mechanical failure.
The refitting will cost between 0.01% and 0.1% (rolled on 1d10) of the ship's total value.
Woah that is a lot of cargo.
If the refitting costs were .05% of the ship's value then a space vehicle with a value of 500 000 000 would cost 250 000 to refit.
