= Inatmo Vehicles

A vehicle is essentially any machine designed to help personas get from point A to point B.
Inatmo vehicles operate within the atmosphere of a planet.
Unlike their outer space cousins (exatmo vehicles), inatmo vehicles operate in a planet's gravity well.
Personas drive these vehicles unless accessories indicate otherwise.

:art: vehicle_fnord_full.png
:width: 450px
:snark: Compact full track
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a boxy compact car with treads instead of wheels.

include::ROOT:partial$articulate.adoc[]

The player generates her vehicle randomly.
This randomness makes for wild and curious vehicles.
The vehicle type determines the gross appearance of the vehicle.
A cargo truck, a passenger sedan and a bicycle are easy to tell apart.
The vehicle use may be less apparent but influences what the vehicle can accomplish.
The vehicle creation system does not lend itself to on-the-spot artifacts.

The prevalence of the vehicles depends on the milieu of the referee's campaign.
Vehicles may pollute a suburban commuter campaign style or be an invaluable asset in a leather and dust campaign style.

The vehicle design is for anthro personas.
Every vehicle has an engine, a body, a braking system, a steering device, and some space for passengers.
The vehicle may also have a windscreen, roof, signal lights, instrument panel, and doors.
Vehicles created for an alien society would reflect the needs of that alien species.
Vehicles created for a robotic society would reflect the needs of that alien species.
The referee must exercise her creative muscle to accommodate cars for robots or gigantic alien species.

.*Vehicle Construction List*
. <<_vehicle_appearance,Vehicle Type>>
. <<_vehicle_purpose,Vehicle Purpose>>
. <<_speed,Speed>>
. <<_acceleration,Acceleration>>
. <<_locomotion,Locomotion>>
. <<_engine_and_fuel_type,Engine and Fuel>>
. <<_handling_level,Handling Level>>
. <<_accessories,Accessories>>
. <<_adaptability,Adaptability>>
. <<_exps,EXPS>>
. <<_value,Value>>

== Vehicle Type 
Vehicle type determines the appearance, shape and size of the vehicle.
Included with the vehicle type are passenger capacity, cargo capacity, and vehicle wate.
Vehicle type is a framework to start creating on.

include::ROOT:partial$CH54_Table_Primary_Format.adoc[]

=== Cargo Type

:art: alien_beasts_of_burden.png
:width: 450px
:snark: Low tech cargo van.
:artist: Morey
:date: 1962
:license: CC BY-SA 4.0
:description: Drawing of alien quadrupeds pulling wooden cart.

include::ROOT:partial$articulate.adoc[]

Cargo vehicles are devoted to the transport of things other than passengers.
Cargo vehicles are vans, trucks, and pick-ups. 
They have limited passenger capacity and have space for moving stuff.
The passenger portion of this vehicle is secondary to the cargo space.
The passenger cabin may, or may not, have access to the cargo hold.

include::ROOT:partial$CH54_Table_Cargo_Vehicle_Type.adoc[]

=== Leisure Type

:art: flying_naudosaucers.png
:width: 450px
:snark: Nice evening for a cruise.
:artist: Morey
:date: 1962
:license: CC BY-SA 4.0
:description: Drawing of two flying saucers in star lit sky.

include::ROOT:partial$articulate.adoc[]

The leisure vehicle is the most familiar vehicle type. 
Most mundane terran vehicle ownership is of the leisure vehicle type.
They include minis, sedans, coupes, motorcycles and mini-vans.
Leisure vehicles are designed for commuting, touring, or parking in front of a house.
They are primarily for passenger travel and have little space allotted for cargo.

include::ROOT:partial$CH54_Table_Leisure_Vehicle_Type.adoc[]

=== Passenger Type

:art: passenger_vehicle.png
:width: 450px
:snark: Where toad sir?
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid toad in driver seat of flying taxi cab.

include::ROOT:partial$articulate.adoc[]

The passenger vehicles are persona cargo vehicles.
They safely move anthros, aliens or robots from one place to another.
They have seating and some cargo space for passenger belongings.
Typical passenger vehicles are taxis, vans and buses.

include::ROOT:partial$CH54_Table_Passenger_Vehicle_Type.adoc[]

=== Self Powered Type

:art: darth_pogo.png
:width: 450px
:snark: Legalize skate boards.
:artist: Peggy Lynn McIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of skate boarder with caped humanoid on pogo stick.

include::ROOT:partial$articulate.adoc[]

These are engineless modes of transport that get the persona from A to B.
Self-powered vehicles employ gears, pulleys and elastics to get around.
These are not your ordinary self-powered vehicles since they can attain tremendous speeds.
Pogo sticks, bicycles, skateboards are typical self-powered types of vehicles.

include::ROOT:partial$CH54_Table_Self_Powered_Vehicle_Type.adoc[]

== Vehicle Type Parameters
These are the parameters that the vehicle type contributes to the overall vehicle function.

=== Appearance
The vehicle appearance only suggests a basic shape for the vehicle type.
The vehicle appearances match mundane terran vehicles of the same name.
Imaginative players should not limit themselves by the appearance of the vehicle type.
The appearance is a framework for function and not a defining appearance.

=== Passengers
The passengers' parameter represents the number of personas that can be safely seated in the vehicle.
Passenger-type vehicles have lots of passenger capacity.
Self-powered type vehicles have limited passenger capacity.

:art: non_powered_vehicles_antennae.png
:width: 450px
:snark: Self powered solo gondolas.
:artist: Ed Carter
:date: 1950
:license: CC BY-SA 4.0
:description: Drawing of two handsome antennae clad humanoids paddling on giant leaves.

include::ROOT:partial$articulate.adoc[]

Exceeding passenger capacity has adverse effects on vehicle handling and maneuvers.
There are also severe consequences for unrestrained passengers in vehicle collisions.

The seating capacity is for medium-sized anthro personas. 
Creating vehicles for gigantic robots or minute aliens will require referee maths.

=== Cargo
The cargo parameter indicates the amount of space for stuff.
Cargo capacity is a combination of wate and volume.
A vehicle may be able to manage additional wate but does not have space for the junk.
Cargo-type vehicles have enormous cargo capacity, while self-powered vehicles have almost none.

=== Wate
The vehicle wate parameter indicates the vehicle's unloaded wate.
Vehicle wate is important in collisions, terrain, transport, or running over stuff.
The wate of a vehicle is in kilograms or tonnes.
This measure is also called the Gross Vehicle Wate.
Massive accessories may increase a vehicle's wate.

==== Size and Shape
When using minis in the tactical combat system, the size of the vehicle becomes important.
A rough estimate of the vehicle's hex size is one hex per 200 kg of vehicle wate.
For example, a double-stretch passenger vehicle (articulated bus) needs 60 hexes of space. 
The hex mat space works out to 3 hexes wide by 20 hexes long.
Typically these hexes are arranged in a rectangle, but accessories and usage may alter this shape.

== Vehicle Purpose
The vehicle type gives the vehicle size and shape. 
The vehicle's purpose gives its reason to be.
Vehicle purpose determines the accessories and operating specifications of the vehicle.
The vehicle's purpose better reflects its present state.

A passenger vehicle type with a combat purpose could be a troop carrier. 
The appearance and structure modify further to reflect a troop carrier.
A leisure vehicle type with a high-performance purpose could be a race car.
The appearance and structure modify further to reflect a race car.
The referee and players are responsible for describing these elements.

include::ROOT:partial$CH54_Table_Secondary_Vehicle_Use.adoc[]

=== High Performance

:art: cool_cat_cool_car.png
:width: 450px
:snark: Cool cat. Cool car.
:artist: Kelly Freas
:date: 1955
:license: CC BY-SA 4.0
:description: Drawing of feline quadruped staring at boxy shaped floating car.

include::ROOT:partial$articulate.adoc[]

High-performance vehicles are souped-up, chromed-out rubber melting machines.
The vehicles are devoted to speed, acceleration, range, and maneuverability.
A leisure vehicle with a high-performance purpose could be a classic muscle car.
A passenger vehicle with a high performance purpose could be a limousine.


High performance vehicles get  +10% on acceleration, +20% on speed, and +2 on handling class.
High performance vehicles also get 1-3 rolls on the High Performance Accessories Table.
Accessory effects are cumulative.
Descriptions of acceleration, speed, and handling level appear later.

include::ROOT:partial$CH54_Table_High_Performance_Bonuses.adoc[]

=== Industrial

:art: van_turret_dust.png
:width: 450px
:snark: Don't text off road.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of hight speed van with a weapon turret on the roof driving off road.

include::ROOT:partial$articulate.adoc[]

Industrial vehicles have specific commercial purposes.
Whatever accessory the industrial vehicle gets determines its purpose.
A skateboard with a shovel accessory is a shovel with wheels.
A pick-up truck with a shovel accessory is a dirt-removing machine.
The industrial accessories will require some creative shoehorning, but hopefully, most are self-explanatory.

Every industrial vehicle gets at least one accessory.
Then there is a 50% of getting a second accessory, a 25% chance of a third accessory and a 13% chance of a fourth accessory.
The maximum number of accessories is four.

Each accessory adds 25% to vehicle wate. 
So four accessories would increase the vehicle wate by 100%.

include::ROOT:partial$CH54_Table_Industrial_Accessory.adoc[]

==== Accessory Weaponization
Players want to use industrial accessories as weapons.
There are no parameters for weaponizing industrial accessories.
Industrial accessories are not weapons, regardless of how powerful and sturdy they appear. 
The accessory may have safety features that prevent it from clobbering targets.
The device may suffer extensive damage when being used as a weapon. 
A mechanic would have to make modifications before weaponizing the accessory.
At that time, the players can decide what the accessories combat parameters are.

=== Combat

:art: tank_deflect_armour.png
:width: 450px
:snark: Tanks for the ride.
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of modern tank kicking up dust at speed.

include::ROOT:partial$articulate.adoc[]

Combat vehicles are tougher than other vehicles.
They resist being shot, crushed and intentionally abused.
A leisure type vehicle with a combat purpose could be a jeep.

Combat vehicles are combat-hardened.
They are harder to hit and harder to damage.
Combat use vehicles have an Defence Rating of 700. 
Combat use vehicles half all extent of damage rolls.
So a damage roll of 80 becomes a damage roll of 40.
The expected major damage becomes minor damage.

Combat use vehicles get 1-3 rolls on the Combat Use Accessory table.
Combat accessories integrate with the vehicle.
They are not detachable and would require a mechanic to remove them.
The combat accessories can define the vehicle as a tank or a jeep, or a driving bomb.

include::ROOT:partial$CH54_Table_Military_Accessories.adoc[]

=== Recreational
Recreational vehicles are for persona comfort.
A recreational use vehicle could be a camper or a limousine.
The player makes one roll on the Recreational Accessory Table. 
Most vehicles get one roll on the table.
Large vehicle gets an additional accessory per 20 passenger spots.
A recreational passenger vehicle that holds 60 passengers gets three extra rolls.

include::ROOT:partial$CH54_Table_Recreational_Vehicle_Accessories.adoc[]

== Speed 
Speed refers to the maximum speed that the vehicle can attain.
The vehicle's maximum speed is in h/u (which equals m/s).
The top speeds vary from 6 to 72 hexes per unit.
Maximum speed is weather agnostic, unless the referee has built-in weather speed limits.
The minimum speed is anywhere between 0 h/u and the maximum speed.
Maximum speed is no indication of safe driving speed.

The maximum reverse speed is 50% of the top speed.
All of these values are guidelines subjected to alteration by the referee.
A flying vehicle may not be able to float at 0 h/u in the air.
An enormous vehicle may have a much reduced reverse speed.
A water-borne vehicle may not be able to reverse at all.

=== Vehicle Maximum Speed
.speed = 6d12 h/u
****
Max speed = 6 + 6 + 6 + 6 + 6 + 6 = 36 h/u (130 kmh)
****

.*For convenience*
* 1 h/u = 1 m/s
* 1 h/u = 3.6 kmh
* 1 h/u = 2.2 mph
* 25 h/u = Gale force wind
* 45 h/u = 100 mph
* 342 h/u = Speed of sound

== Acceleration 
Acceleration indicates how much faster the vehicle can travel from one unit to the next.
The higher the acceleration, the more powerful the engine.
A high acceleration indicates the power of the engine exceeds the wate of the vehicle.
Acceleration generally requires maths.

:art: acceleration.png
:width: 450px
:snark: More faster each unit.
:artist: Michael Jackson, mod HM
:date: 1991, 2010
:license: CC BY-SA 4.0
:description: Drawing of small car with tracks driving out of the image frame.

include::ROOT:partial$articulate.adoc[]

For example, two vehicles have the same speed of 50 h/u.
Vehicle Won has an acceleration of 5 h/u per unit.
Vehicle Also has an acceleration of 10 h/u per unit.
If Won and Also have a drag race, the first four seconds would be as follows.
The first unit, Won travels five hexes, Also travels ten hexes.
The second unit, Won travels ten more hexes but Also travels 20 more hexes.

The outcome is different if the vehicles have different speeds and do laps and not drag racing.
Vehicle Won has an acceleration of 5 h/u per unit and a top speed of 50 h/u
Vehicle Also has an acceleration of 10 h/u per unit and a top speed of 20 h/u.
After ten units, Won will be going 50 h/u and quickly catches up because Also is going a mere 20 h/u.

====
It is best to avoid complex maths and do what is best for the story. 
====

=== Maximum Vehicle Acceleration
.acceleration = (10d20) / 10 in h/u
****
acceleration = 100 / 10 = 10 h/u each unit.
****

== Locomotion 
The locomotion of a vehicle is the external extension of the drive train. 
The locomotion is what acts on the environment to create movement.
The locomotion type determines if the vehicle travels on land, air or water. 
No vehicle is submersible unless specifically hardened for submersion.

There are typical locomotion types like wheels, tracks, and propellers.
EXP has many atypical locomotion types like antigrav, slog bag and chemical slide.
Sciency fiction explanations hint at how the typical and atypical systems work.

NOTE: *Self Powered vehicles do not have a locomotion type.*

:art: cargo_vehicle.png
:width: 450px
:snark: Anti-grav and air screws.
:artist: Moller / Format
:date: 1887 (yes "18" 87)
:license: CC BY-SA 4.0
:description: Drawing of wooden ship with air screws and propeller flying in the clouds.

include::ROOT:partial$articulate.adoc[]

=== Locomotion Type
The speed of a vehicle determines the locomotion options.
A slow-moving vehicle (10 h/u) uses the <15 h/u (left) column
A vehicle with a top speed of 30 h/u uses the middle column.
A speedy vehicle (200 h/u) use the >110 h/h  (right) column.

The brackets following the locomotion type indicate the number of wheels, balloons, or jets moving the vehicle.

include::ROOT:partial$CH54_Table_Vehicle_Locomotion.adoc[]

=== Complementary Locomotion Types
Some vehicles combine two locomotion types.
For example, a set of jet engines may move around a vehicle with wheels.
An asterisk " ^*^ " marks those locomotion types that can have a complementary locomotion type.

include::ROOT:partial$CH54_Table_Vehicle_Secondary_Locomotion.adoc[]

:art: Inatmo_vehicle_industrial.png
:width: 450px
:snark: Antigrav does not mean sleek.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Floating junker vehicle with mini crane and broken sign.

include::ROOT:partial$articulate.adoc[]

=== Antigrav (1)
Antigrav is a classic sciency fiction mode of travel
The vehicle can travel about as though gravity does not affect it.
As ideal as antigrav is, it will only function within a gravity well.
The vehicle has no apparent mechanisms that create its buoyancy in gravity.

Complementary antigrav supplies buoyancy, and the locomotion type moves the vehicle.

Antigrav is an air based locomotion.

=== Balloons (1d12)
Balloons offer both movement force and maneuverability to the vehicle.
The balloons appear very dynamic, inflating and deflating rapidly to change direction and move the vehicle.

Complementary balloons supply buoyancy and the locomotion type moves the vehicle.

Balloons are air based locomotion types. 

=== Chemical slide (1)
The chemical slide allows the vehicle to slide along any surface effortlessly.
This process leaves a quickly evaporating trail, not unlike a giant slug.
This comparison does not necessarily imply the vehicle will be slow.

A complementary chemical slide provides a frictionless surface, and the locomotion type moves the vehicle.

The chemical slide is a land and water based locomotion.

=== Electromagnetic legs (1d4)
Electromagnetic legs are visible beams of energy lift and propel the vehicle.
These legs keep the vehicle about a meter off the ground. 
Electromagnetic legs keep the vehicle level on varying terrain and offer a very stable ride.

Electromagnetic legs are a land based locomotion.

=== Jets (1d4+1)
Jets force gases at high speed to generate movement.
The jets create thrust and maneuverability.
Jets are intake-less and do not eject dangerous super-heated propellants.
Cosmetic wings can accompany jets to resemble mundane terran jet planes.

Jets are an air based locomotion.

=== Magnetic (1)
A magnetic locomotion unit allows the vehicle to hover above the ground at a fixed height.
The vehicle cannot hover more than one hex above the ground.
The magnetic drive keeps the vehicle level on varying terrain and offers a very stable ride.
Vehicles with magnetic locomotion will often float around long after their destruction.

The magnetic drive is a land and water based locomotion.

=== Pistons (1d10)
Pistons quickly poke up and down, keeping the vehicle balanced and moving.
The ride is not a rough one, but from the outside may look chaotic.
The pistons are immaculately timed and keep the vehicle stable.

Pistons are a land based locomotion. 

=== Pods (4d4)
Pods are mechanical legs with multiple articulations.
The articulated poles hop, scuttle or patter the vehicle around.
The ride is not a rough one, but from the outside may look chaotic.

This locomotion type is land-based. 

=== Propellers (1d6)
Propellers are quiet, safely encased airscrews.
The propellers offer thrust and maneuverability to the vehicle. 
Cosmetic wings can accompany propellers to resemble mundane terran planes.

Propellers are an air based locomotion.

=== Sails (1d3)
Sails are very sturdy, electro molecular planes that catch air for movement.
Vehicle sails operate perfectly well in a raging wind or a dead calm.
The sails offer thrust and maneuverability. 

Sails can be air, land or water based locomotion, but only one of the three.

=== Skis (1d4+2)
Skis are attached to articulated pods that skate the vehicle over terrain.
There is no difference in speed whether the vehicle is trotting uphill or sliding down slopes.

Complementary skis offer a contact surface for locomotion while the primary locomotion type moves the vehicle.

Skis are a land and water based locomotion.

=== Slog bag (1)
A slog bag appears like a fluid-filled sack attached to the undercarriage of the vehicle.
However, it does not contain a liquid.
The slog bag moves like a sack of mercury and undulates and contorts itself along the surface.

The slog bag is a land and water based locomotion type.

=== Tracks (1d6)
Tracks look like and are nothing more than rubber-coated tank tracks.
Each track operates individually, and they coordinate to generate force and maneuvers.

Tracks are a land based locomotion type.

=== Wheels (1d12)
They are solid, puncture-proof and can roll across any terrain.
Each wheel operates individually, and they coordinate to generate force and maneuvers.

Complementary wheels offer a contact surface and maneuvers the vehicle, while the locomotion type provides the thrust.

Wheels are a land based locomotion type.

:art: spacevehicle_climbing.png
:width: 450px
:snark: A school bus for oppressors
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a wheelless military troop transport flying at fourty five degrees. 

include::ROOT:partial$articulate.adoc[]

=== Air Based Locomotion
Air based locomotion indicates the ability to fly supported by gas, most commonly air.
Air based locomotions cannot drive on land or water.
They may slowly taxi on land but only make speed while in the air.

Air based locomotion indicated a vehicle has flight and can travel in three dimensions.
Three-dimensional movement and adds massive complexity to tactical combat.
The referee may ground air based locomotion types to preserve game balance.

=== Land Based Locomotion
Land based locomotion vehicles can only drive on solid ground.
Land based locomotion is the most common type of locomotion on mundane terra.

=== Water Based Locomotion
Water based locomotion allows the vehicle to travel over liquid, most commonly water.
The mundane terran form of this travel is a boat.
If the vehicle has water only locomotion, it will harbour many boat like qualities. 

== Engine and Fuel Type
The engine determines the fuel type, and they are intimately connected.
The engine powers all aspects of the vehicle.
Locomotion and all accessories get their energy from the engine.
As the engine operates, it burns fuel.

There are typical fuels and atypical fuels. 
Some engines require refitting as opposed to refuelling.
Coils get demagnetized, rubber bands wind down, and fuel tanks empty.
Refitting and refuelling are primarily cosmetic, and it is the same difference to keeping the engine running.

include::ROOT:partial$CH54_Table_Fuel_Type.adoc[]

:art: motocycle_cyberpunk.png
:width: 450px
:snark: Donor cycle 2077
:artist: James Shields
:date: 2014
:license: Copyright JEShields Stock Art
:description: Drawing of human on motorcycle making a sharp turn.

include::ROOT:partial$articulate.adoc[]

== Handling Level 
The handling level of a vehicle is the combination of the elements of maneuverability, responsiveness and stability.
Handling level includes steering sensitivity, brake response, traction, balance, and chassis design.
The higher the handling level, the better the chance of success with driving maneuvers.
Driving is a unique subset of the performance rolls and has its own ruleset. INSERT

NOTE: Handling Level was formerly known as maneuverability*

High performance vehicles adjust their handling level upwards after rolling the handling level.

include::ROOT:partial$CH54_Table_Handling_Level.adoc[]

== Accessories
Accessories are a collection of annoying to wonderful additions to a vehicle.
An accessory can be junk that adds character or a game-changing artifact that defines the vehicle.

:art: lamps-albatross.png
:width: 450px
:snark: In Seine lighting
:artist: Leon Bennett
:date: 1887
:license: CC BY-SA 4.0
:description: Drawing of a maritime sailing ship flying above paris lighting the sky with searchlights.

include::ROOT:partial$articulate.adoc[]

The player gets one roll on the Accessory Type Table.
Junk Accessories do not count as a roll.
The player stops rolling if she has three junk accessories, one mundane or one artifact accessories.

include::ROOT:partial$CH54_Table_Accessory_Type.adoc[]

include::ROOT:partial$CH54_Table_Junk_Accessories.adoc[]

include::ROOT:partial$CH54_Table_Normal_Vehicle_Accessories.adoc[]

include::ROOT:partial$CH54_Table_Special_Vehicle_Accessories.adoc[]

== Adaptability 
Adaptability represents how easy the vehicle is to repair and add new parts.
Adaptability improves the degree of difficulty of any performance rolls.
The adaptability is multiplied by four and added to the mechanic's Maneuver Roll.
Adaptability ranges from +5 (very adaptable) to -5 (very unadaptable).

=== Calculating Adaptability
.Adaptability = 1d6 - 1d6 (range +5 to -5)
****
Adaptability = 6  - 4 = +2. Bonus = 2 * 4 = +8 on performance roll.
****

== Parts
Mechanics often find themselves repairing engines. 
Parts will match if the vehicle type and fuel types match. 
An engine block for a semi-trailer would not be compatible with that of a pick-up truck.
The referee would also be allowed to consult the INSERT.

== EXPS 
Vehicles have no EXPS value for most personas.
Their reward is allowing the expedition to get around and therefore get more EXPS in other ways.
Nothings can earn experience for driving their first vehicle.
Nothing vehicle EXPS is one EXPS Level or 4242 EXPS towards her Zero Level Vocation.

== Value 
The base value of a vehicle is 10 000 per tonne. 
Vehicle, type, use and accessories increase the value of the vehicle.

include::ROOT:partial$CH54_Table_Vehicle_Value.adoc[]
