= Roll vs Role Playing

[quote]
____
*A tale of two systems*
____

EXP has two play tested sets of rules.
The oldest rule set is the tactical combat system.
The tactical combat system works best with hex paper and miniatures and uses a 1d1000 for attack rolls. 
The tactical combat system is detailed, dice heavy, and is the basis for the technology and mutation sections' details. 

The next oldest rule set is the theatrical combat system.
The theatrical combat system is a simplified version of the tactical combat system.
The theatrical combat system simplifies the tactical combat system by using simpler dice.
The theatrical system works with hundred sided, twenty-sided, ten-sided and six-sided dice.
The theatrical system sacrifices detail and subtly for speed and fun.
The theatrical combat system now has it's own dice mechanic, but dividing down the kilodie is still an option. 

== New Words For Old Things
The most significant change in version 6.0 is the renaming of these two rule sets.
They have been teased apart and given decidedly confusing names: Roll Playing Rules and Role Playing Rules.
Each system is fun for different reasons.
The whole point of roleplaying games is to have fun.

== Roll Playing Rules
The Roll Playing Rules use the tactical combat system and the xref:i-roll_playing_rules:CH00_kilo_die_mechanic.adoc[Kilodie Mechanic, window=_blank].
This ruleset works best on hex paper using miniatures and would enjoy integration with a virtual tabletop. 
The Roll Playing Rules depend on the roll of the dice.  
The dice direct most of the outcomes. 
A lot of arithmetic and reading is required. 
Onboarding of new players requires patience and supportive teaching. 

.*Roll Playing Rules are for you if...*
* You have played previous RPGs
** If you don't know what an RPG is, maybe Roll is not for you
* You like to roll dice
* You are not afraid of arithmetic
* You like details

== Role Playing Rules
The Role Playing Rules use the theatrical combat system and the xref:ii-role_playing_rules:CH26_Fourdeetwo.adoc[4D2 Mechanic, window=_blank].
The rule system does not require miniatures or hex paper but works fine with both.
The Role Playing Rules do not depend on the dice for decisions.
The players specifically describe the outcomes in this ruleset.
There are few tables, and only simple arithmetic is needed.
The most complicated arithmetic is adding and subtracting single digit numbers.
The persona record sheet is composed of words and almost no numbers.
It only takes a few minutes to create a persona, and the game mechanics are intuitive.
Onboarding of new players is immediate.

.*Role Playing Rules are for you if...*
* You have played board games and can roll six-sided dice
* You are dice averse and would rather talk
* You are not fond of remembering numbers
* You don't care too much about details




