= Playing EXP

:art: old_school_rpg.png
:width: 250px
:snark: Peak 1980s.
:artist: Unknown
:date: 1990
:license: CC BY-SA 4.0
:description: Female referee standing and directing a role playing game.

include::ROOT:partial$articulate.adoc[]

The first introduction to EXP was very long.
There were very few roleplaying games.
There was no internet.
There were no cell phones.
There were no laptops.
Very few people knew what an "RPG" was, and those that did feared them.
Much of the first introduction explained how EXP fits into society.
Today there are thousands of roleplaying games.
They are on tabletops.
They are on computer screens.
They are on phones.
They are in virtual reality.
Today "RPG" means roleplaying game and not a rocket-propelled grenade.

== What does EXP mean?
The working title of the homebrew was EXP1000.
EXP stood for EXPerimental, EXPerience points and EXPeditions.
Roleplaying was an important source of EXPerience points. 
It was unique at the time to award experience for anything other than combat success.
The players formed EXPeditions instead of parties.
Combat employed a 1000 sided die instead of a 20 sided die.
EXP proved easier to say than EXP1000.
The extensive artifact system became the centrepiece of the game, and the official title became "EXP: The game of technological chaos." 

== Why do such a thing?
In the 1970s, science fiction was not a large part of the roleplaying world.
There was a game called Dungeons and Dragons, which was a collection of tiny incomplete booklets.
Traveller was also a disorganized collection of tiny booklets.
We were fans of post-apocalyptic speculative fiction, especially anything with mutants and robots.
The author James Ward came to our rescue with Metamorphosis Alpha and Gamma World.
We loved the concepts but not the rules.
EXP1000 was entirely derivative from those two games.
We used miniatures and hex paper to sort out combat.
The system reflected the meticulous war games of the day.
Combat resolution was tactical, detailed, and obsessive.
A twenty-sided die was not refined enough for us.
We devised a thousand sided die by rolling three ten sides.
The 1 to 1000 range allowed us to give subtle bonuses or penalties on the hexagonal mat.
EXP mashed Metamorphosis Alpha, Gamma World and tactical miniature combat into one book. 

== EXP as a reference book
In the 1980s, roleplaying games became an industry. 
Publishing houses needed to create content in the form of books. 
The economics of publishing force the houses to break systems into parts called supplements and modules.
EXP chose not to follow this path.

.*EXP Followed these principles*
. Create a generic sciency fiction roleplaying game.
. Create one tome that contained all content.
. Wait decades for this internet thing to catch on.

Initially, EXP was a book. 
Books were costly to print.
Technology has advanced, and we no longer have to print a 777 page book.
The Intertubes and open source licensing has allowed EXP to be available to all.
Version 6.0 is a rewrite and a move to technologies that will allow EXP to be readily shared.

EXP is no longer a book but a living document that will:

. Be kept in a versioned repository.
. Be free and open source.
. Allow for multiple authors.
. Be downloadable as a book or website.

== Newbies
This section used to be labelled Neophytes.
The section included explanations of how to start a group etc.
Roleplaying games are everywhere today.
Today to get started roleplaying, one needs only ask around at the local game store or chat room.
You are guaranteed to find like-minded folks.
Although they are unlikely to be playing EXP.

Be safe and have fun.

== Concerned Parents
In the 1990s, every roleplaying game had a section that tried to calm concerned parents.
A bored media created a moral panic around roleplaying games, and police forces raided game producers. 
Today parents are concerned if their children are *not* playing roleplaying games.
Today, families, churches, libraries and game stores all host roleplaying games.
Roleplaying games improve numeracy, literacy, creativity and social skills.
A concerned parent today buys, downloads or creates a roleplaying game to play with the whole family.

== Style of EXP
EXP, the game of technological chaos, is a sciency fiction roleplaying game. 
If you think of a roleplaying game's style, you think of its mythos and ruleset.
EXP has a generic mythos.
The system is for players that want to create their own story. 
EXP ruleset has many detailed resolution systems.
These resolution systems vary from insidiously complex to refreshingly simple. 
The system is for players that want to build their own house rules, and EXP works fine using a fraction of its ruleset.

If the following paragraph works for you, then EXP will work for you.
A humanoid gorilla, a robot and a tentacled alien run into a spaceship's bar.
On their heels are a group of angry mutants driving a stolen yellow bus.
The gorilla fires her laser rifle at the yellow bus.
The tentacled alien spits poison at a mutant leaning out a window.
The robot activates her electronic countermeasures.
An angry mutant launches the psionic attack mental blast at the gorilla.
The yellow bus driver fails to navigate in the parking lot and crashes the yellow bus. EXP has integrated rules for all of these shenanigans in one ruleset. 

== EXP is silly
Roleplaying is supposed to be fun.
EXP is not hard science. 
EXP is pseudo-science, sciency fiction or even silly science.
The families, rules and technology are ironic and border on the ridiculous.
The element of randomness is endemic in all of EXP's rules.
This random factor ensures that EXP proudly crosses the border of ridiculousness.
EXP wallows in the pink and green light of the absurd.
There will be nuclear-powered toasters, combat robots with welcome mats, and fun-loving aliens. 

== EXP is Very Random
Personas are determined randomly.
The players adapt to their random personas.
Technological equipment is determined randomly.
The technological level of equipment is determined randomly.
Mutations are acquired randomly.
The game has a whole lot of dice rolling that is best suited for computer assistance.
It has only taken 40 years, but computer assistance has arrived and is plentiful.

[quote]
____
*EXP is the game of technological chaos.*
____

== Personas
The persona is the tool that the player uses to interact with the game. 
The persona is called a character or avatar in other types of roleplaying games.
Each persona has attributes, a type, a vocation, and some tools.
The player employs these elements to play the game. 
Players generate their personas in EXP by rolling dice.
These dice rolls determine the persona's structure, and the player fills in the backstory, appearance, and goals.

=== Attributes
The persona's attributes are determined randomly. 
A persona's attributes are called statistics in other types of roleplaying games.
Example attributes are physical strength, intelligence, charisma. 
The higher the value, the stronger, smarter, and more handsome the persona.

===  Type
The persona has a type that describes how she looks. 
The persona type is called race or species in other types of roleplaying games.
There are three different family types in EXP.
The family types are anthros (like us humans), aliens (monsters and creatures) and robots. 
The persona type goes a long way in the description of the persona. 
However, the details are still up to the player.
For example, if she is a humanoid bird, what kind of bird does she look like?

=== Vocations
The persona has a vocation that describes what she excels at.
The persona vocation is called a class, or job, in other types of roleplaying games. 
Vocations have no built-in backstories like schools or monasteries, or training programs.
The players must fill in these elements if they feel it is needed.
The vocations in EXP are very generic.
Example vocations are biologist, mercenary, mechanic, etc.
As the player accomplishes more goals, the persona becomes better and better at their vocation. 

=== Tools
Personas usually start out with some mysterious equipment to start the technological chaos rolling.
In EXP, any device can appear at any time alongside any other device.
For example, the persona could be in possession of a six-shooter pistol and a psionic headband at the same time. 
Often personas will be in possession of unidentified devices.
Unidentified devices are called artifacts in EXP.
Artifacts can be fun, funny, dangerous, and or valuable. 
The players need to figure out these artifacts without blowing themselves up. 

:art: alien_not_aliens.png
:width: 450px
:snark: Military machine gun maternal mommy.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Woman on spaceship holding machine gun in right hand and little girl on her hip.

include::ROOT:partial$articulate.adoc[]

== Her, him, huh?
In the olden daze, roleplaying games were dominated by young men. 
Regarding roleplaying games in the olden daze, using the term dominated is an understatement.
In an effort to make the world a slightly better place, the language of   EXP moved to be more inclusive. 
This was the 1990s kind of 'trying to be inclusive.'

The writing shifted to the pronoun 'her.' 
This was felt to be more inclusive because the pronouns her and she both included the pronoun he.
Using the pronoun 'her' was quicker and easier than other solutions at the time.

Roleplaying games must intentionally become more welcoming, and should create a safe space for all genders, races and sexualities. 
Using the pronouns 'her and she' was prescient and is now outdated. 
Our actions must be more intentional and systemic than just changing some words.
Talk minus action equals nothing. 

== Introductory Glossary
Here is an abbreviated glossary of terms, abbreviations, that will help players onboarding the language of EXP.
There are more exhaustive, and exhausting, xref:vi-appendices:Appy_A_Glossaries.adoc[Glossaries,window=_blank] in the appendix. 

//is it a getting started term or abbreviation

Alien:: 
Aliens are one of the three families in EXP.
They are organic creatures of unusual shape and size.
They are alien to us but not to themselves.
These are the tentacled, furry, floating horse creatures.
Only experienced players should try playing alien personas.

Anthro:: 
Anthro is short for anthropomorph.
Anthros are one of the three families in EXP.
They are upright and bipedal, and function the same as homo sapiens.
They are phenotypically humanoid versions of creatures from the animal world.
Players are most familiar with playing anthro personas.

Area of effect:: 
Some attacks can affect multiple targets at once. 
This is an area of effect attack.
Grenades are the most famous area of effect weapons
The area of effect is measured in hexes and is described in each weapon or mutation.

Artifact::
A piece of technology that has value due to it's technological ability. 
If the piece of technology has not been identified it is referred to as an artifact.
Once identified an artifact becomes a piece of equipment.

Attack Type::
There are different ways to attack in combat. 
Attack types are differentiated by how they inflict damage. 
A punch is different from a bow which is different from a gun.

Attributes:: 
These are the imaginary divisions of a persona’s physical abilities.
The attributes in EXP are: awareness, charisma, constitution, dexterity, intelligence, physical strength, mental strength and hit points. 
They are also called statistics.

Awareness:: 
This an attribute of a persona.
It represents how alert the persona is. 
Awareness is often abbreviated AWE.

AWE::
Abbreviation for awareness.

Bot:: 
Shortened version of the word robot. 
Robots are inorganic creatures of metal and computer intelligence. 

Campaign:: 
This is the story generated by the referee and the players.
A campaign is built from scenarios.
The scenarios can involve many personas and different locations. 
A campaign can last for months or years.

Charisma::
This is an attribute of a persona.
Charisma represents the charm, looks and leadership of the persona.
It is abbreviated CHA.

CHA::
Abbreviation for charisma.

Constitution::
This is an attribute of a persona.
Constitution represents the internal physique of the persona.
It is abbreviated CON.

CON::
Abbreviation for constitution.

Decidie::
Pronounced decki die, this is a legacy name for a 1d100.

Dexterity::
This is an attribute of a persona.
Dexterity represents the agility, balance and reflexes of the persona.
It is abbreviated DEX.

DEX::
Abbreviation for dexterity.

Dice:: 
* 1d4 - A four sided die. Looks like a pyramid.
* 1d6 - A six sided die. The famous cube.
* 1d8 - An eight sided die. It does not look like an octopus.
* 1d10 - A ten sided die. This die is used to create 1d100 and 1d1000
* 1d12 - A twelve sided die. 
* 1d20 - A twenty sided die. The largest of platonic solids.
* 1d100 - Two 1d10s (tens and digits) are rolled to create a 1d100.
* 1d1000 - Three 1d10s (hundreds, tens and digits) are rolled to create a 1d1000.
* Kilodie - Another name for a 1d1000

include::ROOT:partial$CH01_Table_Gravity_Dependent_Random_Integer_Generators.adoc[]

Die roll:: 
A die roll indicates that a random number must be generated. 
The players grab the appropriate gravity driven random integer generator.
The die is rolled onto the table and the random integer is revealed.
Hence the term die roll.

Exatmo:: 
Short for exterior to atmosphere.
Anything that takes place in the vacuum of outer space. 

Expedition::
A group of personas that have joined forces as a cohesive organized team.

Experience Points:: 
Experience is a combination of learning, maturation and training.
Experience is measured in experience points. 
The more experience points a persona has the better they are at stuff. 
A persona with higher experience will be more successful at combat and skills. 
Experience points are earned through successful die rolls and role-playing. 
This is often abbreviated EXPS.

EXPS::
Abbreviation for experience points.

EXPS Level::
The persona's experience level.
The more experience points the higher the level. 
The higher the level the better the persona is at stuff.

Family:: 
The three families in EXP are anthro, alien and robot.

h::
Abbreviation for the word hexagon, aka hex.

Hex:: 
A hex, short for hexagon. 
The hexagon is a six sided figure.
Hexagons can interconnect to create a hex field. 
The hex field is used to portray tactical combat on the table top. 
A hex equals 2 metres. 

Hexes per Unit (h/u):: 
This is an arbitrary measure of movement in EXP. 
It is equal to m/s.

HIG:: 
High gravity.

Hit Points (HPS):: 
The persona’s hit points indicate how much damage she can take. 
A persona with many hit points can sustain a lot of damage. 
A persona loses hit points when she is hurt. 
If a persona loses too many hit points they die.

Hite:: 
A unique measure to EXP that means height.
It can also be used to compare sizes regardless of family type.
Hite is recorded in centimeters (cm).

HPS::
Abbreviation for the word hit points.

hu::
Abbreviation for the speed measurement hexes per unit, AKA h/u

Inatmo:: 
Short for in atmosphere.
Anything that takes place in normal atmosphere. 

Intelligence::
This is an attribute of the persona.
Intelligence represents smarts, memory and deductive powers.
It is abbreviated INT.

INT::
Abbreviation of the word intelligence.

Intensity:: 
Intensity represents how strong a poison or psionic attack is. 
The higher the intensity, the more dangerous the attack.

Kilodie:: 
A Kilodie generates a random number between 1 and 1000. 
A kilodie is also called a 1d1000.
A roll of 0, 0, 0, would indicate 1000.
The kilodie is composed of three ten sided dice:
* 1d10 is the 100s
* 1d10 is the 10s
* 1d10 is the 1s

include::ROOT:partial$CH27_Table_Tactical_Kilo.adoc[]

Level:: 
A short form of experience level.
A persona's level represents how good she is at combat and skills.
The experience level increases with the persona's experience points.

Mental Strength::
This is an attribute of the persona.
Mental strength represents will power, resilience and psionic connection.
It is abbreviated MSTR.

Milieu::
The milieu is the description and social mechanics of the fantasy world the persona's interact with.
The referee creates most of the milieu with descriptions and backstories.
The players contribute and shape the milieu through their personas.

Miss:: 
A miss is any failed roll.
A failed attack roll is called a miss.
An unsuccessful poison defence roll is a miss. 

Movement:: 
Movement is the changing of position of personas during combat. 
Each persona has a movement rate in hexes per unit.
This is the speed of the persona.

MSTR::
Abbreviation of the word mental strength.

Mundane Terra::
Earth. 
The most likely place you are reading this.

Mutation:: 
Mutations are imaginary biological adaptations.
They can give personas imaginary powers or defects.
For anthros mutations are unique changes to that persona.
For aliens mutations are unique biological skills of the species.
For robots mutations are wildly malfunctioning peripherals.

Persona:: 
The persona is the representation of the player in the imaginary world.
The persona can be controlled by a player or a referee.
Each persona is made up of attributes, description and story.

Percentiles::
Percentiles and percents are a legacy name for a 1d100.

Persona Record::
This is the persona record sheet.
It is a piece of paper or computer thingy that stores the persona's info.
Also called a character sheet.

Phenotype::
Phenotype is the physical appearance of an organism. 
In EXP life forms are arranged phenotypically, or by appearance. 
Anthros are all humanoid, robots look mechanical and aliens look alien. 
This ignores biology for purpose of telling fun stories. 

Physical Strength::
This is an attribute of the persona.
Physical strength represents leverage, power and external physique.
It is abbreviated PSTR.

Post Factualization::
Reverse improvisation to explain something that happened after it has happened. 
Commonly needed by referees when story and pseudo science need to be synched.

Player:: 
You, the reader. 
The real world persona that controls the fantasy world character called a persona.

PSTR::
Abbreviation of the word physical strength.

Ref::
Short for referee. 
This is a player that is burdened with creating the milieu and puzzles of the campaign.
The role of referee is typically played by one player.
However the role of referee can be rotated or shared amongst multiple players.

Referee Persona (RP):: 
A persona that is generated and played by the referee. 
It includes aliens, anthropomorphs and robots. 
These are also called non-player characters.

Ref's Own Table:: 
This comment is found on tables used to generate EXP chaos.
It indicates that the referee and players should create something new. 

Robot:: 
Robots are inorganic creatures of metal and computer intelligence.
One of the three families in EXP.
Robots develop consciousness through malfunction. 
Robot personas should be limited to experienced players. 

Run::
Run refers to players getting together and playing EXP.
Run also refers to playing (or running) a persona.
A run is also called a scenario.

Scenarios:: 
Scenarios are the stories and challenges that take place in the game.
A scenario could be combat, puzzles, or some combination. 
Enough scenarios will build a story arch called a campaign.
These can also be called runs.

Toys/TOYS:: 
Toys are devices which personas use to gain strength and power.
Toys are like magical items from fantasy games.
Toys are created on the Technological Object Yield System.

Unit:: 
The unit is the smallest component of combat time in EXP. 
All personas will move, attack or do part of something during each unit. 
A unit of combat may take ten minutes or an hour of real time to play.
The combat unit is 2 seconds.

u::
An abbreviation for the measure of time unit. 

Vocation:: 
This is a collection of innate abilities that the persona has.
A vocation could arise from innate skill, training or school. 
Also called a class.

Wate:: 
A unique spelling of the word weight in EXP., 
The wate includes inertia, mass, and general size. 

ZOG:: Zero gravity.

