= Roll vs Role Playing

[quote]
____
*A tale of two systems*
____

== Roll Playing and Role Playing 
A comparison between the two.
To be fleshed out as rules are edited.
Much is learned from editing.

.how they are the same and different
* tale of two systems tactical vs theatrical
* both are valid not a platform war
* use mix of both.
* persona on the line? roll playing
* pulled apart for ease of use

* both are about fun. 
* the whole point is to have fun
\
.Roll Playing and Tactical Combat
* exp's origin comes from complicated combat.
* values player personas
* die rolls for everything
* we like dice
* we are not afraid of arithmetic
* helps decide outcomes, not blaming referee or players
* balances personalities randomizer is the equalizer.

== Roll Playing Rules
* all your rolls are belong to us
* *outcomes* decided by dice and tables.
* outcomes not decided by referee thinkspace
* justification and post factualization
* From the outset both methods of play are equally valid.
* details details details

== Role Playing Rules
* role playing always part of EXP
* the desired story of the ref and players wins
* less random 
* EXPS for role playing
* theatrical combat system
* charisma and privilege tends to win
* not everyone is articulate enough


// One is no better than the other. 
// One is no more fun than they other.

Both combat systems are integrated into the technology of the game, and both are fun to play.
They are fun to play for different reasons.


The two rule sets are interchangeable.
The tactical combat system can be used when space and time allow.
The same campaign can use the theatrical system for combat in a different place or time. 


== The Old Stuff
EXP offers both a theatrical, and a tactical combat systems.
The theatrical system is presented first, because it is easier to learn.
Both formats explain in detail all the elements of their combat system.
This way neophytes can start out with either system.
It is recommended that new groups start out with the theatrical system.
It prompts fewer (i.e.
leaves more time for) potentially argumentative situations.
Eventually you'll find that one system will best suit your group.
It is expected that most groups of gamers will find that the inadequacies of the theatrical combat system will force them to look to the tactical one for increased realism.
The artifact technology section is better suited to the tactical combat system.

== Theatrical Combat System
This combat system does not require figures or detailed maps.
The process is very fast, compared to the tactical combat system, and leaves more time for vivid descriptions from the referee, and the players.
More importantly it leaves more time for the campaign to focus on things other than combat.
This is definitely the easier of the two combat systems to learn, but it not necessarily designed just for beginners.
Experienced players that don't like combat, and don't feel it is worth the energy meticulously resolving combat may prefer the theatrical combat system.