= Playing EXP

// formerly known as chapter 1 Playing EXP.

The first introduction to EXP was very long.
There were very few role playing games.
There was no internet.
There were no cell phones.
There were no laptops.
Very few people knew what an "RPG" was and those that did feared them.
Much of the first introduction explained how EXP fits into society.
Today there are thousands of role playing games.
They can be played on table tops.
They can be played on computer screens.
They can be played on phones.
They can be played in virtual reality.
Today "RPG" means role playing game, and not rocket propelled grenade.


== What does EXP mean?

The initial working title of the game was EXP1000.
EXP stood for EXPerimental and EXPerience points.
EXPerience points were awarded for story and role playing. 
It was unique at the time to award experience for anything other than combat success.
1000 represented using a 1000 sided die in combat.
It was shortened to EXP, and then lengthened to EXP The game of technological chaos. 

== Why do such a thing?

EXP was done because it was not there.
There was only a game called Dungeons and Dragons. 
The tiny booklets were incomplete.
We were avid fans of science fiction.
Science fiction was limited to books, broadcast television and theatres.
The company called TSR released two games by the same author (James Ward).
These were Metamorphosis Alpha and Gamma World.
We loved the concepts but not the rules.

EXP1000 was completely derivative from those two games.
As players we used miniatures on hex paper to sort out combat.
Our combat was highly influenced by the meticulous war games of the day.
Combat resolution was tactical, detailed, and obsessive.
A twenty sided die was not refined enough for us.
We simulated a one thousand sided die by rolling three ten sides.
This allowed us to give subtle bonuses or penalties.

Once role playing games became a fledgling industry EXP made a few choices:

. Create a universal role playing game
. Create a single book rule set
. Force players to gather and create their own games

== EXP as a reference book.

EXP was initially created as a reference so players could role play together.
Initially it was a book. 
Books were very expensive to print.
Technology has advanced and we no longer have to print a 777 page book.
The intertubes and open source licensing has allowed EXP to be available to all.
This version is a rewrite and a move to technologies that will allow EXP to grow.

EXP is not longer a book but a living document that will:

. Be kept in a versioned repository
. Be free and open source
. Allow for multiple authors
. Be downloadable as a book or website

== Newbies

This used to be labelled Neophytes.
There were explanations of how to start a group etc.
Role playing games are everywhere today.
To get started simply ask around.
You are gauranteed to find like minded folks.
They are unlikely to be playing EXP.
Better to start off with some friends rather than complete strangers.
Be safe and have fun.

== Concerned Parents

This section was originally written during a moral panic surrounding RPGs. 
Today parents are concerned if there kids are *not* playing RPGs.
Entire families play together. 
RPGs have been shown to improve numeracy, literacy, creativity and social skills.
A parent today would simply buy, download or make up and RPG and start playing with their kids.

== RPG style of EXP

// general introduction
EXP the game of technological chaos is a science fantasy role playing game. 
While EXP has many detailed resolution systems it is not particularly serious.
The base rule set is written with the most detailed solutions in mind.
Most of the resolution systems allow for spectacular successes and failures.
The rule sets are flexible, generic, and interoperable.
There are always simpler, faster and possibly more fun ways to resolve the story.

A humanoid gorilla, a robot and tentacled alien walk into a bar.
That bar is on a space ship that is being chased by a school bus of mutants.
The gorilla fires her laser rifle at the school bus.
The tentacled alien spits poison at the driver..
The robot fires up her electronic counter measures.
All the personas could use their mutations against each other.
The space vehicle fires it's naval cannon at the school bus.
The combat session is suddenly over.

All of these elements are integrated into one rule set.

=== EXP is silly

Role-playing is supposed to be fun.
EXP is not hard science. 
EXP is pseudo-science, science fantasy or even silly science.
The races, rules and technology are tongue in cheek and border on the ridiculous.
The element of randomness is endemic in all of EXP's rules.
The personas and technology are generated randomly.
EXP has been waiting decades for the computer support it needed.
This random factor ensures that EXP proudly crosses the border of ridiculous'
EXP wallows in the pink and green light of the absurd.
There will nuclear powered toasters, combat robots with welcome mats, fun loving aliens. 

*EXP is the game of technological chaos.*

// nature and depth of randomness
=== Very Random
Personas are determined randomly.
The players adapt to their random personas.
Technological equipment is determined randomly.
The technological level of equipment is determined randomly.
Players have to figure out what equipment is.
Mutations are applied randomly.
The game has whole lot dice rolling that is best suited for computer assistance.
There is no computer assistance.

// how are personas made
=== Personas
The player may choose from three different races: anthropomorphs, aliens and robots. 
Most players will be limited to playing the familiar anthro race.
Beyone choosing race the personas are determined randomly.
Typical RPG attributes are generated on 3d6.
The attributes are used to determine the type and vocation of the persona.
Mutations can be randomly added and include defects and special powers.
Each persona is assigned some random equipment that may be junk or valuable.

=== Vocations
EXP has vocations that have set of skills and possibly even ideals.
The vocations the player can choose from are determined by their attributes.
Players are able to make up skills and challenge a performance table to determine success.
The chance of success increases as the persona's gather experience points.

=== Experience points
Players collect experience points for their personas.
These can be collected by participating in combat, roleplaying well, or being funny.


=== Technology
Any tech level device can appear simultaneously with any other tech level device.
The higher the tech level the smaller, lighter and more dependable the device.
Higher tech level items can be hard to recognize.
Very low tech level items can also be hard to recognize. 
It is possible for high and low tech level versions of the same item to co-exist.

=== Combat system
The combat system is based on to hit rolls and damage represented by hit points.
There are multiple combat systems to work with. 
Tactical is the most complex and is considered the game standard.
The tactical combat system uses a d1000 to hit roll
There also is a theatrical combat system.
The theatrical system is derived from the tactical system.
The theatrical system is faster.

=== EXP has no story
EXP is not a milieu. 
The game is a rule set and players are supposed to create their own worlds and stories.
This is intentional.

=== Her, him huh?
During one of EXP's versions it was noted that there was a paucity of women involved in RPGs.
Without any future knowledge of the coming pronoun revolution EXP moved from he to her.
The simple argument was that both her and she included he.
Inclusive and easier to write.

== Introductory Glossary

A brief introductory glossary of EXP terminology.
// trying to say more here explanations and translations.

Adjusted:: 
Adjusted MSTR, adjusted PSTR or any other ‘adjusted’ attributes means that the persona’s level is added to the attribute.

Alien:: 
Blah blah blah.

Anthro:: 
Shortened version of anthropomorph. 
A player could play an anthro. Anthros are phenotypically humanoid versions of creatures from the animal world. 
They are upright and bipedal and possess few of natural abilities of the creature they resemble.

Area of effect:: 
The number of hexes in which targets are subjected to damage or special effects. The value usually gives a radius for a spherical area of effect.

Amour Rating (AR):: The amour rating of the persona indicates how well she is protected from damage in combat. The higher the armour rating value the less likely she is to be damaged.

Attributes:: These are the imaginary divisions of a persona’s physical abilities. They are also called statistics.

Bonus non-proficient (BNP):: This is the to-hit roll bonus used when the persona is attacking with an unfamiliar weapon. This value is less than the regular to-hit roll bonus used. Each weapon type has its own bonus non-proficient.

Bonus proficient (BP):: This value is added to the player’s to-hit roll if her persona is using a weapon she is skilled in. Each weapon type has its own bonus proficient.

Bot:: Shortened version of the word robot. A player could play a bot. Robots have free will through malfunctions. They are inorganic, metallic and have computer brains.

Campaign:: This is the story generated by the referee and the players over many nights of role playing. A campaign can last for months or years of play and can involve many personas and different locations. A campaign is built from many scenarios.

Dice:: 
* 1d4 - A four sided die. Looks like a pyramid.
* 1d6 - A six sided die. The famous cube.
* 1d8 - An eight sided die. It does not look like an octupus.
* 1d10 - A ten sided die. This die is used to create 1d100 and 1d1000
* 1d12 - A twelve sided die. 
* 1d20 - A twenty sided die. The largest of platonic solids.
* 1d100 - Two (tens and digits) 1d10 are rolled to create a 1d100.
* 1d1000 - Three (hundreds, tens and digits) are rolled to creatre a 1d1000.
* Kilodie - Another name for a 1d1000

Damage:: Whenever a hit is scored in combat, the persona loses hit points. The amount of hit points lost is the damage. The more lethal an attack, the more damage it inflicts.

Damage Adjustor (DA):: This value is added to the damage roll for certain weapon types. The stronger the persona is, the more damage she will inflict.

Die roll:: A die roll indicates that a random number must be generated. Because the numbers are generated by dice, it is called a die roll.

Exatmo:: Anything that takes place in the vacuum of outer space. Short for exterior to atmosphere.

Experience (Exps):: Experience is a quantifiable value of the persona’s increase in knowledge from one scenario to the next. The persona earns experience points for being played and the point total represents the persona’s overall experience.

h/u (Hexes per Unit):: This is the scale movement rate for EXP. It is equivalent to m/s.

Hex:: A hex, short for hexagon, is a six sided perfect polygon. The hex is also the game scale for measurement. A hex equals 2 metres. Movement of figures is usually carried out on hex paper: a page of interconnected hexes.

HIG:: High gravity.

Hit Points (HPS):: The persona’s hit points indicate how much damage she can take. A persona with many hit points can sustain more damage than a persona with few hit points,. A persona loses hit points when she is hurt. If a persona loses too many hit points, she dies.

Hit:: A hit is a combat term that indicates a target has been damaged. When a hit is scored, the target usually loses hit points.

Hite:: An environmentally correct spelling of the word height. Their meanings are interchangeable.

Inatmo:: Anything that takes place in normal atmosphere. Short for in atmosphere.

Initiative:: Initiative is a way of determining the order of play between the players. Initiative can include the speed of the personas involved.

Intensity:: Intensity represents how dangerous a poison or psionic attack is. The higher the intensity, the more dangerous the attack.

Kilodie:: A Kilodie indicates that a random number between 1 and 1000 must be generated. The kilodie is composed of three ten sided dice where one die is the hundreds place, another is the tens place and another is the units place. A roll of 0, 0, 0, would indicate 1000. Often abbreviated d1000.

Level:: The level of a persona represents how skilled they are in their respective class. Experience point totals will indicate a persona’s level which will allow her to succeed at more difficult class skills.

Maximum Roll (MR):: This is the highest possible to-hit roll that the player can roll. This only applies to her to-hit roll. If she rolls higher than this value, she may only announce her maximum roll. Each weapon type has a different maximum roll.

Miss:: The miss is a combat term to indicate that a to-hit roll did not score any damage. A miss may contact a target but it cannot cause loss of hit points.

Movement:: Movement is the changing of position of personas during combat. Each persona has a movement rate which indicates how may hexes the persona can move each unit. This is the speed of the persona.

Movement Rate:: How many hexes per unit that the persona can move per unit of combat.

Mutation:: Mutations are changes in the genetic make-up of a persona which yield imaginary abilities built into the body (physical mutation) or controlled by the mind (mental mutation).

Persona:: The persona is the embodiment of all playing features. attributes, race and class. The players (you) manipulate personas like playing pieces to engage in scenarios. Anything that acts in the game is a persona. Personas are also run by referees; however, the player persona is the most detailed and important. Personas can also be called ‘player characters’.

Player:: You, the reader. The real world persona that controls the fantasy world character called a persona.

Race:: The race is the biological representation of the persona. The race is usually a humanoid one; however, bots and aliens can be personas and are categorized as special races.

Ref/Referee:: The player that is responsible for preparing the game for a group of players. The referee is responsible for running all those personas that are not run by players.

Referee Persona(RP):: A persona that is generated and run by the referee. It includes aliens, anthropomorphs and robots.

Ref's Own Table:: This comment is found when a player rolls the maximum on a table. It indicates that pure imagination or campaign discretion will prevail. Some tables will say Other, Ref's Imagination. Regardless it indicates that something NOT on that table should be tried.

Save versus:: Save vs. indicates that a save must be made versus either poison or psionic attacks.

Saves:: When the persona’s mind or body must defend against an attack, she will get a chance to save from the attack. A save is made by having the player roll a twenty sided die. The higher the roll, the more likely the persona is going to save. If the persona doesn’t save, she will be damaged, or affected, by the attack.

Scenarios:: These are smaller stories or challenges that players must face with their personas. An evening of role playing may involve several scenarios. A collection of scenarios may build to create an entire world and story arc called a campaign.

To-Hit roll:: A to-hit roll is a combat term indicating that an attacker is trying to damage her opponent. The higher the to-hit roll, the better because the attacker must generate a number greater than her opponent’s amour rating in order to hit.

Toys/TOYS:: Toys are special high tech equipment created on the Technological Object Yield System in the technology book; hence the abbreviation TOYS.

Type A:: This is a classification of weapons. Type A weapons are non-powered thrusting and striking weapons. Examples are swords, clubs, daggers and axes.

Type B:: This is a classification of weapons. Type B weapons are non-powered missile weapons. These weapons have a ranged attack but the attacking forces are generated by the persona. Some examples are bows, rocks, darts and bolos.

Type C:: This is a classification of weapons. Type C weapons are powered weapons of any sort. Powered weapons require no extensive physical effort by the persona to cause damage. Examples are lasers, rifles, crossbows or aerosols. Weapons listed as type D, E and so o are type C weapons which attack more than once a unit.

Unit:: The unit is the smallest component of combat time. All actions made by the persona during combat are broken down into two second intervals. A unit may take ten minutes or an hour to play.

Vocation:: This is a collection of innate abilities that could result from personal experience or training. Also called a class.

Wate:: An environmentally correct spelling of the word weight. In EXP, wate also includes an indication of how difficult something is to move. An object with a heavier wate would be more difficult to move in ZOG than a lesser wate object.

Weapon type:: All weapons are classed into different types depending on their combat properties. See also type A, type B and type C weapons.

ZOG:: Zero gravity.
