= Playing EXP

The first introduction to EXP was very long.
There were very few role-playing games.
There was no internet.
There were no cell phones.
There were no laptops.
Very few people knew what an "RPG" was, and those that did fear them.
Much of the first introduction explained how EXP fits into society.
Today there are thousands of role-playing games.
They can be played on tabletops.
They can be played on computer screens.
They can be played on phones.
They can be played in virtual reality.
Today "RPG" means role-playing game and not a rocket-propelled grenade.

== What does EXP mean?
The initial working title of the game was EXP1000.
EXP stood for EXPerimental, EXPerience points and EXPeditions.
EXPerience points were awarded for story and role-playing. 
It was unique at the time to award experience for anything other than combat success.
EXPeditions were formed instead of parties.
1000 represented using a 1000 sided die in combat.
EXP1000 was shortened to EXP.
Then EXP was lengthened to EXP  The game of technological chaos. 
This headline was to reflect the randomness of the TOY system.

== Why do such a thing?
EXP was done because it was not there.
There was only a game called Dungeons and Dragons. 
The tiny booklets were incomplete.
We were avid fans of science fiction.
Science fiction was limited to books, broadcast television and theatres.
The company called TSR released two games by the same author (James Ward).
These were Metamorphosis Alpha and Gamma World.
We loved the concepts but not the rules.

EXP1000 was entirely derivative from those two games.
As players, we used miniatures on hex paper to sort out combat.
Our combat was highly influenced by the meticulous war games of the day.
Combat resolution was tactical, detailed, and obsessive.
A twenty-sided die was not refined enough for us.
We simulated a one thousand sided die by rolling three ten sides.
This allowed us to give subtle bonuses or penalties.

== EXP as a reference book
In the 1980s role-playing games became and industry. 
Publishing houses needed to create content to sell and stay afloat.
This practice involved breaking games into parts and making supplements.
EXP chose to not follow this path at all.

. Create a generic sciency fiction role-playing game.
. Create one book that contained all content.
. Wait decades for this internet thing to catch on.

Initially EXP was a book. 
Books were very expensive to print.
Technology has advanced and we no longer have to print a 777 page book.
The intertubes and open source licensing has allowed EXP to be available to all.
This version is a rewrite and a move to technologies that will allow EXP to grow.

EXP is no longer a book but a living document that will:

. Be kept in a versioned repository
. Be free and open source
. Allow for multiple authors
. Be downloadable as a book or website

== Newbies
This used to be labelled Neophytes.
There were explanations of how to start a group etc.
Role-playing games are everywhere today.
To get started simply ask around.
You are guaranteed to find like minded folks.
They are unlikely to be playing EXP.
Better to start off with some friends rather than complete strangers.
Be safe and have fun.

== Concerned Parents
This section was originally written during a moral panic surrounding role-playing games (RPGs). 
Today parents are concerned if their kids are *not* playing RPGs.
Entire families play together. 
RPGs have been shown to improve numeracy, literacy, creativity and social skills.
A parent today would simply buy, download or create an RPG and start playing with their kids.

== RPG style of EXP
EXP, the game of technological chaos, is a sciency fiction role-playing game. 
While EXP has many detailed resolution systems, it is not particularly serious.
The base ruleset is written with the most detailed solutions in mind.
Most of the resolution systems allow for spectacular successes and failures.
The rule sets are flexible, generic, and interoperable.
There are always more straightforward, faster and possibly more fun ways to resolve the story.

A humanoid gorilla, a robot and a tentacled alien walk into a bar...
That bar is on a space ship that is being chased by a school bus full of mutants.
The gorilla fires her laser rifle at the school bus.
The tentacled alien spits poison at the driver.
The robot fires up her electronic countermeasures.
All the personas could use their mutations against each other.
The space vehicle fires it's naval cannon at the school bus.
The combat session is suddenly over.

All of these elements are integrated into one ruleset.

== EXP is silly
Role-playing is supposed to be fun.
EXP is not hard science. 
EXP is pseudo-science, sciency fiction or even silly science.
The families, rules and technology are ironic and border on the ridiculous.
The element of randomness is endemic in all of EXP's rules.
Personas and technology are generated randomly.
EXP has been waiting for decades for the computer support it needed.
This random factor ensures that EXP proudly crosses the border of ridiculousness.
EXP wallows in the pink and green light of the absurd.
There will be nuclear-powered toasters, combat robots with welcome mats, and fun-loving aliens. 

[quote]
____
*EXP is the game of technological chaos.*
____

// nature and depth of randomness
== EXP is Very Random
Personas are determined randomly.
The players adapt to their random personas.
Technological equipment is determined randomly.
The technological level of equipment is determined randomly.
Players have to figure out what equipment is.
Mutations are applied randomly.
The game has a whole lot of dice rolling that is best suited for computer assistance.
There is no computer assistance.

// how are personas made
== Personas
The player may choose from three different families: anthropomorphs, aliens and robots. 
Most players will be limited to playing the familiar anthro family.
Beyond choosing family the personas are determined randomly.
Typical RPG attributes are generated on 3d6.
The attributes are used to determine the type and vocation of the persona.
Mutations can be randomly added and include defects and special powers.
Each persona is assigned some random equipment that may be junk or valuable.

== Vocations
EXP has vocations that have a set of skills and possibly even ideals.
The vocations the player can choose from are determined by their attributes.
Players can make up skills and challenge a performance table to determine success.
The chance of success increases as the persona's gather experience points.

== Experience points
Players collect experience points for their personas.
These can be collected by participating in combat, roleplaying well, or being funny.

== Technology
Any tech level device can appear simultaneously with any other tech level device.
The higher the tech level, the smaller, lighter and more dependable the device.
Higher tech level items can be hard to recognize.
Very low tech level items can also be hard to recognize. 
It is possible for high and low tech level versions of the same item to co-exist.

== Combat system
The combat system is based on attack rolls and damage represented by hit points.
There are multiple combat systems to work with. 
Tactical is the most complex and is considered the game standard.
The tactical combat system uses a d1000 attack roll.
There also is a theatrical combat system.
The theatrical system is derived from the tactical system.
The theatrical system is faster.

== EXP has no story
EXP is not a milieu. 
The game is a rule set, and players are supposed to create their own worlds and stories.
This is intentional.

== Her, him, huh?
During one of EXP's versions, it was noted that there was a lack of women involved in RPGs.
Without any future knowledge of the coming pronoun revolution, EXP moved from he to her.
The simple argument was that both her and she included he.
Inclusive and more comfortable to write.

== Introductory Glossary
An introductory glossary of EXP terminology.
// trying to say more here explanations and translations.



Alien:: 
Aliens are one of the three families in EXP.
They are organic creatures of unusual shape and size.
They are alien to us but not to themselves.
These are the tentacled, furry, floating horse creatures.
Only experienced players should try playing alien personas.

Anthro:: 
Anthro is short for anthropomorph.
Anthros are one of the three families in EXP.
They are upright and bipedal, and function the same as homo sapiens.
They are phenotypically humanoid versions of creatures from the animal world.
Players are most familiar with playing anthro personas.

Area of effect:: 
Some attacks can affect multiple targets at once. 
This is an area of effect attack.
Grenades are the most famous area of effect weapons
The area of effect is measured in hexes and is described in each weapon or mutation.

Artifact::
A piece of technology that has value due to it's technological ability. 

Attack Type::
There are different ways to attack in combat. 
Attack types are differentiated by how they inflict damage. 
A punch is different from a bow which is different from a gun.

Attributes:: 
These are the imaginary divisions of a persona’s physical abilities.
The attributes in EXP are: awareness, charisma, constitution, dexterity, intelligence, physical strength, mental strength and hit points. 
They are also called statistics.

Awareness:: 
This an attribute of a persona.
It represents how alert the persona is. 
Awareness is often abbreviated AWE.

Bot:: 
Shortened version of the word robot. 
Robots are inorganic creatures of metal and computer intelligence. 

Campaign:: 
This is the story generated by the referee and the players.
A campaign is built from scenarios.
The scenarios can involve many personas and different locations. 
A campaign can last for months or years.

Charisma::
This is an attribute of a persona.
Charisma represents the charm, looks and leadership of the persona.
It is abbreviated CHA

Constitution::
This is an attribute of a persona.
Constitution represents the internal physique of the persona.
It is abbreviated CON.

Dexterity::
This is an attribute of a persona.
Dexterity represents the agility, balance and reflexes of the persona.
It is abbreviated DEX.

Dice:: 
* 1d4 - A four sided die. Looks like a pyramid.
* 1d6 - A six sided die. The famous cube.
* 1d8 - An eight sided die. It does not look like an octopus.
* 1d10 - A ten sided die. This die is used to create 1d100 and 1d1000
* 1d12 - A twelve sided die. 
* 1d20 - A twenty sided die. The largest of platonic solids.
* 1d100 - Two (tens and digits) 1d10 are rolled to create a 1d100.
* 1d1000 - Three (hundreds, tens and digits) are rolled to create a 1d1000.
* Kilodie - Another name for a 1d1000

Die roll:: 
A die roll indicates that a random number must be generated. 
The players grab the appropriate gravity driven random integer generator.
The die is rolled onto the table and the random integer is revealed.
Hence the term die roll.

Exatmo:: 
Short for exterior to atmosphere.
Anything that takes place in the vacuum of outer space. 

Experience Points:: 
Experience is a combination of learning, maturation and training.
Experience is measured in experience points. 
The more experience points a persona has the better they are at stuff. 
A persona with higher experience will be more successful at combat and skills. 
Experience points are earned through successful die rolls and role-playing. 
This is often abbreviated EXPS.

Hex:: 
A hex, short for hexagon. 
The hexagon is six sided figure.
Hexagons can interconnect to create a hex field. 
The hex field is used to portray tactical combat on the table top. 
A hex equals 2 metres. 

Hexes per Unit (h/u):: 
This is an arbitrary measure of movement EXP. 
It is equivalent to m/s.

HIG:: 
High gravity.

Hit Points (HPS):: 
The persona’s hit points indicate how much damage she can take. 
A persona with many hit points can sustain a lot of damage. 
A persona loses hit points when she is hurt. 
If a persona loses too many hit points they die.

Hite:: 
A unique measure to EXP that means height.
It can also be used to compare sizes regardless of family type.
Hite is recorded in centimeters (cm).

Inatmo:: 
Short for in atmosphere.
Anything that takes place in normal atmosphere. 

Intelligence::
This is an attribute of the persona.
Intelligence represents smarts, memory and deductive powers.
It is abbreviated INT.

Intensity:: 
Intensity represents how strong a poison or psionic attack is. 
The higher the intensity, the more dangerous the attack.

Kilodie:: 
A Kilodie generates a random number between 1 and 1000. 
A kilodie is also called a 1d1000.
A roll of 0, 0, 0, would indicate 1000.
The kilodie is composed of three ten sided dice:
* 1d10 is the 100s
* 1d10 is the 10s
* 1d10 is the 1s

include::ROOT:partial$CH27_Table_Tactical_Kilo.adoc[]

Level:: 
A short form of experience level.
A persona's level represents how good she is at combat and skills.
The experience level increases with the persona's experience points.

Mental Strength::
This is an attribute of the persona.
Mental strength represents will power, resilience and psionic connection.
It is abbreviated MSTR.

Miss:: 
A miss is any failed roll.
A failed attack roll is called a miss.
An unsuccessful poison defence roll is miss. 

Movement:: 
Movement is the changing of position of personas during combat. 
Each persona has a movement rate in hexes per unit.
This is the speed of the persona.

Mutation:: 
Mutations are imaginary biological adaptations.
They can give personas imaginary powers or defects.
For anthros mutations are unique changes to that persona.
For aliens mutations are unique biological skills of the species.
For robots mutations are wildly malfunctioning peripherals.

Persona:: 
The persona is the representation of the player in the imaginary world.
The persona can be controlled by a player or a referee.
Each persona is made up of attributes, description and story.

Persona Record::
This is the persona record sheet.
It is a piece of paper or computer thingy that stores the persona's info.
Also called a character sheet.

Phenotype::
Phenotype is the physical appearance of an organism. 
In EXP life forms are arranged phenotypically, or by appearance. 
Anthros are all humanoid, robots look mechanical and aliens look alien. 
This ignores biology for purpose of telling fun stories. 

Physical Strength::
This is an attribute of the persona.
Physical strength represents leverage, power and external physique.
It is abbreviated PSTR.

Post Factualization::
Reverse improvisation to explain something that happened after it has happened. 
Commonly needed by referees when story and pseudo science need to be synched.

Player:: 
You, the reader. 
The real world persona that controls the fantasy world character called a persona.

Family:: 
The three families in EXP are anthro, alien and robot.

Ref::
Short for referee. 
This is a player that is burdened with creating the milieu and puzzles of the campaign.
The role of referee is typically played by one player.
However the role of referee can be rotated or shared amongst multiple players.

Referee Persona(RP):: 
A persona that is generated and played by the referee. 
It includes aliens, anthropomorphs and robots. 
These are also called non-player characters.

Ref's Own Table:: 
This comment is found on tables used to generate EXP chaos.
It indicates that the referee and players should create something new. 

Robot:: 
Robots are inorganic creatures of metal and computer intelligence.
One of the three families in EXP.
Robots develop free will through malfunction. 
Robot personas should be limited to experienced players. 

Run::
Run refers to players getting together and playing EXP.
Run also refers to playing (or running) a persona.
A run is also called a scenario.

Scenarios:: 
These stories and challenges that take place in the game.
A scenario could be combat, puzzles, or some combination. 
Enough scenarios will build a story arch called a campaign.
These can also be called runs.

Toys/TOYS:: 
Toys are devices from that personas use to gain strength and power.
Toys are like magical items from fantasy games.
Toys are created on the Technological Object Yield System.

Unit:: 
The unit is the smallest component of combat time in EXP. 
All personas will move, attack of do part of something during each unit. 
A unit of combat may take ten minutes or an hour of real time to play.
The combat unit is 2 seconds.

Vocation:: 
This is a collection of innate abilities that the persona has.
A vocation could arise from innate skill, training or school. 
Also called a class.

Wate:: 
A unique spelling of the word weight in EXP., 
The wate includes inertia, mass, and general size. 

ZOG:: Zero gravity.

//baked in for robots
//high roll FTW
//tool vs tech vs comp vs AI
//vocation
//Roll vs Role
//Tale of two systems
//Skills (knowledge base) procedure (actual act)
//rules written from the point of challenging players (crazy limitations and examples) 


// needs a milieu section


// these rules are common language for a shared imagination experience.

// is armour a fixed AR or an AR adjustment 
