= Playing EXP

The first introduction to EXP was very long.
There were very few role playing games.
There was no internet.
There were no cell phones.
There were no laptops.
Very few people knew what an "RPG" was and those that did feared them.
Much of the first introduction explained how EXP fits into society.
Today there are thousands of role playing games.
They can be played on table tops.
They can be played on computer screens.
They can be played on phones.
They can be played in virtual reality.
Today "RPG" means role playing game, and not rocket propelled grenade.

== What does EXP mean?

The initial working title of the game was EXP1000.
EXP stood for EXPerimental, EXPerience points and EXPeditions.
EXPerience points were awarded for story and role playing. 
It was unique at the time to award experience for anything other than combat success.
EXPeditions were formed instead of parties.
1000 represented using a 1000 sided die in combat.
EXP1000 was shortened to EXP.
Then EXP was lengthened to EXP  The game of technological chaos. 
This headline was to reflect the randomness of the TOY system.

== Why do such a thing?

EXP was done because it was not there.
There was only a game called Dungeons and Dragons. 
The tiny booklets were incomplete.
We were avid fans of science fiction.
Science fiction was limited to books, broadcast television and theatres.
The company called TSR released two games by the same author (James Ward).
These were Metamorphosis Alpha and Gamma World.
We loved the concepts but not the rules.

EXP1000 was completely derivative from those two games.
As players we used miniatures on hex paper to sort out combat.
Our combat was highly influenced by the meticulous war games of the day.
Combat resolution was tactical, detailed, and obsessive.
A twenty sided die was not refined enough for us.
We simulated a one thousand sided die by rolling three ten sides.
This allowed us to give subtle bonuses or penalties.

Once role playing games became a fledgling industry EXP made a few choices:

. Create a universal role playing game
. Create a single book rule set
. Force players to gather and create their own games

== EXP as a reference book.

EXP was initially created as a reference so players could role play together.
Initially it was a book. 
Books were very expensive to print.
Technology has advanced and we no longer have to print a 777 page book.
The intertubes and open source licensing has allowed EXP to be available to all.
This version is a rewrite and a move to technologies that will allow EXP to grow.

EXP is not longer a book but a living document that will:

. Be kept in a versioned repository
. Be free and open source
. Allow for multiple authors
. Be downloadable as a book or website

== Newbies

This used to be labelled Neophytes.
There were explanations of how to start a group etc.
Role playing games are everywhere today.
To get started simply ask around.
You are guaranteed to find like minded folks.
They are unlikely to be playing EXP.
Better to start off with some friends rather than complete strangers.
Be safe and have fun.

== Concerned Parents

This section was originally written during a moral panic surrounding RPGs. 
Today parents are concerned if there kids are *not* playing RPGs.
Entire families play together. 
RPGs have been shown to improve numeracy, literacy, creativity and social skills.
A parent today would simply buy, download or make up and RPG and start playing with their kids.

== RPG style of EXP

// general introduction
EXP the game of technological chaos is a science fantasy role playing game. 
While EXP has many detailed resolution systems it is not particularly serious.
The base rule set is written with the most detailed solutions in mind.
Most of the resolution systems allow for spectacular successes and failures.
The rule sets are flexible, generic, and interoperable.
There are always simpler, faster and possibly more fun ways to resolve the story.

A humanoid gorilla, a robot and tentacled alien walk into a bar.
That bar is on a space ship that is being chased by a school bus of mutants.
The gorilla fires her laser rifle at the school bus.
The tentacled alien spits poison at the driver..
The robot fires up her electronic counter measures.
All the personas could use their mutations against each other.
The space vehicle fires it's naval cannon at the school bus.
The combat session is suddenly over.

All of these elements are integrated into one rule set.

== EXP is silly

Role-playing is supposed to be fun.
EXP is not hard science. 
EXP is pseudo-science, science fantasy or even silly science.
The races, rules and technology are tongue in cheek and border on the ridiculous.
The element of randomness is endemic in all of EXP's rules.
The personas and technology are generated randomly.
EXP has been waiting decades for the computer support it needed.
This random factor ensures that EXP proudly crosses the border of ridiculous'
EXP wallows in the pink and green light of the absurd.
There will nuclear powered toasters, combat robots with welcome mats, fun loving aliens. 

*EXP is the game of technological chaos.*

// nature and depth of randomness
== Very Random
Personas are determined randomly.
The players adapt to their random personas.
Technological equipment is determined randomly.
The technological level of equipment is determined randomly.
Players have to figure out what equipment is.
Mutations are applied randomly.
The game has whole lot dice rolling that is best suited for computer assistance.
There is no computer assistance.

// how are personas made
== Personas
The player may choose from three different races: anthropomorphs, aliens and robots. 
Most players will be limited to playing the familiar anthro race.
Beyond choosing race the personas are determined randomly.
Typical RPG attributes are generated on 3d6.
The attributes are used to determine the type and vocation of the persona.
Mutations can be randomly added and include defects and special powers.
Each persona is assigned some random equipment that may be junk or valuable.

== Vocations
EXP has vocations that have set of skills and possibly even ideals.
The vocations the player can choose from are determined by their attributes.
Players are able to make up skills and challenge a performance table to determine success.
The chance of success increases as the persona's gather experience points.

== Experience points
Players collect experience points for their personas.
These can be collected by participating in combat, roleplaying well, or being funny.


== Technology
Any tech level device can appear simultaneously with any other tech level device.
The higher the tech level the smaller, lighter and more dependable the device.
Higher tech level items can be hard to recognize.
Very low tech level items can also be hard to recognize. 
It is possible for high and low tech level versions of the same item to co-exist.

== Combat system
The combat system is based on to hit rolls and damage represented by hit points.
There are multiple combat systems to work with. 
Tactical is the most complex and is considered the game standard.
The tactical combat system uses a d1000 to hit roll
There also is a theatrical combat system.
The theatrical system is derived from the tactical system.
The theatrical system is faster.

== EXP has no story
EXP is not a milieu. 
The game is a rule set and players are supposed to create their own worlds and stories.
This is intentional.

== Her, him huh?
During one of EXP's versions it was noted that there was a paucity of women involved in RPGs.
Without any future knowledge of the coming pronoun revolution EXP moved from he to her.
The simple argument was that both her and she included he.
Inclusive and easier to write.

== Introductory Glossary

A brief introductory glossary of EXP terminology.
// trying to say more here explanations and translations.

Adjusted:: 
Adjusted MSTR, adjusted PSTR or any other ‘adjusted’ attributes means that the persona’s level is added to the attribute.

Alien:: 
Aliens are organic creatures of unusual shape and size.
One of the three races in EXP.
An experienced player could play an alien.
They are alien to us but not to themselves.
These are the tentacled, furry, floating horse creatures.

Anthro:: 
Shortened version of anthropomorph.
One of the three races in EXP.
Most common persona played in EXP.
Similar to us homo sapiens. 
They are upright and bipedal. 
They possess few of natural abilities of the creature they resemble.
They are phenotypically humanoid versions of creatures from the animal world. 

Area of effect:: 
The number of hexes in which targets are subjected to damage or special effects. 
The value usually gives a radius for a spherical area of effect.

Amour Rating (AR):: 
The amour rating of the persona indicates how well she is protected from damage in combat. The higher the armour rating value the less likely she is to be damaged.

Attributes:: 
These are the imaginary divisions of a persona’s physical abilities.
They are also called statistics.

Bonus non-proficient (BNP):: 
The to-hit roll bonus used when the persona is using an unfamiliar weapon. 
This value is less than the regular to-hit roll bonus.

Bonus proficient (BP):: 
The to-hit roll bonus used for skilled weapons.
Weapon skills are limited to combat vocations.

Bot:: 
Shortened version of the word robot. 
Robots are inorganic creatures of metal and computer intelligence.
One of the three races in EXP.
An experienced player could have a robot persona. 
Robots develop free will through malfunction. 

Campaign:: 
This is the story generated by the referee and the players.
A campaign is built from scenarios.
The scenarios can involve many personas and different locations. 
A campaign can last for months or years.

Dice:: 
* 1d4 - A four sided die. Looks like a pyramid.
* 1d6 - A six sided die. The famous cube.
* 1d8 - An eight sided die. It does not look like an octopus.
* 1d10 - A ten sided die. This die is used to create 1d100 and 1d1000
* 1d12 - A twelve sided die. 
* 1d20 - A twenty sided die. The largest of platonic solids.
* 1d100 - Two (tens and digits) 1d10 are rolled to create a 1d100.
* 1d1000 - Three (hundreds, tens and digits) are rolled to create a 1d1000.
* Kilodie - Another name for a 1d1000

Damage:: 
Whenever a hit is scored in combat, the persona loses hit points. 
The amount of hit points lost is the damage. 
The more lethal an attack, the more damage it inflicts.

Damage Adjustor (DA):: 
This value is added to the damage roll for certain weapon types. 
The stronger the persona is, the more damage she will inflict.

Die roll:: 
A die roll indicates that a random number must be generated. 
Because the numbers are generated by dice, it is called a die roll.

Exatmo:: 
Short for exterior to atmosphere.
Anything that takes place in the vacuum of outer space. 

Experience (EXPS):: 
Experience is a combination of learning, maturation and training.
Experience is measured in experience points. 
The more experience points a persona has the better they are at stuff. 
A persona with higher experience will be more successful at combat and skills. 
Experience points are earned through successful die rolls and role playing. 

Hexes per Unit (h/u):: 
This is an arbitrary measure of movement EXP. 
It is equivalent to m/s.

Hex:: 
A hex, short for hexagon. 
The hexagon is six sided figure.
Hexagons can interconnect to create a hex field. 
The hex field is used to portray tactical combat on the table top. 
A hex equals 2 metres. 

HIG:: 
High gravity.

Hit Points (HPS):: 
The persona’s hit points indicate how much damage she can take. 
A persona with many hit points can sustain a lot of damage. 
A persona loses hit points when she is hurt. 
If a persona loses too many hit points they die.

Hit:: 
A hit is a combat term that indicates a target has been damaged. 
When a hit is scored, the target usually loses hit points.

Hite:: 
A unique measure to EXP that means height.
It can also be used to compare sizes regardless of race type.
Hite is recorded in centimeters (cm).

Inatmo:: 
Short for in atmosphere.
Anything that takes place in normal atmosphere. 

Initiative:: 
Initiative is a way of determining the order of play between the personas. 
Initiative  includes  speed, skill and luck of the persona.

Intensity:: 
Intensity represents how dangerous a poison or psionic attack is. 
The higher the intensity, the more dangerous the attack.

Kilodie:: 
A Kilodie generates a random number between 1 and 1000. 
A kilodie is also called a 1d1000
A roll of 0, 0, 0, would indicate 1000.
The kilodie is composed of three ten sided dice:
* 1d10 is the 100s
* 1d10 is the 10s
* 1d10 is the 1s

Level:: 
A short form of experience level.
A level represents how good a persona is at combat and skills.
The experience level increases with the persona's experience points.

Maximum Roll (MR):: 
This is the highest possible to-hit roll that the player can roll. 
The MR is determined by attributes, experience level and weapon type.

Miss:: 
A miss is any failed roll.
In combat a miss is a failed attempt to damage the target.
In a saving through a miss represents being afflicted by the attack.

Movement:: 
Movement is the changing of position of personas during combat. 
Each persona has a movement rate in hexes per unit.
This is the speed of the persona.


Mutation:: 
Mutations are imaginary biological adaptations.
They can give personas imaginary powers or defects.
For anthros mutations are unique changes to that persona.
For aliens mutations are unique biological skills of the species.
For robots mutations are wildly malfunctioning peripherals.

Persona:: 
The persona is the representation of the player in the imaginary world.
The persona can be controlled by a player or a referee.
Each persona is made up of attributes, description and story.

Persona Record::
This is the persona record sheet.
It is a piece of paper or computer thingy that stores the persona's info.
Also called a character sheet.


Player:: 
You, the reader. 
The real world persona that controls the fantasy world character called a persona.

Race:: 
The three races in EXP are anthro, alien and robot.
The anthro type pure strain human has different anthro types, not races.


Ref::
Short for referee. 
This is a player that is burdened with creating the milieu and puzzles of the campaign.
The role of referee is typically one player.
However the role of referee can be rotated or shared amongst multiple players.

Referee Persona(RP):: 
A persona that is generated and played by the referee. 
It includes aliens, anthropomorphs and robots. 
These are also called non-player characters.

Ref's Own Table:: 
This comment is found on tables used to generate EXP chaos.
It indicates that the referee and players should create something new. 


Run::
Run refers to players getting together and playing EXP.
Run also refers to playing (or running) a persona.
A run is also called a scenario.

Saves:: 
A save is a special kind of roll that refers to non-combat challenges.
Saves are using rolled against a unique attack.
Save vs poison and save vs mental attack are the most famous.
If the player misses the saving throw their persona is subjected to the attack.

Scenarios:: 
These stories and challenges that take place in the game.
A scenario could be combat, puzzles, or some combination. 
Enough scenarios will build a story arch called a campaign.
These can also be called runs.

To-Hit roll:: 
A to-hit roll is a combat term.
It indicates that an attacker is trying to damage her opponent. 
The higher the to-hit roll the more likely to damage the target.
A to hit roll that is higher than the target's armour rating is called a hit.
A to hit roll that is less than the target's armour rating is called a miss.

Toys/TOYS:: 
Toys are devices from that personas use to gain strength and power.
Toys are like magical items from fantasy games.
Toys are created on the Technological Object Yield System.

Type A:: 
This is a classification of weapons. 
Type A weapons are non-powered thrusting and striking weapons. 
Examples are swords, clubs, daggers and axes.

Type B:: 
This is a classification of weapons. 
Type B weapons are non-powered missile weapons. 
These weapons have a ranged attack but persona powered. 
Some examples are bows, rocks, darts and bolos.

Type C:: 
This is a classification of weapons. 
Type C weapons are powered weapons of any sort. 
Powered weapons require no physical effort by the persona to cause damage. 
Examples are lasers, rifles, crossbows or aerosols. 
Weapons listed as type D, E and so o high rate of fire type C weapons. 

Unit:: 
The unit is the smallest component of combat time in EXP. 
All personas will move, attack of do part of something during each unit. 
A unit of combat may take ten minutes or an hour of real time to play.
The combat unit is 2 seconds.

Vocation:: 
This is a collection of innate abilities that the persona has.
A vocation could arise from innate skill, training or school. 
Also called a class.

Wate:: 
A unique spelling of the word weight in EXP., 
The wate includes inertia, mass, and general size. 

ZOG:: Zero gravity.
