= 2. Playing Personas
:sectnums:
:chapter-number:
:sectlinks:



A persona is a character of fictional representation.
In role-playing games the persona is the player’s tool.
The persona allows the player to partake in the game.
Every player has a persona.
Usually each player only has one persona.
Personas are extensions of the players into the fantasy world of EXP.

The referee is also a player.
She is a player who takes on some additional roles.
The referee sets up the puzzles for the players to solve.
She interacts with the players through multiple personas.
These referee personas may be complex and important to the game.

In computer games the persona would be called the avatar.
The greatest simulator is still the human imagination.
Personas allow us interact in the the science fantasy world of EXP.
The personas create a common ground for a shared experience.

== Parts of a Persona
The persona has three essential components. 

* the player
* the description
* the persona record 

=== The Player
The most important part of the persona is the player.
A persona will only be as interesting, fun and descriptive as her player makes it.
The player’s input into the persona is everything.
A persona is nothing but numbers on a page until the player gives it that spark of life.
EXP is focused on people playing live together in the same room. 
The entire point of the game is to people playing and working together.

=== The Description
The persona attributes are randomly generated in EXP.
Numbers are assigned to the persona's intelligence, dexterity and size.
These boring numbers are the data that informs the persona's history and personality.
Persona descriptions need not be detailed.
Let our imaginations fill in the gaps of appearance.
Let the mutual stories created through these personas fill in the gaps of history.

.Some example descriptions
A simple God-fearing tax collector from the orbiting suburban satellite station::
This introduction implies certain ideals. 
It is unlikely this persona would attempt to embezzle the emperor.
Probably has a high intelligence, normal physical strength and low will power.

A happy-go-lucky model QT-1 protocol unit from your local rec centre::
This introduction imparts the impression of a sycophantic cyborg.
This Pollyanna may offer a cherry soda when faced with imminent drive failure.

Ssssssssthp, me Slythris, me chew hoole innards, me catch in tree place::
This introduction is for a reptilian alien.
The hissing words may imply its appearance is sleek, sharp toothed and camouflaged.
One would not expect tool using skills.

== The Persona record
The last “essential of a persona” is the persona record.
The persona record keeps track of attributes, vocation, hit points, and equipment.
The persona record also represents the persona's story. 
Knowing the persona record sheet is important for playing the persona.
Reasonable record keeping and understanding one's persona increases everyone's fun

== Types of Personas
A persona can be anything imaginable.
The player must choose a persona race.
The race is either anthro, robotic or alien.
The anthropomorphic race is the easiest to play.
The persona's attributes determine the anthro, and robot type of the persona.
Robots and aliens should be reserved for experienced players.
The referee may only allow certain races because of story or milieu.

== Attributes
In EXP the player has no say is her persona's attributes.
The dice decide how strong, intelligent or charismatic the persona is.
The attributes are plain English descriptions of what they represent.
The collection of boring old numbers influence the actions of the persona.

A physically strong persona could not lift heavy things.
A persona with low intelligence would not be able to do complex calculations.
The player needs to respect these boundaries in their persona.
The attributes are what makes each persona's different.

== Mutations
Mutations are imaginary biological adaptations.
They can give personas imaginary powers or defects.
For anthros mutations are unique changes to that persona.
For aliens mutations are unique biological skills of the species.
For robots mutations are wildly malfunctioning peripherals.

Mutations can change everything. 
A mutation will influence the persona's name, story, and vocation.
Mutations can make a persona sickly or powerful. 

== Vocation
Skill sets are clumped into vocations in EXP.
They were previously called classes.
The vocation represents more of an inherent aptitude than training.
Schools, training, apprenticing is also possible.
How the skill set comes about is determined by the milieu of the referee.


The choice of vocation is determined by the persona's attributes.
Smart personas will pursue science vocations. 
Hardy personas will pursue combat vocations. 
It is possible to get no choice if the persona's attributes are low enough.

== Equipment
All manner of equipment is available in EXP.
This includes mundane items like torches and luggage.
Personas can also get items like fusion rifles and spaceships.
The random allocation of TOYS is unfair.
Most high tech toys will not be understood by the persona.
The referee can change knowledge and culture around toys to fit her milieu.

== Persona Record Sheet
The most important part of the persona is the player.
The player will infuse the persona with life and help create the story.
What the persona can accomplish will be limited by attributes, mutations and vocation.
This is not to limit the player's imagination in any way.
However, persona's attributes will determine what the persona can do.
If a player wants her persona to kick open a locked door, this will depend on PSTR.
An exuberant description will not trump the persona's physical strength.

If the player cannot find the  physical strength of her persona time is wasted.
Having a legible persona record sheet represents respecting fellow players.
No on is expected to memorize their persona record sheet.
A legible and organized persona record sheet is expected.

== Expeditions
The nature of role-playing games is very social.
RPGs  are for people get together to for mutual creative experience.
Each personas is a solitary unit.
A single persona is attached to a single player.
Groups of players get together and play groups of personas.
By design RPGs are social games. 
This group of personas is called an expedition.
It is called a party in other RPGs.

The expedition works together to solve puzzles and win combat.
No one persona can survive without being in an expedition.
An expedition has the combined tools to solve the ref's challenges.
The players of the expedition are expected to work together.


== Conclusion
EXP The Game of Technological Chaos is a paper and dice science fantasy role playing game. 
It is *not* a POV shooter video game, movie, or app.
It is *not* a persona record sheet.
It is *not* a collection of die rolls.
It is a game with real people creatively sharing and having fun. 
Enjoy.
