== Playing Personas
:toc:

According to most dictionaries, a persona is a character of fictional representation.
In role-playing games, the persona is merely a player’s tool; something which she manipulates to partake in the game.
Each player in the game has a persona and the personas are played together as a group which attempts to solve the puzzles put forth by the referee.

The referee is actually just another player.
She sets up the puzzles for the other players to solve and enters into the game with special personas called referee personas.
Such personas may help or hinder the other players, depending on how the referee plays them.

Personas are extensions of the players into the fantasy world of EXP.
It is impossible for us to clamour aboard spaceships, fire laser pistols or experience zero gravity in our own home but, through our imaginations, we an experience anything.

Imaginations tend to wander frantically and a group of players all visualizing situations differently would soon result in chaos.
Fortunately, the persona helps prevent this.

The persona acts as a common thread throughout the changing scenes put forth by the referee.
No matter what puzzles the players have to solve, they will always have to work with the same persona.
Whether the persona is a human soldier, a maintenance robot or an eight-legged tiger, it remains an unchanging anchor regardless of how bizarre the surroundings may get.

=== Essentials of a Persona

The most important part of the persona is the player.
A persona will only be as interesting, fun and descriptive as her player makes it.
The player’s input into the persona is everything.
A persona is nothing but numbers on a page until the player gives it that spark of life.

Even though the player is the single most important part of a role-playing character, there are other moderating factors which are essential: these are the attributes and history of the persona.

The attributes are the physical parameters of the persona: hite, wate, intelligence, race, age, health, speed, etc.
These values in themselves are quite boring but they are the groundwork by which the player gives her persona history and personality.

The history and personality of the persona are determined by the player but must fall within the guidelines of the referee’s milieu. A persona’s history will help decide how the persona reacts to various situations, how the persona dresses, how the persona talks and what the persona believes in.

Three very brief persona introductions will show how easily a persona personality can be reflected: “I’m just a simple God-fearing tax collector from the orbiting suburban satellite station..
This introduction implies certain ideals and it is unlikely this persona would attempt to embezzle the emperor.
 “Hi.
I’m a happy-go-lucky model QT-1 protocol unit from your local rec centre.
This introduction imparts the feeling of a sycophantic cyborg that will offer a game of electronic ping-pong or a cherry soda even in the presence of an imminent fusion drive explosion.
“Ssssssssthp, me Slythris, me chew hoole innards, me catch in tree place..
This last introduction alludes to a persona of reptilian stupidity.
The hissing words may imply its appearance is sleek, sharp toothed and camouflaged.

The last “essential of a persona” is that the player be familiar with the persona she’s created.
Other player characters, especially referee player characters, will react specifically to the persona that the player created.
For example, the first persona described (the tax collector) might not be welcomed by a gaggle of Imperial tax evaders.
What the player should know about her character is covered ad nauseam in the remainder of this chapter.

=== Types of Personas

A persona can be anything imaginable.
Once a player decides to play EXP, she must choose a persona type that’s humanoid, robotic or alien.
The anthropomorphic races are chosen most often because they are the easiest to play.
These are detailed in chapter 4, Anthropomorphs.
If a player chooses either robotic or alien races, they can be almost certain that their character will not have a humanoid form.
Not having a humanoid form makes a persona difficult to play so aliens and robots are not recommended for beginning players.



The decision of choosing persona type is left up to the player.
However, the ref may only allow certain types because of campaign restrictions.
This chapter gives an introduction on how to create humanoid personas.
Both robots and aliens are generated with step by step procedures (which are detailed in their respective chapters 5 and 6.  
Anthropomorph personas may require more time to create but they are much easier to play.

=== Attributes

The first step in creating a persona is generating the attributes.
The player has no say in how strong, intelligent or charismatic her persona is going to be.
Dice rolling is used to create these vital statistics of the persona.

The attributes are nothing but boring old numbers, yet they should definitely influence how the persona is run.
Physically powerful characters will use their brawn, intelligent personas will think and dextrous characters will pursue more nimble avenues of recourse.
Each attribute is covered in detail in chapter 3.
Attributes.

=== Race

After a player has generated her persona’s attributes, she is ready to determine more tangible aspects of her persona.
When the player chooses her persona’s race, she is choosing her persona’s appearance as well.
Unless the persona is an alien or a robot, she will be humanoid in shape (two arms and two legs).
There are many different humanoid types to choose from.
rodents, dogs, cats, fish and more.
Once this is done, the persona immediately jumps from an array of digits to a real being.
Instead of being a dull persona, she’s now a dumb rat, a charismatic horse or a weakling human.

The people types (as in any of the humanoid races) that the player can choose from are all upright, bipedal humanoids.
A rat would have two legs, two arms, a long snouted rat head, a thick rat tail and would have a covering of thick rat fur.
A horse would have two hoofed feet, arms with hands, a fly-lashing tail, a horse’s fine coat and a horse’s head.

Unfortunately, the players don’t get to choose whichever race type interests them.
What attributes the player has rolled will determine which of the races she can choose from.

=== Mutations

After choosing a race, the player must check her persona for mutations.
Mutations in EXP vary from weird to fantastic abilities to slightly irritating defects.
All personas much check for both Mental and Physical mutations.
This is done by referring to Chapter 7.
Mutations.
Players that want to run mutated personas can double their chance of mutation for their persona’s race.
Those players that wish to run genetically pure personas are still subject to the race’s base chance of mutation.
Mutations are usually rolled in secrecy with the referee and only the descriptive features of physical mutations are revealed to the other players.

Mutations add character to the persona by possibly changing their outlook on life.
E.g., the persona is now a dumb rat with retractable antennae or a charismatic horse that can read minds.

Mutations can definitely change the way a player intends to portray a persona.
In fact, mutations can change a persona so drastically that they must roll for mutations before they choose a profession.
For example, a player once rolled up an excellent spie (character class) and then rolled two noisy mechanical prostheses for legs.
Not all mutation changes are this dramatic but the mutations rolled can affect anything from a subtle name change the choice of a certain career.

=== Persona Class

Careers and professions in EXP are called classes.
The different character classes represent a persona’s aptitudes rather than a trained professional career.

Which of the classes a persona can pursue depends on her attributes.
physically tough personas can be military types; intelligent personas can be technical types; and personas with no distinctive attributes can be civilians.

A player will often be able to choose from several class types and the player will usually choose one which best suits her developing persona.

=== Equipment Etcetera

Choosing the character class is the last step in persona generation.
All other developments, such as personal equipment and history, depend on the campaign in which the player character is run.
The best kind of persona creation is that which takes place during the play of the game.
Personas may develop reputations within the milieu that they play.
Certain characters, or maybe even whole expeditions, may gain famous (infamous) notoriety in their city, planet, star system or universe.

=== Persona Record Sheet

The most important part of the persona is the player.
How the player impresses her persona’s personality on her fellow players and the referee is of upmost importance.
However, the player’s persona ultimately is a series of statistics that will determine what the persona can do.
For example, if a persona is trying to kick open a locked door, the ref will need to know her physical strength score regardless of how exuberant her description is.
If the player can’t remember her strength value or can’t find it on a sheet of paper, valuable playing time will be lost.
The players are not expected to memorize an entire persona (this is an impossible task for us mere mortals); however, a legible and organized persona record sheet is expected.
An example of such a sheet is given in this chapter.

When players record the attributes, abilities and equipment of their persona, they must remember that they and the referee will frequently refer to this sheet of paper.

=== Forming Expeditions

The nature of role-playing games is very social.
They are designed so that groups of people get together to solve problems and express ideas in fictional situations.
The personas described in this chapter are solitary units.
Groups of players will usually get together and play groups of personas.
The unwritten rule is that each player will run one persona.
If the persona is detailed enough, it should be all that one player can run effectively.

Since people will play EXP in groups, the referee will be expected to run (another word for play) groups of players.
A group of players is called an expedition and the expedition has to work together to solve the referee’s puzzles.
An expedition should have the abilities necessary to survive in a referee’s campaign.
No single persona may be able to survive but the entire expedition might be able to survive if they work together.
For instance, the expedition may need to ask the charismatic horse of the expedition to parley on their behalf while the avarian veterinarian tends to be the ursidae mercenary that just got beaten up.

=== Conclusion

The persona, ultimately, is only a sheet of paper, regardless of the player’s input.
EXP is designed as a recreation where people can get together for stimulating fun.
The game should be used as a periodic escape into fantasy, not a crutch for reality.
Record the important info about your persona while playing and forget such details in the interim.
Use the interpersonal skills learned while role-playing in your everyday life and be able to jump right back into the fun with a detailed readable character sheet.
