// fix make the whole game more generous and random
= Introduction

:art: exp_game_headliner.png
:width: 
:snark: 
:artist: Unknown 
:date: 1990
:license: Copyright 1990 Hugh MacLeod
:description: Head and shoulder painting of alien, human and robot.

include::ROOT:partial$articulate.adoc[]

== What is this? 
EXP: The Game of Technological Chaos is a paper and dice sciency fiction role-playing game. 
It is *not* a POV shooter video game, movie, or app. 
You xref:CH01_playing_exp.adoc[play EXP with dice and real people,window=_blank] all sitting in the same room. 
Enjoy.

== How is this?
How does one play games at a table during a pandemic? 
EXP is still *not* a POV shooter video game, movie, or app.
We still play with real people but not around the same table.
The list below is the combination of tools we use to play EXP online.
These tools offer the least number of barriers to having fun.
All are free or have free versions.

.*Playing EXP Online*
. https://shmeppy.com[Shared Mapping]
. https://rolz.org[Dice Rolling, text chat and persona records]
. https://zoom.us[Voice and video chat]

.*All In One Virtual Table Tops*
. https://foundryvtt.com[The best one]
. https://roll20.net[The expensive one]

//Sometimes I have to add a sentence because I forgot how to do everything.

== Why is this?
EXP: The Game of Technological Chaos evolved from the role-playing games of the late 1970s.
Dungeons and Dragons, https://en.wikipedia.org/wiki/Gamma_World[Gamma World], and https://en.wikipedia.org/wiki/Metamorphosis_Alpha[Metamorphosis Alpha]. EXP comes from a home brew based on Metamorphosis Alpha.
https://en.wikipedia.org/wiki/Jim_Ward_(game_designer)[James Ward] is our hero.

== Mission
Help create a less worse world through role playing and speculative fiction.

.*Achieve this mission by...*
* Developing a ruleset and toolset that is accessible, affordable, understandable, and universal.
* Developing a flexible ruleset that allows players to ajudicate decisions as a common experience.
* Developing a generic mythos that allows players to share experiences of their own creation.
* Developing a toolset that automates and eases player participation.
* Removing barriers of cost, culture, and accessibility to the role playing experience.

== Vision
A less worse world by mundane terrans sharing a sciency fiction role playing experience.

.*Measure this vision by...*
* A version controlled ruleset and toolset that is freely available online, offline, and in print.
* A community of kind supportive people that contribute to the ruleset and toolset.
* The translation of the ruleset, toolset and mythos into many languages.
* The acceptance that role playing games are synonymous with improvisation.
* The acceptance of TTRPG 2.0 being table top rpgs that integrate rulesets, toolsets and improv goals.

