= Introduction

:art: exp_game_headliner.png
:width: 
:snark: 
:artist: Unknown 
:date: 1990
:license: Copyright 1990 Hugh MacLeod
:description: Head and shoulder painting of alien, human and robot.

include::ROOT:partial$articulate.adoc[]

NOTE: This is a work in progress. 

== Progress
This is version 6.X of EXP The game of technological chaos. 
Estimated finish date is December 2021. 
A detailed progress description is available via https://docs.google.com/spreadsheets/d/1F9m7keUraYriyFHnk_unvE0gU1-dyO_rqECyTF76prI/edit?usp=sharing[gdocs].
A repository of progress is maintained on https://github.com/misterquetoo/EXP_Documents[github].

.*Chronologic Event List*
* This build 20-Jan-2021
* Last build 12-Jan-2021
* Milestone: all previous art added 03-Jan-2021
* Milestone: all sections rewritten 09-Dec-2020
* The pandemic pause ended 16-July-2020
* The pandemic pause began 13-Mar-2020
* There was a leap year update on 29-Feb-2020.
* There was a palindromic update on 20:20-20-02-2020.
* There was a palindromic update on 2020-0202.

== What is this? 

EXP: The Game of Technological Chaos is a paper and dice sciency fiction role-playing game. 
It is *not* a POV shooter video game, movie, or app. 
You xref:CH01_Playing_Exp.adoc[play EXP with dice and real people] all sitting in the same room. 
Enjoy.

== How is this?

How does one play games at a table during a pandemic? 
EXP is still *not* a POV shooter video game, movie, or app.
We still play with real people but not around the same table.
The list below is the combination of tools we use to play EXP online.
These tools offer the least number of barriers to having fun.
All are free or have free versions.

.*Playing EXP Online*
. https://shmeppy.com[Maps]
. https://rolz.org[Dice Rolling, chat and persona records]
. https://zoom.us[Voice and video chat]

.*All In One Virtual Table Tops*
. https://foundryvtt.com[The best one]
. https://roll20.net[The expensive one]

//Sometimes I have to add a sentence because I forgot how to do everything.

== Why is this?

EXP: The Game of Technological Chaos evolved from the role-playing games of the late 1970s.
Dungeons and Dragons, https://en.wikipedia.org/wiki/Gamma_World[Gamma World], and https://en.wikipedia.org/wiki/Metamorphosis_Alpha[Metamorphosis Alpha]. EXP comes from a home brew based on Metamorphosis Alpha.
https://en.wikipedia.org/wiki/Jim_Ward_(game_designer)[James Ward] is our hero.

//bs test