= Role Playing Rules

[quote]
____
*We like to talk.*
____

This rule system is for players that prefer to tell their story less with dice and more with their minds.
This does not mean there are no dice in the Role Playing Rules. 
Dice are still used to guide the story. 
The dice give descriptive directions rather than absolute results.
The players are still responsible for the story. 

There is only one dice mechanic used in Role Playing Rules.
All decisions can be made by rolled four six sided dice and consulting one table.
The only arithmetic required is addition and anti-addition.

NOTE: *Role Playing Rules arose from the Theatrical Combat System*

The Role Playing Rules are still dependent on the content of the Roll Playing Rules.
Terminology, explanations and concepts are an abstraction from the Roll Playing Rules.
Personas are still anthros, aliens and robots. 
The guns, armour, and space vehicles are the same.
The players can observe, or ignore, as much of the detail as they wish.
In this case 'they wish' means telling a fun story.

The Role Playing Rules convert almost all record keeping to descriptive words.
The persona record sheet is a collection of words.
Attack Rolls, Performance Rolls, Saving Rolls, are replaced with one mechanic.
The principles and details of these concepts are based on the Roll Playing System.
There are no EXPS to keep track of, no levels to keep track of, no HPS to keep track of.
Movement does not require miniatures or hex mats. 

Most playing groups will have a referee.
Role Playing Rules does not differentiate between a referee and a player.
Everyone at the table will be busy contributing to the story. 
Players are responsible for the outcomes of their dice rolls.
The outcomes are guided by all players so everyone is building the story.

There is a solitary dice mechanic in EXP called xref::CH26_Fourdeetwo.adoc[4D2]. 
The 4D2 mechanic gives descriptive results that guide the story.
There are no point deductions, or prescribed outcomes  with 4D2.
The dice decide the descriptors and the players decide the best outcome for the story.

// excellent communications required.
// LACE 
// the concept of decisions


