= Theatrical Tasks

[quote]
____
*Life is a series of mistakes until one of them kills you.*
____

.*Performing Tasks*
. <<_introduction,Introduction>>
. <<_4D2_mechanic_primer,4D2 Mechanic Primer>>
.. <<_number,Number>>
.. <<_outcome,Outcome>>
.. <<_descriptor,Descriptor>>
. <<_shifts,Shifts>>


== Introduction
Everything is a task in EXP.
The tasks in combat are precise, and their dire outcomes earn them their own section.
This section is about performing every other kind of maneuver.
In this context, a task is any persona action that has an unclear outcome.
For example, it is not immediately evident that the mechanic will adequately fix the malfunctioning control box.
The core of all roleplaying games is to fill this unknown with randomness.
Theatrical Tasks uses the 4D2 Mechanic to generate randomness in non-combat persona actions.

The Task System should be used when it makes sense.
Having players make 4D2 rolls for each step they take is cumbersome and not in the spirit of the Role Playing System.
Simple tasks, even combat ones, should simply succeed. 
The 4D2 roll should only come up when a decision helps the story.

The name of this section is rooted in legacy and nostalgia. 
Formerly vocation maneuvers were determined by elaborate Performance Tables.
The Theatrical Tasks replaces Performance Tables and improves storytelling.
The personas are performing maneuvers, not soliloquies.

:art: ethernet_repair_person.png
:width: 450px
:snark: Ethernet repair service.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Futuristic human woman with holographic keyboard and multiple tools works on internet node.

include::ROOT:partial$articulate.adoc[]

== 4D2 Mechanic Primer
4D2 is both a descriptor and a joke. 
The 4 indicates that the mechanic uses 4 dice.
The 4 also indicates that there are 4 steps in the process.
The D refers to dice, and it a play on "D" in the 4d6 convention.
The 2 reflects that the mechanic has two directions.
The joke is that 4D2 sounds like 42.
Fourty Two is the answer to the question.
The 4D2 Mechanic gives the answers to questions you don't understand.

The 4D2 Mechanic uses four six-sided dice to guide the story in the Role Playing System.
The 4D2 Mechanic is a bespoke decision tool for EXP's Role Playing System.
4D2 replaces Attack Rolls, Task Rolls, Attribute Rolls, Saving Rolls, Sphincter Rolls and more.

In Theatrical Tasks, the 4D2 Mechanism guides the story. 

.*Four steps of the 4D2 Mechanic*
. A player rolls dice to get a  *Number*
. That  *Number* yields an *Outcome*
. The   *Outcome* produces a *Descriptor*
.. The *Descriptor* comes from the players or a table.
. The *Story* is influenced by the *Descriptor*

WARNING: Do not proceed with this section until mastering an understanding of the xref:ii-role_playing_rules:CH26_Fourdeetwo.adoc[4D2 Mechanic,window=_blank].

=== Number
A player generates a number by rolling two pairs of competing six siders.
The player rolls 2d6, generating a number between 2 and 12.
The player rolls 2d6 again, generating another number between 2 and 12.
The player subtracts the second roll from the first roll.
The sum of these two numbers generates the *Number* of the 4D2 Mechanic.

=== 4D2 Number Generation
.Number = 2d6 - 2d6
****
The number is always between +10 to -10. + 
A positive number gives a positive outcome. +
A negative number gives a negative outcome. +
Zero gives a neutral outcome.
****

:art: 4d2_dice.png
:width: 250px
:snark: (6+1) - (4+2) = +1
:artist: HM
:date: 2020
:license: CC BY-SA 4.0
:description: Two green dice and two red dice. Total score plus one.

include::ROOT:partial$articulate.adoc[]

=== Outcome
The outcome translates the number into a colourful account of the die roll.
The Outcome from Number Table uses the number to determine the *Outcome* from the 4D2 roll. 
The outcome arises directly from the 4D2 roll and is untainted by shifts (aka bonuses).
Often the outcome is enough of a description for the players to decide how things turn out.

The outcome can have a direct effect on the persona.
A persona can earn a new skill for very successful outcomes.

include::ROOT:partial$CH26_Table_4D2_Outcomes.adoc[]

=== Learning Skills
If the player rolls an Immaculate or Wondrous success, her persona earns a skill in the maneuver she performs. 
This skill reward precedes the adding of any shifts.
A persona cannot earn skills based on shifted rolls. 
Only the unshifted outcome can earn a skill.

=== Skill Learning
.Outcome = Immaculate (+10) or Wondrous (+9) success
****
Persona earns +1 for the maneuver she is performing.
****

=== Descriptor
Often the Outcome gives enough info for the players to tell the story.
Describing an outcome is easy for Immaculate Successes and Cataclysmic Failures.
The other 19 possible outcomes are more subtle and harder to turn into a description.

There is a Descriptor Table for Tasks when the players can't manage a description or agree on a description. 

include::ROOT:partial$CH26_Table_4D2_Descriptors_Performance.adoc[]

If a player were to roll an Extraordinary Success (+5), her persona has made an engine repair that will last months. 
If a player were to roll a Major Failure (-3), her persona has not succeeded and must wait hours before trying again.

:art: sneaky_performance_roll.png
:width: 250px
:snark: Archeologist appropriating an idol.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Indiana Jones like fellow in fedora about to lift a statuette.

include::ROOT:partial$articulate.adoc[]

=== Descriptor Descriptions
Invention::
The persona has had an epiphany about the maneuver. 
If the persona is working on equipment, they may invent an entirely new and better device.
If the persona is working on an organic life form, they may add an attribute or a mutation.
The players should pick an invention that best supports the story of the campaign.
Fixing a tyre should not add artillery to a vehicle.
Surgery to remove a bullet should not result in a mental mutation.

Enhancement::
The player can choose some improvement that permanently makes the maneuver's target or the maneuver itself better.
The players should pick an enhancement that best supports the story of the campaign.

Shifts::
The player enjoys a temporary shift while performing this maneuver for a limited amount of time.
The shift is +1, is cumulative and lasts for the duration described.

Lasts::
'Lasts' indicates how long the maneuver holds together.
A Barely Successful (+1) tyre repair will only stay repaired for a few hours.
A Masterfully Successful (+6) tyre repair will stay repaired for months and give the persona a shift when fixing tyres for the next few hours. 

Waits::
In the case of failures, the persona must wait before they can try the maneuver again.
A Clear Failure (-2) tyre repair leaves the tyre deflated.
The persona must also wait a few minutes before repairing the tyre again.
The persona may be so flustered by this failure that they must wait months before trying again.

Complications::
Complications are unexpected negatives that arise from a failed maneuver.
A complication should mildly worsen the situation.
Fixing a tyre could accidentally damage the rim and ground the vehicle.
Surgery to remove a bullet may leave the bullet in and an instrument.
The players should pick a complication that best supports the story of the campaign.
Complications do not injure or damage the subject of the maneuver.
A persona can get out of a complication with further maneuvers.

Damage::
Done broke it.
The failure directly damages the patient, machine, or device.
Organic personas are subject to a negative folded roll, and a machine now needs spare parts for repair.

Destruction:: 
Done blew up.
The patient may die, the entire vehicle can catch fire, the grenade goes off, the gun explodes. 
Maneuvers resulting in destruction are bad for the persona and her expedition.

=== Cumulative Descriptors
A Wondrous Success (+9) results in an enhancement that lasts months and gives the persona a +1 shift for days.
A Complete Failure (-6) results in a complication and the persona avoiding the maneuver for weeks. 

:art: biologist_at_work.png
:width: 450px
:snark: Grey anatomy.
:artist: JEShields
:date: 2014
:license: Copyright JEShields Stock Art. jeshields.com
:description: Steam punk human woman biologist doing autopsy on alien beast.

include::ROOT:partial$articulate.adoc[]

== Shifts
Shifts are similar to bonuses or penalties.
A shift is anything that moves the Outcome of the 4D2 Mechanism.
A Shift of +2 would move a Solid Success (+2) to an Outstanding Success (+4).
Shifts are significant and are the only way personas can gain an advantage in the 4D2 system.

Shifts come from the persona's attributes, abilities and skills.
However, anything can become a shift if the players accept it.
In hand-to-hand combat, a player could use the PSTR as a shift.
When shooting a pistol, the player could use a pistol skill as a shift.
A glorious description of throwing a grenade can earn a shift.

=== Shift Maximums
The maximum number of shifts a player can add to her Outcome is three.
The maximum Outcome is +10, which is an Immaculate Success.
A roll of 11, 12 or even 13 becomes +10.

=== Shift Penalties
Shifts cannot be negative.
The lowest a player's shift can become is zero.
Penalties can only take away a player's shift.
If a persona wanted to use her DEX as a shift, but her hands were tied, she could not use her DEX shift. 
However, another persona in the same situation without a DEX attribute would not suffer a -1 shift.

=== Shifts and Skills
When the player rolls a high number, her persona can gain skills.
A high number is one pathway to earning new skills and strengthening the persona.
Players cannot use shifts to gain skills. 
Using shifts to score new skills can lead to rapidly overpowered personas. 
A +1 shift increases the chance of the persona gaining a new skill three times.

A shift only moves the outcome and not the descriptor.
For example, a player rolls Masterful Success (+6) when remodulating a tensor refactoring core.
Her shift is +3 (drive skill, DEX and a good description). 
Her Outcome is Masterful Success (+6), and her descriptor is Wondrous Success (+9).
The persona enhances the drives but does not get another drives skill.
 
=== Example Shifts
A persona is in a pistol shootout. 
She has pistol skill and DEX attribute.
She can Shift her 4D2 Outcome by +2.
A Shift of +2 would move a Solid Success (+2) to an Outstanding Success (+4).
If her opponent has Pistol 2, then the competing Shifts would cancel out.

A persona is repairing an antigrav modulator on a skimmer bike.
She has engine skill one and an INT attribute.
The player casts a great yarn about using a piece of wire to reverse the polarity.
She can shift her 4D2 Outcome by +3 (skill, attribute, good story).
The shift of +3 moves her Minor Failure (-1) to a Solid Success (+2).

A persona is play wrestling in the mud pit of a bar.
She has no wrestling skills.
She can use her PSTR and DEX attributes.
She can shift her 4D2 Outcome by +2 (two attributes).
The shift of +2 moves her Magnificent Success (+8) to an Immaculate Success (+10).
The persona earns the accolades of the bar crowd (Outcome = +10) but does not earn a wrestling skill.