= Anthro Creation
All anthros are upright, bipedal.
They have hands, heads and faces.
In the fake taxonomy of life in EXP Anthros are in the family Hominidae, and the genus homo.
Anthros are further differentiated by types.
Each anthro type is considered a species with names like homo avis, or homo felis.
A homo felis (feline) would be further differentiated as a cat, lion or cougar.
The final appearance of the anthro type is chosen by the player.

.*Anthro Creation*
. <<_anthro_attributes,Attributes>>
. <<_anthro_type,Type>>
. <<_anthro_mutations,Mutations>>
. <<_anthro_vocation,Vocations>>
. <<_anthro_skills,Skills>>
. <<_anthro_abilities,Abilities>>
. <<_anthro_artifacts,Artifacts>>
. <<_anthro_name,Name>>
. <<_anthro_appearance,Appearance>>
. <<_anthro_history,History>>

== Anthro Attributes
The standard attributes of EXP are present in all personas.
In the Role Playing System personas only record those attributes at which the persona excels.
A persona could have a blank attributes section and function fine.
Another persona may have the attribute intelligence. 
This indicates that the persona's INT is an attribute she excels at.
It is possible for a persona to excel at more than one attribute.
For example, INT and DEX.

There is no score assigned to an attribute. 
If the persona excels at an attribute they benefit when that attribute is being used.
For example, a persona physical strength would have better results than a persona with INT when lifting.
If two personas grappling both had physical strength then there would be no advantage given.
However if a persona with PSTR and DEX is grappling a persona with just PSTR they get a DEX advantage.

include::ROOT:partial$CH26_Table_Attribute.adoc[]

Size::
Size is an attribute assigned to every persona.
All anthros are size medium.
The size is recorded under the attributes section of the persona record.
For example, the persona record sheet could have Medium and INT recorded under 

Awareness::
Awareness indicates how aware a persona is of her surroundings. 
It indicates how well is the persona’s brain is connected to the outside world. 
The attribute is a collective measure of the persona’s sensors. 
AWE includes senses like hearing, vision, smell, touch and taste. 
Awareness does not include the sixth sense, or a sense of style. 
The abbreviation for awareness is AWE.

Charisma::
Charisma is charm, looks and sociability all combined into one value. 
A high charisma represents a high proficiency at getting along with other personas. 
This attribute is a universal so any persona with a high CHA would be socially adept. 
A persona’s charisma is very important for inter-persona interactions.
The abbreviation for charisma is CHA.

Constitution::
Constitution represents a persona’s internal physique.
CON is a combination of wellness, immunity, energy extraction, healing ability.
A high CON is better to repel disease, resist poisons, and repair damaged tissue.
The abbreviation for constitution is CON.

Dexterity::
Dexterity represents the connection between the brain and outside world.
Agility, balance, eye-hand, reflexes and running speed are components of dexterity.
A high DEX person could run faster, dance better and quicker reflexes.
Dexterity would help the persona catch a priceless vase or dive through a closing door.
The abbreviation for dexterity is DEX.

Intelligence::
Intelligence indicates the smarts of the persona.
Elements of INT are memory, deduction, creativity, adaptability and their synergism. 
The higher the intelligence of the persona the smarter she is.
The abbreviation for intelligence is INT.

Mental Strength::
Mental Strength exists as an attribute.
MSTR must be acquired through a story set out by the players.
If the referee would like a band of knites off on damn fool missions then every persona gets MSTR.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

The MSTR attribute can be earned by completing an MSTR testing story line laid out by the players.
Also MSTR can be assigned by suffering and surviving a mortal wound in combat.
The players will decide if the MSTR attribute has been earned by the persona.
The abbreviation for mental strength is MSTR.

Physical Strength::
Physical Strength represents force the persona can generate to get work done. 
PSTR is a combination of leverage, power and physique. 
Physical Strength determines how much the persona can lift or damage by brute force. 
PSTR helps kicking open doors, breaking bonds, or crushing beer bottles.
The abbreviation for physical strength is PSTR.

Hit Points::
There are no hit points Max or hit points Total.
Combat and damage is both absolute and descriptive. 
There is no quantitative measure of well being like 32 HPS Total out of 42 HPS Max.
Personas are damaged in combat by losing attributes, skills and abilities instead of HPS.
When the 4D2 Mechanic generates a Cataclysmic Failure the persona can lose an attribute, skill or ability.
Extreme failures on the 4D2 Mechanic can mortally wound or kill the persona as well.
The abbreviation for hit points is HPS.

Social Standing::
There is no Social Standing.
All elements of social interaction are expected to be role-played in this system.
The abbreviation for social standing is SS.

EXPS and Level::
There are no Experience Points or Experience levels. 
Personas are awarded additional attributes, skills and abilities instead of experience points or levels.
The 4D2 Mechanic can generate new attributes, skills or abilities.
This process replaces experience points and experience levels.
The abbreviation for experience points is EXPS.

== Anthro Type
There are twelve distinct anthro types to choose from.
If the player does not feel like choosing she may randomly select her persona type.

include::ROOT:partial$CH26_Table_Role_Anthro_Type.adoc[]

=== Anthro Type Abilities
If the player generates her anthro type randomly she can choose from the abilities listed.
If the player wishes to choose her anthro type for style and story the abilities are not an option.
This is an effort to promote diversity.

Aquarian::
Homo Pisces are anthropomorphized aquatic beings. 
The player may add the ability water breathing to her aquarian persona.

Avarian::
Homo Avis are anthropomorphized avarian beings.
Flying can only be acquired through mutation. 
The player may add the ability detect ambush her avarian persona.

:art: sandy_anxious_ostrich.png
:width: 190px
:snark: The sky is being gravitied!
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a humanoid ostrich very upset about something.

include::ROOT:partial$articulate.adoc[]

Canine::
Homo Canis are anthropomorphized dog beings.
The player may add the ability radiation sense to her canine persona.

Equine::
Homo Equus are anthropomorphized hoofed beings.
The player may add either the ability sprinting, or the ability jumping to her equine persona.

Feline::
Homo Felis are anthropomorphized cat beings.
The player may add either the ability ambush, or the ability of night vision to her feline persona.

Florian::
Homo Flora are anthropomorphized plant beings.
The player may add the ability photosynthesis to her florian persona.

Humanoid::
Homo Mutabilis can appear any humanoid form.
For example, simians, hobbits, suidae, dwarves, humans or orcs.
The player may add an ability from Physical Mutations or Mental Mutations.
The mutation will be randomly assigned. 
The player must remove CHA from her attribute list.

Insectoid::
Homo Insectum are anthropomorphized insect beings.
The player may add the ability MSTR resistance to her insectoid persona.
This is not the attribute MSTR, but a defence against MSTR attacks.

Pure Strain::
Pure Strains are Homo Sapiens (us mundane humans) sporting any imaginable skin colour.
The player may add the attribute CHA to her Pure Strain persona.
This persona cannot start with a mutation ability and cannot acquire mutation abilities.

Reptilian::
Homo Serpens are anthropomorphized reptile beings.
The player may add either the ability Torpor, or the ability Chameleon to her persona.

Rodentia::
Homo Rodens are anthropomorphized rodent beings.
The player may add either the ability Night Vision, or the ability Sprinting to her persona.

Ursidae::
Homo Ursus are anthropomorphized bear beings.
The player may add either the ability Frenzy or the ability Hibernation to her persona.

== Anthro Mutations
Anthro mutations are fantasy genetic aberrations the offer the persona Wondrous, mundane or treacherous abilities. 
Mutations are recorded in the abilities section on the persona record sheet.
Mutations are assigned at persona creation based on the persona's attributes and anthro type.

.*Mutate Now. Avoid the post bomb rush.*
* Homo Mutabilis are assigned one completely random mutation.
* CON attribute personas are assigned one non-defective Physical Mutation.
* INT attribute personas are assigned one non-defective Mental Mutation.

The player heads to the designated mutation section and generates a random mutation.
If the players are diligent a player may be allowed to choose a mutation.
Keep in mind that some mutations are incredibly powerful and they are not designed to be 'picked.'

IMPORTANT: *Welcome friend of EXP. Mutations are unfinished in V6.0 of EXP.*

xref:v-wetware:An_index_wetware.adoc[Mutations live here. Mutations are under mutation and evolution.]

== Anthro Vocation
A vocation is a calling or innate skill set possessed by the persona.
If the referee's milieu indicates a vocation could mean training at a school, institute or guild.
The player may choose from any of the listed vocations or choose one randomly.
Allowing the dice to choose the persona's vocation allows for attributes and abilities to be awarded.
For example, choosing vet does not allow the persona to add CHA or choose one ability.
A randomly chosen spie would get the DEX attribute and be able to choose one ability.

include::ROOT:partial$CH26_Table_Role_Vocations.adoc[]

=== Nothing Pathways
Nothing cannot be randomly chosen.
Nothings can be voluntary or forced.
A voluntary nothing is chosen by the player during persona creation.
A forced nothing is any persona that loses her vocation by losing her attributes.
Any persona with no attributes loses her vocation and becomes a nothing.
So mercenary with DEX and PSTR would become a nothing if she loses her DEX and PSTR attributes.
The mercenary would also lose her abilities like ambidextrous combat until any attribute is regained.

Voluntary (chosen by player) nothings get skills and wealth abilities.
Forced (losing attributes) nothings do not get to roll nothing skills or wealth abilities.

=== Vocation Attributes
If the player generates her vocation randomly she is awarded an attribute.
Each vocation is associated with an attribute.
So if the player rolls a mercenary she get's the attribute PSTR added to her attribute list. 
If the player wishes to choose her vocation type for style and story attributes are not granted.
This is an effort to promote diversity of vocations.

=== Vocation Abilities
If the player generates her vocation randomly she can choose one vocation ability.
Most vocations have abilities associated with them.
Abilities are different from skills.
These are different from skills because the abilities are baked into the persona.
No persona can learn the vet Quick Fix ability. 
If the player wishes to choose her vocation type for style and story abilities are not granted.
This is an effort to promote diversity of vocations.

Biologist::
The biologist is dedicated to studying the organic world.
This ranges from it's denizens to it's cultures.
The player may add AWE to her persona's attributes if her vocation is randomly chosen.
Biologists have no abilities, but they do have skills. 

Knite::
The knite is dedicated to the promoting order, or chaos, by connecting the Physical and Think Spaces. 
A player cannot choose or randomly generate the vocation knite.
Before a persona can become a knite she must first earn her MSTR attribute.
The Knite vocation can be earned by completing an Knite qualification story line laid out by the players.
The players will decide if the Knite vocation has been earned by the persona.
If a player's persona becomes a knite she can choose one ability from the extensive list.

Mechanic::
The mechanic is dedicated to studying the inorganic world.
This ranges from it's robots to it's scientific systems.
The player may add INT to her persona's attributes if her persona is randomly chosen.

Mechanics have abilities and skills.
Every mechanic gets one mechanic skill.
A mechanic can choose one ability if her vocation is randomly chosen.
xref:i-roll_playing_rules:CH08_Vocations_Mechanic.adoc#_mechanic_abilities[Mechanic abilities,window=_blank] include: mnemonic trapping, brainstorming and mental patenting.

Mercenary::
The mercenary is dedicated to promoting order, or change, via violence.
Mercenaries are not psychotic, violent or cruel.
They are skilled in the art of war and weapons.
The player may add PSTR to her persona's attributes if her persona was randomly chosen.

Every mercenary gets one mercenary skill.
A mercenary can choose one ability if her vocation is randomly chosen.
xref:i-roll_playing_rules:CH08_Vocations_Mercenary.adoc#_mercenary_abilities[Mercenary abilities,window=_blank] include: Bolster AR, Ambidextrous combat, Snap reload, Proficiency.

Nomad::
The nomad is dedicated to surviving and integrating into her surrounding world.
This includes all aspects of survival, travel and shelter in all terrains.
The player may add CON to her persona's attributes if her vocation is randomly generated.

Every nomad gets one nomad skill.
A nomad can choose one ability if her vocation is randomly chosen.
xref:i-roll_playing_rules:CH08_Vocations_Nomad.adoc#_nomadic_abilities[Nomad abilities,window=_blank] include: Find Water, Find Shelter, Find Food, Make Fire, Safe Passage, Cure Poison, Husbandry, Tracking plus more.

Nothing::
The nothing is dedicated to all things mundane.
This includes money, appearance and social standing.
Nothings have no combat skills and no useful maneuvers.
The skills and abilities listed here are for voluntary nothings.
This vocation is a choice made by the player at persona creation.
This section does not apply to forced nothings who have arrived at the vocation by tragedy and injury.

Every voluntary nothing gets at least one nothing skill.
Most enjoy and extra skill is the skill section below.
The equivalent of nothing ability is money.
The voluntary nothing gets one serving of xref:i-roll_playing_rules:CH08_Vocations_Nothing.adoc#_nothing_wealth[Nothing Treasure,window=_blank] as an ability.

Spie::
The spie is devoted to all things deceptive, sneaky and fabricated.
This includes disguises, sneaking and assassination.
The player may add DEX to her persona's attributes if this vocation is randomly chosen.

Every spie gets one spie skill.
A spie can choose one ability if her vocation is randomly chosen.
xref:i-roll_playing_rules:CH08_Vocations_Spie.adoc#_spie_abilities[Spie abilities,window=_blank] include: assassinate, disguise or martial arts.

Veterinarian::
The veterinarian is devoted to repairing and improving all organic beings.
This includes diagnosis, surgery and medications.
The player may add CHA to her persona's attributes if this vocation is randomly chosen. 

Every veterinarian gets one veterinarian skill.
A veterinarian can choose one ability if her vocation is randomly chosen.
xref:i-roll_playing_rules:CH08_Vocations_Veterinarian.adoc#_vet_abilities[Vet abilities,window=_blank] include: quick fix, subliminal suggestion, paralyzing pinch, and death pinch.

== Anthro Skills
Skills are learned aptitudes that are not baked into the persona like an ability.
A mutation, or anthro type ability, are not skills.
A persona could master the skill knife throwing but she could not master photosynthesis.
Skills can be lost due to cataclysmic failures. 

=== Mundane Skill
Every anthro persona gets one mundane skill rolled on the nothing skill table.
Nothings should end up with 2 nothing skills.
The table is included here for convenience. 

include::ROOT:partial$CH08_Table_Nothing_Skills.adoc[]

=== Other Skills
If the persona has a vocation the player gets one roll from their vocation table. 

.*Vocation Skills*
. xref:i-roll_playing_rules:CH08_Vocations_Biologist.adoc#_biologist_skills[Biologist Skill,window=_blank]
. xref:i-roll_playing_rules:CH08_Vocations_Knite.adoc#_vocation_abilities[Knite Abilities,window=_blank]
. xref:i-roll_playing_rules:CH08_Vocations_Mechanic.adoc#_mechanic_skills[Mechanic Skill,window=_blank]
. xref:i-roll_playing_rules:CH08_Vocations_Mercenary.adoc#_mercenary_skills[Mercenary Skill,window=_blank]
. xref:i-roll_playing_rules:CH08_Vocations_Nomad.adoc#_nomadic_biomes[Nomad Biomes,window=_blank]
. <<_mundane_skill,Nothing Skill>>
. xref:i-roll_playing_rules:CH08_Vocations_Spie.adoc#_spie_skills[Spie Skill,window=_blank]
. xref:i-roll_playing_rules:CH08_Vocations_Veterinarian.adoc#_vet_skills[Vet Skills,window=_blank]

== Anthro Abilities
Abilities are unlearned aptitudes that are baked into the persona's physiology.
A persona can only have the ability photosynthesis built into her.
Anthro abilities can from come from their anthro type, vocation or a mutation.
All abilities are recorded in the abilities section of the persona record.

The player must randomly choose her anthro type to score anthro abilities like torpor or frenzy.
The player must randomly choose her vocation type to score vocation abilities like mnemonic trapping.
Mutations are assigned to persona depending on the anthro types and attributes of the persona.

== Anthro Artifacts
Personas get a TOYs roll. 
It is completely random and only one roll is made. 
The result can range from random junque to starcruiser. 

IMPORTANT: *Welcome friend of EXP. TOYS is unfinished in V6.0 of EXP.*

include::ROOT:partial$CH20_Table_Class_Specific_Artifacts.adoc[]

== Anthro Name
Random personas are best named at the end of persona generation.
Anthro creation in the Role Playing System is player centered, not dice centered.
So creating a persona that reflects it's name is more easily achieved.

== Anthro Appearance
The most basic observable description should be included here. 
For anthros that means the family anthro and species of choice. 
Additional descriptors like clothing, personality can also be included here.
For example, anthro feline tabby wearing a camo kilt carrying a big rifle.

== Anthro History
Keep track of the fun.
Entirely optional.
