= Role Playing Rules

[quote]
____
*One roll to rule them all, and in the story bind them.*
____

. <<_introduction,Introduction>>
. <<_4d2_mechanic,4D2 Mechanic>>
. <<_combat,Combat>>
.. Attack Rolls, Combat Tables
. <<_performance,Performance>>
.. Performance Rolls
. <<_attribute_rolls,Attribute Rolls>>
. <<_saving_rolls,Saving Rolls>>
. <<_critical_rolls,Critical Rolls_>>
. <<_sphincter_rolls,Sphincter Rolls>>
. <<_time,Time>>
. <<_health,Health>>
. <<_skills,Skills>>
. <<_experience,Experience>>
. <<_driving,Driving>>
. <<_encumbrance,Encumbrance>>
. <<_terrain,Terrain>>
. <<_artifact_identification,Artifact Identification>>
. <<_negotiations,Negotiations>>
. <<_money,Money>>
. <<_mundane_equipment,Mundane Equipment>>
. <<_encumbrance,Encumbrance>> 

== Introduction
Role Playing Rules help guide the players tell a cinematic and compelling story.
The Role Playing System is very qualitative. 
In this case qualitative indicates words are used instead of numbers. 
Where the Roll Playing System has a plethora of complicated dice systems the Role Playing System has only one.

The Role Playing System use one mechanic that gives descriptive outcomes.
Dice are still required to play the Role Playing System. 
The Role Playing System uses the 4D2 Mechanic to sort things out.

The 4D2 Mechanic is a a story telling aid.
When personas meet in combat the 4D2 Mechanic can decide the outcome of the combat.
When a persona is attempting to fix an engine the 4D2 Mechanic can decide the outcome.
For more details about the 4D2 System take a xref::CH26_Fourdeetwo.adoc[look here].

The Role Playing System does not use mats or minis.
Most every quantitative aspect in the Roll Playing System is replaced with descriptions.
The 4D2 Mechanic offers direction and the players make the best decision for the story.
The main story is built by the players and follows a campaign.
The rules discussed in this section generate sub-stories.
These sub-stories are called combat stories or performance stories. 

== 4D2 Mechanic Primer
4D2 is both a descriptor and a joke. 
The 4 indicates that the mechanic uses 4 dice.
The 4 also indicates that there are 4 steps in the process.
The D refers to dice, and it a play on "D" in the 4d6 convention.
The 2 reflects that the mechanic has two directions.
The joke is that 4D2 sounds like 42.
Fourty Two is the answer to the question.
The 4D2 Mechanic gives the answers to questions you don't understand.

The 4D2 Mechanic uses four six sided dice to guide the story in the Role Playing System.
The 4D2 Mechanic is a bespoke decision tool for EXP's Role Playing System.
4D2 replaces Attack Rolls, Performance Rolls, Attribute Rolls, Saving Rolls, Sphincter Rolls and more.

In the Role Playing System the 4D2 Mechanism is used to guide the story. 
Players ultimately guide the outcomes generated by the 4D2 Mechanic.

.*Four steps of 4D2 Mechanic*
. get *Result* from 4D2 mechanic
. get *Descriptor* from Result
.. Apply the Shifts
. Decide *Outcome* from Descriptor
. Return to story telling

=== 4D2 Results
The result is the number produced by rolling two pairs of competing six siders.
The player rolls 2d6 and generates a number between 2 and 12.
Another player rolls 2d6 and generates another number between 2 and 12.
The second roll is subtracted from the first roll.
The curve is quite beautiful.

=== 4D2 Result Generation
.Outcome = 2d6 - 2d6
****
Range is +10 to -10. Positive is positive. Negative is negative. Zero is neutral.
****

=== 4D2 Descriptors
The 4D2 Mechanic Result can be used as a raw number to determine what happens to the persona.
There is also a descriptor table that correspondingly dramatic descriptors for every result.
The 4D2 Mechanic Result is converted to a descriptor for fun and efficiency.
For example, +10 is an Immaculate Success and -10 is a Cataclysmic Failure.

include::ROOT:partial$CH26_Table_4D2_Descriptors.adoc[]

=== 4D2 Outcomes 
Often a descriptor gives adequate guidance to the players telling the story.
For common 4D2 Mechanic uses there are also Outcome Tables.
Outcome tables include some common results for their associated descriptors.
This is especially important when a persona's life is one the line. 

// use to guide 

There are only two outcome tables supplied in the Role Playing System.
There is a Combat Outcomes Table and a Maneuvers Outcome Table.
Players can devise their own outcome tables for other repetitive decision.
For example, frequent teleportation may require an outcome table.

===  Shifts
Shifts are similar to bonuses or penalties.
Shifts are very important and are the only way players can gain advantage in the 4D2 system.
A shift is anything that moves the Descriptor of the 4D2 Mechanism Result.
A Shift moves the Descriptor and changes the Outcome of the Result.
A Shift of 2 would move a Solid Success (+2) to an Outstanding Success (+4).

== Combat
Combat in the Role Playing System employs the 4D2 Mechanic to guide the combat story.
The 4D2 Mechanic evolved from a legacy mechanic called the Theatrical Combat System.
The name has stuck for sentimental and legacy reasons.
The Theatrical Combat System guides combat stories so that players can make the most fun choices.

Theatrical Combat has it's xref::CH26_Theatrical_Combat.adoc[own section].

== Performance
Everything is an maneuver in EXP.
In this context a maneuver is any persona action that has an unclear outcome.
The __unclear__ part of the outcome is determined by randomness.
Players can guide the randomness by using skills, and attempting maneuvers in their wheelhouse.

Theatrical Performance has it's xref::CH26_Theatrical_Performance.adoc[own section].

== Attribute Rolls
Attributes function completely differently in the Role Playing System.
There is no collection of attributes with scores attached to them.
Personas have an attribute section on their persona record.
However only those attributes which the persona excels at are listed.

When comparing attribute the players generate a 4D2 Mechanic Result.
Success is determined by this mechanic.
If the persona has a PSTR attribute she enjoys a Shift for an attribute challenge.
Personas can also enjoy size shifts.

== Saving Rolls
All saving rolls in the Role Playing System use the 4D2 Mechanic.
Success indicates that the toxin has reduced effect.
Failure indicates that the toxin harms the persona.
The outcomes and shifts of the 4D2 Mechanic are dependent on the toxin type.

.*Example Saving Rolls*
* Save versus Radiation sickness. 
The persona can use her CON attribute for shift.
A success protects the persona.
A failure leaves the persona sick from radiation.
* Save versus Stun
The persona can use her CON or MSTR to earn a shift.
Success protects the persona.
A failure leaves the persona unconscious.
* Save versus lethal poison.
The persona can use her CON to earn a shift.
Success protects the persona.
A failure may leave the persona dead.


== Critical Rolls
The 4D2 Mechanic has two critical results. 
The positive critical result is called an Immaculate Success.
The negative critical result is called a Cataclysmic Failure.
These are extreme results and have critical impacts on the personas.

== Sphincter Rolls
A Sphincter Roll is used to help the players make inexplicable decisions.
For example, is a much needed air lock bolt in stock or not?
The 4D2 Mechanic replaces the Sphincter Rolls.
The descriptor determines the outcome for the expedition.
Success indicates a decision in the expedition's favour. 
Failure indicates an unfavourable decision for the expedition.

== Time
Time is entirely arbitrary in the Role Playing System.
There are no units, melees or turns. 
Time passes as needed to tell the best story.
Below is a completely unnecessary time table.

include::ROOT:partial$CH12_Table_Time_Components.adoc[]

== Health
There are no Hit Points, aging in the Role Playing System. 
Any health concerns that arise decided by the 4D2 Mechanic.
Aging effects are entirely directed by the best outcomes for the story.

== Skills
Skills acquisition replaces the entire EXPS and EXPS Level system.
Personas acquire new skills when they made Immaculate or wondrous successes.
The more skills the persona has the better they are at their Vocation.

== Experience
Skills acquisition replaces the entire EXPS and EXPS Level system.
Personas acquire new skills when they made Immaculate or wondrous successes.
The more skills the persona has the better they are at their Vocation.

== Driving
Personas can only drive vehicles if they have a driving skill.
In general personas can drive their vehicles wear ever they want without incident.
The 4D2 Mechanic is employed to determine the outcome of driving shenanigans.
The persona may enjoy shifts for DEX attributes, Driving Skills, and Handling Class.

== Terrain
Terrain is about description, ambiance and milieu. 

== Artifact Identification
Unidentified artifacts are fiddled with using the 4D2 Mechanic.
Success indicates identification of the artifact.
Immaculate Success may indicate a new skill regarding the artifact 
Failure indicates the artifact remains unidentified.
Cataclysmic Failure may indicate artifact damage or accidental activation. 

== Negotiations
Negotiations should always be role played in the Role Playing System.
Robots and anthros always have language skills.
Flora or fauna may attack the expedition due to hunger, territory, or fun. 
Whether they attack can be determined with the ubiquitous 4D2 Mechanic.

== Money
Who cares.
Personas should be cinematically and theatrically saving the universe. 
Sheesh.

== Mundane Equipment
What equipment is available to personas is entirely decided by the milieu of the game.
A leather and dust pre-apocalyptic scavenger game may have no equipment.
A suburban post-apocalyptic retro big box store game may have any or all equipment.
In the two cases above pre and post apocalyptic refer to the apocalypse of commerce.

== Encumbrance
Who cares.
Personas should be cinematically and theatrically saving the universe. 
Sheesh.
Abusers of this generous position should have disadvantages assigned by the players. 


