= Theatrical Combat

[quote]
_____
*This failure in communication has escalated quickly.*
_____

.*Core Rules*
. <<_introduction,Introduction>>
. <<_4D2_mechanic_primer,4D2 Mechanic Primer>>
. <<_number,Number>>
. <<_outcome,Outcome>>
. <<_descriptor,Descriptor>>

.*Optional Rules*
. <<_shifts,Shifts>>
. <<_anthro_combat,Anthro Combat>>
. <<_robot_combat,Robot Combat>>
. <<_alien_combat,Alien Combat>>

.*Even More Optional Rules*
. <<_folded_rolls,Folded Rolls>>
. <<_attack_types,Attack Types>>
. <<_armour_rating,Defence Rating>>
. <<_range,Range>>
. <<_attack_frequency,Attack Frequency>>
. <<_size_shifts,Size Shifts>>

.*None Rules*
. <<_movement,Movement>>
. <<_time,Time>>
. <<_initiative,Initiative>>
. <<_ambush,Ambush>>
. <<_weather,Weather>>
. <<_hit_location,Hit Location>>
. <<_vehicle_combat,Vehicle Combat>>


== Introduction
The Theatrical Combat System is the cinematic and storyful sibling of the Tactical Combat System.
The Theatrical Combat System assists the players in telling a combat story. 
Combat in the Role Playing System employs the 4D2 Mechanic to guide the combat story.
The 4D2 Mechanic evolved from a legacy mechanic called the Theatrical Combat System.
The name has stuck for sentimental and legacy reasons.
The Theatrical Combat System guides combat stories so that players can make the most fun choices.

The Theatrical Combat System is not a tactical combat system.
All of EXP's rules build off of the Tactical Combat System.
The Tactical Combat System requires maths, hex mats, tokens, miniatures and lots of dice.
The tactical system feigns war game level single persona combat outcomes.
The players measure success by removing a target's hit points and increasing their persona's experience points. 
The Roll Playing System and it's Tactical Combat System is storyful, but dice rolls more heavily direct the outcomes.

The Role Playing System employs a single dice mechanic that helps players direct the story.
The Role Playing System's Theatrical Combat System is not necessary for combat situations. 
If a particular combat resolution makes for a better story, then the Theatrical Combat System is not activated.
Successes are qualitative and descriptive.

NOTE: *The players interpret outcomes in the cinematic fashion that best serves the story.*

In the Theatrical Combat System, there are only descriptions.
The system has no hit points, no movement, no proficiencies, and no attack rolls to monitor.
The players must work their imagination muscle more than their maths muscle.
A description often requires more effort than subtracting six from 48.
The outcomes are descriptive and require a creative description.

The Role Playing System and its combat resolution tool still have dice rolls.
The dice offer randomness and force the players into unexpected storylines. 
The Theatrical Combat System only uses on dice mechanic.

== 4D2 Mechanic Primer
4D2 is both a descriptor and a joke. 
The 4 indicates that the mechanic uses 4 dice.
The 4 also indicates that there are 4 steps in the process.
The D refers to dice, and it a play on "D" in the 4d6 convention.
The 2 reflects that the mechanic has two directions.
The joke is that 4D2 sounds like 42.
Fourty-two is the answer to the wrong question.
The 4D2 Mechanic gives the answers to questions you can't understand.

The 4D2 Mechanic uses four six-sided dice to guide the story in the Role Playing System.
The 4D2 Mechanic is a bespoke decision tool for EXP's Role Playing System.
If you are familiar with the Roll Playing System of EXP, the 4D2 replaces Attack Rolls, Task Rolls, Attribute Rolls, Saving Rolls, Sphincter Rolls and more.

.*Four steps of the 4D2 Mechanic*
. A player rolls dice to get a  *Number*
. That  *Number* yields an *Outcome*
. The   *Outcome* produces a *Descriptor*
.. The *Descriptor* comes from the players or a table.
. The *Story* is influenced by the *Descriptor*

WARNING: Do not proceed with this section until mastering an understanding of the xref:ii-role_playing_rules:CH26_Fourdeetwo.adoc[4D2 Mechanic,window=_blank].

=== Number
A player generates a number by rolling two pairs of competing six siders.
The player rolls 2d6, generating a number between 2 and 12.
The player rolls 2d6 again, generating another number between 2 and 12.
The player subtracts the second roll from the first roll.
The sum of these two numbers generates the *Number* of the 4D2 Mechanic.

=== 4D2 Number Generation
.Number = 2d6 - 2d6
****
The number is always between +10 to -10. + 
A positive number gives a positive outcome. +
A negative number gives a negative outcome. +
Zero gives a neutral outcome.
****

:art: 4d2_dice.png
:width: 250px
:snark: (6+1) - (4+2) = +1
:artist: HM
:date: 2020
:license: CC BY-SA 4.0
:description: Two green dice and two red dice. Total score plus one.

include::ROOT:partial$articulate.adoc[]

=== Outcome
The outcome translates the number into a colourful account of the die roll.
The Outcome from Number Table uses the number to determine the *Outcome* from the 4D2 roll. 
The outcome arises directly from the 4D2 roll and is untainted by shifts (aka bonuses).
Often the outcome is enough of a description for the players to decide how things turn out.

The outcome can have a direct effect on the persona.
A persona can earn a new combat skill for very successful descriptors.
The combat outcome differs between inorganic and organic targets. 

include::ROOT:partial$CH26_Table_4D2_Outcomes.adoc[]

=== Learning Skills
If the player rolls an Immaculate or Wondrous success, her persona earns a skill in the combat maneuver she performs. 
This skill reward precedes the adding of any shifts.
A persona cannot earn skills based on shifted rolls. 
Only the unshifted outcome can earn a skill.

=== Skill Learning
.Outcome = Immaculate (+10) or Wondrous (+9) success
****
Persona earns +1 to the combat maneuver she is performing.
****

=== Descriptor
Often the Outcome gives enough info for the players to tell the story.
Describing an outcome is easy for Immaculate Successes and Cataclysmic Failures.
The other 19 possible outcomes are more subtle and harder to turn into a description.

There is a Descriptor Table for Combat when the players can't manage a description or agree on a description. 
Most players prefer a descriptor table for when a persona's life is on the line.

include::ROOT:partial$CH26_Table_4D2_Descriptors_Combat.adoc[]

If a player were to roll a Majestic Success (+7), her persona has dealt a mortal wound to her opponent. 
If a player were to roll a Major Failure (-3), her persona has been knocked back by her opponent.

=== Descriptor Descriptions
Aliens and anthros are organic targets, and robots are inorganic targets.
Robots damage differently from organics, and the outcomes are descriptively and effectively different.

The player may choose any success descriptor lesser than the one generated.
If the descriptor indicates a Mortal Wound, the player can choose from Wounded, Stunned or Backfoot if she desires.

.*Organic Successes*
Fatal Wound:: 
The target has suffered a fatal injury on the battlefield and is dead.
A Fatal Wound is a victory condition, and the target is dead.

Mortal Wound::
The target has suffered an injury that will quickly end their life.
A Mortal Wound is a victory condition, and the target is out of combat.
The target will remain alive until combat ends.
If they do not receive immediate care, they will die.

Severe Wound::
The target has suffered an obvious injury.
A Severe Wound is a victory condition, and the target is out of combat.
The target will remain alive even after combat ends.
If they do not receive eventual care, they may die. 

Wound::
The target has suffered an obvious injury.
A Wound is not a victory condition, and the target continues in combat.
A wounded target is unable to move without physical assistance.
Often there will be some penalty for being wounded.
The most manageable penalty is to limit the persona's total shifts when they are wounded.
More wounds can result in more penalties. 
Quick fixes can remove wounds and remove penalties.

Severe Stun::
A Severe Stun rattles the persona but does not include an apparent injury.
A Severe Stun is not a victory condition, and the target continues in combat.
A severely stunned target is unable to move without assistance.
There are no other penalties for a severe stun.
A Severe Stun remains until combat ends, or the persona gets a quick fix. 

Stun::
A Stun rattles the persona but does not include an apparent injury.
A Stun is not a victory condition, and the target continues in combat.
A stunned target is unable to move without encouragement.
There are no other penalties for a severe stun.
A Stun spontaneously resolves at the end of the combat turn. 

Knockback::
A Knockback pushes the target back in the direction of the attacker's preference.
The knockback is not a victory condition, and the target continues in combat.
A knockback does not send a target flying across the battle map. 
Knockback has no movement or shift penalties.

Backfoot::
The player can choose some mildly compromised position for her opponent.
The opponent suffers no shift for this compromise.
However, it may aid the persona to escape or do some other cunning thing.

.*Organic Failures*
If the player's 4D2 roll is negative, her persona can suffer the successes described above as failures. 
Ouch.

.*Inorganic Successes*
Attribute Loss::
Attribute Loss is the most severe damage that a robot can sustain.
Attribute loss indicates permanent damage to a crucial system.
The robot target must permanently cross the attribute off of her attribute list.
Attribute Loss destroys the robot if there are no attributes to remove.
Destruction of attributes is the only victory condition for robot opponents.

Attribute Damage::
Attribute Damage is a temporary loss of an attribute for the target.
The target robot will be unable to use the attribute or shift the attribute grants until the end of combat. 
A damaged attribute cannot lead to robot destruction.
The attribute is disabled but still present.
Damaged attributes reboot back to normal when combat is over.

Peripheral Destruction::
Peripheral Destruction is a very severe injury for the target robot.
Peripherals are baked-in robot abilities that are a mix of hardware and programmes.
The player, usually the referee, must choose a peripheral to remove from her persona.
This peripheral is not repairable after combat.
Peripheral Destruction has no effect if there are no peripherals to destroy.

Peripheral Destruction::
Peripheral Destruction is a very severe injury for the target robot.
Peripherals are baked-in robot abilities that are a mix of hardware and programmes.
The player, usually the referee, must choose a peripheral to remove from her persona.
This peripheral is not repairable after combat.
Peripheral Destruction has no effect if there are no peripherals to destroy.

Peripheral Damage::
Peripheral Damage is a temporary injury for the target robot.
Peripherals are baked-in robot abilities that are a mix of hardware and programmes.
The player, usually the referee, must choose a peripheral to remove from her persona.
This peripheral is repairable during combat and spontaneously reboots after fighting.
Peripheral Damage has no effect if there are no peripherals to damage.

Programme Destruction::
Programme Destruction is a very severe injury for the target robot.
Programmes are software skills that have no hardware.
The player, usually the referee, must choose a programme to remove from her persona.
This programme is not repairable after combat.
Programme Destruction has no effect if there are no programmes to destroy.

Programme Damage::
Programme Damage is a temporary injury to the target robot.
Programmes are software skills that have no hardware.
The player, usually the referee, must choose a programme to remove from her persona.
This programme is repairable during combat and spontaneously reboots after the battle.
Programme Damage has no effect if there are no programmes to damage.

Severe Rattle::
Severe Rattle is like a cross between stun and knockback from the organic successes.
There is no impact on the robot's ability to fight or move during combat.
A Severe Rattle makes the robot more susceptible to priority commands and robotic overrides. 
The control susceptibility lasts until the end of the battle unless reversed by a mechanic.

Rattle::
Rattle is like a cross between stun and knockback from the organic successes.
There is no impact on the robot's ability to fight or move during combat.
A Rattle makes the robot more susceptible to priority commands and robotic overrides. 
The control susceptibility spontaneously resolves at the end of the combat turn.

Cosmetic Injury::
The robot has a new scratch or dent.

.*Inorganic Failures*
If the player's 4D2 roll is negative, her persona can suffer the successes described above as failures. 
Bonk.

== Shifts
Shifts are similar to bonuses or penalties.
A shift is anything that moves the Descriptor.
A shift only applies to the descriptor.
A shift does not apply to an outcome.

NOTE:: Players cannot use shifts to improve the chance to learn skills.

A Shift moves the Descriptor and benefits the player's persona.
A Shift of 2 would move a Knockback (+2) to a Severe Stun (+4).

Shifts are fundamental and are the only way players can gain an advantage in the Theatrical Combat System.

Shifts come from the persona's attributes, abilities and skills.
However, anything can become a shift if the players accept it.
In hand-to-hand combat, a player can use STR as a shift.
When shooting a pistol, a Pistol skill is an obvious shift.
A glorious description of how the persona throws a grenade can earn a shift.

=== Counter Shifts
Competing personas or situations can counter the shifts a player can use.
For example, a persona is in a pistol fight with an opponent. 
She has a pistol skill and a DEX Attribute.
She can Shift her descriptor by +2.
If her opponent has Pistol 2, then the competing Shifts would cancel out.

=== Negative Shifts
The Theatrical Combat System is player-centric. 
The worst situation a persona can be in is to make a raw roll.
An unshifted raw roll is scary enough for a player. 

An essential referee persona should be toughened by reducing a player's success descriptor and not worsening a failure descriptor.
A plot-important referee persona can reduce a success descriptor by two but not worsen a failure descriptor.
A Mortal Wound (+8) wound decreases to a Severe Wound (+6), but a failure Wound (-6) would not worsen to a Mortal Wound (-8).
This descriptor adjustor acts similarly to armour. 

== Folded Rolls
A folded 4D2 roll is for when a +/- randomness cannot apply.
A persona falling from a great height should not earn a skill from a Wondrous Success.
A persona winning a lottery should not have become bankrupt from Catastrophic Failure.
These are examples of where the folded roll comes into play.
If it is good, how good is it?
If it is bad, how bad is it?

To create a folded roll, the player makes a regular 4d2 roll generating a number between +10 and -10.
The mechanic would indicate a positive outcome with a positive number and a negative outcome with a negative number.
We will avoid any maths here to stay in the spirit of the Role Playing System.

If the 4D2 roll is folding for a positive outcome, all the numbers become positive.
The player's roll now ranges from +10 to +10. 
The outcome and descriptors remain the same. 
Only detente and good things can happen.

If the 4D2 roll is folding for a negative outcome, all the numbers become negative.
The player's roll now ranges from -10 to -10. 
The outcome and descriptors remain the same. 
Only detente and bad things can happen.

== Attack Types
The attack types in the Theatrical Combat System Ranges are qualitative and descriptive.
There are no irritating letter categories like are found in the Tactical Combat System.

:art: type_a_sword.png
:width: 350px
:snark: Probably mightier than a pen.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Image of a modern sword with bucket hilt and a hint of energy at base.

include::ROOT:partial$articulate.adoc[]

=== Persona Powered Contact Attacks
These attacks depend on the muscle power of the attacker and must touch a target to cause damage.
The combatants must be within range of each other to engage in combat.
Examples are clubs, fists, claws, bites, swords, and ramming.
The Tactical Combat System calls these Strike attacks.

:art: bow_no_arrow.png
:width: 250px
:snark: Fancy bow.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Ornate fancy bow.

include::ROOT:partial$articulate.adoc[]

=== Persona Powered Ranged Attacks 
These attacks depend on the muscle power of the attacker and are flung at the target to cause damage.
The combatants must be within range to damage each other.
Examples are arrows, bolts, rocks, quills and spit.
The Tactical Combat System calls these Fling attacks.

:art: XHP_rifle.png
:width: 350px
:snark: Large bore rifle.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Rifle with extra large calibre.

include::ROOT:partial$articulate.adoc[]

=== Energy Powered Ranged Attacks
These attacks do not require muscle of the user and are pointed at the target to cause damage.
The energy comes from a battery, a bullet or some combination.
Combatants can be quite far apart and be able to damage each other.
Examples are bullets, laser bolts, energy beams, and crossbow bolts.
The Tactical Combat System calls these Shoot attacks.

:art: aerosol_aoe.png
:width: 300px
:snark: Aerosol attack.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Man throwing spray can onto bbq of another man dressed like a cook.

include::ROOT:partial$articulate.adoc[]

=== Area of Effect Attacks 
Area of effect attacks act upon an area instead of a target.
Every target in the area of effect is simultaneously attacked. 
Area of effect attacks do not need direct contact with the target to cause damage.
Examples are frag grenade, napalm aerosol, or flaming breath.
The Tactical Combat System calls these Area Attack Types.

The Tactical Combat System has a complex set of rules, using hexagon mats, to determine which personas are in the area of effect.
The Theatrical Combat System has no such rules.
The referee and players must quickly decide which targets are in the area of effect. 

The player makes a 4D2 roll when she launches the attack. 
Any outcome Detente (0), or better, indicates a successful grenade, aerosol or bomb attack. 
Any outcome Failure (-1 to -8) indicates a failed area of effect attack.
A failed attack means "no targets were harmed during the making of this explosion."
A Calamitous Failure (-9) will harm other expedition members.
A Cataclysmic Failure (-10) indicates a catastrophic malfunction of the area of effect weapon. 

include::ROOT:partial$CH26_Table_4D2_Descriptors_AOE.adoc[]

Every target in the area of effect must make a negative folded roll to determine the attack's impact.
If efficiency is of concern, one roll can determine the impact on all persona's in the area of effect.


:art: alien_robot_anthros.png
:width: 600px
:snark: An alien, a robot and an anthro walk into a park...
:artist: JEShields, HM added robot
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Two humans a large tentacled alien and a tiny flying robot in the park.

include::ROOT:partial$articulate.adoc[]

== Anthro Combat
The Theatrical Combat System is based on anthros fighting anthros. 
Robots behave slightly differently due to their size and inorganic fabrication.
Aliens behave slightly differently due to their size.

== Robot Combat
There are some advantages to being an inorganic life form in combat.
Mental attacks like ESP or mental control are not effective on the inorganic brain.
Robots cannot be stunned or wounded and keep fighting until destroyed.

Size counts as a shift for robots in hand-to-hand combat.
Ramming is the robotic equivalent of hand-to-hand combat. 
If the players are using size shifts, larger robots can earn a size advantage.

== Alien Combat
There are some advantages to being an alien in combat.
Many aliens have natural attacks that do not run out of ammunition or batteries.
Aliens are not affected by wounds or mortal wounds and will keep fighting without penalties.
Aliens can be stunned by a combat blow.

Size counts as a shift for aliens in hand-to-hand combat.
If the players are using size shifts, larger aliens can earn a size advantage.

== Defence Rating
There are no Armour Ratings in the Theatrical Combat System.
Personas gain combat advantage from their skills, abilities, weapons, and size.
Completely ignoring armour is too unrealistic for even the Theatrical Combat System.
Armour can shift the persona's descriptor in her favour. 
A suit of combat armour can decrease a mortal wound to a mere wound.
More powerful armour may have an even more significant beneficial shift.
Plus two is the highest possible shift armour can offer. 

== Range
There are no minis or hex mats rules for the Theatrical Combat System.
Ranges are descriptive, and the effects of different ranges are qualitative.
The ranges help tell the best combat story possible. 
In most cases, the story will any need for ranges. 
Each descriptive level indicates how far apart the combatants can be and still engage a target.

.*Theatrical Combat Ranges*
. Grapple
. Persona powered contact attacks
. Persona powered projectile attacks
. Pistol attacks
. Rifle attacks
. Rifle and scope 
. Artillery attacks

== Attack Frequency
Under normal circumstances, each persona gets one 4D2 roll per turn.
Some attacks allow for more than one 4D2 roll per turn.
Some aliens are fast and can make multiple bites per turn.
Some weapons have fast triggers and can make multiple attacks per turn.
Some weapons are automated and fire bursts of projectiles.
The exact nature of the multiple attacks is in the weapon description.

Each attack allows the player one 4D2 roll. 
The player may choose the best number from the 4D2 rolls.
So a player whose anthro persona has a plasma rifle (3 attacks per unit) would get three 4D2 rolls and pick the best one.

Only aliens with multiple attacks and mercenaries can spread their attacks between different targets. 

== Size Shifts

include::ROOT:partial$CH26_Table_Size_Shifts.adoc[]

== None Rules
There are no real rules here, just concepts.
If any of these rules are crucial to gameplay, then consider using the Tactical Combat System.
The two combat systems mix and match very well. 
If detailed initiative and movement are essential, the players can use the tactical versions of these rules. 

=== Movement
Combat movement is qualitative in the Theatrical Combat System.
There are no minis, no tokens and no mats.
There are no movement rates.
If a movement decision is critical to the story, the 4D2 Mechanic can determine the result.

=== Time
There are no combat turns in the Theatrical Combat System.
The turns described her are players politely taking turns participating in the combat story.
If there is a race against time decision vital to the story, the 4D2 Mechanic can determine the result.

=== Initiative
There is no initiative in the Theatrical Combat System.
The players politely take turns participating in the combat story.
If there is a race against time built into the story, the players may use the 4D2 Mechanic to determine the outcome.

=== Ambush
There is no ambush in the Theatrical Combat System.
All parties politely take turns participating in the combat story.
If an ambush is part of the story, the players may use the 4D2 Mechanic to determine the outcome.

=== Weather
There are no weather effects in the Theatrical Combat System.
Meteorological effects are a purely descriptive element in this system. 

=== Hit Location
Neither the Theatrical Combat System nor the Tactical Combat System uses hit locations.
Hit locations are a descriptive element in both systems. 

=== Vehicle Combat
There are neither exatmo nor inatmo vehicle combat systems in the Theatrical Combat System.
Space ships and terrestrial vehicles should work as needed for the expedition.
Both are tools to propel the story.
If transportation shenanigans become part of the story, the players may use the 4D2 Mechanic to determine the outcome.

=== Combat Tables
There are no combat tables in the Theatrical Combat System.
The whole purpose of this combat system is to get away from maths.
