= Four D Two System

[quote]
_____
*Four D Two, Four-D-Two, 4D2 are word plays on 42. + 
The answer to the wrong question.*
_____

== 4D2 Mechanic
4D2 is both a descriptor and a joke. 
The 4 indicates that the Mechanic uses 4 dice.
The 4 also indicates that there are 4 steps in the process.
The D refers to dice, and it is a play on the "D" in the 4d6 convention.
The 2 reflects that the Mechanic has two directions.
The joke is that 4D2 sounds like 42.
Forty-Two is the answer to the question.
The 4D2 Mechanic gives the answers to questions you don't understand.

The 4D2 Mechanic uses four six-sided dice to guide the story in the Role Playing System.
The 4D2 Mechanic is a bespoke decision tool for EXP's Role-Playing System.
4D2 replaces Attack Rolls, Performance Rolls, Attribute Rolls, Saving Rolls, Sphincter Rolls and more.

In the Role-Playing System, the 4D2 Mechanic is used to guide the story. 
Players ultimately guide the results generated by the 4D2 Mechanic.

.*Four steps of the 4D2 Mechanic*
. Get a *Number* from the die roll
. Get an *Outcome* from the *Number*
.. Apply Shifts to the *Outcome*
. Get a *Descriptor* from the *Outcome*
.. By using a *Descriptor* Table *-or-*
.. From the players
. return to the *Story*

== Number
The Result is the number produced by rolling two pairs of competing six siders.
The player rolls 2d6 and generates a number between 2 and 12.
The player rolls another 2d6 and generates another number between 2 and 12.
The second roll is subtracted from the first roll.
This generates the Number of the 4D2 Mechanic.


=== 4D2 Number Generation
.Number = 2d6 - 2d6
****
Range is +10 to -10. Positive is positive. Negative is negative. Zero is neutral.
****

The 4D2 Mechanic generates a smooth curve of numbers between +10 and -10.
The Number is player-centric. 
Positive numbers indicate success, and negative numbers indicate failure.
The most common Number from this Mechanic is 0.
0 represents balance, detent or ongoing struggle.
+10 represents the epitome of success for the persona.
-10 represents the epitome of failure for the persona.
The curve is quite beautiful.

:art: fourDtwo.png
:width: 350px
:snark: Thank you anydice.com
:artist: Jasper Flick
:date: 2020
:license: AnyDice.com 

include::ROOT:partial$articulate.adoc[]

The 4D2 Mechanic generates a Number value.
The number is linked to an outcome which leads to a descriptor which returns to the story.

=== How to Roll Dice 
The more dice rolled at once, the more efficient the mechanism.
The player first rolls two six siders (2d6).
This is the positive value.
The same player rolls another two six siders (2d6).
This is the negative value.
Some quick arithmetic generates the Number.

All four dice can be rolled at once to save time.
One pair of dice is assigned as the positive roll. 
A different coloured pair of dice is assigned as the negative roll. 
For example, the positive six siders could be green, and the negative six siders could be red.

:art: 4d2_dice.png
:width: 250px
:snark: (6+1) - (4+2) = +1
:artist: HM
:date: 2020
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The 4D2 Mechanic Number can also be generated by rolling one six sider four times.
This makes the process more dramatic and more time consuming. 
Ultimately players and play groups will develop their own style for generating 4D2 mechanic Numbers.

=== Example Rolls
The player rolls 2d6, and the sum is 12. 
She rolls another 2d6, and the sum is 2.
The 4D2 Mechanic Number is +10 (12 - 2).
+10 is the best Number for the player's persona.

The player rolls 4d6 all at once.
Her red dice are positive and the sum is 9.
Her white dice are negative and the sum is 8.
The 4D2 Mechanic Number is +1 (9 - 8).
+1 is a common Number and represents a slight win for the persona.

The player rolls 1d6 four times in a row. 
Her first roll is 3.
Her second roll is 1.
These two rolls are added to get a positive of +4.
Her third roll is 4.
This is subtracted from +4 to get 0.
Her fourth roll is 6.
This is subtracted from 0 to get -6.
The 4D2 Mechanic Number is -6.
This is a terrible Number and a badness is coming for the player's persona.

== Outcome from the Number
The 4D2 Mechanic Number can be used as a raw number to determine what happens to the persona.
Everyone at the table is aware that +10 is great and -10 is a disaster. 
What do all those other Numbers mean?
Each Number result has an Outcome associated with it. 
There is an Outcome table that has correspondingly dramatic Outcomes for each Number.
The 4D2 Mechanic Number is converted to an Outcome for fun and efficiency.
For example, +10 is an Immaculate Success, and -10 is a Cataclysmic Failure.

include::ROOT:partial$CH26_Table_4D2_Descriptors.adoc[]

The Outcome Table helps __guide__ the players describe the Outcome of the maneuver.
A positive Number yields a success Outcome.
A negative Number yields a failure Outcome.
The Outcome may be all the players need to move the story along. 
For example, a Vet is trying to remove a splinter from a feline's paw.
An Outcome that is an Immaculate Success would be enough to guide a happy story. 

// remove combat bent in this section neutral!

=== Example Outcomes 
A Number of +10 is an Immaculate success.
This Outcome is rare. 
Immaculate success represents the best possible Outcome for the persona.
The player can choose to kill, wound, or incapacitate her opponent.
A maneuver would totally stick and turn out better than expected.

A Number of +2 is a Solid Success.
This Outcome is quite common. 
Solid success represents a positive outcome for the persona, but nothing dramatic.
In combat, the persona has won an advantage, but the combat story is undecided.
A repair maneuver was successful but may fail sooner than expected.

A Number of -10 is a Cataclysmic Failure.
This Outcome is rare. 
Cataclysmic failure represents the worst possible Outcome for the persona.
In combat, the persona will suffer total defeat.
She could be killed, lethally wounded, or knocked unconscious.
Instead of a successful surgery the patient is killed and the persona loses confidence.

A Number of 0 is detent.
This Outcome is the most common. 
Detent represents a balance between the positive and negative.
The struggle is ongoing.
Dramatic fight music continues, and neither persona has the upper claw.

== Descriptor from the Outcome
Often the Outcome gives enough info for the players to tell the story.
This is easy for Immaculate Success and Cataclysmic Failure.
For the other 19 Outcomes some help may be needed.

For recurring 4D2 Mechanic decisions there are Descriptor Tables.
Descriptor Tables give examples of what could happen according to the Outcome.
This is especially important when a persona's life is one the line. 

NOTE: *The Descriptor is guided by the Outcome. The Descriptor can come from the players or a Descriptor Table.*

There are only two Descriptor tables included in the Role Playing System.
There is a Descriptor Table for Combat and a Descriptor Table for Maneuvers.
The players may never need or use either of these tables. 
The Descriptor Tables can be used to save time for repetitive acts.
The players may also create their own Descriptor Tables as they see fit.

include::ROOT:partial$CH26_Table_4D2_Combat_Outcome.adoc[]

include::ROOT:partial$CH26_Table_4D2_Maneuver_Outcome.adoc[]

==  Shifts
Shifts are similar to bonuses or penalties.
A shift is anything that moves the Outcome of the 4D2 Mechanism.
A Shift moves the Outcome therefore improving the persona's situation.
A Shift of +2 would move a Solid Success (+2) to an Outstanding Success (+4).
Shifts are significant and are the only way personas can gain an advantage in the 4D2 system.

Shifts come from the persona's attributes, abilities and skills.
However, literally, anything can become a shift if the players accept it.
In hand to hand combat, a player could use the PSTR as a shift.
When shooting a pistol, the player could use a pistol skill as a shift.
A glorious description throwing a grenade can earn a shift.

NOTE: *Maximum shift is +3*

A shift should move the Outcome and should not change the Number generated.
The Number is used to determine if a persona earns a skill during combat or a maneuver.
A shift of +1 triples the chance of a persona acquiring a new skill.
Shifting the Number creates the risk of creating over-powered personas.
The goal of shifts are meant to improve the persona's survival and performance.
Shifts are not meant to create skill heavy monster personas.

Negative shifts can be applied if the players feel it is appropriate. 
This makes a powerful enemy more difficult to defeat in combat. 

=== Example Shifts
A persona is in a pistol shootout. 
She has pistol skill and DEX attribute.
She can Shift her 4D2 Outcome by +2.
A Shift of +2 would move a Solid Success (+2) to an Outstanding Success (+4).
If her opponent has Pistol 2, then the competing Shifts would cancel out.

A persona is repairing an anti-grav modulator on a skimmer bike.
She has engine skill, and INT attribute.
The player casts a great yarn about using a piece of wire to reverse the polarity.
She can shift her 4D2 Outcome by +3.
A shift of +3 would move a Minor Failure (-1) to a Solid Success (+2).

A persona is play wrestling in the mud pit of a bar.
She has no wrestling skills.
She can use her PSTR and DEX attributes.
This allows her to Shift the 4D2 Outcome by +2.
This shifts her Magnificent Success (+8) into an Immaculate Success (+10).
The persona earns the accolades of the bar crowd (Outcome = +10), but does not earn a wrestling skill (Number = +8).

A persona has challenged a bow master to a shootout. 
The bow master has master level skills, plus DEX by two.
The persona is outclassed and has a Shift of -2.
The 4D2 Number is +10 this would normally be an Immaculate Success.
The Outcome is Shifted by -2 down to a Magnificent Success (+8).
The persona still earns a bow skill because her Number was +10.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== 4D2 Mechanic Learning Tools

:art: 4D2_Mechanic.png
:width: 750px
:snark: More or less complicating?
:artist: HM
:date: 2020
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Download a colourful One Pager (177k PDF) https://hughm3.sg-host.com/exp/6.0/_attachments/Role_Playing.pdf[here,window=_blank].
