= Four D Two System

[quote]
_____
*Four D Two, Four-D-Two, 4D2 are word plays on 42. + 
The answer to the wrong question.*
_____

== 4D2 Mechanic
4D2 is both a descriptor and a joke. 
The 4 indicates that the mechanic uses 4 dice.
The 4 also indicates that there are 4 steps in the process.
The D refers to dice, and it a play on "D" in the 4d6 convention.
The 2 reflects that the mechanic has two directions.
The joke is that 4D2 sounds like 42.
Fourty Two is the answer to the question.
The 4D2 Mechanic gives the answers to questions you don't understand.

The 4D2 Mechanic uses four six sided dice to guide the story in the Role Playing System.
The 4D2 Mechanic is a bespoke decision tool for EXP's Role Playing System.
4D2 replaces Attack Rolls, Performance Rolls, Attribute Rolls, Saving Rolls, Sphincter Rolls and more.

In the Role Playing System the 4D2 Mechanism is used to guide the story. 
Players ultimately guide the outcomes generated by the 4D2 Mechanic.

.*Four steps of 4D2 Mechanic*
. get *Result* from 4D2 mechanic
. get *Descriptor* from Result
.. Apply the Shifts
. get *Outcome* from Descriptor
. Return to story telling

== 4D2 Mechanic Results
The result is the number produced by rolling two pairs of competing six siders.
The player rolls 2d6 and generates a number between 2 and 12.
Another player rolls 2d6 and generates another number between 2 and 12.
The second roll is subtracted from the first roll.
The curve is quite beautiful.

:art: fourDtwo.png
:width: 350px
:snark: Thank you anydice.com
:artist: Jasper Flick
:date: 2020
:license: AnyDice.com 

include::ROOT:partial$articulate.adoc[]

=== 4D2 Result Generation
.Outcome = 2d6 - 2d6
****
Range is +10 to -10. Positive is positive. Negative is negative. Zero is neutral.
****

The 4D2 mechanic generates a smooth curve of results between +10 and -10.
The result is player centric. 
Positive numbers indicate success and negative numbers indicate failure.
The most common result from this mechanic is 0.
0 represents balance, detent or ongoing struggle.
+10 represents the epitome of success for the persona.
-10 represents the epitome of failure for the persona.

The 4D2 Mechanism Result is a numeric value.
Each possible outcome is linked to a descriptor that the player use to guide the story.

=== Example 4D2 Results
The 4D2 Mechanic Result can be generated by rolling one six sider four times.
The more dice rolled at once the more efficient the mechanism.
Most commonly one player rolls two six siders (2d6) and another player rolls the competing two six siders (2d6).
All four dice can be rolled at once by assigning plus to one coloured pair and minus to another coloured pair.

.*Some example results*
* The player rolls 2d6 and the sum is 12. 
The opposing 2d6 roll has a sum of 2.
The 4D2 Mechanic Result is +10.
+10 is the best result for the player's persona.

* The player rolls 2d6 and the sum is 9. 
The opposing 2d6 roll has a sum of 8.
The net roll is +1.
This will result in a very slight win for the player's persona.

* The player rolls her 2d6 and the sum is 4. 
The referee rolls her 2d6 and the sum is 10.
The net roll is -6.
This will result in a very bad outcome for the player's persona.

Every group will develop it's style for generating 4D2 Mechanic Results.
The most common is rolling 2 pairs of different coloured dice.
One pair is positive and the other pair is negative.
For example, the positive six siders could be white and the negative six siders could be red.

== 4D2 Mechanic Descriptors
The 4D2 Mechanic Result can be used as a raw number to determine what happens to the persona.
There is also a descriptor table that correspondingly dramatic descriptors for every result.
The 4D2 Mechanic Result is converted to a descriptor for fun and efficiency.
For example, +10 is an Immaculate Success and -10 is a Cataclysmic Failure.

include::ROOT:partial$CH26_Table_4D2_Descriptors.adoc[]

The descriptors help __guide__ the players describe the outcome of the maneuver.
A positive result (number) yields a positive success descriptor.
A negative result (number) yields a negative failure descriptor.
The descriptor may be all the players need to move the story along. 
For example, a Vet is trying remove a splinter from a feline's paw.
An Immaculate Success descriptor would guide the players to tell a story with a happy result.

// remove combat bent in this section neutral!

.*Some Example Descriptors*
* A result of +10 is an Immaculate Success.
This descriptor is rare. 
Immaculate Success represents the best possible outcome for the persona.
The player can choose to kill, wound, or render her opponent unconscious.
The descriptor guides the players to describe what tells the best combat story.

* A result of +2 is a Solid Success.
This descriptor is quite common. 
Solid Success represents a positive outcome for the persona, but nothing dramatic.
In combat the persona may have won an advantage, but the combat story is undecided.
The descriptor guides the players to describe what tells the best combat story.

* A result of -10 is a Cataclysmic Failure.
This descriptor is quite rare. 
Cataclysmic Failure represents the worst possible outcome for the persona.
In combat the persona will suffered total defeat.
The persona could be killed, lethally wounded, or knocked unconscious.
The descriptor guides the players to describe what tells the best combat story.

* A result of 0 is detent.
This descriptor is the most common. 
Detent represents a balance between the combatants.
The combat story is ongoing.
Dramatic fight music continues and neither persona has the upper claw.

== 4D2 Mechanic Outcomes 
Often a descriptor gives adequate guidance to the players telling the story.
For common 4D2 Mechanic uses there are also Outcome Tables.
Outcome tables include some common results for their associated descriptors.
This is especially important when a persona's life is one the line. 

There are only two outcome tables included in the Role Playing System.
There is a Combat Outcomes Table and a Maneuvers Outcome Table.
Players can devise their own outcome tables for other repetitive decision.
For example, frequent teleportation may lead to a fun outcome table.

The Combat Outcomes Table and a Maneuver Outcomes Table are included here.

include::ROOT:partial$CH26_Table_4D2_Combat_Outcome.adoc[]

include::ROOT:partial$CH26_Table_4D2_Maneuver_Outcome.adoc[]

==  Shifts
Shifts are similar to bonuses or penalties.
A shift is anything that moves the Descriptor of the 4D2 Mechanism Result.
A Shift moves the Descriptor and changes the Outcome of the Result.
A Shift of 2 would move a Solid Success (+2) to an Outstanding Success (+4).

Shifts are very important and are the only way players can gain advantage in the 4D2 system.

Some groups immediately add the Shift to the Result that the player generates.
There is a risk that this shortcut will lead to over-powered personas.
A shift of +1 triples the chance of the persona learning a new skill in combat.
A persona has a better chance of combat success using Shifts.
However using the adjusted outcome will lead to excessive skill acquisition.

=== Example Shifts
Shifts come from the persona's attributes, abilities and skills.
However literally anything can become a shift if the players accept it.
In hand to hand combat a player could use PSTR as a shift.
When shooting a pistol the player could use Pistol skill as a shift.
A glorious description of how a grenade is thrown could earn a shift.
These shifts are all added together and compared to their opponent's shifts.

For example, a persona is in a pistol fight with an opponent. 
She has Pistol skill and DEX Attribute.
She can Shift her 4D2 Outcome by +2.
This Shift of 2 could move a Solid Success (+2) to an Outstanding Success (+4).
If her opponent has Pistol 2 then the competing Shifts would cancel out.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

Negative shifts can be applied if the players feel it is appropriate. 
This makes a powerful enemy more difficult to defeat in combat. 

.*List of Example Shifts*
* PSTR attribute and DEX attribute in sword combat (+2 Shift).
The player generates 7 on the 4D2 Result.
The outcome is adjusted from Majestic Success (+7) to wondrous Success (+9).
The persona deals a fatal wound (+9) to her opponent.
However she can only learn a Temporary Skill (+7).

* DEX attribute, Grenade skill and a story about playing skeet ball (+3 shift).
The player generates -1 on her 4D2 Mechanic Result.
The outcome is shifted from a Minor Failure (-1) to a Solid Success (+2).
There are no persona skills listed on any of these outcomes.
The shift turned failure into success.

* Two personas are shooting arrows at each other. 
The player persona is out skilled by her opponent.
The net Shift is -2.
The player generates a 4D2 Mechanic Result of +10.
The outcome is shifted down from Immaculate Success (+10) to Magnificent Success (+8).
Combat outcome prevents the player from dealing a Fatal Wound.
However the persona would get a new skill from what she learned in the fight.
