= Alien Evolution

Alien is the colloquial term for the family diversidae.
Aliens encompass all non-anthropomorphic organic life forms with consciousness.
The process of generating an alien persona is random.
The player is creating not just her alien persona but an entire species. 
The term for creating an alien persona is "evolving" an alien persona. 

:art: alien_duck_ptreosaur_grasshopper_conifer.png
:width: 450px
:snark: Head: duck, Torso: pterosaur, Arms: grasshopper, Legs: conifer
:artist: Nelson
:date: 1992
:license: CC BY-SA 4.0
:description: Drawing of an alien Head: duck, Torso: pterosaur, Arms: grasshopper, Legs: conifer.

include::ROOT:partial$articulate.adoc[]

include::ROOT:partial$CH26_Table_Record_Alien.adoc[]

.*Alien Evolution*
. <<_alien_attributes,Attributes>>
. <<_alien_appearance,Appearance>>
. <<_alien_mutations,Mutations>>
. <<_alien_abilities,Abilities>>
. <<_alien_vocation,Vocations>>
. <<_alien_skills,Skills>>
. <<_alien_artifacts,Artifacts>>
. <<_alien_name,Name>>
. <<_alien_history,History>>

== Alien Attributes
The standard attributes of EXP are present in all personas.
In the Role Playing System, players only record those attributes at which the persona excels.
A persona can have a blank attributes section and function fine.
Another persona may have the attribute intelligence. 

====
*Attributes:* INT
====

The persona's intelligence attribute is worth noting. 
A persona can excel at more than one attribute.

====
*Attributes:* INT, DEX
====

There is no score assigned to an attribute. 
The persona either excels at an attribute or not.
The attributes help the personas when they undertake maneuvers.
For example, a persona with PSTR would be better at lifting than a persona with INT.
When two personas have the same attribute, then no advantage is given.
If two personas grappling both had physical strength, then neither gains an advantage.
However, if a persona with PSTR and DEX is grappling with a persona with just PSTR, they get a DEX advantage.

These advantages are called shifts and increase the chance of success with the 4D2 Mechanism.

Size::
Every player evolving an alien persona makes a size roll. 
Aliens can have variable sizes. 
Size can be used as an advantage if two personas have PSTR.
The personas with the larger size and PSTR will gain an advantage over the smaller persona with PSTR.
In the Role Playing System, the player does not record numerical wates and only uses the descriptor (Tiny, small, medium, large, gigantic).

include::ROOT:partial$CH06_Table_Alien_Size.adoc[]

Most Excellent Attribute::
The player rolls once to determine the most excellent attribute of her alien persona.

include::ROOT:partial$CH26_Table_Attribute.adoc[]

Awareness::
Awareness indicates how aware a persona is of her surroundings. 
It indicates how well is the persona's brain connects to the outside world. 
The attribute is a collective measure of the persona's sensors. 
AWE includes senses like hearing, vision, smell, touch and taste. 
Awareness does not include the sixth sense or a sense of style. 
The abbreviation for awareness is AWE.

Charisma::
Charisma is charm, looks and sociability all combined into one value. 
A high charisma represents a high proficiency at getting along with other personas. 
This attribute is universal, so any persona with a high CHA would be socially adept. 
A persona's charisma is crucial for inter-persona interactions.
The abbreviation for charisma is CHA.

Constitution::
Constitution represents a persona's internal physique.
CON is a combination of wellness, immunity, energy extraction, healing ability.
A high CON is better to repel disease, resist poisons, and repair damaged tissue.
The abbreviation for constitution is CON.

Dexterity::
Dexterity represents the connection between the brain and the outside world.
Agility, balance, eye-hand, reflexes and running speed are components of dexterity.
A high DEX person could run faster, dance better and quicker reflexes.
Dexterity would help the persona catch a priceless vase or dive through a closing door.
The abbreviation for dexterity is DEX.

Intelligence::
Intelligence indicates the smarts of the persona.
Elements of INT are memory, deduction, creativity, adaptability and their synergism. 
The higher the intelligence of the persona, the smarter she is.
The abbreviation for intelligence is INT.

Mental Strength::
Mental Strength exists as an attribute.
Players cannot roll mental strength as a most excellent attribute.
Players acquire MSTR through a story set out by the referee.
The players will decide if the persona has earned the MSTR attribute.
The abbreviation for mental strength is MSTR.

Physical Strength::
Physical Strength represents force the persona can generate to get work done. 
PSTR is a combination of leverage, power and physique. 
Physical Strength determines how much the persona can lift or damage by brute force. 
PSTR helps kicking open doors, breaking bonds, or crushing beer bottles.
The abbreviation for physical strength is PSTR.

Hit Points::
There are no hit points in the Role Playing System.
Combat and damage are both absolute and descriptive. 
There is no quantitative measure of well-being like 32 hit points out of 42.
Personas are damaged in combat by losing attributes, skills and abilities instead of hit points.
When the 4D2 Mechanic generates a Cataclysmic Failure, the persona can lose an attribute, skill or ability.
Extreme failures on the 4D2 Mechanic can mortally wound or kill the persona.
The abbreviation for hit points is HPS.

Social Standing::
There is no Social Standing in the Role Playing System.
The players must roleplay social interactions in the Role Playing System (go figure).
The abbreviation for social standing is SS.

EXPS and Level::
There are no Experience Points or Experience levels in the Role Playing System. 
Personas earn additional attributes, skills and abilities instead of experience points or levels.
The 4D2 Mechanic can generate new attributes, skills or abilities.
This process replaces experience points and experience levels.
The abbreviation for experience points is EXPS.

:art: alien_conifer_kelp_ape_spider.png
:width: 350px
:snark: Head: conifer, Torso: Kelp, Arms: ape, Legs: Spider
:artist: Nelson
:date: 1992
:license: CC BY-SA 4.0
:description: Drawing of alien with Head: conifer, Torso: Kelp, Arms: ape, Legs: Spider.

include::ROOT:partial$articulate.adoc[]

== Alien Appearance
Aliens are incredibly diverse.
Hence their family name diversidae.
Alien appearance is generated by generating four components and mashing them together.

=== Head Part
The alien's head part _usually_ stores the alien's brain and sensors.
The head is _usually_ located at the front of the alien.
Record the movement letters (l, a, w, s) associated with the head part.
The player may add an optional head adornment later.

=== Torso Part
The alien's torso part _usually_ stores the alien's vital organs.
The part does not indicate the types of vital organs, but they are most likely in the torso.
Record the movement letters  (l, a, w, s) associated with the torso part.
The player may add an optional torso adornment later.

=== Arms Part
The alien's arms part _usually_ indicates the persona front limbs and articulators.
The arms part has no impact on whether the alien is a tool user or not.
Record the movement letters (l, a, w, s) associated with the arms part.
The player may add optional grabby adornments later.

=== Legs Part
The legs part _usually_ indicates the primary way the alien gets around.
Record the movement letters (l, a, w, s) associated with the legs part.
The legs part does not solely determine alien locomotion.
If an alien can fly and run, it will have the parts for both. 
Often an alien's legs will not be legs at all but flukes, flippers, bulbs or blobs.
If the alien has a snake's legs, it slithers about.
If the alien has fish legs, it may wiggle or fin itself about.
If the alien has parrot arms and fish legs, it can still fly and slither.

include::ROOT:partial$CH06_Table_Alien_Body_Parts.adoc[]

:art: flying_tooth_trunker.png
:width: 350px
:snark: Elephant head, fly arms, no body
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Floating leather ball with an elephant trunk and teeth. 

include::ROOT:partial$articulate.adoc[]

=== Appearance and Movement
The alien appearance also determines what kind of terrain she can move through.
Some aliens will be able to fly or swim. 
There is a bracketed lowercase letter following each alien body part description. 
These bracketed letters help determine the movement types of the alien.
The Crab (lw) body part has l and w, and the Moth (a) body part only has a.
The crab can move on land and in water, and the moth can move in the air.

.*Movement as Abilities*
. l - land borne can move on land
. a - airborne alien has flying ability
. w - water-borne alien has swimming ability

The Mundane Terran phrases air, water and land describe alien movement.
Aquatic (w) indicates liquid.
Aquatic could be water or liquid ammonia.
Air (a) indicates gaseous.
Airborne could be air or carbon dioxide.
Land (l) indicates solid ground.
Sessile (s) indicates immobile and is not part of the movement system.

The three movement categories can be stacked. 
Land 3 would have an advantage over Land 2 and would enjoy a shift in a running race.
Air 2 would fly faster than Air 1 and would enjoy a shift in air combat.

== Alien Mutations
Alien mutations are natural abilities that the alien has evolved over time or in a vat.
Alien mutations can only be beneficial or useless. 
An alien will not evolve themselves a defect.

.*Mutate Now. Like Darwin said.*
* CON attribute personas are assigned one non-defective Physical Mutation.
* INT attribute personas are assigned one non-defective Mental Mutation.

The player heads to the designated mutation section and generates a random mutation.
If the players are diligent, the referee may allow players to choose their alien's mutation.
Keep in mind that some mutations are incredibly powerful and can influence game balance.
For more information about mutation types jump to xref:v-wetware:An_index_wetware.adoc[Mutations,window=_blank].

== Alien Abilities
Alien abilities are natural skills that their species evolved in some primordial state.
Mutations are the obvious alien abilities. 
Movement types are also abilities. 
An alien may also have some natural abilities that are part of her species.

Naturally evolved abilities are not compatible with vocation abilities. 
For example, an alien with three attacks per unit cannot use a pistol three times per unit. 
The three attacks are only for her naturally evolved attacks.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

=== Alien Attack Frequency
The attack frequency is how often the alien can use her natural attacks in each unit.
Attack frequency does not apply to artifact weapons or devices.
The alien can use only her natural attacks for multiple attacks. 

The alien will gain one advantage for every extra attack she has.
If an alien has two attacks per unit and is fighting a persona with one attack per unit, she gets an advantage. 

include::ROOT:partial$CH06_Table_Number_of_Alien_Attacks.adoc[]

=== Alien Attack Type
The alien attack types the standard attack types found in EXP.
These non-powered contact (A), non-powered ranged (B), and powered (type C).

include::ROOT:partial$CH06_Table_Alien_Attack_Type.adoc[]

==== Attack Type A
Type A attacks are thrusting, striking attacks powered by the alien's brawn.
These could be bites, punches, stabs, squishes, slashes, pecks, or scratches.
Type A attacks are in close combat, tentacle to tentacle attacks.
The vast majority of aliens employ type A attacks.

==== Attack Type B
Type B attacks are ranged attacks powered by the alien's brawn.
These could be acidic spittle, flying quills, ejected spines or darts.
Type B attacks have a range and shoot like an arrow.
These attacks are not long-range attacks, but close combat is not required.

==== Attack Type C
Type C attacks are the rarest and most alien naturalized attack types.
The alien has evolved a self-propelled powered attack that it controls.
These are attacks like lazer eyes or rapid-fire bone bullets.
Type C attacks appear naturalized but function like a weapon from the Gun Section.

=== Alien Tool Ability
Tool ability determines whether an alien species can use artifacts or not.
It would be very unusual for a player persona alien to be a none tool user.
None tool using means that the player's persona is local flora or fauna. 
Only a most experienced player would be able to play local flora or fauna as a persona.
The players may allow a player persona to roll again if they are none tool using.

Following are three examples of tool use ability on mundane terra.
Raccoons have no tool ability.
Apes demonstrate simple tool ability. 
Advanced apes (humans) have comp(uter) tool ability and are nowhere near creator tool ability.

include::ROOT:partial$CH26_Table_Gen_Alien_Tools.adoc[]

== Alien Vocation
A vocation is a calling or innate skill set possessed by the persona.
If the referee's milieu indicates, a vocation could mean training at a school, institute or guild.
The player may choose from any of the listed vocations or pick one randomly.
Allowing the dice to choose the persona's vocation allows for attributes and abilities to be awarded.
For example, choosing a vet does not allow the persona to add CHA or choose one ability.
A randomly chosen spie would get the DEX attribute and be able to choose one ability.

include::ROOT:partial$CH26_Table_Role_Vocations.adoc[]


=== Vocation Attributes
Each vocation is associated with an attribute.
If the player generates her vocation randomly, her persona gets the designated attribute.
If the player randomly rolls a mercenary, her persona gets the vocation attribute PSTR added to her attribute list. 
If the player chooses a mercenary, her persona does not get the vocation attribute PSTR added to her attribute list. 

=== Vocation Abilities
Many vocations are associated with baked-in abilities.
Abilities are not skills.
Any persona can acquire a skill.
Abilities are part and parcel of the vocation.
A persona cannot learn the vet Quick Fix ability. 
If the player generates her persona vocation randomly, she can choose one vocation ability.

Biologist::
The biologist dedicates herself to studying the organic world.
These studies range from its denizens to it's cultures.
The player can add AWE to her persona's attributes if she randomly chose this vocation.
Every biologist gets two xref:i-roll_playing_rules:CH08_Vocations_Biologist.adoc#biologist_skills[biologist skills,window=_blank].

Knite::
The knite dedicates herself to promoting order, or chaos, by connecting the Physical and Think Spaces. 
A player cannot choose or randomly generate the vocation knite.
Before a persona can become a knite, she must first earn her MSTR attribute.
A persona can earn the Knite vocation by completing a Knite qualification storyline laid out by the players.
The players will decide if the persona has earned the Knite vocation.
For more detail about knites jump to xref:i-roll_playing_rules:CH08_Vocations_Knite.adoc[knites,window=_blank].

Mechanic::
The mechanic dedicates herself to studying the inorganic world.
These studies range from robots to scientific systems.
The player can add INT to her persona's attributes if she randomly chose this vocation. 
The player can add a xref:i-roll_playing_rules:CH08_Vocations_Mechanic.adoc#_mechanic_abilities[mechanic ability,window=_blank] if she randomly chose this vocation. 
Every mechanic gets two xref:i-roll_playing_rules:CH08_Vocations_Mechanic.adoc#_mechanic_skills[mechanic skills,window=_blank].

Mercenary::
The mercenary works hard to promoting order, or change, via violence.
Mercenaries are not psychotic, violent or cruel.
They are skilled in the art of war and weapons.
The player can add PSTR to her persona's attributes if she randomly chose this vocation. 
The player can add a xref:i-roll_playing_rules:CH08_Vocations_Mercenary.adoc#_mercenary_abilities[mercenary ability,window=_blank] if she randomly chose this vocation. 
Every mercenary gets two xref:i-roll_playing_rules:CH08_Vocations_Mercenary.adoc#_mercenary_skills[mercenary skills,window=_blank].

Nomad::
The nomad prides herself on surviving and integrating into her surrounding world.
These survival skills include all aspects of survival, travel and shelter in all terrains.
The player can add CON to her persona's attributes if she randomly chose this vocation. 
The player can add a xref:i-roll_playing_rules:CH08_Vocations_Nomad.adoc#_nomadic_abilities[nomad ability,window=_blank] if she randomly chose this vocation. 
Every nomad gets twoxref:i-roll_playing_rules:CH08_Vocations_Nomad.adoc#_nomadic_biomes[nomad biomes,window=_blank].

Nothing::
The nothing vocation obsesses with all things mundane.
The mundane includes money, appearance and social standing.
The vast majority of the civilians of mundane terra are nothings.
Nothings have no combat skills and no useful maneuvers.
Nothings lack abilities or skills, but they do have a xref:i-roll_playing_rules:CH08_Vocations_Nothing.adoc#_career[career,window=_blank]and some xref:i-roll_playing_rules:CH08_Vocations_Nothing.adoc#_nothing_wealth[money,window=_blank].

Spie::
The spie is devoted to all things deceptive, sneaky and underhanded.
The realm of the spie includes disguises, sneaking and assassination.
The player can add CON to her persona's attributes if she randomly chose this vocation. 
The player can add a xref:i-roll_playing_rules:CH08_Vocations_Spie.adoc#_spie_abilities[spie ability,window=_blank] if she randomly chose this vocation. 
Every spie gets two xref:i-roll_playing_rules:CH08_Vocations_Spie.adoc#_spie_tricks[spie tricks,window=_blank].

Veterinarian::
The veterinarian is devoted to repairing and improving all organic beings.
This practice includes diagnosis, surgery and medications.
The player can add a xref:i-roll_playing_rules:CH08_Vocations_Veterinarian.adoc#_vet_abilities[vet ability,window=_blank] if she randomly chose this vocation. 
Every vet gets two xref:i-roll_playing_rules:CH08_Vocations_Veterinarian.adoc#_vet_skills[vet skills,window=_blank].

== Alien Artifacts
Personas get a TOYs roll. 
It is entirely random, and the player only makes one roll. 
The result can range from random junque to starcruiser. 
Aliens are not limited to using an artifact by their appearance. 
This one alien artifact will be a bespoke piece of equipment that the alien can use.
To generate a toy for the persona jump to xref:iii-hardware:An_index_hardware.adoc#_toy_type[Hardware,window=_blank].

== Alien Name
The player should name her alien persona at the end of its evolution.
The alien name should include a persona name and a species name. 
For more detail than you ever wanted jump to xref:i-roll_playing_rules:CH06_Aliens_14_Name.adoc[Alien Name,window=_blank].

== Alien Appearance
The player should decant her alien's description down to its most prominent features.
For example, the player picks the essential defining parts of her alien: a pigeon-headed caterpillar wearing a camo tent carrying a plastic bag.

== Alien History
Keep track of the fun.
Entirely optional.