= Anthro Creation
All anthros are upright, bipedal.
They have hands, heads and faces.
The fake taxonomy of life in EXP assigns Anthros to the family Hominidae and the genus Homo.
Mundane terra has an infestation of Hominidae homo pure strain.
EXP has many other anthro types.
Each anthro type is considered a species with names like homo avis or homo felis.
A homo felis (feline) can also add descriptors such as a cat, lion or cougar.
The player chooses the final appearance of the anthro type.

:art: anthro_humanoid_elf_biologist.png
:width: 250px
:snark: Elven biologist
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a bald humanoid elf with a butterfly and cute alien. 

include::ROOT:partial$articulate.adoc[]

include::ROOT:partial$CH26_Table_Record_Anthro.adoc[]

.*Anthro Creation*
. <<_anthro_attributes,Attributes>>
. <<_anthro_type,Type>>
. <<_anthro_mutations,Mutations>>
. <<_anthro_vocation,Vocations>>
. <<_anthro_artifacts,Artifacts>>
. <<_anthro_name,Name>>
. <<_anthro_appearance,Appearance>>
. <<_anthro_history,History>>

== Anthro Attributes
The standard attributes of EXP are present in all personas.
In the Role Playing System, players only record those attributes at which the persona excels.
A persona can have a blank attributes section and function fine.
Another persona may have the attribute Intelligence. 

====
*Attributes:* INT
====

The persona's Intelligence attribute is worth noting. 
A persona can excel at more than one attribute.

====
*Attributes:* INT, DEX
====

There is no score assigned to an attribute. 
The persona either excels at an attribute or not.
The attributes help the personas when they undertake maneuvers.
For example, a persona with STR would be better at lifting than a persona with INT.
When two personas have the same attribute, then no advantage is given.
If two personas grappling both had Strength, then neither gains an advantage.
However, if a persona with STR and DEX is grappling with a persona with just STR, they get a DEX advantage.

These advantages are called shifts and increase the chance of success with the 4D2 Mechanism.

Size::
Size is an attribute assigned to every persona.
All anthros are size medium.
The player records the medium size in the attributes section of the persona record.
For example, the persona record sheet could have Medium and INT recorded under 

Most Excellent Attribute::
The player rolls once to determine the most excellent attribute of her alien persona.

include::ROOT:partial$CH26_Table_Attribute.adoc[]

Awareness::
Awareness indicates how aware a persona is of her surroundings. 
It indicates how well is the persona's brain connects to the outside world. 
The attribute is a collective measure of the persona's sensors. 
AWE includes senses like hearing, vision, smell, touch and taste. 
Awareness does not include the sixth sense or a sense of style. 
The abbreviation for Awareness is AWE.

:art: ursidae_charismatic_leader.png
:width: 250px
:snark: Bearing witness
:artist: Doré, Gustave
:date: Pre 1883
:license: CC BY-SA 4.0
:description: Drawing of a bear standing with arms up and many bears bowing to her.

include::ROOT:partial$articulate.adoc[]

Charisma::
Charisma is charm, looks and sociability all combined into one value. 
A high Charisma represents a high proficiency at getting along with other personas. 
This attribute is universal, so any persona with a high CHA would be socially adept. 
A persona's Charisma is crucial for inter-persona interactions.
The abbreviation for Charisma is CHA.

Constitution::
Constitution represents a persona's internal physique.
CON is a combination of wellness, immunity, energy extraction, healing ability.
A high CON is better to repel disease, resist poisons, and repair damaged tissue.
The abbreviation for Constitution is CON.

Dexterity::
Dexterity represents the connection between the brain and the outside world.
Agility, balance, eye-hand, reflexes and running speed are components of Dexterity.
A high DEX person could run faster, dance better and quicker reflexes.
Dexterity would help the persona catch a priceless vase or dive through a closing door.
The abbreviation for Dexterity is DEX.

Intelligence::
Intelligence indicates the smarts of the persona.
Elements of INT are memory, deduction, creativity, adaptability and their synergism. 
The higher the Intelligence of the persona, the smarter she is.
The abbreviation for Intelligence is INT.

Mind::
Mind exists as an attribute.
Players cannot roll Mind as a most excellent attribute.
Players acquire MND through a story set out by the referee.
The players will decide if the persona has earned the MND attribute.
The abbreviation for Mind is MND.

Strength::
Strength represents force the persona can generate to get work done. 
STR is a combination of leverage, power and physique. 
Strength determines how much the persona can lift or damage by brute force. 
STR helps kicking open doors, breaking bonds, or crushing beer bottles.
The abbreviation for Strength is STR.

Hit Points::
There are no hit points in the Role Playing System.
Combat and damage are both absolute and descriptive. 
There is no quantitative measure of well-being like 32 hit points out of 42.
Personas are damaged in combat by losing attributes, skills and abilities instead of hit points.
When the 4D2 Mechanic generates a Cataclysmic Failure, the persona can lose an attribute, skill or ability.
Extreme failures on the 4D2 Mechanic can mortally wound or kill the persona.
The abbreviation for hit points is HPS.

Social Standing::
There is no Social Standing in the Role Playing System.
The players must roleplay social interactions in the Role Playing System (go figure).
The abbreviation for social standing is SS.

EXPS and Level::
There are no Experience Points or Experience levels in the Role Playing System. 
Personas earn additional attributes, skills and abilities instead of experience points or levels.
The 4D2 Mechanic can generate new attributes, skills or abilities.
This process replaces experience points and experience levels.
The abbreviation for experience points is EXPS.

== Anthro Type
There are twelve distinct anthro types.
If the player does not feel like choosing, she may randomly select her anthro type.

include::ROOT:partial$CH26_Table_Role_Anthro_Type.adoc[]

=== Anthro Type Abilities
If the player generates her anthro type randomly, she can choose from the abilities listed.
If the player wishes to choose her anthro type for style and story, the abilities are not an option.

:art: billiard_shark_necklaces.png
:width: 250px
:snark: Billiards not pool.
:artist: JEShields, Modified HM 2021
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Humanoid hammerhead shark holding a pool cue.

include::ROOT:partial$articulate.adoc[]

Aquarian::
Homo Pisces are anthropomorphized aquatic beings. 
The player may add the ability of water breathing to her aquarian persona.

:art: sandy_anxious_ostrich.png
:width: 190px
:snark: The sky is being gravitied!
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a humanoid ostrich very upset about something.

include::ROOT:partial$articulate.adoc[]

Avarian::
Homo Avis are anthropomorphized avarian beings.
Avarians can only acquire flying through mutation. 
The player may add the ability to detect ambush her avarian persona.

Canine::
Homo Canis are anthropomorphized dog beings.
The player may add the ability of radiation sense to her canine persona.

:art: anthro_equine_moose.png
:width: 250px
:snark: Beer can con
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a humanoid moose with beer cans and a large wooden sledge hammer.

include::ROOT:partial$articulate.adoc[]

Equine::
Homo Equus are anthropomorphized hoofed beings.
The player may add either the ability sprinting or the ability jumping to her equine persona.

Feline::
Homo Felis are anthropomorphized cat beings.
The player may add either the ability to ambush or night vision to her feline persona.

Florian::
Homo Flora are anthropomorphized plant beings.
The player may add the ability of photosynthesis to her florian persona.

Humanoid::
Homo Mutabilis can appear in any humanoid form.
Some examples of homo mutabilis are simians, hobbits, suidae, dwarves, humans or orcs.
The player may add an ability from Physical Mutations or Mental Mutations.
The mutation will be randomly assigned. 
The player must remove CHA from her attribute list.

Insectoid::
Homo Insectum are anthropomorphized insect beings.
The player may add the ability of neural stability to her insectoid persona.
Neural stability offers added defence against mental attacks.

:art: purestrain_negotiator.png
:width: 250px
:snark: Charisma is the purestrain's forte.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Young woman in cyberpunk clothes kneeling empathically.

include::ROOT:partial$articulate.adoc[]

Pure Strain::
Pure Strains are Homo Sapiens sporting any imaginable skin colour.
The player may add the attribute CHA to her Pure Strain persona.
This persona cannot start with a mutation ability and cannot acquire mutation abilities.

Reptilian::
Homo Serpens are anthropomorphized reptile beings.
The player may add either the ability Torpor or the ability Chameleon to her persona.

:art: anthro_rodent.png
:width: 250px
:snark: Rat Patrol
:artist: Eric Hotz
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a humanoid rat wearing combat armour and leaning on a rifle.

include::ROOT:partial$articulate.adoc[]

Rodentia::
Homo Rodens are anthropomorphized rodent beings.
The player may add either the ability Night Vision or the ability Sprinting to her persona.

Ursidae::
Homo Ursus are anthropomorphized bear beings.
The player may add either the ability Frenzy or the ability Hibernation to her persona.

== Anthro Mutations
Anthro mutations are fantasy genetic aberrations that offer the persona wondrous, mundane or treacherous abilities. 
Mutations are abilities.
If the player wants her persona to mutate, she gets one mutation.
Pure strain anthros do not get to mutate regardless of the player's wishes.
If the persona does not want her persona to mutate, her persona does not mutate.
Humanoid anthros automatically mutate regardless of the player's wishes.


.*Mutate Now. Avoid the post-bomb rush.*
* Homo Mutabilis get two random mutation abilities
* Pure Strains cannot get a mutation
* All other anthros get one random mutation ability -or-
** trade CON for one non-defective Physical Mutation.
** trade INT for one non-defective Mental Mutation.

The player heads to the designated mutation section and generates a random mutation.

== Anthro Vocation
A vocation is a calling or innate skill set possessed by the persona.
If the referee's milieu indicates, a vocation could mean training at a school, institute or guild.
The player may choose from any of the listed vocations or pick one randomly.
Allowing the dice to choose the persona's vocation allows for attributes and abilities to be awarded.
For example, choosing a vet does not allow the persona to add CHA or choose one ability.
A randomly chosen spie would get the DEX attribute and be able to choose one ability.

include::ROOT:partial$CH26_Table_Role_Vocations.adoc[]

=== Vocation Attributes
Each vocation is associated with an attribute.
If the player generates her vocation randomly, her persona gets the designated attribute.
If the player randomly rolls a mercenary, her persona gets the vocation attribute STR added to her attribute list. 
If the player chooses a mercenary, her persona does not get the vocation attribute STR added to her attribute list. 

=== Vocation Abilities
Many vocations are associated with baked-in abilities.
Abilities are not skills.
Any persona can acquire a skill.
Abilities are part and parcel of the vocation.
A persona cannot learn the vet Quick Fix ability. 
If the player generates her persona vocation randomly, she can choose one vocation ability.

:art: florian_procession.png
:width: 250px
:snark: Offering some lo bak go
:artist: Morey
:date: 1962
:license: CC BY-SA 4.0
:description: Drawing of a helmeted human looking at a procession of radish headed humanoids.

include::ROOT:partial$articulate.adoc[]

Biologist::
The biologist dedicates herself to studying the organic world.
These studies range from its denizens to its cultures.
The player can add AWE to her persona's attributes if she randomly chose this vocation.
Every biologist gets two xref:i-roll_playing_rules:CH08_Vocations_Biologist.adoc#biologist_skills[biologist skills,window=_blank].

:art: reptilian.png
:width: 250px
:snark: Knee deep in trouble
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of reptilian humanoid knee deep in water wielding an energy sword.

include::ROOT:partial$articulate.adoc[]

Knite::
The knite dedicates herself to promoting order, or chaos, by connecting the Physical and Think Spaces. 
A player cannot choose or randomly generate the vocation knite.
Before a persona can become a knite, she must first earn her MND attribute.
A persona can earn the Knite vocation by completing a Knite qualification storyline laid out by the players.
The players will decide if the persona has earned the Knite vocation.
For more detail about knites jump to xref:i-roll_playing_rules:CH08_Vocations_Knite.adoc[knites,window=_blank].

:art: gnome_mech.png
:width: 250px
:snark: Mechanics come in all sizes.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Long eared tiny gnome mechanic wrenching a large nut.

include::ROOT:partial$articulate.adoc[]

Mechanic::
The mechanic dedicates herself to studying the inorganic world.
These studies range from robots to scientific systems.
The player can add INT to her persona's attributes if she randomly chose this vocation. 
The player can add a xref:i-roll_playing_rules:CH08_Vocations_Mechanic.adoc#_mechanic_abilities[mechanic ability,window=_blank] if she randomly chose this vocation. 
Every mechanic gets two xref:i-roll_playing_rules:CH08_Vocations_Mechanic.adoc#_mechanic_skills[mechanic skills,window=_blank].

:art: anthro_human_gi_jane.png
:width: 250px
:snark: GI Jane
:artist: Hotz
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a human woman in combat kit with rifle.

include::ROOT:partial$articulate.adoc[]

Mercenary::
The mercenary works hard to promoting order, or change, via violence.
Mercenaries are not psychotic, violent or cruel.
They are skilled in the art of war and weapons.
The player can add STR to her persona's attributes if she randomly chose this vocation. 
The player can add a xref:i-roll_playing_rules:CH08_Vocations_Mercenary.adoc#_mercenary_abilities[mercenary ability,window=_blank] if she randomly chose this vocation. 
Every mercenary gets two xref:i-roll_playing_rules:CH08_Vocations_Mercenary.adoc#_mercenary_skills[mercenary skills,window=_blank].

:art: nomad_shelter.png

:width: 250px
:snark: Simple shelter.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Scraggly dressed human man taking shelter from sandstorm behind ruins.

include::ROOT:partial$articulate.adoc[]

Nomad::
The nomad prides herself on surviving and integrating into her surrounding world.
These survival skills include all aspects of survival, travel and shelter in all terrains.
The player can add CON to her persona's attributes if she randomly chose this vocation. 
The player can add a xref:i-roll_playing_rules:CH08_Vocations_Nomad.adoc#_nomadic_abilities[nomad ability,window=_blank] if she randomly chose this vocation. 
Every nomad gets twoxref:i-roll_playing_rules:CH08_Vocations_Nomad.adoc#_nomadic_biomes[nomad biomes,window=_blank].

:art: what_am_I.png
:width: 250px
:snark: Am I a rodent, avarian or humanoid?
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Humanoid platypus in lotus position wearing robes.

include::ROOT:partial$articulate.adoc[]

Nothing::
The nothing vocation obsesses with all things mundane.
The mundane includes money, appearance and social standing.
The vast majority of the civilians of mundane terra are nothings.
Nothings have no combat skills and no useful maneuvers.
Nothings lack abilities or skills, but they do have a xref:i-roll_playing_rules:CH08_Vocations_Nothing.adoc#_career[career,window=_blank]and some xref:i-roll_playing_rules:CH08_Vocations_Nothing.adoc#_nothing_wealth[money,window=_blank].

Spie::
The spie is devoted to all things deceptive, sneaky and underhanded.
The realm of the spie includes disguises, sneaking and assassination.
The player can add DEX to her persona's attributes if she randomly chose this vocation. 
The player can add a xref:i-roll_playing_rules:CH08_Vocations_Spie.adoc#_spie_abilities[spie ability,window=_blank] if she randomly chose this vocation. 
Every spie gets two xref:i-roll_playing_rules:CH08_Vocations_Spie.adoc#_spie_tricks[spie tricks,window=_blank].

:art: anatomy_book_surgeon_fixed_desat.png
:width: 250px
:snark: Life long learner
:artist: Studiostoks
:date: 2015
:license: Copyright Studiostoks
:description: Drawing of surgeon reading a book during surgery.

include::ROOT:partial$articulate.adoc[]

Veterinarian::
The veterinarian is devoted to repairing and improving all organic beings.
This practice includes diagnosis, surgery and medications.
The player can add a xref:i-roll_playing_rules:CH08_Vocations_Veterinarian.adoc#_vet_abilities[vet ability,window=_blank] if she randomly chose this vocation. 
Every vet gets two xref:i-roll_playing_rules:CH08_Vocations_Veterinarian.adoc#_vet_skills[vet skills,window=_blank].

== Mundane Skill
Every anthro persona gets one mundane skill rolled on the nothing skill table.
Nothings should end up with two nothing skills.
The table is included here for convenience. 

include::ROOT:partial$CH08_Table_Nothing_Skills.adoc[]

== Anthro Artifacts
Personas get a TOYs roll. 
It is entirely random, and the player only makes one roll. 
The result can range from random junque to starcruiser. 
To generate a toy for the persona jump to xref:iii-hardware:An_index_hardware.adoc#_toy_type[Hardware,window=_blank].

== Anthro Name
The player should name her anthro persona at the end of its creation.
The anthro name is entirely up to the player. 
For more detail than you ever wanted jump to xref:i-roll_playing_rules:CH04_Anthros_Name.adoc[anthro name,window=_blank]

== Anthro Appearance
The player should decant her anthro's description down to its most prominent features.
For example, the player picks the essential defining parts of her anthro: a feline tabby wearing a camo kilt carrying a big rifle.

== Anthro History
Keep track of the fun.
Entirely optional.


