= Persona Creation

Persona generation in Role Playing can be driven by dice or by player choice. 
The Persona Record Sheet is essentially numberless.
There are no attribute scores.
There are no hit points.
There are a limited number of attributes.

.*Steps to Persona Creation*
. Determine Family
.. Anthro, Alien, Robot
. Determine Attribute
.. AWE, CHA, CON, DEX, INT, PSTR
.. Special case MND
.. Size
. Determine Vocation
.. Bio, Vet, Nomad, Spie, Mechanic, Mercenary
.. Special case Nothing
.. Special case Knite
. Determine Skills
. Determine Abilities
. Determine Equipment
. Name persona

== Family
Every persona, from the evilest referee persona to the kindest player persona, has a family.
The three types of families found in EXP are anthros (humans, canines, felines, etc.), robots (janitorial to combot) and aliens (flying carnivorous plants to pulsating blobs).

On mundane terra, scientists sort life using a taxonomy based on genetics.
There are many elements in the taxonomy of life on earth.
EXP ignores all of this in the name of sciency fiction.
EXP divides families phenotypically.
Phenotypically is a long way to say "how something looks."
Phenotypically dividing life forms allows for EXP to have its sciency fiction taxonomy.
EXP uses a shortened taxonomy of Family, Genus and Species.
A more straightforward method is using the common names of anthro, alien, and robot.

.*EXP's Fake Taxonomy*
* *Domain -> Order:* Ignored
* *Family:* 
** Hominidae (Anthro)
** Diversidae (Alien)
** Machinidae (Robot)
* *Genus:*
** Anthro = Homo
** Alien = Determined at evolution
** Robotic = Fabricator Name
* *Species:*
** Anthro = Avis, Aqua, Canis, Felis, et.
** Alien = Determined at evolution
** Robot = Android, Combot, Hobbot, Rescue

Players can choose, randomly determine their persona's family type.
Aliens and robots can be difficult for inexperienced players to use.
Anthro is the recommend persona type for most players.

include::ROOT:partial$CH26_Table_Role_Family.adoc[]