= Role Playing Rules

[quote]
____
*One roll to rule them all, and in the story bind them.*
____

. <<_introduction,Introduction>>
. <<_4d2_mechanic_primer,4D2 Mechanic>>
. <<_combat,Combat>>
. <<_performance,Performance>>
. <<_attribute_rolls,Attribute Rolls>>
. <<_saving_rolls,Saving Rolls>>
. <<_critical_rolls,Critical Rolls>>
. <<_sphincter_rolls,Sphincter Rolls>>
. <<_time,Time>>
. <<_health,Health>>
. <<_skills,Skills>>
. <<_experience,Experience>>
. <<_driving,Driving>>
. <<_encumbrance,Encumbrance>>
. <<_terrain,Terrain>>
. <<_artifact_identification,Artifact Identification>>
. <<_negotiations,Negotiations>>
. <<_money,Money>>
. <<_mundane_equipment,Mundane Equipment>>
. <<_encumbrance,Encumbrance>> 

== Introduction
Role Playing Rules help guide the players to tell a cinematic and compelling story.
The Role Playing System is very qualitative. 
In this case, qualitative indicates words are used instead of numbers. 
The Roll Playing System has a plethora of complicated dice systems. 
The Role Playing System has only one uncomplicated dice mechanic.

Dice are still required to play the Role Playing System. 
The Role Playing System uses a straightforward mechanic that gives descriptive outcomes.

====
The Role Playing System uses the xref:ii-role_playing_rules:CH26_Fourdeetwo.adoc[4D2 Mechanic,window=_blank].
====

The 4D2 Mechanic is a storytelling aid.
The mechanic takes random numbers and generates a description for when decisions arise.
When personas meet in combat, the 4D2 Mechanic can decide the outcome of the battle.
When a persona is attempting to fix an engine, the 4D2 Mechanic can decide the quality of the repair.

The Role Playing System does not use mats or minis.
Almost every quantitative aspect in the Roll Playing System has an equivalent description in the Role Playing System.
The 4D2 Mechanic offers direction, and the players make the best decision for the story.
The players, including the referee, build the story, and that story arch creates a campaign.
The tool and rules described here help generate sub-stories.
These sub-stories are called combat stories or performance stories. 
The sub-stories may be mundane or fantastical. 
The players and the dice decide.

:art: three_plus_one.png
:width: 350px
:snark: Five, three, one?, three. 
:artist: JEShields, HM added one die
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Four white and black six sided dice with third dice's value obscured.

include::ROOT:partial$articulate.adoc[]

== 4D2 Mechanic Primer
4D2 is both a descriptor and a joke. 
The 4 indicates that the mechanic uses 4 dice.
The 4 also indicates that there are 4 steps in the process.
The D refers to dice, and it a play on "D" in the 4d6 convention.
The 2 reflects that the mechanic has two directions.
The joke is that 4D2 sounds like 42.
Fourty-two is the answer to the wrong question.
The 4D2 Mechanic gives the answers to questions you can't understand.

The 4D2 Mechanic uses four six-sided dice to guide the story in the Role Playing System.
The 4D2 Mechanic is a bespoke decision tool for EXP's Role Playing System.
If you are familiar with the Roll Playing System of EXP, the 4D2 replaces Attack Rolls, Task Rolls, Attribute Rolls, Saving Rolls, Sphincter Rolls and more.

.*Four steps of the 4D2 Mechanic*
. Player rolls dice to get a  *Number*
. That  *Number* yields an *Outcome*
. The   *Outcome* produces a *Descriptor*
.. The *Descriptor* comes from the players or a table.
. The *Story* is influenced by the *Descriptor*

WARNING: Do not proceed with this section until mastering an understanding of the xref:ii-role_playing_rules:CH26_Fourdeetwo.adoc[4D2 Mechanic,window=_blank].

== Combat
Combat in the Role Playing System employs the 4D2 Mechanic to guide the combat story.
The 4D2 Mechanic evolved from a legacy mechanic called the Theatrical Combat System.
The name has stuck for sentimental and legacy reasons.
The Theatrical Combat System guides combat stories so that players can make the most fun choices.

====
For a detailed description of combat jump to xref:ii-role_playing_rules:CH26_Theatrical_Combat.adoc[Theatrical Combat System,window=_blank].
====

== Tasks
Tasks in EXP evolved from a collection of vocation-specific performance tables.
So there may be references to "theatrical performance" which has been replaced by tasks.
The theatrical combat system (another legacy term) came with the simplified theatrical performance system. 
Needless to say theatrical performance lead to confusion.
Theatrical performance is a fun part of role playing games.
However there is no system for that in EXP, and theatrical performance system has stuck around for sentimental and legacy reasons.
Please use task rolls when testing abilities, actions, maneuvers of personas.


====
For a detailed description of Tasks jump to xref:ii-role_playing_rules:CH26_Theatrical_Performance.adoc[Theatrical Tasks,window=_blank].
====

== Attribute Rolls
A player makes an attribute roll for her persona when a maneuver challenges a specific attribute.
For example, the persona must catch a falling vase, or the persona must arm-wrestle another persona.
Attribute rolls should not decide the outcome of mundane actions. 
Personas should be able to walk down a flight of stairs safely.
Attribute rolls should never decide life or death situations for personas.

Attributes in the Role Playing System do not have scores, and the persona only records her most excellent attributes.
How does one compare attributes if they do not have scores like Dexterity 16 or Strength 9?

The players decide which attribute is most important for the challenge.
If the persona is trying to catch a vase, the player needs to make an attribute roll using Dexterity.
If the persona has no Dexterity attribute but makes a dramatic description of the diving catch, she would get a shift of +1.
If the persona has Dexterity and makes a dramatic description of the diving catch, she would get a shift of +2.
The number gives an outcome, and that directs what happens to the __vase__.

If two personas are having an arm wrestle, the players may decide that both Dexterity and Strength make up the attribute roll.
The player persona has Dexterity and Strength attributes.
The referee persona has only a Strength attribute. 
The Strength attributes cancel each other out, and the player gets a +1 shift for her Dexterity attribute.

If personas are player personas, it is up to the players to decide which player makes the 4D2 roll.

For more info about shifts jump to xref:ii-role_playing_rules:CH26_Fourdeetwo.adoc#_shifts[Shifts,window=_blank].

== Saving Rolls
Saving rolls are attribute rolls where the persona may or may not come to harm from the result.
The element of risk for the persona is the difference between an attribute roll and a saving roll.
The player makes saving rolls for her persona when facing toxic attacks like poison, radiation, or mind control. 
The type of attack determines which attribute she can use for her shift. 

=== Poison
Poison attacks can be from alien venoms, dastardly drinks, or bad cooking.
Most often, the player will be hoping her persona has a Constitution attribute.
Constitution is the most common shift the player can use against poison.
It is unlikely that the player will be able to earn a shift for a vigorous description.

The player makes a 4D2 roll with the appropriate shifts to determine how severely the poison affects her persona.
If the number is positive, then the persona is unaffected by the poison.
If the number is negative, then the persona is affected by the poison.
The outcome guides the players to decide what happens to the persona.
A cataclysmic failure could indicate the worst possible effect that the poison could have. 
A sleeping poison would cause deep sleep. 
A lethal poison may be fatal.
A truth serum may lead to an embarrassing confession.
In some cases, the referee may prepare a description table for a poison. 

Some poisons are more dangerous than others.
The intensity of the poison reflects that danger.
Poison intensity is very important in the Roll Playing system. 
The referee can build the intensity into a bespoke description table.
The referee can have the poison absorb the player's shifts.

=== Radiation
Radiation in EXP is fantasy radiation that has immediate effects on the persona.
Radiation operates the same as any other toxin using the 4D2 mechanic and a Constitution attribute offering a shift.
There is one exception with radiation. 
If the player rolls a natural +10, her persona can gain a mutation.
If the player rolls a natural -10, and her persona survives, she can gain a defective mutation. 

=== Mental attacks
Psionic invasions, ESP probes, and other fun mind control attacks operate the same as any other toxin.
The player makes the usual 4D2 roll and can use the attribute Mind as a shift. 

== Critical Checks
Critical checks are uncommon extreme rolls that evoke statistical excitement.
Such extreme rolls have synonyms like critical hit, critical save, and automatic success.

The 4D2 Mechanic has two critical results. 
The positive critical result is called Immaculate Success.
The negative critical result is called Cataclysmic Failure.
These are extreme results and have critical impacts on the personas.
The nature of the impact depends on the situation and how the players describe the result.

Positive critical results can earn the persona a new skill or an unexpected bonus.
Negative critical results can result in broken equipment or permanent injury to the persona.

== Sphincter Rolls
Sphincter Rolls help the players make inexplicable decisions.
For example, is that crucial airlock bolt in stock or not?
Does the peanut butter sandwich land the wrong side down in the sand?
The 4D2 Mechanic replaces the Sphincter Rolls.
The descriptor determines the outcome for the expedition.
Success indicates a decision in the expedition's favour. 
Failure indicates an unfavourable decision for the expedition.

== Time
Time is entirely arbitrary in the Role Playing System.
There are no units, melees or turns. 
Time passes as needed to tell the best story.
Below is an entirely unnecessary timetable.

include::ROOT:partial$CH12_Table_Time_Components.adoc[]

== Health
There are no hit points or ageing in the Role Playing System. 
A 4D2 roll guides the outcomes of health concerns. 
If ageing suddenly becomes significant, the player can check to see how that year went. 
In the case of ageing, a cataclysmic failure may result in a life-threatening event.

== Experience
Skills acquisition replaces the entire EXPS and EXPS Level system.
Personas learn new skills when they roll Immaculate or Wondrous successes on the 4D2 roll.

== Driving
Personas can only drive vehicles if they have a driving skill.
In general, personas can drive their vehicles where ever they want without incident.
The 4D2 Mechanic is employed to determine the outcome of driving shenanigans.
The persona may enjoy shifts for Dexterity, driving skills, and vehicle handling class.

== Terrain
The terrain is about description, ambiance and milieu. 
If the referee wishes a dense fog to affect the expedition, she can limit weapon range or absorb one of the persona's shifts.

== Artifact Identification
The 4D2 Mechanic replaces the entire artifact identification system.
Success indicates the identification of the artifact.
Immaculate Success may indicate a new skill regarding the artifact 
Failure means the artifact remains unidentified.
Cataclysmic Failure may indicate artifact damage or accidental activation. 

== Negotiations
Players can only use roleplay to resolve negotiations in the Role Playing System.
Robots and anthros always have language skills.
Flora or fauna may attack the expedition due to hunger, territory, or fun. 
Whether they attack can be determined with the ubiquitous 4D2 Mechanic.

== Money
Who cares.
Personas should be cinematically and theatrically saving the universe. 
Sheesh.

== Mundane Equipment
What equipment is available to personas is entirely decided by the milieu of the game.
A leather and dust pre-apocalyptic scavenger game may have no equipment.
A suburban post-apocalyptic retro big box store game may have all equipment.

== Encumbrance
Who cares.
Personas should be cinematically and theatrically saving the universe. 
Sheesh.
Abusers of this generous position on encumbrance should find their shifts disappearing under the wate. 


