dictionaries = ["en_gb"]

words = [
  "Antora",
  "AntoraDocs",
  "AsciiDoc",
  "EXP",
  "exatmo",
  "Flotto",
  "hite",
  "inatmo",
  "Kirlian",
  "Knite",
  "lazer",
  "maneuver",
  "Sciency",
  "Sotto",
  "spie",
  "UnCombat",
  "wate",
  "zog",
]
