// formats an anthro RP with attributes from the file that calls it
:table-stripes: none

[width="100%",cols="<1,<3", frame="none", grid="none", stripes="none"]
|===
.2+|image:pre_rolls:{image_file}[width="150px", alt='{image_description}', title='Artist: {image_artist} Date: {image_date} License: CC BY-SA 4.0']
|{description}

|{image_description}

|===

== Attributes

[width="100%",cols="9*^",frame="none", grid="none", stripes="none"]
|===

|AWE
|CHA
|CON
|DEX
|INT
|MND
|STR
|SOC
|HPM

|__{awe}__
|__{cha}__
|__{con}__
|__{dex}__
|__{int}__
|__{mnd}__
|__{str}__
|__{soc}__
|__{hpm}__

|~awareness~
|charisma
|constitution
|dexterity
|~intelligence~
|mind
|strength
|privilege
|~toughness~

|===

== Combat

// this should be an include
[width="90%",cols="3,3,3,3,3,3,4,5",frame="none", grid="none" stripes="none"]
|===

5+s|ATTACK TABLE
s|DEF
s|MOVE
|*HPS:* {hpm} 

<|Type
<|Skilled
<|Raw
<|Max
|Force
|{def}
|{move_land} h/u land
.4+|

|Strike
<|{strike_skill}
<|{strike_raw}
<|{strike_max}
<|{strike_force}
|
|{move_air} h/u air

|Fling
<|{fling_skill}
<|{fling_raw}
<|{fling_max}
<|{fling_force}
|
|{move_water} h/u water

|Shoot
<|{shoot_skill}
<|{shoot_raw}
<|{shoot_max}
<|{shoot_force}
|
|


8+<|~*Strike*: self powered melee, *Fling*: self powered ranged, *Shoot*: powered attacks~
8+<|*Skilled*: add to skilled attack rolls, *Raw*: add to unskilled attack roll, *Max*: maximum attack roll, *Force*: add to damage roll
8+<|*DEF*: defence, *Move*: hexes per unit *HPS*:hit points total

|===

== Tasks 

[width="90%",cols="1,1,1,1,1",frame="none", grid="none" stripes="none"]
|===

2+|*Vocation:* {vocation}
|*Level:* {level} 
2+|*EXPS:* {exps}

s|Gifts
s|Interests
3+s|Skills

|{gift_1}
|{interest_1}
|{skill_1}
|{skill_4}
|{skill_5}

|{gift_2}
|{interest_2}
|{skill_2}
|{skill_6}
|{skill_7}

|{gift_3}
|{interest_3}
|{skill_3}
|(skill_8)
|{skill_9}

5+<|~*Vocation*: what the persons does. *Level*: how experienced the persona is~

5+<|*Gifts*: natural actions. *Interests*: broad Knowledge (+1), *Skills*: specific knowledge, ability (+2)

|===



== Biology

[width="100%",cols="1,1,1,1,1,1",frame="none", grid="none" stripes="none"]
|===

2+<|*Family:* {family}
2+<|*Genus:* {genus}
2+<|*Species:* {species}

2+<|*Age:* {age} {age_suffix}
2+<|*Hite:* {hite} {hite_suffix}
2+<|*Wate:* {wate} {wate_suffix}

6+<s|MUTATIONS: {mutations}



|===


== RP Fun
{description}

{persona name} is from {rp_fun_arc_origin}. They are {rp_fun_arc_origin}, and {rp_fun_arc_future}.
Their {appearance_hygiene} {appearance_dress} clothing choice smell like {appearance_smell}.
Their sound is: {laban_sound}. Their move is {laban_move}.

Religion: {belief_religion} Philosophy: {belief_philosophy} Politics: {belief_politics}

== Equipment

[width="100%",cols="4*<", frame="none", grid ="none",  stripes="none"]
|===

4+|Wate Allowance

s|WA: {wa}
s|SPRINT: {eval: {wa}/4}
s|CARRY: {eval: {wa}*1.5}
s|LIFT: {eval: {wa}*2.5}

4+|*WA*: STR wate allowance, *Sprint*: WA/4 *Carry*:WA*1.5, *Lift*: WA*2.5

4+<|special toy here
4+<|special toy here hopefully living includes
4+<|special toy here

|===



== PDF
Download an approximate pdf for this persona. xref:pre_rolls:attachment${pdf_file}.pdf[{persona_name} PDF]

== JSON
The below json will work with the https://github.com/mobilehugh/EXP_Game_Tools[EXP Python Tools]

[source, json]
----
{json_file}
----

