// anthro RP format


// INTRODUCTION and IMAGE

include::pre_rolls:partial$format_intro_and_image.adoc[]


// ATTRIBUTES

== Attributes

[width="100%",cols="9*^",frame="none", grid="none", stripes="none"]
|===

|AWE
|CHA
|CON
|DEX
|INT
|MND
|STR
|SOC
|HPM

|__{awe}__
|__{cha}__
|__{con}__
|__{dex}__
|__{int}__
|__{mnd}__
|__{str}__
|__{soc}__
|__{hpm}__

|~awareness~
|~charisma~
|~constitution~
|~dexterity~
|~intelligence~
|~mind~
|~strength~
|~privilege~
|~toughness~

|===



// COMBAT INFO

== Combat

// this should be an include
[width="80%",cols="5*<",frame="none", grid="none" stripes="none"]
|===

s|DEFENCE
s|MOVE
s|HPS
|
|

|__{def}__
|__{move_land}__ __h/u__
|__{hpm} __
|
|

5+<s|ATTACK TABLE

<s|Type
s|Skilled
s|Raw
s|Max
s|Force

<s|Strike
|__{strike_skill}__
|__{strike_raw}__
|__{strike_max}__
|__{strike_force}__

<s|Fling
|__{fling_skill}__
|__{fling_raw}__
|__{fling_max}__
|__{fling_force}__

<s|Shoot
|__{shoot_skill}__
|__{shoot_raw}__
|__{shoot_max}__
|__{shoot_force}__

5+<|[.small]#*DEFENCE*: how hard to hit, *Move*: hexes per unit *HPS*:hit points total# +
[.small]#*Strike*: self powered melee, *Fling*: self powered ranged *Shoot*: powered attacks# +
[.small]#*Skilled*: add to skilled attack rolls, *Raw*: add to unskilled attack roll# +
[.small]#*Max*: maximum attack roll, *Force*: add to damage roll# +

|===


// TASK INFO

== Tasks 

[width="90%",cols="1,1,1,1,1",frame="none", grid="none" stripes="none"]
|===

2+|*Vocation:* {vocation}
|*Level:* {level} 
2+|*EXPS:* {exps}

s|{gift_title}
s|Interests
3+s|Skills

|{gift_1}
|{interest_1}
|{skill_1}
|{skill_4}
|{skill_7}

|{gift_2}
|{interest_2}
|{skill_2}
|{skill_5}
|{skill_8}

|{gift_3}
|{interest_3}
|{skill_3}
|{skill_6}
|{skill_9}

5+<|[.small]#*Vocation*: what the persons does. *Level*: how good they are. *EXPS*: total experience# +
[.small]#*{gift_title}*: natural actions. *Interests*: broad Knowledge (+1), *Skills*: specific knowledge, ability (+2)#

|===

// BIOLOGY INFO

== Biology

[width="100%",cols="1,1,1,1,1,1",frame="none", grid="none" stripes="none"]
|===

2+<|*Family:* {family}
2+<|*Genus:* {genus}
2+<|*Species:* {species}

2+<|*Age:* {age} {age_suffix}
2+<|*Hite:* {hite} {hite_suffix}
2+<|*Wate:* {wate} {wate_suffix}

|===


include::pre_rolls:partial$format_mutations.adoc[]



anthro_humanoid_biologist_1990_0805_1442_0042.adoc


// RP FUN

== RP Fun
{description}. {persona_name} is from {rp_fun_arc_origin}. They are {rp_fun_arc_present}, and want to {rp_fun_arc_future}.
Their {appearance_hygiene} {appearance_dress} dress smells like {appearance_smell}.
// religious belief
ifeval::["{belief_religion}" == "None"]
They have no religion. 
endif::[]
ifeval::["{belief_religion}" != "None"]
They follow a religion of {belief_religion}.
endif::[]
// philosophical belief
ifeval::["{belief_philosophy}" == "None"]
They have no philosophy. 
endif::[]
ifeval::["{belief_philosophy}" != "None"]
Their life philosophy is {belief_philosophy}.
endif::[]
ifeval::["{belief_politics}" == "None"]
They have no politics. 
endif::[]
ifeval::["{belief_politics}" != "None"]
Their politics are {belief_politics}.
endif::[]
{persona_name} has a {personality} personality. 

VOICE: {laban_sound}. MOVE: {laban_move}.


// EQUIPMENT

include::pre_rolls:partial$format_equipment_list.adoc[]


== PDF

ifeval::["{pdf_file}" == ""]
This persona record does not have a PDF. 
endif::[]

ifeval::["{pdf_file}" != ""]
Download an approximate pdf for this persona. xref:pre_rolls:attachment${pdf_file}[{persona_name} PDF]
endif::[]


== JSON

:dashes: ----

ifeval::["{json_file}" == ""]
This persona record does not have a JSON file. 
endif::[]


ifeval::["{json_file}" != ""]
The below json will work with the https://github.com/mobilehugh/EXP_Game_Tools[EXP Python Tools]

{dashes}

{json_file}

endif::[]



