= Persona Creation

IMPORTANT: *Welcome friend of EXP. You are in an live updating section of EXP. Please use caution.*

Persona generation in Role Playing can be driven by dice or by player choice. 
The Persona Record Sheet is essentially numberless.
There are no attribute scores.
There are no hit points.
There are is a limited number of attributes.
Requires the main persona creation tables and info.
All dice are recommended.

.*Steps to Persona Creation*
. Determine Family
.. Anthro, Alien, Robot
. Determine Attribute
.. AWE, CHA, CON, DEX, INT, PSTR
.. Special case MSTR
.. Size
. Determine Vocation
.. Bio, Vet, Nomad, Spie, Mechanic, Mercenary
.. Special case Nothing
.. Special case Knite
. Determine Skills
. Determine Abilities
. Determine Equipment
. Name persona

== Family
Every persona, from the evilest referee persona to the kindest player persona, has a family.
The three types of families found in EXP are anthros (humans, canines, felines, etc.), robots (janitorial to combot) and aliens (flying carnivorous plants to pulsating blobs).

On earth all life is sorted by a taxonomy based on genetics.
There are many elements in the taxonomy of life on earth.
EXP ignores all of this in the name of science fantasy.
Families in EXP are divided phenotypically.
Phenotypically is a long way to say "how something looks."
Since life in EXP is divided by appearance and not genetics we have our own taxonomy.
Families are organized in EXP  Family, Genus and Species.
This keeps it simple.
Even simpler is dividing the families into their common names: anthro, alien, and robot.

.*EXP's Fake Taxonomy*
* *Domain -> Order:* Ignored
* *Family:* 
** Hominidae (Anthro)
** Machinae (Robot)
** Diversidae (Alien)
* *Genus:*
** Anthro = Homo
** Alien = Determined at generation
** Robotic = Fabricator Name
* *Species:*
** Anthro = Avis, Aqua, Canis, Felis, et.
** Alien = Determined at generation
** Robot = Android, Combot, Hobbot, Rescue
Use the data from Roll playing with out the burden

Player can choose their Family type and record it on their persona record.
The player can also roll their Family type if they choose.

include::ROOT:partial$CH26_Table_Role_Family.adoc[]

// RP = PP

// players are players

== Attributes 
how they work







