= Role Playing Rules

[quote]
____
*One roll to rule them all, and in the story bind them.*
____

IMPORTANT: *Welcome friend of EXP. You are in an unfinished section of EXP. Please ignore.*

. Introduction
. Combat
. Performance
. Time
. Health
. Skills
. Experience
. Driving
. Encumbrance
. Terrain
. Artifact Identification
. Negotiations
. Money
. Mundane Equipment
. Example usages

== Introduction
4D2 Mechanic as a story telling aid.
all players.
no referee.
one die one roll one story.
one roll to rule them all and in the story bind them.
no minis or mats.

stories and sub stories.
story is the campaign, persona story
sub stories are combat stories and performance stories


== Combat
Combat in the Role Playing System employs the 4D2 Mechanic to guide the combat story.
The 4D2 Mechanic evolved from a legacy mechanic called the Theatrical Combat System.
The name has stuck for sentimental and legacy reasons.
The Theatrical Combat System guides combat stories so that players can make the most fun choices.

Theatrical Combat has it's xref::CH26_Theatrical_Combat.adoc[own section].

== Performance
Everything is an maneuver in EXP.
In this context a maneuver is any persona action that has an unclear outcome.
The __unclear__ part of the outcome is determined by randomness.
Players can guide the randomness by using skills, and attempting maneuvers in their wheelhouse.

Theatrical Performance has it's xref::CH26_Theatrical_Performance.adoc[own section].

== Health

== Skills

== Experience

== Driving

== Encumbrance

== Terrain

== Artifact Identification

== Negotiations

== Money

== Mundane Equipment