= Alien Creation

Alien is the colloquial term for the family diversidae.
Aliens encompass any organic living creature that has consciousness.
Aliens are evolved, represent species, and are generated randomly. 

include::ROOT:partial$CH26_Table_Record_Alien.adoc[]

.*Alien Evolution*
. <<_alien_attributes,Attributes>>
. <<_alien_appearance,Appearance>>
. <<_alien_mutations,Mutations>>
. <<_alien_abilities,Abilities>>
. <<_alien_vocation,Vocations>>
. <<_alien_skills,Skills>>
. <<_alien_artifacts,Artifacts>>
. <<_alien_name,Name>>
. <<_alien_appearance,Appearance>>
. <<_alien_history,History>>

== Alien Attributes
The standard attributes of EXP are present in all personas.
In the Role Playing System personas only record those attributes at which the persona excels.
A persona could have a blank attributes section and function fine.
Another persona may have the attribute intelligence. 
This indicates that the persona's INT is an attribute she excels at.
It is possible for a persona to excel at more than one attribute.
For example, INT and DEX.

There is no score assigned to an attribute. 
If the persona excels at an attribute they benefit when that attribute is being used.
For example, a persona physical strength would have better results than a persona with INT when lifting.
If two personas grappling both had physical strength then there would be no advantage given.
However if a persona with PSTR and DEX is grappling a persona with just PSTR they get a DEX advantage.

These advantages are called shifts and are added to the result from the 4D2 Mechanism.
The attribute of Mental Strength is present but not available to the persona at creation.
There are no Hit Points, Social Standing or EXPS or EXPS Levels.

The player does not generate numbers for their list of attributes.
The persona starts with one attribute that she excels in.
This can be randomly generated or chosen by the player. 

include::ROOT:partial$CH26_Table_Attribute.adoc[]

Size::
Aliens can have variable sizes. 
Size can be used as an advantage if two personas have PSTR.
The personas with the larger size and PSTR will gain advantage over the smaller persona with PSTR.

include::ROOT:partial$CH06_Table_Alien_Size.adoc[]

Awareness::
Awareness indicates how aware a persona is of her surroundings. 
It indicates how well is the persona’s brain is connected to the outside world. 
The attribute is a collective measure of the persona’s sensors. 
AWE includes senses like hearing, vision, smell, touch and taste. 
Awareness does not include the sixth sense, or a sense of style. 
The abbreviation for awareness is AWE.

Charisma::
Charisma is charm, looks and sociability all combined into one value. 
A high charisma represents a high proficiency at getting along with other personas. 
This attribute is a universal so any persona with a high CHA would be socially adept. 
A persona’s charisma is very important for inter-persona interactions.
The abbreviation for charisma is CHA.

Constitution::
Constitution represents a persona’s internal physique.
CON is a combination of wellness, immunity, energy extraction, healing ability.
A high CON is better to repel disease, resist poisons, and repair damaged tissue.
The abbreviation for constitution is CON.

Dexterity::
Dexterity represents the connection between the brain and outside world.
Agility, balance, eye-hand, reflexes and running speed are components of dexterity.
A high DEX person could run faster, dance better and quicker reflexes.
Dexterity would help the persona catch a priceless vase or dive through a closing door.
The abbreviation for dexterity is DEX.

Intelligence::
Intelligence indicates the smarts of the persona.
Elements of INT are memory, deduction, creativity, adaptability and their synergism. 
The higher the intelligence of the persona the smarter she is.
The abbreviation for intelligence is INT.

Mental Strength::
Mental Strength exists as an attribute.
MSTR must be acquired through a story set out by the players.
If the referee would like a band of knites off on damn fool missions then every persona gets MSTR.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

The MSTR attribute can be earned by completing an MSTR testing story line laid out by the players.
Also MSTR can be assigned by suffering and surviving a mortal wound in combat.
The players will decide if the MSTR attribute has been earned by the persona.
The abbreviation for mental strength is MSTR.

Physical Strength::
Physical Strength represents force the persona can generate to get work done. 
PSTR is a combination of leverage, power and physique. 
Physical Strength determines how much the persona can lift or damage by brute force. 
PSTR helps kicking open doors, breaking bonds, or crushing beer bottles.
The abbreviation for physical strength is PSTR.

Hit Points::
There are no hit points Max or hit points Total.
Combat and damage is both absolute and descriptive. 
There is no quantitative measure of well being like 32 HPS Total out of 42 HPS Max.
Personas are damaged in combat by losing attributes, skills and abilities instead of HPS.
When the 4D2 Mechanic generates a Cataclysmic Failure the persona can lose an attribute, skill or ability.
Extreme failures on the 4D2 Mechanic can mortally wound or kill the persona as well.
The abbreviation for hit points is HPS.

Social Standing::
There is no Social Standing.
All elements of social interaction are expected to be role-played in this system.
The abbreviation for social standing is SS.

EXPS and Level::
There are no Experience Points or Experience levels. 
Personas are awarded additional attributes, skills and abilities instead of experience points or levels.
The 4D2 Mechanic can generate new attributes, skills or abilities.
This process replaces experience points and experience levels.
The abbreviation for experience points is EXPS.

== Alien Appearance
Aliens are incredibly diverse.
Hence their family name diversidae.
Alien appearance is generated by generating four components and mashing them together.

=== Head Part
The alien's head part _usually_ stores the alien's brain and sensors.
The head is _usually_ located at the front of the alien.
Record the movement letters (l,a,w,s) associated with the head part.
An optional head adornment may be added later

=== Torso Part
The alien's torso part _usually_ stores the alien's vital organs.
The part does not indicate the types of vital organs but they are most likely in the torso.
Record the movement letters (l,a,w,s) associated with the torso part.
An optional torso adornment may be added later

=== Arms Part
The alien's arms part _usually_ indicates the persona front limbs and articulators.
The arms part does not has no effect on whether the alien is a tool user or not.
Record the movement letters (l,a,w,s) associated with the arms part.
An optional grabby adornments may be added later.

=== Legs
The legs part _usually_ indicates the main way the alien gets around.
Record the movement letters (l,a,w,s) associated with the legs part.
Legs part does not solely determine alien locomotion.
If an alien can fly and run it will have the parts for both. 
Often an alien's legs will not be legs at all but flukes, flippers, bulbs and blobs.
If the alien has snake's legs, it slithers about.
If the alien has fish legs, it may wiggle or fin itself about.
If the alien has parrot arms and fish legs it can still fly and slither.

include::ROOT:partial$CH06_Table_Alien_Body_Parts.adoc[]

=== Appearance and Movement
The alien appearance also determines what kind of terrain she can move through.
Some aliens will be able to fly or swim. 
There is a bracketed lowercase letter following each alien body part description. 
For example, Crab (lw) or Moth (a).
These bracketed letters help determine movement types of the alien.

.*Movement as Abilities*
. l - land borne can move on land
. a - air borne alien gets a flying ability
. w - water borne aliens gets a swimming ability

Mundane Terran phrases like air, water and land have been chosen to describe alien movement.
Aquatic (w) indicates liquid.
Aquatic could be water or liquid ammonia.
Air (a) indicates gaseous.
Airborne could be air or carbon dioxide.
Land (l) indicates solid ground.
Sessile (s) is ignored

The three movement categories can be stacked. 
Land 3 would have an advantage over Land 2 and would enjoy a shift in a race.
Air 2 would fly faster than Air 1 and would enjoy a shift in air combat.

== Alien Mutations
Alien mutations are natural abilities that the alien has evolved over time or in a vat.
Alien mutations can only be beneficial or useless. 
An alien will not evolve themselves a defect.

.*Mutate Now. Like Darwin said.*
* CON attribute personas are assigned one non-defective Physical Mutation.
* INT attribute personas are assigned one non-defective Mental Mutation.

The player heads to the designated mutation section and generates a random mutation.
If the players are diligent the player may be allowed to choose a mutation.
Keep in mind that some mutations are incredibly powerful and they are not designed to be 'picked.'

IMPORTANT: *Welcome friend of EXP. Mutations are unfinished in V6.0 of EXP.*

xref:vi-wetware:An_index_wetware.adoc[Mutations live here. Mutations are under mutation and evolution.]

== Alien Abilities
Alien abilities are natural skills that their species evolved in some primordial state.
Mutations are the obvious alien abilities. 
Movement types are also recorded as abilities. 
An alien may also have some natural abilities that are part of her species.

Natural abilities evolved here are considered not compatible with a vocation.
Primal abilities like multiple attacks, and ranged attacks can only be used by natural alien.
A natural alien is similar to the anthro nothing vocation.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

=== Alien Attack Frequency
An alien with multiple attacks enjoy the spectacular advantage of multiple rolls on the 4D2 mechanic in combat. 
Attack frequency applies only to the natural attack type.
Attack frequency cannot be applied to any artifact weapon or device.
Only her natural attacks can be used for multiple attacks. 

include::ROOT:partial$CH06_Table_Number_of_Alien_Attacks.adoc[]

=== Alien Attack Type
The alien attack types parallel the three weapon types found in EXP.
These non-powered contact (A), non-powered ranged (B), and powered (type C).
For naturalized alien attacks the weapon types are referred to as attack types. 

=== Attack Type A
Type A attacks are thrusting, striking attacks powered by the alien's brawn.
These could be bites, punches, stabs, squishes, slashes, pecks, or scratches.
Type A attacks are in close combat tentacle to tentacle attacks.
The vast majority of aliens employ type A attacks.

=== Attack Type B
Type B attacks are ranged attacks powered by the alien's brawn.
These could be acidic spittle, flying quills, ejected spines or darts.
Type B attacks have a range and are shot like an arrow.
While not a long range attack close combat is not required.
The range of the alien's type B attack is 1 hex per PSTR.

=== Attack Type C
Type C attacks are the rarest and most alien naturalized attack types.
The alien has evolved a self propelled powered attack that it controls.
These are attacks like lazer eyes, or rapid fire bone bullets.
Type C attacks appear naturalized but function like a weapon from the Gun Section.
The attack is modelled after the weapon having the same damage, range and rate of fire.

include::ROOT:partial$CH06_Table_Alien_Attack_Type.adoc[]

=== Alien Tool Ability
The player may choose her personas tool use ability or randomly determine it.
A persona that has randomly chosen tool usage may be able to combine her natural abilities with a vocation.
Tool using ability is recorded on the persona record sheet under abilities. 

include::ROOT:partial$CH26_Table_Gen_Alien_Tools.adoc[]

== Alien Vocation
Aliens may follow a vocation regardless of their tool using ability.

A vocation is a calling or innate skill set possessed by the persona.
If the referee's milieu indicates a vocation could mean training at a school, institute or guild.
The player may choose from any of the listed vocations or choose one randomly.
Allowing the dice to choose the persona's vocation allows for attributes and abilities to be awarded.
For example, choosing vet does not allow the persona to add CHA or choose one ability.
A randomly chosen spie would get the DEX attribute and be able to choose one ability.

include::ROOT:partial$CH26_Table_Role_Vocations.adoc[]

=== Natural Pathways
The interaction between the alien's natural abilities can get complicated.
If the player chooses a nothing vocation she can follow a natural pathway.
The natural pathway allows the persona to use her natural alien abilities unhindered.
This also keeps the persona from using the abilities from her vocation.
Vocation abilities cannot be used in conjunction with natural alien abilities.

Following a vocation may preclude an alien persona's ability to use her natural abilities.
A player whose alien is naturally powerful may not want to lose these abilities.
If the alien persona follows a vocation they cannot use their natural alien abilities.
This is open to negotiation between the players.
The discussion should be based on what is better for the story than what is better for the persona.

=== Vocation Attributes
If the player generates her vocation randomly she is awarded an attribute.
Each vocation is associated with an attribute.
So if the player rolls a mercenary she get's the attribute PSTR added to her attribute list. 
If the player wishes to choose her vocation type for style and story attributes are not granted.
This is an effort to promote diversity of vocations.

=== Vocation Abilities
Many vocations are associated with baked in abilities.
Abilities are not skills.
Any persona can acquire a skill.
Abilities are baked into the persona.
A persona cannot learn the vet Quick Fix ability. 
If the player generates her vocation randomly she can choose one vocation ability.

Aliens that have retained their natural abilities cannot add a vocation ability.
Players that chose their vocation type for style and story cannot acquire vocation abilities

Biologist::
The biologist is dedicated to studying the organic world.
This ranges from it's denizens to it's cultures.
The player may add AWE to her persona's attributes if her vocation is randomly chosen.
Biologists have no abilities, but they do have skills. 

Knite::
The knite is dedicated to the promoting order, or chaos, by connecting the Physical and Think Spaces. 
A player cannot choose or randomly generate the vocation knite.
Before a persona can become a knite she must first earn her MSTR attribute.
The Knite vocation can be earned by completing an Knite qualification story line laid out by the players.
The players will decide if the Knite vocation has been earned by the persona.
If a player's persona becomes a knite she can choose one ability from the extensive list.

Mechanic::
The mechanic is dedicated to studying the inorganic world.
This ranges from it's robots to it's scientific systems.
The player may add INT to her persona's attributes if her persona is randomly chosen.

Mechanics have abilities and skills.
Every mechanic gets one mechanic skill.
A mechanic can choose one ability if her vocation is randomly chosen.
xref:i-persona_creation:CH08_Vocations_Mechanic.adoc#_mechanic_abilities[Mechanic abilities,window=_blank] include: mnemonic trapping, brainstorming and mental patenting.

Mercenary::
The mercenary is dedicated to promoting order, or change, via violence.
Mercenaries are not psychotic, violent or cruel.
They are skilled in the art of war and weapons.
The player may add PSTR to her persona's attributes if her persona was randomly chosen.

Every mercenary gets one mercenary skill.
A mercenary can choose one ability if her vocation is randomly chosen.
xref:i-persona_creation:CH08_Vocations_Mercenary.adoc#_mercenary_abilities[Mercenary abilities,window=_blank] include: Bolster AR, Ambidextrous combat, Snap reload, Proficiency.

Nomad::
The nomad is dedicated to surviving and integrating into her surrounding world.
This includes all aspects of survival, travel and shelter in all terrains.
The player may add CON to her persona's attributes if her vocation is randomly generated.

Every nomad gets one nomad skill.
A nomad can choose one ability if her vocation is randomly chosen.
xref:i-persona_creation:CH08_Vocations_Nomad.adoc#_nomadic_abilities[Nomad abilities,window=_blank] include: Find Water, Find Shelter, Find Food, Make Fire, Safe Passage, Cure Poison, Husbandry, Tracking plus more.

Nothing::
For aliens the nothing vocation be a naturalized alien or the standard nothing vocation.
An alien can choose to be naturalized if her Tool Usage ability is none.
Higher level tool using abilities follow the vocation of nothing.

The nothing is dedicated to all things mundane.
This includes money, appearance and social standing.
Nothings have no combat skills and no useful maneuvers.
The skills and abilities listed here are for voluntary nothings.
This vocation is a choice made by the player at persona creation.
This section does not apply to forced nothings who have arrived at the vocation by tragedy and injury.

Every voluntary nothing gets at least one nothing skill.
Most enjoy and extra skill is the skill section below.
The equivalent of nothing ability is money.
The voluntary nothing gets one serving of xref:i-persona_creation:CH08_Vocations_Nothing.adoc#_nothing_wealth[Nothing Treasure,window=_blank] as an ability.

Spie::
The spie is devoted to all things deceptive, sneaky and fabricated.
This includes disguises, sneaking and assassination.
The player may add DEX to her persona's attributes if this vocation is randomly chosen.

Every spie gets one spie skill.
A spie can choose one ability if her vocation is randomly chosen.
xref:i-persona_creation:CH08_Vocations_Spie.adoc#_spie_abilities[Spie abilities,window=_blank] include: assassinate, disguise or martial arts.

Veterinarian::
The veterinarian is devoted to repairing and improving all organic beings.
This includes diagnosis, surgery and medications.
The player may add CHA to her persona's attributes if this vocation is randomly chosen. 

Every veterinarian gets one veterinarian skill.
A veterinarian can choose one ability if her vocation is randomly chosen.
xref:i-persona_creation:CH08_Vocations_Veterinarian.adoc#_vet_abilities[Vet abilities,window=_blank] include: quick fix, subliminal suggestion, paralyzing pinch, and death pinch.

== Alien Skills
Skills are learned aptitudes that are not baked into the persona like an ability.
A mutation, or anthro type ability, are not skills.
A persona could master the skill knife throwing but she could not master photosynthesis.
Skills can be lost due to cataclysmic failures. 

If the persona has a vocation the player can roll from her assigned skill list.

.*Vocation Skills*
. xref:i-persona_creation:CH08_Vocations_Biologist.adoc#_biologist_skills[Biologist Skill,window=_blank]
. xref:i-persona_creation:CH08_Vocations_Knite.adoc#_vocation_abilities[Knite Abilities,window=_blank]
. xref:i-persona_creation:CH08_Vocations_Mechanic.adoc#_mechanic_skills[Mechanic Skill,window=_blank]
. xref:i-persona_creation:CH08_Vocations_Mercenary.adoc#_mercenary_skills[Mercenary Skill,window=_blank]
. xref:i-persona_creation:CH08_Vocations_Nomad.adoc#_nomadic_biomes[Nomad Biomes,window=_blank]
. <<_mundane_skill,Nothing Skill>>
. xref:i-persona_creation:CH08_Vocations_Spie.adoc#_spie_skills[Spie Skill,window=_blank]
. xref:i-persona_creation:CH08_Vocations_Veterinarian.adoc#_vet_skills[Vet Skills,window=_blank]

== Alien Artifacts
Personas get a TOYs roll. 
It is completely random and only one roll is made. 
The result can range from random junque to starcruiser. 
Aliens are not limited to using an artifact by their appearance. 
Artifacts assigned at persona creation will be usable by the persona.

IMPORTANT: *Welcome friend of EXP. TOYS is unfinished in V6.0 of EXP.*

include::ROOT:partial$CH20_Table_Class_Specific_Artifacts.adoc[]

== Alien Name
Random personas are best named at the end of persona generation.
Alien creation in the Role Playing System is player centered, not dice centered.
So creating a persona that reflects it's name is more easily achieved.

== Alien Appearance
The most basic observable description should be included here. 
Additional descriptors like clothing, personality can also be included here.
For example, a pigeon headed caterpillar wearing a camo tent carrying a plastic bag.

== Anthro History
Keep track of the fun.
Entirely optional.
