= Anthro Creation
All anthros are upright, bipedal.
They have hands, heads and faces.
In the fake taxonomy of life in EXP Anthros are in the family Hominidae, and the genus homo.
Anthros are further differentiated by types.
Each anthro type is considered a species with names like homo avis, or homo felis.
A homo felis (feline) would be further differentiated as a cat, lion or cougar.
The final appearance of the anthro type is chosen by the player.

Player can choose their Anthro type and record it on their persona record.
For Example, Hominidae Canine.
The player can also roll their Family type if they choose.

include::ROOT:partial$CH26_Table_Record_Anthro.adoc[]

== Anthro Name
Random personas are best named at the end of persona generation.
Anthro creation in the Role Playing System is player centered, not dice centered.
So creating a persona that reflects it's name is more easily achieved.

== Anthro Appearance
The most basic observable description must be included here. 
For anthros that means the family anthro and species of choice. 
Additional descriptors like clothing, personality can also be included here.
For example, anthro feline tabby wearing a camo kilt carrying a big rifle.

== Anthro Attributes
The player does not generate numbers for a list of attributes.
The persona has one attribute that she excels in.
This can be randomly generated or chosen by the player. 

// attributes not blank size is always present
// personas get one attribute 
// that is there good attribute

include::ROOT:partial$CH26_Table_Attribute.adoc[]

=== Size
Size is an attribute assigned to every persona.
All anthros are size medium.
The size is recorded under the attributes section of the persona record.
For example, the persona record sheet could have medium and INT recorded under 

=== MSTR 
Mental Strength exists as an attribute.
MSTR must be acquired through a campaign.
If the referee would like a band of knites off on damn fool missions then every persona gets MSTR.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

The MSTR attribute can be earned by completing an MSTR testing story line laid out by the players.
Also MSTR can be assigned by suffering and surviving a mortal wound in combat.
The players will decide if the MSTR attribute has been earned by the persona.

=== Levels
No EXPS no levels. 
Immaculate successes add attributes, skills or abilities.

=== HPS
No HPS Max or Total.
Combat either kills a persona or takes away an attribute, skill or ability.
Permanently or temporarily.

== Anthro Vocation
Anyone choose anything from the list.

// consider random or matching attribute
// what is bonus for vocation linked attribute?


include::ROOT:partial$CH26_Table_Role_Vocations.adoc[]

=== Nothing
The Nothing is a vocation.
A player can choose to have a nothing persona.
If a persona loses all of her attributes she becomes a nothing.

=== Knite
Before a persona can become a knite she must earn her MSTR attribute.
The Knite vocation can be earned by completing an Knite testing story line laid out by the players.
Also Knite can be assigned by suffering and surviving a mortal wound in combat.
The players will decide if the Knite vocation has been earned by the persona.

== Skills
One nothing skill.
One skill from vocation.
One skill from attribute.

Skills hold on if vocation lost.

== Abilities
Quirks that are baked into the persona.
These are mutations in the case of anthros.
Abilities cannot be chosen.

A persona with a CON can pick a physical mutation
A persona with an INT can pick a mental mutation.

No defects. 

== TOYS
Personas get a TOY roll. 
This can be chosen from the list or generated.
TOYS is under construction.

Biologist - any
Veterinarian - vet
Nomad - miscellaneous equipment
Nothing - treasure
Spie - miscellaneous weapon
Mechanic - Any
Mercenary - Gun

== History
Keep track of the fun.
Entirely optional.





