= Theatrical Combat

Theatrical Combat is the Role Playing sibling of Tactical Combat.
Tactical Combat requires hex mats, tokens, miniatures and lots of dice.
The theatrical system employs a single mechanic to decide combat outcomes in very few rolls.
The Role Playing System focuses on simple die rolls that inform the direction of the story.
The story is always being built by the players the Role Playing System.

In Theatrical Combat there are no HPS, Movement, or Attacks Roll Bonuses to keep track of.
One roll of the 4D2 Mechanic informs the players of the outcome. 
The players are expected to interpret the outcome in a cinematic fashion that best serves the story.

== 4D2 Mechanic
he four refers to 4 dice being used.
The D refers to dice.
The two refers to the 2 sides of the roll.

4D2 uses four six sided dice to make random decisions in the Role Playing System.
The 4D2 System is the only mechanic in EXP's Role Playing System.
The Role Playing System eschews both the number and diversity of dice used in the Roll Playing System.

The 4D2 roll is a bespoke decision tool for EXP's Role Playing System.
4D2 replaces Attack Rolls, Performance Rolls, Attribute Rolls, Saving Rolls, Sphincter Rolls and more.
The 4D2 mechanic only replaces role playing when the situation exceeds the players' abilities to role play.
Combat and vocation maneuvers are quickly decided with the 4D2 mechanic and the role playing continues.

.*Four steps of 4D2 Mechanic*
. get Result from 4D2 mechanic
. get Descriptor from Result
. get Outcome from Descriptor
.. Apply shifts
. Return to story telling

== Result
The result is the number produced by rolling two pairs of competing six siders.

=== 4D2 Result Generation
.Outcome = 2d6 - 2d6
****
Range is +10 to -10. Positive is positive. Negative is negative. Zero is neutral.
****

The 4D2 mechanic generates a smooth curve of results between +10 and -10.
The result is player centric. 
So positive numbers indicate degree of success and negative numbers indicate degree of failure.
The most common result from this mechanic is 0.
0 represents balance, detent or no change.
+10 represents a phenomenal success for the persona.
-10 represents a phenomenal failure for the persona.

The curve is quite beautiful.

:art: fourDtwo.png
:width: 350px
:snark: Thank you anydice.com
:artist: Jasper Flick
:date: 2020
:license: AnyDice.com 

include::ROOT:partial$articulate.adoc[]

=== Example Results
The more dice rolled at once the more efficient the play.
The system can be used with just one six sided die.
It is more common for the player to roll two six siders (2d6) and the referee to roll two six siders (2d6).
The referee's sum is subtracted from the player's sum.
4D2 mechanic embraces the high roll and the higher the result the better the outcome for the persona.

The player rolls her 2d6 and the sum is 12. 
The referee rolls her 2d6 and the sum is 2.
The net roll is +10.
This will result in the best possible outcome for the player's persona.

The player rolls her 2d6 and the sum is 9. 
The referee rolls her 2d6 and the sum is 8.
The net roll is +1.
This will result in a very slight win for the player's persona.

The player rolls her 2d6 and the sum is 4. 
The referee rolls her 2d6 and the sum is 10.
The net roll is -6.
This will result in a very bad outcome for the player's persona.

Every group will develop it's style for generating these numbers.
The player versus referee will be the most common.
Sometimes the player will roll all 4 dice at once.
She will have pre-assigned on two dice to the positive and two other dice to the negative.
It is quite easy to have the dice pairs sporting different colours.
The positive six siders could be white and the negative six siders could be red.

The players and referee are free to choose whichever mechanic is the most fun. 

== Descriptors
What do these numbers indicate?
The success and failure attributions are pretty straight forward. 
They numerically represent positive and negative outcomes.
The 4D2 mechanic is not as decisive as the Roll Playing mechanics.
The outcome of +10 in combat is wildly different from an outcome -10 with a maneuver.
The positive and negative results __guide__ the role playing between the players and the story.

include::ROOT:partial$CH26_Table_4D2_Descriptors.adoc[]

A result of +10 is an immaculate success.
This result is quite rare. 
Immaculate success represents the best possible outcome for the persona.
In combat the persona will have vanquished their opponent in any fashion they see fit.
The persona can choose to kill, wound, or render her opponent unconscious.
These results are negotiated between the players to determine what supports the story best.

A result of +2 is a solid success.
This result is quite common. 
Solid success represents a successful outcome for the persona, but nothing special.
In combat the persona will won the fight, but the outcome is not certain.
The opponent may have run away, suffering a minor wound.
These results are negotiated between the players to determine what supports the story best.

A result of -10 is a cataclysmic failure.
This result is quite rare. 
Cataclysmic failure represents the worst possible outcome for the persona.
In combat the persona will suffered total defeat.
The persona could be killed, lethally wounded, or knocked unconscious.
These results are negotiated between the players to determine what supports the story best.

A result of 0 is detent.
This result is the most common result. 
Detent represents a neutral none outcome for the person.
In combat the persona continues to be locked in combat.
The fight music keeps playing and neither persona has the upper claw.
These results are negotiated between the players to determine what supports the story best.

== Outcomes 
In most cases the descriptor is an adequate outcome to get back to role playing the story.
Sometimes players need more direction.
This is especially the case in 4D2 combat where a persona can be killed outright with a negative result.
This is when outcomes come into play.
The outcomes are an added column to the Descriptors Table.
Each outcome lists a few options for the players to choose from.

.*Outcome Considerations*
. Persona
.. Outcome for the persona.
. Action
.. Outcome for the action
. Duration 
.. How long action lasts

Players are encouraged to make outcome tables to suit their style.
If the personas are constantly repairing a special drive they may want to have a modified outcome table.
There are two pre made 4D2 descriptor tables built 

=== 4D2 Combat Outcomes
Suggested outcomes for 4D2 result rolls.
Combat outcomes are divided into persona, action and duration outcomes.
Persona (P) outcomes impact the persona.
The outcome changes persona in some fashion.
The outcomes can be permanent, temporary, positive or negative.
For example, an Immaculate Success lets the player choose a new skill per her persona.
Action (A) outcomes describe possible result of the combat. 
The outcomes can be stun, disable, wound, mortally would, or kill.

Duration (D) outcomes indicate how long the action lasts or impacts the persona.
Duration of combat outcomes can be attacks, combat duration, beyond combat, and permanent. 

include::ROOT:partial$CH26_Table_4D2_Combat_Outcome.adoc[]

A result of +10 is an immaculate success.
This result is quite rare.

.*Immaculate Success Outcomes*
* P: Choose New Skill
** The player can add a permanent new skill
* A: Success and Victorious
** The player can choose to Kill, Mortally Wound, Disable or Stun her opponent.
* D: Permanent

Immaculate Success in combat:
The player gets to choose a new skill for her persona. 
She may add hand to hand or guns to her skills list.
This is the only way that personas can get new skills.
The player chooses to kill her opponent and that combat story is over.

A result of +2 is a solid success.
This result is quite common. 

.*Solid Success Outcomes*
* P: --
** No persona outcomes.
* A: Success
** The opponent is stunned.
* D: 2 Attacks
** The opponent is stunned. The player enjoys a shift and the 4D2 Mechanic is used again.

Solid Success in combat:
There are no persona outcomes with this descriptor.
The persona has the advantage, but combat is continuing.
The player gets to shift (+1) the next 4D2 Mechanic.

A result of -10 is a cataclysmic failure.
This result is quite rare.

.*Cataclysmic Failure Outcomes*
* P: Random Perm Loss
** The persona permanently loses a skill or attribute.
* A: Fail and Double Complicate
** The maneuver fails and gets worse .
* D: Months to retry
** The persona cannot try this maneuver again for months.

Cataclysmic Failure in combat:
The persona suffers the permanent loss of a skill or attribute.
The player loses a random attribute, skill or ability. 
The persona is unconscious, mortally wounded or killed outright in the combat.
The players will decide which outcome is best for the story.

== Shifts 
A shift is anything that alters the result of the 4D2 mechanic.
These are almost always bonuses added to the final result of 2d6 minus 2d6.
If a persona had gun skill, and DEX attribute she may be able to shift her result +2.
What shifts can be applied for a 4D2 roll is negotiable between the players.

Shifts are very important and are the only way players can gain advantage in the 4D2 system.
So a 4D2 result of 7 would become 9. 
Or a 4D2 result of -2 would become 0.

A shift may get a persona out of a tight spot. 
A shift may wrestle a success from certain failure.
A shift cannot be used to improve the descriptor generated by the 4D2 mechanic.

A persona has a skill of door repair 2 and the 4D2 result is +8 the final result would be 10 but her descriptor would be Magnificent Success (+8) and not Immaculate Success (+10).
This is still a very successful result for the persona. 
However she does not enjoy the benefits of the Immaculate Success descriptor.

Descriptors can indicate permanent changes to persona. 
The 4D2 mechanic is balanced for +10 to be rare.
Without shifts the 4D2 system has a 0.08% (less than 1%) chance of Immaculate Success.
With the +3 shifts the chance of chance of Immaculate Success increases to nearly 3%.

If the players wish to quickly develop invincible, over powered personas then shifts can alter descriptors.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Unanswered 4D2 Mechanic Results
There will be situations where the 4D2 Mechanic Result should not harm the persona.
If the attacker has a range advantage over the target it is inexplicable that she could be stunned by her opponent.

The Unanswered Result is for personas in combat.
It does not apply to disabled, wounded, unconscious or mortally wounded targets.
For example, a persona that chooses to dispatch a mortally wounded opponent need only role play that action.

For example, a ferocious alien is charging at a persona who has a type C laser pistol.
The players have decided that the charging alien is pistol range away.
The player would get two unanswered 4D2 Mechanic Results before the nasty claws are in range.
The Unanswered roll mostly ignores the negative result rolls.
If the first 4D2 Result is -6 (Complete Failure) the outcome would not be wounded.
It would be a miss and the alien keeps charging.
The next 4D2 Result is -10 (Cataclysmic Failure) the persona is not dead, or mortally wounded.
It would be another miss and the alien keeps charging.
Since a Cataclysmic Failure is so rare the players may decide that something bad should happen.
The players decide that the lazer has a battery failure.
This heightens the drama and adds to the combat story being told.
The 4D2 Mechanic will be a typical one where shifts and luck decide the outcome. 

== Combat Injuries
Theatrical combat does not have hit points to keep track of. 
Combat can be decided in a single 4D2 Mechanism Result.
The 4D2 Combat Outcomes are descriptive more than prescriptive.
There are many victory conditions in Theatrical Combat. 

=== Stun
A stunned target is still able to move, fight and think.
The stunned target is rattled and at a disadvantage. 
A stunned target is not seriously wounded but has been somehow disadvantaged on the next 4D2.

Stunning the opponent is not a victory condition.
An opponent may choose to run away.
If they choose to continue fighting they will be at a disadvantage.
The player enjoys a shift of +1 on the next 4D2 Mechanism Result.
The stun 4D2 Combat Outcomes can last for one or two 4D2 rolls.

What exactly is happening in the combat is described by the players.
The persona may be rattled, unsteady, or in a compromised position. 
They could easily rally, but the attacker has the upper hand.

=== Disabled
The disabled opponent is no longer a combat threat, but is not seriously injured.
They may be able to limp, or crawl, to safety. 
They cannot engage in any useful combat, but their life is not immediately threatened.
They are lucid but unable to act.
A disable persona may offer surrender.

The disabled state can last for a few 4D2 Rolls or until the end of combat.
While a disable persona cannot engage in combat they may still be able to use a mental mutation.

=== Wounded
The wounded opponent has suffered obvious damage as well as being disabled.
They are unable to function until their wounds are treated.
They remain conscious but unable to act.

A wounded persona will not die from their wounds but their inability to defend themselves may be fatal.

=== Mortally Wounded
This is a fatal wound that the persona will die from if they are not medically attended to.
For cinematic drama the persona will not die during combat, but later possibly during a monologue.
If a veterinarian is able to minister to the persona the mortal wound can be stemmed.

=== Unconscious
The personas has somehow been rendered unconscious and cannot function in any capacity. 
They would be at risk of drowning, succumbing to smoke inhalation, or being eaten by rats.
The unconscious state can be accompanied by a mortal wound if the story makes sense.

An unconscious persona die after combat unless medically attended to.
The veterinarian would have to deal with the unconsciousness before ministering to any other wounds.

=== Dead
The persona has suffered a fatal event in the process of combat.
This is why combat is to be avoided. 
The players can decide what ever is the best way for the persona to die.
Referee personas can fall like red shirted storm troopers.
Player personas should likely be offered a more poetic ending. 

== Attack Types
Same types names and explanations.
Ranges are qualitative and descriptive.
Poly attacks multiple rolls take best result.

=== Type A Attacks
These are non powered thrusting and striking attacks.
Type A attacks depend on the muscle power of the attacker, and must connect with target to cause damage.
The combatants must be within range of each other to engage in combat.
In the Theatrical Combat System Type B attacks outrange Type A Attacks.

Examples are: clubs, fists, claws, bites, swords, and ramming.
An anthro could use a weapon like a sword or a axe. 
An alien could use it's natural attack like a bite, or a talon slash.
A robot could use a malfunctioning peripheral that operates like an club.

Aliens and robots can have multiple attacks per turn with their type A attacks.
For example an alien may be able to bite three times each turn.
Or a robot may have multiple pointy things to stab with.

=== Type B Attacks
These are non-powered projectile attacks.
Type B attacks depend on the muscle power of the user, and are launched the target to cause damage.
Unlike type A attacks the attacker launches a projectile using their own muscle power.
The combatants must be within range to damage each other.
In the Theatrical Combat System Type C attacks outrange Type B Attacks.

Examples are: arrows, bolts, rocks, quills and spit.
An anthro would use a weapon like a bow or a sling. 
An alien could have an evolved natural attack like spitting rocks or flinging quills.
A robot could use a malfunctioning peripheral that flings metal shavings.

== Type C Attacks
These are powered projectile attacks.
Type C weapons do not require muscle power of the user, and are just pointed at the target to cause damage.
Combatants can be quite far apart and be able to damage each other.
In the Theatrical Combat System rifles outrange pistols. 

Examples are: bullets, laser bolts, energy beams, and crossbow bolts.
An anthro using a weapon like a gun or a lazer.
An alien could have a naturally evolved attack like lazer eyes or gas projected bone chunks.
A robot could be a combot with a baked in gun or a construction bot misusing a nail gun. 

== Type D, E Attacks
These are powered projectile attacks.
Type D and E attacks do not require muscle power of the user, and are just pointed at the target to cause damage.
Combatants can be quite far apart and be able to damage each other.
In the Theatrical Combat System rifles outrange pistols. 

Type D and E attacks are the same as type C attacks but with a higher firing rate.
Type D attacks attack twice as often as Type C Attacks.
Type D attacks usually allow the player to generate two 4D2 Mechanic Results choosing the best.
Type E attacks attack thrice as often as Type C Attacks.
Type E attacks usually allow the player to generate three 4D2 Mechanic Results choosing the best.

Examples are: bullets, laser bolts, energy beams, and crossbow bolts.
An anthro using a weapon like a fission or plasma rifle.
It would be unusual for an alien to have a type D attack type.
Aliens tend to have multiple attacks of type A, B or C. 
A robot with type D or E attacks usually has a baked in weapon that functions like a fission or plasma gun.

== Type F Attacks
These are powered attacks that are fully automated (F stands for fully automatic).
Type F attacks are almost always weapons.
In EXP full auto weapons are often referred to as flotto weapons
These powered weapons do not require muscle power of the user, and are just pointed to cause damage.
Combatants can be quite far apart and be able to damage each other.

A type F attack has an unique mechanism in the Theatrical Combat System. 
Most personas using a Type F attack are engaging in a pray and spray attack.
The player gets to generate 4 4D2 Mechanic Results picking the top 2.
Type F attacks are ominous indeed.

NOTE: *Weapon Type F was formerly called Weapon Type Special*

Examples are: machine gun, Gatling laser rifle, or machine pistol.
It is very unusual for an alien to have an evolved type F attack.
However tool using aliens could arm themselves the same as anthros.

== Type AOE Attacks
These are area of effect (AOE) weapons. 
Type AOE weapons do not need to contact the target to cause damage.
These weapons typically explode and  damage everything in their area of effect (AOE). 

In the Theatrical Combat System area of effect weapons are a much blunter weapon.
A grenade area of effect would effect all personas within the pistol range or closer.
If the players decide a group of targets are within pistol range of each other the attack effects them all.
A bomb has an enormous range and would effect every persona in combat. 
Only those further than rifle range away can escape the blast.

AOE attacks have a unique 4D2 Mechanic. 
The player generates an Unanswered 4D2 Result.
The Unanswered 4D2 Mechanic is explained later.
In short negative results generated by the player do not harm the persona.
Only a Cataclysmic Failure may result in a grenade drop or accidental early activation.
The decision by the players will decide whatever is best for the story.

Examples are: frag grenade, napalm aerosol, or fusion grenade.

== Range
There are no minis or hex mats rules for the Theatrical Combat System.
Ranges are descriptive and the effects of range are qualitative. 
Each descriptive level indicates how far apart the combatants are and what weapons can be used.

At the range Grapple the personas are locked in a death grip. 
Only punches, bites, claws and chokes can be used. 
There are some close combat weapons that may be used while grappling.

.*Theatrical Combat Ranges*
. Grapple
. Hand to hand
. Hand to hand, weapons
. Hand to hand, missile
. Powered, Pistol
. Powered, Rifle
. Sniping
. Artillery

include::ROOT:partial$CH26_Table_Theatrical_Range.adoc[]

=== Range Advantage
Range advantage is very serious in the Theatrical Combat System.
Range advantage allows for the player to generate Unanswered 4D2 Mechanic Result.
This advantage almost always occurs when a ranged attack is being used on a hand to hand attack.

Theatrical Combat ranges are qualitative and are used to tell the best combat story possible.
So a persona firing a pistol on a target that can only punch would get 3 Unanswered 4D2 Mechanic Results.

include::ROOT:partial$CH26_Table_Theatrical_Unanswered.adoc[]

=== AOE and Range
In the Theatrical Combat System area of effect weapons are a much blunter weapon.
A grenade area of effect would effect all personas within the pistol range or closer.
If the players decide a group of targets are within pistol range of each other the attack effects them all.
A bomb has an enormous range and would effect every persona in combat. 
Only those further than rifle range away can escape the blast.

AOE attacks have a unique 4D2 Mechanic. 
The player generates an Unanswered 4D2 Result.
The Unanswered 4D2 Mechanic is explained later.
In short negative results generated by the player do not harm the persona.
Only a Cataclysmic Failure may result in a grenade drop or accidental early activation.
The decision by the players will decide whatever is best for the story.

include::ROOT:partial$CH26_Table_AOE_Ranges.adoc[]

== Combat Movement
Combat movement is qualitative in the Theatrical Combat System.
There are no minis, no tokens and no mats.
There is no movement rate.
If a situation should arise where movement is critical to the story the 4D2 Mechanic is called upon.

Two personas can race each other to using the 4D2 Mechanic and employ shifts like DEX or Sprinting. 

If positioning for ranged attacks is important the players decide ranges that make the best story.
For example, in a restaurant the personas sitting at the same table are Hand to Hand Range or closer.
Everyone in the restaurant is within Powered, Pistol range or closer.
This would allow everyone to shoot at everyone else in the room.
Personas with Type A attacks may have to suffer an Unanswered 4D2 Mechanic if they are rushing a persona armed with a pistol, bow or laser rifle. 

Players can move their personas closer to engage in combat. 
Disengaging combat used the 4D2 Mechanic to see how successful the tactical withdrawal is.
Depending on the situation disengaging combat may offer the attacker an Unanswered 4D2 Mechanic Result.
If a grenade goes off in the dining area every persona is effected.

== Multiple Attacks
For personas that have multiple attacks there are several advantages.
The player can choose to attack multiple times or attack multiple targets.

Only Mercenaries can make flexible choices on how they divide their results.
For example, a mercenary that has 3 attacks could stop one target and move onto another.
Other vocation types would not be able to shift targets unless they are specially skilled.

=== Multiple Times
Multiple times on one target.
A player that chooses to use her multiple 4D2 Mechanic Results on one target is attacking multiple times.
If both personas are within range for their attacks the usual 4D2 Mechanic Result is generated.
The persona with more attacks has the option of generating additional 4D2 Mechanic Result rolls.
The player with the attack advantage can pick the result that works in their favour. 

include::ROOT:partial$CH26_Table_Mulitples.adoc[]

Combining range advantage with attack frequency dominance makes for an unstoppable force.

NOTE: *Some players do not allow persona enhancements like skills when using multiple results.*

Only combat vocations can change their attack configuration during combat.
For example, a Vet with a Type E attack pistol can only unload all 3 4D2 Results on one target.
A Mercenary with the same pistol may disable her target and choose to move to other targets. 

=== Multiple Targets
Multiple targets indicates that the persona is attacking different targets with each 4D2 Mechanic.
Multiple targets requires all targets to be in range.

For example, a Type D Attack could be split between two different targets.
The player would generate one 4D2 Mechanic Result with each target.
This is most effective when there is a range advantage. 

An alien that has three Type A Attacks could claw three different opponents at once.
If one of the outcomes is fatal for the alien she will get to generate all three 4D2 Mechanic Results.

Only combat vocations can change their attack configuration during combat.
For example, a Vet with a Type E attack pistol can only unload all 3 4D2 Results on one target.
A Mercenary with the same pistol may disable two targets and choose to move another across the room. 

== Combat Tables
There are no combat tables in the Theatrical Combat System.
Players can shift the 4D2 Mechanisms with attributes, skills and abilities. 


shifts are like combat tables

== Armour Rating
There is no armour rating.
There may be abilities that assist.
DEX can be a shift.

== Combat Time
Combat is just a story. 
Players can attribute what ever time is needed to make the best story.

== Initiative
There is no initiative.
maybe unanswered results

The order of combat is decided by which combat story is most important.

== Ambush
Ambush effectiveness is determined by the 4D2 mechanic as a maneuver.
Ranged attacks bonus.


== Weather
Purely descriptive.

== Hit Location
Purely descriptive



== Robot Combat
Ramming.
Size.

== Alien Combat
Size.

== Exatmo Vehicle Combat
Mechanic and then must board. 
Boarding is better story so only option.

== Inatmo Vehicle Combat
Purely descriptive

== Non Lethal Combat
Same mechanic of combat just remove the mortal wounds and death.


