= Theatrical Combat

The Theatrical Combat System is the cinematic and storyful sibling of Tactical Combat System.
The Tactical Combat System requires hex mats, tokens, miniatures and lots of dice.
The Theatrical Combat System assists the players in telling a combat story. 

The Roll Playing System employs many tables and dice rolls to generate faux science outcomes.
Successes are quantified with more dice rolls and numbers.
The players measure success with removing HPS or increasing EXPS. 

NOTE: *The players interpret outcomes in the cinematic fashion that best serves the story.*

The Role Playing System employs a single mechanic that helps direct the story.
Successes are qualitative and descriptive.
The players are required to describe the outcome that best suits the story.

In the Theatrical Combat System there is only story.
There are no HPS, Movement, Proficiencies or Attacks Rolls to keep track of.
This does not mean less work. 
In many ways the participants work their imagination muscle more than their math muscle.
The outcomes are descriptive and require a creative description.
A description often requires more effort than subtracting 6 from 48.

The Role Playing System uses the Theatrical Combat System.
The Theatrical Combat System depends on the 4D2 Mechanic.

== 4D2 Mechanic
4D2 is both a descriptor and a joke. 
The 4 indicates that the mechanic uses 4 dice.
The 4 also indicates that there are 4 steps in the process.
The D refers to dice, and it a play on "D" in the 4d6 convention.
The 2 reflects that the mechanic has two directions.
The joke is that 4D2 sounds like 42.
Fourty Two is the answer to the question.
The 4D2 Mechanic gives the answers to questions you don't understand.

The 4D2 Mechanic uses four six sided dice to guide the story in the Role Playing System.
The 4D2 Mechanic is a bespoke decision tool for EXP's Role Playing System.
4D2 replaces Attack Rolls, Performance Rolls, Attribute Rolls, Saving Rolls, Sphincter Rolls and more.

In the Theatrical Combat System the 4D2 Mechanism is used to guide the combat story. 
Players ultimately guide the outcomes that the mechanic generates.

.*Four steps of 4D2 Mechanic*
. get *Result* from 4D2 mechanic
. get *Descriptor* from Result
.. Apply the Shifts
. get *Outcome* from Descriptor
. Return to story telling

== 4D2 Mechanic Results
The result is the number produced by rolling two pairs of competing six siders.
The player rolls 2d6 and generates a number between 2 and 12.
Another player rolls 2d6 and generates another number between 2 and 12.
The second roll is subtracted from the first roll.
The curve is quite beautiful.

:art: fourDtwo.png
:width: 350px
:snark: Thank you anydice.com
:artist: Jasper Flick
:date: 2020
:license: AnyDice.com 

include::ROOT:partial$articulate.adoc[]

=== 4D2 Result Generation
.Outcome = 2d6 - 2d6
****
Range is +10 to -10. Positive is positive. Negative is negative. Zero is neutral.
****

The 4D2 mechanic generates a smooth curve of results between +10 and -10.
The result is player centric. 
Positive numbers indicate success and negative numbers indicate failure.
The most common result from this mechanic is 0.
0 represents balance, detent or ongoing struggle.
+10 represents the epitome of success for the persona.
-10 represents the epitome of failure for the persona.

The 4D2 Mechanism Result is a numeric value.
Each possible outcome is linked to a descriptor that the player use to guide the story.

=== Example 4D2 Results
The 4D2 Mechanic Result can be generated by rolling one six sider four times.
The more dice rolled at once the more efficient the mechanism.
Most commonly one player rolls two six siders (2d6) and another player rolls the competing two six siders (2d6).
All four dice can be rolled at once by assigning plus to one coloured pair and minus to another coloured pair.

.*Some example results*
* The player rolls 2d6 and the sum is 12. 
The opposing 2d6 roll has a sum of 2.
The 4D2 Mechanic Result is +10.
+10 is the best result for the player's persona.

* The player rolls 2d6 and the sum is 9. 
The opposing 2d6 roll has a sum of 8.
The net roll is +1.
This will result in a very slight win for the player's persona.

* The player rolls her 2d6 and the sum is 4. 
The referee rolls her 2d6 and the sum is 10.
The net roll is -6.
This will result in a very bad outcome for the player's persona.

Every group will develop it's style for generating 4D2 Mechanic Results.
The most common is rolling 2 pairs of different coloured dice.
One pair is positive and the other pair is negative.
For example, the positive six siders could be white and the negative six siders could be red.

== 4D2 Mechanic Descriptors
The 4D2 Mechanic Result can be used as a raw number to determine what happens to the persona.
There is also a descriptor table that correspondingly dramatic descriptors for every result.
The 4D2 Mechanic Result is converted to a descriptor for fun and efficiency.
For example, +10 is an Immaculate Success and -10 is a Cataclysmic Failure.

include::ROOT:partial$CH26_Table_4D2_Descriptors.adoc[]

The descriptors help __guide__ the players describe the outcome of the maneuver.
A positive result (number) yields a positive success descriptor.
A negative result (number) yields a negative failure descriptor.
The descriptor may be all the players need to move the story along. 
For example, a Vet is trying remove a splinter from a feline's paw.
An Immaculate Success descriptor would guide the players to tell a story with a happy result.

.*Some Example Descriptors*
* A result of +10 is an Immaculate Success.
This descriptor is rare. 
Immaculate Success represents the best possible outcome for the persona.
The player can choose to kill, wound, or render her opponent unconscious.
The descriptor guides the players to describe what tells the best combat story.

* A result of +2 is a Solid Success.
This descriptor is quite common. 
Solid Success represents a positive outcome for the persona, but nothing dramatic.
In combat the persona may have won an advantage, but the combat story is undecided.
The descriptor guides the players to describe what tells the best combat story.

* A result of -10 is a Cataclysmic Failure.
This descriptor is quite rare. 
Cataclysmic Failure represents the worst possible outcome for the persona.
In combat the persona will suffered total defeat.
The persona could be killed, lethally wounded, or knocked unconscious.
The descriptor guides the players to describe what tells the best combat story.

* A result of 0 is detent.
This descriptor is the most common. 
Detent represents a balance between the combatants.
The combat story is ongoing.
Dramatic fight music continues and neither persona has the upper claw.

== 4D2 Mechanic Outcomes 
Often a descriptor gives adequate guidance to the players telling the combat story.
For common 4D2 Mechanic uses there are also Outcome Tables.
Outcome tables include some common results for their associated descriptors.
This is especially important when a persona's life is one the line. 

There are only two outcome tables included in the Role Playing System.
There is a Combat Outcomes Table and a Maneuvers Outcome Table.

=== 4D2 Combat Outcomes
Suggested outcomes for the 4D2 Mechanic in the Theatrical Combat System.
The outcomes are not just about combat, but how the outcome affects the persona.
A persona can earn a new combat skill for very successful descriptors.
The combat outcome differs between inorganic and organic targets. 

include::ROOT:partial$CH26_Table_4D2_Combat_Outcome.adoc[]

Aliens and anthros are organic targets and robots are inorganic targets.
Robots damage differently from organics and the outcomes are descriptively and effectively different.

.*Some Example Outcomes*
* The descriptor of Immaculate Success (+10) is quite rare.
The persona earns a new skill. 
An organic opponent can be killed or suffer any lesser outcome.
An inorganic opponent would lost two attributes, likely destroying it.

* The descriptor Solid Success (+2) is quite common.
The persona earns no skills with this outcome.
An organic opponent will be put on a full backfoot.
An inorganic opponent will suffer a rattle. 


* The descriptor Cataclysmic Failure (-10) is quite rare.
The persona has a skill knocked out of their head.
An organic persona could receive a mortal wound losing combat.
An inorganic persona would lose an attribute or a peripheral. 

== Shifts 
A shift is anything that alters the result of the 4D2 mechanic.
These are almost always bonuses added to the final result of 2d6 minus 2d6.
If a persona had gun skill, and DEX attribute she may be able to shift her result +2.
What shifts can be applied for a 4D2 roll is negotiable between the players.

Shifts are very important and are the only way players can gain advantage in the 4D2 system.
So a 4D2 result of 7 would become 9. 
Or a 4D2 result of -2 would become 0.

A shift may get a persona out of a tight spot. 
A shift may wrestle a success from certain failure.
A shift cannot be used to improve the descriptor generated by the 4D2 mechanic.

A persona has a skill of door repair 2 and the 4D2 result is +8 the final result would be 10 but her descriptor would be Magnificent Success (+8) and not Immaculate Success (+10).
This is still a very successful result for the persona. 
However she does not enjoy the benefits of the Immaculate Success descriptor.

Descriptors can indicate permanent changes to persona. 
The 4D2 mechanic is balanced for +10 to be rare.
Without shifts the 4D2 system has a 0.08% (less than 1%) chance of Immaculate Success.
With the +3 shifts the chance of chance of Immaculate Success increases to nearly 3%.

If the players wish to quickly develop invincible, over powered personas then shifts can alter descriptors.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Unanswered 4D2 Mechanic Results
There will be situations where the 4D2 Mechanic Result should not harm the persona.
If the attacker has a range advantage over the target it is inexplicable that she could be stunned by her opponent.

The Unanswered Result is for personas in combat.
It does not apply to disabled, wounded, unconscious or mortally wounded targets.
For example, a persona that chooses to dispatch a mortally wounded opponent need only role play that action.

For example, a ferocious alien is charging at a persona who has a type C laser pistol.
The players have decided that the charging alien is pistol range away.
The player would get two unanswered 4D2 Mechanic Results before the nasty claws are in range.
The Unanswered roll mostly ignores the negative result rolls.
If the first 4D2 Result is -6 (Complete Failure) the outcome would not be wounded.
It would be a miss and the alien keeps charging.
The next 4D2 Result is -10 (Cataclysmic Failure) the persona is not dead, or mortally wounded.
It would be another miss and the alien keeps charging.
Since a Cataclysmic Failure is so rare the players may decide that something bad should happen.
The players decide that the lazer has a battery failure.
This heightens the drama and adds to the combat story being told.
The 4D2 Mechanic will be a typical one where shifts and luck decide the outcome. 

== Combat Injuries
Theatrical combat does not have hit points to keep track of. 
Combat can be decided in a single 4D2 Mechanism Result.
The 4D2 Combat Outcomes are descriptive more than prescriptive.
There are many victory conditions in Theatrical Combat. 

=== Stun
A stunned target is still able to move, fight and think.
The stunned target is rattled and at a disadvantage. 
A stunned target is not seriously wounded but has been somehow disadvantaged on the next 4D2.

Stunning the opponent is not a victory condition.
An opponent may choose to run away.
If they choose to continue fighting they will be at a disadvantage.
The player enjoys a shift of +1 on the next 4D2 Mechanism Result.
The stun 4D2 Combat Outcomes can last for one or two 4D2 rolls.

What exactly is happening in the combat is described by the players.
The persona may be rattled, unsteady, or in a compromised position. 
They could easily rally, but the attacker has the upper hand.

=== Disabled
The disabled opponent is no longer a combat threat, but is not seriously injured.
They may be able to limp, or crawl, to safety. 
They cannot engage in any useful combat, but their life is not immediately threatened.
They are lucid but unable to act.
A disable persona may offer surrender.

The disabled state can last for a few 4D2 Rolls or until the end of combat.
While a disable persona cannot engage in combat they may still be able to use a mental mutation.

=== Wounded
The wounded opponent has suffered obvious damage as well as being disabled.
They are unable to function until their wounds are treated.
They remain conscious but unable to act.

A wounded persona will not die from their wounds but their inability to defend themselves may be fatal.

=== Mortally Wounded
This is a fatal wound that the persona will die from if they are not medically attended to.
For cinematic drama the persona will not die during combat, but later possibly during a monologue.
If a veterinarian is able to minister to the persona the mortal wound can be stemmed.

=== Unconscious
The personas has somehow been rendered unconscious and cannot function in any capacity. 
They would be at risk of drowning, succumbing to smoke inhalation, or being eaten by rats.
The unconscious state can be accompanied by a mortal wound if the story makes sense.

An unconscious persona die after combat unless medically attended to.
The veterinarian would have to deal with the unconsciousness before ministering to any other wounds.

=== Dead
The persona has suffered a fatal event in the process of combat.
This is why combat is to be avoided. 
The players can decide what ever is the best way for the persona to die.
Referee personas can fall like red shirted storm troopers.
Player personas should likely be offered a more poetic ending. 

== Attack Types
Same types names and explanations.
Ranges are qualitative and descriptive.
Poly attacks multiple rolls take best result.

=== Type A Attacks
These are non powered thrusting and striking attacks.
Type A attacks depend on the muscle power of the attacker, and must connect with target to cause damage.
The combatants must be within range of each other to engage in combat.
In the Theatrical Combat System Type B attacks outrange Type A Attacks.

Examples are: clubs, fists, claws, bites, swords, and ramming.
An anthro could use a weapon like a sword or a axe. 
An alien could use it's natural attack like a bite, or a talon slash.
A robot could use a malfunctioning peripheral that operates like an club.

Aliens and robots can have multiple attacks per turn with their type A attacks.
For example an alien may be able to bite three times each turn.
Or a robot may have multiple pointy things to stab with.

=== Type B Attacks
These are non-powered projectile attacks.
Type B attacks depend on the muscle power of the user, and are launched the target to cause damage.
Unlike type A attacks the attacker launches a projectile using their own muscle power.
The combatants must be within range to damage each other.
In the Theatrical Combat System Type C attacks outrange Type B Attacks.

Examples are: arrows, bolts, rocks, quills and spit.
An anthro would use a weapon like a bow or a sling. 
An alien could have an evolved natural attack like spitting rocks or flinging quills.
A robot could use a malfunctioning peripheral that flings metal shavings.

== Type C Attacks
These are powered projectile attacks.
Type C weapons do not require muscle power of the user, and are just pointed at the target to cause damage.
Combatants can be quite far apart and be able to damage each other.
In the Theatrical Combat System rifles outrange pistols. 

Examples are: bullets, laser bolts, energy beams, and crossbow bolts.
An anthro using a weapon like a gun or a lazer.
An alien could have a naturally evolved attack like lazer eyes or gas projected bone chunks.
A robot could be a combot with a baked in gun or a construction bot misusing a nail gun. 

== Type D, E Attacks
These are powered projectile attacks.
Type D and E attacks do not require muscle power of the user, and are just pointed at the target to cause damage.
Combatants can be quite far apart and be able to damage each other.
In the Theatrical Combat System rifles outrange pistols. 

Type D and E attacks are the same as type C attacks but with a higher firing rate.
Type D attacks attack twice as often as Type C Attacks.
Type D attacks usually allow the player to generate two 4D2 Mechanic Results choosing the best.
Type E attacks attack thrice as often as Type C Attacks.
Type E attacks usually allow the player to generate three 4D2 Mechanic Results choosing the best.

Examples are: bullets, laser bolts, energy beams, and crossbow bolts.
An anthro using a weapon like a fission or plasma rifle.
It would be unusual for an alien to have a type D attack type.
Aliens tend to have multiple attacks of type A, B or C. 
A robot with type D or E attacks usually has a baked in weapon that functions like a fission or plasma gun.

== Type F Attacks
These are powered attacks that are fully automated (F stands for fully automatic).
Type F attacks are almost always weapons.
In EXP full auto weapons are often referred to as flotto weapons
These powered weapons do not require muscle power of the user, and are just pointed to cause damage.
Combatants can be quite far apart and be able to damage each other.

A type F attack has an unique mechanism in the Theatrical Combat System. 
Most personas using a Type F attack are engaging in a pray and spray attack.
The player gets to generate 4 4D2 Mechanic Results picking the top 2.
Type F attacks are ominous indeed.

NOTE: *Weapon Type F was formerly called Weapon Type Special*

Examples are: machine gun, Gatling laser rifle, or machine pistol.
It is very unusual for an alien to have an evolved type F attack.
However tool using aliens could arm themselves the same as anthros.

== Type AOE Attacks
These are area of effect (AOE) weapons. 
Type AOE weapons do not need to contact the target to cause damage.
These weapons typically explode and  damage everything in their area of effect (AOE). 

In the Theatrical Combat System area of effect weapons are a much blunter weapon.
A grenade area of effect would effect all personas within the pistol range or closer.
If the players decide a group of targets are within pistol range of each other the attack effects them all.
A bomb has an enormous range and would effect every persona in combat. 
Only those further than rifle range away can escape the blast.

AOE attacks have a unique 4D2 Mechanic. 
The player generates an Unanswered 4D2 Result.
The Unanswered 4D2 Mechanic is explained later.
In short negative results generated by the player do not harm the persona.
Only a Cataclysmic Failure may result in a grenade drop or accidental early activation.
The decision by the players will decide whatever is best for the story.

Examples are: frag grenade, napalm aerosol, or fusion grenade.

== Range
There are no minis or hex mats rules for the Theatrical Combat System.
Ranges are descriptive and the effects of range are qualitative. 
Each descriptive level indicates how far apart the combatants are and what weapons can be used.

At the range Grapple the personas are locked in a death grip. 
Only punches, bites, claws and chokes can be used. 
There are some close combat weapons that may be used while grappling.

.*Theatrical Combat Ranges*
. Grapple
. Hand to hand
. Hand to hand, weapons
. Hand to hand, missile
. Powered, Pistol
. Powered, Rifle
. Sniping
. Artillery

include::ROOT:partial$CH26_Table_Theatrical_Range.adoc[]

=== Range Advantage
Range advantage is very serious in the Theatrical Combat System.
Range advantage allows for the player to generate Unanswered 4D2 Mechanic Result.
This advantage almost always occurs when a ranged attack is being used on a hand to hand attack.

Theatrical Combat ranges are qualitative and are used to tell the best combat story possible.
So a persona firing a pistol on a target that can only punch would get 3 Unanswered 4D2 Mechanic Results.

include::ROOT:partial$CH26_Table_Theatrical_Unanswered.adoc[]

=== AOE and Range
In the Theatrical Combat System area of effect weapons are a much blunter weapon.
A grenade area of effect would effect all personas within the pistol range or closer.
If the players decide a group of targets are within pistol range of each other the attack effects them all.
A bomb has an enormous range and would effect every persona in combat. 
Only those further than rifle range away can escape the blast.

AOE attacks have a unique 4D2 Mechanic. 
The player generates an Unanswered 4D2 Result.
The Unanswered 4D2 Mechanic is explained later.
In short negative results generated by the player do not harm the persona.
Only a Cataclysmic Failure may result in a grenade drop or accidental early activation.
The decision by the players will decide whatever is best for the story.

include::ROOT:partial$CH26_Table_AOE_Ranges.adoc[]

== Combat Movement
Combat movement is qualitative in the Theatrical Combat System.
There are no minis, no tokens and no mats.
There is no movement rate.
If a situation should arise where movement is critical to the story the 4D2 Mechanic is called upon.

Two personas can race each other to using the 4D2 Mechanic and employ shifts like DEX or Sprinting. 

If positioning for ranged attacks is important the players decide ranges that make the best story.
For example, in a restaurant the personas sitting at the same table are Hand to Hand Range or closer.
Everyone in the restaurant is within Powered, Pistol range or closer.
This would allow everyone to shoot at everyone else in the room.
Personas with Type A attacks may have to suffer an Unanswered 4D2 Mechanic if they are rushing a persona armed with a pistol, bow or laser rifle. 

Players can move their personas closer to engage in combat. 
Disengaging combat used the 4D2 Mechanic to see how successful the tactical withdrawal is.
Depending on the situation disengaging combat may offer the attacker an Unanswered 4D2 Mechanic Result.
If a grenade goes off in the dining area every persona is effected.

== Multiple Attacks
For personas that have multiple attacks there are several advantages.
The player can choose to attack multiple times or attack multiple targets.

Only Mercenaries can make flexible choices on how they divide their results.
For example, a mercenary that has 3 attacks could stop one target and move onto another.
Other vocation types would not be able to shift targets unless they are specially skilled.

=== Multiple Times
Multiple times on one target.
A player that chooses to use her multiple 4D2 Mechanic Results on one target is attacking multiple times.
If both personas are within range for their attacks the usual 4D2 Mechanic Result is generated.
The persona with more attacks has the option of generating additional 4D2 Mechanic Result rolls.
The player with the attack advantage can pick the result that works in their favour. 

include::ROOT:partial$CH26_Table_Mulitples.adoc[]

Combining range advantage with attack frequency dominance makes for an unstoppable force.

NOTE: *Some players do not allow persona enhancements like skills when using multiple results.*

Only combat vocations can change their attack configuration during combat.
For example, a Vet with a Type E attack pistol can only unload all 3 4D2 Results on one target.
A Mercenary with the same pistol may disable her target and choose to move to other targets. 

=== Multiple Targets
Multiple targets indicates that the persona is attacking different targets with each 4D2 Mechanic.
Multiple targets requires all targets to be in range.

For example, a Type D Attack could be split between two different targets.
The player would generate one 4D2 Mechanic Result with each target.
This is most effective when there is a range advantage. 

An alien that has three Type A Attacks could claw three different opponents at once.
If one of the outcomes is fatal for the alien she will get to generate all three 4D2 Mechanic Results.

Only combat vocations can change their attack configuration during combat.
For example, a Vet with a Type E attack pistol can only unload all 3 4D2 Results on one target.
A Mercenary with the same pistol may disable two targets and choose to move another across the room. 

== Combat Tables
There are no combat tables in the Theatrical Combat System.
Personas gain combat advantage from their skills, abilities, weapons, and size.
These are called Shifts because they shift the 4D2 Mechanic Result.
Hopefully the Shift will be in the persona's benefit.
The term Shift was chosen because the shift represents a summation of bonuses, penalties, abilities and skills.

When the player generates a 4D2 Mechanic Result she tries to Shift the result in her favour.
Our example is a Mercenary with the attributes PSTR INT, the ability Ambidextrous and the skill Hand to Hand.
When using when attacking with a sword she would get PSTR and Hand to Hand bonuses. 
If these bonuses are unopposed her shift would be +2.
This would indicate her worst outcome from the 4D2 Mechanic is -8 or Mortally wounded.
Her chances are markedly __shifted__ towards success. 
If her opponent had PSTR as well the two would cancel each other out and the persona's Shift would be +1.
This is still helpful.

Persona benefits from the 4D2 Mechanic can only arise from the natural mechanic result.
A shift of +2 and a natural result of +8 converts to an Immaculate Success and likely death for the opponent.
However she can only acquire the +8 Magnificent Success personal bonuses. 
So she will receive a temporary skill attribute, and not permanent new skill (+10).

== Armour Rating
There are no Armour Ratings in the Theatrical Combat System.
Personas gain combat advantage from their skills, abilities, weapons, and size.
These are called Shifts because they shift the 4D2 Mechanic Result.
Hopefully the Shift will be in the persona's benefit.
The term Shift was chosen because the shift represents a summation of bonuses, penalties, abilities and skills.

A persona that has protective armour and DEX attribute may choose to use these to shift the 4D2 Mechanic Result.
The player could use the DEX and Armour to get a shift of +2. 
If the opponent also had DEX and Armour there would be no shift available.

== Combat Time
There are no turns in the Theatrical Combat System.
Players can organize time to what ever is needed to make the best combat story.
If there is a race against time built into the story the players may use the 4D2 Mechanic to determine the outcome.

The players can organize their order of decision making to what ever suits the combat story best.
For example it may be simplest to go around the table and have each player take a turn.
If there is a dire situation for a persona the players may have her player go first or last. 
The order of combat is decided by what makes the best combat story.

== Initiative
There is no initiative in the Theatrical Combat System.
Players can organize play order to what ever is needed to make the best combat story.
If there is a race against time built into the story the players may use the 4D2 Mechanic to determine the outcome.

The players can organize their order of decision making to what ever suits the combat story best.
For example it may be simplest to go around the table and have each player take a turn.
If there is a dire situation for a persona the players may have her player go first or last. 
The order of combat is decided by what makes the best combat story.

== Ambush
The expedition can be on the receiving, or delivering, side of an ambush.
The outcome of the ambush is decided by the 4D2 Mechanic.
The win for an ambush is a number of Unanswered 4D2 Mechanic Results.
An Immaculate Success would give 2 Unanswered 4D2 Mechanic Results.
Any other success would give 1 Unanswered 4D2 Mechanic Result.

A Failure would just mean no surprise and no Unanswered 4D2 Mechanic Results.
If the result is a cataclysmic failure (-10) the players may decide to reverse the ambush effect.

== Weather
There are no weather effects in the Theatrical Combat System.
It is assumed that all personas are affected by the weather equally.
Weather is a purely descriptive element in this system. 

Occasionally a player with an alien may argue for a shift if she is in her element.
This is decided by the players. 

== Hit Location
There are no hit locations in the Theatrical Combat System.
There are no hit locations in the Tactical Combat System either.
Hit locations are a descriptive element in this system. 

== Anthro Combat
The Theatrical Combat System is based on anthros fighting anthros. 
There some adjustments to the system for robots and aliens.
Robots behave slightly differently due to their size and inorganic fabrication.
Aliens behave slightly differently due to their size.

== Robot Combat
There are some advantages to being an inorganic life form in combat.
There are many attacks that are ineffective against robots. 
Mental attacks like ESP or mental control are not effective on the inorganic brain.

=== Robot Size
Size counts as a shift for robots in hand to hand combat.
Size also counts as a shift in how they are damaged in combat.

With Type A Attacks, including ramming, the robot gets a shift for size.
For example, a Large sized robot would get a shift of of +1 if she were battling a Medium or smaller opponent.
A Gigantic sized robot would get a shift of +2 if she were brawling a Medium or smaller sized opponent. 
If the opponents are the same size there is no shift allotted.

=== Robot Damage
Robots can shift 4D2 Mechanic Outcomes in their favour in regards to damage.
For example a Gigantic robot can shift her damage outcome by 2 decreasing the outcome.
This does not affect the personal outcomes of the attacker.
For example a persona is attacking a Gigantic robot.
The player generates an Wonderous Success (+9) Result on the 4D2 Mechanic.
Her persona will earn a skill as suggested by the outcome.
However the robot will only be Mortally wounded by the attack (+7).

Robots cannot be knocked unconscious or disabled during combat.
The player running the persona may choose to drop an attribute of choice. 
A robot is destroyed once it loses all it's attributes. 
Robots are easy to damage, but hard to destroy

== Alien Combat
There are some advantages to being an alien in combat.
Many aliens have natural attacks that allow for Multiple Mechanic Results and Unanswered Mechanic Results.
Aliens can also lever their size with Type A Attacks and Mechanic Outcomes.

=== Alien Size
Size counts as a shift for aliens in hand to hand combat.
Size also counts as a shift in how they are damaged in combat.

With Type A Attacks, aliens enjoy a shift for size.
For example, a Large sized alien would get a shift of of +1 if she were battling a Medium or smaller opponent.
A Gigantic sized alien would get a shift of +2 if she were brawling a Medium or smaller sized opponent. 
If the opponents are the same size there is no shift allotted.

=== Alien Damage
Aliens can shift 4D2 Mechanic Outcomes in their favour in regards to damage.
For example a Gigantic alien can shift her damage outcome by 2 decreasing the outcome.
This does not affect the personal outcomes of the attacker.
For example a persona is attacking a Gigantic alien.
The player generates an Wonderous Success (+9) Result on the 4D2 Mechanic.
Her persona will earn a skill as suggested by the outcome.
However the alien will only be Mortally wounded by the attack (+7).

Aliens cannot be knocked unconscious or disabled during combat.
The player running the persona may choose to drop an attribute of choice. 
A alien is destroyed once it loses all it's attributes. 
Aliens are easy to damage, but hard to destroy

== Size Shifts

include::ROOT:partial$CH26_Table_Size_Shifts.adoc[]

== Exatmo Vehicle Combat
Spaceship combat is decided on a single 4D2 Mechanic Result.
There are no specific outcomes for Exatmo vehicle combat.
The players will choose the outcomes that represent the best outcome for the story.

A success for the expedition would allow them to board the target ship.
Boarding and interacting inside the target space vehicle is much more cinematic and storyful.
For single pilot crafts in an exatmo dog fight a success may mean destruction of the opponent.

A failure could indicate that the target ship escapes or the target ship boards the expedition. 
A failure would rarely result in destruction of the expedition vessel. 
As with successes the players will decide what outcome best suits the story. 



