= Four D Two System

[quote]
_____
*Four D Two, Four-D-Two, 4D2 are word plays on 42. The answer to the wrong question.*
_____

Nomenclature of 4D2. 
The four refers to 4 dice being used.
The D refers to dice.
The two refers to the 2 sides of the roll.

4D2 uses four six sided dice to make random decisions in the Role Playing System.
The 4D2 System is the only mechanic in EXP's Role Playing System.
The Role Playing System eschews both the number and diversity of dice used in the Roll Playing System.

The 4D2 roll is a bespoke decision tool for EXP's Role Playing System.
4D2 replaces Attack Rolls, Performance Rolls, Attribute Rolls, Saving Rolls, Sphincter Rolls and more.
The 4D2 mechanic only replaces role playing when the situation exceeds the players' abilities to role play.
Combat and vocation maneuvers are quickly decided with the 4D2 mechanic and the role playing continues.

.*Four steps of 4D2 Mechanic*
. get Result from 4D2 mechanic
. get Descriptor from Result
. get Outcome from Descriptor
.. Apply shifts
. Return to story telling

== Result
The result is the number produced by rolling two pairs of competing six siders.

=== 4D2 Result Generation
.Outcome = 2d6 - 2d6
****
Range is +10 to -10. Positive is positive. Negative is negative. Zero is neutral.
****

The 4D2 mechanic generates a smooth curve of results between +10 and -10.
The result is player centric. 
So positive numbers indicate degree of success and negative numbers indicate degree of failure.
The most common result from this mechanic is 0.
0 represents balance, detent or no change.
+10 represents a phenomenal success for the persona.
-10 represents a phenomenal failure for the persona.

The curve is quite beautiful.

:art: fourDtwo.png
:width: 350px
:snark: Thank you anydice.com
:artist: Jasper Flick
:date: 2020
:license: AnyDice.com 

include::ROOT:partial$articulate.adoc[]

=== Example Results
The more dice rolled at once the more efficient the play.
The system can be used with just one six sided die.
It is more common for the player to roll two six siders (2d6) and the referee to roll two six siders (2d6).
The referee's sum is subtracted from the player's sum.
4D2 mechanic embraces the high roll and the higher the result the better the outcome for the persona.

The player rolls her 2d6 and the sum is 12. 
The referee rolls her 2d6 and the sum is 2.
The net roll is +10.
This will result in the best possible outcome for the player's persona.

The player rolls her 2d6 and the sum is 9. 
The referee rolls her 2d6 and the sum is 8.
The net roll is +1.
This will result in a very slight win for the player's persona.

The player rolls her 2d6 and the sum is 4. 
The referee rolls her 2d6 and the sum is 10.
The net roll is -6.
This will result in a very bad outcome for the player's persona.

Every group will develop it's style for generating these numbers.
The player versus referee will be the most common.
Sometimes the player will roll all 4 dice at once.
She will have pre-assigned on two dice to the positive and two other dice to the negative.
It is quite easy to have the dice pairs sporting different colours.
The positive six siders could be white and the negative six siders could be red.

The players and referee are free to choose whichever mechanic is the most fun. 

== Descriptors
What do these numbers indicate?
The success and failure attributions are pretty straight forward. 
They numerically represent positive and negative outcomes.
The 4D2 mechanic is not as decisive as the Roll Playing mechanics.
The outcome of +10 in combat is wildly different from an outcome -10 with a maneuver.
The positive and negative results __guide__ the role playing between the players and the story.

include::ROOT:partial$CH26_Table_4D2_Descriptors.adoc[]

A result of +10 is an immaculate success.
This result is quite rare. 
Immaculate success represents the best possible outcome for the persona.
In combat the persona will have vanquished their opponent in any fashion they see fit.
The persona can choose to kill, wound, or render her opponent unconscious.
In skill execution the persona will enjoy a value added success.
The persona repairs the door, and learns a new skill called door repair.
These results are negotiated between the players to determine what supports the story best.

A result of +2 is a solid success.
This result is quite common. 
Solid success represents a successful outcome for the persona, but nothing special.
In combat the persona will won the fight, but the outcome is not certain.
The opponent may have run away, suffering a minor wound.
In skill execution the persona will have gotten the job done, but not one bit more.
The persona will have repaired the door, but the repair won't last forever.
These results are negotiated between the players to determine what supports the story best.

A result of -10 is a cataclysmic failure.
This result is quite rare. 
Cataclysmic failure represents the worst possible outcome for the persona.
In combat the persona will suffered total defeat.
The persona could be killed, lethally wounded, or knocked unconscious.
In skill execution the persona will failed beyond measure.
The persona could have broken the door so badly it will attract invaders.
These results are negotiated between the players to determine what supports the story best.

A result of 0 is detent.
This result is the most common result. 
Detent represents a neutral none outcome for the person.
In combat the persona continues to be locked in combat.
The fight music keeps playing and neither persona has the upper claw.
In skill execution the persona continues to work on it.
The persona has accomplished neither failure not success.
These results are negotiated between the players to determine what supports the story best.

== Outcomes 
In most cases the descriptor is an adequate outcome to get back to role playing the story.
Sometimes players need more direction.
This is especially the case in 4D2 combat where a persona can be killed outright with a negative result.
This is when outcomes come into play.
The outcomes are an added column to the Descriptors Table.
Each outcome lists a few options for the players to choose from.

.*Outcome Considerations*
. Persona
.. Outcome for the persona.
. Action
.. Outcome for the action
. Duration 
.. How long action lasts

Players are encouraged to make outcome tables to suit their style.
If the personas are constantly repairing a special drive they may want to have a modified outcome table.
There are two pre made 4D2 descriptor tables built 

=== 4D2 Maneuver Outcomes
Suggested outcomes for 4D2 result rolls.
The maneuver outcomes are divided into persona, action and duration outcomes.
Persona (P) outcomes impact the persona.
The outcome changes persona in some fashion.
The outcomes can be permanent, temporary, positive or negative.
For example, an Immaculate Success lets the player choose a new skill per her persona.
Action (A) outcomes describe how the maneuver went. 
The outcomes can be success, fail bump or complicate.
A bump indicates that the success was better than expected and bonus outcome is added onto the maneuver.
Duration (D) outcomes indicate how long the action lasts or impacts the persona.
A failed maneuver causes the persona to cool down from trying again.
The worse the failure the longer the cool down.
A successful maneuver will last a certain amount of time. 
A Barely Successful action may only stay successful for a few minutes. 

include::ROOT:partial$CH26_Table_4D2_Maneuver_Outcome.adoc[]

A result of +10 is an immaculate success.
This result is quite rare. 

.*Immaculate Success Outcomes*
* P: Choose New Skill
** The player can add a permanent new skill
* A: Success and Double Bumped
** The players can add two unexpected positives to the action
* D: Permanent
** The maneuver will last as long as beneficial.

Immaculate Success when performing first aid:
The player gets to choose a new skill for her persona. 
She may improve her first aid to +2 or add Gunshots 1 to her skills.
This is the only way that personas can get new skills.
The action is double bumped so the first aid is awarded two extra unexpected results.
The player may choose to cure the patient's cold and remove a scar as well.
Not all bumps can be used all the time.
The duration of the success is permanent and will not unravel without being intentionally unraveled. 

A result of +2 is a solid success.
This result is quite common. 

.*Solid Success Outcomes*
* P: --
** No persona outcomes.
* A: Success
** The maneuver works as expected.
* D: Hours
** The maneuver will last a few hours and may spontaneously unravel.

Solid Success when repairing a damaged wheel:
There are no persona outcomes with this descriptor.
The persona has not great insights from this experience.
The maneuver is successful and the wheel is repaired.
The wheel repair may become undone in few hours if it is challenged or the helps the story.

A result of -10 is a cataclysmic failure.
This result is quite rare.

.*Cataclysmic Failure Outcomes*
* P: Random Perm Loss
** The persona permanently loses a skill or attribute.
* A: Fail and Double Complicate
** The maneuver fails and gets worse .
* D: Months to retry
** The persona cannot try this maneuver again for months.

Cataclysmic Failure when making a disguise:
The persona suffers the permanent loss of a skill or attribute.
This a cataclysmic impact. 
Some how the persona hurt herself trying to make the disguise.
The maneuver is a failure and two complications are added.
The failure may end up making the persona easier to detect in the future, and wrecked her disguise kit.
It will be months before she tries to disguise herself again.

== Shifts 
A shift is anything that alters the result of the 4D2 mechanic.
These are almost always bonuses added to the final result of 2d6 minus 2d6.
If a persona had gun skill, and DEX attribute she may be able to shift her result +2.
What shifts can be applied for a 4D2 roll is negotiable between the players.

Shifts are very important and are the only way players can gain advantage in the 4D2 system.
So a 4D2 result of 7 would become 9. 
Or a 4D2 result of -2 would become 0.

A shift may get a persona out of a tight spot. 
A shift may wrestle a success from certain failure.
A shift cannot be used to improve the descriptor generated by the 4D2 mechanic.

A persona has a skill of door repair 2 and the 4D2 result is +8 the final result would be 10 but her descriptor would be Magnificent Success (+8) and not Immaculate Success (+10).
This is still a very successful result for the persona. 
However she does not enjoy the benefits of the Immaculate Success descriptor.

Descriptors can indicate permanent changes to persona. 
The 4D2 mechanic is balanced for +10 to be rare.
Without shifts the 4D2 system has a 0.08% (less than 1%) chance of Immaculate Success.
With the +3 shifts the chance of chance of Immaculate Success increases to nearly 3%.

If the players wish to quickly develop invincible, over powered personas then shifts can alter descriptors.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*
