= Theatrical Performance System

Everything is an maneuver in EXP.
In this context a maneuver is any persona action that has an unclear outcome.
The __unclear__ part of the outcome is determined by randomness.
Players can guide the randomness by using skills, and attempting maneuvers in their wheelhouse.

The name of this section is rooted in legacy and nostalgia. 
Formerly vocation maneuvers were determined by elaborate Performance Tables.
The Theatrical Performance System replaces Performance Tables and improves story telling.

The Performance System should be used when it makes sense.
Having players roll dice for each step that they make is extreme.
Having players talk their way through a campaign changing outcome is equally extreme.

The Theatrical Performance System uses the 4D2 Mechanic to generate randomness in maneuvers.

== 4D2 Mechanic
4D2 is both a descriptor and a joke. 
The 4 indicates that the mechanic uses 4 dice.
The 4 also indicates that there are 4 steps in the process.
The D refers to dice, and it a play on "D" in the 4d6 convention.
The 2 reflects that the mechanic has two directions.
The joke is that 4D2 sounds like 42.
Fourty Two is the answer to the question.
The 4D2 Mechanic gives the answers to questions you don't understand.

The 4D2 Mechanic uses four six sided dice to guide the story in the Role Playing System.
The 4D2 Mechanic is a bespoke decision tool for EXP's Role Playing System.
4D2 replaces Attack Rolls, Performance Rolls, Attribute Rolls, Saving Rolls, Sphincter Rolls and more.

In the Theatrical Combat System the 4D2 Mechanism is used to guide the combat story. 
Players ultimately guide the outcomes that the mechanic generates.

.*Four steps of 4D2 Mechanic*
. get *Result* from 4D2 mechanic
. get *Descriptor* from Result
.. Apply the Shifts
. get *Outcome* from Descriptor
. Return to story telling

== 4D2 Mechanic Results
The result is the number produced by rolling two pairs of competing six siders.
The player rolls 2d6 and generates a number between 2 and 12.
Another player rolls 2d6 and generates another number between 2 and 12.
The second roll is subtracted from the first roll.
The curve is quite beautiful.

:art: fourDtwo.png
:width: 350px
:snark: Thank you anydice.com
:artist: Jasper Flick
:date: 2020
:license: AnyDice.com 

include::ROOT:partial$articulate.adoc[]

=== 4D2 Result Generation
.Outcome = 2d6 - 2d6
****
Range is +10 to -10. Positive is positive. Negative is negative. Zero is neutral.
****

The 4D2 mechanic generates a smooth curve of results between +10 and -10.
The result is player centric. 
Positive numbers indicate success and negative numbers indicate failure.
The most common result from this mechanic is 0.
0 represents balance, detent or ongoing struggle.
+10 represents the epitome of success for the persona.
-10 represents the epitome of failure for the persona.

The 4D2 Mechanism Result is a numeric value.
Each possible outcome is linked to a descriptor that the player use to guide the story.

=== Example 4D2 Results
The 4D2 Mechanic Result can be generated by rolling one six sider four times.
The more dice rolled at once the more efficient the mechanism.
Most commonly one player rolls two six siders (2d6) and another player rolls the competing two six siders (2d6).
All four dice can be rolled at once by assigning plus to one coloured pair and minus to another coloured pair.

.*Some example results*
* The player rolls 2d6 and the sum is 12. 
The opposing 2d6 roll has a sum of 2.
The 4D2 Mechanic Result is +10.
+10 is the best result for the player's persona.

* The player rolls 2d6 and the sum is 9. 
The opposing 2d6 roll has a sum of 8.
The net roll is +1.
This will result in a very slight win for the player's persona.

* The player rolls her 2d6 and the sum is 4. 
The referee rolls her 2d6 and the sum is 10.
The net roll is -6.
This will result in a very bad outcome for the player's persona.

Every group will develop it's style for generating 4D2 Mechanic Results.
The most common is rolling 2 pairs of different coloured dice.
One pair is positive and the other pair is negative.
For example, the positive six siders could be white and the negative six siders could be red.

== 4D2 Mechanic Descriptors
The 4D2 Mechanic Result can be used as a raw number to determine what happens to the persona.
There is also a descriptor table that correspondingly dramatic descriptors for every result.
The 4D2 Mechanic Result is converted to a descriptor for fun and efficiency.
For example, +10 is an Immaculate Success and -10 is a Cataclysmic Failure.

include::ROOT:partial$CH26_Table_4D2_Descriptors.adoc[]

The descriptors help __guide__ the players describe the outcome of the maneuver.
A positive result (number) yields a positive success descriptor.
A negative result (number) yields a negative failure descriptor.
The descriptor may be all the players need to move the story along. 
For example, a Vet is trying remove a splinter from a feline's paw.
An Immaculate Success descriptor would guide the players to tell a story with a happy result.

.*Some Example Descriptors*
* A result of +10 is an Immaculate Success.
This descriptor is rare. 
Immaculate Success represents the best possible outcome for the persona.
The persona does not just successfully complete her maneuver, but does so with bells on.
The descriptor guides the players in describing the performance story.

* A result of +2 is a Solid Success.
This descriptor is quite common. 
Solid Success represents a positive outcome for the persona, but nothing dramatic.
The maneuver was successfully completed, however it may not last too long.
The descriptor guides the players in describing the performance story.

* A result of -10 is a Cataclysmic Failure.
This descriptor is quite rare. 
Cataclysmic Failure represents the worst possible outcome for the persona.
The maneuver was a failure and the consequences reach beyond the actual maneuver.
The descriptor guides the players in describing the performance story.

* A result of 0 is detent.
This descriptor is the most common. 
Detent represents a balance between the the procedure and the persona.
The persona has neither failed nor succeeded and the maneuver is ongoing.
The descriptor guides the players in describing the performance story.

== 4D2 Mechanic Outcomes 
Often a descriptor gives adequate guidance to the players telling the story.
For common 4D2 Mechanic uses there are also Outcome Tables.
Outcome tables include some common results for their associated descriptors. 

=== 4D2 Performance Outcomes
Suggested outcomes for the 4D2 Mechanic in the Theatrical Performance System.
The outcomes are not just about the maneuver, but how the outcome affects the persona.
A persona can learn a new skill for very successful outcomes.

include::ROOT:partial$CH26_Table_4D2_Maneuver_Outcome.adoc[]

.*Some Example Outcomes*
* The descriptor of Immaculate Success (+10) is quite rare.
The persona can choose a new skill. 
The success comes with some additional, unexpected benefits. 
The results of the maneuver will last until unwound.

* The descriptor Solid Success (+2) is quite common.
The persona earns no skills with this outcome.
The job gets done.
However not the best work ever.
The results of the maneuver will last for hours.

* The descriptor Cataclysmic Failure (-10) is quite rare.
The persona has a skill knocked out of their head.
The failure extends beyond the maneuver and has additional complications.
The persona will be be gun shy from trying again for months. 

Immaculate Success when performing first aid:
The player gets to choose a new skill for her persona. 
She may improve her first aid to +2 or add Gunshots 1 to her skills.
This is the only way that personas can get new skills.
The action is double bumped so the first aid is awarded two extra unexpected results.
The player may choose to cure the patient's cold and remove a scar as well.
Not all bumps can be used all the time.
The duration of the success is permanent and will not unravel without being intentionally unraveled. 

A result of +2 is a solid success.
This result is quite common. 
Solid Success when repairing a damaged wheel:
There are no persona outcomes with this descriptor.
The persona has not great insights from this experience.
The maneuver is successful and the wheel is repaired.
The wheel repair may become undone in few hours if it is challenged or the helps the story.

A result of -10 is a cataclysmic failure.
This result is quite rare.
Cataclysmic Failure when making a disguise:
The persona suffers the permanent loss of a skill or attribute.
This a cataclysmic impact. 
Some how the persona hurt herself trying to make the disguise.
The maneuver is a failure and two complications are added.
The failure may end up making the persona easier to detect in the future, and wrecked her disguise kit.
It will be months before she tries to disguise herself again.




==  Shifts
Shifts are similar to bonuses or penalties.
A shift is anything that moves the Descriptor of the 4D2 Mechanism Result.
A Shift moves the Descriptor and changes the Outcome of the Result.
A Shift of 2 would move a Solid Success (+2) to an Outstanding Success (+4).

Shifts are very important and are the only way players can gain advantage in the 4D2 system.

Some groups immediately add the Shift to the Result that the player generates.
There is a risk that this shortcut will lead to over-powered personas.
A shift of +1 triples the chance of the persona learning a new skill in combat.
A persona has a better chance of combat success using Shifts.
However using the adjusted outcome will lead to excessive skill acquisition.

=== Example Shifts
Shifts come from the persona's attributes, abilities and skills.
However literally anything can become a shift if the players accept it.
If her persona is juggling a player could use DEX as a shift.
When healing a wound she could use her quick fix skill as a shift.
A glorious description of how a lock is picked could earn a shift.
These shifts are all added together.

For example, a persona is in a trying to identify an alien. 
She has Herbivore skill and AWE Attribute.
She can Shift her 4D2 Outcome by +2.
This Shift of 2 could move a Solid Success (+2) to an Outstanding Success (+4).

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

Sometimes there are counter shifts that the player is challenged with. 
For example, juggling in a strong wind may remove her DEX attribute shift.
Negative shifts can be applied if the players feel it is appropriate. 
This makes a powerful enemy more difficult to defeat in combat. 

.*List of Example Shifts*
* INT attribute and DEX attribute in removing a burrowing worm (+2 Shift).
The player generates 7 on the 4D2 Result.
The outcome is adjusted from Majestic Success (+7) to Wonderous Success (+9).
The persona removes the worm very successfully (+9).
Wonderous Success (+9) has a bump so the worm lives to study later.
However she can only learn a Temporary Skill (+7).

* DEX attribute, sprint ability and a story about high school athletics (+3 shift).
The persona is running to catch a falling vase.
The player generates -1 on her 4D2 Mechanic Result.
The outcome is shifted from a Minor Failure (-1) to a Solid Success (+2).
There are no persona skills listed on any of these outcomes.
The shift turned failure into success.
Nothing more.



