= Theatrical Combat

Modified Four D Two just for combat.

== Four D Two Result
.Persona Effect = 2d6 - 2d6
****
Generates a range from +10 to -10. Positive is positive. Negative is negative.
****

== What a lovely spread

:art: fourDtwo.png
:width: 250px
:snark: Thank you anydice.com
:artist: Jasper Flick
:date: 2020
:license: AnyDice.com 

include::ROOT:partial$articulate.adoc[]

include::ROOT:partial$CH00_Table_4D2.adoc[]




== Tale of Two Combat Systems

To try to simulate all of the potential occurrences in modern combat is impossible.
Some gamers like to account for every possible physiological, geographic, and technical aspect humanly possible.
Others want nothing more than an arbitrary, but fair die rolling system for this reason EXP has two distinct combat systems.
Both combat systems are integrated into the technology of the game, and both are fun to play.
They are fun to play for different reasons.

EXP offers both a theatrical, and a tactical combat systems.
The theatrical system is presented first, because it is easier to learn.
Both formats explain in detail all the elements of their combat system.
This way neophytes can start out with either system.
It is recommended that new groups start out with the theatrical system.
It prompts fewer (i.e.
leaves more time for) potentially argumentative situations.
Eventually you'll find that one system will best suit your group.
It is expected that most groups of gamers will find that the inadequacies of the theatrical combat system will force them to look to the tactical one for increased realism.
The artifact technology section is better suited to the tactical combat system.

== Theatrical Combat System

This combat system does not require figures or detailed maps.
The process is very fast, compared to the tactical combat system, and leaves more time for vivid descriptions from the referee, and the players.
More importantly it leaves more time for the campaign to focus on things other than combat.
This is definitely the easier of the two combat systems to learn, but it not necessarily designed just for beginners.
Experienced players that don't like combat, and don't feel it is worth the energy meticulously resolving combat may prefer the theatrical combat system.
See http://expgame.com/?page_id=296[Chapter 26: Theatrical Combat].

== Tactical Combat System

This game system for resolving lethal personal combat is much more detailed than the theatrical one, but it would be false to say that it is more realistic.
The tactical combat system is delicate balance between playability and realism.
It considers factors like movement terrain, attributes, and weapon types for each to hit roll.
It is best played with tokens, miniature figures, placed on a grid (hex or graph paper).
This way terrain, and ranges can be carefully monitored for as much detail as humanly possible.
See http://expgame.com/?page_id=298[Chapter 27: Tactical Combat






There are often alternatives to combat, and more mature players will avoid combat at most costs, in part due to risk to their personas and in part due to the nature of advanced role-playing.
However, combat is fun, and there are classes that are entirely devoted to training and engaging in combat.
The theatrical combat system is presented here to resolve such violent encounters in a simple and fun manner.

== Attacks and Defenses

The theatrical combat system is very simplistic.
Although if one is unfamiliar with the idea of role-playing games, then even the theatrical system will appear completely alien.
The to hit roll is one of those concepts completely unique to role-playing games.
The to hit roll is made on kilodice, and the higher the dice roll the better the attack.
In terms of the game the persona is trying to damage her target.
Let us consider a persona that is trying to crunch an attacker with her sword.
The persona will swing the weapon at high speed, hoping to deceive the defender and hit her in some place that will do damage.

*Attacking*: The player doesn't choose the attack that her persona makes, but rolls dice to see if the attack was successful.
The player doesn't say, My persona hits her in the head, she would say I am going to try and hit her with my sword, and then would make a to hit roll.
If the to hit roll was very high, it is more likely that she will hit the target, but not necessarily in the head.
The most important goal of combat is to score a hit.
Attempting to score a hit depends on many factors: the attacker's combat skills, and the defender's defences.
A combat system balances these elements to determine an attacker's chance to hit.

The player makes a to hit roll for any type of weapon that she is using.
If the weapon is a club, gun, rock, punch or tackle the player must always roll kilodice to determine the effectiveness of her persona's attack.
The results of the attack depend on the armour rating of the target and the damage inflicted by the weapon.

The player rolls to hit for her persona.
The to hit roll indicates the accuracy of the particular attack chosen by her persona.
It is expected that the persona will make every effort to hit, choosing what she expects is the best hit location, speed and combination.
The random die roll determines how good a choice this was.
A high roll, anything above 600, indicates that the persona made good combat decisions and is more likely to hit.
A low roll, anything below 500, indicates that the persona made a bad combat choice.
One that was either parried, deflected or dodged by the target.

*Defending*: Dexterity, armour type, hide structure, body structure, and many other factors are combined into one factor called the Armour Rating.
The armour rating is a quantitative value that represents the quality of the defender's protection.
The higher the armour rating value the better the protection it offers.
The persona has an armour rating too, and when the anything attacks her her armour rating functions to protect her.
The armour rating of aliens is determined by their hide, speed of movement and structure.
Robotic armour rating depends on their case construction.
All anthro personas have a standard armour rating, which is based mostly on their ability to avoid being hit.
See more about armour rating (AR) in http://expgame.com/?page_id=302[Chapter 29: Armour Rating].

== Anatomy of a To Hit Roll

An attacker generates a roll to hit by rolling a kilo‑ die (hence to hit roll'
).
The random integer that is  generated accounts for the enormous number of possibilities that cannot be accounted for on a normal gaming scale.
Armour deflection, air currents, velocities, tensile strengths, concentration levels and luck, are just some examples.
These factors are so complex, and therefore unpredictable, that they might as well be considered random.
The random roll to hit simulates this fact, and it must be re-rolled for every attack.

*Rolling the Dice*: The higher the roll the better.
The player must roll a number higher than the target's combined defences.
These combined defences is called armour rating (AR).
Eg: If some creature were to have an armour rating of 580, an attacker would have to roll equal to or higher than 580 before a hit could be scored.
Thus, any roll between 580 and 1000 would indicate a hit.
Any to hit roll less than 580 (001 to 579) would not count as a hit.
This is called a Miss.
A miss indicates nothing more than the loss of ammunition, or a battery drain.
If kilodie are daunting the theatrical system can be used with d100 or d20 or d10, depending on your penchant for arithmetic and rolling up new personas.

*Frequency of Attacks*: A to hit roll can be made, depending on the weapon, every 2 seconds.
This amount of time is called a Unit.
The unit is the basic value of combat time.
Combat time is imaginary time, or scaled time.
Two seconds of game time could actually take several minutes of real time discussing rules, referring to books, or describing surroundings.
Each player should get to have her persona act during each unit.
The unit ends once everyone has had a turn to act.
The unit is the equivalent of a game turn that one would expect in any game with multiple players.
In the theatrical combat system the personas roll to hit first, followed by the referee personas.

If a player were to roll 657 as a to hit roll for  her persona trying to damage an alien with an armour rating of 650 she would score a hit.
If the player were to make a to hit roll of 657 against another alien which has an armour rating of 660, the to hit roll would be a miss.
The second alien (AR 660) is considered better at defending itself in combat that the first alien (AR 650).
When the enraged alien attacks the persona the referee will make a to hit roll against the persona's armour rating (AR).
Combat continues in this back and forth fashion, until someone is smart enough to run away, or unlucky enough to get killed.

*Hits and Damage*: At first a successful to hit roll will be when the players recall how to work kilodice.
In terms of the persona a successful to hit roll will mean that she has connected with her sword and seriously hurt her target.
Remember that this is lethal personal combat, and it is a system for resolving fights to the death between anthropomorphs, machines and aliens.
As we have stressed above a successful to hit roll is called a hit and damage must be generated.

When a player makes a roll higher than her target's armour rating it is called a Hit.
A hit means that the persona has succeeded in harming her target and a damage roll is in order.
For instance a sword needs a solid hit, and a bullet must hit a none-deflecting surface.
Damage is determined by the weapon being used.
For example a mace will crunch for a random damage of 1-6 hit points.
This means that the referee will remove 1-6 hit points from the player's target.
The more hit points removed the more damaged the target is.
This means the more likely it will run away or die.

== Damaging Opponents

Hit points (HPS) reflect the target's ability to withstand physical damage.
Hit points (HPS) are a simple way of quantifying body construction: how well is the brain protected;
the amount of protective tissue around vital organs;
and the connective tissue's ability to resist tearing and shattering.
There are other less gruesome components of hit points.
These include the innate skill of the target's body, as a whole, to react to threat, and just plain old luck.
These components are combined as a single number which is reduced each time the target is hit.
Targets that lose too many hit points will die.
Hit points (HPS) are a general indicator of a persona's overall hardiness.
The more HPS the creature has the better condition she is in, but the more often she is hit the more HPS she loses and the worse her condition becomes.
When a target is hit, it is damaged by removing hit points, the more deadly the weapon the more hit points it can remove.

When a hit has been scored the player gets to roll damage on the target.
The amount of damage inflicted is dependant on the weapon used by the attacking persona.
The more deadly the weapon the more damage it can inflict.
The amount of damage inflicted is rolled randomly by the player.
EXP is not a game that is devoted to the gruesome destruction of body tissue, and the amount of damage a target can withstand is represented by its hits points (HPS).

The amount of hit points that a weapon can remove from a target'
when it hits is called its Damage.
The damage inflicted by weapons such as swords, clubs and bows is discussed in chapter 28, Weapon.
Rifles, pistols, grenades, lazers and other weird technological weapons have their damages listed in the technology section.
A sword can inflict 1-8 hit points of damage, but an extra high powered lazer rifle could inflict 5-50 hit points in damage.
The lazer is much more deadly than the sword.

A mercenary persona, wielding a sword, and a biologist persona, wielding an extra high powered lazer rifle, both decide to attack the same target.
They both score hits with their to hit rolls on the unlucky target.
Let's say their target has 43 HPS.
The player running the mercenary rolls a 4 on a d8 (a sword does 1-8 HPS damage), and the referee would subtract 4 hit points from the target's total.
The target now has only 39 HPS.
The biologist also scored a hit so her player rolls 5d10 (her persona's lazer rifle does 5-50 HPS of damage).
She rolls 8, 5, 9, 10, and 4 for a total of 36 hit points damage.
The referee would subtract 36 hit points from the target's remaining 39 HPS.
After the attacks by the mercenary and the biologist the target has only 3 HPs left.
Success in lethal personal combat is achieved by removing the HPS of the targets and leaving them unconscious or dead.

The hit point doesn't convert to some unit of energy--like an erg.
However, the hit point is a constant value.
Any anthro, alien, or robot at 10 hit points (HPS) can only withstand 10 HPS of damage.
What varies is how each family type is affected upon reaching 0 HPS.
How aliens and robots respond to very low hit point totals (less than 1) is covered in their respective chapters.
How humanoids respond to particular HPS totals is detailed in http://expgame.com/?page_id=48[Chapter 3: Attributes].

*Combat Success*: Success in lethal personal combat is to stay alive.
The persona must disable her opponent in order to do this though.
Once a target has had enough hit points removed it will fall unconscious, and no longer pose a threat to the persona.
Often there will be several opponents and the process of killing all of them may be quite time consuming.

== Combat Movement

There is no movement in theatrical combat.
Players and referee can pick their targets from a list or description.
Running away and catching up with targets are left to the theatrical description of the scenario.
If the group likes to use markers or table top minis to play the tactical combat movement system can be used.

== To Hit Roll Bonuses

The theatrical combat system does not have a combat table.
However personas can still earn bonuses to their to hit rolls.
To hit roll bonuses include skills and experience that make a persona more likely to hit her target.
This is done by adding numbers to the player's to hit roll.
The theatrical combat system only has basic hit roll bonuses that are easily included in combat.

When a persona becomes more and more experienced she is expected to get better at combat.
This improvement in the persona is represented by a bonus that is added to the player's to hit roll.
This bonus is added to every to hit roll, whether it be a punch, shot gun blast, later attack, or spit.
The bonus is dependant on the persona's class and experience level.
To determine a persona's to hit bonus consult Table 26.1, Theatrical Level To Hit Bonus.

If a persona were a 4th level mercenary the player would add 200 to every kilodie roll that she made.
A kilodice roll of 533 would be increased to 733, and a kilo dice roll of 856 would be increased to 1056.
This makes it more likely that the player will roll higher than the target's armour rating, and therefore it will be more likely that the persona will hit her target.
A 5th level biologist would have a to hit bonus of 75.

If the 5th level biologist and the 4th level mercenary were in the same expedition, and were fighting a target with an armour rating of 880 (quite high) the player running the biologist would have to roll 805 or more to score a hit, but the mercenary would only have to roll 680 or more to hit.

// insert table 229

The difference in the bonuses per level depends on the class of the persona.
Players running personas with combat classes, like mercs and spies, add more to their to hit roll because their personas are better trained and skilled in combat than the non-combat persona classes.

This is the greatest difference between the tactical combat system and the theatrical combat system.
The tactical combat system has a series of detailed bonuses that are added to every to hit roll that a player makes.
The bonuses represent attribute skills, class skills', and experience level.
There are other bonuses that consider terrain, cover, and flanking attacks.
See http://expgame.com/?page_id=314[Chapter 35: Combat Adjustments].

== Combining The Combat Systems

The theatrical combat system is not meant to be an entity unto itself.
It is by no stretch of the imagination a complete combat system designed to adapt easily to any obscure situation that can arise.
For that matter neither is the tactical combat system.
Both the systems are expected to be adapted by the referee and players to a degree which supports the level of realism desired, but remain playable.
The theatrical combat system is a good start for getting used to the combat intricacies of EXP It is very easy to add parts of tactical system in as the campaign proceeds, keeping them as permanent rules in combat or discarding them when not needed.

A lengthy discussion of the melding of the two combat systems would be lost to those who do not have a reasonable grasp of how both systems work, but here are some pointers on what you may find most important to work out.
The tactical combat system has attribute bonuses as well as level bonuses.
This means that the persona's attributes, can be added to the player's to hit rolls increasing the chances of stronger and more dextrOus personas to hit their targets.
There are also weapon damage adjustments for using hand to hand weapons that are based on physical strength.
This increases the damage done by physically strong personas.
Damage adjusters are so easy to employ that most gaming groups will include them when they use the theatrical combat system.

The tactical system has detailed rules for weapon proficiencies.
In the theatrical system personas can use a brand new weapon as well as a one they are well practised with.
Proficiencies ensure that personas will be better with familiar weapons than with newer ones by having bonuses for proficient weapons, and bonuses for non-proficient weapons.
+ The tactical combat system has weapon types.
Each combat weapon is classified into one of three weapon types.
Each weapon type functions differently in combat, relating to number of attacks per unit, range, damage adjustment, and to hit bonuses.

The tactical combat system has combat absolutes by having maximum allowable to hit rolls.
This means that the personas cannot have a to hit roll higher than a certain number.
The maximum roll increases as level increases, and it ensures that high level personas will be better than low level personas in combat.
If any of these  rules sound like they would add to the fun of playing EXP, then looking at the tactical combat system is highly recommended

== Choosing Other Dice

The theatrical combat system replaces pretend realism with speed.
Your role playing group may find the kilo die daunting.
In the theatrical system you can just change that.
Every rule and adjustment for combat is based on the tactical system.
It is just a matter of dividing the tactical numbers to be able to use a different die type.
The most common combat die system on earth is the 1d20.
To use create a theatrical system that uses d20 just divide everything in the tactical system by 50.
You will get really good at dividing stuff by 50.
You must round down after the division is completed.
So an armour rating of 700 would become 14, and a 115 to hit roll bonus would become +2 to hit.
You will quickly see details disappear with the smaller the die size you choose.
This way less factors are included in combat and it becomes faster and faster.

// insert table 228


== No Initiative
This initiative system is similar to the turn system employed by most board games.
All play is carried out in a clockwise direction around the table, or room.
The play moves from one player to the next, treating the referee as another player.
Each player is responsible for the actions her persona and the referee will be responsible for actions of several referee personas.
Each player receives one move and one attack during her turn.
Players must complete all actions during their turn, and cannot act until it is their turn again, or until combat is completed.
The referee may get one move and one attack for every persona that she is responsible for.
This is a good initiative system for players and refs still mastering the combat system.
Experienced players will quickly tire of this initiative method, unless the role-playing is particularly spectacular.





== Theatrical Initiative 
Theatrical initiative is the most common form of initiative found in role-playing combat.
The turn sequence of theatrical initiative is determined by the the roll of a die.
One player from the expedition makes a die roll representing the entire expedition, and the ref makes a die roll representing the referee personas.
Initiative die rolls can also made by other groups involved in combat (police forces, or terrified civilians).
Whoever has the higher die roll gets to move and attack first.

Lets consider an example using a ten sided die.
If the referee rolled 7 on her d10 initiative roll, and the expedition rolled 3 on their d10 initiative roll then the referee personas (run by the referee) get to act first.
This is called winning the initiative, and the referee won the initiative, and all her personas get to move and attack the personas of the expedition.
It is generally considered advantageous to win the initiative in this system because any targets that are killed, knocked unconscious or stunned cannot attack in that unit.
Initiative should not be confused with ambushing a persona.
Initiative is an in combat roll, and the personas that have won initiative are simply acting before other personas in the same unit, and they have no element of surprise whatsoever

Most often the order of action in a theatrical initiative system will simply be a go around each player based on their seating arrangement.
If the players are concerned about this then the order of action of the players can be determined by their DEX attributes.
The persona with the highest DEX acts first, and the persona with the lowest DEX acts last.
Each persona may move/attack, attack/ move, or attack while moving.
The initiative roll also determines when personas can carry out noncombat activities, like changing equipment, class skills and mutations during combat.

For example, and expedition of 3 personas (called Abel, Babel, and Cable) has gotten themselves into a scuffle with 5 aliens.
The expedition members have dexterities of 12, 14, and 9, respectively.
The aliens all have the same dexterity value.
In the first unit of combat the ref rolls 6 on her d10 initiative roll, and the player representative rolls an 8 on her d10 initiative roll.
The order of play is Babel (DEX 14), then Abel (DEX 12), then Cable (DEX 9), and then all of the aliens that the referee is making decisions for.
Aliens disabled when the personas attacked cannot attack during their turn.
In the next unit the ref rolls 9 for initiative, and the expedition rolls 3 for initiative.
The order of play is all the referees remaining aliens, then Babel (DEX 14), then Abel (DEX 12), then Cable (DEX 9).
Any personas knocked unconscious or killed cannot attack during their turn.
The last possible variation is if the ref and the player were to roll the same value.
They would either re-roll to decide an initiative winner, or they would move around the table with everything happening on the combat field simultaneously.
Simultaneous initiative indicates all attacks are simultaneous, and any paths of movement that have crossed are assumed to have collided at their intersection.

All movement and attack sequences are the same for the referee as they are for the players.
The referee may play homogeneous groups (opponents with all the same DEX attributes) in any order that she sees fit.

*Gaming Initiative*: The ref must watch for players who repeatedly miss their turns, and demand action after the rest of the expedition has acted.
The refs best defense against this problem is her ruthlessness.
It is most likely that the player honestly missed her turn, but this is no excuse.
Players should pay attention, and those players that miss their turn during combat are subject to having their persona stand hopelessly confused on the battlefield.

