= Persona Generation

IMPORTANT: *Welcome friend of EXP. You are in an unfinished section of EXP. Please ignore.*



// choose 

Use the data from Roll playing with out the burden


Personas

Name : player choice

Family : player choice or 1d6
1-4 Anthro
5 Alien
6 Robot

Family Type: 
Anthro choice or 1d8
Alien medium sized - roll desc
Robot medium sized - roll type, desc

Attributes: choose one or
1 AWE
2 CON
3 DEX
4 INT
5 CHA
6 PSTR

HPS do not exist

Mstr and knite game based
Mstr must get mortal wound or death 

Vocation: Choose one or Nothing or
Awe Biologist
Cha Veterinarian
Con Nomad
Dex Spie
Int Mechanic
Pstr Mercenary

Mstr and knite game based
Mstr Knite (cannot be picked)

Mutations: choose, irradiate
Con - physical
Int - mental

Skills: pick one from or roll

TOYs: 
Biologist - any
Veterinarian - vet
Nomad - misc eq
Nothing - treasure
Spie - misc weap
Mechanic - Any
Mercenary - Gun

Performance 4D2 successes (skill, att.)
Combat 4D2 results (death, mstr)
Movement grapple, close, near, far, distant
