= Alien Evolution

Alien is the colloquial term for the family diversidae.
Aliens encompass all non-anthropomorphic organic life forms with consciousness.
The process of generating an alien persona is random.
The player is creating not just her alien persona but an entire species. 
The term for creating an alien persona is "evolving" an alien persona. 

:art: alien_duck_dino_grasshopper_conifer.png
:width: 450px
:snark: Head: duck, Torso: pterosaur, Arms: grasshopper, Legs: conifer
:artist: Nelson
:date: 1992
:license: CC BY-SA 4.0
:description: An alien composed of duck head, dino torso, grasshopper arms and conifer legs.
include::ROOT:partial$articulate.adoc[]

include::role_playing_system:partial$persona_record_alien.adoc[]

.*Alien Evolution*
. <<_attributes,Attributes>>
. <<_appearance,Appearance>>
. <<_movement,Movement>>
. <<_evolutations,Evolutations (Mutations)>>
. <<_combat,Combat>>
. <<_tool_usage,Tool Usage>>
. <<_society,Society>>
. <<_vocation,Vocations>>
. <<_artifacts,Artifacts>>
. <<_name,Name>>
. <<_history,History>>

== Attributes
The standard attributes of EXP are present in all personas.
In the Role Playing System, players only record those attributes at which the persona excels.
A persona can have a blank attributes section and function fine.
Another persona may have the attribute Intelligence. 

====
*Attributes:* INT
====

The persona's Intelligence attribute is worth noting. 
A persona can excel at more than one attribute.

====
*Attributes:* INT, DEX
====

There is no score assigned to an attribute. 
The persona either excels at an attribute or not.
The attributes help the personas when they undertake maneuvers.
For example, a persona with STR would be better at lifting than a persona with INT.
When two personas have the same attribute, then no advantage is given.
If two personas grappling both had Strength, then neither gains an advantage.
However, if a persona with STR and DEX is grappling with a persona with just STR, they get a DEX advantage.

These advantages are called shifts and increase the chance of success with the 4D2 Mechanism.

Size::
Every player evolving an alien makes a size roll. 
Aliens can have variable sizes. 
Size can be used as an advantage if two personas have STR.
The personas with the larger size and STR will gain an advantage over the smaller persona with STR.
In the Role Playing System, the player does not record numerical wates and only uses the descriptor (Tiny, small, medium, large, gigantic).

include::role_playing_system:partial$alien_size_qualitative.adoc[]

Most Excellent Attribute::
The player rolls once to determine the most excellent attribute of her alien persona.
If an alien is Large or Gigantic, and the table approves, the persona may get a Strength attribute at no cost.

include::role_playing_system:partial$best_attribute_table.adoc[]

Awareness::
Awareness indicates how aware a persona is of her surroundings. 
It indicates how well is the persona's brain connects to the outside world. 
The attribute is a collective measure of the persona's sensors. 
AWE includes senses like hearing, vision, smell, touch and taste. 
Awareness does not include the sixth sense or a sense of style. 
The abbreviation for Awareness is AWE.

Charisma::
Charisma is charm, looks and sociability all combined into one value. 
A high Charisma represents a high proficiency at getting along with other personas. 
This attribute is universal, so any persona with a high CHA would be socially adept. 
A persona's Charisma is crucial for inter-persona interactions.
The abbreviation for Charisma is CHA.

Constitution::
Constitution represents a persona's internal physique.
CON is a combination of wellness, immunity, energy extraction, healing ability.
A high CON is better to repel disease, resist poisons, and repair damaged tissue.
The abbreviation for Constitution is CON.

Dexterity::
Dexterity represents the connection between the brain and the outside world.
Agility, balance, eye-hand, reflexes and running speed are components of Dexterity.
A high DEX person could run faster, dance better and quicker reflexes.
Dexterity would help the persona catch a priceless vase or dive through a closing door.
The abbreviation for Dexterity is DEX.

Intelligence::
Intelligence indicates the smarts of the persona.
Elements of INT are memory, deduction, creativity, adaptability and their synergism. 
The higher the Intelligence of the persona, the smarter she is.
The abbreviation for Intelligence is INT.

Mind::
Mind exists as an attribute.
Players cannot roll Mind as a most excellent attribute.
Players acquire MND through a story set out by the referee.
The players will decide if the persona has earned the MND attribute.
The abbreviation for Mind is MND.

Strength::
Strength represents force the persona can generate to get work done. 
STR is a combination of leverage, power and physique. 
Strength determines how much the persona can lift or damage by brute force. 
STR helps kicking open doors, breaking bonds, or crushing beer bottles.
The abbreviation for Strength is STR.

Hit Points::
There are no hit points in the Role Playing System.
Combat and damage are both absolute and descriptive. 
There is no quantitative measure of well-being like 32 hit points out of 42.
Personas are damaged in combat by losing attributes, skills and abilities instead of hit points.
When the 4D2 Mechanic generates a Cataclysmic Failure, the persona can lose an attribute, skill or ability.
Extreme failures on the 4D2 Mechanic can mortally wound or kill the persona.
The abbreviation for hit points is HPS.

Social Standing::
There is no Social Standing in the Role Playing System.
The players must role play social interactions in the Role Playing System (go figure).
The abbreviation for Social Standing is SOC.

EXPS and Level::
There are no Experience Points or Experience levels in the Role Playing System. 
Personas earn additional attributes, skills and abilities instead of experience points or levels.
The 4D2 Mechanic can generate new attributes, skills or abilities.
This process replaces experience points and experience levels.
The abbreviation for experience points is EXPS.

== Appearance
Aliens are incredibly diverse.
Hence their family name diversidae.
Alien appearance is generated by generating four components and mashing them together.

=== Head Part
The alien's head part _usually_ stores the alien's brain and sensors.
The head is _usually_ located at the front of the alien.
Record the movement letters (l, a, w, s) associated with the head part.
The player may add an optional head adornment later.

=== Torso Part
The alien's torso part _usually_ stores the alien's vital organs.
The part does not indicate the types of vital organs, but they are most likely in the torso.
Record the movement letters  (l, a, w, s) associated with the torso part.
The player may add an optional torso adornment later.

=== Arms Part
The alien's arms part _usually_ indicates the persona front limbs and articulators.
The arms part has no impact on whether the alien is a tool user or not.
Record the movement letters (l, a, w, s) associated with the arms part.
The player may add optional grabby adornments later.

=== Legs Part
The legs part _usually_ indicates the primary way the alien gets around.
Record the movement letters (l, a, w, s) associated with the legs part.
The legs part does not solely determine alien locomotion.
If an alien can fly and run, it will have the parts for both. 
Often an alien's legs will not be legs at all but flukes, flippers, bulbs or blobs.
If the alien has a snake's legs, it slithers about.
If the alien has fish legs, it may wiggle or fin itself about.
If the alien has parrot arms and fish legs, it can still fly and slither.

include::aliens:partial$alien_shape_body_parts.adoc[]

== Movement
The alien appearance determines what kind of terrain she can move through.
Some aliens will be able to fly or swim. 
If the alien has any animal parts that swim the alien will be able to swim.
If the alien has any animal parts that fly the alien will be able to fly.

If the table cannot decide on whether an alien can fly or swim they may refer to the bracketed letters on the table.
These bracketed letters help determine the movement types of the alien.
The Crab (lw) body part has l and w, and the Moth (a) body part only has a.
The crab can move on land and in water, and the moth can move in the air. 

.*Movement Types*
* l - land borne can move on land
* a - air borne alien has flying ability
* w - water borne alien has swimming ability
* s - sessile, non-moving but indigenous

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Evolutations
Alien mutations are natural abilities that the alien has evolved over time or in a vat.
Alien mutations can only be beneficial or useless. 
An alien will not evolve themselves a defect.
Evolved mutations that are part of a species are called Evolutations.

.*Mutate Now. Like Darwin said.*
* CON attribute personas are assigned one non-defective Phenomic Mutation.
* INT attribute personas are assigned one non-defective Psionic Mutation.

The player heads to the designated mutation section and generates a random mutation.
If the players are diligent, the referee may allow players to choose their alien's mutation.
Keep in mind that some mutations are incredibly powerful and can influence game balance.
For more information about mutation types jump to xref:wetware:a_introduction.adoc[Mutations,window=_blank].

== Combat
Aliens can have as varied types of attacks as all the creatures on mundane terra. 
Unlike anthros and robots aliens can have natural ranged and multiple attacks. 
If the table agrees an alien persona may have multiple attacks if any of its body parts could have multiple attacks.
For example, octopus arms may allow the alien to attack and use multiple limbs at once.
This would be for natural alien attacks, and would not allow an alien to use multiple weapons at once.

=== Attack Frequency
The attack frequency is how often the alien can use her natural attacks in each unit.
Attack frequency does not apply to artifact weapons or devices.
The alien can use only her natural attacks for multiple attacks. 

=== Attack Types
The alien attack types the standard attack types found in EXP.

include::role_playing_system:partial$alien_attack_types.adoc[]

Strike attacks are thrusting, striking attacks powered by the alien's brawn.
These could be bites, punches, stabs, squishes, slashes, pecks, or scratches.

Fling attacks are ranged attacks powered by the alien's brawn.
These could be acidic spittle, flying quills, ejected spines or darts.
Fling attacks have a range and shoot like an arrow.
These attacks are not long-range attacks, but close combat is not required.

Shoot attacks are the rarest and most alien naturalized attack types.
The alien has evolved a self-propelled powered attack that it controls.
These are attacks like lazer eyes or rapid-fire bone bullets.
Shoot attacks appear naturalized but function like a weapon from the Gun Section.

== Tool Usage
Tool ability determines whether an alien species can use artifacts or not.
It would be very unusual for a player persona alien to be a none tool user.
None tool using means that the player's persona is local flora or fauna. 
Only a most experienced player would be able to play local flora or fauna as a persona.
The players may allow a player persona to roll again if they are none tool using.

Considering Mundane Terra. 
Cats have no tool usage;
Apes have simple tool usage;
Advanced apes (humans) have computer tool usage;
No creatures on mundane terra have creator tool usage.

include::role_playing_system:partial$alien_tool_usage.adoc[]

== Society
The society of the alien represents the level of societal development of the entire species.
If the player would like to roll to determine the elements of her alien society roll below.
To determine the particulars of religion type and politics the player may wish to jump to the appropriate referee persona section.

include::role_playing_system:partial$alien_society_levels.adoc[]

== Vocation
A vocation is a calling or innate skill set possessed by the persona.
If the referee's milieu indicates, a vocation could mean training at a school, institute or guild.
The player may choose from any of the listed vocations or pick one randomly.
Allowing the dice to choose the persona's vocation allows for attributes and abilities to be awarded.
For example, choosing a vet does not allow the persona to add CHA or choose one ability.
A randomly chosen spie would get the DEX attribute and be able to choose one ability.

include::role_playing_system:partial$vocation_selection_table.adoc[]

=== Vocation Attributes
Each vocation is associated with an attribute.
If the player generates her vocation randomly, her persona gets the designated attribute.
If the player randomly rolls a mercenary, her persona gets the vocation attribute STR added to her attribute list. 
If the player chooses a mercenary, her persona does not get the vocation attribute STR added to her attribute list. 

=== Vocation Abilities
Many vocations are associated with baked-in abilities.
Abilities are not skills.
Any persona can acquire a skill.
Abilities are part and parcel of the vocation.
A persona cannot learn the vet Quick Fix ability. 
If the player generates her persona vocation randomly, she can choose one vocation ability.

Biologist::
The biologist dedicates herself to studying the organic world.
These studies range from its denizens to it's cultures.
The player can add AWE to her persona's attributes if she randomly chose this vocation.
Every biologist gets two xref:vocations:biologist.adoc#biologist_skills[biologist skills,window=_blank].

Knite::
The knite dedicates herself to promoting order, or chaos, by connecting the Physical and Think Spaces. 
A player cannot choose or randomly generate the vocation knite.
Before a persona can become a knite, she must first earn her MND attribute.
A persona can earn the Knite vocation by completing a Knite qualification storyline laid out by the players.
The players will decide if the persona has earned the Knite vocation.
For more detail about knites jump to xref:vocations:knite.adoc[knites,window=_blank].

Mechanic::
The mechanic dedicates herself to studying the inorganic world.
These studies range from robots to scientific systems.
The player can add INT to her persona's attributes if she randomly chose this vocation. 
The player can add a xref:vocations:mechanic.adoc#_mechanic_abilities[mechanic ability,window=_blank] if she randomly chose this vocation. 
Every mechanic gets two xref:vocations:mechanic.adoc#_mechanic_skills[mechanic skills,window=_blank].

Mercenary::
The mercenary works hard to promoting order, or change, via violence.
Mercenaries are not psychotic, violent or cruel.
They are skilled in the art of war and weapons.
The player can add STR to her persona's attributes if she randomly chose this vocation. 
The player can add a xref:vocations:mercenary.adoc#_mercenary_abilities[mercenary ability,window=_blank] if she randomly chose this vocation. 
Every mercenary gets two xref:vocations:mercenary.adoc#_mercenary_skills[mercenary skills,window=_blank].

Nomad::
The nomad prides herself on surviving and integrating into her surrounding world.
These survival skills include all aspects of survival, travel and shelter in all terrains.
The player can add CON to her persona's attributes if she randomly chose this vocation. 
The player can add a xref:vocations:nomad.adoc#_nomadic_abilities[nomad ability,window=_blank] if she randomly chose this vocation. 
Every nomad gets two xref:vocations:nomad.adoc#_nomadic_biomes[nomad biomes,window=_blank].

Nothing::
The nothing vocation obsesses with all things mundane.
The mundane includes money, appearance and social standing.
The vast majority of the civilians of mundane terra are nothings.
Nothings have no combat skills and no useful maneuvers.
Nothings lack abilities or skills, but they do have a xref:vocations:nothing.adoc#_career[career,window=_blank]and some xref:vocations:nothing.adoc#_nothing_wealth[money,window=_blank].

Spie::
The spie is devoted to all things deceptive, sneaky and underhanded.
The realm of the spie includes disguises, sneaking and assassination.
The player can add CON to her persona's attributes if she randomly chose this vocation. 
The player can add a xref:vocations:spie.adoc#_spie_abilities[spie ability,window=_blank] if she randomly chose this vocation. 
Every spie gets two xref:vocations:spie.adoc#_spie_tricks[spie tricks,window=_blank].

Veterinarian::
The veterinarian is devoted to repairing and improving all organic beings.
This practice includes diagnosis, surgery and medications.
The player can add a xref:vocations:veterinarian.adoc#_vet_abilities[vet ability,window=_blank] if she randomly chose this vocation. 
Every vet gets two xref:vocations:veterinarian.adoc#_vet_skills[vet skills,window=_blank].

== Artifacts
Personas get a TOYs roll. 
It is entirely random, and the player only makes one roll. 
The result can range from Junque to starcruiser. 
Aliens are not limited to using an artifact by their appearance. 
This one alien artifact will be a bespoke piece of equipment that the alien can use.
To generate a toy for the persona jump to xref:hardware:a_introduction.adoc#_toy_type[Hardware,window=_blank].

== Name
The player should name her alien persona at the end of its evolution.
The alien name should include a persona name and a species name. 
For more detail than you ever wanted jump to xref:aliens:moniker.adoc[Alien Name,window=_blank].

== Appearance
The player should decant her alien's description down to its most prominent features.
For example, the player picks the essential defining parts of her alien: a pigeon-headed caterpillar wearing a camo tent carrying a plastic bag.

== History
Keep track of the fun.
Entirely optional.