= Theatrical Combat

[quote]
_____
*This failure in communication has escalated quickly.*
_____

The Theatrical Combat System is the cinematic and storyful sibling of the Tactical Combat Rules.
The Theatrical Combat System assists the players in telling a combat story. 
Combat in the Role Playing System employs the 4D2 Mechanic to guide the combat story.
The 4D2 Mechanic evolved from a legacy mechanic called the Theatrical Combat System.
The name has stuck for sentimental and legacy reasons.
The Theatrical Combat System guides combat stories so that players can make the most fun choices.

The Theatrical Combat Rules are not tactical in nature.
All of EXP's rules build off of the tactical combat rules.
The tactical combat rules requires maths, hex mats, tokens, miniatures and lots of dice.
The tactical system feigns war game level single persona combat outcomes.
The players measure success by removing a target's hit points and increasing their persona's experience points. 
The Roll Playing System's and it's tactical combat rules are storyful, but dice rolls more heavily direct the outcomes.

The Role Playing System employs a single dice mechanic that helps players direct the story.
The Role Playing System's Theatrical Combat System is not necessary for combat situations. 
If a particular combat resolution makes for a better story, then the Theatrical Combat System is not activated.
Successes are qualitative and descriptive.

NOTE: *The players interpret outcomes in the cinematic fashion that best serves the story.*

In the Theatrical Combat System, there are only descriptions.
The system has no hit points, no movement, no proficiencies, and no attack rolls to monitor.
The players must work their imagination muscle more than their maths muscle.
A description often requires more effort than subtracting six from 48.
The outcomes are descriptive and require a creative description.

The Role Playing System and its combat resolution tool still have dice rolls.
The dice offer randomness and force the players into unexpected storylines. 
The Theatrical Combat System only uses the 4D2 Mechanic.

== 4D2 Mechanic Refresher

.*Four steps of the 4D2 Mechanic*
. A player rolls dice (2d6 - 2d6) to get a  *Number*
. That *Number* yields an *Outcome*
. The *Outcome* produces a *Descriptor*
.. The *Descriptor* comes from the player or a table.
. The *Story* is influenced by the *Descriptor*

WARNING: Mastering the xref:role_playing_system:four_dee_two_mechanic.adoc[4D2 Mechanic,window=_blank] is recommended. 

== Combat Descriptors
Often the Outcome gives enough info for the players to tell the story.
Describing an outcome is easy for Immaculate Successes and Cataclysmic Failures.
The other 19 possible outcomes are more subtle and harder to turn into a description.

There is a Descriptor Table for Combat when the players can't manage a description or agree on a description. 
Most players prefer a descriptor table for when a persona's life is on the line.

include::role_playing_system:partial$numbers_combat_descriptors.adoc[]

If a player were to roll a Majestic Success (+7), her persona has dealt a mortal wound to her opponent. 
If a player were to roll a Major Failure (-3), her persona has been knocked back by her opponent.

=== Descriptor Descriptions
Aliens and anthros are organic targets, and robots are inorganic targets.
Robots damage differently from organics, and the outcomes are descriptively and effectively different.

The player may choose any success descriptor lesser than the one generated.
If the descriptor indicates a Mortal Wound, the player can choose from Wounded, Stunned or Backfoot if she desires.

.*Organic Successes*
Fatal Wound:: 
The target has suffered a fatal injury on the battlefield and is dead.
A Fatal Wound is a victory condition, and the target is dead.

Mortal Wound::
The target has suffered an injury that will quickly end their life.
A Mortal Wound is a victory condition, and the target is out of combat.
The target will remain alive until combat ends.
If they do not receive immediate care, they will die.

Severe Wound::
The target has suffered an obvious injury.
A Severe Wound is a victory condition, and the target is out of combat.
The target will remain alive even after combat ends.
If they do not receive eventual care, they may die. 

Wound::
The target has suffered an obvious injury.
A Wound is not a victory condition, and the target continues in combat.
A wounded target is unable to move without physical assistance.
Often there will be some penalty for being wounded.
The most manageable penalty is to limit the persona's total shifts when they are wounded.
More wounds can result in more penalties. 
Quick fixes can remove wounds and remove penalties.

Severe Stun::
A Severe Stun rattles the persona but does not include an apparent injury.
A Severe Stun is not a victory condition, and the target continues in combat.
A severely stunned target is unable to move without assistance.
There are no other penalties for a severe stun.
A Severe Stun remains until combat ends, or the persona gets a quick fix. 

Stun::
A Stun rattles the persona but does not include an apparent injury.
A Stun is not a victory condition, and the target continues in combat.
A stunned target is unable to move without encouragement.
There are no other penalties for a severe stun.
A Stun spontaneously resolves at the end of the combat turn. 

Knockback::
A Knockback pushes the target back in the direction of the attacker's preference.
The knockback is not a victory condition, and the target continues in combat.
A knockback does not send a target flying across the battle map. 
Knockback has no movement or shift penalties.

Backfoot::
The player can choose some mildly compromised position for her opponent.
The opponent suffers no shift for this compromise.
However, it may aid the persona to escape or do some other cunning thing.

.*Organic Failures*
If the player's 4D2 roll is negative, her persona can suffer the successes described above as failures. 
Ouch.

.*Inorganic Successes*
Attribute Loss::
Attribute Loss is the most severe damage that a robot can sustain.
Attribute loss indicates permanent damage to a crucial system.
The robot target must permanently cross the attribute off of her attribute list.
Attribute Loss destroys the robot if there are no attributes to remove.
Destruction of attributes is the only victory condition for robot opponents.

Attribute Damage::
Attribute Damage is a temporary loss of an attribute for the target.
The target robot will be unable to use the attribute or shift the attribute grants until the end of combat. 
A damaged attribute cannot lead to robot destruction.
The attribute is disabled but still present.
Damaged attributes reboot back to normal when combat is over.

Peripheral Destruction::
Peripheral Destruction is a very severe injury for the target robot.
Peripherals are baked-in robot abilities that are a mix of hardware and programmes.
The player, usually the referee, must choose a peripheral to remove from her persona.
This peripheral is not repairable after combat.
Peripheral Destruction has no effect if there are no peripherals to destroy.

Peripheral Destruction::
Peripheral Destruction is a very severe injury for the target robot.
Peripherals are baked-in robot abilities that are a mix of hardware and programmes.
The player, usually the referee, must choose a peripheral to remove from her persona.
This peripheral is not repairable after combat.
Peripheral Destruction has no effect if there are no peripherals to destroy.

Peripheral Damage::
Peripheral Damage is a temporary injury for the target robot.
Peripherals are baked-in robot abilities that are a mix of hardware and programmes.
The player, usually the referee, must choose a peripheral to remove from her persona.
This peripheral is repairable during combat and spontaneously reboots after fighting.
Peripheral Damage has no effect if there are no peripherals to damage.

Programme Destruction::
Programme Destruction is a very severe injury for the target robot.
Programmes are software skills that have no hardware.
The player, usually the referee, must choose a programme to remove from her persona.
This programme is not repairable after combat.
Programme Destruction has no effect if there are no programmes to destroy.

Programme Damage::
Programme Damage is a temporary injury to the target robot.
Programmes are software skills that have no hardware.
The player, usually the referee, must choose a programme to remove from her persona.
This programme is repairable during combat and spontaneously reboots after the battle.
Programme Damage has no effect if there are no programmes to damage.

Severe Rattle::
Severe Rattle is like a cross between stun and knockback from the organic successes.
There is no impact on the robot's ability to fight or move during combat.
A Severe Rattle makes the robot more susceptible to priority commands and robotic overrides. 
The control susceptibility lasts until the end of the battle unless reversed by a mechanic.

Rattle::
Rattle is like a cross between stun and knockback from the organic successes.
There is no impact on the robot's ability to fight or move during combat.
A Rattle makes the robot more susceptible to priority commands and robotic overrides. 
The control susceptibility spontaneously resolves at the end of the combat turn.

Cosmetic Injury::
The robot has a new scratch or dent.

.*Inorganic Failures*
If the player's 4D2 roll is negative, her persona can suffer the successes described above as failures. 
Bonk.

== Learning Skills
If the player rolls an Immaculate or Wondrous success, her persona earns a skill of her choice. 
The player must actually roll +10 or +9 on the actual die roll. 
If a roll has been shifted or folded to +10 or +9 a skill is not earned. 

The new skill should be related to the roll being made.
If the persona is shooting a rifle she can add a rifle skill to her persona record.
The next time she is shooting a rifle she can use a shift of plus one. 

=== Skill Learning
.Number = Immaculate (+10) or Wondrous (+9) success
****
Persona may add a skill related to the successful roll.
****

== Shifts
Shifts are similar to bonuses or penalties.
A shift is anything that moves the Descriptor.
A shift only applies to the descriptor.
A shift does not change an number or an outcome.

NOTE:: Players cannot use shifts to improve the chance to learn skills.

A Shift moves the Descriptor and benefits the player's persona.
A Shift of 2 would move a Knockback (+2) to a Severe Stun (+4).

Shifts are fundamental and are the only way players can gain an advantage in the Theatrical Combat System.

Shifts come from the persona's attributes, abilities and skills.
However, anything can become a shift if the table accepts it.
In hand-to-hand combat, a player can use STR as a shift.
When shooting a pistol, a pistol skill is an obvious shift.
A glorious description of how the persona throws a grenade can earn a shift.

=== Counter Shifts
Competing personas or situations can counter the shifts a player can use.
For example, a persona is in a pistol fight with an opponent. 
She has a pistol skill and a dexterity Attribute.
She can Shift her descriptor by +2.
If her opponent has Pistol 2, then the competing Shifts would cancel out.

=== Negative Shifts
The Theatrical Combat System is player-centric. 
The worst situation a persona can be in is to make a raw roll.
An unshifted raw roll is scary enough for a player. 

An canonical referee persona should be toughened by reducing a player's success descriptor and not worsening a failure descriptor.
A plot-important referee persona can reduce a success descriptor by two but not worsen a failure descriptor.
A Mortal Wound (+8) wound decreases to a Severe Wound (+6), but a failure Wound (-6) would not worsen to a Mortal Wound (-8).
This descriptor adjustor acts similarly to armour. 

== Attack Types
The attack types in the Theatrical Combat System Ranges are qualitative and descriptive.
The details are here to aid in story telling and fun. 

=== Strike Attacks
:art: type_a_sword.png
:width: 350px
:snark: Probably mightier than a pen.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Image of a modern sword with bucket hilt and a hint of energy at base.
include::ROOT:partial$articulate.adoc[]


These attacks depend on the muscle power of the attacker and must touch a target to cause damage.
The combatants must be within range of each other to engage in combat.
Examples are clubs, fists, claws, bites, swords, and ramming.
The tactical combat rules call these Strike attacks.

=== Fling Attacks
:art: bow_no_arrow.png
:width: 250px
:snark: Fancy bow.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Ornate fancy bow.
include::ROOT:partial$articulate.adoc[]

These attacks depend on the muscle power of the attacker and are flung at the target to cause damage.
The combatants must be within range to damage each other.
Examples are arrows, bolts, rocks, quills and spit.
The tactical combat rules call these Fling attacks.

=== Shoot Attacks
:art: XHP_rifle.png
:width: 350px
:snark: Large bore rifle.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Rifle with extra large calibre.
include::ROOT:partial$articulate.adoc[]

These attacks do not require muscle of the user and are pointed at the target to cause damage.
The energy comes from a battery, a bullet or some combination.
Combatants can be quite far apart and be able to damage each other.
Examples are bullets, laser bolts, energy beams, and crossbow bolts.
The tactical combat rules call these Shoot attacks.

=== Grenade Attacks
:art: aerosol_aoe.png
:width: 300px
:snark: Aerosol attack.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Man throwing spray can onto bbq of another man dressed like a cook.
include::ROOT:partial$articulate.adoc[]

Area of effect attacks act upon an area instead of a target.
Every target in the area of effect is simultaneously attacked. 
Area of effect attacks do not need direct contact with the target to cause damage.
Examples are frag grenade, napalm aerosol, or flaming breath.
The tactical combat rules call these Area Attack Types.

The tactical combat rules have a complex set of rules, using hexagon mats and models, to determine which personas are in the area of effect.
The Theatrical Combat System has no such rules.
The referee and players must quickly decide which targets are in the area of effect. 

The player makes a 4D2 roll when she launches the attack. 
Any outcome Detente (0), or better, indicates a successful grenade, aerosol or bomb attack. 
Any outcome Failure (-1 to -8) indicates a failed area of effect attack.
A failed attack means "no targets were harmed during the making of this explosion."
A Calamitous Failure (-9) will harm other expedition members.
A Cataclysmic Failure (-10) indicates a catastrophic malfunction of the area of effect weapon. 

include::role_playing_system:partial$numbers_grenade_descriptors.adoc[]

Every target in the area of effect must make a negative folded roll to determine the attack's impact.
If efficiency is of concern, one roll can determine the impact on all persona's in the area of effect.


:art: alien_robot_anthros.png
:width: 600px
:snark: An alien, a robot and an anthro walk into a park...
:artist: JEShields, HM added robot
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Two humans a large tentacled alien and a tiny flying robot in the park.

include::ROOT:partial$articulate.adoc[]

== Anthro Combat
The Theatrical Combat System is based on anthros fighting anthros. 
Robots behave slightly differently due to their size and inorganic fabrication.
Aliens behave slightly differently due to their size.

== Robot Combat
There are some advantages to being an inorganic life form in combat.
Mental attacks like ESP or mental control are not effective on the inorganic brain.
Robots cannot be stunned or wounded and keep fighting until destroyed.

Size counts as a shift for robots in hand-to-hand combat.
Ramming is the robotic equivalent of hand-to-hand combat. 
If the players are using size shifts, larger robots can earn a size advantage.

== Alien Combat
There are some advantages to being an alien in combat.
Many aliens have natural attacks that do not run out of ammunition or batteries.
Aliens are not affected by wounds or mortal wounds and will keep fighting without penalties.
Aliens can be stunned by a combat blow.

Size counts as a shift for aliens in hand-to-hand combat.
If the players are using size shifts, larger aliens can earn a size advantage.

== Defence Rating
There are no Armour Ratings in the Theatrical Combat System.
Personas gain combat advantage from their skills, abilities, weapons, and size.
Completely ignoring armour is too unrealistic for even the Theatrical Combat System.
Armour can shift the persona's descriptor in her favour. 
A suit of combat armour can decrease a mortal wound to a mere wound.
More powerful armour may have an even more significant beneficial shift.
Plus two is the highest possible shift armour can offer. 

== Range
There are no minis or hex mats rules for the Theatrical Combat System.
Ranges are descriptive, and the effects of different ranges are qualitative.
The ranges help tell the best combat story possible. 
In most cases, the story will any need for ranges. 
Each descriptive level indicates how far apart the combatants can be and still engage a target.

.*Theatrical Combat Ranges*
. Grapple
. Strike attacks
. Fling attacks
. Shoot attack, pistol
. Shoot attack, rifle
. Shoot attack, sniping (scope and spotter)
. Shoot attack, artillery (cannot see target)

include::role_playing_system:partial$horseshoes_hand_grenades.adoc[]

== Attack Frequency
Under normal circumstances, each persona gets one 4D2 roll per turn.
Some attacks allow for more than one 4D2 roll per turn.
Some aliens are fast and can make multiple bites per turn.
Some weapons have fast triggers and can make multiple attacks per turn.
Some weapons are automated and fire bursts of projectiles.
The exact nature of the multiple attacks is in the weapon description.

Each attack allows the player one 4D2 roll. 
The player may choose the best number from the 4D2 rolls.
So a player whose anthro persona has a plasma rifle (3 attacks per unit) would get three 4D2 rolls and pick the best one.

Only aliens with multiple attacks and mercenaries can spread their attacks between different targets. 

include::role_playing_system:partial$speed_may_matter.adoc[]


== Size Shifts
If the player table feels that size should matter.

include::role_playing_system:partial$size_may_matter.adoc[]

== None Rules
There are no real rules here, just concepts.
If any of these rules are crucial to gameplay, then consider using the tactical combat rules in their place.
The two combat systems mix and match very well. 
If detailed initiative and movement are essential, the players can use the tactical versions of these rules. 

=== Movement
Combat movement is qualitative in the Theatrical Combat System.
There are no minis, no tokens and no mats.
There are no movement rates.
If a movement decision is critical to the story, the 4D2 Mechanic can determine the result.

=== Time
There are no combat turns in the Theatrical Combat System.
The turns described her are players politely taking turns participating in the combat story.
If there is a race against time decision vital to the story, the 4D2 Mechanic can determine the result.

=== Initiative
There is no initiative in the Theatrical Combat System.
The players politely take turns participating in the combat story.
If there is a race against time built into the story, the players may use the 4D2 Mechanic to determine the outcome.

=== Ambush
There is no ambush in the Theatrical Combat System.
All parties politely take turns participating in the combat story.
If an ambush is part of the story, the players may use the 4D2 Mechanic to determine the outcome.

=== Weather
There are no weather effects in the Theatrical Combat System.
Meteorological effects are a purely descriptive element in this system. 

=== Hit Location
Neither the Theatrical Combat System nor the tactical combat rules use hit locations.
Hit locations are a descriptive element in both systems. 

=== Vehicle Combat
There are neither exatmo nor inatmo vehicle combat systems in the Theatrical Combat System.
Space ships and terrestrial vehicles should work as needed for the expedition.
Both are tools to propel the story.
If transportation shenanigans become part of the story, the players may use the 4D2 Mechanic to determine the outcome.

=== Attack Tables
There are no attack tables in the Theatrical Combat System.
The whole purpose of this combat system is to get away from maths.
