= Four D Two System

[quote]
_____
*Four D Two, Four-D-Two, 4D2 are wordplays on 42. + 
The answer to the wrong question.*
_____

Reading the following is recommended, but an online support tool exists at https://4d2.expgame.com[4d2.expgame.com]


== 4D2 Mechanic
4D2 is both a descriptor and a joke. 
The 4 indicates that the Mechanic uses 4 dice.
The 4 also indicates that there are 4 steps in the process.
The D refers to dice, as in the  "D" in the 4d6 convention.
The 2 reflects that the Mechanic has two directions.
The joke is that 4D2 sounds like 42.
Forty-Two is the answer to the question.
The 4D2 Mechanic gives the answers to questions you don't understand.

The 4D2 Mechanic uses four six-sided dice to guide the story in the Role Playing System.
The 4D2 Mechanic is a bespoke decision tool for EXP's Role-Playing System.
4D2 replaces Attack Rolls, Task Rolls, Attribute Rolls, Saving Rolls, Sphincter Rolls and more.

In the Role-Playing System, the 4D2 Mechanic is used to guide the story. 
Players ultimately guide the results generated by the 4D2 Mechanic.

.*Four steps of the 4D2 Mechanic*
. Get a *Number* from the die roll
. Get an *Outcome* from the *Number*
. Get a *Descriptor* from the *Outcome*
. Continue the *Story*

.*Number* to *Outcome* to *Descriptor* to *Story*
****
The die roll begets the Number. The number begets the Outcome. The outcome begets the Descriptor. The descriptor propels the Story.
****

== Number
A player generates a number by rolling two pairs of competing six siders.
The player rolls 2d6, generating a number between 2 and 12.
The player rolls 2d6 again, generating another number between 2 and 12.
The player subtracts the second roll from the first roll.
The sum of these two numbers generates the *Number* of the 4D2 Mechanic.

=== 4D2 Number Generation
.Number = 2d6 - 2d6
****
The number is always between +10 to -10. + 
A positive number gives a positive outcome. +
A negative number gives a negative outcome. +
Zero gives a neutral outcome.
****

=== How to Roll Dice 
The more dice rolled at once, the more efficient the mechanism.
The player first rolls two six siders (2d6).
The first roll is the positive value.
The same player rolls another two six siders (2d6).
The second roll is the negative value.
Some quick arithmetic generates the Number.

The player can roll all four dice at once to save time.
One pair of dice generates the positive roll. 
A different coloured pair of dice generates the negative roll. 
For example, the positive six siders could be green, and the negative six siders could be red.

:art: 4d2_dice.png
:width: 250px
:snark: (6+1) - (4+2) = +1
:artist: HM
:date: 2020
:license: CC BY-SA 4.0
:description: Two green dice and two red dice. Total score plus one.
include::ROOT:partial$articulate.adoc[]

The player can generate the number by rolling one six sided four times.
Rolling this way makes the process more dramatic and more time-consuming. 
Ultimately players and playgroups will develop their style for generating 4D2 mechanic Numbers.

=== Example Rolls
The player rolls 2d6, and the sum is 12. 
She rolls another 2d6, and the sum is 2.
The 4D2 Mechanic Number is +10 (12 - 2).
+10 is the best number possible for the player's persona.

The player rolls 4d6 all at once.
Her red dice are positive, and the sum is 9.
Her white dice are negative, and the sum is 8.
The 4D2 Mechanic Number is +1 (9 - 8).
+1 is a typical number and represents a slight win for the persona.

The player rolls 1d6 four times in a row. 
Her first roll is 3.
Her second roll is 1.
These two rolls generate a positive roll of +4.
Her third roll is 4.
This roll is subtracted from +4 to get 0.
Her fourth roll is 6.
This roll is subtracted from 0 to get -6.
The 4D2 Mechanic Number is -6.
This number is terrible, and badness is coming for the player's persona.

== Outcome
The outcome translates the number into a colourful account of the die roll.
The 4D2 Mechanic Number transforms into an Outcome for fun and efficiency.

The 4D2 Mechanic Number can be used as a raw number to determine what happens to the persona.
Everyone at the table is aware that +10 is great and -10 is a disaster. 
What do all those other Numbers mean?
Each Number result has an Outcome associated with it. 
There is an Outcome table that has correspondingly dramatic Outcomes for each Number.

For example, +10 is an Immaculate Success, and -10 is a Cataclysmic Failure.

include::role_playing_system:partial$numbers_to_outcomes.adoc[]

The Outcome Table helps __guide__ the players describe the Outcome of the task.
A positive Number yields a good Outcome.
A negative Number yields a bad Outcome.
The Outcome may be all the players need to move the story along. 
For example, a veterinarian is removing a splinter from a feline's paw.
An Outcome that is an Immaculate Success would be enough to guide a happy story. 

=== Example Outcomes 
The number +10 is an Immaculate Success.
This Outcome is rare. 
Immaculate success represents the best possible Outcome for the persona.
The player can choose to kill, wound, or incapacitate her opponent.
A persona's task would be very successful, leading to unexpected benefits.

The number +2 is a Solid Success.
This Outcome is quite common. 
Solid success represents a positive outcome for the persona, but nothing dramatic.
In combat, the persona has won an advantage, but the combat story is undecided.
A repair task was successful but may fail sooner than expected.

The number of -10 is a Cataclysmic Failure.
This Outcome is rare. 
Cataclysmic failure represents the worst possible Outcome for the persona.
In combat, the persona will suffer total defeat.
The persona could die or be lethally wounded.
Instead of a successful surgery, the patient can die, and the persona loses confidence.

The number 0 is detent.
This Outcome is the most common. 
Detent represents a balance between the positive and negative.
The struggle is ongoing.
Dramatic fight music continues, and neither persona has the upper claw.

NOTE: *The Outcome may be enough to move the story along.*

== Descriptors
Often the Outcome gives enough info for the players to tell the story.
The description of the outcome is easy for Immaculate Success and Cataclysmic Failure.
For the other 19 Outcomes, the players may need some help.

For recurring 4D2 Mechanic decisions, there are Descriptor Tables.
Descriptor Tables give examples of what could happen according to the Outcome.
Concrete descriptors are critical when a persona's life is on the line. 

NOTE: *The Descriptor can come from the players or a table.*

There are only two Descriptor Tables included in the Role Playing System.
There is a Descriptor Table for Combat and a Descriptor Table for Tasks.
The players may never need or use either of these tables. 
Players can use the Descriptor Tables to save time for repetitive acts.
The referee and players can create their own Descriptor Tables as they see fit.

* xref:role_playing_system:combat_rules.adoc[Combat Descriptors]
* xref:role_playing_system:task_rules.adoc[Task Descriptors]

== 4D2 Adjustments
If the table prefers the 4D2 mechanic has adjustments called shifts and folds.
Both shifts and folds are optional.
A shift allows a player persona to move her number based on skills, abilities or story.
A folded roll can only produce a success or a failure outcome.

== Graphic Overview
:art: 4D2_Mechanic.png
:width: 750px
:snark: More or less complicating?
:artist: HM
:date: 2020
:license: CC BY-SA 4.0
:description: Poster describing the four die two mechanic. 
include::ROOT:partial$articulate.adoc[]

== PDF of Entire Role Playing System
Download a colourful One Pager xref:appendices:printables.adoc#record_sheets[here]

== Nerdy Curvey Graph
The 4D2 Mechanic generates a smooth curve of numbers between +10 and -10.
The Number is player-centric. 
Positive numbers indicate success, and negative numbers indicate failure.
The most common Number from this Mechanic is 0.
0 represents balance, detent or ongoing struggle.
+10 represents the epitome of success for the persona.
-10 represents the epitome of failure for the persona.
The curve is quite beautiful.

:art: fourDtwo.png
:width: 350px
:snark: Thank you anydice.com
:artist: Jasper Flick
:date: 2020
:license: AnyDice.com 
:description: A graph showing the result curve of the four die two mechanic. 
include::ROOT:partial$articulate.adoc[]
