= 4D2 Mechanic Adjustments

In its purest form the 4D2 mechanic will operate without adjustments or descriptors.
However, sometimes a story needs some adjustments.
Maybe these adjustments are for drama, common sense, just plain fun.

== Shifts
Shifts are similar to bonuses or penalties.
A shift is anything that moves the Outcome of the 4D2 Mechanism.
A Shift of +2 would move a Solid Success (+2) to an Outstanding Success (+4).
Shifts are significant and are the only way personas can gain an advantage in the 4D2 system.

Shifts come from the persona's attributes, abilities and skills.
However, anything can become a shift if the players accept it.
In hand-to-hand combat, a player could use the STR as a shift.
When shooting a pistol, the player could use a pistol skill as a shift.
A glorious description of throwing a grenade can earn a shift.

=== Shift Maximums
The maximum number of shifts a player can add to her Outcome is three.
The maximum Outcome is +10, which is an Immaculate Success.
A roll of 11, 12 or even 13 becomes +10.

=== Shift Penalties
Shifts cannot be negative.
The lowest a player's shift can become is zero.
Penalties can only take away a player's shift.
If a persona wanted to use her DEX as a shift, but her hands were tied, she could not use her DEX shift. 
However, another persona in the same situation without a DEX attribute would not suffer a -1 shift.

=== Shifts and Skills
When the player rolls a high number, her persona can gain skills.
A high number is one pathway to earning new skills and strengthening the persona.
Players cannot use shifts to gain skills. 
Using shifts to score new skills can lead to rapidly overpowered personas. 
A +1 shift increases the chance of the persona gaining a new skill three times.

A shift only moves the Outcome and does not change the Number.
For example, a player rolls +6 for her number when attacking an enemy.
She has three shifts (skill, DEX and a good description). 
Her number is +6, but her outcome is +9.
The persona deals a fatal wound to her target but does not get a random skill.
 
=== Example Shifts
A persona is in a pistol shootout. 
She has pistol skill and DEX attribute.
She can Shift her 4D2 Outcome by +2.
A Shift of +2 would move a Solid Success (+2) to an Outstanding Success (+4).
If her opponent has Pistol 2, then the competing Shifts would cancel out.

A persona is repairing an antigrav modulator on a skimmer bike.
She has engine skill one and an INT attribute.
The player casts a great yarn about using a piece of wire to reverse the polarity.
She can shift her 4D2 Outcome by +3 (skill, attribute, good story).
The shift of +3 moves her Minor Failure (-1) to a Solid Success (+2).

A persona is play wrestling in the mud pit of a bar.
She has no wrestling skills.
She can use her STR and DEX attributes.
She can shift her 4D2 Outcome by +2 (two attributes).
The shift of +2 moves her Magnificent Success (+8) to an Immaculate Success (+10).
The persona earns the accolades of the bar crowd (Outcome = +10) but does not earn a wrestling skill.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Folded Rolls
A folded 4D2 roll is for when a +/- randomness cannot apply.
A persona falling from a great height should not earn a skill from a Wondrous Success.
A persona winning a lottery should not have become bankrupt from Catastrophic Failure.
These are examples of where the folded roll comes into play.
If it is good, how good is it?
If it is bad, how bad is it?

To generate a folded roll, the player makes a regular 4d2 roll generating a number between +10 and -10.
The negative number is ignored and the player looks at either the Folded Success Table or the Folded Failure Table. 
We will avoid any maths here to maintain the spirit of the Role-Playing System.

The obvious immediate problem with the folded rolls is that they tend towards the mundane. 
The most common outcome is still detente. 
Remember that these are tools for moving the story forward, not rules that spoil role-playing or fun.

=== Folded Success Outcomes

include::role_playing_system:partial$numbers_folded_success.adoc[]

=== Folded Failure Outcome

include::role_playing_system:partial$numbers_folded_failure.adoc[]


== Adjusting Away From d6 
What if one wanted to use use another die roll system other than 4D2 for Role-Playing.
Even though this would defeat the purpose of the the qualitative descriptor 4D2 mechanic.
Below is a table to help with that. 

.*Shift Conversions*
* *4D2* multiply by 1.0
* *Percentile* multiply by 10.0
* *Kilodie* multiply by 42.0

include::role_playing_system:partial$adjustments_not_asked_for.adoc[]
