= Incidentals

Incidentals are game elements that are not part of the biology, personality or knowledge of the persona.
If an incidental is added or removed from the persona, the persona remains the same. 
A persona may behave differently if they lose all their money, but they remain the same persona.
Incidental items are just that, incidental. 

In the role playing system incidentals are even less important than they are in the roll playing system.

Qualitative descriptions of wealth have as much merit as numbers of eps. 
Detailed tables covering incidentals are included here for convenience. 

== Start Money
Start money is the persona's pocket money on day zero of the campaign.
The start money is usually their total worth.
The personas may keep their life savings in a satchel or credit on their plastic money card.

The default currency in EXP is the eps (electrum piece).
The nature of money depends on the back story created by the ref and players.
Money nomenclature is discussed more thoroughly in the xref:roll_playing_system:CH23_Money.adoc[Money,window=_blank] section.

include::ROOT:partial$CH10_Table_Persona_Start_Money.adoc[]

== Start Equipment
To expedite the expedition exploring, the referee can extend start equipment to the personas.
Start equipment is only appropriate if it fits into the milieu of the ref and players.

This equipment will be of the mundane variety.
Here mundane means lo-fi, lo-tech tool level equipment.
Slightly higher-tech equipment is available.
Higher tech equipment is lighter and costs more.
There are no artifacts available for purchase in the incidentals. 
Personas get artifacts from the Technological Object Yield System (TOYS).

NOTE: * High-tech equipment are called artifacts or toys.*

Players can take their start money over to xref:roll_playing_system:CH24_Mundane_Equipment.adoc[Mundane Equipment,window=_blank]
 to purchase their start equipment.
For players not interested in pouring over lists, here is a mundane survival pack.

=== Survival Pack
The survival pack costs 70 eps and has a wate of 13.5 kg.
The survival pack is supposed to speed up the equipment buying procedure.
The referee can configure her survival packs as she sees fit.

include::ROOT:partial$CH24_Table_Survival_Pack.adoc[]

== Artifacts
Toys are special equipment generated on the Technological Object Yield System (TOYs). 
The TOY system generates random technological goodies that help the personas with their goals.
The player makes countless deci-dice rolls to generate a nondescript black box.
Artifacts and toys do not have obvious uses. 
Mundane equipment has obvious uses.

These technomagical high-tech devices are toys or artifacts.
Calling something an artifact sounds more serious.
Players use the terms toys, artifacts and equipment interchangeably.
