= Incidentals

Incidentals are game elements that are not part of the biology, personality or knowledge of the persona.
If an incidental is added or removed from the persona, the persona remains the same. 
A persona may behave differently if they lose all their money, but they remain the same persona.
Incidental items are just that, incidental. 

In the role playing system incidentals are even less important than they are in the roll playing system.

Qualitative descriptions of wealth have as much merit as numbers of eps. 
Detailed tables covering incidentals are included here for convenience. 

== Start Money
Start money is the persona's pocket money on day zero of the campaign.
The start money is usually their total worth.
The personas may keep their life savings in a satchel or credit on their plastic money card.
In a pure role playing experience actual money numbers are not kept track of.
If actual number amounts are needed xref:roll_playing_system:incidentals.adoc#_start_money[jump here,window=_blank]

== Start Equipment
Start equipment refers to the mundane equipment that all personas are assumed to have to role play in their milieu.
The personas will always have torches, cell phones, pens for writing.
This equipment is usually the lo-fi, mundane stuff that is easily found on mundane terra.
Technomagical devices are not considered start equipment and have their own section below. 
If the milieu is austere keeping track of mundane equipment may be part of the fun.
If mundane equipment is part of the milieu xref:roll_playing_system:incidentals.adoc#_start_equipment[jump here,window=_blank]

== Startifacts
Startifacts are a mash up of Start and Artifacts.
Artifacts are technological devices that are not mundane, but are not necessarily useful.
A typical EXP milieu will have each persona start with an artifact or three.
This is in the spirit of technological chaos. 
There is *NO* guarantee that the persona will know how to use the artifact.
It is possible they will have no idea what the artifact is.
To get some startifacts xref:hardware:startifacts.adoc[jump here,window=_blank]

