= Persona Creation

Persona generation in Role Playing can be driven by dice or by player choice.
Roll-able tables are included, but can be safely ignored. 
The Persona Record Sheet is mostly numberless.
There are no attribute scores.
There are no hit points.
Skills do not have levels.
Mutations and equipments are just words that represent a concept.
Artifacts and mutations do not have ranges, use frequencies or areas of effect. 

The words inform the 4D2 Mechanic to assist in story telling. 

== Determine Family
Most player will choose their persona's family.
It is strongly recommended that players choose an anthro persona.
Alien and robot personas are challenging to play and require role playing experience. 
The details of persona generation are self contained within each family.
The anthro family has everything needed for attributes, vocation and skills within it's own section.
For excessive detail about families in EXP, xref:roll_playing_system:families.adoc[jump here.]

include::role_playing_system:partial$family_chooser.adoc[]

== Incidentals
Incidentals are game elements that are not part of the biology, personality or knowledge of the persona.
If an incidental is added or removed from the persona, the persona remains the same. 
A persona may behave differently if they lose all their money, but they remain the same persona.
Incidental items are just that, incidental. 

If you need incidentals like money and equipment, xref:role_playing_system:incidentals.adoc[jump here.]


== Referee Personas
Referee persona creation is identical to player persona creation in the role playing system. 

To access all the of peculiarities of a randomly generated referee persona xref:roll_playing_system:CH11_Referee_Personas_.adoc[jump here.] 


