= Robot Fabrication

Robots are the colloquial name for the family Machinidae. 
Machinidae represents any life form that is inorganic and fabricated.
An organic fabricated life form would be an alien.
An inorganic non-fabricated life form would be a robot.
Anthros, aliens and robots fabricate robots.

:art: robot_delivery_service.png
:width: 450px
:snark: Is a robot stork a drone?
:artist: Studiostoks.
:date: 2017 purchase.
:license: Copyright Studiostoks.
:description: Baby robot being being born like a human baby in hospital.
include::ROOT:partial$articulate.adoc[]

include::role_playing_system:partial$persona_record_robot.adoc[]

.*Robot Fabrication*
. <<_attributes,Attributes>>
. <<_series,Series (Type)>>
. <<_abilities,Peripherals>>
. <<_skills,Skills>>
. <<_artifacts,Artifacts>>
. <<_name,Name>>
. <<_appearance,Appearance>>
. <<_history,History>>

== Attributes
The standard attributes of EXP are present in all personas.
In the Role-Playing System, players only record those attributes at which the persona excels.
A persona can have a blank attributes section and function fine.
Another persona may have the attribute Intelligence. 

====
*Attributes:* INT
====

The persona's Intelligence attribute is worth noting. 
A persona can excel at more than one attribute.

====
*Attributes:* INT, DEX
====

There is no score assigned to an attribute. 
The persona either excels at an attribute or not.
The attributes may help the personas when they undertake tasks.
For example, a persona with STR would be better at lifting than a persona with INT.
When two personas have the same attribute, then no advantage is given.
If two personas grappling both had Strength, then neither gains an advantage.
However, if a persona with STR and DEX is grappling with a persona with just STR, they get a DEX advantage.

These advantages are called shifts and increase the chance of success with the 4D2 Mechanism.

Most Excellent Attribute::
The player rolls once to determine the most excellent attribute of her robot persona.

include::role_playing_system:partial$best_attribute_table.adoc[]

Awareness::
Awareness indicates how aware a persona is of her surroundings. 
It indicates how well is the persona's brain connects to the outside world. 
The attribute is a collective measure of the persona's sensors. 
AWE includes senses like hearing, vision, smell, touch and taste. 
Awareness does not include the sixth sense or a sense of style. 
The abbreviation for Awareness is AWE.

Charisma::
Charisma is charm, looks and sociability all combined into one value. 
A high Charisma represents a high proficiency at getting along with other personas. 
This attribute is universal, so any persona with a high CHA would be socially adept. 
A persona's Charisma is crucial for inter-persona interactions.
The abbreviation for Charisma is CHA.

Constitution::
Constitution represents a persona's internal physique.
CON is a combination of wellness, immunity, energy extraction, healing ability.
A high CON is better to repel disease, resist poisons, and repair damaged tissue.
The abbreviation for Constitution is CON.

Dexterity::
Dexterity represents the connection between the brain and the outside world.
Agility, balance, eye-hand, reflexes and running speed are components of Dexterity.
A high DEX person could run faster, dance better and quicker reflexes.
Dexterity would help the persona catch a priceless vase or dive through a closing door.
The abbreviation for Dexterity is DEX.

Intelligence::
Intelligence indicates the smarts of the persona.
Elements of INT are memory, deduction, creativity, adaptability and their synergism. 
The higher the Intelligence of the persona, the smarter she is.
The abbreviation for Intelligence is INT.

Mind::
Robots do not have this attribute.
Mind is an organic connection to Kirlian Space that represents free will and wisdom.

Strength::
Strength represents force the persona can generate to get work done. 
STR is a combination of leverage, power and physique. 
Strength determines how much the persona can lift or damage by brute force. 
STR helps kicking open doors, breaking bonds, or crushing beer bottles.
The abbreviation for Strength is STR.

Hit Points::
There are no hit points in the Role-Playing System.
Combat and damage are both absolute and descriptive. 
There is no quantitative measure of well-being like 32 hit points out of 42.
Personas are damaged in combat by losing attributes, skills and abilities instead of hit points.
When the 4D2 Mechanic generates a Cataclysmic Failure, the persona can lose an attribute, skill or ability.
Extreme failures on the 4D2 Mechanic can mortally wound or kill the persona.
The abbreviation for hit points is HPS.

Control Factor::
Control factor represents how indebted the robot is to it's previous job or task.
In the role-playing system Control Factor can be chosen by a player to make her robot more free willed.

Adaptability::
This indicates how well the robot can be adjusted, repaired, upgraded or side graded. 

Size::
Size is considered an attribute and is included with the attributes section of the persona record. 

Social Standing::
There is no Social Standing in the Role-Playing System.
The players must  social interactions in the Role-Playing System (go figure).
The abbreviation for Social Standing is SOC.

EXPS and Level::
There are no Experience Points or Experience levels in the Role-Playing System. 
Personas earn additional attributes, skills and abilities instead of experience points or levels.
The 4D2 Mechanic can generate new attributes, skills or abilities.
This process replaces experience points and experience levels.
The abbreviation for experience points is EXPS.

== Series
The robot type determines its intended reason to be.
A robot type describes the primary function of the persona.
A heavy combot is a very different persona from a domestic janitorial robot.

In the Role-Playing System, players use the Single Role Robot Type Table to determine their robot type.
The referee should massage the robot type to suit her campaign's milieu.
For example, is a first-level expedition ready for a heavy combot? 
Players can choose their robot type if that choice improves the story.

include::role_playing_system:partial$robot_single_roll.adoc[]

=== Android
Androids are robots made in the image of their fabricator.
They are mostly indistinguishable from their fabricator type.
Typically it would require a vet or mechanic to determine their true nature.
Androids are very independent robots and have a high degree of autonomy.
Androids appear as their fabricator type.

* Size: Medium
* Attributes: 
** CHA, DEX, INT, CON and STR
** Choose one from CHA, DEX, INT, CON or STR
* Peripherals: None.
* To read the complete owner's manual jump to xref:robots:series_android.adoc[Android,window=_blank].

=== Combot Expendable
These robots are ex-recon, ex-aids or malfunctioning mechanical infantry.
Regardless of what she used to be, the expendable combot has gone freelance.
Expendable combots can drive military vehicles with combat proficiency.
Expendables have an excellent memory for combat details.
An expendable combot may resemble her fabricator type, but there is no question she is a robot.

* Size: Medium
* Attributes: 
** Choose one from DEX or CON
* Peripherals: 
** One Basic Peripheral
** One Offensive Table One
* To read the complete owner's manual, jump to xref:robots:series_combot.adoc#_expendable_combot[Expendable Combot,window=_blank].

=== Combot Defensive
Defensive combots defend positions from enemy attack. 
They are naturally protective of geographical spaces and fellow personas.

* Size: Large
* Attributes: 
** Add CON
** Choose one from AWE, CHA, CON, DEX, or INT.
* Peripherals: 
** Choose from Fortify, Intruder Detection, Anti-Anti-Detection Detector, or Weapon Identification.
** Two Defensive Peripherals
* To read the complete owner's manual, jump to xref:robots:series_combot.adoc#_defensive_combot[Defensive Combot,window=_blank].

=== Combot Light Offensive
Light offensive combots are attack drones.
They have many melee weapons.
Their deployment is for cities or other close-quarter environments.
Light combots are tactical machines and are not considered expendable. 

* Size: Large
* Attributes: 
** Add CON. 
** Choose from CON, DEX, or INT.
* Peripherals:
** One Defensive Peripheral
** One Offensive Peripheral Table Two.
* To read the complete owner's manual, jump to xref:robots:series_combot.adoc#_light_offensive_combot[Light Combot,window=_blank].

=== Combot Heavy Offensive
The heavy offensive combot is the beast of the robot world.
Their deployment is for softening, destroying and punching through enemy targets.
The heavy offensive combot is physically heavy and armed heavy.
Small arms tend to be higher powered.
The heavy combot will sport some heavy weapons like a bomb, artillery or missile.

* Size: Gigantic
* Attributes: 
** Add CON, CON, DEX, STR
** Choose two from CON, DEX, INT, STR
* Peripherals:
** Two Defensive Peripherals
** One Offensive Peripheral Table One 
** One Offensive Peripheral Table Two
** One Offensive Peripheral Table Three
** One Offensive Peripheral Table Four
* To read the complete owner's manual, jump to xref:robots:series_combot.adoc#_heavy_offensive_combot[Heavy Combot,window=_blank].

// todo revisit the combot peripheral applications

=== Datalyzer
Datalyzers used to be called analog monitors. 
Datalyzers are tin-can thinkers stuffed with artificial Intelligence. 
At the core of their Intelligence is a semi-organic, electronically enhanced computing unit. 
The organic matter and intertwined algos cause them to be emotional.
Datalyzers can have an actual psionic mutation woven into their semi-organic brain. 

* Size: Small
* Attributes: 
** Add INT and INT
** Choose one from AWE, INT.
* Peripherals: 
** One Peripheral Basic 
** One non-defective Psionic Mutation.
** One Defensive Peripheral (scaled to size)
* To read the complete owner's manual jump to xref:robots:series_datalyzer.adoc[Datalyzer,window=_blank].

=== Exploration eXtraplanetary
Exploration robots are fabricated to map, search, explore, catalogue, and record everything. 
Exploration robots often go by the nickname exobots or exbots.
Extraplanetary exobots explore new and unknown worlds.

* Size: Medium
* Attributes: 
** Add CON. 
** Choose one from DEX or INT.
* Peripherals:
** Exatmo Hardened
** Choose from Long Range Communication, Photography (all spectrum), Language Comprehension, or Identify Intelligence 
** Choose from Atmospheric Analysis, Poison Detection, Radiation Detection, Mineral Identification,Sample Collection or Map terrain
** One Defensive Peripheral
* To read the complete owner's manual, jump to xref:robots:series_exploration.adoc#_extra_planetary_exploration_robot[Exatmo Explorations,window=_blank].

=== Exploration Planetary
Exploration robots are fabricated to map, search, explore, catalogue, and record everything. 
Exploration robots often go by the nickname exobots or exbots.
Planetary exploration robots work within a single atmosphere of a single planet. 
They are used to find minerals, observe terrain, record weather and take photographs.

* Size: Medium
* Attributes: Choose from CON or INT.
* Peripherals:
** Choose two from Atmospheric Analysis, Long Range Communication, Mineral Identification, Photography (all spectrum), Sample Collection, Poison Detection, or Radiation Detection. 
** One Peripheral, Basic
* To read the complete owner's manual, jump to xref:robots:series_exploration.adoc#_planetary_exploration_robot[Planetary Explorations,window=_blank].

=== Hobbot
Hobbots are hobbyist robots put together by enthusiastic amateur roboticists.
Hobbots are for companionship, fun or some actual purpose.
Hobbots are the most easily modified of all the robots.
They also come with a plethora of Peripherals built-in.
Hobbots have an unusual degree of uniqueness.
Like snowflakes, no two hobbots are identical. 

* Size: Choose from Tiny or Small
* Attributes: 
** Add Adaptability 
** Choose one from INT or DEX.
* Peripherals: 
** Two Peripherals, Basic
** Two Peripherals, Fancy
** Two Defensive Peripherals.
** One Offensive Peripheral, Table One.
* To read the complete owner's manual jump to xref:robots:series_hobbot.adoc[Hobbot,window=_blank].

=== Industrial Builder
Builder robots are mobile assembly machines. 
A builder robot is usually not part of the design process. 
Design usually requires input from a mechanic. 
Once programmed, the builder robot gets right to it. 
The builder will source supplies and create widgets until out of supplies. In austere environments, it can take a long time to acquire construction materials.

* Size: Medium
* Attributes: 
** Add STR
** Choose one from DEX or INT.
* Peripherals: 
** Lingua Mechanica, can speak with mechanics
Two plus Mechanico-linguistics (understand mechanics).
** Two Peripherals, BasicDefensive: None.
** One Offensive Peripheral, Table One
* To read the complete owner's manual jump to xref:robots:series_industrial.adoc#_industrial_builder_robot[Builder,window=_blank].

=== Industrial Lifting
Lifting robots are wandering cargo hoists from warehouses or department stores.

* Size: Large
* Attributes: 
** STR
** Choose one from DEX or STR.
* Peripherals: 
** One lifting articulation
** Two Peripheral, Basic
* To read the complete owner's manual jump to xref:robots:series_industrial.adoc#_industrial_lifter_robot[Lifter,window=_blank].

=== Industrial Moving
Mover robots are intelligent trucks. 
This robot can read maps and understand even the worst directions. 
An industrial mover robot can always find its 'way' between waypoints (on the same planet).

* Size: Gigantic
* Attributes: 
** Add STR and STR
** Choose one from DEX, INT or STR
* Peripherals: 
** Self-loading and Navigation
* To read the complete owner's manual jump to xref:robots:series_industrial.adoc#_industrial_mover_robot[Mover,window=_blank].

=== Janitorial Commercial
Janitorial robots clean up. 
Their goal is to decrease the entropy of the universe. 
Janitorial robots have vacuums, sweepers, cleaners, plungers etc.

* Size: Medium.
* Attributes: Add CON
* Peripherals:
** Commercial Cleaning tools.
** One Peripheral, Basic
* To read the complete owner's manual, jump to xref:robots:series_janitorial.adoc#_commercial_janitorial_robot[Commercial Janitor,window=_blank].

=== Janitorial Domestic
Janitorial robots clean up. 
Their goal is to decrease the entropy of the universe. 
Janitorial robots have vacuums, sweepers, cleaners, plungers etc.

* Size: Small.
* Attributes: Choose one of INT or DEX
** Domestic Cleaning tools.
** One Peripheral, Basic
* To read the complete owner's manual, jump to xref:robots:series_janitorial.adoc#_domestic_janitorial_robot[Domestic Janitor,window=_blank].

=== Maintenance
A maintenance robot is a mechanic in a drum. 
This robot automatically gets a mechanic vocation. 
Maint robots are mostly interested in maintaining, repairing and improving inorganic objects.

* Size: Small.
* Attributes: \
** Add INT
** Choose one from INT or DEX.
* Peripherals: 
** Repair tools.
** Two Peripheral, Basic
* To read the complete owner's manual jump to xref:robots:series_maintenance.adoc[Maintenance,window=_blank].

=== Policing Civil
Civilian policing robots are constables on patrol in a drum. 
Civils can walk the beat, chase criminals, guard banks, issue tickets, etc. 
By sheer chance, this bot's ID is PC. 
This robot is the primary interface between the 'people' and law enforcement. 

* Size: Choose from Small or Medium.
* Attributes: 
** Add CHA 
** Choose one from INT or DEX.
* Peripherals:
** Grapple 
** Choose one from Commanding Voice, Disarm
** One Offensive Peripheral, Table Two -- Roll until Non-Lethal Peripheral acquired.
* To read the complete owner's manual jump to xref:robots:series_policing.adoc#_civilian_policing_robot[Civilian,window=_blank].

=== Policing Riot
Riobots are large crowd control operatives. 
They often turn up at labour disputes, surprise sales, food line-ups, rock concerts, etc. 
Their goal is to contain and restrain unruly hordes of anthros. 
They are essentially a police van with added crowd suppression.

* Size: Gigantic
* Attributes: Add CON and STR.
* Peripherals: 
** Choose from Tear Gas, Grav Disruptor, Weapon Malfunction, or Battery Drain
** Choose from Stun Ray, Sleep Beam, Force Beam, or Water Cannon
** One Defensive Peripheral -- Roll until Non-Lethal Peripheral acquired.
* To read the complete owner's manual jump to xref:robots:series_policing.adoc#_riobot_policing_robot[Riobot,window=_blank].

=== Policing Detective
A detective policing robot is a criminologist in a drum. 
A detective can operate as a chief, manager, auditor, or technologist. 
The detective has no grapple or detainment methods. 
A detective depends on civils to make arrests and do the dirty work. 
Detective policing robots focus on the apprehension of criminals. 

* Size: Choose from Small or Medium.
* Attributes: 
** Add AWE, INT. 
** Choose one from AWE, DEX or INT.
* Peripherals: Grapple.
* To read the complete owner's manual jump to xref:robots:series_policing.adoc#_detective_policing_robot[Detective,window=_blank].

=== Rescue Containment
Containment Rescue robots are like janitor robots for toxic environments. 
Toxic environments include fire, chemicals, radiation, bacteriologic, nanologic, or infestations etc. 
They contain and remove toxic or inconvenient elements.
The referee and players determine what an appropriate toxic danger is. 

* Size: Gigantic.
* Attributes: 
** Add CON
** Choose one from CON or STR
* Peripherals:
** Exatmo Hardened
** Web Gun Effect
** Choose one from Detect Toxins, Cordoning, Flame Suppression, Toxin Envelopment, or Toxin Storage.
** One Peripheral, Basic
** Two Defensive Peripherals
* To read the complete owner's manual jump to xref:robots:series_rescue.adoc#_containment_rescue_robot[Containment,window=_blank].

=== Rescue Retrieval
Retrieval robots remove organic personas, their bodies or their stuff from dangerous situations. 
Rescue retrieval includes complicated extrication from wreckage or rubble. 
The dangerous situations do not include combat. 
The dangerous environs include fires, landslides, radioactive areas, outer space, etc. 
They are capable of performing their duties underwater, in zero-gravity or a vacuum.

* Size: Large
* Attributes: 
** Add CON
** Choose one from CON, DEX or STR.
* Peripherals: 
** Exatmo Hardened
** Choose one from Alerting and Cordoning, Extrication, or Stasis Chambers
** Two Defensive Peripherals, Basic
** One Offensive Peripheral, Table One.
* To read the complete owner's manual jump to xref:robots:series_rescue.adoc#_retrieval_rescue_robot[Retrieval,window=_blank].

=== Social
Social robots look after the social needs of organic personas. 
They are also called robotlers, relation robots, or protocol droids. 
Social robots roughly resemble their fabricator type. 
Soc robots are obviously inorganic, and the resemblance is purely for aesthetics. 

* Size: Medium.
* Attributes: 
** Add CHA
** Choose one from CHA, DEX or INT.
* Peripherals: 
** Choose one from Languages, Cultures or Butlering.
* To read the complete owner's manual jump to xref:robots:series_social.adoc[Social,window=_blank].

=== Transport Inatmo
Transport robots are the truckers, pilots and chauffeurs from the robot world.
They make every vehicle a self-driving vehicle
Their goal is to get passengers and cargo safely to the chosen destination.
Transbots can drive combat vehicles, but they are not versed in vehicle combat.
Inatmo transport robots can pilot any planetside vehicle. 
The list includes trains, planes, cars, boats, or submarines. 
The list does not include non-powered vehicles like bicycles or skateboards.

* Size: Small
* Attributes: Choose one from DEX or INT.
* Peripherals: 
** Driving and Navigation
** One Peripheral, Basic
* To read the complete owner's manual jump to xref:robots:series_transport.adoc#_inatmo_transport_robot[Inatmo Transport,window=_blank].

=== Transport Exatmo
Transport robots are the truckers, pilots and chauffeurs from the robot world.
Exatmo transport robots can pilot and navigate spacecraft. 
The list includes spaceships, starships, space cruisers, jump ships, etc.
They are no adept at driving inatmo, planetside vehicles.

* Size: Small.
* Attributes: Add DEX and INT. 
* Peripherals: 
** Piloting and Astrogation
** One Peripheral, Basic
* To read the complete owner's manual jump to xref:robots:series_transport.adoc#_exatmo_transport_robot[Exatmo Transport,window=_blank].

=== Veterinarian Diagnostic
Veterinarian robots are vets in a drum.
They are also called medibots or vets.
This robot type values life and well-being beyond all.
It is challenging for a player to get their vet robot persona to cause harm.
This dedication to life is not limited to their fabricator type but all organic life.
This robot automatically gets a mechanic vocation but focuses on diagnosis.

* Size: Medium.
* Attributes:
** Add CHA, INT
** Choose one from INT or DEX.
* Peripherals: 
** No harming with peripherals
** Lingua Veterinaria (can speak with Vets)
* To read the complete owner's manual jump to xref:robots:series_veterinarian.adoc#_diagnostic_vet_robot[Diagnostics,window=_blank].

=== Veterinarian Interventional
* Veterinarian robots are vets in a drum.
They are also called medibots or vets.
This robot type values life and well-being beyond all.
It is challenging for a player to get their vet robot persona to cause harm.
This dedication to life is not limited to their fabricator type but all organic life.
This robot automatically gets a mechanic vocation but focuses on interventions.
They can perform Sciency Fiction surgeries.
They work best under the guidance of their diagnostics brethren or a veterinarian.

* Size: Medium.
* Attributes: 
** Add CHA, DEX 
** Choose one from INT or DEX.
* Peripherals: 
** No harming with peripherals
** Lingua Veterinaria (can speak with Vets)
** Veterinarian tool kit
** One Peripheral, Basic
* To read the complete owner's manual jump to xref:robots:series_veterinarian.adoc#_interventional_vet_robot[Interventional,window=_blank].

== Peripherals
Robot abilities are hardware-based and can also be called peripherals. 
Robot skills are software-based and can be called programming.
Everything a robot can do is lumped into peripherals. 
Some series and models get specific peripherals automatically.
The relevant peripheral tables are included here for convenience.
Players only get rolls on those tables listed under peripherals.

=== Peripherals, Basic

include::robots:partial$peripherals_basic_list.adoc[]

=== Peripherals, Fancy

include::robots:partial$peripherals_fancy_list.adoc[]

=== Defensive Peripherals

include::robots:partial$peripherals_defensive.adoc[]

=== Offensive Systems Peripherals

=== Table One

include::robots:partial$peripherals_offensive_1.adoc[]

=== Table Two

include::robots:partial$peripherals_offensive_2.adoc[]

=== Table Three

include::robots:partial$peripherals_offensive_3.adoc[]

=== Table Four

include::robots:partial$peripherals_offensive_4.adoc[]

== Artifacts
Personas get a TOYs roll. 
It is entirely random, and the player only makes one roll. 
The result can range from Junque to starcruiser. 
Robots are not limited to using an artifact by their shape or type. 
This robotic artifact is a bespoke piece of equipment that integrates with the persona.
To generate a toy for the persona jump to xref:hardware:a_introduction.adoc#_toy_type[Hardware,window=_blank].

== Name
The player should name her robot persona at the end of its fabrication.
The robot name should include a persona name, a model number and a fabricator. 
For more detail than you ever wanted jump to xref:robots:name.adoc[robot name,window=_blank].

== Appearance
The player should decant her robot's description down to its most prominent features.
For example, the player picks the essential defining parts of her robot: a matte black sphere sitting on wide treads.

== History
Keep track of the fun.
Entirely optional.



