= Vocations

[quote]
____
*An aptitude and desire beyond training.*
____

:art: hitcher_space.png
:width: 450px
:snark: 9 to 5 and 0g.
:artist: Studiostoks
:date: 2017
:license: Copyright 2017 Studiostoks
:description: Space suited humanoid carrying briefcase and thumb up for a ride in outer space. 
include::ROOT:partial$articulate.adoc[]

A vocation is more of an attitude than a profession.
Choosing a vocation in EXP does not mean that the persona has had any special training.
The information and skills that the persona can utilize are self-taught.
Vocations do not preclude training, and the milieu may have
diplomas or degrees granted by professional institutions.
Even in the case of training, the persona is still self-taught.

NOTE: *Vocations were previously called classes*

The vocation represents innate abilities, desire, and personal interest.
Two vocation types are biologist and mechanic.
The mechanic has a keen sense for interpreting the mechanical world.
A mechanic likely doesn't have an antigrav maintenance diploma.
The mechanic is more like a Ms. Fix-it or a bicycle repair person.
A biologist has an intuitive sense for observing the organic world.
A biologist likely doesn't have a degree in genetics.
The biologist is more like a gardener, a farmer or a bird watcher.

All of the vocations behave in this fashion.
Each vocation represents a natural aptitude that includes sparse bits of disorganized information.
As the persona increases her experience level in her vocation, she improves her skill set.

Vocations do not preclude training, and the milieu may have
diplomas or degrees granted by professional institutions.
Even in the case of training, the persona is still self-taught.

.*Vocation Types*
* xref:vocations:biologist.adoc[Biologist,window=_blank]: Studies and observes organic things.
* xref:vocations:knite.adoc[Knite,window=_blank]: Mystical warrior of order or chaos.
* xref:vocations:mechanic.adoc[Mechanic,window=_blank]: Repairs and improves inorganic things.
* xref:vocations:mercenary.adoc[Mercenary,window=_blank]: Breaks organic and inorganic things.
* xref:vocations:nomad.adoc[Nomad,window=_blank]: Survives using few things.
* xref:vocations:nothing.adoc[Nothing,window=_blank]: Infatuated with material things.
* xref:vocations:spie.adoc[Spie,window=_blank]: Deceiver and breaker of things.
* xref:roll_playing_system:CH08_Vocations_Veterinarian.adoc[Veterinarian,window=_blank]: Repairs and improves organic things.
* <<_alien_as_a_vocation,Alien>>: Does alien things.
* <<_robot_as_a_vocation,Robot>>: Does robot things.


EXP is an anthrocentric rules system, and the vocation system is based on anthropomorphs.
Every anthro persona has a vocation, even if that vocation is no vocation at all (Nothing).
Aliens and robots do not have vocations, they are vocations unto themselves. 


== Vocation Abilities
Each vocation has an area of expertise. This area of expertise gives the persona a better chance to complete a task. For example, a veterinarian is much better at treating an injury than a mercenary. The abilities of a vocation are divided into three parts: gifts, interests and skills. It is this collection of abilities that defines the vocation of the persona. 

=== Gifts
Gifts are tasks that the vocation can complete without effort and offer a guaranteed modicum of success. For example, a veterinarian has the gift of Quick Fix. This allows her to immediately heal her colleague a small amount. A mercenary has the gift of proficiency in personal weapons. A mercenary can pick up a weapon and understand it's basic use. The gifts are inherent understandings that the persona has. They are not learned by training or schooling or video meetings. Each vocation has it's own silly name for their gifts. A veterinarian has procedures, a spie has tricks, a biologist has knacks. It is fine to refer to these as gifts.

Gifts are vocation specific and new ones are earned as the persona gains new experience levels. 

=== Interests
Interests are broad areas that the persona can use to increase their success at completing tasks. Each vocation has it's own areas of interest. A biologist may be interested in taxonomy (which will help identify aliens), or culture (which will help them understand a cultural aspect). A mechanic can have an interest in repairs which will help her fix things. A nothing may have an interest in careers, which will help her with career related tasks. 

Interests are vocation specific, and are randomly assigned or chosen by the player. A persona gets new interests with increasing experience levels. The benefits of interests are cumulative.

=== Skills
Skills are more specific than interests and are not specifically vocation related. If a skill can applied to a task there is a better chance to successfully complete the task. For example, a spie that has a skill in bribery would have an increased chance of success when tasked with bribing a border guard. A veterinarian with a skill of dentistry would have a better chance of winning the task of sharpening some fangs.

Skills are not vocation specific although there are some exceptions. So a mercenary could have the skill of resuscitation, or a spie could have a skill of language. Skills are randomly assigned or chosen by the player. A persona gets new skills with new experience levels. The benefits of skills are cumulative and are expected to be combined with interests. 

== Vocation Selection
The persona's attribute scores determine her vocation.
The attribute minimums for vocations are present to maintain game balance.
Veterinarians need Charisma, and spies need Dexterity and mercenaries need hit points.
The attribute score must be greater than or equal to the vocation requirement.
For example, a biologist must have a combined Awareness and Intelligence greater than or equal to 18.
A persona with a 4 INT and a 14 AWE can become a biologist, but not a mechanic, 
Usually, a player will have a list of vocations to choose from for her persona.
The default anthro vocation is the nothing vocation.

include::vocations:partial$required_attributes.adoc[]

=== Vocation Selection Example
A persona has the attributes: AWE 6, CHA 15, CON 17, DEX 9, INT 14, MND 12, STR 6, and HPS 42.
The persona's social standing (SOC) is not part of the vocation selection process.
The player has a wide selection of vocations from which to choose.
This persona could be any of the following: biologist, mechanic, mercenary, nothing, or veterinarian.

include::vocations:partial$selection_example.adoc[]

== Vocations and Role-Playing
The persona should have at least a keen interest, or possibly an obsession, with her vocation.
Veterinarians should show compassion and a desire to heal.
Biologists should show respect, if not awe, for the natural organic world.
Anti-knites should take on any opportunity to increase the universe's entropy level.

Players that do not role-play their persona's vocation can face challenges.
Villainous veterinarians and altruistic anti-knites may see their skills weaken.
Nomads living in decadent luxury will find their survival skills starting to rust.

Initially, their actions will cost them vocation related experience points.
Continuing transgressions may make it impossible for the persona to carry out her tasks.
A murderous veterinarian may find that her skills don't work well on those who know the truth.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Multiple Vocations
A player may want to have a persona with more than one vocation.
Inexperienced players or referees should avoid multi-vocation personas.
The persona must have the attribute requirements for both vocations.

There are situations where the ref and players may allow a persona to have more than one vocation.
A player may wish to change things up with her persona.
The expedition may need a particular vocation, and a player volunteers to cross-train her persona.
A mercenary may wish to add the mechanic vocation to keep a crucial piece of artillery working.  

The referee is the final arbiter on multi-vocation personas. 
Less mature players may abuse this privilege.
The referee decides if the player is combining or switching personas in good faith.

=== Combining Vocations
Combining vocations is when the player has a persona with two vocations concurrently.
For example, a biologist mechanic can do biologist and mechanic maneuvers. 
The persona advances both levels simultaneously and can use skills from both vocations.

The amount of experience required for each new level will be equal to the sum of both vocations plus 10% of the total.
A combined mechanic-biologist would need 4400 EXPS to reach second level.

Nomads, nothings and spies cannot combine with any other vocation.
A persona cannot be a combined knite and anti-knite.

=== Switching Vocations
Switching vocations is when the player moves her persona from one vocation to another. 
Switching vocations is less demanding than combining vocations.
If the persona has the vocation's attribute requirements, she can switch any time.

For example, a mercenary may suddenly get a conscience and devote the rest of her life to the study of biology.
If she has the appropriate attributes, she can do this switch at any time.
The persona's mercenary skills freeze at her exit level.
She begins collecting experience points as a first-level biologist with zero EXPS.
She can still use her mercenary skills but only collects experience as a biologist.

If the persona does not have the attributes to make a vocation, she can follow the nothing vocation until she gets the necessary EXPS.

== Robot as a Vocation
The vocations in this section are athropomorphic pursuits of knowledge and skill.
Robots do not pursue a specific vocation, and are considered a vocation unto themselves.
Robots have series and models that are built to fulfill specific goals. 
These goals are the robot's vocation.
In a sense a robot does not have a vocation, a robot is a vocation.

* a transport robot's vocation is driving.
* an exploration robot's vocation is exploring. 

Playing a robot persona is very challenging and not recommended for neophytes.
Robots engage in the milieu the same as any other player persona.
Robots can earn experience, gain levels and improve their free will. 

A robot may acquire an anthro vocation through programming, peripherals, or malfunction.
Robots with anthro vocations are an edge case, and the referee and player must decide how to integrate this combined pathway.

To pursue a player persona robot xref:robots:a_introduction.adoc[jump here].

== Alien as a Vocation
The vocations in this section are athropomorphic pursuits of knowledge and skill.
Aliens do not pursue a specific vocation, and are considered a vocation unto themselves.
Aliens have goals of energy procurement and reproduction amd have evolved to fulfill those goals.
These goals are the alien's vocation.
In a sense an alien does not have a vocation, an alien is a vocation.

Playing an alien persona is challenging and not recommended for neophytes.
Aliens engage in the milieu the same as any other player persona.
Aliens can earn experience, gain levels and improve persona's alien proficiencies.

An alien can be born into a society that has education and vocation. 
Under these circumstances the alien can pursue an anthro vocation. 
Aliens with anthro vocations are an edge case, and the referee and player must decide how to integrate this combined pathway.

To pursue a player persona alien xref:aliens:a_introduction.adoc[jump here].


== Take a Vocation
It is a good idea to take a vocation once in a while.
Relaxing vocations that connect with nature are healthy.
However, improving one's lifestyle is much more effective at reducing stress than a holiday vocation. 