= Vocations

[quote]
____
*An aptitude and desire beyond training.*
____

:art: hitcher_space.png
:width: 450px
:snark: 9 to 5 and 0g.
:artist: Studiostoks
:date: 2017
:license: Copyright 2017 Studiostoks
:description: Space suited humanoid carrying briefcase and thumb up for a ride in outer space. 
include::ROOT:partial$articulate.adoc[]

A vocation is more of an attitude than a profession.
Choosing a vocation in EXP does not mean that the persona has had any special training.
The information and skills that the persona can utilize are self-taught.
Vocations do not preclude training, and the milieu may have
diplomas or degrees granted by professional institutions.
Even in the case of training, the persona is still self-taught.

NOTE: *Vocations were previously called classes*

The vocation represents innate abilities, desire, and personal interest.
Two vocation types are biologist and mechanic.
The mechanic has a keen sense for interpreting the mechanical world.
A mechanic likely doesn't have an antigrav maintenance diploma.
The mechanic is more like a Ms. Fix-it or a bicycle repair person.
A biologist has an intuitive sense for observing the organic world.
A biologist likely doesn't have a degree in genetics.
The biologist is more like a gardener, a farmer or a bird watcher.

All of the vocations behave in this fashion.
Each vocation represents a natural aptitude that includes sparse bits of disorganized information.
As the persona increases her experience level in her vocation, she improves her skill set.

.*Vocation Types*
* xref:vocations:biologist.adoc[Biologist,window=_blank]: Studies and observes organic things.
* xref:vocations:knite.adoc[Knite,window=_blank]: Does orderly or chaotic things.
* xref:vocations:mechanic.adoc[Mechanic,window=_blank]: Repairs and improves inorganic things.
* xref:vocations:mercenary.adoc[Mercenary,window=_blank]: Breaks organic and inorganic things.
* xref:vocations:nomad.adoc[Nomad,window=_blank]: Survives using few things.
* xref:vocations:nothing.adoc[Nothing,window=_blank]: Infatuated with material things.
* xref:vocations:spie.adoc[Spie,window=_blank]: Deceiver and breaker of things.
* xref:vocations:veterinarian.adoc[Veterinarian,window=_blank]: Repairs and improves organic things.
* <<_alien_as_a_vocation,Alien>>: Does alien things.
* <<_robot_as_a_vocation,Robot>>: Does robot things.

.*Vocation Creation*
. Vocation determination (choice or rolled)
. knowledge acquisition (choice or rolled)
.. interests
.. expertise
. skill acquisition 
.. gift determination


EXP is an anthropomorphic rules system, and the vocation system is based on anthropomorphs.
Every anthro persona has a vocation, even if that vocation is no vocation at all (Nothing).
Aliens and robots do not have vocations, they are vocations unto themselves. 

The vocations are composed of knowledge and skills. 
Vocation knowledge is what the persona knows. 
Knowledge is used by the persona to succeed at tasks. 
Each vocation has it's own set of knowledge areas.
Each vocation has it's own set of tasks.
These tasks are called skills. 
Some skills are limited to a solitary vocation, others can be used by all vocations. 

== Vocation Selection
The persona's attribute scores determine her vocation.
The attribute minimums for vocations are present to maintain game balance.
Veterinarians need Charisma, and spies need Dexterity and mercenaries need hit points.
The attribute score must be greater than or equal to the vocation requirement.
For example, a biologist must have a combined Awareness and Intelligence greater than or equal to 18.
A persona with a 4 INT and a 14 AWE can become a biologist, but not a mechanic, 
Usually, a player will have a list of vocations to choose from for her persona.
The default anthro vocation is the nothing vocation.

include::vocations:partial$required_attributes.adoc[]

=== Example
A persona has the attributes: AWE 6, CHA 15, CON 17, DEX 9, INT 14, MND 12, STR 6, and HPM 42.
The persona's social standing (SOC) is not part of the vocation selection process.
The player has a wide selection of vocations from which to choose.
This persona could be any of the following: biologist, mechanic, mercenary, nothing, or veterinarian.

include::vocations:partial$selection_example.adoc[]


== Knowledge 
A vocation's knowledge represents things that the persona knows. 
Knowing how to sharpen is a knife is knowledge, actually sharpening the knife is a task. 
Knowledge is split into two parts: interests and expertise. 
A persona is more likely to have expertise that is related to the persona's interests, and those interests reflect the vocation.
Interests and expertise are combined to help with tasks. 
Each persona gets a collection of interests and expertise at first level and adds more as they gain experience. 

=== Interests
Interests are broad areas of knowledge. 
For example, research is an interest. 
Typical areas of interest are research, repair, combat etc.
They are wide in scope by design and can be used to assist all kinds of tasks. 

A biologist may be interested in taxonomy (which will help identify aliens), or culture (which will help them understand a cultural aspect). 
A mechanic can have an interest in repairs which will help her fix things. 
A nothing may have an interest in careers, which will help her with career related tasks. 

Interests are cumulative and a nomad may have survival 3 interest. 
This indicates lots of knowledge about survival, and improves the chance of success on survival tasks. 

Interests are vocation specific, and are randomly assigned or chosen by the player. 
A persona gets new interests with increasing experience levels.

=== Expertise
Expertise is specific knowledge. 
Expertise usually has a concise description like: pistols, cloning, tracking. 
They are narrow in scope by design, and can be used to assist tasks.

A spie can have expertise in bribery
A veterinarian can have expertise in trauma.
Expertise is cumulative and a mercenary could have bombs 4 as an expertise.

Expertise is vocation specific, and is randomly assigned or chosen by the player. 
A persona gets additional expertise with increasing experience levels.

== Skills
Skills are tasks that are best performed by a specific vocation.
However, other vocations can attempt each other's skills as task rolls. 
Some skills are entirely vocation specific.
For example, assassination can only be attempted by a spie, and a mercenary would not be good at tracking.

The persona's interests, expertise and experience level determine what skills the persona can perform.
Initially some skills will be out of reach as the player could not beat the difficulty easily. 
Persona's are welcome to try anything

=== Compendium
Each vocation has a compendium of skills, aka tasks, that are appropriate for the vocation. 
It is expected that the player will record some of the key skills from the compendium on the persona record. 
The compendium is not exhaustive and it is expected that the table will have tasks that are not listed.
These tasks may become skills that the persona has or be disposable one offs. 

=== Gifts
Gifts are skills that the persona has committed to knowledge.
The persona can complete gifted skill without effort and offer a guaranteed modicum of success. 
For example, a veterinarian has the gift of Quick Fix. 
This allows her to immediately heal her colleague a small amount. 
A mercenary has the gift of proficiency in personal weapons. 
A mercenary can pick up a weapon and understand it's basic use. 
The gifts are inherent understandings that the persona has. 
They are not learned by training or schooling or video meetings. 
Each vocation has it's own silly name for their gifts. 
A veterinarian has procedures, a spie has tricks, a biologist has knacks. 
It is fine to refer to these as gifts.

Gifts are vocation specific and new ones are earned as the persona gains new experience levels. 

== Role-Playing
The persona should have at least a keen interest, or possibly an obsession, with her vocation.
Veterinarians should show compassion and a desire to heal.
Biologists should show respect, if not awe, for the natural organic world.
Anti-knites should take on any opportunity to increase the universe's entropy level.

Players that do not roleplay their persona's vocation can face challenges.
Villainous veterinarians and altruistic anti-knites may see their skills weaken.
Nomads living in decadent luxury will find their survival skills starting to rust.

Initially, their actions will cost them vocation related experience points.
Continuing transgressions may make it impossible for the persona to carry out her tasks.
A murderous veterinarian may find that her skills don't work well on those who know the truth.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Multiple Vocations
A player may want to have a persona with more than one vocation.
Inexperienced players or referees should avoid multi-vocation personas.
The persona must have the attribute requirements for both vocations.

There are situations where the ref and players may allow a persona to have more than one vocation.
A player may wish to change things up with her persona.
The expedition may need a particular vocation, and a player volunteers to cross-train her persona.
A mercenary may wish to add the mechanic vocation to keep a crucial piece of artillery working.  

The referee is the final arbiter on multi-vocation personas. 
Less mature players may abuse this privilege.
The referee decides if the player is combining or switching personas in good faith.

=== Combining
Combining vocations is when the player has a persona with two vocations concurrently.
For example, a biologist mechanic can do biologist and mechanic tasks. 
The persona advances both levels simultaneously and can use skills from both vocations.

The amount of experience required for each new level will be equal to the sum of both vocations plus 10% of the total.
A combined mechanic-biologist would need 4400 EXPS to reach second level.

Nomads, nothings and spies cannot combine with any other vocation.
A persona cannot be a combined knite and anti-knite.

=== Switching
Switching vocations is when the player moves her persona from one vocation to another. 
Switching vocations is less demanding than combining vocations.
If the persona has the vocation's attribute requirements, she can switch any time.

For example, a mercenary may suddenly get a conscience and devote the rest of her life to the study of biology.
If she has the appropriate attributes, she can do this switch at any time.
The persona's mercenary skills freeze at her exit level.
She begins collecting experience points as a first-level biologist with zero EXPS.
She can still use her mercenary skills but only collects experience as a biologist.

If the persona does not have the attributes to make a vocation, she can follow the nothing vocation until she gets the necessary EXPS.

== Robots
The vocations in this section are athropomorphic pursuits of knowledge and skill.
Robots do not pursue a specific vocation, and are considered a vocation unto themselves.
Robots have series and models that are built to fulfill specific goals. 
These goals are the robot's vocation.
In a sense a robot does not have a vocation, a robot is a vocation.

* a transport robot's vocation is driving.
* an exploration robot's vocation is exploring. 

Playing a robot persona is very challenging and not recommended for neophytes.
Robots engage in the milieu the same as any other player persona.
Robots can earn experience, gain levels and improve their free will. 

A robot may acquire an anthro vocation through programming, peripherals, or malfunction.
Robots with anthro vocations are an edge case, and the referee and player must decide how to integrate this combined pathway.

To pursue a player persona robot xref:robots:a_introduction.adoc[jump here].

== Aliens
The vocations in this section are athropomorphic pursuits of knowledge and skill.
Aliens do not pursue a specific vocation, and are considered a vocation unto themselves.
Aliens have goals of energy procurement and reproduction amd have evolved to fulfill those goals.
These goals are the alien's vocation.
In a sense an alien does not have a vocation, an alien is a vocation.

Playing an alien persona is challenging and not recommended for neophytes.
Aliens engage in the milieu the same as any other player persona.
Aliens can earn experience, gain levels and improve persona's alien proficiencies.

An alien can be born into a society that has education and vocation. 
Under these circumstances the alien can pursue an anthro vocation. 
Aliens with anthro vocations are an edge case, and the referee and player must decide how to integrate this combined pathway.

To pursue a player persona alien xref:aliens:a_introduction.adoc[jump here].

== Take a Vocation
It is a good idea to take a vocation once in a while.
Relaxing vocations that connect with nature are healthy.
However, improving one's lifestyle is much more effective at reducing stress than a holiday vocation. 