= Biologist

[quote]
____
*Studies and observes organic things.*
____

:art: biologist.png
:width: 250px
:snark: Watching a biologist watch
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: woman wearing a pith helmet using binoculars and a computer in the jungle. 
include::ROOT:partial$articulate.adoc[]

Biologists are personas with a deep connection with the workings of the organic physical world.
The vocation is broad as the organic world. 
Their scope can vary from creepy crawly bugs to complicated economic systems. 

Biologists are more interested in studying the organic world than repairing the organic world.
Biologists are more interested in organic systems than mechanical systems.
Veterinarians, mechanics and biologists work well on research teams together. 

Biologists do not have degrees or diplomas or certificates from training programs.
They are self-taught, and their knowledge base is haphazard.
Their knowledge comes from keen observation, gardening books, environmental leaflets, nature shows, sagely advisors, and personal experience.

If your table is using attribute determined vocations a biologist must have a total AWE and INT greater than or equal to 18. 

== Knowledge
The biologist's abilities cover all aspects of the organic world.
Anything to do with organic life, anthros and aliens, falls under her purvey. 
This includes the observation, discovery, and identification of aliens. 
Biology covers the knowledge spheres of sociology, ecology, culture studies, and more.
A biologist's abilities do not include robots (mechanic) or organic repairs (veterinarian). 
However a biologist could take tasks from the mechanic or veterinarian vocation.

== Interests
Interests are broad areas that cover a swath of the organic world.
The interests are: Culture, Research and Taxonomy.
The Culture interest could help with a linguistic task.
The Research interest could help with a laboratory task.
The Taxonomy interest could help with an alien identification task.

At startup, the persona gets one interest per three points of Intelligence score.
A persona with a 12 INT would get four rolls on the Biologist Interest Table. 
After startup the persona earns another interest with each new experience level.
The player can choose to roll on the Biologist Interest Table, or choose a specific interest.

include::vocations:partial$biologist_interests_list.adoc[]

=== Taxonomy
Taxonomy is about identifying and categorizing organic species.
The taxonomy interest is the classical biologist as a naturalist.
Skills like identifying burrowers in toxic biomes or carnivores in the ocean fall under taxonomy.
Mere categorization of finches on remote islands has changed society.

=== Research
The research interest includes laboratory, invention and extension interests for the biologist.
Skills like cloning, immunology, and antitoxin creation are found under the research interest

=== Culture
The culture interest involves interaction of a population.
Skills like languages, family structures, and political nuance are found under the culture interest.

== Expertise
Biologist expertise is grouped by interest.
A taxonomy interest could come with expertise in: burrowers, hivers or herbivores.
A culture interest could come with expertise in: language, religion or politics 

At startup the player gets one areas of expertise per interest. 
So a biologist with taxonomy 2 and culture 1 would get 2 rolls on the taxonomy expertise table and 1 roll on the culture expertise table.
After start up the persona gets one new expertise per experience level. 
The player can roll on one of the expertise tables or choose a specific expertise.

=== Culture
Culture expertise focuses on understanding the interactions of groups of organic life forms. 
These expertise can be used to predict what a pack of aliens might do, or try and predict an election.

include::vocations:partial$biologist_expert_cultural.adoc[]

=== Research
Research expertise focuses on specific areas of research of the organic world.
These areas of expertise can be used to make an antivenom, clone an alien, or enhance a mutation.

include::vocations:partial$biologist_expert_research.adoc[]

=== Taxonomy
Taxonomy is about identifying and categorizing organic species.
Each skill includes a tasks and a biome type. 
A taxonomy skill could look like this: Taxonomy - Herbivore - Desert Biome.

include::vocations:partial$biologist_expert_taxonomy.adoc[]

=== Knacks 
Biologist knacks (gifts) are tasks that the player does not need to make a task roll for. 
The persona gets one knack at first level and more difficult ones are added at prescribed levels. 

include::vocations:partial$biologist_knacks.adoc[]

=== Organizing
A biologist can rack up a lot of knowledge.
What follows is a way to keep track of them. 

:art: biologist_footprint_symbol.png
:width: 350px
:snark: Footprint? Language? Bad Map?
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Mystical connected semi-circles scratched into ground.
include::ROOT:partial$articulate.adoc[]

.*Example Three Rolls At Startup*
* Interest Taxonomy
* Expertise Herbivores
* Interest Taxonomy
* Expertise Detritivores
* Interest Culture
* Expertise Languages, verbal
* Knack Biological

Interests and expertise are cumulative and separated.
The persona has two taxonomy interest, and the player can use them on any task related to taxonomy.
Even if the persona has no expertise in chaser/hunter aliens, she can still use her taxonomy 2 interest when working on a chaser/hunter behaviour.
When working on a herbivore related task, she will get a task bonus of 3 (taxonomy 2 and herbivore 1).
When studying a herbivore in a desert biome, she will get a total bonus of 5  (taxonomy 2, herbivore 1 and desert biome 2).

.*Reorganized knowledge*
* Interests 
** Taxonomy - 2
** Culture - 1 
* Expertise
** Herbivores - 1
** Detritivores - 1
** Languages, Verbal - 1
* Knacks
** Bioligical (is it organic)


== Compendium
Biologist tasks involve anything organic that does not involve healing.
Most biologist tasks are knowledge based unless an obvious physical intervention is involved.
The minimal equipment required by a biologist is her notebook. 
The referee may make a target roll more difficult if the biologist does not have her notebooks.
For the intricate details of how to resolve tasks in EXP xref:uncombat:task_rolls.adoc[jump here].

Each vocation have special tasks called gifts at which they automatically succeed. 
Biologist gifts are called knacks. 
The player can choose from the below list of tasks or create a bespoke knack.

A non-exhaustive list of biologist tasks arranged by increasing difficulty.

Skill Example (42)::
One line description of skill. Difficulty is in brackets. 

=== Trivial
Biological (12)::
    Is it biological? Yes. No. 

Sentience (12)::
    Sentience present. Yes. No. 

=== Easy
Living (24)::
    Is it alive and living. Yes. No.

Dangerous (24)::
    Is biological organism a threat. 

Flora or Fauna (36)::
    Is the alien flora or fauna. Yes. No. 

Ranged Attacks (36)::
    Is this alien gonna fling stuff. 

=== Normal
Age (42)::
    Estimate chronologic age.

Maturity (42)::
    Estimate stage in life cycle (child, adult).

Smarter than me (42)::
    Is an anthro or alien smarter than the biologist. 

Alien organization (56)::
    Solo, family, herd, pack. 

Leader Finder (56)::
    Identify leader or presence of leader. 

Energy Source (42)::
    What does it eat?

Threat level (42)::
    Degree of danger potential. 

=== Hard
Health Care (84)::
    Is there a healer in the group?

Mutated (84)::
    Mutated. Yes. No.

Mutation Type (84)::
    Psionic or phenomic

=== Tough
Phenomic Identification (126)::
    Identify nature of phenomic mutation. 

=== Impossible
Psionic Identification (168)::
    Identify nature of phenomic mutation. 

=== Bizarre

Cloning (242)::
    Make a copy of a biologic entity.

Gene Design (242)::
    Create new gene expressions. 



== Experience
The benefits of increasing experience levels is increased knowledge, aptitude and knacks, improved task success.
Biologists marginally improve their combat tasks as well.
Biologists earn experience points for completing procedures and role-playing within their vocation.
Only 20% of combat experience can go towards a biologist's experience point total.

include::vocations:partial$biologist_exps.adoc[]


== Biome Constructor
Biome tables are included here for convenience.

include::aliens:partial$biome_list.adoc[]

