= Knites

[quote]
____
*Does orderly or chaotic things.*
____

:art: knitevknites.png
:width: 350px
:snark: Alien knite vs anthro knite.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Two humanoid lizards locked in a psionic control battle.
include::ROOT:partial$articulate.adoc[]

The Knite vocation is a mix of mystical, military and morality.
Knites are mythical and make a clear stand supporting order or chaos. 
They are the only vocation with a strict code of conduct.

The knite vocation combats her foes in the Physical Space and the Think Space simultaneously.
They can use their Strength and Mind simultaneously.

Every persona in the knite vocation is psionically active.
They have no adverse disposition towards using technology, but the knite vocation feels most comfortable wielding their traditional energy sword.

The mental powers of the knite vocation use Kirlian energy. 
EXP includes sciency fiction details about how all this works in its generic mythos.
The referee should understand xref:appendices:generic_mythos.adoc#_the_spaces[The Spaces,window=_blank] and xref:appendices:generic_mythos.adoc#_kirlian_energy[Kirlian Energy,window=_blank] and how these impact the knite vocation.

If the campaign is using attribute requirements for vocations a Knite must have a Mind of at least 18.
Most campaigns will have some sort of trial process before ascension into Order, or Chaos.

== Orders
The knite vocation has two mutually opposing groups.
Both sides manipulate Kirlian energy to fulfill their goals.
Order and chaos are the competing sides of this binary paradigm.
On the side of order is the Knite.
They prefer a steady-state and respect life.
On the side of chaos is the Anti-Knite.
They prefer entropy and do not respect life.
Where one finds Knites, there will be Anti-knites and vice versa.

=== Knites
Knites are the supporters of compassion, goodwill, honesty, and life.
Knites do battle against injustice, intolerance, and enslavement.
They will err on the side of good at every opportunity.
Knites are not pacifists and will deliver fatal justice without a second thought.

:art: anthro_purestrain_knite.png
:width: 250px
:snark: Two swords for justice
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Human woman wearing a onesie holding a sabre and light sword.
include::ROOT:partial$articulate.adoc[]

Knites tend to go off on "damn fool quests."
Knites do not ignore injustices perpetrated by their fellow expedition members.
A knite is a powerful ally in combat but may hinder an expedition's nefarious objectives.

Kirlian energy arises from the interface between the Think Space and the Physical Space. 
The Knite's strong sense of order makes them potent conductors of the Think Space.
This amplification of the Think Space allows them to sense and manipulate the Kirlian energy around them.

=== Anti-Knites
Anti-Knites are the enemies of goodwill, humanity, and organized civilization.
Anti-knites are anti-everything.
An anti-knite is devoted to spreading chaos and entropy, but this does not make them random nihilists.
They can be systematic, calculating and patient.
A complicated plan that leads to more chaos is good.

:art: anthro_purestrain_anti_knite.png
:width: 250px
:snark: Bad in black
:artist: Eric Hotz
:date: 1991
:license: CC BY-SA 4.0
:description: Human woman in black armour wielding a pistol and energy sword. 
include::ROOT:partial$articulate.adoc[]

Anti-Knites tend to organize "complicated deceptions."  
Anti-knites have no regard for personas less powerful than them.
The moment fellow expedition members are no longer valuable to the Anti-Knite, they can expect a savage betrayal.

WARNING: Anti-Knite personas will result in tragedy, and strain player relationships. 

Kirlian energy arises from the interface between the Think Space and the Physical Space. 
The Anti-Knite's strong propensity for chaos makes them potent disruptors of the Physical Space.
This disordering of the Physical Space allows them to sense and manipulate the Kirlian energy around them.

== Practice
In short, Knites must behave, and anti-knites must misbehave.
There is no rigid code of conduct, but there will always be minor errors.
Severe or persistent transgressions may get the persona into trouble.
The consequences for not following their side of order or chaos depend on the transgression. 

The persona may temporarily lose her ability to use Kirlian energy and lose her knite abilities. 
A powerful knite of the same side may appear to remind her of her duties.
A powerful knite of the opposing side may appear to turn her to the other side.

=== Ascension
The knite vocation is powerful and complex.
One does not 'just become' a knite.

.*Process*
. Permission from Referee and Table
. Attribute requirement of Mind 18, or higher
.. Kirlian powers stop if MND < 18
. Ascension Trial


==== Permission
The Knite Anti-Knite paradigm requires extra attention from the referee and must fit into her milieu.
The referee will have to create a mythos if the EXP generic mythos does not fit her milieu.
It is also recommended that the player table be okay with the possibility of an Anti-Knite in their midst.

==== Attribute
The Mind attribute requirement for the knite vocation is sacrosanct.
The persona loses her knite vocation abilities if her Mind score drops below 18.

==== Ascension Trial
It is fine to skip the ascension plot for a Knite persona.
Don't let rules get in the way of the story, or the fun.
However, the ascension of a Knite is very fun, and very storyful. 

The knite is a vocation.
It may or may not involve training. 
It may or may not involve religion.
The ascension trial activates the persona's latent Kirlian connections, and awakens the vocation.
During this trial period, the player's actions determine which side her knite persona will follow.
The righteous will likely become Knites and the ruthless Anti-Knites.
The trial can be an elaborate plotful multi-session mini campaign where Knites and Anti-knites are influencing the persona.
The trial can be as simple as helping a geriatric equine across a busy space walk. 
Upon completion of the trial the persona will realize she has ascended to the codified slavery of the Kirlian energy.

Most knites will function as Nothings without any of the pulls, money or privilege of the Nothing vocation. 
The future knite persona can have a vocation if they desire.
Once they ascend they will eschew all abilities and benefits of that vocation. 
It is possible that a persona can increase through several vocation levels before ascending into knite-dom.

=== Turning
Turning is when a knite moves from order to chaos, or vice versa.
Knites trying to convert Anti-knites to order, and Anti-knites trying to corrupt Knites is a fun plot driver.
However, the EXP mythos has some strong limits on this process.
The referee is free to alter turning to her milieu, but flip flopping knites defeats the purpose of the vocation.

A Knite devoted to order can be turned to the side of chaos.
If a Knite is having a vulnerable time, the forces of chaos may conspire to create a complicated plan to turn her.
Anti-Knites seem always to be prowling around in the dark, waiting for knites to falter.
Once a Knite becomes an Anti-Knite, there is no turning back.

An Anti-Knite devoted to chaos cannot be turned in the physical space.
Only in death can an Anti-Knite be turned.
If an Anti-Knite shows weakness (kindness), the forces of chaos may conspire to create a complicated plan to destroy her.
If an Anti-knite carries out a fatal heroic act of kindness they can become a Knite in martyrdom.

=== Energy Sword
The knite's unique weapon is her energy sword.
The energy sword can be a force field sword, laser sword, or lite sabre.
The knite can do certain things with her energy sword that no other persona can.
These abilities only work with her bespoke energy sword.
The knite cannot pick up any glowing weapon and do knite sword tricks.

=== Death
Death is quite final in EXP. 
There are very few ways to restore a dead persona.
In the case of a knite,  nothing can revive them.
When a knite dies, her Kirlian connection breaks, and she is permanently dead.
Death of a knite has different implications depending on whether the knite is with order or chaos.

A Knite's strong sense of order is a powerful conductor of the Think Space. 
This ordered connection to the Think Space allows them a translucent presence after death.
Dead Knites may occasionally re-appear as translucent immaterial entities to living Knites.

Anti-knites strong sense of chaos is a potent disruptor of the Physical Space.
This chaos  powers their Kirlian energy in the Physical Space, but leads to their complete dissolution at death. 
Dead Anti-Knites swirl in chaotic entropy and makes no smarmy translucent appearances.

== Knowledge
Knite knowledge is split between the physical, the mental and society.
As will all vocation knowledge a mix of interests and expertise influence influences the success of skills. 
In most cases Knite and Anti-Knite knowledge is the same, but their application and goals are different.
There are a few elements of knowledge that are limited to chaos or order. 

NOTE: Knites *cannot* manipulate Kirlian auras through inorganic media like monitors, cameras or phones.

== Interests
Knites have broad areas of interest that improve their chance of succeeding at task rolls.
One knite may have keen interest in manipulating the physical space.
While another knite may be interested studying society.
An interest in the Think Space would assist with any task that involves the think space.

At startup, the persona gets one interest per three points of Intelligence score.
A persona with a 12 INT would get four rolls on the Knite Interest Table. 
After startup the persona earns another interest with each new experience level.

include::vocations:partial$knite_interests.adoc[]

=== Physicum
An interest in the physical space will assist the persona in any task that involves the physical space.
For example, telekinesis involves manipulating the physical space.

=== Cerebrum
An interest in the think space will assist the persona in any task that involves the think space.
For example, intimidation involves manipulating the think space.

=== Culturum
An interest in the cultural space will assist the persona in any task that involves interacting with populations.
For example, interacting with a military institution would be assisted by an interest in the cultural space.

== Expertise
Expertise are areas of increased knowledge focuses on narrower tasks. 
Expertise increases the chances of success for when attempting a task roll. 

At startup the player gets one expertise per interest. 
So a knite with physicum interest 2 and culturum interest 1 would get 2 rolls on the Physicum Expertise Table and 1 roll on the Culturum Expertise Table.
After start up the persona gets one new expertise per new experience level. 

=== Physicum
Physicum expertise represents knowledge and training that supports tasks which impact the physical space.
This can be expertise in areas like energy sword skills or telekinesis.

include::vocations:partial$knite_expert_physicum.adoc[]

=== Cerebrum
Cerebrum expertise represents knowledge and training that supports tasks which impact the think space.
This can be expertise in areas like reading kirlian auras or applying psionic pressure.

include::vocations:partial$knite_expert_cerebrum.adoc[]

=== Culturum
Culturum expertise represents knowledge and training that supports tasks which impact the cultural and political space.
This can be expertise in areas like quickly understanding a religion or finding one's way in a political system.

include::vocations:partial$knite_expert_culturum.adoc[]

== Gifts
Knites are the only vocation that calls their gifts, gifts. 
These gifts are powered by manipulating pervasive Kirlian energy with their mind.
Gifts are tasks that a knite can call on without having to win a task roll.
A gift is like a task that persona can simply use. 
Knite gifts are conveniences and are not meant to destroy plot.

include::vocations:partial$knite_gifts.adoc[]

== Organizing
Knite knowledge is cumulative and can use some organizing.

.*Knite Knowledge*
* Interest Cerebrum
* Expertise See Fate
* Interest Cerebrum
* Expertise See Fate
* Interest Physicum
* Expertise Energy Sword
* Interest Physicum 
* Expertise Mimic
* Expertise Mimic
* Interest Culturum
* Expertise Politics
* Gift Telekinesis

.*Organized Knowledge*
* Interests 
** Cerebrum - 2
** Physicum - 2
** Culturum - 1
* Expertise
** Mimic - 2
** See Fate - 2
** Politics - 1
* Gifts 
** Telekinesis

== Experience
The benefits of increasing experience levels are more refined interpretations and manipulations of Kirlian energy and improved combat skills.
Knites earn experience points for completing tasks and role-playing within their vocation.
Knites earn 100% of combat experience.

include::vocations:partial$knite_exps.adoc[]

== Tasks
Tasks are things that the persona does. 
The player uses her persona's knowledge to improve the chance of completing a skill.

Biologist tasks involve anything organic that does not involve healing.
Most biologist tasks are knowledge based unless an obvious physical intervention is involved.
The minimal equipment required by a biologist is her notebooks. 
The referee may make a target roll more difficult if the biologist does not have her notebooks.

For the intricate details of how to resolve tasks in EXP xref:uncombat:task_rolls.adoc[jump here].

=== Compendium
A non-exhaustive list of biologist skills arranged by increasing difficulty.

Skill Example (42)::
One line description of skill. Difficulty is in brackets. 

==== Trivial
Kirlian Sight (12)::
    See biological outlines without light.

False Rest (12)::
    Appear asleep. Use kirlian site with eyes closed.

Living (12)::
    Is it biological and living? Yes. No.

Kirlian Danger (12)::
    Detect bad intent kirlian aura.

Telekinesis, Drama (12)::
    Attract a light (<1 kg) unfastened object immediately into palm. Range = MND hexes.

==== Easy
Muffle (24 + AWE)::
    Induce silence over a quiet sound. 

Multiple Attacks (24)::
    One attack per gift when using energy sword. 

Kirlian Find (24 + DEX)::
    Find hidden objects or personas.

==== Normal
Imbue Energy Sword (42)::
    Declare a generic energy sword the knite's bespoke energy sword.

Deflect Incoming (42 + DMG)::
    Deflect an energy shoot attack (lazer, plasma) with her energy sword.

Kirlian Truth (42 + MND)::
    See truthfulness of kirlian aura. 

Mimic (42 + AWE)::
    Create benign sound to distract target.

Pressure (42 + MND)::
    Psionically incapacitate a persona with choking fear or guilt. Range = nearby.

Suggestion, Spoken (42 + MND)::
    Get persona to repeat what the knite just spoke.

==== Hard
Disarm, Telekinesis (84 + STR)::
    Attract an opponent's pistol or sword immediately into palm. Range = nearby. 

Kirlian Defence (84 + MND)::
    Double MND when defending against psionic intrusion via the think space. 

Disarm, Energy Sword (84 + DEX)::
    Amputate the weapon hand from an attacker in close combat. Requires strike attack roll. 

Suggestion, Thought (84 + MND)::
    Get persona to repeat what the knite just thought.

==== Tough
Kirlian Intent (126 + MND)::
    See general intent of kirlian aura.

Reflect Incoming (126)::
    Return an energy shoot attack (lazer, plasma) with her energy sword. Raw Shoot Attack. 

Deflect With Palm (126 + DMG)::
    Deflect an energy shoot attack (lazer, plasma) with her open palm.

Telekinesis, Fling (126)::
    Turn random objects into fling attacks. 1d4 DMG per gift, no force bonus.  

==== Impossible
Kirlian Fate (168)::
    See general fate of kirlian aura. 

==== Bizarre
Imbue Talisman (210)::
    Turn a non-technological trinket or knickknack into a Kirlian Talisman. 

Telekinesis, Massive (210)::
    Slowly and dramatically lift something stupidly big. Like a 5000 kg vehicle. Range = nearby.

=== List

include::vocations:partial$knite_tasks.adoc[]



