= Knites

[quote]
____
*Does orderly or chaotic things.*
____

:art: knitevknites.png
:width: 350px
:snark: Alien knite vs anthro knite.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Two humanoid lizards locked in a psionic control battle.
include::ROOT:partial$articulate.adoc[]

The Knite vocation is a mix of mystical, military and morality.
Knites are mythical and make a clear stand supporting order or chaos. 
They are the only vocation with a code of conduct.

The knite vocation combats her foes in the Physical Space and the Think Space at the same time.
They can use their Strength and Mind simultaneously.

Every persona in the knite vocation is psionically active.
They have no adverse disposition towards using technology, but the knite vocation feels most comfortable wielding their traditional energy sword.

The mental powers of the knite vocation use Kirlian energy. 
EXP includes sciency fiction details about how all this works in its generic mythos.
The referee should understand xref:appendices:generic_mythos.adoc#_the_spaces[The Spaces,window=_blank] and xref:appendices:generic_mythos.adoc#_kirlian_energy[Kirlian Energy,window=_blank] and how these impact the knite vocation.

If the campaign is using attribute limitation for vocations a knite must have: 
DEX 15, MIND 18, HPM 25, <<_ascension,Ascension>>.
Some tables do not require ascension, but it is recommended that the MND minimum of 18 be applied.

== Orders
The knite vocation has two mutually opposing groups.
Both sides manipulate Kirlian energy to fulfill their goals.
Order and chaos are the competing sides of this binary paradigm.
On the side of order is the Knite.
They prefer a steady-state and respect life.
On the side of chaos is the Anti-Knite.
They prefer entropy and do not respect life.
Where one finds Knites, there will be Anti-knites and vice versa.

=== Knites
Knites are the supporters of compassion, goodwill, honesty, and life.
Knites do battle against injustice, intolerance, and enslavement.
They will err on the side of good at every opportunity.
Knites are not pacifists and will deliver fatal justice without a second thought.

:art: anthro_purestrain_knite.png
:width: 250px
:snark: Two swords for justice
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Human woman wearing a onesie holding a sabre and light sword.
include::ROOT:partial$articulate.adoc[]

Knites tend to go off on "damn fool quests."
Knites do not ignore injustices perpetrated by their fellow expedition members.
A knite is a powerful ally in combat but may hinder an expedition's nefarious objectives.

Kirlian energy arises from the interface between the Think Space and the Physical Space. 
The Knite's strong sense of order makes them potent conductors of the Think Space.
This amplification of the Think Space allows them to sense and manipulate the Kirlian energy around them.

=== Anti-Knites
Anti-Knites are the enemies of goodwill, humanity, and organized civilization.
Anti-knites are anti-everything.
An anti-knite is devoted to spreading chaos and entropy, but this does not make them random nihilists.
They can be systematic, calculating and patient.
A complicated plan that leads to more chaos is good.

:art: anthro_purestrain_anti_knite.png
:width: 250px
:snark: Bad in black
:artist: Eric Hotz
:date: 1991
:license: CC BY-SA 4.0
:description: Human woman in black armour wielding a pistol and energy sword. 
include::ROOT:partial$articulate.adoc[]

Anti-Knites tend to organize "complicated deceptions."  
Anti-knites have no regard for personas less powerful than them.
The moment fellow expedition members are no longer valuable to the Anti-Knite, they can expect a savage betrayal.

WARNING: Anti-Knite personas in player expeditions will result in tragedy and strain player relationships. 

Kirlian energy arises from the interface between the Think Space and the Physical Space. 
The Anti-Knite's strong propensity for chaos makes them potent disruptors of the Physical Space.
This disordering of the Physical Space allows them to sense and manipulate the Kirlian energy around them.



== Practice
In short, Knites must behave, and anti-knites must misbehave.
There is no rigid code of conduct, but there will always be minor errors.
Severe or persistent transgressions may get the persona into trouble.
The consequences for not following their side of order or chaos depend on the transgression. 

The persona may temporarily lose her ability to use Kirlian energy and lose her knite abilities. 
A powerful knite of the same side may appear to remind her of her duties.
A powerful knite of the opposing side may appear to turn her to the other side.


=== Ascension
The knite vocation is powerful and complex.
One does not 'just become' a knite.

.*Requirement Checklist*
. Ref's <<_milieu,Milieu>>
. <<_attribute_requirements,Attribute Requirements>>
** 15 Dexterity score
** 18 Mind score
** 25 Hit Points
. <<_trial_period,Trial Period>>
. <<_kirlian_ascension,Kirlian Ascension>>

==== Milieu
The Knite Anti-Knite paradigm requires extra attention from the referee and must fit into her milieu.
The referee will have to create a mythos if the EXP generic mythos does not fit her milieu.
In short, the referee will decide if the background-laden vocation of knite is appropriate for her campaign.

==== Attribute Requirements
The Mind attribute requirement for the knite vocation is sacrosanct.
The persona loses her knite vocation abilities if her Mind score drops below 18.

==== Trial Period
The knite is a vocation.
It may or may not involve training. 
It may or may not involve religion.
There is always a trial period where the player must run a none knite persona until she activates the Kirlian energy around her.

The potential knite must start the campaign in a vocation other than knite.
There is no set time for the trial period. 
A persona may gain several levels of experience as a nothing, nomad, mercenary or whatever.
When the knite ascends, she switches to the knite vocation with zero EXPS.

During this trial period, the player's actions determine which side her knite persona will follow.
The righteous will likely become Knites and the ruthless Anti-Knites.

==== Testing
The test event is when the persona realizes she has ascended to the moral slavery of the Kirlian energy.
The referee may devise a life-threatening event where the player has to make an obvious choice between order and chaos.
It is more likely that the persona's behaviour during the trial period decides whether she ascends to order or chaos.

=== Turning
Turning a knite has different implications depending on whether the knite is with order or chaos.

A Knite devoted to order can be turned to the side of chaos.
If a Knite is having a vulnerable time, the forces of chaos may conspire to create a complicated plan to turn her.
Anti-Knites seem always to be prowling around in the dark, waiting for knites to falter.
Once a Knite becomes an Anti-Knite, there is no turning back.

An Anti-Knite devoted to chaos cannot be turned.
If an Anti-Knite shows weakness, the forces of chaos may conspire to create a complicated plan to destroy her.
If an Anti-Knite carries out a fatal heroic act for the side order, this act can posthumously turn her.
Only in death can an Anti-Knite be turned.

=== Energy Sword
The knite's unique weapon is her energy sword.
The energy sword can be a force field sword, laser sword, or lite sabre.
The knite can do certain things with her energy sword that no other persona can.
These abilities only work with her bespoke energy sword.
The knite cannot pick up any glowing weapon and do knite sword tricks.

=== Death
Death is quite final in EXP. 
There are very few ways to restore a dead persona.
In the case of a knite,  nothing can revive them.
When a knite dies, her Kirlian connection breaks, and she is permanently dead.
Death of a knite has different implications depending on whether the knite is with order or chaos.

A Knite's strong sense of order is a powerful conductor of the Think Space. 
This ordered connection to the Think Space allows them a translucent presence after death.
Dead Knites may occasionally re-appear as translucent immaterial entities to living Knites.

Anti-knites strong sense of chaos is a potent disruptor of the Physical Space.
This chaos  powers their Kirlian energy in the Physical Space, but leads to their complete dissolution at death. 
Dead Anti-Knites swirl in chaotic entropy and makes no smarmy translucent appearances.

== Knowledge
Knite knowledge is split between the physical, the mental and society.
As will all vocation knowledge a mix of interests and expertise influence influences the success of skills. 
In most cases Knite and Anti-Knite knowledge is the same, but their application and goals are different.
There are a few elements of knowledge that are limited to chaos or order. 

NOTE: Knites cannot manipulate Kirlian auras through inorganic media like monitors, cameras or phones.

=== Interests
Knites have broad areas of interest that improve their chance of succeeding at task rolls.
One knite may have keen interest in manipulating the physical space.
While another knite may be interested studying society.
An interest in the Think Space would assist with any task that involves the think space.

At startup, the persona gets one interest per three points of Intelligence score.
A persona with a 12 INT would get three rolls on the Knite Interest Table. 
After startup the persona earns another interest with each new experience level.
The player can choose to roll on the Knite Interest Table, or choose a specific interest.

include::vocations:partial$knite_interests.adoc[]

==== Physicum Interest
An interest in the physical space will assist the persona in any task that involves the physical space.
For example, telekinesis involves manipulating the physical space.

==== Cerebrum Interest
An interest in the think space will assist the persona in any task that involves the think space.
For example, intimidation involves manipulating the think space.

==== Culturum Interest
An interest in the cultural space will assist the persona in any task that involves interacting with populations.
For example, interacting with a military institution would be assisted by an interest in the cultural space.

=== Expertise
Expertise are areas of increased knowledge focuses on narrower tasks. 
Expertise increases the chances of success for when attempting a task roll. 

At startup the player gets one expertise per interest. 
So a knite with physicum interest 2 and culturum interest 1 would get 2 rolls on the Physicum Expertise Table and 1 roll on the Culturum Expertise Table.
After start up the persona gets one new expertise per new experience level. 
The player may roll on the expertise table or choose for themselves.

==== Physicum Expertise
Physicum expertise represents knowledge and training that supports tasks which impact the physical space.
This can be expertise in areas like energy sword skills or telekinesis.


include::vocations:partial$knite_skills_physical.adoc[]

==== Cerebrum Expertise
Cerebrum expertise represents knowledge and training that supports tasks which impact the think space.
This can be expertise in areas like reading kirlian auras or applying psionic pressure.

include::vocations:partial$knite_skills_think.adoc[]

==== Culturum Expertise
Culturum expertise represents knowledge and training that supports tasks which impact the cultural and political space.
This can be expertise in areas like quickly understanding a religion or finding one's way in a political system.

include::vocations:partial$knite_culturum.adoc[]

== Skills
Skills are things that the persona does. 
The player uses her persona knowledge to improve the chance of completing a skill.
The persona has special skills called gifts that they automatically succeed at. 

Biologist tasks involve anything organic that does not involve healing.
Most biologist tasks are knowledge based unless an obvious physical intervention is involved.
The minimal equipment required by a biologist is her notebooks. 
The referee may make a target roll more difficult if the biologist does not have her notebooks.

For the intricate details of how to resolve tasks in EXP xref:uncombat:task_rolls.adoc[jump here].

//
// when the compendium is extended do not forget biologist_tasks.adoc table 
//

=== Compendium
A non-exhaustive list of biologist skills arranged by increasing difficulty.

Skill Example (42)::
One line description of skill. Difficulty is in brackets. 

==== Trivial
Kirlian Sight (12)::
    See biological outlines without light.

False Rest (12)::
    Appear asleep. Use kirlian site with eyes closed.

Living (12)::
    Is it biological and living? Yes. No.

Kirlian Danger (12)::
    Detect bad intent kirlian aura.

Telekinesis, Drama (12)::
    Attract a light (<1 kg) unfastened object immediately into palm. Range = MND hexes.

==== Easy
Muffle (24 + AWE)::
    Induce silence over a quiet sound. 

Multiple Attacks (24)::
    One attack per gift when using energy sword. 

Kirlian Find (24 + DEX)::
    Find hidden objects or personas.

==== Normal
Imbue Energy Sword (42)::
    Declare a generic energy sword the knite's bespoke energy sword.

Deflect Incoming (42 + DMG)::
    Deflect an energy shoot attack (lazer, plasma) with her energy sword.

Kirlian Truth (42 + MND)::
    See truthfulness of kirlian aura. 

Mimic (42 + AWE)::
    Create benign sound to distract target.

Pressure (42 + MND)::
    Psionically incapacitate a persona with choking fear or guilt. Range = nearby.

Suggestion, Spoken (42 + MND)::
    Get persona to repeat what the knite just spoke.

==== Hard
Disarm, Telekinesis (84 + STR)::
    Attract an opponent's pistol or sword immediately into palm. Range = nearby. 

Kirlian Defence (84 + MND)::
    Double MND when defending against psionic intrusion via the think space. 

Disarm, Energy Sword (84 + DEX)::
    Amputate the weapon hand from an attacker in close combat. Requires strike attack roll. 

Suggestion, Thought (84 + MND)::
    Get persona to repeat what the knite just thought.

==== Tough
Kirlian Intent (126 + MND)::
    See general intent of kirlian aura.

Reflect Incoming (126)::
    Return an energy shoot attack (lazer, plasma) with her energy sword. Raw Shoot Attack. 

Deflect With Palm (126 + DMG)::
    Deflect an energy shoot attack (lazer, plasma) with her open palm.

Telekinesis, Fling (126)::
    Turn random objects into fling attacks. 1d4 DMG per gift, no force bonus.  

==== Impossible
Kirlian Fate (168)::
    See general fate of kirlian aura. 

==== Bizarre
Imbue Talisman (210)::
    Turn a non-technological trinket or knick-knack into a Kirlian Talisman. 

Telekinesis, Massive (210)::
    Slowly and dramatically lift something stupidly big. Like a 5000 kg vehicle. Range = nearby.

=== Gifts
Knites are the only vocation that calls their gift, gifts. 
These gifts are powered by manipulating pervasive Kirlian energy with their mind.
Gifts are abilities that a knite can call on without having to make a task roll.
A gift is like a task that persona can simply use. 
Knite gifts are conveniences and are not meant to destroy plot.

include::vocations:partial$knite_gifts.adoc[]

== Tasks
Knite tasks are mystical in nature and involve manipulation of the thinkspace.
Knite tasks are considered spiritual gifts or psionic abilities. 
When in combat the knite may be able to get a MND Task Roll bonus.
A knite must have a MND of 18 to perform any of these tasks. 
The knite's MND is an essential piece of equipment.

For the intricate details of how to resolve tasks in EXP xref:uncombat:task_rolls.adoc[jump here].

include::vocations:partial$knite_tasks.adoc[]

== Experience
The benefits of increasing experience levels are more refined interpretations and manipulations of Kirlian energy and improved combat skills.
Knites earn experience points for completing tasks androleplaying within their vocation.
Knites earn 100% of combat experience.

include::vocations:partial$knite_exps.adoc[]


