= Mechanic

[quote]
____
*Repairs and improves inorganic things.*
____

:art: mechanic.png
:width: 250px
:snark: Mechanic mechanizing a mech.
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Humanoid panda with a trucker hat using a wrench.
include::ROOT:partial$articulate.adoc[]

Mechanics are personas with a deep interest in the workings of the inorganic physical world.
The vocation of mechanic encompasses all tasks and knowledge of a technical nature, whether electronic, mechanical, structural, etc.
By definition, mechanics are handy personas.
Their knowledge can range from lazers to sink drains.
Unfortunately, they only have bits and bytes of rudimentary knowledge at their disposal.
Mechanics are exceptionally good at identifying artifacts.
This vocation is essential if the expedition expects to repair equipment or create new contraptions.

If your table is using attribute-determined vocations, a mechanic must have a total INT and DEX greater than or equal to 18.

== Knowledge
Mechanic knowledge focuses on the inorganic world.
The mechanic is in tune with mechanical processes, and fixing/making things is their passion.
Mechanics have areas of interest and expertise.
These interests and expertise are combined to make the persona more likely to succeed at tasks. 

== Interests
Interests are broad approaches to the mechanical world that improve the chance of success when making task rolls.
An interest in repair will help the player win any task roll that involves repair.
If the mechanic is trying to make a better mousetrap, she would benefit from the enhance interest.
When building something that does not exist, or when trying to combine equipment, a research interest is key.

At startup, the persona gets one interest per three points of Intelligence score.
A persona with a 12 INT would get four rolls on the Mechanic Interests Table. 
Each interest roll has an associated expertise roll.
After startup, the persona earns another interest and expertise with each new experience level.

include::vocations:partial$mechanic_interest_list.adoc[]

=== Repair
The repair interest assists the mechanic in any task that returns a mechanism to its undamaged state.
Maintenance of artifacts and toys is also assisted by the repair interest.
By and large, a mechanic cannot repair an object that is destroyed.
The persona could salvage parts from a destroyed object.

=== Enhance
The enhance interest assists the mechanic in any task where they are improving an existing artifact or toy.
For example, improving the range of a crossbow falls under the enhance interest. 
However, if that crossbow is broken, the enhance interest does not benefit the task roll.
Enhancement does not include miniaturization. 

=== Research
The research interest is used to push the boundaries of engineering, fabrication, physics, and Sciency Fiction.
The persona can use the research interest to create a new machine or process.
The research interest can also be used to make a toy smaller or to combine two toys together.

== Expertise
Mechanic expertise represents more specific areas of knowledge.
The expertise can represent tasks or very focused processes.
The player can stack expertise and interests.

At startup, the player gets one expertise per interest.
A mechanic with repair 2 and enhance 1 would get three rolls on the mechanic expertise table.
After startup, the persona gets one new expertise per new experience level.
As described above, the player can roll or choose the new expertise.

include::vocations:partial$mechanic_expert.adoc[]

== Gifts
The mechanic's gifts are tasks where the persona automatically succeeds.

include::vocations:partial$mechanic_gifts.adoc[]

== Experience
The benefits of increasing experience levels are more tasks, improved task roll success, and somewhat better combat tasks.
Mechanics earn experience points for completing procedure rolls (80 EXPS per DD) and role-playing within their vocation.
Only 20% of combat experience can go toward a mechanic's experience point total.

include::vocations:partial$mechanic_exps.adoc[]

== Tasks
Mechanic tasks involve anything inorganic or mechanical in nature.
These tasks are all about fixing, modifying, and creating mechanical devices.
Most mechanic tasks are knowledge, and Dexterity based.
Task roll bonuses will reflect this.

A mechanic must have a tool to work with.
This can be any kind of tool that is not improvised from the persona's body (a slap does not equal a hammer).
The referee may increase the task difficulty if the mechanic does not have a tool.

For details of how to resolve tasks in EXP, jump to xref:uncombat:task_rolls.adoc[Task Rolls].

=== Compendium
A non-exhaustive list of mechanic tasks arranged by increasing difficulty.

include::vocations:partial$mechanic_compendium.adoc[]

=== List
A similar list of tasks arranged in alphabetical order. 

include::vocations:partial$mechanic_tasks.adoc[]
