= Mechanic

[quote]
____
*Repairs and improves inorganic things.*
____

:art: mechanic.png
:width: 250px
:snark: Mechanic mechanizing a mech.
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description:
:description: Humanoid panda with a trucker hat using a wrench.
include::ROOT:partial$articulate.adoc[]

Mechanics are personas with a deep interest in the workings of the inorganic physical world.
The vocation of mechanic encompasses all tasks and knowledge of a technical nature, whether electronic, mechanical, structural, etc.
By definition, mechanics are handy personas.
Their knowledge can range from lasers to sink drains.
Unfortunately, they only have bits and bytes of rudimentary knowledge at their disposal.
Mechanics are exceptionally good at identifying artifacts.
This vocation is essential if the expedition expects to repair equipment or create new contraptions.

If your table is using attribute-determined vocations, a mechanic must have a total INT and DEX greater than or equal to 18.

== Knowledge
Mechanic knowledge focuses on the inorganic world.
The mechanic is in tune with mechanical processes, and fixing/making things is their passion.
Mechanics have areas of interest and expertise.
These interests and expertise are combined to make the persona more likely to succeed at tasks. 

== Interests
Interests are broad approaches to the mechanical world that improve the chance of success when making task rolls.
An interest in repair will help the player win any task roll that involves repair.
If the mechanic is trying to make a better mousetrap, she would benefit from the enhance interest.
When building something that doesn't exist, or when trying to combine equipment, a research interest is key.

At startup, the persona gets one interest per three points of Intelligence score.
A persona with a 12 INT would get three rolls on the Mechanic Interests Table. 
Each interest roll has an associated expertise roll.
After startup the persona earns another interest and expertise with each new experience level.

include::vocations:partial$mechanic_interest_list.adoc[]

=== Repair
The repair interest assists the mechanic in any task that returns a mechanism to its undamaged state.
Maintenance of artifacts and toys is also assisted by the repair interest.
By and large, a mechanic cannot repair an object that is destroyed.
The persona could salvage parts from a destroyed object.

=== Enhance
The enhance interest assists the mechanic in any task where they are improving an existing artifact or toy.
For example, improving the range of a crossbow falls under the enhance interest. 
However, if that crossbow is broken, the enhance interest does not benefit the task roll.
Enhancement does not include miniaturization. 

=== Research
The research interest is used to push the boundaries of engineering, fabrication, physics, and sciency fiction.
The persona can use the research interest to create a new machine or process.
The research interest can also be used to make a toy smaller or to combine two toys together.

== Expertise
Mechanic expertise represents more specific areas of knowledge.
The expertise can represent tasks or very focused processes.
The player can stack expertise and interests.

At startup, the player gets one expertise per interest.
So a mechanic with repair 2 and enhance 1 would get three rolls on the mechanic expertise table.
After startup, the persona gets one new expertise per new experience level.
As described above the player can roll or choose the new expertise.

include::vocations:partial$mechanic_expert.adoc[]

== Crafts
The mechanic’s crafts (gifts) are tasks where the persona automatically succeeds.
New actions are added when the persona gains more experience levels.

include::vocations:partial$mechanic_crafts.adoc[]

== Organizing
Mechanic expertise and interests are cumulative and combinable.

.Example Mechanic Knowledge
* Interest Repair
* Interest Repair
* Expertise Mending
* Interest Enhance
* Expertise Chemistry
* Expertise Detectors
* Craft Broken?
* Expertise Mending

.Reorganized Knowledge
* Interest
** Repair - 2
** Enhance - 1
* Expertise
** Mending - 2
** Chemistry - 1
** Detectors - 1
* Craft (gift)
** Is it broken?

== Experience
The benefits of increasing experience levels are more tasks, improved task roll success, and somewhat better combat tasks.
Mechanics earn experience points for completing procedure rolls (80 EXPS per DD) and role-playing within their vocation.
Only 20% of combat experience can go towards a mechanic's experience point total.

include::vocations:partial$mechanic_exps.adoc[]

== Tasks
Mechanic tasks involve anything inorganic or mechanical in nature.
These tasks are all about fixing, modifying, and creating mechanical devices.
Most mechanic tasks are knowledge-based, and Dexterity-based task roll bonuses will reflect this.

A mechanic must have a tool to work with. 
This can be any kind of tool that is not improvised from the persona's body (a slap does not equal a hammer).
The referee may increase the task difficulty if the mechanic does not have a tool.

For the intricate details of how to resolve tasks in EXP, jump to xref:uncombat:task_rolls.adoc[Task Rolls].

=== Compendium
A non-exhaustive list of mechanic tasks arranged by increasing difficulty.

Skill Example (42)::
One-line description of skill. Difficulty is in brackets.

[discrete]
==== Trivial
Mechanical (12)::
    Is it a machine? Yes/No.

Broken (12)::
    Is it broken? Yes/No.

[discrete]
==== Easy
Quick Repair (24)::
    Unbreak for one more use. Trivial or minor damage.

Bake A Pie (24)::
    Make a pie from ingredients.

[discrete]
==== Normal
Mnemonic Trapping (42)::
    Memorize a technical thing.

Scavenge Parts (42)::
    Get some good parts from a machine.

Repair (42)::
    Fully repair less than major damage.

Find Data (42)::
    Get needed data from data stream.

Terminal Access (42)::
    Access a computer.

ID Normal-Tech Artifact (42)::
    Identify toy, tech level 10.

[discrete]
==== Hard
Hard Repair (84)::
    Fully repair less than critical damage.

Reverse Polarity (84)::
    Make a machine go backwards. Once. 

ID Low-Tech Artifact (84)::
    Identify toy, tech level less than 10.

[discrete]
==== Tough
Robot Override (126)::
    Temporarily block a robot goal.

Tough Repair (126)::
    Fully repair less than Cataclysmic damage.

Compactify (126)::
    Decrease wate by 2×.

ID High-Tech Artifact (126)::
    Identify toy, tech level 15 to 19.

Priority Command (126 + CF)::
    Damage a robot with words and sounds.

Multi-equip (148)::
    Integrate two toys into one.

[discrete]
==== Impossible
ID Alien Artifact (168)::
    Identify alien artifact or tech level 20+ artifact.

Sotto to Flotto (168)::
    Move a gun to full auto.

Miniaturization (168)::
    Decrease wate by 10 times. 

Robotic Override (168 + CF0)::
    Temporarily control a robot or part of a robot.

[discrete]
==== Bizarre
Robot Control (210)::
    Take over a robot.

Fabricate (210)::
    Create a new toy. 

=== List
A similar list of tasks arranged in alphabetical order. 

include::vocations:partial$mechanic_tasks.adoc[]
