= Mechanic

[quote]
____
*Repairs and improves inorganic things.*
____

:art: mechanic.png
:width: 250px
:snark: Mechanic mechanizing a mech.
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: 
:description: Humanoid panda with trucker hat using a wrench.
include::ROOT:partial$articulate.adoc[]

Mechanics are personas with a deep interest in the inorganic physical world's workings.
The vocation of mechanic encompasses all skills and knowledge of a technical nature, whether electronic, mechanical, structural, etc.
By definition, mechanics are handy personas.
Their skills can range from lasers to sink drains.
Unfortunately, they only have bits and bytes of rudimentary knowledge at their disposal.
Mechanics are exceptionally skilled at identifying artifacts.
This vocation is essential if the expedition expects to repair equipment or create new contraptions.

If your game limits vocations by attributes a mechanic must have an INT 13 or higher.

== Knowledge
Mechanic knowledge focuses on the inorganic world. 
The mechanic is in tune with mechanical processes, and fixing/making things is their passion.
Mechanics have areas of interest and expertise based.
These interests and expertise are combined to make the persona more likely to succeed at skills. 

=== Interests
Interests are broad approaches to the mechanical world that improve the chance of success when making task rolls.
An interest in repair will help the player win any task roll that involves repair.
If the mechanic is trying to make a better mousetrap she would benefit from the enhance interest.
When building something that doesn't exist, or when trying to combine equipment a research interest is key. 

At startup, the persona gets one interest per three points of Intelligence score.
A persona with a 12 INT would get three rolls on the Mechanic Interest Table. 
Each interest roll has an associated expertise roll. 
After startup the persona earns another interest and expertise with each new experience level.
The player can choose to roll on the Mechanic Interest Table, or choose a specific interest

include::vocations:partial$mechanic_interest_list.adoc[]

==== Repair Interest
The repair interest assists the mechanic in any task that is returning a mechanism to it's undamaged state.
Maintenance of artifacts and toys is also assisted by the repair interest.
By and large a mechanic cannot repair an object that is destroyed. 
The persona could salvage parts from a destroyed object

==== Enhance Interest
The enhance interest assists the mechanic in any task where they are improving and existing artifact or toy.
For example, improving the range of a crossbow falls under the enhance interest. 
However if that crossbow is broken, the enhance interest does not benefit the task roll. 
Enhancement does not include miniaturization. 

==== Research Interest
The research interest is used to push the boundaries of engineering, fabrication, physics, and sciency fiction.
The persona can use the research interest to create a new machine, or process. 
THe research interest can also be used to make toy smaller, or to combine two toys together.

=== Expertise
Mechanic expertise represents more specific areas of knowledge. 
The expertise can represent tasks or very focused processes. 
The player can stack expertise and interests 

At startup the player gets one expertise per interest. 
So a mechanic with repair 2 and enhance 1 would get 3 rolls on the mechanic expertise table.
After start up the persona gets one new expertise per new experience level. 
As described above the player can roll or choose the new expertise.

include::vocations:partial$mechanic_skills.adoc[]

=== Organizing
Mechanic expertise and interests are cumulative and combinable.

.Example Mechanic Knowledge
* Repair interest 2
* Enhance interest 1
* Chemistry expertise 3
* Detectors expertise 1
* Mending expertise1

To improve lubrication of a vehicle the player could use Enhance 1 and Chemistry 3 when calculating competency 

== Skills
For some reason there is a lot of detail available regarding mechanic abilities. 
This is probably due to game play edge cases encountered running previous mechanic personas. 

=== Compendium
A none exhaustive list of mechanic skills arranged by increasing difficulty.

Skill Example (42) ::
One line description of skill. Difficulty is in brackets. 

==== Trivial


==== Easy


==== Normal


==== Hard



==== Tough


==== Impossible


==== Bizarre



=== Mnemonic Trapping 
Mnemonic trapping allows the mechanic to memorize crucial technical information. 
A mechanic can mnemonically trap dimensions, instructions, serial numbers, or other technical information. 
To memorize important information, the player must win a task roll.
The degree of difficulty (DD) of the task roll increases with the information's amount and complexity.
None technical information like people's names or anniversaries is even more difficult to mnemonically trap.
This ability's typical DD range is 1-8 (1d8).

=== Brainstorming
This ability allows the mechanic to solve complex problems by thinking laterally and thinking imaginatively.
Using brainstorming can solve a problem completely, partially, or not at all.
If the brainstorming attempt fails, the persona will most likely postulate a hair-brained idea instead of no idea.
The difficulty (DD) of the task roll increases with the complexity of the mechanical problem.
Plot points and interpersonal problems are resistant to Brainstorming. 
This ability's typical DD range is 1-20 (1d20).

=== Mental Patenting
The mechanic can memorize a maneuver that she has successfully completed.
Mental patenting allows the mechanic to repeat the maneuver flawlessly.
If the mechanic is upgrading ammo for a mercenary repeatedly, she may want to mentally patent the procedure.
Successful mental patenting will allow her to upgrade the ammo flawlessly in the future.
Mental patented maneuvers do not work with research teams.
Mental patented maneuvers do not earn experience points.
This ability's degree of difficulty is three times the maneuver DD.
To mentally patent a 4DD maneuver requires a DD12 task roll.

== Task Examples
Mechanic tasks involve anything inorganic or mechanical in nature.
These tasks are all about fixing, modifying and creating mechanical devices.
Most mechanic tasks are knowledge based and Dexterity based task roll bonuses will reflect this.

A mechanic must have a tool to work with. 
This can be any kind of tool that is not improvised from the persona's body (a slap does not equal a hammer).
The referee may increase the task difficulty if the mechanic does not have a tool.

For the intricate details of how to resolve tasks in EXP xref:uncombat:task_rolls.adoc[jump here].

include::vocations:partial$mechanic_tasks.adoc[]

=== Crafts
A mechanic's crafts (gifts) define the persona as a mechanic. 
Crafts are the inherent abilities that reflect how the persona is in tune with the organic world. 
Crafts cannot be chosen, and are added as the persona increases in experience levels.

include::vocations:partial$mechanic_crafts.adoc[]

== Experience
The benefits of increasing experience levels are more skills, improved task roll success, and somewhat better combat skills. Mechanics earn experience points for completing procedures rolls (80 EXPS per DD) and role-playing within their vocation. Only 20% of combat experience can go towards a mechanic's experience point total.

include::vocations:partial$mechanic_exps.adoc[]


