= Nomad

[quote]
____
*Survive using few things.*
____

:art: nomad_urban.png
:width: 250px
:snark: Urban nomad in city biome.
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid antelope pushing a shopping cart full of tech junk.

include::ROOT:partial$articulate.adoc[]

Nomads are survivalists.
They are experts at finding their way, constructing a shelter, and doing well with nothing more than their bare hands.
Other vocations cannot grasp the subtleties necessary to adapt to and live off an environment.
It is doubtful that there are accredited schools of nomadic adventure.
The persona most likely was born with these inherent survival abilities.
A nomad's survival abilities may have appeared out of necessity due to some scarcity situation.
Nomads can aid the expedition by providing a source of intuitive survival skills.

NOTE: Nomads can be sociable and have no political baggage.  

Nomads will generally shun technology if it is unnecessary for survival.
They may prefer to sleep in a hollow log or a dumpster rather than a hotel room or tent.
There is no penalty for a nomad who uses technology.

If the campaign is limited vocations by attributes nomads have the following minimums:
AWE 10, CON 6, INT 5 and HPM 20

== Knowledge
Nomadic knowledge is focused on biomes, survival and domestication. 
The interests are broad areas that the nomad excels in.
An interest can be applied to many different skills.
An expertise is more focused, and offers greater benefit to appropriate task rolls. 

=== Interests
Interests are broad abilities that can represent experience that can assist skills and tasks. 
Nomad interests are intentionally wide ranging and can be very loosely applied to most any nomad task.

At startup the persona gets one interest per 3 points of Awareness, and one additional interest per new experience level. 

include::vocations:partial$nomad_interests.adoc[]

==== Biome Interest
Biomes are the bread and butter of a nomad. 
A biome is a geographically, ecologically or socially unique location.
The biome interest will assist any endeavour that involves a biome. 
This is astoundingly broad and it is rare that a nomad task does not involve a biome. 
A nomad that has a nomad interest automatically gets a biome expertise. 

==== Survival Interest
All nomads, and all personas for that matter, are interested in surviving.
A survival interest will assist the player in any task rolls that represents survival tasks.
For example, a safe passage task roll would benefit from the survival interest. 
Whereas trying to domesticate an alien pack mammal would not.

==== Domestication Interest
Nomads can have an interest in domestication aliens for their personal use. 
Domestication helps the nomad when working with aliens from the diversidae family.
While an anthro may be __alien__ this expertise only applies to diversidae aliens.  
The domestication interest will assist the persona in tasks that are part of domesticating aliens.

=== Expertise
Skills are specific abilities that assist with more specific task rolls. 
A skill could represent knowledge, experience or training. 
The player rolls one skill per interest, and if the person earns another interest they gain another skill. 

==== Biome Expertise
A biome is a geographically, ecologically or socially unique location.
The nomad is assisted for any task attempted in a familiar biome.
Biome expertise is cumulative and assists literally any task roll 

Due to space considerations the biome constructor is found at the end of this page <<_biome_constructor,Jump there>>.

:art: nomad.png
:width: 250px
:snark: Nomads desert biome.
:artist: Louis Glanzman
:date: 1952
:license: CC BY-SA 4.0
:description: Two humans sheltering from sun in an alien desert.
include::ROOT:partial$articulate.adoc[]

==== Survival Expertise
Survival expertise is knowledge that assists the nomad in performing survival tasks. 
This expertise area includes things like finding water or calming a feral alien. 
Remember to include biome expertise with survival task rolls.

include::vocations:partial$nomad_skills_survival.adoc[]

==== Domestication Expertise
Domestication expertise helps the nomad when working with aliens from the diversidae family.
While an anthro may be __alien__ this expertise only applies to diversidae aliens.  
The aliens that domestication skills work on are typically flora and fauna. 
Remember to include biome expertise with domestication task rolls.

include::vocations:partial$nomad_skills_domestication.adoc[]

== Skills
Nomad skills are about surviving and manipulating the environment surrounding the persona.
These terrains are called biomes and can be natural, industrial or residential.
These skills  are about personal survival.

A nomad has no essential equipment.
Unlike any other vocation a nomad may be inhibited by survival tools like tents, or fire starters.
The referee may increase task difficulty if the nomad is glamping (glamorous camping).

For the intricate details of how to resolve tasks in EXP xref:uncombat:task_rolls.adoc[jump here].

=== Compendium
A none exhaustive list of nomad skills arranged by increasing difficulty.

Skill Example (42)::
One line description of skill. Difficulty is in brackets. 

==== Trivial
Biological (12)::
    Is it biological? Yes. No. 

Sentience (12)::
    Sentience present. Yes. No. 

Passage In Safety (12)::
    Find safe passage when no danger

Living (18)::
    Is it alive and living. Yes. No.

==== Easy
Water Safety (24)::
    Safe water in wet biomes.

Edible (24)::
    Is it edible? Yes. No. 

Make Sausage (24)::
    Make a yummy sausage. 

Shelter from Forest (24)::
    Make self shelter in dense vegetation. 

Fire From Something (24)::
    Make fire when stuff around. 

Preserves (24)::
    Preserve food for later. 

==== Normal
Quick Fix (42)::
    Heal 1d6 HPS immediately.

Food from Food (42)::
    Make normal survival food safe. 

Energy Source (42)::
    What does it eat?

Water From Rocks (42)::
    Find water in Dry biomes.

Shelter from Nothing (42)::
    Make safe shelter in city or tundra. 

Make Clothing (42)::
    Make appropriate survival clothing. 

Quick Fix (42)::
    Heal 1d6 HPS immediately.

Poison Arrest (56)::
    Stop poison progress. Not heal

==== Hard
Alien organization (84)::
    Solo, family, herd, pack. 

Food from Toxic (84)::
    Make toxic survival food safe. 

Fire from Nothing (84)::
    Make fire in denuded areas. 

Make Cammo (84)::
    Make camouflaged clothing for biome. 

Calm Frenzy (84)::
    Arrest and ursidae frenzy.

Poison Reverse (84)::
    Reverse the effects of a poison (except HPS damage).

Radiation Arrest (84)::
    Stop ongoing effects of radiation.

==== Tough
Water from Sand (126)::
    Find water in arid biomes. 

Shelter from Eyes (126)::
    Make safe shelter under surveillance.

Food from Poison (126)::
    Make poisonous food safe.

Poison Cure (126)::
    Reverse all poison effects (even HPS damage).

==== Impossible
Food from Pharma (168)::
    Turn pharma into food. 

==== Bizarre
Water from Vacuum (210)::
    Find water exatmo.

Track across Vacuum (210)::
    Find target across planets.



=== Domestication
Nomadic domestication involves the befriending and training of alien flora and fauna.
Aliens with language, culture, education, vocations or tool users are not flora or fauna.
Domestication is limited to flora and fauna aliens.
Domestication does not work during combat or with violently defeated aliens.
Domestication does not work with hungry aliens where the nomad is dinner.
Robots cannot be domesticated.

.*Domestication Stages*
. Befriending 1-25 (INT) DD
. Taming 2-50 (2*INT) DD
. Training 2-50 (Assigned) DD

Befriending is the first stage of domestication. 
Befriending indicates an alien that trusts and won't run from the nomad.
The degree of difficulty (DD) for befriending is equal to the alien's INT.

Taming is the second stage of domestication. 
The nomad must befriend an alien before being taming.
Taming indicates the alien has attained a pet status.
The degree of difficulty (DD) for taming is equal to twice the alien's INT.

Train for tricks is the third stage of domestication.
The nomad must tame an alien before teaching tricks.
The referee and players assign the DD of the trick.
The more valuable the trick, the higher the DD.
The player must win a task roll at double the trick's DD to train the alien.
The player must win a task roll to carry out the trick successfully.
Failing to carry out a trick should be humorous, not deadly.

The nomad has decided to domesticate a Festinated Wumpus. 
The Festinated Wumpus has a 4 INT. 
The Wumpus is a herbivore that the expedition has never hunted or killed.
The Wumpus does not use tools and has no language. 

To befriend the Wumpus, the nomad must make a 4DD task roll.
To tame the Wumpus, the nomad must make an 8DD task roll.
Training the Wumpus to retrieve an ammo pack is a 12DD trick.
To train the trick is a 24DD task roll.
The nomad must win a 12DD task roll every time the Wumpus retrieves an ammo pack.

=== Safe Passage
The nomad can determine a safe passage through seemingly impassable terrain: a mountain range, a toxic area, or a red light district.
Safe passage may require multiple task rolls: one roll to get through the city and another to avoid police.
The DD for safe passage has a range of 1-12 (1d12).
Safe passage cannot avoid plot points or story elements.

=== Tracking
Nomads can track anything that they want.
Tracking is not limited to flora and fauna. 
The nomad can track robots and vehicles as well.
There are two aspects of tracking, following and finding.

..*Tracking Abilities*
* Following 1-10 (1d10) DD
** Avoiding add INT
* Finding 1-10 (1d10) DD
** Hiding add INT
* Reverse tracking 2-50 (2*INT) DD

.Following
Following is used to keep up with a moving target. 
Following uses clues and intuition to track an unseen target.
The ability can follow an alien in the forest or a taxi in a megalopolis.
The nomad follows her target until the target stops moving.
If a target is trying to avoid following the target's Intelligence is added to the DD.
A successful following of a target does not guarantee successfully finding a target.

.Finding
Finding places the nomad face to face with her target.
If the target was initially moving, the player must win a task roll for following first.
After following an alien for a few hours in the forest, the player must win a finding maneuver to get that photograph.
If a target is not moving, the player needs only win a finding maneuver.
Finding a deserted warehouse in a city or a persona hiding in the bushes are two examples.
If a target is hiding, the player must add the target's Intelligence to the DD of the finding maneuver.
Finding hidden intelligent personas can be very hard indeed.

.Reverse Tracking
This ability allows the nomad to determine if she is being tracked. 
Reverse tracking lets the nomad know that she is being tracked.
To determine what is tracking her, the player must win a following and finding task rolls.
The nomad will have to follow and find what is tracking her using the 


== Organizing Abilities

.Example Nomad SKills 
* Farm, Toxic
* Forest, Toxic
* Farm, Underground
* Coniferous, Normal

.Reorganized Skills
* Farm - 2
* Toxic - 2
* Forest - 1
* Coniferous - 1
* Underground - 1

Skills are cumulative and separable. 
A nomad trying to follow a rogue tractor on a toxic (2) farm (2) would get +4 on her task roll.
Finding a safe campsite in an underground (1) cave have a bonus of +1.

:art: biome_modern_space.png
:width: 450px
:snark: Biomes are not just trees and dirt.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Landscape of futuristic wall in front of planet and stars.
include::ROOT:partial$articulate.adoc[]



=== Adaptations
The nomad's adaptations (gifts) are skills where the persona automatically succeeds.
New adaptations are added when the persona gains more experience levels.

include::vocations:partial$nomad_adaptations.adoc[]

== Experience
Nomads get half experience for combat and EXPS for successful maneuvers.
Faithful role-playing of the nomad vocation will earn EXPS for the persona.
Increasing levels allows the nomad a greater chance of survival in the wild or combat.

include::vocations:partial$nomad_exps.adoc[]

== Biome Constructor
Biome tables are included here for convenience.

include::aliens:partial$biome_list.adoc[]


