= Nomad

[quote]
____
*Survive using few things.*
____

:art: nomad_urban.png
:width: 250px
:snark: Urban nomad in city biome.
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid antelope pushing a shopping cart full of tech junk.

include::ROOT:partial$articulate.adoc[]

Nomads are survivalists.
They are experts at finding their way, constructing a shelter, and doing well with nothing more than their bare hands.
Other vocations cannot grasp the subtleties necessary to adapt to and live off an environment.
It is doubtful that there are accredited schools of nomadic adventure.
The persona most likely was born with these inherent survival abilities.
A nomad's survival abilities may have appeared out of necessity due to some scarcity situation.
Nomads can aid the expedition by providing a source of intuitive survival skills.

NOTE: Nomads can be sociable and have no political baggage.  

Nomads will generally shun technology if it is unnecessary for survival.
They may prefer to sleep in a hollow log or a dumpster rather than a hotel room or tent.
There is no penalty for a nomad who uses technology.

If the campaign is limited vocations by attributes nomads have the following minimums:
AWE 10, CON 6, INT 5 and HPM 20

== Knowledge
Nomadic knowledge is focused on biomes, survival and domestication. 
The interests are broad areas that the nomad excels in.
An interest can be applied to many different skills.
An expertise is more focused, and offers greater benefit to appropriate task rolls. 

=== Interests
Interests are broad abilities that can represent experience that can assist skills and tasks. 
Nomad interests are intentionally wide ranging and can be very loosely applied to most any nomad task.

At startup the persona gets one interest per 3 points of Awareness, and one additional interest per new experience level. 

include::vocations:partial$nomad_interests.adoc[]

==== Biome Interest
Biomes are the bread and butter of a nomad. 
A biome is a geographically, ecologically or socially unique location.
The biome interest will assist any endeavour that involves a biome. 
This is astoundingly broad and it is rare that a nomad task does not involve a biome. 
A nomad that has a nomad interest automatically gets a biome expertise. 

:art: biome_modern_space.png
:width: 450px
:snark: Biomes are not just trees and dirt.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Landscape of futuristic wall in front of planet and stars.
include::ROOT:partial$articulate.adoc[]

==== Survival Interest
All nomads, and all personas for that matter, are interested in surviving.
A survival interest will assist the player in any task rolls that represents survival tasks.
For example, a safe passage task roll would benefit from the survival interest. 
Whereas trying to domesticate an alien pack mammal would not.

==== Domestication Interest
Nomads can have an interest in domestication aliens for their personal use. 
Domestication helps the nomad when working with aliens from the diversidae family.
While an anthro may be __alien__ this expertise only applies to diversidae aliens.  
The domestication interest will assist the persona in tasks that are part of domesticating aliens.

=== Expertise
Skills are specific abilities that assist with more specific task rolls. 
A skill could represent knowledge, experience or training. 

At startup the persona gets one area of expertise per interest. 
So a nomad with Domestication 2 and Survival 1 would get 2 rolls on the Domestication expertise table and 1 roll on the Survival expertise table.
After start up the persona gets one new expertise per experience level. 
The player can roll on one of the expertise tables or choose a specific expertise.




==== Biome Expertise
A biome is a geographically, ecologically or socially unique location.
The nomad is assisted for any task attempted in a familiar biome.
Biome expertise is cumulative and assists literally any task roll 

Due to space considerations the biome constructor is found at the end of this page <<_biome_constructor,Jump there>>.

:art: nomad.png
:width: 250px
:snark: Nomads desert biome.
:artist: Louis Glanzman
:date: 1952
:license: CC BY-SA 4.0
:description: Two humans sheltering from sun in an alien desert.
include::ROOT:partial$articulate.adoc[]

==== Survival Expertise
Survival expertise is knowledge that assists the nomad in performing survival tasks. 
This expertise area includes things like finding water or calming a feral alien. 
Remember to include biome expertise with survival task rolls.

include::vocations:partial$nomad_skills_survival.adoc[]

==== Domestication Expertise
Domestication expertise helps the nomad when working with aliens from the diversidae family.
While an anthro may be __alien__ this expertise only applies to diversidae aliens.  
The aliens that domestication skills work on are typically flora and fauna. 
Remember to include biome expertise with domestication task rolls.

include::vocations:partial$nomad_skills_domestication.adoc[]

=== Organizing
Knowledge is cumulative and separatory.
This means that an expertise in the biome Arid, Freezing, Desert Ruins, can be combined with the biome Arid, Hot, Tundra Ruins. 

.Organizing Biome Expertise 
* Arid, Freezing, Desert Ruins
* Arid, Hot, Tundra Ruins
* Passage, Back track
* Passage, hidden

.Reorganized Skills
* Arid - 2
* Ruins - 2
* Passage - 2
* Freezing - 1
* Desert - 1
* Back track - 1
* Hidden - 1

When attempting a skill like hidden (1) safe passage (2) in arid (2) ruins (2) the expertise is 7.
Biome expertise is very helpful when attempting nomad skills.   

== Skills
Nomad skills are about surviving and manipulating the environment surrounding the persona.
These terrains are called biomes and can be natural, industrial or residential.
These skills  are about personal survival.

A nomad has no essential equipment.
Unlike any other vocation a nomad may be inhibited by survival tools like tents, or fire starters.
The referee may increase task difficulty if the nomad is glamping (glamorous camping).

For the intricate details of how to resolve tasks in EXP xref:uncombat:task_rolls.adoc[jump here].

=== Compendium
A none exhaustive list of nomad skills arranged by increasing difficulty.

Skill Example (42)::
One line description of skill. Difficulty is in brackets. 

==== Trivial
Biological (12)::
    Is it biological? Yes. No. 

Sentience (12)::
    Sentience present. Yes. No. 

Passage In Safety (12)::
    Find safe passage when no danger

Living (18)::
    Is it alive and living. Yes. No.

==== Easy
Water Safety (24)::
    Safe water in wet biomes.

Edible (24)::
    Is it edible? Yes. No. 

Make Sausage (24)::
    Make a yummy sausage. 

Shelter from Forest (24)::
    Make self shelter in dense vegetation. 

Fire From Something (24)::
    Make fire when stuff around. 

Preserves (24)::
    Preserve food for later. 

Track, Oblivious (24)::
    Follow and find prey unaware of tracking. 

==== Normal
Quick Fix (42)::
    Heal 1d6 HPS immediately.

Food from Food (42)::
    Make normal survival food safe. 

Energy Source (42)::
    What does it eat?

Water From Rocks (42)::
    Find water in Dry biomes.

Shelter from Nothing (42)::
    Make safe shelter in city or tundra. 

Make Clothing (42)::
    Make appropriate survival clothing. 

Quick Fix (42)::
    Heal 1d6 HPS immediately.

Track on Land (42 + INT)::
    Follow and find typical prey. 

Poison Arrest (56)::
    Stop poison progress. Not heal.

==== Hard
Alien organization (84)::
    Solo, family, herd, pack. 

Food from Toxic (84)::
    Make toxic survival food safe. 

Fire from Nothing (84)::
    Make fire in denuded areas. 

Make Cammo (84)::
    Make camouflaged clothing for biome. 

Calm Frenzy (84)::
    Arrest and ursidae frenzy.

Poison Reverse (84)::
    Reverse the effects of a poison (except HPS damage).

Radiation Arrest (84)::
    Stop ongoing effects of radiation.

Track in Water (84 + INT)::
    Find and follow prey in water.

Domesticate, Befriend (84)::
    Make flora fauna alien follow around

Domesticate, Tricks (104)::
    Train flora fauna alien some simple tricks.

==== Tough
Water from Sand (126)::
    Find water in arid biomes. 

Shelter from Eyes (126)::
    Make safe shelter under surveillance.

Food from Poison (126)::
    Make poisonous food safe.

Poison Cure (126)::
    Reverse all poison effects (even HPS damage).

Domesticate, Imprint (126)::
    Make flora fauna alien friend. 

Track in air (126 + INT)::
    Follow and find flying prey.


==== Impossible
Food from Pharma (168)::
    Turn pharma into food. 

==== Bizarre
Water from Vacuum (210)::
    Find water exatmo.

Track across Vacuum (210)::
    Find target across planets.

Domesticate, Parentalize (210)::
    Make flora fauna alien protect nomad like their spawn.

=== Adaptations
The nomad's adaptations (gifts) are skills where the persona automatically succeeds.
New adaptations are added when the persona gains more experience levels.

include::vocations:partial$nomad_adaptations.adoc[]

== Experience
Nomads get half experience for combat and EXPS for successful maneuvers.
Faithful role-playing of the nomad vocation will earn EXPS for the persona.
Increasing levels allows the nomad a greater chance of survival in the wild or combat.

include::vocations:partial$nomad_exps.adoc[]

== Biome Constructor
Biome tables are included here for convenience.

include::aliens:partial$biome_list.adoc[]


