= Nomad

[quote]
____
*Survive using few things.*
____

:art: nomad_urban.png
:width: 250px
:snark: Urban nomad in city biome.
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid antelope pushing a shopping cart full of tech junk.

include::ROOT:partial$articulate.adoc[]

Nomads are survivalists.
They are experts at finding their way, constructing a shelter, and doing well with nothing more than their bare hands.
Other vocations cannot grasp the subtleties necessary to adapt to and live off an environment.
It is doubtful that there are accredited schools of nomadic adventure.
The persona most likely was born with these inherent survival abilities.
A nomad's survival abilities may have appeared out of necessity due to some scarcity situation.
Nomads can aid the expedition by providing a source of intuitive survival knowledge.

NOTE: Nomads can be sociable and have no political baggage.

Nomads will generally shun technology if it is unnecessary for survival.
They may prefer to sleep in a hollow log or a dumpster rather than a hotel room or tent.
There is no penalty for a nomad who uses technology.

If the campaign has vocation attribute selection, nomads require a combined Awareness and Constitution greater than, or equal to,  18. 

== Knowledge
Nomadic knowledge is focused on biomes, survival, and domestication. 
The interests are broad areas that the nomad excels in.
An interest can be applied to many different tasks.
An expertise is more focused, and offers greater benefit to appropriate task rolls. 

== Interests
Interests are broad areas of knowledge that assist the nomad in the performance of tasks. 
Nomad interests are wide ranging and can be applied to most any nomad task.
At startup, the persona gets one interest per 3 points of Intelligence, and one additional interest per new experience level. 

include::vocations:partial$nomad_interests.adoc[]

=== Biome
Biomes are the bread and butter of a nomad. 
A biome is a geographically, ecologically, or socially unique location.
The biome interest will assist any endeavour that involves a biome. 
This is astoundingly broad, and it is rare that a nomad task does not involve a biome. 
A nomad with a nomad interest automatically gets a biome expertise. 

:art: biome_modern_space.png
:width: 450px
:snark: Biomes are not just trees and dirt.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Landscape of futuristic wall in front of planet and stars.
include::ROOT:partial$articulate.adoc[]

=== Survival
All nomads, and all personas for that matter, are interested in surviving.
A survival interest will assist the player in any survival related task roll.
For example, a safe passage task roll would benefit from the survival interest. 
Whereas trying to domesticate an alien pack mammal would not.

=== Domesticate
Nomads can have an interest in the domestication of aliens. 
Domesticate helps the nomad when working with aliens from the diversidae family.
While an anthro may be __alien__, this expertise only applies to diversidae family.  
The domestication interest assists the persona in tasks that are part of domesticating aliens.

== Expertise
Expertise represents areas of knowledge narrower than an interest. 
While an interest is broad and easily applied, an expertise is more focused and less likely to be applicable to a task.
However, when an expertise is applicable, it benefits the persona much more on their task roll. 

At startup, the persona gets one area of expertise per interest. 
So a nomad with Domesticate 2 and Survival 1 would get two rolls on the Domesticate expertise table and one roll on the Survival expertise table.
After startup, the persona gets one new expertise per experience level. 

:art: nomad.png
:width: 250px
:snark: Nomads desert biome.
:artist: Louis Glanzman
:date: 1952
:license: CC BY-SA 4.0
:description: Two humans sheltering from sun in an alien desert.
include::ROOT:partial$articulate.adoc[]

=== Biome
A biome is a geographically, ecologically, or socially unique location.
The nomad is assisted for any task attempted in a biome expertise.
Biome expertise is cumulative and assists literally any task roll.

include::vocations:partial$nomad_expert_biomes.adoc[]

=== Survival
Survival expertise is knowledge that assists the nomad in performing survival tasks. 
This expertise area includes things like finding water or calming a feral alien. 
Remember to include biome expertise with survival task rolls.

include::vocations:partial$nomad_expert_survival.adoc[]

=== Domesticate
Domesticate expertise helps the nomad when working with aliens from the diversidae family.
While an anthro may be __alien__ this expertise only applies to diversidae aliens.  
The aliens that domesticate tasks work on are typically flora and fauna. 
Remember to include biome expertise with domestication task rolls.

include::vocations:partial$nomad_expert_domestication.adoc[]

== Gifts
The nomad's gifts are tasks where the persona automatically succeeds.
New adaptations are added when the persona gains more experience levels.

include::vocations:partial$nomad_gifts.adoc[]

== Experience
Nomads get half experience for combat and full EXPS for successful task rolls.
Faithful role-playing of the nomad vocation will earn even more EXPS for the persona.
Increasing levels allows the nomad a greater chance of survival in the wild or combat.

include::vocations:partial$nomad_exps.adoc[]

== Tasks
Nomad tasks are about surviving and manipulating the environment.
A nomad has no essential equipment.
Unlike any other vocation a nomad may be __inhibited__ by survival tools like tents, or fire starters.
The referee may increase task difficulty if the nomad is glamping (glamorous camping).

For the intricate details of how to resolve tasks in EXP, jump to xref:uncombat:task_rolls.adoc[Task Rolls].

=== Compendium
A non-exhaustive list of nomad tasks arranged by increasing difficulty.

include::vocations:partial$nomad_compendium.adoc[]

=== List

include::vocations:partial$nomad_tasks.adoc[]
