= Spie

[quote]
____
*Deceiver and breaker of things.*
____

:art: spie.png
:width: 250px
:snark: Safe working environment.
:artist: Michael Jackson
:date: 1992
:license: CC BY-SA 4.0
:description: Humanoid warthog picking the lock on a wall safe. 
include::ROOT:partial$articulate.adoc[]

The spie is a tough, mean, and ruthless vocation.
Spies are highly skilled in unarmed combat, deception, and assassination.
Spies can employ any combination of these abilities to satisfy their goals.
A spie is not a psychopath by nature. 
There is no moral code for spies, and they can be on the side of good, evil or both.
It is hard to distinguish the bad from the not-so-bad in the realm of violent espionage.

Spies are an excellent source of dangerous assignments (from governments, corporations, societies or private citizens).
Spies are not dependent on a commission and may carry out a little extortion or kidnapping for their own profit (or fun).
Spies are often members of secret guilds or naughty lodges dedicated to the clandestine arts.
How deeply involved the expedition gets with a spie's source depends on the ref's milieu or scenario set up.

For campaigns using vocation attribute requirements:
AWE, CHA, CON, DEX, INT, MND and STR total above 92 and HPM above 30.

== Martial Arts
Spies have their style of fancy hand-to-hand combat.
The martial art includes kicks, punches, bites, chops, head butts, and body slams.
The martial arts ability is for unarmoured hand-to-hand combat only.
Martial arts attacks do not use weapons and are only effective on targets in an adjacent hex.

include::vocations:partial$spie_martial_arts.adoc[]

Attack Bonus::
The player uses the Skilled Strike attack on the attack roll.
Martial arts does not get to use the force bonus on damage. 

Attack Order::
The attack order is the secret sauce of spie martial arts.
The attack order allows experienced spies to get an attack roll in before and during their opponent's attacks.
The attack order supersedes initiative.

.*Martial Arts Attack Order*
* Before - attack roll before opponent attack regardless of initiative
* During - attack roll during opponent attack regardless of initiative
* Normal - normal initiative and attack roll timing.

If two spies are using martial arts tied attacks (like both have before attacks) use initiative between the spies. 

Attack Damage::
An attack roll win delivers the damage listed.
The player does not use force bonus when using martial arts. 

Defence Bonus::
A spie's Defence Rating (DEF) increases through dodges, parries, blocks, and rolls.
This martial arts DEF is for an *unarmoured* dress like a tuxedo or bathing suit.
This Defence Rating bonus does not improve the AR of worn armour.


== Knowledge
Spie knowledge is broken down into interests and expertise. 
Interests are broad areas of interest.
For example, an interest in infiltration would help the player making and infiltration related task rolls.
The interest of incapacitation will assist whenever the spie is trying to incapacitate a target.
Expertise represents deeper and more narrow area of knowledge. 

=== Interests
Interests are broad areas of knowledge that the spie has aptitude in.
The interests are infiltration, deception and destruction.
Any task that the persona pursues that involves sneaking would benefit from the infiltration interest.
The destruction interest supports any task that involve weapons or an  unwilling increase in entropy.

A startup the player makes 1 roll on the interests table per 3 points of INT. 
After startup the persona gets to roll, or choose, one new interest per EXPS level. 

include::vocations:partial$spie_interests.adoc[]

=== Expertise
Spie expertise are more narrow areas of knowledge that assist the persona even more when making a task roll. 

Personas get one expertise per interest at startup. 
After startup personas may choose, or roll, for another expertise each EXPS level. 

==== Infiltration Expertise
Expertise at getting into where one should not be. 
This expertise does not involve face to face deception, but deception of architecture and security systems.
The player makes one roll per infiltration interest. 

include::vocations:partial$spie_skills_infiltration.adoc[]

==== Deception Expertise
This area of expertise is for face to face trickery and shenanigans and manipulations. 

include::vocations:partial$spie_skills_deception.adoc[]

==== Destruction Expertise
Expertise in combat and mayhem.
The spie can gather expertise with weapons or field skills.

include::vocations:partial$spie_skills_destruction.adoc[]

== Skills
Spie tasks are about deception, treachery and sneaky violence.

Spies have essential equipment.
A spie must have some element of deception in their persona equipment.
Deceptive equipment includes a pair of dark sunglasses, a fake ID or a trench coat.
The referee may make a target roll more difficult if the spie no tools of deception.

For the intricate details of how to resolve tasks in EXP xref:uncombat:task_rolls.adoc[jump here].

=== Compendium
A non-exhaustive list of biologist skills arranged by increasing difficulty.

Skill Example (42)::
One line description of skill. Difficulty is in brackets. 

==== Trivial
No Guilt (12)::
    Expunge guilty feelings. 

Escape! (12)::
    Out of frying pan into fire. 

==== Easy
Case, Low Tech (24)::
    Find security weakness. Less than tech level 10.

Disguise, Planned (24 + AWE)::
    Careful planned hiding of appearance from strangers.

Bypass, Low Tech (24)::
    Get past security measures. Less than tech level 10. 

Sneak, In Crowd (24)::
    Move self around without being noticed in a crowd.

Encrypt (24)::
    Make data hard to read for others. 

Decrypt, Low Tech (24)::
    Read encrypted data in low tech (<10).

Forgery, Low Tech (24)::
    Create fake document in tech level <9.

==== Normal
Bribery (42)::
    Jump order with value. Mutual benefit.

Blackmail (42)::
    Extract value with information. Coercive.

Decrypt, Normal (42)::
    Read encrypted data in normal tech enviro (10).

Case, Mundane (42)::
    Find security weakness. Tech level 10-14

Disguise, Fast (42 + AWE)::
    Temporary improvised hiding of appearance from strangers.

Lying (42 + MND)::
    Falsification without tells. 

Bypass, Mundane (42):: 
    Get past security measures. Tech level 10-14.

Stun, surprise (42 + CON)::
    Total surprise. Successful attack roll. 

Climb (42)::
    Find a way to climb something not obviously climbable.

Sneak, Standard (42)::
    Move self around without being noticed.

Trap (42)::
    Set trap to activate alarm or attack. 

Forgery, Normal (42)::
    Create fake document in tech level 10.

Pilfer (43 + AWE)::
    Sleight of hand conceal hand sized thing.

Interrogation (42 + MND)::
    Get info from anthro using pressure. 

==== Hard
Case, Secure (84)::
    Find security weakness in secure facility.

Disguise, Known (84 + AWE)::
    Hiding appearance from folks that know the persona. 

Bypass, Secure (84)::
    Get past security measures. Tech level 15-19.

Sneak, Security(84)::
    Move self around without being noticed in secure situation.

Incapacitate (84 + AWE + LEVEL)::
    Requires total surprise. Successful attack roll. Ranged attack. 

Stun, Combat (84 + CON + LEVEL)::
    Successful attack roll.

Decrypt, Secure (84)::
    Read encrypted data in secure or higher tech (11-19).

Forgery, High Tech (84)::
    Create fake document in tech level 11-19.

==== Tough
Case, Higher Tech (126)::
    Find security weakness. Tech level 15-19.

Disguise, Close (126 + AWE)::
    Hiding appearance from friends. 

Bypass, Higher Tech (126)::
    Find security weakness. Tech level 15-19.

Assassinate (126 + AWE + LEVEL)::
    Requires total surprise. Successful attack roll. Ranged attack. 

Sneak, Combat (126)::
    Move self around without being noticed in during combat.

Decrypt, High Tech (126)::
    Read encrypted data tech level 20 and up.

Forgery, Secure (126)::
    Create fake document in tech level >20.

==== Impossible
Case, High Tech (168)::
    Find security weakness. Tech level 20 and up.

Bypass, High Tech (168)::
    Find security weakness. Tech level 20 and up.

Disguise, Family (168 + AWE)::
    Hiding appearance from family, expedition members.

Decrypt, Secret (168 + INT)::
    Read encrypted data tech professionally encrypted.

==== Bizarre
Disguise, Self (210)::
    Hiding appearance from self.

==== Glossary

Picking Locks::
    Use Bypass security.

Picking Pockets::
    Use Pilfer.

Trap Removal::
    Use Bypass Security.

Sleight of Hand::
    Use Pilfer.


:art: mysterious_exit.png
:width: 250px
:snark: Out of the frying pan...
:artist: Leon Bennet
:date: 1879
:license: CC BY-SA 4.0
:description: Human escaping out of, or into, a room via a chandelier.
include::ROOT:partial$articulate.adoc[]

=== Tricks
Spie tricks (gifts) are skills that the player does not need to make a task roll for. 
The persona gets one knack at first level and more difficult ones are added at prescribed levels. 

include::vocations:partial$spie_tricks.adoc[]


== Experience
The benefits of increasing experience levels are more tricks, improved task results, and improved combat skills. Spies earn experience points for completing tasks and roleplaying within their vocation. Only 75% of combat experience can go towards a spie's experience point total.

include::vocations:partial$spie_exps.adoc[]

