= Spie

[quote]
____
*Deceiver and breaker of things.*
____

:art: spie.png
:width: 250px
:snark: Safe working environment.
:artist: Michael Jackson
:date: 1992
:license: CC BY-SA 4.0
:description: Humanoid warthog picking the lock on a wall safe. 
include::ROOT:partial$articulate.adoc[]

The spie is a tough, mean, and ruthless vocation.
Spies are highly skilled in unarmed combat, deception, and assassination.
Spies can employ any combination of these abilities to satisfy their goals.
A spie is not a psychopath by nature. 
There is no moral code for spies, and they can be on the side of good, evil or both.
It is hard to distinguish the bad from the not-so-bad in the realm of violent espionage.

Spies are an excellent source of dangerous assignments (from governments, corporations, societies or private citizens).
Spies are not dependent on a commission and may carry out a little extortion or kidnapping for their own profit (or fun).
Spies are often members of secret guilds or naughty lodges dedicated to the clandestine arts.
How deeply involved the expedition gets with a spie's source depends on the ref's milieu or scenario set up.

For campaigns using vocation attribute requirements:
AWE, CHA, CON, DEX, INT, MND and STR total above 92 and HPM above 30.

== Martial Arts
Spies have their style of fancy hand-to-hand combat.
The martial art includes kicks, punches, bites, chops, head butts, and body slams.
The martial arts ability is for unarmoured hand-to-hand combat only.
Martial arts attacks do not use weapons and are only effective on targets in an adjacent hex.

include::vocations:partial$spie_martial_arts.adoc[]

Attack Bonus::
The player uses the Skilled Strike attack on the attack roll.
Martial arts does not get to use the force bonus on damage. 

Attack Order::
The attack order is the secret sauce of spie martial arts.
The attack order allows experienced spies to get an attack roll in before and during their opponent's attacks.
The attack order supersedes initiative.

.*Martial Arts Attack Order*
* Before - attack roll before opponent attack regardless of initiative
* During - attack roll during opponent attack regardless of initiative
* Normal - normal initiative and attack roll timing.

If two spies are using martial arts tied attacks (like both have before attacks) use initiative between the spies. 

Attack Damage::
An attack roll win delivers the damage listed.
The player does not use force bonus when using martial arts. 

Defence Bonus::
A spie's Defence Rating (DEF) increases through dodges, parries, blocks, and rolls.
This martial arts DEF is for an *unarmoured* dress like a tuxedo or bathing suit.
This Defence Rating bonus does not improve the AR of worn armour.


== Knowledge
Spies have a collection of tricks (gifts), interests and skills. 
Interests are broad areas of interest.
For example, an interest in infiltration would help the player making and infiltration related task rolls.
The interest of incapacitation will assist whenever the spie is trying to incapacitate a target.
Expertise represents deeper and more narrow area of knowledge. 

=== Interests
Interests are broad areas of knowledge that the spie has aptitude in.
The interests are infiltration, deception and destruction.
Any task that the persona pursues that involves sneaking would benefit from the infiltration interest.
The destruction interest supports any task that involve weapons or an  unwilling increase in entropy.

A startup the player makes 1 roll on the interests table per 3 points of INT. 
After startup the persona gets to roll, or choose, one new interest per EXPS level. 

include::vocations:partial$spie_interests.adoc[]

=== Expertise
Spie expertise are more narrow areas of knowledge that assist the persona even more when making a task roll. 

Personas get one expertise per interest at startup. 
After startup personas may choose, or roll, for another expertise each EXPS level. 

==== Infiltration Expertise
Expertise at getting into where one should not be. 
This expertise does not involve face to face deception, but deception of architecture and security systems.
The player makes one roll per infiltration interest. 

include::vocations:partial$spie_skills_infiltration.adoc[]

==== Deception Expertise
This area of expertise is for face to face trickery and shenanigans and manipulations. 

include::vocations:partial$spie_skills_deception.adoc[]

==== Destruction Expertise
Expertise in combat and mayhem.
The spie can gather expertise with weapons or field skills.

include::vocations:partial$spie_skills_destruction.adoc[]

== Skills
Spie tasks are about deception, treachery and sneaky violence.

Spies have essential equipment.
A spie must have some element of deception in their persona equipment.
Deceptive equipment includes a pair of dark sunglasses, a fake ID or a trench coat.
The referee may make a target roll more difficult if the spie no tools of deception.

For the intricate details of how to resolve tasks in EXP xref:uncombat:task_rolls.adoc[jump here].

=== Compendium
A none exhaustive list of biologist skills arranged by increasing difficulty.

Skill Example (42)::
One line description of skill. Difficulty is in brackets. 

==== Trivial

==== Easy


==== Normal



==== Hard


==== Tough


==== Bizarre


Assassination::
Assassination allows the spie to instantly and irrevocably kill a target with a single attack.
Under certain conditions, with the correct weaponry, a spie may carry out an assassination.
There are lots of required conditions for an assassination.
Assassination requires knowledge of the target's anatomy.
Whether a spie can assassinate robots and aliens is up to the referee. 

.*Assassination Checklist*
. Win an ambush
. Win an attack roll
. Win a task results roll
. Using an appropriate weapon

If the player fulfills these four requirements, the target is irrevocably dead.
Medical science cannot medically repair the victim.

The spie must have complete surprise through a successful ambush.
For more information about surprise jump to xref:combat:ambush.adoc[Ambush,window=_blank].
An assassination cannot happen during combat or when the target is in a hyper-aware state.

There will be attack roll bonuses with a successful ambush. 
The player must win an attack roll before making the assassination task results roll.

The spie must be using a controllable weapon like a sword, pistol or rifle. 
Area of effect weapons, flame throwers and fusion weapons lack the precise control assassinate at target.
It is not about the damage the weapon delivers but its stealth.
If the task results roll is successful, the player does not even roll damage, and the target is dead.

The degree of difficulty for the task results roll is equal to the target's Awareness attribute score.
The referee can alter the DD as she sees fit.
Plot points and player personas are highly resistant to the assassination ability.

If the player fails the task results roll, the weapon still inflicts damage on the target.
If the damage kills the target, it is not considered an assassination by the spie.
A target that dies during a failed assassination attempt could still be resuscitated.

Only a failed task results roll will reveal the spie's position in a long-range attack.

.*Incapacitate vs Assassinate*
There is a variation on this ability where the spie incapacitates the target by wounding.
There is no difference in the DD of the maneuver, but the player must roll damage.
If the damage does not accidentally kill the target, then the spie has successfully incapacitated the target.

Disguise::
Spies are naturally adept at not appearing as themselves.
A spie can alter the appearance of her hite and wate with no effort at all.
A spie can make herself appear 50% taller or 25% shorter.
A spie can make herself appear 50% heavier or 25% skinnier.
These changes in hite and wate do not require a task results roll.

More elaborate the disguise, the more difficult the task results roll.
The ability to detect a disguise depends on the Awareness attribute of the observer.
Anthros cannot disguise themselves as aliens or robots. 
Vice versa applies. 

.*Impersonation DD*
* Stranger 1-6 (1d6) DD
* Coworker 1-12 (1d12) DD
* Friend 2-25 (1d12 + 1/2AWE) DD
* Family member 2-37 (1d12 + AWE) DD
* Intimate partner 3-62 (1d12 + 2*AWE) DD

The player may be required to make this task results roll multiple times. 
A failed task results roll for disguise reveals the disguise but not the spie.

Bonuses are available to the player.
Surgical interventions, planning, research can improve the chances of success.
If the spie is disguising her voice, the referee should reduce the degree of difficulty.

Stun::
Stun is a specialized martial arts attack used by tv and movie spies across the universe.
Stun represents the single knock-out hand chop.
The stun works best as a surprise attack but can also be useful in combat. 
The spie can only attempt to stun a target once per combat unit.
The player must win an attack roll and a task results roll to stun an opponent successfully.
The difficulty is equal to the MND of the target.
A successful task results roll drops the target unconscious and uninjured to the ground.
An unsuccessful roll inflicts no damage and leads to embarrassment and humour.



:art: mysterious_exit.png
:width: 250px
:snark: Out of the frying pan...
:artist: Leon Bennet
:date: 1879
:license: CC BY-SA 4.0
:description: Human escaping out of, or into, a room via a chandelier.
include::ROOT:partial$articulate.adoc[]

Assassination::
Each assassination skill level reduces her assassination task results roll by 3DD.

Bribery::
Bribery allows the spie to convince personas to act out of context for remuneration.
Some upstanding citizens may refuse any attempt at bribery.
While others look at the additional remuneration as a business transaction
The persona can use her bribery skill to slip across a border, get into a concert, or avoid a traffic ticket.
Personas cannot bribe people into damaging themselves.
Bribery has a DD range of 1-12 (1d12).
The greater the risk for the bribee, the higher the degree of difficultly.

Blackmail::
Blackmail is a variation on bribery where the target is a victim and does not benefit in the transaction.
Blackmail has a DD range of 1-12 (1d12).

Casing::
The spie uses casing to assess the risks of trying to penetrate a structure.
Successful casing determines otherwise hidden alarms and security systems. 
Casing has a minimum DD range of 1-12 (1d12).
The referee may modify this DD as she sees fit.

Climbing::
Climbing tricks allow the spie to channel her inner monkey.
Spie climbing is a combination of freestyle and parkour.
Climbing has a minimum DD range of 1-8 (1d8).
The referee may modify this DD as she sees fit.

Concealment::
Concealment is the art of hiding objects on the body of the spie.
The spie can hide weapons or money in her fat folds, armpits, fur, or orifices.
The difficulty is adjusted depending on the intensity of the search.
Concealment has a minimum DD range of 5-12 (1d8+4).
The referee may modify this DD as she sees fit.
A successful task results roll allows the spie to sneak information or reveal information.

Cryptography::
The spie can use this trick to encode or decode data.
The encrypted material can take on any form the spie sees fit.
The ref should adjust the difficulty to reflect the complexity of the code.
Cryptography has a minimum DD range of 9-16 (1d8+8).
The referee may modify this DD as she sees fit.
A successful task results roll allows the spie to sneak stuff past a search.

Escape::
A spie can use her escape trick to avoid an otherwise inevitable event.
A successful escape only delays impending doom.
The spie can only use an escape roll to escape the impending doom.
The spie can jump out of the way of a giant speeding robot, but she may jump off a bridge to do so. 
_out of the frying pan and usually into the fire_.
Cryptography has a minimum DD range of 9-16 (1d8+8).
The referee may modify this DD as she sees fit.
Escape cannot avoid plot or story points, but it may delay them for dramatic effect.

Forgery::
Forgery is the spie's art form.
Forgery ranges from falsifying legal documents to counterfeiting currency.
Forgery is time-consuming.
Forgery has a minimum DD range of 5-12 (1d8+4).
The referee may modify this DD as she sees fit.
A successful task results roll creates a passable document.

Interrogation::
Interrogation is the formal or informal push for information from an unwilling persona.
The spie can get information from a target by cajoling, deceiving, threatening, or hurting.
The degree of difficulty is equal to the target's Mind score.
An interrogation on a persona with a 10 MND would be a 10 DD maneuver.

Lying::
A successful task results roll allows the persona to deceive lie detectors, immigration officers, legal cross-examination, or scrutiny.
The lying trick should not replace an opportunity for role-playing.
The degree of difficulty is equal to the target's Mind score.
Lying to a persona with a 10 MND would be a 10 DD maneuver.

Picking Locks::
Bypass things that keep things protected.
The locks include doors, boxes, safes, ignitions etc.
Lock picking is non-destructive.
Smashing a lock or shooting it with the Hollywood Unlocking Blaster is not lock picking.
The nature of the lock decides the degree of difficulty.
Tool locks are mechanical, and tech locks are electronic, comp locks may use facial recognition, and AI locks are the hardest to pick.

Picking Pockets::
Picking pockets is any sleight of hand resulting in the transfer of wealth or property to the spie.
The spie removes items from the pocket, flap, purse, or pouch of a primary observer.
The degree of difficulty depends on the Awareness of the target. 
The action rarely will deceive electronic surveillance equipment such as hidden cameras or alarm systems.
The degree of difficulty is equal to the target's Awareness score.
Picking the pocket of a persona with a 10 AWE is be a 10 DD maneuver.

Stealth Movement::
Stealth is like spie camouflage.
Stealth includes the ability to hide in the shadows, move silently, and avoid detection.
The degree of difficulty is equal to the observer's Awareness score.
Sneaking past a persona with a 10 AWE is be a 10 DD maneuver.
The player must win a task results roll for every observer.


=== Tricks
The spie tricks (gifts) are those abilities that help define the persona as a spie. 
No other vocation has access to these abilities.
Spie tricks are baked in and not trained. 
The spie gets tricks at 1st, 4th and 7th level.

include::vocations:partial$spie_tricks.adoc[]


== Experience
The benefits of increasing experience levels are more tricks, improved task results, and improved combat skills. Spies earn experience points for completing tasks and role-playing within their vocation. Only 75% of combat experience can go towards a spie's experience point total.

include::vocations:partial$spie_exps.adoc[]

