= Veterinarian

[quote]
____
*Repairs and improves organic things.*
____


:art: veterinarian.png
:width: 250px
:snark: Vet resuscitating an insect.
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Humanoid crocodile professor doing surgery on a dragonfly. 
include::ROOT:partial$articulate.adoc[]

Veterinarians are the healers of the organic world.
Vets are a combination of doctor, homeopath, surgeon, paramedic, and faith-healer.
They can utilize whatever odds and ends are available to assist organic personas in need.
Vets are self-trained and have *not* suffered at a college or school.
They learned from oral histories, experimentation, pamphlets or bits of AV material. 
Their work may be temporary or permanent, incompetent or miraculous.

If your table is using attribute determined vocations a Veterinarian must have a combined CHA and INT equal to or higher than 18. 

== Conduct
Veterinarians need the trust of their patients to function.
The therapeutic relationship depends on charisma, trust and expertise.
This vocation does not have an oath by any means, but proper conduct makes them better Veterinarians.

.*Good Person Good Veterinarian*
* Avoid using weapons that kill or damage life.
* Avoid using violence as a solution except as a last resort.
* Make the best choices for their patients.

The more the Vet strays from these suggested tenets, the harder it will be to heal personas.
It is also possible that a guild or club may take issue with a violent Vet.
The persona need not be a pacifist or sacrifice their lives senselessly.

== Knowledge
The Veterinarian's knowledge is focused on fixing broken organic things. 
They can work on anthros and aliens alike.
Veterinarians should be familiar with a diversidae alien before repairing one.
However, the Veterinarian would still be the best at knowing what to do with a de novo alien.

=== Interests
The interests of a Veterinarian indicate broad areas of knowledge.
Veterinarian interests are divided into diagnosis, treatment, and research. 
An interest in diagnosis will help with any task roll that involves figuring out what is wrong with a persona.
Treatment interest helps the player win task rolls that alter (hopefully for the better) the wellness of a persona.
An interest in research assists the persona when enhancing or inventing procedures and devices related to healing.

At startup, the player gets 1 roll on the interest table per 3 points of Intelligence.
A Veterinarian with a 12 INT would get 4 rolls on the Veterinarian Interest Table.
After startup, the persona earns another interest with each new experience level.

include::vocations:partial$veterinarian_interests.adoc[]

==== Diagnosis
The diagnostic interest is a broad approach to figuring out what is wrong.
This interest can be applied to any task that involves figuring out what is broken.

==== Treatment
The treatment interest assists the persona when any treatment task is being attempted.

==== Research
Research is anything outside the realm of treatment and diagnosis.
Research interests could be applied to tasks such as enhancements, cybernetics, pharma, or new previously unknown processes.

=== Expertise
The Veterinarian's expertise reflects narrow areas of focus with deeper comprehension. 
The player makes one roll on the expertise table per interest.
So if the persona has 2 interests in treatment she would get 2 rolls on the Treatment Expertise Table.
The persona acquires a new expertise at each new experience level.

==== Diagnostic
Diagnostic expertise is more narrow and assists with task rolls that fit into the expertise. 
An expertise in aging would assist any task roll that involves aging.

include::vocations:partial$veterinarian_expert_diagnostics.adoc[]

==== Treatment
Treatment expertise represent knowledge that helps repair or stabilize an ailing persona. 
A trauma expertise would help when treating any injuries.

include::vocations:partial$veterinarian_expert_treatment.adoc[]

==== Research
Research expertise represents a collection of narrow foci outside of the realm of treatment and diagnosis.
Research expertise can assist with enhancements, cybernetics, new pharma, or new previously unknown processes.

include::vocations:partial$veterinarian_expert_research.adoc[]

=== Gifts
Gifts are the inherent talents that define the persona as a Veterinarian.
The player does not have to win a task roll to succeed with a gift.

include::vocations:partial$veterinarian_gifts.adoc[]

== Tasks
Tasks are things that the persona does. 
The player uses her persona's knowledge to improve the chance of completing a task.
The persona can have special tasks called gifts that the persona automatically succeeds at. 
Veterinarian gifts are called approaches. 

Veterinarian tasks involve healing anything organic.
Vet tasks are a mix of getting answers and physical procedures.
The minimal equipment required by a Veterinarian is her smile and little black bag. 
The referee may make a target roll more difficult if the Veterinarian does not have these elements.

For the intricate details of how to resolve tasks in EXP, jump to xref:uncombat:task_rolls.adoc[Task Rolls].

=== Compendium
A non-exhaustive list of Veterinarian tasks arranged by increasing difficulty.

include::vocations:partial$veterinarian_compendium.adoc[]

=== List
An alpha ordered list of tasks from above.

include::vocations:partial$veterinarian_tasks.adoc[]

== Experience
The benefits of increasing experience levels are more tasks, improved task roll bonus, and additional approaches.
Veterinarians earn experience points for completing tasks and role-playing within their vocation.
Only 10% of combat experience can go towards a Vet's experience point total.

include::vocations:partial$veterinarian_exps.adoc[]