= Veterinarian

[quote]
____
*Repairs and improves organic things.*
____


:art: veterinarian.png
:width: 250px
:snark: Vet resuscitating an insect.
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Humanoid crocodile professor doing surgery on a dragonfly. 
include::ROOT:partial$articulate.adoc[]

Veterinarians are the healers of the organic world.
Vets are a combination of doctor, homeopath, surgeon, paramedic, and faith-healer.
They can utilize whatever odds and ends are available to assist organic personas in need.
Vets are self-trained and have *not* suffered at a college or school.
They learned from oral histories, experimentation, pamphlets or bits of AV material. 
Their work may be temporary or permanent, incompetent or miraculous.

If your table is using attribute determined vocations a veterinarian must have a combined CHA and INT equal to or higher than 18. 

== Conduct
Veterinarians need the trust of their patients to function.
The therapeutic relationship depends on Charisma, trust and expertise.
This vocation does not have an oath by any means, but proper conduct makes them better veterinarians.

.*Good Person Good Veterinarian*
* Avoid using weapons that kill or damage life.
* Avoid using violence as a solution except as a last resort.
* Make the best choices for their patients.

The more the vet strays from these suggested tenets, the harder it will be to heal personas.
It is also possible that a guild or club may take issue with a violent vet.
This conduct is a general goal.
The persona need not be a pacifist or sacrifice their lives senselessly.

== Knowledge
The veterinarian's knowledge is focused on fixing broken organic things. 
They can work on anthros and aliens alike.
Veterinarians should be familiar with a diversidae alien before repairing one.
However, the veterinarian would still be the best at knowing what to do with a de novo alien.

== Interests
The interests of a veterinarian indicate broad areas of knowledge and comprehension.
Veterinarian interests are divided into diagnosis, treatment and research. 
An interest in diagnosis will help with any task roll that involves figuring out what is wrong with a persona.
Treatment interest helps the player win task rolls that alter (hopefully for the better) the wellness of a persona.
An interest in research assists the persona when enhancing or inventing procedures and devices related to healing.

At startup, the player gets 1 roll on the interest table per 3 points of Intelligence.
A veterinarian with a 12 INT would get 4 rolls on the interests table.
After startup, the persona earns another interest with each new experience level.
The player can choose to roll on the Veterinarian Interest Table, or choose a specific interest.

include::vocations:partial$veterinarian_interests.adoc[]

=== Diagnosis
The diagnostic interest is a broad approach to figuring out what is wrong.
This interest can be applied to any task that involves figuring out what is broken.

=== Treatment
The treatment interest assists the persona when any treatment task is being attempted. 

=== Research
Research is anything outside the realm of treatment and diagnosis.
Research interests could be applied to tasks such as enhancements, cybernetics, pharma, or new previously unknown processes.

== Expertise
The veterinarian's expertise reflects narrow areas of focus with deeper comprehension. 
The expertise are quite specific and fall under one of the three interests described above.

The player makes one roll on the task table per interest generated. 
The persona acquires a new task at each new experience level.

=== Diagnostic
Diagnostic expertise is more narrow and assists with task rolls that fit into the expertise. 
An expertise in aging would assist any task roll that involves aging.

include::vocations:partial$veterinarian_expert_diagnostics.adoc[]

=== Treatment
Treatment expertise represent knowledge that helps repair or stabilize an ailing persona. 
A trauma expertise would help when treating any injuries.

include::vocations:partial$veterinarian_expert_treatment.adoc[]

=== Research
Research expertise represents a collection of narrow foci outside of the realm of treatment and diagnosis.
Research expertise can assist with enhancements, cybernetics, new pharma, or new previously unknown processes.

include::vocations:partial$veterinarian_expert_research.adoc[]

== Approaches
Approaches (gifts) are the inherent talents that define the persona as a veterinarian.
The player does not have to roll to succeed with an approach.
An approach happens immediately unless combat time is activated.

include::vocations:partial$veterinarian_approaches.adoc[]

== Organizing
Veterinarian knowledge is more easily managed when organized.

.*Unorganized Knowledge*
* Interest Research
* Expertise Psionic Mutations
* Interest Treatment
* Expertise Trauma
* Interest Diagnosis
* Expertise Psionic Mutations
* Approach Quick Fix

.*Organized Knowledge*
* Interests
** Research - 1
** Diagnosis - 1
** Treatment - 1
* Expertise
** Psionics - 2
** Trauma - 1
* Approaches
** Quick Fix

== Experience
The benefits of increasing experience levels are more tasks, improved task roll bonus, and additional approaches.
Veterinarians earn experience points for completing tasks and role-playing within their vocation.
Only 10% of combat experience can go towards a vet's experience point total.

include::vocations:partial$veterinarian_exps.adoc[]

== Tasks
Tasks are things that the persona does. 
The player uses her persona's knowledge to improve the chance of completing a task.
The persona can have special tasks called gifts that the persona automatically succeed at. 
Veterinarian gifts are called approaches. 

Veterinarian tasks involve healing anything organic.
Vet tasks are a mix of getting answers and physical procedures.
The minimal equipment required by a veterinarian is her smile and black bag. 
The referee may make a target roll more difficult if the veterinarian does not have these elements.

For the intricate details of how to resolve tasks in EXP, jump to xref:uncombat:task_rolls.adoc[Task Rolls].

=== Compendium
A non-exhaustive list of veterinarian tasks arranged by increasing difficulty.

Task Example (42)::
One-line description of task. Difficulty is in brackets. 

==== Trivial
Biological (12)::
    Is it biological? Yes/No. 

Sentience (12)::
    Sentience present. Yes/No. 

Living (18)::
    Is it alive and living? Yes/No.

Autopsy, Fun (12)::
    Disassemble a cadaver.

Stasis Bag (18)::
    Safely stuff into stasis bag. 


==== Easy
Quick Fix (24)::
    Heal 1d6 HPS immediately.

Calm Persona (24)::
    Help a persona relax. 

Admin Pharma (24)::
    No adverse effects. 

Fail Pharma (32)::
    Guarantee adverse effects.

Unstun (32)::
    Immediately remove stun effect from one persona. 

==== Normal
Strong Fix (42)::
    Heal 2d6 HPS over 2 units.

Open Stasis Bag (42)::
    Retrieve patient from stasis bag alive.

Stabilize (42)::
    Stop persona from losing negative HPS.

Cryogenic Wake (56)::
    Safely emerge from cryogenic sleep.

Poison Arrest (56)::
    Stop poison progress. Does not heal.

Heal 50 (50)::
    Restore to 50% HPM. Uncombat only. 

==== Hard
Autopsy, Diagnostic (84)::
    Disassemble to determine cause of death.

Power Fix (84)::
    Heal 3d6 HPS over 3 units. 

Calm Frenzy (84)::
    Arrest an ursidae frenzy.

Resuscitate (84)::
    Restore the persona to zero HPS and unconsciousness.

Poison Reverse (84)::
    Reverse the effects of a poison (except HPS damage).

Radiation Arrest (84)::
    Stop ongoing effects of radiation.

Heal 90 (90)::
    Restore to 90% HPM. Uncombat only. 

Restore Attribute (96)::
    Revive an injured attribute (not from aging).

Psionic Break (96)::
    Interrupt a psionic attack.

Biorganic Attachment (100)::
    Attach a biorganic attachment.


Subliminal Suggestion (108)::
    Interject a thought without detection.

Hearing Restoration (108)::
    Reverse any deafness.


==== Tough
Autopsy, Forensic (126)::
    Disassemble to determine criminal death.

Biorganic Replacement (126)::
    Insert a biorganic replacement.

Poison Cure (126)::
    Reverse all poison effects (even HPS damage).

Radiation Cure (126)::
    Reverse all radiation effects (even HPS damage).

Unstun Group (126)::
    Unstun all within one hex range. 

Paralyzing Pinch (126)::
    Touch target for physical collapse (anthro only).

Mind Inventory (142)::
    Detect mind control. 

Cryogenic Sleep (156)::
    Safely place into cryogenic sleep.

Vision Restoration (156)::
    Restore any blindness. 

==== Impossible
Attribute Boost (168)::
    Temporarily boost an attribute by 1d3 for 1d3 minutes.

Death Pinch (168)::
    Touch target for cardiac arrest (anthro only).

Phenomic Removal (168)::
    Safely remove a phenomic mutation.

Reattach Members (196)::
    Reverse the handiwork of Knites.

==== Bizarre
Attribute Enhance (210)::
    Permanently increase an attribute by 1 (not MIND).

Psionic Removal (210)::
    Unsafely remove a psionic mutation. 

Pharma Creation (242)::
    I wanna new drug. 

Aging Stagnation (242)::
    Arrest an aging effect. One at a time.

=== List
An alpha ordered list of tasks from above.

include::vocations:partial$veterinarian_tasks.adoc[]

