= Pre-Rolls

WARNING: friends of exp. this is a place holder for stuff that was destroy on moving from version 4 to 5. 

The electronic pre-rolls were lost in a WP failure between V5 and V6.
There is a reference document in PDF form at xref:ROOT:attachment$expgame.pdf[EXP 4.01 1993 (32M)].
Remember this is V4 from 1993.
If you need pre-rolls check out the 


A cheesy scenario starts on game page 755 aka PDF page 769.

.Proposed Pre-Rolls
. Referee Personas
.. Anthros
... Cannon Fodder
... Canon Fodder
... Canonical
.. Aliens
... Cannon Fodder
... Canon Fodder
... Canonical
.. Robots
... Cannon Fodder
... Canon Fodder
... Canonical
.. AIs
... Canonical
. Toys
. Scenarios

== Referee Personas
There are many pre-rolled personas in the reference document @ page 713 / PDF page 727.
Remember this is V4 from 1993. 

Many images from the main doc will be used as pre_rolls cutting image use and making doc more real. 
xref:pre_rolls:anthro_night_shadii.adoc[Example Pre Roll].

== TOYs
There are many pre-rolled TOYs in the reference document @ page 689 / PDF page 703.
Remember this is V4 from 1993. 

== Scenarios
There is a cheezy pre-rolled scenario in the reference document @ page 755 aka PDF page 769.
Remember this is V4 from 1993. 

.Impending Scenarios (2025 and later)
* Tsolodvor 
* GHOTI
* Kinder Kilner Haus for Wayward Mutants
* Adventures of Turnip
* Algo 







