= Pre-Rolls

The electronic pre-rolls were lost to data transfer, but still exist on a downloadable PDF https://exp.sciencyfiction.com/_attachments/expgame.pdf[EXP 4.01 1993 (32M)].
There are many pre-rolled personas starting at game page 713 aka PDF page 727. 
There are many pre-rolled TOYs starting at game page 689 aka PDF page 703.
A cheesy scenario starts on game page 755 aka PDF page 769.

There is a collection of python programs at https://github.com/mobilehugh/EXP_Game_Tools[EXP Game Tools] that help decrease the crunchiness of persona creation in EXP. The tool set is pre-alpha, but can make PDFs of referee personas quite easily. The tool will also keep track of experience points and player persona info as well. You will need to install python and FPDF2 for the packages to work. There is an limited readme at the github page.

.Pre-Rolls
. Referee Personas
.. Anthros
.. Aliens
.. Robots
.. AIs
. Toys
. Scenarios




Scenarios

The electronic version of the scenario did not survive data transfer.
The example scenario does exist on a downloadable PDF https://exp.sciencyfiction.com/_attachments/expgame.pdf[EXP 4.01 1993 (32M)].
The scenario is found on game page 755 aka PDF page 769.
You will also need to know the pre-rolled personas on game page 713 aka PDF page 727, and some pre-rolled TOYs on game page 689 aka PDF page 703.

This appendix is for the stuff one will need to create runs, scenarios, mythos and campaigns.
EXP supplies a generic mythos as a guideline for creating one's own mythos in which to role play.

Eventually scenarios will contain a collection of examples that use the generic rules and the generic mythos. 
There is an obsessively documented campaign called Tsolodvor that would fit in this section.
Tsolodvor and other campaigns like GHOTI and The Adventures of Turnip may shoe horn into the Algo World Space. 
None of this will happen before 2022. 



 Pre-Rolled Anthros

Test page for how to present pre-rolled anthro referee personas.

This will contain a list of anthro personas. 
The first one is being formatted now 

 __xref::pre/RP_night_shadii.adoc[Night Shaadi]
