= Pre-Rolls

WARNING: Friends of exp, this is a place holder.

First goal is to port over all the existing pre-rolls from xref:ROOT:attachment$exp_game_v401.pdf[1993 PDF]..
Second goal is to add cannon and canon level referee personas.
Third goal is to add a bunch more pre-rolls. 

xref:pre_rolls:anthro_.adoc[Anthro Pre Rolls]


.Pre-Roll Records
. Anthros
.. Cannon
.. Canon
.. Canonical
. Aliens
.. Cannon
.. Canon
.. Canonical
. Robots
.. Cannon
.. Canon
.. Canonical
. AIs
.. Canonical
. Toys
.. Departments
.. Vehicles
.. Spacecraft

== Organization
The pre-rolls will be accesses by a series of rendered pages. 
The introduction page will be organized by the top layer

.introduction page
. Persona Raw Roll Table
. Anthros
. Aliens
. Robots
. AIs
. TOYs

.Anthro
. Anthro Raw Roll Table
. Genus Roll Table
. Vocation Roll Table
. Combat Ratio Roll Table
. Story
.. Cannon
.. Canon
.. Canonical

.Alien
. Alien Raw Roll Table
. Tool Usage Roll Table
. Social Strata Roll Table
. Combat Ratio Roll Table
. Story
.. Cannon
.. Canon
.. Canonical

.Robot
. Robot Raw Roll Table
. Series Roll Table
. Combat Ratio Roll Table
. Story
.. Cannon
.. Canon
.. Canonical

.AI
. AI Roll Table

.Toys
. Toy Raw Roll Table
. Combat Roll Table
. Uncombat Roll Table
. Departments 
.. Aerosols
.. Armaments
.. Armour
.. Artillery
.. Biorepair
.. Bombs
.. Grenades
.. Guns
.. Junque
.. Materiel
.. Mundane
.. Pharma
.. Spacecraft
.. Vehicle
.. Multiquip

== Data
Data storage and organization is still undecided.
Presentation must be through an adoc file.
The page file will only be data for attributes based on a preset adoc file.
And the partials would be what actually generates the page.
No database.

.Pre-roll Data
* adoc of variables
** persona record
** toy record
** spacecraft record
** vehicle record
* image
** optional
** ROOT image
** pre-roll only image
* pdf
** stored as attachment?
** generated on the fly?
* core data (may not reveal core data)
** json
** adoc

=== adoc schema

[source,adoc]
----
// this is an include for live_anthro_record_v7.pdf
// asciidoctor-pdf -a pdf-theme=theme.yml -a include_this="night_shadii_data" live_anthro_record_v7.adoc
// should use the latest json element only

//INFO 
:persona_name: Night Shadii
:player_name: Hugh
:description: A 103 years old generalis florian knite

//ATTRIBUTES
:awe: 8
:cha: 7
:con: 7
:dex: 14
:int: 8
:mnd: 21
:str: 9
:soc: 173
:hpm: 21

// COMBAT
:attack_table: off

:strike_skill: 142
:strike_raw: 42
:strike_max: 666
:strike_force: 5

:fling_skill: 142
:fling_raw: 42
:fling_max: 766
:fling_force: 3

:shoot_skill: 242
:shoot_raw: 42
:shoot_max: 866
:shoot_force: 0

:def: 542
:move_land: 13
:move_air: 0
:move_water: 0

//BIOLOGIC data
:family: Anthro
:genus: Florian
:species: Generalis

:age_cat: Older
:age: 103
:age_suffix: years

:size_cat: Medium
:hite: 171
:hite_suffix: cms
:wate: 52
:wate_suffix: kgs

//Mutations dictionary  "Mutations": {}, 

// TASKS

//GIFTs, presently calculated by level
:gift_1:
:gift_4:
:gift_7:

//INTERESTs in a list ["Think Space", "Physical Space"] needs to be summed
:interest_1: 
:interest_2: 
:interest_3: 

//SKILLs in a list ["Mimic", "Militarization", "Languages"] needs to be calculated
:skill_1:
:skill_2:
:skill_3:
:skill_4:
:skill_5:
:skill_6:
:skill_7:
:skill_8:
:skill_9:

:vocation: knite
:level: 1
:exps: 1500
:exps_goal:

//EQUIPMENT
// calculate Sprint, Carry and Lift 
// Equipment is a list "Equipment": []
:wa: 14
:wa_sprint: 
:wa_carry:
:wa_lift:


// RP FUN is a list
// "RP_Fun": ["Arc: Past: Nearby, Present: Curious and trusting, Goal: Make it to tomorrow.", 
// "Dress: Sports Team, Hygiene: Dishevelled, Odor: Hay", 
// "Personality: Lustful, Introverted", 
// "Labanations: Voice: Flick (Light, Fast, Indirect), Move: Glide (Light, Slow, Direct)", 
// "Beliefs: Religion: None, Philosophy: None, Politics: None."], 

//HISTORY single string stored in a list
:rp_fun_arc_origin:
:rp_fun_arc_present:
:rp_fun_arc_future:

//APPEARANCES
:appearance_dress:
:appearance_hygiene:
:appearance_gender:
:appearance_smell:

//LABANATIONS
:laban_move:
:laban_sound:

//BELIEFS
:belief_religion:
:belief_philosophy:
:belief_politics:


//DATA
:date_created: Wed-20-Dec-2023(15:43)
:date_updated: Wed-20-Dec-2023(15:43)
:jsonl_name: NIGHT_SHADII_anthro_florian_generalis_knite_1703087031.jsonl

=== json schema


----

[source,json]
----
{"Player_Name": "hugh", "Persona_Name": "Night Shadii", "FAMILY": "Anthro", "FAMILY_TYPE": "Florian", "FAMILY_SUB": "Generalis", "Fallthrough": true, "Bespoke": false, "RP": true, "RP_Cues": true, "Bin": false, "AWE": 8, "CHA": 7, "CON": 7, "DEX": 14, "INT": 8, "MND": 21, "STR": 9,

 "SOC": 173, "HPM": 21, "WA": 14, "AR": 542, "Move": 3, 
 
 "Age_Spans": [], "Age_Cat": "Older", "Age": 103, "Age_Suffix": "years", 
 
 "Size_Cat": "Medium", "Hite": 171, "Hite_Suffix": "cms", "Wate": 52, "Wate_Suffix": "kgs", 
 
 "Quick_Description": "A 103 years old generalis florian knite", 
 
 "RP_Fun": ["Arc: Past: Nearby, Present: Curious and trusting, Goal: Make it to tomorrow.", "Dress: Sports Team, Hygiene: Dishevelled, Odor: Hay", "Personality: Lustful, Introverted", "Labanations: Voice: Flick (Light, Fast, Indirect), Move: Glide (Light, Slow, Direct)", "Beliefs: Religion: None, Philosophy: None, Politics: None."], 
 
 "Vocation": "Knite", "Level": 1, "EXPS": 1500, 
 
 "Mutations": {}, 
 
 "Interests": ["Think Space", "Physical Space"], 
 
 "Skills": ["Mimic", "Militarization", "Languages"], 
 
 "Proficiencies": [], "Equipment": [], "Date_Created": "Wed-20-Dec-2023(15:43)", "Date_Updated": "Wed-20-Dec-2023(15:43)", "File_Name": "NIGHT_SHADII_anthro_florian_generalis_knite_1703087031.jsonl"}

----

== Nomenclature
Changing nomenclature requires a change in the generator program, eventually.
Storage name is different from working name. 


time suffix -> %Y_%m%d_%H%M_00%S -> 2024_0415_1430_0045

.nomenclature
. anthro
.. anthro_genus_vocation_time
.. anthro_canine_mercenary_2024_0415_1430_0045
.. working name is persona name

. alien
.. alien_genus_tool_usage_time
.. alien_camilidae_felidae_creator_2024_0415_1430_0045
.. working name is persona name or species name

. robot
.. robot_series_model_time
.. robot_combot_expendable_2024_0415_1430_0045
.. robot_datalyzer_null_2024_0314_1442_0016
.. working name is persona name

. ai
.. ai_distro_branch_time
.. ai_sessile_g3m_2024_0415_1430_0045
.. working name is persona name

. toy
.. toy_department_type_time
.. toy_gun_fusion_pistol_2024_0415_1430_0045
.. working name is description

== Old News
The electronic pre-rolls were lost in a WP failure between V5 and V6.
There is a reference document in PDF form at xref:ROOT:attachment$exp_game_v401.pdf[EXP 4.01 1993 (32M)].
Remember this is V4 from 1993.

=== RPs
There are many pre-rolled personas in the reference document @ page 713 / PDF page 727.
Remember this is V4 from 1993. 

Many images from the main doc will be used as pre_rolls cutting image use and making doc more real. 
xref:pre_rolls:anthro_night_shadii.adoc[Example Pre Roll].

=== Toys
There are many pre-rolled TOYs in the reference document @ page 689 / PDF page 703.
Remember this is V4 from 1993. 

=== Scenarios
There is a cheezy pre-rolled scenario in the reference document @ page 755 aka PDF page 769.
Remember this is V4 from 1993. 

.Impending Scenarios (2026 or later)
* Tsolodvor 
* GHOTI
* Kinder Kilner Haus for Wayward Mutants
* Adventures of Turnip
* Algo 







