= Mutations
In EXP, the term mutation is not merely the biological transformation of DNA.
Mutations represent randomly acquired complicated permanent changes to the persona. 
The mutation storey is deeply rooted in sciency fiction.
In reality, biological mutations are mostly fatal.

In the sciency fiction world of EXP, mutations are just plain fun.
A referee can't explain this process scientifically.
Mutations are part of the game and fall under the 'black box' explanation. 
However, pseudo-scientific justifications add to the milieu of the campaign.

.*Mutation Checklist*
. Mutation Types
. Acquiring Mutations
. Family Types
. Mutation Parameters
. General Considerations

Anthros that have mutations are considered mutants. 
The nature of mutants in a society depends entirely on the milieu of the campaign.
Mutants may be wholly accepted or wholly reviled.
In general mental mutations harbour an element of suspicion or distrust. 

== Mutation Types
Mutations have two broad categories: mental and physical mutations.

* xref:v-wetware:CH58_Mental.adoc[Mental Mutations,window=_blank]
* xref:v-wetware:CH59_Physical.adoc[Physical Mutations,window=_blank]

=== Mental Mutations
The persona's brain is the focus of mental mutations.
The persona manipulates the world through her brain and her Mind attribute.
Mental mutations have other monikers like psionics, psychic powers, tele-this and tele-that, etc.

====
Mental mutations rarely have any external physical reveal on the persona.
====

Mental mutations function through the thinkspace of the xref:vi-appendices:Appy_C_Mythos_Generic.adoc#_the_spaces[Spaces,window=_blank].
These mutations may impact the physical space, but the effect travels through the thinkspace.
The thinkspace is a faux concept where organic consciousnesses exist. 
In this space, consciousnesses interact, allowing for extrasensory perception and mind control.
Mental mutations do not alter the persona's appearance, making these mutants indistinguishable from other personas.

Mental mutations require concentration of the mind, like lifting a weight involves contraction of the muscles.
The attribute that powers mental mutations is xref:i-roll_playing_rules:CH03_AttributesMND.adoc[Mind,window=_blank].

=== Physical Mutations
Physical mutations are what most readers associate with mutations.
These mutations change the persona's body allowing it unusual powers. 
Physical mutations function in the physical space and do not reach into the thinkspace.
There is no hiding physical mutations.
Even physical mutations that create new internal organs alter the mutant's appearance.

== Acquiring Mutations
The susceptibility of personas to mutation is affected partly by <<_persona_families,family>> and partly by choice.
The families have varying frequencies of mutation based on elements of popular fiction and the ability of the species to adapt to mutation.
The players have input as to whether their persona mutates or not.
If the player desires to mutate, she can double her persona's chance of mutation.
This desire can be a source of backstory like the persona went skinny dipping in that glowing creek.

=== Start Up Mutations
These are mutations that the persona acquires while being generated. 
The frequency of start-up mutations depends on the persona family and type.
For anthros, the player can influence the mutation chance by choice. 
Each <<_persona_families,family>> has a different approach to mutations. 

Defects do *not* count as mutations.
If a persona gets three physical mutations and her first mutation is the defect No Resistance to Disease, the player has three more mutation rolls.

=== De Novo Mutations
These are new mutations or mutation effects acquired during gameplay.
New mutations are rare during a campaign.
Pharma that generates mutations is rare.
Exposure to toxins and radiation is more likely to be lethal than mutagenic.
Adding de novo mutations should be a carefully integrated part of the milieu or campaign. 

== Persona Families
The meat, metal and metamorphosis of mutations.
Mutations are generally an anthro thing, but all family types can enjoy mutation effects.
The nature of what a mutation differs between anthros, aliens and robots. 

* anthro mutations are unique *mutations* of that persona and are unreproducible
* aliens mutations are species-wide *abilities* that have evolved over generations
* robots mutations are unique *malfunctions* of that persona and are unreproducible

=== Anthros
Anthro mutations represent changes in persona DNA that create unique physiologic structures in the persona.
Mutations can be innocuous, powerful or deleterious.
Anthro mutations are the stuff of sciency fiction legend from comics to movies.
Personas can start out having full awareness of their mutations.
Or the mutations could be activated by a story trigger.
Some refs have personas acquire their mutations through gameplay, i.e., skinny dipping in that glowing creek.

The anthro type determines their mutation frequencies.
Humanoids are much more likely to mutate than insectoids.
The player can choose to mutate and increase the chance of her persona getting mutations.

.*Mutation Notes*
* player wants to mutate *double the chance*
* player does *NOT* want to mutate *zero the chance*
* Humanoids type can choose 100% chance to mutate
* Purestrains cannot have a mental mutation defect

include::ROOT:partial$CH04_Table_anthro_mutations.adoc[]

=== Robots
A robot mutation is not an alteration in the persona's DNA.
Robots don't have mutations per se, but they can have peripherals with mutation effects.
Robots generate mutations when being fabricated.
The mutation effect can be a bespoke peripheral or a malfunctioning peripheral.
Usually, it is clear whether the mutation effect arises from malfunction or intention.
The referee must decide if a mutation effect exists in other models of the same robot.
Potent mutations are always malfunctions that are unique to the robot.

=== Aliens
Alien mutations are abilities that are part of their alien species.
Evolving an alien generates not just a persona but an entire species.
The persona will have the mutation effect, and it will also be species-wide.
Not every member of the species will have every mutation effect.
For example, if an alien person has the mutation time stop, it is unlikely every alien in the species does.
Alien personas can also acquire mutations de novo during gameplay.

== General Considerations
Mutations are biologically magical and create a whole host of complications, considerations and confusions. 
The referee and players will use their improv skills, making mutations both interesting and fun.
What follows is a disjointed collection of past roleplay decisions around mutations. 

The mutant must be conscious to use a mutation unless stated otherwise by that specific mutation.
Any degree of consciousness is sufficient for the mutant to use her mutation.
Mutations may still be if the persona is paralyzed, stunned, nauseous, falling or worse.

The mutant cannot turn off a mutation with a duration of constant.
The mutation effect will be functioning whether the player wants it or not.

Restraints will only affect physical mutations.
Mental mutation usually cannot be stopped by binding a persona's paws.

The source of a psionic attack may be very difficult to determine.
Very few mental mutations offer any indication that the persona is employing one.

Psionic defence rolls act subconsciously.
The brain instantly defends against intrusion, whether it is malevolent or benevolent.

The referee should delicately balance the power of mutations with subtle inconveniences, but mutations should never be useless.

Powerful mutations have campaign-altering effects.
For instance, a time stop mutation may attract aliens that manipulate time.
A planal holdaway may cause trouble with the special drives.

No terrain barrier can block a mutation travelling from one mind to another.
ESP, gyrokinesis, and telekinesis can pass through any barrier if the mutant has positive proof that the target exists.
Those mutations which manipulate the environment to attack a target, such as mental blast, or launch-able quills, are subject to terrain effects.

The target of a mental mutation is whatever the mutant intends to affect.
The word 'target' is generic for whatever the mutant wants to affect.
The target is most often another persona but could also be an inanimate object.

Mutations improve as the persona increases in experience level.
Range, damage, area of effect, increasing control usually improves with each new EXPS level.
Using level-adjusted attributes is the most common way to implement level improvements, i.e., MND + EXPS Level or CON + EXPS Level.