= Mutations
In EXP the term mutation is not limited to the biological transformation of DNA.
Mutations represent randomly acquired permanent changes to the persona. 
The mutation story is deeply rooted in sciency fiction.
In reality biological mutations are mostly fatal.

In the sciency fiction world of EXP mutations are just plain fun.
It is impossible for a referee to scientifically explain this process.
Mutations are part of the game and fall under the 'black box' explanation. 
However pseudo-scientific justifications add to the milieu of the campaign.

Anthros that have mutations are considered mutants. 
The nature of mutants in a society depends entirely on the milieu of the campaign.
Mutants may be completely accepted, or completely reviled.
In general mental mutations harbour an element of suspicion or distrust. 

== Mutation Types
Mutations are divided into two broad categories: mental and physical mutations

* xref:v-wetware:CH58_Mental.adoc[Mental Mutations,window=_blank]
* xref:v-wetware:CH59_Physical.adoc[Physical Mutations,window=_blank]

=== Mental Mutations
Mental mutations function through the thinkspace of the EXP mythos.
These mutations may impact the physical space, but the effect is delivered through the thinkspace.
The thinkspace is a faux concept where organic consciousnesses exist. 
In this space consciousnesses interact allowing for extrasensory perception, and mind control.
Mental mutations do not alter the persona's appearance, making these mutants indistinguishable from other personas.
These mutations are also called psionics, psychic powers, or mental attacks. 

Mental mutations require concentration of the mind, like lifting a weight requires contraction of the muscles.
The attribute that powers mental mutations is mental strength.

=== Physical Mutations
Physical mutations are what most readers associate with mutations.
These mutations change the persona's body allowing it unusual powers. 
Physical mutations function in the physical space, and do not reach into other spaces.
Even physical mutations that represent internal organ changes are betrayed by appearance.

== Acquiring Mutations
The susceptibility of personas to mutation is affected partly by family and partly by choice.
The families have varying frequencies of mutation that are based both on elements of popular fiction and the ability of the species to adapt to mutation.
The players also have some input as to whether they mutate or not.
If the player desires to mutate, she can double her persona's chance of mutation.
It is assumed that the parents of this persona were exposed to high levels of mutagens.
Or the persona liked to go skinny dipping in that glowing creek.

=== Start Up Mutations
These are mutations that the persona acquires while being generated. 
The frequency of start up mutations depends on the persona family and type.
For anthros the player can influence the mutation chance by choice. 
Each <<_persona_families,family>> has a different approach to mutations. 

Defects do *not* count as mutations.
If a canine has three physical mutations and generates No Resistance to Disease, a defect, the player would still have 3 mutation rolls.

=== De Novo Mutations
These are new mutations or mutation effects acquired during play of the campaign.
New mutations should be very rare of circumstances during the process of a campaign.
Pharma that generates mutations is rare.
Exposure to toxins and radiation is more likely to be lethal than mutagenic.
Adding de novo mutations should be a carefully integrated part of the milieu or campaign. 

== Persona Families
The meat, metal and metamorphosis of mutations.
Mutations are generally an anthro thing, but all family types can enjoy mutation effects.
The nature of what a mutation is differs between anthros, aliens and robots. 

* anthro mutations are unique *mutations* of that persona and are unreproducible
* aliens mutations are species wide *abilities* that have evolved over generations
** an alien could also have a unique mutation in addition to evolved abilities
* robots mutations are unique *malfunctions* of that persona and are unreproducible
** a robot could also have a mutation effect installed at fabrication

=== Anthros
Anthro mutations represent changes in persona DNA that create unique changes in the persona.
Mutations can be innocuous, powerful or deleterious.
Anthro mutations are the stuff of sciency fiction legend from comics to movies.
Personas can be generated having full awareness of their mutations.
Or the mutations could be activated by some story trigger.
Some refs have personas acquire their mutations through game play.
For example, going skinny dipping in the glowing creek.

Anthro mutation frequencies are determined by their anthro type.
Humanoids are much more likely to mutate than insectoids.
The player can also choose to mutate to increase the chance of her persona mutating.

==== Mutation Chance
Every player must check to see if their persona mutates.
Anthro mutation frequencies are determined by their anthro type.
Humanoids are much more likely to mutate than insectoids.
The player first determines the number of mutations and then generates the specific types.

.*Mutation Chance Notes*
* player wants to mutate *double chance*
* player does *NOT* want to mutate *zero chance*
* Humanoids type can choose 100% chance to mutate
* Purestrains cannot have a mental mutation defect
* 1+roll indicates another chance on the table

include::ROOT:partial$CH04_Table_anthro_mutations.adoc[]

=== Robots
A robot mutation is not an alteration in the persona's DNA.
Robots don't have mutations per se, but they can have peripherals with mutation effects.
Robots generate mutations when being fabricated.
The mutation effect can be a bespoke peripheral, or a malfunctioning peripheral.
Usually it is made clear whether mutation effect is by malfunction or intention.
If the robot is fabricated with an intended mutation effect that peripheral may be found in other models of the same robot type.
Extremely powerful mutations are always malfunctions that are unique to the robot.

=== Aliens
Alien mutations are evolved abilities that are part of their alien species.
Evolving an alien generates not just a persona, but an entire species.
The persona will definitely have the mutation effect, but it will be species wide.
This does not mean that every member of the species will have that mutation.
For example, if an alien person has the mutation time stop it is unlikely every alien in the species does.

==== Mental Abilities
The chance of an alien having a mental mutation is equal to the alien's mental strength attribute.
An alien with a 15 MSTR would have a 15% chance of having a mental mutation.
The player stops checking for mental mutations as soon as a roll is failed.
So if the player were to roll 11 and 16, her alien would have one mental mutation.

==== Physical Abilities
The chance of a creature having evolved a physical mutation is equal to the creature's constitution attribute.
For example, a CON of 10 has a 10% chance of having a mutation.
Once the alien has a mutation, there is an equal chance of having another.
The alien can keep getting additional mutation-like abilities if it keeps making its percent chance.
If the player with the alien that has a 10 CON were to roll 3, 9, and 41, her alien would have two physical mutations.

== General Considerations
In general, there are many questions which will arise when mutations are introduced into play.
Some of the more obvious problems are included here but many others are certain to arise.
The referee is expected to ad-lib and the complications covered here should give her a decent framework with which to improvise.

A persona must be conscious for a mutation to be used.
Unless a contradiction to this is stated in the description of the mutation.

Any degree of consciousness is sufficient for the mutant to use her mutation.
Mutations may still be activated even if she is stunned, dying, nauseous, falling or worse.

A constant frequency mutation cannot be turned off by the persona.
The mutation effect will be functioning whether the player wants it or not.

Restraints will only affect physical mutations that can be constrained.
A mental mutation usually cannot be stopped by binding a persona's paws.

Detecting the source of mutation attacks is only possible for physical mutations.
The source of a psionic attack may be very difficult to determine.

Psionic defence rolls involve little mental exertion and the brain acts subconsciously to defend against the intrusion.

Some powerful mutations are accompanied by scenario based affects.
For instance a time stop mutation may attract aliens that manipulate time.
A planal holdaway may cause trouble with the special drives.
The power of mutations should be delicately balanced with subtle inconveniences.

A consciousness will defend against any and all mental manipulations.
Mental attacks, life saving interventions, or innocuous irritation are automatically defended against.

// editing ended here.

== Targeting Mutations
The target of a mental mutation is whatever the mutant hopes to affect.
The target could be another persona, or an inanimate object.
The word target is generic for what ever the mutant wants to affect.

Most physical mutations require a target be within a specific range or line of sight.
The concept of targeting becomes challenging with mental mutations. 
Most mental mutations have their range clearly described.
That range usually requires line of sight if mutation effect travels in a straight line.
Is line of sight required for mind reading or telekinesis? 

Mental mutation effects that change the physical space need line of sight.
For example, a lazer eye attack needs line of sight.


Line of sight may be required for some mutations, while others merely require the mutant to sense the thinkspace of the target.
If there are any problems a to whether a mutation requires line of sight or not, the referee should decide using these overly simple guideline.
Mutations that travel in a straight line, and affect the target directly require line of sight, whereas area of effect mutations do not.

== Experience Levels 
Mental mutations improve as the persona increases in experience level.
The experience level of the persona is determined the amount of experience that she has amassed, and by her persona class.
Some may argue that class experience level should not affect one's psionic ability.
Experience level is a general rating of life skills, of which the mutant's psionic ability is included.
A more detailed explanation of what experience levels represent can be read in http://expgame.com/?page_id=273[Chapter 15: Experience].



== Mutation Attribute Explanations
Each mutation, whether mental or physical, has certain properties that describe what it is and how it affects play.
The attributes of each mutation are explained in the following paragraphs.
Not only should the basic feature of a mutation be recorded but the mutation number and the page number where the mutation can be found.

=== Name

The name of a mutation can give an inkling to what the mutation does or simply describe it outright.
The title can be deceptive so the mutation should be read in detail and the mutation number recorded on the persona record sheet.

=== Range
The range of a mutation indicates how far away the effects of the mutation can be delivered to a target.
Any exception to this meaning of mutation range will be specified in the mutation.
Many mutations can affect targets hexes away;
others require contact;
and some have a radius of effect.
Ranges are not devoted solely to offensive mutations and even defensive mutations may be critically affected by range limits.

The intensity of a mutation cannot be regulated and neither can its area of effect.
Only a single target mutation can be adjusted for different ranges from the persona.
Mutations that have areas of effect will indiscriminately affect all targets in this area of effect.

Nothing can stop a mutation which travels directly from one mind to another.
E.S.P., gyrokinesis, and telekinesis can pass through any barrier if the mutant has positive proof that the target exists.
Those mutations which manipulate the environment to attack a target such as mind blast or launch-able quills are subject to all terrain effects.

==== Distance
The most common is the ranged mutation.
Ranged mutations can be directed at any target within range of the mutant.
The range is determined by the MSTR and EXPS level of the attacker.
For example, a mutation may have a range of one hex @ MSTR.
This means one hex per point of mental strength and, with a 12 MSTR, a mutant could use the mutation 12 hexes away.
There are variations to this common range format.
Two hexes per MSTR would yield a 24 hex range with a 12 MSTR.
One hex per four MSTR would yield a three hex range with a 12 MSTR.
If the range includes MSTR and experience level then the two are added.
A fourth level persona with a 12 MSTR would have a 16 hex range with a mutation that was listed as one hex per (MSTR + level).

==== Area of Effect
Radius ranges are spherical and use the location hex of the persona for the centre.
Thus a mutation with a ten hex radius of effect would contain all targets within ten hexes including above and below the mutant.
The area of effect would include everything in the 20 hex diameter sphere.

==== Touch
Touch mutations are self explanatory.
The mutant must touch the target to inflict the effects of the mutation whether benevolent or not.
The touch must be hand, paw or claw to skin, fur or scales.
Some touch mutations can be conducted through material that would be considered conductive, like metal.
Some touch mutations may still be effective if derma to derma contact cannot be made.
They may be mutations with very short ranges, several millimetres, and a successful attack roll may be all that is needed to get within range.

=== Duration
The duration of a mutation almost always refers to the length of time that the mutation effects last.
If the mutant has telekinetic flight, she can stay aloft for the duration of the mutation.
Mutations usually require complete concentration on the part of the mutant.
If a mutation obviously does not require complete concentration on the part of the mutant then the concentration need not be maintained.
Mutations that are always in constant use do not require a significant portion of the mutant's mental or physical resources.

Mutations usually last so many units per point of MSTR and they may also be affected by the persona's experience level.
If a mutation has a duration of one until per MSTR, then the mutant can make the mutation last 12 units if she has a 12 MSTR.
Other variations of duration exist and they all function identically to the range variations discussed earlier, except that units replace hexes.
Mutations with random durations are determined each time the mutation is employed.
Such mutations indicate that the mutant has set in motion physical effects which she has no control over.

==== Until Saves
If the duration is "`until saves`", the mutant may continue the attack until the victim saves or is dead.

==== Permanent
When the duration says "`permanent`", it indicates that the effects won't dissipate on their own accord.
For instance, permanent healing of HPS means that they will not disappear after a certain number of units but it does not mean that the mutant has a cache of indestructible HPS.

==== Constant
Most mutations can be stopped whenever the mutant sees fit, except those mutations that have a "`constant`" duration or an "`until dead`" duration.
These mutations will function until the mutant is dead or has the mutation excised.

=== Frequency
The frequency of the mutation indicates how often it can be used during a daily cycle of the mutant.
The frequency assumes a 24 hour day (see Chapter 12: Time and Movement) where the mutant sleeps around eight hours each day.
If the mutant is in a situation where there is no planetary rotation or one where there is no 24 hour cycle, a complete rest (eight hours`' sleep) will be equivalent to the completion of a daily cycle.

Most mutations can be used several times a day depending on the MSTR and level of the mutant.
The more powerful the mutation, the less frequently it can be used each day.
If the frequency of a mutation is one per four MSTR, a persona with a 12 MSTR could employ it three times each day and would have to rest eight hours before using it again.
For this type of mutation, rest for the brain is essential.
Unless otherwise stated, a mutation can be used at least once a day.
This includes mutations which have very low frequencies (e.g.
one per 13 MSTR).
This mutation could be used once a day even by a persona with a MSTR of six.

Mutations which can be used more frequently are labelled "`as needed`" and just as the title states, the mutant can use such a mutation as it is needed.
"`Constant`" mutations are usually defects and they constantly project their effects regardless of what the mutant is doing.
Constant mutations always function whether the mutant is asleep or awake.

Mutations cannot be stored.
A mutant cannot use a mutation more often one day than the next because she saved some uses from the previous day.
The mutant may use the mutation no more than the frequency states and each use is cumulative until she rests.
Mutations cannot be compounded to double an effect.
The mutant can only use one mutation at a time unless one of the mutations has a "`constant`" or "`as needed`" frequency.

The mutant has used a mutation whenever the effects start.
Even if the target saves and the mutation has no effect, the mutation has been used.
If the mutant voluntarily stops the mutation then it has been used.
If the mutant switches from one target to another, this will usually indicate another use.

=== General Bonus
The general bonus listing of the mutation could contain several arcane bits of information that are related to the use of the mutation in unexpected circumstances.
If the mutation is particularly dangerous, then there may be a combat ration (CR) adjustment listed (see http://expgame.com/?page_id=257[Chapter 11: Referee Personas]).
The mutation may indicate a bonus for particular PT rolls, attribute rolls or negotiation rolls.
Any simple affect that the mutation has on the dice rolling of the persona should be included beside the general bonus listing.
