= Mental Mutations
Mental mutations function through the thinkspace of the EXP mythos.
These mutations may impact the physical space, but the effect is delivered through the thinkspace.
The thinkspace is a faux concept where organic consciousnesses exist. 
In this space, consciousnesses interact, allowing for extrasensory perception and mind control.
Mental mutations do not alter the persona's appearance, making these mutants indistinguishable from other personas.
These mutations are also called psionics, psychic powers, or mental attacks. 

Mental mutations require concentration of the mind, like lifting a weight involves contraction of the muscles.
The attribute that powers mental mutations is mental strength.


.*Mental Mutation Checklist*
. <<_mental_mutation_type,Any Mutation Type>>
.. <<_non_combat_mutations,Non Combat Mutations>>
.. <<_defective_mutations,Defective Mutations>>
.. <<_combat_mutations,Combat Mutations>>
. <<_mental_mutation_attribute_explanations,Mental Mutation Attribute Explanations>>


== Mental Mutation Type

include::ROOT:partial$CH58_Table_Mental_Mutation_Type.adoc[]

== Mutation Types 

=== Absorption

[horizontal]
Range:: Persona
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Combat Ratio +4

This mutant can absorb the assigned force that would typically damage her.
A laser bolt will dissipate over her entire body, or radiation will pass through her unaffected.
The damage type that the persona can absorb is determined on the Absorption Table.
A persona with absorption can absorb an amount of damage equal to her HPS Maximum plus 3 HPS per experience level.
Damage cannot be reduced to less than one point of damage.
For example, a level 4 persona with 30 HPS could absorb 42 HPS in damage.
If the attack is supposed to inflict less than 42 HPS of damage, she will take no damage.
Absorption cannot be used to gain HPS.

For combined attacks the players may need consult the xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice,window=_blank].

include::ROOT:partial$CH58_Table_Absorption_Type.adoc[]

=== Alternate Banishment

[horizontal]
Range:: 1h per Level
Duration:: Permanent
Frequency:: Daily per 12 Adjusted MSTR
General Bonus:: Combat Ratio +10

This mutation allows the mutant to transport objects to an alternate space of existence.
An object can include whole personas, and they are transported against their will.
This mutation can only be employed in situations of extreme duress;
like combat, surprise, or imminent death, etc.
The mutant can only banish complete objects.
If the object exceeds the mutant's power, then she cannot banish it.
The mutant can banish half her wate plus 5 kg per level.
A corpulent 4th level persona with a wate of 80 kg could banish any object less than 60kg.

All targets get a save vs psionic attack.
If the save is successful, the mutation has no effect.
Inorganic objects have a MSTR equal to the persona holding it.
Stray objects have a MSTR of 0-9 (1d10-1).

No one knows where the alternate space is, and the object or persona is permanently removed from the campaign. 
Isn't that like being killed?
Yes, it is precisely like being killed.

=== Animal Attachment 

[horizontal]
Range:: Touch
Duration:: Permanent
Frequency:: 1 Animal per 7 Levels
General Bonus:: +10 on biologist rolls

Animal attachment is pet bonding to the highest degree.
The persona and an animal become psionically attached.
The connection is totally different than a human-pet relationship.
There is a synergistic effect that elevates the animal to a much higher level of function.
The animal must be an alien that is defined as cannon fodder, or flora, or fauna. 
The alien must be smaller than the persona. 
The persona's wate must be twice that of the alien.
The persona must be smarter than the alien. 
The persona's intelligence must be 3 times that of the alien.
For example, a persona has a wate of 60kg and intelligence of 12.
This persona could bond with an alien 30kg or less and an INT of 4 or less.

The persona initiates the animal attachment.
The animal must win a psionic roll to avoid attachment.
If the bonding fails, the animal wanders off and can never be convinced again.
Successful bonding creates a telepathic bridge, sharing knowledge, intelligence and communication.

The animal immediately increases its intelligence through the connected consciousnesses.
The persona's intelligence score is added to the animal's intelligence.
In the example above, the persona would have a 12 INT, and the alien could have a new INT as high as 16.
This makes the attached animal more intelligent than the persona.
The animal frequently reminds the persona of this fact. 
Whether the alien's MSTR is increased or not is up to the players. 

The alien heightens her previous drives of food and reproduction.
She can guide the persona to clean water, clean food and eligible partners.
The last heightened ability often has the alien always making said suggestions. 
This is supposed to be a comedic relief source as the alien's timing is never that good. 

The two can speak telepathically without anyone noticing the connection. 
They just appear to be happier than the usual anthro-pet combo. 
The alien can only speak beyond telepathically with the persona.
The alien does not use a name with communicating telepathically.
The connection between the two is beyond names. 

The bond is inseparable. 
The death of the persona will result in the death of the alien.
The death of the alien will severely impact the persona.
If the persona could have prevented the death, she will be hit with severe attribute injuries. 
The sudden loss of counsel and telepathic connection crushes the persona's INT and MSTR.
The persona loses 1-6 (1d6) points on each attribute.
If either attribute drops below zero, the persona is dead.
The lowered attributes will return at 1 point per day. 
The player can add the point to either attribute until she heals.
The persona can only get another animal attachment once her attributes have been restored.

An unwritten permutation of this mutation is analog attachment. 
This allows the persona to have the same relationship with a robot.
Both intelligence and wate requirements apply. 

=== Calculations 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: As Needed
General Bonus::  +15 on any calculation rolls

Calculations allows the mutant to solve any mathematical analysis in seconds.
This arithmetic savant does not need paper, calculator to get the answer.
The mutant does require accurate data to work with. 
It is not a case of garbage in garbage out; the persona knows what info is missing.
When it comes to arithmetic, this mutant is fast as any artificial intelligence.
The answer will be blurted out within 2 seconds. 

This will make the mutant an excellent gambler, estimator, or astrogator.
The mutation is revered by mechanics and nothings. 
Any persona with this mutation can replace a space vehicle's astrogation software.

=== Communicate 

[horizontal]
Range:: Earshot
Duration:: Special
Frequency:: Special
General Bonus:: +15 on any language rolls

This mutant's brain understands the subliminal semiotics (meaning) of language.
Communicate allows her to communicate with any communicating entity.
The method of communication must be detectable by the persona.
As long as there are sounds, smells, motions, vibrations, she will understand.
Understanding the language does not always lead to communication.
For example, the aliens communicate using chemicals that the mutant cannot recreate.
So she will understand but not be able to 'smell' back.

If the mutant wants to speak the language permanently, she has a chance to add it to her repertoire.
There is a chance equal to the persona's adjusted intelligence times three of adding the language.
A 4th level mutant with a 10 INT would have a 42% chance to memorize the language.
If the language is essential to the persona she can try again later. 
Later is determined by the referee.
The mutant can have a number of languages equal to her level plus INT memorized.
The mutant described above could memorize 14 languages.

A memorized language allows a mutant to pass any fluency test, avoid idiomatic errors in diplomacy, and develop devices to help her communicate.
This mutation is especially helpful for biologists and nothings. 

=== Cryokinesis 

[horizontal]
Range:: 1h per Adjusted MSTR
Duration:: 5u per Adjusted MSTR
Frequency:: Once per 5 Adjusted MSTR
General Bonus:: Combat Ratio +3

Cryokinesis allows the mutant to make things around her very cold.
This mutation may be employed in a nasty way or a benevolent way.

The nasty cryokinesis is a mental attack.
The cryokinesis attack freezes the target's consciousness with a deadly chill.
The mental attack starts with a chill and eventually creates a corpscicle.
The target automatically takes 1-4 (1d4) hit points of damage in the first unit.
After the first unit, the target can repel the attack by winning a psionic roll.
The amount of damage inflicted increases by 1-4 (1d4) each unit the mutant attacks.

For example, the target takes 1d4 damage in the first unit.
If the target fails her next three psionic rolls, she will take more damage each combat unit.
Failing 3 rolls would result in 2d4 in the second unit, 3d4 in the third unit, and 4d4 in the fourth unit.
The target will either break the freeze attack or die.
When a target is killed by this attack, it is frozen solid.
If the freeze cycle restarts, the damage per unit restarts at 1d4. 
A mutant with a 10 MSTR could inflict up to 50d4 in damage in her last unit.

The benevolent cryokinesis acts like a psychic air conditioner.
This cooling only works on organic consciousnesses and cannot cool a machine or robot.
The mutant can comfortably cool organics in a four hex radius.


=== Death Field Generation 

[horizontal]
Range:: 1h per Level
Duration:: Permanent
Frequency:: Special
General Bonus:: Combat Ratio *3

This deadly mutation allows the mutant to drain life from surrounding organic personas.
Death field generation instantly drains hit points from the target(s) caught in the area of effect.
If a target persona fails her psionic roll all of her hit points are drained.
Anthros Hit Points Total is reduced to negative one half her Hit Points Maximum.
Aliens Hit Points Total is reduced to zero.
Robots are not affected by this mental attack.
Jump to xref:i-roll_playing_rules:CH13_Health.adoc#_death[Death,window=_blank] for more info about persona death.

The process is instantaneous and the mutant collapses unconscious afterwards.
The mutant remains unconscious for l minute per hit point consumed.
If the mutant absorb 90 hit points from target personas she would remain unconscious for an hour and a half.
During this unconscious state the mutant is very vulnerable.
Once the mutant regains consciousness, she may immediately use her death field generation again.

The mutant cannot control the range of the death field generation. 
Initially it sucks the life out of everything within 1 hex range.
At second level it absorbs all life within 2 hexes, and so on.
The mutant becomes more and more dangerous as her experience level increases.

The mutant can deselect 1 consciousness per 3 levels of experience. 
At 6th level the mutant's death field has an enormous 6 hex area of effect and she can spare two personas from death.

The referee can modify the duration of unconsciousness to limit the power of this mutation.
For example, the mutant may be unconscious for 1 hour per hit point. 

=== Density Control 

[horizontal]
Range:: 10h plus 1h per Level
Duration:: 3u per Adjusted MSTR
Frequency:: 1 per 4 Adjusted MSTR
General Bonus:: Combat Ratio +3

If the target wins the psionic roll, they are unaffected by the mutation.
This mutation can be used on organic and inorganic targets.
If the target is an object with no attributes, it is assigned a random MSTR of 0-9 (1d10-1).
If a target repels the density control, the mutant may try the next unit again.

The target must have a wate less than 10 times the mutant's wate.

Increasing density makes the target's molecular structure tighter and increases its wate in the same volume.
Armour rating increases by 20%.
Movement rate is decreased by 20%.
Any force related damage is decreased by 20%.
Falling damage is doubled.
Inanimate objects double their wate. 
Flying creatures fall from the sky.
Swimming creatures sink.

Decreasing density loosens the target's molecular structure and decreases its wate in the same volume.
Armour rating decreases by 20%.
Movement rate is increased by 20%, but the target has an increased chance of falling.
Any force related damage is increased by 20%.
Falling damage is decreased by 60%
Inanimate objects halve their wate. 
Flying creatures don't fall from the sky but can't fly in a straight line.
Swimming creatures float uncontrollably towards the surface.


=== Detections 

[horizontal]
Range:: 10h per Adjusted AWE
Duration:: Special
Frequency:: As Needed
General Bonus:: +20 on searching rolls

Detections give the mutant a veritable suite of organic detectors.
The persona gets one detection skill per 5 points of awareness.
If the persona has a 15 AWE, she will get three rolls on the below table.
For example, she could detect water, poison and food.
If the same detection is rolled twice, the detection mutation is twice as effective.
A doubled detection has twice the range and doubles the effectiveness. 

This mutation has two functional elements: detecting and locating.

Detecting happens immediately. 
If a lie, life or a robot is present, this mutation will immediately detect it.
These detections have a binary presentation. 
Yes, there is a lie, but not what the lie is.
Yes, the is life, but not whether it is friend or foe.

When used to locate resources, the resource must actually be present. 
For example, looking for pharma will only work if there is pharma to find. 
This is up to the referee.
The chance of successfully sniffing out a resource is equal to three times the persona's awareness.
For example, a persona with 14 AWE has a 42% chance of finding safe water.
The water must be within range, and the search will last about 1-12 (1d12) minutes. 
This mutation will also send personas in the correct general direction of the water. 

include::ROOT:partial$CH58_Table_Detection_Type.adoc[]

=== Directional Sense 

[horizontal]
Range:: Special
Duration:: Constant
Frequency:: As Needed
General Bonus:: +30 on wayfinding rolls

This mutant psionically locates herself within the thinkspace and cannot get lost.
Directional sense allows the mutant to take a correct heading from as little as a claw's pointing.
The mutation has an unlimited range, but it does not work through hyperspace.
If the mutant remains on the planet, she cannot get lost.
She will find her way 'back' after air travel, underwater travel or unconscious travel.
Knowing where to go does not guarantee the ability to get there.
Travel may require boats, planes, or even space vehicles. 
Directional sense does not work through hyperspace, and the mutant cannot find her way home after a special drive jump. 

This mutant is an absolute master of all navigation. 
This includes astrogation, aquatic, subaquatic and terrestrial navigation.


=== Empathy 

[horizontal]
Range:: 1h per Adjusted MSTR
Duration:: Special
Frequency:: 1 per 4 Adjusted MSTR
General Bonus:: +20 for interpersonal rolls

This mutation allows the mutant to experience the feelings of personas near her.
Empathy picks up on emotions like fear, joy, sorrow, pain, etc.
Most personas will not notice that the mutant is "listening in" on their emotions. 
If the mutant is lightly probing a target for superficial emotions, the target will not notice the intrusion.

When the mutant starts to dig deeper into the target's consciousness, a psionic roll is given.
If the target wins the roll, they will notice the intrusion.
A second psionic roll must be won to block the mutant from reading her emotions.

The information gained from empathic probing has many advantages for the mutant.
It will assist them greatly in negotiation, gambling, leadership, and dating.
Empathy is not mind reading and does not give off details of plans or goals. 

=== Energy Attraction 

[horizontal]
Range:: 10h per MSTR
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Defect

This mental mutation defect turns the persona into an energy sink.
When an energy weapon is fired near this mutant, the bolt may redirect towards her.
If a lazer, fission gun, plasma gun is fired within the range of this defect, there is a chance it will change direction towards her.
This includes the energy attacks of fellow personas.
The chance is equal to the persona's MSTR.
If the mutant has a 10 MSTR, there is a 10% chance an energy weapon will change direction towards her.
An attack roll that was directed at another persona is redirected at this mutant.
Ouch.

The redirected attack wastes significant energy and accuracy when changing direction.
The attack roll has a penalty of -200. 
If the attack roll is a hit, the damage is reduced by 25%.
If the attack roll is a miss, the energy beam dissipates harmlessly.

Energy attraction only affects gun attacks and does *not* attract artillery, bombs, or grenades.
The fusion gun is specifically not attracted by this mutation. 

Energy attraction turns off if the mutant is unconscious or sleeping.
Directly attacking this mutant with an energy weapon does not improve the attack roll. 

include::ROOT:partial$Defect_Disclaimer.adoc[]

=== Extrasensory Perception 

[horizontal]
Range:: 2h per Adjusted MSTR
Duration:: 2u per Adjusted MSTR
Frequency:: Special
General Bonus:: Combat Ratio +5, +20 on interpersonal rolls

Extrasensory perception (ESP) allows the mutant to listen in on the thoughts of other personas.
This is the most famous of all the psionic powers in the world of sciency fiction.
The mutant can probe the consciousness of organic creatures through the thinkspace.
The persona does not listen in on actual words, but the icons of sentience. 
This allows the understanding of any type of organic mind regardless of language or family.
ESP is not able to probe a robotic mind. 

The players are not expected to interpret the semiotics of alien consciousness.
The referee will simply reveal the thoughts in plain language.
For example, the mutant would know if a target brain is planning an attack.
The mutant could also learn what cards a gambler is holding.
A lie would not only be detected, but the nature of the lie and what truth is as well.
Having an Esper (a mutant with ESP) mutant is a total game-changer for the referee.

A consciousness will attempt to repulse this level of intrusion.
Before any information can be gleaned, the target must lose a psionic roll. 
A win on the psionic roll blocks the mutant from reading the target mind.
A win on the psionic roll does not allow the persona to alter her thoughts to trick the mutant.
Only another Esper could send fake thoughts to the mutant. 
It is also impossible for the persona to know who or what was invading her mind.

A failure on the psionic roll gives the mutant free range inside the target's mind.
The mutant has limited time inside the target mind. 
The mutant can read the target mind for 1 unit per point of adjusted MSTR.
For example, a mutant with an adjusted MSTR of 15 could browse the target mind for half a minute.
At the end of this time, the target gets another psionic roll to block the intrusion.
The mutant may "listen in" until a psionic roll throws her out.

Once blocked from reading the target mind, the mutant must have one night of restful sleep before trying again.
The mutant can only listen to once consciousness at a time. 

For the referee, this mutation can be a challenge. 
It is easy to inform the player what is going on in the minds of referee personas. 
The referee can reveal plans, desires and ridiculous misconceptions about food to the player.
The challenge is when the player decides to probe the mind of fellow players.
This would be the highest level of team role-playing.
The referee may just ask a player what their persona is thinking.
The mutant may or may not have nefarious intent with the information. 
This kind of power is what leads to a general mistrust of mental mutation powers.

:art: force_field_crash.png
:width: 250px
:snark: Insurance nightmare
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of car crashing around a pedestrian protected an invisible shiled.

include::ROOT:partial$articulate.adoc[]

=== Force Field Generation 

Range:: Persona Only
Duration:: Until Destroyed
Frequency:: 1 per Sleep
General Bonus:: Combat Ratio *2

The force field generation mutation creates a protective shell around the mutant.
The force field may appear as a shimmering translucent shell or be completely transparent.
The shell will keep out rain, dirt, bugs, small animals, and other harmless nuisances.
The force field will also absorb bullets, lazer bolts, clubs, fire, aerosols, explosions, etc.
The force field does not prevent gases from gently wafting into the psionic protective shell.

The mutant is always at the center of the force field, and it moves around with her.
The mutant can't generate her force field and leave it behind.
The mutant cannot create multiple force fields or partial force fields.
The force field continues to function if the mutant is unconscious.
The force field persists until the mutant turns it off, or it is destroyed.

The force field is damaged by anything that would injure the mutant.
The force field can withstand 10 hit points per point of adjusted MSTR.
A 4th level persona with a 16 MSTR has a force field that can withstand 200 hit points of damage.
For example, an attacker scores a successful attack roll and rolls 17 hit points of damage.
This damage is subtracted from the mutant's force field and not the mutant.
An attack roll must be successful before the force field is damaged.

The force field will not prevent attacks from poison gas or radiation.
These attacks can still waft into the shell.
The intensity of attack is reduced by half as it passes through the force field.
Most psionic attacks are unaffected by the force field.
Extrasensory perception is unaffected, while mental blast is completely absorbed.
If the mental attack acts via the physical space, it will be absorbed by the force field.
The force field does not work exatmo and cannot protect the mutant from the vacuum of space.

The shell allows anything to exit (except the mutant).
The mutant can attack from within her force field using ranged attacks. 
The mutant cannot use type A attacks (non-powered thrusting and striking weapons) from within the shell.
Unwanted objects within the force field can easily be evicted by the mutant.
To share the force field with other personas, they must be hugging the mutant before shell generation. 
If they let go, they will be ejected from the force field. 

The mutant requires one night of restful sleep to generate another force field. 

=== Gyrokinesis 

[horizontal]
Range:: 1h per Adjusted MSTR
Duration:: 1u per Adjusted MSTR
Frequency:: 1 per 6 Adjusted MSTR
General Bonus:: Combat Ratio +3

This mutation forces a target to involuntarily revolve.
The target will slightly elevate from the ground and begin to spin.
The spin is around the target's longitudinal axis and parallel with gravity.
Gyrokinesis does not allow for translational motion, and the target spins the same spot.
Angular momentum is thrown to the wind, and the target cannot alter her rotation frequency.

The first unit of this mental attack automatically affects the target.
The target is held in place and involuntarily begins to spin.
The initial frequency of the revolutions is not high.
The target suffers -50 on her attack roll, and +50 on attack rolls against her.
The spinning makes it harder for her to hit a target and easier to be hit.
In the second unit of the attack, the target gets a psionic roll. 
If she wins the psionic roll, the spinning stops.
If she fails the psionic roll, she spins even faster, and the penalties get even worse.
The target's attack roll suffers a -100 penalty, and attacks against her increase to +100.
The target must win a CON attribute roll or fall unconscious.
This process repeats each unit until the target goes unconscious.
In the 3rd unit of the attack, the target suffers a -150 attack roll penalty, a +150 bonus against her. She must win a CON attribute roll at -1 or go unconscious. 

.*Example Gyrokinesis Attack*
. No psionic roll allowed. -50 attack roll. +50 to be attacked.
. -100 attack roll. +100 to be attacked. CON attribute roll to stay conscious.
. -150 attack roll. +150 to be attacked. CON attribute roll -1 to stay conscious.
. -200 attack roll. +200 to be attacked. CON attribute roll -2 to stay conscious.
. -250 attack roll. +250 to be attacked. CON attribute roll -3 to stay conscious.
. A steady-state is reached. The CON attribute roll penalty increases. 

The target can only use abilities like mental mutations while spinning.
It is impossible to do complicated maneuvers or tasks. 

If helpful personas grapple the mutant, they may begin to spin as well. Touching the mutant adds the rescuers to the spinning mess if they fail a psionic roll.

After the first unit, the target will be spinning too fast to be grabbed.
Fastening the target down prevents spinning but does not prevent the attack's effects.

The gyrokinesis attack stops if the target wins a psionic attack roll.
The target will be incapacitated for 1 minute per unit she was spinning. 
The gyrokinesis attack stops if the target loses consciousness. 
The target will remain unconscious for 5 minutes per unit she was spinning.
The gyrokinesis attack stops if the target dies. 
The target will remain dead permanently.

Gyrokinesis can be used against organic and inorganic targets. 
Inanimate objects have a MSTR of 0-9 (1d10-1) and will resist being spun about.

=== Heightened Brain Talent 

[horizontal]
Range:: Persona Only
Duration:: Special
Frequency:: Once per Sleep  
General Bonus:: Special

Heightened brain talent allows the mutant to the whole brain to obsess over one specific problem.
The mutant curls up into a ball, her temperature rises, and her eyes flicker and blink.
The fit of cerebral activity is easily mistaken for a seizure.
The problem-solving trance lasts 1-4 (1d4) minutes.

The fruit of this ungraceful spasm of thinking is an answer.
The answer will almost always be correct, but the solution will usually be complicated.
The percent chance of coming up with a correct answer is 90 plus the mutant's INT score.
This percent chance of success cannot exceed 99%.
A mutant with and 15 INT would have a 99% chance of success, not a 105% chance of success.
If the answer is wrong, the mutant will know and will dispense with the answer immediately.

This mutation is extremely powerful and limited at the same time.
Heightened brain talent should not short circuit session puzzles or a campaign arch.
The player can be given a truthful and correct answer to the question.
However, the solution to this answer could be very complicated.
The answer can be known, but the solution may require sneaking into a restricted area.
Heightened brain talent should advance the story, not short circuit the story.

Heightened brain talent does not allow the mutant to predict the future or solve the mysteries of consciousness.
The following questions are unsolvable. Will I die if I do this? Why are we here? Or what is the "question to the answer"?
Unsolvable questions will injure the mutant and leave her bemusedly confused for 2-16 (2d8) days.

=== Hostility Field 

[horizontal]
Range:: 1h Radius
Duration:: Until Dead
Frequency:: Constant
General Bonus:: -25 on negotiation rolls

This mutation has a self-explanatory title.
There is a field of hostility that surrounds this mutant.
The mutant has some strange psychic effect on all creatures within a one hex range, causing them to have hostile emotions towards the mutant.
This defect has no effect or inorganic personas. 

Outside of the radius of effect, personas have an indifferent attitude towards the mutant.
This indifference turns to overt hostility once inside the area of effect.
During moments of disagreement, the hostility can become quite acute.
Between expedition members, this will rarely come to blows.
If a fight does break out between expedition members, it will always be xref:i-roll_playing_rules:CH37_Non_Lethal_Combat.adoc[Non-Lethal Combat,window=_blank].
However, flora, fauna, pets, and personas of extremely low INT will attack the mutant.

Mutations with this defect suffer many challenges within the campaign.
Veterinarians are repulsed by them when trying to heal them.
Or patients are repulsed by a veterinarian with this mutation.
Relationships do not work out, ever.
Store clerks are more than rude.
Negotiations go poorly. 
Family dinners were cancelled long ago.
Mutants with this defect are often isolated and surrounded by inorganic personas.

include::ROOT:partial$Defect_Disclaimer.adoc[]

:art: illusion_generation_maybe.png
:width: 250px
:snark: Illustrating illusion
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of woman in library confused by images of fairgrounds.

include::ROOT:partial$articulate.adoc[]


=== Illusion Generation 

[horizontal]
Range:: 5h per Adjusted MSTR
Duration:: Special
Frequency:: 1 per 4 Adjusted MSTR
General Bonus:: Combat Ratio +5

Illusion generation allows the mutant to generate sounds, images and sensations for the target.
These illusions can range from a faint noise to a full audiovisual experience.
The illusion only appears in the sensorium of the target. 
If the target wins a psionic roll, the illusion will not form.

An auditory illusion could distract a target and have her wander off to investigate.
An olfactory illusion could divert hungry flora or fauna. 
A visual illusion could cause a driver to veer off the road.
A complete illusion with sound, smell, sensation, and moving imagery could trick a persona into engaging in a battle no one else can see. 

The mutation illusion generation only works on organic personas.

The target will completely believe the illusion if they fail their psionic roll.
They cannot be convinced otherwise.
Challenging a persona experiencing such vivid sensations may lead to intense anger.
The target will feel like they are being called a liar or delusional. 
The illusion is solely within the target's senses and nowhere else.

Illusions are affected by their complexity and believability.
The more complex the illusion, the more energy the mutant expends to maintain it.
A full-featured audio, visual, somatic, and olfactory illusion will have a short duration.

include::ROOT:partial$CH58_Table_Duration_of_Illusion.adoc[]

The less believable the illusion, the less likely it is to work.
Smells, sounds and fleeting images are believable, and the target may succumb to them without getting a psionic roll.
A Doppelganger expedition member attacking the target would get an enormous psionic roll bonus. 

The psionic roll bonus ranges from +1 to +6. 
A way to estimate this is by giving +1 per concept the target needs to deny.
Generating the illusion of good smelling food around chow time would get no bonuses.
The ref may not even offer a psionic roll to the target.
Having the target's mom (+1), who is from another planet (+2) and is deceased (+3), talking her would give the target +6 on her psionic roll. 

Mighty mutants can create elaborate lethal illusions in the minds of weak targets.

=== Information Eradication 

[horizontal]
Range:: 1h per Level
Duration:: Special
Frequency:: 1 per 5 Adjusted MSTR
General Bonus:: Combat Ratio +6, +15 when convincing others

The mutant can force a persona to forget something stored in her memory.
The memory loss is temporary and total.
The target will not even know that she has forgotten something. 
The thought, concept, skill is simply not there.
The target must fail her psionic roll to have the memory erased.
This mutation only works on organic personas.

The more critical the memory, the harder it is to eradicate it.
The more critical the memory, the shorter the time it is eradicated.

include::ROOT:partial$CH58_Table_Memory_Importance_and_Eradication.adoc[]

If necessary, the referee can randomly determine how valuable memory is to the target persona.
The importance of a memory can be determined by a 1d8 roll.
Essential memories like birthdays, names of children, skills and abilities should always be significant.
Only a very powerful mutant psionically attacking a weak target could erase a skill or ability.

Forgetting a memory can be very disconcerting for a target persona. 
Repeatedly information eradications will raise a persona's sense of paranoia and suspicion.

Information eradication cannot be used to reverse engineer what the target persona knows. 
The mutant must know that a particular memory is present before erasing it. 
Information eradication cannot be used to fish for what a target knows by erasing random memories.

=== Intuition 

[horizontal]
Range:: 1h per Adjusted MSTR
Duration:: Not Applicable
Frequency:: 1 per 3 Adjusted MSTR
General Bonus:: Combat Ratio +2, +29 on anything intuitive

Intuition gives the mutant allows the mutant to correctly guess what will happen very soon.
This mutation needs to be intentionally employed and does not "warn" the mutant without being activated.
Intuition would not pre-warn a person of an ambush.
If a mutant specifically asked about an ambush, an answer would be given.

The answer to an intuition question has a binary answer.
The answer could be a simple yes or no. 
The answer may be more like a feeling of danger or no danger.
The answer never includes what is behind the door.
The answer only refers to the immediate future and not the long term implications of the question.

The question gets a psionic roll to not reveal anything to the mutant.
Usually, the question has a mental strength of 0-9 (1d10-1).
If the question directly involves a persona, then that persona's MSTR would be used for the psionic roll.
The mutant will know if her intuition did not work. 
A psionic roll won by the question does not equal a false intuition. 

The player wants to know if it is safe to break through a door into a new room.
The question would be exactly that, "Is it safe to break into this room?"
If the room is safe and the question loses its psionic roll, the mutant will feel safe.
If the room is safe and the question wins its psionic roll, the mutant will get no answer at all.
She may query again immediately if she has the psionic resources left.
If there is an activated combat robot in the room, intuition would reveal danger, but nothing else.
If there was an inactivated combat robot in the room, intuition would reveal safety.
If the expedition activates the combat robot later, the first intuition was still correct.

The intuition mutation is meant to be useful. 
So the referee should not be playing mind games trying to get the mutant killed.
The intuition mutation is not all revealing.
So the player should be playing 20 questions to disassemble a referee's puzzle.
The referee and players must work together to make intuition useful and fun.

=== Knowledge Transmission 

[horizontal]
Range:: Touch
Duration:: Special
Frequency:: Special
General Bonus:: None

Knowledge Transmission allows the mutant to store and transfer information from one persona to another.
The mutant acts as a repository for the data and may not even understand what she is transmitting.
The chunk of knowledge must be a discrete element. 
For example, the recipe for a secret sauce or a Mortal Moon Ship plan would be discrete enough.
However, all childhood memories or secrets about your enemies would not be discrete enough.

The mutant must first acquire the knowledge from a source.
If the source is a willing transmitter of the knowledge, the mutant makes a copy of it in her consciousness.
If the source is not a willing transmitter of the knowledge, she gets to make a psionic roll.
If she wins the psionic roll, the knowledge is blocked from the mutant.
If the source is inorganic, like a robot, an AI or a computer, a psionic roll is always made.
Inorganic sources automatically protect their data.
Inorganic sources use their INT score instead of their MSTR score for the psionic roll.

Once the knowledge is acquired, it is stored in an incorruptible state until the mutant transmits it or is dead.
The mutant cannot use this information as part of her knowledge base. 
She can only transmit the data.
The mutant can hold one discrete knowledge point per point of adjusted INT.

Delivering the data is basically the reverse of acquiring the data.
Organic personas must lose a psionic roll to have the knowledge inserted into their consciousness.
Inorganic personas automatically absorb the information. 

When knowledge transmission has been blocked for the mutant, she must have one restful sleep before attempting transmission again.

Once delivered, the information is gone. 
One source and one destination only, the mutant is not a knowledge photocopier.
Some mutants have transmitted knowledge into fellow personas for later retrieval and transmission.

Knowledge transmission cannot be used to reverse engineer what the target persona knows. 
The mutant must know that a particular memory is present before copying it. 
Knowledge transmission cannot be used to fish for what a target knows beyond the source knowledge.


=== Levitation 

[horizontal]
Range:: Persona Only
Duration:: 30u per Adjusted MSTR
Frequency:: 1 per 2 Adjusted MSTR
General Bonus:: Combat Ratio *4, +10 on sneaky rolls

Levitation allows the mutant to psionically counter gravity and float in the air.
This ability is made most apparent by levitating upwards and defying gravity itself.
Levitation also allows the mutant to safely lower herself into a gravity well without falling.
This mutation allows for up and down movement but not translational movement.
However, it is straightforward for a levitating mutant to move around by other means. 
While not able to fly around, the tactical advantage of the literal high ground is essential.

The mutant can move up and down at double her movement rate.
The levitation movement rate is determined by either her MSTR or DEX score.

Levitation can be used to counter the effect of gravity changes.
When levitation is active, the mutant has no penalties for any gravity between 0 and 8 G.
She can absorb an additional gravity per 2 levels.
Levitation cannot overcome a failed gravity system in xref:i-roll_playing_rules:CH38_Space_Vehicle_Combat.adoc[Space Vehicle Combat,window=_blank]. 

Levitation can be used to assist in lifting heavy objects.
The mutant can counter her own wate and add it to a deadlift. 

Levitating mutants can transfer combat forces into translation motion.
This reduces the damage from kinetic force attacks by half.
A hit from a lazer would have no kinetic force. 
A hit from an axe would be all kinetic force.
Only half the damage is inflicted. 
The other half of the damage sends the mutant flying away 1-8 (1d8) hexes.

=== Life Leech 

[horizontal]
Range:: Touch
Duration:: Permanent
Frequency:: Constant
General Bonus:: Combat Ration +1 per HPS Drain

Life leech allows the mutant to painlessly drain the life force from a persona.
The drained life force is measured in hit points and improves the mutant's hit point total.
Life leech only affects organic personas.

Each touch by the mutant drains at least 5 hit points from the target.
The amount drained increases by 1 hit points per level of the mutant.
So a 3rd level mutant would drain 8  hit points per touch.
The mutant can cling to an incapacitated target and kill them.
Life leech works through any conductive material. 
This mutant could punch, hug, or iron bar a target to activate life leech.

The life force (hit points) is not wasted, and the life force heals the mutant.
So if the mutant drains 8 hit points from the target, her HPS Total increased by 8.
This does not stop until her HPS Total is double her HPS Max.
So a mutant with an HPS Max of 21 could increase her HPS Total to 42. 

These bonus hit points quickly dissipate after the adrenaline of battle ceases.
The mutant returns to her HPS Max after a nap or being knocked out.

The mutation is constant. 
A pat on the back, shake of the paw, or romantic hug will drain hit points.
The target does no notice the lost hit points. 
The attack is painless, and there is no psionic roll to fight it.
A sweet cuddle with this mutant would kill the snuggled persona dead in short order.
They would not know what is happening.
Romantic relationships are challenging indeed.

This mutation is not a defect. 
It is socially challenging. 
Mutants with life leech are often isolated lonely personas.


=== Light Wave Manipulation 

[horizontal]
Range:: Persona Only
Duration:: 30u per Adjusted MSTR
Frequency:: 1 per 4 Adjusted MSTR
General Bonus:: Combat Ratio *4, +42 on sneaky rolls, +25 on optics rolls

This mutant can manipulate electromagnetic waves in the spectrum of visible light.
She can warp and bend the waves to achieve a variety of effects.

Lightwave manipulation allows the mutant to do the following:
* Become invisible
* Create darkness
* Deflect lazers
* Hide her shadow
* Glow

Lightwave manipulation does not allow the mutant to create images out of light.
She can only manipulate the light that hits her body.
Manipulating this part of the spectrum works on any visible light detector.
This includes organic eyes and inorganic video sensors.

The effect is on the persona only.
However, she can include the equipment she is carrying.
The persona must not be encumbered by her equipment.
Too much junk too hard to bend the light. 
For example, her backpack and personal devices fall within her range.
The vehicle she is in or the powered armour she is wearing is outside her range.

.Invisibility
The most common use for this mutation is to hide within the visible spectrum.
Invisibility does not reduce noises made by the mutant. 
Good listening could reveal her general location.
Good sniffing could reveal her general location.
Radar and sonar could detect the mutant.
Lazer sight would not detect the mutant.
Infravision or ultravision may give the mutant away as well.
It would be expected that invisibility would work on all anthros.
Firing an energy weapon may reveal the mutant once the projectile leaves her personal space.

.Deflecting Lazers
Any lazer attack from a personal weapon with a calibre less than extra high power can be bent by the persona.
This does not work for artillery or energy weapons like fission, plasma or fusion weapons. 
The persona cannot be both invisible and deflecting lazer attacks. 
This requires too much concentration.


=== Magnetic Control 

[horizontal]
Range:: 1h per Adjusted MSTR
Duration:: 1u per Adjusted MSTR
Frequency:: 1 per 2 Adjusted MSTR
General Bonus:: Combat Ratio +2, +10 on magnetic rolls

Magnetic control allows the mutant to turn herself into a walking electromagnet.
The effect is broader than a regular magnet as anything metallic is attracted.
This includes any metal alloy as well as classic ferrous metals.
If there is discussion about whether an object has enough 'metal' to be attracted consult the xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice,window=_blank].

When the mutant activates her magnetic control, metallic objects hurtle towards her.
Anything not held in place will fly towards the mutant epicentre.
Knives, guns, robots, artifacts hurtle through the air and gently attach themselves to the mutant.
Using magnetic control does not crush the mutant in a barrage of flying metal.

Any object less than half the mutant's wate will immediately fly towards her.
These smaller objects travel across the radius of effect under a unit.
Metallic objects being held can be rent from the holder.
The persona holding the object must win a PSTR roll vs the mutant's MSTR.
If the persona wins the PSTR roll, she does not lose the object.
However, all she can do is hold onto it.
A sword could not be used as a weapon as she would be wrestling with it.

Objects more than half her wate, but less than her wate slowly drift towards the mutant. 
They will scrape along the ground at 2 hexes per unit. 
The larger objects can be easily stopped by other personas.

Objects that exceed the mutant's wate are unaffected by magnetic control.
The mutant can use magnetic control to attract herself to a large metallic object.
This is done at the discretion of the mutant. 
Smaller objects will still be drawn towards. 

:art: babooshka_head_maze.png
:width: 250px
:snark: Teamwork in one consciouness
:artist: Studiostoks
:date: 2015
:license: Copyright Studiostoks
:description: Drawing of man with many heads inside his head.

include::ROOT:partial$articulate.adoc[]



=== Mass Mind 

[horizontal]
Range:: 1h per Adjusted MSTR
Duration:: Special
Frequency:: 1 per 4 Adjusted MSTR
General Bonus:: Combat Ratio +4, +10 on psionic rolls

Mass mind allows the mutant to behave as a psionic amplifier.
The mutant can channel and manipulate mental mutation within the mass mind range.
This allows the mutant to redirect a mental blast, or increase the range of telepathy or combine mental mutations.
Using mass mind can be helpful to the mutation user or detrimental. 
Redirecting a mental blast mutation would be frustrating for the mutant doing the blasting.
Using mass mind to increase the range of a mental blast could be very helpful.

Only mutations with ranges can be redirected by the mutant's mass mind. 
Mutations that require touch can only be redirected by mass mind if the mutant is within the touch circuit.

Mass mind can only amplify or redirect a psionic attack.
Mass mind cannot be used to dampen, or cancel, a mental attack. 
When mass mind is being used to redirect a mutation, a psionic roll is given to prevent redirection.
When mass mind is being used to amplify a mutation, no psionic roll is required.

The mutant must choose from *one* of the following amplifications: double range, double intensity, or double damage. 
The target persona gets all the same psionic rolls to defend themselves as they usually would.

Mass mind could redirect mental blast from one persona target to another target.
The mutant deploying mental blast must win a psionic roll, or the mental blast is diverted.
Mass mind could be used to double the damage of mental blast. 
There would be no psionic roll needed when improving mental blast.

This mutation is fraught with complicated interactions. 
If the mass mind doubles the range of death field generation, does it affect the mutant?
If intense discussions arise remember that xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice,window=_blank] can help answer the unanswerable. 

:art: mechanical_medical_desat.png
:width: 250px
:snark: Heart beats not by dre
:artist: Studiostoks
:date: 2015
:license: Copyright by Studiostoks
:description: Drawing of mechanical heart surrounded by pair of headphones.

include::ROOT:partial$articulate.adoc[]

=== Mechanical Sense 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Combat Ratio *2, +42 on inorganic related rolls

This mutant has a way with machines.
Mechanical sense gives the mutant the ability to understand anything mechanical.
The mutant can even telepathically communicate with machines.
The mutant must touch the machine for the telepathy to work. 
Simple machines like levers, swords, or clubs cannot communicate. 

There is a chance that the mutant can communicate with a particular machine.
The chance is 3% per point of adjusted MSTR.
A 2nd level mutant with an 11 MSTR has a 39% chance of communing with a specific machine.
Once a relationship has been established, the machine and mutant can chat as needed.

The mutant could pick up a gun and ask it when it was last used.
The gun would answer telepathically to the mutant.
The more complex the machine, the more developed the level of communication is.

Mechanical sense can be organic or inorganic.
The referee may allow the player to choose between the two. 
The chance of randomly having organic mechanical sense is 15%.
The vast majority of mutants with mechanical sense will have the classic inorganic type.

Organic mechanical sense allows the mutant to communicate with organic machines.
The mutant could talk with a bone, liver, heart of a living organism. 
The conversation is telepathic, and the mutant must be touching the body containing the machine. 
There are some self-standing organic machines. 

The chance of communicating with an organic machine is much less likely.
The chance is 1% per point of adjusted MSTR.
A 2nd level mutant with an 11 MSTR has a 13% chance of communing with an organic machine.
The mutant must reconnect with the organic machine each time she wishes to chat. 

A mutant with an inorganic mechanical sense performs as a 2nd level mechanic. 
A mutant with organic mechanical sense performs as a 2nd level veterinarian.
The mutant can have any vocation and still function with those skills. 
A 4th level spie would also function as a 2nd level mechanic. 
If the mutant chooses the vocation that aligns with her mutation, she performs at +2 levels on maneuvers. 

=== Mental Blast 

[horizontal]
Range:: 2h per Adjusted MSTR
Duration:: Permanent
Frequency:: 1u Recharge
General Bonus:: Combat Ratio +1 per Level

Mental blast is a psionic concussion wave felt in the physical space.
The blast wave clearly emanates from the mutant's forehead.
The player can fashion its appearance as desired.
The mental blast cannot be hidden from any persona that witnesses it.

The mutant can make this attack every other unit during combat.
Mental blasts can be emitted without affecting any other task.
The mutant can attack with other weapons, user other mutations, or do maneuvers.

Mental blast requires a line of sight. 
There is no psionic roll to defend against. 
The blast rocks the physical space.
No attack roll is required by the mutant. 
Only defences specifically designed against mental attacks are effective.

This attack does 2-8 (2d4) HPS of damage, plus 1 HPS per level.
A 4th level persona would inflict 6 to 12 (2d4+4) HPS of damage.

=== Mental Control 

[horizontal]
Range:: Special
Duration:: Special
Frequency:: Special
General Bonus:: Combat Ratio *2 + CR of all mentally controlled

Mental control allows the mutant to take over the body and mind of another persona.
The mutation works best with skin contact on an organic persona.
If skin to skin contact is not possible, the mutant must win an attack roll.
Once contact is made, the target must win a psionic roll or fall under the mutant's control.

When the target succumbs to mental control, touch is no longer required, and the mutant controls the target remotely. 
The range of mental control is 1 kilometer per point of adjusted mental strength.
Mental control does work across an atmosphere (from inatmo to exatmo).

The mutant can mentally control more than one target at a time.
The total number of mentally controlled targets is limited by the mutant's intelligence and the target's intelligence.
The combined intelligence of controlled minds cannot exceed the mutant's adjusted intelligence. 
A mutant with an adjusted INT of 12 could mentally control three personas with an INT of 4.
If the target has a higher INT than the mutant, she can still control the persona, but not likely for long.

The player with the mutant persona controls two personas.
The target's eyes become the mutant's eyes. 
The target's mouth becomes the mutant's mouth.
The target's consciousness is controlled by the mutant.
This includes mental mutations and physical mutations of the target.

There are some complications the players must keep in mind. 
When the mutant sleeps, the target sleeps. 
When the mutant is unconscious, the target goes unconscious.
The connection between the mutant and the target allows for target effects to leak into the mutant.
If the target is attacked with a mental mutation, the mutant is also attacked.
If the target is knocked unconscious, the mutant must win a constitution roll or go unconscious.
If the target is killed, the mutant must win a mental strength roll or go unconscious.

.*Breaking Mental Control*
The mutant will instantly know that mental control has been lost, but the loss of control should surprise the mutant. 

A target that exits the range of mental control automatically breaks free.
Smarter targets get more frequent checks to escape mental control.
Placing the target at extreme risk by making terrible choices allows for a mental control check.
Mental control checks are warranted if the mutant places the target in peril.
Mentally controlled targets are not suicidal, and their survival mechanisms will challenge self-harm.
The player should also remember that harming the target can also damage the mutant.

include::ROOT:partial$CH58_Table_Mental_Control_Checks.adoc[]

Targets do not like to be mentally controlled, but dependence is possible.
The mutant can dismiss a target from mental control only if the target wins her psionic roll.
The Mental Control Check Table determines when dismissal can be attempted again.
If the target has a 5 INT, the mutant must have to wait 3 days before attempting dismissal again.
Low intelligence personas can stay controlled for an extended time.

:art: melting_woman_gutter.png
:width: 250px
:snark: Melting into the background
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of human woman half turned into water escaping down drain.

include::ROOT:partial$articulate.adoc[]


=== Mental Control Over Physical State 

[horizontal]
Range:: Persona Only
Duration:: Constant
Frequency:: As needed
General Bonus:: Combat Ratio +5

This mutant is capable of conscious control over the ordinarily automatic physical functions of her body.
Mental control over physical state is used to reduce malevolent effects on the body. 
This is done by controlling previously automated physiologic processes.
Breathing can be made very shallow to reduce respiratory damage from gases.
Arterial flow can be redirected away from a bleeding site.
Venous return can be reduced from a poisonous bite.
Hormones can be controlled to reduce hunger, end fertility, or control sugar levels.

Malevolent physical effects can be reduced by 1 quarter.
Benevolent physical effects can be increased by 4 times.

If a killing poison was supposed to inflict 80 HPS in damage, it would only inflict 20 HPS. 
If the mutant is supposed to age a year, then she'll only age 3 months.
A paralysis effect would have one-quarter of the duration and one-quarter of the paralysis.
This mutant heals 4 times as fast and can extend a pharmaceutical's effect be 4 times.
These benefits are attributed to respiration control, blood re-routing, hormonal adjustments and alterations in enzyme production.

A mutant with mental control over physical state is unaffected by infections or cancers.
The more dangerous an effect the body is fighting, the more the mutant is required to concentrate.

This mutation is a mental one, but it does not affect psionic attacks.
For example, this mutation does not decrease mental control duration, but it would reduce the damage from a mental blast.


=== Mental Defenselessness

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Combat Ratio *0.5

This mutant's consciousness is entirely open to the thinkspace. 
The defect renders the mutant mentally defenceless.
A mutant with this serious defect will usually have a long history of impulsive purchases, personal dependencies, and cult affiliations.
Mental defenselessness does not mean the mutant is lacking intelligence, bravery or emotional weakness.

The mutant's mental strength is not zero.
The mutant still has a mental strength for her other mental mutations, vocations, or will power checks.
However, when she is subject to a psionic attack, her effective MSTR is zero.

include::ROOT:partial$Defect_Disclaimer.adoc[]

=== Molecular Disruption 

[horizontal]
Range:: 1h per adjusted MSTR
Duration:: Permanent
Frequency:: Special
General Bonus:: Combat Ratio *3

This mutant can convert matter into a low energy gaseous state.
Molecular disruption allows the mutant to obliterate solid objects by converting them into a cold cloud of gas.
The mutant need only concentrate on the target to disrupt it at a molecular level.
The target can be a persona or an inanimate object. 
Inanimate objects have an MSTR of 0-9 (1d10-1) or the same MSTR of the persona holding it.
If the target wins a psionic roll, the disruption has no effect.

A mutant can disrupt up to 1 kilogram of wate per 2 kg of the mutant's wate.
An 80 kg mutant can disrupt up to 40 kg of matter.
If the mutant wants to disrupt less than the maximum amount of wate, she must win a psionic roll against herself.
If the mutant wins the psionic roll, she can choose the number of kilograms disrupted.
Immediately after molecular disruption, the mutant collapses and will be unconscious for 1 minute per kilogram disrupted.
If the mutant disrupts 15 kgs of a target, she will be unconscious for 15 minutes. 
The player must consider the safety of her persona post molecular disruption.

Molecular disruption is diffuse and impossible to focus on a particular part of the target.
The target takes 1d20 hit points in damage per kilogram disrupted. 
The amount of damage is the same if the target is an inanimate object or a persona. 
If the wate of the disrupted matter is greater than the wate of the target, the target is irrevocably destroyed.

The molecular disruption is silent and has no extraneous effect. 
The gas is cold and does not create pressure.


=== Molecular Examination 

[horizontal]
Range:: 3h per adjusted MSTR
Duration:: Not Applicable
Frequency:: As Needed
General Bonus:: Combat Ratio +5, +10 on all examination rolls

Molecular examination allows the mutant to determine the strengths and weaknesses in a structure.
The target is instantly analyzed to determine it's weakest point.
The mutant must observe the subject personally and be within range.

Thus molecular examination used against a building in a photograph would determine the weakness in the photograph (not the building), and molecular examination used on someone over a televid would find a weakness in the televid (not the persona).
If the subject appears to have no weaknesses, it may only have no structural, or tactical, weakness from that angle, and a change in view might change this opinion.
Thus the mutant must use molecular examination on a unit by unit basis.

All objects being examined will get a save vs psionic attack to see if they relinquish their weakness.
Buildings and other inorganic objects have a random MSTR between 0 and 9.
Military buildings, and such, may have a higher MSTR due to their defensive nature.
If the target fails its saving throw then the mutant will gain combat bonuses that represent this extra information.

If the mutant walks up to a solid rock and determines its weakness, she would increase her chances of fracturing it, rolling it, or balancing it.
The benefits are + 10 times AWE added to attack rolls, and + AWE to PT rolls.


A mutant with molecular examination, and a 14 AWE is in combat with a particularly well armoured alien.
Using molecular examination the mutant is trying to find a weakness in the alien's thick, scaly hide.
The alien fails her save and the mutant can add 140 to her attack roll, greatly increasing her chances to hit.
However the next unit the alien makes its saving throw, and the mutant gets no bonus other than her regular attack roll bonus.
If the mutant were a biologist and were trying to make an identification on the alien she would automatically add 10 to her PT roll.
If the alien failed her saving throw again, the mutant biologist would get to add her AWE to the PT roll also, for a total PT roll bonus of 24.

=== Molecular Phase Transformation 

[horizontal]
Range:: Persona Only
Duration:: 30u per Adjusted MSTR
Frequency:: 1 per 4 Adjusted MSTR
General Bonus:: Combat Ratio +2

Molecular phase transformation allows the mutant to convert her body into a homogeneous solid, liquid or gas.
The incredibly diverse molecular structure of the body instantly transforms into whichever phase the mutant chooses.
This means that her bones, muscles, blood, skin, etc., transforms into a cohesive solid, liquid or gas. 
While transformed into the chosen phase, the mutant maintains her consciousness and is fully aware of her surroundings.
Each of the phases offers benefits and limitations.

When transformed, the mutant cannot carry or manipulate any of her equipment.
None of her equipment is transformed, and the mutant can no longer interact with it. 
Clothes would be hanging off a solid statue, floating in a puddle or falling in a cloud of gas.
Purely mental mutations can be used while phase transformed. 
Physical mutations no longer function as they are now solid, liquid or gaseous.
Those mental mutations that manipulate the physical space cannot function when phased. 

The mutant can return back to her diverse molecular structure anytime.
Converting back into her diverse molecular states takes about 1-4 (1d4) units.

*Solid Phase*::
The mutant transforms into a homogenous rock-like statue of herself.
Her wate and volume remain the same.
She is impervious to most attacks poison, radiation, exatmo etc.
Processes like bleeding and burning are immediately stopped. 

The mutant is vulnerable to being hammered, chiselled and smashed. 
Projectiles don't harm the mutant in the solid-state. 
Attackers can shoot the solid mutant all they want.
Only if an attacker employs cutting tools is the mutant in danger.
If an attacker somehow manages to cut off a chunk, the mutant will take damage when she reforms.
The mutant loses 1d20 hit points per kilogram lost.
If the mutant statue is sawed into pieces, they would be assumed to end up in pieces. 

*Liquid Phase*::
The mutant's body will pour out of her present form into a cohesive puddle on the floor.
The mutant's wate and volume remain the same while in the liquid phase.
The liquid state of the mutant is very cohesive.
The mutant does not have to worry about mixing with other liquids or being washed away.

While transformed into a liquid, the mutant can ooze along at 1/2 her land movement rate. 
If the mutant had a movement rate of 4h/u, she could ooze along at 2h/u.
The liquid mutant can squeeze through cracks, under doors, along walls and cling to ceilings. 

Attacks that use kinetic energy have no effect on the liquid mutant.
Stabbing, clubbing, shooting, puncturing or biting are equally ineffective. 
Being liquid offers no protection from exatmo exposure. 
Heat and electricity-based attacks can injure the liquefied mutant, but they do so at half damage. 
If an active discussion erupts the players can consult the xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice,window=_blank].

Any attacker trying to separate the liquid mutant with buckets must overcome the mutant's fluid pressure (PSTR).
If an attacker somehow manages to split off some of the liquid mutant, she will damage when she reforms.
Typically 1 litre of mutant equals 1kg of her body.
The mutant loses 1d20 hit points per kilogram lost.

The mutant can generate a fluid pressure equal to her PSTR.
The liquid pressure could be used to push open a door or move a box along the ground.
However, the mutant cannot organize this pressure to turn a door handle or pull a trigger.
The pressure could be used to depress a mechanical button. 
If an active discussion erupts the players can consult the xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice,window=_blank].

A liquid mutant can drown a defenseless target faster than regular water. 

*Gas*:: 
The mutant's body transforms into a cloud of gas, and all her clothes and equipment fall to the ground.
In the gaseous phase, the mutant's wate remains the same, while her volume doubles.
The gaseous state of the mutant is very cohesive.
The mutant does not have to worry about mixing with other gases or being blown away.
The gaseous mutant is not invisible and appears like a cloud.

While transformed into gas, the mutant can float along at her land movement rate. 
If the mutant had a movement rate of 4h/u, she could float along at 4h/u in any direction.
The gaseous mutant can squeeze through cracks, under doors, or float in the center of the room. 
In the gaseous state, the mutant can take advantage of prevailing winds to move even faster.

Exposing the gaseous mutant to exatmo has the expected killing effects.
Low or high-velocity kinetic attacks are ineffective against the gaseous mutant.
Bullets, arrows, clubs, beaks, fists cannot damage a gaseous mutant.
Lazer, fission, and fusion attacks inflict typical damage. 

Any attacker trying to separate the gaseous mutant must overcome the mutant's vapour pressure (PSTR).
If an attacker somehow manages to split off some of the gaseous mutant, she is damaged when she reforms.
Typically 1 litre of mutant gas equals 1kg of her body.
The mutant loses 1d20 hit points per kilogram lost.

When in the gaseous phase, the mutant can generate a vapour pressure equal to her PSTR.
The gaseous pressure could be used to pop open an unsealed box or push a box along the floor.
This pressure cannot be used to push a button or pull a trigger.

The gaseous mutant can suffocate a slow-moving or defenceless target. 
The mutant can envelop the target in an oxygen-free cloud of herself. 
The horrendous specifics of suffocation are covered under xref:i-roll_playing_rules:CH19_Terrain.adoc#_atmosphere[Terrain,window=_blank].

=== Molecular Phase Transmutation 

[horizontal]
Range:: 1h per Adjusted MSTR
Duration:: Special
Frequency:: 1 per 4 Adjusted MSTR
General Bonus:: Combat Ratio *3, +25 on materiel rolls

Molecular phase transmutation allows the mutant to change targets into a solid, liquid or gas.
Molecular phase transmutation cannot be used by the mutant to transmute herself.
The mutation can only be used on targets other than the mutant.
Transmutation is effective against inanimate objects, organic and inorganic personas.
The mutation is most often used as an attack, but voluntary targets are also possible.
If the target wins a psionic roll, she is unaffected by the molecular phase transmutation.
Inanimate targets have an MSTR of 0-9 (1d10-1), or the MSTR of the persona holding the object.

The mutant can transmute half her wate in materials each use.
This means that a 70kg mutant could transmute 35kg of matter.
If the mutant wants to transmute less than half her wate, she must win a psionic roll against herself.
Otherwise, she will transmute exactly half her wate.
If she wins the psionic roll against herself, she can choose how many kilograms she transmutes.

Depending on the amount of matter transmuted, the target will be partially or totally transmuted.
Partial transmutation is an attack that will most likely prove lethal to the target. 
Total transmutation is not lethal but incapacitates the target.

.*Partial Transmutation*
Partially transmuting a target into either a solid, liquid, or gas has equally harmful effects.
A random chunk of the target is violently transmuted into a homogenous rock, puddle or cloud.
Every kilogram of the target transmuted inflicts damage on the target. 
For each kilogram transmuted, the target takes 1d8 hit points in damage.
There is no difference in damage between the three phases. 
If a target loses 12kgs of wate to transmutation, she will lose 12d8 hit points. 
The target must lose a psionic roll before undergoing partial transmutation.

There is a 1% chance the target will undergo total transmutation for every hit point of damage inflicted.
If the target takes 58 hit points in damage, there is a 58% chance it will totally transmute.
If the target totally transmutes, they will not take any damage.

.*Total Transmutation*
Total transmutation indicates that the entire target has transmuted into either a solid, liquid or gas.
The target is wholly transmuted and incapacitated in this state. 
The target turns into a statue, a puddle or a cloud. 
Unlike <<_molecular_phase_transformation,Molecular Phase Transformation>>, the target cannot function when transmuted.
The target's equipment will tumble to the floor or hang off a perfect statue. 

Total transformation does not damage the target.
After 1-1000 units, the target will return to it's complicated state unharmed.
They may have floated away on the wind or dripped into a sewer, but they will reform unharmed. 
A more detailed read on total transmutation is available <<_molecular_phase_transformation,here>>.

A target will totally transmute if it has a wate less than half the mutant's wate.
If the mutant has a wate of 70kg, she will transform 35kg.
Any target 35kg or less will totally transmute if they fail a psionic roll.

A partially transmuted target has a chance to convert to total transmutation.
The more damage inflicted, the more likely the target will convert to total transmutation and avoid injury.

//table dropped in version 6.0

:art: muscle_manipulation_otters.png
:width: 250px
:snark: Why I otter...
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of two humanoid otters where one is making the other punch himself in the snout.

include::ROOT:partial$articulate.adoc[]

=== Muscle Manipulation 

[horizontal]
Range:: 4h per Adjusted MSTR
Duration::  Special
Frequency:: 1 per 4 Adjusted MSTR
General Bonus:: Combat Ratio *6, + on vet rolls

Muscle manipulation allows the mutant to control a muscle group and its associated motor nerves.
This mutation can be used on any organic persona that uses limbs for leverage.
Organic personas include aliens and anthros.
This mutation has no effect on robots or inanimate machines. 
Muscle manipulation is divided into peripheral and central muscles.
Peripheral muscles carry out are voluntary actions like walking or juggling. 
Central muscles carry out involuntary actions like breathing and heart rate. 

.*Peripheral Muscles*
Peripheral muscles carry out are voluntary actions like walking or juggling. 
Peripheral muscles typically are found on the limbs and face of a target.
The mutant does not have to identify the specific muscles and nerves of the target's anatomy.
The mutant need only describe what she wants to happen.
For example: close the eyes, one leg to trip another, make a wing stop working, force a fin to flag about limply, push an undesired button, pull a trigger too soon, not throw a grenade, or change target.

Subtle muscle manipulations do not get a psionic roll and are automatically successful. 
For example, dropping a piece of paper or turning a doorknob the wrong way would automatically succeed.
Dangerous muscle manipulations require the target to lose a psionic roll to work.
For example, changing targets or dropping a grenade at her feet.

.*Central Muscles*
Central muscles carry out involuntary actions like breathing and heart rate.
Central muscles carry out essential life, maintaining actions like breathing or pumping fluids.
For example: stop the heart, speed up the heart, stop breathing, drop blood pressure, increase blood pressure.
Muscle manipulations like stopping the heart, breathing, and inducing cardiovascular collapse are lethal.
The target must win a psionic roll or die from the attack. 

Both central and peripheral muscle manipulations can be carried on dying or recently dead personas.
For example, a recently dead persona could posthumously raise its offensive middle talon. 
The mutant could keep the heart of a dead persona beating with muscle manipulation.


// table dropped in version 6.0


=== Neuronegation 

[horizontal]
Range:: 2h per Adjusted MSTR
Duration:: 1-6 (1d6) minutes
Frequency:: 1 per 4 Adjusted MSTR
General Bonus:: Combat Ratio *3, +40 for anaesthesia Rolls

Neuronegation cuts the target off from all sensory input.
The attack puts the target into a sensory anesthetic state., 
All six senses are shut down: vision, hearing, touch, smell, taste, and psionic.
The target's consciousness is totally cut off from both the physical and think space.
The target must win a psionic roll or collapse into a blankly staring husk.

Whether the target is conscious or not is up to the referee.
Psionic attacks cannot be used by, or used on, a target suffering neuronegation.
The target is cut off from the think space in both directions. 

=== Phase 

[horizontal]
Range:: Persona Only
Duration:: 1u or less
Frequency:: 1 per 3 Adjusted MSTR
General Bonus:: Combat Ratio *5

Phase allows the mutant to momentarily drop out of the physical space leaving only a ghostly after image.
Her body rapidly flickers between the hyper and think space, while her consciousness remains in the physical space. 
This is the explanation supplied by EXP's generic sciency fiction mythos.

The mutant can take a small amount of her equipment along for the ride.
The amount of equipment is limited to her clothing and a few artifacts.
From a ruling standpoint, she must be unencumbered for the phase mutation to work correctly.

Phase works automatically and lasts as long as the mutant desires for up to 1 unit (2 seconds).
The mutant can move during this time but cannot engage in any other actions in the physical space.
While phasing, the mutant cannot use any other mental mutations. 

The phase mutation is used to move through obstructions on the physical plane.
The mutant can pass through walls up to a distance of up to her movement rate. 
When phased the mutant's movement rate is doubled for that one unit.
A mutant with a movement rate of 4 h/u could pass through 8 hexes (16 meters) of obstructions.
The mutant can move downwards into the land or water. 
This mutation cannot be used to fly. 

Phase would not allow a mutant to materialize within a solid object, even if this was the mutant's goal.
Self-preservation prevents the mutant from rematerializing within a solid structure.
It does not protect the mutant from phasing into a dangerous non-solid location.
For example, the mutant cannot get trapped inside a mountain. 
Still, she could rematerialize in water, a vacuum or outside a moving vehicle.
Phase cannot be used to travel through mountain ranges.
Phase could be used to probe a mountain range for caves.

Phase prevents a mutant from materializing at lethal velocities.
If the mutant phases out of a moving vehicle, she will hit the ground, moving her maximum move rate.
If the mutant phases onto a fast-moving vehicle, she will hit the deck, moving at her maximum move rate.

While phased, the mutant is impervious to damage on the physical plane.
When phased, damage simply passes through the mutant.
She can avoid bullets, area of effect weapons, poison gas, fall damage and radiation.  
Phase is a profoundly effective defensive mutation. 
Phase does not protect the mutant from purely psionic mental mutation attacks.

:art: planal_hideaway_bomb_slug.png
:width: 250px
:snark: I am getting into out of here
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a humanoid slug escaping a nuclear device by jumping through a door in space and time.

include::ROOT:partial$articulate.adoc[]



=== Planal Hideaway 

[horizontal]
Range:: Special
Duration:: As Needed
Frequency:: 1 per 20 Adjusted MSTR
General Bonus:: None

A planal hideaway is a convenient time-space aberration that is generated and manipulated by the mutant.
This mutation is used to create an entrance into a room located beyond physical space.
The hideaway can store both personas and stuff. 
This mutation is most often used by the mutant to hide from threats or to hide artifacts.
Hence the name planal hideaway.


.*Getting In*
A planal hideaway entrance is a stationary, 1 dimensional, black void parallel to the most robust local gravitational field (planet, star, or spaceship).
If the hideaway is opened in total darkness, the entrance will always appear darker than the surroundings.
The entrance only has one side, and personas simply walk into the dark cube-shaped room through the opening. 
Anything that can fit in the 2m cube room can fit through the entrance. 
Once the mutant closes the entrance, there is no trace left in the physical space. 
A mutant can always find and open her own planal hideaways.


.*Being In*
The planal hideaway is excised from time and space itself.
Anything inside the cube will remain in stasis and be utterly unaffected by time or any occurrence in the nearby physical space.
Organic creatures can exist inside a planal hideaway without food or water indefinitely.
Personas will not heal, nor will they deteriorate while locked into the planal hideaway.

The planal hideaway is a 2m cube. 
There is no wate restriction for the hideaway, but there are volume restrictions.
The longest item that can be fit in the cube can be determined https://www.wikihow.com/Find-the-Longest-Internal-Diagonal-of-a-Cube[here].
The volume of a cube can be determined https://simple.wikipedia.org/wiki/Cube[here].
Usually, there will be enough space in the hideaway for an expedition, and it's equipment.
The greedy filling of a hideaway can be limited by time pressure imposed by combat or story.

For equipment, the planal hideaway experience is the same as any other box.
For personas, the planal hideaway experience is a peculiar one.
The cube walls cannot be readily perceived, and the room appears to be completely dark.
Despite this sense of darkness, personas can see everything inside the hideaway. 
The walls do not reflect sound, and noises sound muffled and distant.
Despite this, personas can easily hear each other speak and complain.
There is no sense of time within the hideaway. 
Timepieces, timekeeping abilities, or timekeeping mutations are at a standstill. 
The personas have no sense of time passing within the hideaway.
This loss of time perception is a consequence of time having no effect within the planal hideaway.
A 10 second, 10 year or 10000 year passage of time in physical space feels the same inside a hideaway.

.*Getting Out*
When the planal hideaway is opened, its contents unceremoniously drop to the ground.
All items and persons fall 1 hex onto the nearest solid surface.
Only in extreme circumstances will items and personas be damaged by the drop.
The hideaway will not kill its creator on opening.
The planal hideaway will not reopen into certain death.
The hideaway will not open onto the surface of a sun, underwater or into a vacuum.

The mutant must be present to open a planal hideaway. 
She does not need to be inside of it.
A mutant can always find and open her own planal hideaways.

All planal hideaways open if the mutant dies. 
A planal hideaway can last indefinitely if the mutant is in it.

.*Other Stuff*
The mutant can have multiple planal hideaways hidden across the galaxy. 
She must be personally present to open and close each one.
The mutant cannot have two planal hideaways open simultaneously. 

A planal hideaway cannot be opened around a previous planal hideaway. 
Opening a planal hideaway within a planal hideaway is up to the referee. 
The process can be refused outright or be accompanied by in-game challenges.
Past in-game challenges have included releasing alien creatures that eat time. 

NOTE:: The mutant can always find and open her planal hideaways.

Intentionally using the planal hideaway to damage a story arch is to be frowned upon. 
Using the planal hideaway to hide from a story challenge is acceptable.
However, intending to stay in the hideaway for 20 million years is cheeky.
Personas have no concept of time in the hideaway.
The referee can justify reopening the hideaway in a time that keeps the mutant in the storyline. 
The referee can justify reopening the hideaway when it puts the mutant in a completely different storyline. 
The planal hideaway is meant to be convenient and fun. 

Combat within the planal hideaway tends to happen with younger players. 
Sometimes enemies jump into the hideaway at the last millisecond; other times, personas get bored.
How would combat work in an environment outside of time and physical space?
No powered weapons work. 
No explosions happen. 
The personas would be limited to hand to hand combat where no one can die.
If a persona activated a grenade, it would not detonate in the planal hideaway.
The grenade would detonate the moment the hideaway opens. 

=== Planal Holdaway 

[horizontal]
Range:: Special
Duration:: Until Dead
Frequency:: As Needed
General Bonus:: None

The planal holdaway is a convenient time-space aberration that follows the mutant around.
The holdaway is essentially an extra-dimensional backpack.
When the mutant opens her holdaway, a 1-dimensional circle of varying diameter opens. 
The opening is darker than darkness, and the mutant can drop anything she likes into it.
When an artifact is dropped into the opening, it disappears beyond time and the physical space. 
The opening is always within reach of the mutant, but she cannot climb into it herself.
The mutant can open the holdaway at any time, reach into it and remove what she wants. 
If a persona other than the mutant reaches into the darkness, they will pull out a random item.
 
The holdaway can store double the mutant's wate allowance. 
The player uses the PSTR wate allowance table but substitutes her persona's PSTR with her MSTR. 
The mutant can store 1 item equal to her wate allowance inside the holdaway or many things that add up to less than her wate allowance. 
The holdaway is beyond time and physical space.
All items are held in stasis and do not age, deteriorate or heal. 
This mutation is the perfect psionic refrigerator.

The holdaway will involuntarily open if the mutant dies or is unconscious and dying.
The items fall 1 hex to the ground in a clattering mess.

:art: magnetic_control_minivan.png
:width: 250px
:snark: Chasing a moving car
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid fish being magnetically dragged away by a minivan.

include::ROOT:partial$articulate.adoc[]

=== Polar Disruption 

[horizontal]
Range:: 1h per 20kg Wate
Duration:: 1-6 (1d6) Units
Frequency:: Random
General Bonus:: Defect, +10 on magnetism rolls

Polar disruption will randomly and unexpectedly turn the mutant into a super magnet.
When under extreme duress, there is a chance that polar disruption will be activated.
The following are extreme duress examples: losing hit points, being surprised, vehicular misadventure, combat, or just because.
Whenever such stressful situations occur, there is a 3% chance that the mutant will have an attack.

All metallic objects within the range are affected by the polar disruption.
Objects less than half the mutant's wate will be affected.
A 60kg mutant will affect all objects <30kg within 3 hexes.
All loose metallic items will automatically be affected.
Artifacts on a persona must win a psionic roll or be affected by the polar disruption.
If a large metallic object is nearby, the mutant may be affected by that object.

If an active discussion arises regarding whether, or not, something is metallic consult the xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice,window=_blank]

The attack lasts 1-6 (1d6) units, and metallic items that are not moving need to check again.
Suppose a nearby persona manages to hang onto her sword in the first unit of the attack. 
In that case, she must recheck each attack unit.

Typically polar disruption attracts items towards the mutant. 
If the mutant requests, there is a 50% chance the attack will be a repulsive polar disruption.
In an attracting polar disruption, items immediately fly at the mutant and gently settle against her.
In a repulsing polar disruption, items fly away from the mutant and land outside the range of attack.
Neither the mutant nor the items are damaged when things start flying around. 


include::ROOT:partial$Defect_Disclaimer.adoc[]


=== Power Drain 

[horizontal]
Range:: Touch
Duration:: Permanent
Frequency:: 1 per 4 Adjusted MSTR
General Bonus:: Combat Ratio +4, +10 on battery rolls

Power drain allows the mutant to heal by draining potential energy from batteries.
Any battery the mutant touches with her bare skin will be completely drained.
She will restore 1-10 (1d10) hit points per battery she drains.
Once she is at full health (HPS Max), the mutant still drains the batteries, but she does not heal.
This mutant must wear gloves when handling batteries, or they will be drained.
She must protect battery-powered artifacts from her touch as well.
Power drain only works for healing if the battery is touch directly.
So the mutant will drain batteries in artifacts but will not heal herself.

A battery can only defend itself if it is being held by another persona. 
The persona holding the battery must lose a psionic roll before the battery is drained.
If the mutant has the device in her own hands, no psionic roll is granted. 

Power drain does not work on power cells (robots), fuel cells (vehicles), power generators, broadcast cells or psionic cells. 

If the mutant wishes, she has a 50% chance of being able to reverse this mutation.
She can completely recharge a battery by sacrificing 1-12 (1d12) hit points.  

=== Precognition 

[horizontal]
Range:: 3h per Adjusted MSTR
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Combat Ratio +3, Impossible to Ambush

This mutant is psionically alerted to hostility or impending danger.
If the mutant is asleep, the sensation of danger will awaken her.
A mutant can detect danger anywhere from days to seconds before it occurs.
Precognition gives the mutant a nebulous warning and not a detailed explanation.
Precognition requires the threatening situation to be within the range of the mutation.
Precognition is a selfish mutation; it only activates on dangers that personally affect the mutant.
If the mutant is about to bite into a poisoned jelly donut, then precognition will keep her mouth closed.
If a persona is about to shoot her, she will feel an urge to jump or move.
The donut will remain poisoned, and the sniper will still make an attack roll.
This mutant will probably act a little bit more paranoid than usual.

=== Projected Sense 

[horizontal]
Range:: 5h per Adjusted MSTR
Duration:: 1 per Adjusted MSTR
Frequency:: 1 per 3 Adjusted MSTR
General Bonus:: None

The six basic senses of this mutant can be ethereally projected beyond the mutant's body.
The senses projected are hearing, sight, smell, taste, touch and the sixth sense.
So this mutant could project her sight into a locked room and search it.
She could project her sixth sense and activate a mental mutation from that location.
The projected senses can only observe.
They cannot manipulate objects while being projected.

While a sense is projected, the mutant can still use her local senses to their full capacity.
So this mutant could have two sets of eyes watching.
This could offer the player two awareness rolls when her persona is searching an area.

Sight, hearing and sixth sense are still subject to damaging effects while in the projected form.
A flash, boom or mental attack could respectively injure the mutant's sight, hearing or consciousness.
To project more than one sense at a time requires multiple uses of the mutation.


=== Protection Shell 

[horizontal]
Range:: 1h per EXPS Level
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Combat Ratio +2

This mutant has a repulsion shell that wards off selected persona types.
To remain within the radius of effect the persona must win a psionic roll.
This roll must be won by fellow expedition members and attacking aliens as well.
The protective shell does not make the  is not 

include::ROOT:partial$CH58_Table_Protective_Shell.adoc[]

=== Psionic Defence 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Combat Ratio *2

This mutant has a hardened consciousness against all manner of psionic attack.
Psionic defence protects the mutant from mental attacks that work within the thinkspace.
For example, mental control, muscle manipulation directly attack the mutant.
Psionic defence does not protect against those mental attacks that alter the physical world.
A mutant with psionic defence would increase her MSTR against pyrokinesis, but not against a mental blast.

At any point, the player is making a defensive psionic roll, her MSTR is doubled. 
The minimum MSTR this mutant can have against psionic attack is 16.
So a mutant with a 10 MSTR would have a 20 MSTR when fighting a psionic attack.
A mutant with a 4 MSTR would have a 16 MSTR when fighting a psionic attack. 
The mutant's mental strength is not doubled when attacking with mental mutations.
This mutation defends against benevolent intrusion into the mutant's consciousness.

=== Purify 

[horizontal]
Range:: Touch
Duration:: Permanent
Frequency:: 1 per 3 Adjusted MSTR
General Bonus:: +42 on cleansing rolls

This mutation allows the mutant to purify substances by touching them with her bare skin.
The purification process will destroy any infectious organisms or toxic contaminants.
Picking up a piece of meat would eject toxins and neutralize any bacteria or viruses living, making the meat safe to eat.
The same could be done for contaminated water, plastic, or lumps of gold.
The amount of substance purified cannot exceed 10% of the mutant's body WATE, and the mutant must touch the substance for 1-4 units.
This procedure will result in a 100% pure sample (which is immediately subject to recontamination).

Purify does not separate alloys or decompose composite materials.
This mutation makes materials safe to be consumed or held by the mutant.

=== Pyrokinesis 

[horizontal]
Range:: 2h per Adjusted MSTR
Duration:: 5u per Adjusted MSTR
Frequency:: 1 per 2 Adjusted MSTR
General Bonus:: Combat Ratio +5

Pyrokinesis allows the mutant to make things around her very warm.
This mutation may be employed in a nasty way or a benevolent way.

The nasty pyrokinesis is a mental attack.
The pyrokinesis attack heats the target's consciousness with a deadly warmth.
The mental attack starts with a fever and eventually creates a flaming effigy.
The target automatically takes 1-4 (1d4) hit points of damage in the first unit.
After the first unit, the target can repel the attack by winning a psionic roll.
The amount of damage inflicted increases by 1-4 (1d4) each unit the mutant attacks.

For example, the target takes 1d4 damage in the first unit.
If the target fails her next three psionic rolls, she will take more damage each combat unit.
Failing 3 rolls would result in 2d4 in the second unit, 3d4 in the third unit, and 4d4 in the fourth unit.
The target will either break the heating attack or die.
When a target is killed by this attack, it is left a charred smoking husk.
If the pyrokinesis cycle restarts, the damage per unit restarts at 1d4. 
A mutant with a 10 MSTR could inflict up to 50d4 in damage in the last unit.

The benevolent pyrokinesis acts like a psychic space heater.
This warming only works on organic consciousnesses and cannot overheat a machine or robot.
The mutant can comfortably warm organic personas in a four hex radius.

=== Repulsion Field Generation 

[horizontal]
Range:: 1h per EXPS Level
Duration:: 1u per Adjusted MSTR
Frequency:: 1 per 6 Adjusted MSTR
General Bonus:: Combat Ratio *4

Repulsion field generation allows the mutant to nearby personas to become nauseous and ill.
The repulsion field works on all organic personas, including anthros and aliens.
Robots are not affected by a repulsion field.
Each persona in the area of effect must make a psionic roll.
Those who lose the psionic roll become violently ill and are incapacitated.
Those who win the psionic roll are still severely violently ill and are partially incapacitated.
Partially incapacitated includes: -500 on attack rolls, half movement rate (no sprinting or bolting), +10 DD on all maneuver rolls, and halved attributes for attribute rolls.
These effects immediately stop when the persona is out of the area of effect.

The repulsion field is a useful mutation for immobilizing everything within the area of effect.
However, the repulsion field is not a discerning mutation, and every organic persona within range is affected.
Both friends and foes get hit with the repulsion field.
With experience, the mutant can exclude specific personas from being affected by the field. 
The mutant can protect one target per 2 EXPS levels from being attacked.
A 4th level mutant could keep 2 of her expedition members from being affected by the repulsion field.

=== Restoration 

[horizontal]
Range:: Touch
Duration:: Permanent
Frequency:: 1 per 3 Adjusted MSTR
General Bonus:: Combat Ratio +12, +25 on healing rolls

Restoration allows the mutant to heal damaged organic creatures by merely touching them with her bare skin.
If no skin is readily exposed, the mutant must win an attack roll against the target.
The attack roll is required even if the target is voluntary. 
For example, during combat, a persona will readily remove their armour.

Restoration heals an amount of HPS equal to the mutant's hit points total.
A mutant with 13 hit points total can restore 13 hit points to another by a mere touch.
It is in the expedition's interest to keep this mutant healthy.
Restoration only restores hit points and does not cure diseases or regrow missing limbs. 
The mutant cannot reverse to inflict damage.

=== Seizure Projection 

[horizontal]
Range:: 1h per Adjusted MSTR
Duration:: Up to 5u
Frequency:: 1 per 4 Adjusted MSTR 
General Bonus:: Combat Ratio +4

Seizure projection allows the mutant to induce random muscle contractions in a specific target.
The initial muscle contractions are subtle and become progressively worse.
Eventually, the target becomes incapacitated with a full-body seizure (grand mal).

The first unit of this mental attack automatically affects the target.
The lack of coordination and spasms delivers the following penalties: movement drop of 25%, -50 on attacks, and -1 on anything else.
Each time the target loses her psionic roll, the neuromuscular dysfunction increases.
The movement and attack roll penalties increase by 25% and -50 for each failed psionic roll.
By the 3rd failed psionic roll, the target can no longer move and has -200 on her attack roll.

If the target loses her psionic roll again, the target falls into a full-body seizure and goes unconscious.
This seizure will last 1-4 (1d4) minutes and require further recovery once completed.
The mutant can re-attack the target with seizure projection immediately. 

.*Example Seizure Projection Attack*
. No psionic roll offered. Move -25%. -50 Attack roll. -1 all else. 
. Psionic roll at -1. Move -50%. -100 Attack roll. -2 all else.
. Psionic roll at -2. Move -75%. -150 Attack roll. -3 all else.
. Psionic roll at -3. Move None. -200 Attack roll. -4 all else.
. Psionic roll at -4. Total body seizure and unconsciousness.

=== Sensory Deprivation 

[horizontal]
Range:: 1h per Adjusted MSTR
Duration:: 1u per 4 Adjusted MSTR
Frequency:: 1 per 8 Adjusted MSTR
General Bonus:: Combat Ratio +6, +10 on vet rolls

Sensory deprivation allows the mutant to disrupt any of the target's senses.
The attack is only effective against organic personas.
The target must win a psionic roll or lose the chosen sensory input.
Sensory deprivation is selective, and the target remains conscious and likely surprised.
The mutant can cause deafness, blindness, or a loss of tactile and olfactory senses.
The more critical the sensation, the more likely the target will win the psionic roll. 
Removing the sensation of pain can benefit the target in certain circumstances. 

include::ROOT:partial$CH58_Table_Sensory_Deprivation_Effect.adoc[]

:art: sociability_field_cop_cat.png
:width: 250px
:snark: We like you muchly
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of two humans in police armour visibly smitten by woman in sunglasses.

include::ROOT:partial$articulate.adoc[]


=== Sociability Field Generation 

[horizontal]
Range:: 1/2h per EXPS Level
Duration:: Until Dead
Frequency:: Constant
General Bonus:: +20 on negotiations, +42 on charisma rolls

This mutant generates an aura of good humour and friendship around her.
The personas will not fall in love, but they will be unusually friendly towards the mutant.
There is no psionic roll granted to prevent the sociability field effect.
The field is *not* a reality denial field. 
Sociability field generation is not the same as mind control. 
The mutation will not overcome the instincts of a hungry or enraged alien, nor can it be used to pressure personas to place their lives at risk or carry out materially, socially, or personally suicidal acts.
This mutation does not work on robots. 
Sociability field generation does not work over communication devices.

While there is no psionic roll given, not all personas are affected by the field. 
Personas with low intelligence (INT <3) are unaffected by the field.
Personas with very high intelligence (INT>17) or mental strength (MSTR>15) are unaffected by the sociability field.

The mutant may have no idea that she has this mutation. 
She will feel that people are friendly, and she assumes that most people are kind. 
If the campaign uses the attribute social standing, this mutant cannot have an SS less than 900.

=== Sonar 

[horizontal]
Range:: 20h per Adjusted MSTR
Duration:: Until Dead
Frequency:: As Needed
General Bonus:: Triple AWE in search or ambush

This mutation gives the mutant sonar sight.
Sonar sight operates on the acoustic reflection of various frequencies emitted from the mutant's consciousness.
The sonar allows the mutant to detect solid objects in a 360 radius.
Sonar is not a physical mutation, and there is no anatomic change that is detectable on the mutant. 

Sonar allows the mutant to navigate in the dark, determine if holograms are solid or not, and she can see through smoke and water.
Holograms and other projections are invisible to sonar.
The mutant can use this info to detect holograms or other trickery.
Images created directly in the mutant's consciousness would be real to the mutant.
Sonar quickly detects invisible or camouflaged targets.

Sonar and regular sight are interchangeable; however, they are not equivalent in function.
Sonar sight does not give sufficient detail, and the mutant sonar may mistake a combat robot for a hovercar.
The sonar does not differentiate friend or foe as both appear as blips in her 360 sonar field.
Sonar may not be able to function through some helmets.

Sonic attacks on the mutant do double damage and disable her sonar for 1 to 4 days.

=== Sonic Attack 

[horizontal]
Range:: 1h per 2 Adjusted MSTR
Duration:: Speed of Sound
Frequency:: 1 per 4 Adjusted MSTR
General Bonus:: Combat Ratio +3

This mutant can release a deadly burst of sonic energy.
The attack is a psionically adjusted version of the mutant's speech.
Words become a sphere of damaging ultra-high and ultra-low frequencies. 
Sonic attack damages all objects within the radius of effect.
This mutation damages both organic and inorganic audio sensors.
Targets do not get a psionic roll versus this attack.
The amount of damage delivered depends on how far the target is from the mutant.

include::ROOT:partial$CH59_Table_Sonic_Attack_Volume.adoc[]

.*6h Range Example*
* 0h to 1h = 4-32
* 1h to 3h = 3-24
* 3h to 6h = 2-24
* 6h to 7h = 1-8

Targets with enhanced audio sensors, such as sonar, take double damage.

Severe damage can deafen the audio sensors.
There is a 1% chance per point of damage of being deafened by each sonic attack.
The chance of audio sensor damage is not cumulative.
Each new attack calculates a unique percent chance of damage.
The organic audio sensors of anthros and aliens will recover in 1-8 (1d8) hours.
Inorganic audio sensors remain broken until repaired.
Sonic attacks still inflict damage if the target is deafened.

The mutant is unaffected by her sonic attack.

=== Sonic Reproduction 

[horizontal]
Range:: Within Hearing
Duration:: 2u per Adjusted MSTR
Frequency:: As Needed
General Bonus:: Combat Ratio +1, +10 vocal shenanigans

This mutation turns the mutant into a walking digital recorder.
Perfect reproduction quality can be recorded and recreated for any audible sound.
Sounds can be memorized and replayed at a later date.
If the player wins an intelligence roll the mutant can replay an edited, or remixed, copy of the sound.
The more difficult the sound the more difficult it is to memorize.

Each reproduction can last up to two units per point of adjusted MSTR.
A 3rd level mutant with a 10 MSTR could make a recording up to 26 units in length.
The number of recordings stored cannot exceed the mutant's adjusted INT.
Extreme volume cannot be reproduced solely by the mutant.
So she would not be able to scream back a sonic attack. 
The reproduction could reproduce a heard sentence perfectly.
The mutant could not recreate another persona's speech pattern.


=== Suggestion 

[horizontal]
Range:: 1h per 2 Adjusted MSTR
Duration:: Special
Frequency:: 1 per Adjusted MSTR
General Bonus:: Combat Ratio +5, +40 on negotiation rolls

Suggestion can press an intelligent organic persona to make choices she usually wouldn't make.
The mutant could speak a suggestion that this isn't the parking space the target wants.
If the target loses her psionic roll, she would agree and move on to park somewhere else.
The mutant may think a suggestion at an opponent that they need to save ammunition on their fusion rifle.
If the target loses her psionic roll, she will switch to a different weapon.

The mutant can think, or speak, a suggestion at the target.
Spoken suggestions are made orally by the mutant.
Spoken suggestions only work if the target understands the language.
Thought suggestions are directed at the target's consciousness and do not depend on language.

Spoken suggestions are more potent than thought suggestions. 
The target gets a psionic roll bonus of +3 for thought suggestions.
More sensible suggestions are stronger than dangerous proposals.
Destructive suggestions like: harm yourself, attack your friend will undoubtedly fail.
The referee can make psionic roll adjustments (+1 to +6) depending on the suggestion's gravity.

=== Telekinesis 

[horizontal]
Range:: 2h per Adjusted MSTR
Duration:: 2u per Adjusted MSTR
Frequency:: 1 per 3 Adjusted MSTR
General Bonus:: Combat Ratio +5

Telekinesis allows the mutant to lift objects without touching them.
When the mutant concentrates on an object, it will float through the air under the mutant's control.
Objects controlled by telekinesis are not subject to gravity or wind.
The mutant controls the object's translational motion with her will. 
Telekinesis cannot be used to control fine motor actions. 

The mutant cannot use telekinesis on herself.
Specifically, the mutant cannot use telekinesis to fly.

An object includes anything less than half the mutant's wate.
Objects with a wate greater than half the mutant's wate are immune to telekinesis.
An object can be any persona type or an inanimate object.
Anthros, aliens, robots and bags of turnips are vulnerable to telekinesis.
Voluntary organic targets can be moved by telekinesis automatically.
Involuntary organic targets can avoid telekinesis by winning a psionic roll.
All inorganic targets must make a psionic roll to prevent telekinesis. 
Robots and artifacts cannot choose voluntary telekinesis.
Inorganic objects are assigned a random MSTR of 0-9 (1d10-1).
Artifacts in the hands of personas use the persona's MSTR.

If an involuntary target is holding onto something, the referee may allow MSTR vs PSTR attribute challenge.

Sometimes players need to know how fast an object can move telekinetically.
The speed of telekinesis depends on the mutant's MSTR. 
The xref:i-roll_playing_rules:CH03_AttributesDEX.adoc#_moverate[Movement Rate,window=_blank] table is consulted replacing dexterity with the mutant's mental strength. 
So a persona with a 16 MSTR could move an object at six h/u.

Sometimes players want to weaponize telekinesis.
There are many ways to weaponize this mutation.
Lifting a target straight up and dropping them is the simplest.
Regular xref:i-roll_playing_rules:CH19_Terrain.adoc#_falling[Falling,window=_blank] damage applies.
Lifting a target and dropping them off a cliff is very effective as well.
Lifting an object and dropping it on a target can only be used on stationary targets. 
Dropping things is not effective if the target is moving.

The most complicated way to weaponize telekinesis is also the most cinematic.
Players love to hurl objects at targets during combat.
The persona must first win an attack roll to hit the target. 
The attack is considered a non-powered projectile weapon (type B).
If there is an advantage, the player can switch the persona's PSTR with her MSTR.
After being thrown, an object is no longer under the control of telekinesis.

.*Simple Damage Calculation*
* Tiny objects inflict 1d6
* Small objects inflict 1d8 (most common size)
* Medium objects inflict 1d10
* Large objects inflict 1d20
* Gigantic objects inflict 1d100

.*Complicated Damage Calculation*
Determining the damage inflicted by a telekinetically thrown can be made trickier.
When throwing random objects at targets the most complicated ruleset to use is xref:i-roll_playing_rules:CH31_Robotic_Combat.adoc#_ramming[Robotic Ramming,window=_blank].


=== Telekinetic Arm 

[horizontal]
Range:: 1h per Adjusted MSTR
Duration:: 1u per Adjusted MSTR
Frequency:: 1 per 3 Adjusted MSTR
General Bonus:: Combat Ratio +5

This mutant has a telekinetic arm that can carry out fine motor actions.
This invisible articulation can do anything from back-scratching to weapon using to pick-pocketing.
The arm functions like a real arm, paw and all.
The arm can lift an amount determined using the mutant's MSTR for wate allowance.
Even though the telekinetic arm is invisible, it must always be within line of sight.
The mutant can only generate one telekinetic arm at a time.

The telekinetic arm takes damage from area of effect attacks. 
A telekinetic arm will dissipate if it takes more than half the mutant's HPS Max.
A mutant who has 50 HPS Max would lose her telekinetic arm at 25 HPS of damage. 
The mutant takes no damage, but the arm will dissipate and drop any item it is carrying.

=== Telekinetic Flight 

[horizontal]
Range:: Persona Only
Duration:: 30u per Adjusted MSTR
Frequency:: 1 per 3 Adjusted MSTR
General Bonus:: Combat Ratio *3

Telekinetic flight allows the mutant to fly through the air with the power of her mind.
She can defy gravity by merely concentrating her psionic powers.
The mutant can hover, skim along the ground, or soar high into the air.

Telekinetic flight works in any milieu except underwater. 
Neither gravity nor atmosphere is necessary for telekinetic flight.
The mutant cannot carry too much equipment when telekinetically flying.
Using the xref:i-roll_playing_rules:CH18_Encumbrance.adoc[Encumbrance,window=_blank] rules the mutant must be un-encumbered.
If she is carrying too much junk, telekinetic flight does not work.

Telekinetic flight allows her to move at speeds up to three times her movement rate.
The mutant uses her MSTR instead of her DEX on the xref:i-roll_playing_rules:CH03_AttributesDEX.adoc#_moverate[Movement Rate,window=_blank] table.
A persona with a 12 MSTR could telekinetically fly at 15 h/u.
There is no official limit to the speed of telekinetic flight.
However, extreme speeds may exceed the tolerances of the mutant's body.

=== Telempathy 

[horizontal]
Range:: 1h per Adjusted MSTR
Duration:: 30u per Adjusted MSTR
Frequency:: 1 per 6 Adjusted MSTR
General Bonus:: COmbat Ratio +2, +40 on negotiation rolls, +20 on vet rolls

Telempathy allows the mutant to project moods or feelings into the consciousness of organic personas.
The mutant can force personas to feel pain, anger, love, hate, fear, etc.
A Ursidae may frenzy when overwhelmed by anger.
A patient may feel pleasure instead of pain during a procedure.
A nervous persona would suddenly become calm.
The emotions felt by the target are real to them and overwhelming.
Fear will cause the target to bolt in terror; sadness will have them wailing and crying. 
Telempathy does not have subtle effects on the target.

The target must fail her psionic roll for telempathy to work.

Telempathy is not an area of effect mutation. 
The mutant can attack multiple targets at once with additional uses of the mutation.
Less intelligent personas may be incapable of comprehending higher emotions.
Trying to make flora or fauna feel jealous would likely fail.

=== Teleport 

[horizontal]
Range:: 500 km per Adjusted MSTR
Duration:: Instantaneous
Frequency:: 1 per 12 Adjusted MSTR
General Bonus:: Combat Ratio +10

Teleportation transports the mutant's body and consciousness instantly across the physical space.
The mutant visualizes herself in the new location, and her psionic powers correct reality to her visualization.
The mutant slips through hyperspace via the think space and rematerializes in the physical space. 
As long as the target hex is within range, the mutant can teleport there.
There are no barriers to teleportation as it does not occur in physical space.
If the mutant is travelling within hyperspace, the mutant can only teleport within the space vehicle.

Teleportation is mostly safe and compensates for issues such as speed differential.
If the mutant teleports off of a moving train, she reappears, standing where she intended. 
She would not be smashed into the ground as if she jumped from a moving train. 
Teleportation has an instinctive survival defence built-in.
The mutant is unable to commit suicide by teleporting to certain death.
Teleport would not work if the persona were teleporting into a vacuum.

Teleportation is not without risk. 
There is a small chance of a teleport malfunction.
Teleportation failure rules are up to the players.
The referee may offer more teleports per day with higher chances of failure. 

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

include::ROOT:partial$CH58_Table_Teleportation_Failure_Effect.adoc[]

=== Thought Imitation 

[horizontal]
Range:: 4h per Adjusted MSTR
Duration:: One Use
Frequency:: As Needed
General Bonus:: Combat Ratio +5, +42 on learning rolls

Thought imitation turns the mutant's brain into a mental process tape recorder.
By mere observation, the mutant can forge pathways in her consciousness that allow for perfect imitation.
This high level of modelling allows her to repeat physical activities, recreate mental attacks, and predict imitated consciousnesses' actions.
To protect the mutant's brain from becoming a jumble of neural chaos, thought imitations are transient.
The mutant's consciousness resets itself after a restful sleep or loss of consciousness.

The mutant can flawlessly repeat any physical action that she observes.
For thought imitation to work, the action must fail a psionic roll.
The action uses the mental strength of the persona doing the activity.
The mutant could observe a persona opening a combination lock and repeat the combination correctly.
The mutant must be able to recreate the action she is imitating.
A keyboard made for tentacles is more challenging to use than one made for anthro digits.

Thought imitation mutation automatically imitates and returns mental attacks.
The attack is imitated back at the attacker at half strength using the mutant's MSTR.
For example, thought imitation would immediately return a mental blast attack at half power.
The mutation could lead to mutually assured destruction.
Thought imitation applies specifically to mental attacks.
Thought imitation does not work for mutations like teleportation or time stop.

Using thought imitation to predict a persona's actions is a complicated and time-consuming activity.
The mutant must study the target for at least one minute per point of the target's INT.
Therefore a target with 12 intelligence would require 12 minutes of observation.
After observation, the target must fail a psionic roll.
If the target wins her psionic roll, the observation period has failed.
Once the observation is successful, the mutant can imitate the target's thoughts and, therefore, potential actions.

Thought imitation allows the mutant to fake signatures, unlock secret codes, predict battle plans, and order the correct hors d'oeuvre for lunch.
The mutant could predict the combat moves of the imitated mind. 
Combat prediction makes the mutant the perfect sparring partner.
Thought imitation is not mind reading and does not reveal secrets or information.
The mutation will allow the mutant to respond exactly as the target would.
So she may not know the code to a secret door, but once at the door would type the code in effortlessly.

Repeated thought imitations of the same target may be dangerous.
Negative personality traits of the target may become hardwired in the mutant's consciousness.
For example, the mutant may start to exhibit the whiney attitude of the targeted persona. 

=== Time Stop 

[horizontal]
Range:: Consciousness
Duration:: 1u per Adjusted MSTR
Frequency:: 1 per 24 Adjusted MSTR
General Bonus:: Combat Ratio *10

Time stop slows everything in physical space to an undetectable crawl.
For the mutant, it appears as time has stopped around her.
Nothing moves during time stop, except for the mutant.
When time stop is activated, the mutant finds herself in a hazy colour drained diorama.
Falling objects hang in the air, bullets stop, flames freeze, and energy blasts turn still.
There is no hot or cold, no up or down.
All machines, mechanisms, chemical reactions, and physical laws stop cold.
While everything else is frozen, the mutant can move at her usual pace.

What the mutant can get done during the time stop is what makes it the most powerful mutation.
The mutant can race around for the duration of the mutation, altering the course of reality.
She can lift and move any object that she can reach within the duration of effect.
The mutant could gather up all the lazer bolts and point them at other targets.
When time stop ends, the lazer blasts will pursue their new targets.
She could pull the pins on several grenades.
When time stop ends, they all will detonate.
She could open the door of a moving vehicle, push a few personas outside.
When time stop ends,  they will crash onto the road.
She could rush into a burning building, pushing the smoke out of the way, bending the flames, and rescuing as many people as she can carry.
When time stop ends, they will find themselves outside on the sidewalk.

Time stop suspends the mechanisms of the mutant's artifacts as well.
She can fire her weapons and throw her knives, but nothing will happen until time restarts.

Mental mutations do not work within the time-space aberration.
If the mutant has other mental mutations, she can deploy them during time stop.
They would all simultaneously attack when time restarts.
Time stop allows the mutant to stack any other mental mutations that she has. 

Gravity does not function during time stop.
However, the mutant still has limits to how much she can lift.
She can lift ten times her xref:i-roll_playing_rules:CH18_Encumbrance.adoc[Wate Allowance,window=_blank] using her MSTR instead of PSTR.

The range of the time stop is as far as the mutant can think.
However, the effective range of time stop is how far the mutant can move. 
This mutation leaves no visible traces anywhere in existence.
However, there usually is a cacophony of chaos when time restarts.
Not even the mutation time tell can easily detect this time-space aberration.

Time stop is the most powerful mutation in EXP.
The mutant can eliminate any referee persona or win any combat situation.
The mutation's use is limited to every other day for a reason.
Time stop may attract annoying creatures that are born of time-space aberrations.

=== Time Tell 

[horizontal]
Range:: Persona Only
Duration:: Until her time runs out
Frequency:: Constant
General Bonus:: Combat Ratio +2, +42 on timing rolls

Time tell turns the mutant into a walking atomic clock.
She always knows the exact time of day, date, amount of time that has elapsed, duration of an event, or chronological order of any observed series of events.
Not only can she be pedantic about what happens when, but she can do so to several decimal places.
The mutation can be used as an internal watch, for timing cycles of a fusion drive, for knowing exactly when to act, or for detecting time-space aberrations.
The Time Tell mutation is multi-tasking, and she can carry out any number of these tasks simultaneously.

=== Total Recuperation 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: 1 per 12 Adjusted MSTR
General Bonus:: Combat Ratio *2

Total recuperation allows the mutant to restore her body to a previously undamaged state instantly.
The mutant repairs her traumatized tissues by comparing them to an undamaged template stored in her consciousness.
The mutation will not stop the effects of poisons, cancers, infections, or amputations.
The mutant can instantly restore all her hit points.
The persona's HPS Total is recuperated to her HPS Max when this mutation is activated.
Total recuperation can be consciously activated by the mutant or automatically activated when at less than 1 HPS Total.
There must be remaining uses for total recuperation to automatically activate.  

Total recuperation also decreases ageing effects.
This includes ageing attacks and natural ageing effects.
The mutation will quarter the effects (4 years is only one year) of ageing.
The mutant must be at full HPS to use total recuperation versus ageing.

=== Ventriloquism 

[horizontal]
Range:: 2h per Adjusted MSTR
Duration:: 30u per Adjusted MSTR
Frequency:: 1 per 3 Adjusted MSTR
General Bonus:: Combat Ratio +1, +13 on trickery rolls

Ventriloquism allows the mutant to generate acoustic waveforms using her mind.
These sounds are generated within the mutant's consciousness.
There is no indication that she is generating the noises.
The mutant can recreate any noise that her own voice could make.
Ventriloquism allows her to throw her voice perfectly, but it does not allow her to synthesize new sounds.
There is no psionic roll awarded to targets, and sound is a real sound.

Ventriloquism can also be used to alter existing sounds with the mutation's effective range.
Footsteps can be hidden by cancelling the noise out.
The pitch of an alarm bell could be altered or quietened.
One favourite is to alter the pitch of another persona's voice.
Evil referee personas lose some cred when they sound squeaky and high pitched.

While employing this mutation, the mutant can only speak through ventriloquism.
This means the mutant must throw her voice as if it is coming out of her mouth.
This results in the mutant appearing to lip-synch her own voice.


=== Weapons Discharging 

[horizontal]
Range:: 2h Radius
Duration:: Until Dead
Frequency:: 1 per Day
General Bonus:: Defect, +10 on activation and accidental activation rolls

Weapons discharging is a defect that causes mechanical devices to activate accidentally.
Any device with a trigger, a button, or a detonator is capable of spontaneously activating.
The list includes crossbows, lazer guns, artillery, bombs, grenades, aerosols and other switches.
The device must be within the range of this mutant's defect.

Weapons can be accidentally activated if the mutant is ambushed, injured, or otherwise stressed.
When startled, every weapon within range of the mutant's defect is checked for accidental discharge.
If there are no stressors on the mutant, the referee may make one random check per day.
Due to life experience, mutants with weapon discharging tend to avoid trigger weapons.

=== Chance of weapon discharge
.1/2 percent per MSTR - EXPS Level 
****
A weapon check for a 4th level mutant with a 12 MSTR equals a 4% chance of activation.
****

As the mutant gains experience, the chance of accidental activation diminishes. 
The chance of a weapon discharge cannot be less than 1%.
The referee may have non-life-threatening devices turn on at any time.
Weapon's discharging will turn on televids, stereos, vehicle ignitions without notice.
If the accidental activation is life-threatening, the referee must use her once a day check.

include::ROOT:partial$Defect_Disclaimer.adoc[]

include::ROOT:partial$CH58_Table_Direction_of_Weapon_Discharge.adoc[]

:art: Figure_grenade_miss_direction_d12.png
:width: 250px
:snark: Whoops! Random discharge direction (1d12).
:artist: HM
:date: 2010
:license: CC BY-SA 4.0
:description: Diagram of grenade miss direction using a hexagon sheet.

.*Alternative Random Direction*
include::ROOT:partial$articulate.adoc[]

=== Weather Tell 

[horizontal]
Range:: 1 day per Adjusted MSTR
Duration:: As Needed
Frequency:: As Needed
General Bonus:: +42 for nomad rolls

This mutant is intimately entwined with the meteorological nuances of her environment.
Weather tell functions in any and all environments.
She can predict all the normal weather conditions that one would expect.
In addition to the accurate weather report, this mutation also predicts underwater tides, natural radiation surges, cave-ins, solar flares, earthquakes, tidal waves etc.
The mutant can give same day readings with 100% accuracy.
The chance of correctly forecasting events decreases by 5% for every day in the future.

== Mental Mutation Attribute Explanations
Each mutation, whether mental or physical, has certain properties that describe what it is and how it affects play.
The attributes of each mutation are explained in the following paragraphs.
Not only should the basic feature of a mutation be recorded, but the mutation number and the page number where the mutation can be found.

=== Range
The range of a mutation indicates how far away the effects of the mutation can be delivered to a target.
Any exception to this meaning of mutation range will be specified in the mutation.
Many mutations can affect targets hexes away;
others require contact;
and some have a radius of effect.
Ranges are not devoted solely to offensive mutations, and even defensive mutations may be critically affected by range limits.

The intensity of a mutation cannot be regulated, and neither can its area of effect.
Only a single target mutation can be adjusted for different ranges from the persona.
Mutations that have areas of effect will indiscriminately affect all targets in this area of effect.

Nothing can stop a mutation which travels directly from one mind to another.
ESP, gyrokinesis, and telekinesis can pass through any barrier if the mutant has positive proof that the target exists.
Those mutations which manipulate the environment to attack a target, such as mental blast, or launch-able quills, are subject to terrain effects.

==== Distance
The most common is the ranged mutation.
Ranged mutations can be directed at any target within the range of the mutant.
The range is determined by the MSTR and EXPS level of the attacker.
For example, a mutation may have a range of one hex @ MSTR.
This means one hex per point of mental strength and, with a 12 MSTR, a mutant could use the mutation 12 hexes away.
There are variations to this common range format.
Two hexes per MSTR would yield a 24 hex range with a 12 MSTR.
One hex per four MSTR would yield a three hex range with a 12 MSTR.
If the range includes MSTR and experience level, then the two are added.
A fourth level persona with a 12 MSTR would have a 16 hex range with a mutation that was listed as one hex per (MSTR + level).

==== Area of Effect
Radius ranges are spherical and use the location hex of the persona for the centre.
Thus a mutation with a ten hex radius of effect would contain all targets within ten hexes, including above and below the mutant.
The area of effect would include everything in the 20 hex diameter sphere.

==== Touch
Touch mutations are self-explanatory.
The mutant must touch the target to inflict the effects of the mutation, whether benevolent or not.
The touch must be hand, paw or claw to skin, fur or scales.
Some touch mutations can be conducted through material that would be considered conductive, like metal.
Some touch mutations may still be effective if derma-to-derma contact cannot be made.
They may be mutations with very short ranges, several millimetres, and a successful attack roll may be all that is needed to get within range.

=== Duration
The duration of a mutation almost always refers to the length of time that the mutation effects last.
If the mutant has telekinetic flight, she can stay aloft for the duration of the mutation.
Mutations usually require complete concentration on the part of the mutant.
If a mutation obviously does not require complete concentration on the part of the mutant, then the concentration need not be maintained.
Mutations that are always in constant use do not require a significant portion of the mutant's mental or physical resources.

Mutations usually last so many units per point of MSTR, and they may also be affected by the persona's experience level.
If a mutation has a duration of one until per MSTR, then the mutant can make the mutation last 12 units if she has a 12 MSTR.
Other variations of duration exist, and they all function identically to the range variations discussed earlier, except that units replace hexes.
Mutations with random durations are determined each time the mutation is employed.
Such mutations indicate that the mutant has set in motion physical effects which she has no control over.

==== Until Saves
If the duration is "until saves," the mutant may continue the attack until the victim saves or is dead.

==== Permanent
When the duration says "permanent." it indicates that the effects won't dissipate on their own accord.
For instance, permanent healing of HPS means that they will not disappear after a certain number of units, but it does not mean that the mutant has a cache of indestructible HPS.

==== Constant
Most mutations can be stopped whenever the mutant sees fit, except those mutations that have a "`constant`" duration or an "`until dead`" duration.
These mutations will function until the mutant is dead or has the mutation excised.

=== Frequency
The frequency of the mutation indicates how often it can be used during a daily cycle of the mutant.
The frequency assumes a 24 hour day (see Chapter 12: Time and Movement) where the mutant sleeps around eight hours each day.
If the mutant is in a situation where there is no planetary rotation or one where there is no 24-hour cycle, a complete rest (eight hours`' sleep) will be equivalent to the completion of a daily cycle.

Most mutations can be used several times a day, depending on the MSTR and level of the mutant.
The more powerful the mutation, the less frequently it can be used each day.
If the frequency of a mutation is one per four MSTR, a persona with a 12 MSTR could employ it three times each day and would have to rest eight hours before using it again.
For this type of mutation, rest for the brain is essential.
Unless otherwise stated, a mutation can be used at least once a day.
This includes mutations which have very low frequencies (e.g.
One per 13 MSTR).
This mutation could be used once a day, even by a persona with an MSTR of six.

Mutations that can be used more frequently are labelled "as needed" and just as the title states. 
The mutant can use such a mutation as it is needed.
"Constant" mutations are usually defects, and they constantly project their effects regardless of what the mutant is doing.
Constant mutations always function whether the mutant is asleep or awake.

Mutations cannot be stored.
A mutant cannot use a mutation more often one day than the next because she saved some uses from the previous day.
The mutant may use the mutation no more than the frequency states, and each use is cumulative until she rests.
Mutations cannot be compounded to double an effect.
The mutant can only use one mutation at a time unless one of the mutations has a "`constant`" or "`as needed`" frequency.

The mutant has used a mutation whenever the effects start.
Even if the target saves and the mutation has no effect, the mutation has been used.
If the mutant voluntarily stops the mutation, then it has been used.
If the mutant switches from one target to another, this will usually indicate another use.

=== General Bonus
The general bonus listing of the mutation could contain several arcane bits of information that are related to the use of the mutation in unexpected circumstances.
The mutation may indicate a bonus for maneuver rolls, attribute rolls or negotiation rolls.
Any simple effect that the mutation has on the dice rolling of the persona should be included beside the general bonus listing.


== Mutation Sub Tables
When you quickly need a specific type of mutation

=== Defective Mutations
Nature, pharma, or side effect. 
Here is where you unleash biomagical tragedy.

include::ROOT:partial$CH58_Table_Defective_Mental_Mutations.adoc[]

=== Combat Mutations
Nature, pharma, malfunction, or evolution.
Here is where you unleash genetic violence.

include::ROOT:partial$CH58_Table_Combat_Mental_Mutations.adoc[]

=== Non Combat Mutations
Nature, pharma, malfunction, or evolution.
Here is where you unleash genetic curiosity.

include::ROOT:partial$CH58_Table_Non-Combat_Mental_Mutations.adoc[]