= Support Equipment

Support equipment is artifacts that exist to make other artifacts shine. 
Types of support equipment are batteries, ammunition, fuel, manuals, software and spare parts.
Support equipment does not include brassieres or jockstraps.
Support equipment does not have a function on its own. 
However, some support equipment is precious.

Many artifacts require support equipment to function: guns need ammo; detectors need batteries; vehicles need fuel; computers need meaning; everything needs instructions, and everything wears out.

This support equipment section exists to support players in scarce resource campaigns.
It is not a tool to render toys impotent and defeat a game's fun. 
EXP is the game of technological chaos, not the game of carrying defunct equipment. 

:art: video_conference.png
:width: 350px
:snark: Face to face with televid
:artist: Morey
:date: 1962
:license: CC BY-SA 4.0
:description: Drawing of human woman talking with another human woman via a screen.

include::ROOT:partial$articulate.adoc[]


.*Support Equipment Checklist*
. Existing Artifact?
. <<_support_equipment_type,Support Equipment Type>>
.. Subtype?
. Amount
. Details

. xref:iv-software:CH56_Tech_Level.adoc[Tech Level,window=_blank] (optional) 

== Support Equipment Type 

include::ROOT:partial$CH55_Table_Support_Equipment.adoc[]

== Support Equipment Types

NOTE: *Consider existing artifacts when generating support equipment.*

:art: spent.png
:width: 300px
:snark: Spent money spent casings.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Two bullet casings laying on the ground.

include::ROOT:partial$articulate.adoc[]

== Ammunition 
Ammunition is so essential to most weapons that it can hardly be considered support equipment.
Most guns are useless without ammo unless being used as a club.

=== Ammo Type  
Is there an existing weapon for the ammunition type to match?
If there is no existing weapon, roll randomly on the ammo type table.
This roll determines the type of ammo found.
A  weapon that uses batteries would have battery sets. 
A weapon that uses bullets would have magazines.
A weapon that has special fuel would have both the special fuel and the batteries.

include::ROOT:partial$CH55_Table_Weapon_Type.adoc[]

=== Ammo Amount
The number of ammo sets determines the amount of ammo found.
An ammo set is a complete set of what is needed to arm a weapon.
Ten ammo sets are entirely different depending on the weapon type.
Ten sets for a rifle with a 15 round magazine would mean 150 bullets.
Ten sets for a lazer pistol using one battery would indicate ten batteries.
Ten sets for an antimat pistol using two batteries is ten chunks of antimatter ammo and twenty batteries. 

include::ROOT:partial$CH55_Table_Amount_Ammo.adoc[]

.*Armoury*
An armoury represents an endless amount of ammunition.
An ammunition dispensary is not mobile, and the expedition does not get to carry it around.
An armoury could be a battery recharger or broadcast power.
An armoury could be an ammo dispenser or ammunition store.
An armoury conveniently justifies endless munitions for combat fun.

=== Ammo Attributes
Ammunition wate and value are listed with each weapon type. 
Ammo does not earn a persona experience points. 


== Batteries 
Many artifacts require a stored energy source to operate.
The most common stored energy source is batteries.
Batteries should make the game more fun by limiting powerful weapons and a sense of conservation.

This section serves two purposes.
First is determining the cell type and number of cells for a newly generated artifact.
The second is to determine the cell type and number of cells in a cache of support equipment.
For a generated artifact the player needs to roll <<_cell_type,Cell Type>> and <<_cells_per_set,Cells per Set>>.
For a support equipment cache the referee needs to roll <<_cell_type,Cell Type>>, <<_cells_per_set,Cells per Set>> and <<_number_of_cell_sets,Number of Cell Sets>>.

=== Cell Type 
The cell type determines the sciency fiction process that the battery employs to create electricity.
An artifact may require a specific cell type and number of cells to function.
Some campaigns will allow cell types to be interchangeable. 
Cell types should add fun to the game and not frustration. 

include::ROOT:partial$CH55_Table_Cell_Type.adoc[]

Gas::
This cell contains chemicals in a gaseous state reacting to create energy.
A gas cell will cease to function if exposed to extreme cold (like a cryogenic attack).

Liquid::
This cell contains chemicals in a liquid state reacting to create energy.
A liquid cell will cease to function if exposed to a vacuum.

Solid::
This cell contains chemicals in a solid state reacting to create energy.
A solid cell will cease to function when exposed to extreme heat (like fusion, napalm or sustained fire).

Plasmoid::
This cell contains chemicals in a plasmoid state, reacting to create energy.
The plasmoid has a failsafe that prevents its weaponization.
A plasmoid cell will cease to function when exposed to zero gravity.

Dynamo::
Internal dynamos manufacture the useable energies of this cell.
A dynamo cell will cease to function when exposed to high gravity.

Solar::
A solar cell converts light into energy and stores it for later use.
A solar cell can recharge itself after one full hour in bright light.
A solar cell will cease to function if exposed to a violent light attack. 

Magnetic::
A magnetic cell converts magnetic waves into energy and stores it for later use.
A magnetic cell can recharge itself after one full hour in a natural magnetic field.
A magnetic cell needs a natural magnetic field created by a planet or moon for recharging.
These cells cease to function if exposed to magnetic attacks.

Broadcast::
Broadcast cells are power receivers that convert transmissions from a power source into energy.
The receivers will cease to function if they are subject to electronic jamming or leave the broadcast range.
If the broadcast source stops transmitting, broadcast cells stop working.
The range of broadcast power is up to the referee.

Psionic::
Psionic cells tap into the Kirlian energy of consciousness to create energy.
The psionic cells drain mental strength to recharge themselves.
The psionic cell will make a psionic attack on the nearest persona, usually, the persona using the device.
If the target wins her psionic roll against a 3-18 (3d6) attack, the battery moves onto the next nearest consciousness.
The player generates a new attack intensity each time the psionic cell requires recharging.
The psionic battery will keep doing this until a persona fails her psionic roll.
That persona loses one point of mental strength, and the psionic battery has recharged.
If all the nearby personas win their psionic rolls, the battery will stay drained until a new mind comes in range.
The range of the psionic attack is one hex per intensity.

=== Cells per Set
The cells per set can be the number of batteries needed to operate an artifact or the multiplier for the number of batteries in a cache.
If you are generating a new artifact, the table represents the number of batteries required for an artifact.
For example, a mutation detector may have two cells per set.
Two cells per set indicate that those two batteries will operate the detector for five days.
If you are generating a cache of batteries, the table represents the multiplier for the <<_number_of_cell_sets,Number of Cell Sets>>.
For example, a battery cache with four cells per set and four sets would have 16 batteries. 

include::ROOT:partial$CH55_Table_Cells_Required.adoc[]

=== Number of Cell Sets
The number of cell sets helps determine the number of cells in a cache of batteries.
To determine the total number of batteries in a cache, multiply the cells per set times the number of cell sets. 
For example, a battery cache with four cells per set and four sets would have 16 batteries. 

include::ROOT:partial$CH55_Table_Amount_Batteries.adoc[]

.*Power Source*
Power source can indicate a receptacle or generator that powers the artifact.
If the artifact is mobile, there may be a charging station for the artifact.
A power source conveniently justifies endless energy for combat and research fun.

:art: battery_pack.png
:width: 250px
:snark: Extra wate equals extra lazer bolts.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Lazer pistol with extension cord to battery pack on belt.

include::ROOT:partial$articulate.adoc[]

=== Powerpacks
Powerpacks are a collection of cells combined into one device.
Powerpacks have a cell type and number of cells to power any artifact with a powerpack plug.
So a power pack with 16 cells could power a four-battery lazer rifle four times over before expending.
A 16 cell powerpack could power a one cell mutation detector for 80 days. 
Powerpacks contain a number of cells equal to a support equipment battery stash.
To generate a powerpack the player jumps to <<_cell_type,Cell Type>>, <<_cells_per_set,Cells per Set>> and <<_number_of_cell_sets,Number of Cell Sets>>.

=== Multicells 
A multicell is a single cell that replaces an entire battery set. 
The player jumps to <<_cells_per_set,Cells per Set>> to generate a multicell.
If the player generates four cells per set, the multicell can replace four cells.
If an artifact required four solid cells to operate, a multicell with four cells could replace them.
A multicell does not work like a power pack, and a four-cell multicell cannot power a single cell artifact four times over. 
A multicell must have at least two cells per set.

=== Battery Attributes
All batteries, including multicells, have a wate of 0.1 kg (100 gm).
Power packs have a total wate of 2 kg regardless of the number of cells it stores.

A basic battery cell is worth 100 eps.
A powerpack or multicell is worth 200 eps per basic cell. 
A recharging cell is worth 1000 eps.
A recharging multicell or powerpack is worth 2000 eps per cell.
A psionic cell is priceless and dangerous. 
Late one morning, I made a table that says the same as this paragraph.

include::ROOT:partial$CH55_Table_Cell_Value.adoc[]

There are no experience points earned for batteries. 

== Fuel 
Fuel powers vehicles and space vehicles in EXP.
Many campaigns will forgo fuel for fun, and that is an entirely reasonable approach.
The rules for fuels are for scarce resource campaigns.

=== Fuel Type
If the expedition is discovering a fuel cache, the referee should match it with an existing vehicle.

include::ROOT:partial$CH55_Table_Fuel_Type.adoc[]

For more information about fuel and energy jump to the generic mythos section -> xref:vi-appendices:Appy_C_Campaign_Mythos.adoc#_energy_and_power[Energy and Power,window=_blank].

=== Fuel Amount
Fuel amount is determined randomly by two factors.
First, the player generates a random amount of fuel.
Second, the player and referee decide if the fuel is for a vehicle or a space vehicle.
These two elements determine how much fuel is present. 
If the player rolls an eight 800 km of vehicle range or eight months of space, vehicle power would be eight months.

Filling the vehicles is entirely determined by the campaign. 
One would expect that large space vehicles would have spaceports for filling up.

include::ROOT:partial$CH55_Table_Amount_Fuel.adoc[]

.*Depot*
If the player rolls depot as an amount, then there is an unlimited supply of fuel present. 
This may be a refinery, or auto dispenser, or bubbling geographic anomaly.
The depot cannot be move, but it does represent an endless supply of the needed resource.

:art: space_suit_bulky_face_with_pencil.png
:width: 250px
:snark: Happy mech Happy spaceship
:artist: Studiostoks
:date: 2018
:license: Copyright by Studiostoks
:description: Drawing of happy human woman in bulky space suit and floating screwdriver.

include::ROOT:partial$articulate.adoc[]


=== Fuel Attributes
Listing fuel amounts in kilometres of range and months of service make wate and value determination a bit tricky.
Determining fuel wate is a situation that uses post factualization.
Post factualization allows the referee to determine game elements retrospectively while pretending it was always so.

If the fuel is for an existing space vehicle, and the number of months worth of fuel has a wate based on the ship tonnage.
If there is no existing space vehicle, the law of averages indicates that an average month of fuel has a wate of 10 tonnes.

Calculating fuel wate for inatmo vehicles is much simpler. 
Basic fuel types have a  wate of 10kg per 100 kilometres of fuel.
Rechargeable and continuous fuel types have a wate that is 3% of the vehicle wate. 

The milieu of the campaign determines the value of the fuel.
A scarcity based campaign may make fuel acquisition the entire point of the game.
A space-faring campaign may make fuel a cheap and accessible commodity used to travel the galaxy.
One eps per kilogram of fuel makes a decent reference and conversation point.

There are no experience points earned for finding fuel.


== Manuals
Manuals help the personas understand, use and repair artifacts and equipment. 
The referee should assign manuals to existing artifacts and equipment.
If the manual is purely random then the player will use the TOY system.
TOYs is used to generate what artifact the manual is for.

An artifact discovered in the rubble of a mutant's lair is not likely to have any manuals at all.
Guns purchased a the local Laz-R-Mart will have an instruction manual.
A vehicle stolen from a garage may have a repair manual along for the ride. 

The manual will reflect the complexity of the artifact.
Space vehicles will have enormous manuals stored within their onboard computers. 
A vibro mace may have a simple pamphlet covered in pictograms.

=== Type of Manual
There are two types of manuals: instructional and repair. 
The vast majority of manuals will be instruction manuals.
An instruction manual may be as simple as a pamphlet or as gargantuan as a computer system.
Repair manuals are less common than instruction manuals.
Repair manuals are virtually useless to any persona that is not a mechanic.
A bonus of +50 on the performance table roll is granted to a mechanic when using a repair manual.

=== Number of Manuals
Most commonly the player will generate one manual.
Pairs of manuals may be connected 

include::ROOT:partial$CH55_Table_Amount_Manuals.adoc[]

.*1/2 Manual*
A half manual is somehow less than a full manual.
The manual may be missing a part, in a strange language or be for the wrong equipment model.
The manual should not be useless. 
A useless manual should not count as an artifact.

.*Library*
A library is a collection of instructional and repair manuals for all manner of equipment.
There was a time when a library represented a fixed building full of books.
Even in mundane terra, a library can live in a fancy book (electronic book).
The format of the manual determines the type of library.
A library full of paper sheets would be like a library from the last millennium. 
A library on a fancy book would resemble a tablet or computer.

=== Format of Manual
The manual format is mostly for appearance and plays a role in the manual's mobility.
A built-in manual will be part of the artifact. 
Sheet manuals can become very large.
A plastic sheet manual for a space vehicle might resemble a library, but for just one artifact. 

include::ROOT:partial$CH55_Table_Manual_Format.adoc[]

=== Manual Attributes
Unless the manual is a library or built into the device, the persona should be able to carry it around.
If the wate of a manual is too much for a persona to carry, then the manual had better be for a large complex artifact.

The value of an instruction manual comes from the identification and ability to operate the artifact.
Repair manuals can be quite valuable.
As a rule, a manual is worth 1/100 of the value of the artifact.
For a space vehicle, the manual is very valuable in terms of ship function and plain value.

When a mechanic uses a repair manual in conjunction with an artifact, she is awarded the experience point value of that artifact.


== Programmes
Programmes are collections of code that provide skills and insights for inorganic brains.
The inorganic brains include computers of the following types: vocation, space vehicle, robotic, AI and biological.
The referee should consider generating programmes for existing inorganic brains. 
For example, if there is a robot persona, consider having a robotic programme. 

=== Number of Programmes
Most commonly, the player will generate one programme.
A group of programmes may be a suite of tools to assist the inorganic brain.
A programme suite could be an accounting programme and a fraud detection programme.

include::ROOT:partial$CH55_Table_Amount_Software.adoc[]

NOTE: Programmes fully integrate with the computer brain, and a programme is *single-use*.

.*1/2 Programme*
A half programme is somehow less than a full programme.
The programme may be missing a subroutine, in a strange language or be for the wrong equipment model.
The programme should not be useless. 
A useless programme should not count as an artifact.

.*Repository*
A repository is a collection of programmes that the player can search and download.
The Programme Format determines the nature of the repository.
The repo could be a collection of floppy disks or a crystal holding all known programmes for that inorganic brain.
A repo is powerful, but it should be the tool that solves every problem.
Even the best repository may have dependencies that keep every imagined programme from working.

=== Programme Format 
The programme format is an esthetic choice.
There is no performance difference between each of the programme formats.
A format may change the wate of the programme artifact, but it cannot render it useless.

include::ROOT:partial$CH55_Table_Software_Format.adoc[]

=== Programme Type
The programme type indicates computer brain compatibility.
The programmes are not cross-platform, and a vocation computer programme does work with a space vehicle computer.
The programme is strictly limited to the particular computer brain unless it is designated a cross-platform programme.

include::ROOT:partial$CH55_Table_Software_Type.adoc[]

=== AI Computer Programmes
AI programmes work in the MOM series of artificially intelligent computers.
MOM computers are part of the generic mythos of EXP.
For more info jump to xref:v-wetware:CH69_AI.adoc[Autonomous Intelligence,window=_blank]

include::ROOT:partial$CH55_Table_AI_Computer_Software.adoc[]

:art: bio_computer_virus_desat.png
:width: 250px
:snark: Nasty computer virus
:artist: Studiostoks
:date: 2015
:license: Copyright Studiostoks
:description: Drawing of human being attack by tentacles coming out of a computer tablet.

include::ROOT:partial$articulate.adoc[]

=== Vocation Computer Programmes
Vocation programmes work with vocation computers.
Vocation computers assist personas with technical maneuvers carried out by their vocation.
A programme will decrease the difficulty of a maneuver by 0-5 (d6-1) degrees of difficulty.

include::ROOT:partial$CH55_Table_Class_Computer_Software.adoc[]

=== Space Vehicle Computer Programmes
Space Vehicle programmes work with space vehicle computers. 

include::ROOT:partial$CH55_Table_Space_Vehicle_Software.adoc[]

=== Robotic Brain Programmes
Robotic brain programmes extend the skills of a robot persona. 
These programmes are only for insertion and integration with a robotic brain.
The robot persona will add the programme to her repertoire regardless of her robot type.
The programme may be inserted through a port or nailed onto the robot with a sledgehammer.
The player can choose to roll on either AI Computer Programmes or Vocation Computer Programs.
A robot cannot have a space vehicle programme.

=== Biologic Brain Programmes
A biologic brain programme allows an organic persona (anthro or alien) to acquire new skills and abilities instantly.
These programmes are only for insertion and integration with an organic brain.
The programme will give the persona the described ability regardless of her vocation type or family.
The programme may be inserted directly into the skull, delivered via the eyes and ears, or implanted using vet equipment.
The player can choose to roll on either AI Computer Programmes or Vocation Computer Programs.
An organic persona cannot have a space vehicle programme.

=== Cross Platform Programmes
A cross-platform programme is usable by any inorganic computer brain system.
The player rolls on the type again ignoring, robotic, biologic and cross-platform programme types.
Whether the programme is an AI programme, a vocation programme or a space vehicle programme, it works in any inorganic computer brain.

=== Programme Attributes
A programme is a single use entity that melds with the inorganic brain.
The programme cannot be reused and the brain is permanently changed.
Most often the programme can be carried by the persona. 
If the programme is too have for one persona to carry then it must have accessories included.
Space vehicle programmes can have porting, and tooling necessary for the programme to work.

.*Programme Value List*
* AI programme, 100000 eps
* Space Vehicle programme 500000 eps
* Robotic programme 10000 eps
* Cross platform 1000000 eps
* Biologic 2000042 eps


== Spare Parts 
Spare parts help mechanics repair damaged or worn-out equipment.
A mechanic could also use spare parts to enhance a piece of equipment.

Spare parts usually enter the game when a strategic piece of equipment (the one needed to save the universe) breaks down.
Spare parts will always be related to some artifact existing in the expedition already.
Spare parts will appear as unidentifiable odds and sods with a wate 25% of the artifact in question.
Spare parts will have no particular value.
A mechanic will gain +30 on PT repair maneuvers if spare parts are present.

If the referee chooses to have a completely random spare part jump to -> xref:iii-hardware:An_index_hardware.adoc#_toy_type[Toy Type,window=_blank]. 

