= Tech Level

An artifact's tech level (TL) reflects the technological advancement of who created the device.
The higher the tech level the more advanced the device.
The lower the tech level the less advanced the device.
EXP is the game of technological chaos, and high tech level items can exist alongside low tech level items.
If the referee chooses a singular tech level for her milieu and campaign that is completely acceptable.
The following paragraphs detail how to manage various tech levels in EXP.

.*Tech Level Checklist*
. Roll Tech Level
. Adjust wate
. Adjust value
. Adjust description
. Adjust Identification difficulty

The usual tech level is ten. 
Tech level ten reflects the tech of level of mundane terra in the late 20th century.
One could argue that in the 2020s the tech level of mundane terra is possibly 11 with gusts up to 12.
This discussion is beyond the scope of this text, and the average tech level remains 10.
The wate and value of artifacts is based on tech level ten.
Any variation from tech level ten changes the wate, value and appearance of the artifact.

:art: bomb_low_tech_plane.png
:width: 250px
:snark: Peace Maker Low Tech
:artist: unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of smug humans standing around a propeller plane and atomic bomb.

include::ROOT:partial$articulate.adoc[]

The lower the technology of the item the worse off it is.
Low tech level artifacts are heavier, less valuable and more prone to malfunction.
A large building full of water buckets may represent a society's best calculator.
A windmill may be a patented commercial water pump.
Low tech level items can be confusing, and therefore hard to identify. 

:art: bomb_high_tech_dog.png
:width: 250px
:snark: Peace Maker High Tech.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of smug dog burying mouth sized atomic bomb.

include::ROOT:partial$articulate.adoc[]

The higher the technology of the item the better it is.
High tech level artifacts are lighter, stronger, and more valuable.
High tech level items may also be harder to identify.
A flotto laser rifle may look like a stick, and behave like a wand.
A psionic headband may look like a 1970s elastic sweat band, and have a built in radio.
Very high tech items can appear magical in nature. 

== Keeping Time
Time keeping is an important and familiar procedure for us mundane humanoids. 
The below table roughly and historically inaccurately outlines the impact of tech level on time keeping
The table starts at tech level 0, where there is no concept of time, and temporal actions are carried out instinctively.
Very low tech levels reflect the observation of time and it's recognition beyond DNA wiring.

As the tech level of a device increases the skills that require its construction also increase.
Which one begets the other is unclear.
Advances in metallurgy, electronics, ceramics, design, and microbiology are applied to the keeping of time.
The time piece becomes finely focused, and eventually intricately integrated.

The clock ceases being a unit on its own, but is now a trivial component of other devices.
Stoves, cars, pens, and rulers all have built in time keepers. 
As a culture we no longer look for a clock, but we look for the time.
The concept is all that matters the device has been absorbed by other devices.
The device is no longer part of the process.

include::ROOT:partial$CH56_Table_Tech_Level_and_the_Time_Piece.adoc[]

== Mixing It Up
The referee can choose to have a singular tech level for her milieu and campaign.
The TOY system operates under the basic assumption that any device can appear at any tech level.
The tech level refers to the tech level of the *specific artifact*.
The tech level does not refer to the tech of society from which the device arose.
Most societies simultaneously have many different levels of technology at once.
High tech artifacts can by mixed with low tech cultures.
The mix of tech levels arises from ancient extinct societies, alien visitors or trade, or clumsy time travellers. 
All of these sources of tech level are mixed into the melange that is this game of technological chaos.

NOTE: As of 2020 there are at least 300 competing patents for http://tinyw.in/AJRp[dog poop scoopers] on mundane terra.

== Tech Level Ten 
All equipment described in the technology section is tech level ten (TL10).
Tech level ten is an arbitrary number that allows tech levels below and above.
Tech level ten is a familiar reference point for us on mundane terra.
TL10 is that point where all the facets of science--mathematics, electronics, physics, biology--can be cumbersomely grouped together to make any device operate.

As stated previously, the tech level of one device does not represent the tech level of an entire culture.
High tech can be found in low tech cultures.
A high tech artifact merely represents a better combination of the basic sciences for that particular item, and not necessarily a better understanding of these sciences by the whole culture.

== Assigning Tech Level
The vast majority of equipment will be tech level 10.
If the players and referee are in agreement with random tech levels refer to the table below.

include::ROOT:partial$CH56_Table_Assign_Tech_Level.adoc[]

== Effect of TL 
The effects of tech level on equipment are described below.
Wate, EXP and Value are all multipliers.
The native TL 10 device's wate or EXPS or Value is multiplied by the adjustment.
The Artifact Identification (AID) adjustment is added to each roll the player makes on the tactical AID System.

include::ROOT:partial$CH56_Table_Effect_of_Tech_Level_(TL)_on_Artifact.adoc[]

=== Wate 
A low tech level item will use materials which do not aid the device's construction.
In a low tech device components will tend to be arranged in a non-beneficial manner.
As a device increases in tech level, its components become more intricate, and the materials chosen for its construction are of a higher quality.
Such advances decrease the wate of the item.

The numbers listed in the Wate Adjust column are multipliers.
A TL 10 medium powered flotto lazer pistol has a wate of 1.8 kg at TL 10.
At tech level 3 the pistol would have a wate of 9 kg (wate multiplier of 5).
At TL 16 the pistol's wate would be 0.9 kg (wate multiplier of 0.5).
The decreased wate cannot be a detriment, the lighter flotto pistol would have intricate kick back compensation and function better than a TL 10 version.

=== Experience Points 
The experience point value of a piece of equipment is altered by tech level.
This multiplier is awarded by the fact that high, and low, tech artifacts are harder to identify.
Identifying a better made or much worse made TOY may actually yield more information than the regular artifact.
A TL 3 lazer pistol is worth 780 EXPS.
This is 180 experience points more than the tech level 10 version of the same weapon.
This extra experience is awarded in part because the gun is harder to identify, and in part because it is a prime example of either poorer, or better, engineering (as opposed to more of the same).

=== Value 
The value multipliers on Table 56.03: Tech Level Effect are simple enough when used as described.
The problems with the system arise when any semblance of economics is applied to the game.
The first phenomena is the high technology, high inflation correlation.
Why should everything at tech level 18 cost 5 times more than at TL 10?
Does this mean that there is a 500% increase in the cost of production to rise 8 tech levels.
Are the costs of living in a TL 14 world higher than on a TL 8 world?
Why would they be?
The inherent increases of the value multipliers put economic constraints, that actually may not exist, on cultures.
So the reference point is TL 10.
But what about the value of a TL 20 item in a TL 3 world?
These problems will arise only when playing with the most miserly, or observant, of players.
The value multiplier is designed to indicate the comparative value of two artifacts of different tech levels designed for the exact same function.
The referee should remember this, and incorporate it into her explanations of the preceding queries.

=== Identification 
The tech level of an object greatly affects a persona's ability to identify it.
For example, the TL 3 gun described earlier has a wate of 9 kg.
Who would expect a 9 kg gun to be a pistol?
Wate is not the only TL change that can make a toy hard to IDN.
The toy may use different materials--e.g., a plastic frying pan;
the device may operate under a different process--e.g., a stock is squeezed instead of a trigger pulled;
or the artifact may look entirely different--e.g., a key may be a metal ball touched against a door.

Tech level penalties are not applied as mechanically as wate multipliers.
These AID adjustments are relative.
If a person has grown up in a city where 9 kg, TL 3 lazer pistols are the norm, the artifact identification penalty shouldn't apply.
So it is the job of the referee to ensure fair application of these penalties.
These penalties would only apply if the play group is using the
