= Tech Level

An artifact's tech level (TL) reflects the technological advancement of who created the device.
The higher the tech level, the more advanced the device.
The lower the tech level of the device, the less advanced the device.
EXP is the game of technological chaos, and high tech level items can exist alongside low tech level items.
The referee is free to choose a tech level for all artifacts in her campaign. 
The following paragraphs detail how to manage various tech levels in EXP.

:art: very_high_tech_anti_grav.png
:width: 350px
:snark: A very high tech antigrav device.
:artist: JEShields
:date: 2014
:license: Copyright JEShields Stock Art. jeshields.com
:description: Woman in desert robes riding a carpet.

include::ROOT:partial$articulate.adoc[]

.*Tech Level Checklist*
. Roll Tech Level
. Adjust wate
. Adjust value
. Adjust description
. Adjust Identification difficulty

The usual tech level is ten. 
Tech level ten reflects the tech of the level of mundane terra in the late 20th century.
One could argue that in the 2020s, the tech level of mundane terra is possibly 11, with gusts up to 12.
This discussion is beyond the scope of this text, and the base tech level remains 10.
All artifacts that the TOY system generates is a tech level ten device.
Any variation from tech level ten changes the wate, value and appearance of the artifact.

:art: bomb_low_tech_plane.png
:width: 250px
:snark: Peace Maker Low Tech
:artist: unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of smug humans standing around a propeller plane and atomic bomb.

include::ROOT:partial$articulate.adoc[]

The lower the technology of the item, the worse off it is.
Low tech level artifacts are heavier, less valuable and more prone to malfunction.
A large building full of water buckets may represent a society's best calculator.
A windmill may be a patented commercial water pump.
Low tech level items can be confusing, and therefore hard to identify. 

:art: bomb_high_tech_dog.png
:width: 250px
:snark: Peace Maker High Tech.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of smug dog burying mouth sized atomic bomb.

include::ROOT:partial$articulate.adoc[]

The higher the technology of the item, the better it is.
High tech level artifacts are lighter, stronger, and more valuable.
High tech level items may also be harder to identify.
A flotto laser rifle may look like a stick and behave like a wand.
A psionic headband may look like a 1970s elastic sweatband and have a built-in radio.
Very high tech items can appear magical. 

== Timekeeping Example
Timekeeping is an essential and familiar procedure for us mundane humanoids. 
The below table roughly and historically inaccurately outlines the impact of tech level on timekeeping.
The table starts at tech level 0, where there is no concept of time.
Any chronological actions are instinctive.
The lowest tech levels  (1-3) represent observing time beyond what the flora and fauna's DNA has hardwired.

As the timekeeping device's tech level increases, the skill requirements to create the device also increases.
The clock is made from better and better materials.
The clock uses advances in metallurgy, electronics, ceramics, design, and microbiology to improve its tech level.
The clock may lead to these advances or vice versa.
The improvements on the clock lead to lighter and more portable clocks and, eventually, miniaturization.

The clock ceases to be a unit on its own but becomes a trivial component of other devices.
Stoves, cars, pens, and rulers all have built-in timekeepers. 
As a culture, we no longer look for a clock, but we look for the time.
The concept is all that matters. 
Other devices have absorbed the clock.
The clock is no longer integral to the process of timekeeping.

include::ROOT:partial$CH56_Table_Tech_Level_and_the_Time_Piece.adoc[]

== Mixing It Up
The referee can choose to have a consistent tech level for all the artifacts in her milieu and campaign.
This campaign choice is legitimate.
The following paragraphs give guidance for mixing up tech levels in EXP.

The TOY system operates under the basic assumption that any device can appear at any tech level.
The tech level refers to the tech level of the *specific artifact*.
The tech level does not define the technological level of society from which the device arose.
Most societies can have many different levels of technology at once.
High tech artifacts can be part of low tech cultures, and vice versa.

The mix of tech levels arises from ancient extinct societies, alien visitors or trade, corporate asset tracking failure or clumsy time travellers. 
Mix all of these differing technological development sources, and one has the tech level potpourri that is EXP.

NOTE: As of 2020, there are at least 300 competing patents for http://tinyw.in/AJRp[dog poop scoopers] on mundane terra.

== Tech Level Ten 
All equipment described in the technology section is tech level ten (TL10).
Tech level ten is an arbitrary number that allows space for tech levels below and above.
Tech level ten is a familiar reference point for us on mundane terra.
TL10 is that point where all the facets of science--mathematics, electronics, physics, biology--can work together to create any device.

The tech level of one device does not represent the tech level of the entire culture.
A tech level ten culture will have devices that have higher and lower tech levels. 
One can find high tech artifacts in low tech cultures.
The corollary is true as well. 
One can find low tech artifacts in high tech cultures.

== Assigning Tech Level
The vast majority of equipment will be tech level 10.
If the players and referee agree with random tech levels, refer to the table below.

include::ROOT:partial$CH56_Table_Assign_Tech_Level.adoc[]

== Effect of TL 
Changing a device's tech level from ten alters the device's wate, experience point reward, value and the ability to identify it.
Each tech level has a different impact on the wate, EXPS, and value of the artifact. 
Higher tech levels make the artifact lighter and more valuable. 

include::ROOT:partial$CH56_Table_Effect_of_Tech_Level_(TL)_on_Artifact.adoc[]

=== Wate 
The wate column indicates the change in the artifact's wate.
Multiply the wate adjustment with the artifact's wate to get the new wate for the tech level.

A TL 10 medium-powered flotto lazer pistol has a wate of 1.8 kg at TL 10.
At tech level 3, the pistol would have a wate of 9 kg (wate multiplier of 5).
At TL 16, the pistol's wate would be 0.9 kg (wate multiplier of 0.5).
The change in wate cannot be detrimental to the function of the artifact. 
For example, a very light sword would inflict the same damage as it's lower tech level counterpart.

=== Experience Points 
The experience points (EXPS) column indicates the change in the artifact's experience point award for identification.
Multiply the EXPS adjustment with the artifact's EXPS value to get the new EXPS for the tech level.
The EXPS award can increase for both lower and higher tech devices. 
The persona learns as much from understanding a poorly made device as a well-made device.

A tech level ten lazer pistol is worth 500 EXPS.
At tech level three, the same lazer pistol is worth 780 EXPS.
At tech level twenty, that lazer pistol is worth 900 EXPS.

=== Value 
The value column indicates the change in the artifact's value.
Multiply the value with the artifact's value adjustment to get the new value for the tech level.
Value is very arbitrary and does not reflect market value within the referee's milieu.
A low tech lazer pistol may be very valuable in a world where a lazer pistol is the only ranged weapon.
A high tech lazer pistol may be nothing unusual in a peaceful high tech world where everything is plentiful.

A tech level ten lazer pistol is worth 500 eps.
At tech level three, the same lazer pistol is worth 150 eps.
At tech level twenty, that lazer pistol is worth 5000 eps.

=== Identification 
The tech level of an object may affect a persona's ability to identify it.
For more info about identifying objects jump to xref:i-roll_playing_rules:CH20_Artifact_ID.adoc[Artifact Identification,window=_blank] (AID).
The impact of tech level on AID depends on the campaign and milieu.
If 9 kg pistols are common, there is no artifact identification penalty.

For example, the TL 3 gun described earlier has a wate of 9 kg.
Who would expect a 9 kg gun to be a pistol?
Wate is not the only tech level change that can make a toy hard to identify.
The toy may use different materials--e.g., a plastic frying pan.
The device may operate under a different process--e.g., the stock is squeezed instead of a trigger pull.
The artifact may look entirely different--e.g., a key may be a metal ball touched against a door.

A tech level ten lazer pistol has no artifact identification penalty.
At tech level three, the same lazer pistol has an artifact identification penalty of -4.
At tech level twenty, that lazer pistol has an artifact identification penalty of -8.


