= Tech Levels

These wate, shape and appearance differences contribute to the technological chaos of EXP.
A flotto laser rifle may look like a stick.
A psionic headband could be styled like a necklace.
Very high tech items appear magical in nature. 
The practise of faux science we keep them in the realm of sciency fiction.

Low tech level items can be equally confusing to personas. 
A large building may represent a society's best calculator.
Compare a water pump today from the windmill of yester year.

Tech level is checked for each device that the persona has.
The campaign, milieu and story trump the TOYS.

It is not as though bizarre equipment does not abound in our mundane world: there are at least 300 different patents for http://tinyw.in/AJRp[dog poop scooper] on mundane terra.

Tech level (TL) is an optional roll that is available for all equipment generated (including robots).
The higher the tech level of the equipment, the more technologically advanced the device is.

:art: bomb_low_tech_plane.png
:width: 250px
:snark: Peace Maker Low Tech
:artist: unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of smug humans standing around a propeller plane and atomic bomb.


include::ROOT:partial$articulate.adoc[]

Tech levels in EXP are different from how most persons would perceive technological advance.
The system operates under the basic assumption that any device can appear at any tech level.
The tech level refers to the TL of the specific artifact, and not the level of technological advancement of the society from which the device came.
Most societies simultaneously have many different levels of technology at once.
In EXP it is expected that artifacts from past or alien cultures are to be mixed into the melange of technological chaos

:art: bomb_high_tech_dog.png
:width: 250px
:snark: Peace Maker High Tech.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of smug dog burying mouth sized atomic bomb.

include::ROOT:partial$articulate.adoc[]

== Tech Level 10 
All equipment described in the technology section is considered tech level 10.
Why 10?
Tech level ten is chosen as the baseline on almost arbitrary terms.
To be able to include the various artifacts in the technology part of this book, the common tech level had to be somewhere near midground.

Tech level ten (TL10) represents a level of technological development where virtually any sort of device could exist.
TL10 is that point where all the facets of science--mathematics, electronics, physics, biology--can be cumbersomely grouped together to make any device operate.

As stated previously, the tech level of one device does not represent the tech level of an entire culture.
High tech can be found in low tech cultures.
A high tech artifact merely represents a better combination of the basic sciences for that particular item, and not necessarily a better understanding of these sciences by the whole culture.

== Example 
The following table gives a rough indication of technological advance for a very familiar procedure, keeping track of time.
The table starts at tech level 0, where there is no concept of time, and temporal actions are carried out instinctively.
Tech level 13 is essentially our present experience (ed.
Note as of 1993).
By this point the clock has ceased being a unit of its own, but is now a trivial component of other devices.
Computers depend on clocks.
Stoves, cars, pens, and rulers all have clocks built in.
As a culture we no longer look for a clock, but we look for the time.
The concept is all that matters the device is not part of the process.

As the tech level of a device increases the skills that require its construction--such as metallurgy, electronics, ceramics, design, and microbiology--become finely focused, and intricately integrated.
The benefits of an increased tech level are usually performance oriented, but it would be impossible to document such changes for every device.
There are some basic statistics of all equipment which change when its tech level is greater, or less than, 10.
The wate of an artifact decreases as the tech level increases.

include::ROOT:partial$CH56_Table_Tech_Level_and_the_Time_Piece.adoc[]

== Wate 
A low tech level item will use materials which do not aid the device's construction;
and components will tend to be arranged in a non-beneficial manner.
As a device increases in tech level, its components become more intricate, and the materials chosen for its construction are of a higher quality.
Such advances decrease the wate of the item.
The effect of tech level on the wate of a toy can be determined by referring to the wate heading of Table 56.3: Tech Level Effect.

The numbers listed in the Wate Adjust column are multipliers.
A TL 10 medium powered flotto lazer pistol has a wate of 1.8 kg at TL 10.
At tech level 3 the pistol would have a wate of 9 kg (wate multiplier of 5).
At TL 16 the pistol's wate would be 0.9 kg (wate multiplier of 0.5).
The decreased wate cannot be a detriment, the lighter flotto pistol would have intricate kick back compensation and function better than a TL 10 version.

== EXPS 

The experience point value of a piece of equipment is altered by tech level.
This multiplier is awarded by the fact that high, and low, tech artifacts are harder to identify.
Identifying a better made or much worse made TOY may actually yield more information than the regular artifact.
A TL 3 lazer pistol is worth 780 EXPS.
This is 180 experience points more than the tech level 10 version of the same weapon.
This extra experience is awarded in part because the gun is harder to identify, and in part because it is a prime example of either poorer, or better, engineering (as opposed to more of the same).

== Value 
The value multipliers on Table 56.03: Tech Level Effect are simple enough when used as described.
The problems with the system arise when any semblance of economics is applied to the game.
The first phenomena is the high technology, high inflation correlation.
Why should everything at tech level 18 cost 5 times more than at TL 10?
Does this mean that there is a 500% increase in the cost of production to rise 8 tech levels.
Are the costs of living in a TL 14 world higher than on a TL 8 world?
Why would they be?
The inherent increases of the value multipliers put economic constraints, that actually may not exist, on cultures.
So the reference point is TL 10.
But what about the value of a TL 20 item in a TL 3 world?
These problems will arise only when playing with the most miserly, or observant, of players.
The value multiplier is designed to indicate the comparative value of two artifacts of different tech levels designed for the exact same function.
The referee should remember this, and incorporate it into her explanations of the preceding queries.

== Identification 
The tech level of an object greatly affects a persona's ability to identify it.
For example, the TL 3 gun described earlier has a wate of 9 kg.
Who would expect a 9 kg gun to be a pistol?
Wate is not the only TL change that can make a toy hard to IDN.
The toy may use different materials--e.g., a plastic frying pan;
the device may operate under a different process--e.g., a stock is squeezed instead of a trigger pulled;
or the artifact may look entirely different--e.g., a key may be a metal ball touched against a door.

Tech level penalties are not applied as mechanically as wate multipliers.
These AID adjustments are relative.
If a person has grown up in a city where 9 kg, TL 3 lazer pistols are the norm, the artifact identification penalty shouldn't apply.
So it is the job of the referee to ensure fair application of these penalties.
These penalties would only apply if the play group is using the

== Assigning of TL 
All that remains is determining the tech level of the artifact.The tech level of a TOY is determined on the aptly named Table 56.2: Assign Tech Level.
It is assumed that the base tech level of the milieu is tech level 10.

The EXP system is based on complete technological chaos.
Eons and eons of diverging levels of technology are layered on top of, and beside, each other.
Any of which may or may not be alien.
It is expected that this is the background milieu of most campaigns, the Tech Level Determination table can be used to generate the tech level of a toy.
The table assumes deviations from tech level 10.
The base tech level can be any which the ref chooses.
This is commonly TL 10.

If the referee chooses to create a world with tech level other than 10 she is on her own.
The ref must either be good at arithmetic or create her own Effect of Tech Level on Artifact, and Assign Tech Level Tables.
If the ref finds herself dealing with extreme tech levels (TL less than 0 or greater than 25) here are some tips.
TL 0 indicates that there is absolutely no concept of the device at all.
The culture just responds to changes in the environment.
Consider a tech level 0 time piece.
Or a tech level 0 Anti Virus Beam.
Tech level 0 is essentially the unrolling
of a particular toy.
For any artifact with a  greater than TL 26 (or greater) could indicate that this culture has complete understanding, and control, of such a device.
They may have actually surpassed the need for any such device at all.

include::ROOT:partial$CH56_Table_Assign_Tech_Level.adoc[]

== Effect of TL 
The effects of tech level on equipment have been described above.
Wate, EXP and Value are all multipliers.
The native TL 10 device's wate or EXPS or Value is multiplied by the adjustment.
The Artifact Identification (AID) adjustment is added to each roll the player makes on the tactical AID System.

include::ROOT:partial$CH56_Table_Effect_of_Tech_Level_(TL)_on_Artifact.adoc[]