= Anthropomorphs
		
        		
Every persona, from the evilest RP to the kindest player persona, has a race.
The three types of races found in EXP are anthros (humans, canines, felines, etc.), robots (janitorial to combat) and aliens (flying carnivorous plants to pulsating blobs).
Player personas primarily consist of anthropomorphs.
The other race options (robots and aliens) are extraordinary ones which are complicated to run and are only recommended for experienced players.
For more information about bots and aliens, refer to XREFs Chapter 5 Robots and Aliens.
The races detailed in this chapter are referred to as anthropomorphs.
They are all upright, bipedal and humanoid.
Every persona has legs (for locomotion), arms (not used for locomotion) and hands (attached to the ends of the arms) which are used for grasping/manipulating.
The head, however, would be a facsimile of whichever race the persona is.
The body covering (skin, hide, feathers) will also reflect the base race chosen.
The properly proportioned humanoid form would sport whatever tails, snorts, brows, horns or tufts are found on the base race.

Let’s consider a player who is canine.
First, she shall choose a dog type that suits her fancy.
This is done purely for descriptive purposes and will not alter any of the attributes rolled.
The race type chosen may be reflected in the disposition of the persona though.

After much deliberation, the player chooses that her canine persona will have the likeness of a bulldog.
The persona’s head will have the gnarled features and folded jowls characteristic of a bulldog.
The skin would consist of a coat of short hair, typically found on bulldogs.
She would also have stocky upper shoulders and powerful looking arms (which end in stubby paw-like hands).
Her persona would stand upright on two fur covered legs which are topped off in a stubby tail.
Such descriptions would be analogous for other races, like florians – bark for skin, fungus for hair; or insectoids – a buggy-eyed fly’s head atop a bipedal exoskeleton.

The descriptions are as far as the similarities go.
Insectoid personas cannot lift 1000 times their own wate.
Reptiles do not automatically get poisonous bites.
Avarians aren’t all gifted with flight.
The anthro races have no special abilities other than those described in this chapter.
However, each racial type does have specific features which add to the character of the persona.

It may seem very provincial and humancentric to have all the races bipedal, earthbound humanoids.
Such a attitude can be pseudo-scientifically defended on the grounds that there are definite biological advantages to evolving bipedal.
Regardless of how the referee defends this humanoid preference, the form has primarily been chosen for the obvious advantages it yields to role-playing.


Maintaining a standard of humanoid form allows for a great variety of races which are all readily suited to EXP technology and rules.
This means the game can be easily played with few rule changes for one race to another.
This allows the referee to make preparations without having to make exceptions and special rulings for each race.

The constant humanoid shape of the races can be more easily adapted to by the players.
This gives beginners and experienced players alike the ability to role-play without having to worry about being a quadruped, having treads instead of legs or being shaped like an amoeba.
The truly alien non-humanoids are covered in robots and aliens

How the different races arose allows for many avenues of thought.
Each one could have evolved from a lesser species (as humans evolved from apes); they could be peculiarly mutated forms of humans; they could be surviving progeny of long lost cloning experiments; or they could be a unique collection of beings, each divinely created by a superior deity (like Adam and Eve).

Inquisitive players may force a referee to answer more complex question like:
How do all the races appear in the same place?
Why are they humanoid?
Do androids dream of electric sheep (Dick)?
The answers to such questions may be included in the initial campaign background or may even be woven into the goal of the campaign itself.

The players usually have the option of choosing from one of several races.
Which races the player can choose from depends on the attributes rolled for the persona.

== Creating an Anthro Persona

// Make interactive checklist does not work on antora ui
// [options="interactive"]

.Steps to generate an Anthro persona
. Attributes 
. Adjust attributes by attributes
. Anthro type
. Adjust attributes by type
. Age, Hite, Wate
. Mutations
. Vocation
. Combat table 
. Roll Incidentals 
. Roll TOYS
. Have fun

== Anthro Attributes

Chapter 3 Attributes is dedicated the explanation of anthro attributes.
Since anthropomorphs are the basic persona type in EXP that chapter answers all your attribute questions. 
The referee may have all kinds of different ways for generating attributes for anthros. 
The table below reflects an attribute generation system that results in the most balanced collection of persona races and classes.

//table 4.1 

include::~\persona_creation\partials\anthro_attributes_table.adoc[]

=== Attribute Minimums

The Racial Attribute Table not only restricts personas from being certain races but also protects the player while rolling mutations.
Many defective mutations can reduce attribute scores but, while creating a persona, such reductions can never force an attribute below a race’s attribute minimum.E.g., if a feline with a 9 CHA (minimum 8 CHA) were to get a Total Carapace (physical mutation #50), her CHA should drop by 4 points.
Because a feline’s minimum CHA is 8, her CHA would be 8 instead of the expected 5. Charisma is a special example because often a player will want her persona’s CHA attribute to be as low as possible.
If the player desires this, the protective aspect of the racial minimums can be ignored and her CHA can drop as low as possible.
Remember that the persona’s attributes must meet all of the racial requirements before any race can be chosen.

=== Attribute Maximums

Racial maximums do not apply when the player is rolling up her person.
So a canine could have a charisma of 17 even though the racial maximum is 15. 
Attribute minimums and maximums can be ignored once the campaign start.
The racial minimums do not apply and the racial maximums are firmly in place.
If a player’s CHA drops because of burns or her PSTR drops because of disease or her INT drops because of brain damage during the campaign, the racial minimums will not limit the attribute’s decline.
If one, or several, of a persona’s attributes drops below the racial minimum during the course of a campaign, the persona does not have to change races.

== Anthro Type

The Anthro Type Table used by the player to see which of the twelve races she may be.
The player compares the attributes she has rolled against the minimums requirements for each anthro race, and then picks the preferred one.
For example, if she wanted to be an ursidae, both her DEX and INT would have to be 4 or better and her PSTR would have to be 12 or more.
The best way to determine one’s race is to go down the minimum attribute column and then choose from the races that the persona may become.
	
The attribute limits ensure that races at least start the campaign with their attributes resembling their racial stock.
The restrictions ensure that hardy races have a high Con, that smart races have a high INT and that strong races have a high PSTR.
It should be re-emphasized that the humanoid races are referred to as ‘Anthropomorphs’.
Each race tends to have particular fortes and weaknesses; however, such tendencies are not the rule
	
There are twelve different anthro types that the players may have an opportunity to choose from.
Each type is grouped homo-typically (by shape) in such a fashion that will give respectable taxonomists fits.
These groupings are arranged by what visually appears most similar.
Some examples are: giraffes and cows are both classed as equine; kangaroos and rats are both classed as rodents; sloths and polar bears are both grouped as ursidae.
There are probably countless biological reasons for not grouping such animal types together; however, morphologically they are similar.
	
Each race is a bipedal, upright humanoid.
The races only have those special features listed in the discussion for that race.
Special abilities found in the animal kingdom, like flying or poison attacks, do not apply.
Such special abilities can only occur as random mutations when the persona’s mutations are rolled Mutations.
	
=== Requirements

These are the attributes that are required are required by the personal to be the particular anthro type. 
For example for a persona to be an canine their AWE must be at least 4 and CHA at least 3.
 
=== Adjustments

These are the adjustments made the persona’s attributes depending on their anthro type.
 
=== Age

Used to calculate the starting age of the persona in years.
 
=== Hite and Wate

Hite in centimeters and wate in kilograms.
 
=== Determine Anthro Type

A player has generated a persona with the following attributes:  AWE 6, CHA 15, CON 17, DEX 9, INT 14, MSTR 12, PSTR 6 AND HPS 42.
By comparing her attributes to the values on the minimum side of the Racial Attribute Table, this player finds she may choose from avarian, florian, humanoid, insectoid, rodent and PSH (pure strain human).

//table 4.2
include::ROOT:partial$anthro_type_selection_table.adoc


// here is where to locate an ifdef with includes for all the anthros

