= Aquarian

Insert image Aquarian protesting hooking


<h2 class="tablepress-table-name tablepress-table-name-id-9">Table 4.5 Aquarian Data</h2>
<span class="tablepress-table-description tablepress-table-description-id-9">Data for creating a brand new aquarian player persona.</span>

<table id="tablepress-9" class="tablepress tablepress-id-9">
<tbody class="row-hover">
<tr class="row-1 odd">
	<td class="column-1">Requirements</td><td colspan="2" class="column-2">Nil</td>
</tr>
<tr class="row-2 even">
	<td class="column-1">Adjustments<br>
</td><td class="column-2">+2 AWE; +2 DEX</td><td class="column-3">-2 on all attributes when out of liquid.</td>
</tr>
<tr class="row-3 odd">
	<td class="column-1">Age</td><td colspan="2" class="column-2">5-10 (4+1d6) years</td>
</tr>
<tr class="row-4 even">
	<td class="column-1">Hite and Wate</td><td class="column-2">Hite (cms)</td><td class="column-3">Wate (kgs)</td>
</tr>
<tr class="row-5 odd">
	<td class="column-1">One size fits all</td><td class="column-2">150+(6 x d20)-50</td><td class="column-3">60</td>
</tr>
</tbody>
</table>

Aquarians can also be referred to as Homo Pisces
They are basically fish people
It would be expected for an aquarian to have webbed hands, webbed feet and a scaly covering for skin.

An aquarian persona can choose to appear as one of many aquatic life forms
Some examples are shark, goldfish, octopus, salmon, viper, sea cucumber, anemone or sea star
Remember that regardless of the descriptive aquarian type chosen, the persona remains a bipedal humanoid that possesses no special abilities other than rolled mutations
For example, an aquarian fashioned after an electric eel would not have an electric shock
Some aquarians from popular fiction are mermaids, Aquaman, Flipper, Abe Sapien and the Creature From the Black Lagoon.

Aquarians are very limited in that they can only be played easily in the milieu which they were spawned
The aquarians are aquatic life forms and are not capable of prolonged stays in gaseous environments
Fishoids may temporarily leave their liquid environments after hyper-circulating (a process of super-soaking their gills) for at least ten minutes
An aquarian can survive in a gaseous atmosphere for one minute per point of CON
There are special environmental suits that aquarians can obtain to prolong their stay out of water.

Aquarians suffer many out-of-liquid penalties regardless of what equipment they have
The lack of buoyancy out of water makes gravity effects much more severe for aquarians
This race moves at -25% when on normal gravity land
They also suffer a severe penalty of -2 on all attributes
Players running aquarians should keep two sets of data, one for in the water and one for on land
The -2 on all attribute penalty will alter movement rate, combat tables and mutations
Note that the attribute penalty may keep some aquarians permanently in the water.

Aquarians are quite familiar with low or zero gravity environments
In such environments, they suffer no attribute penalties and can move at +30%
For further information on low gravity, see Chapter 19:  Special Terrain.




