== Anthros ==
:awestruct-layout: base
:showtitle:
:prev_section: defining-frontmatter
:next_section: creating-pages
:toc: 
:toclevels: 4

==== trying out stuff on this page 

there are three races in EXP. Athros, aliens and robots. 

.The Three Races
* Anthros
* Aliens
* Robots

Anthros are bipedal upright quad limbed head on the neck hominids that we are humans are most familiar with.
It is good the think **boldly** so that we can go **boldly** where no one has imagined before. 
Humans find this easiest when their avatar is a humanoid. 

==== Pain In the Ass Front Matter

I find that the front matter is very confusing. 
Should each title be = or ==?
It seems to matter to the TOC but not anything else. 

[source,java]
----
== Anthros ==
:awestruct-layout: base
:showtitle:
:prev_section: defining-frontmatter
:next_section: creating-pages
----

Does not seem to function differently from:

[source,java]
----
= Anthros =
:awestruct-layout: base
:showtitle:
:prev_section: defining-frontmatter
:next_section: creating-pages
----


But does that ever mess up the toc.

==== here is some more skanky shite

:app-name: pass:quotes[MyApp^2^]

The variable (attribute in asciifuck) app-name = {app-name}

Here we will fuck with app-name.

[subs=attributes+]
----
{app-name}
----

Which of course did nothing because literally none of the examples work.

[horizontal.properties%step]
property 1:: does stuff
property 2:: does different stuff