= Wetware

Wetware refers to the biomagical, wet and mushy elements of Sciency Fiction.
In EXP's generic mythos wetware is limited to psionic mutations and phenomic mutations. 
The mutation storey is deeply rooted in Sciency Fiction.
In reality, biological mutations are mostly fatal.
In the Sciency Fiction world of EXP, mutations are just plain fun.

Mutation is not merely the biological transformation of DNA.
Mutations represent complicated interactions with the physical, and non-physical worlds.
The mutation effects do not just change the persona, but the Sciency Fiction world in which they exist. 
No attempt is made to explain them scientifically.
Mutations are part of the game and fall into the 'black box' category and pseudo-scientific post-factualization. 

NOTE: Wetware has suffered many different titles over the decades: biologics, bioware, and plain old mutations. 

== Mutations and Families
The meat, metal and metamorphosis of mutations.
Mutations are generally an anthro thing, but all family types can enjoy mutation effects.
The nature of a mutation differs between anthros, aliens and robots. 

* anthro mutations are unique *mutations* of that persona and are unreproducible
* aliens mutations are species-wide *evolutations* that have evolved over generations
** an individual alien persona could develop a unique and personal mutation on top of her evolutations
* robots mutations are unique *malfunctations* of that persona and are unreproducible

=== Anthros
Anthro mutations represent changes in persona DNA that create unique physiologic structures in the persona.
Mutations can be innocuous, powerful or deleterious.
Anthro mutations are the stuff of Sciency Fiction legend from books to movies.
Personas can start out having full awareness of their mutations.
Or the mutations could be activated by a story trigger.
Some refs have personas acquire their mutations through gameplay, i.e., skinny dipping in that glowing creek.

Anthros that have mutations are considered mutants. 
The nature of mutants in a society depends entirely on the milieu of the campaign.
Mutants may be wholly accepted or wholly reviled.
In general psionic mutations harbour an element of suspicion or distrust.

=== Aliens
Alien mutations are abilities that are part of their alien species.
Evolving an alien generates not just a persona but an entire species.
Mutations that are part of a species are called __evolutations__.
The persona will have the mutation effect, and it will also be species-wide.
Not every member of the species will have every mutation effect.
For example, if an alien persona has the mutation time stop, it is unlikely every alien in the species does.
Alien personas can also acquire mutations de novo during gameplay.

=== Robots
A robot mutation is not an alteration in the persona's DNA.
Robots don't have mutations per se, but they can have peripherals with mutation effects.
Robots generate mutations when being fabricated or by malfunctioning in unique ways. 
The mutation effect can be a bespoke peripheral or a malfunctioning peripheral.
Mutation effects that are harboured within a robot are called __malfunctations__.
Usually, it is clear whether the mutation effect arises from malfunction or intention.


== Mutation Domains
Mutations have two broad domains: psionic and phenomic.
These were originally called mental (psionic) and physical (phenomic) mutations. 
As a nod to https://en.wikipedia.org/wiki/Metamorphosis_Alpha[Metamorphosis Alpha,window=_blank] the distinction between the physical and mental has been maintained.

* xref:wetware:phenomics.adoc[Phenomic Mutations,window=_blank]
* xref:wetware:psionics.adoc[Psionic Mutations,window=_blank]

=== Phenomics
Phenomic mutations are what most readers associate with mutations.
These mutations change the persona's body allowing it unusual powers. 
Phenomic mutations function in the physical space and do not reach into the thinkspace.
There is no hiding phenomic mutations.
Even phenomic mutations that create new internal organs alter the mutant's appearance.

=== Psionics
The persona's brain is the focus of psionic mutations.
The persona manipulates the world through her brain and her Mind attribute.
Psionic mutations have other monikers like psionics, psychic powers, tele-this, tele-that, and mentals.

====
Psionic mutations rarely have any external physical reveal on the persona.
====

Psionic mutations function through the thinkspace of the xref:appendices:generic_mythos.adoc#_the_spaces[Spaces,window=_blank].
These mutations may impact the physical space, but the effect travels through the thinkspace.
The thinkspace is a faux concept where organic consciousnesses exist. 
In this space, consciousnesses interact, allowing for extrasensory perception and mind control.
Psionic mutations do not alter the persona's appearance, making these mutants indistinguishable from other personas.

Psionic mutations require concentration of the mind, like lifting a weight involves contraction of the muscles.
The attribute that powers psionic mutations is xref:attributes:mind.adoc[Mind,window=_blank].

== Acquiring Mutations
The susceptibility of personas to mutation is affected partly by <<_persona_families,family>> and partly by choice.
The families have varying frequencies of mutation based on elements of popular fiction and the ability of the species to adapt to mutation.
The players have input as to whether their persona mutates or not.
If the player desires to mutate, she can double her persona's chance of mutation.
This desire can be a source of backstory like the persona went skinny dipping in that glowing creek.

=== Start Up
These are mutations that the persona acquires while being generated. 
The frequency of start-up mutations depends on the persona family and type.
For anthros, the player can influence the mutation chance by choice. 
Each <<_mutations_and_families,family>> has a different approach to mutations. 

NOTE:

Defects do *not* count as mutations.
If a persona gets three phenomic mutations and her first mutation is the defect Sepsomegaly, the player has three more mutation rolls.

=== De Novo
These are new mutations or mutation effects acquired during gameplay.
New mutations are rare during a campaign.
Pharma that generates mutations is rare.
Exposure to toxins and radiation is more likely to be lethal than mutagenic.
Adding de novo mutations should be a carefully integrated part of the milieu or campaign. 

== Considerations
Following is a list of edge cases that have arisen over decades of play.
Mutations are biologically magical and create a whole host of complications, considerations and confusions. 
The referee and players will use their improv skills, making mutations both interesting and fun.
What follows is a disjointed collection of past  decisions around mutations. 

* Fresh personas (first level anthros, aliens, and robots) are limited to *ONE* defective mutation of any type.
This new suggestion prevents mutation overwhelm syndrome, especially in anthro humanoids. 

* The mutant must be conscious to use a mutation unless stated otherwise by that specific mutation.
Any degree of consciousness is sufficient for the mutant to use her mutation.

* The mutant cannot turn off a mutation with a duration of constant.
The mutation effect will be functioning whether the player wants it or not.

* Restraints will only affect phenomic mutations.
Psionic mutation usually cannot be stopped by binding a persona's paws.

* The source of a psionic attack may be very difficult to determine.
Very few psionic mutations offer any indication that the persona is employing one.

* Psionic defence rolls are subconscious.
The brain instantly defends against intrusion, whether it is malevolent or benevolent.

* The referee should delicately balance the power of mutations with subtle inconveniences, but mutations should never be useless.

* Powerful mutations can have campaign-altering effects.
For instance, a time stop mutation may attract aliens that manipulate time.
A planal holdaway may cause trouble with the special drives.

* No terrain barrier can block a mutation traveling from one mind to another.
ESP, gyrokinesis, and telekinesis can pass through any barrier if the mutant can detect the target thinkspace.
Those mutations which manipulate the environment to attack a target, such as mental blast, or launchable quills, are subject to terrain effects.

* The target of a psionic mutation is whatever the mutant intends to affect.
The word 'target' is generic for whatever the mutant wants to affect.
The target is most often another persona but could also be an inanimate object.

* Mutations improve as the persona increases in experience level.
Range, damage, area of effect, increasing control usually improves with each new EXPS level.
Using level-adjusted attributes is the most common way to implement level improvements, i.e., MND + EXPS Level or CON + EXPS Level.

== Generate Mutations

=== Any Mutation

include::wetware:partial$mutation_type_raw.adoc[]

=== xref:wetware:phenomics.adoc#_generate_type[Phenomics,window=_blank]

=== xref:wetware:phenomics.adoc#_no_defects[Phenomic No Defects,window=_blank]
 
=== xref:wetware:phenomics.adoc#_combat_mutations[Phenomic Combat,window=_blank]

=== xref:wetware:phenomics.adoc#_uncombat_mutations[Phenomic Uncombat,window=_blank]

=== xref:wetware:phenomics.adoc#_defect_mutations[Phenomic Defective,window=_blank]

=== xref:wetware:psionics.adoc#_generate_type[Psionics,window=_blank]

=== xref:wetware:psionics.adoc#_no_defects[Psionic No Defects,window=_blank]
 
=== xref:wetware:psionics.adoc#_combat_mutations[Psionic Combat,window=_blank]

=== xref:wetware:psionics.adoc#_uncombat_mutations[Psionic Uncombat,window=_blank]

=== xref:wetware:psionics.adoc#_defective_mutations[Psionic Defective,window=_blank]
