= Phenomic Mutations

Phenomic mutations physically alter the mutant's body.
The effects of phenomic mutations take place within the physical space.
Phenomic mutations are not subtle and usually alter the mutant's appearance.
The changes can range from oversized ears to wings to disgusting faux organs.
Even the most cursory vet exam would expose this mutant as different.
In short phenomic mutations always have a 'tell' that makes the persona different.

.*Phenomic Mutations*
* <<_mutation_type,Any Mutation Type>>
* <<_no_defects,No Defects (start up)>>
* <<_combat_mutations,Combat Mutations>>
* <<_uncombat_mutations,Uncombat Mutations>>
* <<_defective_mutations,Defective Mutations>>

== Parameters

Each mutation has certain properties that describe what it is and how it affects play.
The attributes of each mutation are explained in the following paragraphs.
Not only should the basic feature of a mutation be recorded, but the mutation number and the page number where the mutation can be found.

=== Range
The range of a mutation indicates how far away the effects of the mutation can be delivered to a target.
Any exception to this meaning of mutation range will be specified in the mutation.
Many mutations can affect targets hexes away;
others require contact;
and some have a radius of effect.
Ranges are not devoted solely to offensive mutations, and even defensive mutations may be critically affected by range limits.

The intensity of a mutation cannot be regulated, and neither can its area of effect.
Only a single target mutation can be adjusted for different ranges from the persona.
Mutations that have areas of effect will indiscriminately affect all targets in this area of effect.

Nothing can stop a mutation which travels directly from one mind to another.
ESP, gyrokinesis, and telekinesis can pass through any barrier if the mutant has positive proof that the target exists.
Those mutations which manipulate the environment to attack a target, such as mental blast, or launch-able quills, are subject to terrain effects.

==== Distance
The most common is the ranged mutation.
Ranged mutations can be directed at any target within the range of the mutant.
The range is determined by the MND and EXPS level of the attacker.
For example, a mutation may have a range of one hex @ MND.
This means one hex per point of Mind and, with a 12 MND, a mutant could use the mutation 12 hexes away.
There are variations to this common range format.
Two hexes per MND would yield a 24 hex range with a 12 MND.
One hex per four MND would yield a three hex range with a 12 MND.
If the range includes MND and experience level, then the two are added.
A fourth level persona with a 12 MND would have a 16 hex range with a mutation that was listed as one hex per (MND + level).

==== Area of Effect
Radius ranges are spherical and use the location hex of the persona for the centre.
Thus a mutation with a ten hex radius of effect would contain all targets within ten hexes, including above and below the mutant.
The area of effect would include everything in the 20 hex diameter sphere.

==== Touch
Touch mutations are self-explanatory.
The mutant must touch the target to inflict the effects of the mutation, whether benevolent or not.
The touch must be hand, paw or claw to skin, fur or scales.
Some touch mutations can be conducted through material that would be considered conductive, like metal.
Some touch mutations may still be effective if derma-to-derma contact cannot be made.
They may be mutations with very short ranges, several millimetres, and a successful attack roll may be all that is needed to get within range.

=== Duration
The duration of a mutation almost always refers to the length of time that the mutation effects last.
If the mutant has telekinetic flight, she can stay aloft for the duration of the mutation.
Mutations usually require complete concentration on the part of the mutant.
If a mutation obviously does not require complete concentration on the part of the mutant, then the concentration need not be maintained.
Mutations that are always in constant use do not require a significant portion of the mutant's mental or physical resources.

Mutations usually last so many units per point of MND, and they may also be affected by the persona's experience level.
If a mutation has a duration of one until per MND, then the mutant can make the mutation last 12 units if she has a 12 MND.
Other variations of duration exist, and they all function identically to the range variations discussed earlier, except that units replace hexes.
Mutations with random durations are determined each time the mutation is employed.
Such mutations indicate that the mutant has set in motion physical effects which she has no control over.

==== Until Saves
If the duration is "until saves," the mutant may continue the attack until the victim saves or is dead.

==== Permanent
When the duration says "permanent." it indicates that the effects won't dissipate on their own accord.
For instance, permanent healing of HPS means that they will not disappear after a certain number of units, but it does not mean that the mutant has a cache of indestructible HPS.

==== Constant
Most mutations can be stopped whenever the mutant sees fit, except those mutations that have a "`constant`" duration or an "`until dead`" duration.
These mutations will function until the mutant is dead or has the mutation excised.

=== Frequency
The frequency of the mutation indicates how often it can be used during a daily cycle of the mutant.
The frequency assumes a 24 hour day (see Chapter 12: Time and Movement) where the mutant sleeps around eight hours each day.
If the mutant is in a situation where there is no planetary rotation or one where there is no 24-hour cycle, a complete rest (eight hours`' sleep) will be equivalent to the completion of a daily cycle.

Most mutations can be used several times a day, depending on the MND and level of the mutant.
The more powerful the mutation, the less frequently it can be used each day.
If the frequency of a mutation is one per four MND, a persona with a 12 MND could employ it three times each day and would have to rest eight hours before using it again.
For this type of mutation, rest for the brain is essential.
Unless otherwise stated, a mutation can be used at least once a day.
This includes mutations which have very low frequencies (e.g.
One per 13 MND).
This mutation could be used once a day, even by a persona with an MND of six.

Mutations that can be used more frequently are labelled "as needed" and just as the title states. 
The mutant can use such a mutation as it is needed.
"Constant" mutations are usually defects, and they constantly project their effects regardless of what the mutant is doing.
Constant mutations always function whether the mutant is asleep or awake.

Mutations cannot be stored.
A mutant cannot use a mutation more often one day than the next because she saved some uses from the previous day.
The mutant may use the mutation no more than the frequency states, and each use is cumulative until she rests.
Mutations cannot be compounded to double an effect.
The mutant can only use one mutation at a time unless one of the mutations has a "`constant`" or "`as needed`" frequency.

The mutant has used a mutation whenever the effects start.
Even if the target saves and the mutation has no effect, the mutation has been used.
If the mutant voluntarily stops the mutation, then it has been used.
If the mutant switches from one target to another, this will usually indicate another use.


== Mutation Type

include::wetware:partial$phenomic_list_all.adoc[]

== Mutation List

=== Acidic Enzymes 

[horizontal]
Range:: 1h per Adjusted STR
Duration:: Constant
Frequency:: Alternating Units
General Bonus:: Combat Ratio +2

This mutant has a muscular hyperactive stomach that produces excess amounts of acid and digestive enzymes.
The mutant can eject spittle of corrosive acids.
The mutant's esophagus, mouth and lips are covered in thick protective skin, and her teeth are small and gnarled.
Her thickened upper digestive tract protects the mutant from the corrosive acid, but the rest of her body is vulnerable.
Spitting on herself would give the mutant severe acid burns.

In the duress of combat, she can release one spittle every other unit.
If the mutant wins an attack roll, her spittle will burn her target.
The acid spittle inflicts 2-16 (2d8) HPS of damage plus one hit point per EXPS level.
Thus a 3rd level mutant with a 12 STR could spit acid 15 hexes and inflict 5 to 19 hit points of corrosive damage.

Damage from this digestive acid attack permanently damages organic tissues, preventing them from spontaneously regenerating.
The digestive juices do not affect inorganic materials.
A food culture will not grow after being bitten by a creature with this mutation.
The mutant will probably have a penchant for more spicy foods.
Swallowing acidic compounds will not affect the mutant much.
Kissing is out of the question unless her partner also has this mutation.

=== Adaptation 

[horizontal]
Range:: Persona Only
Duration:: Special
Frequency:: Constant
General Bonus:: Combat Ratio *3

The immune system of this mutant works on a macroscopic level. 
Adaptation allows the mutant to develop immunity to any threat from the physical space.
Her body can adapt to fire, physical force, poison, radiation, and diseases.
Adaptation is automatic, and her body will attempt to transform itself to prevent further damage.
If an attack harms the mutant, there is a chance that her body will adapt to the attack.

The mutant's Constitution and Intelligence determine if she will adapt to an attack. 

[discrete]
=== Adaptation Chance
.% chance = CON + INT + EXPS Level
****
A 4th level mutant with a 12 CON and a 11 INT has a 27% chance of adaptation.
****

If the player wins the roll, the persona will adapt to the threat.
A bacterial infection could be pushed out through her skin or redirected to her stomach for digestion.
A punch to the face would restructure her skin and muscle to counter the next punch.
The mutant's nervous system would safely ground an electro weapon attack.
Her lungs would trap a poisonous gas and excrete it as sweat.
However, the mutant's body may recognize a healing pharma as foreign and reject that as well.

Adaptation does not differentiate a friend from a foe. 
So even benevolent pharma could be blocked by this super immune system.
Adaptation does not have the best memory either.
Most adaptations will disappear after the mutant has a restful sleep.
There is a small chance that an adaptation will remain permanently.

There is a 1% chance per EXPS Level of the mutant becoming permanently adapting to the threat.
So the mutant could become permanently immune to punches, lazer bolts, or healing pharma.
The permanent adaptations are particular.
The mutant would be immune to damage by punches, but not claws or talons or clubs.
The mutant would be immune to a healing pharma pill, but not a healing pharma injection.

The mutant can stay permanently immune to one attack per EXPS Level. 
A fifth level mutant could have permanent immunity to 5 attack types. 
If she develops permanent immunity to a 6th adaptation, the mutation will forget the oldest one.  

=== Attraction Odor 

[horizontal]
Range:: 1km per STR
Duration:: Special
Frequency:: Constant
General Bonus:: +2 CHA, +15 on negotiation rolls

Attraction odour makes this mutant very interesting to a specific type of persona. 
The mutation uses pheromones, chemotactic agents, tasty aromas, vibrations, and thought patterns.
These factors work together to attract less intelligent personas to the mutant.
A specific flying insect may surround the mutant. 
A herd of nomadic fauna may change course to follow her.
A lone, hungry alien may attack the mutant because she simultaneously resembles dinner and love. 

Attraction odour works best on flora or fauna, but more intelligent personas can succumb as well.
The attracted persona will seek out the mutant. 
When the persona finally finds the mutant, the creature will realize neither food nor a mate is present.
If the attracted persona wins a poison roll, she will most likely wander off disappointed. 
The intensity of the poison is equal to the mutant's adjusted Charisma.
It is also possible the attracted persona may find something else to eat at the same time.
The attracted persona will hang around until they finally win their poison roll. 

Attraction odour should not result in a constant swarm of giant deadly fauna attacking the expedition.
The referee should play the mutation as an annoying inconvenience, with occasional episodes of violence.
It is also possible that nothing is nearby to be attracted to the mutant.
Attracted personas usually show up when they will complicate things the most.  

include::hardware:partial$effected_persona_type.adoc[]

=== Arms 

[horizontal]
Range:: Fingertip
Duration:: Permanent
Frequency:: Constant
General Bonus:: Defect, DEX penalty

The mutant is now the proud owner of an extra 1-4 randomly moving arms.
The bonus arms are free willed and infuriating.
They follow their own volition and are not controlled by the mutant.
The arms may scratch the persona's ear, grapple her nose, make an obscene gestures or grab and drop items.
Binding down the arms is not work.
These defective arms will relentlessly struggle and exhaust the mutant.
All mutants with this defect are ambidextrous.

Arms is both an amusing and serious defective mutation.
Each extra arm has a penalty of -1 on the mutant's Dexterity attribute.
A mutant with two extra arms and a 14 DEX would reduce her DEX to 12.
This penalty is the same regardless of the location of the extra arm.

include::combat:partial$hit_location_snap.adoc[]

Surgically removing the extra arms does not improve her confused Dexterity attribute.
The mutation mental control over physical state will allow the mutant to control these autonomous arms.

include::wetware:partial$a_defect_disclaimer.adoc[]



=== Body Structure Change 

:art: cubist_mutation_flesh_blob.png
:width: 250px
:snark: Change will do you good
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Humanoid parts shaped into  a cube.
include::ROOT:partial$articulate.adoc[]

[horizontal]
Range:: Persona
Duration:: 1 Hour per Adjusted CON
Frequency:: 1 per 6 Adjusted CON
General Bonus:: +100 on disguise rolls

This mutant has complete control over her unusually pliable body.
The mutation body structure change comes with an additional layer of cosmetic musculature, flexible bones, and controllable connective tissue.
The mutant has complete control over the shape and location of her muscles, skin, bones, and internal organs.
She can adjust her appearance by altering her nose and changing her hair's length and colour. 
She can retract all her arms and limbs, turning into a ball-shaped thing.
She can restructure her internal organs to assist a veterinarian in surgery.

The mutant can adjust her hite but cannot alter her wate.
She cannot excise flesh through sheer will.
She cannot improve her attributes.
The mutant cannot compromise any essential anatomical parts.
She must retain a mouth to breathe and all those other essential holes.

Regardless of what she is restructuring, the process takes 1-4 minutes.
Swapping her arms and legs may take less time than slightly altering her nose.
The body structure change is gross to watch and quite noisy. 
While restructuring, the mutant becomes malleable and vulnerable.
Any damage inflicted on the malleable mutant is doubled. 
An attack that delivers four hit points of damage would inflict eight hit points of damage to the mutant.

When the mutation reaches the end of its duration, the persona rapidly returns to her previous state.
There is a 1% chance per hour in the restructured state that the mutant will stay in the new shape.
A mutant that changed her hair colour to blue for 5 hours has a 5% chance of being left with blue hair.

=== Carapace 

[horizontal]
Range:: Skin Deep
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Special

The carapace is an unsightly buildup of thick semi-pliable skin.
The mutation offers a protective covering that reduces the damage and impairs appearance.
A carapace makes the mutant more challenging to hit and damage.
The thicker the carapace, the more defence is offered to the mutant.

The Defence Rating adjustment changes the mutant's base Defence Rating. 
With a partial carapace, the mutant's base AR would increase by 99.

A partial carapace has an Defence Rating adjustment of +99.
A mutant with a partial carapace would have a base AR of 599.
Beyond partial carapace, the mutant cannot wear any other armour.

If an attack roll is successful, the carapace will reduce the damage she takes.
The total carapace halves the damage from kinetic attacks.
If the mutant is supposed to take 12 HPS from a punch, it would only inflict 6 HPS.

Covering the mutant in a thick protective layer of crusty skin impairs the mutant's Charisma and Dexterity.
If the mutant has her carapace removed, her Dexterity attribute will improve, but not her Charisma.

Sometimes players want to grow their carapace, thickening it over time.
An easy way to manage this is to have the player record her initial carapace table roll.
The player adds +5 to the initial carapace roll for every new experience level.
The carapace will get thicker as the carapace table roll increases.

A mutant cannot thin her carapace over time.

include::wetware:partial$phenomic_carapace.adoc[]

=== Chameleon 

[horizontal]
Range:: Persona Only 
Duration:: As needed
Frequency:: As needed
General Bonus:: Combat Ratio +5, +25 on sneaky rolls

The mutant's skin has photo-detector cells and chromocytes.
The combination of these two skin cells allows the mutant to blend into the surrounding environment.
Chameleon skin is continually attempting to conceal itself by matching the background.
This mutant's skin will even change colour to match the inside of her clothing.
Bare skin is constantly changing colour with this mutation.

The mutant must be naked to hide with her chameleon skin completely, 
The naked and still chameleon mutant can be very difficult to see.
The mutant is not invisible, but a persona must be actively searching for her to detect her.
When actively searching for a chameleon mutant, a persona must win an Awareness roll to see her.
The mutant can move and remain hidden.
The slower and more tactically she moves, the harder she is to see. 

Chameleon cannot hide the mutant from non-visual sensors like radar, sonar, good ears or long noses.

=== Decoy 

[horizontal]
Range:: Special
Duration:: Not Applicable
Frequency:: Special
General Bonus:: None

The decoy is a detachable tail-like appendage that can be dropped by the mutant at will.
The decoy looks like a lump of succulent flesh attached to the mutant's hindquarters.
The decoy proves most useful when evading pursuit.
The mutant can drop the decoy at any time.
Dropping the decoy is not painful and does not harm the mutant.
If the decoy is already exposed, no time is lost dropping the meat chunk.

The decoy is a succulent treat for any lower Intelligence personas chasing the mutant.
Any persona with Intelligence less than 5 will automatically change course towards the dropped decoy.
The decoy does *not* attract any personas while attached to the mutant.
Personas pursuing the mutant with an INT greater than 5 get to make a poison roll to avoid being distracted by the decoy.
The intensity of the attraction is equal to the persona's Charisma.
Any mutant chasing, or within range of chasing, the mutant must make the poison roll or chase the decoy.

Those that are affected by the aroma will become insatiably hungry and will devour the decoy madly.
It is not unknown for flora and fauna to fight each other over the tasty morsel.
Whoever gets to eat the decoy is in for a nasty surprise.

The ingested decoy is full of a killing poison.
The poison has an intensity level equal to half the mutant's Strength.
The decoy diners will have to recover from the effects of poison.

The decoy will regenerate after one night's restful sleep.
When attached, the decoy is a part of the mutant's body.
Damage to the decoy damages the mutant as well.  
For the record, the decoy's wate is 3% of the mutant's wate. 
The wate of a decoy will almost always become an issue at some point during a game.

In social situations of great duress, the mutant's decoy may spontaneously drop from her body.

=== Density Manipulation 

[horizontal]
Range:: Persona Only
Duration:: 1 minute per Adjusted CON
Frequency:: 1 per 4 Adjusted STR
General Bonus:: +15 on wate related rolls

The mutant can equilibrate the density of her body to match that of the surfaces she is standing on.
Density matching is achieved through bladders that can fill with gas, liquid, or solids.
By manipulating these internal bellows, the mutant can alter her density.
The mutant may appear slightly larger and puffier, shorter and condensed, but her body shape does not radically change.

Density control lets the mutant match the density of liquids or gases, allowing her to walk on them without breaking the meniscus and sinking.
She could also increase her density to that of a solid surface, making her very difficult to displace or damage.
Once this equilibrium is reached, the mutant may move about freely upon the surface unless heat, cold or acidic properties can damage her.
This would allow the mutant to walk on water, stand on a cloud, or hunker down on a rock.
Density control does not allow the mutant to fly by walking on air. 
There must be some interface between the media for the mutant to alter her density.

Increasing density makes the mutant a bit smaller and stout looking.
The denser mutant reduces crushing and penetrating damage by half. 
There is no protection offered from energy attacks like lazers, fission or fusion. 
When density has been increased to prevent being moved, the mutant can double her STR for that specific attribute challenge.
She cannot push back at double her STR, but she can stand her ground. 
Increasing density decreases the mutant's movement rate by half.

Decreasing density makes the mutant look a bit larger and puffier.
The less-dense mutant reduces damage from crushing, falling and concussion attacks. 
The decrease in density allows the mutant to convert damage into translational motion.
In short, she flies away instead of being damaged. 
Whenever an attack roll is successful on the less dense mutant, the player will roll 1-6 (1d6).
The higher the number, the less damage that is inflicted and the further she flies.
The mutant reduces damage by 10% and flies one hex per point the 1d6 rolls.
If the player rolls a three, the persona's damage decreases by 30%, and she lands three hexes away.
Decreasing density has been used to get a persona across a crevasse.

=== Diminished Sense 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Defect

include::wetware:partial$a_defect_compassion.adoc[]

Diminished senses are serious disabilities that the persona is challenged with.
Effective gaming with a diminished sense defect should be rewarded with large amounts of experience points.
The defects are difficult toroleplayaround, and the referee must be constantly aware of them.
Cures, or replacement parts for the persona should be one of a priority of one of the referee's earlier scenarios.
This mutation is a defect and does not count as a start up mutation.
The player receives another roll on the Phenomic Mutation Table.

include::wetware:partial$a_defect_disclaimer.adoc[]

include::wetware:partial$phenomic_diminished_sense.adoc[]

Sixth::
A diminished sixth sense prevents the mutant from connecting her consciousness to the Think Space.
This is both a defect and a blessing.
The mutant cannot have any psionic mutations, and has no psionic abilities.
The mutant loses all existing psionic mutations and cannot generate any further psionic mutations. 
Since her interface between consciousness and the psionic realm is absent the mutant is immune to many psionic mutations.
Those mental attacks that attack via the thinkspace will have no effect.
E.S.P., Mental Control, Hostility Field, and Sociability Field are examples.
Mutations that manipulate the environment around the mutant will have normal effect.
This includes mutations like Time Stop, Molecular Disruption and mental blast.
The persona's Mind score is decreased by 2 points and her Awareness score is decreased by 1 point.

Humour::
A diminished sense of humour keeps the mutant from making, understanding or reacting to humour.
Lacking a sense of humour is not about taste.
The mutant does not have a weird, dry, sarcastic, or sardonic sense of humour. 
This mutant does *not* have a sense of humour. 
The mutant may understand the concept, but exercising or understanding it not possible.
This persona's Charisma score is reduced by 2 points.

Style::
A diminished sense of style makes the mutant completely unable to dress, design, or decorate in any way possible.
The mutant does not dress ironically, cutely or idiosyncratically.
The mutant dresses badly, inappropriately and somewhat offensively.
This makes the persona a tragic cook, painter, stylist, writer, and haute couture is incomprehensible.
This persona's Charisma score is reduced by 1 point and her social standing is reduced by 30 percent.

Smell/Taste::
A diminished sense of smell and taste is not just about cooking and body odour.
The mutant is unable to detect noxious poisons, or smelly surprises.
This impairs the ability of the mutant to detect ambushes, personal body odour or the sulphur of a natural gas leak.
This defect does not affect a canine anthro's ability to detect radiation.
This persona suffers an Awareness score reduction of 1. 

Hearing::
Hearing impairment is keeps the mutant from detecting any audio signals.
If this mutation is of concern to the player the referee should immediately allow a re-roll.
Outdated terms for hearing impairment includes deaf and hard of hearing.

This mutant automatically has a signing language.
She can teach her signing language to one expedition member per month of game time.
Sonic attacks will inflict one quarter damage to this mutant.
This persona's Awareness score is reduced by 2 point.

Touch::
A diminished sense of touch impairs the tactile abilities of the mutant.
This is affects purely tactile receptors regarding touch. 
Other tactile receptors that allow the mutant to walk and swallow are unaffected.
A diminished sense of touch also decreases the mutant's perception of pain.
Damage that involves physical pain, which is most damage, is reduced by half.
The mutant will be bad a fine motor activity and hugs are not very effective.
The mutant's Dexterity score is reduced by 2 points.

Sight::
Diminished sight impairs the mutant from detecting visual signals.
If this mutation is of concern to the player the referee should immediately allow a re-roll.

A blind mutant will have a limited echolocation ability that allows her to move very slowly and grasp nearby objects.
Even with this limited echolocation the mutant is unable to perceive light or any other visual input.
How does a player run a visually impaired persona?
Only a most experienced player should be given this mutation.  
Some groups have players with blinded personas face away from the gaming table. 
The mutant's Awareness score is reduced by 4 points and her Dexterity score is reduced by 2 points. 

=== Double Physical Pain 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Defect

The mutant has no threshold for pain, and her pain receptors are hypersensitive.
Any pain based damage is increased by 2-8 (2d8) hit points.
Pharmaceuticals that relieve pain last half as long for this mutant.
Note that this mutant much resembles a hypochondriac.
This mutant heals twice as fast as other personas when recuperating.
Most personas heal one hit point each day. 
This mutant heals two hit points each day.

include::wetware:partial$a_defect_disclaimer.adoc[]

=== Edible Tissue 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Special
General Bonus:: None

On this mutant's belly is a 4 cm thick buildup of nutritious and tasty regenerating flesh.
The flesh is a muscly, slightly denatured, and stocked with all the essential nutrients.
To sustain herself, the mutant tears strips of edible tissue off her belly.
Each strip is a yummy snack. 
The edible tissue supplies a day's food for the mutant.
The tissue is inedible to other personas and tastes repulsive.

The edible tissue grows back after a restful night's sleep. 
Mutant must keep hydrated (drink water) and expose her edible tissue to light during the daytime. 
The mutant can still eat and enjoys regular food. 

=== Electric Shock 

[horizontal]
Range:: 1/2h per Adjusted STR
Duration:: Not Applicable
Frequency:: Alternating Units
General Bonus:: Combat Ratio +4, +13 on resuscitation rolls

A series of organs found in this mutant's torso generate and store a powerful electric current.
This stored electric charge can be conducted down the mutant's limbs and delivered to an opponent.
The mutant can either touch her target or arc the current through air.
Both attacks create bright blue sparks and make a crackling noise.

The touch attack delivers more damage to the target. 
If her attack roll is successful, the shock touch delivers 7-16 (1d10+6) HPS of damage plus one hit point per EXPS level.
Conductive armour gives the mutant an attack roll bonus of +100.

The ranged attack is convenient but delivers less damage to the target.
If her attack roll is successful, the shock bolt delivers 3-12 (3d4) hit points of damage plus one hit point per EXPS level.
A 4th level mutant with a 10 STR could launch a lightning bolt seven hexes and inflict 7 to 16 hit points of damage.

Robots usually take double damage from electrical attacks. 

Both the ranged and the touch electric shock are Shoot attacks. 
They inflict damage without physical effort by the persona.
The current generating organs need time to recharge.
An electric shock can attack every other unit.

The current generating organs can also absorb electric shock attacks directed at the mutant.
Electricity based attacks inflict half damage on this mutant.

===  Enthalpy Attack. 

[horizontal]
Range:: 1h per Adjusted STR
Duration:: Not Applicable
Frequency:: Alternating Units
General Bonus:: Combat Ratio +3

This mutant has brine like blood and an overactive cardiovascular system.
Her vascular system forces the briny blood to the surface of her skin, where sweaty evaporation cools it.
The mutant has a cold body, and being beside her is like being beside an air conditioner on full blast.
The mutant cools anything within a one hex radius.
A mutant with enthalpy attack prefers warmer climates, but is not bothered by cold environments.

The mutant can also unleash a blast of freezing cold air.
Icicles and hail often accompany this freezing breath attack.
If the player makes a successful attack roll, the enthalpy attack inflicts 2 to 16 (2d8) HPS of damage, plus one hit point per Experience Level.
The air conditioning is constant, but the breath attack needs one unit of rest.

Fire and heat-based attacks have their damage reduced for this mutant.
The mutant's cold production counters the effect of flame and heat attacks.
Cold based attacks inflict normal damage on a mutant with this mutation.

=== Fat Cell Accumulation 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Defect, Combat Ratio *0.9

This mutation causes an increase in fat cells' number and size in a specific location on the body (it's not a malignant tumour).
The blob of fat will always be harmless, noticeable, and embarrassing.
If surgically removed, it will aggressively grow back in one to four (1-4) days.
The growth has a CHA penalty of minus 0 to 3 (d4-1) points, but no other penalties can apply.
If the fat cell accumulation is on the mutant's face, they will not suffer any AWE penalty or attack roll penalty.

include::wetware:partial$a_defect_disclaimer.adoc[]

NOTE: How did you get that hump? What hump?

include::combat:partial$hit_location_anthro.adoc[]

=== Gas Generation 

[horizontal]
Range:: Up to 5h radius
Duration:: 0-3 (1d4-1) units
Frequency:: 1 per 5 Adjusted CON
General Bonus:: Combat Ratio *3

This mutant can release a noxious spume of gas from her mouth or some other orifice.
The mutant is impervious to her generated gas type.
The poison gas intensity is equal to half the persona's Constitution score, plus one per Level.
A 3rd level mutant with a 14 CON would exhale intensity ten poison gas.
Under extreme duress conditions, or after consuming certain foods, the mutant may release gas unintentionally.

The descriptions below all suggest the gas is green in colour.
The player can choose any noticeable cloud colour they like.
This mutation cannot generate invisible or undetectable gas, and where the gas emits from is obvious.
If you need a random xref:hardware:appearance.adoc#_colour_your_whirled[Colour,window=_blank].

include::wetware:partial$phenomic_gas_generation.adoc[]

Death::
This mutant releases a highly toxic green cloud of death.
All organic personas within the area of effect must make a poison roll.
Targets that lose their poison roll take 1-4 (1d4) hit points per level of intensity of the poison.
Targets that win their poison roll take 1/2 damage.
Intensity 10 killing poison would inflict 10-14 (10d4) hit points of damage. 

Nausea::
This mutant releases a highly toxic green cloud of vomit-inducing stench.
All organic personas within the area of effect must make a poison roll.
Targets that lose their poison roll immediately start retching with a ferocity that incapacitates them.
Targets that win their poison roll are also retching but can still run from the cloud.
Incapacitated targets are defenceless for 1 unit per level of intensity of the attack.
Intensity level 10 nausea poison would incapacitate the targets for ten units.

Paralysis::
This mutant releases a highly toxic green cloud of paralyzing gas.
All organic personas within the area of effect must make a poison roll.
Targets that lose their poison roll suffer muscle weakness that paralyzes them.
Targets that win their poison roll can crawl at one h/u.
Incapacitated targets are defenceless for 1 unit per level of intensity of the attack.
Intensity level 10 nausea poison would paralyze targets for ten units.

Pharmaceutical Effect::
This mutant releases a green cloud with a pharma effect.
All organic personas within the area of effect must make a poison roll.
Targets that lose their poison roll are affected by the pharma.
Targets that win their poison roll are unaffected by the pharma.
Beneficial pharma is ineffective if the target wins her poison roll.
The pharma is also ineffective on the mutant spewing it out.
The duration of effect is determined by the xref:hardware:pharma.adoc[Pharma,window=_blank]. 

Unconsciousness::
This mutant releases a highly toxic green cloud of unconscious gas.
All organic personas within the area of effect must make a poison roll.
Targets that lose their poison roll fall unconscious immediately.
Targets that win their poison roll may escape the gas cloud.
A poison roll must be made every unit the target is within the gas cloud.
Targets remain unconscious for 1 minute per level of intensity of the attack.

=== Haste 

[horizontal]
Range:: Persona Only
Duration:: 1u per Adjusted CON
Frequency:: 1 per 4 Adjusted CON
General Bonus:: Combat Ratio *2

The mutant's nervous system has highly conductive neurons, both centrally and peripherally.
When haste is activated, the mutant's body with an adrenaline-like super hormone allowing her to operate at double speed.
The mutant does everything at double speed during the mutation effect.
Skills, and tasks, can be completed in half the time with no penalty on task rolls.
The persona doubles her movement rate with no increased risk of crashing.
If the weapon is capable of doing so, the mutant can double her attack rolls per unit.
Once begun, the mutant cannot stop haste, and all activity will be done in double time, or not at all.
The mutant also burns through pharma at double speed when haste is activated.

The mutant cannot use haste continuously, or she would die from using up essential nutrients.
A bout of haste requires 1 hour of intentional rest or  2 hours of unrestful exertion.
Haste does not work if the mutant is over-encumbered.


=== Heat Generation 

[horizontal]
Range:: 1 per Adjusted CON
Duration:: Constant
Frequency:: Alternating Units
General Bonus:: Combat Ratio +10

Heat generation arises from a dangerously overactive metabolism. 
This mutant amplifies any process that generates heat. 
Her body captures the excess energy from cellular chemical reactions and turns it into body heat.
The mutant is an organic space heater.
The mutant keeps anything within a one hex radius toasty warm.

The heat generation is constant.
The mutant's body temperature is much higher than usual.
The mutant is not bothered by hot temperatures but prefers to reside in colder climates. 
The increased heat signature makes the mutant stand out to thermal detectors. 

During the heat of battle, this mutant can launch searing blasts of superheated air. 
Flammable objects will catch fire for cosmetic and descriptive purposes. 

Heat attack is a Shoot attack.
A successful attack roll is required to inflict damage.
The damage delivered by the heath attack is 3-18 (3d6) hit points of damage, plus one hit point per EXPS Level.
The attack requires one unit to recover.

Cold and cold-based attacks have their damage reduced for this mutant.
The mutant's heat production counters the effect of cold attacks.
Heat based attacks inflict typical damage on a mutant with heat generation.

=== Heightened Attribute 

[horizontal]
Range:: Persona Only
Duration:: Constant
Frequency:: As Needed
General Bonus:: Special

Heightened attribute pushes one of the mutant's physical dimensions into the stratosphere.
This mutation transforms the mutant's body to reflect the heightened attribute.

include::wetware:partial$phenomic_heightened_attribute.adoc[]

Awareness::
The Awareness attribute determines how well the mutant's consciousness interfaces with her environment.
The mutant has oversized ears, big bulging eyes, a long nose, an extremely sensitive palate, and a very delicate sense of touch.
This mutation increases the mutant's Awareness by 2-8 (2d4) points, and her AWE cannot be less than 15.
Also, she earns a bonus of +30 on any Awareness related rolls and tripled AWE when trying to detect an ambush.
The mutant's Combat Ratio is increased by +4.

Charisma::
Heightened Charisma is not just beauty but includes persuasiveness, sociability and leadership.
The mutant automatically adjusts her facial structure, hair length, and posture to optimize her Charisma for each situation.
If she wishes to be alluring, her pupils will dilate, her hair will lengthen, and her voice will change.
If she needs to work up a crowd into a frenzy, her posture will be erect, her face will harden, her hair will shorten, and her voice will deepen.
This mutation offers a permanent Charisma bonus of 2 to 8 (2d8) points, and her CHA cannot be less than 15.
She also has a bonus of +30 on any Charisma related rolls and a tripled CHA during negotiation rolls.

Constitution::
The mutant has superior versions of all those organs that make up the Constitution of the persona.
Her heart is healthy and robust, her blood is resilient, her immune system is ready to go, and she has a liver that can detoxify anything.
This mutation offers a permanent Constitution bonus of 2 to 8 (2d8) points, and her CON cannot be less than 15.

The player must re-roll her persona's hit points, using her new CON, or add hit points based on the additional CON.
The hit point value cannot decrease when being changed by a heightened Constitution.

This mutant is more resilient to poisons as well. 
If the player wins her poison roll, the toxin does not affect the mutant. 
Often winning a poison roll will half the damage or reduce the effect of the poison.
With the heightened Constitution, the mutant will not affect with a poison roll win.
The mutant's Combat Ratio is increased by +8.

Dexterity::
This mutant's neurologic system is supercharged with extra nerves and specialized spinal cord pre-processing.
Heightened Dexterity allows the mutant to carry out incredible feats of balance, agility and speed.
Under normal circumstances, this mutant will not trip, fall, stagger.
Walking on ice is no challenge for this mutant.
This mutation gives a permanent Dexterity bonus of 2 to 8 (2d8) points, and her DEX cannot be less than 15.
The persona's movement rate should increase accordingly.
She will also earn a bonus of +30 on any Dexterity related rolls and tripled DEX during attribute rolls.
The mutant's Combat Ratio is increased by +4.

Intelligence::
This mutant's brain is physically different from that of other personas.
Her skull is enlarged to accommodate the densely packed blob of neurons.
Not only is the mutant's head more massive than usual, her head sports cooling gills for the heat produced by the overactive brain.
When she concentrates on a cerebral topic, her head may hum from increased blood flow.
This mutation offers a permanent Intelligence bonus of 2 to 8 (2d8) points, and her INT cannot be less than 15.
The mutant has a bonus of +30 on any Intelligence-related rolls and tripled INT during attribute rolls.
The mutant's Combat Ratio is increased by +4.

Strength::
This mutant has more muscles than usual, and the extra muscles are bigger and better ones. 
The muscle fibres are larger and more densely packed with the essential chemicals of contraction.
The mutant has additional new muscles that improve leverage and definition.
This mutation offers a permanent STR bonus of 2 to 8 (2d8) points, and her STR cannot be less than 15.
When making STR related attribute rolls the mutants, STR is tripled.
The mutant's Combat Ratio is increased by +4.

Hit Points::
This mutant's body is hardened to all manner of damage.
Her blood clots faster, her arteries can seal off, and create alternate pathways.
Her bones are more robust, and her muscles can absorb shock better than average.
In general, this mutant will look solid and tough.
This mutation offers a permanent hit point increase of 20% to 80% (2d4 times 10%), and her HPM cannot be less than 60.
This mutant will heal twice as fast as other mutants and doubles her HPS when making a recovery or damage system shock roll.
The mutant's Combat Ratio is increased by +8.

=== Heightened Vision 

[horizontal]
Range:: Special
Duration:: Until Dead
Frequency:: As Needed
General Bonus:: None 

Heightened vision adds an exotic vision type to the mutant's regular optical sensors.
The mutant may switch between either vision type as needed.

include::wetware:partial$phenomic_heightened_vision.adoc[]

Betty Davis::
Betty Davis eyes will tease and unease personas around the mutant.
The player must roll dice when using this mutation.
Other personas will think the mutant is a spie.
These eyes can expose things but make vision snowy.
You cannot roll Betty Davis Eyes on the Heightened Vision table. 

Infravision::
Infravision discerns thermal irregularities allowing the mutant to see in darkness.
This heightened vision is not as detailed as the mutant's mundane vision.
For example, the mutant cannot separate objects with equal temperature.
The mutant could easily see a computer monitor in the dark but could not read the monitor's text.
The range of this heightened vision is equal to the mutant's doubled Awareness.
If the mutant already has infravision, the player can roll again or combine the two infravision ranges.
Eyes endowed with infravision are highly reflective, like feline eyes.  

Microscopic::
Microscopic vision allows the mutant to magnify her visual field up to 1000 times.
To microscopically inspect an object, it must be right under the mutant's beak.
The mutant enjoys +30 on any rolls that would benefit from the microscopic inspection.
As the mutant zooms in, her eyes bulge from her face, and her lenses make clicking noises.

Mist Cutting::
Mist cutting allows the mutant to see through particulate matter that would usually obscure her vision.
Mist cutting sees through smoke, fog, dust, hail, or rain.
The mutant suffers no attack roll penalties in fog, rain, or smoke.
When using the mist cutting, a secondary set of translucent eyelids rapidly open and close horizontally.  

Semicircular::
Semicircular vision widens the mutant's visual field to nearly 270 degrees.
This expanded field of vision makes the mutant challenging to ambush.
The mutant doubles her Awareness when detecting an ambush.
She can also laterally attack without turning her body. 
This mutant's eyes are enormous and sit closer to her ears than her nose. 

Telescopic::
The mutant can easily discern text at great distances.
The mutant's heightened vision has a range of 10 hexes per point of adjusted AWE.
So a second level mutant with a 12 AWE could easily discern letters at 14 hexes. 
When using her telescopic eyes, the mutant has +100 on sniping attack rolls.
The mutant cannot use the telescopic vision with scopes or visual aids.
This mutant's tube-like eyes stick out past her nose.
Her eyes make a sucking noise as they continually lengthen and shorten.

Ultravision::
Ultravision adds the ultraviolet spectrum to her visual perception.
This mutation gives the mutant equal night and day vision.
At close range, she can visualize the activity of electronic circuitry.
Ultravision gives the mutant a bonus of +15 on any electronic related rolls.
The mutant's eyes glow bright red in both darkness and daylight.

X-Ray::
X-Ray vision employs radioactive beams that penetrate otherwise opaque materials.
The range of x-ray vision is one hex per 8 points of adjusted Awareness.
The mutant can look at bones through flesh, look through concrete walls, and find weapons at a glance.
The mutant cannot see through metal, discern text on a page, or read a computer monitor.
Using X-ray vision adds +30 to any rolls that would benefit from an x-ray view. 
X-Ray eyes are dangerous and radioactive, and using them counts as a radiation attack.
The intensity of the attack is equal to the range of the mutant's X-ray vision.
The flesh around this mutant's eyes is thickened and leathery, and her eyeballs are black.

=== Increased Metabolism

[horizontal]
Range:: Persona Only
Duration:: Until Death
Frequency:: Constant
General Bonus:: Defect

The metabolism of this mutant operates at a rate three times greater than average. 
The mutant gives off heat, eats nine meals a day, and is jittery and active.
Continually eating food does not make this mutant obese. 
No matter how much she eats, she appears emaciated.
For example, one food culture per day sustains an average medium-sized persona. 
This mutant needs three food cultures per day just to stay alive.


=== Launchable Quills 

[horizontal]
Range:: 1h per Adjusted STR
Duration:: Special
Frequency:: Special
General Bonus:: Special

The mutant has up to a dozen launchable quills hanging from her chest. 
In the resting position, the quills hide easily under clothing and armour.
When activated, the quills elevate into a launching position. 
Restrictive armour and clothing prevent the launching of the quills.

The mutant will have 2-12 (2d6) quills growing from the center of her torso.
The quills clump together and fire as a salvo.
There is a small chance that the quills will have poison.
The percent chance of having poisonous launchable quills is equal to the mutant's Constitution. 
A mutant with a 14 CON has a 14% chance of having poisonous quills.

The mutant launches the quills by muscular contraction and compressed gas. 
Launchable quills are attack Fling.
The mutant launches all her quills at once, and a successful attack roll inflicts 1-8 (1d8) per quill launched.
A mutant that launches six quills would inflict 6d8 damage plus her Fling Force Bonus.
Launchable quills can be a fearsome attack with or without poison.
For poisonous quills, the target must win a poison roll or take killing damage.
The poison intensity is equal to the mutant's Constitution score.

The mutant can hold back one quill per EXPS Level.
A 3rd Level mutant with six quills could launch all six at once, three and then three, etc.
There is no difference between the intensity of poison or Fling Force Bonus made by different sized salvos.

Launchable quills increase the persona's combat ratio by +3.
If the quills are poisonous, the combat ratio triples.

=== Light Generation 

[horizontal]
Range:: 1h per Adjusted CHA
Duration:: Special
Frequency:: 1 per 4 Adjusted CON
General Bonus:: Combat Ratio *2

This mutant is in a symbiotic relationship with subdermal light-emitting organisms.
The mutant's nervous system releases chemicals that excite or depress the colonies of glowing organisms.
The mutant controls how she emits the light from her body.

.*Steady Glow*
The mutant glows steadily. 
She can change the colour and brightness for convenience or mood.
With regular skin exposure and clothing, she can light up the adjacent hex around her. 
The mutant can run dark in cases of emergency.
The symbiotic relationship between the mutant and organisms requires them to glow for the wellbeing of them both.

.*Flashlight*
The mutant can organize the organisms to locate in a specific part of her body, and she can emit a beam of light from there.
The flashlight is often the mutant's forehead, but sometimes the palm or knee has been used.
If desired, the mutant can project a beam emitting from her forehead, extending straight ahead for one hex per point of adjusted STR.
The mutant can produce the flashlight as needed.

NOTE: This mutation variation was previously called "flesh light." The adult toy market now has this moniker firmly in its grip.

.*Flash Attack*
The mutant can excite the glowing organisms to emit a violent blast of blinding light.
The bolt shoots from the mutant's eyes.
The flash attack is exhausting for the symbiotes, and the mutant can barely glow until they have recuperated. 

The target must win an Awareness roll or be temporarily blinded.
The intensity of the attack is equal to the mutant's Charisma attribute.
Blindness will last 1 to 6 minutes (30 units per minute).
If she wins the Awareness roll, she will suffer blurry vision for 2-20 (2d10) units.
Targets with blurred vision have tearing eyes, light sensitivity, and can barely function.
Targets with blurred vision suffer -200 on attack rolls, -200 on AR, +42DD on sight related task rolls, half movement, etc.

:art: refrigerator_man.png
:width: 250px
:snark: Cool man
:artist: Andrew Brechin
:date: 1991
:license: CC BY-SA 4.0
:description: An obese humanoid with a fridge built into their belly.
include::ROOT:partial$articulate.adoc[]

=== Mechanical Insertion 

[horizontal]
Range:: Special
Duration:: As Needed
Frequency:: As Needed
General Bonus:: Special

Sometime, somewhere, somehow, this mutant's body became integrated with an inorganic device.
The device is part of the mutant's nervous system, immune system and skeleton.
The mechanical device gets its energy requirements from the mutant.
If the mutant has a built-in https://en.wikipedia.org/wiki/Videocassette_recorder/[VCR] she has complete control over it.
All the recorder's features record, rewind, forward, eject, etc., are as easily controlled as any other bodily function.

Typically the mutant has no idea how the insertion became part of her.
Was it the work of an insane veterinarian or mechanic?
Did she fall on it when she was a child? 
Did her mother swallow the device during pregnancy?

Mechanical insertion should only include useful functioning devices. 
Hardware like treasure or Junque is not appropriate.
Mechanical insertion should only include devices that fit inside the mutant.
Any hardware greater than 10% of the mutant's wate is not appropriate.
The players should balance the randomness of the TOY system and the usefulness of the device.
A player persona with a fusion grenade in there head is funny but should not count as a phenomic mutation.

For experienced players embracing the randomness of TOYS can be a lot of fun.
If a persona's mechanical insertion were a spaceship, a vehicle, a combot or an artillery piece, she would become a vital part of the campaign.

.*Mechanical Insertion Checklist*
. Determine insertion xref:hardware:a_introduction.adoc#_toy_type[Type,window=_blank]
. Determine insertion xref:combat:hit_locations.adoc[Location,window=_blank]

:art: mechanical_parts_limbs.png
:width: 250px
:snark: Spring in your step
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: A humanoid with springs for legs and arms.
include::ROOT:partial$articulate.adoc[]

=== Mechanical Prosthesis 

[horizontal]
Range:: Persona Only
Duration:: Until Removed
Frequency:: Constant
General Bonus:: Defect, Combat Ratio halved

include::wetware:partial$a_defect_compassion.adoc[]

Somewhere along the line, fate led to replacing one or more of the mutant's limbs with blatantly defective mechanical devices.
Scraping metal levers and gears wind into the mutant's nerves and muscles.
A prosthesis is subject to rust, and malfunctions, and breakdowns.
Damage to the mechanical prosthesis does not harm the mutant but could lead to its malfunction.
The chance of malfunction is determined by xref:uncombat:sphincter_rolls.adoc[Sphincter Roll,window=_blank].
The referee may check for malfunction monthly or when the prosthesis takes damage in combat.
A prosthesis does not alter the mutant's WATE or attributes. 
As much of a noisy hassle, the mechanical prosthesis represents it is better than no limb at all. 

include::wetware:partial$a_defect_disclaimer.adoc[]

include::wetware:partial$phenomic_mechanical_prosthesis.adoc[]

=== Mitosis 

[horizontal]
Range:: Persona Only
Duration:: Special
Frequency:: As needed
General Bonus:: Combat Ratio +3

Mitosis allows the mutant to replace damaged or missing tissues and organs.
The mutant will rapidly grow back a missing limb, regenerate a stolen liver, and smooth over scars.
The mitosis mutation is not a form of reproduction but rapid tissue replication and regeneration.
Mitosis will replace any body part provided that the mutant is not dead.

This mutation does not heal hit points for the mutant, but it does arrest ongoing damage.
Mitosis counters any protracted damage like ongoing poison effects, acid burning, or radiation roasting.
For example, an acid blast that initially inflicts 15 hit points of damage would inflict no further damage.

Mitotic regeneration of organs and limbs starts immediately. 
Within a few hours, a nub of tissue will appear.
After two restful nights of sleep, the mitotic regeneration will be complete.
Mitosis will not finish until the mutant completes the second restful sleep. 

The mutant does not age beyond her start age. 
Mitosis does not make her immortal, and if the mutant takes enough damage at once, she will die.

=== Multiple Body Parts 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Special

Multiple body parts is a genetic phenomenon that can be helpful or harmful to the mutant.
Some of the extra body parts will be entirely under the mutant's control.
Some of the extra body parts are nothing but malformed cosmetic reproductions.

include::wetware:partial$phenomic_multiple_parts.adoc[]

Arms::
The mutant has 1-4 (1d4) extra arms protruding from her torso.
The alignment of the arms will always be symmetrical.
The extra arms are fully functional arms that the mutant can use.
The mutant can use the arm to assist with maneuvers or combat.
Extra attack rolls depend on the attack type. 
If the mutant has four arms, she may use two rifles. 
If the mutant has three arms, she may use one rifle and one pistol.

Ears::
The mutant has 1-6 (1d6) extra ears sprouting from her head.
Half the ears are fully functional, and half are cosmetic oddities.
Extra ears number one, three and five are fully functional ears.
Each fully functional ear adds one to the mutant's Awareness.
If there is an odd number of ears, the mutant subtracts two from her Charisma.
Extra ears number two, four and six are cosmetic oddities. 

Eyes::
The mutant has 1-6 (1d6) extra eyes embedded in her braincase.
Half the eyes are fully functional, and half are cosmetic oddities.
Extra eyes one, three and five are fully functional eyes.
Each fully functional eye adds one to the mutant's Awareness.
Extra eyes two, four and six are blind cosmetic oddities. 

Feet/Toes::
The player chooses whether the mutant has either extra toes or extra feet.
The mutant will have either an extra foot at the end of each leg or 1-3 (1d3) extra toes.
These extra parts frustrate her haberdasher, but otherwise, neither harm nor help the mutant.
While not a defect, the player should roll another multiple body part or an entirely new mutation.

Hands/Fingers::
The player chooses whether the mutant has either extra fingers or extra hands.
The mutant will have either an extra hand at the end of each arm or 1-3 (1d3) extra fingers.
These extra parts frustrate her haberdasher, but otherwise, neither harm nor help the mutant.
While not a defect, the player should roll another multiple body part or an entirely new mutation.

Head::
The mutant has a semi-autonomous, diminutive, wrinkled head attached to her regular head.
The extra head will mimic the mutant's facial expressions and occasionally betrays her emotions.
Hiding the extra head is not possible.
If the mutant tries to hide her extra head, it will start to gasp and snuffle.
The unseemly disconcerting head decreases the mutant's Charisma by four points. 
This mutation variation is a defect and does not count as a start-up mutation.
The player should roll again on the Phenomic Mutations Table or the Multiple Body Parts Table.

Legs::
The mutant has 1-6 (1d6) extra legs attached to her torso.
The alignment of the legs will always be symmetrical.
The extra legs are fully functional and help the mutant move faster.
Each extra leg increases the mutant's movement rate by 20%
Thus a mutant with five extra legs would double her movement rate.

Mouths::
The mutant has 1 to 4 (1d4) extra mouths.
The mouths are smaller, malformed, craggily toothed, fully functional mouths.
The extra mouths can be in synch or out of synch with the mutant's cake hole.
The extra mouths can drool, chew, spit and eject vomit, but they do not talk.
There is a CHA penalty of -1 per extra mouth.
This mutation variant is a defect and does not count as a start-up mutation.
The player should roll again on the Phenomic Mutations Table or the Multiple Body Parts Table.

Noses::
The mutant has 1-8 (1d8) extra noses.
The extra noses are unappealing growths of flesh and cartilage.
The noses dribble mucous and are continually sniffling.
The mutant needs to cover every nose when she sneezes. 
This mutation variant is a defect and does not count as a start-up mutation.
The player should roll again on the Phenomic Mutations Table or the Multiple Body Parts Table.

=== New Organ 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Special

This mutant has a specialized new organ that carries out some peculiar process.
The new organ is not essential to the mutant's life.
Unless specified otherwise, the mutations can be used as often as needed.

include::wetware:partial$phenomic_new_organ.adoc[]

Air Producing::
This enormous gland is located within the torso of the mutant and it digests food to produce oxygen and nitrogen.
The gases collect in the mutant's esophagus.
She  burps into her mouth where she inhales.
The mutant can breathe underwater with ease, hold her breath indefinitely, and kiss for hours.
The mutant is unaffected by inhaled poisons.
Air production increases the mutant's Combat Ratio by +2

Blood Absorbing::
This consists of an external blood sucking tentacle, and an internal blood filtering organ.
The large tentacle burrows to a major artery, injects anticoagulants, and aggressively pumps blood from the target.
The organ will drain 1 to 6 (d6) hit points worth of blood per experience level each unit that the blood draining tentacle is attached.
A 4th level mutant would drain 4d6 worth of vital juices from her target each unit that the blood draining organ remains attached.
This attack increases the mutant's CR by 3.

A target will definitely be aware that the tentacle is attached, and she will make every effort to detach it.
A successful STR challenge will pull the tube out.
The tube can withstand 20% of the mutant's hit points maximum, before being knocked off the target.
If the tube goes to a negative total greater than 20% of the mutant's hit point maximum the tube has been severed.
For instance, if the mutant had 40 hit points, her tube could withstand 8 HPS before being knocked off the target.
If it were reduced to -8 HPS in one attack, the tube would be severed.
A severed blood tube will grow back in 1 to 6 months.
The blood draining tube cannot reach out of the mutant's hex.

Blood Producing::
Normally this mutation will be a blood producing organ that supplements the mutant's blood supply in case of injury.
The mutant will not not suffer damage from prolonged bleeding effects, nor will she have any problem with donating many times her total blood volume every day.
The organ is very sensitive, and will not aggravate internal injuries by pumping liters of blood into the persona's abdomen or skull.
The extra supply of blood keeps the persona from going into shock, easier to perform vet PT rolls on, and harder to knock unconscious.
The player doubles her persona's hit points when making a DSS roll, loses half as many hit points per turn when comatose, and gives vets a +15 PT roll bonus when working on her.
For more information about damage and healing jump to xref:uncombat:health.adoc[Health,window=_blank].

Electricity Storage::
This mutant has an organic rechargeable battery as her new organ.
The mutant can charge up this organ by draining small power cells.
The mutant can then recharge another power cell with the electricity stored in her organ.
The mutant can store a number of cells equal to her CON.

If the mutant has stored her maximum number of cells she can release all the energy at once in an electrical attack.
The attack will inflict a 1d8 per experience level of the mutant, and has a range of 1 hex.
A fully charge mutant will increase her CR by 1.

Gas Absorbing::
The gas absorbing organ sits in the mouth and nose of the persona.
It will grow to cover the lower half of the mutant's face when activated.
The mutation is sometimes called an air liver because it filters anything airborne before it gets inside the mutant.
This makes her immune to most diseases, and very hardy against poisoned gases The mutant receives +5 on her saving throw against any gas attack, and is unaffected by those gases that must be inhaled.
If there is a dispute over whether a gas needs be inhaled or not the referee should consult the http://expgame.com/?page_id=275sphincter-dice[sphincter dice].
The organ also helps draw air out of the environment, and low oxygen atmospheres affect this mutant very little.
This mutation increases the mutant's CR by 2.

Ink Producing::
This organ produces an enormous supply of fine black ink.
The gland opens on to the mutant's skin via a sphincter in which she can clip a quill pen, and write until she dies of old age.

The ink can also be violently ejected in a liquid environment as a distracting screen (6 hexes by 9 hexes).
The screen will dissipate in 3 to 30 units.
The mutant can also spray her ink jet on land as a blinding attack against a single target.
The land attack has a range of 6 hexes, and a poison intensity (blinding), equal to half the attacker's CON.
The mutant will always have enough ink to write with, but can only eject it once a day per 4 points of adjusted CON.
This mutation increases the mutant's CR by 2.

Iron Stomach::
This mutation is a two for one.
The mutant has a stomach that can digest anything that it encounters.
This includes metals, alloys, glass, toxins, plastics, and organic compounds.
The mutant will have an appropriately fortified mouth and esophagus to go with it.
The mutant will be constantly hungry, and may have difficulties to keep from eating computer parts and other essential artifacts.
Ingested poisons will have no effect on the mutant.

Light Emitting::
A light emitting organ will continually carry out chemical reactions that produce light.
The organ can produce a radius of effect equal to 1 hex per experience level.

There is a 20% chance that the mutant has a light absorbing organ instead.
This amazing mutation absorbs ambient light, but has no effect on lazers, and other organized light sources.
This creates a blob of darkness around the mutant that grows by one hex per experience level.
The amount of darkness can be controlled by the mutant, and gives her a bonus of +15 on sneaky PT rolls in the dark.

Mental Attack Absorbing::
This protective organ absorbs those waveforms which travel from thinkspace to thinkspace.
This has the effect of absorbing mental attacks against the mutant's thinkspace.[.Apple-converted-space]  The organ is reflected in a doubled MND when saving against a mental attack.
This organ is not intelligent, and will also interfere with beneficial psionic mutation effects.
The mutation has no effect on those attacks which manipulate the environment around the target.
This mutation increases the mutant's CR by 4.

Plastics Producing::
A plastic producing organ will allow the mutant to ooze plastic from some embarrassingly located orifice.
The plastic is malleable, warm and quick drying.
The plastic can come in any desired color, although once chosen, the colour cannot be changed.
The mutant can produce 1/10 of her body wate in plastic each day.

There is a 30% chance that this mutant will have glands that produce enzymes capable of destroying any plastic that it eats or licks.
It allows the mutant to damage plastic equipment, and eat plastic as a food source.

Poison Producing::
Coursing throughout this mutant's body, and secreted through the pores on her skin is a naturally produced killing poison.
This poison has a random intensity of 3 to 12 (3d4), plus one point per level of experience.
Any close physical contact like a hug, punch, or kiss will subject the victim to a killing poison attack.
Veterinarians must take extra precautions when working on these mutants to avoid a poison attack.
This mutation increases the mutant's CR by 3.

Pus Producing::
This lucky mutant has a gland that keeps to its constant task of spilling out pus, scum, cur, dregs or any other frothy grossness that the referee can imagine.
The randomly located opening cannot be plugged, or sewn shut, This mutation does not count as a start up mutation, and the player should receive another roll on the Phenomic Mutation Table.

=== Non Breathing 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: +100 breath holding tantrums

This mutant does not need to exchange gases to respire.
The mutant does not require light, oxygen, or carbon dioxide to carry out her life processes.
The mutant only needs food and water to carry out the necessary biochemical reactions.
In other respects, the mutant is digestion for nutrients and blood to carry energy around, but not lungs or breathing.
Inhaled poisons do not affect the mutant.

=== No Resistance To Disease 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Defect

include::wetware:partial$a_defect_compassion.adoc[]

This mutant is subject to all diseases. 
She has the pleasure of starting the campaign with one chronic non-terminal disease.
No resistance to disease is not limited to infectious diseases.
All manner of illness, both real and imagined, afflict the mutant. 
Her Constitution works normally against poison, damage and injury, but offers no resistance to illness checks.
Instead of using her CON attribute to fight disease the mutant uses a random value of 0 to 3 (d4-1).

include::wetware:partial$a_defect_disclaimer.adoc[]

=== No Resistance To Poison 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Defect

This mutant has no effective resistance to poison attack.
Poison attacks inflict no additional damage, but are almost certain to effect this mutant.
Her Constitution works normally against illness, damage and injury, but offers no resistance to poison rolls.
Instead of using her CON attribute to fight disease the mutant uses a random value of 0 to 3 (d4-1).
Pharmaceuticals that are imbibed have double effect, but the chance of side effects are tripled.

include::wetware:partial$a_defect_disclaimer.adoc[]

=== Oversized Body Part

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Combat Ratio +4

This mutation involves grossly oversized body part that cannot be hidden.
The oversized body part will challenge the mutant with clothing, armour, and social situations. 
Oversized body part is not a defect. 
There is an associated benefit to the persona for their oversized body part.

include::wetware:partial$phenomic_oversized_part.adoc[]

=== Photosynthetic Skin 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: None

This mutant has light green, hairless, almost translucent skin.
The chloroplasts in her skin can act as a supplementary source of energy.
This mutant does not need not to eat or breathe, but she must continue to drink water.
The mutant must have almost all her skin exposed to use photosynthesis. 
Photosynthesize does not work in complete darkness.
The mutant does not move blood throughout her body. 
The essential nutrients gently ooze along her internal sap lines.

When getting restful periods of sleep in bright light, the mutant heals five times faster than other personas.
If this is an anthro mutation, this mutant bleeds out at half the other anthro mutants' speed. 
Damage from cold or heat-based attacks adds 1/2 damage if the mutant.

=== Phosphorescent Skin 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Defect

Through the production of light-emitting materials in the skin, this mutant continually glows some unique colour.
The player can choose the colour (not black) or generate it at xref:hardware:appearance.adoc#_colour_your_whirled[Colour,window=_blank].
The light produced is barely enough to read by, but it is enough to be easily seen at night.
All but the most extreme efforts to contain the glow fail. 
The mutant also registers as a radiation anomaly.

include::wetware:partial$a_defect_disclaimer.adoc[]

=== Pockets 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: As Needed 
General Bonus:: +30 on concealment rolls

The mutant is capable of creating spontaneous pockets in her flesh.
The pocket location and size are determined by the player as needed.
She can create a big pocket on her tummy, like a kangaroo's pouch.
She can create a dozen smaller pockets all over her body.
The pockets are sealed from the elements and completely waterproof. 
This mutation does not offer a perfect hiding place for items.
The opening of the pocket and storage bulge are visible on the mutant's body.
Pockets can store 5% of the mutant's body wate.
A 100kg mutant can store 5kg of equipment. 

=== Pressurized Body 

[horizontal]
Range:: Persona Only
Duration:: 1u per Adjusted STR
Frequency:: 1u per Adjusted CON
General Bonus:: Combat Ratio +3

Pressurized body combines rapid gas production, inflatable body cavities, and resilient skin to increase her body's internal pressure.
Increasing her body pressure does not harm the mutant.
Pressurizing her body protects her from concussive, crushing, and force-based attacks.
The mutant can fall 1h per Adjusted STR and sustain no falling damage.
Falling damage is reduced by half.
Strike attacks, explosions, pressure waves, and vehicle crashes all halve the damage inflicted.
Pressurized body protects against high-pressure atmospheres and low-pressure atmospheres.
This mutation does not protect against anoxia, and the mutant must get oxygen to survive.

In rare instances, the pressurized mutant may burst a pressurized cavity when hit with a penetrating projectile.
The referee may check for this once in a while.
If the referee rolls 042 on a kilodie, the mutant will explosively decompress one of her many cavities.
This inflicts 6-36 (6d6) hit points of damage to the mutant.
The cavity will heal like any other wound, and the mutant can continue to use the mutation.

=== Radiating Eyes 

[horizontal]
Range:: 1h per Adjusted AWE
Duration:: Not Applicable
Frequency:: Alternating Units
General Bonus:: Combat Ratio +5

This mutant can launch a visible beam of radiation from her eyes.
The beam is her head's size and usually has a distinct xref:hardware:appearance.adoc#_colour_your_whirled[Colour,window=_blank].
Radiating eyes deliver a dose of killing radiation with an intensity of 2-12 (2d6) plus one per experience level.
The mutant must direct the beam at one target, and it can pass through armour.
The player needs to win an attack roll, but the target's Defence Rating is only 500 plus DEX bonus.
Only armour that protects explicitly against radiation can counter this attack.
If the attack roll is successful, the target gets a radiation roll to half the damage. 
This attack takes a unit to recharge, and the mutant must wait for one unit between attacks.

The radiation beam and the mutant herself show up as radioactive.
This mutant's eyes will glow the same colour as the radiation beam, and the flesh around her eyes is built up and scarred. 

=== Regeneration 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Special
General Bonus:: Combat Ratio *3

Every cell in this mutant's body is capable of replicating when damaged.
Regeneration allows the mutant to restore her hit points when damaged.
The mutant's body is always healing itself.
While most personas will have to wait days to recuperate back to their hit points maximum, this mutant repairs herself in minutes.
This mutation quickly knits tissues like bone, skin and muscle back together after traumatic damage.
Regeneration works well on burnt skin, repairing both acidic and flame damage quickly.

Regeneration restores hit points every unit (2 seconds) whether the mutant is in combat or not.
The mutant heals one hit point for every 5 points of adjusted Constitution every unit.
For example, a 4th level mutant with a 16 CON would heal 4 HPS every unit.
She will quickly regenerate to HPM, appearing as good as new.

Regeneration does not work if the mutant has less than 0 hit points.
So once she is critically unconscious, she can die like any other persona.
Regeneration will not grow back missing limbs but will heal the stump beautifully.
This mutation does not reverse the effects of time, and the mutant ages like all other personas.
Carrying out surgery is much more difficult on this mutant as tissue is healing as the scalpel separates it.

Once per day, the mutant can carry out a massive regeneration.
The mutant's body undergoes a total physiologic reset to regenerate an enormous number of hit points at once.
This regeneration rejects any foreign objects hiding in the mutant.
For example, her body violently rejects infections, inorganic implants, cybernetics and any pharma.
Most mutants with regeneration do not have cybernetic implants for this reason.
Massive regeneration can be done voluntarily by the mutant at any time.
The body will instinctively carry out massive regeneration if the mutant's HPS total drops below zero.
Ongoing regeneration is subtle, but massive regeneration is disgusting, violent, loud and messy.

Massive regeneration heals two HPS per adjusted CON.
A 4th level mutant with a 10 CON could massively regenerate 28 HPS.

=== Rubbery Skin 

[horizontal]
Range:: Persona Only
Duration:: Until Dead and longer
Frequency:: Constant 
General Bonus:: None

A rubbery organic equivalent replaces the mutant's skin.
The player can pick the colour of the mutant's slippery sheath.
Or the player can let the dice decide by jumping to xref:hardware:appearance.adoc#_colour_your_whirled[Colour,window=_blank].
The mutant can paint her skin with even the most toxic of paints without harming herself.
The rubbery skin is impenetrable to infections, parasites, fungi, topical poisons and other little critters.
The rubbery skin does not appear naked, and clothing is optional.
The mutant only needs protective clothing in the harshest meteorological or industrial conditions.

Physical attacks damage the mutant typically, as do inhaled poisons and radiation. 
Rubber dissolving aerosols will inflict 3 to 30 HPS of damage to this mutant.

=== Rust 

[horizontal]
Range:: Touch
Duration:: Permanent
Frequency:: Constant
General Bonus:: Combat Ratio +6

This mutation is complex and can quickly become complicated.
What is metallic, and how does her touch affect artifacts?
Are alloys metallic only? 
How are composites affected?
In short, some artifacts are obviously metallic, while others are open to discussion.
If a fevered discussion brings the players to an impasse, they should consult the xref:uncombat:sphincter_rolls.adoc[Sphincter Roll,window=_blank].

In combat, anything that inflicts damage on the mutant has assumed to contact the rust mutation.
So a sword would disintegrate the first time it damages the mutant.
Bullets inflict their damage but rust instantly on the mutant. 
Metal armour would rust away if the mutant were to punch it.
This mutation severely damages robots.

If the player wins an attack roll, the robot is subject to the rust mutation.
The referee may allow the player to have touch-only attack roll bonuses since the mutant does not need to deliver force to do damage.
Robots will take 10-100 (10d10) hit points of damage, plus two rolls on the malfunction table.
Rust damage is catastrophic for robots, and most robots will fall back to ranged attacks after the first rust attack.

=== Self Destruction 

[horizontal]
Range:: 2h per Level
Duration:: Until Dead
Frequency:: Once
General Bonus:: Defect

This mutation causes the mutant's body to store highly hazardous products of respiration between her cells.
There is enough explosive material to cause the mutant to explode fatally.
Self destruction kills the mutant and inflicts damage on those within range, not unlike a temperamental grenade.
Self destruction is the ultimate defective mutation.

When her stress center's panic signals overwhelm her body, the mutant may self destruct in glorious technicolour.
Example situations where self destruction may occur are ambush, death of a friend, losing at checkers, or throwing stuff at the referee.
If the player rolls 042 on a kilodie self destruction kicks in that the mutant immolates in an area of effect attack.
The mutant is exploded and killed instantly.
The explosion covers everything in the area of effect with mutant shrapnel.
Self destruction inflicts 1d20 per experience level of the mutant. 

Self destruction is fatal for the mutant and dangerous for the expedition.
This mutation is far worse than any other defect.
While it is fair and fun for referee personas to explode, player personas exploding is a different story.
Player personas with self destruction should have homebrew alterations to the defect.
For example, a player persona will only self destruct when they die. 
Or a player persona would have to roll 042 once per experience level to explode involuntarily.

The mutant can self destruct voluntarily.
The self destruction may be a vainglorious effort to save the empire or an explosive end to a fit of pique.

The mutant sets off explosives, bombs, and weapon detectors.
Removing the explosive by-product from the mutant's body will only have a temporary effect.
The mutant will return to self-destructive levels after one restful sleep.
Surgery may also result in the accidental detonation of this mutation.

include::wetware:partial$a_defect_disclaimer.adoc[]

=== Shape Change 

[horizontal]
Range:: Persona Only
Duration:: 1 min per Adjusted CHA
Frequency:: 1 per 5 Adjusted CON
General Bonus:: +150 on disguise rolls

Shape change allows the mutant to rearrange her body.
She can change the pigmentation and texture of her skin.
She can reorganize her internal organs as she desires.
The mutant can shape change into anything, a large box, another persona, a robot, or an alien.
She cannot shape change into imaginary objects. 
She must have seen and observed what she is mimicking.

Shape change is entirely cosmetic.
The mutant may now look like a combot, but she is merely flesh and blood that looks like a combot.
She may have claws that look razor-sharp, but they will be no stronger than her fists.
There are also size limitations to the shape change mutation.
The shape change must be within 50% of her hite and wate. 
If she is shape-changing into a much larger alien, she could create a smaller replica of that alien.

The shape change transformation takes time, and it is messy, noisy and disgusting.
Transformation does not harm the mutant, but she breaks her bones, tears her flesh, and takes on an amorphous in-between shape.
Clothes and equipment are not an option during the shape change.
During this amorphous state, the mutant is helpless, and any damage inflicted is increased by three times.

More complex transformations take longer and make the mutant more vulnerable. 
Subtle transformations take less time and don't put the mutant at risk.
Whole-body transformations should take minutes to hours, but changing hair colour is achieved in seconds.

Returning to her normal shape is automatic at the end of the mutation's duration. 
The mutant returns to standard shape four times faster than the transformation took.
Subtle changes will change back instantly, but more complicated changes will return the mutant to that icky amorphous state.
For each minute the shape is maintained, there is a 1% chance the mutant will stay in that shape indefinitely.
To change back to her base shape, she will have to wait until the mutation recharges.


=== Size Manipulation 

[horizontal]
Range:: Persona Only
Duration:: 1 min per Adjusted CHA
Frequency:: 1 per 3 Adjusted CON
General Bonus:: None

The mutant can force the molecules of her body to snuggle closer together or drift further apart.
Size manipulation allows her to decrease or increase her size.
The size change alters her hite, and she keeps her normal proportions.
The change is immediate and complete.
The mutant's equipment is unaffected by this transformation resulting in wardrobe malfunctions.

The mutant can decrease her size down to 25% of her normal size.
Shrinking does not alter her wate, attributes or skill task.
Besides allowing her to fit into tight spaces, the mutant gets an Defence Rating bonus of +75.
Her clothes will drape around her like a tent. 

The mutant can increase her size by up to 150%  for her normal size. 
Enlarging does not alter her wate, attributes or skill task.
Besides allowing her to reach the top shelf, the mutant gets a Force Bonus bonus of +50% non-powered attacks. 


===  Skin Structure Change 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: None

Skin structure change has both a cosmetic and defensive effect on the mutant's skin.
The skin structure change does not alter any attributes or affect her ability to wear armour.
The mutant enjoys all the benefits of the armour type and none of the drawbacks.
For example, skin structure changes have no restrictiveness or encumbrance penalties. 
The structurally changed skin is simply the mutant's skin.
The Defence Rating changes affect the base Defence Rating of the mutant.
So plated skin increases the base Defence Rating from 500 to 650.
The impact is purely on Defence Rating, and the skin structure change offers not other special abilities.
Often mutants with this mutation are averse to wearing armour out of pride or comfort

include::wetware:partial$phenomic_skin_change.adoc[]

=== Smoke Screen 

[horizontal]
Range:: 1h per Unit Duration
Duration:: 1u per 3 Adjusted STR
Frequency:: 1 per 2 Adjusted CON
General Bonus:: Combat Ratio +3

Smoke screen allows the mutant to create a thick smoke that pours off her back.
The mutant can superheat her back, causing a strong-smelling secretion to smoulder fiercely.
This mutant's back can heat up and ignite secretions located on her skin.
The combusting material will generate thick vision-obscuring smoke.
The mutant can instantly heat her back to generate thick smoke.

The cloud does not inhibit one's ability to breathe, but it is entirely disorienting and vision blocking.
The plume of smoke can have a strong xref:aliens:biology.adoc#_aroma[Aroma,window=_blank] and distinct xref:hardware:appearance.adoc#_colour_your_whirled[Colour,window=_blank].
The player can choose the smell and colour if she prefers.

The mutant can create a smoke cloud by standing still. 
The smoke cloud has a one hex radius per unit of burn.
The mutant can create smoke walls by moving and smoking.
If the mutant moves, she will create a smoke wall, two hexes high and one hex wide.
The wall of smoke will follow as she moves for two units.
A 2nd level mutant with a 10 STR could create a cloud of 4 hexes in radius.
The same mutant can use her move of 3 h/u to create a smoke wall 12 hexes long.

The cloud will last for 1 to 12 minutes before settling or being dissipated.
In situations of extreme stress, the mutant may involuntarily deploy her smoke screen.

===  Sonar Attack 

[horizontal]
Range:: 1h per 2 Adjusted STR
Duration:: Special
Frequency:: 1 per 2 Adjusted CON
General Bonus:: None

Sonar attack allows the mutant to create noises so loud they are destructive. 
The mutant's neck has obvious bellows that can blast air through specialized vocal cords.
Immediately before attacking, the mutant's bellows billow out to beyond her nose.
The scream attack combines high and low-frequency wavelengths that deliver destructive force to the target.
The further away the target is, the less damage the sonar attack inflicts. 
A 2nd level mutant with a 10 STR has a radius of effect of 6 hexes.

include::wetware:partial$psionic_sonic_attack.adoc[]

.*6h Range Example*
* 0h to 1h = 4-32
* 1h to 3h = 3-24
* 3h to 6h = 2-24
* 6h to 7h = 1-8

The sonar energy damages every target in the area of effect. 
The player makes one roll for all the targets in the area of effect.
In addition to damaging the targets, there is a chance of deafening audio sensors.
The sonar attack can shut down organic and inorganic sensors.
Objects taking the full force of the attack have a percent chance of going deaf.
Full force is considered those mutants within the one hex range or less.
A percentile roll less than or equal to the damage will deafen the target. 
Organic systems remain deaf for 1-8 (1d8) hours, but inorganic audio systems must await repair.

The sonar attack damages everything in the area of effect with a sonar blast of force.
The mutant's fellow expedition members are also affected by the sonar attack.
The mutant is unaffected by her sonar attack.


=== Spit Poison 

[horizontal]
Range:: 1h per Adjusted STR
Duration:: Special
Frequency:: Alternating Units
General Bonus:: Combat Ratio +9

The mutant has poison producing glands that can eject poisonous spittle at tremendous distances.
The player must win an attack roll on a specific target for the poison to take.
If the attack roll is successful, the target still gets a poison roll to deflect the poison effect.
These poisons are organic and do not affect inorganic targets like robots.

include::wetware:partial$phenomic_spit_poison.adoc[]

Killing::
Killing poison inflicts damage on the target, and with enough damage, the target can die.
The killing poison intensity is random for each attack.
Intensity varies from 1-8 (1d8) intensity plus the mutant's experience level.
The target takes half damage if she wins a poison roll.

Nausea::
Nausea poison incapacitates the target with vomiting and dizziness.
The nausea poison intensity is random for each attack.
Intensity varies from 1-8 (1d8) intensity plus the mutant's experience level.
The target is unaffected by the nausea poison if she wins her poison roll.
If the target loses her poison roll, the nausea poison incapacitates the target for 1-10 units.

Paralysis::
Paralysis poison incapacitates the target by paralyzing their skeletal muscles.
The poison does not affect the mutant's breathing or heart muscles. 
The paralysis poison intensity is random for each attack.
Intensity varies from 1-8 (1d8) intensity plus the mutant's experience level.
The target is unaffected by the paralysis poison if she wins her poison roll.
If the target loses her poison roll, the paralysis poison incapacitates the target for 1-10 units.

Unconsciousness::
Unconsciousness poison incapacitates the target by rendering her unconscious.
The poison does not affect the mutant's breathing or heart muscles. 
The unconsciousness poison intensity is random each attack.
Intensity varies from 1-8 (1d8) intensity plus the mutant's experience level.
The target is unaffected by the unconscious poison if she wins her poison roll.
If the target loses her poison roll, she will remain unconscious until awakened.
The unconscious target will remain out cold for at least 1-10 units.
The target will remain unconscious after the initial 1-10 units unless another persona wakes her up.

=== Static Quills 

[horizontal]
Range:: Persona Only
Duration:: Permanent
Frequency:: Constant
General Bonus:: Combat Ratio +2

Quills, spines, thorns and other nasty pointy things cover this mutant's body.
The quills layer is thick and offers an Defence Rating bonus of +101, but the mutant cannot wear armour.
The precluded armour includes vac suits.
The quills damage any attacker that punches, bites, or claws the pointy persona.
If the attacker wins an attack roll against the mutant, the attacker takes 1-6 (1d6) hit points plus one per experience level.
A 5th level mutant with static quills has a base AR of 601 and would passively deliver 6 to 11 HPS of damage when punched.
Mutants with high Charisma will have organized inviting quills, but a mutant with low Charisma will have scraggly off putting quills.

:art: tentacle_horn_woman.png
:width: 250px
:snark: Tentacular!
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Humanoid with a horn on her forehead and tentacles holding weapons.
include::ROOT:partial$articulate.adoc[]

=== Strange New Body Part

:art: tentacle_horn_woman.png
:width: 250px
:snark: Tentacular!
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Humanoid with a horn on her forehead and tentacles holding weapons.
include::ROOT:partial$articulate.adoc[]

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Special

The mutant has a strange new body part.
The strange new body part is not a defect.
Some of the strange new body parts are only cosmetic.
If the player has rolled a purely cosmetic mutation, she should get another roll on the phenomic mutation table.

include::wetware:partial$phenomic_strange_new_part.adoc[]

Antennae::
The mutant has a pair of organic antennae sticking out of the top of her head.
These may or may not replace the mutant's ears. 
The mutant can use the antennae to listen around corners, but they are otherwise cosmetic.

Ears::
The mutant has a pair of unique ears that resemble no know organic creature's ears.
At rest, the ears fold against the mutant's head, and when active, they unfold like an accordion or fan.
These strange new ears improve the mutant's ability to detect an ambush or intentionally listen.
The mutant doubles her Awareness for detecting an ambush or listening hard.

Eyes::
Most of the mutant's forehead has two reflective concave lenses that focus on an external retinal blob.
Her eyelids are fleshy diaphragmatic shutters.
The concavities are shallow and drastically improve the mutant's field of view.
These strange new eyes improve the mutant's ability to detect an ambush or intentionally search.
The mutant doubles her Awareness for detecting an ambush or looking hard.

Eyestalks::
The mutant's eyeballs sit atop a pair of retractable and articulated eyestalks.
The mutant can extend her eyes from her head by about 30 cm.
The eyestalks are useful for looking around and over things but are otherwise cosmetic.

Fins::
The mutant has a dorsal stabilizing fin and webbed fingers and toes.
The aquatic appendages do not allow the mutant to breathe underwater but will enable her to swim very well.
The fin and webs allow the mutant to swim at the same speed she runs on land.

Gills::
These gills are very obvious and sit on the mutant's neck and flanks.
They function like fish gills allowing the mutant to breathe underwater. 
The gills also pull oxygen from the air, and the mutant is amphibious.

Horns::
The mutant has a set of horns sticking out of her head.
There will be 1-4 (1d4) *pairs* of horns located on her head.
The horns cannot be weaponized and are purely cosmetic.

Mouth::
The mutant's mouth is now a muscle laden boney drawer.
The flesh drawer slides open, and the mutant drops her food and drink into it.
Rotating teeth ground food as the drawer retracts.
The strange new mouth functions like any other cake hole and is considered cosmetic.

Nose::
The mutant's nose is now a highly dynamic stalk of flesh, cartilage and holes.
The strange new nose rapidly retracts and extends from her face.
The retraction and extension of the nose are random. 
This busy nose is purely cosmetic.

Oral Grapple::
The mutant can shoot a small tethered grappling hook from her mouth.
It has a range of 2 hexes and attacks as a Fling weapon.
If the player wins an attack roll, the grapple inflicts 1-4 (1d4) hit points of damage and attaches to the target.
If the target fits in the mutant's mouth, she can reel it back with her ligamentous tether. 
The grapple automatically disengages and retracts back into the mutant's mouth for objects that are too large to eat.

Pincers::
Protruding from the mutant's mouth are a pair of large serrated pincers.
The mutant can dexterously manipulate her food with these pincers.
She can also use them to make a vicious biting attack. 
The pincer bite is a Strike weapon and inflicts 1-8 (1d8) hit points in damage.

Spike::
The spike resembles a unicorn's horn sticking from the mutant's forehead.
Besides looking majestic, the horn can impale targets.
Spike is a Strike weapon and inflicts 1 to 12 (1d12) HPS in damage.

Tail::
The mutant has a nice long articulated tail protruding from her hindquarters.
The tail is fully functional and acts as an extra articulation, allowing the mutant to hold and use tools.

Tentacles::
The mutant has tentacles replacing her usual limbs.
There are 1-4 (1d4) tentacles. 
Each tentacle rolled will replace one limb.
Each tentacle is a fully functional limb.
Tentacle legs can become tentacle arms or vice versa.

Turtle Shell::
This mutant has a fully functional turtle shell into which she can retract.
The shell is robust, environmentally sealed and acts as a solitary bunker.
The mutant must fully retract into her shell to gain its protective properties.
The mutant must completely withdraw into the shell for it to be effective.
Once inside, the shell protects her.
The shell's Defence Rating is 777. 
It is impermeable to poison gas and doubles the mutant's resistance to radiation.
The shell's hit points are separate from the mutant's hit points and are double the mutant's hit points max.


=== Symbiotic Attachment 

[horizontal]
Range:: 1h
Duration:: Permanent 
Frequency:: One 
General Bonus:: Special

Symbiotic attachment allows the mutant to control another persona via a specialized tentacle.
The tentacle appears as a long umbilical cord with a spine filled suction cup.
The cord is an extension of the mutant's nervous system.
The symbiotic attachment contains all the nerves, neurotransmitters, and hormones necessary to operate another organic nervous system.
When the symbiotic attachment connects to another organic persona, that persona becomes an extension of the mutant.

The mutant must win an attack roll, and the target must fail a poison roll before the symbiotic attachment takes control.
From that point on, the player is controlling two personas. 
The target must remain within the one hex range of the symbiotic attachment.

The mutant's successful attack roll must land on the target's skin. 
For example, inflicting damage through powered armour would not count as connecting the symbiotic attachment.
This attack roll must be successful even if the target wishes to be symbiotically connected.
If the mutant fails on her attack roll, the attachment immediately retracts back to the mutant.

The intensity of the poison attack is equal to the mutant's adjusted Intelligence score.
The target can use her Constitution or Intelligence score when making the poison roll. 
The poison roll reflects the resistance of the target's neurologic system resisting the takeover.
Unconscious targets get no poison roll to resist symbiotic attachment.
If the target wins her poison roll, the attachment immediately retracts back to the mutant.

NOTE: The mutant controls her symbiote but does not have access to its memories.

There is a symbiotic component of this mutation.
The mutant feels the pain and emotions of the target.
If the target is subject to a mental attack, the mutant must also make a psionic roll.
The mutant also feels any physical damage suffered by the symbiote.
The mutant takes half of any damage inflicted on her attached symbiote.

If the mutant loses consciousness (not sleeping), the symbiote breaks free.
If the target is more intelligent than the mutant, the target gets daily poison rolls to break free.
If the target is less intelligent than the mutant, the target gets weekly poison rolls to break free.



=== Tearaway Body Part

:art: detachable_hands_eye.png
:width: 250px
:snark: An eye in both hands is worth...
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: A humanoid holding her eyes in her hands, which are crawling away.
include::ROOT:partial$articulate.adoc[]

[horizontal]
Range:: 1h per Adjusted AWE
Duration:: 1 hour per Adjusted CON
Frequency:: Special
General Bonus:: None

The mutant can tear off parts of her body, and they will continue to function as if still attached.
The mutant could tear off an arm and have it open a door while she stands to the side.
She could leave her eye in a room to spy on the occupants.
She could hang an ear to the wall to listen for intruders.
Eyes and ears cannot move, but a hand could scuttle, and a foot could hop.

The mutant can tear away one body part per two levels of experience.
Each torn-away body part has a hit point total of 10% of the mutant's hit point total.
The torn away body parts are delicate. 
If the torn-away body part gets out of range, it begins to decompose.
If the torn away body part stays detached beyond the duration, it begins to compose.
Decomposition inflicts 1-8 (1d8) hit points of damage per hour.
When a body part reaches 0 hit points, it is dead, and the mutant has lost that body part. 


=== Undersized Body Part

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: Constant
General Bonus:: Defect

include::wetware:partial$a_defect_compassion.adoc[]

The undersized body part is completely obvious to any observer. 
Even unintelligent flora and fauna may notice.
There is no attribute penalty for having undersized body parts.
The effect is cosmetic, and each part functions as expected.

include::wetware:partial$a_defect_disclaimer.adoc[]

include::wetware:partial$phenomic_undersized_part.adoc[]

=== Vibrations 

[horizontal]
Range:: Touch
Duration:: 1u per 3 Adjusted DEX
Frequency:: 1 per 4 Adjusted DEX
General Bonus:: Combat Ratio +5

This mutant creates harmonic patterns transfer through her hands.
The vibrations can be soothing and comforting or painful and dangerous.
The mutant can dial in whatever she needs.

In combat, vibrations conducted through the hand can inflict damage right through armour.
The vibration punch is a Strike attack that inflicts 3-12 (3d4) hit points, plus 1 hit point per level of damage.
The player adds +97 to any attack rolls made with vibrating hands.
The vibrations can also be conducted through metallic Strike weapons turning them into organic vibro weapons.

The mutant can also grasp inanimate objects and inflict damage with her vibration attack.
When the object reaches zero hit points, it disintegrates. 

=== Wate Manipulation 

[horizontal]
Range:: Persona Only
Duration:: 3u per Adjusted CON
Frequency:: 1 per 4 Adjusted CON
General Bonus:: Combat Ratio +3

This mutant can increases or decrease her wate at will.
The wate change is nearly immediate, and involves loud bodily noises.

The mutant can triple her body wate by absorbing ambient water and airborne particles
She does not increase in hite, but she will appear to plumper.
When she increases her wate, and therefore her density, she enjoys some benefits.
She increases her Force Bonus by 50%.
She becomes harder to move and carry. 
This will give her benefits in strength challenges, or not being blown away by the wind challenges.

The mutant can reduce her body wate by one third by spewing out bodily fluids and gelatinous matter.
There is no noticeable change in the mutant's hite, but she appears much thinner.
The mutant becomes easier to carry.
The lighter mutant is more nimble and increases her movement rate by 25%

The mutant will return to her normal wate if she is knocked unconscious.

=== Wings 

[horizontal]
Range:: Persona Only
Duration:: Until Dead
Frequency:: As Needed
General Bonus:: Combat Ratio *3

The mutant has a lovely pair of wings coming off her back.
These wings allow the mutant to fly through the air with the greatest of ease.
The mutant will be able to fly at her movement rate.
Her flying movement rate cannot be less than 8 h/u.
The wingspan of the mutant keeps her from flying within normal buildings.
Wings require atmosphere to work.


=== General Bonus
The general bonus listing of the mutation could contain several arcane bits of information that are related to the use of the mutation in unexpected circumstances.
The mutation may indicate a bonus for task rolls, attribute rolls or negotiation rolls.
Any simple effect that the mutation has on the dice rolling of the persona should be included beside the general bonus listing.

== Sub Tables
When you quickly need a specific type of mutation.

=== No Defects
Best for start up phenomic mutations. 

include::wetware:partial$phenomic_list_no_defect.adoc[]

=== Combat Mutations
Nature, pharma, malfunction, or evolution.
Here is where you unleash genetic violence.

include::wetware:partial$phenomic_list_combat.adoc[]

=== Uncombat Mutations
Nature, pharma, malfunction, or evolution.
Here is where you unleash genetic curiosity.

include::wetware:partial$phenomic_list_uncombat.adoc[]

=== Defective Mutations
Nature, pharma, or side effect. 
Here is where you unleash biomagical tragedy.

include::wetware:partial$phenomic_list_defects.adoc[]
