= Chapter 24: Mundane Equipment
:author: expgame
:date: 2010-08-08 02:08:20 -0400
:guid: http://expgame.com/?page_id=292
:id: 292
:page-layout: page

[.s2]#Mundane Equipment are the low tech, non artifact items, that the persona needs to survive in the wilds.
#[.s4]#The equipment lists are #[.s5]#compilations of low tech artifacts which personas #[.s3]#can easily obtain in even the least organized of #societies.
[.s1]#The lists are as generic as possible.
If any equipment appears which the ref&#8217;s #[.s6]#milieu does not support, then it cannot be purchased.
#[.s5]#The referee reserves the right to change wates and costs without notice.
Campaign forces unknown to #[.s3]#the players may force costs to change, and new previously undiscovered alloys may drastically #alter wates.

[.s7]#Each piece of kit includes title, wate, #[.s5]#cost and sometimes alternates for each equipment #type.
The equipment titles should be self [.s2]#explanatory.
Almost all the equipment in this #[.s7]#chapter can be found in any respectable English #[.s3]#dictionary (ed.
note: one would use wikipedia.org in these modern times).
Equipment wate is always listed in #[.s7]#kilograms (kg).
Some of the very light items have #[.s5]#their wates listed in grams (gm).
The more wate a persona carries the less efficient she becomes.
The effects of wate bearing are detailed in http://expgame.com/?page_id=279[Chapter 18: ]#[.s6]#http://expgame.com/?page_id=279[Encumbrance].
The costs of equipment are listed in #[.s3]#electrum pieces (eps).#

[.s3]#The mundane equipment in this chapter has #[.s5]#its prices listed as costs and not as value.
All the costs listed are in electrum pieces (eps).
R#[.s3]#elative to toys, the low tech equipment in this chapter is valueless.
The starting equipment can #[.s6]#be given to the personas, or they can buy it with the #[.s3]#money that they start the campaign with.
#[.s6]#The allotment of start money is determined in http://expgame.com/?page_id=254[C]#[.s5]#http://expgame.com/?page_id=254[hapter 10: Incidentals].
#

== [.s6]#Higher Tech Equipment# {.p5}

[.s6]#The articles on the equipment lists are of a low tech #[.s5]#nature, with an underdeveloped, medieval nature to #[.s7]#their construction.
Anything bought directly from #[.s5]#the equipment lists is low tech.
Low tech equipment #[.s7]#is constructed from animal parts, poorly smelted #[.s3]#metals, shoddy plastics and untreated woods.
#[.s3]#Higher tech equipment is composed of alloys, #polymers, and other synthetics.
Higher tech equipment functions no differently from the [.s3]#low tech counterparts, but higher tech kit is lighter (1/2 the #[.s5]#wate), and more expensive (3 times the cost).
Higher #[.s3]#tech items are just synthetic age versions of items #[.s3]#on the equipment lists and are not artifacts.
For example a suit of chain #[.s5]#mail has a wate of 5.9 kgs, and a cost of 80 eps.
The #[.s7]#high tech version of this chain mail would cost 240 #[.s3]#eps and have a wate of 3.0 kgs.
The higher tech armour would have the same restrictiveness, and #[.s5]#the same armour rating as its low tech counterpart.
Higher tech equipment #[.s7]#is not to be confused with artifacts generated in #[.s2]#the toy system.#

== [.s1]#Class Equipment# {.p11}

[.s7]#Class equipment aids the personas in performing their class skills.
The simple collection of devices #[.s6]#results in a bonus added to the player&#8217;s PT roll.
The #[.s5]#equipment can only be used by the persona in the #[.s3]#pursuit of class skills.
Using class equipment for #[.s5]#anything other than class skills will usually damage #the items beyond usefulness.
http://expgame.com/?page_id=269[Chapter 14: ][.s3]#http://expgame.com/?page_id=269[Performance Rolls], has all the details necessary for successfully completing class skills.
#[.s2]#The class equipment for one persona will #[.s3]#appear as useless junk to another persona.
Each kit of class equipment essentially acts as a black #[.s5]#box that allows the persona to operate smoothly in #[.s3]#her class skills.
It is not required that the persona or the referee describe exactly how the equipment #[.s2]#is being used, it just needs to be present.
Table 14.2: Minimum Equipment is included here for convenience.#

[table id=157 /]

[table id=219 /]

== [.s1]#Armour# {.p11}

[.s7]#The combat parameters of armour and shields are detailed in http://expgame.com/?page_id=302[Chapter]#[.s6]#http://expgame.com/?page_id=302[29:  Armour Rating].
#[.s5]#There are two armour lists, general and designer.
#[.s3]#General armour has a flat rate and cost.
The wate #[.s7]#is directly added to the persona&#8217;s WA (unless it is #[.s5]#worn), and the cost is directly subtracted from the #[.s2]#persona&#8217;s savings.#

*High Tech Armour*: If the campaign&#8217;s milieu allow for it higher tech armour may be available for purchase.
Higher tech armour functions exactly the same as it&#8217;s low tech version, but it has half the wate, and costs three times as much.

[.s5]#*Designer Armour*: [.s3]#Designer armour should be used for #[.s2]#personas that have unique body structures#[.s3]#.
Personas such as#[.s1]# aliens, and anthros with #[.s2]#wings or multiple arms.
#Designer armour depends on the body wate of #[.s7]#the persona wearing it.
On Table 24.2: Mundane Body Armour.
Designer armour costs six times more than the regular armour.
A combination of higher tech designer armour would cost 18 times more than the lo tech armour cost.
#

[table id=220 /]

[table id=221 /]

== [.s1]#Type A, B and C Weapons# {.p13}

[.s8]#Type A weapons are thrusting and striking #[.s7]#weapons.
These weapons do not have lighter high #[.s3]#tech versions because they depend on inertia to inflict damage.
The wate of these weapons is listed in kg, and the cost in eps.
A persona may use one #[.s7]#of the alternate weapons;
however, she cannot use #[.s5]#her BP on her her to hit roll.
Only the BNP can be #[.s3]#added to to hit rolls for alternate weapons.
#[.s2]#Type B weapons are non-powered missile weapons.
The are high tech versions of type B #[.s7]#weapons.
Such weapons do no extra damage, and #[.s1]#can only benefit the persona by having a decreased #[.s11]#wate.
A persona may use one of the alternate #[.s5]#weapons;
however she cannot use her BP on her to hit roll.
Only the BNP can be added to hit rolls for #[.s2]#alternate weapons.
#[.s11]#Type C weapons are powered missile attacks.
Mostly include guns and other #[.s2]#powered weapon attacks that are usually generated as artifacts#[.s5]#.
Crossbows are the only type #[.s3]#C weapon that can be purchased in this chapter.#

[.s3]#[table id=222 /]# + [table id=223 /] + [table id=224 /]

== Survival Equipment

[.s8]#Survival equipment is divided amongst e#[.s3]#ssential survival equipment, and non-essential #[.s11]#survival equipment.
The essential equipment #[.s3]#consists of useful pieces of survival equipment: #[.s7]#backpacks, tents, food, water, rope, etc.
The non#[.s3]#essential equipment is devoted to items which are #[.s7]#not essential, but are nice to have: sleeping bags, #tents, rain suits, etc.

[.s13]#*Survival Pack*:#[.s2]#The survival pack costs #[.s7]#70 eps, and has a wate of 13.5 kg.
The survival pack #[.s2]#is designed to speed up the equipment buying #[.s3]#procedure.
A ref may not allow the survival pack #[.s8]#to be purchased as one lump, but the list of #equipment can be used to ensure that each [.s3]#expedition member is properly equipped.#

[table id=225 /]

[table id=226 /]

[table id=227 /]
