= Mundane Equipment

Mundane Equipment are the low tech, non artifact items, that the persona needs to survive in the wilds.
The equipment lists are compilations of low tech artifacts which personas can easily obtain in even the least organized of #societies.
The lists are as generic as possible.
If any equipment appears which the ref's milieu does not support, then it cannot be purchased.
The referee reserves the right to change wates and costs without notice.
Campaign forces unknown to the players may force costs to change, and new previously undiscovered alloys may drastically #alter wates.

Each piece of kit includes title, wate, cost and sometimes alternates for each equipment #type.
The equipment titles should be self explanatory.
Almost all the equipment in this chapter can be found in any respectable English dictionary (ed.
note: one would use wikipedia.org in these modern times).
Equipment wate is always listed in kilograms (kg).
Some of the very light items have their wates listed in grams (gm).
The more wate a persona carries the less efficient she becomes.
The effects of wate bearing are detailed in http://expgame.com/?page_id=279[Chapter 18: ]http://expgame.com/?page_id=279[Encumbrance].
The costs of equipment are listed in electrum pieces (eps).#

The mundane equipment in this chapter has its prices listed as costs and not as value.
All the costs listed are in electrum pieces (eps).
Relative to toys, the low tech equipment in this chapter is valueless.
The starting equipment can be given to the personas, or they can buy it with the money that they start the campaign with.
The allotment of start money is determined in http://expgame.com/?page_id=254[C]http://expgame.com/?page_id=254[Chapter 10: Incidentals].
#

== Higher Tech Equipment# 

The articles on the equipment lists are of a low tech nature, with an underdeveloped, medieval nature to their construction.
Anything bought directly from the equipment lists is low tech.
Low tech equipment is constructed from animal parts, poorly smelted metals, shoddy plastics and untreated woods.
Higher tech equipment is composed of alloys, #polymers, and other synthetics.
Higher tech equipment functions no differently from the low tech counterparts, but higher tech kit is lighter (1/2 the wate), and more expensive (3 times the cost).
Higher tech items are just synthetic age versions of items on the equipment lists and are not artifacts.
For example a suit of chain mail has a wate of 5.9 kgs, and a cost of 80 eps.
The high tech version of this chain mail would cost 240 eps and have a wate of 3.0 kgs.
The higher tech armour would have the same restrictiveness, and the same armour rating as its low tech counterpart.
Higher tech equipment is not to be confused with artifacts generated in the toy system.#

== Class Equipment# 

Class equipment aids the personas in performing their class skills.
The simple collection of devices results in a bonus added to the player's PT roll.
The equipment can only be used by the persona in the pursuit of class skills.
Using class equipment for anything other than class skills will usually damage #the items beyond usefulness.
http://expgame.com/?page_id=269[Chapter 14: ]http://expgame.com/?page_id=269[Performance Rolls], has all the details necessary for successfully completing class skills.
The class equipment for one persona will appear as useless junk to another persona.
Each kit of class equipment essentially acts as a black box that allows the persona to operate smoothly in her class skills.
It is not required that the persona or the referee describe exactly how the equipment is being used, it just needs to be present.
Table 14.2: Minimum Equipment is included here for convenience.#

// insert table 157

// insert table 219

== Armour# 

The combat parameters of armour and shields are detailed in http://expgame.com/?page_id=302[Chapter]http://expgame.com/?page_id=302[29:  Armour Rating].
There are two armour lists, general and designer.
General armour has a flat rate and cost.
The wate is directly added to the persona's WA (unless it is worn), and the cost is directly subtracted from the persona's savings.#

*High Tech Armour*: If the campaign's milieu allow for it higher tech armour may be available for purchase.
Higher tech armour functions exactly the same as it's low tech version, but it has half the wate, and costs three times as much.

*Designer Armour*: Designer armour should be used for personas that have unique body structures.
Personas such as aliens, and anthros with wings or multiple arms.
#Designer armour depends on the body wate of the persona wearing it.
On Table 24.2: Mundane Body Armour.
Designer armour costs six times more than the regular armour.
A combination of higher tech designer armour would cost 18 times more than the lo tech armour cost.
#

// insert table 220

// insert table 221

== Type A, B and C Weapons# 

Type A weapons are thrusting and striking weapons.
These weapons do not have lighter high tech versions because they depend on inertia to inflict damage.
The wate of these weapons is listed in kg, and the cost in eps.
A persona may use one of the alternate weapons;
however, she cannot use her BP on her her to hit roll.
Only the BNP can be added to to hit rolls for alternate weapons.
Type B weapons are non-powered missile weapons.
The are high tech versions of type B weapons.
Such weapons do no extra damage, and can only benefit the persona by having a decreased wate.
A persona may use one of the alternate weapons;
however she cannot use her BP on her to hit roll.
Only the BNP can be added to hit rolls for alternate weapons.
Type C weapons are powered missile attacks.
Mostly include guns and other powered weapon attacks that are usually generated as artifacts.
Crossbows are the only type C weapon that can be purchased in this chapter.#

// insert table 222 
// insert table 223 
// insert table 224

== Survival Equipment

Survival equipment is divided amongst essential survival equipment, and non-essential survival equipment.
The essential equipment consists of useful pieces of survival equipment: backpacks, tents, food, water, rope, etc.
The nonessential equipment is devoted to items which are not essential, but are nice to have: sleeping bags, #tents, rain suits, etc.

*Survival Pack*:The survival pack costs 70 eps, and has a wate of 13.5 kg.
The survival pack is designed to speed up the equipment buying procedure.
A ref may not allow the survival pack to be purchased as one lump, but the list of #equipment can be used to ensure that each expedition member is properly equipped.#

// insert table 225

// insert table 226

// insert table 227
