= Roll Playing Rules

[quote]
____
*We like dice and arithmetic!*
____

Roll playing refers a game system that depends heavily on die rolls.
Rolling dice does not preclude telling stories, or playing personas with character and passion.
Those who roll play simply enjoy dice and tables and details.

EXP's rule set is written as a roll playing rule set.
EXP has always rewarded role playing and story telling within it's roll playing world.
EXP has always had two combat systems: Tactical for roll playing and theatrical for role playing. 
In this version of EXP the two have been teased apart and sit as two separate systems.

NOTE: *Combat in the Roll Playing System is designed for minis and hex paper.*

using Roll vs Role is a tactical decision.


== Pedantry and Procedures
The words bonus, penalty, proficiency, skill, and ability are used throughout this text.
In EXP each has a specific meaning in how it affects the player and her persona.
A skill is a learned and improvable measure of a procedure.
An ability is a built in procedure limited to the persona by vocation or species.
Sadly these are used interchangeably due to lack of vigilance and legacy from the last millennium.
Hopefully the following glossary will help tease things apart.

=== Rolling Things
A bonus is anything added to a die roll that benefits the player and her persona.
A bonus is different from an adjustment in that an adjustment could be a benefit or a detriment.
Due to a lack of vigilance and legacy bonus and adjustment are often used interchangeably.

Adjustment:: 
Anything that alters the chances of the player and persona being successful.
An adjustment could be beneficial or detrimental.
Bonus:: 
An adjustment that is beneficial to the player and her persona.
Usually a number that is added to a die roll to improve (not guarantee) the chance of success.
Penalty:: 
An adjustment that is detrimental to the player and her persona.
Usually a number that is subtracted from a die roll to decrease the chance of success.

=== Doing Things
Proficient is a linguistically expensive way to say highly skilled. 
Being proficient guarantees a quality level to the skill.
In EXP proficiency is exclusively used to represent weapon knowledge.
Use of this term is legacy from the last millennium. 

Proficiency:: 
Indicates a knowledge level to perform *well* at something.
A proficiency can be learned by a persona.
Proficiencies are binary (on/off).
A persona is proficient or she is not.
Proficiencies do not improve like a skill.
There is no proficiency +4 being better than proficiency +2.
For example, a persona can be proficient with a spear using it properly in all circumstances.

Ability::
Indicates a knowledge to be able to perform something.
An ability is not learnable.
Abilities are binary (on/off).
A persona has an ability or she does not.
Abilities do not improve like a skill.
There is no ability +4 being better than ability +2.
For example, a Nomad persona has the ability to try and find water anywhere.
Find water is a built in nomad ability not possessed by other personas.

Skill::
Indicates a knowledge to be able to perform something.
A skill is learnable.
A skill can be improved over time.
Skills have levels that represent how skilled the persona is.
Juggling 4 is better than juggling 2. 
The higher the skill level the better the chance of success for the persona.
For example, improving a vet's genetics skill from 2 to 4 would improve her chances of success with genetics procedures.

Gift::
A gift is a usually an ability that is not explainable on the physical plane.
A gift cannot be learned, understood or taught by a persona. 
A gift may be something that is awakened, like a mental mutation.
A gift could also be a skill or a proficiency but it usually inexplicable.
For example, the knite ability to use suggestion is an inexplicable gift. 
The term gift is used interchangeably with skills and abilities.


There is a difference between skill, ability and proficiency though.
A skill can be learned and improved. 
Most skills can be learned and are assigned levels.
For example, juggling 2 can advance to juggling 4.
Most abilities are built in and are not learnable. 
For example, a nomad can find water it is not a learned skill.
A proficiency is an on off measure. 





== Roll Playing Rules
// all your rolls are belong to us
// dice tables outcomes decided by dice and tables.

== List of Roll Playing Rules
This is the proposed nav.adoc for section ii

.*Combat*
* Tactical Combat System
** 15 completed
.*Non-Combat*
* 13 completed
** Generation
** Artifact Identification
** Artifact Damage

== Roll Playing

.Success vs Random
. Success roll 
.. affects the persona in that moment
.. have a success, tie fail outcome
. Random rolls 
.. deterministic 
.. randomly decide a skill, Toy or description
.. may be good, bad or indifferent, but not success fail

.Success Rolls
. Static Rolls (one roll vs fixed number)
.. To Hit Roll
.. Saving Throws
.. Attribute Checks - within one persona (same as a save?)
.. PT Rolls
. Dynamic Rolls (one roll vs one roll)
.. Attribute Challenge - between 2 personas
.. Sphincter Dice

== Embrace the KiloDie?
Fine in tactical combat. 
Not yet for generative tables.  
Goal is to removed the 1d100 so common on artifact tables. 
Probably move to kilodie generative tables in 2025.
Won't be a challenge as automation should be up and running by then.

== Embrace the High Roll
Completed.


// strive for the goal of high rolls always win.

== All rolls are to challenge rolls
* the to hit roll is a specialized challenge roll versus an armour rating with random effect (damage).
** 1d1000 vs AR
* saving throw is against an intensity, random or assigned
** 1d20 vs intensity
* performance table special vocation skill roll with success or partial success.
** 1d100 vs table result

.Steps to a Challenge
. Determine Challenge type
.. Attribute
.. Poison
.. Psionic
. Player Rolls Challenge
.. 1d20 plus attribute plus level
. Referee Counter Challenge
.. difficulty fixed
.. difficulty random
.. difficulty special
. Compare Results
.. player higher, player success
.. referee higher, player loss
.. tie is partial success player


== data from python test
Ran average attribute for an anthro and average roll on 1d20 shooting for 60% chance of success.

* attribute 10 v base 18 = 60%
* attribute 10 v base 19 = 55%
* attribute 10 v base 24 = 29%
* attribute 10 v base 32 = 0%
* attribute 11 v base 32 = 0%
* attribute 18 v base 32 = 30%
* change it up
* attribute 10 v base 18 = 59%
* attribute 12 v base 18 = 70%
* attribute 14 v base 18 = 80%
* attribute 16 v base 18 = 90%
* attribute 18 v base 18 = 99%


Below is a challenge roll table

include::ROOT:partial$CH16_Table_Challenge_Rolls.adoc[]

// below in doc table is irrelevant

Below is a difficulty roll table

include::ROOT:partial$CH16_Table_Attribute_Roll_Difficulty.adoc[]



// Table 16.2 Attribute Roll Difficulty
.*Player Centric Challenge Rolls Examples*
[width="75%",cols="4*",frame="all"]
|===

4+<|All attributes are leveled. PSTR + EXPS Level

4+<s|Player trying to arm wrestle another persona 
s|Difficulty
s|Player
s|Referee
s|Success

|Normal
|1d20 + PSTR 
|1d20 + PSTR  
|Player wins wrestle.

4+<s|Paralysis poison attack intensity 13. 
s|Difficulty
s|Player
s|Referee
s|Success

|Normal
|1d20 + CON 
|9 + 13  
|Player not paralyzed.

4+<s|Player projecting illusion psionic attack. 
s|Difficulty
s|Player
s|Referee
s|Success

|Normal
|1d20 + MSTR 
|1d20 + MSTR  
|Target sees illusion.

4+<s|Psionic attack (sleep) on player. 
s|Difficulty
s|Player
s|Referee
s|Success

|Normal
|1d20 + MSTR 
|1d20 + MSTR  
|Player stays awake.

4+<s|Persona breaking down hollow Home Despot door. 
s|Difficulty
s|Player
s|Referee
s|Success

|Easy
|1d20 + PSTR 
|6  
|Door succumbs.

4+<s|Persona breaking down very secure door. 
s|Difficulty
s|Player
s|Referee
s|Success

|Easy
|1d20 + PSTR 
|6  
|Door succumbs.

|===




