= Persona Creation

[quote]
____
the aspect of someone's character that is presented to or perceived by others.
____

The persona is a fictional representation that the player uses to participate in the EXP world. 
In other games, a persona is called a character, an avatar, or an actor.
The persona is the player’s tool, and the player gives the persona life.
The player manipulates the fictional world through her persona.
Every player in the game has a persona.
The referee will have many personas; they are called referee personas.
Some referee personas will be important; others will be insignificant.

EXP is a tabletop roleplaying game, and the players gather together in the flesh. 
A group of personas is called an expedition.
The referee, who is just another player, gives puzzles that the expedition must solve. 
The persona allows us to experience anything through the power of our imagination.

== Steps for Persona Creation

. xref:ROOT:index.adoc[Get to know EXP,window=_blank]
.. xref:ROOT:CH01_Playing_Exp.adoc[The Game,window=_blank]
.. xref:ROOT:CH02_Playing_Personas.adoc[The personas,window=_blank]
. xref:CH04__Families.adoc[Choose a family,window=_blank]
.. xref::CH04_Anthros_.adoc[Anthro,window=_blank] - most familiar, easiest to play
.. xref::CH06_Aliens_.adoc[Alien,window=_blank] - less familiar, harder to play
.. xref::CH05_Robots_.adoc[Robots,window=_blank] - totally unfamiliar, hardest to play
. xref::CH07_Mutating.adoc[Mutations,window=_blank]
. xref::CH08_Vocations_.adoc[Vocations,window=_blank]
. xref:CH10_Incidentals.adoc[Incidentals,window=_blank]
. xref::CH14_Performance_Tables.adoc[Performance Rolls,window=_blank]
. xref::CH09_Combat_Tables.adoc[Combat Tables,window=_blank]
. *Have fun!*
