= Kilodie Mechanic

The kilo-die is a thousand sided die, or 1d1000.
The 1d1000 generates a random number between 1 and 1000.
1d1000 rolls are the die rolls made in combat attack rolls.
Hence the nickname kill-o-die.

The kilodie allows the referee to assign tiny adjustments for minutiae.
For example, a player wants an attack roll bonus for making a ferocious face during combat.
The referee rewards the role-playing aspect of this by giving the player +10 on her attack roll.
If the player scores a hit because of the +10, there will be much rejoicing and merriment.
The kilodie allows for more detail and fun in the tactical combat system.

The kilo die is not a golf ball with tiny writing on it.
Three ten-sided dice simulate the 1d1000 die roll.
For example, roll a green, a yellow and a red ten sider dice all at once.

* The green die is assigned the hundreds place.
** 900, 800, 700, 600, 500, 400, 300, 200, 100 and 0 
* The yellow die is assigned to the tens place.
** 90, 80, 70, 60, 50, 40, 30, 20, 10 and 0 
* The red die is assigned to the digits place.
** 9, 8, 7, 6, 5, 4, 3, 2, 1 and 0 

:art: 664_GYR.png
:width: 250px
:snark: 664
:artist: HM
:date: 2020
:license: CC BY-SA 4.0
:description: Three dice. Green ten sider, yellow ten sider, and red ten sider.

include::ROOT:partial$articulate.adoc[]

Rolling six on the green ten sider, six on the yellow ten sider, and four on the red ten sider results in a kilodie roll of 664.
One can also roll a 1d10 three times to get the same result. 
However, users of the Roll Playing System usually prefer to roll lots of dice.

include::ROOT:partial$CH27_Table_Tactical_Kilo.adoc[]

If your group prefers to use a simpler die, 1d1000 is easily divisible to accommodate simpler dice shapes.

include::ROOT:partial$CH26_Table_Theatrical_Combat_Dice_Options.adoc[]




