= Kilodie Mechanic

The kilo-die is a thousand sided die, or 1d1000.
The 1d1000 generates a random number between 1 and 1000.
1d1000 rolls are mostly needed for attack rolls in combat.
Hence the nick name kill-o-die.

The kilodie allows the referee to assign tiny adjustments for minutiae.
For example, a player wants a bonus to hit for making a ferocious face during combat.
The referee wants to reward the role-playing aspect of this by giving the player +10 to hit.
If the player scores a hit because of the +10 there will be much rejoicing and merriment.
The kilodie allows for more detail and fun in the tactical combat system.

The kilo die is not a golf ball with tiny writing on it.
The kilo die is simulated by rolled three ten sided dice.
For example, roll a red, a yellow and a green ten sider dice all at once.

* The red die is assigned the hundreds place.
** 900, 800, 700, 600, 500, 400, 300, 200, 100 and 0 
* The yellow die is assigned to the tens place.
** 90, 80, 70, 60, 50, 40, 30, 20, 10 and 0 
* The green die is assigned to the digits place.
** 9, 8, 7, 6, 5, 4, 3, 2, 1 and 0 

Rolling 6 on the red ten sider, 6 on the yellow ten sider, and 4 on the green ten sider results in kilodie roll or 664.
The same result can be achieved by rolling 1d10 three times. 
However, users of the Roll Playing System usually prefer to roll lots of dice.

include::ROOT:partial$CH27_Table_Tactical_Kilo.adoc[]

If your group prefers to use a simpler die 1d1000 is easily divisible to accommodate simpler dice shapes.

include::ROOT:partial$CH26_Table_Theatrical_Combat_Dice_Options.adoc[]




