= Charisma (CHA)

:art: charisma.png
:width: 250px
:snark: The frontline of charisma.
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of smiling human male face.

include::ROOT:partial$articulate.adoc[]

Charisma is charm, looks and sociability all combined into one value.
A high charisma represents a high proficiency at getting along with other personas.
This attribute is universal, so any persona with a high charisma would be socially adept.
A persona's charisma is very important for inter-persona interactions.

Anthro charisma is composed of voice, posture, healthy skin, eye contact, 
Alien charisma is composed of coat texture, vocalization, adornments etc.
Robot charisma is composed of speaker quality, detailing, lighting, trim and programming.

Charisma improves the persona's chances in promotions, sales, leading, and negotiating.
Charisma can influence role-playing but does not replace role-playing.
A persona with a high charisma should not avoid opportunities to role-play.
Charisma does not influence the behaviour of the persona. 
A persona with a negative charisma may be kind and considerate.

Charisma is the only attribute that can fall below one and not kill the persona.
Burns, scars, mutations, limp, etc., may reduce a persona's charisma.
However, the reaction of other personas to a low charisma may be fatal.

// brand new table for version 6.0
.*Charisma by Family*
[width="75%",cols="<,^,^,^"]
|===

|
s|Anthro
s|Robot
s|Alien

s|Range
|3-18
|3-18
|3-18

s|Die Roll
|3d6
|3d6
|3d6

|
s|Anthro
s|Robot
s|Alien
|===