= Constitution (CON)

:art: constitution.png
:width:
:snark: The organs of resilience. 
:artist: Warren Oddsson
:date: 1990
:license: CC BY-SA 4.0
:description: Drawing of trachea, lungs and fluid pumper.

include::ROOT:partial$articulate.adoc[]

Constitution represents a persona's internal physique.
Constitution is a combination of wellness, immunity, energy extraction, healing ability.
A high constitution is better to repel disease, resist poison, and repair damaged tissue.

Anthro components of constitution are her heart, lungs, digestion, kidneys, coagulation and immune systems.
Robot components of the constitution reflect the quality of materials, part redundancy of parts, component efficiency.
Alien components of constitution are similar to an anthro's, but gills may replace lungs or sap may replace blood.


There is a strong relationship between constitution and hit points.
Hit Points represent the complete package of the persona's ability to take damage.
The persona's constitution influences hit points for all persona types.

If a persona's constitution drops below one, she is irrevocably dead.
The persona's body is unable to extract energy or repair itself in any way.  

// brand new table for version 6.0
.*Constitution by Family*
[width="75%",cols="<,^,^,^"]

|===

|
s|Anthro
s|Robot
s|Alien

s|Range
|3-18
|Level 1-4
|0-25

s|Die Roll
|3d6
|1d4
|5d6-5

|
s|Anthro
s|Robot
s|Alien
|===

