= Dexterity (DEX)

:art: dexterity.png
:width: 
:snark: Wiring the brain to environment.
:artist: Warren Oddsson
:date: 1990
:license: CC BY-SA 4.0
:description: Drawing of a human hand.

include::ROOT:partial$articulate.adoc[]

Dexterity represents the connection between the brain and the outside world.
Agility, balance, eye-hand, reflexes and running speed are components of dexterity.
A high DEX person could run faster, dance better and quicker reflexes.
Dexterity would help the persona catch a priceless vase or dive through a closing door.

Anthro dexterity is composed of neurons, reflexes, and cerebellar processing.
Robot dexterity is composed of wiring, servos, processors and the like.
Alien dexterity is composed of the alien equivalents of neurons and reflexes.

Dexterity determines a persona's amour rating and movement rate.
Each persona family has it's own way of calculating movement and armour rating. 

If a persona's dexterity falls below one, she is irrevocably dead due to complete motor-nervous system failure.

// brand new table for version 6.0
.*Dexterity by Family*
[width="75%",cols="<,^,^,^"]

|===

|
s|Anthro
s|Robot
s|Alien

s|Range
|3-18
|Level 1-4
|0-25

s|Die Roll
|3d6
|1d4
|5d6-5

|
s|Anthro
s|Robot
s|Alien
|===



