= Physical Strength (PSTR)

:art: physical_strength.png
:width: 250px
:snark: Chemisty and levers.
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Physical Strength represents force the persona can generate to get work done.
PSTR is a combination of leverage, power and physique.
Physical Strength determines how much the persona can lift or damage by brute force.
PSTR helps kicking open doors, breaking bonds, or crushing beer bottles.

PSTR is equivalent amongst all the families. 
Anthro and alien PSTR is determined by contracting fibres, levers and their sizes.
Robot PSTR employs hydraulics, servos, wires etc.
However a 12 PSTR is the same in an alien as an anthro as a robot.

There is a special relationship between Wate Allowance and PSTR.
The stronger the persona is the more the persona can lift.
Wate Allowance is different between organic and inorganic personas.
These differences are reflected in the persona generation of each family.

// brand new table for version 6.0
.*Physical Strength by Family*
[width="75%",cols="<,<,<,<"]
|===

|
s|Anthro
s|Robot
s|Alien

s|Die Roll
|3d6
|1d4 (level)
|6d6-6

s|Range
|3-18
|1-29
|0-30

|
s|Anthro
s|Robot
s|Alien
|===


