= Physical Strength (PSTR)

:art: physical_strength.png
:width: 250px
:snark: Chemisty and levers.
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a muscular arm giving a thumbs up.

include::ROOT:partial$articulate.adoc[]

Physical strength represents the force the persona can generate to get work done.
Physical strength is a combination of leverage, power and physique.
Physical strength determines how much the persona can lift or break using brute force.
Physical strength helps when kicking open doors, breaking bonds, or crushing beer bottles.

Physical strength is equivalent amongst all the families. 
Anthro and alien physical strength arise from contracting fibres and boney levers.
Robot physical strength employs hydraulics, servos, wires etc.
Organic and robotic physical strength is equal on a point by point basis. 
So a robot, alien or anthro with nine physical strength are equally strong.

// brand new table for version 6.0
.*Physical Strength by Family*
[width="75%",cols="<,^,^,^"]
|===

|
s|Anthro
s|Robot
s|Alien

s|Range
|3-18
|1-4 Level
|0-30

s|Die Roll
|3d6
|1d4
|6d6-6

|
s|Anthro
s|Robot
s|Alien
|===


