= Mental Strength (MSTR)

:art: mental_strength.png
:width:
:snark: Where minds meet.
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Mental Strength represents the persona’s will power, psionic ability, and luck.
This attribute is a science fantasy one with no physiologic connection to our world, yet.
A persona with a high MSTR would exhibit will power and resistance to influence.
The MSTR is the key attribute powering mental mutations and psionic battles.
Physical strength represents the amount of force one can generate in the physical world.
Mental strength represents the amount of force one can generate in the psionic world.

____
In EXP the psionic world is called the ThinkSpace.
Psionic is the science fantasy of the occult fantasy term psychic.
____


== Zero MSTR
Mental Strength can drop to zero during game play.
A zero MSTR can generated during persona creation.
A MSTR may not exist at all for a persona. 

=== Robots and Zero
Mental Strength and thinkspace are part of the organic world and are not available to robots.
Robots have no MSTR attribute (registered as zero) and cannot enter the thinkspace.
Robots are not affected by mental attacks that infiltrate the organic brain.
Robots are affected by mental attacks that affect the physical world. 
For example, a mental attack that changes a persona's mind would have no effect on a robot.
However a mental mutation that generates a flame in the physical world would effect the robot.

=== Dropping To Zero
If a persona’s MSTR should drop below 1, she is irrevocably deceased.
This type of death is caused by an evaporation of the life force held within the brain.
This death is reserved for alien and anthro organic personas.

=== Generating A Zero
It is possible for an anthro or alien to generate an MSTR less than 1.
Occasionally the charisma attribute score can drop below 1 during persona creation. 
Anthros with a low INT and low MSTR can create an MSTR less than 1. 
Aliens have a rare chance of rolling a zero attribute.
Options for managing these situations are covered in their respective sections.

// brand new table for version 6.0
.*Mental Strength by Family*
[width="75%",cols="<,<,<,<"]

|===

|
s|Anthro
s|Robot
s|Alien

s|Die Roll
|4d4
^|Nil
|5d6-5

s|Range
|3-18
|0
|0-25

|
s|Anthro
s|Robot
s|Alien
|===



