= Awareness (AWE)

:art: awareness_eyes.png
:width: 
:snark: Eyes, ears, nose. Key elements of awareness.
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of faced focusing on human eyes and ears.

include::ROOT:partial$articulate.adoc[]

Awareness indicates how aware a persona is of her surroundings.
It indicates how well is the persona's brain detects the outside world.
The attribute is a collective measure of the persona's sensors.
AWE includes senses like hearing, vision, smell, touch and taste.
Awareness does *not* include the sixth sense (MSTR) or a sense of style (CHA).

Anthro sensors are ears, eyes, nose, tongue and skin.
Robot sensors are cameras, microphones, vibration, and pheromone detectors.
Alien sensors are ears, eyes, nose, tongue and skin.
Alien sensor appearances reflect the terra mundane animal types that build the alien.  

A persona with a high AWE would have keen eyesight, a fine sense of smell and good hearing.
AWE would be the most important attribute when trying to locate a hidden object or detect an ambush.

If a persona's awareness drops below one, she is dead.
Her brain gets cut off from all exterior and interior stimuli causing her consciousness to dissipate.

// brand new table for version 6.0
.*Awareness by Family*
[width="75%",cols="<,^,^,^"]
|===

|
s|Anthro
s|Robot
s|Alien

s|Range
|3-18
|3-18
|3-18

s|Die Roll
|3d6
|3d6
|3d6

|
s|Anthro
s|Robot
s|Alien

|===