= Mental Strength (MSTR)

:art: mental_strength.png
:width:
:snark: Where minds meet.
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0
:description: Two stern sets of eyes staring at each other.

include::ROOT:partial$articulate.adoc[]

Mental strength represents the persona's will power, psionic ability, and luck.
This attribute is a sciency fiction one with no physiologic connection to our mundane terra just yet.
A persona with high mental strength has excellent will power and resistance to influence.
Mental strength is the crucial attribute powering mental mutations and psionic events.
Physical strength represents the amount of force one can generate in the physical world.
Mental strength represents the amount of force one can generate in the psionic world.

In the EXP xref:vi-appendices:Appy_C_Campaign_Mythos.adoc[Generic Mythos,window=_blank], the psionic and psychic exist within the Think Space. 

Mental strength has family-based peculiarities that other attributes do not have.
Inorganic personas (robots) have a mental strength of zero and are unharmed by this.
Robots do not connect to the Think Space, will power is an issue, and the Cyber Space has no use for luck.
Organic personas die if their mental strength drops to zero. 
The life force of alien and anthro personas evaporates if they lose their mental strength.
In rare instances, an alien may evolve with zero mental strength.
These alien species are an edge case and have no connection to the Think Space.

// brand new table for version 6.0
.*Mental Strength by Family*
[width="75%",cols="<,^,^,^"]

|===

|
s|Anthro
s|Robot
s|Alien

s|Range
|3-18
|0
|0-25

s|Die Roll
|4d4
|Nil
|5d6-5

|
s|Anthro
s|Robot
s|Alien

4+<|Creating a new persona with a 0 MSTR is not fatal.
|===



