= Hit Points (HPS)

:art: hitpoints.png
:width: 
:snark: How much damage can one take?
:artist: Warren Oddsson
:date: 1990
:license: CC BY-SA 4.0
:description: Drawing of chest with bullet scars.

include::ROOT:partial$articulate.adoc[]

Hit points reflect the persona's ability to withstand physical damage.
Hit points are a composition of structural integrity, force distribution, resilience and luck.
The more hit points a persona has, the more physical injury the persona can endure.
When a persona runs out of hit points, they go unconscious and quickly die.

NOTE: Hit Points are the currency of combat.

Anthro hit points are a combination of connective tissue strength, organ padding, bone strength, coagulation and luck.
Alien hit points include all the elements of anthro hit points plus stronger special hides, unique fluid, and luck.
Robot hit points have inorganic equivalents like tensile strength, alloy casings, redundancies, power distribution, and luck.

Hitpoints are a unique attribute.
Unlike all other attributes, hits points are very dynamic.
A persona's hit points can vary wildly everyday.
A persona could lose hitpoints by getting injured.
She could immediately regain those lost hitpoints with a healing pharmaceutical.
She can gradually regain lost hit points as her body repairs itself.
No other attribute dances around like this.

To keep track of this attribute, it has two parts. 
These two parts are the constant hit points maximum, and the dynamic hit points total. 

== Hit Points Maximum
A persona's hit points maximum is determined once.
The player calculates her persona's hit points during persona generation.
Each family calculates its hit points maximum differently.

The hit points max (HPS Max) is a fixed element. 
A persona with 42 HPS Max will always have 42 HPS max. 
A persona cannot heal beyond her hit points max.
For example, a healing pharmaceutical can restore a persona to 42 HPS but not beyond. 
Hit points max is not completely permanent. 
Age, robot decay, or other nastiness can reduce the HPS Max.

== Hit Points Total
HPS Total is the number of hit points the persona has at this instant.
When uninjured, the hit points total (HPS Total) equals the HPS Max.
The persona's HPS Total decreases every time she is injured. 
The HPS Total is like a fuel gauge for damage.
The lower the fuel gauge, the less damage the persona can withstand. 
If this damage gauge gets to zero, dramatic things happen to the persona.
These dramatic things include unconsciousness and death.

== Hit Points
A Hit Point doesn't convert to a unit of energy – like an erg.
However, a hit point has a constant value.
One hit point of damage reduces the hit point total of the persona.
A hit point is a hit point is a hit point.
Anthros, aliens, robots, and inanimate objects all lose hit points when damaged.

== Same Hit Point Different Impact
Robots, aliens and anthros all deduct hit points in the same fashion.
However, the impact of a hit point varies between the families.
Here are some brief examples. 

Anthros can be stunned if they lose too many hit points at once. Aliens and robots cannot be stunned or knocked out by a bolus of damage.
Anthros go unconscious and start dying at zero hit points total. Aliens are dead at zero hit points total. Robots break something and decay a bit at zero hit points. 
Aliens and anthros (organic personas) can spontaneously heal hit points through rest. Robots cannot spontaneously heal hit points and must face dangerous repairs. 


// brand new table for version 6.0
.*Hit Points by Family*
[width="75%",cols="<,^,^,^"]

|===

|
s|Anthro
s|Robot
s|Alien

s|Range
|5-90
|1-500
|1-750


s|Determined by 
|CON
|CON and Type
|CON and Size

|
s|Anthro
s|Robot
s|Alien

|===


