= Intelligence (INT)

:art: intelligence.png
:width: 250px
:snark: Soggy bag of chemicals, electricity and consciousness.
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of brain and brain stem.

include::ROOT:partial$articulate.adoc[]

Intelligence indicates the smarts of the persona.
Elements of intelligence are memory, deduction, creativity, and adaptability.
The higher the intelligence of the persona, the smarter she is.

The intelligence attribute does not replace role-playing. 
Players can make terrible decisions for their intelligent personas.
Role-playing can allow an intelligent persona to accomplish something her player cannot.
In many ways, this is the whole point of playing RPGs.
However, a persona with high intelligence should not subvert a referee's campaign puzzles.
The players must figure some things out for themselves. 

Anthro and alien intelligence represent the number and connectivity of their organic synapses.
Robot intelligence is inorganic and represents baked in processors and machinery. 

Intelligence is equivalent between the families. 
An intelligence score of twelve is the same for anthros, aliens and robots.
The robot consciousness is a malfunction of their machinery, and this can limit their function.
Alien persona intelligence does not indicate language or tool using. 
High alien intelligence makes all these more likely.
An intelligent alien persona that is fauna in the ecosystem will make smart role-playing decisions without language, culture or tools.



// brand new table for version 6.0
.*Intelligence by Family*
[width="75%",cols="<,^,^,^"]

|===

|
s|Anthro
s|Robot
s|Alien

s|Range
|3-18
|Level 1-4
|0-25

s|Die Roll
|3d6
|1d4
|5d6-5

|
s|Anthro
s|Robot
s|Alien
|===