= Awareness (AWE)

:art: awareness_eyes.png
:width: 
:snark: Eyes, ears, nose. Key elements of awareness.
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Awareness indicates how aware a persona is of her surroundings.
It indicates how well is the persona's brain is connected to the outside world.
The attribute is a collective measure of the persona's sensors.
AWE includes senses like hearing, vision, smell, touch and taste.
Awareness does *not* include the sixth sense (MSTR), or a sense of style (CHA).

Anthro sensors are ears, eyes, nose, tongue and skin.
Robot sensors are cameras, microphones, vibration, and pheromone detectors.
Alien sensors will be fashioned after the animal parts the alien is composed of.

A persona with a high AWE would have keen eyesight, fine sense of smell and good hearing.
AWE would be the most important attribute when trying to locate a hidden object or search a room.

If a persona’s awareness drops below 1 she is dead.
Her brain has been cut off from all exterior and interior stimuli.

// brand new table for version 6.0
.*Awareness by Family*
[width="75%",cols="<,<,<,<"]
|===

|
s|Anthro
s|Robot
s|Alien

s|Die Roll
|3d6
|3d6
|3d6

s|Range
|3-18
|3-18
|3-18

|
s|Anthro
s|Robot
s|Alien

|===