= Families

// recommended players skip to anthros
// what is a family in EXP 
// entirely phenotypic


// taxonomy mind map
// challenges and benefits

[quote]
____
*EXP's three families are Alien, Anthro and Robot.*
____

Every persona, from the evilest referee persona to the kindest player persona, has a family.
The three types of families found in EXP are anthros (humans, canines, felines, etc.), robots (janitorial to combot) and aliens (flying carnivorous plants to pulsating blobs).

On earth all life is sorted by a taxonomy based on genetics.
There are many elements in the taxonomy of life on earth.
EXP ignores all of this in the name of sciency fiction.
Families in EXP are divided phenotypically.
Phenotypically is a long way to say "how something looks."
Since life in EXP is divided by appearance and not genetics we have our own taxonomy.
Families are organized in EXP  Family, Genus and Species.
This keeps it simple.
Even simpler is dividing the families into their common names: anthro, alien, and robot.

.*EXP's Fake Taxonomy*
* *Domain -> Order:* Ignored
* *Family:* 
** Hominidae (Anthro)
** Machinae (Robot)
** Diversidae (Alien)
* *Genus:*
** Anthro = Homo
** Alien = Determined at generation
** Robotic = Fabricator Name
* *Species:*
** Anthro = Avis, Aqua, Canis, Felis, et.
** Alien = Determined at generation
** Robot = Android, Combot, Hobbot, Rescue

:art: Life.jpg
:width: 450px
:snark: Hominidae, Machinae, Diversidae
:artist: HM
:date: 2019
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The referee is welcome to use whatever naming structure suits their campaign.
The aliens could all be robots.
The anthros could be aliens.
Don't let the rules get in the way of a good story.

== Anthro Family (Hominidae)

Player personas primarily consist of anthropomorphs.
It is strongly recommended that players choose anthro personas.
New players will find the anthros most relatable.
Anthros are expected to have language, culture, and vocation. 
The anthro most closely fits the long standing experience of role-playing personas.
The player would be expected to name her persona.
She may choose a name like Leslie.
Her persona's fake taxonomy name could be Hominidae-Homo Felis-Bobcat
To deliver an anthro walk over to xref:CH04_Anthros.adoc[Anthros]

== Alien Family (Diversidae)

Aliens are basically any organic creatures that are not humanoid in form.
Aliens can be as big as elephants and even whales.
Aliens may be able to fly, or live exclusively in water.
An alien may lack language, have no education or be unable to comprehend tools.
Aliens are 'alien' to players in that the player must drop all humanoid expectations.
The taxonomy of aliens is as diverse as it's family implies.
A player must name her persona as well as create the name of her species.
If her persona was a 600 kg floating alien that looked like a cow octopus she may create a fake taxonomy name of Diversidae-Bovo Octopi.
To evolve an alien fly over to xref:CH06_Aliens_.adoc[Aliens]

== Robot Family (Machinae)

Robots include all inorganic, fabricated life forms. 
Robots are even more alien than aliens. 
Robots even have different rules of engagement from other life forms.
A robot persona has a tenuous grasp on it's free will.
The free will of a robot is entirely based on malfunction.
The more damaged the robot becomes, the more independent it becomes.
Players are encouraged to name their sentient robots with pet names. 
The fake taxonomy of a robot is based on it's fabrication.
A robot named Leslie could be Machinae-Boomtown Dynamics-Combot-Heavy.
To fabricate a robot roll over to xref:CH05_Robots_.adoc[Robots]

Artificial intelligence is a form of machinae that is left to the referee's discretion.
AI in modern speculative fiction would be a campaign based choice by the referee.

== Choosing a family.

The family of a personas is left entirely up to the referee.
Players are expected to primarily generate anthros.
Aliens and robots are exceptions set aside for experienced players.
Beyond the limitations of the referee's story persona family is entirely a choice.
Most of persona generation in EXP is random.

include::ROOT:partial$CH04_Table_Family_Random.adoc[]














