= Anthro Hit Points

Hit points (HPS) measure how much physical punishment a persona can endure before going unconscious and dying.
An anthro's constitution determines her physiologic health.
In turn, her constitution determines her hit points.

Hit points has two components.
The first component is the fixed hit point max (HPM).
The second component is the dynamic hit point total (HPT).
When someone asks how many hit points a persona has, one responds with the hit point max value.
When someone asks how many hit points a persona has left, one responds with their hit point total. 
The hit points max is full health, and the hit point total is present health. 


== Hit Point Max (HPM)
A persona's hit points is determined by rolling d8s.
A player rolls 1d8 for every two points of CON.
The sum of these d8s comprises the largest component of the HPS. 
A player whose persona has a ten constitution would roll 5d8 and add them together.
The player then adds one hit point per one point of constitution her persona has. 
The persona described in this paragraph would get 5d8 + 10 hit points.
Rolling the eight siders and adding her constitution is how the player determines her persona's hit points maximum.

=== Anthro Hit Points Max Calculation
// tag::Anthro_HPS[]
.HPS = (1/2 CON x 1d8) + CON
****
A persona with a CON of 11 would roll 6d8 and add 11. Rounding benefits the player.
****
// end::Anthro_HPS[]

== Hit Points Total (HPT)
Hit points total reflects the number of hit points the persona has left.
The more hit points the persona has left, the healthier they are.
If the hit points total drops to zero, bad things start to happen. 
If the hit points total drops below zero, the persona is dying.

== Hit Points Minimum (Death)
When the persona loses enough hit points, she is dead.
Death represents a specific negative hit point total.
The hit points minimum is "negative half" her hits points maximum.
A persona with a hit points max of 42 would be irrevocably dead at -21 hit points total. 
If the persona in this paragraph loses 63 hit points at once, she is instantly dead.

Hit points minimum is also called negative one half of one's HPT.

=== Anthro Minimum HPT Calculation
.Death = -1 times (1/2 max HPM)
****
For example an anthro persona with 30 HPM would be dead if her HPT dropped to negative 15 (-15).
****

Hit points is an attribute that can drop below one without killing the persona.
A persona with a negative hit point total is unconscious and dying from physical trauma.
Having a negative hit point total is often referred to as "being negative."
A persona with a negative hit points total is unconscious and can do nothing other than lay about and bleed.

The persona loses one hit point every five units (10 seconds) while her hit point total is negative.
A persona at -2 hit points will drop to -3 hit points five units later, and then -4 hits points 10 seconds after that.
This physiologic collapse continues until the hit point total reaches her hit point minimum, and the persona is dead.
This rapid decline to death does not stop unless medically treated.

For more information about healing and death jump to xref:i-roll_playing_rules:CH13_Health.adoc[Health,window=_blank].

NOTE: Damage system shock and recovery rolls are optional rules. 

== Damage System Shock
Damage system shock (DSS) checks to see if a persona is incapacitated by a bolus of damage.
Whenever a persona loses more than half her hit point total in one attack, she must make a DSS roll or fall unconscious.
The DSS is a specialized attribute roll that takes into consideration the persona's hit point total.

=== Damage System Shock Roll (DSS)
// tag::Anthro_DSS[]
.1d20 + HPT + CON + LVL > 42
****
A 1st level anthro with 30 HPT and 10 CON  must roll 1 on 1d20.
A 1st level anthro with 20 HPT and 10 CON  must roll 11 on 1d20.
A 1st level anthro with 11 HPT and 10 CON  must roll 20 on 1d20
****
// end::Anthro_DSS[]

== Recovery Roll
A recovery roll (REC) is a check to see if a persona awakens from their trauma-induced slumber. 
The persona remains inactive until she makes a successful recovery roll.
The REC is a specialized attribute roll that takes into consideration the persona's hit point total.

=== Recovery Roll (REC)
// tag::Anthro_REC[]
.1d20 + HPT + CON + LVL > 32
****
A 1st level anthro with 20 HPT and 10 CON  must roll 1 on 1d20.
A 1st level anthro with 6 HPT and 10 CON  must roll 15 on 1d20.
****
// end::Anthro_REC[]

Recovery rolls only apply to personas with an HPT greater than 0. 
The player can check every few units during combat or whenever the referee feels a recovery roll is appropriate.
Once combat has ended, all stunned personas should immediately recover and join in on the game.


