= Anthro Attributes

Anthro attributes are generated randomly and added to the persona record sheet.
Attributes determine both the physical abilities and type of the anthro persona. 
Randomly determining anthro attributes is based on ruleset legacy and game balance.
Using multiple dice to generate random numbers creates more organic ability curves.
The weak and strong are outliers. 

include::ROOT:partial$CH04_Table_Anthro_Gen_Attr.adoc[]

== Mind Adjustment
The Mind of an anthro persona increases with her intelligence. 
This Mind adjustment is only for anthro personas. 
Most referees will not reduce a persona's Mind during persona creation. 
The intelligence adjustment of Mind can lead to a persona with a negative attribute. 
Attributes less than one is fatal for personas. 

include::ROOT:partial$CH03_Table_Mental_Strength_Adjustment_by_Intelligence.adoc[]

== Alternate Generation Systems
It is easy enough to incorporate alternate attribute generation systems.
EXP bases all its rules on a system where 3 and 18 are rare attribute scores. 
Bonuses and penalties in EXP reflect anthro attributes based on this on the three die six curves.
Small increases in average attribute scores can lead to powerful personas.
The referee and players should choose the approach that works best for them.
Don't let rules get in the way of the story or the fun.

=== Drop the lowest
Drop the lowest is a simple enough mechanism for increasing anthro attributes.
Players roll 4d6 and drop the lowest die roll. 
If a player rolls 4, 3, 5, and 2, she drops the 2, and her total is 12. 

The impact on the nature of the game using drop the lowest is astounding. 
Expeditions are composed of powerful vocations like spies and knites.
The rule set still works, and using drop the lowest is up to the players and referee.

====
Using python computer models generating personas with drop the lowest made the vocations spie, and knite, commonplace vocations.
====

For technical reasons, Social Standing and hit points cannot be part of drop the lowest. 

=== Roll and assign
Roll and assign is a system that preserves the 3d6 curve and still allows players to alter their attributes as desired. 
The player rolls her attributes in the standard fashion used 3d6.
She can then move the attribute scores around as she sees fit.
She can swap her 12 awareness with her 16 charisma.
If the referee and players want to have an expedition of knites, then include Mind in this process.

For technical reasons, Social Standing and HPS cannot be part of the roll and assign system. 

=== Point System
Point system attribute generation has no random component at all.
The player gets a collection of points that they distribute between appropriate attributes. 
A typical point system is based on a 3d6 system and gives 70 points.
A generous point system is based on 4d6 drop lowest and gives 91 points.

Point systems become alarmingly complicated, very rapidly.
In theory, point systems allow players to create the persona they want.
However, the amount of time spent couriering points around is time-consuming.
Many players find the responsibility of creating their personas de novo stressful.

Players are smart and creative, and the referee may need some rules for the point assignment.
The player must assign at least 3 points to each of her attributes is a good start. 
The referee may limit point assignment to Mind to keep variety in the expedition.

For technical reasons, Social Standing and HPS cannot be part of a point system.
