= Rodentia

:art: rodentia.png
:width: 250px
:snark: Rodent operatives.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid rat and short humanoid mole dressed like spies.

include::ROOT:partial$articulate.adoc[]

// Table 4.15 Rodentia Data
.*Rodentia Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|Rodent data for player personas.

s|Attribute Minimums
2+<|CHA 12

s|Attribute Adjustments
2+<|AWE +2; DEX +1; PSTR -1

s|Age
2+<| 5-25 (1d20+4) years

s|Abilities
2+<|<<_speedy,Speedy>>, <<_night_vision,Night Vision>>

s|Size
s|Hite (cm)
s|Wate (kg)
// One size fits all not present

|Small
|175+(2d20)-20
|71

|Large
|175+(2d20)-15
|71

3+<|xref:CH04_Anthros_Size.adoc[Calculate Hite and Wate]

|===

Rodentia is short for Hominidae Homo Rodens.
Rodentia are humanoid rat people.
Rodentia can appear as beaver, kangaroo, rat, mouse, mole, porcupine, hedgehog, gopher, platypus, hamster, gerbil, squirrel, etc.
Every rodentia has two arms, two legs, a torso and a face.
Rodentia are fur covered humanoids with paws, rodent heads and tails.
Rodents have none of the powers of their chosen type.
For example, a rodentia beaver cannot chew timber, and a platypus would not be poisonous.

== Speedy
Rodents can move fast and are uninhibited by terrain.
All rodentia get a movement bonus of +20%.
So a rodent that has a five h/u move would now move at six h/u.
Rodents are unaffected by familiar terrain.
So if a rodent is running through thick grass, she would not suffer any movement penalty.

== Night Vision
Rodentia have limited night vision.
The night vision does not work if artificial light is present. 
For example, a torch or searchlight would disable rodent night vision.
In complete darkness, a rodent can see two hexes per point of awareness. 
A rodentia with a 12 awareness can see 24 hexes in darkness.


