= Feline

:art: feline.png
:width: 250px
:snark: A catsi tab.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid cat leaning on taxi cab.

include::ROOT:partial$articulate.adoc[]

// Table 4.9 Feline Data
.*Feline Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|Feline data for creating this anthro type is below.

s|Attribute Minimums
2+<|AWE 8; CHA 8; DEX 13

s|Attribute Adjustments
2+<|DEX +2; CON -2; PSTR -1

s|Age
2+<|5-10 (1d6+4) years

s|Abilities
2+<|<<_ambush,Ambush>>

s|Size
s|Hite (cm)
s|Wate (kg)


|Skinny
|150+(1d20)-9
|45

|Chubby
|150+(1d20)-6
|48

3+<| xref:CH04_Anthros_Size.adoc[Calculate Hite and Wate]

|===

Feline is short for Hominidae Homo Felis.
Felines are humanoid cat people.
Some of the cat types that felines may resemble are: Siamese, Manx, lion, tiger, puma, jaguar, leopard, ocelot, etc.
Felines have furry bodies, long slender tails and mouths full of sharp little teeth.
All felines have the same abilities. 
For example, a leopard feline persona could *not* accelerate up to 100 km/h.

Felines have excellent balance and agility.
All felines have a +30% movement bonus.
A feline with a move of 5 h/u increase to 7 h/u.


== Ambush
Civilized felines have evolved beyond sneaking up on dinner in the darkness.
They now prefer to buy dinner at the local grocer.
The skill of night stalking remains.

=== Night Vision
Homo Felis has equal nite/day vision.
This allows them to operate in darkness without any penalty.

=== Ambush Bonus
An ambushing feline can subtract her DEX from the target’s AWE.
So if a feline with a 14 DEX is trying to ambush a target that has a 16 AWE, the target’s effective AWE is reduced to 2.
This drastically improves the change of a successful ambush.
To fully realise this ability the feline must be ambushing alone or with other felines.
The referee can reduce the ambush bonus depending on the makeup of the expedition.






