= Humanoid

:art: humanoid.png
:width: 250px
:snark: Guerilla gardening.
:artist: Peggy Lynn McIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid gorilla holding a hoe in front of corn plants.

include::ROOT:partial$articulate.adoc[]

// Table 4.11 Humanoid Data
.*Humanoid Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|All the deets for humanoid treats

|Attribute Minimums
2+<|CHA -9

s|Attribute Adjustments
2+<|CHA -2

s|Age
2+<|13-18 (12+1d6) years

s|Abilities
2+<|<<_mutability,Mutability>>

s|Size
s|Hite (cm)
s|Wate (kg)

|Tall
|169+(2d20)-20
|62

|Taller
|176+(2d20)-20
|71

3+<|xref:CH04_Anthros_Size.adoc[Calculate Hite and Wate]

|===

Humanoids is short for Hominidae Homo Mutabilis.
Humanoids can appear as any hominid type.
Humanoids can appear as simians (monkeys, apes), suidae (pigs, boars), elves, dwarfs, orcs, human beings etc.
Humanoids resembling humans can sport any colour: white, black, red, yellow, green, blue, etc.
None of these humanoid types have any of their mythical abilities.
Humanoids that resemble elves or leprechauns would have none of their mythical abilities.

== Mutability
Homo mutabilis has no abilities other than their extreme susceptibility to mutation.
If a player wants her humanoid persona to have mutations, she automatically gets mutations. 
If a player does not want her humanoid persona to have mutations, she will likely get them anyway.

