= Families

// recommended players skip to anthros
// challenges and benefits

[quote]
____
*EXP's three families are Alien, Anthro and Robot.*
____

Every persona, from the evilest referee persona to the kindest player persona, has a family.
The three types of families found in EXP are anthros (humans, canines, felines, etc.), robots (janitorial, combot, android, etc.) and aliens (carnivorous plants, pulsating blobs, flying bear slugs, etc.).

On mundane terra, science uses genetics and observation to create a https://en.wikipedia.org/wiki/Taxonomy_(biology)[taxonomy of life,window=_blank].
The biological taxonomy organizes life into domains, kingdoms, phyla, class, order, etc.
EXP ignores all of this in the name of sciency fiction and simplicity, creating its own faux taxonomy.

The faux taxonomy ignores the first six divisions in the schema and focuses on family, genus and species.
The families, genus, and species reflect the life form's appearance and function, not its genetics.
It is even simpler to use their familiar names: anthro, alien, and robot.

.*EXP's Faux Taxonomy*
* *Domains, Kingdom, Phylum, Class, Order:*  are ignored
* *Family:* 
** Hominidae (Anthro)
** Machinidae (Robot)
** Diversidae (Alien)
* *Genus:*
** Anthro = Homo
** Alien = Determined at generation
** Robotic = Fabricator Name
* *Species:*
** Anthro = Avis, Aqua, Canis, Felis, etc.
** Alien = Determined at generation
** Robot = Android, Combot, Hobbot, Rescue

:art: life_in_colour.png
:width: 750px
:snark: Life's what you make it. 
:artist: HM
:date: 2019
:license: CC BY-SA 4.0
:description: Chart showing the fake persona families that exist in EXP.
include::ROOT:partial$articulate.adoc[]

The referee is welcome to use whatever naming structure suits their campaign.
The aliens could all be robots.
The anthros could be aliens.
Don't let the rules get in the way of a good story.

== Anthro Family (Hominidae)
Anthros are organic upright bipedal humanoids that are immediately relatable to players.
Anthros have a shape, structure and physiology most similar to our own. 
Anthros possess language, culture, vocations and norms that are familiar to us from mundane terra. 
Most player personas will be anthros. 
Beginning players should only deliver anthro personas.
To deliver an anthro, walk to xref:CH04_Anthros_.adoc[Anthros,window=_blank]

== Alien Family (Diversidae)
Aliens are organic creatures that have extremely diverse shapes, sizes, and abilities.
Aliens can be as small as mice or as big as elephants.
Aliens may fly in the sky or live underwater.
Due to their random shape and diverse abilities, alien personas require experienced players to avoid the creature's 'personification.'
Not only may aliens lack hands and feet, but they also may lack language, tool use and culture.
Most aliens will be referee personas acting as a friend, foe or dinner to player personas.

When creating an alien persona, the player is creating an entire species.
A player persona alien will only represent one creature, but the generation has all the information for an entire alien species.
To evolve an alien fly to xref:CH06_Aliens_.adoc[Aliens,window=_blank]

== Robot Family (Machinidae)
Robots are inorganic life-forms intentionally fabricated from inorganic materials.
A properly functioning robot does not have consciousness or free will.
Persona robots get their consciousness and free will from random malfunctions in their complicated programmes and parts.
The more damage the robot sustains, the more free will she acquires.
Unlike an organic persona, a robot persona can lose her free will if she is subject to repairs or commands. 

Robot personas are more 'alien' to players than alien personas are.
Robots have no familiar body parts, no facial expressions, no fatigue, no social pressure, no culture, and no familiar goals or desires.
Most robot personas will be referee personas. 
To fabricate a robot, roll to xref:CH05_Robots_.adoc[Robots,window=_blank]

== AI (Machinidae)
AI are inorganic life forms intentionally fabricated to have consciousness and free will.
They are not considered personas and are not the fourth pathway for player personas. 
They are listed here for completeness. 

A player creating an AI persona would require the referee to develop an entire milieu for the AI experience.
The referee may even need to develop an entire rule system to account for the AI's knowledge base and data acquisition continuum.
An AI is exclusively in the domain of a referee persona.
To fabricate and AI transfer to xref:v-wetware:CH69_AI.adoc[Artificial Intelligence,window=_blank].


== Random Family 
Random family determination is usually for referee personas.
Beginning players should use anthro personas to learn the EXP rule set.
Experienced players may be up for a unique experience. 

include::ROOT:partial$CH04_Table_Family_Random.adoc[]















