= Reptilian

:art: reptilian.png
:width: 250px
:snark: Reptilian with light sword.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid reptile knee deep in water holding light sword.

include::ROOT:partial$articulate.adoc[]

// Table 4.14 Reptilian Data
.*Reptilian Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|Data sheet for reptilian player personas.

s|Attribute Minimums
2+<|MSTR 13; PSTR 10

s|Attribute Adjustments
2+<|CHA -2; CON +1; MSTR +3

s|Age
2+<|21-40 (1d20+20) years

s|Abilities
2+<|<<_chameleon,Chameleon>>, <<_torpor,Torpor>>

s|Size
s|Hite (cm)
s|Wate (kg)

|One size fits all.
|165 + (3d20)-30
|50

3+<| xref:CH04_Anthros_Size.adoc[Calculate Hite and Wate]

|===

Reptilian is short for Hominidae Homo Serpens.
Reptilians are upright, bipedal lizard people.
Descriptive choices include: salamander, snake, iguana, gator, turtle, frog, tyrannosaur, brontosaur, etc.
The reptile type is only a decoration.
Every reptilian has two arms, two legs, a torso and a face.
Reptilians may have scaly hide, forked tongues, and decorative tails.
It is possible their skin may make good boots.
Reptilians possess none of the abilities from their description.
For example a black adder would not have a poisonous bite.


== Chameleon
All reptilians have a camouflaging ability.
Chameleon allows the persona to blend into the background.
There are many caveats to the chameleon ability.
The persona must be completely naked, and stationary.
The circumstances must be appropriate as well.
Chameleon does not work under direct gaze.
Nor would chameleon work if the background is overly dynamic.
For example, a reptilian could not disguise themselves against a projection in a crowded room. Chameleon only works on the visual spectrum so alternate vision systems cannot be fooled.

If conditions permit the reptilian may attempt to blend into the background. 
There is a 10% chance per point of Charisma of successfully blending in. 
For example, a reptilian with CHA 11 would have a 110% chance of disappearing into the background.
Once activated the persona disappears unless touched or they move. 
The reptilian will know if they have successfully blended in. 

====
In previous incarnations of EXP chameleon could fail without the persona knowing.
This seemed pretty funny to the referee at the time.
However this is a kindler gentler version of EXP.
====

== Torpor
Torpor is a trance-like state where the reptilian can enhance healing and resist damage.
A reptilian can choose to enter torpor whenever they wish.
Reptilians cannot go into torpor if they have less than 0 hit points.

Once torpor is activated by the reptilian she will remain in this state for 2d6 (2-12) days. 
Torpor is a huge commitment to say the least.
The number of days unconscious is rolled by the referee and is kept secret from the players.

In this state of selective metabolism, the reptilian will heal 3 hit points each day.
Torpor will also reduce the effects of poisonous atmospheres.
When in torpor radiation, heat, cold, ingested or inhaled toxin are reduced in effect.
Torpor reduces the impact cutting the intensity and effect in half.
Corrosive, explosive and fire attacks damage the reptilian normally and are unaffected by torpor.
