= Social

:art: social_robot.png
:width: 250px
:snark: Social robot interrupting someone.
:artist: unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of bug eye humanoid robot tapping woman on shoulder.

include::ROOT:partial$articulate.adoc[]


//  Social Fabrication Data 
.*Social Robot Fabrication Info (S)*
[width="75%",cols="2*<"]
|===
2+<|Fluent in languages, etiquette and irritation

2+<|*Attributes*

|Ranges
|CON 1 or 2; DEX 1 or 2; INT 3 or 4; PSTR 1

|Minimums
|Nil

|Hit Points
|2-4 (1+d3) per point of CON

|Adaptability
|50%

|Size
|Medium

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|10% roll on Table 1

|Defensive
|84% for 1 roll (non-lethal)

|Peripheral
|100% for 1 roll on Primary
|===

Social robots look after the social needs of organic personas.
They are also called robutlers, relation bots, or protocol droids.
Social bots roughly resemble their fabricator type.
This resemblance is purely for aesthetics and they are obviously inorganic robots.
If the player wishes she can replace the rolled Locomotion type with articulated legs.

== Language and Culture
Social robots speak the language of their fabricator type and many others.
This robot can speak 10 language per point of INT. 
So a persona with a 11 INT could fluently speak 110 languages.
If a new language is encountered the robot may already understand it.
The chance of already knowing the language a percent change equal to her INT score.
So a persona with a 11 INT would have an 11% chance of already knowing.
If a language is not already in the library the robot will acquire it in 1d4 days. 

Culture is more complicated than language. 
A social robot can understand the nuances of a culture to assist other personas.
This is often done pedantically and does not guarantee seamless interactions.
The social robot's CHA would still play a role in the roll playing.
The robot can understand 1 culture per point of INT. 
So a persona with a 11 INT could understand 11 cultures..
If a culture is not already in the library the robot will acquire it in 1d4 weeks. 

== Butler Skills
If the social robot understand the language and culture of a persona they can serve them.
This means preparing meals, making up rooms, and tending to other needs. 
They do this well and take this task most seriously.
If the social robot is required to tend to the needs of guest outside of her library she will complain endlessly.
Robutlers can also tend to the needs of 4 guests per INT score.
So a persona with a 11 INT could feed, water and entertain 44 personas.


include::ROOT:partial$CH05_Table_Robotic_Base_Anthro_Type.adoc[]
