= Transportation

Transport robots are the truckers, pilots and chauffeurs from the robot world.
They make every vehicle a self driving driving vehicle.
While they can drive combat vehicles they are not versed in vehicle combat.
Their goal is to get passengers and cargo safely to the chosen destination.

The two types of transportation robots are inatmo and exatmo.
Inatmo transport robots are fabricated to pilot planetary vehicles. 
Exatmo transport robots are fabricated to pilot space-vehicles. 

NOTE: *INTAMO* - short for in atmosphere. Gravity, weather, roads and ground. +
*EXATMO* - short for exterior to atmosphere. Vacuum, special jumps, near light speed.

:art: inatmo_transport_bot.PNG
:width: 250px
:snark: Ware 2
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a boxy floating robot holding a steering wheel.

include::ROOT:partial$articulate.adoc[]


== Inatmo Transport Robot

//  Planetary Transport Fabrication Data 
.*Inatmo Transport Robot Fabrication Info (T-I)*
[width="75%",cols="2*<"]
|===
2+<|Cybernetic chauffeur for all manner of planetary vehicles.

2+<|*Attributes*

|Ranges
|CON 1; DEX 1, 4; INT 1, 4; PSTR 1

|Minimums
|Nil

|Hit Points
|9-12 (8+d4) per point of CON

|Adaptability
|15%

|Size
|Small

|Value:
|100000 times 2d6

2+<|*Systems*

|Offensive
|50% roll on Table 1

|Defensive
|40% for 1 roll

|Peripheral
|100% for 1 roll on Primary
|===

Inatmo transport robots can pilot any planet side vehicle.
This includes trains, planes, cars, boats, submarines.
This does not include non-powered vehicles like bicycles or skateboards.

=== Driving
Inatmo transport robots have attachments that allow it to drive any vehicle.
This mean almost any vehicle from xref:iii-hardware:CH54_Vehicles.adoc[Vehicles]. 
This does not include self powered vehicles.
The inatmo transport bot can pilot two vehicles per point of INT score.
A persona with an 11 INT could drive 22 separate vehicles. 
The chance that this robot already pilot the vehicle is 1% per point of INT.
A persona with an 11 INT has an 11% chance of already knowing how to drive a vehicle.
Inatmo robots are quick learners and can add a new vehicle navigation system in 1d4 minutes.
If the robot fills it's driving library it can delete one of the vehicles.

=== Navigating
An inatmo transportation robot can find it's way around with amazing accuracy.
If the robot is in a familiar city it cannot get lost. 
Bad directions can be interpreted with alarming accuracy.
The inatmo transport bot's navigation programming should be abused.
The robot can easily find the grove of trees near the bend in the creek with big rocks.
The robot cannot be used to find a place where none of expedition has not been.
For example, find the bad referee persona's hide out please would not work.

== Exatmo Transport Robot

//  Extra-Planetary Transport Fabrication Data 
.*Exatmo Transport Robot Fabrication Info (T-X)*
[width="75%",cols="2*<"]
|===
2+<|Cybernetic chauffeur of celestial vehicles.  

2+<|*Attributes*

|Ranges
|CON 1; DEX 1, 4; INT 1, 4; PSTR 1

|Minimums
|DEX 22 INT 22

|Hit Points
|9-12 (8+d4) per point of CON

|Adaptability
|15%

|Size
|Small

|Value:
|100000 times 4d6

2+<|*Systems*

|Offensive
|50% roll on Table 1

|Defensive
|40% for 1 roll

|Peripheral
|100% for 1 roll on Primary
|===

Exatmo transport robots can pilot and navigate space-vehicles.
This includes spaceships, starships, space cruisers, jump ships, etc..
This does *not* include vehicles that are planet side. 
An exception could be made for a low orbit plane. 
This would be up to the referee and players.
An exatmo transport robot cannot drive regular vehicles at all.
This mean almost any vehicle from xref:iii-hardware:CH52_Space_Vehicle.adoc[Space-Vehicles]. 
The exatmo robot is dedicated to moving personas and cargo safely from one location to another.
These robots do not have combat training.

=== Piloting
Space-Vehicles will usually have some mechanism of integrating with the exatmo bot.
If there is no access port the exatmo bot will have the necessary appendages.
Piloting a space-vehicle refers to all inatmo and exatmo drive piloting. 
This involves sub light speed travel, exiting or entering an atmosphere. 
It does not include special drive piloting which is specifically astrogation.

=== Astrogation
Astrogation involves navigating the space-vehicle across many light years in an instant.
It requires non-existent math and special drives like warp, bubble, or probability.
This transport bot replaces an astrogator and integrates directly with the ship's computer.
There will always be a robotic connection to the ship for astrogation.
The robot cannot pilot and astrogate at the same time.

