= Industrial

Industrial robots have been fabricated for specific tasks related to industry.
These are usually the first types of robots that a fabricator type makes. 
Hence the differentiation.

// new table for 6.0
//  Robot Attribute Requirements 
.*Industrial Robot Attribute Requirements*
[width="75%",cols="2*<"]
|===
2+<| Attribute requirement for industrial robot type

s|Industrial Type
s|Attributes

|Builder
|INT > DEX + 
INT > PSTR

|Lifter
|PSTR > DEX  + 
PSTR > INT

|Mover
|DEX > INT + 
DEX > PSTR

s|Industrial Type
s|Attributes
|===

== Industrial Builder Robot

//  Construction Fabrication Data 
.*Industrial Builder Fabrication Info (I-B)*
[width="75%",cols="2*<"]
|===
2+<|It will come. Then you build it.

2+<|*Attributes*

|Ranges
|CON any; DEX 2 or 3; INT 1 or 2; PSTR 4

|Minimums
|INT > DEX and INT > PSTR

|Hit Points
|9-12 (8+1d4) per point of CON

|Adaptability
|25%

|Size
|Medium

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|2 rolls Table 1 *ONLY*

|Defensive
|15% for 1 roll

|Peripheral
|100% 1 Primary +
10% 2nd Primary
|===

Builder bots are mobile assembly machines.
A builder bot is usually not part of the design process.
Designing usually requires input from a mechanic.
Once programmed the builder bot gets right too it.
The builder will source supplies, and create widgets until out of supplies. 
In austere environments it can take a long time to acquire construction materials
Builders with  22 INT score can design objects (cups, ball, combs, toys).
Programming a builder bot is a Mechanic maneuver.
The more valuable the item, the more difficult the Degree of Difficulty.
The robot is not made to replicate fancy high-tech weaponry or other such goodies.
A builder robot offers a huge bonus to mechanics that are building something.

== Industrial Lifter Robot

//  Lifting Fabrication Data 
.*Lifter Robot Fabrication Info (I-L)*
[width="75%",cols="2*<"]
|===
2+<|Always gonna lift you up. May let you down.

2+<|*Attributes*

|Ranges
|CON any; DEX 2 or 3; INT 1 or 2; PSTR 4

|Minimums
|PSTR > DEX and PSTR > INT

|Hit Points
|9-12 (8+1d4) per point of CON

|Adaptability
|25%

|Size
|Large

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|35% for 2 rolls Table 1 *ONLY*

|Defensive
|15% for 1 roll

|Peripheral
|100% 1 Primary
|===

Lifting bots are former cargo hoists from warehouses or department stores.
Lifting bots are capable of supporting one object per three points of DEX.
So a lifting bot with a 12 DEX would have 4 articulations for lifting.
The objects lifted by one arm cannot exceed 3 times the bots Weight Allowance.
If the robot has multiple lifters, they can coordinate to lift a heavier single object.
Objects can be lifted to a height five times the bots Hite.

If something does not want to be lifted the lifting bot must make a successful attack roll. 
A robot can make one attack per lift articulation.
This grab is not a damaging attack. 
Lifting bots will spend a lot of time grabbing and damaging targets by dropping them.

Lifting bots were not made to drop things.
A malfunctioning lifting bot may have been fired for dropping things. 
The player must make a Control Factor roll to successfully drop an object.
Another Control Factor check is required if the target is from her fabricator type.
Falling damage is determined xref:ii-non-combat-rules:CH19_Terrain.adoc#Falling[here]

== Industrial Mover Robot

//  Moving Robot Fabrication Data 
.*Mover Robot Fabrication Info (I-M)*
[width="75%",cols="2*<"]
|===
2+<|Move it. Store it. Catalogue it.

2+<|*Attributes*

|Ranges
|CON any; DEX 2 or 3; INT 1 or 2; PSTR 4

|Minimums
|DEX > INT and DEX > PSTR

|Hit Points
|9-12 (8+1d4) per point of CON

|Adaptability
|5%

|Size
|Gigantic

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|2 rolls Table 1 *ONLY*

|Defensive
|15% for 1 roll

|Peripheral
|100% 1 Primary
|===

Mover bots can easily be mistaken for intelligent trucks  
A mover robot can carry 10 times their robotic wate allowance
Moving robots get a bonus of 50% on their movement rate.
This robot can read maps and understand even the worst directions.
Mover bots can remember 10 way points per INT score. 
An industrial mover bot can always find its 'way' between way points. 
Way points do not work from planet to planet.

Moving bots are self loading. 
The robot can lift an object twice it's wate allowance when loading.
The lifting articulation for a mover bot cannot be weaponized.
A mover bot cannot force an unwilling target into it's cargo hold.
Lifter and mover bots can make a great team. 
