= Robot Locomotion

Locomotion indicates how the robot moves from one location to another. 
The locomotion type affects the robot's appearance and how it can move in the game. 
Some locomotion types allow for three-dimensional flight. 
Some locomotion types are a combination that impacts both its appearance and function in the game.

The player makes a roll on the Primary Locomotion Table. 
All types of locomotion perform equally.
The locomotion type indicates if a complementary locomotion type is needed.
For example, a robot propelled by jets may have wheels as well. 
This robot would be bound to the ground.
A robot propelled by jets with a complementary antigrav system would be able to fly around. 

:art: quadpodbot.png
:width: 350px
:snark: No treads on me.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Stumpy robot with treads for locomotion.

include::ROOT:partial$articulate.adoc[]

The locomotion type does not determine how fast the robot moves.
The robot's dexterity score determines her movement rate.
For more info jump to xref:i-roll_playing_rules:CH05_Robots_Z_Move.adoc[Robot Movement Rate,window=_blank].

All locomotion types function equally.
So a robot with three pods would move the same as a robot with one track. 

include::ROOT:partial$CH05_Table_Robotic_Primary_Locomotion.adoc[]

include::ROOT:partial$CH05_Table_Robotic_Secondary_Locomotion_Type.adoc[]

== Antigrav
Antigrav is a classic sciency fiction term for anti-gravity.
The robot can travel about as though gravity does not affect it.
The robot can fly and flit around the environment.
The robot has no obvious mechanisms that create its buoyancy in gravity.
As ideal as antigrav is, it will only function within a gravity well.

=== Complementary Antigrav
Complementary antigrav floats the robot, while the primary locomotion type moves the robot.
For example, a robot with jets and antigrav would float by antigrav and maneuver by the jets.
The antigrav jet-driven robot would look like it is flying by jets but can float with all jets off.

== Chemical Slide
The chemical slide allows the robot to slide along any surface effortlessly.
This locomotion leaves a quickly evaporating trail, not unlike a slug from mundane terra.
A chemical slide does not imply the robot will be slow.
The robot's dexterity score determines her movement rate.
A chemical slide operates on any terrain equally well.  
The chemical residue may be grosser on sand than on a metal floor.

=== Complementary Chemical Slie
A complementary chemical slide offers a frictionless surface, and the primary locomotion propels it. 
For example, a robot with jets and chemical slide would stay grounded and be pushed around by jets. 

== Electromagnetic Legs 
Electromagnetic legs are visible beams that move the robot around.
A robot will have 1 to 6 (1d6) electromagnetic legs.
These legs keep the robot about a meter off the ground. 
They keep the robot level on varying terrain.
Electromagnetic legs do not work on water.

== Jets
Robotic jets force gases at high speed to generate movement.
A robot will have 1 to 6 (1d6) jets.
The jets create thrust and maneuverability.
Robotic jets are intake-less and do not eject dangerous super-heated propellants.
Whether jets work exatmo or not is up to the referee.

== Magnetic
A magnetic locomotion unit allows the robot to hover above the ground.
The robot can hover no higher than one hex above the ground.
Magnetic locomotion is not a flying type of locomotion.
Robots with magnetic locomotion will often float around long after their destruction.
Magnetic locomotion can travel above any solid or liquid.

== Pistons
Pistons quickly poke up and down, keeping the robot balanced and moving.
A robot has 1 to 10 (1d10) pistons.
The pistons are immaculately timed and keep the robot stable.
Even a single-piston robot will be steady and balanced.
Pistons must have a solid surface to operate.

== Pods
Pods are mechanical legs with at least one articulation.
The robot has 4 to 16 (4d4) pods.
These articulated poles will hop, scuttle or patter the robot around the terrain.
Pods require a solid surface to operate.

== Propellers
Robotic propellers are quiet, high-powered and safely encased airscrews.
The propellers offer thrust and maneuverability to the robot. 
There are 1 to 6 (1d6) propellers.
Propellers combined with antigrav would allow the robot to fly.
Propellers combined with a chemical slide would propel the slide but not allow the robot to fly.

== Sails
Sails are very sturdy, electro molecular planes that catch air for movement.
Robot sails operate perfectly well in the raging wind or dead calm.
The sails offer thrust and maneuverability. 
The robot will have 1 to 3 (1d3) sails.


== Skis
Skis are attached to powered stems that skate the robot over any terrain type.
There are 3 to 6 (1d4+2) skis.
There is no difference in speed whether the robot is trotting uphill or sliding down slopes.

=== Complementary Skis
If the skis are a complementary Locomotion Type, they do not function the as above.
The skis are attached to articulated pods and not powered stems.
The skis would be the surface contact, but the primary locomotion moves the robot.
There are 3 to 6 (1d4+2) complementary skis.

== Slog bag
A slog bag appears as a fluid-filled sack attached to the robot's undercarriage.
The slog bag undulates and contorts itself along the surface on which the robot travels.
The slog bag moves like a sack of mercury.
However, the bag need not contain a liquid and is not vulnerable to puncture.

== Tracks
Robotic tracks appear as rubber-coated tank tracks.
Each track operates independently, and they maneuver the robot by contorting themselves.
There are 1 to 6  (1d6) tracks.

== Wheels
Robotic wheels are independently powered and controlled.
Wheels are solid, puncture-proof and have individual drives.
There are 1 to 12 (1d12) wheels.
The number of wheels has no impact on the robot's maneuverability or stability.

=== Complementary Wheels
When wheels are a complementary locomotion type, they do not have individual drives.
The primary locomotion type generates the force, and the wheels give the direction.
There are 1 to 12 (1d12) complementary wheels.

== Ref's Own Table
The referee can insert campaign-related locomotion types as she sees fit.
