= Robot Fabricator
There are no Asimovian Three Laws of Robotics in EXP.
Robots are free to smash up what and who they like.
There are some limitations though.
A robot can not wantonly harm persona from it's fabricator type.
This is the species that the robot was designed and manufactured for.
Almost all robots were fabricated by an anthro type.
In general a robot cannot harm their fabricator type. 
Nor would the robot allow her fabricator type to come to harm.
Every robot type, unless specified, follow this programming.

Robots can use non-lethal attacks, restraints, immobilization versus their fabricator type.
A robot would not simply allow itself to be destroyed. 
A robot will also protect a fabricator persona from other expedition members.
This is a major inconvenience that the player must get around when running a robot.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

Fabricator protection programming can be worked around. 
The more insane a robot is the more free will the robot has.
The more insane a robot is, the more flexible the application of this core programmed law.
A robot can justify deadly actions against her fabricator type.
The player would have to make a Control Factor Check.

include::ROOT:partial$CH05_Table_Robotic_Base_Anthro_Type.adoc[]

Most of the results on the Fabricator table are anthros.
If the player rolls anthro type equine her persona would protect and not harm equines.
Every other persona type needs to look out. 
Robots and aliens are crazy challenging.
Robots are recursively impossible. 
The referee may need to fabricate the robot fabricator or evolve an alien to fulfill the roll.
