= Datalyzer

:art: datalyzer.png
:width: 250px
:snark: Think think think.
:artist: JEShields, modified HM 
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Floating robot with an organic brain in a jar.

include::ROOT:partial$articulate.adoc[]

//  Datalyzer Data 
.*Datalyzer Fabrication Info (D)*
[width="75%",cols="2*<"]
|===
2+<|Number crunching, data analyzing, mad machines. 

2+<|*Attributes*

|Primes
|CON 1 or 2; DEX 1 or 2; INT 4; STR 1 or 2

|Minimums
|Nil

|Hit Points
|1-3 (1d2+2) HPS per point of CON

|Adaptability
|15%

|Size
|Small

|Value:
|10000 per INT score

2+<|*Systems*

|Offensive
|5% Level 1

|Defensive
|1 Roll +
24%  2nd Roll

|Peripheral
|1 Primary +
1 Secondary
|===

Datalyzers are tin-can thinkers stuffed with a sciency fiction technomagical mix of organic and inorganic parts. 
At the core of this thinking machine is a semi-organic, electronically enhanced central computing unit.
They are full of complex algorithms and tend to be emotional.
A datalyzer can even have a mental mutation.
The chance of having a mental mutation is the same as its fabricator type plus its intelligence score.
The mental mutation cannot be a defect. 
The datalyzer has a Mind of zero, like all other robots.
The robot's intelligence score replaces Mind when required.
Datalyzers used to be called analog monitors.
