= Datalyzer

//  Datalyzer Data 
.*Datalyzer Fabrication Info (D)*
[width="75%",cols="2*<"]
|===
2+<|Number crunching, data analyzing, mad machines. 

2+<|*Attributes*

|Primes
|CON 1 or 2; DEX 1 or 2; INT 4; PSTR 1 or 2

|Minimums
|Nil

|Hit Points
|1-3 (1d2+2) HPS per point of CON

|Adaptability
|15%

|Size
|Small

|Value:
|10000 per INT score

2+<|*Systems*

|Offensive
|5% Level 1

|Defensive
|1 Roll +
24%  2nd Roll

|Peripheral
|1 Primary +
1 Secondary
|===

Datalyzers used to be called analog monitors.
Datalyzers are tin-can thinkers stuffed with artificial intelligence. 
At the core of the AI is a semi-organic, electronically enhanced central computing unit.
They are so stuffed with complex AI that they tend to be emotional and can have mental mutations.
The chance of having a mental mutation is the same as it's fabricator type plus INT score.
The mental mutation cannot be a defect. 
It is up to the referee and players, but if the semi-organic AI core is organic enough this robot may have a MSTR. 
