= Robot Size

The robot has a general descriptor of its size. 
The robot sizes are Tiny, Small, Medium, Large and Gigantic.
The majority of player persona robots will be either Small, Medium or Large.
The possible robot sizes are somewhat human relatable. 
The size descriptor determines the Hite and Wate of the robot.

There are two additional robot sizes not available to player personas.
These are Minute and Humongous. 
They only appear for referee personas.

== Wate
The Wate of a robot is the combination of mass and weight.
The player records her robot wate in kilograms.
A 100kg robot has the same wate as a 100kg anthro and the same wate as 100kg of feathers.

Wate is critical to robots as it determines how much damage is when ramming.
Ramming is the only universal robotic attack.

include::ROOT:partial$CH05_Table_Robotic_Size_Wate.adoc[]

== Hite
The Hite of the robot is a combination of volume and height.
The player records her robot hite in centimetres.
In most cases, the value of hite will determine how high the robot can reach and what may fit on her chassis.

NOTE: Hite or volume does not alter robot wate. 

If necessary, the player may roll all three dimensions for her robot, calculating the volume occupied by the persona.
The player rolls for height, width and length.
These rolls do not affect the wate of the robot.
The player can arrange the dimensions in whatever order works best for the persona.
If the robot dimensions are ruining a finely tuned player persona, choose story and fun over rules and rolls.

include::ROOT:partial$CH05_Table_Robot_Dimensions.adoc[]
