= Maintenance

:art: maintenance_bot.png
:width: 250px
:snark: Puzzling over ancient Newtek device.
:artist: Andrew Hotz
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of bipedal robot puzzling over toaster.

include::ROOT:partial$articulate.adoc[]

//  Domestic Janitorial Fabrication Data 
.*Maintenance Robot Fabrication Info (J-D)*
[width="75%",cols="2*<"]
|===
2+<|Mechanic in a drum.

2+<|*Attributes*

|Ranges
|CON 1,2; DEX 2, 3; INT 2, 3, 4; PSTR 1

|Minimums
|Nil.

|Hit Points
|1-4 (1d4) per point of CON

|Adaptability
|42%

|Size
|Small

|Value:
|100000 per point of INT

2+<|*Systems*

|Offensive
|40% roll on Table 1

|Defensive
|40% for 1 roll

|Peripheral
|100% for 2 rolls on Primary
|===

A maintenance bot is a mechanic in a drum.
This robot is hardwired with the vocation xref::CH08_Vocations_Mechanic.adoc.adoc[Mechanic].
Maint bots are mostly interested in maintaining, repairing and improving inorganic objects.

The maintenance robot gets more bonuses and skills than a typical mechanic.
The player adds double her INT score to any Performance Table rolls.
The maint bot gets many more skills than the typical mechanic.
Starting out the player gets one roll on the mechanic skill table per point of INT. 

// consider adding skill table here


