= Combot

Combot is a contraction of combat robot.
Combots have been designed to fulfill roles previously held by organic beings.
Combots are supposed to be smaller sized drones that represent a playable scale.
They are not intended to be monstrous city killers that destroy game balance.
However that being said a combot can be deadly campaign upturning killing machines.
Combots are objective driven and do not worry at all about fabricator protections.
A combot persona is without clear direction and is likely more disturbed that other robots.
This does not mean combot is not without rules of engagement and rules of war.
A combot should not be an indiscriminate destroyer of everything.

Combots are broken robots that are no longer under the control of a commander or corporation.
The more powerful the combot the more likely a powerful owner is looking to control it.

// new table for 6.0
//  Robot Attribute Requirements 
.*Combot Attribute Requirements*
[width="75%",cols="2*<"]
|===
2+<| Attribute minimums required for combot type

s|Combot Type
s|Attributes

|Expendable
|Nil

|Defensive
|CON 20

|Light Offensive
|CON 19; DEX 15

|Heavy Offensive
|CON 23; PSTR 27

s|Combot Type
s|Attributes
|===

// Expendable combat robot Expendable combat robot

== Expendable Combot

:art: combot_expendable.png
:width: 250px
:snark: Expendable combot.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a walking robot with a target on it's helmet.

include::ROOT:partial$articulate.adoc[]

//  Expendable Data 
.*Expendable Combot Fabrication Info (C-E)*
[width="75%",cols="2*<"]
|===
2+<|High casualty cannon fodder for peace keeping or worse. 

2+<|*Attributes*

|Ranges
|CON 2 or 4; DEX 4; INT 1 or 3; PSTR 4

|Minimums
|Nil

|Hit Points
|5 HPS per point of CON


|Adaptability
|15%

|Size
|Medium

|Value:
|1000000

2+<|*Systems*

|Offensive
|1 roll Table 1

|Defensive
|1 roll

|Peripheral
|1 Primary
|===

These bots are ex-recon, ex-aids, or malfunctioning mechanize infantry.
It is possible that an expendable combot is a walking bomb.
Regardless of what it used to be the expendable combot has gone free lance. 
Expendable combots can drive military vehicles in combat situations.
Regardless of the expendable's INT score it has a good memory for combat details. 

== Defensive Combot

// NO IMAGE? SHAME!!!

//  Defensive  Data 
.*Defensive Combot Fabrication Info (C-D)*
[width="75%",cols="2*<"]
|===
2+<|Protect the perimeter. 

2+<|*Attributes*

|Ranges
|CON 2, 4; DEX 4; INT 1, 3; PSTR 4

|Minimums
|CON 20 or greater

|Hit Points
|21-30 (1d10+20) per point of CON

|Adaptability
|1%

|Size
|Large

|Value:
|10000000

2+<|*Systems*

|Offensive
|1 roll Table 1

|Defensive
|1 per 4 points of CON

|Peripheral
|1 Primary
|===

Defensive combots defend positions from enemy attack.
They are naturally protective of geographical spaces and fellow personas.

Not surprisingly defensive combots have many Defensive Systems.
A defensive combot with a 20 CON score would get 5 rolls on the Robot Defences Table.
That is a lot of defences. 
Each defensive combot has several native defences unique to this combot type.

=== Demoralize
The ability to ceaselessly utter vile comments and insults about the enemy.
The effect of this is unclear and mostly adds a colourful element to combat.
For the psychological warfare to be effective is a normal CHA vs MSTR challenge.

=== Fortify
Analyze attacking enemy formations to optimize defensive strategies.
If there is no organized attack formation this will be identified also.
To properly analyze the attack is a normal INT vs INT challenge.

=== Intruder Detection
Defensive bots can also detect intruders up to a range of 10 hexes times AWE score.

=== Anti-Anti-Detection Detector
Another ability included within the given range is the bots Anti-anti-detection system.
The Anti-anti-detection system will automatically pick up technological aids that are concealing or scrambling the presence of intruders.
This is a hard AWE vs DEX challenge.

=== Weapon Identification
The bot also has a weapons identification skill which can only be used on a weapon which has inflicted damage on the combot.


== Light Offensive Combot

:art: combot_light_offensive.PNG
:width: 250px
:snark: Its the steel thing
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a floating pop machine loaded with guns and rocket launchers.

include::ROOT:partial$articulate.adoc[]

// light offensive combot
.*Light Offensive Combot Fabrication Info (C-L)*
[width="75%",cols="2*<"]
|===
2+<|Delivering freedom from a can. 

2+<|*Attributes*

|Ranges
s|CON 2 or 4; DEX 4; INT 1 or 3; PSTR 4

|Minimums
|CON 19; DEX 15

|Hit Points
|16-25 (15+1d10) per point of CON

|Adaptability
|-50%

|Size
|Large

|Value:
|100000000

2+<|*Systems*

|Offensive
|2 rolls on Table 2 +
1 roll on Table 3

|Defensive
|2 rolls

|Peripheral
|None
|===

Light offensive combots are attack drones. 
They are loaded with many small arms weapons. 
They meant to be deployed in cities or other close quarter environments.
Light combots are tactical machines and are not considered expendable. 
If it fits the story a light offensive combot can control expendable combots.
Referee persona light combots will be found with 0-3 (1d4-1) expendables under their command.

== Heavy Offensive Combot

:art: combot_heavy_offensive.png
:width: 250px
:snark: Offensive and heavy.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a tank sized robot with many big guns.

include::ROOT:partial$articulate.adoc[]

.*Heavy Offensive Combot Fabrication Info (C-H)*
[width="75%",cols="2*<"]
|===
2+<|Destroyer of all things in it's path, even campaigns. 

2+<|*Attributes*

|Ranges
|CON 2 or 4; DEX 4; INT 1 or 3; PSTR 4

|Minimums
|CON 23; PSTR 27

|Hit Points
|16-25 (15+1d10) per point of CON

|Adaptability
|-100%

|Size
|Gigantic

|Value:
|1000000042

2+<|*Systems*

|Offensive
|1 roll on Table 2 +
1 roll on Table 3 +
1 roll on Table 4

|Defensive
|3 rolls

|Peripheral
|None
|===

The heavy offensive combot is the beast of the robot world.
This combot is intended to soften, destroy and punch through enemy targets.
The heavy offensive combot is literally heavy.
It's robot size is gigantic.
The heavy also refers to the weapons that the combot is armed with.
The small arms tend to be higher powered.
The heavy combot will sport some heavy weapons like a bombs, artillery or missile.

Heavy offensive combots to not shun combat and are hardened for it. 
The armour rating for a heavy combot starts at 775.

=== Heavy Weapons
The heavy weapon is determined randomly.
If a referee's campaign balance is threatened by a Nuk-O-Matic cannon don't use it.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

A heavy offensive combot could have the capacity for artillery but be out of ammo.
Such a powerful item should improve a campaign, not destroy it.
That being said....

//a new table for 6.0
.*Heavy Combot Heavy Weapon*
[width="75%",cols="2*<"]
|===
2+<|Add PSTR to the 1d100 roll.

s|Die Roll (1d100)
s|Heavy Weapon

|01-27
|Popcorn Machine

|28-60
|Bomb only

|61-90
|Bomb/Missile

|91-110
|1 Artillery

|111-120
|1 Artillery +
1 Bomb only

|121-128
|1 Artillery +
1 Missile/Bomb

|>129
|Naval Artillery

s|Die Roll (1d100)
s|Heavy Weapon
|===
