= Policing

Policing bots are crime fighting machines.
These bots respect the lives and livelihoods (if legal) of all life forms.
They are especially protective of their fabricator type.
Policing bots can be stationed anywhere.
They are not limited to underserviced or violent areas.

// new table for 6.0
//  Robot Attribute Requirements 
.*Policing Robot Attribute Requirements*
[width="75%",cols="2*<"]
|===
2+<| Attribute requirement for industrial robot type.

s|Policing Type
s|Attributes

|Civil
|Nil.

|Riot
|CON 15

|Detective
|INT 15

s|Policing Type
s|Attributes
|===

== Civil Policing Robot

//  Civil Policing Robot Fabrication Data 
.*Civil Policing Robot Fabrication Info (P-C)*
[width="75%",cols="2*<"]
|===
2+<|Policing civilian environments.

2+<|*Attributes*

|Ranges
|CON 3; DEX 4; INT 3; PSTR 3

|Minimums
|Nil.

|Hit Points
|3-12 (3d4) per point of CON

|Adaptability
|-25%

|Size
|Medium or Small

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|100% roll on Table 1

|Defensive
|100% for 1 roll

|Peripheral
|10% for 1 roll on Primary
|===

Civilian policing bots are constables on patrol in a drum.
Civils can walk the beat, chase criminals, guard banks, issue tickets, etc.
By sheer chance this bot's ID is P-C. 
This robot is the main interface between the 'people' and law enforcement.
Civilian policing bots have some special skills.

=== Commanding Voice
When necessary the civil bot can unleash booming amplified voice commands.
Classic commands like FREEZE! or DROP IT! can be used.
The command can be effective or at least distracting to organic ears.
If a target fails a MSTR challenge vs the bot's doubled CHA they will pause, or obey.

=== Non-Lethal Weapon
A non-lethal weapon is one that can disable or affect a target without harming it.
A stun weapon, or a sleep beam, or a nausea attack would be considered non-lethal.
Less lethal weapons do not count.
The player has three chances to roll a non-lethal weapon for her robot. 
If there is no non-lethal weapon after three rolls the persona has no weapon.

=== Disarm
A civil bot can disarm a target with a successful attack roll.

=== Grapple
When it is time to 'collar' a suspect or subdue a target the civil bot can grapple.
Successfully scoring a hit will completely immobilize an organic target.
A civil bot is completely invested during a grapple and cannot do anything else.
To break from this grapple requires a successful bizarre PSTR roll.
Civil bots will unglamorously drag their grappled collars back to the nearest brig.

== Riobot Policing Robot

:art: riobot.png
:width: 250px
:snark: Riobot protecting and serving
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

//  Riobot Fabrication Data 
.*Riobot Fabrication Info (P-R)*
[width="75%",cols="2*<"]
|===
2+<|Keeping the peace when things are in pieces.

2+<|*Attributes*

|Ranges
|CON 3; DEX 4; INT 3; PSTR 3

|Minimums
|CON 15

|Hit Points
|3-12 (3d4) per point of CON

|Adaptability
|-42%

|Size
|Gigantic

|Value:
|1000000 times 1d6

2+<|*Systems*

|Offensive
|None

|Defensive
|100% for 1 roll

|Peripheral
|10% for 1 roll on Primary
|===

Riot bots are large crowd control operatives.
They often turn up at labour disputes, surprise sales, food line-ups, rock concerts, etc.
There goal is to contain and restrain unruly hordes of anthros.
They function like an automated paddy wagon with added crowd suppression.

=== Grapple and Detain
A riobot can grapple and detain rioters.
Once a rioter is grappled they can be detained either in or on the riobot.

The riobot can grapple one rioter per unit. 
The riobot can carry out all other operations while grappling a rioter. 
A successful attack roll will immobilize the rioter and prepare them for detention.
To break from this grapple requires a successful hard PSTR roll.
Once detained the target is immobilized and attached to the riobot. 
To break free from detention requires a bizarre PSTR challenge.
A riobot can detain one target per point of PSTR.
So a Riobot with a 20 PSTR can detain 20 targets.

While detained the rioters are subject to any area of effect riobot peripherals employed.

=== Riobot Peripherals
These peripherals are specific attachments designed for crowd control.
They are not malfunctioning peripherals being used as weapons.
Riobot peripherals are baked in non-lethal immobilization attacks. 
Riot Policing Bot Peripheral for every three points of INT.
So a riobot with a 12 INT score would get 4 rolls on the peripheral table.
Multiple rolls of the same peripheral are intentional riobot redundancy.
The riobot can use every peripheral every unit.

include::ROOT:partial$CH05_Table_Riot_Policing_Robot_Peripherals.adoc[]

=== Details about the Details
Each riobot peripheral has 4 parameters.
The simplest is the name of the attack. 
The details consists of attack type, range, intensity and effect.

==== Attack Type
The riobot attack peripheral is either target or area of effect. 
A targeted (*Target*)attack is aimed at one target and has no effect on neighbouring targets.

An area of effect (*a/e*) affects every target within the area of effect.
Every target in the area of effect must save vs the attack or suffer the effect.

==== Range
For targeted attacks the range is the number of hexes away a target can be from the bot.
If the range is listed as PSTR the attack can reach a target PSTR hexes away.
So a riobot with a 10 PSTR could attack a target 10 hexes away.

Area of effect range is measured out from the riobot in hexes.
All targets in that area must save vs the attack or suffer the effects. 
If the range is listed as half CON every target within that range must save.
So a riobot with 10 CON would affect every target within 5 hexes of itself.

==== Success
Success is what the player must roll to have the effect take hold. 
If a attack roll is required the player must make a successful attack roll.
To hit rolls are usually reserved for targeted attacks.
A successful attack roll vs the target's AR indicates the effect takes hold.

Intensity level indicates the save the target must make to avoid the effect.
If success is CON intensity the targets must save vs the riobot's CON or be effected.

==== Effect
The effect of the attack is a simple self explanatory description.
The effect is non-lethally immobilize targets.
Once immobilized policing robots can automatically grapple targets. 


== Detective Policing Robot

//  Detective Policing Robot Fabrication Data 
.*Detective Policing Robot Fabrication Info (P-D)*
[width="75%",cols="2*<"]
|===
2+<|Detective, chief, manager, sleuth, criminologist in one.

2+<|*Attributes*

|Ranges
|CON 3; DEX 4; INT 3; PSTR 3

|Minimums
|INT 15

|Hit Points
|2-4 (1+d3) per point of CON

|Adaptability
|10%

|Size
|Medium

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|100% roll on Table 1

|Defensive
|100% for 1 roll

|Peripheral
|100% for 1 roll on Primary
|===

A detective policing bot is a criminologist in a drum.
A detective can operate as a chief, manager, auditor, or technologist.
The detective has no grapple or detain methods. 
A detective depends on civils to make arrests and do the dirty work.
Detective policing robots are dedicated to the apprehension of criminals.
If an expedition engages in criminal activities the detective may need to make CF checks.
