= Robot Power Source

All robots operate on electrical power.
The electrical power runs all their systems and gives them life.
Running out of energy is not a problem for robot personas.
However, in a resource austere campaign setting, finding power may be the key to robot survival. 
If a robot runs out of power, she shuts down until the energy flows again. 
Getting powered down is an extremely vulnerable, but not lethal, state.

The robot power sources is a cross between a cell and an engine.
Each cell works on an ingenious technomagical system that is conveniently beyond explanation.
Robot power sources can go by many names: batteries, cells, supercells, etc.

If the referee and players feel that a robot running out of power is a fun option, consider the following.

.*Robot Power Guidelines*
* one month of use per point of constitution score
* player personas start at a full charge
* one month low battery warning
* battery use does not affect battery duration
* all batteries can be restored or regenerated

include::ROOT:partial$CH05_Table_Robotic_Power_Cell_Type.adoc[]

Gas::
This cell contains chemicals in a gaseous state reacting to create energy.
A gas cell will cease to function if exposed to extreme cold (like a cryogenic attack).

Liquid::
This cell contains chemicals in a liquid state reacting to create energy.
A liquid cell will cease to function if exposed to a vacuum.

Solid::
This cell contains chemicals in a solid-state reacting to create energy.
A solid cell will cease to function when exposed to extreme heat (like fusion, napalm or sustained fire).

Plasmoid::
This cell contains chemicals in a plasmoid state, reacting to create energy.
The plasmoid has a failsafe that prevents its weaponization.
A plasmoid cell will cease to function when exposed to zero gravity.

Dynamo::
Internal dynamos manufacture the useable energies of this cell.
A dynamo cell will cease to function when exposed to high gravity.

Solar::
A solar cell converts light into energy and stores it for later use.
A solar cell can recharge itself after one full hour in bright light.
A solar cell will cease to function if exposed to a violent light attack. 

Magnetic::
A magnetic cell converts magnetic waves into energy and stores it for later use.
A magnetic cell can recharge itself after one full hour in a natural magnetic field.
A magnetic cell needs a natural magnetic field created by a planet or moon for recharging.
These cells cease to function if exposed to magnetic attacks.

Broadcast::
Broadcast cells are power receivers that convert transmissions from a power source into energy.
The receivers will cease to function if they are subject to electronic jamming or leave the broadcast range.
If the broadcast source stops transmitting, broadcast cells stop working.
The range of broadcast power is up to the referee.

Psionic::
Psionic cells tap into the Kirlian energy of consciousness to create energy.
The psionic cells drain Mind to recharge themselves.
The psionic cell will make a psionic attack on the nearest persona.
If the target wins her psionic roll against a 3-18 (3d6) attack, the battery moves onto the next nearest consciousness.
The player generates a new attack intensity each time the psionic cell requires recharging.
The psionic battery will keep doing this until a persona fails her psionic roll.
That persona loses one point of Mind, and the psionic battery has recharged.
If all the nearby personas win their psionic rolls, the battery will stay drained until a new mind comes in range.
The range of the psionic attack is one hex per intensity.

== Ref's Own Table
The referee can insert campaign-related power sources as she sees fit.
