= Exploration

Exploration robots are fabricated to map, search, explore, catalogue, and record everything.
Exploration robots often go by the nick name exbots or exbots. 
There are two types of exbots: planetary and extraplanetary.
The differences are explained below.

== Planetary Exploration Robot 

:art: explorations_planetary.png
:width: 250px
:snark: Looking for minerals in all the wrong places
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of flying robot box with skis.

include::ROOT:partial$articulate.adoc[]

//  Explorations Planet Data 
.*Planetary Exploration Robot Fabrication Info (E-P)*
[width="75%",cols="2*<"]
|===
2+<|Planet side robot fabricated to explore, learn and report. 

2+<|*Attributes*

|Ranges
|CON 4; DEX 2; INT 1 or 4; PSTR 3

|Minimums
|Nil

|Hit Points
|11-16 (1d6+10) per point of CON

|Adaptability
|30%

|Size
|Small

|Value:
|100000 times 1d12

2+<|*Systems*

|Offensive
|25% roll on Table 1

|Defensive
|1 Roll

|Peripheral
|1 Primary
|===

A planetary exploration robots work within the atmosphere of the planet it was fabricated for.
They are used to find minerals, observe terrain, record weather and take photographs.

.Planetary Exobot Skills
* Atmospheric Analysis
* Long Range Communication
* Mineral Identification
* Photography (includes infra-red, x-ray, etc.)
* Poison / Radiation Detection
* Sample Collection

Planetary explorers are mostly interested in the planet, and not it's inhabitants.
This exobot is more likely to avoid encounters with indigenous species. 
Most of the data they collect will be interpreted elsewhere.
The data could be sent to a command center, orbiting space vehicle or an extraplanetary exobot.

== Extra Planetary Exploration Robot

:art: extra_planetary_bot.png
:width: 250px
:snark: Exploiting, exploring, a new planet.
:artist: Louis Glanzman, modded HM
:date: 1953, 2017
:license: CC BY-SA 4.0
:description: Drawing of flat robot exploring alien planet.

include::ROOT:partial$articulate.adoc[]

//  Explorations Planet Data 
.*Extra Planetary Exploration Robot Fabrication Info (E-X)*
[width="75%",cols="2*<"]
|===
2+<|Planet side robot fabricated to explore, learn and report. 

2+<|*Attributes*

|Ranges
|CON 4; DEX 2; INT 1 or 4; PSTR 3

|Minimums
|INT 24

|Hit Points
|11-16 (1d6+10) per point of CON

|Adaptability
|-10%

|Size
|Medium

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|1 roll on Table 1

|Defensive
|2 rolls

|Peripheral
|1 Primary
|===

Extra-planetary exploration robots can do everything their planetary colleagues can do.
They are fabricated to explore new and unknown worlds.
This gives them a few extra robotic skills.

.Additional Extraplanetary Exobot Skills
* Comprehend languages
* Identify intelligence
* Map terrain
* Exatmo hardened

This robot can interpret the information collected by planetary exobots.
The extraplanetary can embrace and contact indigenous life forms. 

Exatmo hardening allows this robot to function in air, liquid or vacuum. 




