= Robot Experience
As a bot gains more experience, it begins to solidify and reinforce its individuality and personality.
The robot becomes more insane as it gathers data moderated by its own free will.
The more individualistic and independent it becomes, the more insane it is.
Remember that insanity in a robot does not mean lunacy, just robotic free will.
Robots will gain experience by engaging in combat, taking damage and taking more damage.

5% of combat EXP's can be converted into data that will reinforce the robot's independent thought.
Nothing will increase the robot's free will more than damage.
Robots will earn 20 EXP's per HPS of damage they take.
Increasing a robot's level will increase its control factor and hence its free will.

Bots cannot acquire experience points for performing functions for which they were designed.
A domestic bot will not get experience for cleaning a room but will be rewarded if lucky enough to expose an informative fresco in the process of doing so.
A bot with painting skill would not be rewarded for painting a house but would gain experience points for using that same ability to spray paint into the eyes of the opponent.
So, novel use of a built-in skill will be rewarded with experience points.

// table insert 76
