= Robot Hit Points

Robots are inorganic fabricated entities.
They do not have a physiology per se.
Consequently, physical damage affects robots different from anthros and aliens. 
While a hit point in damage is still a hit point in damage, its effect on the robot is different.
The main difference between robotic and organic (anthros and aliens) is that robots do not 'die' at zero hit points.
A robot at zero hit points (0 HPS) indicates a broken part rather than a dead robot.
A robot dies when any of its attribute scores falls to zero.
Zero hit points does not destroy a robot, but a zero constitution does.

== Calculating Robotic Hit Points
Each robot type has hit points listed on its fabrication info sheet. 
The player calculates her robot persona's hit points max when the robot type is determined. 
The player multiplies the robot's constitution score by the hit points listed on the fabrication info sheet.
An explorations robot (E) with a 20 CON could have between 220 and 320 hit points max.
A datalyzer (D) with a 4 CON could have between 4 and 12 hit points max.
The robot world is entirely unfair.

:art: battle_hardened.png
:width: 350px
:snark: Closer to consciousness every hit.
:artist: JEShields
:date: 2014
:license: Copyright JEShields Stock Art. jeshields.com
:description: Torso and arms of damaged robot with floating brain in head.

include::ROOT:partial$articulate.adoc[]

== Damaging Robots
When a robot is damaged, there are no organic repair systems to fix things.
Anthros and aliens have organic systems that repair themselves with time.
Robot persona damage is a one-way street.
Technically a robot could get repairs to counter the structural damage.
However, the robot's damage gives it consciousness and free will. 
Repairing a robot may remove that free will.
Robots do not heal themselves of their damage, but that damage helps them grow more independent.
Robotic free will depends on malfunctions.
A properly repaired robot may no longer have free will.

=== Attack Types
Damage to a robot is the same as damage to any other persona.
A punch does the same damage to a robot as an organic target.
Electrical and disintegration attacks are especially damaging to robot personas.
An electrical or disintegration attack inflicts double damage to a robot. 

Robots keep taking more and more damage.
Eventually, the damage will reduce the robot's hit point total to zero. 

== Zero HPS
For organic personas, zero hit points mean unconsciousness or death.
For a robot, zero hit points indicate some system is damaged.
When a robot's HPS total drops below zero, several things happen.

.Zero HPS Checklist
. <<_hps_max_damage,HPS Max Damage>>
. <<_system_damage,System Damage>>
. <<_attribute_damage,Attribute Damage>>

This is sometimes referred to as robot decay, or the decay trifecta.

== HPS Max Damage
Each time the persona's hit points total drops to zero, the robot takes 10% off her hitpoints max.
A robot with 110 HPS Max drops by 10% to a new HPS Max of 99.
The drop in HPS Max rounds down and does not benefit the player.
The robot is dead when her HPS Max reaches zero.

=== HPS Max Decrease
.New HPS Max = old HPS Max times 0.9
****
HPS Max of 110 drops to 99. HPS Total resets to new HPS Max. 
Always round down.
****

=== Rounding Down
This drop in HPS Max continues until the HPS Max is less than one.
The robot drops her HPS Max by 10% every time her HPS Total drops to zero.
Her HPS Max would decrease like so: 110, 99, 89, 80, 72, 64, 57 etc.
An HPS Max of zero indicates a destroyed robot. 
The total damage (using Python models) this robot could sustain is 970 HPS.
Although it is more likely an attribute will drop to zero and destroy the robot first.

=== Carry Over
What happens if a robot takes more than her HPS Max in one massive attack?
In this case, the referee must carry over the remaining damage and subtract it from the newly minted hit point total.

Consider a fresh new robot with 110 HPS Max.
She takes 115 HPS of damage all at once.
The first 110 hit points of damage reduce her hit point total to zero.
This HPS Total would drop to zero, triggering the robot decay trifecta.
The referee carries over the remaining five hit points in damage and subtracts them from the new HPS Total.

For example, her new HPS MAX is 99, and the remaining 5 HPS of damage is carried over.
Her new HPS Max would be 99, and her HPS Total would be 94.
A large bolus of damage can run a robot through the decay trifecta several times.

== System Damage 
When the robot's hit points total drops to zero, the player checks to see which robot system was most damaged.
System damage is similar to a hit location, but the part that malfunctions may be far away from the point of injury. 
The player rolls to determine the system damaged and rolls to determine its severity.

include::ROOT:partial$CH05_Table_Robotic_System_Malfunction.adoc[]

Damaging the locomotion system does not slow down the robot.
Damaging the locomotion system does decrease the robot's dexterity and physical strength. 
The attributes affected by locomotion may slow the robot down, but more importantly, the reduced attributes bring the robot closer to death.

== Attribute Damage
Every attribute listed under the robot system malfunction gets an individual roll on the malfunction severity table.
Damaging the robot's articulations indicates two rolls on the severity table, once for awareness and dexterity.
In the case of control unit damage, every attribute is at risk.

include::ROOT:partial$CH05_Table_Robotic_Malfunction_Severity.adoc[]

If the player gets lucky, there is no decrease in the attribute. 
There is a 1 in 6 chance of not having an attribute decrease.

=== Attributes Decrease
The process is simple. 
If an attribute is severely damaged, the player reduces the attribute score by one point.
If an attribute is critically damaged, the player reduces the attribute score by two points.
Ouch.
There is a chance to get lucky and suffer no attribute decrease.

If any attribute drops to zero, the robot is dead. 

A critical malfunction to the robot brain would reduce the robot's intelligence score by 2 points.
So a robot with an 11 INT now has a 9 INT.
The referee and players may choose to recalculate abilities, range effects, etc., due to the lower intelligence score.
It is equally acceptable to ignore doing such arithmetic.
There is enough arithmetic in robot damage already.

=== Attribute Primes
Attribute damage does not affect the robot's attribute primes.
The prime attribute scores are between 1 and 4 and help determine the robot type and other calculations.
A robot with an intelligence prime of 4 will always have an intelligence prime of 4.

=== Level Bonus
If the referee and players deem it appropriate, a robot persona can earn an experience level for critically damaging an attribute.
This critical damage leading to robotic insight can only happen once per round of robot decay.
So a robot that critically damages her awareness and intelligence can only earn 1 EXPS level. 

== Robot Demolition Tables
Robot demolition tables are essential for referee personas. 
The demolition table has all the damage effects for the robot persona prepared. 
Player personas usually will visit the system damage tables each time they zero their HPS Total.
Someday, computers will automatically calculate the demolition table.

include::ROOT:partial$CH05_Table_Example_Robotic_Decay.adoc[]

== Healing and Repairs
Robots are not self-repairing like organic personas.
For a robot to heal, it would have to have repairs.
Repair for a robot returns it to its original fabrication state, decreasing its control factor.
A fully repaired robot is a referee persona robot that follows orders and protocols. 
In general, player persona robots will avoid repair and revel in the improved control factor.

A robot can have peripherals that allow for self-repair.
Mechanics highly skilled in robots may be able to repair robots without wrecking their free will.

:art: robot_damage_desat.png
:width: 250px
:snark: Inorganic boo boo
:artist: Studiostoks
:date: 2015
:license: Copyright Studiostoks
:description: Drawing of robot hand with bandage on thumb.

include::ROOT:partial$articulate.adoc[]

