= Robot Shape
Robots appear to be robots and have a basic inorganic shape. 
Unless the robot has a specific appearance, its gross shape is determined here.

The player can choose what she likes: fire hydrant, filing cabinet, kitchen appliance, etc.
The players cannot disguise her persona as a fire hydrant or a filing cabinet unless she has a robotic disguise skill.

If some random assistance is needed, consult the below tables.
The tables only offer a shape. 
The colour, design, sound, decals, smell, or detailing is still up to the player.
The referee may have some commercial patching, depending on the campaign.

NOTE: The robot shape has no bearing on attacks, peripherals or defences.

To determine the Hite and Wate of the robot jump to xref:i-roll_playing_rules:CH05_Robots_Z_Size.adoc[Robot Size,window=_blank]

== Basic Shape
The volume of the robot will fit into this shape.
Feel free to contort the shape.

include::ROOT:partial$CH05_Table_Robotic_Basic_Shape.adoc[]

== Contortion of Basic Shape
This table manipulates the basic shape of the robot.
This step is optional and is present to help reflect the randomness that is commercial design.

include::ROOT:partial$CH05_Table_Robotic_Basic_Shape_Adjustment.adoc[]
