= Rescue

Rescue cover all the bases on non-policing emergency response.
There are two types of rescue robots. 
Retrieval rescue robots rescue people and property from dangerous environments.
Containment rescue bots suppress and contain those dangerous environments.
Rescue robots have many unique skills. 
Rescue bots value organic life and property weaponizing their skills would be a challenge. 
If the player wishes to use them outside of a rescue a Control Factor check is warranted.

== Retrieval

//  Rescue Retrieval Fabrication Data 
.*Retrieval Rescue Robot Fabrication Info (R-R)*
[width="75%",cols="2*<"]
|===
2+<|Extricate life forms and equipment from danger.

2+<|*Attributes*

|Ranges
|CON 4; DEX 2 or 4; INT 2 or 3; PSTR 1 or 3

|Minimums
|DEX 22

|Hit Points
|7-15 (2d10+5) per point of CON

|Adaptability
|10%

|Size
|Large

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|100% roll on Table 1 +
25% second roll on Table 1

|Defensive
|100% for 3 rolls

|Peripheral
|100% for 1 roll on Primary
|===

Retrieval bots are fabricated to remove people or bodies from dangerous situations.
This includes complicated extrications from wreckage or rubble.  
The dangerous situations do not include combat. 
The dangerous enviros are fires, landslides, radioactive areas, outer-space, etc.
They are capable of performing their duties underwater, in zero-gravity or in a vacuum.

=== Alerting and Cordoning
Rescue bots have lights, sirens, and loudspeakers to warn and protect.
If the alerts are used outside of an emergency the referee may require a CF check.

The retrieval robot can also cordon off a dangerous area. 
This robot has 50 hexes of glowing retractable fencing for cordoning off danger areas.

=== Saving Targets
Typically a persona or object wants to be rescued. 
Success is just a matter of time.
The more complicated the rescue the longer it takes.
How complicated a rescue is decided by the referee and players. 
The longer the retrieval takes the more injured the victims become.
A retrieval could be automatic, require a success roll, or become an entire run. 

Typically targets want to be rescued.
If a persona is being rescued against their will the bot must grapple the target.
A successful to hit roll indicates a successful grapple and rescue.
Once grappled the victim can be stashed  into a nice cool stasis chamber. 
Grappling and stashing targets in a non-retrieval environment will require a CF check.

=== Stasis Chambers
Retrieval robots can safely store organic creatures in stasis chambers.
The robot is fashioned with one stasis chamber for every two points of PSTR.
So a retrieval robot with a 20 PSTR would have 10 stasis chambers. 
The size of the stasis chamber is based on the fabricator type of the robot. 
Inorganic targets being rescued are safely stored in a stasis chamber.
Retrieved personas and toys stored in the stasis chamber will not come to harm.
If the robot is destroyed the stasis chambers fail and eject their contents.

For all intents and purposes personas in stasis chambers are unable to escape.
If personas detained against their will need to wake up and force their way out to escape.
Waking up in a stasis chamber is the hard part. 
This requires a tough MSTR check.
To break out requires a hard PSTR check. 


// how about a link to stasis chambers in the toy section

== Containment

//  containment Rescue Fabrication Data 
.*Containment Rescue Robot Fabrication Info (R-C)*
[width="75%",cols="2*<"]
|===
2+<|Contain and remove hazardous or inconvenient substances.

2+<|*Attributes*

|Ranges
|CON 4; DEX 2 or 4; INT 2 or 3; PSTR 1 or 3

|Minimums
|Nil

|Hit Points
|7-15 (2d10+5) per point of CON

|Adaptability
|10%

|Size
|Gigantic

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|25% roll on Table 1 

|Defensive
|100% for 3 rolls

|Peripheral
|100% for 1 roll on Primary
|===

Containment Rescue robots are like janitor bots for deadly environments.
Deadly environments include fire, chemicals, radiation, bacteriologic, nanologic, etc.
These threats are inorganic ones, but may certain infestations may meet parameters.
Appropriate toxic dangers are determined by the referee and players.
They are designed to contain and remove toxic, or inconvenient elements.

Containment bots have lights, sirens, and loudspeakers to warn and protect.
If the alerts are used outside of an emergency the referee may require a CF check.

=== Detection
Containment bots can sense toxic danger at a range of ten hexes per point of AWE.
Toxic danger includes: fire, radiation, chemicals, etc.
The toxic danger must be large enough to represent harm to a community.
For example detection does not alarm if a poisonous alien were nearby.

=== Cordoning
The containment rescue robot can cordon off a dangerous area. 
This robot has 250 hexes of glowing retractable fencing for cordoning off toxic danger.

=== Fire Suppression
The containment bot has a universal flame retardant which will extinguish normal fires.
The bot can extinguish 5 hexes of fire for every point of CON.
For example, a bot with CON 22 could put out 110 flaming hexes.
The flame retardant is non-toxic, is breathable, and has minimal residue.
The containment robot can recharge its fire suppression if basic materials are available.
Flame retardant is not weaponizable, but may work as a distraction. 

=== Toxic Covering
A containment bot can cover the toxic area with a bespoke sealing plastic.
The spray on containment will be altered to reflect the toxic danger.
The appearance and composition of the covering will be different for rads vs poison.
The bot will normally have enough spray-on containment cover for 100 hexes of toxic danger.
Merely covering a toxic danger is a last resort or a temporary measure. 
Containment bots prefer to remove and store the offending agent.
If the robot wishes to weaponize the covering it will function as a web gune

=== Storage
This robot uses an array of shovels, rakes, suckers, filters and scoops could clean up.
The containment bot is capable of sifting through debris and storing only the toxic materials.
Once collected, the toxins will be stored in a hold within the containment bot.
This hold has a capacity of 20 times the personas WA.
How much a toxic danger weighs is up to the referee and players.

The containment bots do not neutralize toxins. 
That would be too easy.
Once the containment bot fills it's hold it will revert to covering toxic dangers.
Poisonous junk cannot be completely forgotten once stashed away.
A full containment bot may begin to glow, radiate or attract strange animals.
