= Veterinarian

Veterinarian robots are vets in a drum.
They are also called medibots or vets.
This robot type values life and well being beyond all.
It is very difficult for a player to get their vet bot persona to cause harm.
This dedication to life is not limited to their fabricator type but all organic life.

There are two kinds of vet bots: diagnostic and interventional.
Diagnostic vet robots are dedicated to figuring out what ails the organic creature.
Interventional vet robots are dedicated to repairing, modifying or enhancing organic flesh.

There is often a tendency for interventional robots to be used for nefarious purposes.
Harming an organic would go against all their programming and require intense CF checks. 

== Diagnostic Vet Robot

:art: medibot_diagnostic.png
:width: 250px
:snark: Doc in the box.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of many wheeled box robot with camera arms. 

include::ROOT:partial$articulate.adoc[]

//  Diagnostic Veterinarian Robot Fabrication Data 
.*Diagnostic Veterinarian Robot Fabrication Info (V-D)*
[width="75%",cols="2*<"]
|===
2+<|Thinking robot for diagnosing organic malfunctions.  

2+<|*Attributes*

|Primes
|CON 1, 2; DEX 4; INT 3, 4; PSTR 1


|Minimums
|Nil

|Hit Points
|2 per point of CON

|Adaptability
|15%

|Size
|Medium

|Value:
|2500000

2+<|*Systems*

|Offensive
|Nil

|Defensive
|10% for 1 roll (non-lethal)

|Peripheral
|100% for 1 roll on Primary
|===

The forte of the diagnostic robot is diagnosis.
Diagnosis is attributing a patient's condition to an exact pathology.
The diagnostic bot can accurately diagnose all but the most peculiar conditions.
This robot is more interested in diagnosing than anything else. 
The diagnostic bot will only do the tests and scans necessary to make a diagnosis.
This robot does not like to intervene in the patient at all.
Diagnostic bots do not perform surgery or do therapies. 
Many diagnostic bots feel that doing 'procedures' is beneath their station.

The diagnostic robot performs like a veterinarian in all areas except surgery.
The diagnostic robot gets more bonuses and skills than a typical vet.
The player adds double her INT score to any Performance Table rolls.
The diagnostic bot gets many more skills than the typical veterinarian.
Starting out the player gets one roll on the veterinarian skill table per point of INT. 
The diagnostic vet bot can still get interventional vet skills. 
They just will not be used for interventions.

== Interventional Vet Robot

:art: medibot_interventional.png
:width: 250px
:snark: Heal with steel.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of intravenous pole looking robot doing a procedure.

include::ROOT:partial$articulate.adoc[]

//  Interventional Veterinarian Robot Fabrication Data 
.*Interventional Veterinarian Robot Fabrication Info (V-I)*
[width="75%",cols="2*<"]
|===
2+<|Short on diagnostics. Long on mad skills.  

2+<|*Attributes*

|Primes
|CON 1, 2; DEX 4; INT 3, 4; PSTR 1


|Minimums
|DEX 23; INT 21

|Hit Points
|2 per point of CON

|Adaptability
|15%

|Size
|Medium

|Value:
|5000000

2+<|*Systems*

|Offensive
|Nil

|Defensive
|10% for 1 roll (non-lethal)

|Peripheral
|100% for 1 roll on Primary
|===

Interventional medibots are capable of performing all manner of interventions.
They will do best when working under the direction of a diagnostics bot or veterinarian.
Interventional robots perform surgeries. 
They especially perform sciency fiction surgeries. 
Interventionals can cut, sew, suck, remove, attach, remodel or improve organic flesh.

Interventional bots have local and general anesthetic skills.
None of the procedures carried out will cause pain. 
The patient will be kept anesthetized for as long as necessary or desired.

The interventional robot performs like a veterinarian in all areas except diagnosis.
The interventional robot gets more bonuses and skills than a typical vet.
The player adds double her DEX score to any Performance Table rolls.
The interventional bot gets many more skills than the typical veterinarian.
Starting out the player gets one roll on the veterinarian skill table per point of INT. 
The interventional vet bot can still get diagnostic vet skills. 
They just will not be used for diagnosis.


