= Robot Sensors

All robots will have audio and video sensors allowing the robot to hear and see.
The robotic audio and visual sensors work the same as organic personas' eyes and ears.
To expect a player to manage without these necessary sensors is an excessive burden.
Robots do not have sensors for touch, smell or taste.
As with other personas, the robot's Awareness attribute determines the sensors' effectiveness.
Better Awareness, better sensors.
Robotic sensors are only damaged when the robot's Awareness is damaged. 
Robots will receive one additional sensor for every 4 points of AWE.

include::ROOT:partial$CH05_Table_Robotic_Sensors.adoc[]

== Video
This robot has an extra set of video sensors.
These essentially act as an extra set of eyes for the robot.
These can be built into the robot's hull or conveniently attached to the end of an articulation.

== Optical
Optical sensors are non-video sensors that use wavelengths outside of the organic ranges.
Optical vision systems include laser sight, ultraviolet or infrared detectors.
The player can choose to include these optical sensors in the robot's regular video sensors or a separate component.
Regardless of the optical sensor's type, they all offer equal night day vision.

== Vibrations
Vibration sensors convert molecular vibrations into comprehensible robotic vision.
This sensory feature will cut through any obscuring clouds of gas or particulate debris.
The maximum range of a vibration sensor is five hexes per Awareness score.
Vibration sensors are directional, and the robot must look towards whatever she wants to observe.

== Sonar
Sonar allows the robot to perceive a spherical area where she is the center.
Sonar will work equally well through air, water or smoke, but the medium must be relatively homogenous.
Sonar does not function beyond a transition between media.
For example, sonar will not work across the transition from air to water.
The sonar range is ten hexes her point of AWE.
Sonar does not function in a vacuum.

== Radar
Radar gives 360° vision around the robot.
The 360° vision is a disk and not a spherical detection area.
Radar allows the robot to detect objects and determine their Wate. 
Radar can penetrate solid objects.
The radar range is ten hexes her point of AWE.

== Refs Own Table
The referee can insert campaign related sensors she sees fit.
Examples of unique sensors are organic eyes, tactile tentacles, olfactory unit, emotion sensors, or a sense of style.
