= Alien EXPS

What do aliens earn EXPS for?
Aliens can earn EXPS for role-playing just like any other persona and they also have specific alien ways of earning EXPS.
If an alien is a civilized tool user and has a persona class, then it will increase in levels according to that class`' experience point table.
Aliens earn full experience for combat when fighting with their natural abilities.
When using weapons, they only receive 25% EXPS.
Aliens that are pursuing a persona class will earn experience points according to that class.

The benefits of alien experience levels are quite simple.
Their natural combat abilities will improve, which is reflected in an increase in their natural combat table.
Type A attacks will add PSTR each level increase;
type B attacks will add PSTR each level increase;
and type C attacks will add DEX per level increase.
Thus an alien with a 10 DEX, 15 INT, and a 20 PSTR would add 10 to her type C attacks;
15 to her type B attacks, and 20 to her type A attacks.
Remember that not all aliens have all natural attack types.

In a more cerebral vein, aliens can increase their likelihood of becoming tool users, becoming civilized, or adopting a class.
Non-tool using aliens can add their EXPS level to their roll when trying to comprehend and employ tools.
They can also re-roll their chance to become a tool user (adjusted INT) each time they increase an EXPS level.
Tool using aliens can also add their EXPS level to their DEX roll when attempting to adapt to foreign tools.
Each new experience level that a tool using alien achieves indicates another chance (adjusted INT) to become educated and pursue a persona class.
If an alien suddenly becomes educated, she will begin her new class as a first level with 0 EXPS.

include::ROOT:partial$CH06_Table_Alien_Experience.adoc[]
