= Alien Armour Rating

Armour Rating (AR) is a combat measurement of how hard the alien is to damage.
The higher the armour rating the harder it is to hit the alien in combat.
Armour rating is covered more thoroughly in xref:iii-combat_rules:CH29_Armour_Rating.adoc[Armour Rating].

Alien AR is a composition of all the elements that make it hard to damage.
For example, dexterity, agility, hide, body coverings are rolled into AR.
The description of the alien does not influence the armour rating.
If there is a turtle shell in the description of the alien that does not improve it's AR.

:art: alien_AR_shell.png
:width: 250px
:snark: Shell is for appearance, not armour.
:artist: Unknown.
:date: Unknown.
:license: CC BY-SA 4.0
:description: Drawing of cosmetic turtle shell on back of four legged alien.


include::ROOT:partial$articulate.adoc[]

The AR is determined completely randomly.
An alien's AR can range from 503 to 800.
This roll is the exact base AR for the alien persona.
The rolled AR also represents the naked armour rating of this alien species.

Alien worn armour is extremely rare. 
It may exist for a species that has creator level xref::CH06_Aliens_13_Society.adoc[tool usage].

If a player were to roll 15, 89 and 64, her alien persona would have an AR of 668 and any attack roll would have to be higher than that value to score a hit.

== Alien Armour Rating
// tag::Alien_AR[]
.AR = 500 + 3d100
****
Rolling 15, 89 and 64, would give an AR of 668.
****
// end::Alien_AR[]