= Alien Name
The player must name her persona.
Every persona must have a moniker, call sign, label, title, handle or cognomen.
A player should avoid naming her persona with her mundane world real name.
Creating a persona name makes role-playing more fun.

Alien names can get complicated.
Every alien has a given name and a species name.
The player creates her persona's given name.
The given name is like a pet name or nickname. 
Humans go by the nickname of 'man.' 

Alien names are pronounceable in common parlance.
Aliens that communicate with pheromones, howls, or ultrasonic clicks will only use those names amongst their species.

Aliens also have a pseudo-scientific species name that becomes part of EXP's faux taxonomy. 
The humans of mundane terra ignore their species name, preferring to call themselves man.
Animalia, Chordata, Vertebrata, Mammalia, Primates, Hominidae, Homo Sapien, is a bit a mouthful anyway.

When the player evolves her alien, it represents one member of an entire species.
The species name describes every other alien persona that is *not* the player persona.
Species names reflect elements of the alien itself. 
Using Latin-sounding words makes the species name sound fancier.
A tiny poisonous alien may have the species name Minutiae Venonimous.
This naming opportunity comes with great responsibility.
Usually, the referee and players will negotiate the species name.

The indigenous denizens of newly discovered planets have no names.
Flora and fauna do not give themselves names, and it is up to the players to name them.
Until that time, the referee may assign serial numbers to identify the creatures.

.*Example persona names*
* Kolosaur of Herbiforous Giganticus
* Spink from the species Slitheracine Amicus
* Spot the Feisty a Pernicious Winged Scalamander

== History
Players should create a pre-campaign history for their persona.
A persona's initial history should not be one of great fame or import.
Role-playing in the campaign world is what should build a persona's fame and reputation.
The persona's history should fit in with the referee's milieu and campaign. 

Persona backstories should be short.
If a player wants to make an essay of her persona's background, she should not expect other players to care.

== Description
Aliens come with a detailed description based on their evolution.
The player can embellish her persona with further details: adornments, smells, colours, coverings, coats and coatings.
Overly detailed persona descriptions are fun for players to make.
Overly detailed persona descriptions are less fun for other players.
Concise descriptions make for compelling personas.

The alien persona's description is up to the player. 
However, the persona's description must fit in with the milieu of the campaign.

== Personality
A persona should have a personality of some sort.
Most often, the persona will be a reflection of the player's mundane terra persona.
Experienced players will create a personality for their persona.
The personality could be emotionally based, belief-based, or vocation-based.

NOTE: *The goal of persona personality is to have a perspective and have fun expressing it.*

Alien personalities will reflect their biology.
Prey tends to be flighty and untrusting.
Ambush carnivores could be sneaky and explosive.

== Examples

Kolosaur::
Kolosaur is a member of the species Herbiforous Giganticus.
She looks like a lumbering elephant in shape and size.
Her ferocious t-rex head and mouth are in contrast to her gentle plant-eating lifestyle.
She is bright red and covered in flowing hair.
Kolosaur is not docile and has strong opinions about food.

Spink::
Spink Parlor is his full name.
He never refers to his species Slitheracine Amicus.
Spink has jet black leathery skin and moves about like a slug that can also fly.
Spink is very formal and prefers to go by the name Mr. Parlor.

Spot the Feisty::
This alien is a Pernicious Winged Scalamander.
Spot has minimal language and befriended the expedition because they have its favourite food.
Winged Scalas used air hunt in packs, but Spot is happy to stumble around with his funny-looking new brood.
