= Alien Name

Giving a name to an alien is different from naming other personas.
The player must come up with a persona name and a species name. 

The indigenous denizens of newly discovered planets on which there is no intelligent life do not have names, and it is up to the players to name them.
Until that time, the referee may assign serial numbers to identify the creatures.

Most aliens have more than one name.
Alien species have a pseudo-scientific name that identifies the alien within EXP's faux taxonomy. 
They will also have a pet name or nickname. 
Humans go by the nickname of 'man' and ignore their taxonomy name of Animalia, Chordata, Vertebrata, Mammalia, Primates, Hominidae, Homo Sapien.

The alien's mode of communication may prevent a regular language name.
The alien may lack language and cares not of nicknames or personal names.
The alien may communicate in binary clicks, gymnastics, pheromones, or telepathy, preventing mundane terran language from understanding.

The lack of example alien names is intentional. 

