= Alien Damage Per Attack

Alien damage per attack indicates how many hit points the target loses when the player wins an attack roll.
The more damage per attack, the more dangerous the alien.
The persona's size and physical strength determine damage per hit.
Alien damage per unit depends on the alien's attack frequency. 
A small amount of damage delivered frequently can be very dangerous.

:art: budgie_octopus_bat.png
:width: 450px
:snark: Head budgie, torso bat, arms octopus, legs none.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Flying monster with a budgie face, octopus limbs and bat wings.

include::ROOT:partial$articulate.adoc[]

== Damage per Hit
The damage per hit represents how deadly an alien's naturalized attack is.
The bigger and stronger the alien, the more devastating a successful attack roll is.

How the alien delivers the damage does not affect the damage per for an attack roll win.
Does the alien bite, slash, spit, zap or barf its attack?
The alien's description usually determines the method of attack. 
If the alien uses a pincer or an open hand slap, the damage range will be the same.

A gigantic alien with a 13 PSTR would inflict 3d12 HPS damage each time the player wins an attack roll.
Aliens do not get a damage adjustment for physical strength.
The amount of damage an alien inflicts already reflects its physical strength.

include::ROOT:partial$CH06_Table_Alien_Damage_Per_Attack.adoc[]

== Alien Attack Type
The alien attack type determines how the alien delivers the damage amount.
Does the alien require physical contact to deliver the destructive force?
Does the alien launch a ranged attack to hit enemies from afar?
Is the force of the attack energized by some alien physiologic force?
The alien's description determines how the attack type works. 

include::ROOT:partial$CH06_Table_Alien_Attack_Type.adoc[]

=== Type A Attack
Type A attacks are thrusting, striking attacks powered by the alien's brawn.
These could be bites, punches, stabs, squishes, slashes, pecks, or scratches.
Type A attacks are in close combat, tentacle to tentacle attacks.
The vast majority of aliens employ type A attacks.
Unlike anthros, aliens do not get physical strength damage bonuses for Type A attacks.

=== Attack Type B
Type B attacks are ranged attacks powered by the alien's brawn.
These could be acidic spittle, flying quills, ejected spines or darts.
Type B attacks have a range and shoot like an arrow, *not* like a bullet.
Type B attacks are not long range attacks, but close combat is not required.
The alien's type B attack range is one hex per point of physical strength score.
An alien with a physical strength of 12 has a 12 hex attack range.
Unlike anthros, aliens do not get physical strength damage bonuses for Type A attacks.

=== Attack Type C
Type C attacks are the rarest and most alien naturalized attack type.
The alien has evolved a self-propelled powered attack.
These are classic sciency fiction attacks like lazer eyes or gas-propelled bone bullets.
Type C attacks are naturalized but function like a gun.
The player may turn to the hardware section xref:iii-hardware:CH46_Guns.adoc#_gun_type[Guns,window=_blank]for descriptive inspiration. 


