= Aliens

[quote]
____
*Aliens represent the infinity of organic forms that can be conscious.*
____

Alien is the colloquial term for the family diversidae.
Aliens encompass any organic living creature that has consciousness.
Aliens are evolved, represent species, and are generated randomly. 

== Alien Evolution Checklist

. xref:CH06_Aliens_1_Attributes.adoc[Attributes]
. xref:CH06_Aliens_2_Size.adoc[Size]
. xref:CH06_Aliens_3_HPS.adoc[Hit Points]
. xref:CH06_Aliens_4_Attacks.adoc[Attack Frequency]
. xref:CH06_Aliens_5_Damage.adoc[Attack Damage]
. xref:CH06_Aliens_6_CT.adoc[Combat Table]
. xref:CH06_Aliens_7_AR.adoc[Armour Rating]
. xref:CH06_Aliens_8_Shape.adoc[Description]
. xref:CH06_Aliens_9_Move.adoc[Movement Rate]
. xref:CH06_Aliens_9_WA.adoc[Wate Allowance]
. xref:CH06_Aliens_10_Mutations.adoc[Mutations]
. xref:CH06_Aliens_11_Life_Span.adoc[Life Span]
. xref:CH06_Aliens_12_Biology.adoc[Biology]
. xref:CH06_Aliens_13_Society.adoc[Society]
. xref:CH06_Aliens_14_Name.adoc[Name]
. xref:CH06_Aliens_15_EXPS.adoc[Experience]

Aliens personas are randomly generated and wildly diverse.
Size, shape, attributes, abilities are all randomly determined.
If particular elements are needed in an alien persona look to xref:CH11_Referee_Personas_Alien.adoc[referee alien personas].

EXP assumes that aliens are evolved like other personas. 
The referee's campaign need not follow this assumption.
Aliens could be fabricated, cloned, or divinely assembled.
Regardless of the back story aliens are organic life forms. 

EXP assumes that the alien evolved is an entire species.
When a player is evolving an alien she is creating a species.
The player is generating the attributes, shape and size of an entire species.
Her alien  persona is an individual belonging to this alien species.
The alien persona is an solo free-willed representative of this species.
The referee need only integrate the persona into her campaign.

== Role-Playing Aliens
Role-playing an alien is trickier than role-playing an anthropomorph.
Players can easily relate to playing anthros.
Alien and robot personas are challenging to even experienced players.
An alien is generated randomly and her shape, size and appendages vary greatly.
The persona could weigh 500kg, have pincers instead of hands, and no legs at all.
Players must learn to restrain the urge to personify their aliens.

Players running aliens have to employ the most imaginative role-playing skills.
For example, grasping with tentacles, fitting in a chair, or understanding a tool.
Alien personas may have completely different understanding of remuneration, or success.
The player's flying anemone may be cool, but opening typical doors may be impossible

:art: alien_shapes.png
:width: 450px
:snark: Alien shapes can be strange to play.
:artist: H. Brown
:date: 1938
:license: CC BY-SA 4.0
:description: Drawing of three strange shaped alien creatures. 

include::ROOT:partial$articulate.adoc[]

Alien goals may be as primal as food procurement or as sophisticated as galactic domination.
The player may even find her persona restricted to one particular biome, unable to roam freely like other personas.
Thus the player has to deal not only with the physiological aspects of her alien persona but also with an alien psychology.
The problem is not that aliens have no personality but that it most certainly will be far from human-like.
This problem of alien physiological and psychological personification is going to be the greatest challenge the player will face during actual role-play, and hopefully the most fun!
