= Alien Size

:art: alien_very_small.png
:width: 250px
:snark: Size can matter.
:artist: unknown, HM
:date: unknown, 2017
:license: CC BY-SA 4.0
:description: Drawing of clawed foot about to step on very tiny alien.

include::ROOT:partial$articulate.adoc[]

The size of an alien is not just a descriptive element.
The player generates size early in her persona's evolution because it impacts so many other alien attributes.
The alien's size determines hit points and damage amounts.
The player rolls on the Alien Size Table to determine the alien's size.

include::ROOT:partial$CH06_Table_Alien_Size.adoc[]

The player rolls five 1d100's and adds 100 for her large size alien. 
Rolling 39, 41, 11, 89 and 67 gives her alien a wate of 347 kgs.
Her alien has no description, no name, or abilities, but its wate is 347 kgs.

== Attribute Alien Size Adjustment 
The referee may choose to adjust the alien's size based on her attributes.
Attribute alien size adjustment is an optional rule.

Stronger creatures tend to be larger and dextrous creatures tend to be smaller.
The player adds her persona's Strength and subtracts her persona's dexterity from the Alien Size Table result.
An alien with a 22 STR and a 10 DEX would add 10 to her Alien Size Table result.
A die roll of 67 increases to 77, and the alien moves from medium sized to large sized. 

:art: alien_humongous.png
:width: 250px
:snark: Humongous aliens are hard to play.
:artist: Virgil Finlay
:date: 1966
:license: CC BY-SA 4.0
:description: Drawing of two humans staring into an alien larger than both of them. 

include::ROOT:partial$articulate.adoc[]

== Aliens and Size
Bigger is not always better.
The larger the alien, the more HPS it has and the more damage it can deliver.
Large and gigantic aliens are challenging to play.
The technology of EXP is for anthros, not 500kg aliens. 
Vehicles won't fit.
Armour is unwearable.
Large rifles are clumsy little sticks.
An enormous size is a constant role-playing challenge.
The analogy is the same for tiny aliens.

Two alien sizes do not appear on the Alien Size Table.
These are minute and humongous.
Minute aliens have wates less than 1kg, and Humongous aliens have wates in the hundreds of tonnes.
These extreme alien sizes are only for referee personas.





