= Alien Mutations

// tag::alien_mutations[]
Aliens have a chance of getting mutations.
However, they are more like natural abilities that function as mutations.
An alien's mutations apply to the entire species and are more like naturally evolved defensive or offensive abilities.
Therefore, alien mutations are not considered mutations in the usual sense -- as if they were abnormalities or variations from the norm.

An entire alien species can have a defect. 
The defective mutation will likely inform the alien species' culture, history, and society. 

In the case of potent mutations like time stop or death field generation limitations are recommended.
All alien species members do not possess the ability, or the ability may transiently arise. 

== Mental Abilities
The chance of an alien having a mental mutation is equal to the alien's mental strength attribute score.
An alien with a 15 MSTR would have a 15% chance of having a mental mutation.
If the alien has a defective mutation, the player gets another roll on the mutation table. 
Aliens do not have multiple mental mutations.
To determine the mutation like ability jump to xref:v-wetware:CH58_Mental.adoc[Mental Mutations,window=_blank].

== Physical Abilities
The chance of a creature having evolved a physical mutation is equal to the alien's constitution attribute score.
An alien with a 10 CON has a 10% chance of having a physical mutation.
If the alien has a defective mutation, the player gets another roll on the mutation table. 
Aliens do not have multiple physical mutations.
To determine the mutation like ability jump to xref:v-wetware:CH59_Physical.adoc[Physical Mutations,window=_blank].
//end::alien_mutations[]
NOTE: In past versions of EXP aliens could have multiple mutations. 



