= Alien Number of Attacks

:art: alien_attacks.png
:width: 250px
:snark: Many hands many attacks
:artist: Edward Cartier scan M. Moscow
:date: 1951
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Each alien has a unique frequency of attacks per combat turn.
In EXP combat turns are called units and represent a 2 second interval.
Number of Attacks is how often the player can make a attack roll each unit.
This is the most important element for naturalized alien combat.

The number of attacks only refers to the alien's natural attacks.
This does *NOT* include weapon or mutation attack frequency.
An alien with a 3 attacks per unit can only bite 3 times per combat turn.
The frequency of attack with a pistol would be determined by the pistol.

The naturalized number of attacks can only inflict the alien's naturalized damage.
The alien damage per attack is generated under xref::CH06_Aliens_5_Damage.adoc[Alien Damage]
Number of attacks represents non powered tentacle to tentacle combat.

Aliens with higher DEX scores are more likely to get multiple attacks per unit.
Players add the alien's DEX score divided by three to the die roll.
For example, a persona with a 15 DEX would add 5 to her die roll.

include::ROOT:partial$CH06_Table_Number_of_Alien_Attacks.adoc[]

The player can attack up the number of attacks per unit.
She is not required to full on attack all attacks each attack round.
(attack of the attacks)
The persona with three attacks can attack three different targets.
Attack frequency gets powerful and complicated in no time.
