= Alien Combat Table

The tactical combat system in the roll playing rules uses an attack matrix called the combat table.
The player refers to the combat table every time she makes an attack roll.

The alien combat table is for the alien's natural attacks.
An alien's combat table will only include the alien's natural attack types.
If the alien only ever bites with a Type A attack, the player only completes the Type A attack on the combat table.  
If the player shoots deadly sap blobs as a Type B attack, the player only completes the Type B attack on the combat table.

The combat table lacks a bonus non-proficient (BNP) column. 
An alien can't be unskilled with her natural attack.
The combat table lacks a damage adjustment (DA) column.
The alien's damage per hit already includes her physical strength.
These limitations can make an alien combat table pleasantly simple.

== Type A Attacks
Thrusting and striking weapons for aliens include their naturally endowed thrusting and striking attacks (bite, punch, claw, beak, gore, stab, rake, slice, gouge, tear, trample).

== Type B Attacks
This attack type is for those aliens that fling objects, shoot quills or spit in an attempt to inflict their natural damage (spit, breath, blast, arc, spray).

== Type C Attacks
This attack type is for those creatures with naturally powered attacks (lasers, sonics, electric arcs, radiation doses).
Aliens with natural powered attacks are very rare and extremely dangerous.
They have specially evolved organs that attack like a powered weapon, such as a gun.

include::ROOT:partial$CH06_Table_Alien_Combat_Table.adoc[]

For example, Sal the gigantic alien has a 22 PSTR,  15 DEX,  3 INT and a type B attack (spitting sharp blobs of resin) that attacks three times each unit would have the following combat table:

// Sal's Alien Combat Table
.*Sal the Alien's Combat Table*
[width="75%",cols="<,4*^",frame="all", stripes="even"]
|===
5+<|Example Combat Table for Sal the resin spitting alien.

s|Attack Type
s|BP
s|BNP
s|MR
s|DA

|A (contact)
|--
|--
|--
|--

|B (ranged)
|150
|150
|900
|4d12

|C (weapons)
|--
|--
|--
|--

s|Attack Type
s|BP
s|BNP
s|MR
s|DA
5+<|Alien DA is the damage range not a bonus.
|===

== Aliens and Weapons
If the alien's culture, society and tech level allows her to use a weapon, the player must create a vocation based combat table.
Technologically advanced tool-using aliens may be able to pursue a vocation. 
If the alien is a tool used but has no vocation, the alien uses the Nothing vocation combat table when using a weapon.
If the alien has a vocation, the player will generate another combat table for the alien's vocation type.