Experience points (EXPS) are the currency of growth for EXP personas.
The more EXPS a persona collects, the better their persona gets.
For a more detailed review of experience points jump to xref:i-roll_playing_rules:CH15_Experience.adoc[Experience,window=_blank].

== Aliens With Vocations
If an alien has a vocation, they advance in experience levels as that vocation only. 
Aliens pursuing vocations have evolved beyond the primal alien experiences of their species.

== Aliens Without Vocations
Very few aliens will have a vocation. 
Without vocations, Aliens still collect experience points and improve themselves by advancing EXPS Levels.

Aliens earn full experience points for combat when using their natural abilities.
Aliens earn partial combat experience when using a weapon other than their natural abilities.
Aliens only receive 25% of combat experience when using weapons.
Aliens can earn EXPS for role-playing just like any other persona.

== Combat Table Improvements
As an alien gains experience levels, she improves her combat table. 
The combat table improvements are for her naturalized attacks and do *not* apply to weapons.
The alien increases her Skilled Bonus and Max Roll for each new experience level.

include::ROOT:partial$CH06_Table_Alien_CT_Levels.adoc[]

The alien can only improve those naturalized attack types that she has already evolved.
An alien with a Fling spittle attack and a 12 DEX would add 12 to her Skilled Bonus and Max Roll for each new EXPS Level.
There is no change in damage or movement rate.

== More Society Please
At each new EXPS level, the player can return to the alien society section and recheck to see if her persona alien can personally evolve.
For example, an alien with only language can check again for culture. 
The persona would not check for religion, although it would be fun to burden a player persona with an unplanned religious hankering.
The persona can advance to vocations if the dice allow.
At this point, the player can choose to follow a vocation abandoning her species-based EXPS collection.

== All Those Rolls
Aliens can add their EXPS Level to any roll that any other persona can.
The types of rolls improved by EXPS Level are saving rolls, attribute rolls, and adapting tool checks. 

include::ROOT:partial$CH06_Table_Alien_Experience.adoc[]
