= Alien Description

In keeping with the family name diversidae alien descriptions are very diverse.
The alien description system is wild and unpredictable.
An alien description is a mash up of body parts from a list of earth dwelling denizens.
Each creature part listed will be familiar to the ref and players.
Four different creature types are combined to create a new alien description.
The four parts are proportional to each other and represent appearance only.

Each alien body part has some letters (l,a,w,s) associated with it.
These letters determine the alien's movement rate later.
Please record them with alien part generated.

:art: alien_assembly.png
:width: 450px
:snark: Four rolls. One alien.
:artist: Kevin Long
:date: 1992
:license: Copyright 1992 Kevin Long
:description: Drawing showing four earth creatures being combined into one alien creature.

include::ROOT:partial$articulate.adoc[]

== Generating the Description
The size of the alien has already been determined.
The alien's shape is now determined with four separate rolls on the Alien Body Part table.
Each alien rolls for a head, torso, arms and legs.
Each body part represent the appearance/shape of each part. 
The body part does *NOT* represent the function in any way.

=== Make a Drawing
Attempting to draw the alien helps connect it together.
This does not require an artisan level rendering.
Putting the body parts together on paper (now screens) helps evolve the alien.

== Alien Description Checklist
. Head Part
. Torso Part
. Arms Part
. Legs Part
. Coat and Colour
. Adornments

=== Head Part
The alien's head part _usually_ stores the alien's brain and sensors.
The head is _usually_ located at the front of the alien.
Record the movement letters (l,a,w,s) associated with the head part.
An optional head adornment may be added later

=== Torso Part
The alien's torso part _usually_ stores the alien's vital organs.
The part does not indicate the types of vital organs but they are most likely in the torso.
Record the movement letters (l,a,w,s) associated with the torso part.
An optional torso adornment may be added later

=== Arms Part
The alien's arms part _usually_ indicates the persona front limbs and articulators.
The arms part does not has no effect on whether the alien is a tool user or not.
Record the movement letters (l,a,w,s) associated with the arms part.
An optional grabby adornments may be added later.

=== Legs Part
The legs part _usually_ indicates the main way the alien gets around.
Record the movement letters (l,a,w,s) associated with the legs part.
Legs part does not solely determine alien locomotion.
If an alien can fly and run it will have the parts for both. 
Often an alien's legs will not be legs at all but flukes, flippers, bulbs and blobs.
If the alien has snake's legs, it slithers about.
If the alien has fish legs, it may wiggle or fin itself about.
If the alien has parrot arms and fish legs it can still fly and slither.

include::ROOT:partial$CH06_Table_Alien_Body_Parts.adoc[]

== Coat and Colour
The four parts of the alien converge to create a unique new creature. 
The head, torso, arms and legs are amalgamated into the alien appearance.
The player and referee decide on the connections between the parts.
Does the alien have a tiger neck or worm neck?

The aliens do not appear in a patch work, and usually have a single coat.
This covering can be chosen from any of the four parts or created de novo.
The player can also choose a colour from the parts, or roll on the colour table.

=== Alien Coat Colour
The player can roll on the following three tables to generate a coat colour. 
. Roll a main colour
. Roll as secondary colour
. Roll the pattern of the colours
. Roll an affect for each colour

include::ROOT:partial$add_colour_to_your_world.adoc[]

== Adornments
These are optional accents to the alien's appearance.
Adornments are entirely descriptive.
Adornments do not detract from or add any abilities to the alien. 

// Mundane horse like alien with head adornments


// Adornment or body part type doesn't matter

=== Alien Head Adornment

:art: alien_head_adornment.png
:width: 250px
:snark: Head tusklers.
:artist: Unknown.
:date: Unknown.
:license: CC BY-SA 4.0
:description: Drawing of horse like alien with big tusk horns on it's nose. 

include::ROOT:partial$articulate.adoc[]

include::ROOT:partial$CH06_Table_Adornment_Head.adoc[]

=== Alien Torso Adornment

include::ROOT:partial$CH06_Table_Adornment_Torso.adoc[]

=== Alien Arms Adornment

include::ROOT:partial$CH06_Table_Alien_Adornments_Arms.adoc[]

// table insert 94

:art: alien_none.jpg
:width: 250px
:snark: No parts. No body.
:artist: Earl Bergey
:date: 1945 
:license: CC BY-SA 4.0
:description: Drawing of a liquid blob alien jumping out of a giant glass box.


include::ROOT:partial$articulate.adoc[]

== Missing Parts
If the player rolls _None_ for a body part that part is not there.
The alien does not have and has no use for that particular body part.
An alien with no head part may have sensors attached to the torso.
An alien with no legs may move by means of the torso or be immobile.
Missing parts decrease the alien's movement rate. 
An alien with no body parts would be some kind of gaseous, or blob entity.
at all is the type of non-entity that livens up campaigns.

== Description and Tool Use
The arms part has no bearing on whether the alien is a tool user or not. 
Tool using is determined in the Society section. 
Even if the alien has hands with opposable thumbs she may not recognize tools at all.
The alien hands could be used to pick berries or peel the flesh off of prey.

The corollary is true as well.
If an alien is a tool user this will not be affected by the alien's arms part.
An alien can be a tool user but has no arms but flippers, hooves, or fins.
The grabby things will have adapted to use tools, or the vice versa.

== Description and Proportions
Each body part is proportional to the other body parts in the description
The size of the alien is already determined (Small, Medium, Large, etc.).
A mite head part combined with a bear torso part would have matching size.
The alien would not have a microscopic head on a bear torso.
The alien would be described as a long nosed insect head on hairy bulky body.
The mite's head would be a size proportional to the bear torso.

The corollary is the same.
If an alien is tiny sized that is what determines the alien's size.
A giraffe head part combined with a sperm whale torso part would still be tiny. 
The alien would described as a tiny giraffe head on a tiny sleek body with a whale tail.

== Description and Biology
This is just another reiteration that the alien parts represent structure not function.
Don't let scientific knowledge get in the way of fun and story telling.

[quote]
_____
Harrumph! An amoeba of that size would collapse under its own weight.
_____

The alien is *not* a 542 kg pink amoeba. 
The alien has a wate of 542 kg, it is pink and merely looks like an amoeba.

This alien is held together by alien physiology crafted by generations of evolution.
It's internal composition consists of alien biology that is unlike our.
Just as fantastical devices are justified by _black box_ tech beyond our knowledge, so can alien biology

== Description and Movement
Alien movement is determined by it's description. 
The alien's base movement rate has already been determined.
An alien moves 1 hu per point of DEX score.

Players will be sad to hear that the base movement rate is affected by the body parts.
There are letters in brackets beside each body part.
The terrain letters indicate what terrain type the alien can move in.
Keep track of all of these letters to determine movement rate.

Land creatures have (l) where "`l`" represents land movement (running).
Airborne creatures have (a) where "`a`" represents air movement (flying).
Aquatic creatures have a (w) where "`w`" represents water movement (swimming).
Sessile creatures have an (s) where "`s`" represents no movement (sitting).
Sessile creatures are usually found in certain environment types as listed above.

.*Examples*
* A rabbit is a land creature (l);
* An alligator is land and water creature (lw);
* A hawk is an airborne creature (a);
* A duck runs, flies and swims (law);
* An anemone is sessile aquatic (sw).


.*Visual Example*

:art: alien_trex_head_tricera_lynx_manta.png
:width: 250px
:snark: Head: t-rex, Torso: triceratops, Arms: lynx, Legs: manta ray
:artist: Nelson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of an alien Head: t-rex, Torso: triceratops, Arms: lynx, Legs: manta ray

include::ROOT:partial$articulate.adoc[]

* t-rex (l)
* triceratops (l)
* lynx (l)
* manta ray (w)


