= Mutating

[quote]
____
*to change state or condition, undergo change, from Latin mutatus, past participle of mutare to change*
____

In EXP, the term mutation is not limited to the biological transformation of DNA.
Mutations represent randomly acquired permanent changes to the persona. 
The mutation story is deeply rooted in sciency fiction.
In reality, biological mutations are mostly fatal.

In the sciency fiction world of EXP, mutations are just plain fun.
A referee can't explain this process scientifically.
Mutations are part of the game and fall under the 'black box' explanation. 
However, pseudo-scientific justifications add to the milieu of the campaign.

Mutations have two broad categories: mental and physical.
Mutations.

This section is a tasty overview of mutations in EXP.
Mutating is a mere place holder to help with persona generation.
The meat, metal and metamorphosis of mutations is in the section xref:v-wetware:CH57ish_Mutations.adoc[Mutations]

== Anthros and Mutations
Anthro mutations represent changes in persona DNA that create unique persona changes.
Mutations can be innocuous, powerful or deleterious.
Anthro mutations are the stuff of sciency fiction legend from comics to movies.
Players have full awareness of their persona's mutations.
However, a fun campaign twist is to have the mutation activated by some story trigger.
Some refs have personas acquire their mutations through gameplay.
Going skinny dipping in the glowing creek could be a way to activate an unknown mutation.

The anthro type determines the persona's mutation frequency.
Humanoids are much more likely to mutate than insectoids.
The player can also choose to mutate and increase her persona's mutating chance.
To get the anthro mutation deets, jump to xref::CH04_Anthros_Mutations.adoc[Anthro Mutation]. 

== Robots and Mutations
Robots do not have DNA to mutate, but robots can still have mutation effects.
Robot mutations represent unique malfunctions of existing systems.
The mutation effect is novel to the collection of peripherals and malfunction.
On occasion, a robot will generate a weapon or device that mimics a mutation.
There is no specific check for robot mutations, but they can randomly acquire mutation like functions during their fabrication. 

== Aliens and Mutations
Evolving an alien creates not just a persona but an entire species.
Alien mutations are natural abilities that the alien species has evolved.
However, it does not mean that every member of the species will have that mutation.
For example, if an alien person has the mutation time stop, it is unlikely every alien in the species does.
EXP does not broach the possibility that an alien persona may acquire a mutation unique from her species.
To get the alien mutation deets, jump to xref:CH06_Aliens_10_Mutations.adoc[Alien Mutations].