= Mutating

[quote]
____
*to change state or condition, undergo change, from Latin mutatus, past participle of mutare to change*
____

In EXP the term mutation is not limited to the biological transformation of DNA.
Mutations represent randomly acquired permanent changes to the persona. 
The mutation story is deeply rooted in science fiction.
In reality biological mutations are mostly fatal.

In the science fantasy world of EXP mutations are just plain fun.
It is impossible for a referee to scientifically explain this process.
Mutations are part of the game and fall under the 'black box' explanation. 
However pseudo-scientific justifications add to the milieu of the campaign.

Mutations are divided into two broad categories: mental and physical.
Mutation

This section only begins to cover mutations in EXP.
Mutating is a mere place helder to help with persona generation.
The meat, metal and metamorphosis of mutations is in the section xref:vi-mutations:An_index_mutations.adoc[Mutations]

== Anthros and Mutations
Anthro mutations represent changes in persona DNA that create unique changes in the persona.
Mutations can be innocuous, powerful or deleterious.
Anthro mutations are the stuff of science fantasy legend from comic books to movies.
Personas can be generated having full awareness of their mutations.
However a fun campaign twist is to have the mutation activated by some story trigger.
Some refs have personas acquire their mutations through game play.
For example, going skinny dipping in the glowing creek.

Anthro mutation frequencies are determined by their anthro type.
Humanoids are much more likely to mutate than insectoids.
The player can also choose to mutate to increase the chance of her persona mutating.
The deets are located in section xref::CH04_Anthros_Mutations.adoc[Anthro Mutation]. 

== Robots and Mutations
A robot mutation is not an alteration in the persona's DNA.
Robot mutations represent completely unique malfunctions of existing systems.
The mutation effect is totally unique to the collection of peripherals and malfunction.
On occasion a robot will generate a weapon or device that mimics a mutation.
There is no specific check for robot mutations.
Robot mutations are acquired  like functions during their fabrication 

== Aliens and Mutations
Alien mutations are evolved abilities that are part of their alien species.
Evolving an alien creates not just a persona, but an entire species.
The persona will definitely have the mutation created. 
However it does not mean that every member of the species will have that mutation.
For example, if an alien person has the mutation time stop it is unlikely every alien in the species does.
The deets are located at xref:CH06_Aliens_10_Mutations.adoc[Alien Mutations]