= Veterinarian

:art: veterinarian.png
:width: 250px
:snark: Vet resuscitating an insect.
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a humanoid crocodile professor working on a dragonfly. 

include::ROOT:partial$articulate.adoc[]

Veterinarians are the healers of the organic world.
Vets are combination doctor, homeopath, surgeon, paramedic, and faith-healer.
They can utilize whatever odds and ends available to assist organic personas in need.
Vets are self trained and have *not* been trained at a college or school.
They learned from oral histories, experimentation, pamphlets or bits of AV material. 
Their work may be temporary or permanent, incompetent or miraculous.

== Vet Conduct
Veterinarians need the trust of their patients to function.
This therapeutic relationship is based on charisma, trust and skill.
This vocation does not have an oath by any means, but proper conduct makes then better vets.

* Avoid using weapons that kill or damage life.
* Avoid using violence as solution unless last resort.
* Make the best choices for their patients

The more the vet strays from these suggested tenets the harder it will be to heal personas.
It is also possible that a guild, or club may take issue with a violent vet.
This conduct is a general goal.
The persona need not be a pacifist or sacrifice their lives senselessly.

== Vet Abilities
Vet abilities are special aptitudes that a vet can accomplish and other vocations cannot.

=== Quick Fix (DD varies)
This ability allows the vet to quickly repair injured personas.
Quick fixes give the persona a HPS boost. 
They are most commonly carried out during combat and are completed in units.
Yup that is quick.

The difficulty and during of a quick fix depends on the amount of healing desired.

// Vet Quick Fix new for versions 6.0
.*Vet Quick Fixes*
[width="75%",cols="3*^",frame="all", stripes="even"]
|===
2+<|Snappy HPS restorations. 

s|Heal Amount
s|DD
s|Duration

|5%
|5
|1 unit

|10%
|10
|2 units

|15%
|15
|3 units

|20%
|20
|4 units

s|Heal Amount
s|DD
s|Duration
|===

== Subliminal Suggestion (MSTR  DD)
Words can be popped into the minds of unsuspecting victims.
Simple commands such as "`Don't jump`", "`Wait`", and "`Give it`" may be forced upon the victim.
The more reasonable the suggestion, the more likely that it will succeed.
There is no save versus a successful PT roll.

== Paralyzing Pinch (CON DD)
The vet can render the target unconscious using a dramatic pinch technique.
In an unwilling patient a attack roll must be successful.
The pinch must be applied for 0-2 units (1d3-1).
A attack roll must be made each unit of holding on. 
Only after the successful attack rolls is the performance roll made.
Willing patients do not require the vet to make a attack roll.
An easier performance roll must still be made on a willing patient. 
This ability is used as a non-pharmaceutical anesthetic by the vet.

If the performance roll is successful, the target is immobilized for 1 minute.
The target does not get a saving roll.
A failed performance roll leaves the target enjoying a harmless shoulder grip.

== Death Pinch (double CON DD)
Paralyzing pinch plus.
Death Pinch is the deadly version of the paralyzing pinch.
There are no voluntary receivers of this attack.
If the death pinch is successful the persona gets a saving roll vs death.
The vet must hold on for 0-3 units (1d4-1) in a row.
This means a successful attack roll for each unit of the death grasp.

== Vet Skills
Vet skills are random areas of knowledge picked up during their career.
A vet gets one roll on the Vet Skills Table for every 3 points of INT.
So a vet with an 18 INT would get 6 rolls on the skills table. 
Consider the following rolls: Psionics, Surgery, Psionics, Infection, Aging, Surgery.

The vet gets a new roll on the skill table each new EXPS Level.

.Example Vet Skill List
* Surgery 2
* Psionics 2
* Infection 1
* Aging 1

Vet skills can be combined into better skill bonuses.
Any surgical procedure would get a skill bonus of +2.
If the surgery is for an infection the skill bonus would be +3.
If the surgery vs infection is for an aged persona the skill bonus would be +4.

include::ROOT:partial$CH08_Table_Veterinarian_Skills.adoc[]

== Vet Experience
Vets gain experience for successful performance rolls.
They earn 70 EXPs per DD.
Since vets are a non-combat vocation, they may only receive 10% of combat experience.
Gaining experience allows for an increase of experience levels.
The higher the experience level, the better chance the vet has of having a successful practice in a fashionable part of the universe.

include::ROOT:partial$CH08_Table_Veterinarian_Experience.adoc[]

