= Nothing

:art: nothing_sales.png
:width: 250px
:snark: Fun guy car sales.
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid mushroom headed used car salesman.

include::ROOT:partial$articulate.adoc[]

The nothing is the non-vocation vocation.
The nothing is the unskilled civilian of the role-playing world.
Most player personas become nothings because they lack any other vocation attributes. 
There are no requirements to follow the nothing vocation besides being alive.
A player can choose the nothing vocation for her persona.

NOTE: Nothings can have a vocation aspiration, allowing them to follow a vocation eventually.

Other vocations have keen areas of interest that assist the expedition's survival.
The nothing vocation is mainly concerned about material goods and their social standing.
A nothing career has no measurable value to the expedition.

.Nothing Vocation Checklist
. Home
. Career
. Social Standing
. Net Worth

== Home
Nothings are not from nowhere.
The nothing home is like a cultural biome.
A home is where the persona's social standing and wealth have the most influence.
A nothing vocation can have multiple homes.

The player makes one home roll per 4 points of the persona's charisma score.
The persona adds a new home at every new EXPS Level.
The player can choose to extend an existing home or randomly generate a new one.
If a persona gains an EXPS level in a foreign home, she automatically adds it to her home list.

include::ROOT:partial$CH08_Table_Nothing_Origin.adoc[]

== Career
A nothing's career is neither a skill nor a vocation.
The persona's career may be something that they talk about a lot, but it has no value to expedition survival.
It will be a rare circumstance when a nothing can use her career to aid the expedition.

A nothing can pursue greatness in her nothing career.
However, her social standing solely determines her career success and nothing else.
A nothing may aim to become the best chef in the city, an accountant, or the fastest cage cleaner.

include::ROOT:partial$CH08_Table_Nothing_Skills.adoc[]

== Social Standing
Most personas rolled their social standing (SOC) when generating attributes.
A nothing's social standing is the root of her self-worth.
The higher their social standing, the more influential the nothing is.
For the nothing vocation, social standing is synonymous with wealth and power.
Other vocations may understand social standing's value but have little or no interest in it.
For more information about SOC, jump to xref:i-roll_playing_rules:CH03_AttributesSS.adoc[social standing,window=_blank].

A persona can improve her social standing by increasing her EXPS levels.
A nothing adds 1-100 (1d100) to her social standing for each new EXPS level.

== Net Worth
Personas in the nothing vocation start with a lump of material value.
This wealth is never an artifact or useful device.
The source of wealth is usually limited to the persona's home.
The nothing persona's wealth will be items like property, furniture, bonds, bank accounts, or piles of coconuts. 
Ultimately, the wealth's description depends on the referee's milieu.

The persona's social standing attribute guides the value of her wealth.
Her social standing indicates the number of wealth rolls and the wealth rolls' value.
A campaign could easily revolve around a nothing persona with spectacular wealth and connections.

The treasure system is complicated and convoluted.
The player does not need to know the treasure type.
The player only uses the two tables below to determine her persona's net worth.
If you want more information about treasure jump over to  xref:iii-hardware:CH53_Treasure.adoc[Treasure,window=_blank].

include::ROOT:partial$CH08_Table_Nothing_Wealth.adoc[]

NOTE: A nothing cannot get an artifact when calculating net worth.

include::ROOT:partial$CH53_Table_Treasure_Value.adoc[]

== Pulling Privilege
A nothing persona has one ability, and it allows her to get her way whether she deserves it or not.
A nothing can apply social pressure on another nothing to get her way.
Pulling privilege involves using connections, wealth or career power to get their way.
The nothing persona with the higher social standing wins.
The mechanics of this can vary with the milieu and the story.

Pulling privilege does not work on personas with vocations. 
Nothings can only use this ability on other nothings for inconsequential outcomes.
Examples of pulling privilege are using SOC to: get sports ball tickets, jump the queue, university admission, or hairstylist appointment.

:art: nothing_suit.png
:width: 250px
:snark: Fully armoured nothing.
:artist: Imagestok-Studiostoks
:date: 2017
:license: Copyright Studiostoks 2017
:description: Drawing of a feline humanoid dressed in a suit and tie.

include::ROOT:partial$articulate.adoc[]

== Nothing Experience
Nothings gain experience points by earning money.
Nothings only get 10% of combat experience.  
Nothings are the only vocation that earns EXPS from money.
A nothing earns 1 EXPS for every 100 eps made.
Earned money is monies collected from life-threatening exploration.
Earned does not include gifts, stipends, grants, awards, or risk-free salaries.

The persona only gains nothing EXPS levels if the player has chosen this as her persona's sole vocation.
If the player has chosen to pursue nothing as her persona's vocation, she increases EXPS levels as she earns experience. 
Each new EXPS level increases the persona's SOC and adds a new home.

The persona does *not* use these EXPS levels if she has a vocation aspiration.

include::ROOT:partial$CH08_Table_Nothing_Experience.adoc[]

== Vocation Aspiration
A nothing can pursue a full-fledged vocation if the player desires.
The player can declare her nothing persona to have a vocation aspiration at any time.
However, it is best to make a vocation aspiration clear when the persona is created.

Instead of using EXPS to gain experience levels, the player pools her  EXPS to pursue her preferred vocation.
The nothing persona vocation aspiration allows a player to pursue a vocation even if her persona lacks the attributes.
Vocation aspiration cannot bypass the attribute requirements for the knite vocation.

NOTE: The nothing persona needs an example of her vocation aspiration present while earning pooled EXPS. 


A nothing persona aspiring to become a mercenary must collect 18001 EXPS to become a mercenary persona.
Once she has earned those 18042 EXPS, she becomes a first level mercenary.
The persona leaves the nothing vocation behind and becomes a full-fledged mercenary with 0 EXPS.

include::ROOT:partial$CH08_Table_Experience_to_First_Level.adoc[]

== Nothing Maneuvers
Nothing maneuvers are about surviving in the social fabric of wealth, fame and luxury.
Nothing maneuvers do not really exist, as they offer nothing of worth to the expedition.
If the expedition convinces the referee that a nothing maneuver is possible it will be a Gut maneuver.

The essential equipment for a nothing is any useless item of arbitrary value.
This could be a some cash, a credit card or a vacation souvenir.
The referee may make a target roll more difficult if the nothing has nothing.

include::ROOT:partial$CH14_Table_DD_Nothing.adoc[]