= Nomad

:art: nomad_urban.png
:width: 250px
:snark: Urban nomad in city biome.
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Nomads are survivalists.
They are experts at finding their way, constructing shelter, and doing well with nothing more than their bare hands.
Nomads can aid the expedition by providing a source of intuitive survival skills.

== Nomads and Technology
Nomads will generally shun technology if it is unnecessary for survival.
This vocation prefers to sleep in a hollow log or a dumpster rather than a hotel room or tent.
The other classes are not able to grasp the subtleties necessary to adapt to and live off an environment.
This is something that players must remember and not waste role-playing time trying to do.
The nomadic skills were most likely acquired by the persona after she found herself isolated in some perilous situation and had to make do or die.
It is very unlikely that there are accredited schools of nomadic adventure.

== Nomadic Biomes
Nomads have an initial home base or biome.
A biome is any easily distinguishable subsection of an ecosystem.
A biome could be a deciduous forest, tropical savanna, or radioactive ruin.
It is in this biome that the nomad functions best.
Nomad are not limited to their home biomes.
Biomes are not planetary specific.

NOTE: *Biomes are nomad skills. This nomenclature is due to legacy and fun.*

:art: nomad.png
:width: 250px
:snark: Nomads desert biome.
:artist: Louis Glanzman
:date: 1952
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The nomad gets one roll on the biome table per 4 points of Awareness.
A nomad with a 16 AWE would start with 4 biomes.
The player rolls: Farm, Toxic; Forest Toxic; Farm Underground and Coniferous Normal.

.Example Nomad Biomes
* Farm 2
* Toxic 2
* Forest 1
* Coniferous 1
* Underground 1

The biomes are cumulative and separable. 
A nomad using an ability or skill on a toxic farm would get a bonus of +4.
Attempting a maneuver in an Underground Forest would get a bonus of +2
If that underground forest were coniferous the bonus would be +3.

A new biome is acquired each time the nomad earns an EXPS level.
This can be randomly rolled or assigned by location. 
This is decided by the referee and the players. 

include::ROOT:partial$CH08_Table_Nomadic_Biome.adoc[]

include::ROOT:partial$CH06_Table_Alien_Biome_Characteristic.adoc[]

== Nomadic Abilities
Nomadic abilities are built in skills that other personas cannot do. 
The referee may adjust the degree of difficulty as she sees fit.
For example, finding water in a vac suit is harder than in a rain forest.
Ability performance rolls are improved by the nomad's biomes.

=== Find Water (special)
Collecting water is a 3 + D4 DD action and it can only supply enough water for one person for one day.
To locate a continual source of water (spring, well, or water main) is an 8 + d4 DD maneuver.
All collected water should be routinely purified (5 + D4 DD).
This will eliminate any bacteria or toxins that are unaffected by boiling.

=== Find Shelter (1d4 DD)
This is the ability to either find or build shelter employing nothing other than the biome's materials.
The shelter can protect from the elements, local pests, or toxins.
The nomad must make a performance roll for each persona she is sheltering.
The referee may require additional performance rolls to shelter from pests as well as weather.

=== Make Fire (1DD)
The ability to produce fire from local materials.
The difficulty should be increased by challenging atmospheric or austere conditions.

=== Safe Campsite (1d8 DD)
Successful use of this skill can determine if the chosen camp is safe from natural disasters (e.g., avalanches, floods, fallout, or worse).
Safe campsite designates an area that is safe and any persona within this area is safe from the biomes`' natural disasters.
This skill can be used to reduce the chance of being found by local hungry life forms.

=== Find Food (Various)
Here are four skills relevant to the acquisition of food in the wild.
* gather (1d6+3 DD);
* prepare safely (1d6+4 DD);
* cook (1 DD);
* preserve (1d6+6 DD).

=== Clothing (1d6 DD)
This involves the design of protective clothing.
It could offer warmth, ventilation, or protection from inhospitable environments.
The nomad must roll once per set of clothing required.
Camouflage clothing can also be fashioned from local materials.
Camo triples the DD of the performance roll.

=== Safe Passage (1d12 DD)
The nomad can determine a safe passage through seemingly impassable terrain: a mountain range, a toxic area, or a red light district.

A performance roll is required for each component of the safe passage required.
One roll for the safest route through the city and  one roll to avoid the police.
A failed performance roll will may mean no passage or unsafe passage.
The result of the failure is determined by the referee and the players. 

This ability should not be used to short circuit a referee's wonderful scenario.

=== Poison Cure (special)
The Nomad can cure an organic poison that comes from one of her known biomes.
For example a poison bite could be cured, but a weaponized neurotoxin could not.
The degree of difficulty is equal to the poison intensity.
If the paralysis poison has an intensity of 12 the DD would be 12.
Success can reverse a failed saving roll or prevent a saving roll altogether.
Failure indicates the poison takes it's natural course.

=== Husbandry (special)
Nomadic husbandry involves the befriending and training of alien flora and fauna.
Aliens with language, culture, education, vocations or tool users are not flora or fauna.
Husbandry is limited to flora and fauna type aliens.
Husbandry does not work during combat or with violently defeated aliens.
Husbandry does not work with hungry aliens where the nomad is brain.

The nomad has decided to work her husbandry on a Festinated Wumpus. 
The Festinated Wumpus has a 4 INT. 
The Wumpus is a herbivore that the expedition has never hunted or killed.
The Wumpus does not use tools and has no language. 

==== Befriending (INT DD)
Befriending is the first stage of husbandry. 
Befriending indicates an alien that trusts and won't run from the nomad.
The degree of difficulty (DD) for befriending is equal to the alien's INT.
To befriend the Wumpus the nomad must make a 4DD performance roll.

==== Taming (Double INT DD)
Taming is the second stage of husbandry. 
An alien must be befriended before being tamed.
Taming indicates the alien has attained a pet status.
The degree of difficulty (DD) for taming is equal to twice the alien's INT.
To tame the Wumpus the nomad must make a 8DD performance roll.

==== Tricks (special)
An alien that has been tamed can be taught tricks. 
Each trick has its own DD determined by the referee. 
The performance roll must be made each time the nomad calls the alien trick.
The nomad has trained her Wumpus to fetch an ammo pack.
The referee has assigned a difficulty of 12DD to the fetch trick.

To teach the trick would be a 24DD performance roll.
The nomad must make a 12DD performance roll each time the trick is attempted.
Failing to carry out the trick should be humorous before deadly.

=== Tracking (special)
Nomads can track anything that they want.
Tracking is not limited to organic persona.
Inorganic personas, and vehicles can be tracked by their impact on the environment.

==== Following (INT DD)
The nomad can successfully follow a target with a performance roll equal to target's INT.
If the nomad were tracking the Wumpus above the following DD would be 4.
Complications such as flight, burrowing, and teleportation will adjust the DD.

Following indicates that the prey has not escaped. 
If the nomad fails this performance roll the Wumpus has gotten away.

Following prey can last 2-200 (2d100) hours and the referee must fill this time frame.
The nomad finds out if the follow was successful at end of the follow duration.

==== Finding (INT DD)
If the nomad has successfully followed the prey they can find it with another performance roll.
After a successful tracking spell a Finding performance roll will offer a direct find.
fit).

==== Reverse Tracking 
Reverse tracking is used by the nomad to determine if she is being followed.
It is a much harder skill to employ but it yields an answer immediately.
Reverse tracking is a personal skill.

== Nomadic Experience
Nomads get half experience for combat and 30 EXPS per DD for successful PT rolls.
Increasing levels allows the nomad a greater chance of survival in the wild or combat.

include::ROOT:partial$CH08_Table_Nomadic_Experience.adoc[]