= Mechanic

:art: mechanic.png
:width: 250px
:snark: Mechanic mechanizing a mech.
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: 
:description: Drawing of humanoid panda with trucker hat using a wrench.

include::ROOT:partial$articulate.adoc[]

Mechanics are personas which have deep interest in the workings of the inorganic physical world.
The vocation of mechanic encompasses all skills and knowledge of a technical nature -- whether it be electronic, mechanical, structural, etc.
In general mechanics are handy personas.
Their skills can range from laser technology to unclogging drains.
Unfortunately, they only have bits and bytes of rudimentary knowledge at their disposal.
Mechanics are especially beneficial to the expedition when artifacts need identifying.
They are essential if the expedition expects to repair damaged equipment or attempts to construct unique contraptions.

== Mechanic Abilities
The mechanics have some special abilities related to their vocation that other personas cannot attempt.
An ability is slightly different from a skill.
A skill could be learned by any persona. 
These abilities are limited to the vocation mechanic.

=== Mnemonic Trapping (1d8 DD)
Using finely trained memory skills the mechanic can memorize addresses, instructions, serial numbers, or procedures for later use.
The referee can adjust the degree of difficulty of the maneuver depending on the complexity of the sequence or its length.

=== Brainstorming (1d20 DD)
This ability allows the mechanic to solve complex problems by relating incongruous pieces of information by thinking laterally and by thinking imaginatively.
If the brainstorming attempt is failed, the persona will most likely come up with a hair brained idea instead of no idea at all.
The effect of this ability can be to solve a problem completely, partially, or to earn a PT roll bonus of 1 to 4 DDs.
Brainstorming can be limited by the referee and its degree of difficulty adjusted as needed.

=== Mental Patenting (Triple DD)
The mechanic can memorize a maneuver that she has successfully completed in such a fashion that she can repeat the maneuver flawlessly.
If the mechanic is upgrading ammo for a mercenary repeatedly she may want to memorize it.
Successful mental patenting will allow her to upgrade the ammo flawlessly in the future.
To mentally patent a 4DD maneuver requires a DD12 performance roll.
Mental patented maneuvers do not work with research teams.
Mental patented maneuvers do not earn repeat experience points.

== Mechanic Skills
Mechanics have gained their knowledge from an array of inconsistent sources: curious observation, tinkering or perusing manuals.

The player is entitled to one roll on the Mechanic Skill table for every three points of INT.
For example, a persona with a 16 INT would get five rolls on the Mechanic Skill table.
The player rolled Chemistry 3 times, Detectors 1 time and Mending 1 time.

.Example Mechanic Skill List
* Chemistry 3
* Detectors 1
* Mending 1

Mechanic skills are cumulative and combinable.
A maneuver that involved purely chemistry would give the mechanic a skill bonus of +3,
If the maneuver involved chemistry and a detector her skill bonus would be +4.
If she were mending a broken chemical detector her skill bonus would be +5.



include::ROOT:partial$CH08_Table_Mechanic_Skills.adoc[]

== Experience
Successful rolls on the performance table will earn the mechanic experience points.
How much experience depends on the DD of the accomplished task.
The mechanic will earn 80 EXPs per DD.
Mechanics can also gain a portion of combat experience.
They receive 20% of allotted combat experience.
As mechanics accumulate experience points, they may advance levels.
Higher experience levels aid the player on the performance tables and in combat.

include::ROOT:partial$CH08_Table_Mechanics_Experience.adoc[]