= Mercenary

:art: mercenaries.png
:width: 450px
:snark: High tech merc vs lo tech merc.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid rodent picking a fight with a flying rocket-laden gun toting cop in powered armour.

include::ROOT:partial$articulate.adoc[]

They are the fighters, the tough gals, and the expedition's paramilitary types.
Mercenaries are hardy, ready-to-fight sorts.
Mercs are valuable for the clutter of combat skills that they possess.
They represent the dog-meat essential for the survival of any expedition in combat. 
Mercs do not personally regard themselves as dog-meat.

== Mercenary Abilities
Abilities are maneuvers that only a mercenary can do. 

=== Bolstering Armour Rating
The mercenary can increase her armour rating, making her more difficult to damage in combat.
The mercenary increases her defence by decreasing her attack.
The player can transfer points from her bonus proficient to her armour rating.
So her chance to hit decreases but her chance to be hit decreases as well.
This trade-off can change every unit, and the player doe not need to win a performance roll.
Bolster AR is an automatic combat ability for mercenaries.

Let's consider a 3rd level merc with a BP of 158 and an AR of 620.
She could drop her BP to 98 and increase her AR to 680.

The bonus proficient use must match the attack type.
The player can use her persona's Type A BP against type A attack.
A mercenary can transfer 20 BP points to AR per EXPS level. 
The amount transferred cannot exceed the mercenary's Bonus Proficient.
The player can use only the pure combat table Bonus Proficient.
Other bonuses, like scope bonuses, do not apply.
The mercenary can use her bolstered AR against one attack per EXPS level.

=== Divided Attacks
Mercenaries can make extra attack rolls with non-powered weapons.
Non-powered weapons are thrusting and striking (type A) and non-powered missiles (type B).
Powered weapons (Type C) have a mechanical rate of fire limitation, and the divided attack ability does not apply.
Divided attacks are automatic, and the player does not make a performance roll.

The player divides her bonus proficient between the attack rolls. 
Hence the name divided attacks.
The persona gets one additional attack every two levels of experience to a maximum of 4 divided attacks per unit.
A 4th level mercenary is attacking with an axe and has a BP of 210.
She could chop once with a BP of 210 or 3 times with a BP of +70;

To maintain game efficiency, players should make their calculations in advance.

=== Ambidextrous Combat
Mercenaries can use weapons with both hands without penalty.
The player must win a performance roll or usual penalties for ambidextrous combat.
Ambidextrous combat allows the mercenary to combine any weapon types they can carry.

.Example Ambidextrous Combos
* two rifles
* pistol and sword
* two swords
* aerosol and dagger
* two grenades

Under normal circumstances, a persona suffers a severe penalty for ambidextrous combat.
The typical penalty is -200 for the dominant hand and -300 for the non-dominant hand.
If the player wins a performance roll, the mercenary does not suffer these penalties.
If they miss their performance roll, the merc will suffer -200 and -300 on the two attacks.

The DD of the performance roll is 12. 
If the player wants to combine ambidextrous combat and divided attacks, DD is 24.

==== Poly-dextrous Combat
Aliens can come with multiple attacks pre-evolved.
An alien mercenary gets the same abilities as any other mercenary.
However, mercenary abilities only apply to weapons that the alien mercenary uses, not her native attacks.
For example, an alien with two natural attacks per unit cannot use divided attacks or ambidexterity on her biological attacks. 
A mercenary alien could use her natural attacks and her weapon attacks simultaneously. 
Each alien is different, and whether her natural and weapon attacks work simultaneously must be negotiated between the referee and players.

=== Absolute Proficiency
Mercenaries are proficient in any weapon that they use.
So a mercenary using a lazer pistol she just purchased up would use her Bonus Proficient.
Absolute proficiency only works with fully identified personal weapons.
This ability does not work on unidentified artifact weapons, but the mercenary is most likely to identify a gun.
This ability does not work on weapon systems of mass destruction.

=== Snap Reload
The mercenary can reload her weapon and attack in the same unit.
Most personas would have to miss at least a combat unit to reload a weapon.
The snap reload can also be used as a snap weapon exchange.
The player must win a 6 DD performance roll to snap reload or snap change weapons.
If the mercenary is trying to snap reload during ambidextrous combat, the DD increases to 12. 
A mercenary cannot combine snap reload, ambidextrous combat and divided attacks. 
If the player loses the performance roll, the mercenary reloads like all other personas.

== Mercenary Skills
Mercenary skills are weapon and procedure-specific maneuvers.
The skills improve Performance Rolls and Attack Rolls. 
The number of start-up skills depends on the persona's intelligence score.
The player makes one roll on the table per 4 points of intelligence.
For example, a mercenary with a 12 INT would get three rolls on the Mercenary Skills Table.
The player can choose to extend an existing skill or make a new random roll for each new experience level.

.*Example Three Rolls*
* Hand-to-hand, striking
* Pistol, revolver, XLP (extra-low powered)
* Pistol, revolver, MP (medium-powered)
* Extra Roll!
* Grenades, Buildings

Mercenary skills are cumulative and separable. 
If the persona is snap reloading a bolt action rifle, she does not get a skill bonus.
When snap reloading a medium-powered (+1) revolver (+2), which is also a pistol (+2), she has a skill bonus of +5.
When assessing trench fortifications, she does not get a skill bonus.
When assessing building (+1) fortifications against grenades (+1), she has a skill bonus of +2.

.*Reorganized Skills*
* Pistol - 2
** Revolver - 2
** XLP - 1
** MP - 1
* Hand-to-hand - 1 
** Striking - 1
* Grenades - 1
** Buildings - 1

== Attack Roll Bonuses
Mercenary skills convert directly into combat skills as Attack Roll bonuses.
Each skill point adds +20 to the player's Attack Roll. 
This Attack Roll bonus increases the persona's Bonus Proficient and Maximum Roll.

When making an Attack Roll with a medium-powered (+1) revolver (+2), which is also a pistol (+2), she has a bonus of +100 (5*20).
When throwing a grenade (+1) in a building (+1), she gets an Attack Roll bonus of +40 (2*20).
When swinging a sword the which is a striking (+1) hand-to-hand (+1) weapon, she gets an Attack Roll bonus of +40 (2*20).

include::ROOT:partial$CH08_Table_Mercenary_Skills.adoc[]

include::ROOT:partial$CH08_Table_Merc_Calibre.adoc[]

include::ROOT:partial$CH08_Table_Merc_Specialization.adoc[]

== Experience
The benefits of increasing experience levels are more weapon skills and improved performance.
Mercenaries earn experience points for completing procedures rolls (25 EXPS per DD) and role-playing within their vocation.
Mercenaries gain 110% of combat EXPS earned.

include::ROOT:partial$CH08_Table_Mercenary_Experience.adoc[]

== Mercenary Maneuvers
Mercenary maneuvers are devoted to combat and harming organic and inorganic targets.
These maneuvers are all about destroy, destroy, and destroy.
All mercenary maneuvers are combat maneuvers and allow a PSTR Performance Roll bonus.

A mercenary must have a weapon to work with.
This must be an actual weapon that is not improvised from the persona's body (a fist is not a mace).
The referee may make a target roll more difficult if the mercenary does not have a weapon.

include::ROOT:partial$CH14_Table_DD_Merc.adoc[]