= Mechanic

:art: mechanic.png
:width: 250px
:snark: Mechanic mechanizing a mech.
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: 
:description: Drawing of humanoid panda with trucker hat using a wrench.

include::ROOT:partial$articulate.adoc[]

Mechanics are personas with a deep interest in the inorganic physical world's workings.
The vocation of mechanic encompasses all skills and knowledge of a technical nature, whether electronic, mechanical, structural, etc.
By definition, mechanics are handy personas.
Their skills can range from lasers to sink drains.
Unfortunately, they only have bits and bytes of rudimentary knowledge at their disposal.
Mechanics are exceptionally skilled at identifying artifacts.
This vocation is essential if the expedition expects to repair equipment or create new contraptions.

== Mechanic Abilities
Mechanic abilities focus on the inorganic world. 
The mechanic is in tune with mechanical processes and fixing and making things are their passion.
Mechanic abilities are divided into crafts (gifts) that allow the persona to automatically complete mechanical tasks.
Crafts are the inherent abilities that help define the persona as a mechanic.
Mechanics also have areas of interest and specific skills based on the those interests. 
While the player can mix and match interests and skills, crafts are hardwired and can only be acquired level progression.

=== Mechanic Crafts
A mechanic's crafts (gifts) define the persona as a mechanic. 
Crafts are the inherent abilities that reflect how the persona is in tune with the organic world. 
Crafts cannot be chosen, and are added as the persona increases in experience levels.

include::ROOT:partial$CH08_Table_Mechanic_Crafts.adoc[]

=== Mechanic Interests
Interests are broad approaches to the mechanical world that improve the chance of success when making task rolls.
An interest in repair will help the player win any task roll that involves repair.
If the mechanic is trying to make a better mousetrap she would benefit from the enhance interest.
When building something that doesn't exist, or when trying to combine equipment a research interest is key. 

At startup, the persona gets one interest per three points of intelligence score.
A persona with a 12 INT would get three rolls on the Mechanic Interest Table. 
After startup the persona earns another interest with each new experience level.
The player can choose to roll on the Mechanic Interest Table, or choose a specific interest

include::ROOT:partial$CH08_Table_Mechanic_Interests.adoc[]

==== Repair Interest
The repair interest assists the mechanic in any task that is returning a mechanism to it's undamaged state.
Maintenance of artifacts and toys is also assisted by the repair interest.
By and large a mechanic cannot repair an object that is destroyed. 
The persona could salvage parts from a destroyed object

==== Enhance Interest
The enhance interest assists the mechanic in any task where they are improving and existing artifact or toy.
For example, improving the range of a crossbow falls under the enhance interest. 
However if that crossbow is broken, the enhance interest does not benefit the task roll. 
Enhancement does not include miniturization. 

==== Research Interest
The research interest is used to push the boundaries of engineering, fabrication, physics, and sciency fiction.
The persona can use the research interest to create a new machine, or process. 
THe research interest can also be used to make toy smaller, or to combine two toys together.


=== Mechanic Skills
Mechanic skills are more specific areas of expertise, knowledge or aptitude. 
The skills can represent tasks or very focused processes. 
The player can stack skills and interests 

At startup the player gets one skill per interest. 
So a mechanic with repair 2 and enhance 1 would get 3 rolls on the mechanic skills table.
After start up the persona gets one new interest per new experience level. 
As described above the player can roll or choose the new interest.
Each new interest includes a new skill.
The player can choose or roll the new skill.  

include::ROOT:partial$CH08_Table_Mechanic_Skills.adoc[]

== Organizing Mechanic Abilities

.Example Mechanic Skill List
* Repair 2
* Enhance 1
* Chemistry 3
* Detectors 1
* Mending 1

Mechanic skills and interests are cumulative and combinable.
A task that involved improving a hover car lubricant  the mechanic a task roll bonus of +4 (Chemistry 3 and Enhance 1)
If the task involved chemistry and detectors, her task roll bonus would be at least +4.
If she were mending a broken chemical detector, her task roll bonus would be +6 (Chemistry 3, Repair 2, Mending 1).

== Skill Explanations
For some reason there is a lot of detail available regarding mechanic abilities. 
This is probably due to game play edge cases encountered running previous mechanic personas. 

=== Mnemonic Trapping 
Mnemonic trapping allows the mechanic to memorize crucial technical information. 
A mechanic can mnemonically trap dimensions, instructions, serial numbers, or other technical information. 
To memorize important information, the player must win a task roll.
The degree of difficulty (DD) of the task roll increases with the information's amount and complexity.
None technical information like people's names or anniversaries is even more difficult to mnemonically trap.
This ability's typical DD range is 1-8 (1d8).

=== Brainstorming
This ability allows the mechanic to solve complex problems by thinking laterally and thinking imaginatively.
Using brainstorming can solve a problem completely, partially, or not at all.
If the brainstorming attempt fails, the persona will most likely postulate a hair-brained idea instead of no idea.
The difficulty (DD) of the task roll increases with the complexity of the mechanical problem.
Plot points and interpersonal problems are resistant to Brainstorming. 
This ability's typical DD range is 1-20 (1d20).

=== Mental Patenting
The mechanic can memorize a maneuver that she has successfully completed.
Mental patenting allows the mechanic to repeat the maneuver flawlessly.
If the mechanic is upgrading ammo for a mercenary repeatedly, she may want to mentally patent the procedure.
Successful mental patenting will allow her to upgrade the ammo flawlessly in the future.
Mental patented maneuvers do not work with research teams.
Mental patented maneuvers do not earn experience points.
This ability's degree of difficulty is three times the maneuver DD.
To mentally patent a 4DD maneuver requires a DD12 task roll.

// for use in task tables
// tag::mechanic_maneuvers[]

== Mechanic Tasks
Mechanic tasks involve anything inorganic or mechanical in nature.
These tasks are all about fixing, modifying and creating mechanical devices.
Most mechanic tasks are knowledge based and dexterity based task roll bonuses will reflect this.

A mechanic must have a tool to work with. 
This can be any kind of tool that is not improvised from the persona's body (slap does not equal hammer).
The referee may increase any target if the mechanic does not have a tool.

include::ROOT:partial$CH14_Table_DD_Mech.adoc[]

// end::mechanic_maneuvers[]

== Experience
The benefits of increasing experience levels are more skills, improved task roll success, and somewhat better combat skills. Mechanics earn experience points for completing procedures rolls (80 EXPS per DD) and role-playing within their vocation. Only 20% of combat experience can go towards a mechanic's experience point total.

include::ROOT:partial$CH08_Table_Mechanics_Experience.adoc[]


