= Knite 

:art: reptilian.png
:width: 250px
:snark: Kneed deep in trouble
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Knites are hybrids of the mystical and the military.
Knites are cerebral warriors that are as likely to overpower someone with their will as with raw force.
A knite fights in the physical space and the think space at the same time.
The knites are psionically aware personae.
They communicate with the thinkspace through sciency fiction kirlian auras that the manipulate.
They can use their physical strength and mental strength simultaneously.
They have no adverse disposition towards using technological weapons but knites feel most comfortable wielding their trademark energy sword.

== Mythos of the Knite
Most referees will want to create their own mythos around such a powerful vocation.
The vocation is divided into two separate sects that are as different as dark and light.\
These two sects are knites and anti-knites.
Some form of combat is the only possible outcome of a Knite Anti-knite encounter.

=== Knites
Knites support compassion, goodwill, honesty, and humanity.
Knites battle against injustice, intolerance, and enslavement.
They will err on the side good at every opportunity of every possible opportunity.
Knites are not pacifists.
This is a combat vocation and will deliver fatal justice without a second thought.

Knites tend to go off on "damn fool quests".
Knites cannot ignore injustices carried out by fellow personas.
A knite is a powerful ally in combat but will hinder an expeditions nefarious objectives.

=== Anti-Knites
Anti-knites are the enemies of goodwill, humanity, and organized civilizations.
Anti-knites are anti-everything.
An anti-knite is devoted to to the spreading of chaos and entropy.
Anti-knites are not played as malicious, off-the-wall anarchists.
They can be systematic, ruthless, and calculating nihilists.

Anti-knites will dismiss any persona less powerful than themselves.
Anti-knites will betray their fellow personas the moment their usefulness has ended.
If an expedition is working with an anti-knite backs are just waiting to get stabbed.

== Vocation Requirements
The knite vocation is powerful and complex.
Knites are rare and it is difficult for a persona to pursue this vocation.
The persona must have the required attributes and complete referee assigned tasks.
These tasks are assigned once the player decides to pursue the knite vocation.
Any persona who has the requisite attributes may announce her desire to pursue knite hood.
This intent may be secretly communicated to the referee or announced to the entire expedition.

If a persona should happen to lose the required MSTR of 18 she will also lose vocation skills.

=== Trial Vocation
The persona must survive one experience level in a trial vocation.
Trial vocations can be mercenary, nomad or nothing.
It is the persona's actions during this trial period that determines her sect.
The righteous will likely become knites, and the ruthless anti-knites.

The referee may even pit the persona against specific tasks during this trial experience level.
These trials could be orchestrated by a more powerful knite or anti-knite.
Both sects will endeavour to enlist potential recruits into their devotions.
Carrying out a despicable or gallant act may be sufficient to ascend to knite hood.
Slaughtering an unsuspecting expedition member or killing a knite is usually good (bad) enough to become an Anti-knite.
Attempting to rescue other personas, even evil ones, at personal risk may be sufficient to become a knite.
If the persona has acted accordingly during her trial period, she may ascend into knite hood without her knowledge.

When the persona becomes a knite she restarts her EXPS total at zero.

== Vocation Operation
Simply put knites must behave and anti-knites must misbehave.
If members of either sect fail to act according to their doctrine there will be trouble.
Initially the personas will fail to collect experience.
Persistent or serious transgressions may get the persona expunged from her sect.
The persona may simply lose her connection to the thinkspace and lose her vocation skills.

The good versus evil element of the two sects lends itself to built in storytelling.
Anti-knites are always prowling around in the dark waiting for knites to falter.
If a knite is losing her way it is certain that an anti-knite will have a cunning plan waiting.
If an anti-knite shows weakness she will certainly be done in by another anti-knite or her underlings.

=== Switching Sects
A persona may leave her vocation sect through death or decay.
A knite can become an anti-knite.
Falling to the dark side of the sect.
An anti-knite can only leave the vocation by death.
In short a knite can become an anti-knite and an anti-knite can die.

Anti-knites can only become knites if they elect to do so on their deathbed.
Therefore an anti-knite persona will never get the opportunity to be a knite.

=== Vocation and Death
Any persona that dies while in the knite vocation cannot be revived. 
If a knite is dead for even an instant her kirlian force is drained and they move on.
The knite is irretrievably dead to any form of technological or biological method of restoration.
Dead knites can impart their will on the physical space. 
They can appear as shadowy immaterial entities which aid the ever-endangered forces of good.
Anti-knites do not remain in the physical space.
Anti-knites are trapped in an eternal state of pain in the thinkspace.

== Knite Abilities
The basis of the vocation's skills result from the psionic manipulations of the kirlian auras that penetrate the physical space.
Kirlian auras are a sciency fiction vehicle to explain the powers of knites.
The referee and players may choose to base these powers on some other invisible force.
The kirlian auras are psi-luminescent fields that yield  information about the object or creature that it surrounds.
The kirlian auras of sentient beings are constantly changing depending on their mood, intent, and general outlook on life.
The more powerful a knite, the better they can interpret the auras and the better they can manipulate them.

All of a knite's skills are present at first level but their degree of clarity and refinement (which determines their chance of success), depends on the experience level of the persona.
Although a knite may attempt to use any ability at any time, the chance for success depends on the knite's experience level.

The player must make a successful performance roll to have the skill work as expected.
The knite must be present for the skill to work.
Kirlian auras cannot be manipulated through inorganic media like monitors or cameras.

=== Kirlian Sight (Automatic)
The glowing, flickering kirlian auras allow the knite to maneuver easily in darkness.
Kirlian sight has a range of 1 hex per point of adjusted MSTR (MSTR plus level).

Knites can use their kirlian sight to detect hidden objects.
Different types of material or layers of paint can be visible to kirlian sight.
When searching with their kirlian sight the knite uses her MSTR for search success.

=== Mimic (1d4 DD)
A knite can reproduce a sound so well that it will even carry the emotional aspects it carried.
To repeat the sound the player must make a successful performance roll.
A second successful performance roll will allow her to memorize the sound for later use.
Mimicked sounds can have any effect except physical damage.

=== Induce Silence (1d4 DD)
A successful performance roll will suffuse the knite in silence.
A performance roll must be made every five units (10 seconds) to continue the silence.
Sound cannot exit or enter the area of induced silence.
The knite can operate in silence but she cannot hear any sounds .
The louder the noise the harder it should be to hide it.

=== False Rest (1d4 DD)
A successful performance roll will allow the knite to see with her eyes closed.
This is an extension of kirlian sight, but it requires a performance roll.

=== Defense Shield (varies)
A defence shield can only be used against projectile attacks directed from the front.
The defense shield can be erected as soon as the knite can outstretch both palms in a defensive gesture.
A defense shield can usually be erected before any attack can be launched.
If there is some debate about getting the defense shield ready, the knite may be forced to make an initiative roll using her MSTR.
If the knite's arms are bound behind her back, she can create a defense shield with her feet at double the degree of difficulty.

A successful performance roll will allow the knite to deflect some attacks and absorb damage from those that are not deflected.
Defense shield allows the knite to absorb 5 hit points of damage and increase her AR by 30 per experience level.
A 3rd level knite could absorb 15 HPS of damage from those attacks that penetrated her increased AR (+90).
If the player fails the performance roll, her persona will take full damage if a hit is scored.

=== Pre-empting (special)
This ability allows the knite to put words into the mouths of other personas.
A successful performance roll may cause the victim to repeat what the knite has spoken.
The victim receives a saving roll.
If the target fails to save, she will repeat what the knite has said (or thought).
This is not mind control and the target may not carry out the action.
Pre-empting can only hope to succeed if the knite can speak the same language as the victim.
There is a much better chance of success if the knite speaks the words aloud.

=== Telekinesis (1d6 DD)
A successful performance roll will allow the knite to move an object by mental concentration.
The range is equal to the knite's adjusted MSTR in hexes.
Inanimate objects are automatically subject to telekinesis. 
Robots are unaffected by psionic attacks.
Unwilling targets get a saving roll to avoid telekinesis.
A large target can be slowly moved around. 
Small targets can be flung like type B weapons. 

==== Maximum Wate
The maximum wate is determined on the Wate Allowance table using the persona's MSTR.
This psionic WA is multiplied by one-half of the knite's experience level.
So a knite with a 20 MSTR can telekinese 17 kg at 1st level, and 34 kg at 4th level.
The referee can always adjust the DD under special circumstances.

The persona can telekinese 1 target per 3 EXPS levels. 
A 6th level knite with MSTR 20 could telekinese 3 objects. 
The total wate cannot exceed her wate allowance (51 kg).
Each target requires an additional performance roll.

=== Pressure (DD7)
Pressure fills the target with an overwhelming emotion.
A knite can employ pressure to instill incapacitating guilt.
Anti-knites can employ pressure to instill asphyxiating fear.
Either format immobilizes its victim.
The target is incapacitated if she fails her saving roll.
The pressure must be reapplied every 5 units (10 seconds).
A knite can pressure 1 target per 3 levels of experience.

=== Psionic Defense (DD4)
Psionic defence allow the knite to harden her think space against mental attacks.
A successful saving roll will block any psionic or mental attack on the persona.
The trance like state blocks other knite attacks mental mutations.
While in this psionic fortress the knite cannot use her psionic skills to attack.
This includes detections, pressure, telekinesis, kirlian site or special attacks.
A performance roll is required for each attack made on the knite.

=== Detections
The knite can attempt to read kirlian auras in her immediate surroundings.
Successful performance rolls will provide the knite with some information but failed rolls will reveal nothing more than the typical kirlian jumble.

==== Danger (1d6+4 DD)
When being actively employed by the knite, a successful performance roll will indicate to the knite the location and possibility of impending danger.

==== Intent (1d6+8 DD)
The knite may use this ability to determine the intent of any organic entity.
Detecting intent reveals good or bad intent and does not reveal a plan. 

==== Lies (1d6+11 DD)
When a knite is actively observing a creature, she can determine if the spoken dialogue is truthful or not.
The kirlian auras of machines or robots cannot be read for truthfulness.

==== Life (1d6+12 DD)
Knites, but not anti-knites, may detect life.
Anti-knites, but not knites, may  detect death.
The range of up to 5 hexes per point of adjusted MSTR.

==== Fate (1d6+14 DD)
A successful roll gives some general information about the fate of another persona.
This is an skill for personas involved in campaigns of truly epic proportions.
The referee and players must work together to fulfill successful predetermined fates.

== Energy Sword Skills
The knite's special weapon is her energy sword.
The energy sword can be a force field sword, laser sword, or lite saber.
The knite can do certain things with her energy sword that no other persona can.
All energy sword abilities can be used simultaneously.

=== Deflections (Special)
The energy sword can be used to deflect an attack.
The DD for this action is 1/50 of the attack roll made on her.
Attacks can be deflected without affecting the knite's combat in any way.
Attacks can be deflected from any direction provided that the knite hasn't been ambushed.
The knite can deflect two attacks per unit per experience level.
Thus a 4th level knite could deflect 8 attacks per unit and she need only deflect those attacks which are going to hit her.

=== Multiple Attacks (Automatic)
A knite can attack more than once per unit with her energy sword.
She can make one extra attack per unit per two levels of experience.
This only works with her personal energy sword.
The maximum number of attacks cannot exceed 3 per unit.

=== Amputation (Special)
The most devastating skill that the knite can wield is amputation.
The energy sword is capable of excising any limb that it hits.
The chance of amputation depends on the damage inflicted.
There is a base percent chance depending on the damage inflicted.
So hitting a target with 15 HPS in damage has a 15% chance of amputation.
If the direct percent chance is unsuccessful the knite can use her kirlian forces to amputate.
The knite must make a performance roll against a DD equal to 1/50 the target's AR.
Thus knites get 2 chances to amputate each time they score a hit with a energy sword.

== Knite Experience
Knites earn 20 EXPS per DD for successful completion of skills on the performance table.
Knites gain full experience for combat.
The more experience points that the knite collects, the higher the experience level that is attained.
The gathering of experience levels allows for more refined interpretations and manipulations of kirlian auras and thus a higher proficiency with the knite skills.

include::ROOT:partial$CH08_Table_Knite_Experience.adoc[]
