= Vocations

[quote]
____
*An aptitude and desire beyond training.*
____

:art: hitcher_space.png
:width: 450px
:snark: 9 to 5 and 0g.
:artist: Studiostoks
:date: 2017
:license: Copyright 2017 Studiostoks
:description: Drawing of space suited humanoid carrying briefcase and thumb up for a ride in outer space. 


include::ROOT:partial$articulate.adoc[]

A vocation is more of an attitude than a profession.
Choosing a vocation in EXP does not mean that the persona has had any special training.
There are no diplomas or degrees granted by professional institutions.
The information and skills that the persona can utilize have been self-taught.
This lack of unified training leaves many gaps in their knowledge.
These training gaps lead to frequent failures of seemingly easy procedures.

NOTE: *Vocations were called classes in previous versions of EXP*

Even in the face of what appears to be continual failure, a persona will still pursue her vocation.
The vocation represents innate abilities, desire, and personal interest.
A mechanic doesn't have an anti-grav maintenance diploma.
A mechanic persona does have a keen sense for interpreting the physical world.
The mechanic is more like a ms fix-it, or a bicycle repair person.
A biologist wouldn't have a B.Sc from in clone development.
A biologist has an intuitive sense for observing the organic world.
The bilogist is more like a gardener, a farmer or an environmentalist.
All of the vocations are designed in this fashion.
The vocations are a natural aptitude which is backed up by sparse bits of disorganized information.

== Robot Vocations
Robots do not have vocations.
Robots are vocations.
During fabrication the player chooses a type-vocation 
A transport robot's vocation is driving.
An exploration robot's vocation is exploring.
A robot's dedication to it's type-vocation is baked in and much stronger than any other persona's.

It is possible for a robot to have a typical vocation. 
For example, veterinarian and maintenance robots have a vocation baked in. 
There are also some peripherals that allow a robot to pursue a vocation. 
In these circumstances attribute minimums do not apply and the vocation is programmed in.

== Alien Vocations
Aliens do not have vocations.
An alien can be evolved to have language, and tool using but not have a vocation.
A vocation is the highest level of social evolution for an alien species.
An alien's society must have language, culture and education before vocations.
An alien has about a 1/1000 chance of having vocations.
If an alien species has vocations the player comes here to choose one.

WARNING: *Aliens with vocations are extremely powerful and ruin game balance permanently*

== Vocation Selection
The persona's attributes determine her vocation.
The attribute minimums for vocations are present to maintain game balance.
For example, vets need charisma, spies need dexterity and mercenaries need hit points.
The attribute must have a value equal to or greater than on the Vocation Attributes below.
For example, a biologist must have a combined AWE and INT greater or equal to 18.
A persona with a 4 INT and a 14 AWE can choose biologist.
Usually a player will have a list of vocations to choose from. 

include::ROOT:partial$CH08_Table_Persona_Class_Requirements.adoc[]

=== Vocation Selection Example
A persona has the attributes: AWE 6, CHA 15, CON 17, DEX 9, INT 14, MSTR 12, PSTR 6, and HPS 42.
The player has a wide selection of vocations to choose from.
This persona could be any of the following: biologist, mechanic, mercenary, nothing, or veterinarian.

include::ROOT:partial$CH08_Table_Persona_Vocation_Example.adoc[]

== Vocations and Role-Playing
The persona should have at least a keen interest, or possibly an obsession, with her vocation.
Veterinarians should show compassion and a desire to heal.
Biologists should show respect, if not awe, for the natural organic world.
Anti-knites should take on any opportunity to increase the universe's level of entropy.

Players that do not role-play their persona's vocation should face challenges.
Villainous veterinarians and altruistic anti-knites may see their skills weaken.
Initially the personas will lose out on key vocation related experience points.
Worsening transgressions may lead to punitive actions.
Murdering veterinarians may find that their skills don't work on those who know the truth.
Nomads living in decadent luxury will find their survival skills starting to rust.
In rare cases the persona's may find themselves at odds with organizations that informally police them.

If a campaign requires every persona to be a mercenary then so be it.
If the ref hand players have a system of colleges and training centers all the better.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Vocation Concentration
A vocation is a gross generalization of someone that is able to perform a group of procedures.
Each vocation represents a collection of skills that are similar enough for one persona.
These skill collections are represented by eight separate vocations.
If the ref and players prefer a more varied collection of vocations performance rolls can handle this.

== One Is Not Enough
There are situations where the ref and players may allow for a persona to have more then one vocation.
A player may wish to change up the player of persona.
The expedition may need a certain vocation and a player wants to cross train her persona.
For instance, a mercenary mechanic could be effective in combat and also engage in artifact identification without risking the entire expedition.
Multi-vocation personas are not recommended for inexperienced players or referees.
Mixing vocations is challenging to play and keep track of.
I can see no situation where a player could manage more than two vocations 

=== Combined
The persona carries two vocations at the same time.
The player runs two _different_ vocations from a persona at once.
For example, a persona could make performance rolls as a vet or merc.
The amount of experience required for each new level will be equal to the sum of both vocations plus 10% of the total.
So a combined knite-biologist would need 4675 EXPS for 2nd level.
Lastly, nothings can be combined with no vocations and knites cannot be combined with anti-knites.
The referee is completely in control of what combined vocations are appropriate for her milieu.

=== Switching
Switching vocations is different from combined vocations in that the persona neglects one vocation and begins to start fresh with another.
For example, a mercenary may suddenly get a conscience and devote the rest of her life to the study of biology.
If she has the appropriate attributes, this switch can be done at any time.
The new vocation is started at zero EXPS and advances in levels and EXPS acquisition as the new vocation.
The mercenary skills can still be called on but no experience will be earned for their use.
If the personal does not have the attributes to make a desired switch, she must pursue it through the nothing vocation.

== Attributes and Play
Personas that lose attribute points during the generation of mutations or the choosing of a family and consequently cannot pursue a vocation that they desire are out of luck.
Players are welcome to plan ahead and choose a family that will allow them to be a certain vocation but once the path has been chosen, there should be no turning back.
Personas cannot be ejected from a vocation for attribute alterations that occur during the play of the campaign.
For instance, a veterinarian would not have to retire from that vocation because her CHA was reduced due to a facial scar.