= Biologist

:art: biologist.png
:width: 250px
:snark: Watching a biologist watch
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a woman wearing a pith helmet using binoculars and a computer in the jungle. 

include::ROOT:partial$articulate.adoc[]

Biologists are personas with a deep interest in the organic physical world's workings.
A biologist has broad interests in taxonomy, culture and research.
Their interests range from creepy crawly bugs to complicated economic systems. 
The vocation is broad as the organic world. 
Biologists are more interested in studying the organic world than repairing the organic world.
Biologists are more interested in organic systems than mechanical systems.
Vets, mechanics and biologists work well on research teams together. 

Biologists do not have degrees or diplomas or certificates from training programs.
They are self-taught, and their knowledge base is haphazard.
Their knowledge comes from keen observation, gardening books, environmental leaflets, nature shows, sagely advisors, and personal experience.

== Biologist Abilities
The biologist's abilities cover all aspects of the organic world.
Anything to do with organic life, anthros and aliens, falls under her purvey. 
This includes the observation, discovery, and identification of aliens. 
Biology covers the knowledge spheres of sociology, ecology, culture studies, and more.
A biologist's abilities do not include robots (mechanic) or organic repairs (veterinarian). 
However a biologist could take skills from the mechanic or veterinarian vocation.

Biologist abilties are divided into knacks (gifts), interests, and skills.

=== Knacks 
Biologist knacks (gifts) are the hard wired abilities that probably lead to the persona pursuing the biologist vocation. The biologist starts with the first knack and gets a new one every three EXPS levels.
Knacks are not transferrable between vocations and a player cannot choose a knack.

include::ROOT:partial$CH08_Table_Biologist_Knacks.adoc[]

=== Interests
Biologist interests are broad areas that cover a swath of the organic world.
The interests are: Culture, Research and Taxonomy.
Any task that falls under an interest gets the interest bonus on the task roll.
The Culture interest could help with a linguistic task.
The Research interest could help with a laboratory task.
The Taxonomy interest could help with an alien identification task.

At startup, the persona gets one interest per three points of intelligence score.
A persona with a 12 INT would get three rolls on the Biologist Interest Table. 
After startup the persona earns another interest with each new experience level.
The player can choose to roll on the Biologist Interest Table, or choose a specific interest

include::ROOT:partial$CH08_Table_Biologist_Skill_Stream.adoc[]

Each interest has an associated group of skills.
At startup the player gets one skill per interest.
After startup the player may roll a new skill on the appropriate table or choose a specific skill.

==== Taxonomy Interest
Taxonomy is about identifying and categorizing organic species.
The taxonomy interest is the classical biologist as a naturalist.
Skills like identifying burrowers in toxic biomes or carnivores in the ocean fall under taxonomy.
Mere categorization of finches on remote islands has changed society.

==== Research Interest
The research interest includes laboratory, invention and extension interests for the biologist.
Skills like cloning, immunology, and antitoxin creation are found under the research interest

==== Culture Interest
The culture interest involves interaction of a population.
Skills like languages, family structures, and political nuance are found under the culture interest.

=== Skills
Skills (previously called foci) appear as specific tasks, but have a wider impact on task rolls.
A skill in aging could be used to assist a task roll for determining a persona's, age or understand the implications of a chronovirus.

Biologist skills are grouped by interest.
A taxonomy interest could come with skills like: burrowers, hivers or herbivores.
A culture interest could come with skills like: language, religion or politics 
The interest and skill abilities are cumulative.

At startup the player gets one skill per interest. 
So a biologist with taxonomy 2 and culture 1 would get 2 rolls on the taxonomy skills and 1 roll on the culture skills.
After start up the persona gets one new interest per new experience level. 
As described above the player can roll or choose the new interest.
Each new interest includes a new skill.
The player can choose or roll the new skill.  

==== Culture Skills
Culture skills are about understanding the interactions of groups of organic life forms. 
These skills can be used to predict what a pack of aliens might do, or try and predict an election.

include::ROOT:partial$CH08_Table_Biologist_Cultural_Stream.adoc[]

==== Research Skills
Research skills are about understanding the ways of studying the organic world.
These skills can be used to make an antivenom, clone an alien, or enhance a mutation.

include::ROOT:partial$CH08_Table_Biologist_Research_Stream.adoc[]

==== Taxonomy Skills
Taxonomy is about identifying and categorizing organic species.
Each skill includes a skills and a biome type. 
A taxonomy skill could look like this: Taxonomy - Herbivore - Desert Biome.

include::ROOT:partial$CH08_Table_Biologist_Taxonomy_Stream.adoc[]

include::ROOT:partial$CH08_Table_Nomadic_Biome.adoc[]

include::ROOT:partial$CH08_Table_Biome_Characteristic.adoc[]

NOTE: Skills help the biologist win a task roll. A skill is not required to attempt a task.

== Optimizing the Abilities
A biologist can rack up a lot of abilities.
What follows is a way to keep track of them. 

:art: biologist_footprint_symbol.png
:width: 350px
:snark: Footprint? Language? Bad Map?
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Mystical connected semi-circles scratched into ground.

include::ROOT:partial$articulate.adoc[]

.*Example Three Rolls At Startup*
. Taxonomy interest
** Herbivores, Desert Biome skill
. Taxonomy interest
** Detritivores, Desert Biome skill
. Culture interest
** Languages, Verbal skill

Interests and skills are cumulative and separated.
The persona has two taxonomy interest, and the player can use them on any task related to taxonomy.
Even if the persona has no chaser/hunter behaviour skills, she will use taxonomy 2 when working on a chaser/hunter behaviour.
When figuring out something about herbivores, she will get a total bonus of 3 (taxonomy 2 and herbivore 1).
When studying a herbivore in a desert biome, she will get a total bonus of 5  (taxonomy 2, herbivore 1 and desert biome 2).

.*Reorganized abilities*
* Taxonomy - 2 
** Desert Biome - 2
** Herbivores - 1
** Detritivores - 1
* Culture - 1
** Languages, Verbal - 1

== Biologist Tasks
Biologist tasks involve anything organic that does not involve healing.
Most biologist tasks are knowledge based unless an obvious physical intervention is involved.
The minimal equipment required by a biologist is her notebooks. 
The referee may make a target roll more difficult if the biologist does not have her notebooks.

include::ROOT:partial$CH14_Table_DD_Biologist.adoc[]

NOTE: the author has no idea why there are two separate tables


// for use in task tables
// tag::biologist_maneuvers[]


include::ROOT:partial$CH08_Vocations_Biologist_Ex_Procs.adoc[]

// end::biologist_maneuvers[]

== Biologist EXPS
The benefits of increasing experience levels are more skills, improved task success, and marginally better combat skills.
Biologists earn experience points for completing procedures and role-playing within their vocation.
Only 20% of combat experience can go towards a biologist's experience point total.

include::ROOT:partial$CH08_Table_Biologist_Experience_Points.adoc[]
