= Biologist

:art: biologist.png
:width: 250px
:snark: Watching a biologist watch
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of woman wearing pith helmet using binoculars and computer in the jungle. 

include::ROOT:partial$articulate.adoc[]

Biologists are personas which have deep interest in the workings of the organic physical world.
A biologist has broad interests in the fields of taxonomy, culture and research.
Their interests range from creepy crawly bugs to complicated economic systems. 
The vocation is broad as the organic world. 
Biologists are more interested in studying the organic world than healing (veterinarians) it.
Biologists have more interest in organic physiology than inorganic (mechanics) mechanisms.
Vets, mechs and biologists work well on research teams together. 

Biologists do not have degrees or diplomas or certificates from training programs.
They are self taught and their knowledge base is haphazard.
Their knowledge comes from keen observation, gardening books, environmental leaflets, nature shows, sagely advisors, and similar random sources.

== Biologist Skills 
The biologist areas of interest are labeled as skills. 
The biologist begins with several skills that assist her in the field.
The player gets one roll per 4 points of INT score.
So a persona with a 12 INT would get three rolls on the Biologist Skill Stream Table. 
Another roll is made for each new experience level.

The skill streams are broad.
Any organic biological procedure will enjoy a bonus on the performance roll.
For example, the Taxonomy Stream will help with any alien identification procedures.
The Cultural Stream will help with any language related procedures.
The Research Stream would help with understanding any laboratory experiments.

Each skill stream indicates another roll on a more specific area of interest within the stream.
The Taxonomy Skill Stream could focused on Herbivores in Desert Biome. 
The persona's skills would be recorded as Taxonomy 1, Herbivores 1, Desert Biome 1.
Her second roll is Taxonomy focused on detritovores in Desert Biomes
The persona's skills would be recorded as Taxonomy 2, Herbivores 1, Detritovores 1, Desert Biome 2.
Her third roll is Cultural Verbal Languages.
Her skill list at first level would be:

.Example First Level Skill List
* Taxonomy 2
* Desert Biome 2
* Herbivores 1
* Detritovores 1
* Cultural 1
* Languages Verbal 1

Skills are cumulative and separated.
Each part of the skill descriptor counts as one skill level and they can be mixed and matched.
This biologist trying to identify a Desert Biome Detritovore would have a skill bonus of 5.
This biologist trying to decode a herbivore's verbal language would have a skill bonus of 3. 
This biologist trying to measure toxicity on a lab bench would have a skill bonus of 0.

include::ROOT:partial$CH08_Table_Biologist_Skill_Stream.adoc[]

=== Taxonomy Stream
Taxonomy is about identifying and categorizing organic species.
This is the classic naturalist bent of the biologist.
Identifying finches on remote islands can upturn a whole society.
Each Taxonomy Stream sub skill also includes a biome sub skill as well. 
So a Taxonomy Stream roll would sound like this: Taxonomy - Herbivore - Desert Biome.

include::ROOT:partial$CH08_Table_Biologist_Taxonomy_Stream.adoc[]

include::ROOT:partial$CH08_Table_Nomadic_Biome.adoc[]

=== Research Stream
Research is lab and study work.
It includes dissections, figuring of physiology, understanding cross taxonomy processes.

include::ROOT:partial$CH08_Table_Biologist_Research_Stream.adoc[]

=== Cultural Stream
The cultural stream is the population observation stream of the biologist.
The cultural stream is most like sociology, economics, anthropology, linguistics etc. 

include::ROOT:partial$CH08_Table_Biologist_Cultural_Stream.adoc[]

== Biologist Performance Rolls 
Performance rolls are made every time the biologist attempts a procedure.
An example procedure could be to identify if an alien is poisonous.
The procedure is assigned a degree of difficulty (DD).
The chance of success is improved the more skills the biologist can use in the performance roll.
Many more details are available in the section xref:i-roll_playing_rules:CH14_Performance_Tables.adoc[Performance Rolls].

include::ROOT:partial$CH08_Vocations_Biologist_Ex_Procs.adoc[]

== Biologist EXPS
The benefits of increasing experience levels are: more skills, increased performance, and marginally better combat skills.
Biologists earn experience points for successfully completing PT rolls (90 EXPS per DD).
Only 20% of combat experience can go towards a biologist's experience point total.
If a biologist is consistently destroying potential specimens, the ref may forfeit combat experience altogether.

include::ROOT:partial$CH08_Table_Biologist_Experience_Points.adoc[]
