= Spie

:art: spie.png
:width: 250px
:snark: Safe working environment.
:artist: Michael Jackson
:date: 1992
:license: CC BY-SA 4.0
:description: Drawing of a humanoid warthog picking the lock on a wall safe. 

include::ROOT:partial$articulate.adoc[]

A spie is a tough, mean, and ruthless vocation.
Spies are highly skilled in unarmed combat, deception, and assassination.
Spies can employ any combination of these abilities to satisfy their goals.
A spie is not a psychopath by nature. 
There is no moral code for spies, and they can be on the side of good, evil or both.
It is hard to distinguish the bad from the not-so-bad in the realm of violent espionage.

Spies are an excellent source of dangerous assignments (from governments, corporations, societies or private citizens).
Spies are not dependent on a commission and may carry out a little extortion or kidnapping for their profit (or fun).
Spies are often members of secret guilds or naughty lodges dedicated to the clandestine arts.
How deeply involved the expedition gets with a spie's source depends on the ref's milieu or scenario set up.


== Spie Abilities
Spies have a collection of tricks (gifts), interests and skills. 
Spie tricks are baked in abilities of a spie persona. 
The spie gets new tricks with new levels.
Interests are broad areas of interest.
For example, an interest in infiltration would help the player making and infiltration related task rolls.
The interest of incapacitation will assist whenever the spie is trying to incapacitate a target.
Skills are much more specific and indicate either a focus of knowledge or a maneuver. 

=== Spie Tricks
The spie tricks (gifts) are those abilities that help define the persona as a spie. 
No other vocation has access to these abilities.
Spie tricks are baked in and not trained. 
The spie gets tricks at 1st, 4th and 7th level.

include::ROOT:partial$CH08_Table_Spie_Tricks.adoc[]

=== Spie Interests
Interests are broad areas of interest that the spie has aptitude in.
The interests are infiltration, deception and destruction.
Any task that the persona pursues that involves sneaking would benefit from the infiltration interest.
The destruction interest supports any task that involve weapons or an  unwilling increase in entropy.

include::ROOT:partial$CH08_Table_Spie_Interests.adoc[]

=== Spie Skills
Spie skills are specific tasks, knowledge foci, or maneuvers that the spie can call upon to complete tasks. 
The spie skills are divided up by their interests, and there is a skill table for infiltration, deception and destruction.

==== Infiltration Skills
Getting into where one should not be skills. 
These skills do not involve face to face deception, but deception of architecture and security systems.
The player makes one roll per infiltration interest. 

include::ROOT:partial$CH08_Table_Spie_Infiltration_Skills.adoc[]

==== Deception Skills
These are skills for face to face trickery and shenanigans deception and manipulation. 
The player makes one roll per deception interest.

include::ROOT:partial$CH08_Table_Spie_Deception_Skills.adoc[]

==== Destruction Skills
These skills focus on combat and mayhem.
The spie can gather skills with particular weapon types, and field skills. 
The player makes one roll per deception interest.

include::ROOT:partial$CH08_Table_Spie_Destruction_Skills.adoc[]

== Spie Skill and Task Descriptions
Limitations and expectations of various spie tasks. 

Assassination::
Assassination allows the spie to instantly and irrevocably kill a target with a single attack.
Under certain conditions, with the correct weaponry, a spie may carry out an assassination.
There are lots of required conditions for an assassination.
Assassination requires knowledge of the target's anatomy.
Whether a spie can assassinate robots and aliens is up to the referee. 

.*Assassination Checklist*
. Win an ambush
. Win an attack roll
. Win a performance roll
. Using an appropriate weapon

If the player fulfills these four requirements, the target is irrevocably dead.
Medical science cannot medically repair the victim.

The spie must have complete surprise through a successful ambush.
For more information about surprise jump to xref:i-roll_playing_rules:CH34_Ambush.adoc[Ambush,window=_blank].
An assassination cannot happen during combat or when the target is in a hyper-aware state.

There will be attack roll bonuses with a successful ambush. 
The player must win an attack roll before making the assassination performance roll.

The spie must be using a controllable weapon like a sword, pistol or rifle. 
Area of effect weapons, flame throwers and fusion weapons lack the precise control assassinate at target.
It is not about the damage the weapon delivers but its stealth.
If the performance roll is successful, the player does not even roll damage, and the target is dead.

The degree of difficulty for the performance roll is equal to the target's awareness attribute score.
The referee can alter the DD as she sees fit.
Plot points and player personas are highly resistant to the assassination ability.

If the player fails the performance roll, the weapon still inflicts damage on the target.
If the damage kills the target, it is not considered an assassination by the spie.
A target that dies during a failed assassination attempt could still be resuscitated.

Only a failed performance roll will reveal the spie's position in a long-range attack.

.*Incapacitate vs Assassinate*
There is a variation on this ability where the spie incapacitates the target by wounding.
There is no difference in the DD of the maneuver, but the player must roll damage.
If the damage does not accidentally kill the target, then the spie has successfully incapacitated the target.

Disguise::
Spies are naturally adept at not appearing as themselves.
A spie can alter the appearance of her hite and wate with no effort at all.
A spie can make herself appear 50% taller or 25% shorter.
A spie can make herself appear 50% heavier or 25% skinnier.
These changes in hite and wate do not require a performance roll.

More elaborate the disguise, the more difficult the performance roll.
The ability to detect a disguise depends on the awareness attribute of the observer.
Anthros cannot disguise themselves as aliens or robots. 
Vice versa applies. 

.*Impersonation DD*
* Stranger 1-6 (1d6) DD
* Coworker 1-12 (1d12) DD
* Friend 2-25 (1d12 + 1/2AWE) DD
* Family member 2-37 (1d12 + AWE) DD
* Intimate partner 3-62 (1d12 + 2*AWE) DD

The player may be required to make this performance roll multiple times. 
A failed performance roll for disguise reveals the disguise but not the spie.

Bonuses are available to the player.
Surgical interventions, planning, research can improve the chances of success.
If the spie is disguising her voice, the referee should reduce the degree of difficulty.

Stun::
Stun is a specialized martial arts attack used by tv and movie spies across the universe.
Stun represents the single knock-out hand chop.
The stun works best as a surprise attack but can also be useful in combat. 
The spie can only attempt to stun a target once per combat unit.
The player must win an attack roll and a performance roll to stun an opponent successfully.
The difficulty is equal to the MSTR of the target.
A successful performance roll drops the target unconscious and uninjured to the ground.
An unsuccessful roll inflicts no damage and leads to embarrassment and humour.

Martial Arts::
Spies have their style of deadly hand-to-hand combat.
The martial art includes kicks, punches, bites, chops, head butts, and body slams.
The martial arts ability is for unarmoured hand-to-hand combat only.
Martial arts attacks do not use weapons and are only effective on targets in an adjacent hex.

The attack roll uses the Bonus Proficient (BP) from the Type A line on the combat table.
The damage adjustment (DA) is from the Type B line on the combat table.

include::ROOT:partial$CH08_Table_Spie_Martial_Arts.adoc[]

Amour Rating Bonus::
A spie's armour rating (AR) increases through dodges, parries, blocks, and rolls.
This martial arts AR is for an unarmoured dress like a tuxedo or bathing suit.
This armour rating bonus does not improve the AR of worn armour. 

Attack Frequency::
This column indicates the number of martial arts attacks the spie can make each unit.
The number of attacks applies to the number of martial arts attacks that the persona can make.
The number of attacks does not apply to any weapon attacks.
A first level spie gets one martial arts attack per unit. 
A fifth level spie gets three martial arts attacks per unit.

Attack Damage::
An attack roll win delivers the damage listed.
The player adds her Type B damage adjustment to this roll.
The Type B weapon damage bonus (DA) is  1/4 of the persona's physical strength.
A first level spie with a 12 PSTR inflicts 1d4+3 HPS in damage.
A fifth level spie with a 12 PSTR inflicts 1d8+3 HPS in damage.

Attack Order::
The attack order is the secret sauce of the spie's martial arts.
The attack order allows experienced spies to get an attack roll in before and during their opponent's attacks.
A fifth level spie gets one attack roll before and one attack roll during the opponent's attack.
If this 5th level spie wins the initiative roll, she gets three attacks before her opponent.
The attack order supersedes initiative.

.*Martial Arts Attack Order*
* Normal - normal initiative and attack roll timing.
* Before - attack roll before opponent attack regardless of initiative
* During - attack roll during opponent attack regardless of initiative

:art: mysterious_exit.png
:width: 250px
:snark: Out of the frying pan...
:artist: Leon Bennet
:date: 1879
:license: CC BY-SA 4.0
:description: Drawing of human escaping out of or into a room via a chandelier.

include::ROOT:partial$articulate.adoc[]

== Spie Tricks
Spie tricks are skills that are the trademarks of any qualified spie.
Spie tricks should bypass plot points.

At startup, the player makes one roll per four points of intelligence on the Spie Tricks Table.
The player can extend one of her existing tricks or generate a new one for each new experience level.

So a spie with a 12 INT gets three rolls on the table.

.*Example Spie Trick List*
* Concealment 2
* Cryptography 1

The spie tricks are cumulative and combinable.
If the spie is trying to conceal something, she sets a skill bonus of +2.
If the spie is trying to conceal something with cryptography,  her skill bonus would be +3.

include::ROOT:partial$CH08_Table_Spie_Tricks.adoc[]

Assassination::
Each assassination skill level reduces her assassination performance roll by 3DD.

Bribery::
Bribery allows the spie to convince personas to act out of context for remuneration.
Some upstanding citizens may refuse any attempt at bribery.
While others look at the additional remuneration as a business transaction
The persona can use her bribery skill to slip across a border, get into a concert, or avoid a traffic ticket.
Personas cannot bribe people into damaging themselves.
Bribery has a DD range of 1-12 (1d12).
The greater the risk for the bribee, the higher the degree of difficultly.

Blackmail::
Blackmail is a variation on bribery where the target is a victim and does not benefit in the transaction.
Blackmail has a DD range of 1-12 (1d12).

Casing::
The spie uses casing to assess the risks of trying to penetrate a structure.
Successful casing determines otherwise hidden alarms and security systems. 
Casing has a minimum DD range of 1-12 (1d12).
The referee may modify this DD as she sees fit.

Climbing::
Climbing tricks allow the spie to channel her inner monkey.
Spie climbing is a combination of freestyle and parkour.
Climbing has a minimum DD range of 1-8 (1d8).
The referee may modify this DD as she sees fit.

Concealment::
Concealment is the art of hiding objects on the body of the spie.
The spie can hide weapons or money in her fat folds, armpits, fur, or orifices.
The difficulty is adjusted depending on the intensity of the search.
Concealment has a minimum DD range of 5-12 (1d8+4).
The referee may modify this DD as she sees fit.
A successful performance roll allows the spie to sneak information or reveal information.

Cryptography::
The spie can use this trick to encode or decode data.
The encrypted material can take on any form the spie sees fit.
The ref should adjust the difficulty to reflect the complexity of the code.
Cryptography has a minimum DD range of 9-16 (1d8+8).
The referee may modify this DD as she sees fit.
A successful performance roll allows the spie to sneak stuff past a search.

Escape::
A spie can use her escape trick to avoid an otherwise inevitable event.
A successful escape only delays impending doom.
The spie can only use an escape roll to escape the impending doom.
The spie can jump out of the way of a giant speeding robot, but she may jump off a bridge to do so. 
_out of the frying pan and usually into the fire_.
Cryptography has a minimum DD range of 9-16 (1d8+8).
The referee may modify this DD as she sees fit.
Escape cannot avoid plot or story points, but it may delay them for dramatic effect.

Forgery::
Forgery is the spie's art form.
Forgery ranges from falsifying legal documents to counterfeiting currency.
Forgery is time-consuming.
Forgery has a minimum DD range of 5-12 (1d8+4).
The referee may modify this DD as she sees fit.
A successful performance roll creates a passable document.

Interrogation::
Interrogation is the formal or informal push for information from an unwilling persona.
The spie can get information from a target by cajoling, deceiving, threatening, or hurting.
The degree of difficulty is equal to the target's mental strength score.
An interrogation on a persona with a 10 MSTR would be a 10 DD maneuver.

Lying::
A successful performance roll allows the persona to deceive lie detectors, immigration officers, legal cross-examination, or scrutiny.
The lying trick should not replace an opportunity for role-playing.
The degree of difficulty is equal to the target's mental strength score.
Lying to a persona with a 10 MSTR would be a 10 DD maneuver.

Picking Locks::
Bypass things that keep things protected.
The locks include doors, boxes, safes, ignitions etc.
Lock picking is non-destructive.
Smashing a lock or shooting it with the Hollywood Unlocking Blaster is not lock picking.
The nature of the lock decides the degree of difficulty.
Tool locks are mechanical, and tech locks are electronic, comp locks may use facial recognition, and AI locks are the hardest to pick.

Picking Pockets::
Picking pockets is any sleight of hand resulting in the transfer of wealth or property to the spie.
The spie removes items from the pocket, flap, purse, or pouch of a primary observer.
The degree of difficulty depends on the awareness of the target. 
The action rarely will deceive electronic surveillance equipment such as hidden cameras or alarm systems.
The degree of difficulty is equal to the target's awareness score.
Picking the pocket of a persona with a 10 AWE is be a 10 DD maneuver.

Stealth Movement::
Stealth is like spie camouflage.
Stealth includes the ability to hide in the shadows, move silently, and avoid detection.
The degree of difficulty is equal to the observer's awareness score.
Sneaking past a persona with a 10 AWE is be a 10 DD maneuver.
The player must win a performance roll for every observer.

// for performance tables
// tag::spie_maneuvers[]

== Spie Maneuvers
Spie maneuvers are about deception, treachery and sneaky violence.
Most spie maneuvers are considered combat maneuvers. 
Other spie tricks are considered gut maneuvers.
The referee can adjust Performance Roll bonuses depending on where the maneuver lies.

Spies have essential equipment.
A spie must have some element of deception in their persona equipment.
Deceptive equipment includes a pair of dark sunglasses, a fake ID or a trench coat.
The referee may make a target roll more difficult if the spie no tools of deception.

include::ROOT:partial$CH14_Table_DD_Spie.adoc[]

// end::spie_maneuvers[]




== Spie Experience
The benefits of increasing experience levels are more tricks, improved performance, and improved combat skills. Spies earn experience points for completing maneuvers and role-playing within their vocation. Only 75% of combat experience can go towards a spie's experience point total.

include::ROOT:partial$CH08_Table_Spie_Experience.adoc[]

