= Combat Tables

[quote]
____
*A list of numbers that the persona takes into combat.*
____

The combat table is the centrepiece of the tactical combat system.
The tactical combat system allows for players to carry out detailed combat shenanigans using miniatures on a tabletop.
The Combat Table combines all of the persona's bonuses in one place.
The matrix lists all the bonuses that the player adds to her attack and damage rolls.
The combat table combines attributes, vocation, levels, weapon familiarity and tactics to pretend that these elements matter.

Each persona has its own combat table. 
The amount of time spent calculating the data depends on the importance of the persona.
Player personas have the most detailed combat tables.
Cannon fodder have the least detailed combat tables.

include::ROOT:partial$CH09_Table_Tiny_CT.adoc[]

The tactical combat system is not simple, and the combat table requires an understanding of many acronyms.
You need to read this section if the following acronyms do not make sense: Skilled, Raw, Max, Force, AR, Type A, Type B, Type C etc.
If you know what you are looking for, jump to the combat table you need.
Below is a list is of player persona combat tables. 
Referee persona combat tables are detailed in their referee persona sections

.*Jump to the Combat Tables*
* xref:i-roll_playing_rules:CH04_Anthros_CT.adoc[Anthro Combat Table,window=_blank]
* xref:i-roll_playing_rules:CH05_Robots_Z_CT.adoc[Robot Combat Table,window=_blank]
* xref:i-roll_playing_rules:CH06_Aliens_6_CT.adoc[Alien Combat Table,window=_blank]

== Deconstruction of a Combat Table
The example combat table from above is broken down row by row with links to more detailed explanations.

include::ROOT:partial$CH09_Table_Description_of_a_Combat_Table.adoc[]

// remember anthro, robot CTs are missing in creation alien is present.

// attack types tag
include::CH27_Tactical_Combat.adoc[tag=Attack_Types]

== Skilled Bonus
This number is added to the attack rolls when the persona is using familiar weapons.
Being familiar and skilled with a weapon indicates that the persona is proficient with that weapon.
Using a proficient weapon allows the persona to bring all her aptitude and skills to bear.
The higher the Skilled Bonus (Skilled), the more likely the player will win her attack roll and damage the target. 
When the player throws her kilodie attack roll, she adds the Skilled to the die roll. 

If the persona is using an unfamiliar weapon, she uses her Raw Bonus (Raw).

The Skilled Bonus has two main components: attribute bonuses and level bonuses.

=== Attribute Component
Most of the calculations done on the combat table involve the persona's attributes.
Each attack type has its own attribute calculation. 
Strong personas have better attack bonuses with thrusting and striking attacks.
Dextrous personas excel with powered missile attacks.

:art: combat_feline_pstr_win.png
:width: 250px
:snark: STR helps Type A attacks.
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid feline walking away from destroyed carnival game.

include::ROOT:partial$articulate.adoc[]

=== Level Component
The level component refers to the bonuses the persona gets from her vocation and experience level. 
The higher the experience level, the better the persona is at combat. 
In general, the persona with the higher level will be better in combat.
Sometimes exceptional attributes can overshadow experience levels.
However, if two personas have the same attributes more experienced persona will have an advantage.

== Raw Bonus
The Raw Bonus is added to an attack roll when the persona is using unfamiliar weapons.
The Raw Bonus (Raw) is a fraction of the persona's Skilled. 
The Raw still benefits the player's attack roll but less so than her Skilled.
Personas will prefer to use familiar weapons in which they are proficient.

The persona's vocation determines the persona's  Raw. 
All anthros have vocations and therefore use the Vocation Raw Table to determine their Raw.
The more combat-oriented the vocation is, the better their Raw Bonus.
The less combat-oriented the vocation is, the lower their Raw is relative to their Skilled.
A nothing only can use 10% of her Skilled Bonus with type C attacks.
A mercenary can use 100% of her Skilled for all attacks. 

:art: critical_fail_equine_grenade.png
:width: 250px
:snark: You must know your tool.
:artist: Peggy Lynn McIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a humanoid horse throwing away a pin and holding a grenade.

include::ROOT:partial$articulate.adoc[]

== Maximum Roll
The Maximum Roll is the best attack roll that the player can make for her persona.
If a player's total attack roll is 1042 and her Maximum Roll (Max) is 884, her attack roll becomes 884.
As the persona increases in experience levels, her Maximum Roll increases as well.
Combat vocations increase their Skilled andMax faster than non-combat vocations.
Without the Max, low-level personas are as dangerous as high-level personas.

NOTE: *Critical Checks allow any persona to damage any other persona with pure chance.*

Occasionally a player will be unable to win an attack roll on a target with a high armour rating.
This limitation of the Maximum Roll will leave some players feeling helpless and frustrated.
These emotions indicate that it's a good time for their persona to run away.

:art: maximum_roll.png
:width: 250px
:snark: Just can't get better.
:artist: Andrew Brechin
:date: 1991 
:license: CC BY-SA 4.0
:description: Drawing of dart in center of dartboard.

include::ROOT:partial$articulate.adoc[]

== Force Bonus
The player adds the Force Bonus when she wins an attack roll.
The Force Bonus (Force) represents the impact of Strength on persona-powered attacks.
Strength increases the amount of damage that the persona delivers with a striking weapon.
Powered attacks (type C) do not have a Force Bonus.

NOTE: *Force Bonus is a legacy term from the last millennium. Damage Bonus seems more appropriate.*

== Proficiencies
Proficient indicates that the persona is familiar with the attack type.
If the persona is familiar with the attack type, the player uses the Skilled Bonus when attacking.
If the persona is not proficient with the attack type, she uses her Raw when attacking.
In all cases, excepting the vocation mercenary, a persona's Raw is much lower than her Skilled.

In most cases, proficiency is referring to artifact weapon skill and familiarity.
An anthro, or a tool-using alien, can be proficient in a technological weapon.
Proficiency does not apply to an alien's evolved biological attacks.
Proficiency does not apply to a robot's baked in offensive systems. 

The player chooses the weapon proficiencies for her persona.
Players should choose their persona's weapon proficiencies carefully. 
For example, being proficient with a laser will be fun until its batteries run out.
In a leather and dust milieu, a crossbow proficiency may have been a better choice.
Players are encouraged to reserve weapon proficiencies for when the best weapon comes along.

Combat vocations start with more proficiencies and learn new ones faster.
The player can add new proficiencies as her persona increases in experience levels.
The number of initial proficiencies and the intervals for new ones are listed below.

include::ROOT:partial$CH09_Table_Attack_Proficiencies.adoc[]

Aliens::
Aliens are automatically proficient with their natural attacks.
Aliens that are not tool users can only use their natural attack types in combat.
So aliens do not have Raws for their natural attacks. 
Tool using aliens following vocations use the Vocation Raw Table to determine their Raw.

Robots::
A robot is only proficient with attacks baked-in during fabrication.
Robots use their Raw for attacks that are malfunctioning peripherals. 
Robotic Raw is zero.

Knites:: 
Knites are always proficient with their energy sword.
A knite's energy sword does not count as proficiency.

Mercenaries:: 
Mercenaries are efficient with anything that is a weapon.
A merc must first identify the artifact as a weapon.
Mercs also get skills bonuses that can increase their attack rolls even further.

Nothings:: 
Nothings are only proficient with one weapon and one weapon only.







