= Alien RP

Aliens are not anthros.
Aliens referee personas are organic entities and are defined by their random shape.
Hence the family name diversidae.

When an RP alien is being evolved by the referee she is creating an entirely new species.
Each RP alien is unique unto itself however it is a member of an species.
How much effort goes into each alien is up the referee's milieu.

The referee should massage the alien RP to fit her milieu.
The Alien RP section is for helping creativity, not replacing it.

.*Alien RP Evolution Checklist*
* *RP ROLL PLAYING (Data)*
. <<_alien_rp_roll_playing,Roll Playing>>
. <<_alien_rp_relevance,Relevance>>
. <<_alien_rp_record_sheet,Persona Record Sheet>>
. <<_alien_rp_attributes,Attributes>>
. <<_alien_rp_size,Size>>

. <<_alien_rp_hit_points,Hit Points>>
. <<_alien_rp_number_of_attacks,Attack Frequency>>
. <<_alien_rp_damage,Attack Damage>>
. <<_alien_rp_armour_rating,Armour Rating>>

. <<_alien_rp_wate_allowance,Wate Allowance>>
. <<_alien_rp_description,Description>>

. <<_alien_rp_movement_rate,Move>>
. <<_alien_rp_age,Age>>
. <<_alien_rp_mutations,Mutations>>

. <<_alien_rp_society,Society>>
. <<_alien_rp_exps_level,EXPS Level>>
. <<_alien_rp_vocation,Vocation>>
. <<_alien_rp_equipment,Equipment>>
. <<_alien_rp_combat_table,Combat Table>>
. <<_alien_rp_combat_ratio,Combat Ratio>>
* *RP ROLE PLAYING (Fun)*
. <<_alien_rp_role_playing,Role Playing>>
. <<_alien_rp_biology,Biology>>
. <<_alien_rp_story,Story>>
. <<_alien_rp_appearance,Appearance>>
. <<_alien_rp_beliefs,Beliefs>>
. <<_alien_rp_modifications,Modifications>>
. <<_alien_rp_name,Name>>
. Have Fun!

== Alien RP Roll Playing
Aliens are very diverse and their creation is heavily dependent on die rolls.
The referee is welcome to create everything for her new RP alien species.
The die rolls here are tools to enhance creativity not replace it.

Most often the referee will be creating flora and fauna for her campaign milieu.
In this situation the referee is creating a recurrent RP that is from a species.
The species will have similar combat traits and behaviours for each encounter.

== Alien RP Relevance
Not all RPs are created equal.
Some are less important than others.
The referee will know the RP's level of the beginning of the RP creation.
A RP's relevance increases the entangled they are with the expedition.

Alien referee personas are a single representative of an entire species. 
Cannon and canon fodder may need more information than RPs from other families.

include::ROOT:partial$CH11_Table_RP_Relevance.adoc[]

=== Species or Specific
The alien created is usually a member of a species. 
This is the case for mundane flora and fauna, invading alien hordes, or first encounters.
The species may define everything about the referee persona. 
The species may all have the same size, shape, belief and personality.
How the referee persona fits into this depends on her campaign milieu and back story.
Alien RP evolution can also be used to create a species that the players never meet.

The referee's input is most important in creating all referee personas.
The alien need not be a member of a species, but could be a vat created singular entity.
This would make the persona a very specific one of a kind life form. 

=== Cannon Fodder
Cannon fodder are like movie extras that fill in the background.
Alien cannon fodder are the harmless flora and fauna in a forest.
Alien cannon fodder are also be sidewalk civilians of an advanced society.
Alien sidewalk civilians fill the streets of a city, village, or spacecraft.

.*Cannon Fodder* 
. offer no opposition
. have no useful information
. have no nutritional value, monetary value or useful parts.

Sidewalk civilians, and terrain flora and fauna can be created on the fly. 
The alien cannon fodder has one universal value.
Anthro cannon fodder have a one universal value of 6.
The value is used for HPS or attributes to facilitate play.
This universal value must reflect the alien species as a whole.
For example, a tiny alien may have HPS of 4 while a gigantic alien may have HPS of 20.

Cannon fodder does not mean expendable without consequence.
Hunting flora and fauna may be against the law.
Alien societies may have laws protecting their defenceless comrades.

=== Canon Fodder
Canon fodder have bit parts in the story, but do not make the story. 
Alien canon fodder are usually dangerous flora or fauna or alien combatants.

.*Canon Fodder* 
. could act in opposition to the expedition's goals
. could injure or kill a player persona
. could accidentally alter the story of a campaign
. could have information or treasure

The goal of the canon fodder is usually predetermined by the referee or milieu.
The referee creates as much information as needed.
The alien could an indigenous predator that eats anthros.
The predator's goal is predetermined and lack nuance. 
Their info may be kept on a card, and a persona record sheet is not essential.

Canon fodder can be extremely dangerous to the expedition.
They are there to get in the way of the player's goals. 

=== Canon Referee Persona
Canon referee personas are like supporting actors that make the story possible.
Canon referee personas are integral participants in the campaign story.
They can be powerful recurring enemies, or comrades in arms.
Canon RPs are fully developed alien species of which this RP is a member.
Only the player personas are more important to the story.
Canon referee personas utilize every step of persona creation.

== Alien RP Record Sheet
The referee persona record sheet is just another persona record sheet.
There are few bonus elements that referee must keep track of.
Most player personas do not have elements like personality, politics or religion.
The referee persona record sheet can also be used to keep track of expedition interactions.

NOTE: *If the referee persona is worth playing it is worth writing down.*

== Alien RP Attributes
Alien referee persona attributes are generated here.
The attributes should be massaged to reflect the campaign milieu.
These changes can be made on the fly or applied in <<_alien_rp_modifications,Modifications>> later.

include::ROOT:partial$CH06_Table_Alien_Attributes.adoc[]

== Alien RP Size
The bigger the bigger.
Alien RPs can also be Minute or Humongous.
These sizes are considered not playable for player personas.

include::ROOT:partial$CH06_Table_Alien_Size.adoc[]

=== Extremely Tiny Alien Size
An alien that is Tiny has a 1 in 6 chance to be *Minute* instead.
Minute aliens cannot be run by a player but can be introduced by a referee.
Minute aliens have a WATE of  0 to 999 grams (1d1000-1).
No Minute alien will have a WATE greater than a kilogram.
A minute alien's HPS and PSTR are adjusted by their size.
Other attributes remain unchanged.

==== Minute Alien HPS and PSTR adjustment
.HPS = (rolled HPS) * (wate/1000)
.PSTR = (rolled PSTR) * (wate/1000)
****
An alien with 50 HPS, 12 PSTR and 500 gm Wate would have 25 HPS and 6 PSTR. +
These attributes can easily be reduced to 1. 
****

=== Extremely Gigantic Alien Size
An alien that is Gigantic has a 1 in 6 chance to be *Humongous* instead.
Humongous aliens have a WATE of 6 to 300 tons (1d50 times 6).
Humongous aliens cannot be run by a player but can be introduced by the referee.
A humongous alien uses all the same attribute and combat values of a gigantic alien.

== Alien RP Hit Points
More bigger more hit points.

include::ROOT:partial$CH06_Table_Alien_Hit_Points_HPS.adoc[]

// check why 2 tables?

== Alien RP Number of Attacks
The more attacks the more dangerous.

include::ROOT:partial$CH06_Table_Number_of_Alien_Attacks.adoc[]

== Alien RP Damage
More Bigger More Damage

include::ROOT:partial$CH06_Table_Alien_Damage_Per_Attack.adoc[]

include::ROOT:partial$CH06_Table_Alien_Attack_Type.adoc[]

== Alien RP Armour Rating
How hard is it to damage this alien in combat?

include::CH06_Aliens_7_AR.adoc[tag=Alien_AR]

== Alien RP Wate Allowance
What can the alien carry without being encumbered.

include::ROOT:partial$CH03_Table_Physical_Strength_and_Wate_Allowance_(kg).adoc[]

== Alien RP Description
The alien RP defines it's appearance and diversity.
The appearance also decides the alien's movement rate through different terrains.
Remember to record the movement letters (l,a,w,s) for each body part rolled.

=== Roll  Parts
Four rolls for four parts, and record the movement letters.
Detailed explanation exist at xref::CH06_Aliens_8_Shape.adoc[Alien Appearance]

.Roll the four basic parts.
. Head
. Torso
. Arms
. Legs

include::ROOT:partial$CH06_Table_Alien_Body_Parts.adoc[]

=== Coat and Colour
Coat is uniform over whole alien
Roll colour and affects 

include::ROOT:partial$add_colour_to_your_world.adoc[]

=== Adornments
These are optional accents to the alien's appearance.
Adornments are entirely descriptive.
Adornments do not detract from or add any abilities to the alien. 

==== Head 
include::ROOT:partial$CH06_Table_Adornment_Head.adoc[]

==== Torso
include::ROOT:partial$CH06_Table_Adornment_Torso.adoc[]

==== Arms
include::ROOT:partial$CH06_Table_Alien_Adornments_Arms.adoc[]

== Alien RP Movement Rate
Denizens may hop, slither, scuttle, slime or gallop along with whatever form of locomotion is listed as legs in their appearance.
More detail is available at xref::CH06_Aliens_9_Move.adoc[Alien Movement]

=== Base Movement
// include::CH06_Aliens_9_Move.adoc[tag=Alien_Move]

The type of creature part that is used to describe the alien's locomotion will move at the designated movement rate regardless of what the description is.
For instance, an alien that looks like a snail could move as fast as an alien that looks like a leopard. 

=== Quartering Movement
Determine how fast the alien moves in different terrains. 
Aliens may be able to fly, swim or run. 
The movement rates are determined by the movement lettering of the alien body parts.
These movement rates indicate natural movement of the alien.
An alien who's society is educated may learn how to swim, but that would not make the RP w

include::ROOT:partial$CH06_Table_Calculating_Alien_Movement.adoc[]

== Alien RP Mutations
Aliens have a chance of physical  mutations.
For a species these mutations are considered abilities.
An alien's mutation applies to the entire species and are naturally evolved defensive or offensive abilities.
The alien RP being created would come fully developed with all these abilities intact.
The referee may massage abilities to come out at certain ages or after certain experiences.
For example and entire species with the ability of Time Stop would be challenging indeed.


== Mental Abilities
The chance of an alien having a mental mutation ability is equal to the alien's MSTR.
Each successful roll indicates another roll to check for another ability.
An alien RP with a 15 MSTR would have a 15% chance of having a mental ability.
If successful she can check again for another. 

=== Alien Mental Abilities
.percent chance = MSTR
****
An alien with a 15 MSTR has a 15% chance. 
First 1d100 roll is 11 she gets a mental ability. 
Second roll is 15 she gets a second mental ability.
Third roll is 27 and she moves on with 2 mental abilities. 
****

Defective mutations are played as the referee sees fit.
They can become part of the species, not count as a mental ability, or be re-rolled.

== Physical Abilities
The chance of an alien having a physical mutation ability is equal to the alien's CON.
Each successful roll indicates another roll to check for another ability.
An alien RP with a 15 CON would have a 15% chance of having a physical ability.
If successful she can check again for another. 

=== Alien Physical Abilities
.percent chance = CON
****
An alien with a 15 CON has a 15% chance. 
First 1d100 roll is 11 she gets a physical ability. 
Second roll is 15 she gets a second physical ability.
Third roll is 27 and she moves on with 2 physical abilities. 
****

== Alien RP Age
Life expectancy is defining feature of organic life forms. 

include::ROOT:partial$CH06_Table_Alien_Lifespan.adoc[]

include::ROOT:partial$CH11_Table_Alien_RP_Life_Stage.adoc[]

include::ROOT:partial$CH06_Table_Alien_Life_Stages.adoc[]

=== Extremely Short Life Spans 
If the RP's life span is *less than 10 years* there is a 1 in 6 chance will have an extremely short lifespan.
Extremely short life spans should be reflected in the alien RP's biology and society.
Short lived species often depend on large numbers of offspring requiring minimal energy exertion.
In earthly biology this is referred to as progeny over prodigy.

include::ROOT:partial$CH11_Table_Alien_RP_Age_Short_Lifespan.adoc[]

=== Extremely Long Life Spans
If the RP's life span is *more than 10000 years* there is a 1 in 6 chance that the alien will have an extremely long life span.

Extremely long life spans should be reflected in the alien RP's biology and society.
Long lived species often invest large amounts of energy into very few offspring.
In earthly biology this is referred to as prodigy over progeny.

== Alien RP Society
Alien society is something for the referee to carefully consider and prepare for her campaign.
Alien societies can even be the basis for an entire campaign.
The differences in values, architecture, and social organization alone amongst alien cultures would be beyond the duration of a life time of study.

.Societal Compositions
* Language 36%
* Culture 11%
* Education 4%
* Vocation 1%

.Tool Usage Frequencies
* None 52%
* Simple 38%
* Tech 8%
* Comp 1% 
* Creator (AI) 0.1%


include::ROOT:partial$CH11_Table_RP_Alien_Society.adoc[]

== Alien RP EXPS Level
Good for flora, fauna, and vocations

include::ROOT:partial$CH11_Table_Referee_Persona_Level.adoc[]

== Alien RP Vocation
Must have vocation on society level.
No attributes restrictions apply.

include::ROOT:partial$CH11_Table_Referee_Persona_Class.adoc[]

== Alien RP Equipment
Referee personas carry equipment: they should be supplied with food, survival equipment, and funds.
What the referee persona is carrying as survival equipment will vary depending on terrain.
Referee personas are also assumed to have collected artifacts throughout their travels.
RPs get one artifact for every experience level.

=== No Tool Use
No tools, no rocks, does not even recognize tech. 
Nothing can be solved by anything other than their own body parts.
This alien does not fetch.
This alien would only drink water not collect it.

=== Simple Tool User
May use natural unmodified items.
A rock may be used to mash something.
Sticks could be used to reach something.
The alien may use leaves or shells to collect water for later use.
For combat this alien would always use her natural abilities and not weapons.
This alien does not use mundane equipment, or artifacts at all.

=== Tech Tool User
This is most common interpretation of tool user.
The alien can use all mundane tools.
She can also use artifacts and better mundane equipment.
A tech tool using alien RP gets one roll on the Limited TOY Table below.

xref:i-roll_playing_rules:CH24_Mundane_Equipment.adoc[Mundane Equipment]
Referee personas carry equipment: they should be supplied with food, survival equipment, and funds.
What the referee persona is carrying as survival equipment will vary depending on terrain.

=== Comp Tool User
This is most common interpretation of a high tool user.
While this alien can use all mundane tools she will prefer to use artifacts.
The Comp level tool user does not have access to society transforming artifacts.
A comp tool user gets one roll per EXPS level on the Limited TOY Table below. 
All artifact will be of normal tech level (TL10). 

include::ROOT:partial$CH41_Table_TOY_Type_Limited.adoc[]

=== Creator
Creators an intimate relationship and understanding of technological devices.
Creators get one roll on the regular TOYS table per EXPS Level.
A creator can have space ships or high tech versions of artifacts.

Treasure and Random Junque do not count as a TOYS roll for creators. 
Creator aliens can amass great wealth as well as deadly weapons.

include::ROOT:partial$CH41_Table_TOY_Type.adoc[]

In addition to all kinds of artifacts creator aliens can have high tech artifacts.

include::ROOT:partial$CH49_Table_TOY_Tech_Level.adoc[]

== Alien RP Combat Table
The combat table is used for tactical combat in the Roll Playing Rules.
If you are using the Role Playing Rules you can skip this section.

Alien RPs have can have two combat tables.
Every alien gets a combat table for her natural attacks. 
Aliens that have vocations will have a combat table for their artifact weapons.
If the alien shoots lasers out it's butt use the natural combat table.
If the alien is a nomad shooting an arrow from a bow use the artifact combat table.

=== Natural Attacks
This combat table is used for the natural attacks of the alien RP.
It is not used for artifact weapons.
RP alien attacks like bites, claws, horns, spine shooting or  butt lasers use this combat table.

Aliens do not have a Bonus non-proficient or damage adjustor for their natural attacks.
An alien is automatically proficient with its evolved attacks.
The alien damage adjustor is taken into account with the alien damage amount based on alien size.

Note that level alien EXPS Level bonuses are built right into the Bonus Proficient.

include::ROOT:partial$CH11_Table_Alien_Referee_Persona_Combat_Table_(CT).adoc[]


include::ROOT:partial$CH11_Table_Alien_Referee_Persona_Combat_Table_Example.adoc[]

=== Artifact Attacks
If alien is a tool, tech, comp or creator tool user she may use a weapon.
An alien never uses it's natural attack CT for artifact weapons of any type.
If the alien has a vocation she will use the CT for that vocation.
If the alien does not have a vocation her BP advances as a Nothing Vocation.

include::ROOT:partial$CH11_Table_RP_Bonus_Proficient_(BP).adoc[]

include::ROOT:partial$CH11_Table_Calculated_Level_Bonus__for_RPs_with_Classes.adoc[]

include::ROOT:partial$CH11_Table_Bonus_Non_Proficient_(BNP).adoc[]

== Alien RP Combat Ratio
// boilerplate is from anthro RP
include::CH11_Referee_Personas_Anthro.adoc[tag=Combat_Ratio]

=== Alien Specific

include::ROOT:partial$CH11_Table_RP_CR_Alien.adoc[]

// general CR adjustments list of tables.
// heading is === for each table
include::ROOT:partial$CH11_RP_CR_General.adoc[]

== Alien RP Role Playing
The first half of referee persona creation involves much dice rolling and data collection.
Much of the data collected is needed for Roll Playing Rules. 
For those using the Role Playing Rules much of the data can be ignored, and the results recorded.
This section is a framework. 
The referee may choose the descriptive elements or roll them randomly.
Little or none of the information in this section affects the power of the persona.
However it does affect the story of the persona. 

NOTE: *These rolls and tables are an aid to creativity. Not a replacement for creativity.*

Use this section as a framework to for creating referee personas that have backstory and plans. 

* *RP ROLE PLAYING (Fun)*
. <<_alien_rp_biology,Biology>>
.. Biome
.. Energy Source
.. Reproduction
.. Dwelling
.. Aroma
. <<_alien_rp_story,Story>>
.. Origin
.. Presence
.. Goal
.. Personality
. <<_alien_rp_appearane,Appearance>>
.. Clothing
.. Hygiene
.. Gender
. <<_alien_rp_beliefs,Beliefs>>
.. Religious
.. Political
.. Philosophical
. <<_modifications,Modifications>>
.. attributes
.. size
.. age
. <<_alien_rp_name,Name>>


== Alien RP Biology
Alien biology assigns terrain, eating habits, reproduction etc.
These shouls always be massaged to work best with the ref's campaign milieu 

.*Alien Biology Checklist*
. <<_biome,Biome>>
.. <<_biome_modification,Biome Modification>>
. <<_energy_source,Energy Source>>
.. <<_procurement,Procurement>>
. <<_reproduction,Reproduction>>
. <<_dwelling,Dwelling>>
. <<_grouping,Grouping>>

=== Biome
What terrain is the alien from. 

include::ROOT:partial$CH06_Table_Alien_Biome.adoc[]

==== Biome Modification
How is that terrain modified.

include::ROOT:partial$CH06_Table_Alien_Biome_Characteristic.adoc[]

=== Energy Source
Nom nom.

include::ROOT:partial$CH06_Table_Alien_Energy_Source.adoc[]

==== Energy Procurement
How does the alien get it's nom nom.

include::ROOT:partial$CH06_Table_Alien_Energy_Procurement_Strategy.adoc[]

=== Reproduction
Where do little aliens come from?

include::ROOT:partial$CH06_Table_Alien_Reproductive_Method.adoc[]

=== Dwelling
Typical living space.

include::ROOT:partial$CH06_Table_Alien_Habitation_Type.adoc[]

=== Grouping
Do they hang out in groups or solo?
include::ROOT:partial$CH06_Table_Alien_Group_Size.adoc[]

== Alien RP Story
Everything has a story.
The depth of the story depends on the referee persona's relevance.
The amount of backstory collected is determined by the relevance of the persona. 
Cannon fodder have no back story. 
Canon RPs have all the back story possible.
The backstory for a referee persona must be massaged to fit into the milieu of the story.
The Trinity of the RP (origin, presence, and goal) is usually pre-determined by the referee.

Referee personas benefit from a personality, origin, presence, and goal.
Which of these is the most important is decided by the referee.

=== Origin
Vinda Tralok is a hungry alien that lives in the the nearby desert.
Vinda is always hungry and is always looking for food.
She traps her food by digging collapsing holes.
This is her origin. 

include::ROOT:partial$CH11_Table_Referee_Persona_Origin.adoc[]

=== Presence
Vinda sees that the expedition has her favourite food
Vinda wants to hang around with them so she can get food.
She is willing to be very helpful in order get her nom noms.
This is her presence.

include::ROOT:partial$CH11_Table_Referee_Persona_Presence.adoc[]

=== Goal
Vinda only wants to provide for herself and won't work towards much more than that.
For example she may not be interested in going off planet.
She would rather just hang out near the desert and provide herself with food.

include::ROOT:partial$CH11_Table_Referee_Persona_Goal.adoc[]

=== Anthro RP Personality
Alien RPs get personality traits.
How the alien expresses these personality traits is up to the referee.
If an alien does not have language it is unlikely they can express complex emotions.
Extroverted personality traits are NOT irrational: a diplomatic RP will not try to play consul to a crazed combat robot but she may intercede between inter-expedition differences.
Aliens and robots also get a roll on the Extroverted Personality table.

include::ROOT:partial$CH11_Table_Referee_Persona_Extroverted_Personality_Trait.adoc[]

==== Introverted
The Introverted Personality Sub-table indicates subtle personality traits.
These traits are not too strong and should only be employed by the referee when decisions must be made by the RP.
Such traits are played discreetly by the referee, and may only occasionally be used or noticed.

include::ROOT:partial$CH11_Table_Introverted_Personality_Trait.adoc[]

==== Insane
The Insane Personalities Table lists irrational actions that are basically pathological.
Insane personality traits can appear in completely unexpected situations, endangering the referee persona and the expedition.
The easiest and most fun referee personas to play are insane ones, but they should be kept relatively rare since EXP is an insane enough game as it is.
Referees are not expected to be psychiatrists and can role-play the mental illness however they interpret them.
If the roll on this table has been directed from the Extroverted Personality Trait Table the insanity will be quite overt.
If the referee is rolling an insane personality off of the Introverted Personality Trait then the insanity will be less obvious.

include::ROOT:partial$CH11_Table_Insane_Referee_Persona_Personality_Traits.adoc[]


== Alien RP Appearance
Alien RP appearance is not limited to it's four body parts.
Alien RPs can have gender and clothing.
All additional appearance elements are optional.

=== Gender
Gender represents appearance only.
Gender does not represent genetics, sexuality, reproduction, or employment.
Politics of gender are up the the referee and players. 
It is up to the referee to decide how gender appearance applies to a parasitic psionic feeder.

include::ROOT:partial$CH11_Table_RP_Gender.adoc[]

=== Clothing
Alien RP clothing is completely different from all other clothing. 
The descriptions can be actual swaths of clothing covering parts.
If the alien is particularly enormous there may only be accents of the clothing type.
Flora and fauna with no language that are not tool users have *NO* clothing

include::ROOT:partial$CH11_Table_Referee_Persona_Dress.adoc[]

=== Aroma
What a wonderful smell you have discovered.

include::ROOT:partial$CH06_Table_Alien_Aroma.adoc[]

== Alien RP Beliefs
Beliefs are purely cerebral elements of the referee persona.
They are not nearly as entrenched as personality or hygiene. 
Referee personas may talk the talk about a belief, but how devout they are is variable.
RP beliefs are what the persona would like to be rather than what they actually are.

include::ROOT:partial$CH11_Table_RP_Beliefs.adoc[]

=== Religious Belief
The list here describes the structure of the religion and does not list existing human religions.
The nomenclature, structure, hypocrisy, and corruption level is left to the referee and her milieu.

include::ROOT:partial$CH11_Table_Referee_Persona_Religious_Belief.adoc[]

=== Political Belief
The list here describes the structure of the politics and does not list existing human parties.
The nomenclature, structure, hypocrisy, and corruption level is left to the referee and her milieu.

include::ROOT:partial$CH11_Table_Referee_Persona_Political_Belief.adoc[]

=== Philosophical Belief
Some real.
Some silly.
All futile mental exercises in futility. 

include::ROOT:partial$CH11_Table_Referee_Persona_Philosophical_Belief.adoc[]

== Alien RP Modifications
Not every referee wants their aliens to have the attribute ranges listed in the alien persona chapter.
Often a referee will want a small alien, a dumb alien, a slow alien, or even a dumb, slow, small alien (prey).
For special attributes for special aliens refer to Table 11.6: Descriptive Attribute Adjustments.
The corresponding alien adjectives such as tough, strong, or smart, are not included and, when desired regular alien attribute generation should suffice.

include::ROOT:partial$CH11_Table_Anthro_RP_Modifiers.adoc[]

== Alien RP Name
Alien names can get complicated.
Every alien has a given name and a species name.
The given name is created by the player.

Every alien also has a species name.
When an alien is evolved it represents one member of an entire species.
The species name describes every other alien persona that is not the player persona.
Species names reflect elements of the alien itself. 
Using Latin sounding words in a double hander makes the species name sound fancier.
A tiny poisonous alien may have the species name Minutiae Venonimous.
This naming opportunity comes with great responsibility.
Usually the referee and players will negotiate the species name.

The alien name created here can always be used in common parlance.
Names that are composed of pheromones, howls, or ultrasonic clicks will only be used between the alien species.