= Anthro RP

Anthros are upright, bipedal humanoids.
In the fake taxonomy, anthros are of the family Hominidae and the genus homo.
Referees are most familiar with playing this type of referee persona.
They have hands, heads and faces.
The referee should massage the anthro RP to fit her milieu.
This section is for helping creativity, not replacing it.

.*Anthro RP Delivery Checklist*
* *RP ROLL PLAYING (Data)*
. <<_anthro_rp_roll_playing,Roll Playing>>
. <<_anthro_rp_relevance,Relevance>>
. <<_anthro_rp_record_sheet,Persona Record Sheet>>
. <<_anthro_rp_type,Anthro Type>>
. <<_anthro_rp_size,Size>>
. <<_anthro_rp_age,Age>>
. <<_anthro_rp_attributes,Attributes>>
. <<_anthro_rp_movement_rate,Move>>
. <<_anthro_rp_armour_rating,Armour Rating>>
. <<_anthro_rp_wate_allowance,Wate Allowance>>
. <<_anthro_rp_mutations,Mutations>>
. <<_anthro_rp_exps_level,EXPS Level>>
. <<_anthro_rp_vocation,Vocation>>
. <<_anthro_rp_equipment,Equipment>>
. <<_anthro_rp_combat_table,Combat Table>>
. <<_anthro_rp_combat_ratio,Combat Ratio>>
* *RP ROLE PLAYING (Fun)*
. <<_anthro_rp_role_playing,Role Playing>>
. <<_anthro_rp_story,Story>>
.. Origin
.. Presence
.. Goal
.. Personality
. <<_anthro_rp_appearance,Appearance>>
.. Clothing
.. Hygiene
.. Gender
. <<_anthro_rp_beliefs,Beliefs>>
.. Religious
.. Political
.. Philosophical
. <<_modifications,Modifications>>
.. attributes
.. size
.. age
. <<_anthro_rp_name,Name>>
. Have Fun!

== Anthro RP Roll Playing
Roll playing is a play on words that honours the dice rolling required to create a  referee persona.
The roll playing here generates the data that a referee needs to play a referee persona.
The referee should massage the roll results to reflect the milieu of her campaign.
There is less massaging to do in this section than the role-playing section.

== Anthro RP Relevance
Not all RPs are created equal.
Some personas are less important than others.
The referee usually knows the importance of the persona before she starts generation.
An RP's relevance increases the more entangled they are with the expedition.

include::ROOT:partial$CH11_Table_RP_Relevance.adoc[]

=== Cannon Fodder
Cannon fodder are the movie extras that fill in the background.
Anthro cannon fodder are called sidewalk civilians.
Sidewalk civilians fill the streets of a city, village, or spacecraft.

[quote]
____
Cannon Fodder are volume discounted anthros used to attack cannons.
____

.*Cannon Fodder* 
. offer no opposition
. have no useful information
. have no nutritional value, monetary value or useful parts.

The referee can create sidewalk civilians on the fly. 
Any numerical value needed is 6.
Anthro cannon fodder have 6 HPS, 6 DEX, and 6 MSTR.
The anthro type can is non-descript as in a mutt for canines. 
Cannon fodder only transiently exists, and no persona record sheet is needed.
You can stop here if you randomly rolled cannon fodder. 

Cannon fodder does not mean expendable without consequence.
Killing off cannon fodder is against norms and laws in most settings.
Police forces and superheroes spend most of their time protecting cannon fodder.

=== Canon Fodder
Canon fodder may have bit parts in the story, but they do not make the story. 
Anthro canon fodder are minions, soldiers, or security staff.

.*Canon Fodder* 
. could act in opposition to the expedition's goals
. could injure or kill a player persona
. could accidentally alter the story of a campaign
. could have information or treasure

The referee usually predetermines the goal of canon fodder.
The referee creates as much information as needed.
For example, mercenaries defending a lab may only have a pistol and a BP and BNP.
Their uniforms may be uniforms, and no further description is needed.
The referee generates other attributes as needed.
The referee may keep their info on a card, and a persona record sheet is not essential.

Canon fodder can be extremely dangerous to the expedition.
They are there to get in the way of the player's goals. 
If there is combat, the canon fodder is ready for action.

=== Canonical Persona
Canonical personas are like supporting actors that make the story possible.
These referee personas are integral participants in the campaign story.
They can be powerful recurring enemies or comrades in arms.
Canonical referee personas are the real deal.
These referee personas utilize every step of persona creation.
They have all attributes, vocations, mutations and goals.
Only the player personas are more important to the story.

== Anthro RP Record Sheet
The referee persona record sheet is just another persona record sheet.
There are few bonus elements of which the referee must keep track.
Most player personas do not have elements like personality, politics or religion.
The referee can also use the persona record sheet to keep track of interactions with the expedition.

NOTE: *If it's worth playing, it's worth writing down.*

:art: aquarium_not_aquarian.png
:width: 250px
:snark: An aquarium not an aquarian
:artist: Imagestoks 
:date: 2017
:license: Copyright Imagestoks 2015
:description: Drawing of a space suit with fish swimming in the helmet.

include::ROOT:partial$articulate.adoc[]

== Anthro RP Type
The anthro RP type should reflect the referee's milieu.
The anthro type table is for inspiration only. 

include::ROOT:partial$CH11_Table_Anthro_RP_Anthro_Type.adoc[]

=== Anthro Subtypes
The anthro subtype should reflect the referee's milieu.
The anthro subtype table is for inspiration only. 

Anthro subtypes are phenotypical, not scientific.
Anthros are appearance only and are faithful to mundane terran science.

Non-descript anthro types are also called mutts. 
A canine mutt is a canine, but no more distinct than that.

include::ROOT:partial$CH11_Table_Anthro_RP_Anthro_Type_Subs.adoc[]

.source links for anthro subtypes
* https://en.wikipedia.org/wiki/List_of_fish_common_names[Aquarian]
* https://en.wikipedia.org/wiki/List_of_dog_breeds[Canine]
* https://en.wikipedia.org/wiki/List_of_horse_breeds[Equine]
* https://en.wikipedia.org/wiki/Ungulate[Equine]
* https://en.wikipedia.org/wiki/Felidae[Feline]
* https://en.wikipedia.org/wiki/Reptile[Reptilian]
* https://en.wikipedia.org/wiki/Rodent[Rodentia]
* https://en.wikipedia.org/wiki/Bear[Ursidae]

=== Anthro RP Size
Use this single look-up table to create the anthro's hite and wate. 
For a refresher on calculating hite and wate jump to xref::CH04_Anthros_Size.adoc[Anthro Size,window=_blank].
To choose specific sizes like obese, skinny tall or short, jump to <<_modifications,Modifications>>.

include::ROOT:partial$CH11_Table_Anthro_RP_Hite_and_Wate.adoc[]

=== Anthro RP Age
Most often, the lifespan category is enough of a descriptor for the referee persona.
If the story needs an exact age, EXP has a table that has you covered.

include::ROOT:partial$CH11_Table_Anthro_RP_Lifespan_Category.adoc[]

include::ROOT:partial$CH11_Table_Anthro_RP_Age.adoc[]

== Anthro RP Attributes
Referee persona attributes are slightly better than player persona attributes and do not affect the persona's anthro type or vocation.
The referee generates initial attributes for the referee persona using the attributes table below.
The attributes are then modified to reflect the anthro type and vocation.
To choose descriptive attributes like slow, weak, or dumb jump to <<_modifications,Modifications>>.

include::ROOT:partial$CH11_Table_Anthro_RP_Attributes.adoc[]

=== Anthro RP Hit Points
A referee persona's Hit Points (HPS) maximum is determined the same as any other anthro persona.
For more information about anthro hit points jump xref:i-roll_playing_rules:CH04_Anthros_HPS.adoc[here,window=_blank].

==== HPS Maximum
include::CH04_Anthros_HPS.adoc[tag=Anthro_HPS]

==== Damage System Shock
include::CH04_Anthros_HPS.adoc[tag=Anthro_DSS]

==== Anthro RP Recovery
include::CH04_Anthros_HPS.adoc[tag=Anthro_REC]

=== Anthro Type Attribute Corrections
For RPs, attributes do not select the anthro type.
The attributes are modified to reflect the anthro type.
Attributes are never corrected down. 
However, if the referee needs a clumsy feline, she can achieve this at <<_modifications,Modifications>>

include::ROOT:partial$CH11_Table_Anthro_RP_Attribute_Correction_Type.adoc[]

== Anthro RP Movement Rate
Movement rate is dependent on DEX and represented in hexes per unit.
If the referee needs a slow or fast RP, this is modified at <<_modifications,Modifications>>

include::ROOT:partial$CH03_Table_Dexterity_and_Movement_Rate.adoc[]

== Anthro RP Armour Rating
Armour rating is adjusted using DEX.
// this in include from Anthro AR
include::CH04_Anthros_AR.adoc[lines=3..20]

== Anthro RP Wate allowance
The better the PSTR, the more she can lift.

include::ROOT:partial$CH03_Table_Physical_Strength_and_Wate_Allowance_(kg).adoc[]

== Anthro RP Mutations
Referee personas mutate the same as other personas. 
The referee can push for mutations by doubling the chance.
The table should be used as a guide if mutations are to be assigned.
Pure Strains are not vessels for zany mutations.
Insectoids rarely get physical mutations.
Keep in mind that some mutations are campaign changers and should be appropriately rare.

include::ROOT:partial$CH04_Table_anthro_mutations.adoc[]

== Anthro RP EXPS Level
Generate an experience level for every anthro RP.
Anthros have vocations, and the EXPS level can be their most important roll.
EXPS level impacts how many artifacts and skills the RP gets.

include::ROOT:partial$CH11_Table_Referee_Persona_Level.adoc[]

== Anthro RP Vocation
All anthros get a vocation. 
The referee should choose the vocation that best suits the needs of the story and milieu.

include::ROOT:partial$CH11_Table_Referee_Persona_Class.adoc[]

=== Vocation Attribute Correction
RP attributes do not select the persona's vocation type.
The attributes are modified to reflect the vocation type.
Attributes are never corrected down. 
However, if the referee needs a clumsy spie, she can achieve this at <<_modifications,Modifications>>

include::ROOT:partial$CH11_Table_Referee_Persona__Vocation_Supercharge.adoc[]

== Anthro RP Equipment
Referee personas carry equipment.
They have food, survival equipment, funds, and toys.
RPs get one TOYs roll for every experience level.

=== Mundane Equipment
Referee personas usually have what is necessary to survive in the local terrain.
The persona's survival equipment will vary with the terrain and the referee's milieu.

xref:i-roll_playing_rules:CH24_Mundane_Equipment.adoc[Mundane Equipment]

=== TOYs
Toys are technological devices that behave like magical devices.
If a referee persona needs a particular technological device, the referee will add it to the persona.
The referee may limit  RP equipment to maintain game balance.

Higher-level RPs will have successfully identified most of their toys.
An RP may also have an unidentified technological toy.
An unidentified toy is an artifact.
A lower-level RP is more likely to be carrying around an artifact.

.*Referee Persona TOYs*
* one roll on TOY table per EXPS Level
* vocation limits do not apply
* space vehicle, robot or vehicle limits do not apply
* treasure is accumulated but does not count as roll

include::ROOT:partial$CH41_Table_TOY_Category.adoc[]

== Anthro RP Combat Table
The combat table keeps track of the persona's combat skills and increases with EXPS level.
The referee need not calculate a complete combat table for cannon fodder or canon fodder referee personas.
Canonical referee personas need a full combat table calculated.
For general info about combat tables, jump to xref:i-roll_playing_rules:CH09_Combat_Tables.adoc[Combat Tables,window=_blank] in tactical combat.
For detailed info about the calculations below, jump to xref:i-roll_playing_rules:CH04_Anthros_CT.adoc[Anthro combat table,window=_blank].

A second level spie has the following attributes: AWE 12 CHA 11 CON 12 DEX 10 INT 12 MSTR 14 and PSTR 16.

include::ROOT:partial$CH04_Table_Anthro_CT_Xample.adoc[]

== Anthro RP Combat Ratio
// tag::Combat_Ratio[]
Combat Ratio  (CR) is how tough the referee persona is.
The CR is a number that pretends to measure how dangerous an RP is in combat.
The higher the combat ratio, the more powerful an adversary the referee persona is.
The CR is used to determine the EXPS value and number of attackers.

The Combat Ratio number indicates how many player personas represent a fair fight.
For this process, a player persona is a level one anthro persona with a typical combat table. 

A CR of 20 indicates that the solitary referee persona could handle 20 player personas.
This referee persona is very dangerous.
A CR of 1/10 indicates that ten referee personas are needed to fight one player persona.
This referee persona is very weak in combat.

The combat ratio does not determine precisely how many referee personas show up in an encounter.
The milieu and the story determine the number of referee personas., not the CR.

=== Calculating a Combat Ratio
. RPs initial CR is 1
. Add all the Pluses to the CR
. Multiply all the Times to the CR
. Combat ratio does not follow https://en.wikipedia.org/wiki/Order_of_operations#Mnemonics[BODMAS]

.CR = (1 + all Pluses) * all Times
****
An RP with a Plus 1, Plus 4, Plus 2, Times 1.25, and Times 2.0 +
(1 + 1 + 4 + 2) * 1.25 * 2.0 = 20
****

// end::Combat_Ratio[]

=== Anthro RP Combat Ratio Adjustments
Anthro RP Combat Ratio is tricky to calculate because anthros are soggy bags of mostly water.
However, their weapons and vocations can make them the most dangerous RPs in the game.

When preparing an anthro combat ratio, the referee should consider all of the RP's equipment.
A nothing canine with a fusion pistol is more dangerous than a nomad feline with a bow and arrows.

.*Combat Ratio Checklist*
. Anthro Specific
. Bonus Proficient
. Attack Type
. Number of Attacks
. Damage per Unit
. Movement Rate
. Hit Points
. Mental Strength

=== Anthro Specific

include::ROOT:partial$CH11_Table_RP_CR_Anthro.adoc[]

//collection of general CR tables
include::ROOT:partial$CH11_Table_RP_CR_General.adoc[]

== Anthro RP Role Playing 
The first half of referee persona creation (RP Roll Playing) involves much dice rolling and data collection.
The data collected is essential for players using the Roll Playing Rules. 

NOTE: *This section is an aid to creativity, not a replacement for creativity.*

This second half of referee persona creation (RP Role Playing) is qualitative and descriptive.
Little or none of the information in this section affects the power of the persona.
However, it does affect the story of the persona. 
The Anthro RP Role Playing section is for inspiration and creative support.
Use this section as a framework for creating the backstory plans and emotions of referee personas. 

* *RP ROLE PLAYING (Fun)*
. <<_anthro_rp_story,Story>>
.. Past
.. Present 
.. Future
.. Personality
. <<_anthro_rp_appearance,Appearance>>
.. Clothing
.. Hygiene
.. Gender
. <<_anthro_rp_beliefs,Beliefs>>
.. Religious
.. Political
.. Philosophical
. <<_modifications,Modifications>>
.. attributes
.. size
.. age
. <<_anthro_rp_name,Name>>

== Anthro RP Story
The referee persona's story is a skeleton to help the referee create a backstory.
By this point, the persona already has a vocation, anthro type, experience level.
The past, present, future and personality of the persona give the referee a skeleton to hang the story meat.

Cannon, and canon, fodder do not have detailed stories at all. 
Canonical personas may need a lot more.

=== Past
The past story element is a geographic cue for the referee and players.
This location history helps determine if this persona is exotic or mundane.
The details of the persona's origin may fit into the current milieu or require the referee to extend her world.

include::ROOT:partial$CH11_Table_Referee_Persona_Origin.adoc[]

=== Present
The present story element is a mix of intentions and reasons for showing up.
The reasons behind the Present Story may need filling out or may fit into the existing milieu.

include::ROOT:partial$CH11_Table_Referee_Persona_Presence.adoc[]

=== Future
The future story element is usually an internal goal of the persona.
The referee may drop hints about the persona's future goals.
If they are nefarious, the referee will likely keep the plans secret.
It is also possible that the persona will not know what her future goal is.

include::ROOT:partial$CH11_Table_Referee_Persona_Goal.adoc[]

=== Personality
Personality traits help guide the referee when the RP is making decisions.
While it is fun to play up an RP's personality, the referee must remember the pithy aphorism; less is more. 
The players should be guiding the story, not a strong-willed referee (persona).

The personality types are organized by how strongly they influence the persona's decision.

.*Personality and Decisions*
. None - follows and contributes.
. Introverted - has opinions but does not fight for them.
. Extroverted - has strong opinions and behaviours.
. Insane - has beliefs and will make bad decisions.

The initial die roll is on the Extroverted Personality Trait table. However, the persona is more likely to have an introverted personality trait. 

include::ROOT:partial$CH11_Table_Referee_Persona_Extroverted_Personality_Trait.adoc[]

==== Extroverted
Extroverted personality traits are not irrational.
They are just obvious.
A diplomatic RP will *not* try to negotiate with a heavy combot.
She will run away.
A diplomatic RP may intercede between player persona arguments about loot distribution.
The expedition can win over an extroverted personality trait with some convincing.

==== Introverted
These are not immediately obvious to the players.
The referee persona may have opinions based on the personality trait, but she will readily agree with the expedition.
An introverted personality trait may influence a referee's "behind the shield" decision. 

include::ROOT:partial$CH11_Table_Introverted_Personality_Trait.adoc[]

==== Insane
Insane personality traits are not clinical illnesses.
The traits are not illnesses from the https://en.wikipedia.org/wiki/DSM-5[DSM].
They are personality traits so strong that the RP may make the wrong decision and cannot be convinced otherwise.

The insanity may be overt and quickly discovered by the expedition.
Or it may be hidden and discovered when it is too late.

NOTE: *Insanity is not role-played as a disease but as a decision influencer.*

Extroverted and introverted personality traits will not put the persona in harm's way.
Insane personality traits can put the whole expedition in harm's way. 
These are the kind of traits that will override the better, often safer, decision.

The expedition can influence extroverted and introverted personality traits to do what is best for the expedition.
Insane personality traits are immune to the rational input of the expedition. 

include::ROOT:partial$CH11_Table_Insane_Referee_Persona_Personality_Traits.adoc[]

== Anthro RP Appearance
An RPs appearance has three elements: clothing, hygiene and gender.
All of them are optional.

=== Clothing
Clothing is appearance only.
Clothing does not represent the culture, gender, occupation or personality of the referee persona.
A persona's clothing may be uniform that she always wears or may be a nuance of existing fashions.

An RP may have several favourite styles and may even combine them in some random arrangement.
The shoes may be punk rock, but the hairdo renaissance. 

include::ROOT:partial$CH11_Table_Referee_Persona_Dress.adoc[]

=== Hygiene
Hygiene is a general habit that the persona exhibits.
Hygiene does not influence charisma, social standing or task rolls.

While variable depending on the scenario, the RP tends to ebb back to the hygiene description.
A habitually immaculate RP that fell in the mud would look like someone who fell in the mud.
The immaculate RP would clean herself off sooner and better than the filthy RP.
A habitually filthy spie would not arrive un-groomed at an aristocratic function.

include::ROOT:partial$CH11_Table_Referee_Persona_Hygiene.adoc[]

=== Gender
Gender represents appearance only.
Gender does not represent genetics, sexuality, reproduction, or employment.
The politics of gender are up to the referee and players. 

include::ROOT:partial$CH11_Table_RP_Gender.adoc[]


== Anthro RP Beliefs
Beliefs are purely cerebral elements of the referee persona.
They are not nearly as entrenched as personality or hygiene.
Referee personas may talk the talk about a belief, but how devout they are is variable.
RP beliefs are what the persona would like to be rather than what they are.

include::ROOT:partial$CH11_Table_RP_Beliefs.adoc[]

=== Religious Belief
The list here describes the structure of the religion and does not list existing human faiths.
The referee and her milieu determine the nomenclature, structure, hypocrisy, and corruption of the religion.

include::ROOT:partial$CH11_Table_Referee_Persona_Religious_Belief.adoc[]

=== Political Belief
The list here describes the structure of the politics and does not list existing human parties.
The referee and her milieu determine the nomenclature, structure, hypocrisy, and corruption of the political system.

include::ROOT:partial$CH11_Table_Referee_Persona_Political_Belief.adoc[]

=== Philosophical Belief
Some are real.
Some are silly.
All are mental exercises in futility. 

include::ROOT:partial$CH11_Table_Referee_Persona_Philosophical_Belief.adoc[]

== Modifications
Modifications are descriptors that make changes to the referee personas attributes and size.

include::ROOT:partial$CH11_Table_Anthro_RP_Modifiers.adoc[]

== Anthro RP Name
The anthro should have a name as any anthro player persona does.
For anthro, naming shenanigans jump to xref:i-roll_playing_rules:CH04_Anthros_Name.adoc[Anthro Name,window=_blank].

