= Referee Personas

A Referee Persona (RP) is any persona that is *not* run by a player.
If a persona is not controlled by a player it must be brought to life by the referee.
These personas brought to life by the referee are called referee personas. 
The referee persona could be from any family: anthro, robot, alien or AI.
Referee personas can be friend, foe, flora, or fauna.

NOTE: *Referee Personas have been called non player characters in the past RP=NPC*

== Referee Persona Checklist
Referee run personas require more details than player run personae.
The Referee Persona Creation Checklist indicates the extra info needed for a referee persona. 

.*Referee Persona Creation Checklist*
* *ROLL PLAYING INFO (Data)*
. <<_determine_family,Determine Family>>
.. Anthro
.. Alien
.. Robot
.. AI
. Determine Relevance
.. Cannon Fodder
.. Canon Fodder
.. Canon Persona
. Persona Record Sheet
.. Record creation Date
.. Record unique RP ID
. Determine Type
. Attributes
. Armour Rating
. Movement Rate
. Wate Allowance
. Mutation
. EXPS Level
. Vocation
. Equipment
.. Mundane
.. Artifact
. Combat Table
. Combat Ratio
* *ROLE PLAYING INFO (Fun)*
. Story
.. Origin
.. Presence
.. Goal
.. Personality
. Appearance
.. Clothing
.. Hygiene
.. Gender
. Beliefs
.. Religious
.. Political
.. Philosophical
. Modifications
.. attributes
.. size
.. age
. Name
. Have Fun!

=== Determine Family
The referee starts the process of RP generation by picking a family for the RP.
Most often the referee will need a certain kind of RP and can jump right to that section.
If inspiration is needed then roll on the Referee Persona Family Determination Table. 

include::ROOT:partial$CH11_Table_RP_Family_Type.adoc[]

== Referee Role-Playing
It is the responsibility of the ref to role-play referee personas to the best of her ability.
Intelligent aliens must seem and act intelligently.
Nomads will prefer their biome over luxury.
Anti-knites must not stray from the righteous path of entropy.
Robots lack facial expressions and body language.
In short the referee must be able to make even the temporary personas as real as possible.

=== Spread the Fun
Collaborative role-playing groups will often have players represent referee personas.
This works well for personas that friendly and neutral to the expedition.
A player could run a cranky shop keeper that likes to haggle.
A player could run an adorable alien that begs for scraps of plastic.
A player should not run a Heavy Combot RP that is attacking the expedition.
A player should not run an spie feline RP that knows crucial campaign secrets. 

== Referee Persona Generation
There almost always is a reason for generating referee personas.
The expedition need's an ursidae mercenary for protection in the wilds.
The wilds need's to be populated with ferocious alien creatures.
The radioactive ruin may be ruled by an explorations bot lethally collecting specimen samples.

Most referee personas will be altered to fit into the milieu of the campaign.
A referee could create a completely random referee persona encounter.
However it is unlikely that a completely random creation will fit the milieu.
The referee should massage the RP creation to fit into her milieu.
The RP tool set is for helping creativity, not replacing it.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

Each family has it's own section for RP creation.
Each section has all it's data on one page for convenience.
Moving from top to bottom will create a person most efficiently.
It is recommended to fill in a persona record sheet as you create the persona.

The tables in each section have little additional information.
If more is needed it can usually be found in the persona generation section of that family.
Creating referee persona's can be as much fun as playing them. 

=== Time Constraints
Referee personas with little relevance can be quickly created on the fly. 
Full fledged referee personas that play a significant role in the campaign story cannot.
Violent alien encounters, full fledged anthro expedition members take time to create.
If play time is of the essence it is best to have such RPs created in advance.

=== Descriptors
Descriptors are changes that the referee can employ to influence the RP created.
The referee may want a smart weakling anthro to clean the expedition's hotel room.
These kinds of descriptors can also be rolled by the referee.
Descriptors are not personality or appearances of the RP.
Descriptors change the attributes of the referee persona.
For example, a weak RP will have a low PSTR.

== Roll vs Role
EXP is a tale of two systems. 
The Roll playing system focuses on technical and tactical gaming.
It involves lots of dice rolling and arithmetic. 
The Role-playing system focuses on collaborative story telling.
It involves very little dice rolling and minimal arithmetic.

To create an RP the referee will need to use both systems. 
Roll playing info supplies crucial elements like anthro type, alien attacks and robot size.
Role-playing info supplies elements of colour that influence how the RP is role played.
If the group is using the Role-playing Tootisix system most of the numerical data can be ignored.

Story and character are the point of both systems. 
Roll playing does not disregard story or character. 
Role-playing is a simpler way to get to the story. 
