= Robot RP

Robots are the colloquial name for the family Machinidae. 
Machinidae are life forms that are inorganic and fabricated.
An organic fabricated life form would be an alien.
An inorganic non-fabricated would most likely be an alien.
Robots can be fabricated by Anthros, Aliens or other Robots.

Robot RPs should be massaged to fit into the milieu of the campaign.
This section is for helping creativity, not replacing it.

.*Robot RP Fabrication Checklist*
* *RP ROLL PLAYING (Data)*
. <<_robot_rp_roll_playing,Robot Roll Playing>>
. <<_robot_rp_relevance,Relevance>>
. <<_robot_rp_record_sheet,Persona Record Sheet>>
. <<_robot_rp_type,Select Type>>
. <<_robot_rp_attributes,Attributes>>
. <<_robot_rp_size,Size>>
. <<_robot_rp_armour_rating,Armour Rating>>
. <<_robot_rp_movement_rate,Movement Rate>>
. <<_robot_rp_wate_allowance,Wate Allowance>>
. <<_robot_rp_exps_level,EXPS Level>>
. <<_robot_rp_vocation,Vocation>>
. <<_robot_rp_systems,Systems>>
.. Offensive
.. Defensive
.. Peripheral
. <<_robot_rp_control_factor,Control Factor>>
. <<_robot_rp_adaptability,Adaptability>>
. <<_robot_rp_value,Value>>
. <<_robot_rp_tech_level,Tech Level>>
. <<_robot_rp_age,Age>>
. <<_robot_rp_combat_table,Combat Table>>
. <<_robot_rp_combat_table,Combat Ratio>>
* *RP ROLE PLAYING (Fun)*
. <<_robot_rp_role_playing,Robot Role Playing>>
. <<_robot_rp_technology,Technology>>
.. Power Source
.. Sensors
.. Locomotion
. <<_robot_rp_story,Story>>
.. Origin, Presence, Goal
.. Fabricator Type
.. Personality
. <<_robot_rp_appearance,Appearance>>
.. Shape
.. Colour
.. Adornments
. <<_robot_rp_beliefs,Beliefs>>
. <<_robot_rp_modifications,Modifications>>
. <<_robot_rp_name,Name>>
. Have Fun!

== Robot RP Roll Playing
stuff about dice

== Robot RP Relevance
Not all RPs are created equal.
Some are less important than others.
The referee will know the RP's level of the beginning of the RP creation.
A RP's relevance increases the entangled they are with the expedition.

include::ROOT:partial$CH11_Table_RP_Relevance.adoc[]

=== Cannon Fodder
Cannon fodder are like movie extras that fill in the background.
Robot cannon fodder are inorganic machines operating in the distance.
These robots are delivery drones, cashiers, or elevators.

.*Cannon Fodder* 
. offer no opposition
. have no useful information
. have no nutritional value, monetary value or useful parts.

Any combat contact will utterly destroy robotic cannon fodder.
Destroying robotic cannon fodder is not without consequence.
The robot may be owned by a company or powerful entity. 

=== Canon Fodder
Canon fodder have bit parts in the story, but do not make the story. 
Robot canon fodder can be security sentries, attack drones, or angry shopping carts.

.*Canon Fodder* 
. could act in opposition to the expedition's goals
. could injure or kill a player persona
. could accidentally alter the story of a campaign
. could have information or treasure

The goal of the canon fodder is usually predetermined by the referee or milieu.
The referee creates as much information as needed.
For example, security sentries protecting a plantation may only have a lazer and BP.
The security sentries could all look the same with different numbers.
Other attributes are created as needed.
Their info may be kept on a card, and a persona record sheet is not essential.

Canon fodder can be extremely dangerous to the expedition.
They are there to get in the way of the player's goals. 
If this means combat the canon fodder are ready to do so.

=== Canon Referee Persona
Canon referee personas are like supporting actors that make the story possible.
Canon referee personas are integral participants in the campaign story.
They can be powerful recurring enemies, or comrades in arms.
Canon RPs are fully developed referee personas with attributes, peripherals and goals.
Only the player personas are more important to the story.
Canon referee personas utilize every step of persona creation.

== Robot RP Record Sheet
The referee persona record sheet is just another persona record sheet.
There are few bonus elements that referee must keep track of.
Most player personas do not have elements like personality, politics or religion.
The referee persona record sheet can also be used to keep track of expedition interactions.

NOTE: *If the referee persona is worth playing it is worth writing down.*

== Robot RP Type
The robot RP type is generated on the Single Roll Robot Type Table. 
The referee should massage the robot type to suite her campaign's milieu.
For example, is a first level expedition ready for a heavy combot. 
Nope.

include::ROOT:partial$CH05_Table_Robot_Single_Roll.adoc[]

== Robot RP Attributes
For robot RPs their type determines their attributes.
Robot RP attributes are generated using the robot look up table below. 
The attribute look up table gives the direct attribute scores.
Robot RPs have a mental strength of zero and are not connected to the thinkspace in any way.
What is missing from this look up table are the attribute ranges for the robot RPs.

include::ROOT:partial$CH11_Table_Robot_RP_Attributes.adoc[]

=== Robot Attribute Ranges
Some robot abilities depend on the robot's attribute range. 
For player personas the attribute ranges determine the robot type.
For robot RPs the robot type determines the attribute ranges. 
Consult the lookup table below to record the attribute ranges.

include::ROOT:partial$CH11_Table_Robot_RP_Attribute_Ranges.adoc[]

== Robot RP Size
Robot RP size is broken down in to Wate and Hite.

=== Robot RP Wate

include::ROOT:partial$CH11_Table_Robot_RP_Wate.adoc[]

include::ROOT:partial$CH05_Table_Robotic_Size_Wate.adoc[]

==== Extremely Light Robots
There is a small chance that the robot will be minute or humongous.
Roll 1d100 to make a size check.

=== Extremely Tiny Robot Size
A robot that is Tiny has a 1 in 6 chance to be *Nano* instead.
Nano robots cannot be run by a player but can be introduced by a referee.
Nano robots have a WATE of  0 to 999 grams (1d1000-1).
No nano robot will have a WATE greater than a kilogram.
Nano robots have no change to their attributes or combat values.
However they are not very effective at ramming. 

==== Extremely Heavy Robots
A robot that is Gigantic has a 1 in 6 chance to be  a *Mighty Machine* instead.
Mighty machine robots will have a WATE of 6 to 300 tons (1d50 times 6).
Mighty machine robots cannot be run by a player but can be introduced by the referee.
A mighty machine robot uses all the same attribute and combat values of a gigantic alien.
However in the area of ramming most mighty machines instantly destroy their targets. 

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

=== Hite
Size gives a rough estimation of the volume occupied by the robot.
The referee rolls dimensions once for each of hite, width and length.
These can be arranged in whatever order works best for the personal.

include::ROOT:partial$CH05_Table_Robot_Dimensions.adoc[]

This table does not work for nano robots or mighty machines. 

== Robot RP Armour Rating
Robot RPs have an AR of 700.
A robot AR is the same as any other persona AR.
A successful attack roll damages the robot as it would any other persona.
Robots are different from organic personas and damage differently.
Robot RPs are easy to hit but hard to destroy.

== Robot RP Movement Rate
Robotic movement rates are determined by the robot's DEX value.
Robots are twice as fast as those other personas with the same DEX.
Those bots which move faster than 8 h/u, must accelerate the same as vehicles.
Robotic acceleration is one hex per unit per PSTR level.

include::ROOT:partial$CH05_Table_Robotic_Movement_Rate.adoc[]

== Robot RP Wate Allowance
Bots are affected by encumbrance, though not as much as other referee personas.
As expected, weight allowance is determined by the PSTR and the PSTR level of the bot.
A robot with a PSTR level of 3 and a 17 PSTR would have a wate allowance of 75 kgs.
This means that the robot can carry 75 kgs before any movement penalties are incurred.
All penalties of encumbrance apply to robots as they would apply to other personas.

Robot size does not effect a robot's wate allowance.

include::ROOT:partial$CH05_Table_Robotic_Wate_Allowance.adoc[]

== Robot RP EXPS Level
EXPS Levels improve the RP's Control Factor, assist in saves and robot attributes.

include::ROOT:partial$CH11_Table_Referee_Persona_Level.adoc[]

== Robot RP Vocation
There are very few situations where a robot RP will have a vocation.
Vet and Maint robots have the vocation of veterinarian and mechanic respectively.
Androids can pursue a vocation if this suits the referee's milieu.
Some robot peripherals will enhance the robot RP with a vocation. 

include::ROOT:partial$CH11_Table_Referee_Persona_Class.adoc[]

== Robot RP Systems
Robotic RP have offensive, defensive and peripheral systems.
Offensive and peripheral systems have different strength levels.
Generating systems for persona robots is convoluted and fun.
The number of rolls for each system can be found on the single lookup table below.
Each robot type has different rolls on different tables. 

include::ROOT:partial$CH11_Table_Robot_RP_Systems.adoc[]

=== Offensive Systems
These are the systems that harm others.
On the lower level tables they are often malfunctioning devices being turned into weapons.
On higher level tables they are baked in weapons intent on destroying things.

==== Attack Table One
These attacks include ramming and peripherals being misused. 
It is possible to get a roll on Attack Table Two to get more dangerous weapon systems.

include::ROOT:partial$CH05_Table_Robotic_Attack_Table_One.adoc[]

include::ROOT:partial$CH05_Table_Robotic_Ramming.adoc[]

include::ROOT:partial$CH05_Table_Type_A_Weapon_Type.adoc[]

==== Attack Table Two
Slightly more dangerous weapons.
Still mostly consists of malfunctioning devices.
It is possible to get several rolls on Attack Table One or move up to Attack Table Three.

include::ROOT:partial$CH05_Table_Robotic_Attack_Table_Two.adoc[]

include::ROOT:partial$CH05_Table_Type_B_Weapon_Type.adoc[]

==== Attack Table Three
This table is composed of baked in weapons that are part of real Offensive Systems.
The robot RP can get many rolls on lower Attack Tables and possibly move up to Table Four.

include::ROOT:partial$CH05_Table_Robotic_Attack_Table_Three.adoc[]

==== Attack Table Four
This table is devoted to lethal weapons that are built in to the robot.

include::ROOT:partial$CH05_Table_Robotic_Attack_Table_Four.adoc[]

=== Defences
Robot defensive systems can arise from misused peripherals that offer unplanned defence.
Other defense systems represent true hardening of the robot making harder to damage or hit.

include::ROOT:partial$CH05_Table_Robotic_Defences.adoc[]

=== Peripherals
Peripherals are attachments that give the robot some additional flexibility in performing its tasks.
These peripherals are non-combative and are used by the robot to survive day to day campaign trials.

include::ROOT:partial$CH05_Table_Primary_Robotic_Peripherals.adoc[]

include::ROOT:partial$CH05_Table_Robotic_Secondary_Peripherals.adoc[]

== Robot RP Control Factor
// boilerplate comes from Robot Personas
include::CH05_Robots_Z_CF.adoc[tag=Control_Factor]

== Robot RP Adaptability
Adaptability is added to the performance rolls made by mechanics working on the robot RP.
Many robot's are hardened against adaptability. 
Like combots for instance.

== Robot RP Value
not discussed in polite circles

== Robot RP Tech Level
Typically the robot referee persona will have the tech level of the milieu in which it was created.
If the referee wishes a tech level

include::ROOT:partial$CH49_Table_TOY_Tech_Level.adoc[]

== Robot RP Age
Robots do not age.
Unlike organic life forms robots only decay from damage and not time. 
The longer since the robot was fabricated the less HPS that it has. 
This has be called the table of decrepitude in the past.

include::ROOT:partial$CH11_Table_Robot_RP_Age.adoc[]

== Robot RP Combat Table
The combat table keeps track of the persona's combat skills and increases with EXPS level.
The referee persona's combat table is calculated here.
It is not as exact as a player persona's combat table.
The combat table is for tactical combat used in the Roll Playing System.
If you are using the Role Playing System you can skip this step.

This combat table is for baked in offensive systems including ramming attacks.
Robot RPs only have a bonus proficient (BP) for their baked in attacks. 
If a robot RP manages to use a gun their To Hit Bonus would be zero.
This includes robots that have articulations that can use weapons.
The only exception would be the robot type Android. 
The robot type android may have a vocation and may use that combat table instead.

include::ROOT:partial$CH11_Table_Robot_Referee_Persona_Combat_Table_(CT).adoc[]

== Robot RP Combat Ratio
// boilerplate is from anthro RP
include::CH11_Referee_Personas_Anthro.adoc[tag=Combat_Ratio]

=== Robot Specific

include::ROOT:partial$CH11_Table_RP_CR_Robot.adoc[]

// general CR adjustments list of tables.
// heading is === for each table
include::ROOT:partial$CH11_RP_CR_General.adoc[]

== Robot RP Role Playing
The first half of referee persona creation involves much dice rolling and data collection.
Much of the data collected is needed for Roll Playing Rules. 
For those using the Role Playing Rules much of the data can be ignored, and the results recorded.
This section is a framework. 
The referee may choose the descriptive elements or roll them randomly.
Little or none of the information in this section affects the power of the persona.
However it does affect the story of the persona. 

NOTE: *These rolls and tables are an aid to creativity. Not a replacement for creativity.*

Use this section as a framework to for creating referee personas that have backstory and plans. 

.*Role Playing Stuff*
. <<_robot_rp_role_playing,Robot Role Playing>>
. <<_robot_rp_technology,Technology>>
.. Power Source
.. Sensors
.. Locomotion
. <<_robot_rp_story,Story>>
.. Origin, Presence, Goal
.. Fabricator Type
.. Personality
. <<_robot_rp_appearance,Appearance>>
.. Shape
.. Colour
.. Adornments
. <<_robot_rp_beliefs,Beliefs>>
. <<_robot_rp_modifications,Modifications>>
. <<_robot_rp_name,Name>>
. Have Fun!

== Robot RP Technology
Qualitative details about how the robots moves, sees, and powers itself.

=== Robot RP Power Source
Robot power sources are sciency fiction supercells that allow the robot to operate.
Recharging may be necessary.

include::ROOT:partial$CH05_Table_Robotic_Power_Cell_Type.adoc[]

=== Robot RP Sensors
Robot sensors allow the robot RP to hear and see like any other persona.
The higher the RPs awareness the more sensors they have. 

include::ROOT:partial$CH05_Table_Robotic_Sensors.adoc[]

=== Robot RP Locomotion
Robot locomotion allows the RP to get anywhere she can fit.
The locomotion roll plays a large roll in appearance. 

include::ROOT:partial$CH05_Table_Robotic_Primary_Locomotion.adoc[]

include::ROOT:partial$CH05_Table_Robotic_Secondary_Locomotion_Type.adoc[]

== Robot RP Story
Everything has a story.
The depth of the story depends on the referee persona's relevance.
The amount of backstory collected is determined by the relevance of the persona. 
Cannon fodder have no back story. 
Canon RPs have all the back story possible.
The backstory for a referee persona must be massaged to fit into the milieu of the story.
The Trinity of the RP (origin, presence, and goal) is usually pre-determined by the referee.

Referee personas benefit from a personality, origin, presence, and goal.
Which of these is the most important is decided by the referee.

=== Past
L33t Un1t is an expendable combot left on the planet from a past war.
She has no command and control, and wanders around the desert near the expeditions home base.

include::ROOT:partial$CH11_Table_Referee_Persona_Origin.adoc[]

=== Present
L33t Un1t still misses the organizational elements of an organized military force.
She would be happy to take direction from anyone with military training.
L33t Un1t will work with the expedition if they offer this kind of direction to her.

include::ROOT:partial$CH11_Table_Referee_Persona_Presence.adoc[]

=== Future
L33t Un1t desires nothing more than to find meaningful leadership.
She will leave the expedition to follow any combot or military brass from her previous campaign.

include::ROOT:partial$CH11_Table_Referee_Persona_Goal.adoc[]

=== Personality
Robot personalities are accidental and arise from malfunctions and damage to their processes.
If the robot RP were to be properly 'repaired' she would lose her personality.

include::ROOT:partial$CH11_Table_Introverted_Personality_Trait.adoc[]

=== Fabricator Type
A robot can not wantonly harm persona from it's fabricator type.
This is the species that the robot was designed and manufactured for.
Almost all robots were fabricated by an anthro type.
In general a robot cannot harm their fabricator type. 
Nor would the robot allow her fabricator type to come to harm.
Every robot type, unless specified, follow this programming.

include::ROOT:partial$CH05_Table_Robotic_Base_Anthro_Type.adoc[]

== Robot RP Appearance
Shape, colours, locomotion type, and peripherals create the robot RP appearance.
These tables are for inspiration and fun and should not replace referee creativity.

=== Basic Shape
The volume of the robot will fit into this shape.

include::ROOT:partial$CH05_Table_Robotic_Basic_Shape.adoc[]

=== Contortion of Basic Shape
This table manipulates the basic shape so that the infinity that is commercial design is reflected.

include::ROOT:partial$CH05_Table_Robotic_Basic_Shape_Adjustment.adoc[]

=== Attachments
Useless attachments.

include::ROOT:partial$CH11_Table_Fancy_Attachments.adoc[]

=== Colour Your Robot
Colour make the world go round.

include::ROOT:partial$add_colour_to_your_world.adoc[]

== Robot RP Beliefs
If the referee feels that the robot is sufficiently damaged to express beliefs roll here.
It is also possible that beliefs are baked in by the robot's fabricators.

include::ROOT:partial$CH11_Table_RP_Beliefs.adoc[]

include::ROOT:partial$CH11_Table_Referee_Persona_Religious_Belief.adoc[]

include::ROOT:partial$CH11_Table_Referee_Persona_Political_Belief.adoc[]

include::ROOT:partial$CH11_Table_Referee_Persona_Philosophical_Belief.adoc[]

== Robot RP Name
Robot names can get complicated.
Every robot has a given name.
The given name was imagined by the robot's malfunctioning brain.
The given name is created by the player.

Robots can also have a model name and a fabricator name.
Model and fabricator names are optional.
The model and fabricator names are usually created by the player.
The referee may have pre-made model names and fabricators that reflect her milieu. 

The robot name created here can always be used in common parlance.
Names that sound like fax machines, look like bar codes or have 600 numbers are only used between robots.
