= Anthro RP

Anthros are upright, bipedal humanoids.
In the fake taxonomy, anthros are of the family Hominidae and the genus homo.
Referees are most familiar with playing this type of referee persona.
They have hands, heads and faces.
The referee should massage the anthro RP to fit her milieu.
This section is for helping creativity, not replacing it.

.*Anthro RP Delivery Checklist*
* *RP ROLL PLAYING (Data)*
. <<_anthro_rp_roll_playing,Roll Playing>>
. <<_anthro_rp_relevance,Relevance>>
. <<_anthro_rp_record_sheet,Persona Record Sheet>>
. <<_anthro_rp_type,Anthro Type>>
. <<_anthro_rp_size,Size>>
. <<_anthro_rp_age,Age>>
. <<_anthro_rp_attributes,Attributes>>
. <<_anthro_rp_movement_rate,Move>>
. <<_anthro_rp_armour_rating,Armour Rating>>
. <<_anthro_rp_wate_allowance,Wate Allowance>>
. <<_anthro_rp_mutations,Mutations>>
. <<_anthro_rp_exps_level,EXPS Level>>
. <<_anthro_rp_vocation,Vocation>>
. <<_anthro_rp_equipment,Equipment>>
. <<_anthro_rp_combat_table,Combat Table>>
. <<_anthro_rp_combat_ratio,Combat Ratio>>
* *RP ROLE PLAYING (Fun)*
. <<_anthro_rp_role_playing,Role Playing>>
. <<_anthro_rp_story,Story>>
.. Origin
.. Presence
.. Goal
.. Personality
. <<_anthro_rp_appearance,Appearance>>
.. Clothing
.. Hygiene
.. Gender
. <<_anthro_rp_beliefs,Beliefs>>
.. Religious
.. Political
.. Philosophical
. <<_modifications,Modifications>>
.. attributes
.. size
.. age
. <<_anthro_rp_name,Name>>
. Have Fun!

== Anthro RP Roll Playing
Roll playing is a play on words that honours the dice rolling required to create a  referee persona.
The roll playing here generates the data that a referee needs to play a referee persona.
The referee should massage the roll results to reflect the milieu of her campaign.
There is less massaging to do in this section than the role-playing section.

== Anthro RP Relevance
Not all RPs are created equal.
Some personas are less important than others.
The referee usually knows the importance of the persona before she starts generation.
An RP's relevance increases the entangled they are with the expedition.

include::ROOT:partial$CH11_Table_RP_Relevance.adoc[]

=== Cannon Fodder
Cannon fodder are the movie extras that fill in the background.
Anthro cannon fodder are called sidewalk civilians.
Sidewalk civilians fill the streets of a city, village, or spacecraft.

[quote]
____
Cannon Fodder are volume discounted anthros used to attack cannons.
____

.*Cannon Fodder* 
. offer no opposition
. have no useful information
. have no nutritional value, monetary value or useful parts.

The referee can create sidewalk civilians on the fly. 
Any numerical value needed is 6.
Anthro cannon fodder have 6 HPS, 6 DEX, and 6 MSTR.
The anthro type can is non-descript as in a mutt for canines. 
Cannon fodder only transiently exists, and no persona record sheet is needed.
You can stop here if you randomly rolled cannon fodder. 

Cannon fodder does not mean expendable without consequence.
Killing off cannon fodder is against norms and laws in most settings.
Police forces and superheroes spend most of their time protecting cannon fodder.

=== Canon Fodder
Canon fodder may have bit parts in the story, but they do not make the story. 
Anthro canon fodder are minions, soldiers, or security staff.

.*Canon Fodder* 
. could act in opposition to the expedition's goals
. could injure or kill a player persona
. could accidentally alter the story of a campaign
. could have information or treasure

The referee usually predetermines the goal of canon fodder.
The referee creates as much information as needed.
For example, mercenaries defending a lab may only have a pistol and a BP and BNP.
Their uniforms may be uniforms, and no further description is needed.
The referee generates other attributes as needed.
The referee may keep their info on a card, and a persona record sheet is not essential.

Canon fodder can be extremely dangerous to the expedition.
They are there to get in the way of the player's goals. 
If there is combat, the canon fodder is ready for action.

=== Canonical Persona
Canonical personas are like supporting actors that make the story possible.
These referee personas are integral participants in the campaign story.
They can be powerful recurring enemies or comrades in arms.
Canonical referee personas are the real deal.
These referee personas utilize every step of persona creation.
They have all attributes, vocations, mutations and goals.
Only the player personas are more important to the story.

== Anthro RP Record Sheet
The referee persona record sheet is just another persona record sheet.
There are few bonus elements of which the referee must keep track.
Most player personas do not have elements like personality, politics or religion.
The referee can also use the persona record sheet to keep track of interactions with the expedition.

NOTE: *If tit's worth playing, it's worth writing down.*

:art: aquarium_not_aquarian.png
:width: 250px
:snark: An aquarium not an aquarian
:artist: Imagestoks 
:date: 2017
:license: Copyright Imagestoks 2015
:description: Drawing of a space suit with fish swimming in the helmet.

include::ROOT:partial$articulate.adoc[]

== Anthro RP Type
The anthro RP type should reflect the referee's milieu.
The anthro type table is for inspiration only. 

include::ROOT:partial$CH11_Table_Anthro_RP_Anthro_Type.adoc[]

=== Anthro Subtypes
The anthro subtype should reflect the referee's milieu.
The anthro subtype table is for inspiration only. 

Anthro subtypes are phenotypical, not scientific.
Anthros are appearance only and are faithful to mundane terran science.

Non-descript anthro types are also called mutts. 
A canine mutt is a canine, but no more distinct than that.

include::ROOT:partial$CH11_Table_Anthro_RP_Anthro_Type_Subs.adoc[]

.source links for anthro subtypes
* https://en.wikipedia.org/wiki/List_of_fish_common_names[Aquarian]
* https://en.wikipedia.org/wiki/List_of_dog_breeds[Canine]
* https://en.wikipedia.org/wiki/List_of_horse_breeds[Equine]
* https://en.wikipedia.org/wiki/Ungulate[Equine]
* https://en.wikipedia.org/wiki/Felidae[Feline]
* https://en.wikipedia.org/wiki/Reptile[Reptilian]
* https://en.wikipedia.org/wiki/Rodent[Rodentia]
* https://en.wikipedia.org/wiki/Bear[Ursidae]

=== Anthro RP Size
Use this single look-up table to create the anthro's hite and wate. 
For a refresher on calculating hite and wate jump to xref::CH04_Anthros_Size.adoc[Anthro Size,window=_blank].
To choose specific sizes like obese, skinny tall or short, jump to <<_modifications,Modifications>>.

include::ROOT:partial$CH11_Table_Anthro_RP_Hite_and_Wate.adoc[]

=== Anthro RP Age
Most often, the lifespan category is enough of a descriptor for the referee persona.
If the story needs an exact age, EXP has a table that has you covered.

include::ROOT:partial$CH11_Table_Anthro_RP_Lifespan_Category.adoc[]

include::ROOT:partial$CH11_Table_Anthro_RP_Age.adoc[]

== Anthro RP Attributes
Referee persona attributes are slightly better than player persona attributes and do not affect the persona's anthro type or vocation.
The referee generates initial attributes for the referee persona using the attributes table below.
The attributes are then modified to reflect the anthro type and vocation.
To choose descriptive attributes like slow, weak, or dumb jump to <<_modifications,Modifications>>.

include::ROOT:partial$CH11_Table_Anthro_RP_Attributes.adoc[]

=== Anthro RP Hit Points
A referee persona's Hit Points (HPS) maximum is determined the same as any other anthro persona.
For more information about anthro hit points jump xref:i-roll_playing_rules:CH04_Anthros_HPS.adoc[here,window=_blank].

==== HPS Maximum
include::CH04_Anthros_HPS.adoc[tag=Anthro_HPS]

==== Damage System Shock
include::CH04_Anthros_HPS.adoc[tag=Anthro_DSS]

==== Anthro RP Recovery
include::CH04_Anthros_HPS.adoc[tag=Anthro_REC]

=== Anthro Type Attribute Corrections
For RPs, attributes do not select the anthro type.
The attributes are modified to reflect the anthro type.
Attributes are never corrected down. 
However, if the referee needs a clumsy feline, she can achieve this at <<_modifications,Modifications>>

include::ROOT:partial$CH11_Table_Anthro_RP_Attribute_Correction_Type.adoc[]

== Anthro RP Movement Rate
Movement rate is dependent on DEX and represented in hexes per unit.
If the referee needs a slow or fast RP, this is modified at <<_modifications,Modifications>>

include::ROOT:partial$CH03_Table_Dexterity_and_Movement_Rate.adoc[]

== Anthro RP Armour Rating
Armour rating is adjusted using DEX.
// this in include from Anthro AR
include::CH04_Anthros_AR.adoc[lines=3..20]

== Anthro RP Wate allowance
The better the PSTR, the more she can lift.

include::ROOT:partial$CH03_Table_Physical_Strength_and_Wate_Allowance_(kg).adoc[]

== Anthro RP Mutations
Referee personas mutate the same as other personas. 
The referee can push for mutations by doubling the chance.
The table should be used as a guide if mutations are to be assigned.
Pure Strains are not vessels for zany mutations.
Insectoids rarely get physical mutations.
Keep in mind that some mutations are campaign changers and should be appropriately rare.

include::ROOT:partial$CH04_Table_anthro_mutations.adoc[]

== Anthro RP EXPS Level
Generate an experience level for every anthro RP.
Anthros have vocations, and the EXPS level can be their most important roll.
EXPS level impacts how many artifacts and skills the RP gets.

include::ROOT:partial$CH11_Table_Referee_Persona_Level.adoc[]

== Anthro RP Vocation
All anthros get a vocation. 
The referee should choose the vocation that best suits the needs of the story and milieu.

include::ROOT:partial$CH11_Table_Referee_Persona_Class.adoc[]

=== Vocation Attribute Correction
RP attributes do not select the persona's vocation type.
The attributes are modified to reflect the vocation type.
Attributes are never corrected down. 
However, if the referee needs a clumsy spie, she can achieve this at <<_modifications,Modifications>>

include::ROOT:partial$CH11_Table_Referee_Persona__Vocation_Supercharge.adoc[]

== Anthro RP Equipment
Referee personas carry equipment.
They have food, survival equipment, funds, and toys.
RPs get one TOYs roll for every experience level.

=== Mundane Equipment
Referee personas usually have what is necessary to survive in the local terrain.
The persona's survival equipment will vary with the terrain and the referee's milieu.

xref:i-roll_playing_rules:CH24_Mundane_Equipment.adoc[Mundane Equipment]

=== TOYs
Toys are technological devices that behave like magical devices.
If a referee persona needs a particular technological device, the referee will add it to the persona.
The referee may limit  RP equipment to maintain game balance.

Higher-level RPs will have successfully identified most of their toys.
An RP may also have an unidentified technological toy.
An unidentified toy is an artifact.
A lower-level RP is more likely to be carrying around an artifact.

.*Referee Persona TOYs*
* one roll on TOY table per EXPS Level
* vocation limits do not apply
* space vehicle, robot or vehicle limits do not apply
* treasure is accumulated but does not count as roll

include::ROOT:partial$CH41_Table_TOY_Type.adoc[]

== Anthro RP Combat Table
The combat table keeps track of the persona's combat skills and increases with EXPS level.
The referee need not calculate a complete combat table for cannon fodder or canon fodder referee personas.
Canonical referee personas need a full combat table calculated.
For general info about combat tables, jump to xref:i-roll_playing_rules:CH09_Combat_Tables.adoc[Combat Tables,window=_blank] in tactical combat.
For detailed info about the calculations below, jump to xref:i-roll_playing_rules:CH04_Anthros_CT.adoc[Anthro combat table,window=_blank].

A second level spie has the following attributes: AWE 12 CHA 11 CON 12 DEX 10 INT 12 MSTR 14 and PSTR 16.

include::ROOT:partial$CH04_Table_Anthro_CT_Xample.adoc[]

== Anthro RP Combat Ratio
// This is combat ratio boilerplate and appears in robots and aliens also

// tag::Combat_Ratio[]
Combat ratio is how tough the persona is.
The Combat Ratio is a numerical measure of how dangerous the RP is in combat.
The CR is used to determine EXPS value and number of attackers in the Roll Playing Rules.
If you are using the Role Playing Rules you can skip this section.

The higher the combat ratio the more powerful the adversary is in combat.
The Combat Ratio number equals how many first level anthro personas are needed for a fair fight.
A CR of 20 would indicate a very dangerous opponent in combat.
20 first level anthros would be required for a fair fight.
A Combat Ratio of 1/10 would represents a weaker opponent.
A first level anthro could fight 20 of the RPs and it would still be a fair fight.

Combat ratio is a measure of the referee persona's strength in combat.
It does not automatically indicate the number of RP's that show up every time.
The number of RPs present is determined by the culture, resources and story of the milieu.

An RP's CR determines the Combat EXPS earned when the RP is defeated in combat.

=== Calculating a Combat Ratio
. RPs initial CR is 1
. Add all the Pluses to the CR
. Multiply all the Times to the CR

.CR = (1 + all Pluses) * all Times
****
An RP with a Plus 1, Plus 4, Plus 2, Times 1.25, and Times 2.0 +
(1 + 1 + 4 + 2) * 1.25 * 2.0 = 20
****

// end::Combat_Ratio[]

=== Anthro RP Combat Ratio Adjustments
Anthro RP Combat Ratio is tricky to calculate because anthros are soggy bags of mostly water.
However their weapons and vocations can make them the most dangerous RPs in the game.

When preparing an anthropomorphs combat ratio, the referee should try to take into account all the equipment that the RP has access to.
This means that considerable time may have to be spent in the toy section before the combat ratio can be calculated.
Experienced referees will find that the combat ratio is not needed for estimating equivalent combat conditions but more useful in calculating the RPs experience point value which includes EXPS for encounters other than combative ones.

include::ROOT:partial$CH11_Table_RP_CR_Anthro.adoc[]

// general CR adjustments list of tables.
// heading is === for each table
include::ROOT:partial$CH11_RP_CR_General.adoc[]

== Anthro RP Role Playing 
The first half of referee persona creation involves much dice rolling and data collection.
Much of the data collected is needed for Roll Playing Rules. 
For those using the Role Playing Rules much of the data can be ignored, and the results recorded.
This section is a framework. 
The referee may choose the descriptive elements or roll them randomly.
Little or none of the information in this section affects the power of the persona.
However it does affect the story of the persona. 

NOTE: *These rolls and tables are an aid to creativity. Not a replacement for creativity.*

Use this section as a framework to for creating referee personas that have backstory and plans. 

* *RP ROLE PLAYING (Fun)*
. <<_anthro_rp_story,Story>>
.. Origin
.. Presence
.. Goal
.. Personality
. <<_anthro_rp_appearane,Appearance>>
.. Clothing
.. Hygiene
.. Gender
. <<_anthro_rp_beliefs,Beliefs>>
.. Religious
.. Political
.. Philosophical
. <<_modifications,Modifications>>
.. attributes
.. size
.. age
. <<_anthro_rp_name,Name>>

== Anthro RP Story
Everything has a story.
The depth of the story depends on the referee persona's relevance.
The amount of backstory collected is determined by the relevance of the persona. 
Cannon fodder have no back story. 
Canon RPs have all the back story possible.
The backstory for a referee persona must be massaged to fit into the milieu of the story.
The Trinity of the RP (origin, presence, and goal) is usually predetermined by the referee.

Referee personas benefit from a personality, origin, presence, and goal.
Which of these is the most important is decided by the referee.

=== Origin
Vishna Shraloor is a referee persona with death field generation (a mental mutation).
She matured not knowing that this lethal power was within her.
She grew up through a series of profound personal tragedies: the death of her parents, the death of teachers, the death of mourning relatives, the death of her playmates, the death of social workers, and the death of foster parents.
Many of these deaths may have been caused by her misunderstood mental ability.
That is her sad origin.

include::ROOT:partial$CH11_Table_Referee_Persona_Origin.adoc[]

=== Presence
Vishna's presence is one of a lonely unhappy persona who constantly associates with people she does not like because the people around her tend to die frequently.
Her profession is that of an orbital satellite repair person, a solitary job for certain.
She has chosen to hang around with the expedition because she does not particularly like them much.
This is her presence.

include::ROOT:partial$CH11_Table_Referee_Persona_Presence.adoc[]

=== Goal
Ms. Shraloor's goals are varied.
She would like to destroy the society that has rejected her so totally and she sees the expeditions mentality as something that she can exploit to this end.
If an expedition member should happen to befriend her, show her the nature of her mutation, and nurse her through the subsequent guilt, she may follow another path and desire to help the society that continued to reach out to her despite their extreme risk.
These are her potential goals.

include::ROOT:partial$CH11_Table_Referee_Persona_Goal.adoc[]

=== Personality
The referee is expected to play up these personality traits whenever possible.
Extroverted personality traits are NOT irrational.
They are just obvious.
A diplomatic RP will *not* try to negotiate with a heavy combot.
She will run away.
She may intercede between player persona arguments about loot distribution.

include::ROOT:partial$CH11_Table_Referee_Persona_Extroverted_Personality_Trait.adoc[]

==== Introverted
The Introverted Personality Sub-table indicates subtle personality traits.
These are not immediately obvious to the players.
An introverted personality trait may influence a "behind the ref shield" decision. 

include::ROOT:partial$CH11_Table_Introverted_Personality_Trait.adoc[]

==== Insane
The insane subset of personality traits represent an illness that impedes the persona's life.
None of them are specific diagnoses from the DSM, but strong decision influencers.
Insane personality traits may be very forward and obvious to the players.
Insane personality traits hold greater influence on the RP's decisions.
Extroverted and introverted personality traits don't put the persona in harms way.
Insane personality traits can make for bad decisions in combat. 
These are the kind of traits that will over ride the better, often safer, decision.
Insane personality traits can appear in completely unexpected situations, endangering the referee persona and the expedition.

NOTE: *Insanity is not played as a disease but as a decision influencer.*

If the RP is here from the Extroverted Personality Trait Table then the insanity is overt.
If the RP is here from the Introverted Personality Trait Table then insanity hidden.

include::ROOT:partial$CH11_Table_Insane_Referee_Persona_Personality_Traits.adoc[]

== Anthro RP Appearance
An RPs appearance is divided into three elements: clothing, hygiene and gender.
All of them are optional.

=== Clothing
Clothing is appearance only.
Clothing does not represent the culture, gender, occupation or personality of the RP.
The clothing is used to identify the dress choices made.
It is possible for a RP to change up their clothing as the referee sees fit. 
An RP may have several favorite styles and may even combine them in some random arrangement.
If the referee has time she could generate a different style for different clothing elements.
The shoes may be punk rock but the hair do renaissance. 

include::ROOT:partial$CH11_Table_Referee_Persona_Dress.adoc[]

=== Hygiene
Hygiene is a general habit that the persona exhibits.
Hygiene does not influence charisma, social standing or performance rolls.

While variable depending on the scenario the RP tends to ebb back to the hygiene description.
A habitually immaculate RP that fell in the mud would look like someone who fell into mud.
A habitually filthy spie would not arrive un-groomed at an aristocratic function.
The immaculate RP would clean herself off sooner, and better, than the filthy RP

include::ROOT:partial$CH11_Table_Referee_Persona_Hygiene.adoc[]

=== Gender
Gender represents appearance only.
Gender does not represent genetics, sexuality, reproduction, or employment.
Politics of gender are up the the referee and players. 

include::ROOT:partial$CH11_Table_RP_Gender.adoc[]

== Anthro RP Beliefs
Beliefs are purely cerebral elements of the referee persona.
They are not nearly as entrenched as personality or hygiene.
Referee personas may talk the talk about a belief, but how devout they are is variable.
RP beliefs are what the persona would like to be rather than what they actually are.

include::ROOT:partial$CH11_Table_RP_Beliefs.adoc[]

=== Religious Belief
The list here describes the structure of the religion and does not list existing human religions.
The nomenclature, structure, hypocrisy, and corruption level is left to the referee and her milieu.

include::ROOT:partial$CH11_Table_Referee_Persona_Religious_Belief.adoc[]

=== Political Belief
The list here describes the structure of the politics and does not list existing human parties.
The nomenclature, structure, hypocrisy, and corruption level is left to the referee and her milieu.

include::ROOT:partial$CH11_Table_Referee_Persona_Political_Belief.adoc[]

=== Philosophical Belief
Some real.
Some silly.
All futile mental exercises in futility. 

include::ROOT:partial$CH11_Table_Referee_Persona_Philosophical_Belief.adoc[]

== Modifications
Descriptors that also change attributes or data elements of the referee persona.

include::ROOT:partial$CH11_Table_Anthro_RP_Modifiers.adoc[]

== Anthro RP Name
Anthro names follow standard role-playing game nomenclature. 
Each anthro will usually have a given name and a surname.
Both the given name and surname are created by the player.
The anthro naming structure is most familiar naming structure.

.example persona names
* A mechanic - Hans Tinker
* A mercenary - Hans Grenade
* A nothing - Hans Ophmistuph
