= Time and Movement

This section is devoted to non-combat time and non-combat movement.
Time and movement in tactical combat are particular and consume real-time minutes.

When using tactical combat, time takes place in 2-second chunks called units and movement is recorded using tokens and hexagon covered mats.
This meticulous time and space keeping is part and parcel of the tactical combat system.
Half a minute of game time could take hours of real-time to work through.

Non-combat time and movement are entirely the opposite.
The expedition could have a month of game time pass by in an instant of real-time.
A few months of space travel could pass as quickly as the bowl of chips across the game table.

When persona lives are not on the line, game time passes as a convenience.
What gets accomplished is monitored qualitatively.
A research team could try to upgrade a vehicle system.
A nomad could spend time befriending and training a new alien friend.
A datalyzer could sum ten thousand prime numbers to the power of eleven. 
A mercenary could heal her injuries and return her HPS Total to HPS Max.
Any of these things could take place in an instant with a single Task Roll.

== Unnecessary Time Table

include::ROOT:partial$CH12_Table_Time_Components.adoc[]
