= Combat Time

[quote]
____
Time keeps everything from happening at once.
____

Combat time is entirely different from regular role-playing time.
Personas can travel great distances in the blink of an eye. 
Players can repair a weapon with a roll of the dice.
The expedition could hang out for a month while a persona heals.
An instant of mundane time can equal days, months and occasionally years for personas.

Combat time is the opposite. 
Everything slows down in combat time. 
In combat time, seconds can take minutes of actual time to work through.
Consider a persona detaching a boomerang from her while diving through the fog into a moving space vehicle. 
Her player can describe this plan in seconds. 
However, making the (un)necessary rolls determining success or failure could take minutes. 

This meticulous attention to faux detail is the absolute core of the tactical combat system. 
Tactical combat time and movement require a https://en.wikipedia.org/wiki/Hex_map[hexagon surface,window=_blank] and https://en.wikipedia.org/wiki/Miniature_model_(gaming)[tokens,window=_blank].
If this kind of detail seems obsessive, a xref:ii-role_playing_rules:CH26_Theatrical_Combat.adoc[Theatrical Combat,window=_blank] exists, which sheds dice, minis, and arithmetic.


== When Does It Start
Combat time starts when the referee or players decide so.
The hex map rolls out, the minis throw down, and personas' lives are on the line.
Once the referee decides that combat is underway, combat time is the first step.
Combat time and movement can activate whenever a persona's life is on the line.

[quote]
____
*Finally, a unit of measure with the name unit.*
____

== Combat Unit
The unit of time employed in combat is a call a unit.
In the EXP world, a unit is 2 seconds. 
Units only appear in combat time.
For the players in the mundane world, a combat unit could take 10 minutes to play out.
That means 2 seconds for the personas can take 10 minutes of mundane time for the players to work through.

For more details about non-combat time in EXP, jump to xref:i-roll_playing_rules:CH12_Time_Movement.adoc[Time and Movement,window=_blank].

:art: Unit_Size.png
:width: 450px
:snark: The length of your unit.
:artist: HM, Wikimedia
:date: 2021
:license: CC BY-SA 4.0
:description: Stopwatch with the first two seconds identified by arrows.

include::ROOT:partial$articulate.adoc[]

== When Is My Turn?
The unit is the closest thing to a turn that exists in tactical combat.
Every persona gets to act during every unit of combat time. 
Some personas will run, some will attack, others will run and attack. 
Running is represented as tokens moving on the hex mat.
Attacking requires checking the line of sight, consulting a combat table, rolling dice, and chatting about ball sports.

The order in which players get their turns is not decided by how they are seated at the table.
In combat, the order of turns depends on a complex system called initiative.
The initiative system incorporates dexterity, EXPS level, skills and luck to 
determine the turn order during combat.
For more information about this crucial element of tactical combat jump to 
xref:i-roll_playing_rules:CH33_Initiative.adoc[Initiative,window=_blank].

== Doing Things
An active persona can accomplish a lot in two seconds.
The persona could be attacking, picking a lock, or cowering in fear. 
The player would be making attack rolls, task rolls or hiding under the game table.
Players push their personas to the limit of time and space.
In the end, there is only so much that can get done in two seconds.
Referees will spend a fair amount of time reminding players of how short two seconds is.

=== Movement
Pure movement indicates the persona is doing nothing other than moving.
The persona could be running, crawling or cowering in fear.
The player moves the mini representing her persona on the hex mat.
Even pure movement can become complex when including terrain, barriers and movement types.
For details of tactical combat movement jump to xref:i-roll_playing_rules:CH12_Combat_Movement.adoc[Combat Movement,window=_blank].

NOTE: *Attacking is the most common action in combat. There is no movement cost for attack rolls.*

=== Actions
Actions can be completed within the combat unit and have a movement rate cost.
If the total hex cost of actions is greater than the persona's movement rate, then she must stop moving for that unit.

include::ROOT:partial$CH12_Table_Example_Actions.adoc[]

=== Activities
Activities are more complicated than actions, and they preclude both movement and actions. 
If a persona undertakes such an activity, they cannot participate in combat while doing so.

include::ROOT:partial$CH12_Table_Example_Activities.adoc[]
