= Combat Movement

Under non-combat circumstances, the players simply declare their movement.
Personas can move about a room or cover great distances with a few words.
For example, we take a cab to the zoo, and boom, the expedition is at the zoo.
Or we navigate to the Promulgator System. 
A month in stasis passes in an instant, and the role-playing begins again.

Movement during combat is decidedly the opposite of the above paragraph.
Persona movement and location are meticulously kept track of using a hex mat and tokens.
If a player wants her persona to move further away from an attacker, she physically moves her token on the hex mat.
The number of hexes the token can move depends on the persona's movement rate, terrain, and direction.

== When Does It Start?
Combat movement starts when the referee or players decide so.
The hex map rolls out, the minis throw down, and personas' lives are on the line.
Once the referee decides that combat is underway, combat movement is the first step.
Combat movement also activates when a persona needs to get somewhere fast, and their life is on the line.

[quote]
____
*A hex is not a spell. It is a 2-meter polygon.*
____

== Combat Distance
The unit of distance used in combat movement is the hex.
Hex is short for the word hexagon.
The https://en.wikipedia.org/wiki/Hexagon[hexagon,window=_blank] is a six-sided polygon of great beauty.
The scale of EXP's hexagon is 2 meters. 
In EXP, hexes are a unit of measure. 
Distances, the size of robots, aliens, and spaceships are in hexes.

:art: Hexagon_Scale.png
:width: 450px
:snark: Imperial anthro in metric hex.
:artist: HM, Wikimedia
:date: 2021
:license: CC BY-SA 4.0
:description: 2m hexagon compared to a 6 foot human.

include::ROOT:partial$articulate.adoc[]

Tactical combat movement requires a https://en.wikipedia.org/wiki/Hex_map[hexagon surface,window=_blank] and https://en.wikipedia.org/wiki/Miniature_model_(gaming)[tokens,window=_blank] to keep track of movement. 

== Combat Time
Each turn of combat in EXP is called a unit.
This time measurement is 2 seconds long.
For more details about time in EXP, jump to xref:i-roll_playing_rules:CH12_Combat_Time.adoc[Combat Time,window=_blank].

:art: Unit_Size.png
:width: 450px
:snark: The length of your unit.
:artist: HM, Wikimedia
:date: 2021
:license: CC BY-SA 4.0
:description: Stopwatch with the first seconds identified by arrows.

include::ROOT:partial$articulate.adoc[]

== Movement Rate
Each persona has a movement rate.
Robots, aliens, anthros, and vehicles all have movement rates.
The movement rate is a velocity measure.
The movement rate is the same as miles per hour or kilometres per hour.
For tactical combat, the movement rate is in hexes per unit.

=== Movement Rate Measurement
.hexes per unit = hexes / unit = h/u
****
The number of hexes the persona can move each unit (h/u or hu).
****
 
The persona's movement rate represents what she can get accomplished during a combat turn.
Most commonly, the player will use up all her movement rate to move around the hex map.
The player can use some of those hexes to accomplish simple actions, change direction or overcome terrain.

:art: Figure_Movement_Hexes.png
:width: 650px
:snark: Example token movement on hex sheet.
:artist: hexes pixabay, colours HM
:date: 2020
:license: CC BY-SA 4.0
:description: Diagram of hexagon sheet and sample movements.

include::ROOT:partial$articulate.adoc[]

Movement rates are equal between anthros, aliens, robots and vehicles.
One h/u equals one h/u regardless of locomotion type.
Flippers, feet, wheels, tracks or antigrav boots with the same movement rate move at equal speed.

== Movement Rate Adjustments
Movement adjustments are endless.
Only the most basic ones are covered here.
The more tactical and the more faux realism desired, the more movement adjustments the players use.

== To Move or Act
Movement rate represents the furthest a persona can move in one unit during combat.
During combat, players can move and make an attack roll without penalty.
So an anthro that moves five h/u per unit could move five hexes straight ahead and make an attack roll.
As soon as the persona deviates from this most simplistic move attack combination, there are penalties.
The player pays for these penalties in hexes.

For example, changing direction can cost one hex in movement. 
So an anthro that moves five h/u per unit could move four hexes, change direction and make an attack roll.
The more dramatic the direction change, the more hexes per unit are absorbed.

For example, catching an ammo pack costs two hexes of movement.
So an anthro that moves five h/u per unit could move three hexes, catch the ammo pack, and make an attack roll.

These movement penalties are cumulative.
So an anthro that moves five h/u per unit could move two hexes, catch the ammo pack, change direction and make an attack roll.
She may be getting a lot done, but she is not getting as far as before.

The movement cost for waist-deep water is four hexes per unit.
So changing direction, catching a watermelon, and firing her pistol in waist-deep water is not possible.
She needs seven hexes per unit when she only has five hexes per unit to spend.
Now the player must decide which is most important: the watermelon, changing direction, or moving. 

NOTE: *hexes per unit in tactical combat are similar to action points in other rule sets.*

.Hex costs and consequences 
. Changing direction
.. Running
.. Bolting
.. Hills
.. Acceleration
. Encumbrance
. Actions
. Terrain
. Jumping
. Diving
. Climbing
. Rolling
. Barrel Roll

== Changing Direction
Changing direction is the most straightforward and easily understood of all the movement adjustments.
There is no movement penalty for moving forward on stable terrain.
There is one hex cost per facet of change in direction.

.*Persona with a 6 h/u move*
. Straight ahead, move 6 hexes and attack.
. 180-degree pivot, move 3 hexes and attack.
. 360-degree switchback, move 0 hexes and attack

:art: Figure_Movement_Direction_Penalty.png
:width: 650px
:snark: Change orders are expensive.
:artist: hexes pixabay, colours HM
:date: 2020
:license: CC BY-SA 4.0
:description: Diamgram of hexagon sheet showing penalties for direction changes.

include::ROOT:partial$articulate.adoc[]

== Running
A persona's movement rate represents what she can accomplish per unit of combat.
If a player chooses, she can have her persona ditch combat and run away.
Running away is also called a rapid tactical withdrawal.
A running persona cannot make attack rolls or carry out actions.
They can only run.
The movement benefit is +50%.
This benefit is in hexes of distance only. 
Running does not allow for attack rolls or actions.

.Tactical Withdrawal (Running)
* free or unencumbered (cannot carry a watermelon, for example)
* benefit is hexes of distance only
* no attack rolls
* no actions other than running 

For example, an anthro persona with a move of 6 h/u is carrying a watermelon.
If the player decides on a rapid tactical withdrawal, the persona may drop the watermelon and move at 9 h/u.
Running does not guarantee the safety of a persona in any way.

Robots move at maximum efficiency and cannot increase movement rate by running.
Only aliens and anthros have the flight response that allows them to make a rapid tactical withdrawal.

== Bolting
A persona's movement rate represents what she can accomplish per unit of combat.
If a player chooses, she can have her persona ditch combat and run away.
Bolting cannot be mistaken for a tactical withdrawal. 
Bolting represents a mindless panicked straight-line run.
A bolting persona cannot make attack rolls or carry out actions.
They can only run.
The movement benefit is +100%.
This benefit is in hexes of distance only.
Bolting does not allow for attack rolls or actions.

.Panicked Rout (Bolting)
* free from encumbrance (will drop weapons and shed armour or backpacks)
* benefit is hexes of distance only
* straight line only
* absorbs no tactical information
* no attack rolls
* no actions other than running 
* get +2 hexes for panicked screaming.

For example, an anthro persona with a move of 6 h/u sees a heavy combot eviscerate the rest of her expedition (in one unit).
The player decides her persona should run screaming from the combat area. 
The persona would drop her weapon, her backpack, tear off her armour, and run in a straight line screaming.
Her movement rate bolting would be 14 h/u. 
Double for routing and +2 for panicked screaming. 

Robots move at maximum efficiency and cannot increase movement rate by running.
Only aliens and anthros have the flight response that allows them to make a rapid tactical withdrawal.
Bolting does not guarantee the safety of a persona in any way.

== Up Hills
This guide refers to hills on a hex map and not climbing up walls. 
Personas moving uphill suffer a one hex cost per hex rise in the terrain.
If a persona climbed two hexes in altitude over two hexes of distance, she would face a two hex cost. 
If the persona's move is decreased to zero by the rise in the terrain, she may stop and make an attack roll or start to climb.
Usually, the referee will assign the hex cost penalty to a specific hill on the hex mat.
However, those who enjoy arithmetic can use the calculation below.

=== Hex cost for uphill travel
.slope = rise over run. Cost = run in hexes
****
If the slope is 45% and the persona wants to travel ten hexes, they will have a ten hex move cost. 
****

So walking up that hill will allow the persona to keep making attack rolls and possibly other actions. 
Running up that hill will only allow you to make an attack roll or just run up the hill.

== Down Hills
This guide refers to hills on a hex map and not jumping off cliffs. 
Personas can move down hills safely as long as they move slower than their movement rate. 
If a persona wants a speed boost, she may add the rise she travels through to her movement rate.
The hex distance bonus and does not add any attacks or actions. 
There is also a chance that the persona will faceplant due to the added speed.

== Acceleration
Acceleration is a change in velocity and can represent speeding up or slowing down. 
There are no rules in tactical combat for acceleration.
Very fast vehicles and robots may have some limitations speeding up. 
There are no getting up to speed limitations on personas in combat.

A persona that is running or bolting may crash into something.
Or a robot or vehicle making too tight a turn may risk uncontrolled contact with the terrain.
These considerations are left entirely up to the referee and players.
Remember to err on what makes for the best story.
If the debate becomes heated, this would be an excellent opportunity to use xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice,window=_blank]. 

== Encumbrance
Carrying too much junk slows you down in combat.

include::ROOT:partial$CH18_Table_Encumbrance_and_Movement.adoc[]

== Terrain
The surface of the land also influences movement in combat.
A persona can move faster over solid ground than through a knee-deep swamp.
The terrain surfaces covered here variations on typical environments.
Combat movement covers the mundane terrains.
For exotic terrains like zero gravity or exatmo, jump to  xref:i-roll_playing_rules:CH19_Terrain.adoc[Exotic Terrain,window=_blank].

:art: alien_spaceship_swamp.png
:width: 250px
:snark: Alien slogging through terrain.
:artist: Andrew Bre:chin
:date: 1990
:license: CC BY-SA 4.0
:description: Drawing of chicken legged alien walking through a swamp.

include::ROOT:partial$articulate.adoc[]

=== Foliage
The degree to which grass, plants fungus patches affect movement depends on the persona's size.
Tiny, Small, Medium, Large, and Gigantic personas can overcome specific foliage depths.
Anthro personas are Medium-sized.
Foliage movement costs affect aliens, robots and anthros equally.
Some aliens can fly over the foliage. 
Some robots can float over the foliage. 
Locomotion differences and foliage movement costs are up to referee and player debate.
If the debate becomes heated, this would be an excellent opportunity to use xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice,window=_blank]. 

include::ROOT:partial$CH12_Table_Foliage_Movement_Penalties.adoc[]

Regular grass is not a manicured lawn in suburbia. 
Suburban lawns are, at worst low grass.
The foliage table is for flora that could impede a persona's movement.

If a persona's movement rate drops to zero, they may make an attack roll or climb, but they cannot move.
If the result on the table is "climb," then the foliage is considered impassible. 

=== Liquids
Water, or any liquid substance, slows down personas is covered here/ 
Aliens with water movement rates are not affected by swimming and use their natural movement.
The liquid table applies to snow, sand, mud or Swedish retail ball pits. 
When Swim appears on the table, the persona can no longer push through the liquid.
They then must swim, sink or stick depending on the liquid.

include::ROOT:partial$CH12_Table_Liquids_Movement_Penalties.adoc[]

This table is anthropomorphically centred.
Ankle deep is our mundane human ankle deep. 
The measures of depth are related to a normal-sized anthro persona.
The table evolved to have these descriptive terms instead of heights.
Sadly we are not playing with aliens or robots at the table just yet. 

==== Swim or Climb 
Both the Foliage and Liquid Movement cost tables can stop the persona in their hex.
If the movement cost is greater than the persona's movement rate, then the persona is stopped.
If the table result is "climb" or "swim," then the persona is stopped.

With foliage, the *climb* result is straightforward or straight upward.
The persona can change direction or start climbing over the obstacle.
Climbing has its own <<_climbing,section below>>

With liquid or mud, the consequences are quite different. 
When a persona cannot wade through a puddle, they must swim or sink.
Unlike foliage, the referee must know how swimming affects the personas.
Is the current strong?
Is there an undertow?
Will the mud pull personas down?
How hard is the mud to get out from?
Do persona's know how to swim?
Can personas drown? 

==== Sink or Swim
Whether a persona sinks or swims depends heavily on the family type.
An alien that has a water movement rate is unaffected by deep liquids. 
An aquarian anthro can automatically swim. 
Other anthros may or may not swim. 
Check those xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice,window=_blank] if the player can't come up with a good back story.
Robots will automatically sink unless they have a water compensating locomotion type.

Those persons who can swim need only contend with wate encumbrance, currents, and sea monsters.
Only personas with evolved swimming abilities (aquarians and aliens) can make attack rolls while swimming.

The consequences of sinking are up to the referee.
Drowning is an unseemly way to force players to create new personas.
However, personas who cannot swim and are in the water are in trouble.
Water immersion will damage any robot lacking terrain or exatmo hardening.
A flailing anthro will have to shed armour, backpack and toys. 

Alien and anthros that cannot swim can flail about once they dump their equipment.
Flailing can move the persona to the next water hex if a PSTR roll is successful.
Robots do not flail. 
They simply sink. 

==== Mud
Muddy liquid could be mud, slime, cesspool, jello or any other dense liquid.
Mud uses the Liquid Movement Cost Table.
The thickness of the liquid increases its resistance and increases the movement cost by two levels.
So Knee-deep water functions as Waist deep mud.
An anthro persona (medium-sized) would have a four hex cost in mud versus water.
If their movement rate drops to zero, the persona is "stuck in the mud."
Tiny and Small personas would automatically be "stuck in the mud."

==== Sand
Packed sand is not a terrain obstacle. 
The sand described here is shifting, sinking swirling sand. 
The hex cost for moving through sand uses the Foliage Movement Cost Table.
To calculate the movement cost of sand, use foliage table, but increase the cost by two levels.
If the sand is the depth of normal hite foliage, it has the cost of tall hite foliage.
A medium-sized persona in normal hite sand has a two hex cost (tall foliage).
If the persona must 'climb' in the sand, they are stuck in place. 

==== Snow
Snow or other light particulate matter uses the Liquid Movement Cost Table.
To simulate snow, the referee uses the liquid movement cost and increases the cost by one level.
So Knee-deep snow has the movement cost of Leg deep water.
A medium-sized persona would have a three hex cost penalty in knee-deep snow.
If the persona must "swim" in the snow, they are stuck in a snowbank. 

=== Ice
Ice, or any frictionless surface, is a source of slippery fun for referees.
Unless the persona has special tires, claws or skills, the frictionless surface will wreak havoc.
Ice will offer a 1d4-1 hex cost for all personas for every combat unit on the ice.
Some personas will be unable to move on ice and use their entire movement rate to avoid falling over.

Whether ice over liquid can support larger personas must be decided by the referee in advance.
If the cracking ice is an off the cuff terrain modification the xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice,window=_blank] come into play.

== Movement and Actions
Some actions take less than a unit but still require attention from the persona.
These actions result in minor movement rate adjustments.
The table is included here for convenience.

NOTE: *There is no movement cost for an attack roll.*

include::ROOT:partial$CH12_Table_Example_Actions.adoc[]

== Actions That Stop Movement
The only action that is guaranteed to fit into the combat unit is an attack. 
Some things require too much attention for a persona to keep moving.
The persona can complete some actions within a unit.
Other actions require too much attention to either move or attack. 

include::ROOT:partial$CH12_Table_Example_Activities.adoc[]

=== Doors
Personas travelling at high speeds can move through *unlatched push doors* with only a two hex cost.
So a persona with a five h/u movement rate could go through an unlatched push door and move three hexes that unit.
Latched or pull doors will stop the persona completely.

=== Climbing
Vertical movement that does not involve flying, telekinesis or antigrav requires climbing. 
Personas engaged in climbing make far more predictable targets than otherwise.
Attack rolls on climbing targets gain bonuses.
Attack rolls made by climbing personas suffer penalties.

NOTE: *Under non-combat circumstances, personas just climb things.*

Robots do not climb. 
Alien flora and fauna do not climb. 
Tool using aliens and anthros may try their paws at climbing. 

==== Climbing, Free
Free climbing is free of ropes, pitons, and carabiners.
The referee determines if a surface can be free climbed. 
Free climbing requires all the persona's attention.
The player cannot combine free climbing with attack rolls or unrelated performance rolls.
Attack rolls made on free climbing personas enjoy a bonus of +666. 

Free climbing is slow and requires many attributes.
There are three steps to moving in a free climb.

.*Free Climbing Steps*
. Find the hold (AWE)
. Reach the hold (DEX)
. Move to the hold (PSTR)

If all rolls are successful, the persona moves 1-2 hexes towards their goal. 
This goal could be upwards or sideways, or downwards. 

The persona is at risk of falling if her player fails the DEX or PSTR rolls. 
The consequences of falling are up to the referee. 
The fall is harmless, but the sudden stop at the bottom inflicts 1d4 damage per hex of fall.

==== Climbing, Equipped
Equipped climbing uses ropes, pitons, and carabiners.
Setting up climbing equipment cannot happen during combat.
This section is if the personas are climbing and then get into combat.

Equipped climbing requires all the persona's attention.
The player cannot combine equipped climbing with attack rolls or unrelated performance rolls.
Attack rolls made on equipped climbing personas enjoy a bonus of +333. 
A persona can stop equipped climbing to make combat rolls or performance rolls.
When hanging around and shooting back, the player suffers a -180 attack roll penalty. 

There are a few steps to moving upwards in a free climb.

.*Equipped Climb Steps*
. Find the hold (AWE)
. Reach the hold (Easy DEX)
. Move to the hold (Easy PSTR)

If all rolls are successful, the persona moves 1-3 hexes towards their goal. 
This goal could be upwards or sideways, or downwards. 

Equipped climbers do not suffer the same fall risks as free climbers.
However, equipment damage or failure could lead to a date with gravity.

==== Climbing, Rope
For rope climbing, the referee must consider rope strength.
Personas climbing ropes cannot engage in any other actions other than climbing rope.

The persona can move up one hex per successful PSTR roll each unit. 
Targeting a persona climbing up a rope earns a +333 attack roll bonus.
The persona can move down 1-3 hexes per successful DEX roll each unit.
Targeting a persona climbing down a rope earns a +180 attack roll bonus.

A referee can consider a fall risk if the player fails one of the attribute rolls. 

==== Climbing, Ladder
Climbing by ladder requires no attribute rolls.
A persona may climb a ladder 1d2 hexes each unit.
A persona may descend a ladder 1d4 hexes each unit. 
Unless there are extenuating circumstances, the referee should allow personas to navigate ladders safely.
These rules only apply during combat, so the situation is likely dangerous enough already.


// tag::Combat_Movements[]
== Crawling
A persona can crawl along the ground to improve concealment or cover.
Crawling involves keeping one's body unnaturally close to the ground and compromises movement rate.
Crawling personas move at 1/4 of their regular movement rate. 
So a persona who normally can move eight h/u can crawl at two h/u.
Crawling also impedes the actions a person can undertake.

Crawling gives the persona an AR bonus of +125 to powered and none powered missile weapons.
So attack types B and C are penalized but Type A attacks get an attack bonus of +125. 

Robots cannot alter their locomotion type to gain a crawling AR bonus.  
Only medium-sized or smaller organic personas can use this bonus. 

== Crouching
A persona can crouch while moving to improve concealment or cover.
Crouching involves lowering one's body closer to the ground and compromises movement rate.
Crouching personas move at 1/2 their regular movement rate. 
So a persona who normally can move six h/u can crouch at three h/u.
Crouching also impedes the actions a person can undertake.

Crouching gives the persona an AR bonus of +60 vs powered and none powered missile weapons.
So attack types B and C are penalized but Type A attacks get an attack bonus of +125. 

Robots cannot alter their locomotion type to gain any AR bonus. 
Only medium-sized or smaller organic personas can use this bonus. 

== Rolling
Rolling allows the persona to stay undercover and move a bit faster.
Rolling personas can move at 1/3 their movement rate (rounded down).
A rolling persona with a seven h/u move can roll at two h/u.

Rolling gives the persona an AR bonus of +125 to powered and non-powered missile weapons.
So attack types B and C are penalized but Type A attacks get an attack bonus of +125. 

While rolling, a persona cannot make attack rolls or performance rolls.
The persona can only make roll rolls.

Robots cannot alter their locomotion type to gain any AR bonus. 
Only medium-sized or smaller organic personas can use this bonus. 
// end::Combat_Movements[]


== Barrel Rolling
Once during combat, a persona can make a barrel roll if they scream barrel roll.
The barrel roll does not impair the persona in any way during the unit.
A barrel offers no bonus to the persona in any way.
Anthros, alien tool users and robots can perform a barrel roll once during a combat session. 

== Diving
A dive is a headfirst horizontal torpedo jump that can propel the persona beyond her movement allowance.
Upon finishing her unit's movement, a persona can dive an additional one hex for every six points of PSTR.
Diving can launch her through windows, into doorways, across tables, off cliffs, etc.
Diving renders a persona inactive for the next unit.

== Jumping
A jump is a brief, self-propelled aerial excursion governed mainly by gravity after the point of liftoff.
A jump brings a persona to a complete stop at its end.
No attribute roll is needed to jump successfully.
However, repeated jumping to subvert movement rates should be discouraged.

Jumping here is for jumping during tactical combat. 
Under non-combat circumstances getting around barriers and over obstacles is entirely different. 

Horizontal jumps have no hite and are just for distance.
Vertical jumps get personas over impasses. 
A failed vertical jump leaves the persona crumpled at the base of the barrier.

. Horizontal jump, running start yields one hex per PSTR / 7
. Horizontal jump from standing yields one hex per PSTR / 15
. Vertical jump, half persona hite, normal DEX roll required
. Vertical jump, persona hite, difficult DEX roll required

Robots do not jump. 
Flora and fauna may jump over natural obstructions in their habitat.
