= Combat Time

[quote]
____
Time keeps everything from happening at once.
____

Under normal circumstances time in EXP is purely for the convenience of the players.
The expedition can travel great distances, including interstellar ones, in the blink of an eye.
Complex tasks,undertaken by research teams, can be completed with a few dice rolls.
The expedition could hang out for a month while a persona heals.
An few moments of our mundane time can equal days, months and occasionally years for our personas.
Combat time is completely different from this convenient non-combat time.

Tactical combat turns this concept of convenient time on its head. 
In combat time, seconds of game time can take minutes of mundane time to work through.
During tactical combat persona lives are on the line and a complex collection of rules come into play.

A player wants her persona to throw a boomerang, while driving a vehicle down a smoke covered road.
This kind of action is successfully carried out multiple times in every action movie.
The player can describe this action in a few seconds. 
However the tactical combat system would require quite a few steps to make this work.
The (un)necessary rolls determining success or failure of the boomerang toss could take minutes. 

.For Example
. Initiative roll
. Attack Roll
. Attack Roll driving modifiers
. Attack Roll smoke modifiers
. Driving Roll to maintain vehicle control
. Driving Roll modifiers for the smokey obfuscation 
. Driving Roll modifiers for doing silly things while driving
. Reflect these actions on a https://en.wikipedia.org/wiki/Hex_map[hex mat,window=_blank] using https://t.ly/Clfy-[minis,windows=_blank]
. Consider the actions of other personas 

// todo link shortener needed for https://en.wikipedia.org/wiki/Miniature_model_(gaming) used https://t.ly/Clfy-

This meticulous attention to faux detail is the absolute core of the tactical combat system.
However, the players only need to employ those rules which make sense and are fun.

== When Does Combat Time Start
Combat time starts when the referee or players decide so.
The hex mat rolls out, the minis are thrown down, and persona lives are on the line.
Once the table decides that combat is underway, combat time is the first step.
Combat time and movement can activate whenever a persona's life is on the line.

[quote]
____
*Finally, a unit of measure with the name unit.*
____

== Combat Unit
The unit of time employed in combat is a call a unit.
In the EXP world, a unit is 2 seconds. 
Units only appear in combat time.
For the players in the mundane world, a combat unit could take 10 minutes to play out.
That means 2 seconds for the personas can take 10 minutes of mundane time for the players to work through.

For more details about non-combat time in EXP, jump to xref:i-roll_playing_rules:CH12_Time_Movement.adoc[Time and Movement,window=_blank].

:art: Unit_Size.png
:width: 450px
:snark: The length of your unit.
:artist: HM, Wikimedia
:date: 2021
:license: CC BY-SA 4.0
:description: Stopwatch with the first two seconds identified by arrows.

include::ROOT:partial$articulate.adoc[]

== When Is My Turn?
The unit is the closest thing to a turn that exists in tactical combat.
Every persona gets to act during every unit of combat time. 
Some personas will run, some will attack, others will run and attack. 
Running is represented as tokens moving on the hex mat.
Attacking requires checking the line of sight, consulting a combat table, rolling dice, and chatting about ball sports.

The order in which players get their turns is not decided by how they are seated at the table.
In combat, the order of turns depends on a complex system called initiative.
The initiative system incorporates Dexterity, EXPS level, skills and luck to 
determine the turn order during combat.
For more information about this crucial element of tactical combat jump to 
xref:i-roll_playing_rules:CH33_Initiative.adoc[Initiative,window=_blank].

== Doing Things
An active persona can accomplish a lot in two seconds.
The persona could be attacking, picking a lock, or cowering in fear. 
The player would be making attack rolls, task rolls or hiding under the game table.
Players push their personas to the limit of time and space.
In the end, there is only so much that can get done in two seconds.
Referees will spend a fair amount of time reminding players of how short two seconds is.

=== Movement
Pure movement indicates the persona is doing nothing other than moving.
The persona could be running, crawling or cowering in fear.
The player moves the mini representing her persona on the hex mat.
Even pure movement can become complex when including terrain, barriers and movement types.
For details of tactical combat movement jump to xref:i-roll_playing_rules:CH12_Combat_Movement.adoc[Combat Movement,window=_blank].

NOTE: *Attacking is the most common action in combat. There is no movement cost for attack rolls.*

=== Actions
Actions can be completed within the combat unit and have a movement rate cost.
If the total hex cost of actions is greater than the persona's movement rate, then she must stop moving for that unit.

include::ROOT:partial$CH12_Table_Example_Actions.adoc[]

=== Activities
Activities are more complicated than actions, and they preclude both movement and actions. 
If a persona undertakes such an activity, they cannot participate in combat while doing so.

include::ROOT:partial$CH12_Table_Example_Activities.adoc[]
