= Performance Rolls

Performance rolls are made by players when their persona is attempting a maneuver.
The performance roll is a check for success. 
If the player wins the performance roll, her persona has succeeded at the maneuver.

Some maneuvers are mundane, like trying to repair a vehicle engine.
Some maneuvers are pure sciency fiction, like strapping a grommet-sized oscillating refractometer onto a Frederickson di-collating time re-modulator.
Maneuvers include vocation skills, abilities and gifts as well. 
There is an entire section devoted to the maneuvering maneuvers called xref:i-roll_playing_rules:CH17_Driving.adoc[Driving,window=_blank].

The more complex the maneuver, the more difficult it is for the persona to succeed.
Every maneuver has its degree of difficulty (DD).
The more complex the maneuver, the higher the degree of difficulty, and the higher the DD, the higher the performance roll required to succeed.

:art: monkey_box_anger.png
:width: 250px
:snark: Failure makes Rage.
:artist: Andrew Brechin
:date: 1990
:license: CC BY-SA 4.0
:description: Drawing of humanoid baboon getting mad at technological box.

include::ROOT:partial$articulate.adoc[]

The player rolls a 1d100 to determine the success or failure of the maneuver. 
The player wants to roll high.
Sometimes a maneuver will be too difficult for the persona to complete on their own. 
<<_research_teams,Research Teams>> are crucial to completing complicated maneuvers.


NOTE: *The Performance Roll system replaces Performance Tables from previous versions.*

.*Steps To Peak Performance Rolls*
. <<_determine_skill_level,Determine Skill Score>>
. <<_determine_degree_of_difficulty,Determine Degree of Difficulty>>
. <<_determine_target_roll,Determine Target Roll>>
. <<_determine_bonuses,Determine Bonuses>>
. <<_roll_1d100,Determine 1d100 roll>>

== Determine Skill Score
The Skill Score is a combination of the persona's EXPS Level and her skills.
A persona can use her EXPS Level for any maneuver that fits within her vocation.
If the persona also has an applicable skill, she can add this to her skill score.
Persona's attempting maneuvers outside of their vocation have a skill score of zero.

=== Calculating Skill Score
.Skill Score = EXPS Level + Applicable Skill
****
A third-level biologist with Herbivore 2 would have a skill score of 5 studying herbivores.
****

== Determine Degree of Difficulty
The more complicated something is to do, the higher the Degree of Difficulty (DD).
Almost every maneuver has a degree of difficulty associated with it.
From the driving maneuver table driving straight ahead is DD 1.
The lowest DD possible is 1.
However, the DD can be so high that it is impossible to make the Performance Roll.
From the biologist skill table, cloning is a DD 42 maneuver. 
There is no upper limit to how high a DD can go.

If a maneuver does not exist or there is no assigned degree of difficulty, the players and referee must negotiate one.
The players and referee only need to agree on a qualitative term describing the difficulty of the maneuver.
A dice roll will randomly determine the actual value of the DD.

Let's consider a persona that wants to make some ice from water.
If there is a freezer, this maneuver should be automatic, but there may be some trivial interference.
So the referee and players agree that this is maneuver has a trivial difficulty.
If there is no freezer, and the expedition is on a hot planet where the water is full of sediment, the difficulty should be impossible or bizarre.

include::ROOT:partial$CH14_Table_DD.adoc[]

== Determine Target Roll
The target roll is the actual number that the player must roll higher than to win the performance roll.
The target roll is like the armour rating of a maneuver.
The player must roll equal to or higher than the target roll.
The higher the persona's skill score (EXPS level plus skills), the lower the target roll.
The higher the maneuver's degree of difficulty, the higher the target roll.

The target roll can be tabulated or calculated.
A tabulated target roll employs a table comparing the degree of difficulty to skill score. 
A calculated target roll employs simple maths to determine the target roll.
Very high skill scores and very high DDs require calculation.

xref:i-roll_playing_rules:page$CH14_Performance_Tables.adoc[tag=target_rolls]

// tag::target_rolls[]
=== Tabulated Target Roll
No calculations are required.
Compare DD to skill score to get the target roll.
For example, skill score 5 intersects with DD 5 to yield a target roll of 66.
The player must roll 66 or higher on a 1d100 to win her performance roll.
The higher the persona's skill score, the lower the player's target roll.
Very high skill scores and very high DDs exceed the Target Rolls Table's limits and require calculation.

include::ROOT:partial$CH14_Table_New_Performance.adoc[]

=== Calculated Target Roll
Players can calculate the target roll using some simple maths and a tiny table.
The higher the skill score, the greater the impact on the target roll.

A persona with no aptitude indicates that a persona is attempting a maneuver out of her vocation.
For example, a mercenary trying to identify an alien flower would have no aptitude. 

include::ROOT:partial$CH14_Table_Vocation_Level_Bonus.adoc[]

=== Target Roll Calculation
.Target Roll = 56 + (4 * DD) - (Skill Score * Multiplier)
****
DD 10 vs skill score 8 = 56 + (4 * 10) - (8 * 2) = 56 + 40 - 16 = 80 +
DD 6 vs skill score 11 = 56 + (4 * 6) - (11 * 3) = 56 + 24 - 33 = 47 +
DD 30 vs skill score 9 = 56 + (4 * 30) - (9 * 2) = 56 + 120 - 18 = 158 +
DD 2 vs skill score 18 = 56 + (4 * 2) - (18 *4) = 56 + 8 - 64 = -8
****
// end::target_rolls[]


== Determine Bonuses
The player adds bonuses to her 1d100 roll.
Bonuses often mean the difference between success and failure.
Bonuses can come from every which way.
Some TOYs give performance roll bonuses.
Some computers give performance roll bonuses.
Many referees will offer performance roll bonuses for good role-playing descriptions. 

:art: indiana_lizard.png
:width: 250px
:snark: This gonna be easy.
:artist: Patrick Redding
:date: 1990
:license: CC BY-SA 4.0
:description: Drawing of humanoid about to grab glowing treasure artifact.

include::ROOT:partial$articulate.adoc[]

=== Attribute Bonuses
The most common bonuses are vocation attribute bonuses.
If the maneuver fits into the vocation's aptitude, the player can add an attribute to the 1d100 roll.
For combat maneuvers, mercenaries can add their PSTR.
For knowledge-based maneuvers, biologists can add their INT. 

include::ROOT:partial$CH14_Table_Vocation_Bonus.adoc[]

=== Role Playing Bonuses
The more role-playing is integrated into the roll playing system, the more fun the play is.
Role-playing bonuses for performance rolls incentivizes fun descriptions from the players. 
The following are examples of player descriptions that should earn performance roll bonuses.
 “I’m going to leaf through my notes here and try to identify this bizarre creature.” 
Or “I summon all the forces of evil beneath me, as I try to apply pressure to this weakling altruist.”
Or “Taking my favourite tools from my mechanical kit, I proceed to repair this damaged bicycle.”
Or “I  calmly stalk silently past the sleeping sentry.”

:art: vet_big_hat_idea_desat.png
:width: 250px
:snark: I have an idea.
:artist: StudioStoks, mod HM
:date: 2010
:license: StudioStoks Stock Art.
:description: Drawing of human medical woman getting a brilliant idea.

include::ROOT:partial$articulate.adoc[]

The role-playing bonuses should be small since role-playing has its benefit.
A good description could get a 1d4 bonus.
A description that rocks all the players may get a 1d10 bonus. 
Small bonuses that lead to success generate quite a bit of excitement.

== Roll 1d100
The player rolls the 1d100, adds in the bonuses and hopes to beat the target roll. 
Any roll equal to or higher than the target roll is a success.
Any roll less than the target roll is a failure.

NOTE: The player rolls a 1d100, also called a deci-die, in her attempt to win her performance roll.

:art: performance_roll_mecha_hammer.png
:width: 250px
:snark: Delicate repairs underway.
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of small human hammering repairs on top of giant mech suit.

include::ROOT:partial$articulate.adoc[]

=== Critical Checks
A critical check allows for success in the face of certain failure or vice versa.
A roll of 100 may indicate success in the face of an impossible task.
A roll of 01 may indicate a failure in the face of sure success.
For more information about critical checks jump to xref:i-roll_playing_rules:CH16_Special_Rolls_Critical.adoc[Critical Checks,window=_blank].

== Example Maneuvers
This list is not exhaustive. 
The most common kinds of maneuvers encountered play testing EXP for a decade are listed here.
Many are silly. 

Successful Performance Rolls are granular and represent dice rolls that change a session, not a campaign.
As with all dice rolls in the Roll Playing System, a successful maneuver should not change a campaign's course.
Plot points are highly resistant to dice rolls. 

IMPORTANT: *These tables are not exhaustive.*

=== General Maneuvers 
General maneuvers represent day-to-day things that personas may want to do.
Under normal circumstances, there should be no performance roll required for these actions.
The referee would need some fun excuse to force the player to make a performance roll.
If a persona needs to bake a cake for her dessert, she should simply bake a cake.
If the persona is baking a cake to impress an alien dignitary, then a performance roll is part of the fun.
If the persona needs to bake a cake while recreationally impaired, then a performance roll is part of the fun.

include::ROOT:partial$CH14_Table_DD_General.adoc[]

=== Driving Maneuvers
There is an entire section devoted to xref:i-roll_playing_rules:CH17_Driving.adoc[Driving,window=_blank].
This table is included here for redundancy and convenience.

include::ROOT:partial$CH17_Table_Example_Maneuvers.adoc[]

// Biologist maneuvers tag
include::i-roll_playing_rules:page$CH08_Vocations_Biologist.adoc[tag=biologist_maneuvers]

// Knite maneuvers tag
include::i-roll_playing_rules:page$CH08_Vocations_Knite.adoc[tag=knite_maneuvers]

// Mechanic maneuvers tag
include::i-roll_playing_rules:page$CH08_Vocations_Mechanic.adoc[tag=mechanic_maneuvers]

// Mercenary maneuvers tag
include::i-roll_playing_rules:page$CH08_Vocations_Mercenary.adoc[tag=mercenary_maneuvers]

// nomad maneuvers tag
include::i-roll_playing_rules:page$CH08_Vocations_Nomad.adoc[tag=nomad_maneuvers]

// nothing maneuvers tag
include::i-roll_playing_rules:page$CH08_Vocations_Nothing.adoc[tag=nothing_maneuvers]

// spie maneuvers tag
include::i-roll_playing_rules:page$CH08_Vocations_Spie.adoc[tag=spie_maneuvers]

// veterinarian maneuvers tag
include::i-roll_playing_rules:page$CH08_Vocations_Veterinarian.adoc[tag=veterinarian_maneuvers]

== Cross Vocation Maneuvers  
Occasionally a persona will wish to attempt a maneuver that is clearly from another vocations' skill set.
Mercenaries often find themselves wanting to do quick fixes and stabilizations (vet).
A mechanic may want to work on a security system (spie).
Research teams are not affected by these penalties.

The cross vocation penalties are for individual personas trying to expand their scope of practice.
These degree of difficulty penalties are in addition to zeroing the skill score by lack of aptitude.
A Mechanic trying to use the knite gift energy would face a DD of 45 and have zero skill score (target roll of 236).
The same mechanic trying to use the nothing skill of righteous indignation would have a DD of 4-9 and zero skill score (target roll from 72 to 92).
 
include::ROOT:partial$CH14_Table_Cross_Class_Maneuvers.adoc[]

== Research Teams 
Research teams allow groups of personas to pool their experience skills for a greater chance of success.
Several mechanics may share their expertise to solve a scientific problem or repair a broken warp drive.
A  team of veterinarians could work together to save a life.
The skill score of a research team is the sum of the skill scores of all its members.
Every player with a persona on the research team gets to make a performance roll using the team's combined skill score.
If any of the players win their performance roll, then the entire team is successful.

:art: research_team_biovet.png
:width: 250px
:snark: Biologist and vet working together.
:artist: Kelly Freas
:date: 1957
:license: CC BY-SA 4.0
:description: Drawing of two humans working together on delicate project.

include::ROOT:partial$articulate.adoc[]

=== Research Team Composition
Every research team must have a team leader.
The EXPS Level of the team leader determines the size of the research team.
The team can consist of one persona per level of the team leader in addition to themselves.
A team leader cannot lead a persona with a higher EXPS level than herself.

:art: research_team_cyborg_repair.png
:width: 250px
:snark: Many hands make confusing work.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of various humanoids gathered around a table looking at an injured robot.

include::ROOT:partial$articulate.adoc[]

For example, a 5th level veterinarian could lead a team of 5 veterinarians.
That could be a combined research team of skill score 30 with five five performance rolls.
Teams can accomplish amazing things.
However, teams cannot get together to solve intricate campaign puzzles created by the referee.
As always, plot points are dice roll resistant.

A team can be composed of different vocations.
The players must justify each vocation type's involvement on the research team.
For example, a 7th level biologist could lead a team of 5 biologists, a mercenary, and a spie.
If the research team was trying to determine the chance of alien revolution, this team makes sense.
If the research team were trying to determine the direction of alien migration, including the spie and mercenary would not make sense.

=== Research Team Example
An operating room research team has a 4th level veterinarian team leader.
The team comprises two 3rd level vets, a 3rd level biologist and a 2nd level nomad.
They are working together to fix a famous alien the expedition accidentally ran over with a hovercar.
They need to repair her articulated wing flaps. 
The Degree of Difficulty of the procedure is 20DD.

The research team's total skill score is 15 (4 + 3 + 3 + 3 + 2).

Each team member would get a chance to beat the Target Roll of 76.
The procedure is a success if any of the five players roll 76 or higher.

== Maneuver Duration
How long a maneuver takes depends on a combination of common sense and degree of difficulty (DD).
Some maneuvers have specifically assigned durations.
Performing open-heart surgery (a difficult task) would always take longer than ten minutes.
However, the equally difficult task of performing a double somersault would take an instant.

Combat-related maneuvers happen during the unit of combat unless otherwise specified.
Research teamwork that requires months can pass in an instant with a few performance rolls.

include::ROOT:partial$CH14_Table_Duration_of_Research.adoc[]

A persona carrying out a 4 DD maneuver would require 0-99 units of time.
At the end of which, the player would make her performance roll.
Most of the time, this duration information is a nerd fascination.
If time is not of the essence, then don't play on this table. 
During combat time, these durations may be critical.
Outside of combat time, the maneuver durations pass instantly.

A biologist trying to identify an alien species could take up to 3 minutes to make a decision.
The duration reflects the time she spent leafing through her notes and observing before making a decision.

A mercenary attempting pistol with pistol ambidextrous combat would have no such time duration, and success, or failure, is instantaneous.

NOTE: *The players may win the performance roll in an instant, but the research and preparation may take the personas months.*

Research teams should always check for the duration of maneuvers. 
A maneuver that takes months to complete could be reflected in gameplay with sub-missions to get materials or other team members.

