= Performance Rolls

Performance Rolls are made by players when their persona is attempting a maneuver.
A Performance Roll is required when the persona is trying to do something. 
For example, strapping a grommet-sized oscillating refractometer onto a Frederickson di-collating time re-modulator.
Or steering a hover jeep for the first time. 
With a single die roll, the player skips directly to the aftermath of her persona's attempt.

The more difficult the maneuver the higher the player needs to roll.
The difficulty of the maneuver is indicated the Degree of Difficulty (DD).
The Degree of Difficulty can be determined from a vocation skill list, randomly or arbitrarily by the referee.

:art: monkey_box_anger.png
:width: 250px
:snark: Failure makes Rage.
:artist: Andrew Brechin
:date: 1990
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The player rolls a 1d100 to determine success or failure of the maneuver. 
The player wants to roll high.
Sometimes a maneuver will be too difficult for the persona to complete on their own. 

Performance Rolls are part of the Roll Playing system.
A less complicated approach to skills and maneuvers is found in the Role Playing System.

NOTE: *The Performance Roll system replaces Performance Tables from previous versions.*

.*Steps To Peak Performance Rolls*
. <<_determine_skill_level,Determine Skill Level>>
. <<_determine_degree_of_difficulty,Determine Degree of Difficulty>>
.. Example DDs
. <<_determine_target_roll,Determine Target Roll>>
.. Calculated
.. Tabulated
. <<_determine_bonuses,Determine Bonuses>>
.. Attribute Bonuses
.. Role Playing Bonuses
. <<_roll_1d100,Determine 1d100 roll>>

.*More Performance Roll Rules*
* <<_example_maneuvers,Example Maneuver DDs>>
** <<_general_maneuver,General Maneuver>>
** <<_driving_maneuvers,Driving Maneuvers>>
** <<_biologist_maneuvers,Biologist Maneuvers>>
** <<knite,Knite Maneuvers>>
** <<_mechanic_maneuvers,Mechanic Maneuvers>>
** <<_mercenary_maneuvers,Mercenary Maneuvers>>
** <<_nomad_maneuvers,Nomad Maneuvers>>
** <<_nothing_maneuvers,Nothing Maneuvers>>
** <<_spie_maneuvers,Spie Maneuvers>>
** <<_veterinarian_maneuvers,Veterinarian Maneuvers>>
* <<_cross_vocation_maneuvers,Cross Vocation Maneuvers>>
* <<_research_teams,Research Teams>>
* <<_duration_of_maneuvers,Duration of Maneuvers>>

== Determine Skill Level
The Skill Level is a combination of the persona's EXPS Level and her skills.
A persona can use her EXPS Level for any maneuver that fits within her vocation.
If the persona also has an applicable skill she can add this to her Skill Level.
Persona's attempting maneuvers outside of their vocation have a skill level of zero.

=== Calculating Skill Level
.Skill Level = EXPS Level + Applicable SKill
****
A third level biologist with Herbivore 2 would have a skill level of 5 studying herbivores.
****

== Determine Degree of Difficulty
The more difficult something is to do the higher the Degree of Difficulty (DD).
Most of the time the DD is clearly define by the maneuver in the personas vocation skill list.
Any persona can attempt anything.
However the DD can be so high that it is impossible to make the Performance Roll.
From the biologist skill table Cloning is DD 42. 
From the driving maneuver table driving straight ahead is DD 1.
The lowest DD possible is 1.
There is no upper limit to a how high a DD can go.

Circumstances can increase or decrease the DD of a maneuver.

Degree of Difficulty can also be determined by a description of the maneuver.
The description is usually assigned by the referee, but negotiation is possible.
Described Degree of Difficulty is for maneuvers that are not on any list. 
Player will always be coming up with creative challenges for their personas.
A trivial maneuver has a DD of 1.
An impossible maneuver has a DD ranging from 21 to 30 and is randomly rolled.

Referees are also allowed to arbitrarily decide a Degree of Difficulty based on the Descriptor.

include::ROOT:partial$CH14_Table_DD.adoc[]

== Determine Target Roll
The target roll is like the armour rating of a procedure.
The player must roll equal to or higher than the target roll.
The target roll is determined by Skill Level and Degree of Difficulty.
The higher the skill level the lower the target roll.
The higher the DD the higher the target roll.

The target roll can be calculated or tabulated.
The table is collection of common target rolls pre-calculated for your look up pleasure. 
Very high skill levels and very high DDs will require calculation.

=== Calculated
The skill level bonus increases as the persona's level increases.
Higher EXPS levels have an even greater bonus per EXPS level.

include::ROOT:partial$CH14_Table_Vocation_Level_Bonus.adoc[]

=== Target Roll Calculation
.Roll = 56 + 4 per DD - Skill
****
Must roll 80 or higher to beat a DD6 maneuver with 0 Skill. +
Must roll 50 or higher to beat a DD6 maneuver with 10 Skill.
****

=== Tabulated Target Roll
No calculations compare DD to skill to get Target Roll.

include::ROOT:partial$CH14_Table_New_Performance.adoc[]

== Determine Bonuses
Bonuses are added to the player's 1d100 roll.
Bonuses will often mean the difference between success and failure.
Bonuses can come from every which way.
There are TOYs that give Performance Roll bonuses.
There are computers that give Performance Roll bonuses.
Many referees will offer Performance Roll bonuses for good role-playing descriptions. 

:art: indiana_lizard.png
:width: 250px
:snark: This gonna be easy.
:artist: Patrick Redding
:date: 1990
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

=== Attribute Bonuses
The most common bonuses are vocation attribute bonuses.
If the maneuver fits into the vocation's aptitude the player can add an attribute to 1d100 roll.
For combat maneuvers mercenaries can add their PSTR.
For knowledge based maneuvers biologists can add their INT. 

include::ROOT:partial$CH14_Table_Vocation_Bonus.adoc[]

=== Role Playing Bonuses
The more role-playing is integrated into the roll playing system the more fun the play is.
Role-playing is incentivised in Performance Rolls by awarding roll bonuses for fun descriptions.
For example, the player that says, “I’m going to leaf through my notes here, and try to identify this bizarre creature” before making the Performance Roll should get some bonus.
Or “I summon all the forces of evil beneath me, as I try to apply pressure to this weakling altruist.”
Or “Taking my favorite tools from my mechanical kit, I proceed to repair this damaged bicycle.”
Or “I  calmly stalk silently past the sleeping sentry.”

:art: vet_big_hat_idea_desat.png
:width: 250px
:snark: I have an idea.
:artist: StudioStoks, mod HM
:date: 2010
:license: StudioStoks Stock Art.

include::ROOT:partial$articulate.adoc[]

The bonuses should be small.
For example, +5 added to the Performance Roll would be generous bonus.
Small bonuses that lead to success generate quite a bit of excitement.

== Roll 1d100
The player rolls the 1d100, adds in the bonuses and hopes to beat the target roll. 
Any roll equal to or higher than the target roll is a success.
Any roll less than the target roll is a failure.

:art: performance_roll_mecha_hammer.png
:width: 250px
:snark: Delicate repairs underway.
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

There are xref:CH16_Special_Rolls_Critical.adoc[critical checks] on Performance Rolls.
A roll of 100 can mean a success in the face of an impossible task.
A roll of 01 can indicated a failure in the face of certain victory.

== Example Maneuvers
This list is not exhaustive. 
The most common kinds of maneuvers encountered play testing EXP for a decade are listed here.
Many are silly. 
As with all rolls in the Roll Playing system a successful maneuver should not change the course a campaign.
Successful Performance Rolls are much more granular and represent maneuvers that change a session not a campaign.

IMPORTANT: *These tables are not exhaustive.*

=== General Maneuvers 
Day to day things that personas may want to do.
The referee should not apply these Performance Rolls without some kind of fun excuse.
If a persona needs to bake a cake to eat the persona should just bake a cake.
If the persona is baking a cake to impress an alien dignitary then a Performance Roll is part of the fun.

include::ROOT:partial$CH14_Table_DD_General.adoc[]

=== Driving Maneuvers
There is an entire section devoted to xref:CH17_Driving.adoc[driving].
This table is included here for redundancy and convenience.

include::ROOT:partial$CH17_Table_Example_Maneuvers.adoc[]

=== Biologist Maneuvers
Biologist maneuvers involve anything organic that does not involve healing.
Most biologist maneuvers are knowledge based unless an obvious physical procedure is involved.
Knowledge based maneuvers can grant the player an INT Performance Roll bonus.

The minimal equipment required by a biologist is her notebooks. 
The referee may make a target roll more difficult if the biologist does not have her notebooks.

include::ROOT:partial$CH14_Table_DD_Biologist.adoc[]

=== Knite Maneuvers
Knite maneuvers are mystical in nature and involve manipulation of the thinkspace.
Knite maneuvers are considered spiritual gifts or psionic abilities. 
When in combat the knite may be able to get a MSTR Performance Roll bonus.

A knite must have a MSTR of 18 to perform any of these maneuvers. 
The knite's MSTR is an essential piece of equipment.

include::ROOT:partial$CH14_Table_DD_Knite.adoc[]

=== Mechanic Maneuvers
Mechanic maneuvers involve anything inorganic or mechanical in nature.
These maneuvers are all about fixing, modifying and creating mechanical devices.
Most mechanic maneuvers are knowledge based and Performance Roll bonuses may reflect this.

A mechanic must have a tool to work with. 
This can be any kind of tool that is not improvised from the persona's body (slap does not equal hammer).
The referee may make a target roll more difficult if the mechanic does not have a tool.

include::ROOT:partial$CH14_Table_DD_Mech.adoc[]

=== Mercenary Maneuvers
Mercenary maneuvers are devoted to combat and harming organic and inorganic targets.
These maneuvers are all about destroy, destroy, and destroy.
All mercenary maneuvers are combat maneuvers and allow a PSTR Performance Roll bonus.

A mercenary must have a weapon to work with.
This must be an actual weapon that is not improvised from the persona's body (a fist is not a mace).
The referee may make a target roll more difficult if the mercenary does not have a weapon.

include::ROOT:partial$CH14_Table_DD_Merc.adoc[]

=== Nomad Maneuvers
Nomad maneuvers are about surviving and manipulating the environment surrounding the persona.
These terrains are called biomes and can be natural, industrial or residential.
These maneuvers are about personal survival.
Nomadic maneuvers are mostly Gut maneuvers and the player may enjoy an AWE bonus the Performance Roll.

A nomad has no essential equipment.
Unlike any other vocation a nomad may be inhibited by survival tools like tents, or fire starters.
The referee may make a target roll more difficult if the nomad is glamping (glamorous camping).

include::ROOT:partial$CH14_Table_DD_Nomad.adoc[]

=== Nothing Maneuvers
Nothing maneuvers are about surviving in the social fabric of wealth, fame and luxury.
Nothing maneuvers do not really exist, as they offer nothing of worth to the expedition.
If the expedition convinces the referee that a nothing maneuver is possible it will be a Gut maneuver.

The essential equipment for a nothing is any useless item of arbitrary value.
This could be a some cash, a credit card or a vacation souvenir.
The referee may make a target roll more difficult if the nothing has nothing.

include::ROOT:partial$CH14_Table_DD_Nothing.adoc[]

=== Spie Maneuvers
Spie maneuvers are about deception, treachery and sneaky violence.
Most spie maneuvers are considered Combat maneuvers. 
Other are considered Gut maneuvers.
The referee can adjust Performance Roll bonuses depending on where the maneuver lies.

Spies have essential equipment.
A spie must have some element of deception on their persona.
This could include a pair of dark sunglasses, a fake ID or a trench coat.
The referee may make a target roll more difficult if the spie no tools of deception.

include::ROOT:partial$CH14_Table_DD_Spie.adoc[]

=== Veterinarian Maneuvers
Vet maneuvers involve the healing, repair and enhancement of organic life forms.
Vet maneuvers can be considered Gut or Knowledge based maneuvers.
The referee can adjust Performance Roll bonuses depending on where the maneuver lies.

The vet must be able to smile at her patient.
Personal connection is essential equipment for successful veterinarian maneuvers.
The referee may make a target roll more difficult if the vet cannot emotionally connect with her patient.

include::ROOT:partial$CH14_Table_DD_Vet.adoc[]

== Cross Vocation Maneuver Penalties 
Occasionally a persona will wish to attempt a maneuver that is clearly from another vocations's skill set.
Mercenaries often find themselves wanting to do quick fixes and stabilizations (vet).
A mechanic may want to work on a security system (spie).

The cross vocation penalties are for individual personas trying to expand their scope of practice.
Research teams are rarely effected by these penalties.

include::ROOT:partial$CH14_Table_Cross_Class_Maneuvers.adoc[]

== Research Teams 
Research teams allow groups of personas to pool their experience for a greater chance of success.
Several mechanics may share their expertise to solve a scientific problem, or repair a broken warp drive.
A  team of veterinarians could work  together to save a life.
The Skill Level of a research team is the sum of the EXPS levels of its members.
Every player on the research team gets to make a Performance Roll using the team's combined Skill Level.
If any one of them makes a successful PT roll, then the entire team is successful.

:art: research_team_biovet.png
:width: 250px
:snark: Biologist and vet working together.
:artist: Kelly Freas
:date: 1957
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

=== Research Team Composition
Every research team must have a team leader.
The EXPS Level of the team leader determines the size of the research team.
The team can consist of one persona per level of the team leader in addition to themselves.
A team leader cannot lead a persona with a higher EXPS level than herself.

:art: research_team_cyborg_repair.png
:width: 250px
:snark: Many hands makes confusing work.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

For example, a 5th level veterinarian could lead a team of 5 veterinarians.
The maximum level of veterinarian would be 5th level. 
That could be a combined research team of skill level 30 with 5 Performance Rolls.
Teams can accomplish amazing things.
However teams cannot get together to solve intricate campaign puzzles created by the referee.

The team can be composed of different vocations.
The players must justify each vocation types involvement on the research team.
For example, a 7th level biologist could lead a team of 5 biologists, a mercenary. and a spie.
If the research team was trying to determine the chance of alien revolution this team makes sense.
If the research team was trying to determine the direction of alien migration it would not make sense.

=== Research Team Example
An operating room research team has a 4th level veterinarian team leader.
The team is composed of two 3rd level vets, a 3rd level biologist and a 2nd level nomad.
They are working together to fix a famous alien the expedition accidentally ran over with a hover car.
They need to repair her articulated wing flaps. 
The Degree of Difficulty of the procedure is 20DD.

The research team's total Skill Level is 15 (4 + 3 + 3 + 3 + 2).

Each team member would get a chance to beat the Target Roll of 76.
If any of the player's rolled 76 or higher the alien's articulated wing flaps would be repaired.
Much better chances than the just one veterinarian working solo.

== Maneuver Duration
How long a maneuver takes depends on a combination of common sense and degree of difficulty (DD).
Some maneuvers have specifically assigned durations.
Performing open heart surgery (a difficult task) would always take longer than ten minutes.
However the equally difficult task of performing a double somersault would take an instant.

Combat related maneuvers happen during the unit of combat unless otherwise specified.
Research team work that requires months of time can pass in an instant with a few Performance Rolls.

NOTE: *A maneuver may be completed in an instant but the research and preparation may take months.*

The player would roll 0-99 (1d100-1) to determine the number of unit her biologist would take to Determine Alien Armour Rating, 5 DD.
This would reflect the time she must spend leafing through her notes and observing before making a decision.
During combat time these units may be critical.
Outside of combat time the maneuver durations pass instantly.

The referee will most often use maneuver duration for research teams carrying out complex tasks.
It could easily take a research team a few months to determine complicated question.
The time could be integrated into the campaign by having the expedition go on several sorties, or just pass immediately for convenience. 

include::ROOT:partial$CH14_Table_Duration_of_Research.adoc[]

The Duration of Research Table is a peculiar one.
If the player rolls a zero they move down to lower level and roll there. 
For example a maneuver that takes zero days moves down to the 0-11 hours row.
If that roll is zero hours then the player rolls on the 0-5 hours row.
This decreasing of duration allows players to have immediate epiphanies.

The corollary is also true though.
If the player rolls the maximum duration of a maneuver they referee can move the up to the longer duration row. 
So something that should have taken 0-5 hours could end up taking months.

NOTE: *Anyone who has done research will find the quirky duration table pragmatic.*
