= Critical Checks

[quote]
____
*604 and 1000 and 042 all have the same chance of happening.*
____

Mundane humans love to see patterns where there are none. 
Players attribute unique value to die rolls for fun and persona profit.
The concept of the critical dice roll is too much fun to ignore. 
Critical checks are not specific die rolls like an attack roll or a task roll.
A critical check is observational. 
When a player generates an extreme roll on her dice, this warrants a critical check.
The most famous critical check is the critical hit.
In EXP, a critical hit is a roll of 990 or higher on 1d1000.

:art: critical_hit_arrow_split.png
:width: 250px
:snark: Robin hit.
:artist: Warren Oddsson
:date: 1990
:license: CC BY-SA 4.0
:description: Drawing of arrow splitting another arrow inside a bullseye. 

include::ROOT:partial$articulate.adoc[]

When a player rolls the maximum or minimum value of dice, exciting things can happen.
Rolling a one or a six on a d6 is not as exciting as rolling a 1 or 100 on a d100.
Critical checks can happen in attack rolls, attribute rolls, task rolls, driving rolls, etc.

Any amateur statistician will point out an impressive 998 is no more likely than an obscure 452. 
However, an air of urgency always accompanies these extreme rolls.
We all react hysterically to a roll kilodie of 000, but it is no more likely than a roll of 604.

Critical checks spice up the game by adding that rare dose of the unexpected.
A frail little alien may manage to damage that arrogant invader wearing powered armour.
A landlubber mechanic may manage to fix a damaged exatmo drive during space combat.

A critical check cannot bypass essential plot points.
Critical checks exist to revitalize, not to destroy, a campaign.

.*Parameters for a critical check*
* must be a natural roll 
* must be on a die roll of substance


== Natural Roll
Critical rolls must be natural.
An attack roll of 794 is not a critical roll.
If the persona's bonuses add up to 1000, this does not count for a critical check.
Only a natural 1000 would warrant a critical check.
A task roll of 01 is a critical failure.
All the bonuses in the universe will not prevent this critical failure.

== Dice of Substance
Critical checks should be limited to die rolls where they are unusual and reasonably infrequent.
For example, critical results on 1d4 rolls would occur 50% of the time. 
In EXP, even the famous 1d20 is considered too small to warrant critical checks.

=== 1d100
A 1d100, also called a deci-die, has three critical checks.
The critical values of a 1d100 are 01, 42 and 00 (100).
01 is considered a critical failure. 
00 is a critical success. 
42 is a nod to https://en.wikipedia.org/wiki/Douglas_Adams[Mr. Adams,windows=_blank] and often indicates shenanigans are afoot. 

=== 1d1000
A 1d1000, also called a kilo-die, has three critical checks.
There are two critical ranges and one critical value.
The ranges are 001 to 010 and 990 to 000 (1000).
The critical value is 042.
001 is an absolute critical failure.
002-010 is a critical failure.
990-999 is a critical success.
000 is an absolute critical success.
042 is a nod to https://en.wikipedia.org/wiki/Douglas_Adams[Mr. Adams,windows=_blank] and often indicates shenanigans are afoot. 

== Task Rolls
Task Rolls use a 1d100, and the goal is to roll high.
A natural 00 will bring automatic success.
A natural 01 will bring automatic failure.

While a critical result should result in something exciting, it should not alter crucial plot or story points. 
A critical result should not result in exorbitant EXPS awards that create game imbalance.
Uncommon sense should prevail.

=== Otto Checks
Otto checks are when a player rolls the dice for a task roll even if the outcome is predetermined.
Otto checks are optional, and no one has any idea how the name came to be.
If the player rolls a 42 on the deci-die, she can redeem her persona with a dramatic description.

If the player needs to roll 156 on the 1d100, she may feel the roll is futile.
The player should always roll under these circumstances because she may roll 00 on 1d100 and enjoy a critical success. 
The otto check gives the player another chance to win the task roll if she rolls 42.
A decent description of why her persona actually did succeed will allow her to win the task roll.

For example, a first-level biologist wants to start a fire underwater. 
She has bonuses of +20, but the Target Roll is 140.
The target for the task roll exceeds her chance of success.
If the player rolls 42 and tells a good story, she may find her persona is successful.

There is a corollary otto check for failure as well.
The referee may ask the player to make a task roll under circumstances where she cannot fail.

If a player needs to roll higher than -6 on the 1d100, she may want to skip making the task roll. 
The referee may ask players to make a task roll regardless.
Under these circumstances, the player should not fail even if she rolls 01 on the deci-die.
However, with otto checks, if she rolls 42, she must tell a good story of why she succeeded.

== Attack Rolls
Attack rolls use a kilo-dice (1d1000), and the goal is to roll high.
A  natural roll between 001 and 010 will bring failure.
A natural roll between 990 and 000 (1000) will bring success.
The critical check for an attack roll is called a critical hit or critical miss. 
Critical hits in RPGs have a long history of inflicting bonus damage. 

=== Critical Miss
001 to 010 is considered a critical fail, a critical mass, or even a weapon malfunction.
An attack roll in this range is a guaranteed miss.
A persona cannot damage a target if her player rolls 010 or less on the kilodie.
The persona does not injure herself. 
Nothing extreme will happen unless her weapon indicates a malfunction with this low a roll.
A referee may choose to have something extreme happen to the persona on a roll of 001. 

=== Critical Hit
990 to 000 is considered a critical success or critical hit.
An Attack Roll in this range is a guaranteed hit.
A persona will automatically damage her target with an Attack Roll of 990 or higher on the kilodie.
In some groups, a guaranteed damage roll is critical enough.

:art: critical_hit_head_bot.png
:width: 250px
:snark: Critically critical hit.
:artist: Unknown.
:date: 1990
:license: CC BY-SA 4.0
:description: Drawing of a robot taking a critical hit to the head. 

include::ROOT:partial$articulate.adoc[]

Referees may elect to have damage multipliers for critical hits. 
Here are the suggested Critical Hit damage bonuses proposed for the Tactical Combat System

.*Damage Bonuses for Critical Attack Rolls*
* 000 (1000) = damage times 4
* 990-999 = damage times 1d4

NOTE: *Referees do not use critical hit damage adjusters against player personas.*

== No Critical Checks Here
Critical Checks are limited as described above. 
There are several die rolls where there are no critical checks at all.

.*Nothing To Check Here*
* Damage System Shock Rolls
* Recovery Rolls
* Attribute Rolls
* Saving Rolls
* Initiative Rolls
* Ambush Rolls
* Sphincter Rolls
* Control Factor Rolls
* Damage Rolls
* Attributes Rolls
* Skill Determination
* Lists Extractions
* Mutations
* TOYS
* Chance Tables