= Saving Rolls

[quote]
____
*Physiology's automated defence against external attacks.*
____

Saving Rolls are specialized attribute rolls where the players rolls a die to save her persona from damaging effects.
Saving Rolls could easily be __rolled__ into the section on Attribute Rolls.
However there is a long RPG history of the Saving Throw.
Saving Rolls are EXP's variation on the historic save versus radiation, poison or psionic attack.

Saving Rolls are divided into psionic attacks and toxin attacks.
Toxin attacks can be further divided into poison and radiation attacks. 
There are only two attributes involved in Saving Rolls: constitution and mental strength.

.*Saving Roll Checklist*
. <<_attribute_type,Attribute Type>>
.. Constitution (CON) versus Toxins
.. Mental Strength (MSTR) versus Psionics
. <<_intensity_of_attack,Intensity of Attack>>
. Determine Target Roll
.. Target Roll = Intensity of poison, radiation or Psionic Attack
. <<_make_the_roll,Make the Roll>>
.. The player is always rolling a 1d20


== Attribute Type
The referee decides which attribute is most relevant for the roll.
This attribute score is the attribute added to the 1d20 die roll.
There are only two attributes involved in Saving Rolls: constitution (CON) and mental strength (MSTR).

.*Attribute Type For Save*
* CON vs Toxin
** poison or radiation
* MSTR vs psionic
** internal or external

Saving throws, or saves, are special attribute rolls that compete against a specific toxin or attack.
There are saves versus poison, saves versus radiation and saves versus psionic attack.
The save represents personas internal against an external attack.
The saving throw governs those  automatic physical and mental processes over which the persona has no conscious control.
The body always defends against poison or psionic attack.

== Intensity of Attack
The more dangerous the attack the higher the intensity and therefore the higher the target roll.
The intensity of radiation and poison are usually assigned a value depending on how dangerous they are.
A normal intensity poison would have an intensity of 18.
Psionic attacks are assigned an intensity equal to the attacker's MSTR. 
An average psionic attack intensity would be 12.

Some example target rolls can be gleaned from the Difficulty and Target Rolls Table.

include::ROOT:partial$CH16_Table_Attribute_Roll_Difficulty.adoc[]

=== Poison Attacks
Poisons are toxins that need to contact the persona to activate a Saving Roll.
This can be inhaled, ingested, or contact.
That is the distinct difference between poison and radiation.
Radiation can pass through the persona inflicted damage just sitting there.

Poisons can have specific effects if the player fails her Saving Roll.
A knock out poison will knock the persona out.
A nausea poison will make the persona vomit.
A pharmaceutical effect poison will have the described pharmaceutical effect.
A lethal poison will kill the persona dead.

A killing poison inflicts damage depending on the intensity of the poison.
A killing poison inflicts 1d4 per point of intensity of the poison.
So an intensity 18 poison would inflict 18d4 HPS of damage if the Saving Roll is missed.
Pretty much lethal. 

The intensity is determined by the referee in advance, or from the attack.
Alien poisons may have an intensity related to the alien's constitution. 
Lethal and killing poisons should have their intensity modified to reflect a fun game. 

Robots are unaffected by poisons that are aimed at a physiologic system.
Electric shocks, corrosives and radiation have the same effect on aliens, anthros and robots.

=== Radiation Attacks
Radiation is an electromagnetic toxin that needs not contact the persona to activate a Saving Roll.
Radiation can be inhaled, ingested, or contacted.
Radiation can also pass through the persona inflicted damage just sitting there.
Radiation is dangerous just being there.

Radiation affects all lifeforms equally. 
It smashes tissues, chromosomes and circuitry.
A radiation attack inflicts damage depending on it's intensity.
A radiation attack inflicts 1d4 per point of intensity of the radiation.
So an intensity 12 radiation attack would inflict 12d4 HPS of damage if the Saving Roll is missed.
A successful Saving Roll reduces this damage by half. 
Radiation is deadly coming and going.

This is fantasy radiation, and fun should replace realism.
If the referee is feeling like having fun, or the player tells a good story a mutation check can be warranted.
If a kilodie roll is less than the total damage taken the player gets a chance at mutating.
This is accomplished by doing a mutation check based on the persona type.
Robots do not enjoy this mutation check.
Only anthros and aliens can mutate post radiation attack.

== Psionic Attack
Psionic attacks are sciency fiction manipulations of the persona's mind or the physical plane.
Most psionic attacks are delivered by mental mutations.
Some machines carry out attacks that function similar to psionic attacks. 

:art: knitevknites.png
:width: 250px
:snark: Alien knite vs anthro knite.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

If the attack is affecting the function of the target through the persona's thinkspace a Saving Roll is granted.
This means that ESP, telekinesis, memory eradication, and other direct affects indicate a Saving Roll.
Mental mutations that transform the environment do not get a Saving Roll.
So a mental attack that changes gravity would affect the persona without a Saving Roll.
Hopefully these mutation effects have been appropriately divided between mental and physical mutations.

The intensity of the psionic attack is equal to the mental strength of the attacker.
Player personas may be able to add their EXPS Level to the intensity.
Referee personas, unless Canon RPs, just use their MSTR unadjusted.

A successful Saving Roll against psionic attack completes negates any effect.
There is no partial effect like in radiation or killing poisons.
A failed Saving Roll results in the success for the attacker.
The persona may have her mind controlled, may be thrown by telekinesis or may fall unconsious.
