= Sphincter Rolls

Sphincter Rolls are a roll that a player makes against fate.
There are no bonuses or penalties applied to a Sphincter Roll.
A Sphincter Roll resolves an impasse where congenial discussion can no longer tread.

For example, did the persona leave the door unlocked?
Did the ammunition pack fall to the left or the right?
Has the cheese gone mouldy?
Does the store have any tents in stock?

No efficiently prepared campaign could include the answers to such questions.
The Sphincter Roll determines if the minutiae fall in the persona's favour or not.

Sphincter Rolls are made on deci-dice (1d100).
The referee and player roll simultaneously. 

.*Sphincter Roll Results*
* 01-10 Player fails the roll
* 11-89 Player must roll higher than the referee
* 90-00 Player wins the roll.

A win by the player falls to the persona's benefit. 
The ammo pack fell to the right, onto the deck. 
The cheese is not mouldy, and the Nothing persona is happy.
The store has all kinds of tents in stock.

A loss for the player falls to the persona's inconvenience.
The ammo pack fell to the left, out of the treehouse. 
The cheese is mouldy, and the crackers are too.
The store has no tents in stock.

The referee should only use a Sphincter Roll for true inconsequentialities.
A failed Sphincter Roll should never kill or severely injure a persona.
Conversely, a Sphincter Roll should not solve a puzzle or change a campaign's course. 

== Example Usage
A persona is searching a hardware store for a size LT8R poly flanged wingnut.
She asks the storekeeper if any are in stock.
Hell, replies the referee, I don't know: Let's make Sphincter Roll. 
The player and referee roll their 1d100 dice.
The player rolls a 94, which is an automatic win.
The size LT8R poly flanged wingnut is in stock available for purchase.
The visit to Space Nuts Is Us is successful.

Later, the persona ignores the safety signs and walks through a strong magnetic field.
The referee wonders if the wingnuts are magnetic or not.
So a Sphincter Roll is required.
The player rolls a 75, but the referee rolls 84
The electromagnet pulls the wingnut from the persona's shirt pocket.



