= Saving Rolls

[quote]
____
*Automated internal defences against external attacks.*
____

Saving rolls are specialized attribute rolls where the players roll a die to protect their persona from damaging effects.
Saving rolls could easily be __rolled__ into the section on attribute rolls.
However, there is a long role-playing game history of the saving throw.
Saving rolls are EXP's variation on the historic saving throw versus radiation, poison or psionic attack.

Saving rolls consist of toxin attacks and psionic attacks.
Toxin attacks can separate into poison and radiation attacks. 
There are only two attributes involved in Saving Rolls: Constitution and Mind.

.*Saving Roll Checklist*
. <<_attribute_type,Attribute Type>>
. <<_target_value,Target Value>>
. <<_make_the_roll,Make the Roll>>

== Attribute Type
The referee decides which attribute is most relevant for the roll.
There are only two attributes involved in saving rolls: Constitution (CON) and Mind (MND).
The player adds her persona's attribute score and EXPS Level to the 1d20 die roll.

.*Attribute Type For Saving Roll*
* Poisons use Constitution (CON)
* Radiations use Constitution (CON)
* Psionic attacks use Mind (MND) 

The persona's body will automatically work against these kinds of attacks.
The Constitution primarily defends against unseen attacks originating from the physical space.
A persona's Constitution will repel poisons and infections using her anatomical structures, immune system and hormonal defences.
The Mind primarily defends against unseen attacks originating from the think space. 
A persona's Mind will harden her consciousness against intrusions, psychic controls and existential threats.

== Target Value
The more dangerous the attack, the higher the intensity and, therefore, the higher the target value.
Every toxin or psionic attack is assigned an intensity to reflect how dangerous the attack is.
This intensity determines the target value directly
A usual intensity poison has an intensity of 18.
Psionic attacks are assigned an intensity equal to the attacker's MND. 
An average psionic attack intensity would be 12.

=== Target Value
.Target Value = Intensity of Attack
****
Poison, radiation and mental attacks are all assigned an intensity. +
The player must roll higher than this number to win her saving roll.
****

.*Example Intensities*
* poison intensity listed with the weapon.
* poison intensity based on the attacker's Constitution plus level.
* radiation intensity listed with the weapon.
* mental attack intensity based on attacker's Mind plus level

== Poison Attacks
Poisons are toxins that need to contact the persona for effect.
Poisons can be inhaled, ingested, or contact.
Some poison attacks require a successful attack roll before they can harm the persona.
The persona cannot avoid other poison attacks like a gaseous area of effect attack, for instance.

Poisons can have specific effects if the player fails her saving roll.
A knock-out poison will knock the persona out.
A nausea poison will make the persona vomit.
A pharmaceutical effect poison will have the described pharmaceutical effect.
A lethal poison will kill the persona.

A killing poison inflicts damage depending on the intensity of the poison.
A killing poison inflicts 1d4 per point of intensity of the poison.
An intensity 18 killing poison will inflict 18d4 HPS of damage if the player fails her saving roll.
Pretty much lethal. 

The referee determines the intensity of the poison in advance.
Poisonous weapons usually have pre-determined intensities
Alien poisons may have an intensity related to the alien's Constitution. 
Alien poisons may increase their intensity by adding their EXPS Level to the intensity.
Lethal and killing poisons should have their intensity modified to reflect a fun game. 

Robots are unaffected by poisons that attack organic physiologic systems.
Electric shocks, corrosives and radiation have the same effect on aliens, anthros and robots.

== Radiation Attacks
Radiation is an electromagnetic toxin that need not contact the persona to cause harm.
Radiation poison can be inhaled, ingested, or contacted.
Radiation can also harm the persona if she gets too close.
Radiation is invisible and dangerous.
The distinct difference between poisons and radiation is that radiation can invisibly and secretly harm any persona in range.

Radiation affects all lifeforms equally. 
It smashes tissues, chromosomes and circuitry.
A radiation attack inflicts damage depending on its intensity.
A radiation attack inflicts 1d4 per point of intensity of the radiation.
An intensity 12 radiation attack would inflict 12d4 HPS of damage if the player misses her saving roll.
A successful saving roll reduces this damage by half. 
Radiation is deadly even if the player wins the saving roll for her persona.

EXP employs fantasy radiation, and fun replaces realism.
There is no radiation sickness, no thyroid cancer or dysfunction. 
However, like all good sciency fiction radiation exposure, there is a chance of mutating.
The chance of mutating from radiation exposure is up to the referee and players.
Players that intentionally expose themselves to radiation cannot mutate. 

.*Radiation Mutation Exploitation*
. Involuntary damaging radiation exposure.
. A compelling story from the player why she should mutate.
. 1d1000 roll less than the damage inflicted by the exposure
. If 3 is a win, then a chance to mutate as per persona type.
.. Robots do not mutate
. Jump to xref:i-roll_playing_rules:CH07_Mutating.adoc[Mutations,window=_blank]

== Psionic Attack
Psionic attacks are sciency fiction manipulations of the persona's mind or the physical space around the persona.
The psionic attack, mental attack, psychic attack, and thinkspace attack are all synonymous.
Psionic mutations deliver most psionic attacks.
Some machines carry out attacks that function similarly to psionic attacks. 

:art: knitevknites.png
:width: 250px
:snark: Alien knite vs anthro knite.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of two humanoid lizards locked in a psionic control battle.

include::ROOT:partial$articulate.adoc[]

If the attack affects the persona's consciousness through the thinkspace, the player makes a saving roll.
Psionic attacks like  ESP, telekinesis, memory eradication and other direct attacks indicate a saving roll.
Psionic mutations that transform the environment around the persona do not get a saving roll.
Psionic attacks like gravity disruption, mental blast or lazer eyes and other indirect attacks indicate no saving roll.

The intensity of the psionic attack is equal to the attacker's Mind plus her EXPS Level. 

A successful saving roll against a psionic attack completely negates any effect.
There is no partial effect for mental attacks.
A failed saving roll subjects the persona to the details of the mental attack.
The persona may have her mind-controlled, muscles manipulated or lifted against her will.

== Make the Roll
The player must roll equal to or higher than the target value (intensity).
The player rolls a 1d20 and adds her EXPS Level and attribute type to the roll.

=== Saving Roll 
.Saving Roll = 1d20 + Attribute Type + EXPS Level
****
3rd level with 12 CON rolls 11. Her saving roll is 26.
****

.*Attribute Types For Saving Rolls*
* Poisons use Constitution (CON)
* Radiations use Constitution (CON)
* Psionic attacks use Mind (MND) 


== Example Saving Rolls

include::ROOT:partial$CH16_Table_Saving_Roll_Examples.adoc[]