= Attribute Rolls

[quote]
____
*For juggling books or juggling chainsaws.*
____

Attribute Rolls is the term for a collection of die rolls that test specific attributes.
Acts of dexterity, physical strength or will power are examples of attribute tests.
An attribute test employs a specific attribute is attempting a specific task.
Catching a valuable egg would be dexterity (DEX) test.
Listening for a malfunctioning engine noise would be an awareness (AWE) test.

.*Types of Attribute Tests*
* <<_attribute_type,Attribute Rolls>>
** Player rolls once employing one attribute against a target roll that determines success.
* <<_attribute_competition,Attribute Competition>>
** Two players roll dice competing against each other. 
* xref:CH16_Special_Rolls_Saves.adoc[Attribute Challenge,window=_blank]
** Player rolls once against an attack. Usually a toxin or psionic attack. 
** Called a Saving Roll

Attribute Rolls are meant to be quick rolls to determine success in non-vocational maneuvers.
There are many Roll Playing Systems that involve attributes, but they are not replaceable by Attribute Rolls.
Attribute Rolls do not replace Attack Rolls, Performance Rolls or Driving Rolls.
xref:CH27_Tactical_Combat.adoc[Attack Rolls] are the basis of Tactical Combat and represent a complex balance of attributes.
xref:CH14_Performance_Tables.adoc[Performance Rolls] are meant for the maneuvers of specific vocations.
xref:CH17_Driving.adoc[Driving Rolls] involves both the vehicle handling class and dexterity rolls.

:art: elephant_juggling.png
:width: 250px
:snark: Juggling the books.
:artist: Andrew Brechin
:date: 1990
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Attribute Rolls and Attribute Competitions are slightly different.
An Attribute Roll is made by the player challenging a specific target roll that is determined by the difficulty.
An Attribute Challenge Roll is made by the player against the roll of another player, usually the referee.

An Attribute Rolls should only be employed when a challenging situation arises.
A player should not have to make an Attribute Roll to have her persona open a door.
A persona trying to escape through a complicated door while under fire can warrant an Attribute Roll.
Or a persona trying to unlock their front door while impaired can warrant an Attribute Roll.
An Attribute Roll should make the evening's role-playing more fun.

As with all rolls Attribute Challenges should not decide the course or a campaign.
Nor should an Attribute Challenge be used to solve a referee's puzzle.

.*Attribute Roll Checklist*
. <<_attribute_type,Attribute Type>>
. <<_difficulty_of_task,Difficulty of Task>>
. Determine Target Roll
.. Target Roll = Numeric Difficulty
. <<_make_the_roll,Make the Roll>>
.. The player is always rolling a 1d20

== Attribute Type
The referee decides which attribute is most relevant for the roll.
This will be the attribute added to the 1d20 die roll.
A persona with a DEX of 11 would add 11 to her 1d20 Attribute Roll.

include::ROOT:partial$CH16_Table_Example_Attribute_Rolls.adoc[]

== Difficulty of Task
Not all Attribute Rolls are created equal. 
Attribute Rolls are meant to be quick and to the point.
The difficulties are assigned by descriptors.
When assigning an attribute roll the referee determines the difficulty of the task.
The more difficult the maneuver the higher the target roll.
For example, kicking open a standard residential door would be a Normal or Easy difficulty.
Kicking open a commercial door would be Hard or Tough.
Kicking open a combat fortified door would be Impossible or Bizarre difficulty.

The majority of the time the player will be rolling against a Normal difficulty.
The less likely it seems that the persona could be successful the greater the difficulty.
Bizarre difficulty is left for something impossible but the player still wants to try.

Each difficulty descriptor has a random or static target roll associated with it.
For a normal difficulty Attribute Roll the referee can roll 1d20 for a random target, or use the static 18.

include::ROOT:partial$CH16_Table_Attribute_Roll_Difficulty.adoc[]

The numeric portion of the difficulty becomes the target roll for the player.

== Make the Roll
The player must roll equal to or higher than the target roll.
The numeric portion of the difficulty is the target roll for the player.
The target roll is either the static, or random, difficulty determined by the referee.
The player rolls a 1d20 and adds her EXPS Level and Attribute Score to the roll.

=== Attribute Roll 
.Attribute Roll = 1d20 + Attribute + EXPS Level
****
The players rolls 11 for a 3rd level persona with a CHA of 12. The roll is 26. 
****

== Attribute Competition
An attribute competition pits two personas against each other in a contest directly related to an attribute.
Usually the referee rolls for the referee persona.
Two personas arm wrestling is a PSTR challenge.
Two personas playing hat snatch is a DEX competition.
A staring contest is a MSTR competition.

include::ROOT:partial$CH16_Table_Attribute_Challenges.adoc[]

== Combining Forces
Personas can get together and combine forces to complete a task.
An example would be a bunch of personas lifting a rock off of an expedition member.
If there are enough personas the referee should simply allow the lift to happen.
If there are extenuating circumstances the referee may require a combined Attribute Roll or Competition.
For example a tug of war between two expeditions would be a combined Attribute Competition.

The difference between an Attribute Roll and an Attribute Competition remains unchanged.
When personas are competing the players make an Attribute Competition Roll.

In a combined Attribute Roll each player gets to make a roll. 
If any of the players are successful the entire team is successful.
For example, 3 personas are trying to push over a flag pole.
The target roll is decided by the referee.
Each player gets to roll against the target roll.
The success of any of the players means flag pole has succumbed to the vandalism.

In a combined Attribute Challenge each player gets to make a roll.
Success depends on the number of successes between each team.
So if two groups of ursidae are having a tug of war every player gets to roll.
The referee can match players by descending PSTR. 
Which ever team has the most successes wins the tug of war. 
A tie means that the tug of war is continuing, excitement increases and everyone rolls again.

In general the stronger team will win, but miracles of probability can still occur

