= All Those Rolls

EXP is replete with many dice rolls.
The Roll Playing System is intentionally dice heavy. 
The Roll Playing System is for groups like to roll dice as much as telling the story.
Some of the dice rolls described here are stand-alone sections in the Roll Playing System.
For example, players can use sphincter rolls in either system to assist decisions.
Other dice rolls are part of more complex systems. 
For example, attack rolls require armour rating, combat tables, attributes and vocations to work.

NOTE: *EXP version 6.0 introduced major changes to dice mechanics.*

Embrace the High Roll::
Rolling a higher number is almost always better for the persona.
Previous versions of EXP players would use their hope powers on either high or low rolls.
EXP is now all in for high rolls.

Clear the Tables::
Equations have replaced tables.
Some lookup tables still exist to avoid maths. 
In previous versions of EXP, there were many, many decision tables.

:art: All Those Rolls_transparent.png
:width: 700px
:snark: Inventory of Roll System Rolls
:artist: HM
:date: 2021
:license: CC BY-SA 4.0
:description: Mind map laying out all the different rolls in the game.

include::ROOT:partial$articulate.adoc[]

.*Inventory of Rolls*
* <<_target_rolls,Target Rolls>> (Fixed target)
* <<_challenge_rolls,Challenge Rolls>> (Dynamic target)
* <<_generative_rolls,Generative Rolls>> (No target)
* <<_critical_checks,Critical Checks>> (Look for certain numbers)
* <<_jelly_rolls,Jelly Rolls>> (Tasty Treats)

== Target Rolls
Target rolls require the player to make a dice roll higher than a specific number.
If the player rolls higher or equal to the target number, she wins the roll. 
Most often, the target number is known to the player.
For example, for a player to win an attack roll, she needs to roll higher than the target's armour rating.

.*List of Target Rolls
* <<_attack_rolls,Attack Rolls>>
* xref:i-roll_playing_rules:CH14_Performance_Tables.adoc[Task Rolls,window=_blank]
* xref:i-roll_playing_rules:CH17_Driving.adoc[Driving Rolls,window=_blank]
* xref:i-roll_playing_rules:CH04_Anthros_HPS.adoc#_damage_system_shock[Damage System Shock Roll,window=_blank]
* xref:i-roll_playing_rules:CH04_Anthros_HPS.adoc#_recovery_roll[Recovery Roll,window=_blank]

=== Attack Rolls
Attack rolls are made by the player when her persona is attempting to harm another persona.
The attack may be a punch, gunshot, sword swing, claw, bite, or energy blast.
The player needs to roll higher than, or equal to, the target's armour rating to win her attack roll.
If she wins the roll, she moves on to damaging the target.
The tactical combat system is devoted to calculating all aspects of the attack roll.

NOTE: *Previous versions of EXP called the Attack Roll a To Hit Roll.*

=== Task Rolls
Task Rolls are made by the player when her persona is attempting to perform a maneuver.
These maneuvers are vocation-related skills, abilities, tricks or gifts. 
The player needs to roll higher than, or equal to, the target roll to win her task roll.
The target roll gets higher the more complex the maneuver.

=== Driving Rolls
Driving rolls are made by the player when her persona is attempting to perform a driving maneuver.
A driving roll is a task roll dedicated to driving tasks.
For fun, these are often called maneuvering maneuvers 
The target roll gets higher the more complex the maneuver.
 
=== Damage System Shock Rolls
A damage system shock roll (DSS) is an anthro-specific target roll.
The player rolls dice to keep her persona conscious after a severe bolus of damage.

=== Recovery Rolls
A recovery roll (REC) is an anthro-specific target roll.
The player rolls dice to have her persona regain consciousness after failing a damage system shock roll.

== Challenge Rolls
Challenge Rolls the player is trying to roll higher than a dynamic number to benefit their persona.
The main difference between a challenge roll and a target roll is that the number the player must roll higher than is generated on the spot.
The player must roll higher than another player rolling dice at the same time.
Most often, the other player is the referee.
The winner of the challenge roll is the player that rolls higher. 

.*List of Challenge Rolls*
* xref:i-roll_playing_rules:CH16_Special_Rolls_Attributes.adoc[Attribute Rolls,window=_blank]
* xref:i-roll_playing_rules:CH16_Special_Rolls_Saves.adoc[Saving Rolls,window=_blank]
* xref:i-roll_playing_rules:CH33_Initiative.adoc[Initiative Rolls,window=_blank]
* xref:i-roll_playing_rules:CH34_Ambush.adoc[Ambush Rolls,window=_blank]
* xref:i-roll_playing_rules:CH16_Special_Rolls_Asshole.adoc[Sphincter Rolls,window=_blank]
* xref:i-roll_playing_rules:CH05_Robots_Z_CF.adoc[Control Factor Rolls,window=_blank]

=== Attribute Rolls
An attribute roll involves the player using a specific attribute in a challenge.
Two personas arm wrestling would simultaneously roll dice to see who wins.
The persona's physical strength scores modify the dice rolls.
Two personas trying to out charm each other would simultaneously roll dice to see who wins.
The persona's charisma scores modify the dice rolls.
Hence the title attribute rolls or attribute challenge.

=== Saving Rolls
A saving roll involves the player trying to roll higher than a floating target to protect her persona from harm.
Saving rolls pit a specific attribute against an environmental or psionic nastiness.
The player makes saving rolls against attacks like poison, radiation, and mental attacks.
The persona's most appropriate attribute modifies the player's diced roll. 
For example, the persona's constitution fights against poison and radiation attacks, while mental strength fights against psionic attacks. 

The saving roll tries to beat the intensity of the attack. 
The referee generates the intensity randomly, and that is what makes saving rolls challenge rolls. 

NOTE: *Previous versions of EXP called the Saving Roll a Saving Throw.*

=== Initiative Rolls
Initiative Rolls are specialized dexterity challenges used to determine action order in tactical combat.
The higher the player's roll, the better the persona is positioned for that combat unit.

=== Ambush Rolls
Ambush Rolls are specialized awareness challenges used to see how well the persona reacts to an ambush.
The higher the roll, the more likely the persona will be able to defend themselves in combat.

=== Sphincter Rolls
Sphincter rolls are the last line of decision-making when players cannot agree.
The sphincter roll is a luck challenge roll between two players. 
The player usually competes with the referee when making a sphincter roll.
Sphincter rolls fill those gaps in the referee's milieu.
Sphincter rolls also assist players in making decisions when a decision is elusive.
If the player rolls higher than the referee, the decision falls in favour of the player.

NOTE: *A Sphincter Roll was previously Sphincter Dice which was previously A$$hole Dice.*

The nomenclature here comes from tortuous conversations that arise from a group of youngish Y chromosomes being positional. 
A more appropriate term, Drama Roll, is on the horizon for future versions.

=== Control Factor Roll
The control factor roll is a challenge roll specific to the family of robots.
The player makes a control factor roll for her robot persona to keep her from falling back into her baked-in programming.
The challenge is between the robot's intelligence and the depth of the violation of programming.
The player needs to roll high to stay in control of her robot persona.

== Generative Rolls
Generative rolls have no target and no competitive aspect to them.
A generative roll yields a permanent result that is descriptive of an event or element.
Generative rolls do not predict immediate success or failure for the persona.
Most generative rolls indicate no benefit with a high or low roll.
Some generative rolls are important to the player's persona.
For example, a damage rolls and attribute scores rolls are important generative rolls. 

=== Attribute Generation Rolls
When the player is creating her persona, each attribute is assigned a score. 
These rolls are important. 
They define health, intelligence, species type, vocation type, and combat skills of the persona.
The persona does not succeed or fail based on these dice rolls.

=== Description Rolls
Descriptors are the classic generative die roll.
They are typically rolled once and recorded on the persona record sheet.
Descriptions have no outcome for the persona other than generating a descriptive element.
For example, alien and robot appearances are random and descriptive. 
Some descriptors can impact the performance of the persona.
For example, the wate of a robot or alien impacts the damage they inflict.

=== List Rolls
The player will often find themselves generating something completely random from a list.
They are typically rolled once and recorded on the persona record sheet.
These tables infuse randomness and ensure the rarity of powerful things.
The most famous list rolls include mutation tables, skill tables, and the Technological Object Yields System (TOYs).
List rolls do not immediately put the persona at risk but can have a long-term impact.

=== Chance Tables
These are weird tables limited to inatmo and exatmo vehicle generation.
They are tables where the player makes percent chance checks to see if peripherals or defences exist.
Technically it is a generative roll, but players always want the peripherals.
The chance table represents a percent chance, and a low roll indicates success. 
Chance tables are the only rolls left in EXP where players want to roll low for success.
These chance tables change in future versions of EXP to embrace the high roll.

=== Damage Rolls
Damage rolls are generative rolls that indirectly benefit the persona when the player rolls high.

== Critical Checks
Critical checks are not dice rolls at all.
A Critical check indicates an event that occurs within another roll.
For example, an attack roll can generate a critical success with a specific number.
If a player rolls 000 (1000) on an attack roll, this roll becomes a critical hit.
While the player does not intend to make a critical roll, one is indicated by checking for the 000.
All critical checks are detailed in the section xref:i-roll_playing_rules:CH16_Special_Rolls_Critical.adoc[Critical Checks,window=_blank].

NOTE: *Critical checks are also called Extreme Rolls and Critical Rolls or Critical Hits.*

== Jelly Rolls
Jelly rolls are yummy. 
EXP does not recommend jelly rolls when playing with hex mats and minis. 
For more information about these tasty treats jump to https://en.wikipedia.org/wiki/Swiss_roll[Jelly Rolls,window=_blank].
