= Driving

Driving involves the manual control of any inatmo vehicle.
An inatmo vehicle is any vehicle that is not a space vehicle.
The central assumption is that a persona controls the vehicle and as the vehicle's driver.
This section is not for autonomous vehicles or vehicles driven by transportation robots.  
This section is for the tactical driving of vehicles from xref:iii-hardware:CH54_Vehicles.adoc[Inatmo Vehicles,window=_blank].

This section applies to the aggressive and dangerous driving of cars, tractors, boats, planes or skateboards.
The basic assumption made about driving is that it is safe.
Drivers that obey traffic regulations and employ reasonable amounts of common sense will be fine.
The driving system only comes into play when personas speed, engage in combat or make reckless choices. 
Under normal circumstances, a vehicle allows an expedition to get from A to C to advance the story.

== Observations about Speed
* 1 h/u = 1 m/s
* 1 h/u = 3.6 kmh
* 1 h/u = 2.2 mph
* 25 h/u = Gale force winds
* 45 h/u = 100 mph
* 342 h/u = Speed of sound

== Driving and the Hex Mat
Inatmo vehicles travel at tremendous speeds.
Most vehicles will run out of tabletop combat mat in a unit or two.
Vehicle racing, or chasing, is another reason to keep track of vehicle location.
Car chases are fun.
If there are no persona tokens on the mat, grab a smaller scale hex mat.
The smaller scale mat allows for high-speed maneuvers and treacherous obstacles.
Regardless of the scale of the hex mat, vehicles move like any other persona.
They cover way more hexes every unit and can have lethal collisions.

:art: cool_cat_cool_car.png
:width: 250px
:snark: Cool cat. Cool car.
:artist: Kelly Freas
:date: 1955
:license: CC BY-SA 4.0
:description: Drawing of feline quadruped staring at box shaped hover car.

include::ROOT:partial$articulate.adoc[]

.*Collision Checklist*
. Driving Roll (vehicle-based)
. Rally Roll (driver-based)
. Control Loss
. Collision Check

== When to Check for Collision
Vehicular mishaps should be rare.
The control check is the first step in losing control of a vehicle.
Losing control can result in a collision that injures or kills passengers.
Only under extreme circumstances will a control check be warranted.
For the most part, the vehicle and driver will carry on without issue.
When to make a control check is usually the referee's decision.

.*Control Check Required*
* injury to the driver
** getting attacked by a weapon or hot beverage
* sudden dangerous change in road conditions
** oil slick, chicken swarm
* driver is distracted
** arguing, telling jokes, or juggling dice
* wilfully attempting a hazardous maneuver
** drifting, high-speed turn, barrel roll

== Driving Roll 
The driving roll is a xref:i-roll_playing_rules:CH14_Performance_Tables.adoc[Performance Roll,window=_blank] where the player must beat a target on 1d100 or lose control of her vehicle.
The driving roll functions like other performance rolls in that it compares a skill level to a degree of difficulty to determine a target roll.
The player must roll higher than the target roll or lost control of her vehicle.

.*Driving Roll Checklist*
. <<_determine_driving_skill_score,Determine Driving Skill Score>>
. <<_determine_degree_of_difficulty,Determine Degree of Difficulty>>
. <<_determine_target_roll,Determine Target Roll>>
. <<_roll_1d100,Make the Roll>>

=== Determine Driving Skill Score
The driving skill score is a combination of the vehicle's handling level and the persona's driving skill.
Every inatmo vehicle created has a handling level.
If a persona has no driving skill, the skill score is entirely dependent on the vehicle's handling level.
A persona's dexterity has no role in driving skill score.
The driver's dexterity comes into play if they need to regain control of their vehicle.

=== Driving Skill Score
.Skill Score = Vehicle Handling Level + Driver Skills
****
Handling level 5 and driving skill 2 gives a driving skill score of 7.
****

=== Determine Degree of Difficulty
Like all performance rolls, the more difficult the task, the more difficult it is to succeed.
The degree of difficulty (DD) is maneuver-specific for driving. 
The base degree of difficulty increases with increasing speed.

==== Speed Penalty
Speed effects are dependent on the persona's dexterity.
High dexterity reflects good eye-hand coordination, agility, and reaction time, all of which aids in avoiding accidents.
The maximum speed that a persona can handle is one h/u per point of DEX.

=== Speed Penalty
.Speed penalty  (DD) = (speed  h/u - dexterity) / 10
****
Driving at 20 h/u with 10 DEX is a +1 DD penalty. +
Having a bonus for driving slow is up to the referee.
****

Thus a player with a DEX of 10 could travel at ten h/u (36 km/h) without having a speed penalty.
For every ten h/u (36 km/h) over this driver's maximum speed, any maneuver increases by 1DD.
A  persona with a 10 DEX is cruising at 40 h/u (144 km/h). 
The degree of difficulty has a speed penalty of +3DD.
Even trying to drive straight can be dangerous at high speeds.

=== Maneuver Difficulty

include::ROOT:partial$CH17_Table_Example_Maneuvers.adoc[]

=== Determine Target Roll
The target roll can be calculated or tabulated. 
The table is included here for quick target roll checks. 
The tables below are connected copies from the section on performance tables. 

The target roll can be tabulated or calculated.
A tabulated target roll employs a table comparing the degree of difficulty to skill score. 
A calculated target roll employs simple maths to determine the target roll.
Very high skill scores and very high DDs require calculation.

xref:i-roll_playing_rules:page$CH14_Performance_Tables.adoc[tag=target_rolls]

=== Roll 1d100
If the player rolls the target number or higher, they have won the driving roll.
A successful driving roll indicates the driver has maintained control and exits the collision checklist.
No one in the vehicles notices anything at all.
If the player fails the driving roll, something has gone wrong, and the persona must rally the vehicle.
The vehicle and passengers are one step closer to a collision, and the player now has to win a rally roll.
Tension mounts.

== Rally Roll
If a player fails her driving roll, all is not lost.
The driver has a chance to recover from her driving error through dexterity and skill.
The rally roll is a modified attribute roll using the persona's dexterity and driving skills.
The degree of difficulty is the same DD from the driving roll.

include::ROOT:partial$CH17_Table_Recovery_DEX_Roll.adoc[]

A successful rally roll indicates the driver has maintained control and exits the collision checklist.
A rally roll represents actions that are obvious to everyone in the vehicle.
There may be some dramatic overcompensation or even profanity from the driver.
A failed driving rally roll moves the expedition further down the collision checklist.
The driver has lost control of the vehicle, and the dice are taking over the story.
Tension mounts even more.

== Loss of Control
To arrive here, the player has lost both her driving roll and her rally roll.
The loss of control could be just plain unlucky, but the vehicle was going too fast more often.
Things are now getting dangerous.
Loss of control of the vehicle allows it to travel in a somewhat random direction.
The loss of control is temporary, and if there still is a chance that no collision will occur.

Loss of control has three elements. 

.*Loss of Control*
. Duration
. Deceleration
. Direction

====
These three elements may or may not lead to a collision. 
====

=== Duration
The loss of control of the vehicle will last for 0 to 3 units (1d4-1).
The driver loses control of her vehicle for that duration of time.

If the vehicle is travelling ten h/u and loses control for three units, the vehicle will travel for 30 hexes out of control.

Deceleration and deviation simulate the vehicle careening out of control every unit. 
This period is when everyone in the vehicle is screaming in fear, especially the nothing personas.

=== Duration of Loss of Control
.Duration = 1d4-1 units (0-3 units)
****
A result of  0  indicates this unit only.  +
A result of 3 indicates this unit and the next two.
****

=== Deceleration
This speed loss can be from sensible braking, mad deviations, or both.
While the driver is trying to regain control of the vehicle, the most common reaction is to brake.
Swerving around also wastes energy, and a vehicle out of control *always*  slows down.

The vehicle will decrease its speed by 0%-50% (1d6-1) each unit of lost control.
A 0% deceleration indicates no loss of vehicle speed.
A 50% deceleration indicates that the vehicle will be travelling at half its original speed.

The deceleration can be quite hazardous to the passengers if they lack proper restraints (aka seat belts).
The decelerated speed is the one that determines the damage if an accident should result.

=== Deceleration In Loss of Control
.Deceleration = 1d46-1 times 10%
****
A 1d6 result of 1 =  0% deceleration. A 1d6 result of 3 = 20% deceleration.
****

=== Direction
Finally, the direction of the loss of control is determined by the roll of percentile dice.
The last one, deviation, is left to the discretion of the referee.
The ref must decide whether the vehicle-deviates left, right, or in some cases up or down;
this is usually done randomly.

include::ROOT:partial$CH17_Table_Deviation_During_Loss_of_Control.adoc[]

:art: Figure_Deviation_Hex_Degrees.png
:width: 250px
:snark: Faceting the music in loss of control.
:artist: HM
:date: 2010
:license: CC BY-SA 4.0
:description: Diagram of hexagon demonstrating turn radius and difficulty.

include::ROOT:partial$articulate.adoc[]

____
*Loss of Control may result in a Collision. Make a Collision Check.*
____

== Collision Check
Losing control of a vehicle may result in an collision.
A collision can only occur if the driver's loss of control causes the vehicle to crash into some obstacle, or careen off the road.

.*Collision Indicated*
* loss of control path crosses:
** another vehicle's path
** an obstacle
** goes off the road
* change of grade by 1/2 a hex
* confined space with no other option
* parameters decided by the referee

:art: vehicle_collision_imminent.png
:width: 250px
:snark: Cosmic Highway Patrol
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of three space age vehicles in a tussle on a futuristic highway.

include::ROOT:partial$articulate.adoc[]

== Collision Damage 
The deadliness of a crash depends on the speed of the vehicle.
The higher the speed, the more dangerous the collision.
The speed of the collision determines the energy of the collision.
The energy of the collision determines the  amount of damage delivered.
The vehicle and passengers are damaged simultaneously

NOTE: *Driving is safe. Crashing is dangerous.*

=== Relative Speed and Damage
The speed at which the vehicle collides determines the severity of the accident.
The vehicle should use its decelerated speed as the collision speed.
The vehicle speeds are combined to inflict damage to both vehicles.

.*Relative Speeds*
. Head on add speeds (front 3 facets)
. Rear on subtract speeds (back 3 facets)
. Other ons use highest speed

include::ROOT:partial$CH17_Table_Collision_Damage.adoc[]

=== Relative Wate and Damage
Speed indicates the energy delivered by a collision, but that is not the whole picture.
The relative wates involved in the collision need to be considered.
If relative wates are ignored, problems will arise.
A moped could ram an 80 ton military tank at high speed and kill the tank crew.
Or a jet plane crashes into convertible and convertible driver escapes injury.
There are some faux Newtonian solutions to these potential problems.
The 

=== Collision Wate Multiplier
.Damage Multiplier = Larger vehicle wate / Smaller vehicle wate  
****
Cannot exceed 4 times damage or  1/4 damage.
****

If a 1200 kg vehicle collides with a 400 kg vehicle the larger vehicle would take 1/3 damage. 
The smaller vehicle would take 3 times damage.
The damage multiplier is rounded to the nearest easy number (1, 2, 3, 4) or (1, 1/2, 1/3. 1/4).
The damage factor cannot be increased more than 4 times greater, or be reduced by less than 1/4.

== Persona Damage
Collisions can deliver massive amounts of damage and easily kill personas.
Collision damage works the same as any other damage inflicted on the persona.
The indicated damage die roll is made and subtracted from the persona's HPS total.
The damage can be rolled once for all the personas involved, or individually for each persona.

Every persona involved in the collision takes the HPS damage.
If two vehicles collide, then all the personas in both vehicles take damage.
A collision at 35 h/u, every passenger in both vehicles would take 6d10 HPs in damage.
Relative wate can increase the damage by up to 4 times, or decrease it by 1/4.

Pedestrians hit by vehicles will take damage as if they were in an accident with the vehicle.
A vehicle travelling 35 h/u would do 6d10 to a pedestrian.

=== Unrestrained Personas
A deceleration of 50% will damage to unrestrained passengers.\
Technically this could happen without a collision.
For instance a vehicle that slows down to 50 h/u from 100 h/u means that inertia will carry personas into the bulkhead of the vehicle at 50 h/u.
Smart explorers wear their seat belts!!

== Vehicle Damage
Vehicles do not have hit points.
They are damaged in a fashion similar to other inorganic objects.
Vehicle damage resembles robot, exatmo vehicle, and artifact damage.
The higher the speed of the vehicle has its collision at the more damage that it endures.

A vehicle in a collision at 8 h/u will not sustain damage, but the passengers may.
A vehicle in a collision at 28 h/u would take 3 vehicle damage rolls.
A vehicle that collides at 60 h/u (250 kmh) would take 6 damage table rolls.

Each vehicle damage roll indicates a location of damage and extent of damage. 
The location of damage is completely random. 
The extent of damage can be random or modified depending on the irritation level of the referee.

=== Location of Vehicle Damage
A roll on the Location of Vehicle Damage table must include an Extent of Damage roll.
The location of damage determines which vehicle function is affected by the accident.

include::ROOT:partial$CH17_Table_Location_of_Vehicle_Damage.adoc[]

=== Extent of Vehicle Damage
The extent of damage roll indicates the decrease in efficiency of the damaged part.
Major damage would decrease function by 40% of previous efficiency.
Damage to the speed system would reduce the vehicle's speed by 40%.
The maximum speed of 30 h/u would be reduced to 18 h/u.
Vehicle system damage is cumulative.
For more details on damage see xref::CH21_Artifact_Damage.adoc[Artifact Damage].

include::ROOT:partial$CH21_Table_Artifact_Extent_of_Damage.adoc[]

Extent of damage can be modified by the Collision Wate Modifier.
The referee may multiply the extent of damage roll by the multiplier.
So if the player rolls 50 on the Extent of Damage Table the roll could be reduced by 1/4.

=== Further Complications
There are further complications that the ref may be interested in.
Passenger entrapment equals to 1% per HPS of damage inflicted on the passenger.
Post collision fire is dependent on fuel type and damage to the fuel system.
Whether the vehicle is drivable depends on the damage to systems during the collision.
Final vehicle resting position is entirely up to the decision of the referee.



