= Encumbrance

Encumbrance represents the burden of equipment that the persona has elected to carry.
Everything that the persona wears or carries is included in encumbrance.
This includes: clothing, armour (unless worn), ammunition, weapons, food, and any with a wate.
This section does not cover the philosophical elements of encumbrance,
The age old questions of which is more difficult to carry, 2 kgs of oxygen, or 2 kgs of lead?

:art: encumbrance_desert_pack.png
:width: 250px
:snark: All my stuff.
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Encumbrance is a roll playing tool to afford some faux realism to carrying and lifting stuff.
A persona shuffling through the underbrush with 3 tonnes of equipment would be unrealistic.
Equally, players shouldn't be burdened with an exacting milligram calculation of their equipment list.
Encumbrance is check against carrying the kitchen sink, along with the house. 
The referee can check in on encumbrance once in a while to keep things in check.

Occasionally encumbrance rule can be the center of a scenario or puzzle.
If a single persona cannot lift the essential artifact which persona can?
Or how much loot can be carried out before the demolition clock runs down?

:art: ecumbrance_hurdle.png
:width: 250px
:snark: Free vs Encumbered.
:artist: Andrew Brechin
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

== Determining Wate Allowance
The persona's Physical Strength (PSTR) is what determines how much a persona can carry.
Each PSTR has it's own assigned Wate Allowance. 
Wate Allowance is generated when creating the persona. 
The stronger the persona the more they can carry and lift.
Did you forget to generate Wate Allowance for your persona?

.*Go Visit Wate Allowance*
* xref:i-roll_playing_rules:CH04_Anthros_WA.adoc[Anthro Wate Allowance, window=_blank]
* xref:i-roll_playing_rules:CH05_Robots_Z_WA.adoc[Robot Wate Allowance, window=_blank]
* xref:i-roll_playing_rules:CH06_Aliens_9_WA.adoc[Alien Wate Allowance, window=_blank]

=== Persona Size and Wate Allowance
Bigger personas can lift more stuff. 
The Wate Allowance of the persona is multiplied by the WA Adjustment.

include::ROOT:partial$CH18_Table_Alien_Size_and_Encumbrance.adoc[]


== Encumbrance Levels
Wate Allowance is a solitary number.
Many groups will stop at the single number.
The Roll Playing System divides the WA into qualitative descriptors that affect performance
The persona's Physical Strength (PSTR) is what determines how much a persona can carry.
Encumbrance levels show the impact of carrying too much stuff.

.*Encumbrance Levels*
. Free
. Un-encumbered
. Encumbered
. Over-encumbered
. Lift Only

=== Free
Free from all encumbrances.
This persona is carrying nothing and may be wearing even less.
Restrictive civilian clothing may jeopardize a persona's Free encumbrance level.
Carrying anything removes a persona from the Free encumbrance category.
Flora and fauna are always free of encumbrance.

=== Un-encumbered
This persona is carrying very little equipment.
Wate Allowance determines how much equipment the the persona can carry with impairing their function.
A persona is un-encumbered if she is carrying less than 1/4 her wate allowance (WA).
A persona with an 11 PSTR has a WA of 16 kgs.
She could carry up to 4 kgs, and still be un-encumbered.

=== Calculate Un-Encumbered Level
.wate < Wate Allowance / 4 
****
20 kgs WA. The persona to carry up to 5 kgs of stuff and remain un-encumbered.
****

=== Encumbered
Encumbered is the normal state for most personas.
Personas can carry a certain amount of equipment and not be hampered doing so.
Wate Allowance determines how much equipment the the persona can carry with impairing their function.
Encumbered personas are carrying anywhere from 1/4 to 1 and a 1/2 times their wate allowance (WA).
So the persona with a wate allowance of 16 kgs could carry up to 24 kgs, and only be encumbered.
This is the normal range of wate bearing for the persona, any greater wate will have a detrimental effect on the function of the persona.

=== Calculate Encumbered Level
.wate < Wate Allowance * 1.5
****
20 kgs WA. The persona to carry up to 30 kgs of stuff and remain encumbered.
****

=== Over-encumbered Level
This persona is carrying too much stuff.
They are starting to feel the impact of the wate on their ability to function.
Wate Allowance determines how much equipment the the persona can carry with impairing their function.
An over-encumbered persona is carrying between 1 and 1/2 to 2 and 1/2 times her WA.
The persona with the 11 PSTR would be over encumbered carrying between 24 and 40 kgs of equipment.

=== Calculate Over-encumbered Level
.wate < Wate Allowance * 2.5
****
20 kgs WA. The persona to carry up to 50 kgs of stuff and remain over-encumbered.
****

=== Lift Only
This persona has reached the limit of what they can carry.
Any wate over the over-encumbered can only be lifted.
The persona can do nothing other than lift the wate.
This could be a single object or a rucksack full of random junque.
Nothing but lifting is going on here.

Any load greater than 2 and 1/2 times the persona's wate allowance can only be lifted.
To successfully lift this amount requires a successful Attribute Roll using PSTR.
The more the wate exceeds the persona's Lift Only encumbrance level the more difficult the Attribute Roll.

=== No Wait Wate Allowance Table
If you do not want to do arithmetic this table is available for quick determinations of encumbrance levels.
If a large or gigantic persona has exceeded the values on the table then arithmetic is still required.

include::ROOT:partial$CH18_Table_Wate_Allowance_and_Encumbrance.adoc[]

== Encumbrance Effects
The encumbrance categories are neat and interesting, but how they affect the performance of a persona is what really matters.
The remaining paragraphs describe how being encumbered, and over-encumbered  the persona's overall efficiency.
All of the tables are optional, but reading through them should give the impression that the more you carry the worse off you are.

=== Performance Rolls
Carrying too much equipment has a detrimental effect on the persona's ability to perform class skills.
The higher the encumbrance level the more difficult maneuvers become.
Encumbrance is not just about wate. 
It also includes restrictiveness and entanglements impairing performance.
The persona simply needs to set the stuff down to avoid the Performance Roll penalty.
A 6DD maneuver attempted while encumbered would become a 9DD maneuver.

When encumbrance rules are being used to simulate high gravity environments personas cannot escape the penalties.

include::ROOT:partial$CH18_Table_Encumbrance_and_Performance_Rolls.adoc[]

=== Movement
Encumbrance has its greatest effect on combat movement.
The greater the load on the persona, the more difficult it is to move.
Specialized movement rates like bolting and running cannot be used if the persona is encumbered.
Non-combat movement is only qualitative and is not affected directly by encumbrance.

include::ROOT:partial$CH18_Table_Encumbrance_and_Movement.adoc[]

=== Initiative
The less encumbered persona will get to act first.
A persona loaded down with equipment, will have a hampered response time.
An over-encumbered persona that rolled 18 on her initiative roll would have it reduced to 15.

include::ROOT:partial$CH18_Table_Encumbrance_and_Initiative.adoc[]

=== Driving
Personas must be free or unencumbered to drive or pilot any vehicle.
This includes inatmo and exatmo vehicles
Driving rolls will be impaired the same as performance rolls by encumbrance levels.

=== Attribute Rolls
Some attribute rolls are affected by encumbrance levels.
The higher the encumbrance level the more difficult the Attribute Roll. 
Actions like getting up, balancing, jumping, climbing are impacted by encumbrance.
Attribute rolls for DEX, PSTR, can occasionally be affected by encumbrance levels.
Actions like doing math, smiling, psionic attacks are less impacted by encumbrance.
Attribute rolls for  AWE, CHA, INT and MSTR are less affected by encumbrance levels.
