= Artifact Identification

Technology is diverse and prolific, and not all technological devices can be immediately identified by personas.
Consider the potpourri of technological devices if they were drawn from an entire universe of cultures, and technological levels.
Having personas figure out how a TOY works through role playing would be spectacular.
Due to the cumbersome nature of this endeavour (code for crushing the referee) an example is included here.
This tool is called the artifact identification flowchart. 

NOTE: *The AID Flowchart is a rename of the AID System due to the tragic epidemic on Mundane Terra.*

The flowchart is to be used with discretion.
The AID Flowchart should not be used by the referee to keep personas from using a spatula.
The AID Flowchart should not be used by the players to roll themselves through a scenario.
The referee should decline using this mini game for devices that are too important or too mundane.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*


== Using the Flowchart
The flowchart should be fun to use. 
Consider it a descriptive mini-game used to replace a process that is too complex to role play.
Role playing definitely impacts the flowchart.
As does experience level, personas INT, tech level of device, and most importantly luck. 

The player navigates the flowchart with a series of *1d10 rolls*. 

// duration per roll

:art: aid_table.png
:width: 650px
:snark: Playing with fire for science.
:artist: HM
:date: 2010
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

=== Research Teams
Personas can get together to improve their chances of successful identification.
Two heads are better than one, or many hands makes confusing work. 
The referee can allows as many personas to join in as makes sense.
An artifact may not dispose itself to being surrounded by curious personas.

Every participant on the AID Research Team get's to roll a 1d10.
The referee can average this roll. 
Averaging is arithmetically challenging and can trap the team in a loop.
This a very common problem with teams on Mundane Terra.

A more exciting approach is to have all the players roll at once. 
The highest roll is paired against the lowest roll. 
A CHA Attribute Competition is carried out to see which 'idea' moves the team forward.
This a very common problem with teams on Mundane Terra.

=== Duration of AID
Each roll on the AID Flowchart takes one hour of game time. 
The referee can alter the game time required for each roll of the 1d10.

A complicated low tech cloning machine should not be sorted out in a few minutes by a persona.
An obvious gun looking gun should not take a mercenary 10 days to figure out.

To make the AID Flowchart more faux realistic the referee can change the duration of each roll.
This would only be of import if there was some kind of time pressure placed on the expedition.
For example, can the fusion rifle be identified in time for the mercenary to use it?
Or can the rejuvenation chamber be activated before the dead personas starts to smell?

Each roll on the flowchart can represent minutes, hours, days or even weeks.
The flowchart has been used where each roll represents a year and several adventures before advancing.
In the end the flowchart should be fun to use.

== Start
The player starts out on this location once they have committed to identifying the artifact.
Start is for a persona starting cold with the artifact.

=== Restarting 
If a persona stops the identification process she may be able to pick up where she left off.
A persona can restart where she left off as long she restarts in less than 24 hours.
A player may elect stop rolling if they feel things are going badly.
For example, if the artifact is making scary accidental activation noises it may be best to stop.

== Colour Positions
The colourful circles are for adding colour commentary to the flowchart process. 
There referee may associate each circle with a particular sound or mechanism position.
These embellishments can be for fun, or be they can be used as clues.

For example, position A could fill the persona with a sense of 'nearly there' or an equivalent sound effect.
Or landing on position E could make a scary activation noise or activate a countdown timer.

A player can exit the process at any colour position. 
The player cannot exit the flowchart if they land on a decision point. 
She can return the next day to start at the same location, wait longer to start fresh at Start.

== Identified!
The Identified! flowchart endpoint indicates the person has figured out what the artifact is.
The artifact can no longer accidentally harm the persona.
If the artifact is simple a successful AID can include how to operate it.
Identification does not indicate that she knows everything about the artifact.
Identification should protect the persona from immediate harm.
For example a nuclear device would no longer be thought of as portable oven.
This does not mean the persona is skilled at using the artifact, knows it's value, or knows its tech level.

:art: bot_tv_hand_win.png
:width: 250px
:snark: I knew it all along.
:artist: StudioStoks, mod HM
:date: 2018
:license: Copyright by StudioStoks

include::ROOT:partial$articulate.adoc[]

Identification of an artifact can mean many things.
The referee must remember that Identification is a __positive__ result.
Usually identification only indicates the general use of the artifact type.
For example, this is a medical device for healing (not a bomb), this is a drug (not perfume), this is a napalm aerosol (not hair spray).

Complete identification of an artifact depends on the persona's vocation.
Some artifacts have specific vocation designations.
For example, mercenaries can identify bombs, aerosols, and weapons.
Or climbing equipment is can be fully identified by a nomad.

== Activated!
The Activated! flowchart end point indicates that the persona has unwittingly turned on the artifact.
For weapons, bombs and grenades, the effects can be deadly.
However accidental activation is not all bad.
A lot of information is revealed with an accidental activation. 
The players may be able to identify the artifact just by what happens. 

:art: bot_tv_hand_activated.png
:width: 250px
:snark: I meant to do that.
:artist: StudioStoks, mod HM
:date: 2018
:license: Copyright by StudioStoks

include::ROOT:partial$articulate.adoc[]

Personas learn a lot from an accidentally activated TOY.
Accidental activation for a vocation specific TOY also counts as an identification.
A mercenary persona that accidentally fires a weapon has also identified it.  

Other persons return to the Start with additional information.
The new information gives a +2 bonus on all successive AID rolls.
The bonuses for accidental activation are cumulative.
Another accidental activation increased the bonus to +4.

Damage! and Activation! bonuses are cumulative.

== Damaged!
The Activated! flowchart end point indicates that the persona has injured the TOY in some fashion.
Arrival at this destination could be announced by horrible crunching noises, or sickening splats.
After this occurs, the identifier returns to the start.

:art: bot_tv_hand_damaged.png
:width: 250px
:snark: It was on fire when I got here.
:artist: StudioStoks, mod HM
:date: 2018
:license: Copyright by StudioStoks

include::ROOT:partial$articulate.adoc[]

The player checks to see how severely the artifact was damaged on the Extant of Equipment Damage Table.
More detailed artifact damage is found in the  xref::CH21_Artifact_Damage.adoc[Artifact Damage,window=_blank] section.
Artifact damage requires the subtle intervention of the referee.
Some artifacts just can't be broken.
Other artifacts are obviously delicate.

include::ROOT:partial$CH21_Table_Artifact_Extent_of_Damage.adoc[]

Personas learn a lot from an damaging a TOY.
The persons return to the Start with information about what not to this time.
The new information gives a +1 bonus on all successive AID rolls.
The bonuses for damaging an are cumulative.
Another artifact damage improves the bonus to +2.

Damage! and Activation! bonuses are cumulative.

== AID Flowchart Adjustments
There are many factors that affect the persona's navigation through Artifact Identification.

=== Vocation Adjustments
Mechanics enjoy a very special advantage over all other vocations.
A player with a mechanic persona uses 1d12 instead of the 1d10 roll allotted to all other personas.
Mechanics can also lead a research team and their ideas (rolls) are not subject to CHA Competitions.

The referee may offer bonuses to vocations that are identifying TOYS that there TOY Type.
For example, a mercenary could get a bonus when trying to AID a weapon or armour.
This is an optional bonus as personas get vocation based bonuses for accidental activation as well. 
A persona centered version of the AID Flowchart allows the player to add her EXPS Level to vocation relevant equipment.

include::ROOT:partial$CH20_Table_Class_Specific_Artifacts.adoc[]

== Tech Level Adjustments 
level is a term that loosely represents the artifact's level of technological development.
A person from the Middle Ages would almost certainly be at a loss in a modern kitchen.
Conversely it would be a challenge for someone from today's high-tech kitchen in a Middle Ages kitchen.

The Tech Level AID adjustment is based on the assumption that the persona is from a tech level 10 milieu.
Tech Levels 6-12 are similar enough not to present any serious difficulty to the identifier.
For example, a person from our own technical society (Terran, western, 1980) would have a good idea of how to operate most 19th century artifacts, and will likely to be able to function up to about 50 years into the future.
Beyond this TL 6-12 range, there are probably enough unfamiliarity to confuse a persona--hence, penalties are added, at the rate of minus 1 per Tech Level above 12, and below 6.

If the referee's milieu is based on a higher or lower tech level world she can should adjust accordingly.

include::ROOT:partial$CH20_Table_Tech_Level_and_AID.adoc[]

Some high tech devices can be combined devices. 
Multi equipment is quite common for high tech TOYS.
There is also the possibility that high tech devices come with instructions.
Whether these are linguistically helpful or confusing is determined by the referee's milieu.

== Other Adjustments 
Adjustments are added  depending on how the persona conducts her study of the artifact.
For example, if the player says that her persona is being very careful she will add 3 to her 1d10 roll whenever on circle E (accidental activation possible), or on circle F (artifact damage possible).
However being careful extends the time taken for identification.
Rushing along can speed up the time to identification, or accidental activation.

include::ROOT:partial$CH20_Table_AID_Style_Adjustment.adoc[]

