= Equipment Damage

Personas aren't the only things that get destroyed in EXP.
Besides the ceaseless battering of personas, inorganic equipment is also subject to the effects of entropy.
EXP's premise of equipment is that nothing is indestructible, everything wears out, and what can go wrong will.
Equipment damage is reserved for unique circumstances and is not part of regular game play.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

Equipment do not have HPS Totals like personas.
It would be total bore to keep track of equipment HPS.
Equipment HPS are used for unfortunate circumstances where the referee needs to quantify a mishap.
A crucial artifact that is the center piece of a campaign may warrant a HPS total.
For example if a persona decided to use her prized plasma rifle to stop a fortified door from closing.
This would warrant a damage check if it fit the story.
Non-artifact equipment, aka mundane, equipment is usually just destroyed by incidents.
If perchance mundane equipment is important then there are some HPS guidelines.

== Determining Artifact HPS
Artifact equipment is created using the TOYS. 
These are useful valuable pieces of equipment.

Artifact equipment is based on it's EXPS value, intended use and tech level.
The more EXPS value the tougher it is.

include::ROOT:partial$CH21_Table_Artifact_Hit_Points.adoc[]

For example, a tech level 10 Age Determiner is worth 200 EXPS.
Medical equipment earns 3% of EXPS for HPS.
So this device can withstand 16 HPS of damage (3% x 200 + 10) before being damaged.

A tech level 20 napalm grenade is worth 540 ExPs.
Grenades earn 20% of their EXPS value as HPS.
So this grenade would have 128 HPS (20% x 540 + 20).

== Damaging Equipment
Artifacts are technomagical and are composed of alloys, and polymers.
Equipment is most often damaged by AOE attacks, direct hits, kinetic tragedy and malice.
Anything that damages a persona will damage equipment.

:art: falling_gun.png
:width: 250px
:snark: Oops, kinetic tragedy!
:artist: HM
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of high tech pistol falling towards the ground.

include::ROOT:partial$articulate.adoc[]


== Extent of Damage
Nothing happens to the equipment until it reaches zero HPS.
When this happens the toy does not go unconscious or die but it is randomly damaged.
The extent of damage roll shows what percentage of previous function the toy presently has.
This can vary from no damage what-so-ever (trivial), to complete destruction (destroyed) of the artifact.
Complete explanations of these effects are detailed under Extent of Damage in this chapter.

include::ROOT:partial$CH21_Table_Artifact_Extent_of_Damage.adoc[]

The extent of damage roll can range from trivial to destroyed.
Massive amounts of damage can generate multiple rolls on the extent of damage table.
For example an  artifact with 5 HPS taking 15 HPS damage at once would get 3 rolls on the table.
The damage would be cumulative likely destroying the artifact.
Ouch.

=== Trivial Damage
The least detrimental is trivial damage.
Trivial damage does not affect performance of the device.
The damage could be cosmetic or a mere annoyance.
Such as a stuck button or scratched finish.

=== Minor, Major and Critical Damage
A toy which has sustained minor damage will function at 90% of previous performance, a device sustaining critical damage will function at 30% of regular performance.
Successive damaging effects are cumulative, 2 bouts of critical damage, with no interim repairs, would leave an artifact at 9% performance.

Cumulative damage rolls can disable a toy without destroying it.
The results of reduced performance affects all aspects of the device's performance.
Range, battery duration, duration of effect, area of effect, to hit bonuses, and armour ratings are examples of what is reduced when equipment is damaged.

If the age determiner discussed earlier were critically damaged (30% of previous performance) its new range would be 1 hex, its new battery life 1.5 years, its value reduced to 1500 eps, and possibly its accuracy reduced to 30% (30% chance of success per use).

Damaged artifacts can be repaired. 
The more damage the more difficult the repair.
Destroyed artifacts cannot be repaired.

=== Destroyed
The worst possible damage that a device can sustain is destroyed.
When equipment is destroyed, it will not function and cannot be repaired.
Destroyed equipment cannot be repaired, the artifact becomes a dead wate which may only be valuable for a few spare parts.

=== Instantaneous Destruction
When an artifact is destroyed in one blow there may be additional consequences.
Do destroyed bombs, or grenades, detonate themselves?

Sphincter dice should be consulted to determine if a bomb or grenade is accidentally detonated.
This would be rare situation, something more likely to happen to an enemy, than an expedition.

NOTE: *Accidental activation adds injury to insult*

=== Maintenance
Maintenance of equipment is for those referees and players working through OCD.

Equipment that is used, but un-maintained, will deteriorate at a rate of 1 HPS each month it is used.
A month of use is any month in which the device is deployed.
Un-maintained toys will lose 1 HPs each month of use until no HPs remain.
At that point a roll is made on the Extent of Damage table.
When the extent of damage roll is made, an important component may malfunction, or some unimportant button may get sticky.

Equipment subject to any semblance of routine maintenance is not be affected by wear and tear.

:art: equip_damage_chicken.png
:width: 250px
:snark: Rubber chick organ maintenance is crucial
:artist: Andrew Brechin
:date: 1991 
:license: CC BY-SA 4.0
:description: Drawing of tuxedo clad humanoid pulling chicken out of futuristic music organ.

include::ROOT:partial$articulate.adoc[]

== Mundane Equipment Damage
Personas will often insist on damaging absolutely mundane items that surround them.
They may wish to destroy a door, crash through a wall, blow a hole in the road, or destroy a bridge.
It is impossible for the referee have the HPS of architectural items such as walls, doors, windows and the like prepared for each particular scenario.

While specific items, ones expected to be destroyed, may have HPS ready, most sane referees will not have detailed HPS of the chairs and doors in their scenario.
Mundane items are not treated the same as toys from the technology section of this book.
Mundane Doors and-walls are destroyed when they lose all their HPS.
For instance, a mundane door has 30 HPS.
If a door takes 30 HPS it ceases to be a door and now is an opening with sharp edges.

include::ROOT:partial$CH21_Table_Mundane_Artifacts_Hit_Points.adoc[]
