= Negotiations

Negotiation is the only game system which appears to be replacing role-playing.
Negotiation should not be used to replace interactions between player personas and referee personas.
The negotiation system should be used by the referee to assist making a decision for a referee persona where one hasn't already been predetermined.

The negotiation tables give results for conversations between the expedition and intelligent aliens, civilians, or mad robots.
Negotiation rolls bring some essential randomness into scenarios.
If refs are forced to continually improvise, their own personality will invade all the personas that they play, and their actions will become predictable.
Negotiation does not apply to detailed scenarios where reactions are predetermined like: ambushes, pirate raids, muggings, or starving aliens.

:art: negotiation_peace_gorilla.png
:width: 250px
:snark: Chill dude.
:artist: Unknown 
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

.*Rolled Negotiations*
. Combat or Social
. Pre-Negotiation Roll (first impression)
. Negotiation Roll (communication) 

== Combat or Social
This determination is simple.
If there is a chance of combat happening then the Combat Negotiation Table is used.
Examples included first contact, rogue expeditions meeting, etc.
The Social Negotiation is reserved for everything else.
Examples include getting a permit, buying a trinket etc.
A social negotiation will only devolve into combat by specific actions by the players.

== Pre-Negotiation Roll
The pre-negotiation represents the first impression the referee personas have about the expedition.
The first impressions are unspoken and unconscious.
The pre-negotiation first impression is made as the two expeditions approach each other.
The pre-negotiation consists of judging the smell, numbers, and body language of the expedition.
Referee personas may sniff and stare at the expedition.

The pre-negotiation roll is made on a 1d100.
The referee secretly makes the 1d100 Pre-Negotiation roll. 
It is possible that things may immediately go off the rails.
A roll less than 10 in a combat pre-negotiation roll may lead to immediate attack without negotiation.
A roll greater than 90 in social pre-negotiation roll may lead to immediate open helpfulness.
A decisive roll precludes further negotiations.

== Negotiation Roll
If the first impression did not determine the outcome of the negotiation an actual negotiation occurs.
This allows the players and referee to engage their personas in a cursory chat.
This is an actual negotiation.
The referee should always defer to role-playing leads from the players. 

The negotiation roll is made on a 1d100.
The referee secretly makes the 1d100 Negotiation roll. 
It is possible that things may immediately go off the rails.
A roll less than 10 in a combat negotiation roll may lead to immediate attack without negotiation.
A roll greater than 90 in social negotiation roll may lead to immediate open helpfulness.
The actual negotiation roll is subject to many modifiers.
The most important modifier is how the players choose to role play.
There are example modifiers for each of negotiation tables.

== Social Negotiation Table
Not all failed negotiation results in violence.
A merchant isn't going to attack a persona that walks into her shop.
A shopkeeper's tone may vary from openly helpful to belligerent.
However combat with a customer in her shop is an impossibility.

Other social negotiation examples are:
* receptionist
* traffic citation
* sales representative
* reservations

For example, a persona goes to buy a loaf of Krenoj at the local Krenojeri.
This is a social negotiation as this is typically not a lethal encounter.
The cashier at the Krenojeri is a quiet, conservative avarian.
The persona buying the Krenoj is a flamboyant, exotically dressed feline (11 CHA).

The pre-negotiation roll is 42.
All signs indicate that the cashier is will treat the customer in a perfectly functional manner.
The feline's CHA is added to the roll, making it 53.
This is still functional.
The two personas have conflicting personalities and dress types.
This results in an adjustment of -10 reduces the roll to 38.
This moves the cashier's service level to Below Functional.
Not much comes of this in the pre-negotiation roll.

When it comes to placing the krenoj order a negotiation roll must be made.
The negotiation roll is 21. 
The feline's CHA is added to the roll, making it 32.
This is still below functional.
The personas have conflicting personalities and dress types.
This results in an adjustment of -10 reduces the roll to 12.
The cashier becomes belligerent and unhelpful.
It is likely the transaction will occur, but the persona will get second rate krenoj.

include::ROOT:partial$CH22_Table_Social_Negotiations.adoc[]

include::ROOT:partial$CH22_Table_Neg_Ex_Social.adoc[]

== Combat Negotiation 
Some failed negotiations can result in violence. 
A potential combatant may avoid combat if they are intimidated.
Or they may become enraged by ancient unknown triggers.

:art: hand-to-clamp-combat.png
:width: 250px
:snark: Negotiation failure.
:artist: StudioStoks, mod. HM
:date: 2015
:license: Copyright StudioStoks

include::ROOT:partial$articulate.adoc[]

The Combat Negotiation Table is used for encounters that may result in combat.
This does not mean that combat will happen. 
A positive outcome is still possible through the negotiation.

Situations for combat negotiations:
* wilderness encounter with intelligence alien herd
* encountering a group of drunken revellers 
* encountering another expedition searching an old laboratory 

For example, the expedition meets another expedition foraging an ancient ruin for artifacts.
It is not a case of ambush.
However both expeditions are surprised to encounter the other.
The player expedition sends their best spokesperson to approach.
She is a canine nothing with a CHA is 17.

The pre-negotiation roll is 55.
There are a few adjustments.
The expedition clearly has bigger guns and +10 is added to the roll.
The persona's CHA score is added +17 to the roll.
The total pre-negotiation roll is 82 and the fellow foragers exude good intentions.

The negotiation roll is 65.
There are a few adjustments.
The expedition clearly has bigger guns and +10 is added to the roll.
The persona's CHA score is added +17 to the roll.
The player chooses her persona to be polite and complimentary +5.
The total negotiation roll is 97 and the fellow foragers are openly helpful.
They may give tips about dangers, or help out wounded. 

include::ROOT:partial$CH22_Table_Combat_Negotiations.adoc[]

include::ROOT:partial$CH22_Table_Neg_Ex_Combat.adoc[]
