= Interactions

The players cannot use interactions to replace role-playing between player and referee personas.
The referee should use the interaction system to assist decision-making for referee personas.

The interaction tables give results for conversations between the expedition and intelligent aliens, civilians, and mad robots.
Randomizing referee persona interactions prevent the referee's personality from being infused in all her personas.
Interaction rules do not apply to detailed scenarios like ambushes, pirate raids, muggings, or starving aliens.

:art: negotiation_peace_gorilla.png
:width: 450px
:snark: Chill dude.
:artist: Unknown 
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid gorilla wearing casual clothing and waving peace sign.

include::ROOT:partial$articulate.adoc[]

.*Rolled Interactions*
. Combat or Social
. First Impression
. Negotiations

== Combat or Social
This determination is simple.
If there is a chance of combat happening, then the Combat Interaction Table is used.
Examples included first alien contact, rogue expeditions meeting, etc.
The Social Interaction Tables cover non-combat meetings.
Examples include getting a permit, buying a trinket etc.
Social interactions will only devolve into combat if the players make it so.

== First Impression Roll
The first impression is a pre-negotiation roll.
The first impression reflects what the referee personas think about the expedition before they open their mouths.
The first impressions are unspoken and unconscious.
The first impression involves judging the smell, number, and body language of the expedition.
Referee personas may sniff and stare at the expedition.

The referee secretly makes the 1d100 first impression roll. 
Things may immediately go off the rails.
A roll less than 10 in a combat first impression roll may lead to immediate attack without negotiations.
A roll greater than 90 in social first impression roll may lead to immediate open helpfulness.
A decisive first impression roll may preclude the negotiation roll.

== Negotiation Roll
If the first impression did not decide the interaction outcome, the referee might make a negotiation roll.
The negotiation roll determines what takes place after the first impression.
The referee should always defer to role-playing leads from the players. 

The referee secretly makes the 1d100 negotiation roll. 
Things may immediately go off the rails.
A roll less than 10 in a combat negotiation roll may lead to an immediate attack.
A roll greater than 90 in the social negotiation roll may lead to immediate open helpfulness.
The negotiation roll is subject to many modifiers.
The most important modifier is how the players choose to role-play.
There are example modifiers for both the negotiation tables.

== Social Interaction Tables
Not all failed negotiation results in violence.
A merchant isn't going to attack a persona that walks into her shop.
A shopkeeper's tone may vary from openly helpful to belligerent.
However, combat with a customer in her shop is an impossibility.

For example, a persona goes to buy a loaf of Krenoj at the local Krenojeri.
Buying krenoj is a social negotiation that does not result in violence.
The cashier at the Krenojeri is a quiet, conservative avarian.
The persona buying the Krenoj is a flamboyant, exotically dressed feline (11 CHA).

The referee makes a secret first impression roll of 42.
All signs indicate that the cashier is will treat the customer in a perfectly functional manner.
The feline's charisma is added to the roll, making it 53.
This interaction is still functional.
The two personas have conflicting personalities and dress types.
These conflicts reduce the roll to 38.
The new value moves the cashier's service level downwards to below functional.
Below functional is the krenojier's first impression of the player persona.

When it comes to placing the krenoj order, the referee makes a negotiation roll.
The secret negotiation roll is 21. 
The feline's charisma is added to the roll, making it 32.
The interaction remains below functional.
The personas have conflicting personalities and dress codes.
These conflicts reduce the roll to 12.
The cashier becomes belligerent and unhelpful.
The transaction will still occur, but the persona will get second-rate krenoj.

include::ROOT:partial$CH22_Table_Social_Negotiations.adoc[]

include::ROOT:partial$CH22_Table_Neg_Ex_Social.adoc[]

== Combat Interaction Tables 
Some failed interactions can result in violence. 
A potential combatant may avoid combat if they are intimidated.
A potential combatant may attack by ancient unknown triggers.

:art: hand-to-clamp-combat.png
:width: 450px
:snark: Negotiation failure.
:artist: StudioStoks, mod. HM
:date: 2015
:license: Copyright StudioStoks
:description: Drawing of human in suit grappling with a humanoid robot.

include::ROOT:partial$articulate.adoc[]

The Combat Interaction Tables are for encounters that may result in combat.
Just because combat is possible does not mean that combat will happen. 
A positive outcome is still possible through the interaction.

Situations for combat interactions:
* wilderness encounter with intelligence alien herd
* encountering a group of drunken revellers 
* encountering another expedition searching an old laboratory 

For example, the expedition meets another expedition foraging an ancient ruin for artifacts.
It is not a case of ambush.
However, both expeditions are surprised to encounter the other.
The player expedition sends their best spokesperson to approach.
The persona is a canine nothing with a charisma of 17.

The referee secretly makes a first impression roll of 55.
There are a few adjustments.
The expedition has bigger guns, so the first impression increases by +10.
The persona's charisma score increases the first impression by +17.
The first impression roll is 82, and the other foragers exude good intentions.

The referee secretly makes a negotiation roll of 65.
There are a few adjustments.
The expedition has bigger guns, so the negotiation roll increases by +10.
The persona's charisma score increases the negotiation roll by +17.
The player chooses her persona to be polite and complimentary +5.
The total negotiation roll is 97, and the fellow foragers are openly helpful.
They may give tips about dangers or help out the wounded. 

include::ROOT:partial$CH22_Table_Combat_Negotiations.adoc[]

include::ROOT:partial$CH22_Table_Neg_Ex_Combat.adoc[]
