= Money

Money is beneath most heroic adventurers. 
They are interested in artifacts and altering the universe.
However money does make the planet go around.

:art: money.png
:width: 250px
:snark: Current currencies.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

This section gives a baseline for the players are referee to work from.
Referees may have create their own monetary system for their milieu.
Would an alien currency be two digits in base ten? 
A twelve toed alien society may evolve a base 12 currency.
What is the value of dollar bill in a post apocalyptic wasteland?
The base currency may be ounces of clean water or numbers of happy pills.

.*Sources of Cash*
* xref:i-roll_playing_rules:CH10_Incidentals.adoc[Incidentals,window=_blank].
* xref:iii-hardware:CH53_Treasure.adoc[Treasure,window=_blank].
* Earn it in the wilds.

== Kinds of Currency
EXP money is coins using the eps standard.
Currency can come in any form: cards, chemicals wate, credit vouchers, or paper.
Currency can come in any nomenclature: bucks, domars, cubits, credits, crillos, units, bytes, sense, and doll hairs.

=== EXP Standard Currency
EXP uses the electrum piece standard.
The electrum piece (eps) is a coin based standard.
The eps standard has coins to represent a tenth, hundreds, tens and hundredths.
EXP currency is modeled after the https://en.wikipedia.org/wiki/Loonie[Canadian Loonie,window=_blank].
All coins have same diameter of 25 mm, or about an inch.
All coins have a wate of 25 gm, and 42 coins has a wate of 1 kg.

The fabrication of each coin makes it visually, tactilely and acoustically unique.
So an eps has a unique colour, and imprint, making it stand out. 
The imprint is distinct and touching the coin allows it to be differentiated from other coins.
If the coin is tapped, or rung, it will create sound unique to that coin.
Better yet, the imprint on the coin should be tailored to the referee's milieu.

include::ROOT:partial$CH23_Table_Currency_Units.adoc[]

== Barter
If a milieu has currency a certain level of a cohesive society is implicit.
The most likely form of exchange for a technologically collapsed society is barter.
A bartering system does conjure up an infinite supply of role-playing situations.
The Social Negotiations can be used to sort out unprepared bartering situations.

=== Value and Barter
The referee can use the relative values assigned to artifacts to guide barter.
A million eps artifact is worth 5 times more than a 200k eps artifact.
These exact values may never be used, but the referee can bring them into barter.
Using values to guide barter is only a guideline.
If the expedition needs a specific artifact to complete a mission then it becomes priceless.


