= Mundane Equipment

Mundane Equipment are the items that the persona needs to survive in the wilds.
Mundane equipment are lo-tech, non-artifact, non-powered tools.
These items have a distinctly medieval nature to their construction.
These lists are a convenience and the milieu of the referee rules mundane equipment.
The referee reserves the right to change wates and costs without notice.

== Mundane Tables
Each piece of kit has a wate, cost and sometimes alternates for each equipment type.
Equipment wate is listed in kilograms (kg).
Some very light items have their wates listed in grams (gm).
The costs of equipment are listed in electrum pieces (eps).

== Cost vs Value
All the costs listed are in electrum pieces (eps).
However market prices may increase the value of a piece of kit.
For example, a village in a small ruin may only have one set of plastix to sell.
This could impact the cost of the item.
Relative to an artifact equivalent mundane equipment is valueless.

== Better Mundane Equipment
Mundane items have a low tech, underdeveloped, medieval nature. 
Mundane equipment is constructed from animal parts, poorly smelted metals, shoddy plastics and untreated woods.

Personas their mundane equipment in a modern milieu may have access to better equipment.
Better mundane equipment is composed of alloys, polymers, and other synthetics.
Better equipment functions no better but it is lighter and more expensive.

For example, a suit of chain mail has a wate of 5.9 kgs, and a cost of 80 eps.
Better chain mail would cost 240 eps and have a wate of 3.0 kgs.
The armour rating remains the same at 625.

Better mundane equipment is not to be confused with artifacts generated in the toy system.
Even better mundane equipment is valueless beside artifacts and toys.

include::ROOT:partial$CH24_Table_Mundane_Tech_Levels.adoc[]

== Survival Equipment
Survival equipment is divided amongst essential survival equipment, and non-essential survival equipment.
The essential equipment consists of useful pieces of survival equipment: backpacks, tents, food, water, rope, etc.
The nonessential equipment is devoted to items which are not essential, but are nice to have: sleeping bags, tents, rain suits, etc.

include::ROOT:partial$CH24_Table_Essential_Mundane_Equipment.adoc[]

=== Survival Pack
The survival pack costs 70 eps, and has a wate of 13.5 kg.
The survival pack is designed to speed up the equipment buying procedure.
A ref may not allow the survival pack to be purchased as one lump, but the list of equipment can be used to ensure that each expedition member is properly equipped.

include::ROOT:partial$CH24_Table_Survival_Pack.adoc[]

=== Non-Essential Equipment
Stuff you don't want to take on an expedition.
The stuff nothings like to take on expeditions.

include::ROOT:partial$CH24_Table_Non-Essential_Mundane_Equipment.adoc[]

== Vocation Equipment
Vocation equipment are the tools of the trade.
The equipment list is mostly tongue in cheek.
Vocation equipment aids the personas in performing their vocation skills.
The vocation equipment for one persona will appear as useless junk to another persona.
The equipment acts as a black box for getting things done.
Players need not explain how they are using the equipment to get the attribute bonus.

include::ROOT:partial$CH24_Table_Vocation_Tool_Best.adoc[]

== Armour
Armour is anything that deflects or dissipates force from the persona's hide.
Mundane armour is lower tech armour that may be readily available for purchase.
Armour wate applies for armour being carried. 
Worn armour is not added to the persona's wate allowance.
Armour cost is directly subtracted from the persona's savings.
The gore preventing details of armour is found in the section xref:CH29_Armour_Rating.adoc[Armour Rating].

=== Better Armour
Personas can purchase armour that better reflects the tech level of their campaign.
If the campaign's milieu allows for higher tech armour may be available for purchase.
This armour is lighter and more expensive.
The armour wate is halved and the cost tripled
Armour rating does not improve for better armour.

.Better Armour
* cost times 3
* wate times 1/2
* AR no change

=== Bespoke Armour
Designer armour is bespoke armour tailored to the needs of the persona.
Designer armour should be used for personas that have unique body structures.
Personas such as aliens, and anthros with wings or multiple arms.
Bespoke armour can only be worn by the persona it was made for.
Larger and smaller aliens cannot wear mundane, or bespoke, armour.
Bespoke armour costs six times more than mundane armour. 
Better bespoke armour would cost 18 times more than the mundane version.

.Bespoke Armour
* cost times 6
* wate no change
* AR no change

include::ROOT:partial$CH24_Table_Mundane_Body_Armour.adoc[]

include::ROOT:partial$CH24_Table_Mundane_Shielding.adoc[]

== Mundane Weapons 
Type A weapons are thrusting and striking weapons.
These weapons do not have lighter high tech versions because they depend on inertia to inflict damage.
The wate of these weapons is listed in kg, and the cost in eps.
A persona may use one of the alternate weapons;
however, she cannot use her BP on her her attack roll.
Only the BNP can be added to attack rolls for alternate weapons.
Type B weapons are non-powered missile weapons.
The are high tech versions of type B weapons.
Such weapons do no extra damage, and can only benefit the persona by having a decreased wate.
A persona may use one of the alternate weapons;
however she cannot use her BP on her attack roll.
Only the BNP can be added attack rolls for alternate weapons.
Type C weapons are powered missile attacks.
Mostly include guns and other powered weapon attacks that are usually generated as artifacts.
Crossbows are the only type C weapon that can be purchased in this chapter.

include::ROOT:partial$CH24_Table_Type_A_Weapons.adoc[]

include::ROOT:partial$CH24_Table_Type_B_and_C_Weapons.adoc[]

include::ROOT:partial$CH24_Table_Ammunition_for_Type_B_and_C_Weapons.adoc[]