= Tactical Combat System

[quote]
____
*Mats, minis, mods and many rolls.*
____

The tactical combat system is the keystone of the Roll Playing Rules.
Most Role Playing Rules are built to complement the tactical combat system.
The tactical combat system is played out on hex paper using minis, mods and many rolls.
Resolving combat using the tactical combat system is a hybrid of old school wargame and RPG.
The combat system is centered around a 1d1000 and all the granularity this die roll allows.
The tactical combat system is complicated as well as complex.
If you enjoy detail, dice and tactical fantasy this system is for you.

The tactical combat system is there to resolve lethal persona combat.
The system is balanced. 
Balanced does not mean fair.
The strong will tend to win, and the weak will tend to lose.
The system is detailed.
Detailed does not mean realistic.
The details are a simulation of terrain, movement, skills, weapons, attributes etc.
The tactical combat system is delicate balance between playability and realism.
It represents the least worst system we could think of.

NOTE: The tactical combat system was developed before laptops, handsets or internet. Calculations were done in real time with organic brains. 

== Learn the Tactical Combat System

* *Soft Elements*
. <<_kilo_die,How to use a kilo die>>
. <<_table_top,Put the table back in tabletop>>
. Are we fighting bro?
* *Core Rules*
. Attacks - Combat Tables.
. Defenses - Armour Rating.
. Turns - Combat Time.
.. Me First - Initiative.
. Tokens - Combat Movement.

== Kilo Die
The kilo-die is a thousand sided die, or 1d1000.
The 1d1000 generates a random number between 1 and 1000.
1d1000 rolls are mostly needed for attack rolls in combat.
Hence the nick name kill-o-die.

The kilodie allows the referee to assign tiny adjustments for minutiae.
For example, a player wants a bonus to hit for making a ferocious face during combat.
The referee wants to reward the role playing aspect of this by giving the player +10 to hit.
If the player scores a hit because of the +10 there will be much rejoicing and merriment.
The kilodie allows for more detail and fun in the tactical combat system.

The kilo die is not a golf ball with tiny writing on it.
The kilo die is simulated by rolled three ten sided dice.
For example, roll a red, a yellow and a green ten sider dice all at once.

* The red die is assigned the hundreds place.
** 900, 800, 700, 600, 500, 400, 300, 200, 100 and 0 
* The yellow die is assigned to the tens place.
** 90, 80, 70, 60, 50, 40, 30, 20, 10 and 0 
* The green die is assigned to the digits place.
** 9, 8, 7, 6, 5, 4, 3, 2, 1 and 0 

Rolling 6 on the red ten sider, 6 on the yellow ten sider, and 4 on the green ten sider results in kilodie roll or 664.
The same result can be achieved by rolling 1d10 three times. 
However, users of the Roll Playing System usually prefer to roll lots of dice.

include::ROOT:partial$CH27_Table_Tactical_Kilo.adoc[]

=== Alternate Dice Systems
The 1d1000 is used in the tactical system to allow for detail.
If you don't need detail then it is possible to scale the game to dice that work for you.
All of the game data reflects the kilodie system.
If the group prefers to used different dice for combat the rules scale nicely.
It is recommended to *round down* for any bonuses or penalties.

.*d1000 scales nicely*
* for 1d100 divide by 10
* for 1d20 divide by 50
* for 1d10 divide by 100
* for 2d6 divide by 100

If you are planning to use 2d6 it recommended to jump over to the Theatrical Combat System.
A 2d6 system generates a curve of results so adjustments disproportionately affect the rolls. 

== Table Top
The tactical combat system is designed to be used on hex mat using minis or tokens.
The combat system does not require mats and minis, but it seems like a lot calculating for nothing.

TIP: If you do not know what hex paper is, or what minis are, the theatrical combat system is recommended.

=== The Mat
A hex mat is a specially designed mat covered in hexagons.
It looks like graph paper, but for hexagons. 
The hex mat typically covers the majority of the playing table. 
There are many wonderful commercial options available.
The best ones accommodate erasable markers for drawing terrain directly on the mat.

=== The Minis
Minis are small figurines that represent personas on the mat. 
The most common scale for these minis are 25mm. 
This means a 6ft human is about 25mm tall on the table. 
There is an entire industry of miniatures supporting role playing games.
During the first draft of this document all miniatures were made of lead and tin. 
In the sixth draft of this document really good minis can be 3d printed at home. 

The referee and players can also use tokens to represent personas on the board.
Minis are just fancy tokens. 
Tokens can be paper chits, coloured cut outs, and even specialized paper minis.

=== The Future Is Yesterday
Virtual table tops (VTTs) are nearly common place.
VTTs allow the players to share the mat and the minis on a computer screen
VTTs can be used with everyone in the same room, or remotely.

== Starting Combat 
Combat in EXP is very dangerous for personas. 
While referee personas come and go losing a player persona is a big deal.
Combat in EXP is unforgiving and combat is dangerous to all personas equally.
Dead personas stay dead. 
Only under the most unlikely circumstances will a dead persona return.

Game violence occurs due to failed negotiations, self defence, hunger, or bad problem solving.
Many players feel that violence is the simplest solution to a problem.
The consequences of combat are up to the milieu of the referee.
It is written into the rules that combat is dangerous for personas.

TIP: Any interaction that can result in harm to a persona due to violence is a combat situation.

When regular play becomes combat is the referee’s decision.
If an altercation is solved with a single paw slap or lazer shot combat rules may be avoided.
The transformation to combat rules transforms the game from role playing to solo war game.
This means getting out the mats, the markers, and the minis.

Combat time stretches 2 second intervals into minutes of decisions and dice rolls.
Persona tokens are moved on the hex mat with care and precision.
Players begin rolling dice to determine who goes first, and who hurts who.
A misplaced token can result in getting squashed by an alien or impaled by a combot.  
10 seconds of combat time can take 20 minutes of mundane time to play.

NOTE: If prolonged real time resolution of combat is unappealing consider the Theatrical Combat system.

== Attacks
Any attempt a persona makes to harm another persona is an attack. 
This section focuses on attacks taking using weapons in persona vs persona combat.
There are other kinds of attacks: psionic attacks, area of effect attacks, etc.
There are also completely different kinds of combat: space vehicles, robotic, etc.

A successful attack requires a successful "to hit roll."
To hit rolls in the tactical combat system are made on a kilodie. 
The more a player has successful to hit rolls the more damage she delivers to her target.
The more damage delivered to the target the better the chance of successful combat.
Keep in mind that the referee personas will be doing the same thing back.
The only winners are the ones that survive.

NOTE: *An attacker generates a to hit roll by rolling a kilo-die (hence roll
to hit).*

The higher the to hit roll the better.
The to hit roll must be greater that the target's defences. 
These defences are collectively called the armour rating of the target.
Combat is a series of to hit rolls rolled by the referee and the players.
Successful to hit rolls damage damage the personas.
Too much damage results in death. 

There are many elements that influence attacks. 
Including: weapon type, to hit bonuses, EXPS levels, weapon proficiencies and luck. 

* Weapon Types
* Combat Tables
* Proficiencies

// tag::Attack_Types[]
=== Attack Types
EXP has an enormous variety of weapons.
A primer on weapon types is needed to understand attack bonuses.

==== Type A Attack
These are non powered thrusting and striking weapons.
Type A weapons depend on the muscle power of the user, and must contact the target to cause damage.
The personas must be in adjacent hexes to be able to hit each other.
Examples are: clubs, fists, swords, and axes.

==== Type B Attack
These are non-powered projectile weapons.
Type B weapons depend on the muscle power of the user, and must contact the target to cause damage.
The personas must be several hexes apart and still be able to hit each other.
Examples are: arrows, bolts, rocks, quills and spit.

==== Type C Attack
These are powered weapons.
Type C weapons do not require muscle power of the user, and must contact the target to cause damage.
The personas can be any distance apart and be able to hit each other.
Examples are: bullets, laser bolts, energy beams, and crossbow bolts.

==== Type D, E Attacks
These are powered weapons with multiple attacks per turn.
These powered weapons do not require muscle power of the user, and must hit to cause damage.
The personas can be any distance apart and be able to hit each other.
Type D and E weapons attack as type C weapons but with extra attacks each turn.
Type D weapons get two attacks per turn.
Type E weapons get three attacks per turn.
Examples are: semi-automatic (sotto) guns and hair trigger energy weapons.

==== Type F Attack
These are powered weapons that are fully automated (F stands for fully automatic).
These powered weapons do not require muscle power of the user, and must hit to cause damage.
The personas can be any distance apart and be able to hit each other.
Type F weapons attack as type C weapons.
Type F weapons spray projectiles delivering lots or no damage at all.
A typical type F weapon will disgorge 15 rounds per trigger pull. 
Examples are: machine gun, Gatling laser rifle, or machine pistol

NOTE: *Weapon Type F was formerly called Weapon Type Special*

==== Type AOE Attack
These are area of effect (AOE) weapons. 
Type AOE weapons do not need to contact the target to cause damage.
These weapons typically explode and  damage everything in their area of effect (AOE). 
The to hit roll is made against a location and not a persona.
So the player targets a specific hex to deliver the AOE weapon.
Examples are: frag grenade, napalm aerosol, or fusion grenade.

Type AOE weapons attack as type A, B or C depending on delivery method.
Type B AOE are thrown at the target hex (hand grenade).
Type C AOE are shot at the target hex (grenade launcher).
Type A AOE would be a suicide vest.

// end::Attack_Types[]

=== The Combat Table
In the tactical combat system every persona has a combat table.
The  combat table blends skill level, vocation, weapon type and attributes into one bonus.
The player is allowed to add this bonus to every attack that she makes.
The combat table differentiates between experienced mercenaries and inept civilians.
The bonus is called a to hit bonus. 
There are many other kinds of to hit bonuses in the tactical system.

The combat table is matrix of numbers.
Bonus Proficient (BP), Bonus Non-Proficient (BNP), Maximum Roll (MR) and Damage Adjuster (DA), is calculated for each weapon type (A, B, C).

TIP: If the concept of a combat table seems onerous we recommend the Theatrical Combat System.

include::ROOT:partial$CH27_Table_CT_Example.adoc[]

We will use the story of a nameless nomad anthro persona who is in a tight spot.

==== Bonus Proficient (BP)
The BP value is added to rolls with weapons the persona is skilled with.
When a persona is proficient with a weapons she 'uses' her BP when attacking
Proficiency means skilled in the context of weapons. 

____
Our nameless nomad finds herself in a chase over frozen arctic wastes.
Occasionally she and her pursuers pause to catch their breaths and take a few shots at one another.
Our nomad is packing her favourite 1.5 metre long harpoon.
The nomad has used this weapon for years and is proficient with the harpoon.
She normally uses this for spearing Giant Arctic Sea Slugs.
One of her pursuers is within range of this weapon, and she lets fly with the wickedly barbed weapon.
____

The player rolls an attack using a kilodie.
The player refers to the Combat Table.
The harpoon must be thrown by the persona and that makes it a Type B attack. 
The nomad is proficient with the harpoon.
The player will add the type B Bonus Proficient (BP) to her to hit roll.
So the players to hit roll 600 on the kilodie.
She adds her BP +175 getting a to hit a of 775.
775 is higher than the target's armour rating (AR) she scores a hit.

==== Bonus Non-Proficient (BNP)
The BNP value is added to rolls with weapons the persona does not know how to use.
When a persona is non-proficient with a weapons she 'uses' her BNP when attacking
Proficiency means skilled in the context of weapons. 
The BNP can be much lower than the persona's BP.

____
Our nameless nomad is now sans harpoon.
Her only other weapon she has is a pointy icepick tucked into her boot.
She slides down an icy incline, running for some cover.
Unfortunately an enemy is already hiding behind the cover.
The nomad whips out her icepick, and pokes at the target.
She only uses the ice pick to break up ice.
Ice pick fights are strange to her.
____

The player rolls an attack using a kilodie.
The player refers to the Combat Table.
The ice pick can only be used in close quarters and is a Type A attack. 
The nomad is not combat proficient with the ice pick.
The player will add the type A Bonus Non-Proficient (BNP) to her to hit roll.
So the players to hit roll 500 on the kilodie.
She adds her BNP +35 getting a to hit a of 535.
535 is higher than the target's armour rating (AR) she scores a hit.
This enemy will think twice about wearing an unarmoured down jacket to a knife fight.

==== Maximum Roll (MR)
The Maximum Roll (MR) is the highest roll the player can make when her persona attacks.
The player's to hit roll is capped at the MR for the weapon type.
The MR increases with experience level and differentiates between experienced and neophyte personas.
____
After a few turns fighting with enemy our nameless nomad decides the ice pick isn't good enough.
She flees the fight heading back to get her harpoon.
In her haste she trips over a body with a harpoon stuck in it's head.
The first thing she notices is a laser pistol dropped by the dead referee persona.
By a lucky twist of fate, the nomad is proficient in laser pistols!
She grabs the pistol and shoots at her approaching enemy.
____

The player rolls an attack using a kilodie.
The player refers to the Combat Table.
The laser pistol is clearly a Type C attack. 
The nomad has proficiency with laser pistol.
The player will add the type C Bonus Proficient (BP) to her to hit roll.
So the players to hit roll 800 on the kilodie.
She adds her BP +230 getting a to hit a of 1030.
This is a very high roll. 
It does not mean the nomad can choose to shoot out the target's left eye.
The maximum roll kicks in and her 1030 becomes 905.
This is also a high roll and the target is damaged.

Any Type A to hit roll higher than 790 would become 790.
Any Type B to hit roll higher than 825 would become 825.
Any Type C to hit roll higher than 905 would become 905.

==== Damage Adjustment (DA)
Each successful to hit roll the player makes delivers damage to the target.
Damage is subtracted from the target's hit points incapacitating or killing the persona.
Non-powered weapons inflict more damage the stronger the persona is.
This amount added to the damage roll is called the damage adjustment. 

When the nameless nomad hit her target with a harpoon her player would added her Type B DA.
This Type B Damage Adjustment is +6. 
If the player rolled 6 points of damage she would add 6 more and damage the enemy by 12 hit points.
The nameless nomad is not proficient with the ice pick.
Proficiency only affects the ability to hit the target not the damage delivered.
A hit with an ice pick would add her Type A DA of 12 hit points.
Her lack of proficiency led to less frequent hits but the same damage as her harpoon.
Type C attacks have no DA because they do not use physical strength to damage the target.
A hit with the laser pistol would deliver only the damage specified by the weapon. 
 
=== Weapon Proficiencies
Any tool using persona can use any weapon at any time.
If they don't have skill in the weapon they will not enjoy their bonus proficient.
Each persona starts with a few proficiencies and may add more with time.
Weapon proficiencies vary between persona family and vocation type.
Aliens are automatically proficient with their natural attacks. 
Mercenaries are proficient with any weapon that they can identify.
Robots are whole separate kettle of bolts.

== Defences
Almost everything has a defence. 
Personas wrap all their defences up into one number called Armour Rating (AR).
The Armour Rating (AR) determines how difficult it is to hit the persona and damage her.
Dexterity, armour, hide, body structure, and luck are rolled into the Armour Rating (AR).

The armour rating is a quantitative value that represents how difficult it is to damage the target.
The higher the armour rating the better the protection it offers.

== Combat Time
Each turn of combat time in the tactical combat system is called a unit.
A unit is the smallest measure of time where a persona can get something done.
Getting something done includes: running, shooting, blasting a mutation, etc.
A unit of combat time is 2 seconds in EXP.
The 2 second turn seems rather arbitrary. 
However movement rates, mutation durations, artifact effects are all based on this unit of time.

Combat time is different from regular role playing time.
When personas are sitting around kibitzing about who has more credits time passes normally.
The expedition may skip over months of travel in a space vehicle with the wave of a pen.
However combat time is the opposite.
The 2 second unit leads to a time distortion where 10 seconds of combat can take 10 minutes to play.

== Combat Movement
Combat movement is based on hexes per unit.
Hexes refers to how many hexes on the mat a token can be moved each unit.
A slow persona with a movement rate of 3 hexes per unit (3 hu) could move three hex spaces per turn.
A fast persona with a movement rate of 9 hu could move 9 hex spaces each turn.
The movement rate of a persona is mostly determined by her dexterity.
Being able to move great distances per turn is a fabulous combat advantage.

Movement rate only matters on the hex mat in a tactical combat system persona fight.
A hex is 2 meters and a unit is 2 seconds so hexes per unit conveniently converts to meters per second.
All movement rates are recorded in hu. 
This includes vehicles, robots, aliens and anthros.

== Initiative
Initiative is a tactical combat rule system that determines who gets to act first during combat.
It is not just a simple measure of who goes first. 
Initiative is a measure of tactical advantage based on awareness, dexterity and luck.

Initiative is checked for every persona every turn (unit) of combat. 
The personas are all ranked from highest to lowest initiative. 
The persona with the highest initiative can move and attack first if they wish.
They are also allowed to wait movement and attack until it suits them best. 
Winning initiative is a huge tactical advantage in the tactical combat system.


== Much More
These 5 elements cover the basics of tactical combat. 
Referees and players can pick and choose what works for their milieu.
There are also many more tactical combat rules that can be added in.
Terrain and weather adjustments for to hit rolls and movement.
Range adjustments based on weapon type. 
Attacking from vehicles. 
Ambush effects.
Hit locations.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

