= Tactical Combat System

[quote]
____
*Mats, minis, mods and many rolls.*
____

The tactical combat system is the keystone of the Roll Playing Rules.
All rules within the Roll Playing Rules complement the tactical combat system.
Artifacts, mutations and vocations complement the tactical combat system.
The tactical combat system is the bespoke combat system for EXP.

The theatrical combat system from the Role Playing Rules is a careful reduction of the tactical combat system.

The tactical combat system is played out on a hex mat using minis, mods and many rolls.
Resolving combat using the tactical combat system is a hybrid of old-school wargame and 20th-century role-playing.
The combat system revolves around a 1d1000 attack roll and all the granularity it allows.
The tactical combat system is complicated as well as complex.
If you enjoy detail, dice and tactical fantasy, this system is for you.

The tactical combat system is there to resolve lethal persona combat.
The system is balanced. 
Balanced does not mean fair.
The strong will tend to win, and the weak will tend to lose.
The system is detailed.
Detailed does not mean realistic.
The details are a simulation of terrain, movement, skills, weapons, attributes etc.
The tactical combat system is a delicate balance between playability and realism.
It represents the least worst system that met our pre-computer era needs.

NOTE: The tactical combat system developed before laptops, handsets or the internet—calculations took place in real-time with organic brains. 

.*Tactical Combat Checklist*
* <<_attack_types,Attack Types>>
* <<_combat_table,Combat Table>>
* <<_attack_roll,Attack Roll>>
* <<_armour_rating,Armour Rating>>
* <<_combat_movement,Combat Movement>>
* <<_combat_time,Combat Time>>
* <<_initiative,Initiative>>

== Starting Combat 
Combat in EXP is perilous for personas. 
While referee personas come and go losing a player persona is a big deal.
Combat in EXP is unforgiving, and the battle is dangerous to all persons equally.
Dead personas stay dead. 
Only under the most unlikely circumstances will a dead persona return.

Game violence occurs due to failed negotiations, self-defence, hunger, or bad problem-solving.
Many players feel that violence is the simplest solution to a problem.
The consequences of combat are up to the milieu of the referee.
In EXP, combat is dangerous for personas.

TIP: Any interaction that can harm a persona due to violence is a combat situation.

The referee decides when combat rules are engaged.
The transformation to combat rules transforms the game from role-playing to solo war game.
Combat means getting out the mats, the markers, and the minis.
If an altercation is solvable with a paw slap or threatening lazer shot, the personas may avoid combat rules.

Combat time stretches 2-second intervals into minutes of decisions and dice rolls.
Persona tokens move on the hex mat with care and precision.
Players begin rolling dice to determine who goes first and who hurts who.
A misplaced token can result in getting squashed by an alien or impaled by a combot.  
Ten seconds of combat time can take 20 minutes of mundane time to play.

NOTE: If prolonged real-time resolution of combat is unappealing, consider the xref:ii-role_playing_rules:CH26_Theatrical_Combat.adoc[Theatrical Combat System,window=_blank].

== Attack Roll
Any attempt a persona makes to harm another persona is an attack. 
When the player wants her persona to attack another persona, she makes an attack roll.
The higher the attack roll, the better.
Many elements influence attack rolls, including weapon type, roll bonuses, EXPS levels, weapon proficiencies and luck. 

The attack roll must be greater than the target's defences. 
These defences are collectively called the armour rating (AR) of the target.
When the player's attack roll is higher than the target's armour rating (AR), she has won the attack roll and damages her target.

In the Roll Playing Rules' tactical combat system, the players use a kilo-die to make attack rolls.
The kilo-die is a thousand-sided die, or 1d1000.
The 1d1000 generates a random number between 1 and 1000.
The kilo die is not a golf ball with tiny writing on it.
The player rolls three 1d10s to simulate the 1d1000.
For more info about the 1d1000 jump to xref:i-roll_playing_rules:CH00_kilo_die_mechanic.adoc[Kilodie Mechanic,window=_blank].

// tag::Attack_Types[]
== Attack Types
EXP has an enormous variety of weapons.
A review of attack types is needed to understand combat tables and attack rolls.
For a more detailed explanation jump to xref:i-roll_playing_rules:CH28_Weapons.adoc[Attack Types,window=_blank].

=== Type A
*Non-powered thrusting and striking attack.*
Type A attacks depend on the user's muscle power to inflict damage.
The personas must be in adjacent hexes to be able to damage each other.
Examples are clubs, fists, swords, pincers, claws and axes.

=== Type B
*Non-powered projectile attack.*
Type B attacks depend on the user's muscle power to inflict damage.
The personas may be several hexes apart and still be able to damage each other.
Examples are arrows, bolts, rocks, quills and spit.

=== Type C
*Powered projectile attack.*
Type C attacks do not require the user's muscle power to inflict damage. 
The attack supplies its energy to inflict damage.
The personas can be many hexes apart and still be able to damage each other.
Type C attacks are limited to once per combat unit.
Examples are bullets, laser bolts, energy beams, and crossbow bolts.

=== Type D and E
*Powered projectile attacks.*
Type D and E attacks do not require the user's muscle power to inflict damage. 
These attacks supply their energy to inflict damage.
The personas can be many hexes apart and still be able to damage each other.
Type D and E attacks function the same as type C attacks.
Type D weapons get two attacks per turn.
Type E weapons get three attacks per turn.
Examples are semi-automatic rifles, quill shooting aliens and hair-trigger energy weapons.

=== Type F
*Powered full auto projectile attacks.*
These attacks are fully automated (F stands for fully automatic).
Type F attacks do not require the user's muscle power to inflict damage, and one action results in multiple attacks. 
The attack supplies its energy to inflict damage and make multiple attacks.
The personas can be many hexes apart and still be able to damage each other.
Type F weapons attack as type C weapons.
Type F weapons spray projectiles delivering lots or no damage at all.
A typical type F weapon will disgorge 15 rounds per trigger pull. 
Examples are machine guns, Gatling laser rifles, or a multi-mouthed alien vomit attack.

=== Type AOE
*Area of effect attack.*
Type AOE attack blanket an area with damage, and require no effort by the persona.
Area of effect attacks are unique in that they only need to land near a target to inflict damage.
The AOE attack roll is against a target hex and not a target's defences.
Examples are frag grenade, napalm aerosol, skunk spray, or a fusion grenade.

Type AOE attacks as type A, B or C depending on its delivery method.
The persona throws Type B AOE attacks at the target hex (hand grenade).
The persona shoots Type C AOE attacks at the target hex (grenade launcher).
Type A AOE would be a suicide vest.

// end::Attack_Types[]

== Combat Table
The combat table blends skill level, vocation, and attributes into an attack roll bonus.
Every persona has a combat table.
Every attack type has its attack roll bonus, leading to every weapon having an attack roll bonus.
For a detailed explanation of combat tables jump to xref:i-roll_playing_rules:CH09_Combat_Tables.adoc[Combat Tables,window=_blank].

The combat table is a scary-looking matrix of numbers.
The matrix is a cross of attack types (A, B, C) and attack roll parameters.
The attack roll parameters are Skilled Bonus (Skilled), Raw Bonus (Raw), Maximum Roll (Max) and Damage Adjuster (Force).

TIP: If the concept of a combat table seems onerous, EXP recommends the xref:ii-role_playing_rules:CH26_Theatrical_Combat.adoc[Theatrical Combat System,window=_blank].

include::ROOT:partial$CH09_Table_Tiny_CT.adoc[]

=== Skilled Bonus (Skilled)
The player adds the Skilled Bonus to her attack roll for weapons in which her persona is skilled.

A persona can use any weapon at any time.
Proficiency means skilled in the context of weapons. 
If a persona does not have weapon proficiency, the player cannot add her Skilled Bonus.
Each persona starts with a few proficiencies and may add more with time.
Weapon proficiencies vary between persona family and vocation type.
Aliens are automatically proficient with their natural attacks. 
Mercenaries are proficient with any weapon that they can identify.
Robots are whole separate kettle of bolts.

.Combat table narrative
====
A nameless nomad finds herself in a chase over a frozen wasteland.
Occasionally she and her pursuers pause to catch their breaths and take a few shots at one another.
Our nomad is packing her favourite 1.5-metre long harpoon.
The nomad has used this weapon for years and is proficient with the harpoon.
She usually uses the harpoon for spearing giant sea slugs.
One of her pursuers is within range, and she lets fly with the wickedly barbed weapon.
====

The player rolls an attack using a kilodie.
The player refers to the nameless nomad's combat table.
The harpoon is a Type B attack (self-powered projectile weapon). 
The nameless nomad is proficient with the harpoon.
The player will add the type B Skilled Bonus (Skilled) to her attack roll.
The player's attack roll is 600 on the kilodie.
The Type B Skilled Bonus is +175, and her final attack roll is 775.
If 775 is higher than the target's armour rating (AR), the player will get to roll damage.
 
=== Raw Bonus (Raw)
The player adds the Raw Bonus to her attack roll for weapons in which her persona is not skilled.

A persona can use any weapon at any time.
Proficiency means skilled in the context of weapons. 
If a persona does not have weapon proficiency, the player cannot add her Skilled Bonus.
The player adds the Raw Bonus to her attack roll instead.
The Raw can be much lower than the persona's Skilled.

.Combat table narrative
====
The nameless nomad slides down an icy incline, looking for some cover.
Unfortunately, an enemy is already hiding behind the cover.
Our nameless nomad is no longer has her harpoon.
The only other weapon she has is a pointy icepick tucked into her boot.
She whips out her icepick and pokes at the enemy.
She only uses the ice pick to break up ice, and ice pick fights are strange.
====

The player rolls an attack using a kilodie.
The player refers to the nameless nomad's combat table.
The ice pick can only be used in close quarters and is a Type A attack. 
The nameless nomad is not proficient with the ice pick.
The player can only add the persona's Raw Bonus (Raw) to her attack roll.
The player's attack roll is  500 on the kilodie.
The Type A attack Raw Bonus (Raw) is +35, and her final attack roll is 535.
If 535 is higher than the target's armour rating (AR), the player will get to roll damage.

=== Maximum Roll (Max)
The Maximum Roll (Max) is the highest attack roll the player for her persona.
The player's attack roll cannot be greater than the Maximum Roll for the attack type.
The Maximum Roll (Max) increases with experience level and differentiates between experienced and neophyte personas.
If anMax is lower than the target's armour rating, only a critical roll can damage the target.
For more information about lucky shots jump to xref:i-roll_playing_rules:CH16_Special_Rolls_Critical.adoc[Critical Checks,window=_blank].

.Combat table narrative
====
After tiring of her ineffective icepick combat, the nameless nomad runs back to get her harpoon.
She trips over a body with a harpoon stuck in its head.
She grabs her harpoon and notices a lazer pistol in the snow.
The nameless nomad is proficient in laser pistols!
She grabs the pistol and shoots at the nearest pursuer.
====

The player rolls an attack using a kilodie.
The player refers to the combat table.
The laser pistol is a Type C attack. 
The nomad has proficiency with a laser pistol.
The player can add the Type C attack Skilled Bonus (Skilled) to her attack roll.
The player's attack roll is 800 on the kilodie.
The Type C Skilled Bonus is +230, and her final attack roll is 1030.

1030 is a very high attack roll. 
The persona's Maximum Roll limits the player's attack roll.
In this case, the persona's Maximum Roll (Max) kicks in, limiting her attack roll to 905. 

=== Force Bonus (Force)
The player adds the persona's Force Bonus when she makes a damage roll.
When the player wins an attack roll in combat, she makes a damage roll that decreases the target's hit points.
Decreasing the opponent's hit points is the goal of combat. 

The persona's Strength determines the Force Bonus.
Type A attacks require Strength to inflict damage and therefore have the highest Force Bonus.
Type C attacks are self-powered and have no Force Bonus at all.

When the player wins an attack roll with a Type A weapon (icepick), she adds six hit points to the damage score.
When the player wins an attack roll with a Type B weapon (harpoon), she adds three hit points to the damage score.
When the player wins an attack roll with a Type C weapon (lazer pistol), she adds nothing to the damage score.

== Armour Rating
Personas wrap all their defences up into one number called Armour Rating (AR).
The armour rating is a quantitative value that represents how difficult it is to damage the target.
The higher the armour rating, the better the protection it offers.
Dexterity, armour, hide, body structure, and luck are rolled into the Armour Rating (AR).
For more details about armour rating jump to xref:i-roll_playing_rules:CH29_Armour_Rating.adoc[Armour Rating,window=_blank].

== Combat Time
Each turn of combat time in the tactical combat system is called a unit.
Every player gets a turn to do something for each unit.
A unit is the smallest measure of time where a persona can get something done.
Getting something done includes: running, shooting, blasting a mutation, etc.
Movement rates, mutation durations, and artifact effects are all based on this unit of time.
A unit of combat time is 2 seconds long.
You can take the time to learn more by jumping to xref:i-roll_playing_rules:CH12_Combat_Time.adoc[Combat Time,window=_blank].

== Combat Movement
Combat movement determines how far a persona can move each unit (2 seconds) of combat time.
The measure of combat distance is the hex, and the size of a hex is 2 meters.
A slow persona with a movement rate of 3 hexes per unit (3 hu) could move three hex spaces per turn.
A fast persona with a movement rate of 9 hu could move 9 hex spaces each turn.
To learn more about movement move over to xref:i-roll_playing_rules:CH12_Combat_Movement.adoc[Combat Movement,window=_blank].

== Initiative
The initiative system determines the order in which players act during the combat unit.
Initiative is a measure of tactical advantage based on Awareness, Dexterity and luck.
Every player rolls for initiative for their persona in every combat unit.  
Winning initiative is a huge tactical advantage for the persona.

It is not just a simple measure of who goes first
Initiative is complex and convoluted.
Players can choose to attack first, move first or move and attack first. 
Players can also hold back their attacks and moves to gain a tactical advantage. 
For more details about initiative, jump to
xref:i-roll_playing_rules:CH33_Initiative.adoc[Initiative,window=_blank].

== Table Top
The tactical combat system expects to be used on a hex mat using minis or tokens.
The combat system does not require mats and minis, but it seems like a lot of calculating for nothing.

TIP: If you do not know what hex paper is or what minis are, EXP recommends the xref:ii-role_playing_rules:CH26_Theatrical_Combat.adoc[Theatrical Combat System,window=_blank].

=== The Mat
A hex mat is a specially designed mat covered in hexagons.
It looks like graph paper, but for hexagons. 
The hex mat typically covers the majority of the playing table. 
There are many wonderful commercial options available.
The best ones accommodate erasable markers for drawing terrain directly on the mat.

=== The Minis
Minis are small figurines that represent personas on the mat. 
The most common scale for these minis is 25mm. 
This scale of miniature indicates a 6ft human is about 25mm tall on the table. 
There is an entire industry of miniatures supporting role-playing games.
During the first draft of this document, all miniatures were lead and tin. 
By the sixth draft of this document, excellent minis can be 3d printed at home. 

The referee and players can also use tokens to represent personas on the board.
Minis are just fancy tokens. 
Tokens can be paper chits, coloured cutouts, and or colourful paper minis.

=== The Future Is Yesterday
Virtual tabletops (VTTs) are nearly commonplace.
VTTs allow the players to share the mat and the minis on a computer screen.
VTTs can have everyone in the same room or in different countries.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*