= Attack Types

[quote]
____
*Sticks and stones may break my bones. A fusion pistol roasts me.*
____

An attack is any action where a persona attempts to injure another persona.
This section focuses on attacks where the persona is trying to injure the target persona physically.
The attack types detailed here include weapons, body parts, and explosions. 
The section does not detail attack types like psionics, poisons, or bullying.

== Attack Types
Attack types divide the widely various methods of killing off personas into a few basic groups. 
Attack types separate based on damage mechanism, frequency of attack, and range. 
An attack type can include weapons, alien attacks and misused robot peripherals.

Each persona deploys each attack type differently depending on their family and vocation.
These personalized differences are in the xref::CH09_Combat_Tables.adoc[Combat Table,window=_blank] section.

include::ROOT:partial$CH28_Table_Attack_Types_Intro.adoc[]

== Type A Attacks
*Non-powered thrusting and striking attacks. *

Type A attacks depend on the persona's muscle power to inflict damage. 
The personas must be in adjacent hexes to be able to damage each other.
Type A attacks get one attack roll per unit.
 Examples are clubs, fists, swords, pincers, claws and axes.

An anthro could use a weapon like a sword or an axe. 
An alien could use a natural attack like a bite or a talon slash.
A robot could use a malfunctioning peripheral that operates as a club.

Aliens and robots can have multiple Type A attacks per unit.
For example, an alien may have multiple tentacles with which to slap.
Or a robot may have multiple pointy things with which to stab.

=== Type A Weapons
These are non-powered thrusting and striking weapons.
Type A weapons are handheld but can include the hand itself.
Type A weapons include swords, maces, pole-arms, fists, paws, beaks, spears, etc.
They are close combat weapons, and the target must be in the persona's hex or an adjacent hex.

include::ROOT:partial$CH28_Table_Type_A_Weapons.adoc[]

Length::
Self-explanatory.

Wate::
Self-explanatory.

Armour Rating Bonus::
If the persona has proficiency with the weapon, she can add an AR bonus.
The armour rating bonus only applies when the persona is using the weapon in combat.
The player multiplies the AR Bonus by the persona's Dexterity score and adds it to her armour rating.

Damage::
Damage indicates how many hit points the weapon removes from the target's hit points.
The player also adds her damage adjuster for Type A attack to the damage inflicted (one-half her STR).

== Type B Attacks
*Non-powered projectile attacks.*

Type B attacks depend on the persona's muscle power to inflict damage.
The personas may be several hexes apart and still be able to damage each other. 
Type B attacks get one attack roll per unit.
Examples are arrows, bolts, rocks, quills and spit.

An anthro would use a weapon like a bow or a sling. 
An alien could have an evolved natural attack like spitting rocks or flinging quills.
A robot could use a malfunctioning peripheral that flings metal shavings.

Aliens and robots can have multiple attacks per turn with their type B attacks.
For example, an alien may be able to spit three times each turn.
Or a robot may have multiple pointy things to fling at her targets.

=== Type B Weapons
These are non-powered projectile weapons.
Type B weapons include rocks, daggers, boomerangs, whips, spitting, arrows, darts, etc.
Type B weapons are not close combat weapons, and there must be at least one hex between the persona and her target.

include::ROOT:partial$CH28_Table_Type_B_Weapon_Data.adoc[]

Length::
Self-explanatory.

Wate::
Self-explanatory.

Range::
The range represents how many hexes the weapon can fly true.
There are no attack roll penalties within the weapon's range.
Beyond the range, the weapon becomes much less accurate. 

Decay::
When attacking a target beyond the weapon's range, the attack roll suffers decay penalties.
The player subtracts the decay from the attack roll for every hex beyond the weapon's range. 
For example, an axe thrown ten hexes would have no penalties.
The same axe thrown 16 hexes would have a -600 penalty.

Damage::
Damage indicates how many hit points the weapon removes from the target's hit points.
The player also adds her damage adjuster for Type B attack to the damage inflicted (one-quarter of her STR).

:art: cow_moose_antlers_both_front.png
:width: 350px
:snark: Really Cool Moose Police
:artist: unknown, Helen Field, HM
:date: 1948, Unknown, 2018
:license: CC BY-SA 4.0 (sheriff), Helen Field Stock Art (moose)
:description: Drawing of a humanoid moose wearing an rcmp hat and holding two six shooters.

include::ROOT:partial$articulate.adoc[]

== Type C Attacks
*Powered projectile attack.*

Type C weapons do not require the muscle power of the persona.
The attack supplies its energy to inflict damage. 
For example, the destructive forces may come from a battery or an explosive charge in a bullet.
The personas can be many hexes apart and still be able to damage each other. 
Type C attacks are limited to once per combat unit. 
Examples are bullets, laser bolts, energy beams, and crossbow bolts.

An anthro could use a weapon like a gun or a lazer.
An alien could have a naturally evolved attack like lazer eyes or gas projected bone chunks.
A robot could be a combot with a baked-in gun or a construction robot misusing a nail gun. 

=== Type C Weapons
These are powered weapons.
Type C weapons are the classic guns and lazer weapons from sciency fiction and action movies.
Most type C weapons are artifacts like guns or lasers. 
Powered weapons include lasers, crossbows, rifles, fusion guns, death rays, machine pistols, etc.
Exotic, dangerous tech weapons are described in xref:iii-hardware:CH46_Guns.adoc[Guns,window=_blank].
Mundane type C weapons are listed below. 

include::ROOT:partial$CH28_Table_Type_C_Weapon_Data.adoc[]

Length::
Self-explanatory.

Wate::
Self-explanatory.

Range::
The range represents how many hexes the weapon can fly true.
There are no attack roll penalties within the weapon's range.
Beyond the range, the weapon becomes much less accurate. 

Decay::
When attacking a target beyond the weapon's range, the attack roll suffers decay penalties.
The player subtracts the decay from the attack roll for every hex beyond the weapon's range. 
For example, a small crossbow at a ten hex range would have no penalties.
The same small crossbow at 28 hexes would have a -375 attack roll penalty.

Damage::
Damage indicates how many hit points the weapon removes from the target's hit points.
There are no Strength adjustments for Type C weapons.

== Type D and E Attacks
*Powered projectile attacks.*

Type D and E attacks function the same as Type C attacks but have more than one attack roll per unit.
These attack types do not require any Strength from the persona to inflict damage or make multiple attack rolls.
Combatants can be quite far apart and be able to damage each other.
Type D and E attacks are usually artifact weapons found in the xref:iii-hardware:CH46_Guns.adoc[Guns,window=_blank] section.
It is also possible for an alien to have an evolved attack that functions like a Type D or E attack. 

.*Attack Rolls per Unit*
. Type C one attack roll per unit
. Type D two attack rolls per unit
. Type E three attack rolls per unit

== Type F Attacks
*Powered fully automated projectile attacks.*

These are powered attacks that are fully automated (F stands for fully automatic).
Type F attacks function the same as Type C attacks but have more than one attack roll per unit.
These attack types do not require any Strength from the persona to inflict damage or make multiple attack rolls.
Combatants can be quite far apart and be able to damage each other.

NOTE: *The former name of Type F attack was Weapon Type Special*

A machine gun that releases a hail of bullets with the pull of a trigger is the most iconic Type F attack.
Type F attacks are usually artifact weapons found in the xref:iii-hardware:CH46_Guns.adoc[Guns,window=_blank] section.
It is also possible for an alien to have an evolved attack that functions like a Type F attack. 

The player will make five attack rolls per unit when using a Type F weapon.
Each burst uses 15 rounds of ammunition.
Each attack roll represents a random number of ammo rounds (bullets, lazer bolts, etc.).
For each successful attack roll anywhere from 0-3 rounds (1d4-1) damage the target.
While extremely unlikely, it is possible to win five attack rolls and land zero rounds on the target. 

A persona fires her medium-powered full auto lazer pistol at a target. 
A medium-powered full auto lazer pistol inflicts 2-20 (2d10) hit points of damage per lazer bolt.
The player makes five attack rolls on the target. 
Three of the attack rolls damage the target, two of the attack rolls miss.
The weapon discharges 15 rounds of ammunition regardless.
The player will then roll 1d4-1 three times to see how many lazer bolts damage the target. 
If the player rolls 2, 0, 3 for how many bolts land on the target, she will roll 10d10 hit points of damage. 

Only mercenaries with flotto skills can "spread" the attack rolls between different targets.
In EXP, full auto weapons have the nickname of flotto weapons.

== Type AOE Attacks
*Area of Effect attack*

An area of effect attack covers a predetermined area of combat with damage.
Type AOE attacks are unique because the player does not attack a persona's armour rating but makes an attack roll on a target hexagon.
The attack roll is against a location and not a persona.
For the explosive details of area of effect combat jump to 
xref:i-roll_playing_rules:CH30_Area_of_Effect_Weapons.adoc[Area of Effect,window=_blank].

The player targets a specific hex for the AOE weapon.
She then makes an attack roll to see if she hits the desired target hex.
The armour rating of a hexagon is 600.
The player must win an attack roll versus AR 600 to have her persona's area of effect weapon land where she wants.
Every persona in the area of effect is damaged.
There is no saving throw.

=== Type AOE Weapons
Most Type AOE attacks are weapons like xref:iii-hardware:CH45_Grenades.adoc[Grenades,window=_blank] or
xref:iii-hardware:CH43_Aerosols.adoc[Aerosols,window=_blank].
An alien or robot can have a Type AOE attack.
Below are the mundane area of effect weapons.
Mundane Type AOE weapons function as Type B attacks.

include::ROOT:partial$CH28_Table_Type_AOE_Data.adoc[]

Wate::
Self-explanatory.

Range::
The range of mundane grenades is equal to one hex per point of Strength.
A persona with a Strength of ten could aim at a target ten hexes away. 

AOE::
Mundane area of effect weapons are unpredictable.
The player must roll the area of effect each time one of them detonates.
An AOE of zero indicates only the target hex is damaged.
The other hex values are the radius of the damage.

Roll::
What dice to use to generate the AOE radius of effect.

Damage::
Damage indicates how many hit points the weapon removes from the target's hit points.
There are no Strength adjustments for Type AOE weapons.

