= Initiative

[quote]
____
*Who's On First?*
____

Every game needs a turn sequence. 
For tactical combat we have the unit.
Initiative decides the order that the players get act. 
Initiative is decided by dexterity, level and luck.
Most often the player with fastest and most experienced persona will get to go first.
However tactical initiative is more complex than just going first.

NOTE: *Initiative is shortened to init, and pronounced innish.*

The fog of combat is not well represented by any role-playing system.
The player that wins initiative has the __option__ of moving and attacking first.
Winning initiative gives the winner tactical advantage
There are many situations where it may not be beneficial to go first.
In these instances the player waits her persona's attack rolls and movement. 
The value of this may not be immediately obvious.

:art: initiative_spaceship.png
:width: 250px
:snark: Pilot wins initiative.
:artist: cannot read
:date: 1990
:license: CC BY-SA 4.0
:description: Drawing of spaceship taking off and leaving multiple humanoids behind. 

include::ROOT:partial$articulate.adoc[]

Initiative is not to be confused with ambush. 
There are no secrets that combat is happening, and all participants in combat mode.
Winning initiative gives a tactical advantage for when to move and when to attack.
There are no attack roll bonuses for winning initiative. 

== Initiative Roll
Initiative is rolled once per unit.
All personas roll at once and quickly sum up their total initiative.
Each combatant makes an individual initiative roll on a 1d20, adding their DEX and level.
The referee may make a single initiative roll for a large group of cannon fodder referee personas.
Important canon referee personas will get an individual initiative roll.

.Init = 1d20 + DEX + Level
****
A 4th level person with a 12 DEX rolls 15 on 1d20. Her init roll is 31.
****

If one persona rolls 11, another rolls 14 and another rolls 21 the initiative order is: 21, 14 and 11.
This order does not designate the order of action, but the order of tactical advantage.
The persona that has an initiative of 21 may go first if they wish, but they may also wait to assess before acting.

=== Tied Initiative Rolls
Initiate rolls must be decided there are no ties combat in initiative. 
If there is a tie the tie must be broken.
Even if players are in same expedition the tie must be resolved.

Ties are resolved by rolling 1d10 with the higher roll getting higher initiative.
If two players both have a 17 initiative they both roll 1d10 each.
One player rolls 8 and the other rolls 4.
The initiative values are now 17.8 and 17.4 and the player with 17.8 gets tactical advantage.

== Who Goes First?
The player with tactical advantage decides who goes first.
If the player with the highest initiative wants her persona to move and attack first she may do so.
More often than not the player that wins initiative will wait before attacking or moving.
This gives the player tactical advantage. 
She can wait to see what others are up to before acting.

For example a player that has waited her movement may decide to run out of range of a grenade.
If she had already moved her persona would be subject to the area of effect attack.
The player may wait the attack roll to see which referee persona gets closest to the door before firing.

.*options for initiative*
. forced move and attack
. move and attack
. wait move and attack
. move and wait attack
. wait move and attack
. wait jumping

== Waited Actions
The initiative winners are given tactical advantage, and are not required to act first.
Often it is beneficial to be able to move after the opposition.
Knowing what your opponent is doing offers tactical advantage.
So a higher initiative roll can be used to make the opposition force their hand.
Hence the concept of highest initiative gets tactical advantage, as opposed to moving first.

Any persona may wait their actions until they are forced to act.
The lowest initiative score must move and attack on the first pass through the initiative list.
Waiting to attack, waiting to move, or waiting an action are options for the initiative winner.
The player can mix and match what she waits or acts on.
Eventually all personas will act during the unit. 

Waited actions are lost if the persona is killed, knocked unconscious, stunned, or paralyzed.
It is possible for a weak persona with a dangerous weapon to kill off a strong persona that is waiting.
This can be a serious problem for any persona who's actions have been waited.
Sometimes a player may change her mind about waited actions and want to jump back in. 
For example, if a persona is suddenly in danger she may __wait jump__ and make her move out of queue.

=== Wait Jumping
There is an element of risk when waiting combat actions.
Waited actions are lost if the persona is killed, knocked unconscious, stunned, or paralyzed.
If a player decides her persona is in danger she may __un-wait__ her actions to beat a persona with a lower init.
This is called wait jumping.
A player can wait just movement, attack rolls, or actions.

Wait jumping is not guaranteed and the player must make a Normal AWE roll to jump ahead.
If they fail this roll bad things can happen to a persona waiting their actions.
If they are successful the persona may jump ahead and move or attack before a lower init persona. 

// insert normal AWE roll here.

== Anatomy of a Unit 
Below are four tables that demonstrate an combat unit involving four personas.
At the beginning of the unit all the players roll initiative.

.*Player initiative rolls.*
. Abel, an initiative roll of 26;
. Babel, an initiative roll of 21;
. Cable, an initiative roll of 13;
. Dabel, with an initiative roll of 9.

Each table represents a pass that forces the lowest initiative player to act.
Initiative is only rolled once for the unit. 
The same initiative rolls are used for the entire unit.

include::ROOT:partial$CH33_Table_Init_Pass_1.adoc[]

include::ROOT:partial$CH33_Table_Init_Pass_2.adoc[]

include::ROOT:partial$CH33_Table_Init_Pass_3.adoc[]

include::ROOT:partial$CH33_Table_Init_Pass_4.adoc[]

All four players roll their initiative. 
Abel has a high DEX and Dabel is rolled a really badly.
Dabel's player curses her unlucky dice.
The same initiative rolls are used for the entire unit.

The referee makes the first pass asking the players what they want to do from highest to lowest init roll. 
Abel decides to wait both her attack and move.
Babel does the same.
Cable is happy with her target and makes an attack roll, but stays put.
Dabel complains about being unlucky and must both move and attack.
Dabel throws a rock at her opponent and runs for cover behind a vending machine.

Once Dabel is done the referee makes the second pass again from highest to lowest initiative.
Abel likes the cover of the vending machine and chooses to move there, but waits her attack.
Babel shoots her crossbow at a target and stays put. 
Babel waits her move.
Cable is has the lowest remaining initiative roll. 
Cable must move now. 
She has already made an attack roll.
Cable moves to join Dabel and Abel using the vending machine for cover.

Once Cable is done the referee make a third pass asking Abel what she wants to do first.
Abel has moved and chooses to wait her attack. 
If Abel needed to make an attack roll to intercept an opponent this would be wait jumping. 
Babel has already attacked and must move as she has the lowest initiative on this pass.
Dabel and Cable are done, and are waiting for the next unit.
Babel runs to join Abel, Dabel and Cable behind the crowded and shot up vending machine.

On the last pass for the unit Abel must now act. 
She has already moved so it is her turn to attack.
She is glad she waited her attack because she fired her laser pistol at an opponent that had flanked the vending machine.

The unit is over. 
All players roll again and the process is repeated.

== Mutations
Mental mutation attacks can be used at any time during a unit.
Mental attacks are instantaneous and are unaffected by the initiative list.
If two mental mutations are facing off they make their own initiative using MSTR and level instead of DEX.

Physical mutations do not have this advantage and follow normal initiative.
Robots that have malfunctions and peripherals that function like mutations also follow normal initiative.

== Optimizations
Things that help initiative run smoothly making it more fun for one and all.

.*Initiative Tips*
. Pick the number of rules that work and use one less.
. Ensure lowest init roll moves and attacks promptly
. Players with waited actions must pay attention. Or die.
. Clump referee personas into one init roll
. Save gossip and detailed description for after the unit complete.
. Players that are done need to STF.. er focus for the rest of the unit.
