= Initiative

[quote]
____
*Who's On First?*
____

Every game needs a turn sequence. 
For tactical combat, we have the unit.
Initiative decides the order that the players get to act. 
Dexterity, experience level and luck determine a persona's initiative.
Most often, the persona with the best dexterity will get to go first.
However, the tactical initiative is more complex than just going first.

NOTE: *Initiative shortens to init and pronounced innish.*

Tabletop role-playing systems do not sufficiently represent the fog of combat.
The player that wins initiative has the __option__ of moving and attacking first.
Winning initiative gives the player a tactical advantage.
Tactical advantage does not always mean "going first."
There are many situations where it may not be beneficial to go first.
In these instances, the player "waits" her persona's attack roll, movement or both. 
The value of "waiting" a persona's actions may not be immediately apparent.

:art: initiative_spaceship.png
:width: 450px
:snark: Pilot wins initiative.
:artist: cannot read
:date: 1990
:license: CC BY-SA 4.0
:description: Drawing of spaceship taking off and leaving multiple humanoids behind. 

include::ROOT:partial$articulate.adoc[]

Initiative is not to be confused with ambush. 
There are no secrets that combat is happening, and all participants in combat mode.
Winning initiative gives a tactical advantage for when to move and when to attack.
There are no attack roll bonuses for winning initiative. 

== Initiative Roll
Every player makes an initiative roll every unit of combat.
Each player makes an initiative roll on a 1d20, adding their persona's dexterity score and experience level.
The referee can combine all the referee personas into one initiative roll.
A single initiative roll for a group of cannon fodder referee personas makes sense.
Important referee personas may get an initiative roll.
All personas roll at once and quickly sum up their total initiative.

=== Calculate Initiative 
.Init = 1d20 + DEX + Level
****
Init = 15 (on 1d20) + 12 DEX + 4th level = 31
****

The initiative rolls of three players are 11, 14 and 21.
The order of initiative for the personas is 21, 14 and 11.
This order does not designate the order of action but the order of tactical advantage.
The player with an initiative of 21 may go first if they wish, but they may wait to assess before acting.

=== Tied Initiative Rolls
The dice must decide the order of initiative.
There are no ties in combat initiatives. 
Even if the tie is between players, they must resolve the tie.

The players resolve the tie by rolling an unadjusted 1d10.
This 1d10 result acts as a decimal place added to the initiative roll.
Two players both roll 17 for initiative.
They now both roll a 1d10 each.
One player rolls 8, and the other player rolls 4.
The initiative values are now 17.8 and 17.4, and the player with 17.8 wins the tactical advantage.

== Who Goes First?
The player with tactical advantage decides who goes first.
If the player with the highest initiative wants her persona to move and attack first, she may do so.
More often than not, the player that wins initiative will wait before attacking or moving.
Waiting her attack or move gives the player a tactical advantage. 
She can wait to see what other personas are up to before acting.

For example, a player that has waited her movement may decide to run out of range of a grenade.
If she had already moved, her persona would be subject to the area of effect attack.
The player may wait her attack roll to see which referee persona gets closest to the door before firing.
Sometimes every player will wait both their actions, and this forces the player with the lowest initiative to move and attack first.

.*Player Initiative Choices*
. Forced actions.
. Regular actions.
. Wait actions.
. Wait jumping.

== Forced Actions
If there are no personas left to act, then the remaining persona must move and attack.
Being forced to attack and move is called forced action.
If every other persona has waited actions, the lowest on the init order is forced to act.
Forced actions are entirely normal.
The persona can attack-move, move-attack or do some non-combat action. 

== Regular Actions
In the normal process of a unit, regular actions take place in a regular fashion.
The persona carries out regular actions if they act when their turn in the init order comes up.
The persona can attack-move, move-attack or do some non-combat action. 
If the players have chosen not to use waited actions, all actions are regular actions carried out in the init order.

== Waited Actions
The initiative winners are given a tactical advantage and are not required to act first.
Often it is beneficial to be able to move after the opposition.
Knowing what your opponent is doing offers a tactical advantage.
The player can use her higher initiative roll to force her opponent to play their hand (or claw).
Hence the concept of the highest initiative gets the tactical advantage, as opposed to simply acting first.

Any persona may wait their actions until forced to act.
Every persona will eventually have to make their actions.
Waiting to attack, waiting to move, or waiting a non-combat action are options for the initiative winner.
The player can mix and match what she sees fit.

Waited actions are lost if the persona is killed, knocked unconscious, stunned, or paralyzed.
A weak persona with a dangerous weapon can kill off a strong persona that has waited her actions.
Sometimes a player may change her mind about waited actions and jump back into the init order. 
For example, if a persona notices a grenade is coming her way, she  __wait jump__  and gets back into the init order.

=== Wait Jumping
There is an element of risk when waiting combat actions.
Waited actions are lost if the persona is killed, knocked unconscious, stunned, or paralyzed.
If a player decides her persona is in danger, she may __un-wait__ her actions to beat a persona with a lower init.
Getting back into the init order is called wait jumping.
A player can wait jump movement, attack rolls, or actions.

Wait jumping is not guaranteed, and the player must win a normal (1d20) awareness roll to wait jump successfully.
If the player wins the awareness roll, her persona may jump back into the init order and move or attack before a lower init persona. 
If she fails this roll, bad things can happen to her persona.
To learn how to make an awareness roll jump to xref:i-roll_playing_rules:CH16_Special_Rolls_Attributes.adoc[Attribute Rolls,window=_blank].

== Anatomy of a Unit 
An expedition of four personas gets into a 'situation,' and the game moves into combat time.
The minis are on the hex mat, and the players are getting tactical.
The referee calls for initiative rolls and creates and creates an init order from the rolls. 
The referee's init roll for her referee persona is excluded from the init order for convenience.

.*Player initiative rolls.*
. Abel rolls 26.
. Babel rolls 21.
. Cable rolls 13.
. Dabel rolls 9.

The persona Abel has high dexterity and often tops the init order.
Dabel's player curses her unlucky 1d20.
The referee goes through the init order asking each player what she wants her persona to do.

Abel and Babel wait their actions to try and gain a tactical advantage.
Cable is happy with her target.
She makes an attack roll but does not move yet.
Dabel complains about being unlucky and must both move and attack.
Dabel throws a rock at her opponent and runs for cover behind a vending machine.

include::ROOT:partial$CH33_Table_Init_Pass_1.adoc[]

Dabel is done for this unit and chooses to stop complaining about luck.
Abel likes the cover of the vending machine and chooses to move there but waits her attack.
Babel shoots her crossbow at a target and stays put (waits her move). 
Cable has no choice but to use her remaining actions. 
She has already attacked with her crossbow and now must move.
She joins Able and Dabel behind the vending machine.

include::ROOT:partial$CH33_Table_Init_Pass_2.adoc[]

Dabel and Cable are done for this unit.
Actions are starting to speed up.
Abel chooses to wait her attack.
Babel must now use her remaining actions.
Babel has already attacked and must move.
She joins the other three behind the crowded and heavily damaged vending machine.

include::ROOT:partial$CH33_Table_Init_Pass_3.adoc[]

Dabel, Cable and Babel are done for this unit.
Abel must now act. 
She has already moved, so it is her turn to attack.
She is glad she waited her attack because she fired her laser pistol at an opponent that had flanked the vending machine.

include::ROOT:partial$CH33_Table_Init_Pass_4.adoc[]

The unit is over. 
All players roll again, and the process repeats.

include::ROOT:partial$CH33_Table_Init_Pass_5.adoc[]

== Mutations
Aliens and anthros can use mental mutations at any time during a unit.
Mental attacks are instantaneous and are unaffected by the initiative list.
If two mental mutations are facing off, they make an initiative roll where mental strength replaces dexterity.

Physical mutations follow the usual dexterity-based initiative roll.
All robot mutation-like attacks follow the usual dexterity-based initiative roll.

== Optimizations
Things that help initiative run smoothly, making combat more fun for one and all.

.*Initiative Tips*
. Pick the number of rules that work and use one less.
. Ensure lowest init roll moves and attacks promptly.
. Players with waited actions must pay attention. Or die.
. Clump referee personas into one init roll.
. Save gossip and detailed description for after the unit completes.
