= Attack Roll Adjustments

Attack roll adjustments affect the player's chance of successfully hitting and damaging targets.
Combat adjustments are added or subtracted from the player's kilodie attack roll.
These adjustments are most often penalties that impair ranged attacks by obscuring targets.  
They includes: weather, cover, concealment, range, and firing blind.
Type A attacks are not affected by these attack roll adjustments.

== Armour Rating
Attack roll penalties do not change the target's armour rating. 
For example a target may have 90% cover from one direction and no cover from another direction.

== Combat Tables
Attack roll penalties do not affect the persona's combat table.
The persona's Bonus Proficient (BP), and Maximum Roll (MR) remain the same.
A skilled persona with a high BP can overcome weather and range penalties
An attack roll penalty is subtracted from the player's raw kilo-die roll.

Attack roll bonuses are added to the 


=== Bonuses
Attack roll bonuses are added to the player's net attack roll, even if that is the persona's Maximum Roll (MR).
Thus a rear attack (+90 attack roll) with a club could allow the player to surpass her persona's MR (Maximum Roll) and possibly hit a previously impervious target.
Consider the following scenario of a persona  with a Maximum Roll (MR) of 763 is trying attack roll a target with an Armour Rating (AR) of  793.
Under normal circumstances, the persona could not hit the target because her Maximum Roll (MR) is too low.
However the rear attack attack roll bonus of +90 adjusts the net attack roll upwards by 90.
This means that the net attack roll could be as high as 883 (MR of 793 plus 90) allowing the persona attack roll a target she cannot normally hit when attacking from behind.
This method of administering attack roll bonuses is blatantly biased towards the players.
There is no justifiable reason for players to be excluded from combat because their persona has an inadequate Maximum Roll (MR).
Attack roll bonuses allow the a player to gain a chance attack roll a target through ingenious, or experienced, tactics.

== Weather Conditions
Weather conditions affect the attack rolls of ranged weapons.
There are no effects from snow, or rain on hand to hand combat (type A attacks).
Grenades are affected by weather conditions, while aerosols are not.

:art: combat_adjustments_insect_smoke.png
:width: 250px
:snark: Through rain and sleet and smoke.
:artist: Eric Hotz
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of humanoid insect and human in smoke filled frame.

include::ROOT:partial$articulate.adoc[]

Most of the weather penalties are per hex of range.
For example, shooting a gun through thick smoke at a target ten hexes away is a -600 attack roll penalty
All personas on the hex mat are suffering the same attack roll penalty.
If a penalty is high enough it is equivalent to firing blind. 
Firing blind is self descriptive.

Really low per hex penalties, like -2 per hex in trace fog, should only be applied for important shots.
For example, a persona may be attempting to snipe an important enemy. 
In this case the referee and player may find a hit or miss determined by -4 on the attack roll exciting.
These penalties are part of the tactical combat system. 

// insert table 346
include::ROOT:partial$CH35_Table_Rain_To_Hit_Roll_Penalty.adoc[]

// insert table 347
include::ROOT:partial$CH35_Table_Hail_To_Hit_Roll_Penalty.adoc[]

// insert table 348
include::ROOT:partial$CH35_Table_Sandstorm_To_Hit_Roll_Penalty.adoc[]

// insert table 349
include::ROOT:partial$CH35_Table_Wind_To_Hit_Roll_Penalty.adoc[]

// insert table 350
include::ROOT:partial$CH35_Table_Fog_or_Smoke_To_Hit_Roll_Penalty.adoc[]

// insert table 351
include::ROOT:partial$CH35_Table_Darkness_To_Hit_Roll_Penalty.adoc[]

// insert table 352
include::ROOT:partial$CH35_Table_Snow_To_Hit_Roll_Penalty.adoc[]

// insert table 353
include::ROOT:partial$CH35_Table_High_Gravity_Effects_Penalty.adoc[]

== Cover and Concealment
Cover and concealment are attack roll penalties that are attributed to targets that are hiding.
Cover and concealment penalties apply to ranged attacks only (types B and C).
Attack roll penalties do not change the target's armour rating. 
For example a target may have 90% cover from one direction and no cover from another direction.

:art: dinner_in_a_tube.png
:width: 250px
:snark: Dinner has own tooth pick.
:artist: Louis Glanzman
:date: 1954
:license: CC BY-SA 4.0
:description: Drawing of human trapped in cave by big mouthed dinosaur.

include::ROOT:partial$articulate.adoc[]

Cover and concealment  are completely different entities. 
Cover protects the target from incoming projectiles.
Concealment hides the target from incoming projectiles.
If a player continues to attack a completely hidden target they are firing blind.

An attacker can transform cover to concealment if by using a different weapon.

=== Aliens
Cover and concealment for aliens is decided on a case by case basis.
The referee may have milieu specific variations. 

:art: space_bug_big.png
:width: 250px
:snark: You can hit me, not hurt me.
:artist: Wallace Saaty
:date: 1941
:license: CC BY-SA 4.0
:description: Drawing of rollercoaster sized alien being shot at by army, police and crowd.

include::ROOT:partial$articulate.adoc[]

For Large and smaller sized aliens cover and concealment works the same as for anthros.
For Gigantic aliens cover and concealment is virtually impossible.
Cover and concealment should also be reserved for tool using aliens and those with natural ranged attacks.
Partial hiding is not in the purvey of flora and fauna. 

=== Robots
Cover and concealment for robots is decided on a case by case basis.
The referee may have milieu specific variations. 

Only Medium and smaller sized robots can use cover and concealment. 
Cover and concealment is very tactical should be limited to combots.
Other robots either hide or expose themselves. 

=== Cover 
Cover is when a persona places an solid barrier between herself and the attacker's weapon.
Typical cover includes: rocks, tree trunks, hills, and corners of buildings.
If a bullet, lazer bolt, or arrow hits cover it is stopped in it's tracks.
The referee or Sphincter Dice can decide if a barrier is cover or concealment.
The more cover that a target has the greater the attack roll penalty.

=== Concealment 
Concealment is when a persona places an obscuring barrier between herself and the attacker's weapon.
Typical concealment includes: bushes, tents, drywall, and paintball buildings.
A bullet, lazer bolt, or arrow can pass through concealment.
The referee or Sphincter Dice can decide if a barrier is cover or concealment.
The more concealment that a target has the greater the attack roll penalty.
Concealment attack roll penalties are much lower than cover attack roll penalties.

include::ROOT:partial$CH35_Table_Cover_and_Concealment_Penalty.adoc[]

=== Example 
If a target has 90% cover (a concrete bunker) there would be -450 attack roll penalty
Another target has 90% concealment (in the bushes) there is a -80 attack roll penalty.
The attacker has an idea where the target is with concealment (bushes) and this helps scoring a hit.
The attacker has an idea where the target is with cover (bunker) but this info cannot help.
 
If an attacker were to switch weapons then cover can be reduced to concealment. 
What might be cover for an arrow may not be cover from an XHP rifle. 

== Firing Blind
Firing blind refers to attacks made against targets which are not visible.
The attacker may have an idea where the target is but target has 100% concealment.
Blind firing applies if the target is unseen due to smoke, blindness, invisibility, or tear gas.
Firing blind does not apply to target's with 100% cover.

Firing blind is limited to projectile weapons (Types B, C, D, E, and F).
The projectile must be able to penetrate the concealment. 
Contact attacks (Type A) and area of effect weapons are not part of the firing blind rule set.

Firing blind is mostly luck.
The attacker thinks a target is hidden behind some concealment. 
The cannot aim at the target so they fire into the concealment.
This concealment could be bushes, drywall, or dense smoke.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

The most __tactical__ way to play blind firing is that the referee gives the player no information when firing blind.
Cunning players can extract tactical information depending on how the referee plays firing blind.
To keep the target's concealment total the referee may employ the following steps.

.*meticulous blind firing rules*
. player chooses to attack
. player makes attack roll and damage roll
. referee check the Percent Chance To Get An Attack Roll Dependent On Relative Size of Target If Concealed So Not Visible Table
. no info is given until the persona investigates

The persona may find a dead body, wounded or nothing at all in the bushes.
That is the fog of war.

include::ROOT:partial$CH35_Table_Percent_Chance_To_Have_A_Chance_To_Roll_To_Hit_Dependent_On_Relative_Size_of_Target_If_Concealed_So_Not_Visible.adoc[]

== Range Penalties
The range is the number of hexes between the attacker and the target.
The first hex is the one immediately in front of the attacker, and the last hex is the one containing the target.
Thus a target on an adjacent hex would be one hex away.

:art: Figure_range_examples.png
:width: 450px
:snark: Not an oven range.
:artist: hexes Pixabay. Colour HM
:date: 2020
:license: CC BY-SA 4.0
:description: Diagram showing range penalties using hexagon sheet.

include::ROOT:partial$articulate.adoc[]

There are no range penalties if the target is within the maximum range of the attack.
Maximum ranges vary by weapon construction, tentacle length and robot physical strength
The range attack roll penalties are per hex penalties applied per hex beyond the attack's range.

== Movement Penalties
A persona can use their entire movement rate per unit without penalty.
Movement Rate is the designated amount that a persona can move during a combat unit. 
There are some movement choices that the player can make that affect attack rolls.

=== Movement Differential
When the attacker and the target are moving at vastly different speeds there is an attack roll penalty.
This attack roll penalty is only meant for massive movement rate differentials. 
The kind of differentials created by a vehicle. 

Movement differential attack roll penalties are not applied to natural combat movement rates.
For example a super fast alien would only suffer a movement differential attack roll penalty if she were in a moving vehicle.
Her natural movement rate would never cause an attack roll penalty.

The difference in movement rate must be greater than 10 h/u. 
There is a -10 attack roll penalty per h/u difference in movement rate. 
This is what makes it hard to hit a target from a moving vehicle or vice versa.

=== Differential Movement Rate Attack Roll Penalty
.penalty = -10 per h/u difference.
****
A persona is in a jeep going 50 h/u. Her target is running away at 10 h/u. 40 h/u difference is a -400 attack roll penalty.
****



include::CH12_Combat_Movement.adoc[tag=Combat_Movements]

// flanking bonuses

== Further Points
Take all these adjustments with a table spoon of salt.
This is a faux realism tactical combat system.
Only the most obvious attack roll adjustments are included here.
Most have been added to EXP as they kept recurring and needed a written ruling.
Most often the referee and players will improvise a ruling that seems fair.
If negotiation is not successful the Sphincter Dice should be consulted.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

