= Non-Lethal Combat

[quote]
____
*The goal of non-lethal combat is to subdue the target not kill.*
____

Non-lethal combat is cinema style punch pulling, shin kicking, chair swinging, all out brawling.
The goal of non-lethal combat is not to kill the opponent, but to subdue the opponent.
Subdual occurs when a persona fails a Damage System Shock Roll and is unable to continue.
Non-lethal does not mean benign. 
Each attack still does some damage, and accidents still occur.

Non-lethal and lethal personal combat can be used simultaneously.

.*Non-Lethal Combat Requirements*
. Only striking weapons (fists, clubs) can be used
. Combatants must comprehend the concept (tool users)
. Combatants must be roughly the same size

Only attack types that can have a non-lethal component can be used in non-lethal combat.
For example, fists and flippers are okay, daggers and guns are not.

The combatants must be able to grasp the concept of surrender.
Non-lethal combat is usually limited to anthros, and tool using aliens.
Flora and fauna do not understand surrender and only lethally fight for their lives.
Robots may attack non-lethally, but non-lethal combat has no effect on them.

// what size range restrictions could you use? two levels on the size chart

== Attack Rolls
Non-lethal combat is part of the tactical combat system and works the same way.
Players make attack rolls with kilo-die and try attack against the target's armour rating.
Proficiency in Hand to Hand combat would be required to use the BP (Bonus Proficient).
The key difference is in how the damage is delivered.

Only certain attacks can be used in non-lethal combat.
Type A attacks like Fists, feet, hooves and flippers are allowed.
Type B attacks like rocks, plates, bottles, and cheese wheels are allowed.
There are no Type C, D, E, F, or AOE weapons allowed. 
The only exception are powered stun weapons specifically designed to be non-lethal.

== Damage
Combatants in non-lethal combat are not eye gouging, throat punching, or intentionally snapping bones.
They attack non-lethal, but painful, body locations.
It is expected that the attacker will be pulling her punch at the last millisecond, using the flat side of a sword, and not following through with a kick.
Full damage is rolled normally after a successful attack roll.
The full damage is used for a Damage System Shock check. 
Only 10% of the damage is subtracted from the target's HPS Total.
The more damage delivered the more likely the attack will become accidentally lethal.

=== Non-Lethal Damage
.HPS Damage -> 100% vs DSS. % check for oops. 10% from HPS Total.
****
10 HPS non-lethal subtract 1 from HPS Total. Check for DSS vs 10 HPS Damage. With a 10% chance of oops lethal damage.
****

=== Oops Damage
Non-lethal attacks are not as easy as they appear in the movies.
Personas may accidentally deliver a lethal blow each not lethal attack.
Only personas with hand to hand combat skill can avoid the check for oops damage. 
Unskilled at non-lethal combat, a persona may accidentally deliver a lethal blow.
There is a 1% chance per HPS of damage that the non-lethal attack will convert to lethal.
For example, 15 HPS of non-lethal damage has a 15% chance of becoming 15 HPS of oops lethal damage.

Occasionally a persona may wish to make a lethal attack followed up with nonlethal attacks, this procedure softens up a target, and makes her easier to subdue.

=== Victory Conditions
Players may have their personas volitionally surrender to end non-lethal combat.
A persona may succumb to a failed DSS Roll. 
A persona may die from oops lethal damage.

NOTE: *In non-lethal combat aliens use the DSS Roll to identify subdual.*

=== Damage System Shock 
include:i-roll_playing_rules:CH04_Anthros_HPS.adoc[tag=Anthro_DSS]

== Example Non-Lethal Combat
A persona punches at a target that has 23 HPS Total.
The attack roll is successful and she rolls 7 HPS damage (non-lethal).
The target compares the 7 HPS of damage to see if she needs to make a DSS Roll. 
She does not.
The attacking persona makes a 1d100 roll to see if the attack is lethal oops lethal.
With 7 HPS damage a roll of 7 or less on the 1d100 would turn the attack lethal.  
There is no lethal oops damage.
The target subtracts 1 HPS from her HPS Total (ouch), and her new HPS Total is 21.

.*Suggested Approach for Non-Lethal Combat*
. Attack Roll 
. Damage Roll
. Check for DSS (all damage)
. Check if oops (% = damage)
. Subtract from HPS Total (non-lethal or oops lethal)

Next unit the attacker scores a hit with a chair (purely a dramatic description).
She generates 15 HPS of non-lethal damage.
15 HPS is greater than half the target's HPS Total of 21.
The target must make a DSS Roll or be subdued.
Her roll is successful and she is still standing.
Accidentally oops damage does not occur (15% chance).
The target subtracts 2 HPS from her HPS Total (ouch), and her new HPS Total is 19.

This continues until victory condition are met.

== Grapples, Pins and Tackles
Grappling is any non-lethal hand to hand attack that is designed to hold the target in one place.
Tackles, head locks, full nelsons, father nelsons, pins, and wrap arounds are all considered grapples.
Like any attack, a grapple requires a attack roll against the target's armour rating.
The attacking player can add what ever adjustments are appropriate to her attack roll.
Only personas with hand to hand skills can use their Bonus Proficient when grappling.
If the attack roll is successful the grapple is successful.
A grappled target can try to break free, attack, or reverse the grapple.
Only close range weapons like daggers and pistols can be used in grapple combat.

Full armour ratings apply as combatants are in combat and doin' the jiggly wiggly combat dance.

.*Grasping the Grapple*
. Successful attack roll
. PSTR Roll vs target PSTR
. Break Free
.. PSTR Roll vs grappler PSTR
.. Damage grappler (requires DEX Roll)
. Reverse the Grapple
.. Break free
.. Successful attack roll

It is assumed that the grappling parties will be writhing back and forth, rolling around etc. etc.
If another persona attacks one of two grapplers and misses their attack roll they can hit the other persona.

Big targets can be grappled by more than one persona at a time. 
Working through this situation is up to the referee and players. 

== Weapon Snatching
Weapons snatching is the classic tv trick to turn the tables on dastardly pikers!
Weapon snatching is considered non-lethal personal combat.
Often players want to snatch an opponent's weapon, either to avoid a dangerous situation.
Grappling someone's weapon is impossible in most situations, and extremely difficult in those situations where it is possible.
Since weapon snatching is deeply embedded in our cinematic culture the tactical system has an approach.

. Grab Attempt: Type A attack BNP only
.. Miss gives gun helder +242 attack bonus
. Take weapon: PSTR roll vs target PSTR
.. Fail gun helder +141 attack bonus
. Gun helder grab attempt
. Grabbed guns cannot be used in same unit as grab

The initial grab is considered a type A attack.
The persona can use her Bonus Non-Proficient (BNP) to grab the weapon.
The attack roll is against the target's Armour Rating (AR).
If the grab attack roll is successful she has grappled the weapon but does not control it.
To wrestle the weapon free she must win a PSTR challenge against the target.
If the PSTR roll is successful the former owner gets a grab chance immediately after.
The weapon cannot be used in its grab unit.

Failing the attack roll makes the grabber vulnerable and the weapon helder gets +242 attack bonus 
Failing the PSTR challenge makes the grabber vulnerable and the weapon helder gets +141 attack bonus.

== Tripping
Tripping up a target before they get to the giant red activation switch is more commonly done than one would expect.
Tripping is another non-lethal attack.
It requires a attack roll, using BNP, against the target's Armour Rating (AR).
The attacker (in this case tripper) must win a PSTR attribute roll before making a successful trip.
Too bad the target is not an Italian soccer player.
If the attack roll and PSTR attribute roll are successful the target still gets a chance to avoid being tripped by winning a DEX challenge with the attacker.  As always these rules are just guidelines, and the referee must be prepared to have common sense invade the rules of EXP.
Other things to consider when making rulings about tripping are size differences, risk to attacker, PSTR differences, experience levels, and movement rates.

== Shooting To Disable
Another cinematic wonder is the shooting to disable a target or disarm a target.
If a player declares she is trying to disarm an attacker only a few things change.
The player must make a successful attack roll vs the armour rating of the target.
The EXP way of approaching this to use Hit Location.
The player will be able to shift her hit location on the table upwards or downwards.
If the persona is trying to disable and they can move the hit location to the legs they are successful.
If the persona is trying to disarm and they can move the hit location to the weapon they are successful.

Damage is rolled as usual and is delivered in full. 

Jump to the xref::CH36_Hit_Locations.adoc[Hit Location Charts] for info about hit locations and shifting attacks.



