= Non-Lethal Combat

[quote]
____
*The goal of non-lethal combat is to subdue the target, not kill.*
____

Non-lethal combat is cinema-style punch pulling, shin-kicking, chair swinging, all-out brawling.
The goal of non-lethal combat is not to kill the opponent but to subdue the opponent.
Subdual occurs when a persona fails a Damage System Shock Roll and is unable to continue.
Non-lethal does not mean benign. 
Each attack still does some damage, and accidental death can occur.
The players can use non-lethal and lethal personal combat simultaneously.

.*Pugilistic Parameters*
. Strike attacks only (fists, clubs, feet, sticks)
. Anthros and educated aliens only.
. Subduer must be of comparable size.

The attacker can use only certain attacks in non-lethal combat.
Strike attacks like Fists, feet, hooves and flippers are allowed.
Fling attacks like rocks, plates, bottles, and cheese wheels are allowed.
Pointy Fling attacks like arrows and daggers are not allowed.
There are no Shoot, D, E, F, or AOE weapons allowed. 
The only exception is powered stun weapons specifically designed to be non-lethal.

The combatants must be able to grasp the concept of surrender.
Flora, fauna and robots do not understand surrender and beating them does not help.
Flora and fauna do not understand surrender and only lethally fight for their lives.
Robots may attack non-lethally, but non-lethal combat has no emotional impact on them.

== Attack Rolls
Non-lethal combat is part of the tactical combat system and works the same.
Players make attack rolls with kilodie and must beat the target's Defence Rating.
Proficiency in hand-to-hand combat is required to use one's Strike Skilled Bonus.

== Non-Lethal Damage
Combatants in non-lethal combat are not eye-gouging, throat punching, or intentionally snapping bones.
They attack non-lethal but sensitive body locations.
The attacker is not trying to kill the target, and she will be pulling her punch at the last millisecond.

The player rolls damage after a successful attack roll.
This damage value becomes the potential damage.
The potential damage determines the chance of knocking the opponent out, the amount of actual damage, and the chance of severe damage.

Personas can hold back their Strike Force Bonus and only generate the non-lethal damage of the weapon type.
The player must choose to use, or not use, her Strike Force Bonus. 
She cannot use part of the Force Bonus.
Only personas with hand-to-hand combat skill can choose how much Force Bonus to add to their non-lethal damage score.

.*Non_Lethal Damage Effect*
. Stun Check using non-lethal damage.
. Oops Damage chance = non-lethal damage as %
. Damage using 10% of non-lethal damage


== Stun Check 
A damage system shock check determines if the persona is stunned by the non-lethal blow.
The stun could either be a knock-out blow or a collapse from compounded hammering.
The target must win a damage system shock roll (DSS) against the non-lethal damage value or be stunned. 

=== Damage System Shock Roll (DSS)
.1d20 + HPS + CON + LVL > 42
****
A 1st level anthro with 30 HPS and 10 CON  must roll one on 1d20. +
A 1st level anthro with 20 HPS and 10 CON  must roll 11 on 1d20. +
A 1st level anthro with 11 HPS and 10 CON  must roll 20 on 1d20
****

== Oops Damage
Non-lethal attacks are not as easy as they appear in the movies.
Personas may accidentally deliver a lethal blow instead of a non-lethal attack.
Unskilled at non-lethal combat, a persona may accidentally deliver a lethal blow.
Personas with hand-to-hand combat skill can avoid oops damage. 

There is a 1% chance per HPS of damage that the non-lethal attack will convert to an accidental lethal attack.
For example, 15 HPS of non-lethal damage has a 15% chance of becoming 15 HPS of oops lethal damage.

=== Oops Damage 
.Chance Lethal = 1% per point of Non-Lethal Damage
****
Lethal = 15 HPS non-lethal = 15% chance of inflicting 15 HPS damage
****
A player can combine lethal and non-lethal attacks. 
This method softens up a target and makes her easier to subdue.

== Damage
Every non-lethal damage roll inflicts a smaller amount of actual damage. 
Ten percent of the non-lethal damage causes actual damage to the target.
The target's hit point total (HPS) loses that amount for every successful attack roll.
Eventually, non-lethal combat will drop the target.

If the attacker messed up and did accidental lethal damage, this section does not apply. 

=== Actual Damage 
.Damage = 10% of Non-Lethal Damage (round up)
****
Damage = 0.1 * 15 HPS non-lethal =  2 HPS damage.
Damage = 0.1 * 12 HPS non-lethal = 1 HPS damage.
****

== Victory Conditions
A persona may have had enough and calls it quits.
A persona may be stunned by a failed DSS Roll. 
A persona may be knocked unconscious by an accidental damage bolus.
A persona may die from accidental damage.

== Example Non-Lethal Combat
A persona punches a 2nd level target with 23 HPS Total and a ten Constitution.
The attacker's player wins her attack roll, and she rolls 7 HPS of non-lethal damage.

The target's player must win versus damage system shock or be stunned.
The DSS calculation uses the target's temporary HPS of 16 (23 - 7).
This temporary HPS is only for DSS.
The HPS + CON + LEVEL score is 28, and the player must roll 14 or higher on the 1d20 not to be stunned. 
The player rolls a 15 and merely develops an angry disposition.

The attacker's player must check to see if she delivers some oops damage.
There is only a 7% chance of that happening, and it does not.

Getting punched delivers some real damage to the target. 
10% of the non-lethal damage is deducted from the target's HPS.
The target takes 1 HPS damage, and her HPS drops from 23 to 22.
This combat continues until victory conditions occur.

== Grapples, Pins and Tackles
Grappling is any non-lethal hand-to-hand attack that is intending to hold a target in one place.
Tackles, headlocks, full nelsons, father nelsons, pins, and wrap-arounds are all considered grapples.
Like any attack, a grapple requires an attack roll against the target's Defence Rating.
The attacking player can add whatever adjustments are appropriate to her attack roll.
Only personas with hand-to-hand skills can use their Skilled Bonus when grappling.
If the attack roll is successful, the grapple is successful.
A grappled target can try to break free, attack, or reverse the grapple.
Personas can use only close-range weapons like daggers and pistols in grapple combat.

Armour ratings apply as combatants are in combat and doin' the jiggly wiggly combat dance.

.*Grasping the Grapple*
. Attack roll
. Strength competition
. Break Checks

=== Attack Roll
The player makes a usual attack roll made against the target's Defence Rating.
Grappling is a Strike attack.
The player must use her Raw Bonus unless she has hand-to-hand combat skill.

=== Strength Competition
The player must win a Strength vs Strength challenge to immobilize the target.
If she loses this roll, she cannot make any other attack or move during the combat unit.
The target may move or attack, but there are no attack roll bonuses.
IF the player wins this roll, both the target and the attacker are immobilized. 

=== Break Checks
The target can make a break check every unit.
Per unit break checks may seem too frequent, but the assumption is that the grappling parties are writhing back and forth, rolling around, etc.
If the grappled target wins the Strength challenge, they can break free, move and attack.

=== Strength Competition
.1d20 + STR + Level both personas
****
Whichever player rolls higher wins the challenge. +
Grappler wins; the target is grappled. +
Grappler loses; the target can move and attack.
****

== Weapon Snatching
Weapons snatching is a classic cinema trick to turn the tables on dastardly pikers!
Weapon snatching is part of non-lethal personal combat.
Often players want to snatch an opponent's weapon.
Grappling someone's weapon is impossible in most situations and extremely difficult in those situations where it is possible.
Weapon snatching is part of our cinematic culture, and if the referee is going to allow it, the tactical system has an approach.
The player must win an attack roll, a Dexterity competition and a Strength competition to wrestle a weapon from the target. 

.*Grappling a Weapon*
. Attack roll
. Dexterity competition
. Strength competition

=== Attack roll
The player makes a usual attack roll made against the target's Defence Rating.
Weapon grappling is a Strike attack.
The player must use her Raw Bonus unless she has hand-to-hand combat skill.

=== Dexterity Competition
The gun grabber must win a Dexterity competition to get ahold of the weapon. 
If the grabber fails this Dexterity competition, they have placed themselves in grave danger.
If the target persona has an attack remaining, they get a +242 attack roll bonus on their attacker.

=== Dexerity Competition
.1d20 + DEX + Level both personas
****
Whichever player rolls higher wins the challenge. +
Grappler wins; move onto the STR competition. +
Grappler loses; the target gets +242 on her attack roll.
****

=== Strength Competition
If the persona has successfully grappled the weapon, she must now overpower the target's grip on her weapon.
If the grabber fails this Strength competition, they have placed themselves in danger.
If the target persona has an attack remaining, they get a +141 attack roll bonus on their attacker.

=== Strength Competition
.1d20 + STR + Level both personas
****
Whichever player rolls higher wins the challenge. +
Grappler wins; the target is disarmed. +
Grappler loses; the target gets +141 on her attack roll.
****

== Tripping
Tripping a persona before getting to the giant red activation switch is more common than one would expect.
Tripping is another non-lethal attack.
The player must win an attack roll and a Strength competition to get a chance to trip.
The target then has a chance to dodge the trip by winning a normal Dexterity roll. 
Too bad the target is not an Italian soccer player.

For trips to work, the target and the attacker should be about the same size. 
The target must also be trippable.
The attacker cannot trip a robot with treads.