= Exatmo Vehicle Combat

[quote]
____
We shall fight them on the beaches. We shall fight them in the troposphere. We shall fight them in the cold, silent darkness of space. 
____

Combat in outer space is very deadly.
The threat to organic life is total.
The speeds are incredible.
The weapons are formidable. 
Life enjoying personas avoid space vehicle combat.
The space vehicle combat in EXP supports intimate skirmishes between solitary vessels.
This section is not for battling armadas that can vaporize kilometre-long battle cruisers.
One-on-one space vehicle battles allow the players to be more involved.

:art: space_combat_missiles.png
:width: 450px
:snark: Billions of credits being wasted.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of spaceship launching missiles and firing lazers.

include::ROOT:partial$articulate.adoc[]

Space vehicles are extremely valuable.
Personas prefer to take over space vehicles rather than destroy them.
Most space combat will end with the expedition boarding a defeated vessel or defending a defeated vessel.

The procedure for space vehicle combat is similar to lethal persona combat.
There are turns, initiative, attack rolls, damage rolls, and effects of damage.
For the most part, the computers are running the show in space vehicle combat.
The players can make some decisions, but the execution and success of the combat is a battle of the ships.
The space vehicle computers manage maneuvers, generate electronic countermeasures, and guide missiles.
The organics onboard buckle down while the ship spins to put as much hull between its integral components and incoming attacks.

== Space Vehicle Nomenclature
Exatmo is a contraction for exterior to atmosphere. 
Exatmo is deadly to all personas (anthros, aliens and robots) unless they are specifically protected.
ECM is an acronym for electronic countermeasures. 

A vehicle must have exatmo or special drives to be a space vehicle.
An airship only has an inatmo drive.
An airship could be a plane or a dirigible, but not a space vehicle.

include::ROOT:partial$CH38_Table_Nomenclature_of_Space_Vehicles.adoc[]

Space vehicles are created in the xref:iii-hardware:CH52_Space_Vehicle.adoc[Space Vehicles] section.
Players and referees should understand space vehicles before blowing them up.

== Escape
Personas can avoid space vehicle combat by running away.
Space vehicles are so diverse that one vessel can usually escape another.

NOTE: *The best way to win a space fight is by 12 parsecs.*

One can run away using exatmo drives.
One can dive into the atmosphere using inatmo drives.
One can jump away using special drives.
Unless a ship's drives are damaged, the expedition can choose to escape.
In general exatmo vehicle combat is agreed upon by both parties.

== Elements of Exatmo Vehicle Combat
Exatmo vehicle combat happens at tremendous speed.
Exatmo vehicle combat happens at tremendous distances. 
There are many ways to attack a space vehicle.
ECM, ramming, mines, boarding and artillery.
Most personas will prefer to board and take over a ship due to its value.

.*Unique Elements of Exatmo Vehicle Combat*
. Combat parameters are massive
. Computer-controlled combat
. Combat turns are different
. Victory conditions are unique.

=== Combat Parameters
On an astronomical scale, the distances between space vehicles are minuscule.
For players and their personas, these distances are enormous.
Battling space vehicles could be tens of kilometres apart. 
Only when ramming and boarding do space vehicles come close to each other. 

The speeds are entirely unrealistic. 
Space vehicles use their exatmo drives to maneuver during combat. 
Exatmo drives move at up to 0.9 the speed of light. 
Space vehicles must be travelling at almost the same speed to engage.

=== Computer Controlled
No lifeforms can balance all that is needed to engage in combat.
The combat happens at tremendous speeds.
The combat happens at tremendous distances. 
The process requires many simultaneous calculations.
The ship's computer is not just a calculator. 
The computer integrates with every aspect of the ship.

Only the ship's computer can manage the connectivity and calculations required for combat.
Players and personas are mainly uninvolved in exatmo vehicle combat.
The computers determine the attack sequences, movement and tactics of combat.
The players get to roll dice, but the computer is deciding the combat course.

=== Combat Turns
A turn in exatmo vehicle combat is very different from a combat unit in the tactical combat system.
Space combat turns are longer and more structured than the free-wheeling 2-second tactical combat unit.
A combat turn lasts one minute and involves a stepwise execution of attacks and defences.
During a turn, the combatant vessels are wildly jockeying for position at half the speed of light.
The ship computers are firing missiles, dumping mines, calculating ECM, and aiming artillery.
Most often, the personas will be idle as the players make attack rolls and decisions. 
However, it is also possible for personas to use every unit of the turn doing other stuff.

Players do not make a lot of decisions during exatmo vehicle combat. 
The cycle of attack, defend and counter-attack is built into the turn. 
There are initiative rolls, attack rolls, defence rolls, and damage rolls to be made each turn.
The process continues until a vessel escapes or achieves victory conditions. 

=== Victory Conditions
The victory conditions of space vehicle combat are unique to the vessel itself.
The victory conditions of persona tactical combat are simple.
One of the combatants is unconscious, dead, or escapes.
The goal of space vehicle combat is to gain control of the target ship, not destroy it.

There are four main victory conditions in space vehicle combat.
They all involve the inability of the defeated ship to function.
A space vehicle battle can be lost by: running out of fuel, a severely damaged gravity system, destruction of the exatmo drive, or loss of bridge control.

.*Victory Conditions*
* Loss of Fuel
* Loss of Gravity
* Loss of Exatmo Drive
* Loss of Bridge

NOTE: *Victory conditions are more like defeated conditions. Glory to the English language.*

The victory conditions indicate when the __space battle__ is over.
A space battle rarely destroys a space vehicle. 
Likely the ship's crew and cargo will be intact.

==== Loss of Fuel
Running out of fuel may be the least glamorous way to lose a battle.
Combat fuel burn is tremendous, and no fuel means no combat maneuvers. 
A ship out of fuel stops spinning and hurtles off in a predictable trajectory.
The predictable trajectory makes the vessel vulnerable to boarding, ramming and focused attacks. 
Inadequate fuel for combat does not threaten life support or onboard systems.
A fuel-depleted space vehicle may not be controlled by the attackers yet, but the exatmo battle is undoubtedly over.

==== Loss of Gravity
A space vehicle's gravity system is an essential part of the life support system.
The gravity system allows personas to enjoy normal gravity within the space vehicle.
The gravity system keeps the persona's feet or flippers comfortably on the deck of the space vessel.
While this may sound like a convenience maintaining constant gravity in combat is life-saving.

The sciency fiction exatmo vehicle combat system involves vessels flipping, twirling and banking using their exatmo drives.
These maneuvers would obliterate all life without a gravity system, and the ship would tear itself apart.
Doing a barrel roll at 500 million km/h is not compatible with physics, let alone life. 

Combat is over if the gravity system is functioning at less than 30%.
The space vehicle cannot use exatmo drives if the gravity system functions at less than 10%.

A ship out of gravity safely stops spinning and hurtles off in a predictable trajectory.
This predictable trajectory makes the vessel vulnerable to boarding, ramming and targeted attacks. 
Inadequate gravity for combat does not threaten life support or onboard systems.
The crippled space vehicle may not be controlled by the opposition yet, but the exatmo battle is undoubtedly over.

==== Loss of Exatmo Drive
If the drives are dead, the space vehicle is unable to engage in space combat.
In combat, the exatmo drives are potent units that swing the ship madly around, deflecting kinetic attacks, and aligning weapons.
If the exatmo drives are out of commission, the space vehicle has come second place in space combat.

==== Loss of Control of Bridge
The final pathway at the end of all exatmo vehicle combat is losing control of the bridge.
There are several ways to lose control of the bridge: surrendering the bridge, losing the bridge to personal combat or destroying the bridge during space combat.

== Combat Turn Cycle
Space combat is aggressive.
Every attack is happening as fast as possible.
Each turn has a cycle of attack, defend and counter-attack.
The first strike is the goal, and initiative is essential. 

The combat turn cycle goes from fastest to slowest attacks. 
ECM will always act before naval artillery.
Defences are automatically activated unless the player chooses not to defend.
Counter attacks are attacks that double as defences.
Counter attacks are not automatically activated and require a decision by the player.

Each space vehicle is randomly created and has a different weapon configuration.
The attack order only applies to attacks that the space vehicle has.
One space vehicle may only have ECM, while another may have ECM and bombs.
Naval artillery is very rare.
All space vehicles can ram or board. 
All of these attacks are possible in each combat turn.

include::ROOT:partial$CH38_Table_Attack_Defend_Counter_Attack.adoc[]

== Initiative
Initiative is only needed when both vessels have the same attack type.
For example, if both combatants have ECM, the pilots roll initiative to see which vehicle's ECM acts first.
If only one combatant has ECM, this pilot would automatically act first.

=== Initiative for Space Combat
.Init = 1d20 + Computer Level + Pilot Level
****
Init = 1d20 + computer 4 + pilot 3 = 1d20 +7 = 15 + 7 = 22
****

=== Example of Initiative
Spaceship One (SS One) has the attacks ECM, Ramming, and Artillery. 
Spaceship Two (SS Two) has the attacks Ramming, Artillery and Grenades. 

.*Example Attack Order and Initiative*
. SS One can use its ECM unanswered. No initiative roll. 
. Both vehicles have ramming, 
. Both vehicles have Ramming and initiative SS Two attacks with 2-Ram, SS One defends with 3-Artillery (used 1-ECM as an attack)
. SS One and SS Two want to attack with 3-Artillery initiative roll is required
. Neither ship is trying to 4-Board
. SS Two fires 5-Grenades as mini-missiles, SS One has no defense (used 1-ECM as an attack)

An ECM unit can be used defensively or offensively each turn. 
The player pilot must decide which. 
To do both offensive and defensive ECM, the space vehicle must have two ECM units. 

== Attacks
Attacks are a collection of electronic, kinetic, and energy weapons that one ship uses to control or damage another ship.
Some attacks work as defences as well.

.*List of Attacks*
. ECM
. Ramming
. Artillery
. Boarding
. Grenades
. Bombs
. Naval artillery

// attack rolls vs comp rolls vs pilot rolls

// need a list of attacks and what can assist them and what can defend against them.
// maybe a better attack defend counter cycle table

== ECM
ECM is the abbreviation for electronic countermeasures.
ECM is the battle for control over the electromagnetic spectrum.
In space vehicle combat, ECM is the battle for control over the electronics of the target ship.
Attack ECM can confuse the target ship's defences with false data, control an essential component of the target ship, or be used as defensive instead of attack.
The pilot must choose between Attack Assist, Control Attack or Defense for her ECM each turn.
An ECM attack unit is still an ECM unit and can be used to defend instead.
One unit cannot do both.

=== ECM Attack Assist
When ECM is being used to assist its own ship's attacks, it will attempt to deceive the target by creating inaccurate or false data for the target ship to deal with.
This may be done by making single attacks appear as multiple attacks, altering the apparent course of incoming attacks, or confusing the estimated arrival time of an attack.
All such falsified data will increase the chance of success of a ship's attack.

ECM assisted attack rolls receive a bonus of +150 attack per computer level.
Percent attacks receive a bonus of +3% of success per computer level.
Thus a space vehicle with a level 2 computer making a attack roll attack (missiles) assisted by ECM, would get +300 on the attack roll.
The same space vehicle would enjoy a bonus of +6% for success with percent attacks (ramming) when being assisted by ECM.

=== ECM Control Attack
ECM control is used to manipulate a target ship's onboard systems, play is far more interesting because player input is required.
The chance of successfully controlling another ship's systems is 8% per level of the attacking spacecraft's computer.
If an ECM Control Attack should fail, it cannot be re-attempted during this combat session.
At first glance, the range of effects of the ECM Control Attacks seems quite limited, in reality, the number of targets is virtually limitless.
If an attempt to reduce drive effectiveness fails, the ECM Control Attack can try to alter the ship's gravity in the next turn.
The pilot can choose to use control attacks until something clicks.

=== ECM Computer Roll
.chance = 100 - 8% per computer level
****
Level 6 computer. (100 - 48) = 52. Player must roll 52 or higher. 
****

If control ECM is successful, the targeted component is reduced in capacity.
This effect will last until the targeted ship's own ECM breaks the attack ECM, the target ship uses its special drives, or the attacking ship ceases its attack.
An ECM unit is completely occupied while controlling another ship's components.
Some of the most common ECM controls are described here, however, the referee should be prepared to improvise.
When improvising, the ref should remember that a successful ECM attack will not destroy a ship, it merely reduces a particular component's effectiveness, and increases the ship's vulnerability to other attacks.

include::ROOT:partial$CH38_Table_Example_ECM_Control_Attacks.adoc[]

== Ramming
Ramming is a method of boarding a target space vehicle where all caution has been thrown to the solar wind.
A space cruiser capable of ramming will have a specialized airlock which can attach to any part of the target ship's hull.
Once attached the invading party may breach the hull, airlock, or whatever to gain entry into the ship.
In procedure, ramming is similar to boarding except that ramming is accompanied with lots of crunching and scraping noises.
Ramming, requires skill and brute force.

Ramming can be assisted by ECM. 
Using ECM as an attack assist for ramming gives +6 bonus per computer level on the Ramming Pilot Roll.
The same ECM cannot be used for attack and defense in the same turn.

=== Mutual Ramming
Why ever this would happen, who knows, but if either of the attacking ships is successful in ramming the other ship will automatically be successful.
If both ships fail their ramming attack, the dance will continue.

.*Ramming Checklist*
. Determine number of ram attempts
. Determine Ramming Pilot Roll
. Assess Damage Location on target.
. Extent of Damage to target vessel (max Major)
. Damage (one level less) to ramming vessel
.. Lash and board 0-3 (1d4-1) turns
.. Smash and run

=== Attempts
When a ship does not want to be rammed, it can make avoidance maneuvers using its exatmo drives and pilot skill.
If the below equation is positive, the attacking space vehicle gets that many attempts to ram.
If the result is negative.
The attacking ship gets one chance to ram, but subtracts negative number from the Percent Chance Attack.
So if the attackers drive, computer and pilot level were 7 and the defender's exatmo drives and pilot level were 11  the ramming ship would get 1 chance at 8% per computer level for success.
If the attacker's total was 11 and the target's total was 7 the attacker would get 4 chances to ram.
Only one attempt to ram can be made per turn.
And the number of attempts is the number allowed for that entire battle.

=== Number of Ram Attempts
.Attempts = (attacker drive + computer + pilot levels) - (defender drive + pilot levels)
****
If the value is zero or less, the attacker cannot ram the target vessel.
****

=== Chance of Ram Success
Basically, the ramming vessel's success depends on the attacker's computer level and pilot level.
A space vehicle with a level 3 computer and a level 2 pilot would have a 39% chance of a successful ram.

=== Ramming Pilot Roll
.success = 100 - (12% + pilot level) * computer level
****
Level 6 computer and level 3 pilot. 100 - (15 * 6) = 10. Player must roll 10 or higher to attach.
****

=== Smash or Lash
The players must decide whether they are smashing and running or lashing onto the rammed vessel.
Smashing is exactly what it sounds like. 
The attacker smashes the target ship and backs off like a demo derby near light speed.
Lashing involves attaching to the target ship and boarding through the breached hull. 

Ramming damages both the ramming and rammed vessels. 
Hull breach success is automatic and takes 0-3 (1d4-1) combat turns.
The Damage Location Roll also indicates where the attacking ship will breach the hull.
For example, if the ramming damage location the target ships drives, the boarding party will enter the ship at the drives.

== Artillery
The purpose of ship artillery is to damage the target ship so that it ceases to function.
This goal is achieved by penetrating the hull, and delivering the artillery's destructive force to the internal components of the ship.

Although artillery cannot be fired exatmo into the atmosphere, it can be used freely when the vessel is within an atmosphere.
Ship artillery has the same ranges, damages, and effects as the artillery it is modelled after.
The difference is in the amount of ammunition the fixed gun has access to.
Energy-based weapons can fire as long as the ship has fuel, and artillery requiring ammo will have 100 times the regular supply.

=== Hitting with artillery
Artillery requires a successful attack roll to damage it's target.
The artillery weapon must score a hit against the target spaceship's armour rating.
This means that the attacker must make a kilodie roll higher than her target's AR.
The target ship's armour rating, including hull strength and ECM, may prove impenetrable to many artillery attacks.

The attacking ship's computer level adjusts the artillery's attack roll.
A gunnery program will fire the artillery automatically, with a bonus of +50 per level of ship's computer.
If a skilled gunner persona is firing the artillery, there is a bonus of +100 attack per level of ship's computer.
The organic firing bonus is mostly due to the unpredictability of an organic life form firing a weapon.
This bonus only applies to skilled personas, because a ship's artillery cannot be fired without gunnery skill.

== Boarding
Boarding is congenial ramming.
Boarding lines up airlocks to prepare for a breach and boarding of the target vessel.
Boarding can only be used to force airlocks together while exatmo (exterior to atmosphere).
Once connected the attacking crew will breach the airlock of the target ship and then board.
This method of attack is used because it preserves the target space vehicle, hostages, cargo, and is a lot more fun.

.*Boarding Checklist*
. Determine number of board attempts
. Make Boarding Pilot Roll.
. Prepare to board

=== Mutual Boarding
If two ships are trying to board each other, they will be automatically successful.
Since the goal of both ships is to connect airlocks.
ECM will recognize that both ships want to connect to each other, and it will happen automatically.
Counter attacks such as mines or missiles may still be deployed.
If both ships are attempting to board each other but wish to connect via different airlocks, then the boarding attack is required.
For example a space vehicle with multiple airlocks may want to attach to another space vehicle with a specific airlock.
If the pilot wants a specific airlock then regular boarding attacks is required.

=== Attempts
When a ship does not want to be boarded, it can make avoidance maneuvers using its exatmo drives and pilot skill.
If the below equation is positive, the attacking space vehicle gets that many attempts to board.
If the result is negative, the attacking ship get's only one chance to board, but subtracts negative number from the percent chance attack.
So if the attacker's drive, computer and pilot level were 7 and the defender's drives and pilot level were 9  the boarding ship would get 1 chance at 2% per computer level for success.
If the attacker's total was 11 and the target's total was 7 the attacker would get 4 chances to board.
Only one attempt to ram can be made per turn.
And the number of attempts is the number allowed for that entire battle.

=== Number of Boarding Attempts
.Attempts = (attacker drive + computer + pilot levels) - (defender drive + pilot levels)
****
If the value is zero or less, the attacker cannot board the target vessel.
****

=== Chance per attempt
Basically the boarding vessel's chance of being successful is dependent on the attacker's computer level and pilot level.
A space vehicle with a level 3 computer and a level 2 pilot would have a 18% chance of a successful board.

=== Boarding Pilot Roll
.success = 100 - (4% + pilot level) * computer level
****
Level 6 computer and level 3 pilot. 100 - (7 * 6) = 58. Player must roll 58 or higher to attach.
****

=== Success
Even though boarding requires manual breaching of the airlock and good old personal combat (the lining,tit), the two airlocks require tactical maneuvering (exatmo on combat spin) by the ship's computer.
There is a 4% chance per level of computer of successfully docking with another ship.
Dice Dice are rolled against this chance by the player whose persona is the pilot.
A ship may attempt to board once each turn (30 units).

=== Once Connected
Once connected to the target ship, there are a few options.
The attacking vessel can stay docked, and the boarding party can work on opening the airlock.
If the target ship is still attempting to dislodge the attacker, combat fuel consumption must be maintained.
However, combat fuel consumption is the only requirement to remain attached.
Once a ship has been boarded, it cannot forcefully detach from its attacker.
The only recourse that the target ship has is to continue maneuvering at combat fuel consumption, and hope that the boarding ship runs out of fuel.
They would most likely give up long before that occurs.
Usually, a boarded ship will be resigned to its fate and open the airlock to avoid damage.
If the victim is being impolite, the the airlock may need to be breached.
Airlock breaching is left for the referee to run with her players.
It is recommended that mechanics and spies be more proficient at airlock opening than dumb old mercenaries.

== Grenades
In space vehicle combat grenades explosives delivered by either mini-missile or mini-mine.
The intent of the grenade is to explode against the hull in an attempt to damage the internal mechanisms of the ship.
A successful attack roll must be made against the space vehicle's armour rating to inflict damage.
This is in direct contrast to area of effect weapons in tactical inatmo combat.
If the attack roll is unsuccessful, the grenade detonates ineffectively and silently in space.

Grenade delivery systems have diminutive titles because they only deliver grenades. 
Proper missiles and mines deliver bombs.

=== Grenade Mini-Missiles
Mini-missiles are the more frequent of the two delivery types.
Mini-missiles are ineffective when they are fired at a fleeing spaceship whose exatmo drives are 3 or more levels higher than the exatmo drives of the attacking ship.
Even though a faster ship can outrun mini-missiles, they receive a chance attack if the faster ship is trying to board or ram the missile-firing ship.
A ship can launch 3 mini-missiles per level of computer at one once.
When used inatmo the mini-missiles cannot be outrun, and they can be used against any surface or atmospheric target.
Mini-missiles function inatmo or exatmo but they cannot survive the hazards of entering an atmosphere.

=== Grenade Mini-Mines
Mini-mines are grenades dumped in the path of starships hoping that they will explode for damage.
Grenades can be dumped in the path of a ship's orbit, dumped in the path of a pursuing ship, or jettisoned against the hull of a boarding or ramming ship.
Mini-mines are inactive mini-missiles, they do not chase targets, and they can only be dumped.
The mini-mines are still useful because ECM cannot affect them, they move too slow to be affected by shields, and they cannot be avoided unless they are visually detected.
The ability to detect the tiny camouflaged mini-mines requires a bizarre AWE (kilodie) roll.
Mini mines can be dumped at a rate of 5 mines per unit per level of computer.
Mini-mines, like mini-missiles, cannot survive the rigors of entry into an atmosphere but can be used to bomb targets inatmo.

== Bombs
Bombs are lethal attack weapons.
Bombs need only explode near the ship's hull to inflict damage to the contents within.
The number and type of bomb is determined when the space vehicle is created.
Bombs are delivered by either missiles or mines.

A bomb is guaranteed to damage a target with a successful attack roll.
Every bomb gets a second chance to damage a vessel just by getting close enough. 
If the raw roll of a missile or mine is better than 500, the target is still damaged.
Dangerous destructive devices.

=== Bomb Missile
A bomb missile is also called a naval missile.
Missiles can be fired at any detectable space vehicle.
An attacking ship can control one missile per level of ship's computer.
No vessel can outrun a missile.
This does not mean that a missile automatically hits it's target.
An attack roll is still required.

Even though a missile will eventually catch up with its target, there is some time before impact.
The time to impact is determined by the exatmo drives of the battling space vehicles.
If the attacking vessel has a higher drive level than the target ship, the missile arrives in that turn.
If the target space vehicle's exatmo drive level is higher than the attacker, there is a "calc" for that.

=== Turns to Missile Impact
.Turns = Target's Exatmo Drive Level - Attacker's Exatmo Drive Level
****
Target's drive level is 8 and the attacker's drive is 4. The target has 4 turns to brace for impact.
****

Missiles cannot function inatmo.
A target vessel may escape a missile by hiding inatmo or to jumping with the special drives.

=== Bomb Mine
A bomb mine is also called a naval mine.
A ship may dump one mine per level of ship's computer per unit.
The mines have no drive components, and are discarded into the flight paths of target starships.
Such mines may only be used against orbiting, pursuing, boarding, ramming, or unaware targets.
This bomb mine delivery method has some advantages over its missile counterpart.
First, the mines are virtually undetectable, and defensive ECM cannot be used against them.
A mine can only be visually detected by an improbable (d100) AWE attribute roll.
Mines are hardy enough to be deployed in the atmosphere or in orbit to be used as fierce surface attack weapons.

== Naval Artillery
Naval artillery has only one purpose in mind, to destroy the target ship.
Naval artillery is not used to soften or assist in the taking over of the target vessel.
The sheer force of the weapon accomplishes the destruction.
One use of naval artillery exhausts a whole day's worth of fuel.
The naval artillery cannot be idly used; it requires a gunnery program, and two gunners.
Without this complement, the ship cannot fire its naval artillery.

Naval artillery is more deadly than the regular deadly artillery.
Naval artillery inflicts 3 times the damage and has 100 times the range.
Naval artillery can only be fired exatmo.

Naval artillery is guaranteed to a direct hit with a successful attack roll.
A direct hit by naval artillery inflicts 2 damage rolls.
If the players are using the damage bonus system, each ship location will likely be destroyed.
If the naval artillery scores a direct hit, the attack cannot be absorbed by the target's shields.

Naval artillery that does not score a direct hit can still inflict near-miss damage.
A near miss with naval artillery is any raw attack roll that is higher than 600. 
A near miss only scores 1 damage roll.
Near miss damage rolls can be absorbed by the target's shields.

== Defences
A space vehicle's defences both defend against attacks, and the hostile environment of outer space.
Defences are a mix of combat defences and essential exatmo life support protections

.*Defences*
. Life Support
. Gravity Control
. Hull
. Armour
. ECM
. Shields
. Guns
. Actives

== Life Support
Life support maintains a comfortable environment for the organic, and delicate inorganic, contents of the ship.
The life support system is intimately integrated with the hull and gravity system of the vessel.
Life support is distributed, self contained, and is impossible to disable.
The ship's computer depends on an intact life support system.
Life support does not malfunction unless it is directly damaged in combat.

Control ECM attacks can manipulate life support and make the inhabitants uncomfortable.
Control ECM cannot turn off life support or threaten the well being of the ship's contents.

include::ROOT:partial$CH38_Table_Life_Support_Chain.adoc[]

Destroying life support is rarely the goal of space vehicle combat. 
Space vehicles are too valuable to destroy utterly.
A loss of life support destroys all life on the ship, and more importantly, the ship's computer.
Life support has onion layer protection and and the outer layers must be destroyed in order.

If the life support system is destroyed in one attack, the ship will suffer complete decompression.
Decompression destroys all organic materials (personas), and delicate inorganic devices (computers, robots, toys).
A partially damaged life support system will maintain a fraction of atmosphere proportional to its amount of damage.
A fully operational life support system taking major damage would only have 60% of the atmosphere that it previously had.
This thin atmosphere will make it more difficult to work, and stay conscious.

== Gravity
The gravity system is a crucial component of the life support system.
The gravity system is intimately integrated with the hull and life support system of the vessel.
Life support is distributed, self contained, and is impossible to disable.
Gravity is usually maintained at a constant attraction of 1g.
This includes walkways, workspaces, cargo holds, cabins, and exterior hull etc.
This is controlled by the ship's computer, and is uniform throughout the whole ship.
The gravity can be adjusted between 0.5  and 1.5 gravities.

include::ROOT:partial$CH38_Table_Life_Support_Chain.adoc[]

The gravity system maintains a comfortable working gravity regardless of whether the ship is making combat maneuvers near light speed, or banking inatmo at Mach 8.
Almost any maneuver performed by a space vehicle would destroy all organic materials (personas), and destroy all delicate inorganic devices (computers, robots, toys) without the gravity system.

NOTE: *The gravity system is a sciency fiction mechanism designed for role-playing fun.*

The gravity system can be manipulated by control attack ECM.
However control ECM cannot turn off gravity or make life dangerous for the contents of the vessel.
Control ECM attacks are an irritation manipulating the gravity to confound, not kill, the crew.

.*Damage to Gravity System*
. Gravity at <30% No combat
. Gravity at <10% No exatmo or inatmo movement 
. Gravity at <1% No gravity
. Life Support vulnerable

There are three defining stages of failure for the gravity system.
The gravity system is disabled when it is reduced to <30% function.
The space vehicle can no longer protect it's contents from the gravitational forces of combat.
When gravity is disabled, the vessel must drop out of combat.
This is a victory condition.

If gravity is reduced to <10%, the system is disabled.
The vehicle can no longer maneuver using it's exatmo or inatmo drives. 
A ship could cross into an atmosphere, but it could only beach itself planetside.

== Armour Rating aka Hull
The hull supplies the space vehicle's armour rating used in combat.
When space vehicles are created, they are assigned an armour rating as part of their hull.
The hull and armour rating have an intimate relationship.
In combat Armour Rating can be reduced by absorbing or being damaged.
The space vehicle's armour rating must be reduced to 400 before the hull is damaged.

The hull is a crucial component of the life support system.
The hull is intimately integrated with the gravity and life support systems of the vessel.
Life support is distributed, self contained, and is impossible to disable.

include::ROOT:partial$CH38_Table_Life_Support_Chain.adoc[]

The hull is the containment and physical defence system of the ship.
The hull also defends against both hostile environments and attacks.
The star cruiser's hull is the last line of defence.

NOTE: *The Hull AR protects the Hull. Once the Hull AR is reduced to 420, the Hull takes direct damage rolls.*

Defensive ECM can increase the space vehicle's AR against attack rolls.
The increase in AR is a transient electronic deception and does not actually alter the Hull AR.

== ECM
Electronic countermeasures (ECM) deceptively manipulate the electromagnetic spectrum to defend the ship.
The more powerful the ship's computer level, the more effective the electronic countermeasures.
If any personas have skill in ECM, they can add that skill level to the computer level used for the ECM.
So if a mechanic has ECM level 2 and the computer level is 3, then the ECM will function as a level 5.

ECM is an accessory unit of the ship's computer. 
It can be utilized as attack ECM or defense ECM.
One ECM unit cannot do both in the same combat turn.
If the space vehicle has only 1 ECM unit, the players must decide how to use it each combat turn.

=== ECM AR Boost
Most often defensive ECM will be used to make the ship harder to attack.
This is done by creating false images of velocity, trajectory, rotation, size, etc.
All of this electronic tom-foolery results in a +200 bonus to the ship's armour rating per level of computer.

=== ECM Break Control
Defensive ECM is especially important when the ship is under attack from control ECM.
Defensive ECM can identify whether a ship's component is actually malfunctioning, or whether it is malfunctioning due to control ECM.
Defensive ECM will use the ship's computer to re-route communications channels and alter security, to defend against control ECM attacks.

For example, if a control ECM attack had reduced the effectiveness of the ship's drives defensive ECM could be used to break this control.
This would restore the drives to their normal power level.
The chance of success is 15% per computer level.

=== ECM Break Control Roll
.success = 100 - 15 * (computer + skill level)
****
Level 3 computer and level 2 engineer. 100 - 75 = 25. Player must roll 25 or higher to break control.
****

=== ECM Camouflage
Defensive ECM can be used to hide the ship electromagnetically.
ECM will make the ship blend in with the background, or appear as some anomaly other than a spaceship.
This aspect of ECM will not hide the ship from a visual inspection, but it will deceive another ship's sensors.

=== ECM Camouflage Roll
.success = 100 - 9 * (computer + skill level)
****
Level 3 computer and level 2 engineer. 100 - 45 = 55. Player must roll 55 or higher to hide.
****

=== Damaged ECM
Damaged ECM is reduced by the percentage indicated on the Extent of Damage table.
For example, ECM at 50% efficiency could only offer +100 per computer level to the ship's AR.

== Shields
The shields protect the hull AR and hull from energy and kinetic attacks.
A defensive shield may be a force field or a structural mechanism. 
Both mechanisms work by distributing the damaging force across the entire hull.
This faux scientific diffusion effectively dampers the damage.
The shields have an active mode that the players turn on to thwart intentional damage.
Shields also have a passive mode, and when present, they are part of the life support system.

Shields require energy to distribute attack damage and are powered directly by the exatmo drives.
The shields can absorb 100 HPS of damage for every level of exatmo drive.
For example, a ship with a level 4 drive could absorb 400 HPS of damage.
If an an attacker rolls 429 HPS of damage the space vehicle would only take 29 HPS of damage.

The shields absorb damage from mini-missiles, naval-missiles, artillery, and naval artillery attacks.
Shields have no effect on ECM, boarding, ramming, mini-mines or naval-mines. 

// is there a conflict between direct hit and near-miss naval artillery.

Active shield use doubles fuel consumption. 
Shields usage is optional.
Players may choose to turn off their shields to conserve fuel.

Passive shielding becomes part of the life support system.
The shields must be disabled before the Hull AR can be damaged.
This passive protection does not use any extra fuel.

include::ROOT:partial$CH38_Table_Life_Support_Chain.adoc[]

== Guns
A gun is a purely defensive element in space vehicle combat.
A gun does not sound like a defensive tool, but occasionally the best defence is a good offence.
Guns on space vehicles are anti-personnel air lock defense weapons.
In ship to ship combat, a gun is an ineffectual weapon.
However to prevent boarding or airlock intrusion a mounted gun can be very effective.

.*Airlock Defensive Guns*
* operate inside and outside of airlock
** but not not simultaneously
* operate inatmo or exatmo
* can be automated like a turret
** gunnery software or ship's computer
* Can be controlled by personas
** mercenaries do this best
* has unlimited ammo to defend against boarding
** ammo can be limited if weapon being abused
* has an AR equal to the ship's hull
** including ECM and shields
* damaged by Hull AR damage or airlock damage location

== Active Defenses
Active defences are used against incoming weapons.
Active defences are sometimes called actives.
They can eject missiles, shrapnel, energy blasts, lazer matrices, or crystalline discharges. 
The goal is to dissipate, prematurely detonate, or destroy incoming attacks.
All active defences function equally.
Active defences can be used against grenades, bombs, or artillery.
Actives have no effect against boarding, ramming, ECM, or naval artillery.

=== Active Defence Roll
.success = 100 - 9 * (computer + exatmo drive + skill levels)
****
Level 5 computer and level 3 drives and no gunner. 100 - 56 = 44. The player must roll 44 or higher to block the attack.
****

A ship can attempt to thwart 1 attack per level of computer per turn.
A ship will have 100 disposable charges for every 50 tonnes of ship.

.*Notes about active defences*
* Active defences are not part of the Life Support Onion
* Active defences are automated
** Gunnery skilled personas can help
* Active defences work inatmo and exatmo
* Actives cannot be weaponized

== Counters
What are counters? How do they work? Why do they exist?





== Space Vehicle Damage
When an attack is successful, either by rolling over the target ship's AR (attack roll attack), or rolling under a designated percentage (percent chance attack), the target ship has been damaged.
Although the space vehicles do not have hit points, the HPS damage rolled for an attack is important.
Whenever a ship is damaged, the successful attacker rolls both a hit location, and extent of damage.
The hit location determines what system of the ship has been damaged.
The hit location is determined randomly, just like persona hit location, on Table 38.6: Space Vehicle Hit Location.

.*Breaking Down Space Ship Breaking*
. Successful attack, pilot or comp roll
. Damage Location
. Damage Severity
. Damage Effect

Damage to the interior of the ship does not necessarily indicate hull damage.
Power surges, from one point to another, can also account for random damage locations.

Keep in mind the Life Support Protective Onion when inflicting damage on space vehicles.

include::ROOT:partial$CH38_Table_Life_Support_Chain.adoc[]

== Damage Location
Damage location indicates which of the space vehicle's systems is targeted by an attack.
Damage location in space vehicle combat is completely random.
The randomness results due to space vehicle diversity, chaos of combat maneuvers, and mystery juice.
This damage system is similar damage location for robots, and vehicles.
The damage location must be rolled for every successful attack.

The damage location is not the same as a hit location. 
Power surges, electric disruptions, shields, and ship structure send damage anywhere in the vehicle.
Even a space vehicle that is immobilized cannot have damage locations chosen.
Automatic hitting does not affect damage location.

include::ROOT:partial$CH38_Table_Space_Vehicle_Damage_Location.adoc[]

=== Missing Damage Locations
A space vehicle may not have the damage location rolled.
The damage location may have never existed on the space vehicle, or it has been destroyed.
There are several approaches to missing damage locations.
The player can simply roll again to find a different damage location. 
The referee can move the damage location within the general damage location.
For example, a hit on the special drives is moved to the exatmo drives with the primary location drives.
In the primary section defences they are ordered in priority, and the referee could just move down the list.

In the case of a damage location that has been destroyed, the attack may fall useless onto space rubble.
A damage location is considered totally destroyed when it's function is <1%. 
At this point, it doesn't even exist anymore. 

== Damage Extent
The Extent of Damage Table is used to determine how badly a system has been damaged by a successful attack.
Space vehicle weapons inflict damage in HPS, but space vehicles do not have hit points.
So damage is measured by a decrease in function of the location.
The extent of damage roll usually reduces the performance levels of onboard equipment. 
If an exatmo drive is reduced by 50% functionality, the space vehicle loses half it's speed and range. 
If the exatmo drive is damage by 50% again, the new functionality would be 25% of fully operational. 
For example, an exatmo drive level of 8 would be reduced to 4 by 50% damage and then 2 by another 50% damage.

include::ROOT:partial$CH38_Table_Extent_of_Space_Vehicle_Damage.adoc[]

=== Damage Adjustments
The extent of damage roll is increased by 1 percentage point for every hit point of damage.
So an attack inflicting 30 HPS of damage would add 30 to its extent of damage roll.
When using this damage adjuster space weapons will usually destroy whatever they hit.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

If the referee and players find that this extent of damage adjustment is destroying their space vehicles too quickly then modify it to have more fun.
One could eliminate the HPS Extent of Damage modification altogether.
One could have the vessel's AR to reduce the extent of damage.
If a rule gets in the way of having fun, then change it.

=== Damaged Systems
A space vehicle system is disabled once its performance is reduced to 10%.
From a practical standpoint, the mechanism may become useless long before it reaches 10%.
The effects of a damaged system are detailed below.

include::ROOT:partial$CH38_Table_Extent_Damage_Descriptor.adoc[]

==== Cumulative Destruction
The damaging effects of successful attacks are cumulative.
A space vehicle system can become disabled over several attacks.
A system receiving major damage (60% performance) twice in a row it's level of function would be 36%.
A further critical damage (30% performance) would reduce the part to 11% of its previous performance.
At this point even trivial damage (90% performance) would disable the mechanism.

.*Cumulative Destruction - round down*
. Undamaged 100% function
. Major Damage 60% function
. Major Damage 36% function
. Critical Damage 10% function
. Trivial Damage 9% function - disabled

==== Instantaneous Destruction
If a system  is destroyed in a single attack (<1% previous performance), the device has been damaged beyond repair.
The effects of instantaneous destruction are cataclysmic.
A destroyed hull would explosively decompress, a destroyed drive will melt down, fuel could explode, etc.
There is no chance for repair, and a replacement system will be required.

== Hull Damage
The hull is an integral component of the life support and gravity systems.
The hull helps contain the atmosphere generated by the life support system.
The hull also acts as the substrate for the gravity system.
Hull, life support and gravity are intimately integrated

=== Hull as Armour
The hull cannot be damaged before the ship's Armour (Hull AR) has been disabled.
The AR must be reduced to 400 before the hull system can be damaged.
The referee can move hits on the hull damage locations to Hull AR, or re-roll the damage location.

All initial damage locations on Hull are directed at the Hull AR until the Hull AR <400.
The Hull AR cannot drop below 400, and that is it's destroyed level of function.

include::ROOT:partial$CH38_Table_Life_Support_Chain.adoc[]

=== Hull Compromise
Hull only becomes a damage location once the Hull AR (armour) is reduced to 400.
The hull damages as per any system from this point on.
The hull is  when it's level of function is reduced to less than 10%.
The hull is destroyed when it's level of function is reduced to <1%.

Hull damage directly affects the ship system it is protecting.
This is determined by rolling on the damage location again.
For example, the hull containing the exatmo drives could become compromised.

A disabled hull (<10%) represents a manageable escape of it's inatmo contents.
A destroyed hull (<1%) represents an unmanageable escape of it's inatmo contents.
Both of these hull compromises allow for usual evacuation procedures for the area.
Instantaneous destruction (<1% in one attack) represents explosive decompression.

The ship can partition off a damaged location using it's automated bulkheads.
Open concept space vehicles are not recommended.

The location is considered off-limits and disabled until the leak hull can be repaired.
A destroyed hull cannot be repaired during battle.
Once the leak is repaired, the life support and gravity systems will replenish the location.

== Drive Damage
Drives are the whole point of the space vehicle.
The higher the drive level the better the space vehicle.
Drive levels are reduced by the extent of damage inflicted.
If a level 10 exatmo takes major damage (40% reduction) it becomes a level 6 drive.
This is damage is cumulative. 

=== Inatmo Drive Damage
Reduce the drive level of the in atmosphere drive by the percentage indicated.
This system is disabled when it's level of function is reduced to less than 10%.
A ship with a disabled inatmo drive cannot maneuver in the atmosphere of a planet.
The pilot may beach the ship planetside, or remain in orbit until repaired.

=== Exatmo Drive Damage
A damaged exatmo drive will have its drive level reduced by the percentage indicated.
Exatmo drives are disabled when their function is <10%.
The exatmo drives are the ship's combat drives.
Without exatmo drives it cannot maintain combat spin.
When disabled the ship drops out of combat and start floating towards the nearest star.
Disabling the exatmo drives is a victory condition.

Exatmo drives also power defence shields, active defences, and boarding evasion.
Damage to the exatmo drives also impairs these ancillary functions.
Exatmo drives are not affected by exatmo, however personas running the drives can be.

=== Special Drive Damage
Reduce the drive level of the special drive by the percentage indicated.
A disabled special drive keeps the space vehicle from making any long voyages.
Special drives are so delicate they resemble a life form. 
Exatmo is very unhealthy for a special drive.

== Fuel Damage
Damage to the fuel system represents the drive's inability to access the necessary fuel to function.
Disabling fuel systems can disable a particular drive or all drives. 
Sometimes the fuel itself is destroyed or lost in space.
Other times the fuel is still present, but cannot be accessed.
During combat, there is no difference.
If fuel access is disable or destroyed, this is a victory condition.

=== Inatmo, Exatmo, Special Fuel Damage
This represents damage to the specific fuel system described. 
So if the Inatmo drive is damaged, the exatmo and special drives are unaffected.
The damage could indicate fuel released into space, batteries destroyed or power plants malfunctions.

If a specific fuel system is disabled or destroyed then that particular __drive__ is disabled.
The drive is not damaged, but it can no longer work without fuel.
In the case of exatmo drives this is a victory condition.

If the 10 months of inatmo fuel takes major damage (40%), the storage is reduced to 6 months.
This limits the special drive to 6 jumps.
If the 10 months of exatmo fuel takes major damage (40%), the storage is reduced to 6 months.
Exatmo fuel is burned at the rate of one week per turn of space vehicle combat.
So the space vehicle can now only fuel 24 turns of space combat before dropping out.

=== Amount Damage
The space vehicle's total fuel storage is damaged.
All three fuel systems are reduced by the extent of damage.
The global fuel loss is non-denominational.
If the Fuel Amount is damaged, reduced by 40% inatmo, exatmo and special drives are all reduced.

Fuel Amount damage is cumulative. 
If the exatmo fuel were already damaged to 40% of function a Fuel Amount damage would worsen this.
A Fuel Amount damage of 40% would reduce the exatmo fuel supply to 16%. 
This severely reduces how long the space vehicle can remain in combat.

=== Consumption Damage
This keeps the space vehicle from accessing fuel.
All fuel systems drop by the extent of damage, but no fuel is lost.
One assumes that after combat the consumption system could be repaired and the fuel used later.

Fuel Consumption damage is cumulative. 
If the exatmo fuel were already damaged to 40% of function a Fuel Consumption damage would worsen this.
A Fuel Consumption damage of 40% would reduce the exatmo fuel supply to 16%. 
This severely reduces how long the space vehicle can remain in combat.

== Computer Damage
The computer is the space vehicle.
It is the most important and second most delicate system on the space vehicle.
Computer damage impairs nearly every function of the space vehicle.
If a level 6 computer suffers 40% damage, it is reduced to a level 2 computer.
Every other system that depends on the ship's computer drops in function.
ECM, boarding, defences, ramming, targeting are all impaired. 

A disabled ship's computer puts everything into a non-functional hibernation state. 
Persona's may try to manually operate a ship with a disabled computer.
A destroyed ship's computer leads to an immobilized hulk drifting towards the nearest star.

The computer is not part of the life support onion.
Gravity and life support remain operational in the face of a disabled or destroyed ship's computer.

== Computer Level Damage
This damage is not necessarily a direct hit to the ship's computer.
The damage could be delivered to the computer via a power surge or a conducted concussion..
Reduction of a ship's computer is most devastating as it affects the success of all attacks and defences.

=== Robot Control Damage
The ship's robots cease to function or follow the computer's commands.
Lose control of robots by percentage indicated.
This does not damage the robot, only the ship's control over the robot.
Robots may perform gunnery skills, or veterinarian care, at a reduced skill level.
If robot control is disabled or destroyed the robots may stop functioning all together.
It would be more fun the robots acquired free will with their new found freedom.
Robot self awareness could range from irritating behaviours to well deserved robot mutiny.

=== Software Damage
Specialized ship's software is reduced by the amount indicated in the extent of damage.
This is not just programming data, but damage to essential peripherals and sensors that run software.
Software damage does not affect computer level or ECM.
Only the extra software packages are damaged.
For example, crew replacement software damage may remove the ship's galley and cook.
The software packages can be reduced in effectiveness or simply disabled.
Players should be able to choose which software packages are lost.
They may wish to preserve astrogation or gunnery over the entertainment system.

== Cargo Damage
Cargo hold and any elements related to cargo are damaged.
This includes storage capacity, contents, airlocks, cargo locks and more.
The function of these components is reduced by the indicated decrease in function.
Any damage delivered to the system would also be delivered the contents and personas within it.

For example, extent of damage is major (decrease by 40%) andand includes 42 HPS in damage. 
An airlock may only be able to open to 60% of the previous opening.
All personas in the cargo area would take 42 HPS in damage. 
The value of the Profulcinating Hygromodulators (TM) would be reduced to 60% of previous. 

== Crew Damage
Crew's quarters, and all crew presently within it.
This is the expedition killer of space vehicle combat.
Area of effect damage will also be delivered to any personas in the crew area.

If the crew quarters sustains damage, the amount of space will be reduced.
Also crew amenities like food production, toilets, and entertainment unit will be damaged.
Any damage delivered by the attack will be delivered to the personas as well. 

== Defences
Damage to defences reduces the effectiveness of the defensive system by the percentage indicated.
Life support, gravity, and hull are integrated in the Life Support Onion.

=== Life Support Damage
A space ship's life support cannot be damaged before the other protective layers of the onion are destroyed.
This is the reason that life support does not appear on the Damage Location table.

include::ROOT:partial$CH38_Table_Life_Support_Chain.adoc[]

=== Gravity Damage
Gravity cannot be damaged unless the ship's hull is disabled.
A damage location on the gravity system should be redirected to the highest level of the life support onion.
Once the Hull AR and Hull are disabled, the gravity system can be damaged.
The effectiveness of gravity is reduced by the percentage indicated by the extent of damage roll.
Ineffective gravity can lead to space sickness, and difficulty performing tasks.
Reducing the gravity system to less than 30% forces the ship to drop out of exatmo combat.
Losing gravity is a victory condition.

=== Armour Damage
Armour and hull are intimately integrated and are part of the life support onion.
If the space vehicle has shields, they must be disabled (<10%) before armour can be damaged.
Armour damage specifically reduces the Hull AR of the space vehicle.

NOTE: *Hull AR, Armour, and Armour Rating are interchangeable and separate from Hull.*

Armour Rating is an amalgam of many factors. 
Structurally it includes hull strength, combat hardening, and combat alterations.
Tactically is includes the ship's computer and drives.
Architecturally a combat-ready hull is different from a non-combat hull.

The Hull AR is reduced by the percent amount indicated by the extent of damage.
This Hull AR cannot be reduced below 400.
When the Hull AR is reduced to 400, it is considered destroyed, and the Hull is vulnerable to damage.

==== Calculating Armour Damage
Sadly there are two ways to calculate the extent of damage to the armour rating.
Using the Hull AR of 800 both examples follow.
The simple method is to multiply 800 times 60% and reduce the new Armour Rating (AR) to 480.
The lowest a space vehicle's armour rating can get is 400.

The complex method is to subtract 400 from the Armour Rating, and multiply the result by 60%.
This result is added to the minimum Armour Rating of 400.
So a vessel with an Armour Rating of 800 and major damage would have a new AR of 640.
Destroyed armour is reduced to an armour rating of 400.

=== Defensive ECM Damage
Defensive ECM becomes reduced by the percentage indicated by the extent of damage.
ECM is a bit more resilient than other space vehicle systems.
Damaged defensive ECM can still function fully as attack ECM.
If the space vessel has two ECM systems the attack ECM can replace the damaged defensive ECM, and the Attack ECM can be switched to Defensive ECM.
So the only way to damage Defensive ECM is to damage each of the space vehicle's Defensive ECM.

=== Shield Damage 
The shields are reduced by the percentage indicated on the extent of damage roll.
Shields are immune to damage bonuses on the Extent of Damage Table.
So an attack that does 50 HPS Damage would increase the Extent of Damage roll by 50.
Shields are not affected by this extent of damage bonus.
If a shield could absorb 400 HPS damage and has sustained major damage (60%), it would only be able to absorb 240 HPS per attack until repaired.
The shield is disabled at <10% of capacity and attacks on the shield move to the Hull AR.

=== Gun Damage
This is the airlock defence gun.
The gun will have it's range and HPS damage reduced by the extent of damage indicated.
So an airlock gun that sustained major damage (60%) would have it's range reduced by 60% and each damage attack would be reduced by 60%.
So if the gun used to fire 100 hexes outside the airlock, it would be reduced to 60 hexes, and every damage roll would be multiplied by 0.6.
A disabled gun stops working.

=== Active Damage
Active defences can look after themselves.
The active defence will get one chance to stop an attack from damaging the active defence system.
This active self defence is offered regardless of recent active defence activity.
Depleted active defences cannot defend themselves.
The active defence has its effectiveness reduced by the percentage indicated by the extent of damage.

=== Attack ECM Damage
Attack ECM is reduced by the percentage indicated by the extent of damage.
ECM is a bit more resilient than other space vehicle systems.
Damaged attack ECM can still function fully as defensive ECM.
If the space vessel has two ECM systems, the defensive ECM can replace the damaged attack ECM, and the defensive ECM can be switched to attack ECM.
So the only way to damage attack ECM is to damage each of the space vehicle's ECM systems.

=== Ramming Damage
The chance of ramming is reduced by the percentage indicated by the extent of damage.
The physical plant, sensors, and machinery of ramming become damaged.

Calculating this reduction in ramming effectiveness is a pain in the butt.
The player must make a successful pilot roll for a successful ramming attack.
Does one reduce the player's die roll by the extent of damage?
Therefore reducing the chance of a successful ramming attack.
Does one increase the value that the player needs to beat?
Since ramming is such a blunt instrument, this referee prefers to ignore the graduated drop.
Ramming is either working, or disabled. 

If the Ramming system is disabled this space vehicle may no longer ram.
A space vehicle with disabled ramming capacity may still use the Boarding attack.

=== Artillery Damage
The artillery will have it's range and HPS damage reduced by the extent of damage indicated.
An artillery system suffering major damage (40% reduction) would be reduced to 60% effectiveness.
The artillery's range would be reduced from 500 to 300 hexes.
The artillery's area of effect had a radius would be reduced from 20 to 12 hexes.
Every damage roll would be multiplied by 0.6.

Disabled artillery stops working.
Instantaneously destroyed (reduced to <1% in one attack) artillery may explode inside the space vehicle
This should be determined by Sphincter Dice.
Artillery that explodes inside the ship delivers one location damage roll to the ship.

=== Boarding Damage
The chance of boarding is reduced by the percentage indicated by the extent of damage.
The physical plant, sensors, and machinery of boarding are damaged by the attack.

Calculating the reduction in boarding effectiveness is a pain in the butt.
The player must make a successful pilot roll for a successful boarding attack.
Does one reduce the player's die roll by the extent of damage?
Does one increase the value that the player needs to beat?
Often it is easier to just accept boarding is either operational or disabled. 

If the Boarding system is disabled, this space vehicle may no longer board.
A space vehicle with disabled boarding capacity may still use the Ramming attack.

=== Grenades Damage
The number of grenade attacks is reduced by the amount indicated by the extent of damage.
This reduction in function impacts both mini-missiles and mini-mines.
The damage impairs the guidance systems and connectivity to the ship's computer.

The number of mini-missiles and mini-mines deployable per turn is reduced. 
For example, a grenade system reduced to 60% could only drop 6 mini-mines instead of 10.

If the grenade system becomes disabled, no more grenades can be launched.
If the grenade system is instantaneously destroyed there is a chance of accidental detonation.
The sphincter dice are consulted.
An accidental detonation results in one damage location roll on the space vehicle.

=== Bombs Damage
The number of bomb and attacks and their effectiveness is indication by the extent of damage.
The reduction in effectiveness impacts both naval-missiles, and naval-mines.
The damage impairs the guidance systems and connectivity to the ship's computer.

The bomb delivery system is hardened for combat and is difficult to destroy.
There are no damage bonuses awarded on the Extent of Damage Table for bomb delivery system.

The number of naval-missiles and naval-mines deployable per turn is reduced. 
For example, a bomb system reduced to 60% could only drop 6 naval-mines instead of 10.
If the players desire, the effectiveness of the bomb itself can be reduced.
The bomb's area of effect and damage delivered could be reduced by the effectiveness percentage.

The bomb system is disabled at <10% effectiveness and can no longer deploy bombs
If the bomb system suffers instantaneous destruction, there may be accidental detonation.
A Sphincter Dice check will determine if a bomb has a damage location roll on it's own vessel

=== Naval Artillery Damage
The naval artillery will have it's range and HPS damage reduced by the extent of damage indicated.
An naval artillery system suffering major damage (40% reduction) would be reduced to 60% effectiveness.
The naval artillery's range would be reduced from 500 to 300 km.
The naval artillery's area of effect had a radius would be reduced from 500 to 300 hexes.
Every damage roll would be multiplied by 0.6.

The naval artillery system is hardened for combat and is difficult to destroy.
There are no damage bonuses awarded on the Extent of Damage Table for naval artillery.

Disabled naval artillery stops working.
Instantaneously destroyed naval artillery may explode inside the space vehicle.
This should be determined by Sphincter Dice.
Detonated naval artillery will act as if the space vehicle had shot itself once.

=== Ref's Own Table
The referee can use this opportunity to infuse drama and excitement into the campaign.
It is generally considered bad form to annihilate an expedition using the ref's own table.
Subjecting the personas to comedic or dramatic challenges that lead to their demise is fair game.

:art: police_space_craft.png
:width: 250px
:snark: Please have your driver's license ready.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of spaceship with police written in reverse on bow.
S
include::ROOT:partial$articulate.adoc[]

== Personas and Damage
Exatmo space vehicle combat is lethal.
Personas are fleas perched on battling elephants that can be squashed at any moment.
Players must be aware that personas can be killed in an instant during space vehicle combat.
Any personas located in damaged locations will certainly feel the ship's pain as well.
Minor damage to the space vehicle may be lethal to the anthros, aliens and robots housed in that damage location.
If a persona is in the cargo hold when it is damaged, they will take area of effect damage.
If a mechanic is working on the drives, they could be damaged by a hit to the drives.

Hull penetration is not the cause of the persona damage.
Damaging forces can be communicated into the damage location by shock waves, debris, and energy leaks. 
Most persona damage is delivered when they throw themselves around when the camera shakes.

Damage from a bomb or naval artillery will certainly annihilate any persona caught in the hit location.
A direct hit from naval artillery to the crew's quarters would end up in every persona dead.

*Persona Damage = Attack HPS Damage minus  Hull AR divided by 10*

=== Persona Damage Mitigation by Hull Armour
.HPS Damage = Attack HPS - (Hull AR / 10)
****
110 HPS of damage against a Hull AR of 800 would deliver 30 HPS of damage to personas.
****

== Damage Reports
The ship's computer will general damage reports about the space vehicle's system.
For a true combat damage report, the ship must have defensive ECM or a specialized program.
ECM attacks can deceive a ship's computer to give false damage reports.
Without ECM or damage reporting software personas may be left figuring out system damage themselves.
They will notice that the exatmo drives suck, or that the computer is now dumber.
To gather any damage report info from an opponent would requires a successful attack ECM probe.

From a game standpoint, it is up to the referee and players to decide how much the personas know.
Some referees will keep all space vehicle damage behind the screen and only letting players know a bit.
Other groups will have the players keeping track of their own vessel's demise.

== Onboard Crew
Crew includes any persona that is onboard a space vehicle during combat.
They can lend their skills to assist the ship's computer or repair the damaged ship.
A combat turn lasts 30 units in EXP.
This is sufficient time for personas to have a lot of fun during combat events.
Personas are not be able to assist with an attack and repair the ship simultaneously.

=== Attack Assist
For example, a mechanic with artillery skill 2 is assisting a level 3 computer.
This vocation computer team would make attack rolls as a level 5 computer.
The attack and success roll bonuses are not limited to a particular vocation.

If the space vehicle is flush with crew, the computer can work with a research team to pile up bonuses.
Before a mechanic, a mercenary and spie can work together to assist the computer they must form a research team. 
Research teams are located somewhere in this book. 

=== Ship Repairs
There is enough time during combat turns to accomplish ship repairs.
The goal of ship repairs is to return percentage points of efficiency and restore functionality.
Ship repairs are entirely under the purvey of the mechanic vocation.
The personas can form research teams depending on the system being repaired. 

NOTE: *Destroyed systems cannot be repaired during combat.*

These are not maintenance repairs. 
These are bubble gum and duct tape repairs to get through combat.
Most of these repairs will fall apart once combat ends.

For example, a mechanic attempts to repair the special drive by 10 percentage points. 
This would be a 10 DD maneuver for the mechanic.
If she is successful, the special drive will move from 8% effectiveness (disabled) to 18% effectiveness.
The special drive moves from disabled to critically damaged.
However this let's the expedition jump drive to safety.

The mechanic could also repair an airlock from only opening 40% to opening 60%.
This would be a 20DD maneuver.
This also allows the expeditions combot to join in on the boarding attack. 

== Convenience Table Co-Location

include::ROOT:partial$CH38_Table_Space_Vehicle_Damage_Location.adoc[]

include::ROOT:partial$CH38_Table_Extent_of_Space_Vehicle_Damage.adoc[]

include::ROOT:partial$CH38_Table_Extent_Damage_Descriptor.adoc[]
