= Exatmo Vehicle Combat

[quote]
____
We shall fight them on the beaches. We shall fight them in the troposphere. We shall fight them in the cold, silent darkness of space. 
____

// attack rolls vs comp rolls vs pilot rolls
// need a list of attacks and what can assist them and what can defend against them.
// maybe a better attack defend counter cycle table
// what the fuck are counters anyways

Combat in outer space is very deadly.
The threat to organic life is total.
The speeds are incredible.
The weapons are formidable. 
Life enjoying personas avoid space vehicle combat.
The space vehicle combat in EXP supports intimate skirmishes between solitary vessels.
This section is not for battling armadas that can vaporize kilometre-long battle cruisers.
One-on-one space vehicle battles allow the players to be more involved.

:art: space_combat_missiles.png
:width: 450px
:snark: Billions of credits being wasted.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of spaceship launching missiles and firing lazers.

include::ROOT:partial$articulate.adoc[]

Space vehicles are extremely valuable.
Personas prefer to take over space vehicles rather than destroy them.
Most space combat will end with the expedition boarding a defeated vessel or defending a defeated vessel.

The procedure for space vehicle combat is similar to lethal persona combat.
There are turns, initiative, attack rolls, damage rolls, and effects of damage.
For the most part, the computers are running the show in space vehicle combat.
The players can make some decisions, but the execution and success of the combat is a battle of the ships.
The space vehicle computers manage maneuvers, generate electronic countermeasures, and guide missiles.
The organics onboard buckle down while the ship spins to put as much hull between its integral components and incoming attacks.

== Space Vehicle Nomenclature
Exatmo is a contraction for exterior to atmosphere. 
Exatmo is deadly to all personas (anthros, aliens and robots) unless they are specifically protected.
ECM is an acronym for electronic countermeasures. 

A vehicle must have exatmo or special drives to be a space vehicle.
An airship only has an inatmo drive.
An airship could be a plane or a dirigible, but not a space vehicle.

include::ROOT:partial$CH38_Table_Nomenclature_of_Space_Vehicles.adoc[]

Space vehicles are created in the xref:iii-hardware:CH52_Space_Vehicle.adoc[Space Vehicles] section.
Players and referees should understand space vehicles before blowing them up.

== Escape
Personas can avoid space vehicle combat by running away.
Space vehicles are so diverse that one vessel can usually escape another.

NOTE: *The best way to win a space fight is by 12 parsecs.*

One can run away using exatmo drives.
One can dive into the atmosphere using inatmo drives.
One can jump away using special drives.
Unless a ship's drives are damaged, the expedition can choose to escape.
In general exatmo vehicle combat is agreed upon by both parties.

== Elements of Exatmo Vehicle Combat
Exatmo vehicle combat happens at tremendous speed.
Exatmo vehicle combat happens at tremendous distances. 
There are many ways to attack a space vehicle.
ECM, ramming, mines, boarding and artillery.
Most personas will prefer to board and take over a ship due to its value.

.*Unique Elements of Exatmo Vehicle Combat*
. Combat parameters are massive
. Computer-controlled combat
. Combat turns are different
. Victory conditions are unique.

=== Combat Parameters
On an astronomical scale, the distances between space vehicles are minuscule.
For players and their personas, these distances are enormous.
Battling space vehicles could be tens of kilometres apart. 
Only when ramming and boarding do space vehicles come close to each other. 

The speeds are entirely unrealistic. 
Space vehicles use their exatmo drives to maneuver during combat. 
Exatmo drives move at up to 0.9 the speed of light. 
Space vehicles must be travelling at almost the same speed to engage.

:art: tell_them_I_love_them.png
:width: 350px
:snark: Tell them I love them!
:artist: JEShields
:date: 2014
:license: Copyright JEShields Stock Art. jeshields.com
:description: Naval admiral with manly beard yelling and pointing on bridge.

include::ROOT:partial$articulate.adoc[]

=== Computer Controlled
No lifeforms can balance all that is needed to engage in combat.
The combat happens at tremendous speeds.
The combat happens at tremendous distances. 
The process requires many simultaneous calculations.
The ship's computer is not just a calculator. 
The computer integrates with every aspect of the ship.

Only the ship's computer can manage the connectivity and calculations required for combat.
Players and personas are mainly uninvolved in exatmo vehicle combat.
The computers determine the attack sequences, movement and tactics of combat.
The players get to roll dice, but the computer is deciding the combat course.

=== Combat Turns
A turn in exatmo vehicle combat is very different from a combat unit in the tactical combat system.
Space combat turns are longer and more structured than the free-wheeling 2-second tactical combat unit.
A combat turn lasts one minute and involves a stepwise execution of attacks and defences.
During a turn, the combatant vessels are wildly jockeying for position at half the speed of light.
The ship computers are firing missiles, dumping mines, calculating ECM, and aiming artillery.
Most often, the personas will be idle as the players make attack rolls and decisions. 
However, it is also possible for personas to use every unit of the turn doing other stuff.

Players do not make a lot of decisions during exatmo vehicle combat. 
The cycle of attack, defend and counter-attack is built into the turn. 
There are initiative rolls, attack rolls, defence rolls, and damage rolls to be made each turn.
The process continues until a vessel escapes or achieves victory conditions. 

=== Victory Conditions
The victory conditions of space vehicle combat are unique to the vessel itself.
The victory conditions of persona tactical combat are simple.
One of the combatants is unconscious, dead, or escapes.
The goal of space vehicle combat is to gain control of the target ship, not destroy it.

There are four main victory conditions in space vehicle combat.
They all involve the inability of the defeated ship to function.
A space vehicle battle can be lost by: running out of fuel, a severely damaged gravity system, destruction of the exatmo drive, or loss of bridge control.

.*Victory Conditions*
* Loss of Fuel
* Loss of Gravity
* Loss of Exatmo Drive
* Loss of Bridge

NOTE: *Victory conditions are more like defeated conditions. Glory to the English language.*

The victory conditions indicate when the __space battle__ is over.
A space battle rarely destroys a space vehicle. 
Likely the ship's crew and cargo will be intact.

==== Loss of Fuel
Running out of fuel may be the least glamorous way to lose a battle.
Combat fuel burn is tremendous, and no fuel means no combat maneuvers. 
A ship out of fuel stops spinning and hurtles off in a predictable trajectory.
The predictable trajectory makes the vessel vulnerable to boarding, ramming and focused attacks. 
Inadequate fuel for combat does not threaten life support or onboard systems.
A fuel-depleted space vehicle may not be controlled by the attackers yet, but the exatmo battle is undoubtedly over.

==== Loss of Gravity
A space vehicle's gravity system is an essential part of the life support system.
The gravity system allows personas to enjoy normal gravity within the space vehicle.
The gravity system keeps the persona's feet or flippers comfortably on the deck of the space vessel.
While this may sound like a convenience maintaining constant gravity in combat is life-saving.

The sciency fiction exatmo vehicle combat system involves vessels flipping, twirling and banking using their exatmo drives.
These maneuvers would obliterate all life without a gravity system, and the ship would tear itself apart.
Doing a barrel roll at 500 million km/h is not compatible with physics, let alone life. 

Combat is over if the gravity system is functioning at less than 30%.
The space vehicle cannot use exatmo drives if the gravity system functions at less than 10%.

A ship out of gravity safely stops spinning and hurtles off in a predictable trajectory.
This predictable trajectory makes the vessel vulnerable to boarding, ramming and targeted attacks. 
Inadequate gravity for combat does not threaten life support or onboard systems.
The crippled space vehicle may not be controlled by the opposition yet, but the exatmo battle is undoubtedly over.

==== Loss of Exatmo Drive
If the drives are dead, the space vehicle is unable to engage in space combat.
In combat, the exatmo drives are potent units that swing the ship madly around, deflecting kinetic attacks, and aligning weapons.
If the exatmo drives are out of commission, the space vehicle has come second place in space combat.

==== Loss of Control of Bridge
The final pathway at the end of all exatmo vehicle combat is losing control of the bridge.
There are several ways to lose control of the bridge: surrendering the bridge, losing the bridge to personal combat or destroying the bridge during space combat.

== Combat Turn Cycle
Space combat is aggressive.
Every attack is happening as fast as possible.
Each turn has a cycle of attack, defend and counter-attack.
The first strike is the goal, and initiative is essential. 

The combat turn cycle goes from fastest to slowest attacks. 
ECM will always act before naval artillery.
Defences are automatically activated unless the player chooses not to defend.
Counter attacks are attacks that double as defences.
Counter attacks are not automatically activated and require a decision by the player.

Each space vehicle is randomly created and has a different weapon configuration.
The attack order only applies to attacks that the space vehicle has.
One space vehicle may only have ECM, while another may have ECM and bombs.
Naval artillery is very rare.
All space vehicles can ram or board. 
All of these attacks are possible in each combat turn.

include::ROOT:partial$CH38_Table_Attack_Defend_Counter_Attack.adoc[]

== Initiative
Initiative is only needed when both vessels have the same attack type.
For example, if both combatants have ECM, the pilots roll initiative to see which vehicle's ECM acts first.
If only one combatant has ECM, this pilot would automatically act first.

=== Initiative for Space Combat
.Init = 1d20 + Computer Level + Pilot Level
****
Init = 1d20 + computer 4 + pilot 3 = 1d20 +7 = 15 + 7 = 22
****

=== Example of Initiative
Spaceship One (SS One) has the attacks ECM, Ramming, and Artillery. 
Spaceship Two (SS Two) has the attacks Ramming, Artillery and Grenades. 

.*Turn order and Initiative*
. SS One attacks with ECM.
.. No initiative roll. 
. SS Two makes a ramming attempt.
.. No initiative roll.
.. SS One has used up ECM.
. Both fire their artillery
.. Initiative rolls required.
. Neither ship is boarding
. SS Two fires mini-missile grenades
.. No initiative roll
.. SS One has used up ECM.

== Attacks
Attacks are a collection of electronic, kinetic, and energy weapons that one ship uses to control or damage another ship.
Some attacks work as defences as well.

.*List of Attacks*
. <<_ecm,ECM>>
. <<_ramming,Ramming>>
. <<_artillery,Artillery>>
. <<_boarding,Boarding>>
. <<_grenades,Grenades>>
. <<_bombs,Bombs>>
. <<_naval_artillery,Naval Artillery>>

== ECM
ECM is an abbreviation for electronic countermeasures, and it is pronounced "easy em."
ECM is the battle for control over the electromagnetic spectrum.
In space vehicle combat, ECM is the battle for control over the electronics of the target ship.
Attack ECM can confuse the target ship's defences with false data and control the target ship's essential component.
Or be used as defensive instead of attack.
The pilot must choose between Attack Assist, Control Attack or Defense for her ECM each turn.
An ECM attack unit is still an ECM unit and can be used to defend instead.
One unit cannot do both.

=== ECM Attack Assist
When ECM is being used to assist its own ship's attacks, it will attempt to deceive the target by creating inaccurate or false data for the target ship.
ECM does this by making single attacks appear as multiple attacks, altering the apparent course of incoming attacks, or confusing the estimated arrival time of an attack.
All such falsified data will increase the chance of success of a ship's attack.

ECM-assisted attack rolls receive a bonus of +150 attack per computer level.
Percent attacks receive a bonus of +3% of success per computer level.
A space vehicle with a level 2 computer making an attack roll attack (missiles) assisted by ECM would get +300 on the attack roll.
A level 2 computer gives a bonus of +6% for success with percent attacks (ramming) when being assisted by ECM.

=== ECM Control Attack
ECM control manipulates a target ship's onboard systems.
The chance of successfully controlling another ship's systems is 8% per level of the attacking spacecraft's computer.
If an ECM Control Attack should fail, that particular control attack cannot be re-attempted during the combat session.
However, a different ECM Control Attacks are still possible. 
If an attempt to reduce drive effectiveness fails, the ECM Control Attack can attack the ship's gravity in the next turn.
The pilot can choose to use control attacks until something clicks.

=== ECM Attack Roll
.chance = 100 - 8% per computer level
****
Level 6 computer. (100 - 48) = 52. The player must roll 52 or higher. 
****

If control ECM is successful, the targeted component's capacity decreases.
An ECM unit cannot do anything else while controlling the target ship's components.
This effect will last until the target ship breaks the ECM, the target ship uses its special drives, or the attacking ship ceases the attack.

include::ROOT:partial$CH38_Table_Example_ECM_Control_Attacks.adoc[]

The referee will often need to improvise the effect of an ECM control attack.
When improvising, the ref should remember that a successful ECM attack will not destroy a ship.
An ECM control attack reduces a particular ship component's effectiveness and increases the ship's vulnerability to other attacks.

:art: aggressive_boarding.jpg
:width: 350px
:snark: Some sailors can't wait for boarding.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Human woman with cybernetic parts jumping out of spaceship hull opening.

include::ROOT:partial$articulate.adoc[]

== Ramming
Ramming is a boarding method.
Ramming is similar to boarding, except that ramming has lots of crunching and scraping noises.
Ramming is different from regular boarding because it does not align airlocks.
A space cruiser with a ramming attack has a specialized fortified airlock that can ram into any part of the target ship's hull.
Ramming is violent and throws caution to the solar winds.
Once attached, the invading party may breach the hull to gain entry into the ship.

ECM can assist ramming. 
Using ECM as an attack assist for ramming gives a +6 bonus per computer level on the Ramming Pilot Roll.
ECM cannot assist ramming while carrying out other ECM attacks or defences.

.*Ramming Checklist*
. Determine the number of ram attempts
. Determine Ramming Pilot Roll
. Assess Damage Location on target.
. Extent of Damage to target vessel (max Major)
. Damage (one level less) to ramming vessel
.. Lash and board 0-3 (1d4-1) turns
.. Smash and run

=== Attempts
An attacking vessel only has so many opportunities to ram a target. 
The target ship's pilot and computer make avoidance maneuvers using the exatmo drives.
Eventually, the target vessel will become immune to the ramming attacks.

=== Number of Ram Attempts
.Attempts = (attacker drive + computer + pilot levels) - (defender drive + pilot levels)
****
The maximum number of ramming attempts is four. 
****

If the number of ramming attempts is positive, the attacker gets that many ram attempts.
An attacking vessel cannot have more than four ramming attacks per battle.
If the number of ram attempts is two, the attacker can make two ram attempts during the battle. 
If the number of ram attempts is six, the attack can make four ram attempts during the battle.

If the number of ramming attempts is zero or less, the attacker only gets one ram attack during the battle.
This solitary ram attack suffers a penalty equal to the value of the negative number.
If the number is -3, the attacker gets one ram attempt with a -3 penalty.

=== Ram Begets Ram
Each time an attacker has a failed ram, the target gets a chance to ram in return.
The target space vehicle gets one ram attempt per failure.
If an attacker fails three ramming attempts, the target ship gets three ram attempts. 
The target vessel gets a chance to ram even if it has no further ram attempts left.

=== Ram Success
The ramming vessel's success depends on the attacker's computer level and pilot level.

=== Ramming Target Roll
.success = 100 - (12% + pilot level) * computer level
****
Level 6 computer and level 3 pilot. +
target = 100 - (12+3) * 6 = 100 - 90 = 10. 
Player must roll 10 or higher to ram.
****

=== Smash or Lash
The players must decide whether they are smashing and running or lashing onto the rammed vessel.
Smashing is as it sounds.
The attacker smashes the target ship and backs off like a demo derby near light speed.
Lashing involves attaching to the target ship and boarding through the breached hull. 

Ramming damages both the ramming and rammed vessels. 
Hull breach success is automatic and takes 0-3 (1d4-1) combat turns.
The Damage Location Roll also indicates where the attacking ship will breach the hull.
For example, if the damage location is the target ship's drives, the boarding party will enter the vessel at the drives.

== Artillery
The purpose of ship artillery is to damage the target ship so that it ceases to function.
This goal is achieved by penetrating the hull and delivering the artillery's destructive force to the internal components of the ship.

Space vehicle artillery has the same damages and effects as the inatmo artillery it is modelled after.
The two differences are ammunition stores and range. 
Energy-based weapons can fire as long as the ship has fuel, and ammunition requiring ammo will have 100 times the regular supply.
There are no range penalties during space vehicle combat. 

The expedition cannot fire space vehicle artillery from exatmo to inatmo.
This artillery cannot cross into an atmosphere.
Once the space vehicle is inatmo, the players can use the artillery as usual. 

=== Hitting with artillery
Artillery requires a successful attack roll to inflict damage.
The player must win an attack roll against the target spaceship's armour rating.
The attacker must make a kilodie roll higher than her target's armour rating.
The target ship's armour rating, including hull strength and ECM, may prove impenetrable to many artillery attacks.

The attacking ship's computer level adjusts the artillery's attack roll.
A gunnery program will fire the artillery automatically, with a bonus of +50 per level of ship's computer.
If a skilled gunner persona is firing the artillery, there is a bonus of +100 per level of ship's computer.
The organic firing bonus is due to the unpredictability of an organic life form firing a weapon.

== Boarding
Boarding is congenial ramming.
Boarding lines up airlocks to prepare for a breach and boarding of the target vessel.
The attacker can only use boarding to force airlocks together while exatmo (exterior to atmosphere).
Once connected, the attacking crew will breach the airlock of the target ship and then board.
Boarding is a preferred attack because it preserves the target space vehicle, hostages, cargo and is a lot more fun.

.*Boarding Checklist*
. Determine the number of board attempts
. Make Boarding Pilot Roll.
. Prepare to board

=== Mutual Boarding
If two ships are trying to board each other, they will be automatically successful.
Since the goal of both ships is to connect airlocks.
ECM will recognize that both ships want to connect, and it will happen automatically.
If either the attacker or target vessel wants to direct the mutual boarding to a specific airlock, they must win a boarding roll.

=== Attempts
The number of boarding attempts equals the number of ramming attempts, and the same calculations apply.

=== Chance per attempt
Boarding is more delicate and intricate than ramming.
The success of boarding depends on the computer level and pilot skill of the attacking vessel.

=== Boarding Roll
.success = 100 - (4% + pilot level) * computer level
****
Level 6 computer and level 3 pilot. +
success = 100 - (4 + 3) * 6 = 7 * 6 = 58.  +
Player must roll 58 or higher to attach.
****

=== Once Connected
If the player wins the boarding roll, the two vessels attach via airlocks.
Once connected to the target ship, there are a few options.
The attacking vessel can stay docked, and the boarding party can work on opening the airlock.
Usually, a boarded ship will be resigned to its fate and open the airlock to avoid damage.

Combat fuel consumption is the only requirement to remain attached.
Once a ship has been boarded, it cannot forcefully detach from its attacker.
The only recourse that the target ship has is to continue maneuvering at combat fuel consumption and hope that the boarding ship runs out of fuel.
If the boarding ship can no longer maintain combat maneuvers, the target ship can break away from boarding. 

If the target is unwelcoming, the airlock may require breaching.
Airlock breaching is left for the referee to run with her players.
Mechanics and spies are more proficient at airlock opening than dumb old mercenaries.

== Grenades
The types of space vehicle grenades are the same as their inatmo counterparts.
The main difference is that these grenades travel by mini-missile or mini-mines, and they must win an attack roll to damage the target.
Inatmo personas throw grenades and only need to get close to damage a target.

The grenade is a space vehicle vs a space vehicle weapon.
A successful attack roll must be made against the space vehicle's armour rating to inflict damage.
If the attack roll is unsuccessful, the grenade detonates ineffectively and silently in space.

Grenade delivery systems have diminutive titles because they only deliver grenades. 
Proper missiles and mines deliver bombs.

=== Mini-Missiles
Mini-missiles are rocket-propelled space grenades.
A ship can launch three mini-missiles per level of computer at one once.
The attacker can use ECM to assist the mini-missile attacks.
Each individual mini-missile requires an attack roll to damage the target.

Mini-missiles cannot cross into an atmosphere from space but work perfectly well if launched inatmo.
When used inatmo, the mini-missiles attack like regular grenades as an area of effect weapon.

Space vehicles can outrun mini-missiles.
If a target's drive is more than two levels higher than the attacking vessel, they can outrun mini-missiles.
If an attacker is boarding or ramming a slower vessel, they cannot outrun a mini-missiles attack. 

=== Mini-Mines
Mini-mines are grenades dumped in the path of starships hoping that they will explode for damage.
Grenades can be dumped in the path of a ship's orbit, dumped in the course of a pursuing ship, or jettisoned against the hull of a boarding or ramming ship.
Mini-mines are inactive mini-missiles, they do not chase targets, and a ship can only dump them.
The mini-mines are useful because ECM does not affect them.
Mini-mines also move too slow to be affected by shields.
Essentially mini-mines cannot be avoided unless they are visually detected.
The ability to detect the tiny camouflaged mini-mines requires a bizarre AWE (kilodie) roll.
A space vehicle can dump mini mines at a rate of 5 mines per unit per computer level.
Mini-mines, like mini-missiles, cannot survive the rigours of entry into an atmosphere but can be used to bomb targets once inatmo.

== Bombs
Bombs are lethal attack weapons.
Bombs need only explode near the ship's hull to inflict damage to the contents within.
Space vehicle bombs function the same as their inatmo counterparts, but the delivery is a mine or missile. 

A bomb is guaranteed to damage a target with a successful attack roll.
Every bomb gets a second chance to damage a vessel just by getting close enough. 
If the raw roll of a missile or mine is better than 500, the target is still damaged.
Dangerous, destructive weapons.

=== Bomb Missile
A bomb missile is also called a naval missile.
Missiles can target any detectable space vehicle.
The attacker can control one missile per level of ship's computer.
No vessel can outrun a missile.
An attack roll is still required to damage the target. 
Unlike a mini-missile, a target cannot dodge a bomb missile.

Even though a missile will eventually catch up with its target, there is some time before impact.
The time to impact is a wonderful sciency fiction plot device.
If the attacking vessel has a higher drive level than the target ship, the missile arrives in that turn.
If the target space vehicle's exatmo drive level is higher than the attacker, there is a "calc" for that.

=== Turns to Missile Impact
.Turns = Target's Exatmo Drive Level - Attacker's Exatmo Drive Level
****
Target's drive level is eight, and the attacker's drive is four. The target has four turns to brace for impact.
****

Missiles cannot function inatmo.
A target vessel may escape a missile by hiding inatmo or by jumping with the special drives.

=== Bomb Mine
A bomb mine is also called a naval mine.
A ship may dump one mine per level of ship's computer per unit.
The mines have no drive components and are discarded into the flight paths of target starships.
Mines can attack orbiting, pursuing, boarding, ramming, or unaware targets.

This mine delivery method has some advantages over its missile counterpart.
First, the mines are virtually undetectable.
Defensive ECM does not work against them.
Detecting a min in space is an improbable (d100) awareness attribute roll.
Mines are hardy enough to be deployed in the atmosphere or in orbit to be used as fierce surface attack weapons.

== Naval Artillery
Naval artillery has only one purpose in mind, to destroy the target ship.
Naval artillery is not a tool to soften or assist in the taking over of the target vessel.
The sheer force of the weapon accomplishes the destruction.
One use of naval artillery exhausts a whole day's worth of fuel.
Players cannot idly use the naval artillery; it requires a gunnery program and two gunners.
Without this complement, a ship cannot fire its naval artillery.

Naval artillery is more deadly than its deadly inatmo companion.
Naval artillery inflicts three times the damage and has 100 times the range.
Naval artillery only works exatmo and cannot cross or be used in the atmosphere.

The player must win an attack roll, but naval artillery is so powerful a miss may still damage the target.
A successful attack with naval artillery inflicts two damage rolls.
A near miss (600 or higher) still inflicts one damage roll.
If the naval artillery scores a direct hit, the attack cannot be absorbed by the target's shields.
The target's shields can only absorb damage from one attack at a time. 

== Defences
A space vehicle's defences both defend against attacks and the hostile environment of outer space.
Defences are a mix of combat defences and essential exatmo life support protections.

.*Defences*
. Life Support
. Gravity Control
. Hull
. Armour
. ECM
. Shields
. Guns
. Actives

== Life Support
Life support maintains a comfortable environment for the organic and delicate inorganic contents of the ship.
Life support is a fancy air conditioner that also supplies the air.
The life support,  gravity control and the ship's hull have an intimate level of integration. 
Life support is impossible to disable because it is both distributed and self-contained.
The ship's computer depends on an intact life support system.
Life support functions correctly unless directly damaged by combat.

Control ECM attacks can manipulate life support and make the inhabitants uncomfortable.
Control ECM cannot turn off life support or threaten the well-being of the ship's contents.

include::ROOT:partial$CH38_Table_Life_Support_Chain.adoc[]

Destroying life support is rarely the goal of space vehicle combat. 
Space vehicles are too valuable to destroy utterly.
A loss of life support destroys all life on the ship, and more importantly, the ship's computer.
Life support has onion layer protection, and the outer layers protect the inner layers. 
One cannot damage life support without disabling the hull and then gravity control first.

A partially damaged life support system will maintain a fraction of the atmosphere proportional to its amount of damage.
A fully operational life support system taking major damage would only have 60% of the previously had atmosphere.
This thin atmosphere will make it more challenging to work and stay conscious.

If a space vehicle loses all layers of life support at once, the ship will suffer explosive decompression.
Decompression destroys all organic materials (personas) and delicate inorganic devices (computers, robots, toys).

== Gravity Control
The gravity system is a crucial component of the life support system.
The gravity control, life support and the ship's hull have an intimate level of integration. 

include::ROOT:partial$CH38_Table_Life_Support_Chain.adoc[]

Gravity control maintains gravity at a constant attraction of 1g.
The gravity is uniform across walkways, workspaces, cargo holds, cabins, and hull exterior.
The ship's computer can adjust the gravity from 0.5 to 1.5 gravities.

Gravity control maintains a comfortable working gravity throughout the ship at all times. 
Personas onboard will not notice any difference between a stationary ship and one making combat maneuvers near light speed.
Almost any maneuver performed by a space vehicle would destroy all organic materials (personas) and destroy all delicate inorganic devices (computers, robots, toys) without gravity.

NOTE: *Gravity control is a sciency fiction mechanism designed for role-playing fun.*

The gravity system can be manipulated by control attack ECM.
However, control ECM cannot turn off gravity or make life dangerous for the vessel's contents.
Control ECM attacks are an irritation manipulating the gravity to confound, not kill, the crew.

.*Damage to Gravity System*
. Gravity at <30% No combat
. Gravity at <10% No exatmo or inatmo movement 
. Gravity at <1% No gravity
. Life Support vulnerable

At less than 30% function, gravity control cannot maintain safety during combat maneuvers.
Without the protection of gravity control, the vessel must drop out of combat.
Loss of gravity control is a victory condition.

At less than 10% function, gravity control cannot maintain safety during standard exatmo drive maneuvers.
Without the protection of gravity control, the vessel must crawl through space with limited acceleration.

== Hull
The hull is a crucial component of the life support system.
The ship's hull, gravity control and life support have an intimate level of integration. 

include::ROOT:partial$CH38_Table_Life_Support_Chain.adoc[]

The hull is the containment and physical defence system of the ship.
The hull also defends against both hostile environments and attacks.
The star cruiser's hull is the last line of defence.

The hull supplies the space vehicle's armour rating used in combat.
The hull and armour rating have an intimate relationship.
In combat, the hull absorbs damage decreasing armour rating.

NOTE: *The Hull armour rating (AR) protects the Hull. Once the Hull AR is is less than 420, the Hull takes direct damage rolls.*

Defensive ECM can increase the space vehicle's AR against attack rolls.
The increase in AR is a transient electronic deception and does not alter the Hull AR.

== ECM
Electronic countermeasures (ECM) deceptively manipulate the electromagnetic spectrum to defend the ship.
ECM is more effective as the ship's computer level increases.
If any personas have skill in ECM, they can add that skill level to the computer level used for the ECM.
So if a mechanic has ECM level 2 and the computer level is 3, then the ECM will function as a level 5.

ECM is an accessory unit of the ship's computer. 
Electronic countermeasures are both attack ECM and defence ECM.
An ECM unit cannot be both at the same time.
If the space vehicle has only 1 ECM unit, the players must decide how to use it each combat turn.

=== ECM AR Boost
Most often, defensive ECM will be used to make the ship harder to attack.
ECM creates false images of velocity, trajectory, rotation, size, etc.
All of this electronic tom-foolery results in a +200 bonus to the ship's armour rating per computer level.

=== ECM Break Control
Defensive ECM is essential when the ship is under attack from control ECM.
Defensive ECM can identify whether a ship's component is malfunctioning or whether it is malfunctioning due to control ECM.
Defensive ECM will use the ship's computer to re-route communications channels and alter security, to defend against control ECM attacks.

For example, if a control ECM attack had reduced the effectiveness of the ship's drives, defensive ECM could be used to break this control.
Successfully breaking this control restores the drives to their previous level.
The chance of success is 15% per computer level.

=== ECM Break Control Roll
.success = 100 - 15 * (computer + skill level)
****
Level 3 computer and level 2 engineer. + 
Target = 100 - (15 * 5) = 100 - 75 = 25. +
Player must roll 25 or higher to break control.
****

=== ECM Camouflage
Defensive ECM can be used to hide the ship electromagnetically.
ECM will make the ship blend in with the background or appear some anomaly other than a spaceship.
This aspect of ECM will not hide the ship from a visual inspection, but it will deceive another ship's sensors.

=== ECM Camouflage Roll
.success = 100 - 9 * (computer + skill level)
****
Level 3 computer and level 2 engineer. +
Target 100 - (9 * 5) = 100 - 45 = 55. +
Player must roll 55 or higher to hide.
****

=== Damaged ECM
Damaged ECM drops its effectiveness by the percentage indicated on the Extent of Damage table.
For example, ECM at 50% efficiency can only offer +100 per computer level to the ship's armour rating.

== Shields
The shields protect the hull AR and hull from energy and kinetic attacks.
A defensive shield may be a force field or a structural mechanism. 
Both mechanisms work by distributing the destructive force across the entire hull.
This faux scientific diffusion effectively dampers the damage.
The shields have an active mode that the players turn on to thwart intentional damage.
Shields also have a passive mode, and when present, they are part of the life support system.

Shields require energy to distribute attack damage and are powered directly by the exatmo drives.
The shields can absorb 100 HPS of damage for every level of exatmo drive.
For example, a ship with a level 4 drive could absorb 400 HPS of damage.
An attack with 429 HPS of damage against a 400 HPS shield would only deliver 29 HPS damage to the ship.

The shields absorb damage from mini-missiles, naval-missiles, artillery, and naval artillery attacks.
Shields do not affect ECM, boarding, ramming, mini-mines or naval mines. 

Active shield use doubles fuel consumption. 
Shields usage is optional.
Players may choose to turn off their shields to conserve fuel.

Passive shielding becomes part of the life support system.
Damage must disable the shields before the Hull AR can be damaged.
This passive protection does not use any extra fuel.

include::ROOT:partial$CH38_Table_Life_Support_Chain.adoc[]

== Guns
A gun is a purely defensive element in space vehicle combat.
A gun does not sound like a defensive tool, but occasionally the best defence is a good offence.
Guns on space vehicles are anti-personnel air lock defence weapons.
In ship-to-ship combat, a gun is an ineffectual weapon.
However, to prevent boarding or airlock intrusion, a mounted gun can be very effective.

.*Airlock Defensive Guns*
* operate inside or outside of the airlock
* operate inatmo or exatmo
* operates autonomously with software
* Can be controlled by personas
** mercenaries do this best
* has unlimited ammo to defend against boarding
** ammo can be limited to forward plot
* has an AR equal to the ship's hull
** including ECM and shields
* damaged by Hull AR damage or airlock damage location

== Active Defenses
Active defences intercept incoming attacks.
Active defences are sometimes called actives.
They can eject missiles, shrapnel, energy blasts, lazer matrices, or crystalline discharges. 
The goal is to dissipate, prematurely detonate, or destroy incoming attacks.
All active defences function equally.
Active defences can stop grenades, bombs, or artillery.
Actives defences cannot stop boarding, ramming, ECM, or naval artillery.

=== Active Defence Roll
.success = 100 - 9 * (computer + exatmo drive + skill levels)
****
Level 5 computer and level 3 drives. +
Target 100 - (9 * 8) = 100 - 72 = 28. +
The player must roll 28 or higher to block the attack.
****

A ship can attempt to thwart one attack per level of computer per turn.
A ship will have 100 disposable charges for every 50 tonnes of space vessel.

.*Notes about active defences*
* Active defences are not part of the Life Support Onion
* Active defences are automated
** Gunnery skilled personas can help
* Active defences work inatmo and exatmo
* Actives cannot be weaponized

== Counter Attacks
Counterattacks are opportunities offered by a defending ship.
Counters are specific defences against specific attacks. 
For example, a ship being rammed or boarded gets to counterattack with mines or artillery. 


== Space Vehicle Damage
When an attack is successful, the ship suffers damage.
There are many roads to a successful attack.
The player can win an attack roll by beating the target's armour rating.
The player can win a percentage roll by beating the target roll.

Space vehicles do not have hit points.
Whenever a ship is damaged, the successful attacker rolls both a hit location and extent of damage.
However, the HPS damage rolled for an attack is important.

.*Breaking Down Space Ship Breaking*
. A successful attack
. Damage Location
. Damage Severity
. Damage Effect

Damage to the interior of the ship does not necessarily indicate hull damage.
Power surges, from one point to another, can also account for random damage locations.
Keep in mind the Life Support Protective Onion when inflicting damage on space vehicles.

include::ROOT:partial$CH38_Table_Life_Support_Chain.adoc[]

== Damage Location
Damage location indicates which of the space vehicle's systems is targeted by an attack.
Damage location in space vehicle combat is entirely random.
The damage location is random because of space vehicle diversity, the chaos of combat maneuvers, and mystery juice.
Space vehicle damage is similar to damage location for robots and vehicles.
Every successful attack generates a random damage location.

The damage location is not the same as a hit location. 
Power surges, electric disruptions, shields, and ship structure send damage anywhere in the vehicle.
Even a space vehicle that is immobilized cannot have damage locations chosen.
Automatic hitting does not affect damage location.

include::ROOT:partial$CH38_Table_Space_Vehicle_Damage_Location.adoc[]

=== Missing Damage Locations
A space vehicle may not have the damage location rolled.
The damage location may have never existed on the space vehicle.
 For example, a space vehicle may not have a special drive damage location.

There are several approaches to missing damage locations.
The player can simply roll again to find a different damage location. 
The referee can move the damage location within the general damage location.
For example, a hit on the special drives becomes a hit on the exatmo drives.

In the case of a previously destroyed location, the attack falls on useless space junk. 
A system is destroyed when its function is <1%. 

== Damage Extent
The Extent of Damage Table determines how badly the system is damaged.
Space vehicle weapons inflict damage in HPS, but space vehicles do not have hit points.
Damage inflicts a decrease in function to the location.
The extent of damage roll reduces the performance of onboard equipment. 
If an exatmo drive is reduced by 50% functionality, the space vehicle loses half its speed and range. 
If the exatmo drive is damaged by 50% again, the new functionality would be 25% fully operational. 
For example, an exatmo drive level of 8 would be reduced to 4 by 50% damage and then to 2 by another 50% damage.

include::ROOT:partial$CH38_Table_Extent_of_Space_Vehicle_Damage.adoc[]

=== Damage Adjustment
Damage adjustment is an optional rule that increases the severity of damage by hit points of damage. 
Each hit point of damage increases the extent of damage by one percent.
An attack inflicting 30 HPS of damage adds 30 to the extent of damage roll.
If a player rolls 55 on the extent of damage table and inflicts 30 hit points of damage, the final roll is 85. 
The 30 hit points increased the extent of damage from minor to major.
When using this damage adjuster, space weapons become way more destructive.
The players may prefer to adjust the damage adjustment to one percent per 5 hit points of damage.
Your space milage may vary.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

==== Cumulative Destruction
The damaging effects of successful attacks are cumulative.
A space vehicle system can be disabled over several attacks.
A system taking major damage (60% performance) twice has a 36% level of function. 
If the already damaged system suffered a critical blow (30% performance), it would drop to 11%.
A level 10 computer would be functioning as a level one computer. 
A level 5 exatmo drive would be functioning as a level one drive. 
Any further damage would decrease the system's performance to less than 10%.
A system is disabled when it is less than 10% functional.

.*Example Cumulative Damage*
. Undamaged 100% function
. Major Damage 60% function
. Major Damage 36% function
. Critical Damage 10% function
. Minor Damage 9% function - disabled

==== Instantaneous Destruction
Instantaneous destruction occurs when an attack destroys a system in a single blow.
Naval artillery, mine or missile may have hit the location.
The attack must drop the system from 100% to <1% function in a single attack.

The effects of instantaneous destruction are cataclysmic.
A destroyed hull would explosively decompress, a destroyed drive will melt down, fuel could explode, etc.
There is no chance for repair, and a replacement system will be required.

=== Damage Descriptors
Each time a system is damaged, its performance decreases. 
The damage descriptors offer another way to describe net damage.
A system with minor damage is more than 90% functional.
A disabled system is less than 10% functional.

include::ROOT:partial$CH38_Table_Extent_Damage_Descriptor.adoc[]

== Hull Damage
The hull is an integral component of the life support and gravity systems.
The hull helps contain the atmosphere generated by the life support system.
The hull also acts as the substrate for the gravity system.
Hull, life support and gravity are intimately integrated.

=== Hull as Armour
The hull cannot take damage until the ship's Armour (Hull AR) has been disabled.
The armour ratings of hulls are very high. 
The average armour rating of a space vehicle's hull is 1100.

The armour rating of the hull decreases as it takes damage.
If a mini-mine explodes against the hull and delivers 75 HPS of damage, the hull armour rating decreases by 75.
The hull armour rating can absorb massive amounts of damage, protecting the systems below. 

Reducing the armour rating to 420 disables the armour rating of the hull.
Disabling the armour rating allows damage to pass directly to the hull or the contents below it.
The Hull AR cannot drop below 420.

include::ROOT:partial$CH38_Table_Life_Support_Chain.adoc[]

=== Hull Compromise
Hull only becomes a damage location once the Hull armour rating is exhausted.
The hull begins to fail like any other system on the space vehicle.
The hull is disabled once the level of function drops below 10%.
The hull is destroyed once the level of function drops below 1%.

When the hull has been disabled or destroyed, further hull damage applies to another ship system.
If a player rolls a disabled hull as her damage location, she must roll again to determine which system is affected.
For example, she could hit the exatmo drives through the compromised hull.

A disabled hull (<10%) represents a manageable escape of its inatmo contents.
A destroyed hull (<1%) represents an unmanageable escape of its inatmo contents.
Both of these hull compromises allow for usual evacuation procedures for the area.
Instantaneous destruction (<1% in one attack) represents explosive decompression.
Explosive decompression is lethal to personas and equipment in the damaged location.

The ship can partition off a damaged location using its automated bulkheads.
Naval architecture does not recommend open-concept space vehicles.
The personas can repair a disabled hull during combat.
Life support and gravity systems will replenish repaired hull locations.
Repairing a hull section does not restore its armour rating.
The personas cannot repair a destroyed hull during combat.

== Drive Damage
Drives are the whole point of the space vehicle.
The higher the drive level, the better the space vehicle.
The extent of damage inflicted reduces drive levels.
If a level 10 exatmo takes major damage (40% reduction), it becomes a level 6 drive.
Drive damage is cumulative. 

=== Inatmo Drive Damage
Reduce the drive level of the in atmosphere drive by the percentage indicated.
This system is disabled when its level of function is less than 10%.
A ship with a disabled inatmo drive cannot maneuver in the atmosphere of a planet.
The pilot may beach the ship planetside or remain in orbit until repaired.

=== Exatmo Drive Damage
A damaged exatmo drive will have its drive level reduced by the percentage indicated.
Exatmo drives are disabled when their function is <10%.
The exatmo drives are the ship's combat drives.
Without exatmo drives, it cannot maintain combat spin.
When disabled, the ship drops out of combat and starts floating towards the nearest star.
Disabling the exatmo drives is a victory condition.

Exatmo drives power defence shields, active defences, and boarding evasion.
Damage to the exatmo drives also impairs these ancillary functions.
Exatmo drives are not affected by exposure exatmo. 
However, personas running the drives can be.

=== Special Drive Damage
Reduce the drive level of the special drive by the percentage indicated.
A disabled special drive keeps the space vehicle from making any long voyages.
Special drives are so delicate they resemble a life form. 
Exatmo is very unhealthy for a special drive.

== Fuel Damage
Damage to the fuel system represents the drive's inability to access the necessary fuel to function.
Disabling fuel systems can disable a particular drive or all drives. 
Sometimes the fuel itself is destroyed or lost in space.
Other times the fuel is still present but cannot be accessed.
During combat, there is no difference.

When a specific fuel system is disabled or destroyed, then that specific __drive__ is disabled.
A fuel system will continue to deliver adequate fuel for the drive to function until it is disabled.
The drive is not damaged, but it cannot work without fuel.
In the case of exatmo drives, this is a victory condition.

=== Amount Damage
The space vehicle's total fuel storage is damaged.
Fuel storage damage indicates a loss of actual fuel
The global fuel loss is non-denominational as all drives access the same fuel type.
If the Fuel Amount is damaged, reduced by 40%, all drives have less fuel to burn.
Inatmo, exatmo and special drives become choked for fuel.
Decreasing fuel amount indicates fuel is lost to space or destroyed.
Personas cannot repair fuel amounts lost.

A ship with ten months of fuel takes major damage (40%), reducing the fuel amount to six months.
The special drive can now only make six jumps.
Most importantly, the amount of fuel available for combat maneuvers decreases.
Combat maneuvers burn fuel at the rate of one week per turn of space vehicle combat.
So the space vehicle can now only fuel 24 turns of space combat before dropping out.
Running out of fuel for combat is a victory condition.

=== Consumption Damage
Consumption damage impairs the system that divides fuel between the drives.
The fuel is intact, the drives are intact, and the fuel system is intact.
All fuel systems drop by the extent of damage, but no fuel is lost.
Unless destroyed in combat, the consumption system is repairable.

== Computer Damage
The computer is the space vehicle, and the space vehicle is the computer.
The ship's computer is the most important and most delicate system on the space vehicle.
Computer damage impairs nearly every function of the space vehicle.
If a level 6 computer suffers 40% damage, it becomes a level 2 computer.
ECM, boarding, defences, ramming, targeting are all impaired by this decrease in function. 

A disabled ship's computer puts everything into a non-functional hibernation state. 
Personas may try to operate a ship with a disabled computer manually.
Usually, a destroyed ship's computer leads to an immobilized hulk drifting towards the nearest star.

The ship's computer is not part of the life support onion.
Gravity and life support remain operational in the face of a disabled or destroyed ship's computer.

=== Robot Control Damage
The ship's robots cease to function or follow the computer's commands.
The computer loses control of robots by the percentage indicated.
The ship's control over the robot is damaged. 
The robot is not damaged at all.
Robots will perform gunnery skills, or veterinary care, at a reduced skill level.
Mechanics can try and get the robots functioning through priority commands or robot overrides.

If robot control is disabled or destroyed, the robots stop functioning altogether.
It would be more fun the robots acquired free will with their newfound freedom.
Robot self-awareness could range from irritating behaviours to a well-deserved robot mutiny.

=== Software Damage
While the computer level remains intact, its software loses function.
Ship software has both hardware and software components representing a tight integration with the ship. 

The decrease in function is not only programming data but essential peripherals and sensors as well.
Software damage does not affect the computer level or ECM.
Only the extra software packages are damaged.
For example, crew replacement software damage may remove the ship's galley and cook.
The software packages can be reduced in effectiveness or simply disabled.
Players should be able to choose which software packages are lost.
They may wish to preserve astrogation or gunnery over the entertainment system.

== Cargo Damage
The cargo hold and any elements related to cargo are damaged.
Cargo elements include storage capacity, contents, airlocks, cargo locks and more.
Contents include any cargo or personas in the cargo bay.

Major (decrease by 40%) damage from an attack delivering 42 HPS in damage hits the cargo bay.
The cargo airlock can only open to 60% of the previous opening.
All personas in the cargo area would take 42 HPS in damage. 
The damage would reduce the value of the Profulcinating Hygromodulators (TM) to 60% of previous. 

== Crew Damage
Crew damage is the most dangerous of all the damage locations.
Crew damage includes the crew's quarters and all crew presently within it.
Crew damage is the expedition killer of space vehicle combat.

Apart from the hapless crew in their quarters, the decrease in function reduces berths, food production, hygiene facilities, and entertainment.
For example, the number of televid channels may decrease from 100 to a mere 60.

== Defence Damage
Damage to defences reduces the effectiveness of the defensive system by the percentage indicated.
The defences decrease in effectiveness the same as any other damaged system.

=== Life Support Onion
Before damaging life support, the outer layers of the onion must be disabled or destroyed.
The outermost layer of the onion is the ship's shields. 
If the ship does not have shields, the outermost layer of the onion is the hull armour rating.
The hull armour rating must fail before the hull can be damaged.
The hull must fail before gravity control can be damaged.
Gravity control must fail before life support can be damaged.

include::ROOT:partial$CH38_Table_Life_Support_Chain.adoc[]

=== Life Support Damage
Life support keeps the personas comfy and alive within the spaceship.
Life support does not appear on the damage location table.
Life support is the most critical defence on a space vehicle.
Attacks cannot damage life support without first peeling back the life support onion.
A space vehicle must lose its shields, hull armour, hull and gravity before attacks can damage life support.
Attacks must destroy gravity control before life support is vulnerable.
Life support suffers damage the same as any other system once the onion is disabled.

=== Gravity Control Damage
Gravity control maintains life-saving, plot convenient gravity throughout the space vehicle.
Gravity cannot be damaged before the ship's hull is disabled.
Until the hull is disabled, the damage location of gravity control moves to the highest level of the life support onion.

The effectiveness of gravity control drops by the percentage indicated by the extent of damage roll.
Ineffective gravity control can lead to inconvenient ZOG, space sickness, and difficulty performing tasks.
If gravity control drops to less than 30%, the ship cannot safely make combat maneuvers.
Losing gravity is a victory condition.

=== Hull Armour Rating Damage
The hull armour rating represents the hardening of the space ship's hull to prevent combat damage.
Hull armour rating is part of the life support onion, and unless the space vehicle has shields, hull armour is the outermost layer.
Until the shields are disabled, the damage location of hull armour moves to the ship's shields.

NOTE: *Hull AR, Armour, and Armour Rating are interchangeable and separate from Hull.*

Armour Rating is an amalgam of many factors. 
Structurally it includes hull strength, combat hardening, and combat alterations.
Tactically is includes the ship's computer, ECM and drives.

==== Calculating Armour Damage
Sadly there are two ways to calculate the extent of damage to the armour rating.
The first simply uses the standard extent of damage drop in effectiveness.
An 800 armour rating that takes major damage (40% damage) drops to 480.
The lowest a space vehicle's armour rating can get is 420.
Once the armour rating is 420, the hull is vulnerable to attack.

The second is more complicated but allows armour rating to last a bit longer.
The drop in efficiency only affects the portion of the armour rating that is above 400.
An 800 armour rating would only drop the efficiency of the top 400 points of armour rating.
So a vessel with an Armour Rating of 800 taking major damage would have a new AR of 640.
Once the armour rating is 420, the hull is vulnerable to attack.

=== Defensive ECM Damage
Defensive ECM becomes reduced by the percentage indicated by the extent of damage.
ECM is a bit more resilient than other space vehicle systems.
Damaged defensive ECM can still function fully as attack ECM.
If the space vessel has two ECM systems, the attack ECM can replace the damaged defensive ECM, and the defence ECM can replace the damaged attack ECM.

=== Shield Damage 
Shields are the technomagical standard that indicates the health of a space vehicle.
The shields' effectiveness drops by the percentage indicated on the extent of damage roll.
Shields are immune to damage bonuses on the Extent of Damage Table.
If a shield could absorb 400 HPS damage and has sustained major damage (60%), it would only be able to absorb 240 HPS per attack until repaired.
The shield is disabled at <10% of capacity, and attacks on the shield move to the Hull AR.

=== Gun Damage
Gun damage represents damage to the airlock defence guns.
The gun's range and damage drop by the extent of damage indicated.
So an airlock gun that sustained major damage (40% damage) would have its range reduced by 60%, and each damage roll reduced by 60%.
A gun with a range of 100 hexes would now have a range of 60 hexes.
Every damage roll would be multiplied by 0.6.
A disabled gun stops working.

=== Active Damage
Active defences can look after themselves.
The active defence will get one chance to stop an attack from damaging the active defence system.
This active self-defence is an automatic counterattack regardless of recent activity.
Depleted active defences cannot defend themselves.
The active defence has its effectiveness reduced by the percentage indicated by the extent of damage.

== Attack Damage


=== Attack ECM Damage
Attack ECM effectiveness drops by the percentage indicated by the extent of damage.

=== Ramming Damage
Ramming success drops by the percentage indicated by the extent of damage.
The physical plant, sensors, and machinery of ramming become damaged.

Calculating this reduction in ramming effectiveness is a pain in the butt.
The player must make a successful pilot roll for a successful ramming attack.
Does one reduce the player's die roll by the extent of damage?
Does one increase the value that the player needs to beat?
Since ramming is such a blunt instrument, this referee prefers to ignore the graduated drop.
Ramming is either working or disabled. 

If the Ramming system is disabled, this space vehicle may no longer ram.
A space vehicle with disabled ramming capacity may still use the Boarding attack.

=== Artillery Damage
The artillery drops its range, and HPS damage by the extent of damage indicated.
Major damage drops the artillery to 60% of its previous effectiveness.
The artillery's range decreases from 500 to 300 hexes.
The artillery's area of effect decreases from 20 to 12 hexes.
Every damage roll would be multiplied by 0.6.
Disabled artillery stops working.

Instantaneously destroyed (reduced to <1% in one attack), artillery may explode inside the space vehicle.
Whether the artillery battery explodes in the ship or not should be decided by plot and sphincter dice.
An artillery explosion inside the ship delivers one location damage roll to the ship.

=== Boarding Damage
Boarding success drops by the percentage indicated by the extent of damage.
The physical plant, sensors, and machinery of ramming become damaged.

Calculating the reduction in boarding effectiveness is a pain in the butt.
The player must make a successful pilot roll for a successful boarding attack.
Does one reduce the player's die roll by the extent of damage?
Does one increase the target roll that the player needs to beat?
Often it is easier just to accept boarding is either operational or disabled. 

If the Boarding system is disabled, this space vehicle may no longer board.
A space vehicle with a disabled boarding capacity may still use the Ramming attack.

=== Grenades Damage
The number of grenade attacks drops by the amount indicated by the extent of damage.
This reduction in function impacts both mini-missiles and mini-mines.
The damage impairs the guidance systems and connectivity to the ship's computer.

The extent of damage decreases the number of mini-missiles and mini-mines deployable per turn. 
For example, a grenade system reduced to 60% could only drop six mini-mines instead of 10.

Instantaneously destroyed (reduced to <1% in one attack), grenades may explode inside the space vehicle.
Whether the grenade system explodes in the ship or not should be decided by plot and sphincter dice.
A grenade detonation inside the ship delivers one location damage roll to the ship.

=== Bombs Damage
The number of bomb attacks drops by the amount indicated by the extent of damage.
This reduction in function impacts both naval missiles and naval mines.
The damage impairs the guidance systems and connectivity to the ship's computer.

The extent of damage decreases the number of missiles and mines deployable per turn. 
For example, a bomb system reduced to 60% could only drop six mines instead of 10.

Instantaneously destroyed (reduced to <1% in one attack), bomb systems may explode inside the space vehicle.
Whether the bomb system explodes in the ship or not should be decided by plot and sphincter dice.
A bomb detonation inside the ship delivers two location damage rolls to the vessel.

The bomb delivery system is hardened for combat and is difficult to destroy.
There are no damage bonuses awarded on the Extent of Damage Table for the bomb delivery system.


=== Naval Artillery Damage
The naval artillery drops its range, and HPS damage by the extent of damage indicated.
Major damage drops naval artillery to 60% of its previous effectiveness.
The artillery's range decreases from 15000 to 9000 hexes.
The artillery's area of effect decreases from 200 to 120 hexes.
Every damage roll would be multiplied by 0.6.
Disabled artillery stops working.

Instantaneously destroyed naval artillery may explode inside the space vehicle.
Accidental detonation depends on the plot and Sphincter Dice.
Detonated naval artillery will inflict three damage rolls on itself.

The naval artillery system is hardened for combat and is difficult to destroy.
There are no damage bonuses awarded on the Extent of Damage Table for naval artillery.

== Ref's Own Table
The referee can use this opportunity to infuse drama and excitement into the campaign.
It is generally considered bad form to annihilate an expedition using the ref's own table.
Subjecting the personas to comedic or dramatic challenges that lead to their demise is fair game.

:art: police_space_craft.png
:width: 450px
:snark: Please have your driver's license ready.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of spaceship with police written in reverse on bow.

include::ROOT:partial$articulate.adoc[]

== Personas and Damage
Exatmo space vehicle combat is lethal.
Personas are fleas perched on battling elephants, squashable at any moment.
Players must be aware that space vehicle combat can kill personas in an instant.
Personas caught in damaged locations will undoubtedly feel the ship's pain as well.
Minor damage to a space vehicle may be lethal to the anthros, aliens and robots housed in the damaged location.
Nothing personas showering in the crew quarters are at risk of damage.
Mechanics working on the drives are at risk of damage.

Hull penetration is not the cause of persona damage.
Destructive forces are communicated into the damage location by shock waves, debris, and energy leaks. 
Most persona damage is delivered when they throw themselves around as the camera shakes.

Damage from a bomb or naval artillery will certainly annihilate any persona caught in the hit location.
A direct hit from naval artillery to the crew's quarters would end up in every persona dead.
As the hull armour deteriorates, the risk to crew members increases.

=== Persona Damage Mitigation by Hull Armour
.HPS Damage = Attack HPS - (Hull AR / 10)
****
110 HPS of damage against a Hull AR of 800 would deliver 30 HPS of damage to personas.
****

== Damage Reports
The ship's computer generates damage reports about the space vehicle's system.
For an accurate damage report, the ship must have intact defensive ECM or a specialized program.
ECM attacks can deceive a ship's computer to give false damage reports.
Without automated damage reports, personas need to run around the ship, figuring ship damage themselves.
They may notice that the exatmo drives suck or that the computer is now dumber.


To gather any damage report info from an opponent requires a successful attack ECM probe.
Some referees will keep all space vehicle damage behind the screen and only letting players know a bit.
Other groups will have the players keeping track of their own vessel's demise.

== Onboard Crew
The crew includes any persona that is onboard a space vehicle during combat.
They can lend their skills to assist the ship's computer or repair the damaged ship.
A combat turn lasts 30 units in EXP.
A combat turn is sufficient time for personas to have a lot of fun between combat events.
Personas are not able to assist with an attack and repair the ship simultaneously.

=== Attack Assist
Crew can help the ship's computer and combat systems improve the chances of success.
A mechanic with artillery skill two is assisting a level three computer.
This vocation/computer team makes artillery attacks like a level 5 computer.

If the space vehicle is flush with crew members, the computer can work with a research team to pile up bonuses.
Before a mechanic, a mercenary and a spie must form a research team before assisting the computer. 
Research teams are located xref:i-roll_playing_rules:CH14_Performance_Tables.adoc#_research_team_composition[somewhere in this book,window=_blank]. 

=== Ship Repairs
There is enough time during combat turns to accomplish ship repairs.
The goal of ship repairs is to return percentage points of efficiency and restore functionality.
Ship repairs are entirely under the purvey of the mechanic vocation.
The personas can form research teams depending on which system they are repairing.

These are not maintenance repairs. 
These are bubble gum and duct tape repairs to get through combat.
Most of these repairs will fall apart once combat ends.

NOTE: * Personas cannot repair destroyed systems during combat.*

For example, a mechanic attempts to repair the special drive by ten percentage points. 
This repair would be a 10 DD maneuver for the mechanic.
If she is successful, the special drive will move from 8% effectiveness (disabled) to 18% effectiveness.
This repairs the special drive moves from disabled to critically damaged.
While still critically damaged, the expedition special jumps to safety.

The mechanic could also repair an airlock from only opening 40% to opening 60%.
To repair this 20% deficiency would be a 20DD maneuver.
The repair allows the expedition's combot to join in on the boarding attack. 

== Convenience Table Co-Location

include::ROOT:partial$CH38_Table_Space_Vehicle_Damage_Location.adoc[]

include::ROOT:partial$CH38_Table_Extent_of_Space_Vehicle_Damage.adoc[]

include::ROOT:partial$CH38_Table_Extent_Damage_Descriptor.adoc[]
