= Inatmo Vehicle Combat

Inatmo vehicles are the atypical vehicles that one finds planetside.
This section covers using vehicles in the tactical combat system. 
Inatmo vehicle combat covers how to shoot from, shoot at, and destroy vehicles in battle. 
Inatmo vehicle combat is cinematic vehicle combat and is persona centered.
This section is for when lethal personal combat combines with driving.
Before destroying vehicles, you should learn how to create them first.
Jump to xref:iii-hardware:CH54_Vehicles.adoc[Inatmo Vehicle,window=_blank]. 

Inatmo vehicle combat works best for land-based combat.
These rules can accommodate air, water and submariner combat.
This section does not apply to combat taking place exterior to the atmosphere.
For space vehicle combat, jump  to xref::CH38_Space_Vehicle_Combat.adoc[Exatmo Vehicle Combat,window=_blank].

This section is *not* for expeditions driving from one place to another. 
This section is *not* for expeditions racing cars for fun.
This section is *not* for drivers who are behaving recklessly.
For non-combat driving shenanigans jump to  xref::CH17_Driving.adoc[Driving, window=_blank]. 

:art: vehicle_combat_trick_moves.png
:width: 450px
:snark: Seat belts please.
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of multilane flying car chase scene with guns akimbo.

include::ROOT:partial$articulate.adoc[]

== Vehicle Combat and the Hex Mat
Most vehicles will run out of tabletop hex mat in a unit or two.
Managing the high movement rates of vehicles in combat is a hex mat challenge.
A typical vehicle will cross an entire hex max in one combat unit. 
When using tokens and hexagons, full-speed vehicles just zip across the field.

Vehicle racing, or chasing, is another reason to keep track of vehicle location.
Car chases are fun.
If there are no persona tokens on the mat, try a smaller scale hex mat.
The smaller scale mat allows for high-speed maneuvers, movement and treacherous obstacles.
Regardless of the reason for tracking vehicles on a hex mat, they move like any other persona.
They just cover more hexes each unit and can have a collision if reckless.

Players with flying vehicles must keep track of their elevation. 
EXP is not responsible for misuse of the https://en.wikipedia.org/wiki/Pythagorean_theorem[Pythagorean theorem,window=_blank].

== Speed
A vehicle moving at twenty h/u or less is moving too slow for vehicle combat.
This movement rate works with the tactical system.
The vehicle becomes mobile cover or concealment and not something that requires a whole combat section. 

Vehicle combat is persona-focused and cinematic. 
The rule set is faux realistic and designed for dice-rolling fun.

.*Various Speeds*
* 1 h/u = 1 m/s
* 1 h/u = 3.6 kmh
* 1 h/u = 2.2 mph
* 10 h/u = fastest mundane terran
* 25 h/u = Gale force winds
* 28 h/u = 100 kmh
* 31 h/u = mundane terran spotted cat
* 45 h/u = 100 mph
* 80 h/u = speed of an arrow
* 342 h/u = Speed of sound

== Typical Use Cases
Inatmo vehicle combat is an extension of the tactical combat system. 
Attack rolls, movement, and damage parallel the tactical system.
The rule set here is for tactical combat, including moving vehicles.
The main challenge for vehicle combat is accommodating relative movement rates.
Inatmo combat focuses on the most common use cases that occur in vehicle combat.

NOTE: *Parked vehicles are just cover or concealment.*

.*Common Combat Situations*
* Attack roll at a moving vehicle (attacker essentially still)
* Attack roll from a moving vehicle (target essentially still)
* Attack roll between moving vehicles (attacker and target moving)
* Additional considerations

== Attack roll at a moving vehicle
The main challenge for the attacker is that their target is moving at high speed.
The persona launching the attack is relatively motionless, and only the movement rate of the vehicle applies.
The speed of the vehicle makes a successful attack roll more difficult.
The greater the speed differential, the harder it is to hit the target.
The speed of the vehicle determines its armour rating. 
Attacking a moving vehicle increases the target's Armour Rating.

=== Vehicle Armour Rating
.Vehicle AR = 500 + 10 per h/u 
****
AR = 500 + (30 h/u * 1) = 500 + 300 = 800.
****

== Attack roll from a moving vehicle
The main challenge for the attacker is that they are moving at high speed.
The speed of the vehicle makes it harder for the player to win the attack roll more difficult.

The target is relatively motionless, and only the movement rate of the vehicle applies.
The speed of the vehicle makes a successful attack roll more difficult.
The greater the speed differential, the harder it is to hit the target.
The speed of the vehicle creates an attack roll penalty. 

=== Attack Roll Speed Penalty
.Penalty = -15 per h/u of vehicle speed
****
Penalty = -15 * 30 h/u = -450. 
****

Attacking from a vehicle moving 25 h/u is equivalent to attacking through a gale-force wind.
Attacking from a vehicle moving 45 h/u is equivalent to attacking through 100 mph wind. 

== Attack roll between moving vehicles
The challenge for attackers includes speed differential, drag, vibration, and evasive maneuvers.
These conditions make a successful attack roll more difficult.
The greater the relative speed of the two vehicles, the more difficult it is to score a hit.
Attacking from high-speed vehicles is fraught with penalties. 
The attack roll speed penalty applies to both attackers. 

The following demonstrates the attack roll penalties between vehicle Eh going 30 h/u and vehicle Bee going 50 h/u

.*Attacks between moving vehicles*
. Attack Roll Speed Penalty
. Determine differential speed
. Armour Rating determined by speed differential.

=== Attack Roll Speed Penalty
.Penalty = -15 per h/u of vehicle speed
****
This penalty applies to both vehicles. +
Eh penalty = -15 * 30 h/u = -450.  +
Bee penalty = -15 * 50 h/u = -750
****

The drag, vibrations and high-velocity forces make it nearly impossible to win an attack roll from vehicle Bee.
The armour rating of the vehicle increases depending on the speed differential.

=== Speed Differential
.Differential = faster speed  - slower speed
****
differential = 50 h/u - 30 h/u = 20 h/u
****

=== Differential Armour Rating
.Vehicle AR = 500 + 10 per h/u differential
****
AR = 500 + (10 * 20) = 500 +300 = 700. +
Both vehicles have the same AR.
****

It is nearly impossible for attackers from the higher speed vehicle to attack the slower speed vehicle, but the reciprocal is not correct.

=== Combat Hardened
The base armour rating of 500 applies to an unarmoured civilian vehicle that has no combat hardening.
If the vehicle has an armour rating through combat hardening, that value becomes the base instead of 500.
A vehicle with an armour rating of 700 moving 30 h/u would have an armour rating of 1000.

=== Driving Skill and AR
Driving skill is not combat driving skill.
Driving skills and handling class will keep the vehicle from crashing during combat. 
A driver may attempt evasive maneuvers by making a Driving Roll.

Combat driving skills will increase the vehicle's moving AR by 50 per combat driving skill level.
Combat driving skill two increases the vehicle's base armour rating from 500 to 600. 

=== Flanking and AR
We do not bother with flanking in vehicle combat. 
There is no advantage to flanking when vehicles are entirely randomly created.
A vehicle's flank could be as forbidding as its bow.

== Damaging a Vehicle
A successful attack roll on a vehicle indicates damage.
Vehicles do not have hit points and are damaged differently from organic personas.
Vehicles have a random damage location like robots and space vehicles. 
The process of damaging a vehicle in combat has two steps.

. Location of Damage
.. targeting components
.. targeting passengers
. Extent of Damage

== Location of Vehicle Damage
Hitting the vehicle with a rock, bullet or lazer beam will damage a random location.
The premise of the random location is the same for all inorganic damage location charts.
The system damaged may be some distance from the damage point.
Ricochets, power surges and force distribution essentially make the damage location random.

include::ROOT:partial$CH17_Table_Location_of_Vehicle_Damage.adoc[]

=== Targeting Components
Players often want to "shoot out the tires" of a vehicle.
To even consider targeting specific components, the persona must have combat driving skills.
The persona must also be familiar with the vehicle.
She could be attacking her vehicle, or the vehicle is part of a fleet of well-known vehicles.

.*Targeting Specific Components*
. Combat Driving Skill
. Knowledge of vehicle
. Remaining Skilled Bonus

The remaining Skilled Bonus depends on the player's kilodie attack roll.
If the player's attack roll is 850 and the vehicle's armour rating is 800, her remaining Skilled Bonus is 50.
This value allows her to move the hit location on the vehicle up and down by 50 points. 
The remaining Skilled Bonus value cannot exceed the persona's Skilled Bonus for the weapon. 

=== Targeting Passengers
Players often want to "shoot the driver" of a vehicle.
This attack is a variation on targeting a component described above. 
The player can move the damage location to the crew cabin with whatever remaining Skilled Bonus she has.
Moving the damage location to the crew cabin allows her to make an attack roll on a selected passenger.

The player can then make an attack roll on the target persona. 
The player can only use the remaining remaining Skilled Bonus on her attack roll.
To "shoot the driver" requires two successful attack rolls.
If the player does not win her second attack roll, the attack misses, and the vehicle is not damaged.

== Extent of Damage
The extent of damage is determined randomly and modified by the hit points of the damage delivered.
Since vehicles and vehicle components don't have HPS, they suffer reduced efficiency when damaged.

include::ROOT:partial$CH21_Table_Artifact_Extent_of_Damage.adoc[]

The extent of damage is modified upwards by the HPS of damage inflicted on the system.
For example, 15 HPS of damage would increase the extent of damage roll by 15.
If the player rolls 08 on the 1d100 roll with 15 hit points of damage, she moves the extent of damage from Trivial to Minor.


=== Big HPS Big Damage
Referees may wish to adjust the amount of damage even further.
This rule is optional.
For every 75 HPS in damage, the attacker makes an additional extent of damage roll.
Thus a single attack that inflicts 230 HPs in damage to the vehicle would make three extent of damage rolls at +75 and one roll at +5.
A fusion grenade attack could damage every component on a vehicle and not just destroy a single component.

=== Effect of Damage
The extent of damage roll indicates the decrease in efficiency of the damaged part.
Major damage would decrease function by 40% from its previous efficiency.
The player calculates a  40% drop in efficiency by multiplying the existing efficiency by 0.6.
Major damage to a 30 h/u speed component reduces the maximum speed to 18 h/u.
Vehicle system damage is cumulative.

A vehicle component is disabled when reduced to 10% of its full performance.
From a practical standpoint, the mechanism may become useless long before it reaches 10% effectiveness.
The damaging effects of successful attacks are cumulative, and repeated attacks will destroy a component.

Any component destroyed by a single attack is damaged beyond repair.
If cumulative damage destroys a component, the repair is still possible.

== Driving Rolls
A driver may need to make a driving roll during combat.
The most obvious reason is that she takes damage during combat.
Severe system malfunctions can warrant a driving roll as well
To learn collision avoidance rules jump to  xref::CH17_Driving.adoc[Driving,window=_blank]. 

:art: lady_lazer.png
:width: 450px
:snark: Rear gunner.
:artist: Alex Schumberg
:date: 1948
:license: CC BY-SA 4.0
:description: Drawing of human woman firing lazer cannon through canopy of vehicle.

include::ROOT:partial$articulate.adoc[]

== Attack Types
The wind drag surrounding speeding vehicles has an enormous impact on every attack type.
The Attack Roll penalty for speed combines all the challenges into one faux realistic value. 

=== Strike Attacks
Nope.
Trying to use self-powered thrusting and striking weapons against a vehicle will result in a pedestrian collision for the attacker.

=== Fling Attacks
Fling attacks are self-powered projectile attacks.
When making an attack roll against a moving vehicle, the player may use a Fling attack.
Using Fling attacks from moving vehicles is usually not possible.
The attack roll penalty for speed effectively eliminates all Fling attacks from vehicles.
Arrows, axes, and shuriken cannot compete with the winds of high-speed vehicles.

=== Shoot, D, E, F Attacks
Powered projectile attacks use their mechanical, magical and energy forces to overcome vehicle combat.
These attack types are still subject to enormous penalties due to differentials, vibrations and wind drag.
Individual weapons may reduce the penalties applied due to the wind effect.
For example, a lazer or energy weapon is much less affected by air turbulence than a bullet. 

=== Area Attacks
Area weapons include grenades and aerosols.
Area of effect attacks must score a direct hit on the vehicle to damage the vehicle.
Typically Area weapons need only target a specific hex.
In vehicle combat the Area Attack Roll must beat the vehicle's speed-adjusted armour rating.

Due to the unique chemical nature of Aerosols, a successful attack roll will hit the vehicle.

=== Vehicle Weapons
These are bespoke combat accessories baked into the inatmo vehicle.
Vehicle weapons are generated during inatmo vehicle fabrication.
Built-in vehicular weapons use compensating gimbals, servos, and possibly software to improve high-speed combat.
These components significantly reduce the penalties suffered due to wind drag and speed differential.

.*Benefits of Baked in Bang Bangs*
. Moving Vehicle AR is 500 + 5 per h/u
. Attack Roll Penalty is -5 per h/u
. Attack Roll Penalty is 0 if the persona has vehicle combat skills.

=== Ramming
Ramming involves an intentional collision between two vehicles.
Or the intentional collision between a vehicle and a persona.
Mutual ramming happens automatically, and the vehicles and passengers are damaged.

.*Params of the Ram Rams*
. Ramming vehicle must be faster or
. Ramming vehicle has intercept path
. Ramming vehicle must make an Attack Roll
. Target vehicle can avoid with Driving Roll
. Collision result as per xref::CH17_Driving.adoc[Driving,window=_blank]

=== Boarding
Jumping onto a moving vehicle is fraught with risk.
Without special effects and camera speed adjustments, boarding is nearly impossible.
Nevertheless, players will want to have their personas board moving vehicles.

.*Params of Boarding*
. use the differential speed to Determine the Vehicle's AR
. The jump is considered a Strike attack
. Max speed is ten h/u plus DEX
. A miss counts as a pedestrian struck as per xref::CH17_Driving.adoc[Driving,window=_blank]