= Ambush

[quote]
____
A successful ambush gives the attackers several units of unanswered attack rolls.
____

An ambush aims to gain surprise on an opponent, and during the confusion, inflict as much damage as possible.
Ambush is an entirely combat-related event.
Ambush is not an all or none proposition.
Most ambushes will be partially successful, with part of the expedition ambushed and part not being ambushed.

:art: ambush_bunny_club.png
:width: 450px
:snark: Trophies come to the patient bunny.
:artist: Eric Hotz
:date: 1991
:license: CC BY-SA 4.0
:description: Mangy humanoid rabbit with a club of nails hiding behind a wall.
include::ROOT:partial$articulate.adoc[]

An ambush is a planned event.
Ambushes do not happen when two expeditions accidentally come across each other in the wasteland.
An ambush is different from initiative, and a successful trap allows the ambushers to bypass initiative altogether.

*Ambush Checklist*
. Ambush Detection
. Ambush Duration

== Ambush Detection
The personas targeted by the ambushers have a chance to detect the ambush and act normally during combat.
Personas that do not detect the ambush victims of the surprise attack.
The player must win an ambush Awareness roll to avoid being ambushed.
The Awareness roll becomes more difficult the better prepared the ambushers are.
To learn how to make an awareness roll jump to xref:roll_playing_system:CH16_Special_Rolls_Attributes.adoc[Attribute Rolls,window=_blank].

include::combat:partial$ambush_detection.adoc[]

=== Detection Timing
Timing of ambush detection is critical.
The difficulty of the ambush determines how much warning the expedition gets.
Advanced warning will allow the personas to alert each other to the impending attack, completely negating the ambush.
The timing of ambush detection depends on the difficulty of the ambush.

Trivial and Easy Difficulty::
Personas that detect the ambush will have time to warn other members of the expedition.
Early detection will not only negate the ambush but may allow for a counterattack.

Normal Difficulty::
Normal ambush detection occurs at the last instant, and the referee decides if there is an opportunity to alert other personas.
Personas with ambush detection abilities (like avarians) may allow for advanced ambush detection.
If the expedition is actively moving stealthily to avoid ambush, the referee may allow for timely ambush detection.

Tough, Impossible and Bizarre Difficulty::
These are professional, naturally evolved and electromechanical ambushes.
Only personas that detect the ambush can react.
There is no chance to alert other personas, and carnage will likely ensue.

== Ambush  Duration
The effect of an ambush is to create confusion within the ambushed targets.
The result of this confusion leaves some of the ambushees unable to move, attack or act. 
This oblivious behaviour can last up to three excruciatingly long combat units.
The ambushers get to make unanswered attacks and moves against those who did not detect the ambush.

:art: ambush_robot.png
:width: 450px
:snark: What? Huh?
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Robot leaping onto a humanoid from behind.
include::ROOT:partial$articulate.adoc[]

Those personas not ambushed (whose players won the Awareness roll) combat begins with a typical initiative roll.
Those personas ambushed (whose players lost the Awareness roll) cannot move, attack or act. 
Ambushed personas maintain their Defence Rating but are sitting ducks.

include::combat:partial$ambush_effects.adoc[]

== Anatomy Of An Ambush 
Let's consider a rather intelligent herd of indigenous life forms that have prepared an ambush for an unsuspecting expedition.
The ambushers are well organized and indigenous.
Each persona must make an improbably (1d100) Ambush Detection Roll.
Detecting this ambush will be at the last instant, and there is no opportunity to warn the rest of the expedition.

The expedition consists of four personas Abel, Babel, Cable and Dabel.
Abel is a feline, and her player wins the improbable (1d100) Ambush Detection Roll.
The remaining personas will suffer the effects of an ambush.
How long they remain ambushed depends on Awareness and Dexterity rolls.

include::combat:partial$ambush_anatomy.adoc[]

:art: ambush_van_raptors.png
:width: 450px
:snark: The vanguard of guarding vans.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Pair of velociraptors bursting out from back of van with two surprised pre-dinner meatbags.
include::ROOT:partial$articulate.adoc[]

=== First Unit
The aliens attack the expedition.
The only combatants that can act are the ambushing aliens and Abel.
Abel joins the aliens, making initiative rolls.
Babel, Cable and Dabel do not join the initiative and don't know what is happening.
They are sitting meat bags.
They are not defenceless, and their Defence Rating is unchanged, but they cannot move nor attack in response.
The aliens, and Abel, get to make attack rolls and move.

=== Second Unit
Before making the init order, the ambushed personas have a chance to notice what is going on.
The players running Babel, Cable and Dabel must win a normal (1d20) Awareness roll *and* Dexterity roll to join into combat.
Only Babel's player wins both these rolls, and she can make an initiative roll this unit.

So now, initiative and combat include the aliens, Abel and Babel.
Cable and Dabel remain oblivious meat sacks unable to attack or move.

=== Third Unit
Before making the init order, the ambushed personas have a chance to notice what is going on.
The player running Dabel must win a normal (1d20) Awareness roll *or* Dexterity roll to join into combat.
Sadly for Dabel, her player fails both these attribute rolls.

So now, initiative and combat include the aliens, Abel, Babel and Cable.
Dabel may prove to be a spectator at her funeral.

== Fourth Unit
The pain for the ambushed personas has ended.
All personas still standing can join into combat.
Thankfully Dabel managed to survive the alien attacks and has regained situational Awareness.



