= Attack Roll Adjustments

Attack roll adjustments affect the player's chance of successfully damaging targets.
Combat adjustments are added or subtracted from the player's kilodie attack roll.
These adjustments are most often penalties that impair ranged attacks by obscuring targets.  
Obfuscating impediments include weather, cover, concealment, range, and firing blind.

== Defence Rating
Attack roll adjustments do not change the target's Defence Rating. 
For example, a target may have 90% cover from one direction and no cover from another direction.

== Attack Tables
Attack roll adjustments do not affect the persona's attack table.
The persona's Skilled Bonus (Skilled) and Max Roll (Max) remain the same.
A skilled persona with a high Skilled Bonus can overcome weather and range penalties.

The player subtracts the attack roll penalty from her kilodie roll.
The player adds the attack roll bonus to her final attack roll.
So a bonus can allow a persona to exceed her Max Roll (Max).

Thus a rear attack (+90 attack roll) with a club could allow the player to surpass her persona'sMax (Max Roll) and possibly hit a previously impervious target.

A payer with a Max Roll (Max) of 763 is making an attack roll against an Defence Rating (DEF) of 793.
Under normal circumstances, the persona could not hit the target because her Max Roll (Max) is too low.
However, the rear attack bonus of +90 adjusts the final attack roll upwards by 90.
The final attack roll could be as high as 883 (Max of 793 plus 90), making a successful attack roll possible.

This method of administering attack roll bonuses is blatantly biased towards the players.
There is no justifiable reason for players to be excluded from combat because their persona has an inadequate Max Roll (Max).
Attack roll bonuses allow the player to gain a chance attack roll a target through ingenious, or experienced, tactics.

== Weather Conditions
Weather conditions affect the attack rolls of ranged weapons.
There are no snow or rain effects on hand-to-hand combat (Strike attacks).
Grenades are affected by weather conditions, while aerosols are not.

:art: combat_adjustments_insect_smoke.png
:width: 450px
:snark: Through rain and sleet and smoke.
:artist: Eric Hotz
:date: 1991
:license: CC BY-SA 4.0
:description: Humanoid insect and humanoid in smoke filled frame.
include::ROOT:partial$articulate.adoc[]

Most of the weather penalties are per hex of range.
For example, shooting a gun through thick smoke at a target ten hexes away is a -600 attack roll penalty.
All personas on the hex mat are suffering the same attack roll penalty.
If a penalty is large enough, it is equivalent to firing blind. 

Minimal weather penalties should only apply to important attack rolls.
For example, a persona may be attempting a long-range scope shot on a referee persona. 
In this case, the success of the attack roll could be affected by a -4 penalty.
Exciting!

// insert table 346
include::combat:partial$attack_adjustment_rain.adoc[]

// insert table 347
include::combat:partial$attack_adjustment_hail.adoc[]

// insert table 348
include::combat:partial$attack_adjustment_sand.adoc[]

// insert table 349
include::combat:partial$attack_adjustment_wind.adoc[]

// insert table 350
include::combat:partial$attack_adjustment_smog.adoc[]

// insert table 351
include::combat:partial$attack_adjustment_dark.adoc[]

// insert table 352
include::combat:partial$attack_adjustment_snow.adoc[]

// insert table 353
include::combat:partial$attack_adjustment_hig.adoc[]

== Cover and Concealment
Cover and concealment create attack roll penalties that depend on how the target is hiding.
Cover and concealment penalties apply to ranged attacks only (Attack types B, C, D, E, and F).
Cover and concealment attack roll penalties do not change the target's Defence Rating. 
For example, a target may have 90% cover from one direction and no cover from another direction.

:art: dinner_in_a_tube.png
:width: 450px
:snark: Dinner has own tooth pick.
:artist: Louis Glanzman
:date: 1954
:license: CC BY-SA 4.0
:description: Humanoid trapped in cave by big mouthed dinosaur.
include::ROOT:partial$articulate.adoc[]

Cover and concealment are entirely different. 
Cover protects the target from incoming projectiles.
Concealment hides the target from incoming projectiles.
If a player continues to attack a wholly hidden target, they are firing blind.

An attacker can transform cover to concealment if by using a different weapon.

=== Aliens
The referee must decide cover and concealment penalties for aliens on a case-by-case basis.
Some aliens are simply too big to hide.
The referee may have milieu-specific variations. 

:art: space_bug_big.png
:width: 450px
:snark: You can hit me, not hurt me.
:artist: Wallace Saaty
:date: 1941
:license: CC BY-SA 4.0
:description: Rollercoaster-sized alien being bothered by army, police and crowd.
include::ROOT:partial$articulate.adoc[]

For large, medium, small and tiny aliens, cover and concealment work the same as for anthros.
For gigantic aliens, cover and concealment are virtually impossible.
The referee should reserve cover and concealment for tool using aliens and those with natural ranged attacks.
Partial hiding is not in the purvey of flora and fauna. 

=== Robots
The referee must decide cover and concealment penalties for robots on a case-by-case basis.
Some robots are simply too big to hide.
The referee may have milieu-specific variations. 

For medium, small and tiny robots, cover and concealment work the same as for anthros.
For large and gigantic robots, cover and concealment are virtually impossible.
Cover and concealment are very tactical should be limited to combots.

=== Cover 
Cover is when a persona places a solid barrier between herself and the attacker's weapon.
Typical cover includes rocks, tree trunks, hills, and corners of buildings.
Cover will stop a bullet, lazer bolt or arrow in its tracks. 
If discussion about whether a feature offers cover or concealment becomes intense consult the xref:uncombat:sphincter_rolls.adoc[Sphincter Roll,window=_blank].
The more cover that a target has, the greater the attack roll penalty.

=== Concealment 
Concealment is when a persona places an obscuring barrier between herself and the attacker's weapon.
Typical concealment includes bushes, tents, drywall, and sheets on a clothesline.
A bullet, lazer bolt, or arrow can pass through concealment.
If discussion about whether a feature offers cover or concealment becomes intense consult the xref:uncombat:sphincter_rolls.adoc[Sphincter Roll,window=_blank].
The more concealment that a target has, the greater the attack roll penalty.
Concealment attack roll penalties are much lower than cover attack roll penalties.

include::combat:partial$defence_cover_concealment.adoc[]

=== Example 
If a target has 90% cover (a concrete bunker), there is a -450 attack roll penalty.
If a target has 90% concealment (a scruffy bush), there is a -80 attack roll penalty.
The attacker has an idea where the target is with cover (bunker), but she must win an attack roll against the smaller target.
The attacker has an idea where the target is with concealment (bushes) and can guess where she should target.

If an attacker were to switch weapons, then she can reduce cover to concealment. 
What might be cover for an arrow may not be cover for an extra high-powered rifle. 

== Firing Blind
Firing blind refers to attacks made against targets that are not visible.
The attacker may have an idea where the target is, but the target has 100% concealment.
Firing blind applies if the target is unseen due to smoke, blindness, invisibility, or tear gas.
Firing blind does not apply to target's with 100% cover.

Firing blind is limited to projectile weapons (Types B, C, D, E, and F).
The projectile must be able to penetrate the concealment. 
Contact attacks (Strike) and area of effect weapons are not part of the firing blind ruleset.

Firing blind is mostly luck.
The attacker suspects a target is behind some concealment. 
They cannot aim at the specific target, so they fire into the concealment.
This concealment could be bushes, drywall, or dense smoke.
After firing into the concealment, the persona may find a dead body, wounded alien or nothing at all in the bushes.
That is the fog of war.

To maintain the mystery of firing blind, the referee may request the player roll damage after every attack roll.
This deception helps maintain the secrecy of the hidden.

include::combat:partial$firing_blind_long_title.adoc[]

== Range Penalties
The range is the number of hexes between the attacker and the target.
The first hex is the one immediately in front of the attacker, and the last hex is the one containing the target.
Thus a target on an adjacent hex would be one hex away.

:art: Figure_range_examples.png
:width: 450px
:snark: Not an oven range.
:artist: hexes Pixabay. Colour HM
:date: 2020
:license: CC BY-SA 4.0
:description: Diagram showing range penalties using hexagon sheet.

include::ROOT:partial$articulate.adoc[]

There are no range penalties if the target is within the maximum range of the attack.
Maximum ranges vary by weapon construction, tentacle length and robot Strength.
The range attack roll penalties are per hex penalties applied per hex beyond the attack's range.

== Movement Penalties
A persona can use their entire movement rate per unit without penalty.
Movement Rate is the designated amount that a persona can move during a combat unit. 
There are some movement choices that the player can make that affect attack rolls.

=== Movement Differential
When the attacker and the target are moving at vastly different speeds, there is an attack roll penalty.
This attack roll penalty is for massive movement rate differentials, like those created by a vehicle. 

Movement penalties do not apply to natural combat movement rates.
For example, a super-fast alien would only suffer a movement penalty if she were in a moving vehicle.
Her natural movement rate would never cause an attack roll penalty.

The difference in movement rate must be greater than ten h/u. 
There is a -10 attack roll penalty per h/u difference in movement rate. 

=== Differential Movement Rate Attack Roll Penalty
.penalty = -10 per h/u difference.
****
Penalty = 50 h/u (in a jeep) - 10 h/u (running away) = 40 h/u difference = -400 attack roll penalty.
****


== Flanking Bonuses
Many roleplaying games give bonuses for flanking a target.
Flanking only applies to anthro-shaped targets that do not have eyes on the back of their heads.
Flanking a target only benefits Strike attacks. 
There are no flanking bonuses for projectile or area of effect weapons. 
The player has an attack roll bonus of +90 when attacking from behind and +60 when attacking a rear flank.
The persona cannot earn flanking bonuses by simply maneuvering around her target.
The target must be unable to turn or be occupied by something other than the attacker.

== Penalties vs Defence
EXP cannot decide whether adjustments should count as penalties on the attack roll or bonuses to the defence rating. 
Consider a penalty of 100 points against hitting a target in a rain storm.
This is supposed to reflect the difficulty of making a successful to hit roll on a target in the rain.
One could subtract 100 from the player's attack roll, or one could add 100 to the target's defence rating. 
Both would make the chance of success 100 point more difficult. 

WARNING: This section is full on RPG rule nerdism. 

When the penalty acts on the attack roll it is possible to get a negative attack roll. 
Even though the minimal roll in the tactical combat system is 001 this still seems dirty.
When the penalty is added to the defence rating of the target this feels more elegant.
The attack roll is untainted and the target is harder to hit.

However changing the defence rating of the target may push it beyond the persona's maximum roll.
So the chance of a scoring a hit with the attack roll is left to a critical check. 

|===

5+<|DEF 742, Penalty 150

|Vocation   |Skilled |Max |new DEF |new Skilled
|Mercenary  |242     |842 |892     |108

3+>|Hit Chance
|1% crit only
|35% decent roll

|Nothing
|42
|842
|892
|-108

3+>|Hit Chance
|1% crit only
|1% crit only

5+<|Minimum attack roll is 001
5+<|Adding penalty to attack roll respects combat skills
|===




== Further Points
Take all these adjustments with a tablespoon of salt.
The attack roll adjustments are part of the faux realistic tactical combat rules.
The attack roll adjustments in this section are the basics that cover the most common situations. 
Players will find themselves in situations not listed here.
The referee and players will negotiate a ruling that seems fair.
If negotiation is not successful, remember the xref:uncombat:sphincter_rolls.adoc[Sphincter Roll,window=_blank].

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

