= Attack Types

[quote]
____
*Sticks and stones may break my bones. A fusion pistol roasts me.*
____

An attack is any action where a persona attempts to injure another persona.
This section focuses on attacks where the persona is trying to injure the target persona physically.
The attack types detailed here include weapons, body parts, and explosions. 
The section does not detail attack types like psionics, poisons, or bullying.

== Attack Types
Attack types divide the widely various methods of killing off personas into a few basic groups. 
Attack types separate based on damage mechanism, frequency of attack, and range. 
An attack type can include weapons, alien attacks and misused robot peripherals.

Each persona deploys each attack type differently depending on their family and vocation.
These personalized differences are in the xref:combat:attack_table_details.adoc[Attack Table,window=_blank] section.

include::combat:partial$attack_types_details.adoc[]

== Strike Attacks
*Non-powered thrusting and striking attacks*

Strike Attacks depend on the persona's muscle power to inflict damage. 
The persona must be in an adjacent hex to make an attack roll.
Strike attacks get one attack roll per unit.

An anthro could use a weapon like a sword or an axe. 
An alien could use a natural attack like a bite or a talon slash.
A robot could use a malfunctioning peripheral that operates as a club.

=== Strike Weapons
These are non-powered thrusting and striking weapons.
Strike weapons are handheld but can include the hand itself.
Strike weapons include swords, maces, pole-arms, fists, paws, beaks, spears, etc.
They are close combat weapons, and the target must be in the persona's hex or an adjacent hex.

include::hardware:partial$mundane_strike_weapons.adoc[]

Length::
Self-explanatory.

Wate::
Self-explanatory.

Defence Rating Bonus::
If the persona has proficiency with the weapon, she can add an AR bonus.
The Defence Rating bonus only applies when the persona is using the weapon in combat.
The player multiplies the AR Bonus by the persona's Dexterity score and adds it to her Defence Rating.

Damage::
Damage indicates how many hit points the weapon removes from the target's hit points.
The player adds one half her Strength Attribute as a Force Bonus to her damage roll.

=== Multiple Attacks
Under certain circumstances a persona can have multiple Strike Attacks per unit.
An alien may have multiple tentacles with which to slap.
A robot may have multiple pointy things with which to stab.
A mercenary can split their Skilled Strike Attack Bonus amongst several attacks per unit.
A spie may have multiple martial arts attacks per unit. 
There is no special nomenclature for having multiple Strike Attacks per unit. 

== Fling Attacks
*Non-powered projectile attacks*

Fling attacks depend on the persona's dexterity to hit a target, and on the persona's strength to inflict damage.
The personas may be several hexes apart and still be able to damage each other. 
Fling attacks get one attack roll per unit.

An anthro would use a weapon like a bow or a sling. 
An alien may have evolved natural attack like spitting rocks or flinging quills.
A robot could use a malfunctioning peripheral that throw used batteries.

=== Fling Weapons
These are non-powered projectile weapons.
Fling weapons include rocks, daggers, boomerangs, whips, spitting, arrows, darts, etc.
Fling weapons are not close combat weapons, and there must be at least one hex between the persona and her target.

include::hardware:partial$mundane_fling_weapons.adoc[]

Length::
Self-explanatory.

Wate::
Self-explanatory.

Range::
The range represents how many hexes the weapon can fly true.
There are no attack roll penalties within the weapon's range.
Beyond the range, the weapon becomes much less accurate. 

Decay::
When attacking a target beyond the weapon's range, the attack roll suffers decay penalties.
The player subtracts the decay from the attack roll for every hex beyond the weapon's range. 
For example, an axe thrown ten hexes would have no penalties.
The same axe thrown 16 hexes would have a -600 penalty.

Damage::
Damage indicates how many hit points the weapon removes from the target's hit points.
The player adds one quarter her Strength Attribute as a Force Bonus to her damage roll.

:art: cow_moose_antlers_both_front.png
:width: 350px
:snark: Really Cool Moose Police
:artist: unknown, Helen Field, HM
:date: 1948, Unknown, 2018
:license: CC BY-SA 4.0 (sheriff), Helen Field Stock Art (moose)
:description: Humanoid moose wearing a rcmp hat and holding two six shooters.
include::ROOT:partial$articulate.adoc[]

=== Multiple Attacks
Under certain circumstances a persona can have multiple Fling Attacks per unit.
An alien may be able spit more than one crystal spore per unit. 
Multiple alien Fling Attacks arise from evolutionary process and are natural to the being.
A robot may have multiple levers that allow it to pitch batteries and silicon chunks at their foe.
A mercenary can split their Skilled Fling Attack Bonus between 2 arrow attacks per unit, but this is rare thing.
There is no special nomenclature for having multiple Fling Attacks per unit. 

== Shoot Attacks
*Powered projectile attack*

Shoot Attacks do not require any muscle power from the persona.
The persona uses her intelligence and dexterity to guide the attack 
The attack supplies its own energy to reach the target and inflict damage.
The personas can be many hexes apart and still be able to damage each other. 
Shoot attacks are limited to once per combat unit. 
Examples are bullets, laser bolts, energy beams, and crossbow bolts.

An anthro could use a weapon like a gun or a lazer.
An alien could have evolved lazer eyes or gas propelled bone chunks.
A robot could have an actual baked-in gun or be misusing a construction nail gun.

=== Shoot Weapons
These are powered weapons.
Shoot weapons are the classic guns and lazer weapons from sciency fiction and action movies including lasers, crossbows, rifles, fusion guns, death rays, machine pistols, etc.
They are typical artifacts from the Hardware section of EXP. 
Exotic, dangerous tech weapons are described in xref:hardware:CH46_Guns.adoc[Guns,window=_blank].
Mundane Shoot Type Weapons are listed below. 

include::hardware:partial$mundane_shoot_weapons.adoc[]

Length::
Self-explanatory.

Wate::
Self-explanatory.

Range::
The range represents how many hexes the weapon can fly true.
There are no attack roll penalties within the weapon's range.
Beyond the range, the weapon becomes much less accurate. 

Decay::
When attacking a target beyond the weapon's range, the attack roll suffers decay penalties.
The player subtracts the decay from the attack roll for every hex beyond the weapon's range. 
For example, a small crossbow at a ten hex range would have no penalties.
The same small crossbow at 28 hexes would have a -375 attack roll penalty.

Damage::
Damage indicates how many hit points the weapon removes from the target's hit points.
There are no Strength adjustments for Shoot weapons.

=== Multiple Attacks
Typically Shoot Attacks are limited to one Attack Roll per unit. 
Due to their powered nature Shoot Attacks commonly have multiple attacks per unit.
A robot or alien with multiple Shoot Attacks per unit simply enjoys that many attack rolls per unit.

Weapons with multiple attacks allow anthros (or any other persona kind using them) to make multiple Attack Rolls per unit.
These weapons have special names and rules attached to them.
A semi-automatic weapon is called a Sotto Type Weapon. 
A full-automatic weapon is called a Flotto Type Weapon.
The Sotto and Flotto weapons are both sub types of Shoot Weapons.

=== Sotto Attacks
*Semi-automatic powered projectile attacks*

Semi-automatic weapons allow the player to make multiple attack rolls per unit using her full Skilled Shoot Bonus. 
Sotto is a portmanteau of semi and auto. 
The weapon allows the player to make 2 or 3 attack rolls with the weapon per unit. 
Weapons that attack twice per unit have names like Sotto-2 or Shoot-2.
Weapons that attack thrice per unit have names like Sotto-3 or Shoot-3.
Sotto weapons are usually artifact weapons found in the xref:hardware:CH46_Guns.adoc[Guns,window=_blank] section.

=== Flotto Attacks
*Full-automatic powered projectile attacks.*

Full-automatic weapons allow the player to make hose down her target with bullets or lazer bolts.
Flotto is a portmanteau of full and auto. 
Flotto attacks function use the persona's Skilled Shoot Bonus, and make 5 Attack Rolls per unit.
A machine gun that releases a hail of bullets with the pull of a trigger is the most iconic Flotto attack.
Flotto weapons are usually artifact weapons found in the xref:hardware:CH46_Guns.adoc[Guns,window=_blank] section.

.*How to Flotto*
. Player makes 5 attack rolls 
. Each successful attack roll is considered a "hit"
. Each hit will deliver 0-3 (1d4-1) rounds of damage
. The player rolls damage for each round of damage
. Typically the target is destroyed

The player will makes five Attack Rolls each unit when using a Flotto weapon.
The player adds her persona's appropriate Shoot Bonus to each attack roll.
Each attack roll represents a random number of ammo rounds (bullets, lazer bolts, etc.).
For each successful attack roll anywhere from 0-3 rounds (1d4-1) damage the target.
While extremely unlikely, it is possible to win five attack rolls and land zero rounds on the target. 
Each attack roll expends 15 rounds of ammunition.

NOTE: Only a mercenary with flotto skill can "spread" the attack rolls between different targets.

.*A detailed example*
A persona fires her medium-powered full auto lazer pistol at a target. 
A medium-powered full auto lazer pistol inflicts 2-20 (2d10) hit points of damage per lazer bolt (round).
The player makes five attack rolls on the target. 
Since she is unskilled with lazer rifles she adds her Raw Shoot Bonus to each attack roll.
Three of the attack rolls are successful, two of the attack rolls fail.
The player will then roll 1d4-1 three times to see how many lazer bolts (rounds) damage the target. 
The player rolls 2, 0, 3 indicating 5 rounds hitting the target.
The target will suffer 10d10 hit points of damage. 
The weapon discharges 15 rounds of ammunition regardless.

== Area Attacks
*Area of effect attacks*

An area of effect attack covers a predetermined area of combat with effect (usually damage).
Typically all targets in the area are affected by the attack regardless of Defence. 
Most often an area of effect weapons delivers damage via hit point removal, but special effects can also be delivered by Area Attacks.
A frag grenade obviously deals damage via an explosion, but a sleeping gas aerosol may make the targets fall asleep

When the player makes an Attack Roll with an Area Weapon she makes an Attack Roll against a location and *not* a target's Defence.
The Attack Roll is made against a target hexagon on the combat field and does *not* consider the Defense ratings of any of the personas in the area of effect.

The player targets a specific hex for the Area Attack.
The Attack Roll determines if she hits to desired hexagon.
Everything else is determined by the mechanics of the Area Attack
The player must win an attack roll versus AR 600 to have her persona's area of effect weapon land where she wants.
Every persona in the area of effect is damaged.
There is no saving throw.
For more explosive details on Area Attacks there is a whole section at:  
xref:roll_playing_system:CH30_Area_of_Effect_Weapons.adoc[Area of Effect,window=_blank].

NOTE: a static hexagon has a Defense of 542

// fix area attack hexagon defense is 542

=== Area Weapons
Most Area Attacks are weapons like xref:hardware:CH45_Grenades.adoc[Grenades,window=_blank] or
xref:hardware:CH43_Aerosols.adoc[Aerosols,window=_blank].
An alien or robot can have a Area Attack.
Below are the mundane area of effect weapons.
Mundane Area Attacks function as Fling attacks.

include::ROOT:partial$CH28_Table_Type_AOE_Data.adoc[]

Wate::
Self-explanatory.

Range::
The range of mundane grenades is equal to one hex per point of Strength.
A persona with a Strength of ten could aim at a target ten hexes away. 

Radius::
Mundane area of effect weapons are unpredictable.
The player must roll the radius of effect each time one detonates.
An radius of zero indicates only the target hex is damaged.
The other hex values are the radius of the damage.

Roll::
What dice to use to generate the radius of effect.

Damage::
Damage indicates how many hit points the weapon removes from the target's hit points.
There are no Strength adjustments for Area weapons.

=== Grenade Attacks
*Self powered area of affect attack*

A grenade is a self contained Area Attack that is aimed at a target hex. 
The hex where the grenade lands is the epicenter of the Area Attack
The grenade goes off and the mechanics of the grenade determine the effect and the area.
The player adds the Fling Bonus, excluding the Force Bonus, to the Attack Roll when throwing a Grenade Area Weapon.
If the persona is using a grenade launcher type weapon the player adds the Shoot Bonus to her Attack Roll. 
Irregardless of using Fling or Shoot the target is a hexagon with a defence of 542.

To find out what happens if you miss go to:  
xref:roll_playing_system:CH30_Area_of_Effect_Weapons.adoc[Area of Effect,window=_blank].

=== Aerosol Attacks
*Automated area of affect attack*

An aerosol is a self contained Area Attack that instantly occupies a specified area of effect. 
An aerosol does not have an epicenter and can have a very oddly shaped area of effect
The aerosol is triggered and the mechanics of the aerosol determine the effect and the area.
The effect is automatic and no Attack Roll needs to be made.

Some aerosols require a target hexagon to establish an epicenter.
The player adds the Shoot Bonus to her Attack Roll if the aerosol requires a target hex. 
The hexagon has a defence of 542.

To find out what happens if you miss go to:  
xref:roll_playing_system:CH30_Area_of_Effect_Weapons.adoc[Area of Effect,window=_blank].

== Psionic Attacks
*Mind powered attacks with various effects*

Psionic attacks are listed here to keep EXP grounded in its sciency fiction roots.
A Psionic Attack Type arises from an anthro mutation, and alien evolutation or a robot malfunctation that gives unique powers to the persona.
Mutations can be which can be psionic or phenomic. 
Phenomic mutations are physical in nature and use existing attack types like Strike, Fling, Shoot or Area.
Psionic mutations can be used instantly by the persona, travel across imaginary planes of existence, and are only limited by the mutations description.


