= Robot Combat

Robot combat is a legacy section.
Robots are just another persona in the tactical combat rules. 
There are more similarities than differences.

:art: aikidobot.png
:width: 450px
:snark: Cyber sense say.
:artist: Patrick Redding
:date: 1990
:license: CC BY-SA 4.0
:description: Martial arts skilled humanoid robot throwing two humans at once.
include::ROOT:partial$articulate.adoc[]

== Points to Ponder on Robot Combat

. Combat is an internal computational struggle.
.. xref:robots:control_factor.adoc[Control Factor,window=_blank] rolls may be required.
. Robots may have a fabricator type that they protect.
. Skilled Bonus is only for baked-in bespoke weapons.
.. Raw Bonus is used for misused peripherals. 
. Ramming is different from ramming skill.
.. Ramming attack is required to use the Skilled Bonus.
. Robot Defence Rating is 700 unless hardened by defences.
. Electrical and disintegration attacks inflict double damage.
. A robot is neither destroyed nor unconscious a zero HPS.
.. Demolition tables are complex and fun.
.. Robot free will increases with malfunction and damage.
. Robots can be defeated by means other than violence.

== Fabricator Type
The relationship between a robot and her fabricator type is fluid at the best of times.
There are no https://en.wikipedia.org/wiki/Isaac_Asimov[Asimovian] three rules in EXP.
Robots cannot easily engage in combat with their fabricator type.
For a robot to intentionally harm a persona from her fabricator type would require a xref:robots:control_factor.adoc[Control Factor,window=_blank] Roll.

A robot may destroy an entire expedition and leave the anthro of her fabricator type unharmed.
Robots cannot be easily convinced or easily tricked to attack their fabricator type.
Not harming one's fabricator type is a soft rule.
The rule represents more of an internal struggle than a priority command.

The referee should not weaponize fabricator type against robot personas.
A referee persona robot may allow personas from her fabricator type to smash her into bits.
A player persona robot can run away, immobilize attackers, or even fight back if a control factor roll is successful.

:art: commercial_janitorial.png
:width: 450px
:snark: I just cleaned that!
:artist: Andrew Brechin
:date: 1990
:license: CC BY-SA 4.0
:description: Angry janitorial robot waving a broom at a human who messed up the floor.
include::ROOT:partial$articulate.adoc[]

== Priority Commands
Priority commands are specialized attacks made by mechanics with robot skills.
Strangely worded commands can *immobilize a robot* by creating logical dilemmas within its reasoning circuitry.
Priority commands are the robot's version of a mental attack on the robot's circuitry.

The robot will suffer debilitating effects for the length of time 1 to 100 units in duration.
While this duration appears short, this is a tactical combat maneuver, and 1d100 units a lot of combat time.
Priority commands may slow the robot to move at half speed, ignore a particular weapon, or forget how to turn left.
The referee and the players negotiate the effect of the priority command. 

include::robots:partial$malfunction_location.adoc[]

The higher the robot's control factor, the more difficult it is for a priority command to be successful.
The Degree of Difficulty (DD) of such a priority command is equal to the robot's CF. 
Referees will often have priority commands prepared for their robot referee personas.
Scenario-related priority commands can come along with clues found in the milieu of the game.

== Robot Overrides
Robotic overrides are specialized attacks made by mechanics with robot skills.
Robotic overrides can involve strangely worded commands, and mechanical interventions may allow the mechanic to *control the robot*.
There are even specialized artifacts that assist robot override. 

Robotic overrides are like a mental attack on the robot's malfunctioning free will. 
Successful robot override turns temporarily turns control of the robot over to the attacking mechanic.
A robotic override would be devastating to a player persona robot.
Control lasts 1-100 minutes (1d100).
The override can end abruptly, freeing the robot to exact revenge. 
The minimum Task Roll DD (degree of difficulty) should be 2 DD per point of Control Factor. 

Robotic overrides on powerful plot-related robots may require missions to acquire the needed tech and knowledge.

== Ramming
A robot may smash itself into a target with the full intent of inflicting damage.
If the robot can cross paths with a target on the hex mat, the player can make a ramming attack roll.
Ramming is a Strike attack on the robot's attack table.

While all robots can ram, not all robots have ramming freedom.
Ramming freedom is an offensive system that allows the player to attack without making a control factor roll.

.*Ramming Checklist*
. Attack Roll
. Damage (from fabrication)
. Ramming Speed
. Crush Multiplier 

=== Attack Roll
The player makes an attack roll for her persona.
If the player's attack roll is higher than the target's Defence Rating, the target gets rammed.
The player can add her persona's Strike bonus to her attack roll.
The player can only add her Strike  Raw Bonus to her ramming attack roll.

=== Damage
The damage the player rolls if she wins her attack roll depends on the shape of the part with which the robot rams.
The player determines this during her robot's fabrication. 
The table from that section is below for convenience. 
Robots cannot use the Strike Force Bonus for ramming. 

include::robots:partial$peripherals_offensive_ramming.adoc[]

NOTE: In previous versions, robots took reciprocal damage for ramming. 

=== Ramming Speed
The faster the robot is going, the more ramming damage it delivers.
How much damage a robot inflicts is dependant on the relative speed of the robot and the target.
Relative speed sounds boring, and we call it Ramming Speed instead.

=== Calculate Ramming Speed
.Ramming Speed = Robot move - Target move 
****
Ramming speed assumes the target is running away from the robot. 
****

A robot is moving at 12 h/u, and her target is moving at 3 h/u.
In most cases, the target will be running away from the robot.
If the target were charging the robot, the ramming speed would be 15 h/u.

The robot has a blunt flat ramming surface (1d4 + 1d4 per 3 h/u).
The robot's ramming speed is 9 h/u, and the player rolls 1d4 plus 3d4 hit points in damage (4d4).
If the target were running head-on at the robot, the ramming speed would be 15 h/u, and the damage would be 6d4 hit points.
A successful attack roll will always generate the base damage of 1d4 HPS of damage. 

A robot with a sharp protuberance ramming surface inflicts 1d10 + 1d8 per 3 h/u of ramming speed.
The above ramming speed would inflict 1d10 + 3d8 hit points of damage for a typical ram and 1d10 + 5d8 for a head-on ram.
Ramming can be very destructive.

A stationary target has a move of 0 h/u, and the robot has a ramming speed equal to its move.

There are no rules for angled attacks. 
That kind of arithmetic hurts the brains of even hardened tactical combat players.

=== Crush Multiplier
Ramming speed determines the total damage delivered by the robot.
The crush multiplier considers the relative wate of the target.
Consider being hit by a bicycle vs a dump truck.
The bigger you are, the harder they fall.

If the robot and the target have the same wate description, the crush multiplier does not apply.
So a medium-sized robot does not get a crush multiplier against a medium-sized target.

=== Calculate Crush Multiplier
.Crush Multiplier = Robot wate (kgs) / target wate (kgs)
****
The maximum bonus is 4 times.  +
The maximum penalty is 1/4 times.
****

If a 120 kg robot rams a 40 kg target, the player triples the damage.
In this case, 24 HPS of damage would become 72 HPS of damage.
If a 40 kg robot were to ram a 120 kg target, the player decreases the damage three times.
In this case, 24 HPS of damage would become 8 HPS of damage.
If both the robot and the target were medium-sized, the crush multiplier would not apply.
