= Exatmo Vehicle Combat

[quote]
____
We shall fight them on the beaches. We shall fight them in the troposphere. We shall fight them in the cold, silent darkness of space. 
____

// attack rolls vs comp rolls vs pilot rolls
// need a list of attacks and what can assist them and what can defend against them.
// maybe a better attack defend counter cycle table
// what the fuck are counters anyways

Combat in outer space is very deadly.
The threat to organic life is total.
The speeds are incredible.
The weapons are formidable. 
Life enjoying personas avoid space vehicle combat.
The space vehicle combat in EXP supports intimate skirmishes between solitary vessels.
This section is not for battling armadas that can vaporize kilometer-long battle cruisers.
One-on-one space vehicle battles allow the players to be more involved.

:art: space_combat_missiles.png
:width: 450px
:snark: Billions of credits being wasted.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Spaceship launching missiles and firing lazers.
include::ROOT:partial$articulate.adoc[]

Space vehicles are extremely valuable.
Personas prefer to take over space vehicles rather than destroy them.
Most space combat will end with the expedition boarding a defeated vessel or defending a defeated vessel.

The procedure for space vehicle combat is similar to lethal persona combat.
There are turns, initiative, attack rolls, damage rolls, and effects of damage.
For the most part, the computers are running the show in space vehicle combat.
The players can make some decisions, but the execution and success of the combat is a battle of the ships.
The space vehicle computers manage maneuvers, generate electronic countermeasures, and guide missiles.
The organics onboard buckle down while the ship spins to put as much hull between its integral components and incoming attacks.

== Nomenclature
Exatmo is a contraction for exterior to atmosphere. 
Exatmo is deadly to all personas (anthros, aliens and robots) unless they are specifically protected.
ECM is an acronym for electronic countermeasures. 

A vehicle must have exatmo or special drives to be a space vehicle.
An airship only has an inatmo drive.
An airship could be a plane or a dirigible, but not a space vehicle.

include::appendices:partial$space_vehicle_nomenclature.adoc[]

Space vehicles are created in the xref:hardware:CH52_Space_Vehicle.adoc[Space Vehicles] section.
Players and referees should understand space vehicles before blowing them up.

== Escape!
Personas can avoid space vehicle combat by running away.
Space vehicles are so diverse that one vessel can usually escape another.

NOTE: *The best way to win a space fight is by 12 parsecs.*

One can run away using exatmo drives.
One can dive into the atmosphere using inatmo drives.
One can jump away using special drives.
Unless a ship's drives are damaged, the expedition can choose to escape.
In general exatmo vehicle combat is agreed upon by both parties.

== Points of Difference
Exatmo vehicle combat happens at tremendous speed.
Exatmo vehicle combat happens at tremendous distances. 
There are many ways to attack a space vehicle.
ECM, ramming, mines, boarding and artillery.
Most personas will prefer to board and take over a ship due to its value.

.*Unique Elements of Exatmo Vehicle Combat*
. Combat parameters are massive
. Computer-controlled combat
. Combat turns are different
. Victory conditions are unique

=== Parameters
On an astronomical scale, the distances between space vehicles are minuscule.
For players and their personas, these distances are enormous.
Battling space vehicles could be tens of kilometers apart. 
Only when ramming and boarding do space vehicles come close to each other. 

The speeds are entirely unrealistic. 
Space vehicles use their exatmo drives to maneuver during combat. 
Exatmo drives move at up to 0.9 the speed of light. 
Space vehicles must be travelling at almost the same speed to engage.

:art: tell_them_I_love_them.png
:width: 350px
:snark: Tell them I love them!
:artist: JEShields
:date: 2014
:license: Copyright JEShields Stock Art. jeshields.com
:description: Naval admiral with manly beard yelling and pointing on bridge.
include::ROOT:partial$articulate.adoc[]

=== Computer Controlled
No lifeforms can balance all that is needed to engage in combat.
The combat happens at tremendous speeds.
The combat happens at tremendous distances. 
The process requires many simultaneous calculations.
The ship's computer is not just a calculator. 
The computer integrates with every aspect of the ship.

Only the ship's computer can manage the connectivity and calculations required for combat.
Players and personas are mainly uninvolved in exatmo vehicle combat.
The computers determine the attack sequences, movement and tactics of combat.
The players get to roll dice, but the computer is deciding the combat course.

=== Combat Turns
A turn in exatmo vehicle combat is very different from a combat unit in the tactical combat rules.
Space combat turns are longer and more structured than the free-wheeling 2-second tactical combat unit.
A combat turn lasts one minute and involves a stepwise execution of attacks and defences.
During a turn, the combatant vessels are wildly jockeying for position at half the speed of light.
The ship computers are firing missiles, dumping mines, calculating ECM, and aiming artillery.
Most often, the personas will be idle as the players make attack rolls and decisions. 
However, it is also possible for personas to use every unit of the turn doing other stuff.

Players do not make a lot of decisions during exatmo vehicle combat. 
The cycle of attack, defend and counter-attack is built into the turn. 
There are initiative rolls, attack rolls, defence rolls, and damage rolls to be made each turn.
The process continues until a vessel escapes or achieves victory conditions. 

=== Victory Conditions
The victory conditions of space vehicle combat are unique to the vessel itself.
The victory conditions of persona tactical combat are simple.
One of the combatants is unconscious, dead, or escapes.
The goal of space vehicle combat is to gain control of the target ship, not destroy it.

There are four main victory conditions in space vehicle combat.
They all involve the inability of the defeated ship to function.
A space vehicle battle can be lost by: running out of fuel, a severely damaged gravity system, destruction of the exatmo drive, or loss of bridge control.

.*Victory Conditions*
* Loss of Fuel
* Loss of Gravity
* Loss of Exatmo Drive
* Loss of Bridge Control

NOTE: *Victory conditions are more like defeated conditions. Glory to the English language.*

The victory conditions indicate when the __space battle__ is over.
A space battle rarely destroys a space vehicle. 
Likely the ship's crew and cargo will be intact.

==== Loss of Fuel
Running out of fuel may be the least glamorous way to lose a battle.
Combat fuel burn is tremendous, and no fuel means no combat maneuvers. 
A ship out of fuel stops spinning and hurtles off in a predictable trajectory.
The predictable trajectory makes the vessel vulnerable to boarding, ramming and focused attacks. 
Inadequate fuel for combat does not threaten life support or onboard systems.
A fuel-depleted space vehicle may not be controlled by the attackers yet, but the exatmo battle is undoubtedly over.

==== Loss of Gravity
A space vehicle's gravity system is an essential part of the life support system.
The gravity system allows personas to enjoy normal gravity within the space vehicle.
The gravity system keeps the persona's feet or flippers comfortably on the deck of the space vessel.
While this may sound like a convenience maintaining constant gravity in combat is life-saving.

The sciency fiction exatmo vehicle combat system involves vessels flipping, twirling and banking using their exatmo drives.
These maneuvers would obliterate all life without a gravity system, and the ship would tear itself apart.
Doing a barrel roll at 500 million km/h is not compatible with physics, let alone life. 

Combat is over if the gravity system is functioning at less than 30%.
The space vehicle cannot use exatmo drives if the gravity system functions at less than 10%.

A ship out of gravity safely stops spinning and hurtles off in a predictable trajectory.
This predictable trajectory makes the vessel vulnerable to boarding, ramming and targeted attacks. 
Inadequate gravity for combat does not threaten life support or onboard systems.
The crippled space vehicle may not be controlled by the opposition yet, but the exatmo battle is undoubtedly over.

==== Loss of Exatmo Drive
If the drives are dead, the space vehicle is unable to engage in space combat.
In combat, the exatmo drives are potent units that swing the ship madly around, deflecting kinetic attacks, and aligning weapons.
If the exatmo drives are out of commission, the space vehicle has come second place in space combat.

==== Loss of Bridge Control
The final pathway at the end of all exatmo vehicle combat is losing control of the bridge.
There are several ways to lose control of the bridge: surrendering the bridge, losing the bridge to personal combat or destroying the bridge during space combat.

== Combat Turn Order
Space combat is aggressive.
Every attack is happening as fast as possible.
Each turn has a cycle of attack, defend and counter-attack.
The first strike is the goal, and initiative is essential. 

The combat turn cycle goes from fastest to slowest attacks. 
ECM will always act before naval artillery.
Defences are automatically activated unless the player chooses not to defend.
Counter attacks are attacks that double as defences.
Counter attacks are not automatically activated and require a decision by the player.

Each space vehicle is randomly created and has a different weapon configuration.
The attack order only applies to attacks that the space vehicle has.
One space vehicle may only have ECM, while another may have ECM and bombs.
Naval artillery is very rare.
All space vehicles can ram or board. 
All of these attacks are possible in each combat turn.

include::combat:partial$exatmo_vehicle_turn_order.adoc[]

=== Example
Ship One and Ship Two are unable to talk it out.
An exatmo vehicle battle ensues.

.*Ship One Attacks*
* ECM
* Ramming
* Artillery

.*Ship Two Attacks*
* Ramming
* Artillery
* Mini-Missile (Grenades)

.*Turn order and Initiative*
. Ship One attacks with ECM.
.. ECM (1) act first, no init. 
.. Ship Two has no ECM (1) to counter.
.. ECM (1) affects Ship Two.
. Ship Two makes a ramming attempt.
.. Ram (2) attempt, no init.
.. Ship One has used ECM (1), no counter.
.. Success would convert to onboard battle.
. Both fire their artillery.
.. Artillery (3) are equal.
.. Initiative rolls required.
.. Winner make Artillery attack first.
. Neither ship is boarding (4).
. Ship Two attacks with  Mini-Missiles (5).
.. Ship One has used ECM (1) and Artillery (3), no counter.
.. Ship Two makes Mini-Missile attack on Ship One

== Initiative
Initiative is only needed when both vessels have the same attack type.
For example, if both combatants have ECM, the pilots roll initiative to see which vehicle's ECM acts first.
If only one combatant has ECM, this pilot would automatically act first.

=== Initiative for Space Combat
.Init = 1d20 + Computer Level + Pilot Level + Other
****
Init = 9 (1d20) + 4 (computer level) + 3 (pilot level) = 16
****

=== Example
Ship One and Ship Two are unable to talk it out.
They both have Artillery, which is turn level 3.

.*Ship One Combat Team*
* Computer Level 2
* Pilot Level 3
* Combat Software Level 1
* Init = 9 (1d20) + 2 (computer level) + 3 (pilot level) + 1 (other) = 15

.*Ship Two Team*
* Computer Level 4
* Pilot Level 1
* Init = 11 (1d20) + 4 (computer level) + 1 (pilot level) = 16

Ship Two would win initiative on Artillery (3) and would get to make an attack roll and possible damage Ship One first.

== Counter Attacks
Counterattacks are opportunities offered to a defending ship.
Counters are specific defences against specific attacks. 
For example, a ship being rammed or boarded gets to counterattack with mines or artillery. 
Counters are detailed on the the Attack Defend Counter Attack Table.


== Roll Types
There are two roll types in exatmo vehicle combat.
Attack Rolls and Success Rolls. 

=== Attack Rolls
The first kind of roll is an attack roll. 
Attack rolls are the same as attack rolls in tactical combat.
Exatmo combat attack rolls use a kilodie and the player must roll over a Defence Rating. 
Attack Rolls are used with physical attacks like mini-missiles, mines, artillery etc.
Win an attack roll and damage the target.

=== Success Rolls
The second kind of roll a success roll.
Success rolls are most similar to task rolls.
The player must roll over a calculated number using 1d100.
Success rolls are used with electronic attacks like ECM, and navigation attacks like ramming and boarding. 
Win a success roll and something happens to the target.

A success roll may enjoy persona based bonuses on the fly.
For example, a pilot may be able to add her DEX to a success roll when trying to board.

NOTE*A success roll will eventually become a task roll.*

== Onboard Crew
The crew includes any persona that is onboard a space vehicle during combat.
They can lend their skills to assist the ship's computer or repair the damaged ship.
A combat turn lasts 30 units in EXP.
A combat turn is sufficient time for personas to have a lot of fun between combat events.
Personas are not able to assist with an attack and repair the ship simultaneously.

=== Attack Assist
Crew can help the ship's computer and combat systems improve the chances of success.
A mechanic with artillery skill two is assisting a level three computer.
This vocation/computer team makes artillery attacks like a level 5 computer.

If the space vehicle is flush with crew members, the computer can work with a research team to pile up bonuses.
Before a mechanic, a mercenary and a spie must form a research team before assisting the computer. 
Research teams are located xref:uncombat:task_rolls.adoc#_research_team_composition[somewhere in this book,window=_blank]. 

=== Ship Repairs
There is enough time during combat turns to accomplish ship repairs.
The goal of ship repairs is to return percentage points of efficiency and restore functionality.
Ship repairs are entirely under the purvey of the mechanic vocation.
The personas can form research teams depending on which system they are repairing.

These are not maintenance repairs. 
These are bubble gum and duct tape repairs to get through combat.
Most of these repairs will fall apart once combat ends.

NOTE: * Personas cannot repair destroyed systems during combat.*

For example, a mechanic attempts to repair the special drive by ten percentage points. 
This repair would be a 10 DD maneuver for the mechanic.
If she is successful, the special drive will move from 8% effectiveness (disabled) to 18% effectiveness.
This repairs the special drive moves from disabled to critically damaged.
While still critically damaged, the expedition special jumps to safety.

The mechanic could also repair an airlock from only opening 40% to opening 60%.
To repair this 20% deficiency would be a 20DD maneuver.
The repair allows the expedition's combot to join in on the boarding attack. 

== Table Co-Location
For your surfing convenience.

include::combat:partial$exatmo_vehicle_damage_location.adoc[]

include::combat:partial$exatmo_vehicle_damage_amount.adoc[]

include::combat:partial$exatmo_system_dysfunction.adoc[]

== Attack and Defend 
Jump to the next section xref:combat:combat_and_exatmo_vehicle_weapons.adoc[Exatmo Vehicle Weapons]
