= Equipment Damage

:art: smashing_brick.png
:width: 250px
:snark: Humanoids in glass houses...
:artist: James Shields
:date: 2014
:license: Copyright JEShields Stock Art
:description: Brick smashing through pane of glass.
include::ROOT:partial$articulate.adoc[]

Personas aren't the only things that get destroyed in EXP.
Besides the ceaseless battering of personas, inorganic equipment is also subject to the effects of entropy.
In EXP, nothing is indestructible, everything wears out, and what can go wrong will.
Equipment damage is reserved for unique circumstances and is not part of regular gameplay.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

Equipment does not have hit points like personas.
Equipment HPS comes into play for unfortunate circumstances where the referee needs to quantify a mishap.
Non-artifact equipment, aka mundane equipment, is simply destroyed in incidents.
These rules are for crucial plot affecting artifacts and TOYs. 
For example, the referee to this section if a persona used her plasma rifle as a crowbar.

== Artifact Hit Points
Most artifacts to not have very much in the way of hit points.
Artifact HPS are based on 
The artifact's EXPS is the basis for an artifact's hit points. 

include::combat:partial$artifact_hit_points.adoc[]

A tech level 10 age determiner is worth 200 EXPS and has 10 HPS.
The artifact will be damaged if exposed to 10 or more HPS in damage

A tech level 20 napalm grenade is worth 540 EXPS and has 108 HPS.
The artifact will be damages if exposed to 108 or more HPS in damage.
Whether is detonates or not is a different story. 

A random junque, whiz and click device is worth nothing and mostly irritates the expedition.
It cannot be destroyed by accident or incident.
Only intentional damaging can harm Random Junque.

== Damaging
Artifacts are technomagical and are composed of alloys, and polymers.
Equipment is most often damaged by area attacks, kinetic tragedy and malice.

:art: falling_gun.png
:width: 250px
:snark: Oops, kinetic tragedy!
:artist: HM
:date: 1991
:license: CC BY-SA 4.0
:description: High tech pistol falling towards the ground.
include::ROOT:partial$articulate.adoc[]

=== When
Nothing happens to the equipment if the damage amount is less than it's HPS.
At zero HPS, the toy does not go unconscious or die, but it suffers damage.
Obviously delicate artifacts can be instantly destroyed.
Don't let rules get in the way of story and fun.

The extent of damage roll shows what percentage of previous function the toy presently has.
The extent of damage can vary from trivial (cosmetic only) to the destruction of the artifact.


=== Extent
The extent of damage is determined randomly and modified by the hit points of the damage delivered.

include::combat:partial$exatmo_vehicle_damage_amount.adoc[]

=== Cumulative Damage
The damaging effects of artifact injuries are cumulative.
An artifact can become disabled over several attacks.
An artifact suffering two major damage incidents (40% performance drop) is now functioning at 36%. 
For example, a rifle's range would be reduced from 100 hexes. to 36 hexes.

A system is disabled when it is reduced to less than 10% function.

=== Instantaneous Destruction
Instantaneous destruction occurs when an attack destroys a system in a single blow.
The attack must drop the system from 100% to <1% function in a single attack.
Destroying an artifact in one blow may lead to additional consequences.
Often players will expect a destroyed bomb or grenade to activate accidentally.
Accidental activation is usually determined by a xref:uncombat:sphincter_rolls.adoc[Sphincter Roll,window=_blank]

=== Damage Descriptors
Each time an artifact is damaged, its performance decreases. 
The damage descriptors offer another way to describe net damage.
An artifact with minor damage is functioning at 90% capacity.
An artifact with less than 10% of capacity is disabled. 

include::combat:partial$exatmo_system_dysfunction.adoc[]

== Artifact Repair
Mechanics can repair damaged artifacts.
Damaged artifacts are repairable.
The more damaged the artifact, the more difficult the repair.
Destroyed artifacts are not repairable, but can be a source of spare parts. 
Spare parts are usually determined by a xref:uncombat:sphincter_rolls.adoc[Sphincter Roll,window=_blank]


:art: equip_damage_chicken.png
:width: 250px
:snark: Rubber chick organ maintenance is crucial
:artist: Andrew Brechin
:date: 1991 
:license: CC BY-SA 4.0
:description: A tuxedo clad humanoid pulling chicken out of futuristic music organ.
include::ROOT:partial$articulate.adoc[]

== Maintenance
The more moving parts the artifact has, the more maintenance is needed.
For example, a vehicle needs regular maintenance, but a grenade does not.
A pharmaceutical tablet may be able to sit around for decades.
An ointment may require refrigeration and air conditioning.

Un-maintained artifacts will deteriorate.
Equipment subject to any semblance of routine maintenance is not be affected by wear and tear.
To avoid deterioration, players merely need to say they are maintaining their artifacts. 
Complicated vehicles may require a mechanic for maintenance.
A mercenary can maintain weapons. 
A veterinarian can maintain vet equipment.

The referee can make an extent of damage roll once a year for unmaintained equipment.

:art: glass_half_broken.png
:width: 350px
:snark: It was broken when I got here.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: A few shards of broken glass on the ground.
include::ROOT:partial$articulate.adoc[]

== Mundane Item Hit Points
Personas will often insist on damaging mundane items that surround them.
They may wish to destroy a door, crash through a wall, blow a hole in the road, or destroy a bridge.
The referee can't have the HPS of architectural items such as walls, doors, windows and the like prepared for each particular scenario.

Mundane Doors and-walls are destroyed when they lose all their HPS.
For instance, a mundane door has 30 HPS.
If a door takes 30 HPS, it ceases to be a door and now is an opening with sharp edges.

include::combat:partial$mundane_equipment_damage.adoc[]
