= Non-Lethal Combat

[quote]
____
*The goal of non-lethal combat is to subdue the target, not kill.*
____

Non-lethal combat is cinema-style punch pulling, shin-kicking, chair swinging, all-out brawling.
The goal of non-lethal combat is not to kill the opponent but to subdue the opponent.
Subdual occurs when a persona fails a Damage System Shock Roll and is unable to continue.
Non-lethal does not mean benign. 
Each attack still does some damage, and accidental death can occur.
The players can use non-lethal and lethal personal combat simultaneously.

.*Pugilistic Parameters*
. Strike attacks only (fists, clubs, feet, sticks)
. Anthros and advanced aliens only.
. Subduer must be of comparable size.

The attacker can use only certain attacks in non-lethal combat.
Strike attacks like Fists, feet, hooves and flippers are allowed.
Fling attacks like rocks, plates, bottles, and cheese wheels are allowed.
Pointy Fling attacks like arrows and daggers are not allowed.
There are no Shoot, Sotto, Flotto or Area attacks allowed. 
The only exception is powered stun weapons specifically designed to be non-lethal.

The combatants must be able to grasp the concept of surrender.
Flora, fauna and robots do not understand surrender and beating them does not help.
In turn they do not understand surrender and will lethally fight for their lives.
Robots may attack non-lethally, but non-lethal combat has no emotional impact on them.

.*Non-Lethal Combat Cycle*
. Attack Rolls based on xref:combat:initiative.adoc[Initiative]
. Each successful hit
.. Roll Non-Lethal Damage
.. Stun Check (DSS Roll): against non-lethal damage
.. Inflict actual damage: using 10% of non-lethal damage
.. Oops Damage Check: accidentally deliver full damage

== Attack Rolls
Non-lethal combat is part of the tactical combat rules and attack rolls and attack types function the same.
Players make attack rolls with kilodie and must beat the target's Defence Rating.
Proficiency in hand-to-hand combat is required to use one's Skilled Bonus.

== Non-Lethal Damage
Combatants in non-lethal combat are not eye-gouging, throat punching, or intentionally snapping bones.
They attack non-lethal but sensitive body locations.
The attacker is not trying to kill the target, and she will be pulling her punch at the last millisecond.

Strike weapons can be used in non-lethal combat. 
When using a Strike weapon (club, hammer, etc) the player must add the Force Bonus to the damage rolled.
Only personas with hand-to-hand combat skill can hold back the Force Bonus when using a normally lethal weapon.

The player rolls damage as per normal after a successful attack roll.
In non-lethal combat this damage is applied differently and is called Non-Lethal Damage
Sorry there is no acronym.

An angry pugilist wins her attack roll and generates 20 HPS of Non-Lethal Damage.
She is attacking a Level 2 Nothing with a CON of 8 and HPS of 40.
This unlucky nothing's name is Socmob.
Let's follow that damage bolus through the next three steps.

== Stun Check 
A damage system shock check determines if the persona is stunned by the non-lethal blow.
The target must win a damage system shock roll (DSS) against the non-lethal damage value or be stunned. 
The stun could either be a knock-out blow or a collapse from compounded hammering.
Either way failing the DSS Check is a losing condition.

When the target is hit she must win a DSS Roll __as if__ her HPS were reduced by the Non-Lethal Damage.
A target with 44 HPS being delivered 22 HPS of Non-Lethal Damage would use the DSS check with 22 HPS remaining.
Her HPS total does not change at this point. 

[discrete]
=== Damage System Shock Roll (DSS)
.1d20 + HPS + CON + LVL > 42
****
If Socmob DSS Check = 12 (1d20) + 20 (HPS - Non-Lethal Damage) + 8 (CON) + 2 (Level) = 12 + 20 + 8 + 2 = 42. > 42 so no stun +
If Socmob DSS Check = 8 (1d20) + 20 (HPS - Non-Lethal Damage) + 8 (CON) + 2 (Level) = 8 + 20 + 8 + 2 = 38. < 42 so Socmob goes down
****

== Actual Damage
Every non-lethal damage roll inflicts a smaller amount of actual damage. 
Ten percent of the non-lethal damage causes actual damage to the target.
The target's hit point total (HPS) loses that amount for every successful attack roll.
Eventually, non-lethal combat will drop the target.

[discrete]
=== Actual Damage Calculation
.Damage = 10% of Non-Lethal Damage (round up)
****
Socmob was hit with 20 HPS of Non-Lethal Damage. Her HPS from from 40 to 38. +
Her next DSS Check is with 38 HPS, so she is softened a bit.
****

== Oops Damage
Non-lethal attacks are not as easy as they appear in the movies.
Personas may accidentally deliver a lethal blow instead of a non-lethal attack.
Unskilled at non-lethal combat, a persona may accidentally deliver a lethal blow.
Personas with hand-to-hand combat skill can avoid oops damage. 

There is a 1% chance per HPS of damage that the non-lethal attack will convert to an accidental lethal attack.
For example, 15 HPS of non-lethal damage has a 15% chance of becoming 15 HPS of oops lethal damage.

=== Oops Damage 
.Chance Lethal = 1% per point of Non-Lethal Damage
****
Angry pugilist's 20 HPS of Non-Lethal Damage has a 20% of converting to 20 HPS full damage.
****

If the player running the angry pugilist rolls under 20 on deci-die Socmob would take 20 HPS of damage. 
This would drop her HPS to 20. 
Socmob would be very softened by this blow.
Later in the brawl such a blow could be lethal.

== Victory Conditions
A persona may have had enough and calls it quits.
A persona may be stunned by a failed DSS Roll. 
A persona may be knocked unconscious by an accidental damage bolus.
A persona may die from accidental damage.

== Grapples, Pins and Tackles
Grappling is any non-lethal hand-to-hand attack that is intending to hold a target in one place.
Tackles, headlocks, full nelsons, father nelsons, and pins are all considered grapples.
Like any attack, a grapple requires an attack roll against the target's Defence Rating.
The attacking player can add whatever adjustments are appropriate to her attack roll.
Only personas with hand-to-hand skills can use their Skilled Bonus when grappling.

If the attack roll is successful, the grapple is successful.
A grappled target can try to break free, attack, or reverse the grapple.
Personas can use only close-range weapons like daggers and pistols in grapple combat.

Armour ratings apply as combatants are in combat and doin' the jiggly wiggly combat dance.

.*Grasping the Grapple*
. Attack roll
. Overpower 
. Break Check

=== Attack Roll
The player makes a usual attack roll made against the target's Defence Rating.
Grappling is a Strike attack.
The player must use her Raw Bonus unless she has hand-to-hand combat skill.

=== Overpower
The player must overpower the target to have the grapple stick.
Overpowering is determined by a Strength Challenge between the personas.
If the player wins the Strength Challenge the target is incapacitated by the grapple.
The target cannot accomplish anything other than psionic attacks and yelling while grappled.
The successful grappler has slightly more freedom and may undertake the simplest of tasks.

=== Break Checks
The target can make a break check every unit.
Per unit break checks may seem too frequent, but the assumption is that the grappling parties are writhing back and forth, rolling around, etc.
If the target wins the Strength Challenge, they can break free, move and attack.

=== Strength Challenge
.1d20 + STR + Level vs 1d20 + STR + Level
****
Whichever total is higher wins. 
****

== Weapon Snatching
Weapons snatching is a classic cinema trick to turn the tables on dastardly pikers!
Weapon snatching is part of non-lethal personal combat.
Often players want to snatch an opponent's weapon.
Grappling someone's weapon is impossible in most situations and extremely difficult in those situations where it is possible.
Weapon snatching is part of our cinematic culture, and if the referee is going to allow it, the tactical system has an approach.
The player must win an attack roll, a Dexterity competition and a Strength competition to wrestle a weapon from the target. 

.*Grappling a Weapon*
. Attack roll
. Dexterity competition
. Strength competition

=== Attack roll
The player makes a usual attack roll made against the target's Defence Rating.
Weapon grappling is a Strike attack.
The player must use her Raw Bonus unless she has hand-to-hand combat skill.

=== Dexterity Challenge
The gun grabber must win a Dexterity competition to get ahold of the weapon. 
If the grabber fails this Dexterity competition, they have placed themselves in grave danger.
If the target persona has an attack remaining, they get a +242 attack roll bonus on their attacker.

=== Dexterity Challenge
.1d20 + DEX + Level vs 1d20 + DEX + Level
****
Whichever total is higher wins. 
****

== Tripping
Tripping a target before they get to the giant red activation switch is more common than one would expect.
Tripping is another non-lethal attack.
The player must win an attack roll and a Strength competition to get a chance to trip.
The target then has a chance to dodge the trip by winning a normal Dexterity roll. 
Too bad the target is not an European soccer player.

For trips to work, the target and the attacker should be about the same size. 
The target must also be tippable.
The attacker cannot trip a robot with treads.