= Appendix D: Credits

Versions in chronological order.

== Version 1
*Homebrew 1980 by Hugh MacLeod*

Notes::
Typed on an olivetti underwood electric typewriter. 
Photocopied sections contained in D-Ring binders.

Special Thanks:: 
The minds that changed the meaning of what a game meant, and how collective play could work. https://en.wikipedia.org/wiki/Jim_Ward_(game_designer)[James Ward] (https://en.wikipedia.org/wiki/Gamma_World[Gamma World], and https://en.wikipedia.org/wiki/Metamorphosis_Alpha[Metamorphosis Alpha]); Gary Gygax and Dave Arneson (Dungeons and Dragons).

== Version 2 
*Copywrite © 1983 by Hugh MacLeod*

:art: exp_1983.png
:width: 250px
:snark: Commodore 64 and crafting.
:artist: HM, ED
:date: 1983
:license: CC BY-SA 4.0
:description: Diagram of EXP logo from 1983.

include::ROOT:partial$articulate.adoc[]


== Version 3.01 
*Copywrite © 1990 by Hugh MacLeod*

:art: exp_1993.png
:width: 250px
:snark: Before Corel Draw worked.
:artist: HM, ED
:date: 1993
:license: CC BY-SA 4.0
:description: Diagram of EXP logo from 1990.

include::ROOT:partial$articulate.adoc[]


== Version 4.01
*Copywrite © 1993 by Hugh MacLeod*

:art: exp_1993_front.png
:width: 450px
:snark: Front Cover 1993
:artist: Eric Hotz
:date: 1991
:license: CC BY-SA 4.0
:description: Painting of human, robot and humanoid insect standing in front of DNA circuit board.

include::ROOT:partial$articulate.adoc[]

All rights reserved. 
No copies may be made, in whole or in part, without the expressed written consent of the author. 
This includes digitizing onto super computers, or the ink quill copying made by small furry gremlins. 
The Game of Technological Chaos, EXP and the EXP logo are all trademarks of MERV Engineering, Inc.

Written and Designed:: 
Hugh MacLeod

Editing::
Efrosini Drimoussis, Nick Fleming, Afton Lewis, Jason Montgomery, Bruce Murray, Allen Sens, James MacLeod, Patrick Redding, Dave New

Rule Testers::
Clint Hocking, Jason Montgomery, Bruce Murray, Allen Sens, James MacLeod

Play Testers::
Clint Hocking, Jason Montgomery, Bruce Murray, Allen Sens, James Macleod, Ilmar Weemes, Stephen White, Afton Lewis, Derek Krezeski, Nick Lacoumantas, Randy Parris, Anyone that ever complained, Jason Gilley, Nick Langford, Nick Fleming, Nick Kwan, Mark Kwan, Greg Dunn, Jason Liebert, Dave Bulman, John Sirmul, Karl Innes, Joe Jeffries, plus a few more.

Art Direction::
Mike Jackson

Illustrators::
Mike Jackson, Patrick Redding, Andrew Brechan, Jim Nelson, Eric Hotz, Peggy Lynn McAasic, Duncan X, Mike Deane, Warren Oddsson

Desktop Publishing::
Patrick Redding

:art: exp_1993_back.png
:width: 450px
:snark: Back cover 1993
:artist: Eric Hotz, copy HM
:date: 1991
:license: CC BY-SA 4.0
:description: Painting of a human in flight suit surrounded by alien bunnies.

include::ROOT:partial$articulate.adoc[]

== Version 5.0
*Copywrite 2010  Hugh MacLeod* +
Creative Commons License Share and share alike with attribution.

:art: exp_game_headliner.png
:width: 
:snark: Title header for 2010 WordPress site.
:artist: Unknown 
:date: 1990
:license: Copyright 1990 Hugh MacLeod
:description: Head and shoulder painting of alien, human and robot.

include::ROOT:partial$articulate.adoc[]

Web Development:: 
Hugh MacLeod

Typing:: 
Kimberly Jonasson

Play Testers:: 
Colin, Liam, Jimmy, Benin, Ben, Nigel

Special Thanks:: 
Tobias Bäthge (https://tablepress.org/[Tablepress]), PDF to text (https://www.onlineocr.net/[OnlineOCR])

== Version 5.01
*Copywrite 2018 Hugh MacLeod* +
Creative Commons License share and share alike with attribution.

:art: exp_game_headliner.png
:width: 
:snark: Title header for 2018 WordPress site.
:artist: Unknown 
:date: 1990
:license: Copyright 1990 Hugh MacLeod
:description: Head and shoulder painting of alien, human and robot.

include::ROOT:partial$articulate.adoc[]

Unexpected revision required by a database scramble. Many typos, errors, and grammar mangles fixed.

Web Repairs:: 
Hugh MacLeod

Special Un-thanks:: 
Google Cloud Products. Proprietary incomprehensibility.
JIBC PCP Program. 
Bunch of hateful, cruel, racist, sexist destructive creeps.

== Version 6.0
*Copywrite 2020  Hugh MacLeod* +
Creative Commons License Share and share alike with attribution.

:art: exp_game_headliner.png
:width: 
:snark: Header for 2020 index page.
:artist: Unknown 
:date: 1990
:license: Copyright 1990 Hugh MacLeod
:description: Head and shoulder painting of alien, human and robot.

include::ROOT:partial$articulate.adoc[]

Static Site Migration:: 
Hugh MacLeod

Rule Evolutions::
Hugh MacLeod

Additional Artists::
https://www.patreon.com/jeshields/posts[JE Shields], Hugh MacLeod, Studiostoks 2015

Play Testers::
Eric Green, Sam Weisbrod, Leanne Zarour, Craig Addison, Jeff Templeton, Susan Carroll, Kathy Garneau, Stephan Smith

