= Appendix A2: Glossary of Terms

Adjusted:: 
An attribute that is adjusted by the persona's experience level. 
Adjusted MSTR is the persona's MSTR plus EXPS Level.

Alien:: 
Aliens are organic personas of unusual shape and size.
In the faux taxonomy they are called Diversidae.
Playing an alien persona requires an experienced player.
They are alien to us but not to themselves.
These are the tentacled, furry, floating horse creatures.

Anthro:: 
Anthros are organic personas, and are upright, bipedal humanoids.
In the faux taxonomy they are called Hominidae.
Anthro is short for anthropomorph.
Playing an anthro persona is highly recommended for players.
The entire rule set, and technology system is based on anthros.

Anthrocentric::
Same as anthropocentric, but not limited to humans.

Area of effect:: 
The area in which targets are subjected to damage or special effects. 
It is measured in hexes.
The value usually gives a radius for a spherical area of effect.

Amour Rating (AR):: 
The amour rating of the persona indicates how well she is protected from damage in combat. 
The higher the armour rating value the less likely she is to be damaged.

Attack roll::
The dice roll that is used to see if a target was successfully attacked.
The higher the to hit roll the better.
Usually the to attack roll generated must be higher than an armour rating to indicate success.
A successful attack roll indicates the target has been damaged.

Attributes:: 
These are the imaginary divisions of a persona’s physical abilities.
They are also called statistics.

Bonus non-proficient (BNP):: 
The to-hit roll bonus used when the persona is using an unfamiliar weapon. 
This value is less than the regular to-hit roll bonus.

Bonus proficient (BP):: 
The to-hit roll bonus used for skilled weapons.
Weapon skills are limited to combat vocations.

Bot:: 
Shortened form of robot.

Campaign:: 
This is the story generated by the referee and the players.
A campaign is built from scenarios.
The scenarios can involve many personas and different locations. 
A campaign can last for months or years.

Dice:: 
* 1d1 - A one sided die. Looks like a mobius strip.
* 1d2 - A two sided die. Looks like a coin
* 1d3 - A three sided die. Looks like a risk piece.
* 1d4 - A four sided die. Looks like a pyramid.
* 1d6 - A six sided die. The famous cube.
* 1d8 - An eight sided die. It does not look like an octopus.
* 1d10 - A ten sided die. This die is used to create 1d100 and 1d1000
* 1d12 - A twelve sided die. 
* 1d20 - A twenty sided die. The largest of platonic solids.
* 1d100 - Two (tens and digits) 1d10 are rolled to create a 1d100.
* 1d1000 - Three (hundreds, tens and digits) are rolled to create a 1d1000.
* Kilodie - Another name for a 1d1000

Damage:: 
Whenever a hit is scored in combat, the persona loses hit points. 
The amount of hit points lost is the damage. 
The more lethal an attack, the more damage it inflicts.

Damage Adjustor (DA):: 
This value is added to the damage roll for certain weapon types. 
The stronger the persona is, the more damage she will inflict.

Die::
Usually refers to the singular of dice.
One dice is a die.
I have been told to "get lost and one dice."

Die roll:: 
A die roll indicates that a random number must be generated. 
Because the numbers are generated by dice, it is called a die roll.

Exatmo:: 
Short for exterior to atmosphere.
Anything that takes place in the vacuum of outer space. 

Experience (EXPS):: 
Experience is a combination of learning, maturation and training.
Experience is measured in experience points. 
The more experience points a persona has the better they are at stuff. 
A persona with higher experience will be more successful at combat and skills. 
Experience points are earned through successful die rolls and role-playing. 

Flotto::
Short form of full-auto which means fully automatic. 
Usually a machine gun of some type.

Hexes per Unit (h/u):: 
This is an arbitrary measure of movement EXP. 
It is equivalent to m/s.

Hex:: 
A hex, short for hexagon. 
The hexagon is six sided figure.
Hexagons can interconnect to create a hex field. 
The hex field is used to portray tactical combat on the table top. 
A hex equals 2 metres. 

HIG:: 
High gravity.

Hit Points (HPS):: 
The persona’s hit points indicate how much damage she can take. 
A persona with many hit points can sustain a lot of damage. 
A persona loses hit points when she is hurt. 
If a persona loses too many hit points they die.

Hit:: 
A hit is a combat term that indicates a target has been damaged. 
When a hit is scored, the target usually loses hit points.

Hite:: 
A unique measure to EXP that means height.
It can also be used to compare sizes regardless of family type.
Hite is recorded in centimeters (cm).

Inatmo:: 
Short for in atmosphere.
Anything that takes place in normal atmosphere. 

Initiative:: 
Initiative is a way of determining the order of play between the personas. 
Initiative  includes  speed, skill and luck of the persona.

Intensity:: 
Intensity represents how dangerous a poison or psionic attack is. 
The higher the intensity, the more dangerous the attack.

Kilodie:: 
A Kilodie generates a random number between 1 and 1000. 
A kilodie is also called a 1d1000
A roll of 0, 0, 0, would indicate 1000.
The kilodie is composed of three ten sided dice:
* 1d10 is the 100s
* 1d10 is the 10s
* 1d10 is the 1s

include::ROOT:partial$CH27_Table_Tactical_Kilo.adoc[]

Level:: 
A short form of experience level.
A level represents how good a persona is at combat and skills.
The experience level increases with the persona's experience points.

Maximum Roll (MR):: 
This is the highest possible to-hit roll that the player can roll. 
The MR is determined by attributes, experience level and weapon type.

Miss:: 
A miss is any failed roll.
In combat a miss is a failed attempt to damage the target.
In a saving through a miss represents being afflicted by the attack.

Movement:: 
Movement is the changing of position of personas during combat. 
Each persona has a movement rate in hexes per unit.
This is the speed of the persona.

Mutation:: 
Mutations are imaginary biological adaptations.
They can give personas imaginary powers or defects.
For anthros mutations are unique changes to that persona.
For aliens mutations are unique biological skills of the species.
For robots mutations are wildly malfunctioning peripherals.

Persona:: 
The persona is the representation of the player in the imaginary world.
The persona can be controlled by a player or a referee.
Each persona is made up of attributes, description and story.

Persona Record::
This is the persona record sheet.
It is a piece of paper or computer thingy that stores the persona's info.
Also called a character sheet.

Phenotype::
Phenotype is the physical appearance of an organism. In EXP life forms are arranged phenotypically by appearance. Anthros are all humanoid, robots look mechanical. This ignores genotype and fabrication for purpose of telling fun stories. 

Post Factualization::
Reverse improvisation to explain something that happened after it has happened. 
Commonly needed by referees when story and pseudo science need to be synched.

Player:: 
You, the reader. 
The real world persona that controls the fantasy world character called a persona.

Family:: 
The three families in EXP are anthro, alien and robot.
The anthro type pure strain human has different anthro types, not families.

Ref::
Short for referee. 
This is a player that is burdened with creating the milieu and puzzles of the campaign.
The role of referee is typically one player.
However the role of referee can be rotated or shared amongst multiple players.

Referee Persona(RP):: 
A persona that is generated and played by the referee. 
It includes aliens, anthropomorphs and robots. 
These are also called non-player characters.

Ref's Own Table:: 
This comment is found on tables used to generate EXP chaos.
It indicates that the referee and players should create something new. 

Robots::
Robots are inorganic personas built from metal and computer intelligence.
In the faux taxonomy they are called Machinidae.
Playing a robot persona requires an experienced player.
Robots are often called robots.
Robots develop free will through malfunction. 

Roll Playing::
A role-playing game with a rule set that is built around dice rolling for the sake of dice rolling. 
The majority of decisions are decided by die rolls.

Role Playing::
A role-playing game with a rule set where players make make the majority of decision.

Run::
Run refers to players getting together and playing EXP.
Run also refers to playing (or running) a persona.
A run is also called a scenario.

Saves:: 
A save is a special kind of roll that refers to non-combat challenges.
Saves are using rolled against a unique attack.
Save vs poison and save vs mental attack are the most famous.
If the player misses the saving throw their persona is subjected to the attack.

Scenarios:: 
These stories and challenges that take place in the game.
A scenario could be combat, puzzles, or some combination. 
Enough scenarios will build a story arch called a campaign.
These can also be called runs.

Sotto::
Short form of semi-auto which means semi-automatic. 
Usually a gun that can shoot multiple times per combat turn.

To-Hit roll:: 
An attack roll.
The dice roll that is used to see if a target was successfully attacked.
The higher the to hit roll the better.
Usually the to hit roll generated must be higher than an armour rating to indicate success.
A successful to hit roll indicates the target has been damaged.

Toys/TOYS:: 
Toys are devices from that personas use to gain strength and power.
Toys are like magical items from fantasy games.
Toys are created on the Technological Object Yield System.

Type A:: 
Type A is a classification of attack, also called an attack type.
Type A attacks are non-powered thrusting and striking weapons. 
Non-powered means that the persona must generate the force to inflict damage.
Type A attacks are limited to one attack roll per combat unit.
Examples are swords, clubs, daggers, claws, teeth and punches.

Type B:: 
Type B is a classification of attack, also called an attack type.
Type B attacks are non-powered ranged weapons. 
Non-powered means that the persona must generate the force to inflict damage.
Some examples are bows, rocks, darts, launchable quills, and caustic spit.

Type C:: 
Type C is a classification of attack, also called an attack type.
Type C attacks are powered weapons that make one attack roll per combat unit.
A powered weapon requires no physical effort by the persona to cause damage. 
Examples are bolt-action rifles, crossbows, aerosols, or lazer eyes. 

Type D:: 
Type D is a classification of attack, also called an attack type.
Type D attacks are powered weapons that make two attack rolls per combat unit.
A powered weapon requires no physical effort by the persona to cause damage. 
Examples are semi-auto rifle, electron rifle, fission pistol or faster lazer eyes. 


Type E:: 
Type E is a classification of attack, also called an attack type
Type E attacks are powered weapons that make three attack rolls per combat unit.
Powered weapons require no physical effort by the persona to cause damage. 
Examples are burst lasers, or fission rifle, plastix rifle, or crazy fast lazer eyes. 

Type F:: 
Type F is a classification of attack, also called an attack type. 
Type F attacks are powered weapons the fire fully automatic.
Fully automatic in EXP is 5 attack rolls per combat unit, where each attack represents up to 3 rounds.
Powered weapons require no physical effort by the persona to cause damage. 
Examples are full-auto lasers, machine guns, or holy crap dangerous lazer eyes. 

Unit:: 
The unit is the smallest component of combat time in EXP. 
All personas will move, attack of do part of something during each unit. 
A unit of combat may take ten minutes or an hour of real time to play.
The combat unit is 2 seconds.

Vocation:: 
This is a collection of innate abilities that the persona has.
A vocation could arise from innate skill, training or school. 
Also called a class.

Wate:: 
A unique spelling of the word weight in EXP., 
The wate includes inertia, mass, and general size. 

ZOG:: Zero gravity.

// generated vs  created vs fabricated vs evolved vs rolled
// pick from here the ones that go into introductory glossary
// terra mundane

// roll playing pithy aphorisms
// all your rolls are belong to us
// outcomes decided by dice and tables.
// outcomes not decided by referee thinkspace
// justification and post factualization
// From the outset both methods of play are equally valid.
// details details details


// role-playing pithy aphorisms
// the desired story of the ref and players wins
// less random 
// EXPS for role-playing
// theatrical combat system
// charisma and privilege tends to win
// not everyone is articulate enough

// run session game
// group expedition table party