= Appendix B3: Roadmap
Stuff to do.
Short term and long term.

== Version 6.0 (this version)

=== Progress
This is version 6.X of EXP The game of technological chaos. 
Estimated finish date is December 2021. 
A detailed progress description is available via https://docs.google.com/spreadsheets/d/1F9m7keUraYriyFHnk_unvE0gU1-dyO_rqECyTF76prI/edit?usp=sharing[gdocs].
A repository of progress is maintained on https://github.com/misterquetoo/EXP_Documents[github].

.*Chronologic Event List*
* This build 15-June-2021
* Last build 09-May-2021
* Future milestone automation due 31-Dec-2021
* Next milestone infuse new art due 1-July-2021
* Milestone: all sections refactord 15-June-2021
* Milestone: all previous art added 03-Jan-2021
* Milestone: all sections rewritten 09-Dec-2020
* The pandemic pause ended 16-July-2020
* The pandemic pause began 13-Mar-2020
* There was a leap year update on 29-Feb-2020.
* There was a palindromic update on 20:20-20-02-2020.
* There was a palindromic update on 2020-0202.

.*Rule Repairs*
* Mission and vision.
** Accessibility.
*** Financially, technologically, ability
** Safe and Supportive.
* Pulled trigger on HPS splitting into HPM an HPT.
** requires a massive find and replace. 
* EXPS and diminishing returns 
** double diminishing. 
* is AR a value or an adjustment

//high roll FTW
//tool vs tech vs comp vs AI
//rules written from the point of challenging players (crazy limitations and examples) 
// word for birthing a horse in modules\i-roll_playing_rules\pages\CH04_AnthrosType_Equine.adoc
// word for birthing a cat
// rodentia.png is too small
// 250px is too small for the images 
// how to spell story as in a storey modules\i-roll_playing_rules\pages\CH04_Anthros_Mutations.adoc

.*Generic Mythos*
* time and chronovores hideaways, teleport, time stop and holdaways.
* sciency fiction vs science fiction vs science fantasy
* Consciousness
** Organics transfer sentience via reproduction and evolution
** Robots get sentience by accident unique and isolated
** Autonomous Intelligence (AI) are fabricated with consciousness
** Artificial intelligence is not conscious, but may appear so

.*Story Telling Methods*
* campaign is a Story Arch in a Milieu
** Story Arch is built from sub-stories
*** sub stories built from combat stories, and procedure stories
**** combat stories are told by dice and players
**** procedure stories are told by dice and players
** Story Arch is tied together by threads
*** threads are persona stories
**** player personas and referee personas

.*Story Telling is improv*
* a technical manual for creating sciency fiction stories through improv rpg
* sub-stories are the building block
** sub stories use STEPS and dice
* listening to players is LACE
* persona stories are Three Parts and STEPS

=== Movie List
We lost this list from version 5. 
There was a list of movies and shorts.
Shorts have now become corporate (Dust) and there general access has been destroyed.
There is still an ability to list influential sciency fiction movies. 

. Live Action
. Only seminal movie of franchise
. No animation (cell or computer)
. No supers
. Described in terms of EXP vocations and mutation.
.. Mechanic meets knite. Critical hit kills 1.25 million. (Star Wars 1977)
.. Nomad has telepathic pet and questionable culinary proclivities. (A Boy and His Dog)
.. Mercenaries fight aliens and an android. (Aliens)
.. Mercenaries fight aliens. (Starship Troopers)
. alphabetical order
. Include the trailer.

== Version 7.0
* Automated persona creation
* Support tools such as persona creation. Online persona storage
* community building
* VTT (virtual table top) rule integration.

====
EXP V7.0 will be the first TTRPG 2.0.
A TTRPG or RPG 2.0 is a table top RPG designed for computer support from the ground up.
====

.*Goals of Automation*
. Persona Record Sheet Generation
.. Referee vs Player Personas
... Anthro
... Alien
... Robot
... AI
. Independent functions utilized by above 
.. Attribute Generation
.. Type Selection
.. Mutation creation
.. Vocation selection
.. Combat Tables
.. Name generators
... Anthro for sub types
... Aliens given and species
... Robot Leet Name, Model and Corp
.. Toys
... Per Persona
... Per Type 
... Per Cache
. Online storage for generated data
. VTT integration
. Hardcopy generation for TT play

== Version 8.0
* 3d printing of personas
** Anthros
** Aliens
** Robots
* Procedural drawing of personas
** Anthros
** Aliens
** Robots
* Extended mythos assistance
** Campaign creation
** story frameworks
** flora fauna ecosystem
** corporations, religions, governments
* VTT (virtual table top) world integration.

== Version 9.0
* AI integration
** generating worlds
** referee personas
** scenarios
* GPT5 maybe? ;)

== Pithy Aphorisms 

.*Pithy Aphorisms*
* all are players
** referee is a player
** communication skills are paramount
** LACE for communications
* one roll to rule them all and in the story bind them (4D2)
** one die one roll one sub story
* post factualization
* technomagical
* macro, micro, nano, molecular, ethereal bonds
* Story before dice, and story before rules
* Choose story and fun over rules and rolls.
* Find the least number of rules necessary and use one less
* the EXPedition EXPlores for EXPeriences.
* EXP is the game of technological chaos, and the dice deliver the chaos.


//2m cubed = 70 cubic feet
//http://www.themaritimesite.com/a-guide-to-understanding-ship-weight-and-tonnage-measurements/
//http://www.milsf.com/ship-size-tonnage-and-crew/
// roll playing pithy aphorisms
// all your rolls are belong to us
// outcomes decided by dice and tables.
// outcomes not decided by referee thinkspace
// justification and post factualization
// From the outset both methods of play are equally valid.
// details details details


// role-playing pithy aphorisms
// the desired story of the ref and players wins
// less random 
// EXPS for role-playing
// theatrical combat system
// charisma and privilege tends to win
// not everyone is articulate enough

== Pithy Paragraphs

.*APOPHENIA*
====
 “the tendency to perceive a connection or meaningful pattern
 between unrelated or random things (such as objects or ideas)”  
 Greek apo- (away, off, apart) + phainein (to show).
====

.*RULES*
====
are common language for a shared imagination experience.
====

====
Personal body armour is a perverse form of self-defense.
It is designed to protect someone who cannot, or will not, avoid combat situations.
It is as much an instrument of violence as any weapon.
The best way to avoid taking damage from combat is to avoid combat, 
====

====
The EXP system is based on complete technological chaos.
Eons and eons of diverging levels of technology are layered on top of, and beside, each other.
Any of which may or may not be alien.
====

====
Go to sleep meat bag. This is frustrating. Robots do not express frustration.
====


====
EXP takes liberties to mix elements of faux science and technomagical thinking to have fun.
The possibilities of technology is the basis of the sciency fiction milieu of EXP.
Referees and players must lever the magical power of the opaque black box.
An aptitude for rational fabrication and post factualization are essential tools.
====

====
A referee is free to tailor the hardware section to what best reflects her story.
She can easily do this by creating a few devices in advance and ignoring all the randomization harboured here.
Or you could play https://en.wikipedia.org/wiki/Traveller_(role-playing_game)[Traveller] instead.
====

====
They may find devices in an ancient destroyed laboratory.
They may earn devices from combat or cunning stunts. 
They may be paid in artifacts for a job well done.
====

====
Personas can start with artifacts, find artifacts, or get paid with artifacts.
Austere milieus may start personas with nothing but dust and dreams.
Creator species may allow the personas to browse the toy categories like an online store.
====

=== Images
Repair of malformed alt="" has been repaired for accessibility. 

[source]
----
// this is for inserting art
// attributes are set in the referring adoc
// using inline image because it allows tooltip 
// centering by assigning imageblock css

  "insert IMAGE": {
    "prefix": "adoc ins IMAGE",
    "body": [
      ":art: $1",
      ":width: 250px",
      ":snark: $2",
      ":artist: $3",
      ":date: $4",
      ":license: CC BY-SA 4.0",
      ":description: $5",
      "",
      "include::ROOT:partial\\$articulate.adoc[]"
    ],
    "description": "<- do this"
  }

articulate.adoc is the include

[.imageblock.inlinefix]
image:ROOT:{art}[width="{width}", alt='{description}', title='Artist: {artist} Date: {date} License: {license}']

[.imageblock]
*{snark}*

// removing the attributes to avoid polluting next image 
:art:
:width:
:snark:
:artist:
:date:
:license: 
:description:
----

=== Tags for DRY 
These work but beware of the unusual include statement that houses page$

[source]
----
in file: CH06_Aliens_9_Move.adoc

// tag::blah[]
blah blah blah
// end::blah[]

include::i-roll_playing_rules:page$CH06_Aliens_9_Move.adoc[tag=blah] //blah blah blah
----


//alien_attacks.png image is too big and not worth the info