= Appendix C1: Generic Mythos

IMPORTANT: *Welcome friend of EXP. You are in an unfinished section of EXP. Please be curious.*

EXP has a *generic mythos* that acts as a framework for the sciency fiction fun.
This generic mythos is a loose affiliation of faux concepts and pseudo nomenclature.
These two non-existent descriptors help rationalize this sciency fiction world.
This loose affiliation of ideas is supposed to make the game more fun. 

== The Spaces
The spaces are a faux concept with a pseudo nomenclature that defines where stuff is. 
Physical Space is the space in which we mundanely live. 
This Physical Space is the space in which we pretend to have the most knowledge. 
The other faux spaces exist to defy reality in the Physical Space and tell fun sciency fiction stories.

:art: all_your_space_RBU.png
:width: 750px
:snark: Space for everyone
:artist: Hugh
:date: 2020
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

== The Races
EXP moved away from the term races in the 1990s. 
The generic mythos supports a faux taxonomy that sounds sciency but is appearance-based.
In sciency-language, appearance equals phenotype.
So EXP's faux taxonomy is organized by phenotype and nothing else. 
Life in EXP encompasses any consciousness. 
That consciousness can exist in an anthro, alien, robot or AI. 
Players create anthros, evolve aliens, and fabricate robots.

:art: Life.jpg
:width: 750px
:snark: Life's what you make it.
:artist: HM
:date: 2020
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

== Outer Spaces
EXP has its own language for differentiating vehicle types.
The primary separation is planetary versus extraplanetary.
Planetary vehicles are mundane terra ones like cars, trucks and planes.
Inatmo vehicle is another term for a planetary vehicle because they are constrained to being "in the atmosphere."
Extraplanetary vehicles are the staple of sciency fiction and are capable of traversing the stars.
Exatmo vehicle is another term for an extraplanetary vehicle are because they can function "exterior to the atmosphere."
Exatmo vehicles have a host of different identifiers based on what they can do in outer space.

include::ROOT:partial$CH38_Table_Nomenclature_of_Space_Vehicles.adoc[]

== Artifacts
An artifact is a collective term for tools, devices, machines, weapons, or junque that the personas encounter.
An artifact is anything that the players have no identified yet. 
Equipment is an artifact that the players have identified for their personas.
The system that generates these artifacts is massive and is called the Technological Object Yield System.
Player often refer to technological artifacts as toys. 
Toys are the generic equivalent of magic items in fantasy RPGs.

== Tech Levels
Tech level is a shortening of the term technological levels.
The premise of tech levels in EXP is that any civilization can accomplish any technological achievement.
However, the size, complexity, and required resources to accomplish that achievement are what differ. 
This premise is the basis of how anything can appear anywhere at any time. 
The artifact could be from an extinct civilization, an existing civilization, an alien civilization, or a clumsy time traveller. 

NOTE: EXP is called *The game of technological chaos* for a reason.

In short, the higher the tech level, the smaller, lighter, more valuable and hard to understand an artifact is.
Tech level 10 is our present mundane terra tech level. 

include::ROOT:partial$CH56_Table_Tech_Level_and_the_Time_Piece.adoc[]

== Kirlian Energy
The concept of Kirlian energy and auras has a long history of pseudo-scientific poppycock.
In EXP, Kirlian energy, aura and forces are a sciency fiction extension of https://en.wikipedia.org/wiki/Kirlian_photography[Kirlian Auras,window=_blank].
In EXP, the Kirlian auras happen as the Think Space interfaces with the Physical Space.
The phenomenon of Kirlian energy can be caused by an entity that is a powerful conductor of the Think Space.
The phenomenon of Kirlian energy can be caused by an entity that is a potent disruptor of Physical Space. 

:art: kirlian_koins.jpg
:width: 250px
:snark: Kirlian auras surrounding money.
:artist: Unknown
:date: 2020
:license: Public Domain

include::ROOT:partial$articulate.adoc[]

Kirlian auras can be read and manipulated in the Physical Space.
Only one vocation can use Kirlian auras in this way.
The persona's ability to manipulate these Kirlian auras is what allows them to pursue this vocation.
This vocation is called the Knite. 
The Kirlian auras empower Knites to carry out psionic shenanigans in the Physical Space.  

== Knites, Anti-Knites and Kirlian Auras
There are no alignments in EXP. 
In other fantasy RPGs, moral alignments such as evil, neutral and good guide the persona's choices.
The vocation of knite is an exception to this rule of amorality. 
As powerful conduits of Kirlian energy a knit is bound to either order or chaos.
Whether a knite follows order or chaos she is a powerful amplifiers of the Kirlian force. 
The degree of organization behind the knite depends on the campaign.
Knites may operate individually or in large organizations promoting either order or chaos.
In EXP order and chaos are different sects. 
The sects can go by other names as well: orders, churches, light vs dark. 
Choose the nomenclature that fits your milieu.

NOTE: Kirlian Auras FTW. Not just because Midi-Chlorians suck. 

Knites are potent conductors of the Think Space.
They prefer order and respect life. 
Anti-knites are potent disruptors of the Physical Space. 
They prefer chaos and do not respect life. 
All knites are powerful amplifiers and users of Kirlian energy. 
Order versus chaos creates the classic good vs evil paradigm for Knites.
Where ever one finds Knites, there will be Anti-knites and vice versa. 

Both sects manipulated the Kirlian energy to carry out their missions in the Physical Space.
The knite is a vocation.
It may or may not involve training. 
It may or may not involve religion.
The generic mythos of the knite sets the stage for paladins, Jedis yogis, and other mystical fighters.

== Energy and Power
The zany collection of technological artifacts all require power to operate.
Many players don't worry about how artifacts are powered and simply let everything work all the time.
Not worrying about how artifacts get power is a perfectly valid campaign choice and fun.
A scarcity based campaign may need a framework for energy sources. 
Not surprisingly, EXP has a faux framework for how things get energy and keep running.
The power and energy framework in EXP lends itself to fun sciency fiction explanations.

There are four sources of energy in EXP, cells, fuel cells, fuel and power sources.
Cell, aka batteries, are for personal artifacts that need portable power.
Fuel cells are specifically for robots and not found anywhere else.
Fuel is for planetary and extraplanetary vehicles.
Power sources represent architectural infrastructure that resembles our mundane terra electrical grids. 

* Artifacts get energy from cells (batteries)
* Robots get energy from a fuel cell.
* Vehicles get energy from fuel. 
* Cities get energy from power sources

The energy sources have three different formats: basic, rechargeable, and continuous.
Basic energy sources are expendable and disposable.
Batteries on mundane terra are an example of basic cells.
Rechargeable energy sources charge themselves.
When a solar cell runs out of energy, bright light can recharge it.
Continuous energy sources deliver energy without interruption.
A broadcast cell delivers energy from a continuous energy source.

* Basic energy sources are disposable
* Rechargeable energy sources can replenish themselves
* Continuous energy sources offer uninterrupted energy

There are basic, rechargeable and continuous batteries. 
There are basic, rechargeable and continuous fuel types. 
The various energy sources are replete with sciency fiction nomenclature: nuclear, magnetic, solar, and psionic, to name a few.

== Basic cells
Basic cells contain chemicals that react to create electricity.
One would hope that the nature of these chemicals is so advanced an explanation is optional.
For story telling purposes the chemical could be anything: natural gas, manure, hair, etc.
Recharging the power cell simply requires replacing the depleted materials.

=== Gas and Liquid Cells
Gas and liquid cells will cease operation if exposed to a vacuum.
This does not apply if the robot is exatmo hardened.
They will function as normal once atmosphere is restored.

=== Solid Cells
Solid cells function fine in vacuums, but do not function at high temperature.
Prolonged exposure to temperatures that may not damage the robot may damage its power cell.
Solid cells will function as normal once they cooled.
Extreme heat could destroy a bots solid cell.

== Broadcast
Broadcast cells are power receivers that convert transmissions from a source into energy.
The receivers will cease to function if they are electronically jammed or out of range.
When within range the robot has an endless supply of power.
Robots using broadcast power can store one month of power per point of CON.
A robot with a broadcast power source that runs out of stored charge must be placed back in range to recharge.

== Dynamo
Internal gyros spin up the electricity for this robot.
The countless dynamos are microscopic and silent. 
Cells offer no features beyond source.
Dynamos will not function when exposed to more than 2g.
The dynamos return to normal once gravity drops below 2g.
Dynamo cells can be recharged by plugging into the nearest electrical outlet.

== Gravitational 
This power cell filters gravitational waves into electrical energy.
An explanation of this technological miracle will not be attempted.
The gravitational force cannot exceed 3g or be less than one half g.
The robot will store energy for those instances where gravitational cell cannot function.
The robot has 1 hour of stored energy per point of CON.
Once out of power the robot will remain dormant until gravity normalizes.

== Magnetic 
Cellular magnetic forces are amplified to produce electrical power.
Magnetic cells will be disrupted by any magnetic based attacks or disruptions.
Severe disruptions may cause the cell to be demagnetized and require recharging.
This is left to the discretion of the referee.
Regeneration requires and electrical charge to re-magnetizes the power cells.

== Nuclear 
The nuclear power sources uses slow burn fusion, fission, etc., to produce electricity.
It is impossible for a this persona to explode like an atomic weapon.
The nuclear cell is so efficient that there is no radiation hazard.
The nuclear power source functions in all many or atmospheres and gravities.
Fissionable materials are required to replenish the nuclear batteries.

== Plasmoid 
Superheated gases contained in magnetic bottles fire up the robot for power.
This should make it virtually impossible for Mechanics to use the plasmoid cell maliciously.
The plasmoid cells have many safeguards that prevent their weaponization. 
Recharging plasmoid batteries requires the re-insertion of plasmoid materials.

== Psionic 
Psionic cells convert the surrounding psychic energy into electrical energy.
The psionic cell has the most complicated recharge process.
The batteries last for the usual one month per point of CON.
When it is time to recharge the cell drains local psionic energy.
The nearest persona will to the robot will be drained one point of MSTR to fully recharge the robot.
The persona gets a save vs psionic attack. 
The robot persona uses her CON as MSTR to calculate the saving throw. 
If the persona saves the robot moves onto the next persona.
The process is automated and the robot is unaware of who is attacked when.

== Solar 
The solar power source will keep the robot operational in any amount of light.
Artificial light and light from the nearest star work equally well.
If there is light this robot need not recharge.
If the robot should be plunged into darkness they will operate on stored power.
The robot can store 1 hour energy per point of CON.
A solar powered robot with a 16 CON could run for 16 hours in the dark.

== Ref's Own Table
Referee can insert campaign related power sources as she sees fit.


