= Appendix B3: Roadmap
:experimental: true

NOTE: *More of garbage collection than a roadmap.*

== Images
Repair of malformed alt="" has been repaired for accessibility. 

[source]
----
// this is for inserting art
// attributes are set in the referring adoc
// using inline image because it allows tooltip 
// centering by assigning imageblock css

  "insert IMAGE": {
    "prefix": "adoc ins IMAGE",
    "body": [
      ":art: $1",
      ":width: 250px",
      ":snark: $2",
      ":artist: $3",
      ":date: $4",
      ":license: CC BY-SA 4.0",
      ":description: $5",
      "",
      "include::ROOT:partial\\$articulate.adoc[]"
    ],
    "description": "<- do this"
  }



articulate.adoc is the include

[.imageblock.inlinefix]
image:ROOT:{art}[width="{width}", alt='{description}', title='Artist: {artist} Date: {date} License: {license}']

[.imageblock]
*{snark}*

// removing the attributes to avoid polluting next image 
:art:
:width:
:snark:
:artist:
:date:
:license: 
:description:
----

== Video
Presently video is stored in an /image folder that lives in the module where the page lives.
For example, /module/images/\*.mp4 this services only the pages in that module.
The poster attribute must be in this rogue folder as well.
This is different from still images.
Which are located in /ROOT/images/*.png and service the entire website

.Shadowrun Promo Excerpt (1990, FASA) 
video::shorter_run.mp4[width=426, height=240]


== Buttons
Button testing ground.
Maybe even create a partial like articulate..adoc
Antora does not support video at this point. 
Any hacks must be reversible to support eventual video section.
Buttons require the activation of experimental mode, but there is no documentation on how to activate experimental mode. 



.*Smaller Thing*
video::shorter_run.mp4[width=213, height=120, poster=video.png]

.*Poster and controls*
video::shorter_run.mp4[width=107, height=60, poster=video.png]

.*Poster and nocontrols*
video::shorter_run.mp4[width=107, height=60, poster=video.png, options="nocontrols"]

Press this btn:[Button] to find out how to activate experimental mode.

CAUTION: Actual roadmap starts here.

== ERRATA
Too many to even list here.


== ROADMAP

== Version 6.0 (this version)
Mission and vision.
Accessibility.
Safe and Supportive.


Pulled trigger on HPS splitting into HPM an HPT. 
requires a massive find and replace. 


Apophenia:: “the tendency to perceive a connection or meaningful pattern between unrelated or random things (such as objects or ideas)”  Greek apo- (away, off, apart) + phainein (to show).

.*Generic Mythos*
* time and chronovores hideaways, teleport, time stop and holdaways.
* sciency fiction vs science fiction vs science fantasy
* mutations mental, physical, evolution vs random, psionic vs physical space
* The power of mutations should be delicately balanced with subtle inconveniences.
* Roll vs Role
* Consciousness
** Organics transfer sentience via reproduction and evolution
** Robots get sentience by accident unique and isolated
** AI (artificial or autonomous) are fabricated with consciousness

.*Pithy Aphorisms*
* all are players
** referee is a player
** communication skills are paramount
** LACE for communications
* one roll to rule them all and in the story bind them (4D2)
** one die one roll one sub story
* post factualization
* technomagical
* macro, micro, nano, molecular, ethereal bonds
* Story before dice, and story before rules
* Find the least number of rules necessary and use one less
* the EXPedition EXPlores for EXPeriences.
* EXP is the game of technological chaos, and the dice deliver the chaos.

====
Personal body armour is a perverse form of self-defense.
It is designed to protect someone who cannot, or will not, avoid combat situations.
It is as much an instrument of violence as any weapon.
The best way to avoid taking damage from combat is to avoid combat, 
====


====
The EXP system is based on complete technological chaos.
Eons and eons of diverging levels of technology are layered on top of, and beside, each other.
Any of which may or may not be alien.
====


.*Story Telling Methods*
* campaign is a Story Arch in a Milieu
** Story Arch is built from sub-stories
*** sub stories built from combat stories, and procedure stories
**** combat stories are told by dice and players
**** procedure stories are told by dice and players
** Story Arch is tied together by threads
*** threads are persona stories
**** player personas and referee personas

.*Story Telling is improv*
* a technical manual for creating sciency fiction stories through improv rpg
* sub-stories are the building block
** sub stories use STEPS and dice
* listening to players is LACE
* persona stories are Three Parts and STEPS

//baked in for robots
//high roll FTW
//tool vs tech vs comp vs AI
//vocation
//Roll vs Role
//Tale of two systems
//Skills (knowledge base) procedure (actual act)
//rules written from the point of challenging players (crazy limitations and examples) 

// needs a milieu section


// these rules are common language for a shared imagination experience.

// is armour a fixed AR or an AR adjustment 

== Movie List
We lost this list from version 5. 
There was a list of movies and shorts.
Shorts have now become corporate (Dust) and there general access has been destroyed.
There is still an ability to list influential sciency fiction movies. 

. Live Action
. Only seminal movie of franchise
. No animation (cell or computer)
. No supers
. Described in terms of EXP vocations and mutation.
.. Mechanic meets knite. Critical hit kills 1.25 million. (Star Wars 1977)
.. Nomad has telepathic pet and questionable culinary proclivities. (A Boy and His Dog)
.. Mercenaries fight aliens and an android. (Aliens)
.. Mercenaries fight aliens. (Starship Troopers)
. alphabetical order
. Include the trailer.





== Version 7.0
Automated persona creation
Support tools such as persona creation. Online persona storage
community building
VTT (virtual table top) support.

== Version 8.0
3d printing of all personas
Campaign creation and story frameworks. Appendix C Mythos : C2 Creating
generation: flora fauna ecosystem, corporations, governments, 
VTT (virtual table top) integration.
