= Appendix B3: Roadmap

:art: space_phone_warranty.png
:width: 250px
:snark: We have been trying to reach you...
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Futuristic cellphone with warranty message.

include::ROOT:partial$articulate.adoc[]

The roadmap is a collection of stuff to do, both short term and long term.
This is closer to a collection of aspirations than a roadmap.
Perspiration has transformed some of these aspirations into rules.

== Version 6.0 (this version)

=== Progress
This is version 6.X of EXP The game of technological chaos. 
Estimated finish date is December 2021. 
A detailed progress description is available via https://docs.google.com/spreadsheets/d/1F9m7keUraYriyFHnk_unvE0gU1-dyO_rqECyTF76prI/edit?usp=sharing[gdocs].
A repository of progress is maintained on https://github.com/mobilehugh/EXP_Documents[github].

.*Chronologic Event List*
* This build 15-June-2021
* Last build 09-May-2021
* Future milestone automation due 31-Dec-2021
* Next milestone infuse new art due 1-July-2021
* Milestone: all sections refactored 15-June-2021
* Milestone: all previous art added 03-Jan-2021
* Milestone: all sections rewritten 09-Dec-2020
* The pandemic pause ended 16-July-2020
* The pandemic pause began 13-Mar-2020
* There was a leap year update on 29-Feb-2020.
* There was a palindromic update on 20:20-20-02-2020.
* There was a palindromic update on 2020-0202.

.*Rule Repairs*
* Mission and vision.
** Accessibility.
*** Financially, technologically, ability
** Safe and Supportive.
* Pulled trigger on HPS splitting into HPM an HPT.
** requires a massive find and replace. 
* EXPS and diminishing returns 
** double diminishing. 
* is AR a value or an adjustment

//high roll FTW
//tool vs tech vs comp vs AI
//rules written from the point of challenging players (crazy limitations and examples) 
// word for birthing a horse in modules\i-roll_playing_rules\pages\CH04_AnthrosType_Equine.adoc
// word for birthing a cat
// rodentia.png is too small
// 250px is too small for the images 
// how to spell story as in a storey modules\i-roll_playing_rules\pages\CH04_Anthros_Mutations.adoc

// getting git hub working

== Version 7.0
Active version as of 14-jan-2024.
This will be the first version as a 0.75 full time developer.
A detailed progress description is available at (TBA-spreadsheet).
A repository of progress is maintained at (TBA github repo).
Completion date is 14-June-2024.

.*Goals of Versions 7.x*
* move from letters to words 
** weapons types become descriptive
** attack tables instead of combat tables
** shorten STR and MND
* pre-roll implementation
* reorganize ROOT with sub-folders
* aimagination infiltration
* community building
* active promotions
* expansion of automation section
** how to make personas
** how to local copy exp
* move HPT back to HPS

.*Goals of Automation*
. Persona Record Sheet Generation
.. Referee vs Player Personas
... Anthro
... Alien
... Robot
... AI
. Independent functions utilized by above 
.. Attribute Generation
.. Type Selection
.. Mutation creation
.. Vocation selection
.. Combat Tables
.. Name generators
... Anthro for sub types
... Aliens given and species
... Robot Leet Name, Model and Corp
.. Toys
... Per Persona
... Per Type 
... Per Cache
. Online storage for generated data
. VTT integration
. Hardcopy generation for TT play

== Version 8.0
* 3d printing of personas
** Anthros
** Aliens
** Robots
* Procedural drawing of personas
** Anthros
** Aliens
** Robots
* Extended mythos assistance
** Campaign creation
** story frameworks
** flora fauna ecosystem
** corporations, religions, governments
* VTT (virtual table top) world integration.
* appendiceal add ons 
** Alien Arena
** Space Opera
** Postapocalypso
** Mutant fest


.*Version 7 punt downs*
* Automated persona creation
* Support tools such as persona creation. Online persona storage
* community building
* VTT (virtual table top) rule integration.
* images on or off 
* aimaginations vs images switch
* roll vs role switch
* d1000, 4d2 mechanic switch


====
EXP V7, er V8, um maybe V9, will be the first TTRPG 2.0.
A TTRPG or RPG 2.0 is a table top RPG designed for computer support from the ground up.
====

== Version 9.0
* AI integration
** generating worlds
** referee personas
** scenarios
* GPT5 maybe? ;)

== PROPOSAL: A d20 Task Roll 
Some find the Task Rolls in the Roll Playing system too much effort. 
It really does require maths and may slow down game play. 
The d20 Task Roll would align better with Saves and Competitions which are already d20 based.

The problem with a d20 task roll is that at higher level tasks the roll becomes irrelevant
Legacy system used three distinct die roll types.

.*Legacy d100 task rolls*
* d20 for attributes rolls
* d100 for task rolls
* d1000 for attack rolls


.*Steps for d20 Task Roll*
. <<_determine_difficulty,Determine Difficulty>>
. <<_determine_the_task_roll,Determine the Task Roll>>

=== Determine Difficulty
Knowing the difficulty of a task is only described generally. 
The persona would not know the actual number.

.*d20 Difficulty List*
* Facile - 2
* Trivial - 4
* Easy - 8
* Usual - 16
* Unusual - 24
* Hard - 32
* Really Hard - 38
* Tough - 64
* Impossible - 128
* Plot - 666 

=== Determine the Task Roll
The player rolls a d20 plus whatever bonuses apply.

.*Roll 1d20 plus...*
* Appropriate attribute
* Interests
* Skills
* Level
* Mutations?
* Fun description (1d4)

Players add all their rolls as part of a research team. 

== PROPOSAL: Attribute Nomenclature Update
The attributes Mental Strength (MSTR) and Physical Strength (PSTR) are vestiges of Metamorphosis Alpha.
The terms have avoided updating as they were considered an homage to the OG. 
Times are changing though.
There is no trouble with changing STR to STR. 
This attribute change is comprehensible. 
The challenge is what is MND changed too. 

____
Mental strength represents the persona’s will power, psionic ability, and luck. 
This attribute is a sciency fiction one with no physiologic connection to our mundane terra just yet. 
A persona with high Mind has excellent will power and resistance to influence. 
Mental strength is the crucial attribute powering mental mutations and psionic events. 
____

.*Proposed Changes to Attributes*
* Physical Strength (STR)-> Strength (STR)
* Mental Strength (MND) -> Mind (MND)

.MND Options
* Acuity
* Aura
* Cognition
* Flux
* Fortitude
* Grit
* Mastery
* Metaphysics
* Mindcraft
* Potentiality
* Psyche
* Psychokinesis
* Psychomotor
* Psychonics
* Radiance
* Resilience
* Resonance
* Serendipity
* Telekinesis
* Thoughtforce
* Volition
* Willforce


== PROPOSAL: Combat Table Nomenclature Simplification
Proposed rework of the Combat Table and its ancillary components. 
Goal is to reduce complexity and improve understanding. 
Underlying variable names will be unchanged in the tools application. 

These changes are being play tested. 
So far so good. 
Some abbreviations have changed on the persona record.

.*Proposed Changes to Weapon Types*
* Type A -> *Striking*: self powered melee weapons
* Type B -> *Flinging*: self powered ranged weapons 
* Type C -> *Shooting*: powered ranged weapons 
* Type D -> *Sotto*: Semi auto *Shooting* 2 attacks per unit
* Type E -> *Sotto*: Semi auto *Shooting* 3 attacks per unit
* Type F -> *Flotto*: Full auto *Shooting* 5 attacks per unit
* Type AOE -> *Grenade*: *Flinging* at target hex no damage bonus

.*Proposed Changes to Combat Table*
* Combat Table -> *Attack Table*
* BP (Skilled Bonus) -> *Skilled*
* BNP (Raw Bonus) -> *Raw*
* Max (Max Roll) -> *Max*
* DB (Damage Bonus) -> *Force*

NOTE: Raw may change to Unskilled. Raw is shorter and edgier.

// Proposed changes to Combat Table
.*Attack Table*
[width="95%",cols="<,^,^,^,^",frame="all", stripes="even"]
|===
5+<|What players add to their rolls in combat.

s|Attack Type
s|Raw
s|Skilled
s|Max
s|Force

s|Striking
|50
|100
|725
|6

s|Flinging
|65
|125
|775
|3

s|Shooting
|75
|150
|825
|0

|===


[width="95%",cols="^,<,<,<,<",frame="all", stripes="even"]
|===
5+<|ROW 1 lists the Attack Table headings.

s|Attack Type
4+|Type of attack being used. Striking vs Flinging vs Shooting.

s|Raw
4+|Player adds this number to attack rolls for unfamiliar weapons.


s|Skilled
4+|Player adds this number to attack rolls for proficient weapons.

s|Max
4+|This is the highest attack roll the player can make.

s|Force
4+|The player adds this number to the damage roll. 
|===

[width="95%",cols="^,<,<,<,<",frame="all", stripes="even"]
|===
5+<|ROW 2 lists the bonuses for striking attack types.

s|Striking
4+|Self powered melee weapons like swords, clubs, fists etc.

|Raw
4+|Player adds 50 to her attack roll when using an unfamiliar bat.

|Skilled
4+|Player adds 100 to her attack roll when using her familiar sword.

|Max
4+|If the player's attack roll is higher than 725 on her it becomes 725.

|Force
4+|Player adds 6 hit points of damage to her damage roll.
|===

[width="95%",cols="^,<,<,<,<",frame="all", stripes="even"]
|===
5+<|ROW 3 lists the bonuses for flinging attack types.

s|Flinging
4+|Self powered ranged weapons like daggers, bows, rocks and spears.

|Raw
4+|Player adds 65 to her attack roll when using an unfamiliar throwing spear.

|Skilled
4+|Player adds 125 to her attack roll when using her favourite bow.

|Max
4+|If the player's attack roll is higher than 775 her attack roll becomes 775.

|Force
4+|The player adds 3 hit points of damage to her damage roll.
|===


[width="95%",cols="^,<,<,<,<",frame="all", stripes="even"]
|===
5+<|ROW 4 lists the bonuses for shooting attack types.

s|Shooting
4+|Powered ranged weapons like guns, rifles, pistols. 

|Raw
4+|Player adds 75 to her attack roll when using an unfamiliar rifle.

|Skilled
4+|Player adds 150 to her attack roll when using her service revolver.


|Max
4+|If the player's attack roll is higher than 825 her roll becomes 825.

|Force
4+|No force bonus for shooting weapons. 
|===

[width="95%",cols="^,<,<,<,<",frame="all", stripes="even"]
|===
5+<|Special cases of Sotto, Flotto and Grenade

s|Sotto
4+|Attack Type *Shooting* with two or three attack rolls per unit. 

s|Flotto
4+|Attack Type *Shooting* with five attack rolls per unit.

s|Grenade
4+|Attack Type *Flinging* with no Force bonus. Target is a hex. 

|===

The above information is transient, and has changed since initial email proposal.
Other suggestions have included: Close Muscle, Ranged Muscle, Ranged Powered, Melee. 


== Broad Aspirations
Elements that remain aspirational. 

=== Generic Mythos
Missing parts from the generic mythos. 

.*Generic Mythos*
* time and chronovores hideaways, teleport, time stop and holdaways.
* sciency fiction vs science fiction vs science fantasy
* Consciousness
** Organics transfer sentience via reproduction and evolution
** Robots get sentience by accident unique and isolated
** Autonomous Intelligence (AI) are fabricated with consciousness
** Artificial Intelligence is not conscious, but may appear so

=== Story Telling and EXP
Personal thoughts of how improv and role playing intersect.

.*Story Telling Methods*
* campaign is a Story Arch in a Milieu
** Story Arch is built from sub-stories
*** sub stories built from combat stories, and procedure stories
**** combat stories are told by dice and players
**** procedure stories are told by dice and players
** Story Arch is tied together by threads
*** threads are persona stories
**** player personas and referee personas

.*Story Telling is improv*
* a technical manual for creating sciency fiction stories through improv rpg
* sub-stories are the building block
** sub stories use STEPS and dice
* listening to players is LACE
* persona stories are Three Parts and STEPS

=== Influential Movie List
We lost this resource when version 5 imploded. 
There was a list of movies and shorts.
Shorts have now become corporate (Dust) and there general access has been destroyed.
There is still an ability to list influential sciency fiction movies. 

.*Prerequisites*
. Live action preferred
. Only seminal movie of franchise
. No animation (cell or computer) -- flexible
. No supers -- absolute
. Described in terms of EXP vocations and snark.
.. Mechanic meets knite. Critical roll kills 1.25 million. (Star Wars, 1977)
.. Nomad has telepathic pet and questionable culinary proclivities. (A Boy and His Dog, 1975)
.. Mercenaries fight aliens and an android. (Aliens, 1985)
.. Mercenaries lose their powered are but still fight aliens. (Starship Troopers, 1997)
. alphabetical order
. Include the trailer.

=== Pithiness
A suite of sweet sayings.

.*Pithy Aphorisms*
* all are players
** referee is a player
** communication skills are paramount
** LACE for communications
* one roll to rule them all and in the story bind them (4D2)
** one die one roll one sub story
* post factualization
* technomagical
* macro, micro, nano, molecular, ethereal bonds
* Story before dice, and story before rules
* Choose story and fun over rules and rolls.
* Find the least number of rules necessary and use one less
* the EXPedition EXPlores for EXPeriences.
* EXP is the game of technological chaos, and the dice deliver the chaos.

=== Pithy Paragraphs
A posse of pithy paragraphs

.*APOPHENIA*
====
 “the tendency to perceive a connection or meaningful pattern
 between unrelated or random things (such as objects or ideas)”  
 Greek apo- (away, off, apart) + phainein (to show).
====

.*RULES*
====
are common language for a shared imagination experience.
====

====
Personal body armour is a perverse form of self-defense.
It is designed to protect someone who cannot, or will not, avoid combat situations.
It is as much an instrument of violence as any weapon.
The best way to avoid taking damage from combat is to avoid combat, 
====

====
The EXP system is based on complete technological chaos.
Eons and eons of diverging levels of technology are layered on top of, and beside, each other.
Any of which may or may not be alien.
====

====
Go to sleep meat bag. This is frustrating. Robots do not express frustration.
====


====
EXP takes liberties to mix elements of faux science and technomagical thinking to have fun.
The possibilities of technology is the basis of the sciency fiction milieu of EXP.
Referees and players must lever the magical power of the opaque black box.
An aptitude for rational fabrication and post factualization are essential tools.
====

====
A referee is free to tailor the hardware section to what best reflects her story.
She can easily do this by creating a few devices in advance and ignoring all the randomization harboured here.
Or you could play https://en.wikipedia.org/wiki/Traveller_(role-playing_game)[Traveller] instead.
====

====
They may find devices in an ancient destroyed laboratory.
They may earn devices from combat or cunning stunts. 
They may be paid in artifacts for a job well done.
====

====
Personas can start with artifacts, find artifacts, or get paid with artifacts.
Austere milieus may start personas with nothing but dust and dreams.
Creator species may allow the personas to browse the toy categories like an online store.
====

=== Images
[line-though]#Repair of malformed alt="" has been repaired for accessibility.#

//2m cubed = 70 cubic feet
//http://www.themaritimesite.com/a-guide-to-understanding-ship-weight-and-tonnage-measurements/
//http://www.milsf.com/ship-size-tonnage-and-crew/
// roll playing pithy aphorisms
// all your rolls are belong to us
// outcomes decided by dice and tables.
// outcomes not decided by referee thinkspace
// justification and post factualization
// From the outset both methods of play are equally valid.
// details details details
// the dice giveth and the dice taketh away


// role-playing pithy aphorisms
// the desired story of the ref and players wins
// less random 
// EXPS for role-playing
// theatrical combat system
// charisma and privilege tends to win
// not everyone is articulate enough
// philosophy of dice 
// role of the random in the roll
// a common language for a shared improvised experience


== Code Snippets (VS Code) 


[source]
----
// this is for inserting art
// attributes are set in the referring adoc
// using inline image because it allows tooltip 
// centering by assigning imageblock css

  "insert IMAGE": {
    "prefix": "adoc ins IMAGE",
    "body": [
      ":art: $1",
      ":width: 250px",
      ":snark: $2",
      ":artist: $3",
      ":date: $4",
      ":license: CC BY-SA 4.0",
      ":description: $5",
      "",
      "include::ROOT:partial\\$articulate.adoc[]"
    ],
    "description": "<- do this"
  }

articulate.adoc is the include

[.imageblock.inlinefix]
image:ROOT:{art}[width="{width}", alt='{description}', title='Artist: {artist} Date: {date} License: {license}']

[.imageblock]
*{snark}*

// removing the attributes to avoid polluting next image 
:art:
:width:
:snark:
:artist:
:date:
:license: 
:description:
----

=== Tags for DRY 
These work but beware of the unusual include statement that houses page$

[source]
----
in file: CH06_Aliens_9_Move.adoc

// tag::blah[]
blah blah blah
// end::blah[]

include::i-roll_playing_rules:page$CH06_Aliens_9_Move.adoc[tag=blah] //blah blah blah
----






