= Appendix C1: Generic Mythos

IMPORTANT: *Welcome friend of EXP. You are in an unfinished section of EXP. Please be curious.*

EXP has a *generic mythos* that acts as a framework for the sciency fiction fun.
This generic mythos is a loose affiliation of faux concepts and pseudo nomenclature.
These two non-existent descriptors are used to rationalize this sciency fiction world.
This loose affiliation of ideas is supposed to make the game more fun. 

== The Spaces
The spaces are a faux concept with a pseudo nomenclature that defines where stuff is. 
The physical space is the one we mundanely live in. 
It is one we pretend to know the most about. 
The other spaces exist to allow us to defy reality in the physical space. 

:art: all_your_space_RBU.png
:width: 750px
:snark: Space for everyone
:artist: Hugh
:date: 2020
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

== The Races
EXP moved away from the term races in the 1990s. 
The generic mythos supports a faux taxonomy that sounds sciency but is based on appearance.
In sciency language appearance equals phenotype.
So EXP's faux taxonomy is organized by phenotype and nothing else. 
Life in EXP encompasses any consciousness. 
That consciousness can exist in an anthro, alien, robot or AI. 
Anthros are created, aliens are evolved, and robots are fabricated.

:art: Life.jpg
:width: 750px
:snark: Life's what you make it.
:artist: HM
:date: 2020
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

== Outer Spaces
EXP uses it's own language for separating types of vehicles.
The major separation is planetary and extraplanetary.
Since most planets are defined by having atmosphere the planetary craft are inatmo (in atmosphere) and exatmo (external to atmosphere).

include::ROOT:partial$CH38_Table_Nomenclature_of_Space_Vehicles.adoc[]

== Artifacts
Artifacts is a collective term for tools, devices, machines, weapons, or junque that the personas encounter.
An artifact is anything that the players have no identified yet. 
Equipment is an artifact that the players have identified for their personas.
The system that generates these artifacts is massive, and is called the Technological Object Yield System.
Player often refer to technological artifacts as toys. 
Toys are the generic equivalent of magic items in fantasy RPGs.

== Tech Levels
Tech level is a shortening of the term technological levels.
The premise of tech level in EXP is that any civilization can achieve any technological success.
It is only the size, complexity, and resources required for that success that differs. 
This premise is the basis of the how everything can appear anywhere at anytime. 
The device could be from an extinct civilization, an existing civilization, an alien civilization, or a clumsy time traveller. 

NOTE: EXP was formerly called *The game of technological chaos*.

In short the higher the tech level the smaller, lighter, more valuable and hard to understand an artifact is.
Tech level 10 is our present mundane terran tech level. 

include::ROOT:partial$CH56_Table_Tech_Level_and_the_Time_Piece.adoc[]

== Kirlian Energy
The concept of kirlian energy and auras has a long history pseudo-scientific quagmire of poppycock.
In EXP kirlian energy, aura and forces are a sciency fiction extension of https://en.wikipedia.org/wiki/Kirlian_photography[Kirlian Auras,window=_blank].
In EXP the kirlian auras are caused by the Think Space leaking into the Physical Space.
The phenomenon can be caused by an entity that is a powerful conductor of the Think Space.
The phenomenon can be caused by an entity that is a powerful disruptor of the Physical Space. 

:art: kirlian_koins.jpg
:width: 250px
:snark: Kirlian auras surrounding money.
:artist: Unknown
:date: 2020
:license: Public Domain

include::ROOT:partial$articulate.adoc[]

Kirlian auras can be read and manipulated in the physical space.
Only one vocation is able to use kirlian auras in this way.
The persona's ability to use these kirlian auras is what allows them to pursue said vocation.
This vocation is called the Knite. 
Knites are empowered by the kirlian auras to carry out psionic shenanigans in the Physical Space.  

== Knites, Anti-Knites and Kirlian Auras
There are no alignments in EXP for any personas. 
In other fantasy RPGs players are guided by moral alignments such as evil, neutral and good.
The powerful conduits of the kirlian light are bound by their vocation to order and chaos. 
Both sects are powerful amplifiers of the kirlian force. 
Confusingly both are called knites.

NOTE: Kirlian Auras FTW. Not just because Midi-Chlorians suck. 

Knites are powerful conductors of the Think Space.
They prefer order and respect life. 
Anti-knites are powerful disruptors of the Physical Space. 
They prefer chaos and do not respect life. 
This makes knites power amplifiers and users of the kirlian energy. 
This is the classic good vs evil paradigm, and where there are Knites there are Anti-knites. 

Both sects manipulated the kirlian energy to carry out their missions on the material plane.
The knite is a vocation.
It may or may not involve training. 
It may or may not involve religion.
The generic mythos of the knite sets the stage for paladins, Jedis yogis, and other mystical fighters.

== Generic Stuff to Add
Here are the lists of things to add. 
They are divided into generic mythos and how to tell a story using a generic mythos.

Apophenia:: “the tendency to perceive a connection or meaningful pattern between unrelated or random things (such as objects or ideas)”  Greek apo- (away, off, apart) + phainein (to show).


.*Generic Mythos*
* time and chronovores hideaways, teleport, time stop and holdaways.
* sciency fiction vs science fiction vs science fantasy
* mutations mental, physical, evolution vs random, psionic vs physical space
* The power of mutations should be delicately balanced with subtle inconveniences.
* Roll vs Role


.*Pithy Aphorisms*
* all are players
** referee is a player
** communication skills are paramount
** LACE for communications
* one roll to rule them all and in the story bind them (4D2)
** one die one roll one sub story
* post factualization
* technomagical
* macro, micro, nano, molecular, ethereal bonds
* Story before dice, and story before rules
* Find the least number of rules necessary and use one less
* the EXPedition EXPlores for EXPeriences.

.*Story Telling Methods*
* campaign is a Story Arch in a Milieu
** Story Arch is built from sub-stories
*** sub stories built from combat stories, and procedure stories
**** combat stories are told by dice and players
**** procedure stories are told by dice and players
** Story Arch is tied together by threads
*** threads are persona stories
**** player personas and referee personas

.*Story Telling is improv*
* a technical manual for creating sciency fiction stories through improv rpg
* sub-stories are the building block
** sub stories use STEPS and dice
* listening to players is LACE
* persona stories are Three Parts and STEPS






