= Appendix B3: Roadmap

.*APOPHENIA*
====
 “the tendency to perceive a connection or meaningful pattern
 between unrelated or random things (such as objects or ideas)”  
 Greek apo- (away, off, apart) + phainein (to show).
====

.*RULES*
====
are common language for a shared imagination experience.
====


== ERRATA
Too many to even list here.


== ROADMAP

NOTE: *More of garbage collection than a roadmap.*

== Version 6.0 (this version)

.*Rule Repairs*
* Mission and vision.
* Accessibility.
* Safe and Supportive.
* Pulled trigger on HPS splitting into HPM an HPT.
** requires a massive find and replace. 
* SS is now SOC.
* EXPS and diminishing returns 
** double diminishing. 
* is AR a value or an adjustment

//baked in for robots
//high roll FTW
//tool vs tech vs comp vs AI
//vocations vs classes
//Roll vs Role
//Tale of two systems
//Skills (knowledge base) procedure (actual act)
// abilities inherent skills acquirable
//rules written from the point of challenging players (crazy limitations and examples) 

// needs a milieu section

.*Generic Mythos*
* time and chronovores hideaways, teleport, time stop and holdaways.
* sciency fiction vs science fiction vs science fantasy
* mutations mental, physical, evolution vs random, psionic vs physical space
* The power of mutations should be delicately balanced with subtle inconveniences.
* Roll vs Role
* Consciousness
** Organics transfer sentience via reproduction and evolution
** Robots get sentience by accident unique and isolated
** AI (artificial or autonomous) are fabricated with consciousness

.*Pithy Aphorisms*
* all are players
** referee is a player
** communication skills are paramount
** LACE for communications
* one roll to rule them all and in the story bind them (4D2)
** one die one roll one sub story
* post factualization
* technomagical
* macro, micro, nano, molecular, ethereal bonds
* Story before dice, and story before rules
* Choose story and fun over rules and rolls.
* Find the least number of rules necessary and use one less
* the EXPedition EXPlores for EXPeriences.
* EXP is the game of technological chaos, and the dice deliver the chaos.

====
Personal body armour is a perverse form of self-defense.
It is designed to protect someone who cannot, or will not, avoid combat situations.
It is as much an instrument of violence as any weapon.
The best way to avoid taking damage from combat is to avoid combat, 
====

====
The EXP system is based on complete technological chaos.
Eons and eons of diverging levels of technology are layered on top of, and beside, each other.
Any of which may or may not be alien.
====

====
Go to sleep meat bag. This is frustrating. Robots do not express frustration.
====

.*Story Telling Methods*
* campaign is a Story Arch in a Milieu
** Story Arch is built from sub-stories
*** sub stories built from combat stories, and procedure stories
**** combat stories are told by dice and players
**** procedure stories are told by dice and players
** Story Arch is tied together by threads
*** threads are persona stories
**** player personas and referee personas

.*Story Telling is improv*
* a technical manual for creating sciency fiction stories through improv rpg
* sub-stories are the building block
** sub stories use STEPS and dice
* listening to players is LACE
* persona stories are Three Parts and STEPS

=== Movie List
We lost this list from version 5. 
There was a list of movies and shorts.
Shorts have now become corporate (Dust) and there general access has been destroyed.
There is still an ability to list influential sciency fiction movies. 

. Live Action
. Only seminal movie of franchise
. No animation (cell or computer)
. No supers
. Described in terms of EXP vocations and mutation.
.. Mechanic meets knite. Critical hit kills 1.25 million. (Star Wars 1977)
.. Nomad has telepathic pet and questionable culinary proclivities. (A Boy and His Dog)
.. Mercenaries fight aliens and an android. (Aliens)
.. Mercenaries fight aliens. (Starship Troopers)
. alphabetical order
. Include the trailer.

== Version 7.0
* Automated persona creation
* Support tools such as persona creation. Online persona storage
* community building
* VTT (virtual table top) rule integration.

== Version 8.0
* 3d printing of personas
** Anthros
** Aliens
** Robots
* Procedural drawing of personas
** Anthros
** Aliens
** Robots
* Extended mythos assistance
** Campaign creation
** story frameworks
** flora fauna ecosystem
** corporations, religions, governments
* VTT (virtual table top) world integration.

== Version 9.0
* AI integration
** generating worlds
** referee personas
** scenarios
* GPT5 maybe? ;)



== Testing Zone
Things that have been worked out or are being worked out regarding Antora and the static site.


=== Images
Repair of malformed alt="" has been repaired for accessibility. 

[source]
----
// this is for inserting art
// attributes are set in the referring adoc
// using inline image because it allows tooltip 
// centering by assigning imageblock css

  "insert IMAGE": {
    "prefix": "adoc ins IMAGE",
    "body": [
      ":art: $1",
      ":width: 250px",
      ":snark: $2",
      ":artist: $3",
      ":date: $4",
      ":license: CC BY-SA 4.0",
      ":description: $5",
      "",
      "include::ROOT:partial\\$articulate.adoc[]"
    ],
    "description": "<- do this"
  }



articulate.adoc is the include

[.imageblock.inlinefix]
image:ROOT:{art}[width="{width}", alt='{description}', title='Artist: {artist} Date: {date} License: {license}']

[.imageblock]
*{snark}*

// removing the attributes to avoid polluting next image 
:art:
:width:
:snark:
:artist:
:date:
:license: 
:description:
----

=== Tags for DRY writing 
These work but beware of the unusual include statement that houses page$

[source]
----
in file: CH06_Aliens_9_Move.adoc

// tag::blah[]
blah blah blah
// end::blah[]

include::i-roll_playing_rules:page$CH06_Aliens_9_Move.adoc[tag=blah] //blah blah blah

----

=== Video
After deliberation I have decided to go with vimeo.
Antora is supposed to work with vimeo stream directly. 
Following is the test.

=== Video as a Link

https://vimeo.com/521640030[Link to Xeno Scrot]


=== Video as a Link in a box 

====
https://vimeo.com/521640030[Link to Xeno Scrot]
====

=== Video as an Embed in a box

.*VIDEO AS EMBED - NO ATTRIBUTES*
====
video::521640030[vimeo]
====

=== Video Divider

.*VIDEO AS EMBED - width="640"*
video::521640030[vimeo, width="640"]


=== Video as an Embed in a box

.*VIDEO AS EMBED - width="640"*
====
video::521640030[vimeo, width="640"]
====




=== Video Divider

.*VIDEO AS EMBED - width="640", height="640"*
video::521640030[vimeo, width="640", height="640"]

=== Video Divider

.*VIDEO AS EMBED - width="640", height="480"*
video::521640030[vimeo, width="640", height="480"]