= Appendix A2: Glossary of Terms

Ability:: 
Any capacity that the persona has.
Abilities include gifts, interests, skills, mutations and baked in features.

Adjusted:: 
An attribute that is adjusted by the persona's experience level. 
Adjusted MND is the persona's MND plus EXPS Level.

Alien:: 
Aliens are organic personas of unusual shape and size.
In the faux taxonomy they are called Diversidae.
Playing an alien persona requires an experienced player.
They are alien to us but not to themselves.
These are the tentacled, furry, floating horse creatures.

Anthro:: 
Anthros are organic personas, and are upright, bipedal humanoids.
In the faux taxonomy they are called Hominidae.
Anthro is short for anthropomorph.
Playing an anthro persona is highly recommended for players.
The entire rule set, and technology system is based on anthros.

Anthrocentric::
Same as anthropocentric, but not limited to humans.

Area of effect:: 
The area in which targets are subjected to damage or special effects. 
It is measured in hexes.
The value usually gives a radius for a spherical area of effect.

Amour Rating (AR):: 
The amour rating of the persona indicates how well she is protected from damage in combat. 
The higher the armour rating value the less likely she is to be damaged.

Attack roll::
The dice roll that is used to see if a target was successfully attacked.
The higher the to hit roll the better.
Usually the to attack roll generated must be higher than an armour rating to indicate success.
A successful attack roll indicates the target has been has been hit.
A win on the attack roll does not always indicate damage will be inflicted on the target

Attack table::
A table that lists the attack information of a persona.

Attack types::
Attack types are used to define how a weapon attacks and inflicts damage.
Attack types are in transition. What follows is new name and old name. 
Strike, Type A: non-powereed thrusting and striking attacks
Fling, Type B: non-powered projectile attacks
Shoot, Type C: powered projectile attacks

Attributes:: 
These are the imaginary divisions of a persona’s physical abilities.
They are also called statistics, or stats.

Baked-In:: 
An indistinguishable part of a system.
As opposed to bolted on and obviously an after thought.
Robot peripherals can be baked-in when they are part of the robot's fabrication as opposed to added later.

Bonus non-proficient (BNP):: 
The attack roll bonus used when the persona is using an unfamiliar weapon. 
This value is less than the attack roll bonus used for familiar weapons.

Bonus proficient (BP):: 
The attack roll bonus used for familiar weapons.
Being familiar with a weapon is called a weapon proficiency.

Bot:: 
Shortened form of robot.

Campaign:: 
This is the story generated by the referee and the players.
A campaign is built from scenarios.
The scenarios can involve many personas and different locations. 
A campaign can last for months or years.

Class:: 
Vocation.

Damage:: 
Damage is inflicted if a persona is injured.
Damage is reflected in the persona losing hit points. 
The amount of hit points lost is the damage. 
The more lethal an attack, the more damage it inflicts.

Damage Adjustor (DA):: 
This value is added to the damage roll for certain weapon types. 
The stronger the persona is, the more damage she will inflict.

Damage Bonus (DB):: 
This value is added to the damage roll for certain weapon types. 
The stronger the persona is, the more damage she will inflict.

Decidie::
See Percentile Dice. 
A way to generate 1 to 100 by rolling 2d10s.

Dice:: 
* 1d1 - A one sided die. Looks like a mobius strip.
* 1d2 - A two sided die. Looks like a coin
* 1d3 - A three sided die. Looks like a risk piece.
* 1d4 - A four sided die. Looks like a pyramid.
* 1d6 - A six sided die. The famous cube.
* 1d8 - An eight sided die. It does not look like an octopus.
* 1d10 - A ten sided die. This die is used to create 1d100 and 1d1000
* 1d12 - A twelve sided die. What a 3d calendar might look like.
* 1d20 - A twenty sided die. The largest of platonic solids.
* 1d100 - Two (tens and digits) 1d10 are rolled to create a 1d100.
* 1d1000 - Three (hundreds, tens and digits) 1d10 are rolled to create a 1d1000.
* Kilodie - Another name for a 1d1000
* Percents - Another name for a 1d100
* Decidie - Another name for a 1d100

Die::
Usually refers to the singular of dice.
One dice is a die.
I have been told to "get lost and one dice."

Die roll:: 
A die roll indicates that a random number must be generated. 
Because the numbers are generated by dice, it is called a die roll.

Evolution:: 
The creation of an alien persona using dice and rules in EXP.

Exatmo:: 
Short for exterior to atmosphere.
Anything that takes place in the vacuum of outer space. 

Expedition:: 
The group of personas exploring in EXP.
EXP version of a party of adventurers.

Experience (EXPS):: 
Experience is a combination of learning, maturation and training.
Experience is measured in experience points. 
The more experience points a persona has the better they are at stuff. 
A persona with higher experience will be more successful at combat and skills. 
Experience points are earned through successful die rolls and role-playing. 

Fabrication:: 
The creation of a robot persona using dice and EXP rules. 
Not a lie. 

Family:: 
The three families in EXP are anthro, alien and robot.
The anthro type pure strain human has different anthro types, not families.

Fling::
Fling is a classification of attack, also called an attack type.
Fling attacks are non-powered ranged weapons. 
Non-powered means that the persona must generate the force to inflict damage.
Some examples are bows, rocks, darts, launchable quills, and caustic spit.

Generation:: 
The creation of something (persona, artifact, result) by rolling dice and using EXP rules.

Flotto::
Short form of full-auto which means fully automatic. 
Usually a machine gun of some type.

Gift::
A gift is an ability that is baked into the persona.
A gift cannot be learned by another persona.
Vocation gifts come by many names like knacks, crafts, approaches or tricks.

Hexes per Unit (h/u):: 
This is an arbitrary measure of movement EXP. 
It is equivalent to m/s.

Hex (h):: 
A hex, short for hexagon. 
The hexagon is six sided figure.
Hexagons can interconnect to create a hex field. 
The hex field is used to portray tactical combat on the table top. 
A hex equals 2 metres. 

HIG:: 
High gravity.

Hit Points (HPS):: 
The persona's hit points indicate how much damage she can take. 
A persona with many hit points can sustain a lot of damage. 
A persona loses hit points when she is hurt. 
If a persona loses too many hit points they die.

Hit Points Max (HPS Max, HPM):: 
The maximum number of hit points that the persona has.
Being at hit poits max is the least damage a persona can be.
The persona cannot exceed her hit points max from healing.

Hit Points Total (HPS Total, HPT):: 
Deprecated. See Hit Points

Hit:: 
A hit is usually from a win on an attack roll.
A hit is a combat term that indicates a target has been damaged. 
When a hit is scored, the target usually loses hit points.

Hite:: 
A unique measure to EXP that means height.
It can also be used to compare sizes regardless of family type.
Hite is recorded in centimeters (cm).

Inatmo:: 
Short for in atmosphere.
Anything that takes place in normal atmosphere. 

Initiative:: 
Initiative is a way of determining the order of play between the personas. 
Initiative  includes  speed, skill and luck of the persona.

Intensity:: 
Intensity represents how dangerous a poison or psionic attack is. 
The higher the intensity, the more dangerous the attack.

Interest::
An interest is a vocation ability that covers a broad number of tasks.
For example, an interest is research will help a persona do any research task.
A skill in robot drives would only help with robot drive tasks.  

Kilodie:: 
A Kilodie generates a random number between 1 and 1000. 
A kilodie is also called a 1d1000
A roll of 0, 0, 0, would indicate 1000.
The kilodie is composed of three ten sided dice:
* 1d10 is the 100s
* 1d10 is the 10s
* 1d10 is the 1s

include::ROOT:partial$CH27_Table_Tactical_Kilo.adoc[]

Level:: 
A short form of experience level.
A level represents how good a persona is at combat and skills.
The experience level increases with the persona's experience points.

Maximum Roll (MR):: 
This is the highest possible attack roll that the player can score. 
The MR is determined by attributes, experience level and weapon type.

Miss:: 
A miss is any failed roll.
In combat a miss is a failed attempt to damage the target.
In a saving throw a miss represents being afflicted by the attack.

Movement:: 
Movement is the changing of position of personas during combat. 
Each persona has a movement rate in hexes per unit.
This is the speed of the persona.

Mutation:: 
Mutations are imaginary biological adaptations.
They can give personas imaginary powers or defects.
For anthros mutations are unique changes to that persona.
For aliens mutations are unique biological skills of the species.
For robots mutations are wildly malfunctioning peripherals.

Party:: 
Group of adventurers that EXP calls an expedition.

Performance Roll:: 
Deprecated. See Task Roll. 

Persona:: 
The persona is the representation of the player in the imaginary world.
The persona can be controlled by a player or a referee.
Each persona is made up of attributes, description and story.

Persona Record::
This is the persona record sheet.
It is a piece of paper or computer thingy that stores the persona's info.
Also called a character sheet.

Phenotype::
Phenotype is the physical appearance of an organism. In EXP life forms are arranged phenotypically by appearance. Anthros are all humanoid, robots look mechanical. This ignores genotype and fabrication for purpose of telling fun stories. 

Percentile Dice::
A percentile generates a random number between 1 and 100. 
A percentile die is also called a 1d100, or decidie.
A roll of 0, 0, would indicate 100.
The percentile is composed of two ten sided dice:
* 1d10 is the 10s
* 1d10 is the 1s

Player:: 
You, the reader. 
The real world persona that controls the fantasy world character called a persona.

Post Factualization::
Reverse improvisation to explain something that happened after it has happened. 
Commonly needed by referees when story and pseudo science need to be synched.

Proficiency::
A legacy term that indicates that a persona has skill with a weapon.

Ref::
Short for referee. 
This is a player that is burdened with creating the milieu and puzzles of the campaign.
The role of referee is typically one player.
The role of referee can be rotated or shared amongst multiple players.

Referee Persona (RP):: 
A persona that is generated and played by the referee. 
It includes aliens, anthropomorphs and robots. 
These are also called non-player characters.

Ref's Own Table:: 
This comment is found on tables used to generate EXP chaos.
It indicates that the referee and players should create something new. 

Robots::
Robots are inorganic personas built from metal and computer Intelligence.
In the faux taxonomy they are called Machinidae.
Playing a robot persona requires an experienced player.
Robots are often called robots.
Robots develop free will through malfunction. 

Roll:: 
Usually refers to rolling dice to generate a random number and infuse chaos into story telling.
Roll 1d10 means pick up a ten sided die and roll it onto the table.
Roll also refers to pushing a button to generate a random number on a computer.

Roll Playing System::
A role-playing game with a rule set that is built around dice rolling for the sake of dice rolling. 
The majority of decisions are decided by die rolls.

Role Playing System::
A role-playing game with a rule set where players make make the majority of decision.

Roll vs Role:: 
Roll and role are interchangeable causing much confusion. 
Roll refers to anything from the dice heavy Roll Playing system.
Role refers to anything from the talk heavy Role Playing system.

Run::
Run refers to players getting together and playing EXP.
Run also refers to playing (or running) a persona.
A run is also called a scenario.

Saves:: 
A save is a special kind of roll that refers to non-combat challenges.
Saves are using rolled against a unique attack.
Save vs poison and save vs mental attack are the most famous.
If the player misses the saving throw their persona is subjected to the attack.

Saving Roll:: 
See saves.

Scene::
A part of a scenario.
A scene could be a combat scene, or a negotiation or shopping for spare parts.

Scenarios:: 
These stories and challenges that take place in the game.
A scenario could be combat, puzzles, or some combination. 
Enough scenarios will build a story arch called a campaign.
These can also be called runs.

Sciency fiction:: 
A style of speculative fiction that uses science sounding words to create a consistent imaginary world.
Separate from science fiction in that sciency fiction has no allusion to any science grounding.
Separate from science fantasy in that sciency fiction maintains respect for consistent narrative reality.

Session:: 
Session refers to players getting together and playing EXP.
Session also refers to playing (or running) a persona.
A session is also called a run or scenario.

Shoot::
Shoot is a classification of attack, also called an attack type.
Shoot attacks are powered weapons that make one attack roll per combat unit.
A powered weapon requires no physical effort by the persona to cause damage. 
Examples are bolt-action rifles, crossbows, aerosols, or lazer eyes. 

Skill:: 
A capacity that can be learned by a persona.
Usually vocation related maneuver or knowledge like working with robots.
A skill is focused while an interest is broad. 
A skill can be learned while a gift cannot.

Strike::
Strike is a classification of attack, also called an attack type.
Strike attacks are non-powered thrusting and striking weapons. 
Non-powered means that the persona must generate the force to inflict damage.
Strike attacks are limited to one attack roll per combat unit.
Examples are swords, clubs, daggers, claws, teeth and punches.

Sotto::
Short form of semi-auto which means semi-automatic. 
Usually a gun that can shoot multiple times per combat turn.

Mundane Terra:: 
The only known inhabited planet. 
Mundane terra refers to cultural, technological and biological constructs on our planet.

Table:: 
Group of players that get together to play table top role playing games like EXP.
The table can also refer to the physical table that the minis and mat rest upon.

Task Roll:: 
A specific die roll where the player must roll high for her persona to succeed at a task.
Task rolls are typically made on a 1d100.
 
To Hit roll:: 
Deprecated. An attack roll.

Tool Score:: 
The tool score is a number that indicates how proficient a species is at using tools and technology.
The highest level is creator which we have not yet acheived on mundane terra.

Toys/TOYS:: 
Toys are devices from that personas use to gain strength and power.
Toys are like magical items from fantasy games.
Toys are created on the Technological Object Yield System.

Type A:: 
Type A is a classification of attack, also called an attack type.
Type A attacks are non-powered thrusting and striking weapons. 
Non-powered means that the persona must generate the force to inflict damage.
Type A attacks are limited to one attack roll per combat unit.
Examples are swords, clubs, daggers, claws, teeth and punches.

Type B:: 
Type B is a classification of attack, also called an attack type.
Type B attacks are non-powered ranged weapons. 
Non-powered means that the persona must generate the force to inflict damage.
Some examples are bows, rocks, darts, launchable quills, and caustic spit.

Type C:: 
Type C is a classification of attack, also called an attack type.
Type C attacks are powered weapons that make one attack roll per combat unit.
A powered weapon requires no physical effort by the persona to cause damage. 
Examples are bolt-action rifles, crossbows, aerosols, or lazer eyes. 

Type D:: 
Type D is a classification of attack, also called an attack type.
Type D attacks are powered weapons that make two attack rolls per combat unit.
A powered weapon requires no physical effort by the persona to cause damage. 
Examples are semi-auto rifle, electron rifle, fission pistol or faster lazer eyes. 

Type E:: 
Type E is a classification of attack, also called an attack type
Type E attacks are powered weapons that make three attack rolls per combat unit.
Powered weapons require no physical effort by the persona to cause damage. 
Examples are burst lasers, or fission rifle, plastix rifle, or crazy fast lazer eyes. 

Type F:: 
Type F is a classification of attack, also called an attack type. 
Type F attacks are powered weapons the fire fully automatic.
Fully automatic in EXP is 5 attack rolls per combat unit, where each attack represents up to 3 rounds.
Powered weapons require no physical effort by the persona to cause damage. 
Examples are full-auto lasers, machine guns, or holy crap dangerous lazer eyes. 

Unit:: 
The unit is the smallest component of combat time in EXP. 
All personas will move, attack of do part of something during each unit. 
A unit of combat may take ten minutes or an hour of real time to play.
The combat unit is 2 seconds.

Vocation:: 
This is a collection of innate abilities that the persona has.
A vocation could arise from innate skill, training or school. 
Also called a class.

Wate:: 
A unique spelling of the word weight in EXP., 
The wate includes inertia, mass, and general size. 

ZOG:: 
Zero gravity.