= Appendix C1: Generic Mythos

IMPORTANT: *Welcome friend of EXP. You are in an unfinished section of EXP. Please be curious.*

EXP has a *generic mythos* that acts as a framework for the sciency fiction fun.
This generic mythos is a loose affiliation of faux concepts and pseudo nomenclature.
These two non-existent descriptors help rationalize this sciency fiction world.
This loose affiliation of ideas is supposed to make the game more fun. 

== The Spaces
The spaces are a faux concept with a pseudo nomenclature that defines where stuff is. 
Physical Space is the space in which we mundanely live. 
This Physical Space is the space in which we pretend to have the most knowledge. 
The other faux spaces exist to defy reality in the Physical Space and tell fun sciency fiction stories.

:art: all_your_space_RBU.png
:width: 750px
:snark: Space for everyone
:artist: Hugh
:date: 2020
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

== The Races
EXP moved away from the term races in the 1990s. 
The generic mythos supports a faux taxonomy that sounds sciency but is appearance-based.
In sciency-language, appearance equals phenotype.
So EXP's faux taxonomy is organized by phenotype and nothing else. 
Life in EXP encompasses any consciousness. 
That consciousness can exist in an anthro, alien, robot or AI. 
Players create anthros, evolve aliens, and fabricate robots.

:art: Life.jpg
:width: 750px
:snark: Life's what you make it.
:artist: HM
:date: 2020
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

== Outer Spaces
EXP has its own language for differentiating vehicle types.
The primary separation is planetary versus extraplanetary.
Planetary vehicles are mundane terra ones like cars, trucks and planes.
Inatmo vehicle is another term for a planetary vehicle because they are constrained to being "in the atmosphere."
Extraplanetary vehicles are the staple of sciency fiction and are capable of traversing the stars.
Exatmo vehicle is another term for an extraplanetary vehicle are because they can function "exterior to the atmosphere."
Exatmo vehicles have a host of different identifiers based on what they can do in outer space.

include::ROOT:partial$CH38_Table_Nomenclature_of_Space_Vehicles.adoc[]

== Artifacts
An artifact is a collective term for tools, devices, machines, weapons, or junque that the personas encounter.
An artifact is anything that the players have no identified yet. 
Equipment is an artifact that the players have identified for their personas.
The system that generates these artifacts is massive and is called the Technological Object Yield System.
Player often refer to technological artifacts as toys. 
Toys are the generic equivalent of magic items in fantasy RPGs.

== Tech Levels
Tech level is a shortening of the term technological levels.
The premise of tech levels in EXP is that any civilization can accomplish any technological achievement.
However, the size, complexity, and required resources to accomplish that achievement are what differ. 
This premise is the basis of how anything can appear anywhere at any time. 
The artifact could be from an extinct civilization, an existing civilization, an alien civilization, or a clumsy time traveller. 

NOTE: EXP is called *The game of technological chaos* for a reason.

In short, the higher the tech level, the smaller, lighter, more valuable and hard to understand an artifact is.
Tech level 10 is our present mundane terra tech level. 

include::ROOT:partial$CH56_Table_Tech_Level_and_the_Time_Piece.adoc[]

== Kirlian Energy
The concept of Kirlian energy and auras has a long history of pseudo-scientific poppycock.
In EXP, Kirlian energy, aura and forces are a sciency fiction extension of https://en.wikipedia.org/wiki/Kirlian_photography[Kirlian Auras,window=_blank].
In EXP, the Kirlian auras happen as the Think Space interfaces with the Physical Space.
The phenomenon of Kirlian energy can be caused by an entity that is a powerful conductor of the Think Space.
The phenomenon of Kirlian energy can be caused by an entity that is a potent disruptor of Physical Space. 

:art: kirlian_koins.jpg
:width: 250px
:snark: Kirlian auras surrounding money.
:artist: Unknown
:date: 2020
:license: Public Domain

include::ROOT:partial$articulate.adoc[]

Kirlian auras can be read and manipulated in the Physical Space.
Only one vocation can use Kirlian auras in this way.
The persona's ability to manipulate these Kirlian auras is what allows them to pursue this vocation.
This vocation is called the Knite. 
The Kirlian auras empower Knites to carry out psionic shenanigans in the Physical Space.  

== Knites, Anti-Knites and Kirlian Auras
There are no alignments in EXP. 
In other fantasy RPGs, moral alignments such as evil, neutral and good guide the persona's choices.
The vocation of knite is an exception to this rule of amorality. 
As powerful conduits of Kirlian energy a knit is bound to either order or chaos.
Whether a knite follows order or chaos she is a powerful amplifiers of the Kirlian force. 
The degree of organization behind the knite depends on the campaign.
Knites may operate individually or in large organizations promoting either order or chaos.
In EXP order and chaos are different sects. 
The sects can go by other names as well: orders, churches, light vs dark. 
Choose the nomenclature that fits your milieu.

NOTE: Kirlian Auras FTW. Not just because Midi-Chlorians suck. 

Knites are potent conductors of the Think Space.
They prefer order and respect life. 
Anti-knites are potent disruptors of the Physical Space. 
They prefer chaos and do not respect life. 
All knites are powerful amplifiers and users of Kirlian energy. 
Order versus chaos creates the classic good vs evil paradigm for Knites.
Where ever one finds Knites, there will be Anti-knites and vice versa. 

Both sects manipulated the Kirlian energy to carry out their missions in the Physical Space.
The knite is a vocation.
It may or may not involve training. 
It may or may not involve religion.
The generic mythos of the knite sets the stage for paladins, Jedis yogis, and other mystical fighters.

== Energy and Power
The zany collection of technological artifacts all require power to operate.
Many players don't worry about how artifacts are powered and simply let everything work all the time.
Not worrying about how artifacts get power is a perfectly valid campaign choice and fun.
A scarcity based campaign may need a framework for energy sources. 
Not surprisingly, EXP has a faux framework for how things get energy and keep running.
The power and energy framework in EXP lends itself to fun sciency fiction explanations.

There are four sources of energy in EXP, cells, fuel cells, fuel and power sources.
Cell, aka batteries, are for personal artifacts that need portable power.
Fuel cells are specifically for robots and not found anywhere else.
Fuel is for planetary and extraplanetary vehicles.
Power sources represent architectural infrastructure that resembles our mundane terra electrical grids. 

* Artifacts get energy from cells (batteries)
* Robots get energy from a fuel cell.
* Vehicles get energy from fuel. 
* Cities get energy from power sources

The energy sources have three different formats: basic, rechargeable, and continuous.
Basic energy sources are expendable and disposable.
Batteries on mundane terra are an example of basic cells.
Rechargeable energy sources charge themselves.
When a solar cell runs out of energy, bright light can recharge it.
Continuous energy sources deliver energy without interruption.
A broadcast cell delivers energy from a continuous energy source.

* Basic energy sources are disposable
* Rechargeable energy sources can replenish themselves
* Continuous energy sources offer uninterrupted energy

There are basic, rechargeable and continuous batteries. 
There are basic, rechargeable and continuous fuel types. 
The various energy sources are replete with sciency fiction nomenclature: nuclear, magnetic, solar, and psionic, to name a few.




