= Automation   

[quote]
____
*Better living through electricity.*
____


== EXP Tools
There are two EXP tools available.
They both live on github. 
Both are used locally and have dependencies.
They are covered by CC 4.0 share and share alike open source license. 

=== EXP ruleset
The ruleset allows players to build a static HTML website with all the rules and silliness on their local machine.
This will require a build tool called https://docs.antora.org/antora/latest/[Antoradocs].
The ruleset lives on Github at https://github.com/mobilehugh/EXP_Documents[EXP Documents].
The details of building your own local copy of EXP are found on Github.

=== EXP Tool Set
The tool set allows players top create and store player and referee personas.
The personas are stored in json, can be read on screen or stored as a pdf.
This will require an up to date install of https://www.python.org/downloads/[Python].
The tool set lives on Github at https://github.com/mobilehugh/EXP_Game_Tools[EXP Game Tools].
The details for using the tool set are found on Github.

== Virtual Table Tops (VTT)
Virtual table tops have been the grognard's computer fantasy since the 1980s.
Now that they have arrived en force the grognards hate them.

=== Plague Years (2020-2022)
During the plague years many many new virtual table tops and online aids came into being. 
Our table became a network and we used  the following configuration. 
This configuration is no longer suitable and hopefully we will get things sorted by the next plague. 

.*Playing EXP Online*
* https://shmeppy.com[Shmeppy for Maps]
* https://rolz.org[Rolls for Dice Rolling, chat and persona records] -> dice room 
* https://zoom.us[Zoom for Voice and video chat]


=== EXP Compatibility
VTTs follow the money, and the money is with Hasbro.
Very few VTTs are usable with EXP. 
EXP has several obscure die rolls (4D2 and Kilodie) that make it incompatible.

.*These should work*
* https://foundryvtt.com[Foundry - For the devs!]
* https://roll20.net[Roll20 - For their cash!]
* https://www.rptools.net/[RPTools - For the FOSS!]


=== EXP Compatibility Table
Face it, I just like making asciidoc tables. 

.*Legend*
* Link - click to activate hypertext anchor magic.
* Dice - Yes = can do kilodie and 4D2 dice rolls.
* Map - Yes = can do hexagons on maps.
* Snark - what I think. FOSS = Free and Open Source Stuff.

// VTT LIST NOT IN partials
.*EXP and the VTT*
[width="85%",cols="<1,^1,^1,<3",frame="all", stripes="even"]
|===
4+<|VTTs and EXP compatibility. 

s|Link
s|Dice
s|Map
s|Snark

|https://www.rptools.net/[RPTools]
|Yes
|Yes
|FOSS! Local use only.


|http://roll20.net[Roll20]
|Yes
|Yes
|Apple of VTTs

|http://foundryvtt.net[Foundry]
|Yes
|Yes
|Dev friendly. User unfriendly

|http://shmeppy.com[Shmeppy]
|No
|No
|Lo Fi Maps.

|https://www.owlbear.rodeo/[Owlbear]
|No
|Yes
|Easy onboarding

|https://lets-role.com/[Lets Role]
|Yes
|Yes
|tres francais

s|Link
s|Dice
s|Map
s|Snark
|===


.*Awaiting Assessment*
* https://www.kloogeinc.com/
* http://www.epictable.com/
* https://www.fantasygrounds.com/
* https://talespire.com/
* https://d20pro.com/
* https://www.tableplop.com/
* https://rolisteam.org/
* https://standardaction.net/
* https://www.mipui.net/
* http://battlegroundsgames.com/
* https://www.astraltabletop.com/
* https://www.tabletopsimulator.com/
* http://www.3dvtt.com/
* https://www.nbos.com/products/skwyre
* http://fabletop.com/
* http://itabletop.com/
* https://www.battlemapp.io/
* https://www.theskygrotto.com/
* https://digitald20.com/
* https://illuminantgames.com/gtove/
* http://homebrewedgames.com/