= Automation   

[quote]
____
*Better living through electricity.*
____

== EXP Tools
There are two EXP tools available.
They both live on github. 
Both are used locally and have dependencies.
They are covered by CC 4.0 share and share alike open source license. 

=== EXP ruleset
The ruleset allows players to build a static HTML website with all the rules and silliness on their local machine.
This will require a build tool called https://docs.antora.org/antora/latest/[Antoradocs, window="_blank", rel="noopener noreferrer"].
The ruleset lives on Github at https://github.com/mobilehugh/EXP_Documents[EXP Documents, window="_blank", rel="noopener noreferrer"].
The details of building your own local copy of EXP are found on Github.

=== EXP Tool Set
The Tool Set is no longer public.
There is an extensive python program that will create anthro, alien, or robot personas.
The program allows the user to make Fresh (by the book first level), Bespoke (tailored to user's needs), or Random personas.
The personas can be stored, edited, and illustrated. 
The tool will create US Letter sized PDFs that are ready for campaign play or Death Match play. 

If you would like access to this tool contact the author. 

=== Online Kilodie
Sometimes you don't have your dice with you and you need to roll from 1-1000.
The website https://kilodie.expgame.com[kilo-die, window="_blank", rel="noopener noreferrer"] has what you need. 
Just roll from 1 to 1000, or calculate your persona's attack table. 

=== Online 4D2
Sometimes you don't have your dice with you and you need to know how your decision will turn out.
The website https://4d2.expgame.com[4D2, window="_blank", rel="noopener noreferrer"] has what you need.
Just roll 2d6 minus 2d6 or have the entire descriptor and outcome revealed as well. 


== Virtual Table Tops (VTT)
Virtual tabletops have been the grognard's computer fantasy since the 1980s.
Now that they have arrived en force the grognards hate them.
EXP has several obscure die rolls (4D2 and Kilodie) that make it incompatible.
There are presently no VTTs that are compatible with EXP.

.*These should work*
* https://foundryvtt.com[Foundry - For the devs!, window="_blank", rel="noopener noreferrer"]
* https://roll20.net[Roll20 - For their cash!, window="_blank", rel="noopener noreferrer"]
* https://www.rptools.net/[RPTools - For the FOSS!, window="_blank", rel="noopener noreferrer"]
* https://https://www.owlbear.rodeo[Owlbear Rodeo - For the people!, window="_blank", rel="noopener noreferrer"]

=== Plague Years (2020-2022)
During the plague years many many new virtual tabletops and online aids came into being. 
The tools we used were https://shmeppy.com[Shmeppy for Maps, window="_blank", rel="noopener noreferrer"], https://rolz.org[Rolls for Dice Rolling, chat and persona records, window="_blank", rel="noopener noreferrer"] and https://zoom.us[Zoom for Voice and video chat, window="_blank", rel="noopener noreferrer"].
Our table became a network and we used  the following configuration. 
This configuration is no longer suitable and hopefully we will get things sorted by the next plague. 
Presently we are only playing IRL around a table. 

