= Credits

[quote]
____
*It takes a village to raise an RPG.*
____

Versions in chronological order.
Most recent last.
Thanks to everyone.

== Version 0
Can't throw enough respect to https://en.wikipedia.org/wiki/Metamorphosis_Alpha[Metamorphosis Alpha]. 
EXP is a homebrew based on this RPG.
Eventually I would like to populate this with which seeds lead to EXP. 


== Version 1
*Homebrew 1980 by Hugh MacLeod*

Notes::
Typed on an olivetti underwood electric typewriter. 
Photocopied sections contained in D-Ring binders.

Special Thanks:: 
The minds that changed the meaning of what a game meant, and how collective play could work. https://en.wikipedia.org/wiki/Jim_Ward_(game_designer)[James Ward] (https://en.wikipedia.org/wiki/Gamma_World[Gamma World], and https://en.wikipedia.org/wiki/Metamorphosis_Alpha[Metamorphosis Alpha]); Gary Gygax and Dave Arneson (Dungeons and Dragons). 

While https://en.wikipedia.org/wiki/Space_Opera_(role-playing_game)[Space Opera] came along much later it demonstrated that an organized game with epic, comedic space shenanigans was possible.

== Version 2 
*Copywrite © 1983 by Hugh MacLeod*

:art: exp_1983.png
:width: 250px
:snark: Commodore 64 and crafting.
:artist: HM, ED
:date: 1983
:license: Copyright 1983 Hugh MacLeod
:description: Diagram of EXP logo from 1983.

include::ROOT:partial$articulate.adoc[]

:art: hard_copy_1983-86.jpg
:width: 250px
:snark: Hard copy 1986
:artist: ED 
:date: 1986
:license: Copyright 1983 Hugh MacLeod
:description: Hard copies built by ED.

include::ROOT:partial$articulate.adoc[]


== Version 3.01 
*Copywrite © 1990 by Hugh MacLeod*

:art: exp_1993.png
:width: 250px
:snark: Before Corel Draw worked.
:artist: HM, ED
:date: 1993
:license: CC BY-SA 4.0
:description: Diagram of EXP logo from 1990.

include::ROOT:partial$articulate.adoc[]


== Version 4.01
*Copywrite © 1993 by Hugh MacLeod*

:art: exp_1993_front.png
:width: 450px
:snark: Front Cover 1993
:artist: Eric Hotz
:date: 1991
:license: CC BY-SA 4.0
:description: Painting of human, robot and humanoid insect standing in front of DNA circuit board.

include::ROOT:partial$articulate.adoc[]

:art: exp_1993_colour.jpeg
:width: 250px
:snark: Cerlox copies of the last millennium
:artist: Eric Hotz
:date: 1991
:license: CC BY-SA 4.0
:description: Painting of human, robot and humanoid insect standing in front of DNA circuit board.

include::ROOT:partial$articulate.adoc[]

All rights reserved. 
No copies may be made, in whole or in part, without the expressed written consent of the author. 
This includes digitizing onto super computers, or the ink quill copying made by small furry gremlins.
The Game of Technological Chaos, EXP and the EXP logo are all trademarks of MERV Engineering, Inc.

Written and Designed::
Hugh MacLeod

Editing::
Efrosini Drimoussis, Nick Fleming, Afton Lewis, Jason Montgomery, Bruce Murray, Allen Sens, James MacLeod, Patrick Redding, Dave New

Rule Testers::
Clint Hocking, Jason Montgomery, Bruce Murray, Allen Sens, James MacLeod

Play Testers::
Clint Hocking, Jason Montgomery, Bruce Murray, Allen Sens, James Macleod, Ilmar Weemes, Stephen White, Afton Lewis, Derek Krezeski, Nick Lacoumantas, Randy Parris, Anyone that ever complained, Jason Gilley, Nick Langford, Nick Fleming, Nick Kwan, Mark Kwan, Greg Dunn, Jason Liebert, Dave Bulman, John Sirmul, Karl Innes, Joe Jeffries, plus a few more.

Art Direction::
Mike Jackson

Illustrators::
Mike Jackson, Patrick Redding, Andrew Brechan, Jim Nelson, Eric Hotz, Peggy Lynn McAasic, Duncan X, Mike Deane, Warren Oddsson

Desktop Publishing::
Patrick Redding

:art: exp_1993_back.png
:width: 450px
:snark: Back cover 1993
:artist: Eric Hotz, copy HM
:date: 1991
:license: CC BY-SA 4.0
:description: Painting of a human in flight suit surrounded by alien bunnies.

include::ROOT:partial$articulate.adoc[]

== Version 5.0
*Copywrite 2010  Hugh MacLeod* +
Creative Commons License Share and share alike with attribution.

:art: exp_game_headliner.png
:width: 
:snark: Title header for 2010 WordPress site.
:artist: Unknown 
:date: 1990
:license: Copyright 1990 Hugh MacLeod
:description: Head and shoulder painting of alien, human and robot.

include::ROOT:partial$articulate.adoc[]

Web Development:: 
Hugh MacLeod

Typing:: 
Kimberly Jonasson

Play Testers:: 
Colin, Liam, Jimmy, Benin, Ben, Nigel, Duncan, Rico

Special Thanks:: 
Tobias Bäthge (https://tablepress.org/[Tablepress]), PDF to text (https://www.onlineocr.net/[OnlineOCR])

== Version 5.01
*Copywrite 2018 Hugh MacLeod* +
Creative Commons License share and share alike with attribution.

:art: exp_game_headliner.png
:width: 
:snark: Title header for 2018 WordPress site.
:artist: Unknown 
:date: 1990
:license: Copyright 1990 Hugh MacLeod
:description: Head and shoulder painting of alien, human and robot.

include::ROOT:partial$articulate.adoc[]

Unexpected revision required by a database scramble. Many typos, errors, and grammar mangles fixed.

Web Repairs:: 
Hugh MacLeod

Special Un-thanks:: 
Google Cloud Products. Proprietary incomprehensibility.
JIBC PCP Program. 
Bunch of hateful, cruel, racist, sexist destructive creeps.

== Version 6.0
*Copywrite 2020  Hugh MacLeod* +
Creative Commons License Share and share alike with attribution.

:art: exp_game_headliner.png
:width: 
:snark: Header for 2020 index page.
:artist: Unknown 
:date: 1990
:license: Copyright 1990 Hugh MacLeod
:description: Head and shoulder painting of alien, human and robot.

include::ROOT:partial$articulate.adoc[]

Static Site Migration:: 
Hugh MacLeod

Special Thanks::
https://docs-as-co.de/[Docs as Code].
https://asciidoctor.org/[Asciidoctor].
https://docs.antora.org/antora/latest/[Antoradocs].

Rule Evolutions::
Hugh MacLeod

Additional Artists::
https://www.patreon.com/jeshields/posts[JE Shields], Hugh MacLeod, Studiostoks 2015

Play Testers::
Eric Green, Sam Weisbrod, Leanne Zarour, Craig Addison, Jeff Templeton, Susan Carroll, Kathy Garneau, Stephan Smith

== Version 6.1
*Copywrite 2021  Hugh MacLeod* +
Creative Commons License Share and share alike with attribution.

Rule Evolution::
Refactoring and intense grammar corrections

Automation::
Preliminary pythonic automation available at https://github.com/mobilehugh/EXP_Game_Tools[Tools]

== Version 6.2
*Copywrite 2023  Hugh MacLeod* +
Creative Commons License Share and share alike with attribution.

Rule Evolution::
Hugh MacLeod +
Refactoring of vocation gifts and skills. 
Many tiny irritating typographical corrections.

Rule Automation::
Hugh MacLeod +
Client side terminal based python tool for persona creation https://github.com/mobilehugh/EXP_Game_Tools[Tools]

Play Testers::
Arthur Bullock, Eammon Bullock, Liam MacLeod, Craig Addison, Colin MacLeod, Stephan Smith

== Version 7.0
*Copywrite 2024  Hugh MacLeod* +
Creative Commons License Share and share alike with attribution.

:art: exp_game_headliner.png
:width: 
:snark: Header for 2024 index page.
:artist: Unknown 
:date: 1990
:license: Copyright 1990 Hugh MacLeod
:description: Head and shoulder painting of alien, human and robot.

include::ROOT:partial$articulate.adoc[]

Special Thanks::
https://docs-as-co.de/[Docs as Code] +
https://asciidoctor.org/[Asciidoctor] +
https://docs.antora.org/antora/latest/[Antoradocs]

Rule Evolutions::
http://hughmacleod.com[Hugh] +
letters to words (type A -> Strike, etc) +
improved 4d2 mechanic descriptors +
infilling pre-rolled RPs and TOYs
adding alts to 

Artists::
https://www.patreon.com/jeshields/posts[JE Shields] +
Hugh MacLeod mashups, Aimaginations (Dolly 2 and Dolly 3) +
Studiostoks 2015

Play Testers::
Stephen Smith +
Liam MacLeod +
Colin MacLeod +
Craig Addison +
Rich Ellis +

== Version 7.1
*Copywrite 2024  Hugh MacLeod* +
Creative Commons License Share and share alike with attribution.

Play Testers::
Stephen Smith +
Liam MacLeod +
Colin MacLeod +
Jamie MacLeod +
Rinki Mann +
Amber Monteiro +
Craig Addison +
Rich Ellis +
Mike Howie +

.*changes in 7.1*
* completed by http://hughmacleod.com[Hugh] +
* letters to words is complete
** Type A -> Strike Attack
** Type B -> Fling Attack
** Type C -> Shoot Attack
*** Type D and E -> Sotto Attack
*** Type F -> Flotto Attack
** Type G -> Area
*** Grenade (Fling no Force Bonus)
*** Aerosol (Shoot)
* Armour Rating -> Defence Rating
** AR -> DEF
* Hit Points rationalized
** HPT -> HPS
** HPS Max -> HPM
* Mental Strength -> Mind
** MSTR -> MND
* Physical Strength -> Strength
** PSTR -> STR

== Version 7.2
*Copywrite 2024  Hugh MacLeod* +
Creative Commons License Share and share alike with attribution.

.*changes in 7.2*
* completed by http://hughmacleod.com[Hugh]
* improved nomenclature
** mental mutations -> psionics
** physical mutations -> phenomics
** veterinarian equipment -> biorepair
** miscellaneous weapons -> armaments
** miscellaneous equipment -> devices and gadgets
** pharmaceuticals -> pharma
** exatmo vehicles -> spacecraft
** inatmo vehicles -> vehicles
* new sections
** Mundance equipment
** Materiel
** Pre Rolls 

Three will no further versioning recorded here. 
Github will keep the changes public, and the doc will be referred to as rules.expgame.com.
If folks require more detailed versioning it may appear.
**HM 2024_0613_1926**

== Version 2025_0305
*Copywrite 2025 Hugh MacLeod* +
Creative Commons License Share and share alike with attribution.

Play Testers::
Stephen Smith +
Liam MacLeod +
Colin MacLeod +
Julie Vorha +
Amber Monteiro +
Craig Addison +
Rich Ellis +
Kyle Faas +
James Thornton

.*changes in this version*
Corrections of typos and much input on usefulness of tasks, skills, and expertise of vocations.


== Near Roadmap
The near roadmap is what we are working on at this very momement. 
For bonkers ideas and past failed ideas jump to xref:appendices:roadmap.adoc[Roadmap].

.*Goals for Next Version*
* clarify nomenclature around 
** Tasks
** Skills
** Interests
** Expertise
** Gifts 
* Create the Project system
** replaces research team with a targetted goal for large projects
** side quest generator 
** cause of failure generator
* rework the persona record to reflect rolls
** attribute rolls d20 plus attribute
** task rolls d100 plus competency
** attack rolls d1000 plus proficiency
