= Generic Mythos

EXP has a *generic mythos* that acts as a framework for the sciency fiction fun.
This generic mythos is a loose affiliation of faux concepts and pseudo nomenclature.
These two non-existent descriptors help rationalize this sciency fiction milieu.
This loose affiliation of ideas is supposed to make the game more fun. 

NOTE: in time generic mythos will move to https://wikexpedia.org[wikexpedia.org]

== Sciency Fiction
The chosen term to describe the content that is written for EXP. 
"Sciency fiction" is not an official genre, but it is used here to informally to describe works that feel like science fiction but are either:

* Core elements: Story over substance, technobabble, science fiction fun, and storyful decisions.
* Loosely based on science, with hand-wavy explanations ("quantum stuff", "neural tech", etc.)
* More about the aesthetic of science than scientific rigor
* Sometimes used dismissively, like “faux science fiction” or soft sci-fi”

=== Mundane Terra
Mundane terra is most likely where you are reading this now. 
Our home planet with an atmosphere of gas that is an admixture of 20% oxygen and lots of nitrogen. 
This atmosphere is held onto the planet by gravity that we call 1g. 
All the references to air, water, gravity, life support and pressure are based on mundane terra.
The biology on this cosmologic spacecraft of ours is diverse beyond imagination. 
Using our planet, mundane terra, as a reference allows for a common ground related to our lived experience. 

Good sciency fiction will explore places different from mundane terra. 
There are some tools and rules that can guide the referee when deviating from the biome of mundane terra.

=== Anthropocentric
Mundane terra is dominated by a species of anthropomorphic humanoids called homo sapiens.
The species is diverse in colour, size, shape and smell.
EXP is based on a world of these bipedal upright humanoids with opposable thumbs and common physiologic needs.
The weights and measures, shapes, durations and effects of all equipment, mutations, and combat are based on these humanoids. 

Good sciency fiction will explore non-athropomorphic shapes and physiologies. 
There are extensive tools for creating non-anthropomorphic personas. 
There are almost no rules for playing robots or aliens in the anthro centered mundane terran world of EXP. 
Guidelines exist for how robots and aliens would be challenged by the existing mythos. 

=== Austerity
The chosen generic mythos for EXP is one of austerity.
This austerity reflects a lack, or disorganization, of resources such that training, sustenance and technology are rare.
Austerity does not prevent "anything from existing at any time", but makes cool and powerful things rare.
This rarity of powerful items is reflected in the tables for generating TOYs and is meant to be storyful.
In an austere world a cloning machine would be the basis for a campaign, in an opulent world a cloning machine could be used in one session. 

EXP is not designed for an abundant or opulent mythos. 
However there is certainly enough data to create such worlds. 
All manner of generic device can be found in the hardware catalogue.

Austerity is not just about technology, it is also about information.
In an austere world a mercenary or mechanic trains themselves. 
In an abundant world a veterinarian has been trained at an institute or had their knowledge chemically inserted. 

Austerity allows the referee to place guardrails on technology and education to make a more storyful and growth centered game.
EXP is written such that personas will grow from an austerity using technology and experience.

For an explanation of resource levels jump xref:roll_playing_system:incidentals.adoc#_mythos[here].

=== Peri-apocalyptic
Tying into the austerity theme is the concept of some calamity that created this austerity. 
The apocalyptic event, of unknown description, allows for guardrails on technology and knowledge.
Peri-apocalyptic framing also allows for austerity elements like: no telephone network, no computerized library, no historical memory.
These elements allow for technological and information discovery that is both storyful and entertaining. 
Societies that have abundant or opulent resource levels do not have such limitations. 


.*Jump to the Lies*
. <<_the_spaces,The Spaces>>
. <<_the_races,The Races>>
. <<_the_outer_spaces,The Outer Spaces>>
. <<_artifacts,Artifacts>>
. <<_tech_levels,Tech Levels>>
. <<_kirlian_energy,Kirlian Energy>>
. <<_energy_and_power,Energy and Power>>

== The Spaces
The spaces are a faux concept with a pseudo nomenclature that defines where stuff is. 
Physical Space is the space in which we mundanely live. 
This Physical Space is the space in which we pretend to have the most knowledge. 
The other faux spaces exist to defy reality in the Physical Space and tell fun sciency fiction stories.

:art: all_your_space_RBU.png
:width: 750px
:snark: Space for everyone
:artist: Hugh
:date: 2020
:license: CC BY-SA 4.0
:description: Diagram showing fake spaces that exist in EXP.

include::ROOT:partial$articulate.adoc[]

== The Outer Spaces
EXP has its own language for differentiating vehicle types.
The primary separation is planetary versus extraplanetary.
Planetary vehicles are mundane terra ones like cars, trucks and planes.
Inatmo vehicle is another term for a planetary vehicle because they are constrained to being "in the atmosphere."
Extraplanetary vehicles are the staple of sciency fiction and are capable of traversing the stars.
Exatmo vehicle is another term for an extraplanetary vehicle are because they can function "exterior to the atmosphere."
Exatmo vehicles have a host of different identifiers based on what they can do in outer space.

:art: planets_swirling.png
:width: 350px
:snark: The physical space contains outer space.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Planets surrounded by swirly swishes.

include::ROOT:partial$articulate.adoc[]

include::appendices:partial$space_vehicle_nomenclature.adoc[]

== The Races
EXP moved away from the term races in the 1990s. 
The generic mythos supports a faux taxonomy that sounds sciency but is appearance-based.
In sciency-language, appearance equals phenotype.
So EXP's faux taxonomy is organized by phenotype and nothing else. 
Life in EXP encompasses any consciousness. 
That consciousness can exist in an anthro, alien, robot or AI. 
Players create anthros, evolve aliens, and fabricate robots.

:art: life_in_colour.png
:width: 750px
:snark: Life's what you make it. 
:artist: HM
:date: 2019
:license: CC BY-SA 4.0
:description: Chart showing the fake persona families that exist in EXP.

include::ROOT:partial$articulate.adoc[]

== Artifacts
An artifact is a collective term for tools, devices, machines, weapons, or junque that the personas encounter.
An artifact is anything that the players have no identified yet. 
Equipment is an artifact that the players have identified for their personas.
The system that generates these artifacts is massive and is called the Technological Object Yield System.
Player often refer to technological artifacts as toys. 
Toys are the generic equivalent of magic items in fantasy RPGs.

:art: tech_level_transform.png
:width: 450px
:snark: Tech level is not just size and wate reductions.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Compact rifle unfolding to full sized weapon.
include::ROOT:partial$articulate.adoc[]

== Tech Levels
Tech level is a shortening of the term technological levels.
The premise of tech levels in EXP is that any civilization can accomplish any technological achievement.
However, the size, complexity, and required resources to accomplish that achievement are what differ. 
This premise is the basis of how anything can appear anywhere at any time. 
The artifact could be from an extinct civilization, an existing civilization, an alien civilization, or a clumsy time traveler. 

NOTE: EXP is called *The game of technological chaos* for a reason.

In short, the higher the tech level, the smaller, lighter, more valuable and hard to understand an artifact is.
Tech level 10 is our present mundane terra tech level. 

include::hardware:partial$tech_level_time_piece.adoc[]

include::appendices:partial$tool_usage_examples_tech_level.adoc[]

== Kirlian Energy
The concept of Kirlian energy and auras has a long history of pseudo-scientific poppycock.
In EXP, Kirlian energy, aura and forces are a sciency fiction extension of https://en.wikipedia.org/wiki/Kirlian_photography[Kirlian Auras,window=_blank].
In EXP, the Kirlian energies occur as the Think Space interfaces with the Physical Space.
Kirlian auras and energies behave like static electricity produced as the Think Space rubs within the Physical Space.
While static electricity is an evident phenomenon, very few personas can see Kirlian auras.
Even fewer personas can manipulate Kirlian energies.

The Knite is the only vocation that can see and use Kirlian auras.
The persona's ability to manipulate this interspace friction makes them a Knite.
The Kirlian energy empowers Knites to carry out psionic shenanigans in the Physical Space.  

:art: kirlian_koins.png
:width: 250px
:snark: Kirlian auras surrounding money.
:artist: Unknown
:date: 2020
:license: Public Domain
:description: Black and white image of Kirlian auras on some coins. 

include::ROOT:partial$articulate.adoc[]

Kirlian energy is minimally present through the Physical Space.
Any entity that is a powerful conductor of the Think Space can amplify Kirlian energy's presence.
Conducting the Think Space requires order, which is the purvey of a Knite.
Any entity that is a powerful disruptor of the Physical Space can amplify Kirlian energy's presence.
Disrupting the Physical Space requires chaos, which is the purvey of an Anti-Knite.

=== Knites and Kirlian Energy
There are no alignments in EXP. 
In other fantasy RPGs, moral alignments such as evil, neutral and good guide the persona's choices.
The vocation of Knite is an exception to this rule of amorality. 
As powerful conduits of Kirlian energy,  the Knite vocation is bound to either order or chaos.

:art: chaos_meets_order.png
:width: 450px
:snark: When chaos meets order chaos ensues.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Two humanoids dueling with lazer swords beside gaping hole inside spaceship.

include::ROOT:partial$articulate.adoc[]

Whether a Knite follows order or chaos, she is a powerful amplifier of the Kirlian energy. 
The depth of the mythos surrounding the Knite vocation depends on the campaign.
Knites may operate individually or in large organizations promoting either order or chaos.
In EXP, order and chaos are opposing sects. 
Choose the nomenclature that fits your milieu: churches, orders, light, dark, order or chaos.

NOTE: Kirlian Auras FTW. Not just because Midi-Chlorians suck.

== Energy and Power
The zany collection of technological artifacts all require power to operate.
Many players don't worry about how artifacts are powered and simply let everything work all the time.
Not worrying about how artifacts get power is a perfectly valid campaign choice and fun.
A scarcity based campaign may need a framework for energy sources. 
Not surprisingly, EXP has a faux framework for how things get energy and keep running.
The power and energy framework in EXP lends itself to fun sciency fiction explanations.

There are four sources of energy in EXP, cells, fuel cells, fuel and power sources.
Cell, aka batteries, are for personal artifacts that need portable power.
Fuel cells are specifically for robots and not found anywhere else.
Fuel is for planetary and extraplanetary vehicles.
Power sources represent architectural infrastructure that resembles our mundane terra electrical grids. 

* Artifacts get energy from cells (batteries)
* Robots get energy from a fuel cell.
* Vehicles get energy from fuel. 
* Cities get energy from power sources

The energy sources have three different formats: basic, rechargeable, and continuous.
Basic energy sources are expendable and disposable.
Batteries on mundane terra are an example of basic cells.
Rechargeable energy sources charge themselves.
When a solar cell runs out of energy, bright light can recharge it.
Continuous energy sources deliver energy without interruption.
A broadcast cell delivers energy from a continuous energy source.

* Basic energy sources are disposable
* Rechargeable energy sources can replenish themselves
* Continuous energy sources offer uninterrupted energy

There are basic, rechargeable and continuous batteries. 
There are basic, rechargeable and continuous fuel types. 
The various energy sources are replete with sciency fiction nomenclature: nuclear, magnetic, solar, and psionic, to name a few.

=== Basic cells
Basic cells contain chemicals that react to create electricity.
One would hope that the nature of these chemicals is so advanced an explanation is optional.
For story telling purposes the chemical could be anything: natural gas, manure, hair, etc.
Recharging the power cell simply requires replacing the depleted materials.

==== Gas and Liquid Cells
Gas and liquid cells will cease operation if exposed to a vacuum.
This does not apply if the robot is exatmo hardened.
They will function as normal once atmosphere is restored.

==== Solid Cells
Solid cells function fine in vacuums, but do not function at high temperature.
Prolonged exposure to temperatures that may not damage the robot may damage its power cell.
Solid cells will function as normal once they cooled.
Extreme heat could destroy a robots solid cell.

==== Plasmoid 
Superheated gases contained in magnetic bottles fire up the robot for power.
This should make it virtually impossible for Mechanics to use the plasmoid cell maliciously.
The plasmoid cells have many safeguards that prevent their weaponization. 
Recharging plasmoid batteries requires the re-insertion of plasmoid materials.

==== Dynamo
Internal gyros spin up the electricity for this robot.
The countless dynamos are microscopic and silent. 
Cells offer no features beyond source.
Dynamos will not function when exposed to more than 2g.
The dynamos return to normal once gravity drops below 2g.
Dynamo cells can be recharged by plugging into the nearest electrical outlet.

=== Recharging
Rechargeable power systems do not require materials to regain their power.
Rechargeable power systems or batteries may be swappable, but usually are baked into the device.

==== Gravitational 
This power cell filters gravitational waves into electrical energy.
An explanation of this technological miracle will not be attempted.
The gravitational force cannot exceed 3g or be less than one half g.
The robot will store energy for those instances where gravitational cell cannot function.
The robot has 1 hour of stored energy per point of CON.
Once out of power the robot will remain dormant until gravity normalizes.

==== Solar 
The solar power source will keep the robot operational in any amount of light.
Artificial light and light from the nearest star work equally well.
If there is light this robot need not recharge.
If the robot should be plunged into darkness they will operate on stored power.
The robot can store 1 hour energy per point of CON.
A solar powered robot with a 16 CON could run for 16 hours in the dark.

==== Magnetic 
Cellular magnetic forces are amplified to produce electrical power.
Magnetic cells will be disrupted by any magnetic based attacks or disruptions.
Severe disruptions may cause the cell to be demagnetized and require recharging.
This is left to the discretion of the referee.
Regeneration requires and electrical charge to re-magnetizes the power cells.

=== Continuous
Continuous power sources have no discernable battery or charging port.
They offer continuous uninterrupted power that is usually restricted by range.

==== Broadcast
Broadcast cells are power receivers that convert transmissions from a source into energy.
The receivers will cease to function if they are electronically jammed or out of range.
When within range the robot has an endless supply of power.
Robots using broadcast power can store one month of power per point of CON.
A robot with a broadcast power source that runs out of stored charge must be placed back in range to recharge.

==== Nuclear 
The nuclear power sources uses slow burn fusion, fission, etc., to produce electricity.
It is impossible for a this persona to explode like an atomic weapon.
The nuclear cell is so efficient that there is no radiation hazard.
The nuclear power source functions in all many or atmospheres and gravities.
Fissionable materials are required to replenish the nuclear batteries.

==== Psionic 
Psionic cells convert the surrounding psychic energy into electrical energy.
The psionic cell has the most complicated recharge process.
The batteries last for the usual one month per point of CON.
When it is time to recharge the cell drains local psionic energy.
The nearest persona will to the robot will be drained one point of MND to fully recharge the robot.
The persona gets a save vs psionic attack. 
The robot persona uses her CON as MND to calculate the saving throw. 
If the persona saves the robot moves onto the next persona.
The process is automated and the robot is unaware of who is attacked when.
