= Media

Eventually this will be a curated repository of Sciency Fiction media that informs EXP and is fun. 
Presently this is limited to visual media as the author's learning disability (evident with this doc's prolific typos) precludes written materials.

. *Arbitrary Rules for Inclusion*
* Live action over CGI
* Movie over series
* Sciency fiction over fantasy
* Low budget over blockbuster
* My preference over your preference ;)

NOTE: Due to the data capture kleptocrat pigs that Youtube and Alphabet represent I am forced to use their platform.

Trailers are from Sciency Fiction movies that have a modicum of originality and are borne from passion.
Shorts are brief videos with a Sciency Fiction themes. Music is Sciency Fiction music videos or ambience. 
Grumpy Commentary is from Isaac Arthur who spends a lot of time explaining why everything we love about Sciency Fiction is impossible.
Softer Commentary is from Daniel Orrett who's dulcimer tones explain why everything we love about Sciency Fiction is possible.
Dimensions is the Metal Ball Studios YT channel which has tonnes of videos that help one understand 

. *List of Media Lists*
* https://www.youtube.com/playlist?list=PLjVeahViVrnhB8fCiZdYCokY6_io8GFbs[Shorts]
* https://www.youtube.com/playlist?list=PLjVeahViVrnjy_MhRmLZgUrND21CJDK6v[Trailers]
* https://www.youtube.com/playlist?list=PLjVeahViVrnhpHxibQTCl3cnshH0ZYLKB[Music]
* https://www.youtube.com/@isaacarthurSFIA[Grumpy Commentary]
* https://www.youtube.com/@Spacedock[Softer Commentary]
* https://www.youtube.com/@MetaBallStudios[Dimensions]

NOTE: my experience with making these playlists work makes me *despise* Alphabet and Youtube even more. 


