= Printables

[quote]
____
*It is harder to burn history than delete it.*
____

== Introduction
EXP is a table top sciency fiction role playing game.
Printables is the section where you can get the files for printing the necessary stuff to play.
If you are feeling old school you can snag a copy of EXP v4. 
If you only have 6 sided dice to use you can snag a 4D2 Mechanic One Pager. 

All version 7 PDFs will have their accompanying docs as code ADOC companion downloadable as well.
An ADOC file is a markdown file that can be converted into a PDF using Asciidoc-pdf tools. 
Not only does this stay in EXP's docs as code goals, but allows players to style their PDFs as they see fit. 
All the tools are free and open source.


== Persona Record Sheets
A collection of PDFs that are used to keep track of personas with pencil and paper.
Download, print and play.

// Table Download for Print
.*Persona Records*
[width="85%",cols="<5,^2,^2",frame="all", stripes="even"]
|===
3+<|PDF persona record sheets. Yes it is lonely right now. 
s|Printable
s|Type
s|Size

|xref:ROOT:attachment$anthro_record_v7.pdf[Anthro Record v7]
|PDF
|74k

|xref:ROOT:attachment$alien_record_v7.pdf[Alien Record v7]
|PDF
|98k

3+^|Support PDFs


|xref:ROOT:attachment$campaign_sheet_v7.pdf[Campaign Record v7]
|PDF
|30k

|xref:ROOT:attachment$4d2_mechanic_v61.pdf[4D2 Mechanic v6.1]
|PDF
|177k


s|Printable
s|Type
s|Size
3+<|All licensed by Hugh MacLeod under CC BY-SA 4.0.
|===

== Build Your Own 
Below are the files necessary to generate (most) of the PDFs above.
If you can install asciidoc-pdf you can download and create persona record sheets for EXP.
The ADOC files correspond with the PDF of the same name.
The pdf_theme.yml will be needed for styling, and SVGs decompressed from the zip.

.*Support Files*
[width="85%",cols="<5,^2,^2",frame="all", stripes="even"]
|===
3+<|Mostly PDFs. Some relevant. Some historical.
s|Printable
s|Type
s|Size

|xref:ROOT:attachments$pdf_theme.yml[theme for ADOC PDF]
|YML
|600b

|xref:ROOT:attachment$pdf_svgs.zip[SVGs ZIP file]
|SVGs
|1.6k

|xref:ROOT:attachment$anthro_record_v7.adoc[Anthro Record v7 Code]
|ADOC
|6k

|xref:ROOT:attachment$alien_record_v7.adoc[Alien Record v7 Code]
|ADOC
|7k

|xref:ROOT:attachment$campaign_sheet_v7[Campaign Sheet v7 Code]
|ADOC
|3k

s|Printable
s|Type
s|Size
3+<|All licensed by Hugh MacLeod under CC BY-SA 4.0.
|===

== Historical
Things from the past that may be useful. 
For example, using persona record sheets from v5 (2010) that are missing in v7. 

.*Historical Downloads*
[width="85%",cols="<5,^2,^2",frame="all", stripes="even"]
|===
3+<|Mostly PDFs. Some relevant. Some historical.
s|Printable
s|Type
s|Size

|xref:ROOT:attachment$exp_game_v401.pdf[EXP Game v4.01 (1993)]
|PDF
|32M

|xref:ROOT:attachment$anthro_record_sheet_v5.pdf[Anthro Record v5]
|PDF
|287k

|xref:ROOT:attachment$robot_record_v5.pdf[Robot Record v5]
|PDF
|112k

|xref:ROOT:attachment$alien_record_sheet_v5.pdf[Alien Record v5]
|PDF
|112K

|xref:ROOT:attachment$toy_record_v5.pdf[TOY Record v5]
|PDF
|123k

s|Printable
s|Type
s|Size
3+<|All licensed by Hugh MacLeod under CC BY-SA 4.0.
|===


// fix theme.yml file is missing for PDF
// fix .svg are missing for PDFs
