= Printables

[quote]
____
*It is harder to burn history than delete it.*
____

// FIXME bureaucracy bot is gone

EXP is a tabletop Sciency Fiction role-playing game.
Printables is the section where you can get the files for printing the necessary stuff to play.
If you are feeling old school you can snag a copy of EXP v4. 
If you only have 6 sided dice to use you can snag a 4D2 Mechanic one-pager. 

All version 7 PDFs include an accompanying docs‑as‑code ADOC companion download as well.
An ADOC file is a markdown file that can be converted into a PDF using asciidoctor-pdf tools. 
This supports EXP’s docs‑as‑code goals and lets players style their PDFs as they see fit. 
All the tools are free and open source.


== Record Sheets
A collection of PDFs that are used to keep track of personas, and stuff, with pencil and paper.
Download, print and play.
We don't need to kill a tree.
Try the open source PDF tool https://xournalpp.github.io/[Xournal, window="_blank", rel="noopener noreferrer"].


// ***********
// LATEST PDFs
// ***********


.*Latest PDFs*
[width="100%",cols="<2,<3",frame="all", stripes="even"]
|===
2+<|Latest files to assist live tabletop play.


2+^|Player Persona Records

s|Download
s|Comment

|xref:ROOT:attachment$blank_anthro_2026_0423.pdf[Anthro Record, window="_blank", rel="noopener noreferrer"]
|PDF, letter sized, portrait

|xref:ROOT:attachment$blank_alien_2026_0423.pdf[Alien Record, window="_blank", rel="noopener noreferrer"]
|PDF, letter sized, portrait

|xref:ROOT:attachment$blank_robot_2026_0423.pdf[Robot Record, window="_blank", rel="noopener noreferrer"]
|PDF, letter sized, portrait

|xref:ROOT:attachment$blank_story_sheet_2026_0423.pdf[Story Sheet, window="_blank", rel="noopener noreferrer"]
|Sheets for stories, PDF, letter sized, portrait

2+^|Other Records

|xref:ROOT:attachment$spacer_portrait_2025_1008.pdf[Spacecraft Record, window="_blank", rel="noopener noreferrer"]
|Spacecraft details, PDF, letter sized, portrait (outdated)

|xref:ROOT:attachment$toy_sheet_2025_1008.pdf[Toy Info Sheet, window="_blank", rel="noopener noreferrer"]
|Sheets for toys, PDF, letter sized, portrait (outdated)

|xref:ROOT:attachment$role_playing_one_pager_v7.pdf[4D2 Role Playing Game, window="_blank", rel="noopener noreferrer"]
|PDF, 1 page (very outdated)

|xref:ROOT:attachment$exp_game_v401.pdf[EXP Game (v4 1993), window="_blank", rel="noopener noreferrer"]
|PDF, 777 pages (very, very outdated)

s|Download
s|Comment

2+<|All licensed by Hugh MacLeod under CC BY-SA 4.0.

2+<|All files are less than 1M in size. 

|===

=== Build Your Own 
EXP Game presently does not support Build Your Own personas.
We are switching from ADOC based persona records to https://typst.app/[Typst, window="_blank", rel="noopener noreferrer"] based persona records.
This is in progress as of 2026_0423.



