:kroki-server-url: https://kroki.io

= Printables

[quote]
____
*It is harder to burn history than delete it.*
____

Things that may be helpful when playing at a table. 
All content here is formatted for printing.
Formatted for printing is code for PDFs.

NOTE: record sheets are completely out of date and useless

// Table Download for Print
.*Downloads for Print*
[width="85%",cols="<5,^2,^2",frame="all", stripes="even"]
|===
3+<|Mostly PDFs. Some relevant. Some historical.
s|Printable
s|Type
s|Size

|xref:ROOT:attachment$Role_Playing.pdf[4D2 Mechanic One Pager  V6.1]
|PDF
|177k

|xref:ROOT:attachment$anthropomorph_record_sheet.pdf[Anthro Record Sheet V5.0]
|PDF
|287k

|xref:ROOT:attachment$robot_record_sheet.pdf[Robot Record Sheet V5.0]
|PDF
|112k

|xref:ROOT:attachment$alien_record_sheet.pdf[Alien Record Sheet V5.0]
|PDF
|112K

|xref:ROOT:attachment$toy_record_sheet.pdf[TOY Record Sheet V5.0]
|PDF
|123k

|xref:ROOT:attachment$expgame.pdf[EXP Hardcopy V4.01 (1993 Historical Doc.)]
|PDF
|32M

s|Printable
s|Type
s|Size
3+<|All licensed by Hugh MacLeod under CC BY-SA 4.0.
|===


== diagrams as code
This little chunk of the effort represents an attempt to get diagrams as code working.
This has been an utter failure with an entire 2 days ouroboric none learning.
PlantUML, Antoradocs, and Asciidoctor are just too many layers of abstraction. 

[kroki, plantuml, format="svg", opts="inline"]
....
Alice -> Bob: Hello Bob, how are you?
Bob --> Alice: I am fine, thanks!
....


