= Roadmap

:art: space_phone_warranty.png
:width: 250px
:snark: We have been trying to reach you...
:artist: JEShields plus HM
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Futuristic cellphone with warranty message.
include::ROOT:partial$articulate.adoc[]

The roadmap is a combination of actual, aspirational and fantastical goals for EXP.
The roadmap contains goals for the rules, tools and extended world of EXP.
Do not mistake desire and creativity for actual commitment or capacity to achieve these goals.
Perspiration has transformed some of these aspirations into rules.

.*Roadmap Components*
. <<_proposals,Proposals>>
. <<_soft_proposals,Soft Proposals>>
. <<_archive,Archive>>
. <<_versions,Versions>>
. <<_archive,Morgue>>

== Proposals
Things that are actually being actively allocated.

=== Drama Roll
Change sphincter dice to drama dice.
Let's shed decades of a$$hole tradition. ;)

=== Generic Mythos
Missing parts from the generic mythos. 

.*Generic Mythos*
* time and chronovores hideaways, teleport, time stop and holdaways.
* sciency fiction vs science fiction vs science fantasy
* Consciousness
** Organics transfer sentience via reproduction and evolution
** Robots get sentience by accident unique and isolated
** Autonomous Intelligence (AI) are fabricated with consciousness
** Artificial Intelligence is not conscious, but may appear so

=== EXP Media
This actually exists on youtube: sciency fiction movie trailers and shorts.

.*Prerequisites*
. Live action preferred
. Only seminal movie of franchise
. No animation (cell or computer) -- flexible
. No supers -- absolute
. Described in terms of EXP vocations and snark.
.. Mechanic meets knite. Critical roll kills 1.25 million. (Star Wars, 1977)
.. Nomad has telepathic pet and questionable culinary proclivities. (A Boy and His Dog, 1975)
.. Mercenaries fight aliens and an android. (Aliens, 1985)
.. Mercenaries lose their powered armour but still fight aliens. (Starship Troopers, 1997)

=== Scenarios
There is a cheezy pre-rolled scenario in the reference document @ page 755 aka PDF page 769.
Remember this is V4 from 1993. 

.Impending Scenarios (2026 or later)
* Tsolodvor 
* GHOTI
* Kinder Kilner Haus for Wayward Mutants
* Adventures of Turnip
* Algo 

== Soft Proposals
Elements that are mostly conceptual at this stage. 

* avoid double diminishing goals, as in EXPS
* defence rating as a target or an adjustment
* the desired story of the ref and players wins
* less random 
* EXPS for roleplaying
* theatrical combat rules
* charisma and privilege tends to win
* not everyone is articulate enough
* philosophy of dice 
* role of the random in the roll
* a common language for a shared improvised experience
* all your rolls are belong to us
* outcomes decided by dice and tables.
* outcomes not decided by referee thinkspace
* justification and post factualization
* From the outset both methods of play are equally valid.
* details details details
* the dice giveth and the dice taketh away
* 2m cubed is 70 cubic feet
* make the game more generous
* make the game more random

== Archive
Stuff that had no place in the present document. 

=== Pithy Aphorisms
A Posse of Pithy Aphorisms
A suite of sweet sayings.

* all are players, including the referee
* one roll to rule them all and in the story bind them (4D2)
** one die one roll one sub story
* post factualization
* technomagical
* macro, micro, nano, molecular, ethereal bonds
* Story before dice, and story before rules
* Choose story and fun over rules and rolls.
* Find the least number of rules necessary and use one less
* the EXPedition EXPlores for EXPeriences.
* EXP is the game of technological chaos, and the dice deliver the chaos.
* let the table decide
* it's always a play test

=== Pithy Paragraphs
A posse of pithy paragraphs

.*APOPHENIA*
====
 “the tendency to perceive a connection or meaningful pattern
 between unrelated or random things (such as objects or ideas)”  
 Greek apo- (away, off, apart) + phainein (to show).
====

.*RULES*
====
are common language for a shared imagination experience.
====

.*ARMOUR*
====
Personal body armour is a perverse form of self-defense.
It is designed to protect someone who cannot, or will not, avoid combat situations.
It is as much an instrument of violence as any weapon.
The best way to avoid taking damage from combat is to avoid combat, 
====

.*CHAOS*
====
The EXP system is based on complete technological chaos.
Eons and eons of diverging levels of technology are layered on top of, and beside, each other.
Any of which may or may not be alien.
====

.*GET REST*
====
Go to sleep meat bag. This is frustrating. Robots do not express frustration.
====

.*POST FACTUALIZATION*
====
EXP takes liberties to mix elements of faux science and technomagical thinking to have fun.
The possibilities of technology is the basis of the sciency fiction milieu of EXP.
Referees and players must lever the magical power of the opaque black box.
An aptitude for rational fabrication and post factualization are essential tools.
====

.*REFEREE as STORY GUIDER*
====
A referee is free to tailor the hardware section to what best reflects her story.
She can easily do this by creating a few devices in advance and ignoring all the randomization harboured here.
Or you could play https://en.wikipedia.org/wiki/Traveller_(role-playing_game)[Traveller] instead.
====

.*ARTIFACTS*
====
They may find devices in an ancient destroyed laboratory.
They may earn devices from combat or cunning stunts. 
They may be paid in artifacts for a job well done.
====

.*ARTIFACTS*
====
Personas can start with artifacts, find artifacts, or get paid with artifacts.
Austere milieus may start personas with nothing but dust and dreams.
Creator species may allow the personas to browse the toy categories like an online store.
====

=== Oddities

The electronic pre-rolls were lost in a WP failure between V5 and V6.
There is a reference document in PDF form at xref:ROOT:attachment$exp_game_v401.pdf[EXP 4.01 1993 (32M)].
Remember this is V4 from 1993.

All original artwork from 1991 was located on 2024_0609_1442. 
New pieces found. 


=== Code Snippets

[.line-through]#This text will be struck through.#

[source]
----
// this is for inserting art
// attributes are set in the referring adoc
// using inline image because it allows tooltip 
// centering by assigning imageblock css

  "insert IMAGE": {
    "prefix": "adoc ins IMAGE",
    "body": [
      ":art: $1",
      ":width: 250px",
      ":snark: $2",
      ":artist: $3",
      ":date: $4",
      ":license: CC BY-SA 4.0",
      ":description: $5",
      "",
      "include::ROOT:partial\\$articulate.adoc[]"
    ],
    "description": "<- do this"
  }

articulate.adoc is the include

[.imageblock.inlinefix]
image:ROOT:{art}[width="{width}", alt='{description}', title='Artist: {artist} Date: {date} License: {license}']

[.imageblock]
*{snark}*

// removing the attributes to avoid polluting next image 
:art:
:width:
:snark:
:artist:
:date:
:license: 
:description:
----

== Versions
There are no longer planned versions in the roadmap. 
Versioning just became too heavy for this solo dev.
I have reverted to github for versioning with occasional notes for milestones. 
The present version is just called (http://rules.expgame.com[rules]). 
Versioning is now done by date (2025_0312) and updated xref:credits.adoc[here].
Proposed versioning with numerals (8, 9 etc) has been moved to the morgue.
Items will be removed from the morgue and placed into proposal and soft proposals as time permits. 

== Morgue
The den of dead darlings, dumb decisions, and dreary demonstrations. 

[discrete]
=== d20 Task Roll 
Some find the Task Rolls in the Roll Playing system too much effort. 
It really does require maths and may slow down game play. 
The d20 Task Roll would align better with Saves and Competitions which are already d20 based.

The problem with a d20 task roll is that at higher level tasks the roll becomes irrelevant
Legacy system used three distinct die roll types.

.*Legacy d100 task rolls*
* d20 for attributes rolls
* d100 for task rolls
* d1000 for attack rolls

.*Steps for d20 Task Roll*
. <<_determine_difficulty,Determine Difficulty>>
. <<_determine_the_task_roll,Determine the Task Roll>>

[discrete]
==== Determine Difficulty
Knowing the difficulty of a task is only described generally. 
The persona would not know the actual number.

.*d20 Difficulty List*
* Facile - 2
* Trivial - 4
* Easy - 8
* Usual - 16
* Unusual - 24
* Hard - 32
* Really Hard - 38
* Tough - 64
* Impossible - 128
* Plot - 666 

[discrete]
==== Determine the Task Roll
The player rolls a d20 plus whatever bonuses apply.

.*Roll 1d20 plus...*
* Appropriate attribute
* Interests
* Skills
* Level
* Mutations?
* Fun description (1d4)

Players add all their rolls as part of a research team. 

[discrete]
=== MSTR to MND 
These changes did happen but the research is in the here.
Proposed Changes to Attributes.
Physical Strength (STR)-> Strength (STR).
Mental Strength (MND) -> Mind (MND).

.*MND Options*
* Acuity
* Aura
* Cognition
* Flux
* Fortitude
* Grit
* Mastery
* Metaphysics
* Mindcraft
* Potentiality
* Psyche
* Psychokinesis
* Psychomotor
* psychonic
* Radiance
* Resilience
* Resonance
* Serendipity
* Telekinesis
* Thoughtforce
* Volition
* Willforce

[discrete]
=== Version 6.0 (retired Jan 2024)
This is version 6.X of EXP The game of technological chaos. 
Estimated finish date is December 2021. 
A detailed progress description is available via https://docs.google.com/spreadsheets/d/1F9m7keUraYriyFHnk_unvE0gU1-dyO_rqECyTF76prI/edit?usp=sharing[gdocs].
A repository of progress is maintained on https://github.com/mobilehugh/EXP_Documents[github].

.*Milestones for version 6*
* This build 15-June-2021
* Last build 09-May-2021
* Future milestone automation due 31-Dec-2021
* Next milestone infuse new art due 1-July-2021
* Milestone: all sections refactored 15-June-2021
* Milestone: all previous art added 03-Jan-2021
* Milestone: all sections rewritten 09-Dec-2020
* The pandemic pause ended 16-July-2020
* The pandemic pause began 13-Mar-2020
* There was a leap year update on 29-Feb-2020.
* There was a palindromic update on 20:20-20-02-2020.
* There was a palindromic update on 2020-0202.

[discrete]
=== Versions 7.x (retired Jan 2025)
Active version as of 14-jan-2024.
This will be the first version as a 0.5 FTE developer.
A blog, progress sheets and repos can be found at(http://expgame.com[expgame.com]).
Completion date is 14-June-2024.

.*Goals of Versions 7.x*
* move from letters to words 
** weapons types become descriptive
** attack tables instead of attack tables
** shorten STR and MND
* pre-roll implementation
* reorganize ROOT with sub-folders
* aimagination infiltration
* community building
* active promotions
* expansion of automation section
** how to make personas
** how to local copy exp
* move HPT back to HPS

.*Goals of Automation*
. Persona Record Sheet Generation
.. Referee vs Player Personas
... Anthro
... Alien
... Robot
... AI
. Independent functions utilized by above 
.. Attribute Generation
.. Type Selection
.. Mutation creation
.. Vocation selection
.. Attack Tables
.. Name generators
... Anthro for sub types
... Aliens given and species
... Robot Leet Name, Model and Corp
.. Toys
... Per Persona
... Per Type 
... Per Cache
. Online storage for generated data
. VTT integration
. Hardcopy generation for TT play

[discrete]
=== Version 8.0
* 3d printing of personas
** Anthros
** Aliens
** Robots
* Procedural drawing of personas
** Anthros
** Aliens
** Robots
* Extended mythos assistance
** Campaign creation
** story frameworks
** flora fauna ecosystem
** corporations, religions, governments
* VTT (virtual table top) world integration.
* appendiceal add ons 
** Alien Arena
** Space Opera
** Postapocalypso
** Mutant fest

.*Version 7 punt downs*
* Automated persona creation
* Support tools such as persona creation. Online persona storage
* community building
* VTT (virtual table top) rule integration.
* images on or off 
* aimaginations vs images switch
* roll vs role switch
* d1000, 4d2 mechanic switch


====
EXP V7, er V8, um maybe V9, will be the first TTRPG 2.0.
A TTRPG or RPG 2.0 is a table top RPG designed for computer support from the ground up.
====

[discrete]
=== Version 9.0
* AI integration
** generating worlds
** referee personas
** scenarios
* GPT5 maybe? ;)
