= Storyful Improvisation

For the last 30 years of play almost all EXP play tables have been polluted with improv comedians.
EXP development has gone hand in hand with improv comedy development. 
The online repository of improv comedy info is found at https://learnimprov.com[learnimprov.com]
To improve improv at your table there must be a safe and supportive space, intentional listening, simple characters and storyful scenes. 
Most importantly the improv elements are made up of __tools__ not rules. 
The following pithy aphorisms are pure improv tools and will increase the chances of successful stories.

== Safe and Supportive Space
To be creative folks need to know that they safe. 
Creativity is hampered by prejudgment.
There are ample safety tools in the TTRPG space.
The improv space uses the following approach:

====
We intentionally avoid sexist, racist, homophobic comedy. 
Making fun of people for those things they cannot change about themselves. 
In improvisation these elements will come up. 
When they do we call people in, not call them out. 
====

When working in public spaces with strangers the above is explicitly expressed.
Amongst friends, who may also be strange, the above is implicitly observed. 

== Listening to Offers 
Everything that happens at the table is an offer. 
In improv stories are built stone by stone, and each stone is called an offer.
We do not bring a fully built stone house as an offer.

.*LACE Acronym*
* *L* isten, listen, listen.
** Listen with ears, eyes, brain and heart. 
* *A* cknowledge
** acknowledge what was listened to, aka accept.
* *C* ommit
** Your first idea about what you acknowledged is the best one
* *E* xtend
** Extend the acknowledged idea just a bit.  

We stopped using accept and "yes and" more than 10 years ago.
Not all offers need be accepted, but they need to be acknowledged. 


== Storyful Scenes
Starting and ending scenes are the hardest part of improv comedy and ttrpgs.

.*STEPS Acronym*
* *S* etting
** Where the scene taking place. 
* *T* ies
** What are the connections between the participants of the scene.
* *E* xploration
** What is being explored in this scene. 
* *P* ivot
** What turns the exploration into the unexpected. (remember LACE)
* *S* ort
** What ends the story. Not necessarily a resolution. 


== Character Triangle
Improv comedians need to create a character (persona) in less than a second. 
This tool can be used to assist players to make instant characters.
This tool can also be the base for rich and complex characters. 

.*Triangle* of Character
* *Move*
** How does the character comport their position in space. 
* *Sound*
** How does the character sound. Not an accent. 
* *Goal*
** What does the character want. Not explicitly expressed, and may be unclear. 

== Storyful Arch
Where ttrpgs and improv comedy diverge is in the collective memory of the ttrpg.
Even long form improvisation does not hold characters, and stories for more than 60 minutes.
Ttrpg story telling is in the branch of improv story telling that has memory and complexity.

The ttrpg story is affected by decisions and dice. 
The personas grow in experience both literally and figuratively.
Personas become more powerful and mythos grows around them. 

The players inflict their personas on the milieu.
The milieu will be altered by their actions creating a history around the personas. 

.*Campaign Stories*
* A Campaign has a story arch tied together by threads. 
** Threads are connected stories 
*** threads may increase in drama or fade away
*** threads are improvised and written 
** improvised threads are collaborative
*** combat stories (dice and player choices)
*** task roll stories (dice and player choices)
*** referee persona stories (improvisation)
*** persona stories (improvisation)
** written threads are created by referees and players alike
*** are crafted not improvised
*** can be the consequence of a combat story
*** can be the consequence of persona improvisations
*** can be created de novo to propel, or pivot the story arch

Keeping track of these stories involves record keeping and table memory.
The entire table should be responsible for keeping track of the campaign story.
These can become large indeed. 




