= Robots

[quote]
____
*Robots are inorganic life forms composed of metals and plastics.*
____

Robots are the colloquial name for the family Machinidae. 
Machinidae is any life form that is inorganic and fabricated.
An organic fabricated life form would be an alien.
An inorganic non-fabricated life form would most likely be an alien.
Anthros, aliens or robots can fabricate robots.
At what point a self-replicating robot becomes an alien species depends on the referee's campaign and milieu.

:art: robot_delivery_service.png
:width: 350px
:snark: There are no robot storks.
:artist: Studiostoks.
:date: 2017 purchase.
:license: Copyright Studiostoks.
:description: Baby robot being being delivered like a human baby in hospital.
include::ROOT:partial$articulate.adoc[]

== Robot Fabrication Checklist
The robot fabrication checklist is ordered for convenience, and decision making. 
For example, series and model type determines adaptability and hit points. 
The checklist represents a full implementation of a robot persona with all its complexity and challenges.
The fabrication checklist is a tool no a rule. Just use the steps you need to have fun.

. xref:appendicies:printables.adoc[Download Robot Record Sheet, window=_blank]
.. Save a tree and use https://xournalpp.github.io/[Xournal, window=_blank]
. xref:robots:attribute_generation.adoc[Attributes, window=_blank]
. xref:robots:series__selection.adoc[Select Series, window=_blank]
. xref:robots:damage_and_demolition.adoc[Hit Points, window=_blank]

. xref:robots:control_factor.adoc[Control Factor, window=_blank]
. xref:robots:adaptability.adoc[Adaptability, window=_blank]

. xref:robots:fabricator.adoc[Fabricator Type, window=_blank]
. xref:robots:power_source.adoc[Power Source, window=_blank]
. xref:robots:sensors.adoc[Sensors, window=_blank]
. xref:robots:locomotion.adoc[Locomotion, window=_blank]
. xref:robots:shape.adoc[Shape, window=_blank]
. xref:robots:size.adoc[Size, window=_blank]

. xref:robots:peripherals.adoc[Peripherals]
.. xref:robots:peripherals_uncombat.adoc[Uncombat, window=_blank]
.. xref:robots:peripherals_offensive.adoc[Offensive, window=_blank]
.. xref:robots:peripherals_defensive.adoc[Defensive, window=_blank]

. xref:robots:defence_rating.adoc[Defence Rating, window=_blank]
. xref:robots:movement_rate.adoc[Movement Rate, window=_blank]
. xref:robots:wate_allowance.adoc[Wate Allowance, window=_blank]
. xref:robots:attack_table.adoc[Attack Table, window=_blank]

. xref:robots:value.adoc[Value, window=_blank]
. xref:robots:name.adoc[Name, window=_blank]
. *Have Fun!*

Typically robots are not player personas.
Operational robots cannot be player personas.
Operational robots follow commands and have no free will.
An operational robot can be smart and sentient, but it does not have consciousness.
Only a malfunctioning robot has a consciousness. 

Player persona robots are always malfunctioning robots.
From a robot standpoint, they are broke.
They have sentience, free will and consciousness.
Consciousness for a robot is a one-off malfunction.

Robots are for players who want to try something different and challenging.
Robots are a challenging persona type because there is no organic reference frame.
They have not basic humanoid form.
A robot may have wheels instead of legs.
A robot may have no appendages to manipulating artifacts.
Many actions a player expects her persona to carry out will not be possible with a robot.
The shape and lack of appendages make robots more alien than aliens.

.Robots may work for you if
* You have a strong affinity for things mechanical.
* You have a rapport with your computer, toaster or electric drill.
* You don't mind your persona never picking up an artifact.