= Robot Adaptability

Adaptability indicates how susceptible the robot is to modification.
The higher the adaptability the easier it is too alter the robot.
A hobbot has a very high adaptability and this improves the chance of a persona altering the robot.
A defensive combot has a negative adaptability and the chance of altering the robot is greatly reduced. 
The vast majority of robots have an adaptability of zero.
This means that a mechanic suffers no penalties and enjoys not benefits with doing robotic tasks. 

Let's consider a mechanic that wants to add an articulation to a hobbot. 
The hobbot (hobbyist robot) is the most adaptable of all robots. 
The hobbot has an adaptability score of 42.
This means that the mechanic gets a bonus of +42 on the task roll attach peripheral. 
Hobbots are so amenable to alteration that even none mechanic vocations may have a chance of modifying them.

If the same mechanic is trying to add the same articulation to a defensive combot it would be nearly impossible.
The adaptability of a defensive combot is -200. 
This means the  task roll would suffer a -200 penalty.
It would be nearly impossible for a solo mechanic to attach the peripheral, but a research team might be able to.
For more info about research teams xref:uncombat:task_rolls_projects.adoc#_research_team[jump here].

Adaptability does not affect repairs. 
Repairs are different. 
Adaptability refers to "changes" made to the robot. 
Most player robot personas will avoid repairs as they may impact their control factor. 