= Robot Attributes

Robot persona attribute values are equivalent to organic persona attribute values.
A robot's Strength of ten is the same as an anthro's Strength of ten.
The player's pathway to generate robot attributes is quite different. 
Robots have a combination of prime attributes, regular attributes and irregular robot attributes.

include::robots:partial$robot_attribute_generation.adoc[]

== Regular Attributes
The player generates these regular attributes the same as she would for any other persona. 
She rolls the assigned dice and records the score on her persona record sheet.
The regular attributes are Awareness (AWE), Charisma (CHA) and social standing (SOC).

== Prime Attributes
Prime attributes are the robot persona's most important attributes.
The prime attributes determine the persona's robot type and indicate each attribute score's range.
The prime attributes are Constitution, Dexterity, Intelligence and Strength.

Each prime attribute has a value between 1 and 4 (1d4).
The higher the prime score, the higher the final attribute score will be.
The player records the prime attribute score on the robot persona record. 
The prime scores are immutable, and while the robot's attribute score deteriorates, her prime score does not.

include::robots:partial$prime_attributes_list.adoc[]

A player that rolls a three for STR prime has a STR prime of 3.
The player will also generate a conventional attribute score based on the prime attribute value.
Each prime attribute has a prime score (1-4) and an attribute score (1-29).

include::robots:partial$prime_attributes_translation.adoc[]

=== Prime Attributes Skip
If the byzantine anachronistic robotic series selection process is too much there is a table for that.
However the player must already have a robotic series chosen to skip. 
To speed up the robot fabrication process use the following tables.

.*Skip the Tables*
. xref:robots:series__selection_skip.adoc[Series Selection Skip]
. xref:robots:attribute_generation_skip.adoc[Attribute Generation Skip]

== Irregular Attributes
These attributes are specific only to robot personas. 

The first irregular attribute is the control factor (CF).
Robot Control Factor determines whether a robot maintains its free will.
Robot Type may keep a robot from doing what her persona wants.
For more info about this attribute test jump to xref:robots:control_factor.adoc[Control Factor,window=_blank].

The second irregular attribute is adaptability (ADP).
Robotic Adaptability determines how easily the robot can be altered. 
Some robots are very amenable to being altered, and have a high adaptability.
For example a Hobbot has a very high adaptability, while a heavy offensive combot has a very low adaptability. 

// todo adaptability as an attribute, upgrades and other stuff

The third irregular attribute is Mind (MND).
Robot personas have a Mind score of zero.
A zero Mind does not indicate that robots are psionically vulnerable and easily manipulated.
Robots do not have Mind because their consciousness does not exist within the Think Space.
Robots are unaffected by mental attacks that function through the Think Space. 
Robots cannot be mind-controlled or subject to telempathy or have their mind read.
If a robot must test her MND, she will use her Intelligence score instead. 

== Example 
The player would first generate her persona's regular attributes. 
She rolls 3d6 for her Awareness and Charisma and a 1d1000 for her social standing.
Her persona's regular attributes scores are 11 AWE, 8 CHA and 653 SOC.
She records these scores on her persona record.

The player then generates her prime attributes (CON, DEX, INT and STR) using a 1d4.
Her persona's prime attributes are 1 CON, 2 DEX, 3 INT and 4 MND. 
She then generates the regular scores for each of the prime attributes.
Based on her prime attributes, she rolls 1d8 for her CON, 1d6+7 for her DEX, 1d6+13 for her INT and 1d10+19 for her STR.
Her prime attributes have two values each.
Her CON has a prime of 1 and a score of 6.
Her DEX has a prime of 2 and a score of 11.
Her INT has a prime of 3 and a score of 18.
Her STR has a prime of 4 and a score of 27.

The attribute primes will determine the persona robot type.
The attribute score will determine how the robot performs in the game.


