= Robot Peripheral Systems

Peripherals give the robot the tools to perform its tasks.
Some peripherals are entirely incongruous to the robot type, which is fine.
Why wouldn't a combat robot have a tea service built-in?
Peripherals are not malfunctioning parts but baked in robot-controlled devices.

Every robot gets one roll on the Primary Peripheral Table. 
A percentage value indicates the chance of an extra roll.
Some robots do not have peripherals, which is made clear on their fabrication info.

The peripherals rolled here can be used creatively but cannot be used in combat.
Aroma production can not become a nausea attack, but it could help sell a house.
An articulation could not strangle an opponent, but it could open a door.

Sometimes, the player and referee come to an impasse regarding the peripheral's creative use.
These creative impasses can be bridged using the decision aid xref:roll_playing_system:CH16_Special_Rolls_Asshole.adoc[Sphincter Rolls,window=_blank].

== Primary Peripheral
Primary peripherals are not fancy. 
A primary peripheral will only mildly alter the robot's function or value.

include::ROOT:partial$CH05_Table_Primary_Robotic_Peripherals.adoc[]

== Secondary Peripheral
Secondary peripherals can be game-changers.
Mild-mannered robots can pursue a vocation.
Most secondary peripherals represent a combination of hardware and software.
These peripherals are not overly detailed as they are non-combat peripherals.
A non-combat peripheral does not mean that it is not powerful.
For example, a robotic mutation effect could allow a robot to manipulate time.

include::ROOT:partial$CH05_Table_Robotic_Secondary_Peripherals.adoc[]
