= Robot Control Factor

Control Factor (CF) is a measure of the robot's free will.
The higher a robot persona's control factor, the more likely she will avoid returning to her robot state.
Robot persona consciousness is a malfunction that separates them from their unconscious properly functioning colleagues. 

.*Control Factor Roll Checklist*
. <<_calculate_control_factor,Robot Control Factor>>
. <<_cf_roll_difficulty,Determine Difficulty>>
. <<_make_the_roll,Make the Roll>>

The higher the control factor, the better the player can control her persona.
In rare circumstances, a robot may feel an urge to revert to her former robot duties and losing conscious control of herself.
A janitorial robot may decide to clean a dirty bank vault instead of stealing the bounty. 
A combot may attack the aliens across the table instead of translating for the truce negotiations.

The robot's control factor (CF) helps prevent these embarrassing hiccoughs.
A robot's control factor depends on her Intelligence and improves as EXPS levels increase.
Control factor (CF) is unique to the family Machinidae.


// tag::control_factor[]
== Calculate Control Factor
.CF= (INT score) + (INT Prime* EXPS Level)
****
A 3rd level robot with a 15 INT score, and a 3 INT Prime has a CF = 24
****
// end::control_factor[]

=== Robot Free Will
Robots are machines that do not have free will. 
A robot design includes fulfilling its owners' direction.
A robot persona would likely not suffer orders from another persona and, therefore, would be malfunctioning.
An industrial janitorial robot is supposed to clean the factory and nothing else. 
Player persona robots are _broken_ robots.
The player's free will is considered a malfunction by the robot's fabricators.
Player persona robots are considered insane and rogue.

The robot personas controlled by players are insane robots who don't care much for being slaves.
From a robot perspective, insane does not mean mentally ill.
An insane robot is one with free will. 
Robot persona consciousness allows the player to run the robot persona like any irrational player persona.

NOTE: Robot *insanity* means free willness, not mental illness.

=== Control Factor Rolls
A control factor roll is a check to see if the player persona robot reverts to her pre-consciousness factory settings.
This effect is temporary, and the player still controls the robot, but she must fulfill robot type tasks first.
The referee and players can point out situations that require a control factor roll.
The rolls should not impair the fun of the player using her persona.
Control factor rolls heighten tensions and create new challenges for the expedition.
The control factor roll has another moniker: the "get back to work" roll.

For example, a domestic janitorial robot could find itself in a messy bathroom.
The referee could challenge the player to a Control Factor Roll to have her persona *not* clean the bathroom.
If the player fails the Control Factor Roll, the persona will need to clean the bathroom before doing anything else.
A policing robot may suddenly insist on citing a fellow expedition member for jaywalking during a firefight. 

The story of the milieu and situation should significantly influence how often the player makes control factor checks. 
For example, a combot is more likely to revert when fighting its programmed enemy.

== CF Roll Difficulty
The referee and player determine the difficulty of the control factor check. 
The more difficult the control factor check, the more likely the player will lose control of the robot.
Determining the difficulty of a control factor roll is more arty than sciency.
The general consideration is that the more the situation is like the robot's work, the more difficult the control factor roll is.

A janitorial robot ignoring a slightly messy bathroom should not be a problematic control factor roll.
However, having the same janitorial robot intentionally mess up a bathroom would significantly increase the difficulty. 
Messing up a bathroom in the mansion she used to work as her previous owner asks her to clean it up would be nearly impossible for the janitorial robot.

include::uncombat:partial$task_difficulty.adoc[]

The referee can choose to assign a random difficulty level using the suggested die roll or choose the static number.
The static number is just faster to use. 
The static hard degree of difficulty is simply 24.
The random hard degree of difficulty requires a 1d30 roll to generate the value. 


== Make the Roll
The player always rolls a 1d20 and adds her control factor to the roll.
It is nearly impossible to fail trivial and easy control factor difficulties.
The player must roll higher than or equal to the control factor roll's difficulty.
The control factor roll is a target roll.
The robot persona either wins or loses. 
There are no hazy ties or partial wins with a target roll.

=== Control Factor Roll
.1d20 + Control Factor >= Degree of Difficulty
****
With a 12 CF  the 1d20 roll must be 12 or higher to beat difficulty 24. 
****

=== Loss of Control
The control factor roll generates a win or loss result.
If the player wins, her persona goes about her business.
If the player loses, her persona temporarily loses control of her robot persona.

The player still role plays her persona, but she cannot inject her consciousness into the robot's actions.
For example, a domestic janitorial robot may clean up a washroom while the rest of the expedition raids the techno vault.
Once the robot cleans the bathroom, the player regains control.
More complex actions indicate a more prolonged loss of control.

If the loss of control involves combat, the player will operate her persona in battle.
If the player can complete her own goals while under a loss of control, that  is acceptable (if not brilliant)

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

A control factor roll is supposed to be an added challenge for robot personas. 
A control factor loss should not kill a persona or wipe out an expedition. 
The loss of control is temporary and more often amusing than life threatening. 