= Robot Fabricator

A life form other than the robot fabricates the robot.
The robot then malfunctions and develops consciousness.
This malfunction allows the player to operate her robot persona with free will.

There is a long legacy in sciency fiction of robot builders hard-wiring protections for themselves into robot programming.
We can thank https://en.wikipedia.org/wiki/Isaac_Asimov[Asimov,window=_blank] and our mundane terran fears of robots for the persistence of this belief.
There are no https://en.wikipedia.org/wiki/Three_Laws_of_Robotics[Three Laws of Robotics,window=_blank] in EXP.
Robots are free to smash up what and who they like.
The main issue that keeps robots from becoming mass murderers is that there is no reason to become one. 
Preceding consciousness through malfunction, the concept of doing anything other than their mission statement does not exist.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Fabricator Type
Where fabricator type does play a role is in delivering orders to the robot.
If a fabricator type tells a robot what to do, it is more likely to comply.
In short, the robot's fabricator type is more successful at bossing the robot around.
If a fabricator type makes a reasonable, on mission command to a robot, it would almost certainly result in a control factor roll.

include::robots:partial$fabricator_type.adoc[]

Most of the fabricator types are anthros.
EXP is an anthrocentric game.
If the player rolls fabricator type equine, her robot persona would be vulnerable to equine commands.
If the robot has an alien fabricator type, the referee may have to evolve an alien species just for that role.
If the robot has a robot fabricator type, the referee may have to fabricate a robot just for that role.

NOTE: When a robot has a robot fabricator type, the fabricator type of the fabricator has no impact on the fabricated robot. :)