= Robot Name
The player must name her persona.
Every persona must have a moniker, call sign, label, title, handle or cognomen.
A player should avoid naming her persona with her mundane world real name.
Creating a persona name makes role-playing more fun.

Robot names can get complicated.
Every robot will have a given name.
This given name arises from the player or the robot's malfunctioning computer brain.
The player can get ideas for her persona name from her robot type, her favourite peripheral, or shape.
The given name of the robot works in common parlance.
Names that sound like fax machines, look like bar codes or have 600 digits are only used between robots.

Robots can also have a model name and a fabricator name.
Model and fabricator names are optional.
The referee may have pre-made model names and fabricators that reflect her milieu. 
A complete robot name could have given name, middle name (model name) and surname (fabricator name).

.*Example persona names*
* A janitor robot - Kl33nr by Home Systems Inc
* A social robot - QT by Androgena Compositors.
* A heavy offensive combot - Spot.


== History
Players should create a pre-campaign history for their persona.
A persona's initial history should not be one of great fame or import.
Role-playing in the campaign world is what should build a persona's fame and reputation.
The persona's history should fit in with the referee's milieu and campaign. 

Persona backstories should be short.
If a player wants to make an essay of her persona's background, she should not expect other players to care.

== Description
Robots generate a general description during fabrication.
The robot persona can appear as an elongated cone mounted on a mono-tread.

The player can embellish her persona with further details: adornments, detailing, and fancy colours.
Overly detailed persona descriptions are fun for players to make.
Overly detailed persona descriptions are less fun for other players.
Concise descriptions make for compelling personas.

== Personality
Even robots can enjoy a personality gifted by their malfunction.
Robots need not have overpowering zany personalities.
The insanity of the robot is in their consciousness, not in their erratic behaviour.

NOTE: *The goal of persona personality is to have a perspective and have fun expressing it.*

The robot type can inform the persona's personality.
Combot's may become pacifists, and janitorial robots may have a thing about organization.

== Examples

Kl33nr:: 
Kl33nr pronounces her name cleaner, but her friends call her 33.
She is a retired janitorial robot designed by Home Systems Inc.
Kl33nr looks like a beige coloured cigar mounted on six wheels.
She retired from cleaning sand hog cages after getting hit by a sand sled.

QT::
QT pronounces his name Quinty. 
He looks like a short mechanical feline with large helpless eyes.
He does not like being called cutey.
Androgena Compositors would like QT back because he broke his lease to a local theme park when he malfunctioned into consciousness.

