= Name
The player must name her persona.
Every persona must have a moniker, call sign, label, title, handle or cognomen.
A player should avoid naming her persona with her mundane world real name.
Creating a persona name makesroleplaying more fun.

== Moniker
The player should give her robot persona a name.
This moniker arises from the robot's malfunctioning robot brain.
The player can get ideas for her persona name from her robot type, her favourite peripheral, or shape.

.*Example robot monikers*
* Kl33nr, a Janitorial robot by Home Systems Inc.
* QT, a social robot by Androgena Compositors.
* Spot, a misnamed heavy offensive combot.

While Leet is not required it is a fun way to name robots.
For a description of leet speak jump to https://en.wikipedia.org/wiki/Leet[Leet Speak Wikipedia,window=_blank]

If some inspiration is needed jump to xref:referee_personas:rp_story_cues.adoc[Referee Persona Story Cues,window=_blank]

The given name of the robot works in common parlance.
Names that sound like fax machines, look like bar codes or have 600 digits are only used between robots.

== Taxonomy 
Robots fall under the faux taxonomy of EXP. 
Their family type is robot, but they also have an equivalent of a genus and species.
The series of the robot (combot, datalyzer, android) functions the same as the genus in robot taxonomy.
The model of the robot (expendable, interplanetary) serves as its species. 
So an expendable combat robot could be labelled Combotis Expendabilis. 
Since each robot consciousness is a unique malfunction the taxonomy does not represent a species per se.

== Common
For a robot the common name could be a brand name, or a corporation name.
Often the common name for a robot refers to what the robot did before it developed sentience.


== Examples

Kl33nr:: 
Kl33nr pronounces their name cleaner, but their friends call them 33.
They were fabricated by Home Systems Inc.
Kl33nr looks like a beige coloured cigar mounted on six wheels.
They retired from cleaning sand hog cages after getting hit by a sand sled.
Moniker: 33, Taxonomy: Janitorial Industrialis, Common: Agri Clean

QT::
QT pronounces their name Quinty. 
He looks like a short mechanical feline with large helpless eyes.
He does not like being called cutey.
Androgena Compositors would like QT back because he broke his lease to a local theme park when he malfunctioned into consciousness.
Moniker: Quinty, Taxonomy: Socials Felis, Common: QT Socializer 

