= Robot Power Source

All robots operate on electrical power.
The electrical power runs all their systems and gives them life.
Running out of energy is not a problem for robot personas.
However, in a resource austere campaign setting, finding power may be the key to robot survival. 
If a robot runs out of power, she shuts down until the energy flows again. 
Getting powered down is an extremely vulnerable, but not lethal, state.

The robot power sources is a cross between a cell and an engine.
Each cell works on an ingenious technomagical system that is conveniently beyond explanation.
Robot power sources can go by many names: batteries, cells, supercells, etc.

If the referee and players feel that a robot running out of power is a fun option, consider the following.

.*Robot Power Guidelines*
* one month of use per point of Constitution score
* player personas start at a full charge
* one month low battery warning
* battery use does not affect battery duration
* all batteries can be restored or regenerated

include::hardware:partial$power_source_types.adoc[]

For a detailed explanations of the power sources jump to xref:appendices:generic_mythos.adoc#_energy_and_power[Energy Sources,window=_blank]
