= Combot

Combot is a contraction of combat and robot.
This robot type is responsible for fulfilling the murderous needs of its fabricators. 
There is no mistaking that a combot's role is to destroy life and break things.
This goal does not mean a combot is without rules of engagement or war rules.
A combot should not be an indiscriminate destroyer of everything.

Combots should not be mecha sized city killers that destroy the game balance.
Combots are supposed to be smaller sized drones that fit into a playable human scale.
However, a combot can still be a campaign disrupting killing machine.

Combots are broken robots that are no longer under the direction of a commander or corporation.
This lack of clear direction can make combots more disturbed than other robots.
The more powerful the combot, the more likely a powerful owner is looking to control it.
Combots often have a prehistory of being pursued by established groups in a campaign or milieu.

// new table for 6.0
//  Robot Attribute Requirements 
.*Combot Attribute Requirements*
[width="75%",cols="2*<"]
|===
2+<| Attribute minimums required for combot type

s|Combot Type
s|Attributes

|Expendable
|Nil

|Defensive
|CON 20

|Light Offensive
|CON 19; DEX 15

|Heavy Offensive
|CON 23; STR 27

s|Combot Type
s|Attributes
|===

// Expendable combat robot Expendable combat robot

== Expendable Combot

:art: combot_expendable.png
:width: 250px
:snark: Expendable combot.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a walking robot with a target on its helmet.

include::ROOT:partial$articulate.adoc[]

//  Expendable Data 
.*Expendable Combot Fabrication Info (C-E)*
[width="75%",cols="2*<"]
|===
2+<|High casualty cannon fodder for peace keeping or worse. 

2+<|*Attributes*

|Primes
|CON 2 or 4; DEX 4; INT 1 or 3; STR 4

|Minimums
|Nil

|Hit Points Max
|5 HPM per point of CON


|Adaptability
|0

|Size
|Medium

|Value:
|1000000

2+<|*Systems*

|Offensive
|1 roll Table 1

|Defensive
|1 roll

|Peripheral
|1 Basic
|===

These robots are ex-recon, ex-aids or malfunctioning mechanized infantry.
An expendable combot may be a walking bomb looking for its target.
Regardless of what it used to be, the expendable combot has gone freelance. 
Expendable combots can drive military vehicles in combat situations.
Regardless of the expendable's Intelligence score, it has a good memory for combat details. 

== Defensive Combot

:art: defensive_combot.png
:width: 350px
:snark: Winning the hearts and minds of robots.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Large robot with drill and cannons being offered a flower from a tiny humanoid.

include::ROOT:partial$articulate.adoc[]

//  Defensive  Data 
.*Defensive Combot Fabrication Info (C-D)*
[width="80%",cols="2*<"]
|===
2+<|Protect the perimeter. 

2+<|*Attributes*

|Primes
|CON 2, 4; DEX 4; INT 1, 3; STR 4

|Minimums
|CON 20 or greater

|Hit Points
|21-30 (1d10+20) per point of CON

|Adaptability
|-200

|Size
|Large

|Value:
|10000000

2+<|*Systems*

|Offensive
|1 roll Table 1

|Defensive
|1 per 4 points of CON

|Peripheral
|1 Basic
|===

Defensive combots defend positions from enemy attack.
They are naturally protective of geographical spaces and fellow personas.

Not surprisingly, defensive combots have many defensive systems.
A defensive combot with a 20 Constitution would get five defensive systems.
That is a lot of defences. 
All defensive combots have the following peripherals and programming baked in.

=== Demoralize
Demoralize is a programme that allows the robot to create short-range psychological discomforts.
The defensive combot can create irritating noises or utter vile comments and insults about the enemy.
This programming's in-game effect is unclear but mostly adds a colourful element to combat.
The defensive combot's Charisma score determines how effective her demoralizing actions are.

=== Fortify
Analyze attacking enemy formations to optimize defensive strategies.
Fortify programming can also determine if there is no organized attack pattern.
The success of fortify programming depends on the combot's Intelligence score.

=== Intruder Detection
Intruder detection makes it very difficult for anything to sneak into the detection perimeter.
The range of the detection perimeter is ten hexes per point of Awareness.
The success of detecting a perimeter violation is also dependent on the combot's Awareness score.

=== Anti-Anti-Detection System
Another ability included within the given range is the robots Anti-anti-detection system.
The anti-anti-detection system detects technological stealth devices within the intruder detection perimeter.
This system alerts the defensive combot to the presence of such devices, but the location of the anti-detection technology is not automatic.  
The effectiveness of the anti-anti-detection system depends on the combot's Awareness score.

=== Weapon Identification
A defensive combot can identify any weapon type that damages her. 
The success of weapon identification programming depends on the combot's Intelligence score.

== Light Offensive Combot

:art: combot_light_offensive.PNG
:width: 250px
:snark: Its the steel thing
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a floating pop machine loaded with guns and rocket launchers.

include::ROOT:partial$articulate.adoc[]

// light offensive combot
.*Light Offensive Combot Fabrication Info (C-L)*
[width="75%",cols="2*<"]
|===
2+<|Delivering freedom from a can. 

2+<|*Attributes*

|Primes
s|CON 2 or 4; DEX 4; INT 1 or 3; STR 4

|Minimums
|CON 19; DEX 15

|Hit Points
|16-25 (15+1d10) per point of CON

|Adaptability
|-50

|Size
|Large

|Value:
|100000000

2+<|*Systems*

|Offensive
|2 rolls on Table 2 +
1 roll on Table 3

|Defensive
|2 rolls

|Peripheral
|None
|===

Light offensive combots are attack drones. 
They have a plethora of small arms. 
Light offensive combots are for close-quarter combat, such as in cities or spaceships.
Light combots are tactical machines and are not considered expendable. 
If it fits the story, a light offensive referee persona combot will control expendable combots.
Referee persona light combots can have 0-3 (1d4-1) expendable combots under their command.

== Heavy Offensive Combot

:art: combot_heavy_offensive.png
:width: 250px
:snark: Offensive and heavy.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a tank sized robot with many big guns.

include::ROOT:partial$articulate.adoc[]

.*Heavy Offensive Combot Fabrication Info (C-H)*
[width="75%",cols="2*<"]
|===
2+<|Destroyer of all things in its path, even campaigns. 

2+<|*Attributes*

|Primes
|CON 2 or 4; DEX 4; INT 1 or 3; STR 4

|Minimums
|CON 23; STR 27

|Hit Points
|16-25 (15+1d10) per point of CON

|Adaptability
|-100

|Size
|Gigantic

|Value:
|1000000042

2+<|*Systems*

|Offensive
|1 roll on Table 2 +
1 roll on Table 3 +
1 roll on Table 4

|Defensive
|3 rolls

|Peripheral
|None
|===

The heavy offensive combot is the beast of the robot world.
The heavy offensive combot softens, destroys and punches through enemy lines.
The heavy offensive combot is literally heavy, and it is one of the few gigantic-sized robots.
The heavy also refers to the weapons that the combot carries.
Even this combot's smaller arms tend to be higher powered.
The heavy combot has heavy weapons like bombs, artillery and missiles.

Heavy offensive combots are hardened for combat and do not avoid risk. 
The Defence Rating for a heavy combot starts at 775.

=== Heavy Weapons
Every heavy offensive combot gets one roll on the Heavy Combot Heavy Weapon Table.
A heavy weapon can create a game imbalance.
The referee can neuter the heavy weapon by having the weapon out of ammunition or in need of launch codes. 
If the Nuk-O-Matic cannon wrecks the campaign balance, don't use it. 

include::robots:partial$heavy_combot_heavy_weapon.adoc[]