= Rescue

Rescue robots cover all the bases on non-policing emergency response.
There are two types of rescue robots. 
Retrieval rescue robots rescue people and property from dangerous environments.
Containment rescue robots suppress and contain those dangerous environments.
Rescue robots have many unique skills. 
Rescue robots value organic life and property; weaponizing their skills would be a challenge. 
If the player wishes to use them outside of a rescue, a Control Factor check is warranted.

Both robot types are fastidious about workplace safety and will usually advise against typical expedition plans.

== Retrieval Rescue Robot

//  Rescue Retrieval Fabrication Data 
.*Retrieval Rescue Robot Fabrication Info (R-R)*
[width="75%",cols="2*<"]
|===
2+<|Extricate life forms and equipment from danger.

2+<|*Attributes*

|Primes
|CON 4; DEX 2 or 4; INT 2 or 3; STR 1 or 3

|Minimums
|DEX 22

|Hit Points
|7-15 (2d10+5) per point of CON

|Adaptability
|10%

|Size
|Large

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|100% roll on Table 1 +
25% second roll on Table 1

|Defensive
|100% for 3 rolls

|Peripheral
|100% for 1 roll on Primary
|===

Retrieval robots remove people or bodies from dangerous situations.
The dangerous situations do not include combat. 
The dangerous situations are fires, landslides, radioactive areas, outer-space, etc.
They are capable of performing their duties underwater, in zero-gravity or a vacuum.

=== Alerting and Cordoning
Rescue robots have lights, sirens, and loudspeakers to warn and protect.
The retrieval robot can also cordon off a dangerous area. 
This robot has 50 hexes of glowing retractable fencing for cordoning off dangerous areas.

=== Target Retrieval
Target retrieval is a complicated way to describe rescuing personas.
Typically a persona or object wants to be rescued. 
Success is just a matter of time.
The more complicated the rescue, the longer it takes.
The referee and players decide the complexity of the rescue. 
The longer the retrieval takes, the more injured the victims become.
A retrieval could be automatic, require a success roll, or become an entire game session. 

Typically targets want to be rescued.
If the retrieval robot is rescuing a persona against her will, the robot must grapple the rescuee.
A successful attack roll indicates a successful grapple and rescue.
Once grappled, the robot stashes the rescuee in a nice cool stasis chamber.  

.*Grapple Rescue Checklist*
. Grapple target: the player must win an attack roll.
. Break grapple: the target must win a STR challenge
. Break stasis: the target cannot escape stasis

Grappling and stashing targets in a non-retrieval environment will require a CF check.

=== Stasis Chambers
Retrieval robots can store organic creatures in stasis chambers when necessary.
The robot has one stasis chamber for every two points of Strength.
So a retrieval robot with a 20 STR would have ten stasis chambers. 
The size of the fabricator type determines the size of the stasis chamber.

Inorganic rescuees are also stored in a stasis chamber if they fit.
Retrieved personas and toys stored in the stasis chamber will not come to harm.
The stasis chambers fail and eject their contents if the robot dies.

== Containment Rescue Robot

//  containment Rescue Fabrication Data 
.*Containment Rescue Robot Fabrication Info (R-C)*
[width="75%",cols="2*<"]
|===
2+<|Contain and remove hazardous or inconvenient substances.

2+<|*Attributes*

|Primes
|CON 4; DEX 2 or 4; INT 2 or 3; STR 1 or 3

|Minimums
|Nil

|Hit Points
|7-15 (2d10+5) per point of CON

|Adaptability
|10%

|Size
|Gigantic

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|25% roll on Table 1 

|Defensive
|100% for 3 rolls

|Peripheral
|100% for 1 roll on Primary
|===

Containment Rescue robots are like janitor robots for toxic environments.
Toxic environments include fire, chemicals, radiation, bacteriologic, nanopaths, infestations, Kirlian memetics, etc.
The referee determines what the toxic dangers are, and most will be technomagical.
These robots contain, remove, cordon or cover toxic and inconvenient substances.

=== Alerting and Cordoning
Containment robots have lights, sirens, and loudspeakers to warn and protect.
The containment robot can also cordon off a dangerous area. 
This robot has 250 hexes of glowing retractable fencing for cordoning off dangerous areas.

=== Detection
Containment robots can sense toxic danger at a range of ten hexes per point of Awareness score.
Toxic danger includes fire, radiation, chemicals, epidemics, dangerous thoughts, defective mutations, etc.
The toxic danger must be large enough to represent harm to a community.
For example, detection does not alarm if a poisonous alien were nearby.

=== Fire Suppression
The containment robot has a universal flame retardant, which will extinguish typical fires.
The robot can extinguish five hexes of fire for every point of Constitution score.
For example, a robot with CON 22 could put out 110 flaming hexes.
The flame retardant is non-toxic, is breathable, and has minimal residue.
The containment robot can recharge its fire suppression if basic materials are available.
Flame retardant is not weaponizable but may work as a distraction or as concealment. 

=== Storage
This robot uses various shovels, rakes, suckers, filters, and scoops for clean up.
The containment robot is capable of sifting through debris and storing only the toxic materials.
Once collected, the robot stores the toxins in a specialized hazardous waste hold. 
This hold has a capacity of 20 times the personas Wate Allowance.
How much a toxic danger weighs is up to the referee and players.

The containment robots do not neutralize toxins. 
That would be too easy.
Once the containment robot's hold is full, it will revert to covering toxic dangers.
Poisonous junk is still a hazard once stashed away.
A full containment robot may begin to glow, radiate or attract strange animals.

=== Covering and Concealment
A containment robot can cover a toxic area with a bespoke sealing plastic.
The spray-on containment barrier alters depending on the toxic danger.
The appearance and composition of the covering will be different for radiation vs mutagenic poison.
The robot has enough spray-on containment cover for 100 hexes of toxic danger.
Covering a toxic danger is the last resort or a temporary measure. 
Containment robots prefer to remove and store the offending agent.

If the player wishes to weaponize this system, it functions like a non-lethal web gun. 
For more info on this weapon jump to xref:hardware:armaments.adoc#_web_gun[Web Gun,window=_blank].
