= Social

:art: social_robot.png
:width: 250px
:snark: Social robot interrupting someone.
:artist: unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of bug eye humanoid robot tapping woman on shoulder.

include::ROOT:partial$articulate.adoc[]


//  Social Fabrication Data 
.*Social Robot Fabrication Info (S)*
[width="75%",cols="2*<"]
|===
2+<|Fluent in languages, etiquette and irritation

2+<|*Attributes*

|Ranges
|CON 1 or 2; DEX 1 or 2; INT 3 or 4; STR 1

|Minimums
|Nil

|Hit Points
|2-4 (1+d3) per point of CON

|Adaptability
|+20

|Size
|Medium

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|10% roll on Table 1

|Defensive
|84% for 1 roll (non-lethal)

|Peripheral
|1 Basic
|===

Social robots look after the social needs of organic personas.
They are also called robotlers, relation robots, or protocol droids.
Social robots roughly resemble their fabricator type.
This resemblance is purely for aesthetics, and it is obvious they are robots.
If the player wishes, she can replace the rolled Locomotion type with articulated legs.

== Language and Culture
Social robots speak the language of their fabricator type and many others.
This robot can speak ten languages per point of Intelligence score. 
So a persona with an 11 INT could fluently speak 110 languages.
When a social robot encounters a new language, the robot may already understand it.
The chance of already knowing the language a percent chance equal to her Intelligence score.
So a persona with an 11 INT has an 11% chance of already understanding the new language.
If a language is not already in her repository, the robot will acquire it in 1-4 (1d4) days. 

Culture is more complicated than language. 
A social robot can understand a culture's nuances to assist other personas.
A social robot can be pedantic about culture, and this habit does not guarantee seamless interactions.
The social robot's CHA would still play a role in the role-playing.
The robot can understand one culture per point of Intelligence score. 
So a persona with an 11 INT could understand 11 cultures.
If a culture is not already in the repository, the robot will acquire it in 1-4 (1d4) weeks. 

== Butler Skills
If the social robot understands a persona's language and culture, she can look after their social needs.
Looking after social needs includes preparing meals, preparing rooms, and suggesting up to date apparel. 
They do this well and take this task most seriously.
If the social robot is required to tend to guests outside of her know cultures, she will complain endlessly.
Robotlers can also tend to the needs of 4 guests per point of Intelligence score.
So a persona with an 11 INT could feed, water and entertain 44 personas.

include::robots:partial$fabricator_type.adoc[]
