= Transportation

Transport robots are the truckers, pilots and chauffeurs of the robot world.
They make every vehicle a self-driving vehicle.
While they can drive combat vehicles, they are not versed in vehicle combat.
Their goal is to get passengers and cargo safely to the chosen destination.
These robots do not have vehicle combat training.

The two types of transportation robots are inatmo and exatmo.
Inatmo transport robots pilot planetary vehicles. 
Exatmo transport robots pilot space-vehicles. 

NOTE: *INATMO* - short for in atmosphere. Gravity, weather, roads and ground. +
*EXATMO* - short for exterior to the atmosphere. Vacuum, special jumps, near light speed.

:art: inatmo_transport_bot.png
:width: 250px
:snark: Ware 2
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a boxy floating robot holding a steering wheel.

include::ROOT:partial$articulate.adoc[]

== Inatmo Transport Robot

//  Planetary Transport Fabrication Data 
.*Inatmo Transport Robot Fabrication Info (T-I)*
[width="75%",cols="2*<"]
|===
2+<|Cybernetic chauffeur for all manner of planetary vehicles.

2+<|*Attributes*

|Ranges
|CON 1; DEX 1, 4; INT 1, 4; STR 1

|Minimums
|Nil

|Hit Points
|9-12 (8+d4) per point of CON

|Adaptability
|-15

|Size
|Small

|Value:
|100000 times 2d6

2+<|*Systems*

|Offensive
|50% roll on Table 1

|Defensive
|40% for 1 roll

|Peripheral
|1 Basic
|===

Inatmo transport robots can pilot any planetside vehicle.
Planetside vehicles include trains, planes, cars, boats, submarines.
Planetside vehicles do not include non-powered vehicles like bicycles or skateboards.

Inatmo transport robots drive and navigate.
Exatmo transport robots pilot and astrogate.

=== Driving
Inatmo transport robots have attachments that allow them to drive any vehicle.
A vehicle is an artifact from xref:hardware:vehicles.adoc[Vehicles,window=_blank], but does not include self-powered vehicles.
The inatmo transport robot can pilot two vehicles per point of INT score.
A persona with an 11 INT could drive 22 separate vehicles. 
The chance that this robot already pilots the vehicle is 1% per point of INT.
A persona with an 11 INT has an 11% chance of already knowing how to drive a vehicle.
Inatmo transport robots are quick learners and add a new vehicle navigation system in 1-4 (1d4) minutes.
If the robot fills its driving repository, it must delete one of its vehicle systems before adding a new one.

=== Navigating
An inatmo transportation robot can find its way around with amazing accuracy.
If the robot is in a familiar city, it cannot get lost. 
This robot can interpret vague directions accurately.
Ab inatmo transport robot can easily find the grove of trees near the creek's bend by the big rocks.
The robot's navigation skills are unable to locate hypothetical places.
For example, "find the evil referee persona's hideout please" would not work.

== Exatmo Transport Robot

//  Extra-Planetary Transport Fabrication Data 
.*Exatmo Transport Robot Fabrication Info (T-X)*
[width="75%",cols="2*<"]
|===
2+<|Cybernetic chauffeur of celestial vehicles.  

2+<|*Attributes*

|Ranges
|CON 1; DEX 1, 4; INT 1, 4; STR 1

|Minimums
|DEX 22 INT 22

|Hit Points
|9-12 (8+d4) per point of CON

|Adaptability
|-30

|Size
|Small

|Value:
|100000 times 4d6

2+<|*Systems*

|Offensive
|50% roll on Table 1

|Defensive
|40% for 1 roll

|Peripheral
|1 Basic
|===

Exatmo transport robots can pilot and navigate space-vehicles.
Space-vehicles include spaceships, starships, space cruisers, jump ships, etc.
This mean almost any vehicle from xref:hardware:spacecraft.adoc[Space-Vehicles]. 
Space-vehicles do not include vehicles that are planetside. 
For example,  a low orbit plane is not a spacecraft.
An exatmo transport robot cannot drive planetside vehicles at all.

Exatmo transport robots pilot and astrogate.
Inatmo transport robots drive and navigate.

=== Piloting
Space-Vehicles will usually have some mechanism for integrating with an exatmo transport robot.
If there is no access port, the exatmo robot will have the necessary appendages to pilot the 
Piloting a space-vehicle refers to all inatmo and exatmo drive piloting. 
Piloting involves sub-light speed travel, exiting or entering an atmosphere. 
It does not include special drive piloting, which is specifically astrogation.

=== Astrogation
Astrogation involves navigating the space-vehicle across many light-years in an instant.
It requires non-existent math and technomagical special drives like warp, bubble, or probability.
This transport robot replaces an astrogator and integrates directly with the ship's computer.
There will always be a robot connection to the ship for astrogation.
The robot cannot pilot and astrogate at the same time.

