= Maintenance

:art: maintenance_bot.png
:width: 250px
:snark: Puzzling over ancient Newtek device.
:artist: Andrew Hotz
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of bipedal robot puzzling over a toaster.

include::ROOT:partial$articulate.adoc[]

//  maintenance 
.*Maintenance Robot Fabrication Info (M)*
[width="75%",cols="2*<"]
|===
2+<|Mechanic in a drum.

2+<|*Attributes*

|Primes
|CON 1,2; DEX 2, 3; INT 2, 3, 4; STR 1

|Minimums
|Nil.

|Hit Points
|1-4 (1d4) per point of CON

|Adaptability
|42%

|Size
|Small

|Value:
|100000 per point of INT

2+<|*Systems*

|Offensive
|40% roll on Table 1

|Defensive
|40% for 1 roll

|Peripheral
|100% for 2 rolls on Primary
|===

A maintenance robot is a mechanic in a drum.
This robot acts as a functioning xref:roll_playing_system:CH08_Vocations_Mechanic.adoc[mechanic,window=_blank].
"Maint" robots are interested in maintaining, repairing and improving inorganic objects.

The maintenance robot gets more bonuses and skills than a typical mechanic.
The player adds two times her Intelligence score to any maneuver rolls.
The maint robot starts with many more skills than a regular mechanic.
The player gets one roll on the mechanic skill table per two points of Intelligence score. 

include::ROOT:partial$CH08_Table_Mechanic_Skills.adoc[]


