= Hobbot

:art: hobbot.png 
:width: 250px
:snark: DIY blinged out with chrome accents.
:artist: unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of hemispheric floating robot with many claw like arms.

include::ROOT:partial$articulate.adoc[]

//  Hobbot Data 
.*Hobbot Fabrication Info (H)*
[width="75%",cols="2*<"]
|===
2+<|Highly modifiable hobbyist robot. 

2+<|*Attributes*

|Primes
|CON 1; DEX 1; INT 3 or 4; STR 1

|Minimums
|Nil

|Hit Points
|2-8 (2d4) per point of CON

|Adaptability
|100%

|Size
|Small or Tiny

|Value:
|10000 times 1d6

2+<|*Systems*

|Offensive
|10% roll on Table 1

|Defensive
|50% for 1 roll

|Peripheral
|2-8 (2d4)

|===

// table insert 28

Hobbots are hobbyist robots put together by enthusiastic amateur roboticists.
Hobbots can arise from a need for companionship, fun, or actual purpose.
Hobbots are the most easily modified of all the robots.
They also come with a plethora of Peripherals built-in. 
Hobbots have an unusual degree of uniqueness.  
Like snowflakes, no two hobbots are identical.
Hobbots should not be underestimated because of their humble origins.
A hobbot could easily hide a lethal or useful device in its chaotic chassis.