= Robot Series

There are many different robot series to choose from. 
From a heavy offensive combot capable of annihilating entire cities to a delicate hobbyist robot.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.* 

.List of Robot Series (Types)
* xref:robots:series_android.adoc[A-Android,window=_blank]
* xref:robots:series_combot.adoc[C-Combot,window=_blank]
* xref:robots:series_datalyzer.adoc[D-Datalyzer,window=_blank]
* xref:robots:series_exploration.adoc[E-Explorations,window=_blank]
* xref:robots:series_hobbot.adoc[H-Hobbot,window=_blank]
* xref:robots:series_industrial.adoc[I-Industrial,window=_blank]
* xref:robots:series_janitorial.adoc[J-Janitorial,window=_blank]
* xref:robots:series_maintenance.adoc[M-Maintenance,window=_blank]
* xref:robots:series_policing.adoc[P-Policing,window=_blank]
* xref:robots:series_rescue.adoc[R-Rescue,window=_blank]
* xref:robots:series_social.adoc[S-Social,window=_blank]
* xref:robots:series_transport.adoc[T-Transport,window=_blank]
* xref:robots:series_veterinarian.adoc[V-Veterinarian,window=_blank]


== Explaining Robot Fabrication Info
Each robot type has its own fabrication info.
The fabrication info details what makes the robot persona unique.
We will use the Datalyzer Fabrication Info as an example.

//  Datalyzer Data 
.*Datalyzer Fabrication Info (D)*
[width="75%",cols="2*<"]
|===
2+<|Number crunching, data analyzing, mad machines.
2+<|*Attributes*

|Required Primes
|CON 1 or 2; DEX 1 or 2; INT 4; STR 1 or 2

|Minimum Regular
|Nil

|Hit Points Max
|1d2+2 (1-3) HPM per point of CON

|Adaptability
|0

|Size
|Small

|Value
|10000 times 1d6

2+<|*Systems*

|Offensive
|5% 

|Defensive
|1 Auto

|Peripheral
|1 Auto. Plus 1 Secondary Peripheral
|===

== Title
The title lists the name of the robot series, its ID, and a catchy blurb about it.
The ID is the letter in brackets.
The Datalyzer's ID is D. 
For convenience, the ID is always the first letter of the robot type. 

== Attributes
All information about the robot's attributes is listed here. 

=== Primes
These are the attribute primes that are required by the robot type.
They are *NOT* minimums. 
They are exact numbers. 
A datalyzer must have a  STR Prime of 1 or 2.
A datalyzer *CANNOT* have a STR Prime of 3 or 4.

=== Minimums
These are the attribute minimums that are required by the robot subtypes.
A datalyzer has no subtypes, so nil is listed.
Other robot subtypes require specific regular attribute minimums. 

Combot has several subtypes.
The persona's regular attributes determine the subtype of combot.
For example, a heavy offensive combot needs a STR of 27 and a  STR prime of 4.

=== Hit Points
The range of hit points the robot type has is listed here.
The player gets one roll per point of Constitution using this value.
If this datalyzer robot has a 10 CON, she gets to roll 1d2+2 ten times to generate her hit points. 
For more information, jump to xref:robots:damage_and_demolition.adoc[Robot Hit Points,window=_blank].

=== Adaptability
Adaptability indicates how easy it is to modify the robot type. 
The higher the adaptability, the easier it is to modify the robot type.
The datalyzer has an adaptabilty (ADP) of 0. 
A hobbot has an adaptability of 42, which is added to the player's task roll.
A heavy offensive combot has an adaptability of -100, which added to the mechanic's task roll
For detailed information jump to xref:robots:adaptability.adoc[Adaptability,window=_blank].

=== Size
The size of the robot type is self-explanatory.
A medium-sized robot is about the same hite and wate as an anthro persona.
The size of the datalyzer is small.
For more information jump to xref:robots:size.adoc[Size,window=_blank].

=== Value
The robot value is entirely random and arbitrary.
The value gives a relative value to other robot types in the same culture and tech level.  
A datalyzer robot with a 22 INT has a base value of 220000 eps. 

The value listed is the base value. 
A robot's value can increase dramatically with the installation of valuable systems. 
For more info jump to to xref:robots:value.adoc[Value,window=_blank].

== Systems
Robotic systems are random abilities that accompany the robot at the fabrication point.
The systems indicate weapons, defences, or tools that are part of the robot.
Systems are baked in. 
Each robot has a chance at each of the three systems. 

===  Offensive 
Offensive systems are peripherals that the robot can use in combat to damage targets intentionally. 
The attack may be a baked-in weapon or a malfunctioning peripheral.
The data table indicates None, Auto, or a percent chance. 
The Datalyzer has a 5% chance of having an offensive system from the level 1 Offensive Peripherals Table. 

=== Defensive
Defensive systems are peripherals that the robot can use in combat to defend itself from damage. 
The defence may be a baked-in device or a malfunctioning peripheral.
The data table indicates None, Auto, or a percent chance. 
The Datalyzer automatically gets one roll on the defensive peripheral table. 
There is a 24% chance that the datalyzer will get a second defensive system. 

=== Peripheral 
Peripheral systems are random peripherals that assist the robot in carrying out its tasks. 
The peripheral effect may be a baked-in device or a malfunctioning peripheral.
The data table indicates None, Auto, or a percent chance. 
The random peripherals vary from the magnificent to the ridiculous.
The data table indicates None, Auto, or a percent chance. 
The datalyzer automatically gets two peripherals. 