= Robot Shape
Robots appear to be robots and have a basic inorganic shape. 
Unless the robot has a specific appearance, its gross shape is determined here.

The player can choose what she likes: fire hydrant, filing cabinet, kitchen appliance, etc.
The players cannot disguise her persona as a fire hydrant or a filing cabinet unless she has a robotic disguise skill.

If some random assistance is needed, consult the below tables.
The tables only offer a shape. 
The colour, design, sound, decals, smell, or detailing is still up to the player.
The referee may have some commercial patching, depending on the campaign.

NOTE: The robot shape has no bearing on attacks, peripherals or defences.

To determine the Hite and Wate of the robot jump to xref:roll_playing_system:robots:size.adoc[Robot Size,window=_blank]

:art: quizzical_fancy_bot.png
:width: 300px
:snark: Robot shape depends on story and milieu.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Humanoid robot with fancy plating and a narrow toga looks confused.

include::ROOT:partial$articulate.adoc[]

== Robotic Basic Shape
The volume of the robot will fit into this shape.

include::robots:partial$basic_shapes.adoc[]

== Contortion of Basic Shape
This table manipulates the basic shape of the robot.
This step is optional and is present to help reflect the randomness that is commercial design.

include::robots:partial$basic_shape_distortions.adoc[]
