= Defensive Systems

Defensive systems are anything that makes the robot harder to hit, damage or control.
Robot defences can be malfunctioning peripherals used as a defence in combat.
Most defences are hardenings that protect the robot while doing its assigned job.
The added defence in combat is a bonus.

Unlike the convoluted attack tables, there is only one Defensive Systems Table.
Each robot type has a clear direction on how to approach this table. 
Some robots have no defensive systems.
Others are designated multiple systems.  

include::robots:partial$peripherals_defensive.adoc[]

== Aunty Missile
This defensive system protects the robot from flying attacks.
The defence could be a baked-in defence or creative use of a peripheral.
Aunty missile is a combination of evasive actions, hardened casing and flechette. 
This defence can thwart most ranged attacks: Fling attacks, guided bombs, missiles, grenades, rockets or directed aerosols.
The defence does not work against powered small arms attacks like guns or crossbows (Shoot).
The robot's Defence Rating is increased by 50 to 300 (50d6 or 1d6*50) against missile attacks.

If the attack roll fails, the robot has destroyed the incoming attack. 
Destroying the attack also negates any area of effect damage that the missile could have delivered.
If the attack roll succeeds, the area of effect damage is halved.

== Aunty Personnel
This defensive system repels clamouring parasites or grappling hordes of attackers.
The player chooses the descriptive mechanism of the aunty personnel device.
Regardless of the mechanism, all aunty personnel defensive mechanisms operate the same.
For example, electric shock, sonic attack, flames, shrapnel, or cotton candy webs all have the same impact on attackers.

Aunty Personnel affects targets immediately adjacent to or touching the robot.
The defence has no effective range.
When activated, the player chooses between lethal or non-lethal defence.

=== Non-Lethal Aunty Personnel
The non-lethal aunty personnel defensive system places the well being of the attackers over the well being of the robot.
The player rolls an intensity of 4-24 (4d6) for each use of the defensive system. 
Any attacker in contact with, or immediately adjacent to, the robot must win a save or jump away. 
The players may divide up the saving rolls for groups of attackers to save time. 

The attackers are subject to intense pain, irritation or distraction.
None of the attackers can act during the non-lethal response, and those that fail the saving roll will recoil back.
In the non-lethal mode of aunty personnel, the robot may have restricted movement.
Ranged attackers are unaffected by this defensive system.

=== Lethal Anti-Personnel
The lethal aunty personnel defensive system places the robot's escape over the well being of the attackers.
The player rolls an intensity of 3-18 (3d6) for each use of the defensive system. 
Any attacker in contact with, or immediately adjacent to, the robot is injured and driven away by the defensive system. 
Every attacker takes a damage bolus in hit points equal to the aunty personal defensive system's intensity. 
If the player rolls a 9 for intensity, every attacker loses nine hit points.
This damage can be lethal to weaker attackers, hence the moniker.

The attackers are subject to intense pain, irritation or distraction, and killing damage.
None of the attackers can act during the aunty personnel response, and those that fail the saving roll will recoil back.
In this mode of aunty personnel, the robot can move freely amongst the crowd.
Ranged attackers are unaffected by this defensive system.

== Increase AR
This defensive system increases the robot's Defence Rating, making her harder to damage in combat.
The increase in Defence Rating could be chassis hardening, evasive maneuvers, or a combination of both.
Each visit to this defensive system increases the robot's Defence Rating by 
50 to 300 (1d6 times 50).
This defence's effects are cumulative, and multiple visits to this defence increase the AR each time.

== Artifact Armour
This defensive system replaces the robot's usual alloy hull with a specialized artifact armour.
The player generates the armour type from the xref:hardware:armour.adoc[Armour,window=_blank] section in hardware.
Any armour type can replace the robot's hull, from reflec to powered armour. 
The only limitation is that the armour type *cannot* make the robot weaker.
For example, the armour type cannot decrease the robot's Defence Rating.

== Camouflage
Often the best defence is to avoid being found.
This defensive system combines colour and structural changes with few electronic countermeasures. 
Camouflage is not invisibility, and it does not hold up to direct vision or inspection.
This defensive system is for hiding and is not useful for an ambush.
Ambush is an offensive system. 

The robot can camouflage herself against the sensor types that she has.
A robot with radar and video sensors could camouflage against radar and video.
Other vision types, organic ultravision etc., would visualize the robot as usual.

== Detect ambush
This defence makes it very difficult to surprise this robot.
The robot is four times more likely to detect something detrimental to it.
The robot quadruples (times 4) her Awareness score when detecting an ambush.
The defence includes active and passive ambushes. 
A robot with AWE 12 would use an AWE 48 detecting mines, trip wires or traps.

== Diffuse Bombs
This robot is a demolition demolishing expert.
The robot has both the technical and mechanical skills to defuse any bomb type.
The robot functions as a mechanic when defusing bombs.
The bomb is assigned a degree of difficulty, and the robot gets to work. 
This robot has no other mechanic skills what so ever.

When making the task roll, the player adds 5 to her experience level and doubles her Intelligence score.
This defensive system can also dismantle traps.
This defensive system cannot assist the robot in planting or making bombs or traps.
Diffusing bombs is a defensive system.

== Evasive action
Often the best defence is to run away.
This defensive system is essentially an automated tactical withdrawal mode.
In most instances, the robot *cannot* engage in combat while running away.
Only light and heavy offensive combots (types C-L and C-H) can use their offensive systems while engaging in evasive action.

Evasive action allows the robot to move at her regular movement rate through many obstacles: minefields, tank traps, robot pits and terrain.
The robot will exploit any cover, including her fellow expedition members, to escape.
The player cannot use evasive action to escape an essential plot point. 

== Force Field
This defensive system is the classic sciency fiction damage-absorbing force field.
The force field may or may not be invisible, but its presence becomes evident when it absorbs damage. 
The electromagical defensive shield will absorb every hit point of damage from almost every attack type. 
There are weapon types that specifically avoid force fields. 
The force only prevents damage and does not stop control attacks or otherwise harmless interventions. 

The force field will absorb any hit points that the robot would have taken.
A force field will absorb 25 to 100 HPS of damage (1d4*25).
The force field will shut down for 1 minute per HPS absorbed once depleted.

Force fields are cumulative, and multiple visits to this defensive system increase the force field's strength.
Robots do not earn experience for damage absorbed by their force field.

== Increase HPM
This defensive system increases the robot's hit points max.
The robot does not look too different because most of the improvements are internal. 
Increasing hit points maximum makes the robot a bit tougher.

The robot's hit points maximum increases by 10% to 60% (1d6).
A 30% increase for a robot with 100 HPM  increase her HPM to 130.
Increasing hit points max is cumulative. 
Each new visit increases the hit points max again.

== Psionic Mutation
This robot has a peripheral that functions the same as a uncombat psionic mutation.
The defence could be a baked-in defence or a creative peripheral malfunction.
If the psionic mutation requires Mind to function, the player uses her personas Intelligence score instead.

To generate the mutation jump to the specific table xref:wetware:psionics.adoc#_non_combat_mutations[Non Combat Psionic Mutations,window=_blank].
Ideally, the mutation will be a defensive one, but any uncombat psionic mutation will work if used defensively. 
Under no circumstances can this defensive system weaken the robot. 

== Override Interrupt
Robotic override is an attack that mechanics and robot owners use to regain control of a robot.
This defensive system makes the robot resistant to the robotic override attack.
The player can use override interrupt to break out of a control factor failure.
In short, override interrupt is a defensive system that gives the robot a chance to reboot its consciousness.

The referee may allow override interrupt to be automatic or award significant bonuses for resistance.
A respectable bonus would be tripling the robot's Intelligence to interrupt an override or loss of control. 
