= Peripherals

Peripherals are the things that robots can do. 
Peripherals are usually physical entities that may change the robots appearance or allow it to interact with the milieu.
This differentiates them from programmes which are ethereal and do not alter the robot's appearance.
Some peripherals are baked-in, like a combot's rifle.
Some peripherals are malfunctions, like a cleaning bot's acid jet.
In short these are robot abilities, but ability doesn't sound robotic enough. 

== Uncombat Peripherals
These are the classic attachments that make, break or irritate the robot persona.
Basic peripherals are admittedly dull, but when needed are very convenient.
Every robot gets one basic peripheral
Fancy peripherals are fantastical devices that enhance the robot, but rarely impact combat.

== Offensive Peripherals
Offensive peripherals is where the robots get all their attacks.
The universal robot attack, ramming, is described in this section. 
Offensive peripherals are divided into four tables of increasingly dangerous offensive capabilities.

== Defensive Peripherals
Defensive peripherals improve the robot's ability to avoid getting damaged.
These peripherals may be combat oriented, or environmentally oriented.
For example, increasing the Defence Rating may reflect protection from bullets, or dangerous machinery.

== Baked-in
Whether a peripheral is baked-in or not is story and persona based.
A combot that has a gun is going to be a baked-in gun that meant to be used as a gun.
A construction robot that has a gun is much more likely to be a malfunctioning nailer. 
Being baked-in does matter. 
If a weapon is baked-in the player may use her persona's attack table during combat.
Misused malfunctioning peripherals do no get to use bonuses on the attack table. 

Baked-in peripherals are less flexible than malfunctioning ones.
If a player wishes to use her baked-in gun as a nailer she may need to make a control factor (CF) roll.
If a robot is misusing her nailer as a gun, she could also use it as a nailer without problem. 

== Malfunctions
Peripherals are usually malfunctions if they are don't fit into the expected use of the series or model. 
Malfunctions are much more flexible than baked-in peripherals. 
However, malfunctions do not enjoy attack table bonuses when weaponized.

Malfunctations (robot mutation effects) are almost certainly malfunctions of the complicated technomagical circuitry of the robot.
However, if a combot has a lethal attack mutation there could be an argument for it being baked-in. 
