= Offensive Systems

Offensive peripherals are attacks that the persona can use to inflict damage on targets.
Most robots have no specific offensive peripherals, but all robots can ram.
Most robotic attacks are *not* baked in weapons like guns or lazers.
The robotic persona attacks are more often malfunctioning devices.
Whether the robot is ramming, misusing a peripheral or firing a lazer rifle, the player must win an attack roll to inflict damage.

include::robots:partial$peripherals_offensive_categories.adoc[]

All robots can weaponize themselves and ram targets with their chassis.
The robot type determines if there are any additional offensive peripherals. 
The robot type fabrication info has some gibberish on the offensive peripherals line.

This section does not cover robot combat. 
This section determines what attacks the robot has when she gets into combat.
For more info about robot combat jump to xref:combat:combat_and_robots.adoc[Robotic Combat,window=_blank].

.*Offensive Peripherals Decode*
* Nil: No offensive system. 
** Ramming is the only option.
* Percent: Percent chance of roll on the listed table
** E.g., 15% Table 1. If 1d100 less than 15 player rolls on Table 1.
* Roll: automatically gets a roll on the listed table
** E.g., 2 rolls Table 2. The player gets two rolls on Table 2.

== Offensive Peripherals Limitations
The referee and players should limit the amount and lethality of robotic offensive systems for campaign balance and fun.
A powerful robot can easily acquire a dozen thrusting and striking weapons.
The most dangerous attack table could fashion the robot with a long-range fusion bomb, or worse.
It is okay to limit the impact of powerful weapons creatively. 
It is okay to say "enough is enough already."

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Ramming 
Ramming is a robot's most basic attack, and all robots can ram.
To ram, the robot self-destructively flings itself at a target.
This attack a self-destructive exercise, and ramming often damages the robot.
This base level of ramming is not a robotic offensive system. 
The player must win a control factor roll before her robot can try and crash into something. 

NOTE: *All robots can ram!* _After a successful control factor roll._

The player must win a control factor roll before allowing her robot persona to ram. 
If the control factor roll allows for a ramming attempt, the player must win an attack roll to inflict damage.
The player determines the damage her ramming robot inflicts on the below table. 
The robot will always ram to inflict this amount of damage. 
Ramming is a Strike attack.

include::robots:partial$peripherals_offensive_ramming.adoc[]

A robot will only be able to ram opponents with a pre-determined part of its chassis.
This part will be considered the least vital and can withstand the repeated punishment.

== Attack Table One
Do not underestimate this attack table. 
Attack Table One can generate a collection of lethal close combat attacks very quickly.
There is also a chance to elevate to Attack Table Two from this table.
Attacks do not require a player to win a control factor roll to misuse them.

include::robots:partial$peripherals_offensive_1.adoc[]

=== Defensive System
Sometimes the best offence is a good defence. 
Jump to xref:robots:systems_defensive.adoc[Defensive Systems,window=_blank].

=== Striking Peripheral
The robot may use one of her peripherals as a dangerous striking weapon. 
If the robot has no obvious peripheral to misuse, it may have the actual weapon for a peripheral. 
The striking peripheral is a Strike attack. 
A tool for delicately holding vases can smash a nearby target instead. 
Multiple visits to striking peripheral are cumulative, and a robot can gather many simultaneous Strike attacks.

The player rolls on the Striking Peripheral Attack Table below to determine what kind of weapon the peripheral most resembles. 

include::robots:partial$peripherals_offensive_strike.adoc[]

=== Ramming Freedom
All robots can ram into targets, but they cannot do so casually.
The player must win a control factor roll before crashing her persona into things.
Robots with ramming freedom can ram as they please.
Ramming freedom is cumulative, and repeats of ramming freedom improve the attack.

.*Ramming Freedom Levels*
. No need for CF Roll to ram
. No damage to the robot from ram
. and above, +30 on attack roll per level

=== Table Two Attack
The player makes one roll on the more dangerous Attack Table Two.

== Attack Table Two
Attacks on this table are slightly more dangerous and further ranging than those on Attack Table One.
These attacks are a mix of baked-in devices and misusing peripherals.
Attacks do not require a player to make a control factor roll to misuse them.

include::robots:partial$peripherals_offensive_2.adoc[]

=== Two Rolls on Table One
The player makes two rolls on Attack Table One. 
This Attack Table Two result often leads to multiple attacks or improved attacks.

=== Ramming Freedom 2
Robots with ramming freedom can ram as they please.
This attack functions the same as two levels of <<_ramming_freedom,Ramming Freedom>>.
If this is the first roll for ramming freedom, it will start at level 2.
Cumulative rolls here increase the ramming freedom attack by 2 levels.

.*Ramming Freedom Levels*
. No need for CF Roll to ram
. No damage to the robot from ram
. and above, +30 on attack roll per level

=== Ranged Peripheral
The robot may use one of her peripherals as a deadly ranged weapon. 
If the robot has no obvious peripheral to misuse, it may have the actual weapon for a peripheral. 
The ranged peripheral is a Fling attack. 
A tool for putting lids on cans could instead launch them like shurikens.
Multiple visits to ranged peripheral are cumulative, and a robot can gather many simultaneous ranged attacks.

The player rolls on the Ranged Peripheral Attack Table below to determine what kind of weapon the peripheral most resembles. 
The ranged peripherals damage and ammunition supply is also on this table.

include::robots:partial$peripherals_offensive_fling.adoc[]

=== Nausea Attack
The nausea attack temporarily incapacitates organic targets with overwhelming nausea.
This robotic attack is an area of effect weapon.
As with other robot attacks, the nausea attack could arise from misusing a peripheral or a baked-in weapon.
The attack could arise from releasing toxic gases from the robot's power plant.
The nausea attack uses vapours, sprays or gases, and targets with atmospheric protections are unaffected. 

.*Range*
The range of the attack is one hex per point of her STR Prime score.
A robot with a 3 STR Prime has a range of 3 hexes from her chassis.

.*Intensity*
The intensity of the attack is random each time it is activated. 
The intensity of the attack is 3 to 12 (3d4).
The target must win a saving roll versus poison using her *constitution* or succumb to nausea and vomiting.
The attack has no effect if the target wins her saving roll. 
The incapacitation lasts for 0 to 3 units (1d4-1).

.*Cumulative*
The nausea attack is cumulative and repeatedly generating this attack makes it stronger.
The first appearance of nausea attack is level one. 
Each level increases the range by one hex and the intensity by 1-4 (1d4).

=== Paralysis Attack
The paralysis attack temporarily incapacitates organic targets with overwhelming weakness.
This robotic attack is an area of effect weapon.
As with other robot attacks, the paralysis attack could arise from misusing a peripheral or a baked-in weapon.
The attack could arise from releasing a damaging energy blast from the robot's power plant.
The paralysis attack uses waves, pulsations, and harmonics to penetrate atmospheric protections like vac suits. 

.*Range*
The range of the attack is one hex per point of her INT Prime score.
A robot with a 3 INT Prime has a range of 3 hexes from her chassis.

.*Intensity*
The intensity of the attack is random each time it is activated. 
The intensity of the attack is 3 to 12 (3d4).
The target must win a saving roll versus poison using her *dexterity* or succumb to incapacitation weakness.
The attack has no effect if the target wins her saving roll. 
The paralysis lasts for 0 to 3 units (1d4-1).

.*Cumulative*
The paralysis attack is cumulative and repeatedly generating this attack makes it stronger.
The first appearance of paralysis attack is level one. 
Each level increases the range by one hex and the intensity by 1-4 (1d4).

=== Powered Striking Peripheral
The robot may use one of her peripherals as a deadly striking weapon.
In addition to the regular Strike weapon damage, these peripherals are powered with an extra kick.
Each powered striking peripheral has the properties of a particular miscellaneous weapon.
To generate these attacks is a bit of a walk, but they are powerful and worth the player's effort.

Use the table at <<_striking_peripheral, Striking Peripheral>> to generate the weapon type.

If the robot has no obvious peripheral to misuse, it may have the actual weapon for a peripheral. 
A tool for mixing chemicals could become a vibrating mace. 
Multiple visits to powered striking peripherals are cumulative, and a robot can gather many simultaneous powered striking attacks.

Electro::
This Strike attack is electrified.
The electro weapon has a damage bonus of 2-16 (2d8) and an attack roll bonus of +100 against robots. 
For more info jump to xref:hardware:CH49_Misc_Weapons.adoc#_electro_weapon[Electro Weapon,window=_blank].

Inertia::
This Strike attack increases its density on contact.
The inertia weapon does triple the weapon damage plus ten hit points.
For more info jump to xref:hardware:CH49_Misc_Weapons.adoc#_inertia_weapon[Inertia Weapon,window=_blank].

Stun::
This Strike attack follows up with a debilitating stun attack. 
The damage of the attack converts from hit points stun intensity.
If the successful attack is to inflict 12 hit points of damage, it delivers a 12 intensity stun instead.
The target must win a saving roll against her Constitution or be stunned.
Organic targets are stunned for 1-4 minutes, and inorganic targets are stunned for 1-4 units.
For more info jump to xref:hardware:CH49_Misc_Weapons.adoc#_stun_weapons[Stun Weapon,window=_blank].

Vibro::
This Strike attack vibrates at damaging harmonic frequency. 
The vibro weapon has a damage bonus of +20 and an attack roll bonus of +100.
For more info jump to xref:hardware:CH49_Misc_Weapons.adoc#_vibro_weapon[Vibro Weapon,window=_blank].

=== Table Three Attack
The player makes one roll on the more dangerous Attack Table Three.

== Attack Table Three
Attacks on this table are slightly more dangerous and far-ranging than those on Attack Table Two.
These attacks are a mix of baked-in devices and misusing peripherals.
Attacks do not require a player to make a control factor roll to misuse them.

include::robots:partial$peripherals_offensive_3.adoc[]

=== 3 Rolls on Attack Table One
The player makes three rolls on Attack Table One. 
This Attack Table Three result leads to multiple attacks or improved attacks.
This table result can make the persona cumbersome to play or overpowered.
The referee may limit the total number of attacks to maintain game balance and story. 

=== 2 Rolls on Attack Table Two
The player makes two rolls on Attack Table Two. 
This Attack Table Three result often leads to multiple attacks or improved attacks.
This table result can make the persona cumbersome to play or overpowered.
The referee may limit the total number of attacks to maintain game balance and story. 

=== Nausea Attack 2
The nausea attack temporarily incapacitates organic targets with overwhelming nausea.
This robotic attack is an area of effect weapon.
This attack functions the same as two levels of <<_nausea_attack,Nausea Attack>>.
If this is the first roll for nausea attack, it will start at level 2.
Cumulative rolls here increase the nausea attack by 2 levels.

=== Paralysis Attack 2
The paralysis attack temporarily incapacitates organic targets with weakness.
This robotic attack is an area of effect weapon.
This attack functions the same as two levels of <<_paralysis_attack,Paralysis Attack>>.
If this is the first roll for paralysis attack, it will start at level 2.
Cumulative rolls here increase the paralysis attack by 2 levels.

=== Powered Ranged Peripherals
The robot may use one of her peripherals as a deadly ranged weapon.
In addition to the regular Fling weapon damage, these peripherals include an extra kick.
Each powered ranged peripheral has the properties of a particular miscellaneous weapon.
To generate these attacks is a bit of a walk, but they are powerful and worth the player's effort.

Use the table at <<_ranged_peripheral,Ranged Peripheral>> to generate the weapon type.

If the robot has no obvious peripheral to misuse, it may have the actual weapon for a peripheral. 
A tool for inserting power conducers could shoot electrified ceramic balls instead. 
Multiple visits to powered ranged peripheral are cumulative, and a robot can gather many simultaneous powered ranged attacks.

// todo move the actual data here for each type of attack to avoid page flipping

Electro::
This Fling attack is electrified.
The electro weapon has a damage bonus of 2-16 (2d8) and an attack roll bonus of +100 against robots. 
For more info jump to xref:hardware:CH49_Misc_Weapons.adoc#_electro_weapon[Electro Weapon,window=_blank].

Inertia::
This Fling attack increases its density on contact.
The inertia weapon does triple the weapon damage plus ten hit points.
For more info jump to xref:hardware:CH49_Misc_Weapons.adoc#_inertia_weapon[Inertia Weapon,window=_blank].

Stun::
This Fling attack follows up with a debilitating stun attack. 
The damage of the attack converts from hit points stun intensity.
If the successful attack is to inflict 12 hit points of damage, it delivers a 12 intensity stun instead.
The target must win a saving roll against her Constitution or be stunned.
Organic targets are stunned for 1-4 minutes, and inorganic targets are stunned for 1-4 units.
For more info jump to xref:hardware:CH49_Misc_Weapons.adoc#_stun_weapons[Stun Weapon,window=_blank].

Vibro::
This Fling attack vibrates at damaging harmonic frequency. 
The vibro weapon has a damage bonus of +20 and an attack roll bonus of +100.
For more info jump to xref:hardware:CH49_Misc_Weapons.adoc#_vibro_weapon[Vibro Weapon,window=_blank].

=== Thermal Blast
A thermal blast can be extreme cold or heat that the robot ejects to damage a target.
The player must choose between a pyro attack or a cryo attack, which cannot change.
Both attacks function equally and do not cause fires or freeze things shut.

The attack has a range of 1 hex per point of Dexterity.
The thermal blast is a Fling attack, and the player must win an attack roll to inflict damage.
A thermal blast inflicts 1-8 (1d8) hit points of damage per point of prime Strength.

=== Corrosive Mist
A corrosive mist can be acid or alkali haze that tat the robot ejects to damage a target.
The player must choose between an acid or alkali mist attack.
Both attacks function equally.

The attack has a range of 1 hex per point of Dexterity.
The corrosive mist is a Fling attack, and the player must win an attack roll to inflict damage.
A corrosive mist inflicts 1-8 (1d8) hit points of damage per point of prime Constitution.

=== Gun
This attack is most likely an actual weapon built into the robot.
If the player chooses it to be misused peripheral, the attack will function identical to the gun type.
To determine the gun type jump to xref:hardware:CH46_Guns.adoc#_gun_type[Guns,window=_blank].

=== Aerosol
This attack is most likely an actual weapon built into the robot.
If the player chooses it to be misused peripheral, the attack will function identical to the aerosol type.
To determine the aerosol type jump to xref:hardware:aerosols.adoc[Aerosols,window=_blank].

The aerosol type rolled should be limited to a combat aerosol.
There is no combat sub table for aerosols, and a useful combat aerosol may inflict no damage at all.
Powerful aerosols may require a 24 hour recharge period.

=== Table Four Attack
The player makes one roll on the ever so more dangerous Attack Table Four.

== Attack Table Four
This attack table is composed of lethal weapons that can quickly annihilate an entire expedition. 
The attacks found here are usually baked-in weapons and not malfunctioning peripherals.
The universal requirement is lethality.
Soft-touch attacks are not permitted when using Attack Table Four.

include::robots:partial$peripherals_offensive_4.adoc[]

=== 4 Rolls on Attack Table Two
The player makes four rolls on Attack Table Two. 
This Attack Table Four result leads to multiple attacks or improved attacks.
This table result can make the persona cumbersome to play or overpowered.
The referee may limit the total number of attacks to maintain game balance and story. 

=== 3 Rolls on Attack Table Three
The player makes three rolls on Attack Table Three. 
This Attack Table Four result leads to multiple attacks or improved attacks.
This table result can make the persona cumbersome to play or overpowered.
The referee may limit the total number of attacks to maintain game balance and story. 

=== Lethal Jet
The lethal jet is a killing poison attack. 
This attack is a baked-in intentional killing tool that the robot ejects from its chassis.
The lethal jet only works on organic targets.
The jet is a Shoot attack, and the player must win an attack roll for the poison to take.

A robot cannot have more than one lethal jet attack. 
A second lethal jet should be replaced by a different Attack Table Four result. 

.*Range*
The range of the attack is one hex per point of her Strength score.
A robot with a 13 STR has a  lethal jet range of 13 hexes.

.*Intensity*
The intensity of the attack is different each time it is activated. 
The initial poison attack intensity is 1-8 (1d8) per point of prime STR.
A robot with a prime STR of 3 has a poison intensity of 3-24.

The organic target must win a poison roll or die.
Anthros that lose their poison roll fall unconscious and have -1 hit points.
Aliens that lose their poison roll fall unconscious and have 1 hit points.
Anthros and aliens are dead in ten units without intervention.

Organic targets that win their saving throw take 1-4 hit points (1d4) of damage per point of poison intensity. 
If this damage proves lethal, the persona may switch her saving throw to a loss. 

=== Gun
On Attack Table Four, a  gun is most likely an actual gun built into the robot.
There is a minimum lethality required for the gun-type 
No soft touch guns are allowed. 
The attack must be a killing attack.
The gun type will automatically upgrade to the rifle version.
The gun power (calibre) will automatically upgrade to the highest power version. 
To determine the gun type jump to xref:hardware:CH46_Guns.adoc#_gun_type[Guns,window=_blank].

=== Grenade
This attack employs a self-launching lethal grenade attack.
There is a minimum lethality required for the grenade.
No soft touch grenades are allowed. 
The grenade must have a killing attack.

The player must win a Fling attack roll to hit the target hex.
Like all grenades, close does count.
The grenade is an area of effect weapon damaging, targets and colleagues alike.
The attack has a range of 2 hexes per point of Strength.
To determine the grenade type jump to xref:hardware:CH45_Grenades.adoc#_grenade_type[Grenades,window=_blank].

=== Bomb
The robot has a single bomb that she can launch from her chassis. 
The range of the attack is 1 kilometre per point of STR prime.
To determine the bomb type jump to to xref:hardware:CH44_Bombs.adoc[Bombs,window=_blank].

=== Aerosol
On Attack Table Four, an aerosol will be an actual weapon built into the robot.
The aerosol type rolled must be a killing aerosol.
No soft touch aerosols are allowed.
The aerosol can recharge after one minute of uncombat time.
To determine the aerosol type jump to xref:hardware:aerosols.adoc[Aerosols,window=_blank].

=== Combat Mutation 
The robot will have a baked-in weapon that functions like a mutation.
The mutation must be a combat mutation. 
The mutation cannot be a defect or compromise the persona in any way.

Robots have a zero Mind score. 
The player uses the robot's Intelligence score for mutations that depend on Mind. 

The mutation type can be a Psionic Mutation or a Phenomic Mutation.
If the player rolls less than her constitution score on 1d100, the attack has a xref:wetware:CH59_Physical.adoc#_combat_mutations[Phenomic Mutation,window=_blank] effect.
If the 1d100 roll is greater than her constitution score, the attack has a xref:wetware:CH58_Mental.adoc#_combat_mutations[Psionic Mutation,window=_blank] effect.

=== Disregard Fabricator
This offensive system disengages any connection to the persona's fabricator type.
Fabricator based commands do not weigh on this robot's programming.

This attack does not count as a roll.
The player records this programming aberration on her persona record and restarts the Offensive System roll.
So if the player started at Attack Table Two, she would restart on Attack Table Two.
This restart may be frustrating to players.
Robots do not exhibit frustration.

=== Ref's Own Table
Look out! Here comes something zany.
If the referee does not have a Ref's Own Table, she can pick an appropriate level 4 attack for the robot.
It is up to the referee if the player can pick a level 4 attack for her persona. 