= Systems

Systems are the things that robots can do. 
Some systems are baked-in, like a combot's rifle.
Some systems are malfunctions, like a cleaning bot's acid jet.
In short these are robot abilities, but ability doesn't sound robotic enough. 

== Baked-in
Whether a system is baked-in or not is story and persona based.
A combot that has a gun is going to be a baked-in gun that meant to be used as a gun.
A construction robot that has a gun is much more likely to be a malfunctioning nailer. 
Being baked-in does matter. 
If a weapon is baked-in the player may use her persona's attack table during combat.
Misused malfunctioning systems do no get to use bonuses on the attack table. 

Baked-in systems are less flexible than malfunctioning ones.
If a player wishes to use her baked-in gun as a nailer she may need to make a control factor (CF) roll.
If a robot is misusing her nailer as a gun, she could also use it as a nailer without problem. 

== Malfunctions
Systems are usually malfunctions if they are don't fit into the expected use of the series or model. 
Malfunctions are much more flexible than baked-in systems. 
However, malfunctions do not enjoy attack table bonuses when weaponized.

Malfunctations (robot malfunction) are almost certainly malfunctions of the complicated technomagical circuitry of the robot.
However, if a combot has a lethal attack mutation there could be an argument for it being baked-in. 

== Offensive Systems
Offensive systems is where the robots get all their attacks.
The universal robot attack, ramming, is described in this section. 
Offensive systems are divided into four tables of increasingly dangerous offensive capabilities.

== Defensive Systems
Defensive systems improve the robot's ability to avoid getting damaged.
These systems may be combat oriented, or environmentally oriented.
For example, increasing the Defence Rating may reflect protection from bullets, or dangerous machinery.

== Peripheral Systems
These are the classic attachments that make, break or irritate the robot persona.
Basic peripherals are admittedly dull, but when needed very convenient.
Fancy peripherals are fantastical devices that enhance the robot, but rarely impact combat.


