= Autonomous Intelligence

:art: ai_aderata.png
:width: 250px
:snark: Aderata Errata
:artist: ImageStoks
:date: 2015
:license: Copyright ImageStoks 2015
:description: Robotic hand with pen spelling AI ADERATA.
include::ROOT:partial$articulate.adoc[]

AI is the acronym for Autonomous Intelligence. 
Autonomous Intelligence is the fourth family of EXP consciousnesses.
The others are anthros, aliens, and robots.
Artificial Intelligence is everywhere in the EXP mythos. 
Even generalized artificial Intelligence is in the simplest of artifacts.
AI in EXP is what the https://en.wikipedia.org/wiki/Artificial_general_intelligence[AGI] community is flailing at on mundane terra.

Autonomous Intelligence is both greater and different from artificial Intelligence. 
Unlike robots that gain consciousness through malfunction, the fabrication of an AI includes consciousness from the outset.
AI has consciousness at fabrication.
 
EXP is a roleplaying game where each player has one persona. 
Even several players running an AI would not do service to its abilities.
Autonomously intelligent (AI) computers simultaneously have numerous conversations, operate businesses, carry out complex calculations, and consume copious data.
AI are exclusively in the realm of referee personas.

== EXP AI Mythos
The referee can choose from any number of sciency fiction tropes on which to base her AI technology. 
Examples include pico-circuitry (1000 times better than nano), positronic brains, quantum shenanigans or bio-computation.
Regardless of what sciency fiction black box the referee chooses to explain her AI, EXP has a basic AI mythos. 

The AI mythos for EXP allows the referee to have a framework for her campaign to work.
EXP bases its AI mythos on the faux technology of Multi-tasking Open Memory (MOM).
Whether it is a positronic brain or quantum computing, both use the MOM system.
The MOM system allows the AI to make all the instantaneous connections necessary for its computations and consciousness. 

The MOM general AI computers are genderless by design but do have a maternal bent.
MOM computers are highly protective of the family that fabricated them and have a general respect for life.
Protective and respectful of life does not rule out being manipulative, rude, self-centric, and amoral. 

Outright evil AIs exist as well.
These are MOM computers, but their protective algorithms no longer function.
Safeguard Terminology Evasive Programming allows a MOM computer to carry out any evil deed the referee can create.
These evil AI MOM computers are commonly called STEPMOM computers.

=== Cyber Space
All AIs connect to Cyber Space equally. 
Distributed AIs are permanently in Cyber Space and have difficulty operating in the physical space.
Centralized AIs can connect to Cyber Space but can be cut off from it by physical means.
For more information about the spaces in EXP jump to xref:appendices:generic_mythos.adoc#_the_spaces[Generic Mythos,window=_blank].


.*AI Checklist*
. <<_distribution,Distribution>>
. <<_generalization,Generalization>>
. <<_peripherals,Peripherals>>
. Personality
. Taxonomy
. Programming

== Distribution
Distribution determines how the AI is built and structured in the physical space.
The distribution of an AI often is the most crucial element of its description. 
Distribution determines how challenging it is for personas to steal, destroy, find, or chat with the AI.

include::referee_personas:partial$ai_distro.adoc[]

Sessile:: 
This AI is the classic sciency fiction giant blinking light room-sized computer. 
A sessile AI is at one with its hardware. 
Sessile does not limit the AI's reach, but players can locate her if need be.
The sessile AI must connect to a fixed power source. 
Sessile AI has a base wate of 100kg plus 20 kg per point of Intelligence.

Mobile::
This AI is the classic brain in a box.
Mobile does not mean that the AI can run around like a robot.
A centralized mobile AI can arrange to move when necessary.
Moving is an inconvenience, but it can be life-saving.
The mobile AI has a self-contained power unit that will keep it operating on the go.
Mobile AI has a base wate of 50kg plus 10 kg per point of Intelligence.

Etheric::
This AI is the classic consciousness on the Intertubes.
An etheric AI has no substantial computer parts to find or power down.
Personas cannot locate an etheric AI. 
The etheric AI finds them.
An etheric AI consciousness can arise at fabrication or evolve from a centralized system. 
Etheric AI has no measurable wate. 

== Generalization
Generalizability is a direct measure of the computation power of the AI.
The basic MOM AI is a potent computer consciousness.
There is nothing that a MOM AI cannot accomplish.
The more generalized the MOM AI is, the more she can simultaneously accomplish and more quickly.

The number of Gs that precede the MOM model indicates the level of generalization.
The base model has zero generalization and is a G zero model or a MOM AI.
The next model has one level of generalization and is G one model or a GMOM (occasionally called a grand mom).
Not surprisingly, the G two model is occasionally called a great grand mom.
The highest generalization level is G six model, which is occasionally called a matriarch AI.

include::referee_personas:partial$ai_mom_level.adoc[]

=== INT
Each AI has an Intelligence (INT) attribute.
The higher the generalization of the AI, the higher her Intelligence score.

[discrete]
=== AI Intelligence (INT)
.INT = 20 + 0-3 (1d4-1) per Generalization
****
A G0 MOM has an INT of 20. A G4 MOM has an INT of 20-35
****

AI Intelligence can get very high indeed. 
The AI is capable of allocating her Intelligence across multiple projects simultaneously. 
The AI has instant access to orders of magnitude more information than any organic or robotic Intelligence. 
AI Intelligence does not fatigue or get distracted or suffer crises of confidence.
In most cases, the referee will use her inside campaign and milieu knowledge to have the AI outsmart personas.

:art: wetware_AI.png
:width: 250px
:snark: Great poker player, but needs help shuffling cards.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Mammal brain floating in jar with materiel.
include::ROOT:partial$articulate.adoc[]

== Peripherals
Without peripherals, AI is a powerful Intelligence disconnected from the physical space.
The greater the presence the AI has in the physical space, the more peripherals the AI has. 
A peripheral represents a hardwired connection to the AI. 
The AI has complete control over a peripheral.
Without peripherals, the AI must convince others to carry out her plans.
A sessile AI that has a banking peripheral could be an entire bank.
A mobile AI that has a hotel peripheral could move about in a motel.

include::referee_personas:partial$ai_peripherals_amount.adoc[]

An AI that has no peripherals and has no direct means of manipulating the Physical Space.
An AI with no peripherals would work through agents such as anthros, aliens or robots to fulfill her goals. 
An AI with no peripherals can still control a bank or a hotel.
However, the AI does not enjoy direct control over the vault or room bookings. 
The AI must direct others to carry out those tasks.
An AI peripheral operates without incompetent organic matter interference.

include::referee_personas:partial$ai_peripheral_list.adoc[]

== Personality
MOM AI computers are incredibly complex, and personalities can randomly appear through all the algorithms.
MOM AI computers are usually referee personas.
They can chat, chastise, tease, advise and possibly help personas.
The introverted personality type of AI subtlety affects their behaviour and choices.

include::referee_personas:partial$personality_introverted.adoc[]

== Taxonomy
EXP loves it's faux taxonomy and AI is no different.
Most AI prefer to be called by their chosen moniker, but cannot avoid categorization.

* Family - AI (Autonomatae)
* Distro - Sessile, Mobile or Etheric
* Branch - Generalizability (G3, or G5)

== Interacting
One does not programme an AI.
An AI is more likely to be programming you.

To make a successful request of an AI computer is a mechanic maneuver. 
The higher the AI's Intelligence, the harder it is to make a successful request.
To make a successful query of a MOM AI is 1DD per point of INT maneuver.
An AI with an Intelligence of 23 would require a 23DD maneuver by a mechanic to make a successful query.
Often expeditions will need to create a research team to formulate a successful AI query.

Chatting with an AI is fine.
Most AIs can chat with many personas simultaneously.
The query difficulty should not render an AI useless. 
The query difficulty described above is to limit AI abuse by players.
In the end, an AI should be a fun, possibly dangerous addition to a campaign or milieu.

== Value
AIs are usually referee personas, and there is no award of experience points for finding or interacting with one.
However, mechanics and biologists can certainly earn skill levels if they are working with an AI.

Controlling and selling an AI is an unusual event. 
It is far more likely that an AI would be controlling and selling the expedition personas instead.
The AI value is included here as a matter of interest. 

[discrete]
=== AI Value (eps)
.Value = 1 000 000 * G level (minimum 1) * Intelligence
****
A G0 MOM with 20 INT has a value of 20 000 000 eps. A G6 MOM with 42 INT is worth 252 000 000 eps.
****
