= Alien RP

Aliens are organic lifeforms.
In the faux taxonomy, aliens are of the family Diversidae.
The evolution of an alien is random and can lead to any shape, size, or colour.
This randomness makes aliens genuinely diverse, and hence the family name.
Each RP alien is unique unto itself; however, it is a member of a species.

The referee may visit this section to evolve some flora and fauna for her milieu and end up with a previously unknown space-faring species.
The referee should massage the alien RP to fit her milieu.
The Alien RP section is for helping creativity, not replacing it.

== Record Sheet
You will not be able to keep track of everything that is needed for a referee persona.
It is recommended that you print out a persona record sheet to keep track of stuff.
Download the bare bones PDF (75K) at xref:ROOT:attachment$alien_record_v7.pdf[Alien Record v7]

NOTE: *If it's worth creating, it's worth writing down.*

== Relevance
Not all RPs are created equal.
Some personas are less important than others.
The referee usually knows the importance of the persona before she starts generation.
An RP's relevance increases the more entangled they are with the expedition.

include::referee_personas:partial$persona_relevance.adoc[]

== Species vs RP
The alien being evolved is usually a member of a species. 
The species could be mundane flora and fauna, an invading alien horde, or a close encounter of the 3.14th kind.
The species may define everything the referee requires for her RP. 
Every member of the species may all have the same size, shape, belief and personality.
A homogeneous alien species is undoubtedly the easiest pathway for the referee.

An alien referee persona need not be part of an entire species. 
There are many story-based explanations of solitary aliens.
The alien may be the sole member of an alien species so distant they will never be part of the story.
The alien may be the sole survivor of a species that suffered some cataclysm.
The alien may have been grown in a mad biologist's vat for nefarious purposes.

If an alien is part of a larger alien species she may have her own way of partaking in that species.
The RP Story Cues represent the individual quirks of the alien. 
These may set the persona apart from her species predominant smell, religion or political beliefs.

== Attributes
Alien RP attributes have the same ranges as player persona alien attributes. 
If the referee is looking for a particular configuration of attributes, she can change them in the <<_strong_descriptors,Strong Descriptors>> section.

include::aliens:partial$attributes_generation_list.adoc[]

== Size
The size of the alien RP affects its appearance, wate and hits points.
Alien RPs can have extremely small or large sizes that are not available to player personas.
These extreme sizes are called Minute and Humongous.

include::aliens:partial$size_category_list.adoc[]

=== Minute 
Any Tiny alien has a 1 in 6 chance to be *Minute* instead.
Minute aliens have a WATE of  0 to 999 grams (1d1000-1).
A Minute alien will never have a WATE greater than a kilogram.
Being Minute decreases the alien's STR and HPM but does not affect other attributes. 

==== Minute Alien HPM and STR adjustment
.HPM = (rolled HPM) * (wate/1000)
.STR = (rolled STR) * (wate/1000)
****
An alien with 50 HPM, 12 STR, and 500 gm Wate would have 25 HPM and 6 STR. +
The minimum STR and HPM of a Minute alien are 1.
****

=== Humongous
Any Gigantic alien has a 1 in 6 chance to be *Humongous* instead.
Humongous aliens have a WATE of 6 to 300 tons (1d50 times 6).
Being a humongous alien is just an inconvenience as they have no alteration in their attributes or hit points.

== Hit Points Max
Bigger aliens tend to have more hit points than smaller aliens.
Minute aliens must apply their size modification to the hit points generated here.

include::aliens:partial$hit_points_and_size.adoc[]

== Attacks
The number of attacks indicates the number of attack rolls the referee makes each unit.
This attack frequency is only for the alien's naturally evolved attacks and does not apply to equipment weapons.

include::aliens:partial$attack_frequency_amounts.adoc[]

== Attack Type
The vast majority of aliens will bite, slap, punch and kick their way through combat.
Other attack types exist.
For simplicity, the attack type will apply to all of the alien's attacks. 
The referee can make multiple rolls on this table to give her RP alien with multiple attacks different kinds of attacks. 
For instance, an alien with three attacks per unit could have three Strike attacks or two Strike attacks and one Fling attack.

include::aliens:partial$attack_type_options.adoc[]

== Damage
Bigger aliens tend to inflict more damage than smaller aliens.
Minute aliens must apply their STR modification before determining their damage per attack.
The damage per attack is only for the alien's naturally evolved attacks and does not apply to equipment weapons.

include::aliens:partial$attack_damage_and_size.adoc[]

== Defence
How hard is it to damage this alien in combat?

include::aliens:defence_rating.adoc[tag=Alien_AR]

== Shape
The alien shape is entirely random and makes for very diverse corporeal denizens.
For more details about alien shape, jump to Detailed explanation exist at xref:aliens:alien_shape.adoc[Alien Shape,window=_blank].

The referee makes four rolls on the Alien Body Parts Table.
One roll for each of the four body parts that compose the alien. 
Each body part has a terrain type associated with it.
The terrain type is in brackets and looks like (l, a, w, s).
It is crucial to record the terrain type along with the shape of the body part.

.Roll once for each body part.
. Head
. Torso
. Arms
. Legs

include::aliens:partial$alien_shape_body_parts.adoc[]

[discrete]
=== Adornments
These are optional accents to the alien's appearance.
Adornments are entirely descriptive.
Adornments do not detract from or add any abilities to the alien. 

// head adornment
include::aliens:partial$alien_shape_head_adornment.adoc[]

// torso adornment
include::aliens:partial$alien_shape_torso_adornment.adoc[]

// arms adornment
include::aliens:partial$alien_shape_arm_adornment.adoc[]

=== Coat and Colour
The referee can leave the alien as a patchwork of different skin types or choose a particular coat from one body part.
The colour can be as complicated or as simple as desired. 
The referee can massage the alien colour to match the terrain or reflect its abilities.
The referee can generate a random colour from the xref:referee_personas:rp_story_cues.adoc#_colour[Giant Colour Table,window=_blank]. 

== Movement
Alien movement rate is as important as size in regards to combat.
The shape of the alien determines whether it hops, slithers, flaps, or gallops along.
More detail is available at xref:aliens:movement.adoc[Alien Movement,window=_blank]

[discrete]
=== Movement Quarter
.move (h/u) = DEX / 4
****
An alien with a 12 DEX would have a Movement Quarter of 3 h/u. 
****
Add the terrain types (l, a, w) for each body part shape and multiply them by the movement unit.

include::aliens:partial$movement_calculation.adoc[]

== Evolutations
Aliens can enjoy all the special abilities that psionic and phenomic mutations offer.
However when a player is generating an alien they are generating an entire genus and species.
These mutation abilities are evolved abilities and not point mutations. 
Hence the naming convention of evolutation.

Adding powerful mutations to an entire species requires consideration to plot and milieu.
An evolutation may only appear at certain life stages, or only certain members of the species have the evolutation.
An army of gigantic flying aliens with death field generation would be a world breaker. 
However, a species of tiny aliens with weak telekinesis would be make for an interesting culture. 

Aliens are biological in nature and can acquire unique mutations from radiation or cheeky pharma.

=== Psionic
The chance of an alien having a psionic mutation is equal to the alien's Mind attribute score.
An alien with a 15 MND would have a 15% chance of having a psionic mutation.
Player personas cannot start with a defect.
Aliens do not have multiple psionic mutations.
To determine the evolutation jump to xref:wetware:psionics.adoc[Psionic Mutations,window=_blank].

=== Phenomic
The chance of a creature having evolved a phenomic mutation is equal to the alien's Constitution attribute score.
An alien with a 10 CON has a 10% chance of having a phenomic mutation.
Player personas cannot start with a defect.
Aliens do not have multiple phenomic mutations.
To determine the evolutation jump to xref:wetware:phenomics.adoc[Phenomic Mutations,window=_blank].

== Life Span
Life expectancy is defining feature of organic life forms. 

include::aliens:partial$life_spans.adoc[]

=== Short Life
If the alien's life span is less than ten years, there is a 1 in 6 (1d6) chance that the alien will have an extremely short life span.
Extremely short life spans should influence the alien RP's biology and society.
Short-lived species often depend on large numbers of offspring requiring minimal energy exertion.
This biological process is called progeny over prodigy.

include::referee_personas:partial$alien_short_life_span.adoc[]

=== Long Life
If the alien's life span is more than 10000 years, there is a 1 in 6 (1d6) chance that the alien will have an extremely long life span.
Extremely long life spans should influence the alien RP's biology and society.
Long-lived species often devote increased energy to fewer, more advanced offspring.
This biological process is called prodigy over progeny.

[discrete]
==== Extremely Long Life Spans
.100000 - 100000000 (100000 * 1d1000) years 
****
500 on the 1d1000 yields a life span of 50 million years.
****

=== Life Categories
The amount of time spent in each age category 

include::aliens:partial$life_span_stages.adoc[]

== Age 
To determine the persona age the referee must determine the age category  first.
All biological life forms have the same age categories.

include::referee_personas:partial$age_categories.adoc[]

Once the age category is determined the referee can just assign any age that fits into the age category.
It is very common to just use the age category for aliens, skipping all the maths. 

== EXPS Level
Good for flora, fauna, and vocations.
An alien predator with a high experience level will be more dangerous than a low-level predator of the same species.

include::referee_personas:partial$experience_levels.adoc[]

== Strong Descriptors
Often a referee will want a tiny alien, a dumb alien, a slow alien, or even a stupid, slow, small alien (prey).
Alien attributes tend to be higher than other personas. 
Descriptors such as tough, smart and strong give attribute values relative to anthro personas.
This table may fall short if the referee is trying to generate an alien persona stronger than other aliens in her species.
The downwards attribute modifications are most helpful.

include::referee_personas:partial$strong_descriptors.adoc[]

== Wate Allowance
The wate allowance is the same for all personas. 
The WA indicates how much the alien can carry without being encumbered.
For tool users this could be weapons and computers. 
For flora and fauna wate allowance represents what they can push around for no good reason.

include::anthros:partial$wate_allowance_and_strength.adoc[]

== Attack Table
The attack table keeps track of the persona's combat skills and increases with EXPS level.
The referee may need two attack tables for her tool using aliens.
For general info about attack tables, jump to xref:combat:attack_table_details.adoc[Attack Tables,window=_blank] in tactical combat.

The attack table calculated here is for the alien's naturally evolved attacks and is *not* used for any tool using attacks.
For a detailed explanation of alien attack tables jump to xref:aliens:attack_table.adoc[Alien Attack Table,window=_blank].
Aliens that are tool users do not use their alien attack table when using weapons. 
The referee must generate another vocation attack table for tool users.
For the vocation based attack table, jump to xref:anthros:attack_table[Anthro attack table,window=_blank].

== Biology
Alien biology assigns terrain, eating habits, reproduction etc.
The referee should always massage the alien biology to work best within her campaign milieu.
Many alien species will have evolved beyond the most primal aspects of their biology.
It would be unlikely for a creator tool user to still ambush prey in the desert, but their restaurants may reflect this biological history.

=== Biome
The biome is an alien's naturally evolved terrain type.
Flora and fauna would not venture beyond their terrain type.
More advanced alien species are not limited to their biome.

include::aliens:partial$biome_list.adoc[]

=== Food Source
Nom noms.

include::aliens:partial$energy_sources.adoc[]

=== Food Procurement
How does the alien get its nom noms?

include::aliens:partial$energy_procurement.adoc[]

=== Reproduction
Where do little aliens come from?

include::aliens:partial$reproduction_method_list.adoc[]

=== Dwelling
Typical living space.
Tool usage may allow the alien species to live in architecture informed by this biological history.

include::aliens:partial$habitation_list.adoc[]

=== Grouping
Do they hang out in groups or solo?

include::aliens:partial$grouping_types.adoc[]

=== Aroma
What a wonderful smell you have discovered.

include::aliens:partial$aroma_list.adoc[]

== Society
Alien society is something for the referee to consider and prepare for her campaign carefully.
A single alien society can be the basis for an entire campaign.
The process for determining an alien player persona's society is complex and time-consuming.

For alien referee personas, the society and tech levels are on one table.
The referee generates a society level and then generates the tech level in a second roll.
There is a much higher chance of an alien having a vocation and having tech level creator.

The society levels are cumulative.
If the alien has Education, she automatically has Culture and Language.
For a refresher on the implications of alien society jump to xref:aliens:society.adoc[Alien Society,window=_blank].

include::referee_personas:partial$society_and_tool_usage.adoc[]

=== Language
Aliens with language can communicate amongst themselves and with expedition members. 
This language has no impact on tool usage.
An alien with the ability to communicate may still lack any concept of using a tool.
If the referee wishes, she can burden the alien with a religious belief.

==== No Language
Aliens with no language are the flora and fauna of the world. 
The abilities, size and life-span of the alien determine where they fit in on the food chain.
Aliens can always communicate amongst themselves.
The lack of language prevents higher-level organization or communications across the species.
If an alien with no language is a canonical referee persona, she will have some way to communicate with her expedition members.

==== Religious Belief
Aliens with language may have religious beliefs.
The list here describes the structure of the religious belief. 
The referee and her milieu determine the nomenclature, structure, hypocrisy, and corruption of the political system.
This belief applies explicitly to the alien referee persona.
The referee may wish to roll different beliefs for the entire species.

include::referee_personas:partial$beliefs_religion.adoc[]

=== Culture
Culture allows the aliens to organize their species with a common culture.
Aliens with culture also have language. 
Culture and language have no impact on tool usage.
An alien with the ability to communicate may still lack any concept of using a tool.
If the referee wishes, she can burden the alien with a political belief.

==== Political Belief
The list here describes the structure of the political belief. 
The referee and her milieu determine the nomenclature, structure, hypocrisy, and corruption of the political system.
This belief applies explicitly to the alien referee persona.
The referee may wish to roll different beliefs for the entire species.

include::referee_personas:partial$beliefs_politics.adoc[]

=== Education
An alien with education will also have culture and language.
Education indicates that the species can train its members and pass on information from one generation to the next.
Education does not indicate anthro-like vocations. 
While tool use is nearly guaranteed, an alien species with education may still eschew all technology.
If the referee wishes, she can burden the alien with a philosophical belief.

==== Philosophical Belief
Some are real.
Some are silly.
All are mental exercises in futility. 
This belief applies explicitly to the alien referee persona.
The referee may wish to roll different beliefs for the entire species.

include::referee_personas:partial$beliefs_philosophical.adoc[]

=== Vocation
Aliens with vocations represent the highest level of societal development.
Aliens with vocation have education, culture, and language as well.
This alien species will certainly embrace technology, but there is no guarantee that they have unleashed their full technological creativity.
Only tool usage decides if the species has reached the coveted creator level.

==== Vocation
Aliens at the societal level of vocation roll a vocation type.
This vocation type is for the specific alien referee persona, and the species will have all vocations. 

If the referee persona is an alien knite, her Mind jumps to 18.
Other than the Mind limitation, no other attribute limitations or adjustments apply.

include::referee_personas:partial$vocation_determination.adoc[]

== Tool Usage
Alien tool usage is absolute. 
For a refresher on the implications of alien tool usage to xref:aliens:society.adoc[Alien Society,window=_blank].

include::aliens:partial$tool_use_categories.adoc[]

=== None
The alien species has no concept of a tool. 
They would never consider an artifact as anything other than a rock or branch to step over.
This tool ignorance transcends language, culture, and education.
This alien can only solve a problem using its body parts.
This alien only drinks water. 
She would never collect water.

=== Simple 
Simple tool usage is limited to non-powered tools that require constant physical effort.
These tools depend on the environment of the alien's biome.
If the alien species has *no language*, the tools are limited to the temporary use of sticks or rocks. 
If the alien species has *language*, they can have re-usable tools and employ wind, water and gravity to their advantage.

This alien does not use mundane equipment or artifacts at all.
This alien would only ever use her natural attacks in combat.
This alien may use a rock to smash something.
This alien could use a stick to reach something.

=== Tech
This alien species utilizes any device that reduces their physical workload. 
These devices can use electricity, steam, and springs.
They have complicated clockwork machines but *no computational devices.* 

The alien can use all xref:hardware:mundane_equipment.adoc[Mundane Equipment].
This alien may have survival equipment for their terrain.
This alien may have an artifact but lacks knowledge of how it works.
High-tech artifacts may be mistaken for magic.
A tech tool using alien RP gets *one roll* on the Limited TOY Table below.
The tech level of the toy rolled cannot exceed TL 10.

=== Computer
This alien species can use electronic devices that can replace all physical work.
These devices include computers, telecommunications, and encryption.
There may be rudimentary robots and faux autonomous Intelligence.
The comp level tool user does not have access to physics-defying technologies.
As a species, homo sapiens of mundane terra are at this level.

This alien can use all mundane tools, but she will prefer to use toys.
A comp tool user gets one roll per two EXPS levels on the Limited TOY Table below. 
The tech level of the toy rolled cannot exceed TL 10.

=== Creator
There is no limit to what creators can make and create.
Creator alien species have space travel, special drives, autonomous Intelligence, robots, and more.
Creativity is their only limit. 
An alien species can reach creator-level tool use without evolving vocations.

This alien has an intimate relationship with and understanding of technological devices.
This alien can combine toys for synergistic effects.
Creators get one roll on the regular TOYS table per EXPS Level.
Treasure and Junque do not count as a TOYS roll for creators. 
Creator aliens can amass great wealth as well as deadly weapons.

== Startifacts
Alien RPs get startifacts like any other persona. 
RPs are typically awarded one roll per EXPS Level. 
High level RPs can be very dangerous by way of their TOYs alone.
For Startifacts jump to xref:hardware:startifacts.adoc[Startifacts,window=_blank]

== Name
The alien should have a name as any other player persona does.
The referee may have to name both a referee persona and an alien species. 
For alien, naming shenanigans jump to xref:aliens:name.adoc[Alien Name,window=_blank].

== Story Cues
There are all manner of story cues that the referee may wish to generate.
All are optional. 
For setting up story cues for this referee persona jump to xref:referee_personas:rp_story_cues.adoc[Story Cues,window=_blank].

== Combat Ratio
The combat ratio determines how dangerous a referee persona is.
Combat ratio is partially optional, but plays a roll in assigning combat experience. 
To generate a danger number for this persona jump to xref:referee_personas:rp_combat_ratio.adoc[Combat Ratio,,window=_blank].

