= Alien RP

Aliens are organic lifeforms.
In the faux taxonomy, aliens are of the family Diversidae.
The evolution of an alien is random and can lead to any shape, size, or colour.
This randomness makes aliens genuinely diverse, and hence the family name.
Each RP alien is unique unto itself; however, it is a member of a species.

The referee may visit this section to evolve some flora and fauna for her milieu and end up with a previously unknown space-faring species.
The referee should massage the alien RP to fit her milieu.
The Alien RP section is for helping creativity, not replacing it.

.*Alien RP Evolution Checklist*
. <<_alien_rp_relevance,Relevance>>
. <<_alien_rp_attributes,Attributes>>
. <<_alien_rp_size,Size>>
. <<_alien_rp_hit_points,Hit Points>>
. <<_alien_rp_attack_frequency,Attack Frequency>>
. <<_alien_rp_damage_per_attack,Damage per Attack>>
. <<_alien_attack_type,Attack Type>>

. <<_alien_rp_defence_rating,Defence Rating>>
. <<_alien_rp_wate_allowance,Wate Allowance>>
. <<_alien_rp_shape,Shape>>
. <<_alien_rp_movement_rate,Move>>
. <<_alien_rp_mutations,Mutations>>
. <<_alien_rp_age,Age>>
. <<_alien_rp_exps_level,EXPS Level>>
. <<_alien_rp_society,Society>>
. <<_alien_rp_tool_usage,Tool Usage>>
. <<_alien_rp_combat_table,Attack Table>>
. <<_alien_rp_biology,Biology>>
. <<_alien_rp_combat_ratio,Combat Ratio>>


. <<_alien_rp_modifications,Modifications>>
. <<_alien_rp_name,Name>>
. Have Fun!

== Alien RP Relevance
Not all RPs are created equal.
Some personas are less important than others.
The referee usually knows the importance of the persona before she starts generation.
An RP's relevance increases the more entangled they are with the expedition.

include::referee_personas:partial$persona_relevance.adoc[]

=== Cannon Fodder
Cannon fodder are like movie extras that fill in the background.
Alien cannon fodder are the harmless flora and fauna of a forest.
Alien cannon fodder are also the sidewalk civilians of an advanced society.
Alien sidewalk civilians fill the streets of a city, village, or spacecraft.

.*Cannon Fodder* 
. offer no opposition
. have no useful information
. have no nutritional value, monetary value or useful parts.

Unlike anthro cannon fodder, the referee cannot generate alien cannon fodder on the fly.
An alien has too many parts, literally, for the referee to create them on the fly.

It is possible to create new cannon fodder members from an existing alien species.
If the expedition is tearing things up in an alien city, there will be the equivalent of sidewalk civilians.
The generic attribute for alien sidewalk civilians depends on the size of the alien. 

include::ROOT:partial$CH11_Table_Alien_RP_Cannon.adoc[]

Cannon fodder does not mean expendable without consequence.
Hunting flora and fauna may be against the law.
Alien societies may have laws protecting their defenceless comrades.

=== Canon Fodder
Canon fodder may have bit parts in the story but does not make the story. 
Alien canon fodder are usually dangerous flora or fauna or adversarial alien combatants.

.*Canon Fodder* 
. could act in opposition to the expedition's goals
. could injure or kill a player persona
. could accidentally alter the story of a campaign
. could have nutritional, financial or information value

The referee usually predetermines the goal of canon fodder.
The referee creates as much information as needed.
The alien could be an indigenous predator that eats anthros.
The alien could be a one-off monster in some post-apocalyptic wasteland.

Canon fodder can be extremely dangerous to the expedition.
They are there to get in the way of the player's goals. 
The referee should complete a persona record sheet for alien canon fodder. 
There are too many moving parts with alien RPs to make them on the fly.

=== Canonical Persona
Canonical personas are like supporting actors that make the story possible.
These referee personas are integral participants in the campaign story.
They can be powerful recurring enemies or comrades in arms.
Canonical referee personas are the real deal.
These referee personas utilize every step of persona creation.
They have all the dressings of a player persona.
Only the player personas are more important to the story.

Canonical referee persona aliens usually require background on their species as well as the specific persona.
In the case of recurring flora and fauna, the species background can be brief.
In the case of a tool using creator society, the species background represents serious work. 

=== Species vs Solitary
The alien created is usually a member of a species. 
The species could be mundane flora and fauna, an invading alien horde, or a solo first encounter.
The species may define everything about the referee persona. 
Every member of the species may all have the same size, shape, belief and personality.
A homogeneous alien species is undoubtedly the easiest pathway for the referee.
How the referee persona fits into this depends on her campaign milieu and back story.

An alien referee persona need not be part of an entire species. 
There are many story-based explanations of solitary aliens.
The alien may be the sole member of an alien species so distant they will never be part of the story.
The alien may be the sole survivor of a species that suffered some cataclysm.
The alien may have been grown in a mad biologist's vat for nefarious purposes.

== Alien RP Record Sheet
The referee persona record sheet is just another persona record sheet.
There are few bonus elements of which the referee must keep track.
Most player personas do not have elements like personality, politics or religion.
The referee can also use the persona record sheet to keep track of interactions with the expedition.
Alien RPs have a lot of essential data, and a complete persona record is best.

NOTE: *If it's worth playing, it's worth writing down.*

== Alien RP Attributes
Alien RP attributes have the same ranges as player persona alien attributes. 
If the referee is looking for a particular configuration of attributes, she can change them in the <<_alien_rp_modifications,Modifications>> section.

include::aliens:partial$attributes_generation_list.adoc[]

== Alien RP Size
The size of the alien RP affects its appearance, wate and hits points.
Alien RPs can have extremely small or large sizes that are not available to player personas.
These extreme sizes are called Minute and Humongous.

include::aliens:partial$size_category_list.adoc[]

=== Extremely Tiny 
Any Tiny alien has a 1 in 6 chance to be *Minute* instead.
Minute aliens have a WATE of  0 to 999 grams (1d1000-1).
A Minute alien will never have a WATE greater than a kilogram.
Being Minute decreases the alien's STR and HPS but does not affect other attributes. 

==== Minute Alien HPS and STR adjustment
.HPS = (rolled HPS) * (wate/1000)
.STR = (rolled STR) * (wate/1000)
****
An alien with 50 HPS, 12 STR, and 500 gm Wate would have 25 HPS and 6 STR. +
The minimum STR and HPS of a Minute alien are 1.
****

=== Extremely Gigantic
Any Gigantic alien has a 1 in 6 chance to be *Humongous* instead.
Humongous aliens have a WATE of 6 to 300 tons (1d50 times 6).
Being a humongous alien is just an inconvenience as they have no alteration in their attributes or hit points.

== Alien RP Hit Points
Bigger aliens tend to have more hit points than smaller aliens.
Minute aliens must apply their size modification to the hit points generated here.

include::aliens:partial$hit_points_and_size.adoc[]

// check why 2 tables? I can't see or even find two tables.

== Alien RP Attack Frequency
The number of attacks indicates the number of attack rolls the referee makes each unit.
This attack frequency is only for the alien's naturally evolved attacks and does not apply to equipment weapons.

include::aliens:partial$attack_frequency_amounts.adoc[]

== Alien RP Damage per Attack
Bigger aliens tend to inflict more damage than smaller aliens.
Minute aliens must apply their STR modification before determining their damage per attack.
The damage per attack is only for the alien's naturally evolved attacks and does not apply to equipment weapons.

include::aliens:partial$attack_damage_and_size.adoc[]

== Alien Attack Type
The vast majority of aliens will bite, slap, punch and kick their way through combat.
Other attack types exist.
For simplicity, the attack type will apply to all of the alien's attacks. 
The referee can make multiple rolls on this table to give her RP alien with multiple attacks different kinds of attacks. 
For instance, an alien with three attacks per unit could have three Strike attacks or two Strike attacks and one Fling attack.

include::aliens:partial$attack_type_options.adoc[]

== Alien RP Defence Rating
How hard is it to damage this alien in combat?

include::aliens:defence_rating.adoc[tag=Alien_AR]

== Alien RP Wate Allowance
The wate allowance is the same for all personas. 
The WA indicates how much the alien can carry without being encumbered.

include::anthros:partial$wate_allowance_and_strength.adoc[]

== Alien RP Shape
The alien shape is entirely random and makes for very diverse corporeal denizens.
For more details about alien shape, jump to Detailed explanation exist at xref:aliens:alien_shape.adoc[Alien Shape,window=_blank].

The referee makes four rolls on the Alien Body Parts Table.
One roll for each of the four body parts that compose the alien. 
Each body part has a terrain type associated with it.
The terrain type is in brackets and looks like (l, a, w, s).
It is crucial to record the terrain type along with the shape of the body part.

.Roll once for each body part.
. Head
. Torso
. Arms
. Legs

include::aliens:partial$alien_shape_body_parts.adoc[]

=== Adornments
These are optional accents to the alien's appearance.
Adornments are entirely descriptive.
Adornments do not detract from or add any abilities to the alien. 

// head adornment
include::aliens:partial$alien_shape_head_adornment.adoc[]

// torso adornment
include::aliens:partial$alien_shape_torso_adornment.adoc[]

// arms adornment
include::aliens:partial$alien_shape_arm_adornment.adoc[]

== Coat and Colour
The referee can leave the alien as a patchwork of different skin types or choose a particular coat from one body part.
The colour can be as complicated or as simple as desired. 
The referee can massage the alien colour to match the terrain or reflect its abilities.
The referee can generate a random colour from the Giant Colour Table. 
include::ROOT:partial$add_colour_to_your_world.adoc[]

== Alien RP Movement Rate
Alien movement rate is as important as size in regards to combat.
The shape of the alien determines whether it hops, slithers, flaps, or gallops along.
More detail is available at xref:aliens:movement.adoc[Alien Movement,window=_blank]

== Movement Unit
.move (h/u) = DEX / 4
****
An alien with a 12 DEX would have a base movement unit of 3 h/u. 
****
Add the terrain types (l, a, w) for each body part shape and multiply them by the movement unit.

include::aliens:partial$movement_calculation.adoc[]

== Alien RP Mutations
include::aliens:page$evolutations.adoc[tag=alien_mutations]

== Alien RP Age
Life expectancy is defining feature of organic life forms. 

include::aliens:partial$life_spans.adoc[]

=== Extremely Short Life Spans 
If the alien's life span is less than ten years, there is a 1 in 6 (1d6) chance that the alien will have an extremely short life span.
Extremely short life spans should influence the alien RP's biology and society.
Short-lived species often depend on large numbers of offspring requiring minimal energy exertion.
This biological process is called progeny over prodigy.

include::ROOT:partial$CH11_Table_Alien_RP_Age_Short_Lifespan.adoc[]

=== Extremely Long Life Spans
If the alien's life span is more than 10000 years, there is a 1 in 6 (1d6) chance that the alien will have an extremely long life span.
Extremely long life spans should influence the alien RP's biology and society.
Long-lived species often devote increased energy to fewer, more advanced offspring.
This biological process is called prodigy over progeny.

==== Extremely Long Life Spans
.100000 - 100000000 (100000 * 1d1000) years 
****
500 on the 1d1000 yields a life span of 50 million years.
****

include::ROOT:partial$CH11_Table_Alien_RP_Life_Stage.adoc[]

include::aliens:partial$life_span_stages.adoc[]

== Alien RP EXPS Level
Good for flora, fauna, and vocations.
An alien predator with a high experience level will be more dangerous than a low-level predator of the same species.

include::referee_personas:partial$experience_levels.adoc[]

== Alien RP Society
Alien society is something for the referee to consider and prepare for her campaign carefully.
A single alien society can be the basis for an entire campaign.
The process for determining an alien player persona's society is complex and time-consuming.

For alien referee personas, the society and tech levels are on one table.
The referee generates a society level and then generates the tech level in a second roll.
There is a much higher chance of an alien having a vocation and having tech level creator.

The society levels are cumulative.
If the alien has Education, she automatically has Culture and Language.
For a refresher on the implications of alien society jump to xref:aliens:society.adoc[Alien Society,window=_blank].

include::ROOT:partial$CH11_Table_RP_Alien_Society.adoc[]

=== No Language
Aliens with no language are the flora and fauna of the world. 
The abilities, size and life-span of the alien determine where they fit in on the food chain.
Aliens can always communicate amongst themselves.
The lack of language prevents higher-level organization or communications across the species.
If an alien with no language is a canonical referee persona, she will have some way to communicate with her expedition members.

=== Language
Aliens with language can communicate amongst themselves and with expedition members. 
This language has no impact on tool usage.
An alien with the ability to communicate may still lack any concept of using a tool.
If the referee wishes, she can burden the alien with a religious belief.

==== Religious Belief
The list here describes the structure of the religious belief. 
The referee and her milieu determine the nomenclature, structure, hypocrisy, and corruption of the political system.
This belief applies explicitly to the alien referee persona.
The referee may wish to roll different beliefs for the entire species.

include::ROOT:partial$CH11_Table_Referee_Persona_Religious_Belief.adoc[]

=== Culture
Culture allows the aliens to organize their species with a common culture.
Aliens with culture also have language. 
Culture and language have no impact on tool usage.
An alien with the ability to communicate may still lack any concept of using a tool.
If the referee wishes, she can burden the alien with a political belief.

==== Political Belief
The list here describes the structure of the political belief. 
The referee and her milieu determine the nomenclature, structure, hypocrisy, and corruption of the political system.
This belief applies explicitly to the alien referee persona.
The referee may wish to roll different beliefs for the entire species.

include::ROOT:partial$CH11_Table_Referee_Persona_Political_Belief.adoc[]

=== Education
An alien with education will also have culture and language.
Education indicates that the species can train its members and pass on information from one generation to the next.
Education does not indicate anthro-like vocations. 
While tool use is nearly guaranteed, an alien species with education may still eschew all technology.
If the referee wishes, she can burden the alien with a philosophical belief.

==== Philosophical Belief
Some are real.
Some are silly.
All are mental exercises in futility. 
This belief applies explicitly to the alien referee persona.
The referee may wish to roll different beliefs for the entire species.

include::ROOT:partial$CH11_Table_Referee_Persona_Philosophical_Belief.adoc[]

=== Vocation
Aliens with vocations represent the highest level of societal development.
Aliens with vocation have education, culture, and language as well.
This alien species will certainly embrace technology, but there is no guarantee that they have unleashed their full technological creativity.
Only tool usage decides if the species has reached the coveted creator level.

==== Alien RP Vocation
Aliens at the societal level of vocation roll a vocation type.
This vocation type is for the specific alien referee persona, and the species will have all vocations. 

If the referee persona is an alien knite, her Mind jumps to 18.
Other than the Mind limitation, no other attribute limitations or adjustments apply.

include::referee_personas:partial$vocation_determination.adoc[]

== Alien RP Tool Usage
Alien tool usage is absolute. 
For a refresher on the implications of alien society jump to xref:aliens:society.adoc[Alien Society,window=_blank].

include::aliens:partial$tool_use_categories.adoc[]

=== None Tool User
The alien species has no concept of a tool. 
They would never consider an artifact as anything other than a rock or branch to step over.
This tool ignorance transcends language, culture, and education.
This alien can only solve a problem using its body parts.
This alien only drinks water. 
She would never collect water.

=== Simple Tool User
Simple tool usage is limited to non-powered tools that require constant physical effort.
These tools depend on the environment of the alien's biome.
If the alien species has *no language*, the tools are limited to the temporary use of sticks or rocks. 
If the alien species has *language*, they can have re-usable tools and employ wind, water and gravity to their advantage.

This alien does not use mundane equipment or artifacts at all.
This alien would only ever use her natural attacks in combat.
This alien may use a rock to smash something.
This alien could use a stick to reach something.

=== Tech Tool User
This alien species utilizes any device that reduces their physical workload. 
These devices can use electricity, steam, and springs.
They have complicated clockwork machines but *no computational devices.* 

The alien can use all xref:hardware:mundane_equipment.adoc[Mundane Equipment].
This alien may have survival equipment for their terrain.
This alien may have an artifact but lacks knowledge of how it works.
High-tech artifacts may be mistaken for magic.
A tech tool using alien RP gets *one roll* on the Limited TOY Table below.
The tech level of the toy rolled cannot exceed TL 10.

=== Comp Tool User
This alien species can use electronic devices that can replace all physical work.
These devices include computers, telecommunications, and encryption.
There may be rudimentary robots and faux autonomous Intelligence.
The comp level tool user does not have access to physics-defying technologies.
As a species, homo sapiens of mundane terra are at this level.

This alien can use all mundane tools, but she will prefer to use toys.
A comp tool user gets one roll per two EXPS levels on the Limited TOY Table below. 
The tech level of the toy rolled cannot exceed TL 10.

include::ROOT:partial$CH41_Table_TOY_System_Limited.adoc[]

=== Creator
There is no limit to what creators can make and create.
Creator alien species have space travel, special drives, autonomous Intelligence, robots, and more.
Creativity is their only limit. 
An alien species can reach creator-level tool use without evolving vocations.

This alien has an intimate relationship with and understanding of technological devices.
This alien can combine toys for synergistic effects.
Creators get one roll on the regular TOYS table per EXPS Level.
Treasure and Random Junque do not count as a TOYS roll for creators. 
Creator aliens can amass great wealth as well as deadly weapons.

include::hardware:partial$toys_categories.adoc[]

== Alien RP Attack Table
The attack table keeps track of the persona's combat skills and increases with EXPS level.
The referee may need two attack tables for her tool using aliens.
For general info about attack tables, jump to xref:combat:attack_table_details.adoc[Attack Tables,window=_blank] in tactical combat.
For a detailed explanation of the outline below jump to xref:aliens:attack_table.adoc[Alien Attack Table,window=_blank].

=== Naturally Evolved Attacks
The attack table calculated here is for the alien's naturally evolved attacks and is *not* used for any tool using attacks.
The referee must generate an anthro-based vocation attack table for tool users.
For the vocation based attack table, jump to xref:anthros:attack_table[Anthro attack table,window=_blank].

=== Alien Attack Table Example
A second-level gigantic alien has a 22 STR, 15 DEX, and a 3 INT.
Her attack is spitting sharp blobs of resin which is Attack Fling.

include::aliens:partial$alien_attack_table_example.adoc[]

== Alien RP Biology
Alien biology assigns terrain, eating habits, reproduction etc.
The referee should always massage the alien biology to work best within her campaign milieu.
Many alien species will have evolved beyond the most primal aspects of their biology.
It would be unlikely for a creator tool user to still ambush prey in the desert, but their restaurants may reflect this biological history.

.*Alien Biology Checklist*
. <<_biome,Biome>>
. <<_energy_source,Energy Source>>
.. <<_energy_procurement,Procurement>>
. <<_reproduction,Reproduction>>
. <<_dwelling,Dwelling>>
. <<_grouping,Grouping>>

=== Biome
The biome is an alien's naturally evolved terrain type.
Flora and fauna would not venture beyond their terrain type.
More advanced alien species are not limited to their biome.

include::aliens:partial$biome_list.adoc[]

=== Energy Source
Nom noms.

include::aliens:partial$energy_sources.adoc[]

==== Energy Procurement
How does the alien get its nom noms?

include::aliens:partial$energy_procurement.adoc[]

=== Reproduction
Where do little aliens come from?

include::aliens:partial$reproduction_method_list.adoc[]

=== Dwelling
Typical living space.
Tool usage may allow the alien species to live in architecture informed by this biological history.

include::aliens:partial$habitation_list.adoc[]

=== Grouping
Do they hang out in groups or solo?
include::aliens:partial$grouping_types.adoc[]



=== Aroma
What a wonderful smell you have discovered.

include::aliens:partial$aroma_list.adoc[]

== Alien RP Modifications
Often a referee will want a tiny alien, a dumb alien, a slow alien, or even a stupid, slow, small alien (prey).
Alien attributes tend to be higher than other personas. 
Descriptors such as tough, smart and strong give attribute values relative to anthro personas.
This table may fall short if the referee is trying to generate an alien persona stronger than other aliens in her species.
The downwards attribute modifications are most helpful.

include::referee_personas:partial$strong_descriptors.adoc[]

== Alien RP Name
The alien should have a name as any other player persona does.
The referee may have to name both a referee persona and an alien species. 
For alien, naming shenanigans jump to xref:aliens:moniker.adoc[Alien Name,window=_blank].