= Anthro Referee Personas

Anthros are upright, bipedal humanoids.
In the faux taxonomy, anthros are of the family Hominidae and the genus homo.
Referees are most familiar with playing this kind of referee persona.
They have hands, heads and faces.
The referee should massage the anthro RP to fit her milieu.
This section is for helping creativity, not replacing it.

== Record Sheet
You will not be able to keep track of everything that is needed for a referee persona.
It is recommended that you print out a persona record sheet to keep track of stuff.
Download the bare bones PDF (75K) at xref:appendices:printables.adoc[Anthro Persona Record, window=_blank]

NOTE: *If it's worth creating, it's worth writing down.*

The referee persona record sheet is just another persona record sheet.
There are few bonus elements of which the referee must keep track.
Most player personas do not have elements like personality, politics or religion.
The referee can also use the persona record sheet to keep track of interactions with the expedition.

== Relevance
Not all RPs are created equal.
Some personas are less important than others.
The referee usually knows the importance of the persona before she starts generation.
An RP's relevance increases the more entangled they are with the expedition.

include::referee_personas:partial$persona_relevance.adoc[]

:art: aquarium_not_aquarian.png
:width: 250px
:snark: An aquarium not an aquarian
:artist: Imagestoks 
:date: 2017
:license: Copyright Imagestoks 2015
:description: A space suit with fish swimming in the helmet.
include::ROOT:partial$articulate.adoc[]

== Genus
The anthro genus should reflect the referee's milieu.

include::referee_personas:partial$anthro_genus_determination.adoc[]

=== Species
The anthro species should reflect the referee's milieu.
The most common species is generalis.
Generalis is the typical non-descript anthro species.
On mundane terra a canine generalis is called a __mutt__.

include:referee_personas:partial$anthro_species_determination.adoc[]

Anthro species are phenotypical, not scientific.
Anthros are appearance only and are unfaithful to mundane terran science.

.*Mundane terran examples*
* https://en.wikipedia.org/wiki/List_of_fish_common_names[Aquarian]
* https://en.wikipedia.org/wiki/List_of_dog_breeds[Canine]
* https://en.wikipedia.org/wiki/List_of_horse_breeds[Equine]
* https://en.wikipedia.org/wiki/Ungulate[Equine, even more]
* https://en.wikipedia.org/wiki/Felidae[Feline]
* https://en.wikipedia.org/wiki/Reptile[Reptilian]
* https://en.wikipedia.org/wiki/Rodent[Rodentia]
* https://en.wikipedia.org/wiki/Bear[Ursidae]

== Size
Use this single look-up table to create the anthro's hite and wate. 
All anthros are considered to have the size category of Medium. 
For a refresher on calculating hite and wate jump to xref:anthros:anthro_size.adoc[Anthro Size,window=_blank].
To choose specific sizes like obese, skinny tall or short, jump to <<_strong_descriptors,Strong Descriptors>>.

include::referee_personas:partial$anthro_size_quick_table.adoc[]

== Age
First generate the age category of the referee persona and then hone in on an exact age in years.

include::referee_personas:partial$age_categories.adoc[]

include::referee_personas:partial$anthro_years_old.adoc[]

== Attributes
Referee persona attributes are slightly better than player persona attributes and do not affect the persona's genus or vocation.
The referee generates initial attributes for the referee persona using the attributes table below.
The attributes are then modified to reflect the anthro genus and vocation.
To choose descriptive attributes like slow, weak, or dumb jump to <<_strong_descriptors,Strong Descriptors>>.

include::anthros:partial$anthro_attribute_generation.adoc[]

=== 4d6DL
For attributes with ranges of 3-18 can replace the 3d6 roll with a 4d6DL roll.
With 4d6DL the player rolls 4d6 and drops the lowest die roll. 
If a player rolls 4, 3, 5, and 2, she drops the 2, and her total is 12. 
The impact on the nature of the game using drop the lowest is astounding. 
Using 4d6DL allows for powerful vocations like spies and knites to be more frequent.

=== Hit Points
A referee persona's Hit Points (HPS) maximum is determined the same as any other anthro persona.
For more information about anthro hit points jump xref:anthros:generate_hit_points.adoc[here,window=_blank].

==== Calculation
.HPS = (1/2 CON x 1d8) + CON
****
A persona with a CON of 11 would roll 6d8 and add 11. Rounding benefits the persona.
****

=== Genus Adjustment
For player personas the attributes determine the choice of anthro genus.
For referee personas the anthro genus alters the attributes
Attributes are never corrected down. 
If the referee needs a clumsy feline, she can achieve this using the <<_strong_descriptors,Strong Descriptors>>.

include::referee_personas:partial$anthro_genus_attribute_correction.adoc[]

== Mutations
Referee personas mutate the same as other personas. 
The referee can push for mutations by doubling the chance.
The table is be used as a guide if mutations are to be assigned.
Purestrain anthros are not vessels for zany mutations.
Insectoids rarely get phenomic mutations.
Keep in mind that some mutations are campaign changers and should be appropriately rare.

include::anthros:partial$anthro_mutation_chance.adoc[]

== Anthro RP EXPS Level
Generate an experience level for every anthro RP.
Anthros have vocations, and the EXPS level can be their most important roll.
EXPS level impacts how many artifacts and skills the RP gets.

include::referee_personas:partial$experience_levels.adoc[]

== Anthro RP Vocation
All anthros get a vocation. 
The referee should choose the vocation that best suits the needs of the story and milieu.

include::referee_personas:partial$vocation_determination.adoc[]

=== Attribute Correction
RP attributes do not select the persona's vocation type.
The attributes are modified to reflect the vocation type.
Attributes are never corrected down. 
However, if the referee needs a clumsy spie, she can achieve this at <<_strong_descriptors,Strong Descriptors>>

include::referee_personas:partial$vocation_attribute_correction.adoc[]

== Strong Descriptors
The following table gives guidelines for numerical changes that various descriptors represent.
This table can be used to spice up an entirely random referee persona. 
Not everyone is great. 
It largely lives at the end of this section for ease of calculations. 
Strong descriptors can lead to anomalies like weak mercenaries, or clumsy spies. 

include::referee_personas:partial$strong_descriptors.adoc[]

== Movement Rate
Movement rate is dependent on DEX and represented in hexes per unit.
If the referee needs a slow or fast RP, this is modified at <<_strong_descriptors,Strong Descriptors>>

include::anthros:partial$movement_rate_and_dexterity.adoc[]

== Defence Rating
Defence Rating is adjusted using DEX.
// this in include from Anthro AR
include::anthros:defence_rating.adoc[lines=3..20]


== Wate Allowance
The better the STR, the more she can lift.

include::anthros:partial$wate_allowance_and_strength.adoc[]

== Equipment
Referee personas carry equipment.
They have food, survival equipment, funds, and toys.
RPs get one TOYs roll for every experience level.

=== Mundane
Referee personas usually have what is necessary to survive in the local terrain.
The persona's survival equipment will vary with the terrain and the referee's milieu.

xref:hardware:mundane_equipment.adoc[Mundane Equipment]

=== TOYs
Toys are technological devices that behave like magical devices.
If a referee persona needs a particular technological device, the referee will add it to the persona.
The referee may limit  RP equipment to maintain game balance.

Higher-level RPs will have successfully identified most of their toys.
An RP may also have an unidentified technological toy.
An unidentified toy is an artifact.
A lower-level RP is more likely to be carrying around an artifact.

.*Referee Persona TOYs*
* one roll on TOY table per EXPS Level
* vocation limits do not apply
* spacecraft, robot or vehicle limits do not apply
* treasure is accumulated but does not count as roll

include::hardware:partial$toys_departments_list.adoc[]

== Attack Table
The attack table keeps track of the persona's combat skills and increases with EXPS level.
The referee need not calculate a complete attack table for cannon, or canon, fodder referee personas.
Canonical referee personas need a full attack table calculated.
For general info about attack tables, jump to xref:combat:attack_table_details.adoc[Attack Tables,window=_blank] in tactical combat.
For detailed info about the calculations below, jump to xref:anthros:attack_table[Anthro attack table,window=_blank].

A second level spie has the following attributes: AWE 12 CHA 11 CON 12 DEX 10 INT 12 MND 14 and STR 16.

include::anthros:partial$attack_table_anthro_example.adoc[]

== Startifacts
Anthro RPs get startifacts like any other persona. 
RPs are typically awarded one roll per EXPS Level. 
High level RPs can be very dangerous by way of their TOYs alone.
For Startifacts jump to xref:hardware:startifacts.adoc[Startifacts,window=_blank]

== Name
The anthro should have a name as any anthro player persona does.
For anthro, naming shenanigans jump to xref:anthros:name.adoc[Anthro Name,window=_blank].

== Story Cues
There are all manner of story cues that the referee may wish to generate.
All are optional. 
For setting up story cues for this referee persona jump to xref:referee_personas:rp_story_cues.adoc[Story Cues,window=_blank].

== Combat Ratio
The combat ratio determines how dangerous a referee persona is.
Combat ratio is partially optional, but plays a roll in assigning combat experience. 
To generate a danger number for this persona jump to xref:referee_personas:rp_combat_ratio.adoc[Combat Ratio,,window=_blank].

