= Anthro Referee Personas

Anthros are upright, bipedal humanoids.
In the fake taxonomy, anthros are of the family Hominidae and the genus homo.
Referees are most familiar with playing this type of referee persona.
They have hands, heads and faces.
The referee should massage the anthro RP to fit her milieu.
This section is for helping creativity, not replacing it.

.*Anthro RP Delivery Checklist*
\. <<_anthro_rp_roll_playing,Roll Playing>>
. <<_anthro_rp_relevance,Relevance>>
. <<_anthro_rp_record_sheet,Persona Record Sheet>>
. <<_anthro_rp_type,Anthro Type>>
. <<_anthro_rp_size,Size>>
. <<_anthro_rp_age,Age>>
. <<_anthro_rp_attributes,Attributes>>
. <<_anthro_rp_movement_rate,Move>>
. <<_anthro_rp_defence_rating,Defence Rating>>
. <<_anthro_rp_wate_allowance,Wate Allowance>>
. <<_anthro_rp_mutations,Mutations>>
. <<_anthro_rp_exps_level,EXPS Level>>
. <<_anthro_rp_vocation,Vocation>>
. <<_anthro_rp_equipment,Equipment>>
. <<_anthro_rp_combat_table,Attack Table>>
. <<_anthro_rp_combat_ratio,Combat Ratio>>
. <<_modifications,Modifications>>
.. attributes
.. size
.. age
. <<_anthro_rp_name,Name>>
. Have Fun!

== Anthro RP Roll Playing
Roll playing is a play on words that honours the dice rolling required to create a  referee persona.
The roll playing here generates the data that a referee needs to play a referee persona.
The referee should massage the roll results to reflect the milieu of her campaign.
There is less massaging to do in this section than the role-playing section.

== Anthro RP Relevance
Not all RPs are created equal.
Some personas are less important than others.
The referee usually knows the importance of the persona before she starts generation.
An RP's relevance increases the more entangled they are with the expedition.

include::ROOT:partial$CH11_Table_RP_Relevance.adoc[]

=== Cannon Fodder
Cannon fodder are the movie extras that fill in the background.
Anthro cannon fodder are called sidewalk civilians.
Sidewalk civilians fill the streets of a city, village, or spacecraft.

[quote]
____
Cannon Fodder are volume discounted anthros used to attack cannons.
____

.*Cannon Fodder* 
. offer no opposition
. have no useful information
. have no nutritional value, monetary value or useful parts.

The referee can create sidewalk civilians on the fly. 
Any numerical value needed is 6.
Anthro cannon fodder have 6 HPS, 6 DEX, and 6 MND.
The anthro type can is nondescript as in a mutt for canines. 
Cannon fodder only transiently exists, and no persona record sheet is needed.
You can stop here if you randomly rolled cannon fodder. 

Cannon fodder does not mean expendable without consequence.
Killing off cannon fodder is against norms and laws in most settings.
Police forces and superheroes spend most of their time protecting cannon fodder.

=== Canon Fodder
Canon fodder may have bit parts in the story, but they do not make the story. 
Anthro canon fodder are minions, soldiers, or security staff.

.*Canon Fodder* 
. could act in opposition to the expedition's goals
. could injure or kill a player persona
. could accidentally alter the story of a campaign
. could have information or treasure

The referee usually predetermines the goal of canon fodder.
The referee creates as much information as needed.
For example, mercenaries defending a lab may only have a pistol and a Skilled and Raw.
Their uniforms may be uniforms, and no further description is needed.
The referee generates other attributes as needed.
The referee may keep their info on a card, and a persona record sheet is not essential.

Canon fodder can be extremely dangerous to the expedition.
They are there to get in the way of the player's goals. 
If there is combat, the canon fodder is ready for action.

=== Canonical Persona
Canonical personas are like supporting actors that make the story possible.
These referee personas are integral participants in the campaign story.
They can be powerful recurring enemies or comrades in arms.
Canonical referee personas are the real deal.
These referee personas utilize every step of persona creation.
They have all attributes, vocations, mutations and goals.
Only the player personas are more important to the story.

== Anthro RP Record Sheet
The referee persona record sheet is just another persona record sheet.
There are few bonus elements of which the referee must keep track.
Most player personas do not have elements like personality, politics or religion.
The referee can also use the persona record sheet to keep track of interactions with the expedition.

NOTE: *If it's worth playing, it's worth writing down.*

:art: aquarium_not_aquarian.png
:width: 250px
:snark: An aquarium not an aquarian
:artist: Imagestoks 
:date: 2017
:license: Copyright Imagestoks 2015
:description: Drawing of a space suit with fish swimming in the helmet.

include::ROOT:partial$articulate.adoc[]

== Modifications
Modifications are descriptors that make changes to the referee personas attributes and size.

include::ROOT:partial$CH11_Table_Anthro_RP_Modifiers.adoc[]


== Anthro RP Type
The anthro RP type should reflect the referee's milieu.
The anthro type table is for inspiration only. 

include::ROOT:partial$CH11_Table_Anthro_RP_Anthro_Type.adoc[]

=== Anthro Subtypes
The anthro subtype should reflect the referee's milieu.
The anthro subtype table is for inspiration only. 

Anthro subtypes are phenotypical, not scientific.
Anthros are appearance only and are faithful to mundane terran science.

Non-descript anthro types are also called mutts. 
A canine mutt is a canine, but no more distinct than that.

include::ROOT:partial$CH11_Table_Anthro_RP_Anthro_Type_Subs.adoc[]

.source links for anthro subtypes
* https://en.wikipedia.org/wiki/List_of_fish_common_names[Aquarian]
* https://en.wikipedia.org/wiki/List_of_dog_breeds[Canine]
* https://en.wikipedia.org/wiki/List_of_horse_breeds[Equine]
* https://en.wikipedia.org/wiki/Ungulate[Equine]
* https://en.wikipedia.org/wiki/Felidae[Feline]
* https://en.wikipedia.org/wiki/Reptile[Reptilian]
* https://en.wikipedia.org/wiki/Rodent[Rodentia]
* https://en.wikipedia.org/wiki/Bear[Ursidae]

=== Anthro RP Size
Use this single look-up table to create the anthro's hite and wate. 
For a refresher on calculating hite and wate jump to xref:anthros:anthro_size.adoc[Anthro Size,window=_blank].
To choose specific sizes like obese, skinny tall or short, jump to <<_modifications,Modifications>>.

include::ROOT:partial$CH11_Table_Anthro_RP_Hite_and_Wate.adoc[]

=== Anthro RP Age
Most often, the lifespan category is enough of a descriptor for the referee persona.
If the story needs an exact age, EXP has a table that has you covered.

include::ROOT:partial$CH11_Table_Anthro_RP_Lifespan_Category.adoc[]

include::ROOT:partial$CH11_Table_Anthro_RP_Age.adoc[]

== Anthro RP Attributes
Referee persona attributes are slightly better than player persona attributes and do not affect the persona's anthro type or vocation.
The referee generates initial attributes for the referee persona using the attributes table below.
The attributes are then modified to reflect the anthro type and vocation.
To choose descriptive attributes like slow, weak, or dumb jump to <<_modifications,Modifications>>.

include::ROOT:partial$CH11_Table_Anthro_RP_Attributes.adoc[]

=== Anthro RP Hit Points
A referee persona's Hit Points (HPS) maximum is determined the same as any other anthro persona.
For more information about anthro hit points jump xref:anthros:generate_hit_points.adoc[here,window=_blank].

=== Anthro Type Attribute Corrections
For RPs, attributes do not select the anthro type.
The attributes are modified to reflect the anthro type.
Attributes are never corrected down. 
However, if the referee needs a clumsy feline, she can achieve this at <<_modifications,Modifications>>

include::ROOT:partial$CH11_Table_Anthro_RP_Attribute_Correction_Type.adoc[]

== Anthro RP Movement Rate
Movement rate is dependent on DEX and represented in hexes per unit.
If the referee needs a slow or fast RP, this is modified at <<_modifications,Modifications>>

include::anthros:partial$movement_rate_and_dexterity.adoc[]

== Anthro RP Defence Rating
Defence Rating is adjusted using DEX.
// this in include from Anthro AR
include::anthros:defence_rating.adoc[lines=3..20]

// todo check this include for defence_rating

== Anthro RP Wate Allowance
The better the STR, the more she can lift.

include::anthros:partial$wate_allowance_and_strength.adoc[]

== Anthro RP Mutations
Referee personas mutate the same as other personas. 
The referee can push for mutations by doubling the chance.
The table should be used as a guide if mutations are to be assigned.
Pure Strains are not vessels for zany mutations.
Insectoids rarely get phenomic mutations.
Keep in mind that some mutations are campaign changers and should be appropriately rare.

include::anthros:partial$anthro_mutation_chance.adoc[]

== Anthro RP EXPS Level
Generate an experience level for every anthro RP.
Anthros have vocations, and the EXPS level can be their most important roll.
EXPS level impacts how many artifacts and skills the RP gets.

include::ROOT:partial$CH11_Table_Referee_Persona_Level.adoc[]

== Anthro RP Vocation
All anthros get a vocation. 
The referee should choose the vocation that best suits the needs of the story and milieu.

include::ROOT:partial$CH11_Table_Referee_Persona_Class.adoc[]

=== Vocation Attribute Correction
RP attributes do not select the persona's vocation type.
The attributes are modified to reflect the vocation type.
Attributes are never corrected down. 
However, if the referee needs a clumsy spie, she can achieve this at <<_modifications,Modifications>>

include::ROOT:partial$CH11_Table_Referee_Persona__Vocation_Supercharge.adoc[]

== Anthro RP Equipment
Referee personas carry equipment.
They have food, survival equipment, funds, and toys.
RPs get one TOYs roll for every experience level.

=== Mundane Equipment
Referee personas usually have what is necessary to survive in the local terrain.
The persona's survival equipment will vary with the terrain and the referee's milieu.

xref:hardware:mundane_equipment.adoc[Mundane Equipment]

=== TOYs
Toys are technological devices that behave like magical devices.
If a referee persona needs a particular technological device, the referee will add it to the persona.
The referee may limit  RP equipment to maintain game balance.

Higher-level RPs will have successfully identified most of their toys.
An RP may also have an unidentified technological toy.
An unidentified toy is an artifact.
A lower-level RP is more likely to be carrying around an artifact.

.*Referee Persona TOYs*
* one roll on TOY table per EXPS Level
* vocation limits do not apply
* space vehicle, robot or vehicle limits do not apply
* treasure is accumulated but does not count as roll

include::hardware:partial$toys_categories.adoc[]

== Anthro RP Attack Table
The attack table keeps track of the persona's combat skills and increases with EXPS level.
The referee need not calculate a complete attack table for cannon fodder or canon fodder referee personas.
Canonical referee personas need a full attack table calculated.
For general info about attack tables, jump to xref:combat:attack_table_details.adoc[Attack Tables,window=_blank] in tactical combat.
For detailed info about the calculations below, jump to xref:anthros:attack_table[Anthro attack table,window=_blank].

A second level spie has the following attributes: AWE 12 CHA 11 CON 12 DEX 10 INT 12 MND 14 and STR 16.

include::anthros:partial$attack_table_anthro_example.adoc[]


== Anthro RP Name
The anthro should have a name as any anthro player persona does.
For anthro, naming shenanigans jump to xref:anthros:moniker.adoc[Anthro Name,window=_blank].

