= Robot RP

Robots are inorganic lifeforms.
In the faux taxonomy, robots are of the family machinidae
Machinidae are life forms that are inorganic and fabricated.
Anthros, Aliens or other Robots can fabricate robots.
The robots here are referee persona robots fabricated by the referee.

== Record Sheet
You will not be able to keep track of everything that is needed for a referee persona.
It is recommended that you print out a persona record sheet to keep track of stuff.
Download the bare bones PDF (75K) at xref:ROOT:attachment$robot_record_v7.pdf[Robot Record v7]

NOTE: *If it's worth creating, it's worth writing down.*

== Relevance
Not all RPs are created equal.
Some personas are less important than others.
The referee usually knows the importance of the persona before she starts generation.
An RP's relevance increases the more entangled they are with the expedition.

include::referee_personas:partial$persona_relevance.adoc[]

== Series
For player personas determining their robot type is a laborious process.
The referee can use the Single Roll Robot Type Table below.
One roll using a 1d1000 chooses the robot RP type.
The referee should massage the robot type to suit her campaign's milieu.

include::robots:partial$series_selection_single_roll.adoc[]

== Fabricator
Where fabricator type does play a role is in delivering orders to the robot. If a fabricator type tells a robot what to do, it is more likely to comply. In short, the robot's fabricator type is more successful at bossing the robot around. If a fabricator type makes a reasonable, on mission command to a robot, it would almost certainly result in a control factor roll.
For more information about the implications of the fabricator type jump to xref:robots:fabricator.adoc[Robot Fabricator,window=_blank].

include::robots:partial$fabricator_type.adoc[]

== Attributes
Inverse to player personas, the RP robot's series and model determines her attributes.
While the table looks imposing, it is much faster than the player personas process.
The attribute lookup table gives the direct attribute scores.
The referee determines the robot's prime attributes after her regular attributes. 

include::referee_personas:partial$robot_attributes_from_series.adoc[]

=== Primes
Some robot abilities depend on the robot's prime attribute. 
For robot RPs the robot type determines the attribute ranges. 
Consult the lookup table below to record the attribute ranges.

include::referee_personas:partial$robot_primes_from_attributes.adoc[]

== Size
The robot size consists of the robot's wate and the robot's hite.
The wate of the robot plays a role in ramming damage. 
Heavier robots inflict more damage.
The hite of the robot determines its rough volume. 
Bigger robots don't fit as well into anthro-sized spaces.

=== Wate

include::referee_personas:partial$robot_wate_by_series.adoc[]

==== Nano Bots
Any robot that has a wate of 4.2 kg or less has a chance of becoming an extremely small nano bot.
The chance of the robot becoming a nano bot is 1 in 6 (1d6)
Nano bots have a wate of  0 to 999 grams (1d1000-1).
A nano bot cannot have a wate greater than a kilogram.
Nano robots have no change to their attributes, abilities or combat values.

==== Mighty Machines
Any robot with a wate of 4200 kg or more has a chance of becoming a mighty machine.
The chance of the robot becoming a mighty machine is 1 in 6 (1d6).
Mighty machines have a wate of 6 to 600 tons (1d100 times 6).
Mighty machines have no change to their attributes, abilities or combat values.
However, in regards to ramming, mighty machines can increase their ramming ratio to 12 (versus 4).

=== Hite
Hite gives an estimation of the volume occupied by the robot.
The referee rolls dimensions once for each of hite, width and length.
A hexagon is 200 cm across. 

include::robots:partial$wate_to_hite_estimation.adoc[]

== Shape
The volume of the robot will fit into this shape.

include::robots:partial$basic_shapes.adoc[]

[discrete]
=== Contortion of Basic Shape
This table manipulates the basic shape of the robot.
This step is optional and is present to help reflect the randomness that is commercial design.

include::robots:partial$basic_shape_distortions.adoc[]

[discrete]
=== Attachments 
Useless attachments.

include::robots:partial$peripherals_of_uselessness.adoc[]

== Defence Rating
Robot RPs have an AR of 700.
A robot AR is the same as any other persona AR.
A successful attack roll damages the robot as it would any other persona.
Robots are different from organic personas and damage differently.
Robot RPs are easy to hit but hard to destroy.

== Movement
The robot's Dexterity score determines her movement rate.
Robots are twice as fast as those other personas with the same DEX.
Those robots which move faster than eight h/u must accelerate the same as vehicles.
Robotic acceleration is one hex per unit per STR prime score.

include::robots:partial$movement_rate_and_dexterity.adoc[]

== Wate Allowance
Bots are affected by encumbrance, though not as much as other referee personas.
Strength determines the weight allowance of the robot.
A robot with a STR level of 3 and a 17 STR would have a wate allowance of 75 kgs.
Robot size does not affect a robot's wate allowance.
For more information about carry stuff, jump to xref:uncombat:encumbrance.adoc[Encumbrance,window=_blank].

include::robots:partial$wate_allowance_and_prime_strength.adoc[]

== Systems
Robotic RPs may have offensive, defensive and peripheral systems.
Generating systems for player persona robots is convoluted and fun.
The referee can find the number of rolls for each system on the single lookup table below.
The lookup table seems scary, but it is scientifically proven to be faster than the player robot persona method.

include::referee_personas:partial$robot_systems_by_series.adoc[]

== Offensive Systems
These are the systems that harm others.
On the lower level tables, the robot is misusing and weaponizing malfunctioning peripherals.
On the higher level tables, the robot is using weapons baked-in during fabrication.
The referee will dance back and forth between the attack tables, creating a murderous melange of machinery.

=== Ramming 
All robots can ram, but not without challenges.
Only robots with ramming freedom can fling themselves around with self-destructive abandon.
For more info about robot ramming, ram your way over to xref:robots:systems_offensive.adoc#_ramming[Robot Ramming,window=_blank].

include::robots:partial$peripherals_offensive_ramming.adoc[]

=== Table One
These attacks include ramming, and the robot is misusing and weaponizing malfunctioning peripherals. 
It is possible to get a roll on Attack Table Two to get more dangerous weapon systems.
For details about these attacks jump to  xref:robots:systems_offensive.adoc#_attack_table_one[Attack Table One,window=_blank].

include::robots:partial$peripherals_offensive_strike.adoc[]

=== Table Two
Slightly more dangerous attacks, but mainly consist of misused devices.
It is possible to get several rolls on Attack Table One or move up to Attack Table Three.
For details about these attacks jump to  xref:robots:systems_offensive.adoc#_attack_table_two[Attack Table Two,window=_blank].

include::robots:partial$peripherals_offensive_2.adoc[]

include::robots:partial$peripherals_offensive_fling.adoc[]

=== Table Three
Even more dangerous attacks.
These attacks are a mix of baked-in weapons and misused devices.
It is possible to get several rolls on Attack Table Two or move up to Attack Table Four.
For details about these attacks jump to  xref:robots:systems_offensive.adoc#_attack_table_three[Attack Table Three,window=_blank].

include::robots:partial$peripherals_offensive_3.adoc[]

=== Table Four
Even more dangerous attacks.
These attacks are a mix of baked-in weapons and misused devices.
It is possible to get several rolls on Attack Table Three.
For details about these attacks jump to  xref:robots:systems_offensive.adoc#_attack_table_four[Attack Table Four,window=_blank].

include::robots:partial$peripherals_offensive_4.adoc[]

== Defensive Systems
Robot defences can arise from misused peripherals or intentionally baked-in defensive systems.
For more detailed explanations jump to xref:robots:systems_defensive.adoc[Defensive Systems,window=_blank].

include::robots:partial$peripherals_defensive.adoc[]

== Peripheral  Systems
Peripherals are attachments that give the robot some additional flexibility in performing its tasks.
Peripherals are not weapons. 
For more detailed explanations jump to xref:robots:systems_peripherals.adoc[Peripheral Systems,window=_blank].

=== Basic

include::robots:partial$peripherals_basic_list.adoc[]

=== Fancy

include::robots:partial$peripherals_fancy_list.adoc[]

== EXPS Level
EXPS Levels improve the RP's Control Factor, assist in saves and robot attributes.

include::referee_personas:partial$experience_levels.adoc[]

== Control Factor
Calculate the persona's control factor here.
For more details jump to xref:robots:control_factor.adoc[Control Factor,window=_blank].

[discrete]
=== Calculate Control Factor
.CF= (INT score) + (INT Prime* EXPS Level)
****
A 3rd level robot with a 15 INT score, and a 3 INT Prime has a CF = 24
****

== Adaptability
If there is a need to know the referee persona's adaptability check the fabrication info for the robot type.

== Value
Most referee persona robots do not like to talk about their value. 
If there is a need to know the referee persona's value check the fabrication info for the robot type.

== Tech Level
Tech level alters the wate and size of artifacts.
There is no mechanism in EXP for altering robots based on their tech level. 
Is a high tech level robot less able to ram because it is now lighter? 
Tech level could increase the value of a robot, improve its power plant, and overall alter its appearance.
Would steam power a low tech level robot? 
For more info and the effects of altering tech levels, jump to xref:hardware:tech_level.adoc[Tech Level,window=_blank].



== Age
Robots do not age.
Unlike organic life forms, robots only decay from damage and not time. 
The longer it has been since fabrication allows for an estimate of how much damage the robot has experienced.
The robot age table was previously called the decrepitude table.

include::referee_personas:partial$robot_wear_appearance.adoc[]

== Attack Table
The attack table keeps track of the persona's combat skills and increases with EXPS level.
The referee may need two attack tables for her tool using aliens.
For general info about attack tables, jump to xref:combat:attack_table_details.adoc[Attack Tables,window=_blank] in tactical combat.
For a detailed explanation of the outline below jump to xref:robots:attack_table.adoc[Robot Attack Table,window=_blank].

This attack table is for baked-in offensive systems and ramming freedom.
Robot RPs only have a Skilled Bonus (Skilled) for their baked-in attacks. 
If a robot RP manages to use a gun, her Skilled is zero.
If the robot type is Android (A), then the referee must make an anthro-like vocation-based attack table as well.
For the vocation based attack table, jump to xref:anthros:attack_table[Anthro attack table,window=_blank].

:art: bots_bots_bots.png
:width: 350px
:snark: Combat ratio can alter numbers.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Many flying robots.

include::ROOT:partial$articulate.adoc[]

== Spec Sheet
Qualitative details about how the robot moves, sees, and powers itself.

=== Power Source
Robot power sources are sciency fiction supercells that allow the robot to operate.
Recharging may be necessary.
For more detailed information, jump to xref:robots:power_source.adoc[Power Source,window=_blank].

include::hardware:partial$power_source_types.adoc[]

=== Sensors
Robot sensors allow the robot RP to hear and see like any other persona.
The higher the RPs Awareness, the more sensors they have. 
For more detailed information, jump to xref:robots:sensors.adoc[Sensors,window=_blank].

include::robots:partial$sensor_types.adoc[]

=== Locomotion
Robot locomotion allows the RP to get anywhere she can fit.
For more detailed information, jump to xref:robots:locomotion.adoc[Locomotion,window=_blank].

include::robots:partial$locomotion_types.adoc[]
include::robots:partial$locomotion_types_complementary.adoc[]

== Name
The robot should have a name like any other persona.
Robot names can become complicated because they may need a persona name, model name and fabricator name.
For more details on naming shenanigans, jump to xref:robots:moniker.adoc[Robot Name,window=_blank].

== Story Cues
There are all manner of story cues that the referee may wish to generate.
All are optional. 
For setting up story cues for this referee persona jump to xref:referee_personas:rp_story_cues.adoc[Story Cues,window=_blank].

== Combat Ratio
The combat ratio determines how dangerous a referee persona is.
Combat ratio is partially optional, but plays a roll in assigning combat experience. 
To generate a danger number for this persona jump to xref:referee_personas:rp_combat_ratio.adoc[Combat Ratio,,window=_blank].
