= Referee Story Cues

Story cues are random curiousities that flesh out the past, present and future of the referee personas. 
These have been called RP Cues in the past. 
Players can use these tables to randomly inform the story around their persona.

RP cues need to massaged slightly for each persona family.
A feral alien that has no language will not harbour a strong opinion on philosophy.
Robots may not have personalities, but they can certainly have behaviours that are determined by their malfunctions.

NOTE: *This section is an aid to creativity, not a replacement for creativity.*

== Story
The referee persona's story is a skeleton to help the referee create a backstory.
The past, present, future give the referee a skeleton to hang the story meat.

The referee persona's story is a skeleton to help the referee create a backstory.
Alien society and alien tool usage heavily influence the nature of the alien's story.
Cannon fodder flora and fauna will not have goals like reordering the universe.
A creator species that lives 2 million years may have nothing to do but reorder the universe.++Insane

=== Origin
The origin story element is a geographic cue for the referee and players.
This location history helps determine if this persona is exotic or mundane.
The details of the persona's origin may fit into the current milieu or require the referee to extend her world.

Flora and fauna that have an origin of "off-planet" can be a source of mystery.
A creator alien that has an origin of "off-planet" may have a spaceship nearby.

L33t Un1t is an expendable combot left on the planet from a past war.
She has no command and control and wanders around the desert near the expedition's home base.

include::ROOT:partial$CH11_Table_Referee_Persona_Origin.adoc[]

=== Present
The present story element is a mix of intentions and reasons for showing up.
The reasons behind the Present Story may need filling out or may fit into the existing milieu.

L33t Un1t still misses the organizational elements of an organized military force.
She would be happy to take direction from anyone with military training.
L33t Un1t will work with the expedition if they offer this kind of direction to her.

include::ROOT:partial$CH11_Table_Referee_Persona_Presence.adoc[]

=== Future
The future story element is usually an internal goal of the persona.
The referee may drop hints about the persona's future goals.
If they are nefarious, the referee will likely keep the plans secret.
It is also possible that the persona will not know what her future goal is.

L33t Un1t desires nothing more than to find meaningful leadership.
She will leave the expedition to follow any combot or military brass from her previous campaign.

include::ROOT:partial$CH11_Table_Referee_Persona_Goal.adoc[]

== Personality
Personality traits help guide the referee when the RP is making decisions.
While it is fun to play up an RP's personality, the referee must remember the pithy aphorism; less is more. 
The players should be guiding the story, not a strong-willed referee (persona).

How the alien expresses these personality traits is up to the referee.
If an alien does not have language, she cannot express complex emotions.
Aliens like flora and fauna can have personalities.
The personality would determine how the referee persona interacts with the players.
A local alien without language or tool use may flee in terror with the presentation of a book (bibliophobia)

Robot personalities are accidental and arise from malfunctions and damage to their processes.
If the robot RP was to be appropriately 'repaired,' she would lose her personality.

The personality types are organized by how strongly they influence the persona's decision.

The initial die roll is on the Extroverted Personality Trait table. However, the persona is more likely to have an introverted personality trait. 

.*Personality and Decisions*
. None - follows and contributes.
. Introverted - has opinions but does not fight for them.
. Extroverted - has strong opinions and behaviours.
. Irrational - has beliefs and will make bad decisions.

The initial die roll is on the Extroverted Personality Trait table. However, the persona is more likely to have an introverted personality trait. 

include::ROOT:partial$CH11_Table_Referee_Persona_Extroverted_Personality_Trait.adoc[]

=== Extroverted
Extroverted personality traits are not irrational.
They are just obvious.
A diplomatic RP will *not* try to negotiate with a heavy combot.
She will run away.
A diplomatic RP may intercede between player persona arguments about loot distribution.
The expedition can win over an extroverted personality trait with some convincing.

=== Introverted
These are not immediately obvious to the players.
The referee persona may have opinions based on the personality trait, but she will readily agree with the expedition.
An introverted personality trait may influence a referee's "behind the shield" decision. 

include::ROOT:partial$CH11_Table_Introverted_Personality_Trait.adoc[]

=== Irrational
Irrational personality traits are not clinical illnesses.
The traits are not illnesses from the https://en.wikipedia.org/wiki/DSM-5[DSM].
They are personality traits so strong that the RP may make the wrong decision and cannot be convinced otherwise.

The insanity may be overt and quickly discovered by the expedition.
Or it may be hidden and discovered when it is too late.

NOTE: *Irrational personality traits were formerly called Insane Personality Traits*

Extroverted and introverted personality traits will not put the persona in harm's way.
Irrational personality traits can put the whole expedition in harm's way. 
These are the kind of traits that will override the better, often safer, decision.

The expedition can influence extroverted and introverted personality traits to do what is best for the expedition.
Irrational personality traits are immune to the rational input of the expedition. 

include::ROOT:partial$CH11_Table_Insane_Referee_Persona_Personality_Traits.adoc[]

== Anthro RP Appearance
An RPs appearance has three elements: clothing, hygiene and gender.
All of them are optional.

=== Clothing
Clothing is appearance only.
Clothing does not represent the culture, gender, occupation or personality of the referee persona.
A persona's clothing may be uniform that she always wears or may be a nuance of existing fashions.

An RP may have several favourite styles and may even combine them in some random arrangement.
The shoes may be punk rock, but the hairdo renaissance. 

Clothing is appearance only.
Clothing does not represent the culture, gender, occupation or personality of the referee persona.

Alien RP clothing is unique to the alien. 
At best, the clothing type loosely informs the appearance of the clothing.

Flora and fauna have *NO* clothing.

include::ROOT:partial$CH11_Table_Referee_Persona_Dress.adoc[]

=== Hygiene
Hygiene is a general habit that the persona exhibits.
Hygiene does not influence Charisma, social standing or task rolls.

While variable depending on the scenario, the RP tends to ebb back to the hygiene description.
A habitually immaculate RP that fell in the mud would look like someone who fell in the mud.
The immaculate RP would clean herself off sooner and better than the filthy RP.
A habitually filthy spie would not arrive un-groomed at an aristocratic function.

include::ROOT:partial$CH11_Table_Referee_Persona_Hygiene.adoc[]

=== Gender
Gender represents appearance only.
Gender does not represent genetics, sexuality, reproduction, or employment.
The politics of gender are up to the referee and players. 

include::ROOT:partial$CH11_Table_RP_Gender.adoc[]

== Beliefs
Beliefs are purely cerebral elements of the referee persona.
They are not nearly as entrenched as personality or hygiene.
Referee personas may talk the talk about a belief, but how devout they are is variable.
RP beliefs are what the persona would like to be rather than what they are.

The robot RP can have beliefs similar to an anthro persona.
The robot may be randomly expressing these beliefs due to the damage that gave her consciousness.
The robot may intentionally express these beliefs because they were programmed in by the fabricator type or corporation.

include::ROOT:partial$CH11_Table_RP_Beliefs.adoc[]

=== Religious
The list here describes the structure of the religion and does not list existing human faiths.
The referee and her milieu determine the nomenclature, structure, hypocrisy, and corruption of the religion.

include::ROOT:partial$CH11_Table_Referee_Persona_Religious_Belief.adoc[]

=== Political
The list here describes the structure of the politics and does not list existing human parties.
The referee and her milieu determine the nomenclature, structure, hypocrisy, and corruption of the political system.

include::ROOT:partial$CH11_Table_Referee_Persona_Political_Belief.adoc[]

=== Philosophical
Some are real.
Some are silly.
All are mental exercises in futility. 

include::ROOT:partial$CH11_Table_Referee_Persona_Philosophical_Belief.adoc[]


=== Colour Your Whirled
Colour makes the world go round.

include::ROOT:partial$add_colour_to_your_world.adoc[]



