= Referee Persona Story Cues

Story cues are random curiousities that flesh out the history, reactions and plans of referee personas. 
While primarily intended for referees' use, all players can utilize these tables to add random elements to their personas.

Role playing cues need to be massaged for each persona family.
A feral alien that has no language will not harbour a strong opinion on philosophy.
Robots will not have anxiety but may have malfunctions that make it appear so.

NOTE: *This section is an aid to creativity, not a replacement for creativity.*

== Improv 
The necessary components of a character for improv comedy theatre provide a useful framework for RPG personas.
Improv comedy characters are broken into three parts: Move, Sound, Want.

For more details jump to https://www.learnimprov.com/three-parts/[Triangle,window=_blank] at https://www.learnimprov.com/[Learnimprov.com,window=_blank].

.*Improv Character Triangle*
* move
** gait, posture, speed, gestures, shape
* sound
** volume, speed, pitch, emotion, words
* want
** desires, triggers, goals, beliefs, triggers, needs

== History
The referee persona's story is a skeleton to help the referee create a backstory.
The past, present, future give the referee a skeleton to hang the story meat.

The referee persona's story is a skeleton to help the referee create a backstory.
Alien society and alien tool usage heavily influence the nature of the alien's story.
Cannon fodder flora and fauna will not have goals like reordering the universe.
A creator species that lives 2 million years may have nothing to do but reorder the universe.++Insane

=== Origin
The origin history element is a geographic cue for the referee and players.
Origin history helps determine if this persona is exotic or mundane.
The details of the persona's origin may fit into the current milieu or require the referee to extend her world.

Flora and fauna that have an origin of "off-planet" may have escaped from a visiting spaceship.
A creator level alien that has an origin of "off-planet" may have a spaceship nearby.

Consider L33t Un1t.
She is an expendable combot left behind on the planet after a distant interplanetary conflict.
She has no command and control and wanders around the desert near the expedition's home base.

include::referee_personas:partial$history_origin.adoc[]

=== Present
The present history is mostly focused on how the referee persona is interacting with the expedition right now. 
The table is a mix of intentions and reasons for being present.

Let's consider the expendable combat L33t Un1t again. 
She still misses the organizational elements of an organized military force.
She would be happy to take direction from anyone with military training.
L33t Un1t will work with the expedition if they offer this kind of direction to her.

include::referee_personas:partial$history_present.adoc[]

=== Future
The future story element is usually an internal goal of the persona.
The referee may drop hints about the persona's future goals.
If they are nefarious, the referee will likely keep the plans secret.
It is also possible that the persona will not know what her future goal is.

Let's consider the expendable combat L33t Un1t yet again.
L33t Un1t desires nothing more than to find meaningful leadership.
She will leave the expedition to follow any combot or military brass that will boss her around.

include::referee_personas:partial$history_future.adoc[]

== Personality
Personality traits help guide the referee when the RP is making decisions.
While it is fun to play up an RP's personality, remember the pithy aphorism; less is more. 
The players should be guiding the story, not a strong-willed referee (persona).


Personalities do require some massaging based on family types. 
The main thrust of personalities is to assist anthro referee personas. 
Aliens with advanced societal strata, robots and all anthros can have personalities.

Even a feral aliens may express personality elements. 
A normally docile alien may flee in terror with the presentation of a book (bibliophobia)
An alien that does not have language cannot express complex emotions.

The referee may choose from each of the particular tables if they have something in mind.
If personality traits are being randomly generated then start on the Extroverted Personality Trait Table
Rolling on this table determines the presence of introverted or irrational personality traits.

.*Personality Strength and Decisions*
* None - follows and contributes.
* Introverted - has opinions but does not fight for them.
* Extroverted - has strong opinions and behaviours.
* Irrational - has beliefs and will make bad decisions.

=== Extroverted
Extroverted personality traits are immediately obvious to the players. 
These traits are not irrational, they are just obvious and strong.
A diplomatic RP will *not* try to negotiate with a heavy combot.
She will run away.
A diplomatic RP may intercede between player persona arguments about loot distribution.
The expedition can win over an extroverted personality trait with some convincing.

The initial personality roll is made on the Extroverted Personality Trait Table.

include::referee_personas:partial$personality_extroverted.adoc[]

=== Introverted
Introverted personality traits are not immediately obvious to the players.
The referee persona may have opinions based on the personality trait, but she will readily agree with the expedition.
An introverted personality trait may influence a referee's "behind the shield" decision. 

include::referee_personas:partial$personality_introverted.adoc[]

=== Irrational
Irrational personality traits are immediately obvious to the players and problematic.
These traits impair the referee persona's ability to make good decisions and appear as illnesses.
However, these traits are not illnesses from the https://en.wikipedia.org/wiki/DSM-5[DSM].
They are personality traits so strong that the RP may make the wrong decision.

NOTE: *Irrational personality traits were formerly called Insane Personality Traits*

Extroverted and introverted personality traits will not put the persona in harm's way.
Irrational personality traits can put the whole expedition in harm's way. 
These are the kind of traits that will override the better, often safer, decision.

The expedition can influence extroverted and introverted personality traits to do what is best for the expedition.
Irrational personality traits are immune to the rational input of the expedition. 

include::referee_personas:partial$personality_irrational.adoc[]

== Appearances
Appearances are flexible presentations that the referee persona may have.
The referee persona can change their appearance, but they cannot change their shape.
For example, a gigantic pig headed alien may wear a top hat and look well groomed. 
Later the same gigantic pig headed alien may be wearing a mumu and look dishevelled.

There are really no family limits to appearances.
A robot may cover itself in accents that __resemble__ wet coast rain jacket. 
Aliens with advanced societal strata will certainly have clothing and hygiene presentations. 
Even flora and fauna may cover themselves with elements that make it appear they are dressing up. 
However, in general, flora and fauna do not put on appearances.

=== Dressing
Dressing is appearance only.
Dressing does not represent the culture, gender, occupation or personality of the referee persona.
A persona's dress may be a uniform that she always wears, or just be a fleeting moment of fashion.
Dressings can be mixed and matched.
For example, the shoes may be punk rock, but the hairdo renaissance.
The term dressing is used in place of clothing to reflect how different families can wear things.

include::referee_personas:partial$appearances_dressing.adoc[]

=== Hygiene
Hygiene is a general habit that the persona exhibits.
Hygiene does not influence Charisma, social standing or task rolls.

Hygiene may vary with the scenario, but the RP tends to ebb back to the hygiene description.
A habitually immaculate RP that fell in the mud would look like someone who fell in the mud.
The immaculate RP would clean herself off sooner and better than the filthy RP.
A habitually filthy spie would not arrive un-groomed at an aristocratic function.

include::referee_personas:partial$appearances_hygiene.adoc[]

=== Gender
Gender represents appearance only.
Gender does not represent genetics, sexuality, reproduction, or employment.
The politics of gender are up to the referee and players. 

include::referee_personas:partial$appearances_gender.adoc[]

=== Colour
If some colour is needed to spice things up. 

include::ROOT:partial$add_colour_to_your_world.adoc[]

== Beliefs
Beliefs are purely cerebral elements of the referee persona.
They are not nearly as entrenched as personality or hygiene.
Referee personas may talk the talk about a belief, but how devout they are is variable.
RP beliefs are what the persona would __like to be__ rather than what they are.

The robot RP can have beliefs similar to an anthro persona.
The robot may be randomly expressing these beliefs due to the damage that gave her consciousness.
The robot may intentionally express these beliefs because they were programmed in by the fabricator type or corporation.

By definition alien flora and fauna do not have beliefs.

include::referee_personas:partial$beliefs_complexity.adoc[]

=== Religion
The list here describes the structure of the religion and does not list existing human faiths.
The referee and her milieu determine the nomenclature, structure, hypocrisy, and corruption of the religion.

include::referee_personas:partial$beliefs_religion.adoc[]

=== Political
The list here describes the structure of the politics and does not list existing human parties.
The referee and her milieu determine the nomenclature, structure, hypocrisy, and corruption of the political system.

include::referee_personas:partial$beliefs_politics.adoc[]

=== Philosophical
Some are real.
Some are silly.
All are mental exercises in futility. 

include::referee_personas:partial$beliefs_philosophical.adoc[]

== Labanations
Labanations are an extremely abridged list of descriptive movements based on https://en.wikipedia.org/wiki/Laban_movement_analysis[Laban Movement Analysis].
Laban Movement Analysis is many times more complex than the list below.
The original goal of the work as to create a language for choreography that equalled a musical score.
Laban Movement Analysis is used within theatre arts to characterize both speech and movement. 
This heavily abridged version can be applied to the move and sound of a persona. 
The goal for using this analysis to allow for distinct persona sounds and movements that are rooted in mundane terran cultural accents and stereotypes.

include::referee_personas:partial$labanations.adoc[]

Each Labanation has a wate, speed and intention.

Wate::
Heavy or light. 
A heavy movement may be thudding. 
A heavy sound may be deep or loud. 
A light movement may be delicate or gentle.
A light sound may be quiet. 

Speed::
Fast or Slow.
Same with movements or sounds. 

Intention::
Direct or Indirect.
Direct is focused on a target and not unclear in action.
Indirect is unfocused and may be glancing or unclear. 
