= Referee Persona Cues


== Anthro RP Role Playing
The first half of referee persona creation (RP Roll Playing) involves much dice rolling and data collection.
The data collected is essential for players using the Roll Playing System. 

NOTE: *This section is an aid to creativity, not a replacement for creativity.*

This second half of referee persona creation (RP Role Playing) is qualitative and descriptive.
Little or none of the information in this section affects the power of the persona.
However, it does affect the story of the persona. 
The Anthro RP Role Playing section is for inspiration and creative support.
Use this section as a framework for creating the backstory plans and emotions of referee personas. 

* *RP ROLE PLAYING (Fun)*
. <<_anthro_rp_story,Story>>
.. Past
.. Present 
.. Future
.. Personality
. <<_anthro_rp_appearance,Appearance>>
.. Clothing
.. Hygiene
.. Gender
. <<_anthro_rp_beliefs,Beliefs>>
.. Religious
.. Political
.. Philosophical
. <<_modifications,Modifications>>
.. attributes
.. size
.. age
. <<_anthro_rp_name,Name>>

== Anthro RP Story
The referee persona's story is a skeleton to help the referee create a backstory.
By this point, the persona already has a vocation, anthro type, experience level.
The past, present, future and personality of the persona give the referee a skeleton to hang the story meat.

Cannon, and canon, fodder do not have detailed stories at all. 
Canonical personas may need a lot more.

=== Past
The past story element is a geographic cue for the referee and players.
This location history helps determine if this persona is exotic or mundane.
The details of the persona's origin may fit into the current milieu or require the referee to extend her world.

include::ROOT:partial$CH11_Table_Referee_Persona_Origin.adoc[]

=== Present
The present story element is a mix of intentions and reasons for showing up.
The reasons behind the Present Story may need filling out or may fit into the existing milieu.

include::ROOT:partial$CH11_Table_Referee_Persona_Presence.adoc[]

=== Future
The future story element is usually an internal goal of the persona.
The referee may drop hints about the persona's future goals.
If they are nefarious, the referee will likely keep the plans secret.
It is also possible that the persona will not know what her future goal is.

include::ROOT:partial$CH11_Table_Referee_Persona_Goal.adoc[]

=== Personality
Personality traits help guide the referee when the RP is making decisions.
While it is fun to play up an RP's personality, the referee must remember the pithy aphorism; less is more. 
The players should be guiding the story, not a strong-willed referee (persona).

The personality types are organized by how strongly they influence the persona's decision.

.*Personality and Decisions*
. None - follows and contributes.
. Introverted - has opinions but does not fight for them.
. Extroverted - has strong opinions and behaviours.
. Insane - has beliefs and will make bad decisions.

The initial die roll is on the Extroverted Personality Trait table. However, the persona is more likely to have an introverted personality trait. 

include::ROOT:partial$CH11_Table_Referee_Persona_Extroverted_Personality_Trait.adoc[]

==== Extroverted
Extroverted personality traits are not irrational.
They are just obvious.
A diplomatic RP will *not* try to negotiate with a heavy combot.
She will run away.
A diplomatic RP may intercede between player persona arguments about loot distribution.
The expedition can win over an extroverted personality trait with some convincing.

==== Introverted
These are not immediately obvious to the players.
The referee persona may have opinions based on the personality trait, but she will readily agree with the expedition.
An introverted personality trait may influence a referee's "behind the shield" decision. 

include::ROOT:partial$CH11_Table_Introverted_Personality_Trait.adoc[]

==== Insane
Insane personality traits are not clinical illnesses.
The traits are not illnesses from the https://en.wikipedia.org/wiki/DSM-5[DSM].
They are personality traits so strong that the RP may make the wrong decision and cannot be convinced otherwise.

The insanity may be overt and quickly discovered by the expedition.
Or it may be hidden and discovered when it is too late.

NOTE: *Insanity is not role-played as a disease but as a decision influencer.*

Extroverted and introverted personality traits will not put the persona in harm's way.
Insane personality traits can put the whole expedition in harm's way. 
These are the kind of traits that will override the better, often safer, decision.

The expedition can influence extroverted and introverted personality traits to do what is best for the expedition.
Insane personality traits are immune to the rational input of the expedition. 

include::ROOT:partial$CH11_Table_Insane_Referee_Persona_Personality_Traits.adoc[]

== Anthro RP Appearance
An RPs appearance has three elements: clothing, hygiene and gender.
All of them are optional.

=== Clothing
Clothing is appearance only.
Clothing does not represent the culture, gender, occupation or personality of the referee persona.
A persona's clothing may be uniform that she always wears or may be a nuance of existing fashions.

An RP may have several favourite styles and may even combine them in some random arrangement.
The shoes may be punk rock, but the hairdo renaissance. 

include::ROOT:partial$CH11_Table_Referee_Persona_Dress.adoc[]

=== Hygiene
Hygiene is a general habit that the persona exhibits.
Hygiene does not influence Charisma, social standing or task rolls.

While variable depending on the scenario, the RP tends to ebb back to the hygiene description.
A habitually immaculate RP that fell in the mud would look like someone who fell in the mud.
The immaculate RP would clean herself off sooner and better than the filthy RP.
A habitually filthy spie would not arrive un-groomed at an aristocratic function.

include::ROOT:partial$CH11_Table_Referee_Persona_Hygiene.adoc[]

=== Gender
Gender represents appearance only.
Gender does not represent genetics, sexuality, reproduction, or employment.
The politics of gender are up to the referee and players. 

include::ROOT:partial$CH11_Table_RP_Gender.adoc[]


== Anthro RP Beliefs
Beliefs are purely cerebral elements of the referee persona.
They are not nearly as entrenched as personality or hygiene.
Referee personas may talk the talk about a belief, but how devout they are is variable.
RP beliefs are what the persona would like to be rather than what they are.

include::ROOT:partial$CH11_Table_RP_Beliefs.adoc[]

=== Religious Belief
The list here describes the structure of the religion and does not list existing human faiths.
The referee and her milieu determine the nomenclature, structure, hypocrisy, and corruption of the religion.

include::ROOT:partial$CH11_Table_Referee_Persona_Religious_Belief.adoc[]

=== Political Belief
The list here describes the structure of the politics and does not list existing human parties.
The referee and her milieu determine the nomenclature, structure, hypocrisy, and corruption of the political system.

include::ROOT:partial$CH11_Table_Referee_Persona_Political_Belief.adoc[]

=== Philosophical Belief
Some are real.
Some are silly.
All are mental exercises in futility. 

include::ROOT:partial$CH11_Table_Referee_Persona_Philosophical_Belief.adoc[]


== Alien RP Story
The referee persona's story is a skeleton to help the referee create a backstory.
Alien society and alien tool usage heavily influence the nature of the alien's story.
Cannon fodder flora and fauna will not have goals like reordering the universe,.
A creator species that lives 2 million years may have nothing to do but reorder the universe.

Flora and fauna that have an origin of "off-planet" can be a source of mystery.
A creator alien that has an origin of "off-planet" may have a spaceship nearby.

NOTE: *This section is an aid to creativity, not a replacement for creativity.*

=== Origin
The past story element is a geographic cue for the referee and players.
This location history helps determine if this persona is exotic or mundane.
The details of the persona's origin may fit into the current milieu or require the referee to extend her world.

include::ROOT:partial$CH11_Table_Referee_Persona_Origin.adoc[]

=== Present
The present story element is a mix of intentions and reasons for showing up.
The reasons behind the Present Story may need filling out or may fit into the existing milieu.

include::ROOT:partial$CH11_Table_Referee_Persona_Presence.adoc[]

=== Future
The future story element is usually an internal goal of the persona.
The referee may drop hints about the persona's future goals.
If they are nefarious, the referee will likely keep the plans secret.
It is also possible that the persona will not know what her future goal is.

include::ROOT:partial$CH11_Table_Referee_Persona_Goal.adoc[]

== Alien RP Personality
Personality traits help guide the referee when the RP is making decisions.
While it is fun to play up an RP's personality, the referee must remember the pithy aphorism; less is more. 
The players should be guiding the story, not a strong-willed referee (persona).

How the alien expresses these personality traits is up to the referee.
If an alien does not have language, she cannot express complex emotions.
Aliens like flora and fauna can have personalities.
The personality would determine how the referee persona interacts with the players.
A local alien without language or tool use may flee in terror with the presentation of a book (bibliophobia)

The personality types are organized by how strongly they influence the persona's decision.

The initial die roll is on the Extroverted Personality Trait table. However, the persona is more likely to have an introverted personality trait. 

include::ROOT:partial$CH11_Table_Referee_Persona_Extroverted_Personality_Trait.adoc[]

=== Extroverted
Extroverted personality traits are not irrational.
They are just obvious.
A diplomatic RP will *not* try to negotiate with a heavy combot.
She will run away.
A diplomatic RP may intercede between player persona arguments about loot distribution.
The expedition can win over an extroverted personality trait with some convincing.

=== Introverted
These are not immediately obvious to the players.
The referee persona may have opinions based on the personality trait, but she will readily agree with the expedition.
An introverted personality trait may influence a referee's "behind the shield" decision. 

include::ROOT:partial$CH11_Table_Introverted_Personality_Trait.adoc[]

=== Insane
Insane personality traits are not clinical illnesses.
The traits are not illnesses from the https://en.wikipedia.org/wiki/DSM-5[DSM].
They are personality traits so strong that the RP may make the wrong decision and cannot be convinced otherwise.

The insanity may be overt and quickly discovered by the expedition.
Or it may be hidden and discovered when it is too late.

NOTE: *Insanity is not role-played as a disease but as a decision influencer.*

Extroverted and introverted personality traits will not put the persona in harm's way.
Insane personality traits can put the whole expedition in harm's way. 
These are the kind of traits that will override the better, often safer, decision.

The expedition can influence extroverted and introverted personality traits to do what is best for the expedition.
Insane personality traits are immune to the rational input of the expedition. 

include::ROOT:partial$CH11_Table_Insane_Referee_Persona_Personality_Traits.adoc[]

== Alien RP Appearance
An RPs appearance has three elements: clothing, hygiene and gender.
All of them are optional.

=== Gender
Gender represents appearance only.
Gender does not represent genetics, sexuality, reproduction, or employment.
It is up to the referee to decide how gender appearance applies to a parasitic psionic ambushing insect.

include::ROOT:partial$CH11_Table_RP_Gender.adoc[]

=== Clothing
Clothing is appearance only.
Clothing does not represent the culture, gender, occupation or personality of the referee persona.

Alien RP clothing is unique to the alien. 
At best, the clothing type loosely informs the appearance of the clothing.

Flora and fauna have *NO* clothing.

include::ROOT:partial$CH11_Table_Referee_Persona_Dress.adoc[]



== Robot RP Story
The referee persona's story is a skeleton to help the referee create a backstory.
The past, present, future and personality of the persona give the referee a skeleton to hang the story meat.
Cannon, and canon, fodder do not have detailed stories at all. 
Canonical personas may need a lot more.

=== Past
L33t Un1t is an expendable combot left on the planet from a past war.
She has no command and control and wanders around the desert near the expedition's home base.

include::ROOT:partial$CH11_Table_Referee_Persona_Origin.adoc[]

=== Present
L33t Un1t still misses the organizational elements of an organized military force.
She would be happy to take direction from anyone with military training.
L33t Un1t will work with the expedition if they offer this kind of direction to her.

include::ROOT:partial$CH11_Table_Referee_Persona_Presence.adoc[]

=== Future
L33t Un1t desires nothing more than to find meaningful leadership.
She will leave the expedition to follow any combot or military brass from her previous campaign.

include::ROOT:partial$CH11_Table_Referee_Persona_Goal.adoc[]

=== Personality
Robot personalities are accidental and arise from malfunctions and damage to their processes.
If the robot RP was to be appropriately 'repaired,' she would lose her personality.

include::ROOT:partial$CH11_Table_Introverted_Personality_Trait.adoc[]

== Robot RP Appearance
Shape, colours, locomotion type, and peripherals contribute to the robot RP appearance.
These tables are for inspiration and fun and should not replace referee creativity.

=== Basic Shape
The basic shape is fit into the dimensions of the robot. 

include::robots:partial$basic_shapes.adoc[]

=== Contortion of Basic Shape
The referee can contort the shape above for fun and randomness.

include::robots:partial$basic_shape_distortions.adoc[]

=== Attachments
Useless attachments.

include::ROOT:partial$CH11_Table_Fancy_Attachments.adoc[]

=== Colour Your Robot
Colour makes the world go round.

include::ROOT:partial$add_colour_to_your_world.adoc[]

== Robot RP Beliefs
The robot RP can have beliefs similar to an anthro persona.
The robot may be randomly expressing these beliefs due to the damage that gave her consciousness.
The robot may intentionally express these beliefs because they were programmed in by the fabricator type or corporation.

include::ROOT:partial$CH11_Table_RP_Beliefs.adoc[]

include::ROOT:partial$CH11_Table_Referee_Persona_Religious_Belief.adoc[]

include::ROOT:partial$CH11_Table_Referee_Persona_Political_Belief.adoc[]

include::ROOT:partial$CH11_Table_Referee_Persona_Philosophical_Belief.adoc[]
