= Persona Creation

According to most dictionaries, a persona is a character of fictional representation. 
In role-playing games, the persona is the player’s tool.
The persona is what she manipulates to participate in the game. 
Each player in the game has a persona.
Personas are extensions of the players into the fantasy world of EXP.
The persona is how the player interacts with the imaginary world of EXP.
The personas are all played together as a group which attempts to solve the puzzles put forth by the referee. 
It is impossible for us to clamour aboard spaceships, fire laser pistols or experience zero gravity in our own home but, through our imaginations, we an experience anything.

It is the chapters below that allow one to create a persona for playing EXP.

== Persona Creation
. Familiarize yourself with EXP
.. xref:ROOT:CH01_Playing_Exp.adoc[EXP]
.. xref::ROOT:CH02_Playing_Personas.adoc[Personas]
. xref::CH03_Attributes.adoc[Attributes]
. Choose a race
.. *Anthro* most common
.. Robot
.. Alien
. Mutations
. Vocation
. Combat Tables
. Incidentals
. Referee Personas
.. Alien
.. Anthro
.. Robot