= Persona Creation

[quote]
____
the aspect of someone's character that is presented to or perceived by others.
____

A persona is a character of fictional representation. 
In role-playing games, the persona is the player’s tool.
The persona is what the player manipulates to participate in the game.
Personas are extensions of the players into the fantasy world of EXP.
The persona is how the player interacts with the imaginary world of EXP.
Every player in the game has a persona.
The referee will have many personas.
Some referee personas will be important, others will be insignificant.

Since EXP is a table top in the flesh role playing game the players gather together.
The personas are all played together as a group which attempts to solve the puzzles put forth by the referee. 
It is impossible for us to clamour aboard spaceships, fire laser pistols or experience zero gravity in our own home but, through our imaginations, we an experience anything.

== Steps for Persona Creation

. xref:ROOT:index.adoc[Get to know EXP]
.. xref:ROOT:CH01_Playing_Exp.adoc[The Game]
.. xref:ROOT:CH02_Playing_Personas.adoc[The personas]
. xref:CH04__Families.adoc[Choose a family]
.. xref::CH04_Anthros_.adoc[Anthro (most common)]
.. xref::CH05_Robots_.adoc[Robots]
.. xref::CH06_Aliens_.adoc[Alien]
. xref::CH07_Mutating.adoc[Mutations]
. xref::CH08_Vocations_.adoc[Vocations]
. xref:CH10_Incidentals.adoc[Incidentals]
. xref:ii-non_combat_rules:CH14_Performance_Tables.adoc[Performance Tables]
. xref:iii-combat_rules:CH09_Combat_Tables.adoc[Combat Tables]
. *Have fun!*
