= Social Standing (SS)

:art: sociabilityfield.png
:width: 250px
:snark: Honey attracts more flies.
:artist: Mike Jackson
:date: 1990
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Social Standing indicates where the persona fits into her social structure.
SS is an odd attribute because it is not a physiologic one.
Social Standing indicates how much power the persona has in her society.

How social standing is reflected varies wildly between the families.
Anthro social standing represents with wealth, fame, power or accomplishment.
Alien social standing could represent access to food, breeding or territory.
For aliens with advanced societies SS could be the same as anthro SS.
Robot SS is reflected in access to power, maintenance schedules and 

Social standing influences getting a reservation, where they sit on the bus, or being known.
Social Standing is a tool to assist decisions involving power.
SS always takes second place to role-playing and the referee's story and world creation.

// brand new table for version 6.0
.*Social Standing by Family*
[width="75%",cols="<,<,<,<"]

|===

|
s|Anthro
s|Robot
s|Alien

s|Die Roll
|1d1000
|1d1000
|1d1000

s|Range
|1-1000
|1-1000
|1-1000

|
s|Anthro
s|Robot
s|Alien
|===