= Hit Points (HPS)

:art: hitpoints.png
:width: 
:snark: How much damage can one take?
:artist: Warren Oddsson
:date: 1990
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Hit points reflect the persona’s ability to withstand physical damage.
The important components of HPS are based on the body construction.
how well the brain is protected; the amount of protective tissue around vital organs; and the connective tissue’s ability to resist tearing and shattering.
There are other less gruesome components of hit points.
These include the innate skill of the body, as a whole, to react to threat and just plain old luck.

Hit points are a very dynamic attribute.
Unlike the persona’s other attributes, which are unlikely to ever alter during a persona’s life, hit points will constantly have different values, although none of these values should exceed the persona’s maximum HPS.

Whenever a player character is injured in some way or other, she loses HPS.
Personas which lose too many hit points will die.
Personas which die from loss of hit points will usually die in some violent death.
shooting, stabbing car accident, fall, explosions, etc.
For more information about losing hit points, she chapters 26 or 27 in the combat section.

Personas don’t just lose hit points until they die (hit points are a dynamic attribute, not a declining attribute).
Personas can regain hit points back through rest.
See Chapter 13. Health for more information about rest.
Medical attention can also heal back lost hit points.

The hit point doesn’t convert to some unit of energy – like an erg.
However, the hit point is a constant value.
Any anthro, alien or robot that absorbs 10 HPS of damage deducts that from their HPS total.
What varies is how each family type is affected upon reaching 1 HPS.
How aliens and robots respond to very low hit point totals (less than 1) is covered in their respective chapters.
How people respond to particular HPS totals is detailed here.

All in all, hit points are a general indicator of a being’s overall hardiness.
The more HPS the creature has, the better condition she is in.

== HPS Maximum
A persona’s maximum HPS is determined once, while the player is rolling her attributes.
The maximum HPS cannot be exceeded by healing of any sort (of course, there are always exceptions).
No pity should be given to the players while they are rolling their persona’s HPS.
Hit points should be considered just another attribute which will determine class and family.
Once the player has determined a maximum HPS, it should be recorded in ink on her persona record sheet.

// brand new table for version 6.0
.*Hit Points by Family*
[width="75%",cols="<,<,<,<"]

|===

|
s|Anthro
s|Robot
s|Alien

s|HPS Basis
|CON
|CON and Type
|CON and Size

s|Range
|5-90
|0-500
|1-750

|
s|Anthro
s|Robot
s|Alien

|===


