= Intelligence (INT)

:art: intelligence.png
:width: 250px
:snark: Soggy bag of chemicals, elecricity and consciousness.
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Intelligence indicates the smarts of the persona.
Elements of INT are memory, deduction, creativity, adaptability and their synergism.
The higher the intelligence of the persona the smarter she is.

This attribute does not replace role-playing. 
Players can make very bad decisions for their intelligent personas.
Roll-playing can allow an intelligent persona to accomplish something her player cannot.
A high INT should not subvert a referee's campaign puzzles.
Some things things the player's will need to figure out themselves. 

Anthros and alien INT represents the number and connectivity of their brain's synapses.
Robots brains are inorganic represent baked in processors and machinery. 

Intelligence is equivalent between the families. 
Robot INT of 12 is no better than anthro INT of 12.
Alien INT does not indicate language, tool or tech using. 
An alien can be fauna in the ecosystem, and use it's INT within that system.


// brand new table for version 6.0
.*Intelligence by Family*
[width="75%",cols="<,<,<,<"]
|===

|
s|Anthro
s|Robot
s|Alien

s|Die Roll
|3d6
|1d4 (level)
|5d6-5

s|Range
|3-18
|1-25
|0-25

|
s|Anthro
s|Robot
s|Alien
|===