= Awareness (AWE)

:art: awareness_eyes.png
:width: 
:snark: Eyes, ears, nose. Key elements of awareness.
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]



Awareness indicates how aware a persona is of their surroundings.
The higher the persona’s AWE, the better she can pick out noises, spot objects and detect aromas.
So a person with a high awareness would be observant, have a fine sense of smell and have good hearing.
AWE would be the most important attribute when trying to locate a hidden object or search a room.

AWE for anthros is the same as for homo sapiens. 
Eyes for vision, ears for hearing, nose for smell and skin for touch.
AWE for aliens is similar to anthros with vision, hearing etc.
However there may be no obvious nose, ears or tongue. 
AWE for robots is inorganic in nature.
Robots represents cameras for vision, microphones for hearing and other inorganic sensors.

If a persona’s awareness drops below 1 she is dead.
Her brain has been cut off from all exterior and interior stimuli.

// brand new table for version 6.0
.*Awareness by Family*
[width="75%",cols="<,<,<,<"]
|===

|
s|Anthro
s|Robot
s|Alien

s|Die Roll
|3d6
|3d6
|3d6

s|Range
|3-18
|3-18
|3-18

|
s|Anthro
s|Robot
s|Alien

|===

