= Constitution (CON)

:art: constitution.png
:width:
:snark: The organs of resilience. 
:artist: Warren Oddsson
:date: 1990
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Constitution represents a persona’s internal physique.
CON is a combination of wellness, immunity, energy extraction, healing ability.
A high CON is better to repel disease, resist poisons, and repair damaged tissue.

Anthro components are heart, lungs, digestion, kidneys, coagulation and immune systems.
Robot components quality materials, part redundancy, efficient components.
Alien components are the same as anthro.
However alien one's may include gills, redundant organs, and other unique organs. 

There is a strong relationship between constitution and hit points.
Hit Points represent the complete package of the persona's ability to take damage.
The persona's CON influences HPS for all persona types.

If a persona’s CON should drop below 1 she is irrevocably dead.
Complete failure of energy extraction, healing, 

// brand new table for version 6.0
.*Constitution by Family*
[width="75%",cols="<,<,<,<"]

|===

|
s|Anthro
s|Robot
s|Alien

s|Die Roll
|3d6
|1d4 (level)
|5d6-5

s|Range
|3-18
|1-25
|0-25

|
s|Anthro
s|Robot
s|Alien
|===

