= Intelligence (INT)

:art: intelligence.png
:width: 250px
:snark: Soggy bag of chemicals, elecricity and consciousness.
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The attribute of intelligence includes many aspects of sentient behaviour.
creative thought, mnemonic resources and learning capacity.
It would be incorrect to assume that a persona has an equal distribution of all these components but actually some undetermined mixture which results in the standard INT value.

Rolling INT for a persona poses some questions about player/persona interaction.
Conclusions made by a player cannot be refuted because her persona has a low INT score.
Such inaccuracies will either be creatively disguised by the player or merely chalked up to the old numinous.
The obverse situation, a personal with a high INT attribute run by a dull player will not allow the player to sit back and have scenarios solve themselves.
If the player herself cannot solve a problem, that’s just too bad.

A persona’s INT directly affects one of her other attributes.
The affected attribute is her mental strength.
The mental strength is a psychic sort of attribute.
It reflects the persona’s will power, luck and control over the unknown components of the mind.
Mental strength is an attribute entirely separate from INT but greatly modified by it.
The more intelligent a persona is, the more she can manipulate this intangible mental attribute.

// brand new table for version 6.0
.*Intelligence by Family*
[width="75%",cols="<,<,<,<"]

|===

|
s|Anthro
s|Robot
s|Alien

s|Die Roll
|3d6
|1d4 (level)
|5d6-5

s|Range
|3-18
|1-25
|0-25

|
s|Anthro
s|Robot
s|Alien
|===