= Attributes

A persona’s attributes are its natural given abilities.
The attributes reflect things like strength and intelligence.
Each attribute is determined by dice and these values represent the first inklings of the persona
Until now, the persona has been nothing more than a flicker of the player’s imagination.
The attributes are the first steps toward the creation of a persona.

== What Are They?

The higher the value of the attribute, the better the attribute is.
A persona’s attribute values determine both her race and her class.
Ursidae are physically strong and requires a high physical strength.
The vocation of mechanic needs to be smart and requires a high intelligence. 

// new table attributes of attributes
// update this table for all races.
include::ROOT:partial$CH03_Table_attributes_of_attributes.adoc[]


// discuss reason for random
// offer other dice ranges 
// offer point system



The attributes are not listed in any particular order.
The values of the attributes are equivalent between the races. 

== Generating the Attributes
Each attribute is generated by rolling dice.
What dice are used depends on the persona's race.
Anthros roll attributes using 3d6.
Anthro attributes have the the classic bell curve.
Aliens roll their attributes on 4d6 or more.
Alien attributes range wildly.
Robot attributes are rolled on a 1d4.
This level is then converted into typical attributes.

The value of an attribute is equivalent amongst the races.
A physical strength of 12 is the same between an anthro, alien and robot.

== Attribute Limits
Most attribute tables work between 1 and 25.
Some attributes can drop below 1 and other can exceed 25.
This is not the same for all races though

=== Anthros 
Anthros tend to have attributes between 3 and 18.
This range can be exceeded by all attributes.
The most common values being in the middle of curve.
The attributes of CHA and HPS can drop below 1 for anthros.
If any other attribute drops below 1 (AWE, CON, DEX etc.) the persona is dead.

=== Aliens
Alien attributes range between 1 and 25.
Some alien attributes can exceed 25. 
PSTR tables reach up to 29. 
No alien attribute may drop below 1.
This results in the death of the alien. 
This includes the attribute of HPS

=== Robots
Robot attributes range between 1 and 25.
Some robot attributes can exceed 25. 
PSTR tables reach up to 29.
No robotic attribute can fall below 1.
This results in the destruction of the robot.
Robot attributes decrease with damage.
HPS for robots are quite unique. 
