= Social Standing (SS)

:art: sociabilityfield.png
:width: 250px
:snark: Honey attracts more flies.
:artist: Mike Jackson
:date: 1990
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Social Standing is not a physiologic attribute and just barely finds its place in the attributes chapter.
Social Standing (SS) indicates where persona is socially oriented in their society and how much power they tend to have.
A high social standing is synonymous with wealth and power.
Social Standing is generated with a kilo-die roll.
The higher the roll, the greater the social standing.
What form this social standing takes (famous celebrity, corporate power, or bureaucratic influence) is up to the ref and the milieu of the campaign.
The social standing is of great importance to the persona class nothing.
The persona's CHA attribute is added to the Social Standing kilo-die roll.

// brand new table for version 6.0
.*Social Standing by Family*
[width="75%",cols="<,<,<,<"]

|===

|
s|Anthro
s|Robot
s|Alien

s|Die Roll
|1d1000
|1d1000
|1d1000

s|Range
|1-1000
|1-1000
|1-1000

|
s|Anthro
s|Robot
s|Alien
|===