= Anthros
		
[quote]
____
*Anthros are humanoid life forms with animal appearances.*
____

All anthros are upright, bipedal.
They have hands, heads and faces.
In the fake taxonomy of life in EXP Anthros are in the family Hominidae, and the genus homo.
Anthros are further differentiated by types.
Each anthro type is considered a species with names like homo avis, or homo felis.
A homo felis (feline) would be further differentiated as a cat, lion or cougar.
The final appearance of the anthro type is chosen by the player.

== Anthro Delivery Checklist

. xref:CH04_Anthros_Attributes.adoc[Generate Attributes]
.. xref:CH03_AttributesMSTR.adoc#adjustmstr[Adjust MSTR, window="_blank"]
. xref:CH04_Anthros_Type.adoc[Choose Anthro Type]
.. xref:CH03_AttributesCON.adoc#_damage_system_shock_dss[Record DSS, window="_blank", title="DSS is optional"]
.. xref:CH03_AttributesCON.adoc#_recovery_roll_rec[Record REC, window="_blank", title="REC is optional"]
.. xref:CH03_AttributesDEX.adoc#moverate[Record Move, window="_blank"]
.. xref:CH03_AttributesHPS.adoc#_anthro_hit_points_calculation[Record HPS, window="_blank"]
.. xref:CH03_AttributesMSTR.adoc#adjustmstr[Adjust MSTR if INT changed, window="_blank"]
.. xref:CH03_AttributesPSTR.adoc#_wate_allowance[Record WA, window="_blank"]
. xref:CH07_Mutating.adoc[Mutation Check]
. xref:CH08_Vocations_.adoc[Vocation]
. xref:CH10_Incidentals.adoc[Incidentals]
. xref:iv-hardware:An_index_hardware.adoc[TOY Check]
. xref:ii-non_combat_rules:CH14_Performance_Tables.adoc[Performance Tables]
. xref:iii-combat_rules:CH09_Combat_Tables.adoc[Combat Tables]
. *Have fun!*

Creating personas in EXP can be completely random.
It is the expectation throughout this document that everything is randomly generated.
This is not a requirement and players are free to choose their anthro type.
This choice is up to the referee and players in the game.  

== Anthro Discussion
EXP is extremely open to creative interpretation. 
However there are limitations to what an anthro persona can be.
Let’s consider a player who has a canine (dog) anthro persona.
The player can choose a dog type that suits her fancy.
This could be a husky, a poodle, a golden or a mutt.
Both the canine and dog type are purely descriptive.

The hite, wate, and abilities of the persona are determined by the type canine.
The dog type is cosmetic.
A chihuahua will *NOT* automatically be tiny, anxious, and yappy. 
The canine type will determine the hite and wate.
The vocation will determine the skill set.
The player chooses the disposition.


After much deliberation, the player chooses that her canine persona will have the likeness of a bulldog.
The persona’s head will have the gnarled features and folded jowls characteristic of a bulldog.
The skin would consist of a coat of short hair, typically found on bulldogs.
She would also have stocky upper shoulders and powerful looking arms (which end in stubby paw-like hands).
Her persona would stand upright on two fur covered legs which are topped off in a stubby tail.
Such descriptions would be analogous for other families, like florians – bark for skin, fungus for hair; or insectoids – a buggy-eyed fly’s head atop a bipedal exoskeleton.

The descriptions are as far as the similarities go.
Insectoid personas cannot lift 1000 times their own wate.
Reptiles do not automatically get poisonous bites.
Avarians aren’t all gifted with flight.
The anthro families have no special abilities other than those described in this chapter.
However, each racial type does have specific features which add to the character of the persona.

It may seem provincial and humancentric to have all the families bipedal, earthbound humanoids.
Such a attitude can be pseudo-scientifically defended on the grounds that there are definite biological advantages to evolving bipedal.
Regardless of how the referee defends this humanoid preference, the form has primarily been chosen for the obvious advantages it yields to role-playing.


Maintaining a standard of humanoid form allows for a great variety of families which are all readily suited to EXP technology and rules.
This means the game can be easily played with few rule changes for one family to another.
This allows the referee to make preparations without having to make exceptions and special rulings for each family.

The constant humanoid shape of the families can be more easily adapted to by the players.
This gives beginners and experienced players alike the ability to role-play without having to worry about being a quadruped, having treads instead of legs or being shaped like an amoeba.
The truly alien non-humanoids are covered in robots and aliens

How the different families arose allows for many avenues of thought.
Each one could have evolved from a lesser species (as humans evolved from apes); they could be peculiarly mutated forms of humans; they could be surviving progeny of long lost cloning experiments; or they could be a unique collection of beings, each divinely created by a superior deity (like Adam and Eve).

Inquisitive players may force a referee to answer more complex question like:
How do all the families appear in the same place?
Why are they humanoid?
Do androids dream of electric sheep?
The answers to such questions may be included in the initial campaign background or may even be woven into the goal of the campaign itself.
