= Anthro Mutations

:art: mutation_inducing.png
:width: 250px
:snark: Let's mutate now!
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

// need explanation of defects

Mutations in EXP are science fantasy DNA changes that create special abilities.
Mutations are randomly acquired major changes to the anthro's DNA.
The anthro mutation story is deeply rooted in science fiction.

In reality biological mutations are universally fatal.
It is impossible for a referee to scientifically explain this mutation process.
Mutation explanation is relegated to the 'black box' category in EXP. 
However, a fun pseudo-scientific explanations adds to the story of the campaign. 
The meat, metal and metamorphosis of mutations is in the section xref:vi-mutations:An_index_mutations.adoc[Mutations]

== Mutation Chance
Every player must check to see if their persona mutates.
Anthro mutation frequencies are determined by their anthro type.
Humanoids are much more likely to mutate than insectoids.
The player rolls against the table and records the number of each mutation type.
Then heads over to xref:vi-mutations:An_index_mutations.adoc[Mutations] to generate them.

.Mutation Chance Notes
* player wants a mutant *double chance*
* player does NOT want a mutant *zero chance*
* Humanoid type can choose 100% chance to mutate
* Pure Strains cannot have a mental mutation defect
* 1;repeat = check again after a success

include::ROOT:partial$CH04_Table_anthro_mutations.adoc[]