= Anthros
		
[quote]
____
*Anthros are humanoid life forms with animal appearances.*
____

All anthros are upright, bipedal and have hands, heads and faces.
In the fake taxonomy of life in EXP Anthros are in the family Hominidae, and the genus homo.
Anthros are further differentiated by types.
Each anthro type is considered a species with names like homo avis, or homo felis.
A homo felis (feline) would be further differentiated as a cat, lion or cougar.
The final appearance of the anthro type is chosen by the player.

Creating personas in EXP can be completely random.
It is the expectation throughout this document that everything is randomly generated.
This is not a requirement and players are free to choose their anthro type.
This choice is up to the referee and players in the game.  

== Anthro Limitations

EXP is extremely open to creative interpretation. 
However there are limitations to what an anthro persona can be.
Let’s consider a player who has a canine (dog) anthro persona.
The player can choose a dog type that suits her fancy.
This could be a husky, a poodle, a golden or a mutt.
Both the canine and dog type are purely descriptive.

The hite, wate, and abilities of the persona are determined by the type canine.
The dog type is cosmetic.
A chihuahua will *NOT* automatically be tiny, anxious, and yappy. 
The canine type will determine the hite and wate.
The vocation will determine the skill set.
The player chooses the disposition.


After much deliberation, the player chooses that her canine persona will have the likeness of a bulldog.
The persona’s head will have the gnarled features and folded jowls characteristic of a bulldog.
The skin would consist of a coat of short hair, typically found on bulldogs.
She would also have stocky upper shoulders and powerful looking arms (which end in stubby paw-like hands).
Her persona would stand upright on two fur covered legs which are topped off in a stubby tail.
Such descriptions would be analogous for other families, like florians – bark for skin, fungus for hair; or insectoids – a buggy-eyed fly’s head atop a bipedal exoskeleton.

The descriptions are as far as the similarities go.
Insectoid personas cannot lift 1000 times their own wate.
Reptiles do not automatically get poisonous bites.
Avarians aren’t all gifted with flight.
The anthro families have no special abilities other than those described in this chapter.
However, each racial type does have specific features which add to the character of the persona.

It may seem provincial and humancentric to have all the families bipedal, earthbound humanoids.
Such a attitude can be pseudo-scientifically defended on the grounds that there are definite biological advantages to evolving bipedal.
Regardless of how the referee defends this humanoid preference, the form has primarily been chosen for the obvious advantages it yields to role-playing.


Maintaining a standard of humanoid form allows for a great variety of families which are all readily suited to EXP technology and rules.
This means the game can be easily played with few rule changes for one family to another.
This allows the referee to make preparations without having to make exceptions and special rulings for each family.

The constant humanoid shape of the families can be more easily adapted to by the players.
This gives beginners and experienced players alike the ability to role-play without having to worry about being a quadruped, having treads instead of legs or being shaped like an amoeba.
The truly alien non-humanoids are covered in robots and aliens

How the different families arose allows for many avenues of thought.
Each one could have evolved from a lesser species (as humans evolved from apes); they could be peculiarly mutated forms of humans; they could be surviving progeny of long lost cloning experiments; or they could be a unique collection of beings, each divinely created by a superior deity (like Adam and Eve).

Inquisitive players may force a referee to answer more complex question like:
How do all the families appear in the same place?
Why are they humanoid?
Do androids dream of electric sheep?
The answers to such questions may be included in the initial campaign background or may even be woven into the goal of the campaign itself.

== Anthro Persona Generation

. <<_attributes,Attribute Generation>> 
.. <<_adjusting_attributes_by_attribute,Attributes adjust attributes>>
.. Record attributes
.. Record movement rate
. <<_anthro_type_selection,Anthro Selection>>
.. <<_attributes_adjustments,Adjust Attributes>>
.. <<_age,Age>> 
.. <<_hite_and_wate,Hite and Wate>>
. xref::CH07_Mutating.adoc[Mutations]
. xref::CH08_Vocations_.adoc[Vocations]
. xref:CH10_Incidentals.adoc[Incidentals]
. Roll TOYS
. xref:ii-non_combat_rules:CH14_Performance_Tables.adoc[Performance Tables]
. xref:iii-combat_rules:CH09_Combat_Tables.adoc[Combat Tables]
. *Have fun!*

== Attributes

Anthro attributes are generated randomly and added to the persona record sheet.
Attributes determine both the physical abilities and type of the anthro persona. 
Randomly determining anthro attributes is based on rule set legacy and game balance.
Using multiple die to generate the random numbers creates more organic ability curves.
The weak and strong are outliers. 

Many role playing games have different mechanisms for determining persona attributes. 

// brand new table for version 6.0
.*Anthro Attribute Generation*
[width="75%",cols="<,<,<"]

|===
3+<|Randomly determine the anthro attributes.

s|Attribute
s|Abbreviation
s|Die Roll

|Awareness
|AWE
|3d6

|Charisma
|CHA
|3d6

|Constitution
|CON
|3d6

|Dexterity
|DEX
|3d6

|Intelligence
|INT
|3d6

|Mental Strength
|MSTR
|4d4

|Physical Strength
|PSTR
|3d6

|Hit Points
|HPS
e|Special

|Social Standing
|SS
|1d1000

s|Attribute
s|Abbreviation
s|Die Roll

|===

=== Alternate Generation Systems

It is easy enough to incorporate alternate generation systems.
Keep in mind that EXP is based on a system where 3 and 18 are rare attribute scores. 
Bonuses and penalties in EXP reflect anthro attributes based on this.
The frequency of powerful vocations are checked by using the strict 3d6 method.
The referee and players should choose the approach that works best for them.
Don't let rules get in the way of the story or the fun.

==== Drop the lowest

Drop the lowest is a simple enough mechanism for increasing anthro attributes.
Players roll 4d6 and drop the lowest die roll. 
If a player were to roll 4, 3, 5, and 2 the 2 is dropped and the total is 12. 

The impact on the rule set of drop the lowest is astounding. 
Running python computer models with drop the lowest changed the game considerably. 
Expeditions are be composed of powerful spies and knites.
The rule set still works though and drop the lowest up to the players and referee.

For technical reasons Social Standing and HPS cannot be part of drop the lowest. 

==== Roll and assign

Roll and assign has the player roll 3d6 times and then assign the attribute score.
If a player were to roll 11, 15, 4, 16 etc.
She would next assign each score to an attribute.
Her persona could have a 16 DEX, a 15 INT and 4 CHA etc.

For technical reasons Social Standing and HPS cannot be part of roll and assign. 

==== Point system

Point systems become alarmingly complicated very rapidly.
In theory point systems allow players to create the persona they want.
However the amount of time spent couriering points around is time consuming.
It is likely more efficient to let players choose their type and vocation outright.
There is nothing wrong with this approach at all.
Don't let rules get in the way of story and fun.

A strict point assignment is based on a 3d6 system and totals 70 points.
A generous point assignment is based on 4d6 drop lowest and totals 91 points.
As players are smart and creative the referee will need assignment rules.
A few tips include: making CHA negative will not add points, anthro type minimum and maximums still apply, no attribute can be less than 3, and many more. 

For technical reasons Social Standing and HPS cannot be part of a point system.

== Adjusting Attributes by Attribute

// is this only MSTR and INT? if so SIMPLIFY

Several attributes are influenced by other attributes. 
For example, Mental Strength is improved by Intelligence. 
It is important to make the attribute adjustments as this can change the anthro type choices.

== Anthro Type Selection

Once an potential anthro's attributes have been generated choices must be made.
The player and referee go through the Anthro Type Attribute Requirements Table.
By comparing the generated attributes to this table a list of anthro types is created.
Each anthro type has a set of attribute minimums.
The persona must have attributes equal to or greater than the minimum.
Anthro type maximums do *NOT* apply when choosing an anthro type.

If the referee and player agree this step can be skipped and players can choose whatever anthro type they desire.
The corollary of this also applies. 
The referee can designate that all anthro types be the same. 
Don't let rules get in the way of story or fun.

//table 4.1
include::ROOT:partial$CH04_Table_anthro_attributes.adoc[]

=== Example Anthro Type Selection

A player has generated a persona with the following attributes:  AWE 6, CHA 15, CON 17, DEX 9, INT 14, MSTR 12, PSTR 6 AND HPS 42.
This player finds she may choose from avarian, florian, humanoid, insectoid, rodent and PSH (pure strain human).

//table 4.2
include::ROOT:partial$CH04_Table_anthro_type_selection.adoc[]

=== Attribute Minimums

Anthro attribute minimums have two purposes. 
1) organize anthro types based on physical abilities.
2) ensure a minimum attribute score for the anthro type.

How the anthro attribute minimums are used to select anthro types is detailed previously.
The restrictions ensure that hardy types have a high CON, that smart types have a high INT and that strong types have a higher PSTR.

The anthro attribute minimums are also protective of the persona being created.
Many defect mutations can reduce attribute scores. 
However, while creating a persona, an attribute score cannot drop below an minimum.
If a feline were to get the mutation Total Carapace, her CHA could not drop below 8.
Total Carapace has an armour rating benefit and CHA penalty of -4.
This applies to anything that would drop a persona's attribute during persona creation.

Once in game play the persona attributes are no longer protected by attribute minimums.
In game play attributes can be decreased by aging, mutations or special damage.
If a persona's CHA drops because of burns, or her PSTR drops because of aging or her INT drops because of brain damage the attribute minimums will not limit the attribute’s decline.
This can result in persona attributes permanently dropping and even killing a persona.

=== Attribute Maximums

Anthro type attributes are a legacy element and are not applied to personas during generation or game play.

== Anthro Type Data

Once the player has chosen her persona's anthro type it is recorded on the persona record.
Each anthro type has some defining features which are detailed on their respective anthro data sheets.
Each data sheet includes attribute adjustments, Age, Hite, and Wate. 
Many anthro types have special abilities that are described in the body of each anthro type's section.

// Table 4.16 Ursidae Data
.*Ursidae Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|The bare facts to create an ursidae player persona.

s|Attribute Minimums
2+<|DEX 4; INT 4; PSTR 12

s|Attribute Adjustments
2+<|CON +1; INT -2; PSTR +2

s|Age
2+<|9-12 (1d4+8) years
s|Abilities
2+<|Hibernation, Frenzy


s|Size
s|Hite (cm)
s|Wate (kg)

|Large
|176+(2d20)-20
|78

|Larger
|208+(2d20)-20
|139

3+<| <<_hite_and_wate,How to calculate Hite and Wate>>

|===

=== Attribute Minimums

This is a refresher showing what the minimum attributes for the anthro type are.
This is described in detail above under xref:_anthro_type_selection[Anthro Selection].
The required attributes for an ursidae are:  DEX 4, INT 4, and PSTR 12.  

=== Attribute Adjustments by Type

These are the adjustments made the persona’s attributes depending on their anthro type.
The ursidae persona would take an INT penalty of -2.
She would also enjoy a CON bonus of +1 and a PSTR bonus of +2.
This tends to make ursidae, strong, hardy, but not too smart
An anthro type attribute penalty cannot drop an attribute below the type attribute minimum.
These attribute adjustments are important because attributes influence a persona's choice of vocation.
These attribute changes are permanently recorded on the persona record. 

=== Age

Used to calculate the starting age of the persona in years.
Ages vary wildly from anthro type to anthro type. 
Most of the anthro ages fall into the young adult category.
In the case of an ursidae the player would roll 1d4 and add 8.
This generates an age between 9 and 12 in years.
The age is recorded on the persona record sheet.

=== Abilities
Special things that the particular anthro type can do. 
 
=== Hite and Wate

Hite is measured in centimeters (cm) and wate is recorded in kilograms (kg).
A centimeter is shy of half and inch.
A kilogram is slightly more than 2 pounds. 
In EXP hite and wate are slightly more representative than mere cm and kg.
They are both a pain in the butt to calculate.

Hite and wate often have two categories. 
The player may choose to be small or large. 
Gender does not determine hite or wate. 
It is merely a player's choice.

Below we will calculate the hite and wate of a large ursidae.
If you do not feel like doing math simply use the base hite and base wate of the persona. 
Don't let rules get in the way of story or fun.

==== Hite

The hite of the anthro is calculated using a base hite and a variation.
Each anthro type has a base hite.
The base hite is located to the left of the + sign.
The base hite is bolded below.

// Table 4.16 Ursidae Data
.*Find the Base Hite*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<| Base hite is highlighted: 176 cm

s|Size
s|Hite (cm)
s|Wate (kg)

|Large
|#176#+(2d20)-20
|78


|===

Hite variation is the located to the right of the + sign.

// Table 4.16 Ursidae Data
.*Find the Hite Variation*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<| The hite variation is highlighted : (2d20)-20 cm

s|Size
s|Hite (cm)
s|Wate (kg)

|Large
|176+#(2d20)-20#
|78


|===

The player rolls the variation and adds it to the base hite. 
In our example the player rolled 30 on the 2d20.
Subtracting 20 she arrives a variation of +10

=== Calculate Final Hite
.Base Hite + hite Variation = final Hite
****
The ursidae's base hite is 176 cm. The hite variation is +10 cm. So the persona's final hite is 186 cm.
****

==== Wate 

The wate of the persona is a pure calculation based on the hite of the persona.
The greater the hite the greater the wate. 

.*Find the Base Wate*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<| Base wate is highlighted: 78 kg

s|Size
s|Hite (cm)
s|Wate (kg)

|Large
|176+(2d20)-20
|#78#


|===

=== Calculate Wate Variation
.persona hite / base hite = wate variation
****
The persona's hite is 186. The persona's base hite is 176 cm. Division gives a wate variation of 1.05
****


=== Calculate Final Wate
.base wate * wate variation =  final wate
****
The base wate is 78 kg.  Multiplied by wate variation of 1.05 gives a final wate of 82 kg.
****


The player records the final hite and final wate on her persona record. 
She also wonders if it was worth all the arithmetic work.
Smiling, she remembers that numeracy is a worthy skill.
