= Humanoid

:art: humanoid.png
:width: 250px
:snark: Guerilla gardening.
:artist: Peggy Lynn McIsaac
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

// Table 4.11 Humanoid Data
.*Humanoid Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|All the deets for humanoid treats

|Attribute Minimums
2+<|CHA -9

s|Attribute Adjustments
2+<|CHA -2

s|Age
2+<|13-18 (12+1d6) years

s|Abilities
2+<|<<_mutability,Mutability>>

s|Size
s|Hite (cm)
s|Wate (kg)

|Small
|169+(2d20)-20
|62

|Large
|176+(2d20)-20
|71

3+<| xref:CH04_Anthros.adoc#_hite_and_wate[How to calculate Hite and Wate]

|===

Humanoids is short for Hominidae Homo Mutabilis.
Humanoids can appear as any hominid type.
Humanoid can appear as: simians (monkeys, apes), suidae (pigs, boars), elves, dwarfs, orcs, Human Beings etc.
Humanoids resembling Humans can sport any colour: white, black, red, yellow, green, blue, etc.
None of these humanoid types have any of their mythical abilities.
Humanoids that resemble elves or leprechauns would have none of their mythical abilities.

== Mutability
Homo Mutabilis has no abilities other than their extreme susceptibility to mutation.
If a player wants her Humanoid to mutate the persona automatically will. 

