= Avarian

:art: avarian.png
:width: 250px
:snark: Birds of a feather.
:artist: Peggy Lynn McIsaac
:date: 1990
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

// Table 4.6 Avarian Data
.*Avarian Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|Particulars for hatching an avarian player persona.

s|Attribute Minimums
2+<|AWE 12; CON 10; DEX 10

s|Attribute Adjustments
2+<|AWE +3; CON -1; DEX +2; PSTR -2

s|Age
2+<|13-16 (1d4+12) years

s|Abilities
2+<|<<_flying,Flying>>, <<_ambush_detection,Ambush Detection>>

s|Size
s|Hite (cm)
s|Wate (kg)


|Small
|175+(3d10)-20
|65

|Large
|175+(2d20)-40
|71

3+<| xref:CH04_Anthros.adoc#_hite_and_wate[How to calculate Hite and Wate]

|===


Avarian is the short name for Hominidae Homo Avis.
Avarians are humanoid bird people.
Avarians are not humans with wings.
An avarian persona can choose from many avian life forms.
For example: hawk, parrot, albatross, ostrich, penguin, vulture, swallow, puffin, robin, etc.
The persona remains a bipedal humanoid.
An avarian would have two legs, two arms a torso and a face.
Avarians usually have beaks for mouths, feathers for hair, down covered skin.

The player can choose for her persona to have decorative wings.
Decorative wings stick out of her back and are *not* functional.
Decorative wings do not inhibit the function of the persona at all.
A set of decorative wings would comfortably fold into armour.

== Wings

Avarians are generally wingless. 
If a player does not want her persona to have wings there will be no wings.
The player can choose to have wings.
Any persona can choose to have decorative wings.
There are also full wing sets and functional wing sets.
Full and functional wing sets are randomly determined.
An avarian can only have one set of wings.

=== Decorative
The player can choose for her persona to have decorative wings.
Decorative wings protrude from the back of the torso and are *not* functional.
Decorative wings do not inhibit the function of the persona at all.
A set of decorative wings would comfortably fold into armour.

=== Full Wings
If a player wants her persona to have full wings she may roll the dice.
There is a 5% chance per point of CHA that the persona will have full wings.
So a persona with CHA 12 would have a 60% chance having full wings.

Full wing sets require the persona to modify her clothing and armour.
Full wings are not functional wings and do not allow for flight.
Persona's with full wings are still flightless. 
To fly a persona must have functional wings.

The avarian still has arms and the full wings protrude from the back.
The full wings to not count as a set of extra limbs.
The persona can create a breeze and swat things with their full wings.
Creativity and Sphincter Dice will determine how much can be accomplished with full wings.

An avarian with a full wing set gets bonus of CHA +2. 

=== Functional Wings
If a player wants her persona to have functional wings she must first have full wings.
So if a persona does not have full wings she cannot have functional wings.
There is a 1% chance per point of DEX that the persona will have functional wings.
So a persona with DEX 12 would have a 12% chance having functional wings.
A set of functional wings allow the persona to fly.

== Flying
A flying persona is a major challenge for the referee. 
The chance of having a flying avarian is kept low for that reason.
If the referee and players want all avarians to fly and have wings that is fine.

TIP: Do not let rules get in the way of the story and fun. 

Avarians with fully functional wings can fly.
Flying allows the persona flit about and hover in the air.
The persona can fly at up to double her movement rate..
Functional wings impair walking and a she walks at half her movement rate.
A persona with a Move of 6 h/u would fly at 12 h/u and walk at 3 h/u. 

Flying offers no benefit in zero gravity or underwater.
The functional wings only perform in an atmosphere and up to 1.5 times gravity.

== Ambush Detection
Avarians are flighty, nervous and aware of their surroundings.
This makes them hard to ambush.
When detecting ambush an avarian triples her AWE. 
This makes ambushing an avarian a difficult task indeed.

