= Anthro Armour Rating

Personal body armour is a perverse form of self-defense.
It is designed to protect someone who cannot, or will not, avoid combat situations.
It is as much an instrument of violence as any weapon.
The best way to avoid taking damage from combat is to avoid combat, but many personas happily wade into any altercation they can find or create.The body armour described in this chapter is mundane, or non-artifact, armour.

Artifact armour is described in xref:iv-hardware:CH42_Armour.adoc[Armour], and includes things like force fields, laser reflection, and powered armour.
Mundane armour is not as exciting as artifact armour, and it is usually cumbersome, uncomfortable and difficult to put on.

== Calculate Anthro Armour Rating
// tag::Anthro_AR[]
.AR = 500 + 6 * DEX
****
A persona with a 12 DEX score would have an AR of 572.
****
// end::Anthro_AR[]

The armour rating (AR) s a universal measurement of how difficult something is to hit.
An anthro persona with a DEX attribute of 15 and not wearing any armour would have a natural armour rating (AR) of 590.