= Anthro Attributes

Anthro attributes are generated randomly and added to the persona record sheet.
Attributes determine both the physical abilities and type of the anthro persona. 
Randomly determining anthro attributes is based on rule set legacy and game balance.
Using multiple die to generate the random numbers creates more organic ability curves.
The weak and strong are outliers. 

Many role playing games have different mechanisms for determining persona attributes. 

// brand new table for version 6.0
.*Anthro Attribute Generation*
[width="75%",cols="<,<,<"]

|===
3+<|Randomly determine the anthro attributes.

s|Attribute
s|Abbreviation
s|Die Roll

|Awareness
|AWE
|3d6

|Charisma
|CHA
|3d6

|Constitution
|CON
|3d6

|Dexterity
|DEX
|3d6

|Intelligence
|INT
|3d6

|Mental Strength
|MSTR
|4d4

|Physical Strength
|PSTR
|3d6

|Hit Points
|HPS
e|Special

|Social Standing
|SS
|1d1000

s|Attribute
s|Abbreviation
s|Die Roll

|===

== Alternate Generation Systems

It is easy enough to incorporate alternate generation systems.
Keep in mind that EXP is based on a system where 3 and 18 are rare attribute scores. 
Bonuses and penalties in EXP reflect anthro attributes based on this.
The frequency of powerful vocations are checked by using the strict 3d6 method.
The referee and players should choose the approach that works best for them.
Don't let rules get in the way of the story or the fun.

=== Drop the lowest

Drop the lowest is a simple enough mechanism for increasing anthro attributes.
Players roll 4d6 and drop the lowest die roll. 
If a player were to roll 4, 3, 5, and 2 the 2 is dropped and the total is 12. 

The impact on the rule set of drop the lowest is astounding. 
Running python computer models with drop the lowest changed the game considerably. 
Expeditions are be composed of powerful spies and knites.
The rule set still works though and drop the lowest up to the players and referee.

For technical reasons Social Standing and HPS cannot be part of drop the lowest. 

=== Roll and assign

Roll and assign has the player roll 3d6 times and then assign the attribute score.
If a player were to roll 11, 15, 4, 16 etc.
She would next assign each score to an attribute.
Her persona could have a 16 DEX, a 15 INT and 4 CHA etc.

For technical reasons Social Standing and HPS cannot be part of roll and assign. 

=== Point System

Point systems become alarmingly complicated very rapidly.
In theory point systems allow players to create the persona they want.
However the amount of time spent couriering points around is time consuming.
It is likely more efficient to let players choose their type and vocation outright.
There is nothing wrong with this approach at all.
Don't let rules get in the way of story and fun.

A strict point assignment is based on a 3d6 system and totals 70 points.
A generous point assignment is based on 4d6 drop lowest and totals 91 points.
As players are smart and creative the referee will need assignment rules.
A few tips include: making CHA negative will not add points, anthro type minimum and maximums still apply, no attribute can be less than 3, and many more. 

For technical reasons Social Standing and HPS cannot be part of a point system.
