= Pure Strain Human

:art: pure_strain.png
:width: 250px
:snark: Pure strain teaching biology.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

// Table 4.13 PSH Data
.*Pure Strain Human Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|Pure Strain Human info.

s|Attribute Minimums
2+<|Nil

s|Attribute Adjustments
2+<|CHA +3
 
s|Age
2+<|13-18 (1d6+12) years 

s|Abilities
2+<|Nil 

s|Size
s|Hite (cm)
s|Wate (kg)

|Small
|169+(2d20)-20
|62

|Large
|176+(2d20)-20
|71

3+<| xref:CH04_Anthros.adoc#_hite_and_wate[How to calculate Hite and Wate]

|===

Pure strain humans (PSH) are Homo Sapiens.
PSH are the collection of Hominidae which inhabit this planet Earth.
The term pure strain refers to their lack of fun science fantasy mutations or diseases of any sort.
Pure Strains can choose from any skin colour: black, blue, white, green, yellow, red, gold, etc.
Pure Strains possess none of the mythical strengths or weaknesses from unpopular culture.

There is a small chance a pure strain may catch a mental mutation.
If this happens the mutation cannot have any external affects and cannot be a defect.
If the player does not want her pure strain to have a mutation the persona cannot be forced to have one. 


