= Anthro Type Selection

Once an potential anthro's attributes have been generated choices must be made.
The player and referee go through the Anthro Type Attribute Requirements Table.
By comparing the generated attributes to this table a list of anthro types is created.
Each anthro type has a set of attribute minimums.
The persona must have attributes equal to or greater than the minimum.
Anthro type maximums do *NOT* apply when choosing an anthro type.

If the referee and player agree this step can be skipped and players can choose whatever anthro type they desire.
The corollary of this also applies. 
The referee can designate that all anthro types be the same. 
Don't let rules get in the way of story or fun.

//table 4.1
include::ROOT:partial$CH04_Table_anthro_attributes.adoc[]

== Attribute Requirements
Anthro attribute minimums have two purposes. 
1) organize anthro types based on physical abilities.
2) ensure a minimum attribute score for the anthro type.

How the anthro attribute minimums are used to select anthro types is detailed previously.
The restrictions ensure that hardy types have a high CON, that smart types have a high INT and that strong types have a higher PSTR.

The anthro attribute minimums are also protective of the persona being created.
Many defect mutations can reduce attribute scores. 
However, while creating a persona, an attribute score cannot drop below an minimum.
If a feline were to get the mutation Total Carapace, her CHA could not drop below 8.
Total Carapace has an armour rating benefit and CHA penalty of -4.
This applies to anything that would drop a persona's attribute during persona creation.

Once in game play the persona attributes are no longer protected by attribute minimums.
In game play attributes can be decreased by aging, mutations or special damage.
If a persona's CHA drops because of burns, or her PSTR drops because of aging or her INT drops because of brain damage the attribute minimums will not limit the attribute’s decline.
This can result in persona attributes permanently dropping and even killing a persona.

== Example Anthro Type Selection
A player has generated a persona with the following attributes:  AWE 6, CHA 15, CON 17, DEX 9, INT 14, MSTR 12, PSTR 6 AND HPS 42.
This player finds she may choose from avarian, florian, humanoid, insectoid, rodent and PSH (pure strain human).

//table 4.2
include::ROOT:partial$CH04_Table_anthro_type_selection.adoc[]

== Explaining Anthro Delivery Data
Once the player has chosen her persona's anthro type it is recorded on the persona record.
Each anthro type has some defining features which are detailed on their respective anthro data sheets.
Each data sheet includes attribute adjustments, Age, Hite, and Wate. 
Many anthro types have special abilities that are described in the body of each anthro type's section.

// Table 4.16 Ursidae Data
.*Ursidae Delivery Data*
[width="75%",cols="<,<,<",frame="all"]
|===
3+<|The bare facts to bear an ursidae player persona.

s|Attribute Minimums
2+<|DEX 4; INT 4; PSTR 12

s|Attribute Adjustments
2+<|CON +1; INT -2; PSTR +2

s|Age
2+<|9-12 (1d4+8) years
s|Abilities
2+<|Hibernation, Frenzy

s|Size
s|Hite (cm)
s|Wate (kg)

|Large
|176+(2d20)-20
|78

|Larger
|208+(2d20)-20
|139

3+<| <<_hite_and_wate,How to calculate Hite and Wate>>

|===

=== Attribute Minimums
This is a refresher showing what the minimum attributes for the anthro type are.
The required attributes for an ursidae are:  DEX 4, INT 4, and PSTR 12.  

=== Attribute Adjustments
These are the adjustments made the persona’s attributes depending on their anthro type.
The ursidae persona would take an INT penalty of -2.
She would also enjoy a CON bonus of +1 and a PSTR bonus of +2.
This tends to make ursidae, strong, hardy, but not too smart
An anthro type attribute penalty cannot drop an attribute below the type attribute minimum.
These attribute adjustments are important because attributes influence a persona's choice of vocation.
These attribute changes are permanently recorded on the persona record. 

=== Age
Used to calculate the starting age of the persona in years.
Ages vary wildly from anthro type to anthro type. 
Most of the anthro ages fall into the young adult category.
In the case of an ursidae the player would roll 1d4 and add 8.
This generates an age between 9 and 12 in years.
The age is recorded on the persona record sheet.

=== Abilities
Special things that the particular anthro type can do. 
 
=== Hite and Wate
Hite is measured in centimeters (cm) and wate is recorded in kilograms (kg).
A centimeter is shy of half and inch.
A kilogram is slightly more than 2 pounds. 
In EXP hite and wate are slightly more representative than mere cm and kg.
They are both a pain in the butt to calculate.

Hite and wate often have two categories. 
The player may choose to be small or large. 
Gender does not determine hite or wate. 
It is merely a player's choice.

Below we will calculate the hite and wate of a large ursidae.
If you do not feel like doing math simply use the base hite and base wate of the persona. 
Don't let rules get in the way of story or fun.


