= Robot Defensive Systems
Defensive systems can be anything that makes the robot harder, to hit, damage or control.
Robot defences can be malfunctioning peripherals used as a defence in combat.
However most are hardenings that protect the robot while doing its work.

Unlike the convoluted attack tables there is only one Defensive Systems Table.
Each robot type has clear direction on how to approach this table. 
Some robots have no roll on Defensive Systems.
Others are designated multiple rolls.  

include::ROOT:partial$CH05_Table_Robotic_Defences.adoc[]

== Anti-Missile
This defensive system protects the robot from flying attack.
The defence could be a baked in defense or a peripheral being used creatively.
Anti-missile is a combination of evasive actions, hardened casing and flechette. 
Any ranged attack can be thwarted by this defence.
This includes: type B weapons, guided bombs, missiles, grenades, rockets or directed aerosols.
The defence does not work against powered small arms attacks like guns or crossbows (type C).

The robots AR is increased by 50 to 300 (50d6 or 1d6 times 50) against missile attacks.
If the to hit roll fails the robot has destroyed the incoming attack. 
This will negate any area of effect damage that the missile could have delivered.

A successful to hit roll will limit the damage to area of effect damage.
Any damage delivered will be cut in half.

== Anti-Personnel
Designed to remove clamouring parasites or grappling hordes.
The mechanism of the anti-personnel device is chosen by the player.
The player can choose the nature of the noxious anti-personnel attack.
For example, electric shock, sonic attack, flames, shrapnel, or cotton candy webs.
Regardless of the appearance of the defence all types will function the same.

Anti-personnel affects targets touching the robot or in the robot's immediate area.
The defence has no effective range.
The anti-personnel does not attack immobilized or incapacitated targets.
The player rolls 3d6 each time the defence is activated.
When activated the player can choose between lethal or non-lethal defence.

=== Lethal Anti Personnel
As a lethal defence every organic target with the limited range takes damage.
No to hit roll is necessary as this is an area of effect attack.
The close proximity attackers must make a saving throw versus pain.
The intensity of the attack is equal to the damage delivered. 
A failed saving throw will cause them to fall back at least one hex from the robot.

=== Non Lethal Anti-Personnel
The none lethal version of this defence effects every organic target within range.
While no damage is done the target automatically falls back from the robot in pain.
The referee may allow player persona's a saving throw versus pain to stay on the robot.
If the player persona successfully stays on the robot they will take 3-18 (3d6) HPS of damage.

When using non-lethal anti-personnel the robot can move freely through riotous swarm.

== Increase AR
The increase in armour rating could be chassis hardening, evasive maneuvers, or some combo.
The armour rating of the robot increases by 50 to 300 (1d6 times 50).
The effects of this defence are cumulative. 
Multiple visits to this defence increases the AR each time.
This can lead to armour ratings well above the robot's base of 700.

== Artifact Armour
This robot's hull is replaced by fancy armour from xref:iv-hardware:CH42_Armour.adoc[Armour]
The robot could be covered in relfec, ballistic, a force field, or even powered armour.
There is a limitation on the armour type.
The armour type cannot make the robot weaker.
For example, the armour rating cannot drop below 700.

== Camouflage
Often the best defence is being able to hide.
The defence is combination of colouring and structural changes that allow the robot to blend in.
The robot can camouflage against any type of sensor that it has.
A robot with radar and video sensors could camouflage against radar and video.
This would make it essentially invisible to those types of vision.
This is a defensive skill and does not offer any bonus for ambush. 
A persona will only detect this robot if she is actively searching the area.

== Detect ambush
This defence makes it very difficult to surprise this robot.
The robot is four times more likely to detect something detrimental to it.
The persona's AWE score is quadrupled (times 4) when detecting an ambush
The defence includes active and passive ambush situations. 
A robot with AWE 12 would use an AWE 48 detecting mines, trip wires or traps.

== Diffuse Bombs
This robot is a demolitions demolishing expert.
The robot has both the technical and mechanical skills to defuse all types of bombs.
The robot functions as a 5th level mechanic, plus the robot's EXPS level when diffusing bombs.
When using the Mechanic PT roll the persona doubles her INT score when diffusing bombs. 
This defence does not assist the robot in planting or making bombs.

== Evasive action
Allows the robot to avoid combat situations entirely, providing it is not engaging combat itself.
This is essentially a computerized tactical withdrawal mode.
It allows the robot to move at normal through mine fields, tank traps, phalanx of soldiers and other such detriments to escape.
Each time the robot encounters an escape obstacle, it can avoid it with a d20 DEX roll.
No robot can attack while employing this defence (unless it is a combat robot).

== Force Field
This is the classic science fantasy defensive force field.
The force field will absorb any HPS in damage that should be taken by the robot.\
A force field will be able to absorb 25 to 100 HPS of damage (1d4 times 25).
Multiple force fields are added together and function as a single device.
The force field will shut down for 1 minute per HPS absorbed once depleted.

== Increase HPS
This robot just increased it's ability the take damage.
Increasing HPS makes the robot a bit tougher
Each time Increase HPS is visited the HPS are increased. 
The effect is cumulative.
The robot's HPS are increased by 10% to 60% (d6 times 10%).
A robot with 100 HPS and an increase HPS of 30% would have 130 HPS.

== Mental mutation
This robot has a peripheral that has the same effect as a mental mutation.
The defence could be a baked in defense or a creatively used peripheral malfunction.
The player makes  a jump to xref:vi-mutations:CH58_Mental.adoc[Mental Mutations].

The mutation should be a defensive mutation.
The player may spend some time at xref:vi-mutations:CH58_Mental.adoc[Mental Mutations] rolling and rolling.
If the player wishes to roll a completely random mutation instead then so be it.
The robot cannot have a defective mutation under any circumstances. 
The robot cannot have a purely attack mental mutation.
When attacking the robot uses her INT instead of her MSTR.

== Override interrupt
The robot is immune to robotic override.
The defence protects against attempt to make her subservient.
The referee may feel that a global defence to robotic override is too powerful.
If this is the case this robot can triple her INT vs robotic override and can check 3 times more often 
