= Android (A)

include::ROOT:partial$CH05_Table_Android.adoc[]

Androids are the elite of the robotic world;
they are in a class all their own.
An android is a robotic likeness of the base race that designed the bot.
Except for the intense scrutiny of a veterinarian, most androids are indistinguishable from the base race.
Androids are very independent robots and are manufactured with a very high level of self-determined free will.
From a robotics stand point, this makes them very dangerous.

Androids are generated like regular personas;
the major difference is that they cannot choose their race nor their class.
The androids race is determined by a roll on the _Robotic Base Race_ table.
The android will appear to have the age, sex, hite and wate of the race rolled on that table.
To get all the pertinent information, the player may have to refer to http://expgame.com/?page_id=101[Chapter 4: Anthropomorphs].
The class of the persona can be chosen by the player but, if the referee wishes, she may force the player to roll the androids class on the _Referee Persona Class_ table in Chapter 8.
HPS for androids are determined the same as other humanoid personas.
An android is a formidable opponent and having an android spy or mercenary may seriously jeopardize the balance of the campaign.
Andys get a percentage chance equal to their INT to have a hidden random peripheral (Table . Even though innocently pursuing regular classes and lives, the unique origins of androids should never be forgotten.
The Robotic Base Race Table is included here out of turn for your convenience (thanks copy/paste!).

include::ROOT:partial$CH05_Table_Robotic_Base_Anthro_Type.adoc[]