= Robot Size
The robot has a general descriptor of size. 
Size is used to determine the Hite and Wate of the robot.
The robot sizes: Tiny, Small, Medium, Large and Gigantic.
There are two other sizes not included for player personas.
These are Minute and Humungous. 
They only appear for referee personas.
The list of robot sizes are somewhat human relatable. 

== Wate
The Wate of a robot is the combination of mass and weight that is used by all personas in EXP.
A 100kg robot has the same Wate as a 100kg anthro.
Wate is very important to robots as it determines how much damage is when ramming.
Ramming is the only universal robotic attack.
The majority of player persona robots will be either Small, Medium or Large.
Player persona robots Wate is not adjusted by Tech Level. 

include::ROOT:partial$CH05_Table_Robotic_Size_Wate.adoc[]

== Hite
The Hite of the robot is measured in centimeters (cm).
Robot Hite can also represent the volume of the robot.
The referee and persona can decide how many times to roll on the Hite Table
If desired the player can roll three times: once for each of hite, width and length.
The dimensions can be arranged in whatever order works best for the persona.
If the robot dimensions are ruining a finely tuned player persona ignore them.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

include::ROOT:partial$CH05_Table_Robot_Dimensions.adoc[]
