= Combot

Each category of combat bot is covered individually below.
These bots are supposed to be only small, deadly combat drones;
not super-powered tanks that an entire campaign or game system could be based on.
All of these robots have somehow strayed from their commanders and most of them are being actively hunted by someone or something.
Their pursuers are usually a vengeful enemy, embarrassed opposition or corporate personnel trying to contain the out of control robot.
Often there will be some other combat bot, perhaps holding some grudge, that has decided to make pursuit of this combot its personal mission.

It must be stated that these combots are nothing more than wayward drones.
They are the dog-meat of mechanized massacre.
The combots are merely the tools of larger military machines or governments.
The combots covered here are all expected to have seen battle and be a little worse for wear  
though still substantially lethal.

Combots are exempt from the restriction that keeps a robot from allowing its base family to come to harm.
Any level of civility or responsibility on the battle field could jeopardize a combat robot so this feature is not included in their programming.


// Expendable combat robot Expendable combat robot

== Expendable Combot

:art: combot_expendable.png
:width: 250px
:snark: Expendable combot.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

//  Expendable Data 
.*Expendable Combot Fabrication Info (C-E)*
[width="75%",cols="2*<"]
|===
2+<|High casualty cannon fodder for peace keeping or worse. 

2+<|*Attributes*

|Ranges
|CON 2 or 4; DEX 4; INT 1 or 3; PSTR 4

|Minimums
|Nil

|Hit Points
|5 HPS per point of CON


|Adaptability
|15%

|Size
|Medium

|Value:
|1000000

2+<|*Systems*

|Offensive
|1 roll Table 1

|Defensive
|1 roll

|Peripheral
|1 Primary
|===

These bots are ex-reconnaissance, ex-officer aids, defunct spies or intelligent bombs.
Whatever they used to be, they are not that now and are wandering about on their own, free-lance.
Expendable combat robots can also drive military vehicles in combat situations other robots cannot.
This bot type has the advantage over all the others of being able to remember combat situations and other sensitive issues.

== Defensive Combot

// what? no defensive combot image FOR SHAME!!!

//  Defensive  Data 
.*Defensive Combot Fabrication Info (C-D)*
[width="75%",cols="2*<"]
|===
2+<|Protect the perimeter. 

2+<|*Attributes*

|Ranges
|CON 2, 4; DEX 4; INT 1, 3; PSTR 4

|Minimums
|CON 20 or greater

|Hit Points
|21-30 (1d10+20) per point of CON

|Adaptability
|1%

|Size
|Large

|Value:
|10000000

2+<|*Systems*

|Offensive
|1 roll Table 1

|Defensive
|1 per 3 points of CON

|Peripheral
|1 Primary
|===

To be a defensive bot, the persona must have a CON better than 20.
As the name indicates, these combots defend positions from enemy attack.
They get two specialized abilities granted only to defensive bots: The first is the ability to ceaselessly utter vile comments and insults about the enemy base family.
Second is the ability to analyze attacking enemy formations for offensive weaknesses.
The chance of effectively identifying such a weakness is equal to 4 times the defensive bots INT.
Defensive bots can also detect intruders up to a range of 10 hexes per point of AWE.

Another ability included within the given range is the bots Anti-anti-detection system.
The Anti-anti-detection system will automatically pick up technological aids that are concealing or scrambling the presence of intruders.
The combot has a chance equal to twice its (AWE+INT) when trying to detect mechanical anti-surveillance systems.

The bot also has a weapons identification skill which can only be used on a weapon which has inflicted damage on the bot.
This skill can be successfully employed if the player rolls under 2 times the bots INT on percentile dice.

== Light Offensive Combot

.*Light Offensive Combot Fabrication Info (C-L)*
[width="75%",cols="2*<"]
|===
2+<|Delivering freedom from a can. 

2+<|*Attributes*

|Ranges
s|CON 2 or 4; DEX 4; INT 1 or 3; PSTR 4

|Minimums
|CON 19; DEX 15

|Hit Points
|16-25 (15+1d10) per point of CON

|Adaptability
|-50%

|Size
|Large

|Value:
|100000000

2+<|*Systems*

|Offensive
|2 rolls on Table 2 +
1 roll on Table 3

|Defensive
|2 rolls

|Peripheral
|None
|===


This type of combot requires the player to have a CON better than 19 and a DEX better than 15.
These light offensive combots are small attack drones used mostly for combat in cities and similar short range environments.
Their job is singular  
to attack and destroy the enemy and the enemy's defenses.
That is their sole purpose and they therefore tend to have a single-minded violent outlook on existence.


== Heavy Offensive Combot

:art: combot_heavy_offensive.png
:width: 250px
:snark: Offensive and heavy.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

.*Heavy Offensive Combot Fabrication Info (C-H)*
[width="75%",cols="2*<"]
|===
2+<|Destroyer of all things in it's path, even campaigns. 

2+<|*Attributes*

|Ranges
|CON 2 or 4; DEX 4; INT 1 or 3; PSTR 4

|Minimums
|CON 23; PSTR 27

|Hit Points
|16-25 (15+1d10) per point of CON

|Adaptability
|-100%

|Size
|Gigantic

|Value:
|1000000042

2+<|*Systems*

|Offensive
|1 roll on Table 2 +
1 roll on Table 3 +
1 roll on Table 4

|Defensive
|3 rolls

|Peripheral
|None
|===


This is the major league version of the light combot.
Here too there are some attribute requirements: PSTR greater than 27 and CON better than 23.
These restrictions are tough but so is the heavy combot.
They have a good chance of being armed with bombs or missiles;
a percentage chance equal to their CON for each type of device.
The number of bombs and/or missiles is determined by the referee (a limit of two of either sort is recommended).
The base AR for a heavy combot is 775.