= Veterinarian

Medibots are veterinarians in a drum.
They are capable of carrying out any vet skill provided that it falls under the description of the vedibots sub-type.
All three medibots are capable of minor repair work and standard first aid procedures;
however, a diagnostic bot could not carry out surgical procedures, a surgical bot could not perform facial reconstructions and a cosmetic bot could not stop an internal hemorrhage.

All medibots will be diagnostic unless they qualify as either of the others.
Regardless of how insane a medibot becomes, it will always have a very high regard for life.
In fact, this is how the medibots insanity will usually present itself, with an extraordinarily high regard for life.
This may include bacteria, insects and mindless animals on the same level of sentient life.++

== Diagnostic

:art: medibot_diagnostic.png
:width: 250px
:snark: Doc in the box.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

//  Diagnostic Veterinarian Robot Fabrication Data 
.*Diagnostic Veterinarian Robot Fabrication Info (V-D)*
[width="75%",cols="2*<"]
|===
2+<|Thinking robot for diagnosing organic malfunctions.  

2+<|*Attributes*

|Ranges
|CON 1, 2; DEX 4; INT 3, 4; PSTR 1


|Minimums
|Nil

|Hit Points
|2 per point of CON

|Adaptability
|15%

|Size
|Medium

|Value:
|2500000

2+<|*Systems*

|Offensive
|Nil

|Defensive
|10% for 1 roll (non-lethal)

|Peripheral
|100% for 1 roll on Primary
|===


The forte of the diagnostic robot is diagnosis.
It has the memory capacity and the intuitive abilities to very accurately diagnose all but the most peculiar conditions.
The diagnostic bot can occasionally fail to assess even the most trivial conditions.
A diagnostic bot has enough articulations and peripherals attached to attempt virtually any vet maneuver.
The diagnostic bot cannot apply general anaesthetics or perform classic surgical procedures.
For instance, a diagnostic bot may identify a brain tumour but would be helpless to remove it.

The chance for success of these maneuvers is determined on the _Veterinarian Performance Table_.
The diagnostic bot can subtract its INT level from the DD of the maneuver and add twice its INT to the die roll.
So a diagnostic bot with an INT level of 3 and an INT of 15 would subtract 3 DD from each maneuver and add 30 to the PT roll.
The diagnostic bot is also capable of identifying any medical appliance to pharmaceutical with a proficiency 5 times the personas INT.

== Interventional

:art: medibot_interventional.png
:width: 250px
:snark: Heal with steel.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

//  Interventional Veterinarian Robot Fabrication Data 
.*Interventional Veterinarian Robot Fabrication Info (V-I)*
[width="75%",cols="2*<"]
|===
2+<|Short on diagnostics. Long on mad skills.  

2+<|*Attributes*

|Ranges
|CON 1, 2; DEX 4; INT 3, 4; PSTR 1


|Minimums
|DEX 23; INT 21

|Hit Points
|2 per point of CON

|Adaptability
|15%

|Size
|Medium

|Value:
|5000000

2+<|*Systems*

|Offensive
|Nil

|Defensive
|10% for 1 roll (non-lethal)

|Peripheral
|100% for 1 roll on Primary
|===


These medibots are capable of performing all surgical functions.
They can replace eyes, add bionic parts, add real parts, remove real parts, remove gallstones, glue eyelids shut plus a host of other related wonders.
All surgical bots have local and general anesthetic and any patient can be kept under for as long as necessary or desired.
The surgical bot must be within 1 hex per two points of PSTR to use its anaesthetics.

Before proceeding, the surgical robot must be given a description of what needs to be done.
This description can be given by a diagnostic bot or a veterinarian.
If a surgical bot is left to do its own diagnosis, then it will function as a veterinarian that can add its INT to the performance table rolls.
The percentage chance of successful surgery is 4 times the bots INT.
Recovery is also dependant on the CON of the patient and she must make a DDS roll and a CON attribute roll before recovering.
Failure to recover may mean delayed recovery or death, depending on the procedure.

These bots are also capable of fleshy reconstructions that will affect only the players CHA and external appearance.
Interventional medical bots can reconstruct teeth, change hair, eye, skin colour, facial appearance (nose jobs, etc.) and other purely external changes.
Regardless of the extent of repairs and changes, a personas CHA can only be increased by a maximum of 3 points.
Medical bots make few (if any) errors;
the chance for success is five times the bots INT.
Once the work is finished, the patients CON must be capable of overcoming any complications or side effects  
this is checked with a CON attribute roll.

Whether the bot screws up or the persona succumbs to infection, the result is the same  
a drop in CHA by one to four points.
Lost CHA can be built back up to no more than three higher than the personas original CHA.
The cosmetic bots are only able to anesthetize local parts of the body with their sonic anesthetic.
Spies can add 10 times the INT of the cosmetic bot to their PT roll when using one to create a disguise.
Cosmetic bots can function as a veterinarian.
When using the PT table cosmetic bots can add their INT.