= Android

:art: android_academic.png
:width: 250px
:snark: A sharp academic android.
:artist: James Shields
:date: 2014
:license: Copyright 2015 JESHields Stockart.

include::ROOT:partial$articulate.adoc[]

// Table 5.A Android
.*Android Fabrication Info (A)*
[width="75%",cols="2*<"]
|===
2+<|The anthro appearing robot type of all low budget robot movies. 

2+<|*Attributes*

|Ranges
|CON 4; DEX 4; INT 4; PSTR 4

|Minimums
|Special

|Hit Points
|Special

|Adaptability
|1%

|Size
|Medium

|Value:
|100000000

2+<|*Systems*

|Offensive
|Special

|Defensive
|Special

|Peripheral
|Special
|===

Androids are the elite of the robotic world;
they are in a class all their own.
An android is a robotic likeness of the base family that designed the bot.
Except for the intense scrutiny of a veterinarian, most androids are indistinguishable from the base family.
Androids are very independent robots and are manufactured with a very high level of self-determined free will.
From a robotics stand point, this makes them very dangerous.

Androids are generated like regular personas;
the major difference is that they cannot choose their family nor their class.
The androids family is determined by a roll on the _Robotic Base Family_ table.
The android will appear to have the age, sex, hite and wate of the family rolled on that table.
The class of the persona can be chosen by the player but, if the referee wishes, she may force the player to roll the androids class on the _Referee Persona Class_ table in Chapter 8.
HPS for androids are determined the same as other humanoid personas.
An android is a formidable opponent and having an android spy or mercenary may seriously jeopardize the balance of the campaign.
Andys get a percentage chance equal to their INT to have a hidden random peripheral (Table . Even though innocently pursuing regular classes and lives, the unique origins of androids should never be forgotten.
The Robotic Base Family Table is included here out of turn for your convenience (thanks copy/paste!).

include::ROOT:partial$CH05_Table_Robotic_Base_Anthro_Type.adoc[]