= Industrial

The basic class of industrial robots break down into three separate types: construction, lifting and moving.
If the personas highest attribute is INT, she will be a construction bot.
A lifting bot must have PSTR as the highest attribute.
If DEX is the highest, the persona will be a moving bot.
If there is a tie among the three attributes, the player is free to choose.

== Industrial Construction Robot

//  Construction Fabrication Data 
.*Construction Robot Fabrication Info (I-C)*
[width="75%",cols="2*<"]
|===
2+<|It will come. Then you build it.

2+<|*Attributes*

|Ranges
|CON any; DEX 2 or 3; INT 1 or 2; PSTR 4

|Minimums
|INT > DEX and INT > PSTR

|Hit Points
|9-12 (8+1d4) per point of CON

|Adaptability
|25%

|Size
|Medium

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|2 rolls Table 1 *ONLY*

|Defensive
|15% for 1 roll

|Peripheral
|100% 1 Primary +
10% 2nd Primary
|===

Mobile assembly units that generally cannot design anything.
Once programmed to produce certain items, they set right to it, acquiring their own supplies and machining the items non-stop until supplies run out.
The cycle then starts over: acquisition of raw materials, etc.
Bots with INT ratings greater than 22 can design their own simple objects (cups, ball, combs, toys).
Properly programming a construction bot is a Mechanic maneuver of dS DD.
The more valuable the item, the more difficult the DD.
This skill does not include production of fancy high-tech weaponry and other such goodies.
Usually a construction bot will stop functioning when it runs out of raw materials.

== Industrial Lifting Robot

//  Lifting Fabrication Data 
.*Lifting Robot Fabrication Info (I-L)*
[width="75%",cols="2*<"]
|===
2+<|Always gonna lift you up. May let you down.

2+<|*Attributes*

|Ranges
|CON any; DEX 2 or 3; INT 1 or 2; PSTR 4

|Minimums
|PSTR > DEX and PSTR > INT

|Hit Points
|9-12 (8+1d4) per point of CON

|Adaptability
|25%

|Size
|Large

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|35% for 2 rolls Table 1 *ONLY*

|Defensive
|15% for 1 roll

|Peripheral
|100% 1 Primary
|===

These are unemployed cargo heists that somehow have lost their jobs in warehouses or department stores.
Lifting bots are capable of supporting one object per three points of DEX.
So a lifting bot with a 12 DEX would have 4 articulations for lifting.
The objects lifted by one arm cannot exceed 3 times the bots PSTR weight allowance.
If the robot has multiple lifting articulations, a DEX attribute roll must be made if the arms are to work in unison, i.e., to lift a single object.
Any object which may be lifted can be raised to a height five times the bots size (height).

Normally, for obvious reasons, lifting bots were not made to drop things to the ground.
However, if an insane bot were to drop things too often, that might be why she is unemployed.
If the player wishes to have her lifting bot drop something, a Control Factor (CF) roll must be made.
If the player fails to roll (rolls under CF), the object or creature will be placed safely on the ground.
After this CF failure, the robot will have to rest for a length of time equal to a Control Factor fit.

== Industrial Moving Robot

//  Moving Robot Fabrication Data 
.*Moving Robot Fabrication Info (I-M)*
[width="75%",cols="2*<"]
|===
2+<|Move it. Store it. Catalogue it.

2+<|*Attributes*

|Ranges
|CON any; DEX 2 or 3; INT 1 or 2; PSTR 4

|Minimums
|DEX > INT and DEX > PSTR

|Hit Points
|9-12 (8+1d4) per point of CON

|Adaptability
|5%

|Size
|Gigantic

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|2 rolls Table 1 *ONLY*

|Defensive
|15% for 1 roll

|Peripheral
|100% 1 Primary
|===

These robots should not be mistaken for intelligent trucks  
in action, they more resemble sentient mail carriers.
Like most mail carriers, these bots have gone on strike.
Unlike most mail carriers, they can carry 3 times their robotic wate allowance and they are very fast.
Moving robots get a bonus of 50% on their movement rate.
They can remember 5 locations per point of INT, well within a range of 100 kilometres per point of AWE.
The moving bot can also decipher maps and find points on maps with an efficiency of four times the bots INT.

Some of the Moving bots are capable of loading themselves (the chance is three times INT+DEX).
Those that are self-loading can lift items up to twice their wate allowance and can load them at a rate of about one object per unit.

