= Robot Peripheral Systems
Peripherals give the robot flexibility to perform it's tasks.
Some peripherals are completely incongruous to the robot type and that is fine.
Why wouldn't a combat robot have a tea service built in.
Peripherals are not malfunctioning parts, but baked in robot controlled devices.

Every robot gets one roll on the Primary Peripheral Table. 
A percentage value indicates the chance of an extra roll.
Some robots do not have peripherals and that is indicated on the fabrication into

The peripherals rolled here can be used creatively but cannot by used in combat.
Aroma producing could not be used to make a nausea attack, but it could help sell a house.
An articulation could not strangle an opponent but it could open a door.

Sometimes the player and referee come to an impasse regarding the creative use of a peripheral.
This is best resolved using xref:ii-combat_rules:CH16_Special_Rolls.adoc#-sphincter_dice[Sphincter Dice]

== Primary Peripheral
Primary peripherals are not fancy. 
A primary peripheral will only mildly alter the robots function or value.
The powerful game changing peripherals are on the Secondary Peripheral Table.

include::ROOT:partial$CH05_Table_Primary_Robotic_Peripherals.adoc[]

== Secondary Peripheral
Secondary peripherals can be game changers.
Mild mannered robots can pursue a vocation.
Most secondary peripherals represent a combination of hardware and software.
These peripherals are not overly detailed as they are non-combat peripherals.
This does not mean that they are not powerful.
A robotic mutation could allow a robot to stop time.

include::ROOT:partial$CH05_Table_Robotic_Secondary_Peripherals.adoc[]
