= Policing

Policing bots are crime fighting machines.
These bots respect the lives and livelihoods (if legal) of all life forms.
They are especially protective of their fabricator type.
Policing bots can be stationed anywhere.
They are not limited to underserviced or violent areas.

// new table for 6.0
//  Robot Attribute Requirements 
.*Policing Robot Attribute Requirements*
[width="75%",cols="2*<"]
|===
2+<| Attribute requirement for industrial robot type.

s|Policing Type
s|Attributes

|Civil
|Nil.

|Riot
|CON 15

|Detective
|INT 15

s|Policing Type
s|Attributes
|===

== Civil Policing Robot

//  Civil Policing Robot Fabrication Data 
.*Civil Policing Robot Fabrication Info (P-C)*
[width="75%",cols="2*<"]
|===
2+<|Policing civilian environments.

2+<|*Attributes*

|Ranges
|CON 3; DEX 4; INT 3; PSTR 3

|Minimums
|Nil.

|Hit Points
|3-12 (3d4) per point of CON

|Adaptability
|-25%

|Size
|Medium or Small

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|100% roll on Table 1

|Defensive
|100% for 1 roll

|Peripheral
|10% for 1 roll on Primary
|===

Civilian policing bots are constables on patrol in a drum.
Civils can walk the beat, chase criminals, guard banks, issue tickets, etc.
By sheer chance this bot's ID is P-C. 
This robot is the main interface between the 'people' and law enforcement.
Civilian policing bots have some special skills.

=== Commanding Voice
When necessary the civil bot can unleash booming amplified voice commands.
Classic commands like FREEZE! or DROP IT! can be used.
The command can be effective or at least distracting to organic ears.
If a target fails a MSTR challenge vs the bot's doubled CHA they will pause, or obey.

=== Non-Lethal Weapon
A non-lethal weapon is one that can disable or affect a target without harming it.
A stun weapon, or a sleep beam, or a nausea attack would be considered non-lethal.
Less lethal weapons do not count.
The player has three chances to roll a non-lethal weapon for her robot. 
If there is no non-lethal weapon after three rolls the persona has no weapon.

=== Disarm
A civil bot can disarm a target with a successful to hit roll.

=== Grapple
When it is time to 'collar' a suspect or subdue a target the civil bot can grapple.
Successfully scoring a hit will completely immobilize an organic target.
A civil bot is completely invested during a grapple and cannot do anything else.
To break from this grapple requires a successful bizarre PSTR roll.
Civil bots will unglamorously drag their grappled collars back to the nearest brig.

== Riobot Policing Robot

:art: riobot.png
:width: 250px
:snark: Riobot protecting and serving
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

//  Riobot Fabrication Data 
.*Riobot Fabrication Info (P-R)*
[width="75%",cols="2*<"]
|===
2+<|Keeping the peace when things are in pieces.

2+<|*Attributes*

|Ranges
|CON 3; DEX 4; INT 3; PSTR 3

|Minimums
|CON 15

|Hit Points
|3-12 (3d4) per point of CON

|Adaptability
|-42%

|Size
|Gigantic

|Value:
|1000000 times 1d6

2+<|*Systems*

|Offensive
|None

|Defensive
|100% for 1 roll

|Peripheral
|10% for 1 roll on Primary
|===

Riot bots are large crowd control operatives.
They often turn up at labour disputes, surprise sales, food line-ups, rock concerts, etc.
There goal is to contain and restrain unruly hordes of anthros.

== Grapple and Detain
A riobot can grapple and detain rioters.
Once a rioter is grappled they can be detained either in or on the riobot.
Each unit the riobot can grapple one rioter and 

The riobot cannot disarm rioters.

To hit roll grapple.
Detain on riobot.
A riobot can detain one target per point of PSTR in the same fashion that a Civils Policing bot can.
So a Riobot with a PSTR of 20 can grapple and hold 20 targets.

=== Peripherals
Riot Policing Bot Peripheral for every three points of INT.
It is possible to have multiple copies of the same crowd control peripheral.

include::ROOT:partial$CH05_Table_Riot_Policing_Robot_Peripherals.adoc[]


=== Table explanation
Target vs A/E.
Each crowd control peripheral can be used on one target per point of AWE every unit.

Save vs To Hit Roll

Range

Intensity.



The effect of the attack is a simple self explanatory description.
For effects like sleep, blindness and stun the duration is d4 minutes.
Effectively knocking the target out of combat time.
If for some reason the Riot Bot cannot affect its effect it can choose to default to inflicting 3d4 HPS of damage instead.

== Detective Policing Robot

//  Detective Policing Robot Fabrication Data 
.*Detective Policing Robot Fabrication Info (P-D)*
[width="75%",cols="2*<"]
|===
2+<|Detective, chief, manager, sleuth, criminologist in one.

2+<|*Attributes*

|Ranges
|CON 3; DEX 4; INT 3; PSTR 3

|Minimums
|INT 15

|Hit Points
|2-4 (1+d3) per point of CON

|Adaptability
|10%

|Size
|Medium

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|100% roll on Table 1

|Defensive
|100% for 1 roll

|Peripheral
|100% for 1 roll on Primary
|===

Special operations bots are the bots which dispatch riot bots and civils to perform their sundry duties.
This intelligent robot is a criminologist in a drum (to put it less than glamorously) that is used to track down intergalactic murderers, confidence women and other unsavory rogues.
If a players persona qualifies to become a special operations bot, her highest attribute can be transferred to her INT.
It is possible that when this robotic type fails its CF roll, it will go off hunting criminals.
This may include other personas or even the entire expedition which, due to the nature of the game, stand a good chance of being criminals themselves.