= Social

:art: social_robot.png
:width: 250px
:snark: Social robot interrupting someone.
:artist: unknown
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]


//  Social Fabrication Data 
.*Social Robot Fabrication Info (S)*
[width="75%",cols="2*<"]
|===
2+<|Fluent in languages, etiquette and irritation

2+<|*Attributes*

|Ranges
|CON 1 or 2; DEX 1 or 2; INT 3 or 4; PSTR 1

|Minimums
|Nil

|Hit Points
|2-4 (1+d3) per point of CON

|Adaptability
|50%

|Size
|Medium

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|10% roll on Table 1

|Defensive
|84% for 1 roll (non-lethal)

|Peripheral
|100% for 1 roll on Primary
|===

Relations bots are borgs that roughly resemble the base family that built them.
This resemblance is purely for aesthetics and cannot be mistaken for the real family.
The size and weight of the robot will be rolled on the tables for the base family with the weight being increased by 25%.
This robot type will have articulated legs 90% of the time;
this will supersede any other form of locomotion.
Relations bots speak the language of their base family and possibly many others.
The maximum number of languages that a relations bot can understand and employ is 10 times her INT.
Each new language encountered can be immediately understood with a deci-die roll less than her INT.
If a language is not immediately understood, then a relations bot will come to understand it with 1 to 4 days of exposure.
Relations bots are also known as robotic butlers and they can observe the customs and etiquette (often pedantically) of 1 culture per point of INT.
Robutlers can also tend to the needs of 2 guests per point of INT.

include::ROOT:partial$CH05_Table_Robotic_Base_Anthro_Type.adoc[]
