= Robot Sensors
All robots will have audio and video sensors which will allow the robot to hear and see.
The robotic audio and visual sensors function the same as any other persona.
To expect a player to manage otherwise would most likely be simply frustrating.
Robots do not have sensors for touch, smell or taste.
As with other personas the robot's AWE attribute is integral to the sensors.
Better awareness better sensors.
Sensors are only damaged when the persona's AWE is damaged. 
Robots will receive one additional sensor for every 4 points of AWE.

include::ROOT:partial$CH05_Table_Robotic_Sensors.adoc[]

== Video
This robot has an extra set of video sensors.
These essentially act as an extra set of eyes for the robot.
These can be built into the robot's hull or conveniently attached to the end of an articulation.

== Alternate optical
Alternate forms of optical vision include laser sights or ultraviolet/infrared detectors.
These types of vision can be included in the robot's regular vision or considered an extra component.
The alternate optical sensor allows the robot to easily see in darkness.

== Vibrations
Vibration sensors convert molecular vibrations into comprehensible robotic vision.
This sensory feature will cut through any obscuring clouds of gas or particulate debris.
The maximum range of a vibration sensor is 5 hexes per point of AWE.
Vibration sensors are directional and the robot must look towards whatever she wants to observe.

== Sonar
Sonar allows the bot to perceive a spherical area in the medium it is immersed in.
For instance, sonar will work equally well through air, water or smoke.
The sonar will not function beyond a transition between water and air.
The sonar range is 10 hexes her point of AWE.
Sonar cannot function in a vacuum.

== Radar
Radar gives 360° vision around the robot.
This is a 360° disk and not a spherical area of detection.
This allows the robot to detect objects and determine their wate within 10 hexes per point of AWE.
Radar can penetrate solid objects.

== Refs Own Table
Referee can insert campaign related sensors she sees fit.
Organic eyes, tentacles, olfactory unit, touch sensors, or a sense of style.
