= Robot Power Source
All bots operate on electrical power.
That electrical power comes from many different power sources. 
All cells work via ingenious advanced technological that is conveniently beyond explanation.
All robotic power sources are rechargeable.
Each power source functions equally well
The power source can go by many names: battery, cell, supercell, etc.

The robot's power source has will last one month per point of CON.
For convenience we assume that a new persona has a fully charged power source.
If the persona's CON drops then the duration of the power source drops along with it.
The robot's power source is proportional to it's use. 
No variations in use will drain the power faster or slower.

If a robot runs out of power, the persona will shut down until recharged.
The persona is not dead. 
It is just resting.
Robot personas will get a one month warning. 

It should always be made possible for a robot to recharge its power source.
Robot personas should not spend all their time searching for fuel.
One hour must be spent refuelling for each month of recharged.
Recharging could mean being plugged in, filling with water or being stuffed with materials.

include::ROOT:partial$CH05_Table_Robotic_Power_Cell_Type.adoc[]

== Basic cells
Basic cells contain chemicals that react to create electricity.
One would hope that the nature of these chemicals is so advanced an explanation is optional.
For story telling purposes the chemical could be anything: natural gas, manure, hair, etc.
Recharging the power cell simply requires replacing the depleted materials.

=== Gas and Liquid Cells
Gas and liquid cells will cease operation if exposed to a vacuum.
This does not apply if the robot is exatmo hardened.
They will function as normal once atmosphere is restored.

=== Solid Cells
Solid cells function fine in vacuums, but do not function at high temperature.
Prolonged exposure to temperatures that may not damage the robot may damage its power cell.
Solid cells will function as normal once they cooled.
Extreme heat could destroy a bots solid cell.

== Broadcast
Broadcast cells are power receivers that convert transmissions from a source into energy.
The receivers will cease to function if they are electronically jammed or out of range.
When within range the robot has an endless supply of power.
Robots using broadcast power can store one month of power per point of CON.
A robot with a broadcast power source that runs out of stored charge must be placed back in range to recharge.

== Dynamo
Internal gyros spin up the electricity for this robot.
The countless dynamos are microscopic and silent. 
Cells offer no features beyond source.
Dynamos will not function when exposed to more than 2g.
The dynamos return to normal once gravity drops below 2g.
Dynamo cells can be recharged by plugging into the nearest electrical outlet.

== Gravitational 
This power cell filters gravitational waves into electrical energy.
An explanation of this technological miracle will not be attempted.
The gravitational force cannot exceed 3g or be less than one half g.
The robot will store energy for those instances where gravitational cell cannot function.
The robot has 1 hour of stored energy per point of CON.
Once out of power the robot will remain dormant until gravity normalizes.

== Magnetic 
Cellular magnetic forces are amplified to produce electrical power.
Magnetic cells will be disrupted by any magnetic based attacks or disruptions.
Severe disruptions may cause the cell to be demagnetized and require recharging.
This is left to the discretion of the referee.
Regeneration requires and electrical charge to re-magnetizes the power cells.

== Nuclear 
The nuclear power sources uses slow burn fusion, fission, etc., to produce electricity.
It is impossible for a this persona to explode like an atomic weapon.
The nuclear cell is so efficient that there is no radiation hazard.
The nuclear power source functions in all many or atmospheres and gravities.
Fissionable materials are required to replenish the nuclear batteries.

== Plasmoid 
Superheated gases contained in magnetic bottles fire up the robot for power.
This should make it virtually impossible for Mechanics to use the plasmoid cell maliciously.
The plasmoid cells have many safeguards that prevent their weaponization. 
Recharging plasmoid batteries requires the re-insertion of plasmodial materials.

== Psionic 
Psionic cells convert the surrounding psychic energy into electrical energy.
The psionic cell has the most complicated recharge process.
The batteries last for the usual one month per point of CON.
When it is time to recharge the cell drains local psionic energy.
The nearest persona will to the robot will be drained one point of MSTR to fully recharge the robot.
The persona gets a save vs psionic attack. 
The robot persona uses her CON as MSTR to calculate the saving throw. 
If the persona saves the robot moves onto the next persona.
The process is automated and the robot is unaware of who is attacked when.

== Solar 
The solar power source will keep the robot operational in any amount of light.
Artificial light and light from the nearest star work equally well.
If there is light this robot need not recharge.
If the robot should be plunged into darkness they will operate on stored power.
The robot can store 1 hour energy per point of CON.
A solar powered robot with a 16 CON could run for 16 hours in the dark.

== Ref's Own Table
Referee can insert campaign related power sources as she sees fit.
