= Maintenance

// table insert 49

Maintenance bots should not be confused with janitorial bots (see Type E) although they sound similar.
The crucial difference is that maintenance bots, in addition to cleaning, are adept at repairing artifacts.
A maintenance bot is best likened to a mechanic in a drum.

The robot functions the same as a mechanic except for some tremendous bonuses.
The player can add the repair droids INT to performance table rolls, just like a normal mech;
however, a maintenance bot gets one skill per point of intelligence plus 5 per experience level.
So a maintbot with a 13 INT would be 18 skills at first level plus 5 new skills per experience level.
For referee persona robots, most of these skills will be rolled on the _Mechanic Skills_ table in Chapter 8: Classes.

Players can choose where they want the expertise of their personal to lie.
Thus a robot could have skill level 15 in repairing bicycles and skill level 2 in guns.
Thus this robot would be able to subtract 15 DDs when repairing or working with bicycles.
This is an ominous bonus indeed.
It is recommended that one take a variety of skills, making their persona more flexible.
For further reading about performance tables, consult http://expgame.com/?page_id=269[Chapter 27: Performance Tables].