= Robot Locomotion
This is how the robot moves around. 
Wheels, skis, balloons, tracks move the robot and define it's appearance.
Every robot rolls on the Primary Locomotion Table below. 
All types of locomotion perform equally.
So a robot with 3 pods would move equally to a robot with tracks. 
The persona's DEX score would be the difference not the locomotion type.

Some locomotion types require a complementary locomotion type. 
The complementary locomotion type  

include::ROOT:partial$CH05_Table_Robotic_Primary_Locomotion.adoc[]

include::ROOT:partial$CH05_Table_Robotic_Secondary_Locomotion_Type.adoc[]

== Antigrav
Antigrav is a classic science fiction term for anti-gravity.
The robot can travel about as though gravity has no effect upon it.
The robot can fly and flit about.
As ideal as antigrav is, it will only function within a gravity well.
The robot has no obvious mechanisms that create it's buoyancy in gravity.

Complementary antigrav only floats the robot, while the primary locomotion type moves the robot.
For example, a robot with jets and antigrav would float by antigrav and maneuver by the jets.
The antigrav jet driven robot would look like it is flying by jets, but would float with all jets off.

== Chemical slide
The chemical slide allows the robot to effortlessly slide along any surface.
This process leaves a quickly evaporating trail not unlike a slug.
This comparison does not necessarily imply the bot will be slow.
A chemical slide will operate just as well up a slope as down a slope.
Sand, stairs and other difficult terrain may prove to be a challenge for a robot with this locomotive type.
How difficult such travel is depends entirely on the referee.

A complementary chemical slide is offering a frictionless surface and the primary locomotion propels it. 
For example, a robot with jets and chemical slide would stay grounded and be pushed around by jets. 

== Electromagnetic legs (1d4)
Electromagnetic legs are visible beams the move the robot around.
A robot will have 1 to 4 electromagnetic legs.
These legs keep the robot about a meter off the ground. 
They keep the robot level on varying terrain.
Electromagnetic legs do not work on water.

== Jets (1d4+1)
Robotic jets force gases at high speed to generate movement.
A robot will have 2 to 5 jets.
The jets create thrust and maneuverability.
Robotic jets are intake-less and do not eject dangerous super-heated propellants.
Whether jets work exatmo or not is up the referee.

== Magnetic
A magnetic locomotion unit allows the robot to hover above the ground.
The height of the robot is fixed at no higher than 1 hex.
Magnetic locomotion is not a flying type of locomotion.
Robots with magnetic locomotion will often float around long after their destruction.
Magnetic locomotion can travel above any solid or liquid.

== Pistons (1d10)
Pistons quickly poke up and down keeping the robot balanced and moving.
A robot has 1 to 10 pistons.
A single piston looks like a robot on a pogo stick.
The pistons are immaculately timed and keep the robot stable.
Pistons must have a solid surface to operate.

== Pods (4d4)
Pods are articulated mechanical legs.
The robot has 4 to 16 pods.
These articulated poles will hop, scuttle or patter the robot about.
Pods require a solid surface to operate.

== Propellers (1d6)
Robotic propellers are quiet, high-powered and safely encased air screws.
The propellers offer thrust and maneuverability to the robot. 
There are 1 to 6 propellers.
Propellers combined with antigrav would allow the robot to fly.
Propellers combined with a chemical slide would propel the slide.

== Sails (1d3)
Sails are very sturdy, electro molecular planes that catch air for movement.
Robot sails operate perfectly well in raging wind or dead calm.
The sails offer thrust and maneuverability. 
All locomotion types are equivalent.
Movement is determined by DEX score. 
The robot will have 1 to 3 sails.


== Skis (1d4+2)
Skis are attached to articulated pods that skate the robot over any type of terrain.
There are 3 to 6 (d4 plus 2) skis.
There is no difference in speed whether the robot is trotting uphill or sliding down slopes.

If the skis are a complementary Locomotion Type they do not function the same.
The skis are attached to articulated pods and not powered legs.
The skis would be the surface contact but jets, sails or propellers would drive the robot.

== Slog bag
A slog bag appears as a fluid filled sack attached to the undercarriage of the robot.
The slog bag undulates and contorts itself along the surface the surface the robot travelling.
The slog bag moves like a sack of mercury, however it need not contain a liquid.
The slog bag cannot be during regular combat unless the robot's locomotion is damaged.

== Tracks (1d6)
Robotic tracks are nothing more than rubber-coated tank tracks.
Each track is individually controlled and maneuvers by contorting itself.
There are 1 to 6 tracks.
This form of locomotion is rugged, although not especially familiar.

== Wheels (1d12)
Robotic wheels are independently powered and controlled.
They are solid, puncture proof and 
There are 1 to 12 wheels.

When wheels are complementary locomotion type the Primary Locomotion Type generates the force.

== Ref's Own Table
Referee can insert campaign related locomotion types as she sees fit.
