= Transportation

There are two types of transportation robots.
Planetary (terrestrial) and extra-planetary (can pilot space vehicles).
In order to be an extra-planetary transportation bot, DEX and INT must both be at least 22.

== Planetary

// table insert 50

Transportation bots get driving skills equal to their INT plus five skills per experience level.
Thus a first level transport bot with an INT of 23 would have 28 skills to divide amongst chosen vehicles.
Any bot that can use a vehicle that carries more than 15 passengers automatically gets a serving skill.
These bots can only maneuver and navigate their vehicles  
than cannot engage in vehicle combat.
Only expendable combots can use vehicles for offensive combat tactics.
There is nothing keeping a particularly insane transbot from attempting such maneuvers though.

The transport bot uses the _Driving Performance_ table (see Chapter 17: Driving) as any other persona would;
however, she can use her skill level to reduce the DD of the maneuver.
For instance, a transport bot with air-car skill level 10 would subtract 10 DD from any maneuver she was attempting.
The chance that a transport robot will be able to pilot a vehicle is equal to 4 times its INT, regardless of skill level.

== Extra-Planetary

// table insert 51

An extra-planetary transport bot has all the same skills as its cousin above, except that it can pilot space-vehicles and can function normal in a vacuum.
An extra-planetary transport bot can be used to replace a pilot.