= Policing

Policing bots are used by crime fighting forces in extremely rough areas or in places where there are severe police staff shortages. The three types of policing bots are: riot (CON minimum 15), civilian or special operations (INT minimum 15). All policing bots respect the lives and livelihoods (if legal) of their fabricator type, though it is expected that insane policing bots may be renegade and not the great protectors of law and order that they were initially designed to be.

== Civil Policing Robot

//  Civil Policing Robot Fabrication Data 
.*Civil Policing Robot Fabrication Info (P-C)*
[width="75%",cols="2*<"]
|===
2+<|Policing civilian environments.

2+<|*Attributes*

|Ranges
|CON 3; DEX 4; INT 3; PSTR 3


|Minimums
|Nil.

|Hit Points
|3-12 (3d4) per point of CON

|Adaptability
|-25%

|Size
|Medium or Small

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|100% roll on Table 1

|Defensive
|100% for 1 roll

|Peripheral
|10% for 1 roll on Primary
|===

Civilian policing bots are sent out to apprehend known criminals, guard banks, give out traffic tickets, lecture kids on road safety, etc. This bot type can speak very fluently and can double its CHA to make commanding comments like: FREEZE! or HOLD IT! The civil bots get three chances to roll a single non-damaging weapon from the robot attack tables 2 or 3. If the bot is unsuccessful on all three attempts to acquire a stunning or similarly non-damaging weapon, the bot will be without any form of attack.

Those civil policing bots without weapons can still grapple a target. Successfully scoring a hit will completely immobilize a humanoid target, rendering them unable to do anything physical. To break away requires a bizarre PSTR roll. During this time, the civil bot will usually remove any weapons or offending items from the immobilized persona. Civil policing bots will usually carry their collars (captured criminals) in this unglamorous fashion to the police station.

== Riobot Policing Robot

:art: riobot.png
:width: 250px
:snark: Riobot protecting and serving
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

//  Riobot Fabrication Data 
.*Riobot Fabrication Info (P-R)*
[width="75%",cols="2*<"]
|===
2+<|Less than lethal control of mobs.

2+<|*Attributes*

|Ranges
|CON 3; DEX 4; INT 3; PSTR 3

|Minimums
|CON 15

|Hit Points
|3-12 (3d4) per point of CON

|Adaptability
|-42%

|Size
|Gigantic

|Value:
|1000000 times 1d6

2+<|*Systems*

|Offensive
|None

|Defensive
|100% for 1 roll

|Peripheral
|10% for 1 roll on Primary
|===

Riot bots are large crowd control devices and often turn up at labour disputes, surprise sales, food line-ups, rock concerts, etc. A riobot can detain one target per point of PSTR in the same fashion that a Civils Policing bot can. So a Riobot with a PSTR of 20 can grapple and hold 20 targets. In addition to grappling each riobot has one roll on Table 5.12 Riot Policing Bot Peripheral for every three points of INT. It is possible to have multiple copies of the same crowd control peripheral.

Each crowd control peripheral can be used on one target per point of AWE every unit. The first detail is whether the peripheral is targeted or area of effect. Targeted means that the riobot picks targets and attacks. Area is the range around the Riobot that the effect radiates. Next item is the range of the attack. Usually it is an attribute of the bot. So if the range was PSTR and the bots PSTR was 11 the range would be 11 hexes. That would either be the range to the target like any type C attack, or the radius around the bot like a grenade attack. The next data point is the intensity of the attack. If the riot bot is using a stun ray with a CON of 14 the target would get a save of versus intensity 14 attack. If intensity says AR then at to hit roll must be successful. If the intensity says None there is no save or the referee could refer to [Chapter 16 Special rolls](http://expgame.com/?page_id=275 "Chapter 16: Special Rolls"), more specifically Sphincter Dice. The effect of the attack is a simple self explanatory description. For effects like sleep, blindness and stun the duration is d4 minutes. Effectively knocking the target out of combat time. If for some reason the Riot Bot cannot affect its effect it can choose to default to inflicting 3d4 HPS of damage instead.

include::ROOT:partial$CH05_Table_Riot_Policing_Robot_Peripherals.adoc[]

== Detective Policing Robot

//  Detective Policing Robot Fabrication Data 
.*Detective Policing Robot Fabrication Info (P-D)*
[width="75%",cols="2*<"]
|===
2+<|Detective, chief, manager, sleuth, criminologist in one.

2+<|*Attributes*

|Ranges
|CON 3; DEX 4; INT 3; PSTR 3

|Minimums
|INT 15

|Hit Points
|2-4 (1+d3) per point of CON

|Adaptability
|10%

|Size
|Medium

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|100% roll on Table 1

|Defensive
|100% for 1 roll

|Peripheral
|100% for 1 roll on Primary
|===

Special operations bots are the bots which dispatch riot bots and civils to perform their sundry duties. This intelligent robot is a criminologist in a drum (to put it less than glamorously) that is used to track down intergalactic murderers, confidence women and other unsavory rogues. If a players persona qualifies to become a special operations bot, her highest attribute can be transferred to her INT. It is possible that when this robotic type fails its CF roll, it will go off hunting criminals. This may include other personas or even the entire expedition which, due to the nature of the game, stand a good chance of being criminals themselves.