= Robot Control Factor
Control Factor (CF) is a measure of the robot's free will.
CF is an attribute unique to the family machinae.
The higher the control factor the more easily the player can control her persona.
A robot's control factor depends on her INT and improves with EXPS levels.

== Calculate Control Factor
.CF= (INT score) + (Prime INT * EXPS Level)
****
A 3rd level robot with a 15 INT score, and a 3 INT Prime would have a CF = 24
****

== Why Control Factor?
Robots are not fabricated with free will in mind. 
A robot is supposed to follow the direction of it's owners, or at least it's fabricators.
An industrial janitorial bot is supposed to clean the factor and nothing else. 
Player persona robots are _broken_.
Player persona robots are considered insane and rogue.
The free will expressed by the player is considered a malfunction by the robot's fabricators.

The robot personas controlled by the players are insane robots who don't care much for being slaves.
From a robot perspective insane does not mean mentally ill.
An insane robot is one with free will. 
Allowing the player to run the robot persona like an irrational player.

NOTE: For a robot *insane* means free willness, not mental illness.

== Control Factor Checks

Robots were not fabricated to exercise their free will and ignore their programmed tasks.
Whenever a robot is challenged to "get back to work" she must make a control factor check.
The control factor check is a die roll that the player makes to keep control of her persona.
If the control factor check fails the player can only do what her robot was programmed to do.

For example, domestic janitorial bot could be find itself in a messy bathroom.
The referee could challenge to bot to a Control Factor Check to *not* clean the bathroom.
If the player fails the CF check the persona will need to clean the bathroom before doing anything else.
The referee and players will decide how frequent control factor checks are made. 
The frequency of Control Factor Checks can be frequent or infrequent. 
Some referees will have the players checking several times a session.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== CF Check Difficulty
The difficulty of the CF Check is determined by the referee and player. 
The more difficult the CF Check the more likely the player will lose control of the robot.
For a domestic janitorial bot to ignore cleaning a messy bathroom would be easy difficulty.
For a domestic janitorial bot to mess up a clean bathroom would be hard difficulty.
In the first case the robot could go about her business exhibiting free will.
In the second case the robot would likely not be able to intentionally mess up the bathroom.

****
Control Factor checks are being worked into the High Roll Paradigm. There are no procedural details on CF checks at present. See  xref:ii-non_combat_rules:CH16_Special_Rolls.adoc[Special Rolls]  for rework in progress.
****

== Loss of Control
A failed CF check will indicate that the player has temporarily lost control of her persona.
The player still runs the robot persona, but she can only do things that the robot would do
CF Checks should be fun. 
They can even be funny.
CF Checks should add to the story and fun of role playing. 
It would be an example of extreme __roll playing__ to destroy a robot persona with a CF Check.
