= Exploration

Explorations bots come in two quite distinct but complementary types: planetary and extraplanetary.
In order to qualify for extraplanetary status, a minimum of 24 INT is required, making extraplanetary bots the rarer of the two exbots.

== Planetary Exploration Robot 

//  Explorations Planet Data 
.*Planetary Exploration Robot Fabrication Info (E-P)*
[width="75%",cols="2*<"]
|===
2+<|Planet side robot fabricated to explore, learn and report. 

2+<|*Attributes*

|Ranges
|CON 4; DEX 2; INT 1 or 4; PSTR 3

|Minimums
|Nil

|Hit Points
|11-16 (10+1d6) per point of CON

|Adaptability
|30%

|Size
|Small

|Value:
|100000 times 1d12

2+<|*Systems*

|Offensive
|25% roll on Table 1

|Defensive
|1 Roll

|Peripheral
|1 Primary
|===

The planetary exploration robot is the more mindless version commonly deposited on planets as an expendable drone to do preliminary reconnaissance.
Their job is to survey a section of the planet on which they have been let loose;
they are mostly used to determine mineral contents, atmosphere composition, surface mapping and take photographs.
They are capable of speech but are not advanced enough to undertake communication with newly encountered creatures on the planet.
A planetary explorations bot will actively avoid the natives.
Some standard functions planetary bots perform are:

* Atmospheric Analysis
* Long Range Communication
* Mineral Identification
* Photography (includes infra-red, x-ray, etc.)
* Poison / Radiation Detection
* Sample Collection

Data for more complex tasks such as map-making and surveying is relayed to another location and interpreted there.
These communications may be processed anywhere from an orbiting spaceship to a roving extra-planetary bot.


== Extra Planetary Exploration Robot

:art: extra_planetary_bot.png
:width: 250px
:snark: Exploiting, exploring, a new planet.
:artist: Louis Glanzman, modded HM
:date: 1953, 2017
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

//  Explorations Planet Data 
.*Extra Planetary Exploration Robot Fabrication Info (E-E)*
[width="75%",cols="2*<"]
|===
2+<|Planet side robot fabricated to explore, learn and report. 

2+<|*Attributes*

|Ranges
|CON 4; DEX 2; INT 1 or 4; PSTR 3

|Minimums
|INT 24

|Hit Points
|11-16 (10+1d6) per point of CON

|Adaptability
|-10%

|Size
|Medium

|Value:
|100000 times 1d6

2+<|*Systems*

|Offensive
|1 roll on Table 1

|Defensive
|2 rolls

|Peripheral
|1 Primary
|===

Extra-planetary bots can do everything their less qualified counterparts can do, plus more.
The exbot can process the information which the planetary bot can only collect.
Extra-planetary bots are far more intelligent than their planetary friends and so are able to think more independently, get around more, accomplish more and defend themselves far better.
They come with an AR of 800 and can function in a greater variety of substances: liquid, vacuum, etc.
can also:

* Comprehend languages
* Identify intelligence
* Map terrain
