= Hobbot

:art: hobbot.png 
:width: 250px
:snark: DIY blinged out with chrome accents.
:artist: unknown
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

//  Datalyzer Data 
.*Hobbot Fabrication Info (H)*
[width="75%",cols="2*<"]
|===
2+<|Highly modifiable hobbyist robot. 

2+<|*Attributes*

|Ranges
|CON 1; DEX 1; INT 3 or 4; PSTR 1

|Minimums
|Nil

|Hit Points
|2-8 (2d4) per point of CON

|Adaptability
|100%

|Size
|Small or Tiny

|Value:
|10000 times 1d6

2+<|*Systems*

|Offensive
|10% roll on Table 1

|Defensive
|50% for 1 roll

|Peripheral
|2-8 (2d4)

|===

// table insert 28

Hobby robots put together at home by an enthused robotics hobbyist.
Hobbots are made for companionship, mechanical fun or even possibly for some actual purpose.
The hobbots come with many peripherals rolled off the Random Peripheral Tables.
Hobbots are the most easily modified of all the robots.
There is a +2 DD bonus for Mechanics when trying to work on a hobbot.
Hobbots are also characterized by an unusual degree of uniqueness  
it is almost impossible to have two identical hobbots.
Often they are jerry-built super-mechano sets with bits and bytes attached here and there.
They should not be underestimated because of their humble origins  
they may cunningly conceal a host of nifty tricks and treats.