= Android

:art: android_academic.png
:width: 250px
:snark: A sharp academic android.
:artist: James Shields
:date: 2014
:license: Copyright 2015 JESHields Stockart.

include::ROOT:partial$articulate.adoc[]

// Table 5.A Android
.*Android Fabrication Info (A)*
[width="75%",cols="2*<"]
|===
2+<|The anthro appearing robot type of all low budget robot movies. 

2+<|*Attributes*

|Ranges
|CON 4; DEX 4; INT 4; PSTR 4

|Minimums
|Special

|Hit Points
|Special

|Adaptability
|1%

|Size
|Medium

|Value:
|100000000

2+<|*Systems*

|Offensive
|Special

|Defensive
|Special

|Peripheral
|Special
|===

Androids are robots made in the image of their fabricator.
They are mostly indistinguishable from their fabricator type. 
Typically it would require a vet or mechanic to determine their nature.
Androids are very independent robots and are fabricated with a high degree of autonomy.
The player essentially can function as a fully autonomous persona.

The vast majority of androids will be fabricated after a certain anthro type.
The referee may allow the player to choose what she is fabricated after.
For example, if the fabricator type is feline the android will look like a feline.

From this point on the persona is generated like any other anthro persona. 
The attributes will be radically different. 
The feline android would be incredibly smart and fast. 
She would be able to choose nearly any vocation (except knite). 
There would be no mutations. 
There would be no built in weapons, or defences or peripherals.
The persona would appear as an extremely strong, smart, fast and tough feline.

An android is like any other robot and is functioning outside of its parameters. 
Control factor checks may still be required for reasonable requests from the fabricator type.

include::ROOT:partial$CH05_Table_Robotic_Base_Anthro_Type.adoc[]