= Robot Control Factor
// tag::Control_Factor[]
Control Factor (CF) is a measure of the robot's free will.
CF is an attribute unique to the family machinae.
The higher the control factor the more easily the player can control her persona.
A robot's control factor depends on her INT and improves with EXPS levels.

== Calculate Control Factor
.CF= (INT score) + (INT Range * EXPS Level)
****
A 3rd level robot with a 15 INT score, and an INT Range of 3  would have a CF = 24
****
// end::Control_Factor[]

== Why Control Factor?
Robots are not fabricated with free will in mind. 
A robot is supposed to follow the direction of it's owners, or at least it's fabricators.
An industrial janitorial bot is supposed to clean the factor and nothing else. 
Player persona robots are _broken_.
Player persona robots are considered insane and rogue.
The free will expressed by the player is considered a malfunction by the robot's fabricators.

The robot personas controlled by the players are insane robots who don't care much for being slaves.
From a robot perspective insane does not mean mentally ill.
An insane robot is one with free will. 
Allowing the player to run the robot persona like an irrational player.

NOTE: For a robot *insane* means free willness, not mental illness.

== Control Factor Rolls

Robots were not fabricated to exercise their free will and ignore their programmed tasks.
Whenever a robot is challenged to "get back to work" she must make a control factor check.
The control factor check is a die roll that the player makes to keep control of her persona.
If the control factor check fails the player can only do what her robot was programmed to do.

For example, domestic janitorial bot could be find itself in a messy bathroom.
The referee could challenge to bot to a Control Factor Check to *not* clean the bathroom.
If the player fails the CF check the persona will need to clean the bathroom before doing anything else.
The referee and players will decide how frequent control factor rolls are made. 
The frequency of Control Factor Rolls can be frequent or infrequent. 
Some referees will have the players checking several times a session.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Control Factor Roll

Whenever a robot persona performs a task for which it was originally designed -- a janitorial bot cleaning up, a combat bot killing an opponent --it must roll below its control factor or briefly return to it's original programming.
Control Factor rolls are usually Normal Attribute rolls  (1d20).
If the janitorial bot were ordered to clean up a room by a charismatic mechanic from the robot's base family, a tough (1d50) Control Factor roll would be need to be made.

The Control Factor of a robot is the robot's INT plus its experience level, and represents how well it has learned to bypass its programming.
To fail a Control Factor roll is to give in to that programming, a persona robot phenomenon known as loss of control.
A robot that has lost control becomes a helpless automaton, a temporary referee person.
 The persona will continue to perform exactly its programmed function without deviation until it regains control of itself.
If the failure occurs during combat, it will last a random number of units determined by the same, die the robot lost control with so failing a tough (d50) CF roll would result in d50 units of boring, non-sentient behaviour.
Outside of combat, the failure will last a random number of minutes on the same die: failing an improbable (d100) roll might lead to over an hour and a half of tedium.

*Control Factor (CF) = Intelligence plus EXPS Level*




== CF Check Difficulty
The difficulty of the CF Check is determined by the referee and player. 
The more difficult the CF Check the more likely the player will lose control of the robot.
For a domestic janitorial bot to ignore cleaning a messy bathroom would be easy difficulty.
For a domestic janitorial bot to mess up a clean bathroom would be hard difficulty.
In the first case the robot could go about her business exhibiting free will.
In the second case the robot would likely not be able to intentionally mess up the bathroom.

****
Control Factor rolls are being worked into the High Roll Paradigm. There are no procedural details on CF rolls at present. See  xref:ii-non_combat_rules:CH16_Special_Rolls.adoc[Special Rolls]  for rework in progress.
****

== Loss of Control
A failed CF check will indicate that the player has temporarily lost control of her persona.
The player still runs the robot persona, but she can only do things that the robot would do
CF Rolls should be fun. 
They can even be funny.
CF Checks should add to the story and fun of role playing. 
It would be an example of extreme __roll playing__ to destroy a robot persona with a CF Check.
