= Alien Number of Attacks

:art: alien_attacks.png
:width: 250px
:snark: Many hands many attacks
:artist: Edward Cartier scan M. Moscow
:date: 1951
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The number of attacks a denizen is entitled to is usually its most important offensive combat parameter.
The number of attacks that an alien gets is determined by a deci-dice roll (1d100) on the Number of Attacks table.
Players add 1.3 their DEX to the d100 roll.
Thus a persona with a 15 DEX would have 5 added to her die roll.

The number of attacks indicates how often the creature may roll to hit each unit.
The attack refers to the alien's natural attack.
The damage of an alien's natural attack is listed under damage in this chapter.
The number of attacks does not refer to any sort of technological weapon or mutation-like attack that has a pre-set attack frequency.
The number of attacks refers only to the creature's natural offences -- tentacle to tentacle combat so to speak.

include::ROOT:partial$CH06_Table_Number_of_Alien_Attacks.adoc[]

One attack every second unit may seem very slow, until one fabricates some possible reasons for this.
Perhaps the family is inherently non-combative and too many of the alien's blows are being easily blocked.
The alien may have a high DEX but in combat it is just plain slow.
Conversely, high attack frequencies can turn an alien with an average damage per attack into a killing machine and may require justification by the referee.

