= Alien Size

:art: alien_very_small.png
:width: 250px
:snark: Size can matter.
:artist: unknown, HM
:date: unknown, 2017
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The size of an alien is not just a descriptive element.
Alien size impacts HPS and damage delivered.
The size roll reflects the size of this alien.
The size roll also indicates the size of the alien species.
While sizes within the species may vary the size rolled here is this persona's actual size.

Size is generated early in alien evolution because it impacts other alien elements.
The alien has a size and wate, but no shape, character, name or culture. 

:art: alien_humongous.png
:width: 250px
:snark: Humongous aliens are hard to play.
:artist: Virgil Finlay
:date: 1966
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Bigger is not always better.
The larger the alien the more HPS it has and the more damage it can deliver.
Large and gigantic aliens are difficult to play.
The technology of EXP is based on anthro shape and size.
Vehicles won't fit.
Armour is unwearable.
Large rifles are clumsy little sticks.
An enormous size will be a constant role playing challenge.

There are two alien sizes that do not appear on the alien size table.
These are minute and humongous.
Minute aliens have wates less than 1kg and are reserved for referee personas.
Humongous aliens have wates of hundreds of tonnes and are reserved for referee personas.

== Adjusting the Alien Size Roll
An alien's size is affected by DEX and PSTR.
Stronger creatures tend to be larger and dextrous creatures tend to be smaller.
The player adds her persona's PSTR and subtracts her persona's DEX from the die roll.

include::ROOT:partial$CH06_Table_Alien_Size.adoc[]

A player whose alien has a 12 DEX and a 22 PSTR would add 10 to her deci-dice roll and a die roll of 67 would be adjusted to 77 and the alien would be large sized.
She rolls 39, 41, 11, 89 and 67 for her 5 d100 rolls.
Her alien's wate is 347 kgs.
Her alien has no description, no name and no abilities to speak of but its wate is 347 kgs.
