= Alien Movement

Aliens can move up to one hex/unit per point of DEX.
Denizens may hop, slither, scuttle, slime or gallop along with whatever form of locomotion is listed as legs in their Description.
The type of creature part that is used to describe the alien's locomotion will move at the designated movement rate regardless of what the description is.
For instance, an alien that looks like a snail could move as fast as an alien that looks like a leopard.

== Alien Base Movement Rate
// tag::Alien_Move[]
.move (h/u) = DEX
****
A persona with a 12 DEX would have a base movement rate of 12 h/u. 
****
// end::Alien_Move[]
If the creature type listed there does not have any obvious form of locomotion, it will still move and the player must use her imagination.
The chance that an alien will be sessile is quite rare: the alien must have a zero DEX or all the creature parts must be non-mobile (s).

The fact that earth phrases like air, water and land have been chosen to describe alien movement should not limit the referee to these types of terrain.
Aquatic (w) means liquid.
It could be water or liquid ammonia.
Airborne flying (a) does not have to be air but could be any gaseous atmosphere like carbon monoxide or smog.
Let Table 6.19, Alien Biome (later in this chapter) decide the alien's favourite atmosphere, not its movement type.

The system has some peculiarities which are not immediately obvious.
If the alien has sea creature parts but lives on an arid planet, it will merely be slowed down but it will not die from dehydration.
If the alien has parts all of one type then it will be restricted to that one environment.
If the alien has body parts from amphibious creatures then it may be able to move equally fast on land as in liquid.

== Movement and Description
The creature parts rolled do have an effect on the alien's movement rate but not in the direct fashion that their description dictates their speed.
As one would expect from EXP, there is a much more convoluted way to determine the alien's movement rate (move).
The alien's DEX represents the maximum movement rate that an alien can travel at.
Thus an alien with 12 DEX would have a base movement rate of 12 h/u.
The alien's movement rate is adjusted for different terrains and it will rarely move at its given maximum movement.

For example, each creature part listed on the Alien Body Part table has a terrain familiarity listed after it in brackets;
for example, pig (l), hippopotamus (l,w) and sea urchin (n-w).
It is these designations that determine the alien's speed on land, in the air, and in the water.
The terrain types are described under step (8) Description earlier in this chapter.

== Quartering Movement
The three types of movement are land, air, and water and the alien's movement rate is divided amongst these terrain types.
Each of the four body parts is designated a certain terrain type(s).
Every time that a certain terrain type appears, 25% of the alien's movement rate can be achieved on that terrain.

If all four of an alien's body parts (head, torso, arms, and legs) were derived from land creatures (l), then the alien would move at 100% on land.
If it were an alien with a 12 DEX, it would move 12 h/u on land but it could not swim or fly.
If the alien were to have three land creature parts (l) and one sea creature part (w), then it would move ¾ on land (9 h/u) and ¼ in liquid (3 h/u).
If the alien had two land creature parts (l), one aquatic part (w), and one flying part (a), then it would move at ½ on land (6 h/u), ¼ in air (3 h/u), and ¼ in water (3 h/u).

The Example Alien Movement table has the movement rates calculated for an alien with three land parts, two airborne parts, and one water part.
Note that none part simply reduces the alien's total movement.

include::ROOT:partial$CH06_Table_Calculating_Alien_Movement.adoc[]
