= Alien Society

Alien society is something for the referee to carefully consider and prepare for her campaign.
Alien societies can even be the basis for an entire campaign.
The differences in values, architecture, and social organization alone amongst alien cultures would be beyond the duration of a life time of study.

Most of the persona aliens will be rogues or outcasts that have rejected their alien culture thus allowing them to form their own cultural niche.
The referee cannot possibly prepare a detailed alien society each time a player generates an alien persona.
For the most part, alien personas will not be members of galactic societies or developed countries.
If some idea of the alien's society is necessary but total preparation is not, the referee should turn to Chapter 11: Referee Personas and determine the society's religious, political, and philosophical beliefs.

*Alien Communications*: The aliens that are generated as personas are usually from non-tool using, non-civilized, and otherwise un-organized species.
For role-playing convenience, the aliens almost always will be able to communicate with the other personas and only the most malicious referee will not allow an alien persona this leniency.
It is unrealistic to think that an alien will be able to converse freely with humanoid personas but remember that this is science fantasy and fun must win out over realism.

*Tool Users*: The most important roll for any player running an alien is whether her persona is a tool user or not.
There is a percentage chance that the alien species will be tool users equal to the alien's INT.
Thus, an alien with a 13 INT has a 13% chance of being a tool user.
Aliens that are tool users are allowed one roll on the TOY system (Chapter 41) to get one device which is adapted for their own use.

Tool users can easily use artifacts that are designed for them and can adapt themselves to use artifacts that are designed for humanoids.
An artifact would be considered alien to an alien if there were a drastic difference in size;
if the alien had no digits that could obviously operate the artifact;
or it the referee were in a petty mood.
The chance of this happening can be determined by rolling Sphincter dice as described in Chapter 19: Special Rolls.

*Adapting to a Tool*: When a tool user encounters an artifact that it cannot manipulate easily, then it must try to adapt to the artifact.
This means that the alien will use its tongue instead of a finger or a hoof instead of a hand.
The chance of successfully adapting to an artifact is equal to twice the alien's DEX.
If it cannot adapt itself then it CANNOT use the artifact.
Thus a tool using alien with a 10 DEX that encounters an alien (to it) artifact has a 20% chance of manipulating the device.
If it fails, then the alien CANNOT use the device.
Biologists can aid the alien in adapting to its device and mechanics can adapt the device itself.

// Beasts of burden.+++</figcaption>++++++</figure>+++

*Non-Tool Users*: According to the dice, most aliens will be non-tool users.
The referee may automatically allow alien personas to be tool users to increase their involvement in the game.
The referee should not depend solely on the dice rolling of her players.
If a player comes up with an ingenious idea about how her persona can manipulate a particular artifact then the persona should be able to do so.
Role-Playing should overcome dice rolling.

*Trying Anyway*: Non-tool users must make an INT check against percentile dice to see if they can even begin to comprehend a particular artifact.
Non-tool users must make this check for every artifact that they encounter.
Even if they succeed in identifying an item as useful, then they must adapt themselves to the artifact as a tool-using alien would have to adapt to a foreign artifact.
It will be rare indeed when a non-tool using alien will be able to deploy a technological device.

*Alien Education*: Alien education implies that the alien has developed a curiosity about the natural world that far exceeds the animal awareness that most creatures have.
If an alien is a tool user, then there is a percentage chance equal to her INT attribute that she will be educated.
This roll is required by all alien personas whether they are run by a referee or a player.
It is not recommended that referees allow player run aliens to automatically be educated as is done with tool users.

Educated aliens can pursue persona classes like anthropomorph personas.
All requirements and abilities for these classes are the same as listed in Chapter 8: Classes.
Once an alien adopts a persona class, it may become a very dangerous alien indeed.
The referee may invoke class restrictions she feels are necessary to ensure a game balance.
Could you imagine trying to fairly referee an invisible, 900 kg, flying spie?
Just this one sentence may keep the referee from allowing alien personas from ever pursuing classes.
