= Aliens

[quote]
____
*Aliens represent the infinity of organic forms that can be conscious.*
____

Alien is the colloquial term for the family diversidae.
Aliens encompass any organic living creature that has consciousness.
Aliens are evolved, represent species, and are generated randomly. 

== Alien Evolution Checklist

. xref:CH06_Aliens_1_Attributes.adoc[Attributes]
. xref:CH06_Aliens_2_Size.adoc[Size]
. xref:CH06_Aliens_3_HPS.adoc[Hit Points]
. xref:CH06_Aliens_4_Attacks.adoc[Attack Frequency]
. xref:CH06_Aliens_5_Damage.adoc[Attack Damage]
. xref:CH06_Aliens_6_CT.adoc[Combat Table]
. xref:CH06_Aliens_7_AR.adoc[Armour Rating]
. xref:CH06_Aliens_8_Shape.adoc[Shape]
. xref:CH06_Aliens_9_Move.adoc[Movement Rate]
. xref:CH06_Aliens_10_Mutations.adoc[Mutations]
. xref:CH06_Aliens_11_Life_Span.adoc[Life Span]
. xref:CH06_Aliens_12_Biology.adoc[Biology]
. xref:CH06_Aliens_13_Society.adoc[Society]
. xref:CH06_Aliens_14_Name.adoc[Name]
. xref:CH06_Aliens_15_EXPS.adoc[Experience]

Like all other generation systems in EXP, the alien persona generation system can create very individual (i.e.
bizarre) creatures of varying intelligences, strengths and descriptions.
Persona aliens are created completely randomly and their niches in the campaign story can vary greatly.
The personas could be introduced as natives of an unexplored world, as members of a conquering alien horde, as the offspring of biological experimentation or any combination of these.

It is usually considered that the player is generating the attributes for an entire family, in which case her persona becomes an individual belonging to this alien family.
For convenience, the alien persona is considered an exactly average free-willed representative of this species and the referee is expected to splice this new family into the existing campaign.
The player's business involves the running of her particular alien and the referee is responsible for the alien family.
Usually alien personas will never encounter members of their own family.
The referee should remember that she can alter the nature of an alien to suit her campaign as she sees fit.

== Role-Playing Aliens

Role-playing an alien is trickier than role-playing an anthropomorph and these players have more problems than usual in adjusting to their personas.
The aliens are generated randomly and their shape, size and powers vary greatly.
For instance, the player may have to relate to a persona that is bright pink, waving multiple appendages, wagging a tail, sporting antlers or having no limbs at all.

As with robot personas, alien personas will have to learn to restrain the urge to personify their aliens.
If the alien lacks a head, arms, legs or some other fundamental feature, the player will have to adjust accordingly.

Players running aliens will have to use the most refined imaginative role-playing skills.
They will have to imagine grasping items with tentacles;
realize that humanoid seats were not necessarily designed for them (if "`sitting is even possible);
get accustomed to their massive (or diminutive) size;
accept alien priorities (e.g., eating vs.
remuneration);
and adapt to a host of other special circumstances.
If your persona were a flying anemone, you may have difficulties with such mundane tasks as turning door handles or firing humanoid weapons.

:art: alien_shapes.png
:width: 250px
:snark: Alien shapes can be strange to play.
:artist: H. Brown
:date: 1938
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]


There is no reason to assume that the alien's psychology will be even remotely similar to the player's or to any other humanoid.
Alien goals may be as primal as food procurement or as sophisticated as galactic domination.
The player may even find her persona restricted to one particular biome, unable to roam freely like other personas.
Thus the player has to deal not only with the physiological aspects of her alien persona but also with an alien psychology.
The problem is not that aliens have no personality but that it most certainly will be far from human-like.
This problem of alien physiological and psychological personification is going to be the greatest challenge the player will face during actual role-play and hopefully the most fun!

== Limits of the Alien Generator
There are limits to what the alien generation system can produce.
Aliens that are blobs of gas, crystalline rock formations or distinctly humanoid cannot be randomly created with this system.
This system cannot be expected to produce a perfect, ready to use alien.
It is meant to be used to generate all the biological particulars -- attributes, size, movement, damage, etc.
-- of an alien persona as well as a haphazard physical description.
If the referee wants a particular type of persona with particular looks, size and attributes, it is recommended that she refer to the Referee Personal chapter (11) where referee aliens are discussed.
Chapter 11 discusses all types of referee personas including how to generate aliens that suit the scenario or campaign.

== Evolving Aliens
The values generated in this chapter are considered to be the mean values for an adult of the species.
Any alternations due to age, sex, climate, etc.
are left to the ref to accommodate.
Personal idiosyncrasies of the alien are left to the player.
To properly generate an alien persona, the player must follow the Alien Generation Checklist.
