= Alien Lifespan

All personas except for robots have a projected life-span.
The idea of an alien only living for a certain amount of time is a reflection of its biological nature.
The life spans of aliens can be very alien indeed when compared to those of humanoid personas.

The referee should have the alien's life span reflected in the society of the alien species.
Very long lived species would have fewer offspring and possibly take less risks than short lived aliens;
possibly arguing that they have very much more to lose than a species that will only enjoy existence for a few years.
They could equally likely get profoundly bored and take tremendous risks.
Although this should not impinge on the way the player runs her persona, ignoring the fact that one is going to live several thousand years would not be very realistic role-playing.

*Calculating Lifespan*: Determining the alien's life-span is done in two parts.
First the absolute life-span of the alien is rolled on the Alien Life-span Table.
This deci-dice roll determines the longest that the alien can live in a number of years.
Peculiar things like differences in year lengths must be considered by the referee but it is assumed here that all year lengths in EXP are equal.
Second is the distribution of the alien's life stages.
This part determines what percentage of the alien's life will be spent as a child, an adolescent, an adult, or as an older member of the family.
The effects of these different stages are the same for all aging personas and are discussed in http://expgame.com/?page_id=267[Chapter 13: Health].

// table insert 96

*Alien Life Stages*: The alien life stages are quite superficial indeed.
They do not consider alien aging peculiarities like pupal stages, physical transformations, dormancy, or years of dependency.
An alien persona will always start the campaign as a young adult and most developmental problems like dependency and pupal stages should have been avoided.
The referee could propose transformations that would alter the appearance of the alien as it passed from one life stage to another.
Except for developmental changes unique to the alien, aliens suffer the same attribute adjustments as they pass through the various life stages.
See Chapter 13: Health.

// table insert 97

*Example Alien Life Span*: If a player were to have rolled 82 on the Alien Lifespan table, then her alien would have an age between 160 and 250 years old.
She determines her persona's maximum possible age to be 200 years.
The results of her rolls on the Alien Life Stages table are given below.
Note that the aged category must be rolled before the older category can be determined.
The alien's start age should be about 29 to 30 years and on its 169th year, it will be in the older category and at 197 years in the aged category.
After 200 years, it has exceeded its life expectancy.
For the effects of these age changes, see Chapter 13: Health.

// table insert 98
