= Alien Mutations

Aliens have a chance of getting mutations;
however, they are not generally considered mutations but natural abilities that function the same as mutations.
An alien's mutations apply to the entire family and are more like naturally evolved defensive or offensive abilities.
Therefore, alien mutations are not considered mutations in the usual sense -- as if they were abnormalities or variations from the norm.
Occasionally mutations may force changes in the creature's physical description as determined in the Description section.
If a player running an alien wishes to mutate, she cannot adjust her chance of mutation like humanoid personas can.

Mental Mutations: The chance of an alien having a mental mutation is equal to the alien's MSTR attribute.
An alien with a 15 MSTR would have a 15% chance of having a mental mutation per mutation check.
The player stops checking for mental mutations as soon as a roll is failed.
So if the player were to roll 11 and 16, her alien would have one mental mutation.
These mutations are described in Chapter 58: Mental Mutations.

Physical Mutations: The chance of a creature having evolved a physical mutation is equal to the creature's CON.
For example, a CON of 10 has a 10% chance of having a mutation.
Once the alien has a mutation, there is an equal chance of having another.
The alien can keep getting additional mutation-like abilities if it keeps making its percent chance.
If the player with the alien that has a 10 CON were to roll 3, 9, and 41, her alien would have two physical mutations.
The mutations are described in http://expgame.com/?page_id=366[Chapter 59: Physical Mutations].
