= Alien Attributes

Alien attributes are generated in a different manner than those of other personas.
The attributes being generated are considered to be the mean attributes (average) for an entire alien family.
This presents no problem for the player because her persona is considered to be a model example of an adult alien.
All her attributes are exactly average and they require no adjustment upwards or downwards.
However, if the ref decides to have attribute differences due to sex or age, it is up to her to determine these deviations.
The player rolls her persona's attributes on the Mean Attributes Table.

Alien attribute scores are the same as any other personas, whether that persona is a robot or a humanoid.
An alien PSTR of 12 is no stronger than a humanoid PSTR of 12 which is no stronger than a robotic PSTR of 12.
There is a subtle difference in that aliens can begin a campaign with a zero attribute.
If a zero is rolled for any of the alien's attributes, some special conditions will have to apply.

*Generating Attributes*: Like other personas, the alien attributes are generated once for each attribute.
Aliens use the Mean Attribute Table to determine their attributes.
For example, CON, DEX, INT and MSTR are supposed to be generated on 5d6 -5.
This means that fixe six-sided dice are rolled and 5 is subtracted from their total.
It is essential that these attributes be rolled on the number of dice given.
This assures a good statistical curve of attributes for all aliens generated.

// table insert 82

*Zero Attributes*: Certain of the alien's attributes can have a nominal value of zero;
however, this number has somewhat different implications than it would for an anthropomorphic persona.
For instance, if the DEX roll were 0, the creature would be sessile (immobile).The DEX should be re-rolled to determine limb co-ordination and aiming ability.
If CON were 0, this would mean that the creature has no hit points.
Such a situation could be interpreted to mean that they lack a life force and do not appear to be alive as usually defined.
However, their CON would be re-rolled to determine how much damage they can take before disintegrating.
The re-rolled attributes are the same as any other persona's attribute and, if any of these are reduced to zero, the alien is irrevocably dead.
Such explanations could be invented for DEX, INT, MSTR AND PSTR.
