= Alien Armour Rating

Only the AR in terms of aliens is described here.
Armour rating is covered more thoroughly in Chapter 29: Armour Rating.
Alien AR includes its dexterity, agility, hide structure, body structure and any other natural devices that have evolved to avoid getting damaged or captured.

What fraction of a creature's AR depends on dexterity is subjectively determined by the DEX roll.
If the alien has a high DEX, its natural AR most likely consists of dodges and dekes.
An alien with a low DEX is more likely to have a thick hide or a defensive body structure (internal or external).

Regardless of the alien's DEX, or description, the AR is determined completely randomly.
The alien's AR can range from 503 to 800.
This is the average natural armour rating for completely nude and un-armoured members of this alien family.
Any armour that is worn by an alien will increase its AR from this value.
So, in essence, this is the alien's base AR.
Getting specialized alien armour is not discussed here but will make the alien even harder to hit.

If a player were to roll 15, 89 and 64, her alien persona would have an AR of 668 and any to hit roll would have to be higher than that value to score a hit.

*ALIEN ARMOUR RATING (AR) = 500 + 3d100*
