= Alien Size

:art: alien_very_small.png
:width: 250px
:snark: Size can matter.
:artist: unknown, HM
:date: unknown, 2017
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The size of an alien may seem like an irrelevant die roll but, aside from determine size and wate, it helps decide the alien's hit dice and damage.
Like the alien attributes, size indicates the mean racial wate and this will perhaps vary for individual aliens.
Size is determined on the Alien Size table, which gives both a general adjective and a wate range.
The size of an alien does not determine its shape, which is created under Alien Description in this chapter.

:art: alien_humongous.png
:width: 250px
:snark: Humongous aliens are hard to play.
:artist: Virgil Finlay
:date: 1966
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The size die roll is adjusted by the persona's DEX and PSTR.
The player adds her persona's PSTR to the die roll and subtracts her aliens`' DEX from the die roll.
This should reflect the basic biological principle that stronger creatures are usually larger and more dextrous creatures are usually smaller.
This principle is not entirely correct but the Alien Size table roll should be adjusted by those attributes.
If the adjustment is forgotten and the persona is completed, there is no re-rolling of alien size.
This gives an added randomness to the creation of aliens.

include::ROOT:partial$CH06_Table_Alien_Size.adoc[]

A player whose alien has a 12 DEX and a 22 PSTR would add 10 to her deci-dice roll and a die roll of 67 would be adjusted to 77 and the alien would be large sized.
She rolls 39, 41, 11, 89 and 67 for her 5 d100 rolls.
Her alien's wate is 347 kgs.
Her alien has no description, no name and no abilities to speak of but its wate is 347 kgs.
Often the size of an alien will be noted by the first letter of the size adjective -- e.g., L for Large.