= Alien Name

Giving a name to an alien is different from naming any other character because the player must name an entire family as well as itself.
A few pointers on naming aliens are listed below:

1) The denizens of unexplored planets on which there is no intelligent life do not have names and it is up to the players to christen them.
Until that time, the referee must assign serial numbers for identification of the creatures.

2) Most denizens have more than one name.
They have a scientific name that identifies the creature's kingdom, phylum, etc.
and another "`pet name`".
Humans go by the "`pet name`" of "`man`" but also have the more specific classification of: Animalia, Chordata, Vertebrata, Mammalia, Primates, Hominidae, and Homo Sapiens.

3) The alien's mode of communication (decided by the referee) may not allow for a regular name.
If the creature uses binary clicks, body shapes, pheromones or something even stranger to communicate, this has to be taken into account when naming it.
