= Alien Hit Points

Alien HPS depend on their size and their CON.
The alien's size determines the type of die that is used to generate the alien's HPS and the alien's CON determines how many times the die is rolled.
The die type is determined on the Alien Hit Point table and it is rolled once per point of CON that the alien has.

include::ROOT:partial$CH06_Table_Alien_Hit_Points_HPS.adoc[]

According to the table, a player running a large alien with a 9 CON would roll 9d10 to determine her alien's HPS.
The numbers generated on each die are cumulated as the person's HPS.
If the player had rolled 4, 5, 2, 6, 8, 3, 5, 6 and 7, her alien would have 46 HPS.
The HPS max and the dice rolled should be recorded on the personal record sheet of the alien.

== Alien Death
One final, very important point that players with alien personas must remember, especially those expecting to be involved in combat, is that aliens, unlike other characters, are DEAD at zero hit points.
Aliens are not required to make Damage System Shock rolls regardless of how much damage they have taken, however , when they reach 0 HPS, the persona is irrevocably dead.

