= Alien Damage Per Attack

Alien damage per natural attack is determined from the Alien Damage Table.
Yet there are subtle complexities about the damage itself that must be considered.
The player must decide how the alien attacks -- whether it punches, kicks or gores or whether it fires lasers, spits acid or electrocutes.
This is determined on the Attack Type table.

Multiple attacks also pose a slight problem.
If an alien has three attacks, it is unlikely that it claws, bites or kicks three times in one unit (unless, for example, it has three mouths).
If the ref feels it is necessary or if the description dictates, multiple attacks can be given different damages where the different damages represent different types of attack.
Normally there is only one attack and that is repeated several times.

== Damage per Hit
Consider a gigantic alien with a 13 PSTR and three attacks.
According to the Alien Damage table, the alien would inflict 3d12 (3-36) HPS damage each time it scores a hit.
A deci-dice roll on the alien Attack Type table is 57.
This alien would inflict its damage by a type A attack: contact.
The type of physical attack that is employed, whether it is biting, slashing or clawing is determined by the player.
Aliens do not get a damage adjustment like other personas.
The amount of damage an alien inflicts already includes its PSTR.

include::ROOT:partial$CH06_Table_Alien_Damage_Per_Attack.adoc[]

== Alien Attack Type

The alien attack type categorizes the alien's damage into one of the 3 basic weapons types discussed in weapons.
Type A attacks are thrusting and striking attacks and some examples of some alien thrusting and striking attacks are given.
Type B attacks are ranged attacks that are powered by the alien herself.
These could be quills or spittle that can be hurled up to a length equal to the persona's PSTR.
Aliens that have attack type C have a naturally evolved attack that resembles a weapon rolled from GUNS.
The attack will be modelled after the weapon rolled in Chapter 46, having the same damage, range and rate of fire.
For example, an alien could spit seeds like a fully automatic rifle.

include::ROOT:partial$CH06_Table_Alien_Attack_Type.adoc[]