= Alien Shape

The description system for aliens is, at best, wild and unpredictable.
The description is achieved by choosing body parts from an enormous list of past and present earth dwelling denizens.
Each creature listed on the Alien Body Part table should be familiar to anyone reading it.
However, the random combination of these parts creates a strange description indeed.
To create a plausible description, the players must remember that the alien parts merely resemble those of the familiar creature and are proportional to each other in size.

== Alien Proportions
It is essential that the proportions of the body parts be kept in mind.
If the alien has the body of a bear and head of a mite, it is not a big ball of fur with a microscopic head;
the creature is better described as a medium (rolled on size charge) sized creature with an insect-like head atop a bulky, furry body.
The mite's head would be a size proportional to the bear torso.
When adjusting the alien description to fit the relative body sizes, do not disregard the size of the alien, rolled earlier.
If an alien is a tiny creature with the body of a sperm whale and the head of a giraffe, remember that it is still tiny and has a tiny giraffe's head and a tiny sperm whale's body.
Also, if an alien has the legs of an ant but is gigantic, then the alien has sig gigantic ant legs.

== External Appearance
Another problem people have when using this system is that they apply their scientific knowledge and not their imagination to the generated descriptions.
Comments such as the following abound: "`...an amoeba of that size couldn't possibly support its own weight in...`".
The alien is not a 542 kg pink amoeba;
it is something that has a wate of 542 kg, is pink and bears a striking resemblance to an amoeba.

The rolls merely indicate that the alien's shape strongly resembles the particular earth creature part.
The familiarity is totally visual and there is no reason to assume any internal similarities whatsoever.
For example, an alien may look like it has the head of a wasp, the torso of a porcupine and the flippers of a walrus.
However, its internal composition will consist of highly alien biological workings that can only be guessed wildly at.

The "`black box`" physiology of the alien is very convenient;
it allows the ref to create imaginative "`biologically`" based explanations for any of the alien's peculiar attributes, abilities or limitations.

Although all the steps described will very straightforwardly deliver an alien, this is not meant to be a rigid system.
Feel free to at any time manipulate the description of the alien.
Add or remove special adornments, slap in new eyes or antennae, change the mouth, re-roll the coat etc.
Alter and mould the creation into the form of the perfect alien, creature, denizen, beasty or whatever.

The alien description seems quite sterile because it is.
A mundane list of words and parts don't have the synergistic effect of seeing the whole creature.
This is why a drawing is recommended.
Regardless of how poorly the alien is rendered, even the attempt to join all the body parts together will help solidify the alien description.

== Description and Movement
Beside each creature type are letters contained in brackets.
These letters indicate the types of earth terrain that the creature type is mobile in.
Land creatures have an "`l`" for land;
flying creatures have an "`a`" for air;
and aquatic creatures have a "`w`" for water.
Sessile creatures have an "`s`" for sessile (non-mobile).
Sessile creatures are usually found in certain environment types as listed above.
A rabbit is a land creature (l);
an alligator is both aquatic and land (l,w);
a hawk is airborne (a);
a duck is all three (l,a,w);
and an anemone is sessile aquatic (s-w).
These parameters should be recorded on the persona record sheet.

:art: alien_none.jpg
:width: 250px
:snark: No parts. No body.
:artist: Earl Bergey
:date: 1945 
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

== None and Unknown Parts
If the body part is unknown to the players or ref, it is best researched in a dictionary or an encyclopaedia.
If the body type rolled should happen to be "`None`" then the alien does not have, or has no use for, that particular body part.
A creature with no head may have sensors attached to the torso;
a creature with no legs may move by means of the torso or be immobile;
an alien with no body parts at all is the type of non-entity that livens up campaigns.

== Generating the Description
The size of the alien has already been determined.
The alien's shape is now determined with four separate rolls on the Alien Body Part table.
Each alien rolls for a head, torso, arms and legs.
The four divisions are given to divide up the four most basic structures that any life form would be expected to have.
Such classic divisions should not be interpreted to mean that all aliens have such standard structures.

=== Head
The Alien's head type is the one that stores the alien's brain, its primary sensors, and is usually located on the front of the alien.
Once the head type has been determined, the player can make some decisions about the alien's appearance.
Should she use the neck attached to the head or wait for the torso?
Does the description of the head indicate a possible attack mode for the creature?
Should she roll for a special adornment (from the Head Adornment table)?
Such decisions are purely cosmetic and should not profoundly affect the alien.

=== Torso
It is expected that the torso would be the most likely place for the alien to store its vital organs.
Who knows what these vital organs might be or what they might process but they are more likely than not to be stored in the torso.
Descriptively, the torso is probably the most general category of all the body part rolls and it can easily be melted into the limbs and head of the alien.
Some considerations are: Whether or not to use the neck attached to the torso?
Does the tail suit this alien?
Should we add a special adornment from the Torso Adornment table?

=== Arms
Arms are the articulations of the alien.
Because an alien has limbs that are designated for grasping, it does not immediately imply that the alien is a tool user.
The alien might use the specialized limbs to pick berries or peel the flesh off of prey.
Whether or not the alien is a tool user or civilized is determined under alien society in this chapter.

Even if it is decided that the alien should have arms with manipulative hands, the Alien Body Part table may still generate a body part that resembles a creature with either no arms (snake, paramecium) or a creature that has no digits (horse, shark).
If the alien is supposed to be a civilized tool user but the animal type rolled has no arms but has flippers, hooves, fins or legs, then a specially evolved grasping attachment can be rolled on the Arm Adornment table.
The Arm Adornment table should only be used as a last resort (read cop-out).
Intelligent families that have hooves or flippers will most likely have designed their technology to accommodate such digits.

=== Legs
This alien part indicates the main form of locomotion that gets the alien around.
Often an alien's legs will not be legs at all but flukes, flippers, bulbs and blobs.
If the alien has snake's legs, it slithers about;
if it has fish legs, it may wiggle or fin itself about;
if it has parrot legs, it may have clawed bird-like legs, wings to fly with or both.

Whole picture: Once the basic body of the alien has emerged with head, torso and limbs all amalgamated satisfactorily, various adjustments and "`cosmetic`" touch ups can be incorporated.
There are three Special Adornment tables (Head, Torso and Arms) to choose from.
The last feature to be decided is the creature's coat.
Although the alien will consist of body parts resembling various animals, there is no reason that it must have a patchy appearance.
The alien would most likely have a coat/hide colour that gives it camouflage to avoid hunters and catch prey.

:art: alien_assembly.png
:width: 450px
:snark: Four rolls. One alien.
:artist: Kevin Long
:date: 1992
:license: Copyright 1992 Kevin Long

include::ROOT:partial$articulate.adoc[]

include::ROOT:partial$CH06_Table_Alien_Body_Parts.adoc[]

== Various Adornments
These are optional variations on the alien's appearance.
In no way would they keep an alien from being a tool user, or being able to swim or fly.
Again these are cosmetic.

// Mundane horse like alien with head adornments


// Adornment or body part type doesn't matter

include::ROOT:partial$CH06_Table_Alien_Adornments_Arms.adoc[]

include::ROOT:partial$CH06_Table_Adornment_Head.adoc[]

include::ROOT:partial$CH06_Table_Adornment_Torso.adoc[]

// table insert 94
