= Spie

:art: spie.png
:width: 250px
:snark: Safe working environment.
:artist: Michael Jackson
:date: 1992
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Spies, simply put, are tough, mean, ruthless, and lethal personas.
They are highly skilled in unarmed combat, deception, and murder.
Spies can employ any combination of these abilities to satisfy their goals.
Spies can be of value to the expedition if they feel like it.
Often they will be disguised as some other class (yes, even a Vet) which pretends to function as part of the expedition.
For the party, Spies are an excellent source of dangerous assignments (from governments, corporations, societies or private citizens).
Spies are not totally dependent on a commission and can carry out a little extortion or kidnapping for their own profit (or fun).
Spies from popular fiction are James Bond, Flint, Sten, and the Stainless Steel Rat.

The cut-throat nature of the spie world does not mean all spies must be ruthless assassins and terrorists.
But in the realm of international and extra-planetary espionage, it is very difficult to distinguish the bad from the not-so-bad.
Spies very rarely operate freelance and usually depend on some source for assignments and possible remuneration.
How deeply involved the expedition gets with a spie's source depends on the milieu or scenario set up by the ref.
It is also not uncommon for spies to be members of secret guilds or naughty lodges which can offer training in the clandestine arts.
Any spie that initiates an act of counter-espionage (turning on her employer) whether by a higher authority or personal decision is almost certainly in big (like massive) trouble.

The skills of spies are fairly strict and new ones must be carefully analyzed to ensure they do not infringe on those of mercenaries.
Spies almost certainly have attending some sort of "`spie school`" or special forces training and they may be the only class to have had any formal training.
The pre-gaming history of a spie's education can be left up to the ref or the player.
The basic spie skills are Assassination, Disguise and Martial Arts.
There are many other spie tricks that the persona can have.
These are determined on the table below.

== Assassinate
Under optimal conditions and with the correct weaponry, a spie may carry out an assassination.
The attempt must be made under the conditions of complete surprise.
This excludes assassination attempts on victims during combat or with weapons that announce their approach.
A flame thrower would be an inappropriate weapon but a rifle fired some distance from the target would be adequate (the bullet arrives before the bang).
Once the spie and the ref have finished arguing (er, discussing) whether the situation is an acceptable one, the spie must attempt to roll to hit.
Only after a hit has been scored can an assassination attempt be made.
The DD for the assassination depends on the victim's experience level, AWE, and a random factor.

If the PT roll is successful, the victim is dead.
There is no turning back, no saving throw;
the victim is deceased.
If the roll is unsuccessful, the victim takes damages as from the hit.
If this normal damage kills the victim, it is not considered an assassination by the spie.
Getting caught, whether successful or not, depends on the scenario being played out by the ref and the players.

== Disguise
A masquerading spie can make herself appear about 50% taller or heavier or about 25% shorter or lighter.
Whether or not the disguise is detected depends on the AWE of the observer and the complexity of the disguise.
Generally, it is an Improbable attribute roll (D100) (see Chapter 16:  Special Rolls) that an observer will notice that something is wrong.
The more extravagant the disguise, the less difficult the Attribute roll.
If the initial PT roll is failed, the spie may still be identifiable but the disguise will appear more as a costume.
If an observer notices that a spie is disguised, the spie is not necessarily identified, just uncovered.
Further action must be taken to ascertain the spie's identity.

== Martial Arts
Spies also have their own form of very deadly hand-to-hand combat.
The spie's martial arts abilities include kicks, punches, elbows, chops, head butts, and body slams.
None of these hand-to-hand attacks vary in damage from one type to another and none of them have any special significance (other than the damage they produce).

include::ROOT:partial$CH08_Table_Spie_Martial_Arts.adoc[]

=== Martial Arts Table 
This a 5th level spie that loses initiative would get one attack before her opponent attacks, one attack while her opponent attacks, and then one normal attack.
If the spie wins initiative, she has earned 3 attacks before her opponent can act.
Note that the spie cannot move until her turn and the martial arts attacks have a limited range on the adjacent hex.

=== Amour Rating
This martial arts training adjusts the spie's armour rating as she employs throws, parries, blocks, and rolls to increase her AR.
If the spie is wearing no protective covering, she will always have the armour rating bonus listed on the Spie Martial Arts table.
If the spie wishes to combine her defensive martial arts with amour, she must make a successful PT roll or have the lesser of the two armour ratings.
The DD of this maneuver is equal to the armour rating of the armour divided by 100 plus its restrictiveness.
The player should have this DD memorized if she wishes her persona to carry out that maneuver.

=== Number of Attacks
The number of attacks applies to the number of martial arts attacks that the persona can make.
If she wishes to make additional attacks with other weapons, she must make a successful PT roll.
If this performance table maneuver is failed, she will suffer a to hit roll penalty of -300 on the weapon attack and -200 on her martial arts attack.

=== Attack Damage
Martial arts attacks can only be used on targets in an adjacent hex.
The damage inflicted is added to the regular PSTR bonus awarded for hand-to-hand combat.
This is the same as the damage adjustment for the type B attacks and it is equal to ½ the persona's PSTR.
The persona uses her type A weapon attack on her combat table.
For martial arts, refer to Chapter 25: The Combat Introduction for more information.

=== Attack Sequence
The attack sequence is very important to the spie.
Using her martial arts, she can alter the course of initiative by getting attacks in before others can act.
"`Normal`" attacks are self-explanatory and the spie attacks in the normal combat order.
"`Before`" attacks allow the persona to make the given number of martial arts attacks before her opponent can attack her.
The before attacks are granted even if the spie loses initiative.
"`During`" attacks are launched simultaneous to any attacks on the spie regardless of whether she wins the initiative or not.

== Spie Tricks
Neat little tricks are the trademark of any qualified spie.
Several are listed here.
Before adding a new trick, the ref must analyze it in excruciating detail, ensuring that it is different from the other class`' skills, spie-like, and not excessively ridiculous.
The tricks are not hard and fast rules.
They are very dependent on ref-player interaction and are included mostly to explain some of the things that our favourites spies can do.

:art: mysterious_exit.png
:width: 250px
:snark: Out of the frying pan...
:artist: Leon Bennet
:date: 1879
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

include::ROOT:partial$CH08_Table_Spie_Tricks.adoc[]

=== Bribery
This is a skill that must be run very subjectively by the referee.
Some upstanding citizens may refuse any attempt at bribery (it being a criminal offense on some planets may aid in their morality) while others will gladly accept the additional remuneration.
Successfully casing a potential bribe will increase this skill's chance of success.
The players and ref should remember to role-play the situation whenever possible.
One quick die roll does not give service to a situation potentially as fun as this.
Bribery skill can be used by the persona to slip across a border line, get into a rock concert, or avoid a traffic ticket.
Personas cannot bribe people into damaging themselves and the greater the physical risk involved, the higher the DD should be.
Failure at bribery could result in any reaction other than a successful bribe and the response could vary from snickers to violence.

=== Casing
This skill should be carried out by the spie before any other skulking action is taken.
Casing can determine potential difficulties that may have to be overcome in order to successfully bypass security, bribe, etc.
The DD of casing depends on how elaborate the protections are (if any) and how large an area is being cased.
If the spie fails to case the "`joint`" properly, unsuspected bits of security may foil even her best laid plans.
Successfully casing may yield specific information of importance to the spie like there is a trap/alarm over there, someone is watching the building, or the safe is behind the aquarium.
If there is no specific gaming information to be had by the persona, there will at least be a -2 DD bonus on performance table rolls following a successful case.

=== Climbing
This allows the spie to channel her inner monkey.
Spie climbing is a combination of freestyle and parkour.
It allows the persona to get to places they want to get to, however it does not necessarily plan for the best escape once there.

=== Concealment
Concealment is the art of hiding objects on the body of the spie.
It allows weapons, detectors, money, etc.
to be hidden in the fat folds, armpits, fur, and orifices of the spie.
A successful PT roll means that the spie can avoid discovery of items if she were subjected to a cursory strip search.
The DD can (and should) be adjusted by the ref for more lenient or stringent searches.

=== Cryptography
This skill can be used to encode or decode data.
The encrypted material can take on any form the spie sees fit.
The ref should adjust the DD so that the complexity of the code is reflected in the DD assigned.
Players must remember that many codes exist that cannot be broken without computer aids or other special keys.

=== Escape
The escape roll may be applied as an absolute last resort.
The escape roll is merely a way of delaying impending doom.
The skill is best described as "`out of the frying pan and usually into the fire`".
An escape roll can only be used by the spie to physically avoid the impending doom.
For example, the spie can only jump out of the way of the speeding two tonne robot;
she cannot disable it or make it crash.
The danger continues on its merry way;
only the spie may change.
The referee can deny an escape whenever she sees fit.

=== Forgery
This is the spie's art form.
Forgery skill ranges from falsifying initials on legal documents to counterfeiting campaign currency.
In some circumstances, the chance of successful forgery can be aided by previous casing.
Forgery is very time consuming.
Either the finished product takes a long time to create or there is tremendous amounts of practice involved.
The referee can upwardly adjust the DD level for counterfeiting as she sees fit.

=== Interrogation
This is the formal or informal pushing for information from a persona.
The spie will be able to get information from a victim by cajoling, deceiving, threatening, or hurting.

=== Lying
A successful PT roll will allow the persona to deceive lie detectors, immigration officers, legal cross-examination, or close scrutiny.
Again, good opportunities for roll playing should not be replaced with a die roll.

=== Picking Locks
A classic spie trick is the ability to bypass locking mechanisms on doors, safes, vehicles.
Lock picking is non-destructive, and it would be likely that anyone other than another spie would know if a lock has been bypassed.
Smashing a lock or shooting it with the Hollywood &#8220;unlocking blaster&#8221;
would not count as lock picking.
The referee would assign the degree of difficulty of the maneuver.

=== Picking Pockets 
Represents the removal of items from the pocket, flap, purse, or pouch of the primary observer.
For example, stealing candy from the bib of a 3rd level baby would add 3 DD.
The other two examples (table and demo) represent pilfering something from a display and simple magic tricks.
Failure indicates that the spie has been caught out and that fast talking, fast feet, or fast weapons are in order.
Success indicates that the victim, primary observer, or audience has been fooled.
The action rarely will deceive electronic surveillance equipment such as hidden cameras or alarm systems.

=== Stealth Movement
Stealth is like spie camouflage.
It represents the ability to hide in the shadows, move silently, and avoid detection by hiding in the shadows, moving quietly, remaining motionless, or playing dead.

=== Stunning
If the spie does not desire lethal combat but wants to incapacitate her target, she may attempt to stun her opponent.
The stun is a specialized martial arts attack.
The ideal opportunity for stunning the opponent is during an ambush when the spie can get a chance to stun before the target can even react.
If the spie must stun during combat, the skill is equally effective but the degree of difficulty is increased.
Stunning the opponent requires a successful to hit roll and then a successful PT roll.
The DD of the stun depends on the target's experience level and a random factor.
If the PT roll is successful, the target is stunned.
Only the first attack in a martial arts sequence can be considered an ambush stun.
Unsuccessful stuns inflict no damage and have no effect on the target.

=== Trap Defusing
A successful PT roll with this skill will indicate the laying of a deadly booby trap.
It could be as complex as a grenade triggered by an opening door or as simple as a concealed trip-wire.
The better the description of the trap, the more likely it will succeed.
The ref can adjust the DD depending on the complexity of the trap or other factors unforeseen by the spie.
Disarming traps can be done by spies or mechanics.

== Spie Experience
Spies obtain three quarters experience for combat.
Successful PT rolls are awarded by 50 EXPs per DD.
The acquisition of EXPs will allow the spie to increase in experience levels thus increasing her combat skills and spie skills.
For more information about earning experience, see Chapter 15:  Experience.

include::ROOT:partial$CH08_Table_Spie_Experience.adoc[]