= Spie

:art: spie.png
:width: 250px
:snark: Safe working environment.
:artist: Michael Jackson
:date: 1992
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The Spie is a tough, mean, ruthless, and lethal vocation.
Spies are highly skilled in unarmed combat, deception, and murder.
Spies can employ any combination of these abilities to satisfy their goals.
Spies can be of value to the expedition if they feel like it.
The cut-throat nature of the spie business does not mean all spies are psychopaths.
In the realm of extra-planetary espionage, it is hard to distinguish the bad from the not-so-bad.

Spies are an excellent source of dangerous assignments (from governments, corporations, societies or private citizens).
Spies are not totally dependent on a commission and may carry out a little extortion or kidnapping for their own profit (or fun).
Spies are often members of secret guilds or naughty lodges dedicated to the clandestine arts.
How deeply involved the expedition gets with a spie's source depends on the milieu or scenario set up by the ref.

[quote]
_____
A spie that initiates an act of counter-espionage (turning on her employer) is in trouble.
Whether turned by a higher authority or moral awakening massive trouble will result.
_____

== Spie Abilities
Abilities are skills that can only be carried out by the spie.
No other persona can engage in these acts.

=== Assassinate
Assassinate allows the spie to instantly kill a target with a single hit.
Under certain conditions, with the correct weaponry, a spie may carry out an assassination.
There are lots of required conditions for an assassination.

. Successful ambush (complete surprise)
. Appropriate weapon or attack
. Successful to hit roll
. Successful performance roll

An assassination cannot happen during combat or when the target is in a hyper aware state.
A flame thrower would be an inappropriate weapon but a Low powered pistol would be fine.
It is not about the damage the weapon can deliver but it's stealth.
There will be to hit bonuses due to the ambush state, but a to hit roll must be successful.
The degree of difficulty for the performance roll is equal to the target's AWE score.
The referee can alter the DD as she sees fit.

If all 4 pieces fall into place the target is irrevocably dead.
The victim cannot be medically repaired.
Their brain is mushed.

If the assassination performance roll is a fail the target takes damage.
If the damage kills the victim, it is not considered an assassination by the spie.

Whether robots and aliens can be assassinated is up to the referee. 
Assassination requires knowledge of the target's anatomy.

=== Disguise
Spies are naturally adept at not appearing as themselves.
A spie can alter the appearance of her hite and wate with no effort at all.
A spie can make herself appear 50% taller or 25% shorter.
A spie can make herself appear 50% heavier or 25% skinnier.
Only another spie can detect these simple disguise efforts.

More complex disguises like an impersonation for close interactions are much harder.
The spie must make a successful performance table roll at various times during the encounter.
The degree of difficulty is equal to the observer's AWE score.

The more intimate the disguise the harder the impersonation.
For example impersonating a family member would double the degree of difficulty.

Physical disguises must be of the same family and species.
Anthros cannot disguise themselves as aliens or robots. 
Vice versa applies. 
However an alien or robot spie would be a campaign altering persona to say the least.

There are also auditory disguises like voice impersonation which is less rigorous.
Imitating a persona over the phone halves the degree of difficulty.

A failed performance roll for disguise reveals the disguise but not the spie.
Further action must be taken to ascertain the spie's identity.

=== Martial Arts
Spies have their own style of deadly hand-to-hand combat.
The martial art includes kicks, punches, bites, chops, head butts, and body slams.
Spie martial arts is for unarmoured hand to hand combat.
Martial arts attacks are hand to hand and can only be used on targets in an adjacent hex.

The attacks are made as type A (thrusting and striking) attacks.
The damage adjustment (DA) is like a type B weapon (one quarter of PSTR).


include::ROOT:partial$CH08_Table_Spie_Martial_Arts.adoc[]

==== Amour Rating
A spie's armour rating (AR) is increased by dodges, parries, blocks, and rolls.
This armour rating does not work with mundane or tech armour.
This martial arts AR is for unarmoured dress like a tuxedo or bathing suit.

==== Attacks
This refers to the number of martial arts attacks the spie can make each unit.
If she wishes to combine martial arts with other weapons she must make a performance roll
The number of attacks applies to the number of martial arts attacks that the persona can make.
If this performance roll fails, she will suffer a to hit roll penalty of -300 on the weapon attack and -200 on her martial arts attack.

A first level spie gets one martial arts attack per unit. 
A fifth level spie gets three martial arts attack per unit.

==== Damage
A successful to hit roll delivers the damage listed.
The spie adds a damage adjustment of one quarter her PSTR.
A first level spie with a PSTR of 12 would do 1d4+3 HPS in damage per hit.
A fifth level spie with a PSTR of 12 would do 1d8+3 HPS in damage per hit.

==== Order
The attack order is ultimately the secret sauce of the spie martial arts.
The attack order allows the spie to get attacks in before and during opponent attacks.
The martial arts attack order is divided into three types.

* Normal - regular initiative and attack timing.
* Before - happens before opponent attack regardless of initiative
* During - happens simultaneous to opponent attack regardless of initiative

A first level spie gets one martial arts attack with a normal initiative roll.
A fifth level spie gets one attack before and one attack during the opponent's attack.

:art: mysterious_exit.png
:width: 250px
:snark: Out of the frying pan...
:artist: Leon Bennet
:date: 1879
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

== Spie Tricks (skills)
Spie skills are neat little tricks that are the trademark of any qualified spie.
The spie gets one roll per 4 points of INT on the Spie Tricks table.
She also gets one additional roll per experience level.
So a spie with a 12 INT would get 3 rolls on the table.
A first level spie rolls: concealment, concealment and cryptography.

.Example Spie Trick List
* Concealment 2
* Cryptography 1

The spie tricks are cumulative and combinable.
Whenever the spie is trying to conceal something she would get a skill bonus of +2.
If that concealment involved some sort of cryptography her skill bonus would be +3.

include::ROOT:partial$CH08_Table_Spie_Tricks.adoc[]

=== Bribery
Bribery is used to convince personas to act out of context for remuneration.
This trick allows the spie to do it better.
The degree of difficulty is determined by the referee.

Some upstanding citizens may refuse any attempt at bribery.
While others look at the additional remuneration as a business transaction
Bribery skill can be used by the persona to slip across a border line, get into a rock concert, or avoid a traffic ticket.
Personas cannot bribe people into damaging themselves.
The greater the risk involved for accepting the bribe the more difficult the performance roll.

Blackmail is a variation on bribery where the target is a victim and does not benefit in the transaction.

=== Casing
The spie can assess the risks of trying to penetrate a structure or location.
Casing can determine potential difficulties that may have to be overcome in order to successfully bypass security.
The difficulty of casing a joint depends on its security and size.

Successfully casing will yield specific information of importance to the spie.
For example, is there a trap or alarm system, are their guards, the safe is behind the aquarium.

A failed roll can be a lack of information or wrong information.


=== Climbing
This allows the spie to channel her inner monkey.
Spie climbing is a combination of freestyle and parkour.
It allows the persona to get to places they want to get to.

=== Concealment
Concealment is the art of hiding objects on the body of the spie.
It allows weapons or money to be hidden in spie's fat folds, armpits, fur, or orifices.
The difficulty is adjusted depending on the intensity of the  search.
A successful performance roll allows the spie to sneak stuff past a search.

=== Cryptography
This skill can be used to encode or decode data.
The encrypted material can take on any form the spie sees fit.
The ref should adjust the difficulty to reflect the complexity of the code.

=== Escape
The escape roll may be applied as an absolute last resort.
The a successful escape performance roll is only delays impending doom.
_out of the frying pan and usually into the fire_.
An escape roll can only be used by the spie to escape the impending doom.
The spie can jump out of the way of a giant speeding robot, but robot would not be harmed.
The referee can decline an escape roll to protect her campaign or story.

=== Forgery
Forgery is the spie's art form.
Forgery ranges from falsifying a legal documents to counterfeiting currency.
In some circumstances, the chance of successful forgery can be aided by previous casing.
Forgery is time consuming.
Either the finished product takes a long time to create or there is tremendous amounts of practice involved.

=== Interrogation
This is the formal or informal pushing for information from a persona.
The spie will be able to get information from a victim by cajoling, deceiving, threatening, or hurting.

=== Lying
A successful performance roll will allow the persona to deceive lie detectors, immigration officers, legal cross-examination, or close scrutiny.
A good opportunity for role playing should not be replaced by roll playing.

=== Picking Locks
A classic spie trick is the ability to bypass locking mechanisms on doors, safes, vehicles.
Lock picking is non-destructive, and it would be likely that anyone other than another spie would know if a lock has been bypassed.
Smashing a lock or shooting it with the Hollywood &#8220;unlocking blaster&#8221;
would not count as lock picking.
The referee would assign the degree of difficulty of the maneuver.

=== Picking Pockets 
Represents the removal of items from the pocket, flap, purse, or pouch of the primary observer.
For example, stealing candy from the bib of a 3rd level baby would add 3 DD.
The other two examples (table and demo) represent pilfering something from a display and simple magic tricks.
Failure indicates that the spie has been caught out and that fast talking, fast feet, or fast weapons are in order.
Success indicates that the victim, primary observer, or audience has been fooled.
The action rarely will deceive electronic surveillance equipment such as hidden cameras or alarm systems.

=== Stealth Movement
Stealth is like spie camouflage.
It represents the ability to hide in the shadows, move silently, and avoid detection by hiding in the shadows, moving quietly, remaining motionless, or playing dead.

=== Stunning
If the spie does not desire lethal combat but wants to incapacitate her target, she may attempt to stun her opponent.
The stun is a specialized martial arts attack.
The ideal opportunity for stunning the opponent is during an ambush when the spie can get a chance to stun before the target can even react.
If the spie must stun during combat, the skill is equally effective but the degree of difficulty is increased.
Stunning the opponent requires a successful to hit roll and then a successful PT roll.
The DD of the stun depends on the target's experience level and a random factor.
If the PT roll is successful, the target is stunned.
Only the first attack in a martial arts sequence can be considered an ambush stun.
Unsuccessful stuns inflict no damage and have no effect on the target.

=== Trap Defusing
A successful PT roll with this skill will indicate the laying of a deadly booby trap.
It could be as complex as a grenade triggered by an opening door or as simple as a concealed trip-wire.
The better the description of the trap, the more likely it will succeed.
The ref can adjust the DD depending on the complexity of the trap or other factors unforeseen by the spie.
Disarming traps can be done by spies or mechanics.

== Spie Experience
Spies obtain three quarters experience for combat.
Successful PT rolls are awarded by 50 EXPs per DD.
The acquisition of EXPs will allow the spie to increase in experience levels thus increasing her combat skills and spie skills.
For more information about earning experience, see Chapter 15:  Experience.

include::ROOT:partial$CH08_Table_Spie_Experience.adoc[]