= Mercenary

:art: mercenaries.png
:width: 250px
:snark: High tech merc vs lo tech merc.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Mercenaries are generally hardy, ready-to-fight sorts.
They are the fighters, the tough gals, and the paramilitary types of the expedition.
Mercs are valuable for the hodgepodge of combat skills that they possess.
They represent the dog-meat essential for the survival of any expedition in combat. 
Mercs do not personally regard themselves as dog-meat.

== Tale of Two Systems
EXP has a set of roll playing rules and a set of role playing rules.
The merc bonuses listed here reflect this tactical combat system in the roll playing rules.
The tactical combat system allows mercs to shine as efficient killing machines.
That is if you consider killing a shiney thing.

== Mercenary Abilities
Abilities are skills that only a mercenary can use. 

=== Bolstering AR (automatic)
When desired a mercenary can increase her armour rating by sacrificing her to hit bonus.
The mrcenary concentrates on being harder to be hit rather than hitting a target.
A mercenary does not have to use all of her Bonus Proficient solely to increase her chance to hit.

The mercenary does this by transfering her To Hit Bonus Porficient to her Armour Rating. 
This decreases her Bonus Proficient and increases Armour Rating.
A merc can transfer 20 BP points to AR per EXPS level. 
The amount transferred cannot exceed the mercenaries Bonus Proficient.
Only the pure attribute based Bonus Proficient can be used.
Other bonuses do not apply.
The mercenary can only use the bolstered AR against one attack per EXPS level.

Let's consider a 3rd level merc with a BP of 158, and an AR of 620.
She could drop her BP to 98, and increase her AR to 680.
This higher AR could be used against 3 different attacks. 

=== Divided Attacks (automatic)
Mercenaries can make extra attacks per unit of combat by dividing their Bonus Proficient.
Experienced mercs can increase the attack rate of mundane non-powered weapons.
This ability is limited to thrusting and striking (type A) and non-powered missiles (type B).
Powered weapons (Type C) have baked in rate of fire limitations.

They can get 1 extra attack per 2 experience levels.
The maximum number of attacks per unit is 4.
2 attacks at 2nd level, 3 attacks at 4th level, and 4 attacks at 6th level.

The attacks are delivered by dividing up her Bonus Proficient.
These attacks can be divided as the mercenary sees fit.
Let's consider a 6th level mercenary with a Type A BP of 210.
She could attack once with a BP of 210, or 3 times with a BP of +70;

To maintain game efficiency it is recommended that players have their calculations done in advance.

=== Ambidextrous Combat (12DD)
Mercenaries can use weapons with both hands without penalty.
Ambidextrous combat allows the mercenary to combine any weapon types they can carry.

.Example Ambidextrous Combos
* two rifles
* pistol and sword
* two swords
* aerosol and dagger
* two grenades

Under normal circumstances a persona would suffer a penalty of -200 and -300 for each attack.
If a performance roll is successful the mercenary does not suffer these penalties.
If they miss their performance roll the merc will suffer -200 and -300 on the two attacks.

If a mercenary wishes to combine divided attacks and ambidextrous combat the DD is 24.

==== Polydextrous Combat
Aliens can come with multiple attacks pre-evolved.
An alien mercenary would get the same abilities as any other mercenary.
It is recommended that polydextrous combat only double the number of evolved attacks the alien has.
For example, and alien with 2 natural attacks per round could get 4 attacks per round.
An alien with 8 decorative tentacles should not be able to wield 16 pistols. 

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

=== Absolute Proficiency (automatic)
Mercenaries are proficient in any weapon that they use.
So a merc using a new lazer pistol they just picked up would use her Bonus Proficient.
Absolute proficiency only works with fully identified personel weapons.
This ability does not work on weapon systems of mass destruction.
This ability does not work on artifact weapons that have not been identified as a weapon. 

=== Snap Reload (6DD)
The mercenary can reload her weapon and attack in the same unit.
A mercenary can reload without penalty with a successfully performance roll.
The snap reload can also be used as a snap weapon exchange.
Ambidextrous or divided attack reloads are more difficult.
A performance roll must be made for each weapon being snapped. 

Under normal circumstances a persona would not be able to attack while reloading or changing weapons. If the performance roll is unsuccessful the mercenary loses combat time like other personas. 

== Mercenary Skills
Skills that mercenaries have are determined by her INT.
A mercenary gets one roll on the table per 4 points of INT.
For example a mercenary with a 12 INT would get three rolls on the Mercenary Skills Table.
She rolls the following: Hand-to-hand, striking; Pistol weapons, revolver, XLP; Pistol weapons, revolver, MP and Grenades in Buildings

.example mercenary skills
* Pistol weapons 2
* Revolver 2
* Hand-to-hand 1 
* Striking weapons 1
* XLP extra low powered 1
* MP medium powered 1
* Grenades 1
* Buildings 1

Mercenary skills are cumulative and separable. 
The skills both improve performance rolls and chance to hit.
When reloading a Medium Powered revolver she would get a skill bonus of +5.
When attacking with a Medium Powered revolver she would get a to hit bonus of +100.
Assessing a building's fortifications a skill bonus of +1.
If assessing a building's fortifications vs grenades the skill bonus increases to +2.
If throwing a grenade in a building she would get +40 to hit.

=== To Hit Bonuses
Mercenary skills convert directly into combat skills as to hit bonuses.
Each skill point adds +20 to the player's to hit roll. 
This to hit bonus is not affected by the persona's Maximum Roll.
The player gets +20 per skill level when rolling to hit on the kilodie.

Using our example mercenary described above.
A sword is a a hand-to-hand +1 striking +1 weapon.
Her bonus is +2 for skills and +40 to hit.
A bow is a hand-to-hand +1 weapon.
Her bonus is +1 for skills and +20 to hit.

//assess playability for separable skills and effects on combat

include::ROOT:partial$CH08_Table_Mercenary_Skills.adoc[]

include::ROOT:partial$CH08_Table_Merc_Calibre.adoc[]

include::ROOT:partial$CH08_Table_Merc_Specialization.adoc[]

== Experience
Mercenaries gain experience from combat that they directly engage in.
If the mercenary does not inflict damage during combat, they do not receive EXPS.
If the merc was successful in combat then she will receive 100% of the experience point value of whatever she was fighting.
Mercs will also receive 25 EXPs per DD of successful performance rolls.
The more experience gained, the higher the level the merc attains.
Higher levels allow for more weapon skills and a greater chance of success in performing vocation skills.

include::ROOT:partial$CH08_Table_Mercenary_Experience.adoc[]