= Nothing

:art: nothing_sales.png
:width: 250px
:snark: Fun guy car sales.
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]


The nothing or civilian is more of a consolation class than anything else.
Those personas with attributes insufficient to enter any other class are forced to become nothings.
There are no attribute requirements for nothings (other than being alive).
The nothings are allowed to pursue any civilian employment provided that their skills can in no way aid them in regular adventure gaming.
The nothing serves little or no purpose for the expedition.
Some nothings from popular fiction and film are:  Arthur Dent (Hitchhikers Guide to the Galaxy, Otto (Repo Man), and Pinback (Dark Star)

The most important factor to a civilian (a nothing) is her ability to perform her mundane task and her social standing.
The importance of these variables can vary depending on the milieu that the referee has created.
For example, going to the best parties may be the drive of nothings in one culture while getting enough to eat may be the drive in another.
All nothings should determine their social standing, their wealth, and what they want to do with their life.
A nothing may pursue a real persona class or may specialize in becoming a high level nothing.

== Social Standing
The social standing is of great importance to the nothing.
It indicates where they are socially oriented in their society and how much money they tend to have.
A high social standing is synonymous with wealth and power.
Nothings determine their social standing with a kilo-die roll.
The higher the roll, the greater the social standing.
What form this social standing takes (famous celebrity, corporate power, or bureaucratic influence) is up to the ref and the scenario in which the nothing appears.

:art: nothing_suit.png
:width: 250px
:snark: Fully armoured nothing.
:artist: Imagestok-Studiostoks
:date: 2017
:license: Copyright Studiostoks 2017

include::ROOT:partial$articulate.adoc[]

The higher the social standing, the more likely a nothing is able to apply pressure on another civilian.
The mechanics of this is dependent on the milieu and the ref.
Nothings may have connections to lodges, clubs, or other such groups which will allow them to order other nothings around.

The simplest rule for which this can be played is by comparing the two persona's social standings (SS).
If a persona's SS is more than 200 points higher than a referee persona, then the player's persona could subtly apply pressure to the other and maybe force her to capitulate in circumstances where she otherwise might not.

If the player has chosen to pursue nothing as a persona class, she can increase her social standing as her experience level increases.
Each level that the nothing acquires, she may add 20 to her social standing.
This means that a 1st level nothing with a social standing of 367 would have a social standing of 387.

This is something that can only occur between nothings and other classes should be relatively exempt.
This feature of nothing SS should be applied with moderation;
it would be unrealistic for one nothing to drastically affect the life of another but it would be likely to play a part in a mundane type of thing such as butting in line or getting correct change.

== Origin of Nothing
All nothings receive one roll on Table 8.17:  Nothing Skill and Table 8.13:  The Origin of Nothing to give the persona some background history.

include::ROOT:partial$CH08_Table_Nothing_Origin.adoc[]

== Nothing Wealth
Unlike the other classes, the nothings receive rolls directly on the treasure tables.
How many rolls on the treasure table the nothing gets depends on her social standing.
The Treasure Table is found in http://expgame.com/?page_id=353[Chapter 53:  Treasure].
Table 8.14: Nothing Treasure is used to determine how the player will roll wealth for her nothing.
A campaign could easily revolve around a nothing that has spectacular wealth and connections.
How the wealth is represented (information, savings, land, stocks, technology, or industry) depends on the milieu and on the mood of the referee.

include::ROOT:partial$CH08_Table_Nothing_Wealth.adoc[]

== Nothing Class Pursuit
All is not lost for impoverished nothings.
They (and wealthy ones as well) may directly pursue any class except for knite, alien, or robot.
The class of knite can be indirectly pursued via the appropriate class (see knite in this chapter).
They will remain as nothings until they survive a trial period, after which they can become first level of a chosen class.
The trial period consists of about four experience levels of EXPs determined by the pursued class.
Once a nothing has achieved fifth level of a particular class, she can become a first level persona in her new class.
Upon reaching this point, they lose all experience accumulated as nothings and being to gain it as the learned class normally would.
For example, a nothing aspiring to become a mercenary must collect 18001 experience points to become a first level merc.
Once she has earned 18001 EXPs as a nothing, she would begin playing as a first level merc with 0 EXPs.

include::ROOT:partial$CH08_Table_Experience_to_First_Level.adoc[]

== Nothing Skills
Nothings can have some skills that are very significant to their social world but not too important in the world of gaming.
The nothing skills represent mundane and repetitious talents like baking, accounting, bricklaying, etc.
It will be a rare and unique circumstance when a nothing persona will be able to use her skills to assist the expedition.

There are certain skills that a persona may wish to hone for purely academic reasons.
For instance, a nothing may wish to become the best chef in the city, an established accountant, or the fastest cage cleaner.
If the nothing class has been chosen, the persona can add a skill roll for each level that she increases or she can increase her initial skill level by one.
A persona with accounting 3 would earn a 3DD bonus on the General Performance Table when carrying out accounting maneuvers.

include::ROOT:partial$CH08_Table_Nothing_Skills.adoc[]

== Nothing Experience
Nothings gain experience points differently from their pursued classes.
All nothings, regardless of pursued class, earn 10% of combat experience and one experience point for every 10 eps earned.
"`Earned`" monies must be collected while exploring and cannot be gifts, stipends, grants, awards, or salaries gathered without personal risk.
The pursuit of gold will no longer generate EXPs once the nothing has entered the new class.
If the player has chosen to pursue the nothing as a class, she can use the Nothing Experience table to determine her level of experience.

include::ROOT:partial$CH08_Table_Nothing_Experience.adoc[]