= Vocations

[quote]
____
*An aptitude and desire that exceeds a trade or profession.*
____

// must be a good image for here

The persona vocation represents the persona's profession or career.
Vocations are mainly in the domain of the anthro family.
Up to this point, the persona is nothing more than a list of attributes, a family, and maybe a few mutations.
The vocation should give the persona certain standards to attain, a reason to be or even an all-encompassing outlook on life.
This is obviously moderated by the wishes of the player running the persona but the vocation will shape the goals that she chooses for her persona.

== Nature of Vocations
As implied in the opening paragraph, the vocation isn't just the profession of the persona but it is an attitude too.
In actuality, it may be more of an attitude than a profession.
Choosing a vocation in EXP does not mean that the persona has had any special training.
There are no diplomas or degrees granted by professional institutions.
The majority of the information or skills that the player can utilize have been self-learned by her persona.
This lack of unified training has left many gaps in their knowledge which accounts for the persona's frequent inability to properly perform some tasks (and botch others altogether).

Even in the face of what appears to be continual failure, a persona will still pursue her vocation because the vocation represents innate abilities, desire, and personal interest.
A mechanic persona doesn't have an anti-grav maintenance diploma but a mechanic persona does have a keen sense for interpreting the physical world -- a miss fix-it or a bicycle repair person better fits the description.
A biologist wouldn't have a B.Sc.
in clone development but more likely would be a gardener, a farmer or an environmentalist.
All of the vocations are designed in this fashion.
The personas have a natural aptitude which is backed up by sparse bits of disorganized information.
More detailed descriptions of each vocation are given in this chapter.

== Vocations and Role-Playing
The effect that the choice of vocation has on the persona should be quite obvious.
The persona should be played with an obsession, or at least a keen interest, in her area of study.
Veterinarians should show compassion and a desire to heal;
biologists should show respect, if not awe, for the natural world;
and no anti-knite should pass up the opportunity to increase the Universe's level of entropy.

One general rule to observe is that the more skills that the vocation has, the more the vocation must be reflected in role-playing.
Nothings have no abilities and are free to act in any manner they wish;
while knites, laden with powerful skills, must follow a stringent code of honour.

Players that do not role-play their vocation properly (villainous veterinarians and altruistic anti-knites) are going to be punished.
At first, they are merely punishing their personas, cutting them out of vocation experience and maybe even role-playing experience.
If the transgressions continue or are particularly severe, the referee may take other forms of punitive action.
Veterinarians that have murdered other expedition members may find their skills ineffective on those who know the truth.
Nomads that insist on living in the lap of decadent luxury without at least complaining may find some of their survival skills very rusty.

== Specificity of vocations
Why are there vocations?
A vocation is a gross generalization of someone that is able to perform a group of procedures.
EXP could very easily have 42 separate vocations that have very specific skills and knowledge such as street cleaners, ammo testers, etc.
There are a much smaller number of vocations in EXP.
Each vocation represents a collection of abilities that are considered similar enough that they can be performed by one persona.

These general categories are represented by the eight separate vocations.
If the referee prefers many separate vocations or professions, more specialized sub-vocations can easily be evolved from the general vocation.
The newly spawned vocations could even continue using the main vocation`' Performance Table.

== Robot and Alien vocations
Robots and aliens are also vocations but they are very different from those listed in this chapter.
Robots and aliens are also vocationified as different families.
In fact, the two entities can be called vocation-families because these parameters are often inseparable.
If a player wishes to run either of these peculiar vocations, she must say so before she rolls any attributes, chooses a family, or rolls for mutations.
This preference must be stated early because robots and aliens have radically different procedures for generating their attributes.
The finished products are far afield of the conservative, bipedal canines and florians that are described in previous chapters.

There is also little freedom of choice with aliens and robot vocations because the dice determine every aspect of their nature, description, and purpose.
Beginning players probably should not attempt to play aliens or robots.
It is difficult enough to relate to strange new humanoids, let alone non-articulated boxes and blobs of protoplasm.
For much more information about robots and aliens see chapters 5 and 6.

== Selecting a vocation
The initial dice rolling that determines the persona's attributes also determines the persona's vocation.
The persona must pass attribute requirements before she can be a particular vocation.
These requirements exist to ensure variety amongst the personas and to ensure that vocations maintain certain requirements.
For instance, certain vocations have attribute requirements that must be met: trustworthy veterinarians must be charismatic;
spies must be dextrous;
mercenaries must have ample hit points, etc.

The referee must be absolutely ruthless when applying the vocation Requirement Table (Table 8.1).
Absolutely no fudging should be allowed.
Personas that lose attribute points during the generation of mutations or the choosing of a family and consequently cannot pursue a vocation that they desire are out of luck.
Players are welcome to plan ahead and choose a family that will allow them to be a certain vocation but once the path has been chosen, there should be no turning back.
Personas cannot be ejected from a vocation for attribute alterations that occur during the play of the campaign.
For instance, a veterinarian would not have to retire from that vocation because her CHA was reduced due to a facial scar.
Knites are no exception to this rule.

The persona's attribute must have a value equal to or greater than one listed on the vocation Requirement Table.
A nomad must have an AWE of ten or higher -- absolutely no exceptions.
A biologist must have a combined AWE and INT greater or equal to 18.
Thus a persona with an INT of four and an AWE of 14 can be a biologist because the combined value equals 18.
Once a player has determined which vocations she is eligible for, she may choose freely from any of them.

include::ROOT:partial$CH08_Table_Persona_Class_Requirements.adoc[]

Here is an example using a persona with the following attributes: AWE 6, CHA 15, CON 17, DEX 9, INT 14, MSTR 12, PSTR 6, and HPS 42.
This persona could be any of the following: biologist, mechanic, mercenary, nothing, or veterinarian.
The player has a wide selection of vocations to choose from.
It is recommended that the player read over all of the possible vocations in this chapter before choosing.

include::ROOT:partial$CH08_Table_Persona_Vocation_Example.adoc[]

== Multi-vocation Personas

There are often conditions where a player wishes her persona to have more than one persona vocation.
The conditions for this could arise from the player getting tired of certain persona vocation, the expedition needing a certain vocation or the persona wanting to get more involved in the game.
For instance, a mercenary mechanic could be effective in combat and also engage in artifact identification without risking the entire expedition.
Multi-vocation personas are not recommended for inexperienced players.
They are challenging to run from a persona and a refereeing standpoint.

*Combined*: A player can combine persona vocations from the beginning, advancing in each vocation at the same rate.
This can only be done with two vocations at a time.
If this is the case, she will function equally with either vocation.
For instance, she could function on both the veterinarian and the mercenary performance tables, earning experience for manoeuvres on both performance tables.
The amount of experience required for each new level will be equal to the sum of both vocations plus 10% of the total.
So a combined knite-biologist would need 4675 EXPS for 2nd level.
A combined vocation will generate toys as if both vocations were present.
Lastly, nothings can be combined with no vocations and knites cannot be combined with anti-knites.
The referee is completely in control of what combined vocations are appropriate for her milieu.

*Switching*: Switching vocations is different from combined vocations in that the persona neglects one vocation and begins to start fresh with another.
For example, a mercenary may suddenly get a conscience and devote the rest of her life to the study of biology.
If she has the appropriate attributes, this switch can be done at any time.
The new vocation is started at zero EXPS and advances in levels and EXPS acquisition as the new vocation.
The mercenary skills can still be called on but no experience will be earned for their use.
If the personal does not have the attributes to make a desired switch, she must pursue it through the nothing vocation.




