= Nomad

:art: nomad.132.png
:width: 250px
:snark: Urban nomad in city biome.
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]


Nomads are survivalists supreme.
They are experts at finding their way, constructing shelter, and doing well with nothing more than their bare hands.
Nomads can aid the expedition by providing a source of intuitive survival skills.
Nomads have an initial home base or biome (a biome is any easily distinguishable subsection of an ecosystem such as deciduous forest, tropical savanna, or radioactive ruins).
It is in such familiar territory that the nomad functions best.
The nomads`' skills are not limited to just these biomes but she will prefer them and enjoy DD bonuses when within their boundaries.
Nomads from popular fiction are Borellian Nomen (Battlestar Galactica, Ki (The Gods Must Be Crazy), Daniel Boone, Uil Gibbons Fremen (Dune), and your friendly neighbourhood bag lady.

== Nomads and Technology
Nomads will generally shun technology if it is unnecessary for survival, usually preferring to sleep in a hollow log or in a Smithrite garbage container rather than a hotel room or tent.
Nomadic skills are essentially unteachable.
The other classes are not able to grasp the subtleties necessary to adapt to and live off an environment.
This is something that players must remember and not waste role-playing time trying to do.
The nomadic skills were most likely acquired by the persona after she found herself isolated in some perilous situation and had to make do or die.
It is very unlikely that there are accredited schools of nomadic adventure.

== Nomadic Biomes
A biome is an environmental region that the nomad is familiar enough with that she will be able to survive within it.
The biome that the nomad originated from can be randomly determined on Table 8.10: Nomadic Biomes chosen by the ref or chosen by the player.
All nomads will have a start-up biome.

The nomad can acquire a new biome by gaining a complete experience level in a new area.
This means that a first level nomad from the desert travelling around on the tundra (a foreign biome) would gain tundra as an additional biome upon reaching second level.
The higher the experience level of the nomad, the more difficult it is to learn a new biome.
This is because the nuances and pitfalls of previous biomes cloud the newer ones and make them harder to learn.
This effect is reflected in the increasing experience level of the nomad.

Biomes are not planetary specific.
A biome on one planet is the same as an identical biome on another planet;
only the species are different.
Available biomes are listed on the Nomadic Biome Table.
The same table is used if the biomes are being randomly generated.
A biome may have special characteristics if the referee deems them necessary.

include::ROOT:partial$CH08_Table_Nomadic_Biome.adoc[]

include::ROOT:partial$CH06_Table_Alien_Biome_Characteristic.adoc[]

== Nomadic Skills
These are example skills that can be employed by the nomad.
These skills are generally personal and are harder to employ for another persona.
So a nomad may be able to find enough food for herself but unable to find food for another personal also.
The DDs vary because the nature of a biome is dynamic and what might be shelter one night might not be the next night.
The referee may also adjust the DD as she sees fit.
For instance, finding water while floating in a vac suit in outer space may be increased many times over finding water in a rain forest.
If the nomad were to still success, the referee must be prepared to explain the success in a fashion that doesn't seriously alter the nature of her milieu.

== Shelter (d4 DD)
This is the ability to either find or build shelter employing nothing other than the biome's materials.
The shelter can protect from the elements, local pests, or toxins.
The nomad must roll once per specific protection required.
Hiding out from local animals and background radiation would require 2 PT rolls.
Remember that the number of expedition members included increases the DD.

== Clothing (d6 DD)
This involves the design of protective clothing.
It could offer warmth, ventilation, or protection from inhospitable environments.
Camouflage clothing can also be fashioned from the local materials if another PT roll is made.
The nomad must roll once per set of clothing required.
Finding clothing or other personas increases the DD by 2.

== Safe Passage (d12 DD)
The nomad can determine a safe passage through seemingly impassable terrain:  mountain ranges, toxic areas, or a red light district.
It is potentially the most abused nomadic ability available.
The nomad must remember that the skill cannot be used to avoid a referee's detailed scenario;
although a good PT roll may alter the scenario's presentation.
A safe passage roll is required for each component of the safe passage required.
If the nomad wants safe passage through a city (a route through) and safe passage from the police (evasion), she would have to make two PT rolls.
A failure of this roll can mean either that no passage could be found (normal travel applies) or an unsafe one was determined (a critical failure on the PT roll).

== Poison Cure (special)
How difficult is it to cure the effects of poison depends on the intensity of the poison.
The DD = poison intensity.
Thus, an intensity 12 snake bit would require DD12 performance table roll.
There is no DD penalty for employing this skill on another persona.

*Husbandry (special)*: Nomadic husbandry involves the befriending and training of alien creatures.
If the ref has deemed the creature befriendable by the nomad, the DD is equal to the INT of the creature.
So trying to befriend a wumpus (a pointed, furry creature with a 4 INT) would be DD4.

Once befriended, the nomad can train the beasty to do various tricks.
The DD and time requirement is determined by the ref.
Some aliens cannot be trained at all, especially those with an organized social structure or sufficient free will to pursue their own class.
Robots cannot be trained by a nomad.
The ref should watch for abuses of this nomadic skill.
Pets will often run away if mistreated and the more intelligent the creature, the more difficult it is for the nomad to maintain a dominant relationship.
It will be difficult for the nomad to convince the animals to leave their biome.

The nomad will be able to teach tamed animals up to one trick per experience level.
The tricks can only be simple commands but it will take a PT roll versus d12 DD to make the trick stick.

Once the trick has been learned, the nomad will also have to check to see if the commend itself is successful.
The DD of successfully commanding the animal depends on how many tricks that the animal has learned and nothing else.
If the animal knows 2 tricks, commanding it will be a DD2 maneuver.
Command failure in animal husbandry should have humorous effects if at all possible.

*Tracking (special)*: Nomads can track anything that they want.
A successful PT roll will indicate that their prey has not escaped.
Complications such as flight, burrowing, and phasing out will adjust the DD.
The DD should be decreased for larger pretty or prey that is ignorant that it's being tracked.

Once the nomad has decided to track something, it is determined how long the chase will take (2-200 hours) and at the end of this the PT roll is made.
Thus tracking time can indicate the number of hours to discovery or the number of hours until giving up.
Distractions and diversions during the chase can alter the chance of success (adjusted as the ref sees fit).

Reverse tracking is used by the nomad to determine if she is being followed.
It is a much harder skill to employ but it yields an answer immediately.
Reverse tracking is a personal skill.

== Food (special)
Here are four skills relevant to the acquisition of food in the wild.
They are based on the requirements of one normal sized person for one day:  find a gather (3 + d6 DD);
prepare safely (4 + d6 DD);
cook (1 DD);
and preserve (6 + d6 DD).
Only the first two PT rolls (gather and prepare) are necessary to supply the daily nutritional needs of the nomad.

== Fire (1 DD)
The ability to produce fire from local materials.
The DD should be increased in poor atmospheric or climatic conditions.

== Safe Campsite (d8 DD)
Successful use of this skill can determine if the chosen camp is safe from natural disasters (e.g., avalanches, floods, fallout, or worse).
Safe campsite designates an area that is safe and any persona within this area is safe from the biomes`' natural disasters.
This skill can be used to reduce the chance of being found by local hungry life forms.

== Water (special)
Collecting water is a 3 + D4 DD action and it can only supply enough water for one person for one day.
To locate a continual source of water (spring, well, or water main) is an 8 + d4 DD maneuver.
All collected water should be routinely purified (5 + D4 DD).
This will eliminate any bacteria or toxins that are unaffected by boiling.

== Nomadic Experience
Nomads get half experience for combat and 30 EXPS per DD for successful PT rolls.
Increasing levels allows the nomad a greater chance of survival in the wild or combat.

include::ROOT:partial$CH08_Table_Nomadic_Experience.adoc[]