= Mercenary

:art: mercenaries.png
:width: 250px
:snark: High tech merc vs lo tech merc.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Mercenaries are generally hardy, ready-to-fight sorts.
They are the fighters, the tough gals, and the paramilitary types of the expedition.
Mercs are valuable for the hodgepodge of combat skills that they possess.
They represent the dog-meat essential for the survival of any expedition in combat, though they may not personally regard themselves as such.

The skills that mercs possess have been acquired mostly through plain old blood-thirsty interest -- and a liberal dose of on-the-job-training.
The skills rolled by mercs represent weapon skills.
These weapon skills allow for bonuses to hit and increased chances of successfully doing merc-like things with the particular weapon type.
The players receive one roll on the Mercenary Skills table for every four points of INT.
The player is also entitled to one roll on the Mercenary Skills table for every new experience level.

== Theatrical Combat System Skills
When using the theatrical combat system, the mercenary skill table offers no bonuses to hit.
When a player rolls a weapon type on the Mercenary Skill table, it indicates that she can use this weapon.
So a merc that rolled hand-to-hand striking weapons could use swords, maces, and hammers without penalty.
The theatrical combat system is for combat resolution in non-combat campaigns.
It is explained in Chapter 26:  Theatrical Combat.

== Tactical Combat System Skills
The tactical combat system allows mercs to shine, if you can call efficient killing in armed combat shining.
There are many skills beyond weapon proficiency that the mercenary can employ in the tactical combat system.
For more information about the tactical combat system, she Chapter 27: Tactical Combat.

== Weapon Skill Bonuses
For the tactical combat system, mercs not only become proficient in the weapons rolled but they earn bonuses to hit also.
Let's use a persona with four skills as an example:

* Hand-to-hand;
striking
* Pistol weapons;
revolver;
XLP
* Pistol weapons;
revolver;
MP
* Grenades;
buildings

Each fraction of a weapon skill is worth +20 to hit.
This means that +20 or more is added to the player's kilo-die roll when trying to score a hit.

If the persona were attacking with a sword, she would get a +40 to hit because it is both a hand-to-hand weapon and a striking weapon.
If she were using a bow, she would get a +20 to hit because the bow is considered hand-to-hand but not a striking weapon.

If this merc were using a laser pistol, she would get +40 to hit because the skill pistol weapons appears twice.
If she were using a HP revolver, her bonus to hit would be +80 because both pistol weapons and revolver skills appear twice.
Note that these skills are not randomly applied.
For example, the medium powered (MP) caliber skill can only apply to revolvers.
Also a semi-automatic pistol skill cannot be applied to a semi-automatic rifle.

This persona would also receive +20 to hit with grenades and +40 to hit when using grenades inside buildings.

This persona is most skilled in using a MP or XLP revolver.
With an XLP revolver, she would get +100 to hit.
On the other hand, this mercenary is least skilled in rifle weapons and would receive no bonuses to hit.

== Bolstering of Amour Rating
A mercenary does not have to use all of her Bonus Proficient solely to increase her chance to hit.
A special skill of the mercenary can make her much harder to be hit, instead of concentrating on hitting a target.
This could prove to be necessary for a number of peculiar reasons.

A mercenary can bolster her AR by up to 20 points per experience level.
The total of this AR bonus is subtracted from the merc's to hit roll in the same unit.
The player running the merc must announce their intention to bolster their persona's AR in the preceding unit.

The total amount of bolstering available is limited by several factors.
The merc can never use an amount that exceeds her BP for the attacking weapon type.
So if a merc's BP for Type A is 158, she can never bolster her AR against Type A attacks by more than 158.
Special weapon bonuses do not apply.
The AR bolster can only be used against one attack per level, per unit.
This means that a 1st level merc could add 20 to her AR against 1 attack while a 5th level merc could possibly add 100 to her AR versus 5 attacks.
Experience level is the only limit to the number of attacks that the persona can defend against.

== Multiple Attacks
Mercenaries can increase the number of attacks they get with Type A and Type B and some Type C weapons.
They can get 1 additional attack per 2 experience levels per unit.
This means 2 attacks at 2nd level, 3 attacks at 4th level, and 4 attacks at 6th level.
The number of attacks cannot exceed 4 per unit.
If the player elects to have her persona attack more than once per unit, she must divide her BP (plus applicable skill bonuses) amongst the attacks.

For instance, a 6th level merc with a BP for Type A of 210 could attack 3 times at +70;
2 times at +105;
1 time at +210;
or 1 time at +200 and 2 times at +5, etc.
The player must determine how many attacks she is going to make and and what the bonus will be per attack in the unit preceding the multiple attack.
Once she has stated that she is going to make multiple attacks, she is committed to the pattern chosen.

Note that combining multiple attacks with bolstering of the AR can produce some pretty wild calculations and the players applying these merc skills must ensure that they are properly prepared each unit and that they are not slowing down combat for everyone else.

== Ambidextrous Combat
A mercenary can fight as an ambidextrous persona if the player running her successfully makes a PT roll each unit of combat.
Personas using two weapons simultaneously would normally suffer a penalty of -200 and -300 on the two attacks.
This is a penalty of -200 on the persona's dominant paw and -300 on the person's non-dominant paw.

This penalty applies to any combination of two weapons: rifle and pistol;
two rifles;
pistol and sword;
two swords, etc.
If the player makes her PT roll, the persona can use two weapons simultaneously without suffering the -200/-300 penalty.
This penalty is described in better detail in Chapter 35: Combat Adjustments.
If she fails the PT roll, the merc will suffer the penalty as would any other persona.

Combining ambidextrous combat with multiple attacks can create a formidable hand-to-hand combatant indeed.
If ambidextrous combat is attempted, the degree of difficulty will be doubled.
If the performance table roll fails, the merc will subtract 200 from good handed to hit rolls and 300 from her weak handed to hit rolls.

== Absolute Proficiency
Mercenaries are the only class that are proficient in any personal weapon that they can identify and understand the workings of.
A merc could use any rifle with her BP provided that she can identify it as a rifle.
This skill only applies to weapons of a personal nature and not to weapons of mass destruction or of a strategic nature.

== Snap Reload
A mercenary can reload and fire in the same unit if she successfully makes a PT roll.
If the PT roll is unsuccessful, she will lose combat time to reloading like any other persona.
If the merc is using ambidextrous combat, she must make two successful PT rolls.
Failure in either roll will leave both weapons unloaded.
The snap reload ability of mercenaries can also be used as a snap weapon exchange, switching from one weapon to another and still being able to attack in that unit.

include::ROOT:partial$CH08_Table_Mercenary_Skills.adoc[]

include::ROOT:partial$CH08_Table_Merc_Calibre.adoc[]

include::ROOT:partial$CH08_Table_Merc_Specialization.adoc[]

== Experience
Mercenaries gain experience from combat that they directly engage in.
If the mercenary does not inflict damage during combat, they do not receive EXPs.
If the merc was successful in combat then she will receive 100% of the experience point value of whatever she was fighting.
Mercs will also receive 25 EXPs per DD of successful PT maneuvers.
The more experience gained, the higher the level the merc attains.
Higher levels allow for more weapon skills and a greater chance of success in performing class skills.

include::ROOT:partial$CH08_Table_Mercenary_Experience.adoc[]