= Nothing

:art: nothing_sales.png
:width: 250px
:snark: Fun guy car sales.
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The nothing, aka civilian, is the non-vocation vocation.
A player may choose her persona to follow the Nothing vocation.
There are no requirements, other than being alive, to follow the Nothing vocation.

The Nothing is only concerned about their pointless career, their social standing and money.
A Nothing career has no measurable value to the expedition.
The nothing serves little or no purpose for the expedition.

.Nothing Vocation Elements
. Origin
. Social Standing
. Career
. Wealth

== Origin of Nothing
Nothings are not from nowhere.
The nothing origin is like a biome where her social standing and wealth mean the most.
A nothing adds an new origin each new EXPS Level.
The more the nothing gets around the better her career and social standing.

include::ROOT:partial$CH08_Table_Nothing_Origin.adoc[]

== Social Standing
Most personas rolled their social standing (SS) when generating attributes.
The Nothing's social standing is the root of her self worth.
Other personas have their vocations for self esteem.

The higher their social standing (SS) more powerful the nothing is.
Social standing is synonymous with wealth and power.
Regardless of how famous the nothing their skills mean nothing to the expedition.

=== Pulling Privilege
A nothing  can apply social pressure on another nothing to try and get their way.
The process usually involves using connections to get their way.
The nothing with the higher SS will get their way.
The mechanics of this can vary with the milieu and the story.

Pulling privilege does not work on personas with vocations. 
This ability can only be used on other nothings for inconsequential outcomes.
For example, getting into a club, butting into the line, getting show tickets etc.

:art: nothing_suit.png
:width: 250px
:snark: Fully armoured nothing.
:artist: Imagestok-Studiostoks
:date: 2017
:license: Copyright Studiostoks 2017

include::ROOT:partial$articulate.adoc[]

=== Improving Social Standing
The persona  can improve her social standing by increasing her EXPS levels.
This cannot be done if the nothing has a <<_nothing_vocation_aspiration,vocation aspiration>>. 
Nothings aspiring to another vocation pour all their experience into that goal.
Nothings that are following the vocation of Nothing can increase their Social Standing.
A Nothing adds 1d100 to her Social Standing for each new EXPS level.

== Nothing Wealth
Unlike the other vocation, the nothings receive rolls directly on the treasure tables.
How many rolls on the treasure table the nothing gets depends on her social standing.
A campaign could easily revolve around a nothing that has spectacular wealth and connections.
How the wealth is represented (information, savings, land, stocks, technology, or industry) depends on the milieu and on the mood of the referee.

include::ROOT:partial$CH08_Table_Nothing_Wealth.adoc[]

== Nothing Career
The Nothings career is significant in their social world but not in expedition explorations.
It will be a rare circumstance when a nothing will be able to use her skills to aid the expedition.

A nothing can pursue greatness in their Nothing Career.
This is determined by social standing an nothing else.
A nothing may aim to become the best chef in the city, an accountant, or the fastest cage cleaner.

This cannot be done if the nothing has a <<_nothing_vocation_aspiration,vocation aspiration>>. 
Nothings aspiring to another vocation pour all their experience into that goal.
Nothings that are following the vocation of Nothing can add new careers.
A Nothing adds one new career for each EXPS level.


include::ROOT:partial$CH08_Table_Nothing_Skills.adoc[]

=== Nothing Vocation Aspiration
A nothing can pursue a full fledged vocation if they desire.
Vocation aspiration must be clearly stated by the player to the referee.
All experience earned goes into the goal of getting to first level in the chosen vocation.
Nothings cannot use money EXPS to get to the EXPS for their vocation aspiration. 

A nothing aspiring to become a mercenary must collect 18001 EXPS to become a first level merc.
Once she has earned those 18042 EXPs she becomes a first level mercenary.
The persona leaves the Nothing vocation and becomes a full fledge merc with 0 EXPS.

include::ROOT:partial$CH08_Table_Experience_to_First_Level.adoc[]

== Nothing Experience
Nothings gain experience points from earning money.
Nothings only get 10% of combat experience.  
Nothings are the only vocation that earns from money.
A nothing earns 1 EXPS for every 10 eps earned.
Earned means monies collected from life threatening exploration.
Earned does not include gifts, stipends, grants, awards, or risk free salaries.

If the player has chosen to pursue the nothing as a vocation, she can use the Nothing Experience table to determine her level of experience.

include::ROOT:partial$CH08_Table_Nothing_Experience.adoc[]