= Biologist

:art: biologist.png
:width: 250px
:snark: Watching a biologist watch
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Biologists are personas which have inherent interest and skill in understanding nature.
They are best described as self-educated naturalists that still have a lot to learn.
Their personal interests could range from fungi to DNA;
such knowledge may or may not have any practical field application.
Biologists come through for the expedition when it is exploring unknown terrain.
Such terrain may harbour aliens or hazardous plant life.
The biologist is essential if the group expects to determine if these encounters are benign, dangerous or worse.

Biologists are free to act how they wish but they are expected to at least try to identify a new specimen before vaporizing it.
Specimens may be most easily observed when they are dead but then subtle behavioural traits are impossible to detect.
Thus there are definite advantages for the biologist to identify and observe specimens before a hostile encounter takes place.
In this regard, the biologist may find herself directly opposed to the goals of other expedition members.

The haphazard nature of biological knowledge acquisition has already been alluded to.
Their information sources are usually things like: gardening books, environmentalist leaflets, nature shows, sagely advisors, and maybe even the odd biology lecture.

The persona is expected to have had some special interests within the field of biology itself.
These areas of interest are determined randomly on Table 8.2: Biologist Skill.
The player may make one roll for every four points of INT.
The biologist will also receive one additional roll for each new experience level attained.
The rolls indicate areas of special interest which increase the biologist's chances when attempting to apply her skills.
The persona can attempt to do any biological type of activity that is within, or not within, her areas of special interest.
The special skills indicate that she will be more likely to succeed if what she is doing falls under one of her areas of special interest.

A player running a biologist with a 12 INT would get three rolls on the Biologist Skill table.
Because the table is from 01 to 00, she should roll deci-dice.
Her rolls are 11, 20, and 97.
This indicates three major concentrations: plants, animals, and camouflage.
Plants and animals also have specific concentrations and both require additional deci-dice rolls.
She rolled 77 for plants which means she has a specific concentration of plants: mosses.
A roll of 46 for animals would mean that she has further specialization in animals: worms.

The skills help her when she rolls on the Biologist Performance Table (PT).
Each concentration reduces the degree of difficulty (DD) by two.
If the biologist were trying to identify an animal that was a worm-type alien, she would receive -4DD (the higher the DD, the more difficult the roll).
If the worm also specialized in camouflage, she would receive another -2DD reduction (because her other major concentration is camouflage), bringing her total bonus to -6DD, increasing her chances of success greatly.
For a much more detailed description of how PT's work, refer to chapter 14: Performance Tables.

This particular camouflaging worm may be causing problems for the expedition because it keeps burrowing into the landing pads of their all-terrain aircars.
The worms are uncommon (DD6) but the ref feels that this is more rare a worm;
she adjusts it upwards.
The final DD is 7.
Because of the player's special interests, the DD is reduced to 1.
Being first level, she would have to roll 90 or higher on percentile dice in order to successfully identify the alien.
Since she also has an up to date notebook on worms, she can add her AWE to the deci-dice roll.
After identifying the irritating worm, she can determine why it burrows into the landing pads and possibly even a way to prevent it.

== Biologist Skills 

include::ROOT:partial$CH08_Table_Biologist_Skill_Stream.adoc[]

=== Taxonomy Stream

include::ROOT:partial$CH08_Table_Biologist_Taxonomy_Stream.adoc[]

include::ROOT:partial$CH08_Table_Nomadic_Biome.adoc[]

=== Cultural Stream

include::ROOT:partial$CH08_Table_Biologist_Cultural_Stream.adoc[]

=== Research Stream

include::ROOT:partial$CH08_Table_Biologist_Research_Stream.adoc[]

*Biologist EXPS*: The benefits of increasing experience levels are: more skills, increased performance, and marginally better combat skills.
Biologists earn experience points for successfully completing PT rolls (90 EXPS per DD).
Only 20% of combat experience can go towards a biologist's experience point total.
If a biologist is consistently destroying potential specimens, the ref may forfeit combat experience altogether.
