= Incidentals

[quote]
____
To avoid incidents don't miss the incidentals.
____

The incidentals are the left over bits from the persona creation process.
They are here for a convenience and not an attempt to wreak havoc with a referee's milieu.
Take from the incidentals what the personas need. 

:art: backpack.png
:width: 250px
:snark: Stuff in your stuff.
:artist: Warren Oddsson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

== The Materials
These are the real items that most personas need to survive in EXP.
These items are entirely dependent on the world created by the referee and the players.
If there is are no tools don't roll for Mundane Equipment.
If there is no money don't generate Start Money.

Anthro personas usually need the mundane materials included here.
Robot personas have no use for anything in this section.
Alien personas usage depends on their society and tool using status. 

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

=== Start Money
This is money in the pocket of the persona at start up.
It might be their life savings in a satchel or credit on their plastic money card.
The default currency in EXP is the eps (electrum piece).
The nature of money depends on the back story created by the ref and players.
Money nomenclature is discussed more thoroughly in the xref:ii-roll_playing_rules:CH23_Money.adoc[Money] section.
If large amounts of money is needed refer to xref:iv-hardware:CH53_Treasure.adoc[Treasure].

include::ROOT:partial$CH10_Table_Persona_Start_Money.adoc[]

=== Start Equipment
To expedite the expedition exploring the referee can extend start equipment to the personas.
Start equipment is only appropriate if it fits into the milieu of the ref and players.

This equipment will be of the mundane variety.
Here mundane means lo-fi, lo-tech tool level equipment.
Slightly higher tech equipment is available.
Higher tech equipment is lighter and costs more.
There are no artifacts available for purchase in the incidentals. 
Personas get artifacts from the Technological Object Yield System (TOYS).

NOTE: *High tech equipment are called artifacts or toys.*

Players can take their start money over to xref:ii-roll_playing_rules:CH24_Mundane_Equipment.adoc[Mundane Equipment]
 to collect their start equipment.
For players not interested in pouring over lists a mundane survival pack is included here.

==== Survival Pack
The survival pack costs 70 eps, and has a wate of 13.5 kg.
The survival pack is designed to speed up the equipment buying procedure.
A ref may not allow the survival pack to be purchased as one lump, but the list of equipment can be used to ensure that each expedition member is properly equipped.

include::ROOT:partial$CH24_Table_Survival_Pack.adoc[]

=== Start Toys
Toys are special equipment generated on the Technological Object Yield System.
The terms artifact and toys are used interchangeably.
Although artifacts sounds more serious.
The toy system employs countless deci-dice rolls to produce a nondescript black box.
The referee and players will decide if personas start the campaign with toys or not.
The intended use of high tech artifacts can be completely opaque to the persona.
Figuring out what an artifact does reflects the technological chaos of EXP.

Mundane items have obvious uses.
Artifacts and toys do not have obvious uses. 

include::ROOT:partial$CH24_Table_Mundane_Tech_Levels.adoc[]

If the milieu permits personas to have start toys head over to xref:iv-hardware:An_index_hardware.adoc[Hardware] to get some toys.

== The Immaterials
The immaterials are what makes the persona a persona.
These are the unrollable characteristics of the persona.
This is where  the player gives her persona character and flare.

=== Name
The player must name her persona.
Every persona must have a moniker, call sign, label, title, handle or cognomen.
A player should avoid naming her persona with her mundane world real name.
Creating a persona name makes role-playing more fun.

==== Anthros
Anthro names follow standard role playing game nomenclature. 
Each anthro will usually have a given name and a surname.
Both the given name and surname are created by the player.
The anthro naming structure is most familiar naming structure.

==== Robots
Robot names can get complicated.
Every robot has a given name.
The given name was imagined by the robot's malfunctioning brain.
The given name is created by the player.

Robots can also have a model name and a fabricator name.
Model and fabricator names are optional.
The model and fabricator names are usually created by the player.
The referee may have pre-made model names and fabricators that reflect her milieu. 

The robot name created here can always be used in common parlance.
Names that sound like fax machines, look like bar codes or have 600 numbers are only used between robots.

==== Aliens
Alien names can get complicated.
Every alien has a given name and a species name.
The given name is created by the player.

Every alien also has a species name.
When an alien is evolved it represents one member of an entire species.
The species name describes every other alien persona that is not the player persona.
Species names reflect elements of the alien itself. 
Using Latin sounding words in a double hander makes the species name sound fancier.
A tiny poisonous alien may have the species name Minutiae Venonimous.
This naming opportunity comes with great responsibility.
Usually the referee and players will negotiate the species name.

The alien name created here can always be used in common parlance.
Names that are composed of pheromones, howls, or ultrasonic clicks will only be used between the alien species.

==== Example Persona Names
Persona names do not _have_ to be silly. 

.example persona names
* A mechanic - Hans Tinker
* A mercenary - Hans Grenade
* A nothing - Hans Ophmistuph
* A janitor robot - Kl33nr by Home Systems Inc
* A social robot - QT by Androgena Compositors
* A gigantic alien - Kolosaur of Herbiforous Giganticus

=== History
Pre-campaign history is determined by vocation, family, and place of birth.
Players can create their own pre-campaign history or work with the referee to create one.
A persona's initial should not be one of great fame or import.
Fame and reputation should be created by role-playing in the campaign.

Pre-campaign histories ought to be very simple.
An ursidae that came from the cold mountains.
A humanoid that inhabits a tropical forest.
A robot that has no recollection of anything at all.
The pre-campaign history is a tool for the referee to brief the players on their new world.
The players make their own history.

=== Description
How would you describe your persona to another person (or persona).
Anthro players pick an anthro type and sub-type when being delivered.
Alien persona appearance is determined during their evolution.
Robot personas are built out to a basic shape during fabrication.

The player can embellish her persona with further details: adornments, smells, colours, coverings, coats and coatings.
The player creates the persona's clothing, jewelry, fur texture, paint color, and eye(s) shape.
Overly detailed personas descriptions are fun for players to make.
Overly detailed personas are less fun for other players to hear about.
Concise, fun, descriptions make for more compelling personas.

=== Personality
A persona should have a personality of some sort.
Most often the persona will be a reflection of the player's persona.
Experienced players will create a personality for their persona.
The personality could be emotionally based, belief based, or vocation based.

The persona may exude extroverted traits like distrust of veterinarians, abject fear of reptilians, compulsive desire for battle, or an overwhelming worry about the present predicament.

The main challenge is that the personality remains consistent.
How consistent the persona's personality is not set in stone.
Staying alive will require a persona to switch from trusting to paranoid in an instant.

NOTE: *The goal of persona personality is to have a point of view and have fun exercising it.*
