= Referee Personas


A Referee Persona (RP) is any persona -- alien, bot, or anthropomorph -- that is not run by a player.
Anything not run by a player must be brought to life by the referee.
Any entity the ref controls is essentially an referee persona of one type or another and only the degree of the referee's involvement varies.
The referee is responsible for controlling the planetary denizens that wander about on uncharted planets and she is also responsible for portraying the personas that may join the expedition in their campaign.
The difference in preparation of these two examples is enormous yet they both fall under the category of referee personas.

== Referee Role-Playing

It is the responsibility of the ref to role-play referee personas to the best of her ability.
For example, intelligent aliens must seem and act intelligently;
nomads will never sleep in a bed if it can be avoided;
anti-knites must be absolutely ruthless, sparing no personas in their righteous path;
aliens must be alien in personality as well as structure;
robots do not have facial expressions or body language.Presenting these sorts of character identities is the responsibility of the ref.
Referees must be as diligent in ensuring the uniqueness of the various personas as they are in ensuring the originality of their scenarios.
They must be prepared for a form of controlled schizophrenia as it may be necessary to switch from one referee persona to another in an instant.

Referees cannot expect of themselves repeated brilliant performances of wholly unique personas nor will the player always notice or appreciate such displays.
The players are there to role-play and have fun and the referee is there to role-play and have fun too.
It is also the referee's job to ensure that precious game time is shared between the personas and the referee personas.
To be more blunt, referees have to be egotistical attention seekers (or they wouldn't be referees) and they must ensure that they don't take over the show and bore the rest of the players.
(Enough of this referee-player pseudo-psychological investigation!)

Regardless of the involvement of a referee with her referee persona (RP), she cannot afford to get attached to her personas like the players do.
Referee personas may serve no purpose other than cannon fodder;
they may depart the scenario at any time either violently or by choosing a separate path from the expedition.
Often referee personas will simply be dispatched by paranoid players.
Regardless of the importance of a referee persona, the referee must be ready to part with them at any moment because they will always end up on the referee persona scrap heap.

== Generating a Referee Persona

An RP includes all the components a persona does plus a few more.
An RP is expected to have experience levels and a collection of toys.
A simple system is given to randomly determine an RP's type, attributes, class, level, personality, etc.
The system is outlined in the Referee Persona Checklist.
Most often the ref will have some idea of what kind of an RP is desired.
This system can be used to flesh out some (or all) of the information which the ref has not already decided on.

== Referee Persona Checklist

// insert table 251

== 1) Origin, Presence, and Goal

As previously stated, referee personas can have a wide degree of involvement in a campaign or with an expedition.
All referee personas must have an origin, presence, and goal.
The origin of an RP should explain where it came from and why it things the way it does.
The presence of the RP will dictate how and why it interacts with the expedition.
The goal of an RP is what it wants from the campaign, dictating what it will do with the expedition and when it will part company.

For 95% of the RPs the expedition will encounter, the Trinity of the RP (origin, presence, and goal) will be pre-determined.
Referee personas such as innocent civilians and animals will have simplistic origins such as migrating through the area or on their way to work.
Their presence might be riding on the subway or rummaging through the bushes.
Their goal may be to find some berries to eat or to get to work on time.
If the expedition frequently intervenes in the lives of such unimportant referee personas, the referee need have no more prepared than usual.

If the referee persona is a more important one the referee must create  a more detailed origin, presence, and goal.
Let's consider a young man from the farming district of his impoverished planet (origin) is willing to hire on for the expedition as a porter (presence) if they will take him off planet (goal).
Another referee persona could be a very hungry alien that just jumped out of a tree (origin) and is ferociously attacking the expedition (presence) because the alien's hungry and the expedition members look like something good to eat (goal).

Other RPs may have much more complex origins, presences, and goals.
Vishna Shraloor is a referee persona with death field generation (a mental mutation).
She matured not knowing that this lethal power was within her.
She grew up through a series of profound personal tragedies: the death of her parents, the death of teachers, the death of mourning relatives, the death of her playmates, the death of social workers, and the death of foster parents.
Many of these deaths may have been caused by her misunderstood mental ability.
That is her sad origin.

Vishna's presence is one of a lonely unhappy persona who constantly associates with people she does not like because the people around her tend to die frequently.
Her profession is that of an orbital satellite repair person, a solitary job for certain.
She has chosen to hang around with the expedition because she does not particularly like them much.
This is her presence.

Ms. Shraloor's goals are varied.
She would like to destroy the society that has rejected her so totally and she sees the expeditions mentality as something that she can exploit to this end.
If an expedition member should happen to befriend her, show her the nature of her mutation, and nurse her through the subsequent guilt, she may follow another path and desire to help the society that continued to reach out to her despite their extreme risk.
These are her potential goals.

This chapter provides no guidelines on preparing an origin or goal for the referees personas but it does help with the presence of the referee personas.
In fact, this chapter could be considered a guide on how to prepare a referee personas presence.
If the ref knows that she needs RPs but has no origins or goals, then it might help to create the persona presence first.
This is an excellent procedure for sparking the imagination or solidifying a watery idea.

// insert table 253

// insert table 254

// insert table 255

== 2) Determine Referee Persona Type

The type of referee persona chosen by the referee should be predetermined by the nature of the story being told in the campaign.
This should also dictate the depth of persona development required.
There are three persona types that the referee can choose from.
As a rule, the most frequently chosen will be that of an anthropomorph.
EXP is a humanocentric game and the rules are best suited for play by upright, bipedal, anthropomorph personas.
The other two referee persona types are aliens and robots.
Highly developed alien and robot personas will be extremely rare, but this depends on the ref's milieu.
The referee should know exactly what type of persona she wants and the RP creation system should be used to flesh out this precast persona.
If, and only if, the referee is completely and utterly stumped should she refer to the Referee Persona Type table.

// insert table 252

== 2-1) Alien Referee Personas

When creating an alien referee persona encounter the referee must keep in mind that she is likely creating an entire alien species.
Aliens don't merely exist unto themselves as a singular entity but are components of a species as are the humanoid families.
Alien species are generated by the referee either to supply background and interest to a campaign or to provide the primary focus and/or conflict around which to design a campaign.
The reason the aliens are referred to as species and not families is because they can be unsophisticated animals of an unexplored world or highly developed conquering alien hordes.

=== *http://expgame.com/?page_id=2187[Go to Subchapter 11-1 Alien RP Generation] *

== 2-2) Anthropomorph Referee Personas

Anthro referee personas (RP) will be the most common type that the referee will introduce to the expedition.
Such referee personas can vary from altruistic veterinarians that are placing themselves at risk to heal the expedition to ruthless anti-knites that are using the expedition as a disposable tool in their quest for universal chaos.
Other RPs will be colourful campaign descriptors like meaningless civilians that clog sidewalks or mutant markets.
Such anthro referee personas should require no more personification than an accented voice or a marker on the table.
If the poor innocent civilian is unfortunate misfortune to happen upon the expedition during a combat situation then a little more preparation is required.

*Sidewalk Civilians*: These are the unprepared personas that simply fill the streets of a city, village, or spacecraft in an effort to describe a crowd.
Such personas will generally have no more than 9 HPS, no weapons, and no combat table.
Any civilian attributes that are required are rolled as needed and usually need not be recorded.
If the ref is suspicious of the expeditions intentions when entering a civilian area, she may generate several sets of attributes for those exceptional civilians that are capable of defending themselves.

*True Referee Personas*: In those instances where the expedition comes across a true referee persona, the ref must be fully prepared with attributes, family, mutations, class, level, personality, and equipment.
There is no telling what will be required of the persona once it is introduced to the expedition.
These are the referee personas where the ref must have a reasonably detailed origin, presence, and goal.

=== http://expgame.com/?page_id=2191[*Go To Subchapter 11-2 Anthro RP Generation*]

== 2-3) Robot Referee Personas

If the referee is at a loss for determining what kind of robot to introduce to the expedition, her best bet is to generate a robot persona and play it as an RP robot.
Chapter 5 is dedicated to the creation of robot personas and the majority of the RP robot will be developed there.
The referee must remember to return to this chapter in order to give the robot pertinent RP details like EXPS level and persona qualities.

=== http://expgame.com/?page_id=2193[*Go To Subchapter 11-3 Robot RP Generation*]

== 3) Referee Persona Class

The referee persona class should only be used for those referee personas that can pursue a class.
This would be anthros, alien tool users, androids, and the rare robot that has class skills.
The anthro referee persona's most important element will be her class.
The nature of each class is discussed in http://expgame.com/?page_id=250[Chapter 8: Classes].
The referee persona class table is included for those instances where the referee cannot decide what class she wishes her referee persona to have.

// insert table 316

*Multi-Class*: Multi-class personas simply roll as often as the dice indicate.
If the same persona class is rolled twice, then the experience levels, determined later, are added together.
There is no limit other than realistic probability to the number of classes that a referee persona can have.
The first roll on multi-class will indicate that the referee will roll twice and any further rolls on multi-class will indicate another roll.
Knites cannot be multi-classed.

*Class Attributes*:  To ensure that referee persona meets the attribute requirements of their class.
The referee can utilize the Table 11.7: Class Attribute Adjustments.

// insert table 317

== 4) Experience Level of RP

A referee personas EXPS level is applicable to anthros, aliens and robots.
If the referee personas class should happen to be a nothing, the experience level will represent the number of rolls she is entitled to in http://expgame.com/?page_id=353[Chapter 53: Treasure].

// insert table 318

== 5) Referee Persona Combat Table

The RP combat table is calculated the same as any other persona's combat table.
Aliens use their natural attack table if they have no class abilities.
Anthropomorphs and class skilled aliens use the combat table described in Chapter 27: Tactical Combat.
Robots have their own combat table regardless of whether they are class skilled or not.
The robotic combat table is described in Chapter 31: Robotic Combat.
The referee may wish to simplify her RP combat tables to increase the speed of combat.
It is assumed that the referee will be ethical and round the RP combat tables (CTs) down.

*Alien Combat Table*: For more information about the alien combat table refer to http://expgame.com/?page_id=252[Chapter 9: Combat Tables].
This combat table is for natural attacks of the alien RP.
If the alien is advancing in a class she will use the Anthro Class RP combat table.
There is no such thing as a Bonus Non-Proficient (BNP) for natural attacks.
Aliens do  not have a BNP.
Alien PSTR is included in their damage attack, and they do not have a Damage Adjustor (DA) either.
The initial combat table can be calculated here, and it can be important to add the level bonus to the Bonus Proficient (BP).
Unfortunately the level bonus must be calculated by hand if it applies to the alien.
So for example an alien RP with a PSTR of 20 would increase her BP for Type A natural attack  by 20 at level 2, by 13 at level 3, and by 10 at level 4.

// insert table 319

*Robot Combat Table*: For more information about the robot combat table refer to http://expgame.com/?page_id=252[Chapter 9: Combat Tables].
The initial combat table is be calculated here.
Robots have a bonus non proficient (BNP) of zero.
Robots have no Maximum Roll (MR).
Unfortunately the level bonus must be calculated by hand for the robot RP.
So for example  a robot RP with a PSTR of 20 would increase her BP for Type A attack by 10 at level 2, by 7 at level 3, and by 5 at level 4.
If the robot is advancing in a class she will use the Anthro Class RP combat table.

// insert table 320

*Anthro Class Combat Table*:  For more information about the combat table refer to http://expgame.com/?page_id=252[Chapter 9: Combat Tables].
The initial combat table is calculated here and the level adjustment should be added to the Bonus Proficient (BP).
For simplicity sake we use one combined level bonus for all three weapon types for the referee persona.
If detail must prevail the level bonus can be calculated by hand.
Calculate the Bonus Proficient on Table 11.11: Bonus Proficient for Referee Personae, then add the level bonus from Table 11.11.1: Total Level Bonus by Class.
This will create a quick Bonus Proficient that reflects the referee personas attributes, class and level.

// insert table 322

// insert table 321

// insert table 323

== 6) Referee Personal Equipment

Referee personas carry equipment: they should be supplied with food, survival equipment, and funds.
What the referee persona is carrying as survival equipment will vary depending on terrain.
Referee personas are also assumed to have collected artifacts throughout their travels.
RPs get one artifact for every experience level.
This includes multi-class levels.
Treasure does not count as a roll so RPs can accumulate considerable wealth in addition to their personal collection of artifacts.
Nothing RPs do not get a roll on the Toy Table but they do get additional treasure rolls.
This tends to make RP nothings tremendously wealthy.
If the referee desires impoverished nothings, she can save herself a whole lot of rolling on the treasure tables.
Nothing RPs also receive their complimentary one piece of miscellaneous equipment.

== 7) Referee Persona Qualities

A referee persona is more than a collection of attributes and some artifacts.
Referee personas are an essential part of the story being told in the campaign.
RPs are expected to have all the personality qualities as any other persona.
This challenges the limits of creativity of the referee because she must supply different personalities, appearance  and qualities for the quadrillions of referee personas that will participate in the campaign.
If the referee does not already have a particular appearance, personality, or set of beliefs in mind for her RP, she may find the tables provided useful.
The referee persona qualities are on Table 11.14: RP Qualities Checklist.

// insert table 324

=== 7-1) Appearance

An RPs appearance is divided into two categories: hygiene and dress.
Hygiene represents the personas normal level of personal care.
The hygienic habits of the RP are determined on the RP Hygiene table.
Hygiene is not unwavering like an attribute but is dependent on the scenario at hand.
For example, a habitually immaculate RP that just dived into mud would look like someone who dived into mud;
a habitually filthy spie would not arrive un-groomed at an aristocratic function she was trying to infiltrate.
However, the immaculate RP would clean the mud off herself sooner than the filthy spie and the filthy spie would be the first to get soiled at the aristocratic bash.
The dress of the referee persona does not reflect ANYTHING about the referee persona.

The dress of an RP is even more variable than hygiene.
An RP may have several favorite styles and may even combine them in some random arrangement.
The roll on the table dress indicates which type of dress is worn: shoes, shirts, blouses, pants, hair-dos, etc.
Appearance is mostly directed at anthropomorph RPs, but it can also include aliens or deeply eccentric robots.
It is easy to imagine a filthy canine lumberjack but an immaculate six legged alien dressed in traditional tribal gowns is harder to visualize.
Robots can certainly have hygienic qualities, appearing dirty or well washed, but robot dress may be just too absurd.
For instance, would a 60s style robot have fins and chrome bumpers?

// insert table 325

// insert table 326

=== 7-2) Personality

The referee is expected to play up these personality traits whenever possible.
Extroverted personality traits are NOT irrational: a diplomatic RP will not try to play consul to a crazed combat robot but she may intercede between inter-expedition differences.
Aliens and robots also get a roll on the Extroverted Personality table.
Properly functioning robots would not have  a shred of personality whatsoever, but the free willed robots of EXP are malfunctioning and extroverted personalities or even insanities are possible.

// insert table 327

==== Introverted

The Introverted Personality Sub-table indicates subtle personality traits.
These traits are not too strong and should only be employed by the referee when decisions must be made by the RP.
Such traits are played discreetly by the referee, and may only occasionally be used or noticed.

// insert table 328

==== Insane

The Insane Personalities Table lists irrational actions that are basically pathological.
Insane personality traits can appear in completely unexpected situations, endangering the referee persona and the expedition.
The easiest and most fun referee personas to play are insane ones, but they should be kept relatively rare since EXP is an insane enough game as it is.
Referees are not expected to be psychiatrists and can role-play the mental illness however they interpret them.
If the roll on this table has been directed from the Extroverted Personality Trait Table the insanity will be quite overt.
If the referee is rolling an insane personality off of the Introverted Personality Trait then the insanity will be less obvious.

// insert table 329

=== 7-3) Beliefs

The referee should be prepared to have their preferred personas possess some personal beliefs that may affect their attitude, and how they act while role-playing.
Beliefs are divided into three categories: political, religious, and philosophical.
The player will have from 0-3 (d4-1) separate beliefs, where 0 is none and 3 is three rolls on Table 11.19.
The beliefs are more transient than the RP's personality and they will can conflict directly with the referee persona's personality.
The belief tables are somewhat self-explanatory and are mostly used as the tack that a particular personal will take when arguing ethics with expedition personas.
In the case of aliens these beliefs may be the basis for their entire culture.
For example, an alien that is militaristic and believes religiously in anonymous writings may be a member of a war-like invading family.

// insert table 330

// insert table 331

// insert table 332

// insert table 333

== 8) Combat Ratios

The combat ratio aids the referee in objectively rating how tough a referee persona has been created.
The combat ratio indicates the number of expedition personas that should be needed in combat for a fair fight with that one referee persona.
The higher the combat ratio, the stronger the referee persona.
In other words, if 1 persona vs.
20 referee personas constitutes a fair fight, this is a pretty feeble referee persona.
If the combat ratio indicates 20 personas vs.
1 RP is a fair fight, then it is a tough referee persona.
The combat ratio is just an indicator of the RPs combat strength.
The number of RPs appearing depends on the type of referee persona, its social behaviour, and the setting of the scenario.
If the combat ratio is 1/20, it does not necessarily mean that 20 RPs will automatically show up for every persona.

*Calculating CR*: Add up all the pluses first.
Then multiply all the times.
So a Combat Ratio with Plus 1 and Plus 4 and Plus 3 and Times 1.25 and Times 2.0.
It would be calculated as so: 1 plus 4 plus 3 = 8;
times 3 times 1.25 gives a CR of 30!

// insert table 334

// insert table 335

// insert table 336

// insert table 337

// insert table 338

// insert table 339

// insert table 340

*(8-1) Alien Combat Ratio*: The calculation of the combat ratio is reasonably self-explanatory.
Simply follow the Combat Ratio tables  and adjust the number of personas that are indicated for each of the aliens combat parameters.
Assume that the ratio begins at 1 (1 persona to 1 alien).
The combat ratio can get an alien into a lot of trouble.
Aliens with high combat ratios (requiring many personas for a fair fight) can get a reputation for being violent and combative.
The aggressiveness of the alien is determined by its psychology not its combat ratio.
The corollary is true also and aliens with low combat ratios may be very dangerous if they happen to use weapons or travel in massive numbers.
The combat ratio merely represents the aliens natural ability to hold its own, against average personas.

// insert table 341

*(8-2) Anthropomorph Combat Ratio*: The anthropomorph RP combat ratio is very difficult to calculate in that their use of artifacts can greatly alter their deadliness regardless of what their class is or their attributes are.
Even the most deadly referee persona can be handled easily by the expedition if the referee makes a mistake.
Also the most benign referee persona can become extremely dangerous if she manages to get a hold of a deadly weapon.

When preparing an anthropomorphs combat ratio, the referee should try to take into account all the equipment that the RP has access to.
This means that considerable time may have to be spent in the toy section before the combat ratio can be calculated.
Experienced referees will find that the combat ratio is not needed for estimating equivalent combat conditions but more useful in calculating the RPs experience point value which includes EXPS for encounters other than combative ones.

// insert table 342

*(8-3) Robotic Combat Ratio*: Robots are considerably easier to prepare a combat ratio for than other persona types because they are so structured.
Robots are not nearly as flexible as the biological RPs but they can be very deadly.
The most important point about robots is that they are difficult to destroy but easy to damage.
The following tables can be used as a general guideline as to how challenging a robot is in combat.

// insert table 343

== 9) Referee Persona Name

Often the most important part of a referee persona is its name.
The description of a humanoid may be glossed over and that of an aliens forgotten completely but the name will always be remembered.
The players will recall an RPs name before they will remember her personality, dress, or special abilities.
There is no question that a referee personas name is much more important to the campaign than that of an expedition persona.
Often an RPs name will have some significance, like a veterinarian named Ivy Blodgett or a melancholic nothing named Sue Siedal.

Robots are more difficult to name because there is some unwritten rule that they must have letters and numbers in their names, like: QT, oicur12, unit 42, or SNOO-KM series.
Remember the more insane the robot, the more free willed it is and the more likely that it will have named itself.
Additional names that the referee may be required to produce for an RP robot are manufacturers name, model line, and unit name.

Alien families are fun to name.
The referee will often be naming an entire family as well as the specific species member that she has created.
A helpful hint in naming alien families is to avoid personification.
No self-respecting space-faring family would call itself the Obese Ones,
or the Furry Ones.
If such alien properties are important to an alien family (which they might well be), translations can mean anything the referee likes and the Vojing Dur
may translate into Obese Ones
but in that aliens tongue (if they have tongues) human
might translate into scrawny geeks.
Always keep in mind that these creatures are alien and alien sounding words that reflect the alien are the most useful and fun.


