= Alien RP

When creating an alien referee persona encounter the referee must keep in mind that she is likely creating an entire alien species.
Aliens don't merely exist unto themselves as a singular entity but are components of a species as are the anthropomorph types.
Alien species are generated by the referee either to supply background and interest to a campaign or to provide the primary focus and/or conflict around which to design a campaign.
Aliens are referred to as species because they can be unsophisticated animals of an unexplored world or highly developed conquering alien hordes.

Most aliens will be altered to fit into the milieu of the campaign.
The referee should massage the alien RP to fit her milieu.
This section is for helping creativity, not replacing it.

.*Alien RP Evolution Checklist*
* *RP ROLL PLAYING (Data)*
. Relevance
. Persona Record Sheet
. Attributes
. Size
. Hit Points
. Attack Frequency
. Attack Damage
. Armour Rating
. Wate Allowance
. Description
. Movement Rate
. Mutations
. Age
. Society
. EXPS Level
. Vocation
. Equipment
. Combat Table
. Combat Ratio
* *RP ROLE PLAYING (Fun)*
. Biology
. Story
. Appearance
. Beliefs
. Modifications
. Name
. Have Fun!

== Role Playing Aliens
Ain't that fun.

== Generating the Alien RP
In that chapter, the referee should record all the pertinent information about the alien created.
For RP aliens, details like whether they are tool users or educated are very important.
Referee persona qualities (8) only apply to an alien RP if it expresses a civilized or tool-using nature.
The communication method used between the alien and the expedition is determined by the referee.

Refs should create their own aliens.
Aliens custom-designed by the referee are certain to fit into the campaign or terrain that they were designated for.
Creating original aliens eliminates the problem of finding that perfect creature necessary for the moment.
The alien generation system creates basic creatures that do not have a place in any existing food chain, pre-designed environment, or social system.
All these important points that make an alien species more realistic are left to the ref to design around the generated alien.
Many referees will discover that rolling up aliens will almost certainly jog their imaginations.

When creating an alien referee persona encounter the referee must keep in mind that she is likely creating an entire alien species.
Aliens don't merely exist unto themselves as a singular entity but are components of a species as are the humanoid families.
Alien species are generated by the referee either to supply background and interest to a campaign or to provide the primary focus and/or conflict around which to design a campaign.
The reason the aliens are referred to as species and not families is because they can be unsophisticated animals of an unexplored world or highly developed conquering alien hordes.

There is always the possibility that an alien is the singular creation of a biological research laboratory gone civilized or some other such cloning cliché.
Whether the alien is singular in existence or a member of a species, the referee should have it properly prepared.

== Alien RP Relevance
Not all RPs are created equal.
Some are less important than others.
The referee will know the RP's level of the beginning of the RP creation.
A RP's relevance increases the entangled they are with the expedition.

Alien referee personas are a single representative of an entire species. 
Cannon and canon fodder may need more information than RPs from other families.

include::ROOT:partial$CH11_Table_RP_Relevance.adoc[]

=== Cannon Fodder
Cannon fodder are like movie extras that fill in the background.
Alien cannon fodder are the flora and fauna in a forest.
Alien cannon fodder may also be sidewalk civilians in an advanced society.
Alien sidewalk civilians fill the streets of a city, village, or spacecraft.

.*Cannon Fodder* 
. offer no opposition
. have no useful information
. have no nutritional value, monetary value or useful parts.

Sidewalk civilians, flora, fauna can be created on the fly. 
The alien cannon fodder has one universal value.
This value must reflect the alien species as a whole.
The same number is used for HPS or attributes to facilitate play.
For example, a tiny alien may have HPS of 4 while a gigantic alien may have HPS of 20.

Cannon fodder does not mean expendable without consequence.
Hunting flora and fauna may be against the law.
Alien societies may have laws protecting their defenceless comrades.

=== Canon Fodder
Canon fodder have bit parts in the story, but do not make the story. 
Alien canon fodder are usually dangerous animals or combatants.

.*Canon Fodder* 
. could act in opposition to the expedition's goals
. could injure or kill a player persona
. could accidentally alter the story of a campaign
. could have information or treasure

The goal of the canon fodder is usually predetermined by the referee or milieu.
The referee creates as much information as needed.
The alien could an indigenous predator that eats anthros.
The predator's goal is predetermined and lack nuance. 
Their info may be kept on a card, and a persona record sheet is not essential.

Canon fodder can be extremely dangerous to the expedition.
They are there to get in the way of the player's goals. 

=== Canon Referee Persona
Canon referee personas are like supporting actors that make the story possible.
Canon referee personas are integral participants in the campaign story.
They can be powerful recurring enemies, or comrades in arms.
Canon RPs are fully developed alien species of which this RP is a member.
Only the player personas are more important to the story.
Canon referee personas utilize every step of persona creation.

Alien canon referee personas are entire species and can become the focus of an entire campaign.

== Alien RP Record Sheet
The referee persona record sheet is just another persona record sheet.
There are few bonus elements that referee must keep track of.
Most player personas do not have elements like personality, politics or religion.
The referee persona record sheet can also be used to keep track of expedition interactions.

NOTE: *If the referee persona is worth playing it is worth writing down.*

== Alien RP Attributes
Attribute are rolled here.
Modifications are done later

include::ROOT:partial$CH06_Table_Alien_Attributes.adoc[]

== Alien RP Size
The bigger the bigger.

include::ROOT:partial$CH06_Table_Alien_Size.adoc[]

=== Minute Alien Size
Any alien that is Tiny has a chance to be Minute instead.
There is a 1 in 6 chance that a tiny alien being minute.
Minute aliens are very small and cannot be reasonably run by a player but can be introduced by a referee.
Minute aliens have a WATE of  1 to 1000 grams (1d1000).
No Minute alien will have a WATE greater than a kilogram.
Minute aliens have half the HPS that were rolled for the corresponding tiny alien and PSTR is reduced to one quarter that of the tiny alien's.
All other attributes and measurements remain the same.

=== Humongous Alien Size
Any alien that is Gigantic has a chance to be Humongous instead.
There is a 1 in 6 chance that a gigantic alien is humongous.
Humongous aliens have a WATE of 6 to 300 tons (1d50 times 6).
Such aliens are impossible for a player to run but can be introduced by the referee.
None of the humongous alien's attributes are different from those of the corresponding gigantic alien.

== Alien RP Hit Points
More bigger more hit points.

include::ROOT:partial$CH06_Table_Alien_Hit_Points_HPS.adoc[]

// check why 2 tables?

== Alien RP Number of Attacks
The more attacks the more dangerous.

include::ROOT:partial$CH06_Table_Number_of_Alien_Attacks.adoc[]

== Alien RP Damage per Attack
More Bigger More Damage

include::ROOT:partial$CH06_Table_Alien_Damage_Per_Attack.adoc[]

include::ROOT:partial$CH06_Table_Alien_Attack_Type.adoc[]

== Alien RP Armour Rating

include::CH06_Aliens_7_AR.adoc[tag=Alien_AR]

== Alien RP Wate Allowance

include::ROOT:partial$CH03_Table_Physical_Strength_and_Wate_Allowance_(kg).adoc[]

== Alien RP Description
Record the movement letters (l,a,w,s)

=== Roll  Parts
Four rolls for four parts.
Head, Torso, Arms, and Legs.

include::ROOT:partial$CH06_Table_Alien_Body_Parts.adoc[]

=== Coat and Colour
Coat is uniform over whole alien
Roll colour and affects 

include::ROOT:partial$add_colour_to_your_world.adoc[]

=== Adornments
These are optional accents to the alien's appearance.
Adornments are entirely descriptive.
Adornments do not detract from or add any abilities to the alien. 

==== Head 
include::ROOT:partial$CH06_Table_Adornment_Head.adoc[]

==== Torso
include::ROOT:partial$CH06_Table_Adornment_Torso.adoc[]

==== Arms
include::ROOT:partial$CH06_Table_Alien_Adornments_Arms.adoc[]


== Alien RP Movement Rate
Denizens may hop, slither, scuttle, slime or gallop along with whatever form of locomotion is listed as legs in their Description.

=== Base Movement
include::CH06_Aliens_9_Move.adoc[tag=Alien_Move]

The type of creature part that is used to describe the alien's locomotion will move at the designated movement rate regardless of what the description is.
For instance, an alien that looks like a snail could move as fast as an alien that looks like a leopard.

=== Quartering Movement

include::ROOT:partial$CH06_Table_Calculating_Alien_Movement.adoc[]

== Alien RP Mutations
Aliens have a chance of getting mutations;
However, they are not generally considered mutations but natural abilities that function the same as mutations.
An alien's mutations apply to the entire family and are more like naturally evolved defensive or offensive abilities.
Therefore, alien mutations are not considered mutations in the usual sense -- as if they were abnormalities or variations from the norm.
Occasionally mutations may force changes in the creature's physical description as determined in the Description section.
If a player running an alien wishes to mutate, she cannot adjust her chance of mutation like humanoid personas can.

// these are not mutations but abilities
// no defects
== Mental Abilities
The chance of an alien having a mental mutation is equal to the alien's MSTR attribute.
An alien with a 15 MSTR would have a 15% chance of having a mental mutation per mutation check.
The player stops checking for mental mutations as soon as a roll is failed.
So if the player were to roll 11 and 16, her alien would have one mental mutation.
These mutations are described in Chapter 58: Mental Mutations.

== Physical Abilities
The chance of a creature having evolved a physical mutation is equal to the creature's CON.
For example, a CON of 10 has a 10% chance of having a mutation.
Once the alien has a mutation, there is an equal chance of having another.
The alien can keep getting additional mutation-like abilities if it keeps making its percent chance.
If the player with the alien that has a 10 CON were to roll 3, 9, and 41, her alien would have two physical mutations.

Aliens have a chance of getting mutations;
however, they are not generally considered mutations but natural abilities that function the same as mutations.
An alien's mutations apply to the entire species and are more like naturally evolved defensive or offensive abilities.
Therefore, alien mutations are not considered mutations in the usual sense -- as if they were abnormalities or variations from the norm.
Occasionally mutations may force changes in the creature's physical description as determined in the Description section.
If a player running an alien wishes to mutate, she cannot adjust her chance of mutation like humanoid personas can.

== Alien RP Age
All personas except for robots have a projected life-span.
The idea of an alien only living for a certain amount of time is a reflection of its biological nature.
The life spans of aliens can be very alien indeed when compared to those of humanoid personas.
First generate the total lifespan, and then the possible age in years of the alien can be calculated.

include::ROOT:partial$CH06_Table_Alien_Lifespan.adoc[]

include::ROOT:partial$CH11_Table_Alien_RP_Life_Stage.adoc[]

include::ROOT:partial$CH06_Table_Alien_Life_Stages.adoc[]

=== Extremely Short Life Spans 
If the alien RP's life span in years is less than 10 years there is a 1 in 6 chance that the aliens lifespan will be measured in months or days or hours.
Really short life spans should have an impact on how the alien's function in their biology and how they live their existence.

// insert table 271

=== Extremely Long Life Spans
If the alien RP's life span is more than 1000 years there is a 1 in 6 chance that the alien will have a maximum life span of 1-1000 million years (1d1000 times 1000000).
Yes of course this changes everything about how the alien behaves, it's culture, and it's history.


== Alien RP Society
Alien society is something for the referee to carefully consider and prepare for her campaign.
Alien societies can even be the basis for an entire campaign.
The differences in values, architecture, and social organization alone amongst alien cultures would be beyond the duration of a life time of study.

.Societal Compositions
* Language 36%
* Culture 11%
* Education 4%
* Vocation 1%

.Tool Usage Frequencies
* None 52%
* Simple 38%
* Tech 8%
* Comp 1% 
* Creator (AI) 0.1%

Most of the persona aliens will be rogues or outcasts that have rejected their alien culture thus allowing them to form their own cultural niche.
The referee cannot possibly prepare a detailed alien society each time a player generates an alien persona.
For the most part, alien personas will not be members of galactic societies or developed countries.
If some idea of the alien's society is necessary but total preparation is not, the referee should turn to Chapter 11: Referee Personas and determine the society's religious, political, and philosophical beliefs.

include::ROOT:partial$CH11_Table_RP_Alien_Society.adoc[]


== Alien RP EXPS Level
Good for flora, fauna, and vocations

include::ROOT:partial$CH11_Table_Referee_Persona_Level.adoc[]

== Alien RP Vocation
Must have vocation on society level.
No attributes apply.

include::ROOT:partial$CH11_Table_Referee_Persona_Class.adoc[]

== Alien RP Equipment
Referee personas carry equipment: they should be supplied with food, survival equipment, and funds.
What the referee persona is carrying as survival equipment will vary depending on terrain.
Referee personas are also assumed to have collected artifacts throughout their travels.
RPs get one artifact for every experience level.


=== No Tool Use
No tools, no rocks, does not even recognize tech. 
Does not even fetch.
Does not hold water in arms.

=== Simple Tool User
May use natural unmodified items.
Rocks, found sticks, hold water.
No mundane and no artifacts.

=== Tech Tool User
Simple machines like levers.
Understand artifacts are better.

xref:ii-roll_playing_rules:CH24_Mundane_Equipment.adoc[Mundane Equipment]
Referee personas carry equipment: they should be supplied with food, survival equipment, and funds.
What the referee persona is carrying as survival equipment will vary depending on terrain.

=== Comp Tool User
TOY roll no space ships
No vehicles

==== Some Artifacts
Personal only no AI no Robots

// whoa robots as TOYS?

=== Creator 
Can roll anything on the TOY Table

==== Any Artifact
Referee personas are also assumed to have collected artifacts throughout their travels.
RPs get one artifact for every experience level.
This includes multi-class levels.
Treasure does not count as a roll so RPs can accumulate considerable wealth in addition to their personal collection of artifacts.
Nothing RPs do not get a roll on the Toy Table but they do get additional treasure rolls.
This tends to make RP nothings tremendously wealthy.
If the referee desires impoverished nothings, she can save herself a whole lot of rolling on the treasure tables.
Nothing RPs also receive their complimentary one piece of miscellaneous equipment.
// they know how to use their artifacts
include::ROOT:partial$CH41_Table_TOY_Type.adoc[]

== Alien RP Combat Table
This combat table is for natural attacks of the alien RP.
If the alien is advancing in a class she will use the Anthro Class RP combat table.
There is no such thing as a Bonus 

=== Natural Attacks

include::ROOT:partial$CH11_Table_Alien_Referee_Persona_Combat_Table_(CT).adoc[]

Non-Proficient (BNP) for natural attacks.
Aliens do  not have a BNP.
Alien PSTR is included in their damage attack, and they do not have a Damage Adjustor (DA) either.
The initial combat table can be calculated here, and it can be important to add the level bonus to the Bonus Proficient (BP).

// Pure alien level bonuses
Unfortunately the level bonus must be calculated by hand if it applies to the alien.
So for example an alien RP with a PSTR of 20 would increase her BP for Type A natural attack  by 20 at level 2, by 13 at level 3, and by 10 at level 4.


=== Artifact Attacks
Use the Anthro.
If no vocation use nothing.

include::ROOT:partial$CH11_Table_RP_Bonus_Proficient_(BP).adoc[]

include::ROOT:partial$CH11_Table_Calculated_Level_Bonus__for_RPs_with_Classes.adoc[]

include::ROOT:partial$CH11_Table_Bonus_Non_Proficient_(BNP).adoc[]

== Alien RP Combat Ratio
// boilerplate is from anthro RP
include::CH11_Referee_Personas_Anthro.adoc[tag=Combat_Ratio]

=== Alien Specific

include::ROOT:partial$CH11_Table_RP_CR_Alien.adoc[]

// general CR adjustments list of tables.
// heading is === for each table
include::ROOT:partial$CH11_RP_CR_General.adoc[]


== Alien RP Biology
All of the alien information up to this date is considered biology but the biology covered here represents superfluous information that will only subtly affect the nature of the alien;
whereas the previous biology represented factors that affect the attributes of the alien personas like movement, combat abilities, size, etc.

Biology gives a very brief description of where the alien fits into its ecological system.
The biome describes the terrain that the alien is accustomed to living in.
The last five tables provide some extra insight into what makes an alien tick.
They may seem trivial at first but can be very important under certain circumstances.

.*Alien Biology Checklist*
. <<_biome,Biome>>
.. <<_biome_modification,Biome Modification>>
. <<_energy_source,Energy Source>>
.. <<_procurement,Procurement>>
. <<_reproduction,Reproduction>>
. <<_dwelling,Dwelling>>
. <<_aroma,Aroma>>

=== Biome 

include::ROOT:partial$CH06_Table_Alien_Biome.adoc[]

==== Biome Modification

include::ROOT:partial$CH06_Table_Alien_Biome_Characteristic.adoc[]

=== Energy Source

include::ROOT:partial$CH06_Table_Alien_Energy_Source.adoc[]

==== Energy Procurement

include::ROOT:partial$CH06_Table_Alien_Energy_Procurement_Strategy.adoc[]

=== Reproduction

include::ROOT:partial$CH06_Table_Alien_Reproductive_Method.adoc[]

=== Dwelling

include::ROOT:partial$CH06_Table_Alien_Habitation_Type.adoc[]

=== Grouping

include::ROOT:partial$CH06_Table_Alien_Group_Size.adoc[]

== Alien RP Story
Everything has a story.
As previously stated, referee personas can have a wide degree of involvement in a campaign or with an expedition.
All referee personas must have an origin, presence, and goal.
The origin of an RP should explain where it came from and why it things the way it does.
The presence of the RP will dictate how and why it interacts with the expedition.
The goal of an RP is what it wants from the campaign, dictating what it will do with the expedition and when it will part company.

For 95% of the RPs the expedition will encounter, the Trinity of the RP (origin, presence, and goal) will be pre-determined.
Referee personas such as innocent civilians and animals will have simplistic origins such as migrating through the area or on their way to work.
Their presence might be riding on the subway or rummaging through the bushes.
Their goal may be to find some berries to eat or to get to work on time.
If the expedition frequently intervenes in the lives of such unimportant referee personas, the referee need have no more prepared than usual.

If the referee persona is a more important one the referee must create  a more detailed origin, presence, and goal.
Let's consider a young man from the farming district of his impoverished planet (origin) is willing to hire on for the expedition as a porter (presence) if they will take him off planet (goal).
Another referee persona could be a very hungry alien that just jumped out of a tree (origin) and is ferociously attacking the expedition (presence) because the alien's hungry and the expedition members look like something good to eat (goal).

=== Origin
Vishna Shraloor is a referee persona with death field generation (a mental mutation).
She matured not knowing that this lethal power was within her.
She grew up through a series of profound personal tragedies: the death of her parents, the death of teachers, the death of mourning relatives, the death of her playmates, the death of social workers, and the death of foster parents.
Many of these deaths may have been caused by her misunderstood mental ability.
That is her sad origin.

include::ROOT:partial$CH11_Table_Referee_Persona_Origin.adoc[]

=== Presence
Vishna's presence is one of a lonely unhappy persona who constantly associates with people she does not like because the people around her tend to die frequently.
Her profession is that of an orbital satellite repair person, a solitary job for certain.
She has chosen to hang around with the expedition because she does not particularly like them much.
This is her presence.

include::ROOT:partial$CH11_Table_Referee_Persona_Presence.adoc[]

=== Goal
Ms. Shraloor's goals are varied.
She would like to destroy the society that has rejected her so totally and she sees the expeditions mentality as something that she can exploit to this end.
If an expedition member should happen to befriend her, show her the nature of her mutation, and nurse her through the subsequent guilt, she may follow another path and desire to help the society that continued to reach out to her despite their extreme risk.
These are her potential goals.

include::ROOT:partial$CH11_Table_Referee_Persona_Goal.adoc[]

This chapter provides no guidelines on preparing an origin or goal for the referees personas but it does help with the presence of the referee personas.
In fact, this chapter could be considered a guide on how to prepare a referee personas presence.
If the ref knows that she needs RPs but has no origins or goals, then it might help to create the persona presence first.
This is an excellent procedure for sparking the imagination or solidifying a watery idea.

=== Anthro RP Personality
The referee is expected to play up these personality traits whenever possible.
Extroverted personality traits are NOT irrational: a diplomatic RP will not try to play consul to a crazed combat robot but she may intercede between inter-expedition differences.
Aliens and robots also get a roll on the Extroverted Personality table.
Properly functioning robots would not have  a shred of personality whatsoever, but the free willed robots of EXP are malfunctioning and extroverted personalities or even insanities are possible.

include::ROOT:partial$CH11_Table_Referee_Persona_Extroverted_Personality_Trait.adoc[]

==== Introverted
The Introverted Personality Sub-table indicates subtle personality traits.
These traits are not too strong and should only be employed by the referee when decisions must be made by the RP.
Such traits are played discreetly by the referee, and may only occasionally be used or noticed.

include::ROOT:partial$CH11_Table_Introverted_Personality_Trait.adoc[]

==== Insane
The Insane Personalities Table lists irrational actions that are basically pathological.
Insane personality traits can appear in completely unexpected situations, endangering the referee persona and the expedition.
The easiest and most fun referee personas to play are insane ones, but they should be kept relatively rare since EXP is an insane enough game as it is.
Referees are not expected to be psychiatrists and can role-play the mental illness however they interpret them.
If the roll on this table has been directed from the Extroverted Personality Trait Table the insanity will be quite overt.
If the referee is rolling an insane personality off of the Introverted Personality Trait then the insanity will be less obvious.

include::ROOT:partial$CH11_Table_Insane_Referee_Persona_Personality_Traits.adoc[]


== Alien RP Appearance
=== Gender
Not physiology or sexuality. 
Gender here is appearance only.

include::ROOT:partial$CH11_Table_RP_Gender.adoc[]

=== Clothing
The dress of an RP is even more variable than hygiene.
An RP may have several favorite styles and may even combine them in some random arrangement.
The roll on the table dress indicates which type of dress is worn: shoes, shirts, blouses, pants, hair-dos, etc.
Appearance is mostly directed at anthropomorph RPs, but it can also include aliens or deeply eccentric robots.
It is easy to imagine a filthy canine lumberjack but an immaculate six legged alien dressed in traditional tribal gowns is harder to visualize.
Robots can certainly have hygienic qualities, appearing dirty or well washed, but robot dress may be just too absurd.
For instance, would a 60s style robot have fins and chrome bumpers?

include::ROOT:partial$CH11_Table_Referee_Persona_Dress.adoc[]

=== Hygiene
Hygiene is not unwavering like an attribute but is dependent on the scenario at hand.
For example, a habitually immaculate RP that just dived into mud would look like someone who dived into mud;
a habitually filthy spie would not arrive un-groomed at an aristocratic function she was trying to infiltrate.
However, the immaculate RP would clean the mud off herself sooner than the filthy spie and the filthy spie would be the first to get soiled at the aristocratic bash.
The dress of the referee persona does not reflect ANYTHING about the referee persona.

include::ROOT:partial$CH11_Table_Referee_Persona_Hygiene.adoc[]

=== Aroma

include::ROOT:partial$CH06_Table_Alien_Aroma.adoc[]

== Alien RP Beliefs
In the case of aliens these beliefs may be the basis for their entire culture.
For example, an alien that is militaristic and believes religiously in anonymous writings may be a member of a war-like invading family.

include::ROOT:partial$CH11_Table_Referee_Persona_Religious_Belief.adoc[]

include::ROOT:partial$CH11_Table_Referee_Persona_Political_Belief.adoc[]

include::ROOT:partial$CH11_Table_Referee_Persona_Philosophical_Belief.adoc[]


== Alien RP Modifications
Not every referee wants their aliens to have the attribute ranges listed in the alien persona chapter.
Often a referee will want a small alien, a dumb alien, a slow alien, or even a dumb, slow, small alien (prey).
For special attributes for special aliens refer to Table 11.6: Descriptive Attribute Adjustments.
The corresponding alien adjectives such as tough, strong, or smart, are not included and, when desired regular alien attribute generation should suffice.

include::ROOT:partial$CH11_Table_Anthro_RP_Modifiers.adoc[]

== Alien RP Name
Often the most important part of a referee persona is its name.
The description of a humanoid may be glossed over and that of an aliens forgotten completely but the name will always be remembered.
The players will recall an RPs name before they will remember her personality, dress, or special abilities.
There is no question that a referee personas name is much more important to the campaign than that of an expedition persona.
Often an RPs name will have some significance, like a veterinarian named Ivy Blodgett or a melancholic nothing named Sue Siedal.

Robots are more difficult to name because there is some unwritten rule that they must have letters and numbers in their names, like: QT, oicur12, unit 42, or SNOO-KM series.
Remember the more insane the robot, the more free willed it is and the more likely that it will have named itself.
Additional names that the referee may be required to produce for an RP robot are manufacturers name, model line, and unit name.

Alien families are fun to name.
The referee will often be naming an entire family as well as the specific species member that she has created.
A helpful hint in naming alien families is to avoid personification.
No self-respecting space-faring family would call itself the Obese Ones,
or the Furry Ones.
If such alien properties are important to an alien family (which they might well be), translations can mean anything the referee likes and the Vojing Dur
may translate into Obese Ones
but in that aliens tongue (if they have tongues) human
might translate into scrawny geeks.
Always keep in mind that these creatures are alien and alien sounding words that reflect the alien are the most useful and fun.

