= Anthro RP

Anthros are upright, bipedal, humanoids.
In the fake taxonomy anthros are of the family Hominidae, and the genus homo.
Referees are most familiar with playing this type of referee persona.
They have hands, heads and faces.
Every role playing game in the history of role playing games is based on anthros. 

Most anthros will be altered to fit into the milieu of the campaign.
The referee should massage the anthro RP to fit her milieu.
This section is for helping creativity, not replacing it.

.*Anthro RP Delivery Checklist*
* *RP ROLL PLAYING (Data)*
. <<_anthro_rp_relevance,Relevance>>
. <<_anthro_rp_record_sheet,Persona Record Sheet>>
. <<_anthro_rp_type,Anthro Type>>
. <<_anthro_rp_size,Size>>
. <<_anthro_rp_age,Age>>
. Attributes
. Movement Rate
. Armour Rating
. Wate Allowance
. Mutation
. EXPS Level
. Vocation
. Equipment
.. Mundane
.. Artifact
. Combat Table
. Combat Ratio
* *RP ROLE PLAYING (Fun)*
. Story
.. Origin
.. Presence
.. Goal
.. Personality
. Appearance
.. Clothing
.. Hygiene
.. Gender
. Beliefs
.. Religious
.. Political
.. Philosophical
. <<_modifications,Modifications>>
.. attributes
.. size
.. age
. Name
. Have Fun!

== Anthro RP Relevance
Not all RPs are created equal.
Some are less important than others.
The referee will know the RP's level of the beginning of the RP creation.
A RP's relevance increases the entangled they are with the expedition.

include::ROOT:partial$CH11_Table_RP_Relevance.adoc[]

=== Cannon Fodder
Cannon fodder are like movie extras that fill in the background.
Anthro cannon fodder are called sidewalk civilians in EXP.
Sidewalk civilians fill the streets of a city, village, or spacecraft.

[quote]
____
Cannon Fodder were volume discounted anthros used to attack cannons.
____

.*Cannon Fodder* 
. offer no opposition
. have no useful information
. have no nutritional value, monetary value or useful parts.

Sidewalk civilians can be created on the fly. 
Any numerical value needed is 6.
Anthro cannon fodder have 6 HPS, 6 DEX, 6 MSTR.
The anthro type can be assigned as mutt, or non-descript.
None of these values are recorded and no persona record sheet is needed.
You can stop here if you randomly rolled cannon fodder. 

Cannon fodder does not mean expendable without consequence.
Killing off cannon fodder is against norms and laws in most settings.
Police forces and superheroes spend most of their time protecting cannon fodder.

=== Canon Fodder
Canon fodder have bit parts in the story, but do not make the story. 
Anthro canon fodder can be minions, soldiers, or security staff.

.*Canon Fodder* 
. could act in opposition to the expedition's goals
. could injure or kill a player persona
. could accidentally alter the story of a campaign
. could have information or treasure

The goal of the canon fodder is usually predetermined by the referee or milieu.
The referee creates as much information as needed.
For example, mercenaries defending a lab may only have a pistol and a BP and BNP.
Their uniforms may be uniforms and no further description is needed.
Other attributes are created as needed.
Their info may be kept on a card, and a persona record sheet is not essential.

Canon fodder can be extremely dangerous to the expedition.
They are there to get in the way of the player's goals. 
If this means combat the canon fodder are ready to do so.

=== Canon Referee Persona
Canon referee personas are like supporting actors that make the story possible.
Canon referee personas are integral participants in the campaign story.
They can be powerful recurring enemies, or comrades in arms.
Canon RPs are fully developed referee personas with attributes, vocations and goals.
Only the player personas are more important to the story.
Canon referee personas utilize every step of persona creation.

== Anthro RP Record Sheet
The referee persona record sheet is just another persona record sheet.
There are few bonus elements that referee must keep track of.
Most player personas do not have elements like personality, politics or religion.
The referee persona record sheet can also be used to keep track of expedition interactions.

NOTE: *If the referee persona is worth playing it is worth writing down.*

:art: aquarium_not_aquarian.png
:width: 250px
:snark: An aquarium not an aquarian
:artist: Imagestoks 
:date: 2017
:license: Copyright Imagestoks 2015

include::ROOT:partial$articulate.adoc[]

== Anthro RP Type
The anthro RP type should reflect the referee's milieu.
If inspiration is needed refer to the Anthro Type Table. 

include::ROOT:partial$CH11_Table_Anthro_RP_Anthro_Type.adoc[]

=== Anthro Sub Types
This very limited table offers so sub type differentiation.
Anthro and sub types are appearance only and not based on terrestrial science.
Non descript anthro types are referred to as mutts. 
A canine mutt is clearly a canine, but no more distinct than that.
Anthro sub types are phenotypical not scientific

include::ROOT:partial$CH11_Table_Anthro_RP_Anthro_Type_Subs.adoc[]

.source links for various anthro types
* https://en.wikipedia.org/wiki/List_of_fish_common_names
* https://en.wikipedia.org/wiki/List_of_dog_breeds
* https://en.wikipedia.org/wiki/List_of_horse_breeds
* https://en.wikipedia.org/wiki/Ungulate
* https://en.wikipedia.org/wiki/Felidae
* https://en.wikipedia.org/wiki/Reptile
* https://en.wikipedia.org/wiki/Rodent
* https://en.wikipedia.org/wiki/Bear

=== Anthro RP Size
Use this single look up table to create the anthro's hite and wate. 
Refresher on calculating hite and wate is xref::CH04_Anthros_Size.adoc[here].
Appearance changes like tall or obese are made under <<_modifications,Modifications>>.


include::ROOT:partial$CH11_Table_Anthro_RP_Hite_and_Wate.adoc[]

=== Anthro RP Age
Determine the anthro's lifespan category and from that determine the RP's age in years.
If the referee prefers a young or older anthro it is recommended to select that here.

include::ROOT:partial$CH11_Table_Anthro_RP_Lifespan_Category.adoc[]

include::ROOT:partial$CH11_Table_Anthro_RP_Age.adoc[]

== Anthro RP Attributes
Anthro RP attributes are rolled like any other persona.
For RPs attributes do not select the anthro type.
The attributes are modified to reflect the anthro type.
This is done in the following section attribute supercharging.
Specific attributes like weak, or dumb, modified at <<_modifications,Modifications>>

include::ROOT:partial$CH11_Table_Anthro_RP_Attributes.adoc[]

=== Anthro RP Hit Points
A referee persona's Hit Points (HPS) maximum is determined the same as any other anthro persona.
The HPS Max are determined by the persona's CON attribute.

==== HPS Maximum
include::CH04_Anthros_HPS.adoc[tag=Anthro_HPS]

==== Damage System Shock
include::CH04_Anthros_HPS.adoc[tag=Anthro_DSS]

==== Anthro RP Recovery
include::CH04_Anthros_HPS.adoc[tag=Anthro_REC]

=== Anthro Type Attribute Corrections
For RPs attributes do not select the anthro type.
The attributes are modified to reflect the anthro type.
For RPs the attributes do not matter.
So an RP could be a clumsy feline.
If this is not fun for the campaign correct the necessary attribute.
Attributes are never corrected down. 

include::ROOT:partial$CH11_Table_Anthro_RP_Attribute_Correction_Type.adoc[]

== Anthro RP Movement Rate
Movement rate is dependent on DEX and represented in hexes per unit.
If the referee needs a slow or fast RP this is modified at <<_modifications,Modifications>>

include::ROOT:partial$CH03_Table_Dexterity_and_Movement_Rate.adoc[]

== Anthro RP Armour Rating
Armour rating is adjusted using DEX.
// this in include from Anthro AR
include::CH04_Anthros_AR.adoc[lines=3..20]

== Anthro RP Wate allowance
The better the PSTR the more she can lift.

include::ROOT:partial$CH03_Table_Physical_Strength_and_Wate_Allowance_(kg).adoc[]

== Anthro RP Mutations
Referee personas mutate the same as other personas. 
The referee can push for mutations by doubling the chance.
The table should be used as guide if mutations are to be assigned.
Pure Strains are not vessels for zany mutations.
Insectoids rarely get physical mutations.
Keep in mind that some mutations are campaign changers and should be appropriately rare.

include::ROOT:partial$CH04_Table_anthro_mutations.adoc[]

== Anthro RP EXPS Level
Generate an experience level for every anthro RP.
Anthros have vocations and the EXPS level can be their most important roll.
EXPS level impacts how many artifacts and skill levels the RP gets.

include::ROOT:partial$CH11_Table_Referee_Persona_Level.adoc[]

== Anthro RP Vocation
All anthros get a vocation. 
The referee should choose the vocation that best suits the needs of the story and milieu.

include::ROOT:partial$CH11_Table_Referee_Persona_Class.adoc[]

=== Vocation Attribute Correction
For RPs attributes do not select the vocation type.
The attributes are modified to reflect the vocation type.
For RPs the attributes do not matter.
So an RP could be a clumsy spie.
If this is not fun for the campaign correct the necessary attribute.
Attributes are never corrected down. 

include::ROOT:partial$CH11_Table_Referee_Persona__Vocation_Supercharge.adoc[]

== Anthro RP Equipment
Referee personas carry equipment: they should be supplied with food, survival equipment, and funds.
What the referee persona is carrying as survival equipment will vary depending on terrain.
Referee personas are also assumed to have collected artifacts throughout their travels.
RPs get one artifact for every experience level.

=== Mundane
Referee personas carry equipment: they should be supplied with food, survival equipment, and funds.
What the referee persona is carrying as survival equipment will vary depending on terrain.

xref:ii-roll_playing_rules:CH24_Mundane_Equipment.adoc[Mundane Equipment]

=== Artifacts
Artifacts are technological devices that behave like magical devices.
The referee can decide if an RP needs a specific artifact.
The referee can limit the artifacts an RP has to maintain game balance.

It is assumed that an RP will know how to use their artifacts. 
This is not a given though an RP could be carrying an unidentified toy.
The referee can choose which ever is the most fun.
High level referee personas can have tremendous wealth and lots of cool stuff. 


.*Referee Persona TOYs*
* one roll on TOY table per EXPS Level
* vocation limits do not apply
* space vehicle, robot or vehicle limits do not apply
* treasure is accumulated but does not count as roll

include::ROOT:partial$CH41_Table_TOY_Type.adoc[]

== Anthro RP Combat Table
The combat table keeps track of the persona's combat skills and increases with EXPS level.
The referee persona's combat table is calculated here.
It is not as exact as a player persona's combat table.
The combat table is for tactical combat used in the Roll Playing System.
If you are using the Role Playing System you can skip this step.

include::ROOT:partial$CH11_Table_RP_Bonus_Proficient_(BP).adoc[]

include::ROOT:partial$CH11_Table_Calculated_Level_Bonus__for_RPs_with_Classes.adoc[]

include::ROOT:partial$CH11_Table_Bonus_Non_Proficient_(BNP).adoc[]

== Anthro RP Combat Ratio
// This is combat ratio boiler plate and appears in robots and aliens also

// tag::Combat_Ratio[]
Combat ratio is how tough the persona is.
The Combat Ratio is a numerical measure of how dangerous the RP is in combat.
The CR is used to determine EXPS value and number of attackers in the Roll Playing Rules.
If you are using the Role Playing Rules you can skip this section.

The higher the combat ratio the more powerful the adversary is in combat.
The Combat Ratio number equals how many first level anthro personas are needed for a fair fight.
A CR of 20 would indicate a very dangerous opponent in combat.
20 first level anthros would be required for a fair fight.
A Combat Ratio of 1/10 would represents a weaker opponent.
A first level anthro could fight 20 of the RPs and it would still be a fair fight.

Combat ratio is a measure of the referee persona's strength in combat.
It does not automatically indicate the number of RP's that show up every time.
The number of RPs present is determined by the culture, resources and story of the milieu.

An RP's CR determines the Combat EXPS earned when the RP is defeated in combat.

=== Calculating a Combat Ratio
. RPs initial CR is 1
. Add all the Pluses to the CR
. Multiply all the Times to the CR

.CR = (1 + all Pluses) * all Times
****
An RP with a Plus 1, Plus 4, Plus 2, Times 1.25, and Times 2.0 +
(1 + 1 + 4 + 2) * 1.25 * 2.0 = 20
****

// end::Combat_Ratio[]

=== Anthro RP Combat Ratio Adjustments
Anthro RP Combat Ratio is tricky to calculate because anthros are soggy bags of mostly water.
However their weapons and vocations can make them the most dangerous RPs in the game.

When preparing an anthropomorphs combat ratio, the referee should try to take into account all the equipment that the RP has access to.
This means that considerable time may have to be spent in the toy section before the combat ratio can be calculated.
Experienced referees will find that the combat ratio is not needed for estimating equivalent combat conditions but more useful in calculating the RPs experience point value which includes EXPS for encounters other than combative ones.

include::ROOT:partial$CH11_Table_RP_CR_Anthro.adoc[]

// general CR adjustments list of tables.
// heading is === for each table
include::ROOT:partial$CH11_RP_CR_General.adoc[]

== Anthro RP Role Playing Tools
A Canon Referee Persona is more than a collection of attributes and artifacts.
The tables here help the referee fill in the blanks.
//completely created use as a frame work

== Anthro RP Story
Everything has a story.
The depth of the story depends on the referee persona's relevance.
Cannon fodder have no back story. 
Canon referee personas have all the back story possible.

The backstory for a referee personas must be massaged to fit into the milieu of the story.



All referee personas must have an origin, presence, and goal.
The origin of an RP should explain where it came from and why it things the way it does.
The presence of the RP will dictate how and why it interacts with the expedition.
The goal of an RP is what it wants from the campaign, dictating what it will do with the expedition and when it will part company.

For 95% of the RPs the expedition will encounter, the Trinity of the RP (origin, presence, and goal) will be pre-determined.
Referee personas such as innocent civilians and animals will have simplistic origins such as migrating through the area or on their way to work.
Their presence might be riding on the subway or rummaging through the bushes.
Their goal may be to find some berries to eat or to get to work on time.
If the expedition frequently intervenes in the lives of such unimportant referee personas, the referee need have no more prepared than usual.

If the referee persona is a more important one the referee must create  a more detailed origin, presence, and goal.
Let's consider a young man from the farming district of his impoverished planet (origin) is willing to hire on for the expedition as a porter (presence) if they will take him off planet (goal).
Another referee persona could be a very hungry alien that just jumped out of a tree (origin) and is ferociously attacking the expedition (presence) because the alien's hungry and the expedition members look like something good to eat (goal).

=== Origin
Vishna Shraloor is a referee persona with death field generation (a mental mutation).
She matured not knowing that this lethal power was within her.
She grew up through a series of profound personal tragedies: the death of her parents, the death of teachers, the death of mourning relatives, the death of her playmates, the death of social workers, and the death of foster parents.
Many of these deaths may have been caused by her misunderstood mental ability.
That is her sad origin.

include::ROOT:partial$CH11_Table_Referee_Persona_Origin.adoc[]

=== Presence
Vishna's presence is one of a lonely unhappy persona who constantly associates with people she does not like because the people around her tend to die frequently.
Her profession is that of an orbital satellite repair person, a solitary job for certain.
She has chosen to hang around with the expedition because she does not particularly like them much.
This is her presence.

include::ROOT:partial$CH11_Table_Referee_Persona_Presence.adoc[]

=== Goal
Ms. Shraloor's goals are varied.
She would like to destroy the society that has rejected her so totally and she sees the expeditions mentality as something that she can exploit to this end.
If an expedition member should happen to befriend her, show her the nature of her mutation, and nurse her through the subsequent guilt, she may follow another path and desire to help the society that continued to reach out to her despite their extreme risk.
These are her potential goals.

include::ROOT:partial$CH11_Table_Referee_Persona_Goal.adoc[]

This chapter provides no guidelines on preparing an origin or goal for the referees personas but it does help with the presence of the referee personas.
In fact, this chapter could be considered a guide on how to prepare a referee personas presence.
If the ref knows that she needs RPs but has no origins or goals, then it might help to create the persona presence first.
This is an excellent procedure for sparking the imagination or solidifying a watery idea.

=== Anthro RP Personality
The referee is expected to play up these personality traits whenever possible.
Extroverted personality traits are NOT irrational: a diplomatic RP will not try to play consul to a crazed combat robot but she may intercede between inter-expedition differences.
Aliens and robots also get a roll on the Extroverted Personality table.
Properly functioning robots would not have  a shred of personality whatsoever, but the free willed robots of EXP are malfunctioning and extroverted personalities or even insanities are possible.

include::ROOT:partial$CH11_Table_Referee_Persona_Extroverted_Personality_Trait.adoc[]

==== Introverted
The Introverted Personality Sub-table indicates subtle personality traits.
These traits are not too strong and should only be employed by the referee when decisions must be made by the RP.
Such traits are played discreetly by the referee, and may only occasionally be used or noticed.

include::ROOT:partial$CH11_Table_Introverted_Personality_Trait.adoc[]

==== Insane
The Insane Personalities Table lists irrational actions that are basically pathological.
Insane personality traits can appear in completely unexpected situations, endangering the referee persona and the expedition.
The easiest and most fun referee personas to play are insane ones, but they should be kept relatively rare since EXP is an insane enough game as it is.
Referees are not expected to be psychiatrists and can role-play the mental illness however they interpret them.
If the roll on this table has been directed from the Extroverted Personality Trait Table the insanity will be quite overt.
If the referee is rolling an insane personality off of the Introverted Personality Trait then the insanity will be less obvious.

include::ROOT:partial$CH11_Table_Insane_Referee_Persona_Personality_Traits.adoc[]

== Anthro RP Appearance
An RPs appearance is divided into two categories: hygiene and dress.
Hygiene represents the personas normal level of personal care.
The hygienic habits of the RP are determined on the RP Hygiene table.
// most important is the type and subtype usually enough

=== Gender
Not physiology or sexuality. 
Gender here is appearance only.

include::ROOT:partial$CH11_Table_RP_Gender.adoc[]

=== Clothing
The dress of an RP is even more variable than hygiene.
An RP may have several favorite styles and may even combine them in some random arrangement.
The roll on the table dress indicates which type of dress is worn: shoes, shirts, blouses, pants, hair-dos, etc.
Appearance is mostly directed at anthropomorph RPs, but it can also include aliens or deeply eccentric robots.
It is easy to imagine a filthy canine lumberjack but an immaculate six legged alien dressed in traditional tribal gowns is harder to visualize.
Robots can certainly have hygienic qualities, appearing dirty or well washed, but robot dress may be just too absurd.
For instance, would a 60s style robot have fins and chrome bumpers?

include::ROOT:partial$CH11_Table_Referee_Persona_Dress.adoc[]

=== Hygiene
Hygiene is not unwavering like an attribute but is dependent on the scenario at hand.
For example, a habitually immaculate RP that just dived into mud would look like someone who dived into mud;
a habitually filthy spie would not arrive un-groomed at an aristocratic function she was trying to infiltrate.
However, the immaculate RP would clean the mud off herself sooner than the filthy spie and the filthy spie would be the first to get soiled at the aristocratic bash.
The dress of the referee persona does not reflect ANYTHING about the referee persona.

include::ROOT:partial$CH11_Table_Referee_Persona_Hygiene.adoc[]


== Anthro RP Beliefs
The referee should be prepared to have their preferred personas possess some personal beliefs that may affect their attitude, and how they act while role-playing.
Beliefs are divided into three categories: political, religious, and philosophical.
The player will have from 0-3 (d4-1) separate beliefs, where 0 is none and 3 is three rolls on Table 11.19. 
// ha ha you missed this sentence

include::ROOT:partial$CH11_Table_Referee_Persona__Beliefs.adoc[]

The beliefs are more transient than the RP's personality and they will can conflict directly with the referee persona's personality.
The belief tables are somewhat self-explanatory and are mostly used as the tack that a particular persona will take when arguing ethics with expedition personas.

include::ROOT:partial$CH11_Table_Referee_Persona_Religious_Belief.adoc[]

include::ROOT:partial$CH11_Table_Referee_Persona_Political_Belief.adoc[]

include::ROOT:partial$CH11_Table_Referee_Persona_Philosophical_Belief.adoc[]

== Modifications
Referee mods.
Age go back and do it.
Gender go back and do it.

include::ROOT:partial$CH11_Table_Anthro_RP_Modifiers.adoc[]

== Anthro RP Name
Anthro names follow standard role playing game nomenclature. 
Each anthro will usually have a given name and a surname.
Both the given name and surname are created by the player.
The anthro naming structure is most familiar naming structure.

.example persona names
* A mechanic - Hans Tinker
* A mercenary - Hans Grenade
* A nothing - Hans Ophmistuph


Often the most important part of a referee persona is its name.
The description of a humanoid may be glossed over and that of an aliens forgotten completely but the name will always be remembered.
The players will recall an RPs name before they will remember her personality, dress, or special abilities.
There is no question that a referee personas name is much more important to the campaign than that of an expedition persona.
Often an RPs name will have some significance, like a veterinarian named Ivy Blodgett or a melancholic nothing named Sue Siedal.




