= Anthro RP

// always better from referee and based on the campaign story.
// this is a helping tool
Anthro referee personas (RP) will be the most common type that the referee will introduce to the expedition.
Such referee personas can vary from altruistic veterinarians that are placing themselves at risk to heal the expedition to ruthless anti-knites that are using the expedition as a disposable tool in their quest for universal chaos.
Other RPs will be colourful campaign descriptors like meaningless civilians that clog sidewalks or mutant markets.
Such anthro referee personas should require no more personification than an accented voice or a marker on the table.
If the poor innocent civilian is unfortunate misfortune to happen upon the expedition during a combat situation then a little more preparation is required.

The largest source of detailed anthro personas is the persona morgue.
These are ready-made referee personas that may even include a personality.
It is not recommended that the ref directly plagiarize a player's old persona but merely use it for inspiration.

.*Anthro RP Checklist*
* *RP ROLL PLAYING (Data)*
. Relevance
. Persona Record Sheet
. Anthro Type
. Hit and Wate
. Age
. Attributes
. Movement Rate
. Armour Rating
. Wate Allowance
. Mutation
. EXPS Level
. Vocation
. Equipment
.. Mundane
.. Artifact
. Combat Table
. Combat Ratio
* *RP ROLE PLAYING (Fun)*
. Story
.. Origin
.. Presence
.. Goal
.. Personality
. Appearance
.. Clothing
.. Hygiene
.. Gender
. Beliefs
.. Religious
.. Political
.. Philosophical
. Modifications
.. attributes
.. size
.. age
. Name
. Have Fun!

== Anthro RP Relevance
Many referee's will prepare extensive details on every persona they create. 
In the days when everything was generated by dice and recorded on paper it was impossible.
Today with computerized generated personas it is possible.
It is just not always necessary.

The referee persona relevance is decided by the referee.
The persona relevance is not set in stone.
A referee persona's relevance can increase if for some reason they get entangled in the expedition.

include::ROOT:partial$CH11_Table_RP_Relevance.adoc[]

=== Cannon Fodder

[quote]
____
Cannon Fodder is a despicable term from warfare.
Cannon Fodder were pure strain humans used to charge cannons.
____

Cannon fodder hold no useful information.
Cannon fodder offer no measurable opposition to the persona's goals.
Cannon fodder have no nutritional value, monetary value or useful parts.
Are called Sidewalk Civilians in EXP.


These are the unprepared personas that simply fill the streets of a city, village, or spacecraft in an effort to describe a crowd.
Such personas will generally have no more than 9 HPS, no weapons, and no combat table.
Any civilian attributes that are required are rolled as needed and usually need not be recorded.
If the ref is suspicious of the expedition's intentions when entering a civilian area, she may generate several sets of attributes for those exceptional civilians that are capable of defending themselves.
Cannon fodder refers to background personas that need little or no information. 
Cannon fodder not have any substantial outcome for the campaign.
A cannon fodder persona may only have HPS and a blurry description.
// choose fixed 9 or 6
// may roll an anthro type
// if any more then canon fodder
// no persona record required.
// you can stop here

=== Canon Fodder
Canon fodder can change the story of the campaign.
Canon fodder could injure or kill a player persona.
Canon fodder may make a decision that alters the well being of the expedition.
Canon fodder require a bit more information than cannon fodder.
Canon fodder may need several attributes, campaign info, HPS, or combat tables.
For anthros this could be a merchant who is going to steal from the expedition.
// random goal 
// random purpose
// determines attributes
// just here for the STORY

=== Canon Referee Persona
This is the big leagues!
In those instances where the expedition comes across a true referee persona, the ref must be fully prepared with attributes, anthro type, mutations, class, level, personality, and equipment.
There is no telling what will be required of the persona once it is introduced to the expedition.
These are the referee personas where the ref must have a reasonably detailed origin, presence, and goal.

A canon referee persona is a complete referee persona.
A complete referee persona used to represent an enormous amount of preparation and work.
Much of this work has been replaced by puters. 
There is a special level of irritation when a full referee persona is violently deleted by paranoid players. 

Canon referee personas are integral participants in the campaign story.
These personas can be powerful recurring enemies, or comrades in arms.
Canon referee personas have personality, history, goals, morals and more. 
Most of the time referees create the details of their most important referee personas.
These personas are essential in moving the story forward and making the game more fun.
There are three levels of persona relevance. 
Cannon Fodder, Canon Fodder and Canon Personas.
Each level requires more input and information about the referee persona.
Most often the referee will know what she is looking for persona relevance.
In case the referee 

== Anthro RP Record Sheet
The referee persona record sheet is just another persona record sheet.
There are few bonus elements that referee must keep track of.
Most player personas do not have elements like personality, politics or religion.
The referee persona record sheet can also be used to keep track of expedition interactions.
// ID number
// share them worldwide

:art: aquarium_not_aquarian.png
:width: 250px
:snark: An aquarium not an aquarian
:artist: Imagestoks 
:date: 2017
:license: Copyright Imagestoks 2015

include::ROOT:partial$articulate.adoc[]

== Anthro RP Type
The referee may not be certain which anthropomorph type she wants her RP to have.
Regardless of whether the anthro type was predetermined or randomly generated, there are other factors that she must consider.The referee must choose a decorative subspecies for the persona.
Florians may be petunias or fungi;
Insectoids may be ants, spiders, or mantis;
and so on.
The available choices of subspecies are so extensive that no tables have been prepared and the ref must choose the decorative subspecies on her own.
// always better from referee and based on the campaign story.
// this is a helping tool

include::ROOT:partial$CH11_Table_Anthro_RP_Anthro_Type.adoc[]

=== Anthro Sub Types
Easiest is mutt. 
Looks like anthro type but can't be distinguished.
Anthro type is phenotypical not science.
// always better from referee and based on the campaign story.
// this is a helping tool
// very limited

include::ROOT:partial$CH11_Table_Anthro_RP_Anthro_Type_Subs.adoc[]

.source links for various anthro types
* https://en.wikipedia.org/wiki/List_of_fish_common_names
* https://en.wikipedia.org/wiki/List_of_dog_breeds
* https://en.wikipedia.org/wiki/List_of_horse_breeds
* https://en.wikipedia.org/wiki/Ungulate
* https://en.wikipedia.org/wiki/Felidae
* https://en.wikipedia.org/wiki/Reptile
* https://en.wikipedia.org/wiki/Rodent
* https://en.wikipedia.org/wiki/Bear

=== Anthro RP Hite and Wate
Hite and Wate can be adjusted for adjectives like tall, skinny, short and obese.
The adjustments are listed on the Upward and Downward Anthro Attribute Adjustments.
// adjust here or later in mods

include::ROOT:partial$CH11_Table_Anthro_RP_Hite_and_Wate.adoc[]

=== Anthro RP Age
The age range of the anthro referee persona is first determined on Table 11-2.8: Anthro RP Age Category.
Then the exact age in years depending on the anthro type an age range is.
// these can be adjusted here recommended to adjust here

include::ROOT:partial$CH11_Table_Anthro_RP_Lifespan_Category.adoc[]

include::ROOT:partial$CH11_Table_Anthro_RP_Age.adoc[]

== Anthro RP Attributes
Anthro referee persona attributes are generated as per Table 11-2.2: Anthro RP Attributes.
As always the referee should alter the attributes to the needs of the story and how the referee persona fits in.
// can be altered later in modifications 

Referees need to show some discretion when they choose to make upwards attribute adjustments.
There are many ways that an referee persona can have her attributes adjusted upwards.
There are the adjectives listed on Table 11-2.: Upwards Anthro RP Adjustments.
Then there are further upwards adjustments that are attributed to anthro type, and then more attribute adjustments attributed to class.

include::ROOT:partial$CH11_Table_Anthro_RP_Attributes.adoc[]

=== Anthro RP Hit Points
A referee persona's Hit Points (HPS) maximum is determined the same as any other anthro persona.
The HPS Max are determined by the persona's CON attribute.
As the referee has more and more anthro RPs succumb violently to the paranoia of player personas there may be a desire to give all their referee persona's high CONs and the upward attribute adjustment of Resilient.

Don't bother.
If the referee cannot keep her referee personas out of combat by role playing there will be no amount of hit points that will keep her alive.

==== HPS Maximum
include::CH04_Anthros_HPS.adoc[tag=Anthro_HPS]

==== Damage System Shock
include::CH04_Anthros_HPS.adoc[tag=Anthro_DSS]

==== Anthro RP Recovery
include::CH04_Anthros_HPS.adoc[tag=Anthro_REC]

=== Type Attribute Supercharging
Referee personas are super heroes.
At most one attribute should be supercharged.
If the RP still does not meet class or racial requirements, remember RPs are assumed to have an origin of some sort and those missing the required attributes may have originally been nothings or lost the attribute points during some traumatic part of their origin.
If the referee feels that RPs must have the required attributes for their class, the offending attributes may be re-rolled.
Remember that ant attribute requirements only apply to personas while rolling up and any attribute changes that subsequently occur cannot force a persona from her anthro type.

include::ROOT:partial$CH11_Table_Anthro_RP_Attribute_Supercharge.adoc[]

== Anthro RP Movement Rate
Movement rate for anthro referee personas is determined in the same fashion as for player personas.
The upwards (fast) and the downwards (slow) attribute modifiers can alter the movement rate of the referee persona.

include::ROOT:partial$CH03_Table_Dexterity_and_Movement_Rate.adoc[]

== Anthro RP Armour Rating
// this in include from Anthro AR
include::CH04_Anthros_AR.adoc[lines=3..20]

== Anthro RP Wate allowance
The stronger the anthro is the more she can lift.

include::ROOT:partial$CH03_Table_Physical_Strength_and_Wate_Allowance_(kg).adoc[]

== Anthro RP Mutations
If randomness is ruling the creation of this referee persona.
If the referee would like the anthro RP to be more likely to mutate she can halve the 1d100 die roll, therefore doubling the chance of mutations.

include::ROOT:partial$CH04_Table_anthro_mutations.adoc[]

== Anthro RP EXPS Level
A referee personas EXPS level is applicable to anthros, aliens and robots.
If the referee personas class should happen to be a nothing, the experience level will represent the number of rolls she is entitled to in

include::ROOT:partial$CH11_Table_Referee_Persona_Level.adoc[]

== Anthro RP Vocation
The referee persona vocation should only be used for those referee personas that can pursue a vocation.
This would be anthros, alien tool users, androids, and the rare robot that has vocation skills.
The anthro referee persona's most important element will be her vocation.
The referee persona vocation table is included for those instances where the referee cannot decide what vocation she wishes her referee persona to have.

include::ROOT:partial$CH11_Table_Referee_Persona_Class.adoc[]

=== Vocation Attribute Supercharging
To ensure that referee persona meets the attribute requirements of their vocation.
Take the higher of the two.

include::ROOT:partial$CH11_Table_Referee_Persona__Vocation_Supercharge.adoc[]

== Anthro RP Equipment
Referee personas carry equipment: they should be supplied with food, survival equipment, and funds.
What the referee persona is carrying as survival equipment will vary depending on terrain.
Referee personas are also assumed to have collected artifacts throughout their travels.
RPs get one artifact for every experience level.
This includes multi-class levels.

=== Mundane
Referee personas carry equipment: they should be supplied with food, survival equipment, and funds.
What the referee persona is carrying as survival equipment will vary depending on terrain.

xref:ii-roll_playing_rules:CH24_Mundane_Equipment.adoc[Mundane Equipment]

=== Artifacts
Referee personas are also assumed to have collected artifacts throughout their travels.
RPs get one artifact for every experience level.
This includes multi-class levels.
Treasure does not count as a roll so RPs can accumulate considerable wealth in addition to their personal collection of artifacts.
Nothing RPs do not get a roll on the Toy Table but they do get additional treasure rolls.
This tends to make RP nothings tremendously wealthy.
If the referee desires impoverished nothings, she can save herself a whole lot of rolling on the treasure tables.
Nothing RPs also receive their complimentary one piece of miscellaneous equipment.
// they know how to use their artifacts

include::ROOT:partial$CH41_Table_TOY_Type.adoc[]

== Anthro RP Combat Table
The RP combat table is calculated the same as any other persona's combat table.

The initial combat table is calculated here and the level adjustment should be added to the Bonus Proficient (BP).
For simplicity sake we use one combined level bonus for all three weapon types for the referee persona.
If detail must prevail the level bonus can be calculated by hand.
Calculate the Bonus Proficient on Table 11.11: Bonus Proficient for Referee Personae, then add the level bonus from Table 11.11.1: Total Level Bonus by Class.
This will create a quick Bonus Proficient that reflects the referee personas attributes, class and level.

include::ROOT:partial$CH11_Table_RP_Bonus_Proficient_(BP).adoc[]


include::ROOT:partial$CH11_Table_Calculated_Level_Bonus__for_RPs_with_Classes.adoc[]

include::ROOT:partial$CH11_Table_Bonus_Non_Proficient_(BNP).adoc[]

== Anthro RP Combat Ratio
The combat ratio aids the referee in objectively rating how tough a referee persona has been created.

The anthropomorph RP combat ratio is very difficult to calculate in that their use of artifacts can greatly alter their deadliness regardless of what their class is or their attributes are.
Even the most deadly referee persona can be handled easily by the expedition if the referee makes a mistake.
Also the most benign referee persona can become extremely dangerous if she manages to get a hold of a deadly weapon.

When preparing an anthropomorphs combat ratio, the referee should try to take into account all the equipment that the RP has access to.
This means that considerable time may have to be spent in the toy section before the combat ratio can be calculated.
Experienced referees will find that the combat ratio is not needed for estimating equivalent combat conditions but more useful in calculating the RPs experience point value which includes EXPS for encounters other than combative ones.

The combat ratio indicates the number of expedition personas that should be needed in combat for a fair fight with that one referee persona.
The higher the combat ratio, the stronger the referee persona.
In other words, if 1 persona vs.
20 referee personas constitutes a fair fight, this is a pretty feeble referee persona.
If the combat ratio indicates 20 personas vs.
1 RP is a fair fight, then it is a tough referee persona.
The combat ratio is just an indicator of the RPs combat strength.
The number of RPs appearing depends on the type of referee persona, its social behaviour, and the setting of the scenario.
If the combat ratio is 1/20, it does not necessarily mean that 20 RPs will automatically show up for every persona.

*Calculating CR*: Add up all the pluses first.
Then multiply all the times.
So a Combat Ratio with Plus 1 and Plus 4 and Plus 3 and Times 1.25 and Times 2.0.
It would be calculated as so: 1 plus 4 plus 3 = 8;
times 3 times 1.25 gives a CR of 30!

=== Anthro RP Combat Ratio Adjustments
include::ROOT:partial$CH11_Table_RP_CR_Anthro.adoc[]

// general CR adjustments list of tables.
// heading is === for each table
include::ROOT:partial$CH11_RP_CR_General.adoc[]

== Anthro RP Role Playing Tools
A referee persona is more than a collection of attributes and some artifacts.
Referee personas are an essential part of the story being told in the campaign.
RPs are expected to have all the personality qualities as any other persona.
This challenges the limits of creativity of the referee because she must supply different personalities, appearance  and qualities for the quadrillions of referee personas that will participate in the campaign.
If the referee does not already have a particular appearance, personality, or set of beliefs in mind for her RP, she may find the tables provided useful.

== Anthro RP Story
Everything has a story.
As previously stated, referee personas can have a wide degree of involvement in a campaign or with an expedition.
All referee personas must have an origin, presence, and goal.
The origin of an RP should explain where it came from and why it things the way it does.
The presence of the RP will dictate how and why it interacts with the expedition.
The goal of an RP is what it wants from the campaign, dictating what it will do with the expedition and when it will part company.

For 95% of the RPs the expedition will encounter, the Trinity of the RP (origin, presence, and goal) will be pre-determined.
Referee personas such as innocent civilians and animals will have simplistic origins such as migrating through the area or on their way to work.
Their presence might be riding on the subway or rummaging through the bushes.
Their goal may be to find some berries to eat or to get to work on time.
If the expedition frequently intervenes in the lives of such unimportant referee personas, the referee need have no more prepared than usual.

If the referee persona is a more important one the referee must create  a more detailed origin, presence, and goal.
Let's consider a young man from the farming district of his impoverished planet (origin) is willing to hire on for the expedition as a porter (presence) if they will take him off planet (goal).
Another referee persona could be a very hungry alien that just jumped out of a tree (origin) and is ferociously attacking the expedition (presence) because the alien's hungry and the expedition members look like something good to eat (goal).

=== Origin
Vishna Shraloor is a referee persona with death field generation (a mental mutation).
She matured not knowing that this lethal power was within her.
She grew up through a series of profound personal tragedies: the death of her parents, the death of teachers, the death of mourning relatives, the death of her playmates, the death of social workers, and the death of foster parents.
Many of these deaths may have been caused by her misunderstood mental ability.
That is her sad origin.

include::ROOT:partial$CH11_Table_Referee_Persona_Origin.adoc[]

=== Presence
Vishna's presence is one of a lonely unhappy persona who constantly associates with people she does not like because the people around her tend to die frequently.
Her profession is that of an orbital satellite repair person, a solitary job for certain.
She has chosen to hang around with the expedition because she does not particularly like them much.
This is her presence.

include::ROOT:partial$CH11_Table_Referee_Persona_Presence.adoc[]

=== Goal
Ms. Shraloor's goals are varied.
She would like to destroy the society that has rejected her so totally and she sees the expeditions mentality as something that she can exploit to this end.
If an expedition member should happen to befriend her, show her the nature of her mutation, and nurse her through the subsequent guilt, she may follow another path and desire to help the society that continued to reach out to her despite their extreme risk.
These are her potential goals.

include::ROOT:partial$CH11_Table_Referee_Persona_Goal.adoc[]

This chapter provides no guidelines on preparing an origin or goal for the referees personas but it does help with the presence of the referee personas.
In fact, this chapter could be considered a guide on how to prepare a referee personas presence.
If the ref knows that she needs RPs but has no origins or goals, then it might help to create the persona presence first.
This is an excellent procedure for sparking the imagination or solidifying a watery idea.

=== Anthro RP Personality
The referee is expected to play up these personality traits whenever possible.
Extroverted personality traits are NOT irrational: a diplomatic RP will not try to play consul to a crazed combat robot but she may intercede between inter-expedition differences.
Aliens and robots also get a roll on the Extroverted Personality table.
Properly functioning robots would not have  a shred of personality whatsoever, but the free willed robots of EXP are malfunctioning and extroverted personalities or even insanities are possible.

include::ROOT:partial$CH11_Table_Referee_Persona_Extroverted_Personality_Trait.adoc[]

==== Introverted
The Introverted Personality Sub-table indicates subtle personality traits.
These traits are not too strong and should only be employed by the referee when decisions must be made by the RP.
Such traits are played discreetly by the referee, and may only occasionally be used or noticed.

include::ROOT:partial$CH11_Table_Introverted_Personality_Trait.adoc[]

==== Insane
The Insane Personalities Table lists irrational actions that are basically pathological.
Insane personality traits can appear in completely unexpected situations, endangering the referee persona and the expedition.
The easiest and most fun referee personas to play are insane ones, but they should be kept relatively rare since EXP is an insane enough game as it is.
Referees are not expected to be psychiatrists and can role-play the mental illness however they interpret them.
If the roll on this table has been directed from the Extroverted Personality Trait Table the insanity will be quite overt.
If the referee is rolling an insane personality off of the Introverted Personality Trait then the insanity will be less obvious.

include::ROOT:partial$CH11_Table_Insane_Referee_Persona_Personality_Traits.adoc[]

== Anthro RP Appearance
An RPs appearance is divided into two categories: hygiene and dress.
Hygiene represents the personas normal level of personal care.
The hygienic habits of the RP are determined on the RP Hygiene table.
// most important is the type and subtype usually enough

=== Gender
Not physiology or sexuality. 
Gender here is appearance only.

include::ROOT:partial$CH11_Table_RP_Gender.adoc[]

=== Clothing
The dress of an RP is even more variable than hygiene.
An RP may have several favorite styles and may even combine them in some random arrangement.
The roll on the table dress indicates which type of dress is worn: shoes, shirts, blouses, pants, hair-dos, etc.
Appearance is mostly directed at anthropomorph RPs, but it can also include aliens or deeply eccentric robots.
It is easy to imagine a filthy canine lumberjack but an immaculate six legged alien dressed in traditional tribal gowns is harder to visualize.
Robots can certainly have hygienic qualities, appearing dirty or well washed, but robot dress may be just too absurd.
For instance, would a 60s style robot have fins and chrome bumpers?

include::ROOT:partial$CH11_Table_Referee_Persona_Dress.adoc[]

=== Hygiene
Hygiene is not unwavering like an attribute but is dependent on the scenario at hand.
For example, a habitually immaculate RP that just dived into mud would look like someone who dived into mud;
a habitually filthy spie would not arrive un-groomed at an aristocratic function she was trying to infiltrate.
However, the immaculate RP would clean the mud off herself sooner than the filthy spie and the filthy spie would be the first to get soiled at the aristocratic bash.
The dress of the referee persona does not reflect ANYTHING about the referee persona.

include::ROOT:partial$CH11_Table_Referee_Persona_Hygiene.adoc[]


== Anthro RP Beliefs
The referee should be prepared to have their preferred personas possess some personal beliefs that may affect their attitude, and how they act while role-playing.
Beliefs are divided into three categories: political, religious, and philosophical.
The player will have from 0-3 (d4-1) separate beliefs, where 0 is none and 3 is three rolls on Table 11.19. 
// ha ha you missed this sentence

include::ROOT:partial$CH11_Table_Referee_Persona__Beliefs.adoc[]

The beliefs are more transient than the RP's personality and they will can conflict directly with the referee persona's personality.
The belief tables are somewhat self-explanatory and are mostly used as the tack that a particular persona will take when arguing ethics with expedition personas.

include::ROOT:partial$CH11_Table_Referee_Persona_Religious_Belief.adoc[]

include::ROOT:partial$CH11_Table_Referee_Persona_Political_Belief.adoc[]

include::ROOT:partial$CH11_Table_Referee_Persona_Philosophical_Belief.adoc[]

== Modifications
Referee mods.
Age go back and do it.
Gender go back and do it.

include::ROOT:partial$CH11_Table_Anthro_RP_Modifiers.adoc[]

== Anthro RP Name
Anthro names follow standard role playing game nomenclature. 
Each anthro will usually have a given name and a surname.
Both the given name and surname are created by the player.
The anthro naming structure is most familiar naming structure.

.example persona names
* A mechanic - Hans Tinker
* A mercenary - Hans Grenade
* A nothing - Hans Ophmistuph


Often the most important part of a referee persona is its name.
The description of a humanoid may be glossed over and that of an aliens forgotten completely but the name will always be remembered.
The players will recall an RPs name before they will remember her personality, dress, or special abilities.
There is no question that a referee personas name is much more important to the campaign than that of an expedition persona.
Often an RPs name will have some significance, like a veterinarian named Ivy Blodgett or a melancholic nothing named Sue Siedal.




