= Referee Personas

A Referee Persona (RP) is any persona that is *not* run by a player.
The persona could be from any of the families: anthro, robot, or alien.
If the persona is not controlled by a player it must be brought to life by the referee.
These special personas are called referee personas. 
// be well versed in the rules

NOTE: *Referee Personas have been called non player characters in the past RP=NPC*

== Referee Persona Checklist
Referee run personas require more data than player run personas.

.*General Referee Persona Checklist*
* *ROLL PLAYING INFO (Data)*
. Determine Relevance
.. Cannon Fodder
.. Canon Fodder
.. Canon Persona
. Persona Record Sheet
.. Record creation Date
.. Record unique RP ID
. Determine Family
.. Anthro
.. Alien
.. Robot
.. AI
. Determine Type
. Attributes
. Armour Rating
. Movement Rate
. Wate Allowance
. Mutation
. EXPS Level
. Vocation
. Equipment
.. Mundane
.. Artifact
. Combat Table
. Combat Ratio
* *ROLE PLAYING INFO (Fun)*
. Story
.. Origin
.. Presence
.. Goal
.. Personality
. Appearance
.. Clothing
.. Hygiene
.. Gender
. Beliefs
.. Religious
.. Political
.. Philosophical
. Modifications
.. attributes
.. size
.. age
. Name
. Have Fun!

== Referee Role-Playing
It is the responsibility of the ref to role-play referee personas to the best of her ability.
Intelligent aliens must seem and act intelligently.
Nomads will prefer their biome over any other luxury.
Anti-knites must not stray from their righteous path of entropy.
Robots lack facial expressions and body language.
In short the referee must be able to make even the temporary personas as real as possible.

=== Spread the Fun
Collaborative role playing groups will often have players represent referee personas.
This works well for personas that friendly and neutral to the expedition.
A player should not run a Heavy Combot referee persona that is attacking the expedition.
A player should not run an spie feline that knows about crucial campaign information. 
One of the players may have fun running a shop keeper that does not haggle her prices.


== Referee Persona Generation
// referee's ideas FTW 
// these tools are for helping out
It is rare that a referee persona's generation will be completely random.
There almost always is a reason for generating referee personas.
The expedition need's an ursidae mercenary for protection in the wilds.
The wilds need's to be populated with ferocious alien creatures.
The radioactive ruin may be ruled by an explorations bot lethally collecting specimen samples.

=== Descriptors
While there may be clear roles for the personas created these sections help fill in the gaps.
Each family type has descriptors that the referee can use to massage the referee persona.
For example referees can choose to have a tall smart feline.
There are hite, attribute and anthro type modifiers in each family section.

=== Pure Random
For the referee that is using the referee persona section for a purely random encounter.
The referee starts here with a roll on the Referee Persona Family Table.
Once the family type is decided take a look at the checklist and get rolling the dice. 

include::ROOT:partial$CH11_Table_RP_Family_Type.adoc[]

