= Referee Personas

A Referee Persona (RP) is any persona that is *not* run by a player.
The persona could be from any of the families: anthro, robot, or alien.
If the persona is not controlled by a player it must be brought to life by the referee.
These special personas are called referee personas. 

== Referee Role-Playing
It is the responsibility of the ref to role-play referee personas to the best of her ability.
Intelligent aliens must seem and act intelligently.
Nomads will prefer their biome over any other luxury.
Anti-knites must not stray from their righteous path of entropy.
Robots lack facial expressions and body language.
In short the referee must be able to make even the temporary personas as real as possible.

=== Spread the Fun
Collaborative role playing groups will often have players represent referee personas.
This works well for personas that friendly and neutral to the expedition.
A player should not run a Heavy Combot referee persona that is attacking the expedition.
A player should not run an spie feline that knows about crucial campaign information. 
One of the players may have fun running a shop keeper that does not haggle her prices.

== Referee Persona Relevance
Many referee's will prepare extensive details on every persona they create. 
In the days when everything was generated by dice and recorded on paper it was impossible.
Today with computerized generated personas it is possible.
It is just not always necessary.

The referee persona relevance is decided by the referee.
The persona relevance is not set in stone.
A referee persona's relevance can increase if for some reason they get entangled in the expedition.

=== Cannon Fodder
Cannon fodder refers to background personas that need little or no information. 
Cannon fodder not have any substantial outcome for the campaign.
A cannon fodder persona may only have HPS and a blurry description.

[quote]
____
Cannon Fodder is a despicable term from warfare.
Cannon Fodder were pure strain humans used to charge cannons.
Having no human value at all.
____

Cannon fodder hold no useful information.
Cannon fodder offer no measurable opposition to the persona's goals.
Cannon fodder have no nutritional value, monetary value or useful parts.

For anthros these are sidewalk civilians crowding city streets.
For aliens these are flora and fauna in the underbrush and trees.
For robots these are delivery drones navigating for digital overlords. 

=== Canon Fodder
Canon fodder can change the story of the campaign.
Canon fodder could injure or kill a player persona.
Canon fodder may make a decision that alters the well being of the expedition.

Canon fodder require a bit more information than cannon fodder.
Canon fodder may need several attributes, campaign info, HPS, or combat tables.

For anthros this could be a merchant who is going to steal from the expedition.
For aliens these are flora and fauna that can attack and injure the expedition.
For robots these are bots that act as low level sentries, spying or tracking the expedition. 

=== Full Referee Persona
A full referee persona used to represent an enormous amount of preparation and work.
Much of this work has been replaced by puters. 
There is a special level of irritation when a full referee persona is violently deleted by paranoid players. 

Full referee personas are integral participants in the campaign story.
These personas can be powerful recurring enemies, or comrades in arms.
Full referee personas have personality, history, goals, morals and even more. 
Most of the time referees create all the details of their referee personas.
This allows them to assist moving the story forward and making the game more fun.
These referee persona sections are tools to help inspire and build full referee personas.

== Referee Persona Generation
It is rare that a referee persona's generation will be completely random.
There almost always is a reason for generating referee personas.
The expedition need's an ursidae mercenary for protection in the wilds.
The wilds need's to be populated with ferocious alien creatures.
The radioactive ruin may be ruled by an explorations bot lethally collecting specimen samples.

=== Descriptors
While there may be clear roles for the personas created these sections help fill in the gaps.
Each family type has descriptors that the referee can use to massage the referee persona.
For example referees can choose to have a tall smart feline.
There are hite, attribute and anthro type modifiers in each family section.

=== Pure Random
For the referee that is using the referee persona section for a purely random encounter.
The referee starts here with a roll on the Referee Persona Family Table.
Once the family type is decided take a look at the checklist and get rolling the dice. 

include::ROOT:partial$CH11_Table_RP_Family_Type.adoc[]

=== Referee Persona Checklist
Make sure you get every element of your randomly created referee persona.
A referee persona includes all the elements of player persona plus a few more.
A referee persona is expected to have experience levels and a equipment.
This equipment could include complex artifacts.
Full referee personas will have personalities, beliefs, goals and history.
The general checklist is the broad strokes a referee persona. 
Each family has it's own detailed referee persona checklist.

.General Referee Persona Checklist
. Create a Persona Record Sheet
.. Record creation Date
.. Record unique RP ID
. Determine Family
. Determine Relevance
.. Origin
.. Presence
.. Goal
. EXPS Level
. Equipment
.. Mundane
.. Artifacts
. Vocation
. Combat Table
. Combat Ratio
. Name

== 3) Referee Persona Class

The referee persona class should only be used for those referee personas that can pursue a class.
This would be anthros, alien tool users, androids, and the rare robot that has class skills.
The anthro referee persona's most important element will be her class.
The nature of each class is discussed in http://expgame.com/?page_id=250[Chapter 8: Classes].
The referee persona class table is included for those instances where the referee cannot decide what class she wishes her referee persona to have.

// insert table 316

*Multi-Class*: Multi-class personas simply roll as often as the dice indicate.
If the same persona class is rolled twice, then the experience levels, determined later, are added together.
There is no limit other than realistic probability to the number of classes that a referee persona can have.
The first roll on multi-class will indicate that the referee will roll twice and any further rolls on multi-class will indicate another roll.
Knites cannot be multi-classed.

*Class Attributes*:  To ensure that referee persona meets the attribute requirements of their class.
The referee can utilize the Table 11.7: Class Attribute Adjustments.

// insert table 317

== 4) Experience Level of RP

A referee personas EXPS level is applicable to anthros, aliens and robots.
If the referee personas class should happen to be a nothing, the experience level will represent the number of rolls she is entitled to in http://expgame.com/?page_id=353[Chapter 53: Treasure].

// insert table 318

== 5) Referee Persona Combat Table

The RP combat table is calculated the same as any other persona's combat table.
Aliens use their natural attack table if they have no class abilities.
Anthropomorphs and class skilled aliens use the combat table described in Chapter 27: Tactical Combat.
Robots have their own combat table regardless of whether they are class skilled or not.
The robotic combat table is described in Chapter 31: Robotic Combat.
The referee may wish to simplify her RP combat tables to increase the speed of combat.
It is assumed that the referee will be ethical and round the RP combat tables (CTs) down.

*Alien Combat Table*: For more information about the alien combat table refer to http://expgame.com/?page_id=252[Chapter 9: Combat Tables].
This combat table is for natural attacks of the alien RP.
If the alien is advancing in a class she will use the Anthro Class RP combat table.
There is no such thing as a Bonus Non-Proficient (BNP) for natural attacks.
Aliens do  not have a BNP.
Alien PSTR is included in their damage attack, and they do not have a Damage Adjustor (DA) either.
The initial combat table can be calculated here, and it can be important to add the level bonus to the Bonus Proficient (BP).
Unfortunately the level bonus must be calculated by hand if it applies to the alien.
So for example an alien RP with a PSTR of 20 would increase her BP for Type A natural attack  by 20 at level 2, by 13 at level 3, and by 10 at level 4.

// insert table 319

*Robot Combat Table*: For more information about the robot combat table refer to http://expgame.com/?page_id=252[Chapter 9: Combat Tables].
The initial combat table is be calculated here.
Robots have a bonus non proficient (BNP) of zero.
Robots have no Maximum Roll (MR).
Unfortunately the level bonus must be calculated by hand for the robot RP.
So for example  a robot RP with a PSTR of 20 would increase her BP for Type A attack by 10 at level 2, by 7 at level 3, and by 5 at level 4.
If the robot is advancing in a class she will use the Anthro Class RP combat table.

// insert table 320

*Anthro Class Combat Table*:  For more information about the combat table refer to http://expgame.com/?page_id=252[Chapter 9: Combat Tables].
The initial combat table is calculated here and the level adjustment should be added to the Bonus Proficient (BP).
For simplicity sake we use one combined level bonus for all three weapon types for the referee persona.
If detail must prevail the level bonus can be calculated by hand.
Calculate the Bonus Proficient on Table 11.11: Bonus Proficient for Referee Personae, then add the level bonus from Table 11.11.1: Total Level Bonus by Class.
This will create a quick Bonus Proficient that reflects the referee personas attributes, class and level.

// insert table 322

// insert table 321

// insert table 323

== 6) Referee Personal Equipment

Referee personas carry equipment: they should be supplied with food, survival equipment, and funds.
What the referee persona is carrying as survival equipment will vary depending on terrain.
Referee personas are also assumed to have collected artifacts throughout their travels.
RPs get one artifact for every experience level.
This includes multi-class levels.
Treasure does not count as a roll so RPs can accumulate considerable wealth in addition to their personal collection of artifacts.
Nothing RPs do not get a roll on the Toy Table but they do get additional treasure rolls.
This tends to make RP nothings tremendously wealthy.
If the referee desires impoverished nothings, she can save herself a whole lot of rolling on the treasure tables.
Nothing RPs also receive their complimentary one piece of miscellaneous equipment.

== 7) Referee Persona Qualities

A referee persona is more than a collection of attributes and some artifacts.
Referee personas are an essential part of the story being told in the campaign.
RPs are expected to have all the personality qualities as any other persona.
This challenges the limits of creativity of the referee because she must supply different personalities, appearance  and qualities for the quadrillions of referee personas that will participate in the campaign.
If the referee does not already have a particular appearance, personality, or set of beliefs in mind for her RP, she may find the tables provided useful.
The referee persona qualities are on Table 11.14: RP Qualities Checklist.

// insert table 324

=== 7-1) Appearance

An RPs appearance is divided into two categories: hygiene and dress.
Hygiene represents the personas normal level of personal care.
The hygienic habits of the RP are determined on the RP Hygiene table.
Hygiene is not unwavering like an attribute but is dependent on the scenario at hand.
For example, a habitually immaculate RP that just dived into mud would look like someone who dived into mud;
a habitually filthy spie would not arrive un-groomed at an aristocratic function she was trying to infiltrate.
However, the immaculate RP would clean the mud off herself sooner than the filthy spie and the filthy spie would be the first to get soiled at the aristocratic bash.
The dress of the referee persona does not reflect ANYTHING about the referee persona.

The dress of an RP is even more variable than hygiene.
An RP may have several favorite styles and may even combine them in some random arrangement.
The roll on the table dress indicates which type of dress is worn: shoes, shirts, blouses, pants, hair-dos, etc.
Appearance is mostly directed at anthropomorph RPs, but it can also include aliens or deeply eccentric robots.
It is easy to imagine a filthy canine lumberjack but an immaculate six legged alien dressed in traditional tribal gowns is harder to visualize.
Robots can certainly have hygienic qualities, appearing dirty or well washed, but robot dress may be just too absurd.
For instance, would a 60s style robot have fins and chrome bumpers?

// insert table 325

// insert table 326

=== 7-2) Personality

The referee is expected to play up these personality traits whenever possible.
Extroverted personality traits are NOT irrational: a diplomatic RP will not try to play consul to a crazed combat robot but she may intercede between inter-expedition differences.
Aliens and robots also get a roll on the Extroverted Personality table.
Properly functioning robots would not have  a shred of personality whatsoever, but the free willed robots of EXP are malfunctioning and extroverted personalities or even insanities are possible.

// insert table 327

==== Introverted

The Introverted Personality Sub-table indicates subtle personality traits.
These traits are not too strong and should only be employed by the referee when decisions must be made by the RP.
Such traits are played discreetly by the referee, and may only occasionally be used or noticed.

// insert table 328

==== Insane

The Insane Personalities Table lists irrational actions that are basically pathological.
Insane personality traits can appear in completely unexpected situations, endangering the referee persona and the expedition.
The easiest and most fun referee personas to play are insane ones, but they should be kept relatively rare since EXP is an insane enough game as it is.
Referees are not expected to be psychiatrists and can role-play the mental illness however they interpret them.
If the roll on this table has been directed from the Extroverted Personality Trait Table the insanity will be quite overt.
If the referee is rolling an insane personality off of the Introverted Personality Trait then the insanity will be less obvious.

// insert table 329

=== 7-3) Beliefs

The referee should be prepared to have their preferred personas possess some personal beliefs that may affect their attitude, and how they act while role-playing.
Beliefs are divided into three categories: political, religious, and philosophical.
The player will have from 0-3 (d4-1) separate beliefs, where 0 is none and 3 is three rolls on Table 11.19.
The beliefs are more transient than the RP's personality and they will can conflict directly with the referee persona's personality.
The belief tables are somewhat self-explanatory and are mostly used as the tack that a particular personal will take when arguing ethics with expedition personas.
In the case of aliens these beliefs may be the basis for their entire culture.
For example, an alien that is militaristic and believes religiously in anonymous writings may be a member of a war-like invading family.

// insert table 330

// insert table 331

// insert table 332

// insert table 333

== 8) Combat Ratios

The combat ratio aids the referee in objectively rating how tough a referee persona has been created.
The combat ratio indicates the number of expedition personas that should be needed in combat for a fair fight with that one referee persona.
The higher the combat ratio, the stronger the referee persona.
In other words, if 1 persona vs.
20 referee personas constitutes a fair fight, this is a pretty feeble referee persona.
If the combat ratio indicates 20 personas vs.
1 RP is a fair fight, then it is a tough referee persona.
The combat ratio is just an indicator of the RPs combat strength.
The number of RPs appearing depends on the type of referee persona, its social behaviour, and the setting of the scenario.
If the combat ratio is 1/20, it does not necessarily mean that 20 RPs will automatically show up for every persona.

*Calculating CR*: Add up all the pluses first.
Then multiply all the times.
So a Combat Ratio with Plus 1 and Plus 4 and Plus 3 and Times 1.25 and Times 2.0.
It would be calculated as so: 1 plus 4 plus 3 = 8;
times 3 times 1.25 gives a CR of 30!

// insert table 334

// insert table 335

// insert table 336

// insert table 337

// insert table 338

// insert table 339

// insert table 340

*(8-1) Alien Combat Ratio*: The calculation of the combat ratio is reasonably self-explanatory.
Simply follow the Combat Ratio tables  and adjust the number of personas that are indicated for each of the aliens combat parameters.
Assume that the ratio begins at 1 (1 persona to 1 alien).
The combat ratio can get an alien into a lot of trouble.
Aliens with high combat ratios (requiring many personas for a fair fight) can get a reputation for being violent and combative.
The aggressiveness of the alien is determined by its psychology not its combat ratio.
The corollary is true also and aliens with low combat ratios may be very dangerous if they happen to use weapons or travel in massive numbers.
The combat ratio merely represents the aliens natural ability to hold its own, against average personas.

// insert table 341

*(8-2) Anthropomorph Combat Ratio*: The anthropomorph RP combat ratio is very difficult to calculate in that their use of artifacts can greatly alter their deadliness regardless of what their class is or their attributes are.
Even the most deadly referee persona can be handled easily by the expedition if the referee makes a mistake.
Also the most benign referee persona can become extremely dangerous if she manages to get a hold of a deadly weapon.

When preparing an anthropomorphs combat ratio, the referee should try to take into account all the equipment that the RP has access to.
This means that considerable time may have to be spent in the toy section before the combat ratio can be calculated.
Experienced referees will find that the combat ratio is not needed for estimating equivalent combat conditions but more useful in calculating the RPs experience point value which includes EXPS for encounters other than combative ones.

// insert table 342

*(8-3) Robotic Combat Ratio*: Robots are considerably easier to prepare a combat ratio for than other persona types because they are so structured.
Robots are not nearly as flexible as the biological RPs but they can be very deadly.
The most important point about robots is that they are difficult to destroy but easy to damage.
The following tables can be used as a general guideline as to how challenging a robot is in combat.

// insert table 343


