= Robot RP


If the referee is at a loss for what kind of robot to introduce to the expedition, she can always generate a robot referee persona using this chapter.
Detailed explanation of robot persona peculiarities is described in http://expgame.com/?page_id=239[Chapter 5: Robots].

== Robot RP Creation Checklist

// insert table 285

== 1) Robot RP Type

When the persona&#8217;s attributes and attribute levels have been determined, refer to the _Robot Determination Table_ to see what possibilities are available to the player.
For example, a bot with a PSTR Level III would look down the column for PSTR III and find that three robot types (F, H & J) are allowed.
This is repeated for each of the four attributes.
The robot type that appears most frequently becomes the persona&#8217;s robot type.
In the case of a tie, the player is free to choose.

// insert table 286

== 2)  Robot RP Attributes

Although attributes for robots are comprised of the usual seven (AWE, CHA, CON, DEX, INT, MSTR, PSTR), their generation differs.
There are four prime requisites:  CON, DEX, INT and PSTR.
Each of these is determined initially on a four-sided die and is referred to as the level of the attribute.
A player that rolls a three for PSTR thus has a PSTR level of 3.
The level of the attribute is quite distinct from the true value of the attribute.
The levels are used to determine what robotic type the player will have and must be converted to standard attribute values for play.
Although a robot&#8217;s attributes may change in the course of a campaign, its attribute level cannot change.
So before moving on the persona will be have four attribute levels each between one and four.
For example the robot Persona Sal has a CON level 0f 2, a DEX level of 2, a INT level of 3 and a PSTR level of 4.
These attribute levels are endlessly important for robot personas.
There are no table for adjusting robotic attributes.

// insert table 287

== 3) Robot RP Base Anthro Type

This is the anthro type that the robot referee persona was manufactured for.
Unless otherwise specified, a bot will not harm or allow to come to harm any member of its manufacturing anthro type.
So, if a robot were to have an equine base anthro type, then the persona would not be able to damage any equine anthro that she met.
Nor would the robot allow the equine anthro to accidentally come to harm.
Non-lethal attacks that inflict small amounts of damage can be employed against a robot&#8217;s base anthro type.
A robot will protect a member of its base anthro type from other expedition members also.
This is a major inconvenience that the player must get around when running a robot.
Androids (type A) and combat robots (type C) are exempt from protecting their manufacturing anthro type.
Whenever the referee persona robot wants to damage her manufacturing anthro type she must make a control.
More information about control factor is found in http://expgame.com/?page_id=239[Chapter 5: Robots].

// insert table 288

== 4) Robot RP Armour Rating

All bots have a base AR of 700.
It is important to note that armour rating values are the same for robots and all other personas.
A robot has no immunity from punches, slashes and bangs just because they are composed of special alloys.
A successful to hit roll will do damage to a robot as it would to any other target.
So a to hit roll of 700 or higher would damage a bot with an AR 700 just as it would damage any other persona with an AR of 700.
Robots are different from biological creatures and damage differently.
This aspect of damage is covered in this chapter under robotic damage.

== 5) Robot RP Movement Rate

Robotic movement rates are determined by the robot&#8217;s DEX value.
Robots are twice as fast as those other personas with the same DEX.
Those bots which move faster than 8 h/u, must accelerate the same as vehicles.
Robotic acceleration is one hex per unit per PSTR level.

// insert table 289

== 6) Robot RP Wate Allowance

Bots are affected by encumbrance, though not as much as other referee personas.
As expected, weight allowance is determined by the PSTR and the PSTR level of the bot.
The wate allowance of a robot, measured in kilograms, is determined on the _Robotic Wate Allowance_ table.
A robot with a PSTR level of 3 and a 17 PSTR would have a wate allowance of 75 kgs.
This means that the robot can carry 75 kgs before any movement penalties are incurred.
All penalties of encumbrance apply to robots as they would apply to other personas.
These affects are detailed in http://expgame.com/?page_id=279[Chapter 18: Encumbrance].

// insert table 290

== 7) Robot RP Power Source

All bots operate on electrical power but the cell (or supercell) that converts the source into electrical power will vary.
For further information about Robotic Power Sources refer to http://expgame.com/?page_id=239[Chapter 5: Robots].

// insert table 291

== 8) Sensors

All robots will have built-in audio and video sensors which will allow the robot to "`hear`" and "`see`".
Robots will receive one additional sensor for every 4 points of AWE.
The new sensor type is rolled on the below table.

// insert table 292

== 9) Locomotion

This means of locomotion, in addition to being an important necessity, will add a great deal of personality and individuality to the bot.
The locomotion type is the first indication of the appearance of the robot and it will greatly affect the development of the persona.
To determine the robot's locomotion type, roll once on Table 11-3.9: Robot RP Locomotion.

// insert table 293

// insert table 294

== 10) Offensive Systems

Robotic attacks are rarely built-in devices designed for inflicting damage on targets in combat.
The robots in EXP have a particularly high level of free will and hence are considered quite insane.
The majority of &#8220;weapons &#8220;that robots use are improperly utilized robotic devices.
http://expgame.com/?page_id=239[Chapter 5: Robots], and http://expgame.com/?page_id=306[Chapter 31: Robotic Combat] are both very helpful chapters in regards to robot RP offensive systems.

// insert table 295

// insert table 296

// insert table 299

// insert table 300

// insert table 301

// insert table 298

// insert table 297

// insert table 302

== 11) Defensive Systems

Robot defences are typically malfunctioning peripherals used as a defence in combat, or some kind of industrial hardening to protect the robot to do it&#8217;s prescribed task.
Occasionally robots defences are just that, a defence built to protect a robot from abuse.

// insert table 303

// insert table 304

== 12) Peripheral Systems

Peripherals are attachments that give the robot some additional flexibility in performing its tasks.
These peripherals are non-combative and are used by the robot to survive day to day campaign trials.

// insert table 305

// insert table 306

// insert table 307

== 13) Description

The robot can be shaped like anything the referee wants: fire hydrant, filing cabinet, kitchen appliance, etc.
If you choose to let the dice decide roll on the following two tables below to get a basic robot shape.
The robotic shape has no bearing on any other robotic abilities be they attacks, peripherals or defences.

// insert table 308

// insert table 309

// insert table 310

// insert table 311

== 14) Wate

A robot's wate will be determined by one of two factors: outdoor and indoor.
For robots that are designed to carry out hard work such as heavy lifting or construction, there is the outdoor wate equation.
Other robots that are not designed for such load bearing tasks use the indoor wate equation.

// insert table 312

*Extreme Robot Wates*: There is a small chance that the robot will be minute or humongous.
Roll 1d100 to make a size check.
If the roll is one the robot is a nano bot and has a wate of 1 to 1000 grams.
If the size check is 100 the robot is a mighty machine and has a wate of 5d100 tonnes.
If the robot is either a nano or a mighty the referee will have to make alterations in step (15) Size amongst other things.

== 15) Size

Size gives a rough estimation of the volume occupied by the robot.
The referee rolls dimensions once for each of hite, width and length.
These can be arranged in whatever order works best for the personal.

// insert table 313

== 16) Control Factor

Control Factor (CF) is essentially a measure of the robot referee persona&#8217;s free will &#8212;
the higher the Control Factor, the more control the referee has over her robot referee persona.

*CONTROL FACTOR (CF) = INT plus (INT level times EXPS LEVEL)*

== 17) Hit Points (HPS)

Robot referee personas simply generate HPS from Table 11-3.29: Robot RP Hit Points.

// insert table 314

== 18) Age

A robot referee persona&#8217;s age is related to it&#8217;s time since fabrication.
The longer since fabrication the lower its HPS.

// insert table 315

== 19) Tech Level

Typically the robot referee persona will have the tech level of the milieu in which it was created.
If the referee wishes a tech level can roll a tech level in  http://expgame.com/?page_id=359[Chapter 56 Tech Level].

== 20) Return to Chapter 11
