= Alien RP

When creating an alien referee persona encounter the referee must keep in mind that she is likely creating an entire alien species.
Aliens don't merely exist unto themselves as a singular entity but are components of a species as are the anthropomorph types.
Alien species are generated by the referee either to supply background and interest to a campaign or to provide the primary focus and/or conflict around which to design a campaign.
Aliens are referred to as species because they can be unsophisticated animals of an unexplored world or highly developed conquering alien hordes.

There is always the possibility that an alien is the singular creation of a biological research laboratory gone civilized or some other such cloning cliché.
Whether the alien is singular in existence or a member of a species, the referee should have it properly prepared.

== 2-1) Alien Referee Personas

When creating an alien referee persona encounter the referee must keep in mind that she is likely creating an entire alien species.
Aliens don't merely exist unto themselves as a singular entity but are components of a species as are the humanoid families.
Alien species are generated by the referee either to supply background and interest to a campaign or to provide the primary focus and/or conflict around which to design a campaign.
The reason the aliens are referred to as species and not families is because they can be unsophisticated animals of an unexplored world or highly developed conquering alien hordes.




== Generating the Alien RP

Persona aliens are generated in http://expgame.com/?page_id=241[Chapter 6: Aliens].
In that chapter, the referee should record all the pertinent information about the alien created.
For RP aliens, details like whether they are tool users or educated are very important.
Referee persona qualities (8) only apply to an alien RP if it expresses a civilized or tool-using nature.
The communication method used between the alien and the expedition is determined by the referee.

Refs should create their own aliens.
Aliens custom-designed by the referee are certain to fit into the campaign or terrain that they were designated for.
Creating original aliens eliminates the problem of finding that perfect creature necessary for the moment.
The alien generation system creates basic creatures that do not have a place in any existing food chain, pre-designed environment, or social system.
All these important points that make an alien species more realistic are left to the ref to design around the generated alien.
Many referees will discover that rolling up aliens will almost certainly jog their imaginations.

// insert table 257

== 1) Alien RP Attributes

For convenience we have included Table 6.2: Alien Attributes here.
More detailed discussion about alien attributes can be found in Chapter 6: Aliens.

// insert table 261

*Attribute Adjustments*: Not every referee wants their aliens to have the attribute ranges listed in the alien persona chapter.
Often a referee will want a small alien, a dumb alien, a slow alien, or even a dumb, slow, small alien (prey).
For special attributes for special aliens refer to Table 11.6: Descriptive Attribute Adjustments.
The corresponding alien adjectives such as tough, strong, or smart, are not included and, when desired regular alien attribute generation should suffice.

// insert table 256

// insert table 258

== 2) Alien RP Size

For convenience we have included Table 6.3: Alien Size here.
More detailed discussion about alien size can be found in Chapter 6: Aliens.

// insert table 265

*Minute Alien Size*: Any alien that is Tiny has a chance to be Minute instead.
There is a 1 in 6 chance that a tiny alien being minute.
Minute aliens are very small and cannot be reasonably run by a player but can be introduced by a referee.
Minute aliens have a WATE of  1 to 1000 grams (1d1000).
No Minute alien will have a WATE greater than a kilogram.
Minute aliens have half the HPS that were rolled for the corresponding tiny alien and PSTR is reduced to one quarter that of the tiny alien's.
All other attributes and measurements remain the same.

*Humongous Alien Size*: Any alien that is Gigantic has a chance to be Humongous instead.
There is a 1 in 6 chance that a gigantic alien is humongous.
Humongous aliens have a WATE of 6 to 300 tons (1d50 times 6).
Such aliens are impossible for a player to run but can be introduced by the referee.
None of the humongous alien's attributes are different from those of the corresponding gigantic alien.

== 3) Alien RP Hit Points

For convenience we have included Table 6.4: Alien Hit Points here.
More detailed discussion about alien hit points can be found in Chapter 6: Aliens.

// insert table 262

// insert table 260

== 4) Alien RP Number of Attacks

For convenience we have included Table 6.5: Alien Number of Attacks here.
More detailed discussion about alien number of attacks can be found in Chapter 6: Aliens.

// insert table 263

== (5) Alien RP Damage per Attack

For convenience we have included Table 6.6: Alien Damage, and Table 6.7: Alien Attack Type here.
More detailed discussion about alien damage and attack type can be found in Chapter 6: Aliens.

// insert table 264

// insert table 266

== 6) Alien RP Armour Rating

*ALIEN ARMOUR RATING (AR) = 500 + 3d100*

== 7) Alien RP Description

For convenience we have included Table 6.10: Alien Body Parts here.
It is important to keep track of each body parts terrain type to determine the alien RPs movement rate.
The special adornment tables are not included here, but can be found in Chapter 6: Aliens.

// insert table 90

// insert table 92

// insert table 93

// insert table 94

== 8) Alien RP Movement Rate

Aliens can move up to one hex/unit per point of DEX.
Denizens may hop, slither, scuttle, slime or gallop along with whatever form of locomotion is listed as legs in their Description.
The type of creature part that is used to describe the alien's locomotion will move at the designated movement rate regardless of what the description is.
For instance, an alien that looks like a snail could move as fast as an alien that looks like a leopard.

// insert table 268

== 9) Alien RP Mutations

Aliens have a chance of getting mutations;
however, they are not generally considered mutations but natural abilities that function the same as mutations.
An alien's mutations apply to the entire species and are more like naturally evolved defensive or offensive abilities.
Therefore, alien mutations are not considered mutations in the usual sense -- as if they were abnormalities or variations from the norm.
Occasionally mutations may force changes in the creature's physical description as determined in the Description section.
If a player running an alien wishes to mutate, she cannot adjust her chance of mutation like humanoid personas can.

*Mental Mutations*: The chance of an alien having a mental mutation is equal to the alien's MSTR attribute.
An alien with a 15 MSTR would have a 15% chance of having a mental mutation per mutation check.
The player stops checking for mental mutations as soon as a roll is failed.
So if the player were to roll 11 and 16, her alien would have one mental mutation.
These mutations are described in Chapter 58: Mental Mutations.

*Physical Mutations*: The chance of a creature having evolved a physical mutation is equal to the creature's CON.
For example, a CON of 10 has a 10% chance of having a mutation.
Once the alien has a mutation, there is an equal chance of having another.
The alien can keep getting additional mutation-like abilities if it keeps making its percent chance.
If the player with the alien that has a 10 CON were to roll 3, 9, and 41, her alien would have two physical mutations.
The mutations are described in http://expgame.com/?page_id=366[Chapter 59: Physical Mutations].

== 10) Alien RP Age

All personas except for robots have a projected life-span.
The idea of an alien only living for a certain amount of time is a reflection of its biological nature.
The life spans of aliens can be very alien indeed when compared to those of humanoid personas.
Once the alien category has been determined on Table 11-1.14: Alien RP Age Category, the possible age in years needs to be determined.
First generate the total lifespan, and then the possible age in years of the alien can be calculated.
More detailed information about alien age can be found in Chapter 6: Aliens

// insert table 269

// insert table 270

// insert table 272

*Extremely Short Life Spans*: If the alien RP's life span in years is less than 10 years there is a 1 in 6 chance that the aliens lifespan will be measured in months or days or hours.
Really short life spans should have an impact on how the alien's function in their biology and how they live their existence.

// insert table 271

*Extremely Long Life Spans*: If the alien RP's life span is more than 1000 years there is a 1 in 6 chance that the alien will have a maximum life span of 1-1000 million years (1d1000 times 1000000).
Yes of course this changes everything about how the alien behaves, it's culture, and it's history.

== 11) Alien RP Biology

All of the alien information up to this date is considered biology but the biology covered here represents superfluous information that will only subtly affect the nature of the alien;
whereas the previous biology represented factors that affect the attributes of the alien personas like movement, combat abilities, size, etc.

Biology gives a very brief description of where the alien fits into its ecological system.
The biome describes the terrain that the alien is accustomed to living in.
The last five tables provide some extra insight into what makes an alien tick.
They may seem trivial at first but can be very important under certain circumstances.

// insert table 99

// insert table 100

// insert table 101

// insert table 102

// insert table 103

// insert table 104

// insert table 105

// insert table 106

== 12) Alien RP Society

Alien society is something for the referee to carefully consider and prepare for her campaign.
Alien societies can even be the basis for an entire campaign.
The differences in values, architecture, and social organization alone amongst alien cultures would be beyond the duration of a life time of study.

Most of the persona aliens will be rogues or outcasts that have rejected their alien culture thus allowing them to form their own cultural niche.
The referee cannot possibly prepare a detailed alien society each time a player generates an alien persona.
For the most part, alien personas will not be members of galactic societies or developed countries.
If some idea of the alien's society is necessary but total preparation is not, the referee should turn to Chapter 11: Referee Personas and determine the society's religious, political, and philosophical beliefs.

// insert table 273


*Alien Combat Table*: For more information about the alien combat table refer to http://expgame.com/?page_id=252[Chapter 9: Combat Tables].
This combat table is for natural attacks of the alien RP.
If the alien is advancing in a class she will use the Anthro Class RP combat table.
There is no such thing as a Bonus Non-Proficient (BNP) for natural attacks.
Aliens do  not have a BNP.
Alien PSTR is included in their damage attack, and they do not have a Damage Adjustor (DA) either.
The initial combat table can be calculated here, and it can be important to add the level bonus to the Bonus Proficient (BP).
Unfortunately the level bonus must be calculated by hand if it applies to the alien.
So for example an alien RP with a PSTR of 20 would increase her BP for Type A natural attack  by 20 at level 2, by 13 at level 3, and by 10 at level 4.



== 8) Combat Ratios

The combat ratio aids the referee in objectively rating how tough a referee persona has been created.
The combat ratio indicates the number of expedition personas that should be needed in combat for a fair fight with that one referee persona.
The higher the combat ratio, the stronger the referee persona.
In other words, if 1 persona vs.
20 referee personas constitutes a fair fight, this is a pretty feeble referee persona.
If the combat ratio indicates 20 personas vs.
1 RP is a fair fight, then it is a tough referee persona.
The combat ratio is just an indicator of the RPs combat strength.
The number of RPs appearing depends on the type of referee persona, its social behaviour, and the setting of the scenario.
If the combat ratio is 1/20, it does not necessarily mean that 20 RPs will automatically show up for every persona.

*Calculating CR*: Add up all the pluses first.
Then multiply all the times.
So a Combat Ratio with Plus 1 and Plus 4 and Plus 3 and Times 1.25 and Times 2.0.
It would be calculated as so: 1 plus 4 plus 3 = 8;
times 3 times 1.25 gives a CR of 30!

// insert table 334

// insert table 335

// insert table 336

// insert table 337

// insert table 338

// insert table 339

// insert table 340



*(8-1) Alien Combat Ratio*: The calculation of the combat ratio is reasonably self-explanatory.
Simply follow the Combat Ratio tables  and adjust the number of personas that are indicated for each of the aliens combat parameters.
Assume that the ratio begins at 1 (1 persona to 1 alien).
The combat ratio can get an alien into a lot of trouble.
Aliens with high combat ratios (requiring many personas for a fair fight) can get a reputation for being violent and combative.
The aggressiveness of the alien is determined by its psychology not its combat ratio.
The corollary is true also and aliens with low combat ratios may be very dangerous if they happen to use weapons or travel in massive numbers.
The combat ratio merely represents the aliens natural ability to hold its own, against average personas.

// insert table 341


== 9) Referee Persona Name

Often the most important part of a referee persona is its name.
The description of a humanoid may be glossed over and that of an aliens forgotten completely but the name will always be remembered.
The players will recall an RPs name before they will remember her personality, dress, or special abilities.
There is no question that a referee personas name is much more important to the campaign than that of an expedition persona.
Often an RPs name will have some significance, like a veterinarian named Ivy Blodgett or a melancholic nothing named Sue Siedal.

Robots are more difficult to name because there is some unwritten rule that they must have letters and numbers in their names, like: QT, oicur12, unit 42, or SNOO-KM series.
Remember the more insane the robot, the more free willed it is and the more likely that it will have named itself.
Additional names that the referee may be required to produce for an RP robot are manufacturers name, model line, and unit name.

Alien families are fun to name.
The referee will often be naming an entire family as well as the specific species member that she has created.
A helpful hint in naming alien families is to avoid personification.
No self-respecting space-faring family would call itself the Obese Ones,
or the Furry Ones.
If such alien properties are important to an alien family (which they might well be), translations can mean anything the referee likes and the Vojing Dur
may translate into Obese Ones
but in that aliens tongue (if they have tongues) human
might translate into scrawny geeks.
Always keep in mind that these creatures are alien and alien sounding words that reflect the alien are the most useful and fun.

== Combat Ratio

=== Alien Specific

include::ROOT:partial$CH11_Table_RP_CR_Alien.adoc[]

// general CR adjustments list of tables.
// heading is === for each table
include::ROOT:partial$CH11_RP_CR_General.adoc[]