= Alien RP

When creating an alien referee persona encounter the referee must keep in mind that she is likely creating an entire alien species.
Aliens don't merely exist unto themselves as a singular entity but are components of a species as are the anthropomorph types.
Alien species are generated by the referee either to supply background and interest to a campaign or to provide the primary focus and/or conflict around which to design a campaign.
Aliens are referred to as species because they can be unsophisticated animals of an unexplored world or highly developed conquering alien hordes.

.*Alien RP Checklist*
* *RP ROLL PLAYING (Data)*
. Relevance
. Persona Record Sheet
. Attributes
. Size
. Hit Points
. Attack Frequency
. Attack Damage
. Armour Rating
. Wate Allowance
. Description
. Movement Rate
. Mutations
. Age
. Society
. EXPS Level
. Vocation
. Equipment
.. Mundane
.. Artifact
. Combat Table
. Combat Ratio
* *RP ROLE PLAYING (Fun)*
. Biology
. Story
.. Origin
.. Presence
.. Goal
.. Personality
. Appearance
.. Clothing
.. Hygiene
.. Gender
. Beliefs
.. Religious
.. Political
.. Philosophical
. Modifications
.. attributes
.. size
.. age
. Name
. Have Fun!

== Role Playing Aliens
Ain't that fun.

== Generating the Alien RP
In that chapter, the referee should record all the pertinent information about the alien created.
For RP aliens, details like whether they are tool users or educated are very important.
Referee persona qualities (8) only apply to an alien RP if it expresses a civilized or tool-using nature.
The communication method used between the alien and the expedition is determined by the referee.

Refs should create their own aliens.
Aliens custom-designed by the referee are certain to fit into the campaign or terrain that they were designated for.
Creating original aliens eliminates the problem of finding that perfect creature necessary for the moment.
The alien generation system creates basic creatures that do not have a place in any existing food chain, pre-designed environment, or social system.
All these important points that make an alien species more realistic are left to the ref to design around the generated alien.
Many referees will discover that rolling up aliens will almost certainly jog their imaginations.

When creating an alien referee persona encounter the referee must keep in mind that she is likely creating an entire alien species.
Aliens don't merely exist unto themselves as a singular entity but are components of a species as are the humanoid families.
Alien species are generated by the referee either to supply background and interest to a campaign or to provide the primary focus and/or conflict around which to design a campaign.
The reason the aliens are referred to as species and not families is because they can be unsophisticated animals of an unexplored world or highly developed conquering alien hordes.

There is always the possibility that an alien is the singular creation of a biological research laboratory gone civilized or some other such cloning cliché.
Whether the alien is singular in existence or a member of a species, the referee should have it properly prepared.

== Alien RP Relevance
Many referee's will prepare extensive details on every persona they create. 
In the days when everything was generated by dice and recorded on paper it was impossible.
Today with computerized generated personas it is possible.
It is just not always necessary.

The referee persona relevance is decided by the referee.
The persona relevance is not set in stone.
A referee persona's relevance can increase if for some reason they get entangled in the expedition.

=== Cannon Fodder
Cannon fodder refers to background personas that need little or no information. 
Cannon fodder not have any substantial outcome for the campaign.
A cannon fodder persona may only have HPS and a blurry description.

[quote]
____
Cannon Fodder is a despicable term from warfare.
Cannon Fodder were pure strain humans used to charge cannons.
____

Cannon fodder hold no useful information.
Cannon fodder offer no measurable opposition to the persona's goals.
Cannon fodder have no nutritional value, monetary value or useful parts.

For aliens these are flora and fauna in the underbrush and trees.

=== Canon Fodder
Canon fodder can change the story of the campaign.
Canon fodder could injure or kill a player persona.
Canon fodder may make a decision that alters the well being of the expedition.

Canon fodder require a bit more information than cannon fodder.
Canon fodder may need several attributes, campaign info, HPS, or combat tables.
// most aliens are canon fodder 


For aliens these are flora and fauna that can attack and injure the expedition.

=== Canon Referee Persona
A canon referee persona is a complete referee persona.
A complete referee persona used to represent an enormous amount of preparation and work.
Much of this work has been replaced by puters. 
There is a special level of irritation when a full referee persona is violently deleted by paranoid players. 
// rare for aliens

Canon referee personas are integral participants in the campaign story.
These personas can be powerful recurring enemies, or comrades in arms.
Canon referee personas have personality, history, goals, morals and more. 
Most of the time referees create the details of their most important referee personas.
These personas are essential in moving the story forward and making the game more fun.

== Alien RP Record Sheet
The referee persona record sheet is just another persona record sheet.
There are few bonus elements that referee must keep track of.
Most player personas do not have elements like personality, politics or religion.
The referee persona record sheet can also be used to keep track of expedition interactions.
// ID number
// share them worldwide

== Alien RP Attributes
Attribute are rolled here.
Modifications are done later

include::ROOT:partial$CH06_Table_Alien_Attributes.adoc[]

== Alien RP Size
The bigger the bigger.

include::ROOT:partial$CH06_Table_Alien_Size.adoc[]

=== Minute Alien Size
Any alien that is Tiny has a chance to be Minute instead.
There is a 1 in 6 chance that a tiny alien being minute.
Minute aliens are very small and cannot be reasonably run by a player but can be introduced by a referee.
Minute aliens have a WATE of  1 to 1000 grams (1d1000).
No Minute alien will have a WATE greater than a kilogram.
Minute aliens have half the HPS that were rolled for the corresponding tiny alien and PSTR is reduced to one quarter that of the tiny alien's.
All other attributes and measurements remain the same.

=== Humongous Alien Size
Any alien that is Gigantic has a chance to be Humongous instead.
There is a 1 in 6 chance that a gigantic alien is humongous.
Humongous aliens have a WATE of 6 to 300 tons (1d50 times 6).
Such aliens are impossible for a player to run but can be introduced by the referee.
None of the humongous alien's attributes are different from those of the corresponding gigantic alien.

== Alien RP Hit Points
More bigger more hit points.

include::ROOT:partial$CH06_Table_Alien_Hit_Points_HPS.adoc[]

// check why 2 tables?

== Alien RP Number of Attacks
The more attacks the more dangerous.

include::ROOT:partial$include::ROOT:partial$CH06_Table_Number_of_Alien_Attacks.adoc[][]

== Alien RP Damage per Attack
More Bigger More Damage

include::ROOT:partial$include::ROOT:partial$CH06_Table_Alien_Damage_Per_Attack.adoc[][]

include::ROOT:partial$include::ROOT:partial$CH06_Table_Alien_Attack_Type.adoc[][]

== Alien RP Armour Rating

include::CH06_Aliens_7_AR.adoc[tag=Alien_AR]

== Alien RP Wate Allowance

include::ROOT:partial$CH03_Table_Physical_Strength_and_Wate_Allowance_(kg).adoc[]

== Alien RP Description
Record the movement letters (l,a,w,s)

=== Roll  Parts
Four rolls for four parts.
Head, Torso, Arms, and Legs.

include::ROOT:partial$CH06_Table_Alien_Body_Parts.adoc[]

=== Coat and Colour
Coat is uniform over whole alien
Roll colour and affects 

include::ROOT:partial$add_colour_to_your_world.adoc[]

=== Adornments
These are optional accents to the alien's appearance.
Adornments are entirely descriptive.
Adornments do not detract from or add any abilities to the alien. 

==== Head 
include::ROOT:partial$CH06_Table_Adornment_Head.adoc[]

==== Torso
include::ROOT:partial$CH06_Table_Adornment_Torso.adoc[]

==== Arms
include::ROOT:partial$CH06_Table_Alien_Adornments_Arms.adoc[]


== Alien RP Movement Rate
Denizens may hop, slither, scuttle, slime or gallop along with whatever form of locomotion is listed as legs in their Description.

=== Base Movement
include::CH06_Aliens_9_Move.adoc[tag=Alien_Move]

The type of creature part that is used to describe the alien's locomotion will move at the designated movement rate regardless of what the description is.
For instance, an alien that looks like a snail could move as fast as an alien that looks like a leopard.

=== Quartering Movement

include::ROOT:partial$CH06_Table_Calculating_Alien_Movement.adoc[]

== Alien RP Mutations
Aliens have a chance of getting mutations;
However, they are not generally considered mutations but natural abilities that function the same as mutations.
An alien's mutations apply to the entire family and are more like naturally evolved defensive or offensive abilities.
Therefore, alien mutations are not considered mutations in the usual sense -- as if they were abnormalities or variations from the norm.
Occasionally mutations may force changes in the creature's physical description as determined in the Description section.
If a player running an alien wishes to mutate, she cannot adjust her chance of mutation like humanoid personas can.

// these are not mutations but abilities
// no defects
== Mental Abilities
The chance of an alien having a mental mutation is equal to the alien's MSTR attribute.
An alien with a 15 MSTR would have a 15% chance of having a mental mutation per mutation check.
The player stops checking for mental mutations as soon as a roll is failed.
So if the player were to roll 11 and 16, her alien would have one mental mutation.
These mutations are described in Chapter 58: Mental Mutations.

== Physical Abilities
The chance of a creature having evolved a physical mutation is equal to the creature's CON.
For example, a CON of 10 has a 10% chance of having a mutation.
Once the alien has a mutation, there is an equal chance of having another.
The alien can keep getting additional mutation-like abilities if it keeps making its percent chance.
If the player with the alien that has a 10 CON were to roll 3, 9, and 41, her alien would have two physical mutations.

Aliens have a chance of getting mutations;
however, they are not generally considered mutations but natural abilities that function the same as mutations.
An alien's mutations apply to the entire species and are more like naturally evolved defensive or offensive abilities.
Therefore, alien mutations are not considered mutations in the usual sense -- as if they were abnormalities or variations from the norm.
Occasionally mutations may force changes in the creature's physical description as determined in the Description section.
If a player running an alien wishes to mutate, she cannot adjust her chance of mutation like humanoid personas can.

== Alien RP Age
All personas except for robots have a projected life-span.
The idea of an alien only living for a certain amount of time is a reflection of its biological nature.
The life spans of aliens can be very alien indeed when compared to those of humanoid personas.
First generate the total lifespan, and then the possible age in years of the alien can be calculated.

include::ROOT:partial$CH06_Table_Alien_Lifespan.adoc[]

include::ROOT:partial$CH11_Table_Alien_RP_Life_Stage.adoc[]

include::ROOT:partial$CH06_Table_Alien_Life_Stages.adoc[]

=== Extremely Short Life Spans 
If the alien RP's life span in years is less than 10 years there is a 1 in 6 chance that the aliens lifespan will be measured in months or days or hours.
Really short life spans should have an impact on how the alien's function in their biology and how they live their existence.

// insert table 271

=== Extremely Long Life Spans
If the alien RP's life span is more than 1000 years there is a 1 in 6 chance that the alien will have a maximum life span of 1-1000 million years (1d1000 times 1000000).
Yes of course this changes everything about how the alien behaves, it's culture, and it's history.


== Alien RP Society

Alien society is something for the referee to carefully consider and prepare for her campaign.
Alien societies can even be the basis for an entire campaign.
The differences in values, architecture, and social organization alone amongst alien cultures would be beyond the duration of a life time of study.

Most of the persona aliens will be rogues or outcasts that have rejected their alien culture thus allowing them to form their own cultural niche.
The referee cannot possibly prepare a detailed alien society each time a player generates an alien persona.
For the most part, alien personas will not be members of galactic societies or developed countries.
If some idea of the alien's society is necessary but total preparation is not, the referee should turn to Chapter 11: Referee Personas and determine the society's religious, political, and philosophical beliefs.

.Societal Compositions
* Language 36%
* Culture 11%
* Education 4%
* Vocation 1%

.Tool Usage Frequencies
* None 52%
* Simple 38%
* Tech 8%
* Comp 1% 
* Creator 0.1%

== Alien RP Combat Table
This combat table is for natural attacks of the alien RP.
If the alien is advancing in a class she will use the Anthro Class RP combat table.
There is no such thing as a Bonus 

include::ROOT:partial$CH11_Table_Alien_Referee_Persona_Combat_Table_(CT).adoc[]



Non-Proficient (BNP) for natural attacks.
Aliens do  not have a BNP.
Alien PSTR is included in their damage attack, and they do not have a Damage Adjustor (DA) either.
The initial combat table can be calculated here, and it can be important to add the level bonus to the Bonus Proficient (BP).
Unfortunately the level bonus must be calculated by hand if it applies to the alien.
So for example an alien RP with a PSTR of 20 would increase her BP for Type A natural attack  by 20 at level 2, by 13 at level 3, and by 10 at level 4.

== Alien RP Combat Ratio
The calculation of the combat ratio is reasonably self-explanatory.
Simply follow the Combat Ratio tables  and adjust the number of personas that are indicated for each of the aliens combat parameters.
Assume that the ratio begins at 1 (1 persona to 1 alien).
The combat ratio can get an alien into a lot of trouble.
Aliens with high combat ratios (requiring many personas for a fair fight) can get a reputation for being violent and combative.
The aggressiveness of the alien is determined by its psychology not its combat ratio.
The corollary is true also and aliens with low combat ratios may be very dangerous if they happen to use weapons or travel in massive numbers.
The combat ratio merely represents the aliens natural ability to hold its own, against average personas.

The combat ratio aids the referee in objectively rating how tough a referee persona has been created.
The combat ratio indicates the number of expedition personas that should be needed in combat for a fair fight with that one referee persona.
The higher the combat ratio, the stronger the referee persona.
In other words, if 1 persona vs.
20 referee personas constitutes a fair fight, this is a pretty feeble referee persona.
If the combat ratio indicates 20 personas vs.
1 RP is a fair fight, then it is a tough referee persona.
The combat ratio is just an indicator of the RPs combat strength.
The number of RPs appearing depends on the type of referee persona, its social behaviour, and the setting of the scenario.
If the combat ratio is 1/20, it does not necessarily mean that 20 RPs will automatically show up for every persona.

*Calculating CR*: Add up all the pluses first.
Then multiply all the times.
So a Combat Ratio with Plus 1 and Plus 4 and Plus 3 and Times 1.25 and Times 2.0.
It would be calculated as so: 1 plus 4 plus 3 = 8;
times 3 times 1.25 gives a CR of 30!

=== Alien Specific

include::ROOT:partial$CH11_Table_RP_CR_Alien.adoc[]

// general CR adjustments list of tables.
// heading is === for each table
include::ROOT:partial$CH11_RP_CR_General.adoc[]


== Alien RP Biology
All of the alien information up to this date is considered biology but the biology covered here represents superfluous information that will only subtly affect the nature of the alien;
whereas the previous biology represented factors that affect the attributes of the alien personas like movement, combat abilities, size, etc.

Biology gives a very brief description of where the alien fits into its ecological system.
The biome describes the terrain that the alien is accustomed to living in.
The last five tables provide some extra insight into what makes an alien tick.
They may seem trivial at first but can be very important under certain circumstances.

.*Alien Biology Checklist*
. <<_biome,Biome>>
.. <<_biome_modification,Biome Modification>>
. <<_energy_source,Energy Source>>
.. <<_procurement,Procurement>>
. <<_reproduction,Reproduction>>
. <<_dwelling,Dwelling>>
. <<_aroma,Aroma>>

=== Biome 

include::ROOT:partial$CH06_Table_Alien_Biome.adoc[]

==== Biome Modification

include::ROOT:partial$CH06_Table_Alien_Biome_Characteristic.adoc[]

=== Energy Source

include::ROOT:partial$CH06_Table_Alien_Energy_Source.adoc[]

==== Energy Procurement

include::ROOT:partial$CH06_Table_Alien_Energy_Procurement_Strategy.adoc[]

=== Reproduction

include::ROOT:partial$CH06_Table_Alien_Reproductive_Method.adoc[]

=== Dwelling

include::ROOT:partial$CH06_Table_Alien_Habitation_Type.adoc[]

=== Grouping

include::ROOT:partial$CH06_Table_Alien_Group_Size.adoc[]



== Alien RP Story
. Story
.. Origin
.. Presence
.. Goal

== Alien RP Appearance
.. Personality
. Appearance
.. Clothing
.. Hygiene
.. Gender

include::ROOT:partial$CH06_Table_Alien_Aroma.adoc[]

== Alien RP Beliefs
. Beliefs
.. Religious
.. Political
.. Philosophical



== Alien RP Modifications
Not every referee wants their aliens to have the attribute ranges listed in the alien persona chapter.
Often a referee will want a small alien, a dumb alien, a slow alien, or even a dumb, slow, small alien (prey).
For special attributes for special aliens refer to Table 11.6: Descriptive Attribute Adjustments.
The corresponding alien adjectives such as tough, strong, or smart, are not included and, when desired regular alien attribute generation should suffice.

include::ROOT:partial$CH11_Table_Anthro_RP_Modifiers.adoc[]

== Alien RP Name
Often the most important part of a referee persona is its name.
The description of a humanoid may be glossed over and that of an aliens forgotten completely but the name will always be remembered.
The players will recall an RPs name before they will remember her personality, dress, or special abilities.
There is no question that a referee personas name is much more important to the campaign than that of an expedition persona.
Often an RPs name will have some significance, like a veterinarian named Ivy Blodgett or a melancholic nothing named Sue Siedal.

Robots are more difficult to name because there is some unwritten rule that they must have letters and numbers in their names, like: QT, oicur12, unit 42, or SNOO-KM series.
Remember the more insane the robot, the more free willed it is and the more likely that it will have named itself.
Additional names that the referee may be required to produce for an RP robot are manufacturers name, model line, and unit name.

Alien families are fun to name.
The referee will often be naming an entire family as well as the specific species member that she has created.
A helpful hint in naming alien families is to avoid personification.
No self-respecting space-faring family would call itself the Obese Ones,
or the Furry Ones.
If such alien properties are important to an alien family (which they might well be), translations can mean anything the referee likes and the Vojing Dur
may translate into Obese Ones
but in that aliens tongue (if they have tongues) human
might translate into scrawny geeks.
Always keep in mind that these creatures are alien and alien sounding words that reflect the alien are the most useful and fun.

