= Referee Personas

A Referee Persona (RP) is any persona that is *not* run by a player.
The persona could be from any of the families: anthro, robot, or alien.
If the persona is not controlled by a player it must be brought to life by the referee.
These special personas are called referee personas. 

== Referee Role-Playing
It is the responsibility of the ref to role-play referee personas to the best of her ability.
Intelligent aliens must seem and act intelligently.
Nomads will prefer their biome over any other luxury.
Anti-knites must not stray from their righteous path of entropy.
Robots lack facial expressions and body language.
In short the referee must be able to make even the temporary personas as real as possible.

=== Spread the Fun
Collaborative role playing groups will often have players represent referee personas.
This works well for personas that friendly and neutral to the expedition.
A player should not run a Heavy Combot referee persona that is attacking the expedition.
A player should not run an spie feline that knows about crucial campaign information. 
One of the players may have fun running a shop keeper that does not haggle her prices.

== Referee Persona Relevance
Many referee's will prepare extensive details on every persona they create. 
In the days when everything was generated by dice and recorded on paper it was impossible.
Today with computerized generated personas it is possible.
It is just not always necessary.

The referee persona relevance is decided by the referee.
The persona relevance is not set in stone.
A referee persona's relevance can increase if for some reason they get entangled in the expedition.

=== Cannon Fodder
Cannon fodder refers to background personas that need little or no information. 
Cannon fodder not have any substantial outcome for the campaign.
A cannon fodder persona may only have HPS and a blurry description.

[quote]
____
Cannon Fodder is a despicable term from warfare.
Cannon Fodder were pure strain humans used to charge cannons.
____

Cannon fodder hold no useful information.
Cannon fodder offer no measurable opposition to the persona's goals.
Cannon fodder have no nutritional value, monetary value or useful parts.

For anthros these are sidewalk civilians crowding city streets.
For aliens these are flora and fauna in the underbrush and trees.
For robots these are delivery drones navigating for digital overlords. 

=== Canon Fodder
Canon fodder can change the story of the campaign.
Canon fodder could injure or kill a player persona.
Canon fodder may make a decision that alters the well being of the expedition.

Canon fodder require a bit more information than cannon fodder.
Canon fodder may need several attributes, campaign info, HPS, or combat tables.

For anthros this could be a merchant who is going to steal from the expedition.
For aliens these are flora and fauna that can attack and injure the expedition.
For robots these are bots that act as low level sentries, spying or tracking the expedition. 

=== Canon Referee Persona
A canon referee persona is a complete referee persona.
A complete referee persona used to represent an enormous amount of preparation and work.
Much of this work has been replaced by puters. 
There is a special level of irritation when a full referee persona is violently deleted by paranoid players. 

Canon referee personas are integral participants in the campaign story.
These personas can be powerful recurring enemies, or comrades in arms.
Canon referee personas have personality, history, goals, morals and more. 
Most of the time referees create the details of their most important referee personas.
These personas are essential in moving the story forward and making the game more fun.

== Referee Persona Generation
It is rare that a referee persona's generation will be completely random.
There almost always is a reason for generating referee personas.
The expedition need's an ursidae mercenary for protection in the wilds.
The wilds need's to be populated with ferocious alien creatures.
The radioactive ruin may be ruled by an explorations bot lethally collecting specimen samples.

=== Descriptors
While there may be clear roles for the personas created these sections help fill in the gaps.
Each family type has descriptors that the referee can use to massage the referee persona.
For example referees can choose to have a tall smart feline.
There are hite, attribute and anthro type modifiers in each family section.

=== Pure Random
For the referee that is using the referee persona section for a purely random encounter.
The referee starts here with a roll on the Referee Persona Family Table.
Once the family type is decided take a look at the checklist and get rolling the dice. 

include::ROOT:partial$CH11_Table_RP_Family_Type.adoc[]

=== Referee Persona Checklist
Make sure you get every element of your randomly created referee persona.
A referee persona includes all the elements of player persona plus a few more.
A referee persona is expected to have experience levels and a equipment.
This equipment could include complex artifacts.
Full referee personas will have personalities, beliefs, goals and history.
The general checklist is the broad strokes a referee persona. 
Each family has it's own detailed referee persona checklist.

.General Referee Persona Checklist
. Create a Persona Record Sheet
.. Record creation Date
.. Record unique RP ID
. Determine Family
.. Anthro
.. Alien
.. Robot
.. AI
. Determine Type
. Determine Relevance
.. Cannon Fodder
.. Canon Fodder
.. Canon Persona
. Descriptors
.. attributes
.. size
.. Appearance
.. age
.. gender
. Convictions
.. Personality
.. Beliefs
. Attributes
. Vocation
. Mutation
. EXPS Level
. Equipment
.. Mundane
.. Artifact
. Armour Rating
. Movement Rate
. Combat Table
. Combat Ratio
. Story
.. Origin
.. Presence
.. Goal

. Name
. Have Fun!