= Chapter 57: Multi-Equipment
:author: expgame
:date: 2010-08-08 04:06:39 -0400
:guid: http://expgame.com/?page_id=362
:id: 362
:page-layout: page

Multi-equipment is the shortened form of multiple #equipment.
Multiple equipment is not just several pieces of equipment, but several different artifacts combined into one device.
Combinations such as medi-kit, drug dispensers, or metal detector earth cancellor are very useful examples.
In EXP+++<b>+++, +++</b>+++being #the testament to technological chaos that it is, the combinations of equipments are determined randomly.
The randomness is not without humor though: powered-armour-underwear;
chair-guns;
hat-bombs;
or fusion pistol-medi-kits.#

== Creating# 

Multi-equipment can be generated simply by the ref deciding that something different is needed, and then continuing to roll several times on the #http://expgame.com/?page_id=326#1-basic-toy-type[[.s6\]#Toy #[.s7\]#Type T#able].
Multi-equipment may also be needed when the equipment in this book does not exactly meet the requirements of some toy the ref has in mind, but a combination of several toys would.#

The &#8220;official&#8221;
system for generating multi-toys employs a deci-die roll against the toy's TL (tech level).
If a deci-die roll is less than the tech level of the toy, then another piece of equipment is added to the first one.
This additional piece of equipment is rolled randomly.
This is done in the same manner as any other toy, accept that the additional toy must be the same tech level as the last one.
The ref continues to make percentile dice rolls until she rolls higher than the multi-equipment's tech level, or gets sick of combining new toys.
High tech level equipment will very rarely not be multi-equipment.
If the ref decides to roll a new tech level for each additional toy, the percentile roll will be compared against the highest of the tech #levels.
A piece or multi-equipment is going to be #different from its basic components by wate, EXPS+++<b>+++, +++</b>+++#and value.

== Wate# 

The wate of multi-equipment is the total wate of all its component toys.
Some refs may even make the multi-equipment's wate slightly less than its total components  because of shared power supplies, processing units or reservoirs.#

== EXPS 

Each piece of equipment maintains its own experience point value.
When a persona identifies a component of a combination toy she will get #experience for that part, and only when all functions of the toy are identified will she earn experience for the entire toy.#

== Value 

A multi-toy's value is equal to the total of all the component toys'
values.
The total value of the artifact is slightly greater than the total of all the component artifacts.
Add a percentage value equal to the tech level of the multi-toy.
So a tech level 10 multi-toy with a total value of 1000 would at 10% (or 100 eps) to the value of the total device.
#

== Notes 

Multi-equipment shares a common power supply, and therefore all devices will run off of a single battery set.
Every device in a multi-toy combination can be used simultaneously without penalty.
This factor alone can make multi-guns a menacing artifact indeed.
Artifact identification, is more difficult for multi-equipment, since the identifier must identify each component separately.
Multi-#equipment will often remain under used not all of the component artifacts are not identified.#
