= Combat Time

[quote]
____
Time keeps everything from happening at once.
____

Combat time is completely different from typical role playing time.
Massive amounts of time in EXP can be covered quickly in the mundane world.
Personas can travel great distances in the blink of an eye. 
Players can repair a weapon with a roll of the dice.
The expedition could 'hang out' for a month while a persona heals.
An instant of mundane time can equal days, months and occasionally years of time for personas.

Combat time is the opposite. 
In combat time seconds can take minutes of mundane time to work through.
Consider a persona detaching a boomerang from her while diving though the fog into a moving space vehicle. 
Her player can describe this plan in seconds, however making the (un)necessary rolls could take a few minutes. 
Once tactical combat starts movement is kept track of using minis on a hex mat.
Attack rolls involve consulting a combat table, arithmetic and dice rolling.
Everything slows down in combat time. 

== When Does It Start
Combat time starts when the referee or players decide so.
The hex map rolls out, the minis are thrown down and persona's lives are on the line.
If a persona's life is on the line combat time should be activated. 

== When the Unit Measure Is A Unit
The unit of time employed in combat time is a call a unit.
In the EXP world a unit is 2 seconds. 
Units are only used in combat time.
In the mundane world a unit could take 10 minutes to play out.
That means 2 seconds for the personas can take 10 minutes of mundane time to work through.

[quote]
____
*A __turn__ is called a UNIT and is TWO SECONDS in duration.*
____

== When Is My Turn?
The unit is the closest thing to a turn that exists in tactical combat.
Every persona gets to act during every unit of combat time. 
Some personas will run, some will attack, others will run and attack. 
Running is represented as tokens moving on the hex mat.
Attacking requires checking line of sight, reading the combat table, and rolling dice.

Order of action is crucial in combat and the player's take turns based on the the xref::CH33_Initiative.adoc.adoc[Initiative system].
While each player gets a turn with her persona each unit the __order__ of turns is decided by initiative.

Time is important in EXP but initiative makes the tactical combat system even more tactical.
The xref::CH33_Initiative.adoc.adoc[Initiative] system incorporates, dexterity, level, skills and luck to give fast experienced personas the advantage over lumbering neophytes.

== Doing Things
An active persona can accomplish a lot in two seconds.
Players push their personas to the limit of time and space.
In the end there is only so much that can get done in two seconds.
Referees will spend a fair amount of time reminding players of how short two seconds is.

.Three Things Per Unit
. Movement
. Action
. Movement and Action

=== Movement
Pure movement indicates the persona is doing nothing other than moving.
The persona could be running, crawling or cowering in fear.
The player moves the mini representing her persona on the hex mat.
Even pure movement can become complex when including terrain, barriers and movement types.
The details of tactical combat movement is covered in the xref::CH12_Combat_Movement.adoc[Combat Movement] section.

=== Action
Pure action indicates the persona is doing something an not moving.
The persona could be attacking, picking a lock, or cowering in fear. 
The player would be making attack rolls, performance rolls or hiding under the game table.

NOTE: *Under non-combat time such actions are completed immediately and are not measured.*

Some actions can be completed within a unit.
Other actions cannot be completed in a unit.
The only action that is guaranteed to fit into the combat unit is an attack. 
Some actions preclude the persona's ability to move or attack.
Many actions require too much attention to either move or attack. 
If a persona undertakes such an activity they cannot participate in combat while doing so.

include::ROOT:partial$CH12_Table_Example_Activities.adoc[]

=== Movement and Action
Some actions take less than a unit but still require attention from the persona.
These actions result in small movement rate adjustments.
The table is included here for convenience.
These are actually elements that 

NOTE: *Attacking is the most common action in combat. There is no movement cost for attack rolls.*

include::ROOT:partial$CH12_Table_Example_Actions.adoc[]
