= Time and Movement

This section is devoted to non-combat time and movement.
The Roll Playing System's Tactical Combat is meticulous about time and movement.
Time is played out in 2 second chunks called units.
Movement is recorded using tokens and hexagon covered mats.
This meticulous time and space keeping is only used in the Tactical Combat System.

During combat game time passes very slowly compared to mundane time.
Half a minute of game time could take hours of mundane time to work through.
Non-combat time is completely the opposite.
The expedition could have a month of game time pass by in an instant of mundane time.
A few months of space travel could pass as quickly as the bowl of chips across the game table.

When persona lives are not on the line game time passes as a convenience.
What gets accomplished is monitored qualitatively.
A research team could try to upgrade a vehicle system.
A nomad could spend time befriending and training a new alien friend.
A datalyzer could sum ten thousand prime numbers to the power of eleven. 
A mercenary could heal her injuries and return her HPS Total to HPS Max.
Any of these things could take place in an instant with a single Performance Roll.

This does not mean nothing interesting would happen during the down time.
Most referees will have unexpected encounters and puzzles ready for the expedition.
These encounters could be mundane.
For example, an insurance investigator has a few questions about what happened to a grav car.
Or a revenge driven mob could ambush the expedition for destroying a relic with a grav car.

== Unnecessary Time Table

include::ROOT:partial$CH12_Table_Time_Components.adoc[]


// location for random encounters?
// conversations between referee personas and player personas happen in real time.
