= Combat Time

Not everything happens at once, and to keep matters that way, EXP uses the concept of time.
Every action in the game occurs at a particular time, and all events happening at the same time happen at once.
Moreover, time flows that is, it runs in a smooth progression from any given time to any other, passing through every time in between, and it cant be stopped.
The concept is tricky, but fairly intuitive for anyone brought up on the inside of a universe.

Slightly more subtle is the idea of game time.
It might take a player five minutes to calculate all the ProficiencyTable adjustments for a particularly complex manoeuvre, but her persona, blithely detaching the boomerang from her left shoe as she dives through the fog into her waiting space vehicle, will finish the entire episode for better or worse in only a few seconds.
On the other hand, a comment like, Ill unlock the big door with the gargoyles on it,
might imply several minutes:of frenzied work for the persona, while, Are you talking to me, Batface
would drawl at exactly, the same speed both in the game and out of it.

Time for the personas in EXP, simply put, flows at a rate which bears little or no resemblance to time in the real world.
To help distinguish, EXP measures game time by the unit.
A unit lasts for two seconds of game time, or for one round of combat, regardless of how long in real time it takes to play out.
Its passing indicates how far a persona can move at a stretch, how many to hit rolls she can make before her opponent strikes back, or how much time she has left to use her mutation.
Naturally, two seconds isn't very long  but to pose a shorter duration would keep personas from finishing the simplest tasks in one go.
Likewise, a longer interval would leave too much time unaccounted for: a unit is about the smallest measure of time in which personas can accomplish a reasonable amount of activity.

Unlike personas, however  especially combat-prone personas  civilizations rarely operate on a two-second scale EXP thus has many longer divisions of game time by which numerous other important activities, from sleeping to mapping the fall of a galactic civilization, can be measured.
These are listed in Table 12.1, Time Components, below, along with their equivalents in units and their real time analogues.

// table 147 goes here

== Doing Things
An active persona can do a surprisingly amount in two seconds.
Players will often push their personas to the limit of time and space.
They will often be attempting compilations of actions that will make the referees head spin.
If only they would stick to straightforward moving and attacking!
There are two basic types of things that can happen: activities and actions.
There are tables listing examples of both, and the impact on the persona.
Success of such manoeuvres  are governed by performance tables.

=== Activities
Activities preclude the personas ability to move or attack.
They have a specific duration can take place during combat, but the persona cannot move or attack while carrying out these activities.
For example counting 100 eps would take 10 units and that would be all that the persona could do for 10 units.
This would only be necessary to calculate if the persona needs to count money while the rest of the expedition is engaging in combat.
Examples are listed on Table 12.2: Duration of Activities.
 
// table 152 goes here

=== Actions
Actions are bonus undertakings that have an effect on movement rate, but do not prevent combat.
Most have a movement penalty, and the most complex stop movement, but allow to hit rolls to still be made..
Typical actions are listed on Table 12.3 Typical Actions.
Actions are particularly simple manoeuvres that Do need not replace movement as the sole activity in a unit (like an activity does).
A moving persona can push open an unlocked door with only a small movement penalty, but unlocking the door would stop the persona cold.
Where the effect is Choose
the persona may choose to either move and do the action or attack and do the action but not both.


// table 153 goes here