= Experience

[quote]
_____
*Experience is previous bad experiences preventing future bad experiences.*
_____

Personas become more powerful by completing missions, surviving combat and practicing their vocation.
The concept of an experience point is as old as role playing games. 
The persona is awarded experience points (EXPS) for doing things correctly.
There are some occasions where failure can lead to earning experience points.
As the experience points accumulate the persona increases in levels.
These levels represent improvements in combat, skills and attribute performance. 

:art: research_team_biovet.png
:width: 250px
:snark: Learning by doing.
:artist: Kelly Freas
:date: 1957
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The amount of EXPS required to increase levels varies from vocation to vocation.
Anthros put their experience towards improving their vocations. 
Robots and aliens also can acquire EXPS and increase their EXPS Levels.

.*Sources of EXPS*
* Combat
* Identifying artifacts
* Successful maneuvers
* Role playing fun

Generally EXPS are only awarded for success.
There is no reason why failure should be any less educational.
Granting EXPS for failure is up the referee.
There is no system for failure experience in EXP.

== Player vs. Persona Experience 
As a player does more and more role playing, her personal skill level at role playing will improves.
No longer the incompetent neophyte that she once was, an experienced player won't even consider actions that might have sorely tempted her personas gone by.
Her current persona will exhibit an increased level of consciousness in even the simplest of her actions.
There is nothing wrong with this sixth sense that the personas of experienced players seem to have.
There is nothing that a referee can or should do to make a player forget her hard-won skills.

The player must be careful lest her persona seem to possess information she could not possibly know.
A brand new persona should not display in depth knowledge of a ruin mapped by the player's three previous personas.
However, it would be perfectly acceptable if the persona, on a hunch, acted in a very cautious manner while scrounging through those same ruins.

== Experience Points 
As the expedition progresses through each scenario the referee keeps track of earned EXPS.
Over the course of an adventure, the persona might earn 100 EXPS for using her vocation skills, 200 EXPS for identifying a toy, 75 EXPS for combat, and 1000 EXPS for good roleplaying.
Historically experience point totals are updated at the end of the scenario or evening of play.
Real time EXPS compilation is not healthy for flow of roleplaying.

Each persona's EXPS total is converted to an experience level on their appropriate EXPS Level Table.
Every vocation has it's own Experience Points to Level Table.
Aliens and robots also have Experience Points to Level Tables.

A spie who has collected 6243 EXPS is described as third level.
A veterinarian with 18402 EXPS is at fourth level.
Different vocations progress in their vocation skills at different rates.
A biologist going from 4th to 5th level needs to earn 10000 Exps, while a knite crossing the same boundary must earn 24000 EXPS.
These differences reflect how dangerous the vocation or just reflect legacy from older rule sets.

The experience level affects how well the persona performs in combat, maneuvers, and life in general.
Every roll that a player makes is adjusted in some fashion by her persona's EXPS Level.
Performance rolls, attack rolls, saving rolls, attribute rolls all reflect a bit of EXPS Level.

The experience point is a universal value like the hit point. 
One EXPS is one EXPS is one EXPS.

== Anthro Experience
Every anthro pursues a vocation.
EXPS Levels are determined by the vocation chosen by the player.
Even the venerable nothing can earn EXPS and become a better nothing.

== Robot Experience 
Robot personas are not mechanical servants in any sense of the word.
Robots are insane machines whose internal damage has given them a mind of their own.
Robots can collect experience by destroying their internal programming. 
This is achieved by misusing their peripherals and by directly  damaging their systems.
A robot earns no experience points when using any of her peripherals as expected.
A combot may get no experience for combat, but would get EXPS for using her cannons to plant trees.

=== Robot Damage and EXPS
.20 EXPS per 1 HPS of damage
****
A robot that takes 20 HPS in damage would earn 400 EXPS.
****

This method of accumulating experience also destroys the robot.
The player must is rewarded by resourceful with her peripherals.
For example, blinding targets by spray painting them mauve. 
Or use a dental drill to break into a safe.
These creative uses should earn EXPS a plenty for the persona.

Robots with vocations can level up as a vocation or as a robot.
There is no combining. 

== Alien Experience 
Aliens gain experience by succeeding at their natural abilities. 
The higher the EXPS level of the alien the better they are at being an alien.
An alien that is following a vocation must choose between the vocation or being primal.
An alien with a vocation functions the same as any other persona in that vocation.

Aliens can range from unintelligent planetary denizens to important dignitaries of intergalactic empires.

== Experience for Money
Personas do not gain EXPS for acquiring wealth.
Aliens and robots do not earn EXPS for gaining money, but they may gain EXPS for the process.
For example, there may be an EXPS award for robbing a bank. Stealing 1M or 1K eps is no different
There is one exception to this rule, the nothing vocation.

Nothings are a special vocation representing those who have no vocation. 
Nothings are most often anthros, but it is possible for an alien or robot to follow this vocation.
They are the civilians, the mundane, the unheroic.
They have maneuvers like being scared and dressing for success.
Only personas of this level of irrelevance gain EXPS from eps. 

=== Nothing EXPS for EPS
.1 EXPS per 10 eps
****
A nothing who acquires 1000 eps earns puts 100 EXPS towards her next nothing level.
****

Earned money must be stolen, found, sought, or gathered with at least some risk to the nothing persona.
EXPS earning eps cannot be given, granted, won (as in a lottery) or inherited.
Thus a nothing may receive 100 EXPS if she sold an antique chair worth 1000 eps.
If the chair was given to her by her grandmother she would get no experience points.
If she somehow earned the chair from her grandmother she would earn EXPS 

== Experience for Performance Rolls 
The most straightforward, and honest, way to earn EXPS is to practise one's vocation skills.
Whenever a player makes a successful Performance Roll her persona is awarded EXPS.
Biologists get EXPS for identifying aliens, nomads get EXPS for finding shelter, and nothings get EXPS for collecting cash.

The amount of experience awarded depends on the degree of difficulty of the Performance Roll.
The persona earns 42 EXPS per DD of the maneuver being attempted.

=== EXPS for Performance Rolls
.42 EXPS per 1 Degree of Difficulty
****
A persona succeeding at a 10DD maneuver would earn 420 EXPS.
****

== Experience for Practice
The referee may allow for personas to improve themselves with a period of intentional practise.
Personas cannot earn EXPS for practice.
Personas cannot improve attributes from practice.
If things line up in the story a persona may be able to improve their skills.


Practice should be an infrequent occurrence.
During a prolonged persona downtime the referee may allow a persona to study and practice a particular skill.
The downtime could be a long space voyage, or a savage winter.
The most a persona could add is one new skill level.
The topic must be related to the downtime.
For example a biologist left alone in a zoo for two months may add a skill in zookeeping.
However a mercenary with a part time job counting money would learn nothing.

Acquiring new skills should not be abused by the players or the referee.
Personas automatically earn new skill with new EXPS Levels.
Earning new skills the old fashioned way maintains game balance and is more fun.

A persona can only acquire one new skill after each acquiring a new EXPS Level.
A persona can only acquire a new skill with practice.
A persona cannot increase an skill level through practice. 
For example, a 3rd level biologist has the skills zookeeping 1 and herbivore 2. 
During a 3 month stint on the Valley Forge she decides to practice for the skill plants 1. 
She cannot bump up zookeeping or herbivore skills. 
She cannot practice for another skill until she earns a new EXPS Level.

== Experience for Artifact Identification
Personas in EXP will be encountering unknown technological devices of great mystery on a regular basis.
Figuring out how they work is a key source of EXPS for all persona types. 

The most fun way to identify an artifact is to role play through a prepared story from the referee.
For example, the expedition finds a slippery white cylinder with no visible markings. 
The mechanic tries plugging it into a slot in their exatmo drives.
The mercenary waves it at enemies during combat.
The veterinarian rubs it on an infected wound.
The nothing attempts to eat it with curry.
The AID Flowchart can replace role playing when time does not permit. 

Every artifact has an EXPS Value listed with it.
Hopefully more powerful and interesting TOYs have higher EXPS values.
If an artifact is acquired by adventuring EXPS are granted to the personas that identify it.
EXPS awards are only granted once for an artifact.
Artifacts purchased by money cannot earn experience.
For example, an expedition earns EXPS for a fusion rifle they found in the wilds.
They would not earn EXPS for a fusion rifle purchased at Energy Weapons R Us.
Nor would they earn EXPS for finding a second fusion rifle in the wilds. 

Some artifacts have very large EXPS values.
Such artifacts should be acquired through more complicated puzzles over many gaming sessions. 

== Experience for Combat 
The best way to gain combat experience is to fight.
Personas gain EXPS for vanquishing opponents in heroic battle.
Vanquishing being defined as knocking unconscious, paralyzing, stunning, killing, or otherwise rendering inoperative and non-threatening.
There are some subtleties and vanquishing may not be immediately obvious.
Personas with mental powers are be vanquished until their mental attacks are stopped.
Mutants that regenerate are not vanquished until thoroughly destroyed.

:art: combat_experience.png
:width: 250px
:snark: Pwned.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Simply engaging a target in lethal combat does not guarantee the earning of EXPS.
The opponent must have posed a threat to the expedition.
Slaughtering the kittens in the local pet store would not result in EXPS for combat.
An anti-knite may get some vocation experience for doing this, but no combat EXPS.
Players cannot farm experience for their personas by engaging in frequent one sided battles. 

=== Calculating Combat EXPS
Every referee persona created has a combat ratio (CR).
The higher the combat ratio the more dangerous the persona to the expedition.
Combat ratio loosely represents the number of first level personas needed for a fair fight.
A weak but aggressive alien has a combat ratio of 1/2.
This indicates two of these aliens versus 1 first level player persona is a balanced fight.
A powerful combot has a combat ratio of 200.
This indicates this one combot would need to fight an army of player personas for a fair fight.

=== Combat Ratio to EXPS
.EXPS = (100 + HPS Total) * Combat Ratio
****
A vanquished alien with 30 HPS and a CR of 5 earns 650 EXPS.
****

The EXPS value of a vanquished opponent is equal to 100 plus its HPS Total all times the combat ratio (CR).
An alien with 40 HPS and a CR of 14 would be worth 1960 EXPS.
100 + 40 = 140 then 140 x 14 = 1960.
A robot with 350 HPS and a CR of 29 would be worth 13050 HPS.
100 + 350 = 450, and 450 x 29 = 13050.
The EXPS granted is the total of the  EXPS value of each vanquished opponent.

The referee may wish to adjust combat EXPS based on the nature of the combat.
Combat that is riskier to the expedition earns more EXPS. 
Combat that faced little risk to the expedition earns less EXPS.

include::ROOT:partial$CH15_Table_Combat_Results_Adjustment.adoc[]

=== Combat EXPS and Vocation
Non-combat vocations do not glean as much useful knowledge from the combat.
The referee can choose to modify combat EXPS by vocation. 
A veterinarian will learn something about healing from combat but not as much as healing the wounded.
For example, a mechanic whose share of combat experience was 400 EXPS would earn only 20% of it, or 80 EXPS

include::ROOT:partial$CH15_Table_EXPS_Vocation_Combat.adoc[]

== Experience for Role Playing 
Role playing is the single most entertaining aspect of EXP.
The clue to this is that the words role and playing are in it's title.
Role playing informs the mood, strengthens the thread of reality, and provides essential comic relief.
Persona should be rewarded best by the role playing choices of her player.
EXPS for role playing incentivises role playing for even the most shy player. 

:art: rocketdog_jedi.png
:width: 250px
:snark: Stylin.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

[quote]
____
"I hastily rummage through the filing cabinet with my stubby claw paws. 
Ears up and sniffing for any sign of sentries."
____

The above example conveys more information than the search.
The player has included her persona's appearance.
The player has indicated her persona is also paying attention by describing her canine abilities.
This is more fun than "I search the room."
Such a description should earn her an EXPS award.

[quote]
____
"Thagron trumpets a thundering charge with her imposing bulk." The player raises her arms miming her death dealing antlers. 
____

The player has used words and physical action to convey colour to her alien's choice of attack.
This is more fun than "I attack."
Such a description should earn her an EXPS award.

include::ROOT:partial$CH15_Table_EXPS_For_Role-Playing.adoc[]

Properly assigning role playing EXPS by the referee is an epic refereeing challenge.
The ref must be keenly attuned to the player's choices.
Many referees will defer to the players to assess each others role playing flourishes.
If at any time the player seems to be stepping beyond the bounds of necessity to use language appropriate to the situation at hand, the ref should note that EXPS are deserved.

Enthusiastic descriptions may not always be clear ones.
The referee and players should be comfortable with asking for more info.
Role playing is a collective experience.
Players and referees must be supportive of players efforts in all areas.
It is fine to laugh at a terrible die roll.
However critiquing a player's role playing effort is not supportive and not conducive to fun game.

== Shared Experience
Role playing is a shared experience.
How should the referee share experience points between players.
Every referee will develop their own method for keeping track of EXPS during a session.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

Some referees will have the EXPS values of their game missions pre-determined right down to each persona.
Others will review the game night and bring the results to the next session.
Other referees will wing it and just trust their gut.

The fairest way to divide experience between personas is using shares.
Every persona involved in a combat gets a share.
The total experience for the combat session is divided by the number of shares and each personas get's one.
If a nothing was particularly important to a fight she earn an extra share.
This same process can be used when a bunch of player's work out an artifact's function and operation.

For example, there are 5 personas in an expedition.
Three personas do battle with sentry droids while the other two reprogram a security system.
The mercenary is smashing robots like jackhammer. 
The spie and the nomad are less effective.
The mechanic and nothing are doing the reprogram.
The nothing is commenting on the mainframe's aesthetics, while the mechanic is programming.

The expedition is successful.
They destroyed a bunch of sentry droids and have programmed the security system to let them in later.
Total EXPS for combat is 4000 EXPS.
Total EXPS for reprogramming the mainframe is 6000 EXPS.

Using shares the combat is divided 4 ways for 1000 per share.
The merc gets two shares for her hard work. 
The spie and nomad get 1 share each for their contribution.

Using shares the entire mission is divided 6 ways for 1000 per share.
The mechanic gets two shares for her hard work.
The merc, spie, nomad, and nothing get 1 share for the contribution to the mission.

The nothing earned a role playing EXPS award for making amusing design comments about the mainframe.
This EXPS is not divided amongst the personas. 

The merc gets 2000 EXPS for combat and 1000 EXPS for the mission. 
The mech gets 2000 EXPS for the mission and nothing for combat.
The spie and the nomad get 1000 EXPS for combat and 1000 for the mission.
The nothing gets 1000 EXPS for the mission, nothing for combat and 200 EXPS for role playing.

