= Sphincter Dice

Often a player will want to know some absolutely unpredictable, impossible to prepare, yet entirely relevant piece of data -- did she leave the car door unlocked?
Did the ammunition pack fall to the left or to the right?
Has the cheese gone moldy?
Does the store have any tents in stock?
No efficiently prepared campaign could possibly include the answers to such questions, so sphincter dice are used to see whether such milieu minutiae are in the persona's favour or not.

Sphincter dice are rolled on deci-dice by both the referee and the player simultaneously.
If the player rolls 10 or less, her request is automatically denied;
if she rolls 90 or more, it is automatically granted.
If she rolls between 11 and 89, her request is granted if and only if her roll is equal to or greater than the referee's.
If the referee rolls higher than the player, the situation is resolved to the persona's greatest inconvenience.The referee should only use sphincter dice for true inconsequentialities -- facts that will shape the path of the campaign but not the outcome.
Certainly, she should never consult them when personas'
lives are on the line.
