= Sphincter Dice

Often a player will want to know some absolutely unpredictable, impossible to prepare, yet entirely relevant piece of data -- did she leave the car door unlocked?
Did the ammunition pack fall to the left or to the right?
Has the cheese gone moldy?
Does the store have any tents in stock?
No efficiently prepared campaign could possibly include the answers to such questions, so sphincter dice are used to see whether such milieu minutiae are in the persona's favour or not.

Sphincter dice are rolled on deci-dice by both the referee and the player simultaneously.
If the player rolls 10 or less, her request is automatically denied;
if she rolls 90 or more, it is automatically granted.
If she rolls between 11 and 89, her request is granted if and only if her roll is equal to or greater than the referee's.
If the referee rolls higher than the player, the situation is resolved to the persona's greatest inconvenience.The referee should only use sphincter dice for true inconsequentialities -- facts that will shape the path of the campaign but not the outcome.
Certainly, she should never consult them when personas'
lives are on the line.

A good example is of a persona searching a hardware store for a size L8 wing nut.
Wing nuts are kept behind the counter, so she asks the storekeeper if any are in stock.
Hell,
replies the referee, I don't know: Let's check the sphincter dice.
The player and the referee both roll, but the player's roll is a 94, so the part is automatically available.
She purchases it and leaves.
A  little later, the persona accidentally steps underneath a powerful electromagnet.
The referee isn't sure if the wing nut will be attracted to the magnet or not, so she calls on the sphincter dice once more.
This time, the player rolls a 75, but the referee rolls an 84;
the electromagnet immediately tries to wrest the wing nut from the persona's grip.
The rest of the encounter would be determined by attribute rolls, mutations, or even combat.


