= Attribute Rolls

Most unusual situations will directly challenge one of a persona's attributes -- catching a valuable egg, for instance, relates to DEX, or  noticing that odd echo every time the leaf merchant opens her mouth pertains to AWE.
No simulation game can possibly have specific rules for all such eventualities, though -- and if it did, finding any one of those rules on demand would take hours -- so EXP uses a system of attribute rolls to allow the referee to improvise on demand.

Some situations, like scaling a cliff face, or aging beyond one's natural life span, have a particular attribute roll associated with them;
except for these few cases, attribute rolls should only be used in genuinely unusual circumstances.
No persona should have to roll a die just to open a door successfully, but if she is panicking, heavily encumbered, and being shot at by a lumpy fish, it may be fair if she checks for a fumble.
Similarly, attribute rolls should never infringe on class skills: no persona, whatever her luck, should be able to survive indefinitely without food if she isn't a nomad.

== Attribute Type
The referee decides which attribute is most relevant to the situation, and the player tries to roll equal to or less than her persona's attribute value.
If she succeeds, her persona has also succeeded;
personas with high attributes are thus somewhat better off than personas with low attributes.
Table 16.1: Relevant Attributes gives some example circumstances and which attribute would apply.
Sometimes, the referee may require more than one attribute roll for a complicated action -- to catch a very heavy valuable egg, for instance, might require attribute rolls for both DEX and PSTR.

// insert table 183

== Difficulty
Not all attribute rolls  have the same level of difficulty. After all, a player will roll under her persona's INT far more easily using a d10 than using a d1000.
When assigning an attribute roll, the referee must decide not only which attribute the persona must roll under, but also on which dice she must do it.
Table 16.2: Attribute Roll Difficulty lists some levels of difficulty and the dice used to challenge the attribute.
Titles like Easy
and Improbable
should indicate how vague these levels are.
They are not performance table DD's, and hardly describe distinct categories of difficulty.
The referee can, and should, fiddle with them at will.
Personas cannot earn EXPS for winning an attribute roll.
Specific attribute rolls are usually referred to by their difficulty and the name of their relevant attribute: an attribute roll against MSTR on d50 would be called a tough mental strength roll.

// insert table 184

== Bonuses
Like performance rolls and to hit rolls, attribute rolls have bonuses associated with them.
A persona could have a penalty assigned but usually this is represented by making the roll more difficult.
All players get to add their persona's level to an attribute roll.
A 3rd level persona with a 10 INT  would need to roll less than 13 on an intelligence check.
Other times bonuses are just applied due to a skill or artifact adjustment.
If a persona's DEX is 12, and she has an attribute roll bonus of 3, she must roll under 15 on whichever die she's using;
if it has a penalty of 8, she must roll under 4.
The most common bonus is the experience level of the persona.

*Roll Less than = Attribute plus EXPS level*

Let's consider a 3rd level persona with a DEX of 14 and an INT of 5.
If she needed to catch a falling egg and the ref decided that this was a Normal dexterity challenge the player would need to roll 17 or less on a d20.
She is almost guaranteed to catch the falling egg.
Although if she needs to remember what floor of the building the egg was tossed from that might be an easy intelligence challenge, and the player would need to roll 8 or less on a d10.

== Attribute Competition Rolls
An attribute competition roll pits two personas against each other in a contest directly related to an attribute.
They might do battle with PSTR by arm wrestling, or with DEX by skipping rope;
they might compare MSTR in a staring contest or AWE by hunting for mites in each other's fur.
Each player involved rolls a d20 and adds the result to her persona's relevant attribute.
Which ever player's total is highest wins the contest.
Ties are just that: the personas can continue the struggle or declare themselves evenly matched and go for a soda.

Eight macho personas decide to have a duel by bowling, they each must roll a d20 and add the result to their DEX.
Supposing that the totals are 8, 14, 15, 15, 21, 24, 24, and 24, the first five personas have lost, and will presumably be executed at dawn;
the last three each rolled a strike, and must move on to the second frame if the duel is to have a lone winner.
If they bowl again, and their new totals are 19, 28, and 22, the second persona has won.

== Combining Forces
Just as personas can form research teams to attempt delicate and complex class procedures, they can join together to perform an attribute-related manoeuvre -- three ursidae combining PSTR to manipulate a battering ram, for example, or five basketball players'
DEX trying to block a layup.
On such an occasion, the players should average their personas'
relevant attributes, and add one to the result for each persona more than one in the group.
Each player then gets one attribute roll, and if any of them succeeds, the entire group is successful.

In the case of the ursidae above, if their PSTR, scores are 10, 8, and 15, their average PSTR is 11.
Since there are three of them, they add two to this average to get 13, and each proceeds to try to roll 13 or lower.
(Clearly, the first two ursidae are only slowing the third one down: she'd be better off just using her shoulder three times.) The five basketball players, however, if each has a DEX of 13, also have an average DEX of 13;
adding four because there are five of them, will need to roll under 17 to block the shot.
