= Critical Rolls

Critical rolls are extreme rolls of the dice -- 001 or 000 on kilo-dice, 1 or 20 on a d20, 00 or 01 on deci-dice.
As any amateur statistician will point out, such extreme rolls are no more likely than any other roll, an impressive 998 is no more significant than an obscure 452 
but somehow an air of urgency always accompanies them.
Players inevitably react hysterically to a roll of 000, because there is something so dramatically fateful about it.

:art: critical_hit_arrow_split.png
:width: 250px
:snark: Critcal hit.
:artist: Warren Oddsson
:date: 1990
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]



In gaming terms, critical rolls represent incredibly fluky results that could be either detrimental or beneficial to the persona attempting them.
Critical rolls add spice to the game, because they always bring that slight chance of the unexpected.
The wimpy little alien stuck in the crevasse might yet beat the arrogant invader in powered armour if she makes a critical to hit roll.
The landlubber mechanic may never have seen an exatmo drive before, but could still manage to patch one together if she makes a critical performance roll.
EXP is science fantasy, and part of fantasy is the unexpected.

Nevertheless, a well-developed scenario should never be terminated early by a critical roll --they exist to enliven, not to destroy, the campaign.
Like all rules, they should serve the players, not the other way around;
any time a critical roll interferes, the referee should simply manipulate the outcome until everything fits once more.

All critical rolls must be natural.
If a player rolls 794 to hit, then no matter what bonuses she has, her roll is not a critical one.
Conversely, if she rolls a natural 01 on a performance roll, all the bonuses in the universe won't keep her from suffering a critical failure.

== Performance Table Rolls
PT rolls are made on deci-dice;
the goal is to roll high.
A natural 00 will thus bring automatic success in whatever procedure was being attempted, however difficult, and a natural 01 automatic failure.
Some procedures should never have a chance of success -- gall bladder surgery with a meat hook will always result in tragedy --but there's little point in even rolling for these.
Use your common sense.

Occasionally, a critical PT roll success will seem to indicate an exorbitant number of EXPS for the persona.
EXPS are handed out for class skills because of the knowledge gained through the successful maneuver.
A vet who has managed to accomplish something far beyond her skill by sheer luck has gained nothing from the experience but a healthy llama.The referee should reduce her EXPS award accordingly.

== Attribute Rolls
Critical attribute rolls are redundant.
Since the object of an attribute roll is to roll low, a critical success is a roll of 1 --but since all living personas have positive attributes, only dead personas would ever fail on a roll of 1.
And dead personas don't make attribute rolls.
Conversely, a critical failure is a maximal roll on whichever die is being used -- 10 on d10, 20 on d20, etc.
A maximum roll should fail regardless. Otherwise the persona had no chance of failing, and the referee shouldn't have called for an attribute roll in the first place.

== To Hit  Rolls
To hit rolls are made on kilo-dice (1d1000), and like PT rolls, the goal is to roll high.
Any roll naturally greater than or equal to 990 is thus called a critical hit, and will inflict from 1-4 (d4) times the rolled damage, a factor known as the damage multiplier.
A natural roll of 000, aka 1000 on a d1000, provides an instant kill.
When calculating the damage from a critical hit, a player first rolls the damage as normal, then multiplies by the damage multiplier, and only then adds her PSTR damage adjustment.

All of this only applies to cases where 990, or 000, would have hit anyway.
If a critical hit is the only way for the persona to hit her target a critical hit simply means a hit, with damage meted out as normal.
Similarly, critical hits by the referee are always just hits, with no instant kills and no damage multiplier, for personas are attacked so much more often than their opponents are that any other ruling would kill off personas far too quickly.

A critical miss with a type A or B weapon is any to hit roll less than or equal to 010;
any player who makes such a roll has dropped, misthrown, misstrung, or otherwise mishandled her weapon.
If the player rolls below 050 with a type C weapon, the referee should check for a malfunctions.
A roll of 001 with a type A weapon indicates that the persona has accidentally damaged herself or broken the weapon.
Any type B weapon attacking with a 001 to hit also automatically breaks, but without damage to the persona;
type C weapons subject to a 001 critical miss automatically jam.
The amount of damage suffered by a malfunctioning weapon can be determined in http://expgame.com/?page_id=286[Chapter 21, Equipment Damage].

== No Critical Rolls Here
There are no critical rolls in DSS rolls, REC rolls, CF rolls, saving throws, attribute challenge rolls, or sphincter dice.
The first four cases all govern involuntary reactions, in which the body (or mind) is already doing the best it can;
the concepts of critical success and failure are meaningless for white blood cells.
Critical attribute challenge rolls, like critical attribute rolls, are a redundant concept -- if only one persona has a critical success, she's won anyway;
if two do, they're still tied.
Sphincter dice, meanwhile, already have critical rolls built in: if the player rolls over 90, events proceed in her favour, and if she rolls under 10, they don't.
