= Sphincter Dice

Sphincter Rolls are a roll that a player makes against a referee.
There are absolutely no bonuses or penalties applied to a Sphincter Roll.
The roll is made to determine an impasse in normally congenial discussions surrounding the task at hand.
For example, did the persona leave the door unlocked?
Did the ammunition pack fall to the left or to the right?
Has the cheese gone moldy?
Does the store have any tents in stock?

No efficiently prepared campaign could possibly include the answers to such questions.
So sphincter Roll is used to see whether the minutiae falls in the persona's favour or not.

Sphincter Rolls are made on deci-dice (1d100).
The referee and player roll simultaneously. 

.*Sphincter Roll Results*
* 01-10 Player has missed the roll
* 11-89 Player must roll higher than the referee
* 90-00 Player has succeeded in the roll.

A success by the player is resolved to her persona's convenience. 
Sphincter dice cannot be used to solve a referee's puzzle or change the course of a campaign.

A failure by the player is resolved to her persona's inconvenience.
The referee should only use sphincter dice for true inconsequentialities.
A failed Sphincter Roll should never kill or severely injure a persona.

== Example Usage
A persona searching a hardware store for a size LT8 poly flanged wing nut.
Wing nuts are kept behind the counter, so she asks the storekeeper if any are in stock.
Hell, replies the referee, I don't know: Let's check the sphincter dice.
The player and the referee both roll.
The player's roll is a 94, so the part is automatically available.
A successful visit to Space Nuts Are Us has been completed.

Later, the persona carelessly steps through a powerful electromagnetic field.
The referee wonders if the wing nut will be attracted by the magnet or not.
So a Sphincter Roll is required.
The player rolls a 75, but the referee rolls 84
The electromagnet pulls the wing nut from the persona's shirt pocket.
The rest of the encounter would be determined by attribute rolls, mutations, or even combat.


