== Saving Throw

Saving throws, or saves, are special attribute rolls that compete against a specific toxin or attack.
There are saves versus poison, saves versus radiation and saves versus psionic attack.
The save represents personas internal against an external attack.
The saving throw governs those  automatic physical and mental processes over which the persona has no conscious control.
The body always defends against poison or psionic attack.

=== Intensity
Saving throws differ from attribute rolls because the attack (poison, radiation, stun, psionic, sleep) has an intensity.
The higher the intensity the more difficult it is for the persona to defend against the attack.
Acting against the persona is the intensity of the attack, a measurement of just how powerful it is.
Intensities range from 1 to 25, with 1 being mostly harmless and 25 usually fatal.
In the case of a poison attack, the intensity varies with the type of poison employed.
(See http://expgame.com/?page_id=347[Chapter 50,]http://expgame.com/?page_id=347[Pharmaceuticals], for descriptions of a wide variety of poisons).
The intensity of a psionic attack is equal to the MSTR of the attacker.

=== Toxin
The most common toxins are poison and radiation.
When a persona is poisoned, her body sets in motion a collection of activities to repel the offending substance.
If the poison attacks her digestive tract, it may trigger vomiting or diarrhea.
Other effects depend on the toxin attack.
Typical poisons include nerve toxins, radioactive substances, venoms, and drugs, any of which might act through inhalation, digestion, or simply contact with the persona's skin, fur, or scales.
Only the persona's CON puts up any defense.
The player must roll less than the save versus toxin using a Normal (1d20) or a difficult (1d30) roll.


*Save versus Toxin = Constitution plus EXPS level minus Poison Intensity*

If the persona fails her save against a poison attack, the poison does her d4 His of damage for every point of its intensity.
For ease of play, it then leaves her system, and she eventually recovers if she's still alive.
(In real life, some more insidious poisons can remain in the body for decades, gradually debilitating it until they are removed by operation.
If the referee really wants to bog down her campaign with the hassle of calculating strontium ratios in the bone tissue, she can, but it's far simpler to assume that all poisons act once, act quickly, and leave within a couple of days.)

=== Psionic Attack
A psionic attack is any foreign intrusion into the persona's thinkspace (mind).
This collection of defensive measures cannot be measured by modern instruments.
All psionic defense  occurs at the subconscious level;
unless the persona is actively searching for mental interlopers, she will not even know she is under siege until too late.
Only her MSTR can help.
The player must roll less than the save versus psionic using a Normal (1d20) or a difficult (1d30) roll.


*Save versus Psionic = MSTR plus EXPS level minus Attacker MSTR*

A failed psionic attack usually results in a specific effect on the target.
So if a player fails her person's save versus psionic attack anything from having her mind read, to being telekinetically thrown can result.
Various effects are described in too much detail in http://expgame.com/?page_id=364[Chapter 58: Mental Mutations].
Unlike toxins, however, no mental attack has partial success.
The psionic attack is either completely repelled or completely successful.

=== Various Bonuses
All insectoids get a +1 bonus against psionic attacks for every 4 points of MSTR.
Myra the bumblebee with an MSTR of 17 would get a +4 bonus versus psionic attack.
All ursidae get a +1 bonus against poison for every 3 points of CON.
Gruff the grizzly with an 8 CON would get a +3 bonus against a poison toxin.
