= Driving

Driving involves the manual control of any powered vehicle.
The exact meaning of manual control and motor-powered is left to the discretion of the referee, and in EXP there are many variations to be had.
The driving system is designed specifically for those vehicles that are created in 

The vehicles created there are primarily land or atmosphere dependent.
This section does not cover water vehicles, submarines or spaceships.
If a vehicle is created which does not seem to fit the description of anything that can be used on any system, the ref must design her own system, adapt an existing one, or discard the vehicle.

:art: cool_cat_cool_car.png
:width: 250px
:snark: Cool cat. Cool car.
:artist: Kelly Freas
:date: 1955
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The basic assumption made about driving is that it is safe, provided that drivers obey traffic regulations, and employ reasonable amounts of common sense.
Such common sense involves not over-driving (speeding, cornering), choosing a qualified driver, and properly maintaining the vehicle.
By nature, personas are daring, unskilled and mechanically ignorant.
Who can expect an expedition of murderous mercenaries, technically inept biologists and terrified nothings to do anything less than throw caution to the wind, and disregard common sense?


:art: van_turret_dust.png
:width: 250px
:snark: Don't text off road.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

== 1) Check Warranted? 
When the driver is required to complete a driving roll is the ref's decision.
Some occasions when a driving roll is warranted are: any dangerous maneuvers;
whenever the driver has been hit;
sudden change in road conditions (oil slick, change in grade);
whenever the vehicle has been damaged;
if the driver is distracted (arguing with other personas, telling a joke, juggling dice);
or whenever the ref gets irritated.
Even though a driving performance roll check is initiated by a somewhat subjective referee decision, the remaining steps are based on the difficulty of the maneuver, the DEX of the driver, direction of loss of control, and speed of the vehicle.

== 2) Driving Performance Roll 
Whenever drivers attempt to be daring, adventurous or foolhardy (the prime characteristics of all personas) while driving they have created a dangerous situation.
When the driver has attempted some dangerous maneuver, the player must make a driving performance roll http://expgame.com/?page_id=277[Table 17.1: Driving Performance Roll].
This table is similar to other performance tables.
The degree of difficulty (DD) is based on the difficulty of the maneuvers, but the skill level is replaced by the handling level of the vehicle.
Every vehicle created in the Technological Object Yield System (TOYS) will have a handling level.
The better the handling level the more insane the maneuvers that can be carried out.

A successful driving performance roll indicates that nothing bad has happened, and driving continues undisturbed.
A driver is more likely to have success with a driving performance roll if she has skill in driving, and is driving a vehicle with a good handling level.
Failure of a driving performance roll indicates potential for loss of control of the vehicle.
Players that fail a driving performance roll have to succeed at a DEX attribute roll, or they lose control of the vehicle.

The Driving Performance Roll Table is left open, like all other performance tables, for bizarre manoeuvres which no sane ref can be prepared for.
Included with the performance table is a list of expected manoeuvres and their adjustments.
There are more adjustments than manoeuvres.
The adjustments affect the DD of specific maneuvers, and they are listed with a + or 
sign.
The + adjustments make the maneuver more difficult by increasing the DD, and the -adjustments make it easier decreasing the DD.
For example, driving in reverse is not a 3DD manoeuvre, but any maneuver attempted while driving in reverse is increased by 3DD (this includes driving straight).
If there are any questions about performance tables in general, refer to http://expgame.com/?page_id=269[Chapter]http://expgame.com/?page_id=269[14: Performance Rolls].

== Driving Performance Rolls 
This is the performance table for either maneuvers that the driver is trying to accomplish, or when the driver is challenged in some fashion.
Please check step 1) Check Warranted?
The listed maneuvers are mere inspiration, the players will surely come up with more.
Handling Level is determined by the vehicle.
All vehicles in EXP have a handling level.
Example maneuvers are given below.
Example adjustments are given below as well.
The referee should use the penalties with reason and fun in mind.
Making it impossible to park a vehicle due to penalties would SUCK.
The  table shows Handling Level versus degree of difficulty (DD).
Each row represents a Handling Level and the columns are degree of difficulty (DD).
So a Vehicle with Handling Level 5 attempting a DD 5 maneuver would need to roll 15 or higher on d100 to be successful.
This table can be scrolled left to right and right back left again.

// replace with table 188

// replace with table 189

// replace with table 190

== 3) Recovery DEX Roll
Failing on the performance table does not mean players should crumple up their persona record sheets.
The driver still has a chance to recover from her driving error through sheer dexterity.
This is done by granting the player a DEX roll in a desperate attempt to avoid loss of control.
If there is a fail of on the Driving Performance Roll the player must make a Recovery DEX roll must be made.
Once again, the faster a persona drives, the more dangerous the maneuver.
The Recovery DEX roll becomes harder with the more difficult the degree of difficulty that was failed.


Let's consider a driver with an 11 DEX operating a vehicle with a handling level of 5.
She is attempting to turn left at an intersection when one of her passengers spills a PGGB in her lap.
This constitutes a Driving Performance Roll, whereas normally, this simple driving maneuver (i.e., rounding a corner) would not warrant a check.
A 90
turn is a DD4 maneuver.
She is obeying her speed limit, and no other penalties (road conditions, etc.) apply.
She must roll over 5 to corner without further incident.
Unfortunately, she rolls 02, and fails.
Before losing control of her vehicle, she gets a difficult Recovery DEX roll (d20) because she failed a 4DD maneuver.
She rolls a 4 on the d20, and maintains control of her vehicle because she has rolled less than her DEX.

// replace with table 191

=== Speeding
Speed effects are dependent on the player's DEX.
A high DEX reflects good eye-hand coordination, agility, and reaction time, all of which aids in avoiding accidents.
The maximum speed that a persona can handle is 1 h/u per point of DEX.
Thus a player with a DEX of 10, could travel at 10 h/u (36 km/h) without having a speed penalty.
For every 10 h/u (36 km/h) over this driver's maximum speed, any maneuver is increased by 1DD.
If the persona with a 10 DEX were cruising down a highway at 40 h/u (144 km/h) she would have +3DD on any maneuver attempted.
The expedition will quickly realize that speeding can prove very hazardous.

== 4) Loss of Control
Loss of control of a vehicle results when the driver has both failed her Driving Performance Roll, and her Recovery DEX roll.
Losing control of a vehicle will last a certain amount of time in units and result in deceleration and deviation.

=== Duration
The loss of control of the vehicle will last for 0 to 3 units (1d4 
1).
This determines how many units the vehicles careens out of control.
If the vehicle is traveling 10 h/u and loses control for 3 units the vehicle will travel for 30 hexes before control is regained.
The referee would roll a new deceleration and deviation for each unit of lost control

*Duration of Loss of Control (units) = 1d4 minus in units*

=== Deceleration
While trying to control the vehicle the driver will presumably brake, or momentum will be lost in the lack of control.
A vehicle that has lost control will decelerate by 0%-50% (d6-1) from its previous speed.
This deceleration can be quite hazardous to the passengers if they are not properly restrained.
A 0% deceleration indicates no loss of vehicle speed.
A 50% deceleration indicates that the vehicle will be travelling at half its original speed at the end of the deviation.
The decelerated speed is the one that determines the damage if an accident should result.
The deviation will last for 0-3 units.
A new amount of deceleration is rolled for each unit of loss of control.


*Deceleration of of Vehicle = (1d6 1) times 10% *

=== Deviation
Finally, the direction of the loss of control is determined by the roll of percentile dice.
The last one, deviation, is left to the discretion of the referee.
The ref must decide whether the vehicle-deviates left, right, or in some cases up or down;
this is usually done randomly.

// replace with table 192

// replace with table 193

=== Example of Loss of Control
In a previous paragraph of this chapter there was a poor driver who had a PGGB spilled in her lap while attempting to make a left hand turn, at 11 h/u.
If she had failed her DEx roll then she would have lost control of her vehicle.
First it is determined how long the vehicle is out of her control 0-3 unites (1d4-1).
The Duration of Loss of Control was  1 unit.
Which means this unit and the next.
Secondly she would determine how much she decelerated.
A 1 was rolled on the d6 which indicates 0% deceleration.
Thirdly her deviation roll was 36 indicating that she travels straight ahead.
So in her first unit of loss of control her vehicle will travel straight ahead at 11 h/u.
This could mean that she just missed the left hand turn, hit an oncoming vehicle turning left, or careened off an embankment.
In her second unit of loss of control her vehicle would decelerate a given amount and her deviation of loss of control would be re-rolled.

:art: vehicle_collision_imminent.png
:width: 250px
:snark: Cosmic Highway Patrol
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]


== 5) Collision? 
Losing control of a vehicle may result in an collision.
A collision can only occur if the driver's loss of control causes the vehicle to crash into some obstacle, or careen off the road.
The chance of losing vehicle control is increased by bad road conditions, bad weather, an improperly maintained vehicle, poor handling level, high vehicle speeds, and poor physical condition of the driver.
If any obstacle crosses the path of an out of control vehicle, then the vehicle has had a collision with that obstacle.
If loss of control results in a drop of more than half a hex (land based vehicle only) an accident has resulted, if the vehicle crosses the path of a simultaneously moving vehicle then the two have collided.
Either of these scenarios, or any other similar one, indicates damage to the vehicle and its passengers.
When there is a collision both the vehicle and the passengers are damaged according to 

The driving system should be used with much caution.
If strange things begin to happen (E.g., the personas become petrified of vehicles), it may indicate a need to alter the way the ref runs the vehicle system.
The deadliness of a crash depends on the speed of the vehicle.
The higher the speed, the more dangerous the collision.
Damage is divided into two categories: damage to the vehicle, and damage to the passengers.
Vehicle damage is recorded by the state of a particular part of the vehicle;
passenger damage is recorded in hit points.
Special vehicle construction can reduce vehicle damage, and safety equipment (restraining belts, air bags) can reduce passenger damage.

== 6) Collision Damage 
Everything considered, driving is safe;
it's crashing that's dangerous.
The speed of the collision represents the energy of the collision, and therefore the amount of damage delivered to the vehicle and the passengers.
The speed that the vehicle decelerates to is the speed that is used on Table 17.4: Collision Damage.
The after-collision speed depends entirely on what the vehicle crashed into.
Vehicles involved in a head on collision would be reduced to zero speed, while vehicles that scrape up against a embankment may not be slowed at all.

*Collision Speed*:The speed at which the vehicle collides determines the severity of the accident.
The decelerated speed of the vehicle is what is used in the the event of a collision.
A deceleration of 50% could mean damage to unrestrained passengers.
For instance a vehicle that slows down to 50 h/u from 100 h/u means that inertia will carry personas into the bulkhead of the vehicle at 50 h/u.
Smart explorers wear their seat belts!!

// replace with table 194

=== Persona Damage
Damage to passengers is very straight forward;
everyone in the vehicle takes the amount of dice damage indicated by the vehicle's collision speed.
The amount of damage indicated can be found on the Collision Damage_ T_able.
One roll may indicate damage for the group, or damage may be re-rolled for each passenger.
If a vehicle were travelling at 50 h/u, the driver lost control and decelerated to 35 h/u, but still got into an accident, every passenger would take 6d10 HPs in damage.
If the passengers are in a vehicle that has been hit with a vehicle travelling at high speed then they will take damage as if they were in that vehicle.
Pedestrians hit by vehicles will take damage as if they were in an accident with the vehicle, thus a vehicle travelling 35 h/u would do 6d10 to a pedestrian.

If the referee feels that it is necessary, the passengers may take damage relative to the wates of the vehicles involved.
Passengers in a heavier vehicle may take less damage than passengers in a lighter vehicle.
The wates of the two vehicles are divided, and the resultant ratio is multiplied by the damage.
Referees will mostly use this system to reduce the damage to personas that are in heavier vehicles.
The damage adjustment cannot exceed 4 times, nor be less than 4 times.

=== Vehicle Damage
The higher the speed of the vehicle has its collision at the more damage that it endures.
Column three of Table 17.4 Collision Damage determines the number of time the vehicle is damaged.
Vehicles don't have hit points per se, so the higher the speed of the collision the more vehicle parts that are damaged.
For example,  a vehicle that has a  collision at 8 h/u will not be damaged.
A vehicle that has a collision at 28 h/u would make 3 vehicle damage rolls.
A vehicle that collides at 60 h/u (250 kmh) would make 6 damage table rolls.
Each roll damages a specific part of the vehicle to a certain extent.
This is similar to the way a robot is damaged.
Each damage roll indicates a roll first on Table 17.5: Location of Vehicle Damage;
and then Table 17.6: Extent of System Damage.
The decelerated speed of the vehicle is what is used to determine how much damage the vehicle has sustained.

=== Location of Vehicle Damage
A roll on the Location of Vehicle Damage table must include an Extent of Damage roll.
The location of damage determines which vehicle function is affected by the accident.
The extent of damage roll indicates the new level of efficiency of the damaged part.
If a vehicle's speed interface were to sustain major damage, it would function at 60% its previous efficiency.
So if the damaged vehicle had a maximum speed of 30 h/u originally, this would be reduced to 18 h/u.
Note that vehicle damage is cumulative, and further damage to the speed interface would affect the current 18 h/u max speed.

The Location of Vehicle Damage Table is also used if the vehicle is hit with a weapon attack.
This is discussed in greater detail in chapter 39, Other Vehicle Combat.

// replace with table 195

=== Extent of Damage
The more speed the more damage.
The amount of damage dealt to the system is determined on Table 17.6: Extent of Vehicle Damage.
For each system that is identified as damaged on Table 17.5: Location of Damage the extent of damage must be determined.
Trivial damage indicates mostly cosmetic damage that does not affect the system damaged.
Critical damage would reduce the performance of the vehicle system to 30% of previous function.
So a vehicle that has a top speed of 24 h/u taking critical damage to its Speed System would now have a max speed of 8 h/u.

// replace with table 196

Table 17.6: Extent of Vehicle Damage is also used if the vehicle is damaged by a weapon attack.
In this instance the HPs of damage inflicted is added to the extent of damage die roll.
This is discussed in greater detail in http://expgame.com/?page_id=322[C]http://expgame.com/?page_id=322[Chapter 39: Other Vehicle Combat].

=== Speed Adjustment
One would expect that the speed at which a vehicle is involved in an accident would affect the extent of damage it receives.
It would be unfair to have a vehicle's Speed System destroyed by a collision at 2 h/u.
However one could easily justify such a disaster.
If the referee and player's would like to have a speed adjustment to the extent of damage table here you go: 

*Adjust Extent of Damage Roll=  0.5 times speed (h/u) 
10*

This equation ensures that vehicles travelling very slowly tend to be damaged less than vehicles travelling fast.
A vehicle travelling at 8 h/u is involved in a collision;
the extent of damage roll (1d100) would have -6 added to the roll.
Nothing in this collision could be destroyed at this low speed.
However for  a vehicle travelling at 40 h/u the referee would add 10 to the extent of damage roll. In a collision at this speed the vehicle would not get lucky with trivial damage and is more likely to have vehicle systems severely broken.
One could argue that this should be used to protect persona vehicles at low speeds only because high speed collisions already have multiple rolls on the damage table.


=== Relative Wate
If the ref does not take relative wates and speeds into account, the following scenarios are possible: moped rams 80 ton military tank at high speed, tank crew killed;
jet plane crashes into parked convertible, convertible driver escapes injury due to low speed of convertible.
There are some Newtonian solutions to these potential gaming inaccuracies.
Remember to sum the velocities of any two moving vehicles crashing into any of the three front hexes (head on).
Relative speeds may also be reduced if the colliding vehicles make contact on any of the back three facets (rear ender).
Relative wate works much the same in vehicular accidents as it does in http://expgame.com/?page_id=306[Chapter 31: Robotic]http://expgame.com/?page_id=306[Combat].

If the referee feels that it is necessary, the passengers may take damage relative to the wates of the vehicles involved.
Passengers in a heavier vehicle may take less damage than passengers in a lighter vehicle.
The wates of the two vehicles are divided, and the resultant ratio __is __multiplied by the damage__.
__Referees will mostly use this system to reduce the damage to personas that are in heavier vehicles.
The damage adjustment cannot exceed 4 times, nor be less than _4 _times.

=== Further Complications
There are further complications that the ref may be interested in.
The chance of a passenger being trapped in the wreckage of a vehicle is equal to the amount of damage that the passenger takes.
The chance of a fire is left to be decided by the sadistic ref, but a good system is: there's a 10% chance of fire if the fuel system is critically damaged or destroyed.
If the situation is very critical, and the players desire that everything be quantified, the ref may have to disregard her colorful ad lib description and use Table 17.7 : Accident Description.
The results from the table do not affect damage to the vehicles in any way.
However, other consequences may arise from the described chain of events.
