= Artifacts

[quote]
____
*A bad manual can make even the simplest technology appear as magic* 
____


// basis of EXP
// technology terminology
// artifacts, TOYS, tech
// ID is a minigame.
// Destroying things
// NOT Mundane equipment

EXP's headline is "The Game of Technological Chaos."
This reflects a rule system that expects any device to exist alongside any other device.
Is the laser pen mightier than the vibro sword?
Can a low tech culture devote all it's resources to make a time machine?
Can a high tech culture devote all it's resources make itself feel sad and pathetic?
Add a bit of humour and these are explorations are what EXP is all about.

NOTE: *Technology represents a mix of unknown devices.*

In our Mundane Terran olden daze there was a game show about https://en.wikipedia.org/wiki/What_in_the_World[identifying things,window=_blank].
This game show was broadcast on a one way colourless video device called a television.
More than 70 years later neither this game show or device exist.
The game show is now a real time experience between friends.
The television has been replaced by a handheld piece of glass. 
This is just one device spread over 3 of our mundane Terran human generations.

Consider a world where all these devices, especially science fantasy ones, exist simultaneously.
If this sounds like fun you are reading the right book for you.
How this happened is entirely up to the milieu of the referee.
Did countless society's rise and fall leaving their technology to be found later.
What if our Mundane Terran pyramids were full of technological devices beyond our https://en.wikipedia.org/wiki/Stargate[understanding,window=_blank]?
How it happens is up to the players. 
How to simulate it is in the Role Playing rule set.

Calling technological devices artifacts is a twist on the archeological nature of the their discovery.
These discovered artifacts represent the detritus of a technologically advanced civilisation.
Everything old is new again.
EXP artifacts are usually found by personas while on an expedition.
There is no reason that they could not be purchased from a local junk store, print catalogue or computer store.

Throughout EXP the term TOYS and artifacts are used interchangeably.
The term TOY grew from the random artifact generation system called the Technological Object Yield System.
It is also a concrete reference to the fact that a powerful artifact is a toy to play with.

.*Artifacts are TOYs*
* Generating artifacts
** xref:iv-hardware:An_index_hardware.adoc[Technological Object Yield System,window=_blank]
* xref:CH20_Artifact_ID.adoc[Artifact Identification,window=_blank]
** a mini game
* xref:CH21_Artifact_Damage.adoc[Artifact Damage,window=_blank]
* Tech Levels


