= Attack Types

[quote]
____
*Sticks and stones may break my bones. A fusion pistol's gonna roast me.*
____

An attack is anything that intends to injure another persona.
An attack is when the player makes an attack roll in an attempt to reduce a target's hit points.
This section focuses on attack rolls using weapons, tentacles or ramming. 
It includes any action where the attack roll is trying to hit a specific target.
For example the target hex of an area of effect weapon.

Attack types *not* detailed here include: psionic attacks, poisons, or bullying.

== Attack Types
EXP has an enormous variety of attack types.
Attack types go far beyond weapons. 
Attack types include alien tentacles and robot peripherals.
A weapon, an evolved ability and a deadly peripheral may all have the same attack type.
The attack types are organized by power, range, and frequency. 
There are many edges cases and exceptions.

Each persona deploys each attack type differently depending on their family and vocation.
These personalized differences are in the xref::CH09_Combat_Tables.adoc[Combat Table] section.

include::ROOT:partial$CH28_Table_Attack_Types_Intro.adoc[]

== Type A Attacks
These are non powered thrusting and striking attacks.
Type A attacks depend on the muscle power of the attacker, and must connect with target to cause damage.
The combatants must be in adjacent hexes to be able to damage each other.
A type A attack roll can be made once per turn (called a unit).

Examples are: clubs, fists, claws, bites, swords, and ramming.
An anthro could use a weapon like a sword or a axe. 
An alien could use it's natural attack like a bite, or a talon slash.
A robot could use a malfunctioning peripheral that operates like an club.

Aliens and robots can have multiple attacks per turn with their type A attacks.
For example an alien may be able to bite three times each turn.
Or a robot may have multiple pointy things to stab with.

=== Type A Weapons
These are non-powered thrusting and striking weapons.
Type A weapons are hand held, but can include the hand itself.
Type A weapons include swords, maces, pole-arms, fists, paws, beaks, spears, etc.
They are close combat weapons and the target must be in the persona's hex or an adjacent hex.

include::ROOT:partial$CH28_Table_Type_A_Weapons.adoc[]

The length and wate of the weapons is self explanatory.
AR bonus is granted to personas that have a proficiency in the weapon as a shield.
The AR bonus is added to the persona's armour rating.
Damage indicates the die roll that is made if the player makes a successful attack roll.
For type A weapons the damage value is increased by half the persona's PSTR attribute.

== Type B Attacks
These are non-powered projectile attacks.
Type B attacks depend on the muscle power of the user, and are launched the target to cause damage.
Unlike type A attacks the attacker launches a projectile using their own muscle power.
The combatants may be several hexes apart and still be able to damage each other.
A type B attack roll can be made once per turn (called a unit).

Examples are: arrows, bolts, rocks, quills and spit.
An anthro would use a weapon like a bow or a sling. 
An alien could have an evolved natural attack like spitting rocks or flinging quills.
A robot could use a malfunctioning peripheral that flings metal shavings.

Aliens and robots can have multiple attacks per turn with their type B attacks.
For example an alien may be able to spit three times each turn.
Or a robot may have multiple pointy things to fling at her targets.

=== Type B Weapons
These are non-powered projectile weapons.
Throwing weapons are ones that can inflict damage at a distance.
Type B weapons include: rocks, daggers, boomerangs, whips, spitting, arrows, darts, etc.

Type B weapons can attack every unit, but they cannot be used at close range.
Type B weapons are not close combat weapons.
They cannot be used on targets all up in the persona's grill (in the same hex).
Some type B weapons must be retrieved before they can be used again. 

include::ROOT:partial$CH28_Table_Type_B_Weapon_Data.adoc[]

The Wate is self explanatory.

Range represents how many hexes the weapon can fly true.
Beyond the range the weapon becomes much less accurate. 
The decay is a penalty for the attack roll with this weapon for each hex beyond it's range.
For example, an axe being thrown 10 hexes would have no penalties.
The same axe being thrown 16 hexes would have a -600 penalty.

Damage indicates the die roll that is made if the player makes a successful attack roll.
For type B weapons the damage value is increased by quarter of the persona's PSTR attribute.

== Type C Attacks
These are powered projectile attacks.
Type C weapons do not require muscle power of the user, and are just pointed at the target to cause damage.
Combatants can be quite far apart and be able to damage each other.
A type C attack roll can be made once per turn (called a unit).

Examples are: bullets, laser bolts, energy beams, and crossbow bolts.
An anthro using a weapon like a gun or a lazer.
An alien could have a naturally evolved attack like lazer eyes or gas projected bone chunks.
A robot could be a combot with a baked in gun or a construction bot misusing a nail gun. 

=== Type C Weapons
These are powered weapons.
Powered weapons do not depend on the physical strength of the attacker to inflict damage.
Type C weapons little physical effort to attack and inflict damage.
The killing forces are generated by batteries, expanding gases, springs, or other methods that are independent of the persona's PSTR.
A typical type C weapon can attack every unit without taxing the persona in anyway.

Most type C weapons are artifacts like guns or lasers. 
Mundane type C weapons are listed here.
Powered weapons include lasers, crossbows, rifles, fusion guns, death rays, machine pistols, etc.

include::ROOT:partial$CH28_Table_Type_C_Weapon_Data.adoc[]

The Wate is self explanatory.

Range represents how many hexes the projectile can fly true.
Beyond the range the projectile becomes much less accurate. 
The decay is a penalty for the attack roll with this weapon for each hex beyond it's range.
For example, a small crossbow being shot 10 hexes would have no penalties.
The same bolt being shot 28 hexes would have a -375 attack roll penalty.

Damage indicates the die roll that is made if the player makes a successful attack roll.
For type C weapons the damage value there is no damage benefit from PSTR.

== Type D, E Attacks
These are powered projectile attacks.
Type D and E attacks do not require muscle power of the user, and are just pointed at the target to cause damage.
Type D and E attacks are the same as type C attacks but with extra attacks each turn.
Combatants can be quite far apart and be able to damage each other.
Type D attacks get two attacks per turn.
Type E attacks get three attacks per turn.

Examples are: bullets, laser bolts, energy beams, and crossbow bolts.
An anthro using a weapon like a fission or plasma rifle.
It would be unusual for an alien to have a type D attack type.
Aliens tend to have multiple attacks of type A, B or C. 
A robot with type D or E attacks usually has a baked in weapon that functions like a fission or plasma gun.

== Type F Attacks
These are powered attacks that are fully automated (F stands for fully automatic).
Type F attacks are almost always weapons.
In EXP full auto weapons are often referred to as flotto weapons
These powered weapons do not require muscle power of the user, and are just pointed to cause damage.
Combatants can be quite far apart and be able to damage each other.
A type F weapons functions as a type C attack.
Type F weapons spray projectiles delivering lots of damage or none at all.

A typical type F weapon will disgorge 15 rounds per trigger pull. 
The player makes 5 attack rolls each time they pull the trigger.
For each attack roll that scores a hit the target will be hit with 0-3 rounds (1d4-1).
Each round then delivers damage to the target.
Type F attacks are usually spray and pray weapons. 

Examples are: machine gun, Gatling laser rifle, or machine pistol.
It is very unusual for an alien to have an evolved type F attack.
However tool using aliens could arm themselves the same as anthros.

NOTE: *Weapon Type F was formerly called Weapon Type Special*

=== Type D, E, and F Weapons
These are powerful artifact weapons that are created using the TOYS.
There may be some mundane rapid firing weapons.
That would depend on the milieu that the referee has created. 

== Type AOE Attacks
These are area of effect (AOE) weapons. 
Type AOE weapons do not need to contact the target to cause damage.
These weapons typically explode and  damage everything in their area of effect (AOE). 
The to hit roll is made against a location and not a persona.
So the player targets a specific hex to deliver the AOE weapon.
Examples are: frag grenade, napalm aerosol, or fusion grenade.

Type AOE weapons attack as type A, B or C depending on delivery method.
Type A AOE would be a suicide vest.
Type B AOE are thrown at the target hex (hand grenade).
Type C AOE are shot at the target hex (grenade launcher, or aerosol).

=== Type AOE Weapons
Most area of effect weapons are powerful artifacts created using the TOYS.
There are some mundane area of effect weapons. 
These are all type B AOE weapons and are thrown by the persona.
These weapons are volatile and can lead to self harm.

==== Fabrication
Each mundane area of effect weapon must be constructed by a mechanic.
These weapons cannot be fabricated during combat.
The mechanic must make a successful DD7 Performance Roll.
A critical failure could lead to detonation during construction.
Detonation during construction can cause nearby mundane AOEs to detonate as well.
Grab those Sphincter Dice.

==== Activation
Each device takes one unit of preparation before a to hit roll can be made.
This preparation time could be lighting, shaking or twisting. 
A attack roll is made like any other type B attack.
The attack roll is not against a persona target but a specific hex.
Grenade misses are detailed in xref::CH30_Area_of_Effect_Weapons.adoc[area of effect combat]
The player can only use the bonus proficient if her persona is proficient with grenades.
So most personas will only be able to add their bonus non-proficient to the grenade to hit roll.
Using one's BNP makes improvised grenade devices even more dangerous.

==== Detonation
No one really knows what will happen when the device is thrown.
The below values are taken from the attack roll.

.*AOE and attack roll (without BP)*
* 000-042 Detonation in hex of thrower
* 043-200 No detonation, may be thrown back
* 201-599 Ineffectual detonation or destroyed
* >600 Target hex hit boom.

include::ROOT:partial$CH28_Table_Type_AOE_Data.adoc[]



