= Armour Rating

The armour rating (AR) s a universal measurement of how difficult something is to hit.
Armour Rating (AR) is not solely a measure of worn armour or hide thickness.
The armour rating is a collection of hide, dexterity, worn armour and luck.
The armour rating represents a single number that determine how difficult a target is to hit and damage.
Players need to score a to hit roll higher than the target's armour rating to do damage.
Referees need to score at to hit roll higher than the persona's AR to do damage.

.*Elements of Armour Rating*
. Naked Armour Rating
. Armour Adjustment

== Naked Armour Rating
Calculation of armour ratings for each of the family types.
This is the persona's armour rating wearing no protection at all. 
Armour increases the persona's armour rating and has other effects on the persona.

.Anthro AR = 500 + 6 * DEX
****
An anthro with a 15 DEX would have an AR of 590 when naked.
****

.Robot AR = 700 
****
Robots have no AR adjustment. Easy to hit, hard to kill.
****

.Alien AR = 500 + 3d100
****
Alien AR is random and unaffected by body type.
****

.Inanimate Object AR
****
If an object with no AR needs an AR go <<_inanimate_objects,here>>.
****

== Armouring 
// this is mundane armour
// artifact armour
// pull trigger on adjusting the 500 depending on restrictiveness

The protection of mundane armour is offered through simple mechanics: thicker hides absorb and distribute forces, while special surfaces deflect blows.
The persona's DEX attribute also plays an important role in a persona's defence: dodging, twisting, etc.
All of these factors are combined into one single value called armour rating (AR).
The higher the AR the better.
Stronger materials, better armour design, and superior quality of workmanship all contribute to a higher armour rating AR.

// differentiate between armour rating and armour
// armour rating is a number, armour is a thing

== Armour Parameters 

// BONUS not a flat rate

When the player is making a to hit roll she is trying to roll higher than the target's armour rating.
Like the target'
s armour rating the persona's armour rating is used when someone is trying to hit her.
If a referee persona should score a hit on a persona then that means that the referee rolled higher than the persona's armour rating.
The persona is hit, and takes damage the exact same way as any target would.

Armour types vary greatly in protection restrictiveness, and weight.
Very light, and non restrictive armour (no armour, or leather) benefit the persona by allowing her to use her DEX to her advantage.
The other extreme is cumbersome and heavy armour (plate mail, banded) which protects the persona by force absorption and deflection, and does not allow for dextrous dodging.
The Armour Rating (AR) of various armour types can be found on Table 29.1:  Mundane Body Armour
A persona wearing chain mail would have an AR of 625.
Anyone trying to hit the persona would have to roll 625, or higher, on her to hit roll to damage the persona.
An unarmoured persona would be much easier to hit, because her Armour Rating AR would be only 500.

Layering of armour is to be discouraged.
If two armour types are combined the persona will only gain protection from the higher AR, but the two restrictiveness of the two armour type are added together.

=== Restrictiveness
The next most important factor of body armour is its restrictiveness.
Restrictiveness is a rating of how badly the armour hampers a persona's actions compared to an unarmoured state.
The higher the restrictiveness, the more binding, cumbersome and generally claustrophobic the armour is.
Heavy protective armour is usually very restrictive while light evasive armour is not.
Usually the heavier the armour is, the more restrictive it is.

Armour restrictiveness is represented by a number.
The lower the restrictiveness the less restrictive it is.
An unarmoured persona has a restrictiveness of 0, while a persona wearing plate armour has a restrictiveness of 5.
Just for interest, deactivated powered armour has a restrictiveness of 15.
There is no reason why armour couldn't have a negative restrictiveness, where it actually assists the persona's movement when she is wearing it, but this armour type definitely wouldn't be found in the mundane armour chapter.
The restrictiveness of the armour can affect movement, Performance  Rolls and even armour rating.

==== Physical Strength
Sheer power can be used to reduce the restrictiveness of armour.
For every 5 points of PSTR that the persona has she can reduce the armour restrictiveness by 1.
The armour still has its restrictiveness but the persona is strong enough to power through it.
A person with an 11 PSTR wearing plate armour would reduce the restrictiveness from 5 to 3.
A persona with an 8 PSTR could wear padded armour as if she were unarmoured.
The are benefits to reducing the restrictiveness of armour.

==== Movement
The restrictiveness of armour affects the movement rate of a persona.
The more binding and cumbersome armour type is the more the persona is slowed.
Table 29.2: Movement Penalty shows the h/u penalty of armour restrictiveness.
A persona wearing studded armour would have her movement rate reduce by 2 h/u because that armour's restrictiveness is 3.
Certain personas may find that they are not able to wear certain armour types.
A persona can reduce an armour's restrictiveness with her PSTR, and this may allow her to move faster than a weaker persona wearing the same armour type.

// insert table 235

Personas with very high PSTRs create a potential conundrum for referees.
The Movement Penalty Table is incomplete in some respects because a negative restrictiveness could easily occur.
For instance a persona with a 16 PSTR, and leather armour (restrictiveness 1) would have an effective restrictiveness of -2.
Does this mean that she gets a movement bonus?
Most referees will immediately rule that there can be no movement bonus from extensions of the Movement Penalty Table, but it might be an excellent way to include the impact of PSTR on movement rates.

==== Performance Rolls
Many classes must pay attention to the restrictiveness of armour types.
Classes which require nimble actions, physical contact, or keen senses, are penalized when attempting class skills while wearing certain armour types.
This does not stop personas from wearing any armour they wish, but any class skills they pursue will be penalized.

To avoid the performance table penalty does not necessarily require removal of the entire suit of armour, but rather gauntlets, helmet or other appropriate part.
If the relevant piece is not removed, the DD of the task attempted in increased by an amount equal to the restrictiveness value of the entire suit of armour.
If a veterinarian, wearing scale mail, is trying to do a quick fix on a wounded persona she must remove her helmet and gauntlets or suffer a DD 4 penalty.
If there are further questions about DDs and performance table then refer to chapter 14, Performance Tables.

=== Armour 
An armour type's restrictiveness determines the AR DEx bonus awarded to personas when using the tactical combat system.
The theatrical'
combat system is not obligated to AR DEx bonuses, but they can easily be included.
The AR DEX bonus improves the persona's armour rating, and it makes the persona harder to hit.

An unarmoured persona receives an AR DEx bonus of six times her DEx.
Thus an unarmoured persona with a 15 DEx would increase her ARby 90.
Including the DEx bonus for a 15 DEx this persona's AR would be 590.
If the same persona were wearing splint armour (restrictiveness 3) her AR DEx bonus would be reduced to 45, and her total AR would be 695.
Highly restrictive armour reduces the persona's DEx bonus, but usually offers more protection.
Except in rare cases, being armoured will offer more protection than being unarmoured.
The following equation gives the AR DEX bonus dependant on restrictiveness.

*Armour Rating DEX Bonus (6 
Restrictiveness) x DEX*

If the persona's armour has been reduced to a negative restrictiveness (due to PSTR) it is up to the referee to decide whether she can get more than 6 times her DEX in AR bonus.
According to the equation armour with a restrictiveness of-2 should get 8 times DEX added to it.
Most referees, being sane and rational people, will not allow Armour Rating DEX bonus to exceed 6 times the persona's DEX.

=== Wate
The wate of armour is excluded from the persona's wate allowance if she is wearing it.
Armour is designed for combat movement and its wate should be properly distributed over the entire body.
Only if the armour is carried is its wate added to the persona's wate allowance.
Armour wate is listed on Table 29.1 as either general or designer.
The general armour wate simply indicates the wate of the suit of armour in kg.
According to the general heading, a suit of leather armour would have a wate of 3 kilograms.
The general heading is the basic wate of all suits of armour for that type.
It is independent of the size of the persona, and can be used when armour wate is desired quickly.
The designer heading gives the % of body wate that the armour should weigh when suited to a particular persona.
This means that armour will vary according to the individual wearing it.
If a persona whose wate is 83 kg were to have a suit of banded armour (10% body weight) made for her, the armour would weigh 8.3 kgs.

:art: armour_rating_burning_tail.png
:width: 250px
:snark: Comnining protection, agility and luck.
:artist: Andrew Brechin
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

== Mundane Armour Types
A brief description of the composition, advantages and disadvantages of each armour type is listed below.
This may aid referees and players in deciding if armour is flammable, buoyant (hah!), edible, repairable, etc.
The list is arranged in order of lowest to highest armour rating.

The ref may alter the composition and weights of these armour types according to the scenario at hand.
The detailed technical information is listed on the armour table in this section.

=== None
 No armour, civilian dress or daily attire.
This armour type has no movement or restrictiveness penalties and grants the maximum DEX bonus, but it also has the lowest armour rating.

=== Furs/skins
 Classic Neanderthal wear.
Composed of layers of uncured and unpreserved animal hides.
This armour type is very inexpensive, but loses its composition as it rots.

=== Leather
 This is the preserved hide of some thick-skinned animal.
Leather armour is light and non-restrictive.

=== Padded
 Two layers of leather armour sandwiching some from of stuffing.
All materials are sewn.

=== Studded
 Padded armour with metal studs connecting the two pieces of leather.

=== Ring
 Padded armour base, with large rings draped on the outside.
This is NOT chain mail.

*Scale:* Padded armour with metal strips (or scales) hung loosely on the outer layer of leather.

=== Cured hide
 A thick animal hide hardened by curing.
This armour has low restrictiveness.

=== Plant Fibre
 Material woven from preserved cellulose.
This armour is light and not very restrictive.

=== Chain
 A suit composed of many small interlocked rings.
This is separate from ring mail, which is composed of loose metal rings.

=== Splint
 Strips of concrete or hardwood affixed to a padded armour base.
Can be restrictive.

=== Banded
 Overlapping metal strips fastened to cured hide.

=== Plastix
 Any synthetic (Kevlar, fiberglass, plastix) composition arranged in sheet form.
This armour type has a high armour rating, but is light and non-restrictive.
The plastic listed here is higher tech, modern body armour.
It is not the same as the artifact Plastix armour.

=== Plate
 A single, large metal breastplate covering a suit of padded armour.
Very, very cumbersome.

=== Plate Armour
 Covering the torso and limbs with pieces of interconnected metal.
This armour type is extremely cumbersome and extremely restrictive.

// insert table 233

== Helmets and Gauntlets
It is expected that helmets are composed of the same material as the suit of body armour.
Padded armour would have a padded hat, etc.
Helmets are designed to protect the head, but at the same time they hinder a persona's hearing, field of vision and occasionally her sense of smell.
Because of these sensory reductions, many classes won't perform their class skills while wearing helmets.

The gauntlets (gloves) that are included with a suit of body armour are composed of similar materials.
For example, chain mail would have an intricately woven ring material covering the hands.
Players and referees must remember that gauntlets are very restrictive to the hands.
Imagine, for example, trying to unlock your car door while wearing a hockey glove.
The ref must consider whether or not artifacts are designed to be handled with a mailed fist.
Considering this, there are also some class restrictions for wearing gauntlets.

== Shielding
Shielding is any non-garment device used to reduce the chance of being hit.
Shielding usually deflects blows or reduces exposed surface.
In the tactical combat system, many weapon types can aid a persona's AR if properly used.
Before any device can be used as shielding, the persona must take proficiency in that shield type.
This means that a persona with three proficiencies would only have two after choosing a shield for shielding.
Contrary to some opinion, the ability to use a shield is not innate and trivial, but rather an acquired ability.


// insert table 234

=== Shield
 This consists of a piece of metal, wood, or some other material attached to one arm.
The shield caw be used for deflection, cover and deception.
A shield hand cannot be used for anything other than manipulating the shield.
Shields are useful against all weapon types.

=== Net, cloak
 Any strong sheet that can be easily manipulated by one hand.
this device primarily entangles an incoming attack.
This shielding type can be used against all weapon types.
Type A weapons can also be disarmed with proper use of a cloak or net.

Chain, pipe, stick: Any pole or flexible tube about half a meter in length constitutes this shielding type.
This shielding is designed to block type A weapon attacks, and is ineffective against weapon types B or C.

== Paying For, Fitting Up, Putting On and Maintaining
Any armour bought by the persona will fit.
Armour found while adventuring, or scavenging unlucky personas, will not necessarily fit.
Before armour can fit it must meet two criteria.
First, it must be designed for the same basic body shape of the persona (not for a four armed avarian tripod).
Second, it must be made for a body wate within 15% of the new owner's wate.
Thus a persona with a wate of 70 kgs could wear armour designed for a previous owners with wates between 59.5 and 80.5.
If a persona insists, on wearing armour that doesn't fit, increase its restrictiveness.

Suiting up for battle is very time consuming.
The more restrictive the armour type the longer it takes to put on the armour.'
A good rule of thumb is 1.5 minutes per point of restrictiveness.
A suit of chainmail would take about 8 minutes to put on.
This rule should only be applied whenever time is &8220;running out&8221;.

Well maintained armour should never wear out.
To keep armour well maintained, it should be kept out of inhospitable environments (acid bath es, combat, fires, vacuums, etc.), and tended to after every battle.
Unattended armour will take damage.
Whatever damage that the persona takes, the armour will take also.
Armour has one hit point per point of AR.
When reduced to 0, the armour is ruined.
A suit of unmaintained studded armour could withstand 575 hit points of damage before being wrecked.
Some of the poorer personas will insist on mixing up armour types.
The combinations could involve a plastix helmet with no armour, or a metal breast plate with padded arms and studded leggings.
The only way that this armour type can be run is by employing the Hit Location table (See chapter 36).
The ref determines where the attack is going to land, and then rolls to hit against the appropriate armour rating.

== Inanimate Objects
The first thing that referees will realize is that personas like attacking things that aren't really targets.
These include door knobs, walls, windows, car wheels, and a host of other things that the referee can't possibly have prepared armour ratings for.
In light of the expected unexpected some guidelines for ad-libbing are included here.
The following tables do not reflect combat ARs, they are targeting ARs.
Hitting with these to hit rolls will still damage the target, but none of these tables can be used to increase the chance to hit opponents in combat.
The tables are for non-combat targets.
Things in the environment that are not normally struck at or shot at.
The tables below are guidelines for assigning an armour rating (AR)  to those items that typically do not have one.

// insert table 236

// insert table 237

// insert table 238
