= Robot Combat

Robots are just another persona in the tactical combat system. 
There are more similarities than differences.

:art: aikidobot.png
:width: 250px
:snark: Cyber sense say.
:artist: Patrick Redding
:date: 1990
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

== Points to Ponder on Robot Combat

.*in no particular order*
. robots were not fabricated with free will in mind
.. robot free will comes from malfunction and damage
. robots may have a fabricator type that they cannot harm
.. combots do not have this limitation
. combat is an internal computational struggle
.. control factor rolls may be required multiple times
. robot armour rating is 700 unless hardened by defences
. robots are easy to hit but hard to destroy
. robots can be defeated by means other than violence
. a robot is neither destroyed nor unconscious a zero HPS
.. demolition tables are complicated but fun
. Bonus proficient is only used for baked in bespoke weapons
.. Bonus non-proficient is used for angry peripherals 
. combot robots are like rogue tanks and are very dangerous
. ramming (requires CF roll) is different from ramming skill (offensive system)

== Fabricator Type
The relationship between a robot and her fabricator type is fluid at the best of times.
Robots cannot easily engage in combat with their fabricator type.
For a robot to intentionally harm a persona from their fabricator type would require a Control Factor Roll.
There are no https://en.wikipedia.org/wiki/Isaac_Asimov[Asimovian] three rules in EXP.
However not harming the fabricator type is a soft rule that is designed to cause confusion.

A robot may attack an entire expedition, and leave one persona alone.
Robots cannot be easily convinced, or easily tricked, to attack their fabricator type.
Players will find that referees will keep close tabs on efforts to loophole their way through programming.

Fabricator type should not be weaponized by the referee against robot personas.
A fully operational robot with no free will may be smashed to bits by angry members of it's fabricator type.
A persona robot can run away, immobilize attackers, or even fight back if a control factor roll is successful.

:art: commercial_janitorial.png
:width: 250px
:snark: I just cleaned that!
:artist: Andrew Brechin
:date: 1990
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

== Control Factor
Control Factor Rolls are required for the player to maintain control of her persona.
If the player is tasker her robot persona with actions that go against her programming a CF Roll is in order.
Control Factor Rolls can happen many times during combat.

include:ii-roll_playing_rules:CH05_Robots_Z_CF.adoc[tag=Control_Factor]

Robots are machines and their free will is an anomaly of damaged circuitry.
They were fabricated to be under the control of an owner or at least a fabricator type.
One way to defeat a robot is to restore the persona to it's fabricated servitude.

Control Factor does not allow a persona to control a robot because she is from the fabricator type.
Players can try ordering robot personas around. 
Being from the robot's fabricator type may help barking commands.
A robot persona is not an automaton and they enjoy their free will
An anthro is welcome to try and give orders to a heavy combat robot.
The player likely won't try and do that again.

In short robots are free willed and conversing with them cannot bring them under the spell of their fabricator type.

=== Spontaneous Loss of Control
Under certain conditions a robot may involuntarily revert to its utilitarian nature.
This is called loss of control, and it means the player has lost control of her persona.
This loss of control is temporary.
During this time the robot will return to it's expected fabrication role.
A cleaning robot may start to clean up combat mess instead of fighting.

What triggers a Control Factor Roll is decided by the referee and the players.
The difficulty of maintaining control is decided by the referee
For example losing control doing a simple task would be an Easy Control Factor Roll.
If a janitorial bot was used to clean a dirty bathroom.
A more difficult CF Roll may be required if the robot were asked to mess up a bathroom.

=== Priority Commands
Priority commands are specialized attacks made by mechanics with robotic skills.
Strangely worded commands can immobilize a robot by creating logical dilemmas within its reasoning circuitry.
Priority commands are the robot's version of a mental attack on the robot's circuitry.

The robot will suffer debilitating effects for the length of time 1 to 100 units in length.
While this time is appears short this is a tactical combat maneuver, and 1d100 units a lot of combat time.
Priority commands may slow the robot to move at half speed, ignore a certain weapon, or forget how to turn left.
The effect of the priority command is negotiated between the referee and the players. 

If there is no preparation as to the priority command effect try this table. 

include::ROOT:partial$CH05_Table_Robotic_System_Malfunction.adoc[]

The higher the robot's control factor the more difficult it is for a priority command to be successful.
The Degree of Difficulty (DD) of such a priority command is equal to the robot's CF. 
Referees will often have priority commands prepared for their robot referee personas.
Scenario related priority commands can come along with clues found in the milieu of the game.

=== Robot Overrides
Robotic overrides are specialized attacks made by mechanics with robotic skills.
Robotic overrides can involved strangely worded commands and mechanical interventions.
There are even specialized artifacts that assist robot override. 

Robotic overrides are like a mental attack on the robot's malfunctioning free will circuitry.
Successful robot override turns control of the robot over to the attacking mechanic.
Needless to say this would be devastating to a player persona robot.
Control lasts 1-100 hours (1d100).
The override can end abruptly freeing the robot to exact revenge. 

Robotic override on powerful robots should be part of the campaign.
The referee should have sub quests that are needed to build up the required tech and knowledge.
It would not be good game balance for high level mechs to walk around commanding heavy combots.

The minimum Performance Roll DD (degree of difficulty) should be 2 DD per point of Control Factor. 

== Robot Attacks
Some robots have no attacks at all.
Some robots have developed offensive systems. 
How does a robot with no built-in attacks damage an opponent?
This is left to the ingenuity of the player and referee.
Attacks can be as simple as running over a target, or as convoluted as mopping the opponent's face.

. Creative misuse
. Ramming
. Deadly random peripheral
. Baked in weapons

=== Robot Damage
Damage inflicted by robots does *not* follow too much physics or even faux realism.
Keep in mind that these are malfunctioning robots with malfunctioning peripherals.
In short the peripheral is not being used for what it was meant to.
This includes ramming attacks. 
An attack may still have safety programming, material variances, or other pseudo science impairing the damage

For example the excavating shovel of a robot will not necessarily crush everything flat.
It may still move a tonne of dirt, but safety mechanisms could limit it's attack ability.
Trying to crush a scampering alien is not part of the programming for that device.
The robot can still smack the alien with it's shovel, but not with 1 tonne of force.

=== Creative Misuse
Creative misuse is up to the ingenuity of the player and referee.
Creative misuse actions rarely involve attack rolls or damage.
However they can be helpful or destructive an expedition in different ways
For example, face mopping, face painting, locking a door, unlocking an airlock, turning off the lights, etc.
Familiarity with Sphincter Dice can assist in creative misuse discussions.

=== Ramming
A robot may smash itself into a target with the full intent of inflicting damage.
Both the robot and the target will will take damage from successful ramming.
If the robot can cross paths with a target on the hex mat they can make a ramming attack roll.
Ramming is considered a type A attack on the combat table.

.*elements affecting ramming*
. Control Factor Roll (if no Ramming Skill)
. Ramming surface (from fabrication)
. Relative Speeds (ramming speed)
. Relative Wates (crushy macsmushy)

include::ROOT:partial$CH05_Table_Robotic_Ramming.adoc[]

==== Relative Speed
The faster the robot is going the more ramming damage it can deliver.
Relative damage is a very Tactical Combat type of adjustment.
How much damage a robot inflicts is dependant on the relative speed of the robot and the target.

Relative speed is boring and we prefer to call it Ramming Speed instead.

==== Calculate Ramming Speed Damage
.Ramming Speed = Robot move - target move (negative if towards robot) 
****
Descriptions below.
****

If the bot is chasing a target running away the target's speed is subtracted from the robot's speed.
A robot move of 12 h/u and target move 8 h/u (running away) would generate 4 h/u of ramming speed. 
A blunt flat ramming surface would generate 1d4 damage plus 3d4 for ramming speed (total 4d4).
A successful attack roll will always generate the base damage of 1d4 HPS of damage. 

If the bot and the target are heading towards each other the target's speed is added to the robot's speed.
A robot move of 12 h/u and target move 8 h/u (charging robot) would generate 20 h/u of ramming speed.
A blunt flat ramming surface would generate 1d4 damage plus 7d4 for ramming speed (8d4).
A successful attack roll will always generate the base damage of 1d4 HPS of damage.

If the robot had a sharp protuberance the damage would be 1d10 + 7d8 for ramming speed. 
That is a damage range of 8-66 HPS. 
Ramming can be very destructive.

If the target were stationary (move of 0 h/u) the robot would have a ramming speed equal to it's move.
A robot move of 12 h/u and a target move 0 h/u (standing still) would generate 12 h/u of ramming speed.
A blunt flat ramming surface would generate 1d4 damage plus 4d4 for ramming speed (5d4).
A successful attack roll will always generate the base damage of 1d4 HPS of damage.

There are no rules for angled attacks. 
That kind of arithmetic hurts the brains of even hardened tactical combat players.

==== Relative Wate
Ramming speed determines the total damage delivered by the robot.
Relative wate takes into consideration the size and wate of the robot.
Consider being hit by a bicycle vs a dump truck.
The bigger you are the harder they fall.

NOTE: *The Crush Multiplier is only used if personas are different sizes.*

Relative wate is an optional rule.
Players that have heavy robot personas like to use it.
Players being rammed by heavy robots do not like to use it. 

==== Calculate Crush Multiplier
.Crush Effect = Robot wate / target wate
****
Cannot exceed 4 times bonus or a 1/4 penalty.
****

The damage is determined using the Ramming Speed Damage calculation.
The Crush Multiplier is determines how that damage is modified due to size difference.

If a 120 kg robot rammed a 40 kg target for 22 HPs of damage it would inflict triple damage.
Increasing damage from 22 to 66 HPS damage.
If a 40 kg robot were to ram a 120 kg target for 24 HPS of damage the bot would inflict one third damage.
Decreasing damage from 24 to 8 HPS damage.
The damage factor cannot exceed 4 times greater, or be reduced by less than 1/4.

Just for fun.
If the robot with the sharp protuberance (8-66 HPS damage) described was 4 times heavier than it's target the damage range would be a whopping 32 to 264 HPS of damage. 
Even simple ramming robots can be the most dangerous personas on the hex mat. 

=== Damage With Random Peripherals
A robot persona may have a deadly random peripheral as part of her Offensive Systems.
A player may want to use a random peripheral as an attack.
How much damage does a mop to the head do?
The referee and player will discuss and improvise some outcome for random peripheral attack rolls.
This includes attack type, damage and other effects.
If the player wants to use her robot's mop to make a mess a control factor roll is reasonable.
These deadly random peripherals are usually negotiated during robot fabrication.

Not unexpectedly EXP has a zany system for determining damage from misused random peripherals.
The system is so arcane and convoluted there is no table for it.
Total damage is determined by the robot persona's PSTR.
Dice used is determined by the robot persona's EXPS Level.

=== Random Peripheral Damage Calculation
.die roll = total < PSTR using 1 die per EXPS Level
****
So a 3rd level robot with a PSTR of 20 could use 3d6 or 2d8 or 1d12 to roll damage. She could not roll 5d4.
****

A robot with a PSTR of 9 at first level would likely choose to roll 1d8 for damage.
At second level she could roll 2d4, or 1d6 + 1d3 for damage.
At third level she could roll 3d3 etc. 
EXPS level allows the robot to inflict a better damage profile with her deadly random peripheral.

An extreme example is a 10th level robot with a PSTR of 20.
She could choose to roll 10d2 vs 2d10.
Improving her average damage roll from 10 to 15 HPS. 
Probability is fun.

=== Baked in Weapons
These are peripherals that act like artifact weapons or bespoke artifact weapons.
Which is which is determined at robot fabrication.
Combot weapons are usually baked in allowing the player to use her persona's Bonus Proficient.
When a malfunctioning peripheral is functioning __like__ a weapon the persona used her BNP.
Otherwise baked in weapons function the same as any other weapon regarding range, damage, and malfunction.

== Damaging Robots 
A hit point is a hit point is a hit point.
This means 4 HPS in damage from a feather duster is the same as 4 HPS damage from a metal pole.
Damage organic and inorganic personas is the same.
The shell and hull of a robot does not determine the damage. 
The attack determines the damage. 
Any HPS damage inflicted are subtracted from robot's HPS Total.

NOTE: *Robots get EXPS from damage. More damage equals more player control over her robot persona.*

=== Repair or Healing
Robots are not self repairing like organic personas.
For a robot to heal they would have to be repaired.
Repair for a robot returns it to it's original fabrication state which can decrease it's control factor.
A fully repaired robot is a referee persona robot that follows orders and protocols. 

It is possible for a robot to have peripherals that allow for self repair.
Mechanics highly skilled in robots may be able to repair robots without wrecking their free will.

=== Zero Hit Points
Aliens are dead at zero hit points.
Anthros are unconscious at zero hit points.
Robots keep on kicking at zero hit points, but they are a bit worse off.
When a robot's HPS Total drops below zero, it is damaged, but not dead yet.

A robot continues on through a zero HPS Total as if nothing has happened at all.
She may get a damage report or notice something working less well, but that is all.
Zero HPS Total inflicts general decay (decreased HPS Max) and system malfunction (decreased attribute) on the robot.
As the robot is damaged she her HPS Max and attributes deteriorate.

.*Effects of Zero Hit Points*
. General Decay
.. Decrease HPS Max by 10%
. Random System Malfunction
.. Decrease an attribute by 0-2 points

[quote]
____
A robot is destroyed when an attribute reaches zero (including HPS Max). 
____

==== General Decay (HPS Max)
When a robot's HPS Total drops below zero the robot will suffer a general decay.
Each general decay reduces the robot's HPS Maximum by ten percent.
Once the new HPS Max is calculated the robot continues taking damage as if her HPS Total is the new HPS Max.
Examples are needed.

For example, when a robot with 110 HPS Max is damaged and drops to a zero HPS Total two things happen.
First she has a new 99 HPS Max (10% off of 110), second her HPS Total is now 99 as well.
This continues as she takes more damage.
When she takes 99 more HPS in damage she passes a Zero HPS Total. 
The process repeats.
She has a new 89 HPS Max (10% off of 99), and a new 89 HPS Total.

This continues with HPS Max of 80, 72, 57, etc.
A zero HPS Max destroys the robot not the HPS Total. 

==== Easy Calculation of General Decay
.New HPS Max = Old HPS Max times .9
****
A robot with a HPS Max of 100 drops to a HPS Max of 90. The new HPS Total is also 90.
****

==== System Malfunction (Random Attribute)
Each time the robot passes by a zero HPS Total one of her systems is damaged.
If her sensors were damaged she could drop her AWE from 13 to 12.

Regardless of how the robot lost the HPS the system  malfunction is randomly determined.
This could roughly be considered the hit location of the damage taken.
An attacker could damage a bot's sensors, or power plant, without ever aiming for that particular part.
Each time the robot is reduced to zero HPS Total another robot system malfunctions.
Robot death, the fatal malfunction, occurs when any of a robot's attributes, including its HPS Maximum, is reduced to zero.

Depending on which system malfunctions one of the robot's attributes will be reduced.
Whenever any of these attributes is reduced to zero the robot has suffered a fatal malfunction and is irrevocably destroyed.

include::ROOT:partial$CH05_Table_Robotic_System_Malfunction.adoc[]

include::ROOT:partial$CH05_Table_Robotic_Malfunction_Severity.adoc[]

=== Robot Demolition Table
The first question that any self-respecting referee will ask is how in the hell does one destroy a robot without destroying playability.
It's called a Robot Demolition Table

include::ROOT:partial$CH05_Table_Example_Robotic_Decay.adoc[]


