= Hit Location

Hit location charts can be haphazardly used to determine the location of damage from a combat hit.
In actuality the hit location table is more suitable for determining erogenous zones than it is for determining hit locations.
It is accepted that most weapons have to hit to do damage, and hitting means contact with some part of the targets body.
Using a hit location table to determine where the target is hit is as unrealistic as it is complex.

A separate hit location table would be required for every possible position that the target could be in: leaning, kneeling, running, lying down, etc., etc.
Still more tables would be required for snake-like things, spider-like things, amoeba-like things, robots, etc.
Each of these body shapes would require a whole host of tables for different target positions.
The concept of being able to generate a specific hit location on any possible target would require a system even more elaborate than tactical combat;
the idea is pure fantasy.
Fantasy, of course, is a key aspect of role-playing games, and there definitely are instances where hit location information can be fun and necessary.
E.g., throwing a paint bomb (does it hit the eyes?);
flinging a bolo at an escaping prisoner (does it tangle her legs?);
or does the last ditch shot stop the evil professor before she pulls the switch?
(does it hit her hand?).

The hit location charts will be used mostly as a descriptive aid.
If the referee feels that she would like to add a bit of randomness to her descriptions without stopping for the detailed hit location tables, there is Table 36.4: Snap Hit Location.
The quick roll table is not very accurate, and is not recommended for important hit location rolls.

== Anthro Hit Locations

// insert table 356

== Alien Hit Locations

Hit location tables obviously can serve some purpose, but even the most rudimentary ones get into trouble with aliens and robots.
These two types of targets have no pre-defined shapes, and may even be lacking hit location parts designated on the anthro hit location tables.
Instead of indicating which body part of the target received the damage, the Alien Hit Location table indicates what purpose the hit body part has.
E.g., if an alien is hit in the locomotion, it has been hit on whatever body part was designated for locomotion (fins, legs, wings, etc.).

// insert table 357

== Robot Hit Locations

The Robotic Hit Location table is offered only as a descriptive aid.
Robots have a very unique way of taking damage, and regardless of where the robotic target is hit, the Robotic Damage table in chapter 31 will determine where the target has been damaged.
The attack may hit the robots locomotion, but it may be the engine that is damaged.
Robotic damage is covered in more detail in chapters 5 and 31, Robots, and Robotic Combat.

// insert table 358

// insert table 359

== Hit Location and To Hit Rolls

EXPs to hit roll damage  system is designed to be simple and fast in play.
The personas can move and attack in every combat unit, and when they attack they are firing on or swinging at their target with no consideration for hit locations.
Having hit locations creates an additional layer of combat bureaucracy that EXP probably could not support.
When a player insists on having her persona attack a targets specific body part remind her that the damage will be the same regardless of where she hits.
This will usually negate the desire to hit a target in the head, or whatever.
Conditions warranting select hit locations can certainly occur.
There maybe a target wearing various armour types, and the persona may wish to hit one of the weaker parts.
The hit location is generated on the appropriate hit location table, and the to hit roll is made against the armour type on that body part.
It is expected that if the persona is trying to hit a weakness on the target, the target is trying to defend against the weakness just as much, and the random hit location roll represents this.

=== Bonus Proficient Hit Locations 
If hit locations are still required, and the players are demanding more control over what they hit then consider this simple system.
If the player scores a hit on the target  the player then makes a roll on the Hit Location Table.
She can then adjust her  roll on the Hit Location Table by her Bonus Proficient (BP).
A persona that has a Bonus Proficient (BP) of 141 scores a hit on her target.
The player rolls 241 on the Hit Location Table.
Normally that would be the targets groin.
The player could then choose a Hit Location adjusted by her BP.
With Bonus Proficient of 141 she could adjust the hit location to any body part between 100 to 382.
This means that she can now choose to hit the knee, thigh, hip, groin, or abdomen.
This will not affect the damage generated, but it may allow her to hit the target.
If the target has no armour on her legs, but heavy armour on her stomach then she could choose to make a to hit roll against the lower AR increasing her chance to inflict damage, but not the amount of damage inflicted.

== Hit Location and Damage

There are no damage adjustments for hit locations.
All that is indicated by the hit location tables is that a majority of the damage was sustained by that body part.
Hit locations are not officially part of the combat system.
They do not affect damage in any way.
A hit to the head, as determined by the hit location tables will be nothing more than a hit to the head.
The HPS damage rolled after the successful to hit roll will be the damage inflicted.
The fact that the hit was delivered to the head makes no difference.
If the combat system has determined that 11 HPS of damage has been taken by the target then the target will subtract 11 HPS of damage from her HPS Total, regardless of where the hit is located.
Hits that do extra damage are called critical hits, these are discussed in http://expgame.com/?page_id=275[Chapter 16: Special Rolls].

