= Hit Location

[quote]
____
*That's gonna leave a mark. Right there.*
____

The tactical combat system is not designed with hit locations in mind.
However it can be easily incorporated. 
Hit locations do not alter the damage delivered to the target.
So a hit to head that delivers few HPS in damage is a grazing shot.
However a hit to the foot that delivers many HPS in damage represents a seriously injury to the foot.

Hit locations can be used for story details.
Hit locations can be used to determine if partial suites of armour are effective.
Hit location can be used to determine what body part gets splatted with a paintball.

The hit locations are tremendously inaccurate. 
A less faux realistic hit location system would require a different chart for every angle of attack.
No one here is going to be making those tables.
Simple differences for attacks to the front or back of the target.

== Snap Hit Location 
This is a cross family table to quickly indicate where a successful attack roll landed on the target.
The Snap hit location chart can be used mostly as a descriptive aid.
It is fast and can eventually even be memorized. 

include::ROOT:partial$CH36_Table_Snap_Hit_Location.adoc[]

== Anthro Hit Locations
Use this table when the referee or players need to know where a successful attack roll lands.
Obviously this only applies to anthros.

include::ROOT:partial$CH36_Table_Anthro_Hit_Location.adoc[]

== Alien Hit Locations
Alien hit location is more challenging. 
Aliens are called Diversidae for a reason.
Sometimes the indicated hit location does not even exist on the alien.
Improvisation or post factualization 

include::ROOT:partial$CH36_Table_Alien_Hit_Location.adoc[]

== Robot Hit Locations
This is a purely descriptive hit location chart.
Robot hit location is different from robot damage location.
This chart simply describes where a hit landed. 
The system damaged is completely different.
For example, a descriptive hit location on a robot may be the sensors.
However the system damaged may be completely different. 
Robots are easy to hit and hard to destroy.

// insert table 358
include::ROOT:partial$CH36_Table_Robot_Hit_Location.adoc[]


== Hit Location and Attack Rolls
The player's attack roll considers some obvious elements and attributes the unknowns to a random roll.
This random roll (kilo die attack roll) takes into account, angles, dodging, velocity, etc.
The tactical system is already complex enough. 
Attack rolls plus hit locations adds a layer of combat bureaucracy that the system may not support.

=== Adding Hit Location Anyways
One untested, but discussed, option would be to allow hit location shifting based on Bonus Proficient.
This would only be allowed for combat vocations like: mercenary, knite, and spie.
A successful attack roll is followed by a roll on the appropriate hit location table.
The player can move the hit location up or down the table depending on her BP.

This works easiest for anthros. 
If the player rolls 800 on the anthro hit location (Forearm) and has a BP +150.
She could choose to hit anywhere from the Pectorals (650) to the Shoulder (950).
Thus allowing her to shoot a gun holding hand or a body part lacking armour.

For aliens and robots the BP is divided by 10 to work on their hit location charts.
It would be reasonable for a referee to limit hit location targeting for unknown robots and aliens.

== Hit Location and Damage
The player's damage roll considers some obvious elements and attributes the unknowns to a random roll.
This random roll (various dice) takes into account, angles, dodging, anatomy, etc.
The tactical system is already complex enough. 
Damage rolls plus hit locations adds a layer of combat bureaucracy that the system may not support.

There is no system that takes hit location and damage into account for EXP.

