= Inatmo Vehicle Combat

This section is dedicated to the complexities that vehicles add to the tactical combat system.
Inatmo refers to any vehicle based combat that takes place planet side.
For space vehicle combat jump over to xref::CH38_Space_Vehicle_Combat.adoc[Exatmo Vehicle Combat].

Before destroying vehicles in combat it is recommended to know how to create them. 
xref:iv-hardware:CH54_Vehicles.adoc[Inatmo Vehicle creation]. 

Inatmo vehicle combat is not a complete vehicle combat system. 
This section covers the most common interactions that take place during vehicle combat. 
Inatmo vehicle combat is cinematic vehicle combat and is persona centered.
It is intended use when lethal personal combat is combined with driving.

This section is not for expeditions driving from one place to another. 
Nor is this section for persona's piloting their vessels recklessly.
Non-combat driving shenanigans are covered in the xref::CH17_Driving.adoc[Driving Section]. 

:art: vehicle_combat_trick_moves.png
:width: 250px
:snark: Seatbelts please.
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The complications of vehicle combat will require many snap judgement calls by the referee. 
Does wind affect my lazer rifle?
My persona hunted flying womp mice this should be easy!
Can our supersonic vehicle outrun a sonic pistol attack?
The rules presented here are just guidelines, as all rules are, and common sense and fun should prevail.
Most players will be quite adamant in their beliefs about vehicular combat because most of us are so familiar with cars.
Above all have fun.

== Attacking A Vehicle
Damaging a vehicle requires a to hit roll against the vehicle's armour rating (AR).
If the player rolls higher than the target vehicle's armour rating then her persona has damaged the vehicle.
A vehicle's armour rating depends on its structure and its speed.
Unless the vehicle has been given a special AR when it was randomly generated, its base armour rating is 500 

// vehicle AR

=== Armour Rating
500 would be the AR of a parked non-military vehicle.
A parked vehicle offers nothing more than cover to the personas.
A hardened combat vehicle may have a higher base armour rating.
The vehicle's AR increases by 5 for every h/u of speed that it has.
This armour rating (AR)  adjustment for speed is not relative.
If a car is travelling at 50 h/u then its armour rating is 750 regardless of whether it is being fired on from another vehicle travelling 50 h/ u, or from a stationary attacker.

*Vehicle Armour Rating = Base Armour Rating (500) plus 5 per h/u of Speed*

=== Driving Skills
Driving skill is rare, but it can increase the AR of the vehicle by 1 point of armour rating per h/u per point of skill.
So if a vehicle were being driven at 50 h/u by someone with driving 1 (plus 5 per h/u of speed), the car's AR would be 800.
This simple adjustment takes into account all the exciting swerves and maneuvers.

=== Weapon Restrictions
The armour rating of many high speed vehicles will make them impossible to hit with most weapons.
Trying to hit high speed vehicles requires specialized weapons that can compensate for speed The armour rating adjustment will also make it impossible for combat between vehicles if they are travelling too fast.
This may not be as much fun, but it is intuitively logical that inter-vehicle combat cannot be possible at higher speeds.
If a vehicle is specifically designed for high speed combat it will have weapons that compensate for the added velocity.

There are also weapon type restrictions depending on the speed of the target vehicle.
A type A weapon is ineffectual against a vehicle moving more than 20 h/u.
Personas that still try to attack a moving car with a club will risk personal injury.
Type B attacks can be used against vehicles at the referee's discretion.
Any powered attack that scores a hit on a vehicle can damage it.

=== Flanking Attacks
A vehicle's AR is determined by its velocity;
the armour rating is unaffected by the location of the attacker relative to the target.
Regardless whether the attacker is attacking from directly in front of the vehicle, from the side of the vehicle, or even from above the vehicle the attacker is still subject to the displacement effects which create the vehicle's armour rating.
The anthropomorph eye simply cannot compensate for the rapid change in position regardless of its vantage point.
When an attacker is so distant from a vehicle that movement is imperceptible, the attacker must remember the movement is still there, and for high velocity vehicles most personal attacks would be out of range.

== Location of Vehicle Damage
A successful to hit roll on a vehicle will damage it in a random location.
This is done the same as hit location for space vehicles, for robots, and for organics.
The player makes a roll on Table 39.1: Location of Vehicle Damage to determine which part of the vehicle has been hit.
The attacker cannot choose which part of the vehicle she is going to hit, and every hit will be on a random location.
Random hit locations are used because the vehicles are randomly generated and are remarkably varied externally.
The architecture of the component systems in vehicles is unknown also, and a random location for hitting is the easiest way.

// insert table 369

=== Targeting Components
Quite often attackers will want to choose their targets on vehicles.
They may focus their attack on a car's wheels, or the undercarriage of an antigrav vehicle.
Remember that there is no evidence that the construction of any such vehicle is the same as our present day cars.
Engines won't always be in the front, the fuel won't always be in the back, and the tires might be just for landing, and not locomotion.
Not only will the construction of the vehicle be alien, so will its components.
A hit in one spot might be deflected, conducted, or absorbed in another spot, damaging an entirely unexpected component.
Personas that are skilled in vehicular combat, and are very familiar with the vehicle that they are attacking may be allowed to adjust their hit location on the Location of Vehicle Damage table.
The adjustment should equal their BP with the weapon being used divided by 50.
Thus a persona attacking a vehicle with a BP of 295 could adjust her hit location up 6 points or down 6 points on the Location of Vehicle Damage table.
She can also add her vehicle combat skill to the adjustment.
Thus a deci-die roll of 62 (acceleration) could be adjusted up to 68 (still acceleration), or down to 56 (speed).

=== Targeting Passengers
One exception to the ineffectiveness of targeting is when the attacker is attempting to hit the passengers.
Passengers are usually easy to identify inside an unsealed vehicle, and directing an attack against them makes sense.
Passengers, including the driver, are difficult to hit in a moving vehicle.
The attacker must first hit the vehicle before an attempt can be made to a passenger.

=== Random Passengers
If the hit location rolled indicated that the passenger cabin has been struck (Cargo hold usually), then the attacker can make a to hit roll on a random passenger in the vehicle.
So the attacker must first get their attack on target and hit the moving vehicle.
If that attack goes into the passenger zone of the vehicle then they may make a to hit roll against a random persona in the vehicle.
In most passenger vehicles the cargo hold represents the passenger area since the passengers are the cargo.
If the weapon has an area of effect it will function just like any other area of effect weapon on all the occupants within range.

=== Specific Passenger
If the attacker wishes to direct fire at a specific passenger, usually the presumed driver, then they must have some kind of vehicle combat skill or extraordinary luck.
A specific passenger must first be visible, otherwise the target is enjoying complete concealment and sometimes complete cover.
The attacker must first score a hit on the vehicle's speed adjusted armour rating.
If that is successful then they must score a hit against the specific persona's cover and speed adjusted armour rating (AR).
An unlikely hit indeed.
A miss on at specific passenger targeted attack does not damage the vehicle or the targeted persona.

== Extent of Damage
Once the hit location of the successful attack has been determined the amount of damage is determined on the extent of damage table.
Vehicles do not have hit points, and their essential components are damaged until they are destroyed.
Table 39.2, Extent of Damage determines how badly the component has been affected by the hit.
The component may only sustain trivial damage, which doesn't affect performance at all.
Or the component may sustain  critical damage where it is reduced to 30% of its previous performance.

The percentile roll made on the Extent of Damage table is increased with the severity of the attack by adding the damage to the die roll.
If an attack were to do 15 HPS of damage to the locomotion, maybe the anti-gray plates, the decidie extent of damage roll would be increased by 15.
There are no adjustments for velocity of the vehicle affecting the damage of the attack.
A random die roll on the Extent of Damage table decides how dangerous the attack was.
A high velocity vehicle may take more damage from an attack because of the increased relative velocity of the projectile.
This effect is determined by the extent of damage roll, and nothing else.
High speed air currents can cushion blows, and ricochets can deflect attacks just as easily (well maybe) as a the high velocity could increase damage.
There are simply too many parameters and possibilities to include, so a random table must suffice to cover such eventualities.
For a detailed explanation of extent of damage refer to chapter 21, Equipment Damage.

=== Big Damages Small Vehicles
Attacks that inflict enormous amounts of damage should justifiably inflict more damage than those attacks that inflict small amounts of damage.
This is reflected in the HPS adjustment to the Extent of Damage table.
If this adjustment isn't enough, use of the table can be adjusted to include multiple hit locations for a single attack.
For instance a fusion attack could legitimately damage every component on the vehicle, and not just destroy a single component.
A single attack can roll once on the table for every 75 hit points in damage, adding no more than 75 to the die roll.
Large vehicles, and damage hardened vehicles (military ones) may be exempt from this type of vehicle damage.
Thus a single attack that inflicts 230 HPs in damage to the vehicle would make 3 rolls at +75 and one roll at +5.
So much for that vehicle.

// insert table 370

=== Effect of Damage
Whenever an vehicle component is damaged anything can happen.
The component may be trivially damaged, where there is no reduction in efficiency, or the component may be critically damaged where there is a reduction to 30% of previous performance.
If a vehicle's locomotion (speed) was 20 hexes per unit, and the locomotion component suffered major damage (60% previous) the maximum speed would now be 12 h/u.
And it would remain at that maximum speed until repaired.
If  destroyed (less than 10% function), the vehicle would cease to move.

=== Destroyed Systems
A vehicle system is considered destroyed once reduced to 10% of its full performance.
From a practical standpoint the mechanism may become useless long before it reaches 10%.
The effects of a disabled, or destroyed, mechanism are detailed on Table 39.1: Location of Vehicle Damage.

=== Cumulative Destruction
The damaging effects of successful attacks are cumulative, and a system can be destroyed over several attacks.
If a device were to take major damage (60% performance), and then major damage (60% reduction) again its effective level of function would be 36%.
A further critical damage (30% performance) would reduce the part to 11% of its previous performance.
At this point even trivial damage (90% performance) would disable the component.

=== Instantaneous Destruction
If something is destroyed by a single attack (0% previous performance) the device is considered damaged beyond repair.
The effects of instantaneous destruction are cataclysmic.
A destroyed locomotion system would destroy the engine, power system and locomotion.
There is no chance for repair, and replacement parts will be required.

=== Modifying For Fun
If the referee and players find that this extent of damage adjustment is destroying their vehicles too quickly then modify it to have more fun.
Eliminate the HPS Extent of Damage modification.
Allow the vehicle's armour rating to reduce the extent of damage.
Regardless of what ruling the referee uses to reduce the damage effect of the attack it should be done only to keep the game fun for everyone.
If a rule gets in the way of having fun then change it.

== Vehicle to Vehicle Combat
Vehicle to vehicle attacks require the most concentration of all.
The persona is not only attacking a moving vehicle, but she is firing from one.
Previous rules considered what happens when an attacker is attacking a moving vehicle.
When a persona is attacking from one moving vehicle at another moving vehicle she does not suffer combined attack penalties.
The to hit adjustments of the faster moving vehicle will be applied to all personas either shooting from or shooting at the faster vehicle.
Vehicles moving at the same speed have a relative velocity of 0, however the vehicle's armour rating will still include the speed adjustment.
The speed adjustment still applies because the inherent speed of the vehicle complicates to hit rolls: wind resistance, vibrations, and high speed evasive maneuvers still affect the to hit roll.
Speed related weapons restrictions are applied with the fastest moving vehicle (not relative speeds) so type B weapons will not work between two vehicles both traveling at 25 h/u.

== Area of Effect Attacks
Area of effect attacks (grenades and aerosols) must first roll to hit the  vehicle's speed adjusted armour rating.
The speed adjusted armour rating applies to grenades thrown from a vehicle as well.
The vehicle's speed adjusted armour rating is used regardless of the direction of the attack.
The referee may grant some bonus to personas that are attacking a vehicle that is directly behind the attacker.
This roll ensures that the attacker has correctly compensated for the displacement of the moving vehicle.
Unlike close in regular hand grenades a vehicle that has been missed cannot be damaged by a grenade.

A hit on the vehicle will allow the attacker to roll for a regular area of effect attack as 

The grenade miss table functions the same except that the target hex will be as far away as the vehicle has traveled in the unit.
So if the persona misses with a grenade toss in a vehicle moving at 25 h/u the grenade will detonate 25 hexes behind the vehicle.

== Driving PT Check
Whenever  a vehicle is damaged the driver may be required  to make a driving performance table roll.
It is assumed that the driver will face some kind of challenge maintaining control of the vehicle after it has been damaged.
Any vehicle damage that affects the performance of the vehicle will require a driving performance table check.
The player must roll against whatever maneuver her persona is doing, plus an adjustment for the severity of the damage.
So if a system is critically damaged it may even be difficult to drive the vehicle in a straight line.
Use Table 39.3: Vehicle Damage and DPT Adjustment to determine the final DD on the driving performance table.

// driving PT Roll

If a driver were executing a two facet (90°) turn, and her vehicle took major damage to the locomotion she would have to make a DD 12 performance table roll.
The higher the degree of difficulty the more likely the persona will lose control of the vehicle.
The Driving Performance Table can be found in http://expgame.com/?page_id=277[Chapter 17: Driving].

:art: lady_lazer.png
:width: 250px
:snark: Rear gunner.
:artist: Alex Schumberg
:date: 1948
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

== Attacking From A Vehicle
Personas attacking a stationary target from a vehicle are subject to the same displacement problems that high speed targets have.
A to hit roll launched from a moving vehicle will suffer a penalty of -3 per h/u per h/u if the vehicle speed is greater than 20 h/u.
Thus an attack from a vehicle travelling 25 h/u would suffer a penalty of -75 to hit.
If the vehicle is traveling at 15 h/u then there would be no to hit roll penalty.
Often personas will suffer several to hit roll penalties at once.
If the player is making a reasonable case to have a chance to hit the referee should offer the player a reasonable chance to score a hit.
However this reasonable chance to hit should only be allowed under reasonable circumstances.

== Vehicular Weapons
Vehicle weapons are those weapons built into vehicles, or weapons specifically designed to be used against vehicles.
Vehicle weapons do not suffer the same vehicle speed differential penalty.
Built in vehicular weapons have compensating gimbals, and possibly even compensatory software.
The speed adjusted armour rating is reduced by 4 points for vehicular weapons.
The normal armour rating adjustment for speed is 5 per h/u.
Vehicular weapons would reduce this to 1 point per h/u for most vehicles (instead of the regular 5).
When attacking with a vehicular weapon the armour rating of a vehicle moving 50 h/u would be 550 as opposed to the regular speed adjusted 750 AR.
Vehicle weapons are an obvious advantage in vehicular combat.

== Ramming
Surprisingly ramming has little or nothing to do with vehicular combat rules, and a lot to do with driving rules.
There are three conditions required for an intentional ram.
1) the paths of the vehicles must intersect 2) the ramming driver must win initiative 3) the ramming driver must score a to hit roll.
If both vehicles are trying to ram each other it will be instantly successful.
If a persona successfully rams a vehicle the hit will result in a collision between the two vehicles.
The effects of a collision are detailed in http://expgame.com/?page_id=277[Chapter 17: Driving].

If a driver is attempting to ram a pedestrian the driver must first make a successful to hit roll.
If ramming driver has hit the pedestrian the target will take damage as though she were a passenger involved in a collision.
The damage will be determined as if the target were a passenger in a vehicle that crashed at the speed which the attacking vehicle was moving.
The details of passenger damage are found in Chapter 17.
A vehicle is a deadly weapon in it's own right.
