// todo skilled weapons 
// todo equipment
// json to ADOC 


= Night Shadii (florian knite)

:art: RP_night_shaadi.jpg
:width: 750px
:snark: Bringing light to the dark side.
:artist: Aimagination_hugh
:date: 2023
:license: CC BY-SA 4.0
:description: muscular humanoid plant with a flower head wearing a tank top and holding a techno energy sword.

include::ROOT:partial$articulate.adoc[]

== Attributes
AWE: 8 CHA: 7 CON: 7 DEX: 14 INT: 8 MSTR: 21 PSTR: 9 HPS: 21 SOC: 173 + 
A 103 years old generalis florian knite wearing a tank top. 

== Biologic Info
Age: 103 years Hite: 171 cms Wate: 52 kgs + 
MUTATIONS None

== Role Playing Cues
Arc: Past: Nearby, Present: Curious and trusting, Goal: Make it to tomorrow. + 
Dress: Sports Team, Hygiene: Dishevelled, Odor: Hay + 
Personality: Lustful, Introverted + 
Labanations: Voice: Flick (Light, Fast, Indirect), Move: Glide (Light, Slow, Direct) + 
Beliefs: Religion: None, Philosophy: None, Politics: None. + 

== Combat Info
MOVE:  3 h/u  ARMOUR RATING: 542

[width="75%",cols="5*^",frame="all", stripes="even"]
|===
5+<|ATTACK TABLE: KNITE LEVEL 1

s|TYPE
s|Skilled
s|Raw
s|Max
s|Force

|*Strike*
|127
|32
|752
|5

|*Fling*
|120
|24
|770
|3

|*Shoot*
|181
|55
|856
|0

s|TYPE
s|Skilled
s|Raw
s|Max
s|Force
|===

**Proficiencies** + 
Light Sabre + 
Lazer pistol MP + 
Dagger

== Vocation Info
GIFTS: + 
1) Kirlian Sight

INTERESTS: + 
1) Physical Space-1 + 
2) Think Space-1 + 

Knite SKILLS:
1) Languages-1 + 
2) Militarization-1 + 
3) Mimic-1

== Equipment Info
14 kg for Anthro with move 3 h/u + 
Sprint (6 h/u): <3.5 kg Carry (3 h/u): <21.0 kg. Lift Max (0 h/u): 35.0kg.

Lite Sabre +  
Deflated soccer ball + 
Food culture

== PDF
PDF may not match this description exactly. 





== JSON
The below json will work with the https://github.com/mobilehugh/EXP_Game_Tools[EXP Python Tools] and was Created: Wed-20-Dec-2023(15:43) for Hugh 
[source, json]
----
{"Player_Name": "hugh", "Persona_Name": "Night Shadii", "FAMILY": "Anthro", "FAMILY_TYPE": "Florian", "FAMILY_SUB": "Generalis", "Fallthrough": true, "Bespoke": false, "RP": true, "RP_Cues": true, "Bin": false, "AWE": 8, "CHA": 7, "CON": 7, "DEX": 14, "INT": 8, "MSTR": 21, "PSTR": 9, "SOC": 173, "HPM": 21, "WA": 14, "AR": 542, "Move": 3, "Age_Spans": [], "Age_Cat": "Older", "Age": 103, "Age_Suffix": "years", "Size_Cat": "Medium", "Hite": 171, "Hite_Suffix": "cms", "Wate": 52, "Wate_Suffix": "kgs", "Quick_Description": "A 103 years old generalis florian knite", "RP_Fun": ["Arc: Past: Nearby, Present: Curious and trusting, Goal: Make it to tomorrow.", "Dress: Sports Team, Hygiene: Dishevelled, Odor: Hay", "Personality: Lustful, Introverted", "Labanations: Voice: Flick (Light, Fast, Indirect), Move: Glide (Light, Slow, Direct)", "Beliefs: Religion: None, Philosophy: None, Politics: None."], "Vocation": "Knite", "Level": 1, "EXPS": 1500, "Mutations": {}, "Interests": ["Think Space", "Physical Space"], "Skills": ["Mimic", "Militarization", "Languages"], "Proficiencies": [], "Equipment": [], "Date_Created": "Wed-20-Dec-2023(15:43)", "Date_Updated": "Wed-20-Dec-2023(15:43)", "File_Name": "NIGHT_SHADII_anthro_florian_generalis_knite_1703087031.jsonl"}


----