= Tactical Combat


The tactical combat system is used to resolve those persona differences that negotiations cannot resolve.
The tactical combat system is much more detailed than the theatrical one, but they both are equivalent in their degree of lethality.
It is expected that anyone using the tactical combat system at least has previous experience with other role playing game combat systems.
That previous experience could be with the theatrical combat system or with the combat systems from other role-playing games.
If you have never played a role playing game before it is recommended that you read http://expgame.com/?page_id=294[Chapter 25: Introduction to Combat] before this chapter.
Every combat system has its flaws in realism and playability, but the tactical combat system is the least unrealistic, most playable system that EXP has to offer.

== Attacks and Defenses

The most important goal in the tactical combat system is to stay alive.
This is done by defeating opponents by scoring hits and removing the opponents hit points.
Attempting to score a hit depends on many factors: the attackers attributes and skill level, and the defenders combat defences.
A combat system revolves around these elements that affect an attackers chance to hit.

Attacking: An attacker generates a to hit roll by rolling a kilo-die (hence roll
to hit).
The random integer that is generated accounts for the enormous number of possibilities that cannot be accounted for on a normal gaming scale.
Armour deflection, air currents, velocities, tensile strengths, concentration levels etc., are just some examples of elements that cannot be determined on a table top role playing game.
The total impact  of these factors is so unpredictable that that replaced with randomness.
The kilodie to hit roll is a random number that pretends to account for this minutiae.
A to hit roll is made by the player every time her persona is trying to hit a target.

The higher the to hit roll the better.
The player must roll a number higher than the targets ability to defend itself.
The total ability of the target to defend itself is represented by another number called armour rating (AR).
In order for a to hit roll to score a hit the player must roll a number higher than the targets armour rating (AR).
If some alien were to have an armour rating (AR) of 580 the player would have to roll equal to or higher than 580 on her to hit roll for  her persona to score a hit.
Thus any to hit roll greater than 580 would indicate a hit.
A hit means that the target will be damaged.
A Miss indicates a non-damaging attack, and nothing more than a loss of ammunition, or a battery drain.

Defending: Dexterity, armour type, hide structure, body structure, and many other factors are collectively called the Armour Rating (AR).
The armour rating is a quantitative value that represents how difficult it is to hit the target.
The higher the armour rating the better the protection it offers.
The armour rating of anthro personas is determined mostly by their dexterity attribute and the type of  armour that they are wearing.
A very detailed  discussion of armour rating is given in http://expgame.com/?page_id=302[Chapter 29: Armour Rating].

== Weapon Types

EXP has an enormous variety of weapons.
In order to make the combat table manageable these weapons are divided into three identifiable types.
Not surprisingly each category is called a weapon type.
The three weapon types that appear on the combat table are discussed in the following paragraphs.
To the persona the weapon types are invisible.
They do not decide to use a certain weapon labelled with a C
because they have just completed physiological testing that indicates that they are faster than they are stronger.
It is only the mundane player that knows such details about her persona.
The player may role-play that her persona has a favourite weapon, which just might be one of the weapon types that her persona has the largest bonus proficient for.
An exhaustive list is included in http://expgame.com/?page_id=300[Chapter 28: Weapons].

=== Type A

These are non powered thrusting and striking weapons.
The non-powered part of this weapon type description implies those weapons that are dependent on the physical effort of the attacker to inflict damage.
Thrusting and striking weapons are those that either poke or strike their targets to inflict damage.
Type A weapons are primarily hand held, or can include the hand itself.
The list includes swords, maces, pole-arms, fists, paws, beaks, spears, etc.
Type A weapons are characteristically the slowest weapons because they are labour intensive and require special conditions to inflict damage.
They must contact with a cutting edge, or they must connect without deflection to inflict damage.
Combat time must be spent preparing each attack (spotting an opening, dodging, parrying, etc.).
Type A weapons are very dependent on the PSTR of the persona.
Personas with high PSTR will be more likely to hit, and will inflict more damage using type A weapons.
Aliens will most often have no choice but to use their natural type A abilities.

=== Type B

These are non-powered projectile weapons.
Again non-powered implies that the weapons damage depends on the physical activity of the persona.
Throwing weapons are ones that can inflict damage at a distance from the attacking persona.Type B weapons include: rocks, daggers, boomerangs, whips, spitting, arrows, darts, etc.
A more complete list of type B weapons is given in chapter 28, Weapons.
These weapons are as much dependant on the aiming ability (DEX) of the attacker as they are on the attackers PSTR.
Type B weapons can attack every unit, but they cannot be used at close range.
Any weapon that is drawn, thrown, or heaved will get a to hit roll bonus mostly by the personas DEX attribute.
Type B weapons are more difficult to use than type A weapons, because the attacker must consider additional factors such as range and movement in order to score a hit.

=== Type C

These are powered weapons.
Powered weapons do not depend on the physical strength of the attacker to inflict damage.
Type C weapons little physical effort to attack and inflict damage.
The killing forces are generated by batteries, expanding gases, springs, or other methods that are independent of the personas PSTR.
Powered weapons include lasers, crossbows, rifles, fusion guns, death rays, machine pistols, etc.
A typical type C weapon can attack every unit without taxing the persona in anyway.
Type C weapons are highly dependant on the DEX of the persona because their most important factor is how well they are aimed.
Once properly aimed and triggered the powered weapon does the rest of the work.
There are no damage bonuses for type C weapons.

=== Type D, E, F

In addition to type C weapons there can be found Type D, E, F and special.
These are also powered weapons and they are treated the same as a type C weapon.
These weapons have one important difference.
Type D weapons get 2 attacks per unit, Type E weapons get 3 attacks per unit and Type F get 4 attacks per unit.
This means that its firing mechanism is so delicate that the player gets to make multiple to hit rolls each unit her persona uses fires the  weapon.

=== Type Special

These are fully automatic machine weapons.
Special attack is fully automatic.
This means that charges, or bullets are spraying forth from the end of the weapon.
Such weapons can empty their entire ammunition stores in several units.
When using a fully automatic (Flotto) weapon the player gets 5 to hit rolls every unit.
Each to hit roll accounts for a burst of 3 rounds of ammunition.
If a to hit roll is a miss then all three rounds miss the target.
If a to hit roll indicates a hit, then between 0 and 3 rounds hit the target.
If 0 rounds hit the target then no damage is inflicted, but if 3 rounds hit the target damage is rolled 3 times.
Special uses 15 rounds of ammunition each burst.

== The Combat Table

There are components of combat that increase the attackers chance of scoring a hit on her target.
These factors are called bonuses.
The bonuses are added to the players to hit roll, which increases the chance of her persona scoring a hit.
In the tactical combat system different weapon types have different bonuses, and the personas have a limited number of proficiencies.
These bonuses are contained on a matrix that cross references weapon types and weapon familiarity.
This matrix is called the Combat Table.
Each persona has her own combat table.
The combat table is the basis of the tactical combat system.
Other factors, such as terrain, range modifiers, and meteorological effects can easily be included in the theatrical system, but the idea of the combat table cannot.
The generation of the personas combat table is outlined in http://expgame.com/?page_id=252[Chapter 9: Combat Tables].

The combat table is the players friend it represents the combination of the all the inherent bonuses that the persona get to add to her to hit roll.
Consider a third level nomad persona that has the following attributes: AWE 12, CHA 6, CON 17, DEX 15, INT 12, MSTR 4, PSTR 10 and HPS 43.
Calculating her Bonus Proficient (BP), Bonus Non-Proficient (BNP), Maximum Roll (MR) and Damage Adjuster (DA), for weapon types A, B and C;
the combat table is assembled, taking into account the nomads experience level.

[table id=230 /]

=== Bonus Proficient

Let us suppose for the moment that our nomad finds herself in a chase over frozen arctic wastes.
Occasionally she and her pursuers pause to catch their breaths and take a few shots at one another.
It so happens that our nomad is packing a 1.5 metre long harpoon used normally for spearing the Giant Arctic Sea Slug that frequents the waters below.
The nomad has used this weapon for years and happens to be proficient using it.
Suddenly one of her pursuers is within range of her weapon, and she lets fly with the wickedly barbed weapon.

The nomads player rolls a kilodie to hit roll.
Instead of calculating the personas bonus for DEX, and PSTR and EXPS Level each time she rolls, the player has an up to date Combat Table.
The persona is proficient in harpoon, so the player is entitled to add the nomads Type B Bonus Proficient (BP) of 184 to her to her to hit roll.
So the players to hit roll of an even 600 gets +184  added to it, creating a to hit roll of 784.
If 784 is higher than the targets armour rating (AR) she will have scored a hit.

=== Bonus Non-Proficient

Unfortunately for the nomad, she is now sans harpoon.
The only other weapon she has is a nasty icepick tucked into her boot.
She slides down an icy incline, trying to reach some cover.
Suddenly a second evil mercenary springs out from under the snow before the nomad can get cover.
The nomad whips out her icepick.
Knife-fighting is not the nomads forte.
She doesnt have a proficiency in icepick,
so after dodging the mercs first slash, player gets to make a to hit roll.
However the player can only add the personas Type A Bonus Non-Proficient (BNP) to the kilodie to hit roll.
She rolls a natural 500 for a to hit, adding her Bonus Non-Proficient (BNP) of 87 totals a to hit roll of 587.
This to hit roll is just greater than the targets Armour Rating (AR) of 575, and the ice pick plunges home.

=== Maximum Roll

After a knock-down, drag-out slashfest lasting several units, our nomad decides  her well-worn icepick is not good enough versus the new target.
So she decides to flee her present opponent.
In doing so, she accidentally trips over the body of her first target (the one with a harpoon stuck in his head).
While scrambling to her feet, she finds the fallen harpooned targets Extra High Powered  (XHP) Semi-Automatic (Sotto) Pistol.
By a pleasant twist of fate, it happens to be the only handgun with which the nomad has proficiency with.

Spinning on her attacker the nomad fires in the general direction of the other attackers head.
Generates a to hit roll of 852, to which she may add her Type C BP of 234, giving her a grand to hit roll of a whopping 1086.
One might expect this high to hit roll equates to instant decapitation of her taget.
However, the nomads Maximum Roll (MR) of 909 prevents the well-placed shot from being anything other than just a well placed damage inducing to hit roll success.

The players will hate, unless its working in their favour, the maximum roll.
Reasons for a maximum roll (MR) is to ensure a  differential between high and low level personas.
There are certain armour ratings that inexperienced personas will not be able to hit except under extremely lucky circumstances (see critical rolls in http://expgame.com/?page_id=275[Chapter 16: Special Rolls]).
Without the Maximum Roll (MR) the referee will find that low levels personas are could be just as successful in lethal personal combat as much higher level personas.
If there is no limiting difference between low and high level personas in combat then there is no point in having combat classes advance in experience levels.
Occasionally a persona will be unable to hit a particular target because its armour rating is too high.
This will leave some players feeling helpless and frustrated.
That would indicate that its time for their persona to run away.

The maximum roll also raises a problem of realism for the referee.
Should a persona know that she cannot hit a target?
Is it realistic for a persona to stop attacking a ferocious alien after just one failed attack?
The referee may deceive the players (for realism of course), by pretending that a maximum roll is a hit, recording the damage, but not subtracting it from the targets hit point total.
After a while the players will realize that the alien has withstood tremendous amounts of damage, but it is still being ferocious.
It is then a role-playing decision whether or not to continue the combat, or to enact a tactical withdrawal.

=== Damage Adjustment

A hit with a to hit roll means damage to the target.
Each hit delivers a random amount of damage.
When the nomad scored a hit with harpoon she inflicts 1-8 hit points (Type B weapon spear).
She also gets to add her Type B Damage Adjuster (DA) of plus 3.
So with her damage roll of 7 HPS damage would be increased to 10 HPS damage and that is what the harpooned target would take subtract from her HPS total.
When she later scored a hit with the pistol the player gets to roll 3-30 hit points of damage to the target.
There is no Damage Adjuster (DA) for Type C weapons so the HPS damage of 21 from the gun is subtracted from the targets HPS total.

== Weapon Proficiencies

Proficient means that the persona can use the design of a weapon so that it aids her in combat.
Proficiency is more similar to weapon familiarity than it is to weapon skill.
It allows the persona to hit with the edge of a sword, use the full leverage of a pike, and aim a gun in the right direction.
Each proficiency refers to a single weapon.
Thus a persona that can have 3 proficiencies can choose 3 specific weapons that she is proficient in.
If a persona is proficient in a weapon it means that her player can add her personas Bonus Proficient (BP) to any to hit rolls that she makes.
Proficiency does not increase the personas ability to score a hit by increasing her bonus proficient, but it allows the player to add her entire BP to any to hit rolls that she makes.
Combat based persona classes like nomads, spies, and knites get more proficiencies that non-combat classes like mechanics, biologists and nothings.

Personas are not automatically proficient in all weapon types, and they must choose them carefully.
For example, being proficient with a laser may be really fun until its batteries run out, and in the long run a crossbow proficiency may have been a better choice.
What weapons a persona is proficient in is completely determined by the player.
Weapon proficiencies need not be chosen all at the same time, and the player can wait until the right weapon for her persona comes along.
The number of weapons that a persona can be proficient in is limited, and is dependant on her class.
Combat classes start with more proficiencies and learn new ones faster, while non-combat class personas will become proficient in very few weapons.

*Initial Proficiency*: Each persona has an initial number of proficiencies when she starts at first level.
The number of proficiencies is determined Chapter 9: Combat Table.
Each proficiency represents familiarity with one particular weapon.
According to this Table 9.7: Weapon Proficiencies a nomad could be proficient in up to non powered missile weapons (type B weapons), and one type A and one Type C  weapons at first level.
She does not have to choose all three of these proficiencies in first level, and in the case of type C weapons the persona may not even encounter them.

*Acquiring More Proficiencies*: If the player chooses that her persona is proficient in a particular weapon then she simply records it on her persona record sheet.
The player may find that 3 non-powered weapons arent enough proficiencies for her nomad, because she has encountered some additional weapon that she would love to be proficient in.
The player can add new proficiencies as her persona increases in experience levels.
If the nomad described earlier had used up all her proficiencies for type A and B weapons then she would have to wait until 3rd level before she can add another non-powered weapon proficiency.
The number of initial proficiencies, and the intervals that new ones are added are listed on the Table 9.7: Weapon Proficiency table.

== More Tactical Combat

Tactical combat is not just a complex combat table that the players use to keep track of their persons bonuses to hit.
All the remaining chapters in Section 3: Combat Rules are devoted to tactical combat.
There are many more complications that can make to hit rolls more, or less, likely to succeed.
Tactical combat also includes  initiative rolls, detailed movement rules, and copious to hit adjustments.
For many play groups the Combat Table is more than enough tactical
combat.
As with all rules in EXP they are written to have more fun with role-playing and tactical combat has the most rules that can be ignored without hurting role playing.
