= Chapter 28: Weapons


This chapter is devoted to everything you ever wanted to know about non-powered weapons, but were too smart to ask.
The weapons discussed are primarily type A and type B weapons.
These are the generic hand to hand combat weapons that almost any anthropomorph tool users would be expected to use.
The referee's milieu should designate what kinds of weapons are available, and which are not.
As stated earlier these are generic non-powered weapons.
These are the mundane weapons of personal combat that have been made famous by popular media.
The weapons are discussed by type covering each weapon type's peculiarities, and the particular weapons that fall into each weapon type.
There is also a brief introduction into type C weapons (powered).

== Weapon Type A

These are non-powered thrusting and striking weapons.
The non-powered
part of this weapon type description implies those weapons that are dependent on the physical effort of the attacker to inflict damage.
Thrusting and striking weapons are those that must either poke or strike their targets in order to inflict damage.
Type A weapons are hand held, but can include the hand itself.
Type A attacks include swords, maces, pole-arms, fists, paws, beaks, spears, etc.
A more complete list is found on the Type A Weapon Data Table.

Type A weapons are characteristically the slowest weapons because they are so labour intensive and require special conditions to be able to inflict damage.
Type A weapons must contact with a cutting edge or a particular hitting part, i.e., they must connect on the target without deflection to score a hit.
Because these weapons require such specialized, circumstances to inflict damage it is expected that some of the combat time is spent preparing the attack.

Table 28.1: Type A Weapon Data, is fairly self explanatory.
Each weapon included is fairly basic, and should be familiar to most people.
Those that aren't can be researched quite easily in a dictionary or an encyclopedia.
What isn't immediately obvious are the parameters of the weapons.
The parameters of Table 28.1: Type A Weapon Data are as follows: The Length is listed in cm, and is the length of the entire weapon.
The length includes hilts, blades, and points of the weapon.
The Wate is listed in kilograms, and should be included in the persona's wate allowance.
If a persona finds herself encumbered by a weapon, she should get a different one.
The AR Bonus indicates how well the weapon can be used for defensive purposes.
It is representative of how effective the weapon is at parrying an attack, or creating a defensive feint The value of the weapon's AR bonus is multiplied by the persona's DEx.
This value is added to her armour rating (AR) when using this weapon in combat.
A persona with a 12 DEx using a small flail, would add 12 to her armour rating (AR).
The weapon Damage is the most important component of the weapon's data.
The damage is the range of HPS that are subtracted from a target that is hit by the weapon.
An axe will inflict 2-12 HPS in damage (1d10 + 2)  each time a hit is scored.
The damage is generated each time a to hit roll scores a hit.
Type A weapons add the persona's PSTR to the die roll for a damage adjustment.
For even more mundane data about weapons refer to http://expgame.com/?page_id=292[Chapter 24: Mundane Equipment].

// insert table 231

== Weapon Type B

These are non-powered projectile weapons.
Again non-powered implies that the weapon's damage depends on the physical activity of the persona.
Throwing weapons are ones that can inflict damage at a distance.
Type B weapons include: rocks, daggers, boomerangs, whips, spitting, arrows, darts, etc.
A more complete list of type B weapons is given on Table 28.2: Type B Weapon Data.
These weapons are dependant on the aiming ability (DEX) of the attacker as they are on the attacker's PSTR..
Type B weapons can attack every unit, but they cannot be used at close range.
No type B weapon can attack if its target is within 1 hex.
Obviously there are some type B weapons that can only be used once.
For instance an axe would have to be retrieved before it could be used again.
Any weapon that is drawn, thrown, or heaved will get a roll to hit dependent on the persona's DEX value.
Type B weapons are more difficult to use than type A weapons, because the attacker must consider additional factors such as range and movement in order to score a hit.

Each weapon described is straightforward, and can be looked up in any respectable dictionary.
Several of the weapons are unique to EXP.
An Object is any solid, hand sized chunk that can be hurled by the persona.
This includes rocks, books, canned vegetables, or whatever.
A Point is any hand sized, thrown weapon which damages with a pointed end, screw driver, dagger, ice pick.
The Wham is a lethal flying disc.

The Type B Weapon Data table is fairly self explanatory.
The parameters of the weapons are as follows: The Wate is listed in kilograms, and should be included in the persona's wate allowance.
If a persona is encumbered by a weapon, she should get a different one.
+ The Range of type B weapons indicates the number of hexes the target can be from the attacker before penalties are issued.
If the target of an axe attack is within 14 hexes there is no range penalty.
The Decay of a weapon indicates how inaccurate the attack is once it is beyond the weapon's effective range.
The Decay is subtracted from the roll to hit for every hex beyond the weapon's range.
So if the axe attack just mentioned were 16 hexes from its target the to hit penalty would be -600.
Those weapon types that have their Range listed as PSTR have a range dependant on the physical strength of the attacker.
If a persona with a PSTR of 12 were to throw a staff, she would have an effective range of 12 hexes, and no further.
The weapon Damage is self explanatory, these are the number of Hit Points (HPS) subtracted from the target when a hit is scored.
Remember to add one quarter the  persona's PSTR as a Damage Adjuster (DA) for type B weapons.
Grenades are area of effect weapons, and they do not receive a damage adjustment when they detonate.
Type B attacks are used for grenades because they are usually thrown at a target, where they explode under their own power.

The cost of these mundane weapons and the parameter of ammunition for bows and slings is found in http://expgame.com/?page_id=292[Chapter 24: Mundane Equipment].

// insert table 232

== Weapon Type C

These are powered weapons.
Powered weapons do not depend on the physical strength of the attacker to inflict damage.
Type C weapons little physical effort to attack and inflict damage.
The killing forces are generated by batteries, expanding gases, springs, or other methods that are independent of the persona's PSTR.
Powered weapons include lasers, crossbows, rifles, fusion guns, death rays, machine pistols, etc.
A typical type C weapon can attack every unit without taxing the persona in anyway.
Type C weapons are highly dependant on the DEX of the persona because their most important factor is how well they are aimed.
Once properly aimed and triggered the powered weapon does the rest of the work.
There are no damage bonuses for type C weapons.

*Crossbows*: Crossbows are the only mundane type C weapon that is listed on Table 28.2 Type B and C Weapon Data.
They are spring launched attack weapons, and the persona cranks them up each and releases all the force when the trigger is pulled.
The remainder of Type C weapons are artifacts generated by the TOY system.

*Weapon Types D, E, F:* In addition to type C weapons there can be found Type D, E, F and special.
These are also powered weapons and they are treated the same as a type C weapon.
These weapons have one important difference.
Type D weapons get 2 attacks per unit, Type E weapons get 3 attacks per unit and Type F get 4 attacks per unit.
This means that its firing mechanism is so delicate that the player gets to make multiple to hit rolls each unit her persona uses fires the  weapon.

*Weapon Type Special*: These are fully automatic machine weapons.
Special attack is fully automatic.
This means that charges, or bullets are spraying forth from the end of the weapon.
Such weapons can empty their entire ammunition stores in several units.
When using a fully automatic (Flotto) weapon the player gets 5 to hit rolls every unit.
Each to hit roll accounts for a burst of 3 rounds of ammunition.
If a to hit roll is a miss then all three rounds miss the target.
If a to hit roll indicates a hit, then between 0 and 3 rounds hit the target.
If 0 rounds hit the target then no damage is inflicted, but if 3 rounds hit the target damage is rolled 3 times.
Special uses 15 rounds of ammunition each burst.

== Area Of Effect Weapons

Area of effect weapons are different than type A, B and most type C weapons because they deliver damage to everything in a certain collection of hexes whether they hit  the target or not.
The most famous area of effect weapon is the grenade.
There are some mundane area of effect weapons that personas may want to risk carrying about.
Area of effect weapons have a range equal to the persona's PSTR, and they also have an area of effect which will damage all targets within their area of effect.
Personas cannot buy area of effect weapons, and nor can they make them.
Only mechanics can fashion corrosive flasks, molotov cocktails and pipe bombs.
Grenade combat is covered in more detail in http://expgame.com/?page_id=304[Chapter 30: Grenades and Aerosol Combat].

*Mechanism*: A to hit roll is made like any other type B attack.
The persona can only use her BP if she is proficient in grenades.
So most personas will only be able to add their BNP to the grenade to hit roll.
Each device takes one unit of preparation before a to hit roll can be made.
All these weapons have a wate of 1 kilogram, and a chance of malfunction.
Any unadjusted to hit roll that between 42 and 200 will indicate that the device has failed.
Any unadjusted to hit roll less than 42 will indicate that the device has accidentally detonated.
A failed device is simply a dud and no one is damaged by the attack.
Unadjusted to hit rolls is the base kilodie roll before any bonuses are added.

*Oops*: Any unadjusted to hit roll less than 42 will indicate that the mundane area of effect weapon accidentally detonated.
If a homemade area of effect accidentally detonates then there is a chance that other homemade area of effect weapons within range will also detonate.
Each homemade area of effect weapon has a 2% of detonating spontaneously in the presence of another accidental detonation.

*Corrosion Flasks*: This area of effect weapon explodes on impact bathing everything in the area of effect with corrosives (acid or alkaline).
Area of effect is 0-1 hexes, and the damage is 2d10.
Construction is a DD5 mechanic maneuver.
A critical failure during the mechanic's performance roll indicates a accidental detonation on construction.

*Molotov Cocktail*: This area of effect weapon contains a flammable liquid that explodes on impact burning everything that is flammable.
The area of effect is 0-2 hexes, and the damage is 3d10.
The Molotov will burn for an additional 1 to 10 units creating a zone of damaging fire.
See http://expgame.com/?page_id=282[Chapter 19: Special Terrain].
Construction is a DD7 mechanic maneuver.
A critical failure during the mechanic's performance roll indicates a accidental detonation on construction.

*Pipe Bomb*: This is a handmade area of effect weapon that explodes on impact with a 0-3 hex radius.
It inflicts 2d12 damage to all targets in the area of effect.
Construction is a DD9 mechanic maneuver.
A critical failure during the mechanic's performance roll indicates a accidental detonation on construction.
