Task Example (42)::
One-line description of task. Difficulty is in brackets. 

==== Trivial
Salute (12)::
    Gesticulate deference to superior.

==== Easy
Proficiency (24)::
    Use any personal weapon as an expertise. 

Ambidextrous, Pistols (24)::
    Use two pistols at once, no penalty.

Snap Reload (24)::
    Reload a weapon without time loss.

Snap Unjam (24)::
    Unjam a weapon without time loss.

Breach, Civilian (24)::
    Destructively remove a civilian door.

Bolster (36)::
    Move attack bonus points to defence (DEF). 

Conscious (36)::
    Remain conscious when HPS are negative.

==== Normal
Divide (42)::
    Split attack bonus between attack rolls.

Ambush Ambivalence (42)::
    Act during ambush as if no ambush.

Safe Shot, Grenade (42)::
    Fling a grenade to avoid one target.

Ambidextrous, Striking (42)::
    Use two striking weapons no penalty.

Flanking (42)::
    Achieve flanking bonuses. 

Deflank (64)::
    Remove attacker flanking bonus. 


Running Cover (64)::
    Run, and maintain, full Defence rating.

==== Hard
Ambidextrous, Rifles (84)::
    Use two rifles at once no penalty.

Safe Shot, Aerosol (84)::
    Maneuver an aerosol to avoid one target.

Ambidextrous, Grenades (84)::
    Use two grenades at once no penalty.

Dodge Grenade (100)::
    Half kinetic HPS damage from grenade. 

==== Tough
Ambidextrous, Fling (126)::
    Use two fling weapons no penalty.

Dodge Artillery (100)::
    Half kinetic HPS damage from artillery. 

==== Impossible
Falling (168)::
    Perform any less difficult task while falling.

==== Bizarre
Dodge Bomb (242)::
    Avoid bomb damage. 

