Task Example (42)::
One-line description of task. Difficulty is in brackets. 

==== Trivial
Biological (12)::
    Is it biological? Yes/No. 

Sentience (12)::
    Sentience present. Yes/No. 

Passage In Safety (12)::
    Find safe passage when no danger

Living (18)::
    Is it alive and living. Yes/No.

==== Easy
Water Safety (24)::
    Safe water in wet biomes.

Edible (24)::
    Is it edible? Yes/No. 

Make Sausage (24)::
    Make a yummy sausage. 

Shelter from Forest (24)::
    Make shelter in dense vegetation for self. 

Fire From Something (24)::
    Make fire when stuff is around. 

Preserves (24)::
    Preserve food for later. 

Track, Oblivious (24)::
    Follow and find prey unaware of tracking. 

==== Normal
Quick Fix (42)::
    Heal 1d6 HPS immediately.

Food from Food (42)::
    Make normal survival food safe. 

Energy Source (42)::
    What does it eat?

Water From Rocks (42)::
    Find water in Dry biomes.

Shelter from Nothing (42)::
    Make safe shelter in city or tundra. 

Make Clothing (42)::
    Make appropriate survival clothing. 

Track on Land (42 + INT)::
    Follow and find typical prey. 

Poison Arrest (56)::
    Stop poison progress. Not heal.

==== Hard
Alien Organization (84)::
    Solo, family, herd, pack. 

Food from Toxic (84)::
    Make toxic survival food safe. 

Fire from Nothing (84)::
    Make fire in denuded areas. 

Make Camo (84)::
    Make camouflaged clothing for biome. 

Calm Frenzy (84)::
    Arrest an ursidae frenzy.

Poison Reverse (84)::
    Reverse the effects of a poison (except HPS damage).

Radiation Arrest (84)::
    Stop ongoing effects of radiation.

Track in Water (84 + INT)::
    Find and follow prey in water.

Domesticate, Befriend (84)::
    Make flora fauna alien follow persona around.

Domesticate, Tricks (104)::
    Train flora fauna alien some simple tricks.

==== Tough
Water from Sand (126)::
    Find water in arid biomes. 

Shelter from Eyes (126)::
    Make a safe shelter under surveillance.

Food from Poison (126)::
    Make poisonous food safe.

Poison Cure (126)::
    Reverse all poison effects (even HPS damage).

Domesticate, Imprint (126)::
    Make flora fauna alien friend. 

Track in air (126 + INT)::
    Follow and find flying prey.


==== Impossible
Food from Pharma (168)::
    Turn Pharma into food. 

==== Bizarre
Water from Vacuum (210)::
    Find water in exatmo.

Track across Vacuum (210)::
    Find target across planets.

Domesticate, Parentalize (210)::
    Make a flora fauna alien protect nomad like their spawn.

