Task Example (42)::
One-line description of task. Difficulty is in brackets. 

==== Trivial
Be Afraid (12)::
    Ensure others know you are afraid.

Fall Asleep (12)::
    Get shut-eye anywhere.

==== Easy
Attention (24)::
    Make herself the center of attention. 

Eat Fast (24)::
    Fill cake hole quietly and quickly.

Recall Name (24)::
    Recall a referee persona's name. 

==== Normal
Dress for Success (42)::
    Wear the right clothes to a function.

Attention, Diversion (42)::
    Make someone else the center of attention.

Righteous Indignation (42)::
    Project righteous indignation.

Tie a Tie (42)::
    Correctly adorn a tie on herself.

Queue Jumping (42)::
    Get herself past the queue.

==== Hard
Wakey Wakey (84)::
    Wake up at the correct time.

Tie Another's Tie (84)::
    Correctly adorn a tie on another persona.

Queue Trashing (84)::
    Get the expedition past the queue.

==== Tough
Loan, Residential (126)::
    Get a loan for habitation.

Loan, Commercial (148)::
    Get a loan for business.

==== Impossible
Venture Capital (168)::
    Secure venture capital. 

==== Bizarre
Quick Fix (210)::
    Heal 1d6 HPS. 

