Task Example (42)::
One-line description of task. Difficulty is in brackets. 

==== Trivial
No Guilt (12)::
    Expunge guilty feelings. 

Escape! (12)::
    Out of frying pan into fire. 

==== Easy
Case, Low Tech (24)::
    Find security weakness. Less than tech level 10.

Disguise, Planned (24 + AWE)::
    Carefully planned hiding of appearance from strangers.

Bypass, Low Tech (24)::
    Get past security measures. Less than tech level 10. 

Sneak, Crowded (24)::
    Move self around without being noticed in a crowd.

Encrypt (24)::
    Make data hard to read for others. 

Decrypt, Low Tech (24)::
    Read encrypted data in lo-tech (<10).

Forgery, Low Tech (24)::
    Create fake document in tech level <9.

==== Normal
Bribery (42)::
    Jump order with value. Mutual benefit.

Blackmail (42)::
    Extract value with information. Coercive.

Decrypt, Normal (42)::
    Read encrypted data in normal tech environment (10).

Case, Mundane (42)::
    Find security weakness. Tech level 10-14.

Disguise, Fast (42 + AWE)::
    Temporary improvised hiding of appearance from strangers.

Lying (42 + MND)::
    Falsification without tells. 

Bypass, Mundane (42)::
    Get past security measures. Tech level 10-14.

Stun, Surprise (42 + CON)::
    Total surprise. Successful attack roll. 

Climb (42)::
    Find a way to climb something not obviously climbable.

Sneak, Standard (42)::
    Move self around without being noticed.

Trap (42)::
    Set trap to activate an alarm or attack. 

Forgery, Normal (42)::
    Create a fake document up to tech level 10.

Pilfer (43 + AWE)::
    Sleight of hand conceal hand-sized thing.

Interrogation (42 + MND)::
    Get info from a persona using pressure. 

==== Hard
Case, Secure (84)::
    Find security weakness in secure facility.

Disguise, Known (84 + AWE)::
    Hiding appearance from folks that know the persona. 

Bypass, Secure (84)::
    Get past security measures. Tech level 15-19.

Sneak, Security (84)::
    Move self around without being noticed in a secure location.

Incapacitate (84 + AWE + LEVEL)::
    Requires a successful ambush and attack roll.

Stun, Combat (84 + CON + LEVEL)::
    Successful attack roll.

Decrypt, Secure (84)::
    Read encrypted data in a secure situation. Tech Level (11-19).

Forgery, High Tech (84)::
    Create a fake document in tech level 11-19.

==== Tough
Case, Higher Tech (126)::
    Find security weakness. Tech level 15-19.

Disguise, Close (126 + AWE)::
    Hiding appearance from friends. 

Bypass, Higher Tech (126)::
    Find security weakness. Tech level 15-19.

Assassinate (126 + AWE + LEVEL)::
    Requires total surprise. Successful attack roll. Ranged attack. 

Sneak, Combat (126)::
    Move self around without being noticed during combat.

Decrypt, High Tech (126)::
    Read encrypted data. Tech level 20 and up.

Forgery, Secure (126)::
    Create a fake document. Tech level 20 and up.

==== Impossible
Case, High Tech (168)::
    Find security weakness. Tech level 20 and up.

Bypass, High Tech (168)::
    Get past security measures. Tech level 20 and up.

Disguise, Family (168 + AWE)::
    Hiding appearance from family, or expedition members.

Decrypt, Secret (168 + INT)::
    Read professionally encrypted data.

==== Bizarre
Disguise, Self (210)::
    Hiding appearance from self.

