Task Example (42)::
One-line description of task. Difficulty is in brackets. 

==== Trivial
Biological? (12)::
    Is it biological? Yes/No. 

Sentience (12)::
    Sentience present. Yes/No. 

Living? (18)::
    Is it alive and living? Yes/No.

Autopsy, Fun (12)::
    Disassemble a cadaver.

Stasis Bag (18)::
    Safely put stuff into a stasis bag. 


==== Easy
Quick Fix (24)::
    Heal 1d6 HPS immediately.

Calm Persona (24)::
    Help a persona relax. 

Admin Pharma (24)::
    No adverse effects. 

Fail Pharma (32)::
    Guarantee adverse effects.

Unstun (32)::
    Immediately remove stun effect from one persona. 

==== Normal
Strong Fix (42)::
    Heal 2d6 HPS over 2 units.

Open Stasis Bag (42)::
    Retrieve patient from stasis bag alive.

Stabilize (42)::
    Stop persona from losing negative HPS.

Cryogenic Wake (56)::
    Safely emerge from cryogenic sleep.

Poison Arrest (56)::
    Stop poison progress. Does not heal.

Heal 50% (50)::
    Restore to 50% HPM. Uncombat only. 

==== Hard
Autopsy, Diagnostic (84)::
    Disassemble to determine cause of death.

Power Fix (84)::
    Heal 3d6 HPS over 3 units. 

Calm Frenzy (84)::
    Arrest an Ursidae frenzy.

Resuscitate (84)::
    Restore the persona to zero HPS and unconsciousness.

Poison Reverse (84)::
    Reverse the effects of a poison (except HPS damage).

Radiation Arrest (84)::
    Stop ongoing effects of radiation.

Heal 90% (90)::
    Restore to 90% HPM. Uncombat only.

Restore Attribute (96)::
    Revive an injured attribute (not from aging).

Psionic Break (96)::
    Interrupt a psionic attack.

Biorganic Attachment (100)::
    Attach a biorganic attachment.


Subliminal Suggestion (108)::
    Interject a thought without detection.

Hearing Restoration (108)::
    Reverse any deafness.


==== Tough
Autopsy, Forensic (126)::
    Disassemble to determine criminal death.

Biorganic Replacement (126)::
    Insert a biorganic replacement.

Poison Cure (126)::
    Reverse all poison effects (even HPS damage).

Radiation Cure (126)::
    Reverse all radiation effects (even HPS damage).

Unstun Group (126)::
    Unstun all within one hex range. 

Paralyzing Pinch (126)::
    Touch target for physical collapse (anthro only).

Mind Inventory (142)::
    Detect mind control. 

Cryogenic Sleep (156)::
    Safely place into cryogenic sleep.

Vision Restoration (156)::
    Restore any blindness. 

==== Impossible
Attribute Boost (168)::
    Temporarily boost an attribute by 1d3 for 1d3 minutes.

Death Pinch (168)::
    Touch target for cardiac arrest (anthro only).

Phenomic Removal (168)::
    Safely remove a phenomic mutation.

Reattach Members (196)::
    Reverse the handiwork of Knites.

==== Bizarre
Attribute Enhance (210)::
    Permanently increase an attribute by 1 (not MIND).

Psionic Removal (210)::
    Unsafely remove a psionic mutation. 

Pharma Creation (242)::
    I wanna new drug. 

Aging Stagnation (242)::
    Arrest an aging effect. One at a time.

