= Aliens

[quote]
____
*Aliens represent the infinity of organic forms that can be conscious.*
____

Alien is the colloquial term for the family diversidae.
Aliens encompass any organic living creature that has consciousness.
Aliens are evolved, represent species, and are generated randomly. 

== Alien Evolution Checklist
The alien evolution checklist is ordered for convenience, and decision making. 
For example, shape precedes movement rate as shape determines flying, running and swimming speeds. 
The checklist represents a full implementation of an alien persona with all its complexity and challenges.
The evolution checklist is a tool no a rule. Just use the steps you need to have fun.

. xref:appendices:printables.adoc[Get Alien Persona Record, window=_blank]
.. Save a tree and use https://xournalpp.github.io/[Xournal, window=_blank]
. xref:aliens:attributes.adoc[Attributes, window=_blank]
. xref:aliens:size.adoc[Size, window=_blank]
. xref:aliens:hit_points_generation.adoc[Hit Points, window=_blank]
. xref:aliens:attack_frequency.adoc[Attack Frequency, window=_blank]
. xref:aliens:attack_type.adoc[Attack Type, window=_blank]
. xref:aliens:attack_damage.adoc[Attack Damage, window=_blank]
. xref:aliens:attack_table.adoc[Attack Table, window=_blank]
. xref:aliens:defence_rating.adoc[Defence Rating, window=_blank]
. xref:aliens:alien_shape.adoc[Shape, window=_blank]
. xref:aliens:movement.adoc[Movement Rate, window=_blank]
. xref:aliens:wate_allowance.adoc[Wate Allowance, window=_blank]
. xref:aliens:evolutations.adoc[Evolutations, window=_blank]
. xref:aliens:life_span.adoc[Life Span, window=_blank]
. xref:aliens:biology.adoc[Biology, window=_blank]
. xref:aliens:society.adoc[Society, window=_blank]
. xref:aliens:tool_usage.adoc[Tool Usage, window=_blank]
. xref:aliens:name.adoc[Name, window=_blank]

Alien personas are randomly generated and wildly diverse.
Size, shape, attributes, abilities are all randomly determined.
If a referee needs a particular feature in an alien persona, look to xref:referee_personas:alien_rp.adoc[referee alien personas].

EXP follows the sciency fiction assumption that aliens evolve themselves into existence. 
The referee's campaign need not follow this assumption.
Aliens could be fabricated, cloned, or divinely assembled.
Regardless of the back story, aliens are organic life forms. 

EXP assumes that the alien evolved is an entire species.
When a player is evolving an alien, she is creating a species.
The player generates the attributes, shape and size of an entire species.
Her alien persona is an individual belonging to this alien species.
The alien persona is a solo free-willed representative of this species.
The referee needs only integrate the persona into her campaign.
A resourceful referee and players may integrate each new species into the campaign's milieu.

== Role-Playing Aliens
Role-playing an alien is trickier than roleplaying an anthro.
Players can easily relate to playing anthros.
Alien and robot personas are challenging to even experienced players.
Alien generation is random, and there is wide variation in shape, size, and type of appendages.
The persona could weigh 500kg, have pincers instead of hands, and no legs at all.
Players must learn to restrain the urge to personify their aliens.

Players running aliens have to employ the most imaginative roleplaying skills.
For example, holding an object, sitting in a chair, or pressing buttons may be impossible.
Alien personas may have a completely different understanding of remuneration or success.
The player's flying anemone may be cool, but it may prefer to hunt squirrels instead of saving the universe.

Anthropomorphizing alien personas is to be avoided.
Alien anatomy, physiology and psychology is the great roleplaying challenge for the players.
Keeping it real for a non-existent species is the fun and pain of playing an alien persona.

:art: alien_shapes.png
:width: 450px
:snark: Alien shapes can be strange to play.
:artist: H. Brown
:date: 1938
:license: CC BY-SA 4.0
:description: Drawing of three strange shaped alien creatures. 

include::ROOT:partial$articulate.adoc[]

