= Alien Shape

In keeping with the family name diversidae, alien shapes are very diverse.
The alien description system is wild and unpredictable.
An alien shape is a mash-up of body parts from a list of mundane terra denizens.
Each creature part listed will be familiar to the ref and players.
Four different creature types are combined to create a new alien shape.
The four parts are proportional to each other and represent appearance only.
Sparrow arms on a tiger body are fully functioning components, not vestigial specks.
The image below best demonstrates the proportionality of the animal shapes.

:art: alien_assembly.png
:width: 450px
:snark: Four rolls. One alien.
:artist: Kevin Long
:date: 1992
:license: Copyright 1992 Kevin Long
:description: Drawing showing four earth creatures being combined into one alien creature.

include::ROOT:partial$articulate.adoc[]

The shape of the alien persona fits into the alien size previously generated.
If the alien size is small, the assembled alien will be small. 
An alien with a wate of 10kg and a tiger torso would have a proportionally scaled-down tiger torso.

== Introduction

The player generates a head, torso, arms and legs.
Each body part represents the shape of each animal. 
The body part does *NOT* add any special abilities the animal may have.
For example, a scorpion torso would not be poisonous.
The body part may not even have the same colour or coat texture of the animal type.
The body parts' mash-up determines the alien's shape and her movement rate.

== Terrain Parts
Each alien body part has some lowercase letters in parenthesis beside it.
These are the alien's terrain types and determine the alien's movement rate in different terrain. 
Goose (law) indicates the body part is shaped like a goose's and works well on land, water and air. 
Goat (l) indicates the body part is shaped like a goat's and works well on land.

:art: alien_trex_head_tricera_lynx_manta.png
:width: 250px
:snark: Head: t-rex, Torso: triceratops, Arms: lynx, Legs: manta ray
:artist: Nelson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of an alien Head: t-rex, Torso: triceratops, Arms: lynx, Legs: manta ray

include::ROOT:partial$articulate.adoc[]

* t-rex (l)
* triceratops (l)
* lynx (l)
* manta ray (w)

=== Head
The alien's head part _usually_ stores the alien's brain and sensors.
The head is _usually_ located at the front of the alien.
Record the terrain types (l, a, w, s) associated with the head part.
The player may add an optional <<_head_adornment,Head Adornment>> later.

=== Torso
The alien's torso part _usually_ stores the alien's vital organs.
The part does not indicate the types of vital organs, but they are most likely in the torso.
Record the terrain types (l, a, w, s) associated with the torso part.
The player may add an optional <<_torso_adornment,Torso Adornment>> later.

=== Arms
The alien's arms part _usually_ indicates the alien's front limbs and articulators.
The arms part does not affect whether the alien is a tool user or not.
Record the terrain types (l, a, w, s) associated with the arms part.
The player may add optional <<_arms_adornment,Arms Adornment>> later.

=== Legs
The legs part _usually_ indicates the primary way the alien moves.
Record the terrain types (l, a, w, s) associated with the legs part.
The legs part does not solely determine alien locomotion.
If an alien can fly and run, it will have the parts for both. 
Often an alien's legs will not be legs at all but flukes, flippers, bulbs and blobs.
If the alien has a snake's legs, it slithers about.
If the alien has fish legs, it may wiggle or fin itself around.
If the alien has parrot arms and fish legs, it may fly or slither.

include::aliens:partial$alien_shape_body_parts.adoc[]

== Adornments
These are optional accents to the alien's appearance.
Adornments are entirely descriptive.
Adornments do not detract from or add any abilities to the alien. 
The player chooses the details (amount and size) of the adornments. 

=== Head Adornment

:art: alien_head_adornment.png
:width: 250px
:snark: Head tusklers.
:artist: Unknown.
:date: Unknown.
:license: CC BY-SA 4.0
:description: Drawing of horse like alien with big tusk horns on it's nose. 

include::ROOT:partial$articulate.adoc[]

include::aliens:partial$alien_shape_head_adornment.adoc[]

=== Torso Adornment

include::aliens:partial$alien_shape_torso_adornment.adoc[]

=== Arms Adornment

include::aliens:partial$alien_shape_arm_adornment.adoc[]

== Coat
The aliens need not appear as a patchwork of feathers, hide and fur.
Most players will choose a single coat type for their alien.
This covering can be chosen from any of the four parts or created de novo.

== Coat Colour
The aliens need not appear as a patchwork of diverse colours.
Most players will choose a single coat colour for their alien.
This covering can be chosen from any of the four parts or created de novo.
There is also an overly detailed colour generator in EXP.
To create a de novo coat colour jump to xref:hardware:appearance.adoc#_colour_your_whirled[Colour,window=_blank].

== Missing Parts
If the player rolls _None_ for a body part, that part is not there.
The alien does not have any use for that particular body part.
An alien with no head part may have sensors attached to the torso.
An alien with no legs may move by utilizing the torso or be immobile.
Missing parts decrease the alien's movement rate. 
An alien with no body parts would be a gaseous or blob entity.

:art: alien_none.png
:width: 250px
:snark: No parts. No body.
:artist: Earl Bergey
:date: 1945 
:license: CC BY-SA 4.0
:description: Drawing of a liquid blob alien jumping out of a giant glass box.

include::ROOT:partial$articulate.adoc[]

== Tool Use
The arms part has no bearing on whether the alien is a tool user or not. 
The society elements determine tool use, not the alien's shape.
An alien with opposable thumbs may not recognize a tool at all.
The opposable thumbs may only pick berries or peel the flesh off prey.

The corollary is true as well.
The society elements determine tool use, not the alien's shape.
An alien with no obvious tool using appendages will still be a tool user.
 Flippers, hooves, or fins adapt to tool use, or the tools adapt to flippers hooves or fins.

== Proportions
Each body part is proportional to the other body parts in the description.
The alien's size attribute (Small, Medium, Large, etc.) determines the alien size, not her body parts.
A mosquito head part combined with a bear torso part would have matching sizes.
The alien would not have a microscopic head on a bear torso.
The alien looks like a bulky hairy body with an insectoid head sporting a long proboscis.
The mosquito's head would be a size proportional to the bear's torso.

The corollary is true.
The alien's size attribute (Small, Medium, Large, etc.) determines the alien size, not her body parts.
A giraffe head part combined with a sperm whale torso part would still be tiny. 
The alien looks like a square blubbery body with a giraffe head on a long neck.
The whole abomination is about the size of a german shepherd. 

== Biology
This section is yet another reiteration that the alien parts represent shape, not function.
Don't let scientific knowledge get in the way of fun and storytelling.

[quote]
_____
Harrumph! An amoeba of that size would collapse under its weight.
_____

The alien is *not* a 542 kg pink amoeba. 
The alien has a wate of 542 kg, and it looks like an amoeba.

This alien is held together by alien physiology crafted by generations of evolution.
The alien's internal composition consists of alien biology unlike biology on mundane terra.
Fantastical artifacts have Sciency Fiction  _black box_ technomagical explanations.
Alien biology also enjoys this _black box_ explanation.

== Movement
Alien shape and Dexterity score determines its movement rate.
The alien's Dexterity score will determine her base movement rate. 
The alien's shape indicates which terrain types the alien is capable of moving on.
The terrain types indicate how the base rate gets split between land, air, and water movement.
Whether an alien can fly or not is enormously important to the player.
Keeping track of the terrain types letters (l, a, w, s) is critical when evolving an alien species.
For a detailed rendering jump to xref:aliens:movement.adoc[Alien Movement,window=_blank].
