= Alien Attack Type

The alien attack type determines how the alien delivers the damage amount.
Does the alien require physical contact to deliver the destructive force?
Does the alien launch a ranged attack to hit enemies from afar?
Is the force of the attack energized by some alien physiologic force?
The alien's description determines how the attack type works. 

include::aliens:partial$attack_type_options.adoc[]

== Strike Attack
Strike attacks are thrusting, striking attacks powered by the alien's brawn.
These could be bites, punches, stabs, squishes, slashes, pecks, or scratches.
Strike attacks are in close combat, tentacle to tentacle attacks.
The vast majority of aliens employ Strike attacks.
Unlike anthros, aliens do not get Strength damage bonuses for Strike attacks.

== Attack Fling
Fling attacks are ranged attacks powered by the alien's brawn.
These could be acidic spittle, flying quills, ejected spines or darts.
Fling attacks have a range and shoot like an arrow, *not* like a bullet.
Fling attacks are not long range attacks, but close combat is not required.
The alien's Fling attack range is one hex per point of Strength score.
An alien with a Strength of 12 has a 12 hex attack range.
Unlike anthros, aliens do not get Strength damage bonuses for Strike attacks.

== Attack Shoot
Shoot attacks are the rarest and most alien naturalized attack type.
The alien has evolved a self-propelled powered attack.
These are classic sciency fiction attacks like lazer eyes or gas-propelled bone bullets.
Shoot attacks are naturalized but function like a gun.
The player may turn to the hardware section xref:hardware:guns.adoc#_generate_type[Guns,window=_blank]for descriptive inspiration. 









