= Alien Attack Table

The combat rules in the Roll Playing System employs an attack matrix called the attack table.
The player refers to the attack table every time she makes an attack roll.
An alien's attack table is for their evolved natural attacks. 
The Strike Attack would be for her nasty bite attack, and the Fling Attack would be for her steaming sap blob spittles. The alien attack table is not for artifact weapons. 



This section has cursory explanations and detailed calculations. 
For more info jump to xref:roll_playing_system:CH09_Combat_Tables.adoc[Attack Tables,window=_blank].

== Aliens and Weapons
The attack table generated here is for the alien's naturally evovled attacks and *not* artifact weapons.
For an alien to even consider using a weapon the species must be a tool user.
Even a simple tool user can use an artifact weapon (gun, grenade, axe, etc).
However flora or fauna aliens do not even comprehend tools of any kind.
A non-tool using alien would step over the fusion rifle and attack the robot with her beak. 

If an alien does not have a Vocation she must use the Raw Bonus of zero.
If the alien species has education and she can follow a Vocation then a Vocation Attack Table is generated for artifact weapons attacks. 

.*Aliens and Artifact Weapons*
* Flora or Fauna - No weapon use or interest at all
* Tool Using - May use a weapon with Raw Bonus of zero
* Educated - May use Vocation Attack Table and it's Skilled Bonus

The player can use a Vocation Attack Table for  artifact weapons.
The Alien Attack Table is used for evolved natural attacks. 
Managing the burden of having two attack tables is up to the referee and the table of players.
Aliens can be powerful and being able to use their super charged attributes to shoot things may affect game balance.

The player can create a Vocation Attack Table for her educabucated tool usin' alien by jumping xref:anthros:attack_table[here,window=_blank].

== Attack Table
This section has cursory explanations and detailed calculations. 
For more info jump to xref:roll_playing_system:CH09_Combat_Tables.adoc[Attack Tables,window=_blank].

include::anthros:partial$attack_table_blank.adoc[]

.*Attack Table Checklist*
. <<_skilled_bonus,Skilled Bonus>>
. <<_raw_bonus,Raw Bonus>>
. <<_max_roll,Max Roll>>
. <<_force_bonus,Force Bonus>>

== Skilled Bonus
The Skilled Bonus (Skilled) is for the alien's natural attacks.
The player adds the Skilled to her attack roll when her persona is attacking.
The Skilled has two main components: Attributes Bonus and Level bonus.
The persona's Skilled increases as the persona gains EXPS levels. 

include::aliens:partial$alien_attack_table_calculation.adoc[]

== Raw Bonus
An alien cannot be unskilled with her natural attack.
Alien's Raw Bonus equals her Skilled Bonus.
If the alien is a tool user wielding weapons, the player must generate an additional attack table that includes a Raw.

include::aliens:partial$alien_attack_table_raw_bonus.adoc[]

== Max Roll
The Max Roll is the highest roll that a player can make on the kilo-die attack roll.
There is always a chance to damage an attacker using xref:roll_playing_system:CH16_Special_Rolls_Critical.adoc[Critical Checks,window=_blank].

include::aliens:partial$alien_attack_table_max_roll.adoc[]

== Force Bonus
Alien damage already includes both the alien's size and Strength.
There is no Force Bonus for alien attack roll wins.

include::aliens:partial$alien_attack_table_force_bonus.adoc[]

== Alien Attack Table Example
A second-level gigantic alien has a 22 STR, 15 DEX, and a 3 INT.
Her attack is spitting sharp blobs of resin which is Attack Fling.

include::aliens:partial$alien_attack_table_example.adoc[]


