= Alien Damage Per Attack

Alien damage per attack indicates how many hit points the target loses when the player wins an attack roll.
The more damage per attack, the more dangerous the alien.
The persona's size and Strength determine damage per hit.
Alien damage per unit depends on the alien's attack frequency. 
A small amount of damage delivered frequently can be very dangerous.

:art: budgie_octopus_bat.png
:width: 450px
:snark: Head budgie, torso bat, arms octopus, legs none.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Flying monster with a budgie face, octopus limbs and bat wings.

include::ROOT:partial$articulate.adoc[]

== Damage per Hit
The damage per hit represents how deadly an alien's naturalized attack is.
The bigger and stronger the alien, the more devastating a successful attack roll is.

How the alien delivers the damage does not affect the damage per for an attack roll win.
Does the alien bite, slash, spit, zap or barf its attack?
The alien's description usually determines the method of attack. 
If the alien uses a pincer or an open hand slap, the damage range will be the same.

A gigantic alien with a 13 STR would inflict 3d12 HPS damage each time the player wins an attack roll.
Aliens do not get a Force Bonus for Strength.
The amount of damage an alien inflicts already reflects its Strength.

include::aliens:partial$attack_damage_and_size.adoc[]



