= Alien Attributes

Alien attributes are very diverse and uniquely generated.
The player generates the attributes for her specific persona, but there is more to it than just that.
The attributes also represent the attributes of an entire alien species.

Attribute values are equal amongst the personas, whether anthro, robot or alien.
An alien's 12 STR equals an anthro's 12 STR, which equals a robot's 12 STR.

The player generates a new score for each alien attribute.
The player must use the range and die roll prescribed for each attribute score.
There are no alternate attribute generation systems for aliens.
The prescribed rolls assure a good statistical curve of all aliens' attributes.

include::aliens:partial$attributes_generation_list.adoc[]

== Alien Species
The player persona is a model citizen from a previously non-existent alien species.
The attribute scores should represent the average attribute scores of a young adult of that species.
Integrating the new alien persona as a species is up to the referee and players.

:art: alien_mule_tarantula_trex_paramecium.png
:width: 250px
:snark: Head: mule, Torso: tarantula, Arms: t-rex, Legs: paramecium
:artist: Nelson
:date: 1992
:license: CC BY-SA 4.0
:description: Drawing of an alien Head: mule, Torso: tarantula, Arms: t-rex, Legs: paramecium.

include::ROOT:partial$articulate.adoc[]

== Alien Death and Attributes.
If an alien persona drops any of her attributes to zero, she dies.
Having an attribute hit zero is lethal for robots, anthros and aliens.
An alien is dead if her hit points reaches zero.
 

