= Alien Biology

Biology gives a cursory description of where the alien fits into its ecological system.
The biome describes the alien's preferred terrain that the alien.
The remaining tables provide some insight into what makes an alien tick.
For alien species that use tools and have vocations, these biological descriptors merely inform the species' nature.
Advanced species may embrace or eschew this evolutionary heritage.

:art: biome_modern_space.png
:width: 450px
:snark: Biomes are not just trees and dirt.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Landscape of futuristic wall in front of planet and stars.

include::ROOT:partial$articulate.adoc[]

== Alien Biology Checklist
. <<_biome,Biome>>
.. <<_biome_modification,Biome Modification>>
. <<_energy_source,Energy Source>>
.. <<_energy_procurement,Procurement>>
. <<_reproduction,Reproduction>>
. <<_dwelling,Dwelling>>
. <<_aroma,Aroma>>

== Biome
A biome is a the weather, flora, fauna, biology, and geography of where the alien species is most comfortable.
Most aliens can survive outside their biome, and the biome offers no special benefits to the persona.
The alien biome is a descriptive tool that helps build the species. 
The biome is for an entire species and is used to inform the species behaviour, culture and politics.

Each biome benefits from a characteristic. 
An alien from a High Gravity Coniferous biome would be at home in such a biome. 

include::aliens:partial$biome_list.adoc[]

include::aliens:partial$biome_characteristic.adoc[]

== Energy Source
Energy source is what the alien biologically requires to sustain their existence.
An absence of energy leads to alien death. 
The energy source is usually from their biome, but it could also be from the local grocery store.
The nature of what the alien must consume for sustenance is determined on the below table.
The energy source is for an entire species and is used to inform the species behaviour, culture and politics.

include::aliens:partial$energy_sources.adoc[]

Psionovore requires a bit of extra attention.
A psionovore drains the Mind Attribute of biological (anthros, aliens) in order to survive.
The referee or table may give the alien volition over what it eats as a psionovore. 
Most importantly does the player persona drain the Mind (MND) attribute of fellow expedition members. 
A psionovoric alien can be the basis for entire milieu or young adult literature property. 

=== Energy Procurement

:art: booh.png
:width: 350px
:snark: Boo!
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Thick skinned toothy worm bursting from ground.

include::ROOT:partial$articulate.adoc[]


Energy procurement is all that matters to flora or fauna aliens.
Energy procurement for a creator tech species may be no more interesting than a button push. 
The energy source is for an entire species and is used to inform the species behaviour, culture and politics.
Contradictory energy source and procurement combinations are intentional to reflect the peculiarity and diversity of biologic entities

include::aliens:partial$energy_procurement.adoc[]

== Reproduction

:art: alien_prodigial_repro.png
:width: 350px
:snark: Out on a limb prodigial reproductive strategy.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Overly large egg in tiny nest balancing on limb out over cliff.
include::ROOT:partial$articulate.adoc[]

The reproductive strategy is for the entire species and is used to inform the species behaviour, culture and politics.

include::aliens:partial$reproduction_method_list.adoc[]

== Dwelling

The dwelling type is for the entire species and is used to inform the species behaviour, culture and politics.

include::aliens:partial$habitation_list.adoc[]

== Aroma

The aroma is for the entire species and is used to inform the species behaviour, culture and politics.
Aroma can play a role where aliens are big bads and their mere smell informs the game play.

include::aliens:partial$aroma_list.adoc[]

== Sounds

The sounds that the alien make will inform it's language whether it is part of a society with education or flora and fauna scraping out it's existence.

include::aliens:partial$sounds.adoc[]