= Alien Defence Rating

Defence Rating (DEF) is a combat measurement of how hard the alien is to damage.
The higher the Defence Rating, the harder it is to hit the alien in combat.
Armour rating is covered more thoroughly in  xref:roll_playing_system:CH29_Armour_Rating.adoc[Defence Rating,window=_blank].

Alien Defence Rating is a composition of all the elements that make it hard to damage.
For example, speed, agility, hide, body coverings are rolled into Defence Rating.
The description of the alien does not influence the Defence Rating.
A turtle shell in the alien's description does not improve the alien's Defence Rating.

:art: alien_AR_shell.png
:width: 250px
:snark: Shell is for appearance, not armour.
:artist: Unknown.
:date: Unknown.
:license: CC BY-SA 4.0
:description: Drawing of cosmetic turtle shell on back of four legged alien.


include::ROOT:partial$articulate.adoc[]

The Defence Rating is determined entirely randomly.
An alien's base Defence Rating can range from 503 to 800.
This Defence Rating represents the 'naked' Defence Rating of this alien species.

Aliens can wear body armour, but alien body armour is extremely rare. 
Before an alien could have worn armour in addition to her native armour, the species would have to be technologically capable.
Body armour may exist for a species that has creator level in xref:roll_playing_system:CH06_Aliens_13_Society.adoc[Tool Usage,window=_blank].

The higher the Defence Rating, the tougher the alien.
There is no Dexterity score bonus for alien Defence Rating.

== Alien Defence Rating
// tag::Alien_AR[]
.AR = 500 + 3d100
****
Rolling 15, 89 and 64, would give an AR of 668.
****
// end::Alien_AR[]