= Evolutations (Mutations)

Aliens can enjoy all the special abilities that psionic and phenomic mutations offer.
However when a player is generating an alien they are generating an entire genus and species.
These mutation abilities are evolved abilities and not point mutations. 
Hence the naming convention of evolutation.

Adding powerful mutations to an entire species requires consideration to plot and milieu.
An evolutation may only appear at certain life stages, or only certain members of the species have the evolutation.
An army of gigantic flying aliens with death field generation would be a world breaker. 
However, a species of tiny aliens with weak telekinesis would be make for an interesting culture. 

Aliens are biological in nature and can acquire unique mutations from radiation or cheeky pharma.

== Psionic Evolutations
The chance of an alien having a psionic mutation is equal to the alien's Mind attribute score.
An alien with a 15 MND would have a 15% chance of having a psionic mutation.
Player personas cannot start with a defect.
Aliens do not have multiple psionic mutations.
To determine the evolutation jump to xref:wetware:psionics.adoc[Psionic Mutations,window=_blank].

== Phenomic Evolutations
The chance of a creature having evolved a phenomic mutation is equal to the alien's Constitution attribute score.
An alien with a 10 CON has a 10% chance of having a phenomic mutation.
Player personas cannot start with a defect.
Aliens do not have multiple phenomic mutations.
To determine the evolutation jump to xref:wetware:phenomics.adoc[Phenomic Mutations,window=_blank].

NOTE: In past versions of EXP aliens could have multiple evolutations. 



