= Alien Lifespan

All organic personas have a projected life-span.
Aliens and anthros are born with consciousness and a limited time to use it.
Robots have an unlimited life-span until they acquire consciousness through entropy.

The alien's life span impacts the alien species' society and behaviour.
Long-lived species may have fewer offspring and may take fewer risks than short-lived alien species.
Long-lived species may get profoundly bored and take tremendous risks near the end of their life-span.
Life-span should not rule how the player runs her persona.

== Total Life Span
The player generates the total life-span in years of the alien on the Alien Life Span Table.
The years are mundane terran years.
The referee is free to create planet dependent years and calendars as she sees fit.

include::aliens:partial$life_spans.adoc[]

:art: life_stages.png
:width: 350px
:snark: Life stages are not just about size.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Large alien biped with scary head, smaller version and egg version.
include::ROOT:partial$articulate.adoc[]

== Alien Life Stages
The alien life stages are anthropomorphized and random.
The alien life stages indicate how much time the alien spends in each life stage. 
The life stage does not indicate the life stage details like pupae, puberty, dormancy, ferality or dependency. 
The life stage does not indicate any superficial changes to appearance or demeanour.

The life stages indicate each stage's duration and the attribute adjustments of each stage.
For the attribute adjustments levied for breaching life stages jump to xref:uncombat:health.adoc#_aging[Aging,window=_blank]. 

include::aliens:partial$life_span_stages.adoc[]

== Persona Age
After all the above machinations, how old is the player's persona?
The player must choose an age from late adolescence to young adult. 
EXP humbly recommends that the alien persona's start age represent the alien that the player evolved.
If any of these life stages represents a pupal, dependent or feral stage, the referee must have all of the details set out.

== Example Alien Life Span
To start, the player rolls 82 on the deci-die and generates a total life span of 160-250 years.
She determines her persona's total life span is 200 years.
Her die rolls on the Alien Life Stages Table determine how much time the species spends in each life stage. 
The player and referee engage in some simple maths to generate the alien's life span.

include::aliens:partial$life_span_example.adoc[]

The player can choose a start age between late adolescence (25 years old) and young adult (40 years old). 
In her 169th year, she becomes an elder, and in her 197th year, she becomes aged.
Beyond 200 years, she has exceeded her life expectancy.
For the effects of these age changes jump to  jump to xref:uncombat:health.adoc#_aging[Aging,window=_blank]. 
