= Moniker
The player must name her persona.
Every persona must have a moniker, call sign, label, title, handle or cognomen.
A player should avoid naming her persona with her mundane world real name.
Creating a persona name makes role-playing more fun.

.*Alien Names*
* Persona Moniker -- player's job
* Species Name -- <<_species_names,help is below>>
* Colloquial Name -- referee and milieu dependent

Alien names are complicated.
The player is responsible for naming her persona and her persona's species. 
Every alien has a moniker and a species name.
The persona will interact with her compatriots using her her moniker "Zetheria."
The alien persona will also have a species name like "Crustacae Iritii."
There is often a common species name that may be self referential or given.
Zetheria may consider herself a "Oceanic" named after her species rise from an ocean.
However, the mortal enemies of her species may refer to them as "Crabbies."

A human from mundane terra will call themselves Joe. 
They scientifically call themselves homo sapiens.
To Joe, and other mundane terrans, we call ourselves humans.
However, the cetaceans on mundane terra call us "Meat Sacks."

Alien names are pronounceable in common parlance.
Aliens that communicate with pheromones, howls, or ultrasonic clicks will only use those names amongst their species.

The indigenous denizens of newly discovered planets have no names.
Flora and fauna do not give themselves names, and it is up to the players to name them.
Until that time, the referee may assign serial numbers to identify the creatures.

== Examples

Kolosaur::
Kolosaur is a member of the species Herbiforous Giganticus.
She looks like a lumbering elephant in shape and size.
Her ferocious t-rex head and mouth are in contrast to her gentle plant-eating lifestyle.
She is bright red and covered in flowing hair.
Kolosaur is not docile and has strong opinions about food.

Spink::
Spink Parlor is his full name.
He never refers to his species Slitheracine Amicus.
Spink has jet black leathery skin and moves about like a slug that can also fly.
Spink is very formal and prefers to go by the name Mr. Parlor.

Spot the Feisty::
This alien is a Pernicious Winged Scalamander.
Spot has minimal language and befriended the expedition because they have its favourite food.
Winged Scalas used air hunt in packs, but Spot is happy to stumble around with his funny-looking new brood.

== Species Names
Aliens fall under the faux taxonomy of EXP and their psuedo scientific name is based on their alien shapes.
The player can make her own Genus and Species for her alien. 
If help is needed the Genus name is based on the Torso of the Alien, and the Species is based on the species of the alien
The following giant table includes a host of fake Latin and Greek sounding roots based on the body part types. 
Many of them are just plain silly. 

include::aliens:partial$shapes_to_faux_nomenclature.adoc[]


