= Name
The player must name her persona.
Every persona must have a moniker, call sign, label, title, handle or cognomen.
A player should avoid naming her persona with her mundane world real name.
Creating a persona name makes role-playing more fun.

Naming aliens can be complex.
Aliens are brand new life forms within the faux taxonomy of the alien family.
Naming aliens requires a moniker, a taxonomy and common name. 
The player may name her persona Bob, but Bob may be one member of an alien species. 
This requires additional naming as well. 

.*Alien Naming*
* Moniker (Zetheria) -- player's choice
* Taxonomy(Crustacae Iritii) -- <<_species_names,help is below>>
* Common Name (Crabbies) -- referee and milieu dependent

The persona will interact with her compatriots using her her moniker "Zetheria."
The alien also has a taxonomy like "Crustacae Iritii."
There is often a common name that may be self referential or given.
Zetheria may consider herself to a member of the "Oceanicas".
However, the mortal enemies of her species may refer to them as "Crabbies."

== Moniker
The player is responsible for coming up for her alien's moniker.
The moniker is the name that the persona uses to interact with the other personas.
It is expected that there is a language that allows the expedition members to communicate.
Often the moniker the players chooses is all that is required to start having fun. 
Taxonomy and common names are quite optional. 

Alien names are pronounceable in common parlance.
Aliens that communicate with pheromones, howls, or ultrasonic clicks will only use those names amongst their species.

If some inspiration is needed jump to xref:referee_personas:rp_story_cues.adoc[Referee Persona Story Cues,window=_blank]

== Taxonomy
Aliens fall under the faux taxonomy of EXP and their pseudo scientific name is based on their alien shape.
The taxonomy is for the entire alien species and typically has a Genus and Species. 
The player can create her own Genus and Species for her alien persona.

The genus is named after the torso of the alien, and the species is named after the head of the alien.
So an alien with the body of a lion and the head of a tarantula could be assigned the taxonomy of Rorius Arachnida.
If you are having troubles there is a list you can jump to <_faux_taxonomy_list,Faux Taxonomy List>
Many of them are just plain silly. 

Aliens with language and society may well have assigned their own taxonomy. 
However the flora and fauna of newly discovered planets have no taxonomy, and it is up to the players to assign one.
This is the bread and butter of the biologist vocation.

== Common
For aliens the common name could be their species names, or their society's name.
Only aliens with language and culture can name themselves. 
Flora and fauna are usually named by those around them. 
For example, Bov Taurus are called cows on mundane terra.

A human from mundane terra goes by the moniker of Joe. 
Toe's taxonomy is homo sapiens.
Joe considers himself a human.
However, the cetaceans on mundane terra call Joe a "Meat Sack."

The common name of a brand new alien species will likely require discussion between the referee and the table.

== Examples

Kollie::
Kollie looks like a lumbering elephant in shape and size.
Her ferocious t-rex head and mouth contrasts her gentle plant-eating lifestyle.
Kollie is not docile and has strong opinions about food.
Moniker: Kollie, Taxonomy: Herbiforous Giganticus, Common: Kilosaur.

Spink::
Spink has jet black leathery skin and slimes about with his slug torso but can also fly.
Spink Parlor is his full name.
Spink is very formal and prefers to go by the name Mr. Parlor.
Moniker: Mr Parlor, Taxonomy: Slitheracine Amicus, Common: none. 

Spot the Feisty::
Spot looks like a salamander with bat wings. 
Spot has minimal language and befriended the expedition because they have its favourite food.
Spot usually hunts in a pack, but Spot is happy to stumble around with his funny-looking new brood.
Moniker: Spot, Taxonomy: Pernicious Winged Scalamander, Common: Winged Scala. 

== Faux Taxonomy List
include::aliens:partial$shapes_to_faux_nomenclature.adoc[]



