= Alien Size

:art: alien_very_small.png
:width: 250px
:snark: Size can matter.
:artist: unknown, HM
:date: unknown, 2017
:license: CC BY-SA 4.0
:description: Drawing of clawed foot about to step on very tiny alien.

include::ROOT:partial$articulate.adoc[]

The size of an alien is not just a descriptive element.
The player generates size early in her persona's evolution because it impacts so many other alien attributes.
The alien's size determines hit points and damage amounts.
The player rolls on the Alien Size Table to determine the alien's size.

== Size
Size is a qualitative description of the alien's size.
It lack wate and hite information. 
Often the qualitative size of the alien is good enough for the players.
Alien size is randomly determined for persona aliens. 

include::aliens:partial$size_category_list.adoc[]

The player rolls five 1d100's and adds 100 for her large size alien. 
Rolling 39, 41, 11, 89 and 67 gives her alien a wate of 347 kgs.
Her alien has no description, no name, or abilities, but its wate is 347 kgs.

=== Attributes and Size
The referee may choose to adjust the alien's size based on her attributes.
Attribute alien size adjustment is an optional rule.
Like all rules.

Stronger creatures tend to be larger and dextrous creatures tend to be smaller.
The player adds her persona's Strength and subtracts her persona's Dexterity from the Alien Size Table result.
An alien with a 22 STR and a 12 DEX would add 10 to her Alien Size Table result.
A die roll of 67 increases to 77, and the alien moves from medium sized to large sized. 

:art: alien_humongous.png
:width: 250px
:snark: Humongous aliens are hard to play.
:artist: Virgil Finlay
:date: 1966
:license: CC BY-SA 4.0
:description: Drawing of two humans staring into an alien larger than both of them. 

include::ROOT:partial$articulate.adoc[]

=== Size Matters
Bigger is not always better.
The larger the alien, the more HPS it has and the more damage it can deliver.
Large and gigantic aliens are challenging to play.
The technology of EXP is for anthros, not 500kg aliens. 
Vehicles won't fit.
Armour is unwearable.
Large rifles are clumsy little sticks.
An enormous size is a constant roleplaying challenge.
The analogy is the same for tiny aliens.

Two alien sizes do not appear on the Alien Size Table.
These are minute and humongous.
Minute aliens have wates less than 1kg, and Humongous aliens have wates in the hundreds of tonnes.
These extreme alien sizes are only for referee personas.

== Wate 
Alien wate is determined by size and can be rolled based on the outcome in the above table.

== Hite
Most of the time the qualitative alien size will be adequate for most play.
However, the actual space occupied by the alien may be important. 

include::aliens:partial$alien_wate_to_hite_estimation.adoc[]

=== Reach
The reach of an alien is how far away from it's torso can it impact the world.
The reach of an anthro is easily understood by referees and players alike. 
However the reach of an alien with a cow shaped body and octopus arms may not be as clear.
Once extremes of size are added into the size "reach" can become complicated indeed.

Typically the alien's arms will be it's reaching limbs. 
If an alien has no arms reaching may not be part of their existence or they can use their legs. 
Reach only applies to grabbing objects or strike attacks. 
Reach does not apply to fling attacks, shoot attacks or psionic evolutations.

Small and Tiny alien reach is limited to the hex that they are in.
Medium and large aliens can reach into the adjacent hex.
Gigantic aliens can reach through the adjacent hex and into the next hex over.

[discrete]
== if you need to know
Wate to Size estimates is based on the following. 

. 1 tonne of meat occupies 1 cubic meters
. 1 cubic meters is 1 x 1 x 1 meters of volume, or half a hex
. very roughly 2 tonne of meat is 1 hex of Hite






