= Alien Society

Alien society decides whether the species is local fauna or a galactic empire.

Alien society is something for the referee to consider and prepare for her campaign carefully.
Alien societies can be the basis for an entire campaign.
The differences in values, architecture, and social organization are beyond this game's scope.
This section outlines a light skeleton of an alien's society.

The alien society has no impact on the player's choices with her alien persona.
Almost all player personas are rogues and outcasts cutting their paths in the dusty universe.
Alien player personas should be the same. 

The most pressing questions a player will ask are: Do I have language?  Can I use tools?
Player personas should have a language to communicate with their fellow expedition members. 
Purist use of aliens would leave this to chance.
Referees tend to leave tool usage and vocations to chance. 
Just one gigantic alien anti-knite, and the referee will have to restructure her whole campaign.

NOTE: Society sits on top of Biology. Both inform each other. 

== Alien Society Build
. <<_language,Language>>
.. Language Check
.. Tool Score Check
. <<_culture,Culture>>
** *if NO Language NO Culture checks*
.. Culture Check
.. Tool Score Check
.. Religion Check
. <<_education,Education>>
** *if NO Culture NO Education checks*
.. Education Check
.. Tool Score Check
.. Politics check
. <<_alien_vocation,Vocation>>
** *if NO Education NO Vocation checks*
.. Vocation Check
.. Tool Score Check
.. Philosophy check

If one thinks a complicated flowchart will help jump to <<_alien_society_flowchart,Flowchart>>.

== Language

:art: cunning_charisma.png
:width: 350px
:snark: The universal language of vulnerable.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Six legged bunny with huge eyes crying.
include::ROOT:partial$articulate.adoc[]

All aliens get to check for language and rudimentary tool use. 

=== Language Check

.Chance = 3 * INT score
****
An alien with a 12 INT has a 36% chance of having language.
****

This die roll determines if the alien species has a natural language or not. 
For the alien species to have language, the player must roll less than or equal to three times her persona's Intelligence attribute.

If there is no language, the alien species *cannot have a culture, education or vocation*.
An alien species without language can only communicate biological nees amongst their kind.
These communications are not translatable and are meaningless to translators.
An alien species with no language is flora or fauna and dependent on the biome to survive.

Alien species with language can communicate through translators and have concepts beyond eat, drink and love.
An alien species with language can evolve to have a culture, education and vocations.

NOTE: Player persona aliens should automatically have language to participate with the expedition.

=== Language Tool Check
.Chance = 2 * DEX score
****
An alien with a 12 DEX has 24% chance to add +1 to the alien's tool score. 
****

Regardless of the alien language check result, the player makes a tool score check.
This first tool score check depends on the persona's Dexterity score and not her Intelligence score.
All other tool score checks depend on the persona's Intelligence.
To increase the alien species tool score, the player must roll less than or equal to two times her persona's Dexterity score.

If an alien species has no language and a tool score of one, the aliens can transiently use simple machines.
Aliens that lack language but can use tools are an edge case where curiosity and dexterity lead to random intermittent tool use.
Language negative, tool positive aliens have no tool memory, and cannot use artifact tech tools or build artifacts.

== Culture

The alien must have language before making any culture checks.

=== Culture Check
.Chance = 3 * CHA score
****
An alien with a 12 CHA has a 36% chance of having a culture.
****

This die roll determines if the alien species has a cultural structure or not. 
An alien species cannot evolve a culture without language.
For the alien species to have culture, the player must roll less than or equal to three times her persona's Charisma score.

If there is no culture, the alien species *cannot have education or vocation*.
If the alien species has no organized culture, it may still have a hierarchy within its grouping. 
The alien group's hierarchy may depend on size, speed, strength or charisma. 
If the alien species has no culture, it operates in isolation and cannot plan beyond the immediate grouping or family unit.

If the alien species has a culture, they can work together from grouping to grouping. 
Culture allows the aliens to band together and communicate. 

=== Culture Tool Check
.Chance = 2 * INT score
****
An alien with a 12 INT has 24% chance to add +1 to the alien's tool score. 
****

To increase the alien species tool score, the player must roll less than or equal to two times her persona's Intelligence score.
The higher the tool score, the more adept the species is with technology.

=== Religion Check
.Chance = 2 * INT score - MND score
****
An alien with a 12 INT and a 6 MND has 18% chance of having religion. 
****

There is a chance that an alien species with language and culture will develop a religious persuasion.
The religious persuasion's flavour is determined on the table immediately following the religion check. 
A failed religion check has no impact on the alien species evolving education.

include::ROOT:partial$CH11_Table_Referee_Persona_Religious_Belief.adoc[]

== Education

The alien must have language and culture before making any education checks.
 
=== Education Check
.Chance = 3 * AWE score
****
An alien with a 12 AWE has a 36% chance of having an education system.
****

This die roll determines if the alien species has an educational system or not. 
An alien species will not evolve education without culture and language.
For the alien species to have culture, the player must roll less than or equal to three times her persona's Awareness score.

If the alien species has no education system, they tend to learn by trial and error.
While individual aliens may be bright, the culture will seem less so. 
This alien species will repeat its failures and forget its victories.

Education indicates that the alien species trains and teaches its members about the biome and beyond. 

=== Education Tool Check
.Chance = 2 * INT score
****
An alien with a 12 INT has 24% chance to add +1 to the alien's tool score. 
****

Regardless of the alien education check result, the player makes a tool score check.
To increase the alien species tool score, the player must roll less than or equal to two times her persona's Intelligence score.
The higher the tool score, the more adept the species is with technology.

=== Politics Check
.Chance = INT score + CHA score
****
An alien with a 12 INT and a 12 CHA has 24% chance of having politics. 
****

There is a chance that an alien species with language, culture and education will develop a political system. 
The political system's flavour is determined on the table immediately following the politics check. 
A failed politics check has no impact on the alien species evolving vocations.

include::ROOT:partial$CH11_Table_Referee_Persona_Political_Belief.adoc[]

== Vocation

The alien must have language, culture and education before making any vocation checks.

=== Vocation Check
.Chance =  AWE + DEX + INT score
****
An alien with a 10 AWE, a 12 DEX and a 14 INT has a 36% chance of having vocations.
****

This die roll determines if the alien species can pursue vocations or not. 
An alien species will not develop vocations with education, culture and language.
For the alien species to have vocations, the player must roll less than or equal to the total of her persona's Awareness, Dexterity and Intelligence scores.

If the alien species do not have vocations, they lack specialization in their culture. 
There may be all kinds of Nothing jobs, but there will be no mercenaries, mechanics, or veterinarians.
Their culture and society may still have healers and warriors, but they will not benefit from a vocation.
 
If the alien species can pursue vocations, the player can choose from any field available to her persona.
EXP does not differentiate between anthros, aliens or robots pursuing vocations. 
Keeping in mind that alien persona vocations should be rare is not without hazard.
The referee may invoke class restrictions she feels are necessary to ensure a game balance.
An invisible, 900 kg, flying spie alien persona is a possibility.

=== Vocation Tool Check
.Chance = 2 * INT score
****
An alien with a 12 INT has 24% chance to add +1 to the alien's tool score. 
****

Regardless of the alien vocation check result, the player makes a tool score check.
To increase the alien species tool score, the player must roll less than or equal to two times her persona's Intelligence score.
The higher the tool score, the more adept the species is with technology.

=== Philosophy Check
.Chance =  INT + AWE score
****
An alien with a 12 INT and a 12 AWE has 24% chance of having philosophy. 
****

There is a chance that an alien species with language, culture,  education, and vocation will develop a philosophical outlook. 
The philosophical outlook's flavour is determined on the table immediately following the philosophy check. 
If the alien species has both religion and philosophy, the referee can decide if they contrast or complement each other.

include::ROOT:partial$CH11_Table_Referee_Persona_Philosophical_Belief.adoc[]







== Tool Usage
The most critical evolutionary advance of any alien species is its relationship with technology.
Tool usage is discussed in detail at xref:aliens:tool_usage.adoc[Tool Usage].
Questions about using anthro artifacts, alien artifacts and general technomagical shenanigans is covered there.

== Alien Society Flowchart
The flowchart below may help navigate the complicated process of creating an alien society.
Red arrows indicate the failure of the player's die roll.
Green arrows indicate the success of the player's die roll.
Black arrows indicate movement that is independent of any die rolls.

:art: deeper_society.png
:width: 750px
:snark: Misused flowchart for society
:artist: HM 
:date: Feb-2021
:license: CC BY-SA 4.0
:description: Flowchart laying out options for alien societies.

include::ROOT:partial$articulate.adoc[]

== What are the chances?
A Python script using the flowchart above did some rudimentary modelling of alien society compositions.
The image below shows the outcomes of 10000 iterations of the alien societies. 
Each iteration used randomly generated attributes. 
The term creator replaced AI for the tool user score of 4.
Creators are rare indeed. 

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

:art: alien_society_data_10K.png
:width: 500px
:snark: Safety in numbers.
:artist: HM
:date: 2019
:license: CC BY-SA 4.0
:description: Screen capture showing chances of alien societies after 10000 iterations. 
include::ROOT:partial$articulate.adoc[]

.Societal Compositions
* Language 36%
* Culture 11%
* Education 4%
* Vocation 1%

.Tool Usage Frequencies
* None 52%
* Simple 38%
* Tech 8%
* Comp 1% 
* Creator 0.1%

