= Tool Usage

The most critical evolutionary advance of any alien species is its relationship with technology.
In EXP, the alien species tool score determines this relationship.
The tool score may increase from zero to four as the player checks against her persona's Dexterity and Intelligence scores.
There is a slight chance that a fully developed alien civilization may have no use for tools at all.
There is no chance that an undeveloped alien civilization will be technologically advanced.
The player looks up her alien species' technological adeptness on the Alien Tool Score Table.

An alien's tool score is calculated by evolving it's xref:aliens:society.adoc[Society].
The alien must be a tool user the tool score can be quickly calculated using a 1d4.

include::aliens:partial$tool_use_categories.adoc[]

None::
The alien species has no concept of a tool. 
They would never consider an artifact as anything other than a rock or branch to step over.
This tool ignorance transcends language, culture, and education.

Simple::
Simple tool usage is limited to non-powered tools that require constant physical effort.
These tools depend on the environment of the alien's biome.
If the alien species has *no language*, the tools are limited to the temporary use of sticks or rocks. 
If the alien species has *language*, they can have re-usable tools and employ wind, water and gravity to their advantage.

Tech::
This alien species utilizes any device that reduces their physical workload. 
These devices can use electricity, steam, and springs.
They have complicated clockwork machines but no computational devices. 

Computers::
This alien species can use electronic devices that can replace all physical work.
These devices include computers, telecommunications, and encryption.
There may be rudimentary robots and faux autonomous Intelligence.
As a species, homo sapiens of mundane terra is at this level.

Creators::
There is no limit to what creators can make and create.
Creator alien species have space travel, special drives, autonomous Intelligence, robots, and more.
Creativity is their only limit. 
An alien species can reach creator level tool use without evolving vocations.

:art: alien_powered_armour.png
:width: 350px
:snark: Alien sporting powered armour.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Tortoise with a cybernetic eye and a machine gun on it's shell.
include::ROOT:partial$articulate.adoc[]


// An alien species will only have a written language have a tool use score of at least one.

=== TOYs as Alien Artifacts
The player can generate one artifact from TOYs if her species has a Tech or higher tool use score.
The TOY will be a bespoke artifact tailored to the alien's shape.
If the alien persona has a vocation, the player generates artifacts from TOYs as per her vocation.
All vocation based TOYs will be bespoke artifacts tailored to the alien's shape.

NOTE: Alien artifacts come unidentified, the same as anthro artifacts.

:art: alien_creator_class.png
:width: 450px
:snark: The equipment will suit the alien.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Blob of tentacles with boots and an helmet running.
include::ROOT:partial$articulate.adoc[]

=== Adapting Non-Alien Artifacts
Artifacts and equipment in EXP are anthrocentric. 
Alien tool users can implement these artifacts through adaptive use.
Adaptive use is when the alien uses her tongue instead of a finger to manipulate equipment.
The chance of successfully adapting to an artifact is equal to twice the alien's combined Dexterity and Intelligence scores.

=== Adaptive Use Check
.Chance =  2*DEX + 2*INT
****
An alien with a 12 DEX and a 12 INT has 48% chance of adapting a stinky anthro device. 
****

If the player fails this roll, the alien *cannot* use the artifact.
Biologists and veterinarians can assist the alien in adapting to a  device allowing for another chance at adaptive use.
 Mechanics can assist the alien by altering the device, allowing for another adaptive use chance.

=== Non-Tool Users and Artifacts
Most aliens will be non-tool users.
The referee may automatically allow alien personas to be tool users to increase their involvement in the game.
The referee should not depend solely on the dice rolling of her players.
If a player comes up with an ingenious idea about how her persona can manipulate an artifact, the persona should do so.
Role-Playing should overcome dice rolling.

In past versions of EXP, non-tools users could overcome the technological deficit. 
This die roll exception is no longer the case, and for a player persona alien to use tools is up to the referee and players. 
