= Playing EXP



// FIXME woman running exp campaign at table 

== What is this? 
EXP: The Game of Technological Chaos is a paper and dice Sciency Fiction role-playing game. 
It is *not* a POV shooter video game, movie, or app. 
You play EXP with dice and real people all sitting in the same room. 
Enjoy.

== Why is this?
EXP: The Game of Technological Chaos evolved from the role-playing games of the late 1970s.
Dungeons and Dragons, https://en.wikipedia.org/wiki/Gamma_World[Gamma World], and https://en.wikipedia.org/wiki/Metamorphosis_Alpha[Metamorphosis Alpha]. EXP comes from a home brew based on Metamorphosis Alpha.
https://en.wikipedia.org/wiki/Jim_Ward_(game_designer)[James Ward] is our hero.

== How is this?
The game is played using the document you are reading now. 
Folks get together and meet in real life and play EXP as a tabletop role playing game.

== Mission
Help create a less worse world through role playing and speculative fiction.

.*Achieve this mission by...*
* Developing a ruleset and toolset that is accessible, affordable, understandable, and universal.
* Developing a flexible ruleset that allows players to ajudicate decisions as a common experience.
* Developing a generic mythos that allows players to share experiences of their own creation.
* Developing a toolset that automates and eases player participation.
* Removing barriers of cost, culture, and accessibility to the role playing experience.

== Vision
A less worse world through mundane terrans sharing a Sciency Fiction role playing experience.

.*Measure this vision by...*
* A version controlled ruleset and toolset that is freely available online, offline, and in print.
* A community of kind supportive people that contribute to the ruleset and toolset.
* The translation of the ruleset, toolset and mythos into many languages.
* The acceptance that role playing games are synonymous with improvisation.
* The acceptance of TTRPG 2.0 being tabletop RPGs that integrate rulesets, toolsets and improv goals.

== A Deeper Dive
The first introduction to EXP was very long.
There were very few role-playing games.
There was no internet.
There were no cell phones.
There were no laptops.
Very few people knew what an "RPG" was, and those that did feared them.
Much of the first introduction explained how EXP fits into society.
Today there are thousands of role-playing games.
They are on tabletops.
They are on computer screens.
They are on phones.
They are in virtual reality.
Today "RPG" means role-playing game and not a rocket-propelled grenade.

=== What does EXP mean?
The working title of the homebrew was EXP1000.
EXP stood for EXPerimental, EXPerience points and EXPeditions.
role-playing was an important source of EXPerience points. 
It was unique at the time to award experience for anything other than combat success.
The players formed EXPeditions instead of parties.
Combat employed a 1000 sided die instead of a 20 sided die.
EXP proved easier to say than EXP1000.
The extensive artifact system became the centrepiece of the game, and the official title became "EXP: The game of technological chaos." 

=== Why do such a thing?
In the 1970s, science fiction was not a large part of the role-playing world.
There was a game called Dungeons and Dragons, which was a collection of tiny incomplete booklets.
Traveler was also a disorganized collection of tiny booklets.
We were fans of post-apocalyptic speculative fiction, especially anything with mutants and robots.
The author James Ward came to our rescue with Metamorphosis Alpha and Gamma World.
We loved the concepts but not the rules.
EXP1000 was entirely derivative from those two games.
We used miniatures and hex paper to sort out combat.
The system reflected the meticulous war games of the day.
Combat resolution was tactical, detailed, and obsessive.
A twenty-sided die was not refined enough for us.
We devised a thousand sided die by rolling three ten sides.
The 1 to 1000 range allowed us to give subtle bonuses or penalties on the hexagonal mat.
EXP mashed Metamorphosis Alpha, Gamma World and tactical miniature combat into one book. 

=== EXP as a reference book
In the 1980s, role-playing games became an industry. 
Publishing houses devoted to role playing games came to be. 
The economics of book production, and profits, lead to dividing game systems into supplements and modules.
This parceling of product continues today. 
Decades ago EXP consciously chose not to follow this path.

.*EXP Followed these principles*
. Create a generic Sciency Fiction role-playing game.
. Create one tome that contained all content.
. Wait decades for this internet thing to catch on.

Initially, EXP was a book. 
Books were costly to print.
Technology has advanced, and we no longer have to print a 777 page book.
The intertubes and open source licensing has allowed EXP to be available to all.
Version 6.0 is a rewrite and a move to technologies that will allow EXP to be readily shared.

EXP is no longer a book but a living document that will:

. Be kept in a versioned repository.
. Be free and open source.
. Allow for multiple authors.
. Be downloadable as a book or website.

=== Newbies
This section used to be labelled Neophytes.
The section included explanations of how to start a group etc.
role-playing games are now omnipresent.
To get started role-playing today, one can head to the local game store or search online.
You are guaranteed to find like-minded folks, although they are unlikely to be playing EXP.

Be safe and have fun.

=== Concerned Parents
In the 1990s, every role-playing game had a section that tried to calm concerned parents.
A bored media created a moral panic around role-playing games, and police forces raided game producers. 
Today parents are concerned if their children are *not* playing role-playing games.
Today, families, churches, libraries and game stores all host role-playing games.
role-playing games improve numeracy, literacy, creativity and social skills.
A concerned parent today buys, downloads or creates a role-playing game to play with the whole family.

=== Style of EXP
EXP, the game of technological chaos, is a Sciency Fiction RPG. 
If you think of a role-playing game's style, you think of its mythos and ruleset.
EXP has a generic mythos.
The system is for players that want to create their own story. 
EXP ruleset has many detailed resolution systems.
These resolution systems vary from insidiously complex to refreshingly simple. 
The system is for players that want to build their own house rules, and EXP works fine using a fraction of its ruleset.

If the following paragraph works for you, then EXP will work for you.
A humanoid gorilla, a robot and a tentacled alien run into a spaceship's bar.
On their heels are a group of angry mutants driving a stolen yellow bus.
The gorilla fires her laser rifle at the yellow bus.
The tentacled alien spits poison at a mutant leaning out a window.
The robot activates her electronic countermeasures.
An angry mutant launches the psionic attack mental blast at the gorilla.
The yellow bus driver fails to navigate in the parking lot and crashes the yellow bus. EXP has integrated rules for all of these shenanigans in one ruleset. 

=== EXP is silly
role-playing is supposed to be fun.
EXP is not hard science. 
EXP is pseudo-science, Sciency Fiction or even silly science.
The families, rules and technology are ironic and border on the ridiculous.
The element of randomness is endemic in all of EXP's rules.
This random factor ensures that EXP proudly crosses the border of ridiculousness.
EXP wallows in the pink and green light of the absurd.
There will be nuclear-powered toasters, combat robots with welcome mats, and fun-loving aliens. 

=== EXP is Very Random
Personas are determined randomly.
The players adapt to their random personas.
Technological equipment is determined randomly.
The technological level of equipment is determined randomly.
Mutations are acquired randomly.
The game has a whole lot of dice rolling that is best suited for computer assistance.
It has only taken 40 years, but computer assistance has arrived and is plentiful.

[quote]
____
*EXP is the game of technological chaos, and the dice introduce the chaos*
____



=== Her, him, huh?
:art: alien_not_aliens.png
:width: 450px
:snark: Military machine gun maternal mommy.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Woman on spaceship holding machine gun in right hand and little girl on her hip.
include::ROOT:partial$articulate.adoc[]

In the olden daze, role-playing games were dominated by young men. 
Regarding role-playing games in the olden daze, using the word dominated is a gross understatement.
Women in role playing games was very rare.
In an effort to make the world slightly less worse, the language of   EXP moved to be more inclusive. 
This was the 1990s kind of 'trying to be inclusive.'

The writing shifted to the pronoun 'her.' 
This was felt to be more inclusive because the pronouns her and she both included the pronoun he.
Using the pronoun 'her' was quicker and easier than other solutions at the time.

role-playing games must intentionally become more welcoming, and should create a safe space for all genders, races and sexualities. 
Using the pronouns 'her and she' was prescient and is now outdated. 
Our actions must be more intentional and systemic than just changing some words.
Talk minus action equals nothing. 

=== The Plague Years
During the plagues of the 2020s folks got together on-line and played.
EXP did *not* become a POV shooter video game, movie, or app.
We still play with real people but not around the same table.
Below is the combination of tools we use to play EXP during the plague.
These tools offered the least number of barriers to having fun.
All are free or have free versions.

.*Playing EXP Online*
. https://shmeppy.com[Shared Mapping]
. https://rolz.org[Dice Rolling, text chat and persona records]
. https://zoom.us[Voice and video chat]

.*All In One Virtual Table Tops*
. https://foundryvtt.com[The best one]
. https://roll20.net[The expensive one]