= Introductory Glossary

Below is a brief glossary of terms and abbreviations that are unique to EXP.
This section should help neophytes on board to EXP and give experienced players some translational terms. 
There is a much more exhaustive, and exhausting, list in the xref:appendices:Appy_A_Glossaries.adoc[glossaries section,window=_blank]. 

4D2::
Four rolls of a six sided die are added together to generate a digit between +10 and -10. 
This is a die roll unique to the Role Playing System. 
For more info about this go to xref:role_playing_system:CH26_Fourdeetwo.adoc[Four D Two].

Alien:: 
Aliens are one of the three families in EXP.
They are organic creatures of unusual shape and size.
They are alien to us but not to themselves.
These are the tentacled, furry, floating horse creatures.
Only experienced players should try playing alien personas.

Anthro:: 
Anthro is short for anthropomorph.
Anthros are one of the three families in EXP.
They are upright and bipedal, and function the same as homo sapiens.
They are phenotypically humanoid versions of creatures from the animal world.
Players are most familiar with playing anthro personas.

Artifact::
A piece of technology that has value due to it's technological ability. 
If the piece of technology has not been identified it is referred to as an artifact.
Once identified an artifact becomes a piece of equipment.

Attack Type::
There are different ways to attack in combat. 
Attack types are differentiated by how they deliver damage. 
The three attack types are Strike, Fling and Shoot.

Attributes:: 
These are the imaginary divisions of a persona’s physical abilities.
The attributes in EXP are: Awareness, Charisma, Constitution, Dexterity, Intelligence, Strength, Mind, Hit Points and Social Standing. 
They are also called statistics.

Bot:: 
Shortening of the word robot. 
Robots are inorganic creatures of metal and computer Intelligence. 

Campaign:: 
This is the story generated by the referee and the players.
A campaign is built from scenarios.
The scenarios can involve many personas and different locations. 
A campaign can last for months or years.

Decidie::
Legacy name for a 1d100. 
Two dice are used to create results between 01 and 100.
It is pronounced decki die.

Dice::
Gravity driven random integer generators which are rolled or thrown to generate numbers. 

Die roll:: 
A die roll indicates that a random number must be generated. 
The player grabs the appropriate gravity driven random integer generator.
The die is rolled onto the table and the random integer is revealed.
Hence the term die roll.

Evolutation::
An imaginary biological adaptation bespoke to a specific alien species.
Evolutation (mutation) give the alien imaginary powers. 

Exatmo:: 
Short for exterior to atmosphere.
Anything that takes place in the vacuum of outer space. 

Expedition::
A group of personas that have joined forces as a cohesive organized team.

Experience Points:: 
Experience points are the currency of knowledge.
They are a combination of learning, maturation and training.
The more experience points the better the persona is at everything. 

Fling::
An attack type where the persona maked a ranged attack using her own strength. 
Arrows and rock are fling attacks.

Level::
The persona's experience level.
The more experience points the higher the level. 
The higher the level the better the persona is at stuff.

Family:: 
The three families in EXP are anthro, alien and robot.

Hex (h):: 
A hex, short for hexagon. 
The hexagon is a six sided figure.
Hexagons can interconnect to create a hex field. 
The hex field is used to portray tactical combat on the table top. 
A hex equals 2 metres. 

Hexes per Unit (h/u):: 
This is an arbitrary measure of movement in EXP. 
It is equal to m/s.

Hite:: 
A unique measure to EXP that means height.
It can also be used to compare sizes regardless of family type.
Hite is usually recorded in centimeters (cm).

Inatmo:: 
Short for in atmosphere.
Anything that takes place in normal atmosphere.

Intensity:: 
Intensity represents the strength of a poison or psionic attack. 
The higher the intensity, the more dangerous the attack.

Kilodie:: 
A Kilodie generates a random number between 1 and 1000. 
xref:roll_playing_system:CH00_kilo_die_mechanic[Details about the kilodie, window = _blank]
It is pronounce Kee Low Die, not Kill Oh Die. 

Level:: 
A short form of experience level.
A persona's level represents how good she is at combat and skills.
The experience level increases with the persona's experience points.

Malfunctation::
An imaginary peripheral mulfunction bespoke to a specific robot.
Malfunctations (mutation) give the robot imaginary powers. 

Milieu::
The milieu is the description and social mechanics of the fantasy world the persona's interact with.
The referee creates most of the milieu with descriptions and backstories.
The players contribute and shape the milieu through their personas.

Miss:: 
A miss is any failed roll.
A failed attack roll is called a miss.
An unsuccessful poison defence roll is a miss. 

Movement:: 
Movement is the changing of position of personas during combat. 
Each persona has a movement rate in hexes per unit.
This is the speed of the persona.

Mundane Terra::
Earth. 
The most likely place you are reading this.

Mutation:: 
Mutations are imaginary biological adaptations.
They can give personas imaginary powers.

Persona:: 
The persona is the representation of the player in the imaginary world.
The persona can be controlled by a player or a referee.
Each persona is made up of attributes, description and story.

Percentiles::
Legacy name for a 1d100. 
Two dice are used to create results between 01 and 100.
Percents and percentile dice are the same.

Persona Record::
This is the persona record sheet.
It is a piece of paper or computer thingy that stores the persona's info.
Also called a character sheet.

Phenomics::
Sciency fiction things that a persona's body can do.
Previously called phenomic mutations.

Phenotype::
Phenotype is the physical appearance of an organism. 
In EXP life forms are arranged phenotypically, or by appearance. 
Anthros are all humanoid, robots look mechanical and aliens look alien. 
This ignores biology for purpose of telling fun stories. 

Portmanteau::
When words are combined to create a new world. 
This happens a lot in this text. 

Psionics::
Sciency fiction things that a persona's brain can do.
Previously called psionic mutations.

Strength::
This is an attribute of the persona.
Strength represents leverage, power and external physique.
It is abbreviated STR.

Post Factualization::
Reverse improvisation to explain something that happened after it has happened. 
Commonly needed by referees when story and pseudo science need to be synched.

Player:: 
You, the reader. 
The real world persona that controls the fantasy world character called a persona.

Ref::
Short for referee. 
This is a player that is burdened with creating the milieu and puzzles of the campaign.
The role of referee is typically played by one player.
However the role of referee can be rotated or shared amongst multiple players.

Referee Persona (RP):: 
A persona that is generated and played by the referee. 
It includes aliens, anthropomorphs and robots. 
These are also called non-player characters.

Ref's Own Table:: 
This comment is found on tables used to generate EXP chaos.
It indicates that the referee and players should create something new. 

Robot:: 
Robots are inorganic creatures of metal and computer Intelligence.
One of the three families in EXP.
Robots develop consciousness through malfunction. 
Robot personas should be limited to experienced players. 

Run::
Run refers to players getting together and playing EXP.
Run also refers to playing (or running) a persona.
A run is also called a scenario.

Scenarios:: 
Scenarios are the stories and challenges that take place in the game.
A scenario could be combat, puzzles, or some combination. 
Enough scenarios will build a story arch called a campaign.
These can also be called runs.

Shoot::
An attack type where the persona makes a ranged attacked that is aimed by her dexterity and powered by technology.
Guns and lazers are shoot attacks. 

Strike::
An attack type where the persona makes a melee attack using her own strength.
Swords and fists are strike attacks. 

Table::
Refers to the group of players that are playing together.

Toys (TOYS):: 
Toys are artifacts created on the Technological Object Yield System.
Toys are devices which personas use to gain strength and power.
Toys are like magical items from fantasy games.

Unit:: 
The unit is the smallest component of combat time in EXP. 
All personas will move, attack or do part of something during each unit. 
A unit of combat may take ten minutes or an hour of mundane time to play.
The combat unit is 2 seconds.

Vocation:: 
This is a collection of innate abilities that the persona has.
A vocation could arise from innate skill, training or school. 
Also called a class.

Wate:: 
A unique spelling of the word weight in EXP., 
The wate includes inertia, mass, and general size. 
