= Playing Personas

The player is you. 
As a player, you control a persona.
The persona is a piece in the game, the player's tool that allows her to play the game.
Usually, a player has one persona.
In other games, personas are called characters, avatars, and actors.

The referee is also a player.
She is a player who takes on some additional roles.
The referee sets up the puzzles for the players to solve.
She interacts with the players using referee personas.
Referee personas interact with player personas and are essential to creating the story.
A referee will have many referee personas.
Referee personas will vary from insignificant bystanders to critical components of the story.  

The personas create a common ground for a shared experience amongst the players.
This shared experience takes place in the most fantastic simulator of all, the human brain.

:art: beaver_teeth_preserver.png
:width: 350px
:snark: I WANT LONG TEETH!
:artist: JEShields, modded HM to no blood
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Angry humanoid beaver waving a chainsaw.
include::ROOT:partial$articulate.adoc[]

== Parts of a Persona
The persona has three essential components. 

* the player
* the description
* the persona record 

=== The Player
The most important part of the persona is the player.
A persona will only be as interesting, fun and descriptive as her player makes it.
The player's input into the persona is everything.
A persona is nothing but numbers on a page until the player gives it that spark of life.

=== The Description
The player needs to create a description of her persona.
A player's description of her persona creates an image in the minds of her fellow players.
Those players will have quick, fun descriptions for their personas as well.
The referee will have descriptions of all of her referee personas as well. 

The personas description does not arise from pure imagination. 
The player rolls dice in a process called persona generation. 
Persona generation generates some numbers to describe the persona's attributes like Intelligence and Charisma. 
These attributes let the player make choices about physical appearance and vocation. 

Some example descriptions.

A simple God-fearing tax collector from the orbiting suburban satellite station.::
This introduction implies certain ideals. 
It is unlikely this persona would attempt to embezzle the emperor.
She probably has high Intelligence, normal Strength and low will power.

A happy-go-lucky model QT-1 protocol unit from your local rec centre.::
This introduction imparts the impression of a sycophantic cyborg.
This Pollyanna may offer a cherry soda when faced with imminent warp drive failure.

Ssssssssthp, me Slythris, me chew hoole innards, me catch in tree place.::
This introduction is for an alien covered in scales.
The hissing words may imply its appearance is sleek, sharp-toothed and camouflaged.
One would not expect this alien to be a tool-user.

=== The Persona record
The players don't memorize every aspect of their persona.
The persona record is a record of all the persona's elements.
The sheet of paper records the persona's attributes, species, vocation, abilities and equipment.
An adequately maintained persona record helps keep track of shenanigans and keeps track of things between sessions.

The persona record is composed of a melange elements that make up a persona.

==== Persona Type
The player can choose from three different persona families: anthro, robot or alien.
The anthro family are humanoids like us, which makes them the easiest to play.
Robots and aliens are for experienced players.
The referee may also limit families and types to maintain a consistent milieu.

==== Attributes
The dice decide how strong, intelligent, charismatic a persona is.
The attributes are straightforward descriptions of what they represent.
The attribute Intelligence represents the persona's smarts. 
The attribute Charisma represents the persona's leadership skill.
There is a number attached to each attribute. 
The higher the number, the better the attribute.
A physically strong persona could lift heavy things.
Complex calculations would challenge a persona with low Intelligence.

==== Mutations
Mutations are imaginary biological adaptations.
They give personas imaginary powers or defects.
Anthro mutations are unique changes to that persona.
Alien mutations represent a biological trait of the species.
Robot mutations are unique malfunctioning peripherals.

Mutations can change everything for the persona. 
A mutation can influence the persona's name, story, and vocation.
Mutations can make a persona weak or powerful. 

==== Vocation
The persona's vocation is a mix of training, passion, aptitude and beliefs.
A vocation is associated with a clump of skills.
Depending on the milieu designed by the referee, there may be schools, guilds or apprentice programs for each vocation.
In the generic mythos of EXP, vocations are more about attitude and self-learning than schooling.

The persona's attributes determine the choice of vocation.
Smart personas will pursue science vocations. 
Hardy personas will pursue combat vocations. 
Example persona vocations are mercenary, biologist, nomad and veterinarian.

In other games, vocations are called classes, professions or jobs. 

==== Equipment
All manner of equipment is available in EXP.
The equipment varies from torches to luggage and from lazer guns to spaceships.
Mundane equipment can usually be purchased within the milieu.
Powerful high tech equipment is usually found or is the reward for solving a puzzle.
The function and purpose of high tech equipment may not be obvious to the personas.

Equipment yet to be understood are called artifacts. 
Artifacts are most often high tech devices from ancient or alien civilizations. 
Artifacts can also be useless junk.
Once an artifact is identified it is called a toy. 
There is no strict canon on the usage of these descriptors.

The expedition is supposed to work together, sharing the collective wealth of their equipment.
There will be many devices that players find that their persona does not understand.

== Expeditions
A group of personas is called an expedition.
A group of players is called a cacophony.
Players get their personas together to work as an expedition to explore the milieu created by the referee.
In other roleplaying games, an expedition is called a party or horde.

== Conclusion
The nature of roleplaying games is very social.
RPGs are for people to get together for a mutual creative experience.
Each player has a persona with a unique appearance and personality.
Groups of players form expeditions of personas that work together in the referee's milieu. 
Together they create stories and laughs.
By design, roleplaying games are a social endeavour. 

EXP The Game of Technological Chaos is a paper and dice sciency fiction roleplaying game. 
It is *not* a POV shooter video game, movie, or app.
It is *not* a persona record sheet.
It is *not* a collection of die rolls.
It is a game with real people creatively sharing and having fun. 
Enjoy.
