= Roll vs Role Playing

[quote]
____
*A tale of two systems*
____

EXP has two play tested sets of rules.
The oldest ruleset are the tactical combat rules.
The tactical combat rules work best with hex paper and miniatures and uses a 1d1000 for attack rolls. 
The tactical combat rules are detailed, dice heavy, and is the basis for the technology and mutation sections' details. 

The next oldest ruleset are the theatrical combat rules.
The theatrical combat rules is a simplified version of the tactical combat rules.
The theatrical combat rules simplifies the tactical combat rules by using simpler dice.
The theatrical system works with hundred sided, twenty-sided, ten-sided and six-sided dice.
The theatrical system sacrifices detail and subtly for speed and fun.
The theatrical combat rules now has it's own dice mechanic, but dividing down the kilodie is still an option. 

== New Words For Old Things
The most significant change in version 6.0 is the renaming of these two rule sets.
They have been teased apart and given decidedly confusing names: Roll Playing System and Role Playing System.
Each system is fun for different reasons.
The whole point of roleplaying games is to have fun.

== Roll Playing System
The Roll Playing System uses the tactical combat rules and the xref:roll_playing_system:kilo_die_mechanic.adoc[Kilodie Mechanic, window=_blank].
This ruleset works best on hex paper using miniatures and would enjoy integration with a virtual tabletop. 
The Roll Playing System depends on the roll of the dice.  
The dice direct most of the outcomes. 
A lot of arithmetic and reading is required. 
Onboarding of new players requires patience and supportive teaching. 

.*Roll Playing System is for you if...*
* You have played previous RPGs
** If you don't know what an RPG is, maybe Roll is not for you
* You like to roll dice
* You are not afraid of maths
* You like details
* xref:roll_playing_system:a_introduction.adoc[Take me there NOW!, window=_blank]

== Role Playing System
The Role Playing System uses the theatrical combat rules and the xref:role_playing_system:four_dee_two_mechanic.adoc[4D2 Mechanic, window=_blank].
The rule system does not require miniatures or hex paper but works fine with both.
The Role Playing System does not depend on the dice for decisions.
The players specifically describe the outcomes in this ruleset.
There are few tables, and only simple arithmetic is needed.
The most complicated arithmetic is adding and subtracting single digit numbers.
The persona record sheet is composed of words and almost no numbers.
It only takes a few minutes to create a persona, and the game mechanics are intuitive.
Onboarding of new players is immediate.

.*Role Playing System is for you if...*
* You have played board games and can roll six-sided dice
* You are dice averse and would rather talk
* You are not fond of remembering numbers
* You don't care too much about details
* xref:role_playing_system:a_introduction.adoc[Take me there NOW!, window=_blank]
