= Anthros
		
[quote]
____
*Anthros are humanoid life forms with animal appearances.*
____

All anthros are upright and bipedal.
They have a face, a head, and two functional hands.
Anthros function like us mundane humans, and are the most familiar shape available to the player.
EXP's fake taxonomy of life describes anthros as the family Hominidae and the genus homo.
Each anthro type is considered a species with names like homo avis or homo felis.
Anthros differentiate further with purely cosmetic types. 
A homo felis (feline) would be of the type Manx, lion or cougar.
The player chooses the final appearance of her anthro type.

:art: claw_pistol_grip_underhand.png
:width: 250px
:snark: Awkward looking, but deadly
:artist: Elliot Cues, Hugh
:date: 1890, 2018
:license: CC BY-SA 4.0
:description: Drawing of a bird claw holding a revolver.

include::ROOT:partial$articulate.adoc[]

Anthros are the core family for all rules and technology.
Using a humanoid form as the standard makes for the most relatable ruleset possible.
Technology, mutations, vocations are all written from an anthro frame of reference.
Robots and aliens are the exceptions in regards to EXP.

== Anthro Delivery Checklist

. xref:ROOT:attachment$anthro_record_v7.pdf[Download Anthro Record Sheet]
.. Save a tree and use https://xournalpp.github.io/[Xournal]
. xref:anthros:generate_attributes.adoc[Attributes,window=_blank]
. xref:anthros:generate_hit_points.adoc[Hit Points,window=_blank]
. xref:anthros:genus__selection.adoc[Select Genus,window=_blank]
. xref:anthros:movement_rate.adoc[Movement Rate,window=_blank]
. xref:anthros:defence_rating[Defence Rating,window=_blank]
. xref:anthros:age.adoc[Age,window=_blank]
. xref:anthros:anthro_size.adoc[Size,window=_blank]
. xref:anthros:mutation_check.adoc[Mutation Check,window=_blank]
. xref:vocations:a_introduction.adoc[Vocation,window=_blank]
. xref:roll_playing_system:incidentals.adoc[Incidentals,window=_blank]
. xref:hardware:a_introduction.adoc[TOY Check,window=_blank]
. xref:anthros:attack_table[Attack Table,window=_blank]
. xref:anthros:moniker.adoc[Name,window=_blank]
. *Have fun!*

Creating personas in EXP is entirely random.
The player gets to make choices about her persona, but the dice determine which choices she gets to make.
As of version 6.0, there is no point system for creating personas.
EXP is the game of technological chaos, and the dice deliver the chaos.

EXP is exceptionally open to creative interpretation. 
However, there are limitations to what an anthro persona can be.
Let's consider a player who has a canine (dog) anthro persona.
The player can choose a dog type that suits her fancy.
She can choose a husky, a poodle, a golden or a mutt.
The dog type is cosmetic.
A chihuahua need *NOT* be tiny, anxious, and yappy. 
The player chooses the disposition of her persona.

Let's consider a player who chooses bulldog as her persona's canine type.
The persona's head will have the gnarled features and folded jowls characteristic of a bulldog.
The skin would consist of a coat of short hair, typically found on bulldogs.
She would also have stocky upper shoulders and powerful looking arms (which end in stubby paw-like hands).
Her persona would stand upright on two fur-covered legs, which meet at a stubby tail.

Such descriptions would be analogous for other families, like florians – bark for skin, fungus for hair; or insectoids – a buggy-eyed fly's head atop a bipedal exoskeleton.

The anthro families have no special abilities other than those described for their genus.
Canines can sniff out radiation, and felines can see in the dark. 
The descriptions are as far as the similarities go.
Insectoid personas cannot lift 1000 times their own wate.
Reptiles do not automatically get poisonous bites.
Avarians aren't all gifted with flight.