= Calculate Anthro Hite

The player is welcome to use whatever hite she chooses as long as it does not negatively influence the story or the fun.
It is presumed the reader is having trouble calculating the persona's hite if they are reading this. 

== Hite
The player calculates her persona's hite by referencing her anthro type's hite data.
Each anthro type has an average hite and a hite variation.

The player rolls the hite variation described for her chosen anthro size.
Next, the player adds the hite variation to her anthro type's base hite.
The hite variation can be positive or negative, generating a hite above or below the average.
The following example shows how to generate an ursidae anthro's hite.

.*Find the anthro's average hite*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|Average hite is #highlighted#: 176 cm

s|Size
s|Hite (cm)
s|Wate (kg)

|Big
|#176#+(2d20)-20
|78

|===

.*Determine the anthro's hite variation*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|Hite variation is #highlighted# : (2d20)-20 cm

s|Size
s|Hite (cm)
s|Wate (kg)

|Big
|176+#(2d20)-20#
|78

|===

=== Calculate Anthro Hite
.anthro hite = average hite + hite variation
****
The average hite is 176 cm. If hite variation is +10 cm she is 186 cm tall. 
If the hite variation is -15 cm, she is 161 cm tall.
****