= Anthro Size

Anthros are human-sized.
In the vernacular of EXP, anthros are medium sized. 
The occasional ursidae may sneak onto the bottom of the large scale.
Only alien and robot personas can be tiny or gigantic.
Size has two components, hite and wate. 
Hite, aka height, is the persona's length in centimetres (cms).
Wate, aka weight, is the persona's volume/mass in kilograms (kgs).

A combined table of all genera hite and base wate is included for convenience.
The base wate on this table is *NOT* the persona's wate in kg. 
This is the base wate from which the persona's wate is calculated.

Hite and wate are genderless in EXP.
The player can choose a descriptor to influence their hite and wate.
The player is also welcome to choose a hite and wate that suits their persona.
Don't let rules get in the way of the story or fun.

include::anthros:partial$anthro_hite_and_wate.adoc[]

.*Calculate Hite and Wate*
* xref:anthros:anthro_hite_calc.adoc[Calculate Hite, window=_blank]
* xref:anthros:anthro_wate_calc.adoc[Calculate Wate, window=_blank]


