= Calculate Anthro Wate

The player is welcome to use whatever wate she chooses as long as it does not negatively influence the story or the fun.
It is presumed the reader is having trouble calculating the persona's wate if they are reading this. 

== Wate 
The persona's wate is proportional to her hite.
The taller she is, the greater her wate.
The wate of the persona is a pure calculation based on the hite of the persona.
The greater the hite of the persona, the greater her wate. 

There are no rolls made when generating a persona wate.
The player finds her persona's average wate.
The player calculates her persona's wate variation.
The player calculates her wate variation by dividing her hite by her average hite. 
The player multiplies her average wate by wate variation.
The following example shows how to calculate an ursidae's wate.

.*Find the Average Wate*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<| Average wate is #highlighted#: 78 kg

s|Size
s|Hite (cm)
s|Wate (kg)

|Big
|176+(2d20)-20
|#78#

|===

=== Calculate Wate Variation
.wate variation  = persona hite / average hite
****
The persona's average hite is 176 cm. If her hite is 186 cm, she has a wate variation of 1.05. If her hite is 161 cm, she has a hite variation of 0.91.
****

=== Calculate Anthro Wate
.anthro wate = average wate * wate variation
****
The base wate is 78 kg.  A 1.05 wate variation yields an 82 kg anthro. A 0.91 wate variation yields a 71 kg anthro.
****

====
The player records the final hite and final wate on her persona record. 
She also wonders if it was worth all the maths.
Smiling, she remembers that numeracy is an excellent skill.
====