= Anthro Genera 

The anthro family has several genera to choose from. 
These used to be called anthro types.
As with all of the families the genera are largely phenotypical, meaning they reflect form more than function.


.List of Genera
* xref:anthros:genus_aquarian.adoc[Aquarian, window=_blank]
* xref:anthros:genus_avarian.adoc[Avarian, window=_blank]
* xref:anthros:genus_canine.adoc[Canine, window=_blank]
* xref:anthros:genus_equine.adoc[Equine, window=_blank]
* xref:anthros:genus_feline.adoc[Feline, window=_blank]
* xref:anthros:genus_florian.adoc[Florian, window=_blank]
* xref:anthros:genus_humanoid.adoc[Humanoid, window=_blank]
* xref:anthros:genus_insectoid.adoc[Insectoid, window=_blank]
* xref:anthros:genus_purestrain.adoc[Pure Strain, window=_blank]
* xref:anthros:genus_reptilian.adoc[Reptilian, window=_blank]
* xref:anthros:genus_rodentia.adoc[Rodentia, window=_blank]
* xref:anthros:genus_ursidae.adoc[Ursidae, window=_blank]

== Explaining Anthro Delivery Data
Once the player has chosen her persona's anthro type, she records it on her persona record sheet.
Each anthro type has a Delivery Data Table.
Each table is unique to the anthro type and contains essential information about the type.
Below we use the  Ursidae Delivery Data table to explain the info.

// todo add the different types 


.*Ursidae Delivery Data*
[width="75%",cols="<,<,<",frame="all"]
|===
3+<|The bare facts to bear an ursidae player persona.

s|Attribute Minimums
2+<|DEX 4; INT 4; STR 12

s|Attribute Adjustments
2+<|CON +1; INT -2; STR +2

s|Age
2+<|9-12 (1d4+8) years
s|Abilities
2+<|Hibernation, Frenzy

s|Size
s|Hite (cm)
s|Wate (kg)

|Big
|176+(2d20)-20
|78

|Bigger
|208+(2d20)-20
|139

3+<| xref:anthros:anthro_size.adoc[Calculate Hite and Wate]

|===

=== Attribute Minimums
The required attributes for an ursidae are DEX 4, INT 4, and STR 12.  
See above for details ad nauseam.

=== Attribute Adjustments
These are the adjustments made to the persona's attributes.
Strong personas get even stronger, and weak personas may get even weaker.
The ursidae persona would take an Intelligence penalty of -2.
She would also enjoy a Constitution bonus of +1 and a Strength bonus of +2.
These attribute adjustments make the ursidae strong, hardy, but not too smart
An anthro type attribute penalty cannot drop an attribute below the type attribute minimum.
These attribute adjustments are important because attributes influence a persona's choice of vocation.
The player records the adjusted attributes on the persona record sheet. 

=== Age
The starting age range of the persona in years.
Ages vary wildly from anthro type to anthro type. 
Most of the anthro ages fall into the young adult category.
In the case of an ursidae, the player would roll 1d4 and add 8.
The die roll generates an age between 9 and 12 in years.
The player records her persona's age on the persona record sheet. 

=== Abilities
Abilities are cool things that the anthro type can do. 
Abilities are part of the anthro type, and they are not mutations.
All ursidae have frenzy and hibernation
The player can read the details of frenzy and hibernation in the 
 
=== Hite and Wate
Hite is in centimetres (cm), and wate is in kilograms (kg).
A centimetre is shy of half an inch.
A kilogram is slightly more than 2 pounds. 
The delivery data lists two different sets of hite and wate.
The player chooses between the sizes big and bigger.
Their titles are self-explanatory for the ursidae.
In general, ursidae are big.

Not all anthro types have a choice between larger and smaller sizes. 
These are the "one size fits all" anthro size.
Gender does not determine the anthro size in EXP.
Anthro size a player's choice.

The hite and wate listed here are average hite and wate.
To calculate the persona's exact hite and wate, jump to xref:anthros:anthro_size.adoc[Calculate Hite and Wate].

