= Anthro Defence Rating

Defence Rating (DEF) is a number that indicates the persona's natural ability to avoid being harmed in combat.
The higher the persona's Defence Rating, the more difficult it is for an attacker to score a successful attack roll.
Defence Rating attempts to create a universal number that indicates how difficult a persona is to damage. 
There is a more detailed discussion found under xref:roll_playing_system:CH29_Armour_Rating.adoc[Defence Rating,window=_blank] in the tactical combat rules. 

The persona's Defence Rating is dependent on her Dexterity. 
The faster, more agile, and more wiggly the anthro, the more difficult it is to land a combat punch.
The Defence Rating determined here is her naked Defence Rating. 

== Calculate Anthro Defence Rating
// tag::Anthro_AR[]
.DEF = 500 + 6 * DEX
****
A persona with a 12 DEX would have an DEF of 572.
****
// end::Anthro_AR[]

Anthro personas are unique because they can wear armour to protect themselves in combat.
Mundane armour is not as exciting as artifact armour, and it is usually cumbersome, uncomfortable and challenging to wear.
Jump to xref:hardware:mundane_equipment.adoc#_armour[Mundane Armour,window=_blank] to learn about norm tech armour types
Jump to xref:hardware:CH42_Armour.adoc[Armour,window=_blank] for artifact armour. 