= Florian

:art: florian.png
:width: 250px
:snark: A pine fellow indeed.
:artist: Peggy Lynn McIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of space suit wearing plant in locker room.

include::ROOT:partial$articulate.adoc[]

// Table 4.10 Florian Data
.*Florian Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|Here are the seeds for creating a florian player persona.

s|Attribute Minimums
2+<|CON 12; INT 12

s|Attribute Adjustments
2+<|INT +1
 
s|Age
2+<|21-40  (1d20+20) years

s|Abilities
2+<|<<_photosynthesis,Photosynthesis>>

s|Size
s|Hite (cm)
s|Wate (kg)

|One size fits all.
|165+(3d20)-30
|50

3+<|xref:anthros:anthro_size.adoc[Calculate Hite and Wate]

3+<|Example species: Apple, Coconut, Daisy, Fern, Pine, Rose, Shroom, Turnip.
|===

Florian is short for Hominidae Homo Planta.
Florians are humanoid walking plant people.
Florians can take the appearance of any plant type: venus flytrap, rose, seaweed, pine tree, mushroom, etc.
Remember that these various florian types are only decorations. 
Every florian has two arms, two legs, a torso and a face.
Their skin may be bark, and their hair leaves.
Florians have no abilities other than those listed below.
For example, a poison ivy florian would not be poisonous.



== Photosynthesis
Florians are photosynthetic.  
Even florians modelled after fungi are photosynthetic.  
Florians need sunlight and water to keep from starving.  
Florians do not have blood but life-giving sap.
A wounded florian will still bleed to death.

The photosynthetic skin of the florian is a doubly important organ.
Fire, heat, cold and corrosive attacks do double damage.

Florians do have lungs.
The florian lung draws carbon dioxide from the air and exhales waste oxygen. 
The lungs are redundant and only assist photosynthesis.
Florians can hold their breath indefinitely and can avoid the effects of inhaled gases. 

== Healing
When resting in sunlight and drinking plenty of water, a florian can rapidly heal.
A florian heals twice as fast as other anthro types.
A Sunbathing florian will heal at two hit points per day for the first seven days, and then four hit points per day. 

