= Anthro Genus Selection

At this point, the player's anthro is merely a list of numbers.
Her persona may be strong or smart but has no form.
Choosing the anthro's genus is the first step in giving the persona a literal shape.

The player gets to make choices, but as usual, the dice guide her options.
The persona's attributes determine which of the anthro genera the player may choose from.
Some anthro types are less common due to their unique abilities and attribute adjustments.
A player whose persona has a Strength less than ten cannot have an equine anthro. 
A persona with a Dexterity of twelve or less cannot be a feline.

Using the Anthro Genus Selection Table reflects some legacy in the ruleset.
In the past, these kinds of creative limitations were commonplace. 
Role-playing games have matured over the last 40 years.
Today limiting the player choice of anthro genus seems miserly.
However, balance in the roll playing system is based on these kinds of limitations.
One can find a <<_alternate_anthro_genus_selection,compromise>> below. 
Don't let rules get in the way of the story or fun.

The player and referee compare the persona's list of attributes to the attribute minimums one the Anthro Type Table. 
This comparison results in a list of anthro types from which the player can choose.

include::ROOT:partial$table/anthro_genus_selection.adoc[]

== Attribute Minimums
Anthro attribute minimums serve two purposes. 
1) organize anthro types based on physical abilities.
2) ensure a minimum attribute score for the anthro type.

The restrictions ensure that hardy anthro types have a high Constitution, that smart anthro types have high Intelligence, and that strong anthro types have high Strength.

Persona attribute minimums are part of a selection process and do represent a protected attribute score.
In gameplay, ageing, mutation or injury can drop an attribute score below the anthro type's minimum.
A persona's Charisma score can drop below her anthro type minimum due to burns.
A persona's Strength can drop below her anthro type minimum due to ageing or injury.

== Example Anthro Genus Selection
A player has generated a persona with the following attributes:  AWE 6, CHA 15, CON 17, DEX 9, INT 14, MND 12, STR 6 AND HPS 42.
The player can choose from the following anthro types avarian, florian, humanoid, insectoid, purestrain and rodentia.

include::ROOT:partial$table/anthro_genus_selection_example.adoc[]

.The player may choose from the following genera:
* Aquarian
* Canine
* Florian
* Humanoid
* Insectoid
* Purestrain 
* Rodentia

== Alternate Anthro Genus Selection
Players can skip the arduous procedure of comparing attribute types and choose their anthro type directly.
The referee and players must give care to game balance if the straight selection model. 
Expeditions will quickly become overpowered and full of ursidae spies and reptilian knites without some balance.
If the player chooses an anthro type purely for cosmetic and story reasons, they should forfeit the abilities and attribute adjustments of the anthro type.
So if a player always wanted to look like a panda bear but lacks the attributes, she can look like a panda bear but does not get hibernation, frenzy or plus two on her Strength. 
Choosing appearance over abilities and attributes is called the "I wanna look like" loophole. 
