= Canine

:art: canine.png
:width: 250px
:snark: Dog daze in the club.
:artist: Peggy Lynn McIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Dog headed bartender washing a glass.

include::ROOT:partial$articulate.adoc[]

// Table 4.7 Canine Data
.*Canine Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|What one needs to whelp up a canine player persona.

s|Attribute Minimums
2+<|AWE 4; CHA 3

s|Attribute Adjustments
2+<|AWE +1; CHA -2; CON +1

s|Age
2+<|5-10 (1d6+4) years

s|Abilities
2+<|<<_radiation_sense,Radiation Sense>>

s|Size
s|Hite (cm)
s|Wate (kg)
// One size fits all not present

|One size fits all
|150+(1d12)-8
|48
// Large not present

3+<|xref:anthros:anthro_size.adoc[Calculate Hite and Wate]

3+<|Example species: Chihuahua, Dane, Dingo, Labrador, Poodle, Terrier, Weiner, Wolf.

|===

Canine is the short name for Hominidae Homo Canis.
Canines are humanoid dog people.
A canine persona can select the looks of one of many dog types: poodle, terrier, wolf, jackal, dingo, fox, etc.
The persona remains a bipedal humanoid.
A canine would always have two arms, two legs, a torso and a face.
The canines are humanoid dogs sporting fur and doggy tails.

Some examples from popular culture are https://en.wikipedia.org/wiki/Anubis[Anubis,window=_blank], and https://en.wikipedia.org/wiki/Cynocephaly[Dog heads,window=_blank].

== Radiation Sense
Radiation sense allows a canine to detect and identify radioactive nastiness.
Radiation sense's effectiveness depends on the persona's AWE and not the type of canine.
For example, a poodle would sniff out radiation as well as a bloodhound.
Radiation sense does not convey any immunity to radiation.
Radiation poisoning is just as deadly to canines as other personas.

=== Detect Radiation
This canine ability allows the persona to notice radiation.
The ability yields a binary result.
Either, yes radiation or no radiation.
The persona can immediately tell whether the radiation is a point source or general radiation.
If there is a point source of radiation, the canine can move towards the epicentre. 
The canine could also track a mobile source of radiation.
If there is a generalized background radiation level, the persona can determine this as well.
The range of radiation detection is five hexes per point of AWE and radiation intensity.
The range is very far. 
Canines can use this ability to avoid poisoned wastelands or track down a leaking fusion pistol.

=== Identify Radiation
Identifying the radiation type is more complicated than detecting radiation. 
The referee decides whether or not there is a distinctive radiation type. 
EXP does not differentiate between radiation types. 
If the radiation type matters to the story, the referee can differentiate it by source rather than radiation type. 
For example, there could be natural radiation, post bomb radiation, leaking reactor radiation, etc.




