= Aquarian

:art: aquarian.png
:width: 250px
:snark: Aquarian protesting hooking.
:artist: Kate Cunningham
:date: 2017
:license: Copyright Artist 2017
:description: Fish with legs in wet suit protesting.

include::ROOT:partial$articulate.adoc[]

// Table 4.5 Aquarian Data
.*Aquarian Data*
[width="75%",cols="<,<,<",frame="all"]

|===
3+<|Data for spawning a brand new aquarian persona.

s|Attribute Minimums
2+<|Nil

s|Attribute Adjustments
2+<|AWE +2; DEX +2

s|Age
2+<|5-10 (1d6+4) years

s|Abilities
2+<|<<_swimming,Swimming>>

s|Size
s|Hite (cm)
s|Wate (kg)

|One size fits all
|150+(6d20)-50
|60

3+<|xref:anthros:anthro_size.adoc[Calculate Hite and Wate,window=_blank]

|===

Aquarian is the short name for Hominidae Homo Pisces.
Aquarians are humanoid fish people.
The player can choose from many aquatic life forms: shark, goldfish, octopus, salmon, viper, sea cucumber, anemone, sea star, etc.
The persona remains a bipedal humanoid. 
An aquarian would always have two arms, two legs, a torso and a face.
The hands may have webbing between the fingers, or the legs may have suction cups.
Regardless of the appearance, an aquarian can do anything any other anthro can do.
An aquarian would not take on any special abilities of their chosen fish shape.
An aquarian electric eel would not have an electric shock.

Some aquarians from popular culture are https://en.wikipedia.org/wiki/Merman[mermaids,window=_blank], https://en.wikipedia.org/wiki/Yacuruna[yakaruna, window=_blank], https://en.wikipedia.org/wiki/Abe_Sapien[Abe Sapien,window=_blank], https://en.wikipedia.org/wiki/Creature_from_the_Black_Lagoon[Gill Man,window=_blank], and https://youtu.be/xEIpzBPUjEo[Adam, window=_blank].

== Swimming
Aquarians are adept swimmers and can move in liquid with ease.
They are equally adept in low gravity and gain all liquid bonuses in half gravity or less.
When the aquarian is in liquid or zero gravity (ZOG), she is swimming.

A swimming aquarian enjoy attribute and movement bonuses.
The persona gets  +2 on her AWE, CHA, DEX, INT, and STR attributes.
She also gets a movement rate bonus of 50% when swimming.
For personas that frequently swim, keeping two sets of attributes is advised.

Aquarians are aquatic life forms and must regularly return to their liquid environment.
By super soaking their gills, aquarians can venture into full gravity and air. 
An aquarian can survive in a gaseous atmosphere for one hour per point of CON.
For example, an aquarian with CON 11 could wander the mall for 11 hours.
After 11 hours, she would start to suffocate.
