= Moniker
The player must name her persona.
Every persona must have a moniker, call sign, label, title, handle or cognomen.
A player should avoid naming her persona with her mundane world real name.
Creating a persona name makes role-playing more fun.

NOTE: https://en.wiktionary.org/wiki/moniker[Moniker] is another word for "name". 
// todo moniker may need to change back if there is push back

Anthro names follow standard role-playing game nomenclature. 
Each anthro will usually have a given name and a surname.
The player creates both the given name and surname.
The anthro naming structure is the most familiar naming structure from the three families.

.*Example persona names*
* A mechanic - Hans Tinker
* A mercenary - Hans Grenade
* A spie - Hans Ophmistuph
* A reptilian boa - Hugs McCuddler

The persona's vocation, anthro type, and anthro subtype are the most potent name determiners.
Anthro names need not be silly.

== History
Players should create a pre-campaign history for their persona.
A persona's initial history should not be one of great fame or import.
Role-playing in the campaign world is what should build a persona's fame and reputation.
The persona's history should fit in with the referee's milieu and campaign. 

Persona backstories should be short.
If a player wants to make an essay of her persona's background, she should not expect other players to care.

== Description
Anthro players pick an anthro type and sub-type when being delivered.
The persona description would allow the reptilian snapping turtle to stand out from other reptilian snapping turtles.

The player can embellish her persona with further details: adornments, smells, colours, coverings, coats and coatings.
The player creates the persona's clothing, jewelry, fur texture, paint colour, and eye(s) shape.
Overly detailed persona descriptions are fun for players to make.
Overly detailed persona descriptions are less fun for other players.
Concise descriptions make for compelling personas.

The persona's description is up to the player. 
However, the persona's description must fit in with the milieu of the campaign.

== Personality
A persona should have a personality of some sort.
Most often, the persona will be a reflection of the player's mundane terra persona.
Experienced players will create a personality for their persona.
The personality could be emotionally based, belief-based, or vocation-based.

NOTE: *The goal of persona personality is to have a perspective and have fun expressing it.*

The persona may exude extroverted traits like distrust of veterinarians, abject fear of reptilians, compulsive desire for battle, or an overwhelming worry about the present predicament.
The main challenge of persona personality is remaining consistent.
Staying alive will require a persona to switch from trusting to paranoid in an instant.

// todo add RP personality stuff here to help inform persona

== Examples

Hans Tinker:: 
Hans is a reptilian snapping turtle sporting a blue shell. 
She works to repair the local sand sleds and does not like to destroy equipment. 

Hans Ophmistuph::
Hans is a sad-looking hound dog. 
His coat is dark grey, and his clothes are unkempt.
He grew up without much, and he gets angry if people touch his stuff.

Clara Voyant::
Clara is a humanoid that has elven features.
Her hair is bright pink, and she has more bangles than she needs.
She is excellent at selling used sand sled parts because she seems to know what customers want.
