= Anthro Mutations

:art: mutation_inducing.png
:width: 250px
:snark: Let's mutate now!
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of tank top wearing woman and humanoid frog in radiation zone.

include::ROOT:partial$articulate.adoc[]

// need explanation of defects

Mutations in EXP are sciency fiction DNA changes that create special abilities.
Mutations are randomly acquired unique changes to the anthro's DNA.
The anthro mutation storey is deeply rooted in sciency fiction.
In reality, extreme biological mutations are universally fatal.
Explaining how these sciency fiction mutations can exist is left the "black box" of creative pseudo-science.
However, fun pseudo-scientific explanations add to the story of the campaign.

.*More detailed mutation information*
* xref:wetware:CH57ish_Mutations.adoc[Mutations in General,window=_blank]
* xref:wetware:CH58_Mental.adoc[Psionic Mutations,window=_blank]
* xref:wetware:CH59_Physical.adoc[Phenomic Mutations,window=_blank]

== Mutation Chance
Every player must check to see if their persona mutates.
Anthro type determines anthro mutation frequencies.
Humanoids are much more likely to mutate than insectoids.
The player rolls against the table and records the number of each mutation type.

.Mutation Chance Variations
* a player that wants her persona to mutate *doubles her chance*
* a player that does *not* want her persona to mutate *zeroes her chance*
* a player should not be emotionally burdened by her persona having a mutation defect
* a player with a humanoid anthro can choose a 100% mutation chance
* a Purestrain cannot start with any identifiable phenomic mutations

include::ROOT:partial$anthros/anthro_mutation_chance.adoc[]