= Chapter 40: Technology Basics
:author: expgame
:date: 2010-08-08 03:48:55 -0400
:guid: http://expgame.com/?page_id=324
:id: 324
:page-layout: page

[.s3]#A very large portion of this game is devoted to the workings of technological devices.
This is not surprising since the headline is &#8220;The Game of Technological Chaos.&#8221;
While the referee may create any campaign milieu that they wish EXP is ready for a world of mixed technologies, and mixed up tech levels.
EXP is not hard science fiction.
EXP The game of technologic chaos is a science fantasy role playing game.
If the referee happens#[.s5]# to have an interdisciplinary #[.s6]#PhD in physics, biology and engineering go ahead explain it all.
For the rest of us mortals the science fantasy moniker will allow us to defer to the potent power of the magical black box of unknown technological process, and a good aptitude for &#8216;rational fabrication&#8217;
should #suffice.

The technology in this section of the game is[.s7]# magical in nature, and it is the root of the science fantasy milieu of EXP.
#[.s5]#The referee will find that technology can #drastically alter the course of a campaign, and this does not always have to be an obviously powerful [.s4]#item.
For instance a life ray could change the way #[.s7]#that the personas behave in their world, and change the entire effect of the combat#[.s3]#.
An ancient control baton (a #device that manipulates powered armour) may seem useless until the expedition encounters the powered armour wearing overseers of their tiny village[.s4]#.#

== [.s3]#How To Use This Section# {.p5}

[.s8]#The technology tables, whether they be for #[.s9]#mutations, guns, or medical equipment are #[.s4]#designed to be used by referees and players.
The initial rolling can eventually result in literally any artifact.#[.s6]# While most personas and referees will be rolling random artifacts in this section&#8217;s chapter, the lists can also be used as a catalogue of ridiculous toys.
Whether or not the equipment here #[.s7]# can be purchased by the personas is entirely up the referee.
Story always takes precedence over the random artifact generation.
#[.s4]#The equipment lists are dual purpose #tables.
The referee and players can use the lists to [.s3]#generate random artifacts, or they can use them as #[.s4]#catalogues to choose how to outfit their personas.
The referee #[.s6]#always has complete control over the equipment #[.s4]#lists, restricting items that do not suit her milieu, #[.s10]#altering items so that they suit her campaign #[.s4]#better, or adding items that she thinks are essential.#

== [.s12]#Nature of The Equipment# {.p5}

[.s6]#Section iii: Hardware covers a wide #[.s4]#range of items.
#[.s6]#There is deadly stuff;
useless #[.s3]#stuff, and silly stuff.
The hardware section is #[.s10]#intended to be used by many different styles of #[.s6]#refereeing and game playing.
Expect things to vary with different referees #[.s4]#and sometimes with the same referee in different #moods.
[.s12]#The main goal of technology in EXP is t#[.s4]#o accommodate as many role-#[.s3]#playing situations as possible#[.s8]#.
The creation of the toys was quite #[.s4]#systematic.#

This is not to say that all the equipment is [.s6]#predictable, since each device has its quirk.
For #[.s4]#every powerful device there is another device that #can overcome it.
For every weak device there is a [.s3]#situation in which it is extremely important.
Every #[.s14]#device has its own inherent strengths and #weaknesses, and through this series of checks and [.s7]#balances artifacts should remain unpredictable.
#[.s5]#There is also some equipment that has no #[.s4]#place in the scheme of things and may be simply #[.s7]#weird.
These items are often there for fun.
For #instance rocket assisted roller skates, or an antigrav [.s7]#belt are somewhat anomalous devices, but they #[.s5]#add fun to the campaign.
Other equipment has #[.s3]#found its way into the technology catalogue from a historical perspective.
These are devices like Little Golden Books, slug throwers, and the arm of ephro.
Such items are meaningful to those of us who wrote #[.s4]#the game, and it simply wouldn&#8217;t be EXP without #[.s6]#them.
You will quickly find that your campaigns are littered with campy little devices that no one #[.s4]#else knows anything about.
This is what makes a #[.s7]#game personal and attractive to the people that #play it.

== [.s3]#When To Use It# {.p5}

[.s14]#The referee can add equipment to the #[.s6]#campaign in any fashion that she sees fit.
There #[.s4]#may be bits of stuff hidden around in an ancient ruin, #[.s10]#there may be the infrequent space travelling #[.s6]#salesperson that arrives on their planet, they may #rent their equipment from a corporation, they may [.s4]#have their equipment assigned by the government, #[.s8]#or they may steal it from their captors.
The #[.s9]#possibilities are endless, and the referee is #[.s6]#responsible for creative introduction of new toys.
[.s12]#This is a technology game, and players will come to #[.s13]#expect their campaigns to revolve around the #[.s7]#mysteries of varying technological levels.
The #[.s10]#degree of technological involvement will be #[.s13]#determined by the referee.
The personas start #[.s7]#with a certain allotment of equipment.##

[.s8]#Toys should be included in a campaign #[.s4]#whenever it would be fun.
The ref must remember at all times that the game should be fun, and that #[.s6]#should be the determinant of what she does.
The #[.s3]#referee must also consider balance in her campaign.
#[.s4]#Not allowing personas to become too powerful is #[.s8]#important, and she must consider that com#[.s3]#binations of equipment can quickly produce an very #[.s6]#powerful persona.
Again the employment of this #[.s3]#should be moderated by what is fun for the players #[.s4]#(the referee is included as a player).
Being all powerful becomes quickly boring, and being all wimpy is quickly #[.s6]#boring, and fatal.
#[.s13]#The referee must find that entertaining #[.s12]#balance where the persona&#8217;s know their place in the #[.s6]#food chain.
Something tougher than them should #[.s4]#be beatable if they use their smarts, and something #[.s5]#weaker than them should be dangerous if they #[.s7]#make a mistake.#

== [.s1]#Keep Track of Toys# {.p5}

[.s12]#The referee should keep track of the toys that the personas #[.s7]#have.
She must have some sort of a permanent #[.s3]#book (ed.
note this portion was written in 1990) in which she records the essential information #[.s6]#about each toy that is generated in her campaign.
The reason that this is the referee&#8217;s responsibility #[.s13]#is because the referee is the constant in her campaign.
#[.s6]#Personas will come and go, but their equipment #[.s4]#will remain long after them.
Cryptically recorded #[.s6]#persona record sheets will not relinquish useful #[.s5]#information about artifacts all that often.
It is #[.s10]#important that the referee record, in her own #[.s6]#cryptic records, at least the essential information about each persona&#8217;s toys.
Without book keeping#[.s12]#, fission rifles turn into fusion rifles, #[.s6]#grenades have variable area of effects, vehicles change accelerations, etc., etc.
In no way is this #[.s4]#malicious on the part of anyone involved.
#[.s5]#It is just simple fact that as data is transcribed #[.s6]#from one page to another it always suffers a little bit of accidental alteration (http://tinyw.in/bwL5[bible]).#

*Book Keeping and Game Play*: If keeping track of mutations, weapons, computers, [.s4]#robots, and other stuff is starting to bog down the #[.s6]#game simply decrease the amount of information that is important in the game.
Do you really need #[.s4]#to know the battery type of a particular device?
Is #[.s6]#the range of a detector so important that it should #[.s4]#be included for every detector?
You will find that #[.s3]#the amount of information kept track of will be the #[.s6]#amount of information that is needed in the game.
#[.s14]#Some players will be able to handle more #[.s6]#information than others, and they will gravitate towards highly equipped personas.
Other players #[.s14]#will keep their #[.s14]#personas as simple and as #[.s6]#uncluttered as possible.
Each player will rise to #[.s4]#their level of http://tinyw.in/0Se8[complexity].#

&nbsp;
