= Chapter 42: Armour
:author: expgame
:date: 2010-08-08 03:55:20 -0400
:guid: http://expgame.com/?page_id=331
:id: 331
:page-layout: page

[.s1]#This is the artifact armour section.
These armour #[.s2]#types not only protect the wearer against general #[.s1]#damage, but also have special qualities that vary from thermal protection to computerized, servo-aided joints.
#[.s3]#All armour is worn on the body.
Unless #[.s1]#otherwise stated, the armour will include torso, #[.s2]#limb, hand, foot, and head protection.
Shields are #[.s1]#not included in armour protection.
#[.s4]#Each separate armour type has several #[.s5]#statistics listed.
These are explained in the following #[.s2]#paragraphs.
For more information about the nature of armour refer to [.s1]#http://expgame.com/?page_id=302[Chapter 29: Armour]#http://expgame.com/?page_id=302[Rating].
#[.s5]#All the artifact armour parameters listed are based on the tactical combat #[.s1]#system, and a tech level 10.#

== Armour Rating {.p1}

[.s3]#The higher the armour rating, the better the #[.s2]#protection offered to the wearer.
Not all the armour in this chapter has a high armour rating, but each #[.s5]#offers some unique form of special protection.
Those #armour types without a listed armour rating have a value [.s1]#listed that is added to the armour rating (AR) of regular armour #[.s6]#types.
These armour types are meant to be worn in #[.s1]#conjunction with other armour types.#

[.s7]#The base armour rating of an unarmoured target is 500.
The armour ratings are related to #[.s2]#this base value.
For instance a suit of armour that has an armour rating of 725 would give the wearer #[.s1]#a base armour rating of 725 instead of 500.
This #[.s5]#could also be considered an armour rating (AR) bonus of +225.
The #[.s2]#complexities and confusions of armour rating are #[.s1]#discussed-in more detail in http://expgame.com/?page_id=302[Chapter 29: Armour]#http://expgame.com/?page_id=302[Rating].

== Restrictiveness {.p5}

[.s2]#The more restrictive a suit of armour is, the more cumbersome, and unyielding it is to normal body #[.s4]#movement.
This is represented by a higher #[.s1]#restrictiveness value.
The less restrictive armour #[.s7]#is the more that the persona can use her natural dexterity#[.s8]#* *#[.s7]#to avoid taking damage.
This operates the #[.s1]#same for artifact armour as it does for mundane #[.s2]#armour.
#

== [.s9]#Wate# {.p6}

[.s2]#The wate of  armour is listed as  percent of body wate.
% Body WATE is used to determine the wate of the suit of #[.s1]#armour.
Armour is a form of clothing, and it is usually tailored to a particular wearer.
Thus the #[.s2]#wate of armour is related to the wate of the wearer.
Previously #[.s6]#there were no set WATEs for armour for the reason that different amounts of material are required for #[.s2]#different body sizes.
Therefore armour WATE is #[.s10]#listed as a percentaggla the body wate of the #[.s1]#persona that the armour was designed for.
A flat #[.s2]#wate in kgs is included in brackets based on the % wate.
The flat wate is based on that of a #[.s1]#70 kilogram anthro.
#[.s1]#The armour&#8217;s WATE must be recorded and #[.s7]#considered part of the persona&#8217;s encumbrance.
#Nice referees will conveniently fit found armour to [.s3]#the wate of the persona who found it.
If the #[.s7]#scenario indicates that found armour has been #[.s6]#tailored for a specific race, then such a convention #[.s2]#cannot apply.#

== EXPS {.p3}

[.s6]#Experience points for armour are earned when the #[.s1]#player identifies the armour&#8217;s special function.#

== Value {.p3}

[.s2]#Value of armour will be listed in one of two #[.s7]#ways: a single value, or a cost per kilogram.
A #single value represents the flat cost of the armour.
[.s2]#Some armours are composed of material which is #[.s15]#very valuable, and the amount of this material #[.s7]#reflects the value of the armour.
These armour #[.s10]#types are listed as having values like 590 per #[.s6]#kilogram or 750 per kilogram.
So the value of such #[.s2]#armour is directly related to the wate of the armour.
#[.s6]#If the armour had a wate of 2 kilograms, and it were worth 750 eps per kilogram, it would be worth 1500 #[.s1]#eps.
For convenience a value based on the wate armour required for a 70 kilogram anthro will be included in brackets.#

== Armour Types {.p8}

Use table 42.1 to determine what kind of artifact armour the persona, referee persona, or loot pile has found.

[table id=376 /]

== 1) Ablative {.p8}

[table id=377 /]

[.s6]#Ablative armour is designed to negate lazer attacks.
#[.s5]#When hit by a lazer the ablative material vaporizes, #[.s7]#producing an anti-lazer gas that dissipates the #[.s2]#lazer bolt, keeping the attack from damaging the #[.s1]#wearer.
When hit by a lazer, the wearer will take no damage because of the ablative armour.
This #[.s15]#armour only works against lazers, and cannot #[.s1]#affect energy attacks such as fission, fusion, or #[.s7]#plasma.
The armour rating represents how well the armour is at deflecting all other attacks.
#[.s1]#Since the armour vaporizes to disrupt lazers, #it has a limited life-span.
The armour will lose its [.s2]#ablative effect after disrupting 300 to 1000 (d8+2 #[.s1]#times 100) hit points of lazer damage.
If a lazer #[.s2]#attack scores a hit, damage is rolled as normal, but #the damage is subtracted from the armour, not the [.s1]#target.
Once the ablative effect is worn out the #armour retains its AR of 625, but loses all special [.s1]#defences against lazers.#

== 2) Ballistic {.p26}

[table id=378 /]

[.s1]#Ballistic armour is very similar to ablative armour #[.s6]#in its function.
A criss-crossing mat of super-dense #[.s5]#polymers is woven to absorb high velocity projectile #[.s1]#damage (bullets, fragments, etc.).
Ballistic armour #is capable of absorbing 100-600 (d6 times 100) hit [.s1]#points of high velocity (Type C attacks) damage.
Once the armour has sustained this maximum damage it will be unable to negate projectile damage, but will still act as #[.s15]#regular armour.
#[.s2]#Ballistic cloth does not absorb damage from #[.s15]#from type A attacks, such as: punches, maces, #[.s2]#pipes, flails, etc.#

== 3) Combat Armour {.p23}

[table id=379 /]

[.s7]#Combat armour is typical futuristic, militaristic #[.s2]#body protection designed for infantry dogmeat.
It #[.s7]#usually composed from such mundane materials as kevlar weaves and ceramic plates.#

== 4) Compucrafted {.p30}

[table id=380 /]

[.s2]#Compucrafted armour is computer designed versions #[.s15]#of mundane armour types.
They are designed to #[.s1]#handle stress better, deflect blows better, be less restrictive, and have less wate.
Compucrafted #[.s2]#armour uses special alloys, plastics, and ceramics #[.s7]#which are not found in regular mundane armour types.#

[table id=381 /]

[.s2]#Roll the mundane armour type on Table 42.2: Compucrafted Armour Type.
The armour rating (AR) is increased from the bas by 30 to 120 (3d4 times 10)#[.s3]#.
This improvement is from construction and stronger materials, offering #[.s17]#greater protection.
#[.s15]#Lighter and #[.s1]#less cumbersome materials allow for freer body #[.s2]#movement, giving the [.s17]#armour a new #[.s15]#restrictiveness between 0-3 (d4-1)#.
The new restrictiveness cannot exceed the previous one.
The wate of the compucrafted armour is reduced by half and it&#8217;s value is increased 4 times.
The Wate and value changes are recorded on Table 42.2 below.
EXPS value is a flat 300 points for all types of compucrafted armour.#

== 5) Concussion {.p34}

[table id=382 /]

[.s1]#Concussion armour appears as a bulky, pillowy #[.s2]#crash suit.
Each of the large fluffy lumps is full of small resilient beads that increase the surface area #[.s6]#that concussion force is absorbed over.
This design #[.s1]#reduces crushing damage from explosions, falls, #[.s7]#crashes, blunt weapons, squeezing attacks, etc.
Any of these damages types are reduced by 1/2 #[.s3]#when wearing concussion armour.
Concussion armour #[.s6]#has a base AR of 625, and all #attacks must score a hit before any damage can be [.s7]#taken.
Concussion armour is also known as a g-#suit.

== 6) Flexion {.p57}

[table id=383 /]

[.s3]#Flexion coverings are designed to increase #[.s2]#protection against specific attacks.
They offer no #protection against attacks other than the ones they [.s15]#were manufactured to thwart.
#[.s15]#The various flexion coverings appear as #[.s6]#beltless, pocketless ponchos, parkas or trenchcoats.
#[.s7]#The protection is designed to be worn over all #[.s15]#external armour and equipment.
#[.s4]#The flexion coverings can essentially #[.s1]#withstand limitless damage.
If the ref desires to #have the coverings wear out, flexion should only do [.s6]#so after the persona has sustained 500 hit points in #[.s10]#damage.
The referee can arbitrarily wear the #[.s1]#flexion suit out if it has been continually abused.
#[.s15]#Roll on Table 42.3: Flexion Covering Type to #determine the covering type, its restrictiveness, its wate, and its value.
Each covering type is explained [.s1]#in detail in the following the table.#

[table id=384 /]

[.s41]#*1) Concussion*:^.^#[.s2]#Concuflect appears as a bulky #[.s1]#down parka.
Concuflect reduces the chance to be #[.s6]#hit by all compression, non-puncture, non-energy, attacks.
When wearing concuflect a player&#8217;s armour rating (AR) is #[.s1]#improved by +150 against such attacks.#

[.s42]#*2) Electro*:#[.s15]#Electroflec coverings reduce the #[.s5]#chance of taking damage from electrical attacks by #[.s10]#grounding the deadly current.
When wearing #electroflex the persona&#8217;s armour rating (AR) is improved by +150 [.s1]#against electrical based attacks, and a bonus of 3 #[.s7]#on any electrical related saving throws.#

[.s41]#*3) Energy*:#[.s2]#Enerflec reduces the chance to be hit #by personal energy weapons (such as fusion, fission [.s6]#and plasma guns).
When wearing this shimmering #[.s7]#covering the wearer&#8217;s AR is increased by +150 against energy attacks.
Damage from energy based area of effect attacks, for example fusion attacks, #[.s2]#are reduced one half by Enerflec.#

[.s1]#*4) Inertia*: Inerflec has a slickery covering that #[.s3]#makes low velocity striking and puncturing #weapons less likely to hit.
The Inerflec is especially [.s1]#good at hampering Type A and B attacks.
There is a bonus of +150 to the wearer&#8217;s armour rating (AR) against such #attacks.

[.s5]#*5) Lazer*: Reflec is the most well known of all the #flexion coverings.
It increases the wearer&#8217;s armour [.s1]#rating by +150 against lazer attacks.
The cloak has #[.s2]#a matte colour, with a highly reflective underlay to deflect and #[.s7]# misdirect lazers.#

[.s15]#*6) Projectile*: Proflec is a hardened covering #[.s1]#composed of a thin layer of ballistic cloth.
This #[.s5]#flexion covering aids in the deflection of high velocity #[.s7]#projectile attacks (type C attacks), and increases the wearer&#8217;s AR #[.s1]#by +150 against them.#

[.s10]#*6) Vibro*: Vibroflec is an intricate weave of #[.s44]#microscopic (the modern catchphrase is &#8216;nano&#8217;), high tensile threads which are #designed to make vibro attacks more likely to &#8216;skip [.s10]#off&#8217;
their target without doing damage.
Vibro #[.s7]#attacks have -150 against Vibroflec (increase the #[.s1]#AR of the wearer by +150 vs such attacks).#

== 7) Force Field Belt {.p2}

[table id=385 /]

[.s1]#Force field belts generate an invisible defensive #[.s4]#shield contoured to the wearer&#8217;s body.
The #[.s6]#electromagically generated field will dissipate kinetic #[.s2]#energy over the entire field.
Any object approaching #[.s10]#at high speed will have all its kinetic energy #[.s1]#absorbed and dissipated before it hits the belt wearer.#

[.s2]#The belt is triggered by anything that indicates #a relatively high velocity differential between itself [.s7]#and the persona.
Thus the defensive field will #[.s1]#absorb damage from high velocity, high energy #[.s6]#attacks (lazers, falls, bullets, grenades, rocks), but #[.s10]#anything approaching the player in a passive #[.s1]#manner will not be hampered by the force field #[.s2]#(injections, gases, kisses).#

[.s1]#Any damage that would have been taken by #the wearer is absorbed by the force field belt.
The [.s1]#force field belt requires energy to dissipate the #[.s7]#force, and when it has absorbed the maximum #amount of damage its batteries are dead.
The force [.s1]#field belt cannot be used again until its batteries are replaced.
See http://expgame.com/?page_id=357[Chapter 55: Support Equipment].
#Force field belts vary in the number of hit [.s7]#points they absorb, and increase in WATE and #[.s6]#value depending on their  capacity to absorb damage.
#

[table id=386 /]

== 8) Helmet {.p78}

[table id=387 /]

[.s2]#These are specialized helmets that offer not only head protection, but built in equipment also.
The #[.s1]#helmet could have a _gun_+++<i>+++, +++</i>+++medical equipment, or scope installed.
The player rolls once on #[.s6]#Table 42.5: Helmet Accessory to determine what is #[.s2]#built into the helmet.
The persona will be able to #[.s4]#control the device in her helmet with head #[.s16]#movements, tongue connections, or facial #[.s1]#expressions.#

[.s2]#The base helmet type must be determined by #[.s6]#the referee.
The referee must choose from either a #[.s5]#combat armour helmet (armour #3), a compucrafted #[.s1]#helmet (armour #4), or a plastix helmet (armour #[.s6]##9).
There is no effective difference between the 3 #[.s7]#helmet types.#

[.s15]#Whichever helmet type is chosen the AR #[.s6]#bonus will be +40 if worn without armour, and no #[.s15]#bonus if worn with a full suit of armour.
The #[.s2]#helmet offers no increased restrictiveness, as the #[.s7]#artifacts will be ergonomically inserted in the #[.s6]#helmet.
The wate of the helmet will be equal to the #[.s2]#wate of the toy that is built into it.
These are the #[.s1]#specifications of the helmet, regardless which of the 3 helmet types is chosen.#

[.s2]#When using the Helmet Accessory table there #[.s1]#are some obvious restrictions as to what type of #[.s2]#equipment can be placed within the helmet.
Very #[.s5]#heavy items, such as cloning equipment, or artillery #[.s15]#would not only be impractical, but may cause #[.s2]#severe neck injury.
The table is an abbreviated list #[.s1]#of equipment that may be useful in a combat #[.s2]#helmet.
Each of the accessory types is discussed i#[.s1]#.
It is best to record all #[.s6]#information about the helmet now, roll its accessory, #[.s7]#and not have to refer to this chapter again.#

[table id=388 /]

[.s52]#*1) Communication*:#[.s7]# The communication device is#[.s1]# rolled from the list of communication artifacts #[.s7]#found in http://expgame.com/?page_id=343[Chapter 48: Miscellaneous Equipment].
The device cannot have a wate #[.s7]#greater than 6 kg.
Helmet communications are #[.s2]#common, and this does not count as a roll.
Instruct #[.s1]#the player to roll on the Helmet Accessory table #again.

[.s10]#*2) Gun*: The weapon is rolled in http://expgame.com/?page_id=339[Chapter 46: ]#[.s2]#http://expgame.com/?page_id=339[Guns], and is limited to a pistol, or a pistol version of the gun rolled.
The gun is part of the helmet, and #[.s1]#it is triggered by the wearer&#8217;s head actions.#

[.s53]#*3) Medical Equipment*:#[.s1]#Medical equipment is #[.s6]#rolled in http://expgame.com/?page_id=341[Chapter 47: Medical Equipment].
The only #[.s1]#requirement is that the device rolled be reusable #(not a disposable vedi-kit), and it must have a wate [.s1]#less than 6 kg.#

[.s54]#*4) Miscellaneous Equipment*:#[.s44]#Any bizarre #[.s3]#device could be rolled in http://expgame.com/?page_id=343[Chapter 48: Miscellaneous Equipment].
Again the #[.s1]#maximum wate of the artifact is limited to 6 kg, #[.s6]#and the mood of the referee.
For instance a plastix #[.s2]#helmet with a built in fire log, may be humorous, but cruel.
If the device is not reusable, or it has a #[.s15]#wate greater than 6 kg, the player should roll #[.s1]#another piece of miscellaneous equipment.#

[.s55]#*5) Scope*:#[.s5]#Roll from the list of scope[.s1]# artifacts #[.s7]#found in http://expgame.com/?page_id=343[Chapter 48: Miscellaneous Equipment]##[.s1]#.
There is no limit to the type of scope #that is inserted into the helmet.
The scope will be [.s2]#useable with any weapon of the appropriate type.
For instance, a scope dedicated to rifles could be #[.s7]#used with any rifle that the persona is using.#

[.s41]#*6) Visual Aid*:#[.s2]#Roll from the list of visual aid [.s1]#artifacts #[.s7]#found in http://expgame.com/?page_id=343[Chapter 48: Miscellaneous Equipment]#.
The mutant will be able to #[.s5]#flip the visual aid into and out of place in a stylish visor like #fashion.

== 9) Plastix {.p97}

[table id=389 /]

[.s1]#Plastix armour is nice, white, ceramic composite #[.s3]#plate armour.
The armour has a tendency to #[.s6]#remain clean and white, and is commonly worn by disposable #[.s7]#spacefaring infantry.
This armour type&#8217;s helmet #[.s15]#has a closed face plate with a built in, nearly #opaque, sun visor.
If the helmet is worn the player [.s1]#receives a #[.s5]#penalty of -114 on her to hit rolls.
The armour rating is not compromised if the helmet is removed.
#

== 10) Powered {.p102}

[table id=390 /]

[.s15]#Powered armour is servo aided and computer #[.s7]#enhanced body armour.
Typical powered armour is sealed, carries its own power #[.s2]#plant is integrated with it&#8217;s accessories.
#[.s1]#Powered armour enhances the wearer&#8217;s attributes #[.s7]#by electronically amplifying the persona&#8217;s#[.s3]# natural abilities.
The persona wearing #[.s10]#powered armour is neurally wired into the suit giving #[.s1]#immediate access to an array of equipment built #[.s15]#into her armour.#

[.p109]
=== http://expgame.com/?page_id=3111[Subchapter 42-1]

== 11) Protex {.p161}

[table id=398 /]

[.s9]#Suits of protex are industrial under armour designed to protect personas from specific work place hazards.
#[.s44]#The armour-clothing offers complete #[.s23]#protection from the hazard described.
Each suit consists of gloves, hood, socks, and a body suit.
The problem is that this armour is not designed for the rigors of #[.s5]#combat, and combat will destroy it fairly quickly.
#[.s1]#Protex armour is considered destroyed once the #[.s5]#persona has withstood 100 HPS of damage while wearing the armour.
This means any damage from any source.
Roll on Table 42.6: #[.s7]#Protex Armour Type #[.s5]#to determine the type of protection offered.
#[.s23]#This protection is total, no damage taken, no saves #necessary

[table id=399 /]

== 12) Shield {.p180}

[table id=400 /]

[.s1]#Artifact shields are arm held plates based on the #materials, or technologies, of other TOY armour [.s1]#types.
For instance, a plastix shield may be found #[.s7]#with a suit of plastix armour.
The plastix shield #[.s2]#will improve the user&#8217;s armour rating by decreasing the surface area available for effective attack.
The #[.s1]#main point of a shield is that it can only protect one #[.s2]#flank of the wearer, and does not cover her whole body.
A force field wrist band would only place a force field in front of the persona, and attacks from #[.s15]#the other flanks would not suffer the shielding #[.s7]#bonus.
Further rules for shielding can be found under Shielding in http://expgame.com/?page_id=302[Chapter 29: Armour Rating].
#[.s1]#The type of artifact shield and it&#8217;s benefits are determined #[.s2]#on Table 42.7: Shield Armour Type+++<i>+++.
+++</i>+++All special properties of the armour that apply to the shield are listed on #[.s15]#the table.
Shields are quite dull, and take some #[.s2]#time to roll up since the referee must flip between #[.s7]#several parts of this chapter.#

[table id=401 /]

== 13) Vac Suit {.p178}

[table id=402 /]

[.s6]#The vacuum resistance suit keeps the persona #[.s15]#from being simultaneously asphyxiated, boiled #[.s6]#and frozen by the harsh environment of deep space #[.s5]#(exatmo).
The vac suit, or space suit, is the standard #[.s1]#protection worn by anthropomrphs expecting to #[.s2]#survive zero atmosphere.
There are three separate #[.s44]#types of vac suits: civilian, industrial, and #[.s2]#military**.
**Each of which has it&#8217;s #[.s15]#peculiarities.
#Vac suits will tear only if subject to extreme [.s1]#damaging forces.
If a persona wearing a vac suit #takes 30 points of damage, there is a 30% chance of [.s15]#vac suit rupture.
Vac suit rupture will kill the persona very quickly.
See http://expgame.com/?page_id=282[Chapter 19: Special Terrain].#

[.s53]#*Civilian*:#[.s1]#The civilian vac suit is the virtual #[.s7]#life preserver of outer space.
It can be adorned #[.s23]#quickly, within 1 to 4 units if a normal DEX attribute** **roll is made.
The #[.s2]#wearer will be able to function normally for 4 days.
If the vac suit is worn for greater than 4 days, the #wearer will be preserved cryogenically until revived [.s2]#by medical personnel (DD 5).
The civilian vac suit #[.s7]#has no movement controls to speak of, and the #[.s2]#persona must drag herself around in zero gravity.
Since the civilian vac suit is only going to be worn #[.s3]#in emergency situations is also acts as an all #[.s6]#frequency homing device, emitting a locator-distress #[.s1]#call to all receivers.
#[.s3]#The vac suit can also be worn to protect #[.s2]#against toxins inside an atmosphere.
The suit will #[.s1]#maintain a safe environment for 4 days, and then act as a stasis bag for 4 months.#

[.s59]#*Industrial*:#[.s16]#The industrial vac suit was #[.s5]#designed to do outside repair work for space vehicles #[.s1]#while exatmo.
The suit can be jumped into by a #skilled wearer in 1 to 4 units.
An industrial vac suit can be flown around by the wearer.
It has jets built [.s3]#into the shoes, and gloves, so the wearer can #[.s7]#maneuver at 8 h/u.
The industrial vac suit has a #built in radio, and lots of space for tools, and spare [.s1]#parts.
The industrial vac suit has a mini airlock #[.s7]#which can transfer small pieces of equipment to #[.s6]#the inside of the suit for delicate hands on work.
A persona can function normally for 8 days in this vac #[.s2]#suit, but beyond this time the wearer will be placed #[.s15]#in cryogenic suspension, and an all frequency #[.s1]#emergency beacon will begin transmitting.#

[.s53]#*Military*:#[.s1]#While exatmo, the military vac suit #[.s7]#is virtually undetectable to anything other than #[.s1]#direct visual sight.
The suits have built in lazer #[.s16]#communicators, and line of sight must be #[.s3]#maintained to converse between two talkers.
#[.s1]#Specially articulated gloves allow the wearer to #[.s15]#employ triggered weapons.
There is also a jet #[.s2]#system built into the shoulders and feet of the vac #[.s1]#suit.
The jets allow the wearer to travel at 10 h/u.
#The military vac suit is designed for quick removal [.s2]#once in atmosphere, and can explode off the wearer #[.s1]#in less than a unit.
A military vac suit cannot be #adorned in an emergency basis.
A military vac suit [.s15]#will last for 6 days in exatmo, after which the #[.s1]#wearer is dead.
Most military vac suits will immolate after the wearer has died, leaving no useful evidence other than harmless space debris.
#
