= Armour

This is the artifact armour section.
These armour types not only protect the wearer against general damage, but also have special qualities that vary from thermal protection to computerized, servo-aided joints.
All armour is worn on the body.
Unless otherwise stated, the armour will include torso, limb, hand, foot, and head protection.
Shields are not included in armour protection.
Each separate armour type has several statistics listed.
These are explained in the following paragraphs.

.Armour Checklist
. <<_armour_type, Armour Type>>
. <<_armour_attribute_explanations,Armour Attribute Explanations>>

== Armour Type

include::ROOT:partial$CH42_Table_Armour_Type.adoc[]

== Armour Types

=== Ablative Armour

[horizontal]
Armour Rating:: 625
Restrictiveness:: 3
Wate:: 2.5 (1.5kg)
EXPS:: 200
Value:: 590/kg (900)

Ablative armour is designed to negate lazer attacks.
When hit by a lazer the ablative material vaporizes, producing an anti-lazer gas that dissipates the lazer bolt, keeping the attack from damaging the wearer.
When hit by a lazer, the wearer will take no damage because of the ablative armour.
This armour only works against lazers, and cannot affect energy attacks such as fission, fusion, or plasma.
The armour rating represents how well the armour is at deflecting all other attacks.
Since the armour vaporizes to disrupt lazers, it has a limited life-span.
The armour will lose its ablative effect after disrupting 300-1000 (1d8+2 x 100) hit points of lazer damage.
If a lazer attack scores a hit, damage is rolled as normal, but the damage is subtracted from the armour, not the target.
Once the ablative effect is worn out the armour retains its AR of 625, but loses all special defences against lazers.

=== Ballistic Amour

[horizontal]
Armour Rating:: 625
Restrictiveness:: 3
Wate:: 2.9 (2kg)
EXPS:: 200
Value:: 590/kg (1200)

Ballistic armour is designed to negate ballistic attacks.
A criss-crossing mat of super-dense polymers is woven to absorb high velocity projectile damage (bullets, fragments, etc.).
Ballistic armour is capable of absorbing 100-600 (1d6 times 100) hit points of high velocity (Type C attacks) damage.
Once the armour has sustained this maximum damage it will be unable to negate projectile damage, but maintains it AR of 625.
Ballistic cloth does not absorb damage from from type A attacks, such as: punches, maces, pipes, flails, etc.

=== Combat Armour 

[horizontal]
Armour Rating:: 725
Restrictiveness:: 2
Wate:: 3.0 (2kg)
EXPS:: 100
Value:: 1000/kg (2000)

Combat armour is typical futuristic, militaristic body protection designed for infantry dogmeat.
It usually composed from such mundane materials as Kevlar weaves and ceramic plates.

=== Compucrafted Armour

[horizontal]
Armour Rating:: Plus 30-120 (3d4 times 10)
Restrictiveness:: 0-3 (1d4-1)
Wate:: Halved
EXPS:: 300 
Value:: See below

Compucrafted armour is computer designed versions of mundane armour types.
They are designed to handle stress better, deflect blows better, be less restrictive, and have less wate.
Compucrafted armour uses special alloys, plastics, and ceramics which are not found in regular mundane armour types.

include::ROOT:partial$CH42_Table_Compucrafted_Armour_Types.adoc[]

Roll the mundane armour type on Compucrafted Armour Type Table.
The armour rating (AR) is increased from the mundane base by 30-120 (3d4 x 10).
Lighter and less cumbersome materials allow for freer body movement, giving the armour a new restrictiveness between 0-3 (1d4-1).
The new restrictiveness cannot exceed the mundane armour's previous restrictiveness.
The wate of the compucrafted armour is reduced by half and it's value is increased 4 times.
EXPS value is a flat 300 points for all types of compucrafted armour.

=== Concussion Armour

[horizontal]
Armour Rating:: 625
Restrictiveness:: 3
Wate:: 2.9 (2kg)
EXPS:: 200
Value:: 590/kg (1200)

Concussion armour is designed to absorb concussive forces.
The protection looks lie a bulky, pillowy onesie.
Each of the large fluffy lumps is full of small resilient beads that increase the surface area that concussion force is absorbed over.
This design reduces crushing damage from explosions, falls, crashes, blunt weapons, squeezing attacks, etc.
Any of these damages types are reduced by 1/2 when wearing concussion armour.
Concussion armour has a base AR of 625, and all attacks must score a hit before any damage can be taken.

=== Flexion Covering

[horizontal]
Armour Rating:: None
Restrictiveness:: Table
Wate:: Table
EXPS:: 333
Value:: Table

Flexion coverings are designed to increase protection against specific attacks.
They offer no protection against attacks other than the ones they were manufactured to thwart.
The various flexion coverings appear as beltless, pocket-less ponchos, parkas or trench coats.
The protection is designed to be worn over armour and equipment.
The flexion coverings can essentially withstand limitless damage.
Flexion should only do so after the persona has sustained 1000 hit points in damage.
The ref can arbitrarily have flexion armour wear out if the covering is being abused.

include::ROOT:partial$CH42_Table_Flexion_Covering_Type.adoc[]

Concussion::
Concuflex reduces the chance of being injured by concussion attacks.
Shockwaves, crushing and gravity attacks are concussive attacks.
Concuflex increases the persona's armour rating (AR) by +150 against such attacks.
This covering appears as a bulky down parka.

Electro:: 
Electroflex reduces the chance of being injured by electrical attacks.
Electrical based attack include stun, lightning arcs and electrocution.
Electroflex increases the persona's armour rating (AR) by +150 against such attacks.
This covering appears like a black slicker with tendrils reaching the ground.

Energy:: 
Enerflex reduces the chance of being injured by energy attacks.
Energy weapons include fusion, fission and plasma attacks
Enerflex improves the persona's AR by +150 against energy attacks
This covering appears like a translucent shimmering raincoat.

Inertia::  
Inerflex reduces the chance of being injured by energy inertia attacks.
Classic inertia attacks are focused concussive damage like swords, punches, or inertia weapons.
Inerflex improves the persona's AR by +150 against inertia attacks.
This covering appears like a wet flattened down parka.

Lazer::  
Reflex reduces the chance of being injured by energy lazer attacks.
Lazer attacks include anything generated by a lazer, including lazer sights and lazer detectors.
Reflex improves the persona's AR by +150 against lazer attacks.
This covering appears like a matte trench coat with reflective flecks.

NOTE: *Previous incarnations of EXP employed a 'c' (reflec, concuflec) instead of an 'x'. The change was due to a marketing issue in a distant planet where sales were high. It turned out that the 'c' ending for flexion products sound similar to a derogatory term in the language of the main buyers.*

Projectile::  
Proflex reduces the chance of being injured by high velocity projectile attacks.
Projectile attacks include bullets, crossbow bolts and launched quills.
Proflex improves the persona's AR by +150 against projectile attacks.
This covering appears like a poncho woven from tiny ballistic tiles.

Vibro:: 
Vibroflex reduces the chance of being damaged by the very specific vibro weapon attacks.
Vibro attacks include any vibro enhanced attack, sonic attacks other high frequency damage.
Vibroflex improves the persona's AR by +150 against vibration attacks.
This covering appears like a rough weave of loose fibers.


=== Force Field 

[horizontal]
Armour Rating:: 0
Restrictiveness:: 0
Wate:: Table
EXPS:: 500
Value:: Table

Force field belts generate an invisible defensive shield contoured to the wearer's body.
The electromagically generated field dissipates kinetic energy protecting the wearer.
Any attack that uses energy (kinetic, lazer, clubs) will be absorbed by the belt.
The field is raised instantly when an incoming attack is detected.
Any damage that would have been taken by the wearer is absorbed by the force field belt.
Poison gas, radiation, kisses or psionic attacks are not stopped by this force field.

Once the maximum damage has been absorbed the force field shuts off.
The force field belt cannot be used until its batteries are replaced.
Force field belts vary in the number of hit points they absorb, and increase in WATE and value depending on their  capacity to absorb damage.

include::ROOT:partial$CH42_Table_Force_Field_Belt_Strength.adoc[]

=== Helmet 

[horizontal]
Armour Rating:: +40
Restrictiveness:: 0
Wate:: Special
EXPS:: 50 + TOY  
Value:: 100 + TOY 

These are specialized helmets that offer head protection and equipment.
The helmet could have a gun, veterinarian equipment, or scope installed.
The device can be controlled by voice command, tongue wrangling, or facial contortions.
The base helmet type is determined by the milieu of the campaign.

Typically it will from the one of the following armour types:

.*Helmet Types*
. <<_combat_armour,Combat Armour>>
. <<_compucrafted_armour,Compucrafted Armour>>
. <<_plastix_armour,Plastix Armour>>

Regardless of the helmet type the AR bonus is the same. 
Helmets have no effect on restrictiveness. 
The Wate of the helmet is determined by the bespoke equipment.
The Value of the helmet is determined by the value of the equipment.

The type of equipment installed is limited by wate and reason.
Heavy items would not only be impractical, but would cause severe neck injury.
The table is an abbreviated list of equipment that may be useful in a combat helmet.


include::ROOT:partial$CH42_Table_Helmet_Accessory.adoc[]

Communication:: 
The communication device is generated at xref:iv-hardware:CH48_Misc_Equip.adoc#_communicators[communicators].
The device cannot have a wate greater than 6 kg.
Helmet communications are common, and this does not count as a roll.
Instruct the player to roll on the Helmet Accessory table again.

Gun:: The weapon is rolled in  xref:iv-hardware:CH46_Guns.adoc#_gun_type[Gun], and is limited to a pistol, or a pistol version of the gun rolled.
The gun is part of the helmet, and it is triggered by the wearer's head actions.

Veterinarian Equipment:: Veterinarian equipment is rolled in xref:iv-hardware:CH47_Medical.adoc#_veterinary_equipment_type[Vet Equipment].
The only requirement is that the device rolled be reusable (not a disposable vedi-kit), and it must have a wate less than 6 kg.

Miscellaneous Equipment:: Any bizarre device could be rolled in xref:iv-hardware:CH48_Misc_Equip.adoc#_miscellaneous_equipment_type[Miscellaneous Equipment].
Again the maximum wate of the artifact is limited to 6 kg, and the mood of the referee.
For instance a plastix helmet with a built in fire log, may be humorous, but cruel.
If the device is not reusable, or it has a wate greater than 6 kg, the player should roll another piece of miscellaneous equipment.

Scope:: Roll from the list of scope artifacts found in xref:iv-hardware:CH48_Misc_Equip.adoc#_scopes[Scopes].
There is no limit to the type of scope that is inserted into the helmet.
The scope will be useable with any weapon of the appropriate type.
For instance, a scope dedicated to rifles could be used with any rifle that the persona is using.

Visual Aid:: Roll from the list of visual aid artifacts found in xref:iv-hardware:CH48_Misc_Equip.adoc#_visual_aids[Visual Aids]
The persona will be able to flip the vizaud in and out of place with a stylish visor.

=== Plastix Armour

[horizontal]
Armour Rating:: 800
Restrictiveness:: 1
Wate:: 1.0 (0.7kg)
EXPS:: 75
Value:: 1000/kg (1000)

Plastix armour is unusually clean looking, white, ceramic composite plate armour.
The armour has a tendency to remain clean and white.
This ceramic plating is commonly worn by disposable spacefaring infantry.
This armour's helmet includes a closed face plate with a nearly opaque, sun visor.
Any persona wearing the helmet suffers a -114 penalty on her attack rolls.
The armour rating is not compromised if the helmet is removed.


=== Powered Armour

[horizontal]
Armour Rating:: 750
Restrictiveness:: 15
Wate:: 300 (210kg)
EXPS:: 1000
Value:: 10000000 + accessories

Powered armour is servo aided and computer enhanced body armour.
Typical powered armour is sealed, carries its own power plant is integrated with it's accessories.
Powered armour enhances the wearer's attributes by electronically amplifying the persona's natural abilities.
The persona wearing powered armour is neurally wired into the suit giving immediate access to an array of equipment built into her armour.

Jump over to the chapter devoted to xref:iv-hardware:CH42_Powered_Armour.adoc[Powered Armour].


=== Protex

[horizontal]
Armour Rating:: 600
Restrictiveness:: +2
Wate:: None (2kg)
EXPS:: 900
Value:: 20000

Suits of protex are industrial under armour designed to protect personas from specific work place hazards.
The armour-clothing offers complete protection from the hazard described.
Each suit consists of a body suit and integrated gloves, hood, and socks.
This armour is not designed for the rigors of combat.
Combat will destroy protex fairly quickly.
Protex armour is considered destroyed at 400 HPS of total damage.
Any hit points of damage that the persona suffers are considered protex damage.
This includes any damage from any source.
The protection is total, no damage taken, no saves necessary

include::ROOT:partial$CH42_Table_Protex_Armour.adoc[]

=== Shield 

[horizontal]
Armour Rating:: Table
Restrictiveness:: Table
Wate:: Table
EXPS:: 100
Value:: Table

A shield is a handheld sheet of armour used to deflect and block attacks. 
This is not a force field.
These are shields like a buckler or tower shield.
A shield can only protect one flank, and does not cover the entire persona.
They are crafted from specific armour types and offer bonuses in AR and defences.
A plastix shield may be found with a suit of plastix armour.
A force field wrist band would generate a shield shaped force field.

include::ROOT:partial$CH42_Table_Shield_Type.adoc[]

Ablative Shield::
This shield is based on the armour type <<_ablative_armour,Ablative>>. 
The shield gives an armour rating bonus of +75 and defends against lazer attacks.
The shield negates 10-100 (1d10 x 10) hit points of lazer damage.

Ballistic Shield::
This shield is based on the armour type <<_ballistic_armour,Ballistic>.
The shield gives an armour rating bonus of +75, and defends against ballistic attacks.
The shield negates 10-100 (1d10 x 10) hit points of ballistic  damage.
 
Combat Armour Shield::
The shield is based on the armour type <<_combat_armour,Combat>>.
The shield gives an armour rating bonus of +125.
It is often found with a full suit of combat armour.

Compucrafted Shield::
This shield is base on a <<_compucrafted_armour,Compucrafted>> version of mundane armour.
The shield improves armour rating by +3-300 (3d10 * 10).

Concussion Shield::
This shield is based on the armour type <<_concussion_armour,Concussion>>.
The shield gives an armour rating bonus of +75, and defends against concussion attacks.
The shield negates 10-100 (1d10 x 10) hit points of concussion  damage.

Flexion Shield::
A flexion shied like an umbrella made of <<_flexion_covering,Flexion>> armour.
The shield gives an armour rating bonus of +125.

Force Shield::
A force field shield a defensive wall projected from a wrist band. 
It does not encompass the persona's body like a regular <<_force_field,Force Field>>.
The force shield absorbs 10-100 (1d10 x 10) hit points per battery.

Plastix Blocker::
This large white shield is based on the armour type <<_plastix_armour,Plastix>>.
The shield gives an armour rating bonus of +75, and impairs the user's accuracy.
Using a plastix shield will inflict an attack roll penalty of -100.

Powered Shield::
A powered shield is an attachment for an upper limb of xref:iv-hardware:CH42_Powered_Armour.adoc[Powered Armour].
The shield is meant to be bolted onto the peripheral point of a powered armour limb.
The shield gives an armour rating bonus of +100 and 0-2 (1d3-1) accessories.
The accessories for a powered shield are generated at xref:iv-hardware:CH42_Powered_Armour.adoc#_upper_limbs[Upper Limbs].

Protex Shield::
A protex shield is based on the armour type <<_protex,Protex>>.
There is no adjustment of the persona's armour rating. 
The will absorb 100-400 (1d4x100) hit points of the protex type. 

=== Vac Suit
The vacuum resistance suit protects organic personas the harms of space.
The cumbersome vac suit beats being simultaneously asphyxiated, boiled and frozen.
The vac suit can also be called a space suit.

NOTE: *The vacuum of space is often abbreviated to as exatmo. Exterior to atmosphere. The abbreviation for in atmosphere is inatmo.*

There are three separate types of vac suits: civilian, industrial, and military.
Each of which has it's own peculiarities.
Vac suits will rip only if subject to direct damaging forces.
Shooting a vac suit or trying to puncture it may lead to rupture.

None of these vac suits are fabricated to survive entry into an atmosphere. 


include::ROOT:partial$CH42_Table_Vac_Suit.adoc[]

==== Civilian

[horizontal]
Armour Rating:: 500
Restrictiveness:: 4
Wate:: 10 (8kg)
EXPS:: 350
Value:: 100000

The civilian vac suit is the life preserver of outer space.
It is designed to keep civilians alive in case of an exatmo emergency.
It can be adorned quickly and is simple to understand.
Explosive decompression is an exception to this and survival depends on the situation. 

The civilian vac suit has no movement controls. 
Personas must clumsily drag themselves around by grappling in zero gravity.

The persona will be able to function for 4 days in a vacuum.
After day 4 the persona suit turns into a personalized cryogenic suspension unit.
Vac suit cryo will keep a persona alive as long as it suits the story.
Being resuscitated from vac suit cryo is a veterinarian maneuver.

The vac suit can also be worn to protect against toxins inside an atmosphere.
The suit will maintain a safe environment for 4 days, and then act as a stasis bag for 4 months. 

Civilian vac suits have an all frequency homing device, emitting a locator-distress call.

A civilian vac suit is relatively delicate and intentional destruction can lead to rupture.
If warranted there is a 1% chance of rupture per hit point of damage.
For example, 30 hit points of damage equals a 30% chance of vac suit rupture.
Vac suit rupture will quickly kill the persona.

==== Industrial

[horizontal]
Armour Rating:: 600
Restrictiveness:: 8
Wate:: 30 (21kg)
EXPS:: 350
Value:: 250000

The industrial vac suit is designed for repair work in outer space.
It is cumbersome to put on and is not useful in an emergency decompression.

An industrial vac suit can be flown around by the wearer.
Jets in the shoes, and gloves, allow the wearer to maneuver at 6 h/u.

The industrial vac suit has a built in radio, and storage for tools, and parts.
The industrial vac suit also has a mini airlock.
The airlock allows for delicate inatmo hands on work.

The industrial vac suit can be inhabited for 1 day.
Beyond one day of use the wearer will die from the perils of exatmo. 
There are no safety features like those found in civilian vac suits.
An industrial vac suit cannot function inatmo.

==== Military

[horizontal]
Armour Rating:: 700
Restrictiveness:: 6
Wate:: 20 (15kg)
EXPS:: 350
Value:: 300000

A military vac suit is the least hospitable of vac suits.
It is designed to be stealthy, combat ready and expendable. 
There are no similarities between powered armour and military vac suits.
The military vac suit has no role in emergency procedures.

The military vac suit is designed not to be found. 
It is dark, light absorbing and hard to detect.
There are no finding beacons. 
Communications is only through direct line of a site with a lazer communicator.

The suit has a jet system built into the shoulders and feet of the vac suit.
This jet system is nimble and can be turned on a electrum piece.
The system allows the wearer to travel at 12 h/u.

The gloves are highly articulated allowing the wearer to employ any weapon.
The entire suit is designed for explosive removal in atmosphere.
This is to ensure the wearer is immediately combat ready when boarding a space vehicle.
A military vac suit cannot function inatmo.

A military vac suit will function for 6 days in exatmo.
There is no cryogenic suspension. 
In fact it is quite the opposite.
Upon incapacitation of the wearer a military vac destroys itself and it's wearer.
The suit melts into harmless space debris leaving no useful evidence behind.

== Armour Attribute Explanations

=== Armour Rating 
The higher the armour rating, the better the protection offered to the wearer.
Not all the armour in this chapter has a high armour rating, but each offers some unique form of special protection.
Those armour types without a listed armour rating have a value listed that is added to the armour rating (AR) of regular armour types.
These armour types are meant to be worn in conjunction with other armour types.

The base armour rating of an unarmoured target is 500.
The armour ratings are related to this base value.
For instance a suit of armour that has an armour rating of 725 would give the wearer a base armour rating of 725 instead of 500.
This could also be considered an armour rating (AR) bonus of +225.
The complexities and confusions of armour rating are discussed-in more detail in the tactical combat system.

=== Restrictiveness 
The more restrictive a suit of armour is, the more cumbersome, and unyielding it is to normal body movement.
This is represented by a higher restrictiveness value.
The less restrictive armour is the more that the persona can use her natural dexterity to avoid taking damage.
This operates the same for artifact armour as it does for mundane armour.

=== Wate (Flat Wate)
The wate of  armour is listed as  percent of body wate.
% Body WATE is used to determine the wate of the suit of armour.
Armour is a form of clothing, and it is usually tailored to a particular wearer.
Thus the wate of armour is related to the wate of the wearer.
Previously there were no set WATEs for armour for the reason that different amounts of material are required for different body sizes.
Therefore armour WATE is listed as a percentage the body wate of the persona that the armour was designed for.

A flat wate in kgs is included in brackets based on the % wate.
The flat wate is based on that of a 70 kilogram anthro.
The armour's WATE must be recorded and considered part of the persona's encumbrance.
Nice referees will conveniently fit found armour to the wate of the persona who found it.
If the scenario indicates that found armour has been tailored for a specific race, then such a convention cannot apply.

=== EXPS 
Experience points for armour are earned when the player identifies the armour's special function.

=== Value 
Value of armour will be listed in one of two ways: a single value, or a cost per kilogram.
A single value represents the flat cost of the armour.
Some armours are composed of material which is very valuable, and the amount of this material reflects the value of the armour.
These armour types are listed as having values like 590 per kilogram or 750 per kilogram.
So the value of such armour is directly related to the wate of the armour.
If the armour had a wate of 2 kilograms, and it were worth 750 eps per kilogram, it would be worth 1500 eps.
For convenience a value based on the wate armour required for a 70 kilogram anthro will be included in brackets.

