= Aerosols
An aerosol is a cylindrical canister that violently ejects a pressurized, gaseous solution through a push button valve.
When activated, an aerosol will discharge all of its contents, and cannot be used again.
Unlike grenades, aerosols lack a history of military use.
Aerosols  unforeseen methods of conflict, or could merely be maliciously employed industrial devices.

== Range 
Aerosols:The range of an aerosol depends entirely on the pressure of its contents.
This internal pressure usually ejects the contents of the aerosol a safe distance before exploding with an area of effect blast.
Some aerosols have an swath area of effect, and the range represents the longest dimension of this area of effect.
For more info see chapter 30, Grenade and Aerosol Combat.

== Area of Effect 
Aerosols:An aerosol is an area of effect weapon.
First the contents of the aerosol are sprayed a certain distance, and once reaching that range (or hitting a solid object) the contents explode about their area of effect.
For example, a freezing aerosol has a 9 hex range, and an 8 hex area of effect.
This aerosol fires out 9 hexes, and then freezes everything in an 8 hex spherical area of effect.

== Damage 
This is the hit point range that is inflicted upon any target caught within the area of effect of either an aerosol or grenade.
Wherever the damage has been omitted, the aerosol has some other special effect.
Remember that damage is rolled once, and applied to all targets within the area of effect.
Unless specified there is no save versus area of effect attacks.

== Wate 
This is the wate of an unspent grenade, or aerosol.
An empty aerosol canister has a wate 10% of its original wate.
E.g., 2 kg aerosol is reduced to an empty 200 gm canister.

== EXPS 
Experience points for identifying a grenade, or aerosol, are earned the same as for any other artifact.
An equivalent experience point value can be earned after either weapon has been discharged, but these EXPS* *can only be earned by the firer.

== Value 
The value of a grenade, or aerosol, is the value of one charge.
In some cases aerosols can generate more than one charge, but even with these modifications such aerosols still have the same value.

== Trigger 
Aerosols are even simpler to use than grenades.
Push the release valve on top of the canister, and all its contents instantly spray out for all their described effects.

== Amount 
The ref rolls a d8 to determine the number of aerosol canisters found in a package.
For powerful campaign altering aerosols one will suffice.

== Description 
The aerosol can appears to be an oversized version of today's typical Freon container.
The aerosol may have a distinctive colour--either the canister, or the jet--that can be rolled on the Grenade Colour table.

Aerosol Markings:Since many of the aerosols described in this chapter are non-military in.
nature, many may still have their industrial labelling intact.
To determine the literacy of an aerosol's labelling roll a d10.
A roll of 1 indicates unintelligible labelling.
This is labelling that is either in an alien language, has incorrect instructions, or is somehow damaged.
A roll of 10 will yield an aerosol with proper markings, and instructions.
Proper labelling may greatly reduce the ExPs value of an aerosol, but increase its monetary value.
All other rolls (29) indicate that no markings of any sort are listed on the aerosol canister.

== Aerosol Type 
Roll on table 45.6: Aerosol Type to determine aerosol type.
This table should not be used for generation of TOYs for personas.
It is not properly balanced for initial artifact rolls.



== Antilazer Aerosol 
The antilazer aerosol will dissipate any lazer bolts which pass through its gaseous field. 
The antilazer cloud does not obscure vision, but it does cause lazers to flare out into harmless glowing balls. 
The antilazer aerosol affects lazers, but energy attacks—​fission, fusion, plasma—​are unaffected. 
There is no limit to the amount of damage that antilazer aerosol can dissipate, and the shimmering cloud will evaporate 1-10 minutes after discharge.

.Antilazer aerosol attributes
[width="50%",cols="2*<"]
|===

s|Range
|4h

s|Area of effect
|7h

s|Damage
|None

s|Wate
|2kg

s|EXPS
|275

s|Value
|1000

|===




== Attraction Aerosol 
The attraction aerosol is an incredibly potent anti-repellant.
The attraction aerosol discharges pheromones, vibrations, chemicals, or sounds that attract a particular entity.
Whatever type of creature is affected by this aerosol will swarm towards the center of the discharge.
The creatures will be hungry, desperately in love, or just plain curious.
Exactly how many referee personas approach the expedition depends mostly on the mood of the referee.
The ref should moderate a wholesale onslaught of deadly attackers with lots of harmless aliens.
This aerosol is also known as a love bomb.

.Attraction Aerosol attribute list
[width="50%",cols="2*<"]
|===

s|Range
|None

s|Area of Effect
|1 km

s|Damage
|None

s|Wate
|2.0kg

s|EXPS
|250

s|Value
|100

|===

// insert table 506

== 24) Blinding Aerosol 

// insert table 507

Any target with organic optical sensors must save versus poison or be blinded when subject to this attack.
Every 3 units spent within the cloud will require the target to make another save versus poison or be blinded.
The save is against intensity 2-20 (2d10) poison.
If blinded, the target will remain blind for 0 to 9 minutes.
If the duration of the blindness is less than 1 minute, the target will be blinded for 1 to 20 units.
The cloud of the aerosol is invisible, and will dissipate in 1 to 12 units.
Any target entering the cloud must save versus blindness.
The blinding aerosol is commonly called tear gas.

== 25) Catabolic Dismodulator Aerosol 

// insert table 508

The catabolic dismodulator turns inorganic matter into an opaque, multi-hued, cloud of gas.
The effects are devastating to equipment, and robots.
If the ref feels that the effects of this weapon may severely disrupt the course of a campaign, she may allow persona robots a save versus intensity 13 to 28 (10+3d6) poison, or be destroyed.
Note that only solid inorganic matter within the target hex is dismodulated.
The 3 hex area of effect refers to the cold damage taken by all targets within the area of effect cloud.
Those organic creatures hit directly with a catabolic dismodulator have a 5% chance of  dismodulating along with their equipment.
If the dice should indicate this, it is only polite to offer the same saving throw awarded to persona robots.
If the player fails this roll her persona is dead.
Jump to http://expgame.com/?page_id=275saving-throw[saving throws]  for more information.

== 26) Demagnetizer Aerosol 

// insert table 509

The relevance of this aerosol to anything in particular escapes me, it is sort of an industrial strength tape head cleaner which briefly nullifies the weak forces of magnetism.
The obvious problems that could arise from this are: magnetic buckles detaching themselves;
TV sets going blank;
magnetic legs (vehicles, and robots) collapsing;
electronic components ceasing to function;
computer memories being erased;
and little plastic animals falling off of the fridge.
Military electronics will get a save versus mental attack, intensity 3 to 18, to avoid being affected by the attack.
The magnet's battery source, the magnets themselves, or any electronic components will be restored to normal operation after 3-18 units.
There is a 1% chance per unit of dysfunction of a device being permanently damaged.
See http://expgame.com/?page_id=286[Chapter 21: Equipment Damage] for what tragedy demagnetization could cause.


== 27) Disintegrator Aerosol 

// insert table 510

The disintegrator aerosol turns inorganic substances into dust.
More refined, and discerning, than its cousin the http://expgame.com/?page_id=33725-catabolic-dismodulator[catabolic dismodulator aerosol], the disintegrator aerosol will only affect a certain substance.
The substance type is determined on Table 45.8: Disintegration Type.
Any amount of this material caught in the 1 hex area of effect will be broken down into a useless dust massing much less than its previous wate.

Any complex equipment, composed of many basic materials, caught in the area of effect has a % chance, determined by the referee, of malfunctioning.
The malfunction is assumed to have been caused by some integral part of the device disintegrating into dust.
The chance of this happening can be determined by rolling http://expgame.com/?page_id=275sphincter-dice[Sphincter dice], as described in chapter 16, Special Rolls.
The extent of the damage should be determined in http://expgame.com/?page_id=286[Chapter 21: Equipment Damage]

// insert table 511

== 28) Exploding Aerosol 

// insert table 512

This sadistic device explodes like a fragmentation grenade when it is triggered.
All targets in the 1 hex area of effect take the damage listed.
The referee should note that it is very impolite to laugh when an exploding aerosol is discharged.

== *29) Foam Aerosol* 

// insert table 513

The foam aerosol creates a pad of creamy foam 16 hexes across, and 2 hexes deep.
For the first minute, the foam can be easily travelled through.
By the end of the second minute the foam is starting to thicken, and movement is halved.
Three minutes after being discharged the foam will be so viscous that movement will be reduced to one quarter.
The pad will be completely solidified 4 minutes after its discharge, and anything caught within it will be completely trapped.
At no time, even during the solid phase, is breathing hampered in any way by the foam.
Anything entombed by the foam pad will starve to death before anything else.
The foam is not much stronger than styrofoam, but only those persons trapped in the outer edges, and those who are particularly industrious will be able to free themselves.
The colour of the foam will be the same as on the outside of the aerosol canister.
Once solid, the foam is structurally sound, and well insulated.
This aerosol has been given synonyms such as the insulator, and the homemaker.

== 30) Freezing Aerosol 

// insert table 514

The freezing aerosol subjects all targets in its area of effect (8 hexes) to an enthalpy attack, coating everything with ice and snow.
The freezing aerosol has a % chance, equal to the damage inflicted, of entrapping large, or smaller, sized targets in ice.
This attack also freezes switches in place, triggers in the firing position, pins in grenades, pant zippers closed, etc.

== 31) Gas Aerosol 

// insert table 515

The gas aerosol fills the area of effect with a pall of transparent, but noticeable gas.
The cloud of gas will affect all within it, and saving throws vs.
poison must be made for every unit within the area of effect.
The cloud will dissipate in 4 to 16 units.
The intensity of the poison in the gas cloud varies between 2 and 16.
Roll on the below table to determine the effect of the gas.

// insert table 488

== 32) Invisibility Aerosol

// insert table 516

The magical invisibility aerosol permeates all visible matter within its area of effect with a substance that does not reflect, or deflect the path of light.
Everything in the area of effect will be undetectable to sensors that use reflected light.
Sonar, infravision, ultravision, and other such sensors will detect these &8220;invisible&8221;
objects normally.

Everything within the hex of discharge will be invisible: the ground, walls, equipment, personas, halves of personas.
The aerosol does an effective job of making the targets disappear, but remember that these invisible objects still exist.
Equipment is easily lost, personas still make noise, personas still smell, and eye hand co-ordination is virtually non-existent.
The invisibility aerosol can offer a great escape route, but can also cause a lot of trouble for the users.
The effects of this aerosol will last for 1 to 4 days.

== 33) Matter Detector Aerosol 

// insert table 517

The matter detector aerosol is much more useful than its title implies.
Any solid matter within the area of effect of this aerosol will be affixed with chemicals that emit low levels of heat, light, radiation, and vibrations.
This allows matter to be detected by any of the more common sensors (eyes, infravision, sonar, etc.).
The aerosol can also be used to determine whether something is composed of solid matter or not.
Hence it makes a good hologram detector also.

All matter in the area of effect will glow light blue, and then fade into glowing technicolor for 14 minutes.
The effect of the matter detector will continue for 1 to 4 minutes, and during that time any target can be seen through smoke, darkness, behind holograms, or in hiding places.
Any to hit rolls will receive a bonus of +65 to hit on any target hit with a matter detector aerosol.
Hiding maneuvers are 10 DDs more difficult if the persona has been affected by this aerosol, and ambushes are 10 times easier to detect.
Targets that wish to avoid detection may attempt to disappear after the 1-4 minute duration ends.
This aerosol is also called a marker aerosol, or a targeting aerosol.

== 34) Mistor Aerosol 

// insert table 518

The mistor is the complete opposite to the matter detector aerosol.
The mistor renders all detection equipment--eyes, sonar, infravision, touch, smell, everything--completely useless when within the area of effect.
No lights can penetrate the cloud, yelling is futile, and everything feels cool to the touch.
Virtually all sensors are dulled through lack of stimuli.
Any attacks made are in a random direction, even if the target recently brushed against the attacker.
Movement is random, unless the persona has some form of heightened directional sense.
The suspension will remain cohesive for 16 days.

== 35) Molecular Diffusion Aerosol 

// insert table 519

The molecular diffusion aerosol is a nasty sounding combat weapon that inflicts the prescribed damage to all targets in the area of effect.
How the aerosol inflicts its damage, and what happens when it is discharged is left to the improvisational talents of the referee.

== 36) Napalm Aerosol 

// insert table 520

The napalm aerosol blasts a swath of flaming gas and gel when it is triggered.
This is definitely not a toy you'd like to mistakenly point backwards.
Anything caught in the blazing area of effect will be seared for 6 to 60 (6d10) hit points of damage, and then promptly immolate for further damage.
Targets that have immolated will burn for an additional 2 to 8 units.
Burning targets will take an additional 4 to 24 hit points of damage each unit that they are aflame.
Other than the flaming targets, the napalm aerosol will extinguish itself immediately.

== 37) Paint Aerosol 

// insert table 521

The paint aerosol can be used to paint the entire wall of a room with one explosive button push.
Unfortunately this time saving feature will paint everything in front of the wall also.
The completely indiscriminate nature of the paint aerosol allows it to be used as a weapon.
When sprayed onto opponents, or expedition members, they must make a successful saving throw versus poison, or be blinded for 1 to 20 units.
The intensity of the poison will be from 1 to 12.
The referee may allow the player to use her persona's DEX instead of CON for this saving throw.
The paint colour will be the same as the colour of the aerosol canister.

// insert table 443

== 38) Pharmaceutical Aerosol 

// insert table 522

This aerosol can be used to apply long range prescriptions to groups of patients.
What sort of plague, military infestation, or Woodstock celebration prompted the invention of such a dispenser is unknown.
The pharmaceutical type, effect, duration, etc.
is determined in http://expgame.com/?page_id=347[Chapter 50: ]http://expgame.com/?page_id=347[Pharmaceuticals].

All targets in the area of effect must fail a save versus poison to be affected by the medication.
The intensity of the poison (pharmaceutical) is 2 to 20.
This intensity is reduced by one for every target in the area of effect.
The more potential users, the milder the dose.
Note that it is possible to make the spray from this aerosol completely ineffective by having too many targets in the area of effect.
The cloud dissipates immediately after it has been ejected.

== 39) Poison Aerosol 

// insert table 523

The poison aerosol is a very selective, very lethal, combined nerve gas and respiratory poison.
Whatever type of creature is poisoned _ _by this aerosol must make a save versus intensity 2 to 24 poison, or die.
Creatures that save versus the poison attack will automatically be repulsed by the 12 hex x 3 hex swath, and will not cross, or approach the lingering residue.
The attack is only lethal to those targets caught within the initial blast, but the repellant effect will linger for 1 to 3 hours.
These population strength poison aerosols are usually labelled &8220;raid&8221;, or nerve gas canisters.

// insert table 488

== 40) Repellent Aerosol 

// insert table 524

This is the pacifist's version of the poison aerosol.
Creatures of the repelled type must save versus poison (intensity 13-28), or not be able to approach anything covered by this aerosol.
The aerosol will start to repulse creatures at a 10 hex range.
This repelling effect will last for 1 to 6 days.
Intelligent creatures may make an additional save each new day in which they approach the repulsive area.
Unintelligent aliens will most likely bolt in terror when failing to save versus the repellent.
This aerosol is also called off, repex, or protector.

// insert table 1056

== 41) Siren Aerosol 

// insert table 525

This ear splitting siren will wail for 2-8 minutes, inflicting 2-12 hit points of damage to all within the area of effect.
The siren aerosol will inflict double damage to mutants employing sonar.
There is also a 10% chance per hit point of damage inflicted of that the target will become deaf.
There is no saving throw granted.
Hearing will be restored after 1-10 hours.
The screeching will continue to inflict 2 to 12 hit points of damage each minute until the hearing target is deafened, unconscious or out of range.
This aerosol has severe environmental effects.
When used outdoors most of the smaller animals--birds, hares, jackalopes, and rats--in the 1 kilometer radius of effect will be killed.
The expedition will also have to deal with a considerable number of deaf, confused, and possibly angry local fauna.

== 42) Smoke Aerosol 

// insert table 526

This smoke aerosol will instantly discharge a 24 hex diameter sphere of dense smoke.
The smoke will obscure the vision of any visual sensors caught within its field.
This means that there is a -230 per hex to hit penalty for ranged attacks, unless the persona has some sort of smoke cutting device.
The smoke is so dense that it can only be moved by a gale force wind, or a bulldozer.
The cloud will disperse in 1 to 8 weeks.
The colour of the smoke will be the same as the colour of the canister that it was ejected from.

== 43) Web Aerosol 

// insert table 527

The web aerosol splatters the area of effect with a super adhesive goo.
Anything caught in the area of effect will be trapped until the webby mess dissipates 2-16 minutes later.
Any persona that saunters into the messy web will instantly become glued.

To escape the persona must make a bizarre PSTR roll (kilo-die).
Otherwise she is trapped until the web decomposes.
During each escape attempt the entrapped persona must ensure that she does not glue her mouth and nose shut risking suffocation.
There is a 1% chance of this happening each time that she struggles (attempts to break free).
The colour of the web will be the same as the colour of the aerosol canister.The persona can attempt to make subtle movements, such as pulling a gun trigger, activating an aerosol, or taking a pharmaceutical.
To this properly she must make a successful difficult DEX (d20) roll, or be unable to move at all.

Procedures such as burning, dissolving or disintegrating the web will have varying chances of success.
The chance of an action being successful can be determined by rolling Sphincter dice, as described in chapter 16, Special Rolls.
Each attempt to free a persona will indicate a chance to entrap the rescuer.
A web aerosol is also known as silly string.