== 3) Antimat Pistol 

// insert table 532

An antimat pistol launches a micro particle of antimatter suspended in a lattice of electrons.
This lattice will shatter when it hits a liquid or solid.
The resulting explosion will instantly annihilate 50 kg of matter.
The explosion releases a blast of heavy particles and super-heated gases that will affect everything within a ten hex radius regardless of cover.
Everything in the ten hex radius will take 25 to 70 (5d10+20) hit points of damage.
A malfunction with this weapon means the electron lattice has shattered within the gun.
This usually means a harmless misfire, but if the ref is in a bad mood the gun will disintegrate itself.

== 4) Antimat Rifle 

// insert table 533

An antimat rifle is the long range cousin of the antimat pistol.
The antimat rifle releases a larger particle of antimatter, and causes a more powerful explosion.
The antimat rifle attack eliminates approximately 200 kilograms of matter.
The resulting blast has a 25 hex radius inflicting 35 to 80 (5d10+30) hit points of damage.
In other respects, the antimat rifle functions the same as an antimat pistol.
More information is listed under gun 3, Antimat pistol.