= Aerosol Gun



== Aerosol Pistol 

Type:	C
Range:	Double (-1000)
Accuracy:	-150
Damage:	As Per Aerosol
Magazine:	Triple Usage
Wate:	0.5kg (Special)
Malfunction:	20
EXPS:	500
Value:	2000 (Special)

An aerosol pistol amplifies some of the abilities of targetable aerosols.
This pistol will double the targetable range, and triple the number of charges of an ordinary aerosol canister.
In no way does this pistol alter area of effect, duration, or damage of an aerosol.
Aerosol canisters cannot be disconnected from the pistol until all charges are extinguished.
If an aerosol that has a range of 10 hexes and an area of effect of 3 hexes were to be inserted into this pistol, the aerosol would then have a range of 20 hexes, the same area of effect, and it could be ejected from the pistol 3 times.

A malfunction indicates a loss of all remaining charges.
There is a slim chance (determined by the ref) of the weapon exploding on malfunction.

== Aerosol Rifle 

Type:	C
Range:	Triple (-1000)
Accuracy:	-50
Damage:	As Per Aerosol
Magazine:	5 Times Usage
Wate:	1.6kg (Special)
Malfunction:	20
EXPS:	500
Value:	8000 (Special)

An aerosol rifle enhances two of the abilities of targetable aerosols.
This rifle will triple the targetable range, and quintuple (five times) the number of charges in an aerosol canister.
In no way can this device alter the area of effect, duration or damage of any aerosol.
Aerosol canisters cannot be disconnected from an aerosol rifle until all charges are deployed.
If an aerosol that has a range of 10 hexes and an area of effect of 3 hexes were to be inserted into this pistol, the aerosol would then have a range of 30 hexes, the same area of effect, and it could be ejected from the rifle 5 times.
A malfunction will indicate a loss of all remaining charges.
There is a slim chance, determined by the ref, that the weapon will explode on a malfunction.