= Pharmaceuticals

The pharmaceuticals described in this chapter are fantastic miracle substances capable of diagnosing, preparing, and administering the proper remedy.
They can do wonders, but they can also have deadly side effects when not used under the most competent of medical supervision.
Pharmaceuticals are found in groups of doses called a prescription.
A prescription may consist of pills, injections or liquids.
A prescription will normally have a negligible mass.
Overuse of a prescription may result in dependence to that specific pharmaceutical type.
Addiction to pharmaceuticals is very rare considering the vicious side effects that will ultimately accompany their use.


// insert drugs.539.png Say no to pharmacologic interventions.

The pharmaceuticals have many parameters , and some guidelines for generating them should be followed.
In the immediately following paragraphs the pharmaceutical attributes are described.
After these paragraphs are the steps to creating a pharmaceutical.
These parameters can be rolled before the pharmaceutical type is determined.

== Duration 

This note describes the length of time that the pharmaceuticals effect will last.
The onset is instantaneous, and the body will return to normal at the end of the duration.
Remember that side effects may have a longer duration than the pharmaceutical's effect.
A Permanent
duration indicates a permanent change in the taker's body.
All other durations are given in normal time ranges.
Those drugs that have a range of times listed for a duration must be rolled each time a dose is applied.

== Doses 

This is the number of doses that will usually be found with the prescription.
A dose represents the number of times the prescription can produce its indicated effect.
This could represent the number of pills, injections, or spoon fulls that the persona has access to in the prescription.
The dosage of a prescription cannot be extended in any way unless a veterinarian has made a specific maneuver.
None of the pharmaceuticals listed here require multiple doses for a single effect.
For instance a disease curing drug need only be taken once to attain the full effect, and not once a day for 2 weeks.

== Purity 

Purity is simply the chance that the substance has no side effects.
Purity can be checked for each dose taken, or one roll can reflect the entire prescription.
Purity is usually equal to the tech level of the pharmaceutical.
A tech level 10 pharmaceutical has a 10% chance of no side effects.
To determine the tech level of any artifact, including pharmaceuticals, refer to http://expgame.com/?page_id=359[Chapter 56: Tech Level].

== EXPS 

EXPS are the experience points granted for identifying the prescription.
The substance's purpose can either be determined by using the veterinarian performance tables, or by imbibing the pharmaceutical (and correctly guessing the effect).
If a prescription has more than one dose EXPS will only be granted once for identifying the nature of the prescription.

== Value 

The value is an indicator of the pharmaceutical's relative worth.
The value is the value of a single dose.
If a prescription has 3 doses then it is worth 3 times the given value.
The value of pharmaceuticals can change according to the market's needs.
Unidentified pharmaceuticals are equally worthless, or valuable depending on requirements.


== Prescription 

// insert table 782

=== 1) Method 

The method of administration  refers to the manner in which each dose is applied, ingested, injected, or in some way installed into the body.
A roll on Table 50.1: Method of Administration__ __will determine how the pharmaceutical is administered into the body.
A completely unhelpful colour can be applied to the prescription.
Pills would sport the colour rolled, and aerosols would be have that colour of case.
For colour use the Colour Bomb!
Table supplied below for your convenience.

// drugneedless.544.png Finger poking.


// insert table 783 /] + [table id=436

=== 2) Metabolism

There are many different persona types in EXP, and to make the pharmaceutical situation a little more interesting we going to consider the metabolisms of the various persona types.
The metabolism indicates which of the persona types that the pharmaceutical was intended for.
The effects of using a pharmaceutical designated for another race are not complex.

// insert table 784

==== Anthro 

If an anthro is imbibing a pharmaceutical meant for her own anthro type the chance of side effect depends entirely on the purity of the pharmaceutical.
If they are imbibing a pharmaceutical meant for a different anthro type the chance of side effect is doubled.
If the imbibe a pharmaceutical meant for an alien or robotic metabolism they will automatically have a side effect and be poisoned.
Robotic pharmaceuticals will only be poisonous to an 

==== Alien 

Pharmaceuticals that are compatible with an alien metabolism can be imbibed by any alien with the standard purity.
Pharmaceuticals not compatible with anthros will only automatically have a side effect when ingested by aliens.
Robotic pharmaceuticals will be poisonous to aliens.


==== Robot 

Robot pharmaceuticals are better described as spectacular motor oils, or bizarre fuels.
Liquid programming
is another label for robotic materials that cause pharmaceutical effects.
For example, a robotic injection would appear more like a pneumatic dagger than a hypodermic needle.
Organic pharmaceuticals have no effect on a robot.


=== 3) Markings 

The only safe--only some are those filled out by the local pharmacist.
Unfortunately the druggists that filled out these prescriptions have not only been dead for thousands of years, but probably spoke a long since deceased language.
Prescription markings are essentially random. Prescription Markings table is made.
This will indicate how useful surviving prescription labelling is.
If the roll indicates none, all labelling has been removed or destroyed.
Mis-labelled
indicates that something other than the original prescription markings are on the labelled container.

// insert table 785

=== 4) Side Effects 

Very rarely can pharmaceuticals be expected to invade the physiology of an organism, and achieve the desired effect, without some form of side effect.
A side effect is an undesirable change in the body's chemistry that arises from taking a pharmaceutical.
Each pharmaceutical type has a purity value.
This is the percent chance of no side effects occurring per dose taken.
A cure with a purity of 18 would have an 18% chance of having no side effect when taken by the prescribed persona type.
The impact of persona type and side effects is described above under http://expgame.com/?page_id=3472-metabolism[2) Metabolism].

A roll on the Side Effect table will determine what side effect the persona will sustain if they have a failure of purity or take a prescription not tuned to their metabolism.
The side effects themselves are not lethal, but their consequences can be.
The ref can roll a new side effect each time one occurs, or have a specific one prepared for that pharmaceutical.

The duration of the side effect is decided by the ref.
Of course, some guidance is given here.
Pharmaceuticals that enact permanent changes in the taker will have side effects that last for 1-10 days.
Those pharmaceuticals with none permanent durations shall have side effects that last for 1-10 minutes.

If the side effects counter the desired effect of the pharmaceutical, this is tough luck.
This could be considered an allergic reaction to the chemicals which renders the pharmaceutical useless.
Proper administration of pharmaceuticals by vets can reduce the chance of side effects.
Side effects are not the end of useful pharmaceuticals.
The personas get a save vs.
intensity 5-30 poison (5d6) in an attempt to throw off the undesired effects.

// insert table 786

== Pharmaceutical Type

include::ROOT:partial$CH50_Table_Pharmaceutical_Type.adoc[]

== 1. Cures 

// insert table 788

A cure is not an inoculation, and therefore does not reduce the chance of future contraction of a disease.
A cure will simply arrest the process of a disease, or poison, but it will not heal damage that has already happened.
Cures restore no damaged attributes, or reduced hit point totals.
Cures stop the affliction in its tracks and remove it from the persona.
Refer to Table 50.6: Cure Type to see what kind of cure the pharmaceutical is.

// insert table 789

== 2. DNA 

// insert table 790

DNA is a pharmaceutical capable of replacing lost limbs or organs, and reactivating non-functioning ones.
A dose of DNA activates the growth centers of remaining cells at the site of missing, or inactive, body parts.
The type of body part replaced can be determined on Table 50.7: DNA Type.
The repair is accelerated, and will be complete in 10 to 100 hours.
The DNA will replace any missing, damaged, or malfunctioning organ or limb, but it will be especially effective at replacing the part rolled on the table.
The repaired, or replaced, limb will resemble that of the metabolism type rolled for the drug.
The organ, or limb will function absolutely normally regardless of persona type, but there will be an obvious cosmetic effect.
For example an avarian may have an ursidae arm, but a perfectly good functioning one though.
A DNA dosage may also activate any previously nonfunctional body part--like a mutated extra ear, or limb.

Any unnecessary dose of DNA, i.e., no missing or damaged parts,  will yield the persona an automatic side effect from the Side Effects Table.
A purity roll will also be required to avoid the outgrowth of a non-functioning limb, or organ.
The type of new growth, and its location are determined by the referee.
For example if a perfectly well humanoid anthro unnecessarily consumed an alien sensory organ DNA pharmaceutical she may find herself with an blind alien eye on her forehead.
If the referee is looking for randomness the alien part can be rolled on http://expgame.com/?page_id=2418-description[Alien Description] and the location on http://expgame.com/?page_id=316[Hit Location].


// insert table 791

== 3. Narcotic 

// insert table 792

Narcotics represent drugs that have been made for illicit recreational use, and those regular pharmaceuticals that have gone sour.
The narcotics are not grouped by any name or class, but by how they affect the psycho motor system of the user.
To determine how the user's mental state is affected roll on Table 50.9: Narcotic Effect.__ __Table 50.8: Effect Duration is used to determine how long the narcotic effect lasts.

The narcotic also reduces several of the persona's attributes.
AWE, DEX, and INT all receive a penalty of 1 to 6 (d6) for the duration of the narcotic effect.
It is up to the referee whether or not a narcotic attribute reduction will kill the persona.
Narcotic overdoses regularly kill humans in our realm.
Persona's will have their MSTR, halved while under the effect of a narcotic.
Knites will avoid any such excursions into the chaos of the mind.

// insert table 793

// insert table 794

== 4. Heal 

// insert table 795

Heals are pharmaceuticals that repair physically damaged tissues.
The results of the healing process are reflected by a change in the persona's hit point total.
Heals never alter the persona's hit point maximum, but will improve the present total.
The underlined dosage is the most frequent amount appearing, and the value refers to the value of a single dose.

A heal may have either of  two functions, restoring hit points, or healing attributes and hit points.
To determine what a heal repairs a roll must be made on Table 50.10: Heal Type__ __and then on Table 50.11:  Hit Points Healed__.__

// insert table 797

*Percent Heal*: Heals that indicate a % hit point total work in the following fashion: they return the persona the given % of their hit point max.
So a persona with a HPS max of 50 using a 40% heal would immediately be raised to 20 hit points.
If the persona has more than 20 hit points when the dose is taken, the heal has no effect.

*HPS Heal*: The other type of heal repairs a preset number of hit points.
A 20 hit point heal would return 20 hit points to a persona regardless of her hit point total.
However, the persona's hit point total can never exceed her hit point max by taking heals.

*Attribute Healing*: Those heals that can repair attributes will repair 1-6 (1d6) points of attribute per dosage.
Attributes cannot exceed their original values by the use of heals.
E.g., a persona who lost 3 points of CHA (15 down to 12) from a recent burn, just happens to inhale a bronchial spray which heals 50% Hps, and CHA.
A d6 roll indicates that 4 points of CHA are to be returned to the user.
So the persona's CHA returns to her previous CHA of 15, not a new CHA of 16.

All heals are worth 100 EXPS.
Those heals that also repair attribute values are worth 100 to 600 times more than the HPS heal value.
So the healing pharmaceutical used in the latest example has a value of 40 000 000 (100 000 for the HPS heal, times 400 for the 4 points of CHA).

// insert table 796

== 5. Inoculation 

// insert table 1065

Inoculations are not cures, and taking an inoculation will only increase one's resistance to future attacks of the inoculated ailment.
A roll on Table 50.12: Inoculation Type will reveal what the pharmaceutical inoculates against.
Multiple inoculations will result in a side effect, and no additional protection.
If a persona is inoculated against paralysis she will double her CON when trying to win a saving throw versus a paralyzing or stunning attack.
So if her CON were 15 she would save as if her CON were 30.


// insert table 799

== 6. Mutation Permanent 

// insert table 798

This bizarre pharmaceutical will give the persona a single mutation from either of the mutation lists.
There is also a chance that the persona will have a skin/coat colour change as a side effect.
The colour deviations are a permanent side effect specific to this pharmaceutical, and appear after the mutant's first night sleep.
Physical mutations will grow in after 1-4 sleeps, and mental mutations will be ready to use immediately.
To make the effects of these chemicals a little more challenging, the player will not know what mutation her persona has until she deduces it, or happens across it accidentally.
Refer to Table 50.12: Mutation Type for the drug's effect

The mental and physical mutations are rolled in their respective chapters.
The persona cannot get only a defect.
While a defect is possible it will always be accompanied by a non-defect mutation.
The colour of the skin or coat colour change will match the colour of the pharmaceutical.

// insert table 800

== 7. Mutation Effect 

// insert table 801

Personas taking a mutation effect pharmaceutical will quickly get some idea that their body and/or thinkspace has changed, and possibly a hint as to what way.
The persona will function identically to a mutant--setting off detectors--for the duration of the effect.
Physical mutations will explode from the mutant's body in minutes, and mental mutations will begin with a tremendous headache.
Due to the limited duration of the mutation effect, the persona should be able to figure out what the mutation is pretty quickly.
The mutation effect cannot be a defect.
The pharmaceutical may even cause a skin/coat colour alteration.
The new colour will last as long as the mutation effect lasts, and matches the colour of the pharmaceutical.

// insert table 802

== 8. Periodic Intumescent 

// insert table 803

Periodic intumescents are also known as boosters.
They increase the value of a persona's attribute for the duration of effect.
Which attribute is increased depends on the roll generated on Table 50.14: Periodic Intumescents.
The attribute is doubled 90% of the time, and tripled the remaining 10% of the time.
These temporary values can easily exceed race restrictions, but cannot exceed the biological maximums.
Note that the effects are carried out on the present value of the attribute.
E.g., HPS total of 20 will be increased to 40 or 60.

Some of the extreme attribute values may allow for special abilities that are otherwise unheard of.
Personas with very high AWEs may be able to sense through materials that would normally block vision, or hearing.
High MSTRs may be able to sense kirlian auras, or develop the odd knite ability.
Spectacular CHAs could mesmerize the general populace with glorious orations.

// insert table 804

== 9. Permanent Intumescent 

// insert table 805

Pharmaceuticals which increase attributes are the most sought after of all the exotic substances in this chapter.
The attribute increaser chemicals have one catch.
The catch is that they only increase the maximum value of the persona's attribute, and she must work very hard to raise her attribute to the increased level.
Permanent intumescents expand the maximum range of the persona's attribute, but the persona must wait for age modifiers, heals, or periodic intumescents to raise the attribute to its new level.
Periodic intumescents, although not permanent, will recede to the attribute's higher level (provided that the attribute has no damage outstanding).

An increased HPS Maximum must wait for pharmaceutical, or natural healing to reach the new hit point total.
If a persona has taken an injection that increases her DEX* *by 2 points she would not immediately enjoy the increased attribute.
If her previous DEX* *were 14 she would not have a 16 DEX* *until she somehow improved her DEX.
She could do this with a periodic intumescent, a heal, through aging or a training program.
If none of these avenues are immediately available the referee can arrange a training program for the persona.
This could be mental exercises, balance practise, or exercise.
Both natural and mutation abilities come into effect automatically.


Permanent intumescents should be so rare that multiple use should not be a problem.
If personas attempt to employ them--from the same prescription--repeatedly, there are dire consequences.
For each additional dose taken there is a cumulative 25% chance that there will be a poison effect, in addition to side effects, and attribute increases.

// insert table 806

== 10. Poison 

// insert table 807

Poisons are pharmaceuticals that have gone completely sour, or are poisonous substances mistaken for pharmaceuticals.
The effects of poison are very, very bad.
Personas can very easily die from the effects of poison.
Poisons can be one of the greatest deterrents for keeping personas from using pharmaceuticals indiscriminately.
Personas expect to get a save vs.
poison, but since this is a drug administered directly into the system no save is awarded.
If a save is to be awarded the intensity of the poison is 6 to 36 (6d6).
The ref, and personas, should remember that when any attribute of a persona is reduced to zero the persona is irrevocably dead (except CHA).
None of the poisons directly kill, but their effects on the system of the persona can be lethal.
All poisons automatically have a side effect as well.


// insert table 808
