= Inatmo Vehicles

A vehicle is essentially any machine designed to help personas get from point A to point B.
Inatmo vehicles operate within the atmosphere of a planet.
Unlike their outer space cousins (exatmo vehicles) they trapped in the gravity well of a planet.
Inatmo vehicles are completely controlled by personas unless accessories indicate otherwise.

Vehicles are randomly generated. 
They are based on the shapes and purposes of the mundane vehicles of our world.
A referee can have intelligent spacefaring Easels in  her campaign.
However it is unlikely the vehicles created in this section will turn out like that.

Prevalence of the vehicles is determined by the milieu of the referee's campaign.
A big city campaign could be polluted with vehicles.
A leather and dust campaign could revolve around a single vehicle.
The vehicle creation system does not lend itself to on-the-spot artifacts.

The vehicle system is designed with anthropomorph personas in mind.
A basic vehicle will almost certainly come with an engine, a body, a braking system, a steering device, and some space for passengers.
Additionally if it makes sense a vehicle should include a windscreens, roof, signal lights, instrument panels, and doors.
Vehicles created for an alien society would reflect the needs of that alien species.
Vehicles created for an robotic society would reflect the needs of that alien species.
EXP makes no accommodation for these differences and the referee must exercise her creative muscle.

.*Vehicle Construction List*
. <<_vehicle_appearance,Vehicle Type>>
.. Cargo 
.. Leisure
.. Passenger
.. Self Powered
.. Passenger Capacity
.. Cargo Capacity
.. Wate
... Size
. <<_vehicle_function,Vehicle Use>>
.. High Performance
.. Industrial
.. Combat
.. Recreational
. <<_speed,Speed>>
. <<_acceleration,Acceleration>>
. <<_locomotion,Locomotion>>
. <<_engine_and_fuel_type,Engine and Fuel>>
. <<_maneuverability,Maneuverability>>
. <<_accessories,Accessories>>
. <<_adaptability, Adaptability>>
. <<_exps,EXPS>>
. <<_value,Value>>

== Vehicle Type 
Vehicle type determines the appearance, shape and size of the vehicle.
Appearance is intentionally based on familiar existing Terran vehicles.
Id does not matter if the vehicle was produced by hand or by an assembly line.
Included with the vehicle type are passenger capacity, cargo capacity, and vehicle wate.
Vehicle type is a framework to start creating on.
Imaginative players, and refs, should not be restricted by the appearance of the vehicle type.

include::ROOT:partial$CH54_Table_Primary_Format.adoc[]

=== Cargo Type

:art: alien_beasts_of_burden.png
:width: 250px
:snark: Low tech cargo van.
:artist: Morey
:date: 1962
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Cargo vehicles are devoted to the transport of things other than passengers.
Cargo vehicles are vans, trucks, and pick ups. 
They have limited passenger capacity and have space for moving stuff.
The passenger portion of this vehicle is secondary to the cargo space.
The passenger cabin may, or may not, have access to the cargo hold.

include::ROOT:partial$CH54_Table_Cargo_Vehicle_Type.adoc[]

=== Leisure Type

:art: flying_naudosaucers.jpg
:width: 250px
:snark: Nice evening for a cruise.
:artist: Morey
:date: 1962
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The leisure vehicle is the most familiar vehicle type. 
Most mundane Terran vehicle ownership is of the leisure vehicle type.
They include minis, sedans, coupes, motorcycles and mini-vans.
Leisure vehicles are designed for commuting, touring, or for parking in front of the house.
They designed primarily for passenger travel, and have little space allotted for cargo.

include::ROOT:partial$CH54_Table_Leisure_Vehicle_Type.adoc[]

=== Passenger Type

:art: passenger_vehicle.png
:width: 250px
:snark: Where toad sir?
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

The passenger vehicles are persona cargo vehicles.
They are designed to move anthros, aliens or robots from one place to another.
They have seating, and some cargo space for passenger belongings.
Typical passenger vehicles are taxis, vans and buses.

include::ROOT:partial$CH54_Table_Passenger_Vehicle_Type.adoc[]

=== Self Powered Type

:art: darth_pogo.png
:width: 250px
:snark: Legalize skate boards.
:artist: Peggy Lynn McIsaac
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

These are engineless modes of transport get's themselves from A to B.
Self powered vehicles employ gears, pulleys and elastics to power the vehicle.
These are not your ordinary self powered vehicles since they can attain tremendous speeds.
Pogo sticks, bicycles, skateboards are typical self powered types of vehicles.

include::ROOT:partial$CH54_Table_Self_Powered_Vehicle_Type.adoc[]

=== Passenger Capacity
Passenger Capacity is the number of seats the vehicle has to safely carry personas.
Passenger type vehicles will have lots of passenger capacity.
Self powered type vehicles will have limited passenger capacity.

:art: non_powered_vehicles_antennae.jpg
:width: 250px
:snark: Self powered solo gondolas.
:artist: Ed Carter
:date: 1950
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Exceeding passenger capacity can have negative effects on vehicle handling and maneuvers.
There are also severe consequences for unrestrained passengers in vehicle collisions.

Seating is based on the shapes of anthro personas.
The equivalent alien size is medium or smaller.
The equivalent robot size is small or smaller.
Size does not guarantee that a persona can be safely restrained by the seating.
The referee needs to decide if the seating is designed for anthros, aliens or robots.
EXP is designed around anthro personas.
So alien and robot seating would be the exception rather than the rule.

=== Cargo Capacity
Cargo capacity is a combination of wate and volume.
Most vehicle types can manage additional wate, but do not have the space for additional junk.
Cargo type vehicles have a set capacity that is measured in tonnes.
Other vehicles have cargo capacities based on the number of passengers. 
Exceeding cargo space should increase DD on the driving performance table.

=== Vehicle Wate
Vehicle wate indicates the vehicle's unloaded wate.
The wate of a vehicle is recorded in kilograms or tonnes.
This can also be called the Gross Vehicle Wate.
Massive accessories may change a vehicle's wate.
Massive accessories, particularly industrial ones, assume that they add 25% to the vehicle wate.

Full cargo or passenger capacities are added to the vehicle when important.
Vehicle wate is important in collisions, terrain, transport, or running over stuff.

==== Size 
When using minis in the tactical combat system the size of the vehicle can become important.
A rough estimate of the vehicle's hex size is one hex per 200 kg of vehicle wate.
Typically these hexes are arranged in a rectangle, but accessories and usage may alter this shape.

== Vehicle Use
Vehicle use determines the accessories and specifications that the vehicle has.
Vehicle type has already been determined and the vehicle use accentuates this.
The vehicle use is more relevant to the vehicle's present state.

The vehicle use is not solely random accessories, but alterations to the entire vehicle.
A passenger vehicle type with a combat vehicle use could be a troop carrier. 
It would have its appearance and structure modified to reflect being a troop carrier.
A leisure vehicle type with a high performance use could be a race car.
It would have its appearance and structure modified to reflect being a race car.
The referee and players will be responsible for creating the finished type and use.

include::ROOT:partial$CH54_Table_Secondary_Vehicle_Use.adoc[]

=== High Performance Use

:art: cool_cat_cool_car.png
:width: 250px
:snark: Cool cat. Cool car.
:artist: Kelly Freas
:date: 1955
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

High performance vehicles are souped-up, chromed out, rubber melting machines.
The vehicles are devoted to speed, acceleration, range, and/or maneuverability.
A leisure type vehicle with high performance use would be the classic muscle car.
A passenger type vehicle with high performance is designed to get personas around fast.

Vehicle acceleration, speed, and maneuverability are described later in this section.
High performance use vehicles get  +10% on acceleration, +20% on speed, and +2 on maneuverability.
High performance use vehicles also get 1-3 rolls on the High Performance Accessories Table.
Accessory effects are cumulative.

include::ROOT:partial$CH54_Table_High_Performance_Bonuses.adoc[]

=== Industrial Use
Industrial use vehicles are designed for specific commercial uses.
The specific use(s) is determined by the Industrial Accessories Table.
The industrial accessories listed in this section are self explanatory.

The accessory effectiveness is determined by the wate of the vehicle.
A shovel mounted on a semi-trailer will move more dirt than a shovel mounted on a skateboard.
The number 25% is a used as a quick assessment of the accessory's capacity.
The accessory will be able to lift, shovel, paint, 25% of the vehicle's wate.
Referee and player discretion must be implemented with Industrial Accessories.

Every industrial use vehicle gets at least one accessory.
Then there is a 50% of getting a second roll, a 25% chance of a third roll and so on.
This continues until the player fails a to get another roll, or has 4 accessories on her vehicle.

include::ROOT:partial$CH54_Table_Industrial_Accessory.adoc[]

==== Weaponization
Inevitably players will want to use industrial accessories as weapons.
There are no detailed attributes for these industrial device.
There are no combat attributes listed for these industrial accessories.

Regardless of how powerful and strong an accessory may be it is not built to be weapon.
The device may have safety features that prevent it from clobbering targets.
The device may suffer extensive damage when being used as a weapon. 
There is no system in place for turning a shovel into a robot crusher.
These discussions usually result in conferring with Sphincter Dice 

=== Combat Use

:art: tank_deflect_armour.png
:width: 250px
:snark: Tanks for the ride.
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

Combat vehicles are built tougher than other vehicles.
They are designed to be shot at, crushed and intentionally abused.
A leisure type vehicle with combat use could be a jeep.

Combat vehicles are combat hardened.
They are harder to hit and harder to damage.
Combat use vehicles have base Armour Rating of 700. 
Combat use vehicles reduce the extent of damage by 50%.
A combat use vehicle that is hit with major damage would reduce it's function by 20% not 40%.

Combat use vehicles get 1-3 rolls on Combat Use Accessory table.
The devices are integrated into the vehicle.
Combat use accessories can define the vehicle as a tank or a jeep or a driving bomb.

include::ROOT:partial$CH54_Table_Military_Accessories.adoc[]

=== Recreational Use
Recreational use vehicles have been made to accommodate persona comfort.
A recreational use vehicle could be a camper, or an full on RV.
A recreational use vehicle gets one Recreational Use Accessory per 20 passenger spots.
Most vehicles get one roll on the table.
A passenger type vehicle that holds 60 passengers with recreational use would get 3 rolls.

include::ROOT:partial$CH54_Table_Recreational_Vehicle_Accessories.adoc[]

== Speed 
Speed refers to the maximum speed that the vehicle can attain.
Speed is rolled on 6d12s, all summed.
This is the vehicle's maximum speed in h/u.
Maximum speed is weather agnostic, unless the referee has built in specific limits.
Minimum speed is anywhere between 0 h/u and the maximum speed.
Reverse speed is 50% of maximum speed.

Maximum speed is no indication of safe driving speed.
All of these values are guidelines subjected to alteration by the referee.
A flying vehicle may not be able to float at 0 h/u in the air.
A water going vessel may not be able to reverse.
An enormous vehicle may have a very slow reverse speed.

=== Vehicle Maximum Speed
.speed = 6d12 h/u
****
If the player rolls all 6s her vehicle could travel 36 hexes each unit.
****

.*For convenience*
* 1 h/u = 1 m/s
* 1 h/u = 3.6 kmh
* 1 h/u = 2.2 mph

== Acceleration 
Acceleration indicates how much faster the vehicle can travel from one unit to the next.
A high acceleration indicates the power of the engine in relation to the wate of the vehicle.
Basically the higher the acceleration the more powerful the engine.
Acceleration generally requires arithmetic.
Acceleration is used for a comparison between vehicles. 

:art: acceleration.png
:width: 250px
:snark: More faster each unit.
:artist: Michael Jackson, mod HM
:date: 1991, 2010
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

For example two vehicle's have the same speed of 50 h/u.
Vehicle Won has an acceleration of 5 h/u per unit.
Vehicle Also has an acceleration of 10 h/u per unit.
In the first unit Vehicle Won can move 5 hexes, and Vehicle Also can move 10 hexes.
The next unit Vehicle Won can move 10 hexes, and Vehicle Also can move 20 hexes.
It is clear who is going to win a race, even though both vehicles have the same speed.

=== Maximum Vehicle Acceleration
.acceleration = (10d20) / 10 in h/u
****
If the player rolls 100 on 10d20 her vehicle could accelerate 10 h/u each unit.
****

== Locomotion 
The locomotion of a vehicle is the external extension of the drive train. 
The locomotion is what acts on the environment to create movement.
The locomotion type determines if the vehicle travels on land, air or water. 
No vehicle is submersible unless specifically hardened for submersion.

There are typical locomotion types like wheels, tracks, and propellers.
EXP has many atypical locomotion types like antigrav, slog bag and chemical slide.
Science fantasy explanations are used to explain how both the typical and atypical systems work.

NOTE: *Self Powered vehicles do not have a locomotion type.*



:art: cargo_vehicle.png
:width: 250px
:snark: Anti-grav and air screws.
:artist: Moller / Format
:date: 1887 (yes 18 87)
:license: CC BY-SA 4.0

include::ROOT:partial$articulate.adoc[]

=== Air Based Locomotion
Air based locomotion indicates the ability to fly supported by gas, most commonly air.
Air based locomotion indicated a vehicle has flight.
An air based locomotion cannot drive on the land or water.
An air capable vehicle may be able to slowly taxi, but cannot fully function on air or water.

Flight is 3 dimensional movement and adds massive complexity to tactical combat.
The referee is allowed to ground any flying locomotion types.
Grounded antigrav, or props have a ceiling of 1 meter off of the ground.
There are many examples of these kinds of vehicles in our mundane Terran world. 

=== Land Based Locomotion
This is the most familiar type of mundane Terran locomotion. 
Land based locomotion vehicles can only drive on solid ground.
It is assumed that the ground also means a prepared terrain like a road.
Land based vehicles can only travel off road if indicated by the locomotion type or an accessory.

=== Water Based Locomotion
Water based locomotion allows the vehicle to travel over liquid, most commonly water.
The mundane Terran form of this travel is a boat.
If the vehicle has water only locomotion it will harbour many boat like qualities. 


=== Locomotion and Speed
The speed of the vehicle helps determine the locomotion type.
For example, a vehicle that can move 30 h/u would roll on the middle column, while one that moves 200 h/u would roll on the rightmost column.
Some vehicles combine locomotion types have an ^*^ indicating a complementary locomotion type.

include::ROOT:partial$CH54_Table_Vehicle_Locomotion.adoc[]

include::ROOT:partial$CH54_Table_Vehicle_Secondary_Locomotion.adoc[]

=== Antigrav
Antigrav is a classic science fiction term for anti-gravity.
The vehicle can travel about as though gravity has no effect upon it.
The vehicle can fly and flit about.
As ideal as antigrav is, it will only function within a gravity well.
The vehicle has no obvious mechanisms that create it's buoyancy in gravity.

This locomotion type is air based and can fly inatmo unless grounded by the referee.

Complementary antigrav only floats the vehicle, while the primary locomotion type moves the vehicle.
For example, a vehicle with jets and antigrav would float by antigrav and maneuver by the jets.
The antigrav jet driven vehicle would look like it is flying by jets, but would float with all jets off.

=== Balloons (1d12)
Balloons offer both movement force and maneuverability to the vehicle.
The balloons appear very dynamic inflating and deflating rapidly to change direction and move the vehicle.
A vehicle will sport 1-12 (1d12) balloons.

When balloons are combined with a complementary locomotion type they only supply buoyancy and primary locomotion type moves the vehicle

Balloons are air based locomotion types. 

=== Chemical slide
The chemical slide allows the vehicle to effortlessly slide along any surface.
This process leaves a quickly evaporating trail not unlike a giant slug.
This comparison does not necessarily imply the vehicle will be slow.

This locomotion type is land and water based. 

A complementary chemical slide is offering a frictionless surface and the primary locomotion propels it. 
For example, a vehicle with jets and chemical slide would stay grounded and be pushed around by jets. 

=== Electromagnetic legs (1d4)
Electromagnetic legs are visible beams of energy the move the vehicle around.
A vehicle will have 1 to 4 electromagnetic legs.
These legs keep the vehicle about a meter off the ground. 
They keep the vehicle level on varying terrain.

This locomotion type is land based. 

=== Jets (1d4+1)
Jets force gases at high speed to generate movement.
A vehicle will have 2 to 5 jets.
The jets create thrust and maneuverability.
Jets are intake-less and do not eject dangerous super-heated propellants.

This locomotion type is air based and can fly inatmo unless grounded by the referee.
Wings are completely cosmetic and this locomotion type flies without wings.

=== Magnetic
A magnetic locomotion unit allows the vehicle to hover above the ground.
The height of the vehicle is fixed at no higher than 1 hex.
Vehicles with magnetic locomotion will often float around long after their destruction.

This locomotion type is land and water based and cannot fly.

=== Pistons (1d10)
Pistons quickly poke up and down keeping the vehicle balanced and moving.
A vehicle has 1 to 10 pistons.
A single piston looks like a vehicle on a pogo stick.
The pistons are immaculately timed and keep the vehicle stable.

This locomotion type is land based. 

=== Pods (4d4)
Pods are articulated mechanical legs.
A vehicle has 4 to 16 pods.
These articulated poles will hop, scuttle or patter the vehicle about.
The ride is not a rough one but from the outside may look chaotic.

This locomotion type is land based. 

=== Propellers (1d6)
Propellers are quiet, safely encased air screws.
The propellers offer thrust and maneuverability to the vehicle. 
There are 1 to 6 propellers per vehicle.
Propellers can function alone or be combined with a complementary locomotion type.

Propellers alone, or combined with antigrav are air based vehicles. 
Propellers combined with a chemical slide would be a land based vehicle.

=== Sails (1d3)
Sails are very sturdy, electro molecular planes that catch air for movement.
Vehicle sails operate perfectly well in raging wind or dead calm.
The sails offer thrust and maneuverability. 
All locomotion types are equivalent.

Sails can be used on land or water or air. 
However the player must pick one of the three options.

=== Skis (1d4+2)
Skis are attached to articulated pods that skate the vehicle over terrain.
There are 3 to 6 (1d4 plus 2) skis.
There is no difference in speed whether the vehicle is trotting uphill or sliding down slopes.

Skis can work on land or water equally well.

Complementary skis function differently depending on what they are combined with.
Complementary skis are attached to struts and not powered legs.
The skis would be the surface contact but jets, sails or propellers would drive the vehicle.
Complementary skis function as well on land as water.

=== Slog bag
A slog bag appears like a fluid filled sack attached to the undercarriage of the vehicle.
The slog bag undulates and contorts itself along the surface the surface the vehicle travelling.
The slog bag moves like a sack of mercury, however it need not contain a liquid.

The slog bag is a land and water based locomotion type and travels equally well on both.

=== Tracks (1d6)
Tracks look like and are nothing more than rubber-coated tank tracks.
Each track is individually controlled and maneuvers by contorting itself.
There are 1 to 6 tracks on a vehicle.

This is a land based locomotion type.

=== Wheels (1d12)
Wheels are independently powered and controlled.
They are solid, puncture proof and can roll across any terrain.
A vehicle has 1 to 12 wheels.

This locomotion type is land based.

Complementary wheels do not offer locomotion force, but steering. 
The primary locomotion type generates the movement forces.

=== Ref's Own Table
Referee can insert campaign related locomotion types as she sees fit.

== Engine and Fuel Type
The engine type powers the locomotion and accessories of the vehicle.
The engine type is entirely a black box located either in the vehicle or distributed amongst the locomotion.
All the personas know is what type of fuel powers the engine.
It is possible that they may not even know that. 

There are typical fuels and atypical fuels. 
Some engines require refitting as opposed to refueling.
Coils get demagnetized, rubber bands wind down and fuel tanks empty.
This is mostly cosmetic and is a same difference to keeping the engine running.

=== Parts
Mechanics often find themselves repairing engines. 
Parts will match if the vehicle type and fuel types match. 
An engine block for a semi-trailer would not be compatible with that of a pick up truck.
The referee would also be allowed to consult the Sphincter Dice.

include::ROOT:partial$CH54_Table_Fuel_Type.adoc[]

== Handling Level 
The handling level of a vehicle is the combination of the elements of maneuverability.
Handling level includes steering sensitivity, brake response, traction, balance, and chassis design

NOTE: *Handling Level was formerly referred to as Maneuverability*

The higher the handling level the better the chance of success with driving maneuvers.
Driving is a unique subset of the performance rolls and is detailed in the driving section.

High performance vehicles adjust their handling level upwards after rolling the handling level

include::ROOT:partial$CH54_Table_Handling_Level.adoc[]

== Accessories
Accessories are a collection of maddening to wonderful additions for to a vehicle.
An accessory can be junk that adds character, or a game changing artifact that defines the vehicle.
All vehicles get one roll on the General Accessory Table.

The player get's one roll on the Accessory Type Table.
Junk Accessories do not count as a roll.
The player stops rolling if she has 3 Junk Accessories.
The player stops rolling if she get's either a Mundane or Artifact Accessory.
There are extra rolls that allow a vehicle to have multiple Mundane or Artifact accessories. 

include::ROOT:partial$CH54_Table_Accessory_Type.adoc[]

include::ROOT:partial$CH54_Table_Junk_Accessories.adoc[]

include::ROOT:partial$CH54_Table_Normal_Vehicle_Accessories.adoc[]

include::ROOT:partial$CH54_Table_Special_Vehicle_Accessories.adoc[]

== Adaptability 
Adaptability is optional.
Adaptability represents how easy the vehicle is to repair and add new parts.
Similar in spirit to the Handling Level in that is adjusts the DD of the mechanic maneuver.
The adaptability is multiplied by 4 and added to the mechanics Maneuver Roll.

Adaptability ranges from +5 (very adaptable) to -5 (very unadaptable).
Adaptability is rolled on using 2d6. 
Where 1d6 is substracted from another 1d6.

=== Calculating Adaptability
.Adaptability = 1d6 - 1d6 (range +5 to -5)
****
Rolling 6 and 4 gives an adaptability of +2, on +8 on the mechanic's maneuver roll.
****

== EXPS 
Vehicles have no EXPS value for most personas.
Their reward is allowing the expedition to get around and therefore get more EXPS in other ways.
A nothing that get's to drive a vehicle will gain 1 full Nothing EXPS Level or can put 4242 EXPS towards her Zero Level Vocation.

== Value 
The base value of a vehicle is 10 000 per tonne. 
Vehicle, type, use and accessories increase the value of the vehicle.

include::ROOT:partial$CH54_Table_Vehicle_Value.adoc[]

