= Hardware

[quote]
____
*Technology is indistinguishable from magic as soon as the manual goes missing.*
____

:art: temple_trouble.png
:width: 350px
:snark: 
:artist: Rogers
:date: 1951
:license: CC BY-SA 4.0
:description: Montage of oil derricks, atom symbol, gun and bow.
include::ROOT:partial$articulate.adoc[]

EXP's headline is "The Game of Technological Chaos."
This title reflects a rule system where one can expect any device to exist alongside any other device.
Is the laser pen mightier than the vibro sword?
Can a low-tech culture devote all its resources to make a time machine?
Can a high-tech culture devote all its resources to make itself feel sad and pathetic?
Add a bit of humour, and these explorations are what EXP is all about.

NOTE: *Technological indicates a mix of unknown devices.*

In our mundane terra's olden daze, there was a game show dedicated to https://en.wikipedia.org/wiki/What_in_the_World[identifying things,window=_blank].
This game show broadcast on a one-way colourless video device called a television.
Hardware in EXP is like a similar to that ancient game show. 
Personas do not know what they are looking at.

More than 70 years later, neither this game show nor the television exists.
A handheld piece of glass with high-resolution full colour interactive text and pictures has replaced the television. 
This evolution of the television took four generations on mundane terra.

The chaos arises from the randomness of the system that generates technological objects in EXP.
The hardware section has many equipment categories, and they are designed for random artifact generation. 
The hardware section also makes a decent reference catalogue for technomagical devices. 

The Technological Object Yield System (TOYS) is where the technological chaos begins.
The TOY System generates random artifacts.
These artifacts can vary from worthless junque to sun hopping starships.
The randomness is the root premise of The Game of Technological Chaos.

== Nomenclature
Calling technological devices artifacts is a twist on the archeological nature of their discovery.
These discovered artifacts represent the detritus of a technologically advanced civilization.
Everything old is new again.
EXP artifacts are usually found by personas while on an expedition.
There is no reason that the expedition could not purchase them from a local junk store, print catalogue or computer store.

TOYS or TOYs:: 
Technological Object Yield System. 
The TOY system is the ruleset for generating random tech.
The TOYS ruleset is the entire Hardware Section.

Toy::
Anything that the TOYS generates is a toy. 
A toy can be powerful or useless.
Most toys are somewhere in between.
An unidentified toy can be called an artifact.
An identified toy is often still called a toy.

Artifact:: 
An unidentified potentially technological device.
An artifact can be powerful or useless.
Most artifacts are somewhere in between.
Useless artifacts can be called mundane equipment.

Startifact::
Start plus artifact.
An artifact that the persona starts the game with.

Mundane Equipment:: 
Mundane equipment is the boring practical stuff of life.
Personas can usually purchase mundane equipment in a local shop.
Sometimes what was once an artifact is demoted to mundane equipment.

== Toy Types
A quick introduction into the types of artifacts that the TOY system can yield. 

include::hardware:partial$toy_department_descriptions.adoc[]

== Support Equipment
Support Equipment is stuff that is needed to run the equipment.
Support Equipment ranges from manuals to ammunition and from batteries to software.
Support Equipment is ineffective on its own but essential to another device.
Jump to xref:software:CH55_Support.adoc[Support Equipment,window=_blank] for more details.

== Tech Level
Tech Level is a numerical measure of how well crafted an artifact is.
The higher the Tech Level (TL), the better the artifact. 
An advanced artifact does not automatically arise from an advanced civilization.
A culture may focus a disproportionate amount of energy on a particular device.

Higher tech level artifacts are more durable, lighter, more efficient, etc.
Tech level can also change the shape and appearance of an artifact.
A flotto laser rifle may look like a stick.
A psionic headband may look like a necklace.
Very high-tech items can appear to function like magical items. 

Low tech level items can be equally confusing to personas. 
A large building may represent a society's best calculator.
Compare a water pump of today from the waterwheel of yesteryear.

Jump to xref:software:CH56_Tech_Level.adoc[Tech Levels,window=_blank] for more details.

include::ROOT:partial$CH56_Table_Assign_Tech_Level.adoc[]

== TOY Record
Artifacts in EXP are like snowflakes.
Each one appears different and functions differently.
If the device was worth generating, it is worth writing down.
Keeping artifact records results in quicker gameplay and fewer 'oops' moments.

.*Example Toy Record*
* *Desc*: dark blue pipe with button and dial setting
* *Toy*: Gun, 16 full-auto lazer rifle (flotto) 
* *Wate*: 4.0kg *EXPS*: 760 *Value:*
* *Tech Level*: 19 (see below Adjustments)
* *Wate*: 0.8kg *EXPS*: 1120 *Value*: 85000 (adjusted to tech level)
* *Support Eq.*.: 3 x Liquid batteries.
* *Info*: Shoot, Flotto; 120h 60; 3-30 MP; +50
* *Owner*: Ester Drone (canine) *Date*: 19/Oct/64 *Serial*: yrul2

If the spirit of the unknown artifact is part of the milieu, the players will only know the description and wate of the equipment. 

// todo make a toy record pdf
// todo does malfunction still apply here?

=== Toy Story
The referee can use post factualization to explain the how and why of an artifact.
An artifact can also be a tool for explaining the culture from which it hails. 
Most artifacts will simply be equipment, but some artifacts will become part of the campaign itself.
Some artifacts have Intelligence and attitude.

