= Aerosols

:art: aerosol_face.png
:width: 450px
:snark: Ding dong. Facial calling.
:artist: Michael Jackson
:date: 1990
:license: CC BY-SA 4.0
:description: Aerosol spray melting away a humanoid face.
include::ROOT:partial$articulate.adoc[]

An aerosol is a cylindrical canister that violently ejects a pressurized, gaseous solution through a push-button valve.
An aerosol ejects all of its contents instantly, leaving a spent container.
Unlike grenades, aerosols lack a history of military use.

.*Aerosol Checklist*
. <<_generate_type, Aerosol Type>>
. <<_trigger,Trigger>>
. <<_number,Number>>
. <<_description, Description>>
. <<_parameters,Parameters>>

== Generate Type

include::hardware:partial$list_of_aerosols.adoc[]

== Aerosol Data

=== Trigger
Aerosols are much simpler to use than grenades.
Pushing the release valve on the top of the canister activates the aerosol.
Where to direct the aerosol is clearly marked.
Aerosol triggers are safe and cannot accidentally activate.

=== Number
Aerosols come in six-packs, not unlike a famous mundane terran beverage.
However, only 1-6 (1d6) aerosols will be in a pack.
For powerful campaign-altering aerosols, one aerosol will suffice.

=== Description
The aerosol appears to be an oversized version of mundane terra's typical gas-powered container.
Each pack of aerosols will have a distinctive canister and xref:software:CH55_Appearances.adoc#_colour_your_whirled[Colour,window=_blank].
Aside from their distinct colouring, aerosols lack labelling and safety information.
To more aggressively modify the toys' description jump to xref:software:CH44_Appearances.adoc[Appearances,window=_blank].


=== Parameters
For details on the special elements of aerosol combat jump to xref:combat:area_attacks.adoc#_aerosols[Aerosol Combat,window=_blank].

==== Range
The range parameter for an aerosol is either 'None' or a hex range.
A range of none indicates the aerosol's epicentre is the aerosol itself, and the area of effect reaches out from the aerosol.
Less lethal aerosols tend to have a range of None.

A range listing in hexes indicates two possibilities. 
The first is that a blob shoots up to the hex range, and the epicentre is the target hex.
Hopefully, the radius of the area of effect does not consume the origin of the aerosol.
The second is that the range indicates a swath effect that sprays outwards from the aerosol.

==== Area of Effect 
The area of effect is a radius in hexes unless the aerosol has a swath attack.

==== Damage 
The damage parameter has a range of hit points and the dice for calculating the damage amount in parentheses. 
If there is no damage parameter listed the weapon likely has some other horrible effect.

==== Wate 
The wate of an unfired aerosol is 2 kgs. 
The wate of a fired aerosol is 200 gms. 
The wate of a spent aerosol is 10% of its charged wate.

==== EXPS 
The persona gets this value for identifying the aerosol. 
The player may identify the aerosol before or after discharge. 

==== Value 
The value of the aerosol in eps.


== Aerosol Catalogue 

=== Antilazer
[horizontal]
Range:: 4h
Area of Effect:: 7h
Damage:: None
Wate:: 2kg
EXPS:: 275
Value:: 1000

The antilazer aerosol will dissipate any lazer that passes through its gaseous field. 
The antilazer cloud dissipates attacks, blinds lazer vision and blocks lazer comms. 
There is no limit to the amount of damage that an antilazer aerosol can dissipate.
Energy attacks like ​fission, fusion, plasma ​are not affected by this aerosol. 
The shimmering cloud will evaporate 1-10 (1d10) minutes after discharge.

=== Attraction
[horizontal]
Range:: None
Area of Effect:: 1 km
Damage:: None
Wate:: 2.0kg
EXPS:: 350
Value:: 100

The attraction aerosol is a potent anti-repellant.
The attraction aerosol generates pheromones, vibrations, chemicals, or sounds that appeal to a particular persona.
The attracted persona will swarm towards the epicentre of the discharge.
The creatures will show up hungry, desperately in love, or plain curious.
How many referee personas approach the expedition depends on the mood of the referee.

This aerosol is also known as a love bomb.

include::hardware:partial$effected_persona_type.adoc[]

=== Blinding
[horizontal]
Range:: 12h
Area of Effect:: 3h
Damage:: None
Wate:: 2 kg
EXPS:: 300
Value:: 50

The blinding aerosol renders organic optical sensors inoperative
Any target with organic optical sensors must win a poison roll or be blinded.
Every three units spent within the cloud will require another poison roll or be blinded.
The blinding poison has an intensity of 2-20 (2d10).
If blinded, the target will remain blind for 0-9 (1d10-1) minutes.
If the duration is less than 1 minute, the duration is 1 to 20 (1d20) units.
The cloud of the aerosol is invisible and will dissipate in 1 to 12 units.
Any target entering the cloud must make a poison roll.

The blinding aerosol is alternatively called tear gas.

=== Catabolic Dismodulator

[horizontal]
Range:: 12h
Area of Effect:: 3h, special
Damage:: 5-60 (5d12), special
Wate:: 2 kg
EXPS:: 300
Value:: 25000

The catabolic dismodulator turns inorganic matter into an opaque, multi-hued cloud of gas.
The effects are devastating to inorganic equipment and especially robots.
Only solid inorganic matter within the target hex is dismodulated.

Inorganic personas and equipment must win a poison roll or suffer destruction by this attack.
The poison intensity is 13 to 28 (10+3d6) poison.
Most equipment has little or no Constitution to combat this attack. 
Organic personas hit directly with a catabolic dismodulator have a 5% chance of dismodulating along with their equipment.
If an organic persona can be dismodulated, they must win a poison roll or die.

The area of effect of the catabolic dismodulator is only the target hex.
The three hex area of effect is from cold damage to targets caught in the shimmering cloud.

=== Demagnetizer

[horizontal]
Range:: 12h
Area of Effect:: 5h
Damage:: None
Wate:: 2kg
EXPS:: 300
Value:: 25

This aerosol is an industrial-strength tape head cleaner.
Temporarily dissolving the weak forces of magnetism creates chaos for devices.
The obvious problems that could arise from this are broad.
Fridge magnets fall of the fridge. 
Monitors will go blank.
Magnetic attachments will detach.
Magnetic levitating legs on vehicles and robots will collapse.
Electronic memories get erased.
This attack has no specific damage, but the result of its attack may result in injury.

Military devices must win a mental attack roll or demagnetize.
The Mind of the attack is 3-18 (3d6).

Magnetized items remain neutralized for 3-18 units.
There is a 1% chance for each unit of duration that the device is damaged.

=== Disintegrator

[horizontal]
Range:: 15h
Area of Effect:: 1h
Damage:: Special
Wate:: 2kg
EXPS:: 300
Value:: 12000

The disintegrator aerosol turns inorganic substances into dust.
Unlike the catabolic dismodulator, the disintegrator aerosol is a more discerning attack.
A disintegrator only affects a specific material type.
Any amount of the target material turns into dust.
If the persona is disintegrating a homogenous stone wall, the effects are straightforward.
However, if the target is a composite of many materials, the effect is less clear.

A technological device may only partially disintegrate due to its composition.
A robot may have alloys, but it is not entirely composed of alloys.
The player attacking makes a  xref:uncombat:sphincter_rolls.adoc[Sphincter Roll,window=_blank] to determine the aerosol's effect.
If the player wins the sphincter roll the artifact suffers a xref:combat:equipment_damage.adoc#_extent[Equipment Damage,window=_blank] to determine the extent of damage.

A malfunction of this weapon disintegrates the aerosol into dust.

include::hardware:partial$effected_material.adoc[]

=== Exploding

[horizontal]
Range:: None
Area of Effect:: 1h
Damage:: 5-60 (5d12)
Wate:: 2kg
EXPS:: 4200
Value:: 42

This sadistic device explodes like a fragmentation grenade when it is triggered.
All targets in the one hex area of effect take the damage listed.
The referee should note that it is very impolite to laugh when a persona detonates an exploding aerosol.
This artifact would be considered a trap and should not count as a toy roll at startup.

=== Foam

[horizontal]
Range:: None
Area of Effect:: 8h by 2h
Damage:: None
Wate:: 2kg
EXPS:: 100
Value:: 250

The foam aerosol creates a pad of creamy foam 16 hexes in diameter and two hexes deep.
For the first minute, personas can easily move through the foam.
By the end of the second minute, the foam is starting to thicken, and personas move at half speed.
Three minutes after being discharged, the foam will be so viscous that personas can only move at quarter speed.
The pad solidifies after four minutes, and anything still in the foam is completely trapped.

At no time is breathing hampered by the foam.
Anything entombed by the foam pad will starve to death before anything else.
The foam is not much more substantial than mundane terran polystyrene.
However, any persona stuck in the foam pad is immobilized.
Only those personas on the outermost edges can attempt to break free.

The colour of the foam will be the same as on the outside of the aerosol canister.
Once solid, the foam is structurally sound and well insulated.
This aerosol has synonyms such as the insulator and the homemaker.

=== Freezing

[horizontal]
Range:: 9h
Area of Effect:: 8h
Damage:: 5-60 (5d1)
Wate:: 2kg
EXPS:: 300
Value:: 1000

The freezing aerosol subjects all targets in its area of effect (8 hexes) to an enthalpy attack.
The supercooled temperatures coat everything with ice and snow.
The freezing aerosol has a % chance, equal to the damage inflicted, of entrapping large or smaller, sized targets in ice.
This attack also freezes switches in place, triggers in the firing position, pins in grenades, pant zippers closed, etc.

=== Gas

[horizontal]
Range:: 7h
Area of Effect:: 6h
Damage:: Special
Wate:: 2kg
EXPS:: 250
Value:: 900

The gas aerosol fills the area of effect with a pall of transparent but noticeable gas.
The cloud of gas will affect all organic creatures within it.
Personas must win a poison or be affected by the toxin.
Personas must repeat the poison roll for every three units within the area of effect.
The intensity of the poison is 2-16 (2d8).
The cloud will dissipate in 4 to 16 units.
Roll on the below table to determine the effect of the gas.

include::hardware:partial$gas_effect_type.adoc[]

=== Invisibility

[horizontal]
Range:: None
Area of Effect:: 0h
Damage:: None
Wate:: 2kg
EXPS:: 300
Value:: 250000

The invisibility aerosol prevents matter from deflecting or reflecting visible light.
This aerosol has a limited area of effect and only works on its target hex.
Everything in that area will become undetectable to sensors that use reflected light.

The aerosol does an effective job of making the targets invisible.
The disguise is only on the visible spectrum.
Personas still occupy space, exude odours and make noise. 
Sonar, infravision, ultravision, and other such sensors are not affected.

There are many challenges to being invisible. 
Eye-hand coordination becomes none existent. 
Equipment dropped remains invisible.

The effects of this aerosol last 1-4  (1d4) days.

=== Matter Detector

[horizontal]
Range:: 12h
Area of Effect:: 12h
Damage:: None
Wate:: 2kg
EXPS:: 100
Value:: 400

The matter detector aerosol brings the material world into clear focus.
The aerosol covers any solid matter with detection chemicals.
The detection coating emits subtle amounts of heat, light, radiation, and vibration.
This chemical exposes matter to the most common sensors (eyes, infravision, sonar).
Invisible objects start to glow, and architectural deceptions (hidden doors) reveal themselves.
If something is not solid, it does not take on the detecting glow.
The matter detector aerosol is a good hologram detector too.

Attack rolls on lit targets receive a bonus of +65.
Ambushes are ten times easier to detect.
Hiding while lit is 10 DDs more difficult.
The duration of detection continues for 1 to 4 minutes.

This aerosol is also called a marker aerosol or a targeting aerosol.

=== Mistor

[horizontal]
Range:: None
Area of Effect:: 25h
Damage:: None
Wate:: 2kg
EXPS:: 100
Value:: 400

The mistor aerosol disables all sensory modalities ineffective.
Sensors include eyes, sonar, infravision, touch, smell, etc.
Personas within the cloud are not blinded, but there is a barrier between all five senses.
Inside the cloud, vision grey, yelling is quiet, and touch is numb.
Personas have no sense of direction, and combatants may bump into each other. 
Attack rolls are random swings and shots.
Movement is random unless the persona has some form of heightened directional sense.
The suspension will remain cohesive for 16 days.

=== Molecular Diffusion

[horizontal]
Range:: 10h
Area of Effect:: 7h
Damage:: 12-96 (12d8)
Wate:: 2kg
EXPS:: 300
Value:: 2500

This aerosol delivers microscopic tears to anything in the area of effect. 
This micro rending of molecular connections causes severe damage. 
Personas and equipment do not appear to have any apparent damage or injury.
Only a detailed inspection of equipment, or bodies, will reveal the microscopic tears. 

=== Napalm

[horizontal]
Range:: 8h
Area of Effect:: 8h x 2h
Damage:: 6-60 (6d10)
Wate:: 2kg
EXPS:: 300
Value:: 1900

The napalm aerosol blasts a swath of flaming gas and gel when triggered.
This aerosol is not an artifact you'd want to point backwards mistakenly.
The blazing area of effect sears everything for 6 to 60 (6d10) hit points of damage.
Everything that takes the initial heat damage immolates and continues to be damaged.
Targets that have immolated will burn for an additional 2 to 8 units.
Burning targets take an additional 4-24 (4d6) hit points of damage per unit.
Personas cannot extinguish the especially adherent flammable chemicals with routine measures.
Most targets will continue to burn for the entire immolation period.

Other than the flaming targets, the napalm swath extinguishes itself immediately.

=== Paint

[horizontal]
Range:: 4h
Area of Effect:: 4h
Damage:: None
Wate:: 2kg
EXPS:: 50
Value:: 42

This aerosol can paint an entire room with one explosive button push.
This time-saving aerosol violently paints everything in its area of effect.
The indiscriminate nature of the paint aerosol allows it to be weaponized.
If caught in the area of effect, personas must win a poison roll or be blinded.
The blinding affects all visual sensors and lasts 1-20 (1d20) units.
The intensity of the poison 1-12 (1d12).
The player may use her persona's DEX or CON for this poison roll.

The paint colour matches the aerosol canister colour.
To get a simple or zany colour jump to xref:software:CH55_Appearances.adoc#_colour_your_whirled[Colour,window=_blank].

This aerosol is also called RBG or Color Your Whirled.

=== Pharm

[horizontal]
Range:: 12h
Area of Effect:: 1h
Damage:: None
Wate:: 2kg
EXPS:: Double pharma
Value:: Triple pharma

The pharma aerosol delivers long-range dosing to groups of patients.
This mass dispenser is suitable for most plagues, military infestations, or Woodstock-like celebrations.
Take a little trip over to xref:hardware:CH50_Pharmaceuticals.adoc#_pharmaceutical_type[pharmaceuticals,window=_blank] 

All targets in the area of effect must *lose* a poison roll to be affected.
The player must lose the poison to be affected by a beneficial pharmaceutical.
The intensity of the poison (pharmaceutical) is 2 to 20.

This intensity is reduced by one for every target in the area of effect.
The more potential users, the milder the dose.
It is possible to make this aerosol completely ineffective by having too many targets in the area of effect.
The pharma cloud has no duration and dissipates instantly.

=== Poison  

[horizontal]
Range:: 12h
Area of Effect:: 3h x 12h
Damage:: Death
Wate:: 2kg
EXPS:: 300
Value:: 700

The poison aerosol ejects a cloud is a mix of nerve gas and pulmonary desiccant.
The lethal combination is very selective.
The lethal attack does not linger and only affects those personas indicated.
Any persona affected by this attack must win a poison roll or die.
The intensity of the poison is 2-24 (2d12).

While the lethal toxin's effect has no duration, there is a lingering residue.
This residue violently repulses susceptible personas. 
Affected personas cannot approach the swath area unless they win another poison roll.
The repellent effect lasts for 1-4 (1d4) days.

The lethal poison aerosol is also called Raid, or nerve gas.

include::hardware:partial$effected_persona_type.adoc[]

=== Repellent  

[horizontal]
Range:: None
Area of Effect:: 3h
Damage:: None
Wate:: 2kg
EXPS:: 300
Value:: 50

The repellent aerosol employs irritating pheromones, smells, vibrations and emotions.
These irritations drive the affected personas out of the area of effect.
There is no roll vs poison. 
The three hex area of effect or anything coated by the repellent is unapproachable.
Flora and fauna aliens will bolt far beyond the area of effect.
Intelligent creatures may approach the epicentre if they win an intensity 13-28 (3d6+10) poison roll.
The repellent effect lasts 1-6 (1d6) days.

This aerosol is also called Oph, Repecks, or Protector.

include::hardware:partial$effected_persona_type.adoc[]

=== Siren  

[horizontal]
Range:: None
Area of Effect:: 500h
Damage:: 2-12 (2d6)
Wate:: 2kg
EXPS:: 100
Value:: 75

This ear-splitting siren will wail for 2-8 minutes.
The initial blast of sound inflicts 2-12 (2d6) hit points of damage.
There is also a 10% chance per hit point of damage of going deaf.
Each minute spent in the area of effect will inflict another 2-12 (2d6) hit points of damage. 
Once a persona becomes deaf or unconscious, the siren inflicts no further damage.
Organic personas will restore hearing their hearing after 1-10 hours.

Sonar detectors or mutations double the damage on the initial blast.
When used outdoors, delicate flora and fauna can die from shock. 
The epicentre may attract deaf, confused and angry local fauna.

This aerosol can also be called a whistler or screecher.

=== Smoke  

[horizontal]
Range:: None
Area of Effect:: 12h
Damage:: None
Wate:: 2kg
EXPS:: 42
Value:: 100

This smoke aerosol will instantly discharge a 24 hex diameter sphere of dense smoke.
The smoke will obscure the vision of any visual sensors caught within its field.
Smoke inflicts a -230 per hex attack roll penalty for ranged attacks.
The smoke is so dense that its removal requires a bulldozer.
The cloud will disperse in 1 to 8 weeks.
The colour of the smoke will match the colour of the aerosol canister.
To generate the colour jump to xref:software:CH55_Appearances.adoc#_colour_your_whirled[Colour,window=_blank].

=== Web  

[horizontal]
Range:: 8h
Area of Effect:: 8h
Damage:: None
Wate:: 2kg
EXPS:: 300
Value:: 1000

The web aerosol splatters the area of effect with a super adhesive goo.
The webby mess will trap anything caught in the area of effect until it dissipates.
The web maintains its sticky grip for  2-16 minutes.
Any persona that saunters into the goo will instantly become stuck.

A trapped persona can attempt to make subtle movements without risk.
Small actions like pulling a trigger, firing an aerosol, or taking a pharmaceutical are possible.
Struggling to break free is a different situation.
There is a chance that the web will block the persona's face and risk suffocation.
There is a 1% chance of suffocation whenever a trapped persona struggles.

Any attempt to free a persona is a chance to entrap the rescuer.
Procedures such as burning, dissolving or disintegrating will have varying success.
Consult the xref:uncombat:sphincter_rolls.adoc[Sphincter Roll,window=_blank] to determine if a particular attempt to destroy the web works. 

The colour of the web will be the same as the colour of the aerosol canister.
Jump to xref:software:CH55_Appearances.adoc#_colour_your_whirled[Colour,window=_blank] to generate a colour of string. 

The web aerosol is also called Killy String or Super Goo. 

