= Appearance

Randomly generating an artifact's appearance is an entirely optional and useful exercise.
Generating an artifact appearance is fun and helpful for the campaign.
Unidentified equipment is called artifacts, and giving them a distinct appearance helps keep track of them.
If the players know what a device is, its description is purely cosmetic.
When the players don't know what a device is, it's description offers a fun way to record it on her persona record.
For example, a red pistol with glowing tubes is more dramatic and fun than pistol #2f421. 

The referee can use appearance to fuel the milieu of her campaign. 
The appearance generated for artifacts can influence the culture from which they arose.
An imperial city may have lazer pistols that sport roman flourishes and dark red alloys. 
Artifact appearances need not be utterly random, and the referee's milieu can inform how they appear.

NOTE: An ideal description is a short sentence that differentiates the artifact from everything else.

.*Appearance Checklist*
. <<_shape,Shape>>
. <<_style,Style>>
. <<_descriptors,Descriptors>>
. <<_colour,Colour>>

== Shape
The general shape depends on the hardware, and it's tech level.
Tech level ten devices tend to appear as familiar mundane terran devices.
For example, a tech level ten rifle will look like a rifle. 
The rifle may have unique colours, style and descriptors, but it will still look like a rifle.
A tech level twenty rifle may not look like a rifle at all. 
A tech level two rifle may not look like a rifle either.
So for familiar devices, the shape remains the same. 
The artifact shape may be random for aberrant tech level artifacts. 

=== Basic
The volume of the device will fit into this shape.
Feel free to contort the shape.

include::robots:partial$basic_shapes.adoc[]

=== Contortion
This table manipulates the basic shape to reflect the infinity that is commercial design.

include::robots:partial$basic_shape_distortions.adoc[]

=== Adornments
These are fun and aggravating descriptors to distract the players. 

include::hardware:partial$strange_adornments.adoc[]

== Style
Artifact style calls upon references from mundane terra to help describe a device.
Styles are a useful tool because they allow the players to use their imagination and quickly identify an artifact.
The Aztec accented blue suitcase offers a description and a distinct identification.
The styling does not affect the tech level of the artifact.
For example, a TL10 lazer pistol with Ancient Greek design principles is not technology.

include::hardware:partial$appearance_stylings.adoc[]

== Descriptors
Descriptors reflect the cleanliness, age and usage of the device.
Descriptors have no impact on device performance or value.
For example, a persona could clean yup her dirty radiation detector.
A destroyed looking black detector box is perfectly functional.

=== Cleanliness
Cleanliness is a description and does not reflect the artifact's performance or value.
High tech level artifacts may have self cleaning properties that make them appear very clean.

include::hardware:partial$appearance_cleanliness.adoc[]

=== Age
Age is a description and does not reflect the artifact's performance or value.
Age appearance also does not reflect the actual age of an artifact. 
High tech level artifacts may have self cleaning properties that make them appear brand new.

include::hardware:partial$appearance_age.adoc[]

=== Usage
Usage is a description and does not reflect the artifact's performance or value.

include::hardware:partial$appearance_usage.adoc[]

== Colour
Colour has the most impact on the appearance of the artifact.
Artifacts can have any colour: a red and blue rifle, a lime green detector, or an orange striped aerosol.

=== Colour Your Whirled
Add colour. 
Use 1d12 for snap colours.
Roll 1d100 to go zany.
Further tables are optional

include::ROOT:partial$add_colour_to_your_world.adoc[]
