= Bombs

:art: bombs_dropping.png
:width: 250px
:snark: Peace from above.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Bombs falling from bomb bay doors.
include::ROOT:partial$articulate.adoc[]

Bombs are a subsection of grenades.
Bombs are nothing more than great big grenades.
They have a greater effect, inflict more damage, and have longer durations than the grenades or aerosols that the bomb is modelling.
Grenade and aerosol special effects increase in lethality as well.
Clouds, fires, radioactivity, or ice fields will last ten times longer.
The intensities of poisons are amplified by ten as well.
The intensity of a bomb attack cannot exceed 25.

.*Bombs are very deadly.*
====
Misuse of bombs, which is usually guaranteed, can melt an entire expedition in a flash.
====

.*Bomb Checklist*
. <<_generate_type, Bomb Type>>
. <<_creator_template,Bomb Template>>
. <<_detonator,Detonator>>
. <<_number,Number>>
. <<_description, Description>>
. <<_parameters,Parameters>>

== Generate Type

include::hardware:partial$list_of_bombs.adoc[]

== Bomb Data

===  Creator Template
The is the core template used to convert an aerosol or grenade into a bomb. 

[horizontal]
Range:: Not applicable
Area of Effect:: times 20
Damage:: times 10
Wate:: times 25
EXPS:: No change
Value:: times 50

=== Detonator
A bomb's detonator is the nitty-gritty of the device.
Unlike grenades and aerosols, bomb detonators are *NOT* designed with persona safety in mind.
The bombs have radio detonators, fuses, or other long-range triggering devices that allow for user safety.
Once the detonator is activated, the bomb will explode, spreading death all about itself.
Fooling with a bomb's detonator could very quickly annihilate an entire expedition.
There is a 75% chance that a bomb's detonator is separate from the bomb itself.
Safety first.

:art: bomb_short_fuse.png
:width: 250px
:snark: Worst nuke fuse ever.
:artist: StudioStoks
:date: 2015
:license: Copyright StudioStoks 2015 
:description: Humanoid hand holding a spherical black bomb with lit fuse.
include::ROOT:partial$articulate.adoc[]

=== Number
Bombs come in the loneliest number, one.

=== Description
Bombs are military devices that tend to lack branding and colour. 
It is very fun to disguise a bomb and make it appear un-bomb like. 
Each bomb has a basic shape, like a grenade has a basic shape. 
If flashy colours, appendages and strange shapes are your jam jump to xref:hardware:appearance.adoc[Appearances,window=_blank].  

include::hardware:partial$explosive_shapes.adoc[]

:art: mechanic_garbage_bomb.png
:width: 250px
:snark: Some people hate recycling.
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Humanoid affixing a timer to a garbage can. 
include::ROOT:partial$articulate.adoc[]

=== Parameters

==== Range 
Bombs cannot be thrown and do not have a range.

==== Area of Effect 
The area of effect of bombs is almost always a radius in hexes.
The cover granted to a bomb attack must be much more substantial than that needed to impede other areas of effect attacks.
In the case of a bomb, only a military bunker may be able to protect the target.
Bombs are deadly.
The goal of a bomb is to destroy large areas effectively and economically.

==== Damage 
The damage parameter has a range of hit points and the dice for calculating the damage amount in parentheses. 
If there is no damage parameter listed, the weapon likely has some other horrible effect.

Any damage that the base weapon inflicts is multiplied by 10.
This multiplier raises even the most trivial area of effect weapon damage to killer proportions.
If the referee feels that a non-lethal base weapon has been made too deadly by the change in damage, she may feel free to alter it.

==== Wate 
A bomb will have a wate 25 times greater than its base artifact type.
The wate is in kgs.

==== EXPS 
Bombs are worth the same number of EXPS of the grenade or aerosol that they imitate.

==== Value 
The value of a bomb is 50 times that of its base artifact type.
The value is in eps.


== Bomb Catalogue

=== Air Raid Siren

[horizontal]
Base Weapon:: xref:hardware:aerosols.adoc#_siren[Siren Aerosol,window=_blank]
Area of Effect:: 500h
Damage:: 1-20 (1d20)
Wate:: 2kg
EXPS:: 100
Value:: 3750

This ear-splitting siren will wail for 2-8 minutes.
The initial blast of sound inflicts 1-20 (1d20) hit points of damage.
Each minute spent in the area of effect will inflict another 1-20 (1d20) hit points of damage. 
Once a persona becomes deaf or unconscious, the siren inflicts no further damage.

This attack will deafen all audio systems for 1 to 10 days.
Deafness includes organic ears and inorganic microphones.
There is a 1% chance per day of deafness that the hearing loss becomes permanent.
There is no saving roll against deafness from the Air Raid Siren.

=== Black Out Bomb 

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_energy_drain_grenade[Energy Drain Grenade,window=_blank]
Area of Effect:: 60h, special
Damage:: Special
Wate:: 12kg
EXPS:: 275
Value:: 75000

The blackout bomb will drain all batteries within 200 hexes.
The bomb uses the stolen energy for a killing attack with a 60 hex range.
The damage of the killing attack depends on the amount of energy around to drain.
If there is a power plant nearby, the bomb will be ferocious.
If there are only batteries around, the bomb will merely be lethal.

This bomb would deliver 5-200 (50d4) hits points of damage in a civic area.
Within 200h of a power plant, detonation would do 20-800 (200d4) hit points of damage.
A middling power source like a robot would be somewhere in between.
Draining the power sources does not destroy them.
They are only damaged if they are in the explosion range.

=== Bomb 

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_fragmentation_grenade[Fragmentation Grenade,window=_blank]
Area of Effect:: 20h
Damage:: 50-500 (50d10)
Wate:: 25kg
EXPS:: 125
Value:: 2000

This bomb is the standard drop from the plane, hide in a car type bomb.
They are bringing peace and liberty to innocent civilians everywhere.

=== Bug Bomb 

[horizontal]
Base Weapon:: xref:hardware:aerosols.adoc#_repellent[Repellent Aerosol,window=_blank]
Area of Effect:: 60h
Damage:: None
Wate:: 50kg
EXPS:: 300
Value:: 2500

The bug bomb is a super-sized repellent and is the pacifist's version of the toxin bomb.
Targets repelled by the bomb must save versus intensity 25 poison.
A failed saving roll indicates that the persona will irrationally run, fly or hop away.
If the persona saves versus the repellent, they still must leave the area of effect.
Any recursion into the repellent area of effect indicates another save is required.
The residue will work repel targets for 1-6 (1d6) weeks.

include::hardware:partial$effected_persona_type.adoc[]

=== Cover Bomb 

[horizontal]
Base Weapon:: xref:hardware:aerosols.adoc#_mistor[Mistor Aerosol,window=_blank]
Area of Effect:: 500h
Damage:: None
Wate:: 70kg
EXPS:: 100
Value:: 2000

The cover bomb disables all sensory modalities ineffective.
Sensors include eyes, sonar, infravision, touch, smell, etc.
Personas within the cloud are not blinded, but there is a barrier between all five senses.
Inside the cloud, vision grey, yelling is quiet, and touch is numb.
Personas have no sense of direction, and combatants may bump into each other. 
Attack rolls are random swings and shots.
Movement is random unless the persona has some form of heightened directional sense.
The suspension will remain cohesive for 10-160 (1d6 x 10) days.
Getting lost in the one-kilometre diameter sensory deprivation tank is guaranteed.

=== Cremator 

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_napalm_grenade[Napalm Grenade,window=_blank]
Area of Effect:: 40h x 160h
Damage:: 60-600 (60d10)
Wate:: 39kg
EXPS:: 300
Value:: 50000

When discharged, the bomb launches itself into the air and sprays flaming adhesive gelatin along its path.
Additional burning damage will usually be irrelevant to all but the freshest combat robot.
The path will burn for 20 to 80 units after the attack, inflicting 20 to 240  (20d12) HPS in burning damage each unit.

=== Diffusion Bomb

[horizontal]
Base Weapon:: xref:hardware:aerosols.adoc#_molecular_diffusion[Molecular Diffusion Aerosol,window=_blank]
Area of Effect:: 140h
Damage:: 120-960 (12d8 x 10)
Wate:: 100kg
EXPS:: 300
Value:: 25000

This bomb delivers microscopic tears to anything in the area of effect. 
This micro rending of molecular connections causes severe damage. 
Personas and equipment do not appear to have any apparent damage or injury.
Only a detailed inspection of equipment, or bodies, will reveal the microscopic tears. 

=== Dissolver 

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_corrosive_grenade[Corrosive Grenade,window=_blank]
Area of Effect:: 60h
Damage:: 50-400 (50d8)
Wate:: 25kg
EXPS:: 200
Value:: 15000

All targets in the area of effect take the initial damage of 50-400 on detonation.
Inorganic targets continue to take 20-200 (20d10) hit points per unit in the area of effect.
The dome of dissolving lasts 1-3 minutes. 
The dissolver is for clearing out mobs of inorganic (robot) targets.

=== Diversionizer 

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_pyrotechnic_grenade[Pyrotechnic Grenade,window=_blank]
Area of Effect:: 100h
Damage:: None
Wate:: 10kg
EXPS:: 100
Value:: 8750

The diversionizer is a shock and awe weapon.
The bomb can be composed of smoke, sonic, flash or any combination.
While it may not be directly lethal, its effects often result in fatalities.

include::hardware:partial$pyrotechnic_components.adoc[]

Smoke:: 
The diversionizer's smoke attack fills the area of effect with very dense smoke.
The smoke will last for 1-10 (1d10) hours.
For a fancy smoke colour, jump to the xref:hardware:appearance.adoc#_colour_your_whirled[Colour your whirled,window=_blank].

Flash:: 
The diversionizer's flash bomb will blind any target that has optical sensors.
The sensors (eyes, cameras) will remain inoperative for 1 to 10 hours.
There is a saving roll versus intensity 3-24 (3d8) poison.

Sonic:: 
The diversionizer's sonic boom delivers a painful eardrum splitting howl on discharge.
The attack deafens any audio receptors in the area of effect.
Total deafness lasts 1 to 10 hours, followed by days of impaired audio.
There is no saving throw for the diversionizer's sonic attack.

=== Emperor

[horizontal]
Base Weapon:: xref:hardware:aerosols.adoc#_demagnetizer[Demagnetizer Aerosol,window=_blank]
Area of Effect:: 100h
Damage:: None
Wate:: 55kg
EXPS:: 300
Value:: 1250

The emperor delivers an electromagnetic wave that incapacitates electronic devices.
Only military hardware, specifically EMC or EMP hardened, can avoid shut down.
Equipment with such hardening gets to roll versus intensity 4 to 24 (4d6) radiation.
Robotic personas also get to roll versus intensity 4 to 24 (4d6) radiation.
Equipment will be inoperative for 1 hour per level of intensity.
There is also a 1% chance per level of intensity of permanent 
xref:combat:equipment_damage.adoc#_extent[damage,window=_blank] 

The Emporer is also called an EMP bomb.

=== Foam Bomb 

[horizontal]
Base Weapon:: xref:hardware:aerosols.adoc#_foam[Foam Aerosol,window=_blank]
Area of Effect:: 160h
Damage:: None
Wate:: 75kg
EXPS:: 100
Value:: 1237

The foam bomb instantly covers its area of effect with a rapidly hardening blob of foam.
The foam pad is ten h deep.
The foam hardens in 20 units. 
The bomb will permanently trap anything still within the foam after 20 units.
The foam is thick and slows movement by 1/2. 

Once cured, the foam is easily cut away.
However, trapped personas are entirely helpless.
At no time are personas at risk of suffocation. 
A more likely death is dehydration and starvation.

=== Grand Slam 

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_big_bertha_grenade[Big Bertha,window=_blank]
Area of Effect:: 160h
Damage:: 120-1440 (12d12 x 10)
Wate:: 50kg 
EXPS:: 300
Value:: 50000

The Grand Slam is a concussion bomb.
Aside from doing massive damage, the grand slam topples targets.

.*Grand Slam Effect*
* 160h range 12d12 damage
* 240h range stun
* 320h range topple

These effects are cumulative.
Stun is versus intensity 25.
Topple is versus intensity 25.

=== Gravitas 

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_gravruptor_grenade[Gravruptor Grenade,window=_blank]
Area of Effect:: 250h
Damage:: Special
Wate:: 50kg
EXPS:: 250
Value:: 300000

The gravitas generates 1-12 random gravities of anomalous attraction.
The effect will either smash targets into the ground, throw them high into the air, or fling them off into space.
The gravitas produces an instantaneous burst of random acceleration.
Newtonian physics conveniently need not apply.
Objects greater than 100 tonnes in wate are not affected by this grenade's attack.

.*Up*
25% of the time, the gravitas reverses gravity by 1-12 (1d12) gravities.
Reversing gravity accelerates everything in the opposite direction to the present gravity.
The general effect is that things go flying into the air.
All items fly one hex into the air per anomalous gravity.
This acceleration inflicts 1 to 12 (1d12) hit points of damage per gravity of acceleration.
Hitting the ground inflicts an additional 1-6 (1d6) hit points per gravity.
Colliding with an immobile object along the path of the toss will also inflict 1-6 (1d6) hit points per gravity.

.*Down*
The remaining 75% of the time, the gravitas will add 1-12 (1d12) g to the local terrain.
Increasing gravity causes personas to crash to the ground and vehicles to grind into the dirt.
This pressing problem will also inflict damage to all targets in the area of effect.
This damage is 1 to 12 (1d12) hit points in damage per extra gravity.
E.g., three gravities would smash targets into the ground for 3-36 (3d12) hit points of damage.

.*All Around*
This weapon is a ZOG (zero gravity) combat weapon.
The gravruptor flings enemy combatants off into space.
All targets accelerate away from the epicentre at 1-12 (1d12) gravities.
This acceleration inflicts 1 to 12 (1d12) hit points of damage per gravity of acceleration.
The targets are also flying away at one h/u for every 2 points of damage.
Consider a gravitas that generated five gravities on detonation
The referee generates 24 HPS of damage using 5d12.
Each target subtracts 24 HPS from their HPS Total and is flying away at
12 h/u.

=== Jumping Jack Blast

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_multiple_explosive_grenade[Multiple Explosive Grenade,window=_blank]
Area of Effect:: Special
Damage:: Special
Wate:: 45kg
EXPS:: 250
Value:: 25000

The jumping jack blast will detonate multiple times with unpredictable effects.
There will be a 1 to 10 (1d10) unit pause between explosions.
The new epicentre will be 20 to 120 (2d6 x 10) hexes away from the last one.

The jumping jack blast is the "exploding cigars" of mass destruction.
This bomb initially explodes like any other bomb, but similarities end there.
After the first explosion, the bomb flies into the air, only to land and explode again.
The number of detonations, area of effect and damage is determined each time. 

The successive explosions will occur 1-10 (1d10) units apart.
The new epicentre will be 20 to 120 (2d6 x 10) hexes away from the last one.
The easiest way to determine is to make a random facet roll.

:art: Figure_grenade_miss_direction_d12.png
:width: 350px
:snark: Roll to see where it lands (1d12).
:artist: HM
:date: 2010
:license: CC BY-SA 4.0
:description: Diagram showing grenade miss direction on hexagon sheet.
include::ROOT:partial$articulate.adoc[]

include::hardware:partial$jumping_jack_pattern.adoc[]

=== Junk Yard 

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_magnetic_disruptor_grenade[Magnetic Disruptor Grenade,window=_blank]
Area of Effect:: 150h
Damage:: Special
Wate:: 37kg
EXPS:: 300
Value:: 112500

The junkyard bomb resembles an implosive super magnet. 
When detonated, this bomb attracts loose items towards its epicentre.
The disruptor will attract anything inorganic: metals, alloys, plastic, wood, etc.
Armour gets ripped off of personas.
Tools tear from utility belts.
Weapons fly from the paws of personas.
Unless the terrain is intentionally completely barren, there will always be stuff to attract.
Personas have no chance to keep anything in their hands once the gravitas bomb attracts it.

Everything inorganic within 150h will fly towards the epicentre.
These high-speed projectiles smash into all targets within the area of effect.
The targets closest to the detonation endure more hurtling stuff.
The damage increases the closer the target is to the epicentre of the grenade detonation.
A persona 150h out from the epicentre would take 1d4 of damage.
A persona at the epicentre would take 150d4.

In zero gravity, the bomb will attach to the nearest object within range.
If there is no reference object, the junkyard bomb will create a satellite of junk.

=== Land Scraper

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_energy_grenade[Energy Grenade,window=_blank]
Area of Effect:: 150h x 150h x 10h
Damage:: 12-480 (12d4 x 10)
Wate:: 25kg
EXPS:: 300
Value:: 250000

Sends a lazer sheet parallel to the ground, travelling with the contours of the terrain, damaging all targets along the way.
This bomb is also called a trench clearer.

=== Lazer Cover 

[horizontal]
Base Weapon:: xref:hardware:aerosols.adoc#_anti_lazer[Anti Lazer Aerosol,window=_blank]
Area of Effect:: 70h
Damage:: None
Wate:: 50kg
EXPS:: 275
Value:: 50000

The lazer cover bomb dissipates any lazer bolts entering its gaseous field. 
The antilazer cloud causes lazers to flare out into harmless glowing balls. 
The cloud does not obstruct vision.
The lazer cover bomb does not affect other energy attacks like ​fission, fusion, or plasma.
There is no limit to the amount of damage that a lazer cover bomb can dissipate.
The shimmering cloud evaporates 1-10 hours after detonation.

This bomb is also called the peacemaker.

=== Nerve Bomb 

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_gas_grenade[Gas Grenade,window=_blank]
Area of Effect:: 260h
Damage:: Varies 
Wate:: 25kg
EXPS:: 275 
Value:: 22500

The nerve bomb discharges a dense mist of poisons.
The nerve agents are both contact and respiratory poisons.
All organic targets must roll vs poison attack or suffer the described effect.
The gas's intensity will vary from 4-24 (4d6).

The cloud of gas will remain and be poisonous for one day per point of intensity.
Prevailing winds may affect the duration and intensity of the gas cloud.

include::hardware:partial$gas_effect_type.adoc[]

=== Neutron Bomb 

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_radiation_grenade[Radiation Grenade,window=_blank]
Area of Effect:: 240h
Damage:: 30-180 (30d6)
Wate:: 55kg
EXPS:: 200
Value:: 25000

This hater of all things organic does not damage structures or robots.
A neutron bomb bathes everything in the area of effect with destructive radiation.
Only those organics hardened to radiation can avoid the initial wave of damage.
Anything that survives the initial attack then must roll versus intensity 25 radiation.

The area of effect remains hot for 25 years, dropping one level of radiation intensity per year.
The site will remain radioactively anomalous forever.
What mad alien race would invent such a sick and twisted device?

=== Nuclear Device 

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_fusion_grenade[Fusion Grenade,window=_blank]
Area of Effect:: 200h
Damage:: 100-1200 (10d12 x 10)
Wate:: 42kg
EXPS:: 300
Value:: 10000

This 'device' is the favourite mundane terran tool for preserving peace through assured immolation.
What mad alien race would invent such a sick and twisted weapon?

.*Nuclear Device Areas of Effect*
* 200h tiny and small sized personas disintegrate
* 200h medium, large, and gigantic personas take 100-1200 (10d12 x 10) hit points
* 300h immolation 
* 400h blinding flash
* 600h radiation attack

The effects of a nuclear device are cumulative.
Consider a persona that is within 200 hexes taking 600 HPS of damage.
First, she subtracts 600 HPS from HPS Total (ha ha ha).
She then catches fire, is blinded and takes a 25 intensity radiation attack.

.*Immolation*
Any flammable object within 300 hexes of the epicentre catches fire.
The immolation includes personas as well as equipment.
Anything ignited by the bomb will burn until extinguished.

.*Blinding*
Any personas within 400 hexes have a chance of being blinded.
The chance of being blinded is 1/2% per point of damage.
This attack affects both organic and inorganic personas and devices.
Vision restores spontaneously in 1-10 (1d10) days.

.*Radiation*
Any target within 600 hexes is subject to a lethal radiation attack.
The intensity of the attack is 25.

.*Residual Radiation*
For effect, the ref can make the 200 hex area of effect a lingering radiation zone.
The radiation intensity decreases from 25 by one point per month.
The device creates a permanent radiation anomaly for detectors and canines.

=== Paint Bomb 

[horizontal]
Base Weapon:: xref:hardware:aerosols.adoc#_paint[Paint Aerosol,window=_blank]
Area of Effect:: 80h
Damage:: None
Wate:: 50kg
EXPS:: 50
Value:: 2250

This bomb colours everything within range to match the same colour as the bomb's casing.
A paint bomb could paint everything within range in stripes or even plaid.
Personas caught in the area of effect will be temporarily blinded for 1 minute.
Unclothed organic personas must save vs intensity 1-6 (1d6) damaging poison. 
To determine the paint colour and pattern, jump to the xref:hardware:appearance.adoc#_colour_your_whirled[Colour your whirled,window=_blank].


=== Polarizer

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_cryoblast_grenade[Cryoblast Grenade,window=_blank]
Area of Effect:: 160h
Damage:: 30-300 (30d10)
Wate:: 25kg
EXPS:: 300
Value:: 25000

There is a 1% chance per hit point of damage of trapping the target in an ice mausoleum.

=== Robot Bomb

[horizontal]
Base Weapon:: xref:hardware:aerosols.adoc#_catabolic_dismodulator[Catabolic Dismodulator Aerosol,window=_blank]
Area of Effect:: 20h, special
Damage:: 50 to 600 (50d6)
Wate:: 42kg
EXPS:: 300
Value:: 2250000

The robot bomb turns inorganic matter into an opaque, iridescent cloud of freezing gas.
The attack dismodulates any equipment, vehicles, armour, computers or robots (including persona robots) within the area of effect.
A persona robot gets a  roll versus intensity 13 to 28 (10+3d6) poison or disappears.

Everything within 60h of detonation will take damage from the freezing gas. 
These targets are mostly organic personas because dismodulation destroyed everything else.
The freezing gas cloud inflicts 50 to 600 (50d6) hit points of damage.
If an organic persona is in the detonation hex of this weapon, they too can disintegrate.
An organic persona suffering a direct hit has a 42% chance of disappearing along with their equipment.
An organic persona gets a  roll versus intensity 13 to 28 (10+3d6) poison.

=== Sky Breaker 

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_skylighter_grenade[Skylighter Grenade,window=_blank]
Area of Effect:: 800h x 600h
Damage:: 40-400 (40d10)
Wate:: 70kg
EXPS:: 300
Value:: 275000

The sky breaker combines a massive serving of destruction with shock and awe.
The initial detonation fires straight up, apparently doing nothing.
Then 20 to 60 units later, the area of effect is hailed with shards of iridescent glowing ice.
This bomb depends on complex meteorological mechanisms and does not work underwater, in zero gravity or a vacuum.

=== Smog Machine 

[horizontal]
Base Weapon:: xref:hardware:aerosols.adoc#_smoke[Smoke Aerosol,window=_blank]
Area of Effect:: 240h
Damage:: None
Wate:: 50kg
EXPS:: 50
Value:: 5000

The smog machine creates a gigantic immobile pall of a particular colour.
The cloud will disperse over 10 to 80 (1d8 x 10) weeks.
The dense smog requires excavation equipment for removal.
If the range penalties are in play, the smog counts as opaque.
The colour of the smog will match the colour of the casing of the bomb.
To determine the smog colour jump to the xref:hardware:appearance.adoc#_colour_your_whirled[Colour your whirled,window=_blank].

=== Space Modulator

[horizontal]
Base Weapon:: xref:hardware:grenades.adoc#_molecular_disruptor[Molecular Disruptor Grenade,window=_blank]
Area of Effect:: Special
Damage:: Special
Wate:: 42kg
EXPS:: 300
Value:: 500000

A space modulator is a temperamental disintegration bomb.
When discharged, this bomb converts solid matter into a warm, seething cloud of iridescent gas.
The problem is that neither the user nor the bomb has any idea what is going to happen.
The table below determines the amount of disruption.

include::hardware:partial$space_modulator_effect.adoc[]

=== Toxin Bomb 

[horizontal]
Base Weapon:: xref:hardware:aerosols.adoc#_poison[Poison Aerosol,window=_blank]
Area of Effect:: 240h
Damage:: Death
Wate:: 50kg
EXPS:: 300
Value:: 35000

The toxin bomb cloud is a mix of nerve gas and pulmonary desiccant.
The lethal combination is very selective.
The lethal attack does not linger and only affects those personas indicated.
Any persona affected by this attack must win a poison roll or die.
The intensity of the poison is 25

While the lethal toxin's effect has no duration, there is a lingering residue.
This residue violently repulses susceptible personas. 
Affected personas cannot approach the swath area unless they win another poison roll.
The repellant effect will last for 1-3 (1d3) weeks.

include::hardware:partial$effected_persona_type.adoc[]

=== Tracker Bomb 

[horizontal]
Base Weapon:: xref:hardware:aerosols.adoc#_matter_detector[Matter Detector Aerosol,window=_blank]
Area of Effect:: 120h
Damage:: None
Wate:: 49kg
EXPS:: 300
Value:: 2000000

The tracker bomb coats all matter with chemicals that emit heat, vibrations, aromas, light and radiation.
The effect is immediate exposing all hidden objects within the area of effect.
The bomb will expose potential ambush, invisible or camouflaged targets within the area of effect.

=== World Wide Web 

[horizontal]
Base Weapon:: xref:hardware:aerosols.adoc#_web[Web Aerosol,window=_blank]
Area of Effect:: 160h x 20h
Damage:: None
Wate:: 50kg
EXPS:: 300
Value:: 50000

The worldwide web bomb splatters the area of effect with a super adhesive goo.
The webby mess will trap anything caught in the area of effect until it dissipates.
The web maintains its sticky grip for 20-160 (2d8 x 10) minutes.
Any persona that strolls into the goo will instantly become stuck.

A trapped persona can attempt to make subtle movements without risk.
Small actions like pulling a trigger, firing an aerosol, or taking a pharma are possible.
Struggling to break free is very risky.
There is a chance that the web will block the persona's face and risk suffocation.
There is a 1% chance of suffocation whenever a trapped persona struggles.

Any attempt to free a persona is a chance to entrap the rescuer.
Procedures such as burning, dissolving or disintegrating will have varying success.
Consult the xref:uncombat:sphincter_rolls.adoc[Sphincter Roll,window=_blank] to determine if a particular attempt to destroy the web works. 

The colour of the web will be the same as the colour of the bomb casing.





