= Grenades

A grenade is any hand, claw, or paw thrown area of effect weapon.
Grenades are remarkable for their ease of use and even more remarkable for their deadliness.
The grenade is particularly unintelligent and damages expedition members as indiscriminately as opponents.
Grenades are imprecise and still manage to impact all targets within their area of effect.

:art: hand_grenade.png
:width: 450px
:snark: Grenade with hand
:artist: Andrew Brechin
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of gnarly humanoid hand holding an old school grenade.

include::ROOT:partial$articulate.adoc[]

.Grenade Checklist
. <<_grenade_type, Grenade Type>>
. <<_trigger,Trigger>>
. <<_number,Number>>
. <<_description, Description>>
. <<_grenade_parameters,Grenade Parameters>>

== Grenade Type

include::ROOT:partial$CH45_Table_Grenades.adoc[]

== Grenade Types

=== Big Bertha Grenade 

[horizontal]
Range:: STR
Area of Effect:: 8h
Damage:: 12-144 (12d12)
Wate:: 2kg
EXPS:: 300
Value:: 1000

The big bertha is a massive concussion grenade.
Aside from inflicting massive damage, big bertha stuns and topples targets.

.*Big Bertha Effect*
* 8h range 12d12 damage
* 12h range stun
* 16h range topple

These effects are cumulative.
A target within eight hexes takes damage, gets stunned and gets toppled.
To avoid being stunned, the player must win a xref:roll_playing_system:CH04_Anthros_HPS.adoc#_damage_system_shock[Damage System Shock,window=_blank] roll (anthros only).
To avoid being toppled, the player must win a dexterity xref:roll_playing_system:CH16_Special_Rolls_Attributes.adoc[Attribute Roll,window=_blank].

The name big bertha has its roots in mundane terran war history https://en.wikipedia.org/wiki/Big_Bertha_(howitzer)[Big Bertha].

=== Chemical Explosive Grenade

[horizontal]
Range:: STR
Area of Effect:: 4h
Damage:: 8-64 (8d8)
Wate:: 0.75kg
EXPS:: 100
Value:: 200

A chemical explosive grenade is a more powerful version of the typical fragmentation grenade.
The chemical explosive is the big sister of the Fragmentation grenade and the little sister of the Big Bertha.

=== Corrosive Grenade

[horizontal]
Range:: STR
Area of Effect:: 3h
Damage:: 5-40 (5d8)
Wate:: 1kg
EXPS:: 200
Value:: 300

The corrosive grenade bathes the area of effect with acids, alkalis, or non-neutralizing combinations of both.
The corrosive grenade's contents are highly volatile but neutralize themselves on organic surfaces.
This grenade is selectively more destructive to inorganic materials and robot personas.
Organic targets suffer damage from the initial grenade explosion.

After the initial explosion, the residue will continue to eat away at inorganic materials.
Metals, plastic, rubber, etc., continue to take damage until washed clean.
Items such as armour, weapons, or robots will take an additional 2-20 hit points of damage for each of the continuing 1-8 units of reaction.
E.g., an unwashed robot could take an additional 2-20 HPS for four units after the initial blast.
Corrosive grenades are also known as acid baths and Drainoh bombs.

=== Cryoblast Grenade

[horizontal]
Range:: STR
Area of Effect:: 8h
Damage:: 3-30 (3d10)
Wate:: 1kg
EXPS:: 300
Value:: 500

The cryoblast grenade freezes everything in its area of effect to a blast of extreme cold.
The grenade can freeze things solid and can trap personas in ice.
Medium or smaller, sized targets have a % chance, equal to the damage inflicted, of being trapped in the ice.
So a medium-sized beasty that took 19 points of damage has a 19% chance of being frozen immobile.
The cryoblast grenade can also freeze swords in scabbards, render buttons frozen, jam weapons, etc.
The cryoblast is also known as a cryofrag, a berg bomb, or a rinkmaker.

=== Energy Drain Grenade

[horizontal]
Range:: STR
Area of Effect:: Special
Damage:: Special
Wate:: 0.5kg
EXPS:: 275
Value:: 3000

An energy drain grenade will suck the life out of nearby potential energy stores (batteries) and self-destruct.
Any batteries within a ten hex radius will be instantly devoid of charge.
The grenade will shower a smaller three hex area of effect with its exploding fragments.
This explosion will inflict 1d4 hit points of damage for every battery drained.
An unlucky target has 16 batteries within the area of effect.
The grenade explodes in 0 to 3 units--inflicting 16d4 of damage to all within three hexes.

The energy drain grenade only works on discrete batteries storing potential energy.
Continuous battery sources like broadcast or psionic batteries are immune.
The energy drain grenade does not affect robots, powered armour, or vehicle power plants.

The energy drain grenade is also known as an Amp-ire grenade or a Never-ready.

=== Energy Grenade

[horizontal]
Range:: STR
Area of Effect:: 15h x 15h x 1h
Damage:: 12-48 (12d4)
Wate:: 1kg
EXPS:: 300
Value:: 5000

The energy grenade emits a controlled lazer explosion of the given volume (15h x 15h x 1h).
Regardless of the terrain in which the grenade, the detonation always occupies the given volume.
The grenade's blast area will race along corridors, through open doors, around corners, and down escalators.
Using this weapon in unfamiliar terrain could have its effects hurtling directly back at the user.
The energy grenade is also known as an anti-trench grenade or a mouser.

=== Exploding Pin Grenade

[horizontal]
Range:: STR
Area of Effect:: 4h
Damage:: 1-6 (1d6) per pin 
Wate:: 1.25kg
EXPS:: 150
Value:: 650

The exploding pin grenade is a sadistic version of a micro grenade launcher.
When an EPG goes off, it showers the four hex area of effect with tiny pins.
These tiny pins will stick into the hardest of alloys (AR less than 1000).
Whenever a pin hits, it will immediately explode, inflicting the 1d6 damage described above.
The number of pins that hit a target depends on the target's size.
The larger the target, the more pins inflict damage.

include::ROOT:partial$CH45_Table_Pin_Amount.adoc[]

=== Fragmentation Grenade

[horizontal]
Range:: STR
Area of Effect:: 1h
Damage:: 5-50 (5d10)
Wate:: 0.85kg
EXPS:: 125
Value:: 75

The fragmentation grenade is your run-of-the-mill shrapnel grenade.
These are commonly called frags or grenades.

=== Fusion Grenade

[horizontal]
Range:: STR
Area of Effect:: 10h
Damage:: 10-120 (10d12)
Wate:: 2.5kg
EXPS:: 300
Value:: 4000

A fusion grenade delivers a micronuclear explosion.
The explosion includes a host of other nasty effects beyond damage.

.*Fusion Grenade Areas of Effect*
* 10h 10d12 damage
* 15h immolation chance 
* 20h blinding flash
* 30h radiation attack

.*Immolation*
Any flammable object within 15 hexes of the epicentre has a chance of immolating.
The immolation chance includes personas and equipment.
The chance of immolation is equal to 1% per point of damage.
Anything ignited by the grenade will burn until extinguished.

.*Blinding*
Any personas within 20 hexes have a chance of being blinded.
The chance of being blinded is 1/2% per point of damage.
This attack affects both organic and inorganic personas and devices.
Video sensors will restore vision in 1-10 (1d10) minutes.

.*Radiation*
Any target within 30 hexes is subject to a lethal radiation attack.
The intensity of the attack is equal to 1/10 of the damage.

The effects of a fusion grenade are cumulative and lethal.
A persona that is within ten hexes taking 60 HPS of damage.
First, she subtracts 60 HPS from HPS Total.
Then she has a 60% chance of catching fire and a 30% chance of being blinded.
Finally, she must make a roll versus intensity six lethal radiation.

.*Residual Radiation*
For effect, the ref can make the ten hex radius of effect become a lingering radiation zone.
The radiation intensity is 1/10 of the blast damage.
The radiation zone's intensity level will decrease by one point per hour, day, or week, depending on how dirty the grenade was.

The reader should have noticed that this is not a close combat weapon.
More observant readers have noticed that a persona cannot throw a fusion grenade safely out of range.

Fusion grenades are also known as micro-nukes, CQ bombs, and tactical nukes.

:art: stormy_storm_trooper_gas.png
:width: 450px
:snark: It has been a gas gentlemen
:artist: Rob Miller
:date: 1950 
:license: CC BY-SA 4.0
:description: Drawing of shadowy humanoid wearing gas mask entering room full of collapsed humanoids. 

include::ROOT:partial$articulate.adoc[]

=== Gas Grenade

[horizontal]
Range:: STR
Area of Effect:: 13h
Damage:: Special
Wate:: 0.9kg    
EXPS:: 275
Value:: 250

The gas grenade discharges a dense mist of poisons.
The nerve agents are both contact and respiratory poisons.
All organic targets must roll vs poison attack or suffer the described effect.
The cloud of gas will dissipate in 1-8 units.
Prevailing winds may affect the duration and intensity of the gas cloud.
The gas's intensity will vary from 4-24 (4d6).
This value is generated once for the entire cloud.

include::ROOT:partial$CH44_Table_Gas_Type.adoc[]

=== Gravruptor Grenade

[horizontal]
Range:: STR
Area of Effect:: 25h
Damage:: Special
Wate:: 2kg
EXPS:: 300
Value:: 6000

The gravruptor grenade generates 1-6 random gravities of anomalous attraction.
The effect will either smash targets into the ground, throw them high into the air, or fling them off into space.
The gravruptor grenade produces an instantaneous burst of random acceleration.
Newtonian physics conveniently need not apply.
Objects greater than 2 tonnes in wate are not affected by this grenade's attack.

.*Up*
25% of the time, the gravruptor grenades reverses gravity by 1-6 (1d6) gravities.
Reversing gravity accelerates everything in the opposite direction to the present gravity.
The general effect is that things go flying into the air.
All items fly one hex in the air per anomalous gravity.
There is no damage from flying into the air or accelerating back down to the ground.
However, the deceleration of hitting the ground inflicts 1-6 (1d6) hit points per gravity.
Colliding with an immobile object along the path of the toss will also inflict 1-6 (1d6) hit points per gravity.

.*Down*
The remaining 75% of the time, the gravruptor grenade will add 1-6 g to the local terrain.
Increasing gravity causes personas to crash to the ground and vehicles to grind into the dirt.
This pressing problem will also inflict damage to all targets in the area of effect.
This damage is 1 to 12 (1d12) hit points in damage per extra gravity.
E.g., three gravities would smash targets into the ground for 3-36 (3d12) hit points of damage.

.*All Around*
This weapon is a ZOG (zero gravity) combat weapon.
The gravruptor flings enemy combatants off into space.
All targets accelerate away from the epicentre at 1-6 (1d6) gravities.
This acceleration inflicts 1 to 6 (1d6) hit points of damage per gravity of acceleration.
The targets are also flying away at one h/u for every 2 points of damage.
Consider a gravruptor grenade that generated five gravities on detonation
The referee generates 16 HPS of damage using 5d6.
Each target subtracts 16 HPS from their HPS Total and is flying away at
eight h/u.

The gravruptor grenade is also known as a downer or a jump bomb.

=== Magnetic Disruptor Grenade

[horizontal]
Range:: STR
Area of Effect:: 12h
Damage:: Special
Wate:: 1.5kg
EXPS:: 300
Value:: 4500

The magnetic disruptor grenade resembles an implosive super magnet. 
When detonated, this grenade attracts loose items towards its epicentre.
The disruptor will attract anything inorganic: metals, alloys, plastic, wood, etc.
Armour may get ripped off of personas.
Tools may tear from utility belts.
Weapons may fly from the paws of personas.
Unless the terrain is intentionally completely barren, there will always be stuff to attract.

These high-speed projectiles smash into all targets within the area of effect.
The targets closest to the detonation endure more hurtling stuff.
The damage increases the closer the target is to the epicentre of the grenade detonation.
A persona 12h out from the target hex takes 1d4 hit points of damage.
A persona in the target hex takes 12d4hit points of damage.

A Strength attribute roll is required if the referee feels something could fly out of a persona's grip.
The closer to the epicentre, the harder it is to hang onto stuff.
The attribute challenge is versus 24 at the epicentre and two at the periphery (12 hexes).

=== Mini Grenade

[horizontal]
Range:: 1/2 STR
Area of Effect:: attack roll
Damage:: special
Wate:: 0.1kg
EXPS:: 170
Value:: 1000

Mini grenades are so small and light that they don't throw very far.
The player must win an attack roll to damage a target using a mini grenade.
A miss with a mini grenade explodes loudly and harmlessly.
The target's size determines its Defence Rating, and bigger targets are easier to hit.
The target does not use its regular combat Defence Rating and must use the target size AR.
The target's Defence Rating should decrease, which follows the spirit of grenades being area of effect attacks.

include::ROOT:partial$CH45_Table_Size_Armour_Rating.adoc[]

Mini grenade users may wish to throw a handful of these micro explosives at their target.
The persona can throw up to three mini grenades at once.
If the persona does not have a grenades skill, there is an attack roll penalty.
Three grenades have attack roll penalties of -100, -200 and -300.
Two grenades have attack roll penalties of -100 and -200.
A single mini grenade attack has no penalties.

Mini grenades are also known as pea grenades or pill grenades.
High-tech level mini grenades can become extremely small.

include::ROOT:partial$CH44_Table_Mini_Grenades.adoc[]

Explosive Mini Grenades::
Each grenade that hits inflicts 3-18 (3d6) hit points of damage.
There is no area of effect. 
Only the target is damaged. 

Mini Gas Grenades::
Mini gas grenades do no damage unless the poison type does.
The intensity of the gas attack is from 3-18 (3d6).
There is no area of effect.
Only the target is affected. 
To determine the gas type jump to <<_gas_grenade,Gas Grenade>>.

Mini Pyrotechnic Grenades::
Mini pyrotechnic grenades are harmless but highly distracting.
There is no area of effect.
Only the target is affected. 
To determine the pyrotechnic type jump to <<_pyrotechnic_grenade, Pyrotechnic Grenade>>.

=== Molecular Disruptor Grenade

[horizontal]
Range:: STR
Area of Effect:: Special
Damage:: 8-64 (8d8)
Wate:: 1.7kg
EXPS:: 300
Value:: 10000

A molecular disruptor is a temperamental disintegration grenade.
When discharged, this grenade converts solid matter into a warm, seething cloud.
The problem is that neither the thrower nor the grenade has any idea what is going to happen.
The Extent of Disruption Table determines the amount of disruption.

include::ROOT:partial$CH45_Table_Disruption_Event.adoc[]

.*Damage*
Targets in this area of effect take 8-64 (8d8) hit points of damage. 
Damage comes from slivers of disruption that burst from the grenade.
These slivers punch microscopic holes through anything in the damage area of effect.

.*Disruption*
The disruption area of effect utterly destroys any target within it. 
Any matter within this area of effect transforms into a warm homogenous gas.
There is no explosion, no noise, just a giant cloud of effervescent warm gas.
The effect of getting disrupted is devastating and final.
All personas, equipment, terrain, and good ideas disappear.

The molecular disruption grenade is also known as a disintegration grenade.

=== Multiple Explosive Grenade

[horizontal]
Range:: STR
Area of Effect:: Special
Damage:: Special
Wate:: 3kg
EXPS:: 250
Value:: 1000

The multiple explosive grenades are the "exploding cigars" of lethal combat.
This grenade initially explodes like any other grenade, but similarities end there.
After the first explosion, the grenade flies into the air, only to land and explode again.
The number of detonations, area of effect and damage is determined each time. 

The successive explosions will occur 0 to 3 units apart.
The location of the explosion is 0-5 (1d6-1) hexes in a random direction. 
The easiest way to determine is to make a random facet roll.

:art: Figure_grenade_miss_direction_d12.png
:width: 350px
:snark: Roll to see where it lands (1d12).
:artist: HM
:date: 2010
:license: CC BY-SA 4.0
:description: Diagram showing grenade miss direction on hexagon sheet.

include::ROOT:partial$articulate.adoc[]

These grenades are dangerous to the expedition for obvious reasons.
Unless identified, a multiple explosive grenade is indistinguishable from a regular lethal grenade.
If used indoors, the grenade will explode, each unit bouncing around the room.

Multiple explosive grenades are also known as jumping jacks.

include::ROOT:partial$CH45_Table_Multiple_Explosions.adoc[]

=== Napalm Grenade

[horizontal]
Range:: STR
Area of Effect:: 2h x 8h
Damage:: 6-60 (6d10)
Wate:: 1.75kg
EXPS:: 300
Value:: 2000

The napalm grenade covers an area with an adhesive flaming goo.
The napalm grenade is unique in that it has a swath area of effect instead of a spherical area of effect.
The grenade launches itself into the air for an eight hex trip raining adhesive flammables all along its course.
Usually, this grenade will launch itself in the same direction that the persona threw it.
If the thrower is unskilled in grenade combat and rolls less than 200 on her attack roll, the napalm grenade will launch itself in a random direction.

Anything caught in this blazing area of effect will take 6-60 (6d10) hit points of damage and immediately immolate.
Immolation lasts for 2-8 (2d4) units, inflicting  2-24 (2d12) hit points of damage every unit.
The two hex by eight hex patch of flaming death will burn itself out in 1 to 10 minutes.
Referees should also be prepared to consider the effects of smoke inhalation if used indoors.

Napalm grenades are also labelled phosphorous grenades and Smoky the Fear bombs.

=== Pin Grenade

[horizontal]
Range:: 1/4 STR
Area of Effect:: 1h
Damage:: 1-10(1d10) per pin
Wate:: 0.5kg
EXPS:: 150
Value:: 500

The pin grenade is the needler of area of effect attacks.
The pin grenade pierces everything in 1 hex radius of effect with explosive pins.
The initial detonation is relatively quiet. 
The size of the target determines how many pins stick.

include::ROOT:partial$CH45_Table_Pin_Amount.adoc[]

Exploding Pin Grenade::
There is an 80% chance that the pin grenade will be an exploding pin grenade.
Each pin explodes for 1-10 (1d10) hit points of damage.
So a Large target could take up to 12-120 (12d10) hit points of damage.

Poison Pin Grenade::
There is a 20% chance that a pin grenade will deliver toxin instead of exploding.
The intensity of the chemical will vary from 3 to 18.
The persona must make a saving roll even if the pin contains a  beneficial pharmaceutical.

include::ROOT:partial$CH45_Table_Pin_Effect.adoc[]

The pin grenade is also known as a porcupin(e), or inoculator grenade.

=== Pyrotechnic Grenade

[horizontal]
Range:: STR
Area of Effect:: 5h
Damage:: None
Wate:: 0.35kg
EXPS:: 100
Value:: 175

Pyrotechnic grenades are smoke, sonic, and flash weapons.
The pyrotechnic grenades appear in military actions or violent magic shows.
Pyro grenades can be devoted to one attack type or a mix of all three. 
Targets must win a saving roll for each different type of pyro attack. 

include::ROOT:partial$CH45_Table_Pyro_Combo.adoc[]

Smoke:: 
A smoke grenade fills the area of effect with very dense smoke.
There is no saving roll versus smoke. 
The smoke will dissipate in 1 to 10 minutes.
For a fancy smoke colour jump to the <<_grenade_colour,Colour Table>>.

Flash:: 
Flash grenades will temporarily blind any target that has optical sensors.
The sensors (eyes, cameras) will remain inoperative for 1 to 10 units.
There is a saving throw versus intensity 2 to 16 (2d8) poison.

Sonic:: 
Sonic grenades deliver a painful eardrum numbing howl on discharge.
The attack deafens any audio receptors in the area of effect.
Total deafness lasts 1 to 10 minutes, followed by days of tinnitus.
There is a saving throw versus intensity 2 to 16 (2d8) poison.

=== Radiation Grenade

[horizontal]
Range:: STR
Area of Effect:: 12h
Damage:: 3-24 (3d8)
Wate:: 2.8kg
EXPS:: 200
Value:: 1000

The radiation grenade bathes the area of effect with lethal radiation types.
Any target caught in the bath area will take 3 to 24 hit points of damage.
There is a simultaneous radiation attack of intensity equal to the damage rolled. 
If the blast doesn't get you, the radiation will.
The radiation grenade is entirely silent. 

The grenade attack leaves ongoing lethal residual radioactivity. 
The area of effect will remain toxic one day per intensity level of radiation.
A radiation intensity 12 attack would remain toxic for 12 days. 
The intensity decreases by 1 per day until there is no lethal radiation.
The detonation site will remain anomalous to radiation detectors forever.

The radiation grenade is also known as a Neutron grenade or a Micrograve Oven.

=== Skylighter Grenade

[horizontal]
Range:: STR
Area of Effect:: 40h x 40h rectangle
Damage:: 4-40 (4d10)
Wate:: 2.95kg
EXPS:: 300
Value:: 5500

The sky lighter is an outdoorsy grenade.
On detonation, the grenade launches a projectile into the sky.
After 2-6 (3d3) units, the enormous area of effect is deluged with jagged hail.
The initial explosion does no damage, but the hailstorm is like nails that melt.
This grenade depends on complex meteorological mechanisms.
This grenade is useless if used indoors, underwater, in zero gravity or a vacuum.

The skylighter grenade is also known as a Painmaker, Rainmaker, or Chicken Little.

=== Torc Grenade

[horizontal]
Range:: STR
Area of Effect:: 12h
Damage:: 12-144 (12d12)
Wate:: 1.75
EXPS:: 275
Value:: 9000

The torc grenade is the anti-force field grenade.
A torc grenade does no damage unless the target is within a force field.
The grenade affects any force field that makes contact with the radius of the torc grenade.
Any tactical, personal or battery-powered force field will instantly be exhausted.
A force field powered by a renewable power plant returns in 1 to 10 minutes.
The torc grenade cannot damage a civic or naval forcefield. 
The grenade may create a temporary hole in such force fields to assist the story.

The collapse of the shield delivers 12-144 (12d12) hit points of damage.
The damage is only for those targets inside the force field. 

The torc grenade is also known as a force field disruptor.

:art: unpinned.png
:width: 350px
:snark: Not the throwning part.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: A grenade's pin and lever laying on the ground.

include::ROOT:partial$articulate.adoc[]

== Trigger
The trigger of the grenade activates the weapon, and the sudden deceleration on the target hex detonates it.
The grenade can also detonate if it were to hit a solid object after activation.
Grenade triggers are mainly descriptive.

include::ROOT:partial$CH45_Table_Grenade_Trigger.adoc[]

== Number
Grenades come in six-packs, not unlike a famous mundane terran beverage.
However, only 1-6 (1d6) grenades will be in a pack.
For powerful campaign-altering grenades, five of the six will be missing.

:art: grenade_loveless.png
:width: 250px
:snark: They never look like this
:artist: Unknown
:date: Unknown
:license: CC BY-SA 4.0
:description: Drawing of an old school grenade with pin and release lever.

include::ROOT:partial$articulate.adoc[]

== Description
Not all grenades are created equal. 
Even the same grenade type may have different shapes and colours.
The random descriptions of grenades in EXP arise from the technological chaos.
Different companies, species, technologies, and regulations are all mixed.
Grenades lack identifying markings.
Identification of a grenade depends on instinct, feel and other indicators.
Expeditions often blow themselves fiddling with grenades.

=== Grenade Shape
The bomb shape table is used purely for the convenience of the author.

include::ROOT:partial$CH44_Table_Bomb_Shape.adoc[]

:art: equine_hoof_grenade.png
:width: 250px
:snark: Any shape, any size, any shade of grey.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Stylized futuristic hand grenade with large obvious loop pin.

include::ROOT:partial$articulate.adoc[]

=== Grenade Shape Shift
The bomb shape deformation table is used purely for the convenience of the author.
It is not lazy. 
It is efficient.
This table is optional, but if you don't use it, you are the lazy one.

include::ROOT:partial$CH44_Table_Bomb_Shape_Adjustment.adoc[]

=== Grenade Adornment
The bomb adornment table is used here because this author is efficient and preserves electrons.
Adornments are the most fun and aggravating descriptors of grenades. 

include::ROOT:partial$CH44_Table_Bomb_Strange_Adornment.adoc[]

=== Grenade Colour
Keep it simple with a 1d10 roll, or make it zany with a 1d100 roll.

include::ROOT:partial$add_colour_to_your_world.adoc[]

== Grenade Parameters
For details on the special elements of grenade combat jump to xref:roll_playing_system:CH30_Area_of_Effect_Weapons.adoc#_grenades[GrenadeCombat,window=_blank].

=== Range
The range of a grenade depends entirely on the thrower.
A persona can throw a grenade one hex per point of Strength
There is no guarantee that a persona can throw a grenade further than its area of effect.

=== Area Of Effect
The area of effect represents the radius of the sphere affected by the grenade.
For example, a fragmentation grenade has an area of effect of 1 hex.
Any target with the target hex and the surrounding hex is affected.
Personas above the target hex are also impacted because the area of effect is spherical.m
The area of effect of a grenade is indiscriminate and any fellow expedition members caught in the area of effect are impacted.

=== Damage
The damage parameter has a range of hit points and the dice for calculating the damage amount in parentheses. 
If there is no damage parameter listed, the weapon likely has some other horrible effect.

=== Wate
The wate of the grenade in kilograms.

=== EXPS
The persona gets this value for identifying the grenade. 
The player may identify the grenade before or after detonation. 

=== Value
The value of the grenade in eps.

