= Miscellaneous Weapons

Miscellaneous weapons are unique technomagical artifacts that do not fit into typical weapon types.
These weapons have bizarre twists that make them different from the regular bizarre weapons.
Miscellaneous weapons are killing devices, and they are used to deliver injury and death.

.*Miscellaneous Weapon Checklist*
. <<_miscellaneous_weapon_type,Miscellaneous Weapon Type>>
. <<_miscellaneous_weapon_parameters,Miscellaneous Weapon Parameters>>

== Miscellaneous Weapon Type

include::ROOT:partial$CH49_Table_Miscellaneous_Weapon_Type.adoc[]

:art: arm_of_ephro.png
:width: 350px
:snark: A disarming armament    
:artist: Hugh   
:date: 1991     
:license: CC BY-SA 4.0
:description: Drawing of a flying stick with serrated disks on both ends.

include::ROOT:partial$articulate.adoc[]


=== Arm of Ephro 
[horizontal]
Type:: Strike
Range:: Adjacent Hex
Damage:: 4-24 (4d6)
Duration:: Until Destroyed
Wate:: 30kg
EXPS:: 820
Value:: 1243941

The arm of ephro is a personal robotic combat machine.
The device appears as a pole with a spiked ball on each end.
The arm befriends a persona and will join in combat against her enemies.
The arm's only drawback is its tendency to jump the gun and attack prematurely.
The arm may spontaneously attack personas who the owner speaks harshly of or dislikes.
Whenever the persona gets angry or raises her voice, a 2% chance of the arm will go flying into action.
There is no method of communication with this robot. 
It only expresses its love by attacking the persona's enemies.
During combat, the arm fights in front of its owner and increases her AR by 75.
The arm attacks twice per unit, has an AR of 900, and can move at ten h/u (via anti-gray).
Unlike other robots, this one is destroyed when it reaches 0 HPS,
The arm of ephro will start with 10-100 (10d10) Hit Points.

:art: blackhole_oops.png
:width: 350px
:snark: Small but mighty
:artist: Patrick Redding    
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of people and machines being violently pulled into a singularity.

include::ROOT:partial$articulate.adoc[]


=== Black Hole 
[horizontal]
Type:: Special
Range:: Adjacent Hex
Damage:: Complete Annihilation
Duration:: 42 Moves per Battery
Wate:: 108 Tonnes
EXPS:: 5700
Value:: 50000000000

The black hole is an unorthodox but deadly weapon.
When activated appears as a black space.
Anything that wanders within one hex of the active black hole also wanders into oblivion.
Any artifacts, personas, projectiles that pass through the field disappear in a spiralling light show. 
While this process is not instantaneous, it cannot be stopped and is absolutely final.
Anything lost to a black hole is lost from both time and space and can never be retrieved.
Pretty serious stuff.

An activated black hole does not suck the air out of a room. 
An activated black hole does pull everything within light-years towards it.
An activated blackholed does not generate darkness beyond its one hex radius.
There is some debate whether this weapon is a black hole at all. 
Maybe it is a tiny black hole?
Maybe it is a field gravity anomaly that behaves like a black hole?
In this mythos, there are few scientists (mechanics) left to study this artifact.
Accidents lead to less and less of them all the time.

When deactivated, the black hole lives in its gravulator.
The gravulator looks like a spherical backyard three-wheeled barbecue with a matching remote control device. 
The gravulator has a wate over 100 tonnes.
The gravulator disappears when the black hole is activated and reappears when inactivated.

The gravulator remote control is the only way to move the black hole.
The remote control has a few arrows and an off/on button.
It is an off/on button and not an on/off button. 
The black hole can only move by remote control in its inactive gravulator form.
The sphere of darkness must be properly, never safely, positioned before being activated.
The remote control for the gravulator can store five moves simultaneously and is very irritating to maneuver.
The gravulator moves at two h/u and can make 42 moves before replacing the battery.
Throwing the remote control into the black hole automatically deactivates it, and it returns to its gravulator state.
The black hole will not consume its remote control, but it will finish consuming whatever else is on the menu.

For example, maneuver the black hole via the gravulator up against a wall. When the black hole is activated, it will suck in all the wall elements touching the black hole. 
It will not suck in the whole wall. 
It will create a black hole sized opening in the wall. 
There is no dust or debris or noise, just a spiral of final light.
Whether the rest of the wall gives off debris, creaks or whines, or collapses is the referee's purvey.
Personas going into the black hole may be very noisy indeed.

If the gravulator loses power, is destroyed or tampered with, the black hole will drift away.
The black hole will float away from the planet's gravity at a rate of 1cm per day. 
It will eat all it encounters, disappearing in the blackness of space, looking for its friends.

=== Bullet Pen 
[horizontal]
Type:: Shoot
Range:: 20h (-200)
Damage:: 4-24 (4d6)
Duration:: One Shot
Wate:: 0.1 kg
EXPS:: 200
Value:: 700

The bullet pen appears and functions as a normal pen.
It has a steel nib and an inkwell and writes very nicely.
However, drawing back the pocket clip ignites the ink, firing the steel nib as a lethal projectile.
This pen is mightier than a sword.

:art: compucrafted_dagger.png
:width: 350px
:snark: More comp more stabby.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Stylized futuristic looking dagger.

include::ROOT:partial$articulate.adoc[]

=== Compucrafted Weapon 
[horizontal]
Type:: Strike or Fling
Range:: Same
Damage:: Special
Duration:: Until Destroyed
Wate:: Special
EXPS:: 500
Value:: Special

The compucrafted weapon is a new and improved version of a mundane weapon type.
Compucrafted weapons are better balanced, better engineered, and use better materials, 
The compucrafted equivalent of a mundane weapon is easier to use and more dangerous. 
Compucrafted weapons have an attack roll bonus of +3-300 (3d100) and a damage bonus of +1-8 (1d8).
Thus a compucrafted sword could have an attack roll bonus of +120 and a Force Bonus bonus of +5.
The compucrafted weapon's wate is half the mundane weapon's wate. 
The wate alteration has no adverse effect on the weapon. 
It is still a more potent killing device.
The compucrafted weapon's value is equal to its mundane cost multiplied by its attack roll bonus.

include::ROOT:partial$CH49_Table_Compucrafted.adoc[]

=== Comm Blaster 
[horizontal]
Type:: Special
Range:: 300 h
Damage:: 6-36 (6d6)
Duration:: 3 Uses per Battery
Wate:: 7.4 kg
EXPS:: 700
Value:: 220000

The comm blaster destroys a specific radio transceiver by delivering a pulse of energy.
The target radio explodes like an acoustic fragmentation grenade.
The explosion has a two hex radius area of effect.
This counter-insurgency device is for destroying active threats or disposing of compromised equipment.
The comm blaster does not work on lazer communicators.
Regardless of the communicator size, the area of effect and damage is the same.
Earpiece or smaller personal comm devices destroyed only harm the wearer and have no area of effect.

=== Cutting Lazer 
[horizontal]
Type:: Special
Range:: 15h (-999)
Damage:: Special
Duration:: 20 Units per Battery
Wate:: 5 kg
EXPS:: 795
Value:: 120000

A cutting lazer is an industrial tool repurposed to destroy robots. 
This robot slayer is the bane of synthetics, women in powered armour, and most referees.
The cutting lazer emits a coherent beam of organized light that slices through solid, inorganic matter, like a lazer slices through a vacuum.
The mere twist of a persona's wrist can cut a hex-sized hole in hull metal.
An inventive player can use this artifact to solve most scenarios in a few moments.
What defence does a referee's scenario have against a cutting lazer (other than organic walls)?
Nothing.

For uncombat cutting, the lazer cutter works as expected.
The lazer cannot cut more than four hexes in length per unit (a generous hex-sized opening).
The cutting lazer has 20 units of power, and every unit of cutting uses 1-12 (1d12) units of energy.

Weaponizing a cutting lazer first requires an attack roll win.
Involuntary targets are not automatically hit like a stationary wall.
Sessile inorganic targets do not require an attack roll.
A cutting lazer gets a +250 attack roll bonus against inorganic targets.
A successful hit will simply cut something off.
The damage incurred by inorganic targets should be at least catastrophic.
A cutting lazer will inflict 100 to 600 (10d6 times 10) HPS of damage to robots per successful hit.

:art: displacement_gloves.png
:width: 350px
:snark: Force field sucker punch
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of human face eating a force field knuckly sandwich.

include::ROOT:partial$articulate.adoc[]

=== Displacement Gloves 
[horizontal]
Type:: Strike
Range:: Special
Damage:: 1-4 (1d4)
Duration:: 20 hits per Battery
Wate:: 0.4 kg
EXPS:: 240
Value:: 600

The principle of displacement gloves is straightforward.
A force field projects the damaging force ahead of the incoming fist.
The displacement gloves alter the range of the striking force after each attack, making it difficult for the target to get familiar with the device.
There is a +150 attack roll bonus for punches offered.
The bonus is primarily due to the target's confusion rather than increased combat skill.

:art: electro_staff.png
:width: 250px   
:snark: Electro staff discharging
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Old timey staff weapon with electricity pulsing off it's business end.

include::ROOT:partial$articulate.adoc[]

=== Electro Weapon
[horizontal]
Type:: Strike or Fling
Range:: Special 
Damage:: Special
Duration:: 30 hits per Battery
Wate:: Plus 0.3 kg
EXPS:: 500
Value:: Plus 900

Electro weapons are non-powered weapons with an added electrical charge.
Electro weapons are also called zappers.
The electro weapon attacks the same as its base weapon type, but the electro weapon has an added kick of +2 to 16 hit points of shock damage.
When the battery charge runs out, an electro weapon still works as a mundane weapon.

include::ROOT:partial$CH49_Table_Electro.adoc[]

=== Expando Dagger 
[horizontal]
Type:: Strike
Range:: Nil
Damage:: 4-24 (4d6)
Duration:: Until Destroyed
Wate:: 0.75
EXPS:: 220
Value:: 110

An expando dagger appears as an ordinary dagger.
The expando mode is optional and activates when the player wins an attack roll.
The player can choose to have the weapon attack as a regular dagger (1d4) or activate its expando mode.
The expando action fires out barbs and hooks when the dagger detects a target hit.
This shredding action accounts for the additional damage.

A skilled user has three options after the expando barbs are activated. 
*The first option* to have the barbs retract, allowing for another attack in the next unit. 
*The second option* is to have the dagger remain stuck in the target. 
The barbs and hooks undulate, causing extreme pain and ongoing damage.
Leaving the expando dagger in the target inflicts ongoing damage of 1-4 hit points per unit. 
A vet or mechanic is required to remove the expando weapon. 
*The third option* is to violently pull the expando dagger our inflicting another 4-24 (4d6) hit points of damage.
The player must win a Strength roll against the initial damage, or her persona loses control of the dagger.

A poison-coated expando dagger increases the intensity of the poison by 4 points locked into the target.

=== Flare Gun 
[horizontal]
Type:: Shoot
Range:: 40h (-999)
Damage:: 2-20 (2d10)
Duration:: Special
Wate:: 0.75 kg
EXPS:: 220
Value:: 110

The flare gun is a pistol-shaped survival device that fires a geostationary flare into the sky.
A dial on the flare gun determines the height of the flare.
The flare can fire horizontally to light up an area far from the expedition.
A five hex radius below the flare lights up like daylight.
The radius of effect is the same regardless of how high the flare above the ground.
Once aloft, the flare is unaffected by regular winds and shines through cloud and rain.
The flare and ground effect last until the firer turns it off.
The flare gun can reveal the expedition's position to rescuers or draw attention to enemy targets.

Players love to weaponize the flare gun.
While a cumbersome weapon, it has its bright spots.
A flare gun is a single magazine weapon and can only attack every other unit.

A successful attack roll inflicts 2-20 (2d10) hit points of damage.
Each hit point of damage indicates a 5% chance the flare will adhere and burn the target.
So a flare that inflicts ten hit points in damage has a 50% chance of sticking to the target.
While stuck, the flame burns brightly, both revealing the target and inflicting additional damage.
Each unit that the flare is attached inflicts an additional 1-6 (1d6) hit points of damage.

The flare is not designed to burn flesh or metal and extinguishes itself in 1-20 units.

=== Geo Drop Disk 
[horizontal]
Type:: Special
Range:: Special
Damage:: 100-1200 (1d12*100)
Duration:: One Use
Wate:: 0.5 kg
EXPS:: 650
Value:: 1500000

The geo drop disk is a targeting device for an exatmo bombardment.
The dense metallic disk may sport a few boring lights.
It may be mistaken for a land mine with blinking lights.
When activated, the disk becomes the center of an area of attack weapon from outer space.
The geo drop disk calls for and targets a surface strike from an orbiting death-dealing device.
The drop disk has two dials, one for the area of effect (0 to 20 hexes) and another one for time (0 to 30 units).
Setting both the dials prepares the device for action.
Dramatically dropping it to the ground activates the geo drop disk.
Once the timer expires, the disk "brings the rain" into the area of effect.
The geo disk is gravitationally locked in place and is unmovable once dropped.

The source of the area of attack depends on the referee's campaign and milieu. 
The mythos may indicate the activation of a long-forgotten orbiting space station, a drone strike or some out-of-sight artillery barrage.
Or a low orbit military craft patiently on duty. 
The personas may never know.

The nature of the damage is up to the referee as well.
There may be a wall of tiny pebbles hurtling at terminal velocity, a massive beam of destruction from the sky, a missile strike, or something odder.
Once a giant anvil labelled 16 tonnes crashed onto the geo disk. 

:art: grapple_whip.png
:width: 300px
:snark: Whip and hold.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Classic looking black whip composed of woven leather.

include::ROOT:partial$articulate.adoc[]

=== Grapple Whip 
[horizontal]
Type:: Fling
Range:: 1 hex
Damage:: 2-5 (1d4+1)
Duration:: Until Destroyed
Wate:: 0.3 kg
EXPS:: 200
Value:: 400

A grapple whip can be used as a regular whip-cracking damage out with a snap.
With an added twist, the grapple whip will tangle itself around the target.
The player must win an attack roll to grapple a target.
The grapple whip leaps from the attacker's grasp and starts to crush the grappled target.

The crushing and cutting of the grapple whip inflicts 4-24 (4d6) hit points of damage each unit.
The grapple whip will continue to grapple, crush and cut until it finds itself.
Even if the target is dead, the crushing grapple whip will continue to crush and cut until it connects with itself.
A grapple whip continues crushing until something falls off the target.
Typically the whip will meet itself and disengage after delivering 100 hit points. 
If a persona is still alive after 100 hit points of damage, the grapple may have amputated something.
The referee and players can consult xref:combat:hit_locations.adoc[Hit Locations,window=_blank] to determine what horror transpires.

The grapple whip can only grapple Tiny, Small, and Medium (anthro) sized targets.
Personas can destroy a grapple whip by damaging it with 100 hit points of damage.  

=== Grenade Launcher 
[horizontal]
Type:: Shoot
Range:: 30 h (-200)
Damage:: Special
Duration:: 30 per Battery
Wate:: 2.5 kg
EXPS:: 350
Value:: 4500

The grenade launcher is a pump-activated, magnetically powered grenade launcher.
The launcher can be mounted on a rifle or held like a pistol for the same effect.
The grenade launcher can hold three grenades at once.
The grenade must have a wate between 0.5 kg and 2.0 kg.
The grenade wate requirement becomes less stringent as the grenade launcher increases in tech level.
The grenades load unarmed, and they auto-trigger and detonate upon firing.
This weapon is pump-activated and requires batteries to function.

:art: inertia_axe.png
:width: 250px
:snark: Power assisted chopping device.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Axe with articulated and powered handle.

include::ROOT:partial$articulate.adoc[]

=== Inertia Weapon
[horizontal]
Type:: Strike or Fling
Range:: Special
Damage:: 10 + Special
Duration:: 30 per Battery
Wate:: +1.5kg
EXPS:: 300
Value:: 700

Inertia weapons technomagically increase their inertia the moment they contact a target.
While this increase in wate and force increases damage, it does not improve on attack rolls.
The damage delivered is three times the mundane weapons damage plus ten hit points. 

For example, a sword that inflicts 1-8 (1d8) hit points in damage would inflict 3-24 (3d8).
Then ten additional hit points plus the persona's Force Bonus are added to the total damage.
An inertia weapon that has no power functions the same as its mundane base weapon.

include::ROOT:partial$CH49_Table_Inertia.adoc[]

=== Lazer Bolo 
[horizontal]
Type:: Fling
Range:: 2 h per STR (-100)
Damage:: 3-38 (3d6)
Duration:: Until Explodes
Wate:: 1 kg
EXPS:: 700
Value:: 1300

The lazer bolo starts out looking like a metallic softball-sized sphere, but it transforms into a crackling lazer bolo when thrown.
The ball separates into two hemispheres with a crackling line of lazer light connecting them.

A successful attack roll inflicts 3-18 (3d6) hit points of damage.
There is a 5% chance per point of damage that the bolo will explode.
A bolo that sacrifices itself by exploding inflicts an extra 5-30 (5d6) HPS of damage.
If the bolo does not explode, there is a 5% chance per point of damage that the bolo will tangle and trip the target. 
The bolo can explode on any sized target but can only trip up medium, small and tiny personas.

If the bolo does not explode and does not tangle the target, it snaps back into a ball and must cool for three units.
On occasion, a bolo fight emerges where the same bolo flies back and forth.



=== Lite Sabre
[horizontal]
Type:: Strike (no Force Bonus)
Range:: Nil
Damage:: Special
Duration:: Until Destroyed
Wate:: 1.2kg
EXPS:: 700
Value:: Special

A lite sabre is an energy sword that retracts into its hilt.
There are three different types of lite sabre, each having its damage, duration, and value.
The three types of lite swords refer to the composition of the energy blade of the weapon. 

include::ROOT:partial$CH49_Table_Lite_Sabre_Type.adoc[]

If you need a random colour for the lite sabre then jump to xref:software:CH55_Appearances.adoc#_colour_your_whirled[Colour,window=_blank].

:art: knite_young.png
:width: 350px
:snark: Knites have many appearances.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Young woman with electrified baseball bat in full swing.

include::ROOT:partial$articulate.adoc[]

==== Clear
A clear beamed lite sabre is more a force field club than a lazer sword.
A successful attack roll inflicts 2-12 hit points of damage. 
While the beam is transparent, it is visible to the naked eye and cold to the touch.
Placing one's digits in the activated energy field will not injure the curious persona.
A clear energy sword does not allow for amputation attacks.
The clear lite sabre has a value of 10000.

==== Shimmering
A shimmering beam lite sabre has a superheated energy field emerging from its hilt. 
The smokeless energy blade resembles a flaming sword.
A successful attack roll inflicts 4-24 (4d6) hit points.
Placing one's digits on the blade of a shimmering lite sabre will burn and injure the curious persona.
The shimmering energy sword does allow for amputation attacks but does *not* as a Knite focus tool. 
The shimmering lite sabre has a value of 100000.

==== Solid
The solid beam lite sabre has a contained beam of cutting lazer light emitting from its hilt.
The beam is a solid blade of light and gives off a glow that matches its colour.
A successful attack roll inflicts 4-24 (4d6) hit points of damage.
Placing one's digits on the blade of a solid lite sabre will amputate them.
The solid lite sabre allows for amputation attacks and can become a Knite focus tool.
The solid lite sabre is priceless to Knites of either sect and a value of 1000000 to all other vocations.

==== Amputation
Any combat vocation (mercenary, Knite, spie or nomad) can amputate body parts with a lite sabre.
There is a 1% chance per point of damage of an amputating attack.
An amputating attack does no additional damage, leaving the target with a nicely cauterized stump.
The attack can cut off a tentacle, mechanical arm, or hoof equally easily.
For help with amputation location jump to with xref:combat:hit_locations.adoc[Hit Locations,window=_blank].

A spie or nomad must take proficiency in lite sabre to allow for amputation attacks. 
Mercenaries can use their proficiency ability.
The Knite ability of amputation is in addition to the percent chance of lite sabre amputation.
The player does not include her Force Bonus when determining the chance of an amputation attack.

==== Kirlian Focus Tool
A solid lite sabre is the preferred xref:vocations:knite.adoc[Knite's,window=_blank]  weapon.
Those lite sabres that act as a xref:hardware:CH48_Misc_Equip.adoc#_kirlian_talisman[Kirlian Talisman,window=_blank] for Knites are ancient and of limited number. 
These powerful mythologic weapons follow the path of a knite (order) or anti-knite (chaos).
The weapon amplifies the Kirlian energy through chaos or order.
A lite sabre will be either a knite sabre or an anti-knite sabre.
The referee and players will decide if they have found a tool of chaos or order.

=== Mash Net 
[horizontal]
Type:: Fling
Range:: 3 h (-999)
Damage:: 2-20 (2d10) per unit
Duration:: Until Destroyed
Wate:: 3 kg
EXPS:: 350
Value:: 700

The mash net functions as a regular net when used as shielding.
When thrown as an attack weapon, the mash net will tangle up the target.
The more the target struggles, the tighter the mesh net gets. 
Each unit of struggle will inflict 2-20 (2d10) hit points of crushing and cutting damage.
If the target remains motionless and does not struggle, they will not take any crushing damage.
Personas like flora or fauna may panic and struggle until killed by the mash net.
 Intense cooling will cause the mash net to unfold and release its captive.

=== POV Canon 
[horizontal]
Type:: Shoot
Range:: 15h (-333)
Damage:: 1-4 (1d4)
Duration:: 6 per Battery
Wate:: 4.2 kg
EXPS:: 869
Value:: 245000

The POV Canon (pronounced paw-vee) inflicts minimal physical damage and massive mental transformation.
A successful attack roll has two components: damage and a powerful wave of compassionate transference.
The target will take 1-4 (1d4) hit points of damage and a psionic attack of intensity 1-10 (1d10) plus the firer's Mind.
If the target loses the mental attack roll, she suffers an intense but temporary change of mind. 
The target's point of view switches to a deep, often debilitating, understanding of the attacker's point of view.
The persona immediately adopts a complete understanding of the attacker's emotional and personal position.
The results of this are temporary, lasting one unit per point of intensity of the attack.

A space trooper adorned in plastix armour may suddenly stop attacking the expedition because she now 'feels' her enemy.
On rare occasions, the target may assist the firer of the POV Canon.
More often, the target will wander off in a perplexed and deeply contemplative state.
There is a 1 in 1000 (42 on 1d1000) chance that the target suffers a complete conversion. 
Complete conversion only works on intelligent organic life forms, and the persona will permanently side with the firer of the weapon.
Flora or fauna are immune to POV attacks but still take the physical damage.

The POV Shooter is an excellent negotiation or interrogation tool.
Personas gain +24 when negotiating with a target hit by a POV Canon.
The POV Canon is not a stealth weapon.

=== Rocket Assisted Weapons 
[horizontal]
Type:: Fling
Range:: Tripled
Damage:: Doubled + 15 
Duration:: One Use
Wate:: 4 times
EXPS:: 300
Value:: 10 times

Rocket-assisted weapons are formerly mundane non-powered missile weapons with rocket assist.
The arrows, boomerangs, and daggers have micro boosters that increase speed and range. 
Until the boosters kick in, the weapons are indistinguishable from their mundane counterparts.
The boosters are activated when launched, and the rocket weapon screams into action.
Rocket-assisted weapons are initially self-powered, but the booster rockets triple their range and increase their damage (15 + 2 times damage).

Jump to mundane formerly non-power projectile weapon list xref:hardware:CH49_Misc_Weapons.adoc#_type_b_weapons[here,window=_blank].

:art: rocket_launcher_shells..png
:width: 350px
:snark: Not your NASA rockets
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a tube with a trigger and some stylized rocket ammunition.

include::ROOT:partial$articulate.adoc[]


=== Rocket Launcher 
[horizontal]
Type:: Shoot
Range:: 75h (-100)
Damage:: 6-60 (6d10)
Duration:: 1-4 (1d4) Magazine
Wate:: 5 kgs
EXPS:: 500
Value:: 6000

The rocket launcher is a shoulder-mount directing tube that fires a tactical micro missile.
The missile's warhead explodes like a shrapnel grenade with a two hex radius of effect.
Like all other area of effect weapons, the firer targets a hex.
The target hex has an Defence Rating of 600, and a miss uses the grenade miss table.
The typical grenade area of effect carnage follows.

If the player targets a single unlucky persona, she must win an attack roll against the target's Defence Rating.
There is no area of effect blast, but the target takes triple damage.
If the player fails the attack roll, the missile flies off into the distance.
Directly targeting a persona is an act of classic action movie vengeance.

Indoor use of a rocket launcher is an off-label that never works as expected.h

The rocket launcher's magazine holds 1-4 (1d4) rockets.
A rocket launcher with a three-missile magazine can fire three times before having to reload.

.*Exotic Warhead*
There is a 20% chance that the rocket launcher has an exotic warhead.
An exotic warhead has a grenade instead of the typical warhead. 
The grenade area of effect, damage and special effects replace the standard fragmentation warhead.
To determine the grenade type jump to xref:hardware:CH45_Grenades.adoc#_grenade_type[Grenade Type,window=_blank].
Add the value of the grenade to the value of the rocket launcher.

.*Exotic Missile Type*
There is a 42% chance the rocket launcher has an exotic delivery method.
The exotic missile type replaces the standard expanding gas delivery method.

include::ROOT:partial$CH49_Table_Special_Rocket_Type.adoc[]

Auto strike::
A computerized targeting sight allows the firer to attack solitary targets with ease.
The player can choose to hit a target hex for the usual effect.
If the player target's a solitary persona (to hit for triple damage), the target's AR cannot be higher than 600.
Direct hits inflict triple damage and have no area of effect damage
Auto strike increases the value of the rocket launcher by 5000000.

Crawl::
The persona uses the targeting system to identify the target hex and pulls the trigger.
Instead of a flaming missile shooting out of the rocket launcher, the rocket hops out and crawls along the ground.
The crawling rocket moves at +25 h/u and can be on treads, wheels or scud along.
Crawling missiles are experts at evading detection and anti-missile systems.
If necessary, the missile may park itself and wait for a clear shot.
A crawling missile acts as an ambush, but an attack roll must still be successful. 
Crawl increases the value of the rocket launcher by 1000000.

Decoy::
Decoys accompany every rocket launched from the tube.
Each rocket attack includes 1-3 (1d3) mostly harmless decoy rockets.
The number of decoys is determined once and remains the same every attack.
The decoys are identical in appearance and speed.
The decoys will reduce the effectiveness of anti-missile defences.
In the case of anti-missile devices, the player gets +100 on the attack roll per decoy.
There is no attack roll bonus if there is no anti-missile defence.
There is confusion as there is more than one incoming missile.
Each decoy increases the value of the rocket launcher by 100000.

Delay::
The persona uses the targeting system to identify the target hex and pulls the trigger.
When fired, the missile slowly exits the tube and heads off in a random direction.
The rocket takes a leisurely and uninterceptable course to the target.
This rocket cannot follow moving targets and only works for hexagons and buildings. 
The rocket arrives 2-20 (2d10) units after being launched.
An attack roll is still required to hit the target hex.
The delayed arrival rocket increases the rocket launcher value but 100000.

Memory::
The persona uses the targeting system to identify the target and pulls the trigger.
The missile will remember this location or persona and immediately starts tracking the target.
A memory missile can arrive much later. 
The rocket can travel up to 100 kilometres or ten days to find and detonate on its target.
The rocket can go around corners, maneuver stairs, and even wait for an elevator.
The rocket cannot navigate off-planet or public transit.
An attack roll is still required when the rocket lands. 
The memory rocket increases the value of the rocket launcher by 10000000.

Passenger::
This rocket launcher has a cargo bay that can carry a 1.5 kg passenger.
The passenger can deliver the cargo safely at the target hex.
Often the passenger will be a grenade.
Rigging a grenade on a passenger rocket is a DD2 mechanic, or a DD12 mercenary, maneuver.
The passenger delivery system increases the value of the rocket launcher by 50000.

Vehicle:: 
The targeting system for this rocket launcher compensates for vehicular combat.
There are no penalties when firing from a vehicle at any speed.
The missile can also lock onto a vehicle chasing it down at supersonic speed.
The missile will take 0-3 units to catch up with a targeted vehicle.
A successful attack roll is still required. 
Vehicle compensations increase the value of the rocket launcher by 200000.

:art: spinning_wheel_of_death.png
:width: 350px
:snark: Not spinning Not deadly
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Giant serrated device sitting on table with built in crank. 

include::ROOT:partial$articulate.adoc[]



=== Spinning Wheel of Death 
[horizontal]
Type:: Fling
Range:: 150h (-999)
Damage:: Special
Duration:: Reusable Self Powered
Wate:: 25kg
EXPS:: 500
Value:: 32000

The spinning wheel of death is a hand-cranked flying wheel that brings serrated death from above.
The wheel looks like a small table sporting a crank and a dangerous-looking children's spin top.
The spin top is large and covered in razor-sharp vertical slats.
The stalk of the spin top rests beneath the table and sports needles and barbs.
Feverish cranking of the SWOD activates it after two units.
Once activated, it flies straight up into the air and hovers while picking its target.
The spinning wheel of death will select a random organic persona that is in front of the table.
The front of the table is the non-crank side.
The wheel does not discern between player personas and referee personas. 
If there is and paucity of targets, the wheel could come back for the persona that launched it.
Once the wheel makes its decision, it hurtles in for the kill.
The device employs callous AI, as well as thermal and motion detectors. 

The wheel automatically hits less important referee personas.
The SWOD automatically wins its attack roll against flora, fauna, and cannon fodder.
The player must win an attack roll before damaging player personas and relevant referee personas.
The player makes an attack roll with a +200 bonus to hit the target (it is possible to be rolling a hit on one's persona).

Damage from the spinning wheel of death is excessive.
The gnarly stem pins the target to the ground, and its barbs and hooks start to grind away.
The stem flies around and tears at the target for 0-3 (1d4-1) units, inflicting 4-40 (4d10) hit points of damage each unit.
After the tearing and grinding from the stem finishes, the main body inflicts an additional 10-100(10d10) hit points of damage.

Once all damage is delivered, the wheel can be recovered, cleaned off and used again.
Hit location makes no difference to the damage.
There is no saving roll.

=== Stun Weapons 
[horizontal]
Type:: Strike or Fling
Range:: Special
Damage:: Special
Duration:: 15 per Battery
Wate:: + 0.3kg
EXPS:: 250
Value:: 2000

Stun weapons are complicated artifacts that render organic targets stunned and incapacitated.
These are the less-lethal weapons of choice for pacifists or kidnappers.
They appear as mundane persona-powered weapons like a sword, mace, or bow.
There may be a small light or some circuitry betraying their unusual nature.
The player makes an attack roll and rolls damage as she would with the usual weapon.

Technomagical servos, force fields and force converters protect the target from taking physical damage.
The energy that usually damages the target converts into a neural shock designed to knock the target out.

If the attack roll is successful, the player rolls damage and the damage indicates the intensity of the stun attack.
For example, instead of taking 13 hit points in damage, the target is hit with an intensity 13 stun attack.
Failing the saving roll leaves the target stunned for 1-4 (1d4) minutes. 
Inorganic personas take damage from the electrical nature of the attack but cannot be stunned.

include::ROOT:partial$CH49_Table_Stun.adoc[]

==== Gauntlets
The stun gauntlets appear as bulky electronic gloves.
The stun intensity is equal to the damage a punch. 
A punch inflicts -1 to 2 (1d4-2) hit points of damage plus Strength.
The harder the hit, the more likely the fall.

=== Transmogrifier 
[horizontal]
Type:: Shoot
Range:: 15h (-666)
Damage:: Special
Duration:: 5 per Battery
Wate:: 42 kg
EXPS:: 566
Value:: 325000

The transmogrifier converts diverse matter into a homogeneous solid block.
The artifact appears as a box with a giant overly dramatic lever on top.
Pulling the lever activates the weapon.

The player points the business end of the transmogrifier in the general direction of the target.
If the attack roll is successful, the target (alien, anthro, or robot) must save versus poison or turn into a statue.
The intensity of the poison attack is 3-24 (3d8). 
If the player fails the poison roll, the persona transmogrifies into a solid block.
The player must fail the poison even if the persona is willing to be transmogrified.

Transmogrification does not freeze the persona. 
It transforms her into a 1 to 1 scale statue of themselves.
The https://en.wikipedia.org/wiki/Cinema_of_the_United_States[Hollywood] version of the device blows off the target's clothing, leaving a detailed naked statue.
The https://en.wikipedia.org/wiki/The_Walt_Disney_Company[Disney] version of the device transmogrifies the persona's equipment and clothing as well. 
No damage is delivered when the persona transmogrifies into a statue.
If the persona saves versus transmogrification, she takes 3-18 (3d6) hit points of damage.

Transmogrification reverses easily.
The player points the business end of the transmogrifier in the target's general direction and pulls the overly dramatic lever.
The persona will return to her previous state with or without clothing.
Reverse transmogrification inflicts 2-12 (2d6) hit points of damage.

Typically this device is used as a weapon by freezing combatants out of the fight.
An expedition can also use the process to freeze personas for their protection.
The statue is unaffected by poison, radiation and the vacuum of space.
Voluntary transmogrification is helpful for emergency stasis or hiding in a museum.

The statues are not indestructible, and moving them requires reasonable care.
If a statue loses a limb, the persona will be missing that limb.
If something destroys the statue, the persona is dead.
If numbers are needed, a statue will have 1000 hit points.
The statue has no Defence Rating and is defenceless against chisels or hammers.

=== Temporal Disrupter 
[horizontal]
Type:: Shoot
Range:: 20h (-100)
Damage:: Special
Duration:: 7 per Battery
Wate:: 4 kg
EXPS:: 475 
Value:: 542000

The temporal disrupter is a chrono accelerator that instantly ages targets.
A successful attack roll inflicts 3-36 (3d12) hit points of damage and ages the persona one year per point of damage.
The ageing effect is instantaneous and permanent.

Organic personas that pass through a life stage will lose or gain attribute points.
Enough ageing will kill the organic persona.
Aliens with short life spans may instantly die.

Inorganic personas and artifacts appear more shabby and suffer hit point damage as well.
The temporal disrupter will destroy a robot, but it may take a long, long time.

For more info about temporal attacks jump to xref:uncombat:health.adoc#_aging[Aging,window=_blank].

A malfunction will this weapon inflicts an ageing attack on everything within a two hex radius.

=== Toss Garotte 
[horizontal]
Type:: Fling
Range:: 25h (-170)
Damage:: Special
Duration:: Reusable
Wate:: 0.25 kg
EXPS:: 290
Value:: 5000

The toss garotte is a hideous memory metal murder weapon.
The weapon looks like https://en.wikipedia.org/wiki/Aerobie[flat ring], and the persona throws it like a disc toy.
The opening fits any anthro-sized head.
The persona can place the garotte over the target's head or toss it from a distance.
To place the garotte is a Strike attack that requires a successful ambush.
When tossing the garotte, previously unforeseen guidance systems will drop the weapon over the target's head.

A successful attack roll indicates that the garotte is on the target's shoulders and quickly clamps the target's neck.
As the garotte tightens, it inflicts 2-8 (2d8) hit points of damage per unit.
The strangling target must win a saving throw versus her Constitution or fall unconscious.
The intensity of the attack increases with the damage that the garotte inflicts. 
The first unit inflicts six hit points and requires an intensity 6 saving roll to stay conscious.
The second unit inflicts five hit points and requires an intensity 11 saving roll to stay conscious.

Once the target is unconscious, the toss garotte stops inflicting damage.
Safe removal of the toss garotte requires a vet or mechanic task roll.
Violent removal of the toss garotte requires 30 hit points of damage. 
The target suffers the damage as well.
If a toss garotte kills a persona during strangulation, it has accidentally decapitated the target.

:art: nass_bruckles .png
:width: 350px
:snark: Worse than a knuckle sandwich.
:artist: JEShields
:date: 2014
:license: Copyright JEShields Stock Art. jeshields.com
:description: High tech brass knuckles with a screen and wires.

include::ROOT:partial$articulate.adoc[]

=== Vibro Weapon
[horizontal]
Type:: Strike 
Range:: Nil
Damage:: +20 damage
Duration:: 25 per Battery
Wate:: +1.3kg
EXPS:: 500
Value:: 5000

Vibro weapons are non-powered thrusting and striking weapons that amplify their deadliness by vibrating at hypersonic speeds.
The vibration aids the weapons attack roll and damage roll. 
Vibro weapons earn +100 on an attack roll and get +20 hit points to a damage roll.

Jump to the xref:hardware:CH49_Misc_Weapons.adoc#_type_a_weapons[Strike Weapon,window=_blank] to see which mundane weapon is being vibrated.


=== Web Gun 
[horizontal]
Type:: Shoot
Range:: 20h (-100)
Damage:: Nil
Duration:: 5 Uses
Wate:: 1.75
EXPS:: 375
Value:: 900

The web gun is a glue sprayer with a one hex area of effect.
A successful attack roll stops the target in her tracks.
The target will be incapacitated by gluing her down to the ground or by gluing all her limbs together.
The web gun will work on any target less than 750 kg in wate.

The delicate glue threads remain sticky for 0-3 (1d4-1) units.
Anything passing through the webbed hex or touching the webbed target will also get entangled.
Once the web is set and hardened the target is wrapped in a cocoon.
Once cocooned, only outside help may free the victim.
Chiselling, acid, or cutters will make short work of the web, but the persona can't move to free herself.
Saliva can loosen the web just enough to breathe.

NOTE: Other bodily fluids do not affect the web. 

=== Whammer 
[horizontal]
Type:: Fling
Range:: 35h (-100) 
Damage:: 3-36 (3d12)
Duration:: As Needed
Wate:: 1.0 kg
EXPS:: 750
Value:: 1050

The whammer is a lazer disc.
The persona throws the whammer like a discus.
The lazer frisbee will return to the persona after each attack
The whammer returns 0-3 (1d4-1) units after each attack.

The throwing action charges the whammer, and it requires no batteries.
Any target trying to catch the whammer automatically gets takes damage.

== Miscellaneous Weapon Parameters

=== Type 
The refers to the attack type of the miscellaneous weapon.
Jump here for the gory details of xref:combat:attack_types.adoc[Attack Types,window=_blank]

include::combat:partial$attack_types_details.adoc[]

=== Range 
The range is how far the weapon can shoot and retain its accuracy. 
The range is a hardware limitation and does not reflect the skills of the persona in any way. 
The weapon's range is limited by wavering bullets, dissipating charges, or decaying material.

The range lists a number and a negative number in brackets, 120h (-230). The first number is the range in hexes where there are no range penalties. The number in brackets is the per hex penalty for targets beyond the weapons range (first number).

A weapon has the following range parameters 120h (-230). 
The persona can shoot any target within 120 hexes with no penalties. 
A target 121 hexes away has a -230 attack roll penalty. A target 123 hexes away has a -690 attack roll penalty.

The range parameters of 100h (-1000) indicate a weapon with a maximum range of 100 hexes and no further.

Past versions of EXP called the number in brackets the decay value of the weapon.

=== Damage 
The damage is the range of hit points the target loses when the player wins an attack roll.
Shoot weapons get no STR Force Bonus.

=== Duration 
Duration is the amount of use that the miscellaneous weapon can withstand before it depletes its battery charge.
The duration parameter can show units, the number of charges, or other metrics indicating when the device needs recharging, reloading, etc.

=== Wate 
The wate is simply the wate of the weapon in kilograms, excluding batteries.
This value is added to the persona's wate allowance if she decides to carry the weapon.

=== EXPS 
The persona wins this experience point award for identifying the miscellaneous weapon.
The player may identify the weapon by deduction or activation.

=== Value 
The value indicates the MSRP (Money Suggested for RolePlaying) of the miscellaneous weapon in eps. 

=== Accessory Tables 
Located here for your rolling convenience.

==== Strike Weapon List

include::ROOT:partial$CH49_Table_Miscellaneous_Type_A_Weapons.adoc[]

==== Fling Weapon List

include::ROOT:partial$CH49_Table_Random_Type_B_Miscellaneous_Weapons.adoc[]
