= Pharmaceuticals

The pharmaceuticals described in this chapter are fantastic miracle substances capable of diagnosing, preparing, and administering the proper remedy.
They can do wonders, but they can also have deadly side effects.
Pharmaceuticals come in groups of doses called a prescription.
A prescription may consist of pills, injections or liquids.
A prescription will typically have a negligible wate.

:art: drugs.png
:width: 350px
:snark: Say no to pharma
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of pills, tablets, inhaler, and liquid dropper.

include::ROOT:partial$articulate.adoc[]


.*Pharmaceutical Checklist*
. <<_pharmaceutical_type,Pharmaceutical Type>>
. <<_prescription,Prescription>>
.. <<_labelling,Labelling>>
.. <<_delivery_method,Delivery Method>>
.. <<_metabolism,Metabolism>>
.. <<_side_effects,Side Effects>>
.. <<_doses,Doses>>
. <<_pharmaceutical_parameters,Pharmaceutical Parameters>>

== Pharmaceutical Type

include::ROOT:partial$CH50_Table_Pharmaceutical_Type.adoc[]

== Pharmaceutical Types

=== Cures 

[horizontal]
Duration:: Until next time.
Safety:: 4
EXPS:: 100
Value:: Special

A cure arrests the progress of a disease or poison.
A cure is not an inoculation and does not prevent future illness or repair existing damage.
Cures stop the affliction in its tracks and remove it from the persona.

include::ROOT:partial$CH50_Table_Cure_Type.adoc[]

Ageing::
The ageing cure removes any abnormal ageing the patient has suffered.
If there is no abnormal ageing (like from a Chrono weapon), the cure increases the patient's life span by 10%.
Each time an ageing cure extends a persona's life span, the cure's safety level halves.
Value is 250000 per dose.

Trauma::
This cure removes any abnormal decreases to the patient's hit point maximum (HPM or HPM).
If there is no injury to the persona's hit points max, the patient's hit point max increases by 10%
Each time a trauma cure increases the patient's HPM, the cure's safety level halves.
The trauma cure has no impact on the patient's hit point total.
Value is 250000 per dose.

Infection::
Infection cure supercharges the patient's immune system removing any infectious invaders.
The types of infections include bacterial, viral, parasitic, prion or other sciency fiction infestation.
If there is no existing infection, the infection cure gives the patient +1 on any future infectious saving rolls.
Further doses of an infection cure have no further benefit to the patient.
An infection cure does not harm symbiotic infections like gut flora. 
Value is 50000 per dose.

Attribute::
The attribute cure can restore attributes reduced by natural ageing or unnatural attacks. 
This cure only has side effects if there are no degraded attributes.
The attribute cure will repair the most recently damaged attribute unless under the guidance of a veterinarian (10DD).
Value is 500000 per dose.

Psionics::
The psionics cure briefly disconnects the persona's consciousness from the think space.
This reset interrupts all psionic effects on the persona.
For example, a persona suffering mind control would be thinking for themselves after taking this cure.
The duration of the psionic cure depends on what makes for a better story. 
Value is 1000000 per dose.

Mutation::
This cure removes the patient's most recent mutation. 
The cure does not discriminate and removes beneficial or defective mutations.
A veterinarian 20DD maneuver is needed for the mutation cure to remove a particular mutation.
Value is 1000000 per dose.

Toxins::
Toxin cure arrests the effects of any non-radiation poison or toxin.
Toxins include envenomations, poison gases, chemical exposures etc.
The toxin cure does not affect radiation toxicity or toxic personalities.
The cure does not reverse damage or repair a persona's hit points. 
A veterinarian can use this cure to prevent injury from a specific expected poisoning with a 15DD maneuver.
Value is 50000 per dose.

Radiation::
A rad cure removes any ongoing effects of radiation from the persona.
If taken early enough, the cure can avoid damage from radiation as well.
How early is early enough? 
The persona would have to know that radiation damage is imminent. 
A veterinarian can use this cure to prevent radiation damage with a successful 15DD maneuver per dose.
Value is 50000 per dose.

Thermal::
A thermal cure returns organic flesh to its original state after cold or heat damage.
The thermal cure does not heal hit points back but restores any permanent damage due to thermal injury.
The cure will also arrest any ongoing thermal damage from an active attack.  
Value is 50000 per dose.

Ubiquitous::
The ubiquitous cure is programable by a veterinarian to cure what ails the persona. 
The vet and persona can choose whatever they would like cured with this generic cure.
The vet must win a 10 DD maneuver roll.
More difficult cures like curing a defective mutation or a mental illness would increase the DD.
If a pharmacologic impasse arises the players should consult the xref:roll_playing_system:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice,window=_blank].
Value is 4200042 per dose.

Decomposition::
This cure prevents the decomposition of a dead or soon-to-die persona.
The persona will not decompose, but they are also dead. 
The dead but not rotting persona requires advanced veterinarian machinery for rejuvenation. 
This cure has been previously called  "cured ham" or "poison apple."
Value is 250000 per dose.

=== DNA 

[horizontal]
Duration:: Until next time.
Safety:: 1
EXPS:: 1000
Value:: 2000000

DNA is a pharmaceutical for repairing or replacing injured or missing organs and limbs. 
Each DNA pharma has a specific focus, but it will replace any missing, damaged, or malfunctioning organ or limb.
If there is something to repair or replace, imbibing DNA is straightforward.
If the persona has no malfunctioning or missing parts bits, the DNA's impact is more random (fun).
DNA will diagnose what is missing and get to work repairing or replacing.
The process will finish in 10-100 (10d10) hours.

.*DNA Checklist*
. Side Effects
. Metabolism Type

==== Side Effects
If a persona using DNA has all her body parts intact, the pharmaceutical becomes confused, leading to side effects.
Repairing amputated limbs is not all that common unless the campaign is full of limb chopping Knites.
More commonly, a risk-taking persona will imbibe the DNA without knowledge of its effects.

There is a percent chance that the persona will gain a vestigial new limb growing from a random body location.
There is also a percent chance that the limb will be vestigial in size and shape but controlled by the personas. 
The percent chance of growing a new limb is equal to the persona's Constitution score. 
The chance of being able to control the limb is equal to the persona's Dexterity score.
A persona with an  11 CON and 14 DEX has an 11% of growing something new and a 14% chance of controlling it.

A vet can dial in the misuse of this pharma to get desired parts.
This would be a 42DD maneuver and a xref:roll_playing_system:CH14_Performance_Tables.adoc#_research_teams[Research Teams] is recommended.

include::ROOT:partial$CH36_Table_Snap_Hit_Location.adoc[]

==== Metabolism Types
DNA creates a proper and functioning body part regardless of its metabolism type.
For example, if a feline were to use canine DNA to replace a missing arm, she would have a canine arm.
This dog arm would be a fully functioning dog-like limb on an otherwise feline persona.
An alien metabolism type would create a limb that resembles an xref:roll_playing_system:CH06_Aliens_8_Shape.adoc#_terrain_types[Alien Body Part,window=_blank].
A canine may have a limb that looks like a worm, but it would function perfectly well. 
Not surprisingly, a robotic metabolism type will replace the missing limb or part with a cybernetic appearing limb. 

include::ROOT:partial$CH50_Table_Pharmaceutical_Intended__Metabolism.adoc[]

:art: pharma_pills.png
:width: 350px
:snark: Say no to candy.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Toy robot with either pills or candy spilling out.

include::ROOT:partial$articulate.adoc[]

=== Narcotic 

[horizontal]
Duration:: Special
Safety:: 5
EXPS:: -42 (yes minus)
Value:: 42

Narcotics are recreational pharma.
The narcotic effect may be a side effect of a malfunctioning pharmaceutical or a bespoke recreational pharmaceutical.
In EXP, narcotics do not offer insightful experiences that enhance Mind.
Narcotics render personas useless for their duration and have both temporary and permanent adverse effects.

Narcotics temporarily impair the persona's Awareness, Dexterity, Intelligence and Mind attributes.
For the duration of the impairment, the persona's AWE, DEX, and INT drop by 1-6 (1d6) points, and her Mind drops by half.
It is up to the referee to decide if the attribute drop can kill the persona.
Narcotic misadventures regularly kill pure strains on terra mundane.
Knites avoid any such excursions into the chaos of the mind.

Narcotics permanently decrease the persona's EXPS total by 42 points.

include::ROOT:partial$CH50_Table_Narcotic_Effect_Duration.adoc[]

include::ROOT:partial$CH50_Table_Narcotic_Effect.adoc[]

=== Heal 

[horizontal]
Duration:: Until the next injury
Safety:: 7
EXPS:: 100
Value:: Special

Heals are pharmaceuticals that immediately repair damaged tissue.
The vast majority of heals repair physical damage and increase the patient's hit point total.
The less common heal type restores damaged attributes.

include::ROOT:partial$CH50_Table_Heal_Type.adoc[]

==== Hit Points
Healing pharma instantly improves the persona's hit point total (HPS Total) but does not affect the maximum hit point (HPM).
So a persona with 42 hit points maximum will only heal to 42 hit points and no more.

include::ROOT:partial$CH50_Table_Hit_Points_HPS_Healed.adoc[]

Percent Heal::
A percent heal pharmaceutical raises the persona's hit point total to a certain percent of her hit point maximum.
A patient with 50 HPM taking a 50% heal jumps right to 25 HPS Total.
If that patient had more than 25 hit points, the percent heal has no effect.

Hit Points Heal::
These heals add the listed value to the patient's HPS Total.
A 20 hit point heal adds 20 hit points to the patient's hit point total.
The patient's hit point total cannot exceed her hit point max.

==== Attribute Heals
Attribute heals restore damaged attribute scores.
A persona who lost Charisma points to a burn, or a persona that lost Dexterity points to ageing will benefit from this pharmaceutical.
The pharma restores 1-6 (1d6) attribute points per dosage.
Attributes cannot exceed their original values by using heals.

:art: pro_vaxxer.png
:width: 350px
:snark: This will only hurt a lot.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Image of fancy looking hypodermic needle.

include::ROOT:partial$articulate.adoc[]

=== Inoculation 

[horizontal]
Duration:: Permanent
Safety:: 8
EXPS:: 1001
Value:: 1000000

Inoculations are not cures. 
Inoculations are not heals.
They neither repair nor fix the persona.
Inoculations increase the persona's resistance to future effects.
If a persona inoculated against paralysis, she will double her CON when trying to win a saving throw versus paralysis or stun attacks.

include::ROOT:partial$CH50_Table_Inoculation_Type.adoc[]

=== Mutation

[horizontal]
Duration:: Permanent
Safety:: 1/2 (TL / 2)
EXPS:: 100
Value:: 6000000

This pharmaceutical gives the persona a permanent mental or phenomic mutation.
The mutation will not be a defect.
The player will not know which mutation the persona has taken on.
Part of the fun, and danger, involves figuring out the mutation.

include::ROOT:partial$CH50_Table_Mutation_Type.adoc[]

Colour::
Colour deviations are a permanent side effect specific to this pharmaceutical.
The colour mutation will change the persona's skin or coat colour.
They appear after the mutant's first sleep after dosing.
Make a jump over to xref:iv-software:CH55_Appearances.adoc#_colour_your_whirled[Colour,window=_blank].

Mental::
The persona has acquired a psionic mutation.
The psionic mutation takes hold immediately, but the power is not immediately understood.
Psionic mutations are hard to figure out and may only reveal themselves under duress.
Jump to xref:v-wetware:CH58_Mental.adoc#_mutation_type[Psionic Mutations,window=_blank] to generate a fresh new mutation. 
*This mutation cannot be a defect.*

Physical::
The persona has acquired a phenomic mutation.
The phenomic mutation will take a few nights of sleep to grow in.
The mutation's growth can be itchy, painful or unseemly.
Jump to xref:v-wetware:CH59_Physical.adoc[Phenomic Mutations,window=_blank] to generate the mutation.
If the player rolls a defect for her persona, she gets the defect but must roll an additional non-defect mutation.

=== Mutation Effect 

[horizontal]
Duration:: 2-200 (2d100) hours
Safety:: 1/4 (TL / 4)
EXPS:: 100
Value:: 2000000

This pharmaceutical gives the persona a temporary mental or phenomic mutation effect.
The persona transiently acquires either a physical or psionic mutation.
Unlike the gradual onset of the permanent mutation, the mutation effect comes quickly reveals its power.

include::ROOT:partial$CH50_Table_Mutation_Type.adoc[]

Colour::
Colour deviations are a *permanent* side effect of this pharmaceutical.
The colour change immediately appears with a mutation effect.
This colour change can be as simple or as fancy as the referee desires.
Make a jump over to xref:iv-software:CH55_Appearances.adoc#_colour_your_whirled[Colour,window=_blank].

Mental::
The persona has acquired a psionic mutation effect.
The psionic mutation comes on with a ferocious headache and quickly reveals itself.
Jump to xref:v-wetware:CH58_Mental.adoc#_mutation_type[Psionic Mutations,window=_blank] to generate a fresh new mutation. 
*This mutation cannot be a defect.*
When the duration ends, the psionic mutation fades away.

Physical::
The persona has acquired a phenomic mutation effect.
The phenomic mutation violently explodes out of the persona's body.
The process is painful and unseemly.
Jump to xref:v-wetware:CH59_Physical.adoc[Phenomic Mutations,window=_blank] to generate the mutation.
*This mutation cannot be a defect.*
When the duration ends, the phenomic mutation withers away and falls off.

=== Transient Intumescence 

[horizontal]
Duration:: 1-6 (1d6) minutes
Safety:: 1
EXPS:: 100
Value:: 2000000

Transient intumescence rapidly swells an attribute beyond normal bounds.
This boost is unnatural and temporary.
A transient intumescence doubles the attribute that it affects.
An Awareness of 15 would become an Awareness of 30. 
Anthro attribute restrictions do not impede the transient intumescent.
A radical physical transformation accompanies intumescence.
A STR intumescence transforms the persona into a muscle-layered hulk.
An AWE intumescence dilates the eyes, ears and nose of the persona. 

Extreme attribute scores allow for abnormal performance.
Super Awareness may let the persona smell chemical formulas or see microscopic cracks. 
Super Mind may let the persona see Kirlian auras.
Spectacular Charisma may let the persona woo a large crowd with a magnificent oration.

The effects of this pharma are desirable to players, but abuse will lead to severe adverse effects for personas.
If the expedition has repeated access to this prescription, the referee may need to apply some specific limitations.
Long recovery times with debilitated attributes are suitable methods for game balance.
If the persona temporarily enjoyed a 24 DEX with the intumescent, she may suffer a 6 DEX for a few days after dosing.

include::ROOT:partial$CH50_Table_Periodic_Intumescent_Type.adoc[]

=== Permanent Intumescence

[horizontal]
Duration:: Permanent
Safety:: 2
EXPS:: 100
Value:: 10000000

This complicated pharmaceutical permanently enhances a specific persona attribute.
The new attribute scores do not instantly appear.
The persona must earn the improved attribute over time.
The attribute increase can arise through training, moe pharma, or extraordinary events. 
For example, a Strength increase would require a strength training regimen or may suddenly appear in a life or death STR test.
Repeated dosing with permanent intumescents can lead to permanent attribute damage. 

include::ROOT:partial$CH50_Table_Permanent_Intumescent_Type.adoc[]

=== Poison

[horizontal]
Duration:: Special
Safety:: 0
EXPS:: 1001
Value:: 42

Poisons are pharmaceuticals that do nothing but harm the patient.
They may be intentional poisons or pharma that has gone sour. 
Poison effects are very, very bad.
Poisons can very easily kill personas.
Poisons act as a deterrent for personas indiscriminately imbibing pharma.

Because the persona voluntarily administers the pharma poison directly into herself, the intensity of the attack is very high.
The intensity of pharma poison is 6-36 (6d6).
Reducing a persona's attribute to zero can lead to death.
None of the poisons are directly lethal, but their effects can be.

include::ROOT:partial$CH50_Table_Poison_Type.adoc[]

== Pharmaceutical Parameters
Explanations of the pharma parameters.

=== Duration 
This note describes the length of time that the effect of the pharmaceutical will last.
The onset is instantaneous, and the body will return to normal at the end of the duration.
Remember that side effects may have a longer duration than the pharmaceutical's effect.
A Permanent duration indicates a permanent change in the patient's body.
The player must roll those drugs with a range of times listed for a duration each time a dose is applied.

=== Safety 
Safety is simply the chance that the substance has no side effects.
The player makes a safety check for each dose taken.
Safety is usually equal to the tech level of the pharmaceutical.
A tech level 10 pharmaceutical has a 10% chance of no side effects.
If tech level is not part of your ruleset, the default is TL10.

=== EXPS 
EXPS are the experience points granted for identifying the prescription.
The player can determine the pharmaceutical's effect by winning a vet task roll.
Imbibing the pharma and correctly deducing the effect can also earn the EXPS.

=== Value 
The value is an indicator of the pharmaceutical's worth in eps.
The value is for a single dose.
If a prescription has three doses, then the prescription is worth three times the given value.
The value of pharmaceuticals can change according to the market's needs.

== Prescription

.*Prescription Checklist*
. <<_labelling,Labelling>>
. <<_delivery_method,Delivery Method>>
. <<_metabolism,Metabolism>>
. <<_side_effects,Side Effects>>
. <<_doses,Doses>>

=== Labelling
Prescriptions on mundane terra are usually well labelled.
In EXP, the apothecary that filled this prescription may have been deceased for a thousand years, or the language used no longer exists.
In short, prescription markings are essentially random. 
A living vet is the best bet for identifying an artifact pharmaceutical.

include::ROOT:partial$CH50_Table_Prescription_Markings.adoc[]

:art: drug_needleless.png
:width: 350px
:snark: You may not feel a little prick
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a syringe with no needle injecting into the skin. 

include::ROOT:partial$articulate.adoc[]

=== Delivery Method
The delivery method indicates the manner in how a dose gets inside the persona's physiology.
The delivery method includes an entirely uninformative colour for the pharmaceutical.
Jump to xref:iv-software:CH55_Appearances.adoc#_colour_your_whirled[Colour] to spice things up.
The colour indicates the pill colour or the container colour in the case of an inhaler.

include::ROOT:partial$CH50_Table_Method_of_Administration.adoc[]

=== Metabolism
There are many different persona types in EXP.
Metabolism is an optional rule that can throw some pharmacologic curve balls at the players.
Metabolism mostly has impacts on side effects. 
The metabolism interactions between family types (anthro, alien, robot) can lead to severe adverse reactions.

include::ROOT:partial$CH50_Table_Pharmaceutical_Intended__Metabolism.adoc[]

==== Anthro
This pharma is for for anthros.
Often the players will stop there and not worry about specific anthro types.
If the anthro type does not match the metabolism type of the pharma, the safety level decreases by half.
If an alien is using an anthro pharma, there is an automatic adverse effect.
Anthro metabolism pharma does not affect robots.

==== Alien 
This pharma is for a specific alien species.
Alien pharma is designed for a specific alien species and does not work between aliens.
The method of delivery will match the size of the alien.
Gigantic aliens would have larger pills and syringes.
If an anthro or a non-species alien uses this pharma, they automatically have an adverse effect.
Alien metabolism pharma does not affect robots.

==== Robot 
This pharma is a nanosynthetic meant only for robots.
Robot pharmaceuticals are like spectacular motor oils or bizarre fuels.
Liquid programming is another label for robotic materials that cause pharmaceutical effects.
For example, a robotic injection would appear more like a pneumatic dagger than a hypodermic needle.
Anthros or aliens that manage to dose themselves with robot pharma have a <<_poison,poison pharma>> adverse effect.

=== Side Effects 
Pharmaceuticals in EXP are complicated technological compounds that both diagnose and remodel the persona's body.
This level of invasiveness makes Side Effects very common with pharmaceuticals.
A Side Effect is an unexpected change in the body's chemistry that arises from taking a pharmaceutical.
The side effects here are all adverse effects. 
A side effect may be harmful or good, while adverse effects are all bad.

==== Safe Dosing
The higher the tech level and the higher the pharma's safety level, the less likely chance of an adverse effect.
If the campaign does not use tech level, the default value of TL 10 applies.

==== Chance of Safe Dosing
.Percent chance safe dose = Safety Level * Tech Level
****
% safe dose = 3 * 10 = 30%. 30 or less on 1d100 is a safe dose.
****

==== Adverse Effect
If the dosing is not safe, the persona will suffer an adverse effect.
The adverse effects themselves are not lethal, but their consequences can be.
The player rolls a brand new adverse effect for every unsafe dose imbibed.

include::ROOT:partial$CH50_Table_Pharmaceutical_Side_Effect.adoc[]

=== Doses
The more expensive the pharmaceutical is, the fewer doses per prescription.
One dose equals one effect. 
The number of doses could represent the number of pills in a bottle or puffs in an inhaler.

Vets can extend the number of doses in a prescription.
The more valuable the dose, the harder it is to split a dose. 

include::ROOT:partial$CH50_Table_Pharma_Dosing.adoc[]