= Exatmo Vehicles

[quote]
____
Ships sail from A to B across the C. Spaceships sail from A to B across __nothing__.
____

An exatmo (exterior to atmosphere) vehicle can function outside planetary atmospheres and sail off into the wild black yonder.
Space vehicles have specially sealed hulls, super-powerful engines, and technomagical drives that jump enormous distances.
Space vehicles can be the focus of a story or a tool to advance a story.

:art: have_space_will_travel.png
:width: 450px
:snark: Have space will travel
:artist: Ed Emshwiller, Hugh
:date: 1958, 2018
:license: CC BY-SA 4.0
:description: Drawing of two space suited humanoids floating around camper in outer space.

include::ROOT:partial$articulate.adoc[]

A space vehicle may be a piece of garbage discarded by a 1000 planet armada, or the priceless effort of a culture trying to escape its gravity well.
Space vehicles can be found, stolen, rented, lent or inherited by the expedition.
Space travel may be the campaign goal or just to mechanism to expand campaign horizons.
Either way, access to a spaceship brings the level of fantasy to galactic proportions.

.*Space Vehicle Checklist*
. <<_nomenclature,Nomenclature>>
. <<_hull,Hull>>
. <<_drives,Drives>>
. <<_fuel,Fuel>>
. <<_computer,Computer>> 
. <<_software,Software>>
. <<_defensive_systems,Defensive Systems>>
. <<_offensive_systems,Offensive Systems>>
. <<_crew,Crew>>
. <<_cargo,Cargo>>
. <<_space_chattels,Chattels>>
. <<_exps,EXPS>>
. <<_value,Value>>
. <<_operational_costs,Costs>>

== Nomenclature
The type of space vehicle reflects its function.
The space vehicle types starship and airship indicate different functions.
A starship does it all. 
A starship can travel between stars (special drive), between planets (exatmo drive) and enter the atmosphere (inatmo drive).
An airship can only maneuver within a planet's atmosphere and gravity (inatmo drive).
An airship could be a plane or a dirigible, but not a space vehicle.

Exatmo is a contraction of "exterior to the atmosphere." 
Exatmo is deadly to all life forms unless they are specifically protected.
Inatmo is a contraction of "in the atmosphere."
Inatmo is usually safe for lifeforms with ground, gravity and atmosphere. 
Special drives defy existing physics to transport the expedition across the vastness of space.

include::appendices:partial$space_vehicle_nomenclature.adoc[]

== The Build 
Space vehicles are neither accurate in detail nor aerospace specifications.
A space vehicle is a tool for role-playing. 
It is not an end itself.
The build creates random space vehicles that supply the basic necessities of space travel.
The only guarantees are a hull, drives, computers, and life support.
The layout and appearance depend on the referee and players.

== Hull
A hull is the outer covering of a seed. 
A space vehicle hull encases the ship's contents, protecting them from exatmo.
The first assumption about space vehicles is that they have hulls.
The shape of the hull is determined entirely for dramatic effect.
Space vehicles shaped like pirate ships are acceptable if this fits the referee's milieu.
The ship's hull is an intimate part of the ship's life support and gravity systems. 

.*Hull Checklist*
. Size
. Composition
. Strength

:art: danger_in_deep_space_ships.png
:width: 250px
:snark: Different sized space vehicles
:artist: Louis Glanzman
:date: 1953
:license: CC BY-SA 4.0
:description: Space vehicle docking at space station with planet in background.

include::ROOT:partial$articulate.adoc[]

=== Hull Size 
Hull size determines the space vehicle size.
The bigger the hull size, the bigger the space vehicle.
Hull size represents the amount of volume displaced by the space vehicle.
Hull size does not correlate with reality in any way.
Metric tonnes of displacement sounds lends a sciency fiction maritime feel to hull size.

include::ROOT:partial$CH52_Table_Hull_Size.adoc[]

=== Hull Composition 
Hull Composition is more of a descriptor.
All hulls function the same except regarding maintenance.
Most space vehicles will be composed of metal, plastix, and ceramic alloys.
Smart hulls are self-maintaining and slowly repair themselves.
Smart hulls offer no combat benefit at all. 
They allow the expedition to avoid the expenses of hull refitting.

include::ROOT:partial$CH52_Table_Hull_Composition.adoc[]

=== Hull Strength 
Hull strength determines the hull's ability to prevent damage to the ship's interior components.
It is a mix of composition strength, shape and redundancy.
The hull strength is also the hull Defence Rating (DEF). 
The hull cannot be damaged before depleting the hull's AR. 
This depletion can happen fast in space vehicle combat.

include::ROOT:partial$CH52_Table_Hull_Strength.adoc[]

== Drives
Like any vehicle, a space vehicle needs engines to travel from one point to another.
However, space vehicles are not so provincial as to call their power sources engines.
Space vehicles call their engines drives.
The term drive includes all the components needed to propel the space vehicle.

:art: spacevehicle_reentry.png
:width: 450px
:snark: Entering atmosphere at high speed
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a stylish spaceship showering flames on reentry.

include::ROOT:partial$articulate.adoc[]

.*Drive Checklist*
. <<_drive_configuration,Drive Configuration>>
. <<_drive_power,Drive Power>>

=== Drive Configuration
The configuration of the drive types determines the space vehicle type.
The referee should always choose the kind of space vehicle that best suits the story.

include::ROOT:partial$CH52_Table_Drive_Types.adoc[]

Starship::
The starship does it all.
A starship can take off and land on a planet's surface, travel from planet to planet and jump from star to star. 

Starcruiser::
This space vehicle can't enter an atmosphere but can travel anywhere else in space.
The starcruiser also has the name star bus or simply a cruiser.

Spaceship::
The spaceship is limited to work within the confines of one star system.
This vehicle can cross into the atmosphere of any planet in the system.
The spaceship also has the name shuttlecraft or space bus.

Spacecruiser::
The spacecruiser only operates in the vacuum of space within one star system.
This space vehicle cannot enter the atmosphere of a planet or jump to another star system.
The spacecruiser also has the name transfer craft or space tug.

Starjumper::
The starjumper only has a special drive and can only jump from one location to another.
The starjumper cannot enter the atmosphere and cannot travel between planets.
The starjumper is hardened for exatmo but can only maneuver around a planet.
The starjumper also has the name transfer station or transport satellite.

Airship::
An airship only has an inatmo drive and cannot travel outside of a planet's orbit or atmosphere.
Airships also have names like plane, dirigible, or rocket.
Mundane terra has a few airships that can drop off satellites and crash back to terra aqua.

:art: space_cruiser_slick_looking.png
:width: 450px
:snark: Even a space tug can look good.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Sleek pointy space ship against the outline of a planet.

include::ROOT:partial$articulate.adoc[]

=== Exatmo Drive
The exatmo drive maneuvers the ship through the vacuum of space and is the defining feature of a space vehicle.
The exatmo drives are sciency fiction fast.
The larger the drive size, the more powerful the exatmo drive.
The exatmo drives are essential in space vehicle combat.
They can maneuver a ship well beyond survivable physics in combat. 

Exatmo drives will be one of two types: fusion or gravetics.
The player creating the space vehicle may choose between the two.
Both are equally efficient at moving the ship around exatmo.
Neither type of exatmo drive can function within the atmosphere.
Fusion and gravetics drives require an absence of gravity and atmosphere to function.

Both the exatmo drives function equally well.

=== Inatmo Drive
The inatmo drive maneuvers the ship through the atmosphere and gravity of planets. 
These are the in-atmospheric drives of the ship.
Inatmo drives require both atmosphere and gravity to function, and they do not work in space. 
A space vehicle that does not have an inatmo drive cannot enter an atmosphere (safely).
A space vehicle with both inatmo and exatmo drives can enter and exit a planet's atmosphere.

All of the inatmo drive types function equally well.

include::ROOT:partial$CH52_Table_Inatmo_Drive_Type.adoc[]

==== Antigrav Inatmo Drive
Classic sciency fiction anti-gravity units suspend and maneuver the ship above the planet's surface.

==== Balloons Inatmo Drive
Once in the atmosphere, balloons will automatically billow out and fill themselves with a computerized mixture of gases.
The ship is maneuvered about by altering the buoyancy of the various balloons.

==== Chutes Inatmo Drive
This spaceship ejects an enormous collection of kites, and parachutes, which computers control to maneuver the ship while fuel supplies last.
The spaceship can employ prevailing winds to lift off.

==== Jets Inatmo Drive
A multitude of fuel-burning jets (or rockets) maneuvers the ship in the atmosphere.

==== Props Inatmo Drive
Large airscrews located about the ship operate at various power levels to attain maneuverability.

:art: spacevehicle_deep_space.png
:width: 450px
:snark: Oh look, a wormhole!
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of a space ship heading towards a hole in the time space continuum.

include::ROOT:partial$articulate.adoc[]

=== Special Drives
Special drives technomagically fling the starship instantly across space.
Special drives replace generational space vehicles and unhealthy cryosuspension.
Special drives are the cornerstone of sciency fiction space operas.
The speed of light is just not good enough.
The logistics of the 2000 year space flights are the root cause of special drives.
The special drives turn insurmountable distances into science fiction pulp.

All special drives function equally well.

include::ROOT:partial$CH52_Table_Special_Drive_Type.adoc[]

==== Bloater Special Drive
A bloater drive expands the ship and its contents by increasing the space between its molecules.
The expansion continues until entire planets, stars, and galaxies can pass between the ship's molecules.
This bloating continues until the destination point is near the ship's hull.
The ship then begins to deflate around its new destination point, arriving instantly without moving.

==== FTL Special Drive
Faster than light travel plays havoc with many paradoxes.
FTL travel is a convenient way to get from point A to point B and advance the story.

==== Hyper Special Drive
Also known as jump drives.
Anything hyper does more than anything else in the same amount of time.
So the hyperdrive covers light years faster than a non-hyper drive would.

==== Psi-Flip Special Drive
The psi-flip transports the ship to the location thought of by the navigator.
This drive requires a most precise mental image and corrects the reality so that the idea of the new location becomes true.
Once the psionic navigator has convinced her mind that she is somewhere else, the psi-flip drive corrects reality.
Psi-flip is known as a mind flip drive or a flip drive.
To navigate a psi-flip special drive requires 18 MND or a specially mutated persona.
Robots cannot operate a psi-flip special drive.

==== Time-Slip Special Drive
Another one of the mystically bizarre space travel devices is the time slip.
This drive system drops its payload into time limbo (likely hyperspace).
While in hyperspace, the drive scans through moments in the past/future until it finds a moment better aligned for its travel purposes.
The drive then re-enters the original space-time but at its desired location.

==== Transmat Special Drive
The transmat drive exploits electron probability to cover plot improving distances.
At some point, some electron of the ship will be near the location where they want to be.
Once this occurs, it is just a __matter__ of reorienting the ship's molecular parts with the vagrant orbital electron particle.
A transmat is also known as a probability drive.

==== Warp Special Drive
Warp drives operate under the premise that space can fold up, bringing stars much closer together.
Once space-time is folded, the space vehicle passes through the base of the fold.
This distance travelled is short, but the distance covered is enormous.
Warp drives are also called origami or laundry drives.

=== Drive Power
The drive power represents how powerful the drive is.
The more powerful the drive, the faster, further the drive goes.
Each drive type has its own power level between one and ten.
The player rolls drive power from 1-10 (1d10) for each drive the space vehicle has.
The player may roll three times for a starship (exatmo, inatmo, and special) or once for a space tug (exatmo only).
The more powerful the drive is, the more hull space it occupies.

include::ROOT:partial$CH52_Table_Drive_Level_and_Size.adoc[]

Drive Power Level::
The player rolls drive power from 1-10 (1d10) for each drive the space vehicle has.
The player must record the drive power level for each drive type, i.e., Inatmo 4, Exatmo 2 and Special 6.
The drive power determines the drive size and drive performance.

Drive Size::
The more powerful the drive, the more hull space it occupies.
The larger the space vehicle, the larger the drive that moves it.
The tonnage of a drive is 1% of the hull size per level of drive power.
Each drive has its own power level, and therefore each drive occupies a unique amount of hull.
These individual drive wates are cumulative. 
A space vehicle with a 100-tonne hull has a power level 10 exatmo drive (zoom zoom) and a power level 5 special drive.
The drives occupy 15 tonnes of hull space.

Performance::
Each drive has a metric that each drive's power level multiplies.
A level 5 exatmo drive can move at 0.5 C (speed of light) and pull 5 G maneuvers. 
A level 5 inatmo drive can move at Mach 5 through the sky of a 5 G planet.
A level 5 special drive can jump 100 light-years.

Special Drives are Special::
The special drive can travel 20 light-years (LY) per level.
A level 6 special drive can travel 120 light-years in one moment.
The referee can change to what works best for the milieu and campaign, i.e., parsecs or astronomical units.
A special drive jump is usually instantaneous.
The referee can change to what works best for the milieu or campaign, i.e., days or weeks per jump unit.
Regardless of the special drive type, the vessel travels through xref:appendices:generic_mythos.adoc#_the_spaces[hyperspace,window=_blank].. 
There is no communication within hyperspace or between hyperspace and physical space.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Fuel
Fuel seems like a trivial issue for a gallant expedition out to save the universe.
Energy is the limiter of all things, especially space vehicles.
Fuel is a tool to make gameplay more challenging and the storytelling more interesting.
The players can dispense with fuel's rules if desired.

.*Fuel Checklist*
. <<_fuel_type,Fuel Type>>
. <<_fuel_level,Fuel Level>>
. <<_fuel_consumption,Fuel Consumption>>

=== Fuel Type
A space vehicle's fuel type is a fun descriptor.
It is entirely up to the referee if gas from one vessel is compatible with gas from another vessel.
A space vehicle will only have one fuel type.
Each drive type will use the same fuel type.
The drive types may use the same fuel, but each drive type has different needs and rates of consumption.
Whether the space vehicle has a full tank, a half tank or vapours is up to the referee and the milieu of the campaign.

For more information about fuel and energy jump to the generic mythos section -> xref:appendices:generic_mythos.adoc#_energy_and_power[Energy and Power,window=_blank].

include::ROOT:partial$CH52_Table_Fuel_Type.adoc[]

//.1(5)+.2(10.5)+.2(22)+.3(220)+.1(900)+0.05(3750)+0.04(21000)

:art: spacevehicle_gigantic.png
:width: 450px
:snark: Rocking space ship
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of very big space ship built around a rock.

include::ROOT:partial$articulate.adoc[]

=== Fuel Level
The drive types the space vehicle has, the more fuel the space vehicle may have.
Each drive type contributes an amount to the shared fuel storage.
The fuel storage occupies hull space on the vessel.
The fuel amount also determines the range of the space vehicle.
 
include::ROOT:partial$CH52_Table_Fuel_Storage.adoc[]

Fuel Level::
The fuel level indicates how much fuel each drive type contributes to the total fuel level.
For example, a spaceship has the following fuel levels: inatmo 8, exatmo 9 and special 3.
The total fuel level is 20, which determines the fuel storage and fuel range.

Fuel Storage::
Fuel storage indicates the amount of space that the fuel occupies in the hull of the vessel.
The total fuel level of all the drive types determines the size of the fuel storage.
Each fuel level occupies 1% of the hull displacement.
A fuel level of 20 occupies 20% of the vessel's hull space.
If this were a 100-tonne spaceship, a fuel level of 20 would occupy 20 tonnes of hull space.

Range::
The range indicates how long the space vehicle can run until it runs out of fuel.
The fuel level indicates the number of months that the ship can operate with a full tank.
A vessel with a fuel level of 20 would have a range of 20 months. 
The following section on fuel consumption explains the concept of fuel range as months.

=== Fuel Consumption
Fuel consumption varies with the drive type and how the expedition is using it.
Combat fuel consumption is much higher than tourist or haulage fuel consumption.

Both fuel consumption and fuel range are in units of time.
Calculating light-years, kilometres, or parsecs became overwhelming and tedious.
Using date time for monitoring fuel consumption allows for limits on fuel (if the campaign desires) and allows for more storyful measurements.

Each month of range consists of 30 days of fuel use.
A month of range is for that specific space vehicle.
The range takes into account the vessel size and all fuel necessary for the task at hand.
Choosing a time of fuel burn proved to be the easiest way to keep track of fuel consumption.

Consider a special drive jump as an example.
A special drive jump uses one month of fuel and moves the ship as many light-years as the special drive level indicates.
A 10 tonne or a 100-tonne vessel would use one month of their fuel storage to make the jump.
This method allows the ship to make several jumps before refuelling but does not bog the players down with astronomical calculations.

include::ROOT:partial$CH52_Table_Fuel_Consumption.adoc[]

So a space vehicle with 15 months of fuel could make 15 special drive jumps or compete in 60 turns of space combat or 90 minutes of inatmo flight.
A space vehicle drops out of combat if there is less than one week of fuel onboard.
Running out of fuel during combat is a victory condition for the vessel that does not run out of fuel.
A space vehicle cannot jump if there is less than one month of fuel onboard.

The nature of refuelling depends on the referee's milieu and campaign.
Some fuel types may be ubiquitous materials that one skims off the local gas giant.
Other fuel types may require days of retooling by highly skilled space mechanics.

== Computer
The computer is the vessel, and the vessel is the computer.
The computer integrates deeply with every system on the space vehicle.
The computer manages special drive jumps, combat maneuvers, life support, gravity and more.
A space vehicle requires a computer and crew to function.
Pilots, navigators and engineers work on the space vehicle through the ship's computer.
Software can replace the crew of a space vehicle, but there are no manual space vehicles.

Life support protects the vessel's cargo, but it is really there for the ship's computer.
A dead computer is a dead space vehicle.
Cargo and crew come and go, but ship's last generations.

.*Installing the ship's computer*
. Computer Level
. Computer Size

The ship's computer is distributed throughout the entire space vehicle.
There may be a central location for interaction with the ship's computer.
This central computer interface could be called the ship's bridge, but a ship's bridge is not strictly necessary.
Personas acting as the ship's crew can be located on a bridge or distributed about the vessel.

A ship's computer is not an autonomous Intelligence. 
However, it may have attitude and personality.
The referee may consider the ship's computer a referee persona.
However, it will be friendly and helpful for vessel operations.
The expedition may interact with the computer via devices or voice interaction.

=== Computer Level
The higher the computer level, the more powerful it is.
A higher ship's computer level improves everything from the galley food to combat maneuvers. 
The higher the level of the computer, the more complicated the software it can manage.
The computer level ranges from 1-10 (1d10).

The bigger the ship, the larger the computer.
The computer size and wate represent all components, wiring, peripherals, terminals, processors and doohickeys.
The ship's computer occupies 1% per level of hull space.
So a 200-tonne starship with a level 4 computer would have 8 tonnes of computer equipment on board.

:art: swirling_opportunity.png
:width: 550px
:snark: Remember where you are standing.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Swirling image of a many stars and galaxies.

include::ROOT:partial$articulate.adoc[]

== Software
Computer software broadens the ship's computer skills in specific areas.
All space vehicles automagically maintain life support, gravity and keep things from exploding.
A space vehicle needs direction from personas to get up and go.
A ship's computer is artificially intelligent but not autonomously intelligent.
The computer level determines the effectiveness of the software.

The software will include any hardware and connections it needs to function on the vessel.
A software package may physically bolt onto the space vehicles or be auto-downloaded from https://github.com/mobilehugh/EXP_Documents[GitHub].

There is no limit to the amount of software a ship's computer can store, but there is a limit to the number of programmes that it can simultaneously operate. 
A space vehicle is limited to using one software title per level of computer at once.
Players will have to make choices about what is the most critical package to run.

=== Crew Replacement Software
Crew replacement software indicates programmes and mechanical devices that can replace essential crew.
In some circumstances, the crew software replaces the required crewmember completely.
In other circumstances, the programmes direct a persona or robot on how to operate the system.

A space vehicle is limited to using one software title per level of computer at once.
Players may have to make choices about what is the most critical software to run.
A low-level ship's computer may always require a persona crew member to function.

The table for crew replacement software is a bit different.
The table used to generate software is a __Chance__ Table. 
The player rolls decidice (1d100) for every programme, and there is a chance of having it.
A level 3 computer has a 60% chance of an astrogation programme and a 15% chance of a piloting programme.
The player rolls once for every item on the chance table, i.e., she makes a separate roll for astrogation, navigation etc.

include::ROOT:partial$CH52_Table_Software_Crew.adoc[]

Astrogation::
This programme allows any persona to pilot the special drives.
The persona works directly with the ship's computer to plot special drive jumps. 
When an astrogator uses this software, she can reduce fuel usage for jumps (2 weeks) or decrease the duration of time in hyperspace.

Engineering::
This software title allows any persona to carry out ship maintenance and repairs. 
The ship's computer directs personas what needs doing, where it needs doing and how to do it.
Combining engineering crew replacement with a robot can make for nearly seamless space vehicle operations.
A mechanic working with this software gets bonuses on her task rolls for ship-related maneuvers.
Ship repair and maintenance task rolls get a bonus of +5 per level of the ship's computer.

Navigation::
This software title allows any persona to pilot the inatmo and exatmo drives.
The persona works directly with the ship's computer via specialized control devices (steering wheel). 
A pilot or navigator working with this software can optimize the programme, saving fuel or making unorthodox maneuvers.
Combat fuel usage is unaffected by this teamwork.

Piloting::
This programme allows any persona to hand over all maneuvers to the ship's computer completely.
Piloting includes navigation, astrogation and combat maneuvers. 
Piloting software is very advanced, and it may have its own personality that interacts with the personas and ship's computer.

=== Miscellaneous Software
Miscellaneous software consists of programmes that vary from functional to sublime.
The programmes include both the hardware and software that the packages need to operate.
The programmes allow the ship's computer to carry out the task and help personas perform maneuvers.

When a persona can use the ship's computer for a maneuver, she enjoys a bonus of +1 per computer level.
For instance, a persona who can use the etiquette programme to help cater a fancy dinner.
 If the computer level is 5, the persona gets a +5 DD bonus when maki9ng the meal. 

The player makes one roll per level of the ship's computer. 

include::ROOT:partial$CH55_Table_Space_Vehicle_Software.adoc[]

== Defensive Systems
A ship's defences comprise anything that protects the contents of the space vehicle.
The defences include computer programmes and structural protections.
For example, the computer assists with evasive maneuvers, the hull is fortified, and there is a force field.
Life support, gravity and hull are considered defensive systems. 
Life support works together to defend against the harshness of exatmo.
Intentional defences, like ECM and shields, are designed to protect the ship in combat.

To learn how defensive systems work in combat jump to 
xref:combat:combat_and_exatmo_vehicle_intro.adoc[Space Vehicle Combat,window=_blank].

The table used to generate defensive systems is a __Chance__ Table. 
The player rolls decidice (1d100) for every defence on the list.
A level 3 computer has a 30% chance of electronic countermeasures and a 6% chance of active defences.
The player rolls once for every item on the chance table, i.e., she makes a separate roll for ECM, Shields etc.

include::ROOT:partial$CH52_Table_Defences.adoc[]

=== Life Support
Life support maintains a comfortable environment for the organic and delicate inorganic contents of the ship.
The most straightforward description is an 'outer space air conditioner.'
Destroying the life support system exposes all of the hull's contents to the deadly vacuum of space.

Life support is entirely self-contained and is impossible to tamper with and hard to destroy.
The life support system functions entirely unknown for the players until something goes wrong.
Life support, gravity, Defence Rating, hull and shield (if present) are all part of the <<_life_support_onion,Life Support Onion>>.

=== Gravity System
Gravity maintains a safe, comfortable and convenient gravitational force throughout the space vessel.
The gravity system allows the personas to work in comfort and protects them from extreme maneuvering gravities.
A space vehicle's exatmo drives generate gravities that would kill any organic or delicate inorganic persona.

Gravity works on walkways, workspaces, cargo holds, cabins, and the exterior hull.
The ship's computer controls gravity at a constant attraction of 1g with local adjustments between 0.5  and 1.5 gravities.

Gravity is entirely self-contained and is difficult to tamper with and hard to destroy.
The gravity system functions entirely unknown for the players until something goes wrong.
Life support, gravity, Defence Rating, hull and shield (if present) are all part of the <<_life_support_onion,Life Support Onion>>.

=== Hull
The hull defines the space vessel.
The hull protects the contents of the space vehicle from the lethal vacuum of space.
Every space vehicle system is part of the hull, and the hull contains every space vehicle system.

The hull also determines the shape of the space vehicle.
The players decide the shape of their space vehicle.
Most often, the hull is an oblong spheroid that contains the space vehicle's contents.
A space vehicle that can enter the atmosphere may have a more streamlined appearance. 

The hull is the structure that maintains the ship's gravity and life support.
Life support, gravity, Defence Rating, hull and shield (if present) are all part of the <<_life_support_onion,Life Support Onion>>.

=== Defence Rating 
The Defence Rating indicates the strength of the space vehicle's hull.
The Defence Rating is in addition to the shape and structure that the hull offers. 
The hull and Defence Rating have an intimate relationship.
The Defence Rating protects the hull and makes its appearance as the hull strength during hull creation.

The Defence Rating of the hull determines the structural resilience of the hull during combat. 
Attack rolls must be higher than the hull's Defence Rating to damage the vessel.
Damage reduces Defence Rating.
Once the Defence Rating drops to 420, it no longer protects the hull.

The Defence Rating is a component of the life support system.
Life support, gravity, Defence Rating, hull and shield (if present) are all part of the <<_life_support_onion,Life Support Onion>>.

=== ECM
Electronic countermeasures (ECM) manipulate the electromagnetic spectrum to defend the ship.
A more powerful ship's computer makes for more effective electronic countermeasures.
ECM is a combination of programming and equipment.
ECM is integrated throughout the ship and connects to every ship system.

ECM uses all kinds of electronic deception to both defend or attack.
Personas can use the ECM unit to defend the ship or attack another ship.
One ECM unit cannot do both in the same combat turn.

Personas can work in unison with ECM to protect the space vessel.
For example, a mechanic with ECM 2 working with a level 3 computer creates a total ECM level of 5.

Electronic countermeasures are not part of the life support onion.

=== Shields
The shields protect the hull Defence Rating from energy and kinetic attacks.
These are the classic sciency fiction shields that handsome captains raise just before combat.
The defensive shield can be a force field or a structural mechanism. 
Both mechanisms work by distributing the destructive force across the entire hull.
This faux scientific diffusion effectively dampers the damage.
The shields have an active mode that the players turn on to thwart intentional damage.
Shields also have a passive mode, and when present, they are part of the life support onion.
Life support, gravity, Defence Rating, hull and shield (if present) are all part of the <<_life_support_onion,Life Support Onion>>.

=== Guns
A gun is a defensive tool in space vehicle combat.
A gun does not sound like a defensive tool, but occasionally the best defence is a good offence.
Guns on space vehicles are anti-personnel air lock defence weapons.
In ship-to-ship combat, a gun is an ineffectual weapon.
However, to prevent boarding or airlock intrusion, a mounted gun can be very effective.
To create the airlock gun jump to xref:hardware:CH46_Guns.adoc#_gun_type[Guns,window=_blank]

Guns are not part of the life support onion.

.*Airlock Defensive Guns*
* can swap between inside and outside the airlock
* operate inatmo or exatmo
* Can be controlled by personas or ship's computer
* has unlimited ammo to defend against boarding
** ammo may deplete for game balance and fun
* has an AR equal to the ship's hull
* damaged by Hull AR damage or airlock damage

=== Active
Active defences are fancy mechanisms that attack incoming attacks.
Active defences are sometimes called actives.
They can eject missiles, shrapnel, energy blasts, lazer matrices, or crystalline discharges. 
All active defences function equally, and the description is the player's choice.
Their goal is to dissipate, prematurely detonate, or destroy incoming attacks.
Active defences work against grenades, mines, or artillery.
Actives do not work against boarding, ramming, ECM, or naval artillery.

Active defences are not part of the life support onion.

.*Notes about active defences*
* Active defences are automated
** Gunnery skilled personas can help
* Active defences work inatmo and exatmo
* Actives cannot be weaponized

=== Life Support Onion
The life support onion is the layering of the space vehicle defences that protect the contents of the hull.
The innermost part of the onion is life support itself. 
Before anything can damage or impair life support, it must work its way through all the outer layers. 

Before damaging life support, the outer layers of the onion must be disabled or destroyed. 
The outermost layer of the onion is the ship’s shields. 
If the ship does not have shields, the outermost layer of the onion is the hull Defence Rating. 
The hull Defence Rating must fail before the hull can be damaged. 
The hull must fail before gravity control can be damaged. 
Gravity control must fail before life support can be damaged.

include::ROOT:partial$CH52_Table_Life_Support_Onion.adoc[]

== Offensive Systems
Space vehicle combat is highly discouraged due to the high probability of persona mortality.
Offensive systems are for damaging and disabling space vehicles. 
Due to the value of space vehicles, they rarely suffer intentional destruction.
The offensive systems are tools for weakening a vessel in preparation for boarding.

A space vehicle may have offensive systems because they are pirate scum.
A space vehicle may have offensive systems to fight pirate scum.
There is no official EXP military space vehicle.
A vessel that has naval artillery, mines, or missiles becomes a military space vehicle.

To learn how offensive systems work in combat jump to 
xref:combat:combat_and_exatmo_vehicle_intro.adoc[Space Vehicle Combat,window=_blank].

The table used to generate offensive systems is a __Chance__ Table. 
The player rolls decidice (1d100) for every attack on the list.
The referee goes down the list rolling once for each attack type.
So a space vehicle with exatmo drive level 4 would have a 20% chance of ramming, a 16% chance of ECM, and a 2 percent chance of Naval Artillery.

include::ROOT:partial$CH52_Table_Attacks.adoc[]

=== Boarding
Boarding lines up airlocks to prepare for a breach and boarding of the target vessel.
All space vehicles can attempt to dock with another vessel forcibly.
Boarding is congenial ramming.
Boarding only works exatmo (exterior to atmosphere).
Once connected, the attacking crew will breach the airlock of the target ship and then board.
This method of attack preserves the target space vehicle, generating hostages, free cargo, and is a lot more fun.

=== Ramming
Ramming is aggressive boarding casting caution to the solar wind.
A ramming space vehicle has a specialized airlock that can attach to any part of the target ship's hull.
Once attached, the attacking party must breach the hull or airlock to enter the ship.
Ramming is similar to boarding, except that ramming has lots of crunching and scraping noises.

=== ECM
ECM is the acronym for electronic countermeasures.
ECM units battle for control over the electromagnetic spectrum.
In space vehicle combat, ECM is the battle for control over the electronics of the other vessel. 

ECM uses all kinds of electronic deception to both defend or attack.
So the personas can use the ECM unit to defend the ship or attack another ship.
One ECM unit cannot do both in the same combat turn.

Personas can work in unison with ECM to protect the space vessel.
For example, a mechanic with ECM 2 working with a level 3 computer creates a total ECM level of 5.

=== Grenades
Grenades in space!
In space vehicle combat, grenades are tiny bombs exploding against the hull to damage the internal mechanisms of the ship.
Grenades launch their attack by mini-missile or mini-mine.

They do not enjoy the area of effect attack of their terrestrial counterparts.
Grenades require a successful attack roll to inflict damage.
If the attack roll is unsuccessful, the grenade detonates ineffectively and silently in space.
Grenade delivery systems have diminutive titles because they only deliver grenades. 
Naval missiles and naval mines deliver bombs.

include::ROOT:partial$CH52_Table_Spacer_Grenade_Type.adoc[]

=== Bombs
Bombs are lethal attack weapons.
Bombs are both dangerous and destructive.
Bombs delivery systems are either missiles or mines.
Missiles and mines can also be called naval missiles or naval mines.
Having this type of offensive system indicates a combat vessel of some fashion.

In space, bombs are an area of effect weapon.
Bombs need only explode near the ship's hull to inflict damage to the contents within.
A bomb is guaranteed to damage a target with a successful attack roll.
Every bomb gets a second chance to damage a vessel just by getting close enough. 
If the raw attack roll of a missile or mine is higher than 500, the target is still damaged.

include::ROOT:partial$CH52_Table_Spacer_Bomb_Type.adoc[]

=== Artillery
The purpose of ship artillery is to damage the target ship so that it ceases to function.
This goal is to wear down shields and armour and directly damaging the hull if necessary.
In space combat terms, artillery is very tiny and is only in range when vessels are boarding or ramming. 
Naval artillery is the literal big gun of space combat.

In space combat (exatmo), artillery must win an attack roll to damage the target vessel.
While inside the atmosphere (inatmo), artillery functions as an area of effect weapon on terrestrial targets.
Artillery cannot cross into the atmosphere or out of an atmosphere.

Ship artillery has the same ranges, damages, and effects as the artillery it is modelled after.
Energy-based weapons can fire as long as the ship has fuel, and artillery requiring ammo will have 100 times the regular supply.

include::ROOT:partial$CH52_Table_Spacer_Artillery_Type.adoc[]

=== Naval Artillery
Naval artillery is for destroying the target ship.
Naval artillery is not for softening the target vessel.
The sheer force of naval artillery leads to the target's destruction.
One use of naval artillery exhausts a whole day's worth of fuel.
Naval artillery requires a gunnery program and a gunner.
Without this complement, the ship cannot fire its naval artillery.

NOTE: *Artillery are big guns. Naval artillery are big big big guns.*

Naval artillery is more deadly than regular deadly artillery.
Naval artillery inflicts three times the damage and has 100 times the range.
Naval artillery only works exatmo and cannot fire inatmo or cross into an atmosphere.

The player rolls on the spacer artillery table above and then does arithmetic as directed below.

include::ROOT:partial$CH52_Table_Naval_Artillery.adoc[]

include::ROOT:partial$CH52_Table_Example_Naval_Artillery.adoc[]

== Crew
Space vehicles vary in size from personal craft to city-sized leviathans.
They can have fantastical drives that flit them across the stars and computers that weigh tonnes.
An essential element is still the crew.
EXP is about personas and has a persona focus. 
Space vehicles are tools to help tell stories by moving personas and cargo from place to place. 


TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

The crew of a space vehicle can be composed of aliens, anthros, or robots.
Every space vehicle has an essential crew.
Without the essential crew, a space vehicle will not move.
A space vehicle will have the essential crew on board or the software programmes to replace them.

.*Essential Services*
. Pilot
. Astrogator (for special drive)
. Engineer

Some space vehicles will require even more crew. 
Some space vehicles will require multiple engineers. 
These three are the essential crew needed.

:art: crude_replacement.png
:width: 450px
:snark: Pilot in a drum.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Spaceship cockpit with humanoid robot pilot and woman navigator.

include::ROOT:partial$articulate.adoc[]

=== Pilot 
The pilot is an essential crew member, and a space vehicle cannot function without one.
The pilot is the overseer of all the ship's functions.
She is responsible for executing planetary maneuvers, star system maneuvers, combat maneuvers, ship procedures, and ship authority.
All of these tasks require the intimate cooperation of the ship's computer and the pilot.
Without a pilot, the ship is a motionless piece of space opera potential.
No ship cannot travel without a pilot.
Space vehicles can have personalities and attitudes, but they are *not* autonomous lifeforms. 

Every 10000 tonnes of displacement requires an additional pilot (co-pilot).

.*Qualified Pilots*
. Mechanic vocation with pilot skill
. Nothing vocation with pilot skill
. Exatmo transport bot

=== Astrogator 
The astrogator is an essential crew member if the ship has a special drive.
The astrogator operates the ship's special drive, and a special drive cannot function without one.
The astrogator works with the ship's computer to coordinate a safe special drive jump.

.*Qualified Astrogator*
. Nomad vocation
. Knite vocation
. Mechanic vocation with astrogation skill
. Nothing vocation with astrogation skill 
. Exatmo transport bot

=== Engineer
The engineer is an essential crew member, and a space vehicle will malfunction without one.
The engineer does essential repairs and maintenance on the space vehicle.
A space vehicle may jump once or engage in combat once without an engineer.
Afterwards, it will not function.
Without maintenance, the space vehicle will cease to operate.

The engineer maintains tonnes of drives, complicated airlocks. 
There is a lot that will go wrong.
It is the responsibility of the ship's mechanic to monitor the computer's maintenance programs, to program repairs, and to pick up the wrench herself occasionally.

A space vehicle requires an extra engineer for every 9000 tonnes of hull displacement.

.*Qualified Engineer*
. Mechanic vocation
. Maintenance robot

=== Gunner 
Gunners operate the combat equipment: artillery, naval artillery, mines, active defences, missiles, and shields.
None of the listed equipment will function without a gunner or a software replacement.
Combat robots can replace a gunner without the need for a gunnery program.
Combat robots can operate one active combat device for every 4 points of Intelligence.

.*Qualified Gunner*
. Mercenary vocation
. Spie vocation
. Combot

=== Doctor 
Any space vehicle that has organic passengers requires a ship's doc.
Guests, soldiers, cattle without proper vet attention will get sick in deep space.

.*Qualified Ship's Doc*
. Veterinarian vocation
. Diagnostics veterinarian robot

:art: spacevehicle_QE_lots.png
:width: 450px
:snark: QE 1113
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Drawing of luxury cruise liner space ship orbiting a planet.

include::ROOT:partial$articulate.adoc[]

=== Steward 
Guest laden starships require a ship's steward.
The steward changes linen, washes clothes, and generally makes space travel bearable for guests.
Without a steward, guests will undoubtedly be in a bad temper and may even rebel during a long trip.

A space vehicle requires one steward for every 50 passengers.

.*Qualified Steward*
. Nothing vocation with SOC<400
. Social robot
. Domestic janitorial robot

=== Administrator 
One optional crew member who the expedition may actively shun is the ship's administrator.
The ship's administrator will arrange docking papers, interpret cartage laws, balance accounts, designate cargo allotments, and fill in as the ship's legal advisor.

.*Qualified Administrator*
. Nothing vocation with INT <12
. Transport robot
. Datalyzer robot

=== Diplomat 
The diplomat is good at being excruciatingly polite, even to the most horrific of alien species.
A diplomat will attempt to keep the crew, the guests, (and especially the personas) from offending rarely encountered cultures.

.*Qualified Diplomat*
. Nothing vocation with CHA >12
. Biologist with culture and sociology
. Social robot

== Cargo
Cargo is the tonnage remaining after deducting the space taken up by drives, fuel, and computers.
The cargo does not immediately become space for cargo.
Other space vehicle features occupy potential cargo space.
These are cold storage, workspaces, cabins, and corridors.
All of these cargo space deductions are essential for an operational space vehicle.
The player must account for all the following items as she sees fit.
Plotting out the cargo and operational essentials has the most significant impact on space vehicle design. 
It is during this process that the players create a simple map of the space vehicle. 

=== Access Port (mandatory)
Allows access to the space vehicle when inatmo. 
If the space vehicle has an airlock, the airlock can function as the inatmo access portal. 

=== Workspaces (mandatory)
Workspaces are even more mandatory than the essential crew.
Workspaces are not the same as cabins.
Each crew member (pilot, engineer, astrogator) requires a half tonne of workspace.

=== Airlock
An airlock allows passengers, crew and stuff to get in and out without decompressing the space vehicle.
Airlocks work perfectly well inatmo.
Airlocks are simple, secure and safe.
Any tool using life form can use an airlock.
They usually employ pictograms and may even have language assist.
Airlocks are secure. 
The ship will only allow the identified crew to enter the space vehicle.
Airlocks are safe.
It would be nearly impossible to eject a life form from a functioning airlock.

NOTE: Airlocks do not deduct cargo space but do require cargo space.

An airlock takes up no space __inside__ the space vehicle.
However, an airlock requires 5 tonnes of cargo space.
Smaller space vehicles do not have enough space for an airlock.
A ship can have one airlock for every 5 tonnes of vacant cargo space.
Airlocks are free to be located anywhere on the space vehicle.
So a ship with a 15 tonnes vacant cargo hold could support three airlocks anywhere on its hull.
A ship with 2 tonnes vacant cargo space would only have an inatmo access port.

A space vehicle without an airlock depends on inatmo boarding either planetside or in a larger space vehicle hanger.

=== Cargo Lock
A larger ship may prefer a cargo lock.
A cargo lock is not pressurized and can only work inatmo. 
A cargo lock is a big inatmo access portal.
A cargo lock requires a minimum of 50 tonnes of vacant cargo space.
A cargo lock does not occupy any cargo space.

A cargo lock is more than just a door; it is a system.
A typical cargo lock has a capacity of 10 tonnes.
A 10-tonne cargo lock can load/unload 10 tonnes of cargo per hour or a day or whatever.

=== Cargo Airlock
Cargo airlocks are enormous airlocks that only gigantic space vehicles can use.
The cargo airlock can move cargo or without depressurizing the space vehicle.
A cargo airlock requires at least 500 tonnes of vacant cargo space.
The cargo airlock also occupies cargo space.
A space vehicle loses 1 tonne of cargo space per 2 tonnes of cargo airlock size.

There is no open hull force field protected cargo airlocks in EXP.
Development is ongoing, and EXP users may reach this milestone with expected technological advances.

=== Cold Storage 
Cold storage is for cryogenic suspension of organic material less than 250 kg in wate.
The freezers will maintain life, with no drain on life support, and will continue to function after life support has failed.
Cold storage will work until the cold storage box itself is destroyed.
Each cold storage space occupies a half tonne of cargo space.

=== Cabins 
Cabins are somewhat of a luxury, but it is impossible to have guests (other than in cold storage) without cabin space.
Each cabin requires one tonne of hull space and can comfortably house two passengers.

=== Corridors 
Corridors only apply to any passageways that connect luxury cabins, workspaces or ship systems.
Cabin corridors require 200 kg of hull space per map hex (2 meters) of passage.
If personas want to run from the artillery bay to the exatmo drives quickly, corridors are a must.

The entire ship is accessible by utility corridors.
Utility corridors occupy no significant amount of hull space.
However, they are cramped, claustrophobic and slow to navigate.

=== Example Calculation
All remaining cargo space is honest to goodness cargo space.
Cargo space is protected from exatmo and allows for the transfer of stuff.
Often the expedition will earn money for transporting cargo.
More often, the cargo will become the focus of an exatmo space vehicle adventure.

Let's walk through an example 100 tonne spacecruiser (space bus).
Exatmo drives level 10.
Fuel storage level 5.
Computer level 4.
There are 20 passengers, 16 in cold storage and 4 in Cabins.
The crew consists of a pilot, engineer, doctor, and steward.
There are no robots and no crew replacement software.
After all deductions, there are leaves 63 tonnes of cargo space in the vessel.
The remaining cargo space allows for a cargo lock and multiple airlocks.
The cargo lock does not work inatmo, so its inclusion is a mystery.
Sixty tonnes is the capacity of two mundane terran dump trucks.

include::ROOT:partial$CH52_Table_Calculate_Cargo_Space.adoc[]

:art: space_ship_shape.png
:width: 450px
:snark: The player shapes the shipshape ship's shape.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Pointy alien looking spaceship. 

include::ROOT:partial$articulate.adoc[]

== Space Chattels
Space chattels cover equipment and architecture common to ancient and future space travel.

=== External Drives 
External drives are self-explanatory.
Either the exatmo or inatmo drives are on the outside of the hull.
This innovation converts the hull space they occupied into cargo space.
The drawback of this system is that the drive units are more vulnerable to attack during combat.
External drives can either be accessed directly through the hull or via an airlock.

Special drives can never be external.

=== Datalocks 
Datalocks are also called hardpoints.
Data locks are electronic accesses to the exterior of the hull.
Every external contraption requiring exatmo access (guns, missiles, viewers, etc.) requires a datalock.
A ship has ten datalocks per computer level.

=== Vac Suits 
Vac suits allow delicate organic life forms to survive exatmo.
A spacecraft will have one civilian vac suit per crew member and luxury cabin.
So a pleasure cruiser with five crew and six cabins would have eleven civilian vac suits.

There is a 10% chance per civilian vac suit that there will be an industrial vac suit.

For more information about vac suits jump xref:hardware:CH42_Armour.adoc#_vac_suit[Vac Suits,window=_blank].

=== Gravity Couches
Gravity couches are chairs specially designed to save the body from damage during high-g maneuvers.
They are composed of force-absorbing materials and restraining belts.
Grav couches are only needed when the vessel's gravity system has failed.
Passengers and crew not in gravity couches during high-g combat maneuvers are dead.

Only combat vessels have grav couches by default. 
A combat vessel is a space vehicle with naval artillery, bombs or grenades.

=== Emergency Response 
Emergency response is part of the ship's life support system.
Space vehicles will have automated emergency equipment and processes.
The ship will temporarily repair minor air leaks.
The ship will suppress small fires.
The ship will close off bulkheads to contain raging fire, depressurization or radiation leaks.

The ship can only look after itself in a limited way.
Major events must be dealt with by the crew.
Major hull repair, radiation clean up and passenger rescue need actual personas on board.

=== Life Bloat  
A life bloat will maintain four passengers (up to 250 kg in wate each) in cryogenic suspension for an indefinite length of time.
The cryogenic suspension will begin when the balloon-like life bloat is subject to exatmo.
There will be one life bloat for every four luxury passengers.

=== Sickbay 
The sickbay is the doctor's place of operation and personal respite.
A sickbay can hold four patients and takes up two cabins (2 tonnes) worth of space.
There is a 1% chance per organic persona that the space vehicle will include a sickbay.
If the space vehicle has a doctor, there will automatically be a sickbay.

=== Machine Shop
The machine shop is a mechanic's place of operation and personal respite.
A machine shop requires two cabins (2 tonnes) worth of space.
There is a 5% chance per robot on board of having a machine shop.

=== Food Machine 
The food machine will generate nutritionally balanced meals for anything that eats.
The referee determines the palatability of said foodstuffs.
Most food machines employ algae, or fungal, cultures to create the primary heterotrophic food groups.
One tonne of food machine is required for every ten eaters supported.
Because of their potential for comic relief, all ships will have a food machine.
Food machines are also known as compu-cooks and auto chefs.
If the food machine is busy enough, it would be reasonable to give it a personality.

=== Robots 
Robots are a common occurrence on long-haul space vehicles.
The use of robots must reflect the referee's milieu.
The robots can be on board to replace crew, to aid crew, or as paying guests.
The chance of a ship sporting a particular robotic has many factors. 
The depth of persona fabrication that goes into spacer robots depends on the referee's resources and story needs.

The table used to generate space robots is a __Chance__ Table. 
The player rolls decidice (1d100) for every robot type, and there is a chance of having it.
A level 3 computer has a 15% chance of having a maintenance robot on board.
The player rolls once for every item on the chance table, i.e., she makes a separate roll for combots, social robots etc.


include::ROOT:partial$CH52_Table_Spacer_Robots.adoc[]

== EXPS
The EXPS value of a spacecraft is impossible to assess.
The expedition earns experience for a space vehicle once they have flown it somewhere.
In austere resource campaigns, the EXPS award for an earned space vehicle is one complete EXPS level.
If space vehicles are commonplace, this EXPS award only counts once.

== Value
A space vehicle's value depends on several components: hull, drives, computer, etc.
Wear and tear may have reduced a ship to worthlessness in one culture, while another will pay dearly for anything that can get them into orbit.
Space vehicles are precious.
Space vehicles with powerful computers and special drives are worth enormous amounts.

include::ROOT:partial$CH52_Table_Space_Vehicle_Value.adoc[]

=== Example Value Calculation
The following is an example value using the space bus from the <<_example_calculation,cargo space calculation>>.
The spacecruiser has 100 tonnes displacement, Defence Rating of 700, exatmo drive 10, fuel level 5, computer level 4

include::ROOT:partial$CH52_Table_Space_Vehicle_Value_Calc.adoc[]

== Operational Costs
Space vehicle maintenance and operational cost are tedious.
The main operational costs of a spaceship are wages and fuel.
Maintenance carried out by the ship's engineer costs nothing and is completed correctly.
Replacing destroyed parts costs the same as the calculated value of the part.
Upgrading parts cost the same as the calculated value of the new part.
The cost of parts includes parts and labour.
Refitting takes weeks to months. 

:art: busy_bow_prop_repair.png
:width: 450px
:snark: Inatmo drive repair.
:artist: Ladrimal
:date: 1887 (yes 1887)
:license: CC BY-SA 4.0
:description: Drawing of workers repairing propeller of flying ship.

include::ROOT:partial$articulate.adoc[]

General refitting is necessary for alloy hulls.
After extended travels or any combat, the hull will require refitting.
Not refitting the space vehicle will lead to mechanical failure.
The refitting will cost between 0.01% and 0.1% (rolled on 1d10) of the ship's total value.
Woah, it takes a lot of cargo to refit a bit space vehicle.
If the refitting costs were .05% of the ship's value, then a space vehicle worth 500000000 would cost 250000 to refit.
