= Devices and Gadgets

Devices and gadgets includes those artifacts that don't have a specific home.
Examples are visual aids, computers, lights, and weird ammunition.
Devices and gadgets also includes some rare and unique devices.
Examples of these are dehydrators and tesseract boxes.

.*Device and Gadget Checklist*
. <<_generate_type,Device Type>>
. <<_description, Description>>
. <<_parameters,Parameters>>

== Generate Type

include::hardware:partial$list_of_devices_and_gadgets.adoc[]

== Device Data

=== Description
The appearances of these devices is as varied as there are devices in the universe. 
Of all the artifact departments the devices are the most likely to not be understood by their shape. 
If no obvious description comes to mind jump to xref:hardware:appearance.adoc[Appearances,window=_blank].

=== Parameters

==== Vocation 
Vocation represents the persona vocation best suited for the device.
If the vocation attribute indicates Mechanic, then the artifact is used by mechanics.
If the artifact vocation is labelled Spie, then it is an artifact for spying.
If the vocation is labelled None, then it sits in no particular vocation category.

==== Duration 
Duration indicates how much use the device can endure before the user must replace the battery set.
It would be unusual for a battery set to run down, but who knows, it may happen just when the device is most needed!
Other toys have a predetermined number of uses before the user must replace the battery set.
Single-use artifacts usually consume themselves to reach their objective.
Artifacts with the duration of Power Source need a connection to a  power source like a wall outlet or a generator.
These are artifacts that require enormous power plants like nuclear generators and hydroelectric dams.

==== Wate 
The wate parameter lists the wate of the device in kilograms.
This parameter is added to the persona's wate allowance if she is carrying the artifact.

==== EXPS
The experience point value is for the persona, or personas, who correctly identifies the device. Identification can occur before or after the device is used.

==== Value
The value parameter is how many electrum pieces the device is worth. The value of a device may be priceless in certain situations of milieus.


== Device Catalogue

=== Absorber 

[horizontal]
Vocation:: None
Duration:: 120 Hour per Battery
Wate:: 2kg
EXPS:: 200
Value:: Special

Absorbers are capable of eliminating environmental components that are harmful to organic creatures.
The absorbers are industrial-strength air cleaners that counteract harmful agents like radiation, gas, and smoke.
The devices all operate on unknown electrochemical and mechanical principles that allow the referee to ignore any problems regarding the laws of conservation of mass.
All absorbers have the same specifications and abilities.
They eliminate the substance in question in a non-violent manner.

They have a three hex radius of effect in which the toxic material will have absolutely no effect.
For instance, a radiation absorber would reduce the effects of radiation __within__ the three hex area of effect for the duration of the battery set.
The absorber will also clean up an area around itself by drawing in and neutralizing the offending substance.
The absorbers reduce the duration and area of effect to 1/4 of expected.
Substances like smoke, radiation and gas clouds drop to 1/4 of their area of effect and duration.
For those absorbers that can absorb damage, each HPS of damage absorbed counts as 1 hour of battery life.

include::hardware:partial$absorber_types.adoc[]

=== Aerosol Regulator 

[horizontal]
Vocation:: None
Duration:: one canister
Wate:: 500gms
EXPS:: 600
Value:: Special

The aerosol regulator has no false advertisements in its title. 
It simply regulates aerosols.
The cap-like device snaps onto an aerosol, restraining its all-in-one-use nature.
The aerosol regulator will yield 1-4 additional uses for an aerosol.
Aerosols typically only yield one use.
The persona cannot remove the aerosol regulator until she expends all charges.
The device can also moderate the effect of any uncombat aerosol.
Paint aerosols will act like ordinary paint canisters, and foam aerosols will dispense like shaving cream.

=== Ammunition 

[horizontal]
Vocation:: Mercenary, Spie
Duration:: One Use
Wate:: Doubled
EXPS:: 100
Value:: Special

This ammo is unique, more like bizarre, ammunition for guns.
The ammo is for bolt action rifles, derringers, semi-automatic weapons, full-auto pistols/rifles, job pistols/rifles and revolvers.
These are the typical weapons that explosively launch bullets.
Other special weapons (fusion, plasma) do not have special ammo.
An ammo cache has 1 to 1000 rounds.
Whether or not ammo fits an available weapon can be determined by xref:uncombat:sphincter_rolls.adoc[Sphincter Roll,window=_blank]

include::hardware:partial$ammunition_unique.adoc[]


=== Anti Grav Backpack 

[horizontal]
Vocation:: Nomad
Duration:: As needed
Wate:: 1kg or 15kg
EXPS:: 250
Value:: 10000

The antigrav backpack reduces the wate of equipment stored within it.
Antigrav load balancing will reduce anything placed inside the backpack to one-tenth its normal wate.
If the backpack should get turned off, it will have a wate of 15 kg plus the regular wate of all equipment stored within it.
The backpack has a maximum capacity of 200 kg of equipment.
This device offers no benefits to the wearer other than wate allowance.
For instance, the antigrav backpack will not allow the persona to fly, fall slowly, or reduce her wate in high gravity atmospheres.

=== Anti Grav Beam 

[horizontal]
Vocation:: Mechanic
Duration:: 120 hours per Battery
Wate:: 2.5kg
EXPS:: 250
Value:: 500000

The antigrav beam generates anomalous gravity in a one hex area of effect, up to 5 hexes away.
The beam delicately lifts objects into the air and gently sets them back down.
There is no way to weaponize this device or lift involuntary personas. 
The antigrav beam is for lifting large or delicate objects to ease repair.
The user can adjust the beam to rotate objects into any position needed.
The maximum wate supported by the beam is 20 tonnes.
An antigrav beam replaces hoists and lifts for repairs and inspections.

=== Anti Grav Belt 

[horizontal]
Vocation:: Nothing
Duration:: Unlimited
Wate:: 250gm
EXPS:: 375
Value:: 5000

The antigrav belt is a device that shows that cheeky refs write rules.
The antigrav belt is a support device that keeps a persona's trousers from dropping.
There is another version of the belt that can replace a brassiere.
The antigrav belt, or brassiere, does not lift the persona into the air, allowing them to fly around.
Antigrav boots allow a persona to fly around, defying gravity.

=== Anti Grav Boots 

[horizontal]
Vocation:: None
Duration:: 10 day per Battery
Wate:: 8kg each
EXPS:: 250
Value:: 250000

:art: antigravboots.png
:width: 350px
:snark: Light on your feet
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: A pair of cowboy boots flying in the air.
include::ROOT:partial$articulate.adoc[]

Antigrav boots are the typical antigrav unit found in most Sciency Fiction milieus.
Antigrav boots allow the wearer to fly about without the worries of gravity.
The gravity repulsion unit can operate for ten days per battery set.
The antigrav boots can come in a belt form which has a wate of 16 kg.
The antigrav boots will work on personas up to 150 kg in wate.
Either antigrav unit (boots or belt) can travel at up to 25 h/u, hover, fly upside down, fly sideways, etc.

The antigrav device is very maneuverable and has a handling class equal to the persona's DEX.
If a persona is trying a zany maneuver, a driving roll should apply.

=== Anti Anti Grav 

[horizontal]
Vocation:: Mechanic
Duration:: 50 uses per Battery
Wate:: 5kg
EXPS:: 299
Value:: 90000

The anti-antigrav beam is also called an antigrav neutralizer.
The device normalizes gravity fields that antigrav devices have manipulated.
The beam has the effect of negating antigrav units, gravruptor attacks, or other non-natural gravity anomalies.
The device maintains normal gravity.

Any devices generating anomalous gravitational fields will instantly shut off.
If the beam hits an antigrav backpack, the backpack will crash to the floor.
The same is for antigrav boots and antigrav belts.
The persona will crash to the ground, or her pants may fall.

The antigrav units are disabled for 1-20 (1d20) units.
The longer the antigrav is disabled, the more likely it will remain broken.
If the pack were disabled for 14 units there would be a 14% chance of the backpack's anti grav unit being xref:combat:equipment_damage.adoc#_extent[damaged,window=_blank].

The anti-antigrav beam has a range of 20 hexes.
The maximum wate that it can affect is 2 tonnes. 
Machines like space ships cannot be knocked out of the sky by this device.
Mechanics enjoy a +10 bonus on any anti grav related rolls.

=== Anti Grav Pushcart 

[horizontal]
Vocation:: Mechanic, Nomad, Nothing
Duration:: 5 days per Battery
Wate:: 0kg or 75kg
EXPS:: 100
Value:: 250000

The antigrav push cart is also called a wheel-less barrow.
The gravity repulser plate will nullify the wate of any object less than 10 tonnes.
The pushcart must be under the object, but it need not be centred to lift.
The barrow will raise the object about 20 cm off the ground.
The device has safety features that prevent falling damage.
While on the barrow, balance is unimportant since there is no gravity to tip the object over.
The pushcart's max speed is five h/u.

=== Attractors 

[horizontal]
Vocation:: Special
Duration:: 10 uses per Battery
Wate:: 35kg
EXPS:: 600
Value:: Special

Attractors are heavy boxes that employ a fantastical array of chemical, pheromonal, gravitational, magnetic, and even stranger mechanisms to redirect objects in motion.
The box can attract waves of energy, aliens, or projectiles.

include::hardware:partial$attractor_types.adoc[]

==== Aliens
This device attracts organic lifeforms from the family diversidae.  
When activated, aliens from far and wide will shuffle, hop and slither towards the attractor.
In most cases, the alien will be a referee persona that helps move the story along.
Player persona aliens must win a Mind roll or head towards the attractor.
The alien attractor has no specific range but has a specific impact on the story.
For example, deploying this device in a zoo would create chaos.

include::hardware:partial$effected_persona_type.adoc[]

==== Ballistics
The ballistic attractor redirects __high-velocity__ projectiles.
Bullets, missiles or gauss slugs change direction towards the attractor.
The attractor does not affect low-velocity projectiles like arrows or spears.
Expedition ballistics are also affected by the attractor.

The projectile must pass through the device's 10 hex area of effect. 
The projectiles change course and crash harmlessly into the ground around the attractor.
Artillery, bombs, and grenades may still have their area of effect attack after redirection. 
The ballistic attractor also makes a decent targeting device.

==== Comms
The communications attractor acts like a black hole sucking in information.
The attractor redirects and disrupts data transfer through the physical space. 
Any electromagnetic waves transporting data, such as radio or lazer, are redirected to the attractor.
The field knocks out radio communications, disrupts hard-wired data lines and even face-to-face speech.

When redirecting comms, the data is randomly bent out of shape, rendering it useless for eavesdropping.
In an urban center, this artifact would devastate the communication system.
This device does not attract psionic communications, sign language, the written word or semaphore. 

In a major urban center, the energy load on the attractor can become dangerous. 
When used in any dense communication environment, the artifact will seep radiation.
Personas within five hexes must win a radiation roll versus intensity 4-24 (4d6) radiation.
The radius of the comms attractor is 1 kilometre, but story trumps this range.

==== Energy
This attractor specifically draws energy within its 10 hex area of effect.
It is very effective at disrupting energy attacks like fusion and plasma attacks. 
The attractor will also draw down power from energy transmission sources like power lines.
The attractor does not drain batteries unless the battery is using broadcast power. 
A mechanic may harness this attracted energy to recharge batteries.
Recharging batteries from an energy attractor is a hard (84) mechanic task.

In an energy-rich environment, the load on the attractor can become very high. 
This overload may cause the attractor to seep radiation.
Personas within five hexes must win a radiation roll versus intensity 4-24 (4d6) radiation.

The energy attractor has a range of 10 hexes, a value of 100000 and is a mechanic artifact.

==== Lazers
This attractor redirects energy dense lazer projectiles.
The lazer must pass through the device's 10 hex area of effect. 
Any lazer attacks or lazer communications redirect towards the attractor.
Energy attacks like fusion, fission or plasma attacks are no affected by this device.
Expedition lazers are also affected by the attractor.
The lazer beams dissipate harmlessly around the attractor.

==== Projectiles
This attractor redirects __low-velocity__ projectiles.
The projectile must pass through the device's 10 hex area of effect. 
The device redirects arrows, rocks or daggers, forcing them to fall safely on the ground.
Projectiles like bullets or lazers are unaffected by this attractor.

==== Robots
The robot attractor draws robots from far and wide.
The device has no specific range other than it helps move the story along.
The attractor creates data and signals that make a robot within the range come and check things out.
A moving bot may believe the attractor has a delivery for her.
A combot may believe there is an enemy infiltration.
A policing bot may believe there is a crime in progress.
Player robots must win a control factor roll to not be attracted to the device
If you don't have a robot in mind jump to xref:referee_personas:robot_rp.adoc#_series[Robot Series].

=== Auto Lock Pick 

[horizontal]
Vocation:: Spie
Duration:: 25 Uses per Battery
Wate:: 3kg
EXPS:: 2106
Value:: 220000

The computerized, automated, robotic lock pick is for defeating *mechanical* locks.
The auto-lock pick is non-destructive and does not damage the lock or door.
The lock pick is also covert and avoids setting off alarms if they are detected. 
This toy works on mechanical locks or the mechanical part of an electronic lock.
The lock pick does not work on electronic or computer locks. 

If employed by a spie, the auto lock pick will be 90% effective at opening the lock.
To avoid traps or alarms, the player must win a normal (42) task roll. 
Other persona vocations can deploy the auto lock pick.
The chance of success is 42% to open the lock.
If there is an alarm or trap, there is only a 21% chance to avoid it.

=== Auto Holster 

[horizontal]
Vocation:: Mercenary, Spie
Duration:: Unlimited use
Wate:: 1 kg
EXPS:: 200
Value:: 20000

The auto holster rapidly deploys its holstered weapon directly into the persona's hand.
The persona merely puts their hand into an "I want to shoot my gun" position, and the holster flings the weapon to the ready.

Under normal circumstances, the auto pistol will always get the drop on an opponent.
If two auto holsters are involved in a quick draw, the personas have a Dexterity challenge.
The auto holster allows the persona to attack during any stage of an ambush.
If the persona is not allowed to move during an ambush, the auto holster allows for a pistol attack.

Mechanics can modify the auto holster for rifles, detectors or vedi kits.

=== Auto Brush 

[horizontal]
Vocation:: Nothing
Duration:: Powered by Passion
Wate:: 230gms
EXPS:: 193
Value:: 250

The auto brush is a handheld device that sprays chemicals onto surfaces, discolouring them. 
The auto brush is a glorified paint dispenser.
The grip on the brush manipulates the colour, texture, and width of each stroke.
This brush is for fine arts and not for commercial structure painting.

=== Auto Card 

[horizontal]
Vocation:: Spie, Mechanic
Duration:: Unlimited
Wate:: 500gms
EXPS:: 2006
Value:: 220000

The computerized autocard is for defeating __electronic__ locks.
The auto card is not destructive and does not damage the lock or door
The auto card should avoid setting off alarms if they are detected. 
The autocard opens electronic locks or the electronic parts of a mechanical lock.

If employed by a spie, the auto card will be 90% effective at defeating the lock.
To avoid traps or alarms, the player must win a normal (42) task roll.
A mechanic has no benefit when using the auto card to defeat locks but gains +10 on all lock-related rolls. 

Other persona vocations can deploy the auto card on electronic locks.
Other persona vocations can deploy the auto lock pick.
The chance of success is 42% to open the lock.
If there is an alarm or trap, there is only an 11% chance to avoid it.

=== Battery Power Plug 

[horizontal]
Vocation:: Mechanic
Duration:: Power Source
Wate:: 15 kg
EXPS:: 90
Value:: 5000

The power plug can attach itself to any power source and recharge most batteries. 
It looks like a big box with cords and adapters hanging out of it.
The power plug can recharge any kind of battery except for psionic and broadcast batteries.
There is a 50% chance that the power plug will have an adapter for a particular battery.
Batteries immediately recharge, but in combat, the process takes 1-20 (1d20) units.
Any vocation can use the automated battery power plug.

The toy comes with 1 to 3 attached extension cords.
The battery power plug can charge 1-10 (1d10) batteries at once.

A mechanic can adapt the power plug to charge any battery with an easy (24) task roll.
A mechanic can wire an extension cord to power an artifact indefinitely with a hard (84) task roll.
For example, a lazer rifle attached to an extension cord would have unlimited ammo when plugged in.  

The battery power plug grants a +15 bonus for any power or battery-related rolls.

=== Battery Slot

[horizontal]
Vocation:: Mechanic
Duration:: Not Applicable
Wate:: 5 kg
EXPS:: 666
Value:: 5000

The battery slot takes any battery type and converts it to a standard output.
The persona can then use the output to power another artifact.
The battery slot allows the artifact to get power from any battery type. 
The battery can hold 3-18 (3d6) batteries of any type.

A one battery lazer pistol attached to a battery slot holding eight batteries could shoot eight magazines of lazer bolts in succession.
A mechanic is required to connect the battery slot to an artifact.
Connecting a battery slot to an artifact is a normal (42) task roll.

=== Battery Recharger

[horizontal]
Vocation:: None
Duration:: Power Source
Wate:: 10kg
EXPS:: 300
Value:: 20000

A battery recharger restores and recharges depleted batteries.
The recharger cannot restore and recharge psionic or broadcast batteries.
Non-mechanics using the device must roll 1d100 for each recharge of the battery.
A roll of 42 indicates the battery has spectacularly expired.

The battery recharger can recharge 3-18 (3d6) batteries at once.
The persona must connect the battery recharger to a power source.
Recharging a full set of batteries takes 8 hours.

=== Bot Neutralizer

[horizontal]
Vocation:: Mechanic
Duration:: 10 uses per Battery
Wate:: 2.3kg
EXPS:: 850
Value:: 50000

The robot neutralizer is a portable off switch for robots.
The neutralizer disconnects a robot from its power source, bringing any robot to a grinding halt.
Neutralized robots will gently park themselves and power down. 
The shutdown will not allow a robot to harm itself or its fabricator type.

The robot neutralizer has a chance of failure equal to the robot's control factor.
A robot with a 25 control factor has a 25% chance of avoiding neutralization.
This chance of failure cannot be higher than 80%
A robot with a 97 control factor has an 80% chance of avoiding neutralization.

Domesticated robots are easier to shut off with the robot neutralizer.
Combots (Shoot), exatmo exploration (type E-X), policing (type P) are resistant to being neutralized.
These robot types earn a second chance to avoid a shutdown.
A datalyzers (Sotto - 2) and hobbots (type H) *cannot* be turned off with a robot neutralizer.

Neutralization is not permanent, and the robot will reactivate in 3-300 (3d100) units. 
In a  uncombat neutralization, the robot will reactivate in 1-10 (1d10) minutes.
Using the robot neutralizer on a shutdown robot will cause it to reactivate immediately.
So turning one robot off may turn another robot on within the three hex area of effect.

Mechanics will earn a bonus of +42 on any robot-related PT rolls with this artifact.


=== Canceller

[horizontal]
Vocation:: Mechanic
Duration:: 50 uses per Battery
Wate:: 2.3kg
EXPS:: 850
Value:: 50000

:art: atomizer.png
:width: 350px
:snark: Jail time cancelled
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Human operating beam cutting through jail bars.
include::ROOT:partial$articulate.adoc[]

The canceller safely disperses matter into its useless components.
A canceller can disperse one hex of matter per use.
The wate of the dispersed substance is not crucial because personas are usually trying to pass by a barrier.
The device has industrial safeguards which only allow the canceller to disperse homogeneous or simple substances.
The canceller does not affect complex objects such as robots or organics.

include::hardware:partial$canceller_material.adoc[]

=== Climate Band 

[horizontal]
Vocation:: Nomad
Duration:: 5 Days per Battery
Wate:: 900gms
EXPS:: 80
Value:: 100000

The climate band is a uncombat, meteorologic force field that defends the persona against the weather.
The climate band creates a form-fitting force field that protects the persona from temperatures between -50째C and +50째C.
The climate band will counter any meteorological conditions such as wind chill, precipitation, hypothermia, heatstroke, sand storms, etc.
A battery set will last five days.
This force field can only operate in inatmo.
The climate band does not block poison gas, radiation, lightning strikes or weaponized attacks.

=== Climate Portent

[horizontal]
Vocation:: Nomad
Duration:: Until Destroyed
Wate:: Special
EXPS:: 42
Value:: Special

The climate portent is a translucent tent-shaped force field against the weather.
The climate portent can protect its guests from all but the most extreme meteorological conditions.
The portent protects personas from temperatures between -50째C and +50째C.
The portent counters meteorological conditions such as wind chill, precipitation, hypothermia, heatstroke, sand storms, etc.
The portent will hold anywhere from 2-16 (2d8) anthro (medium-sized) personas.
This force field offers no protection from combat attacks or poisonous gases.
The climate portent will only work in earth-like atmospheres.

=== Clothing 

[horizontal]
Vocation:: None
Duration:: As needed
Wate:: 4 kg
EXPS:: 42
Value:: Special

A clothing set includes socks, pants, shirts, jacket, boot covers, gloves and a hat or hoody.
A onesie or a cloak can replace the above items.
This clothing is specialized and has rare and unique properties.
The persona cannot use clothing in conjunction with armour.

include::hardware:partial$clothing_artifact.adoc[]

==== Compucammo
Compucammo passes light from behind the wearer onto the suit.
The detectors on one side of the suit alter the emitters on the opposite side of the suit.
This mechanism creates dynamic camouflage making the wearer very hard to see with optical sensors.
The suit cannot defeat radar, sonic eyes, smell or echolocation.
A searcher must win a tough Awareness roll to notice the persona.

The compucammo is for stealth, not combat. 
While sneaking and hiding motionless compucammo is very effective.
This advantage disappears during hand-to-hand combat or close inspection.

Spies and nomads enjoy a +42 bonus on sneaky task rolls.
Compucammo is worth 100000 and is considered a spie or nomad artifact.

==== Computerized
Computerized clothing is a self-adjusting, self-cleaning formal wear with situational Awareness.
The autotux is rife with sensors that assess the room for the best effects for its wearer.
Adjusting filaments alter the suit's shape, and photo emitters subtly change the suit's hue.
This tux tailors itself 'to suit' the crowd.
If desired, the formal wear can be an auto gown of flowing distinction.

A nothing earns a +200 on her social standing and +2 on CHA while wearing the suit.
The autotux is worth 50000 and is a nothing artifact.

==== Displacement
A displacement suit emits a real-time hologram that slightly displaces the persona.
The hologram may fool attackers into attacking the displaced image instead of the persona.
The hologram is a copy of what the persona looks like and is wearing. 
A displacement garment is not a disguise.
It is most effective during combat situations increasing the wearer's AR by 200.
The wearer must activate displacement clothing before getting the Defence Rating bonus. 

Displacement clothing is worth 75000 and is a mercenary or spie artifact.

==== Jump
The jumpsuit maintains a safe gravity for the wearer in the face of gravity increases.
A jumpsuit protects the persona from gravities between 0 and 10 g.
This type of suit is worn by pilots and others working with aberrant gravities.
The jumpsuit nullifies any weaponized gravity attacks that inflict acceleration damage.
If desired, a jumpsuit may disrupt personal antigrav devices.
The suit does not prevent damage from falling or being hit by flying debris. 

A flight suit is worth 10000 and has no assigned vocation.

==== Stealth
The stealth suit is a classic black jumper worn by spies, commandos and snazzy anarchists.
The suit subdues sound, light and most detection radiations. 
Radar, sonar, and infrared don't reflect as off this matte black weave.
While *not* an invisibility device, the suit is ideal for sneaking around. 
In the darkness, the stealth suit will offer a +20 bonus on sneaky PT rolls.

The stealth suit is worth 4242 and is considered a spie or nomad, or mercenary artifact.

=== Communicators 

[horizontal]
Vocation:: Mechanic
Duration:: As needed
Wate:: Special
EXPS:: Special
Value:: Special

:art: all_hale_radio.png
:width: 350px
:snark: All hale the radio
:artist: Rogers
:date: 1951
:license: CC BY-SA 4.0
:description: a bald robed humanoid holding up radio like a bible. 
include::ROOT:partial$articulate.adoc[]

There are several communication transceivers that personas can use to chat.
They mainly vary in size, which affects the transmission range.
The bigger the transceiver is, the further its range.
The smaller the transceiver is, the more devices.
These devices are supposed to be useful and assist the players in helping develop the story.

Each communicator has a unique ability and a size.

.*Communicator Checklist*
. <<_communicator_size,Communicator Size>>
. <<_transmission_type,Transmission Type>>

==== Communicator Size
include::hardware:partial$communicator_size.adoc[]

Dental::
Dental communicators are very light, no more than 5 gm, and can hide on one of the persona's molars.
When in the mouth of the persona, she can communicate with her expedition without speaking aloud.
The wearer listens to communicators via vibrations of her skull via the jaw.
Dental comms have a 500-meter range and are worth 100 EXPS / 300 eps and numbers 2-12 (2d6).

Collar::
Collar communicators are small (30 gms) adhesive transceivers that a persona can attach anywhere.
Collar comms have a 1-kilometre range, are worth 25 EXPS / 200 eps, and will number 3-30 (3d10).

Wrist::
Wrist communicators are 100 gm transceivers that can be worn as a bangle, a hoop earring, or a nose ring.
They have a 12-kilometre range, are worth 25 EXPS / 500 eps, and will number 1-10 (1d10).

:art: phoney_phone.png
:width: 250px 
:snark: Data package is extra.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Hand holding a fancy video data phone.
include::ROOT:partial$articulate.adoc[]

Handheld::
Handheld communicators are the classic transceivers that one expects to find in mundane terran police dramas.
These appear as radios or mobile telephones and weigh 500 gms.
These communicators are slightly programmable and have multiple channels.
Mechanics can engage in electronic security countermeasures (security scrambling of their signals) with a normal (42) task roll.
These communicators have a 24-kilometre range, are worth 25 EXPS / 1000 eps, and will number 1-6 (1d6).

Backpack::
The backpack communicator is a portable 15 kg radio station.
A mechanic using this radio can engage in electronic countermeasures within the range of the backpack.
A mechanic can use a backpack comms to camouflage her communications, jam communicators, locate transmitters, and create general terror on the airwaves.
The backpack communicator will give any persona a +25 PT roll bonus on communication task rolls.
The backpack communicator has a planetary range of 500-kilometres, is worth 200 EXP / 10000 eps, and includes 0-9 (d10-1) handheld communicators.

Vehicle::
A vehicle communicator allows the persona to engage in virtually any electronic countermeasures (ECM) that she desires.
Mechanics get a +35 bonus ECM task rolls.
The vehicle radio is 65 kg in wate and requires vehicle power to operate.
Vehicle comms an inatmo range of 5000 kilometres and can reach spacecraft in orbit.
A is worth 400 EXPS / 20000 eps and includes 0 to 3  (1d4-1) backpack communicators.

Spacecraft:: (600/100000)  
The spacecraft communicator is a transmissions laboratory that allows for the most elaborate planetside ECM maneuvers.
The spacecraft comms can manipulate voices, eavesdrop, decrypt and synthesize fake messages.
This comms laboratory is part of a spacecraft and requires a ship's computer and a ship's power plant to operate.
Exatmo comms has a spacecraft range of 2-12 (2d6) light-years, is worth 600 EXPS and 100000 eps and includes 0 to 5 (1d6-1) vehicle communicators, 

Included comms units are cumulative. 
For instance, a spacecraft communicator could monitor, encrypt and manipulate the signals of 4 vehicle communicators, 12 backpack communicators, and 63 handheld communicators.

==== Transmission Type
include::hardware:partial$communicator_transmission.adoc[]

Standard::
Mundane terran radio transmissions.

Data::
Extended for data communication with robots and AIs.
This data-enhanced unit can communicate in their electronic tongues.
Data transmission doubles the value of the communicator.

Encrypted::
Harder to comprehend when intercepted and much harder to intercept.

Lazer::
Line of site communication only. 
Interception is only possible by physically diverting the lazer.
Combining this with dental communicators has strong comedy potential.
Lazer comms increase the device's value by ten times.

Telepathic::
Users can pass their thoughts to each other through the thinkspace.
These messages are instantaneous and do no travel through the physical space.
Interception of telepathic comms requires unique equipment or psionic mutations.
Telepathic comms increase the device's value by 100 times.

=== Compass 

[horizontal]
Vocation:: Nomad
Duration:: Until Destroyed
Wate:: 1.5kg 
EXPS:: 93
Value:: 250

:art: radar_compass_detector.png
:width: 250px
:snark: Going my way.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Hand held futuristic detector with tiny direction monitor. 
include::ROOT:partial$articulate.adoc[]

A compass is a direction maintaining device or anything that attains a constant direction for reference.
This compass will maintain any direction programmed into it or any of several standard directional indicators.
The compass accounts for any deviations in delineation, gravity, pressure, or climate.
The compass works underwater, in zero gravity, or a vacuum.
This device will aid a nomad with +24 on any nomadic PT rolls.

=== Compukit 

[horizontal]
Vocation:: Mechanic
Duration:: As needed
Wate:: 3.0kg
EXPS:: 40
Value:: 5000

The compukit is a computerized tool kit.
Not only does it house essential electronics tools, but it also has a built-in helper screen and many fancy-looking sensors.
The compukit is the mechanic's electronic toolbox.
Mechanics get a +20 bonus on all mechanic task rolls using this device. 

=== Computers 

[horizontal]
Vocation:: Mechanic
Duration:: As needed
Wate:: Special
EXPS:: Special
Value:: Special

:art: class_computer_with_stuff.png
:width: 350px
:snark: Vocation computer with connectors.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Open box with computer monitor in lid and attachments stuffed in.
include::ROOT:partial$articulate.adoc[]

Computers are black boxes of data with which the persona can interact.
Computers will be vocation computers automatically.
If the referee is on board there is a 1 in 10 chance that the device will be an AI.

==== Vocation Computers 
Vocation computers have a wate of 10 kg, and a technicolour screen and a touch display.
They appear as bloated portable computers sporting many strange and exotic ports.
Vocation computers have no printout, and they do not talk.
The persona uses the machine to access data about her profession.
The data hides beneath icons in a haphazard hierarchic manner.
No one is certain what information a vocation computer contains, and the information varies in accuracy.
The persona contributes her data into the vocation computer as others have before her.

Vocation computers aid the player when making task rolls.
The bonus is a random 3-30 (3d10) on task rolls.
The more experienced the persona, the better she is at using her vocation computer.
Players get one bonus roll per three EXPS levels.
The player gets to choose the highest roll for her bonus.
So a 6th level persona would get three rolls of 3-30 picking the best roll.

include::hardware:partial$vocation_computer_type.adoc[]

==== AI Computers
Autonomous Intelligence (AI) is a highly interactive artificial Intelligence with both consciousness and immeasurable computational power.
Artificial general Intelligence is one of mundane terra's current obsessions.
In EXP, AI refers to autonomous Intelligence or aware Intelligence, and calling it artificial may piss it off. 
An AI  computer will almost certainly become a referee persona with emotions, personality and goals.
To fabricate an AI, jump to xref:referee_personas:ai_rp.adoc[Autonomous Intelligence,window=_blank].


=== Control Baton 

[horizontal]
Vocation:: Mercenary
Duration:: 10 user per Battery
Wate:: 2.5 kg
EXPS:: 631
Value:: 125000

:art: control_baton.png
:width: 350px
:snark: Stick it to biomech armour
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: A short baton with a button and hand strap.
include::ROOT:partial$articulate.adoc[]

The control baton is similar in appearance to a field marshal's baton.
However, this baton can instantly shut down biomech armour.
There are two buttons located on the rather heavy handheld device.
One button will completely immobilize a suit of biomech armour.
The other will re-mobilize it.

The control baton's off button disconnects the armour wearer's physiologic connections to the suit.
Turning a suit off is instantaneous, creating a form-fitting jail.
The baton will not allow the armour wearer to come to harm.
E.g., the armour's hover would not shut off and drop a persona to her death.

When control returns to the wearer, it takes a while to reconnect.
There will 5-50 (5d10) units of reconnection time taken before the suit is operational again.

A control baton is a tool meant for biomech armour training. 
The shut-off is for the safety and punishment of trainees.
There is a 42% chance that this will work on a specific suit of biomech armour.
If the baton does work, the persona within the armour is at the mercy of the baton holder.

The baton has a range of 50 hexes.
A mechanic earns a bonus of +15 when making rolls related to biomech armour.

=== Cords 

[horizontal]
Vocation:: None
Duration:: Until Destroyed
Wate:: Special
EXPS:: 42
Value:: Special

Cords can be used as rope for climbing, tying things down, making macrame, or whatever.
These are special cords with unique properties are possibly useful for the expedition.

include::hardware:partial$cord_type.adoc[]

Alloy::
Alloy cord is more robust and lighter than ordinary rope.
It is composed of supple alloy threads with ceramic elements.
The cord can support 999kg of wate without special accommodations.
Alloy cord length varies from 3-300 (3d100) hexes. 
Its wate is 100gm per hex and is worth 50 per hex. 

Grav::
Grav cord can suspend itself as the persona players it out.
Parallel to gravity, the cord can support 250kg.
Perpendicular to gravity, the cord can support 100kg.
The grav rope must fasten to at least one solid surface.
The cord cannot hover in the air unsupported.
Grav cord length varies from 3-90 (3d30) hexes.
The grav cord has no wate and is worth 5000 per hex.

Monofilament::
Monofilament cord is only a few molecules thick.
However, all the energy of those molecules works together, keeping the line very strong.
The thin cord is dangerous and will cut a persona mishandling it.
Monofilament cord is not easy to weaponize because of its intended commercial use.
Monofilament wire can support 1998kg in wate without making special accommodations.
Monofilament cord comes in lengths of 3-60 (3d20) hexes.
Its wate is 10gms per hex and is worth 1000 per hex.

=== Cutters 

[horizontal]
Vocation:: Mechanic
Duration:: As needed per Battery
Wate:: 0.6 kg
EXPS:: 390
Value:: Special

:art: lazer_hand_saw.png
:width: 250px
:snark: A cut above a common cutter.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Hacksaw with a lazer instead of a blade.
include::ROOT:partial$articulate.adoc[]

Cutters are artifacts designed to cut through most anything.
A cutter will be able to slice through stone, alloy, ceramics or spacecraft hull.
A cutter is not a weapon and only works on sessile objects.
All cutters have safety features that prevent injury to organic materials.
The lazer cutter will slice through a suit of armour but leave the persona inside unharmed.

Cutters are for industry and not combat.
An ambushed robot or biomech suit is immune to a cutter.
A persona could cut an __incapacitated__ robot or immobilized biomech suit to shreds.

include::hardware:partial$cutter_artifact_type.adoc[]

=== Dehydrator

[horizontal]
Vocation:: Biologist
Duration:: Power Source
Wate:: 2301kg
EXPS:: 2069
Value:: 10000000420

:art: dehydrator.png
:width: 400px
:snark: Big thing to make small things
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Human silhouette standing beside a large bin machine. 
include::ROOT:partial$articulate.adoc[]

The dehydrator cryogenically suspends an object and then ejects up to 99.9942% of its molecular components.
The dehydrator then bags the gray powder in a nondescript cellophane bag.
The gray powder includes a complex memory molecule.
Adding water will reconstitute the original object.
The dehydrator straddles the edge of Sciency Fiction and Sciency Fiction.

Typically the dehydrator is used for storing scrumptious dinners for romantic hikes.
A dehydrator can shrink any molecular combination (organic or inorganic).
Many referees will limit the dehydration process to only organic objects. 
The final product has a wate between 1 and 10 grams (1d10).

A dehydrator requires a power source. 
Batteries are not enough. 
While dehydrating, the machine bathes a ten hex radius with 1-12 (1d12) intensity radiation.
A power failure during dehydration will destroy the specimen in the most disgusting manner possible.

There is a 90% chance that the dehydration will be successful.
A biologist can increase the chance of success to 99% with a normal (42) task roll.
Dehydration is never risk-free, and a 1d100 roll is essential.
A roll of 42 indicates the dehydration has failed.

Failure of dehydration is not evident until rehydration.
Failed dehydration affects organic and inorganic objects differently.
A failed organic object will acquire 0-3 (1d4-1) xref:wetware:phenomics.adoc#_defective_mutations[Defective Phenomic Mutations,window=_blank].
The mutations are present on rehydration. 
A failed inorganic sample rehydrates into a cacophony of random primary materials.

Dehydration costs personas 1 point of Mind.
The MND penalty applies every time the persona dehydrates.

The device can convert up to 750 kg of matter at once.
Each kilogram takes one minute to dehydrate into gray powder.
The dehydrator must cool down for 1 hour per kilogram dehydrated.

Mixing bags of dehydrated grey powder does not mix up the objects.
The complex memory molecule maintains each object's integrity.



=== Detectors

[horizontal]
Vocation:: None
Duration:: 5 days per Battery
Wate:: 3.5 kg
EXPS:: 1200
Value:: 950

:art: detector_detecting.png
:width: 250px
:snark: Detector detecting detectors
:artist: Louis Glanzman
:date: 1953
:license: CC BY-SA 4.0
:description: Space suited humanoid looking at computer on stand.
include::ROOT:partial$articulate.adoc[]

Detectors are classic devices for leading expeditions to excitement, fun, and danger.
All detectors are black boxes with a pistol grip and an unmistakable business end.
Most detectors only give a binary answer via a red light on the casing.
The detectors may also yield direction, intensity or number by alterations of the red light.
The ref should be ready to improvise and have fun with detectors.

A lie detector may flash red if a lie is detected.
Or the brightness of the red light may increase with the severity of the lie.
Directional detectors, like mineral detectors, will light up more brightly when pointed in the direction of the source.

Detectors are 90% efficient.
They will discover the mutant, detect the lie, or find the bomb 90% of the time.
Detectors find the closest detectable thing first.

include::hardware:partial$detector_types.adoc[]

=== Detonator Box

[horizontal]
Vocation:: Mercenary, Mechanic
Duration:: Special
Wate:: 10.7kg
EXPS:: 530
Value:: 10000

A detonator box explodes bombs from a safe distance.
The box uses radio beacons for real-time detonations and a vast array of other physical detonators.
The detonator box (the transmitter) includes 1-10 detonators.
The detonators have a wate of 1 kg and must be attached to the bomb.
The detonator box and its detonators are smart. 
They can detonate any bomb in any manner the demolition requires.
A mechanic can fashion the detonator box to activate anything remotely. 
For example, the box could remotely start a vehicle, activate an aerosol, or turn on a robot.
Off-label use (other than bombs) requires a hard (84) task roll.

The detonator box offers +15 on any demolition-related rolls.

=== Filters

[horizontal]
Vocation:: None
Duration:: Single Use
Wate:: 25gms
EXPS:: 100
Value:: 1000

Filters protect the persona's sensory organs from short-term hazards.
The filters consist of nose plugs, earplugs, or contact lenses.
The filters allow the sensor to function normally but will filter out any damaging effects.

There is an equal chance of any of the filters. 
Roll a 1d12.
1-4 is ear filters.
5-8 is eye filters.
9-12 is nose filters.

Ear Filters::
The ear filter fits snugly in the ear and does not impair hearing at all.
Any anthro and some aliens can use the ear filters.
The filter changes its structure when subject to any deafening attack.
The spongy ear filter will defend against both the decibels and the vibrations of sonic attacks.
The filter negates one attack and sacrifices itself.
Ear filters come in pairs of 1-12 (1d12).

Eye Filters::
The eye filter is a contact lens that does not blur sight at all. 
Any anthro and some aliens can use these safety lenses.
The filter changes its structure when subject to any blinding attack.
The filter negates the attack and safely disintegrates.
Eye filters come in pairs of 1-6 (1d6).

Nose Filter::
The nose filter a pair of cones that fill the nostrils. 
The persona can breathe normally wearing nose filters.
Any anthro and some aliens can use these nose filters.
When subject to an inhaled poison gas, the persona can escape without effect.
The filter changes its structure and absorbs poison gas.
The filter negates the attack entirely and safely disintegrates.
Eye filters in pairs of 1-6 (1d6).

=== Fire Logs

[horizontal]
Vocation:: Nomad
Duration:: Special
Wate:: 2 kg
EXPS:: 99
Value:: Special

Fire logs are a high-technology take on the old fireplace log.
Al fire logs have a ripcord starter and easily ignite in any weather.

include::hardware:partial$fire_log_types.adoc[]

Wooden::
A pull of the ripcord produces 2 hours of colourful dancing flames and heat.
A compressed wooden fire log has no value.
Wooden fire logs use up oxygen, create smoke and can start larger fires.
They come in lots of 2-20 (2d10) logs.
There is a variant called a Press To Log where a proprietary button has replaced the ripcord.

Coalex::
A pull of the ripcord produces 8 hours of uniform flame and heat.
A compressed coal fire log has no value.
Coal fire logs use up oxygen, create smoke and can start larger fires.
They come in lots of 1-10 (1d10) logs.

Glow Pro::
The glow pro is a solid cylinder that emits heat and simulated flame light.
The glow pro starts to warm the area when removed from its storage bag.
A glow pro can be re-bagged and re-used later.
This artifact does not require oxygen to burn and even works exatmo.
A glow pro does not off-gas and will not start a larger fire.
The glow pro will burn for five days in total.
A glow pro is worth 1000 and comes in lots of 1-6 (1d6).

Synthex::
The synthex fire log is the stealth heater of the fire log industry.
It gives off no heat signature or light and warms all personas within two hexes.
The synthex fire-less log emits interference patterns that vibrate nearby molecules.
All personas in the area of effect are kept nice and warm. 
This artifact does not require oxygen to burn and even works exatmo.
It does not off-gas and will not start a larger fire.
The glow pro will burn for 15 days in total.
A synthex fire log is worth 10000 and comes in lots of 1 (1d1).

=== Food Culture

[horizontal]
Vocation:: Nomad
Duration:: As Needed
Wate:: 1.5kg
EXPS:: 103
Value:: 5000

The food culture is a icosahedron shaped colony of nutritious fungus on a stick.
Although it sounds unappetizing, the food culture is sanitary, tasty and very nutritious.
The culture can supply a medium-sized anthro persona with a day's nutrition.
The spongy matrix supplies adequate hydration as well.
The food culture grows back in about 6 hours and is ready for breakfast.

A food culture will not survive drastic changes in temperature or climate.
The culture cannot grow back from acid attacks or acid bites. 

=== Generator

[horizontal]
Vocation:: Mechanic
Duration:: Special
Wate:: 25 kg
EXPS:: 45
Value:: 750

A generator converts fuel energy to battery energy.
A generator can be a power source for larger artifacts.
A generator will only work with one type of fuel.
A mechanic is required to connect the generator to an artifact. 
Power source connection is an easy (24) task roll.
A mechanic is required to adapt the generator to charge a battery type. 
Adapting a battery is a normal (42) task roll.
The generator cannot recharge psionic or broadcast batteries.

include::hardware:partial$power_source_types.adoc[]

=== Hooks

[horizontal]
Vocation:: Spie
Duration:: Unlimited
Wate:: 200gms
EXPS:: 103
Value:: 2000

There are two different types of hooks destructive and non-destructive.
The hooks come with handles and attach themselves to any surface.
They are most commonly used to climb walls.
A mechanic can convert hooks to grapples with a cord and a job rifle.
The referee can pick between the two hook types.

.*Destructive Hook*
This hook is the classic metal barbed hook. 
The business end appears like a bouquet of alloy barbs.
The barbed hook does inflict a bit of damage to the surface.
When used as a weapon, the barbed hook acts as a mace.

.*Non-destructive Hook*
This hook is a non-destructive sticky hook.
The business end appears like a cluster of synthetic grapes.
The sticky hook does not make a useful weapon.

=== Instant Stuff

[horizontal]
Vocation:: None
Duration:: Single Use
Wate:: 1-10 (1d10) gms
EXPS:: 400
Value:: Add 900000

Instant stuff is a grey powder that comes in a transparent cellophane bag.
Adding water instantly produces a random artifact.
A complicated memory molecule uses the water to reconstitute an entire object.
Proper labels have long since worn away.
Only the referee knows what will instantly appear when the persona adds water.
Instant stuff usually comes from a <<_dehydrator,Dehydrator>>.

WARNING: *Mistaking instant stuff for food is disastrous for impulsive personas.*

include::hardware:partial$instant_stuff.adoc[]

=== Jet Boots

[horizontal]
Vocation:: None
Duration:: 5 Days per Battery
Wate:: 30kg
EXPS:: 820
Value:: 110000

Jet boots appear as oversized hiking boots with miniature jet engines.
The boots are gyroscopically stabilized and easy to operate.
The boots move at 21-30 (20+1d10) hexes per unit and allow the wearer to fly through the air.
The wearer must have a wate between 40 and 140 kg.

There are some limitations to jet boots.
Jet boots do not hover.
A persona can only use powered weapons while jet booting. 
Strike and  fling weapons would unbalance the jet booter.
If needed, the boots have a handling class equal to half the persona's Dexterity.

=== Jet Backpack

[horizontal]
Vocation:: None
Duration:: 5 Days per Battery
Wate:: 30kg
EXPS:: 820
Value:: 110000

The jet backpack appears as a backpack with diminutive jet engines.
The backpack is gyroscopically stabilized and easy to operate.
The pack moves at 21-40 (20+1d20) hexes per unit and allows the wearer to fly through the air.
The backpack can carry 50kg in its storage compartment.
The user must have a wate between 40 and 200 kgs. 

There are some limitations with a jet backpack.
A persona can only use powered weapons while jet backpacking. 
Strike and fling weapons would unbalance the jet backpack.
If needed, the boots have a handling class equal to half the persona's Dexterity.

=== Joiners

[horizontal]
Vocation:: Mechanic
Duration:: As needed
Wate:: 1kg
EXPS:: 100
Value:: 1000

Joiners are artifacts that join materials together.
The joiner may be a device or a substance.
Glue, tape, and soldering irons are all joiners.

All joiners create permanent bonds.
A permanent bond works as though the substances were always as one.
To separate the bond is equivalent to breaking apart a solid object.
Joiners do not reconnect complex components between materials. 
Haphazardly gluing a robot peripheral back on will yield a non-functional peripheral.

While the bond is permanent, the laws of physics still apply to the objects.
Joining a pole arm to an anthro's head will bond but will most likely pull the flesh off the persona's forehead. 

If the joiner is connecting materials, it will not run out.
If the joiner is creating de novo objects it will quickly expire.
For example, a tube of glue will bond materials endlessly.
Using the glue to construct a helmet will cause it to run out. 

include::hardware:partial$joiner_artifact_type.adoc[]

Sonic:: 
A sonic joiner, or sonic welder, employs acoustic vibrations to meld substances together.
The edges of the substance must be in contact for joining to take place.
A sonic welder can join materials at the rate of 1/2 hex per unit.

Lazer::
A lazer joiner employs focused lazer light to melt substances together.
The edges of the substance must be in contact for joining to take place.
The artifact has a range of 10 cms. 
The lazer joiner is the only joiner that does not require physical contact to join materials.
The lazer can join materials at the rate of 1 hex per unit.

Glue::
The glue joiner is an instantly setting liquid goop.
This joining requires no setting time and molecularly bonds the items permanently.
The glue is pretty super. 
The applicator can be a tube, pump, or spray.
The glue can join materials at 10 cm per unit.
A mechanic can manipulate the setting time, bond strength and bond duration with this joiner.

Tape::
Joiner tape is adhesive and melts into the materials permanently.
The tape may come on a roll or a fancy dispenser.
Tape can join materials at the rate of 1 hex per unit.
A mechanic can manipulate the setting time, bond strength and bond duration with this joiner.



=== Kirlian Talisman 

[horizontal]
Vocation:: Knite
Duration:: Until Destroyed
Wate:: Negligible
EXPS:: 200
Value:: Special

:art: kirlian_talisman.png
:width: 250px
:snark: Order or Chaos?
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: A circular pendant with a complex pattern.
include::ROOT:partial$articulate.adoc[]

The Kirlian Talisman is a concentration symbol employed by xref:vocations:knite.adoc[Knite Vocation,window=_blank].
The talisman amplifies the Knite's psionic focus.
A Kirlian Talisman will support either _order_ (knite) or _chaos_ (anti-knite).

A Kirlian talisman is a potent weapon against its opposite sect.
A knite talisman can injure an anti-knite and vice versa.
A successful attack roll destroys the talisman and reduces the Knite's Mind by 1-4 (1d4) points.
While Mind loss is temporary, if the Knite's MND is less than 18, she loses all her Knite abilities.
The knite, or anti-knite, regains one point of Mind per night of restful sleep.

Knites earn a bonus of 15 on psionic-related rolls when wearing their talisman.
This bonus only works if the talisman is openly displayed.
The talisman does not work if hidden under clothing or armour.
A Kirlian talisman is invaluable to knites and worthless to other vocations.

If a knite finds a Kirlian talisman, it will usually be from the opposite sect. 



=== Lazer Pen 

[horizontal]
Vocation:: Nothing
Duration:: 1000 words 
Wate:: 90gms
EXPS:: 42
Value:: 29

:art: lazer_pen.png
:width: 350px
:snark: Not as powerful as a lazer sword
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Overly thick pen with hazard switch. 
include::ROOT:partial$articulate.adoc[]


A lazer pen will burn a crisp black line onto any surface, at any angle in any environment.
The line width can be varied, and the lazer pen works exatmo.
The pen painlessly writes on flesh and is not a weapon.
The sword is mightier than this pen.
The pen will require a brief recharge after one thousand words.

Nothings have a bonus of +10 on any status rolls when using a lazer pen.
The EXPS value of the lazer pen is 2042 for nothings.

=== Lights 

[horizontal]
Vocation:: None
Duration:: As Needed
Wate:: Special
EXPS:: 10
Value:: 10000

These lights serve are the electronic torches lighting the darkness.
Each light will also have a unique feature built-in.
When used for illumination, the artifact is indistinguishable from an everyday flashlight.

For normal illumination purposes, the light has a range and terminus diameter. 
The user can dial down the terminus diameter to half a hex in diameter. 
The range of regular illumination is also the range of the light's unique property.
The width of the light beam spreads as it gets further away from the source.
The beam width will be less than a hex wide at the source and will increase in width by one hex per 16 hexes of range, with terminus widths of 1, 2, 4, or 8 hexes.
A wall that is 64 hexes away has a circle of light two hexes in radius  (4 hexes in diameter).

include::hardware:partial$light_artifact_power.adoc[]

include::hardware:partial$light_artifact_feature.adoc[]

=== Locks 

[horizontal]
Vocation:: Mechanic, Nothing, Spie
Duration:: Until Destroyed
Wate:: 1kg
EXPS:: 200
Value:: Special

These locks are padlocks designed for one persona's personal use.
The device can be attached to whatever the persona desires.
Mundane locks require a latch to lock the object in question. 
Autonomous locks can be placed on an object, locking, protecting and hiding the valuable.
Biologic, robotic, and holographic locks are autonomous locks.

Mundane locks are worth 1000, and autonomous locks are worth 100000.

Spies and mechanics earn a +10 bonus on lock-related rolls with this artifact.

include::hardware:partial$lock_artifact_types.adoc[]

=== Mapper 

[horizontal]
Vocation:: Nomad
Duration:: Special
Wate:: 400kg
EXPS:: 1493
Value:: 250001

The mapper is an aerial device that generates a detailed planetary map.
This artifact is close to being a robot. 
The device will employ acoustics, lazers, radar and photography to develop its map. 
E.g., buildings, roads, mines, logging, dredging, canals, dams, irrigation, etc.
The map can be reviewed on a monitor or printed out on flammable, water-soluble sheets.
This device is for advancing and developing the story and not for bypassing challenges or puzzles. 



=== Mindlink 

[horizontal]
Vocation:: Mechanic
Duration:: Self Powered
Wate:: 2 kg
EXPS:: 900 
Value:: 195000

:art: psionic_headband.png
:width: 350px
:snark: Psionic head vice
:artist: Andrew Leydenfrost
:date: 1955
:license: CC BY-SA 4.0
:description: Humanoid wearing an uncomfortable electronic device on their head.
include::ROOT:partial$articulate.adoc[]

The mindlink allows an organic persona to communicate with electronic equipment.
The device allows organic personas to peruse files or chat with inorganic consciousnesses.
A simple computer could be read like a book, while a robot could involve in a conversation.
A mindlink cannot bypass encryption, nor does it allow the persona to control the machine.
The larger the machine, the greater the chance mindlink will be able to connect.
When using a mindlink, a mechanic gets a bonus of +42 on computer rolls.

=== Money Counter 

[horizontal]
Vocation:: Nothing
Duration:: Until Destroyed
Wate:: 8 kg
EXPS:: 50
Value:: 15000

The money counter is a computerized box loaded with heaps of artificial (not autonomous) Intelligence and video sensors.
The technology is devoted to the counting of money and the valuation of non-tech artifacts.
A non-tech artifact anything useful to a vocation, for example, Junque or treasure.
The money counter could valuate a broach or Junque but not a gun or grenade.
The machine will grind, chunk, and squeak its way through the evaluation.
When counting currency, the device will always get the correct amount.
If there is enough cultural knowledge, the box will detect counterfeit or outdated currency.
The money counter also acts as a safe storing up to 20 kg of valuable materials.

A money counter is a nothing's vocation computer.
Nothings enjoy a +42 bonus on money-related rolls when using a money counter.
The money counter is worth 2142 EXPS to nothings.

=== Plastix Explosive 

[horizontal]
Vocation:: Mechanic
Duration:: Single Use
Wate:: 1 kg
EXPS:: 299
Value:: 2000

Plastix explosive is an anti-architectural shape charge.
Each charge is moldable to optimized structural damage.
The plastix explosive is safe to work with and can be frozen or liquefied without the risk of detonation.
The explosive has no effective range.
Personas can stand directly beside the explosion with no fear of damage (says the manufacturer).
The debris field or building collapse would be a different story.
In short, this is the safest, most destructive, commercial explosive made.
Plastix is nearly impossible to weaponize, but it often gives a tactical advantage.

One kg of plastix will blow one hex-sized hole in any civilian architectural structure.
Flying debris can be a problem for those caught on the wrong side of a charge (say inside a room).
Technically the plastix explosive imparts 1000 HPS of damage.
A mercenary or mechanic with demolitions skill must apply the plastix to inflict full damage.
All other personas applying the plastix will only inflict 100-600 (1d6*100) hit points of damages.
If 1000 HPS equals a one hex hole, less damage will produce a proportionally smaller hole.

To properly apply plastix explosive requires an easy (24) mechanic task roll.
Detonation of plastix explosives is easy to achieve.
Accidental detonation of plastix explosive is nearly impossible.
There is a 5% chance that the plastique will be silent, doubling its value.
There is also a 15% chance that the plastique will be smokeless, increasing its value by 10%.
Usually, a cache contains 1-8 kg (1d8) of plastix explosive.

=== Psionic Headband 

[horizontal]
Vocation:: None
Duration:: Self Powered
Wate:: 500gms
EXPS:: 590
Value:: 9900611

The psionic headband amplifies an organic persona's psionic abilities.
The psionic headband must be close to the brain and contact the skin.
This artifact does not change the persona's Mind attribute.
However, it does improve the persona's psionic effectiveness.
This artifact doubles the parameters of uncombat mutation effects.
A uncombat mutation with a range of 10 hexes would have a range of 20 hexes.
The persona increases her Mind by 50% when making mental attacks.
For psionic defence, the headband doubles the persona's MND.
The fortified defensive MND of the wearer cannot be less than 15.

A knite cannot wear a psionic headband. 
The knite's connection with the thinkspace must be pure and uninhibited by machines.

=== Recorders 

[horizontal]
Vocation:: None
Duration:: Self Powered
Wate:: Special
EXPS:: 250
Value:: 10000

A recorder is any device that records data.
These recorders record, store, edit, analyze and playback data.
Audio, visual and audiovisual reflect the audiovisual spectrum of anthro personas. 
Every recorder includes one <<_detectors,Detector>>.
The recorder will also be able to record data from the detector as well.
The recorder type includes some unique recording media.
The recorder that also can record telepathy is worth 1000000. 

include::hardware:partial$recorder_artifact_types.adoc[]

=== Robot 

[horizontal]
Vocation:: Mechanic
Duration:: Special
Wate:: Special
EXPS:: Special
Value:: Special

The persona is now controlling a robot.
Initially, this will be a functioning robot that follows the instructions of the persona.
As the robot becomes more damaged, it will likely evolve into a referee persona.
Some robots, like Datalyzers and Hobbots, are cheeky from the start.
A robot is more like an amicable referee persona than a slave.
The players shouldn't use the robot to upset the balance of the game.
Using a robot to destroy plot points will accelerate its acquisition of consciousness.

include::role_playing_system:partial$robot_single_roll.adoc[]

=== Robotic Override 

[horizontal]
Vocation:: Mechanic
Duration:: 5 Uses per Battery
Wate:: 18kg
EXPS:: 2006
Value:: 994000

The robotic override is a focused computer that can reprogram the purpose and ownership of a target robot.
The robotic override connects with the target robot via a full-contact attack or ranged attack.
There is no question that robotic override is anything other than an attack.
The robot must win a roll vs poison intensity 3-30 (3d10) or succumb to the override.
The robot uses its Intelligence attribute to combat the programming poison, not her Constitution.
Mechanics can increase the intensity of the attack by winning task rolls.

Once controlled, the user of the robotic override controls the robot.
The personas can order a combot to clean sidewalks or a hobbot to ram targets.
Persona robots get to make a control factor check every day they are under foreign control.
The more egregious the abuse, the more likely the persona robot is to break free from override.

NOTE: *Persona robots pronounce overridden as overwritten.*

Mechanics earn a bonus of +20 when making robot-related rolls using this device.

==== Full Contact Override (Strike Attack)
The mechanic must get up close and personal with the robot.
The override is the full contact type 68% of the time.
The player must win a Strike attack with the override to inject the override coding.
Some robots are very hard to win an attack roll against, making them resistant to override.
For docile, non-evasive, robots there is no need for the attack roll. 
The pick does not have an 18kg wate, but the pick, cable and backpack do.

==== Ranged Override (Shoot Attack)
The mechanic can beam the override computations from up to 10 hexes away.
The override is the ranged type the remaining 42% of the time.
The player must win a Shoot attack with the override to inject the override coding.
For docile, non-evasive, robots there is no need for the attack roll.


=== Rocket Rollerskates 

[horizontal]
Vocation:: None
Duration:: 1000 km per Battery
Wate:: 4 kg each
EXPS:: 99
Value:: 12000

Rocket rollerskates propel the persona along the ground faster than regular rollerskates.
The skates have a gyroscopically stabilized truck system which helps prevents crashes.
The skates are landlocked and do *not* fly.
They also require a reasonably smooth surface.
They work best on proper roads in civilized areas.

This device only works in pairs (not impaired).
One cannot skate with just one rocket rollerskate. 
The plural is essential.

The skates are fast and move at 31 to 50 (1d20+30) hexes per unit.
When necessary, their handling class is equal to the wearer's DEX.
Dangerous moves will require the player to win driving rolls or crash.

There is a 10% chance that a rocket roller skates will be an identically functioning skateboard.
If the player so desires, the rocket roller skate could be a rocket skateboard instead.


=== Scopes 

[horizontal]
Vocation:: Mercenary
Duration:: 250 Shots per Battery
Wate:: 1 kg
EXPS:: 500 (Special)
Value:: Special

:art: scopes.png
:width: 350px
:snark: Not the mouthwash
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Two boxy shaped and one telescope shaped rifle scopes
include::ROOT:partial$articulate.adoc[]

A scope is a device that aids the player's attack roll.
Artifact scopes range from a sight mounted on a rifle to a gyroscope on a sword.
If the device helps increases the chance of damaging the target, it is a scope.
There are scopes for all weapon types. 
Every scope has an attack roll bonus and a specialization.

.*Scope Checklist*
. Scope Attack Type
. Scope Attack Roll Bonus
. Scope Base Value
. Scope Feature

==== Scope Attack Type
Each scope works with a specific attack type. 
The scope is not interchangeable, and the technology only works on its designated weapon type.
A scope designed for thrusting and striking weapons would not look like a rifle scope.
A scope for Strike weapons could be a box on the hilt or a bracelet.
The scope would then modify the motion of the blade to improve the attack roll.

include::hardware:partial$scope_attack_type.adoc[]

==== Scope Attack Roll Bonus
.1d4 times 30 (1d4*30)
****
The attack roll bonus is +30, +60, +90, or +120
****

The player adds the bonus to her final attack roll.
A scope allows the player to exceed the persona's Max Roll (Max).
For example, a persona with a Max Roll of 710 could generate an attack roll of 800 with a +90 scope.

==== Scope Base Value
The value of this scope is equal to 1000 per to hit bonus.
A scope with +90 to hit is worth 90 000.

==== Scope Specialization
Scope Specialization determines what unique feature the scope has.
The unique ability of the scope works in uncombat situations.
A player can look down a scope to see through the smoke at any time.

include::hardware:partial$scope_feature_type.adoc[]

==== Auto strike
This scope compensates for virtually any error that the persona can make in combat.
An autoscope is the cheat code equivalent for a weapon.
The scope must have line of sight and cannot shoot through cover, concealment or severe weather.
The player must still make an attack roll.

A successful attack roll becomes a critical hit. 
Jump to xref:uncombat:critical_checks.adoc#_critical_hit[Critical Hits,window=_blank].
A miss on the attack roll becomes a regular hit.
A weapon malfunction is the only way to miss.

There is an *EXPS penalty* for using an autoscope. 
Combat experience is reduced to 10% using the autoscope. 
The value of this artifact is 10000 times the base attack bonus.

==== Climate 
The climate scope compensates for all meteorological conditions except darkness.
The scope removes all penalties for wind, fog, rain, snow etc. 
The climate scope is worth double the base value of the scope.

==== Darkness
This night scope cancels penalties for darkness.
The scope uses a combination of IR, UV, and whatever else helps the darkened attack.
The darkness scope does not give up its position unless intentionally detected. 
There is no value bonus for a darkness scope.

==== Gravity 
The gravity scope allows the weapon to be unimpeded by 0 to 8 gravities.
In ZOG, the scope compensates for kickback and protects its user from being thrown around.
This scope is exatmo hardened.
The gravity specialization triples the value of this scope. 

==== Multi-scope 
The multi-scope is a combination of multiple scopes into a single artifact.
So a multi-scope could be a climate and darkness scope.
Each scope gets another roll on the attack rolls bonus section. 
So multi-scope made up of +60 climate, and +90 Darkness would have a +150 attack bonus.
It would also attack cleanly in any weather or darkness.
Each visit to multi-scope adds another scope to a maximum of three scopes and a maximum attack roll bonus of +250.
The value of a multi-scope is the combined value of the scopes times 10. 

==== Pacifist
The pacifist scope is a non-lethal auto strike scope.
The scope determines a target's most vulnerable points.
Instead of delivering a killing attack, the pacifist scope delivers a debilitating attack.
A pacifist scope has an attack roll bonus, like all other scopes.

After a successful attack roll, the player rolls damage. 
The pacifist scope converts the damage into a percent chance to stun the opponent.
Each point of damage inflicted will have a 2% chance of stunning the target for 0 to 9 (1d10-1) units.
A pacifist scope does not work with area of effect weapons or weapons of malicious destruction.
For example, this scope does not work with a fusion pistol or flame thrower.
The value of the scope is increased by 1000000.

==== Range
Range scopes increase the effective range of the weapon.
The range extender scope doubles the weapon's range and halves the decay.
The scope optimizes a projectile's decay by compensating for wind and gravity effects.
A weapon with a range of 50 and decay of -100 improves to a range of 100 and a decay of -50.
For Strike attacks, the range extender allows the weapon to make a Fling attack with a range of STR in hexes.
There is no increased value for a range extender scope.

==== Smoke
The smoke cutting scope can sight through mist, fog, smoke, and other gaseous obfuscations.
The player suffers no attack roll penalties in smoke when using this scope. 
There is no value modifier with a smoke scope.

=== Sincerity Machine 

[horizontal]
Vocation:: Nothing
Duration:: 1 year per Battery
Wate:: 1 kg
EXPS:: 230
Value:: 2000

The sincerity machine improves the persona's Charisma by manipulating the voice.
A sub-linguistic vocalization analyzer modifies the persona's voice such that anything she says sounds nice.
The effect is excellent for negotiation, and during talks increases the persona's Charisma by 3-8 (1d6+2).
A persona can alter the sincerity machine to have a reverse effect which will get the expected reaction.
When combined with good looks, and clever wording, even coarse profanities sound like compliments.
A vet will earn a bonus of +15 for all rolls on conscious patients.
This device does not work with powered armour.

This Charisma boost does not alter the persona's Charisma attribute. 
If the machine loses power, all Charisma bonuses immediately disappear.



=== Superconductor Suit 

[horizontal]
Vocation:: None
Duration:: Until Destroyed
Wate:: 0.6 kg
EXPS:: 50
Value:: 130000

:art: sony_stealth_suit_action.png
:width: 450px
:snark: High tech haute couture
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Humanoid jumping into a cave wearing a skintight outfit and firing a pistol.
include::ROOT:partial$articulate.adoc[]

The superconductor suit is a skintight jumpsuit that improves Dexterity.
Typically the superconductor suit is worn underneath clothing or armour.
However, the superconductor suit is rather stylish on its own.
The superconductor threads include sensitive biotransceivers
The transceivers pick up nerve impulses and bypass the regular nervous system along superconducting threads.
The suit allows the persona to react faster and move faster, improving the persona's Dexterity.
The suit has a DEX bonus of plus 3-8 (1d6+2) points.
This device does not work with powered armour.

This device does not permanently change the persona's Dexterity attribute.
Once removed or damaged, the persona returns to her normal DEX attribute value.
The suit is delicate and is damaged every time the persona is damaged. 
For gameplay, the suit usually starts with 1000 hit points.
Once reduced to zero HPS, it stops conducting. 

=== Materiel 

[horizontal]
Vocation:: Special
Duration:: Special
Wate:: Special
EXPS:: Special
Value:: Special

Materiel is artifacts that exist to make other artifacts shine.
Types of materiel are batteries, ammunition, fuel, manuals, software and spare parts.
Materiel does not have a function on its own. 
However, some materiel is precious.

It is also reasonable to have materiel align with existing expedition artifacts.
For example, a player may roll extra batteries for her lazer pistol.
Or one persona may have the software for another persona's vocation computer.

Take a jump over to xref:hardware:materiel.adoc[Materiel,window=_blank].

=== Targeting Computer 

[horizontal]
Vocation:: Mercenary
Duration:: 50 uses per Battery
Wate:: 20.8 kg
EXPS:: 395
Value:: 900000

A targeting computer helps aim artillery or missiles. 
The persona targets the artillery using the binoculars wired to the artillery box.
The targeting computer either moves the weapon on a platform or barks directions.

Non-mercenary vocations can use a targeting computer to fire artillery. 
They cannot fire on moving targets and get no attack roll bonuses.
Under normal circumstances, personas not trained in artillery cannot use it.

A mercenary using a targeting computer can target moving objects like vehicles or whales.
When firing on a stationary target, the mercenary gets an attack roll bonus of +100.
There is no bonus awarded when firing on moving targets.
Computer targeting is much faster than manual targeting, only taking 1-10 (1d10) units.
The targeting computer gives mercenaries and mechanics +20 on any artillery-related rolls.

=== Tesseract Box 

[horizontal]
Vocation:: None
Duration:: Approach Infinity
Wate:: Approach Infinity
EXPS:: 42
Value:: Special

A tesseract box is a multi-roomed artifact that appears small and mundane on its outside.
A tesseract box only occupies one hex of physical space.
On the inside, the tesseract box can contain 100s of medium-sized rooms. 
A tesseract box is a campaign-altering artifact.
It would not be uncommon to find referee personas inside the tesseract box. 
Such an artifact can be the basis of a campaign or even an entire Sciency Fiction series.

A tesseract box will have 100 to 1000 (1d10*100) rooms arranged in whatever fashion the referee sees fit.
These rooms are not in the physical space but may exist in the interstitium of physical space (aka xref:appendices:generic_mythos.adoc#_the_spaces[hyperspace,window=_blank]).
The rooms are only accessible through the tesseract box entrance. 
Any items brought into the tesseract box must fit through the single exterior opening, and that is a normal-sized door.

A tesseract box can be fitted with a xref:hardware:spacecraft.adoc#_special_drives[Special Drive,window=_blank].
Since the box has a special relationship with hyperspace, its jump drive can travel further than usual jump drives.
The box cannot have any other kind of spacecraft drive, as the box has far too much wate.
No external force can move a tesseract box.
The box has incalculable wate but does not influence local gravity.

The value of a tesseract box is irrelevant because no owner will part with hers until she is dead.n

=== Timepieces 

[horizontal]
Vocation:: Nothing
Duration:: Until Time Runs Out
Wate:: Special
EXPS:: Special
Value:: Special

Artifact timepieces are also calendars, thermometers, and altimeters.
The timepieces are self-setting and conveniently adjust themselves to new planetary systems.
Prolonged exposure to another planetary rotation will also reset the calendar.
The timepiece can recall all older chronological cycles without difficulty.
Any artifact timepiece will automatically synchronize with nearby watches.

:art: hollow_watch.png
:width: 250px 
:snark: Watch this space.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Obvious watch with wristband no face. 
include::ROOT:partial$articulate.adoc[]

There is a 90% chance the timepiece is part of another artifact.
Allowing for another roll on the TOYs.
For example, the timepiece could be in a rifle or a microwave oven.

include::hardware:partial$timepiece_artifact_types.adoc[]

=== Visual Aids 

[horizontal]
Vocation:: None
Duration:: Special
Wate:: 1 kg
EXPS:: 75
Value:: Special

:art: low_tech_vizaids_desat.png
:width: 450px
:snark: Nick's M2V2
:artist: Studiostoks
:date: 2015
:license: CC BY-SA 4.0
:description: Humanoid wearing an enormous convoluted mechanical visor.
include::ROOT:partial$articulate.adoc[]

The visual aids are a host of goggles that help persona's through the darkness, smoke, or worse.
Visual aids are often called vizauds, vizaids, optical enhancers or happy goggles.

include::hardware:partial$visual_aid_types.adoc[]

Binox:: 
These are electronic binoculars that allow the persona to see further and with greater detail.
The user can adjust the magnification, and the device will give the range of significant objects.
Binox are passive and have no detectable emissions.
Binoculars are worth 100. 

Flexiscope::
The flexiscope is a flexible light pipe.
The light pipe can be bent in any direction allowing the persona to look around corners.
This device easily attaches to other vizauds.
The flexiscope is worth 1100.  

Infrared::  
These goggles allow the persona to see things in the dark.
They employ infrared imaging tech to do so.
IR visual aids have a value of 500.

Macroscopic::
Macroscopic goggles use computers and lenses to increase the persona's field of view. 
The goggles are perfect for finding things on open plains or exatmo.
They are flash-protected and blinding attacks are ineffective.
These goggles grant the persona a +10 on any ambush detection rolls made.
Macroscopic goggles are worth 20000  

Microscopic::
These glasses are very much like microscopes attached to the eyes.
They allow the persona to zoom in on small areas and expand the image thousands of times.
Microscopic goggles give a persona +20 on any miniature-related rolls.
Binocular microscopic goggles are worth 10000.

NIX Magic Multi-Vision Visor:: 
The NIX corporation makes incredibly complex and comprehensive equipment.
The multi-vision visor is so detailed that no one knows precisely what it does.
All M2V2s will have infrared, binox, and anti-flash screens as standard.
Other visual aids may also be present, smoke cutting, x-ray vision, ultravision, macroscopic, and microscopic.
There is a 17% chance that a particular visual aid will be present.
For example, if the persona needs radar there is a 17% radar vision will be present.
The vision type may not be present the next time, but it may present the time after that.
Nix Magic Multi-Vision Visor is worth 10000000. 

Smoke::
The smoke-cutting visor allows the persona to function as though there was no smoke obscuring her vision.
The scope works equally well with mist, fog, and other particulate matter.
The smoke will still asphyxiate the persona, but it does so without visual impairment.
The smoke visor is worth 250.

Ultravision:: 
These goggles allow the persona to see things in the dark.
They employ ultraviolet imaging tech to do so.
UV visual aids have a value of 500.

X-Ray:: 
The wearer can adjust the x-ray goggles to see inside things at various depths.
They have a range of 1 hex and can penetrate up to one hex of hull metal.
These goggles are detectable as radioactive by canines.
Xray goggles have a value of 15000.

ZBGs::
The abbreviation G stands for glasses, and ZB are the initials of a universally infamous, excellent chicken.
The glasses always appear as ordinary glasses, but they go opaque when they detect the Kirlian auras of danger. 
The ZBGs will even detect danger behind the persona.
The glasses are special to nothings and will count as 4242 EXPS.
ZBG vizauds have a value of 42042. 

=== Waste Disposer 

[horizontal]
Vocation:: Nothing
Duration:: As Needed
Wate:: 15 kg
EXPS:: 859
Value:: 36000

:art: machine_thing.png
:width: 450px
:snark: Wasting resources for waste resource
:artist: Louis Glanzman
:date: 1954
:license: CC BY-SA 4.0
:description: Humanoid standing in front of techno tube hold a techno thing.
include::ROOT:partial$articulate.adoc[]

A waste disposer is an entirely safe disintegration device (or so the manufacturer says).
Waste is placed into a drawer, the drawer is closed, and the trash is disintegrated with a poof noise.
The drawer can handle up to 25 kg of waste at a time.
The disintegrator will open the drawer and eject any living materials or moving objects.
The disintegrator harnesses energy released from the previously disintegrated materials.
There will always be just enough energy for the subsequent disintegration.
The waste disposer will disintegrate itself if subject to tampering.

