= Generation

Let the chaos begin.

The referee can make the plethora of 1d100 (decidie) rolls needed to generate an artifact.
The referee will often involve the players to make the decidie rolls. 
Hence the constant reference to the 'player' is rolling.
The referee usually secretly records the toy information to preserve the element of the unknown.

The player rolls on the Toy Category Table to determine the artifact category.
From this table, the referee jumps to the appropriate category and generates the specific toy type.
The player rolls 64 on the 1d100 indicating the Pharmaceutical category.
The referee jumps to pharma and generates the specific pharma type.

== Raw Roll
Anything goes roll on the Technological Object Yield System. 

include::hardware:partial$toys_departments_list.adoc[]

== Plot Protected
A roll limited to toys that don't destroy plot.

include::hardware:partial$toys_plot_safe.adoc[]

== UnCombat 
We don't need to damage and destroy.

include::hardware:partial$toys_uncombat.adoc[]

== Combat
We need to damage and destroy.

include::hardware:partial$toys_combat_only.adoc[]

== Cool Stuff 
We only want cool things. 
If it is not cool roll again. 

include::hardware:partial$toys_cool_only.adoc[]

== Startifacts
Specifically looking for toys for fresh personas jump to xref:hardware:startifacts.adoc[Startifacts,window=_blank].