= Guns

:art: pistols_pistols-pistols.png
:width: 550px
:snark: Pistols can have any shape.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Four futuristic pistols in a row.
include::ROOT:partial$articulate.adoc[]

:art: rifles_rifles_rifles.png
:width: 550px
:snark: Rifles can have any shape.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Three futuristic rifles in a row.
include::ROOT:partial$articulate.adoc[]

Guns are personal combat weapons designed to delivery damage and destruction.

.*Gun Checklist*
. <<_generate_type,Gun Type>>
. <<_power_level,Power Level>>
. <<_description,Description>>
. <<_parameters,Gun Parameters>>

== Generate Type

include::hardware:partial$list_of_guns.adoc[]

== Gun Data

=== Power Level
Power level is a generic term for calibre or the weapon.
Power level could be the diameter of the bullet or the amount of lazer force each attack delivers.
The default power level is medium power, and only if a change is needed is this table used.
There are five different power levels, and the most common is medium power. 

include::hardware:partial$gun_calibre_types.adoc[]

=== Description
Guns typically look like rifles or pistols. 
Very low tech or very high tech guns may have unique shapes. 
To modify a toys' description jump to xref:software:CH55_Appearances.adoc[Appearances,window=_blank].

=== Parameters

==== Attack Type 
The attack types indicate the frequency of attack that the powered projectile weapon has.
Attack Shoot has one attack roll per unit.
Attack Types D and E have two and three attack rolls per unit.
Attack Flotto is for Full auto, and the player makes five attack rolls per unit with some special rules. 
For all the deets jump to xref:combat:attack_types.adoc[Attack Types,window=_blank].

==== Range 
The range is how far the weapon can shoot and retain its accuracy.
The range is a hardware limitation and does not reflect the skills of the persona in any way.
The weapon's range is limited by wavering bullets, dissipating charges, or decaying material.

The range lists a number and a negative number in brackets, 120h (-230).
The first number is the range in hexes where there are no range penalties.
The number in brackets is the per hex penalty for targets beyond the weapons range (first number).

A weapon has the following range parameters 120h (-230).
The persona can shoot any target within 120 hexes with no penalties.
A target 121 hexes away has a -230 attack roll penalty.
A target 123 hexes away has a -690 attack roll penalty.

The range parameters of 100h (-1000) indicate a weapon with a maximum range of 100 hexes and no further.

The number in brackets was previously called the decay value of the weapon.

==== Accuracy 
Accuracy simply reflects the accuracy of the gun.
The better balanced and better designed the weapon, the easier it is to hit the target.
The player adds the accuracy parameter of the gun to her attack roll.
A weapon with an accuracy of +50 adds +50 to every kilodie roll the player makes with the weapon. 

==== Damage 
Damage is the number of hit points the weapon subtracts from the target with a successful attack roll.
Most often, the damage parameter is a number range with the suggested die roll in brackets.
For example, 4-48 (4d12) indicates a weapon that inflicts 4-48 hit points of damage, and four twelve-sided dice will generate the value.
If there is a list of five different damage ranges, such as 5-60, 5-50, 4-48, 3-30, 2-20, then the weapon has power levels.

==== Magazine 
The magazine lists the number of attack rolls before having to reload.
Emptying the magazine can mean using up all the bullets, expending all the fuel or draining the battery.
A gun with a magazine of 45 can shoot 45 rounds before the persona must reload.

==== Wate 
Wate lists the unloaded wate of the gun in kilograms.
There are several different parameters for wate.
The first number is the wate of the weapon, and the number in parenthesis is the wate of the ammunition.

The weapon wate is usually a single number, but weapons with different power levels (calibres) have three values.
The first wate is for high powered versions, the middle wate is for the medium powered version, and the last wate is for low powered versions.
For example, 4.62, *2.75*, and 1.95 represent 4.63 kgs for the high powered version (XHP and HP), 2.75 kgs for the medium powered version (MP) and 1.95 kgs for the low powered versions (LP and XLP)

The ammunition wate is usually a single value in brackets.
If the value is a percentage (like 1.5%), the ammunition wate is a percentage of the weapon wate.
If the value is a precise wate (200 gms), the ammunition wate is specifically that amount.
If the value in the brackets says (battery), the ammunition wate is that of a battery (usually 100 gms).
If the value in the brackets says (fuel), the ammunition wate is that of the fuel (usually negligible).

Ammunition wate is for encumbrance purists.

==== EXPS 
The persona wins this experience point award for identifying the gun. 
The player may identify the gun by deduction or firing. 

==== Value 
The value indicates the MSRP (Money Suggested in RolePlaying) of the gun in eps.
The value in brackets is the value of the ammunition in eps.


== Gun Catalogue



=== Aerosol Pistol 

[horizontal]
Attack Type:: Shoot
Range:: Double (-1000)
Accuracy:: -150
Damage:: Special
Magazine:: 3
Wate:: 0.5kg
EXPS:: 500
Value:: 2000

:art: pistol_aerosol.png
:width: 250px
:snark: Convert ozone damage to real damage.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Pistol with chamber for holding gas canister.
include::ROOT:partial$articulate.adoc[]

An aerosol pistol amplifies the range and efficiencies of aerosols.
The aerosol pistol doubles the range and triples the number of charges.
The pistol does not alter the area of effect, duration, or damage of an aerosol.
The persona cannot disconnect aerosol canisters from the pistol before extinguishing all charges.
An aerosol with a ten hex range and three hex area of effect would have a 20 hex range and a three hex area of effect.

A malfunction indicates a loss of all remaining charges.
There is a slim chance (determined by the ref) of the weapon exploding on malfunction.



=== Aerosol Rifle 

[horizontal]
Attack Type:: Shoot
Range:: Triple (-1000)
Accuracy:: -50
Damage:: Special
Magazine:: 5
Wate:: 1.6kg
EXPS:: 500
Value:: 8000

:art: aerosol_rifle.png
:width: 450px
:snark: Convert Ozone damage to real damage.
:artist: JEShields
:date: 2014
:license: Copyright JEShields Stock Art. jeshields.com
:description: Fancy rifle with extra bulbs and things.
include::ROOT:partial$articulate.adoc[]

An aerosol rifle amplifies the range and efficiencies of aerosols.
The aerosol rifle triples the range and quintuples (five times) the number of charges.
The rifle does not alter the area of effect, duration, or damage of an aerosol.
The persona cannot disconnect aerosol canisters from the rifle before extinguishing all charges.
An aerosol with a ten hex range and three hex area of effect would have a 30h range and the same area of effect.

A malfunction indicates a loss of all remaining charges.
There is a slim chance (determined by the ref) of the weapon exploding on malfunction.


=== Antimat Pistol

[horizontal]
Attack Type:: Shoot
Range:: 90h (-100)
Accuracy:: -30
Damage:: Special
Magazine:: 1 + Batteries
Wate:: 2.7kg (5gm)
EXPS:: 900
Value:: 100000 (10000)

:art: pyrotomic_disintegrator_pistol.png
:width: 250px
:snark: Patented pyrotomic disintegrator pistol
:artist: G.C. Schaible
:date: 1953
:license: CC BY-SA 4.0
:description: Toy pistol from patent office 1953.
include::ROOT:partial$articulate.adoc[]

An antimat pistol launches a micro-particle of antimatter suspended in a lattice of electrons.
This lattice will shatter when it hits a liquid or solid.
The resulting explosion will instantly annihilate 50 kg of matter.
The explosion releases a blast of heavy particles and superheated gases that will affect everything within a ten hex radius regardless of cover.
Everything in the ten hex radius will take 25 to 70 (5d10+20) hit points of damage.

A malfunction with this weapon means the electron lattice has shattered within the gun.
A malfunction usually indicates a harmless misfire, but if the ref is in a bad mood, the gun may disintegrate itself.


=== Antimat Rifle 

[horizontal]
Attack Type:: Shoot
Range:: 150h (-95)
Accuracy:: 0
Damage:: Special
Magazine:: 2 + Batteries
Wate:: 5kg (10gm)
EXPS:: 900
Value:: 375000 (15000)

:art: pyrotomic_disintegrator_rifle.png
:width: 450px
:snark: Patented pyrotomic disintegrator rifle
:artist: G.C. Schaible
:date: 1953
:license: CC BY-SA 4.0
:description: Toy rifle from patent office 1953.
include::ROOT:partial$articulate.adoc[]

An antimat rifle launches a micro-particle of antimatter suspended in a lattice of electrons.
This lattice will shatter when it hits a liquid or solid.
The resulting explosion will instantly annihilate 100 kg of matter.
The explosion releases a blast of heavy particles and superheated gases that will affect everything within a 25h radius regardless of cover.
Everything in the 25h radius will take 25-70 (5d10+20) hit points of damage.

A malfunction with this weapon means the electron lattice has shattered within the gun.
A malfunction usually means a harmless misfire, but if the ref is in a bad mood, the gun may disintegrate itself.

=== Beegun 

[horizontal]
Attack Type:: Shoot
Range:: 150h (-100)
Accuracy:: 0
Damage:: Death
Magazine:: 1
Wate:: 2kg (200gm)
EXPS:: 500
Value:: 250000 (30000)

:art: bee_gun.png
:width: 250px
:snark: 1B and not 2B.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Pistol with image of bee on casing.
include::ROOT:partial$articulate.adoc[]

The beegun's activation chamber excites a normally docile insect into a poisonous rage.
After two units of warming up, the beegun is ready to fire.
If the player wins an attack roll, the insect will inject a deadly and instantaneous poison.
The target must save vs intensity 19 to 24 (18+d6) poison or die.
If the player wins the saving roll, her persona will be comatose for 1-4 days.
The ammunition for a beegun is not reusable.

A malfunction can only occur with the ammo of this weapon.
A malfunction indicates a non-poisonous projectile.


=== Bolt Action rifle

[horizontal]
Attack Type:: Shoot
Range:: 150 (-50)
Accuracy:: +75
Damage:: 4-48, 3-36, *3-30*, 3-24, 2-20
Magazine:: 15
Wate:: 3.7 kg, *3.4 kg*, 3.1 kg (1.5%)
EXPS:: 400
Value:: 500 (1)

:art: bolt_action_rifle.png
:width: 450px
:snark: Classic single shot long gun.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Rifle with wooden stock and bolt for chambering bullets.
include::ROOT:partial$articulate.adoc[]

The bolt action rifle is your familiar mundane terran hunting, or target, rifle.
This weapon can also be called a pump-action, revolving chamber, steam, or pneumo-rifle.

A malfunction with this weapon is an ammo misfire and not a jam.

=== Cryogun 

[horizontal]
Attack Type:: Shoot
Range:: 15h (-1000)
Accuracy:: 0
Damage:: 4-24 (4d6)
Magazine:: 10 per Battery
Wate:: 2kg + Battery
EXPS:: 700
Value:: 6000

:art: pistol_cryo.png
:width: 250px
:snark: Freeze! 
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Futuristic pistol with square large barrel.
include::ROOT:partial$articulate.adoc[]

A cryogun precipitously drops the temperature creating ice, snow and death.
This weapon inflicts both damage and freezes the target in place.
Every target within the 15h x 2h swath suffers the damage.

Damage is rolled once for the entire attack.
There is also a chance that targets will get frozen in place.
The chance of being entrapped is 1% per hit point of damage.
With 15 hit points, there is a 15% chance of trapping a medium-sized in ice.
There would also be a 15% chance of freezing swords in scabbards, buttons in the on position, steering wheels straight ahead, etc.
The chance of freezing must be checked for each target.

The freezing effects of a cryogun will melt away in 6 to 60 units.
Heating will halve the melting time.

This weapon is also known as a Frigid Aire or a cop gun (they don't have to yell "freeze." They just pull the trigger).

A malfunction results in the loss of a charge.

=== Death Ray Pistol
[horizontal]
Attack Type:: Shoot
Range:: 40 (-99)
Accuracy:: -125
Damage:: 2-16 (2d8)
Magazine:: 5 per Battery
Wate:: 1.25kg (1.5%) + Battery
EXPS:: 250
Value:: 200 (1)

:art: death_ray_pistol.png
:width: 250px
:snark: Death on demand.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Pistol with funnel like barrel.
include::ROOT:partial$articulate.adoc[]

The death ray pistol attacks the electrochemical life force of organic creatures.
The beam attack must score a hit to be effective.
The death ray inflicts 2-16 (2d8) hit points of damage plus a good chance of death.
Any target hit by the death ray must save versus intensity 3-24 (3d8) poison or die.
The intensity of the killing attack is generated every time the weapon is fired.

This weapon is also called a kill-o-zap gun or a terminator.

The malfunction of this weapon will occasionally call for an attack on the firer.
Normal malfunctions result in the loss of all remaining charges.

=== Derringer 

[horizontal]
Attack Type:: Shoot
Range:: 40h (-99)
Accuracy:: -125
Damage:: 2-16 (2d8)
Magazine:: 5
Wate:: 1.25 (1.5%)
EXPS:: 250
Value:: 200 (1)

:art: gun_soft_serve.png
:width: 250px
:snark: Disposable disposer.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Modern fake looking pistol with swirly barrel. 
include::ROOT:partial$articulate.adoc[]

The derringer is a compact and concealable weapon pistol.
It is composed of plastic alloys, and is coated with fingerprint resistant materials.
The derringer can be melted to nothing by submerging it in boiling water. 
When being concealed, this weapon will give bonuses of +20 on sneaky PT rolls.

This weapon is also known as a family planner, or a Saturday night special.

A malfunction will jettison dud ammo and jam the weapon.

=== Disintegration Gun 

[horizontal]
Attack Type:: Shoot
Range:: 100h (-115)
Accuracy:: 0
Damage:: 8-64 (8d8); Special
Magazine:: 5
Wate:: 4.5kg + Batteries
EXPS:: 20
Value:: 500 000 + Batteries

:art: disintegration_gun.png
:width: 450px
:snark: Disassembly inspired.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Futuristic boxy looking gun with dish instead of barrel.
include::ROOT:partial$articulate.adoc[]

The disintegration gun turns solids into elemental particles. 
The nicely organized matter turns into a cloud of dust.
This weapon is very temperamental, and outcomes vary each time the trigger is pulled.
Like all good disintegration weapons it is capable of making a target disappear.
The cascade of disintegration only begins if a hit is scored on a target.
A miss will not result in a disintegration cascade.
Every target hit will take the assigned 8-64 (8d8) hit points in damage.
If the disintegration cascade starts much more damage follows.

.*Disintegration Cascade*
Each attack has a chance of disintegrating it's target. 
The disintegration cascade will affect 1-100 (1d100) kgs of wate.
The amount of disintegrated matter is unique each time.
The greater the amount of matter affected the greater the chance the cascade will fail.
There is a 1% chance per kg of matter that the attack will fail.

So an attack that is affecting 42 kgs of a target has a 42 percent chance of failing.
Basically the player immediately rolls the 1d100 again. 
If the second roll is greater than the amount of wate things disintegrate.
Using the above example of a 42 kg cascade the player immediately rolls again.
If the roll is 42 or higher, the cascade is successful and 42 kgs disappears.
If the roll is 41 or lower the cascade fails and the weapon inflicts 8-64 hit points.

.*Disintegration Damage*
If the target has a wate less than the amount of matter disintegrated it disappears.
If it is a persona she is irrevocably destroyed and suffers classic disintegration.
Partial disintegration inflicts 1-20 (1d20) hit points in damage per kg destroyed.
For example, a 100 kg target that has 21 kg disintegrated will take 8-64 plus 20-400.
Very few personas survive a disintegration event. 

.*Other Stuff*
The disintegrated matter must be semi-contiguous.
For example, a hit on the backpack, would annihilate the backpack, and send its contents clattering to the floor.
If hit location is important jump to xref:combat:hit_locations.adoc[Hit Location].
If there is trouble deciding if matter is contiguous or not jump to xref:uncombat:sphincter_rolls.adoc[Sphincter Roll]

WARNING: Nomenclature overlap could lead to different methods of disintegration. User must be remain wary.

A weapon malfunction indicates an internal disintegration event.
This will most likely destroy the weapon.
This gun is also known as a vaporizer, a duster and a dismodulator.

=== Electron Pistol 

[horizontal]
Attack Type:: Shoot
Range:: 100h (-60)
Accuracy:: 0
Damage:: 2-24, 2-20, *3-18*, 2-16, 1-15
Magazine:: 10 per Battery
Wate:: 1.3 kg, *1.0kg*, 0.8 kg + Battery
EXPS:: 500
Value:: 5000 + Battery

:art: tom_corbett_pistol.png
:width: 250px
:snark: Zapping pistol
:artist: M. Hirsch
:date: 1953
:license: CC BY-SA 4.0
:description: Futuristic pistol from Tom Corbett TV show merchandise.
include::ROOT:partial$articulate.adoc[]

The electron pistol releases a beam of electron tearing molecules.
This pistol's electron beam is unaffected by force fields.
An electron pistol's beam is not absorbed by the force field and damages the target.
The damage is subtracted from the  force field as well as the target.
The medium powered electron pistol damage is 3-30 and its wate is 1 kg.

A malfunction results in a fully drained battery.


=== Electron Rifle 

[horizontal]
Attack Type:: D
Range:: 170h (-60)
Accuracy:: +50
Damage:: 5-50, 4-48, *4-40*, 4-32, 3-30
Magazine:: 15 per Battery
Wate:: 4.2 kg, 4.0 kg, 3.8 kg (+ Battery)
EXPS:: 750
Value:: 20000 + Battery

:art: tom_corbett_rifle.png
:width: 450px
:snark: Zapping rifle
:artist: M. Hirsch
:date: 1953
:license: CC BY-SA 4.0
:description: Futuristic rifle from Tom Corbett TV show merchandise.
include::ROOT:partial$articulate.adoc[]

A minute organized beam of electrons massacre the target's molecules.
The beam has the ability to punch holes in force fields.
If a hit is made, the attack damages both the target and the force field.
The medium powered electron rifle damage is 4-40 and its wate is 4.0kg.

A malfunction results in a fully drained battery.



=== Fission Pistol 

[horizontal]
Attack Type:: D
Range:: 90h (-60)
Accuracy:: 0
Damage:: 5-50 (5d10)
Magazine:: 10 per Battery
Wate:: 1.5kg + Battery
EXPS:: 500
Value:: 8000 + Battery

:art: fission_pistol.png
:width: 250px
:snark: Zap zap.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Pistol with narrowing barrel.
include::ROOT:partial$articulate.adoc[]

The fission pistol creates an energy wave that super heats hydrogen molecules.
Obviously, this weapon can only be used in hydrogen laden atmospheres (air and water are good examples).
Charges are still drained if the weapon is fired in the absence of hydrogen.
This device is thoroughly waterproofed.
Some cynics call this weapon a kettle-gun.

A malfunctions will indicate a back flash, resulting in damage to the firer.



=== Fission Rifle 

[horizontal]
Attack Type:: E
Range:: 110h (-70)
Accuracy:: +50
Damage:: 6-72 (6d12)
Magazine:: 15 per Battery
Wate:: 4.25 + Battery
EXPS:: 950
Value:: 32000 + Battery

:art: 2b_or_not_2b.png
:width: 450px
:snark: Zap zap zap.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Stylized futuristic rifle narrowing in height towards muzzle.
include::ROOT:partial$articulate.adoc[]

The fission rifle creates an energy wave that super heats hydrogen molecules.
Obviously, this weapon can only be used in hydrogen laden atmospheres (air and water are good examples).
Charges are still drained if the weapon is fired in the absence of hydrogen.
This device is thoroughly waterproofed.
Some cynics call this weapon a kettle-gun.

A malfunctions will indicate a back flash, resulting in damage to the firer.



=== Full Auto Lazer Pistol 

[horizontal]
Attack Type:: Shoot, Shoot-2, Shoot-3, Flotto
Range:: 80h (-60)
Accuracy:: +30
Damage:: 4-40, 3-30, *2-20*, 2-16, 1-10
Magazine:: 30 per Battery
Wate::  2.3 kg, *2.15 kg*, 2.0 kg + Battery
EXPS:: 700
Value:: 8000 + Battery

:art: pistol_lazer_sotto.png
:width: 250px
:snark: Pew pew pew pew pew.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Pistol with no barrel.
include::ROOT:partial$articulate.adoc[]

The full automatic lazer pistol is a hand held lazer weapon with a rapid-fire option.
The F weapon type releases 15 charges in one unit.
When flotto is employed the player makes 5 attack rolls in one unit.
Each successful attack roll scores 0-3 (d4-1) lazer bolts of damage.
For a discussion of full auto (flotto) attacks jump to xref:combat:attack_types.adoc#_type_f_attacks[Flotto Attacks].

The medium powered full auto lazer pistol damage is 2-20 and its wate is 1.8kg.
This weapon can also be dubbed as a flap gun or flotto lazer pistol.

A malfunction of this weapon indicates overheating and shuts down for a few minutes.


=== Full Auto Lazer Rifle 

[horizontal]
Attack Type:: Shoot, Shoot-3, Flotto
Range:: 120h (-60)
Accuracy:: +70
Damage:: 5-50, 4-40, *3-30*, 2-20, 2-16
Magazine:: 45 per Battery
Wate:: 4.1 kg, *4.0 kg*, 3.9 kg + Battery
EXPS:: 700
Value:: 12000 + Battery

:art: octo_cannon.png
:width: 550px
:snark: Octo merc suggests you remain calm
:artist: Hezekiah Butterworth, Edmund Ollier, HM
:date: 1891, 1871, 2018
:license: CC BY-SA 4.0
:description: Floating octopus operating an old school gatling gun.
include::ROOT:partial$articulate.adoc[]

The full automatic lazer rifle is a two handed weapon with a rapid fire option.
The F weapon type releases 15 charges in one unit.
When flotto is employed the player makes 5 attack rolls in one unit.
Each successful attack roll scores 0-3 (d4-1) lazer bolts of damage.
For a discussion of full auto (flotto) attacks jump to xref:combat:attack_types.adoc#_type_f_attacks[Flotto Attacks].

The medium powered full auto lazer rifle damage is 3-30 and its wate is 4.0kg
This weapon is also known as a lazer Gatling, a fair ("faller") gun, or a flotto lazer rifle.

A malfunction of this weapon results in the loss of a charge.
So 1 charge for weapon Shoot attack or 15 charges for weapon type F. 



=== Full Auto Pistol 

[horizontal]
Attack Type:: Shoot, Shoot-2, Flotto
Range:: 60 (-70)
Accuracy:: 0
Damage:: 3-30, 2-20, *2-16*, 2-12, 1-10
Magazine:: 15
Wate::  2.0 kg, *1.5 kg*, 1.0 kg (1.5%)
EXPS:: 350
Value:: 1000 (1)

:art: pistol_flotto.png
:width: 250px
:snark: Compact full otto.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Pistol with extended mag, scope and stock.
include::ROOT:partial$articulate.adoc[]

A full automatic pistol fires bullets, and tosses outspent shell casings.
The F weapon type releases 15 rounds in one unit.
When flotto is employed the player makes 5 attack rolls in one unit.
Each successful attack roll scores 0-3 (d4-1) rounds of damage.
For a discussion of full auto (flotto) attacks jump to xref:combat:attack_types.adoc#_type_f_attacks[Flotto Attacks].
The rate of fire is determined by trigger squeeze.

The medium powered full-auto pistol damage is 2-16 and its wate is 1.5kg
This weapon is alternately called a machine pistol, or flotto pistol.

Malfunction with this weapon indicates a mechanism jam.


=== Full Auto Rifle 

[horizontal]
Attack Type:: Shoot, Shoot-2, Shoot-3, Flotto
Range:: 90h (-44)
Accuracy:: +50
Damage:: 4-48, 4-32, *3-30*, 3-24, 2-20
Magazine:: 45
Wate::  3.9 kg, *3.6 kg*, 3.3 kg (1.5%)
EXPS:: 700
Value:: 4000 (1)

:art: flotto_rifle_drum.png
:width: 450px
:snark: Sounds like a drum roll.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Old timey drum fed machine gun.
include::ROOT:partial$articulate.adoc[]

The full-auto rifle is the standard weapon of military service.
The F weapon type releases 15 rounds in one unit.
When flotto is employed the player makes 5 attack rolls in one unit.
Each successful attack roll scores 0-3 (d4-1) rounds of damage.
For a discussion of full auto (flotto) attacks jump to xref:combat:attack_types.adoc#_type_f_attacks[Flotto Attacks].
The rate of fire is determined by trigger squeeze.

The medium powered full auto rifle damage is 3-30 and its wate is 3.6kg.
This weapon is also known as a smig, F.A.R., sub machine gun, Ripley etc.

A malfunction with this weapon indicates a mechanism jam.


=== Fusion Pistol 

[horizontal]
Attack Type:: Shoot
Range:: 60h (-85)
Accuracy:: -40
Damage:: Special
Magazine:: 5 or 3 per Battery
Wate:: 2.3kg + fuel + Battery
EXPS:: 550
Value:: 200000 (2000) + Battery

:art: fusion_pistol.png
:width: 250px
:snark: Small and mighty.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Futuristic heavy looking pistol with tanks and dials.
include::ROOT:partial$articulate.adoc[]

The fusion pistol is a vicious weapon.
When fired, it launches a miniscule blob of fusion material.
The first persona damaged by the fusion pistol is the firer.
The heat blast is so intense that the firer takes 3-30 (3d10) hit points of damage.
Firing damage is inflicted every time the weapon is fired.
Self damage can be avoided by turning on fusion pistol shielding.
When the ammo is loaded, shielding can be activated decreasing output to 3 rounds.
A fusion pistol installed in powered armour does not damage the firer.

If firing the fusion pistol seems dangerous being the target is much worse.
The fusion pistol has both direct hit damage and area of effect damage.
A target hit by a fusion pistol has a good chance of simply exploding. 
The exploding target turns into molten fleshy shrapnel.

include::hardware:partial$fusion_pistol_damages.adoc[]

Target Size::
This weapon is the bane of small or tiny personas.
They are killed instantly if a hit is scored on them.
Tiny and Small targets explode and turn into collateral damage.
Medium, Large and Gigantic targets do not explode when hit. 
However they do both take Swath and Hit damage when hit. 

Swath Damage::
Swath damage is an inescapable area of effect damage along the route of the fusion blob.
Any target within 1 hex of the straight-line trajectory takes swath damage.
The heat blast delivers 6 to 60 (6d10) hit points in damage.
Medium, Large and Gigantic sized personas take swath damage as well as hit damage.
The swath damage is delivered first (6-60) and the hit damage (8-80) is added on.
A medium sized target would take 14 to 140 (14d10) hit points of damage.

Hit Damage::
A successful attack roll indicates a direct hit with the fusion pistol.
A target hit by a fusion pistol takes swath damage as well as hit damage.
Tiny and Small targets explode and become collateral damage.
The swath damage is delivered first (6-60) and the hit damage (8-80) is added on.
A medium sized target would take 14 to 140 (14d10) hit points of damage.

Collateral Damage::
If a target is exploded by a fusion pistol hit their body parts are weaponized.
The boiling flesh and bits of bone hurtle outward from hex of the exploded.
This steaming goo of collateral colleague has a 1 hex radius. 
A Tiny exploding person inflicts 3-30 (3d10) hit points in a 1 hex radius. 

NOTE: *Close only counts in horseshoes and fusion weapons.*

The fuel for a fusion pistol has negligible wate. 
This weapon has not been designed for close quarters combat.
This weapon has been nicknamed GVMB, expedition exterminator, or the BFG.

A malfunction of this weapon indicates a dangerous explosion.
An exploding malfunction delivers 6-60 (6d10) hit point to all within 3 hexes.


=== Fusion Rifle 

[horizontal]
Attack Type:: Shoot
Range:: 90h (-60)
Accuracy:: -25
Damage:: Special
Magazine:: 5 or 3 per Battery
Wate:: 8kg + fuel + Battery
EXPS:: 900
Value:: 800000 (2000) + Battery

:art: fusion_rifle.png
:width: 450px
:snark: Not for close combat.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Oversized futuristic rifle with lights and tanks.
include::ROOT:partial$articulate.adoc[]

The fusion rifle is a vicious weapon.
When fired, it launches a miniscule blob of fusion material.
The first persona damaged by the fusion rifle is the firer.
The heat blast is so intense that the firer takes 6-60 (6d10) hit points of damage.
The next personas damage are the ones standing within 1 hex of the firer.
The head backlash is an area of effect weapon on firing.

Firing damage is inflicted every time the weapon is fired.
Self damage can be avoided by turning on fusion rifle shielding.
When the ammo is loaded, shielding can be activated decreasing output to 3 rounds.
A fusion rifle installed in powered armour does not damage the firer.

If firing the fusion rifle seems dangerous being the target is much worse.
The fusion rifle has both direct hit damage and area of effect damage.
A target hit by a fusion rifle has a good chance of simply exploding. 
The exploding target turns into molten fleshy shrapnel.

include::hardware:partial$fusion_rifle_damages.adoc[]

Target Size::
This weapon annihilates any persona medium sized or smaller.
Medium and smaller personas are killed instantly if a hit is scored on them.
All anthros are Medium-sized. 
Tiny, Small, and Medium targets explode and turn into collateral damage.
Large and Gigantic targets do not explode when hit. 
However they do both take Swath and Hit damage when hit. 

Swath Damage::
Swath damage is an inescapable area of effect damage along the route of the fusion blob.
Any target within 2 hexes of the straight-line trajectory takes swath damage.
The heat blast delivers 8 to 80 (8d10) hit points in damage.
Large and Gigantic sized personas take swath damage as well as hit damage.
The swath damage is delivered first (8-80) and the hit damage (10-180) is added on.
A Large-sized target would take 18 to 180 (18d10) hit points of damage.

Hit Damage::
A successful attack roll indicates a direct hit with the fusion rifle.
A target hit by a fusion rifle takes swath damage as well as hit damage.
Tiny, Small and Medium targets explode and become collateral damage.
The swath damage is delivered first (8-80) and the hit damage (10-180) is added on.
A Large-sized target would take 18 to 180 (18d10) hit points of damage.

Collateral Damage::
If a target is exploded by a fusion rifle hit their body parts are weaponized.
The boiling flesh and bits of bone hurtle outward from hex of the exploded.
This steaming goo of collateral colleague has a 3 hex radius. 
A Medium exploding persona inflicts 7-70 (7d10) hit points in a 3 hex radius. 

NOTE: *Close only counts in horseshoes and fusion weapons.*

The fuel for a fusion rifle has negligible wate. 
This weapon has not been designed for close quarters combat.
This weapon has been nicknamed GVMB, expedition exterminator, or the BFG.

A malfunction of this weapon indicates a dangerous explosion.
An exploding malfunction delivers 8-80 (8d10) hit point to all within 5 hexes.

=== Gauss Pistol 

[horizontal]
Attack Type:: D
Range:: 100h (-55)
Accuracy:: +100
Damage:: 5-50, 4-40, *3-30*, 2-24, 2-16
Magazine:: 10 
Wate:: 1.8 kg, *1.5 kg*, 1.0 kg (1.8%)
EXPS:: 500
Value:: 3000 (3)

The gauss pistol magnetically hurls specialized ammunition.
Each round is a combination of battery and projectile.
The battery expends it's energy to propel itself at lethal velocity.
There are no casings ejected.
A gauss pistol has no measurable kickback.
Low kickback helps with the pistol's accuracy and utility in zero gravity.
The weapon is quiet but not entirely silent.

The medium powered gauss pistol damage is 3-30 (3d10) and its wate is 1.5kg.

A malfunction indicates an ammo defect and must be manually removed.

=== Gauss Rifle 

[horizontal]
Attack Type:: E
Range:: 190h (-40)
Accuracy:: +170
Damage:: 5-60, 5-50, *4-48*, 3-30, 2-20
Magazine:: 30
Wate:: 3.75 kg, *3.5 kg*, 3.25 kg (1.8%)
EXPS:: 754
Value:: 12000 (5)

The gauss rifle magnetically hurls specialized ammunition.
Each round is a combination of battery and projectile.
The battery expends it's energy to propel itself at lethal velocity.
There are no casings ejected.
A gauss rifle has no measurable kickback.
Low kickback helps with the rifle's accuracy and utility in zero gravity.
The weapon is quiet but not entirely silent.

The medium powered gauss rifle damage is 4-48 (4d12) and its wate is 3.5kg.

A malfunction indicates an ammo defect and must be manually removed.



=== Glass Gun 

[horizontal]
Attack Type:: D
Range:: 100h (-99)
Accuracy:: Special
Damage:: 4-48 (4d12)
Magazine:: 10
Wate:: 3.75kg (200gm)
EXPS:: 300
Value:: 5000 (75)

:art: pistol_bellows.png
:width: 350px
:snark: Pain in the glass.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Pistol with bellows for stock and fans on body.
include::ROOT:partial$articulate.adoc[]

The glass gun ejects clouds of penetrating ceramic shards.
The attack is designed to penetrate fur, hide and low tech armour.
This weapon enjoys a +200 accuracy bonus on attack rolls against multi-pieced armour.
Some examples of multi-pieced armour are furs, leather, padded, studded, ring, scale and chain.
The bonus to hit does not apply for skins like: robots, powered armour, full plate armour, and vac suits.
Each magazine is a solid chunk of crystalline material that acts as both battery and projectile.

A malfunction of this weapon indicates a magazine malfunction and all remaining rounds are lost.

=== Grapple Gun 

[horizontal]
Attack Type:: Shoot
Range:: 15h (-1000)
Accuracy:: -100
Damage:: Special
Magazine:: 1
Wate:: 3kg
EXPS:: 330
Value:: 1006

:art: grapple_ouchy_version.png
:width: 250px
:snark: Grapple gun with barbed grapple.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Pistol with serrated barbs instead of barrel.
include::ROOT:partial$articulate.adoc[]

The grapple gun fires a sticking device attached to a strong cord.
The grapple is the mainstay of most every action movie in existence. 
This weapon offers great opportunities for story progression.

There are two type of grapple guns. 
Destructive and non-destructive.
The player can pick either. 
Otherwise there is a 42% chance the grappled will be destructive.

Both grapples are mechanized and can lift 130kg straight up at 3 h/u.
An unattached grapple can be power rewound in 1 unit of combat time.
An attached grapple can only be removed if there is *no* cord tension.

Grapple guns have a off label use of being used to hit and pull in unwilling targets.
There is no ruleset for land fishing.
A recommended approach would be to first compare wates.
If wates are comparable (medium-sized vs medium-sized) then move to Strength challenges. 
To compare personas competing by attribute jump to xref:uncombat:attribute_rolls.adoc#_attribute_competition[Attribute Competition].

A malfunction with this weapon indicates a mechanism jam.

.*Destructive Grapple*
This is the classic metal barbed grapple. 
The business end appears like a bouquet of alloy barbs.
The destructive grapple must score a hit.
When it smashes into the target 4-24 (4d6) hit points of damage is inflicted.
This could harm a targeted persona or damage a rooftop. 
There is a 5% chance of adherence per point of damage inflicted.
Forcefully removing this grapple will inflict a 1-4  (1d4) hit points of damage.

.*Non-destructive Grapple*
This is the non-destructive sticky grapple.
The business end appears like a cluster of synthetic grapes.
The sticky end does no damage, but it will attach to anything that it hits.
The sticky grapple can only be removed by pushing a button on the gun.



=== Gravruptor Gun 

[horizontal]
Attack Type:: Shoot
Range:: 30h (-80)
Accuracy:: 0
Damage:: Special
Magazine:: 10 per Battery
Wate:: 4.25kg + Battery
EXPS:: 1000
Value:: 10000 + Battery

:art: gravruptor_gun.png
:width: 350px
:snark: A device of great gravity.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Stubby rifle with satellite dish instead of a barrel.
include::ROOT:partial$articulate.adoc[]

The gravruptor gun inflicts gravitational anomalies to disrupt and damage.
A hit by the gravruptor subjects the target to a blast of random gravity.
A miss has no effect on the target or surrounding objects.
The gravruptor is ineffective against targets with a wate greater than 500kg.

Most often the gravruptor gun will add 1-4 (1d4) gravities to the local terrain.
The target may crash to the ground, and weapons are torn from grasps.
This pressing problem will also inflict damage to all targets in the area of effect.
This damage is 1 to 12 (1d12) hit points in damage per extra gravity.
E.g., 3 gravities would smash targets into the ground for 3-36 hit points of damage.

Being crushed into the ground, flung into a ceiling or wall, or shot into space, the damage is the same.
It is possible that further damage may follow if the persona flies off a cliff, or lands in a toxic waste pit.

include::hardware:partial$gravruptor_effects.adoc[]

All of the above effects are described for a normal gravity world.
What effects this gun has on high gravity and low gravity planets depends entirely on the ref.

The gravruptor gun is designed for zero gravity combat.
It has no recoil to cause the firer any spin problems, and sends those targets that it hits flying off into space.
A successful attack roll will still inflict damage for accelerating the target, and the target will then fly away at 1 h/u per 2 hit points of damage.
Thus a hit that inflicts 20 hit points of damage would send the target racing off into space at an uncontrolled movement rate of 10 h/u.

The gravruptor gun is also known as an accelerator rifle, or a gravgun.

A malfunction with this weapon will result in a gravitational anomaly attacking the weapon and weapon holder.

=== Job Pistol 

[horizontal]
Attack Type:: Shoot
Range:: 25h (-100)
Accuracy:: -30
Damage:: 1-20 (1d20)
Magazine:: 10 per Battery
Wate:: 1kg + Battery
EXPS:: 400
Value:: 4500 + Battery

The job pistol employs a combination gauss, spring and vacuum chamber mechanism.
This allows the pistol to turn any solid material into a lethal projectile.
JOB is an acronym for Jack Of all Bullets.
To load the weapon dump about 1 kg of loose material into the chamber.
Sand, rocks, plastic, batteries, or bullets will hurtle out with lethal velocity.
Each kilogram of junk is good for 5 shots.

This weapon is not a grenade launcher.
Most grenades are too heavy to fit in the pistol's junk chamber.
Grenade launchers arm and fire a grenade.
Pre-arming and firing a grenade from a job pistol can result in accidental detonation.

A job pistol has no specific ammunition. 
This weapon is also called a junk gun or garbage pistol.

A malfunction with this weapon indicates a weapon jam. 

=== Job Rifle 

[horizontal]
Attack Type:: Shoot
Range:: 100h (-75)
Accuracy:: +25
Damage:: 3-30 (3d10)
Magazine:: 15 per Battery
Wate:: 4kg + Battery
EXPS:: 500
Value:: 17500 + Battery

The job rifle employs a combination gauss, spring and vacuum chamber mechanism.
This allows the rifle to turn any solid material into a lethal projectile.
JOB is an acronym for Jack Of all Bullets.
To load the weapon dump about at least 2kg of loose material into the chamber.
Sand, rocks, plastic, batteries, or bullets will hurtle out with lethal velocity.
Each 2 kilogram load of detritus is good for 5 shots.

This weapon is not a grenade launcher.
Most grenades are too heavy to fit in the rifle's junk chamber.
Grenade launchers arm and fire a grenade.
Pre-arming and firing a grenade from a job rifle can result in accidental detonation.

A job rifle has no specific ammunition. 
This weapon is also called a junk gun or garbage rifle.

A malfunction with this weapon indicates a weapon jam. 

=== Lazer Pistol 

[horizontal]
Attack Type:: Shoot
Range:: 80h (-50)
Accuracy:: +60
Damage:: 4-40, 3-30, *2-20*, 2-16, 1-10
Magazine:: 15 per Battery
Wate:: 1.3 kg, *1.15 kg*, 1.0 kg + Battery
EXPS:: 400
Value:: 1500 + Battery

:art: pistol_lazer.png
:width: 250px
:snark: Pew.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Pistol with no barrel. 
include::ROOT:partial$articulate.adoc[]

This is your everyday, run of the mill, coherent light energy weapon.
The lazer pistol is the staple of sciency fiction everywhere.
The gun makes the classic pinging, zapping or crackling noise.
Ionized gasses ejected from the emission chamber create a mild kickback.
The lazer beam itself is continuous and invisible. 
Often the lazer beam is given a colour to assist in targeting.
Jump to xref:software:CH55_Appearances.adoc#_colour_your_whirled[Colour] if you want a fancy beam colour.

The medium powered lazer pistol damage is 2-20 (2d10) and its wate is 1.15kg.
The lazer pistol is also called a phaser or blaster.

A malfunction indicates the loss of a charge.

=== Lazer Rifle 

[horizontal]
Attack Type:: Shoot
Range:: 150h (-40)
Accuracy:: +100
Damage:: 5-50, 4-40, *3-30*, 2-20, 2-16
Magazine:: 45 per Battery
Wate::  3.7 kg, *3.6 kg*, 3.5 kg + Battery 
EXPS:: 500
Value:: 6000 + Battery

:art: rifle_lazer.png
:width: 450px
:snark: Rifle (pew) and battery pack
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Futuristic rifle with battery pack and cables.
include::ROOT:partial$articulate.adoc[]

This is your everyday, run of the mill, coherent light energy weapon.
The lazer rifle is the staple of sciency fiction everywhere.
The gun makes the classic pinging, zapping or crackling noise.
Ionized gasses ejected from the emission chamber create a mild kickback.

The medium powered lazer rifle damage is 3-30 (3d10) and its wate is 3.6kg.
The lazer rifle is also called a phaser or blaster.

A malfunction indicates the loss of a charge.



=== Napalm Gun 

[horizontal]
Attack Type:: Shoot
Range:: 15h (-250)
Accuracy:: -100
Damage:: 10-100 (10d10)
Magazine:: 5 
Wate:: 4.5kg (300gm)
EXPS:: 900
Value:: 12000

:art: napalm_gun.png
:width: 450px
:snark: Not for lighting barbecues.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Unique rifle with rounded smooth casing and tank attachment.
include::ROOT:partial$articulate.adoc[]

The napalm gun sprays a jet of flaming adhesive death.
The jet from the gun is covers a 19 by 1 hex swath area of effect.
The area of effect is a straight line, and cannot be swept over an arc.
Everything caught inside the one hex wide path will take 10-100 HPS of damage.

All objects capable of burning have a chance of bursting into flames.
The percentage chance of immolating is equal to the damage rolled.
If a target were to take 64 hit points in damage, it would have a 64% chance of bursting into flames.
Targets that are set alight will burn for 1 to 10 units.
Each unit of burning will inflict an additional 2 to 20 (2d10) hit points of damage.

This weapon is also labelled the torch, Bick, flame thrower, or a cig weaver.

Usually, a malfunction indicates a mechanism jam, but occasionally it may cause the flame thrower to explode.

=== Needler 

[horizontal]
Attack Type:: E
Range:: 30h (-85)
Accuracy:: -25
Damage:: 1-6 (1d6)
Magazine:: 12
Wate:: 0.7kg (100gm)
EXPS:: 300
Value:: 300 (1000)

A needler is a silent pistol that launches bunches of specialized needles.
A hit inflicts 1-6 (1d6) hit points of damage. 
The needles can be coated  in a variety of quick release poisons.
The poisons will only have an effect on organic targets.
The player must make a roll versus poison or be incapacitated.
Regardless of the poison type, the target will be incapacitated.
The intensity of the poison attack is 12 plus 2 per point of damage.
So a hit for 5 hit points of damage would have a poison intensity of 22.

All of the poison types, except pharma, disable the target completely.
Nausea is incapacitating and amnesia is total.

include::hardware:partial$needler_effects.adoc[]

.*Pharma*
Pharma is a special ammo type that injects a pharmaceutical into the target. 
In this case, the needler is a long range hypodermic needle.
To determine the med injected jump to xref:hardware:CH50_Pharmaceuticals.adoc#_pharmaceutical_type[Pharmaceuticals].
If the pharma is beneficial to the persona, they can choose to fail their saving roll.
This way long range healing pharma can still help the persona. 
The value of the pharmaceutical is multiplied ten fold in this format.
Powerful pharmaceuticals are limited to one dose only.
Note that a miss with this weapon has no effect and wastes the pharmaceutical.

Each cartridge is a self-contained unit, containing the needles, toxin and power.
A malfunction results in a mechanism jam wasting all remaining rounds.

=== Plasma Pistol 

[horizontal]
Attack Type:: D
Range:: 100h (-25)
Accuracy:: +50
Damage:: 4-32 (4d8)
Magazine:: 12 per Battery
Wate:: 1.6 + Battery
EXPS:: 500
Value:: 9000 + Battery

The plasma pistol deploys an organized plasma bolt to inflict damage.
The damage is inflicted by heat and shock wave. 
The bolt is discrete in nature and not a beam of energy.
Each plasma pistol may have an unique bolt colour. 
Jump to xref:software:CH55_Appearances.adoc#_colour_your_whirled[Colour].

A malfunction indicates a misfire and this weapon does not jam.

=== Plasma Rifle 

[horizontal]
Attack Type:: E
Range:: 160h (-50)
Accuracy:: 0
Damage:: 4-48 (4d12)
Magazine:: 30 per Battery
Wate:: 4kg + Battery
EXPS:: 700
Value:: 36000 + Battery

The plasma rifle deploys an organized plasma bolt to inflict damage.
The damage is inflicted by heat and shock wave. 
The bolt is discrete in nature and not a beam of energy.
Each plasma rifle may have an unique bolt colour. 
Jump to xref:software:CH55_Appearances.adoc#_colour_your_whirled[Colour].

A malfunction indicates a misfire and this weapon does not jam.


=== Plastix Pistol 

[horizontal]
Attack Type:: D
Range:: 35h (-85)
Accuracy:: 0
Damage:: 4-40, 4-30, *3-30*, 3-24, 2-20
Magazine:: 15
Wate:: 1.2 kg, *1.1kg*, 0.9 kg (10% Cylinder)
EXPS:: 500
Value:: 2000 (75)

:art: pistol_plastix.png
:width: 250px
:snark: Molten plastix ejector.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Futuristic pistol with enormous barrel bore.
include::ROOT:partial$articulate.adoc[]

A plastix pistol spits globs of molten plastix.
This weapon was specifically designed for penetrating plastix armour.
When attacking a target that is wearing plastix armour, the opponent is considered unarmoured (AR 500).
The ammunition for this weapon is a solid cylindrical cartridge that contains both the plastix compound, and the energy to charge the gun.

The medium powered plastix pistol damage is 3-30 (3d10) and its wate is 1.1kg.

A malfunction with a plastix pistol indicates a mechanism jam from molten plastic.



=== Plastix Rifle 

[horizontal]
Attack Type:: E
Range:: 120h (-50)
Accuracy:: +60
Damage:: 6-60, 6-40, *4-32*, 3-30, 2-24
Magazine:: 30
Wate::  4.2 kg, *4.0 kg*, 3.8 kg (10% Cylinder)
EXPS:: 600
Value:: 8500 (100)

:art: rifle_plastix.png
:width: 450px
:snark: Molten plastix ejector.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Futuristic rifle with enormous barrel bore.
include::ROOT:partial$articulate.adoc[]

A plastix rifle spits globs of molten plastix.
This weapon was specifically designed for penetrating plastix armour.
When attacking a target that is wearing plastix armour, the opponent is considered unarmoured (AR 400).
The ammunition for this weapon is a solid cylindrical cartridge that contains both the plastix compound, and the energy to charge the gun.

The medium powered plastix rifle damage is 4-32 (4d8) and its wate is 4kg.

A malfunction with a plastix rifle indicates a mechanism jam from molten plastic.



=== Protein Disrupter 

[horizontal]
Attack Type:: Shoot
Range:: 125h (-60)
Accuracy:: +150
Damage:: 5-60, 5-50, *4-40*, 3-30, 3-24
Magazine:: 9 per Battery
Wate:: 4.3 kg, *4.2 kg*, 4.1 kg + Battery
EXPS:: 700
Value:: 11000 + Battery

:art: protein_distuptor.png
:width: 350px
:snark: Auto digest on command.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Short stubby ugly rifle with prongs instead of a barrel.
include::ROOT:partial$articulate.adoc[]

The protein disrupter tears apart essential protein structures in organic tissue.
The beam from the gun unravels collagen, melts bone, and liquefies flesh.
This weapon is designed to be an anti-organic weapon.
Inorganic personas are unaffected as the disrupting ray passes through them unimpeded.
The beam harmlessly passes through robots, walls, Argillan rock women, and armour.
Machines and personas with organic components can be affected by this attack.
Target's bearing inorganic armour are considered unarmoured (AR 500) to this beam.
A attack roll is still required to damage a target. 

Wounds from this weapon are a gory mush.
Typical veterinarian quick fixes are ineffective.
A vet must have access to biorepair equipment to repair these wounds. 

The medium powered protein disrupter damage is 4-40 (4d10) and its wate is 4.2kg.

A malfunction of this weapon attacks the weapon bearer.
Typically injury will be the firer's hands. 


=== Radiation Gun 

[horizontal]
Attack Type:: D
Range:: 150h (-70)
Accuracy:: 0
Damage:: Special
Magazine:: 12 per Battery
Wate:: 3.76kg + Battery
EXPS:: 900
Value:: 8500 + Battery

:art: radiation_gun_pistol.png
:width: 450px
:snark: Free radiographs.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Boxy stout rifle with radiation markings.
include::ROOT:partial$articulate.adoc[]

This gun fires beams of lethal radiation.
The intensity of the radiation is 3 to 24 (3d8).
The intensity of the radiation is random and is determined each attack.
Radiation damage is 1-4 (1d4) hit points of damage per intensity of radiation.
An intensity 12 radiation attack would inflict 12-48 (12d4) hit points of damage.
The radiation beam affects inorganic and organic personas equally.
For more info about radiation attacks jump to xref:uncombat:saving_rolls.adoc#_radiation[Radiation Attacks].

This is also known as an x-ray gun, or a rad rifle.
A malfunction with this gun will bathe a 3 hex radius with intensity 3 to 24 radiation for one to six units.


=== Revolver 

[horizontal]
Attack Type:: Shoot
Range:: 80h (-66)
Accuracy:: 0
Damage:: 3-30, 2-20, *2-16*, 2-12, 1-10
Magazine:: 5
Wate:: 1.25 kg, *1.1kg*, 0.75 kg (1.5%)
EXPS:: 250
Value:: 200 (1)

:art: revolver.png
:width: 250px
:snark: Revolutionary in it's day.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Pistol with revolving ammo barrel.
include::ROOT:partial$articulate.adoc[]

A revolver launches a projectile powered by a controlled explosion within the ammo.
The trigger mechanism rotates a barrel loaded with ammunition. 
Hence the title revolver.

The medium powered revolver damage is 2-16 (2d8) and its wate is 1.1kg.

A malfunction of this weapon is a misfire, but does not jam the weapon.

=== Semi Auto Lazer Pistol 

[horizontal]
Attack Type:: Shoot, Shoot-2
Range:: 70h (-60)
Accuracy:: +50
Damage:: 4-40, 3-30, *2-20*, 2-16, 1-10
Magazine:: 15 per Battery
Wate:: 1.8 kg, *1.6 kg*, 1.4 kg + Battery
EXPS:: 500
Value:: 2000 + Battery

:art: pistol_lazer_sotto.png
:width: 250px
:snark: Pew pew.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: A pistol with no barrel.
include::ROOT:partial$articulate.adoc[]

This is your everyday, run of the mill, coherent light energy weapon.
The semi-auto lazer pistol allows for 2 attacks per unit.
The lazer pistol is the staple of sciency fiction everywhere.
The gun makes the classic pinging, zapping or crackling noise.
Ionized gasses ejected from the emission chamber create a mild kickback.
The lazer beam itself is continuous and invisible. 
Often the lazer beam is given a colour to assist in targeting.
Jump to xref:software:CH55_Appearances.adoc#_colour_your_whirled[Colour] if you want a fancy beam colour.

The medium powered semi-auto lazer pistol damage is 2-20 (2d10) and its wate is 1.6kg.
This weapon is also called a phaser, blaster or sotto lazer pistol.

A malfunction indicates the loss of a charge.

=== Semi Auto Lazer Rifle 

[horizontal]
Attack Type:: Shoot, Shoot-2, Shoot-3
Range:: 125h (-50)
Accuracy:: +90
Damage:: 5-50, 4-40, *3-30*, 2-20, 2-16
Magazine:: 24 per Battery
Wate:: 3.9 kg, *3.8 kg*, 3.7 kg + Battery
EXPS:: 600
Value:: 80000 + Battery

:art: rifle_lazer.png
:width: 450px
:snark: Rifle (pew pew pew) and battery pack
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Futuristic rifle with battery pack and cables.
include::ROOT:partial$articulate.adoc[]

This is your everyday, run of the mill, coherent light energy weapon.
The semi-auto lazer rifle allows for 3 attacks per unit.
The lazer rifle is the staple of sciency fiction everywhere.
The gun makes the classic pinging, zapping or crackling noise.
Ionized gasses ejected from the emission chamber create a mild kickback.
The lazer beam itself is continuous and invisible. 
Often the lazer beam is given a colour to assist in targeting.
Jump to xref:software:CH55_Appearances.adoc#_colour_your_whirled[Colour] if you want a fancy beam colour.

The medium powered semi-auto lazer rifle damage is 3-30 (3d10) and its wate is 3.8kg.
This weapon is also called a phaser, blaster or sotto lazer rifle.

A malfunction indicates the loss of a charge.

=== Semi Auto Pistol 

[horizontal]
Attack Type:: Shoot, Shoot-2
Range:: 70h (-60)
Accuracy:: +40
Damage:: 3-30, 2-20, *2-16*, 2-12, 1-10
Magazine:: 10
Wate:: 1.5 kg, *1.25 kg*, 1.4 kg (1.5%)
EXPS:: 300
Value:: 750 (1)

:art: pistol_sotto.png
:width: 250px
:snark: Semi otto pistol with mods.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Pistol with magazine, scope, stock and extended barrel.
include::ROOT:partial$articulate.adoc[]

This pistol launches a projectile powered by a controlled explosion within the ammo.
The next round may be chambered by the explosive force or a spring mechanism.
A semi-auto pistol can attack twice each unit.

This weapon is also called a sotto pistol.
The medium powered semi-auto pistol damage is 2-16 (2d8) and its wate is 1.25kg.

When a sotto pistol malfunctions, it has a mechanism jam.

=== Semi Auto Rifle 

[horizontal]
Attack Type:: Shoot, Shoot-2, Shoot-3
Range:: 110h (-44)
Accuracy:: +60
Damage:: 4-48, 3-36, *3-30*, 3-24, 2-20
Magazine:: 45
Wate:: 3.8 kg, *3.4 kg*, 3.0 kg (1.5%)
EXPS:: 600
Value:: 2800(1)

:art: rifle_flotto.png
:width: 450px
:snark: Semi automated freedom.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Classic military rifle small magazine clip.
include::ROOT:partial$articulate.adoc[]

This rifle launches a projectile powered by a controlled explosion within the ammo.
The next round may be chambered by the explosive force or a spring mechanism.
A semi-auto rifle can attack twice each unit.

This weapon is also called a sotto rifle.
The medium powered semi-auto rifle damage is 3-30 (3d10) and its wate is 3.4kg.

When a sotto rifle malfunctions, it has a mechanism jam.

=== Slug Thrower 

[horizontal]
Attack Type:: Shoot, Shoot-2
Range:: 40h (-50)
Accuracy:: 0
Damage:: 3-18 (3d6)
Magazine:: 20
Wate:: 250 (90gms)
EXPS:: 300
Value:: 250(50)

:art: slug_thrower.png
:width: 250px
:snark: Slugger.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Pistol with transparent magazine and spheroid ammo.
include::ROOT:partial$articulate.adoc[]

The slug thrower is a quiet, but not silent, spring powered weapon.
The magazine is a self-contained cartridge with the ammo and mechanical power. 
Many players are disappointed to find out this weapon does not pitch living slugs.

A malfunction indicates a mechanism jam.


=== Sonic Pistol 

[horizontal]
Attack Type:: Shoot
Range:: 40h (-211)
Accuracy:: -50
Damage:: Special
Magazine:: 12 per Battery
Wate:: 1.3kg + Battery
EXPS:: 630
Value:: 2000 + Battery

:art: pistol_sonic.png
:width: 250px
:snark: It's bark is worse than it's bite.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Stubby futuristic pistol with bloated barrel.
include::ROOT:partial$articulate.adoc[]

A sonic pistol uses sound waves to damage it's target. 
The pistol has a variable mechanism that is unnecessarily complicated.
Some legacy rules just won't go away.

There are a variety of attacks that the firer can choose from.
The more powerful the attack, the greater life drain on her batteries.
The sonic pistol is not an area of effect weapon.
An attack roll must be successful to damage the target.

include::hardware:partial$sonic_pistol_volumes.adoc[]

Damaging attacks vibrate the target with sound to inflict their damage.
Damage attacks have no other effects like deafness or pain infliction.

A deafening attack will disable organic and inorganic audio sensors.
The audio sensor gets a roll versus poison of intensity 4 to 32.
Organic sensors will recover in 1 to 10 hours.
Inorganic sensors must must await repair.

The sonic pistol is also called a screamer, whistle gun, or sonic disruptor.

A malfunction will result in a low power sonic attack on the user (1d8 HPS).


=== Sonic Rifle 

[horizontal]
Attack Type:: D
Range:: 80h (-211)
Accuracy:: -50
Damage:: Special
Magazine:: 24
Wate:: 3.8kg + Battery
EXPS:: 675
Value:: 8000 + Battery

:art: sonic_rifle.png
:width: 450px
:snark: The sonic rifle's bark is it's bite.
:artist: JEShields
:date: 2014
:license: Copyright JEShields Stock Art. jeshields.com
:description: Bulky futuristic rifle with blunt knobby muzzle end.
include::ROOT:partial$articulate.adoc[]

A sonic rifle uses sound waves to damage it's target. 
The rifle has a variable mechanism that is unnecessarily complicated.
Some legacy rules just won't go away.

There are a variety of attacks that the firer can choose from.
The more powerful the attack, the greater life drain on her batteries.
The sonic rifle is not an area of effect weapon.
An attack roll must be successful to damage the target.

include::hardware:partial$sonic_rifle_volumes.adoc[]

Damaging attacks vibrate the target with sound to inflict their damage.
Damage attacks have no other effects like deafness or pain infliction.

A deafening attack will disable organic and inorganic audio sensors.
The audio sensor gets a roll versus poison of intensity 4-40 (4d10).
Organic sensors will recover in 1-10 (1d10) hours.
Inorganic sensors must must await repair.

The sonic rifle is also called a screamer, whistle gun, or sonic disruptor.

A malfunction will result in a low power sonic attack on the user (2d10 HPS).

=== Stun Pistol 

[horizontal]
Attack Type:: D
Range:: 80h (-80)
Accuracy:: +80
Damage:: Special
Magazine:: 10
Wate:: 1.4kg + Battery
EXPS:: 500
Value:: 1500 + Battery

The stun pistol overloads the central nervous system of organic.
A stunned target collapses safely to the ground in a semi-conscious state.
The stun pistol is the weapon of choice for pacifists.
To avoid being stunned to player must roll versus 2-16 (2d8) intensity poison.
The target takes no damage but will remain stunned for 3-30 (3d10) units.
 
Inorganic personas are not stunned, but can be damaged by this weapon.
Robot personas take 1 hit point of damage per intensity.

Other names for a stun pistol is stunner, pacifier or slumper.
A malfunction with this weapon results in the loss of a charge.

=== Stun Rifle 

[horizontal]
Attack Type:: D
Range:: 130h (-35)
Accuracy:: +170
Damage:: Special
Magazine:: 20 per Battery
Wate:: 3.95kg + Battery
EXPS:: 700
Value:: 6000 + Battery

The stun pistol overloads the central nervous system of organics.
A stunned target collapses safely to the ground in a semi-conscious state.
The stun pistol is the weapon of choice for pacifists.
To avoid being stunned to player must roll versus 3-24 (3d8) intensity poison.
The target takes no damage but will remain stunned for 1-3 (1d3) minutes.
 
Inorganic personas are not stunned, but can be damaged by this weapon.
Robot personas take 1 hit point of damage per intensity.

Other names for a stun pistol is stunner, pacifier or slumper.
A malfunction with this weapon results in the loss of a charge.


=== Variable Lazer Pistol 

[horizontal]
Attack Type:: Shoot
Range:: 80h (-80)
Accuracy:: 0
Damage:: Special
Magazine:: 12 per Battery
Wate:: 1.5kg + Battery
EXPS:: 700
Value:: 9000 + Battery

:art: pistol_variable.png
:width: 250px
:snark: Set the lazer for something.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Futuristic pistol.
include::ROOT:partial$articulate.adoc[]

This gun is a coherent light energy weapon with a damper dial.
The firer can choose from a variety of settings.
There are three lethal settings and three non-lethal settings.
The persona dials in one of the six at the beginning of the combat unit.

include::hardware:partial$variable_lazer_pistol_settings.adoc[]

.*Damage Attacks*
The lethal attacks make the classic pinging, zapping or crackling noises.
Ionized gasses ejected from the emission chamber create a mild kickback.
The lazer beam itself is continuous and invisible. 
Often the lazer beam is given a colour to assist in targeting.
Jump to xref:software:CH55_Appearances.adoc#_colour_your_whirled[Colour] if you want a fancy beam colour.

.*Stun and Blind*
Both stun and blind have to score a hit to stun or blind the target.
Each have require a roll versus intensity 1-10 (1d10) poison.
The duration of the either effect will be 1 unit per point of intensity.
Blind works against any light sensor whether or organic or not.
Stun delivers 1 hit point of damage per intensity to robots. 
Robots cannot be stunned.

.*Flashlight*
Flashlight can light up 1 hex of area up to 50 hexes away.
There is no beam cast by this lazer light. 
Targets are illuminated in the dark without giving up the light source.

This weapon is also called a nightstick, or VLP.

A malfunction will result in complete battery drain.


=== Variable Lazer Rifle 

[horizontal]
Attack Type:: D
Range:: 130h (-80)
Accuracy:: 0
Damage:: Special
Magazine:: 24 per Battery
Wate:: 4.1kg + Battery
EXPS:: 780
Value:: 36000 + Battery

This gun is a coherent light energy weapon with a damper dial.
The firer can choose from a variety of settings.
There are three lethal settings and three non-lethal settings.
The persona dials in one of the six at the beginning of the combat unit.

include::hardware:partial$variable_lazer_rifle_settings.adoc[]

.*Damage Attacks*
The lethal attacks make the classic pinging, zapping or crackling noises.
Ionized gasses ejected from the emission chamber create a mild kickback.
The lazer beam itself is continuous and invisible. 
Often the lazer beam is given a colour to assist in targeting.
Jump to xref:software:CH55_Appearances.adoc#_colour_your_whirled[Colour] if you want a fancy beam colour.

.*Stun and Blind*
Both stun and blind must score a hit to stun or blind the target.
Each have require a roll versus intensity 2-20 (2d10) poison.
The duration of the either effect will be 1 minute per point of intensity.
Blind works against any light sensor whether or organic or not.
Stun delivers 1 hit point of damage per intensity to robots. 
Robots cannot be stunned.

.*Flashlight*
Flashlight lights up a 3 hex area up to 100 hexes away.
There is no beam cast by this lazer light. 
Targets are illuminated in the dark without giving up the light source.

This weapon is also called a nightstick, perimeter light or a VLR.

A malfunction will result in a complete battery drain.



=== Water Gun 

[horizontal]
Attack Type:: Shoot
Range:: 50h (-190)
Accuracy:: 0
Damage:: 3-18 (3d6)
Magazine:: 30 per Battery
Wate:: 0.75 + Battery
EXPS:: 500
Value:: 750 + Battery

:art: water_pistol.png
:width: 350px
:snark: Not a toy.
:artist: Mike Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Pistol with reservoir on top of body.
include::ROOT:partial$articulate.adoc[]

A water gun condenses and lethally propels droplets of water.
This gun has no water storage, and draws humidity from the air.
This weapon does not work in a vacuum, and environs where humidity is absent.

This gun is totally waterproof. 
If used underwater, it's range is reduced to 25 hexes.
This weapon is also called a squirt gun.

A malfunction indicates a malformed water droplet and the loss of a charge.

:art: I_like_big_guns.png
:width: 400px
:snark: I like big guns and I cannot lie.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Punk rocker woman in skirt holding an enormous futuristic rifle.
include::ROOT:partial$articulate.adoc[]


// todo find me a home

:art: ammo_weapon.png
:width: 450px
:snark: Ammo affects the shape of the gun.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Rifle with oblong barrel opening and top fed revolving feed.
include::ROOT:partial$articulate.adoc[]