= Junque

:art: random_Junque_Bin.png
:width: 250px
:snark: One persona's garbage...
:artist: Peggy-Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: An overflowing garbage can.
include::ROOT:partial$articulate.adoc[]

The title of this chapter is self explanatory.
The tables contained in here are filled with lists of completely useless equipment.
It is almost certain that these artifacts have existed in every society in one form or another.
Random junque is useless equipment when compared to the artifacts created by TOYs.
However players regularly find use for Junque during their sessions. 

Random junque should not count as a roll for players generating start up Toys.

== Generate Type
Pick a piece of random Junque. 

include::hardware:partial$list_of_junque.adoc[]

== Junque Data

Wate::
If a Junque needs a wate the players decide whether it is large or small.
Small items are 100 grams and large items are 10kg. 

EXPS::
Players should earn decent EXPS if they manage to use Junque in their game session.
The EXPS earned usually ends in 42, and ranges from 42 to 1042 experience points.

Value::
Random junque has a random resale value of 1-10 (1d10) eps.
There is also a 10% chance that sacrificing a piece of Junque will generate a spare part.
A spare part can be used to fix a more objectively useful artifact.

[discrete]
=== Ref's Own Table
The ref's own table for Junque should consist of useless things from the milieu.
Regardless of the milieu there will always be waste, incompetence and corruption.

== Junque Catalogue

=== Appliances
Every civilization has its kitchenware of convenience.

include::hardware:partial$junque_appliances.adoc[]

=== Armour
Things you would never expect as armour.

include::hardware:partial$junque_armour.adoc[]

=== Books
Rare medium not well done.

:art: random_junque_helmet_books.png
:width: 250px
:snark: One generations junque...
:artist: Warren Oddson
:date: 1991
:license: CC BY-SA 4.0
:description: Space helmet, books and shaving brush on table.
include::ROOT:partial$articulate.adoc[]

include::hardware:partial$junque_books.adoc[]

=== Clothing
Well worn stuff to wear.

include::hardware:partial$junque_clothing.adoc[]

=== Fiddle Junque
Even more purposeless than the usual Junque.

:art: smog_globe.png
:width: 250px
:snark: Vacation memory ball.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Snow globe of a worn out city. 
include::ROOT:partial$articulate.adoc[]

include::hardware:partial$junque_fiddling.adoc[]


=== Foodstuff
Never enough to sate hunger, always enough to make one hungrier. 
Junque food for certain.
First roll container type and then the foodstuff in it.
A frozen gaseous cookie is possible.

:art: yummy_bar.png
:width: 300px
:snark: Yummy bar.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Rectangular treat with a corner bitten off.
include::ROOT:partial$articulate.adoc[]


==== Container

include::hardware:partial$junque_food_container.adoc[]

==== Content

include::hardware:partial$junque_food_contents.adoc[]

=== Furniture
Often only the most useless part of a piece of furniture.

:art: radio_or_not.png
:width: 250px
:snark: Old timey radio or trans-hyperspace monitor?
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Old radio with turn dial and wooden frame.
include::ROOT:partial$articulate.adoc[]

include::hardware:partial$junque_furniture.adoc[]

=== Livestock
A unique alien species is evolved for this junque item. 
The alien must always be small, weak, dumb, and slow.
Livestock is not a pet, not a friend, and is not trainable. 
Only the xref:referee_personas:alien_rp.adoc#_shape[shape], xref:aliens:biology.adoc#_sounds[sound] and xref:aliens:biology.adoc#_aroma[smell] elements are generated.

=== Materials
Incomplete building material components.

include::hardware:partial$junque_materials.adoc[]

=== Musical Instruments
Various out of tune noise makers.

include::hardware:partial$junque_musical_instruments.adoc[]

=== Personal
You are so king in it.

include::hardware:partial$junque_personal_items.adoc[]

=== Sports
Go ball sport team. 

include::hardware:partial$junque_ball_sports.adoc[]

=== Stationary
Non-moving stationery. 

include::hardware:partial$junque_stationery.adoc[]

=== Weapons
Unusual replacements for non-powered weapons. 

include::hardware:partial$junque_weapons.adoc[]

=== Miscellaneous
No missiles here at all. 

:art: random_junque_pig_toaster.png
:width: 250px
:snark: Pet pig, toaster and blender
:artist: Warren Oddson
:date: 1991
:license: CC BY-SA 4.0
:description: A blender a toaster and a piggy.
include::ROOT:partial$articulate.adoc[]

include::hardware:partial$junque_missile_anus.adoc[]










