= Multequip

:art: multi_driver_percussion.png
:width: 350px  
:snark: Screw driver and percussion tool. Low tech multi.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Worn out wooden mallet has screw driver built into handle.
include::ROOT:partial$articulate.adoc[]

The term multequip describes a solitary piece of equipment that is a seamless fusion of multiple equipment pieces.
Multi-equipment, multi-toy, or poly-fact (multiple artifacts) all arise from the term multiple equipment.
Combinations of a medi-kit and drug dispensers, or metal detector and earth canceller are examples of well-matched multequip.
Equipment combinations can also be contradictory or ridiculous.
Combinations of powered-armour and underwear, inflatable chair and gun,  or bomb and computer are poorly-matched multequip examples.
This brief section gives some guidance to referees that want to, or need to, combine TOYs for fun or danger.

Multi-equipment share a common power supply, and all the devices run off of a single battery set.
The persona can use every device in a multi-toy simultaneously.
This factor makes a multi-gun a menacing artifact indeed.

== Need
Multi-equipment may result from a referee's specific need for a device that does not exist in the TOY system.
For example, an established policing unit may have plastix helmets with built-in night vision goggles.
Multi-equipment can result from a pure random check for its existence.
High tech equipment is more likely to become multequip.
This higher chance is due to the miniaturization that impacts high tech toys.
There is a percent chance equal to the artifact's tech level that it will become a piece of multequip.

== Generation
This determination is entirely optional but works as follows.
If a deci-die roll is less than the toy's tech level, then another piece of equipment is added to the first one.
The player generates another random piece of equipment and adds it to the first one.
The player generates a new toy in the same manner as any other toy.
The player can randomly determine the additional TOY via the xref:hardware:a_introduction.adoc#_toy_type[Toy Type,window=_blank].
The referee can guide the generation of the new toy to ensure a suitable it is a suitable one.  

[discrete]
=== Multi-Equipment Chance
.Chance  = 1% per Tech Level 
****
Tech level 10 device has a 10% chance of adding a new device. Maximum three devices.
****

The additional artifact will have the same tech level as the original toy.
Adding new toys can continue until the player rolls higher than the tech level of the device.
Even a dice rolling purist referee will limit a multi-toy to 3 seamlessly combined artifacts.

== Parameters

=== Wate 
The wate of multequip is slightly less than the total wate of all its component toys.
The devices share batteries, wiring, reservoirs and the like, so the total wate is 10% less than expected.
If three devices combined have a 10 kg wate, the multequip version would have a 9 kg wate.

=== EXPS 
Each piece of equipment maintains its experience point (EXPS) value.
When a persona identifies a component of a multi-toy, she earns the experience for that specific toy.
As the multi-toy reveals more uses, the persona earns more experience points.

=== Value 
The value of a multi-toy is slightly higher than the total value of all the component toys.
The device's total value is 10% greater than the sum of its parts.
A multi-toy with a total device value of 1000 eps would be worth 1100 eps. 

=== Identification
Artifact identification is more difficult for multequip since the identifier must identify each component separately.
Multi-equipment is often underused as a persona may not identify each of the component toys.



