= Mundane Equipment

Mundane equipment represents the items that the persona needs to survive in the wilds.
Mundane equipment consists of low-tech non-artifact tools.
These items have a distinctly medieval nature to their construction.
These lists are a convenience, and the milieu of the referee rules mundane equipment.
The referee reserves the right to change wates and costs without notice.

== Cost vs Value
All the costs listed are in electrum pieces (eps).
However, market prices may increase the value of a piece of kit.
For example, a village in a small ruin may only have one set of plastix to sell.
The scarcity and importance of an item could impact its cost.
Relative to an artifact, equivalent mundane equipment is valueless.

=== Mundane Equipment 
Mundane items have a low-tech, underdeveloped, medieval nature. 
Mundane equipment construction consists of animal parts, poorly smelted metals, shoddy plastics and untreated woods.
Everything listed here is mundane equipment.
Most everything listed here can be acquired on mundane terra. 
Hence mundane. 

All the items on the equipment tables are of the mundane variety.
Each item has a wate in kilograms and a cost in eps.
Where possible, the list includes an alternative for the item.
For example, a wrench could replace a hammer.

=== Better Equipment
Better mundane equipment is composed of better materials than mundane equipment. 
Depending on the campaign's milieu, the composition of better equipment could include alloys, polymers, and other synthetics.
Better equipment functions no better, but it is lighter and more expensive.

* cost times 3
* wate times 1/2
* No change in function

For example, a suit of chain mail has a wate of 5.9 kgs, and a cost of 80 eps.
Better chain mail would cost 240 eps and have a wate of 3.0 kgs.
The Defence Rating bonus remains the same at +125.

Better mundane equipment is not to be confused with artifacts generated in the toy system.
Better mundane equipment is still mundane equipment and is valueless besides artifacts and toys.

=== Bespoke Equipment
Bespoke mundane equipment is composed of either mundane or better materials and has a specialized design. 
Bespoke equipment could include armour for an alien, a fancy-looking sword, or other specialization.
Bespoke equipment functions no Bespoke, but it is lighter and more expensive.

* Cost times 6
* Wate unchanged
* Function unchanged

For example, a suit of chain mail has a wate of 5.9 kgs, and a cost of 80 eps.
Bespoke chain mail would cost 480 eps and have a wate of 5.9 kgs and an Defence Rating bonus of +125.
A bespoke better suit of the chain mail would cost 1440 eps, have a wate of 3.0 and an AR bonus of +125.
Bespoke mundane equipment is not to be confused with artifacts generated in the toy system.
Bespoke mundane equipment is still mundane equipment and is valueless besides artifacts and toys.

== Survival Equipment
The essential equipment consists of items critical to expedition survival.

include::hardware:partial$mundane_essentials.adoc[]

=== Survival Pack
The survival pack is a time-saving list of essential equipment.
The goal of the survival pack is to speed up persona creation.
The survival pack costs 70 eps and has a wate of 13.5 kg.

include::hardware:partial$mundane_survival_pack.adoc[]

== Comfort Equipment
Non-essential equipment consists of items for expedition comfort.

include::hardware:partial$mundane_none_essential.adoc[]

== Vocation Equipment
Vocation equipment is what a persona needs to carry out her vocation maneuvers.
The vocation equipment list is mostly tongue in cheek.

include::hardware:partial$vocation_tool_kits.adoc[]

== Armour
Armour is anything that deflects or dissipates force from the persona's hide.
The wate of worn armour does not increase the persona's wate allowance.
If the persona is carrying the same armour, its wate increases her wate allowance.
For all the gore preventing details jump to xref:combat:defence_rating.adoc[Defence Rating,window=_blank].

=== Body Armour

include::hardware:partial$mundane_armour.adoc[]

=== Shielding

include::hardware:partial$mundane_shielding.adoc[]

== Weapons 
The weapons included here are non-powered thrusting, striking and projectile weapons. 
Powered weapons like guns are part of the artifact system.
The referee must determine the cost, wate and particulars of artifact weapon equipment in advance. 
Crossbows are the only Shoot weapon that a persona can purchase in this chapter.

Some weapons have alternates listed. 
Alternate weapon types only last one battle and does not offer the same bonuses as the actual item.
For example, using a coat rack as a small lance will work once. 
The player can only add her persona's Raw Bonus to the attack roll.
If she wins the attack roll the coat rack will inflict 4d4 hit points in damage but be destroyed in the process.

=== Strike Weapons

include::hardware:partial$mundane_weapons_strike.adoc[]

=== Fling Weapons

include::hardware:partial$mundane_weapons_fling.adoc[]

=== Shoot Weapons

include::hardware:partial$mundane_weapons_shoot.adoc[]

=== Area Weapons 

include::hardware:partial$mundane_weapons_area.adoc[]


=== Ammunition

include::hardware:partial$mundane_ammunition.adoc[]