= Spacecraft

[quote]
____
Ships sail from A to B across the C. Spaceships sail from A to B across __nothing__.
____

:art: have_space_will_travel.png
:width: 450px
:snark: Have space will travel
:artist: Ed Emshwiller, Hugh
:date: 1958, 2018
:license: CC BY-SA 4.0
:description: Two space suited humanoids floating around their space camper on a moon.
include::ROOT:partial$articulate.adoc[]

A spacecraft is any vehicle that can function outside planetary atmospheres and sail off into the wild black yonder.
Spacecraft have specially sealed hulls, super-powerful engines, and technomagical drives that hop enormous distances.
Spacecraft can be the entire focus of a story or a mere tool to advance a story.

A spacecraft may be a piece of garbage discarded by a 1000 planet armada, or the priceless effort of a culture trying to escape its gravity well.
Spacecraft can be found, stolen, rented, lent or inherited by the expedition.
Space travel may be the campaign goal or just to mechanism to expand campaign horizons.
Either way, access to a spaceship brings the level of fantasy to galactic proportions.

The spacecraft creation system is complex and does not lend itself to on-the-spot artifacts.

== Nomenclature
The type of spacecraft reflects its function.
The spacecraft types starship and airship indicate different functions.
A starship does it all. 
A starship can travel between stars, between planets and enter an atmosphere.
An airship can only maneuver within a planet's atmosphere and gravity well.
An airship could be a plane or a dirigible, but not a spacecraft.

Exatmo is a contraction of "exterior to the atmosphere." 
Exatmo is deadly to all life forms unless they are specifically protected.
Inatmo is a contraction of "in the atmosphere."
Inatmo is usually safe for lifeforms with ground, gravity and atmosphere. 
Special drives defy existing physics to transport the expedition across the vastness of space.

* drive - fancy word for engine
* exatmo - exterior to atmosphere
* inatmo - interior to atmosphere
* special - an engine that outside of space and time

include::appendices:partial$space_vehicle_nomenclature.adoc[]

== The Build 
Spacecraft are neither accurate in detail nor aerospace specifications.
A spacecraft is a tool for role-playing. 
The build creates random spacecraft that supply the basic necessities of space travel.
The only guarantees are a hull, drives, computers, and life support.
The layout and appearance depend on the referee and players.

== Hull
The first assumption about spacecraft is that they have hulls.
A hull is like the outer covering of a seed. 
A spacecraft hull encases the ship's contents, protecting them from exatmo.
The ship's hull is an intimate part of the ship's life support and gravity systems. 
The shape of the hull is determined entirely for dramatic effect.
Spacecraft shaped like pirate ships are acceptable if this fits the referee's milieu.

.*Hull Checklist*
. <<_size,Size>>
. <<_composition,Composition>>
. <<_strength,Strength>>

:art: danger_in_deep_space_ships.png
:width: 250px
:snark: Different sized spacecraft
:artist: Louis Glanzman
:date: 1953
:license: CC BY-SA 4.0
:description: Space vehicle docking at space station with planet in background.
include::ROOT:partial$articulate.adoc[]

=== Size 
Hull size determines the spacecraft size.
The bigger the hull size, the bigger the spacecraft.
Hull size represents the amount of volume displaced by the spacecraft.
Hull size does not correlate with reality in any way.
Metric tonnes of displacement sounds lends a sciency fiction maritime feel to hull size.

include::hardware:partial$spacecraft_hull_size.adoc[]

=== Composition 
Hull Composition is more of a descriptor.
Most spacecraft will be composed of metal, plastix, and ceramic alloys.
Smart hulls are self-maintaining and slowly repair themselves.
Smart hulls offer no combat benefit at all. 
They allow the expedition to avoid the expenses of hull refitting.

include::hardware:partial$spacecraft_hull_composition.adoc[]

=== Strength 
Hull strength determines the hull's ability to prevent damage to the ship's interior components.
It is a mix of composition strength, shape and redundancy.
The hull strength is also the hull Defence Rating (DEF). 
The hull cannot be damaged before depleting the hull's Defence Rating. 
This depletion can happen fast in spacecraft combat.

include::hardware:partial$spacecraft_hull_defence.adoc[]

== Drives
Like any vehicle, a spacecraft needs engines to travel from one point to another.
However, spacecraft are not so provincial as to call their power sources engines.
Spacecraft call their engines drives.
The term drive includes all the components needed to propel the spacecraft.

:art: spacevehicle_reentry.png
:width: 450px
:snark: Entering atmosphere at high speed
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: A stylish spaceship showering flames on reentry.
include::ROOT:partial$articulate.adoc[]

.*Drive Checklist*
. <<_configuration,Drive Configuration>>
. <<_power_level,Power Level>>

=== Configuration
The configuration of the drive types determines the spacecraft type.
The referee should always choose the kind of spacecraft that best suits the story.

include::hardware:partial$spacecraft_drive_configuration.adoc[]

Starship::
The starship does it all.
A starship can take off and land on a planet's surface, travel from planet to planet and jump from star to star. 

Starcruiser::
This spacecraft can't enter an atmosphere but can travel anywhere else in space.
The starcruiser also has the name star bus or simply a cruiser.

Spaceship::
The spaceship is limited to work within the confines of one star system.
This vehicle can cross into the atmosphere of any planet in the system.
The spaceship also has the name shuttle craft or space bus.

Spacecruiser::
The spacecruiser only operates in the vacuum of space within one star system.
This spacecraft cannot enter the atmosphere of a planet or jump to another star system.
The spacecruiser also has the name transfer craft or space tug.

Starjumper::
The starjumper only has a special drive and can only jump from one location to another.
The starjumper cannot enter the atmosphere and cannot travel between planets.
The starjumper is hardened for exatmo but can only maneuver around a planet.
The starjumper also has the name transfer station or transport satellite.

Airship::
An airship only has an inatmo drive and cannot travel outside of a planet's orbit or atmosphere.
Airships also have names like plane, dirigible, or rocket.
Mundane terra has a few airships that can throw satellites into orbit before crashing back to terra aqua.

:art: space_cruiser_slick_looking.png
:width: 450px
:snark: Even a space tug can look good.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Sleek pointy space ship against the outline of a planet.
include::ROOT:partial$articulate.adoc[]

=== Exatmo
The exatmo drive maneuvers the ship through the vacuum of space and is the defining feature of a spacecraft.
The exatmo drives are a sciency fiction core trope.
The larger the drive size, the more powerful the exatmo drive.
The exatmo drives are essential in spacecraft combat.
They can maneuver a ship well beyond survivable physics in combat. 

Exatmo drives will be one of two types: fusion or gravetics.
The player creating the spacecraft may choose between the two.
Both are equally efficient at moving the ship around exatmo.
Neither type of exatmo drive can function within the atmosphere.
Fusion and gravetics drives require an absence of gravity and atmosphere to function.

Both the exatmo drives function equally well.

=== Inatmo
The inatmo drive maneuvers the ship through the atmosphere and gravity of planets. 
These are the in-atmospheric drives of the ship.
Inatmo drives require both atmosphere and gravity to function, and they do not work in space. 
A spacecraft that does not have an inatmo drive cannot enter an atmosphere (safely).
A spacecraft with both inatmo and exatmo drives can enter and exit a planet's atmosphere.

All of the inatmo drive types function equally well.

include::hardware:partial$spacecraft_drives_inatmo.adoc[]

Antigrav::
Classic sciency fiction anti-gravity units suspend and maneuver the ship above the planet's surface.

Balloons::
Once in the atmosphere, balloons will automatically billow out and fill themselves with a computerized mixture of gases.
The ship is maneuvered about by altering the buoyancy of the various balloons.

Chutes::
This spaceship ejects an enormous collection of kites, and parachutes, which computers control to maneuver the ship while fuel supplies last.
The spaceship can employ prevailing winds to lift off.

Jets::
A multitude of fuel-burning jets (or rockets) maneuvers the ship in the atmosphere.

Props::
Large airscrews located about the ship operate at various power levels to attain maneuverability.

:art: spacevehicle_deep_space.png
:width: 450px
:snark: Oh look, a wormhole!
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: A space ship heading towards a hole in the time space continuum.
include::ROOT:partial$articulate.adoc[]

=== Special
Special drives technomagically fling the starship instantly across space.
Special drives replace generational spacecraft and unhealthy cryo-suspension.
Special drives are the cornerstone of sciency fiction space operas.
The speed of light is just not good enough.
The logistics of the 2000 year space flights are the root cause of special drives.
The special drives turn insurmountable distances into science fiction pulp.

All special drives function equally well.

include::hardware:partial$spacecraft_drives_special.adoc[]

Bloater::
A bloater drive expands the ship and its contents by increasing the space between its molecules.
The expansion continues until entire planets, stars, and galaxies can pass between the ship's molecules.
This bloating continues until the destination point is near the ship's hull.
The ship then begins to deflate around its new destination point, arriving instantly without moving.

FTL::
Faster than light travel plays havoc with many paradoxes.
FTL travel is a convenient way to get from point A to point B and advance the story.

Hyper::
Also known as jump drives.
Anything hyper does more than anything else in the same amount of time.
So the hyper drive covers light years faster than a non-hyper drive would.

Psi-Flip::
The psi-flip transports the ship to the location thought of by the navigator.
This drive requires a most precise mental image and corrects the reality so that the idea of the new location becomes true.
Once the psionic navigator has convinced her mind that she is somewhere else, the psi-flip drive corrects reality.
Psi-flip is known as a mind flip drive or a flip drive.
To navigate a psi-flip special drive requires 18 MND or a specially mutated persona.
Robots cannot operate a psi-flip special drive.

Time-Slip::
Another one of the mystically bizarre space travel devices is the time slip.
This drive system drops its payload into time limbo (likely hyperspace).
While in hyperspace, the drive scans through moments in the past/future until it finds a moment better aligned for its travel purposes.
The drive then re-enters the original space-time but at its desired location.

Transmat::
The transmat drive exploits electron probability to cover plot improving distances.
At some point, some electron of the ship will be near the location where they want to be.
Once this occurs, it is just a __matter__ of reorienting the ship's molecular parts with the vagrant orbital electron particle.
A transmat is also known as a probability drive.

Warp::
Warp drives operate under the premise that space can fold up, bringing stars much closer together.
Once space-time is folded, the spacecraft passes through the base of the fold.
This distance traveled is short, but the distance covered is enormous.
Warp drives are also called origami or laundry drives.

=== Power Level
The drive power represents how powerful the drive is.
The more powerful the drive, the faster, further the drive goes.
Each drive type has its own power level between one and ten.
The player rolls drive power from 1-10 (1d10) for each drive the spacecraft has.
The player may roll three times for a starship (exatmo, inatmo, and special) or once for a space tug (exatmo only).
The more powerful the drive is, the more hull space it occupies.

include::hardware:partial$spacecraft_drive_power_levels.adoc[]

Drive Power Level::
The player rolls drive power from 1-10 (1d10) for each drive the spacecraft has.
The player must record the drive power level for each drive type, i.e., Inatmo 4, Exatmo 2 and Special 6.
The drive power determines the drive size and drive performance.

Drive Size::
The more powerful the drive, the more hull space it occupies.
The larger the spacecraft, the larger the drive that moves it.
The tonnage of a drive is 1% of the hull size per level of drive power.
Each drive has its own power level, and therefore each drive occupies a unique amount of hull.
These individual drive wates are cumulative. 
A spacecraft with a 100-tonne hull has a power level 10 exatmo drive (zoom zoom) and a power level 5 special drive.
The drives occupy 15 tonnes of hull space.

Performance::
Each drive has a metric that each drive's power level multiplies.
A level 5 exatmo drive can move at 0.5 C (speed of light) and pull 5 G maneuvers. 
A level 5 inatmo drive can move at Mach 5 through the sky of a 5 G planet.
A level 5 special drive can jump 100 light-years.

Special Drives are Special::
The special drive can travel 20 light-years (LY) per level.
A level 6 special drive can travel 120 light-years in one moment.
The referee can change to what works best for the milieu and campaign, i.e., parsecs or astronomical units.
A special drive jump is usually instantaneous.
The referee can change this duration to what works best for the campaign, i.e., a jump may take days or weeks.
Regardless of the special drive type, the vessel travels through xref:appendices:generic_mythos.adoc#_the_spaces[hyperspace,window=_blank].
There is no communication within hyperspace or between hyperspace and physical space.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

== Fuel
Fuel seems like a trivial issue for a gallant expedition out to save the universe.
Energy is the limiter of all things, especially spacecraft.
Fuel is a tool to make gameplay more challenging and the storytelling more interesting.
The players can dispense with fuel's rules if desired.

.*Fuel Checklist*
. <<_type,Fuel Type>>
. <<_capacity,Fuel Capacity>>
. <<_consumption,Fuel Consumption>>

=== Type
A spacecraft's fuel type is a fun descriptor.
It is entirely up to the referee if gas from one vessel is compatible with gas from another vessel.
A spacecraft will only have one fuel type.
Each drive type will use the same fuel type.
The drive types may use the same fuel, but each drive type has different needs and rates of consumption.
Whether the spacecraft has a full tank, a half tank or vapours is up to the referee and the milieu of the campaign.

For more information about fuel and energy jump to xref:appendices:generic_mythos.adoc#_energy_and_power[Energy and Power,window=_blank].

include::hardware:partial$power_source_types.adoc[]


:art: spacevehicle_gigantic.png
:width: 450px
:snark: Rocking space ship
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0
:description: A very big space ship built around a rock.
include::ROOT:partial$articulate.adoc[]


=== Capacity
Capacity is the amount of fuel storage within the spacecraft.
The more drive types the spacecraft has, the more fuel the spacecraft may have.
Each drive type contributes an amount to the shared fuel capacity.
The fuel storage occupies hull space on the vessel.
The fuel amount also determines the range of the spacecraft.
 
include::hardware:partial$spacecraft_fuel_capacity.adoc[]

Capacity::
The fuel level indicates how much fuel each drive type contributes to the total fuel level.
For example, a spaceship has the following fuel levels: inatmo 8, exatmo 9 and special 3.
The total fuel level is 20, which determines the fuel storage and fuel range.

Storage Size::
Fuel storage indicates the amount of space that the fuel occupies in the hull of the vessel.
The total fuel level of all the drive types determines the size of the fuel storage.
Each fuel level occupies 1% of the hull displacement.
A fuel capacity of 20 occupies 20% of the vessel's hull space.
If this were a 100-tonne spaceship, a fuel level of 20 would occupy 20 tonnes of hull space.

Range::
The range indicates how long the spacecraft can run until it runs out of fuel.
The fuel level indicates the number of months that the ship can operate with a full tank.
A vessel with a fuel level of 20 would have a range of 20 months. 
The following section on fuel consumption explains the concept of fuel range as months.

=== Consumption
Fuel consumption varies with the drive type and how the expedition is using it.
Combat fuel consumption is much higher than tourist or haulage fuel consumption.

Both fuel consumption and fuel range are in units of time.
Calculating light-years, kilometres, or parsecs became overwhelming and tedious.
Using date time for monitoring fuel consumption allows for limits on fuel (if the campaign desires) and allows for more storyful measurements.

Each month of range consists of 30 days of fuel use.
A month of range is for that specific spacecraft.
The range takes into account the vessel size and all fuel necessary for the task at hand.
Choosing time to measure fuel burn proved to be the easiest way to keep track of fuel consumption.

Consider a special drive jump as an example.
A special drive jump uses one month of fuel and moves the ship as many light-years as the special drive level indicates.
A 10 tonne or a 100-tonne vessel would use one month of their fuel storage to make the jump.
This method allows the ship to make several jumps before refuelling but does not bog the players down with astronomical calculations.

include::hardware:partial$spacecraft_fuel_consumption.adoc[]

So a spacecraft with 15 months of fuel could make 15 special drive jumps or compete in 60 turns of space combat or 90 minutes of inatmo flight.
A spacecraft drops out of combat if there is less than one week of fuel onboard.
Depleting an opponent of fuel is a victory condition.
A spacecraft cannot jump if there is less than one month of fuel onboard.

The nature of refuelling depends on the referee's milieu and campaign.
Some fuel types may be ubiquitous materials that one skims off the local gas giant.
Other fuel types may require days of retooling by highly skilled space mechanics.

== Computer
The computer is the vessel, and the vessel is the computer.
The computer integrates deeply with every system on the spacecraft.
The computer is essential for special drive jumps, combat maneuvers, life support, gravity and more.
A spacecraft requires both a computer and crew to function.
Pilots, navigators and engineers work on the spacecraft through the ship's computer.
Software can replace the crew of a spacecraft, but there are no manual spacecraft.

Life support protects the vessel's cargo, but it is really there for the ship's computer.
A dead computer is a dead spacecraft.
Cargo and crew come and go, but ship's last generations.

.*Installing the ship's computer*
. Computer Level
. Computer Size

The ship's computer is distributed throughout the entire spacecraft.
There may be a central location for interaction with the ship's computer.
This central computer interface could be called the ship's bridge, but a ship's bridge is not strictly necessary.
Personas acting as the ship's crew can be located on a bridge or distributed about the vessel.

A ship's computer is not an autonomous Intelligence. 
However, it may have attitude and personality.
The referee may consider the ship's computer a referee persona.
However, it will be friendly and helpful for vessel operations.
The expedition may interact with the computer via devices or voice interaction.

[discrete]
=== Computer Level
The higher the computer level, the more powerful it is.
A higher ship's computer level improves everything from the galley food to combat maneuvers. 
The higher the level of the computer, the more complicated the software it can manage.
The computer level ranges from 1-10 (1d10).

The bigger the ship, the larger the computer.
The computer size and wate represent all components, wiring, peripherals, terminals, processors and doohickeys.
The ship's computer occupies 1% per level of hull space.
So a 200-tonne starship with a level 4 computer would have 8 tonnes of computer equipment on board.

:art: swirling_opportunity.png
:width: 550px
:snark: Remember where you are standing.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Swirling image of a many stars and galaxies.
include::ROOT:partial$articulate.adoc[]

== Software
Computer software broadens the ship computer's skills in specific areas.
All spacecraft automagically maintain life support, gravity and keep things from exploding.
A spacecraft needs direction from personas to get up and go.
A ship's computer is artificially intelligent but not autonomously intelligent.
The computer level determines the effectiveness of the software.

The software will include any hardware and connections it needs to function on the vessel.
A software package may physically bolt onto the spacecraft or be auto-downloaded from https://github.com/mobilehugh/EXP_Documents[GitHub].

There is no limit to the amount of software a ship's computer can house, but there is a limit to the number of programmes that it can simultaneously operate. 
A spacecraft is limited to deploying one software title per computer level at once.
Players will have to make choices about what is the most critical package to run.

=== Crew
Crew replacement software indicates programmes and mechanical devices that can replace essential crew.
In some circumstances, the crew software replaces the required crew member completely.
In other circumstances, the programmes direct a persona or robot on how to operate the system.

Crew replacement software is limited by the computer's level. 
A spacecraft is limited to using one software title per level of computer at once.
A low-level ship's computer may always require a persona crew member to function.

The player rolls decidice (1d100) for each programme, and there is a chance of having it.
A level 3 computer has a 60% chance of an astrogation programme and a 15% chance of a piloting programme.
The player rolls once for every item on the chance table, i.e., she makes a separate roll for astrogation, navigation etc.

include::hardware:partial$spacecraft_programmes_crew.adoc[]

Astrogation::
This programme allows any persona to pilot the special drives.
The persona works directly with the ship's computer to plot special drive jumps. 
When an astrogator uses this software, she can reduce fuel usage for jumps (2 weeks) or decrease the duration of time in hyperspace.

Engineering::
This software title allows any persona to carry out ship maintenance and repairs. 
The ship's computer directs personas what needs doing, where it needs doing and how to do it.
Combining engineering crew replacement with a robot can make for nearly seamless spacecraft operations.
A mechanic working with this software gets bonuses on her task rolls for ship-related maneuvers.
Ship repair and maintenance task rolls get a bonus of +5 per level of the ship's computer.

Navigation::
This software title allows any persona to pilot the inatmo and exatmo drives.
The persona works directly with the ship's computer via specialized control devices (steering wheel). 
A pilot or navigator working with this software can optimize the programme, saving fuel or making unorthodox maneuvers.
Combat fuel usage is unaffected by this teamwork.

Piloting::
This programme allows any persona to hand over all maneuvers to the ship's computer completely.
Piloting includes navigation, astrogation and combat maneuvers. 
Piloting software is very advanced, and it may have its own personality that interacts with the personas and ship's computer.

=== Operations
Miscellaneous software consists of programmes that vary from functional to sublime.
The programmes include both the hardware and software that the packages need to operate.
The programmes allow the ship's computer to carry out the task and help personas perform maneuvers.

When a persona can use the ship's computer for a maneuver, she enjoys a bonus of +1 per computer level.
For instance, a persona who can use the etiquette programme to help cater a fancy dinner.
If the computer level is 5, the persona gets a +5 DD bonus when making the meal. 

The player makes one roll per level of the ship's computer. 

include::hardware:partial$spacecraft_programmes_operational.adoc[]

== Crew
Spacecraft vary in size from personal craft to city-sized leviathans.
They can have fantastical drives that flit them across the stars and computers that weigh tonnes.
An essential element is still the crew.
EXP is about personas and has a persona focus. 
Spacecraft are tools to help tell stories by moving personas and cargo from place to place. 


TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

The crew of a spacecraft can be composed of aliens, anthros, or robots.
Every spacecraft has an essential crew.
Without the essential crew, a spacecraft will not move.
A spacecraft will have the essential crew on board or the software programmes to replace them.

.*Essential Services*
. Pilot
. Astrogator (for special drive)
. Engineer

Some spacecraft will require even more crew. 
Some spacecraft will require multiple engineers. 
These three are the essential crew needed.

:art: crude_replacement.png
:width: 450px
:snark: Pilot in a drum.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Spaceship cockpit with humanoid robot pilot and humanoid navigator.
include::ROOT:partial$articulate.adoc[]

=== Pilot 
The pilot is an essential crew member, and a spacecraft cannot function without one.
The pilot is the overseer of all the ship's functions.
She is responsible for executing planetary maneuvers, star system maneuvers, combat maneuvers, ship procedures, and ship authority.
All of these tasks require the intimate cooperation of the ship's computer and the pilot.
Without a pilot, the ship is a motionless piece of space opera potential.
No ship can travel without a pilot.
Spacecraft can have personalities and attitudes, but they are *not* autonomous lifeforms. 

Every 10000 tonnes of displacement requires an additional pilot (co-pilot).

.*Qualified Pilots*
. Mechanic vocation with pilot skill
. Nothing vocation with pilot skill
. Exatmo transport bot

=== Astrogator 
The astrogator is an essential crew member if the ship has a special drive.
The astrogator operates the ship's special drive, and a special drive cannot function without one.
The astrogator works with the ship's computer to coordinate a safe special drive jump.

.*Qualified Astrogator*
. Nomad vocation
. Knite vocation
. Mechanic vocation with astrogation skill
. Nothing vocation with astrogation skill 
. Exatmo transport bot

=== Engineer
The engineer is an essential crew member, and a spacecraft will malfunction without one.
The engineer does essential repairs and maintenance on the spacecraft.
A spacecraft may jump once or engage in combat once without an engineer.
Afterwards, it will not function.
Without maintenance, the spacecraft will cease to operate.

The engineer maintains tonnes of drives, complicated airlocks. 
There is a lot that will go wrong.
It is the responsibility of the ship's mechanic to monitor the computer's maintenance programs, to program repairs, and to pick up the wrench herself occasionally.

A spacecraft requires an extra engineer for every 9000 tonnes of hull displacement.

.*Qualified Engineer*
. Mechanic vocation
. Maintenance robot

=== Gunner 
Gunners operate the combat equipment: artillery, naval artillery, mines, active defences, missiles, and shields.
None of the listed equipment will function without a gunner or a software replacement.
Combat robots can replace a gunner without the need for a gunnery program.
Combat robots can operate one active combat device for every 4 points of Intelligence.

.*Qualified Gunner*
. Mercenary vocation
. Spie vocation
. Combot

=== Doctor 
Any spacecraft that has organic passengers requires a ship's doc.
Guests, soldiers, cattle without proper vet attention will get sick in deep space.

.*Qualified Ship's Doc*
. Veterinarian vocation
. Diagnostics veterinarian robot

:art: spacevehicle_QE_lots.png
:width: 450px
:snark: QE 1113
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Luxury cruise liner space ship orbiting a planet.
include::ROOT:partial$articulate.adoc[]

=== Steward 
Guest laden starships require a ship's steward.
The steward changes linen, washes clothes, and generally makes space travel bearable for guests.
Without a steward, guests will undoubtedly be in a bad temper and may even rebel during a long trip.

A spacecraft requires one steward for every 50 passengers.

.*Qualified Steward*
. Nothing vocation with SOC < 420
. Social robot
. Domestic janitorial robot

=== Administrator 
One optional crew member who the expedition may actively shun is the ship's administrator.
The ship's administrator will arrange docking papers, interpret cartage laws, balance accounts, designate cargo allotments, and fill in as the ship's legal advisor.

.*Qualified Administrator*
. Nothing vocation with INT < 12
. Transport robot
. Datalyzer robot

=== Diplomat 
The diplomat is good at being excruciatingly polite, even to the most horrific of alien species.
A diplomat will attempt to keep the crew, the guests, (and especially the personas) from offending rarely encountered cultures.

.*Qualified Diplomat*
. Nothing vocation with CHA > 12
. Biologist with culture and sociology
. Social robot


== Defensive Systems
A ship's defences comprise anything that protects the contents of the spacecraft.
The defences include computer programmes and structural protections.
For example, the computer assists with evasive maneuvers, the hull is fortified, and there is a force field.
Life support, gravity and hull are considered defensive systems. 
Life support works together to defend against the harshness of exatmo.
Intentional defences, like ECM and shields, are designed to protect the ship in combat.

The player rolls decidice (1d100) for every defence on the list.
A level 3 computer has a 30% chance of electronic countermeasures and a 6% chance of active defences.
The player rolls once for every item on the chance table, i.e., she makes a separate roll for ECM, Shields etc.

include::hardware:partial$spacecraft_defensive_systems.adoc[]

=== Life Support Onion
The life support onion is the layering of the spacecraft defences that protect the contents of the hull.
The innermost part of the onion is life support itself. 
Before anything can damage or impair life support, it must work its way through all the outer layers. 

Before damaging life support, the outer layers of the onion must be disabled or destroyed. 
The outermost layer of the onion is the ship’s shields. 
If the ship does not have shields, the outermost layer of the onion is the hull Defence Rating. 
The hull Defence Rating must fail before the hull can be damaged. 
The hull must fail before gravity control can be damaged. 
Gravity control must fail before life support can be damaged.

include::hardware:partial$spacecraft_onion_of_life.adoc[]

To learn how defensive systems work in combat jump to 
xref:combat:combat_and_exatmo_vehicle_intro.adoc[Spacecraft Combat,window=_blank].


=== Life Support
Life support maintains a comfortable environment for the organic and delicate inorganic contents of the ship.
The most straightforward description is an 'outer space air conditioner.'
Destroying the life support system exposes all of the hull's contents to the deadly vacuum of space.

Life support is entirely self-contained and is impossible to tamper with and hard to destroy.
The life support system functions entirely unknown for the players until something goes wrong.
Life support, gravity, Defence Rating, hull and shield (if present) are all part of the <<_life_support_onion,Life Support Onion>>.

=== Gravity
Gravity maintains a safe, comfortable and convenient gravitational force throughout the space vessel.
The gravity system allows the personas to work in comfort and protects them from extreme maneuvering gravities.
A spacecraft's exatmo drives generate gravities that would kill any organic or delicate inorganic persona.

Gravity works on walkways, workspaces, cargo holds, cabins, and the exterior hull.
The ship's computer controls gravity at a constant attraction of 1g with local adjustments between 0.5  and 1.5 gravities.

Gravity is entirely self-contained and is difficult to tamper with and hard to destroy.
The gravity system functions entirely unknown for the players until something goes wrong.
Life support, gravity, Defence Rating, hull and shield (if present) are all part of the <<_life_support_onion,Life Support Onion>>.

=== Hull
The hull defines the space vessel.
The hull protects the contents of the spacecraft from the lethal vacuum of space.
Every spacecraft system is part of the hull, and the hull contains every spacecraft system.

The hull also determines the shape of the spacecraft.
The players decide the shape of their spacecraft.
Most often, the hull is an oblong spheroid that contains the spacecraft's contents.
A spacecraft that can enter the atmosphere may have a more streamlined appearance. 

The hull is the structure that maintains the ship's gravity and life support.
Life support, gravity, Defence Rating, hull and shield (if present) are all part of the <<_life_support_onion,Life Support Onion>>.

=== Armour 
Armour indicates the strength of the spacecraft's hull.
Armour is in addition to the shape and structure that the hull offers. 
The hull and Armour have an intimate relationship.
The Armour protects the hull and makes its appearance as the hull strength during hull creation.

NOTE: Armour is hull strength is defence rating. 

The Armour of the hull determines the structural resilience of the hull during combat. 
Attack rolls must be higher than the hull's Armour to damage the vessel.
Damage reduces Defence Rating.
Once the Armour drops to 420, it no longer protects the hull.

The Armour is a component of the life support system.
Life support, gravity, Defence Rating, hull and shield (if present) are all part of the <<_life_support_onion,Life Support Onion>>.

=== ECM
Electronic countermeasures (ECM) manipulate the electromagnetic spectrum to defend the ship.
A more powerful ship's computer makes for more effective electronic countermeasures.
ECM is a combination of programming and equipment.
ECM is integrated throughout the ship and connects to every ship system.

ECM uses all kinds of electronic deception to both defend or attack.
Personas can use the ECM unit to defend the ship or attack another ship.
One ECM unit cannot do both in the same combat turn.

Personas can work in unison with ECM to protect the space vessel.
For example, a mechanic with ECM 2 working with a level 3 computer creates a total ECM level of 5.

Electronic countermeasures are not part of the life support onion.

=== Shields
The shields protect the hull Defence Rating from energy and kinetic attacks.
These are the classic sciency fiction shields that handsome captains raise just before combat.
The defensive shield can be a force field or a structural mechanism. 
Both mechanisms work by distributing the destructive force across the entire hull.
This faux scientific diffusion effectively dampers the damage.
The shields have an active mode that the players turn on to thwart intentional damage.
Shields also have a passive mode, and when present, they are part of the life support onion.
Life support, gravity, Defence Rating, hull and shield (if present) are all part of the <<_life_support_onion,Life Support Onion>>.

=== Guns
A gun is a defensive tool in spacecraft combat.
A gun does not sound like a defensive tool, but occasionally the best defence is a good offence.
Guns on spacecraft are anti-personnel air lock defence weapons.
In ship-to-ship combat, a gun is an ineffectual weapon.
However, to prevent boarding or airlock intrusion, a mounted gun can be very effective.
To create the airlock gun jump to xref:hardware:guns.adoc#_generate_type[Guns,window=_blank]

Guns are not part of the life support onion.

.*Airlock Defensive Guns*
* can swap between inside and outside the airlock
* operate inatmo or exatmo
* Can be controlled by personas or ship's computer
* has unlimited ammo to defend against boarding
** ammo may deplete for game balance and fun
* has an DEF equal to the ship's hull
* damaged by Hull DEF damage or airlock damage

=== Active
Active defences are fancy mechanisms that attack incoming attacks.
Active defences are sometimes called actives.
They can eject missiles, shrapnel, energy blasts, lazer matrices, or crystalline discharges. 
All active defences function equally, and the description is the player's choice.
Their goal is to dissipate, prematurely detonate, or destroy incoming attacks.
Active defences work against grenades, mines, or artillery.
Actives do not work against boarding, ramming, ECM, or naval artillery.

.*Notes about active defences*
* Active defences are automated
** Gunnery skilled personas can help
* Active defences work inatmo and exatmo
* Actives cannot be weaponized

== Offensive Systems
Space vehicle combat is highly discouraged due to the high probability of persona mortality.
Offensive systems are for damaging and disabling spacecraft. 
Due to the value of spacecraft, they rarely suffer intentional destruction.
The offensive systems are tools for weakening a vessel in preparation for boarding.

A spacecraft may have offensive systems because they are pirate scum.
A spacecraft may have offensive systems to fight pirate scum.
There is no official EXP military spacecraft.
A vessel that has naval artillery, mines, or missiles becomes a military spacecraft.

To learn how offensive systems work in combat jump to 
xref:combat:combat_and_exatmo_vehicle_intro.adoc[Spacecraft Combat,window=_blank].

The player rolls decidice (1d100) for every attack on the list.
The referee goes down the list rolling once for each attack type.
So a spacecraft with exatmo drive level 4 would have a 20% chance of ramming, a 16% chance of ECM, and a 2 percent chance of Naval Artillery.

include::hardware:partial$spacecraft_offensive_systems.adoc[]

=== Boarding
Boarding lines up airlocks to prepare for a breach and boarding of the target vessel.
All spacecraft can attempt to dock with another vessel forcibly.
Boarding is congenial ramming.
Boarding only works exatmo (exterior to atmosphere).
Once connected, the attacking crew will breach the airlock of the target ship and then board.
This method of attack preserves the target spacecraft, generating hostages, free cargo, and is a lot more fun.

=== Ramming
Ramming is aggressive boarding casting caution to the solar wind.
A ramming spacecraft has a specialized airlock that can attach to any part of the target ship's hull.
Once attached, the attacking party must breach the hull or airlock to enter the ship.
Ramming is similar to boarding, except that ramming has lots of crunching and scraping noises.

=== ECM
ECM is the acronym for electronic countermeasures.
ECM units battle for control over the electromagnetic spectrum.
In spacecraft combat, ECM is the battle for control over the electronics of the other vessel. 

ECM uses all kinds of electronic deception to both defend or attack.
So the personas can use the ECM unit to defend the ship or attack another ship.
One ECM unit cannot do both in the same combat turn.

Personas can work in unison with ECM to protect the space vessel.
For example, a mechanic with ECM 2 working with a level 3 computer creates a total ECM level of 5.

=== Grenades
Grenades in space!
In spacecraft combat, grenades are tiny bombs exploding against the hull to damage the internal mechanisms of the ship.
Grenades launch their attack by mini-missile or mini-mine.

They do not enjoy the area of effect attack of their terrestrial counterparts.
Grenades require a successful attack roll to inflict damage.
If the attack roll is unsuccessful, the grenade detonates ineffectively and silently in space.
Grenade delivery systems have diminutive titles because they only deliver grenades. 
Naval missiles and naval mines deliver bombs.

include::hardware:partial$spacecraft_grenades.adoc[]

=== Bombs
Bombs are lethal attack weapons.
Bombs are both dangerous and destructive.
Bombs delivery systems are either missiles or mines.
Missiles and mines can also be called naval missiles or naval mines.
Having this type of offensive system indicates a combat vessel of some fashion.

In space, bombs are an area of effect weapon.
Bombs need only explode near the ship's hull to inflict damage to the contents within.
A bomb is guaranteed to damage a target with a successful attack roll.
Every bomb gets a second chance to damage a vessel just by getting close enough. 
If the raw attack roll of a missile or mine is higher than 500, the target is still damaged.

include::hardware:partial$spacecraft_bombs.adoc[]

=== Artillery
The purpose of ship artillery is to damage the target ship so that it ceases to function.
This goal is to wear down shields and armour and directly damaging the hull if necessary.
In space combat terms, artillery is very tiny and is only in range when vessels are boarding or ramming. 
Naval artillery is the literal big gun of space combat.

In space combat (exatmo), artillery must win an attack roll to damage the target vessel.
While inside the atmosphere (inatmo), artillery functions as an area of effect weapon on terrestrial targets.
Artillery cannot cross into the atmosphere or out of an atmosphere.

Ship artillery has the same ranges, damages, and effects as the artillery it is modelled after.
Energy-based weapons can fire as long as the ship has fuel, and artillery requiring ammo will have 100 times the regular supply.

include::hardware:partial$spacecraft_artillery.adoc[]

=== Naval Artillery
Naval artillery is for destroying the target ship.
Naval artillery is not for softening the target vessel.
The sheer force of naval artillery leads to the target's destruction.
One use of naval artillery exhausts a whole day's worth of fuel.
Naval artillery requires a gunnery program and a gunner.
Without this complement, the ship cannot fire its naval artillery.

NOTE: *Artillery are big guns. Naval artillery are big big big guns.*

Naval artillery is more deadly than regular deadly artillery.
Naval artillery inflicts three times the damage and has 100 times the range.
Naval artillery only works exatmo and cannot fire inatmo or cross into an atmosphere.

The player rolls on the spacer artillery table above and then does arithmetic as directed below.

include::hardware:partial$spacecraft_naval_artillery.adoc[]

== Baked-in Systems
Spacecraft are not guaranteed to have an airlock, cabins, sickbays. 
These are all choices made by the referee or player generating the spacecraft.
Every spacecraft will have the required systems described below.
None of the required systems occupy, or need, cargo space and built into the spacecraft.

=== Access Port
Allows access to the spacecraft when inatmo. 
If the spacecraft has an airlock, the airlock can function as the inatmo access portal. 
A spacecraft may have one access port per 20 tonnes of hull size.
Access ports are not limited by hull space or cargo space. 

=== Workspaces
Every crew member requires a workspace. 
A workspace is __not__ a cabin or an office. 
The workspace may be a chair with a console with or without 
Each crew member (pilot, engineer, astrogator) requires a half tonne of workspace.

=== Utility Corridors
The entire ship is accessible by utility corridors.
Utility corridors connect workspaces, drives, computers and fuel systems. 
They are cramped, claustrophobic and slow to navigate.
Utility corridors occupy no significant amount of hull space.
However, they are cramped, claustrophobic and slow to navigate.

=== Datalocks 
Datalocks are also called hardpoints.
Data locks are electronic accesses to the exterior of the hull.
Every external contraption requiring exatmo access (guns, missiles, viewers, etc.) requires a datalock.
A ship has ten datalocks per computer level.

=== OSHA 
Outer space habitat assurance is an extension of the life support system.
OSHA will temporarily repair minor air leaks, and suppress small fires.
OSHA may also close off bulkheads to contain larger fire, depressurization or radiation leaks.
While it appears that this is for the crew of the spacecraft it is actually there to protect the ship's computer.

The ship can only look after itself in a limited way.
Major events must be dealt with by the crew.
Major hull repair, radiation clean up and passenger rescue need actual personas on board.

:art: space_ship_shape.png
:width: 450px
:snark: The player shapes the shipshape ship's shape.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Pointy alien looking spaceship. 
include::ROOT:partial$articulate.adoc[]

== Accessory Systems
The accessory systems are the non-essential, but fun sciency fiction components of spacecraft. 
They include airlocks, cold storage, workspaces, cabins, sickbays, and corridors.
The types of accessories available depend on hull space. 

=== Hull Space 
Hull space determines what can be attached to or built into the spacecraft. 
Hull space is the remaining tonnage available after drives, computer and fuel is taken into account. 
Accessories are limited to available hull space. 

Let's walk through an example 100 tonne spacecruiser (space bus).
Exatmo drives level 10.
Fuel storage level 5.
Computer level 4.

include::hardware:partial$spacecraft_hull_space.adoc[]

=== Airlock

* Requires: 5 tonnes
* Occupies: 0 tonnes

An airlock allows passengers, crew and stuff to get in and out without decompressing the spacecraft.
Airlocks work perfectly well inatmo.
Airlocks are simple, secure and safe.
Any tool using life form can use an airlock.
They usually employ pictograms and may even have language assist.
Airlocks are secure. 
The ship will only allow the identified crew to enter the spacecraft.
Airlocks are safe.
It would be nearly impossible to eject a life form from a functioning airlock.

An airlock takes up no space __inside__ the spacecraft.
However, an airlock requires at least 5 tonnes of hull space.
A ship can have one airlock for every 5 tonnes of  hull space.
So a ship with a 15 tonnes  hull hold could support three airlocks anywhere on its hull.

Smaller spacecraft do not have enough space for an airlock.
Airlocks are free to be located anywhere on the spacecraft.
A ship with only 2 tonnes of hull space can only have an access port.

=== Cargo Airlock

* Requires: 500 tonnes
* Occupies: 1 tonnes per 2 tonnes capacity

Cargo airlocks are enormous airlocks that only gigantic spacecraft can use.
The cargo airlock can move cargo in and out without depressurizing the spacecraft.
A cargo airlock requires at least 500 tonnes of hull space.
Cargo airlocks are rated by how many tonnes of cargo they can move at once.
For example a cargo airlock may need to allow a 10 tonnes spacecraft to pass through it.
For every 2 tonnes of capacity 1 tonne of hull space is required. 
So a cargo airlock that allows 10 tonnes of spacecraft to exit exatmo would eat 5 tonnes of hull space. 

There are no open hull force field protected cargo airlocks in EXP.
Development is ongoing, and EXP users may reach this milestone with expected technological advances.

=== Cabins 

* Requires: 1 tonnes
* Occupies: 1 tonnes

Cabins are a space luxury.
If a spacecraft has passengers, other than in cold storage, it must have cabin space.
If a spacecraft has cabins it must have corridors connecting them. 
Each cabin requires one tonne of hull space and can comfortably house two passengers.

=== Cargo Lock

* Requires: 50 tonnes
* Occupies: 0 tonnes

A larger ship may prefer a cargo lock.
A cargo lock is not pressurized and can only work inatmo. 
It is like a big access portal.
A cargo lock requires a minimum of 50 tonnes of hull space.
A cargo lock does not occupy any cargo space.

A cargo lock is more than just a door; it is a system.
A typical cargo lock has a capacity of 10 tonnes.
A 10-tonne cargo lock can load/unload 10 tonnes of cargo per hour or a day or whatever.

=== Cold Storage 

* Requires: 0.25 tonnes
* Occupies: 0.25 tonnes


Cold storage is for cryogenic suspension of organic material less than 250 kg in wate.
The freezers will maintain life, with no drain on life support, and will continue to function after life support has failed.
Cold storage will work until the cold storage box itself is destroyed.
Each cold storage space occupies a half tonne of cargo space.

=== Corridors 

* Requires: 0.2 tonnes
* Occupies: 0.2 tonnes per hex

Corridors are passageways that connect cabins, workspaces or ship systems.
Corridors are considered a space luxury, but are required if there are cabins.
Cabin corridors require 200 kg of hull space per map hex (2 meters) of passage.
If personas want to run from the artillery bay to the exatmo drives quickly, corridors are a must.

The entire ship is accessible by utility corridors.
Utility corridors occupy no significant amount of hull space.
However, they are cramped, claustrophobic and slow to navigate.

=== External Drives

* Requires: 0 tonnes
* Occupies: increases hull space

External drives are self-explanatory.
Exatmo or inatmo drives are bolted onto the outside of the hull freeing up hull space.
The drawback of this system is that the drive units are more vulnerable to attack during combat.
Any attack that damages the hull of the spacecraft would damage the external drives. 
External drives are accessed directly through the hull or via an airlock.

Special drives are delicate and can never be external.

=== Gravity Couches

* Requires: 0 tonnes
* Occupies: 0 tonnes

Gravity couches are specialized chairs designed to save the body from damage during the lethal maneuvers of combat.
They are composed of force-absorbing materials and restraining belts.
Grav couches allow a spacecraft to maneuver even with a damage gravity system.
Passengers and crew not in gravity couches during high-g combat maneuvers are dead.

These are military devices and are only found on military craft (pirate or government).
A combat vessel is a spacecraft with naval artillery, bombs or grenades.

=== Life Bloats

* Requires: 0.25 tonnes
* Occupies: 0.25 tonnes (1 per 4 guests)

A life bloat will maintain four passengers (up to 250 kg in wate each) in cryogenic suspension for an indefinite length of time.
The cryogenic suspension will begin when the balloon-like life bloat is subject to exatmo.
There will be one life bloat for every four luxury passengers.

=== Machine Shop

* Requires: 2 tonnes
* Occupies: 2 tonnes

The machine shop is a mechanic's place of operation and personal respite.
A machine shop requires two cabins (2 tonnes) worth of space.
There is a 5% chance per robot on board of having a machine shop.

=== Mess 

* Requires: 1 tonnes
* Occupies: 1 tonnes (1 per 10 guests)

The food machine will generate nutritionally balanced meals for anything that eats.
The referee determines the palatability of said foodstuffs.
Most food machines employ algae, or fungal, cultures to create the primary heterotrophic food groups.
One tonne of food machine is required for every ten eaters supported.
Because of their potential for comic relief, all ships will have a food machine.
Food machines are also known as compu-cooks and auto chefs.
If the food machine is busy enough, it would be reasonable to give it a personality.

=== Robots 
Robots are a common occurrence on long-haul spacecraft.
The use of robots must reflect the referee's milieu.
The robots can be on board to replace crew, to aid crew, or as paying guests.
The chance of a ship sporting a particular robotic has many factors. 
The depth of persona fabrication that goes into spacer robots depends on the referee's resources and story needs.

The player rolls decidice (1d100) for every robot type.
A level 3 computer has a 6% chance of having a maintenance robot on board.
The player rolls once for every item on the chance table, i.e., she makes a separate roll for combots, social robots etc.


include::hardware:partial$spacecraft_robots.adoc[]

=== Sickbay 

* Requires: 2 tonnes
* Occupies: 2 tonnes

The sickbay is the veterinarian's place of operation and personal respite.
A sickbay can hold four patients and takes up two cabins (2 tonnes) worth of space.
There is a 1% chance per organic persona that the spacecraft will include a sickbay.
If the spacecraft has a ship's doc (veterinarian), there will automatically be a sickbay.

=== Vac Suits 

* Requires: 0 tonnes
* Occupies: 0 tonnes

Vac suits allow delicate organic life forms to survive exatmo.
A spacecraft will have one civilian vac suit per crew member and luxury cabin.
So a pleasure cruiser with five crew and six cabins would have eleven civilian vac suits.

There is a 10% chance per civilian vac suit that there will be an industrial vac suit.

For more information about vac suits jump xref:hardware:armour.adoc#_vac_suit[Vac Suits,window=_blank].

== Cargo Space
Cargo space is protected from exatmo and allows for the transfer of stuff.
Often the expedition will earn money for transporting cargo.
More often, the cargo will become the focus of an exatmo spacecraft adventure.

Let's walk through an example 100 tonne spacecruiser (space bus).
Exatmo drives level 10.
Fuel storage level 5.
Computer level 4.
There are 20 passengers, 16 in cold storage and 4 in Cabins.
The crew consists of a pilot, engineer, doctor, and steward.
There are no robots and no crew replacement software.
After all deductions, there are leaves 63 tonnes of cargo space in the vessel.
The remaining cargo space allows for a cargo lock and multiple airlocks.
The cargo lock does not work inatmo, so its inclusion is a mystery.
Sixty tonnes is the capacity of two mundane terran dump trucks.

include::hardware:partial$spacecraft_cargo_space.adoc[]

== Parameters

=== EXPS
The EXPS value of a spacecraft is impossible to assess.
The expedition earns experience for a spacecraft once they have flown it somewhere.
In austere resource campaigns, the EXPS award for an earned spacecraft is one complete EXPS level.
If spacecraft are commonplace, this EXPS award only counts once.

=== Value
A spacecraft's value depends on several components: hull, drives, computer, etc.
Wear and tear may have reduced a ship to worthlessness in one culture, while another will pay dearly for anything that can get them into orbit.
Spacecraft are precious.
Spacecraft with powerful computers and special drives are worth enormous amounts.

include::hardware:partial$spacecraft_value.adoc[]

==== Example Value Calculation
The following is an example value using the space bus from above.
The spacecruiser has 100 tonnes displacement, Defence Rating of 700, exatmo drive 10, fuel level 5, computer level 4, etc.

include::hardware:partial$spacecraft_value_example.adoc[]

== Operations
Space vehicle maintenance and operational cost are tedious.
The main operational costs of a spaceship are wages and fuel.
Maintenance carried out by the ship's engineer costs nothing and is completed correctly.
Replacing destroyed parts costs the same as the calculated value of the part.
Upgrading parts cost the same as the calculated value of the new part.
The cost of parts includes parts and labour.
Refitting takes weeks to months. 

:art: busy_bow_prop_repair.png
:width: 450px
:snark: Inatmo drive repair.
:artist: Ladrimal
:date: 1887 (yes 1887)
:license: CC BY-SA 4.0
:description: Workers repairing propeller of flying ship.
include::ROOT:partial$articulate.adoc[]

General refitting is necessary for alloy hulls.
After extended travels or any combat, the hull will require refitting.
Not refitting the spacecraft will lead to mechanical failure.
The refitting will cost between 0.01% and 0.1% (rolled on 1d10) of the ship's total value.
Woah, it takes a lot of cargo haulage to refit a big spacecraft.
If the refitting costs were .05% of the ship's value, then a spacecraft worth 500000000 would cost 250000 to refit.



