= Startifacts

[quote]
____
*A bad manual transforms the simplest technology into magic* 
____

:art: babooshkas_PSH.png
:width: 550px
:snark: Complicated old lady doll
:artist: Pat Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Relaxed researcher inspecting set of Russian dolls.
include::ROOT:partial$articulate.adoc[]

== Startifacts
Startifact is a portmanteau of start and artifact.
There is a legacy rule in EXP of fresh personas starting the game with a few artifacts.
Artifacts are different from mundane equipment. 
Artifacts can be technomagical devices that transcend comprehension.
Artifacts can also be complete junk.
Startifacts are usually secret.
Players roll the dice to generate their persona's startifacts, but the referee records their info with an alloy-clad poker face.

A startifact should not destroy a referee's plot or milieu.

== TOYs
The players generate technomagical equipment using the Technological Object Yield System.
This Technological Object Yield System is called TOYs for short, and anything it generates is a toy.
An unidentified toy is called an artifact.
An identified toy is called a toy or equipment.
Each table of players will develop their language for equipment.

== Number 
Players get *three* startifacts, maybe. 
Personas can end up with more or less than three items.

Junque and minimal Treasure do not count as startifacts.
In this case, the persona may get more than three items, although some are useless.
Spaceships, vehicles, robots and other powerful items stop startifact generation.
In this case, the persona may get less than three items because of the item's power.

== Limitations
Personas are not allowed to amass artifacts related to their vocation.
Vocation toy limits is a legacy rule within a legacy rule.
This rule prevents personas from being overpowered with startifacts.
It also encourages the expedition to work together from startup.
The player should stop generating startifacts according to the below table.
For example, a player rolling startifacts for her mercenary persona would stop once she generates a weapon.

include::hardware:partial$toys_vocation_limitor.adoc[]

== Generation
The referee is free to modify the roll on the fly.
If a spacevehicle defeats the purpose of the entire campaign, roll again.
If the table is looking for tables that focus on combat, uncombat, or cool stuff jump to xref:hardware:generation.adoc[TOY Generation].

=== Plot Protective
This table generates TOYs that tend to not mess with plot as the unlimited table. 
Referees may limit personas from austere milieus, aliens from limited tech strata to this table. 

include::hardware:partial$toys_plot_safe.adoc[]

NOTE: The roll must fit the plot. If not, roll again.

=== Raw Roll 
Anything goes technological chaos. 

include::hardware:partial$toys_departments_list.adoc[]

NOTE: The plot must roll with the artifacts. 

== Presentation
How the technological chaos arises is up to the milieu of the referee.
Did countless societies rise and fall, leaving their technology to be found later?
Did alien civilizations leave their garbage behind under https://en.wikipedia.org/wiki/Stargate[pyramids,window=_blank]?
Or is it both?

== Identification
Personas may not know how their startifact works. 
In fact, personas usually have no idea how their startifacts work.
Some TOYs can blow up the expedition if mishandled. 
Startifacts can play a role in both persona and campaign story development.
Most often players roleplay their way through artifact identification.

For the mini-game of artifact identification xref:uncombat:artifact_id.adoc[jump here.,window=_blank]

