= Treasure

:art: treasure_chips_sand.png
:width: 250px
:snark: Arrgh space pirate plunder
:artist: Peggy Lynn MacIsaac
:date: 1991
:license: CC BY-SA 4.0
:description: Open treasure chest with gold and computer parts.
include::ROOT:partial$articulate.adoc[]

Virtually anything can be considered treasure.
A treasure artifact is only valuable for it's value. 
Treasure rarely has any useful purpose other than it's value.
A beautiful crystal may have an enormous value for no functional reason at all.
The beautiful crystal cannot be used as a weapon, or fuel, or food. 
Assigning value to treasure is deliciously random, and literal junk can have enormous value.
Treasure can lead to repetitive dice rolling.
Everyone needs practice rolling dice and the more you practice the luckier you are. 

To refresh on how money works in EXP jump to xref:uncombat:money.adoc[Money,window=_blank].

.*Treasure Checklist*
. <<_treasure_value,Treasure Value>>
. <<_treasure_types,Treasure Type>>

== Treasure Value
The base value is determined on the below table. 
The base value is multiplied by 1-100 (1d100) to determine the value is eps.
The referee can adjust the base multiplier depending on the mythos of the game.
During times of economic recession the multiplier could be decreased to 1-10 (1d10).
During economic booms the multiplier could be increased to 1-1000 (kilo-die)

include::hardware:partial$treasure_values.adoc[]

[discrete]
=== Value Extremes
If a treasure is less that 4242 eps in value it does not count a TOY roll.
The persona will get the treasure, but earn another roll on the TOYs.
This caveat only applies to players on the start up TOYs.

Very valuable treasure should always have story attached to it. 
Most often there are entities pursuing valuable treasure that come along for the story.
A 100M gem stone could influence a campaign as much as a fusion pistol.

While negative treasure is not possible debt is. 
The treasure value table could represent a persona's starting debt.
Nothings with very low social standing could start the campaign with debt. 

== Treasure Types
Presently, treasure is nothing more than a value awaiting some form.
The treasure formats give the treasure some tangible, identifiable character.

include::hardware:partial$treasure_types.adoc[]

=== Substance 
The treasure consists of a substance that may or may not be obviously valuable.
Of all the treasure types substance is the heaviest and can be difficult to cart around.
An entirely random wate of 1-1000 (kilodie) kgs is assigned to the substance.
Extremely valuable substances may be a mine, factory, stored in a building. 

include::hardware:partial$treasure_substances.adoc[]

=== Crystal 
Crystal is a generic term imprecisely including gems, and other shiny baubles.
Players quickly associate shiny baubles with treasure. 
An entirely random wate of 1-1000 (kilodie) grams is assigned to the crystal.
Crystals are free range and are not included in jewelry. 

include::hardware:partial$treasure_stupid_rocks.adoc[]

=== Ornament 
Ornaments are trinkets designed to adorn the body of the wearer.
Valuable ornaments will almost certainly have a history, and perhaps even a name.
An ornament is valuable because of the way that it has been assembled.
Ransacking it for its primary elements may render it worthless.

Ornaments are created in a confusing multi-step process. 
Each ornament has a composition and a location.
The composition determines what treasures the ornament is composed of.
The location determines where the ornament lives. 
If the ornament's proper location is a finger it could be a ring.
If the ornament's location is a table it could be a centerpiece.

Generating an ornament may require many die rolls. 
In the end the system creates an outline of a piece of ornamental jewelry. 
Minute descriptive details are left to the artistic imagination of the ref.
Valuable jewelry will certainly have a history and story attached.

include::hardware:partial$treasure_ornament_components.adoc[]

include::hardware:partial$treasure_ornament_location.adoc[]

include::hardware:partial$treasure_ornament_application.adoc[]

=== Info
Treasure info is composed of info and gossip that does not affect the story. 
Info usually has some value to an external party like a family, corporation, or newspaper.
The treasure could be a love letter, corporate plan, or civic Intelligence.
One way to keep information treasure out of the expedition's story is to encrypt it.
The wate (kg) of the information is usually negligible.

include::hardware:partial$treasure_info_formats.adoc[]

=== Relic 
A relic is a piece of Junque applied arbitrary value for obtuse cultural reasons.
The object can be a luxury piece of random junk: an antique;
a souvenir (owned by some important someone);
or commodity shipment consisting of many units of random junk.
Jump to xref:hardware:junque.adoc[Junque,window=_blank] to generate a relic for the treasure value. 

:art: space_cards.png
:width: 300px
:snark: Space cards from the edge.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Three postcards from outer space. 
include::ROOT:partial$articulate.adoc[]


=== Cash 
Cash treasure is currency, coin, money etc. 
The cash can determined by the currency used in the milieu, or randomly generated.
The treasure could be a pile of cash, a credit chit, a some monetary recording tool.
The below table includes typical types of cash. 
For a walk on the random side the treasure value could be stored on an Info Type. 

:art: eps_on_table.png
:width: 250px   
:snark: Electrum pieces.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Several coins laying on an old wooden table.
include::ROOT:partial$articulate.adoc[]

include::hardware:partial$treasure_cash_types.adoc[]

=== Mixed 
Mixed treasures will have their values mixed amongst the basic treasure types found here.
For example a relic or an ornament could be a form of cash.
Cash or crystal could be information.
Just shakes things up a bit.

include::hardware:partial$treasure_combinations.adoc[]
