= All Those Rolls

:art: nuts_for_dice.png
:width: 350px
:snark: Nuts for dice.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: Several polyhedral dice, chewed pencil and mouse wearing headphones.
include::ROOT:partial$articulate.adoc[]

EXP is full of dice rolls.
The Roll Playing System is intentionally dice heavy. 
The Roll Playing System is for groups like to roll dice as much as telling the story.
Some of the dice rolls described here are stand-alone sections in the Roll Playing System.
For example, players can use sphincter rolls in either system to assist decisions.
Other dice rolls are part of more complex systems. 
For example, attack rolls require Defence Rating, attack tables, attributes and vocations to work.

Embrace the High Roll::
Rolling a higher number is almost always better for the persona.
Previous versions of EXP players would use their hope powers on either high or low rolls.
EXP is now all in for high rolls.

Clear the Tables::
Equations have replaced tables.
Some lookup tables still exist to avoid maths. 
In previous versions of EXP, there were many, many decision tables.

:art: all_those_rolls.svg
:width: 600px
:snark: Visual Review of Rolls in Roll System
:artist: HM - Drawio
:date: 2023
:license: CC BY-SA 4.0
:description: Mind map laying out all the different rolls in the game.
include::ROOT:partial$articulate.adoc[]

.*Inventory of Rolls*
* <<_target_rolls,Target Rolls>> (Fixed target)
* <<_challenge_rolls,Challenge Rolls>> (Dynamic target)
* <<_generative_rolls,Generative Rolls>> (No target)
* <<_yummy_rolls,Yummy Rolls>> (Tasty Treats)

== Target Rolls
Target rolls require the player to make a dice roll higher than a specific number.
If the player rolls higher or equal to the target number, she wins the roll. 
Most often, the target number is known to the player.
For example, for a player to win an attack roll, she needs to roll higher than the target's Defence Rating.

=== Attack Rolls
*Roll a 1d1000*

Attack rolls are made by the player when her persona is attempting to harm another persona.
The attack may be a punch, gunshot, sword swing, claw, bite, or energy blast.
The player needs to roll higher than, or equal to, the target's Defence Rating to win her attack roll.
If she wins the roll, she moves on to damaging the target.
The tactical combat rules are devoted to calculating all aspects of the attack roll.
For more info about rolling 1d1000 jump here xref:roll_playing_system:kilo_die_mechanic.adoc[Jump here.,window=_blank]

=== Task Rolls
*Roll a 1d100*

Task Rolls are made by the player when her persona is attempting to perform a task.
They should only be required for tasks that are important.
If the player is making a task roll to open a fridge door then you are doing this wrong. 

==== Doing Things
These tasks are vocation-related skills, abilities, tricks or gifts. 
The player needs to roll higher than, or equal to, the target roll to win her task roll.
The target roll gets higher the more complex the maneuver.
Jump to xref:roll_playing_system:CH14_Performance_Tables.adoc[Task Rolls,window=_blank]

==== Driving Things
Driving rolls are made by the player when her persona is attempting to perform a driving task.
A driving roll is a task roll dedicated to driving tasks.
For fun, these are often called maneuvering maneuvers 
The target roll gets higher the more complex the maneuver.
Jump to xref:roll_playing_system:CH17_Driving.adoc[Driving,window=_blank]

WARNING: Tasks are in flux 1d100 may be replaced by a 1d20 this is under dev.

=== Attribute Rolls
*Roll a 1d20*

Attribute rolls are used when a player's persona is being challenged in a particular way.
Attribute rolls function the same as task rolls, but there are *NO* bonuses added for abilities or skills.
The only time an attribute roll is modified is when a specific mutation or ability states that it modifies an attribute roll.
Attribute rolls have there own subsection, jump there xref:roll_playing_system:CH16_Special_Rolls_Attributes.adoc[Attribute Rolls]

==== Attribute Test
For example, a persona is trying to lift a heavy weight. 
The referee may call for a STR attribute roll. 
The weight is fixed and it is a pure test of strength.
Unlike an arm wrestle which would be a <<_challenge_rolls,Challenge Roll>>

==== Saving Throw
A saving roll involves the player trying to roll higher than a floating target to protect her persona from harm.
Saving rolls pit a specific attribute against an environmental or psionic nastiness.
The player makes saving rolls against attacks like poison, radiation, and mental attacks.
The persona's most appropriate attribute modifies the player's diced roll. 
For example, the persona's Constitution fights against poison and radiation attacks, while Mind fights against psionic attacks. 

The saving roll tries to beat the intensity of the attack. 
The referee generates the intensity randomly, and that is what makes saving rolls challenge rolls. 
For more about saving rolls jump here xref:roll_playing_system:CH16_Special_Rolls_Saves.adoc[Saving Rolls,window=_blank]

NOTE: *Saving Roll, Saving Throw, Save are synonymous*

==== Control Factor
The control factor roll is a challenge roll specific to the family of robots.
The player makes a control factor roll for her robot persona to keep her from falling back into her baked-in programming.
The challenge is between the robot's Intelligence and the depth of the violation of programming.
The player needs to roll high to stay in control of her robot persona.
Would you like to know more?
Jump to xref:robots:control_factor.adoc[Control Factor,window=_blank].

==== Damage System Shock
A damage system shock roll (DSS) is an anthro-specific target roll.
The player rolls dice to keep her persona conscious after a severe bolus of damage.
For knock out info about DSS jump to xref:anthros:generate_hit_points.adoc#_system_shock[Damage System Shock,window=_blank]

==== Recovery
A recovery roll (REC) is an anthro-specific target roll.
The player rolls dice to have her persona regain consciousness after failing a damage system shock roll.
For more info about DSS jump to xref:anthros:generate_hit_points.adoc#_recovery[Damage System Shock,window=_blank]

== Challenge Rolls
Challenge Rolls the player is trying to roll higher than a dynamic number to benefit their persona.
The main difference between a challenge roll and a target roll is that the number the player must roll higher than is generated on the spot.
The player must roll higher than another player rolling dice at the same time.
Most often, the other player is the referee.
The winner of the challenge roll is the player that rolls higher. 
Challenge rolls with attributes are covered with excoriating detail elsewhere, jump there xref:roll_playing_system:CH16_Special_Rolls_Attributes.adoc[Attribute Rolls]

=== Battling Attribute
An attribute roll involves the player using a specific attribute in a challenge.
Two personas arm wrestling would simultaneously roll dice to see who wins.
Each persona rolls separately adding their strength attribute to the 1d20 roll.
The higher roll wins the arm wrestle.
A tie indicated detente and ongoing arm wrestling.

=== Initiative
Initiative Rolls are specialized Dexterity challenges used to determine action order in tactical combat.
The higher the player's roll, the better the persona is positioned for that combat unit.
Initiative rolls are complex and have their own section under combat.
Jump there xref:combat:initiative.adoc[Initiative,window=_blank]

=== Ambush
Ambush Rolls are specialized Awareness challenges used to see how well the persona reacts to an ambush.
The higher the roll, the more likely the persona will be able to defend themselves in combat.
Ambush rules are detailed and have their own section under combat.
Jump there xref:combat:ambush.adoc[Ambush,window=_blank]

== Generative Rolls
Generative rolls have no target and no competitive aspect to them.
A generative roll yields a permanent result that is descriptive of an event or element.
Generative rolls do not predict immediate success or failure for the persona.
Most generative rolls indicate no benefit with a high or low roll.
Some generative rolls are important to the player's persona.
For example, a damage rolls and attribute scores rolls are important generative rolls. 

=== Attributes
When the player is creating her persona, each attribute is assigned a score. 
These rolls are important. 
They define health, Intelligence, species type, vocation type, and combat skills of the persona.
The persona does not succeed or fail based on these dice rolls.

=== Descriptive
Descriptors are the classic generative die roll.
They are typically rolled once and recorded on the persona record sheet.
Descriptions have no outcome for the persona other than generating a descriptive element.
For example, alien and robot appearances are random and descriptive. 
Some descriptors can impact the performance of the persona.
For example, the wate of a robot or alien impacts the damage they inflict.

=== List Result
The player will often find themselves generating something completely random from a list.
They are typically rolled once and recorded on the persona record sheet.
These tables infuse randomness and ensure the rarity of powerful things.
The most famous list rolls include mutation tables, skill tables, and the Technological Object Yields System (TOYs).
List rolls do not immediately put the persona at risk but can have a long-term impact.

=== Chance
These are weird tables limited to inatmo and exatmo vehicle generation.
They are tables where the player makes percent chance checks to see if peripherals or defences exist.
Technically it is a generative roll, but players always want the peripherals.
The chance table represents a percent chance, and a low roll indicates success. 
Chance tables are the only rolls left in EXP where players want to roll low for success.
These chance tables change in future versions of EXP to embrace the high roll.

=== Damage
Damage rolls are generative rolls that indirectly benefit the persona when the player rolls high.

== Checks
Critical checks are not dice rolls at all.
A Critical check indicates a special event occurs within a normal roll.
Humans attribute special value to numbers that have no statistical significance.
For instance, rolling 20 on a 1d20 is as likely as rolling an 18, but it is special to us.
To honour humanity's superstitious traits we have critical checks.
Crits are so import they have their own section.
Jump there xref:roll_playing_system:CH16_Special_Rolls_Critical.adoc[Critical Checks,window=_blank].

NOTE: *Critical check, roll, hit result are synonymous*

=== 1d1000
Attack rolls have several checks. 
If the player rolls a __natural__ 990 or higher the attack roll is an automatic hit, and inflicts 1d4 times the damage dice roll.
If the player rolls a __natural__ 42 the referee can consider a weapon malfunction.

=== 1d100
Task rolls have a check value. 
If the player rolls a __natural__ 100 she rolls another 1d2100 and adds it to the task roll.
This allows the persona to achieve miraculous 

=== 1d20
Attribute rolls have a check value. 
If the player rolls a __natural__ 20 she rolls another 1d20 and adds it to her attribute roll.

== Sphincter Roll
Sphincter rolls are the last line of decision-making when players cannot agree.
The sphincter roll is a luck challenge roll between two players. 
The player usually competes with the referee when making a sphincter roll.
Sphincter rolls fill those gaps in the referee's milieu.
Sphincter rolls also assist players in making decisions when a decision is elusive.
If the player rolls higher than the referee, the decision falls in favour of the player.
For more details about these rolls jump to xref:roll_playing_system:CH16_Special_Rolls_Asshole.adoc[Sphincter Dice,window=_blank]

== Yummy Rolls
Jelly, sushi and bread rolls are yummy. 
EXP does not recommend jelly rolls when playing with hex mats and minis. 
For more information about these tasty treats jump to https://en.wikipedia.org/wiki/Swiss_roll[Jelly Rolls,window=_blank].
