= Attribute Rolls

[quote]
____
*For juggling books or juggling chainsaws.*
____

:art: elephant_juggling.png
:width: 250px
:snark: What could go wrong?
:artist: Andrew Brechin
:date: 1990
:license: CC BY-SA 4.0
:description: A four-armed humanoid elephant juggling a chainsaw, pistol, cat and satellite phone. 
include::ROOT:partial$articulate.adoc[]

Attribute rolls are die rolls that test persona attributes.
Acts of Dexterity, Strength or willpower are examples of attribute rolls.
An attribute roll pits a specific attribute against a particular task.
Catching a valuable egg would be a dexterity (DEX) roll.
Listening for a malfunctioning engine noise would be an awareness (AWE) roll.

== Quick Look
Make a quick roll and skip the details.
Referee and players decide appropriate attribute to test.

[discrete]
=== Attribute Roll
.1d20 + Attribute + Level
****
The roll must be greater that the target below.
****

[discrete]
=== Target
The attribute roll above must meet or beat this number.
The referee and players decide the difficulty.
The referee may have a pre determined difficulty and target roll. 

include::uncombat:partial$task_difficulty.adoc[]

== Attribute Rolls
Attribute rolls are quick dice rolls to determine success in non-vocational maneuvers.
Attribute rolls do not replace attack rolls, task rolls or driving rolls.
Attack rolls are unique to the tactical combat rules and represent a complex balance of combat skills and Defence Rating.
Task Rolls are for the maneuvers of specific vocations and represent a balance of difficulty and skills.
Driving Rolls involves both the vehicle handling class and Dexterity rolls.

=== When To Use
Attribute rolls should only be employed when a challenging situation arises.
A persona trying to open a door should not have to make an attribute roll.
A persona trying to open a complicated door while under fire in combat may require an attribute roll.
A persona trying to unlock her apartment door should not require an attribute roll.
A persona trying to unlock her front door after drinking a https://en.wikipedia.org/wiki/Zaphod_Beeblebrox#Pan-Galactic_Gargle_Blaster[PGGB] may require an attribute roll.
An attribute roll should make the evening's role-playing more fun.

As with all rolls, attribute rolls should not decide the course of a campaign.
Nor should an attribute roll be used to solve a referee's puzzle.

.*Attribute Roll Checklist*
. <<_attribute_type,Attribute Type>>
. <<_target_value,Target Value>>
. <<_make_the_roll,Make the Roll>>

=== Attribute Type
The referee and players decide which attribute is most relevant for the roll.

include::uncombat:partial$attribute_roll_type.adoc[]

=== Target Value
Not all attribute rolls are created equal. 
Some are much harder than others.
Attribute rolls should be quick and to the point.
When assigning an attribute target value, the referee determines the difficulty of the task.
The players and referee decide on a qualitative description of how difficult the task should be.
The less likely it seems that the persona could be successful, the greater the difficulty.
For example, kicking open a standard residential door would be an easy or normal difficulty task.
Kicking open a commercial door would be a hard or tough difficulty task.
Kicking open a fortified combat door would be an impossible or bizarre difficulty task.

Each difficulty descriptor has a random or static target roll associated with it.
The numeric portion of the difficulty becomes the target value for the attribute roll.
For a normal difficulty attribute roll, the referee can roll 1d20 for a random target value or use the static 18.
The referee can use the random or static target value. 
Players prefer the random values for very difficult tasks.
The players and referee should use whichever is faster and more fun.

include::uncombat:partial$task_difficulty.adoc[]

The majority of the time, the player will be rolling against a normal difficulty.
The bizarre difficulty task is for impossible tasks that the player still wants to try.

=== Make the Roll
The player must roll equal to or higher than the target value.
The player rolls a 1d20 and adds her EXPS Level and attribute score to the roll.

=== Attribute Roll 
.Attribute Roll = 1d20 + Attribute + EXPS Level
****
Dexterity roll = 11 (1d20) + 11 (DEX score) + 3 (3rd level Nomad) = 25 +
Strength roll = 4 (1d20) + 9 (STR score) + 5 (5th level Veterinarian) = 18
****

== Attribute Challenge
Attribute rolls and attribute challenges are slightly different.
An attribute challenge pits two personas against each other in a contest of 1d20 rolls and attributes.
In an attribute roll the player makes an attribute roll trying to beat a specific target that is related to difficulty.
In an attribute challenge the player is simultaneously rolling against against another player.
The other player is typically the referee but could be another player from the expedition.
The higher roll wins.
If there is a tie a dramatic period of detente occurs and and attribute challenge is made.

Two personas arm wrestling is a strength challenge.
Two personas playing hat snatch is a dexterity challenge.
A staring contest is a mind challenge.

=== Challenge Examples
The referee decides which attribute is most relevant for the competition.
The player adds the relevant attribute to her chosen attribute to her 1d20.
There are many examples of competition types above.

include::uncombat:partial$attribute_challenge_examples.adoc[]

== Saving Rolls
The saving roll is a unique attribute roll that has its own section due to legacy and importance. 
Most attribute rolls are not life and death for the persona.
However, saving rolls are often life and death for the persona.
Jump to xref:uncombat:saving_rolls.adoc[Saving Rolls,window=_blank] for the deets.

== Combining Forces
Personas can get together and combine their attributes to complete a task.
An example would be a bunch of personas lifting a rock off of an expedition member.
If there are enough personas, the referee will allow the lift to be successful without any rolls.
If there are extenuating circumstances, the referee may require the personas to combine their forces.
For example, a tug of war between two expeditions would be a combined attribute competition.
The success states for a combined attribute roll a combined attribute competition remains unchanged.

The difference is in the synergy of numbers.
In a combined attribute roll, every player gets to make a roll. 
If any of the players are successful, the entire team is successful.
For example, three personas are trying to push over a flag pole.
Each player gets an attribute roll against the difficulty of this task.
A win by any of the players means the flag pole has succumbed to vandalism.

In a combined attribute competition, each player gets to make a roll.
Success depends on the number of successes made by each team.
So if two groups of ursidae are having a tug of war, every player gets to roll.
The referee matches the players by their Strengths. 
Whichever team has the most successes wins the tug of war. 
A tie means that the tug of war is continuing, excitement increases, and the pull-a-thon continues.
In general, the stronger team will win, but miracles of probability can still occur.

== Resolving Ties
The most common way to resolve a tie is to declare detente, talk some drama and roll again.
In those situations where detente is not acceptable the Decimal System can be used.
The decimal system is used in resolving initiative rolls.

=== Decimal System

Resolving ties has each player rolling a 1d10.
The 1d10 roll indicates the next decimal place of their roll.
If both player's total roll were 11, each player would roll a 1d10, adding a decimal place to their result.
So the player that rolled 11.5 would win the competition versus a player that rolled 11.4.
If there were another tie, the players would add another decimal place. 
These decimal place challenges can be pretty exciting.

==  Python Data
A little python program made thousands of simulated attribute rolls.
The goal was to determine what intensity gave an average attribute a 60% chance of success.

.*Average Attribute vs Ascending difficulty*
* attribute 10 versus difficulty 18 = 60% chance success
* attribute 10 versus difficulty 19 = 55% chance success
* attribute 10 versus difficulty 24 = 29% chance success
* attribute 10 versus difficulty 32 = 0% chance success

.*Ascending Attribute vs Average Difficulty*
* attribute 10 versus difficulty 18 = 60% chance success
* attribute 12 versus difficulty 18 = 70% chance success
* attribute 14 versus difficulty 18 = 80% chance success
* attribute 16 versus difficulty 18 = 90% chance success
* attribute 18 versus difficulty 18 = 99% chance success

.*High Attribute vs High Difficulty*
* attribute 18 versus difficulty 32 = 30% chance success
