= Critical Checks

[quote]
____
*604 and 1000 and 042 all have the same chance of happening.*
____

Mundane humans love to see patterns where there are none. 
Players attribute unique value to die rolls for fun and persona profit.
The concept of the critical dice roll is too much fun to ignore. 
Critical checks are not specific die rolls like an attack roll or a task roll.
A critical check is observational. 
When a player generates an extreme roll on her dice, this warrants a critical check.
The most famous critical check is the critical hit.
In EXP, a critical hit is a roll of 990 or higher on 1d1000.

:art: critical_hit_arrow_split.png
:width: 250px
:snark: Robin hit.
:artist: Warren Oddsson
:date: 1990
:license: CC BY-SA 4.0
:description: An arrow splitting another arrow inside a bullseye. 
include::ROOT:partial$articulate.adoc[]

When a player rolls the maximum or minimum value of dice, exciting things can happen.
Rolling a one or a six on a d6 is not as exciting as rolling a 1 or 100 on a d100.
Critical checks can happen in attack rolls, attribute rolls, task rolls, driving rolls, etc.

Any amateur statistician will point out an impressive 998 is no more likely than an obscure 452. 
However, an air of urgency always accompanies these extreme rolls.
We all react hysterically to a roll kilodie of 000, but it is no more likely than a roll of 604.

Critical checks spice up the game by adding that rare dose of the unexpected.
A frail little alien may manage to damage that arrogant invader wearing powered armour.
A landlubber mechanic may manage to fix a damaged exatmo drive during space combat.

A critical check cannot bypass essential plot points.
Critical checks exist to revitalize, not to destroy, a campaign.

.*Parameters for a critical check*
* must be a natural roll 
* must be on a die roll of substance
* must be on a roll of relevance
** attack roll
** task roll
** attribute roll

== Natural Roll
Critical check must arise from a natural roll.
No modifiers can cause a player generate a critical check.
If the persona's bonuses add up to 1000, this does not count for a critical check.
Only a natural 990 or higher on the kilodie roll would make a critical check.

== Dice of Substance
Critical checks should be limited to die rolls where they are unusual and reasonably infrequent.
For example, critical results on 1d4 rolls would occur 25% of the time.

NOTE: *Critical check, roll, hit result are synonymous*

=== 1d1000
The kilodie only has critical checks when it is being rolled as an attack roll.
A 1d1000, also called a kilo-die, has two critical checks.
There one critical range and one critical value.
The critical range is 990 to 000 (1000).
The critical value is 042.
42 is a nod to https://en.wikipedia.org/wiki/Douglas_Adams[Mr. Adams,windows=_blank]. 

.Attack Roll Critical Checks
* a __natural__ 990, or higher, is a critical hit
** the player's persona automatically hits
** 990-999 has a damage multiplier of 1d4
** 000 (1000) has a damage multiplier of 4 
* a __natural__ 42 is critical check
** the referee may consider a weapon malfunction
* there are no critical fails with attack rolls

NOTE: *Referees do not use critical hit damage adjusters against player personas.*

=== 1d100
The decidie only has critical checks when making a task roll.
A 1d100, also called a deci-die, has three critical checks.
There are two critical values and one critical range.
The critical range is 95-00 (100), and the critical checks are 01 and 42.

.Task Roll Critical Checks
* a __natural__ 95, or higher, is a critical success
** the player rolls another 1d100 and adds it to the Task Roll.
** there is no automatic success
* a __natural__ 42 is a critical chaos injection
** if the roll is a fail it is weird bad
** if the roll is a success it is weird good
* a __natural__ 01 must fail.
** the persona gets EXPS for a critical fail

=== 1d20
A twenty sider only has critical checks when making attribute rolls. 
A 1d20 has 1 critical check.
The critical check is 20. 

.Attribute Roll Critical Check
* a __natural__ 20 is a critical success
** the player rolls another 1d20 and adds it to her attribute roll
** there is no automatic success

== Otto Checks
Otto checks are when a player rolls the dice for a task roll even if the outcome is predetermined.
Otto checks are optional, and no one has any idea how the name came to be.
If the player rolls a 42 on the deci-die, she can redeem her persona with a dramatic description.

If the player needs to roll 156 on the 1d100, she may feel the roll is futile.
The player should always roll under these circumstances because she may roll 00 on 1d100 and enjoy a critical success. 
The otto check gives the player another chance to win the task roll if she rolls 42.
A decent description of why her persona actually did succeed will allow her to win the task roll.

For example, a first-level biologist wants to start a fire underwater. 
She has bonuses of +20, but the Target Roll is 140.
The target for the task roll exceeds her chance of success.
If the player rolls 42 and tells a good story, she may find her persona is successful.

There is a corollary otto check for failure as well.
The referee may ask the player to make a task roll under circumstances where she cannot fail.

If a player needs to roll higher than -6 on the 1d100, she may want to skip making the task roll. 
The referee may ask players to make a task roll regardless.
Under these circumstances, the player should not fail even if she rolls 01 on the deci-die.
However, with otto checks, if she rolls 42, she must tell a good story of why she succeeded.

:art: critical_hit_head_bot.png
:width: 250px
:snark: Critically critical hit.
:artist: Unknown.
:date: 1990
:license: CC BY-SA 4.0
:description: Drawing of a robot taking a critical hit to the head. 

include::ROOT:partial$articulate.adoc[]

== No Checks Here
Critical Checks are limited as described above. 

.*Nothing To Check Here*
* Initiative Rolls
* Ambush Rolls
* Sphincter Rolls
* Control Factor Rolls
* Damage Rolls
* Attributes Rolls
* Any generative table roll