= Encumbrance

Encumbrance represents the burden of equipment that the persona has elected to carry.
Everything that the persona wears or carries contributes to encumbrance.
Encumbrance includes clothing, armour (unless worn), ammunition, weapons, food, and anything else with a wate.
This section does not cover the philosophical elements of encumbrance,
The age-old questions of which is more difficult to carry, 2 kg of oxygen, or 2 kg of lead?

:art: encumbrance_desert_pack.png
:width: 250px
:snark: All my stuff.
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Sweaty humanoid carrying overloaded pack in the desert.
include::ROOT:partial$articulate.adoc[]

Encumbrance is a roll playing tool that affords some faux realism to carrying and lifting stuff.
A persona shuffling through the underbrush with 3 tonnes of equipment would be unrealistic.
Equally, players should not suffer and exacting per milligram calculations of their equipment list.
Encumbrance is a check against carrying the kitchen sink along with the house. 
The referee can check in on encumbrance once in a while to keep things in check.

Occasionally encumbrance rule can be the center of a scenario or puzzle.
If a single persona cannot lift the essential artifact, which persona can?
Or how much loot can be carried out before the demolition clock runs down?

:art: encumbrance_hurdle.png
:width: 250px
:snark: Free vs Encumbered.
:artist: Andrew Brechin
:date: 1991
:license: CC BY-SA 4.0
:description: Lightly dressed humanoid antelope out maneuvering heavily encumbered humanoid panda. 
include::ROOT:partial$articulate.adoc[]

== Wate Allowance
The persona's Strength (STR) is what determines how much they can carry.
Each STR has its own assigned Wate Allowance. 
Each persona gets assigned a Wate Allowance when being created. 
The stronger the persona, the more they can carry and lift.

.*Did you forget to record Wate Allowance?*
* xref:anthros:wate_allowance.adoc[Anthro Wate Allowance, window=_blank, rel="noopener noreferrer"]
* xref:robots:wate_allowance.adoc[Robot Wate Allowance, window=_blank, rel="noopener noreferrer"]
* xref:aliens:wate_allowance.adoc[Alien Wate Allowance, window=_blank, rel="noopener noreferrer"]

=== Size Adjustment
Bigger personas can lift more stuff. 
The player multiplies her persona's  Wate Allowance by the WA Adjustment.

include::uncombat:partial$wa_and_size.adoc[]

== Encumbrance Categories
Wate Allowance is a solitary number.
For many playing tables, just using wate allowance works well enough.
If the players prefer something more granular, EXP has a complicated and byzantine encumbrance system.
The Roll Playing System divides the WA into qualitative descriptors that affect performance.
The persona's strength (STR) is what determines how much a persona can carry.
Encumbrance levels show the impact of carrying too much stuff.

.*Encumbrance Categories*
. Free
. Light
. Normal
. Burdened
. Lift Only
. Max Lift

=== Free
Free from all encumbrances.
This persona is carrying nothing and may be wearing even less.
Restrictive civilian clothing may jeopardize a persona's Free encumbrance level.
Carrying anything removes a persona from the Free encumbrance category.
A persona with a WA of 16 kg must carry 0 kg of stuff to be free of enbcumbrance.
Wildlife (flora and Fauna) are always free of encumbrance.

==== Calculate Free Category
.wate = 0 kg
****
Persona can carry nothing, and clothing must be light and airy. Think mundane terran sprinter.
****

=== Light Encumbrance
This persona is carrying very little equipment.
A persona has light encumbrance if she is carrying less than 1/4 her wate allowance (WA).
A persona with a WA of 16 kg could carry up to 4 kg and have light encumbrance.

==== Calculate Light Encumbrance
.wate < Wate Allowance / 4 
****
20 kg WA. The persona to carry up to 5 kg of stuff and have light encumbrance.
****

=== Normal Encumbrance
Normal is the normal encumbered state for a personas.
A persona has normal encumbrance if she is carrying less than 1 and a 1/2 times her wate allowance (WA).
Normal encumbrance is the amount of equipment a persona can carry and function normally.
Carrying any more wate will have a detrimental effect on the persona's function.
A persona with a WA of 16 kg could carry up to 24 kg and have light encumbrance.

==== Calculate Normal Encumbrance
.wate < Wate Allowance * 1.5
****
20 kg WA. The persona to carry up to 30 kg of stuff and not suffer encumbrance penalties (normal encumbrance).
****

=== Burdened Encumbrance
This persona is carrying too much stuff.
A burdened persona is carrying between 1 and 1/2 times and 2 and 1/2 times her WA.
They are starting to feel the impact of the wate on their ability to function.
A persona with a WA of 16 kg would have burdened uncumbrance when carrying between 24 and 40 kg of stuff.

==== Calculate Burdened Encumbrance
.wate < Wate Allowance * 2.5
****
20 kg WA. The persona can carry up to 50 kg of stuff and still move with burdened encumbrance.
****

=== Lift Only
This persona has reached the limit of what they can carry.
The persona can only lift a load greater than 2 and 1/2 times the persona's wate allowance.
The persona can do nothing other than lift that wate.
The wate could be a single object or a rucksack full of junque.
A persona with a WA of 16 kg can only lift an object, or rucksack, 40 kg or over.

==== Calculate Lift Only
.wate > Wate Allowance * 2.5
****
20 kg WA. The persona cannot move with, but can lift, 50 kg of stuff.
****

=== Max Lift
This is the absolute max that a persona can move based on their wate allowance.
A persona cannot lift or move anything beyond max lift without using levers or tools.
A persona with a WA of 16 kg cannot lift, or move, any wate 48 kg or over.

==== Calculate Max Lift
.wate > Wate Allowance * 3
****
20 kg WA. The persona cannot budge anything  >60 kg.
****


== Encumbrance Effects
The encumbrance categories are neat and interesting, but how they affect the persona is what matters.

=== Tasks
Carrying too much equipment has a detrimental effect on the persona's ability to perform tasks.
The higher the encumbrance level, the more difficult tasks become.
Encumbrance is not just about wate. 
It also includes restrictiveness and entanglements impairing performance.
The persona needs to set the stuff down to avoid the task roll penalty.
An easy (12) task would increase the difficulty 24 when encumbered.

When encumbrance rules are due to high gravity environments, personas cannot escape the penalties.

include::uncombat:partial$encumbrance_and_tasks.adoc[]

=== Movement
Encumbrance has its most significant effect on combat movement.
The greater the load on the persona, the more difficult it is to move.
The persona cannot use specialized movement rates like bolting and running when encumbered.
Non-combat movement is only qualitative and is not affected directly by encumbrance.

include::combat:partial$movement_and_encumbrance.adoc[]

=== Initiative
The less encumbered persona will get to act first.
A persona loaded down with equipment will have a hampered response time.
A persona with burdened encumbrance that rolled 18 on her initiative roll would have it reduced to 14.

include::uncombat:partial$encumbrance_and_initiative.adoc[]

=== Driving
Personas must be free or unencumbered to drive or pilot any vehicle.
This requirement includes vehicles and spacecraft.
Driving rolls will be impaired the same as task rolls by encumbrance levels.

=== Attribute Rolls
Some attribute rolls are affected by encumbrance levels.
The higher the encumbrance level, the more difficult the attribute roll. 
Encumbrance impacts actions like getting up, balancing, jumping, and climbing.
Attribute rolls for DEX, STR can occasionally be affected by encumbrance levels.
Actions like doing math, smiling, psionic attacks are less impacted by encumbrance.
Attribute rolls for  AWE, CHA, INT and MND are less affected by encumbrance levels.

=== No Wait WA Table
If you do not want to do arithmetic, this table is available for quick determinations of encumbrance levels.
If a large or gigantic persona has exceeded the table's values, then arithmetic is still required.
This table will also fall short for robots. 


include::uncombat:partial$encumbrance_calculated.adoc[]
