= Experience

[quote]
_____
*Experience is bad experiences preventing future bad experiences.*
_____

Personas become more powerful by completing missions, surviving combat and practicing their vocation.
The concept of an experience point is as old as role-playing games. 
The persona is awarded experience points (EXPS) for doing things correctly.
There are some occasions where failure can lead to earning experience points.
As the experience points accumulate, the persona increases in levels.
These levels represent improvements in combat, skills and attribute challenges. 

:art: research_team_biovet.png
:width: 250px
:snark: Learning by doing.
:artist: Kelly Freas
:date: 1957
:license: CC BY-SA 4.0
:description: Two humans working together on delicate project.
include::ROOT:partial$articulate.adoc[]

The amount of EXPS required to increase levels varies from vocation to vocation.
Anthros put their experience towards improving their vocations. 
Robots and aliens also can acquire EXPS and increase their EXPS Levels.

Experience points are the personas reward for successes.
There is no reason why failure should be any less educational.
Granting EXPS for failure is up to the referee.
There is no system for failure experience in EXP.

== Player Experience 
As a player does more and more role-playing, her skill level at role-playing improves.
No longer the incompetent neophyte she once was, an experienced player won't even consider actions that might have sorely tempted her previous personas.
Her current persona will exhibit an increased level of consciousness in even the simplest of her actions.
There is nothing wrong with this sixth sense that the personas of experienced players seem to have.
There is nothing that a referee can or should do to make a player forget her hard-won skills.

The player must be careful lest her persona seems to possess information she could not possibly know.
A brand new persona should not display in-depth knowledge of a ruin mapped by the player's three previous personas.
However, it would be perfectly acceptable if the persona, on a hunch, acted in a very cautious manner while scrounging through those same ruins.

The persona has no concept of gaining these points for activities. 
The persona is just living their life, and likely won't even notice that they are better and finding shelter or fixing robots. 

.*Sources of EXPS*
* Combat
* Identifying artifacts
* Successful maneuvers
* Role-playing fun

== Experience Points 
As the expedition progresses through each scenario, the referee keeps track of earned EXPS.
Throughout an adventure, the persona can earn experience points for various actions.

* 100 EXPS for using her vocation skills
* 200 EXPS for identifying an artifact
* 175 EXPS for combat
* 1000 EXPS for good role-playing.

The player adds these experience point rewards to her persona's EXPS total.
Historically experience point totals are updated at the end of the scenario or evening of play.
Real-time EXPS compilation is not healthy for the flow of role-playing.
Computation devices may make this possible in the nearer and nearer future.

Each persona has a lookup table that converts her experience point total to a convenient experience level. 
Every persona, regardless of family or vocation, has an experience point table.
Aliens and robots also have experience point tables.

A spie who has collected 6243 EXPS is a third-level spie.
A veterinarian with 18402 EXPS is a fourth-level vet.
Different vocations progress in their vocation skills at different rates.
A biologist going from 4th to 5th level needs to earn 10000 EXPS, while a knite crossing the same boundary must achieve 24000 EXPS.
These differences reflect how the difficulty of the vocation.

The experience level affects how well the persona performs in combat, completes tasks, and life in general.
Every roll that a player makes is adjusted in some fashion by her persona's EXPS Level.
Task rolls, attack rolls, saving rolls, attribute rolls all reflect a bit of EXPS Level.

The experience point is a universal value like the hit point. 
One EXPS is one EXPS is one EXPS.

=== Anthro
Every anthro pursues a vocation.
The anthro experience level is the same as the anthro's vocation level.
Even the venerable nothing can earn EXPS and become a better nothing.

=== Robot 
EXPS is the same for robots and they can improve their ability to win control factor rolls and increase their free will.
Robots are uniquely positioned to collect EXPS for taking damage.

=== Alien 
Aliens gain experience by succeeding at their natural abilities. 
The higher the EXPS level of the alien, the better they are at being an alien.
An alien that is following a vocation must choose between her vocation or being primal.
An alien with a vocation functions the same as any other persona in that vocation.

Aliens can range from unintelligent planetary denizens to important dignitaries of intergalactic empires.

== Sources

.*Sources of EXPS*
* Combat
* Tasks
* Artifacts
* Role-playing fun

=== Combat 
The best way to gain combat experience is to fight.
Personas gain EXPS for vanquishing opponents in heroic battles.
Vanquishing includes knocking unconscious, paralyzing, stunning, killing, or otherwise rendering inoperative and non-threatening.

:art: combat_experience.png
:width: 250px
:snark: Pwned.
:artist: Michael Jackson
:date: 1991
:license: CC BY-SA 4.0
:description: Smug police officer with shotgun standing over subdued humanoid feline.

include::ROOT:partial$articulate.adoc[]

Simply engaging a target in lethal combat does not guarantee the earning of EXPS.
The opponent must have posed a threat to the expedition.
Slaughtering the kittens in the local pet store would not result in EXPS for combat.
An anti-knite may get some vocation experience for doing this, but no combat EXPS.
Players cannot farm experience for their personas by engaging in frequent one-sided battles. 
It is possible that farming for experience may weaken combat skills leading to  EXPS penalties.

==== Calculating Combat EXPS
Every referee persona created has a combat ratio (CR).
The combat ratios calculations are in their respective referee persona sections.
The higher the combat ratio, the more dangerous the persona to the expedition.
Combat ratio loosely represents the number of first-level personas needed for a fair fight.
A weak but aggressive alien has a combat ratio of 1/2.
This combat ratio indicates two of these aliens versus one first-level persona is a balanced fight.
A powerful combot has a combat ratio of 200.
This combat ratio indicates this one combot would need to fight an army of 200 personas for a fair fight.

==== Combat Ratio to EXPS
.EXPS = (100 + HPS Total) * Combat Ratio
****
30 HPS and CR of 5 = (100 +30) * 5 = 130 *5 = 650 EXPS. +
40 HPS and CR of 14 = (100 +40) * 14 = 140 * 14 = 1960 EXPS. +
350 HPS and CR of 29 = (100 + 350) * 29 = 450 * 29 = 13050 EXPS.
****

The referee may wish to adjust combat EXPS based on the nature of the difficulty of the battle.
Combat that is riskier to the expedition earns more EXPS. 
Combat that faced little risk to the expedition earns less EXPS.

include::uncombat:partial$exps_combat_adjustments.adoc[]

==== Combat EXPS and Vocation
Non-combat vocations do not glean as much practical knowledge from the combat.
The referee can choose to modify combat EXPS by vocation. 
A veterinarian will learn something about healing from combat but not as much as healing the wounded.
For example, a mechanic whose share of combat experience was 400 EXPS would earn only 20% or 80 EXPS

include::uncombat:partial$exps_combat.adoc[]


=== Tasks 
The most straightforward and honest way to earn EXPS is to practise one's vocation.
Whenever a player wins a new task roll, her persona gets EXPS.
Biologists get EXPS for identifying aliens, nomads get EXPS for finding shelter, and nothings get EXPS for collecting cash.

A persona cannot collect experience for repetitive tasks. 
So a nomad does not get EXPS for starting 7 campfires in the week.
But starting a campfire in a new biome could earn EXPS. 

NOTE: Some vocations have a bespoke EXPS value per DD. 

The amount of experience awarded depends on the difficulty of the Task Roll.
The persona earns 42 EXPS per DD of the maneuver.

==== EXPS for Task Rolls
.42 EXPS per Difficulty
****
A persona succeeding at a trivial task (12DD) would earn 504 EXPS.
****

=== Money
Personas do not gain EXPS for acquiring wealth.
Aliens and robots do not earn EXPS for gaining money, but they may gain EXPS for the process.
For example, there may be an EXPS award for robbing a bank. Stealing 1M or 1K is no different.

There is one exception to this rule. 
The nothing vocation can earn experience for earning money.

=== Practice
The referee may allow for personas to improve themselves with a period of intentional practice.
Personas cannot earn EXPS for practice.
Personas cannot improve attributes from practice.
If things line up in the story, a persona may be able to improve their skills.

During a prolonged persona downtime, the referee may allow a persona to study and practice a particular skill.
The downtime could be a long space voyage or a savage winter.
The most a persona could add is one new skill level.
For example, a biologist left alone in a zoo for two months may add skill in zoo keeping.
However, a mercenary with a part-time job counting money would learn nothing.

Acquiring new skills should not be abused by the players or the referee.
Personas automatically earn new skills with new EXPS Levels.
Earning new skills the old-fashioned way maintains game balance and is more fun.

=== Artifacts
Personas in EXP will be encountering unknown technological devices of great mystery regularly.
When these items are unidentified, they are artifacts.
Once identified, they become toys or equipment.
Turning an artifact into a toy is an experience point source.

The most fun way to identify an artifact is to role-play through a prepared story from the referee.
For example, the expedition finds a slippery white cylinder with no visible markings. 
The mechanic tries plugging it into a slot in their exatmo drives.
The mercenary waves it at enemies during combat.
The veterinarian rubs it on an infected wound.
The nothing attempts to eat it with curry.
Eventually, the slippery white cylinder hatches and its predator parent comes looking for the baby.

If there is no time for role-playing shenanigans artifact identification can be turned into a dice laden flow chart mini-game at xref:uncombat:artifact_id.adoc[Artifact ID,window=_blank].

Every artifact has an EXPS Value listed with it.
Hopefully, more powerful and exciting TOYs have higher EXPS values.
EXPS awards are only granted once for an artifact.
Artifacts purchased by money cannot earn experience.
For example, an expedition earns EXPS for a fusion rifle they found in the wilds.
They would not earn EXPS for a fusion rifle purchased at Energy Weapons R Us.
Nor would they earn EXPS for finding a second fusion rifle in the wilds. 

Some artifacts have enormous EXPS values.
The personas should acquire such artifacts through more complicated puzzles over many gaming sessions. 

=== Role-Playing 
Role-playing is the single most entertaining aspect of playing an RPG.
The clue to this is that the words role and playing are in its title.
Role-playing informs the mood, strengthens the thread of reality, and provides essential comic relief.
Persona should be rewarded best by the role-playing choices of her player.
EXPS for role-playing incentivizes role-playing for even the shyest player. 

:art: rocketdog_jedi.png
:width: 250px
:snark: Stylin.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Canine humanoid sporting rocket pack, pistol and energy sword.
include::ROOT:partial$articulate.adoc[]

[quote]
____
"I hastily rummage through the filing cabinet with my stubby claw paws. 
Ears up and sniffing for any sign of sentries."
____

The above is more fun than "I search the room."
Such a description should earn her an EXPS award.

[quote]
____
"Thagron trumpets a thundering charge with her imposing bulk." The player raises her arms, miming her death-dealing antlers. 
____

The above  is more fun than "I attack."
Such a description should earn her an EXPS award.

include::uncombat:partial$exps_role_playing.adoc[]

Properly assigning role-playing EXPS by the referee is an epic refereeing challenge.
The ref must be aware of the player's choices.
If the player is making an effort, the referee should throw some EXPS her way.
Enthusiastic descriptions may not always be clear ones.
The referee and players should be comfortable with asking for more info.
Role-playing is a collective experience.

== Sharing
Role-playing is a shared experience.
How should the referee share experience points between players?
Every referee will develop their method for keeping track of EXPS during a session.

TIP: Rules maintain game balance and assist creativity. +
*Do not let rules get in the way of the story or the fun.*

Some referees will have the EXPS values of their game missions pre-determined right down to each persona.
Others will review the game night and bring the results to the next session.
Other referees will wing it and trust their gut.

Personas own their task roll experience and do not share it.
Personas own their role-playing experience and do not share it
Personas share experience from shared artifact identification.
Personas share experience from teamwork, research teams and projects.
Personas share experience from combat. 

=== Shares

The fairest way to divide experience between personas is by using shares.
Every persona involved in combat gets a share of the experience.
Most groups will divide experience amongst all personas involved.
As expected, EXP also has an unnecessarily complicated way of sharing experience.
This experience-sharing method is entirely optional, of course.

The referee divides the total experience for combat by a number greater than the number of personas.

If a nothing persona was critical in a battle, the referee could allot her an extra share.
This same method works for research teams or team artifact identification.

==== Example

Consider an expedition with five personas.
Three of the personas do battle with sentry droids while the other two reprogram a security system.
The mercenary is smashing robots like a jackhammer. 
The spie and the nomad are less effective, but are damaged during combat.
The mechanic and nothing are doing the security bypass, and avoid combat.
The nothing persona is mostly likely commenting on the mainframe's aesthetics, while the mechanic is programming.

The expedition is successful in both combat and security bypass.
The mercenary, nomad and spie destroyed the sentry droids.
The mechanic has bypassed the security system.
Total EXPS for combat is 4000 EXPS.
Total EXPS for security bypass is 6000 EXPS.

The combat has three participants, but the ref divides the experience four ways.
The reprogramming task has two participants, but the referee divides the experience three ways.
Each combat share is worth 1000 EXPS, and each task share is worth 2000 EXPS.
The mercenary gets two shares of combat experience, and the spie and nomad each get one share.
The mechanic gets two shares from the reprogramming task experience, and the nothing persona gets one share. 
The mechanic gets 4000 EXPS, the mercenary gets 2000 EXPS, the nothing persona gets 2000 EXPS, the nomad gets 1000 EXPS, and the spie gets 1000 EXPS.
The player of the spie persona is probably wondering if they should have helped reprogram the sentry.

Easy peasy. 
