= Saving Rolls

[quote]
____
*Automated internal defences against external attacks.*
____

== Quick Look
Make a quick roll and skip the details.
Referee and players decide appropriate attribute to test.

[discrete]
=== Saving Roll
.1d20 + Attribute + Level
****
CON vs toxins. MND vs psionics.
****

[discrete]
=== Intensity
The attribute roll above must meet or beat this number.
A typical poison, or radiation, toxin intensity is 18.
A typical psionic intensity is 12
Usually the referee has a prepared intensity from the item, persona, or alien info.

== Saving Roll
Saving rolls are specialized attribute rolls where the players roll a die to protect their persona from damaging effects.
Saving rolls could easily be __rolled__ into the section on attribute rolls.
There is a long standing history of the saving throw in RPGs.
Saving rolls are EXP's variation on the historic saving throw versus radiation, poison or psionic attack.

NOTE: Saving rolls, saving throws and saves are interchangeable.

.*Saving Roll Checklist*
. <<_attack_type,Attack Type>>
** Determines attribute used for defence
. <<_target_value,Attack Intensity>>
. <<_make_the_roll,Make the Roll>>

== Attack Type
The attack type determines what is attacking the persona and what attribute defends against the attack. 
Almost all saving rolls involve Constitution (CON) and Mind (MND).
The player adds her persona's attribute score and EXPS Level to the 1d20 die roll.

.*Attribute Type For Saving Roll*
* Poisons use Constitution (CON)
* Radiations use Constitution (CON)
* Psionic attacks use Mind (MND) 

The persona's body will automatically work against these kinds of attacks.
The Constitution primarily defends against unseen attacks originating from the physical space.
A persona's Constitution will repel poisons and infections using her anatomical structures, immune system and hormonal defences.
The Mind primarily defends against unseen attacks originating from the think space. 
A persona's Mind will harden her consciousness against intrusions, psychic controls and existential threats.

=== Poison
Poisons are toxins that need to contact the persona for effect.
Poisons can be inhaled, ingested, or fondled.
Some poison attacks require a successful attack roll before they can harm the persona.
Poison attacks like a gaseous or area of effect attacks, cannot be avoided

Poisons can have specific effects if the player fails her saving roll.
A knock-out poison will knock the persona out.
A nausea poison will make the persona vomit.
A pharmaceutical effect poison will have the described pharmaceutical effect.
A lethal poison will kill the persona.

A killing poison inflicts damage depending on the intensity of the poison.
*A killing poison inflicts 1d4 per point of intensity of the poison.*
An intensity 18 killing poison will inflict 18d4 HPS of damage if the player fails her saving roll.
Pretty much lethal. 

The referee determines the intensity of the poison in advance.
Poisonous weapons usually have pre-determined intensities
Alien poisons may have an intensity related to the alien's Constitution. 
Alien poisons may increase their intensity by adding their EXPS Level to the intensity.
Lethal and killing poisons should have their intensity modified to reflect a fun game. 

Robots are unaffected by poisons that attack organic physiologic systems.
Electric shocks, corrosives and radiation have the same effect on aliens, anthros and robots.

=== Radiation
Radiation is an electromagnetic toxin that need not contact the persona to cause harm.
Radiation poison can be inhaled, ingested, or simply wash over the persona.
Radiation can also harm the persona if she gets too close.
Radiation is invisible and dangerous.
The distinct difference between poisons and radiation is that radiation can invisibly and secretly harm the persona.

Radiation affects all families equally. 
It smashes tissues, chromosomes and circuitry.
A radiation attack inflicts damage depending on its intensity.
*A radiation attack inflicts 1d4 per point of intensity of the radiation.*
An intensity 12 radiation attack would inflict 12d4 HPS of damage if the player misses her saving roll.
A successful saving roll reduces this damage by half. 
Radiation is deadly even if the player wins the saving roll for her persona.

EXP employs fantasy radiation, and fun replaces realism.
There is no radiation sickness, no thyroid cancer or bowel dysfunction. 
However, like all good sciency fiction radiation exposure, there is a chance of mutating.
The chance of mutating from radiation exposure is up to the referee and players.
Players that intentionally expose themselves to radiation cannot mutate. 

.*Radiation Mutation Exploitation*
. Involuntary damaging radiation exposure.
. A compelling story from the player why she should mutate.
. 1d1000 roll less than the damage inflicted by the exposure
. If step 3 is a win, then a chance to mutate as per persona type.
.. Robots do not mutate
.. Anthros jump to xref:anthros:mutation_check.adoc[Anthro Mutations].
.. Aliens jump to xref:aliens:evolutations.adoc[Alien Mutations]

NOTE: An alien that mutates due to an external force has a mutation, not an evolutation.

:art: knitevknites.png
:width: 350px
:snark: Alien knite vs anthro knite.
:artist: Unknown
:date: 1991
:license: CC BY-SA 4.0
:description: Two humanoid lizards locked in a psionic control battle.
include::ROOT:partial$articulate.adoc[]

=== Psionic
Psionic attacks are sciency fiction manipulations of the persona's mind or the physical space around the persona.
The psionic attack, mental attack, psychic attack, and thinkspace attack are all synonymous.
Psionic mutations deliver most psionic attacks.
Some machines carry out attacks that function similarly to psionic attacks. 

If the attack affects the persona's consciousness through the thinkspace, the player makes a saving roll.
Psionic attacks like  ESP, telekinesis, memory eradication and other direct attacks indicate a saving roll.
Psionic mutations that transform the environment around the persona do not get a saving roll.
Psionic attacks like gravity disruption, mental blast or lazer eyes and other indirect attacks indicate no saving roll.

The intensity of the psionic attack is equal to the attacker's Mind plus her EXPS Level. 

A successful saving roll against a psionic attack completely negates any effect.
There is no partial effect for mental attacks.
A failed saving roll subjects the persona to the details of the mental attack.
The persona may have her mind-controlled, muscles manipulated or lifted against her will.

== Attack Intensity
The more dangerous the attack, the higher the intensity and the higher the target value.
The player must roll higher than, or equal to, the target value or suffer the effects of the attack.
Most attacks have a designated attack intensity. 
A typical poison has an intensity of 18.
A psionic attack has an intensity equal to the attacker's MND. 
An typical psionic attack intensity would be 12.

.*Example Intensities*
* poison intensity listed with the weapon, grenade or pharma
* poison intensity based on the attacker's CON plus level.
* mental attack intensity based on attacker's Mind plus level

=== Target Value
.Target Value = Intensity of Attack
****
intensity of 15 indicates a target value of 15
****

== Make the Roll
The player must roll equal to or higher than the target value (intensity).
The player rolls a 1d20 and adds her EXPS Level and attribute type to the roll.

=== Saving Roll 
.Saving Roll = 1d20 + Attribute Type + EXPS Level
****
3rd level with 12 CON rolls 11. Her saving roll is 26.
****

If the intensity of the poison is 26 or less she is less affected or unaffected by the poison.

== Examples

include::uncombat:partial$saving_roll_examples.adoc[]