= Task Rolls

Task rolls are made by players when their persona is attempting something.
The task roll is a check for success. 
If the player wins the task roll, her persona has succeeded at the something.

Tasks can be mundane, like trying to repair a loose door knob.
Tasks are pure sciency fiction, like strapping a grommet-sized oscillating refractometer onto a Fredericton di-collating time re-modulator.
Tasks can be uncombat related like making a pie.
Tasks can be attempted in combat like trying to fight with two weapons at once. 
The list of tasks are infinite, and there is no list of them all for space reasons. 

It is expected that there will be a host of tasks that players call on frequently. 
These tasks are considered skills, however it is also expected that players will be making up tasks on the fly.
Some of these tasks may become skills. 
The goal of this section is to support a crunchy, but fun, way for personas to attempt mundane, weird and wonderful things. 

:art: monkey_box_anger.png
:width: 250px
:snark: Failure makes Rage.
:artist: Andrew Brechin
:date: 1990
:license: CC BY-SA 4.0
:description: Humanoid baboon getting mad at a technological box.
include::ROOT:partial$articulate.adoc[]

[discrete]
== TLDR
.Interests + Skills * 2 + Aptitude > Difficulty = Success
****
Research interest 1, Herbivore expertise 2, Biologist level 3 vs Difficulty 42 +
1d100 + Competency 8 must beat 42 to win when researching a herbivore,
****

== When to Task
Task rolls are for events that matter in the story.
It is not expected that players are checking to see if their personas can cross the street, toss a ball, or climb onto a chicken coop.
A task roll is expected if the success fail consequence has an impact on the story. 
This being said there are player conditions, such as inebriation or concussion, where __everything__ will require a task roll. 

== How to Task 
In short, the player must roll higher than the difficulty of the task on a 1d100.  

A task roll has a few steps. 
The first is to determine the Difficulty (DD) of the task at hand.
The second is the determine the Competency (Comp) of the persona attempting the task. 
The last is the make a roll on a 1d100. 
Rolling higher than the DD means the task is a success. 
Simple in theory a tad crunchier in practice.

.*Steps of a Task Rolls*
. <<_difficulty,Determine Difficulty>>
. <<_competency,Determine Competency>>
. <<_bonuses,Determine Bonuses>>
. <<_make_the_roll,Make the Roll>>

== Difficulty
The more complex something is the greater the Difficulty (DD).
If a task roll is indicated there will be a Difficulty associated with it.
The difficulty of the task is the number that the player must roll higher than on a 1d100.
In the vocation section there are many skills that are assigned a difficulty

NOTE: *Difficulty is shortened to DD for historical reasons and is an homage to Degree of Difficulty.*

While the lowest DD possible is 1 there is no limit to how high a DD can go.
However, the DD can be so high that it is impossible to win the Task Roll.
For example, cloning is a DD 200 task. 

include::uncombat:partial$task_difficulty.adoc[]

If a task does not exist or there is no assigned degree of difficulty, the players and referee must negotiate one.
The players and referee only need to agree on a qualitative term describing the difficulty of the task.
A dice roll will randomly determine the actual value of the DD.

Let's consider a persona that wants to make some ice from water.
If there is a freezer, this task should be automatic, but there may be some trivial interference.
So the referee and players agree that this is task has a trivial difficulty.
If there is no freezer, and the expedition is on a hot planet where the water is full of sediment, the difficulty should be impossible or bizarre.

For tasks that have an enormously high difficulty the players may find success by creating a task team, or a research team. 
A task team is for quick tasks where players can create a team competency that is larger than the single persona.
A research team is put together for a project that make take a long time with multiple attempts to complete (like cloning).

== Competency
The competency the bonus that the player adds to her 1d100 roll when trying to beat a task difficulty.

Competency is a combination of the persona's knowledge and aptitude.
Knowledge is a mixture of the persona's vocation interests and expertise.
Her aptitude reflects her persona's experience. 
A persona can use her EXPS Level for any task that fits within her vocation.
If the persona also has an applicable skill, she can add this to her Competency.

.Competency = Knowledge plus Aptitude

=== Knowledge 
The knowledge component of competency is reflected in the persona's interests and expertise. 
Interests are broad areas of knowledge that can be applied to many different tasks.
Expertise contributes more to competency, but has less applications. 
For example, and interest in research could assist any research related task roll.
However an expertise in pumpkins would only assist when the task involves pumpkins. 

A vocation is literally built on it's knowledge. 

=== Aptitude
Aptitude determines how much of the persona's experience level improves competency.
The higher the persona's level the more their competency improves.
However aptitude is limited by by tasks that one's vocation would carry out. 
A veterinarian would not be able to apply aptitude to tasks that are purely martial in nature. 
If the persona does not have aptitude in the task area they cannot have competence. 
Aptitude can be as simple as staying in your vocation's lane, or more nuanced.

include::uncombat:partial$task_aptitude_competency_multiplier.adoc[]

[discrete]
==== Stay In Your Lane
I can do that.

Often personas will want to accomplish a task that is not within the realm of their vocation.
Mercenaries often need the vet skills quick fix and stabilization.
A mechanic may want to to do spie stuff on a security system.

The cross vocation penalties are for individual personas trying to expand their scope of practice.
These degree of difficulty penalties are in addition to zeroing the skill score by lack of aptitude.
A Mechanic trying to use the knite gift energy would face a DD of 45 and have zero skill score (target roll of 236).
The same mechanic trying to use the nothing skill of righteous indignation would have a DD of 4-9 and zero skill score (target roll from 72 to 92).

include::uncombat:partial$task_vocation_lanes.adoc[]

== Bonuses
The player adds bonuses to her 1d100 roll.
Bonuses often mean the difference between success and failure.
Bonuses can come from every which way.
Some TOYs give task roll bonuses.
Some computers give task roll bonuses.
Many referees will offer task roll bonuses for good role-playing descriptions. 

:art: indiana_lizard.png
:width: 250px
:snark: This gonna be easy.
:artist: Patrick Redding
:date: 1990
:license: CC BY-SA 4.0
:description: Humanoid lizard wearing a beloved fedora about to lift a treasure artifact.
include::ROOT:partial$articulate.adoc[]

=== Attribute Bonuses
The most common bonuses are vocation attribute bonuses.
If the task fits into the vocation's aptitude, the player can add an attribute to the 1d100 roll.
For combat tasks, mercenaries can add their STR.
For knowledge-based tasks, biologists can add their INT. 

include::uncombat:partial$vocation_attribute_bonus.adoc[]

=== Role Playing Bonuses
The more role-playing is integrated into the roll playing system, the more fun the play is.
Role-playing bonuses for task rolls incentivize fun descriptions from the players. 
The following are examples of player descriptions that should earn task roll bonuses.
“I'm going to leaf through my notes here and try to identify this bizarre creature.” 
Or “I summon all the forces of evil beneath me, as I try to apply pressure to this weakling altruist.”
Or “Taking my favourite tools from my mechanical kit, I proceed to repair this damaged bicycle.”
Or “I  calmly stalk silently past the sleeping sentry.”

:art: vet_big_hat_idea_desat.png
:width: 250px
:snark: I have an idea.
:artist: StudioStoks, mod HM
:date: 2010
:license: StudioStoks Stock Art.
:description: Humanoid medical woman getting a brilliant idea.
include::ROOT:partial$articulate.adoc[]

The role-playing bonuses should be small since role-playing has its benefit.
A good description could get a 1d4 bonus.
A description that rocks all the players may get a 1d10 bonus. 
Small bonuses that lead to success generate quite a bit of excitement.

== Make the Roll
The player rolls the 1d100, adds in their competency and any bonuses and hopes to beat the task difficulty. 
Any roll equal to or higher than the difficulty is a success.
Any roll less than the difficulty is a failure.

:art: performance_roll_mecha_hammer.png
:width: 250px
:snark: Delicate repairs underway.
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0
:description: Small human hammering repairs on top of giant mech suit.
include::ROOT:partial$articulate.adoc[]


=== Examples
3rd level mechanic with repair interest of 3 and bomb expertise of 2 wants to defuse a bomb.
Competency is 10 (3 + 4 + 3), bonus 13 (DEX) for a plus 23 to the 1d100 roll.


6th level veterinarian with treatment interest of 4, burns expertise of 2 is treating a burn.
Competency is 20 (12 + 4 + 4), with an rpg bonus of 4 (making a Mr Burns joke) for a plus 24 to the 1d100 roll.

9th level mercenary with combat interest of 6, ambidextrous expertise of 2 and pistols expertise 2 wants to use two pistols at once.
Competency is 41 (27 + 6 + 8), bonus 11 (DEX) for a plus of 52 to the 1d100 roll. 

=== Success 
If the difficulty of the task is exceeded, or equalled, the persona reaps the reward of the successful task. 

=== Failure
EXP does not have partial successes.
If the player rolls less than the difficulty the task is a failure. 
If the player is extremely close to being successful the referee may allow the player to go for an role playing bonus. 

The consequences of a failure may be simple and apparent. 
A mercenary wanting to do ambidextrous combat fails their task roll they may revert to single weapon combat or suffer the dual wielding penalty.
A mechanic that fails at defusing a bomb may leave the bomb in an un-defused state or may detonate the bomb.
It is considered poor play to kill a persona outright for a failed task roll. 
An element of out of the frying pan into the fire consequence is more fun.

For most fail tasks the persona can try again later.
There is no particular indications for how much later. 
A combat related failed task, ambidextrous combat or grappling may have to wait until the end of combat or a new opponent.
A research related failed task may be delayed a day or may require replenishment of materiel. 
A failed enhancement of a persona's toy would only damage the toy in extreme circumstances. 
For example if the persona was trying to make an extreme modification to the toy. 

=== Critical Checks
Critical task rolls are not automatic successes but offer a huge bonus to the task roll. 
Rolling a natural 99 or 100 allows the player to add an additional 1d100 to the task roll. 
For more information jump to xref:uncombat:critical_checks.adoc[Critical Checks,window=_blank].

== Duration
I want it now!

The duration of a task depends on whether the duration matters or not.
If the personas are leisurely working on a project to improve the mercenary's shotgun the weeks may pass without event.
If a persona is trying to unlock a door while being chased by a combot then time is of the essence.
The duration of a task will be guided by the referee with the input of the table.

include::uncombat:partial$task_durations.adoc[]


