= Task Rolls

Task rolls are made by players when their persona is attempting something.
The task roll is a check for success. 
If the player wins the task roll, her persona has succeeded at the something.

Tasks can be mundane, like trying to repair a loose doorknob.
Tasks can be pure Sciency Fiction, like strapping a grommet-sized oscillating refractometer onto a Fredericton di-collating time re-modulator.
Tasks can be uncombat related, like making a pie.
Tasks can be combat related, like trying to fight with two weapons at once. 
The possible number of tasks is infinite, and there is no complete list of tasks. 

It is expected that there will be a host of tasks that players call on frequently. 
These tasks are the same as skills, but for simplicity we are calling everything a task. 
It is expected that players will make tasks up on the fly.
The goal of this section is to support a crunchy, but fun, way for personas to attempt mundane, weird and wonderful things. 



:art: monkey_box_anger.png
:width: 250px
:snark: Failure makes Rage.
:artist: Andrew Brechin
:date: 1990
:license: CC BY-SA 4.0
:description: Humanoid baboon getting mad at a technological box.
include::ROOT:partial$articulate.adoc[]

== When to Task
Task rolls are for events that matter in the story.
Players should not make task rolls to see if their personas can cross the street, toss a ball, or climb onto a chicken coop.
A task roll is used if the consequence has an impact on the story. 
There are player conditions, such as inebriation or concussion, where __everything__ will require a task roll. 

== How to Task 
In short, the player must roll equal to, or higher than, the difficulty of the task on a 1d100.

A task roll has a few steps. 
The first is to determine the Difficulty (DD) of the task.
The second is to determine the task roll bonus of the persona.
The third is to check for any adjustments that can be applied.
The last step is to make a roll on a 1d100. 
Rolling higher than, or equal to, the DD means the task is a success.
Simple in theory, a tad crunchier in practice.

[discrete]
== TLDR
.1d100 + Level Bonus + Interest Bonus + Expert Bonus &ge; Difficulty
****
3rd level, Interest 1, Expertise 2: Level Bonus = 3, Interest Bonus = 1, Expert Bonus = 6 +
1d100 + (3 + 1 + 6) must beat, or equal, 42 to win the task roll
****


.*Steps of a Task Roll*
. <<_difficulty, Determine Difficulty>>
.. DD is determined by the task or the referee
. <<_level_bonus, Determine Level Bonus>>
.. Always applied. Higher the EXPS Level the higher the bonus
. <<_interest_bonus, Determine Interest Bonus>>
.. Generally applied. Higher the interest score the higher the bonus
. <<_expert_bonus, Determine Expert Bonus>>
.. Specifically applied. Combination of EXPS Level and expertise score.
. <<_make_the_roll, Make the Roll>>

== Difficulty
The more complex something is the greater the Difficulty (DD).
If a task roll is indicated there will be a difficulty associated with it.
The difficulty of the task is the number that the player must roll higher than (or equal to) on a 1d100.
In the vocation section there are many common tasks that have assigned difficulties.

NOTE: *Difficulty is shortened to DD for historical reasons (Degree of Difficulty).*

While the lowest DD possible is 1, there is no limit to how high a DD can go.
A difficulty can become so high that a single persona cannot succeed at the task.
For example, cloning is a DD 200 task and cloning requires a team to be successful. 

include::uncombat:partial$task_difficulty.adoc[]

If a task does not exist, or there is no assigned difficulty, the players and referee must negotiate one.
The players and referee only need to agree on a qualitative term describing the difficulty of the task.

Let's consider a persona that wants to make some ice from water.
If there is a freezer, this task should be automatic, but there may be some trivial interference.
So the referee and players agree that this task has a trivial difficulty.
If there is no freezer, and the expedition is on a hot planet where the water is full of sediment, the difficulty could be impossible or bizarre.

For tasks that have an enormously high difficulty the players may find success by us teamwork or create a project. 
Teamwork allows a few personas to work together to improve the chance of beating the difficulty.
A project enlists a research team for complex tasks that take a long time. 
For more information, jump to xref:uncombat:task_rolls_projects.adoc[Projects,window=_blank, rel="noopener noreferrer"], or <<_teamwork, Teamwork>>.

== Level Bonus
The level bonus is added to any task roll that the persona makes.
Previously called the experience bonus the level bonus reflects the total life experience that the persona has.
The higher the experience level (EXPS Level) the higher the Level Bonus

include::uncombat:partial$level_bonus_table.adoc[]

A 4th level mercenary attempted to quick load her batteries would get a +4 Level bonus.
She could also use the level bonus when trying to do tasks outside of her vocation, like finding shelter.

== Interest Bonus
The interest bonus is very general and the player should be able to find some interest to apply to their task roll.
The interest bonus is equal to the interest score that the persona has.
For example, if the mercenary above had Combat Interest 3 she would get +3 on her combat related task rolls.
So her total bonus for a quick load of batteries would be LeveL Bonus plus Interest Bonus +7.
Interest bonuses are very loosely applied and the persona would need to be well outside her vocation to not have one apply.

[discrete]
== Interest Bonus
.Interest Bonus = Interest Score
****
A persona with a tactical interest of 3 would get an Interest Bonus of +3 on anything remotely tactical.
****


=== Interests
Every vocation has 3 core interests that represent general knowledge that helps the persona win task rolls.
Areas of interest are broad and can be applied quite easily to a task.
There should always be an applicable interest for the player to use. 
For each interest the player adds 1 point to the 1d100 roll.
So a biologist with Research 3 would get to add 3 to her task roll.

== Expert Bonus
The expert bonus is very specific, and the player must have an expertise score before the bonus can be added.
The expert bonus is equal to the expertise score times her EXPS Level.
An expertise bonus can get very large and represents what the persona is really good at.

[discrete]
== Expert Bonus
.Expert Bonus = Expertise Score * EXPS Level
****
3rd level and aerosol expertise 3 would get an Expert Bonus of +9 on aerosol related tasks.
****

=== Expertise
Every vocation has areas of expertise that are part of the persona's knowledge.
An area of expertise is more focused than an area of interest. 
It is possible that an area of expertise will not be applicable to a task.

== Adjustments
Adjustments are added to the roll for the fun of the game.
The player adds adjustments to her 1d100 roll.
Adjustments often mean the difference between success and failure.
Adjustments can come from every which way.
Some TOYs give task roll adjustments.
Some computers give task roll adjustments.
Many referees will offer task roll adjustments for good role-playing descriptions.

:art: indiana_lizard.png
:width: 250px
:snark: This gonna be easy.
:artist: Patrick Redding
:date: 1990
:license: CC BY-SA 4.0
:description: Humanoid lizard wearing a beloved fedora about to lift a treasure artifact.
include::ROOT:partial$articulate.adoc[]

=== Stay In Your Lane
I can do that.

Often personas will want to accomplish a task that is not within the realm of their vocation.
Mercenaries often need the vet tasks like quick fix and stabilization.
A mechanic may want to do spie stuff on a security system.
It is completely reasonable for a referee to disallow unrealistic task roll attempts that injure the story.
A mechanic who wants to use the easy (12 DD) knite task of Kirlian sight should just be told no.
The following is an unnecessary arithmetic demonstration as to why.

include::uncombat:partial$task_vocation_lanes.adoc[]

=== Attribute Adjustments
The most common adjustments are vocation attribute adjustments.
If the task fits into the vocation's aptitude, the player can add an attribute to the 1d100 roll.
For combat tasks, mercenaries can add their STR.
For knowledge-based tasks, biologists can add their INT.

include::uncombat:partial$vocation_attribute_bonus.adoc[]

=== Role Playing Adjustments
The more role playing is integrated into the Roll Playing system, the more fun the play is.
Role playing adjustments for task rolls incentivize fun descriptions from the players.
The following are examples of player descriptions that should earn task roll bonuses.
“I'm going to leaf through my notes here and try to identify this bizarre creature.” 
Or “I summon all the forces of evil beneath me, as I try to apply pressure to this weakling altruist.”
Or “Taking my favourite tools from my mechanical kit, I proceed to repair this damaged bicycle.”
Or “I calmly stalk silently past the sleeping sentry.”

:art: vet_big_hat_idea_desat.png
:width: 250px
:snark: I have an idea.
:artist: StudioStoks, mod HM
:date: 2010
:license: StudioStoks Stock Art.
:description: Humanoid medical woman getting a brilliant idea.
include::ROOT:partial$articulate.adoc[]

The role-playing bonuses should be small since role-playing has its benefit.
A good description could get a 1d4 bonus.
A description that rocks all the players may get a 1d10 bonus. 
Small bonuses that lead to success generate quite a bit of excitement.

== Task Roll Examples
The player rolls the 1d100, adds their Bonuses and applicable adjustments and hopes to beat the task difficulty.
Any roll equal to or higher than the difficulty is a success.
Any roll less than the difficulty is a failure.

:art: performance_roll_mecha_hammer.png
:width: 250px
:snark: Delicate repairs underway.
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0 
:description: Small human hammering repairs on top of a giant mech suit.
include::ROOT:partial$articulate.adoc[]

* 3rd level mechanic with repair interest of 3 and bomb expertise of 2 wants to defuse a bomb.
** Level Bonus +3
** Interest Bonus +3
** Expertise Bonus +6
** Role Playing adjustment for detailed description of green vs blue wire +2
*  1d100 + 14 vs defuse simple bomb, difficulty of 42 (normal).

* 6th level veterinarian with treatment interest of 4, burns expertise of 2 is treating a burn.
** Level Bonus +12
** Interest Bonus +4
** Expert Bonus +12
** No adjustments were applied
* 1d100 + 28 vs treat simple burn, difficulty of 24 (Easy)

* 9th level mercenary with combat interest of 6, ambidextrous expertise of 2 wants to use two pistols at once.
** Level Bonus +27
** Interest Bonus +6
** Expert Bonus +18
** Attribute Adjustment DEX of 11
* 1d100 + 62 vs ambidextrous pistols, difficulty of 24 (Easy). Can overcome negative adjustments.

=== Success 
If the difficulty of the task is exceeded, or equalled, the persona reaps the reward of the successful task. 

=== Failure
EXP does not have partial successes.
If the player rolls less than the difficulty the task is a failure.

The consequences of a failure may be simple and apparent. 
A mercenary failing at ambidextrous combat may revert to single weapon combat, or suffer the dual wielding penalty.
A mechanic that fails at defusing a bomb may leave the bomb in an undefused state, or may detonate the bomb.
*It is considered rude to kill a persona outright for a failed task roll.*
An element of out of the frying pan into the fire consequence is more fun.

For most failed tasks the persona can try again later.
There is no particular indication for how much later. 
A combat related failed task, like grappling may have to wait until the next opponent.
Research related failed tasks may be delayed a day or may require replenishment of materiel. 
A failed enhancement of a persona's toy would only damage the toy in extreme circumstances. 
For example if the persona was trying to make an extreme modification to the toy.

[discrete]
==== Really Close to Success
If the player's roll is very close to a success the referee may elect to allow the player a role playing adjustment.
This is done purely for drama and fun.
The player does not get to roll again but may add a 1d4 or 1d10 depending on what the table thinks of their description.
This is optional and should be done for fun once in a while, or for important rolls that are dramatically close.

=== Critical Checks
Critical task rolls are not automatic successes but offer a huge bonus to the task roll. 
Rolling a natural 99 or 100 allows the player to add an additional 1d100 to the task roll. 
For more information, jump to xref:uncombat:critical_checks.adoc[Critical Checks,window=_blank, rel="noopener noreferrer"].

== Duration
I want it now!

The duration of a task depends on whether the duration matters or not.
If the personas are leisurely working on a project to improve the mercenary's shotgun the weeks may pass without event.
If a persona is trying to unlock a door while being chased by a combot then time is of the essence.
The duration of a task will be guided by the referee with the input of the table.

include::uncombat:partial$task_durations.adoc[]

== Teamwork
Personas can work together to make a success more likely. 
This requires a task that can be shared between personas.
Reflex task rolls like dodging or ambidextrous combat usually cannot be shared. 

Teamwork is for simple, brief tasks that are not projects. 
A merc and mechanic may work together to breach a door.
A biologist and a nomad may work together to find a warren. 
Two veterinarians may work together to stabilize an injured anthro.

.*Teamwork Making the Dream Work*
. Maximum of three team members
. *Lowest two total task roll bonuses* are combined
. Each player gets to make a task roll

Teamwork can improve the chance of success by combining the two lowest total task roll bonuses, and up to three players can roll.
Consider a mercenary with a task roll bonus of 11 and a mechanic with a task roll bonus of 16 trying to breach a door.
Both players can try and beat the difficulty with a 1d100 roll plus 27. 
That means two rolls with an improved bonus. 
If a spie with task roll bonus 21 decided to help out the merc and mech the bonus would remain 27.
However, three players can roll, but the bonus is still only 27.
This is a "too many cooks spoil the broth" situation. 

A research team is different from teamwork. 
A research team can have any number of personas involved, and they work on a project.
For more Byzantine complicated shenanigans, jump to xref:uncombat:task_rolls_projects.adoc[Project]

