= Task Rolls

Task rolls are made by players when their persona is attempting something.
The task roll is a check for success. 
If the player wins the task roll, her persona has succeeded at the something.

Tasks can be mundane, like trying to repair a loose doorknob.
Tasks can be pure Sciency Fiction, like strapping a grommet-sized oscillating refractometer onto a Fredericton di-collating time re-modulator.
Tasks can be uncombat related, like making a pie.
Tasks can be combat related, like trying to fight with two weapons at once. 
The possible number of tasks is infinite, and there is no complete list of tasks. 

It is expected that there will be a host of tasks that players call on frequently. 
These tasks are the same as skills, but for simplicity we are calling everything a task. 
It is expected that players will make tasks up on the fly.
The goal of this section is to support a crunchy, but fun, way for personas to attempt mundane, weird and wonderful things. 



:art: monkey_box_anger.png
:width: 250px
:snark: Failure makes Rage.
:artist: Andrew Brechin
:date: 1990
:license: CC BY-SA 4.0
:description: Humanoid baboon getting mad at a technological box.
include::ROOT:partial$articulate.adoc[]

== When to Task
Task rolls are for events that matter in the story.
Players should not make task rolls to see if their personas can cross the street, toss a ball, or climb onto a chicken coop.
A task roll is used if the consequence has an impact on the story. 
There are player conditions, such as inebriation or concussion, where __everything__ will require a task roll. 

== How to Task 
In short, the player must roll higher than the difficulty of the task on a 1d100.  

A task roll has a few steps. 
The first is to determine the Difficulty (DD) of the task.
The second is to determine the Competency (knowledge plus level bonus) of the persona.
The third is to check for any bonuses that can be applied.  
The last step is to make a roll on a 1d100. 
Rolling higher than the DD means the task is a success. 
Simple in theory, a tad crunchier in practice.

[discrete]
== TLDR
.1d100 + Interests + Expertise + Experience &ge; Difficulty
****
Interests 1, Expertise 2, Level 3 + 
1d100 + (1 + 6 + 3) must beat 42 to win the task roll
****


.*Steps of a Task Roll*
. <<_difficulty, Determine Difficulty>>
. <<_competency, Determine Competency>>
.. <<_interests, Interests>>
.. <<_expertise, Expertise>>
.. <<_Experience, Experience>>
. <<_bonuses, Bonuses>>
. <<_make_the_roll, Make the Roll>>

== Difficulty
The more complex something is the greater the Difficulty (DD).
If a task roll is indicated there will be a difficulty associated with it.
The difficulty of the task is the number that the player must roll higher than on a 1d100.
In the vocation section there are many common tasks that have assigned difficulties.

NOTE: *Difficulty is shortened to DD for historical reasons (Degree of Difficulty).*

While the lowest DD possible is 1, there is no limit to how high a DD can go.
A difficulty can become so high that a single persona cannot succeed at the task.
For example, cloning is a DD 200 task and cloning requires a team to be successful. 

include::uncombat:partial$task_difficulty.adoc[]

If a task does not exist, or there is no assigned difficulty, the players and referee must negotiate one.
The players and referee only need to agree on a qualitative term describing the difficulty of the task.

Let's consider a persona that wants to make some ice from water.
If there is a freezer, this task should be automatic, but there may be some trivial interference.
So the referee and players agree that this task has a trivial difficulty.
If there is no freezer, and the expedition is on a hot planet where the water is full of sediment, the difficulty could be impossible or bizarre.

For tasks that have an enormously high difficulty the players may find success by us teamwork or create a project. 
Teamwork allows a few personas to work together to improve the chance of beating the difficulty.
A project enlists a research team for complex tasks that take a long time. 
For more information, jump to xref:uncombat:task_rolls_projects.adoc[Projects,window=_blank], or <<_teamwork, Teamwork>>.



== Competency
Competency is a collective term for the knowledge bonuses that the player adds to her 1d100 roll.

Competency is a combination of the persona's knowledge and experience.
Knowledge is a mixture of the persona's vocation interests and expertise.
Her aptitude reflects her persona's experience. 
A persona can use her EXPS Level for any task that fits within her vocation.

The knowledge component of competency is reflected in the persona's interests and expertise. 
Interests are broad areas of knowledge that can be applied to many different tasks.
Expertise is more specific, but contributes more to the roll when applicable.
For example, an interest in research could assist any research related task roll.
However, an expertise in pumpkins would only assist when the task involves pumpkins. 

[discrete]
== Competency
Interests + Expertise + Experience
****
Interests add +1 per interest +
Expertise add EXPS level per expertise +
Experience add amount from table below
****

=== Interests
Every vocation has 3 core interests that represent general knowledge that helps the persona win task rolls.
Areas of interest are broad and can be applied quite easily to a task.
There should always be an applicable interest for the player to use. 
For each interest the player adds 1 point to the 1d100 roll.
So a biologist with Research 3 would get to add 3 to her task roll.

=== Expertise
Every vocation has areas of expertise that are part of the persona's knowledge.
An area of expertise is more focused than an area of interest. 
It is possible that an area of expertise will not be applicable to a task.
The player adds their EXPS level for each point of expertise.
So a 1st level biologist with herbivore-2 could add 2 to her task roll, but at 3rd level she can add 6. 

=== Experience
The persona's EXPS level impacts the task roll. 
The player can always add their persona's experience bonus to the task roll. 
At higher levels the experience bonus may overshadow both interests and expertise.
The higher the persona's level the more their competency improves.

Employing the below table: 
* a 3rd level persona would add 3 to any task roll
* a 5th level persona would add 10 to any task roll

include::uncombat:partial$task_aptitude_competency_multiplier.adoc[]

There are limitations to the experience bonus.
If the persona does not have aptitude in the task area they cannot have competence. 
Aptitude can be as simple as staying in your vocation's lane, or more nuanced.

[discrete]
==== Stay In Your Lane
I can do that.

Often personas will want to accomplish a task that is not within the realm of their vocation.
Mercenaries often need the vet skills quick fix and stabilization.
A mechanic may want to do spie stuff on a security system.
It is completely reasonable for a referee to disallow unrealistic task roll attempts that injure the story.
A mechanic who wants to use the easy (12) knite skill of Kirlian sight should just be told no.
The following is an unnecessary arithmetic demonstration as to why. 

The competency for the persona is zero, and the penalty from the table is also added.
A mechanic trying to use the knite skill Kirlian sight would have to roll 154 on 1d100 with no bonuses.
The same mechanic trying to use the nothing skill of righteous indignation (42) have to beat 84 on the 1d100.

include::uncombat:partial$task_vocation_lanes.adoc[]

== Bonuses
Bonuses are added to the roll for the run of the game, and are unrelated to competency.
The player adds bonuses to her 1d100 roll.
Bonuses often mean the difference between success and failure.
Bonuses can come from every which way.
Some TOYs give task roll bonuses.
Some computers give task roll bonuses.
Many referees will offer task roll bonuses for good role-playing descriptions.

:art: indiana_lizard.png
:width: 250px
:snark: This gonna be easy.
:artist: Patrick Redding
:date: 1990
:license: CC BY-SA 4.0
:description: Humanoid lizard wearing a beloved fedora about to lift a treasure artifact.
include::ROOT:partial$articulate.adoc[]

=== Attribute Bonuses
The most common bonuses are vocation attribute bonuses.
If the task fits into the vocation's aptitude, the player can add an attribute to the 1d100 roll.
For combat tasks, mercenaries can add their STR.
For knowledge-based tasks, biologists can add their INT.

include::uncombat:partial$vocation_attribute_bonus.adoc[]

=== Role-Playing Bonuses
The more role-playing is integrated into the roll playing system, the more fun the play is.
Role-playing bonuses for task rolls incentivize fun descriptions from the players.
The following are examples of player descriptions that should earn task roll bonuses.
“I'm going to leaf through my notes here and try to identify this bizarre creature.” 
Or “I summon all the forces of evil beneath me, as I try to apply pressure to this weakling altruist.”
Or “Taking my favourite tools from my mechanical kit, I proceed to repair this damaged bicycle.”
Or “I calmly stalk silently past the sleeping sentry.”

:art: vet_big_hat_idea_desat.png
:width: 250px
:snark: I have an idea.
:artist: StudioStoks, mod HM
:date: 2010
:license: StudioStoks Stock Art.
:description: Humanoid medical woman getting a brilliant idea.
include::ROOT:partial$articulate.adoc[]

The role-playing bonuses should be small since role-playing has its benefit.
A good description could get a 1d4 bonus.
A description that rocks all the players may get a 1d10 bonus. 
Small bonuses that lead to success generate quite a bit of excitement.

== Make the Roll
The player rolls the 1d100, adds their competency and extra bonuses and hopes to beat the task difficulty. 
Any roll equal to or higher than the difficulty is a success.
Any roll less than the difficulty is a failure.

:art: performance_roll_mecha_hammer.png
:width: 250px
:snark: Delicate repairs underway.
:artist: Patrick Redding
:date: 1991
:license: CC BY-SA 4.0 
:description: Small human hammering repairs on top of a giant mech suit.
include::ROOT:partial$articulate.adoc[]


=== Examples
3rd level mechanic with repair interest of 3 and bomb expertise of 2 wants to defuse a bomb.
Competency is 12 (3 + 6 + 3), bonus 13 (DEX) for a plus 26 to the 1d100 roll.

6th level veterinarian with treatment interest of 4, burns expertise of 2 is treating a burn.
Competency is 28 (4 + 12 + 12), with a role-playing bonus of 4 (making a Mr Burns joke) for a plus 32 to the 1d100 roll.

9th level mercenary with combat interest of 6, ambidextrous expertise of 2 and pistols expertise 2 wants to use two pistols at once.
Competency is 69 (6 + 36 + 27), bonus 11 (DEX) for a bonus of 80 to the 1d100 roll. 

=== Success 
If the difficulty of the task is exceeded, or equalled, the persona reaps the reward of the successful task. 

=== Failure
EXP does not have partial successes.
If the player rolls less than the difficulty the task is a failure. 
If the player is extremely close to being successful the referee may allow the player to go for a role-playing bonus. 

The consequences of a failure may be simple and apparent. 
A mercenary failing at ambidextrous combat may revert to single weapon combat, or suffer the dual wielding penalty.
A mechanic that fails at defusing a bomb may leave the bomb in an undefused state, or may detonate the bomb.
*It is considered poor play to kill a persona outright for a failed task roll.*
An element of out of the frying pan into the fire consequence is more fun.

For most failed tasks the persona can try again later.
There is no particular indication for how much later. 
A combat related failed task, like grappling may have to wait until the next opponent.
Research related failed tasks may be delayed a day or may require replenishment of materiel. 
A failed enhancement of a persona's toy would only damage the toy in extreme circumstances. 
For example if the persona was trying to make an extreme modification to the toy. 

=== Critical Checks
Critical task rolls are not automatic successes but offer a huge bonus to the task roll. 
Rolling a natural 99 or 100 allows the player to add an additional 1d100 to the task roll. 
For more information, jump to xref:uncombat:critical_checks.adoc[Critical Checks,window=_blank].

== Duration
I want it now!

The duration of a task depends on whether the duration matters or not.
If the personas are leisurely working on a project to improve the mercenary's shotgun the weeks may pass without event.
If a persona is trying to unlock a door while being chased by a combot then time is of the essence.
The duration of a task will be guided by the referee with the input of the table.

include::uncombat:partial$task_durations.adoc[]


== Teamwork
Personas can work together to make a success more likely. 
This requires a task that can be shared between personas.
Reflex task rolls like dodging or ambidextrous combat usually cannot be shared. 

Teamwork is for simple, brief tasks that are not projects. 
A merc and mechanic may work together to breach a door.
A biologist and a nomad may work together to find a warren. 
Two veterinarians may work together to stabilize an injured anthro.

.*Teamwork Making the Dream Work*
. Maximum of three team members
. *Lowest two competencies* are combined
. Each player gets to make a task roll

Teamwork can improve the chance of success by combining the two lowest competencies, and up to three players can roll.
Consider a mercenary with a competency of 11 and a mechanic with a competency of 16 trying to breach a door.
Both players can try and beat the difficulty with a 1d100 roll plus 27. 
That means two rolls with an improved bonus. 
If a spie with competency 21 decided to help out the merc and mech the bonus would remain 27.
However, three players can roll, but the bonus is still only 27.
This is a "too many cooks spoil the broth" situation. 

A research team is different from teamwork. 
A research team can have any number of personas involved, and they work on a project.
For more Byzantine complicated shenanigans, jump to xref:uncombat:task_rolls_projects.adoc[Project]

