= Projects

Research teams allow groups of personas to pool their experience skills for a greater chance of success.
Several mechanics may share their expertise to solve a scientific problem or repair a broken warp drive.
A  team of veterinarians could work together to save a life.
The skill score of a research team is the sum of the skill scores of all its members.
Every player with a persona on the research team gets to make a task roll using the team's combined skill score.
If any of the players win their task roll, then the entire team is successful.

:art: research_team_biovet.png
:width: 300px
:snark: Biologist and vet working together.
:artist: Kelly Freas
:date: 1957
:license: CC BY-SA 4.0
:description: Drawing of two humans working together on delicate project.

include::ROOT:partial$articulate.adoc[]

== Composition
Every research team must have a team leader.
The EXPS Level of the team leader determines the size of the research team.
The team can consist of one persona per level of the team leader in addition to themselves.
A team leader cannot lead a persona with a higher EXPS level than herself.

For example, a 5th level veterinarian could lead a team of 5 veterinarians.
That could be a combined research team of skill score 30 with five five task rolls.
Teams can accomplish amazing things.
However, teams cannot get together to solve intricate campaign puzzles created by the referee.
As always, plot points are dice roll resistant.

:art: alien_research_team.png
:width: 300px
:snark: Research teams can be technical and cute.
:artist: JEShields
:date: 2016-2021
:license: Copyright JEShields Stock Art. jeshields.com
:description: 

include::ROOT:partial$articulate.adoc[]

A team can be composed of different vocations.
The players must justify each vocation type's involvement on the research team.
For example, a 7th level biologist could lead a team of 5 biologists, a mercenary, and a spie.
If the research team was trying to determine the chance of alien revolution, this team makes sense.
If the research team were trying to determine the direction of alien migration, including the spie and mercenary would not make sense.

== Example
An operating room research team has a 4th level veterinarian team leader.
The team comprises two 3rd level vets, a 3rd level biologist and a 2nd level nomad.
They are working together to fix a famous alien the expedition accidentally ran over with a hovercar.
They need to repair her articulated wing flaps. 
The Degree of Difficulty of the procedure is 20DD.

The research team's total skill score is 15 (4 + 3 + 3 + 3 + 2).

Each team member would get a chance to beat the Target Roll of 76.
The procedure is a success if any of the five players roll 76 or higher.

== Task Duration
How long a task takes depends on a combination of common sense and degree of difficulty (DD).
Some tasks have specifically assigned durations.
Performing open-heart surgery (a difficult task) would always take longer than ten minutes.
However, the equally difficult task of performing a double somersault would take an instant.

Combat-related tasks happen during the unit of combat unless otherwise specified.
Research teamwork that requires months can pass in an instant with a few task rolls.

include::uncombat:partial$task_durations.adoc[]

A persona carrying out a 4 DD task would require 0-99 units of time.
At the end of which, the player would make her task roll.
Most of the time, this duration information is a nerd fascination.
If time is not of the essence, then don't play on this table. 
During combat time, these durations may be critical.
Outside of combat time, the task durations pass instantly.

A biologist trying to identify an alien species could take up to 3 minutes to make a decision.
The duration reflects the time she spent leafing through her notes and observing before making a decision.

A mercenary attempting pistol with pistol ambidextrous combat would have no such time duration, and success, or failure, is instantaneous.

NOTE: *A task roll is won in an instant, but the research and prep may take months.*

Research teams should always check for the duration of tasks. 
A task that takes months to complete could be reflected in gameplay with sub-missions to get materials or other team members.