= Vocation Tasks
This list is not exhaustive. 
The most common kinds of tasks encountered play testing EXP for a decade are listed here.
Many are silly. 

Successful Task Rolls are granular and represent dice rolls that change a session, not a campaign.
As with all dice rolls in the Roll Playing System, a successful task should not change a campaign's course.
Plot points are highly resistant to dice rolls. 

IMPORTANT: *These tables are not exhaustive.*

== General 
General tasks represent day-to-day things that personas may want to do.
Under normal circumstances, there should be no task roll required for these actions.
The referee would need some fun excuse to force the player to make a task roll.
If a persona needs to bake a cake for her dessert, she should simply bake a cake.
If the persona is baking a cake to impress an alien dignitary, then a task roll is part of the fun.
If the persona needs to bake a cake after drinking a https://en.wikipedia.org/wiki/Zaphod_Beeblebrox#Pan-Galactic_Gargle_Blaster[uncombat:task_rolls.adoc], then a task roll is part of the fun.

include::uncombat:partial$general_tasks.adoc[]

== Biologist
include::vocations:partial$biologist_tasks.adoc[]

== Knite
Only a knite can accomplish knite tasks. 
include::vocations:partial$knite_tasks.adoc[]

== Mechanic
include::vocations:partial$mechanic_tasks.adoc[]

== Mercenary
include::vocations:partial$mercenary_tasks.adoc[]

== Nomad
include::vocations:partial$nomad_tasks.adoc[]

== Nothing
Other vocations have little or no concept of these irrelevant skills.
include::vocations:partial$nothing_tasks.adoc[]

== Spie Tasks
include::vocations:partial$spie_tasks.adoc[]

== Veterinarian
include::vocations:partial$veterinarian_tasks.adoc[]